### ISSUE TITLE
Space Packing Algorithm (Again!) 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1002]
Do you reckon this was done manually or using Algorithm?
http://www.designboom.com/design/rafael-esquer-iconic-new-york-illuminated-alfalfa-studio-11-28-2016/

Do you recall anything similar for packing UV or maybe in Processing? 

Every now and then I always want this feature. Both 2D or 3D packing that pushes boundary of each separate elements, so that no overlapping happens.

I will try Houdini if this is a bit too advanced level.

**Comment by nortikin** [comment]
think it is manual

**Comment by nortikin** [comment]
packing is advanced anyway. we have no such algorythm yet.

**Comment by enzyme69** [comment]
Ok, that's one day wishlist. Cheers.
