### ISSUE TITLE
Extra Objects Hacking

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1003]
I wonder if Sverchok can use Extra Objects, but kind of retain the ability to change the shape?

![screen shot 2016-11-30 at 19 29 01](https://cloud.githubusercontent.com/assets/3952687/20745041/6ffcb5a6-b733-11e6-9b18-7c9ca9e06f92.png)

Each one of them can be node if we have all the time, like I might try to make Script Node. 

But can one actually just use the command and have ability to update the mesh. Not once off.

**Comment by enzyme69** [comment]
I want to test this command using SN Lite:
bpy.ops.mesh.curveaceous_galore(ProfileType='Splat', outputType='NURBS', shape='2D', use_cyclic_u=True, order_u=2, MiscCurveType=2, outerRadius=2.14, arcSides=28, endAngle=90.9, arcType=3, Nsides=8, splatSides=23, splatScale=1.03, seed=156, basis=11)

**Comment by zeffii** [comment]
Once you call that line, the `curvaceaceous_galore` operator is finished. I'm not aware that the Extra Objects operators are designed to let you modify properties after the operator has `{'FINISHED'}'.  (unlike primitives in 3dmax for instance, which are editable until converted to mesh). 

Calling that operator repeatedly with different values from python, will simply generate a new object each time.

**Comment by enzyme69** [comment]
@zeffii I am testing SN Lite with Extra Objects.

This is weird, does not work if I plug an input. However, sliding the seed will generate a new object each time. Any advice to do this more elegantly?

https://gist.github.com/837d48bcb6147e7f337109bbdd699528

![screen shot 2016-11-30 at 20 55 38](https://cloud.githubusercontent.com/assets/3952687/20747746/5fe0b9ae-b73f-11e6-9c8d-4b0986586ee7.png)

**Comment by zeffii** [comment]
use n=2

**Comment by enzyme69** [comment]
Wait the minute, now nothing works. Changing seed does not trigger the script anymore ....

**Comment by enzyme69** [comment]
@zeffii I changed the nestedness to n=2 and started to get something. The effect is generating new shape each time. Not bad of setup for experimentation. Will generate something.

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 21 03 18](https://cloud.githubusercontent.com/assets/3952687/20747981/70de1c32-b740-11e6-8583-078ea5ddc9c8.png)

**Comment by zeffii** [comment]
read https://github.com/nortikin/sverchok/issues/1003#issuecomment-263827883 slower

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 21 13 39](https://cloud.githubusercontent.com/assets/3952687/20748339/e1cf6332-b741-11e6-9872-2871f8f6c7ee.png)

Random is nice, but soon wanting to "replace" existing data or generate new on command.

**Comment by enzyme69** [comment]
Ok got it so the script was not made in a way that the object can be revisited and modified.

**Comment by zeffii** [comment]
> Ok got it so the script was not made in a way that the object can be revisited and modified.

yep, like most operators. Worth reading the source anyway.

**Comment by enzyme69** [comment]
Where to find the source for Extra Objects?

**Comment by enzyme69** [comment]
Ook got it will check. Cheers~
