### ISSUE TITLE
Extra Objects into Script Nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1005]
Originally I was asking a trivial question: Why can't we have these Extra Objects operators as Node and can't it be live and auto update the generation at any time? 
https://github.com/nortikin/sverchok/issues/1003

- [x] FlowerCurve
- [x] CogCurve
- [ ] NSideCurve
- [x] SplatCurve
- [x] HelixCurve
- [ ] ArcCurve

I am attempting to just copy pasting the python code, credit to original authors of this Extra Curves Add-On.

🐌

'''
bl_info = {
    "name": "Curveaceous Galore!",
    "author": "Jimmy Hazevoet, testscreenings",
    "version": (0, 2),
    "blender": (2, 59, 0),
    "location": "View3D > Add > Curve",
    "description": "Adds many different types of Curves",
    "warning": "", # used for warning icon and text in addons panel
    "wiki_url": "http://wiki.blender.org/index.php/Extensions:2.6/Py/"
                "Scripts/Curve/Curves_Galore",
    "category": "Add Curve",
}
'''

**Comment by enzyme69** [comment]
This makes FlowerCurve points.

```
def sv_main(petals=8, innerradius=0.5, outerradius=1.0, petalwidth=2.0):

    in_sockets = [
        ['s', 'Petals',  petals],
        ['s', 'Inner Radius',  innerradius],
        ['s', 'Outer Radius',  outerradius],
        ['s', 'Petal Width',  petalwidth]
    ]

    from math import sin, cos, radians, pi, sqrt
    from mathutils import Vector, Euler


    #Verts = []
    #verts_new = Verts.append

    newpoints = []
    
    step = (2.0/(petals))
    pet = (step/pi*2)*petalwidth
    i = 0
    while i < petals:
        t = (i*step)
        x1 = cos(t*pi-(pi/petals))*innerradius
        y1 = sin(t*pi-(pi/petals))*innerradius
        newpoints.append([x1, y1, 0])
        x2 = cos(t*pi-pet)*outerradius
        y2 = sin(t*pi-pet)*outerradius
        newpoints.append([x2, y2, 0])
        x3 = cos(t*pi+pet)*outerradius
        y3 = sin(t*pi+pet)*outerradius
        newpoints.append([x3, y3, 0])
        i += 1
        

        
    out_sockets = [
        ['v', 'Verts', [newpoints]]
    ]

    return in_sockets, out_sockets
```

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 21 47 24](https://cloud.githubusercontent.com/assets/3952687/20749677/648960a2-b747-11e6-8b2b-6480c68048df.png)

**Comment by enzyme69** [comment]
@zeffii Any tips to vectorize node like above?

**Comment by enzyme69** [comment]
A quick hack is to Monad it 💃 

![screen shot 2016-11-30 at 21 58 50](https://cloud.githubusercontent.com/assets/3952687/20749873/391b5762-b748-11e6-87c8-c32671a1bf88.png)

**Comment by zeffii** [comment]
before you expend too much energy you _can_ import these functions directly from the source
```
"""
in petals       s d=8    n=2 
in innerradius  s d=0.5  n=2 
in outerradius  s d=1.0  n=2
in petalwidth   s d=2.0  n=2
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
points = FlowerCurve(petals, innerradius, outerradius, petalwidth)

```

**Comment by enzyme69** [comment]
Face palms... thanks @zeffii

**Comment by enzyme69** [comment]
This makes Splat Curve.

'''
def sv_main(sides=24, scale=1.0, seed=0, basis=0, radius=1.0):

    in_sockets = [
        ['s', 'Sides',  sides],
        ['s', 'Scale',  scale],
        ['s', 'Seed',  seed],
        ['s', 'Basis',  basis],
        ['s', 'Radius',  radius]
    ]

    from math import sin, cos, radians, pi, sqrt
    from mathutils import Vector, Euler
    import mathutils.noise as Noise

    # Generate random number:
    def randnum(low=0.0, high=1.0, seed=0):
        """
        randnum( low=0.0, high=1.0, seed=0 )

        Create random number

            Parameters:
                low - lower range
                    (type=float)
                high - higher range
                    (type=float)
                seed - the random seed number, if seed is 0, the current time will be used instead
                    (type=int)
            Returns:
                a random number
                    (type=float)
        """

        Noise.seed_set(seed)
        rnum = Noise.random()
        rnum = rnum*(high-low)
        rnum = rnum+low
        return rnum

    # Make some noise:
    def vTurbNoise(x, y, z, iScale=0.25, Size=1.0, Depth=6, Hard=0, Basis=0, Seed=0):
        """
        vTurbNoise((x,y,z), iScale=0.25, Size=1.0, Depth=6, Hard=0, Basis=0, Seed=0 )

        Create randomised vTurbulence noise

            Parameters:
                xyz - (x,y,z) float values.
                    (type=3-float tuple)
                iScale - noise intensity scale
                    (type=float)
                Size - noise size
                    (type=float)
                Depth - number of noise values added.
                    (type=int)
                Hard - noise hardness: 0 - soft noise; 1 - hard noise
                    (type=int)
                basis - type of noise used for turbulence
                    (type=int)
                Seed - the random seed number, if seed is 0, the current time will be used instead
                    (type=int)
            Returns:
                the generated turbulence vector.
                    (type=3-float list)
        """
        rand = randnum(-100, 100, Seed)
        if Basis == 9:
            Basis = 14
        vTurb = Noise.turbulence_vector((x/Size+rand, y/Size+rand, z/Size+rand), Depth, Hard, Basis)
        tx = vTurb[0]*iScale
        ty = vTurb[1]*iScale
        tz = vTurb[2]*iScale
        return tx, ty, tz


    #Verts = []
    #verts_new = Verts.append

    newpoints = []
    
    step = (2.0/(sides))
    i = 0
    while i < sides:
        t = (i*step)
        turb = vTurbNoise(t, t, t, 1.0, scale, 6, 0, basis, seed)
        turb = turb[2] * 0.5 + 0.5
        x = sin(t*pi)*radius * turb
        y = cos(t*pi)*radius * turb
        newpoints.append([x, y, 0])
        i += 1
        
    out_sockets = [
        ['v', 'Verts', [newpoints]]
    ]

    return in_sockets, out_sockets

'''

**Comment by enzyme69** [comment]
Something funky happened when I connect the vectorized data into UV Connection. Point seems ok.

![screen shot 2016-11-30 at 22 19 00](https://cloud.githubusercontent.com/assets/3952687/20750451/0bc2fb6e-b74b-11e6-8c5e-a3d8c05bcb36.png)

**Comment by zeffii** [comment]
to vectorize the SN, and SNLite scripts, isn't too hard, you just go one nested level up
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
from sverchok.data_structure import match_long_repeat

def listify(data):
    print(data)
    if isinstance(data, (int, float)):
        data = [data]
    return data
 
petals = listify(petals)
innerradius = listify(innerradius)
outerradius = listify(outerradius)
petalwidth = listify(petalwidth)

# match longest
params = match_long_repeat([petals, innerradius, outerradius, petalwidth])

points = []
add_point_list = points.append
for param_set in zip(*params):
    add_point_list(FlowerCurve(*param_set))
```

**Comment by enzyme69** [comment]
@zeffii What is going on when SN Lite does not update when I change the params?

**Comment by zeffii** [comment]
also, a more reusable general vectorize function
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
from sverchok.data_structure import match_long_repeat

def vectorize(all_data):

    def listify(data):
        print(data)
        if isinstance(data, (int, float)):
            data = [data]
        return data

    for idx, d in enumerate(all_data):
        all_data[idx] = listify(d)

    return match_long_repeat(all_data)

params = vectorize([petals, innerradius, outerradius, petalwidth])

points = []
add_point_list = points.append
for param_set in zip(*params):
    add_point_list(FlowerCurve(*param_set))
```

**Comment by zeffii** [comment]
> @zeffii What is going on when SN Lite does not update when I change the params?

you'd have to share the script, also..look at the terminal/console messages..

**Comment by enzyme69** [comment]
```
"""
in theeth       s d=8    n=2 
in innerradius  s d=0.8  n=2 
in middleradius  s d=0.95  n=2
in outerradius   s d=1.0  n=2
in bevel s d=0.5 n=2
out points      v
"""

#from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
#points = [FlowerCurve(petals, innerradius, outerradius, petalwidth)]

from add_curve_extra_objects.add_curve_aceous_galore import CogCurve

points = [CogCurve( theeth=8, innerradius=0.8, middleradius=0.95, outerradius=1.0, bevel=0.5 )]


```

**Comment by zeffii** [comment]
even shorter..
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
from sverchok.data_structure import match_long_repeat

def vectorize(all_data):

    def listify(data):
        print(data)
        if isinstance(data, (int, float)):
            data = [data]
        return data

    for idx, d in enumerate(all_data):
        all_data[idx] = listify(d)

    return match_long_repeat(all_data)

params = vectorize([petals, innerradius, outerradius, petalwidth])

points = [FlowerCurve(*param_set) for param_set in zip(*params)]
```

**Comment by enzyme69** [comment]
Whoa...

Didn't we need to use .=

**Comment by enzyme69** [comment]
Potential bug or I need to Flip or somethin?
![screen shot 2016-11-30 at 22 38 39](https://cloud.githubusercontent.com/assets/3952687/20751018/c45c0fc4-b74d-11e6-9a27-0aa3e22af376.png)

**Comment by zeffii** [comment]
you are calling the Cog function with the same paramters, regardless of the slider values. look carefully.

```python
points = [CogCurve(theeth=8, innerradius=0.8, middleradius=0.95, outerradius=1.0, bevel=0.5)]
```

**Comment by enzyme69** [comment]
Face Palms x 2. Thanks man. 

Now how about the UV Connection is that a new topic?

**Comment by zeffii** [comment]
that's a viewer draw artefact, i think... turn on `tesselate ngon` in the sidebar or VDMK2

**Comment by zeffii** [comment]
by default we don't tesselate because it's faster, but if you want to throw rubbish geometry at it, i added tesselate to give it a chance..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20751273/2cff35cc-b6fb-11e6-8158-dccd6006034d.png)

**Comment by enzyme69** [comment]
Yes, the poly face works for a single output, but not multiple.

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 22 52 02](https://cloud.githubusercontent.com/assets/3952687/20751411/b042eba0-b74f-11e6-8e43-ee20c78ba2ec.png)
The edge seems to be alright

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 22 53 07](https://cloud.githubusercontent.com/assets/3952687/20751433/c7fcbee2-b74f-11e6-9c2e-5c7bfe5aa953.png)

**Comment by zeffii** [comment]
send over the gist :)

**Comment by enzyme69** [comment]
Roger that:
https://gist.github.com/52694d064ba45125131573d8a2960525

**Comment by zeffii** [comment]
yep, that _is_ weird...

**Comment by zeffii** [comment]
I think that's a VDMK2 bug,, reusing older vertex indices..

**Comment by enzyme69** [comment]
I see, I did encounter that situation a few times, and always avoiding it.

**Comment by zeffii** [comment]
ooh not a bug..

**Comment by enzyme69** [comment]
Didn't work with BMesh MK2 either btw. Ehh. you figure out something?

**Comment by zeffii** [comment]
uv connect is expecting the same number of verts for each vert list.

**Comment by enzyme69** [comment]
Oh.. it needs enhancement 😗

**Comment by enzyme69** [comment]
![screen shot 2016-11-30 at 23 10 50](https://cloud.githubusercontent.com/assets/3952687/20751850/42023b7a-b752-11e6-9297-3616ddf7d53d.png)

This is similar to Iterate Matrix case. I still don't get it. It tends to over vectorize.

**Comment by zeffii** [comment]
no, not really,

you should be outputting 'face' data too for each pointset in points..

**Comment by enzyme69** [comment]
Ok... it needs to be in the SN code?

**Comment by zeffii** [comment]
yeah, and whenever you throw 'random' input at algorithms that you don't know you should be using small values first, and use the index viewer to see where the verts are (sequence and location is important, and not always obvious)
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
out faces       s
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve
from sverchok.data_structure import match_long_repeat

def vectorize(all_data):

    def listify(data):
        print(data)
        if isinstance(data, (int, float)):
            data = [data]
        return data

    for idx, d in enumerate(all_data):
        all_data[idx] = listify(d)

    return match_long_repeat(all_data)

params = vectorize([petals, innerradius, outerradius, petalwidth])

points = [FlowerCurve(*param_set) for param_set in zip(*params)]

faces = [[list(range(len(n)))] for n in points]
```

**Comment by zeffii** [comment]
like this ; https://gist.github.com/a7609483ac63f7f96d82662e1ba8a6eb

it's impossible to sanely be able to correct for input like this: 
![image](https://cloud.githubusercontent.com/assets/619340/20752331/1f64e960-b701-11e6-9e81-3665eafe6a3f.png)

**Comment by zeffii** [comment]
The error here is with the _User_ i'm afraid. but interesting to debug your own logic :)

**Comment by zeffii** [comment]
but the UV Connect does seem to choke on that particular kind of input... let me think about this.

**Comment by enzyme69** [comment]
I just made a Live Noding video about this :D

UV connection seems to also choke in generating "edges" for this guy: 

```
"""
in number       s d=100    n=2
in height  s d=2.0  n=2
in startangle  s d=0.0  n=2
in endangle   s d=360.0  n=2
in width s d=1.0 n=2
in a s d=0.0 n=2
in b s d=0.0 n=2
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import HelixCurve

points = HelixCurve( number, height, startangle, endangle, width, a, b )
```

**Comment by enzyme69** [comment]
![screen shot 2016-12-01 at 00 24 13](https://cloud.githubusercontent.com/assets/3952687/20753877/877dada6-b75c-11e6-8722-1ba76111bc86.png)

Very likely script clashing or it was not supposed to be used this way. 

Scripted Node is more safe?

**Comment by zeffii** [comment]
well, i don't know what you did there to provoke the `socket_info = self.node_dict(hash(self)['sockets']` in `make_new_locals` to be invalid.

**Comment by zeffii** [comment]
i'll need to think about that.. but if you can reproduce the problem with a step by step instructions, i'll happily track it down and fix. Else It may take a bit longer.

**Comment by zeffii** [comment]
```python
"""
in number       s  d=100    n=2
in height       s  d=2.0    n=2
in startangle   s  d=0.0    n=2
in endangle     s  d=360.0  n=2
in width        s  d=1.0    n=2
in a            s  d=0.0    n=2
in b            s  d=0.0    n=2
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import HelixCurve

points = [HelixCurve(number, height, startangle, endangle, width, a, b)]
```
you are forgetting to wrap the points in a list.

**Comment by zeffii** [comment]
i might have to expose a magic parameter ..perhaps `parameters` which is a list of all parameters in sequence,  so we don't have to write 
```python
HelixCurve(number, height, startangle, endangle, width, a, b)
```

but can write 
```python
HelixCurve(*parameters)
```

**Comment by zeffii** [comment]
OK i can reproduce the snlite hash problem.. let me see...

**Comment by zeffii** [comment]
that can be written as this now.
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
out faces       s
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve

from sverchok.data_structure import match_long_repeat
from sverchok.utils.snlite_utils import vectorize

params = vectorize(parameters)

points = [FlowerCurve(*param_set) for param_set in zip(*params)]

faces = [[list(range(len(n)))] for n in points]
```
the `parameters` variable is injected ( if the tickbox is enabled in the side bar for snlite )
and the `vectorize` function is part of the snlite helper library now.

**Comment by zeffii** [comment]
fixed the snlite code to be a bit more relaxed about things. update sverchok please.

**Comment by zeffii** [comment]
btw, a simplified UV connect SNLite version..
```python
"""
in vert_lists v n=[] d=0
out polygons s
"""

polygons = []
for vlist in vert_lists:
    polygons.append([list(range(len(vlist)))])
    print(vlist)
```
expects each sublist of vertices to represent an individual polygon. Notice here the randomized input is carefully limited to not produce self intersecting polygons.

![image](https://cloud.githubusercontent.com/assets/619340/20766043/17e6e07e-b735-11e6-849c-7a827f360590.png)

https://gist.github.com/456df3679137d4661c7fcf25d5e7b380

**Comment by zeffii** [comment]
> Scripted Node is more safe?

i haven't needed to use sn1 since creating snlite :)  but the more people test it the faster i'll be able to fix weird bugs that I didn't envisage while designing it.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1007
( you should update blender / restart )

**Comment by enzyme69** [comment]
Zeff you are genius man. Thanks for spotting weird error like min max in
random.

currently on mobile but will study all this once I am on laptop

**Comment by enzyme69** [comment]
Will add more results here, but will close :D

**Comment by zeffii** [comment]
i've added injection of the 'vectorize' function locally to the sn script, and also the list of parameters. So this is possible now. (See change log for info)

```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
"""

from add_curve_extra_objects.add_curve_aceous_galore import FlowerCurve

# look . magic! 
params = vectorize(parameters)

points = [FlowerCurve(*param_set) for param_set in zip(*params)]
```

**Comment by enzyme69** [comment]
I'll study this as soon as possible! Thanks Zefff!!



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
@zeffii Am I doing it right?
https://gist.github.com/c0e867e8e887712f34c5397250116805

Seems like the "lofting" operation is not right.

**Comment by zeffii** [comment]
don't know can't look atm.

**Comment by enzyme69** [comment]
I can load your example and it works fine, but if I use SNL and copy paste your script with parameters, I get this error... so strange.
![screen shot 2016-12-19 at 21 36 17](https://cloud.githubusercontent.com/assets/3952687/21309650/3b46b078-c633-11e6-9064-e7fb24fcd8f6.png)

What is "parameters" in this case?

**Comment by enzyme69** [comment]
Hitting "Reload" on your setup also trigger this error on "parameters".

**Comment by zeffii** [comment]
to get parameters auto injected you must modify
```python
"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
"""
```

into

"""
in petals       s d=8    n=1 
in innerradius  s d=0.5  n=1 
in outerradius  s d=1.0  n=1
in petalwidth   s d=2.0  n=1
out points      v
inject
"""

**Comment by enzyme69** [comment]
Inject. Interesting. Thanks @zeffii ! I'll check the frozen bug thing, but so far I am not seeing it on Windows. Maybe memory thing. Same with Mac. Sudden memory changes, it crashes. If computer has lots of memory or ram, it's ok.
