### ISSUE TITLE
Polyline Viewer Feature Request

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1006]
I really like this Polyline Viewer, because it is simple and works with Curve Galore on steroid thanks to Zeffi. 
https://github.com/nortikin/sverchok/issues/1005

Just one thing, instead of outputting 3D pipe lines, can we also allow for 2D Curve with Fill?

Currently this is nice and option available:
![screen shot 2016-11-30 at 23 22 03](https://cloud.githubusercontent.com/assets/3952687/20752145/db8b8980-b753-11e6-9741-fe495e306d24.png)
![screen shot 2016-11-30 at 23 22 11](https://cloud.githubusercontent.com/assets/3952687/20752143/db8a844a-b753-11e6-8172-c21312172498.png)

Maybe 2D Curve and Fill option also?
![screen shot 2016-11-30 at 23 22 19](https://cloud.githubusercontent.com/assets/3952687/20752144/db8b1482-b753-11e6-9f53-a3e80097e3d8.png)

**Comment by zeffii** [comment]
there's the 2D version in beta nodes , same kind of node but just makes 2d shapes..

**Comment by zeffii** [comment]
(i didn't want to combine the 2d/3d modes in one node, but nortikin wanted a 2d version -- hence the reason they are separate).

it would make sense to combine them eventually..
