### ISSUE TITLE
Cool visualisations of algorithms

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1009]
https://www.youtube.com/watch?v=OgupE9snZlQ

branching from evenly spaced point set   https://youtu.be/OgupE9snZlQ?t=10m22s
forcefield packing   https://youtu.be/OgupE9snZlQ?t=11m30s

**Comment by enzyme69** [comment]
A while back ago, I watched that Processing Documentary. It was so scary back then. I want to know those stuffs, I wanted to create cool visual, but it feels so difficult, especially because I have zero knowledge of programming. And not before long I found out: algorithm is also hard 🗡

**Comment by zeffii** [comment]
>  I have zero knowledge of programming.

There are four stages to mastery:

1. unconscious incompetence
2. conscious incompetence
3. conscious competence
4. unconscious competence

it takes a lot of time and there are no shortcuts. But a trend does seem to be that the most effort is up front,, a steep learning curve / amount of effort. After this initial period new stuff isn't so hard to 'assimilate' . 

But yeah, complex algorithms are complex, (not easy) and that's why they are called complex. :)

**Comment by enzyme69** [comment]
I don't know the pacing or time it takes to be a "great programmer". Maybe just like any skill in this world.

For example, you and Ly and Nikitron have certain levels where you make tools for noobs and artists and people like me.

Every now and then I got stucked. This year I have been noding quite good. Maybe still just touching the basics. 

Perhaps, I am ready to re-learn Processing and get to the next level.

I often think some parts of programmings are a headache.

**Comment by nortikin** [comment]
yes, headache for sure. but if you get result it is awesome

**Comment by enzyme69** [comment]
Awesome devs like SV Devs really lifted up the complexity and unlock the potential that artists never ever seen. I have to thank yous for that.

**Comment by nortikin** [comment]
thank you, @enzyme69 
pleasure is when your work is helping somebody
