### ISSUE TITLE
Create New Cycles Material + attr node for VertexColor layer

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1011]
Some nodes create or modify a vertex color layer, we can make an operator to generate a material that outputs `attr = <vertex color layer name>` for that object (or just generally into the bpy.data.materials with fake user )

Save users from creating a new cycles material by hand, just to be able to view a vertex color layer.

**Comment by nortikin** [comment]
did not think of it. I usually change mode to view result
