### ISSUE TITLE
Why have a Mesh Join and a Matrix Apply (and Join) node separately?

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1017]
![image](https://cloud.githubusercontent.com/assets/619340/20866955/ad2992ba-ba39-11e6-80c4-94ab5075b473.png)

if we made the matrix input _optional_ for Matrix Apply, then we could even Mesh Join..

**Comment by zeffii** [comment]
unless ofcourse... some of us actively generate socketdata for PolyEdge that mixes Polygons and Edges.... do we?

**Comment by zeffii** [comment]
just wondering :)

**Comment by nortikin** [comment]
hm, realy.
i made pols/edges sockets as or it or that, not both. no need mixed sockets maybe. i have two nodes that eat matrices or vertices, no matter what you feed. maybe this principle is well enough, but pols/edges just for user convenience, he know himself what to link, as i thought.
no mixes initially. but UX can be like that.
