### ISSUE TITLE
Using Sverchok to transfer Vertex Color to Particle Instances

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1021]
This is something that confused me. Maybe Blender Developers are still working on this, but I cannot find in anyway on how we can assign Vertex Color into the Instance of Particles.

I might be wrong and not familiar with how Blender Cycles handling Materials to Particle Instances.

All I wanted to do:
- Sverchok generate Vertex Color which will be passed into the EMITTER object Points.
- Somewhat passing the data from Sverchok into Cycles Particle Instancing.
- Perhaps in the future: being able to randomize UV texture for Particles.

NOTE: Although I realized that each particle can have its own Instance with different color... 

I think the answer might be via UV and having to bake the texture? Hmm...

I always find Cycles kind of "lacking" in a way it is handling the data in and out. Well, there is this OSL thing that might be possible to "hack" whatever data in and out. But the nodes in Cycles are currently limited or designed to be limited.

**Comment by enzyme69** [comment]
Interestingly my old blog post is kind of hinting the UV and Texture color passing for Particles.... 
![screen shot 2016-12-05 at 12 53 26](https://cloud.githubusercontent.com/assets/3952687/20871428/e1748628-bae9-11e6-9d7a-c3049a02abd5.png)

Which is well, kind of okey.

Kind of wanting a simpler ONE-TO-ONE direct point to particle instance. Vertex Color of each point to Particle Instances.

Any take on this?

**Comment by enzyme69** [comment]
Reading this...
http://www.blenderguru.com/articles/cycles-input-encyclopedia/

**Comment by enzyme69** [comment]
If we have this List of Colors and we have Particle Index List, and somewhat can pipe the data using "special cycles node" I think it's possible.

**Comment by zeffii** [comment]
forget about Sverchok for a moment.

If you can show us how this could be done with Cycles and `bpy`, then we will show you how to do it via Sverchok (and a new node if needed )

**Comment by enzyme69** [comment]
​Good idea, I shall do that.

**Comment by zeffii** [comment]
to some degree it is possible, but there should be dedicated attributes on a particle..and you should fillibuster blender devs about particle nodes / and particle system before they complete their redesign, or you might regret it.

![image](https://cloud.githubusercontent.com/assets/619340/20884048/79083fa8-bae9-11e6-9fc9-080fccd04e30.png)

**Comment by nortikin** [comment]
@zeffii but we have in alphas particles node, we can not use scripted node

**Comment by zeffii** [comment]
if it can be done with scripted node, then absolutely it can be done with a first-class- particles node.

**Comment by zeffii** [comment]
here the snlite version
```python
"""
in obj_id        o   d=[] n=1
in particle_sys  s   d=0 n=2
"""
import bpy
from random import random

objects = bpy.data.objects

a = self.inputs[0].sv_get()
if a and len(a) == 1:
    obj = a[0]

    if particle_sys < len(obj.particle_systems):
        ps = obj.particle_systems[particle_sys]
        particles = ps.particles

        for i in range(len(particles)):
            pt = particles[i]
            pt.velocity = (random(), random(), random())

```

**Comment by zeffii** [comment]
good opportunity to decide how the objects socket should work with snlite. hence my interest :)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20884671/e5113c24-baec-11e6-8b12-b4afdd099393.png)
```python
"""
in obj_id        o   d=[] n=1
in particle_sys  s   d=0 n=2
in colors        v   d=[[]] n=1
"""
import bpy
from random import random

a = self.inputs[0].sv_get()
if a and len(a) == 1:
    obj = a[0]

    if particle_sys < len(obj.particle_systems):
        ps = obj.particle_systems[particle_sys]
        particles = ps.particles

        for i in range(len(particles)):
            pt = particles[i]
            if colors and len(colors) <= len(particles):
                pt.velocity = colors[i]
```

**Comment by nortikin** [comment]
particles in and out node to have all parameters (hidden by default, control in draw_ext)
Also Polyline Viewer have to have inputs all parameters of polylines curves. weight and so on, handle type...
But also object in have to recognize type of object and output sockets, that needed. vertex weight, vertex color or other in addition. So we will have insertion node for scene. Also complicated output node for polyline, mesh, etc.
this will help communicate with scene.

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 13 05 29](https://cloud.githubusercontent.com/assets/3952687/20910274/b2d28af6-bbb4-11e6-90e1-275f349b86af.png)
 
@zeffii  LOL, I tried and passing Random Vector into Velocity. But this is an interesting development.

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 13 12 42](https://cloud.githubusercontent.com/assets/3952687/20910476/b425dcb8-bbb5-11e6-94cc-af46e970158c.png)

Not sure what to do with actual Particle Velocity being "hacked" like this, but I am pretty happy with current potential :)

**Comment by enzyme69** [comment]
Particle Info node should have option to specifically use Particle A, B, C.... Just like the Point Density node. Point Density node currently still does not have option for proper Particle Color, but will try Sverchok SNLite handles such matter...

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 13 37 29](https://cloud.githubusercontent.com/assets/3952687/20910999/2a0b79d0-bbb9-11e6-8747-4da6e601d31b.png)

So... Velocity is per Particle attribute. Maybe we can mix it with Attribute, but unfortunately the data from Object Vertex Color, is not something that Particles can read.

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 13 43 01](https://cloud.githubusercontent.com/assets/3952687/20911117/f1dbe49a-bbb9-11e6-8fc0-e9979975bc59.png)

The nice thing about this is that I can use 1 billion particles without problem 💃

**Comment by enzyme69** [comment]
![tenmillions_002](https://cloud.githubusercontent.com/assets/3952687/20912633/dfe06f76-bbc4-11e6-94f2-c46910e29e17.png)

10 Millions Particles, display 1% on screen, rendered under 20 minutes.

**Comment by enzyme69** [comment]
Not sure what's going on with color there. Maybe Script has not updated it properly. I tried twice, same result. With 10 millions data color, how to properly manage it.

After all, I just realized, maybe over millions of "point data" color, we need to use Texture maybe.

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 15 25 01](https://cloud.githubusercontent.com/assets/3952687/20913013/4d9481c6-bbc8-11e6-9424-8298d8c8a3c1.png)

10000 donuts instancing and color is still a bit funky... wonder why... maybe it got mixed with Velocity. Will try 100 first.

**Comment by enzyme69** [comment]
[sv_snlite_particletest_013_2016_12_06_04_34.zip](https://github.com/nortikin/sverchok/files/632995/sv_snlite_particletest_013_2016_12_06_04_34.zip)

On screen render preview, it renders the velocity correctly, however, when I hit render, it seems to reset the value and I am getting the color velocity apparently that's the case..

**Comment by enzyme69** [comment]
![screen shot 2016-12-06 at 15 35 23](https://cloud.githubusercontent.com/assets/3952687/20913169/a55f2950-bbc9-11e6-8972-20a11ad7a1c2.png)

Works in opengl and render preview, but when I hit "Render" on Cycles, it reset the velocity ...

**Comment by zeffii** [comment]
yeah, might have to switch the update kind (during render animation) in the Sverchok settings panel (user prefs -> addons -> Sverchok  ->   it might be `_pre_frame_change` atm

**Comment by zeffii** [comment]
my point is really, that the Cycles / Particle system needs to allow this to be passed in easily, and not abusing the velocity parameter (which might get overwritten anyway if you have moving particles)

**Comment by nortikin** [comment]
@enzyme69 https://yadi.sk/d/w0vRuvN932NUp3 this is how add count value with objectid set property.
for sure we need popup enum property to set without touching string exec.
I see it as interface with appearing enum popups as property is presented in some parameter
i.e. you add object -- choose data -- choose vertices -- choose co -- etc. every time adding to interface new property. But how to store values (names of choosen parameter)?

**Comment by nortikin** [comment]
Do you understand?

**Comment by nortikin** [comment]
so, we can make universal node

**Comment by nortikin** [comment]
additionally the button when you press - it shows all the parameters in inputs sockets (some limit esteblished) also output the same - safety concept, intuitive interface. What do you think?

**Comment by nortikin** [comment]
I cannot stop!!!!
https://yadi.sk/d/VWpkPyDC32NaVw

**Comment by zeffii** [comment]
: )  show screenshots

**Comment by nortikin** [comment]
https://yadi.sk/d/CR3Fye1y32NbCy
one more and go home

**Comment by nortikin** [comment]
haha!
https://vk.com/video-35076122_456239162

**Comment by nortikin** [comment]
![set_object_parameter2](https://cloud.githubusercontent.com/assets/5783432/20932764/d7f68a80-bbe6-11e6-9477-8cda02de9aef.png)

**Comment by nortikin** [comment]
amusing

**Comment by zeffii** [comment]
the .blend won't load here : /

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 10 44 37](https://cloud.githubusercontent.com/assets/3952687/20948822/2f0d7080-bc6a-11e6-8f39-d2041489df44.png)

@nortikin I got the new Objects ID but there is an issue with Objects in MK2, sometimes it is showing the newer, sometimes the old...

see: https://github.com/nortikin/sverchok/issues/1025#issuecomment-265266852

**Comment by enzyme69** [comment]
@nortikin I never 100% understand Particle Boids in Blender.

Btw, CrowdMaster and Sverchok? How about it?
http://jmroper.com/crowdmaster/

**Comment by nortikin** [comment]
never seen this. but blender web assets is cool.

**Comment by nortikin** [comment]
the problem here as i see, everyone try to make new node system, including us. we not see perspective in each other's nodes. maybe it is more convenient to use previous works. But as we started there was only one example to create node in blender, we did not have more samples at that moment. So started from blank. Folks like to make own. Motion tools AN, SV, blengdgraph, CM etc. till we have official all in nodes

**Comment by nortikin** [comment]
our solution with upgrade plugin shared in node systems everywere

**Comment by enzyme69** [comment]
So currently everyone is trying to implement Node system? Particles will not work? Not in a ideal way anyway?

**Comment by enzyme69** [comment]
@zeffii  SN Lite hack into Particle Vector is really interesting though. It's strong.

**Comment by nortikin** [comment]
in blender 2.8.0 we trust

**Comment by zeffii** [comment]
@enzyme69  i'll say this again, we are limited in several ways.

- sometimes bpy is weak and doesn't expose all the useful parameters that we, as users, can imagine ( sometimes for good reasons, sometimes just no-one thought of allowing bpy access to them )
- when the params are exposed via Python, sometimes there's fast ways of sending data in/out but not always,  meaning.. well.. working with a slow implementation isn't very user friendly.
- lots of the things that a user/artist might want from a node system should be implemented in a faster / compiled language. 

It's amazing that we managed to do using bpy/python/numpy/bgl. It just doesn't scale well to large scene / geometry count (reasons worth examining seriously at some point)
