### ISSUE TITLE
INSPIRATION: Brave Rabbit QTown and Shigeto Maeda video on the procedural city + Generative Creature

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1022]
I think, I will have to start making some simple procedural building, maybe 50 variations and we can make city. The texturing and UV, will also be need to think about.

See: QTown plugin.

And I also take screen shot from video by Shigeto Maeda:

![screen shot 2016-12-05 at 22 02 47](https://cloud.githubusercontent.com/assets/3952687/20882790/cc52ee86-bb36-11e6-9dde-396e0f51643f.png)
![screen shot 2016-12-05 at 22 02 40](https://cloud.githubusercontent.com/assets/3952687/20882793/cc53db02-bb36-11e6-8491-40c64f914891.png)
![screen shot 2016-12-05 at 22 02 38](https://cloud.githubusercontent.com/assets/3952687/20882791/cc532e50-bb36-11e6-9e3e-abcc1c42ae21.png)
![screen shot 2016-12-05 at 22 02 31](https://cloud.githubusercontent.com/assets/3952687/20882792/cc53cf68-bb36-11e6-9afa-b8a7091e73ba.png)
![screen shot 2016-12-05 at 22 01 59](https://cloud.githubusercontent.com/assets/3952687/20882794/cc541702-bb36-11e6-96b7-2326357044aa.png)

I always like Particles for Instancing.

**Comment by nortikin** [comment]
lovely

**Comment by zeffii** [comment]
i think Shigeto Maeda would like Sverchok :)

**Comment by nortikin** [comment]
@zeffii http://download.blender.org/documentation/bc2013/shigeto_maeda_GMP_Supplement.pdf

**Comment by nortikin** [comment]
https://vimeo.com/170402914

**Comment by enzyme69** [comment]
I showed Shigeoto-san Sverchok a couple of years ago, but maybe he has Python script already for his own research. More comfortable with Python especially when doing Generative works? Not entirely sure.

Same video on his channel:
https://www.youtube.com/watch?v=d-NKeiqZCZ4

I think it's a good idea to gather all "generative" design and creature into one thread.
http://golancourses.net/2012spring/02/21/joe-medwid-project-3-proposal/

**Comment by enzyme69** [comment]
https://au.pinterest.com/daniilz/generative-art/

Too many results from Google.

I remember there was one computer artists dealing with creature design... can't remember the name. He use very old school program. 

I think every 100 years people try to make algorithm to generate creature.

**Comment by enzyme69** [comment]
Karl Sims:
http://www.karlsims.com/

That's the one. Wonder if he is still alive and use Blender and Sverchok :D

**Comment by zeffii** [comment]
this doesnt need to stay open to remain useful

**Comment by enzyme69** [comment]
understood (-_-)V
