### ISSUE TITLE
Obj In MK2 freezing

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1025]
this is a separate issue, because it definitely isn't a feature :)

there are scenarios that makes snlite freeze up,  possibly go into infinite loop.  i'll keep this open for a while or until I find it..

**Comment by zeffii** [comment]
scenario one.
1. start a new fresh blend
2. add suzanne
3. import directly https://gist.github.com/3f2068bd472784c56d43fbfd5a8e58c4
4. freeze

**Comment by zeffii** [comment]
@nortikin  i think objects in needs a 'Clear' button on `buttons_ext` to wipe all references.

I don't want to automatically wipe all stored data in `objects_in` when adding to `.json` .

**Comment by zeffii** [comment]
will test with SN1 first, this might be nothing to do with `obj_in_mk2`.

**Comment by zeffii** [comment]
i wonder if this does work: https://gist.github.com/82665e7fcd07e1620735a06cc920ea23

**Comment by zeffii** [comment]
because this happens with both snlite and sn1, it might be the internal code that both nodes execute..  time to redux out the bmesh code there :) lets see..

**Comment by zeffii** [comment]
no bmesh  code in snlite, still freezing? https://gist.github.com/128f9ae9f9610721e0a558f1a3bd1117

**Comment by zeffii** [comment]
ok, still happening without bmesh code...and using sn1.  now time to remove all sn nodes :)

**Comment by zeffii** [comment]
oh.. @nortikin  looks like it's obj in's fault..  or viewer draw :)

![image](https://cloud.githubusercontent.com/assets/619340/20942591/4857fbf0-bbfc-11e6-9676-545facd9d1b0.png)

**Comment by zeffii** [comment]
Can anyone else @ly29 @nortikin @enzyme69 confirm that picking up 1 object with `Objects In MK2` while it is connected to something like Viewer Draw will freeze Blender?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20942775/2fba1014-bbfd-11e6-83dd-4a6d14c9976e.png)

**Comment by enzyme69** [comment]
Never happened to me @zeffii And your Objects in Mk2 looks different from mine?

**Comment by enzyme69** [comment]
However, different issue, click on "Select" is giving an error.


![screen shot 2016-12-07 at 10 22 53](https://cloud.githubusercontent.com/assets/3952687/20948236/35db47fa-bc67-11e6-80eb-d01fccc0e01d.png)

**Comment by enzyme69** [comment]
I supposed "Select" button should actually select objects currently listed in the node.

No, Zeff, working fine here, no Freezing ice2 baby.

**Comment by enzyme69** [comment]
Your Blender is probably going ROUGE? Or you need to reinstall Sverchok Add-On?

![screen shot 2016-12-07 at 10 27 39](https://cloud.githubusercontent.com/assets/3952687/20948355/cedcd446-bc67-11e6-92c4-8fe1b1434f68.png)

Your voodoo example is cool~

**Comment by enzyme69** [comment]
WEIRD! I opened up example from Nikitron and now my Objects In is matching yours Zeffi.... investigating.

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 10 37 37](https://cloud.githubusercontent.com/assets/3952687/20948647/32075f4a-bc69-11e6-97f6-c294c2d7cf7c.png)

I am not getting Objects In MK 3 btw. Unless I open Nikitron example.

**Comment by enzyme69** [comment]
No wait... it goes back to above. I am not getting a new one. Strange?!

**Comment by enzyme69** [comment]
@nortikin You keep mentioning you made update to Objects In MK2, now I understand. But I am not getting that new node. There is a weird clashing here. Zeffi's snapshot is showing the newer node. I got that one time, but now it is back to old node.

**Comment by enzyme69** [comment]
@zeffii  @nortikin Objects In weirdness is causing my Blender to crash. Noticed in many of my Live Noding video, it crashes when I get Objects In MK2.

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 12 30 04](https://cloud.githubusercontent.com/assets/3952687/20951275/f7bf0cce-bc78-11e6-8805-d6304d0bbdd1.png)

I restarted my computer and now I am getting the Objects In MK2 newer node.... hmm... willl keep you guys updated.

**Comment by enzyme69** [comment]
I restarted Blender and keep getting the old node of Objects In. Weird?

**Comment by nortikin** [comment]
no, remove old sverchok first. i changed folders, old folders store old nodes

**Comment by enzyme69** [comment]
Yeah @nortikin I decided to remove Sverchok and reinstall. I get the new node again. Will check Zeffi freezing issue. Not happening. here.

**Comment by nortikin** [comment]
https://gist.github.com/57943848480245d46e6f86ecb4217e61
many normal normals

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 20 11 29](https://cloud.githubusercontent.com/assets/3952687/20961492/5c391e5c-bcb9-11e6-914d-4742bb2c934f.png)
Nice Hairy Donut.

**Comment by enzyme69** [comment]
Still does not explain Zeffi's Blender / Sverchok going ROGUE!

**Comment by nortikin** [comment]
@zeffii im ok, maybe not git, than remove sverchok and install again

**Comment by zeffii** [comment]
line 55 should be   (the select operator mentioned by @enzyme69 
```python
bpy.context.scene.objects.active = bpy.data.objects[0]   
```

ok, i'll do a clean pull of master .

**Comment by zeffii** [comment]
maybe lateron this evening i'll have time. (fetch and reset also failed)

the problem is really like this.
 1. add object_in mk2
 2. connect object_in  verts/edges outputs to any other nodes.  ( don't pick an object yet )
 3. select objects to object_in
 4. freeze

**Comment by nortikin** [comment]
@zeffii so, i made mistake to comment this line?
but it works for me...

**Comment by zeffii** [comment]
@nortikin  commenting the line fine ofcourse, it just means that the active object won't be set. The correct way to set the active object is via `bpy.context.scene.objects.active = ` and not `bpy.context.active_object = `

**Comment by nortikin** [comment]
oh, thanks!! @zeffii

**Comment by enzyme69** [comment]
I have a feeling that all the crashing bugs, is related to this.

But often the crashing happens when:
- I use Blender for sometimes or leave Blender for a while (idle)
- then I load Sverchok and Objects In MK2
- loading Node Tree via JSON can sometimes crash Blender as well.

**Comment by nortikin** [comment]
objectin is some kind of complicated case

**Comment by zeffii** [comment]
Sverchok has no code that we can't reason about, but its interaction with AN is undefined. There's a variety of application handlers that run in the background for both SV and AN, and while these calls are not concurrent , their sequence and frequency might be a source of problems.

This issue was started because i thought it was SNLite freezing, it turned out to be Object's in - and under reproducible circumstances so that's great (as stated). I've been busy and haven't had to time to look into this, 

i'll probably add a `ObjInLite` node with a lot less features and less code to reason about, I rarely use the obj in node for anything other than getting `v,e,f,m`. It's great to have fully featured nodes, but I also really like the simpler nodes.

**Comment by zeffii** [comment]
> I have a feeling that all the crashing bugs, is related to this.
> 
> But often the crashing happens when:
> - I use Blender for sometimes or leave Blender for a while (idle)
> - then I load Sverchok and Objects In MK2
> - loading Node Tree via JSON can sometimes crash Blender as well.

The freeze described by _this issue_ can at least be reproduced with 100% certainty, it is not related to the 'Blender closing to desktop'.  It's important that we be more exact about the way we describe things.

These following things are very different.
- a freeze 
- a blender closes to desktop. (crash )

**Comment by zeffii** [comment]
this still isn't resolve.
- new latest blender from builder.bot
- new startup.blend / new userpref.blend
- cleaned, sverchok directory locally and pulled all new files.

All i have to do to freeze blender is 
1. add obj in mk2
2. connect it to VDMK2
3. select an object in the scene
4. press Get Selection.

Freeze. Does this happen to anyone else?

**Comment by zeffii** [comment]
who wrote this:
```python
        handle = handle_read(self.name + self.id_data.name)
        if self.objects_local:
            if handle[0]:
                for i, o in enumerate(handle[1]):
                    if i > 4:
                        layout.label('. . . more ' + str(len(handle[1]) - 5) + ' items')
                        break
                    layout.label(o)
            else:
                handle_write(self.name + self.id_data.name, literal_eval(self.objects_local))
        else:
            layout.label('--None--')

```

**Comment by zeffii** [comment]
ok :) took me a few minutes of headache, seems to need more freeze/unfreeze  due to update in bpy.data.meshes calling an update on scene update...which I think triggers updates inside blender :) 

https://github.com/nortikin/sverchok/tree/objmk2_test

**Comment by ly29** [comment]
That ```handle_write``` is for for F8 reloading scenario if I remember correctly.
The whole freeze unfreeze is a bit weird thing that I did to cut down on the number of updates.

**Comment by zeffii** [comment]
I see!  i'll modify it to do that in `process` instead.

**Comment by zeffii** [comment]
@ly29  we detect the F8 reload event in `__init__.py` perhaps a general update could be issued from there, I would prefer that than in the draw_buttons function of a node.

**Comment by nortikin** [comment]
this handle principle was added Nedovizin Alexander, as i remember

**Comment by zeffii** [comment]
i would love to rip out the handle dependency, completely...

**Comment by zeffii** [comment]
solved with the latest commit..

**Comment by enzyme69** [comment]
​Latest commit is not yet arrived here, I checked latest update, but no
update.

**Comment by zeffii** [comment]
i reverted the changes already,  but this is even happening in the objects_mk2 without my changes.
