### ISSUE TITLE
Objects ID Set and Get Exploration

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1026]
I am wondering with Objects ID Set and Get about a couple of things:
- I do Object Color often with AN, and it does not work with SV Objects ID Set and Get. Wonder why?
- Does Object ID Set and Get only accepting a single value/vector input? Or can be multiple?

![screen shot 2016-12-07 at 10 49 52](https://cloud.githubusercontent.com/assets/3952687/20948985/13da264a-bc6b-11e6-8787-5b198d1725be.png)

**Comment by nortikin** [comment]
@Kosvor2 is it yours?

**Comment by Kosvor2** [comment]
Color must contain 4 items, not 3.

**Comment by enzyme69** [comment]
Ah, ok got it. With AN, there is some kind of indicator and error reporting. Thanks!

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 19 05 41](https://cloud.githubusercontent.com/assets/3952687/20959643/2c7c4382-bcb0-11e6-802f-ef47d32b6862.png)

Nope this one no good. Still...

**Comment by enzyme69** [comment]
This sort of work, but something is not right:
https://gist.github.com/b2e930717fe0ec1c746f8ea9f5ed1b88

**Comment by enzyme69** [comment]
![object_color](https://cloud.githubusercontent.com/assets/3952687/20959776/ea344730-bcb0-11e6-8707-4658e65a503c.gif)

How to make 4 list btw? Random Vector gives 3 floats list.

**Comment by Kosvor2** [comment]
```

def sv_main(verts=[[]]):
 
    in_sockets = [
        ['v', 'Vertices',  verts],
    ]
    Col = []
    for v in verts:
        Col.append([v0+(1.0,) for v0 in v])    
    
    out_sockets = [
        ['v', 'Colors', Col],
    ]
 
    return in_sockets, out_sockets

```
This script (for old script node) must help.

**Comment by enzyme69** [comment]
Thanks!! @Kosvor2

**Comment by enzyme69** [comment]
![screen shot 2016-12-07 at 20 42 40](https://cloud.githubusercontent.com/assets/3952687/20962516/b9698586-bcbd-11e6-9b3f-696bdd34fd80.png)
This mixing and split 4 also works. 

@nortikin any other trick? just need RGBA node :D

**Comment by nortikin** [comment]
https://gist.github.com/da0f92cf27899c87ece10d9404694646
@enzyme69

**Comment by nortikin** [comment]
zip rulez. but i think, we can make 4-vertex input and output nodes.

**Comment by Kosvor2** [comment]
Can be done without script node like this:

![color_location](https://cloud.githubusercontent.com/assets/22656834/21006404/da2bf0ec-bd49-11e6-8bae-c4454d4ab74c.png)

**Comment by enzyme69** [comment]
​That's incredible!!! Never knew!

**Comment by nortikin** [comment]
@Kosvor2 it is unclear concept of Object ID. What pipeline you mean? Do you propose common case when you take all objects in scene and operate with them with your node or we can completely use object in node to handle all types of objects? or we can make ObjectID get more precise in objects choosing?

**Comment by nortikin** [comment]
did not know color = sum(i.vertices[0].co[:]) needed documentation
I propose to make object id get scalable. to handle properties also, three-four popups etc to get exact parameter and work with it.

**Comment by enzyme69** [comment]
​And also I propose RGB, RGBA, HSV also :D

**Comment by nortikin** [comment]
how to get colors in viewport?

**Comment by enzyme69** [comment]
​Blender Internal, Object Color (color attribute). Cycles works differently

**Comment by enzyme69** [comment]
​1 Material, "Use Object Color" then apply to all object, then adjust
"Color".

**Comment by nortikin** [comment]
finally, object color

**Comment by nortikin** [comment]
thanks

**Comment by nortikin** [comment]
@Kosvor2  how you convert objects to bmesh?

**Comment by nortikin** [comment]
ok, bmesh in node, see.

**Comment by nortikin** [comment]
how to get matrix world from object id?

**Comment by nortikin** [comment]
ok, we need scene node, that get all properties from any part of scene. adding new enum in draw def
