### ISSUE TITLE
PROCEDURE: Trace, Separate and Colorize

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1027]
![screen shot 2016-12-07 at 12 45 35](https://cloud.githubusercontent.com/assets/3952687/20951657/2718613a-bc7b-11e6-9a29-bb038bbce6d2.png)

I am doing this artwork that needs to be traced, each loose parts separated and colorized.

The trace part is magically done using X tool. Unless Sverchok can do tracing, but that's for other story.

NEXT: the separate loose.
The big artwork has around 1700 parts, it's unfortunately a big trouble for Blender. I cannot turn them into 1700 objects. Well I could, but it is super slow even in 3D View.

I tried using Svechok, actually it is even slower, especially with "Separate Loose Part" process. @nortikin how did you kind of bake a single node one time and not to process it again unless it is dirty? sorry I asked it twice.

The whole procedure is rather simple, and I can do it for smaller setup like above. I have only around 13 parts, however, the issue is with the objects being heavy with too many points.

**Comment by enzyme69** [comment]
Actually... I just figured out that I probably cannot do this in Sverchok, yet. Because Vertex Color New only works for object.

**Comment by nortikin** [comment]
It needs optimization.

**Comment by enzyme69** [comment]
If busy no worries. But yeah, separate loose part is no good in this case.

Anyhow, I think once off separate loose and use Object in AN easier for now.
