### ISSUE TITLE
That LIVE Object In Option ....

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1028]
I figure there is LIVE Object In option in Sverchok Add-On Preferences.

![screen shot 2016-12-08 at 10 51 52](https://cloud.githubusercontent.com/assets/3952687/20991787/7293eb70-bd34-11e6-9d1b-7f20f4326906.png)

But I don't know if that thing is actually working. Because I have bunch of objects in group and when I made duplicates it does not update.

It comes to my understanding of how each node can and be triggered. So far, I just assume all nodes gets recalculated and trigger updated by frame changes.

**Comment by nortikin** [comment]
oh, i changed objectin mk2 and it goes wrong. first with 3d panel, and it was more and more

**Comment by nortikin** [comment]
i donno where is enable_live_objin

**Comment by zeffii** [comment]
Branch wasn't merged I think? I'd remove the option in prefs till later. The 'obj_in_live_updates' is still present but stale

**Comment by nortikin** [comment]
live object worked till i changed object in mk3

**Comment by zeffii** [comment]
the old branch: https://github.com/nortikin/sverchok/tree/obj_in_liveupdate_mode

**Comment by zeffii** [comment]
@nortikin 

https://github.com/nortikin/sverchok/blob/8fe4d36523a7e1b8f3518ebc69ef285c9094ed3a/ui/sv_panels.py#L43-L45

and

https://github.com/nortikin/sverchok/blob/8fe4d36523a7e1b8f3518ebc69ef285c9094ed3a/ui/sv_panels.py#L82-L84

stuff like this needs to be updated..

```python
                    for n in ng.nodes:
                        if n.bl_idname == 'ObjectsNode':
                            nodes.append(n)
                    if nodes:
```

like

```python
              if n.bl_idname in {'ObjectsNode','ObjectsNodeMK2'}:
```

**Comment by zeffii** [comment]
```python
                if ng.sv_process:
                    updateable = {'ObjectsNode', 'ObjectsNodeMK2'}
                    nodes = [n for n in ng.nodes if n.bl_idname in updateable]
                    if nodes:
                        obj_nodes.append(nodes)
```

but, because only one object can be in edit mode at a time, we could take it further and test if bpy.context.active_object is in the object list of of the ObjectsNode .. and skip updating those nodes that don't reference the object being edited :)

**Comment by zeffii** [comment]
and future proof for ObjInLite
```
            obj = bpy.context.edit_object
            if ng.sv_process and obj:
                
                def should_update(n):
                    if n.bl_idname in {'ObjectsNode', 'ObjectsNodeMK2'}:
                        if obj.name in ast.literal_eval(n.objects_local)
                            return True
                    # if n.bl_idname == 'SvObjInLite' and (obj.name == n.obj_name)
                        return True

                nodes = [n for n in ng.nodes if should_update(n)]
                if nodes:
                    obj_nodes.append(nodes)
```

**Comment by zeffii** [comment]
@enzyme69   I don't think duplicated objects were ever picked up by the obj in nodes, there's no code to this effect anyway. (never had been)

**Comment by zeffii** [comment]
but the question did expose another missing feature (shown above in code).. 

so going to close for now, but will add code to the operator once i'm done with obj_in_lite , or maybe @nortikin will add the correct bl_idname checks.   I don't want to check out a different branch at the moment :)

**Comment by zeffii** [comment]
The current implementation fixed.. but there's room for improvement..
https://github.com/nortikin/sverchok/commit/b0c6d5ea3ae6a525032bc1781b5842ae079f3c71

**Comment by zeffii** [comment]
hmm, the code I added now doesn't fix the freeze/infinite loop..

**Comment by zeffii** [comment]
(but don't reopen this issue, the problem is still with `objects in mk2`)

**Comment by nortikin** [comment]
so where is definition for handle live update?

**Comment by zeffii** [comment]
![ezezgif](https://cloud.githubusercontent.com/assets/619340/21220036/669e0caa-c2b7-11e6-83d5-f028fb606fde.gif)

update your blender

**Comment by zeffii** [comment]
This works for Curves, but not for Meshes ( I think this is a limitation in `obj.to_mesh` ) operator. where Curves in EditMode can be passed to obj.to_mesh but Meshes -> obj.to_mesh will use the current state of the mesh (and this is only updated when the mesh leaves edit mode..

**Comment by zeffii** [comment]
if it was once working, then the commit will restore to what worked.

**Comment by zeffii** [comment]
if it's necessary to get meshes in their Edit mode state we can do a if else ..something like
```python
   if obj.type == 'MESH' and obj.mode = 'EDIT':
        verts, edges, faces = pydata_from_bmesh(bmesh.from_edit_mesh(obj.mesh))
   else:
        obj_data = obj.to_mesh(scene, self.modifiers, 'PREVIEW')
        ....
```
