### ISSUE TITLE
Porting this JAVA code Image Tracing algorithm....

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1029]
I am trying to achieve a result like this:
http://asserttrue.blogspot.com.au/2010/01/fast-conversion-of-bitmaps-to-svg.html#

![screen shot 2016-12-08 at 11 57 25](https://cloud.githubusercontent.com/assets/3952687/20993306/8196eb82-bd3d-11e6-8304-33fb13c8d9b2.png)

It gave the program in JAVA language.

I accidentally stumbled into above while searching for "image tracer". I have seen this "tracing" question asked and answered multiple times.
http://blender.stackexchange.com/questions/1609/tracing-a-monochrome-image-into-a-3d-extruded-object-with-a-script

The image tracing result tends to be dirty and not optimized anyway. Inkscape does not work on my Mac, anyhow for proper Image Tracing, I may just use Houdini. 

Anyhow, back to the above JAVA thing, I don't have enough knowledge to run the program. Even following all below does not give me result:
https://docs.oracle.com/javase/tutorial/ext/basics/install.html
https://docs.oracle.com/javase/tutorial/deployment/jar/basicsindex.html
https://developer.apple.com/library/content/qa/qa1170/_index.html
http://alvinalexander.com/blog/post/java/java-faq-what-is-classnotfoundexception

The idea here is for me to try to run X program that gives a result to be used in Blender.

(pardon me if this is not question directly related to Sverchok)

**Comment by enzyme69** [comment]
For Processing I found image trace that is more for OpenCV stuff, wonder if that's helpful, but I put that aside.
https://github.com/atduskgreg/opencv-processing

I got another friend he knows Java and Javascript, he recommend Flash tracing.

Javascript?
```
//// EDGE ////
function edgeImage(imageObj){
    var canvas = document.getElementById("Edge");
    var context = canvas.getContext("2d");
    var destX = 0;
    var destY = 0;

    context.drawImage(imageObj, destX, destY);

    var imageData = context.getImageData(0, 0, canvas.width, canvas.height);
    var data = imageData.data;
    var width = canvas.width, height = canvas.height;

    var matrixH = [-1,-2,-1,
		     0, 0, 0,
		     1, 2, 1];
    var matrixV = [-1, 0, 1,
		    -2, 0, 2,
		    -1, 0, 1];

    var outputData = [];
    for (var y = 0; y < height; y++) {
	for (var x = 0; x < width; x++) {
	    var pixel = (y*width + x)*4;
	    var rh = 0; gh = 0; bh = 0;
	    var rv = 0; gv = 0; bv = 0;
	    for(var row = -1; row <= 1; row++){
	    	var iy = y+row;
	        var ioffset;
	        if(iy >= 0 && iy < height){
	            ioffset = iy*width*4;
	        } else {
	            ioffset = y*width*4;
	        }
	    var moffset = 3*(row+1)+1;
	    for(var col = -1; col <= 1; col++){
	        var ix = x+col;
	        if(!(ix >= 0 && ix < width)){
	            ix = x;
	        }
	        ix *= 4;
	        var r = data[ioffset+ix];
	        var g = data[ioffset+ix+1];
	        var b = data[ioffset+ix+2];
	        var h = matrixH[moffset+col];
	        var v = matrixV[moffset+col];
	        rh += parseInt(h*r);
	        bh += parseInt(h*g);
	        gh += parseInt(h*b);
	        rv += parseInt(v*r);
	        gv += parseInt(v*g);
	        bv += parseInt(v*b);
	    }
	}
	r = parseInt(Math.sqrt(rh*rh + rv*rv) / 1.8);
	g = parseInt(Math.sqrt(gh*gh + gv*gv) / 1.8);
	b = parseInt(Math.sqrt(bh*bh + bv*bv) / 1.8);

	outputData[pixel] = r;
	outputData[pixel+1] = g;
	outputData[pixel+2] = b;
	outputData[pixel+3] = data[pixel+3];
	}   
    }
    for(var k = 0; k < outputData.length; k++){
	data[k] = outputData[k];
    }
    
    context.putImageData(imageData, 0, 0);
```

**Comment by enzyme69** [comment]
![15220242_10209379884587469_1501534075297884765_n](https://cloud.githubusercontent.com/assets/3952687/20996471/ff505810-bd51-11e6-9023-7d8c565af87e.jpg)
![15380433_10209379871827150_8006517606982676611_n](https://cloud.githubusercontent.com/assets/3952687/20996472/ff509d98-bd51-11e6-8cbe-3d3ad7620497.jpg)

**Comment by enzyme69** [comment]
![screen shot 2016-12-08 at 14 29 07](https://cloud.githubusercontent.com/assets/3952687/20996582/b464797a-bd52-11e6-8208-11bea24c92e4.png)
Houdini (free version) and export OBJ.

The conversion can be very unoptimized.

**Comment by enzyme69** [comment]
![screen shot 2016-12-08 at 16 10 57](https://cloud.githubusercontent.com/assets/3952687/20998344/37d142e4-bd61-11e6-84a9-637d3fa5b6c8.png)

I understand now that I need to compile ImageMunger.java and it become this "Java Class", weird, anyhow, I run the program, it failed :(

In term of Sverchok, does it need to be Python, btw? Can it be Swift?

I'll try to find other method.

**Comment by enzyme69** [comment]
Error in Java and Javascript:

~/_JAVA java ImageMunger pokemon.jpg tiles.js
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: getRMSError is not a function, it is sun.org.mozilla.javascript.internal.NativeJavaPackage. (<Unknown source>#67) in <Unknown source> at line number 67
	at com.sun.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:156)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:232)
	at ImageMunger.runScriptFromFile(ImageMunger.java:118)
	at ImageMunger.main(ImageMunger.java:155)
2016-12-08 16:10:57.076 java[7751:1193883] -_cgsEventRecord is deprecated for _cgsEventRecord. Please use -CGEvent.

**Comment by nortikin** [comment]
:om:
