### ISSUE TITLE
Slicing Rock Generator

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1031]
I kind of wanted to make Bunch of Rocks generated by slicing. It's probably something that will result from Voronoi 3D WIP, however, this is slightly different:

![screen shot 2016-12-09 at 18 10 45](https://cloud.githubusercontent.com/assets/3952687/21040765/fd371bc4-be3a-11e6-9793-733683095e58.png)

In a way, I want to do multiple Bisect slicing, iteratively or recursively.

Any idea?

**Comment by nortikin** [comment]
matrix location Z + rotation in oposite to center = many bisect section from bisect node + convex hull node

**Comment by enzyme69** [comment]
![screen shot 2016-12-10 at 10 41 40](https://cloud.githubusercontent.com/assets/3952687/21068313/4327f1f0-bec5-11e6-97bb-df6fde12a47c.png)

Yeah, I thought about something like that but not getting it:
https://gist.github.com/6234d0aa510951fd3f4fd5249d3e0e6e

Bisect is getting rid of half mesh, but that's one process. I thought Sverchok can do that but that requires recursive operation.

**Comment by enzyme69** [comment]
At some point I want to talk about Houdini recursive.

**Comment by enzyme69** [comment]
![screen shot 2016-12-10 at 10 45 44](https://cloud.githubusercontent.com/assets/3952687/21068389/d3d993ca-bec5-11e6-8bca-00ec4159ba4a.png)

Mesh Join, but not elegant. I think something is missing here.

**Comment by nortikin** [comment]
@enzyme69 yes, plug vector rotation to socket angle, not to first. first rotation socket is initial orientation

**Comment by enzyme69** [comment]
![screen shot 2016-12-11 at 23 06 24](https://cloud.githubusercontent.com/assets/3952687/21079960/78164902-bff6-11e6-9400-9baaa26b8660.png)

Still nope

**Comment by enzyme69** [comment]
@nortikin Can you explain again why the Vector goes into Float of Angle? And it supposed to work?

**Comment by nortikin** [comment]
it is feature. we have to write not angle, but angle/vertex that defines aim direction, axis defines initial direction in this acse of use
