### ISSUE TITLE
Object In Lite

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1033]
The plan is to make a simplified Object In, which only outputs mesh data

- Single Object reference
- Mesh data (Verts, Edges, Faces, Matrix)
- Does not live update
- Will store the referenced Object's Mesh internally in the `self.node_dict[hash(self)]['geom']`
- Will store object data in iojson :)

Most of the time this is what I need, but i'm undecided about how to store the geometry in the json, probably plain-readable-text (at least initially)

**Comment by zeffii** [comment]
maybe a flat-list storage to conserve space,

**Comment by nortikin** [comment]
space. flat is fatser

**Comment by zeffii** [comment]
I think i'll store Edges even if Edges isn't a connected socket, same for Faces. Or make option to `store optimal`. anyway. time to code today..

**Comment by zeffii** [comment]
here's a https://github.com/nortikin/sverchok/tree/obj_in_lite prelim implementation. not heavily tested yet, but it will be tested before it lands in master.

**Comment by zeffii** [comment]
finished prelim flatten / unflatten https://github.com/nortikin/sverchok/blob/obj_in_lite/utils/mesh_repr_utils.py  :)

**Comment by zeffii** [comment]
https://gist.github.com/anonymous/2cb1e588550ee49452161fa0b79205b2
the obj_in_lite branch now stores one obj per obj in node, and flattens it into json :) and can re import :)

**Comment by zeffii** [comment]
any questions, please reopen this issue. --

--this is now added as a beta node :)
