### ISSUE TITLE
UV Connection but do not connect Strokes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1035]
I have an idea to make a Kanji stroke tracer, this is for my next Live Noding video.

[kanji_strokes_data_002_2016_12_11_01_15.zip](https://github.com/nortikin/sverchok/files/644163/kanji_strokes_data_002_2016_12_11_01_15.zip)

From Grease Pencil, typically one will have multiple strokes, I wanted to bring it into Sverchok and then turn it into JSON data for each strokes, and then we can perhaps load it back as points.

Then I use UV, but UV kind of connect each strokes with lines, just like Grease Pencil, I kind of want to "cut" the edge that is in between strokes.

Does UV Stroke has that kind of hidden functionality, is it with "slice"?

I tried KDTree Closest Edge, might work, but too hacky.

I think UV Connection and Edge masking is better. But I need a procedural way to "mask" edges between strokes.

Any hint will help thanks 💃

**Comment by zeffii** [comment]
include the GP strokes in your blend, and i _might_ do something.

**Comment by zeffii** [comment]
the GP layer will include data to make segmentation of disjoint lines easy.

**Comment by zeffii** [comment]
no need to make this more complicated.
![image](https://cloud.githubusercontent.com/assets/619340/21080962/8662c4e8-bfbc-11e6-853b-f8aa553d8a8d.png)

**Comment by zeffii** [comment]
I don't think we have any node that returns the length of each edge..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21081502/ba174cf8-bfc8-11e6-804f-cb42bccb3522.png)

**Comment by enzyme69** [comment]
Yes, remove longest edge I thought about that.

A single stroke indexes must be placed next to each other in the index.

If there is sudden jump it must be a change in stroke.

I was thinking each stroke has start and end index and perhaps that is
something to note.

Grease and Sverchok are good buddy we need to make Sverchok as buddy plugin
for Grease just like Maya PFC

**Comment by enzyme69** [comment]
Thanks @zeffii

**Comment by zeffii** [comment]
> Does UV Stroke has that kind of hidden functionality, is it with "slice"?

look at the code for uv connection node.

**Comment by nortikin** [comment]
here i post again. ease your job. it needs to be as scene node at all!!!
```python
def sv_main(a=0):

    in_sockets = [
        ['s', 'nothing',  a],
        ]

    if bpy.data.grease_pencil:
        verts_out = [[[[p.co[:] for p in str.points] for str in gl.active_frame.strokes] for gl in gp.layers] for gp in bpy.data.grease_pencil]
    else:
        verts_out = [[]]

    out_sockets = [
        ['v', 'verts', verts_out]
    ]

    return in_sockets, out_sockets
```

**Comment by enzyme69** [comment]
Interesting, sometimes need my head to go 360 and back, but it's neat.

![screen shot 2016-12-13 at 22 59 45](https://cloud.githubusercontent.com/assets/3952687/21139613/dcf7aa68-c187-11e6-9e93-15502c5be492.png)

https://gist.github.com/92ddaa8748dd84541a0d12013dae5588

**Comment by enzyme69** [comment]
One by one
https://gist.github.com/8cc3b1ef6fe57e544e91b8ba64787bea

**Comment by enzyme69** [comment]
Now just need a way to go from start to end, which each stroke is drawing...

**Comment by enzyme69** [comment]
@nortikin unfortunately we don't have List Length and Resample based on length. Future homework....

**Comment by enzyme69** [comment]
This is the finalize version:
https://gist.github.com/49699bdee90f7f4163e07e90c65f47e2

Can be improved if we:
- have Length Measurement for Edge Strokes
- better Polyline viewer
- better Pipe :)

**Comment by zeffii** [comment]
I consider the end point nodes, like the _Viewer Nodes_ , to be the hardest to code. Especially nodes that generate real scene data (Curves, Mesh). I don't think you'll ever appreciate how 'hairy' the code is that makes those things work, until you try writing one.

when you say ' better polyline viewer ' that's a bit of an empty statement, until you describe _how_ you'd like to see it improved. I'll probably agree with suggestions, but there are many small fixes I want to do to non beta/alpha nodes first.

**Comment by enzyme69** [comment]
Better Polyline Viewer meaning a way to take Edge Indices to mask?

**Comment by zeffii** [comment]
then use list mask, i don't think that should be part of the viewer.. this is the whole reason we have a modular system.

**Comment by nortikin** [comment]
https://gist.github.com/51db335dd6c59c892d9d40f9d13505de
maybe to play with it
