### ISSUE TITLE
Particle Alpha but multiple Emitter?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1037]
![screen shot 2016-12-11 at 22 37 48](https://cloud.githubusercontent.com/assets/3952687/21079843/890a7930-bff2-11e6-9804-14e664b437b7.png)

Current Particle node does not seem to take vectorized emitter (multiple emitter)? Wonder if there is a way around it?

**Comment by enzyme69** [comment]
![bake_every_frame](https://cloud.githubusercontent.com/assets/3952687/21079873/a41c5c06-bff3-11e6-8a9c-6182f4e2dde4.gif)
Baking every frame, once each time... but that's dumb.

**Comment by Kosvor2** [comment]
```
def sv_main(c=[]):
    in_sockets = [
       ['v', 'Not working socket', c],
    ]

    out = []
    for i in bpy.data.objects:
        if i.particle_systems:
            ps = i.particle_systems.active.particles
            out.append([i2.location[:] for i2 in ps])

    out_sockets = [
        ['v', 'particles', out]
    ]

    return in_sockets, out_sockets

```

This script outputing particles of active Psystems for all objects in the scene which have particle systems on them.

**Comment by enzyme69** [comment]
@Kosvor2 thanks so much! Willl try now. 

![screen shot 2016-12-12 at 11 21 40](https://cloud.githubusercontent.com/assets/3952687/21084844/2bd0f0b2-c05d-11e6-850a-e3bdc5d97566.png)

@nortikin Look!

Script Node rocks!

**Comment by enzyme69** [comment]
![particle_bukkake_002](https://cloud.githubusercontent.com/assets/3952687/21085001/d47be1de-c05f-11e6-8b38-4605506f7dd0.png)

Kosvor unlock Particle Bukkake node!

**Comment by nortikin** [comment]
ok, i will remake particles node adding regime 'ALL objects'

**Comment by nortikin** [comment]
for greace_pencil:

```python
def sv_main(a=0):

    in_sockets = [
        ['s', 'nothing',  a],
        ]

    if bpy.data.grease_pencil:
        verts_out = [[[[p.co[:] for p in str.points] for str in gl.active_frame.strokes] for gl in gp.layers] for gp in bpy.data.grease_pencil]
    else:
        verts_out = [[]]

    out_sockets = [
        ['v', 'verts', verts_out]
    ]

    return in_sockets, out_sockets
```
