### ISSUE TITLE
GP strokes pressure + co

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1038]
in an old thread I made a SN for a single stroke/polygon as a mesh. now i'll do a GP stroke with pressure.

https://github.com/nortikin/sverchok/issues/509

compare the snlite generator version for the spiral..with the old one :)

```python
"""
in arc         s  d=1.0   n=2
in separation  s  d=3.0   n=2
in num_points  s  d=300   n=2
in scale       s  d=0.13  n=2
out verts      v
"""

import math

def spiral_points(scale, arc=1, separation=1):
    """
    lifted directly from: 
    http://stackoverflow.com/a/27528612/1243487 
    by user: liborm

    generate points on an Archimedes' spiral
    with `arc` giving the length of arc between two points
    and `separation` giving the distance between consecutive 
    turnings
    - approximate arc length with circle arc at given distance
    - use a spiral equation r = b * phi
    """
    def p2c(r, phi):
        """polar to cartesian
        """
        return (scale * r * math.cos(phi), scale * r * math.sin(phi), 0)

    # yield a point at origin
    # not using the origin may give better results
    yield (0, 0, 0) 

    # initialize the next point in the required distance
    r = arc
    b = separation / (2 * math.pi)
    # find the first phi to satisfy distance of `arc` to the second point
    phi = float(r) / b
    while True:
        yield p2c(r, phi)
        # advance the variables
        # calculate phi that will give desired arc length at current radius
        # (approximating with circle)
        phi += float(arc) / r
        r = b * phi


point_gen = spiral_points(scale, arc, separation)

verts = [[]]
point = verts[0].append
for i in range(num_points):
    point(next(point_gen))

```
![image](https://cloud.githubusercontent.com/assets/619340/21099548/19b39c1a-c06f-11e6-8ae4-4f36a205f79c.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21100217/2640f9ec-c073-11e6-8755-3624556222c1.png)

**Comment by nortikin** [comment]
have we folder for snlite scripts?

**Comment by enzyme69** [comment]
I was going to do what you did up there @zeffii  wooh! awesome!!

**Comment by enzyme69** [comment]
@zeffii btw, how do you sample the image above to displace the thickness of spiral? Skin Modifier?

**Comment by zeffii** [comment]
there is a scriptnode that for every point on the spiral (call this P) , will output two points with a center/median based on the point P, and their angle based on the angle of P in the spiral. Their 'scale' from the point P is decided by one of the components of the RGB pixel closest to P. 

I don't recall exactly how I did it, but all the code is there in the .blends on the other issue.

The image above isn't actually a greasepencil stroke, but if I had time and desire I would make something that is image dimension agnostic, ... but it's more effort than I felt was worth it, and plus... the effect has been truly done already and hardly novel. It's up to someone else who wants to learn by experimentation :)

**Comment by enzyme69** [comment]
It is going to be me to deconstruct this Sverchok goodness! Thanks for
hints!

**Comment by enzyme69** [comment]
@nortikin 
We do have folder already with some awesome examples from @zeffii 

![screen shot 2016-12-14 at 11 20 45](https://cloud.githubusercontent.com/assets/3952687/21164789/670b19a8-c1ef-11e6-8a51-55928d1a1bf4.png)

Hey, I think GP and SV are awesome team together. Maybe one day we have special node to filter grease pencil etc.

**Comment by enzyme69** [comment]
@zeffii By the way, your SN Lite seems to reset itself when Blend reloaded.

**Comment by enzyme69** [comment]
![screen shot 2016-12-14 at 11 54 02](https://cloud.githubusercontent.com/assets/3952687/21165549/1a529884-c1f4-11e6-9230-7a706d4630b2.png)
![screen shot 2016-12-14 at 11 54 09](https://cloud.githubusercontent.com/assets/3952687/21165548/1a5233bc-c1f4-11e6-81da-ef40d1e43394.png)

I realized NODE is a shorcut. I can achieve "cool stuff" with few nodes, but not learning much. But if I understand what's going on underneath and can code NODE then it's a big learning boost.

**Comment by zeffii** [comment]
> @zeffii By the way, your SN Lite seems to reset itself when Blend reloaded.

i'm not sure what you mean, I _can_ say that whatever it is.. if it bothered me it would probably be fixed already :) you'll need to explain a little.

**Comment by enzyme69** [comment]
@zeffii opening a blend file with SN Lite for Spiral for example, resets it to its default value sets in the Text, instead of keeping the values in the node that is set earlier. Needs a way to save the preset or maybe I should plug something into the node to keep the value as it is?

**Comment by zeffii** [comment]
ok yes, I see. This hasn't bothered me yet, but it's a valid point.
