### ISSUE TITLE
Kosvor SV Script Node Particle Tracing has a glitch

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1041]
Previously:
https://github.com/nortikin/sverchok/issues/1037

I was using @Kosvor2  technique to load Particle System and then tracing it using Sverchok, but I kept getting one extra edge. 

![extra_edge_error](https://cloud.githubusercontent.com/assets/3952687/21134577/a8e4f1d2-c172-11e6-9a39-820e1cd49cf2.gif)

SETUP: (make a bunch of Particle System emitted from a single point, then load them into Object In)
https://gist.github.com/cb483aa51eaa8f5b60e5c3d2d8d2bb21

I talked about it here:
https://youtu.be/S3uschDguJk

I use Animation Nodes to drive the Emitter, but I realized I don't need it.

**Comment by enzyme69** [comment]
If I were to "delete" one of that extra edge bit, I can use Edge Slice, it seems to be the last edge in the edge indices.

![list_edge_delete_001](https://cloud.githubusercontent.com/assets/3952687/21134775/6f98006c-c173-11e6-8215-0a50f201730c.gif)

**Comment by enzyme69** [comment]
My current solution is just:
https://gist.github.com/bdfc02ea8748d982beb849e0c227cc86

**Comment by Kosvor2** [comment]
yes, or like this:

![list_item](https://cloud.githubusercontent.com/assets/22656834/21135184/fff8f2a2-c131-11e6-9d6e-3176450cba40.png)

**Comment by zeffii** [comment]
anything that uses `object in` you might aswell just share the zip/blend , the gist will crash here.

**Comment by enzyme69** [comment]
Ah, ok got it :) Thanks for the tips.  @Kosvor2 

@zeffii  Ok understood.

**Comment by enzyme69** [comment]
[ANSV_particle_tracing_one_004_2016_12_13_10_10.zip](https://github.com/nortikin/sverchok/files/648551/ANSV_particle_tracing_one_004_2016_12_13_10_10.zip)

**Comment by enzyme69** [comment]
![screen shot 2016-12-13 at 21 12 28](https://cloud.githubusercontent.com/assets/3952687/21136222/df2a96b0-c178-11e6-9e17-a8f54f57042f.png)
@Kosvor2 

Although that above does not work. I miss something.

11 particle system, 11 indices list, I need to remove last indices for every 11 particle system in 11 list.

Do I use Int -1 and repeat 11 times?

**Comment by zeffii** [comment]
i can't load that either @enzyme69  . oh well :)

**Comment by enzyme69** [comment]
![screen shot 2016-12-13 at 21 21 36](https://cloud.githubusercontent.com/assets/3952687/21136546/2d948c06-c17a-11e6-95dd-fbbb90f890a8.png)

How odd... I can load. Wait...

**Comment by enzyme69** [comment]
@zeffii what is the error message when opening? hmm... .strange.

**Comment by enzyme69** [comment]
![screen shot 2016-12-13 at 21 24 14](https://cloud.githubusercontent.com/assets/3952687/21136634/85792bfc-c17a-11e6-8629-59e0423268c4.png)

It's a simple setup except for that "Vector Noise" setup that I always do which is basically "Vector Wiggle".

**Comment by Kosvor2** [comment]
works with 4 lists, so must work with 11:

![12dfg12](https://cloud.githubusercontent.com/assets/22656834/21136688/a5269482-c137-11e6-85dc-1afde003ce6d.png)

**Comment by zeffii** [comment]
no error - that just freezes blender here.  but that doesn't matter. 

I think the issue is not a glitch, but rather a symptom of the what blender indexes the particles, I noticed a while back that there's an off-by-one in the index, I think you should start indexing at 1 and not 0 (which would be more logical)

**Comment by zeffii** [comment]
generate a single particle trail, then look at all their indices at once, i think you'll notice its a little weird. show me :)

**Comment by zeffii** [comment]
i think you might be generating one too few particle locations..

**Comment by enzyme69** [comment]
[single_particle_002_2016_12_13_10_39.zip](https://github.com/nortikin/sverchok/files/648621/single_particle_002_2016_12_13_10_39.zip)

Single Particle, using Kosvor Script, also gives this one extra edge.

I cannot get List Item to work, mildly frustrating, the fact that I know I just need to remove one indice, it's weird. 

I can use List Slice though.

**Comment by enzyme69** [comment]
It's quite strange that your Blender keeps on freezing. Maybe reinstall Blender?

(In the way, this one is more like mesh point tracing. In the next one, I will try to do Particle tracing. I need to constraint Particle Emitter.)

I recorded the whole step again, took me around 5-8 minutes. Uploading the video:
https://youtu.be/W_muZryPysg

Thanks for your time checking this btw.

**Comment by enzyme69** [comment]
I got the List Item to works, but can't get that weird edge to disappear, however I am happy with List Slice :) Thanks!

**Comment by zeffii** [comment]
My blender freezes reproducably, this doesn't worry me :) ..subject for a different discussion/issue
