### ISSUE TITLE
SV PiSonic Experiment

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1043]
I am using @zeffii SN Lite to test this Python PiSonic thing, it works quite well :)

```
"""
in notes s d=[[]] n=1
"""

# SOURCE
# https://github.com/gkvoelkl/python-sonic

import sys

# find path to pysonic for python 3.5 in this case

pysonic_path = r"/Users/jimmygunawan/anaconda/envs/py35/lib/python3.5/site-packages"

if not pysonic_path in sys.path:
    sys.path.append(pysonic_path) 
    
from psonic import *

for i in notes:
    play(i)

```

Still pretty basic at the moment, just random values, with Sonic Pi running in the background.

I was inspired by Atsushi Tadokoro Processing Tidal
https://vimeo.com/160563352

**Comment by zeffii** [comment]
it's not a question!

**Comment by zeffii** [comment]
Tidal Cycles could be controlled via SN Lite .. i think, it's really just evaluating strings..
