### ISSUE TITLE
Skin Mesher Update is later than Render.

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1045]
I have this weird issue where the Sverchok Update will apply to the mesh a bit later than actual render. It's the Skin Mesher beta node.

Not sure how to fix this.

**Comment by enzyme69** [comment]
![spiral_issue_update](https://cloud.githubusercontent.com/assets/3952687/21171295/15dbd3bc-c21f-11e6-9c4d-15cdc63cc409.gif)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21176630/e4bfaf38-c1e7-11e6-84b2-61b9fcc21ae8.png)

it might be as simple as changing the even handler to `pre` or  post..   or we might need a `bpy.app.handlers.render_pre`  handler to update the node tree prior to starting a render frame.

**Comment by enzyme69** [comment]
Still getting the same result with Skin Mesher. It will render, then it
calculates my spiral displacement and reading the modifier.

**Comment by zeffii** [comment]
yeah, i think should be a `render_pre` handler if we really wanted to support this.

you could do a test by writing your own event handler (for render_pre ), and switch the Sverchok frame change handler to 'None' .

**Comment by zeffii** [comment]
something like
```
import bpy

def my_handler(scene):
    print("pre render frame", scene.frame_current)

    # all sverchok node trees
    bpy.ops.node.sverchok_update_all()

    # just one specific
    # bpy.ops.node.sverchok_update_current(node_group="NodeTree")

bpy.app.handlers.render_pre.append(my_handler)


```

do not repeatedly execute this code in the TextEditor, it will keep adding handlers ..
