### ISSUE TITLE
objects_mk2 freeze

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1047]
let me know if you experience this freeze, I will revert the last pullrequest. If i had known this was happening I would not have pushed in the first place.

reproduce

1. add any four mesh objects to the scene
2. add objects_mk2 to node tree
3. select two of the mesh objects , and press Get Selection
4. try to delete one of the two currently unselected objects.  

Freezes here, but _why_ is beyond me.

**Comment by zeffii** [comment]
I reverted for simplicity..

**Comment by zeffii** [comment]
OK.. i rolled back and exactly the same thing happens before my edits... i think it's a windows thing.  Can anyone test this sequence of events to see if it happens.. on linux/mac  @enzyme69  @portnov  @ccamara  @taxpon  @ly29

**Comment by enzyme69** [comment]
Got Torus not found error on Mac. But no freezing.

I might test this out on Windows 7, maybe later.

**Comment by zeffii** [comment]
let me be more accurate in my description of the scenario that freezes ..

1.  start a fresh .blend with a new empty NodeTree
2.  add 4 Objects ( Cube, Plane, Torus, Monkey , move them around a little )
3.  add objects_mk2 to nodetree
4.  select Cube and Plane in 3dview, press Get Selection on objects_mk2
5.  hook up objects_mk2 to Viewer Draw Mk2 (inlcuding matrices)
6.  observe that the object data is being displayed by VDMK2
7.  try deleting Torus or Monkey   (yep, not the objects that we collected for objects_mk2....)

this freezes blender here..

**Comment by zeffii** [comment]
![unngif](https://cloud.githubusercontent.com/assets/619340/21257587/3efc7d7c-c379-11e6-817f-44e64dd3e06d.gif)

**Comment by zeffii** [comment]
but it doesn't freeze if I first disconnect objects_mk2 from Viewer Draw, and then delete the torus.

**Comment by zeffii** [comment]
helpful irc triage by lijenstina 

    <lijenstina> zeffii, i've tried a 2.77.3 build and it works
    <lijenstina> from 2016-08-26

**Comment by zeffii** [comment]
possibly https://github.com/lukastoenne/blender/compare/cc8132b0c83e60d46e24ecec93744f0dd2b5db90...841f3e49725685b64f54c8dff6f29dab7bc223ee#diff-406550b469dd898c4c5989bb23b0fd2dR1844

**Comment by zeffii** [comment]
if i can find builds between `2016-11-13 < > 2016-11-27`  for win64 it's easier to put the blame somewhere

**Comment by zeffii** [comment]
[some_chore1_sel.zip](https://github.com/nortikin/sverchok/files/658023/some_chore1_sel.zip)

1. Two objects are already selected
2. press Get Selection on Viewer Draw
3. Connect
     - Vertices - > verts , 
     - Edges (or Polygons) -> EdgePol
     - Matrices -> Matrix
4. you'll see the Viewer Draw will generate bgl overlay drawing
5. now try to delete the donut or the monkey

**Comment by zeffii** [comment]
[some_chore1.zip](https://github.com/nortikin/sverchok/files/658052/some_chore1.zip)

this blend will load in older version of Blender but not in the later versions where the above bug is also encountered.

**Comment by zeffii** [comment]
the issue here is Blender and I haven't been able to compile it for windows to track down the exact commit where the bug was introduced.  closing because it's not somethinf we can fix in the tracker

**Comment by ly29** [comment]
Okay, actually if that is the issue we could actually stop using the ```update``` function for execution and start using a scene handler which executes if things have changed.

A handler like this
```python
def sv_main_handler(scene):
    for ng in sverchok_nodes_trees():
        if ng.changed:
            ng.process()
```
And update in the ```NodeTree``` changes to

```python

    def update(self):
          self.changed = True
        
```

**Comment by ly29** [comment]
Then we execute in a different context potentially avoiding similar problems?

**Comment by ly29** [comment]
Or is the problem also triggered by having us create new socket from the update function? That is something that should be supported, but even then we could do that instead via some other things.

**Comment by zeffii** [comment]
am waiting for a win64 build to include these changes. (I can only sink so much time into trying to get blender to compile here... )

**Comment by ly29** [comment]
Us using the ```update``` function instead of a scene handler has no real effect on us, nor is there any real thought behind the choice, if I had known it was wrong I would have done it differently.

It is from the time before when everything happened during the ```update``` calls which was horribly fundamentally broken in many ways but still worked surprisingly well...

**Comment by zeffii** [comment]
but where is that update function?  oh shit... this? https://github.com/nortikin/sverchok/blob/master/node_tree.py#L365-Lundefined

**Comment by zeffii** [comment]
for the record, I don't know if these new commit on Blender.org actually fix the freeze,  yet.

**Comment by ly29** [comment]
But keep crashing build around and let us see if that fixes it.

**Comment by ly29** [comment]
@zeffii 
Exactly that one. It is the context of everything that happens.

**Comment by zeffii** [comment]
could fix a few of the other crashes that don't seem to have anything to do with the content of a node.. but are a direct result of a menu operation / (adding from search, or deleting from scene)

**Comment by ly29** [comment]
>could fix a few of the other crashes 

Most likely, it is change we should push none the less. 

It should be very easy to do... We might have to review some nodes specific updates functions as well.
