### ISSUE TITLE
Object ID and Lattice Exploration

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1052]
I wanted to play with Lattice Points using Sverchok.

What is a good way to actually do this? I can see co and co_deform, co being the original position / current position and read only. co_deform actually can be modified. I tried below:

![screen shot 2016-12-20 at 19 14 49](https://cloud.githubusercontent.com/assets/3952687/21342977/b9965ffe-c6e8-11e6-8ca3-6c5e8cce2a6e.png)

**Comment by enzyme69** [comment]
Wonder why I cannot use data.points[:].co_deform? And also with Object ID GET, can I be more specific like wanting to GET the Vertex positions of mesh?

**Comment by Kosvor2** [comment]
_[:]_ turns  _data.points_ into python list like _[p[0],p[1],p[2],p[3]]_ so you need to use another "set" node to aply something to yeach _P_ inside those list.

**Comment by enzyme69** [comment]
![screen shot 2016-12-20 at 19 32 37](https://cloud.githubusercontent.com/assets/3952687/21343505/16f55a90-c6eb-11e6-9201-a177b4321c81.png)

Full of questions:
1) A lattice with multiple points
2) Multiple Lattice with Multiple Points

I feel like wanting to document this Object ID inside out.

**Comment by nortikin** [comment]
we need new objectID get-set
i have thoughts, but not time. ASAP will make my evrsion mk2

**Comment by Kosvor2** [comment]
![lattice](https://cloud.githubusercontent.com/assets/22656834/21343788/72d02ddc-c6a9-11e6-94dd-f4c10ebec85f.png)

**Comment by enzyme69** [comment]
Thank you K N I will try this!

**Comment by enzyme69** [comment]
![screen shot 2016-12-20 at 20 30 39](https://cloud.githubusercontent.com/assets/3952687/21345184/364d4f94-c6f3-11e6-8950-8b1295f1d32c.png)

One more thing, @Kosvor2 How to mix Sverchok usual data way with Object ID data? Script node?

**Comment by Kosvor2** [comment]
_[:]_ also can turn _Mathutils.Vector_ to tuple (most of Sverchok nodes cant work with _Mathutils.Vector_ data),
There are other problems also... some nodes want vertices data to be passed from vert socket instead of this green data socket. Vector math node on pic outputs nothing. Try to change socket type using Convert socket node. Or its because of wrong nestines (8 and 1 in inputs).

**Comment by enzyme69** [comment]
![screen shot 2016-12-20 at 21 43 24](https://cloud.githubusercontent.com/assets/3952687/21347578/5c3b926a-c6fd-11e6-8eb3-fb1865ea767a.png)

Hmm... Socket convert does not like it. 

But you are probably right the data isn't recognized. Nestines.. I tried List Join, still does not do it.

This is a single Lattice, wonder if multiple Lattice also gonna be complicated.

By the way Object ID MK2 is not yet in latest update.

**Comment by Kosvor2** [comment]
Use _co[:]_ instead of _co_ to output tuples. Converter is working, it seems... list join node to add one more level of nestiness... to make it _[[data, data]]_ instead of _[data, data]_

**Comment by Kosvor2** [comment]
Actualy with _MK2_ you not need to use _list join_ node:

![lattice_mk2](https://cloud.githubusercontent.com/assets/22656834/21350332/c86da65c-c6c7-11e6-8473-d29896cffb02.png)

**Comment by nortikin** [comment]
@Kosvor2 it is really hard to start with this node. But powerfull it is, yes

**Comment by enzyme69** [comment]
Thanks so much! Yes, it's hard :D but interesting too.

Make a LIVENODING video:
https://youtu.be/LiB90D5fX-E

Anyhow, documentation and more examples should help. Wonder if trying to access multiple lattice will be hard as well.

Will check other TYPE of OBJECT and try it with Script Node Lite of Zeffii.

**Comment by nortikin** [comment]
Ждём документацию, очень нужна, @Kosvor2
