### ISSUE TITLE
Simple Elegant Transition of Points

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1053]
I got confused on a simple matters.

I wanted to do this kind of elegant transition of bunch of points:
https://twitter.com/yncywy/status/724344226985598976

Supposed, I just have Circle, maybe bunch of Circle with multiple points. Maybe 2 circles only for now. I use Vector Interpolation but getting a lot of points.
https://gist.github.com/b0fe6df5513c5c1b3aabc66fb9d28079

I just wanted to transition point from one to next, each one stagger offset, with noise.

![screen shot 2016-12-20 at 19 55 06](https://cloud.githubusercontent.com/assets/3952687/21344110/392c9382-c6ee-11e6-9d4e-1f0e30d33ed0.png)

It should be easy with Sverchok, but why I can't figure out.

**Comment by enzyme69** [comment]
AN setup would be like this:
![screen shot 2016-12-20 at 19 59 44](https://cloud.githubusercontent.com/assets/3952687/21344248/e407bb4c-c6ee-11e6-942d-8fefab869635.png)

**Comment by zeffii** [comment]
one way to do it..

keyframe the value of `old_min`  in the maprange node,  from `-50 ... 1.0`  over 20 frames 

[wazbak_2016_12_20_15_30.zip](https://github.com/nortikin/sverchok/files/664065/wazbak_2016_12_20_15_30.zip)

![uhllgif](https://cloud.githubusercontent.com/assets/619340/21356540/476d7e8c-c6d2-11e6-90c9-3d76d30d5cb3.gif)

**Comment by nortikin** [comment]
commented on youtube
```
maybe try to sort vertices by attractors to control start-end animation shifting? Like that https://gist.github.com/0d5ff3d64312fac2fb261e2582a76bdf
or like this
https://gist.github.com/54aa385d050454f3f3e403520328c93f﻿
```

**Comment by enzyme69** [comment]
Thank you all, I will give a study.

**Comment by enzyme69** [comment]
@nortikin Distance and Crossover.... what... that's new for me.

**Comment by nortikin** [comment]
it is mistake named, cross over. maybe better every vertex with every. every is better name
