### ISSUE TITLE
Complex Elegant Transition of Points

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1054]
I manage to make sense of this transition animation of points in a sane way.

https://gist.github.com/4bd20b2f7c53cdefbbaaddb33fa8ccc9

Now, instead of Evaluate Vector node, I wanted to use Vector Interpolation node to do the same thing. And it failed.

https://gist.github.com/33ca106597081077b7ab90b26dbb11bd

I will check the data differences....

**Comment by enzyme69** [comment]
I think I am into something.

This one:
![screen shot 2016-12-23 at 11 37 00](https://cloud.githubusercontent.com/assets/3952687/21444660/2579e106-c904-11e6-9193-fe3b9c4d46cd.png)

Translate into:
10 points, translating through 10 different point position, each doing the same path, at 10 different times.

**Comment by enzyme69** [comment]
What I am trying to do:
10 points, traveling through 10 different path, each at 10 different positions, each at 10 different times.

**Comment by enzyme69** [comment]
The more I think of it.... how do you stay SANE trying to do this :)

I imagine people who animate using just code... 

In Processing, I recall people make Class and Function for Class.

If in 3D, people often end up using Particle simulation.

**Comment by zeffii** [comment]
I think when you decide to code more, you will become better at describing problems in detail, Often the act of describing the problem in all the details you can think of is the first step towards a solution. Sometimes I write a question on BSE and before I submit, a solution enters my mind because that was the first time I fully described the problem in writing. (This is a common thing among coders)

I'm not certain I understand exactly what your question is here in this thread.

**Comment by enzyme69** [comment]
Yes, I was trying to do too many things at the same time. In one side, trying to understand the Vector Interpolation better. It's like Evaluate Vector is simpler, but not really, especially if I started to add stuff like:
- multiple points inputs
- wanting to control points individually.

Basically wanting to do effect like Blender Keyed Particles. Points moving from positions A, to B, to C, etc. But I wanted to have fuller control over the points motion.

Hope that is better question. If too hard, we can close this.

**Comment by zeffii** [comment]
i still don't understand the question, it seems very similar to https://github.com/nortikin/sverchok/issues/933

**Comment by enzyme69** [comment]
Similar but with added complexity. I keep thinking: this probably can be
simpler.
