### ISSUE TITLE
Preview doesn't clean up after remove/disconnect

### ISSUE THREAD

**Issue by ValooFX** [nortikin/sverchok#1055]
Hi, i just discovered this amazing addon.
When playing around with it i noticed that the preview doesn't get cleaned up neither when i disconnect the viewer node nor when i delete the whole layout.
http://i.imgur.com/Y36yHCt.jpg (here it's just the output of a single line node into a 'viewer draw' node and after i deleted the layout)
A workaround is manually hiding each layout preview before deleting it, but it doesn't feel like it should be this way.

**Comment by zeffii** [comment]
This is due to caching of the last openGL draw instructions, i'm inclined to agree that this could be modified to remove the callback when no sockets are connected or when a node or node_tree no longer exists.

No ETA on this, but I'm sure we could make a one-liner to detach all callbacks..

**Comment by zeffii** [comment]
btw, when you press X on a nodetree, it doesn't get removed until you save/reopen the blend. Just like materials. This means if you press X on a node tree and it looks like it's gone, it's still going to show up in the node tree dropdown, and it will still be drawing the openGL instructions.. 
![uhgif](https://cloud.githubusercontent.com/assets/619340/21466613/1f018c7a-c9d1-11e6-8e0c-b0afdda0a543.gif)

**Comment by zeffii** [comment]
disconnecting the viewer node should remove the `draw_callback`, but i wouldn't be surprised if there are scenarios when this doesn't happen - i haven't experienced this lately. I'll have to poke around about.

Thanks for the report!

**Comment by zeffii** [comment]
OK, wasn't hard to track down. The problem you describe happens when you delete the input node ( like the Line node) , but not strictly when you manually disconnect the sockets first. This is down to a caching of the last draw callback. and a delete of a node doesn't trigger an update/process in the nodes downstream (in this case the Viewer Draw) , so there's a bit of stale/cached drawing info..

do you agree that this describes the problem?

**Comment by zeffii** [comment]
i'm not able to reproduce the scenario where removal of the Viewer Draw node doesn't also remove the drawing instructions in 3dview..

**Comment by zeffii** [comment]
did you use the console to delete the layout?  something like the following works if you don't have the node view window visible..
```
>>> bpy.data.node_groups.remove(bpy.data.node_groups[0], do_unlink=True)
```

**Comment by zeffii** [comment]
also you can execute this from console to remove all drawing done by sverchok
```
>>> from sverchok.ui.viewer_draw_mk2 import callback_disable_all
>>> callback_disable_all()
```

**Comment by ValooFX** [comment]
Hi, i've not yet tested the console commands, but interestingly, after restarting Blender cleaning up after a disconnect of nodes does work now. I recorded when it still doesn't: https://www.youtube.com/watch?v=bYtYJj4TeI4

**Comment by zeffii** [comment]
cool. OK. we can add an additional `callback_disable_all()` into the hard_clean operator. It's not a panel I use much in 3dview.

**Comment by ValooFX** [comment]
Maybe consider doing that on an unlink (set users to 0) too (shift x-click) for me it felt natural to expect the preview to vanish.

**Comment by zeffii** [comment]
I concur, however I don't think there's a way to override the 'shift x-click' behaviour -- these kinds of overrides will be implemented I think in Blender 2.8.

**Comment by zeffii** [comment]
making a button to close any nodeview that shows a Sverchok node tree, and then removing all such node trees / remove drawing callbacks  is fairly easy. But I won't be adding this immediately.

**Comment by ValooFX** [comment]
Ah, ok. Thank you and merry christmas :-)
