### ISSUE TITLE
Socket Convert - Vertex Weight Group (Polygon vs Data) - Post Modifier

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1057]
![screen shot 2016-12-26 at 10 55 11](https://cloud.githubusercontent.com/assets/3952687/21473302/dd36b556-cb59-11e6-9fa4-8b52eae4d43a.png)

I am working on this Vertex Group Weights, trying to generate list of pattern of weights to control the Displacement Modifier.

I realized sometimes Sverchok generate DATA, sometimes generate POLYGON data, they both are similar.

But Vertex Group Weight node does not understand DATA. I tried Socket Convert, it seems to fail.

Random Num Gen node and Vector Out Float List from Random Vector MK2 generate this POLYGON data that Vertex Group Weight node like.

But using my own Formula or converted Boolean List, it fails.

https://gist.github.com/f0c78665eee04d18abe361849f20a13e

**Comment by enzyme69** [comment]
![screen shot 2016-12-26 at 10 59 19](https://cloud.githubusercontent.com/assets/3952687/21473323/60bc5106-cb5a-11e6-8453-b070cf2b0b06.png)

**Comment by enzyme69** [comment]
What....... str()

![screen shot 2016-12-26 at 11 19 14](https://cloud.githubusercontent.com/assets/3952687/21473395/28f92f48-cb5d-11e6-8dd0-5bad284adf6c.png)

**Comment by enzyme69** [comment]
Still didn't work with the Vertex Weight Group node :(

**Comment by enzyme69** [comment]
![screen shot 2016-12-26 at 11 24 37](https://cloud.githubusercontent.com/assets/3952687/21473404/e959408e-cb5d-11e6-9118-ceafbc20da85.png)

**Comment by enzyme69** [comment]
@Kosvor  @Kosvor2 

I read this and didn't understand what is going on
https://github.com/nortikin/sverchok/blob/master/nodes/object_nodes/weightsmk2.py

**Comment by enzyme69** [comment]
I tried generating the value using SN Lite, if I use rand() it works, if I use float(i > 200) it failed...

![screen shot 2016-12-26 at 11 43 43](https://cloud.githubusercontent.com/assets/3952687/21473458/956fa87a-cb60-11e6-8206-82d4ec121b43.png)


```
"""
in num_items s d=242 .=2
in radius s d=1.0 .=2
out verts v
"""
from random import random as rand
from math import sqrt, cos, sin, pi as M_PI

verts = []
for i in range(num_items):
    
    mynum = float(i > 200)
    #mynum = float(rand())
    verts.append( (mynum, 0.0, 0.0) )
    #verts.append( (0.2, 0.0, 0.0) )
    #print(type(mynum))

verts = [verts]
```

**Comment by enzyme69** [comment]
Still NOPE.
![sv_hate_me](https://cloud.githubusercontent.com/assets/3952687/21473492/ea0d796a-cb61-11e6-9324-0ad362f1c485.gif)

**Comment by enzyme69** [comment]
I know why: Vertex Weight does not read the object "Post Modifier". I have been stuffing this weight data into original Icosphere (before subdiv).

Can we have Post Modifier option in Vertex Weight ... =_=

**Comment by enzyme69** [comment]
Objects in MK2 Post Modifier -> Stuffed into Vertex Weight Object, does not read it as post.

**Comment by enzyme69** [comment]
Also, is there a way to control Post Modifier but at different stage of Modifier?

**Comment by Kosvor2** [comment]
Weights MK2 seems broken... i will change it to new version right now. As for post modifiers - it cause crashes in weights node immediately, so i dont see a way to implement it.

**Comment by enzyme69** [comment]
Great, I will check the update. It's ok if the post modifier at the back end is tricky, maybe some time later.
