### ISSUE TITLE
SV Image Processing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1059]
For doing stuff like IMAGE PIXEL processing like Median Stacking, can Sverchok be hacked to do that with Image?

Just like Compositor?

I think it would be nice to SOURCE IMAGE > DO SOMETHING TO PIXEL > OUTPUT IMAGE.

Or IMAGE SAMPLING example.

Because 2D Image is like GRID, and I realized that under certain configuration, especially when working with Face Color via Vertex Color, it's like making image processing.

**Comment by Kosvor2** [comment]
Here hack with v # command is used to apply entire list of values to object instead one by one:

![image_mod](https://cloud.githubusercontent.com/assets/22656834/21495780/b77b479c-cc2a-11e6-8344-035d1acbbdb4.png)

tested with only one image with very low amount of pixels.

**Comment by Kosvor2** [comment]
Previous method changes the image from which pixels are taken.
Here's a way to keep the original image such as it was:

![image_mod2](https://cloud.githubusercontent.com/assets/22656834/21497678/c1237316-cc37-11e6-95a4-3b8315c554b5.png)

That is, needed to create two images, share them with the filter node and changing the values of pixels of the first image, apply these values to the pixels of the second image.

**Comment by enzyme69** [comment]
Thanks Kosvor for some examples to get me started!

I always wonder what Object ID can and cannot do --- together with MultiLines Exec or ScriptNode.

I will give this a try.

I was previously trying to use SV Vertex Color node. Maybe under 4 Megapixels (4 million ish faces) should still be possible. 

If animating, maybe Dynamic Paint can bake out the Face Vertex Color. But don't know yet.

In one side, I think OSL and Blender Material Noding is probably a more suitable tool.

I'll investigate your example.

**Comment by enzyme69** [comment]
The funny thing is that we can probably save vector positions of an object as image, and then if the image is sequence, it can be read in Unity or UE as "vertex displacement".

I remember one guy doing this using Houdini.

**Comment by enzyme69** [comment]
From your method, I am using 35 x 25 pixels of emoji and the list I get is list of 3500 (35 x 25 x 4). I assume they represent RBGA (4 values)?

This is actually really interesting, but might be slow for big hires pixel image. But I can make video tutorial about it I guess.

![screen shot 2016-12-27 at 22 34 00](https://cloud.githubusercontent.com/assets/3952687/21498851/9e6f98fc-cc84-11e6-8c5f-0900c1d68f51.png)

🍩

**Comment by enzyme69** [comment]
![screen shot 2016-12-27 at 22 52 15](https://cloud.githubusercontent.com/assets/3952687/21499137/30be463e-cc87-11e6-92c3-a6fd74c1adc1.png)

640 x 480 pixels are pretty fast, just few seconds to process :)

But 100 x 100 should be a good start. I remember DBN Program.

I can finally make Node Script that bend and move pixels, thanks for the tool~

**Comment by enzyme69** [comment]
![screen shot 2016-12-27 at 23 00 40](https://cloud.githubusercontent.com/assets/3952687/21499252/51f56016-cc88-11e6-8c18-3c1b2e8c8604.png)

Any tips on handling RGBA? Should I use LIST ZIP?

**Comment by enzyme69** [comment]
![screen shot 2016-12-27 at 23 08 00](https://cloud.githubusercontent.com/assets/3952687/21499375/575896a8-cc89-11e6-96c2-b156e6ce5fa7.png)

Finally we have Color Viewer SV :D

**Comment by enzyme69** [comment]
Just wondering, I plug in 40000 list of values into Object ID Set, but the output of Object ID Set is 4 x 40000 = 160000, any idea why?

**Comment by enzyme69** [comment]
@zeffii any idea of previous Script node that deals with RGBA that I could study?

**Comment by enzyme69** [comment]
I remember my old post... will attempt to convert to SN Lite DrawPixel and SN Lite Draw Pixel RGBA 

http://blendersushi.blogspot.com.au/2013/03/python-pixel-art-in-blender.html

**Comment by enzyme69** [comment]
![screen shot 2016-12-28 at 12 54 02](https://cloud.githubusercontent.com/assets/3952687/21512072/cad42502-ccfc-11e6-9d7b-04cb46bb0637.png)

This one is sampling texture back into the Pixel Generator. It's probably a bit stupid because I am using Blender's own Procedural Texture to create pixel.

I would like to study number pattern more. Somewhat it needs to meet half way.

**Comment by enzyme69** [comment]
Using Sverchok or Python NumPy can be interesting though. PIL stuff.

**Comment by enzyme69** [comment]
Basically want to use NumPy, but skipping PIL, but in something that Sverchok can work with.

**Comment by enzyme69** [comment]
https://gist.github.com/bb2d12e8213ebe3ee744ca942817d20a

![pixelstory_002](https://cloud.githubusercontent.com/assets/3952687/21512244/cf77ddcc-ccfe-11e6-8bae-79ddd73bfca4.png)

**Comment by enzyme69** [comment]
Trying to think how to make a single white pixel just swim around...

**Comment by enzyme69** [comment]
![screen shot 2016-12-28 at 17 13 01](https://cloud.githubusercontent.com/assets/3952687/21515293/7ace9986-cd22-11e6-972a-dd35cd863cde.png)
![screen shot 2016-12-28 at 17 11 35](https://cloud.githubusercontent.com/assets/3952687/21515290/7acd9efa-cd22-11e6-9f8b-148dca9ed8a3.png)
![screen shot 2016-12-28 at 17 06 49](https://cloud.githubusercontent.com/assets/3952687/21515291/7acd8f82-cd22-11e6-9c2a-26a2184b3a54.png)
![torusknot](https://cloud.githubusercontent.com/assets/3952687/21515292/7acdfa76-cd22-11e6-8717-27a7cbb8dd30.png)

**Comment by zeffii** [comment]
> @zeffii any idea of previous Script node that deals with RGBA that I could study and implement here?

all scripts that read/write to blender image.pixels must deal with `rgba`, exercise some google fu.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21522813/0b117a0a-cd09-11e6-838f-f1ab77f82d2b.png)
i'd come up with something similar... `mesh -> png`

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21523280/fbfb7ac6-cd0c-11e6-80d6-831f6b77b269.png)
`png -> mesh`

**Comment by enzyme69** [comment]
That's SVORGASMIC.

**Comment by enzyme69** [comment]
It's gone slightly off topic, but very well done 💃 thanks so much~

XYZ to RGBA
https://gist.github.com/enzyme69/8e8284ed2f3fb2701ccfe455ffc73114

![screen shot 2016-12-29 at 11 26 28](https://cloud.githubusercontent.com/assets/3952687/21534346/ae42ec6c-cdb9-11e6-81a7-e712d4d3ee5d.png)

**Comment by enzyme69** [comment]
![screen shot 2016-12-29 at 11 46 09](https://cloud.githubusercontent.com/assets/3952687/21534514/7b66589e-cdbc-11e6-8a8e-48a182c7576d.png)
![screen shot 2016-12-29 at 11 46 04](https://cloud.githubusercontent.com/assets/3952687/21534516/7bbe08fa-cdbc-11e6-8e86-138a168d9035.png)
![screen shot 2016-12-29 at 11 46 01](https://cloud.githubusercontent.com/assets/3952687/21534515/7bbd2a5c-cdbc-11e6-85ee-957d92e898f1.png)

The RGBA to XYZ seems to fail, but I learn something about the masking, super interesting... 

https://gist.github.com/b9bbec8eb61583366cd2dc249551fbf5

**Comment by enzyme69** [comment]
I do not get the last part....

![screen shot 2016-12-29 at 11 48 19](https://cloud.githubusercontent.com/assets/3952687/21534533/ba5f1cc0-cdbc-11e6-9a60-c6f62944349d.png)

**Comment by enzyme69** [comment]
After the magic of tweaking and more careful observation of the recipe....

https://gist.github.com/9e3471a7590dd22b8d8e260d2323d977

This is a very good example of Sverchok :)

**Comment by enzyme69** [comment]
@zeffii  You also have some kind of Bounding Box and Centering mechanism. Very nice.

**Comment by zeffii** [comment]
that/my layout assumes the object's coordinates on any axis don't go beyon `[-1.0 .... +1.0]`  hence it's OK to `+1 -> / 2` . I imagine some interesting processing (hue, lightness... or jst in-painting) can be done to the bitmap to modify the resulting geometry..

**Comment by enzyme69** [comment]
I realized that maybe I should study Processing and algorithm more which could help with what I am trying to pursue.

**Comment by zeffii** [comment]
just do it.
