### ISSUE TITLE
Object ID Get - Stethoscope displays name a bit wrong

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1069]
Just a small bug I think displaying the data object names.

Supposedly Text, Text.001, Text.002.

![screen shot 2016-12-29 at 21 39 29](https://cloud.githubusercontent.com/assets/3952687/21542086/8c8e73c4-ce0f-11e6-8718-c7e45b1e66a9.png)

**Comment by Kosvor2** [comment]
There is lazy fix: https://github.com/nortikin/sverchok/commit/6dc2635193a3584013d9e422d66279dd8555e099

but it will not work if names are brought to stethoscope out of Set node with name as parameter.
The "Note" node is working correctly, use it instead.

**Comment by zeffii** [comment]
stethoscope's code was written before we got this rich variety of socket data, sooner or later `StethoscopeMK2` should be implemented. I started musing about it a while back. 

see: https://github.com/nortikin/sverchok/issues/914#issuecomment-262787914
