### ISSUE TITLE
Sverchok Metaballs Vertex Coloring

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1071]
[sv_dynamic_paint_metaballs_010_2016_12_30_00_05.zip](https://github.com/nortikin/sverchok/files/678080/sv_dynamic_paint_metaballs_010_2016_12_30_00_05.zip)

I am attempting to colorize Metaballs which has "blending" capability.

![sv_metaballs3](https://cloud.githubusercontent.com/assets/3952687/21557427/1cf4968a-ce80-11e6-9aa6-eaa2575a376a.gif)

Currently my approach is using Dynamic Paint Canvas (meshed metaballs) and Dynamic Paint Brushes (sverchok generate the mesh brush based on metaballs radius and position).

This approach failed because Sverchok is generating a new mesh and resetting the Vertex Color each frame.

I think, would be nicer if Sverchok has some kind of Reactor nodes. Easier than using Distance node that @nortikin shown... I still don't get how you can have this influence value over distance.

**Comment by enzyme69** [comment]
Maybe Particle Color and Point Density influencing Metaballs will be simpler, but still headache.

**Comment by zeffii** [comment]
you can't normally add a vertex_color layer to a metaball. the only reason you can is because of the metaball -> mesh conversion that happens every frame, In the example image you show that the vertex count changes when metaballs merge and break appart, this might invalidate the vertex_color layer due to changes in topology anyway.

I don't think object_in mk2 automatically generates a vertex_color layer (or if it does i'm not sure it resets it). Objects_in isn't deleting the objects , just switching the internal data (meshes).

I'm afraid without modifying the code you won't get much further with this..

**Comment by zeffii** [comment]
as you may know, there's no vertex_color layer 'stream' within sverchok - the only place you can set vertex_color layer is after something like bmeshviewer, from the resulting object socket,

not exactly a priority.  have a look at the code involved in the nodes you used here

**Comment by zeffii** [comment]
look at https://github.com/nortikin/sverchok/blob/master/nodes/viz/viewer_bmesh_mk2.py#L192

this is where creation / cleanup for Blender objects/meshes happens, notice that there's no automatic creation (or reset) of a vertex_color layer. This would be exactly where that _should_ happen. but it would be need to be an optional switch intially..so it doesn't break old layouts with the same node.

like 
```python

auto_generate_vcols = BoolProperty()

# somewhere after the creation of an object
if hasattr(self, 'auto_generate_vcols') and self,auto_generate_vcols:
    # something like this... untested
    obj.vertex_colors.clear()   # gotta wipe any existing
    obj.vertex_colors.new(name='SvCol')


# somewhere in the draw function
if hasattr(self, 'auto_generate_vcols'):
    layout.row.prop(self, 'auto_generate_vcols')
```

**Comment by enzyme69** [comment]
Hmm... seems to complex maybe scrap the idea for some other time.

**Comment by enzyme69** [comment]
Although, interested to know if Sverchok can have "Reactor" like influence like Dynamic Paint.... although that's like a big request. I thought that Dynamic Paint should be able to handle it, but not. 

Maybe, I should bake the changing mesh beforehand?

The conclusion I got is that DP does not like changing mesh. So ok we can close this.

**Comment by enzyme69** [comment]
![metaballs_coloring](https://cloud.githubusercontent.com/assets/3952687/21564460/feb7baaa-cee1-11e6-9328-94ee8e593ee0.gif)

Quick update:
I tried baking Sverchok metaballs meshing as Alembic...

Brought back in and set as DP Canvas, and tadaa... it works. Yeah, it's weird :)
