### ISSUE TITLE
can i use chinese character with Typography?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#1074]
as title

**Comment by enzyme69** [comment]
I think, if Blender cannot do it, maybe Sverchok cannot do it. But there might be a way, so let's wait for Sverchok developers answer.

**Comment by Kosvor2** [comment]
There is a way to make blender text object to show international fonts: https://youtu.be/PdLle7ZXWj8?t=23

But Sverchok Typography node will not save this settings, so no way to use it currently, sorry.

There is other ways to control locations of text objects, but create them can only Typography node, unfortunately:

![font_obj](https://cloud.githubusercontent.com/assets/22656834/21577054/bc861100-cf5d-11e6-90bf-635f073a24c7.png)

**Comment by stansu** [comment]
guys, i figure it out.
just add chinese font to blender then change viewer_typography.py's font type to chinese font, at line 60...

default = bpy.data.fonts.get('MicrosoftJhengHeiRegular')

:)

**Comment by zeffii** [comment]
you can set the font that typography viewer uses from the rightside toolpanel (N).

![image](https://cloud.githubusercontent.com/assets/619340/21577291/327190c2-cf56-11e6-8773-5de19ad62306.png)

but to get the chineese characters into something like a Note node you currently need to copy the chineese to a clipboard then:

![image](https://cloud.githubusercontent.com/assets/619340/21577297/5e2945fc-cf56-11e6-964e-6be0ba4d0f17.png)

press copy from clip board

**Comment by zeffii** [comment]
arguably the Node node should have a 'from text editor' button :)

**Comment by zeffii** [comment]
Rather than editing the code on line 60 to force the default, i suggest that you make a startup .blend that contains the desired font :) @stansu    but whatever is easier for you

**Comment by stansu** [comment]
Thanks!
I missed that panel.
