### ISSUE TITLE
If a perfect Triangles have Direction, on which direction will it face?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1078]
I hate to close this question too early...
https://github.com/nortikin/sverchok/issues/1077#event-908641609

I think one wants the need to understand Triangle and Normal and also the Vertex Normal control in Sverchok, that enables such Instancing of simple adapting Tris into Tris.

I will meditate...

**Comment by zeffii** [comment]
The normal of any face is decided by two things.

1. location of vertices
2. order in which the indices of the vertices are stored in the face's index list.

See: image here for illustration https://github.com/nortikin/sverchok/issues/902#issuecomment-252423059

Note the direction of the arrow, clockwise is one direction, counter-clockwise is the reverse direction.

**Comment by zeffii** [comment]
The normal of any face is decided by two things.

1. location of vertices
2. order in which the indices of the vertices are stored in the face's index list.

See: image here for illustration http://stackoverflow.com/a/15041831/1243487

Note the direction of the arrow, clockwise is one direction, counter-clockwise is the reverse direction.

**Comment by zeffii** [comment]
related: https://github.com/nortikin/sverchok/issues/1077#issuecomment-269947385

**Comment by zeffii** [comment]
this is still a valid image to use https://github.com/nortikin/sverchok/issues/902#issuecomment-252423059

![image mine](https://cloud.githubusercontent.com/assets/619340/19213247/aaf0c662-8d66-11e6-9915-0579e29f0d41.png)

note the index list on the left is what defined the polygons, and the order in which those vertex indices are shown is what determines the direction of the normal. 

![image](https://cloud.githubusercontent.com/assets/619340/21587542/f20a38fc-d0dd-11e6-9cb3-96e8d2759e31.png)

I think this fully answers the question of directionality.

**Comment by enzyme69** [comment]
Ok thanks I remember that post and sorry for asking the same thing, I think
the question is maturing for answers.



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
