### ISSUE TITLE
KDTree Connecting just connecting point within distance

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1079]
For this task, I just want to use KDTree to connect point that is closest within radius, Icosphere should be pretty easy because I think all the points are within same radius distance.

![screen shot 2017-01-02 at 12 40 45](https://cloud.githubusercontent.com/assets/3952687/21583926/f10606a6-d0e8-11e6-9e91-e13141ee0d31.png)

**Comment by zeffii** [comment]
i'm going to agree there's a flaw in the way i implemented this kdtree node -- rejecting valid edges, a fix was proposed 2 years ago. perhaps mk2 is in order.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21586807/66125e86-d0d5-11e6-84ab-2800a462420f.png)

**Comment by zeffii** [comment]
https://gist.github.com/152d365d8943d770c0802f41406aed04

![image](https://cloud.githubusercontent.com/assets/619340/21587019/b0439946-d0d7-11e6-8fa4-3a7a8927cd42.png)

**Comment by zeffii** [comment]
objects_in_lite will generate the icosphere in the blender scene too btw..  start with an empty .blend

**Comment by enzyme69** [comment]
Let me study this sometimes tomorrow! Thanks Sir Zeffii.

**Comment by zeffii** [comment]
I will make mk2 of this node.

**Comment by zeffii** [comment]
will fix in : https://github.com/nortikin/sverchok/tree/krtree_edges_mk2

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1081

**Comment by zeffii** [comment]
i didn't bump the version so no new update will be available. try a forced update..
https://github.com/nortikin/sverchok/issues/1039

**Comment by enzyme69** [comment]
Yeah, not quite sure about Force Update. And I have not been receiving new
update for a while.



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
The UI won't show new updates if we don't bump the revision. We haven't bumped it in the last few days.
To bypass this and update anyway, use that line of code.

> Yeah, not quite sure about Force Update

that tells me exactly nothing about 1. have you tried it 2. did it work / fail / something else.
