### ISSUE TITLE
JSON Input, is it still working?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1080]
I tried copy pasting some data that's supposed to be JSON type, but none of them are working. Unlike the simple CSV, what type of JSON data does Sverchok actually able to use?

I wanted to try with Instagram type of data for example.
https://code.tutsplus.com/tutorials/introduction-to-the-instagram-api--cms-23608
https://adobe.github.io/Spry/samples/data_region/JSONDataSetSample.html

I was watching this video tutorial earlier on NodeBox 3 and data type:
https://www.youtube.com/playlist?list=PL2X584G_KpfRMPXW68CxSuB9LlmUMOScQ

Can Sverchok read JSON type of data that contains:
- web URL for image 
- string
- etc

And then the output in Blender load displat that image, etc.

----

Actually IMAGE may be too much for now, how about if the JSON data is changing per frame for displaying DATA over TIME?

**Comment by enzyme69** [comment]
Or for a simpler kind of data JSON I would like to save PRESET for example. Pose Preset for Bones, etc...

**Comment by zeffii** [comment]
You are expected too much from this simple node, all it will do is load json that is specifically formatted to contain 'v', 's', 'm' member lists.. like 

{
   'v':  [[.....vertices], .... ],
   's':  [[...polygons oredges ... edgepol],  ....],
   'm':  [ [matrix for object], ... ]
}

read this code. https://github.com/nortikin/sverchok/blob/master/nodes/scene/text.py#L478-L492

It's not hard to make a general purpose json loader node, but TextIn is not such a node. Perfect learning opportunity if you want to get stuck in.

**Comment by enzyme69** [comment]
Got it! Cheers for this explanation. I think it's time for me to read the code for each node.... it's 2017, I will try.

Cheers.

**Comment by zeffii** [comment]
Do. Or do not. There is no try.

**Comment by zeffii** [comment]
if you look at the code before asking a question, you might find that you already will be able to get an idea of why something isn't working , link us to the code you think is problematic, this will then better inform your question, and make the process easier for us.
