### ISSUE TITLE
Distance Cross Over

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1083]
I feel the itch to explain this Distance node "Cross Over" at some point @nortikin is showing a way to use this as Influence. I still don't quite get it.

![screen shot 2017-01-03 at 19 39 16](https://cloud.githubusercontent.com/assets/3952687/21602855/6f90e438-d1ec-11e6-8aac-fb6d5f7bf0f5.png)

**Comment by enzyme69** [comment]
So if we have 2 points and bunch of points, what can distance do? How to mix the value from both to have more useful effect?

Rhino Grasshopper artist always loves to use this "influence" by distance. I like it too, but I rather use Dynamic Paint.

**Comment by enzyme69** [comment]
I am especially feel challenged to do what Commotion AddOn can do.
https://github.com/mrachinskiy/commotion
https://www.youtube.com/watch?v=gLj4PvHbm4s&feature=youtu.be

I think AN is trying to get to that point.

Wonder SV Object ID and Action can do offset, I think it's not that simple. Not so familiar with Blender Action BPY that can offset slide animation fcurve...

....

studying.

**Comment by enzyme69** [comment]
Maybe can do something with these attributes:
action.fcurves[0].keyframe_points[0].co

Old blog post, I did try to use BPY.
http://blendersushi.blogspot.com.au/2013/06/procedural-domino-array-animation-using.html?view=classic

**Comment by enzyme69** [comment]
![screen shot 2017-01-03 at 22 00 30](https://cloud.githubusercontent.com/assets/3952687/21605876/11f31300-d200-11e6-8dd7-c6d1da9367d7.png)

This actually does something to the keyframe points....

**Comment by enzyme69** [comment]
![screen shot 2017-01-03 at 22 16 16](https://cloud.githubusercontent.com/assets/3952687/21606258/4ef44e70-d202-11e6-9d97-457e7ddf1438.png)

Hmm... offsetting f-curve animation means dealing with many numbers apparently. Above should work, but probably not quite right.

I am pretty happy if we can control blocks of animation in and out. like sequence.

**Comment by enzyme69** [comment]
![screen shot 2017-01-03 at 22 21 25](https://cloud.githubusercontent.com/assets/3952687/21606352/ff75f4ba-d202-11e6-89e3-6d428a70dbe5.png)

NLA seems simpler to work with, but no access to this yet via Sverchok.

**Comment by ly29** [comment]
Using a distance to influence design is like getting a simple factor. It is more productive to think like functions.

Say ```height = dist(p0, loc)```, so if you have two points, you need a function that maps this in a sane way.

Could be ```height = min(dist(p0, loc), dist(p1, loc))``` for example, letting the minimum influence it. You could even weigh the influence of the points this way.

Anything you can think in functional form should work well with sverchok.
---

For animation a certain other system has more helpful functions,.. I don't have clue about animation so I havn't tried to implent such functionality. I am not against it however

**Comment by zeffii** [comment]
@enzyme69  you want to turn Sverchok into an animation goldmine, but you have to realize that we've stayed mostly focused on geometry/topology. (almost like a mission statement). 

There's an old saying

>  if all you have is a hammer, everything looks like a nail. 

Sverchok isn't intended / equipped to do everything with the least amount of effort, this means there will be some horribly convoluted setups for things that seem trivial. But this will be because there aren't dedicated Sverchok nodes for a feature, or you haven't taken the time to try to make a node-script and get your head around the `bpy` involved. yet.

**Comment by enzyme69** [comment]
Ok back to topic. Thanks @ly29 I'll try a simple setup first with this Distance. "Cross Over", Niki said was wrongly named. I don't get it.

I will try with 2 points.



With animation stuff... I realized something:
- Lots of motion graphics stuff can be done at low level already
- Sometimes animators prefer animating one and offsetting the animation or mixing

**Comment by enzyme69** [comment]
@zeffii Yes, you are right. I go back to Distance stuff.

**Comment by zeffii** [comment]
I take no pleasure in repeatedly saying Sverchok isn't for all needs. believe me :)

**Comment by zeffii** [comment]
but just to stand with what @ly29 , i also have no objection to add more animation stuff. but with the caviat that i also don't do animation, so not only do i _not_ need these features, I think it's better implemented by someone who does not that side of bpy and all its pitfalls/shortcomings/pros/cons/conveniences..

**Comment by zeffii** [comment]
but just to stand with what @ly29 said, i also have no objections to add more animation stuff. but with the caveat that i also don't do animation, so not only do i not need these features, I think it's better implemented by someone who does know that side of bpy and all its pitfalls/shortcomings/pros/cons/conveniences..

**Comment by ly29** [comment]
Cross over gives the distance between all points,

```
[v0, v1, v2]
[u0, u1]
# crossover
v0u0, v0u1, v1u0, ...
```

**Comment by enzyme69** [comment]
![screen shot 2017-01-03 at 22 40 00](https://cloud.githubusercontent.com/assets/3952687/21606748/9db31340-d205-11e6-8a5c-2929924ce20d.png)

Ok this part I understand now that I use brain.

**Comment by enzyme69** [comment]
https://gist.github.com/d922601979018837629cd7b5685e436d

**Comment by enzyme69** [comment]
Trying to mix 2 or more points....

**Comment by enzyme69** [comment]
I think Distance is not what I think it is. 

![screen shot 2017-01-03 at 22 50 43](https://cloud.githubusercontent.com/assets/3952687/21606950/1771da30-d207-11e6-9d9f-c81733bd18f0.png)


https://gist.github.com/a7b8897166babfb32e845b4f54636071

**Comment by ly29** [comment]
It would be more clear to reformulate the problem with list cross match and distance using the vector math node and staying away from the distance node.

**Comment by zeffii** [comment]
what you're looking for sounds like an _attractor / proportional editing_ kind of interaction between 1 or more points and a mesh. If so I do plan to implement something like that https://github.com/nortikin/sverchok/issues/914#issue-182487380 but no eta.

**Comment by ly29** [comment]
```python
    def calcM(self, list1, list2):
        ll1, ll2 = len(list1[0]), len(list2[0])
        if ll1 > ll2:
            short = list2
            long = list1
        else:
            short = list1
            long = list2
        dists = []

        for obsh in short:
            obshdis = []
            for vers in obsh:
                for obln in long:
                    oblndis = []
                    for verl in obln:
                        oblndis.append(self.distance(vers, verl))
                    obshdis.append(oblndis)
            dists.append(obshdis)

        return dists[0]
```

This is what crossover does if you want to dig into it...

**Comment by enzyme69** [comment]
Looks simple and elegant.

**Comment by enzyme69** [comment]
I will make few Live Noding Videos using Distance, but I think Ly makes a good point:
It would be more clear to reformulate the problem with list cross match and distance using the vector math node and staying away from the distance node.

And Zeffii, you read my mind clearly. 

I guess I can play a bit with this.

**Comment by nortikin** [comment]
who dealing now with "everything in nodes" stuff of blender?

**Comment by enzyme69** [comment]
Maybe only Lukas Tonne? He and his "Particle Nodes".

**Comment by nortikin** [comment]
lukas went out of BI as i know

**Comment by ly29** [comment]
Everything nodes is not an immediate goal any more, but they try to lay the foundation for it.
