### ISSUE TITLE
loading zipped .blend from link

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1084]
time to implement simple _in place_ loading for these urls generated by github for zips we paste into the issue tracker.

no ETA. but soon hopefully.

**Comment by zeffii** [comment]
for example: https://github.com/nortikin/sverchok/files/647412/scipy_voroi_2016_12_12_22_27.zip

**Comment by zeffii** [comment]
```python
import os
import urllib
import urllib.request
from zipfile import ZipFile

import bpy

os_temp_path = os_temp_path = r'C:\tmp'
self = lambda: None
self.download_url = "https://github.com/nortikin/sverchok/files/647412/scipy_voroi_2016_12_12_22_27.zip"

def execute(self, context):

    wm = bpy.data.window_managers[0]
    wm.progress_begin(0, 100)
    wm.progress_update(20)

    if not self.download_url:
        return

    try:
        file_and_ext = os.path.basename(self.download_url)
        to_path = os.path.join(os_temp_path, file_and_ext)
        file = urllib.request.urlretrieve(self.download_url, to_path)
        wm.progress_update(50)
    except:
        # self.report({'ERROR'}, "Cannot get archive from Internet")
        wm.progress_end()
        print(" return {'CANCELLED'}  ")

    try:
        err = 0
        with ZipFile(to_path) as zf:
            inner_files = zf.namelist()
            if len(inner_files) == 1:
                blendfile = inner_files[0]
            else:
                print('cancelled, not a github zipped .blend')
                return

        ZipFile(file[0]).extractall(path=os_temp_path, members=None, pwd=None)

        wm.progress_update(90)
        err = 1
        os.remove(file[0])
        err = 2
        wm.progress_update(100)
        wm.progress_end()
        
        fp = os.path.join(os.temp_path, blendfile)
        bpy.ops.wm.open_mainfile(filepath=fp)
        
    except:
        # self.report({'ERROR'}, "Cannot extract files errno {0}".format(str(err)))
        wm.progress_end()
        os.remove(file[0])
        print("return {'CANCELLED'} ")

execute(self, None)
```

**Comment by zeffii** [comment]
osx/linux users should set their .blend temp path according to their preferences.

**Comment by zeffii** [comment]
closing for later.

**Comment by jotero3d** [comment]
hi zeffil   error  >os.remove(file[0]) <       os.remove(dirPath + "/" + file)   better for me :)

**Comment by zeffii** [comment]
@jotero3d hi
please explain that again using the following syntax
<pre>
```diff
- isntead of this line
+ use this line
```
</pre>

**Comment by zeffii** [comment]
without the error message i don't really know much @jotero3d 
```diff
-   os.remove(file[0])
+  os.remove(to_path)
```

**Comment by jotero3d** [comment]
Sorry, my mistake, my provider had problems :(
all three write white go under windows 7 or 10
`os.remove(dirPath + "/" + file)`
`os.remove(file[0])`
`os.remove(to_path)`

------- but I can't always still with me!
[http://www.jotero.com/3d/voro_01.png](url)
[http://www.jotero.com/3d/voro_02.png](url)

for me, I have a solution but maybe there also one for Blender ;)
[https://www.sidefx.com/forum/topic/27610/](url)

Sorry again zeffii for the Sunday error :*)

**Comment by zeffii** [comment]
don't feel bad, that `.blend` doesn't load on my machine anymore either. It's related to the scipy / numpy mismatch. If you open up the windows (Toggle System Console) and you'll get better error messages.

**Comment by zeffii** [comment]
i'm on win10 and `os.remove(file[0])`  works ok, because i have a folder called `C:\tmp` in the root.

**Comment by jotero3d** [comment]
Thank you, I'm looking for a solution.
http://www.jotero.com/3d/voro_03.png

**Comment by zeffii** [comment]
get the 64bit windows version of anaconda, it comes with scipy, then adjust the `scipy_path` on that `voronoi.py` to match the path of scipy on your machine.
