### ISSUE TITLE
Easing Node is not behaving as expected

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1085]
I tried to make sense of this node called "Easing".

The idea is supposedly to make multiple objects in the scene (25 box) to move from position A to B. Each with offset, but I want the animation to have more quality to it, so I need to use Easing.

[Easing_Stuff_002_2017_01_04_05_49.zip](https://github.com/nortikin/sverchok/files/683982/Easing_Stuff_002_2017_01_04_05_49.zip)

![screen shot 2017-01-04 at 16 50 47](https://cloud.githubusercontent.com/assets/3952687/21632824/128ccf06-d29e-11e6-813b-06b442f431d8.png)

Maybe my failure is in mapping the value, easing is probably expecting value between 0 and 1, but the value I am plugging is big value and clamping it will not help either.

I will try with smaller number of box for now. Even just one.

**Comment by enzyme69** [comment]
Comparing it with AN "Animate" node.

![screen shot 2017-01-04 at 16 59 24](https://cloud.githubusercontent.com/assets/3952687/21632952/2e229510-d29f-11e6-9958-413e274dd63b.png)

Trying to make sense and recreate the node in Sverchok that kind of the same as Animate Float node in AN....

**Comment by enzyme69** [comment]
![screen shot 2017-01-04 at 17 06 32](https://cloud.githubusercontent.com/assets/3952687/21633077/2a214096-d2a0-11e6-9764-6868977203e8.png)
A tweak from above, but still not quite right....

![anim_ease_001](https://cloud.githubusercontent.com/assets/3952687/21633116/764e8384-d2a0-11e6-953c-96c46c8650ca.gif)

**Comment by nortikin** [comment]
deselect clamp

**Comment by nortikin** [comment]
yes, it extends from 1 somehow

**Comment by zeffii** [comment]
1. the input must be between 0 and 1
2. depending on the easing function, the output can exceed those limits ( overshoot is intended for some functions, it is part of the algorithm ). 
3. When using an easing function that extends the output beyond 0...1 you should adjust the output range too with the remap node . ( destination values should then also exceed the desired resting and starting points  ).

https://github.com/nortikin/sverchok/blob/master/utils/sv_easing_functions.py

I should probably set up a blend file to automatically draw all curves in a graph to show input vs output, and those functions that _do_ overshoot, give their multiplication value to help fix the later remaps.

**Comment by zeffii** [comment]
please read https://github.com/nortikin/sverchok/issues/695
