### ISSUE TITLE
Objects In code overhaul

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1087]
This node has worked well for a long time, until mid November 2016 between November 13th and 27th , code was introduced that makes it fail on windows machines (not a low memory issue).

This means I can't use this node for anything without being hyper cautious to avoid crashing scenarios ( https://github.com/nortikin/sverchok/issues/1047#issuecomment-267623020 ) .

This led me to make `objects_in_lite`, which does not suffer from the same problem - And that's making me consider rewriting the internals of objects_in. Retaining all user functionality. Maybe even storing meshes at iojson request at export time like objects_in_lite does. 

I don't know if a scene cache is needed for objects, it's not like we encourage users to use large objects in objects_in in the first place.

**Comment by ly29** [comment]
Something like this
```python
class ObjectsIn:

    object_names = bpy.props.CollectionProperty(type=bpy.types.PropertyGroup)


    def get_objects_from_scene(self):
        """
        Collect selected objects
        """
        self.object_names.clear()
        names = [obj.name for obj in bpy.data.objects if obj.selected]
        if self.sorting:
            names.sort()
        for name in names:
            item =  self.object_names.add()
            item.name = obj.name

    def select_objs(self):
        """select all objects referenced by node"""
        for item in self.object_names:
            bpy.data.objects[item.name].select = True
        return {'FINISHED'}
         
```

**Comment by zeffii** [comment]
the list of object names can be stored in many ways
  1. a node_dict
  2. a StringProperty with json stores/dumps get/set
    ```python
    names = StringProperty('{\'names\': []')

    def get_names():
        return json.dumps(self.names)['names']

    def add_names(names):
        name_list = json.dumps(self.names)['names'] 
        name_list.extend(names)  # must be an iterable
        self.names = json.stores({'names': name_list})
```
   3. CollectionProperty / PropertyGroup like used in [Exec Node](https://github.com/nortikin/sverchok/blob/master/nodes/script/multi_exec.py)

**Comment by zeffii** [comment]
but yeah: `  object_names = bpy.props.CollectionProperty(type=bpy.types.PropertyGroup) `
directly also takes my preference.

**Comment by ly29** [comment]
Note, the default ```ProperyGroup``` has a ```StringProp``` called ```name```.

**Comment by zeffii** [comment]
ooooh. that makes sense, and explains why my exec node needed to define a propertygroup because i used the `eval_line` String property.

**Comment by ly29** [comment]
The problem here is backwards compatibility and the operators are used in some places.

Both are solvable, but the first I don't really want to solve

**Comment by zeffii** [comment]
mk3 for sure, i'm not interested in add more code to this than strictly needed.

**Comment by zeffii** [comment]
little progress update .. ob3  ( i will call it this for convenience )  now has a lot less code.  But still mostly works for the base case.  Most UI code and related props remain unchanged, most of the rest comes from our discussions here and my previous attempt at modifying ob2 . 

Unfortunately the particular freeze still happens, but at least there's now less code to reason over.

**Comment by zeffii** [comment]
Sv3DPanel  not handled for `SvObjectsNodeMk3` yet. first thing i'll do next.

**Comment by ly29** [comment]
The call for updating a node tree from a node is.

```python
def process_node(self, context):
#line 112
self.process_node(None)
```

**Comment by zeffii** [comment]
cool! 

also i see `utils/sv_panels_tools.py`  will need a few changes.

**Comment by zeffii** [comment]
sv3d props panel operator for Get   doesn't work at the moment, will return later.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1092

**Comment by zeffii** [comment]
maybe draw the stored object names not as label, but using one of the templates for propertygroups / UIlist.. / template_list()

**Comment by zeffii** [comment]
going to add a mode for edit mode meshes to update while in animation/objin_live mode, then the recode reaches feature parity.

**Comment by ly29** [comment]
Would be cool if you mesh out also worked in obj mode. 
With some small changes you could create operators in Sverchok for editing meshes etc.

**Comment by ly29** [comment]
Slightly different mode but still, hmm. Far off topic

**Comment by zeffii** [comment]
![okgif](https://cloud.githubusercontent.com/assets/619340/21741367/c0a29ca6-d4d3-11e6-9581-92b11f20dc4a.gif)

**Comment by zeffii** [comment]
btw, bgl is removed now in 2.8 , so perfect opportunity to consider the replacement..

**Comment by ly29** [comment]
Perfect time for 0.6 branch with some general cleanup aiming for 2.8 then no?
New issue to outline. Dropping old nodes and overhauling etc.

**Comment by zeffii** [comment]
yep. This is ready to push now. it's reached feature parity.
