### ISSUE TITLE
Passing Random Values into Object ID ShapeKeys

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1089]
![screen shot 2017-01-05 at 11 25 26](https://cloud.githubusercontent.com/assets/3952687/21664304/b85532f2-d339-11e6-9cf1-24d7cb586ec5.png)

Does not quite work as expected. I must be missing something.

[sv_shapekeys_001_2017_01_05_00_26.zip](https://github.com/nortikin/sverchok/files/686165/sv_shapekeys_001_2017_01_05_00_26.zip)

**Comment by enzyme69** [comment]
![screen shot 2017-01-05 at 11 32 22](https://cloud.githubusercontent.com/assets/3952687/21664446/a5d6836e-d33a-11e6-8b0d-e9ac020af094.png)

Ok that thing actually does something.

Multi Filtering is a bit tricky.

**Comment by enzyme69** [comment]
![screen shot 2017-01-05 at 11 33 52](https://cloud.githubusercontent.com/assets/3952687/21664468/dac0c008-d33a-11e6-8e69-142ab502b5a1.png)

Interesting. @Kosvor2 Anything to add?

**Comment by enzyme69** [comment]
Can we filter source Shape Keys "owned" by an Object instead of directly modifying Shape Keys block modification? Or this is how Blender works?

**Comment by Kosvor2** [comment]
You can filter objects and then find their shape keys like this:

![shk1](https://cloud.githubusercontent.com/assets/22656834/21722172/8fa6eaea-d43c-11e6-9d93-9141f0f9f49b.png)

**Comment by enzyme69** [comment]
Thanks for example! nice trick with .0
https://gist.github.com/c560b402acca5852e0c6dcce7c0f1bd3
