### ISSUE TITLE
Edge Adaptive Multiple Input

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1090]
Continuation of this:
https://github.com/nortikin/sverchok/issues/695#issuecomment-270335408

I think I know what I am trying to do (sort of)

![screen shot 2017-01-05 at 19 16 44](https://cloud.githubusercontent.com/assets/3952687/21673223/dc19b4be-d37b-11e6-8e52-f44cc21a08d9.png)

A way to combine and randomize Edge Adaptive Donor, to turn it into a single line.

https://gist.github.com/1c2bbfbb023108b89a7a46af0cb22395

**Comment by enzyme69** [comment]
Although Edge Adaptive node does not really do squash and stretch... regardless the distance of edge slices.

![screen shot 2017-01-05 at 19 24 02](https://cloud.githubusercontent.com/assets/3952687/21673339/94708e16-d37c-11e6-865f-ca152ae6ccc3.png)

I am actually trying to visualize "animation" curve.

**Comment by enzyme69** [comment]
![screen shot 2017-01-05 at 19 26 47](https://cloud.githubusercontent.com/assets/3952687/21673419/ebe7b2aa-d37c-11e6-930b-f9f8d9611f7b.png)

That's interesting but what is reallly controlling "the amplitude" of this EASE function?

**Comment by ly29** [comment]
As the author I can certainly state that adaptive egdes could needs more work.
For this case the scanning happens inside of adaptive edges with intdiv which for this case is a bit strange...

**Comment by enzyme69** [comment]
![screen shot 2017-01-05 at 19 30 29](https://cloud.githubusercontent.com/assets/3952687/21673527/7c7bf38a-d37d-11e6-80aa-3464a3b96c42.png)
![screen shot 2017-01-05 at 19 29 55](https://cloud.githubusercontent.com/assets/3952687/21673528/7c7c1414-d37d-11e6-9518-73371617b759.png)

Thanks @ly29 

I don't know what I am trying to do, but kind of thinking of 2D animation curve, and then trying to combine animation curve.

Adaptive Edges seems can help with what I am trying to do.

**Comment by enzyme69** [comment]
The Edge Adaptive scale based on length but does not stretch or squash isnt
it, any way we can change the behaviour?

I like the node, powerful.

Is there a way to also rotate twist the edge while on it?

**Comment by zeffii** [comment]
> what is reallly controlling "the amplitude" of this EASE function

Amplitude is defined by the function, the functions don't take parameters, and aren't intended to be supremely configurable. You might use something like the Exec Node / Script nodes to write your own `x->y` functions.  The Ease functions in the node are the 30 most common. their source is [here](https://github.com/nortikin/sverchok/blob/master/utils/sv_easing_functions.py) to learn from and adapt to your own needs.

**Comment by ly29** [comment]
All of those things are issues with adaptive edges, today it would be called an alpha node, it needs more control and needs to be redone. Sadly not my best work.

**Comment by enzyme69** [comment]
@ly29 thanks Ly I will look forward to the update of the node. But I think it's still pretty powerful!

@zeffii very good point there, I appreciate the explanation. I think the squash and stretch requires a deformation of Vector.

**Comment by nortikin** [comment]
vectorized it today.

**Comment by enzyme69** [comment]
@nortikin any example?

**Comment by nortikin** [comment]
https://gist.github.com/nortikin/380019871206531dffa8c93beb7b7f4d
