### ISSUE TITLE
Strips detection / Edge Loop 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1094]
Any idea or interest let say selecting edge loop algorithm?

![screen shot 2017-01-07 at 12 13 20](https://cloud.githubusercontent.com/assets/3952687/21737954/ca47593c-d4d2-11e6-9ad4-9597fa12e8a0.png)

**Comment by zeffii** [comment]
if the code is licensed gpl3 we could use it, else it would need to be distributed separately from Sverchok (and never be part of Sverchok). If you have the code you could also use a scriptnode to test it.

else  not sure what to do with this, I think finding edge looks / face loops would be a neat feature - definitely not against adding it..  but without anything to look at (code) it's a mute point

**Comment by nortikin** [comment]
https://github.com/dmarx/Topological-Anomaly-Detection
also found this

![](https://raw.githubusercontent.com/dmarx/Topological-Anomaly-Detection/master/Iris_outlier_graph_small.png)
