### ISSUE TITLE
Vector Noise and Seed

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1095]
Random Num Gen and Random Vector has handy _seed_ input, sometimes I think Vector Noise needs that Seed value?

It makes me wonder if Vector Noise actually understand vectorization yet or not... 

From my understanding currently Vector Noise is like a function node, it takes Vector position at different place and will generate random value anyway, and moving the Vector point inputs will push the point through vector to generate noise as scalar or vector outputs.

**Comment by enzyme69** [comment]
Also looking into this old issue:
https://github.com/nortikin/sverchok/issues/949

I'll attempt to do similar thing, but in a different set of mind.

**Comment by zeffii** [comment]
have a look at the Vector Noise's code.

**Comment by enzyme69** [comment]
Thanks for reminder, I am gonna look now.

**Comment by zeffii** [comment]
There's a lot of potential in the noise module, I think the Vector Noise node barely scratches the surface. Excellent opportunity for someone who wants to learn bpy / writing nodes to get stuck in.

**Comment by enzyme69** [comment]
https://github.com/nortikin/sverchok/blob/d37532f5777292a12872e4e8115848d6371b85fc/nodes/vertex/noise.py

**Comment by zeffii** [comment]
anyway, there does appeart to be a seed property for the noise module

https://www.blender.org/api/blender_python_api_current/mathutils.noise.html

### mathutils.noise.seed_set(seed)

- Sets the random seed used for random_unit_vector, random_vector and random.
- Parameters:	seed (Int) – Seed used for the random generator. When seed is zero, the current time will be used instead.

not sure if that `random_vector` means `mathutils.noise.noise_vector`, if so the bpy docs are outdated

**Comment by zeffii** [comment]
a simple test snlite ..
```python
"""
in   seed        s  d=0 n=2
in   inputvecs   v  d=[[]] n=1
out  noisevecs   v
"""
out = [[]]

import mathutils
from mathutils import noise

PERLIN = noise.types.STDPERLIN
noise.seed_set(seed)
out[0] = [noise.noise_vector(v, noise_basis=PERLIN) for v in inputvecs]
```

**Comment by zeffii** [comment]
a simple snlite noise vector test confirms this.
```python
"""
in   seed        s  d=0 n=2
in   inputvecs   v  d=[] n=1
out  noisevecs   v
"""
noisevecs = [[]]

import mathutils
from mathutils import noise
from mathutils import Vector as V

PERLIN = noise.types.STDPERLIN
noise.seed_set(seed)
noisevecs[0] = [noise.noise_vector(V(p), PERLIN)[:] for p in inputvecs]
```

**Comment by enzyme69** [comment]
Wonder if reading AN wiggle noise would help.

**Comment by zeffii** [comment]
to answer you question of the Title, yeah,  `Vector Noise` noise could be bumped to mk2 and get a Seed param.

**Comment by enzyme69** [comment]
😩 yeah, sorry for the trouble with all my requests... currently, if I tried to make something, I will definitely use Script node. Making actual SV Node still intimidates me somewhat. 

@ly29 said a while ago that he is not programmer, but he did make some nodes..

**Comment by ly29** [comment]
While I agree that the vector noise module really could do with a make and an expanded scope I am not sure that seed is the relevant parameter to expose but rather an *offset* could be used based on the docs.

However based on reality the *seed* does matter. Hmm

Also no need to create a ```Vector()```, also not according to docs.

```python
>>> from mathutils import noise
>>> noise.seed_set(10)
>>> noise.noise_vector((.4,.4,.0))
Vector((0.1592249870300293, -0.03704875707626343, 0.12853741645812988))

>>> noise.seed_set(11)
>>> noise.noise_vector((.4,.4,.0))
Vector((0.06762981414794922, 0.017115235328674316, 0.27754223346710205))
```

I propose try to create useful a node(s) considering mostly how to expose the different noise types, it is rather rudimentary now and not so useful as a node.

**Comment by zeffii** [comment]
> Making actual SV Node still intimidates me somewhat.

_A bit of armchair psychology here.. so read it and ignore it: _

Most likely this is down to a fear of failing. When you avoid writing code by using nodes - if you fail then then you can say to yourself ' the reason i didn't succeed is because the nodes don't allow me to do x '. But if you failed because you couldn't figure out how to write a node, then you might see that as a personal failure. Once you get into the mindset of failing while coding is the best feeling ever, you'll make progress :)

**Comment by zeffii** [comment]
@ly29   the doc says : ` position (mathutils.Vector) `   for ` mathutils.noise.noise_vector ` but it if works on just a 3 tuple/list all the better..

**Comment by zeffii** [comment]
@ly29 i wonder which other functions we could avoid converting list/tuples to Vector :)

**Comment by ly29** [comment]
Many I think. It has changed recently.

**Comment by ly29** [comment]
Also we will be able to help, comment and nudge you in the right direction.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21749255/a454d596-d59b-11e6-80a4-e45718889f87.png)

https://github.com/nortikin/sverchok/tree/noise_vector_mk2

**Comment by zeffii** [comment]
i'm undecided (and too lazy) to figure out a nicer way to do the vectorization..

**Comment by zeffii** [comment]
I was thinking about a mix parameter, so the output could be 
- vector input is same as vector output if mix is zero
- fully noise vector output if mix is 1
- any value in between if mix is between 0...1
- or a projection vector linear interpolation if below 0 or above 1

**Comment by zeffii** [comment]
but first i'll have a think about how granular I want the vectorization to be..

**Comment by zeffii** [comment]
@ly29 Noise Vector is your node, are you OK with my MK2 version? would like to push

**Comment by ly29** [comment]
@zeffii 
I am okay with proposed changes of introducing a seed the code for selecting a seed looks a bit complicated though...

Also would be nice to clean up some of my old too short variable names once we at it.
```python
out.append([n_f(v, n_t) for v in obj])
#
out.append([noise_func(vertices, noise_type) for vertices in obj])
```

Would like the pull request to be clean to master with only changes in the node file.

**Comment by zeffii** [comment]
i have since kept the branch to the node file only..

**Comment by ly29** [comment]
Perfect

**Comment by zeffii** [comment]
yeah, vectorization is convoluted AF :)

**Comment by zeffii** [comment]
it probably doesn't make sense to have the option to set the Seed per element of the input, so I stopped at that granualirity.. but this is why I ask you to look and offer an improvement if there's something that could be done obviously simpler.

**Comment by ly29** [comment]
I would go for something like this I think.
```python
for seed, obj in *match_long_repeat([seeds[0], verts]):
```
But I might miss some detail.

**Comment by zeffii** [comment]
i'm happy to do that, just one seed per input list, come to think of it.. it's not a super helpful to have a different seed per vector, might as well be generating random verts.

**Comment by zeffii** [comment]
interesting thing happens if seed is 0 , noise_function seems to periodically switch seed internally in a random way, but anything above 0 is stable.

**Comment by ly29** [comment]
0 is considered unsetting the ```seed```. 

```python
            Random = []
            param = match_long_repeat([Coun, Seed, Scale])
            # set seed, protect against float input
            # seed = 0 is special value for blender which unsets the seed value
            # and starts to use system time making the random values unrepeatable.
            # So when seed = 0 we use a random value far from 0, generated used random.org
            for c, s, sc in zip(*param):
                int_seed = int(round(s))
                if int_seed:
                    seed_set(int_seed)
                else:
                    seed_set(140230)
```

**Comment by zeffii** [comment]
prelim doc (rst soon)

**Comment by zeffii** [comment]
yeah, I inferred that seed=0. I do want to keep that behaviour :)

**Comment by ly29** [comment]
I am skeptical since any change to the layout will produce a random result. Move a link and the view changes. 

Perhaps as an advanced option in side panel...

**Comment by ly29** [comment]
The problem being that 0 is such likely value of being feed to the node and would produce unexpected results.

**Comment by zeffii** [comment]
you make a good point..

**Comment by zeffii** [comment]
close to pushing, has docs now. https://github.com/nortikin/sverchok/blob/noise_vector_mk2/docs/nodes/vertex/noise_mk2.rst

**Comment by zeffii** [comment]
@enzyme69   noise mk2 is ready to be abused.

**Comment by zeffii** [comment]
(but you might need to force an update) i'm not going to bump sverchok version number for this.

**Comment by enzyme69** [comment]
I shall force update (uninstall and reinstall) to abuse this beauty
