### ISSUE TITLE
Learning Sverchok using Dan Shiffman's "Nature of Code"

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1096]
I propose we get the Sverchok community to implement [Dan Shiffman's _Nature of Code_ using Sverchok](http://natureofcode.com/book/) as much as possible, and ScriptNodes when standard nodes are't sufficient. I'll probably do a few myself, and we can accept any number of submissions per chapter, meaning per challenge there would be multiple examples of how to approach it. 

Good opportunity to see how Sverchok can be used for general graphics programming and nice to cross reference a creative standard like processing/p5js with what we've got.

**Comment by zeffii** [comment]
### Nature of recode

1. VECTORS
2. FORCES
3. OSCILLATION
4. PARTICLE SYSTEMS
5. PHYSICS LIBRARIES
6. AUTONOMOUS AGENTS
7. CELLULAR AUTOMATA
8. FRACTALS
9. THE EVOLUTION OF CODE
10. NEURAL NETWORKS

**Comment by ly29** [comment]
All these are good exercises, would be nice to make Sverchok handle some of the cases nicely. Especially particles, agents and fractals

**Comment by zeffii** [comment]
yeah, could push us to make a numpy based particle system .. so we rely less on Blender.

**Comment by enzyme69** [comment]
![screen shot 2017-01-08 at 22 23 02](https://cloud.githubusercontent.com/assets/3952687/21749335/132c12d6-d5f1-11e6-91d2-de5e93c408a2.png)

I'll make video about "Counting". It's Python thing. I use SN Lite. The script might be dodge, but yeah... a step at time.

**Comment by enzyme69** [comment]
```

"""   (tripple quote marks to demark the header)
in listnumbers  s  default=[[]] nested=1
out outnumbers s 
out total s
"""

#mystuff = []

blah = []

for i in range(5):
    blah.append(listnumbers.count(i))

    
outnumbers = [blah]
total = len(listnumbers)
```

**Comment by enzyme69** [comment]
Slight improvement.
![screen shot 2017-01-08 at 22 27 39](https://cloud.githubusercontent.com/assets/3952687/21749373/b6b6d742-d5f1-11e6-968a-60a5594317ec.png)

**Comment by zeffii** [comment]
@enzyme69 let me suggest that you start your own `sverchok_learning` repository on github (repos don't have to be purely about code), and when you have a chapter done (or parts of a chapter), then add the link to it here by editing my second post..

as a tip, i would start out using as few nodes as possible.
1.  `range_int -> stethoscope`   (one list)
2.  `range_int -> range_int -> stethoscope`  (multiple lists)

**Comment by zeffii** [comment]
Or we might do this via the sverchok wiki, I don't want this to happen in the issue-tracker really.

**Comment by zeffii** [comment]
it's a wiki page now. https://github.com/nortikin/sverchok/wiki/Nature-Of-Node
