### ISSUE TITLE
Vector Lerp

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1098]
note to self

The Vector Evaluate node can be used for this, the UI has a `min=0` and `max=1`, 

![v111gif](https://cloud.githubusercontent.com/assets/619340/21751404/d14dca64-d5c6-11e6-890e-8f499d0cec93.gif)

but if you go beyond those values by passing a float node with the values `-1` or `1.6` the Vectors will be Linear Interpolated beyond the `0 .. 1`  range.

![v222gif](https://cloud.githubusercontent.com/assets/619340/21751385/95a2d838-d5c6-11e6-84ba-c5f14c949f8b.gif)

**Comment by zeffii** [comment]
hmm, i need Vector Evaluate to be vectorized..

**Comment by zeffii** [comment]
also Vector Evaluate has a small (bug significant bug)  `points` is defined twice.

Am going to make a `Vector Lerp` , and depreciate Vector Evaluate (unless for some reason that behaviour was intended)

**Comment by zeffii** [comment]
Am going to make a `Vector Lerp` , and depreciate Vector Evaluate (unless for some reason it's weird behaviour was intended)

**Comment by zeffii** [comment]
![umpalumpa](https://cloud.githubusercontent.com/assets/619340/22398119/4015cde2-e581-11e6-81d3-66510b7e74bd.gif)
https://github.com/nortikin/sverchok/pull/1186

**Comment by nortikin** [comment]
love that word umpalumpa, it is sounds like african's word

**Comment by enzyme69** [comment]
Call the node Vector Lerp Oompa Loompa.

**Comment by enzyme69** [comment]
Interface node wise, would it be better
Vector A
Vector B
Factor

or
Factor
Vector A
Vector B

**Comment by zeffii** [comment]
current ui copies the Vector Evaluate node F,V,V, but perhaps V,V,F could be viewed as more consistent with  the rest of the nodes. I certainly accept that reasoning.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22403415/97f342a2-e616-11e6-8494-668a28c3cfb9.png)

**Comment by zeffii** [comment]
0.5  
![image](https://cloud.githubusercontent.com/assets/619340/22403445/b6ffef46-e617-11e6-8d84-f47295be5230.png)

-0.5  
![image](https://cloud.githubusercontent.com/assets/619340/22403447/e18ff24c-e617-11e6-82cd-abd28c22a517.png)

1.5  
![image](https://cloud.githubusercontent.com/assets/619340/22403454/fc9b6030-e617-11e6-9f18-822fb0ab5a50.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22403637/2f95747a-e61e-11e6-8913-825cb4e609b9.png)
https://gist.github.com/867b519aa1085b424c48018a03bdadee

**Comment by zeffii** [comment]
works well. committed

**Comment by Durman** [comment]
One more example:
https://gist.github.com/831a33308cc9bcf99940ac766dcaca60
![2018-01-20_19-52-20](https://user-images.githubusercontent.com/28003269/35185299-cbad191a-fe1b-11e7-9b19-4083c8449f07.png)
![interpolation mesh](https://user-images.githubusercontent.com/28003269/35185305-da2c033e-fe1b-11e7-9900-db913bc45243.gif)
