### ISSUE TITLE
SN Lite in Sverchok vs AN Script Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1099]
Not to start a long thread about nothing.

I am currently learning SN Lite designed by @zeffii , it feels just slightly harder just in term of working out the IN and OUT. Of course, much more user friendly compared to original Script Node 1.

AN has advantage of this adding INPUT and OUTPUT in its own way.

Sverchok is definitely for more advance users but scripter will undersand and find coding the INPUT and OUTPUT will be smoother the Sverhcok way. In fact in the long run, scripted INPUT and OUTPUT is definitely a benefit.

What is the advance script feature of Sverchok that is not very obvious for beginners. I know @zeffii mentioned about the Vectorization in SN Lite at some point. I think it can be very value-able to mention this in my live noding videos.

Svechok can do this array over array thing, I was wondering if SN Lite has that kind of unwrapping feature or something that users should know?

I will re-read his thread on SN Lite and check example again.
https://github.com/nortikin/sverchok/issues/942

To be honest, I am a bit better with Sverchok matrioshka list in list, but to do the same in Python, sometimes still a gotcha.....

**Comment by enzyme69** [comment]
I keep forgetting the term "NESTINESS". I should have mentioned in my Live Noding. Sverchok has this Nestiness, packing unpacking, and multi-ple vectorization that AN does not have yet.

**Comment by zeffii** [comment]
>  it feels just slightly harder just in term of working out the IN and OUT.

The script nodes aren't for beginners - they are not my target audience. SN1 and SN1Lite are meant for people who are comfortable with Python, but don't want to write any of the boilerplate involved in making full SvNodes. For that group of people I think the current documentation of SN and SNLite and all the examples have proved sufficient (Ko, Ly, Nortikin, Elfnor and several at BA have written wonderful scripts for the node). 

> AN has advantage of this adding INPUT and OUTPUT in its own way.

Some front-end things can't be made simpler, without making the back end more complex ( I don't feel like doing that..) I can't compare our scriptnodes with AN's scriptnode, I don't know if AN's data model contains nested lists - if it does then the things that make Scriptnode complicated will be similar in both AN and SV. 

Our nestedness is what allows us pass multiple sets of data in one socket. But the current implementation of that using nested-lists does add an extra level of complexity to the coder/scripter,

**Comment by zeffii** [comment]
All nesting / nestedness is is putting lists inside a list.

```python
major_list = [minor_list1, minor_list2, minor_list3]
```

or to be more explicit
```python

minor_list1 = [2, 3, 4, 5, 6]
minor_list2 = [5, 4, 2, 6, 6]
minor_list3 = [3, 4, 2, 3, 6]
major_list = [minor_list1, minor_list2, minor_list3]

>>> print(major_list)
[ 
    [2, 3, 4, 5, 6], 
    [5, 4, 2, 6, 6], 
    [3, 4, 2, 3, 6]
]
```
This is beginner's Python, only slightly more complicated is if those lists contain vectors (lists/tuples of length 3 in sverchok terms)
```python
minor_list1 = [(2,2,4), (3,1,2), (4,4,2), (5,5,2), (6,6,4)]
minor_list2 = [(9,8,2), (2,5,6), (2,5,2), (2,3,6), (4,6,1)]
minor_list3 = [(2,2,2), (5,5,2), (4,4,2), (2,5,2), (6,6,1)]
major_list = [minor_list1, minor_list2, minor_list3]

>>> print(major_list)
[ 
    [(2,2,4), (3,1,2), (4,4,2), (5,5,2), (6,6,4)],   # lists of tuples ( but also lists can be used for vectors..)
    [(9,8,2), (2,5,6), (2,5,2), (2,3,6), (4,6,1)],
    [(2,2,2), (5,5,2), (4,4,2), (2,5,2), (6,6,1)]
]
```
This is the same as a multidimensional array. a 2-d array with vectors as elements.
If someone doesn't grasp the list / nested list, then they should be studying Python more in depth first else they will continuously have a hard time.

**Comment by zeffii** [comment]
I don't know if my answer is helpful here btw. If there are questions about the SNLite documentation you need to take a screenshot of the part you don't understand and underline it or add question marks to the side. I'm happy to correct / improve the docs..

**Comment by zeffii** [comment]
sorry, I cant really detect a question here @enzyme69
