### ISSUE TITLE
Simple replace_socket

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1101]
```python
def replace_socket(socket, new_type, new_name=None, new_pos=None):
    '''
    Replace a socket with a socket of new_type and keep links
    '''
    
    socket_name = new_name or socket.name
    socket_pos = new_pos or socket.index
    ng = socket.id_data

    ng.freeze()

    if socket.is_output:
        outputs = socket.node.outputs
        to_sockets = [l.to_socket for l in socket.links]
    
        outputs.remove(socket)
        new_socket = outputs.new(new_type, socket_name)
        outputs.move(len(outputs)-1, socket_pos)

        for to_socket in to_sockets:
            ng.links.new(new_socket, to_socket)

    else:
        inputs = socket.node.inputs
        from_socket = socket.links[0].from_socket if socket.is_linked else None
    
        inputs.remove(socket)
        new_socket = inputs.new(new_type, socket_name)
        inputs.move(len(inputs)-1, socket_pos)

        if from_socket:
            ng.links.new(from_socket, new_socket)

    ng.unfreeze()

    return new_socket

```

i propose this.. not tested much yet

**Comment by ly29** [comment]
If testing proves it works I all for simplification, but there is a lot subtle things with the sockets which I rather not spend time on.

**Comment by zeffii** [comment]
it's only 2 changes really, pushing the  `socket_pos` (formerly node_pos ) to the top because it is identical for inputs and outputs, and now we can use `socket.index` anyway.

**Comment by ly29** [comment]
Yeah, it looks way cleaner, go for it.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1103 still testing

**Comment by ly29** [comment]
There probably are a lot things to be made simpler due to better functions and style of code. Cleaning up data structure made it somewhat more accessible which is a very good thing.

**Comment by zeffii** [comment]
i won't push this until i'm certain it's solid.

**Comment by zeffii** [comment]
![setget](https://cloud.githubusercontent.com/assets/619340/21779067/46a6c326-d6a6-11e6-87ea-5c3e43f64908.gif)

**Comment by zeffii** [comment]
users:  x, confirm works

- [x]  nodes/vertex/noise_mk2.py 
- [x]  nodes/generator/script1_lite.py 
- [x]  nodes/object_nodes/getsetprop.py 
- [ ] nodes/scene/monad.py 
- [ ] utils/monad.py 
- [ ] nodes/scene/group.py 
- [ ] core/monad.py

**Comment by zeffii** [comment]
looks quite OK. 

https://github.com/nortikin/sverchok/pull/1103/files

though now i've found   Vector Math node needs some loving
` Vector Math two inputs, both vector,  failed `

**Comment by zeffii** [comment]
or monad needs to be a little less eager to update, while rotating socket positions..
[saboro_2017_01_09_19_31.zip](https://github.com/nortikin/sverchok/files/694452/saboro_2017_01_09_19_31.zip)

if you cycle the inputs of the monad, eventually the Vector node will complain temporarily.. maybe a freeze is in order at some point in the index change..

**Comment by zeffii** [comment]
But I'm certain this is more a problem with monad than with my silly replacement of replace_socket.

**Comment by ly29** [comment]
Sounds very likely

**Comment by zeffii** [comment]
https://gist.github.com/anonymous/ab1e8861380a14fd0fabbe3f74c8812b  confirmed, has nothing to do with `replace_socket`'s replacement , happens in master too.

am confident enough to push this, it's a direct mapping.

**Comment by zeffii** [comment]
I'll push this after @ly29 pushes the update handler..
