### ISSUE TITLE
Change from update to scene handler

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1102]
As noted in #1047 many crashes could because of bad design decision in Sverchok to use the nodegroup level update function for execution on editor changes.

Proposed fix, on changes trigger set a flag that changes has occurred and execute from *scene handler*.

Rough sketch below.

```python
def sv_main_handler(scene):
    for ng in sverchok_nodes_trees(): # some function that yields sv node trees
        if ng.changed:
            ng.process()
```
And update in the ```NodeTree``` changes to

```python
    changed = BoolProperty(default=False)

    def update(self):
          self.changed = True

   def process(self):
         if self.changed:
            self.build_update_list()
            self.changed = False

        if self.sv_process:
            process_tree(self)

```

**Comment by ly29** [comment]
We should also make review to do as little as possible in ```update``` functions in nodes.

**Comment by ly29** [comment]
ETA tomorrow

**Comment by zeffii** [comment]
when the sliders of a node are adjusted, do you call the node's own update function or the update function of the node tree ?

**Comment by ly29** [comment]
The same for them, we just have to change the effect of ```updateNode```

**Comment by ly29** [comment]
But they aren't updated in the same kind of context, I don't know what effects are allowed via the ```update=``` function of property but it shouldn't have the same sorts of constraints I think.

**Comment by zeffii** [comment]
and this scene update handler, is the right way to go? doesn't it trigger ridiculously often?

**Comment by ly29** [comment]
Yeah but we would only execute when the node tree has been edited

**Comment by ly29** [comment]
So now testing is in order. Surprisingly small changes needed means that some abstraction is done correctly at least.

Scenarios that might need testing:
- [ ] Load old file
- [ ] Load json
- [ ] Edit
- [ ] Animating something
- [ ] Test if resolves crash for object in mk2 @zeffii

**Comment by ly29** [comment]
If this works out as expected we can tell the developers they don't need to make a special case for us.

**Comment by zeffii** [comment]
I think this fixed obj_in freeze!!
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by zeffii** [comment]
let me do a final test by removing the node.freeze from obj_in_mk3's update function...

**Comment by ly29** [comment]
Good! If we had problems with data blocks there we would probably have in many other places potentially as well for other functions writing to ```bpy.data```

**Comment by ly29** [comment]
Actually now we should be able to remove all the ```ng.freeze``` code I think.

**Comment by zeffii** [comment]
I am not able to freeze it doing the same things as before, so I'm happy to get this commited!

**Comment by zeffii** [comment]
>  Open question, `scene_update_pre` or `scene_update_post` ?   

whatever we're using now seems to work.

**Comment by ly29** [comment]
Pushed, keeping open for bugs and strange behaviours for now.

**Comment by ly29** [comment]
With some more testing we can tell the developers that if they want they can remove that exception for us.

**Comment by zeffii** [comment]
maybe i was over confident, but I already added a message to the blender.org commit  saying as much.

**Comment by ly29** [comment]
I feel confident that should to the trick basically. Some nodes might be doing more than adding sockets and similar via ```update(self)``` should stop. I don't think many (any?) nodes do but I don't have the overview I once had.

**Comment by ly29** [comment]
Also feels good not to be responsible for the need for any comments associated like this

> XXX Yuck!!!! nodetree update can do pretty much any thing when talking about py nodes,

**Comment by zeffii** [comment]
agreed, that made me cringe too.  but hey, with so few working examples of a pynode system you did what was most obvious at the time. Now sverchok is a bit of a behemoth and gradually starting to slim down .

btw. we need to redo scalar and vector math nodes :)

**Comment by ly29** [comment]
@zeffii 
Yeah, at the time I did that (2014) we used the ```node.update(self)``` to update everything, then we switched to ```process``` but kept the node tree level ```update``` for executing the node tree. I thought about a handler and Lukas Tonne mentioned to me that he preferred that method but didn't state reasons so I kept in the back of my head but didn't deal with it...

**Comment by ly29** [comment]
I wonder if this will resolve the odd crashes @enzyme69 used to have...

**Comment by ly29** [comment]
Nobody seems to have been upset by this. Close for now but keep an eye open for unexpected or changed behaviour
