### ISSUE TITLE
Vector Math MK2

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1105]
Whenever I look at this node's source now I'm puzzled as to why I needed to approach it so complicated, it needs to be brought into 2017.  The `recurse_fx` and `recurse_fxy` are fine, but pretty much all the other tat leading up to the process function that's bloaty and my fault.

additionally, 
- it would be neat to have a vector property appear in the node when no socket is connected
- same for scalar input

**Comment by ly29** [comment]
Much agreed.

**Comment by zeffii** [comment]
think i'll stick to inputs A. B and output Out .

**Comment by ly29** [comment]
I like U and V for vectors but not that important

**Comment by zeffii** [comment]
when the implementation works nicely using just A,B and Out , i'm happy to expand the socket names back to `U V S` and `W OUT`. I also like UV for vectors.

**Comment by ly29** [comment]
Sounds like a sane approach

**Comment by zeffii** [comment]
this anaconda shed a lot of skin @ly29 . https://github.com/nortikin/sverchok/blob/vmathmk2/nodes/vertex/math_mk2.py

**Comment by ly29** [comment]
Comments
 - If we drop noise we should drop cell noise at the same time
- Drop useless try/except, see below
- Maybe move the recurse function outside of the node so they skip the useless/unrelated ```self``` argument
- Otherwise good, maybe ```leve``` -> ```level``` saving the on char three times seems short sighted

```python
        result = [[]]
        try:
            if num_inputs == 1:
                result = self.recurse_fx(input_one, func, leve - 1)
            elif num_inputs == 2:
                result = self.recurse_fxy(input_one, input_two, func, leve - 1)
        except:
            pass
```
Into
```python
        if num_inputs == 1:
            result = self.recurse_fx(input_one, func, leve - 1)
        else: #if num_inputs == 2:
            result = self.recurse_fxy(input_one, input_two, func, leve - 1)
```

**Comment by zeffii** [comment]
now just the default values for sockets / prop_name for when stff isn't connected

**Comment by zeffii** [comment]
`level` agreed.

**Comment by zeffii** [comment]
ditching cell noise as we speak

**Comment by zeffii** [comment]
cell noise will either be part of noisemk2 or its own node..  i can safely say i've never used it, but that doesn't mean other haven't.

**Comment by ly29** [comment]
it is in noise already.

**Comment by zeffii** [comment]
cell noise? i didn't realize..

**Comment by ly29** [comment]
I might be wrong, can't check right now

**Comment by ly29** [comment]
It is so much simpler and shorter now already

**Comment by zeffii** [comment]
tiny bit of complexity added back to support ui sliders `prop_name`  and `use_prop` for v and s sockets.

worth testing the branch now :)

**Comment by ly29** [comment]
Will be able to test tomorrow, but it looks good. I don't for see any real problems.

**Comment by zeffii** [comment]
iojson may need coercion, untested.

**Comment by ly29** [comment]
Looks fine, I think it should work with iojson.

Also we can remove the ```import noise```

**Comment by zeffii** [comment]
```python
    "Vector Math MK2": {
      "bl_idname": "SvVectorMathNodeMK2",
      "color": [
        0.6079999804496765,
        0.6079999804496765,
        0.6079999804496765
      ],
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -78.08036804199219,
        -142.96578979492188
      ],
      "params": {
        "current_op": "ADD"
      },
      "width": 140.0
    },
```

iojson will not pickup vector property / slider -- it might have the same problem for matrix_in..  I recall vaguely that this part of iojson is not great. easy to fix now..

**Comment by zeffii** [comment]
fixing the iojson end of this is probably better for a different branch, as it will involve several nodes..
https://github.com/nortikin/sverchok/search?p=2&q=.use_prop&utf8=%E2%9C%93

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1107

**Comment by ly29** [comment]
Testing...
When I switch mode the socket values are reset, less than ideal

**Comment by zeffii** [comment]
I think using `.prop_name = some_name` pointing to a local FloatVectorProperty() solves that problem, instead of using `.use_prop = True`.

**Comment by ly29** [comment]
Yeah also solves the IO JSON problem for now and makes it possible to push directly.

**Comment by zeffii** [comment]
yep, I'll be back shortly to do that.

**Comment by zeffii** [comment]
this is pushed now. enjoy.
