### ISSUE TITLE
iojson to handle use_prop while not socket.is_linked

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1107]
[12 (or thereabouts)](https://github.com/nortikin/sverchok/search?p=2&q=.use_prop&utf8=%E2%9C%93)  current nodes use this UI feature to display a vector input area when a socket isn't connected. IOjson has not been updated to provide support for that. While i'm doing a little sprint this week anyway I seek to include this in the import/export pass.

some note to self

```python
additional_props = {}
for idx, socket in enumerate(self.inputs):
    if socket.use_prop and not socket.is_linked:
        additional_props[idx] = socket.sv_get()[:]  # or  socket.prop
```

bl_idnames in question

- [ ] 'MatrixGenNode'  nodes/matrix/matrix_in.py
- [ ] 'SvBVHRaycastNode'  nodes/analyzer/bvh_raycast.py 
- [ ] 'SvRayCastNode'  old_nodes/scene_raycast.py 
- [ ] 'SvRayCastObjectNode'  old_nodes/object_raycast.py 
- [ ] 'SvSCNRayCastNodeMK2'  nodes/object_nodes/scene_raycast2.py 
- [ ] 'SvOBJRayCastNodeMK2'  nodes/object_nodes/object_raycast2.py 
- [ ] 'SvBVHnearNode'  nodes/analyzer/bvh_nearest.py 
- [ ] 'SvPointOnMeshNode'  old_nodes/closest_point_on_mesh.py 
- [ ] 'SvPointOnMeshNodeMK2'  nodes/object_nodes/closest_point_on_mesh2.py 
- [ ] 'SvInterpolationStripesNode'  nodes/vertex/interpolation_stripes.py 
- [ ] 'SvPipeNode'  nodes/modifier_make/pipe_tubes.py 
- [ ] 'SvGetPropNode' / 'SvSetPropNode'  nodes/object_nodes/getsetprop.py

**Comment by ly29** [comment]
This is a problem and I think it will get worse. We should make a standard interface for getting (or not) values from sockets that aren't linked.

**Comment by zeffii** [comment]
The SvLathe node uses `FloatVectorProperty(size=3)` and `prop_name`   instead of `.use_prop`

**Comment by ly29** [comment]
Yeah, but more things will start using properties in sockets so there needs to be a simple standard way for that to work

**Comment by zeffii** [comment]
I think most of these nodes listed here could probably be parsed with little effort, but they might benefit from using the node to store the properties like svlathe.

**Comment by ly29** [comment]
That is the short term solution, the longer term solution is to support properties in sockets, for that to happen in sane way there needs to be standardised interface.

**Comment by zeffii** [comment]
Then each such socket need a descriptor, that tells the parser what to store and where to restore it. I'm thinking (maybe not deep thought) a dict per socket

```
{
'inputs': {0: { stuffff } , 1: { stuffff } , 3: { stuffff }   },
'outputs': {0: { stuffff } , 2: { stuffff }   }
}
```

**Comment by zeffii** [comment]
Then each such socket needs a descriptor, that tells the parser what to store and where to restore it. I'm thinking (maybe not deep thought) a dict per socket and a dict per node

```
{
'inputs': {0: { descriptor } , 1: { descriptor } , 3: { descriptor }   },
'outputs': {0: { descriptor } , 2: { descriptor }   }
}
```

**Comment by zeffii** [comment]
@ly29  don't know if you've seen that yet but : https://github.com/BlendingJake/NodeIO

is an interesting approach to standardised io with json for all trees. It's not fully working for sverchok ( try a scriptnode mk 1 ) . Not quite prepared to halt iojson development yet, but ditching that part of sverchok would be really great :)

**Comment by ly29** [comment]
@zeffii 
I will take a look but if we are somewhat constrained going forward something much smaller than that could work.
It has a lot of node specific code going on also for us.

**Comment by ly29** [comment]
He evens supports my generic note node. 😄

**Comment by zeffii** [comment]
nothing to add to this for now. if I get really bored i'll fix something up.
