### ISSUE TITLE
Vertex Color New node did not assign multiple vector list of colors

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1108]
[random_color_variation_vertex_001_2017_01_10_23_19.zip](https://github.com/nortikin/sverchok/files/697634/random_color_variation_vertex_001_2017_01_10_23_19.zip)

![screen shot 2017-01-11 at 10 20 54](https://cloud.githubusercontent.com/assets/3952687/21828966/aa237a4c-d7e7-11e6-8631-d730dffaa964.png)

I am trying to colorize multiple objects with different vertex color using Vertex Color New. I can random seed the Vector Noise MK2. The values seem correct, but when plugged into Vertex Color New, it is using the same value for all.

**Comment by ly29** [comment]
I willl take a look at this tomorrow

**Comment by enzyme69** [comment]
thanks Ly! I should check the code before after

**Comment by zeffii** [comment]
@enzyme69 - yes, read the code. It confirms what you just said.

https://github.com/nortikin/sverchok/blob/master/nodes/object_nodes/vertex_colors_mk2.py#L90-L93

**Comment by ly29** [comment]
Well it uses object socket and I didn't change it. will get on it...

**Comment by ly29** [comment]
Fixed.
![skarmavbild 2017-01-11 kl 09 13 52](https://cloud.githubusercontent.com/assets/6241382/21840539/56a16ce8-d7de-11e6-9ac5-d53005c8ce25.png)
