### ISSUE TITLE
JSON Github Export to Gist failed to work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1109]
I updated to latest version of Sverchok 0.5.9.0 and Export to Gist is no longer working :(

Error message:
https://gist.github.com/enzyme69/bdd4b886c9e7566c4369184f6d497db6

**Comment by enzyme69** [comment]
Actually it failed to work when I have Renderman Nodes or Cycles node ? Just now it works.

**Comment by enzyme69** [comment]
False alarm, I will close this. Probably just glitch.

**Comment by zeffii** [comment]
With issues related to iojson please include a .blend with the report. This makes it easier to reproduce the problem, if _indeed_, if it is a problem.

Be advised that object_in (mk1,mk2,mk3) won't store Objects in the json. If your layout uses Scene Objects, then best avoid iojson - share Blends with fellow users in that case.

The only node that does support referencing and storing scene objects is the (beta) `Object In Lite`, it only storers verts/edges/faces  for one object at a time. Nothing else.

**Comment by enzyme69** [comment]
​Ok got it, if getting same issue, I'll supply the Blend.
