### ISSUE TITLE
STUDY: Trying to make this box with layered hole

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1110]
![file 11-1-17 11 23 25 am](https://cloud.githubusercontent.com/assets/3952687/21830404/8f640de4-d7f0-11e6-9753-b54da77f49f7.jpeg)

source: http://www.jenstark.com/

I saw this art from Twitter. I feel challenged to recreate that in Sverchok, so this is going be that kind of thread.

**Comment by enzyme69** [comment]
![screen shot 2017-01-11 at 11 25 33](https://cloud.githubusercontent.com/assets/3952687/21830421/b14c89ea-d7f0-11e6-9c5b-6baa747934e0.png)

That curve that looks like reaction diffusion is probably a tricky one to generate, however, I will start with the above. 

Resampling Plane square that will be used to loft into random circle shape.

![screen shot 2017-01-11 at 11 27 35](https://cloud.githubusercontent.com/assets/3952687/21830465/f8d4db64-d7f0-11e6-949a-bb4e04e1179f.png)

**Comment by enzyme69** [comment]
Suddenly, I have idea that maybe Array slice inverted Boolean can do the job... hmmm..  but yeah that's another hack idea.

**Comment by enzyme69** [comment]
![screen shot 2017-01-11 at 11 30 43](https://cloud.githubusercontent.com/assets/3952687/21830533/6a0e0b20-d7f1-11e6-9d8c-5b030e931bd2.png)

**Comment by enzyme69** [comment]
![screen shot 2017-01-11 at 11 36 30](https://cloud.githubusercontent.com/assets/3952687/21830641/3a02690c-d7f2-11e6-8471-afb5f8479f35.png)

Yeah above is interesting hack, but wanted to do this more parametric way using Sverchok... 

Thinking....

**Comment by enzyme69** [comment]
![screen shot 2017-01-11 at 11 47 20](https://cloud.githubusercontent.com/assets/3952687/21830839/bb27909c-d7f3-11e6-95e6-3d10a24163a4.png)

https://gist.github.com/e3c346c5018da6cbf518cdf4e17c8ba7

**Comment by enzyme69** [comment]
I see doing it this way, sorting the circular index will be tricky...

![screen shot 2017-01-11 at 11 53 03](https://cloud.githubusercontent.com/assets/3952687/21830987/aab74256-d7f4-11e6-91be-7c2b47346735.png)

Actually... better to do this using thinking outside the box...

**Comment by ly29** [comment]
Well  in this case I would think inside of the box and start with that part.

**Comment by zeffii** [comment]
maybe even get more eye/brain looking at this by asking how others would do it on sverchok's Google+, keeping all these 'how to/how do I' threads confined to the issue-tracker means you won't reach much of an audience.

**Comment by ly29** [comment]
![box](https://cloud.githubusercontent.com/assets/6241382/21846416/5a914bd4-d7f7-11e6-87aa-384d928acced.png)

Not happy with this result really but it shows. The outside of the box is a boolean outside of Sverchok, the top pattern could be made fun. Coloring of box is using vertex color inside of Sverchok.

![skarmavbild 2017-01-11 kl 12 13 46](https://cloud.githubusercontent.com/assets/6241382/21846443/76c33754-d7f7-11e6-96a8-0bc9c3730f98.png)

Not sharing right now because some ugly...

**Comment by ly29** [comment]
![box2](https://cloud.githubusercontent.com/assets/6241382/21851796/f3b846dc-d810-11e6-9209-dfd0d5149253.png)

**Comment by enzyme69** [comment]
Aahh... @ly29 you are genius need your brain, can you make Live Noding videos?

Still WIP:
![screen shot 2017-01-12 at 12 08 21](https://cloud.githubusercontent.com/assets/3952687/21873035/f17bf7f6-d8bf-11e6-885f-5c4f99e8467a.png)
https://gist.github.com/5e9e2f271137ed0e2fb3e0792d64163d

@Kosvor2 Ray node is used and his shrinkwrap trick used here. The Object ID does not have Matrix Apply but that's oke for now.

**Comment by enzyme69** [comment]
I think the harder part is to make it works with Vectorization stuff. I am stuck here.

https://gist.github.com/08ab05f045fbb86f4ef2e6812457b804

But if I just duplicate that creation above, and bake each frame with different Vector Noise MK2 (I like this node so much I can marry it 👍 ) and randoize the seed, it's a solution/

**Comment by enzyme69** [comment]
![sv_noise_mk2_002](https://cloud.githubusercontent.com/assets/3952687/21873226/569f8340-d8c1-11e6-848c-13a090df80b6.gif)

**Comment by enzyme69** [comment]
@ly29 I remember you said at some point that you don't know programming, but you study architecture. I remember Liero said the same thing.

**Comment by enzyme69** [comment]
Studying @ly29 example. Ideally, there should be "Lofting" node or some sort.

**Comment by enzyme69** [comment]
Reference:
https://github.com/nortikin/sverchok/issues/919

**Comment by enzyme69** [comment]
![screen shot 2017-01-12 at 19 53 54](https://cloud.githubusercontent.com/assets/3952687/21882969/f783bb5c-d900-11e6-9762-694075e20da9.png)

I think it's pretty good, case closed! Thanks~
