### ISSUE TITLE
The infinite complexity generator

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1112]
Or things I learned from monad / vectorize and SvRedux attempts...

There are now 192 nodes, getting them all with the different styles to work well in a coherent form is a monumental task.

So how should things work? If every node could be reduced to a function there would be three main signatures.

```python

# generator 
# Something that creates complexity from number to list.
# list(range(3)) -> [0, 1 , 2]
def circle(vertices: Int = 24, radius: Float = 1.0) -> Vertices, Edges, Faces:
      # do stuff

# map, operator
# Something that keeps the same level of complexity
# 1 + 2 -> 3
def add(x: Number = 0.0, y: Number = 0.0) -> Number:
      # do stuff

# reduce
# something that reduces the level of complexity
# sum(range(10)) -> 45
def uv_connect(*vert: [Vertices]) -> Vertices, EdgePolyData:
      # create connections

```

So fine, how would this actually work? 
Right now nodes are called once for each execution of each layout, the output from each node is stored in a socket data cache.

Each node *should* work as function not caring about context doing part of the work by itself according to its signature. So if we set the data for example for a circle node for each part of the list instead of. Something like below
![skarmavbild 2017-01-11 kl 16 11 10](https://cloud.githubusercontent.com/assets/6241382/21853745/9e02d394-d818-11e6-96f3-c7ba9d90c1a7.png)
https://github.com/nortikin/sverchok/blob/master/core/monad.py#L409-L439

The vectorise options still have the problem of losing the *structure* of the data.

So compare the following.
```python
def int_range(start: Int = 0 , stop: Int = 10 , step: Int = 1) -> [Int]:
    return list(range(start, stop, step))      

int_range(10, 20, 1) => [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

def compile_node(node):
     """ somewhat simplified version but still working"""
    def f(*args):
        for idx, arg in enumerate(args):
            socket = node.inputs[idx]
            if socket.is_linked:
                socket.other.sv_set([[arg]])
            else:
                setattr(node, socket.prop_name, arg) 
        node.process()
        data = []
        for socket in node.outputs:
            if socket.is_linked:
                data.append(socket.other.sv_get()[0])
            else:
                data.append(None)
        return tuple(data)
    return f

>>> node = D.node_groups['NodeTree'].nodes['Range Int']
>>> f = compile_node(node)
>>> f(0,10,10)
([0, 10, 20, 30, 40, 50, 60, 70, 80, 90],)

```
Now we have turned any node into a function using the current Sverchok system.

```python
args = match_long_repeat([[2, 3], list(range(10, 20)), [10]])

>>> list(starmap(f, zip(*args)))
[([2, 12, 22, 32, 42, 52, 62, 72, 82, 92],), ([3, 14, 25, 36, 47, 58, 69, 80, 91, 102],), ([3, 15, 27, 39, 51, 63, 75, 87, 99, 111],), ([3, 16, 29, 42, 55, 68, 81, 94, 107, 120],), ([3, 17, 31, 45, 59, 73, 87, 101, 115, 129],), ([3, 18, 33, 48, 63, 78, 93, 108, 123, 138],), ([3, 19, 35, 51, 67, 83, 99, 115, 131, 147],), ([3, 20, 37, 54, 71, 88, 105, 122, 139, 156],), ([3, 21, 39, 57, 75, 93, 111, 129, 147, 165],), ([3, 22, 41, 60, 79, 98, 117, 136, 155, 174],)]
```

Having these functions we have to sort the nodes into signatures.

Now that the nodes are under control we can turn to the data.
We can envision the data as a tree instead of a list. 

Each linked output socket has a data tree.

So for each node we parse the trees associated with match the different levels using some form of iteration, apply the node function with matching data and creates trees for each associated output socket. Each nodes can get called unspecified number of times instead of once per layout as now.

Some nodes, mostly the ones dealing with output, will have to be treated specially. Probably given a list from flattened version of input tree or will have be rewritten.

 ```python
# sketch of execution mechanism
# DAG gives nodes in correct eval order
# data_trees is and interface for storing socket data
# recurse_tree matches data and executes function, while building tree
def exec_node_group(node_group):
    for node in DAG(node_group):
        for socket in node.outputs:
            if socket.is_linked:
                data_trees.add(socket)
                out_trees = data_trees.get(socket)
        func = compile_node(node)
        trees = []
        for socket in node.inputs:
            if socket.is_linked:
                tree = data_trees.get(socket.other)
                trees.append(tree)
        recurse_trees(func, in_trees, out_trees)
```

**Comment by enzyme69** [comment]
I often thought how you guys would manage such nodes in a long run.
Monumental tasks indeed.

Ly29 got points!

I am reading and studying.

**Comment by ly29** [comment]
![skarmavbild 2017-01-12 kl 14 50 07](https://cloud.githubusercontent.com/assets/6241382/21892310/7a386924-d8d6-11e6-92f1-cfba74a4451a.png)
The following is working right now.

**Comment by ly29** [comment]
https://github.com/nortikin/sverchok/tree/inf_comp

**Comment by ly29** [comment]
![skarmavbild 2017-01-12 kl 15 57 00](https://cloud.githubusercontent.com/assets/6241382/21894516/ca7c7b10-d8df-11e6-9a2f-0dab5620f655.png)
```python
Range.002 0.0001 1
Range.001 0.0002 1
Range 0.00299 13
Scripted Node Lite 2.5886 481
Viewer Draw 0.0031 1
```

**Comment by ly29** [comment]
![skarmavbild 2017-01-12 kl 16 52 50](https://cloud.githubusercontent.com/assets/6241382/21896714/9a140b5c-d8e7-11e6-95fc-1dbd95814ddb.png)
Working reduce.

**Comment by ly29** [comment]
So what is needed is the complete organisation of nodes into the above categories. It isn't as bad as it sounds... Many nodes gives the same results for ```f(data)``` as ```[f(x)[0] for x in data]```

**Comment by nortikin** [comment]
waiting for weekend to investigate this peace of goodness

**Comment by ly29** [comment]
There are some/many issues still but I is the first attempt at generalising the nodes that I feel is achievable with our resources.

**Comment by ly29** [comment]
I propose to call this **0.6** #453 Sverchok 0.5 was, very long ago and this actually, short term, an even smaller project allowing a pass of all nodes making them much simpler, however that pass is a somewhat later problem...

I have some ideas of how to fix the remaining issues with this step, but since it solves so much in one step I think it is the way forward.

**Comment by ly29** [comment]
@zeffii 
Any comments?

**Comment by zeffii** [comment]
@ly29 i'll need to read the thread carefully and process, before blurting :)

**Comment by portnov** [comment]
Good ideas.

I'd propose to extend them:

* Each node should be a function, declaring types of inputs, and outputs. Whether it wants Int, or List of Ints, or Vertex, or List of Vertices, or Lsit of List of vertices, or whatever. There should be some simple way to declare some number of "standard" types.
* The function works only with one item, it does not loop by input lists.
* There should be standard settings in each node about how it should be vectorized. These settings are similar to List Match node settings. They are not implemented in each node, but by some common code called by all nodes "automatically".
* So if we have a node that takes list of vertices and returns a list of vertices; then we can easily turn it to one taking list of list of vertices and returning list of list of vertices, just by changing node settings.

**Comment by ly29** [comment]
I agree portnov, what I proposed above is a transitional strategy. 

For declaring the actual nodes in the future think a SN 3 like syntax makes sense.

**Comment by zeffii** [comment]
I'm all for this. I think we have discussed this in Redux / @vectorize threads at a higher level. But can't offer much help initially, am happy and willing to jump on board once a few nodes are clearly defined as templates / good practice.

**Comment by ly29** [comment]
I will make this happen, hopefully soonish. I think have all issues under control...

**Comment by ly29** [comment]
There are some issues I am thinking about, basically how far to go in the change:

Scenarios

1. Full out redux, new syntax, new nodes, full numpy. Fully independent from Sverchok. Best long term. No transferred cruft, code only moved in small parts.
2. Partial redux, new syntax, old nodes working side by side (somewhat). Independent from Sverchok but allowing old nodes to co exist if Sverchok is installed. Could be partial numpy for transitional phase or no numpy, gradually removing cruft.
3. New execution system as outlined above, quickest but will still brake old layouts in many cases and reusing Sverchok syntax, will be less than optimal. Will keep cruft

Things I would like to sort out:
- Socket names and types
- Class names
- removing cruft

@portnov 

Comments
- types, most definitely
- Only with one item, Yes, node functionally should be atomic
- Here I am not totally convinced that there is only one way to go. I would like to use numpy which would the smallest unit for the system, but not necessarily the nodes ```np.array```
- Yes, the nodes aren't static in their relationship with functional signatures

**Comment by ly29** [comment]
Note to self:
20 most used node based on the templates.
```
FloatNode 94
ViewerNode2 79
GenVectorsNode 69
NodeFrame 66
Formula2Node 45
SvGenFloatRange 40
LineConnectNodeMK2 35
IntegerNode 31
NoteNode 26
ScalarMathNode 26
MatrixGenNode 22
ListJoinNode 18
VectorMoveNode 17
VectorsOutNode 16
MaskListNode 16
ViewerNode_text 15
SvCircleNode 12
ListFlipNode 11
SvBmeshViewerNodeMK2 11
SvTextInNode 11
SvInterpolationNode 11
GenListRangeIntNode 10
ObjectsNode 9
VectorMathNode 9
SphereNode 8
svAxisInputNode 7
ListLengthNode 7
SvLogicNode 7
NodeReroute 7
RandomVectorNode 7
```

**Comment by ly29** [comment]
I expect this to take more or less a month depending on my available time

1. Defining basic execution system, types, sockets nodes definitions. All based on SN3/SvRx
2. Implement a set of basic nodes as above/ ghosting ordinary Sverchok nodes (if easy)
3. Test/Evaluate, changes
4. Implement different Sverchok system, upgrading, manage node trees, groups IO Json (if needed)
5. Fill with nodes

During part 2 nodes will be kept according to the KISS methodology.

Since I have been at this before will talk so much more of until there is something to discuss.

**Comment by portnov** [comment]
I am interested in such a "refactored sverchok" :)
I am available at Saturdays/Sundays for coding and other days for consultations/reviews/etc. Please ask if you need help :)

**Comment by ly29** [comment]
@portnov 
I expect to have something by the weekend.

**Comment by zeffii** [comment]
I have things on my mind here, and have not much time to edit them. Not sure if they're the right time, but best said early. A few points i do want to argue for


- socket classes should 
    - have a `self.color` and a `self.color_reset`
    - [accept a draw function from the associated socket](https://github.com/nortikin/sverchok/issues/992) to allow properties from a node to be displayed in that socket.

- vectors should be `x y z w`. or offer v3 / v4 modes for Vector sockets.

In software modular sound systems the atomic/processing part of a node is called the `unit_generator`, it's what does the work on a given set of inputs.  For endpoint viewers/'to scene' nodes the unit_generator would need to take a parameter like `index`.

```python
    def unit_generator(self, idx, all_params):
        # idx to tell this function where in the iteration it is
        # self.last_idx could help this function determine when to do clean-up (remove stale objects./ meshes )
```

After having done all those svGet/Set removals, i've seen a lot of repetition, but also a lot of subtle differences in the code that leads up to the processing of input data. It comes down to

- making sockets available if dynamic
- decide when to return early before processing
- getting socket data ( expanding, extending where needed )
- arrange socket data for the unit_generator
- iterate over the socket_data and send each set of data to the unit generator, 
     - collect the output of unit_generator with each iteration
- iterate over collected data and pass to outputs

For many nodes the above steps will either be very similar, to the extent where it's formulaic and could be defined by a short dictionary if one or two things are unique -- is that the plan? I imagine there will be a variations on the compile function? custom compile functions for more esoteric nodes.. like viewers and dynamic nodes..

**Comment by ly29** [comment]
@zeffii 
What you say basically aligns with my thinking even if some details/naming might differ slightly.

Please expand on what how the ```socket.color_reset``` would be used.

Basically stateful things would get an before/after call alternatively be handed an ```generator```. The index way is also possible.

**Comment by zeffii** [comment]
maybe custom socket colors are not so important for all socket types, but it would allow us to use a single socket class to transport similar but slightly different data and give a visual cue to the user by coloring the socket a different way.

not a super big deal, it's place in that list was not to rank its importance.

**Comment by zeffii** [comment]
Experimenting with sockets did lead me to believe it would be good to have a convenient way to color them.

**Comment by ly29** [comment]
I wish blender properties where optionals like in switch and C# so the could be unset, would allow a really clean solution to this. Anyway, tinkering onwards.

**Comment by ly29** [comment]
I am making progress, but was busier this week than expected so sadly not there quite yet. I want to share something working, even if barely, to start the discussion with.

**Comment by ly29** [comment]
![skarmavbild 2017-01-22 kl 15 39 37](https://cloud.githubusercontent.com/assets/6241382/22183222/13d8d5a2-e0b9-11e6-8cb0-c87396977b42.png)
Not much too show yet, refactoring and integration takes longer than expected...

**Comment by portnov** [comment]
@ly29 
Are you making something from scratch or just creating new nodes for current sverchok?

**Comment by ly29** [comment]
@portnov 
I am making it from scratch, so everything is much leaner than before. But using some of my old code from various places.
I think if we get a working base system porting nodes will be quite easy. All doing that would allow us to standardise and clean up a bit.

**Comment by ly29** [comment]
No there yet...
https://github.com/Sverchok/Sverchok

**Comment by ly29** [comment]
I now have more time to spend on this. I will make this happen and make clear issues for different aspects. 

But on the new tracker to keep things organized. 
Will focus and that but still do bug fixing for the Sverchok 0.5x since it will take some time to get stable and fixed.

**Comment by ly29** [comment]
An basic outline over at https://github.com/Sverchok/Sverchok/issues/1
