### ISSUE TITLE
Skinner Node or BMesh MK2 with Skin Data

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1116]
I am testing this Vector Noise MK2 thing to generate wiggly lines. 

![screen shot 2017-01-12 at 10 46 32](https://cloud.githubusercontent.com/assets/3952687/21871190/8dcf4402-d8b4-11e6-974f-7fc27635d80c.png)

With BMesh MK2 Viewer, I can get this "edges", but I realized Alembic does not export Lines only, so I think OK I will just use Skin Modifier on top of this lines, it works for a single frame, but as Sverchok updated the BMesh MK2 viewer, the Skin Data get reset and lost.

If I am using SV Skinner node, it works only for a single mesh Edge.

What could be the best solution?

https://gist.github.com/487b9b8ba6369509c51646775341b2bb

**Comment by enzyme69** [comment]
I could perhaps join the mesh and use Skin Mesher, although sometimes I get "sausages".

![screen shot 2017-01-12 at 10 50 36](https://cloud.githubusercontent.com/assets/3952687/21871244/0313a7c6-d8b5-11e6-9c6b-1cf99081c6c4.png)

https://gist.github.com/8eb463b3a9750f733ed58a2436182bd0

Maybe there is a cleaner way to skin the Lines?

**Comment by zeffii** [comment]
- ask lukas toenne if it makes sense to add support in Alembic for verts+edges only.
- i might update `skin_mesher` node to mk2,  most of the needed code is written already.
- as for skin_modifier in the context of Bmeshviewer, Even if the skin_modifier wasn't invalidated between mesh updates, you'd still need to reset the vertex radii too somehow automatically. Making the internals of Bmeshviewer even more kludgy.

**Comment by zeffii** [comment]
unfortunately I think even when eventually it accepts verts/edges/matrix/radii past the first list, it will look essentially the same as if you mesh_join first. This is down to the way skin modifier behaves on that kind of mesh. For instance bake one such polyline with Viewerdraw, then add skinmodifier ..you'll see it the verts+edge is very twisty there will be the saucage / possibly self intersecting effect.

I think this has nothing to do with how skin mesher works specifically :/

**Comment by zeffii** [comment]
- can't fix the issue with bmeshviewer invalidating the skin-modifier between updates ( i see that as a bug in the modifier, but blender devs see that as sverchok trying to do something the modifier wasn't coded to be able to handle. )
- blender doesn't have a non operator way to move around _Modifiers_ (last i checked), meaning whatever I tried would feel ugly.
- Skin Viewer is a beta node, [please don't make new issues about it](https://github.com/nortikin/sverchok/issues/775). -- i'll continue in that one.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1132

![svkingif](https://cloud.githubusercontent.com/assets/619340/21954655/cb969336-da57-11e6-8c56-7119d0cbc35a.gif)
