### ISSUE TITLE
Vector Noise MK2 Scalar and Seeding

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1118]
![screen shot 2017-01-12 at 21 00 29](https://cloud.githubusercontent.com/assets/3952687/21885079/40160b3c-d90a-11e6-93b8-2ba90a2b4a7b.png)

@zeffii Vector Noise MK2 Scalar mode does not seem to work with seed.

**Comment by zeffii** [comment]
i can confirm, will look into it.

**Comment by enzyme69** [comment]
In the meantime, I will use Vector Out trick. Thanks!

**Comment by zeffii** [comment]
The function used to produce the random scalar value ( mathutils.noise.noise ) from a vector, is not influenced by the seed value. The problem here is the mathutils.noise module.

**Comment by zeffii** [comment]
see in text editor
```python
import bpy
import mathutils

noise_type = mathutils.noise.types.STDPERLIN
for seed_val in range(2, 6):

    mathutils.noise.seed_set(seed_val)
    for v in [(0,0,0), (1,0,0), (0,1,0),(0,0,1), (1,1,0)]:
        p = mathutils.noise.noise(v, noise_basis=noise_type)
        print(p)
```

**Comment by zeffii** [comment]
one option we have is to mix the output of `noise.noise` with `noise.random()` (which does get affected by seed).

@ly29  what do you think?

The rather unhelpful alternatives might be
   - hide the seed value/socket/ when in Scalar mode
   - draw extra label into ui to say scalar mode ignores seed.

Neither of those are appealing.

**Comment by ly29** [comment]
First I would like to have look at the noise module to see if is intentional how seed works, either seed influencing noise is a bug or is isn't.

**Comment by zeffii** [comment]
```
mathutils.noise.seed_set(seed)
Sets the random seed used for random_unit_vector, random_vector and random.

Parameters:	seed (Int) – Seed used for the random generator. When seed is zero, the current time will be used instead.
```
no explicit mention of mathutils.noise.noise being influence by seed.

**Comment by ly29** [comment]
I have reported two bugs for the noise module, one affected documentation and one a bug in the code.
It ain't the most well tested module in blender I guess.

**Comment by ly29** [comment]
Okay. So what happens is that the vector output i affected by a state vector generated from seed but scalar noise function isn't, whether that is totally intentional or not, it is inconsistent. 

If it is intended behaviour it should be noted.

So bug report time with question, are you up for it @zeffii ?

```C
static void noise_vector(float x, float y, float z, int nb, float v[3])
 {
          /* Simply evaluate noise at 3 different positions */
          const float *ofs = state_offset_vector;
          for (int j = 0; j < 3; j++) {
                  v[j] = (2.0f * BLI_gNoise(1.0f, x + ofs[0], y + ofs[1], z + ofs[2], 0, nb) - 1.0f);
                  ofs += 3;
          }
 }
```

```C
static PyObject *M_Noise_noise(PyObject *UNUSED(self), PyObject *args)
 {
         PyObject *value;
         float vec[3];
         int nb = 1;
         if (!PyArg_ParseTuple(args, "O|i:noise", &value, &nb))
                 return NULL;
  
          if (mathutils_array_parse(vec, 3, 3, value, "noise: invalid 'position' arg") == -1)
                  return NULL;
  
          return PyFloat_FromDouble((2.0f * BLI_gNoise(1.0f, vec[0], vec[1], vec[2], 0, nb) - 1.0f));
 }
```

Vs

```C
static PyObject *M_Noise_noise_vector(PyObject *UNUSED(self), PyObject *args)
 {
          PyObject *value;
          float vec[3], r_vec[3];
          int nb = 1;
  
          if (!PyArg_ParseTuple(args, "O|i:noise_vector", &value, &nb))
                  return NULL;
  
          if (mathutils_array_parse(vec, 3, 3, value, "noise_vector: invalid 'position' arg") == -1)
                  return NULL;
  
          noise_vector(vec[0], vec[1], vec[2], nb, r_vec);
  
          return Vector_CreatePyObject(r_vec, 3, NULL);
 } 
```

**Comment by zeffii** [comment]
i'm doing this sv_set/get maintenance stuff.. i'd like to continue that while i'm still in the mood.

**Comment by ly29** [comment]
Do that, I almost at a working #1112 so I not stopping that right now.
We can report a bit later.

**Comment by zeffii** [comment]
i don't mind adding a temporary kludge that uses the Vector noise for both Scalar and Vector out

for scalar it would measure the distance from the noise vectors to (0,0,1) , and since the max distance would be 2, all values are divised by that.   

```python
noise.seed_set(someval)
for v in input_vectors:
      u = noise.noise_vector(v)
      scalar_val = (vector(u)-vector(v)).length() / 2
```

**Comment by zeffii** [comment]
i haven't changed my mind about this kludge :)

**Comment by zeffii** [comment]
```python
def deepnoise(v):
    u = noise.noise_vector(v)[:]
    a = u[0], u[1], u[2]-1
    return math.sqrt((a[0] * a[0]) + (a[1] * a[1]) + (a[2] * a[2])) * 0.5
```

**Comment by zeffii** [comment]
![noise_scalargif](https://cloud.githubusercontent.com/assets/619340/21944852/907be8b6-d9d8-11e6-8e7f-d1a405227575.gif)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21945129/e24fc9c2-d9d9-11e6-9b21-17d0626f919f.png)

**Comment by zeffii** [comment]
infinite terrain generator

https://gist.github.com/c061e6432c35aad14e64897170252248

![image](https://cloud.githubusercontent.com/assets/619340/21989067/d7842d94-dc09-11e6-9f6b-5ad39b8f9588.png)
