### ISSUE TITLE
On the Limits of F8 reload

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1120]
There are so many things that can go wrong that I think we should say, please restart instead of just press F8.

Why?

> There are a number of other caveats:

> When a module is reloaded, its dictionary (containing the module’s global variables) is retained. Redefinitions of names will override the old definitions, so this is generally not a problem. If the new version of a module does not define a name that was defined by the old version, the old definition remains. 

> If a module imports objects from another module using from ... import ..., calling reload() for the other module does not redefine the objects imported from it — one way around this is to re-execute the from statement, another is to use import and qualified names (module.name) instead.

https://docs.python.org/3/library/importlib.html?highlight=reload#importlib.reload

Many changes are needed in the whole of Sverchok to make F8 reload work well, I think it less likely that we will be able to do these changes in a good way avoiding all pitfalls that exist.

All the in following form would have to be changed basically...
```python
from sverchok.data_structure import updateNode
```

**Comment by zeffii** [comment]
if F8 doesn't work after 2 attempts, then I restart. If that doesn't resolve then I'm the problem :)

**Comment by ly29** [comment]
Totally agreed 😄

**Comment by zeffii** [comment]
On top of that i'll often delete a Node too and recreate it after the F8 has completed - but a lot of the time for the smaller edits to nodes the F8 works fine :)

UI stuff (panels.. key combos) can be a bit hit/miss .
