### ISSUE TITLE
Vector Rewire

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1122]
![image](https://cloud.githubusercontent.com/assets/619340/21906889/78c4599a-d90d-11e6-87c7-c61bd46f7dbb.png)
maybe with 3 tickboxes,  X to filter a component. unticked to pass through.

**Comment by ly29** [comment]
It is a very common pattern, worth spending some time to think about a good ui for it.

**Comment by zeffii** [comment]
```python
  _____________________
    component replace
  _____________________
  |     vector out (v)-
  |     x | y | z     | 
  - vector in (v)     |
  - co replace (s)    |
  |___________________|

```

**Comment by ly29** [comment]
Yeah, that looks good.

**Comment by nortikin** [comment]
```  |     x | y | z     | ```
is it label?

**Comment by zeffii** [comment]
@nortikin  `x y z` would be enum.  one of those components would be replaced by 0 or values from `co replace`

**Comment by zeffii** [comment]
possibly a better name 'Vector MixIn'

**Comment by zeffii** [comment]
something like this

![image](https://cloud.githubusercontent.com/assets/619340/22211977/3bb60a64-e18f-11e6-82ca-5afac681b195.png)

**Comment by zeffii** [comment]
prelim node doc

---------------

### Vector Rewire

Use this node to swap Vector components, for instance pass X to Y (and Y to X ). Or completely filter out a component by switching to the Scalar option. it will default to `0.0` but if you pass it input via a socket it will  replace the component with the values from the socket. If the content of the Scalar input lists don't match the length of the Vectors list, the node will repeat the last value in the list or sublist.

**Comment by zeffii** [comment]
pushed, and wrote doc. 
https://github.com/nortikin/sverchok/pull/1169

solved my major needs, tho something seems broken in the docs online/offline operator..
