### ISSUE TITLE
Blender 2.8 Drops BGL

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1123]
There will be a replacement, but information about it is sparse. Worth querying the folks in charge. The viewers that rely on bgl will have the chance to be revisited.

- must be easier to do antialiasing on lines / polygons
- nicer vertex / dot representation
- automatic z-offset of lines drawn over polygons ( this is what causes our odd edge-width fluctuations )
- must make it easy to set a different font (fixed width) and set it's resolution to show non-blocky at reasonable zoom levels

**Comment by ly29** [comment]
Also worth noting it that from now on we can only draw triangles as per modern OpenGL, making tessellation a must in our pipeline.
I think a separate 2.8 branch is needed soonish since I suspect there will be some other python api changes, if not it is possible to have two separate backends for a transitional period.

**Comment by zeffii** [comment]
i follow the commit bot on twitter :)  https://twitter.com/BlenderLogs

**Comment by zeffii** [comment]
work in progress design discussion: i'm not sure i'm following the content here
https://docs.google.com/document/d/1rRaFqjRaElGZydeGqKTMq3N2_Ysyhii5MWmro9Q8Mr0/edit

**Comment by zeffii** [comment]
and here https://lists.blender.org/pipermail/bf-committers/2016-June/047455.html

**Comment by ly29** [comment]
So they are making their own thing that they will make python interface for. 
We will just have to wait and see. 
I guess with all the new graphics interfaces it makes sense to have unifying layer

**Comment by zeffii** [comment]
not much else to say here really, let's see what happens
