### ISSUE TITLE
The removal of old nodes

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1125]
The old nodes, many could be dropped soon I think. Here I am not so sure about the right way. This is better served as a new issue.

- [ ] old_nodes/bakery.py  💀
- [ ] nodes/vertex/noise.py
- [ ] old_nodes/circle.py ☠️ 
- [ ] old_nodes/eval_knieval.py  💀
- [ ] old_nodes/formula.py   💀
- [ ] old_nodes/kd_tree_edges.py
- [ ] old_nodes/list_item.py ☠️ 
- [ ] old_nodes/obj_remote.py   💀
- [ ] old_nodes/polygons_center.py
- [ ] old_nodes/random_vector.py
- [ ] old_nodes/range.py ☠️ 
- [ ] old_nodes/reroute.py ☠️ 
- [ ] old_nodes/series.py ☠️ 
- [ ] old_nodes/shift.py 
- [ ] old_nodes/sum.py
- [ ] old_nodes/test.py ☠️ 
- [ ] old_nodes/uvconnectmk1.py
- [ ] old_nodes/viewer.py   💀
- [ ] old_nodes/viewer_bmesh.py  💀
- [ ] old_nodes/viewer_text.py
- [ ] old_nodes/voronoi.py ☠️

**Comment by zeffii** [comment]
let's be clear what we mean and what the impact could be. These nodes are depreciated and may not work with changes made to the update system, and ongoing changes to bpy, we could keep their code around but that doesn't mean they'd work in _modern_ sverchok/blender

- old .blend might use these nodes, these nodes now all have better alternatives
- there is no automated system to replace depreciated nodes with their updated counterparts ( but this could be scripted .. )
    ```python
    for node in layout_dag:
          replace_if_depreciated(node):
    ```
    the time would be spent on creating a mapping dictionary for 
           old bl_idname : replacement_bl_idname
           old_socket : new_sockets  ( if different, if ommited then assumed identical )
           old params : new params  ( if different, if ommited then assumed identical )

**Comment by ly29** [comment]
Note also that not all new nodes are 1:1 match so setting additional options could be required...
I strongly vote to remove all nodes from the initial batch two years ago...

**Comment by ly29** [comment]
I will move forward with 0.6 project so not doing this.
