### ISSUE TITLE
Viewport slowdown (since moving to update_scene_pre/post ? )

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1126]
now I don't mean a small slowdown, i mean literally crawl viewport when rotating around a vdmk2 drawing monkey with 2 subdiv levels.

You may not experience this, and i'll test it with the older and later Blender versions, i'll resist to speculate what results in the slowdown. Some debugging will be done :)

**Comment by ly29** [comment]
Do you have object auto update or something like that on?

**Comment by zeffii** [comment]
nope...  i think there's full endpoint updates going on rapidly.

**Comment by ly29** [comment]
Ok. Start with verifying that.
This is the exact scenario that fails right?
![skarmavbild 2017-01-13 kl 16 35 04](https://cloud.githubusercontent.com/assets/6241382/21935552/47ed55a0-d9ae-11e6-893b-b1ae5e73c389.png)

**Comment by ly29** [comment]
See what the ```timings``` option in side panel print in the console?

**Comment by zeffii** [comment]
yeah, but i add the monkey off-centre so i don't need the vector_in-> matrix. otherwise identical.

i've replaced `scene_update_pre` with `post` and both are slow .

**Comment by zeffii** [comment]
yikes.. `callback drawn in 0.634977`  keeps on printing.. even if i'm not active inside blender..

**Comment by ly29** [comment]
Check if the node tree executes or just the callback.

**Comment by ly29** [comment]
Some things to uncomment here just to see. Might have to restart blender for these changes.

```python
@persistent
def sv_main_handler(scene):
    """
    Main Sverchok handler for updating node tree upon editor changes
    """
    for ng in sverchok_trees():
        # print("Scene handler looking at tree {}".format(ng.name))
        if ng.has_changed:
            # print("Edit detected in {}".format(ng.name))
            ng.process()
```

**Comment by ly29** [comment]
If it is then we know that it is this handler or coming from somewhere else.

**Comment by zeffii** [comment]
it's coming from `obj_in_mk3`

same geometry loaded with obj_in_lite is displayed fine and snappy in viewport during rotation.

**Comment by zeffii** [comment]
`obj_in_lite` node caches the geometry,  but `obj_in_mk3` processes the input entirely whenever `process` is triggered.

**Comment by zeffii** [comment]
with `obj_in_mk3` -> `vdmk2`  and 
```python
      if ng.has_changed:
            print("Edit detected in {}".format(ng.name))
            ng.process()
```
this is triggered repeatedly
```
Edit detected in NodeTree
Edit detected in NodeTree
Edit detected in NodeTree
Edit detected in NodeTree
Edit detected in NodeTree
Edit detected in NodeTree
...
```
about 4 times a second

**Comment by ly29** [comment]
This is very odd, I don't see such behaviour at all.

**Comment by zeffii** [comment]
oh.. maybe it's a stuck @perstant handler?

**Comment by ly29** [comment]
For some reason the ```.has_changed``` doesn't turn off or gets triggered in each update.

Try setting the ```.has_changed =  False``` at last line of the function 
https://github.com/nortikin/sverchok/blob/master/node_tree.py#L379-L389

**Comment by zeffii** [comment]
```python
    def process(self):
        """
        process the Sverchok tree upon editor changes from handler
        """
        if self.has_changed:
            self.build_update_list()
            self.has_changed = False
        if self.is_frozen():
            return
        if self.sv_process:
            process_tree(self)

        self.has_changed = False
```

**Comment by ly29** [comment]
It should never trigger from process. 
Put in a extra =false after execution of the node tree for now?

**Comment by zeffii** [comment]
looks to tame things down. so yes!

**Comment by ly29** [comment]
Do it :)

**Comment by zeffii** [comment]
ok :)

**Comment by zeffii** [comment]
i think perhaps the fact that obj_in_mk3 uses a temp mesh object (which when added or removed will trigger some scene update) may be of influence. also that node temporarily freezes the tree..

**Comment by ly29** [comment]
Either of those things I guess. 
What version do you use at the moment?

**Comment by zeffii** [comment]
```python
>>> bpy.app.build_hash
b'65582e7'
>>> bpy.app.version
(2, 78, 4)
```

for testing

**Comment by zeffii** [comment]
but I downloaded todays too. same was happening.

**Comment by zeffii** [comment]
I don't use `obj_in_mk*` terribly often on anything other than a cube, else this would have manifested itself a few days earlier.

**Comment by ly29** [comment]
Curious. Anyway good knowing that obj is causing it.
