### ISSUE TITLE
How to add a Vector noise transform onto a single axes?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1128]
First, this is my post here i want thanks all developers here for  this addon: sverchok is amazing!

my question i want trasform a mesh by adding a noise so i found Vector Noise MK2 node, the problem is i would to transform only the X or Y or Z values of the vertices not all at the same time. How can i achieve this?
Thank's 

Walter

**Comment by zeffii** [comment]
a quick way is to use _Modifier Change_ -> _Randomize Input Vertices_, and then pick which components you want to randomize.

**Comment by zeffii** [comment]
or using `vector noise mk2`
![image](https://cloud.githubusercontent.com/assets/619340/21939358/b5f5f42e-d9bf-11e6-972b-9e6760d44cf7.png)

**Comment by kalwalt** [comment]
Thanks @zeffii i will look into it!

**Comment by kalwalt** [comment]
![schermata del 2017-01-13 18-55-30](https://cloud.githubusercontent.com/assets/1275858/21939917/442aecc0-d9c2-11e6-8bc8-4cdb47d2bdd1.png)
Cool! i want to do now only for one component...

**Comment by zeffii** [comment]
remove one of the two Math nodes then (Mul X, Y)

**Comment by kalwalt** [comment]
yes i did. This was exactly what i would achieve
![schermata del 2017-01-13 19-15-08](https://cloud.githubusercontent.com/assets/1275858/21940472/d49e025e-d9c4-11e6-8f88-ebdbb6c86694.png)

**Comment by zeffii** [comment]
looks ok to me :)

**Comment by kalwalt** [comment]
Very simple i have to say,  At first i was puzzled to find how can be done with nodes, I code a bit in Processing and OpenFrameworks, to add noise you just neeed :
in OF: ofVertex( ofNoise(x), y , z);

**Comment by zeffii** [comment]
we could make a Noise version of "Randomize Input Verts", with a factor per component. then it would be like..3   generator - > NoiseOnInputVerts -> viewer :)

**Comment by zeffii** [comment]
Processing and OpenFrameworks, great stuff, welcome on board - or at least welcome to sverchok.

**Comment by kalwalt** [comment]
Appreciated, and glad to be here!

**Comment by zeffii** [comment]
we habitually close issues ASAP , nothing personal. 

- new questions are welcome.
