### ISSUE TITLE
Color Vertex Loopy Gradient

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1131]
Just wondering with this gradient thing, I think @ly29 is responsible :) I was wondering if the gradient can be vertical or horizontal? Instead of diagonal.

![screen shot 2017-01-14 at 12 13 04](https://cloud.githubusercontent.com/assets/3952687/21950852/1c48f0da-da53-11e6-8085-2e119c606f4e.png)

May use brain a bit, but I believe I need to make a repeating color for vertex 1,2 and then 3,4, etc... Hmm... such interesting case.

https://gist.github.com/34d44dec85f98deb3e2692b3c32133eb
https://gist.github.com/9dec7a2f9888abdde8fbbf3a3fa3f1bb

**Comment by enzyme69** [comment]
4 Colors supplied for loopy gave me this:
![screen shot 2017-01-14 at 12 21 05](https://cloud.githubusercontent.com/assets/3952687/21950943/027a3dac-da54-11e6-9a39-4e8ae79a0dd0.png)

I supposed I can do List Repeat and List Zip....

**Comment by enzyme69** [comment]
Ok so I am not that stupid after alll..

![Uploading Screen Shot 2017-01-14 at 12.23.32.png…]()

**Comment by enzyme69** [comment]
https://gist.github.com/301037cea3921620f404e47b6f6b9f11

**Comment by enzyme69** [comment]
[sverchok_gradient_003_2017_01_14_01_34.zip](https://github.com/nortikin/sverchok/files/705670/sverchok_gradient_003_2017_01_14_01_34.zip)

Just now, I realized with this setup, when I made changes to the Time Frame number, Sverchok suddenly reset itself and the SvCol disappear... Any idea?

**Comment by enzyme69** [comment]
![sv_gradient_error](https://cloud.githubusercontent.com/assets/3952687/21951111/0f4313f4-da56-11e6-9b7c-f462680aa23e.gif)

**Comment by ly29** [comment]
Will have to take a look

**Comment by enzyme69** [comment]
I think the looping over a face is quite interesting. Especially when
thinking of it in term of Colors, instead of index that draws the face.

Obviously the node seems to take care of looping. But I imagine if I
correctly think of color and pattern for each face dependant on the number
of vertices it has, I can list shift the number as pleased.

**Comment by ly29** [comment]
So you define the object in another node tree, the data gets overwritten since the order of execution is  undefined.

Define the object in the same node tree.
