### ISSUE TITLE
stethoscope mk2

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1135]
i left the original stethoscope super primitive, but I did intend to make it more like a tool that would help explore the content of a socket.

- it needs level selection
- needs abstract display type ( instead of data values show small quads of various colours to indicate postive, negative, 0 , 1, string .. i haven't decided yet..  
- color code braces/brackets/parens
- nicer font / higher res (adaptive to zoom and dpi )
- background optional.

**Comment by nortikin** [comment]
scroll somehow?

**Comment by portnov** [comment]
What is really needed imho in stethoscope or text view IMHO - is to show "shape" of data in terms of numpy: 1x100 for list of 100 integers, 1x100x3 for list of 100 vertices, 10x30 for 10 lists of 30 integers each and so on.

**Comment by zeffii** [comment]
agreed, often that values contained in the lists are not as relevant. but shape is.
I aim to do something about it.

**Comment by zeffii** [comment]
also https://github.com/theodickson/shapes

**Comment by ly29** [comment]
Also good to have something to plug into the new variant. I don't want to show before there are things to discuss, it but am making progress. If only I had some more time to work on it right now...

**Comment by zeffii** [comment]
now for some dinner.

![image](https://cloud.githubusercontent.com/assets/619340/22072854/f087d6e2-dda3-11e6-8000-0f9ebbc9fe39.png)

**Comment by nortikin** [comment]
new sthetoscope looks intrigued.
PS
what i understood today:
```python
for i in zip(*[[1,2,3,4,5,6,7,8,9,0]]*3): print(i)
```

**Comment by zeffii** [comment]
not serious btw 

![image](https://cloud.githubusercontent.com/assets/619340/22084595/073fb09e-ddd1-11e6-9389-e62bd7b9a8f9.png)

**Comment by zeffii** [comment]
a visual grammar for topology / geom data.. more experimentation tomorrow..

**Comment by zeffii** [comment]
now ,  back to more fun things..

**Comment by zeffii** [comment]
@nortikin  in python3 " the builtin function zip behaves like itertools.izip did in Python 2 "

**Comment by enzyme69** [comment]
In my opinion, Text Viewer big frame on the left is hardly used, best
placed on the right side like Stetoschope. And easy on off view.

I use Stetoschope for that reason. It's on the right side.

**Comment by zeffii** [comment]
uch.. it's difficult to get back into this now :/

**Comment by enzyme69** [comment]
Hi Zeffii, you can do it! :) Just motivational note.
