### ISSUE TITLE
What does it take to make Torus node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1136]
I realized that we don't have SV Torus node, so I am making it from scratch as node tree for now.
https://gist.github.com/c1ca412b5f37eb40607e840e8e5e2a1c

I can make it using node tree and it was under 15 minutes and now it's one way we can have torus.

However, there is this part I learn from @nortikin,  the Vector data plug into Angle to make this polar circular structure:
![screen shot 2017-01-17 at 10 22 59](https://cloud.githubusercontent.com/assets/3952687/22002321/249939d6-dc9f-11e6-8adf-e6df2aa6874d.png)

I am also wondering what it takes to create a real SV Torus node? If one of the devs make from scratch, how long will it take? Can you create a video creation of Sverchok Torus node, I will study it. 

If I were to make Torus node, for example, what is required? Because I can see that we already have:
- Torus Ops in Blender, can one just copy paste and modify script? Or that only works for Script node?
- We have Circle in Sverchok, maybe in order to make Torus, we can take that circle and use it.

Although I can make the Torus procedurally using node, but in order to actually make SV Torus node, where do one have to start?

**Comment by enzyme69** [comment]
![torus_001](https://cloud.githubusercontent.com/assets/3952687/22002442/3d707248-dca0-11e6-9ad1-cc80ba4d32b9.gif)

Hmm... yeah this part is strange isn't it.

**Comment by enzyme69** [comment]
Anyway this one I understand:
![screen shot 2017-01-17 at 10 33 42](https://cloud.githubusercontent.com/assets/3952687/22002476/7137ce6e-dca0-11e6-9d03-68b106d25caf.png)

**Comment by ly29** [comment]
It would be quite trivial to write. For me low priority right now.

**Comment by zeffii** [comment]
torus was planned for the geom module https://github.com/nortikin/sverchok/issues/854 but also low priority.

am surprised to see torus is missing from `bmesh.ops`

**Comment by ly29** [comment]
For now I suggest the monad method.

**Comment by enzyme69** [comment]
Ok, I guess we can leave it there. Somebody (me) needs to try to make a SV node. I still don't know how "trivial" is.

If only if anyone in the world make a node from scratch, make a video tutorial, and then post it. <=== if nobody, I will be the first.

**Comment by zeffii** [comment]
I'd use the lathe node, which is vectorized to the core :)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22014542/7b4d3c74-dc9e-11e6-9488-98f68fd329bc.png)

**Comment by zeffii** [comment]
### never a shortage of ways..

![image](https://cloud.githubusercontent.com/assets/619340/22014980/6a8e2446-dca0-11e6-804b-596692b3379c.png)


```python
"""
in major_segments     s   d=48    n=2
in minor_segments     s   d=12    n=2
in major_radius       s   d=1.0   n=2
in minor_radius       s   d=0.25  n=2
in abso_major_radius  s   d=1.25  n=2
in abso_minor_radius  s   d=0.75  n=2
out verts v
out faces s
"""

import bpy

verts = [[]]
faces = [[]]

mesh_set_before = {mesh for mesh in bpy.data.meshes}

data = bpy.ops.mesh.primitive_torus_add(
    major_segments=major_segments,
    minor_segments=minor_segments,
    major_radius=major_radius, 
    minor_radius=minor_radius,
    abso_major_rad=abso_major_radius, 
    abso_minor_rad=abso_minor_radius
)

mesh_set_after = {mesh for mesh in bpy.data.meshes}

data = (mesh_set_after - mesh_set_before).pop()


verts[0].extend([v.co[:] for v in data.vertices])
faces[0].extend([i.vertices[:] for i in data.polygons])

bpy.data.meshes.remove(data, do_unlink=True)
```

**Comment by ly29** [comment]
Sometimes I wish we could package monads as nodes for keeping the amount of nodes down...

**Comment by zeffii** [comment]
what if we just nodify the major parts of the python language.. that way each node would be described at highest level as a node and compiled to python text when needed.
https://pbs.twimg.com/media/Cz9OA85UsAAMMwe.jpg:large

**Comment by zeffii** [comment]
Way way way off topic

what if we "just" nodify the major parts of the python language.. that way each node would be described at highest level as a monad/node and compiled to python text when needed.
![img](https://pbs.twimg.com/media/Cz9OA85UsAAMMwe.jpg:large)

**Comment by ly29** [comment]
Would be fun but probably a biggish project...

**Comment by ly29** [comment]
That is really nice picture btw

**Comment by zeffii** [comment]
i was impressed too!

**Comment by portnov** [comment]
Idea which is more realistic for "refactored sverchok": if each node is basically a function; then we can compose nodes programmatically as easily as composing functions; something like 

```
def torus(...):
    return lathe(move(circle(..), ..), ..)
```

So having relatively small number of basic nodes, we could implement complex nodes easier.

**Comment by ly29** [comment]
Yeah something like that should indeed be possible.

**Comment by nortikin** [comment]
@portnov as i see, main transformations + generators + modifiers as functions or even classes...
what part of incapsulation is usefull here?

**Comment by portnov** [comment]
@nortikin 
if we had one generic data type for "mesh" (have no idea in what representation yet), and node functions could get and return "meshes", then we could compose these functions as in my example above. For now i have no idea how to "plug" one node into another programmatically to get complex node.

**Comment by zeffii** [comment]
I think an efficient chain would be bm all the way, and 
```
def bm_torus(...):
    return bm_lathe(bm_move(bm_circle(..), ..), ..)
```
Using bm in the function name to make it's return type obvious.  ideally, pipedreams, these functions would convert the first parameter to bm automatically if it was passes as a pydata 'tuple' . (v, e, f).

**Comment by zeffii** [comment]
a decorator might help a little, but it still becomes verbose...

```python
def bm_torus(maj_segs, min_segs, maj_rad, min_rad, abso_maj_rad, abso_min_rad):
    ...
    matrix_rotate = ...
    translate = abso_maj_rad  
    axis = (0,0,1)
    steps = maj_segs

    with bm_circle(verts=min_segs, radius=min_rad) as bm:
        with bm_rotate(bm, matrix_rotate) as bm:
            with bm_move(bm, translate) as bm:
                with bm_lathe(bm, axis, steps) as bm:
                    return bm
```

maybe not :)

**Comment by enzyme69** [comment]
On iPhone.

@zeffii how did you create that beautiful diagram?

**Comment by enzyme69** [comment]
@portnov

My dream is to be able to node Processing ... well there is NodeBox.

But so far Sverchok caters most of my ideas already. As it is.

But the Script Node is a pending study.

**Comment by zeffii** [comment]
> @zeffii how did you create that beautiful diagram?

it's not mine.  https://fossbytes.com/learn-it-faster-the-entire-python-language-in-a-single-image/
