### ISSUE TITLE
Viewer draw doesn't repeat topology info

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1137]
I got this setup with my torus. But looks like there is no "vectorization" happening.

https://gist.github.com/af11249b4d0d74fc3546bd3951b0257a

![screen shot 2017-01-17 at 11 28 58](https://cloud.githubusercontent.com/assets/3952687/22003493/2a30de86-dca8-11e6-8bc8-f63e36d54c8b.png)

**Comment by enzyme69** [comment]
However, MONAD seems to come to the rescue.

![screen shot 2017-01-17 at 11 40 26](https://cloud.githubusercontent.com/assets/3952687/22003704/cb6da094-dca9-11e6-8266-1c3329568d72.png)
![screen shot 2017-01-17 at 11 40 12](https://cloud.githubusercontent.com/assets/3952687/22003705/cb6dd0e6-dca9-11e6-9529-728373e5ebbb.png)

**Comment by ly29** [comment]
The monad is almost always the easiest answer to vectorisation problems.

## tip
if you only want location for matrix input you can just plug vertices directly into the viewer.

**Comment by ly29** [comment]
However in this case it shouldn't really matter, hmm. don't have to check right now.

**Comment by zeffii** [comment]
Formula Shape (according to the node's source file) can generate a torus !

**Comment by ly29** [comment]
Actually, the fail so to speak, or what actually happens is that Viewer Draw which doesn't repeat the face data but instead multiplies the first object with the matrices.

![skarmavbild 2017-01-17 kl 18 18 09](https://cloud.githubusercontent.com/assets/6241382/22031585/575b2e3c-dce1-11e6-90ae-bb9c3dd5fb8d.png)

Now this is a different debate altogether.

**Comment by ly29** [comment]
one best for a eventual mark 3 or redux I think.

**Comment by nortikin** [comment]
formula shape is defective initially. need to rethink of what inside
