### ISSUE TITLE
Objects In - Matrix Out for Empty is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1139]
![screen shot 2017-01-17 at 15 47 54](https://cloud.githubusercontent.com/assets/3952687/22008133/625dbb66-dccc-11e6-97d1-03c4bbe1976c.png)

I tried using Empy and want to use its 3D view position, using Object In and Matrix Out and failed.

I use Object ID Out MK2 is working though.

**Comment by zeffii** [comment]
i'll fix it today

**Comment by zeffii** [comment]
looking it now, very noob coding mistake :)
```python
                if obj.type == 'EMPTY':
                    continue
```

easy fix

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22012023/567f79ae-dc92-11e6-993c-65754985685a.png)

**Comment by zeffii** [comment]
commited the change to master. This can be done any number of ways. @ly29 @nortikin change this if it bothers you :)

**Comment by zeffii** [comment]
the fact that I freeze the nodetree here is a different, matter..

**Comment by zeffii** [comment]
The assumption in the above code is that you don't mix Empties and Objects (Mesh, Curve) in one selection of `Object_In`.

**Comment by ly29** [comment]
It was in old code as well so nothing changed there.
