### ISSUE TITLE
List Repeat, Pattern to Colorize Shell of Loose Mesh

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1140]
I am wondering if Sverchok actually provides means to do this.

If I am not wrong, this similar question has been asked before by me and @ly29 I think kind of gave the answer. 

Previously:
Multiple pieces of shells joined into a single mesh object. I wanted to colorize each pieces separately. 

But, what I want to know if I have:
[apple, banana, papaya]
[3,2,6]

What would be the quickest using nodes to turn it into:
[apple, apple, apple, banana, banana, papaya, papaya, papaya, papaya, papaya, papaya]

would this require numpy list or string actually can just do this quite easily?

**Comment by enzyme69** [comment]
![screen shot 2017-01-17 at 18 19 33](https://cloud.githubusercontent.com/assets/3952687/22011137/872417b4-dce1-11e6-81c7-a2189444ec26.png)

**Comment by enzyme69** [comment]
[random_pattern_013_2017_01_17_07_35.zip](https://github.com/nortikin/sverchok/files/710297/random_pattern_013_2017_01_17_07_35.zip)

1. I have a mesh, a single object, each has few separate shells.
2. Object In that mesh.
3. Separate object mesh loose part.
4. From 3, I can found out the number of polygon from each shells.
5. The plan is to colorize each shell using 1 color.

@ly29 showed me how at some point, trying to get that.

What I realize is that this might be simpler, if I can get the index numbers of polygon faces, each based on separate loose shell.

Then I can just pipe in the color.

**Comment by ly29** [comment]
That is good use case. I will try give answer tonight

**Comment by enzyme69** [comment]
Cheers @ly29 I supposed would be handy to have a node that output the Index Number of separate loose shells. -> Script Node is one option.

![screen shot 2017-01-17 at 19 55 17](https://cloud.githubusercontent.com/assets/3952687/22013776/e4934b92-dcee-11e6-986c-91de35aff15e.png)

**Comment by ly29** [comment]
Yeah Script node is the best option for a quick result. But yeah, there are number of things that would be useful to give as info from the things separate loose parts does.

Some *light* reading on the subject https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/mesh_separate.py#L46-L89

**Comment by ly29** [comment]
![skarmavbild 2017-01-17 kl 17 33 33](https://cloud.githubusercontent.com/assets/6241382/22029500/1820997e-dcdb-11e6-83cf-e3cbe43a3a6c.png)

So made a new mesh separate node.
Two new sockets and stable output order based on lowest index in each separate part.


![skarmavbild 2017-01-17 kl 17 32 38](https://cloud.githubusercontent.com/assets/6241382/22029476/02bbd72e-dcdb-11e6-8d13-72a99a41486b.png)

**Comment by ly29** [comment]
![skarmavbild 2017-01-17 kl 17 54 27](https://cloud.githubusercontent.com/assets/6241382/22030486/09a9e0dc-dcde-11e6-9d75-613155d65da3.png)
Random colors to each part.

**Comment by enzyme69** [comment]
That's... rocks! Thanks for this one @ly29 

I have a funny feeling that List Repeats is a bit like loop. But that is for some other time.

**Comment by enzyme69** [comment]
![screen shot 2017-01-18 at 11 32 09](https://cloud.githubusercontent.com/assets/3952687/22045976/d1468b16-dd71-11e6-9a30-10d5c52781ad.png)

I tried with Zeff Skin Mesher, and apparently something funky going on. Maybe the vertex order issue or something...

Result is super cool btw @ly29.

Instead of List Repeat, the index uses List Item, this is interesting!

**Comment by enzyme69** [comment]
[colorize_shell_005_2017_01_18_00_31.zip](https://github.com/nortikin/sverchok/files/712729/colorize_shell_005_2017_01_18_00_31.zip)

@ly29 maybe the sorting issue with skin modifier or something.

**Comment by enzyme69** [comment]
![screen shot 2017-01-18 at 11 50 46](https://cloud.githubusercontent.com/assets/3952687/22046384/60e28c14-dd74-11e6-9492-e8f80fcd9d23.png)
[shell_colorize_001_2017_01_18_00_51.zip](https://github.com/nortikin/sverchok/files/712740/shell_colorize_001_2017_01_18_00_51.zip)

3 Suzanne Head, Joined, and trying to colorize the shell.... there is something not quite right.

**Comment by enzyme69** [comment]
I realized I might have misplaced the noodle from Index of Vertex or Face.

![screen shot 2017-01-18 at 11 53 46](https://cloud.githubusercontent.com/assets/3952687/22046455/d6ab65f6-dd74-11e6-8b29-80290fbd460b.png)

**Comment by enzyme69** [comment]
![screen shot 2017-01-18 at 11 56 47](https://cloud.githubusercontent.com/assets/3952687/22046502/381254c6-dd75-11e6-9e30-4d490d181db3.png)
[colorize_shell_005_2017_01_18_00_56.zip](https://github.com/nortikin/sverchok/files/712747/colorize_shell_005_2017_01_18_00_56.zip)

For unknown reason this one is still funky.

**Comment by enzyme69** [comment]
Interesting how we can use Vector and ABS of Math.

**Comment by enzyme69** [comment]
![screen shot 2017-01-18 at 13 00 43](https://cloud.githubusercontent.com/assets/3952687/22047949/446357b2-dd7e-11e6-985d-f00b0ebf54e7.png)

Applying Modifier (Skin and Subdiv), separate mesh, rejoin and reassign this setup apparently fixing it.

Very interesting, maybe Blender's own issue.

**Comment by enzyme69** [comment]
Another weirdness.... related to Post Modifier Object In... there must be something...

![screen shot 2017-01-18 at 14 48 03](https://cloud.githubusercontent.com/assets/3952687/22050246/4537a9a4-dd8d-11e6-94f8-bec70e553c12.png)
[death_star_thing_003_2017_01_18_03_47.zip](https://github.com/nortikin/sverchok/files/713007/death_star_thing_003_2017_01_18_03_47.zip)

**Comment by enzyme69** [comment]
Solution is the same:
- Apply all modifiers
- Separate Loose Part (Blender Manual)
- Rejoin

**Comment by enzyme69** [comment]
I have a feeling it's SubDiv Modifier that scramble the vertex.

**Comment by ly29** [comment]
The things is, vertex color is stored for the base mesh, not the derived.

**Comment by ly29** [comment]
![skarmavbild 2017-01-18 kl 07 21 25](https://cloud.githubusercontent.com/assets/6241382/22053090/c5fcc3ba-dd4e-11e6-91b8-25e2f62336c3.png)
So something like this works out.

**Comment by enzyme69** [comment]
That's work like charm!!! Magic thanks Ly!

**Comment by enzyme69** [comment]
Love this thread, and will close it 🍡 thanks @ly29
