### ISSUE TITLE
List Split, is it vectorized?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1142]
I am wondering if List Split is vectorized...
https://gist.github.com/f9f2cca8e35975c5de3e2da3da3fba1a

Or is there another way?

![screen shot 2017-01-17 at 21 03 07](https://cloud.githubusercontent.com/assets/3952687/22015985/92282d00-dcf8-11e6-910f-1209717877e3.png)

Checking the node code...

**Comment by zeffii** [comment]
what was your intended outputs? 

   [[0,1],[2,3,4,5,6],[7,8,9]]     ?

**Comment by zeffii** [comment]
list Slice   if it was..
![image](https://cloud.githubusercontent.com/assets/619340/22016581/177196d8-dca7-11e6-98a9-c764e2b79432.png)

**Comment by ly29** [comment]
The code is somewhat opaque of how vectorized it is actually looking back...

**Comment by ly29** [comment]
Also then intention wasn't to do what you wanted if I remember correctly. All these questions and surprises with vectorization is rationale for #1112

**Comment by ly29** [comment]
The answer is no, it could become it, but for now I don't think investing the time is worth for me here since using list slice is possible.

**Comment by enzyme69** [comment]
List Slice it is then cheers!!
