### ISSUE TITLE
Skin Mesher observation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1143]
@zeffii 

The Skin Mesher node is very cool, but I am getting a funky thing.

This is alright:
![screen shot 2017-01-17 at 21 42 57](https://cloud.githubusercontent.com/assets/3952687/22017324/fc03ce32-dcfd-11e6-988b-e37dd3251193.png)

When I subdivided, there is like extra 1,2 points bit and maybe because of the lines?

![screen shot 2017-01-17 at 21 43 59](https://cloud.githubusercontent.com/assets/3952687/22017349/21106f1e-dcfe-11e6-96b5-ce2b511fd085.png)

GIST:
https://gist.github.com/c421195520d63204ccba926ee094e02a

The idea here is to use Line node and each Line will have a single radius.

**Comment by zeffii** [comment]
can't say I know why it does that... does the same happen if you manually do it?

**Comment by zeffii** [comment]
why not share the gist that produces exactly that second image.

**Comment by zeffii** [comment]
also. use this thread: https://github.com/nortikin/sverchok/issues/775
