### ISSUE TITLE
Line MK2

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1147]
![image](https://cloud.githubusercontent.com/assets/619340/22034239/eabff626-dceb-11e6-8d9d-c74345428784.png)

slightly tricky to compose the input lists for this, because unlike with the Circle node, the steps had been allowed to be non-constant. (With circle each segment is a constant angle away from the previous..)

I'm not saying this is the best approach to vectorizing a Line node, but it makes the most basic need a lot simple than the current one.

https://github.com/nortikin/sverchok/pull/1146

**Comment by ly29** [comment]
Plane has the same issue. For both it would be nice with a start option instead of only positive...

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22034524/e18579c2-dcec-11e6-9e47-841ce4fd7ddc.png)

**Comment by zeffii** [comment]
like a start Vector?

**Comment by ly29** [comment]
The thing is also that line is so easy to do with Vector in/UvConnect that I rarely get annoyed with it...
But I wish we had done the change a long time ago and standardised the generators.

**Comment by zeffii** [comment]
uv connect feels incredibly bloaty for making edges for simple lines..

**Comment by zeffii** [comment]
i almost want my own node folder with Lite versions of everything  :)

**Comment by zeffii** [comment]
the current Node List needs a red wedding.

**Comment by ly29** [comment]
Soon @zeffii, soon. Future nodes will be much lighter.

**Comment by ly29** [comment]
But totally agree with the red wedding...

**Comment by nortikin** [comment]
is it support different steps inside one node?
i propose vectorisation as is for line for everything.
Concept is simple at all
1 level of data - lines
2 level of data - data inside lines
3 level of data - more for sublists as sphere or plane when separated case.

I strongly propose to keep separated principle. I need it anyway.
Simplify? yes, but not loose this nestyness.
Especially for generators

**Comment by ly29** [comment]
The concept might be real simple but if isn't uniform it gets unpredictable real soon which makes things very hard to use. Anyway...

#1112 FTW long term

**Comment by zeffii** [comment]
@nortikin  it's never the intention to regress, but alternative versions (or modes) of the node will help other people who have different needs from a line node. Not a big deal for me either, i would rather have a Lite 'Edges from Verts sequence' node :) Float Range -> Vector In is a fine way to make lines.
