### ISSUE TITLE
the solidify's direction is random?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#1148]
why is that? because resort vests in solidify?

thanks for reply

[solidifyError.blend.zip](https://github.com/nortikin/sverchok/files/713000/solidifyError.blend.zip)

**Comment by ly29** [comment]
It should be based on the face normal. Will take look in a while.

**Comment by stansu** [comment]
thanks

**Comment by ly29** [comment]
Where I guess the problem is if anybody else has time to take a look.


```python
    bm = bmesh_from_pydata(vertices, [], faces)
    geom_in = bm.verts[:]+bm.edges[:]+bm.faces[:]

    bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])
    bmesh.ops.solidify(bm, geom=geom_in, thickness=t[0])

```
https://github.com/nortikin/sverchok/blob/master/nodes/modifier_make/solidify.py#L37-L41

**Comment by zeffii** [comment]
i recall concluding that line 40 (bmesh.ops.recalc_face_normals) is the culprit here.  based on previous issues on the tracker.

**Comment by ly29** [comment]
So better to use extrude for singular faces as it is now.
I the recalc_face_normals really needed, I don't remember. Wrote it almost 3 years ago.

**Comment by zeffii** [comment]
the solution is this
```
    for f in bm.faces:
        f.normal_update()
```

**Comment by zeffii** [comment]
we can offer both methods, 
   - the ops will be faster and work fine for larger meshes with few disjoint polygons 
   - the loop will always work, but potentially be slower.

**Comment by zeffii** [comment]
usually the `bmesh_from_pydata` doesn't need to return calculated normals, but i have no objection to adding a keyword argument to perform that last loop/normal_update when requested.

**Comment by ly29** [comment]
So the solution is adding bool switch with something like ```use recalc face normals ``` defaulting to current behaviour and the changes you suggest above.

**Comment by zeffii** [comment]
agreed

**Comment by zeffii** [comment]
![calgif](https://cloud.githubusercontent.com/assets/619340/22057253/31ee63e8-dd64-11e6-85b6-1da41f31dabb.gif)

**Comment by zeffii** [comment]
pull request to fix it.  pleaes test :) https://github.com/nortikin/sverchok/pull/1149

**Comment by zeffii** [comment]
@enzyme69  this fix should address issues you've had with seemingly random flipping when using solidify

**Comment by ly29** [comment]
@zeffii 
nice fix btw

**Comment by zeffii** [comment]
@stansu  the fix will be available when you next update sverchok.

**Comment by zeffii** [comment]
the fix seems so obvious now.

**Comment by stansu** [comment]
Great job, guys

**Comment by zeffii** [comment]
i should have called the second mode 'correct' and not 'accurate' , because i liked your quote @ly29 .

**Comment by ly29** [comment]
@zeffii 
😃

**Comment by zeffii** [comment]
it appears we can just use `bm.normal_update()` for accurate..

**Comment by ly29** [comment]
That does make sense.

**Comment by zeffii** [comment]
now , not so sure if it's worth the extra granularity to pass `fev`, if the single call continues to prove itself accurate..

**Comment by ly29** [comment]
Most likely not
