### ISSUE TITLE
More places to revisit recalc_face_normals

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1152]
update by @ly29

The following nodes, but this isn't as easy just changing, I think for example volume then recalc face normals might make more sense (or not):

pass 1  [committed](https://github.com/nortikin/sverchok/tree/recalc_normals)

- [x] polygons adaptive :octocat: 🉑 
- [x] solidfy  :octocat: 🉑 

pass 2 https://github.com/nortikin/sverchok/tree/normals_pass2

- [x] holes_fill  :octocat: 🉑 
- [x] offset :octocat: 🉑 
- [x] volume  :octocat: 🉑 
- [x] recalc_normals :octocat: 🉑 
- [x] vertex/normal :octocat:  🉑 
- [x] wire frame :octocat: 🉑

**Comment by ly29** [comment]
Yeah some of them more urgent than others.
Recalc was probably the wrong option...

**Comment by zeffii** [comment]
offset probably is next..

**Comment by ly29** [comment]
Polygons adaptive also

**Comment by zeffii** [comment]
ahhhyes! polygons adaptive, that's the one we've had issues with defo.

**Comment by ly29** [comment]
So moved the code to ```bmesh_from_pydata``` but didn't work out in adaptive polygons by default.

**Comment by zeffii** [comment]
I think i'd prefer this instead
```python
if faces:
        add_face = bm.faces.new
        if face_normals:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face)).normal_update()
        else:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face))
```
more code to read, but less instructions to compute

**Comment by ly29** [comment]
Yeah that works out as well.

**Comment by zeffii** [comment]
but don't change that unless add_face is magnitudes slower than testing `if face_normals`  : )

**Comment by ly29** [comment]
Nothing more will happen with this today from me anyway. Feel free to add things.

**Comment by zeffii** [comment]
yeah, not today for me either.

**Comment by ly29** [comment]
Actually some of these might need vertex normals which I guess also needs to be updated in a similar way after the faces...

**Comment by ly29** [comment]
```
if faces:
        add_face = bm.faces.new
        if face_normals:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face)).normal_update()
        else:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face))
        if face_normals and vertex_normal:
            for i in range(len(bm.verts)):
                 bm.verts[i].normal_update()
```

**Comment by zeffii** [comment]
maybe a nitpick. but if face normals are required for calculating vertex_normals, then face_normals should get set in the background to True if vertex_normal was passed as True ?
```python
    if faces:
        if vertex_normals:
            face_normals = True


        add_face = bm.faces.new
        if face_normals:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face)).normal_update()
        else:
            for face in faces:
                add_face(tuple(bm.verts[i] for i in face))

        if vertex_normals:
            # for i in range(len(bm.verts)):
            #    bm.verts[i].normal_update()
            for v in bm.verts:
                v.normal_update()
```

**Comment by ly29** [comment]
That would make sense to me.

**Comment by zeffii** [comment]
pretty solid module then at this point.

**Comment by ly29** [comment]
maybe just a ```normals=True/False``` and then we do them both?

**Comment by ly29** [comment]
![skarmavbild 2017-01-20 kl 08 37 19](https://cloud.githubusercontent.com/assets/6241382/22140283/ba2ec8e6-deeb-11e6-9f8b-f90bd33dc579.png)
Sometime I forget what an awesome node adaptive polygons is.

**Comment by ly29** [comment]
![skarmavbild 2017-01-20 kl 08 40 35](https://cloud.githubusercontent.com/assets/6241382/22140339/272bf338-deec-11e6-8eb4-75b6b90d65cb.png)
I feel that one of these could go and one could also give edge normals...

**Comment by zeffii** [comment]
A single Normals node.  makes sense.

**Comment by enzyme69** [comment]
Will use this at some point.

**Comment by zeffii** [comment]
>  maybe just a normals=True/False and then we do them all?
Face, vertex, and edge?

my only concern is the extra cost of calculating normals when they aren't strictly needed for the rest of the node's processing of a `bm`.  Be as computationally lean as possible initially.

**Comment by ly29** [comment]
Yeah, it shouldn't be done by default but as an option

```python
def bmesh_from_pydata(verts=[], edges=[], faces=[], normals=False):

# vs 
def bmesh_from_pydata(verts=[], edges=[], faces=[], vertex_normals=False, face_normals=False, edge_normals=False)

# vs
# normals as string with "vfe" and done as needed
def bmesh_from_pydata(verts=[], edges=[], faces=[], normals="")
      normals = normals.lower()
      vertex_normals = 'v' in normals
      face_normals = 'f' in normals
      edge_normals = 'e' in normals
```
I leaning towards 3

**Comment by zeffii** [comment]
i'm all for three and even wanted to suggest _exactly_ that method :)

**Comment by ly29** [comment]
well, we have been working on this for a while and our styles and ideas start align a bit I guess :)

**Comment by zeffii** [comment]
but also 
   if `v` or `e` in normals, then f is flipped to true.

**Comment by zeffii** [comment]
and 'a' in normals , then f,v,e are all flipped.

**Comment by ly29** [comment]
Yeah that makes sense.

**Comment by ly29** [comment]
Went the verbose route... Didn't have the energy to be clever.
```python
    vertex_normals = False
    face_normals = False
    edge_normals = False

    if 'a' in normals:
        vertex_normals = True
        face_normals = True
        edge_normals = True
    else:
        if 'f' in normals:
            face_normals = True
        if 'v' in normals:
            vertex_normals = True
            face_normals = True
        if 'e' in normals:
            face_normals = True
            edge_normals = True
```

**Comment by zeffii** [comment]
yeah, no need to write headfuck :)

**Comment by ly29** [comment]
The recent revisit to old code made me feel a like a lot less clever code is better many times.
If you want to test I think it is ready for master basically and then we can continue investigate things as needed.

**Comment by zeffii** [comment]
nicely described
```
    ''' verts is necessary, edges/faces are optional
        normals is a string of containing {'v', 'e', 'f', 'a'}
        so normals="f" will calculate face normals
        'e' and 'v' implies 'f' and 'a' does them all
    '''
```

**Comment by zeffii** [comment]
making the `normals` parameter a keyword means it's a nice drop-in , existing callers shouldn't notice a change, the default behaviour will be no normals anywhere.

**Comment by zeffii** [comment]
we _can_ probably drop these 
```
if hasattr(bm.verts, "ensure_lookup_table"):
```

**Comment by zeffii** [comment]
happy to test the commit, but want to find a computer here to test the upgrade stuff on.

**Comment by ly29** [comment]
That was some years ago so yes.

**Comment by ly29** [comment]
Merged the two mentioned parts above.

**Comment by zeffii** [comment]
i'll have a look at the rest today.

**Comment by zeffii** [comment]
maybe `normals='x'` performs 
```python
# at the top
face_normals, vert_normals, edge_normals = False   
# before returning.
bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])
```

**Comment by zeffii** [comment]
## Offset 
i'm not noticing (looking at debug timings) much speed increase on the `offset` node, so will set to fast recalc before pushing to master.   Until then you can test it with both.

## Next

**Comment by zeffii** [comment]
```python
def bmesh_from_pydata(verts=None, edges=None, faces=None, normal_update=False):
    ''' verts is necessary, edges/faces are optional
        normals is a string of containing {'v', 'e', 'f', 'a', 'x'}
        so normals="f" will calculate face normals
        'e' and 'v' implies 'f' and 'a' does them all
        'x' will only do a fast recalc_face_normals on bm.faces at the end
    '''

    bm = bmesh.new()
    add_vert = bm.verts.new
    _ = [add_vert(co) for co in verts]  # assign 2 throwaway variabe silences pylint
    bm.verts.index_update()
    bm.verts.ensure_lookup_table()

    if faces:
        add_face = bm.faces.new
        for face in faces:
            add_face(tuple(bm.verts[i] for i in face))

        bm.faces.index_update()

    if edges:
        add_edge = bm.edges.new
        for edge in edges:
            edge_seq = tuple(bm.verts[i] for i in edge)
            try:
                add_edge(edge_seq)
            except ValueError:
                # edge exists!
                pass

        bm.edges.index_update()

    if normal_update:
        bm.normal_update()
    return bm


```

**Comment by zeffii** [comment]
Ok. these are done.
