### ISSUE TITLE
Surface Normal to Point Normal

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1153]
![screen shot 2017-01-19 at 12 59 42](https://cloud.githubusercontent.com/assets/3952687/22090673/560dc168-de47-11e6-8140-2db861b102c9.png)

I wanted to know a method in Sverchok for Grease Pencil Curve to understand the surface normal. I reckon it will involve Ray somwhat. 

Closest Point on Surface and comparing original curve position and the ray probably equal the normal.

Any idea?

@Kosvor2

**Comment by enzyme69** [comment]
For reference:
![screen shot 2017-01-19 at 13 08 30](https://cloud.githubusercontent.com/assets/3952687/22090969/67739b52-de48-11e6-88f2-61f3bc468d10.png)

Still not sure why when those vector plugged into angle, we can get the normal.

**Comment by enzyme69** [comment]
So, far I know this fact, for 2 Vector Sub, can become like Point Normal for Matrix.

https://gist.github.com/088b8ee4458fb13843c20eebcac02c62

![screen shot 2017-01-19 at 13 27 23](https://cloud.githubusercontent.com/assets/3952687/22091351/11294ece-de4b-11e6-8427-37871388847c.png)

**Comment by enzyme69** [comment]
![screen shot 2017-01-19 at 13 30 03](https://cloud.githubusercontent.com/assets/3952687/22091536/684825ea-de4b-11e6-9aab-64d9bc41ac44.png)

Which means, very likely I found the answer...

Apparently didn't work before with Lines, because Line is pointing in X axis direction, should be Z like Cylinder.

Still surprised that Vector can be stuffed into Angle.

**Comment by enzyme69** [comment]
https://gist.github.com/b952857a3ba994c6e8d5857368688471

**Comment by ly29** [comment]
If you put the vertices into angle it will use it to calculate the rotation difference between rotation angle and the input angle. So if you use line change the rotation vertices input into the x axis.

**Comment by nortikin** [comment]
only put vertex to rotation is not universal case
maybe needed kdtree or object raycast node or something like that

**Comment by zeffii** [comment]
@enzyme69  first read the process function of a node you have questions about. it's the first step to getting more out of those nodes. You can treat these nodes as grey boxes, ( reading the code can give you a sense of what it does in certain scenarios, even if you don't understand how it works ) . You will be forever surprised until you make a habit of doing that.

### Matrix in has a special mode

When you connect vectors into the `locations` socket and vectors into `angle` sockets of the Matrix In node, it goes into a special mode that expects the data going into the `angle` socket to represent a direction or _Normal_. Location and Normal are then used to construct a Rotation Matrix.

----------------
It's not voodoo, but it's also not documented. We should fix this.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22101071/0e8081c4-de32-11e6-91f9-a7d9c666729d.png)
