### ISSUE TITLE
possible crashing scenario

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1155]
![image](https://cloud.githubusercontent.com/assets/619340/22104465/8a19f4f2-de3f-11e6-89a2-aaf8ebb5b61e.png)

more later.

**Comment by zeffii** [comment]
i've been able to do this a few time in a row now
- add plane
- add vdmk2
- add v noise , duplicate it down (don't change properties)
- add v evaluate
- hook up noise 1 to vertice A
- hook up noise 2 to vertice B
- hook v evaluate to vdmk2

**Comment by zeffii** [comment]
interesting.. in noise mk 2 there's this property without a default..
```
    noise_type = EnumProperty(
        items=avail_noise,
        description="Noise type",
        update=updateNode)
```

**Comment by zeffii** [comment]
maybe something less clever to make avail_modes here..
```
avail_modes = [(kind, kind, '', idx) for idx, kind in enumerate(dir(noise.types)) if not kind.startswith('__')]

[('BLENDER', 'BLENDER', '', 0), ('CELLNOISE', 'CELLNOISE', '', 1), ('NEWPERLIN', 'NEWPERLIN', '', 2), ('STDPERLIN', 'STDPERLIN', '', 3), ('VORONOI_CRACKLE', 'VORONOI_CRACKLE', '', 4), ('VORONOI_F1', 'VORONOI_F1', '', 5), ('VORONOI_F2', 'VORONOI_F2', '', 6), ('VORONOI_F2F1', 'VORONOI_F2F1', '', 7), ('VORONOI_F3', 'VORONOI_F3', '', 8), ('VORONOI_F4', 'VORONOI_F4', '', 9)]

```

**Comment by zeffii** [comment]
anyway, i'll only set the default for now..

**Comment by zeffii** [comment]
oh...

TypeError: EnumProperty(...): 'default' can't be set when 'items' is a function

**Comment by zeffii** [comment]
that can't be it then..

**Comment by zeffii** [comment]
![uhhhhhhgif](https://cloud.githubusercontent.com/assets/619340/22107401/dca43134-de4d-11e6-82bd-d99d7da27e4f.gif)

**Comment by ly29** [comment]
Strange crash. 
Would likely be better to write those noise types out, if a new one is added or the order changes.

**Comment by ly29** [comment]
One can be too clever for ones own good...

**Comment by zeffii** [comment]
yeah, i'll write them out. 

btw, debug-all   https://gist.github.com/zeffii/b32c9cb562d3dff82c9d70fdf561eb23

Error: EXCEPTION_ACCESS_VIOLATION

**Comment by ly29** [comment]
Turn on debug in sverchok and see how far we get...

**Comment by ly29** [comment]
If you are using a daily build my guess some changes in the api for opengl

**Comment by zeffii** [comment]
not using a new daily build ..

**Comment by zeffii** [comment]
very peculiar indeed :)

**Comment by ly29** [comment]
Could be line evaluate I guess, since it is not done before it is hooked up.

**Comment by zeffii** [comment]
would like to gut line evaluate and not use vectors.

**Comment by zeffii** [comment]
my money is on line evaluate, it's a node i almost never use...

**Comment by ly29** [comment]
In that case it should happen if you plug the output into some other node as well, and not view draw which is potentially one of the risker nodes

**Comment by zeffii** [comment]
yep, crashes without a vdmk2 on the scene too... just before connecting to `debug print` node . what the F :)

**Comment by ly29** [comment]
My guess is some change in the vector lerp function then.

**Comment by zeffii** [comment]
weird.. i can't make it crash while writing debug.log with or without sverchok's debug mode on.

**Comment by zeffii** [comment]
these kinds of crashes kill me a little on the inside.

**Comment by ly29** [comment]
The sverchok debug mode shouldn't affect things at all, it only print some timings basically...

Where lerp ends up
```C
void interp_vn_vn(float *array_tar, const float *array_src, const float t, const int size)
{
	const float s = 1.0f - t;
	float *tar = array_tar + (size - 1);
	const float *src = array_src + (size - 1);
	int i = size;
	while (i--) {
		*(tar) = (s * *(tar)) + (t * *(src));
		tar--;
		src--;
	}
}
```

**Comment by zeffii** [comment]
closing this til it can be reproduced withou fail.
