### ISSUE TITLE
Image node bug

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1159]
Probably a very low priority.

I made something like this:
https://gist.github.com/5cc36fac354b9328380755d7a10cde46

Supposedly just sampling an image and compared the distance before after the points and then use  those values for instance.

Now, reloading the Blend, I realized that it is complaining about the image.

Also other things:
- Is it possible to remove the limit of 100 x 100 pixels
- If the image is a sequence, can we force update in Sverchok?

```python
File "/nodes/generator/image.py", line 107, in process
    out = [self.make_vertices(IntegerX-1, IntegerY-1, StepX, StepY, self.name_image)]
File "/nodes/generator/image.py", line 140, in make_vertices
    xcoef = lenx//delitelx
Node Image had exception integer division or modulo by zero
```

**Comment by zeffii** [comment]
1. i too noticed ` integer division or modulo by zero` that's definitely a bug. seems to go away if you use multiples of 2 for step x, y.   

2. as for sequence of images, it could certainly be done. with relative ease, but the speed will be massively influenced by the image resolution.

**Comment by zeffii** [comment]
share a zip of these images .

**Comment by zeffii** [comment]
https://gist.github.com/cac9bf771e048d28102ed85ebb82959a  cuts out about a 3rd of the matrices..

![image](https://cloud.githubusercontent.com/assets/619340/22149576/d55aa2c4-df14-11e6-9254-f3eaf5daac95.png)

**Comment by zeffii** [comment]
the max `100` is hardcoded. any real changes to this node would need to be an mk2

**Comment by zeffii** [comment]
Note that an 100*100 produces a vertices set of 10.000, which is kind of heavy if that's at the start of a node tree. maybe when we switch to numpy arrays that won't be such a resource drain.

**Comment by ly29** [comment]
For many things the sample image script is a good idea for using an image as an influence instead of having all data as Sverchok data

**Comment by zeffii** [comment]
also distancepp had a small bug ( i've just committed mods )

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22150863/ade3168e-df1b-11e6-9c78-eb488a284488.png)

https://gist.github.com/cf2cfbb55dae291c9b64211ab139a3cd

**Comment by zeffii** [comment]
i get this a lot 
```python
 File "nodes\generator\image.py", line 107, in process
    out = [self.make_vertices(IntegerX-1, IntegerY-1, StepX, StepY, self.name_image)]
  File "nodes\generator\image.py", line 151, in make_vertices
    middle = (imag[addition]*R+imag[addition+1]*G+imag[addition+2]*B)*imag[addition+3]
Node Image had exception tuple index out of range
```

**Comment by zeffii** [comment]
likely to avoid that error maybe
```python
        for y in range(delitely+1):
            addition = int(ycoef*y*4*lenx)
            for x in range(delitelx+1):
                #  каждый пиксель кодируется RGBA, и записан строкой, без разделения на строки и столбцы.
                middle = (imag[addition]*R+imag[addition+1]*G+imag[addition+2]*B)*imag[addition+3]
                vertex = [x*stepx[x], y*stepy[y], middle]
                vertices.append(vertex) 
                addition += int(xcoef*4)
        return vertices
```
maybe
```
        max_index = len(image)
        for y in range(delitely+1):
            addition = int(ycoef*y*4*lenx)
            for x in range(delitelx+1):

                if addition+3 < max_index:
                    middle = (imag[addition]*R+imag[addition+1]*G+imag[addition+2]*B)*imag[addition+3]
                else:
                    middle = 0.0

                vertex = [x*stepx[x], y*stepy[y], middle]
                vertices.append(vertex) 
                addition += int(xcoef*4)
        return vertices

```

**Comment by zeffii** [comment]
or fix `addition = int(ycoef*y*4*lenx)`

**Comment by zeffii** [comment]
@ly29  @nortikin   not sure who originally wrote this node .. but this is my attempt at fixing it. probably easier for whoever wrote it to fix the intended algorithm, rather than my fix which addresses only the symptom.

https://github.com/nortikin/sverchok/pull/1161

**Comment by ly29** [comment]
Not me either.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22173976/1bdcc7aa-dfd2-11e6-9fbc-dc9a2dea3b0b.png)

no such restrictions on Image Decompose node btw. @enzyme69

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22174046/a9f4bda2-dfd4-11e6-9d4c-711141f34141.png)
