### ISSUE TITLE
cross-trees operator

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#1166]
watched vid https://www.youtube.com/watch?v=3QFX14OGm2Y and arized idea:
operator, handling selected node and taking outputs from AN to SV, from SV to AN, from material to SV etc.
So you select node, press keys combination and it popup dialog to send values to some other node tree. Think, it is not hard.

**Comment by ly29** [comment]
From Sverchok is probably pretty easy since we store so much data, from other things probably harder...

**Comment by enzyme69** [comment]
I remember having such wishlists some times ago.

So far this is one of my stupid hack that actually works to transfer data
between the two using intermediate live Mesh Data.

Set and Get sometimes does it to node. But gets trickier with multiple
datas.

So I use that trick. As long the data is in order.

**Comment by nortikin** [comment]
@enzyme69 in alpha section we have node remote control to handle one side from sverchok to other. but have no shortcut to get properties from AN directly. but i see it is dark matter for me to inevstigate foreign code

**Comment by enzyme69** [comment]
The GET and SET?

**Comment by enzyme69** [comment]
Oh Object and Node Remote Control? Wow... checking now..

**Comment by enzyme69** [comment]
![screen shot 2017-01-23 at 23 01 36](https://cloud.githubusercontent.com/assets/3952687/22203201/f05e829a-e1bf-11e6-807a-c16d442ced2c.png)

Not working, it has exception.

**Comment by nortikin** [comment]
that is why we need collaborate somehow or to ask someone to deal with it. one guy made json exporter-importer, maybe he can do...

**Comment by ly29** [comment]
What a node does and actually means is very different between node layouts so calling different nodes directly can be tricky, setting a blender property and that way triggering an update can work well in some scenarios but break down in other depending on a variety of circumstances.
