### ISSUE TITLE
Cannot install version 0.5.9.6

### ISSUE THREAD

**Issue by nantille** [nortikin/sverchok#1167]
Hello,

I cannot install the latest version, there is an undefined variable in __init__.py at line 131: "nodes is not defined". See screenshot below. I use the stable build 2.78a on MacOS.

![screen shot 2017-01-23 at 09 28 53](https://cloud.githubusercontent.com/assets/10866779/22196719/caf6aa4e-e14e-11e6-9cfe-b8ec69e516cb.png)

**Comment by nortikin** [comment]
try to remove sverchok completely and install it again or simply reopen blender and reactivate sverchok

**Comment by nantille** [comment]
I tried this several times already. The error is still there.

**Comment by nortikin** [comment]
i mean sverchok folder can be with other name so you got two sverchoks

**Comment by zeffii** [comment]
nantille, can you start blender from terminal, and take a screenshot of the full error/exception stack ?

**Comment by zeffii** [comment]
- definitely restart blender
 - enable that tick box by pressing only once ( the tick itself may take a while (30 seconds) to appear ticked ) (Sverchok is a heavy add-on to enable for the first time)

**Comment by nantille** [comment]
it now works! I had restarted blender still with the same problem. It might be due to multiple instances of blender running, that's my wildest guess. Something must have been kept in cache somewhere to trigger that error and I was patient, clicking once on the tick but the error appeared instantly.
This issue appeared when I tried to upgrade from an older sverchok version in the UI.

**Comment by zeffii** [comment]
i see, sometimes F8 isn't enough :)  lately there was a larger modification to sverchok's directory structure and did require complete DNR.

multiple instances conflicting, sounds about right.  Enjoy!

**Comment by nortikin** [comment]
from version 0.5.9.0 it needs to remove folder and instal from blank
