### ISSUE TITLE
Polyvox experiments

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1168]
Hi sv_developers! :sparkles:
I want to show to you what i'm working on. I'd like to use with blender the amazing Polyvox voxel library. Go here for a description: http://www.volumesoffun.com/polyvox-about/ . Polyvox is a C++ library but there are python bindings, Unfortunately aren't synced with the latest commit, they are a bit old (from 2014) but i builded them in linux64 if someone want to test. I'm new to python so it's not all clear of the language itself. So i'm sorry, maybe for you it's a easy task the code that i'm going to show. I used the ScriptedNode to code a test but I dont know if this is the best for testing pourpose. I think that the vertex aren't packed out correctly as shown in the screenshots. But at least the polyvox python bindings lib is loaded and the script too... How the vertexes should packed? and numpy is needed in your opinion?

```
import sys
sys.path.append("//home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-     master/node_scripts/templates/polyvox/lib") #This is just to point to the generated bindings

import PolyVoxCore as pv

def sv_main(vol_region=32,sphere_radius=30):
    in_sockets = [
        ['s', 'Volume region', vol_region],
        ['s', 'Sphere radius', sphere_radius]
       ]

    #Create a 64x64x64 volume of integers
    #volume = vol_region - 1
    volume = 32
    r = pv.Region(pv.Vector3Dint32_t(0,0,0), pv.Vector3Dint32_t(volume,volume,volume))
    vol = pv.SimpleVolumeuint8(r)

    #Now fill the volume with our data (a sphere)
    v3dVolCenter = pv.Vector3Dint32_t(vol.getWidth() // 2, vol.getHeight() // 2, vol.getDepth() // 2)
    sphereRadius = 30
    #This three-level for loop iterates over every voxel in the volume
    for z in range(vol.getDepth()):
       for y in range(vol.getHeight()):
          for x in range(vol.getWidth()):
             #Compute how far the current position is from the center of the volume
             fDistToCenter = (pv.Vector3Dint32_t(x,y,z) - v3dVolCenter).length()

             #If the current voxel is less than 'radius' units from the center then we make it solid.
             if(fDistToCenter <= sphereRadius):
                #Our new voxel value
                uVoxelValue = 255
             else:
                uVoxelValue = 0

             #Write the voxel value into the volume
             vol.setVoxelAt(x, y, z, uVoxelValue);

    #Create a mesh, pass it to the extractor and generate the mesh
    mesh = pv.SurfaceMeshPositionMaterialNormal()
    extractor = pv.CubicSurfaceExtractorWithNormalsSimpleVolumeuint8(vol, r, mesh)
    extractor.execute()

    #That's all of the PolyVox generation done, now to convert the output to something OpenGL can read efficiently

    import numpy as np

    indices = np.array(mesh.getIndices()) #Throw in the vertex indices into an array
    #The vertices and normals are placed in an interpolated array like [vvvnnn,vvvnnn,vvvnnn]
    vertices = np.array([[vertex.getPosition().getX(), vertex.getPosition().getY(), vertex.getPosition().getZ()] for vertex in mesh.getVertices()] )
    #to test the vertices...
    print(vertices)

    Verts = vertices
    Edges = []
    
    out_sockets = [
        ['v', 'Verts', [Verts]],
        ['s', 'Edges', [Edges]],
    ]

    return in_sockets, out_sockets
```

![schermata del 2017-01-23 12-28-28](https://cloud.githubusercontent.com/assets/1275858/22204275/59d6bb06-e171-11e6-828e-f63125353022.png)

You can find my experiments at this github [link](https://github.com/kalwalt/sverchok_nodes_collection)    with the python binding for linux64 and a .blend file ,and a .json for the ScriptedNode code.
If someone want to build the python bindings i reccomend to use this [commit](https://bitbucket.org/volumesoffun/polyvox/commits/cc430ae129d71e3625cfc63d7ce1612db197eacb) and follow these [instructions](http://www.volumesoffun.com/python-bindings-for-polyvox-preview/) 
and eventually this thread in the polyvox [forum](http://www.volumesoffun.com/phpBB3/viewtopic.php?f=14&t=693)

p.s. forgot to say the names of the files: use polyvox-text.py  and polyvox.test.blend

**Comment by kalwalt** [comment]
Another question related:
How i can debug inside the code? i added
 `print(vertices)` 
but do not output nothing in the console.

**Comment by zeffii** [comment]
kalwalt.  take a step back. 

make the smallest possible script and run it from the Blender Text Editor and see if that can produce output to the OS terminal/console . If that doesn't work, then that's where you learn how to fix it.

**Comment by nortikin** [comment]
maybe it breaks before print...

**Comment by zeffii** [comment]
yeah, no need for numpy here
```
vertices = []
for vertex in mesh.getVertices():
    p = vertex.getPosition()
    vertices.append([p.getX(), p.getX(), p.getX()])
```

**Comment by kalwalt** [comment]
thank u all, also i think numpy is not needed. I will try to simplify the things much possible, 
Probably something like this as  @zeffii  point out will track me to a right direction:

> vertices= []

 >for vertex in mesh.getVertices():
     p = vertex.getPosition()
     vertices.append([p.getX(), p.getX(), p.getX()])


Anyway  mesh.getVertices() i discovered return a tuplet, let's try how to handle it now.

**Comment by kalwalt** [comment]
Sorry to reopen this issue... i have done some good progress. Now we have something to  see. 
![schermata del 2017-01-24 16-42-34](https://cloud.githubusercontent.com/assets/1275858/22254714/b143cee4-e255-11e6-9ac0-2a310674c7cd.png)

The mesh is a cube alike shape because i used the minimum number of voxel and radius of the sphere. But i can't hanlde the edges in the right way Do you see something wrong in the code?
Also take a look at the output of the indices and compared it to the order of edges. 

```python
Edges = []
    
    for i in mesh.getIndices():
        
        edg = [indices[i],indices[i+1]]       
        Edges.append(tuple(edg))
    
    print("Total edges: " + str(len(Edges)))
    #Verts = vertices
    out_sockets = [
        ['v', 'Verts', [verts_out]],
        ['s', 'Edges', [Edges]],
    ]
```

```
Indices: (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)

N. of Indices: 36

Vertices: [(1.5, 1.5, 1.5), (1.5, 2.5, 1.5), (2.5, 1.5, 1.5), (2.5, 2.5, 1.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 1.5, 2.5), (1.5, 2.5, 2.5), (2.5, 1.5, 2.5), (2.5, 2.5, 2.5)]

N. vert: 24

Total edges: 36

[[[(1.5, 1.5, 1.5), (1.5, 2.5, 1.5), (2.5, 1.5, 1.5), (2.5, 2.5, 1.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 1.5, 2.5), (1.5, 2.5, 2.5), (2.5, 1.5, 2.5), (2.5, 2.5, 2.5)]]]

[[(0, 1), (1, 2), (2, 1), (1, 2), (1, 3), (2, 1), (3, 2), (4, 6), (2, 4), (2, 4), (4, 6), (6, 5), (5, 5), (5, 6), (6, 7), (5, 6), (7, 8), (6, 7), (8, 9), (10, 9), (9, 10), (9, 10), (10, 9), (9, 11), (11, 10), (10, 12), (12, 14), (10, 12), (14, 13), (12, 14), (13, 13), (14, 15), (13, 14), (13, 14), (14, 15), (15, 16), (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)]]
```

**Comment by zeffii** [comment]
your edges  have many repeats and reverses..

`(1, 2)` is the same edge as `(2, 1)`  

are you sure mesh.getIndices returns edges or is it returning Polygon indices... ? how many elements does each `i` in `mesh.getIndices()` have ? more than 2 ?

**Comment by zeffii** [comment]
else `mesh.getIndices()` is returning the flat list of edge indices..

**Comment by zeffii** [comment]
```python
indices = (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)

edges = [(indices[i], indices[i+1]) for i in range(0, len(indices)-1, 2)]
print(edges)

```

**Comment by kalwalt** [comment]
> are you sure mesh.getIndices returns edges or is it returning Polygon indices... ? how many elements does each i in mesh.getIndices() have ? more than 2 ?

Probably they return poly indices, infact looking into the example the polyvox indices are stored in a OpenGL Vbo, and if i'm right OpenGL Vbo should works only with triangles. Then i should output trianlges or poly as quads, how sverchok manage the polygons?

**Comment by kalwalt** [comment]
`indices = (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)

edges = [(indices[i], indices[i+1]) for i in range(0, len(indices)-1, 2)]
print(edges)`

i will try also this thanks!

**Comment by kalwalt** [comment]
your code give me better result but again there are some missed edge, and some edge use the same vertex, as(5,5) and (13,13) and duplicate edges:
```
current inputs  : ['Volume region', 'Sphere radius']
new required in : ['Volume region', 'Sphere radius']
current outputs  : ['Verts', 'Edges']
new required out : ['Verts', 'Edges']
Indices: (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)
N. of Indices: 36
Vertices: [(1.5, 1.5, 1.5), (1.5, 2.5, 1.5), (2.5, 1.5, 1.5), (2.5, 2.5, 1.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 1.5, 2.5), (1.5, 2.5, 2.5), (2.5, 1.5, 2.5), (2.5, 2.5, 2.5)]
N. vert: 24
Total edges: 36
[[[(1.5, 1.5, 1.5), (1.5, 2.5, 1.5), (2.5, 1.5, 1.5), (2.5, 2.5, 1.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (1.5, 1.5, 1.5), (1.5, 1.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 1.5, 1.5), (2.5, 1.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 2.5, 1.5), (1.5, 2.5, 2.5), (2.5, 2.5, 1.5), (2.5, 2.5, 2.5), (1.5, 1.5, 2.5), (1.5, 2.5, 2.5), (2.5, 1.5, 2.5), (2.5, 2.5, 2.5)]]]
[[(0, 1), (1, 2), (2, 1), (1, 2), (1, 3), (2, 1), (3, 2), (4, 6), (2, 4), (2, 4), (4, 6), (6, 5), (5, 5), (5, 6), (6, 7), (5, 6), (7, 8), (6, 7), (8, 9), (10, 9), (9, 10), (9, 10), (10, 9), (9, 11), (11, 10), (10, 12), (12, 14), (10, 12), (14, 13), (12, 14), (13, 13), (14, 15), (13, 14), (13, 14), (14, 15), (15, 16)]]
```

**Comment by zeffii** [comment]
ah..then yes `  (13, 13) ` suggests also that this isn't Edge indice list.

but a Tri index list
```python
indices = (0, 1, 2, 1, 3, 2, 4, 6, 5, 5, 6, 7, 8, 9, 10, 9, 11, 10, 12, 14, 13, 13, 14, 15, 16, 17, 18, 17, 19, 18, 20, 22, 21, 21, 22, 23)

tris = [(indices[i:i+3]) for i in range(0, len(indices)-1, 3)]
print(tris)

>>> [(0, 1, 2), (1, 3, 2), (4, 6, 5), (5, 6, 7), (8, 9, 10), (9, 11, 10), (12, 14, 13), (13, 14, 15), (16, 17, 18), (17, 19, 18), (20, 22, 21), (21, 22, 23)]
```

**Comment by kalwalt** [comment]
@zeffii the code works perfectly! Tested with a volume of 64 voxel and i get the classical voxelized sphere:

![schermata del 2017-01-24 23-41-49](https://cloud.githubusercontent.com/assets/1275858/22270274/18e0a822-e28f-11e6-8e9b-488f8e3a4067.png)

 Thank's so much! issue definetely closed...
and more to come

**Comment by kalwalt** [comment]
Better screenshot with mesh baked in the scene:

![schermata del 2017-01-24 23-51-41](https://cloud.githubusercontent.com/assets/1275858/22270538/5ad18728-e290-11e6-9721-ebefd12fefbe.png)

**Comment by zeffii** [comment]
lovely stuff :) @kalwalt
