### ISSUE TITLE
is List Math broken?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1170]
![screen shot 2017-01-24 at 10 43 58](https://cloud.githubusercontent.com/assets/3952687/22227923/104ef2da-e222-11e6-845c-dfc77e7f1127.png)

Very likely List Math node is currently is not working as expected.

Testing it with Image Decompose node. I wanted to get the average of R G B per color, but so far it does not work.

**Comment by ly29** [comment]
So decompose the vector per color into x y z. 
or use bbox node.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22236813/5eec60c2-e208-11e6-972d-a68095fa0e13.png)

**Comment by zeffii** [comment]
use `List Sum` node,

**Comment by zeffii** [comment]
probably the comma in the function_dict
```python
    def process(self):
        func_dict = {
            "MIN": min,
            "MAX": max,
            "AVR": self.avr,
            "SUM": sum,
            #"ACC": acc
            }
        if 'Func
```

**Comment by zeffii** [comment]
and 
```python
  File "nodes\list_main\func.py", line 83, in count
    for obj in data:
Node List Math had exception 'method' object is not iterable
```

**Comment by zeffii** [comment]
then
```python
        if 'Function' in self.outputs and self.outputs['Function'].is_linked:
            if 'Data' in self.inputs and self.inputs['Data'].is_linked:
                data = self.inputs['Data'].sv_get()  # <--- wasn't a function call
                func = func_dict[self.func_]
```

**Comment by zeffii** [comment]
seems like a bug to me too /w List Math

![image](https://cloud.githubusercontent.com/assets/619340/22237569/03b37894-e20d-11e6-83a4-ebea17b54fcd.png)

but you want List Sum anyway..

**Comment by enzyme69** [comment]
Interesting... especially that example with List Mask. Never thought of that.

**Comment by zeffii** [comment]
List Math has bugs. we will fix it.

**Comment by zeffii** [comment]
this corrects some coding artefacts https://github.com/nortikin/sverchok/commit/186cfdba790eab47806a9d66f687533f3eb59cc4

but doesn't fix the 'sum' mode, i'm not sure this is the intended use of the node anyway... @ly29 @nortikin  ?

**Comment by ly29** [comment]
Not sure, will take a look tonight.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22255436/ab710976-e257-11e6-98bd-267f81ea24b2.png)

i think list Math sum is fine btw..  since the small fixes..

**Comment by zeffii** [comment]
seems fixed...
