### ISSUE TITLE
How to use Text Out to dump RGB values?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1172]
I am dumping RGB from Image Decompose as CSV via Text Out.

But Text In cannot read that CSV.

![screen shot 2017-01-24 at 12 26 46](https://cloud.githubusercontent.com/assets/3952687/22230224/7a3e96b0-e230-11e6-8280-1be7cf4faa79.png)

**Comment by ly29** [comment]
Nobody can accuse the poor csv text node of being clever...

But try to decompose the vertices into x, y, and z.

**Comment by zeffii** [comment]
not sure what's generating that last character `[]` at the end there.. Try csv unix 

![image](https://cloud.githubusercontent.com/assets/619340/22245866/6988b8bc-e232-11e6-98aa-2180279e9119.png)

you'll notice that the it makes little sense to dump the colors without the xyz coordinates, also note that the  z component is 0.0 all the way here, meaning... you could just dump xy and forget z , and generate it later (at import time) if needed.

![image](https://cloud.githubusercontent.com/assets/619340/22245946/c811605a-e232-11e6-8850-17ba665aa0a5.png)

![image](https://cloud.githubusercontent.com/assets/619340/22246201/e5fed65a-e233-11e6-83a1-0030cc5315e0.png)

**Comment by ly29** [comment]
Looking back here I not entirely sure I get my reasoning for the flatten list part...
I don't want to dive into this code again right now.

In retrospect would it have made sense to dump vertices in 3 columns named, socket.x, socket.y and socket.z? Most definitely yes. But did I? No.

```python
        if self.text_mode == 'CSV':
            data_out = []
            for socket in self.inputs:
                if socket.is_linked:

                    tmp = socket.sv_get(deepcopy=False)
                    if tmp:
                        # flatten list
                        data_out.extend(list(itertools.chain.from_iterable([tmp])))

            csv_str = io.StringIO()
            writer = csv.writer(csv_str, dialect=self.csv_dialect)
            for row in zip(*data_out):
                writer.writerow(row)

            out = csv_str.getvalue()
```

**Comment by zeffii** [comment]
answered
