### ISSUE TITLE
Node Remote Control can't control certain nodes. why?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1173]
[image_decompose_study_006.blend.zip](https://github.com/nortikin/sverchok/files/725561/image_decompose_study_006.blend.zip)

Trying to pass values between 2 Sverchok Node Tree, apparently Node Remote is failed and values are not transferred.

**Comment by enzyme69** [comment]
![screen shot 2017-01-24 at 14 39 58](https://cloud.githubusercontent.com/assets/3952687/22233223/fe77a7b6-e242-11e6-8219-932246a8d8d7.png)

**Comment by enzyme69** [comment]
![screen shot 2017-01-24 at 14 41 42](https://cloud.githubusercontent.com/assets/3952687/22233257/3e55e29e-e243-11e6-8341-44ba24866fd7.png)

**Comment by enzyme69** [comment]
Simple test
[test_sum_2017_01_24_03_42.zip](https://github.com/nortikin/sverchok/files/725568/test_sum_2017_01_24_03_42.zip)

**Comment by zeffii** [comment]
Node Remove Control works by _settings_ the socket data of the destination node/socket. Some (many) nodes have a few lines of code at the top of their process function to test whether it's worth doing any work. One of those nodes is viewer_typography.py , it has this at the top of `process`

```python
 def process(self):

        if (not self.activate) or (not self.inputs['text'].is_linked):
            return

        # all code involved in generating output will be below this section 
        # not included for brevity.

```

The `self.inputs['text'].is_linked`  line really means, " does the Text socket have a real link? " . Node Remote Control aren't considered a real link, hence that's where the processing stops.

It's not a bug, the code is working exactly as intended - albeit it a way that makes NodeRemote->TypographyViewer interactions fail.

I could probably change that line to get the input (regardless of `is_linked`, and continue processing if the content of self.inputs['Text'].sv_get() is useful.

**Comment by zeffii** [comment]
i'd like to stress the fact that many many nodes have such criteria tests at the top of their process functions, so if you find a node that isn't responding to a Remote Control look at the source for that node, to confirm. Mostly it's arbitrary to implement the criteria that way, if I made a second pass one some of these nodes i'd probably not use `is_linked' in some places.

A simple solution would be a `Receiver Node` that you'd plug into whichever nodes don't listen unless 'physically connected'. 

low priority.
