### ISSUE TITLE
docs online/offline operator is broken. here's a fix

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1174]
as title implies.

**Comment by zeffii** [comment]
ok maybe you broke it @nortikin 
nodes/vector/... and not nodes/vertex
and docs/vector .... and not docs/vertex
we use Vector in the node catagories, and nowhere is vertex used. 

I propose this .  https://github.com/nortikin/sverchok/pull/1175

**Comment by zeffii** [comment]
May require users to do a DNR if they aren't using GIT.

should be last DNR for the forseable future .

**Comment by zeffii** [comment]
i've pushed this.

**Comment by nortikin** [comment]
have to fix docs vertex-vector

**Comment by zeffii** [comment]
yep. sorry :)
