### ISSUE TITLE
INSPIRATION: Chromata Generative Art Tool

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1176]
http://www.michaelbromley.co.uk/experiments/chromata/#playground

That kind of thing is fascinating. Probably best to use Processing or similar tool because this is kind of thing that continuously generating pixels.

@zeffii  @nortikin What do you think?

**Comment by enzyme69** [comment]
![snail_chromata_003](https://cloud.githubusercontent.com/assets/3952687/22273762/8a2378e0-e2f6-11e6-97c0-2fd7a244587f.png)
![snail_chromata_002](https://cloud.githubusercontent.com/assets/3952687/22273761/8a2246fa-e2f6-11e6-91d2-70e982e318c0.png)
![snail_chromata](https://cloud.githubusercontent.com/assets/3952687/22273763/8a25dd9c-e2f6-11e6-89e6-d16c62b7dedf.png)

I realized after a while, this algorithm generates something that looks like pattern and more like FILTER.... maybe not as exciting.

**Comment by zeffii** [comment]
processing or html/canvas,

but bpy can also write to pixels of the image. If you have a 100*100 px image and only modify 20 pixels at each iteration that's going to be a fast process. When you try to update each pixel that's when the slow down really happens.. what bpy won't do is make nice anti-aliases lines/curves for you..it won't look fantastic :)

but hey, this is off topic for the Sverchok issue tracker.
