### ISSUE TITLE
Fractals functions scripts

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1177]
Looking in sverchok nodes i can't found if there are yet implemented fractals functions from `mathutils.noise`, as i can see in the 'Vector Noise MK2' there are "only" `voronoi, stdperlin, blender, newperlin, cellnoise functions` Am i right ? So i coded this little script it seems to work but im a beginner with python, maybe you can tell me how to correct and fix it, or maybe there are a better way to code it.
My idea is to write a script with all the fractals inside ( well, the fbm, turbolence, hetero_terrain, ect.... i mean what is not included in 'Vector Noise MK')

```python
#fbm.py
from mathutils import noise, Vector

def sv_main( verts=[], h_factor=1.0, lacunarity=1.0, octaves=3 ):

    data = []

    in_sockets = [
        ['v','Vector', [verts]],
        ['s', 'H Factor ', h_factor],
        ['s', 'Lacunarity', lacunarity],
        ['s', 'octaves', octaves],
    ]

    out_sockets = [
        ['s', 'Float Data', data],
    ]
    print(range(len(verts)))
    
    for x in range(len(verts)):
        for y in range(len(verts)):
            for z in range(len(verts)):
                 
                 out = noise.fractal( Vector((verts[x][0][0],verts[0][y][0],verts[0][0][z])), h_factor, lacunarity, octaves )
                 data.append(out)
                 print("Float data: " + str(data))
                 
    return in_sockets, out_sockets
```

example in blender:

![schermata del 2017-01-25 19-07-44](https://cloud.githubusercontent.com/assets/1275858/22303058/d712857a-e331-11e6-8fa1-13697a3c6f99.png)

and also look the experiments with Polyvox libs and Fbm:

![schermata del 2017-01-25 16-15-59](https://cloud.githubusercontent.com/assets/1275858/22303142/328d482c-e332-11e6-8b08-ace8eade7c5d.png)

**Comment by zeffii** [comment]
cool! The VectorNoise MK2 has a limited scope. I encourage you to [look at it's source](https://github.com/nortikin/sverchok/blob/master/nodes/vector/noise_mk2.py)

once your script nodes work, explore writing a Node directly :)

- copy the source
- rename the copy `fractal.py`
- make a classname and bl_idname something like `SvVectorFractal` (including the registration below)
- add `SvVectorFractal` to index.md in the Vector subheading

**Comment by zeffii** [comment]
see this all data in sockets is wrapped in a `[  ]` , so if you only have one incoming list of verts it's going to be `[some_list_of_verts]` and to access it's content you need to do `[some_list_of_verts][0]` to read `some_list_verts`.

```python
from mathutils import noise, Vector

def sv_main( verts=[], h_factor=1.0, lacunarity=1.0, octaves=3 ):

    data = []

    in_sockets = [
        ['v','Vector', verts],
        ['s', 'H Factor ', h_factor],
        ['s', 'Lacunarity', lacunarity],
        ['s', 'octaves', octaves]
    ]

    out_sockets = [
       ['s', 'Float Data', [data]]
    ]

    if verts and verts[0]:    
        for v in verts[0]:
             out = noise.fractal(v, h_factor, lacunarity, octaves )
             data.append(out)
                     
    return in_sockets, out_sockets
```
have I confused you, check the docs for Script Node .

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22305016/3724bd40-e33a-11e6-83fb-933f47e2fa24.png)
![image](https://cloud.githubusercontent.com/assets/619340/22305037/54866280-e33a-11e6-8aef-54e4ca7bea61.png)

**Comment by kalwalt** [comment]
I will look into it. Thank's!

but 'verts' are like Vector in 'mathutils.Vector' ? because if i understood , the first argument of 'noise.fractal is a mathutils.Vector, right?

**Comment by kalwalt** [comment]
oh cool! didn't see your post! this is what i would to do!

**Comment by zeffii** [comment]
@kalwalt correct, that's what the documentation suggests,  but a while back maintainers added code to allow simple 3-tuple/lists as well as Vectors :)

**Comment by kalwalt** [comment]
> correct, that's what the documentation suggests, but a while back maintainers added code to allow simple 3-tuple/lists as well as Vectors :)

This simplify a lot the things!
Thank you again, will see what can i do from a code point of view!

**Comment by zeffii** [comment]
you're welcome. enjoy!

**Comment by kalwalt** [comment]
Something like this? But it's only a starting point... i need to look carefully into the code:
![screen -2017-01-25-19-07-44](https://cloud.githubusercontent.com/assets/1275858/22308630/04555632-e348-11e6-8c05-1b32cd2ede9c.png)

**Comment by kalwalt** [comment]
First question related, look at this:
```
noise_options = [
    ('BLENDER', 0),
    ('STDPERLIN', 1),
    ('NEWPERLIN', 2),
    ('VORONOI_F1', 3),
    ('VORONOI_F2', 4),
    ('VORONOI_F3', 5),
    ('VORONOI_F4', 6),
    ('VORONOI_F2F1', 7),
    ('VORONOI_CRACKLE', 8),
    ('CELLNOISE', 14)
]
```
 Noise types has a specific id in the enumeration , there is a multi_fractal reason for every type of noise to have a specific id? May i assign what id i prefer to Fractal,  Multi_fractal, Ridged_multi_fractal ect...?

**Comment by zeffii** [comment]
I manually enumerated them in that case, this is to control the Enum 's indexing. in case internally they changed in Blender's noise module. (that would break potentially the behaviour of sverchok's node )

> May i assign what id i prefer to Fractal, Multi_fractal, Ridged_multi_fractal ect...?

yes,, as long as the id doesn't change in the future for that node, if you make changes in the enumeration/id you probably need to go to a MK2 of the node to it doesn't break old node layouts.

**Comment by kalwalt** [comment]
ok, thank's for the clarification!

**Comment by ly29** [comment]
The main reason that the other noise types aren't in that node is because they have very different function signatures.

**Comment by kalwalt** [comment]
@ly29 yes i saw in the C source and in the API. I have forked sverchok and created a fractal_node branch [https://github.com/kalwalt/sverchok/tree/fractal_node](url) i have some question, i will ask in the next hours with more time as i will finish other stuff.

**Comment by ly29** [comment]
@kalwalt 
404 on that link. please ask away

**Comment by kalwalt** [comment]
Sorry @ly29  The fork should be online now, anyway it is labeled `fractal_node`. (Should i ask i pull request?)
At the moment i wrote the code for the fractal function, basically is similar to the script that @zeffii help me with, but i receive an error:
 
```
File "/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/scripts/addons/sverchok-master/nodes/vector/fractal.py", line 69, in fractal
    for verts in v[0]:
Node Vector Fractal had exception 'float' object is not iterable
```


Apart this issue, because `noise.fractal noise.multi_fractal noise.hetero_terrain noise.ridged_multi_fractal noise.hybrid_multi_fractal` return only float value i think we can delete the switch for Vector-Scalar. But correct me if i'm wrong. And it's not all clear to me for example: def changeMode(self, context): reside only in noise_mk2.py? may i delete in this case?

Thank you,
Walter

p.s. also would be nice a little preview of the fractal/noise in grayscale mode... what do you think?

**Comment by ly29** [comment]
create a pull request and we can review and comment

**Comment by zeffii** [comment]
@kalwalt   
1. you must check that `v` is,  if `v[0]` is a float, then perhaps `v` is already a vector. 
2. Yes you can of course remove a socket you don't need, and also remove the code used for switching.
3. happy to review the fractal_node too.

**Comment by zeffii** [comment]
if you refer to this
```
    if v and v[0]:
        for verts in v[0]:
             out = noise.fractal(verts, h_factor, lacunarity, octaves, _noise_type)
             data.append(out)
    return out
```

**Comment by zeffii** [comment]
i think `v` is infact a vectors..(3 tuple)
so
```python
def fractal(v, h_factor,  lacunarity, octaves, offset, gain, _noise_type):

    # h_factor=1.0
    # lacunarity=1.0
    # octaves=3
    return noise.fractal(verts, h_factor, lacunarity, octaves, _noise_type)
```

**Comment by zeffii** [comment]
> p.s. also would be nice a little preview of the fractal/noise in grayscale mode... what do you think?

would be great, but such things are essential for documentation, less essential for directly on the node (and unless you know how to do it.. i'm not going to have time to do that )
