### ISSUE TITLE
docs offline bug?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1183]
I compiled the docs with makefile in html format but Vector nodes do not appear in the display tree, i look i into nodes.rst and there is:

` Vertex <nodes/vertex/vertex_index>`

That's strange because i have a previuos version and it was displayng correctly, i compiled th doc with 
`make html` command and i'm on a Ubuntu 16.04 64bit machine.
I would also help with the docs but i never seen the .rst format, i will look in the python reference and will see what can i do. 
I would also know  if it possible to diplay the offline docs in html format. I saw the htmlhelp tag in the makefile, i compiled the docs with this tag, but at the end it display a .rst file.

**Comment by zeffii** [comment]
yeah, it should be nodes/vector/..

**Comment by kalwalt** [comment]
i fixed it look in my fractal_node branch.

**Comment by zeffii** [comment]
i pushed fixes to master

**Comment by kalwalt** [comment]
ok!

**Comment by zeffii** [comment]
@kalwalt  unfortunately the online html files are compiled only periodically, and aren't somehow uploaded automatically with the content created by `make html`.

maybe I should try to get the page response from the webbrowser and show `github/master/..../whatever.rst` if the page isn't available on the hosted manual.

**Comment by zeffii** [comment]
but I think offline should always work now :)

**Comment by nortikin** [comment]
ok
