### ISSUE TITLE
Fractal node outputs only Scalar?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1190]
I just noticed this new Fractal node.
![screen shot 2017-01-30 at 20 30 36](https://cloud.githubusercontent.com/assets/3952687/22418009/2afb3608-e72b-11e6-8e41-7741bd266e02.png)

From the docs, this line:
    Noise Function | Pick between Scalar and Vector output 

This node is very similar to Vector Noise MK2, with extra control over the noise... but however no Seed? 

Also, often the output give explosion for value nearing Zero for Lacunary, maybe we should just limit it?

**Comment by enzyme69** [comment]
This however is interesting:
![screen shot 2017-01-30 at 20 44 16](https://cloud.githubusercontent.com/assets/3952687/22418379/e7210848-e72c-11e6-8b09-04093cc7fd1f.png)

**Comment by kalwalt** [comment]
> Noise Function | Pick between Scalar and Vector output

sorry, my fault. the node output only scalar values. i think we can modify that line.

> This node is very similar to Vector Noise MK2, with extra control over the noise?

yes, with the difference that your out is only scalar and you have more control on it.

and about Lacunarity i wll do some more tests, The result depends on i think also what combination of noise with fractal are you using.

**Comment by enzyme69** [comment]
Aha... got it!

I will do a live noding video to kind of explore this Fractal node in basics:
![screen shot 2017-01-30 at 20 48 45](https://cloud.githubusercontent.com/assets/3952687/22418529/88e12e60-e72d-11e6-8971-caa160a35a6c.png)

Maybe if there is example that is not beyod obvious of the usage of this node.

**Comment by zeffii** [comment]
I don't think the fractal functions listen to the noise.seed, but a scriptnode could be written to prove this correct or wrong.

**Comment by kalwalt** [comment]
@zeffii i was thinking the same! in many software you can assign the seed to the fractal functions, it sounds strange to me that you can't assign it. (for example Terragen..)

**Comment by zeffii** [comment]
use this kind of code from Text Editor to test if seed makes a difference
https://github.com/nortikin/sverchok/issues/1118#issuecomment-272126774

**Comment by kalwalt** [comment]
i tested with the fractal function:

`import bpy
import mathutils

noise_type = mathutils.noise.types.VORONOI_F1
H = 1.5
lacunarity = 0.05
octaves = 3

for seed_val in range(2, 6):

    mathutils.noise.seed_set(seed_val)
    for v in [(0,0,0), (1,0,0), (0,1,0),(0,0,1), (1,1,0)]:
        p = mathutils.noise.fractal(v, H, lacunarity, octaves, noise_type)
        print('seed={0}'.format(seed_val), 'v', 'becomes', p)`

 it seems that seed do not affect the fractal function:

```
seed=2 v becomes -78.57662963867188
seed=2 v becomes -39.83271026611328
seed=2 v becomes -100.10897064208984
seed=2 v becomes -89.26876068115234
seed=2 v becomes -57.61077117919922
seed=3 v becomes -78.57662963867188
seed=3 v becomes -39.83271026611328
seed=3 v becomes -100.10897064208984
seed=3 v becomes -89.26876068115234
seed=3 v becomes -57.61077117919922
seed=4 v becomes -78.57662963867188
seed=4 v becomes -39.83271026611328
seed=4 v becomes -100.10897064208984
seed=4 v becomes -89.26876068115234
seed=4 v becomes -57.61077117919922
seed=5 v becomes -78.57662963867188
seed=5 v becomes -39.83271026611328
seed=5 v becomes -100.10897064208984
seed=5 v becomes -89.26876068115234
seed=5 v becomes -57.61077117919922
```

**Comment by zeffii** [comment]
yep, so not much we can do - except offer a faux seed which might randomly displace the incoming verts based on a seed value, and then pass them to the fractal function. 

```python
import random
import bpy
import mathutils

noise_type = mathutils.noise.types.VORONOI_F1
H = 1.5
lacunarity = 0.05
octaves = 3

for seed_val in range(2, 6):

    random.seed(seed_val)
    d = random.random() * 20, random.random() * 20, random.random() * 20
    for v in [(0,0,0), (1,0,0), (0,1,0),(0,0,1), (1,1,0)]:
        vr = d[0]+v[0], d[1]+v[1], d[2]+v[2]
        p = mathutils.noise.fractal(vr, H, lacunarity, octaves, noise_type)
        print('seed={0}'.format(seed_val), 'v', 'becomes', p)
    print()
```
_something_ like that. but it would be slower.
