### ISSUE TITLE
Color Pattern Study 10 x 10 grid

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1191]
I am thinking to do a COLOR PATTERN study using Sverchok. We don't have Color RGB and HSV yet, so it might be tricky, but I will start anyway.

[sv_color_pattern_006_2017_01_31_10_36.zip](https://github.com/nortikin/sverchok/files/741684/sv_color_pattern_006_2017_01_31_10_36.zip)

![screen shot 2017-01-31 at 21 38 29](https://cloud.githubusercontent.com/assets/3952687/22461505/a4c4e092-e7fd-11e6-9cb9-b3f06f2761cb.png)

The aim is to understand how to make:
- vertical gradient
- horizontal gradient
- circular gradient
- etc

I wanted to get that color pattern for example. But kind of stuck.

**Comment by enzyme69** [comment]
Similar to OSL, we can apparently use the position of each square to get pattern , such as:

https://gist.github.com/65ba41b12b25110e1458904984bd3916

![screen shot 2017-01-31 at 21 48 11](https://cloud.githubusercontent.com/assets/3952687/22461838/0c40ee90-e7ff-11e6-9cda-da32224e2faa.png)

**Comment by enzyme69** [comment]
Modulo:

https://gist.github.com/901e79eb820812b363157338029056a4

![screen shot 2017-01-31 at 21 50 08](https://cloud.githubusercontent.com/assets/3952687/22461890/454256b6-e7ff-11e6-8dfa-a1c7884d7a25.png)

**Comment by enzyme69** [comment]
X + Y ?

https://gist.github.com/dd274986547007e71bc508d458add532

![screen shot 2017-01-31 at 21 59 44](https://cloud.githubusercontent.com/assets/3952687/22462240/9ef1c6b4-e800-11e6-931c-3c7ffcbd3b04.png)

**Comment by enzyme69** [comment]
https://gist.github.com/fafa888162dd8c4c0ea7449bc7cdd8dd

![screen shot 2017-01-31 at 22 04 03](https://cloud.githubusercontent.com/assets/3952687/22462389/34844198-e801-11e6-8bf6-6e443a81d392.png)

**Comment by ly29** [comment]
Hint, you interpolate colors based on the coordinate.
So map the coordinate to uv and interpolate in a sensible way.

**Comment by enzyme69** [comment]
Map the Coordinate to UV? Interpolate? Scratching head... Normalizing?

**Comment by enzyme69** [comment]
![screen shot 2017-01-31 at 22 09 30](https://cloud.githubusercontent.com/assets/3952687/22462596/02dc693a-e802-11e6-8fb6-d0a95e0b5ab4.png)

Vector Math can be interesting, I realized...

**Comment by enzyme69** [comment]
I don't mind even if we use Script Node.

**Comment by ly29** [comment]
Noise can also be fun also.
![skarmavbild 2017-01-31 kl 12 23 58](https://cloud.githubusercontent.com/assets/6241382/22463039/32392274-e7b0-11e6-8eae-2fb8a40e3194.png)

**Comment by enzyme69** [comment]
@ly29 yes, the endless fractal noise thing is the best distraction.

I am thinking the UV overnight, you mean I need to place RGB over -0.5 to 0.5 ?

First of all, I think I am stil not 100% how to linear gradient in all 4 directions.

We can hack it in so many different ways, but wondering also the most mathematically correct way to do this.

Inigo Quilez and Fundza website will be my key study.

**Comment by enzyme69** [comment]
![screen shot 2017-02-01 at 10 00 39](https://cloud.githubusercontent.com/assets/3952687/22488313/5f290e1a-e865-11e6-88f7-d478f7cfcdff.png)

I might be able to use LERP too... somewhat

**Comment by enzyme69** [comment]
I just remember Distance will generate this Circular thing.

![screen shot 2017-02-01 at 18 45 47](https://cloud.githubusercontent.com/assets/3952687/22498819/b2b269e8-e8ae-11e6-88f4-5d965654139b.png)

**Comment by enzyme69** [comment]
REFERENCE:
https://thebookofshaders.com
https://thebookofshaders.com

**Comment by kalwalt** [comment]
Interesting your research and... thebooksofshaders is cool!

**Comment by enzyme69** [comment]
![screen shot 2017-02-01 at 21 20 01](https://cloud.githubusercontent.com/assets/3952687/22503111/410e10ec-e8c4-11e6-81ea-0460c578777d.png)

@zeffii Your LERP does not work, but EVALUATE works... interesting!

**Comment by ly29** [comment]
@enzyme69 
They do slightly different things https://github.com/nortikin/sverchok/blob/master/docs/nodes/vector/lerp.rst

**Comment by enzyme69** [comment]
https://gist.github.com/4e8fb16b1c4c76eb43c49e7927a8a935

Still trying to get diagonal gradient.

![screen shot 2017-02-01 at 21 33 31](https://cloud.githubusercontent.com/assets/3952687/22503505/272114f2-e8c6-11e6-9da5-b0c7f27fa685.png)

**Comment by enzyme69** [comment]
@ly29 the LERP is like as ShapeKeys.

**Comment by enzyme69** [comment]
@ly29  Any idea how to make this Vertical and Diagonal?

https://gist.github.com/2713ba7ed29b9780204370cda7f6c0d3

![screen shot 2017-02-01 at 21 36 17](https://cloud.githubusercontent.com/assets/3952687/22503579/8620a2ba-e8c6-11e6-87ec-da6e0dd71d67.png)

Looks like we can colorize either by factor of index or via the positioning of pixels.

**Comment by enzyme69** [comment]
@kalwalt I tried to understand this procedural shader so many times, but so far only understand some basics:
- modulo = repeat
- gradient
- sine
- noise
- absolute
- distance

It gets very confusing. My Math is just like that.

**Comment by enzyme69** [comment]
https://gist.github.com/6fefb3374651318712696545d2c5d594

![screen shot 2017-02-01 at 21 59 19](https://cloud.githubusercontent.com/assets/3952687/22504300/bb236c06-e8c9-11e6-9b6a-b4c6a5f6f512.png)

**Comment by enzyme69** [comment]
https://gist.github.com/65636ebe6914511b10c315989a7afc7c

![screen shot 2017-02-01 at 22 06 28](https://cloud.githubusercontent.com/assets/3952687/22504484/b59dd702-e8ca-11e6-9276-7b6d82faa312.png)

**Comment by ly29** [comment]
You are making great progress here @enzyme69

**Comment by enzyme69** [comment]
![screen shot 2017-02-01 at 22 09 32](https://cloud.githubusercontent.com/assets/3952687/22504573/22c4fda6-e8cb-11e6-808c-73f3f66c0396.png)

https://gist.github.com/d9af2cc6e62e4217f66e9dc43b125eed

**Comment by enzyme69** [comment]
Fractal node cheat:
https://gist.github.com/837c389f4f108746060dc43e9740768b

![screen shot 2017-02-01 at 22 11 53](https://cloud.githubusercontent.com/assets/3952687/22504651/850f1ad2-e8cb-11e6-8a79-ab011ca12ef9.png)

**Comment by enzyme69** [comment]
@ly29 I realized how vast (large, huge) this procedural texture is...

All I want for now is to generate that gradient UV Grid ...

But this is fun.

**Comment by enzyme69** [comment]
Is there a good open source book to study all this? 
 
![screen shot 2017-02-01 at 22 14 16](https://cloud.githubusercontent.com/assets/3952687/22504704/cbf8b5b6-e8cb-11e6-9217-09e05e3a9435.png)

**Comment by ly29** [comment]
![skarmavbild 2017-02-01 kl 12 46 54](https://cloud.githubusercontent.com/assets/6241382/22505595/9b877128-e87c-11e6-80f5-615c1f5bb0fb.png)

https://gist.github.com/f82ef4addf4247351ade9bb17fb8846a

**Comment by zeffii** [comment]
@enzyme69 

> @zeffii Your LERP does not work, but EVALUATE works... interesting!

please be more exact with your language,  Lerp does work, maybe what you were trying to do with it was illogical.

**Comment by enzyme69** [comment]
@zeffii Roger that, I apologize.

**Comment by enzyme69** [comment]
Ok, I understand the difference Vector Evaluate and Lerp:
https://gist.github.com/b0bb258ee247cc6e5f6e82f35919c6e7

Vector Lerp can be more useful for animation. Vector Evaluate can be for the RGB Color Lerp.

**Comment by enzyme69** [comment]
Evaluate Color...

![screen shot 2017-02-02 at 13 51 09](https://cloud.githubusercontent.com/assets/3952687/22535353/b09107d2-e94e-11e6-8d7a-434454d4bccc.png)

https://gist.github.com/6e51a894bd86a08a4f639b0bc036ee15

**Comment by enzyme69** [comment]
![screen shot 2017-02-02 at 13 52 46](https://cloud.githubusercontent.com/assets/3952687/22535383/e626fdf2-e94e-11e6-8d13-ae4bfdb067a0.png)

https://gist.github.com/589af73fd99e28ef7ba8148655e52f1f

I might make my RGB HSV Script Node for now... not vectorized. Or vectorized using Zeffii way.

**Comment by enzyme69** [comment]
I guess we can close this one until HSV RGB color node is invented. Thanks @ly29  @zeffii !

**Comment by enzyme69** [comment]
GIST:
https://gist.github.com/20741dd67040598059aad7d559c9b052

![screen shot 2017-02-21 at 16 44 04](https://cloud.githubusercontent.com/assets/3952687/23152259/fc719378-f854-11e6-9a13-0ce1a0ad17ae.png)
