### ISSUE TITLE
Move, Rotate, and Scale node are not vectorized?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1199]
I am trying to do this setup:
- Line separated into multiple edges
- each adge is resampled into 3 points
- 3 points is for the Arc creations
- Now I would like to move the center of 3 points using Move
- Move somewhat does not seem to vectorized, only 1 resulting Arc

https://gist.github.com/d5366c29201837c3235c8b7482aa455c

![screen shot 2017-02-03 at 11 19 24](https://cloud.githubusercontent.com/assets/3952687/22574430/df0f1298-ea02-11e6-8c23-921c1517b8f8.png)

**Comment by enzyme69** [comment]
![screen shot 2017-02-03 at 11 54 49](https://cloud.githubusercontent.com/assets/3952687/22575110/b2c82d5a-ea07-11e6-8320-2229c2270e7c.png)
https://gist.github.com/b0d97b1e1f5811b4e01f5bf3c07ee31b

**Comment by enzyme69** [comment]
Weird thing seems to work this way...

https://gist.github.com/a95b7cb41e772896a53e8b13ae782bd6

![screen shot 2017-02-03 at 11 58 41](https://cloud.githubusercontent.com/assets/3952687/22575188/255f664e-ea08-11e6-8672-3bb701ece1ee.png)

**Comment by nortikin** [comment]
it is too vectorized.
it works as for separate vertex so for objects
