### ISSUE TITLE
List Item node is probably broken also

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1201]
![list_item_failed](https://cloud.githubusercontent.com/assets/3952687/22574638/351d852e-ea04-11e6-8499-0437b3eb343e.gif)

I tried List Item today and the OTHER output is probably broken?

**Comment by ly29** [comment]
I will take a look at this

**Comment by ly29** [comment]
Sorry about that, good catch with both this and #1200 @enzyme69, thanks

**Comment by enzyme69** [comment]
@ly29 No need to say sorry, I thank you for time fixing bugs and enhancing! 👍 👍

**Comment by ly29** [comment]
well I caused them both 😄
