### ISSUE TITLE
Variable lacunarity script

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1205]
The script use the `mathutils.noise.variable_lacunarity(position, distortion, noise_type1=noise.types.STDPERLIN, noise_type2=noise.types.STDPERLIN)` it is interesting because mix two different noise types:

````python
from mathutils import noise, Vector

def sv_main( verts=[], distortion=1.0, noise_type1=1, noise_type2=2 ):

    data = []

    in_sockets = [
        ['v','Vector', verts],
        ['s', 'Distortion ', distortion],
        ['s', 'Noise type1', noise_type1],
        ['s', 'Noise type2', noise_type2]
    ]

    out_sockets = [
       ['s', 'Float Data', [data]]
    ]
    #variable_lacunarity(position, distortion, noise_type1=noise.types.STDPERLIN, noise_type2=noise.types.STDPERLIN)
    if verts and verts[0]:    
        for v in verts[0]:
             out = noise.variable_lacunarity(v, distortion, noise_type1, noise_type2 )
             data.append(out)
                     
    return in_sockets, out_sockets

````

![screen-variable-lacunarity](https://cloud.githubusercontent.com/assets/1275858/22630250/c6887962-ebf6-11e6-9ba1-5ac05114ccc6.png)

Should we develope it in a sverchok node?

**Comment by kalwalt** [comment]
![screen-variable-lacunarity01](https://cloud.githubusercontent.com/assets/1275858/22630362/24338a32-ebf9-11e6-940f-501b87f2949e.png)
with Voronoi F1 and Cell noise type.

**Comment by kalwalt** [comment]
![screen-variable-lacunarity02](https://cloud.githubusercontent.com/assets/1275858/22630384/81fb1d38-ebf9-11e6-91b3-d433f42f6159.png)
with NewPerlin and Voronoi Crackle noise type.

**Comment by kalwalt** [comment]
![screen-variable-lacunarity03](https://cloud.githubusercontent.com/assets/1275858/22630413/08d943e8-ebfa-11e6-9869-98b11ec1e7a4.png)
with StdPerlin and Voronoi F2F1 noise type.

**Comment by enzyme69** [comment]
I didn't know if this was even possible! Normally I made such thing using Blender Displace Modifier.

**Comment by portnov** [comment]
Played with the script yesterday. I think this should be a standard node :)

**Comment by kalwalt** [comment]
@portnov  i will start to work on it and will add to the Turbulence pull request https://github.com/nortikin/sverchok/pull/1188

**Comment by ly29** [comment]
This does look nice indeed.
