### ISSUE TITLE
totem monad

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1206]
@enzyme69 

![image](https://cloud.githubusercontent.com/assets/619340/22645864/83e5aa30-ec69-11e6-9b9c-edc9fd8fa0b5.png)

[array_inside_sverchok_004_2017_02_06_11_19.zip](https://github.com/nortikin/sverchok/files/754473/array_inside_sverchok_004_2017_02_06_11_19.zip)

**Comment by ly29** [comment]
Thank you @zeffii

**Comment by enzyme69** [comment]
![screen shot 2017-02-07 at 11 22 06](https://cloud.githubusercontent.com/assets/3952687/22672390/b2f80b74-ed27-11e6-9591-33c8f9a21fc1.png)

Aha..! The Objects In goes inside! Wonder why they cannot be outside. But that's ok for now. 

Cheers @zeffii !

**Comment by ly29** [comment]
Thay can be outside but then you will have to split the lists yourself using list split.

**Comment by zeffii** [comment]
The _objects_ are what you might consider one of the "constants" in your monad, hence no need to expose them as properties or sockets. Many ways to do this, this seemed most appropriate for the scenario.

**Comment by enzyme69** [comment]
Got it! Constraints is good sometimes. And thanks for tips on Split, Ly.
