### ISSUE TITLE
Making LEAF using Extrude Edge

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1208]
I only noticed Extrude Edge node the other day.

Thinking to make some kind of LEAF that grows in 2 directions. But instead getting this:

https://gist.github.com/0e94b8dfbe25fabffc859766e88b0e43

![screen shot 2017-02-07 at 10 02 42](https://cloud.githubusercontent.com/assets/3952687/22670311/bd7a7006-ed1c-11e6-8517-2a36d64eba5f.png)

**Comment by enzyme69** [comment]
And another strangeness... but cool.

https://gist.github.com/6a2a3eaa2f5184f4bab238d84ca43247

![screen shot 2017-02-07 at 10 06 59](https://cloud.githubusercontent.com/assets/3952687/22670428/3477d1a8-ed1d-11e6-9600-e36f72893f8a.png)

**Comment by enzyme69** [comment]
Actually:
https://gist.github.com/f436cd4ce1842ba105ec97a194dbf78d

**Comment by enzyme69** [comment]
![screen shot 2017-02-07 at 11 14 19](https://cloud.githubusercontent.com/assets/3952687/22672223/9c7cccb4-ed26-11e6-889d-26d4b352b3a7.png)

This is the noob way:
https://gist.github.com/c5251c67217dcb121edbe47671f0ab1d

**Comment by enzyme69** [comment]
... and above gives a flipped normal.

![screen shot 2017-02-07 at 11 16 03](https://cloud.githubusercontent.com/assets/3952687/22672265/d907e768-ed26-11e6-9f43-e4b767deb003.png)

Not sure how to flip it back.

**Comment by nortikin** [comment]
list reverse node for polygons to reverse other part

**Comment by enzyme69** [comment]
Worked! Thanks @nortikin
