### ISSUE TITLE
Case of Extruding and wanting to remove inside polygon face

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1210]
![screen shot 2017-02-08 at 11 36 15](https://cloud.githubusercontent.com/assets/3952687/22718157/eae3b364-edf2-11e6-87fa-5c7a19e58dd3.png)

https://gist.github.com/471f411d0dea587c29a224714c2504bd

I tried extruding a plane and want to have no hole at extrusion. 

But we have only Extrude Separate at the moment. Resulting in this "bubbles".

There must be a way to get rid of polygons that are inside.

**Comment by portnov** [comment]
Maybe you just better use the Solidify node?

**Comment by enzyme69** [comment]
Actually you are right! :D Thanks!
