### ISSUE TITLE
Extrude with vector

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1211]
Unlike solidify or extrude separate, I need a node that takes a mesh and a vector and extrudes all face islands in the direction of the vector. May combine the mentioned nodes

**Comment by portnov** [comment]
I also thought of node which applies bmesh's extrude_region. The problem is how to select a region to extrude, i think in many cases you want to extrude not all faces.

**Comment by zeffii** [comment]
@portnov i can't find a bmesh operator by that name https://docs.blender.org/api/blender_python_api_2_78a_release/search.html?q=extrude_region&check_keywords=yes&area=default

**Comment by zeffii** [comment]
but : https://docs.blender.org/api/blender_python_api_2_78a_release/bmesh.ops.html?highlight=extrude#bmesh.ops.extrude_face_region  should be no problem

**Comment by zeffii** [comment]
using a mask list to select faces

**Comment by zeffii** [comment]
excellent project for a new contributor.  closing for now.
