### ISSUE TITLE
Mirroring Noise for Deformation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1212]
Probably a silly question, but can we actually "mirror" the force of Vector Noise or Fractal, and then applying it to deform mesh geometry?

https://gist.github.com/454a32e3eb419b5da69961f8cec0ffb9

![screen shot 2017-02-08 at 23 20 28](https://cloud.githubusercontent.com/assets/3952687/22737005/4ec22b24-ee55-11e6-8f83-e967f33147e7.png)

**Comment by zeffii** [comment]
I think it makes more sense to look for a way to Mirror verts+faces over an axis (matrix).

**Comment by portnov** [comment]
Maybe set "amount" parameter of SCALAR node to -1 or other negative value?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22738434/bc86ad86-ee07-11e6-8ff9-75695837aaed.png)

tho.. you will need to add a polygon reverse / invert direction on the mirrored side (I didn't add that)

https://gist.github.com/82df6e8a30fc594cfda5a9fe8c21499a

**Comment by zeffii** [comment]
here's with mirroring faces: https://gist.github.com/fb78399d97147a34a887d3b3f8ed93bf

**Comment by enzyme69** [comment]
Thanks so much all and especially @zeffii ! This is so useful! I can probably design some proper armor for my robots.

![sym_001](https://cloud.githubusercontent.com/assets/3952687/22763982/e32347a6-eebb-11e6-9e50-4946b6ee9ec6.gif)
