### ISSUE TITLE
Intersect Edges is not working?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1213]
I have suspicion the Intersect Edges node is no longer working at all...

https://gist.github.com/7f437b677991de2fd5fc156864e0a33c

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22774618/435df7e2-eea8-11e6-8845-216d9fc446d8.png)

fine here..

**Comment by zeffii** [comment]
fill holes was recently modifed, maybe i didn't test it extensively

**Comment by zeffii** [comment]
i'll look at `fill holes`

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22775188/cb684596-eeaa-11e6-861c-030663f003ed.png)

intersect edges needs a `remove doubles` after it - at one point I had a branch with an intersect edges node with remove doubles on the node... not sure what happened to it.

**Comment by zeffii** [comment]
i might make a removedouble property for fill holes - but it will be much later today

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22777045/4800c95a-eeb2-11e6-84c9-6f2a93ff4c6b.png)

https://gist.github.com/755df352f14f0f216d52b3ea2c4a5df0

**Comment by enzyme69** [comment]
Thanks Zeffii~ much appreciated!

**Comment by zeffii** [comment]
I've pushed an MK2 of intersect edges. Same docs will be fine for now.

- `doubles` toggle will perform a post processing step (becomes slower...but about the same speed as if you added a remove doubles node manually)

![image](https://cloud.githubusercontent.com/assets/619340/22853773/07de136a-f05f-11e6-879a-b11208287d67.png)

**Comment by enzyme69** [comment]
Thanks Zeff!
