### ISSUE TITLE
Flipping Normal Case again

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1214]
I am using this Fill Holes node and Recalculate Normal, but still getting Normals that are flipping. 

![screen shot 2017-02-10 at 10 36 31](https://cloud.githubusercontent.com/assets/3952687/22807789/daf33052-ef7c-11e6-860b-379b8fa19074.png)

Wondering if there is 100% solution for this.

I will look at latest related topic.

BLEND:
[sv_swimmingpool_basic_004_2017_02_09_23_37.zip](https://github.com/nortikin/sverchok/files/765278/sv_swimmingpool_basic_004_2017_02_09_23_37.zip)

GIST:
https://gist.github.com/a4ee283f83347bdfc34788833c4dbfc9

**Comment by zeffii** [comment]
nope. check their index order. and see the last time i responded to this kind of question and explained the polygon direction issue.

**Comment by zeffii** [comment]
here's a quiz for you @enzyme69 

draw an arrow on each polygon to indicate the direction, use the order given by the Index list on the right
![image](https://cloud.githubusercontent.com/assets/619340/22823074/699ccdfe-ef82-11e6-9fb8-33b6874a20a0.png)

**Comment by zeffii** [comment]
This selecively flips certain polygons ( wether you do this using list Reverse or RecalcNormals doesn't matter -- list reverse is fast, and RecalcNormals is designed to recalc normals of faces that have neighbouring faces... this example.. not a single edge is used by two faces -- therefor no faces have beighbours...(proximity and face of polygons close to eachother is irrelevant )

https://gist.github.com/939c7e97291c25b28300a313500009c1

![image](https://cloud.githubusercontent.com/assets/619340/22828656/c4c29080-ef9e-11e6-97a1-280e96374fca.png)


The list input in this screenshot is used to manually select polygons to flip. "That's great, but hardly procedural" I hear you think.

**Comment by zeffii** [comment]
If you look at node like `CentersPolsNodeMK3`  it calculates each face normal by doing

```python
norm = geometry.normal(v0, v1, v2)
```

which is fine if you have 3..or 4 vertices per polygon, but when you start to have many verts and concave surfaces, there's no guarantee that the normal of vertex 0,1,2 of that polygon will be pointing in the right direction.

**Comment by zeffii** [comment]
With VDMK2 we use the first 4 vertices to get the normal, and use the first found normal for the rest of that 'triangles' in that NGon. The Tesselate NGon is another extra step which may paint the direction of that polygon with the first found normal of all the subtriangles... and also there is no guarantee given that it represents the right direction.  This is one of the problems with NGons..

**Comment by zeffii** [comment]
An argument could be made for a `Flip Normals` Node, with these features

- Flip all Normals
- Flip masked Normals
- Flip Normals to Match an input Vector
- Flip Normals based on normalized average of each tesselated ngon towards input Vector

flip normals really means 'reverse polygon index direction'

One of us will really have to want this before it gets made. Learn to code jimmy, it's the only way :)

**Comment by zeffii** [comment]
```python
"""
in Verts v
in Polys s
in Direction v d=(0,0,1) n=2
out Polys_ s
"""

from mathutils import Vector
from mathutils.geometry import normal
from mathutils.geometry import tessellate_polygon as tessellate

Polys_ = []

# Don't try this on non-planar faces..

for idx, poly_list in enumerate(Polys):
    for poly in poly_list:
        if len(poly) in {3, 4}:
            n = normal(Verts[idx][i] for i in poly)
            print(n)
        else:
            # tesselate and average
            v = [Vector(Verts[idx][i]) for i in poly]
            for pol in tessellate([v]):
                n = normal(Verts[idx][i] for i in poly)                
                print(len(pol), n)
            print('___')

```

**Comment by zeffii** [comment]
proof that even tessellating first isn't going to do much good.. (maybe i did it wrong..)

**Comment by zeffii** [comment]
this lets you reverse polygons using a Mask List - This could be made into a Node
```python
in enumerate(Polys):
    POUT = []
    for i, poly in enumerate(poly_list):
        if Mask[i]:
            POUT.append(poly)
        else:
            POUT.append(poly[::-1])
        
    Polys_.append(POUT)

```
https://gist.github.com/a8d4a6c05471320ff78e45079fb2c65d

![image](https://cloud.githubusercontent.com/assets/619340/22838505/c419a80e-efc5-11e6-957d-8e96669ed491.png)

**Comment by zeffii** [comment]
but here is a normals flip that takes a Normal Vector (Direction) and try to flip the faces towards that Normal. 
```
"""
in Verts v
in Polys s
in Direction v d=(0,0,1) n=2
out Polys_ s
"""

from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata
from mathutils import Vector


Polys_ = []

# Don't try this on non-planar faces..

for idx, poly_list in enumerate(Polys):
    POUT = []
    
    bm = bmesh_from_pydata(Verts[idx], faces=Polys[idx], normal_update=True)
    for face in bm.faces:
        poly = [i.index for i in face.verts]
        if (face.normal - Vector(Direction)).length < 0.004:
            POUT.append(poly)
        else:
            POUT.append(poly[::-1])
    bm.free()
    Polys_.append(POUT)
```
_this_ should be a node.

**Comment by enzyme69** [comment]
That is an in depth conversational reply. Thanks a lot Dealga!! Yeah I
should add this to livenoding lecture. So I think I can use List Reverse
with mask... let me read through after this.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1218

that's pushed now. you should be able to update. If you have questions, try reading the source first. struggle.. then ask here.
