### ISSUE TITLE
Bake All for Viewer Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1216]
I realized there might be a need for a single button or command function for Sverchok that allows Bake All for every Viewer Node. This might have been asked before.

Is this something that's best to do via Python?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22827016/e70917a8-ef95-11e6-865a-ba0068a5a032.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22827056/251c5d20-ef96-11e6-96cb-abf020bf4b76.png)

**Comment by enzyme69** [comment]
Such hidden details make me love Sverchok.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
