### ISSUE TITLE
Cylinder Hacking, each separated into components and scaled, maybe twisted

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1219]
I probably should know how to do this, but somewhat brain cannot compute.

https://gist.github.com/5f9f2a722284abea3c40667f64984076
![screen shot 2017-02-11 at 22 24 24](https://cloud.githubusercontent.com/assets/3952687/22853377/0711a056-f0a9-11e6-911a-8e271c63b703.png)

The idea here is to use Scale node for each and every cylinder division.

I am somewhat stuck, too many List Split and List Del.

And there is also many situations where I want to get "middle point" of bunch of vector to scale it. And I was using Bounding Box. Wonder if there is a better way. Will Vector Average works?

**Comment by enzyme69** [comment]
This does not help much, somewhat I get multiple points...

![screen shot 2017-02-11 at 22 27 52](https://cloud.githubusercontent.com/assets/3952687/22853395/604bd9d4-f0a9-11e6-84a5-e24f659d792d.png)

I wanted to scale each ring of Cylinders.

**Comment by enzyme69** [comment]
If I use Circle, I kind of got it:

![screen shot 2017-02-11 at 22 30 16](https://cloud.githubusercontent.com/assets/3952687/22853412/b6ca2bd0-f0a9-11e6-98be-3f9e05214739.png)

**Comment by enzyme69** [comment]
But separating Cylinders into multiple Rings and trying to Scale each Rings separately... somewhat not as simple?

**Comment by enzyme69** [comment]
![screen shot 2017-02-11 at 22 34 40](https://cloud.githubusercontent.com/assets/3952687/22853434/4b01c380-f0aa-11e6-8c3c-ca98a0ea5479.png)

Back to zero...

**Comment by enzyme69** [comment]
Ohh... wait... 

https://gist.github.com/b0ba0d4cd093f6dfc9334b7c5ec3bb2b

![screen shot 2017-02-11 at 22 37 14](https://cloud.githubusercontent.com/assets/3952687/22853452/b8708cbc-f0aa-11e6-8277-39bfeee93a68.png)

**Comment by enzyme69** [comment]
https://gist.github.com/1e07af008ff47d9862ce9fd5d9f64ddf

![screen shot 2017-02-11 at 22 39 22](https://cloud.githubusercontent.com/assets/3952687/22853455/f587a34c-f0aa-11e6-8705-a42871c22ed1.png)

List Split apparently needs to be used few times.

**Comment by enzyme69** [comment]
Cylinder is weird that way interesting! Almost there is this hidden interpolation between the TOP and BOTTOM...

So problem seems fixed, but one little question, is there a way to get "center" or "mean" of many2 points? Or Bounding Box is fine?

**Comment by zeffii** [comment]
i'd consider a different starting point . 

![image](https://cloud.githubusercontent.com/assets/619340/22853845/8a04bffa-f060-11e6-902b-caf9069e74b8.png)

**Comment by enzyme69** [comment]
With Rounded Box capsule objects, can we control each ring separately from nodes?

Is what I am doing is already the most elegant way?
https://gist.github.com/32b9ddf1a8fae219887b5ec2855d9e99

![screen shot 2017-02-12 at 11 06 16](https://cloud.githubusercontent.com/assets/3952687/22858490/4e1726d2-f113-11e6-9443-2a4b1d22be6d.png)

**Comment by enzyme69** [comment]
While still on this, I was wondering, if I wanted to "twist" this Cylinder in such a way to get a Twisting Cylinder, how do I go about that that?

I know that List Shift is probably what I will need, but do I need to do List Flip or something?

This List Shift actually shifted the circle up down, instead of going around its vertices:
https://gist.github.com/9b111cd62e482a525199baff080a657f

**Comment by enzyme69** [comment]
@nortikin you have anything that already mention such case?

**Comment by enzyme69** [comment]
Hey, I think we can also make like Jelly Fish this way... that's next maybe.

But still, I wonder how to make Twist?

**Comment by enzyme69** [comment]
![screen shot 2017-02-12 at 11 31 01](https://cloud.githubusercontent.com/assets/3952687/22858611/c4d7e92a-f116-11e6-81c8-a40719f90f6d.png)
@zeffii I am getting a different result. I remember getting a capsule too at some point.

**Comment by enzyme69** [comment]
![screen shot 2017-02-12 at 11 32 11](https://cloud.githubusercontent.com/assets/3952687/22858617/eba325f6-f116-11e6-9976-3f04efcd01e0.png)

**Comment by zeffii** [comment]
you don't even need to separate those vertex rings on the circle. If you consider the xy scaling of each vertex to be a function of the Z height.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22861479/f980c5a4-f119-11e6-9788-7b2f7ee1838a.png)
we don't have a Node to conveniently lock the scaling of vectors to vectors XY/YZ/XZ

![image](https://cloud.githubusercontent.com/assets/619340/22861534/468fc164-f11b-11e6-8330-265e8e934909.png)

https://gist.github.com/b44b1d22e82fe662b605ca21757501c2

**Comment by zeffii** [comment]
also the amount of rotation can be a function of the Z value of each vertex

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22861565/3c8173a6-f11c-11e6-822f-abda083554db.png)

https://gist.github.com/5916509b55fed68d2de2846b2ead3d14

adding noise per Z level is also trivial

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22861590/d54dd818-f11c-11e6-9fe0-926c2bf97d04.png)
https://gist.github.com/d78b1ae8a9a68514bac738116d2e2470
