### ISSUE TITLE
Exploring Rounded Boxes 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1225]
Actually Zeffii started this, so I want to look more into this Rounded Boxes. Seeing what this capable of and exploring the inside. If we can control the component bits....

![screen shot 2017-02-12 at 11 33 42](https://cloud.githubusercontent.com/assets/3952687/22858627/29da435e-f117-11e6-9021-6ccfd23a490c.png)

**Comment by enzyme69** [comment]
How @zeffii get divisions along Rounded Box is still a mystery...

**Comment by enzyme69** [comment]
![screen shot 2017-02-12 at 11 39 55](https://cloud.githubusercontent.com/assets/3952687/22858672/fdecbc94-f117-11e6-83d5-527352a230d9.png)

I figured it out... Hmmm I wish have known this node better. So powerful!

**Comment by enzyme69** [comment]
![screen shot 2017-02-12 at 11 42 12](https://cloud.githubusercontent.com/assets/3952687/22858689/5035240a-f118-11e6-8eac-b0bfdf3566d0.png)

Did you design this @zeffii node? This node has a lot more than it seems! Nicely free forming square. Almost like Tetris. Do you have thread WIP on this node?

**Comment by zeffii** [comment]
Look at the source. No this is lifted from the blender add-on by the same name

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/403   

use this thing please @enzyme69 

![image](https://cloud.githubusercontent.com/assets/619340/22860584/8df54204-f102-11e6-8aab-f108104822ff.png)

**Comment by enzyme69** [comment]
Got it! Thanks!
