### ISSUE TITLE
I cant install Sverchok on Ubuntu 14

### ISSUE THREAD

**Issue by svnserendipity** [nortikin/sverchok#1226]
I want to start using sverchok, but I cant install this addon on my Ubuntu laptop. I have a message: Can not import name "multiarray".

Need to tell you though. Im not a tech savvy. Not a programmer either. Using Ubuntu because I hate Windows hehehe. So help?. Thanx.

**Comment by zeffii** [comment]
Try a prebuilt Blender from buildbot.blender.org

**Comment by svnserendipity** [comment]
@zeffii hmmm. the url is not active anymore :(

**Comment by zeffii** [comment]
it might have been temporarily down https://builder.blender.org/download/

**Comment by ly29** [comment]
Or download 2.78b from here https://www.blender.org/download/

**Comment by zeffii** [comment]
If this is still a problem get back to us

**Comment by adnanmakda** [comment]
I am unable to install it on blender 2.8 
https://drive.google.com/file/d/1pwmwHL0mNhDyZ4Z4XyHY6mkSJFyO96YR/view?usp=sharing

**Comment by zeffii** [comment]
@adnanmakda   https://github.com/nortikin/sverchok/issues/2326  

sverchok-master  does not work with Blender 2.8  , you need to download the alternative version linked in issue 2326
