### ISSUE TITLE
Staggered Grid Ala HoneyComb

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1229]
Does Sverchok has this hexagonal grid pattern already somewhere? I always find this need every now and then.

![screen shot 2017-02-13 at 11 12 53](https://cloud.githubusercontent.com/assets/3952687/22867500/75554ef2-f1dd-11e6-8d2e-d33edc1582c0.png)

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/blob/master/docs/nodes/generator/bricks.rst

**Comment by nortikin** [comment]
http://nikitron.cc.ua/sverch/html/nodes/generator/bricks.html

**Comment by nortikin** [comment]
https://github.com/portnov/sverchok/issues/19

**Comment by enzyme69** [comment]
@nortikin @portnov yes the Brick is the suspect, however, if you look closely the HoneyComb is made, but the grid has extra vertices if I just want that stagger points...

**Comment by nortikin** [comment]
a!
ok, maybe centers of polygons.

**Comment by nortikin** [comment]
https://gist.github.com/baaeb8138c4b12755d9ba6f4c7c6883f

**Comment by enzyme69** [comment]
I thought about that... thanks @nortikin !
