### ISSUE TITLE
monad not work in reopened file

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#1230]
![po8hc1tvw34](https://cloud.githubusercontent.com/assets/5783432/22887837/97b69276-f214-11e6-9f74-dcd13ad78538.jpg)

**Comment by zeffii** [comment]
can you zip the file and paste here?

**Comment by nortikin** [comment]
https://yadi.sk/d/ozlR3IHS3E3yLD
yes, we can

**Comment by zeffii** [comment]
i wonder if we should allow an option to view non SverchCustomTree node tree (ie Monads) in the list of Tree layouts...   @nortikin  does that monad contain other monads ?

**Comment by zeffii** [comment]
```
>>> bpy.data.node_groups['Monad.002'].nodes[:]
[bpy.data...nodes["Group Outputs Exp"], bpy.data...nodes["Vector in.001"], bpy.data...nodes["Math.002"], bpy.data...nodes["Math"], bpy.data...nodes["Math.001"], bpy.data...nodes["Monad.001"], bpy.data...nodes["Group Inputs Exp"]]
```

so yeah, you have Monad.001 inside Monad.002  -- i don't think this is supported / well tested / tested at all.

**Comment by ly29** [comment]
I will take a look

**Comment by ly29** [comment]
If this happens one can try with:
Group -> Update appened/linked

In this case it worked. I will see if fix the underlaying problem as well

**Comment by ly29** [comment]
Actually will just kind of work in that case, hmm. Something goes wrong with properties.

**Comment by ly29** [comment]
So the issue comes down to the tours node that sets some sub types of properties that we usually don't set which somehow triggers this bug.

```python
    torus_R = FloatProperty(
        name="Major Radius",
        min=0.00, max=100.0,
        default=1.0,
        subtype='DISTANCE',
        unit='LENGTH',
        description="Radius from the torus origin to the center of the cross section",
        update=major_minor_radii_changed)

# compare to radius from circle node

    rad_ = FloatProperty(name='Radius', description='Radius',
                         default=1.0,
                         update=updateNode)


```

**Comment by ly29** [comment]
So what happens is that we through deep inspection sets the ```subtype=5``` for example instead of the appropriate string value. The 5 is the index value of enumproperty that.
Added a fix for this now. It seems to be working fine.

**Comment by ly29** [comment]
At least torus can be into a monad and the mentioned file opens fine.

**Comment by ly29** [comment]
Please test and report further errors.

**Comment by ly29** [comment]
And if getting strange monad errors please @ tag me.

**Comment by nortikin** [comment]
ok, thanks much
