### ISSUE TITLE
Rotate and Align Along Path

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1231]
Classic question, always find a need to do this, but never actually do it, or I was avoiding it. What was the right way or the easiest to get instances to point toward path direction?

![screen shot 2017-02-14 at 23 53 15](https://cloud.githubusercontent.com/assets/3952687/22929648/d3e8c794-f310-11e6-92fe-db79b91b945e.png)

**Comment by enzyme69** [comment]
And what is that Tangent and Unit Tangent in Vector Interpolation node...? Any example usage?

![Uploading Screen Shot 2017-02-14 at 23.54.22.png…]()
[align_along_curve_path_direction_001_2017_02_14_12_54.zip](https://github.com/nortikin/sverchok/files/774109/align_along_curve_path_direction_001_2017_02_14_12_54.zip)

https://gist.github.com/1f4afed8f427d8ce7a68f9d0a9a64e2f

**Comment by enzyme69** [comment]
Oh wait... is this it?

![screen shot 2017-02-14 at 23 56 27](https://cloud.githubusercontent.com/assets/3952687/22929724/3b107160-f311-11e6-8da4-361a1309ee55.png)

Tangent works when I set it to Cubic only?

**Comment by enzyme69** [comment]
Not perfect with Twisting, but kind of okey. And not sure how to tweak the twist procedurally.

/Users/jimmygunawan/Desktop/align_along_curve_path_direction_001_2017_02_14_12_59.zip

[align_along_curve_path_direction_001_2017_02_14_12_59.zip](https://github.com/nortikin/sverchok/files/774113/align_along_curve_path_direction_001_2017_02_14_12_59.zip)

**Comment by enzyme69** [comment]
So far...:
![screen shot 2017-02-15 at 00 02 36](https://cloud.githubusercontent.com/assets/3952687/22929907/131846be-f312-11e6-976f-da250f6afc51.png)

**Comment by enzyme69** [comment]
Twisty?
https://gist.github.com/84a578bfd2070e99745ae6b334e94a7f

**Comment by enzyme69** [comment]
Sometimes, when dealing with edges, etc... Skin Mesher seems to solve it somewhat. Such a nice cheat. Probably Skin Mesher OUT and IN into UV can be used....

![screen shot 2017-02-15 at 00 07 45](https://cloud.githubusercontent.com/assets/3952687/22930109/d69a5ec4-f312-11e6-9c57-d7702ed72210.png)

**Comment by enzyme69** [comment]
![screen shot 2017-02-15 at 00 10 08](https://cloud.githubusercontent.com/assets/3952687/22930180/238ee52e-f313-11e6-9301-b75c53a9d010.png)

Ok nope.

**Comment by nortikin** [comment]
polyline node maybe

**Comment by enzyme69** [comment]
@nortikin Polyline actually only outputs 1 Curve at time right? No multiple curves as 1 object? Actually I quite like polyline and CURVE itself has control of Tangent, Closest, and Z Up.

**Comment by enzyme69** [comment]
![screen shot 2017-02-15 at 13 25 18](https://cloud.githubusercontent.com/assets/3952687/22958258/4630a440-f382-11e6-8147-d23862570f27.png)
Actually can be nice if I could then separate each components again with UV Connection.

**Comment by enzyme69** [comment]
@nortikin Polyline is awesome, wishlist will include Radius and Tilt control :) 👍

**Comment by enzyme69** [comment]
[grease_pencil_polyline_001_2017_02_15_02_28.zip](https://github.com/nortikin/sverchok/files/775854/grease_pencil_polyline_001_2017_02_15_02_28.zip)

@nortikin Actual Lofting and Sweeping node is not possible?

**Comment by enzyme69** [comment]
I just found out "Duplicate objects along edge" node. Probably what I need at this moment.

![screen shot 2017-02-15 at 18 59 47](https://cloud.githubusercontent.com/assets/3952687/22965337/329693e8-f3b1-11e6-97b4-db01996d0fff.png)

Very interesting, whoever made the node thanks!

**Comment by zeffii** [comment]
@enzyme69  see https://github.com/nortikin/sverchok/issues/758

> Polyline is awesome, wishlist will include Radius and Tilt control

i think that's a reasonable upgrade suggestion.

> Polyline actually only outputs 1 Curve at time right? No multiple curves as 1 object? Actually I quite like polyline and CURVE itself has control of Tangent

correct the current implementation only makes one spline per object, intentionally. You can't have different matrices per spline, unless you first transform all the vertex sets for each object.

changes I want to make soon to Polyline viewer is
- [ ] radius per vertex
- [ ] twist per vertex
- [ ] multiple splines per object
- [ ] pick Bevel curve shape.

no eta. stuffs busy

**Comment by zeffii** [comment]
(i'm responding because I made that node)

**Comment by enzyme69** [comment]
@zeffii Thanks for the respond in your busy time. That's ok, slowly2 trying to make the best of what nodes available.

The Duplicate Along Edge node is a surprise for me actually that's also a power node.

Polyline is my favourite Curve Out node. RandomNumGen is also. Top 5 nodes is made by Zeffii 🍡

**Comment by enzyme69** [comment]
![screen shot 2017-02-15 at 20 13 00](https://cloud.githubusercontent.com/assets/3952687/22967587/2df2f8d6-f3bb-11e6-8fb2-28705016ccad.png)

Would be nice if Duplicate Along Edge have documentation.

But anyhow, I'll look forward to a way to better drive this twisting thing ala Curve.

**Comment by zeffii** [comment]
RandomNumGen should be migrated to Number category (out of beta)

**Comment by zeffii** [comment]
but @enzyme69 if you like the node so much you should write the docs for it. make a copy of this and update it 
https://github.com/nortikin/sverchok/blob/master/docs/nodes/number/random.rst

**Comment by zeffii** [comment]
and call it `random_num_gen.rst`

**Comment by enzyme69** [comment]
@zeffii Maybe I should do that and follow other style of writing of RST. When I am done I just upload it? That easy? I will be a documentation person then. Will digest in my head a bit.

**Comment by zeffii** [comment]
Take your time , write it as a gist first with a correct filename as suggested above. The gist will show with nice format

**Comment by lostchao11** [comment]
It seem to me Duplicate along edge is trying to preserve edge length, don't know if there is a way to override this?

**Comment by Durman** [comment]
@lostchao11 
https://gist.github.com/eb31a740e2973881d6c56cd874327a5e
![dupli](https://user-images.githubusercontent.com/28003269/29664899-aa918008-88e2-11e7-8539-882f3388daf0.gif)

**Comment by lostchao11** [comment]
@Durman

![example](https://user-images.githubusercontent.com/7042169/29692929-77c1a180-88e7-11e7-8d72-059e40224c92.png)

Here is an example of what i'm talking about. On the first mesh to the left notice how the curve stays parallel to the x and y axis . I don't believe this can be done in sverchok with "Duplicate object along edge" if look to the right mesh you will see twisting occurs any time the mesh starts to bend to persevere edge length. This node cant do everything arrays can be its still pretty awesome though.

**Comment by zeffii** [comment]
you may get reasonable results if you use Sverchok as a "factory" for shapes ( like Bevel Object and Curve/Paths ), it can directly generate Curve Objects. Then turn off the processing of the node tree, and assign Blender's modifiers to the Objects Sverchok produces.

I know it would be useful to be able to do everything in Sverchok, but we've intentionally stayed away from duplicating what Blender is already good at.

**Comment by nortikin** [comment]
in everithing in nodes we trust
