### ISSUE TITLE
Alpha masking(blending) bug?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1233]
I did this test because i want a system to mask values in a similar way as an alpha mask does with a texture, in the json file two approach with nodes and via script: should be the same result but instead output is not. Something wrong in my code? 
![alpha-mask-example](https://cloud.githubusercontent.com/assets/1275858/22944713/e713c1bc-f2f1-11e6-9fd6-8fb357a0d94e.png)

gist file: https://gist.github.com/kalwalt/c96b358211c89e58539da6146b48d94a

alpha masking script:

````python
#alpha masking script

def sv_main(base=[],alpha=[]):

    data = []
    out = []

    in_sockets = [
        ['s', 'base', base],
        ['s', 'alpha', alpha]] 

    out_sockets = [
        ['s','data', data]
    ]
    
    print('alpha values: {0}'.format(alpha))
   
    if alpha and alpha[0]:
      
        for a in alpha[0][0]:
               
            out = [(1.0 - b) * a for b in base[0][0]]
        data.append(out)    
  

    return in_sockets, out_sockets

````
(edited to fit the screen)

base values input: `  [[[0.844421, 0.7579544, 0.420571, 0.25891675]]]`

alpha values input:  `[[[1.0, 0.0, 1.0, 1.0]]]`

output values from script: ` [[0.155578, 0.2420455, 0.5794284, 0.74108324]]`

output values from math formula node (formula=(1-n[0])*x)): 
` [[0.155578, 0.0, 0.5794, 0.7410837]]`

this last should be correct.

**Comment by kalwalt** [comment]
note that switching to float from int in the `List input` node does not change anything....

**Comment by zeffii** [comment]
```python
        for a in alpha[0][0]:
               
            out = [(1.0 - b) * a for b in base[0][0]]
        data.append(out)  
```
how many things are in alpha[0][0] ?
if `for a in alpha[0][0]` iterates over more than 1 item, then   the value in `out` will be overwritten each time... and only the last `out` will be appended to `data`.

**Comment by kalwalt** [comment]
@zeffii This is the equivalent solution, that works as the `formula node`, i found :

````python

if alpha and alpha[0]:
        
        out = [(1.0-b)*a for a, b in zip(alpha[0][0], base[0][0])]
       
        data.append(out)

````

stackoverflow inspirational link: http://stackoverflow.com/questions/18713321/element-wise-addition-of-2-lists

**Comment by kalwalt** [comment]
I think also that func `(1.0-b)*a` is not correct for aplha masking/blending...

**Comment by zeffii** [comment]
i'm not sure what you're trying to do. forget about sverchok for a moment. just write this in your python ide / console / Blender TextEditor ..and see if you can figure it out.
```python
base = [0.844421, 0.7579544, 0.420571, 0.25891675]
alpha = [1.0, 0.0, 1.0, 1.0]


out = [(1.0 - b) * a for a, b in zip(base, alpha)]
print(out)

# >>> [0.0, 0.7579544, 0.0, 0.0]
```

**Comment by zeffii** [comment]
i'm not sure what you're trying to do. forget about sverchok for a moment. just write this in your python ide / console / Blender TextEditor ..and see if you can figure it out.
```python
base = [0.844421, 0.7579544, 0.420571, 0.25891675]
alpha = [1.0, 0.0, 1.0, 1.0]


out = [(1.0 - b) * a for b, a in zip(base, alpha)]
print(out)

# >>> [0.15557900000000002, 0.0, 0.579429, 0.74108325]
```

**Comment by kalwalt** [comment]
yes in the console is simpler, i always use it. basically i want this:

````python
        #out[alpha] = src_a+dst_a*(1-src_a) this is correct!
        out = [(1.0-a)*b + a for a, b in zip(alpha[0][0], base[0][0])]
````
and that is what i search for.
from stackoverflow example with numpy:
http://stackoverflow.com/questions/3374878/with-the-python-imaging-library-pil-how-does-one-compose-an-image-with-an-alp
and from wikipedia
https://en.wikipedia.org/wiki/Alpha_compositing
I would use them in combination of noise/fractal nodes to get more interesting result.

**Comment by kalwalt** [comment]
an example of "noise alpha masking modulation" to create a stone like mesh:
![screen -example-noise-modulation](https://cloud.githubusercontent.com/assets/1275858/23022648/3a4df012-f452-11e6-98bb-8d14c7cc0c22.png)

**Comment by kalwalt** [comment]
the same mesh in 3dcoat:
![image](https://cloud.githubusercontent.com/assets/1275858/23023074/1fd38d62-f454-11e6-80a1-88c2940b0d63.png)

**Comment by zeffii** [comment]
have you solved this, can it be closed?

**Comment by kalwalt** [comment]
@zeffii yes thank's!
