### ISSUE TITLE
Can we nodify "Simplify Curve" Add On

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1234]
That is my question. I think if Sverchok can somewhat use Simplify Curve add-on script to generate points, we can have more control on Grease Pencil sampling.

I will now read the script. Maybe Script Node can do something about this matter.

Thinking....

**Comment by zeffii** [comment]
i'm more likely to add a GreasePencil Input node, with built in simplify/interpolate options. if the Simplify Curve addon is included in official Blender release we can even just import directly from it... if it has useful functions that are sufficiently modular .

**Comment by enzyme69** [comment]
Re-studying this again:
https://github.com/nortikin/sverchok/issues/1005

![screen shot 2017-02-15 at 20 27 46](https://cloud.githubusercontent.com/assets/3952687/22968123/4c048b44-f3bd-11e6-9b0d-3ccd3cd5f727.png)


"""
in splineVerts       v
out points      v
"""

import curve_simplify as cs

points = [cs.simplypoly(splineVerts)]

**Comment by enzyme69** [comment]
![screen shot 2017-02-15 at 20 30 03](https://cloud.githubusercontent.com/assets/3952687/22968186/965664e2-f3bd-11e6-80b3-a944658793e6.png)
![screen shot 2017-02-15 at 20 30 00](https://cloud.githubusercontent.com/assets/3952687/22968187/969ff9d6-f3bd-11e6-8799-90e4c84c9a1e.png)

**Comment by enzyme69** [comment]
@zeffii Direct Grease Pencil data block will be nice :) So far I am using Object ID but Grease Pencil converted to Curve is ok too. More modular. Grease Pencil itself seems to be evolving slowly.

**Comment by zeffii** [comment]
look at your console with that sn loaded
```
TypeError: simplypoly() missing 1 required positional argument: 'options'

```

**Comment by zeffii** [comment]
read the first 10 lines of `def simplypoly(splineVerts, options):`

**Comment by enzyme69** [comment]
Reading now, I probably need to find out what type of curves we are dealing with. But from what I assume, Sverchok already done conversion in Objects In.

**Comment by zeffii** [comment]
yep. essentially the Interpolation node already does what 'simplify' does. except it doesn't output a Curve object.

**Comment by enzyme69** [comment]
options = [
                self.mode,       #0
                self.output,     #1
                self.k_thresh,   #2
                self.pointsNr,   #3
                self.error,      #4
                self.degreeOut,  #5
                self.dis_error,  #6
                self.keepShort]  #7

**Comment by enzyme69** [comment]
Vector Interpolation is nice and works for most of cases.

What interesting about this Simplify Curve is the ability to "smooth" the interpolation and getting rid points that are too close together or too spikey, and end result Simplified Curve seems useful.

**Comment by zeffii** [comment]
if you really want to use `simplycurve` then you must figure out the types of those params and sane values. Some of the options i'm sure can be passed in as Ints/ Floats.

> What interesting about this Simplify Curve is the ability to "smooth" the interpolation and getting rid points that are too close together or too spikey, and end result Simplified Curve seems useful.

if that's your experience, then it's worth doing a side by side test with Interpolation and such a SN :)

**Comment by enzyme69** [comment]
I will tweak until I gave up. Thanks Zeffii.

**Comment by enzyme69** [comment]
WIP but getting somewhere I think.

```
"""
in splineVerts       v
in mode       s d=1    n=2 
in output  s d=1  n=2 
in k_thresh  s d=1.0  n=2
in pointsNr   s d=5  n=2
in error       s d=0.1    n=2 
in degreeOut  s d=0.5  n=2 
in dis_error  s d=0.3  n=2
in keepShort   s d=2.0  n=2
out points      v
"""

options = [
        mode,       #0
        output,     #1
        k_thresh,   #2
        pointsNr,   #3
        error,      #4
        degreeOut,  #5
        dis_error,  #6
        keepShort]  #7

from curve_simplify import simplypoly

points = [simplypoly(splineVerts, [1,2,3,4,5,6,7,8])]
```

**Comment by zeffii** [comment]
not all items of `options` are used , but they still need to be passed
```
"""
in splineVerts v
out points v
"""

print(splineVerts[0])

import curve_simplify as cs

options = [
    None, # self.mode,       #0
    None, # self.output,     #1
    2.2,  # self.k_thresh,   #2
    6,    # self.pointsNr,   #3
    None, # self.error,      #4
    None, # self.degreeOut,  #5
    0.8,  # self.dis_error,  #6
    None  # self.keepShort   #7
]

points = [cs.simplypoly(splineVerts[0], options)]
print(points)
```

( no this doesn't work yet ... but this is more correct than what you are trying )

**Comment by zeffii** [comment]
so what you should do .. is edit `simplypoly` by adding a print statement to the top (inside simplypoly) to `print(options)` , and see what those sane values should be.

**Comment by zeffii** [comment]
looks like 2d points...

so looking at `class CURVE_OT_simplify(bpy.types.Operator):`  suggests it calls `main` first and not simplypoly, but main in turn can call simplypoly.   but also needs `newPoints = vertsToPoints(newVerts, splineVerts, splineType)`

**Comment by zeffii** [comment]
and points need to be converted to Vectors first.

**Comment by zeffii** [comment]
a bit closer..
```python
"""
in splineVerts v
out points v
"""

from sverchok.data_structure import Vector_generate as as_vectors
# from sverchok.data_structure import Vector_degenerate as from_vectors
import curve_simplify as cs

options = [
    'DISTANCE', # 0  self.mode
    None,       # 1  self.output
    0.01,       # 2  self.k_thresh
    42,         # 3  self.pointsNr
    0.01,       # 4  self.error
    None,       # 5  self.degreeOut
    0,          # 6  self.dis_error
    None        # 7  self.keepShort
]

# simplify spline according to mode
mode = options[0]
if mode == 'DISTANCE':
    newVerts = cs.simplify_RDP(splineVerts, options)

if mode == 'CURVATURE':
    newVerts = cs.simplypoly(splineVerts, options)
 

# convert indices into vectors3D
newPoints = cs.vertsToPoints(newVerts, splineVerts, splineType='DUMMY')

# create new spline
points = [newPoints]
print(points)

``` 

but no more time.

**Comment by zeffii** [comment]
this kind of works
```python
"""
in splineVerts v d=[[]] n=0
in num_points s d=5 n=2
in kthresh s d=0.3 n=2
in errordist s d=0.3 n=2
in diserror s d=0.1 n=2
out points v
"""

from sverchok.data_structure import Vector_generate as as_vectors
import curve_simplify as cs

options = [
    'DISTANCE', # 0  self.mode
    'INPUT',    # 1  self.output
    kthresh,    # 2  self.k_thresh
    num_points, # 3  self.pointsNr
    errordist,  # 4  self.error
    None,       # 5  self.degreeOut
    diserror,          # 6  self.dis_error
    False       # 7  self.keepShort
]

def split_n_by_x(stride, chop_length, collection):
    return [collection[i:i+3] for i in range(0, len(collection), 4)]

points = []
for vlist_vecs in as_vectors(splineVerts):

    # mode == 'DISTANCE':
    newVerts = cs.simplify_RDP(vlist_vecs, options)

    # convert indices into vectors3D
    points.append(split_n_by_x(4, 3, cs.vertsToPoints(newVerts, vlist_vecs, splineType='DUMMY')))

```

**Comment by enzyme69** [comment]
I am ok even with "kind of working".

![screen shot 2017-02-16 at 12 08 15](https://cloud.githubusercontent.com/assets/3952687/23002745/a15105e0-f440-11e6-924d-cd48d857a331.png)

I will study this progression code.

**Comment by enzyme69** [comment]
![screen shot 2017-02-16 at 12 11 18](https://cloud.githubusercontent.com/assets/3952687/23002839/0a1bb610-f441-11e6-9345-c1eb4f1f650b.png)

**Comment by zeffii** [comment]
Yesterday I also made a lightweight point filter, this sn's code can be added to make a small utility module that canbe used by a node as extra processing step (gp in).. or straight up as a node

**Comment by enzyme69** [comment]
Probably sufficient for now, but I might come back and revisit this for further study.
