### ISSUE TITLE
Bug report via BA / Bad gist error message.

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1236]
I cannot reproduce this on 2.78b on windows, anyone else?

> Just downloaded and imported this JSON:
> https://gist.github.com/enzyme69/dac4de8f4297e4ebb974d65896c24470
> from this video:
> 
> https://www.youtube.com/watch?v=UWmPvyvC9Oc
> BLENDERSUSHI / SV Edge To Arc (LIVENODING307)
> into the latest version of Blender: 2.78b
> 
> It loads just fine into 2.78a
> Two different laptops, same result.
> Blender crashes

https://blenderartists.org/forum/showthread.php?272679-Addon-WIP-Sverchok-parametric-nodes-for-architects&p=3153647#post3153647

**Comment by ly29** [comment]
Now it gives a 404, closing for now...

**Comment by ly29** [comment]
Ok me being stupid, url working now, can't confirm on mac either.

404 should give a nice looking error however.

**Comment by ly29** [comment]
![skarmavbild 2017-02-16 kl 07 30 33](https://cloud.githubusercontent.com/assets/6241382/23010081/df61a15e-f419-11e6-8eea-9d1c348b1e44.png)

404 error on bad gist id. To trigger remove one character from gist id. 
@zeffii Mind a try except -> bad gist report?

```python
        try:
             nodes_json = self.obtain_json(self.gist_id.strip())
       except:
            # bad gist
            self.report({'Erro'}, "Bad GIST id or no internet connection")
```
https://github.com/nortikin/sverchok/blob/master/utils/sv_IO_panel_tools.py

**Comment by zeffii** [comment]
Yeah ill add a custom exception, later today

**Comment by zeffii** [comment]
Time for user to update to b or c or use buildbot, its also possible that the versions of sverchok are different shas etc. I haven't updated blender for 2 weeks.

**Comment by ly29** [comment]
He seems to say that 2.78a works but 2.78b crashes. C should be out today or soonish

**Comment by ly29** [comment]
I will let you deal with the error check, not so high priority

**Comment by zeffii** [comment]
Oh ...would be neat to have a convenient way to receive bug reports from users. But also not getting bug reports instantly is also important for our sanity.

**Comment by ly29** [comment]
Yes, and also keeping track of all auto uploaded gists (optional of course)

I guess we need a small server somewhere...

**Comment by zeffii** [comment]
Ahhh, we can use the data storage to storage gistid locally and include the layout name separated by a comma and date - that makes sense..I bet we wish this was stored all along

**Comment by ly29** [comment]
a good thing about a bug report would be versions of everything

**Comment by zeffii** [comment]
a warning for the 404
https://github.com/nortikin/sverchok/pull/1237

we could make a default 404 gist/layout  that it can try if the user pasted url is a 404. it could consist out of a frame with a description of what's going on .. and some solutions. ..maybe even a dedicated node with a massive ' Launch Issue Tracker ' button .

**Comment by ly29** [comment]
Can anybody reproduce the crashes with importing the JSON?

@nortikin @enzyme69 perhaps?

**Comment by zeffii** [comment]
i'll try B today

**Comment by zeffii** [comment]
well.. the json doesn't crash blender but it does output this to console
```python
Traceback (most recent call last):
  File "sverchok\utils\sv_IO_panel_tools.py", line 574, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "sverchok\utils\sv_IO_panel_tools.py", line 565, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "Objects in mk3" not found'

Traceback (most recent call last):
  File "sverchok\utils\sv_IO_panel_tools.py", line 574, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "sverchok\utils\sv_IO_panel_tools.py", line 565, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "Objects in mk3" not found'

Traceback (most recent call last):
  File "sverchok\utils\sv_IO_panel_tools.py", line 574, in make_links
    ng.links.new(*resolve_socket(*link, name_dict=name_remap))
  File "sverchok\utils\sv_IO_panel_tools.py", line 565, in resolve_socket
    return (ng.nodes[f_node].outputs[from_socket],
KeyError: 'bpy_prop_collection[key]: key "Objects in mk3" not found'

failed total 3
[['Objects in mk3', 'Vertices', 'Matrix Apply', 'Vectors'], ['Objects in mk3', 'Matrixes', 'Matrix Apply', 'Matrixes'], ['Objects in mk3', 'Edges', 'Polygon Boom', 'edg_pol']]
  File "sverchok\core\update_system.py", line 322, in do_update_general
    node.process()
  File "sverchok\nodes\transforms\apply.py", line 40, in process
    vecs_ = self.inputs['Vectors'].sv_get(deepcopy=False)
  File "sverchok\node_tree.py", line 178, in sv_get
    raise SvNoDataError
Node Matrix Apply had exception
```

**Comment by ly29** [comment]
The node is named ```icosphere``` hmm

**Comment by ly29** [comment]
```python
"Objects in mk3": {
      "bl_idname": "SvObjectsNodeMK3",
      "color": [
        0.904932975769043,
        1.0,
        0.883421003818512
      ],
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -1323.907470703125,
        35.240806579589844
      ],
      "object_names": [
        "Icosphere"
      ],
      "params": {
        "modifiers": 1
      },
      "width": 140.0
    },
```

**Comment by ly29** [comment]
Here the bug is, short variable names come back to bit you


```python
def add_node_to_tree(nodes, n, nodes_to_import, name_remap, create_texts):
# instead of n node_name
# or use obj_name below
    if bl_idname == 'SvObjectsNodeMK3':
        print(node_ref)
        obj_names = node_ref.get('object_names', [])
        for n in obj_names:
            node.object_names.add().name = n

    gather_remapped_names(node, n, name_remap)
```

**Comment by zeffii** [comment]
ohh...lol

**Comment by zeffii** [comment]
good catch. if you want i'll push a fix

**Comment by ly29** [comment]
go for it, I am making np torus faces, fun stuff.

**Comment by zeffii** [comment]
make the torus vertices in 5 (long) lines of np . or less ... i get close.. but it wrecks my head (literally )

**Comment by ly29** [comment]
The below might almost be [brainfuck ](https://en.wikipedia.org/wiki/Brainfuck) for all the readability it has
```python
def torus_faces(x, y):
    faces = np.empty((x * y, 4), dtype=np.uint32)
    tmp = np.arange(0, x * y)
    faces[:, 0] = tmp
    faces[:, 1] = np.roll(tmp, -y)
    tmp.shape = (x, y)
    tmp[:, y - 1] -= y
    tmp.shape = -1
    faces[:3] = tmp
    faces[:2] = np.roll(tmp, -y)
    faces.shape = -1
    l_total = np.empty(x * y, dtype=np.uint32)
    l_total[:] = 4
    l_start = np.arange(0, (x * y) * 4, 4, dtype=np.uint32)
    return SvPolygon(l_start, l_total, faces)
```

**Comment by zeffii** [comment]
yeah, that's a bit mental. :D

**Comment by zeffii** [comment]
but i must say, it's terseness has a beauty of its own.

**Comment by ly29** [comment]
I does, updated, I forgot to add +1 to tmp for the second part.

**Comment by ly29** [comment]
Anyway enough OT np for now.

**Comment by zeffii** [comment]
oh yeah, btw... 2.78b will indeed crash to the desktop..

**Comment by zeffii** [comment]
and has nothing to do with the other error/bug :)

**Comment by zeffii** [comment]
let's see if editing the json makes a difference

**Comment by zeffii** [comment]
well... i got my hopes it.. it crashed once. but after restarting Blender 2.78b repeatedly and doing the same thing I don't have the same problem.   The one time it did crash was when i moved panned nodeview immediately after importing..

**Comment by ly29** [comment]
Well, it is tricky if we can't reproduce.

**Comment by enzyme69** [comment]
Never crash only error, I experience that few times if I copy paste with
HTTP address instead of just the ID.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by ly29** [comment]
Thanks @enzyme69

**Comment by zeffii** [comment]
we can close until reproduced.
