### ISSUE TITLE
Is there infrastructure in place to integrate custom icons ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1240]
I was going to start working on custom icon integration and was wondering if anyone has started working on this yet. 

Here are some useful links I found related to blender icons:

http://blender.stackexchange.com/questions/32335/how-to-implement-custom-icons-for-my-script-addon

https://blenderartists.org/forum/showthread.php?201093-Icon-Enumeration-Script-(Blender-2-5)

https://wiki.blender.org/index.php/Dev:2.5/Doc/How_to/Add_an_icon

**Comment by ly29** [comment]
I know there was some work done with this but for me all new infrastructure work goes towards redux. 

That said it is a good idea

I imagine a file called icons in ui doing the register and a subdir called icons.

**Comment by zeffii** [comment]
I think bl_icon  on nodes must be an existing name, we could implement bl_icon2 for the node view's ctrl+space menu.

Custom icons do not.have any convenient infrastructure, but we could add one.

Not certain if custom icons will show up in an enum

**Comment by zeffii** [comment]
`mesh_tiny_cad` (included in main Blender distribution) uses custom icons for menu items
https://github.com/zeffii/mesh_tiny_cad

**Comment by DolphinDream** [comment]
Yeah. I pretty much did what the tiny_cad did. I placed the icons in the ui/icons folder and created a utils/sv_custom_icons.py script the does the loading, unloading and accessing of the custom icons by name. For the name I chose to have the file name be converted into a icon ID, and have the icon names follow specific pattern like: sv_torus_knot.png .. which will be converted during loading of the icons into a SV_TORUS_KNOT. The classes will then use icon_value=customIcon(“SV_TORUS_KNOT”). 

Questions:
1. I’m not sure how bl_icon2 would work. Further hints?

2. I don’t know for now how to set the icons for the nodes themselves, which is typically set via bl_icon inside the node file (I know how to add the icon to a menu item that is added directly to the search menu (e.g. in nodeview_space_menu.py) however the individual items added to the search main categories are not added explicitly in this file (any hints to where all the nodes are added to the menu?)

So far I was able to set the icons in the search_menu main category, in the props for the nodes (e.g. node layout props, property panel props etc, see screen capture). I haven’t tried yet to add it to enum lists yet.

3. How do i get the sv_custom_icons.py register/unregister to be called automatically to load/remove the icons. Currently i call loadCustomIcons / removeCustomIcons from the register/unregister of the search_meny register/unregister functions. when you add a py file to the addon do you have to do anything to have its register/unregister methods invoked ?

![customicons-example1](https://cloud.githubusercontent.com/assets/2083719/23066379/49c89966-f4e8-11e6-8694-6321470a4b05.jpg)

**Comment by zeffii** [comment]
because bl_icon must be in the known set of icon names, you'd have to define a string ( no need for StringProperty) 

```
class SvObjectsNodeMK3(bpy.types.Node, SverchCustomTreeNode):
    ''' Objects Input slot MK3'''
    bl_idname = 'SvObjectsNodeMK3'
    bl_label = 'Objects in mk3'
    bl_icon = 'OUTLINER_OB_EMPTY'
    bl_icon2 = 'MY_CUSTOM_ICON'
```
then in the https://github.com/nortikin/sverchok/blob/master/ui/nodeview_space_menu.py
must be edited. but this is a little cryptic after much refactoring

i'd prefer to rewrite this myself: https://github.com/nortikin/sverchok/blob/master/ui/nodeview_space_menu.py#L44-L81

I don't think we have control over the Search ui, regarding custom icons.

**Comment by ly29** [comment]
I would call the ```icons``` and place it ```ui```

For registering see ```__init__.py``` in the root.

**Comment by zeffii** [comment]
```python
def layout_draw_categories(layout, node_details):
    show_icons = menu_prefs.get('show_icons')

    def cicon(name):
        return icon_collection["main"][name].icon_id

    def icon(display_icon):
        '''returns empty dict if show_icons is False, else the icon passed'''
        return {'icon': display_icon for i in [1] if show_icons and display_icon}

    def get_icon(node_ref):
        # some nodes don't declare a bl_icon, but most do so try/except is fine.
        try:
            _icon = getattr(node_ref, 'bl_icon2') or getattr(node_ref, 'bl_icon')
            if _icon == 'OUTLINER_OB_EMPTY':
                _icon = None
        except:
            _icon = None
        return _icon

    add_n_grab = 'node.add_node'
    for node_info in node_details:

        if not node_info:
            print(repr(node_info), 'is incomplete, or unparsable')
            continue

        bl_idname = node_info[0]
        node_ref = getattr(bpy.types, bl_idname)

        display_icon = get_icon(node_ref)
        if hasattr(node_ref, "bl_label"):

            if getattr(node_ref, 'bl_icon2'):
                layout_params = dict(text=node_ref.bl_label, icon_value=cicon(display_icon))
            else:
                layout_params = dict(text=node_ref.bl_label, **icon(display_icon))

        elif bl_idname == 'NodeReroute':
            layout_params = dict(text='Reroute')
        else:
            continue

        node_op = layout.operator(add_n_grab, **layout_params)
        node_op.type = bl_idname
        node_op.use_transform = True

```

**Comment by zeffii** [comment]
maybe
```python
            if getattr(node_ref, 'bl_icon2'):
                icon_dict = dict(icon_value=cicon(display_icon))
            else:
                icon_dict = icon(display_icon))
            layout_params = dict(text=node_ref.bl_label, **icon_dict)    
```

**Comment by zeffii** [comment]
```python
def layout_draw_categories(layout, node_details):
    show_icons = menu_prefs.get('show_icons')

    def cicon(name):
        return icon_collection["main"][name].icon_id

    def icon(display_icon):
        '''returns empty dict if show_icons is False, else the icon passed'''
        return {'icon': display_icon for i in [1] if show_icons and display_icon}

    def get_icon(node_ref):
        # some nodes don't declare a bl_icon, but most do so try/except is fine.
        try:
            _icon = getattr(node_ref, 'bl_icon2') or getattr(node_ref, 'bl_icon')
            if _icon == 'OUTLINER_OB_EMPTY':
                _icon = None
        except:
            _icon = None
        return _icon

    add_n_grab = 'node.add_node'
    for node_info in node_details:

        if not node_info:
            print(repr(node_info), 'is incomplete, or unparsable')
            continue

        bl_idname = node_info[0]
        node_ref = getattr(bpy.types, bl_idname)

        display_icon = get_icon(node_ref)
        if hasattr(node_ref, "bl_label"):

            if getattr(node_ref, 'bl_icon2'):
                icon_dict = dict(icon_value=cicon(display_icon)) if show_icons else {}
            else:
                icon_dict = icon(display_icon))
            layout_params = dict(text=node_ref.bl_label, **icon_dict)    

        elif bl_idname == 'NodeReroute':
            layout_params = dict(text='Reroute')
        else:
            continue

        node_op = layout.operator(add_n_grab, **layout_params)
        node_op.type = bl_idname
        node_op.use_transform = True
```

**Comment by DolphinDream** [comment]
Neat. Thx @zeffii 
I'll push some changes I made (including your examples) to a customIcons branch soon.
Here are some icons I designed already and added for testing to the search menu.

![customicons-example2](https://cloud.githubusercontent.com/assets/2083719/23080384/838d0962-f51e-11e6-823e-5b457a85076e.png)

**Comment by zeffii** [comment]
or,,, untested
```python
def layout_draw_categories(layout, node_details):
    show_icons = menu_prefs.get('show_icons')

    def cicon(name):
        return icon_collection["main"][name].icon_id

    def icon(node_ref):
        '''returns empty dict if show_icons is False, else the icon passed'''
        if not show_icons:
            return {}
        else:
            display_icon = get_icon(node_ref)
            if getattr(node_ref, 'bl_icon2'):
                return {'icon_value': cicon(display_icon))}  # assume it's found. else its ok to crash horribly.
            else:
                return {'icon': display_icon} if display_icon else {}

    def get_icon(node_ref):
        # some nodes don't declare a bl_icon, but most do so try/except is fine.
        try:
            _icon = getattr(node_ref, 'bl_icon2') or getattr(node_ref, 'bl_icon')
            if _icon == 'OUTLINER_OB_EMPTY':
                _icon = None
        except:
            _icon = None
        return _icon

    add_n_grab = 'node.add_node'
    for node_info in node_details:

        if not node_info:
            print(repr(node_info), 'is incomplete, or unparsable')
            continue

        bl_idname = node_info[0]
        node_ref = getattr(bpy.types, bl_idname)
        
        if hasattr(node_ref, "bl_label"):
            layout_params = dict(text=node_ref.bl_label, **icon(node_ref))    
        elif bl_idname == 'NodeReroute':
            layout_params = dict(text='Reroute')
        else:
            continue

        node_op = layout.operator(add_n_grab, **layout_params)
        node_op.type = bl_idname
        node_op.use_transform = True
```

**Comment by zeffii** [comment]
more untested
```python
def layout_draw_categories(layout, node_details):
    show_icons = menu_prefs.get('show_icons')

    def get_icon(node_ref):
        # some nodes don't declare a bl_icon, but most do so try/except is fine.
        try:
            _icon = getattr(node_ref, 'bl_icon2') or getattr(node_ref, 'bl_icon')
            if _icon == 'OUTLINER_OB_EMPTY':
                _icon = None
        except:
            _icon = None
        return _icon

    def icon(node_ref):
        '''returns empty dict if show_icons is False, else the icon passed'''
        if not show_icons:
            return {}
        else:
            display_icon = get_icon(node_ref)
            if getattr(node_ref, 'bl_icon2'):
                icon_ref = icon_collection["main"].get(name)
                if not icon_ref:
                    return {}
                return {'icon_value': icon_ref.icon_id} 
            else:
                return {'icon': display_icon} if display_icon else {}

    add_n_grab = 'node.add_node'
    for node_info in node_details:

        if not node_info:
            print(repr(node_info), 'is incomplete, or unparsable')
            continue

        bl_idname = node_info[0]
        node_ref = getattr(bpy.types, bl_idname)
        
        if hasattr(node_ref, "bl_label"):
            layout_params = dict(text=node_ref.bl_label, **icon(node_ref))    
        elif bl_idname == 'NodeReroute':
            layout_params = dict(text='Reroute')
        else:
            continue

        node_op = layout.operator(add_n_grab, **layout_params)
        node_op.type = bl_idname
        node_op.use_transform = True
```

**Comment by zeffii** [comment]
with UI code we need to be a bit more defensive, it gets called way more than you might realize.

**Comment by DolphinDream** [comment]
I added my code with some of your code suggestions (@zeffii) to customIcons developing branch (pull requested). I added some testing icons to ui/icons as well, which are to be updated with better ones as we continue developing.

**Comment by zeffii** [comment]
to get consistent icons we need
-  a style guide
-  a `icon_demo.blend` that renders 1 or more icons, 
-  scripts needed to automate the render process (include this in the icon_demo.blend)

for mesh_tiny_cad i used a single render to render all icons, and later sliced the output.

https://github.com/zeffii/mesh_tiny_cad/issues/43 
  - blend   http://blender.stackexchange.com/questions/31180/material-shading-options-in-3d-viewport-limited-for-curve-objects
 - script    https://github.com/zeffii/mesh_tiny_cad/issues/43#issuecomment-223912593

**Comment by zeffii** [comment]
closing here as the main question is answered, and further discussion has been taking place in the PR : https://github.com/nortikin/sverchok/pull/1242

reopen if you don't agree

**Comment by DolphinDream** [comment]
Do you guys use IRC? I was thinking a #sverchok IRC channel could be handy rather than starting new issues to ask simple questions. Also adding unrelated questions like this one to an already existing issue or pull request thread is a bit overkill I think.

**Comment by ly29** [comment]
No really using irc, the good thing about issues are that they are all here and searchable. Don't worry about to small issues, there is plenty of noise already.

**Comment by zeffii** [comment]
we registered Freenode #sverchok a while back - it didn't get much traction.. and
