### ISSUE TITLE
Monad/Group is missing in ctrl+space menu...

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1249]
![monad1](https://cloud.githubusercontent.com/assets/6241382/23094846/97ef0990-f600-11e6-8aa6-e6d076b2f713.PNG)

I can understand now the desire to see a listing of monads, for me this wasn't an issue since I used shift-a menu.

**Comment by DolphinDream** [comment]
Is there a good reason why there is a SHIFT+A and a CTRL+SPACE to trigger different menus for sv nodes? (one with icons, one with not ;)

**Comment by ly29** [comment]
The whole menu in ctrl-space could be drawn with functions like below.

```python
def draw_node_ops(self,layout, context):
    make_monad = "node.sv_monad_from_selected"
    ungroup_monad = "node.sv_monad_expand"
    update_import = "node.sv_monad_class_update"
    layout.operator(make_monad, text='make group (+relink)', icon='RNA')
    layout.operator(make_monad, text='make group', icon='RNA').use_relinking = False
    layout.operator(ungroup_monad, text='ungroup', icon='RNA')
    layout.operator(update_import, text='update appended/linked', icon='RNA')
    layout.separator()
```
https://github.com/nortikin/sverchok/blob/master/menu.py#L144-L153

**Comment by ly29** [comment]
Not really...

**Comment by zeffii** [comment]
In addition to what @ly29 mentions `Ctrl+Space` menu was added to allow customization and further sub-categorising. Seen as the Shift+A menu is almost entirely auto generated and at the time we had fewer node directories.

**Comment by zeffii** [comment]
then

nodeview_space_menu.py
```
from sverhok.menu import draw draw_node_ops

...

draw_group_menu = lambda self, context: draw_node_ops(self, layout, context)

def register():
     ...
     bpy.types.NODEVIEW_MT_Dynamic_Menu.append(draw_group_menu)

# unregister / .remove

```
i think... @ly29

**Comment by zeffii** [comment]
or...
```
from sverhok.menu import draw_node_ops

...

class NODEVIEW_MT_AddGroupss(bpy.types.Menu):
    bl_label = "Groups"

    def draw(self, context):
        layout = self.layout
        draw_node_ops(self, layout, context)
````

**Comment by zeffii** [comment]
or just add 
```
layout.menu("NODE_PT_category_SVERCHOK_GROUPS", icon="RNA"))
```

**Comment by zeffii** [comment]
or just add 
```
layout.menu("NODE_MT_category_SVERCHOK_GROUPS", icon="RNA")
```
to `class NODEVIEW_MT_Dynamic_Menu(bpy.types.Menu)`

![image](https://cloud.githubusercontent.com/assets/619340/23096350/02ef0bd6-f61b-11e6-9b51-43dba6eb3f58.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/6cb6200090ab4c9529bf1dd917e99bc05ad38764

**Comment by ly29** [comment]
Makes sense. 
:)

**Comment by ly29** [comment]
To expand a bit further, the shift-a infrastructure also informs the t-panel, which I never use...

The submenus could use icons for the shift-a menu but using custom draw but the main can't with some overriding...


![menu_shift_a](https://cloud.githubusercontent.com/assets/6241382/23101251/817fc6c4-f68f-11e6-82ad-312f8d5be399.PNG)

**Comment by ly29** [comment]
It would be nice with icons in default menu...

**Comment by ly29** [comment]
@zeffii @nortikin 
Any thoughts about this?

**Comment by zeffii** [comment]
not really, i'd much rather see shift+A use the spacebar menu.

**Comment by nortikin** [comment]
shift+A is ok as for me. Users mostly use shift + A as i see from conversation experience. Maybe to replace default shift+A to that is in ctrl+space?

**Comment by ly29** [comment]
That is a better option anyway
