### ISSUE TITLE
Exception when reloading add-ons (F8) 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1250]
Any reason why this happens ? (current master: SHA: 6cb6200090ab)
With some blend files when I reload F8 and render I get blender to crash. It’s possible that the crash has something to do with the freestyle (since it doesn’t crash when it’s off), nevertheless I though the exception below should be better handled.

```python
UnRegister Custom Nodes addon
Unregistered Animation Nodes
addon_utils.disable: space_view3d_align_tools not disabled.
Exception in module unregister(): '.../sverchok/__init__.py'
Traceback (most recent call last):
  File ".../modules/addon_utils.py", line 397, in disable
    mod.unregister()
  File ".../sverchok/__init__.py", line 178, in unregister
    m.unregister()
  File ".../sverchok/ui/nodeview_keymaps.py", line 60, in unregister
    remove_keymap()
  File ".../sverchok/ui/nodeview_keymaps.py", line 52, in remove_keymap
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem 
‘NODE_OT_sv_monad_from_selected' cannot be removed from 'Node Editor'
```

**Comment by zeffii** [comment]
ouch.. it might be that one of those other add-ons (or freestyle) already removed the Node Editor map,/ or something higher up before Sverchok's unregister gets called. If you want to help out you might stick some debug info in (different branch)

https://github.com/nortikin/sverchok/blob/master/ui/nodeview_keymaps.py#L50-L53

**Comment by zeffii** [comment]
i'd want to know what this (or more elaborate says)
```python
def remove_keymap():
    for km, kmi in nodeview_keymaps:
        try:
            km.keymap_items.remove(kmi)
        except Exception as e:
            print(repr(e))
            print('current keymap items', km.keymap_items)
    nodeview_keymaps.clear()
```

**Comment by zeffii** [comment]
Animation node has this line in its unregister

```python
wm.keyconfigs.addon.keymaps.remove(km)
```
and if km happens to be 'Node Editor' , then that whipes Sverchoks keymaps too. So when Sverchok tries, there's no `Node Editor` keymap to access / remove entries from.

```
import bpy

wm = bpy.context.window_manager
km = wm.keyconfigs.addon.keymaps['Node Editor']

wm.keyconfigs.addon.keymaps.remove(km)
```

we can add some extra checking there, Thanks for the report.

**Comment by zeffii** [comment]
Animation node has this line in its unregister

```python
wm.keyconfigs.addon.keymaps.remove(km)
```
and if km happens to be 'Node Editor' , then that wipes Sverchok's keymaps too. So when Sverchok tries, there's no `Node Editor` keymap to access / remove entries from.

if you disabled all the node add-ons and just had Sverchok enabled, and ran the code below before hitting F8, you'd get the same Exception.

```
import bpy

wm = bpy.context.window_manager
km = wm.keyconfigs.addon.keymaps['Node Editor']

wm.keyconfigs.addon.keymaps.remove(km)
```

we can add some extra checking there, Thanks for the report.

**Comment by zeffii** [comment]
i'm not familiar with the `custom nodes` add-on, displayed at the top there.. possibly if it copies the keymap unregister code from animation nodes, it might also be removing the keymaps, before animation nodes gets a chance to.

**Comment by zeffii** [comment]
Add-ons shouldn't really be removing entire keymaps like that, because `unregister` also gets called when the user disables an addon. Not a big deal, but i'll push a fix anyway.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1252

**Comment by DolphinDream** [comment]
FYI: The custom nodes was a little add-on I wrote to create simple nodes like (separate, combine xyz) for compositor nodes I think (back in the days). I disabled it and the F8 still gets the same error (in the same sverchok code i used when i posted this issue)

[customNodes.py.zip](https://github.com/nortikin/sverchok/files/785929/customNodes.py.zip)

`
trying to save userpref at /Users/atokirina/Library/Application Support/Blender/2.78/config/userpref.blend ok
addon_utils.disable: ui_pie_menus_official not disabled.
Unregistered Animation Nodes
addon_utils.disable: space_view3d_align_tools not disabled.
Exception in module unregister(): '/Users/atokirina/Library/Application Support/Blender/2.78/scripts/addons/sverchok/__init__.py'
Traceback (most recent call last):
  File "/Applications/blender.app/Contents/MacOS/./../Resources/2.78/scripts/modules/addon_utils.py", line 397, in disable
    mod.unregister()
  File "/Users/atokirina/Library/Application Support/Blender/2.78/scripts/addons/sverchok/__init__.py", line 178, in unregister
    m.unregister()
  File "/Users/atokirina/Library/Application Support/Blender/2.78/scripts/addons/sverchok/ui/nodeview_keymaps.py", line 60, in unregister
    remove_keymap()
  File "/Users/atokirina/Library/Application Support/Blender/2.78/scripts/addons/sverchok/ui/nodeview_keymaps.py", line 52, in remove_keymap
    km.keymap_items.remove(kmi)
RuntimeError: Error: KeyMapItem 'NODE_OT_sv_monad_from_selected' cannot be removed from 'Node Editor'

Reloading: <module 'bl_operators' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/nodeitems_builtins.py'>
Registered Animation Nodes with 409 modules.

** Sverchok loaded with 199 nodes **
added keyboard items to Text Editor.
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **
`

**Comment by DolphinDream** [comment]
I added this to nodeview_space_menu.py 

```python
def remove_keymap():

    for km, kmi in nodeview_keymaps:
        try:
            km.keymap_items.remove(kmi)
        except Exception as e:
            print("EXCEPTION: remove_keymap exception caught")
            print(" km: ", km)
            print("kmi: ", kmi)
            print(repr(e))
            print('current keymap items', km.keymap_items)
            err = repr(e)
            if "cannot be removed from 'Node Editor'" in err:
                print('keymaps for Node Editor already removed by another add-on, sverchok will skip this step in unregister')
                break

    nodeview_keymaps.clear()
```

and the F8 prints:

```python
Unregistered Animation Nodes
keymaps for Node Editor already removed by another add-on, sverchok will skip this step in unregister
EXCEPTION: remove_keymap exception caught
 km:  <bpy_struct, KeyMap("Node Editor")>
kmi:  <bpy_struct, KeyMapItem("wm.call_menu")>
RuntimeError("Error: KeyMapItem 'WM_OT_call_menu' cannot be removed from 'Node Editor'\n",)
current keymap items <bpy_collection[0], KeyMapItems>
keymaps for Node Editor already removed by another add-on, sverchok will skip this step in unregister
{}
Reloading: <module 'bl_operators' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/nodeitems_builtins.py'>
Registered Animation Nodes with 409 modules.

** Sverchok loaded with 201 nodes **
added keyboard items to Text Editor.
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **
```

Fist, I’m not sure why the first “skip message” is printed before the “EXCEPTION message” is printed, since the if statement that prints the “skip message” come later in the exception handling clause. Could this be related in any way to the Animation Nodes add-on?

**Comment by zeffii** [comment]
nope. there are two places where I remove keymaps. see the pullrequest. https://github.com/nortikin/sverchok/pull/1252/files  
it's printing the other one first.

**Comment by zeffii** [comment]
but because one of those keymaps might be deprecated soon i'm not going to factor / turn that into a library function.

**Comment by DolphinDream** [comment]
I see.. ok.. added extra debug prints to the other remove_keymap.. here’s the output on F8 now:

```bash
Unregistered Animation Nodes
EXCEPTION: remove_keymap exception caught
 km:  <bpy_struct, KeyMap("Node Editor")>
kmi:  <bpy_struct, KeyMapItem("node.sv_monad_from_selected")>
RuntimeError("Error: KeyMapItem 'NODE_OT_sv_monad_from_selected' cannot be removed from 'Node Editor'\n",)
current keymap items <bpy_collection[0], KeyMapItems>
keymaps for Node Editor already removed by another add-on, sverchok will skip this step in unregister
EXCEPTION: remove_keymap exception caught
 km:  <bpy_struct, KeyMap("Node Editor")>
kmi:  <bpy_struct, KeyMapItem("wm.call_menu")>
RuntimeError("Error: KeyMapItem 'WM_OT_call_menu' cannot be removed from 'Node Editor'\n",)
current keymap items <bpy_collection[0], KeyMapItems>
keymaps for Node Editor already removed by another add-on, sverchok will skip this step in unregister
{}
Reloading: <module 'bl_operators' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_operators/__init__.py'>
Reloading: <module 'bl_ui' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/bl_ui/__init__.py'>
Reloading: <module 'keyingsets_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/keyingsets_builtins.py'>
Reloading: <module 'nodeitems_builtins' from '/Applications/blender.app/Contents/Resources/2.78/scripts/startup/nodeitems_builtins.py'>
Registered Animation Nodes with 409 modules.

** Sverchok loaded with 201 nodes **
added keyboard items to Text Editor.
** version:  (0, 5, 9, 6)  **
** Have a nice day with sverchok  **
```

**Comment by zeffii** [comment]
I don't think there's any confusion regarding the cause of the exception, or its remedy. Not sure why you would need the extra verbosity.

**Comment by DolphinDream** [comment]
I added verbosity just so I can paste what was going on at my end. I didn’t suggest it should stay in the code. I thought you would appreciate knowing what exactly was the cause of the exception (if that wasn’t clear enough), but maybe it’s irrelevant.

**Comment by zeffii** [comment]
I  consider this an animation nodes 'over reach' to remove the  keymap.

**Comment by zeffii** [comment]
because, what's happening is 

```python
import bpy


wm = bpy.context.window_manager
kc = wm.keyconfigs.addon

print('before', [m.name for m in wm.keyconfigs.addon.keymaps])

# addon 1
km_one = kc.keymaps.new(name='Node Editor', space_type='NODE_EDITOR')

# addon 2
km_two = kc.keymaps.new(name='Node Editor', space_type='NODE_EDITOR')

print('after', [m.name for m in wm.keyconfigs.addon.keymaps])

```

at this point there is still only one keymap called 'Node Editor`.
