### ISSUE TITLE
Monad input problem - wrong socket.prop_name set, unclear how

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1251]
I created a monad with 4 inputs, but it seems that from outside of the monad the forth input is the duplicate of one of the other 3. 

![monad-input-bug-2](https://cloud.githubusercontent.com/assets/2083719/23099257/74e4dc06-f630-11e6-9dec-c4b2f519b055.png)
![monad-input-bug-1](https://cloud.githubusercontent.com/assets/2083719/23099258/74ef03c0-f630-11e6-8be9-43b610deb2c5.png)
[sverchock-Icons1.blend.zip](https://github.com/nortikin/sverchok/files/785579/sverchock-Icons1.blend.zip)

**Comment by ly29** [comment]
That is indeed odd. Will investigate

**Comment by ly29** [comment]
So for some reason the ```socket.prop_name``` is wrong.
The quick fix is 
```python
D.node_groups['NodeTree'].nodes['Monad'].inputs[0].prop_name="i_x2"
```
Obviously this doesn't answer how it happened that  is wrong in the first hand...

**Comment by ly29** [comment]
Adding a new monad instance sets it up correctly. The ```inputs_template``` is correct. Hmm.

**Comment by ly29** [comment]
I am not sure how it happened, but forcing setting the prop_name upon name change forces it to happen.

**Comment by zeffii** [comment]
The match node uses the Int/Float switch, makes me think it has something to do with the `prop_types`, i'm going to push the unfinished iojson-bump branch

**Comment by zeffii** [comment]
pushed. it might not fix it (haven't tested) but it's certainly not going to make it worse.

**Comment by zeffii** [comment]
oh I forgot, monad uses the `node copy operator`.. not the `create_dict_of_tree`  . -- therefore iojson changes will have no effect either way.

**Comment by ly29** [comment]
Yeah but won't hurt anyway.

**Comment by zeffii** [comment]
short example of the problem https://gist.github.com/b6ff2ecc787586046ab8d1b2fd942555

**Comment by ly29** [comment]
@zeffii 
Not sure I see the problem there.

**Comment by zeffii** [comment]
the problem didn't appear to be directly related to that particular configuration of nodes turned into a monad,  but the gist could make reproduction less involved.

**Comment by ly29** [comment]
True, thanks

**Comment by DolphinDream** [comment]
What I remember doing is that once I created the monad I connected more inputs inside the monad and renamed them x,y,Nx,Ny, adjusting their limits and descriptions. Once I got out of monad I noticed that the x was Nx. It wasn’t just the label wrong but even the limits. It appeared that x was indeed Nx (or a copy of it). Then I added more inputs inside the monad for x, thinking that somehow the x got screwed up when I created it, but then again, the new inputs connected to the monad input group ended up being Nx again. Yeah the x,y values come from a min/max nodes that had their to int turned on since i wanted the monad inputs to be int once created. Btw, it would be nice if you could change the type of a monad input once created (e.g. int to float, float to int).

**Comment by ly29** [comment]
> Btw, it would be nice if you could change the type of a monad input once created (e.g. int to float, float to int).

Yes it would :) For now add and remove, no promises but will look into it.

Yeah, the socket ```x``` referenced the property of ```Nx```. If you edit ```x``` socket it now sets all the time.
Not clear where to logic miss was that caused to happen. 
Will dig around a bit more, if you manage to pin down a scenario where it happens would be great, but with the fixes in now should be a lot less likely to happen.

**Comment by ly29** [comment]
Still can't find how it happened. Hmm closing for now
