### ISSUE TITLE
Read & parse JSON / XML files from disk - Linking Empty

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1257]
Can sverchock read and parse JSON/XML files from disk? Here's the problem I'm trying to tackle: I am currently thinking about creating a blend file for SV icons and I think I'd like to be able to define a JSON (or xml) file that stores the list of icon information in a structured file, specifying the icon name, category, subcategory, description etc. Then I would like to be able to read/parse this file and based on the categories/subcategories/order these icons are listed in to place them in a dynamic 2D grid which could be adjusted via sverchok nodes. Regardless of whether the SV icon blend file should be organized like this I was wondering if in general this kind of thing is possible in sverchok. 

My goal for this project is to create a new icon object (the parent of a set of parts defining an icon) in the icon blend file, give it a predefined pattern name (SV_SOME_ICON_NAME) then once the icon info is added to a JSON file (read by a SV node), the nodetree will place my object in a given location in the 2D grid defined by a SV node tree. Basically I'm trying to avoid having a predefined grid structure for the icons and be able to expand/reduce the rows available for a category as new icons are added to/removed from a category. 

The SV node tree would know where each icon is (given its name) in the 2D icon grid, thus when it renders each icon it can save it to disk in a filename given by that icon's name. Also it would only render the cells in the grid that have an icon in it (non-empty cells are skipped). Additional, for partial rendering of only new icons or a certain set of icons, I could provide a select set of icon names that will need re-rendering so that not all icons are rendered all the time. All these would be possible if I could somehow easily map a icon info (possibly defined in a JSON file) to a dynamically set 2D location in a 2D grid of icons.

Any thoughts ?

**Comment by ly29** [comment]
It is a bit out of scope. Can probably be done but I would simply write a script or script node. 

The json/csv read part code is old and doesn't do anything meaningful with strings, also only works with files in the blender text editor. 

Apart from that it sounds like nice setup to have.

**Comment by DolphinDream** [comment]
So..I defined a JSON file listing the icons for the nodes in the node categories and read the file to identify the numbers of categories and number of icons in each category. But now I wonder whether it would be better to use the node attributes to generate this JSON file automatically. I would need the nodes to have additional attributes added perhaps:

```python
{
    "generators":
        {
            "line":
            {
                "description": "Line Generator",
                "icon_id": "SV_LINE"
            },
            "plane":
            {
                "description": "Plane Generator",
                "icon_id": "SV_PLANE"
            },
            "plane":
            {
                "description": "Plane Generator",
                "icon_id": "SV_PLANE"
            },
         # etc...
        },

    "transforms":
        {
            "rotation":
            {
                "description": "Rotation transform",
                "icon_id": "SV_ROTATION"
            },
            "scale":
            {
                "description": "Scale transform",
                "icon_id": "SV_SCALE"
            },
            "move":
            {
                "description": "Move transform",
                "icon_id": "SV_MOVE"
            }
        },
     # etc
}
```

If each node would have an extra attribute sv_category = “SV_CATEGORY_GENERATORS”, “SV_CATEGORY_TRANSFORMS” etc, perhaps a script could iterate over all the nodes registered and construct a JSON file based on these attributes. Who knows, perhaps the search menu itself could be generated based on this node attributes, without having to have the search_menu explicitly create menus and submenus. Of course, if you rely on the search menu to be generated automatically based on these attributes, it would require more diligence on our part to make sure all nodes have all the necessary attributes defined or else the nodes would not appear in the search menu.

Anyway, would it be ok to add these extra attributes to the nodes? Would it help with what i’m trying to do ? (i.e. is it possible to traverse all registered nodes and create a JSON file like the one above?

**Comment by zeffii** [comment]
I think this overcomplicates the matter.of generating icons . also, if adding cats/subcategories to the node directly, with the intent to auto parse directories for a node menu, makes it more complicated to force submenu item ordering.

Definitely hold off on that effort. A simpler solution will emerge

**Comment by zeffii** [comment]
Forgive me if you mentioned this, I'm bad at getting through walls of text.

Also, a node might specify any number of custom icons . Some icons won't be directly associated with any one node or even a node at all

**Comment by zeffii** [comment]
We can use the strength of Blender rather than forcing the constraint to make sverchok the main driver of the file. What I suggest is first generate a grid of Empties, more than you need initially, and rename them to correspond with a `SV_ICON_NAME`, and build up the icon centered around each Empty. This is almost no work initially, and each icon you add can either go at the end of a row.. or on a new column.

Then have a script that takes (selected) Empties, and going through all of them individually to render to a file with that empty's name. Parent lights to the camera, and script the camera movement to jump to each empty.

**Comment by zeffii** [comment]
added bonus of using an empty as a centering device is that you can parent all icon geometry to the empty and rearrange the empties manually/procedurally.

**Comment by DolphinDream** [comment]
That’s more or less what I have already done. I used the Animation Node to replicate an empty at the center of a grid generated by sverchok nodes (since I don’t know yet how to use sverchok  to replicate an empty), then I renamed a empty to SV_ICON_NAME which then I used as a parent to the icon parts defining that icon. I’m still working on having these icon (empties) location manipulated by some sverchok nodes. (hence my JSON question).

![Icon Grid Setup](https://cloud.githubusercontent.com/assets/2083719/23189828/cccbb05a-f862-11e6-9575-a10354f6b05d.png)

**Comment by DolphinDream** [comment]
And yes, the camera is located above a cell in the grid using SV nodes.
![icon grid camera locator setup](https://cloud.githubusercontent.com/assets/2083719/23190009/a0a92b64-f863-11e6-98f9-548eb7f544d4.png)

**Comment by enzyme69** [comment]
I want to know more about Linking Empties - made easier - using Sverchok!

**Comment by DolphinDream** [comment]
Is there a SV node that finds objects by name ? If I have a list of icon names (strings) “SV_PLANE”, "SV_TORUS" etc.. I would like to have a node that gives me the objects corresponding to these names (if they exist in the scene). 

![icon name grid location generator](https://cloud.githubusercontent.com/assets/2083719/23190826/42bff348-f868-11e6-9e2d-21143c0d75e1.png)

**Comment by DolphinDream** [comment]
@zeffii I agree with the point you were making earlier that some icons are not nodes or that multiple icons could belong to one node. Which is a good reason why adding extra attributes to the node itself would not help (aside from the fact that the order in a self generated search menu is undetermined based solely on the existence of extra node attributes). 

Btw, I was going to organize the icons into “node” icons, “extra” icons etc and list the node icons grouped together and the “extra” icons grouped together. Various nodes may share certain extra icons (e.g. interpolation icons for instance; not that we need to create new ones for interpolation, but just to give an example of icons that could be used in various nodes).

**Comment by nortikin** [comment]
centers of polygons - replicate with empty out node
select objects by name with https://gist.github.com/nortikin/9e22995948982d118939e2f9a7662902

**Comment by enzyme69** [comment]
@nortikin Empty Out seems to be broken or something. Only 1 empty being generated?

**Comment by enzyme69** [comment]
A good time to test multiple EMPTY and Link to Blend.

**Comment by enzyme69** [comment]
![screen shot 2017-02-23 at 13 24 26](https://cloud.githubusercontent.com/assets/3952687/23242156/77c98658-f9cb-11e6-955c-1246c724070f.png)

Reading Empty Out, maybe need a tweak... I am such a noob.

**Comment by zeffii** [comment]
Empty out wasn't designed to use multiple matrices, it's part of a family of scene / viz nodes which have not had much attention

**Comment by enzyme69** [comment]
that is what i thought, maybe Nortikin can do some magic. otherwise I think
AN can be used.

Instancing based on empty is attractive
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by ly29** [comment]
@enzyme69 
Looking back at empty out there are things I would to different, extending to multiple empties would be quite easy based on code on viewer bmesh. But I never think I actually worked with it either so I am not going to put time into it right now. If somebody wants to do it I am all for it.

**Comment by enzyme69** [comment]
I wish I am more knowledge-able coding based maybe I am just one gap and
fear away from making my first node.

As user I like Empty to be able to be brought in and out of Sverchok as a
mean to bring Linked Objects.

Imagine:
- multiple empty with metadata
- metada to link objects

But I am also noobs with Blender workflow with empty.

Will make live noding about empty and linked obkects anyways using AN for
now.

Sverchokk in the future
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
here;s a basic scriptnode, which does most of what a fullblown multiple-empties node would need to do
https://github.com/nortikin/sverchok/issues/1263#issuecomment-281670201

**Comment by enzyme69** [comment]
Awesome @zeffii ! It works. Dupli Group and Dupli Type can then be accessed via Object ID.

![screen shot 2017-02-23 at 23 25 57](https://cloud.githubusercontent.com/assets/3952687/23259091/8131181a-fa1f-11e6-81be-b319d7c8525b.png)

I actually just understand Blender LINK and GROUP a bit better. Maybe still sketchy. Man it was such a headache. This blog helps a bit.
https://jtheninja.wordpress.com/2014/06/24/121/

"Overriding" stuff like Materials to LINKED DATA is not trivial. Apparently there is such thing as PROXY. I am still not quite sure how to do the proper LINK and OVERRIDE of Materials for A Rigged Character.

At some point, it will probably make more sense....

So far, I am doing it like this:
- LINK Data into Asset X, this should come greyed out.
- Make Proxy A, B, C, assigning different material on Object Level --- I am still not 100% sure with Proxy that comes from GROUPed data.
- Anyways, Make few Group variation of the Proxy, make Group A, B, C, ...
- Generate EMPTY and then the rest is trivial.

**Comment by enzyme69** [comment]
I think I make this thread a bit out of topic @DolphinDream sorry. But carry on with the ICON thing! 👍

**Comment by DolphinDream** [comment]
Yeah, I noticed the take over, @enzyme69  ;) Actually I figured out a way to have my icongrid (json based) script node find objects (empties) in the scene with the names I'm looking for (SV_ICON_NAME) and have it create a list of objects and the list of corresponding locations (on a grid) for those objects. I figured that it's easier this way than relying on some 20 different nodes to give me the same object/location info. (see the [ customIcon pull request thread](https://github.com/nortikin/sverchok/pull/1242))

**Comment by zeffii** [comment]
>  I realized 10000 EMPTY slows down Blender, but DupliFace of a single object with 10000 faces = faster.

that's what the DupliInstancer node does. 0_o.  because it is faster to push the geometry of 10000 faces into one object than it is to generate 10000 objects with a single face each.

**Comment by enzyme69** [comment]
Ok thanks for the info :) I started to have rough ideas to deal with
multiple Blends, linking, and dupli them. What DolphinDream does also
inspired me to do make like Blend Grid Layout Contact Sheet of multiple
Blends.
