### ISSUE TITLE
Can script node generate UI for parameters

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1261]
I know the script nodes can generate input/output sockets, but is it possible to create also UI elements for parameters? E.g checkbox (bool), dropdown list etc?

**Comment by ly29** [comment]
To certain extent yes. 
There was the script 3 project that could all these things but due to time constraints I never finished it. If you want to things like this or really anything more advanced I recommend the redux. 

You can do a full node in text editor for one offs

**Comment by zeffii** [comment]
>  You can do a full node in text editor for one offs

For anything that would benefit from customized ui with limits on sockets, you want to go straight to a node. As @ly29 mentions you can write a Node in the TextEditor (add register/unregister) , and inject the node into the nodeview using 'bpy.data.node_groups['NodeTree'].nodes.new("your_bl_idname")`.

The ScriptNodes are mostly used for one off experiments / quick input-output processing that would otherwise take many nodes.

**Comment by zeffii** [comment]
yes you can do custom properties on the UI because SNLite (unlike SN MK1 ) allows you to specify a custom draw function. From that point, you need bpy skills.

https://github.com/nortikin/sverchok/issues/942#issuecomment-282094415

**Comment by DolphinDream** [comment]
Does this lite node have documentation somewhere ?

**Comment by zeffii** [comment]
yeah, go to the top of that thread.

**Comment by DolphinDream** [comment]
I can't seem to find an example on that thread showing how to use the "custom draw" button to create properties. Do you have an example somewhere?

**Comment by DolphinDream** [comment]
@zeffii To inject a node into the node tree.. does this get done via the register in the node script? or would I have to do it in blender console or running the script in the blender text editor?

**Comment by zeffii** [comment]
All custom draw does is append to snlite's own 'def draw_buttons ' a call to a user supplied draw function. At the end of the page shows an example of registering a property group and how to setup the update function on member properties.

It could be simplified
