### ISSUE TITLE
Can a script node have an object output socket 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1263]
Can I have an output socket that returns an object? or a list of objects ?

**Comment by zeffii** [comment]
it was never explicitly added, ObjectSocket was added to Sverchok about 2 years after scriptnode 1 was done. But that should not be a problem to add. The syntax would then be "o" to mean ObjectSocket.

**Comment by zeffii** [comment]
scriptnode lite does already allow Object Sockets.

**Comment by DolphinDream** [comment]
I think it worked with ’s’.. and i just tried ‘o’ and the output socket does not appear. I reloaded the scripts and even restarted blender and created new script node.

**Comment by zeffii** [comment]
I would need to update the ScriptNode, but you can use ScriptNode Lite. (it does require that you connect something  to the output socket - else it won't update )

**Comment by zeffii** [comment]
```python
"""
in num_empties s d=4 n=1
out obj_generated o
"""
import bpy
scene = bpy.context.scene
objects = bpy.data.objects

idx = 0
for i in range(num_empties):
    mt_name = 'empty_sv.' + str("%04d" % i)
    if mt_name not in objects:
        mt = objects.new(mt_name, None)
        mt['origin'] = 'SNLite'
        mt['idx'] = i
        mt.location = (0, 2, 1.2*i )
        mt.empty_draw_size = 2
        scene.objects.link(mt)
        scene.update()
    else:
        mt = objects[mt_name]
    idx += i

for obj in objects:
    if obj.get('origin') == 'SNLite' and obj.get('idx') > idx:
        scene.objects.unlink(obj)
        objects.remove(obj, do_unlink=True)


obj_generated = [o for o in objects if obj.get('origin') == 'SNLite']
```

![image](https://cloud.githubusercontent.com/assets/619340/23213622/e7da1a68-f90b-11e6-9907-c954cbc2610d.png)

not a perfect script.. but i think you get the idea

**Comment by zeffii** [comment]
for the regular ScriptNode MK1
https://github.com/nortikin/sverchok/blob/master/nodes/generators_extended/script.py#L19

**Comment by zeffii** [comment]
it could be as simple as adding it here
```
sock_dict = {
    'v': 'VerticesSocket',
    's': 'StringsSocket',
    'm': 'MatrixSocket',
    # 'o': 'SvObjectSocket'
}

```
but i wouldn't hold my breath.

**Comment by zeffii** [comment]
here another: https://github.com/nortikin/sverchok/issues/942#issuecomment-281928625

**Comment by zeffii** [comment]
so in short. yes, but at the moment only Scriptnode Lite. (but don't let the term Lite fool you)
