### ISSUE TITLE
Terrain nodes proposal

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1265]
So, here we are... as mentioned in the Texture Viewer  node [issue](https://github.com/nortikin/sverchok/issues/1248) we can discuss here for an eventually nodes branch for terrain creation. I think many people will be interested: as i understood Sverchok users are architects, designers, modelers, creative minds. My proposal is to develop a sub branch so people can eventually download this module or not,( sverchok has 200 nodes now i think..) I think with a git submodule this could be possible. 
Here a list of nodes to develop:

- general terrain node with  displacement and colour

- selector nodes based on height, slope and other input

- erosion nodes

- visualizer with Vertex Buffer Object and/or glsl shader

- multhithreading support

- tiled terrain

more to come...

**Comment by kalwalt** [comment]
One of the first thing i want to do is a `terrain node` in which is integrated fractal and grid vector creation, in a way you don't need to create every time a `plane node` a and `fractal node`. I hope in the next days, weeks to have the time to try this, i think i colud use the grid function that come from `geom.py` to start in a scriptLite this kind of node.

See you! :smile:

**Comment by kalwalt** [comment]
This is an idea with a scripted node (lite), i imported as you can see the make_plane function from the plane node and the noise function from mathutils.
![terrain_generator_script](https://cloud.githubusercontent.com/assets/1275858/23473899/1d733938-feb2-11e6-85c7-d61ed7a4c9e2.png)
Then next i will implement a my make_plane function, so that build only the verts without edges and faces that i don't need. Should be speeder?

This the script, if someone wants to try it:

```python
"""
in int_X s d=2 n=2
in int_Y s d=2 n=2
in StepX s d=1.0 n=2
in StepY s d=1.0 n=2
in noise_type s d=1 n=2
out data s
"""
from sverchok.nodes.generator.plane import make_plane
from mathutils import Vector, noise

args = make_plane(int_X, int_Y, StepX, StepY, separate=False, center=False)

v_list=[]

if args[0]:
    for v in args[0]:
        v_list.append(v)
    data = [[noise.noise(Vector(tuple(vert)),noise_type) for vert in v_list]]

```

**Comment by kalwalt** [comment]
![terrain_generator_script01](https://cloud.githubusercontent.com/assets/1275858/23479027/68082858-fec3-11e6-9503-6e9057bd0d9c.png)
This is the  'modified' version of the make_plane function, tha plane node is necessary for the viz in 3d of course. The idea is to vizualize via new  VertexBuffer node (plus shader maybe). I'm searching also a way to switch the output in a script node lite, switching from scalar to vertex as the` noise node`, Does it possible @zeffii ?

**Comment by zeffii** [comment]
to switch output.. you could just change the header/directive
```python
'''
in some_name v 
out some_other_name v
'''
```
to
```python
'''
in some_name v 
out some_other_name s
'''
```

:) 
or output both from the node.
```python
'''
in some_name v 
out some_other_name v
out some_other_other_name s
'''
```

**Comment by zeffii** [comment]
if you want to prevent calculation you can do regular Node code..

```
'''
in some_name v 
out some_other_name v
out some_other_other_name s
'''

if self.outputs['some_other_other_name'].is_linked
    some_other_other_name = .... some data.
```

**Comment by zeffii** [comment]
"self" is available in the scope of the SNLite code.

**Comment by zeffii** [comment]
and `ctrl+enter` while in the TextEditor will update the loaded code : )

**Comment by kalwalt** [comment]
i will try thank you @zeffii

**Comment by zeffii** [comment]
mind if i close this until you get around to it.
