### ISSUE TITLE
Texture viz node

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#1266]
- [x] Color modes, RGB + RGBA
- [ ] Update a packed blender images for texture/image use, if this option is used, use this one for gltexture
- [x] Control file name and directory of save
- [ ] Save on frame change
- [x] Custom image size

More?

@kalwalt

**Comment by kalwalt** [comment]
i will think about!

**Comment by kalwalt** [comment]
@ly29 i will add allowing texture not squared, if it is possible

**Comment by zeffii** [comment]
@kalwalt  i've made some changes in  https://github.com/nortikin/sverchok/pull/1264    but haven't hooked them up yet, i thought maybe you want to do that. 
- now has directory selecting using a generic file selector
- allows `self.image_name` to be passed. 

see the parts with `#####` at the end of the line.

**Comment by zeffii** [comment]
i've pushed this anyway, so you'll need to pull and merge

**Comment by kalwalt** [comment]
@zeffii ok i will try it.

**Comment by zeffii** [comment]
```
    def save_bitmap(self, image_name='image_name', alpha=False):
```
can be replaced with 

```python
    def save_bitmap(self, alpha=False):
        image_name = self.image_name or 'image_name'    # if self.image_name was empty it will give a default
```

**Comment by zeffii** [comment]
maybe the draw_buttons_ext
```
    def draw_buttons_ext(self, context, layout):
        callback_to_self = "node.scriptlite_ui_callback"
        directory_select = "node.sv_generic_dir_selector"
        layout.label(text="Save texture as a bitmap image, choose a format:")
        layout.separator()
        layout.prop(self, "bitmap_save")
        layout.separator()
        row = layout.row(align=True)
        leftside = row.split(0.7)
        leftside.prop(self, 'image_name', text='')
        rightside = leftside.split().row(align=True)
        rightside.operator(callback_to_self, text="Save").fn_name = "save_bitmap"
        rightside.operator(directory_select, text="", icon='IMASEL').fn_name = "set_dir"
```
![image](https://cloud.githubusercontent.com/assets/619340/23307078/745a1466-faa6-11e6-8327-124b2a094ce7.png)

**Comment by kalwalt** [comment]
i can save in the desired folder! now only to fix little things.

**Comment by zeffii** [comment]
@kalwalt   i won't touch this anymore until you seek help, promise ;)

**Comment by ly29** [comment]
I won't do more either

**Comment by Kosvor2** [comment]
If someone wants to create a renderer on python for Blender, then the Sverchok is a convenient starting point.

![sverchok_renderer](https://cloud.githubusercontent.com/assets/22656834/23329336/33ad6e42-fb58-11e6-80a5-9b08f9c69146.png)

**Comment by kalwalt** [comment]
@Kosvor2  nice idea!

to @ly29  i will add to the list if it is a doable thing, (i looked in the code of the `text viewer node`)  screen display in a frame instead of normal rect squared. Does the frame could be resized and moved?

**Comment by ly29** [comment]
It should be doable. There are some potential gotchas with it so do it as separate thing. 

do things in order, not everything at once.

**Comment by zeffii** [comment]
bgl isn't great for interactive UI .  please do everything else first.  @kalwalt

**Comment by kalwalt** [comment]
Color mode support done!
![texture_viz_rgb_test_final](https://cloud.githubusercontent.com/assets/1275858/23334975/dfe9f822-fbaa-11e6-9906-1cf24dc93bf3.png)

The script load a simple rgb image and output to to texture viz.

**Comment by kalwalt** [comment]
![texture_viz_rgb_test_w_fractals](https://cloud.githubusercontent.com/assets/1275858/23335414/9369e1dc-fbb5-11e6-91a2-93534259c291.png)
With fractals per color channels

**Comment by kalwalt** [comment]
![texture_viz_rgb_test_w_fractals01](https://cloud.githubusercontent.com/assets/1275858/23335506/27b1eb54-fbb7-11e6-8c52-a2f3e4fff78b.png)

this is better, with stepx,y=0.03

**Comment by Kosvor2** [comment]
To make tuple input available:

```

    def get_buffer(self):
        data = np.array(self.inputs['Float'].sv_get(deepcopy=False)).flatten()

```

![color_flatten](https://cloud.githubusercontent.com/assets/22656834/23379789/15001b62-fd5a-11e6-82e0-abc57dd9dfed.png)

**Comment by kalwalt** [comment]
super cool idea! @Kosvor2

**Comment by Kosvor2** [comment]
No need for extra input. Maybe just rename **Float Input** to just **Input**

![pixels](https://cloud.githubusercontent.com/assets/22656834/23383793/f15b6daa-fd69-11e6-9768-2f2db465afa0.png)

**Comment by kalwalt** [comment]
@Kosvor2  great! do you have some issue with the display and the texture viewer?

**Comment by kalwalt** [comment]
![texture_viz_tuples_noise](https://cloud.githubusercontent.com/assets/1275858/23384837/cc71a5f8-fd4c-11e6-9ea1-10d8d4b38047.png)

I will add to it!

**Comment by enzyme69** [comment]
every now and then I am getting weird glitch of interface of Blender,
becoming black or flickering and seeing ghosting of interface.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
texture viewer node alot of fun
![texture_noise](https://cloud.githubusercontent.com/assets/5783432/23415453/467ca084-fdf0-11e6-962e-5e349dcd317a.png)

**Comment by kalwalt** [comment]
@nortikin wow! the Texture viz will always be better!

**Comment by enzyme69** [comment]
Is it already available to use because I am not actually getting the latest
Texture Viewer in all full color :|

**Comment by nortikin** [comment]
@enzyme69 how you do? there is vertex socket plugged

**Comment by kalwalt** [comment]
@enzyme69 in `texture_viewer.py` just change the line:

```
data = self.inputs['Float'].sv_get(deepcopy=False)[0]
to
data = np.array(self.inputs['Float'].sv_get(deepcopy=False)).flatten()
```

**Comment by kalwalt** [comment]
![custom_tex_rgba_settings](https://cloud.githubusercontent.com/assets/1275858/23578323/8e25ef58-00d4-11e7-9940-e31ee76de860.png)
We can save a BW, RGB, RGBA image in the whatever  size we want! but maximum 1024...

**Comment by kalwalt** [comment]
It seems if found the solution for the viz display bug, wait for other news, soon.

**Comment by kalwalt** [comment]
Added pull request https://github.com/nortikin/sverchok/pull/1303 please test this.

**Comment by kalwalt** [comment]
New feature of Texture viewer node: transfer to blender internal image viewer! see [this](https://github.com/nortikin/sverchok/pull/1363) pull request.

**Comment by kalwalt** [comment]
@zeffii Sorry, there is a bug in `draw_label` and other small things, i'm working on it. Soon i will ask for a pull request.

**Comment by kalwalt** [comment]
fix here: https://github.com/nortikin/sverchok/pull/1383

**Comment by zeffii** [comment]
closing as inactive for now. welcome to reopen or start fresh issue about node (focusing on new changes).

very fun node btw.

**Comment by kalwalt** [comment]
i would develop the `Save on frame change` feature, but i don't know if i will have the time in the near future...
