### ISSUE TITLE
Brainstorming about a Hexagonal Grid node 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1270]
Let’s talk hexa ! :) 

I’ve been playing around with various nodes to create hexagonal grids and I am a bit frustrated I can’t create a hexagonal grid to my linking, preferably using a simple setup. Jimmy’s videos inspired me but only to leave me even more frustrated that we can’t create a hexagonal grid with a simple node setup. I know the brick node can do some magic with getting this done, but it’s not quite doing it for me, since the edges of the brick layout are cropped. Maybe I could get rid of those vertices at the edge of the brick grid with some list magic nodes, but why going through so much trouble just to create a simple hexagonal grid?   

There may be other node setups that can do this, other than the brick node, like creating a staggered set of points using the points on the plane node, with every other line shifted by some amount to get the triangular stagger pattern.. which then can be used to place a properly scaled circle (6 points) to create the hexagonal grid. Yeah.. this is how my node setup looks like, using two lines + circle generators: 

![hexa grid setup](https://cloud.githubusercontent.com/assets/2083719/23334724/06d9fe74-fb73-11e6-82d5-6d6b523cd79e.png)

Not pretty, but it does the job. I can even put it in a monad and call it a day. But i’m not quite satisfied with that either. I want a magical hexagonal grid node that can do something like this out of the box:

http://www.redblobgames.com/grids/hexagons/implementation.html

Checkout the section 4.4 (map shape). where the hexagons can be arranged to form triangle shapes, hexagonal shapes, rectangular shapes, rhombic shapes etc. 

Anyway, before I dive into node coding I figured maybe I can brainstorm around this a bit with y’all.

**Comment by DolphinDream** [comment]
Having fun with hexa grids ☺️  No SV node was hurt in the making of this grid. 😉 

![hexagridlevels-1k](https://cloud.githubusercontent.com/assets/2083719/23335596/467070aa-fb86-11e6-93f1-793c6fb17655.jpg)

**Comment by enzyme69** [comment]
This excites my brain, because suddenly something make sense a bit more! This is like Kaleidoscope Puzzle.

**Comment by DolphinDream** [comment]
And now let’s abuse the SV nodes to make the above :) This is based on a series of triangle meshes subdivided, to use their vertices to replicate a hexagon. 

![hexagridlevels-1](https://cloud.githubusercontent.com/assets/2083719/23335909/522befda-fb8d-11e6-9c9f-05f26bbc2a06.png)

[hexaGrid-Levels.blend.zip](https://github.com/nortikin/sverchok/files/801639/hexaGrid-Levels.blend.zip)

**Comment by enzyme69** [comment]
Wonder how the most correct hexagon grids is like. Maybe Mathematically
beautiful yet complex for non Math users.

I translated OSL hexagon at some point... weird but somewhat manage.

http://blendersushi.blogspot.com/2014/02/osl-honeycomb-aka-hexagon-tile.html

I think Small Blender Things have lots of tricks need to be revisited.

At some point the hexagonal stuff become like Mapping that works. More or
less like bricks.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by portnov** [comment]
First, it is possible to use Bricks generator to generate hexagonal grids: https://github.com/portnov/sverchok/issues/19

Second, somewhere in the past I had a special "hex grid" node, I wonder where it gone...

**Comment by portnov** [comment]
Aha, https://github.com/portnov/sverchok/issues/10

**Comment by zeffii** [comment]
there's a simple function that takes `(num_rows, num_column, radial_distance)` and produces points that can be used.

![image](https://cloud.githubusercontent.com/assets/619340/23338495/ffef9fca-fc0c-11e6-93d8-72fa26799696.png)

```python
"""
in numx  s  d=6    n=2
in numy  s  d=5    n=2
in rad   s  d=0.4  n=2
out grid v
"""

import math

def get_grid(b, numx, numy):

    c = b * 2
    a = math.sqrt((c*c) - (b*b))

    grid_values = []
    grid_x = 0
    grid_y = 0
  
    for i in range(numx):
        if (i % 2 == 0):
            grid_y += b
        for j in range(numy):
            grid_values.append([grid_x, grid_y, 0])
            grid_y += 2*b

        grid_x += a
        grid_y = 0

    return grid_values

grid = [get_grid(rad, numx, numy)]

```

**Comment by DolphinDream** [comment]
@portnov sure you can use brick node, but it creates extra (cropped) vertices at the top and the bottom.. which do not allow you to create a hexagonal tile all the way to these edges.

![hexagrid-bricknode](https://cloud.githubusercontent.com/assets/2083719/23340886/1f0afb44-fc0c-11e6-833c-40c874477bca.png)

**Comment by DolphinDream** [comment]
@zeffii nice. Now we can make that a node ;) This is a nice setup that can be used to create half tone images (by varying the hole of the hexagons. I can see a new life noding coming up :) Jimmy ? 

Here’s a minor update to @zeffii code to make it more predictable (default radius is 1 which will create a perfect tile with a 6-point circle of radius 1.  (see the grease pencil math) 

```python
"""
in numx  s  d=6    n=2
in numy  s  d=5    n=2
in rad   s  d=1.0  n=2
out grid v
“""

from math import sqrt

def get_grid(r, numx, numy):

    dx = r * 3 / 2
    dy = r * sqrt(3)

    grid_values = []
    grid_x = 0
    grid_y = 0

    for i in range(numx):
        if (i % 2 == 0):
            grid_y += dy/2
        for j in range(numy):
            grid_values.append([grid_x, grid_y, 0])
            grid_y += dy

        grid_x += dx
        grid_y = 0

    return grid_values

grid = [get_grid(rad, numx, numy)]
```

![hexagridscript2](https://cloud.githubusercontent.com/assets/2083719/23341255/c7bb3e02-fc11-11e6-95ed-59c49d61b5b0.png)

**Comment by DolphinDream** [comment]
Behold !! 🙌 The mighty HexaGrid node is born .. (again?) :) Soon to be unleashed into the pull request realm to fight the evil spaghetti of nodes attempting to do some hexa grid layouts 😉 

![hexagridnode-layouts-example1](https://cloud.githubusercontent.com/assets/2083719/23344642/084489b0-fc4e-11e6-8461-c4e51c897c0e.png)

![hexagrid-layouts](https://cloud.githubusercontent.com/assets/2083719/23344644/1130694a-fc4e-11e6-8892-d559f947d3d5.jpg)

**Comment by kalwalt** [comment]
congratulations, amazing work!

**Comment by nortikin** [comment]
vectorization maybe to act with every hexagon?
to make attractor-specific layouts

**Comment by DolphinDream** [comment]
@nortikin I'm still working on vectorization and you're right, the vectorization has to be meaningful especially once we add VEP outputs as to allow to modify the tiles effectively. I'll elaborate more on this aspect soon.

**Comment by AG89z** [comment]
Not sure it is related to the last entry, however I was trying to replicate something like this without much success (I mean inflating the cells). Is it possible with the current node or it would be necessary to wire a honeycomb from scratch? 
![image](https://user-images.githubusercontent.com/26380268/28229363-befda172-68e2-11e7-8660-ca7656a170f8.png)

**Comment by AG89z** [comment]
Ok never mind, I managed 

![image](https://user-images.githubusercontent.com/26380268/28237671-5a8140f6-6945-11e7-9cda-37227b332ee1.png)
