### ISSUE TITLE
Script Node example that generate and delete any object type cleanly

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1275]
Many nodes in Sverchok can generate Mesh Data in many different ways. Random Vector MK2 is a favourite examples.

Now, I am thinking of using Script Node. Basically to be able to generate ANY OBJECTS but using script way.

For example, I want to generate bunch of objects, let say Camera or Lights. But I want to be able to name it, clean it up, etc.

Do we have such example?

Thanks!

**Comment by enzyme69** [comment]
It's a bit like "on the fly Instancing" ala Animation Nodes. But I want to do more, let say, if I want to create NODES on the fly, etc.

Object Instance Script node? Maybe, but still thinking....

**Comment by enzyme69** [comment]
Making a lamp for example using BPY OPS:
bpy.ops.object.lamp_add(type='POINT', radius=1, view_align=False, location=(0, 0, 0), layers=(True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False))

But I heard that we should not use OPS.

For example, I want to suddenly generate 100 lamps.

**Comment by enzyme69** [comment]
Currently I am doing it this way:
![screen shot 2017-02-28 at 12 33 35](https://cloud.githubusercontent.com/assets/3952687/23387668/24f3eb18-fdb2-11e6-9d65-b8379ba50150.png)

**Comment by enzyme69** [comment]
Hints for self:
Zeffii Script Node for Empty might be a good example...

**Comment by enzyme69** [comment]
Extra info, will try:
http://stackoverflow.com/questions/17355617/can-you-add-a-light-source-in-blender-using-python

So far what I know:

I can generate 1 lamp and many lamp, maybe give name + numbers
I don't know how to delete and clean data in Blend properly using script, using Nodes however I have no idea

**Comment by enzyme69** [comment]
Noob Python Script to generate bunch of lamps:

```python
import bpy

scene = bpy.context.scene
lamp_name = "mylamp"
total_lamp = 25

for item in range(total_lamp):

    # Create new lamp datablock
    lamp_data = bpy.data.lamps.new(name=lamp_name, type='POINT')

    # Create new object with our lamp datablock
    lamp_object = bpy.data.objects.new(name=lamp_name, object_data=lamp_data)

    # Link lamp object to the scene so it'll appear in this scene
    scene.objects.link(lamp_object)
```

**Comment by enzyme69** [comment]
Strangely enough, it's not actually hard if I just modify @zeffii Empty to Lamp.

```python
"""
in num_lamp    s   d=4   n=1
out obj_generated o
"""
import bpy
scene = bpy.context.scene
objects = bpy.data.objects

idx = 0
for i in range(num_lamp):
    lamp_name = 'lamp_sv.' + str("%04d" % i)
    if lamp_name not in objects:
        lamp_data = bpy.data.lamps.new(name=lamp_name, type='POINT')
        lamp = objects.new(name=lamp_name, object_data=lamp_data)
        lamp['origin'] = 'SNLite'
        lamp['idx'] = i
        #lamp.location = (0, 2, 1.2*i )
        #lamp.empty_draw_size = 2
        scene.objects.link(lamp)
        scene.update()
    else:
        lamp = objects[lamp_name]
    idx = i

for obj in objects:
    if obj.get('origin') == 'SNLite' and obj.get('idx') > idx:
        scene.objects.unlink(obj)
        objects.remove(obj, do_unlink=True)


obj_generated = [o for o in objects if o.get('origin') == 'SNLite']
```

**Comment by enzyme69** [comment]
There is a weird thing that I cannot plug Int Input to the Script Node.. but other than that... all good.

![screen shot 2017-02-28 at 15 27 02](https://cloud.githubusercontent.com/assets/3952687/23391611/6cb7daaa-fdca-11e6-962f-0eea09f62bb6.png)
![screen shot 2017-02-28 at 15 26 57](https://cloud.githubusercontent.com/assets/3952687/23391613/6cbb0dce-fdca-11e6-9b7f-72a9903bced7.png)
![screen shot 2017-02-28 at 15 26 51](https://cloud.githubusercontent.com/assets/3952687/23391612/6cbae948-fdca-11e6-9f16-aac824e80bcd.png)

**Comment by enzyme69** [comment]
The n=2 seems to fix the weird thing that it does not accept Int Input.

**Comment by enzyme69** [comment]
@zeffii If you want to add something? I guess since LAMP can be generated this way, many other objects can also be generated like this.

**Comment by zeffii** [comment]
I could add a library function to abstract most of that away,  but am glad I didn't yet - looks like it was a learning experience

**Comment by enzyme69** [comment]
Cool! Surprisingly, it takes a very small effort (sometimes) to get the cool functionality. Well, I know this is still trivial, but .... next I want to try using Python to generate and connect nodes.

**Comment by zeffii** [comment]
> The n=2 seems to fix the weird thing that it does not accept Int Input.

Thanks, i'll correct the examples :)  ( see the next example in the SNLite thread where the script takes matrices to generate empties instead. )

the n parameter is just a _nesting index_, it's not _weird_. It's the result of our list nesting feature. (Exactly the strength of Sverchok). Possibly best imagined like this.

![image](https://cloud.githubusercontent.com/assets/619340/23399114/639cdc34-fd9f-11e6-8aa2-0238f2020373.png)

**Comment by kalwalt** [comment]
@zeffii we should add this picture in the doc!

**Comment by zeffii** [comment]
agreed ill add
