### ISSUE TITLE
Scientific Visualization: Colorizing 3D Mesh 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1278]
We can already do this sort of thing right?
https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Mesh/ColorMesh

Vertex Color and then somewhat 3D Gradient Ramp.

But not as clear cut.

I imagine Blender Cycles Material as well, but the limitation of Cycles from getting outside data annoys me. Although Attribute node can be used.

**Comment by zeffii** [comment]
knowing what you know.. i'm surprised that you ask this question here.

**Comment by enzyme69** [comment]
Sorry, I will close, I shall ask at Blender Stack Exchange~

**Comment by enzyme69** [comment]
![screen shot 2017-02-28 at 23 33 02](https://cloud.githubusercontent.com/assets/3952687/23405424/456d6dfe-fe0e-11e6-98da-ee1ed4b8c56f.png)

https://gist.github.com/f4ec13c65668edb163dbbae9af3d6a9d
