### ISSUE TITLE
Blender 2.78C failed to load Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1279]
```python
Traceback (most recent call last):
  ....
  File "sverchok-master/utils/sv_update_utils.py", line 19, in <module>
    import requests
ImportError: No module named 'requests'
```

**Comment by zeffii** [comment]
that might be an osx specific thing..  Python compiled for osx without requests module?

if you go to text editor and try to run `import requests` that should work.. else you should file a bug report.. or see if one has been filed on blender.org already. probably has.

**Comment by zeffii** [comment]
```python
import requests

print(requests.__title__, requests.__build__)
```
should print something like
```text
requests 135168
```

**Comment by zeffii** [comment]
if that prints an Exception or error.. please close this Issue and file a report on https://developer.blender.org/

**Comment by portnov** [comment]
2.78*c* changelog for reference: https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.78/Performance_update2

**Comment by portnov** [comment]
does not reproduce on 2.78c linux build (I downloaded linux x64 build as tar.bz2).

**Comment by zeffii** [comment]
also works in win64.

**Comment by zeffii** [comment]
people are talking about on IRC / #blendercoders now.  osx's python has no requests module

**Comment by zeffii** [comment]
probably @enzyme69  the foundation will release the osx installers again using the same `.zip  2.78c` , that's what they said anyway.. i didn't stay around for long.

**Comment by enzyme69** [comment]
ok then, B should ok

**Comment by zhaozj89** [comment]
@enzyme69 , how did you deal with it? I face the same problem. Thanks.

**Comment by zeffii** [comment]
@zhaozj89 get a more recent build for osx :  https://builder.blender.org/download/
