### ISSUE TITLE
Sorting and Index and Vertex Color

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1283]
I have a big confusion here on a case of SORTING based on Key Distance, Random Values, for Color.

I am able to SORT based on the Center of Region of Maps, however, using that same Key, I am unable to sort Color Sequence Gradient.

[map_vis_part_two_011_2017_03_01_12_50.zip](https://github.com/nortikin/sverchok/files/810737/map_vis_part_two_011_2017_03_01_12_50.zip)

This is a bit hard to explain, unless you check my latest Live Noding video:
https://www.youtube.com/watch?v=2DXxix5ZmY4

**Comment by enzyme69** [comment]
![screen shot 2017-03-01 at 23 50 34](https://cloud.githubusercontent.com/assets/3952687/23460587/2b339b26-feda-11e6-8e27-e252e00aaaef.png)

I don't think the color is sorted.

**Comment by enzyme69** [comment]
This is another version, before I separated the Curve -> Mesh and Mesh to Color.

My fear is that Object BMesh out and Objects In is again sorting the list. 
[map_vis_part_two_009_2017_03_01_12_53.zip](https://github.com/nortikin/sverchok/files/810745/map_vis_part_two_009_2017_03_01_12_53.zip)

**Comment by enzyme69** [comment]
I tried with a simpler setup, similar to above. Seems to work. But on the map, I am not 100% sure.

[map_vis_part_two_009_2017_03_01_12_53.zip](https://github.com/nortikin/sverchok/files/810780/map_vis_part_two_009_2017_03_01_12_53.zip)

![screen shot 2017-03-02 at 00 08 21](https://cloud.githubusercontent.com/assets/3952687/23461063/5e58503a-fedc-11e6-8ab0-a646701d1a35.png)

**Comment by enzyme69** [comment]
As soon as I started to duplicate the original Curves Circles, and updating the whole thing... I can see sorting issue.

![screen shot 2017-03-02 at 00 10 50](https://cloud.githubusercontent.com/assets/3952687/23461142/c56902c4-fedc-11e6-8a90-fa6241a66e15.png)

**Comment by enzyme69** [comment]
Even just plugging the distance (mapping values) directly does not work as expected. 

[sorting_things_005_2017_03_01_13_19.zip](https://github.com/nortikin/sverchok/files/810804/sorting_things_005_2017_03_01_13_19.zip)

**Comment by zeffii** [comment]
what kind of sorting are you looking for?

**Comment by enzyme69** [comment]
What would be nice is to get "index" number based on the List Sort, just like Index Viewer is showing. 

Totally confused.

**Comment by enzyme69** [comment]
@zeffii Sorting or Mapping based on:
- Distance to Empty
- Number assigned to each point region
- etc

**Comment by enzyme69** [comment]
I am looking at List Sort and KEY. The KEY is the Distance, so I think logically this setup should work, but apparently not/

**Comment by zeffii** [comment]
please describe this problem using fewer nodes.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23461651/0bff5e42-fe8b-11e6-9d05-b6a96b201d47.png)

**Comment by enzyme69** [comment]
I will continue tomorrow, since it is bed time :) but yeah, I guess this should be straight forward, I am just not sure about sorting and whether Object In or BMesh Out is automatically doing sorting causing everything to get confusing.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23462215/32e55352-fe8d-11e6-8731-7345f1d790a3.png)

https://gist.github.com/076e23ec0fedd7cee7cc8f80558a72e2

**Comment by zeffii** [comment]
seems to me like you could be asking these how-to questions on BSE, and if it turns out that the answers are all more complicated that they should be conceptually, then ask an issue on the issue-tracker here -- because then it's about add/modifying code to make sverchok better.

I think it would be a great boost to the community if you did that, you ask the most questions here..but really we should using BSE for the exchange of knowledge / and keep the issue tracker for discussing features and code. 

Warning.. before posting on BSE, have a good think about the question first - people there are harsh if they perceive the question to be unclear.

**Comment by zeffii** [comment]
>   I am unable to sort Color Sequence Gradient.

try to be clearer there. isn't Color a function of something else? try sorting on that other thing.

**Comment by enzyme69** [comment]
I am asking here because it is possible that there is a bug or confusion. I can close this or asking at BSE, but that will be so confusing too. 

I can SORT and can see the Index Viewer is correctly sorted based on distance. However, when I use List Sort and KEY for other data, I don't seem to get the same result.

And if I can sort the Index correctly, why is sorting other DATA is not as simple? 

Hoping it can be clearer or maybe the node can be enhanced to include option to use Index to sort.

**Comment by enzyme69** [comment]
Maybe I was asking the question wrong.

**Comment by zeffii** [comment]
because not all data is nested in the same way. so you must adjust levels to tell the node how far you want to 'zoom out' .

**Comment by zeffii** [comment]
make a small set of sample data that you can see one one screen ..  so you really understand the data,  

for example:
- 3 circles with 3 verts each, all using different radii   ---> data
- the edges from these circles                            ---> data

and then try to sort it using some kind of key sequence. These won't be sorted by the same 'level'.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23484484/7b5035d6-fed7-11e6-88c3-39ffe6d561e3.png)
always debug your brain with the smallest amount of data.

**Comment by enzyme69** [comment]
I like that concept of zooming in and zooming out of data to scope the
Levels. I will investigate. Thanks Zeff sorry for your time.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
When I figure out it will be facepalms.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
