### ISSUE TITLE
using .hide on sockets (pros/cons/possible resolution)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1285]
sparked by https://github.com/nortikin/sverchok/pull/1271 but used in several nodes
- [create_bvh_tree.py](https://github.com/nortikin/sverchok/blob/d37532f5777292a12872e4e8115848d6371b85fc/nodes/scene/create_bvh_tree.py)
- [vector_polar_out.py](https://github.com/nortikin/sverchok/blob/afef289579753820008e2749a670545ead24b402/nodes/vector/vector_polar_out.py)
- [objects_along_edge.py](https://github.com/nortikin/sverchok/blob/021979e956ffd5390fd658bd1caa1af8ca299a36/nodes/modifier_change/objects_along_edge.py)
- [mesh_filter.py](https://github.com/nortikin/sverchok/blob/021979e956ffd5390fd658bd1caa1af8ca299a36/nodes/analyzer/mesh_filter.py)

and 3 or 4 more maybe.

the use of `.hide` on sockets has been very sparse and mostly has crept in under the radar. The point of this issue is to discuss and resolve the issue preventing us from using this feature (or similar custom `.hide_safely` implementation) .

### cons on `.hide`

- hidden sockets don't drop their links automatically, meaning the node can be getting more calls to process from upstream nodes than a user might realize ( testable )
- (bad reason but a reason nonetheless) iojson doesn't store socket properties , gists won't work flawlessly out of the box.

### cons on `.remove`

- it's quite the headache to implement remove/add upon mode switch, certainly compared to simply .hide.
- depending on how `process` is written can require extra sanitizing to see if a socket exists.

### Resolution

There are any number of routes, and one, some or _all_ might be needed.
-  to solve the iojson issue, 
    - It would be worth adding socket properties to iojson to keep code like this simpler
        - also some sockets use `.prop_type` (or something) which we don't track yet either.
    - don't track links between hidden sockets
- to solve calls to process, links on a hidden socket could be ignored and not cause triggers to flow to that node (unless it has other connected sockets of course)
- Maybe we add a `.hide_safe` to the socket class, that auto unlinks hidden socket.links.

@ly29 anything to add or is the restriction on .hide cargocult, it's been a while since I looked the DAG

**Comment by ly29** [comment]
@zeffii 
I don't remember actually if what will happen. I prefer not to add complexity or spend time messing with the overly complicated update system...
From a conservative standpoint I vote no.

**Comment by zeffii** [comment]
The least impact would be a two-parter i think..

- add a `.hide_safe`, that force-disconnects links. ( in / out / to reroute node )
- deal with the iojson to store info about the sockets,  `.hide` / `.prop_type`

**Comment by zeffii** [comment]
yikes.. 
- one one node the socket will remain visible if it's hidden, but connected
- on another node (mesh filter ) the socket is disconnected
(without looking at their implementation i don't know what's going on)

**Comment by zeffii** [comment]
hmmm https://developer.blender.org/rB2db71782e750313fc2c7d0a420e0fab6e06e38d4

**Comment by zeffii** [comment]
### ...in conclusion 

- we can probably allow `.hide`, but offer `.hide_safe` as a wrapper to ensure the socket is unlinked before hidding. I suspect this hasn't been a massive issue because the few nodes that do use the feature don't get used much in gists :)

- iojson will need to store the .hide and .prop_type, for any node that uses them. ( i/o version bump )

No ETA. so expect broken gists with those nodes until i get around to it.
