### ISSUE TITLE
is_linked modus operandum

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1292]
Is the test is_linked done on output sockets (in order to only compute things that are needed/used) actually checking whether the outputs of a node are effectively used to some end ? Just having a node output socket connected to another node which is not doing anything with that input is NOT enough of an indication data needs to be computed for that output socket. The ultimate resolution to this "should data be computed for an output socket" question is to find out by traversing the node hierarchy connected to that output and query the nodes whether they produce anything with the input they receive (directly or indirectly) from that output socket (e.g. Do they print something on the screen or do they generate/alter mesh or do they manipulate anything at all). Such a hierarchical test would make sure no computation is done for anything that is not effectively used. 

Perhaps an output.is_needed() or output.is_used() could do such node traversal checking.

**Comment by zeffii** [comment]
> traversing the node hierarchy connected to that output and query the nodes whether they produce anything with the input they receive (directly or indirectly) 

not worth the effort. also it assumes that the output of a node downstream isn't read by some other pynode tree (ie not physically connected). We talked about this as team-sverchok a while back.. maybe i'll find the thread .

**Comment by zeffii** [comment]
here's one related issue, https://github.com/nortikin/sverchok/issues/1173
but there are more.

**Comment by ly29** [comment]
Apply the kiss principle.
If you don't use something don't link it. The link is the semantic information. Sure further compiler optimization can be done but to be honest, if you look into how this works there are so much stupid things going on it simple doesn't make sense to add the complexity on a node level. Some nodes like plane where the polygon output is very heavy could/should be refactored into but in general no.

Consider a node to be a function in a functional programming framework and not some kind OO object doing inquirers and looking into what happens.
