### ISSUE TITLE
List length display OR Stethoscope input length display

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1294]
Often time i want to see the length of an output list and to do that I have to add a List Length node and a Stethoscope length. Should we make it so that either the List Length node itself displays the length of the node the same way as the Stethoscope does, or enhance the stethoscope to also display the length of the list (or lengths of the nested lists) aside from displaying the lists. This could be added as an extra button you can toggle on/off to display the list length info. 

![sv-listlengthinfo](https://cloud.githubusercontent.com/assets/2083719/23531480/96aa1872-ff74-11e6-8798-e576193ae7cb.png)

**Comment by kalwalt** [comment]
Did you see the sthetoscope MK2? it also output the length, or maybe you need something more precise?

**Comment by zeffii** [comment]
I encourage any sane augmentations to stethoscope MK2.

**Comment by zeffii** [comment]
closing, seen as mk2 does do this already.
