### ISSUE TITLE
Is there a node to create both inset & outset ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1295]
The inset node can create inset or outset but not both. I’m after turning a circle into a circle band (centered ON the circle line). Basically, for the “flower of life" patterns (generated with the hexa grid) I would like to create thick circle lines that I can render. I don’t want to skinny the mesh which makes a tube around the edges since I don’t care about the 3D lines (and i want to keep the triangle count to a minimum); I only need to render the 2D circle patterns. So, I thought that I could use a node like inset to do the job, but the inset moves the circle radius either in or out, which is why i need the inset node to do both In  & Out around the edge (like in the image below).  I could augment the Inset node to do this if that’s ok. And if the node is updated I also think that the “mask inner” should be made an input socket in its full rights so I don’t have to attach an int node just to set it. Any thoughts ?

The node tree in the screenshot does not actually solve my problem; just illustrating the outcome i’m after.
![sv-insetoutset-example](https://cloud.githubusercontent.com/assets/2083719/23535515/bd493108-ff8c-11e6-9c90-53adf1368a08.png)

**Comment by zeffii** [comment]
1. I agree inset specials should have those properties on the node, i'll add them.
2. Augmenting the node? Make it a separate node first. 

Also see 
![image](https://cloud.githubusercontent.com/assets/619340/23543805/2dc055d0-fff4-11e6-9324-a7523a0a7ab0.png)

- consider adding a `2d_donut` to `utils.geom` ( closely related function is _arc_slices_ ) , 
- consider a 2d mode to the donut node :) so we pass it only radius and thickness and it outputs VEP.

A while back i sank some time into a generalized 2d solution to go from edgenet to edgenet with thickness, it was never completed - i might have another stab at it :)  https://github.com/nortikin/sverchok/issues/623

![img](https://cloud.githubusercontent.com/assets/619340/7418615/61d52cca-ef6f-11e4-8a2c-864d76b22a1c.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23544336/e8bcc11e-fff6-11e6-8038-91d9299404ef.png)
sadly this only outputs one set of VEP, a dedicated 2d donut is definitely on the cards (if you won't, I will )

**Comment by zeffii** [comment]
... or a circle MK2 . with thickness value, thickness 0 just outputs as normal, any positive thickness value would generate the 2d donut.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23544925/504c42b2-fff9-11e6-947b-29e5179931a7.png)

**Comment by enzyme69** [comment]
Can be great for some kind of LEVEL design.

**Comment by DolphinDream** [comment]
I like the EdgeNet idea..which is more general and would work for any type of mesh/edges not just the symmetrical circle/cylinder. For what I need @zeffii’s solution is good, though a circle or 2D_torus node would be better. A 2D torus would be natural though since you could provide the inner and outer radius, or major/minor radius. I can do this actually since I did the 3D torus and the UI infrastructure is half way there. Should the 3D torus have a 2D mode instead of creating a separate node, btw?

**Comment by zeffii** [comment]
that's up to you, but it's nice to have single purpose nodes - their code is less hectic. `donut_2d.py` for generators extended 

  - mode 1:  circle radius / circle width
  - mode 2:  inner circle radius / outer circle radius
  - mode 1+2:  num_verts (not segments..ie faces)  / phase start

**Comment by zeffii** [comment]
back to the main question of this issue, a inset outset. node

I'm for a two mode node on this  (at least two nodes)
- general "add thickness to 2d edge net " ( based on XY plane , as show above )
   - in verts 
   - in edges
   - in polygons (but poly data will be stripped to edges)
- general "generate inset/outset of each polygon"
   - in verts
   - in polys
   - in mask to omit faces
   - in (optional) edge ring count per face (vectorized)

**Comment by zeffii** [comment]
closing until there's movement again on it.
