### ISSUE TITLE
Float / Int input node to pass through, if linked

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1296]
A good.
![image](https://cloud.githubusercontent.com/assets/619340/23544967/747965fc-fff9-11e6-913f-9a734f7adf33.png)

A bad
![image](https://cloud.githubusercontent.com/assets/619340/23544992/95a398a6-fff9-11e6-84b2-2192cc614620.png)

**Comment by DolphinDream** [comment]
Where’s the “ugly” ? :)

**Comment by zeffii** [comment]
The ugly? the code of Int and Float input :) I very much want to combine those nodes..

**Comment by zeffii** [comment]
```python
    def process(self):
        # inputs
        Float = min(max(float(self.inputs[0].sv_get()[0][0]), self.minim), self.maxim)
        # outputs
        self.outputs['Float'].sv_set([[Float]])
```
becomes
```python
    def process(self):
        inputs, outputs = self.inputs, self.outputs

        if inputs[0].is_linked:
            outputs['Float'].sv_set(inputs[0].sv_get())
        else:
            Float = min(max(float(inputs[0].sv_get()[0][0]), self.minim), self.maxim)
            outputs['Float'].sv_set([[Float]])
```

**Comment by zeffii** [comment]
but because it's such a fundamental node, probably don't want to "Fix" this in the same file where some .blends may rely on the existing behaviour.

**Comment by zeffii** [comment]
it'll be a new node, two modes int/float
