### ISSUE TITLE
Mesh Join tiny update

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1298]
still there is a scenario where Verts+PolEdge in is needed but Verts in _alone_ should be fine.

![image](https://cloud.githubusercontent.com/assets/619340/23549906/9ba9e10a-000e-11e7-8aea-23e91983cf62.png)

**Comment by DolphinDream** [comment]
Wouldn’t this work without the Matrix In node? I often time see this node being used between the vertex output and the viewer node, but i noticed that plugging vertex right into the viewer’s matrix node works too . Does the socket do some sort of auto conversion?

**Comment by zeffii** [comment]
> Wouldn’t this work without the Matrix In node? 

sure, i _added_ the Vertex to Matrix converter only a couple of months ago. In the case of this example I want to scale those circles too but didn't remove the node for the screenshot.

**Comment by zeffii** [comment]
maybe..
```python
    def process(self):
        Vertices, PolyEdge = self.inputs
        Vertices_out, PolyEdge_out = self.outputs

        if Vertices.is_linked:
            verts = Vertices.sv_get()
            poly_edge = PolyEdge.sv_get(default=[[]])

            if PolyEdge.is_linked:
                verts_out, _, poly_edge_out = mesh_join(verts, [], poly_edge)
                PolyEdge_out.sv_set([poly_edge_out])
            else:
                verts_out = []
                _ = [verts_out.extend(vlist) for vlist in verts]
                
            Vertices_out.sv_set([verts_out])
```

**Comment by zeffii** [comment]
done

**Comment by portnov** [comment]
It would be nice to have a wiki page comparing Turbulence, Vector Fractal and Vector Noise nodes...

**Comment by kalwalt** [comment]
> t would be nice to have a wiki page comparing Turbulence, Vector Fractal and Vector Noise nodes.

@portnov I would do, i'm also preparing a tutorial on Noise inspired by [the book of shaders](https://github.com/patriciogonzalezvivo/thebookofshaders) the wiki will be the ideal place.
