### ISSUE TITLE
Cut at branching algorithm

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1301]
It's an idea that was accidentally appears, I thought it might be a good study for myself, I want to be smarter.
https://github.com/nortikin/sverchok/pull/1293#issuecomment-283945797

Might create BLEND with simple single branch.

The problem:
To do opposite of Remove Doubles, especially for tree branching, etc. To cut and separate edges with repeating index. To separate branching structure, if they meet at one point.

**Comment by zeffii** [comment]
start by using images to explain the problem, a before and after.

**Comment by zeffii** [comment]
before:
![image](https://cloud.githubusercontent.com/assets/619340/23585901/e567fe54-0189-11e7-99e1-5f24f4405ac6.png)
after:
![image](https://cloud.githubusercontent.com/assets/619340/23585904/ecf3241e-0189-11e7-92e5-89ee0b9c7b25.png)
(essentially the reverse of remove doubles: https://github.com/nortikin/sverchok/issues/898#issuecomment-251962041  )

**Comment by zeffii** [comment]
the extra complexity will be in ordering the vertex indices of the disjoint elements (there is a topological sort in Nortikins/Script nodes "sort for profile .." ) but you'll want to sort from the vertex that was once shaired.. probably.

**Comment by enzyme69** [comment]
I remembered we have "Polygon To Edge" or a method in Blender Modifier that make point intersection unique, if the angle is more than X.
