### ISSUE TITLE
Intersect Edges fails on large 4k+ BU grid test

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1302]
![screen shot 2017-03-05 at 22 22 59](https://cloud.githubusercontent.com/assets/3952687/23586855/662fa1aa-01f2-11e7-88d8-f825d4746ed0.png)

I am testing Intersect Edges MK2 for this horizontal and vertical lines:

https://gist.github.com/9129164a7001054518b5787ff46b00e4

Somewhat the output is not as expected. Wonder where I did wrong.

**Comment by enzyme69** [comment]
If I bake those lines and scale them down, somewhat Intersect Edges works! There must be a hidden attribute here.

![screen shot 2017-03-05 at 22 27 27](https://cloud.githubusercontent.com/assets/3952687/23586882/fc6118a2-01f2-11e7-96cc-0e73a4efd4da.png)

@zeffii Any idea?

**Comment by zeffii** [comment]
i'll have a look

**Comment by zeffii** [comment]
it looks like a precision issue, scale it down.  not much i can do here..

**Comment by zeffii** [comment]
The tool is design for operating with much smaller values, like.. < 10 meter geometry. (based around the regular grid, with 5 decimal places precision). I could add a toggle to autodetect scale which you'd switch on if you realize it's not cutting.  so it would scale down internally, and do the cutting, then scale back up before returning.

**Comment by zeffii** [comment]
if one of your dimensions has a span of (5 * 820) = > 4k.

The limits of the 32bit float precision are around 5/6 positions..
```
4000.00
4000.000
```
the intersections on these lines probably happens deeper down
```
4000.00000<here>
```
and that falls outside of what can be expected from 32 bit float.

**Comment by zeffii** [comment]
i'll have a think about this.

**Comment by zeffii** [comment]
well.. a scan to automatically set the Epsilon isn't going to happen, but i'll add a draw_buttons_ext with a precision slider in the near future.
