### ISSUE TITLE
Mesh evaluate node  / Mesh Expression 

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#1304]
Initial idea.
To create useful meshes, it would be nice to get a mesh modelled "by hand", and parametrize it.

Proposed implementation.
Step 1: get selected mesh object and store it, for example, in JSON format (dict with "vertices", "edges" and "faces" keys).
Step 2: replace some numbers in "vertices" list with variable names.
Step 3: load resulting JSON and plug variable values as node inputs.

Initial implementation is in https://github.com/portnov/sverchok/tree/mesh_from_json.

**Comment by portnov** [comment]
![eval_1_screen](https://cloud.githubusercontent.com/assets/284644/23589735/dbab6f2c-01fc-11e7-9ea1-3a208b725024.png)

**Comment by zeffii** [comment]
oh cool!!  did you check _object_in_lite_ ?  stores a single mesh in json/restores from json in gist.

**Comment by portnov** [comment]
Yes, probably that feature will be needed too.

**Comment by portnov** [comment]
@zeffii 
I have a question about evaluating expressions in Profile node and similar (for example, Formula node). Do we really need own parser and evaluator? Can't we use smth like http://effbot.org/zone/librarybook-core-eval.htm ?

**Comment by zeffii** [comment]
it's up to you @portnov , but try to avoid external modules.. or make a platform independent way to ensure a module's availability if it's not part of std.

**Comment by portnov** [comment]
@zeffii 
Python has builtin eval() function, so we could use it with several precautions. But it is possible for "hacker" to use it for some "evil" things. I.e. one can run "rm -rf ~/*" with it. 
I'm trying to understand, why we implemented own parser in Profile node? Is it for security reasons?

**Comment by portnov** [comment]
![output1](https://cloud.githubusercontent.com/assets/284644/23673219/994c9822-039b-11e7-93f4-48aa44597a80.gif)

**Comment by zeffii** [comment]
Write a DSL then @portnov.

we use eval/exec in several nodes, do a search in the repo :)  We also discussed the dangers a long time ago.

**Comment by zeffii** [comment]
> why we implemented own parser in Profile node?

profile node, i like writing parsers :)

**Comment by portnov** [comment]
Ok
Currently I'm using python's ast+eval for parsing/evaluating expressions, and a simple trick with passing __builtins__ = {} in environment, and restricted number of "safe" functions, to be more or less secure.

**Comment by enzyme69** [comment]
@portnov I tried this node. It gives me nothing.

I kind of expect the output of this node to work with Text In JSON.

**Comment by portnov** [comment]
@enzyme69 
please provide json that you tried and it did not work.

Later today I can provide some examples that are working for me.

And yes, this node obviously needs documentation. I hope to write it this week.

**Comment by portnov** [comment]
@enzyme69 
Trivial plane example:
```

{
  "faces": [
    [
      0,
      1,
      3,
      2
    ]
  ],
  "edges": [
    [
      0,
      2
    ],
    [
      0,
      1
    ],
    [
      1,
      3
    ],
    [
      2,
      3
    ]
  ],
  "vertices": [
    [
      "-Size",
      "-Size",
      0.0
    ],
    [
      "Size",
      "-Size",
      0.0
    ],
    [
      "-Size",
      "Size",
      0.0
    ],
    [
      "Size",
      "Size",
      0.0
    ]
  ]
}
```

Nontrivial example:

```
{
  "vertices": [
    [
      -1.0,
      -1.0,
      -1.0
    ],
    [
      -1.0,
      -1.0,
      "Center"
    ],
    [
      -1.0,
      1.0,
      -1.0
    ],
    [
      -1.0,
      1.0,
      "Center"
    ],
    [
      1.0,
      -1.0,
      -1.0
    ],
    [
      1.0,
      -1.0,
      "Low"
    ],
    [
      1.0,
      1.0,
      -1.0
    ],
    [
      1.0,
      1.0,
      "Low"
    ],
    [
      -1.0,
      0.0,
      -1.0
    ],
    [
      -1.0,
      0.0,
      "Center"
    ],
    [
      1.0,
      0.0,
      -1.0
    ],
    [
      1.0,
      0.0,
      "Low"
    ],
    [
      -1.0,
      -0.5,
      -1.0
    ],
    [
      1.0,
      -0.5,
      "Low"
    ],
    [
      -1.0,
      -0.5,
      "Center"
    ],
    [
      1.0,
      -0.5,
      -1.0
    ],
    [
      -1.0,
      0.5,
      "Center"
    ],
    [
      1.0,
      0.5,
      -1.0
    ],
    [
      -1.0,
      0.5,
      -1.0
    ],
    [
      1.0,
      0.5,
      "Low"
    ],
    [
      0.5,
      1.0,
      -1.0
    ],
    [
      "A",
      1.0,
      "0.25*Center + 0.75*Low"
    ],
    [
      0.5,
      -1.0,
      -1.0
    ],
    [
      "A",
      -1.0,
      "0.25*Center + 0.75*Low"
    ],
    [
      "A",
      0.0,
      "0.25*Center + 0.75*Low"
    ],
    [
      0.5,
      0.0,
      -1.0
    ],
    [
      "A",
      -0.5,
      "0.25*Center + 0.75*Low"
    ],
    [
      0.5,
      -0.5,
      -1.0
    ],
    [
      0.5,
      0.5,
      -1.0
    ],
    [
      "A",
      0.5,
      "0.25*Center + 0.75*Low"
    ],
    [
      -1.0,
      -0.5,
      "Center+H2"
    ],
    [
      -1.0,
      0.0,
      "Center+H2"
    ],
    [
      -1.0,
      0.5,
      "Center+H2"
    ],
    [
      "A",
      0.0,
      "0.25*Center + 0.75*Low+H2"
    ],
    [
      "A",
      -0.5,
      "0.25*Center + 0.75*Low+H2"
    ],
    [
      "A",
      0.5,
      "0.25*Center + 0.75*Low+H2"
    ]
  ],
  "edges": [
    [
      0,
      12
    ],
    [
      0,
      1
    ],
    [
      3,
      16
    ],
    [
      2,
      3
    ],
    [
      2,
      20
    ],
    [
      7,
      21
    ],
    [
      6,
      7
    ],
    [
      6,
      17
    ],
    [
      5,
      13
    ],
    [
      4,
      5
    ],
    [
      4,
      22
    ],
    [
      1,
      23
    ],
    [
      8,
      18
    ],
    [
      9,
      14
    ],
    [
      10,
      15
    ],
    [
      11,
      19
    ],
    [
      11,
      24
    ],
    [
      8,
      25
    ],
    [
      10,
      11
    ],
    [
      8,
      9
    ],
    [
      8,
      12
    ],
    [
      11,
      13
    ],
    [
      1,
      14
    ],
    [
      4,
      15
    ],
    [
      12,
      14
    ],
    [
      13,
      26
    ],
    [
      12,
      27
    ],
    [
      13,
      15
    ],
    [
      9,
      16
    ],
    [
      10,
      17
    ],
    [
      2,
      18
    ],
    [
      7,
      19
    ],
    [
      17,
      19
    ],
    [
      18,
      28
    ],
    [
      19,
      29
    ],
    [
      16,
      18
    ],
    [
      6,
      20
    ],
    [
      3,
      21
    ],
    [
      0,
      22
    ],
    [
      5,
      23
    ],
    [
      26,
      34
    ],
    [
      10,
      25
    ],
    [
      14,
      26
    ],
    [
      15,
      27
    ],
    [
      17,
      28
    ],
    [
      16,
      29
    ],
    [
      21,
      29
    ],
    [
      20,
      28
    ],
    [
      25,
      27
    ],
    [
      24,
      26
    ],
    [
      25,
      28
    ],
    [
      24,
      29
    ],
    [
      23,
      26
    ],
    [
      22,
      27
    ],
    [
      22,
      23
    ],
    [
      20,
      21
    ],
    [
      30,
      31
    ],
    [
      31,
      32
    ],
    [
      31,
      33
    ],
    [
      30,
      34
    ],
    [
      32,
      35
    ],
    [
      33,
      34
    ],
    [
      33,
      35
    ],
    [
      14,
      30
    ],
    [
      29,
      35
    ],
    [
      24,
      33
    ],
    [
      16,
      32
    ],
    [
      9,
      31
    ]
  ],
  "faces": [
    [
      18,
      16,
      3,
      2
    ],
    [
      20,
      21,
      7,
      6
    ],
    [
      15,
      13,
      5,
      4
    ],
    [
      22,
      23,
      1,
      0
    ],
    [
      27,
      15,
      4,
      22
    ],
    [
      26,
      14,
      1,
      23
    ],
    [
      24,
      29,
      35,
      33
    ],
    [
      28,
      17,
      10,
      25
    ],
    [
      17,
      19,
      11,
      10
    ],
    [
      12,
      14,
      9,
      8
    ],
    [
      0,
      1,
      14,
      12
    ],
    [
      14,
      26,
      34,
      30
    ],
    [
      25,
      10,
      15,
      27
    ],
    [
      10,
      11,
      13,
      15
    ],
    [
      6,
      7,
      19,
      17
    ],
    [
      20,
      6,
      17,
      28
    ],
    [
      21,
      3,
      16,
      29
    ],
    [
      8,
      9,
      16,
      18
    ],
    [
      7,
      21,
      29,
      19
    ],
    [
      2,
      20,
      28,
      18
    ],
    [
      8,
      25,
      27,
      12
    ],
    [
      11,
      24,
      26,
      13
    ],
    [
      18,
      28,
      25,
      8
    ],
    [
      19,
      29,
      24,
      11
    ],
    [
      13,
      26,
      23,
      5
    ],
    [
      12,
      27,
      22,
      0
    ],
    [
      4,
      5,
      23,
      22
    ],
    [
      2,
      3,
      21,
      20
    ],
    [
      35,
      32,
      31,
      33
    ],
    [
      33,
      31,
      30,
      34
    ],
    [
      26,
      24,
      33,
      34
    ],
    [
      29,
      16,
      32,
      35
    ],
    [
      16,
      9,
      31,
      32
    ],
    [
      9,
      14,
      30,
      31
    ]
  ]
}
```

**Comment by portnov** [comment]
ouh... probably I should better put it to gist.

**Comment by enzyme69** [comment]
Any JSOn did not work in Viewer, I tried, not sure if I should pull git.

-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by portnov** [comment]
@enzyme69 
Maybe the problem is that you did not connect anything to inputs? The node currently needs all inputs (variables) to be connected; you can for example plug Float nodes.

**Comment by nortikin** [comment]
Спасибо за узел, не хватало его
Thanks for Uzel, ne hvatalo ego

**Comment by zeffii** [comment]
the node should really be in extended generators, i think..

**Comment by zeffii** [comment]
also, to make it clearer to the user that the node has indeed read the json, i think it makes sense to wrap the updateNode function attached to `self.filename` , to do a `self.adjust_inputs()` -- else sockets aren't added until the user clicks a socket somewhere..

**Comment by enzyme69** [comment]
![screen shot 2017-03-16 at 22 46 40](https://cloud.githubusercontent.com/assets/3952687/23994742/751c19b8-0a9a-11e7-949c-832f7ecbccf5.png)

Hmmmm.... no input slot to connect to.

**Comment by enzyme69** [comment]
And I tried your JSON:

Traceback (most recent call last):
  File "/Users/jimmygunawan/bsscript/addons/sverchok/utils/sv_IO_panel_tools.py", line 855, in execute
    import_tree(ng, nodes_json=nodes_json)
  File "/Users/jimmygunawan/bsscript/addons/sverchok/utils/sv_IO_panel_tools.py", line 650, in import_tree
    generate_layout('', nodes_json)
  File "/Users/jimmygunawan/bsscript/addons/sverchok/utils/sv_IO_panel_tools.py", line 611, in generate_layout
    print('#' * 12, nodes_json['export_version'])
KeyError: 'export_version'

location: <unknown location>:-1

**Comment by zeffii** [comment]
1. insert the json into the text editor
2. locate it file the file selector on the MeshEvalNode
3. click any socket.
4. correct socketset will appear, you can now connect the output of the node to viz

**Comment by enzyme69** [comment]
Ok I got it! I keep hitting "from selection" and if I don't have any input it does not generate anything.

**Comment by zeffii** [comment]
ok.

**Comment by zeffii** [comment]
1. insert the json into the text editor
2. locate it with the file selector on the MeshEvalNode
3. click any socket.
4. correct socket-set will appear, you can now connect the output of the node to viz

**Comment by enzyme69** [comment]
![screen shot 2017-03-16 at 22 52 45](https://cloud.githubusercontent.com/assets/3952687/23994941/4bae78e0-0a9b-11e7-8058-cebe971a7a6a.png)

**Comment by enzyme69** [comment]
However, it would be nice if we can have this Mesh Evaluate Node to pass
Mesh Data even without any attribute. Cleaner.

But this is very cool and allows for lots of possibilities I cannot think
of.

**Comment by enzyme69** [comment]
It's also kind of unfortunate that it cannot accept "var" + 1, or ("var" * -1).

![screen shot 2017-03-17 at 10 41 46](https://cloud.githubusercontent.com/assets/3952687/24023175/a3314ff8-0afe-11e7-9a99-0cb4b8906f10.png)

I think this kind of Mesh Eval node can become like Intermediate node.

**Comment by portnov** [comment]
@enzyme69 
It accepts expressions, but they all should be enclosed in quotes. For example, "-1*a".

**Comment by enzyme69** [comment]
To my pleasant surprise, apparently MeshEval node, when exported out as GIST and imported back in, brings the whole Text JSON data with it!

The Text is no longer pretty JSON, it become a single line text, but I think that's ok for now. 

![screen shot 2017-03-17 at 18 52 19](https://cloud.githubusercontent.com/assets/3952687/24033836/f2a2ab56-0b42-11e7-8b1a-9717a8217a47.png)

**Comment by zeffii** [comment]
@enzyme69 
https://github.com/nortikin/sverchok/blob/master/nodes/generator/mesh_eval.py#L251

read the docs for [`json.dumps`](https://docs.python.org/3.5/library/json.html)

**Comment by zeffii** [comment]
@portnov  , you probably want store the mesh's json in Gists exactly as it appears in the datablock (regarding newlines), ..so flattened string, and restore from Gist using the string too.

**Comment by enzyme69** [comment]
@zeffii @portnov I tested both approach Objects In Lite - Text Out, and also MeshEvalNode. What would be nice:
- The JSON of both can work the same, currently they are spitting a very similar data, but not talking to each other. Supposedly Mesh Eval can hack into the data and add Variable on the fly. I assume.
- The JSON when brought back via GIST become not pretty, but I believe like Zeffii pointed out it is probably as simple as prettifying it back, maybe SV node can do it.

Thanks!

**Comment by zeffii** [comment]
All the mentioned nodes work complementary and have their own usecase.. the json edited with mesh eval doesn't make sense to load it with textin .

I do agree mesheval should not modify formatting when stored/retrieved in a gist., maybe even have a nicer initial formatting to begin with.

**Comment by portnov** [comment]
Well, I'll try to take notes in this thread into account and provide some fixes this weekend.

**Comment by portnov** [comment]
Please see #1387. :)

**Comment by portnov** [comment]
Dodecahedron:
https://gist.github.com/portnov/79630a99cc5d6fd549ef0124c4d243f1

So this node can be useful also to make primitives like this and share them. So for example we do not actually need "dodecahedron" node anymore :)

**Comment by zeffii** [comment]
makes me wish that items in the `defaults`  could reference other defaults already defined..

```json
{
  "defaults": {
     "A": 0.5773502588272095,
     "B": 0.35682210326194763,
     "C": 0.9341723322868347,
     "amp": 1.0
  },
  "vertices": [
    [  "A * amp",   "A * amp",    "A * amp"  ],
    [  "A * amp",   "A * amp",   "-A * amp"  ],
    [  "A * amp",  "-A * amp",    "A * amp"  ],
    [  "A * amp",  "-A * amp",   "-A * amp"  ],
    [ "-A * amp",   "A * amp",    "A * amp"  ],
    [ "-A * amp",   "A * amp",   "-A * amp"  ],
    [ "-A * amp",  "-A * amp",    "A * amp"  ],
    [ "-A * amp",  "-A * amp",   "-A * amp"  ],
    [  "B * amp",   "C * amp",    0.0        ],
    [ "-B * amp",   "C * amp",    0.0        ],
    [  "B * amp",  "-C * amp",    0.0        ],
    [ "-B * amp",  "-C * amp",    0.0        ],
    [  "C * amp",   0.0,          "B * amp"  ],
    [  "C * amp",   0.0,         "-B * amp"  ],
    [ "-C * amp",   0.0,          "B * amp"  ],
    [ "-C * amp",   0.0,         "-B * amp"  ],
    [  0.0,        "B * amp",     "C * amp"  ],
    [  0.0,       "-B * amp",     "C * amp"  ],
    [  0.0,        "B * amp",    "-C * amp"  ],
    [  0.0,       "-B * amp",    "-C * amp"  ]
  ],
  "edges": [  ],
  "faces": [
    [0,12,13,1,8],
    [0,8,9,4,16],
    [0,16,17,2,12],
    [8,1,18,5,9],
    [9,5,15,14,4],
    [4,14,6,17,16],
    [2,17,6,11,10],
    [2,10,3,13,12],
    [3,19,18,1,13],
    [5,18,19,7,15],
    [3,10,11,7,19],
    [6,14,15,7,11]
  ]
}
```

**Comment by zeffii** [comment]
can close this unless there's something else to be added

**Comment by rdrgodavi** [comment]
hey @enzyme69  , how can im trying to open your sushi vault ( https://github.com/enzyme69/blendersushi ) , but the .json doesnt open with the Mesh Expression node. How can i import those .json files corectly in SV and AN?﻿

**Comment by enzyme69** [comment]
@rdrgodavi which vault example? We can store Mesh as Mesh Expression and modify it by hand on the code, but which example is this? Try posting this question at my Github?
