### ISSUE TITLE
Edge Center / Edge Split node ? 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1305]
I know there is a polygon center node (a few of them) but I can’t seem to find a way to get the center of the  edges ? Should there be an Edge center node too? Is there any magic node that can give me these?

Alternatively maybe we can have an Edge Split node which allows you to split the edges anywhere inside the edge.. in the middle or in any “factor” position between 0 and 1 (closer to V1 or close to V2).

**Comment by DolphinDream** [comment]
Btw,  when you get an edge list input that comes as [[ [1,3], [3,4] ]] etc.. and read this and an input into an node, how do I get rid of the extra nestedness ? Or should I not get rid of it (in case the vectorization later on needs to rely on it?).

**Comment by zeffii** [comment]
the nested nature of the data makes vectorization possible, it's up to you whether you use it ..or stop looking after the first input list  (`.sv_get()[0]` = first list)

**Comment by DolphinDream** [comment]
Here’s an “Edge Split" node preview.

![edgesplit-preview](https://cloud.githubusercontent.com/assets/2083719/23591051/7b03334c-01b8-11e7-9a09-8fc5dcb2a823.png)

**Comment by zeffii** [comment]
make it split
```
| -----x---------------------------------x-----|
```
too :)

**Comment by zeffii** [comment]
i think there's a bmesh.ops now that makes this very simple

**Comment by DolphinDream** [comment]
What do you mean @zeffii ? Add two vertices on each edge? Is this for your edge net idea? :)

Btw, the node does not adjust the edges, simply generates vertices where the split position on each edge would be.

**Comment by DolphinDream** [comment]
Btw, is there a way to connect every vertex with every other vertex? Perhaps a combinatorial node would be nice to have.

**Comment by zeffii** [comment]
like edge split in 3dsmax has a mirror option, that splits the way i showed above. This is very useful for when we subdivide an edge based mesh as it allows consistent curvature/radius deformation where there

> Btw, the node does not adjust the edges, simply generates vertices where the split position on each edge would be.

oooh. i see - never mind then, it's easy enough to write script nodes for these things..

**Comment by zeffii** [comment]
kdtree edges can be used to connect everthing, but if you want pure topological 'fully connected' graph from all verts, then..no we don't have a node for that.   `itertools.combinations(iterable, r)` ,where r is 2 and iterable is the `list(range(len(verts))`

**Comment by DolphinDream** [comment]
@Zeffii so you don't think s node like this is useful ? It can be made similar to the polygon center node.

**Comment by zeffii** [comment]
i think you are talking about two nodes here? Nodes with too many functions is something I want to avoid, because that brings a new problem of naming the node. and the node internals tend to become very messy.

just because i don't have a need for a _fully connected graph_ node doesn't mean i'm against it..  it just means i'm not going to be excited about it.

**Comment by zeffii** [comment]
the `Exec Node Mod` is worth exploring for stuff that can be implemented in one or two lines of code
![image](https://cloud.githubusercontent.com/assets/619340/23591649/014f88a2-01f4-11e7-88de-158ebb7798a9.png)

**Comment by zeffii** [comment]
```
import itertools
append(list(itertools.combinations(range(len(V1[0])), 2)))
```
here append is aliased to the `out.append`

**Comment by DolphinDream** [comment]
@zeffii Sorry. I guess my follow up question about full connectivity created some confusion as to what node we are talking about. I was suggesting 2 nodes: one for edge centers (or more generalized edge split vertex node) similar to the polygon center nodes. The other was a node to create combinatorial operations on a set of vertices to allow two generate a **complete graph** type of connectivity (btw, a fully connected graph is not necessarily a complete graph). (note: your itertools example does create a complete graph though. thanks for the tip). The first node could be extended to do the type of mirroring you suggested and perhaps go beyond that and not just create the vertices on the edges, but also create the additional split edges. I’m not sure how to handle new polygons when the edges are split though and I was not going to tackle the polygons at all in this node, but it’s probably doable. The more i think about it though, an edge splitter that splits also polygons would be pretty much like a subdivide operation, except that an edge splitter that takes a splitting factor as an input can also determine where the subdivide (split) location on an edges will go. I believe blender’s subdivide op puts the split verts at the edge centers. 

As for the second node for combinatorics, I can’t see many uses for it either but it would be nice to have. I do need for something I was working on (e.g. generate the Metatron’s cube lines by fully connecting vertices on a cube)

![sv-metatron-cube-test](https://cloud.githubusercontent.com/assets/2083719/23593947/7cc4e5e2-01e3-11e7-8840-e133470f0ba5.png)

**Comment by DolphinDream** [comment]
And with the complete graph the MC is now complete :) 

btw.. the exec mode node is kewl 👍 .. Though I wish there was a combinatorics node though 😁 

![sv-metatron-cube-test2](https://cloud.githubusercontent.com/assets/2083719/23594434/0a59c4a0-01e8-11e7-89f6-e836b65ff09e.png)

**Comment by enzyme69** [comment]
Edge Center we can use Bounding Box for every points ... or Vector
Interpolation of 2 points
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by DolphinDream** [comment]
Here’s the edge split node with “mirror” option. 

Now that i’m thinking about we could add a number of splits as well (1,2,3 infinity :) 

![edgesplit-demo1](https://cloud.githubusercontent.com/assets/2083719/23595518/8962b3da-01f0-11e7-9340-cb42170178d2.gif)

**Comment by enzyme69** [comment]
I like that DolphinDream!!
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by DolphinDream** [comment]
And the version where the edges are actually split .. with or without mirroring. (added new edges output)

![edgesplit-demo2](https://cloud.githubusercontent.com/assets/2083719/23596390/09fb61f2-01f8-11e7-84b8-bba3959487d6.gif)

**Comment by zeffii** [comment]
Make a combinatorial node, with the few obvious modes. Itertools is your friend, spacial searches are already implemented in kdtree nodes.

**Comment by DolphinDream** [comment]
If needed i could pull request my EdgeSplit branch:
https://github.com/DolphinDream/sverchok/tree/edgeSplitNode

**Comment by zeffii** [comment]
if you move it to Modifiers / Change , then i'm happy to accept the Pull Request.

**Comment by DolphinDream** [comment]
will do.. soon. It’s been a while.. time to get back to the SV realms :)

**Comment by enzyme69** [comment]
Dolphin Dream is back yey! I am curious how this edge thing can be used for
Origami effect.

**Comment by DolphinDream** [comment]
I just realized (going back to my blend files using this node) that I actually failed to honor the initial title I gave to this issue “Edge Center” :) I needed the edge centers.. not just to split the edges. Any objection to adding a “Split Verts” output so that I can get access the actual vertices added during the split ? It would provide a similar functionality to the poly center node, but for edges.

![SplitEdges-splitVerts](https://user-images.githubusercontent.com/2083719/29009262-c8d442b8-7aef-11e7-968d-a144e72837b0.png)

**Comment by enzyme69** [comment]
Normally to get Edge Center, I am using Vector Intepolation and 0.5 value.

**Comment by DolphinDream** [comment]
Sure.. though I imagine you would have to split the edges and average each edge vertices or something like that. 

Here’s a demo with the SplitVerts addition.. which gives the vertices generated during the split for any given factor (not just 0.5).. and also works with mirrored splitting. 

![sv-splitcenteredges-demo3](https://user-images.githubusercontent.com/2083719/29011972-92a176f0-7b05-11e7-9853-d2ccaf0809a0.gif)

**Comment by cosmopardo** [comment]
hi guys! i'm so -soooo- noob.
and i have this problem using edge-lenght.py on SNL
when i input a box <ex: 2units side>, i obtain a list (on sthetoscope) of 12 elements <once an edge> with of 2units lenght. right?
but, when i try join the SNL's out-socket with text-imput of ViewerIndex for visualize the results, i can visualize only 8 values, and all of them are on the verts. 
i would like to use it as «linear-dimension»of typically CADsofts, and measure some or all edges on a solid. some ideas?
i tried to make a matrix with edge-centers (SplitEdges at .5 factorI). and use the new mid-vertex location to positionate the lenghts. but the result is horrible (like my eng, sorry)
![giphy](https://user-images.githubusercontent.com/33662786/33608128-d7087ff6-d9c3-11e7-8baf-c9a714c985ec.gif)

**Comment by zeffii** [comment]
You want the _Edge Length_ per Edge to appear on the Edge using ViewerIndex node? Admittedly we have no convenience method for this, but i'd use something like:

here's a modified version of edge-length.py (this is not a SNL script.. its a ScriptNode 1 script...)
```python
import mathutils 
from mathutils import Vector

#get length of all edges
 
def sv_main(verts=[[]],edges=[[]]):
 
    # in boilerplate - make your own sockets
    in_sockets = [
        ['v', 'Vertices',  verts],
        ['s', 'Edges',  edges],
    ]
    lengths = []
    locations = []
    for v,es in zip(verts,edges):
        lens=[]
        locs=[]
        for e0,e1 in es:
            edgelen = (Vector(v[e0])-Vector(v[e1])).length
            lens.append([round(edgelen, 4)])
            locs.append(((Vector(v[e0])+Vector(v[e1]))/2)[:])
        lengths.append(lens)
        locations.append(locs)
    
    out_sockets = [
        ['s', 'Lengths', lengths],
        ['v', 'Locations', locations]
    ]
 
    return in_sockets, out_sockets

```
![image](https://user-images.githubusercontent.com/619340/33610371-9f45a01e-d9cb-11e7-84a8-2df8fc476dbe.png)

**Comment by zeffii** [comment]
here's SNLite version.. with adjustable rounding
```python
"""
in verts v
in edges s
in roundn s default=5 nested=2
out locations v
out lengths s
"""

import mathutils 
from mathutils import Vector


for v, es in zip(verts, edges):
    lens = []
    locs = []
    for e0, e1 in es:
        edgelen = (Vector(v[e0])-Vector(v[e1])).length
        edgemid = ((Vector(v[e0])+Vector(v[e1]))/2)[:]
        lens.append([round(edgelen, roundn)])
        locs.append(edgemid)
    lengths.append(lens)
    locations.append(locs)
```

**Comment by cosmopardo** [comment]
madonna! is too much!

1st: thank you very much. 2nd: XD which the difference between SN and SNL? code type?

you are a CRACK. i follow you (and follow jimmy on youtube), and both are a great inspiration to my work. in fact, im still starting on blender. i installed it on january, and step by step i leaved the others softwares.

**Comment by zeffii** [comment]
let me respond in a dedicated thread: https://github.com/nortikin/sverchok/issues/1903

**Comment by Durman** [comment]
@cosmopardo 
SNL more comfortable for scripting. Documentation is here #942

**Comment by Durman** [comment]
This node could have been useful for creating something like this: 

![2017-12-22_10-34-55](https://user-images.githubusercontent.com/28003269/34288025-43e77116-e704-11e7-9f58-af29b39d268e.png)

**Comment by Durman** [comment]
Works wrong but looks interesting.

![spli_edges](https://user-images.githubusercontent.com/28003269/34309648-810fd37c-e76c-11e7-8a42-b3be6dc77949.gif)
