### ISSUE TITLE
Polygon To Edges, Unique Edges option does not work anymore?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1306]
![screen shot 2017-03-06 at 12 59 32](https://cloud.githubusercontent.com/assets/3952687/23594275/e61b70f4-026c-11e7-99cf-6449ef4c9d24.png)
[unique_edges_001_2017_03_06_02_01.zip](https://github.com/nortikin/sverchok/files/819983/unique_edges_001_2017_03_06_02_01.zip)
![screen shot 2017-03-06 at 13 01 05](https://cloud.githubusercontent.com/assets/3952687/23594292/0cd1d5bc-026d-11e7-8699-6ea42453014a.png)

@nortikin 

I am also referencing this:
https://github.com/nortikin/sverchok/issues/1301#issuecomment-284137088

**Comment by enzyme69** [comment]
Hmm... weird, seems to do something, but not making edges separated.


![unique_edges](https://cloud.githubusercontent.com/assets/3952687/23594371/96bb1950-026d-11e7-9a07-0530acdc588c.gif)

**Comment by enzyme69** [comment]
Also errored out here, when used with Separate Loose.
![screen shot 2017-03-06 at 13 09 11](https://cloud.githubusercontent.com/assets/3952687/23594427/1e27514c-026e-11e7-8c24-3970624076c5.png)

Which means my older setup to make Pocky failed :|

**Comment by enzyme69** [comment]
But @nortikin Polygon Boom to separate edges work. However, what's the Polygon To Edges node is for then? Maybe related to Separate at intersection?

Ok, I'll investigate.

**Comment by zeffii** [comment]
Switch off the indexviewer background polygon to see if there are doubles,

**Comment by zeffii** [comment]
@enzyme69  there's overlap in the functionality of a few nodes.  

-  _Polygons to Edges_ generates an _edge list_ when only  a _polygon_list_ is available.
- For example in a cube each polygon shares 1 edge, (or looking in reverse, each edge is shared by two polygons) . Unique Edges makes sure that there are no duplicate edges in the output _edge list_,

http://nikitron.cc.ua/sverch/html/nodes/modifier_change/polygons_to_edges.html  needs to be updated.

**Comment by zeffii** [comment]
see, left has duplicates if you look closely.  and the number of edges produced is 24
whereas the right side, there are no duplicates, and the edge count is a predictable 12
![image](https://cloud.githubusercontent.com/assets/619340/23602230/d699a10e-024f-11e7-8e7e-fd01bf9c2e35.png)

**Comment by enzyme69** [comment]
Ok cheers for info.

**Comment by nortikin** [comment]
yes, oldy node.
