### ISSUE TITLE
Math mod software

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1307]
Have you ever seen [Math mod](https://sourceforge.net/projects/mathmod/?source=typ_redirect)? it is the successor of [K3dsurf](https://sourceforge.net/projects/k3dsurf/?source=recommended)
It has a lot of formulas, texture support, noise, script saving in .json format. Maybe we can import into sverchok?

Go to [google+](https://plus.google.com/u/0/108432079989441783124) to see a lot of images.

p.s.: if you download the linux64 i had some issues, instead the win64 version under wine works fine.

Have fun!

Walter

**Comment by zeffii** [comment]
if someone writes a parser for those files :) i'll add a file loader / self.file_name property to snlite to facilitate the loader. but until then i'll let someone else attack it :)

**Comment by zeffii** [comment]
closing for now :)
