### ISSUE TITLE
NodeTree updates twice with manual frame change?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1308]
When we jump into frame number, Blender or Sverchok seems to update twice. Well, luckily, when played frame by frame, it does not do this.

**Comment by zeffii** [comment]
yes, quite possibly.. link to the script here please

**Comment by zeffii** [comment]
well.. a simple setup proves that it's not SNLite but the node tree in general.

![image](https://cloud.githubusercontent.com/assets/619340/23611084/cde58d72-0275-11e7-80df-ecab2147464e.png)

**Comment by zeffii** [comment]
@ly29  .. is it updating twice because changing the frame is a scene_update .. and the fact that the frame changes is a separate trigger to update ?

**Comment by zeffii** [comment]
@enzyme69  you can use this to scroll through frames

![image](https://cloud.githubusercontent.com/assets/619340/23611363/33840392-0277-11e7-847f-768c092acfff.png)

**Comment by ly29** [comment]
@zeffii 
That does sounds likely, the scene update handler needs a check to see if we are playing I guess.

Hmm.

**Comment by zeffii** [comment]
congratulations on the new job btw!  hopefully somewhat fulfilling :)

**Comment by ly29** [comment]
@zeffii 
Thanks. 
Fun so far, somewhat of career change but for a couple of months I will be very busy...

**Comment by zeffii** [comment]
@ly29  cool! 

`bpy.context.screen.is_animation_playing`  btw :)

**Comment by zeffii** [comment]
possibly
```python
@persistent
def sv_update_handler(scene):
    """
    Update sverchok node groups on frame change events.
    """
    for ng in sverchok_trees():
        try:
            ng.process_ani()
        except Exception as e:
            print('Failed to update:', name, str(e))
    if bpy.context.screen.is_animation_playing:
        scene.update()
```

**Comment by zeffii** [comment]
i'll have a look at this tomorrow if @ly29 doesn't. (no pressure either way.. )

**Comment by enzyme69** [comment]
I will watch this thread and learning like a good student :)
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by ly29** [comment]
I won't have time until the weekend.

**Comment by zeffii** [comment]
```python
@persistent
def sv_update_handler(scene):
    """
    Update sverchok node groups on frame change events.
    """
    if not bpy.context.screen.is_animation_playing:
        # manual scrub causes this to be triggered twice, 
        # - once with is_animation_playing True
        # - once with is_animation_playing False
        return

    for ng in sverchok_trees():
        try:
            ng.process_ani()
        except Exception as e:
            print('Failed to update:', name, str(e))

    scene.update()
```

**Comment by zeffii** [comment]
that should do the trick, tests OK.

**Comment by zeffii** [comment]
committed: https://github.com/nortikin/sverchok/pull/1324
