### ISSUE TITLE
SV OSC ChucK and Sonic Pi, but ChucK for now

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1311]
While experimenting with the idea of Sverchok connecting to SOUND GENERATOR like Sonic Pi, I stumbled into Python ChucK module.

https://github.com/Calysto/chuck/blob/master/docs/API.md

Currently I am testing this ChucK module with Sverchok Script Node Lite. I manage to make sound, although the refresh rate is too low, I wonder if I am doing it right.

My issue is often with the idea of REALTIME and UPDATE. I don't know exactly how Blender or Sverchok "update" apart from update when time changed or parameter changed. 

Is this thing slow because of the ChucK module itself is slow? Or because the environment was not really made for it (realtime)?

Maybe we can somewhat make it to work? 👍 

```
"""
in trigger      s   d=1     n=2
in note        s   d=440.0    n=2
"""
import bpy
#from psonic import *
from chuck import *

init()

s = SineWave()
s.connect()

if(trigger):
    s.setFrequency(note)
    
else:
    s.disconnect()

```

**Comment by enzyme69** [comment]
For below, I am getting 2 fps:

```
"""
in trigger      s   d=1     n=2
in note        s   d=440.0    n=2
"""
import bpy
#from psonic import *
from chuck import *

init()

m = Mandolin()
m.connect()
m.setFrequency(note)

if(trigger):
    m.noteOn(0.8)
       
else:
    m.noteOff(0.2) 
```

**Comment by enzyme69** [comment]
Sverchok and Sonic Pi is really quite fast, somewhat. There is a slight delay, but otherwise it is fine.

The thing with Sonic Pi one is that it does not have the instaneous interaction smoothness that I experience using ChucK.

I realized one BIG thing:
For all my programming experience, whether it is using Processing, ChucK, my biggest issue is the lack of UI and Interaction. NODES and PARAMETERS apparently gave me a boost of confidence in my learning progression, somewhat. This is why NodeBox, Sverchok, Animation Nodes feel easier.

**Comment by zeffii** [comment]
1. ChucK does have an osx _UI_ library built on cocoa (iirc). I don't know if the python module for ChucK exposes it.

2. OSC over udp/tcp has some latency, latency is generated by several contributing factors and i feel i've explained this in the past. Anyway.. external modules (like _python chuck_) to sverchok are beyond the scope of this issue tracker (even tho it's interesting)..

One thing that will have a big influence on the chuck/python latency using SN1 is the fact that you are repeatedly doing this: 
```
"""
in trigger      s   d=1     n=2
in note        s   d=440.0    n=2
"""
init()

m = Mandolin()
m.connect()
```
means each time you trigger the node.. it does something in `init()` and instancing `Mandolin()` and `m.connect()` probably also take up time. The only thing you should be doing on a SN update is
```python
m.setFrequency(note)

if(trigger):
    m.noteOn(0.8)
       
else:
    m.noteOff(0.2) 
```

SNlite is "stateless" and isn't equipped to handle this, but SN MK1 is. 
```python
# psuedo

init()

m = Mandolin()
m.connect()

svmain

    m.setFrequency(note)

    if(trigger):
        m.noteOn(0.8)
       
    else:
        m.noteOff(0.2) 
```
Making SNLite work with `state` is definitely something I want to add, it's even noted somewhere in the first commits of SNLite to master. but no ETA.

**Comment by enzyme69** [comment]
Thanks @zeffii for explanation I will keep this egg as pending wishlist.

**Comment by zeffii** [comment]
@enzyme69   can you please use ` _underscores_ ` to _emphasise_ words, instead of CAPITALS. caps are for acronyms. please please please.

**Comment by enzyme69** [comment]
@zeffii I will try to remember this. I got used to CAPITALIZE... yeeks. I will _emphaize_ like this.
