### ISSUE TITLE
Accumulate List

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1316]
![screen shot 2017-03-08 at 11 03 51](https://cloud.githubusercontent.com/assets/3952687/23683786/0370018c-03ef-11e7-8a47-fce9407428c7.png)

https://gist.github.com/b55d92c542b3caf5a3c53f86d9944c0a

The task here is to make Circle Pie, but each with Random Num Slicing that should make 360 degree in total.

I think I am kind of half way there. Just not quite sure how to generate ACCUM list. Probably similar to other problem of Accumulating the Sum of Bounding Box.

Is there a node in Sverchok that Accumulate List again?

mylist = [1,4,3,2]
accum = [1, 5, 8, 10]
OR accum = [0,1,5,8]

**Comment by Kosvor2** [comment]
![exec12](https://cloud.githubusercontent.com/assets/22656834/23686056/3ab667a6-03c9-11e7-9efe-a2bd64948f25.png)

**Comment by enzyme69** [comment]
Aah... cumsum of numpy!! Thanks kosvor!!!!
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
![Uploading Screen Shot 2017-03-08 at 16.36.48.png…]()

**Comment by enzyme69** [comment]
GIST:
https://gist.github.com/933c3aae4cf890e464f0fd86dbbb6fb3
