### ISSUE TITLE
Working in edit mode - Manual selection of vertices/edges/faces in 3D view

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#1320]
General idea.
When creating useful meshes, you often want to select "these" faces (or vertices, or edges) and do something with them: extrude or delete or whatever.
Currently you can do it with masks; but the main problem is what numbers to write. Index viewer is of use, but the problem is: when you looked at indices and wrote them to List Input node to be a mask; then next time someone opens blend file, he will have no idea what these numbers in List Input mean, why these numbers were entered, not other.

Looking for competitors: in Grasshopper, you can select parts of created mesh interactively in 3D view at any time.
It would be cool to have similar behaviour in Sverchok, but I have no idea if it is possible in Blender at all.

So, currently suggested solution is:
* Add "Selected verts mask", "Selected edges mask", "selected faces mask" outputs to BMesh Viewer node.
* Add "Get selection" button to it. Node should remember selected verts/edges/faces when you press this button.
* (not implemented yet): BMesh Viewer should use remembered selection when generating new meshes. So it will be easy to slightly modify previously remembered selection.

So the workflow will be like:
* Generate something with BMesh Viewer
* Select that mesh and go to Edit mode
* Select some verts/edges/faces
* In BMesh Viewer node, press "Get Selection". It will remember indicies of verts/edges/faces you selected, and pass them to output.
* Now you can switch UPD in this BMesh Viewer off, and delete generated mesh, if you do not need it. Node will still remember what verts/edges/faces you selected.
* Use Mask outputs of BMesh Viewer somewhere.
* It is possible to use several BMesh Viewers in one node tree. For example: extrude these, then extrude one of extruded faces...

If at some point you decided that you need to change selection:
* enable UPD for corresponding BMesh Viewer (it will generate new mesh)
* select that new mesh and go to edit mode
* (not implemented yet): selection will be the same as you selected first time
* Adjust selection
* Press "Get Selection" button in BMesh Viewer again.
* Now you can switch UPD off and remove mesh.

This workflow is not super-nice, but i think it is better than nothing.

Current implementation is in: https://github.com/portnov/sverchok/tree/viewer_bmesh_select

**Comment by portnov** [comment]
![output1](https://cloud.githubusercontent.com/assets/284644/23697163/da004894-0410-11e7-907e-4501681efa9d.gif)

**Comment by portnov** [comment]
Open questions:
* Do I need to create "BMesh viewer mk3" to add new outputs?
* Is it ok to add such functionality into BMesh Viewer at all? But I think to create new node which renders mesh, plus allows to select it, is even worse idea...
* Maybe it is possible somehow to select verts/edges/faces on OpenGL thingy generated by Viewer Draw?

**Comment by ly29** [comment]
Working in edit more would be very fun. There are a lot of gotchas there however.

**Comment by enzyme69** [comment]
I've been wanting to have such feature. Probably mentioned it somewhere. 

We need some kind of GROUP node ala Houdini that can do pattern selection whether from USER or ala LIST MASK (generated).

But, your idea here is to have some kind of "Intermediate Objects" that can be used.

Imagine this:
- User create a grid
- User want to select some area from the grid
- Generate Intermediate Mesh, maybe delete area that user does not want
- Bring it back into Sverchok and COMPARE the Mesh Original and Current Mesh

**Comment by portnov** [comment]
@ly29 
Yeah, but I do not see how it is possible at all within Sverchok's approach.

@enzyme69 
Current implementation basically uses existing idea of masks. The only thing it does is allow to easily create masks by selecting things in 3D view.

To compare meshes is... well, not easily done task imho. Especially when edges/faces are represented as in Sverchok: vertex indices will be shuffled if you add or remove a vertex.

Current implementation have similar problem: if you change topology (add/delete vertices), all masks you created will become invalid. But you can recreate them manually again if you want to.

**Comment by portnov** [comment]
@zeffii 
I'm waiting for your thoughts too :)

**Comment by zeffii** [comment]
i was thinking instead of 3d masking using 'brushes', (boxes, donuts, spheres), any verts within those brushes would be returned as a list of indices..

**Comment by zeffii** [comment]
- and planes could be used to select any polygons / verts that intersect with a plane.

the whole point of parametrics is that we can avoid interacting with the geometry, but using 3dbrushes is how i envisioned that (on those rare moments where i do wish for interaction)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/219#issuecomment-45727337

**Comment by portnov** [comment]
Most obvious ways of "parametrically select" something are:
* Select "leftmost" or "rightmost" vertices. More exactly, select vertices that have (direction, Vertex) >= X, where direction is specified vector and X is some number. And also select edges and faces that include selected vertices.
* Select by normal direction. Select faces (and faces?), that have (Normal(Face), direction) >= X. And also select vertices that are included into selected faces.
* Select "in range". Select vertices, that have distance(Vertex, Center) <= Radius. And also select edges and faces that include selected vertices.

I think I better implement this modes in separate node anyway.

**Comment by portnov** [comment]
@zeffii 
(i'll better continue discussion here to not mix things)
So if I move functionality described in starting post to new "BMeshViewer Mk3", (copy of mk2 + new functions), it will be ok?

**Comment by zeffii** [comment]
yep!

**Comment by zeffii** [comment]
also a perfect opportunity to move to abstracting away more stuff and use `sv_viewer_utils.py`

- get_children
- remove_non_updated_objects
- `node.basemesh_name + '.' + str("%04d" % obj_index)`  (like new code in in viewer_polyline_mk1 )

**Comment by nortikin** [comment]
now i working with profile node and have needs to show string (point) number in 3d automatically. So, i think of autocreate index viewer node from pressing ```from selection``` button to see what is in 3d.
thinking of it now. The same - needed more interation with simple mouse.

**Comment by enzyme69** [comment]
​That is cool, some kind of way _USER_ can select some Index Points in 3D
and then "copy paste" or grab that selection into Sverchok in Blender.​

**Comment by zeffii** [comment]
@portnov  ideasman mentions ` bmesh_walkers_impl.c`  maybe we can lobby for a py wrapper..

**Comment by Durman** [comment]
With current update system switching off update of the `Bmesh viewer` node is not good idea. When some changes happens in node tree all sockets lose their data. So next after `Bmesh viewer` node after a change in node tree should show no data passed error. 

Generally I don't see reasons why this functionality can't be implemented in separate node. I think `Bmesh viewer` is already complex enough. 

Partly the problem can be solved by improving modifier nodes. For example extrude node can have selection socket input and output and managing with selection data according inner algorithm. On the picture I expect such result after extrusion.

![2019-06-19_23-21-45](https://user-images.githubusercontent.com/28003269/59794150-5e619700-92e9-11e9-9de3-6bf1f01c29e5.png)

Also the modifier node can takes to account another types of data like index material, uv maps, weights of vertex and so on.

![handlimg material](https://user-images.githubusercontent.com/28003269/59794475-18f19980-92ea-11e9-89db-5b736d1faf23.gif)

**Comment by Durman** [comment]
I think we could have one more `mesh viewer` node.

Main feature of this node should be active mode. It will be possible to have several `mesh viewer` nodes which bakes mesh in one object. But only one node from set of them can be active. 

For example there is next chain of nodes:
`n1 - n2 - V1 - n3 - n4 - V2 - n5 - V3`

Where:
- `n` is Sverchok node 
- `V` is new viewer node 

If n3 node is changing v3 viewer should be activated and other viewer nodes disactivated. It can be done manually or it is possible to add new handler for searching active node in Sverchok node tree and do activation automaticaly. 
Also there is sense in having mode when only last viewer in chain is always active. 

Next feature of this node can be to storing custom information about mesh inside itself. 
For example:
- viewer node baked mesh
- then different materials was assign to different part of this mesh
- after coming back to object mode viewer should bake information about materials inside itself
- after next update event of viewer node redraw function should be called
Redraw function:
- should delete current mesh and create new mesh
- after that custom information should be applied to this new mesh 

It should work if viewer node gets mesh with constant topology. If topology was changed we can try to apply custom information and mark node that custom data probably is outdated. 

Performance of redraw function the slower the more type of custom data it works. So there is sense to have option what custom data should be included to the node.

**Comment by Durman** [comment]
Actually I see that it even possible to let change topology by user with logic based on Blender shape keys.

![Shape_keys](https://user-images.githubusercontent.com/28003269/59819512-3437c580-9339-11e9-9bd4-05c0e114c11e.gif)

On the picture can be seen that Blender memorize base points of mesh in time of creating Basis shape. And then after changing topology new vectors also get some impact from moving base points. 

In this case redraw function should:
- create during first call base mesh and custom mesh. Custom mesh will be shown in 3d view. 
- during next redraw calling the function should find difference between input mesh and base mesh and apply this two base points of custom mesh. Something similar what I described here: https://github.com/nortikin/sverchok/issues/2423#issuecomment-497200666
- If topology of custom mesh was changed impact to new points should calculated. Probably such algorithm can help: #2426

**Comment by enzyme69** [comment]
@Durman I have even at some point think that maybe Shapekeys is something that SV can incorporate.

**Comment by nortikin** [comment]
> @Durman I have even at some point think that maybe Shapekeys is something that SV can incorporate.

we have SNL shapekeys script

**Comment by enzyme69** [comment]
@nortikin Need to revisit that Shapekeys idea.

**Comment by nortikin** [comment]
> @nortikin Need to revisit that Shapekeys idea.

with surface lerp node it is the same, but extended
![Снимок экрана от 2020-04-30 17-25-48](https://user-images.githubusercontent.com/5783432/80722250-d868cc00-8b07-11ea-874e-68498af5819e.png)
