### ISSUE TITLE
Thinking ASCII ART

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1321]
![screen shot 2017-03-08 at 22 46 27](https://cloud.githubusercontent.com/assets/3952687/23702845/2a5e1ee8-0451-11e7-8d5a-3513eb716ec5.png)

I am thinking of generating _ASCII Art_. But it needs to be super efficient.

Currently my setup is _grid points_ that place 1 Text Object Character per point and with 64 x 64, I am getting... 4096 objects. Which is stupid.

I guess, it can be reduced to only 64 objects. I am using 0-9 Numeric Digits for a starter. But I think it could be more interesting with proper random ASCII characters.

What would be most efficient is if I can use /n _Enter_ New Line inside Typography. Or something.

And so instead of thousands of Text Object, a single text with lines separator will do the job.

Still thinking the easiest way to combine [0,1,2,4,5] into 01245 and separating many lines into /n ...

Some basic python that I need to look at.

**Comment by enzyme69** [comment]
The funny thing is... I realized, it is much more efficient and simpler to have X number of representation of ASCII as 3D Mesh that got into Sverchok and outputted as a single mesh.

**Comment by kalwalt** [comment]
@enzyme69  cool! but why you are not using the new `Texture viewer` version?

**Comment by zeffii** [comment]
I didn't realize that typography node filters out newlines?.. i don't recall adding that. ( i looked..it's not there )

still dumb.. but 64 times less dumb
![image](https://cloud.githubusercontent.com/assets/619340/23712893/85538522-0424-11e7-90a5-ce343c1da4a1.png)

**Comment by zeffii** [comment]
you will need to use a monospace font for that btw..

**Comment by zeffii** [comment]
then this is 4096 times less dumb
![image](https://cloud.githubusercontent.com/assets/619340/23713059/fd997762-0424-11e7-9b0c-ca991ffc2c6d.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23720217/66b8579a-043e-11e7-9800-9616ff74d2c1.png)

```python
"""
in   size      s  d=64  n=2
in   dvalues   s  d=[]  n=1
out  text      s
"""
from math import floor


if dvalues:
    squared = size**2
    if len(dvalues) == squared:
        mstr = [chr(floor(i)+48) for i in dvalues]
        collected = []
        for j in reversed(range(0, squared, size)):
            collected.append(''.join(mstr[j:j+size]))
        text = [['\n'.join(collected)]]

```
not as satisfying as I thought it might be..

**Comment by enzyme69** [comment]
@kalwalt yes, I checked last time, was not there. I tried pulling and update. Maybe I will try again.

@zeffii wow! you are on fire. Yes, that new line function is definitely a necessity :) yes I will use monospace, will give this a try once I got to computer. String manipulation and fluency in Python is something I want to get into more.

**Comment by zeffii** [comment]
@enzyme69  you need to switch to master
```
> git checkout master
> git pull
```

**Comment by zeffii** [comment]
# NEVER USE "update" anymore if you are properly using GIT.

**Comment by zeffii** [comment]
closed because it's not really an issue.. but a problem with process. 

Regarding the ASCII:
These are exactly the kinds of musings that might better be places on BSE or Google+ to give a wider audience the chance to suggest / think with you.

**Comment by enzyme69** [comment]
@zeffii  Ok thanks again for helping me understand and musing with ASCII. You are right with Blender Stack Exchange thing, fully understood.

@kalwalt Got the new Texture Viewer using Zeffii Git Pull!

**Comment by enzyme69** [comment]
Wonder why 128 x 128 resolution is running super slow somewhat ... even with 1 Text Object?

I thought that I could get realtime speed at 1280 x 720 ...

**Comment by enzyme69** [comment]
I am curious about the speed / slowness @zeffii  @ly29 

[sv_ascii_test_010_2017_03_09_00_59.zip](https://github.com/nortikin/sverchok/files/829406/sv_ascii_test_010_2017_03_09_00_59.zip)

I could do this differently where I have maybe 10 objects to represent 10 greyscale values and doing sampling of image on the fly using Displace Modifier and it is MUCH faster than doing it with String.

Is String and Python = slow?
