### ISSUE TITLE
Enable download options for documentation

### ISSUE THREAD

**Issue by pbella** [nortikin/sverchok#1325]
When playing around with Sverchok offline, it would be very handy to have an offline copy of the documentation.   A few other projects also use Read the Docs and have a download option available in several formats so I suspect this is a configuration issue that likely wouldn't require effort beyond enabling it.  (To see the download formats I'm talking about, please see http://animation-nodes-manual.readthedocs.io/en/latest/ and click on the option in the lower left of the window labeled 'Read the Docs    v: latest' and you should see the option to download as PDF, html archive, epub)

**Comment by zeffii** [comment]
welcome @pbella .

good point, we'll get on that. sverchok.readthedocs.io was last updated a year ago. No ETA.

**Comment by zeffii** [comment]
it seems automatic build using `https://readthedocs.org/projects/sverchok/builds` fails because the docs have some Cyrillic / Russian characters.  @nortikin  maybe can log in to configure read the docs to handle dual language ( I don't know )

**Comment by zeffii** [comment]
I don't think we ever had a successful documentation build hosted by `readthedocs.io`, because of the mixed languages of some pages in our docs. The download feature is part of the hosting on that domain. Currently sverchok docs are hosted on `http://nikitron.cc.ua`.

Getting the _download option_ to work on readthedocs.io requires first that the docs can be built by `readthedocs.io`, and that's out of my hands. Worst case scenario is that it's not possible to have Cyrillic and Latin characters in one doc/directory... but i can't imagine that's the case.

**Comment by zeffii** [comment]
@ly29  you set up that page, is there option to setup LaTeX to allow multiple charsets ?

**Comment by ly29** [comment]
@zeffii 
I had forgotten about that page.

**Comment by ly29** [comment]
I will take a look, it didn't work when I registered it and I never did anything more with it.

**Comment by zeffii** [comment]
- either there's a switch to support multiple charsets 
- we make two docs `en/ru`

one of those is a lot less work than the other :)

**Comment by zeffii** [comment]
[wafel node docs](https://github.com/nortikin/sverchok/search?utf8=%E2%9C%93&q=Great+thanks+to+magazine)
[neuro elman node docs](https://github.com/nortikin/sverchok/search?utf8=%E2%9C%93&q=%D0%A3%D0%B7%D0%B5%D0%BB+%D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9+%D1%81%D0%B5%D1%82%D0%B8&type=Code)
maybe more.

**Comment by zeffii** [comment]
@pbella 

https://media.readthedocs.org/pdf/sverchok/master/sverchok.pdf

i'm sure it's a bit rough with tables cutting off early,, 

there's always the offline version of the docs built in to sverchok in the N-panel, if a node has docs, you can press 

![image](https://cloud.githubusercontent.com/assets/619340/23794552/f086d106-0590-11e7-8a54-ddc03390f9af.png)

**Comment by zeffii** [comment]
@ly29 @nortikin 
it passes the LaTeX conversion test now because i removed the few places where Cyrillic is used in the docs.
https://readthedocs.org/projects/sverchok/

but I can totally understand if you want to have russian in the docs.. this was just a test.

**Comment by zeffii** [comment]
@ly29 i think you have to enable something somwhere to route the built docs to 
http://sverchok.readthedocs.io/en/master/
http://sverchok.readthedocs.io/en/latest/

**Comment by ly29** [comment]
@zeffii 
Will do tomorrow.

**Comment by zeffii** [comment]
it might be temporary downtime for rtfd.. their issue tracker has sporadic mentions of similar things.

**Comment by ly29** [comment]
@zeffii 
I think maybe the clever move here is to add you as a admin of that page

**Comment by zeffii** [comment]
cool

**Comment by pbella** [comment]
Thanks for the quick turnaround on this... even if it has some rough edges, the PDF option is quite handy to have.  Also, thanks for the tip @zeffii ... I hadn't noticed that option before.

**Comment by zeffii** [comment]
closing because this isn't a massive concern, 
- the docs are always available offline via .rst in the browser.. 
- can be downloaded with the pdf above
- could be compiled by the user using `make html` in a terminal pointed at the docs directory.

**Comment by nortikin** [comment]
https://www.quora.com/How-to-create-a-PDF-out-of-Sphinx-documentation-tool
rst2pdf cannot import mathbase

**Comment by nortikin** [comment]
it is python2  librery. so i have to rewrite my own rst2pdf

**Comment by nortikin** [comment]
handsup. no way for pdf.

**Comment by zeffii** [comment]
http://sverchok.readthedocs.io/en/latest/nodes.html   

\o/ !

**Comment by zeffii** [comment]
http://sverchok.readthedocs.io/en/latest/main.html

**Comment by zeffii** [comment]
nortikin, can you restore the docs code you changed? the automatic build now fails on readthedocs (and that does automatically make the pdf )

**Comment by zeffii** [comment]
i removed the rst2pdf line for now. waiting for it to build on readthedocs.

**Comment by nortikin** [comment]
yes, sorry for lately answer. will check evening

**Comment by zeffii** [comment]
works already :)
http://sverchok.readthedocs.io/en/latest/main.html
https://media.readthedocs.org/pdf/sverchok/latest/sverchok.pdf
