### ISSUE TITLE
Slowness in processing String

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1326]
This is extension of my question regarding _ASCII Art_.
https://github.com/nortikin/sverchok/issues/1321

@nortikin  @ly29  @zeffii Using 128 x 128 it is already super slow.

[sv_ascii_test_010_2017_03_09_00_59.zip](https://github.com/nortikin/sverchok/files/829408/sv_ascii_test_010_2017_03_09_00_59.zip)

I thought I could get realtime 24-60 fps in Sverchok to pass random numbers into a single Text object..

Is the slowness because of _string or text_ processing?

**Comment by zeffii** [comment]
in sverchok prefs enable " print timings ". Will show you where most time is spent

**Comment by enzyme69** [comment]
This setup is probably faster?
![screen shot 2017-03-09 at 17 31 31](https://cloud.githubusercontent.com/assets/3952687/23738641/459bdbda-04ee-11e7-83f7-8007ae886651.png)

@zeffii Most time spent seems to be in the Object In of those Mesh Data where I am comparing the difference of Points _before_ and _after_ the Displace Modifier.

And also, Script Node that is doing the _line break_ for String.

But generating 1 million Points and processing it is actually quite heavy right?

**Comment by enzyme69** [comment]
What strange is that pring timing shows just fraction of seconds, while in reality, my computer is finishing the process in 30-60 seconds.

**Comment by enzyme69** [comment]
128 x 128 plane points data to place 22 mesh data into random matrix:

Processed  Plane in: 0.0990
Processed  Matrix in in: 0.3619
Processed  Vector Math MK2 in: 0.0129
Processed  Vector Noise MK2 in: 0.0451
Processed  Map Range in: 0.0064
Processed  Float to Int in: 0.0248
Processed  List Item.001 in: 0.0102
Processed  List Item in: 0.0098
Processed  Viewer Draw in: 0.0700
Node set updated in: 0.6402 seconds
Partial update from node Plane in 0.6417
Processed  Plane in: 0.0983
Processed  Matrix in in: 0.3677
Processed  Vector Math MK2 in: 0.0139
Processed  Vector Noise MK2 in: 0.0455
Processed  Map Range in: 0.0063
Processed  Float to Int in: 0.0242
Processed  List Item.001 in: 0.0106
Processed  List Item in: 0.0099
Processed  Viewer Draw in: 0.0659
Node set updated in: 0.6423 seconds
Partial update from node Plane in 0.6435

The actual process timing (calculted inside my head): 24 seconds.

**Comment by enzyme69** [comment]
My feeling is that with this "ASCII Art", I don't actually needs to go into crazy details. 256 * 256 is probably high detailed resolutions already. Might stay at 100 * 100.

I realized that 1024 * 1024 plane points data is also a bit slow after all.

Still wondering if the process can be optimized and faster? Particle Instancing Hack?

**Comment by ly29** [comment]
Well viewer draw does its heavy work outside of the node context. 
You can see that by enabling the timings for viewer draw in the side panel.

**Comment by enzyme69** [comment]
@ly29 You mean without Viewer Draw, the whole thing can be faster?

**Comment by ly29** [comment]
Bake that and see how much data it actually is.

**Comment by enzyme69** [comment]
![screen shot 2017-03-09 at 18 17 17](https://cloud.githubusercontent.com/assets/3952687/23739766/a71cd2dc-04f4-11e7-9977-11fa29afb0b5.png)

Actually, 100 x 100, Zeffii Script Node Method, 17 second ish.

It's slow because there are actually 8 million of data?

**Comment by enzyme69** [comment]
![screen shot 2017-03-09 at 18 18 59](https://cloud.githubusercontent.com/assets/3952687/23739829/e5c587a4-04f4-11e7-9fcd-79d551f02002.png)

So it's totally different to Particle that can go 10000-100000... 

Maybe I should try the instancing method after all. For most efficiency.

**Comment by enzyme69** [comment]
For now, I think I'll go less is more method. If there is anymore tips and trick for efficiency, I'll put here.

Thanks!

**Comment by enzyme69** [comment]
Maybe: Locator + Group Instancing is fast.

**Comment by zeffii** [comment]
When using viewer draw you aren't modifying blender objects, like happens in typeviewer. 

- You can time how long it takes to pass a 4096 char string to a text object '.body'
- time how long it takes to generate 4096 chars from A list of floats or int 
- how long it takes to generate the full 4096 len string, with and without newline chars.

All can be done in texteditor with python, removing sverchok from the equation,. Google " how to time my python code".. " how to identify the slow parts in my python code "

**Comment by enzyme69** [comment]
Text Viewer... (need to be monotype) is actually ... realtime!!
![ascii_text](https://cloud.githubusercontent.com/assets/3952687/23741022/778131f2-04fa-11e7-97c6-d3f69e1c0c24.gif)

@zeffii Good info!

**Comment by enzyme69** [comment]
I understand now, the slowness is the extra procesing to generate mesh, etc.  Hmmm... baking is the way, or maybe Particle Instancing.

![ascii_text2](https://cloud.githubusercontent.com/assets/3952687/23741496/cdfe3bf4-04fc-11e7-970e-b2fa15f941eb.gif)
