### ISSUE TITLE
Note node and Text Viewer to be Monotype?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1327]
Maybe not so urgent, but can Text Viewer by a nice Monotype Font?

![screen shot 2017-03-09 at 19 01 55](https://cloud.githubusercontent.com/assets/3952687/23741088/e2535488-04fa-11e7-835b-46c9709c7e55.png)

And Note node also :)

Btw @zeffii Note node does not understand "\n"

**Comment by zeffii** [comment]
I'm not aware of any feature in the Frame / Note Node that allows us to specify the type of font.

**Comment by enzyme69** [comment]
Ok then, I guess Text Editor output --> will do. It is monotype, but maybe I can custom change the font here.
