### ISSUE TITLE
Text Viewer issues

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1328]
I think this "type" printing out every time is slowing down Text Viewer a bit.
![print_viewer](https://cloud.githubusercontent.com/assets/3952687/23741925/eb2be620-04fe-11e7-8664-28bc0132009f.gif)

**Comment by enzyme69** [comment]
I was going to fix it by commenting it out, but it says: you need to be in branch, etc.

**Comment by zeffii** [comment]
A single print statement per update is not going to slow down the node considerably.

https://github.com/nortikin/sverchok/blob/master/nodes/text/viewer_text_mk2.py#L156-L168

A tip... don't 'fix' things based on a hunch. The reason it prints 'type' there is because the checks above it fail. If we are to fix anything ..it is those checks.

**Comment by zeffii** [comment]
also.. i think it's still pointless to print text to the frame when it isn't monospaced. ( Monotype is something completely different).. 

If you are trying to debug logic.. then you don't do that with thousands of values, but with a grid of many 5*5.

**Comment by zeffii** [comment]
compare

```python
"""
in num_lines s  d=2 n=2
in num_chars s  d=20 n=2
out mytext  s
"""
from random import random as rnd

for i in range(num_lines):
    mytext.append([chr(int(rnd()*26)+65) for _ in range(num_chars)])

```

```python
"""
in num_lines s  d=2 n=2
in num_chars s  d=20 n=2
out mytext  s
"""
from random import random as rnd

for i in range(num_lines):
    mytext.append([[chr(int(rnd()*26)+65) for _ in range(num_chars)]])
```

and..
```python
"""
in num_lines s  d=2 n=2
in num_chars s  d=20 n=2
out mytext  s
"""
from random import random as rnd

for i in range(num_lines):
    mytext.append(''.join([chr(int(rnd()*26)+65) for _ in range(num_chars)]))

```

**Comment by zeffii** [comment]
and `Text->Debug Print` is fine for small quantities of data, its socket don't make any assumptions about the structure of data contained in your links. (TextViewer does...currently..)

![image](https://cloud.githubusercontent.com/assets/619340/23743790/48bd7dc8-04b2-11e7-9ace-5e75f01a1a9e.png)

**Comment by zeffii** [comment]
i'm going to hijack this thread and add a few points that might be good to address too.

- can't suppress Frame creation
- prints 'type' when https://github.com/nortikin/sverchok/blob/master/nodes/text/viewer_text_mk2.py#L156-L168 can't figure out whats going on
- could offer a generic Data socket with no assumptions.
