### ISSUE TITLE
Baking Sverchok Mesh as Alembic MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1329]
![screen shot 2017-03-09 at 20 07 28](https://cloud.githubusercontent.com/assets/3952687/23743272/18bc75be-0504-11e7-93d0-82317f00ba4d.png)

Adding Displace Modifier, set to zero, as Alembic animation used to work. It failed in latest Blender. They changed something.

https://gist.github.com/228e312a172fde64319a6f507040bf2c

Is there anyway we can force it somewhat so that we can Bake out the Sverchok output? :(

**Comment by enzyme69** [comment]
I have a feeling, it's not Blender Alembic exporter that changed, but the way Sverchok handling before and after... it is no longer registering to Alembic exporter.

It used to work, I swear.

I used to be able to use Alembic export for animation of mesh changing, mesh deforming.

**Comment by zeffii** [comment]
Alembic support _has_ changed. whereas the BMesh viewer hasn't significantly .  If the vertex count is constant, use the switch in the `draw_buttons_ext`.

**Comment by enzyme69** [comment]
I'll try... I think without Alembic bake support for Sverchok, it feels missing.

**Comment by zeffii** [comment]
ok.. i see whats going on..
```
AttributeError: 'NoneType' object has no attribute 'is_animation_playing'
```
is the error you get if you export alembic , i'll fix that.. it might solve the issue.

**Comment by zeffii** [comment]
if you want to test it, before i push to master:
```
> git checkout master
> git pull
> git checkout valid_is_animation_playing
```

**Comment by enzyme69** [comment]
I'll try now!

**Comment by zeffii** [comment]
`\o/`

**Comment by enzyme69** [comment]
And... it works! Thanks @zeffii 👍 💯

**Comment by zeffii** [comment]
then we push.

**Comment by zeffii** [comment]
```
> git checkout master 
> git pull
```
to return to normal

**Comment by zeffii** [comment]
because i merged the new code, you have to switch to `master`..and `pull` the code updates.

**Comment by enzyme69** [comment]
This checkout and pull git thing ... it's weird at first.

**Comment by zeffii** [comment]
Agreed

**Comment by kalwalt** [comment]
> This checkout and pull git thing ... it's weird at first.

welcome to the git world @enzyme69 ! but you will appreciate it, think as an advantage.
