### ISSUE TITLE
Frame Info Node upgrades

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1333]
I've been meaning to do this for ages.. but some convenience is possible on this node...

![image](https://cloud.githubusercontent.com/assets/619340/23766760/63fca75e-0506-11e7-92a0-60d3a517dc07.png)

i'd like controls.. start/pause/reverse
and an output for the fraction between start/end that current frame is .. so 'evaluate' would be a value between 0 and 1,0.

https://gist.github.com/15905e73fd762d7f4c676df5f4a5e0bb

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23767499/0ef58aac-0509-11e7-8da3-46a3a57e32e8.png)

**Comment by zeffii** [comment]
ideally, the socket would be directly attached to the slider..

**Comment by enzyme69** [comment]
This is ... a stroke of genius. With evaluate, we can even simulate a timeline viewer!

**Comment by zeffii** [comment]
it'll probably be tomorrow. my brain just died.

**Comment by zeffii** [comment]
and it doesn't need the `|<< <<    >> >>|`

**Comment by zeffii** [comment]
perfect looping :)
![image](https://cloud.githubusercontent.com/assets/619340/23788728/2c076524-0578-11e7-8850-a4253a31bdc9.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1339

https://gist.github.com/8ee0863415d33d5a419e44d3a719316a

doesn't store frame start/end/current in the node.. or gist.. perhaps it should..
