### ISSUE TITLE
Pixel viewer node 

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1334]
The main goal of this issue is to try new ways, techniques for the `Texture viewer node`, maybe this will become another  new node . At this time i was able to transfer the data from the node to the image viewer. as described by @ly29 [here](https://github.com/Sverchok/Sverchok/issues/56). See the picture above. it does plus or minus what the texture viewer does but in a simpler way. It is in my local repository for now, when i'm fine with it i will post the link. (too messy code for now). This node derive from this [discussion](https://github.com/nortikin/sverchok/issues/1332)

p.s. the node is red for some errors from `updateNode`. 

![pixelviewer_test_toimage_viewer](https://cloud.githubusercontent.com/assets/1275858/23767536/315f7684-0509-11e7-95a2-cb652a4db6ff.png)

**Comment by kalwalt** [comment]
also with custom size:

![pixelviewer_test_toimage_viewer_custom](https://cloud.githubusercontent.com/assets/1275858/23769036/4774726c-050e-11e7-92c9-58b2657de2c5.png)

**Comment by enzyme69** [comment]
Maybe also put Tile-able texture node :) Pile and Tile Seamless add on is too good.

**Comment by kalwalt** [comment]
with RGBA!

![pixelviewer_test_toimage_viewer_rgba](https://cloud.githubusercontent.com/assets/1275858/23774720/60b2ea08-0525-11e7-821a-e5012d116721.png)

**Comment by kalwalt** [comment]
Ok i have my branch [Pixel viewer node](https://github.com/kalwalt/sverchok/tree/Pixel_viewer_node), thinking if make sense for a pull request, Actually only experimenting but also some little improvement, also for the `Texture viz node `....

**Comment by kalwalt** [comment]
i agree with you @zeffii, i will see if develop or not this.

**Comment by enzyme69** [comment]
Pixel drawer or tracer might be fun.
