### ISSUE TITLE
Sverchok (or me) needs to be more fluent with String Data > Text In improvement?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1337]
![screen shot 2017-03-10 at 11 13 55](https://cloud.githubusercontent.com/assets/3952687/23776478/b8dc9442-0582-11e7-80c4-1f5cad5c080b.png)

I was looking at @zeffii Script node example that is outputting Text Data Block Writer. 
https://github.com/nortikin/sverchok/issues/1331

My quick instinct is to plug the Text Output into Typography viewer via Text In (just like Blender convert text to 3D, but realized it is not possible yet.

I think Sverchok probably needs few more nodes to be fluent with String Data.

Imagining: "SVERCHOK" >> [S], [V], [E], [R], [C], [H], [O], [K]

What do you reckon?

**Comment by enzyme69** [comment]
Work around with AN...
![screen shot 2017-03-10 at 11 19 58](https://cloud.githubusercontent.com/assets/3952687/23776631/89029b58-0583-11e7-8769-bbb31ab880e0.png)

But I noticed, the TXT was updating but as soon as I use AN, it stopped.

**Comment by enzyme69** [comment]
CORRECTION:
Apparently Script Node is updating the text no problem, but I need to plug the out socket into something, even though the output is nothingness.

Actually @zeffii What's missing from that little script of yours, the data is not understood by Sverchok?

![Uploading text_block.gif…]()

**Comment by enzyme69** [comment]
Trying something...

[write_to_demo_004_2017_03_10_00_34.zip](https://github.com/nortikin/sverchok/files/832654/write_to_demo_004_2017_03_10_00_34.zip)


![screen shot 2017-03-10 at 11 34 44](https://cloud.githubusercontent.com/assets/3952687/23776967/9539d4e8-0585-11e7-9321-ec2de40c394c.png)

```
"""
in num_lines s  d=5 n=2
in num_chars s  d=5 n=2
out mytext  s
"""
from random import random as rnd


fname = 'demo.txt'
text = bpy.data.texts.get(fname) or bpy.data.texts.new(fname)

text.clear()
for i in range(num_lines):
    mytext = ''.join([chr(int(rnd()*26)+65) for _ in range(num_chars)]) + '\n'
    text.write(''.join([chr(int(rnd()*26)+65) for _ in range(num_chars)]))
    text.write('\n')
```

**Comment by enzyme69** [comment]
![screen shot 2017-03-10 at 11 42 11](https://cloud.githubusercontent.com/assets/3952687/23777132/a30d4676-0586-11e7-8e36-9186f27c42bb.png)

After doing above.. I realized I forgot about _list_ ...

**Comment by enzyme69** [comment]
![screen shot 2017-03-10 at 11 45 48](https://cloud.githubusercontent.com/assets/3952687/23777217/21cdaf1e-0587-11e7-9d5b-17dcb22b13b3.png)

That is better, but I realized the output into Text Block is a different data from the one passing out.

```
"""
in num_lines s  d=5 n=2
in num_chars s  d=5 n=2
out mytext  s
"""
from random import random as rnd

mytext = []

fname = 'demo.txt'
text = bpy.data.texts.get(fname) or bpy.data.texts.new(fname)

text.clear()
for i in range(num_lines):
    mytext.append(''.join([chr(int(rnd()*26)+65) for _ in range(num_chars)])) 
    text.write(''.join([chr(int(rnd()*26)+65) for _ in range(num_chars)]))
    text.write('\n')
```

**Comment by enzyme69** [comment]
Maybe Text Block In and Out ala AN is needed.

Text Block >> has String Data with Return Line.

**Comment by enzyme69** [comment]
Would be interesting to study @zeffii example that is causing Text Block to output Return Line in his ASCII example.
https://github.com/nortikin/sverchok/issues/1321

For common artists, probably they would just like to join multiple single line String Text into Text Block. Logically easier to compute.

**Comment by zeffii** [comment]
Text in node doesn't have a mode for just text. You set the mode csv which expects a file with a certain formatting. Look at literally any csv file and tell me some differences with the product of the sn.

There's no speedup for writing the text file and loading it's content into the '.data.body' of a font object. But having a text with the desired number of characters and newlines does let you time how fast 
'''
bpy.data.objects['Text'].data.body = bpy.data.texts['demo.txt'].as_string()
'''
Is. Which is pretty slow as you increase the data. If there's a faster way I don't know about, let me know.

**Comment by zeffii** [comment]
Yep snlite needs like all nodes to be connected, either in or out, else it is skipped by the update system. Typeviewer expects '[[   string   ]]' or '[[   string, string, ...   ]]',  in python a string is one or more characters. Look at Typeviewer process function,

**Comment by zeffii** [comment]
If you want Typeviewer to read the socket and Just make one text object , the snlite's output should be '[['blaaaa\nblaaaa\nblaaaa]]'

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23784686/afea1220-0563-11e7-8269-935f5ac6e951.png)

**Comment by zeffii** [comment]
```python
"""
in dummy_in s  d=5 n=2
out mytext  s
"""
from random import random as rnd

fname = 'demo.txt'
text = bpy.data.texts.get(fname) or bpy.data.texts.new(fname)

mytext.append([text.as_string()])
```

**Comment by zeffii** [comment]
but (maybe you are arriving at this conclusion yourself,) 

If you gain a certain proficiency in the Python language you will have a much easier time understanding sverchok, and solving your own problems. Sometimes we should have better docs, other times you should definitely be investing your time and energy in learning Python because a majority of the problems you encounter are easier to fix than they are for us to 'explain, discuss and then fix'.

Learn python outside of the context of Blender/Sverchok/Animation nodes , String manipulation and file generating have zero to do with Sverchok (except that we implement some specific file reading methods)

We could have better nodes for handling String data, but it's not a massive issue because it's so easy to write a SNLite for these kinds of things, so there is little incentive. As I write this I do feel the urge to make a Strings category and add a few nodes like ("TextFile In", "String Split" , "String Ops", "String Replace", "String Regex"... etc)  and pythonify the common string interactions.

hmmmm.

**Comment by enzyme69** [comment]
​You are right again.

Maybe it goes into categories not urgent, until somebody invest time to
make Text Manipulation Nodes :D

I am starting reading Python books again, and much easier now. Much, much
easier.
