### ISSUE TITLE
String Category

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1338]
As I write this I do feel the urge to make a Strings category and add a few nodes like 

- TextFile In  (local or from file system)
- String Ops   `.lower() .title() .strip() .replace() .split() ..etc `
- String Regex   (re.replace  re.match...)

and pythonify the common string interactions.

**Comment by enzyme69** [comment]
Earlier today, I am using Sverchok Text Out dump to make this ASCII for Sketchfab point cloud. It was surprisingly smooth!

![screen shot 2017-03-11 at 20 27 37](https://cloud.githubusercontent.com/assets/3952687/23822086/31189bf6-0699-11e7-9088-a935187ff2e4.png)

To output animated Point Cloud, I made a little Python script for Saving Text Block into multiple *.txt. Surprisingly stumbled into few Zeffii posts on his website and Blender Stack Exchange as well to accomplish such task! It's like getting help from the past.

I think with additional nodes dealing with Texts and String, Sverchok will feel more complete. The AN String nodes can be some inspirations.

**Comment by enzyme69** [comment]
![screen shot 2017-03-11 at 20 33 13](https://cloud.githubusercontent.com/assets/3952687/23822131/f846ef8e-0699-11e7-89ce-a91d4645e3e1.png)

**Comment by zeffii** [comment]
it will be 5 or 6 nodes at most

**Comment by enzyme69** [comment]
Could it be part of List Split, List Join, or it will be "String Split", "String Join", "String Mix"?

**Comment by zeffii** [comment]
see first comment on top.

**Comment by zeffii** [comment]
anyone with some Python knowledge can already use `exec node mod` for just about any string processing... quite literally .

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23823360/18218e88-0661-11e7-95ee-b1afbfee8d77.png)

**Comment by zeffii** [comment]
> I think with additional nodes dealing with Texts and String, Sverchok will feel more complete

i'm not so sure that nodes can offer the granularity that simply writing out the operations in python, in some sense these node systems will always lack something in someone's eyes. I'll implement the features that i've needed in the past (especially nice regex features..)  .. but no ETA on this stuff from my side.. it might wait until my own needs dictate it. : /

**Comment by enzyme69** [comment]
At some point, I was happy that I can do this.

![screen shot 2017-03-12 at 19 58 14](https://cloud.githubusercontent.com/assets/3952687/23830414/449e114a-075e-11e7-9a4e-f3f0bd4dc264.png)
