### ISSUE TITLE
Render Gallery

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1342]
Project Sverchok needs a 'visual outreach' program.

One thing we've failed at consistently is make attractive renders to show the power of this beast. Some of you may be unfamiliar with it but there was a small attempt ( http://nortikin.github.io/sverchok/ ) at a landing page, I would love to add a set of images that give a better impression of what's possible now.

I don't mind doing the site coding etc.. but really my time is better spent doing other things. I really just want images to stick in there. Preferably Architectural or Graphics, the criteria being just Sverchok/Blender (things that can be done without other add-ons, or with the default supplied add-ons - via imports in Scripted Nodes etc..)

![capture_vaschnikt333](https://cloud.githubusercontent.com/assets/619340/23803359/8b1c70e8-05b6-11e7-9c44-cc78734a3bec.PNG)

A bonus would be if you can submit a gist of the layout too, or a .blend

This thread should be about what you have _done_ not about _what you would like to do_. i'll be sanitising comments to reflect that.

**Comment by portnov** [comment]
http://gallery.iportnov.tech/image/Misc/cube-sponge.png

http://gallery.iportnov.tech/image/Misc/hex_pyramid_6.png

http://gallery.iportnov.tech/image/Misc/torus_knot_fractal_3.png

http://gallery.iportnov.tech/image/Misc/torus_knot_fractal_4.png

http://gallery.iportnov.tech/image/Misc/torus_knot_6.png

http://gallery.iportnov.tech/image/Misc/bracelet-hex-metal3.png

http://gallery.iportnov.tech/image/Misc/city1.png

:)

**Comment by zeffii** [comment]
http://gallery.iportnov.tech/image/Misc/hex_pyramid_6.png  : )  definitely. The other could benefit from framing and delicate lighting, and then they would become exactly what i'm looking for. Despite what my example image suggests, i think the material is probably the least important..

**Comment by zeffii** [comment]
for instance here: https://n-e-r-v-o-u-s.com/blog/?p=507   form sells the image.

**Comment by enzyme69** [comment]
Good point Zeffii.

I will try to find my older BS Artworks that are worth presenting as examples of things Sverchok can do.

I have a plan to showcase Sverchok as animated procedural objects in Sketchfab.

**Comment by enzyme69** [comment]
![pxr_mario_006](https://cloud.githubusercontent.com/assets/3952687/23817577/4c616d8a-0648-11e7-8da1-a433bea626e4.png)
![001_15million_2000obj_23min](https://cloud.githubusercontent.com/assets/3952687/23817591/5d0a34a0-0648-11e7-9d3a-f9df53a6997c.png)
![blender_array_modifier2](https://cloud.githubusercontent.com/assets/3952687/23817604/6f6867fc-0648-11e7-9ba8-0cd44443d393.gif)
![black_dog_resampling_004](https://cloud.githubusercontent.com/assets/3952687/23817608/78b98e4e-0648-11e7-8e3b-ea29636fb0b1.png)
![hexagonal_monad_001](https://cloud.githubusercontent.com/assets/3952687/23817611/814b4f20-0648-11e7-9053-83de411baf8e.png)


![many_snail_007](https://cloud.githubusercontent.com/assets/3952687/23817614/8c38d290-0648-11e7-90ba-7d5a72130ac0.png)
![proxy_anim_test_002](https://cloud.githubusercontent.com/assets/3952687/23817617/925eb900-0648-11e7-84e0-4ef260df9070.gif)

**Comment by zeffii** [comment]
Thanks @enzyme69 , some comments.

- I like the mario render, but not the use of mario as the subject. Maybe the Blender symbol that way..
- the roundedboxes render looks a bit blown out with light
- the gif of the noise modified (whatever that is) deserves a smooth seemless render
- i like the dog/hexagrid/snails (but am not certain the snail image shows anything that isn't pretty simple with Blender already.. - correct me if i'm wrong)
- the little rotating objects (last image) ..maybe.. i don't know .. better framing, not simply in a grid.

**Comment by zeffii** [comment]
i'm thinking of having two galleries, a Render Gallery and a Technical Gallery.  
- The Render gallery is for stuff you would consider including in a portfolio applying to a design / architecture position (or student place)
- The technical gallery would maybe for conceptual examples and gists.

**Comment by zeffii** [comment]
show also the capacity to take control of random() with rules / logic / based on geometry or attractors

**Comment by portnov** [comment]
@zeffii 
How do you want to organize filling of galleries? I mean, will you fill it yourself after grepping this thread, or?...

Btw, one of possibilities is to open a group on deviantart.

**Comment by zeffii** [comment]
@portnov  a deviantart group makes sense, anything that will push the community to a little competition in the render quality. This could be separate from the http://nortikin.github.io/sverchok/ gallery, where the content is curated _super objectively_.

**Comment by enzyme69** [comment]
At some point Reddit /sverchok will be nice too.

**Comment by enzyme69** [comment]
Point Cloud 1 Million, just converting from original Mesh Data with Random Point Colors.
https://skfb.ly/66VAW

**Comment by zeffii** [comment]
make the point cloud not random colours, but the colours that would be logical on the crab on those points. Then I would use it as a technical example.  Use random values for debugging / understanding the system.. but conscious color choices based on rules/subject to show it can also be controlled.

**Comment by enzyme69** [comment]
Random walk MK2:
![random_walk_mk3](https://cloud.githubusercontent.com/assets/3952687/23831178/cc21c4f2-076f-11e7-9f14-55cf5a595cc5.png)

**Comment by enzyme69** [comment]
@zeffii I am thinking to make another Point Cloud example, but the one transferring texture.

**Comment by enzyme69** [comment]
![torus_knot_003](https://cloud.githubusercontent.com/assets/3952687/23844846/c7144bc0-0818-11e7-832f-8841cfb2e2da.png)

A bit of Sverchok coolness and Cycles geekiness... all procedural, that's the point.

**Comment by zeffii** [comment]
OK, _that_ looks less trivial, maybe even hard without Sverchok.

**Comment by zeffii** [comment]
the image " Random walk MK2 " goes for quantity over quality, it doesn't show me that the randomness is controllable.

**Comment by nortikin** [comment]
I have collected not renders, but gists
https://vk.com/topic-35076122_35054289
here

**Comment by zeffii** [comment]
also very important

**Comment by enzyme69** [comment]
A bit simplistic, but colorful:
![ring_gradient_002](https://cloud.githubusercontent.com/assets/3952687/24195117/a35c3a86-0f4c-11e7-98e9-c8fcd58aefb7.png)

**Comment by enzyme69** [comment]
3D Cross Hatching using Grease Pencil and Polygon Adaptive.
![screen shot 2017-03-26 at 22 07 23](https://cloud.githubusercontent.com/assets/3952687/24330728/abaa75f0-1270-11e7-9c4b-ef2508374d70.png)

**Comment by zeffii** [comment]
@enzyme69  i'm going to have to push you much harder , those look like technical demos... pretty colors .. but not enough personality.

**Comment by portnov** [comment]
This sort of things is possible without sverchok, but here everything is parametric...
![jug-1](https://cloud.githubusercontent.com/assets/284644/24620292/e35320e8-18be-11e7-8998-a51d144828d3.png)
![jug-2](https://cloud.githubusercontent.com/assets/284644/24620293/e3547fc4-18be-11e7-839c-908f5f9ce2bf.png)

**Comment by portnov** [comment]
![jug-3](https://cloud.githubusercontent.com/assets/284644/24620784/ccb426c8-18c0-11e7-8667-600b6817e0f5.png)

**Comment by zeffii** [comment]
try framing it ..giving it a real location
![image](https://cloud.githubusercontent.com/assets/619340/24621204/fe68f8bc-18a0-11e7-8b53-e4ebd346736d.png)

**Comment by nortikin** [comment]
it is too hard
rorshach drawings or something
like wooman in left with hairs or pump hat

**Comment by enzyme69** [comment]
@portnov That's great, make like 64 variations in height, width, like Dutch designer.

**Comment by portnov** [comment]
"Just a quick demo" taking 20 minutes on my computer to render...

![jug-5](https://cloud.githubusercontent.com/assets/284644/24672068/62d2c6a8-1995-11e7-9f2f-a50b2abc09cc.png)

Blend file in case someone with faster GPU wants to take this render to next level: https://www.dropbox.com/s/3ut09ondvjh6kfd/jug-1.blend.gz?dl=0
:)

**Comment by zeffii** [comment]
@portnov  i was hoping you'd do a scene..with vases in a honeycombe display case or something... 
![image](https://cloud.githubusercontent.com/assets/619340/24677476/3c158a0e-1987-11e7-99f3-a013d0c53964.png)

with tiny spotlights in the planks for extra scene lighing.. : )

**Comment by nortikin** [comment]
with pattern interpolation mk2 node?

**Comment by enzyme69** [comment]
![screen shot 2017-04-22 at 22 01 36](https://cloud.githubusercontent.com/assets/3952687/25304275/821b52f8-27a7-11e7-954d-9a1d56a14366.png)

It's a WIP, but was inspired by Sougwen Chung. Grease Pencil needs to be unleashed. 

Freestyle and outlining is so slow... I think Texture and Cycles material is way to go. No one has tried Texture with Alpha along curves with Grease Pencil, it would be so awesome like Chinese or Japanese Sumi-E Brush Strokes.

**Comment by nortikin** [comment]
freestyle have troubles with short edges. So, composite or use cycle material for that (normal orientation)

**Comment by enzyme69** [comment]
Cheers for tips @nortikin I don't know sometimes too much overlaps and failure with Freestyle. And Curves generates such high resolution mesh when rendered.

Somewhat this one renders ok... after simplification.
![screen shot 2017-04-23 at 11 38 56](https://cloud.githubusercontent.com/assets/3952687/25309780/871f5e80-2819-11e7-8da1-0ec77275d471.png)

**Comment by enzyme69** [comment]
The idea I want to generate some kind of "very expressive" and alive strokes. It should be animated like floating water. And I just draw like Grease Pencil strokes.

**Comment by zeffii** [comment]
That looks like bacon

**Comment by enzyme69** [comment]
@zeffii Hahaha.. maybe chewing gum. Bacon Sugar Cookie.

**Comment by enzyme69** [comment]
![mummy_003](https://cloud.githubusercontent.com/assets/3952687/25580567/7346e2ae-2ec5-11e7-977b-3c785105152e.png)

Grease Pencil and Sverchok. Inspired by Nitz Art.

**Comment by danbachm** [comment]
Hey Gang,
I just checked out this thread and wonder if I might help out a bit.
I am not really a node wrangler guy but try to recreate noodelings from blendersushi and other great online ressources. 
I have two weeks now, where I could help out setting up and rendering content since I have broke my foot and have nothing else to do :)

If you do not mind, you cloud send me blend files of your setups and I could set them up into nice images with some graphical continuity for a gallery of results. I can render different contents with a "standardized" look and feel. What I am not really proficent is setting up the noodles since I am more on the artist side and not on the math one. 

My idea is to also have a nice footer with the name of the artist who created the setup and the sverchok logo integrated.

What do you think? I you want to try me, share a scene you like and I spend some time on it, then we see where it is going.

**Comment by enzyme69** [comment]
![shredded_005](https://cloud.githubusercontent.com/assets/3952687/25663277/8cb9611c-305a-11e7-865d-b8a6702ee8ff.png)

More noodles thanks to uber awesome Zeffii Polyline node.

**Comment by enzyme69** [comment]
@danbachm We actually need a proper Sverchok logo that is simple and presentable.

Thanks btw for kind feedback on my random noodle-ing using Sverchok at BS. Feel free to use the GIST I put online and make your own artworks. 

My computer system cannot handle too much complex Freestyle, and usually my render is pretty basic. I don't have time to do proper lighting and material.

**Comment by enzyme69** [comment]
![screen shot 2017-05-19 at 21 38 00](https://cloud.githubusercontent.com/assets/3952687/26246273/87caee36-3cdb-11e7-9f46-f23878e056e4.png)

Probably another "tech demo".

Explanation:
- Sverchok providing emitter geo and instance geo, very easy to interactively adjust the result for instancing. Although the outcome is really only 1 instance objects, duplicated many times by Blender Particles Hair. Would be nicer if Blender accept multiple objects as Hair Instancing.
- I have 2 layers of Hair, where Hair 2 is instanced on top of Hair 1.
- On top of that Hair 2 got Sverchok instancing some fruits.

**Comment by enzyme69** [comment]
![hair_hack_001](https://cloud.githubusercontent.com/assets/3952687/26247113/be34e6c6-3cdf-11e7-94f3-0949276892a6.png)

Feels like dejavu, I am pretty sure I did something like this in the past. But more control thanks to Sverchok.

**Comment by enzyme69** [comment]
Just 2000 x example generated robotic armory design, utilizing Zeffii Voronoi 3D :)
https://youtu.be/Wryiz8XMsWY

**Comment by zeffii** [comment]
>  generated robotic armory design

This is more like a [Rorschach](https://en.wikipedia.org/wiki/Rorschach_test), where its resemblance to certain shapes is only as strong as the viewer's imagination. Calling this "design" I think is inappropriate. Design implies careful consideration and parameters that evolve and respond to the surrounding.

The distinction might be purely academic..  but words have meaning :)

**Comment by nortikin** [comment]
![9u2mbegluos](https://user-images.githubusercontent.com/5783432/26870573-10dc0c40-4b79-11e7-9244-fb9e1d0c2f3a.jpg)
![idqri0enpqm](https://user-images.githubusercontent.com/5783432/26870572-10db48c8-4b79-11e7-8916-5431aec73688.jpg)

**Comment by enzyme69** [comment]
@nortikin I quite like it, surrealism.

**Comment by enzyme69** [comment]
![screen shot 2017-06-21 at 19 12 41](https://user-images.githubusercontent.com/3952687/27376494-b3c6912c-56b5-11e7-9b5a-92c0c51f1b36.png)

@ly29 Adaptive Polygon, like Tissue Add-On actually stands quite powerful up to this day. There is a weird anomaly, but so far pretty happy that it can do this knitting stuff.

Ideally, we can use UV info, to project deform the UV with respected seam, and get a more beautiful knitting. That's for future study, I guess.

**Comment by enzyme69** [comment]
![knitting_hairy_001](https://user-images.githubusercontent.com/3952687/27432351-287b32a6-5793-11e7-8624-50439a5bae4e.png)

I learned a lot from this study of knitting. Actually @ly29 Adaptive Polygon has thought about this far far away ago, I am so impressed. Maybe even Adaptive Edge is related.

I also found out about Mira Add-On for Wrapping, and also getting used more with Tissue Add-On. Tissue Add-On tesselate is like Adaptive Polygon MK2, but I like how fast and interactive Sverchok Adaptive Polygon to generate hair edges. Amazing. Would be nice if Polygon Adaptive can randomly rotate the plate.

One could have used Hair and some kind of clever "at render time" rendering of curve into threads for maximum details.

There are few things to improve knitting, like retopology, to make sure each "polygon plate" is flowing more naturally.

If there is a book, this should be one of the chapters.

**Comment by AG89z** [comment]
Hello, I used Sverchok to generate and 3D print some parametric tiles and I wrote a tutorial about it if you want to see it:) Love Sverchok http://www.codeplastic.com/2017/07/06/parametric-tiles-with-blender-and-sverchok/

![codeplastic_017](https://user-images.githubusercontent.com/26380268/27909748-7872bc38-6252-11e7-8057-3b866bbcdd45.jpg)

**Comment by zeffii** [comment]
thanks for sharing @AG89z . If you encounter any problems, let us know.

**Comment by nortikin** [comment]
@AG89z try template in sverchok called 

> petri spiral scale

**Comment by AG89z** [comment]
@nortikin  Wow that's pretty impressive! I will try to work on that too

**Comment by nantille** [comment]
Hello all, 

Here's my first attempt at using Sverchok. I coded enough Python to dive easily into it when needed but here Sverchok really gave me the power to do complex things by hand with little effort. Thank you for this add-on!

The illustration is for a recent publication about connectivity in the brain by Eyal Gal. Some patterns appear in the connectivity of neurons, such as the "rich club" in the middle. The article was published in Nature Neuroscience. 

The original illustration is in A0 format so rendering alone took 14h on a 48-core workstation. :)
![structure_in_the_jungle_web](https://user-images.githubusercontent.com/10866779/28069747-d9a11f4e-664a-11e7-9286-6ccd41a14dba.jpg)

This is at 50% scale (yes, I could zoom in further).
![structure_in_the_jungle_detail](https://user-images.githubusercontent.com/10866779/28069746-d99d24c0-664a-11e7-8004-fc62e401c4e7.jpg)

**Comment by zeffii** [comment]
That made my day @nantille  :)

**Comment by nantille** [comment]
Thanks! ^^

**Comment by AG89z** [comment]
Wow amazing @nantille ! Would you mind sharing the node tree? If not never mind:)

**Comment by zeffii** [comment]
@nantille ,  Ah. i see !  https://www.nature.com/neuro/journal/v20/n7/pdf/nn.4576.pdf   also , nice to see  Idan Segev on that paper ( I did one of his Neurology Moocs a few years back )

**Comment by nantille** [comment]
@AG89z yes I could share the nodetree, but today my Holiday started. You'll have to wait for my return. ;)

@zeffii you know Idan ! What a small world ! I followed one of his moocs (intro to neuroscience) on coursera by chance several months before joining Blue Brain. Maybe that was your work?

**Comment by AG89z** [comment]
@nantille  haha all right ;)

**Comment by zeffii** [comment]
@nantille

> I followed one of his moocs (intro to neuroscience)

That's all i did too (but forgot exactly the title of the course), i was not involved with the production in any form.. just watched the videos and did the quizzes etc. Very interesting stuff.  Would take it again.

**Comment by enzyme69** [comment]
![screen shot 2017-07-19 at 15 33 00](https://user-images.githubusercontent.com/3952687/28352079-b877656e-6c97-11e7-894d-a793dc0d64c4.png)
![screen shot 2017-07-19 at 15 32 33](https://user-images.githubusercontent.com/3952687/28352078-b875e23e-6c97-11e7-80e8-d100753973b4.png)

I will render this properly when I got time.

**Comment by nortikin** [comment]
![1cb7qwtgg0q](https://user-images.githubusercontent.com/5783432/28353012-4b15e232-6c62-11e7-83c9-9e1ee5c53f32.jpg)

pillow generator (see post in G+ group)

**Comment by zeffii** [comment]
@nantille  is this interesting to you?  

https://twitter.com/Interstellate_/status/898606419364110336

https://www.drvtechnologies.com/neuroscienceawards

**Comment by nantille** [comment]
I'm back. ^^
@zeffii Yes these are interesting, as learning material. This drvtech thing is about microscopy images, something close to photography. Not my field since I design illustrations. However one of my colleague's research might be on topic. Thanks!

**Comment by nantille** [comment]
Hello, as promised, here's the complete sverchok node tree with the resulting curves/connections. I made a group that I used a lot, it's called "Vertices in region". It filters some vertices from a given group and allows me to draw connections between samples from regions (layers 1 to 6). There's also the material used for the connections. You can directly preview the scene, I think it should work. 
[connectivity_sverchok_tree.blend.zip](https://github.com/nortikin/sverchok/files/1242080/connectivity_sverchok_tree.blend.zip)
Cheers

**Comment by nortikin** [comment]
![default](https://user-images.githubusercontent.com/5783432/29998482-b84af086-9034-11e7-9ced-70042cabd7d4.png)
Spinner generator
you can print on 3d printer and insert iron part simply

**Comment by enzyme69** [comment]
@nortikin or anyone with 3D printer, let's print this!

**Comment by AG89z** [comment]
@nortikin They are very nice! I work  for a 3d printing company (Zmorph), we could print them out  and write an article about it if you want (either on the company's blog or informally on www.codeplastic.com). Let me know:)

**Comment by enzyme69** [comment]
Render is "Meh", but this has potential.
![suzanne_feather_004](https://user-images.githubusercontent.com/3952687/30020251-94e4af56-91a6-11e7-82ab-1fd1c238b54d.png)
![suzanne_feather_002](https://user-images.githubusercontent.com/3952687/30020252-94f54262-91a6-11e7-9995-091128faf23f.png)

**Comment by zeffii** [comment]
www.codeplastic.com is fun to read through., and especially satisfying to see the 3d printed results. i'm working through a python port of the processing code (which I think is itself a port from inconvergence's python code)

**Comment by enzyme69** [comment]
![prtscr capture_36](https://user-images.githubusercontent.com/3952687/30022793-3e048116-91b0-11e7-8ec9-d2b884b5388f.png)
![prtscr capture_35](https://user-images.githubusercontent.com/3952687/30022794-3e4cc5ac-91b0-11e7-8c65-8bd21ce8b415.png)
![prtscr capture_33](https://user-images.githubusercontent.com/3952687/30022795-3e66512a-91b0-11e7-838e-1544f16e691c.png)

**Comment by nortikin** [comment]
@AG89z
Your email, please.
Write: nikitronn @ yandex . ru
It have to be heavy, material plumbum or make hollow fill with water, but it may not rotate well.
Dimentions ofmechanism if you have, tell me.

**Comment by nortikin** [comment]
@AG89z 
Here is paper.
Mistake in heighting. will fix tomorrow.
[single.pdf](https://github.com/nortikin/sverchok/files/1275445/single.pdf)
Here is blend.
[спинер_2017_09_04_20_03.zip](https://github.com/nortikin/sverchok/files/1275449/_2017_09_04_20_03.zip)

**Comment by enzyme69** [comment]
Inspired by Sougwen Chung arts, this is the dance of Sine and Wave using Sverchok. OpenGL render. Will turn this into AR.
 
![bs_swc_004](https://user-images.githubusercontent.com/3952687/30041338-a7e90c7e-922c-11e7-8729-472685167aa4.png)
![bs_swc_003](https://user-images.githubusercontent.com/3952687/30041339-a7ebb7d0-922c-11e7-9bdc-19d781092f8c.png)
![bs_swc_002](https://user-images.githubusercontent.com/3952687/30041336-a7d7629e-922c-11e7-9c74-96adf53119a0.png)
![bs_swc_001](https://user-images.githubusercontent.com/3952687/30041337-a7d9690e-922c-11e7-8a73-4f35d794a68d.png)

**Comment by zeffii** [comment]
those are large images @enzyme69 .  also i'm struggling to see any real level of conscious control of the "signal". but hey.. i'm not your art teacher :) ... but I am the highly opinionated and objective curator of this gallery .

**Comment by AG89z** [comment]
@zeffii Thanks Zeffi, it's nice to hear that you like the blog :)
@nortikin Great thanks! We will make few prints and come back:) I think that they would also be very nice as necklaces.

**Comment by nortikin** [comment]
@AG89z please, read PDF before you make something

**Comment by AG89z** [comment]
First simple test:

![spinner](https://user-images.githubusercontent.com/26380268/30148440-bc171006-93a3-11e7-88b3-cfd191f85469.gif)

**Comment by nortikin** [comment]
https://vk.com/sverchok_b3d?w=wall-35076122_8933
![image](https://user-images.githubusercontent.com/5783432/30148527-7e12c634-93ac-11e7-861b-7d204caf88d6.png)
Иван Прытов made that layout (on link blend file in google docs, download now). He subscribed all the parts detailed, look at his nodes.

**Comment by nortikin** [comment]
![6](https://user-images.githubusercontent.com/5783432/30248164-76553afe-962b-11e7-9731-104d098e4630.png)
![5](https://user-images.githubusercontent.com/5783432/30248165-7656fc86-962b-11e7-88bc-ed97093afae0.png)
new fun with spinner. script node ALT+P making some 
[спинер_2017_09_10_10_26.zip](https://github.com/nortikin/sverchok/files/1290432/_2017_09_10_10_26.zip)
@AG89z

**Comment by nortikin** [comment]
![7](https://user-images.githubusercontent.com/5783432/30253441-c1bf1962-968d-11e7-9700-4296ff20ebd9.png)
my new approach give me more great result.

**Comment by AG89z** [comment]
![spinners_003](https://user-images.githubusercontent.com/26380268/30482879-126e95be-9a25-11e7-9387-6c8fa1f6be3f.jpg)

@nortikin I will send you an email with the pictures and prepare a small article for the blog and post it

**Comment by enzyme69** [comment]
For better 60 fps spin animation, maybe upload it to GFYCAT.

**Comment by nortikin** [comment]
cool

**Comment by AG89z** [comment]
Here's the article! http://www.codeplastic.com/2017/09/18/spinner-generator-with-sverchok/ Hope it's OK, if not I will fix it:) 
And here the images @nortikin https://drive.google.com/drive/folders/0B_5qJS1PZRJFOXdWQTRpUTIwcVk?usp=sharing

**Comment by enzyme69** [comment]
Some kind of Node Flow FX:
![nodeflow_002](https://user-images.githubusercontent.com/3952687/30575391-abf59964-9d43-11e7-83b8-0c532f360899.png)

**Comment by enzyme69** [comment]
I am going to colorize the shapes. Really I can make a unlimited mandala coloring book based on this.
![prtscr capture_57](https://user-images.githubusercontent.com/3952687/32029984-9e2b6b70-ba43-11e7-9424-891ccef148d0.png)
![prtscr capture_56](https://user-images.githubusercontent.com/3952687/32029985-9e5b1118-ba43-11e7-8e48-911660f0fdba.png)

**Comment by zeffii** [comment]
Mandalas lost my interest the moment it became easy to make them.

**Comment by enzyme69** [comment]
That's true, ideally we would build some kind of Temple like Candi Borobudur. Imagine some crazy detailed structure all made using Sverchok, then upload to Sketchfab for AR and VR. I like that.

**Comment by nortikin** [comment]
mandala generator of Gunnawan

**Comment by AG89z** [comment]
Having a good time with Variable Lacunarity and Easing 0..1
http://www.codeplastic.com/2017/11/06/raster-voronoi-with-sverchok/
![render_2](https://user-images.githubusercontent.com/26380268/32453823-9b1860cc-c31d-11e7-9872-eac4bd47b6d8.png)
![render_3](https://user-images.githubusercontent.com/26380268/32453824-9b378254-c31d-11e7-95b7-b50027b7fd0f.png)
![insta_252scaled](https://user-images.githubusercontent.com/26380268/32453825-9b4e44da-c31d-11e7-89a8-7a65cbcee142.jpg)

**Comment by zeffii** [comment]
would be interesting to make soundproofing with like 20 different tiles, to diffuse all over the place.

**Comment by AG89z** [comment]
Well having a wall full of those is on the list:P

**Comment by nortikin** [comment]
it should looks great and expensive.

**Comment by nortikin** [comment]
![028](https://user-images.githubusercontent.com/5783432/32971683-7cefba06-cbff-11e7-88fc-04fa24ef54a7.png)

**Comment by nortikin** [comment]
https://ello.co/search?terms=%23sverchok
Mark Dooney from London
Thanks to him

#b3d #sverchok #blender #cad #autocad
#architect #architecture #архитектура
#SV3D #forget_revit #forget_autocad
#python #addon #программирование

**Comment by AG89z** [comment]
![dsc08678_4](https://user-images.githubusercontent.com/26380268/33373428-29e655e8-d502-11e7-9269-ba66bb8a77d5.JPG)
I've decided to open a little Etsy shop for these tiles, in case you are interested following this [link ](https://www.etsy.com/shop/SinePanelsAndTiles?coupon=SVERCHOK20) there is a 20% discount :)

**Comment by portnov** [comment]
![multiext-1](https://user-images.githubusercontent.com/284644/33525602-c47d922e-d854-11e7-940f-f04a8018f0f1.png)

**Comment by zeffii** [comment]
use more light portnov!!

**Comment by enzyme69** [comment]
Light wise seems ok, maybe it's Filmic thing just adjust contrast, etc.

**Comment by zeffii** [comment]
well maybe it is a contrast/brightness issue, but  light it up man :)

![image](https://user-images.githubusercontent.com/619340/33526390-d64e7374-d840-11e7-9a4a-be613205ee3d.png)

**Comment by nortikin** [comment]
instagram @sverchok.3d
collection will rise

**Comment by portnov** [comment]
![loft-hex-plastic1](https://user-images.githubusercontent.com/284644/33807685-5d92fcb8-ddfc-11e7-93d6-d4fac7b8888b.png)

**Comment by portnov** [comment]
![loft-boxes-1](https://user-images.githubusercontent.com/284644/33899549-abf69404-df8d-11e7-817d-c866940357ae.png)

**Comment by portnov** [comment]
![loft-boxes-3](https://user-images.githubusercontent.com/284644/33901809-d45877c6-df94-11e7-81c5-203af9c6ef9b.png)

**Comment by Durman** [comment]
![2017-12-14_20-21-41](https://user-images.githubusercontent.com/28003269/34002987-86d456a8-e10d-11e7-87ff-ce71a7b20826.jpg)

**Comment by portnov** [comment]
![loft-hex-fractal-2](https://user-images.githubusercontent.com/284644/34077698-27910efe-e32c-11e7-872d-bba26007755d.png)

**Comment by portnov** [comment]
![loft-bricks-1](https://user-images.githubusercontent.com/284644/34174390-7f3e7174-e51a-11e7-8610-599117eb5e77.png)

**Comment by enzyme69** [comment]
This thread will end up becoming very huge :) 

By the way, if you are using Instagram, simply upload some nice render of Sverchok into Instagram with hashtag #sverchok, I have done some and recently Instagram has "Follow Hashtag" feature. Very handy.

@nortikin has SV special account as well.

**Comment by portnov** [comment]
![radio-hex-bent](https://user-images.githubusercontent.com/284644/34325956-6ccba08c-e8c3-11e7-8c38-44212ffd0c58.png)

**Comment by portnov** [comment]
![radio-hex-bent2](https://user-images.githubusercontent.com/284644/34327331-3cda8dbe-e8e3-11e7-9b68-43b01ea65058.png)

**Comment by desmarkie** [comment]
Hi!

You can grab the blend file for my animated gif ( https://github.com/nortikin/sverchok/issues/1342#issuecomment-345440691 ) here: http://markdooney.com/blender/sverchok-003.blend

:)

Let me know if you want any others, I'm not sure how tidy they are and I've just managed to ruin my install on 2.79 ahaha. Back to 2.78 for the mo.

**Comment by portnov** [comment]
https://www.deviantart.com/tag/sverchok

**Comment by portnov** [comment]
Render is WIP

![wavy_3](https://user-images.githubusercontent.com/284644/34342429-a19fa8a8-e9d1-11e7-959a-9a485e76ebc9.png)

Not a texture - but a proper mesh :) ~300k vertices, ~40sec update of sverchok tree, ~10min render.

**Comment by Durman** [comment]
something like a bench:

![bench](https://user-images.githubusercontent.com/28003269/34719435-4d393d7c-f554-11e7-8499-978879f56648.jpg)

**Comment by desmarkie** [comment]
Latest doodle, promised I'd post the files :)

The .blend has a handy group I use to loop a sin value over the total number of frames. e.g. 2x PI over 180 frames. Might be of use to anyone animating with Sverchok.

grab the file from http://markdooney.com/blender/sverchok-045.blend

<img width="216" alt="screen shot 2018-01-15 at 22 09 36" src="https://user-images.githubusercontent.com/338495/34963891-c137bd50-fa42-11e7-8ffc-7f2e008b255a.png">

[Video](https://twitter.com/desmarkie/status/952680011101868032)
![sv-045-f](https://user-images.githubusercontent.com/338495/34963534-fd893880-fa40-11e7-98f8-7d6ed4b12bc8.png)

**Comment by portnov** [comment]
![curve_contour_2](https://user-images.githubusercontent.com/284644/35114532-edea6b8e-fca6-11e7-9f37-72391786d35d.png)

**Comment by enzyme69** [comment]
Just modifiers combo (edge split - smooth) randomized using Sverchok: 
<img width="1235" alt="screen shot 2018-01-21 at 12 07 47 am" src="https://user-images.githubusercontent.com/3952687/35183739-317f576c-fe3f-11e7-9284-b00a4f15a191.png">

Edge Split node in SV would be handy, we don't have it, maybe one day.

**Comment by zeffii** [comment]
> Edge Split node in SV would be handy, we don't have it, maybe one day.

https://github.com/nortikin/sverchok/issues/1305 .  please use the search before saying ", we don't have it, "

**Comment by Durman** [comment]
![default](https://user-images.githubusercontent.com/28003269/35208194-70e7a856-ff60-11e7-9273-a6d293ec8e61.jpg)

**Comment by enzyme69** [comment]
Just wondering what would be better than long GitHub thread to store all these SV Gallery. Flickr is kind of okey right? 1 TB free.

**Comment by nortikin** [comment]
https://user-images.githubusercontent.com/5783432/35446607-4f812ed0-02c6-11e8-8dab-7fb539b3b572.png

**Comment by desmarkie** [comment]
@nortikin @enzyme69 Is it worth having another repo just as a gallery? Would allow you to host it on 
https://pages.github.com/ and people could submit images as a pr.

**Comment by nortikin** [comment]
![sverchok_transformation template1](https://user-images.githubusercontent.com/5783432/36561783-d9c098a0-1825-11e8-8a1f-d9026e3f90c8.png)

**Comment by nortikin** [comment]
@desmarkie 
if you wish you can edit this site: http://nortikin.github.io/sverchok/
here: https://github.com/nortikin/sverchok/tree/gh-pages
add your images, extend gallery. Old images with links in currect gallery can be removed.
Make this page great again :copyright:

**Comment by desmarkie** [comment]
Cheers @nortikin, I'll make it a side project

**Comment by nortikin** [comment]
![buddah_8](https://user-images.githubusercontent.com/5783432/40021128-af737da6-57cc-11e8-9c01-1ece79a17e54.png)

**Comment by nortikin** [comment]
![decorative_element](https://user-images.githubusercontent.com/5783432/41176908-d29de68e-6b6a-11e8-9a3e-24070abadea6.png)
generative decorative element on hilbert filtered vertices
https://vk.com/sverchok_b3d?w=wall-35076122_9718

**Comment by nortikin** [comment]
![decorative_elemennt](https://user-images.githubusercontent.com/5783432/41179959-45c0386a-6b75-11e8-9746-a74fd97d3412.png)

**Comment by AG89z** [comment]
Hello, I wrote a short ebook about Sverchok. Once I will finish to review it I will put it for free on my blog. I would like to have some comments/impressions first though. Here it is 
[Learning Sverchok.pdf](https://github.com/nortikin/sverchok/files/2775469/Learning.Sverchok.pdf)

**Comment by nortikin** [comment]
ok, i have red the learning.sverchok.pdf

added comments in my previous post. maybe continue conversation in email
