### ISSUE TITLE
Moving Like Turtle or Snail - NumPy CumSum

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1345]
I've been wanting to make video tutorial that compares Python Turtle and Sverchok.
https://gist.github.com/7f6e8e0b40c829b892ce3aeebf2f4ab7

![screen shot 2017-03-11 at 22 09 03](https://cloud.githubusercontent.com/assets/3952687/23822755/69ecc4d0-06a7-11e7-8d84-44d84e85ba76.png)

They are quite different of course. And normally in node we piggy back in order to get that kind of step by step movement.

This is probably not quite different to "Random Walk" but interesting nevertheless.

Now... 

If I were to provide list of step to move like below:
![screen shot 2017-03-11 at 22 11 00](https://cloud.githubusercontent.com/assets/3952687/23822766/a96a07d0-06a7-11e7-941d-e153475f82e8.png)

Can we make it so that the Turtle moves one step at a time?

**Comment by enzyme69** [comment]
Wait the minute... that's odd..

![screen shot 2017-03-11 at 22 14 43](https://cloud.githubusercontent.com/assets/3952687/23822790/28df25c2-06a8-11e7-97ef-75a91ad2e68b.png)

**Comment by enzyme69** [comment]
Oooh.... that thing does not "move" accumulate, but keep moving within -1, -1, -1 and 1, 1, 1 bounding point.

**Comment by enzyme69** [comment]
I am trying the NumPy thing... just like Pizza example. But I think I did it wrong:

![screen shot 2017-03-11 at 22 31 17](https://cloud.githubusercontent.com/assets/3952687/23822898/86761158-06aa-11e7-807c-3d4a3c866abf.png)

https://gist.github.com/490d6d411b91195a2d8b79e20bebabea

**Comment by enzyme69** [comment]
![screen shot 2017-03-11 at 22 35 58](https://cloud.githubusercontent.com/assets/3952687/23822926/1e1bb99a-06ab-11e7-8b3c-103816fef64c.png)

NumPy does not work the Vector ..... interesting.

**Comment by enzyme69** [comment]
Maybe I did the right thing here:
![screen shot 2017-03-11 at 22 46 44](https://cloud.githubusercontent.com/assets/3952687/23823003/a11d5cbc-06ac-11e7-90e0-c181b194f052.png)
https://gist.github.com/a4bd54fb5803f31b53a0e1997ac3549b

Accidentally.

**Comment by enzyme69** [comment]
Got it!

https://gist.github.com/90236bd4a5ca27d7388e8e1ed3b8cde8

**Comment by enzyme69** [comment]
At some point, need to think in term of Rotate and Move, but this is ok for now, I guess.

**Comment by nortikin** [comment]
Me proud of you, Jimmy

**Comment by enzyme69** [comment]
![screen shot 2017-10-11 at 20 14 06](https://user-images.githubusercontent.com/3952687/31431956-ec30e7b6-aec0-11e7-836c-24596d8156a1.png)
![screen shot 2017-10-11 at 20 14 00](https://user-images.githubusercontent.com/3952687/31431957-ec6889e6-aec0-11e7-9224-86010aef30f1.png)
![screen shot 2017-10-11 at 20 13 48](https://user-images.githubusercontent.com/3952687/31431958-ec9fa692-aec0-11e7-9b62-d5a43d169880.png)

Monad inside Monad to CumSum.

[numpy_cum_004_2017_10_11_09_14.zip](https://github.com/nortikin/sverchok/files/1374932/numpy_cum_004_2017_10_11_09_14.zip)

Unfortunately Sverchok monad or loop and iterate and reassign. Yet.
