### ISSUE TITLE
Auto-Update OFF

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1347]
When working with a really big mesh data, connecting and disconnecting noodles become a chore, because for every parameter changes, Sverchok is doing this very long calculations.

Perhaps, similar to Animation Nodes, we need a way to control baking of:
- frame changes
- parameter changes
- nodes being created

Or a more controlled baking.

**Comment by ly29** [comment]
Please list precisely what controls are missing from the layout manager in the side panel.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23831108/4dd53c1e-071a-11e7-95de-5a72dd9b7e31.png)

**Comment by ly29** [comment]
The images in the documentation needs to be updated.
http://nikitron.cc.ua/sverch/html/panels.html#node-tree-panel

**Comment by enzyme69** [comment]
Ok that's the one... Not so obvious even for me that has been using Sverchok years :) Cheers!
