### ISSUE TITLE
bug hunt: bevel node or remove doubles

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1350]
![image](https://cloud.githubusercontent.com/assets/619340/23832613/5a807046-0738-11e7-908d-f3dc2e18e0f2.png)

https://gist.github.com/1f9c2105e021c8ac91594265a8965c22

**Comment by ly29** [comment]
Bevel wraps the data one extra time causing remove doubles to fail.

**Comment by ly29** [comment]
Spot the extra ```[ ]``` around each separate list object in the list comprehensions 
```python

        oV.sv_set([[i[0]] for i in out])
        if oE.is_linked:
            oE.sv_set([[i[1]] for i in out])
        if oP.is_linked:
            oP.sv_set([[i[2]] for i in out])
```
https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/bevel.py#L129-L133

**Comment by zeffii** [comment]
excellento, yes @ly29  . that processing func could be much shorter.. am tempted to redux it.

**Comment by ly29** [comment]
I mostly want to go all pep8 over it.

**Comment by ly29** [comment]
@zeffii 
I am working with javascript at the moment so some simple Sverchok bug hunting I can do in my sleep. So much subtle things going on in javascript...

**Comment by zeffii** [comment]
am suprised you haven't tried to build a webbased sverchok like tool already. sooner or later everything is emulated in js.

**Comment by ly29** [comment]
not sverchok like at all, just really simple javascript things right now. (for real a minesweep clone to learn right very trivial but still so many things to deal with)

am tempted to do something like sverchok for the web, just to try, with webgl and obj export etc.

**Comment by zeffii** [comment]
js has become quite nice ,  _arrow functions_ and all that es6/7/harmony whatever they call it now..

**Comment by ly29** [comment]
the lambda syntax with arrows is one of things I wish they had done right in python.

**Comment by zeffii** [comment]
pushed.
