### ISSUE TITLE
Color extended generators nodes

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1352]
Can we color the extended generators greenish ? not the same green as the main generators, but a slightly different green color to indicate they are generators to distinguish them from the rest of the nodes? 

![extendedgenertorcolors](https://cloud.githubusercontent.com/assets/2083719/23833821/c4579ede-0721-11e7-9328-b37ed3212592.png)

**Comment by zeffii** [comment]
i don't see why not,

**Comment by DolphinDream** [comment]
oops.. spoiler alert (working on a MK2 plane node.. similar update as for the line mk2 node) :)

**Comment by zeffii** [comment]
but please compact that PlaneMK2 ui.  
- sizeX sizeY on one row / (align=True)    (and add a way to lock X/Y.. if one changes, the other updates too)
- maybe Separate/Center/Normalize one one row too  and add (toggle=True)

**Comment by DolphinDream** [comment]
@zeffii  Similar to the UV connect toggle buttons ?

**Comment by zeffii** [comment]
yeah,   but actually of those suggestions I think the locking feature is what I really want to lobby for.

**Comment by zeffii** [comment]
btw, scripted nodes are not to be coloured differently :) extended or not.

**Comment by DolphinDream** [comment]
I’m not lobbying for the scripted nodes .. yet :) Only for the generator extended.

**Comment by DolphinDream** [comment]
@zeffii can you elaborate on the “locking” feature? you want the sizeX and sizeY to update at the same time? Perhaps lock them to the same size? (symmetric x/y size?)

**Comment by zeffii** [comment]
new thread fine.   like photoshop has locking to resize an image width if you update height.

**Comment by zeffii** [comment]
there's a sverchok theme setting, you should change it there too.. but don't modify scriptnodes as mentioned.

**Comment by DolphinDream** [comment]
Sweet. i’ll pull a request soon.

**Comment by enzyme69** [comment]
@nortikin make some kind of color scheme at some point, it works sometimes, but not always working.

**Comment by DolphinDream** [comment]
@enzyme69 there seem to be two themes (default, and Nippon Blossom) you can chose from in the sverchock add-on settings. The color for the generator extended was added to both these themes.

**Comment by nortikin** [comment]
@enzyme69 it can not work because alpha and beta nodes not placed right and some categories not colored also

**Comment by zeffii** [comment]
you'll be incorporating this in the User prefs revamp.. so can close?

**Comment by DolphinDream** [comment]
Yes. That was the plan.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24407854/648361ac-13cc-11e7-9ba6-71b1c6e08e81.png)

**Comment by DolphinDream** [comment]
Revisiting this.. any reason why the extended generators are not colored the same as the main generators ? or if not, get a similar color (as proposed in this issue) ?

**Comment by zeffii** [comment]
no reason, just motivation.
