### ISSUE TITLE
Brainstorming about Plane MK2

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1353]
I stared to revamp the Plane node (similar to the changes I made for the Line MK2). Sure, i’ll make sure to preserve the list of list vectorization built into the node (which is similar to vectorization in the line node). 

Here’s the preview of the node UI.

XY/YZ/ZX orientation will generate the plane grid in the corresponding plane.

When normalize is ON, the sizeX,SizeY fields are displayed to allow user to select the plane X/Y sizes.

![planenodemk2-example1](https://cloud.githubusercontent.com/assets/2083719/23834055/f4f38c8e-0725-11e7-9677-6502ea2db84d.png)

**Comment by DolphinDream** [comment]
@zeffii  you were saying something about locking the sizeX/sizeY normalization ?  can you please elaborate here?

**Comment by DolphinDream** [comment]
Btw, should the MK2 generator nodes be made extended generators or just generators ?

**Comment by zeffii** [comment]
ico = LINKED  ,   UNLINKED
![image](https://cloud.githubusercontent.com/assets/619340/23834168/1d2ce6c4-0752-11e7-86cc-5e5d383dafc6.png)

sometimes we want to set stepX the same as step Y so we end up sticking a socket in both.. but a way to link values would be great. I almost never want to have separate step sizes.

re _generators_ or _generators extended_  , maybe initially extended - this is really up to @nortikin i think.  ( i'm OK with either )

**Comment by DolphinDream** [comment]
@zeffii any ideas how to disable a property callback function so that I can sync the values without triggering a cascading callback?

**Comment by DolphinDream** [comment]
I figured out a work around the cascading callback issue, btw, using a synching flag to keep track when the synching is in progress and break the cascade. It’s in the planeNodeMK2 pull request.

**Comment by nortikin** [comment]
why not place to generators and place old plane line to folder old_nodes?
