### ISSUE TITLE
To Test Procedural Selection in Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1355]
I have an interesting problem:
![screen shot 2017-03-13 at 09 44 00](https://cloud.githubusercontent.com/assets/3952687/23836775/ba290906-07d1-11e7-8bd6-dc1767d65364.png)

Let say, I created the twisted torus and wanting to select every Edge Loop that goes twisting.

I think @portnov selector can do the job, but it can be tricky. First need to know the pattern of this looping edge.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23848774/fdd4dcb4-07d8-11e7-9b95-f80905d43d6d.png)

List modifier has a nice ' Mask subset A in B ' mode.

**Comment by zeffii** [comment]
if you can't see a pattern immediately, use less geometry (Recreate.. fewer Major/Minor segments..) if there's no pattern even then... there might not be a numerical pattern. In this case there is.

**Comment by zeffii** [comment]
unfortunately `bmesh` doesn't have an operator for 'select edge loop from given index' , which admittedly would be pretty handy

**Comment by enzyme69** [comment]
Thanks for the hints Zeffii. I'll give this a think.
