### ISSUE TITLE
Point Viewer Draw in RGB Color

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1356]
Probably more like not so urgent request. But would be nice if we can see Points in full RGB Color to help to show Point Cloud in color.

![screen shot 2017-03-13 at 12 02 06](https://cloud.githubusercontent.com/assets/3952687/23838014/0937d1fe-07e5-11e7-9ccc-ea11b18ff743.png)

**Comment by enzyme69** [comment]
I can always do this each time, but this generates X extra number of mesh just for viewing. Well I can always reduce the numbers by Vector Interpolation resampling, but then...

https://gist.github.com/f432b6cd0c365033fdbc9a50cc8e8a96

![screen shot 2017-03-13 at 12 06 38](https://cloud.githubusercontent.com/assets/3952687/23838057/929e5fe4-07e5-11e7-993a-f818febd9065.png)

**Comment by zeffii** [comment]
I've been meaning to add a generic 3d view callback to make it easier to add stuff like this.

**Comment by zeffii** [comment]
the callback is added, i expect some interesting additional viewer will emerge.

nothing more to say here.

**Comment by zeffii** [comment]
see: https://github.com/nortikin/sverchok/pull/1359#issuecomment-286070591

**Comment by jotero3d** [comment]
nice idea :)
https://goo.gl/photos/Z7DcLnLaGR1xW8KG7

**Comment by nortikin** [comment]
g+ sverchok group published
