### ISSUE TITLE
Closed Bspline twisting error in polyline viewer

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1360]
[error_polyline_001_2017_03_13_10_51.zip](https://github.com/nortikin/sverchok/files/837951/error_polyline_001_2017_03_13_10_51.zip)
![screen shot 2017-03-13 at 21 50 37](https://cloud.githubusercontent.com/assets/3952687/23851330/3a3145a4-0837-11e7-8396-6966278634af.png)

@zeffii Either there is a bug or I am doing it wrong here.

**Comment by enzyme69** [comment]
The twisting is correct if I have BSpline off (closed) and then I smooth it.

![screen shot 2017-03-13 at 21 57 17](https://cloud.githubusercontent.com/assets/3952687/23851546/0699b2f2-0838-11e7-96f2-1b7615b8c889.png)

But I do want proper BSpline and Twist to work.

**Comment by zeffii** [comment]
> But I do want proper BSpline and Twist to work.

maybe you want to rephrase that.

**Comment by zeffii** [comment]
also..you have 31 twist values, for 30 points.

**Comment by zeffii** [comment]
and i think the twist isn't supposed to be 'rotary' where you can just twist it 360 degrees to match up with 0 degrees...

**Comment by enzyme69** [comment]
Sp... if I am using BSpline, the Twist cannot work properly?

If BSpline is turned off, and I checked Closed, the Twist can sort of rotary perfectly, with the right number.

**Comment by zeffii** [comment]
it's not a scenario I had tested, Someone could write a simple script and as blender devs if the output is expected/normal/ if not then can it be fixed?

**Comment by zeffii** [comment]
it looks like the very last tilt value is flipped , if closed + bspline

**Comment by zeffii** [comment]
i'll look at it tomorrow.
