### ISSUE TITLE
Image Sequence / Movie

### ISSUE THREAD

**Issue by Vi-dot** [nortikin/sverchok#1361]
Hello,

I'm looking for a node like **Image Generator** but with an _Image Sequence_ instead of a _Single Image_.
Then grid will follow an animation made of images black & white.
Is there something existing near that ?

We can do that with DupliVerts in Blender, but the duplicated objets can't have collision physic.

Thanks

**Comment by kalwalt** [comment]
Hi @Vi-dot, i'm developing an upgraded version of the [`Texture viewer node`](https://github.com/nortikin/sverchok/blob/master/nodes/viz/texture_viewer.py) that  will let us to save a sequence of images, or better say a frame animation. At the moment i haven't a fork to show the code, i hope soon as possible to apply some improvements. 

> Then grid will follow an animation made of images black & white.
Is there something existing near that ?
> We can do that with DupliVerts in Blender, but the duplicated objets can't have collision physic.

Sorry, not sure to understand what do you mean...

**Comment by Vi-dot** [comment]
Hello @kalwalt, thank you for your answer

I'm not sure, but **Texture viewer node** is more an `output`, unlike **Image Generator** is an `input`.

I may not express myself clearly, what I would like to do :
- Make a grid of cloned objects
- Black&White images (Image Sequence) make grid move with wave effect
-> each cloned object can move on Z axis regardless others, depending on current B&W image

(with `DupliVerts` and `Displace modifier`, we can do that, but we cannot add a collision physic on duplicated objects)

**Comment by zeffii** [comment]
@Vi-dot we haven't explicitly added support for image sequences, primarily because our focus hasn't been motion graphics / animation. There's not much stopping us from upgrading the node or adding an Image Sequence node - except of course _time and incentive_.

( Generators -> Image (bl_idname ImageNode ) - is one of the older nodes in our toolkit, i might have a stab at it.

**Comment by Vi-dot** [comment]
@zeffii Ok I understand, and your plugging looks huge. It's a long time that I didn't use Blender, then I didn't know your plugging, but your features look very wide.

If you find time for it, that would be great !

**Comment by zeffii** [comment]
>  Ok I understand, and your add-on looks huge.

it has a lot to offer both users and python heads.

**Comment by zeffii** [comment]
I think @enzyme69  accidentally had a setup where he was reading the image of a sequence on each frame.. can you remember / show ?

**Comment by enzyme69** [comment]
I might cheat it by replacing the image using script node or expression?

**Comment by enzyme69** [comment]
Blender can load Image Object as sequence, but I just tested, Sverchok does not update the data via Image Decompose.
![screen shot 2017-03-15 at 17 49 45](https://cloud.githubusercontent.com/assets/3952687/23936746/df654252-09a7-11e7-912f-3f4d01a77e60.png)

**Comment by zeffii** [comment]
no you have some kind of frameset of the muybridge cat running.
https://goo.gl/images/kwVbCK

**Comment by enzyme69** [comment]
![sv_ppap_1](https://cloud.githubusercontent.com/assets/3952687/23936913/c8c45a3c-09a8-11e7-83f4-01b3c727639e.gif)
Oh maybe I use SV Image...?

**Comment by enzyme69** [comment]
Sometimes ... if we set correctly in Blender, it auto-update the frame that Sverchok can read. I'll have to check my old live noding.

**Comment by zeffii** [comment]
i was hoping never to see ppap again. come on jimmy.

**Comment by enzyme69** [comment]
@zeffii With Muybridge, I am using my "Displace Modifier" trick.

We know that Image Sequence works with Displace Modifier, and based on the displace change XYZ, I am piping it into Sverchok for other means.

It's funny how Image and Image Decomposer behave differently when it comes to reading the image :) @zeffii  You made both node right?

**Comment by enzyme69** [comment]
@zeffii Sorry it's the only image sequence I have. Will test again using Muybridge.

**Comment by enzyme69** [comment]
Ok so SV Image, when we pass in Image Sequences and run Alt+A while in Image context, will produce a realtime animated result. 
![sv_muy_001](https://cloud.githubusercontent.com/assets/3952687/23937104/e168dc6a-09a9-11e7-9dd5-55dff0837b07.gif)

I remember, SV Image has limit of 100 x 100 pixels only. Too bad.

Image Decomposer can do higher rest.

Maybe it's about time to upgrade or to have a node that deals with Image Sequence? 

I did manage to use Object ID Image and pixels[:] trick.

**Comment by zeffii** [comment]
> It's funny how Image and Image Decomposer behave differently when it comes to reading the image :) 

i did the decomposer, ( see difference https://github.com/nortikin/sverchok/issues/835#issuecomment-242968378 ) 

i already have a branch for a new sv image node.. no ETA

**Comment by enzyme69** [comment]
Ok thanks @zeffii 

For now @Vi-dot You can set the system that reads Image RGBA this way:

![screen shot 2017-03-15 at 18 17 50](https://cloud.githubusercontent.com/assets/3952687/23937462/cbbd414c-09ab-11e7-88e2-4072d209c4f0.png)

The Image Sequence will work automatically via Blender. If your mouse is hovering on the UV/Image Editor, it will force update the image and you can bake whatever data into Sverchok as type of mesh or anything.

**Comment by enzyme69** [comment]
No fancy Skip Pixel, just 1:1 sampling of every points. Maybe can be remapped somewhat.

Scatter random point sampling. If you want Scattering Random points, you can use my Displace Modifier techniques.

GIST:
https://gist.github.com/e09866cb3c608f94ad1c08f5b00584e1

**Comment by zeffii** [comment]
a step by step guide
1. open UV editor, load image
2. select all of the images that are part of your sequence
3. press Open Image
4. in the N panel toggle 'Auto Refresh' to on.
5. notice now when you scrub around in the UV editor bottom timeline that the image updates accoringly.
5. now there's several ways to do this.. most of this involves beta nodes which are relatively stable (and should be moved out of beta and into their own group soon )

![image](https://cloud.githubusercontent.com/assets/619340/23940170/32807a22-0964-11e7-8769-42658999a0a3.png)

the SV image node method should also work fine with Auto Refresh on..

**Comment by Vi-dot** [comment]
Hello,
Thanks for your help !

Yesterday I found a way to do it without Sverchok, but it lose the possibility to edit the reference object to change all others, the duplication has to be applied.
1. Create a Plane with DupliVerts link to the Reference Object
2. Apply DupliVerts ("Make real..")
3. Parent Cloned Objects to Plane using "Vertex", then they are going to be stick to each vertex. Vertex and Center of Objects have to be to the same global position.
4. Now you can add a "Displace" modifier on Plane

As it's very usefull to can edit the reference object, I'm going to try your way.
