### ISSUE TITLE
Mesh Eval Node... needs documentation?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1362]
@portnov 
Need your guidance on this node. I am very curious. It seems to output JSON but Text In node refuses to take it.

![screen shot 2017-03-14 at 21 52 30](https://cloud.githubusercontent.com/assets/3952687/23897285/a4db3af8-0900-11e7-8a4c-76ff082ea83c.png)

It seems to nicely turning mesh into text ascii. Would be nice if we can just put int some variable.

**Comment by zeffii** [comment]
@enzyme69 
https://github.com/nortikin/sverchok/issues/1304

did you read this?

**Comment by zeffii** [comment]
closing. please continue talk on the original thread.

**Comment by enzyme69** [comment]
Roger that.
