### ISSUE TITLE
options={'ANIMATABLE'} not needed but how to get F-curves in GraphEditor

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1364]
I noticed some props have the options={ANIMATABLE} and from what I understand this is to that f-curves are created for the given properties when they are keyframed. I tried to keyframe such parameters in SV nodes but I can't see any f-curves in the f-curve editor. Am i missing anything? Btw, is it possible to use f-curves with the keyframed SV node values ? 

If these ANIMATABLE options are not used can we remove them from the props?

**Comment by zeffii** [comment]
according to the docs `ANIMATABLE` is the default option, when unset .

f.ex:
```
bpy.props.BoolProperty(name="", description="", default=False, options={'ANIMATABLE'}, subtype='NONE', update=None, get=None, set=None
```

**Comment by DolphinDream** [comment]
@zeffii So, then it can be removed form SV props to shorten the code. And as for second part of my question.. can f-curves be used with sv nodes?

**Comment by zeffii** [comment]
yes, feel free to remove them from your own nodes. I tend not to add that argument. but sometimes when resuscitating an old node it gets copied over :)

regarding F-Curves, they are not automatically added with keyframes of bpy.props, i'm not sure if we are underdefining the node class or something.. but .. we haven't needed F-Curves, so hasn't bothered us.

**Comment by zeffii** [comment]
weirdly enough:

![image](https://cloud.githubusercontent.com/assets/619340/23911262/880944f2-08dc-11e7-88c0-dac87591930d.png)

**Comment by DolphinDream** [comment]
Interesting indeed. What does that mean?  The f-curves are created but not displayed in the f-curve editor ? Do the f-curves have to be connected to an object in the scene to be displayed i wonder ? 

Btw, I remember that keyframing nodes in the material or compositor editor will not show the f-curve of that property i keyframe unless the node for that property is elected.

**Comment by zeffii** [comment]
> have to be connected to an object

That's what I think, but it might also just be a feature which isn't enabled for the `NodeTreeAction` generated by custom node trees ,

**Comment by zeffii** [comment]
Changing the title because the latter question isn't dealt with yet. Ideally we focus on one question per issue, but it's understandable that this often doesn't pan out that way.

I asked yesterday in IRC / freenode but got no response, will try again today.

**Comment by zeffii** [comment]
http://blender.stackexchange.com/questions/75793/showing-nodetreeaction-fcurves-in-grapheditor-generated-by-custom-pynodes

either this or a bug report. closing for now / unless there's something we can do on our end.

**Comment by nortikin** [comment]
i will try to avoid with custom properties on fly. because it handle on scene/object RNA, but not in nodes. Will bind to values for float-int nodes.
But it should slow down all when checking for animation values. maybe make flag for f-curve to display. Only int/float values. Maybe collection property.

**Comment by Durman** [comment]
I can't agree that we haven't need in f-curves for our needs. 

We already have `Easing` node and `draw_override_complex` script but first is appropriate for simple cases only and second is not too comfortable to use. 
I don't mean to use f-curves for animation of course but for getting more complex number sequences. We have `Range int/float` node that gives linear sequence but with f-curves Sverchok could become much more powerful.

![2018-06-22_18-02-58](https://user-images.githubusercontent.com/28003269/41780766-b6c5efec-7646-11e8-8b8f-3f7b9e2bbfd1.png)

**Comment by zeffii** [comment]
`draw_override_complex` is a super ugly, but necessary, hack.

we could make a dedicated "FCurve sampler at frame", that evaluates a selected FCurve at 
   - either current frame or 
   - requested frame (via input socket for frame number...)

you would need to create an object ( I suggest an empty) and use something like the `X axis-location-over-time` to evaluate/sample from.

As discussed above Blender devs already suggested Fcurves in grapheditor would not be made available for custom node tree properties. This could change in the future, maybe it will now AN coder was working on 2.8.

**Comment by zeffii** [comment]
i may make such a sampler node, if there's interest!

**Comment by Durman** [comment]
As i see this node should expect to get values for X axis (timeline) and return Y coordinates according f-curve that it has got. 
I have done an example how this can be used.
[fcurve_2018_06_22_17_04.zip](https://github.com/nortikin/sverchok/files/2128509/fcurve_2018_06_22_17_04.zip)
There is great interest in having such node i think, it would be nice if you had a go at this direction.))

![2018-06-22_20-51-21](https://user-images.githubusercontent.com/28003269/41789326-f64a2390-765f-11e8-8bff-c99b22c1868f.png)

**Comment by zeffii** [comment]
OK! :)

**Comment by Durman** [comment]
More experiments, )) 
Mesh becomes more subtle 

![f-curve spiral](https://user-images.githubusercontent.com/28003269/41792880-5ec05e84-766b-11e8-9513-7cb8cd89cefa.gif)

**Comment by zeffii** [comment]
maybe it makes to have several modes for this..

- default:  one value (take frame number, or if unconnected input..use `bpy.context.scene.current_frame`)
- multi_sample: take a sequence (a range) and generate the evaluated range
