### ISSUE TITLE
CSG Boolean fails on Suzanne

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1366]
Just now, I am making this piggy-back of monad to do cutting, and works really well on simple geometry:
![screen shot 2017-03-15 at 11 09 46](https://cloud.githubusercontent.com/assets/3952687/23927774/e8e0ff20-096f-11e7-980e-2e7399998557.png)

However, I realized it will not work on Suzanne. perhaps some kind of max recursion issue in the node.

[boolean_combo_monad_006_2017_03_15_00_08.zip](https://github.com/nortikin/sverchok/files/843052/boolean_combo_monad_006_2017_03_15_00_08.zip)

Wonder if this is fixable. I know the fact that cutting through something like Suzanne eyes edge ring is pretty bad process...

**Comment by zeffii** [comment]
- suzanne is not a closed object.
- the CSG node is implemented in python, and works best on simple geometry.. Maybe Blender devs will add a bmesh.ops for booleans, that would speed up things a little, but until then stick to simpler geometry.

**Comment by zeffii** [comment]
these are some of the reasons the node won't leave the Beta category any time soon.
