### ISSUE TITLE
Simple Extruding of Region -- does it need to be this complicated?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1367]
![screen shot 2017-03-15 at 17 21 56](https://cloud.githubusercontent.com/assets/3952687/23936061/f3c0eb42-09a3-11e7-950b-77a773778ed4.png)

I am testing a simple extrusion, but it seems for me that Selecting and Extruding Region, eventhough we have nodes to help with extrusion seems to be still pretty complicated.

One second, I will check and compare with Houdini....

**Comment by portnov** [comment]
You can pass Polygons from Cylinder right to Extrude Region, do not need to use List Mask (it is required only if you want to preview mask in Viewer node). And connect FacesMask from Selector to ExtrudeRegion's Mask.

**Comment by enzyme69** [comment]
Aha... like this @portnov 
![screen shot 2017-03-15 at 17 30 40](https://cloud.githubusercontent.com/assets/3952687/23936266/22cd1270-09a5-11e7-9530-d506684efa05.png)

**Comment by enzyme69** [comment]
Thanks I will practice~

**Comment by enzyme69** [comment]
![screen shot 2017-03-15 at 17 38 15](https://cloud.githubusercontent.com/assets/3952687/23936414/32dd1fb0-09a6-11e7-868b-a1ce885c6a26.png)

Houdini one for comparison. It has a couple of Grouping method including expression, something that probably Sverchok also can do in its own way.

The one that is missing that is probably can be useful is Extrusion Division number. And perhaps extrude with spline, but that's probably for future developer task.

Cheers @portnov I will study your Selection node.

**Comment by enzyme69** [comment]
(Houdini glitchy UI is annoying.)

**Comment by enzyme69** [comment]
@portnov Houdini Bounding Box selection is actually can be an idea. Maybe for future.
