### ISSUE TITLE
Arrow Key in Timeline no longer update Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1368]
I am not sure since when, but I am noticing a change in behaviour. I use to use Arrow Key to move back and forth to update Sverchok. This is no longer happening :/

Scrub still updates but... does not work on the Time MK2.

![timeline_issue](https://cloud.githubusercontent.com/assets/3952687/23940811/7145bcbc-09ba-11e7-977f-6ab9362664a9.gif)

The only relieable way is to playback.

**Comment by zeffii** [comment]
yep. No ETA on a fix.

**Comment by zeffii** [comment]
I don't think we are able to distinguish from a wanted ' click on a frame to jump to it, but don't trigger the update system twice'  vs ' use `arrow key and do update` .

**Comment by zeffii** [comment]
would it help if I added a `+1` / ` -1` frame button on the Frame node.

**Comment by zeffii** [comment]
(i wanted to do that anyway) 

not sure how much effort finding a solution to the kb route will be.

**Comment by zeffii** [comment]
we could even override the left right keys behaviour if the mouse is inside nodeview / sverchok.

**Comment by zeffii** [comment]
a recap:

- The Arrow keys are global for most views they will update the timeline, but views like the TextEditor have a different behaviour.
- Has nothing to do with the frame_in node `MK1` / `MK2`. this is the result of quashing the double update trigger during manual scrub.. `fix one thing , break another`.

solutions?  I don't want to mess with the update system for this feature so 

- dedicated `+1 / -1` button in Frame info
- kb command maybe  `shift < > `  if arrow keys can't be overridden.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23946389/81c0caa4-097a-11e7-80d8-524a3f621305.png)

**Comment by zeffii** [comment]
the `current frame` property, isn't attached to the Sverchok update system -- so a wrapper could be written for it...  but at the moment i'm not going to do that

**Comment by enzyme69** [comment]
Used to work though.. maybe Ly knows?

**Comment by zeffii** [comment]
i explained why.

**Comment by kalwalt** [comment]
@zeffii it will not works neither in others nodes, i'm trying to add a simple sequence mechanism to the `Texture viz` but after i realized this issue; maybe i can take a look at this, but not Eta promise...

**Comment by zeffii** [comment]
The arrow keys have never been associated with the NodeTree directly/ nor any Node.. (Selected or not) , doesn't matter if a slider is selected.  The array keys work globally, and trigger an update that is not nicely distinguishable from the unwanted second trigger of manual scrubbing.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1372

this fixes it.. but i'm reluctant to polute the handlers with code like that.. @ly29

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1374  maybe..

**Comment by zeffii** [comment]
i think this most recent pullrequest fixes, else it's easy enough to undo the change.
