### ISSUE TITLE
One must be on branch stuff...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1376]
I wanted to make a little tweak on this simple labeling bug.
![screen shot 2017-03-17 at 11 43 34](https://cloud.githubusercontent.com/assets/3952687/24024373/0334b23e-0b07-11e7-89d9-5e1c8df55619.png)

But I have no idea how to make branch and merging. Maybe will Google in a bit.

**Comment by zeffii** [comment]
Top left where it says Tree and the long sha , use the dropdown. Pick master, that will let you edit,... But instead of pushing direct, you can save changes as a patch. Probably ok for a one char edit.

**Comment by zeffii** [comment]
I was considering dropping mk2 from just the label. Soon we Will have too many mk2 it will seem noisy in menus

**Comment by enzyme69** [comment]
@zeffii Ok I make a branch, I think. And not sure about comitting etc. I have few fixes for typo error.

**Comment by zeffii** [comment]
@enzyme69 stick to keeping your fixes as patches, like this:

![image](https://cloud.githubusercontent.com/assets/619340/24035411/c138b76a-0af5-11e7-86c1-e85072677de4.png)

and then

![image](https://cloud.githubusercontent.com/assets/619340/24035450/f392725a-0af5-11e7-803c-8cf481ae19ef.png)

and definitely don't push / merge yet.

**Comment by zeffii** [comment]
meanwhile i've already corrected:
```python
    bl_label = 'Frame info'
```
so find something else :)

**Comment by enzyme69** [comment]
Ok thanks Master Zeffi!
