### ISSUE TITLE
Combining Object ID nodes into a single Asset Properties Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1379]
i'm not proposing to remove the existing Object ID nodes, but i do want to make a node that does the work of three of those nodes, for the simpler cases. 

This could be done in one node, with a simple UI (not so simple back end) 

![image](https://cloud.githubusercontent.com/assets/619340/24036815/9ec379e4-0afb-11e7-9d45-8e4071cb60b8.png)

- [x] texts
- [x] objects
    - [x] filter object display list, given selected object type
    - how far to go? :)
- [x] grease_pencil
   - GP name
      - layer (name)
           - frame (active? )
                - stroke
                        - points
                        - color

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24041376/648fba96-0b0d-11e7-85d6-53376ede3f13.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24041395/7f2bbb66-0b0d-11e7-9e14-ce1e2b049db0.png)

**Comment by zeffii** [comment]
maybe add filter already... +startswith, +endswith, 'contains string in text_name', matches regex

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24051124/61408068-0b31-11e7-9a1d-c80d5e51bc66.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24064461/df17a09c-0b64-11e7-8fe0-2561ac829ac3.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24071349/d5b1dc6e-0bcf-11e7-8114-f99f9d56d8b4.png)

**Comment by zeffii** [comment]
i've noticed there's a 1 frame lag, between the points output from the Asset Prop node and the correct frame data for the select GP_layer.

**Comment by zeffii** [comment]
ha...gp from nodes..
![image](https://cloud.githubusercontent.com/assets/619340/24075408/33a97af2-0c1b-11e7-93f6-48ab284d8cf0.png)

**Comment by enzyme69** [comment]
That is my wishlist Zeffii, GP via nodes. Not sure why anyone wants that :)
GP is evolving too into Objects... so this might change in the future! But
maybe we can draw colorful GP.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
gp is useful for making quick openGL renders for Blueprints
![image](https://cloud.githubusercontent.com/assets/619340/24079587/ac9ff8f8-0c8b-11e7-938a-a7a8c7acd444.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24079719/bb90216e-0c8e-11e7-87a5-38895c266528.png)

@Kosvor2   maybe we should add a convenience function to ExecNodeMod  
```python
def dunderless(data):
    return [i for i in dir(data) if not i.startswith('__')]
```

**Comment by zeffii** [comment]
or `ddir`  (dunderless_dir)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24080368/21ed0134-0c9e-11e7-961e-aaf77ed89362.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24080468/24ad1e5c-0ca0-11e7-9bc6-12b7f59c767f.png)

**Comment by zeffii** [comment]
am renaming Asset / Properties not to `Object ID Selector`.

**Comment by Kosvor2** [comment]
`object_nodes/closest_point_on_mesh2.py` bring it there too.

**Comment by zeffii** [comment]
OK!

**Comment by zeffii** [comment]
i've merged this. some time soon we should write the docs for this list of nodes, and create a directory called 'bpy_data` and move the nodes that now live in `objects` , to this more generic location.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24084721/ed3245ba-0cef-11e7-8f32-a47ced01fac7.png)

**Comment by enzyme69** [comment]
@zeffii that Grease Pencil node is a WIP, right? I'll keep eyes on it.

**Comment by enzyme69** [comment]
![gp_test](https://cloud.githubusercontent.com/assets/3952687/24086674/0772085c-0d68-11e7-96a1-f4135c153477.gif)

???

**Comment by enzyme69** [comment]
@zeffii Probably Bone access is also something I look forward to. Slowly2, I will try to dig it.

**Comment by zeffii** [comment]
Pushing a variable num point to a gp stroke is tricky, hence the dedicated node. No eta.
