### ISSUE TITLE
Noise and random tutorial

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1384]
I started to write a tutorial based on [the book of shaders](https://github.com/patriciogonzalezvivo/thebookofshaders) i don't know if it will become something useful and interesting, but anyway the idea is to start with the simplest nodes and creating the more complex algorithms. If you want take a look at go [here](https://github.com/kalwalt/sverchok_nodes_collection/tree/master/docs/tutorial_noise).  Feel free to express your opinion, and if you find some error (especially in the language)  unfortunately :cry:  my English is not so good. 
Moreover i have to learn a bit more of the Markdown syntax, i think the text should be formatted and presented with more spaces, and some parts need more emphasis.
The second part will be written in the next days, and will concern Noise, maybe i will add a third part focused on scripting own noise functions.
Will see the development...
Thank you all
Walter

**Comment by zeffii** [comment]
cool your English is fine btw

**Comment by kalwalt** [comment]
> cool your English is fine btw
Thanks @zeffii ! maybe later i will post something new.

**Comment by kalwalt** [comment]
A preview of the new chapter: Fbm (Fractal Brownian Motion from Musgrave) made with simpler nodes and `noise` node as noise basis function: 
[fbm](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/images/tutorial_noise_sverchok/noise_octaves_nodes.png)
[fbm_json](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/json/tutorial_noise/noise_w_octaves.json)

I will do also some example of fractals with different noise basis functions by script. deal with nodes it's a bit hard, instead creating a script this task became a lot easier.

This is also very useful:
[noise with freq and amp](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/images/tutorial_noise_sverchok/noise_freq_amp_nodes.png)
[noise with freq and amp json](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/json/tutorial_noise/noise_w_freq_and_amp.json)

**Comment by zeffii** [comment]
why not SNLite ? :(

**Comment by kalwalt** [comment]
>why not SNLite ? :(
yes, that was the idea for the scripts.

**Comment by nortikin** [comment]
it is always good to have tutorials. 
do you propose to embed it for sverchok docs?
Unit1,2,3...?
It is ok if that. I like narrative.

**Comment by kalwalt** [comment]
@nortikin mi first idea was to put somewhere in github, maybe in a web page, but if you think that this it might be interesting to be in the Sverchok documentation, i will happy to convert it . Could be also placed in the wiki as you prefer. 
When i start it, I have no idea how long should be but nowi think could be 4 units.

**Comment by nortikin** [comment]
@kalwalt 
Lets make to docs sphinx units
Later we will maybe separate lessons (sphinx also) with clear docs
Efforts you put on lessons dare to placed in docs.

**Comment by kalwalt** [comment]
> Lets make to docs sphinx units
Later we will maybe separate lessons (sphinx also) with clear docs
Efforts you put on lessons dare to placed in docs.

ok, @nortikin  i will work to finish it quickly or nearly, because at the end of this month i will go in France and i don't know how much time i will have.
Do you think we can put this tutorial after the @zeffii Sverchok introduction?

**Comment by nortikin** [comment]
ok if that.

**Comment by kalwalt** [comment]
`value noise` all by nodes!!

![value_noise](https://cloud.githubusercontent.com/assets/1275858/24832529/66fb8380-1cb2-11e7-92d1-c7e4ce9224e6.png)

**Comment by kalwalt** [comment]
gradient noise with a different random function (different from that used in the `value noise`)
![gradient_noise](https://cloud.githubusercontent.com/assets/1275858/24837330/553a798c-1d32-11e7-9320-3e00e93dd0af.png)

**Comment by zeffii** [comment]
add links to this in the wiki please :) I think it's open to edit for anyone

**Comment by kalwalt** [comment]
@zeffii hadn't time to do anything, but when i will have a bit of time sure i'll do it.
