### ISSUE TITLE
Polygon Boom and Center Polygon

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1385]
Sometimes I do wonder if Polygon Boom can simply maintain the Center of each Polygon, or maybe there is another way to do this "quickly separating each polygon face for further transform":

![screen shot 2017-03-19 at 18 22 25](https://cloud.githubusercontent.com/assets/3952687/24078996/2a99aeb2-0cd1-11e7-819a-92a21e283689.png)

**Comment by enzyme69** [comment]
![screen shot 2017-03-19 at 18 24 26](https://cloud.githubusercontent.com/assets/3952687/24079000/4d17ac50-0cd1-11e7-9dc1-b133752d34bf.png)

Hmm.. that's kind of does the job. 

Any explanation why Polygon Boom and Center Polygon gives an offset? @nortikin

**Comment by zeffii** [comment]
Polygon boom just separates all polygons, a polygon's center is determined by the average of all its vertices. Polygon boom could offer a 'recenter' option and output with that a new socket to represent the center location of each polygon (pre transform).

When two nodes are used frequently together, i'm inclined to think their functionality should be merged (in a way that doesn't make the node heavier)..

**Comment by zeffii** [comment]
For polygon boom we expect the polygons to be in the same position in 3d space before and after the operation. You introduce the offset by transforming them with a matrix.

**Comment by enzyme69** [comment]
Thanks for explanation @zeffii !

**Comment by jotero3d** [comment]
Polygon boom is the hammer, I completed yesterday only :)
https://goo.gl/photos/RaFdGM5tun3xZX2x8

**Comment by nortikin** [comment]
centers of polygons have to be before boom, to use original object. Than you use boom and correspond polygon to center matrix
