### ISSUE TITLE
Scale Node is a little slow

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1386]
![screen shot 2017-03-19 at 18 40 37](https://cloud.githubusercontent.com/assets/3952687/24079071/902f0c70-0cd3-11e7-83b9-976232eafdbb.png)
![screen shot 2017-03-19 at 18 40 21](https://cloud.githubusercontent.com/assets/3952687/24079072/90775a98-0cd3-11e7-91e4-308ef16051c3.png)

I have this setup, I think the Scale node is just slightly slow.

https://gist.github.com/adccbdcbe205df6819a4ac6aa71d275c

Processed  Frame info in: 0.0001
Processed  List Repeater in: 0.0002
Processed  Random Num Gen in: 0.0004
Processed  List Repeater.001 in: 0.0123
Processed  Math in: 0.1226
Processed  Polygon Boom in: 0.0010
Warning: Centers polygons 3 setting unconncted socket: Centers
Warning: Centers polygons 3 setting unconncted socket: Norm_abs
Warning: Centers polygons 3 setting unconncted socket: Normals
Processed  Centers polygons 3 in: 0.0040
Processed  Map Range in: 0.0700
Processed  Scale in: 1.7199
Processed  Viewer Draw in: 0.0474
Node set updated in: 1.9801 seconds

Maybe not urgent, but I wonder if this can be optimized.

**Comment by Kosvor2** [comment]
Change node source code to this:

```
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
import numpy as np
from bpy.props import FloatProperty, BoolProperty
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode, match_long_repeat


class SvScaleNode(bpy.types.Node, SverchCustomTreeNode):
    ''' Scale '''
    bl_idname = 'SvScaleNode'
    bl_label = 'Scale'
    bl_icon = 'MAN_SCALE'

    factor = FloatProperty(name='Factor', description='scaling factor',
                           default=1.0, options={'ANIMATABLE'}, update=updateNode)

    def sv_init(self, context):
        self.inputs.new('VerticesSocket', "Vertices", "Vertices")
        self.inputs.new('VerticesSocket', "Center", "Center").use_prop = True
        self.inputs.new('StringsSocket', "Factor", "Factor").prop_name = "factor"
        self.outputs.new('VerticesSocket', "Vertices", "Vertices")

    def process(self):
        if self.outputs[0].is_linked:
            Ve, Ce, Fa = self.inputs
            V = Ve.sv_get()
            C = Ce.sv_get()
            F = Fa.sv_get()
            ar1, ar2, ar3 = match_long_repeat([V, C, F])
            nparr = (np.array(ar1) + np.array(ar2)) * np.array(ar3)
            self.outputs[0].sv_set(nparr.tolist())


def register():
    bpy.utils.register_class(SvScaleNode)


def unregister():
    bpy.utils.unregister_class(SvScaleNode)

```

Then start blender, create new scale node in nodetree, and tell if it works much faster, please.

**Comment by enzyme69** [comment]
I tried and somewhat the node tree failed to work anymore. Maybe I have wrong setup. I'll investigate.

**Comment by enzyme69** [comment]
![screen shot 2017-03-19 at 20 31 04](https://cloud.githubusercontent.com/assets/3952687/24079728/ff98477a-0ce2-11e7-813e-c33827c39ce1.png)

Maybe something missing in term of vectorization.

**Comment by enzyme69** [comment]
```
  File "/Users/jimmygunawan/bsscript/addons/sverchok/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/Users/jimmygunawan/bsscript/addons/sverchok/nodes/transforms/scale.py", line 48, in process
    nparr = (np.array(ar1) + np.array(ar2)) * np.array(ar3)
Node Scale had exception operands could not be broadcast together with shapes (16,4,3) (16,1) 
```

**Comment by enzyme69** [comment]
I switched to the original and do notice something... maybe I need to fix this extra data.

![screen shot 2017-03-19 at 20 33 51](https://cloud.githubusercontent.com/assets/3952687/24079748/66efcc04-0ce3-11e7-9d85-1f94cd6eaa87.png)

**Comment by enzyme69** [comment]
I produced extra data that might have slowed down the Scale thing considerably. I was using Total Vertices instead of Total Center or Total Polygon Face.

Now performing better:

Processed  Centers polygons 3 in: 0.0024
Processed  Math in: 0.0044
Processed  Map Range in: 0.0023
Processed  Scale in: 0.0471
Processed  Viewer Draw in: 0.0015
Node set updated in: 0.0611 seconds

https://gist.github.com/f0c7c7e481f51b084c271d4e60433df2

Still curious if Kosvor source update can improve this.

**Comment by zeffii** [comment]
i'm pretty sure you want to match the counts of Factors with the Vectors and Center counts.
https://gist.github.com/4d248075acebee9f2138379b00b18c65

![image](https://cloud.githubusercontent.com/assets/619340/24079791/ec0a7266-0c90-11e7-97c5-af0099e5bbe3.png)

else you are creating (242-42= 200) duplicates of the last one ..which you don't see.

**Comment by enzyme69** [comment]
@Kosvor2 Your code might have something that makes below GIST does not work.
https://gist.github.com/6debce54f7dc9428ef44db0a5f57f462

Perhaps it increases the speed, I don't know it yet. But I think the original is working kind of ok around 7-8 fps and interactive. Previously I did make mistake.

**Comment by enzyme69** [comment]
@zeffii Yes, that's I just realized. If this is not a case of "Slow" we can close it. Unless @Kosvor2 code can improve the speed with numpy.

**Comment by Kosvor2** [comment]
Here second atempt:

```
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
import numpy as np
from bpy.props import FloatProperty, BoolProperty
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode, match_long_repeat


class SvScaleNode(bpy.types.Node, SverchCustomTreeNode):
    ''' Scale '''
    bl_idname = 'SvScaleNode'
    bl_label = 'Scale'
    bl_icon = 'MAN_SCALE'

    factor = FloatProperty(name='Factor', description='scaling factor',
                           default=1.0, options={'ANIMATABLE'}, update=updateNode)

    def sv_init(self, context):
        self.inputs.new('VerticesSocket', "Vertices", "Vertices")
        self.inputs.new('VerticesSocket', "Center", "Center").use_prop = True
        self.inputs.new('StringsSocket', "Factor", "Factor").prop_name = "factor"
        self.outputs.new('VerticesSocket', "Vertices", "Vertices")

    def process(self):
        if self.outputs[0].is_linked:
            Ve, Ce, Fa = self.inputs
            V = Ve.sv_get()
            C = Ce.sv_get()
            F = Fa.sv_get()[0]
            out = []
            ar1, ar2, ar3 = match_long_repeat([V, C, F])
            for i, i2, i3 in zip(ar1, ar2, ar3):
                i, i2 = match_long_repeat([i, i2])
                out.append(np.multiply(np.array(i) + np.array(i2), i3).tolist())
            self.outputs[0].sv_set(out)


def register():
    bpy.utils.register_class(SvScaleNode)


def unregister():
    bpy.utils.unregister_class(SvScaleNode)

```

**Comment by zeffii** [comment]
would be nicer of hexnode allowed something like this
![image](https://cloud.githubusercontent.com/assets/619340/24079859/b7bc1eae-0c92-11e7-8da6-af835078f538.png)

**Comment by enzyme69** [comment]
@Kosvor2 Faster but behaviour changes :D 

![scale_001](https://cloud.githubusercontent.com/assets/3952687/24079883/0de35a6e-0ce7-11e7-903f-e8930d3fa236.gif)

This thing involves List Slice and sometimes feels a bit complex.

**Comment by enzyme69** [comment]
And slight tweak, I got this... the Scaling using Center of Poly thing is ignored?

![scale_002](https://cloud.githubusercontent.com/assets/3952687/24079904/8671882a-0ce7-11e7-8fa1-5bd9452887f1.gif)

https://gist.github.com/22eb656e30dd52b8a4b3793c5a63554c

**Comment by Kosvor2** [comment]
Yes.

**Comment by enzyme69** [comment]
@Kosvor2 Maybe just a bit more tweak and we get a faster Scaling.

**Comment by enzyme69** [comment]
I will roll back to previous and maybe one day we numpy this. Thanks!
