### ISSUE TITLE
Sensor Logging iPhone Data CSV Rotation Out

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1388]
Supposed I have a sensor logging of iPhone Yaw, Roll, and Pitch. And I wanted to input the CSV data and output it into the Matrix of Empty like below:

![screen shot 2017-03-19 at 23 04 35](https://cloud.githubusercontent.com/assets/3952687/24080690/9a793438-0cf8-11e7-9bd2-be5344cdc236.png)

Is there a missing conversion in Sverchok for Rotation?

**Comment by enzyme69** [comment]
Ok firstly I realized I need to do this:
value * 180/pi

**Comment by enzyme69** [comment]
How to plug Euler XYZ Rotation to Matrix to get the rotation out to Empy?

**Comment by enzyme69** [comment]
![screen shot 2017-03-19 at 23 20 26](https://cloud.githubusercontent.com/assets/3952687/24080829/a8175ed8-0cfa-11e7-8255-9fc1a7a92db5.png)

Ok found it.

**Comment by zeffii** [comment]
i think you should start waiting 30 minutes before posting issues here. that would stop maybe half of your posts :)
