### ISSUE TITLE
Chamfer Operations on Vertices

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1391]
Maybe more like a request, but wondering if _Chamfer_ operation on vertices is something that we can have in Sverchok at some point? Blender do not have Chamfer operation, I don't think. But there should be add-on somewhere that is already doing it? I will check.

Some people keeps mentioning Bevel Center or Bevel operation related to this Chamfer.

**Comment by enzyme69** [comment]
![screen shot 2017-03-20 at 11 39 03](https://cloud.githubusercontent.com/assets/3952687/24086332/d8dfc5de-0d61-11e7-90e7-5852a86e4d9c.png)
![screen shot 2017-03-20 at 11 38 03](https://cloud.githubusercontent.com/assets/3952687/24086333/d91d1b14-0d61-11e7-83c6-f22bc1799c73.png)

Something like above, but not sure if 3dsmax or Maya does the same thing.

**Comment by enzyme69** [comment]
If we have Rip operation:
https://github.com/nortikin/sverchok/issues/1392

We can probably do Chamfer easier. Sort of. Depends...

![chamfer](https://cloud.githubusercontent.com/assets/3952687/24086414/151243dc-0d63-11e7-9e8e-00bf07cd7a87.gif)

**Comment by enzyme69** [comment]
![screen shot 2017-03-20 at 11 58 46](https://cloud.githubusercontent.com/assets/3952687/24086504/963c1112-0d64-11e7-9e08-f5c2d9606d18.png)

**Comment by zeffii** [comment]
not sure why the bevel node doesn't have a Vertex mask.. like it has the Edge mask..

**Comment by zeffii** [comment]
>  Blender do not have Chamfer operation, I don't think

in edit mode. subdivide a plane, select a vertex, press ctrl+shift+B.

![image](https://cloud.githubusercontent.com/assets/619340/24095203/41cb56fe-0d5c-11e7-9fde-7cd97b8c1ef1.png)

**Comment by enzyme69** [comment]
@zeffii That's exactly it! Very hidden function. I have to write this down on my blog.

Any possibilities for this scenario from inside Sverchok --- out to Blender Edit, do procedure --- back to Sverchok.

Actually above sentence sounds really silly, maybe Script node can do this, if List Mask is properly done of course.

Anyhow, maybe I can close this. Thanks!

**Comment by enzyme69** [comment]
Subsurf, decimate iteration and Chamfer can make strawberry as demonstrated manually...

![screen shot 2017-04-07 at 12 56 34](https://cloud.githubusercontent.com/assets/3952687/24783764/aa094fee-1b91-11e7-87c1-651fd700b8a7.png)

http://imgur.com/vFklKfz

**Comment by enzyme69** [comment]
@nortikin Any way we can do this in Sverchok? That change of topology and also chamfer?

**Comment by nortikin** [comment]
[strawberry_2017_04_07_16_13.zip](https://github.com/nortikin/sverchok/files/906304/strawberry_2017_04_07_16_13.zip)
useless i guess
![strawberry](https://cloud.githubusercontent.com/assets/5783432/24811547/2422be0e-1bcf-11e7-91ee-055c972b28ac.png)

**Comment by nortikin** [comment]
should be other way for spiral screw, than sorting grouping lists of four ertices (with topology respect)

**Comment by zeffii** [comment]
https://gist.github.com/484f66b042c852bd280a0ccfbcfa491b

![image](https://cloud.githubusercontent.com/assets/619340/24812075/f9e61218-1bc8-11e7-8981-65de4230c585.png)

**Comment by nortikin** [comment]
[strawberry1_2017_04_07_16_33.zip](https://github.com/nortikin/sverchok/files/906350/strawberry1_2017_04_07_16_33.zip)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24812339/f4cd02cc-1bc9-11e7-9d61-039091c0495e.png)

**Comment by zeffii** [comment]
it would be neat to get `bmesh.ops.smooth_laplacian_vert` smoothing as node...

**Comment by nortikin** [comment]
[bevel-strawberry_2017_04_07_16_47.zip](https://github.com/nortikin/sverchok/files/906393/bevel-strawberry_2017_04_07_16_47.zip)
something wrong with overlap polygons or i miss ?

**Comment by nortikin** [comment]
i need old polygons, maybe to correct extrude region?..

**Comment by nortikin** [comment]
some
[bevel-strawberry1_2017_04_07_16_50.zip](https://github.com/nortikin/sverchok/files/906404/bevel-strawberry1_2017_04_07_16_50.zip)

![bevel-strawberry1](https://cloud.githubusercontent.com/assets/5783432/24812858/74f311e4-1bd4-11e7-8043-c89adc724033.png)

**Comment by zeffii** [comment]
listmodifier should (but curren't does not ) be able to generate a list mask from `Polgyons subset new polygons`

**Comment by zeffii** [comment]
```python
"""
in total_pols s
in new_pols s
out out_mask s
"""

for idx, pol_list in enumerate(total_pols):
    submask = []
    for pol in pol_list:
        submask.append(pol in new_pols[idx])
    out_mask.append(submask)
```

**Comment by zeffii** [comment]
converting to sets for the test would be even faster :)  and proper set theory..

**Comment by zeffii** [comment]
https://gist.github.com/133ba3e7afe48b1b4f2475bd4c254e15

add a subsurf to the output of bmesh :)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24814093/a87d5ece-1bd0-11e7-97d3-5033db20c2de.png)

**Comment by nortikin** [comment]
![bevel-strawberry2](https://cloud.githubusercontent.com/assets/5783432/24814083/0353108e-1bd9-11e7-9ab8-18110aebba58.png)
I think, that scale have to be easier.
My proposition for sublevels operations is too tricky. But maybe someone have opinion, hw to make easy but not plain.
[bevel-strawberry2_2017_04_07_17_23.zip](https://github.com/nortikin/sverchok/files/906473/bevel-strawberry2_2017_04_07_17_23.zip)

**Comment by nortikin** [comment]
vector interpolation have to be replaced with move node. but i thought it was vectorized... something strange

**Comment by zeffii** [comment]
i think most of all our start shape is not nicely subdivided :)

**Comment by enzyme69** [comment]
I think this is fascinating procedural topology that needs to be explored...
