### ISSUE TITLE
Disable/Deactivate input/output sockets

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1393]
Is there a way to deactivate/disable (gray out) the input/output sockets? Would that be a good feature to have ? I’m thinking of the situations when certain parameters in the node may render some of the other inputs/parameters inactive/not needed (e.g. an example is the PlaneMK2 when normalized is on the step sizes values in the node itself does not affect the output. You can certainly hide/show them instead of enable/disable them, but hiding will disrupt the input connections.

**Comment by zeffii** [comment]
I posed a similar question not too long ago, made a branch to allow socket.greyed_out . I think this is a continuation of the weak .hide situation.

The counter argument to all this hiding/disabling is that the node is maybe doing too much. That's a matter of perspective of course.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1182#issuecomment-275648397

**Comment by zeffii** [comment]
a few take aways from a collection of threads pertinent to this problem.

- currently  `.hide` is not a great solution  
    - *pro*: intuitively it makes sense
    - *con*: practically, it's a nightmare for several reasons (why?)
- would a grey out / disable "inactive" option be ok? 
    - *pro*: intuitively it makes sense
    - *con*: practically, it's a nightmare for several reasons (why?)
- if you're going to have socket appearing and disappearing, it's simpler to have them at the bottom of the node.
    - *pro*:  It solves all confusion when done right
    - *con*:  doing it right can be a headwreck

**Comment by zeffii** [comment]
@DolphinDream  feel free to flesh out that list.

I fully agree that it could be simpler to modify the sockets of a node, just as it's simple to `.replace_socket`.

**Comment by zeffii** [comment]
well..  `hide_safe` is now implemented (it automatically cuts links for sockets that you want to hide)

a word of caution, hidden sockets are not confirmed to be 'working' in monads. somebody familiar with Monads will need to take the time to test the logical scenarios. It might work.. i don't know (error on the side of caution for now).

we can reopen this if there's active discussions
