### ISSUE TITLE
Viewer BMesh Halted Operation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1395]
Probably not urgent, but I noticed something that can be improved.

I am using Viewer BMesh to output below setup:
https://gist.github.com/4901313e3abcc7749b2b4120877488e9

At some point Viewer Bmesh got halted  because of error, maybe data incorrect, when Plane Selection does not have any data when it goes beyond the bound.

Using Viewer Draw, the halted operation seems to be more elegant.

Any thought?

**Comment by enzyme69** [comment]
![halted_operation_001](https://cloud.githubusercontent.com/assets/3952687/24126627/1b074862-0e23-11e7-9e5f-6d1b72de052d.gif)

**Comment by zeffii** [comment]
@enzyme69 not "maybe" data incorrect, definitely.

**Comment by zeffii** [comment]
red node means there was an exception, there should be some kind of error message in the terminal/console.

Disable the UPD, then stick the links that currently go into the bm viewer, into a DebugPrint. You should see  what you are feeding it.

In my opinion the 'going red' is the correct behaviour, it hints to you that you don't know what you are passing into it.

**Comment by zeffii** [comment]
if we always tested each index item in a polygon/edge list for "does that vertex exist", you'd get a noticably slower node. Now it assumes you are passing the correct data, because most of the time you will be.

**Comment by zeffii** [comment]
maybe the exception could be give a better message...
```
Node Viewer BMeshMK2 had exception object of type 'int' has no len()
or
Node Viewer BMeshMK2 had exception 'int' object is not iterable
```

The issue that concerns me here is that ViewerDrawMK2 doesn't turn Red. pick your battles.
