### ISSUE TITLE
SV Typography Align Vertical and Horizontal 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1397]
![screen shot 2017-03-21 at 12 58 36](https://cloud.githubusercontent.com/assets/3952687/24129347/33e38d60-0e36-11e7-9be6-eb1e07568968.png)

Very likely the align vertical or horizontal is not showing properly on the node?

**Comment by zeffii** [comment]
Font object had several improvements since the node was made. I haven't kept up to date.

**Comment by zeffii** [comment]
it's tempting to add the object output here.. and do a general MK1. with other minor usability changes (but possibly heavy internal changes..)

**Comment by zeffii** [comment]
allowing object output would let you use `Object ID set` to _all other properties_.

**Comment by zeffii** [comment]
closing this till I find time.
