### ISSUE TITLE
Object ID Selector but need Object ID GET

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1404]
![screen shot 2017-03-22 at 12 49 14](https://cloud.githubusercontent.com/assets/3952687/24178575/0dc40c2c-0efe-11e7-9807-345362caf8a3.png)

I just realized with Object ID Selector, we can only select 1 object at a time... but Object ID GET used to be able to just "get all objects" and filter it out.

@Kosvor2  @zeffii Any idea on this?

**Comment by enzyme69** [comment]
One wants to perhaps do these below:
- select all curves or bunch of curves, then change the "Use UV for Mapping"
- select bunch of objects, access its modifier and change property

Maybe Object ID Selector can have option that simply get All and then we use Object ID Filter.

**Comment by enzyme69** [comment]
Or have Object ID GET as separate node?

**Comment by zeffii** [comment]
Leave the object name blank.
