### ISSUE TITLE
Brainstorming about Revamping the Preferences 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1405]
The SV preferences seems to need a little TLC 😁  sooo I gave it some attention :) oops.

This was actually prompted by me trying to find a place where to put the icon manager settings (@nortikin suggested this should be the place to put it). So, instead of just adding one more setting to a pile of other settings I decided to restructure the preferences into tabs. I placed all the theme related UI into a Theme tab, and the rest I placed for now into a General and Developer tabs. If anyone feels they need a distraction here’s a great chance to brainstorm about revamping the preferences 😀 : relocating current settings to proper tab, adding other sections/tabs, adding other possible settings etc. the sky is the limit.

Some things that I thought it would be nice to add to the preferences are:
- default sizes (for vertex size, edge width etc) in the viewer draw node
- default colors for the viewer Index backgrounds :) 
- default show previews (e.g. in the easing node kind of preview)
- option to allow saving custom theme presets 

![sv-preferences-demo2](https://cloud.githubusercontent.com/assets/2083719/24179586/5e602102-0e86-11e7-96d1-c548d1b2285e.gif)

**Comment by zeffii** [comment]
i don't oppose this, but 

- "themes" should not be the first/default enum
- event handler (frame change) and developer can be in one tab, and show it by default.
- not enough typos.

**Comment by DolphinDream** [comment]
Yeah, I didn’t know what the “frame change” setting was for. I’ll put it in the developer tab.
If the Themes tab should not be first which tab should go first ? General ? Developer ?

What do you mean by “not enough typos” ? :)

What is the “Heat map” used for ? 

I see a “    #  bgl viewer settings” comment in the settings.py code but it’s not used. Were BGL related settings going to be added to the preferences/settings ? there is a custom_font_id that is defined but not used.

**Comment by zeffii** [comment]
_`custom_font_id`_ 
was added for letting users pick a font for the stethoscope, but implementing it is a little unwieldy - so it can be removed safely.

_`heatmap`_
colours nodes depending on their processing weight. (how much time an update takes per node)
https://github.com/nortikin/sverchok/issues/235

Right now I just see potential for two tabs, General and Theme. 
![image](https://cloud.githubusercontent.com/assets/619340/24198465/5109bc54-0f06-11e7-90e9-9a02f5f6d3e6.png)

**Comment by DolphinDream** [comment]
True, not enough settings for now to put in more sections, however I would advocate for a separate Developer tab regardless. I see this area of the add-on preferences as something that typical users would use to configure their SV experience, however the typical user may not care, nor should they, about settings that only the developers or perhaps the more advanced user may care (like the timing, icon manager stuff etc). If we put developer related settings in its own tab we can keep the normal user related settings in the other tabs - a place dedicated for them alone. 

And about the heat map.. If you put the heat map enabling setting in one tab, the hot/cold colors should probably be put in the same tab, since the heat map enabling will enable/disable (gray out) the hot/cold colors. But if you put the heat map settings in a different tab than the Theme tab, you split apart the color settings, which would be a good argument against moving the heat map out of the theme tab.

**Comment by zeffii** [comment]
Primarily we make Sverchok for us, so I want the options that we are likely to use to be visible first.

I'm tempted to pull `Enable Live Object-In` , `Print update timings`, and  `Heat map` toggles into the nodeview panel. I rarely use these, but I find going to the prefs to toggle them a little cumbersome. Even more rare is the need to edit the colours or icons. I'm not indifferent, and do think the toggle for heatmap can be separated from the choice of the heatmap colours.

But.. i should mention that I use [a little console add-on](https://github.com/zeffii/BlenderConsolePrompt) that can switch themes by just typing `bright` or `sv blossom` and hitting ctrl Enter.

**Comment by DolphinDream** [comment]
Oh... I thought we are aiming for a greater good here, to make these tools friendly enough for new users. My bad. :) In that case I guess keeping the preference in a “hacky” state should be fine.

**Comment by zeffii** [comment]
I don't see how that was the take-away from what I said.

**Comment by DolphinDream** [comment]
Apparently I misunderstood you. Sorry. What I got from what you were saying is that is more important to make this preferences more useful for “us” - the developers and have the settings that are used more often by the developers show up first. Is that what you were suggesting? Your last statement that you can modify things in the terminal without relying on the preference settings indicated to me that those preference settings are not all that much needed. Sorry if I misunderstood your point. My overall understanding was that eventually SV add-on would be adopted by a larger group and having a well designed, robust and polished set of nodes, preferences etc is a desirable thing that we as developers should aim to, which is why i suggested a revamp of the preference area to begin with (make it easy for developers but also attractive/polished for the new users).

**Comment by zeffii** [comment]
I will draw attention once again to my very first response, i am not opposed to a good user preference area.. just my requirements contrast your suggestion. I fail to see the need for a developers tab,  anything we as devs should need shouldn't really be accessible from a menu only tucked away there.. The items listed in General below are not features that only developer will use (contrary to what you seem to be saying).

```
General

- Frame change handler [Pre | Post | None]
- print update timings
- show heatmap
- enable live obj-in

Theme

- show icons in ctrl+space
- big buttons
- Theme preset [ choices ]
- - auto apply theme settings
- - apply theme when opening file
- - apply theme layouts
- Error Colors
- Heatmap Colors
- icon manager

Node defaults 

- enum list of nodes that have defaults
- defaults listed

```

**Comment by DolphinDream** [comment]
Perfect. Btw, what is the “Node Defaults” ? Is this a suggested new tab?

**Comment by zeffii** [comment]
sure. i don't want Node defaults to be part of a color theme .. at least.. not yet.

**Comment by zeffii** [comment]
(there might be node defaults in one theme that you like.. but you like defaults of other nodes from another theme... it poses a problem. separation doesn't)

**Comment by DolphinDream** [comment]
What exactly are these “node defaults” ? Are these to include things like “Show or not the node preview by default” ?

**Comment by zeffii** [comment]
that could be an option yeah, it was you who mentioned it. I am indifferent, the current default works for me.

other things like 
- vdmk2_default_vertex_size
- vdmk2_default_edge_width
- vdmk2_default_vertex_color
- vdmk2_default_edge_color
- vdmk2_default_face_color
- vdmk2_default_shaded
- vdmk2_default_transparency
- vdmk2_default_ngon
- index_view_default_vertex_text_color
- index_view_default_vertex_text_bgcolor
- index_view_default_edge_text_color
- index_view_default_edge_text_bgcolor
- index_view_default_face_text_color
- index_view_default_face_text_bgcolor
- bmview2_default_shade_smooth

etc...

**Comment by zeffii** [comment]
( but don't go ahead and make a massive PR that tries to do all of that last part at once... )

**Comment by DolphinDream** [comment]
Yeah, I did suggest that particular default, but only as an illustration as to what kind of defaults can go in the prefs, not because it really mattered to me. :) As a matter of fact, like you said, most of the defaults as they are now work for me just fine.

**Comment by zeffii** [comment]
> My overall understanding was that eventually SV add-on would be adopted by a larger group and having a well designed, robust and polished set of nodes,

I think the primary mission is 'continuously respond to new requirements, and fix encountered bugs'. Its large scale adaptation is not a goal, it would possibly even be overwhelming to handle the bug reports. It's OK to work on underappreciated tools :) i kind of like the exclusivity. It's an Alpha tool (and that doesn't necessarily mean alpha quality)

kind of like the difference between Max/MSP / Puredata . Puredata is butt-ugly but is amazing in the right hands. Whereas Max/MSP has a much more attractive UI and UX experience.

I hope you can understand my resistance to adding features "just because we can"..

**Comment by DolphinDream** [comment]
Points noted.

**Comment by DolphinDream** [comment]
Ok.. I need a hint. I added this “Enable Center” setting to the defaults in the Settings, since I almost always want my line and plane to be centered.. so I figured this could be a good candidate for a default setting. How do I then use this default value now in the plane MK2 for instance? I imagine that once i define the center property in plane MK2 I would have to initialize it with the default value from the preferences. If so, how do I read this value ?

**Comment by DolphinDream** [comment]
After digging some more.. i figured that this is a class property so I don’t know how the class property can be changed once the classes were registered. Perhaps they need to be re-registered once the setting changes in the preferences? Or perhaps whoever is in charge of creating new nodes could override that property for a node with whatever is defined in the preferences ?

**Comment by DolphinDream** [comment]
OK.. not sure if this is the way to do it but this is the solution i figured out:

```python
    from sverchok import data_structure

    def get_default_center(self):
        addon_name = data_structure.SVERCHOK_NAME
        addon = bpy.context.user_preferences.addons.get(addon_name)
        if addon and hasattr(addon, "preferences"):
            prefs = addon.preferences
            return prefs.enable_center

        return False

    def sv_init(self, context):
        self.center = self.get_default_center()
```

**Comment by zeffii** [comment]
Use utils.context_managers sv prefs to get a reference to prefs ,  if it doesn't work straight from the class body, maybe do it from sv_unit.

**Comment by zeffii** [comment]
I  think the following shhould possible.

       Some_prop = StrProp(default=prefs['name'])

**Comment by zeffii** [comment]
Tho perhaps prefs needs a dedicated function for returning a copy of the current default, and not the ref directly.

**Comment by zeffii** [comment]
maybe we can change the order in which we load `settings` and the nodes (haven't looked at the consequences of that yet).. else for now this will have to suffice. 

even tho it looks a bit weird.. i'm OK with it because it shows us immediately which properties are relegated to a preference default. This might not be immediately noticable if done in the class body.

```python
    stroke_color = bpy.props.FloatVectorProperty(
        update=updateNode, name='Stroke', default=(.3, .3, .2, 1.0),
        size=4, min=0.0, max=1.0, subtype='COLOR'
    )

    fill_color = bpy.props.FloatVectorProperty(
        update=updateNode, name='Fill', default=(.1, .3, .6, 1.0),
        size=4, min=0.0, max=1.0, subtype='COLOR'
    )

    def sv_init(self, context):
        ...

        with sv_preferences() as prefs:
            self.stroke_color = prefs.gpv_stroke_color
            self.fill_color = prefs.gpv_fill_color

```

**Comment by zeffii** [comment]
alternatively, and this gets my preference.. make a `../datafiles/sverchok/defaults/node_defaults.json`. To read and write from. But I see the implementation of these defaults as a distinctly separate issue from the subject of the thread.

**Comment by DolphinDream** [comment]
So you would say the settings would write to the default.json file and the nodes will read from it ?

**Comment by DolphinDream** [comment]
Btw, where do the settings values get saved ? Are they saved automatically by blender given that the addon-prefs is derived form the AddonPreferences, thus all the derived class props get saved to some saved settings file ?

**Comment by DolphinDream** [comment]
I like your prefs['someName'] idea (which i assume is a custom function to return the value of the property someName form the addon preferences? .. i.e. bpy.context.user_preferences.addon.preferences.someName)?

Btw, if you add the default value to node class property defined, my understanding is (and that may be incorrect) that since the node classes are already registered with some default values already, changing the default values later in the preferences will not affect the defaults already registered with the node class. Do you know what i mean? Or does the new node being instantiated get to have its properties defined in the class initialized dynamically with whatever default values it can get form the addon preferences ?

**Comment by zeffii** [comment]
> So you would say the settings would write to the default.json file and the nodes will read from it 

my understanding is the AddonPreferences get stored much like blender's own theme preferences ( perhaps startup.blend or default.blend .. exactly where isn't really relevant -- we can take for granted that it will store settings)

I would like to do this with as little hard coding as possible, possibly auto growing from the Node tab in NodeView. It could 

- enumerate all currently changed props (name, value) and have a 'use current settings as default for this node' button. 
- Then it would write that to the `datafiles/ ..../___.json` , 
- future instances of that node would do a lookup prior to hitting `sv_init`, 
- freeze the layout (avoid updates associated with setting a property)
- change the value to the stored default value, 
- then run sv_init. and proceed to load the node.

User preferences tab would allow you to import / export a node_defaults.json , but you'd never have to interact with it.. or go to preferences to tweak stuff..

**Comment by zeffii** [comment]
regarding the random value, I struggle to find a reason to include that as a feature on the first pass, but you could certainly make an operator that spawns desired nodes with certain properties randomized within the range of the their min/max, and later include that as a tickbox `'randomize'  (description='randomize within range min/max)` . These things can be solved separately.

**Comment by DolphinDream** [comment]
oh boy.. that was JUST an example.. not a feature to add, so that i understand how default initialization works in the context of  class registration, instantiation :)

**Comment by zeffii** [comment]
- blender creates the node from the current hardcoded defaults, 
- then _before _it hits sv_init, the props would be injected, 
- then it enters sv_init .

This way we don't have to edit any nodes specially, just the node baseclass. Anyone could customize any default value without editing a single line of code.

**Comment by zeffii** [comment]
i might just code it tonight :)

**Comment by DolphinDream** [comment]
Alternatively.. i was thinking .. we could have each node have a "default settings" section in the property panel which can be used to alert the default values for that node instead of shoving all into the preferences. Also this section could include an option to "Save current settings for the node as default for future instances of the same node" type of functionality. Such defaults may need to be saved to some json file of sort (perhaps own by Sverchok).

**Comment by zeffii** [comment]
```
nodes['Range Int'].values()
```
will return []  if no sliders have been modified.. or 
```
for name, value in nodes['Range Int'].items():
     print(name, value)
```
Will print the name and value of any parameter that was modified away from default. This provides  sufficient information to dynamically generate a simple ui to allow users to define their own alternative defaults. I like abstracting it away from the node's own code, because it's just not convenient to edit each node' s class to add those options. Not convenient for us as developers, and not for users who need to convince one of us to add a default lookup for them... 

I fear it will only make sense if I implement it (tho maybe not tonight).

**Comment by zeffii** [comment]
> Alternatively.. 

but @DolphinDream  that's almost exactly what i mean.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24314128/5a083e26-10e0-11e7-8869-6e1d31730426.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24314445/ef643582-10e1-11e7-8cbd-17d007eda83e.png)

**Comment by zeffii** [comment]
by default the box would be folded up
at the bottom of the box a button would be added 'save as defaults'.

**Comment by DolphinDream** [comment]
Sweet. Now all is left is to inject the values into the props 👍🏼 and save and load them from file ?

**Comment by zeffii** [comment]
Yeah going with least viable until all parts are confirmed working, then go back and tweak

**Comment by DolphinDream** [comment]
The exception/nodata/heatmap colors are currently not part of the theme. Should they ?

**Comment by zeffii** [comment]
i don't see why not.. but for `nipon_blossom` those should be the same as the default.  nipon_blossom is my theme :)

**Comment by zeffii** [comment]
i went ahead and did some simpler upgrades instead. I much prefer not getting too complicated / elaborate with these things. I'll continue on the node defaults soon.

**Comment by DolphinDream** [comment]
Should I gather that my work on [PR 1413] (https://github.com/nortikin/sverchok/pull/1413) is no longer needed ? I’ve done some more work on it since last commit.

**Comment by zeffii** [comment]
Keep it around,  it may be worth cherry picking from later.
