### ISSUE TITLE
Testing Kosvor Particles MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1406]
This is pretty sweet so we have direct control over Velocity, I might have to see what we can do with that.

Below, I am trying to control 10 particles using Sverchok. The 10 Particles position can be used also to control 10 objects that are emitting particles.

![screen shot 2017-03-22 at 22 58 23](https://cloud.githubusercontent.com/assets/3952687/24196768/22bf2d32-0f53-11e7-8460-59cb80dc0e77.png)

So far the missing link:
- Need to be able to create Particles System directly from Sverchok
- Maybe ability to deep copy Instance Objects with Particle System attached to it (kind of like Animation Nodes Obect Instancing)

**Comment by enzyme69** [comment]
[particles_MK2_003_2017_03_22_12_02.zip](https://github.com/nortikin/sverchok/files/861287/particles_MK2_003_2017_03_22_12_02.zip)

Get JSON error actually:
![screen shot 2017-03-22 at 23 02 44](https://cloud.githubusercontent.com/assets/3952687/24196921/b32bea68-0f53-11e7-82db-c67339ffc8fb.png)

**Comment by zeffii** [comment]
When a node stores references to an object(or nodetree..), then `json` IO will fail. It can't be fixed in the IOjson code, so it needs to be fixed (if it's possible to fix it) in the Node's own code.

**Comment by enzyme69** [comment]
@zeffii Ok, I will wait for the fix.

The next thing I noticed with Particles MK2 is the behaviour it can change the Size of Particles, which will affect the Instance. But sometimes if pops. Maybe if we can somewhat mixing the original Size and Velocity and add Sverchok influence on top of it. Maybe @Kosvor2  can give some pointer?

![particle_radius_001](https://cloud.githubusercontent.com/assets/3952687/24235504/b25ead98-0ff1-11e7-866f-10479f09d839.gif)

**Comment by Kosvor2** [comment]
you can forcing particles to form any shape like that:

![parti_p2](https://cloud.githubusercontent.com/assets/22656834/24237232/43d41a22-0fc7-11e7-9d1d-0ed8a9c77cf0.png)

<a href=http://www.filedropper.com/particlesplaneloc><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >upload files online</a></div>

as of these isues... dont know what to do, sorry.

**Comment by enzyme69** [comment]
@Kosvor2  Thanks, will leave it there for now!
