### ISSUE TITLE
Object ID Set with Object Out socket

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1408]
![screen shot 2017-03-24 at 10 47 30](https://cloud.githubusercontent.com/assets/3952687/24274857/54cb6142-107f-11e7-928e-57c682e4746c.png)

Maybe not too urgent, but I have a feeling maybe Object ID Set can have Object ID Out Slot so that the node noodles flow can keep the node tree flowing to the right side. Especially when we have all kind of attributes and params to modify.

**Comment by zeffii** [comment]
yeah maybe..   or an alternative Obj Id Set that detects the attributes and enumerates them, and lets you add inputs automatically.

**Comment by zeffii** [comment]
when you use the term 'piggy backing', i think you mean 'daisy chaining'.
> COMPUTING
connect (several devices) together in a linear series.

**Comment by enzyme69** [comment]
You are right... daisy chain! How did I ever came up with piggy back *gulp*
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by Kosvor2** [comment]
All nodes that operate with objects must have an output of objects. Thus, I believe, it will be possible to control their execution order. Sometimes it is necessary that some are performed earlier and others later.

**Comment by zeffii** [comment]
The easiest way to do this is to add the Objects out as a second socket, after values.. what do you think @Kosvor2 ?

**Comment by Kosvor2** [comment]
OK

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1410
what you think @Kosvor2  ?

**Comment by nortikin** [comment]
for SVRX may be node's subclass with default object in and out for some nodes...
