### ISSUE TITLE
Get Selected and Active Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1409]
Maybe at some point, one will find the need to select Object(s) by Active and Selected.

![screen shot 2017-03-24 at 18 19 27](https://cloud.githubusercontent.com/assets/3952687/24284270/8d36a192-10be-11e7-9c0c-f6343d3ac3fa.png)

What do we reckon?

**Comment by enzyme69** [comment]
Oh... "Select" is actually attribute!

![screen shot 2017-03-24 at 18 25 17](https://cloud.githubusercontent.com/assets/3952687/24284427/4eb83e16-10bf-11e7-910c-7fcfde343814.png)

Hmm... here json cannot be exported.

[selected_001_2017_03_24_07_26.zip](https://github.com/nortikin/sverchok/files/867151/selected_001_2017_03_24_07_26.zip)

**Comment by enzyme69** [comment]
Just need one more thing to find the Active Object, which is probably need to be the same type and only 1 active object possible.

Probably the answer is a single liner Script Node?

**Comment by zeffii** [comment]
how about google.

**Comment by enzyme69** [comment]
@zeffii 🤘🏽

![screen shot 2017-03-24 at 19 26 04](https://cloud.githubusercontent.com/assets/3952687/24286107/c8ae87c2-10c7-11e7-9fb8-bd69de0f97d7.png)
