### ISSUE TITLE
Inverting Proportional Edit Mask

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1411]
Found something funny, I tried to invert the value of Proportional Edit Mask and not getting expected result.

![inverting_001](https://cloud.githubusercontent.com/assets/3952687/24292261/add76446-10e0-11e7-9b2b-356166bae2bd.gif)

Any idea @portnov

**Comment by enzyme69** [comment]
https://gist.github.com/275bc956e2d330589773c9d75c2f1b14

**Comment by zeffii** [comment]
i think this is just a radius vs falloff issue

https://gist.github.com/964a7d63b615c4c51ed2af5a0edbb993

![image](https://cloud.githubusercontent.com/assets/619340/24292624/709e8a0c-108e-11e7-885f-470c3031c7e8.png)

**Comment by enzyme69** [comment]
@zeffii How did you invert it? I saw your example, it's not doing it.

**Comment by enzyme69** [comment]
Oh wait, it does work. But how?

**Comment by enzyme69** [comment]
Oh... bigger value of radius... hmmm.. I guess that will do. Strange though. Thanks!

**Comment by zeffii** [comment]
if you think it's strange, then you don't understand it. inspect the example closer.

**Comment by zeffii** [comment]
what would be really cool. ... is if there was a way to render the volume of the sphere (of radius) and the volume of the falloff to the radius separately.. something like :  

![image](https://cloud.githubusercontent.com/assets/619340/24294863/988faad2-1098-11e7-9e90-b60e34bb1ab6.png)
![image](https://cloud.githubusercontent.com/assets/619340/24295017/4252f722-1099-11e7-88ad-6c24d9f5089c.png)

https://gist.github.com/a3ce003718df5f1a00beaa407765d814

would make it a less confusing maybe..

**Comment by portnov** [comment]
@enzyme69 
You can also use Math node after Proportional Edit, to have formula like "1-x" applied for falloff coefficients.
