### ISSUE TITLE
Possibility for GP Duplication and Instancing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1414]
@zeffii 

Currently exploring GP node in Sverchok. I can make bunch of circles with different random colors and size, which is totally unbelievable.

But, right away I was wondering the possibility of GP node to actually do duplications or instancing:
![screen shot 2017-03-25 at 22 17 08](https://cloud.githubusercontent.com/assets/3952687/24321772/e0e2b642-11a8-11e7-9073-427d304c609d.png)

Like perhaps we have 5 different flowers, and then want to have 1000 of them.

Would it be too tricky to implement at the moment?

I could imagine that if the flower can be generated procedurally, perhaps it is possible to output them. It would be a lot easier to manually duplicate strokes or perhaps turning GP into Curves.

Probably super tricky to think about strokes grouping, stroke colors, stroke etc... and wondering if that is a workflow anyone would really want to embrace.

But, before going too far, so if we have 1 flower (in color, few palettes, made of few strokes), can we make the same flower duplications?

[sv_gp_001_2017_03_25_11_22.zip](https://github.com/nortikin/sverchok/files/869956/sv_gp_001_2017_03_25_11_22.zip)

**Comment by enzyme69** [comment]
Ok I have suddenly an idea:
A possible scenario is if Sverchok can transform Matrix the GP strokes as a group.

Maybe it is actually good idea to get some feedbacks from GP animator users and what is the current GP limitation and how Sverchok can work around the limitations.

Some possibilities:
- Way of quickly instance and randomize, maybe even use Particles a bit.
- Resampling strokes
- Animating procedurally, for leaves, rains, etc
- Some kind of way to rig Grease Pencil, but then BONE should come here.

Maybe GP workflow would be better if GP itself a First Class Object in Blender. 

Anyhow, I will explore the Sverchok GP that we can already do. BRB...

**Comment by zeffii** [comment]
I think you are overestimating the 'lightweightness' of the GreasePencil interface.

what's a "BONE" , do you mean Bone?

**Comment by zeffii** [comment]
but yes, duplicating Strokes and layers should be doable. just not an immediate goal..

**Comment by enzyme69** [comment]
@zeffii Yes _bone_. I will test it first.

**Comment by zeffii** [comment]
btw, "passing" points only makes sense for getting the content of a frame's set of points.. if you want to manipulate a frame , and have a dynamic set of strokes which can grow or shrink, don't use _passing points_.

**Comment by zeffii** [comment]
can we slow down a little and get to nice version of GP pencil node first.. along the way i'll keep this in mind.

**Comment by zeffii** [comment]
current version is Beta, and will change .. but I did consider adding Matrix input..undecided.

**Comment by enzyme69** [comment]
Roger that! Thanks for this node btw, it's big :D 🥇
