### ISSUE TITLE
Maybe every constraint needs to become a node...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1416]
Starting with "Look At Camera" constraint. Is there an easy way to accomplish this already in Sverchok? Maybe if we have Grease Pencil to always look at X object / camera?

**Comment by zeffii** [comment]
From what I can tell grease pencil layers/strokes don't have a matrix like Objects do, so making that possible is more involved than simply nodifying the constraints.

Unless somehow strokes are transformed according to the Matrix of the Object they're associated with... that would be a nice surprise...

**Comment by Kosvor2** [comment]
"Look At" constraint:

![look_at1](https://cloud.githubusercontent.com/assets/22656834/24329959/cda9e6e2-122d-11e7-8827-a2d64db99f11.png)

**Comment by enzyme69** [comment]
@zeffii Grease Pencil seems messier when exported out as mesh with fill, but it is already quick nice as strokes. Maybe wait till Blender 2.8 - 3.0 when GP is a real object?

@Kosvor2 Thanks! I will test this out!!!

Close for now..

**Comment by zeffii** [comment]
> @zeffii Grease Pencil seems messier when exported out as mesh with fill

you mean it's tesselated? by all means show an image

**Comment by enzyme69** [comment]
@zeffii maybe when I encounter again. currently I think best if each grease pencil shapes I want to pass into as data for other grease pencil is a single shape.

**Comment by zeffii** [comment]
i tried passing Suzanne to GP, but it seems to draw the faces first to last (normal of the face is ignored) ..

![image](https://cloud.githubusercontent.com/assets/619340/24331594/a334c198-1237-11e7-8bbb-b391dc55b1c9.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24331606/e03540d6-1237-11e7-96d1-019a12a33bf5.png)
