### ISSUE TITLE
Exploring GP node for Crosshatching

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1421]
I am testing the idea of using Sverchok to create CrossHatching effect, perhaps to recreate painting. 2D at the moment, but can be 3D as well.

https://gist.github.com/9abec37feeb315f78e420ddc5dbf74e5

![screen shot 2017-03-27 at 11 46 47](https://cloud.githubusercontent.com/assets/3952687/24336977/27473ba4-12e3-11e7-9806-beb0013dd0b8.png)

When working with GP, often time I found this situation where multiple strokes combined into single connected lines. Probably there is a way around it?

I think similar effect happens with using Polyline. 

My guess is that we can either "cut" the connecting lines between strokes, or this is some kind of functionality that can be added to Polyline Viewer or GP node?

**Comment by enzyme69** [comment]
![screen shot 2017-03-27 at 11 50 39](https://cloud.githubusercontent.com/assets/3952687/24337014/9f188174-12e3-11e7-9692-715174179176.png)

**Comment by enzyme69** [comment]
Not just the "cyclic" but also separation of every strokes.

**Comment by zeffii** [comment]
Each time you lift the pen you end a stroke, there are no gaps possible in gp strokes, unless you fake it using a segment using very small pressure.. but you might still see it.

Cyclic closes the stroke, but if you stroke  is closing even without cyclic then you might be passing fewer points than the stroke needs.. that is why the gp node is needed, don't use obj is set to dynamically push points.

**Comment by zeffii** [comment]
so if you hopes relied on passing multiple polyline segments as one stroke, let me crush those hopes, 

```
# one polyline (one stroke)
X-----------X---------------X----------------X

# two polylines (two strokes)
X-----------X---------------X----------------X      X-----------X---------------X----------------X
```
these need to be separate strokes. This is simply the way GP works.. not as much a limit as it is "a law of nature until B3D Developers change it ".

**Comment by zeffii** [comment]
hmmm, i might be wrong about this.. but the current GP Node won't be updated for a while.

**Comment by enzyme69** [comment]
Will find a work around this, thanks Zeffii!

**Comment by zeffii** [comment]
nope. one connected line per stroke. sorry to get your hopes up.
