### ISSUE TITLE
GP Explore Multi Lines Stamping

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1422]
I started with few strokes called it Grease Pencil A, and I wanted to random stamp those few strokes for Grease Pencil B.

![screen shot 2017-03-27 at 16 04 05](https://cloud.githubusercontent.com/assets/3952687/24341696/30cec7d6-1307-11e7-9e01-4a54510daa1d.png)
[gp_multi_strokes_002_2017_03_27_05_03.zip](https://github.com/nortikin/sverchok/files/871518/gp_multi_strokes_002_2017_03_27_05_03.zip)

I am trying to prevent "Joining" the lines, while keeping this grouped Grease Pencil A strokes as it is, to perhaps replace Polygon Face by Adaptive.

GIST:
https://gist.github.com/bf5a352dc2992aa3c94b32213e0d1599

Can this actually be simpler, or I am doing the right thing?

Thanks!

**Comment by enzyme69** [comment]
![screen shot 2017-03-27 at 16 06 43](https://cloud.githubusercontent.com/assets/3952687/24341728/6448b522-1307-11e7-92e7-12c0e35ff341.png)

**Comment by zeffii** [comment]
> Can this actually be simpler, or I am doing the right thing?

if it works, it's OK.

**Comment by enzyme69** [comment]
Ok will try this!

**Comment by enzyme69** [comment]
Watching every strokes and fill :D 
![screen shot 2017-03-27 at 20 20 23](https://cloud.githubusercontent.com/assets/3952687/24349531/1332d6e4-132b-11e7-93e1-264cbf02cbb1.png)
