### ISSUE TITLE
Switch Node vectorization

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1423]
![image](https://cloud.githubusercontent.com/assets/619340/24346229/bd3a3180-12d3-11e7-94ba-14b2633eca47.png)

maybe a cheeky MK2

**Comment by zeffii** [comment]
else..
![image](https://cloud.githubusercontent.com/assets/619340/24346346/2dd4084e-12d4-11e7-99bb-936d6e7c69e5.png)

**Comment by enzyme69** [comment]
I believe this can help with Grease Pencil :)

**Comment by zeffii** [comment]
if it was possible to set the opacity of each segment then yes :) .. but it isn't currently.

**Comment by scorpion451** [comment]
I'm enthusiastically seconding this one, and suggesting bumping up the priority- I'm constantly running into situations where I _really_ need a vectorized switch node. That's the entire point of a programmable switch, after all- _not_ having to manually process data one operation at a time.

**Comment by zeffii** [comment]
The switch node is a little bit complicated internally, can't promise i'll get around to it in the immediate future.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25862851/cad2e07a-34e9-11e7-83e1-d01789a91b0d.png)

instead of editing the existing code, best I can do is add another mode.

**Comment by zeffii** [comment]
i've pushed a vectorized version,  the single mode retains original behaviour, while 'multi' adds behaviour that I think is useful in other situations. (it also auto wraps Object Lists so if needed. )
