### ISSUE TITLE
Multi Extrude Along Path

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1427]
Back to this one. Multi extude node is there, and I am trying to make sense of this node for Multi Extrusion.

https://gist.github.com/28ce6a2aa3b26d729c7f610e72e6b0aa

![screen shot 2017-03-28 at 19 24 48](https://cloud.githubusercontent.com/assets/3952687/24395725/4e058ef8-13ec-11e7-8eff-19f26ace5302.png)

@portnov I am doing this wrong.

Any hints?

**Comment by enzyme69** [comment]
Using Grease Pencil Resampled Curve also failed:

https://gist.github.com/43e7d8706e74f30ffbce6abd7965e253

![screen shot 2017-03-28 at 19 33 33](https://cloud.githubusercontent.com/assets/3952687/24396025/8674c348-13ed-11e7-8d0b-c8d558dff471.png)

I think the missing thing here is how to convert Direction to Rotation.

**Comment by zeffii** [comment]
please consult: https://github.com/nortikin/sverchok/blob/master/docs/nodes/modifier_change/extrude_region.rst

closely.
