### ISSUE TITLE
Something wrong with Texture Viewer?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1428]
I tried all kind of inputs, nothing seems to work anymore.

![screen shot 2017-03-28 at 20 44 39](https://cloud.githubusercontent.com/assets/3952687/24399110/687f772a-13f7-11e7-990a-d142b57e1e62.png)

**Comment by enzyme69** [comment]
@kalwalt This node used to be easier to use... but now I am confused.

**Comment by enzyme69** [comment]
Ooooh... This node is now more strict with dimension 🤡

![screen shot 2017-03-28 at 20 54 04](https://cloud.githubusercontent.com/assets/3952687/24399523/c5e38072-13f8-11e7-91ca-317ac572bb58.png)

**Comment by enzyme69** [comment]
I kind of like the ability to see the texture filling up ... but well I guess have to live like this.

**Comment by kalwalt** [comment]
> Ooooh... This node is now more strict with dimension 

@enzyme69 yes because we change a bit the code, for the `passing` to internal editor. Maybe in a near future will be possible again. Now i prefer to work on the other pull requests, sorry.

**Comment by enzyme69** [comment]
I think if possible to change the code so that we can get "the feel good of the pixels filling the grid" squares again, instead of errorring out and only accepting 64, 128, 256, etc.

I will make a live noding about this.

**Comment by enzyme69** [comment]
![filling_up](https://cloud.githubusercontent.com/assets/3952687/24434894/fe01298e-147d-11e7-8042-47373f510138.gif)

This is what I mean by "Nice Feeling" data filling up the container. What do you think @kalwalt  @zeffii

**Comment by enzyme69** [comment]
![filling_up2](https://cloud.githubusercontent.com/assets/3952687/24435026/a8f8c5e0-147e-11e7-9fab-0dabd062e24c.gif)

Yeah, I think makes me sad....

**Comment by enzyme69** [comment]
But not urgent I guess I can close it.

**Comment by enzyme69** [comment]
![screen shot 2017-03-29 at 14 13 24](https://cloud.githubusercontent.com/assets/3952687/24436929/f49f0652-1489-11e7-9cfb-1e88a839273d.png)

This actually works...  and makes me happy again. I guess I will do another Live Noding talking about this "feeling good sliding interactive".
