### ISSUE TITLE
Comparing 2 Vector Array to get Mask

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1429]
Suppose I have 2 Vector Array:
1) Grid
2) Randomly scattered points (perhaps along the grid)

How in the most effective way in Sverchok to somewhat get the visualization to compare the two?

I thought we have such case already in the past. My guess is by using distance, but then it didn't work.

I am thinking to use Grease Pencil to get the weight distance. Currently, Dynamic Paint is my only thing I could think of.

**Comment by enzyme69** [comment]
![screen shot 2017-03-28 at 21 05 16](https://cloud.githubusercontent.com/assets/3952687/24399930/43cb7840-13fa-11e7-9ce3-7b5e459952ec.png)

**Comment by enzyme69** [comment]
One example of the same case is like below:

[getting_weighting_001_2017_03_28_10_10.zip](https://github.com/nortikin/sverchok/files/875263/getting_weighting_001_2017_03_28_10_10.zip)
![screen shot 2017-03-28 at 21 10 10](https://cloud.githubusercontent.com/assets/3952687/24400118/f9d1b5be-13fa-11e7-85e1-97c77d38d1f5.png)

By using that setup with Dynamic Paint, we can sort of getting the *mask* of the grid based on Grease Pencil strokes.

We have some ways to get Selection Masking, maybe this "select by grease pencil distance points" is the one missing one.

And at some point, would like to also being able to transfer the value into Texture Viewer.

**Comment by zeffii** [comment]
i recall answering some thing like this about Led lighting matrix.

**Comment by enzyme69** [comment]
@zeffii Maybe my brain cannot compute tonight. I will search your LED Matrix.

I found all kind of weird issue like Blender or Sverchok is not reading Vertex Weighting from Dynamic Paint, even with Post Modifier turned on.

It reads other Vertex Weighting correctly though.

![screen shot 2017-03-28 at 21 27 21](https://cloud.githubusercontent.com/assets/3952687/24400767/57f60026-13fd-11e7-8d19-a31d93a7d127.png)
[Uploading dp_001_2017_03_28_10_25.zip…]()

Will check tomorrow ...

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/884#issuecomment-248259918

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/860

**Comment by enzyme69** [comment]
@zeffii Aha, Thanks I think I can study your examples again and may have another method.
