### ISSUE TITLE
Live Dynamic Paint weight is no longer readable in Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1430]
This is weird, I thought I went crazy, but I think Dynamic Paint weight (that is live) used to be readable in Sverchok.

But static dynamic paint works fine.

I'll upload example real soon....

**Comment by enzyme69** [comment]
[dp_003_2017_03_28_10_42.zip](https://github.com/nortikin/sverchok/files/875344/dp_003_2017_03_28_10_42.zip)

**Comment by enzyme69** [comment]
Static weight paint actually works fine. It's the Dynamic one that is strangely failed to work.

![screen shot 2017-03-28 at 21 43 31](https://cloud.githubusercontent.com/assets/3952687/24401310/9e477db4-13ff-11e7-9358-2bef4dc4c025.png)

**Comment by enzyme69** [comment]
I have suspicion that this is Blender bug. But how to report this issue is tricky.

**Comment by zeffii** [comment]
you probably need to have animation playing.

**Comment by enzyme69** [comment]
@zeffii Yes, I tried, but something is broken or behaviour changes in DP inside Blender again.

I always have weird suspicion that Dynamic Paint is quite broken a while ago:
1) Dynamic Paint only works and updates on the 1st frame
2) Sometimes Dynamic Paint weighting is only showing the last result
3) Ideally Dynamic Paint weighting is changing overtime.

I tried reporting this dynamic paint weight bugs many times to Blender, but always got closed/ignored. I talked to Miika H, the developer of Dynamic Paint a while back ago, he seems to understand what happened, but he asked me to report to Blender Foundation.

Anyhow...

I am curious on why the Dynamic Paint in 3D view is working, but the data is not transferring. Maybe we can somewhat access that data.

I'll check again tomorrow, brain is a bit burning.

**Comment by zeffii** [comment]
but if you do decide to do a bug report to Blender .org  then don't include any mention of Sverchok. You need to be able to produce the problem without any sverchok involvement.

it's not like sverchok doesn't have bugs :) it's very possibly an update scenario we haven't tested. Sadly i'm not a DP user so i'm not exactly motivated to track down the cause. maybe @Kosvor2  ?

**Comment by Kosvor2** [comment]
I have cheked this Sverchok version: https://github.com/nortikin/sverchok/releases/tag/0511
It also doesnt work with Dynamic Paint weight.

**Comment by zeffii** [comment]
thank you @Kosvor2

**Comment by enzyme69** [comment]
Hmm.... strange. I swear it works at one point. Searching for proof.....

**Comment by enzyme69** [comment]
Logically it should works when Hair is turned on. But apparently still not... which is weird. I remember having this conversation ... dejavu?

Sverchok can maybe take advantage of Dynamic Paint viewing the weight changing?

**Comment by enzyme69** [comment]
I knew it!
https://github.com/nortikin/sverchok/issues/872

I think I can work around this Blender limitation.

**Comment by enzyme69** [comment]
![dp_experiment_001](https://cloud.githubusercontent.com/assets/3952687/24432826/6c413906-1470-11e7-8818-c8f83b217441.gif)

[dp_test_002_2017_03_29_00_11.zip](https://github.com/nortikin/sverchok/files/877398/dp_test_002_2017_03_29_00_11.zip)

The limitation imposed by Blender for Dynamic Paint not updating the live weight is absurd. As the changing weight itself is possible to be used inside Hair simulation (Length). I don't know how they hide this data.

But, anyhow, the animated Vertex Weight can affect the Displace Modifier, which Sverchok can use by comparing the Distance before and after. 

Not sure if there is another way to to get this value without having to use Displace Modifier. Maybe one day. For now I think its good for quick experimentation with Grease Pencil.
