### ISSUE TITLE
Object ID Export GIST failed

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1431]
Sorry to report this issue twice under different thread. But I am using Object ID nodes more often and when exporting to the GIST, it failed me more often too.

Sometimes it works, the strange thing is.

[sv_look_at_constraint_002_2017_03_29_00_55.zip](https://github.com/nortikin/sverchok/files/877470/sv_look_at_constraint_002_2017_03_29_00_55.zip)
![screen shot 2017-03-29 at 11 55 27](https://cloud.githubusercontent.com/assets/3952687/24433783/d0791a3c-1476-11e7-9283-ab1a19547759.png)

For example this Aim Constraint example from Kosvor, I was hoping I could export as JSON, but nope it is giving me an error.

I swear at some point that I can do this, but on other occassion it fails me.

If we can JSON every nodes, it would be nice.

**Comment by zeffii** [comment]
I might try to catch that exception and display a message to the user, to tell user to use a zipped blend for sharing instead.

The gist I/o stuff was designed for layouts that generate from scratch , with the exception of the " obj in " nodes,

**Comment by enzyme69** [comment]
Fully understood. Thanks~

**Comment by zeffii** [comment]
> If we can JSON every nodes, it would be nice.

i agree, but it's not my goal. The json / Gist should be considered lightweight sketch interchange between people. 

i am considering adding an operator that loads `zipped .blends` from a weblink. The code already exists [here](https://github.com/nortikin/sverchok/issues/1084#issuecomment-270209446)
