### ISSUE TITLE
GP Symmetry Mirror

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1433]
![screen shot 2017-03-29 at 17 29 25](https://cloud.githubusercontent.com/assets/3952687/24441442/57757534-14a5-11e7-9a18-bc6a46f287d8.png)

I am testing an idea of using Sverchok to quickly Mirror GP drawings.
https://gist.github.com/0ee8d9439cc46b9c0ae215156924c444

Sort of work, except that I need to manually update via frame update each time. If there is another trick to trigger update based on date changes (Grease Pencil)?

Thanks!

**Comment by enzyme69** [comment]
And also another gotcha:  if one uses **up** and **down** to jump frame of Grease Pencil, it's also not updating on the frame, there is this 1 frame delay thing.

**Comment by zeffii** [comment]
> there is this 1 frame delay thing.

yeah. this was reported already.

**Comment by zeffii** [comment]
>  If there is another trick to trigger update based on date changes

date changes?

**Comment by zeffii** [comment]
but I completely see the usefulness of having live update enabled for a GP Stroke system, so that might happen... it might mean a separate `GP specific Selector` node.. but uncertain

**Comment by enzyme69** [comment]
Ok can close this until further needs, I guess. I can brute force. 

I mean "data changes" :)

**Comment by zeffii** [comment]
but really... maybe it should be it's own addon. Sverchok doesn't have to do everything.

" Jack of All trades, master of None "

**Comment by enzyme69** [comment]
That's me: Masters of None.

**Comment by zeffii** [comment]
My interpretation of Blenders update system is that it is less than convenient to filter all the various update events, it would be cool to have a routing system like webpages..

```
    if update_event in {
        'GREASE_PENCIL_NEW_POINT', 
        'GREASE_PENCIL_NEW_STROKE'
        ... etc
    }:  then do this
   
    .... other events do something else

    .... other event ignore only if some condition X is True

```

**Comment by zeffii** [comment]
I think if you really wanted you could make an add-on / operator  by studing the GP Node and the Python template for `operator_modal_draw.py` .
