### ISSUE TITLE
Loading Zipped .Blends from URL

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1434]
only to be used on trusted sources. It's up to you to know what you're doing. Anyway...

##### steps

0. be sure to save your current work.. the following steps will try to load a new blend.
1. [copy a zipped .blend url](https://github.com/nortikin/sverchok/files/878707/recuva_2017_03_29_10_35.zip) (only zips loaded on the issue tracker here will work`*` ) into your clipboard
   
2. in nodeview hit `space` -> `Load z..`  should be enough
    ![image](https://cloud.githubusercontent.com/assets/619340/24449579/fd9fe8fa-1477-11e7-966d-8e5ee6a8aeab.png)

    this pops up
    ![image](https://cloud.githubusercontent.com/assets/619340/24450764/62aa798c-147c-11e7-90b3-327d1c39fbb6.png)

3. press OK. it will load the url found in your clipboard.  (no manual pasting)
4. wait for progress bar.
5. observe a newly loaded .blend

`*` other zips will work, but they need to be structured the same as saved from sverchok's zip.blend saver

**Comment by zeffii** [comment]
[recuva_2017_03_29_10_35.zip](https://github.com/nortikin/sverchok/files/878707/recuva_2017_03_29_10_35.zip)

**Comment by zeffii** [comment]
added

**Comment by nortikin** [comment]
ahaha!!!!ahahahaha!!!!!hahaha!!

omg!

**Comment by zeffii** [comment]
i know it works on windows... but probably not on linux because i hardcoded `C:\tmp`..

**Comment by nortikin** [comment]
`sh
blender-2.78-linux-glibc211-i686/2.78/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot get archive from Internet

`

**Comment by zeffii** [comment]
added exception handleing.. now also you can load a zip without the dialogue

![image](https://cloud.githubusercontent.com/assets/619340/24576842/6a6cd3e2-16c3-11e7-8912-aff8cbf25272.png)
 it will start downloading immediately (if the clipboard has content)

**Comment by zeffii** [comment]
Downloads are unpacked to your system's temp folder. so save the .blend in an alternative folder if you want to keep it.
