### ISSUE TITLE
Experimental: MIDI Notes using Sequencer Editor and Sonic Pi

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1436]
![screen shot 2017-03-29 at 22 32 35](https://cloud.githubusercontent.com/assets/3952687/24452600/b8271b2e-14cf-11e7-89dc-55018b16174c.png)

I am thinking to use Sequencer Editor to generate some kind of Musical Generator, this way we can easily:
- set timing
- length of notes and rest
- melody notes high low

This will requires Sonic Pi, will try the "live loop" built in threading concurency.

So far... I manage to modify Number Text String using Sverchok.

The melody should be triggered via Script Node, maybe. But supposedly, as the Timeline is playing, it is sending message into Sverchok to trigger the sound.

**Comment by enzyme69** [comment]
[sequence_block_005_2017_03_29_11_36.zip](https://github.com/nortikin/sverchok/files/878850/sequence_block_005_2017_03_29_11_36.zip)

**Comment by enzyme69** [comment]
First question:
Supposed I have bunch of Sequence Block with name "Notes.001" etc, how to grab list of just sequence block with that name using Object ID?

I can grab all using [:] but filtering it by type or name, not sure.

![screen shot 2017-03-29 at 22 40 38](https://cloud.githubusercontent.com/assets/3952687/24452820/d85819d8-14d0-11e7-9931-9165df2737e2.png)

**Comment by enzyme69** [comment]
Actually... this works.

![screen shot 2017-03-29 at 22 43 13](https://cloud.githubusercontent.com/assets/3952687/24452872/269484ce-14d1-11e7-8a81-1860d24f1f4e.png)


Any tips on how to filter by Sequence Type?

**Comment by enzyme69** [comment]
Probably this requires a bit of thinking, but so far kind of have the rough ideas:
- Not sure how to properly sorting all the blocks from Start to End, currently probably just sorted by their names
- **frame_start** can be the trigger
- **channel** position can be the notes pitch
- need a way to check a running frame and trigger midi 

![screen shot 2017-03-29 at 22 46 55](https://cloud.githubusercontent.com/assets/3952687/24452980/aa264fe8-14d1-11e7-941d-3e7f6091536f.png)
[sequence_block_005_2017_03_29_11_46.zip](https://github.com/nortikin/sverchok/files/878878/sequence_block_005_2017_03_29_11_46.zip)

Will sleep and try simple one do, re, mi, etc.

**Comment by zeffii** [comment]
this should be a blog post... not an issue for the tracker.   i mean.. it's interesting.. and i have thoughts about it ..   make your own Github repo jimmy and use it as a 'sverchok experiments' issue tracker.

**Comment by enzyme69** [comment]
ok. sorry~

**Comment by zeffii** [comment]
seriously. make your own GitHub repository _now_. 
you'll even be able to drag in .blends into folders on the repo..

**Comment by zeffii** [comment]
i do it too.  https://github.com/zeffii/weblog

**Comment by nortikin** [comment]
ahaha!!
