### ISSUE TITLE
Visualizing Select By Components BBOX and more

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1442]
![screen shot 2017-03-31 at 22 55 45](https://cloud.githubusercontent.com/assets/3952687/24549489/3d227b84-1665-11e7-82aa-9ce63cf1fd29.png)

gist:
https://gist.github.com/64a9fbd2a0c557b0653149977f5a6ec3

@portnov The bbox itself, can it be based on "Bounding Box" node that can rotate scale etc.?

**Comment by portnov** [comment]
I'll think about it. Probably I can add "Origin" input for BBox mode, to indicate axis directions for bbox.
