### ISSUE TITLE
GP to a Mesh: UV connection slice issue and alembic export no update on mesh

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1446]
I tried a example test with GP and UV connection, but slice or no slice seems to give a different issue.

Slice On:
Frame one failed

Slice Off:
other frames failed to generates mesh

[shadow_test_001_2017_04_01_00_45.zip](https://github.com/nortikin/sverchok/files/887222/shadow_test_001_2017_04_01_00_45.zip)

**Comment by enzyme69** [comment]
![slice-or-noslice](https://cloud.githubusercontent.com/assets/3952687/24573587/f00c3120-16d0-11e7-9e8d-8d9fc6c707a3.gif)

**Comment by enzyme69** [comment]
List Join before UV connection seems to fix it.

But the next issue is that when exporting this changing Mesh as Alembic animation, it does not read the changing data...

**Comment by enzyme69** [comment]
[shadow_test_006_2017_04_01_01_24.zip](https://github.com/nortikin/sverchok/files/887239/shadow_test_006_2017_04_01_01_24.zip)

**Comment by zeffii** [comment]
I don't think gp can be Baked directly, so use bmesh view? I'm running into all kinds of problems using and updating the gp node code. Frame lagging is the least of my worries. Thats an obj id selector related issue.

**Comment by zeffii** [comment]
And possibly frame_change_pre vs post... Animation issues get solved last.

**Comment by zeffii** [comment]
the fact that you want to use the baked mesh for a shadow - is not relevant to the problem.

**Comment by zeffii** [comment]
@enzyme69   what do you think UVConnect's _Slice_ does?

**Comment by zeffii** [comment]
In zip shows on frame one you have 2 strokes, and the other frames 1 stroke. This means the UV Connect node isn't expecting a change in the incoming data.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24577314/ca70c818-16cb-11e7-9709-92f52016203e.png)
that would force the input to be a single stroke

**Comment by enzyme69** [comment]
@zeffii To be really honest, sometimes I assume "slice" does something, but never 100% sure. 

Thanks for looking into this "issue", much appreciated.

**Comment by zeffii** [comment]
i'm not sure i know what slice does either.

**Comment by nortikin** [comment]
slice cut data on peaces by level (by objects, by vertices, etc)
