### ISSUE TITLE
Organizing search menu - brainstorming

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1451]
Start a thread to start adding some notes regarding the search menu.

Adding custom icons feature to SV was a start but more needs to be done to make the search menu look presentable (IMO).

- Obviously the custom icons are still needed to be created and added to the nodes/categories. Once the icon manager is in place and we come up with a design guidelines we should be able to start creating custom icons to populate the search menu.

- Should the submenus be line separated into sections just like the main menu ? (see the animation node search menu screenshot)

- Should the node names have an alternative shorter name instead of the full name ? E.g Vectors/Mix Vectors could be just Vectors / Mix. Matrix / Matrix Shear could be just Matrix / Shear (see the animation node search menu screenshot)

... add your own ideas ...

![an-searchmenu](https://cloud.githubusercontent.com/assets/2083719/24580173/7e4f2d5c-16d1-11e7-8d03-1a0ce29f8f71.png)

**Comment by zeffii** [comment]
I am the "module owner" of ctrl+spacebar menu. 

>  more needs to be done to make the search menu look presentable (IMO).

I don't share that opinion, but I do agree with some of your statements/question

1. I agree that if the category is called f.ex  Matrix, then the menu items inside it don't need to also show the label prefixed with Matrix. **(relatively simple to fix)**
2. while the `bl_label` should still show that prefix for two reasons:
     - when a Node has been added to NodeView  
     - using the Search (ctrl+spacebar -> enter) to look for a node by name.
3. yes a few new categories are intended. (Color, Interpolation...)

I think part of why our menu is so "underdeveloped" is because the Search by name feature is far superior. Navigating menus just slows you down. Developing the UI menus therefore never takes precedence.

We are not trying to grow towards AN. Personally my gut reaction is to avoid moving closer to AN just for diversity's sake. Maybe @nortikin @ly29 have different opinions.

(that doesn't mean a good idea in AN can't be considered for SV, but it would be implemented in a way to makes sense for SV..)   i see this kind of conversation between people who use 3dsmax/maya trying to make Blender more like their favourite tool.  We already like Sverchok, and will implement stuff the way that makes sense for how sverchok works.

**Comment by nortikin** [comment]
i prefare prefix is ok. when i popup list category it looks nice with list prefix, because i see - no mistake.

ctrl+space menu have to migrate to shift+A menu and replace it.

**Comment by zeffii** [comment]
we can modify the `index.md` parser , to read a line that starts with `    ---` as a separator..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24590372/149c0846-17ec-11e7-85fa-3b05518c0ad3.png)

is defined this way
```md
## Vector
    GenVectorsNode
    VectorsOutNode
    SvVectorMathNodeMK2
    VectorDropNode
    VectorPolarInNode
    VectorPolarOutNode
    VertsDelDoublesNode
    ---
    EvaluateLineNode
    SvVectorLerp
    SvInterpolationStripesNode
    SvInterpolationNode
    SvInterpolationNodeMK2
    SvInterpolationNodeMK3
    ---
    SvAttractorNode
    SvVertSortNode
    SvNoiseNodeMK2
    SvVectorFractal
    SvLacunarityNode
    SvTurbulenceNode
    SvVectorRewire
    svAxisInputNode
    SvAxisInputNodeMK2

```

**Comment by DolphinDream** [comment]
Sweet 🤗

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24590524/cb9eb384-17ee-11e7-8e54-e20e7af66a05.png)

We haven't had an exodus of old nodes for a while.. (we remove nodes that have been deprecated by MK2 MK3... )  
- SvInterpolationNode ( mk1, mk2 )
- SvVectorLerp is a full replacement of EvaluateLineNode
- SvAxisInputNode replaced by MK2

**Comment by DolphinDream** [comment]
I agree with what you were saying, @zeffii about menu slowing you down. I also prefer to type the name of the node i’m looking for rather than look up for it in the search menus/submenus. Sometimes though I find myself having to use the menu if for instance i’m not sure what name I’m searching for, or to familiarize myself wth nodes I haven’t used before, so having a nice looking/organized search menu helps :) 

Unfortunately blender doesn’t have a fuzzy search (I wish it had) and if I misspell the name of the node i’m searching for I get no results. I asked the blender devs a while ago why blender doesn’t have a fuzzy search (e.g. similar to the sublime text) and I was told that it would be really slow to search through all the operator names etc. which is IMO, with all due respect, bogus, since sublime text can do it with huge number of files instantly. I doubt blender has that many operator names to search through. Hopefully one day we’ll get it in blender, which should make the search experience much better.

**Comment by zeffii** [comment]
we can implement a fuzzy search - i don't see a problem there.

**Comment by zeffii** [comment]
i propose ctrl+F for that...

**Comment by DolphinDream** [comment]
We can ? :) that would be super neato. I didn’t know you can hack into blender’s search engine. I assume that’s what SV uses in the ctrl+space search. Preferably the ctrl+space search should have the fuzzy search in it (if for instance you can subclass/override blender’s search function or something).

**Comment by zeffii** [comment]
we would be writing our own search :)

**Comment by zeffii** [comment]
we already have all our nodes categorized once per session, from that list we can get bl_idname, classname, and even docstring.. if i'm not mistaken. From that point it's just a matter of writing a general search operator (maybe that takes wildcards.. or closest match..with trailoff ("word ladder")  )

**Comment by DolphinDream** [comment]
Kewl. Here’s SublimeText’s fuzzy search when I type “vecin” which could be for vector index, vector interpolation etc.. I get all files (in this case SV files) containing these characters in this order. I really like it.

![sublimetext-fuzzysearch](https://cloud.githubusercontent.com/assets/2083719/24591102/dab3c6c4-17c7-11e7-89a2-d89a8f2bbd77.png)

**Comment by zeffii** [comment]
I the there's an add-on called 'API search' that implements some kind of search too

**Comment by zeffii** [comment]
" API Navigator " (blender add-on standard distribution)

**Comment by zeffii** [comment]
Ill implement. Invoke_search_popup, scaffolding and we can collaborate on how fuzzy it is

**Comment by zeffii** [comment]
But there a limit to what can be displayed in the default search framework, I think just one string per line,

**Comment by zeffii** [comment]
some options:  http://blender.stackexchange.com/questions/8699/what-ui-would-work-for-choosing-from-a-long-long-list

unfortunately `invoke_search_popup` doesn't appear to pass the string being searched to the items function..

**Comment by zeffii** [comment]
i'll ask around in IRC blendercoders to see if there's a way to get the currently types string from within the items callback.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24606165/2757e254-186c-11e7-9783-a6a61a9faf22.png)

**Comment by zeffii** [comment]
have handled that as far as possible. next step is a little more involved... but open to contributions
[Fuzzsearch](https://github.com/nortikin/sverchok/issues/1471).

**Comment by DolphinDream** [comment]
Finally.. **fuzzy search** is coming to Blender (already in 2.91) :) I wonder if SW can tap into this feature for SV search menu. (@zeffii )

https://youtu.be/iAZhjF-UFKc

**Comment by zeffii** [comment]
ofcourse : )
