### ISSUE TITLE
Should SV have a COLOR node category ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1453]
As color nodes are starting to emerge.. I was thinking if a new node category would be needed.

I was thinking of adding a mix color node (derived mix inputs node) for colors and it could go in such COLOR node category.

**Comment by zeffii** [comment]
yes to color category (this was already discussed in the past here but too few nodes to justify at the time).

**Comment by zeffii** [comment]
the question is not _should_ but _when_.

**Comment by DolphinDream** [comment]
When?

**Comment by DolphinDream** [comment]
Btw.. is there a color socket in the queue?

**Comment by zeffii** [comment]
see the color in / out nodes in Beta,  we just use a StringsSocket type with a custom color.. -- Currently there's not much incentive to make a new socket type, for what can essentially be handled by an existing socket.

**Comment by zeffii** [comment]
"practicality over purity" again :)

**Comment by DolphinDream** [comment]
Thank you for the  moment of Zen, @zeffii  :) it reminds me to always live in the now and accept what (SV) IS and never try to change anything. 😉

**Comment by zeffii** [comment]
> never try to change anything.

we compromise all the time.. but not on everything.

**Comment by DolphinDream** [comment]
I’m not sure if i asked this before.. is there a ColorsSocket in the queue? Should we create one ?

**Comment by enzyme69** [comment]
When we do find a need, we create one :D I think we need UV socket or
something. But I am happy to try any Color Socket.
