### ISSUE TITLE
Output formats 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1458]
I’m (still) trying to figure out the output formats... In particular I don’t quite understand the matrix output vs other outputs..

for a float (e.g. float node) the output format is:
`[[ a ]]`

for a list (e.g. range of floats) the output format is:
`[[ a, b, c, d ]]`

for a vector (e.g. vector in) the output format is:
`[[ (x,y,z) ]]`

for a list of vectors (e.g. random vector) the output format is:
`[[ (x,y,z), (x,y,z) ]]`

though for a matrix (e.g. matrix in) the output format is (similar to a list of vectors):
`[[ (x,y,z), (x,y,z), (x,y,z), (x,y,z) ]] `

while (intuitively) I expected the 4 vectors to be grouped as one:
`[[ ((x,y,z), (x,y,z), (x,y,z), (x,y,z)) ]] `

and the list of matrices the output is :
`[ [(x,y,z), (x,y,z), (x,y,z), (x,y,z)], [(x,y,z), (x,y,z), (x,y,z), (x,y,z)] ] `

while I expected to have:
`[[ ((x,y,z), (x,y,z), (x,y,z), (x,y,z)), ((x,y,z), (x,y,z), (x,y,z), (x,y,z)) ]]`

I sort of got the idea that every output has to have double brackets [[ ]] .. and the value inside are grouped as tuples (x,y,z) for vectors and ((v1), (v2), (v3), (v4)) for matrices, while the single values (floats/ints) don’t get to be in a tuple.

I’m asking this as I’m working on the mix inputs nodes (int, float, vector, color, quaternion, list, matrix) and for all the nodes the derived/base classes work fine as i’m reading the input as sv_get()[0], but for matrix type the code breaks since the vectors in a matrix are not grouped together as I expected.. for matrices I’d have to read the input sv_get() (without the [0]) so that the matrix gets passed to the mixer function as a whole, not one vector at a time. Can someone demystify the output formats for me and why the difference between the matrix and the rest of the types?

**Comment by DolphinDream** [comment]
For the time being, regarding the mix input nodes issue I was having, the way i dealt with this output format differences is by creating a get_inputs() and set_outputs() method in the derived classes that the base class calls before and after interpolating the values. This way each derived class will read the inputs as needed and set the outputs as needed as to conform to the input/output formats.

**Comment by Kosvor2** [comment]
Container list == []
One sverchok object == [[]]
Two objects == [[],[]]
one matrix per object == [M,M]

**Comment by nortikin** [comment]
digits can be directly in object [[x]]
but can be added additional level of data (may call them groups)

[[[x,x,x]]] - original vertex or polygon
[[[[x,x,x]]]] - grouped

**Comment by zeffii** [comment]
see here about Matrix : https://github.com/nortikin/sverchok/issues/1470#issuecomment-291814727

**Comment by zeffii** [comment]
http://nikitron.cc.ua/sverch/html/contribute.html#some-rules

if it's not clear the docs should be updated.

**Comment by zeffii** [comment]
It's up to the node author to decide how they populate their output list, and I think there's some discrepancy among nodes. One place to look for hints is the Matrix Interpolation node.

We intentionally don't force tuple or list in our data types. The tuple has the advantage that it's slightly faster, but at the same time the cost is that it's immutable.

With Matrix the 
```python
v = (x, y, z)   # or [x, y, z]
row = (v1, v2, v3, v4)  # or [v1, v2, v3, v4]
Matrix = [row, row, row, row]  # or   (row, row, row, row)

# non nested
matrices = [Matrix, Matrix, Matrix....]

# nested
matrices = [ [Matrix, Matrix, Matrix....], [Matrix, Matrix, Matrix....], .... ]
```

I think implicit `v->m` socket conversion turns the whole incoming stream into a non nested variant.

**Comment by zeffii** [comment]
It's up to the node author to decide how they populate their output list, and I think there's some discrepancy among nodes. One place to look for hints is the Matrix Interpolation node.

We intentionally don't force tuple or list in our data types. The tuple has the advantage that it's slightly faster, but at the same time the cost is that it's immutable.

With Matrix the 
```python
row = (v1, v2, v3, v4)  # or [v1, v2, v3, v4]
Matrix = [row1, row2, row3, row4]  # or   (row, row, row, row)

# non nested
matrices = [Matrix, Matrix, Matrix....]

# nested
matrices = [ [Matrix, Matrix, Matrix....], [Matrix, Matrix, Matrix....], .... ]
# nested . but this means each top level element just stores 1 matrix..where it could store several
matrices = [ [Matrix], [Matrix.], .... ]
```

I think implicit `v->m` socket conversion turns the whole incoming stream into a non nested variant.

**Comment by DolphinDream** [comment]
So.. since tuples are immutable. would we want vectors to be lists instead of tuples ? e.g. [x, y, z] instead of (x, y, z) ? I would think it doesn’t matter (in general) since the vector input (whether tuples or lists) is used to calculate other vectors for output .. not necessarily changed the input in place. 

Also:
- for colors, quaternions etc..(4 value vectors).. should they be lists or tuples? or maybe it doesn’t matter?
- for matrices.. any reason not to store the matrices as tuple of tuples ? ((x,y,z), (x,y,z), (x,y,z), (x,y,z)) instead of list of tuples (which is basically the same as a list of 4 vectors).

**Comment by zeffii** [comment]
Follow the behavior of nodes you use the most, if you aren't certain go for immutable where it makes sense. Remember we use 4 by 4 matrices.

**Comment by zeffii** [comment]
if you still think it's hocus pocus, reopen.

**Comment by zeffii** [comment]
And feel free to enhance the documentation to include a section about output formats for contributors. -- It can be quite cathartic to express the inner workings of the system in easy to read prose.
