### ISSUE TITLE
Input socket names

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1459]
Can you set a socket label to be different than the socket name ? 

```python
        self.inputs.new(‘VerticesSocket', "v1", "List 1")
```
Note: I’ve seen this in some code but I don’t think the second parameter does what I was hoping it would do :)

Basically I want an input to be named v1 and read as v1.. bu the label of the socket to appear as List 1.

**Comment by zeffii** [comment]
Look at the draw func of that socket's class. For convenience and sanity I disparage creating a scenario where the label is not the same as the socket name.

**Comment by DolphinDream** [comment]
The one situation where i could find this useful is in the derived/base scenario.. where the base defines the input socket v1 and reads the input form v1 but the derived class wants to label it according to the class type (e.g. float, vector etc). In my case I ended up defying the sockets in the derived class and read the input in the derived classes so i can name them any way i want not worrying about the base class.

**Comment by zeffii** [comment]
Then reference socket index

**Comment by zeffii** [comment]
handled I think...
