### ISSUE TITLE
Thinking Group and Cluster

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1460]
![screen shot 2017-04-03 at 20 44 39](https://cloud.githubusercontent.com/assets/3952687/24606354/2621232a-18b0-11e7-84dd-27803f896307.png)

https://gist.github.com/55a64770600ebcb830252e5b59d652e9

I am looking at some of nodes Sverchok already have for Masking and node that performs Transform and Extrude for those Masked Components. This is already quite interesting and unique.

Wondering what would be next for this. Is there going to be a way to "Group and Name" or maybe "Cluster" Vertices, for example:
- Based on Portnov multi center and radius, maybe those vertices can then be manipulated separately as different clusters
- Maybe Grouped or Masked Vertices can be "named" and then at some other stage can be specifically selected.

**Note**: Clustering is Maya thing, a way it groups bunch of vertices as Cluster and it has its own transform, Grouping with Name is Houdini. Houdini is better, it can keep track of Group.

It can be complicated, but maybe for now **Clustering** is probably easier method, especially when dealing with Transforming masked vertices.

Actually... Clustering is kind of happening automatically when Mask and Transform is used. Well... sort of.. Not sure what Blender equivalent to Cluster, maybe more like Bone controlling bunch of vertices.
https://gist.github.com/2e4c261c4ee90040913f601e445e9d40

![screen shot 2017-04-03 at 20 51 00](https://cloud.githubusercontent.com/assets/3952687/24606419/5c1deecc-18b0-11e7-8e9e-f7619ae30177.png)

Oh, by the way, with SV Mask like Select Component, maybe it is nicer to have Vertex, Edge, Polygon output from the Mask node itself, so instead of data stream for mask going out branching, it can be just continuously chaining
![screen shot 2017-04-03 at 20 51 00](https://cloud.githubusercontent.com/assets/3952687/24606419/5c1deecc-18b0-11e7-8e9e-f7619ae30177.png)

What do you reckon?

![screen shot 2017-04-03 at 20 55 03](https://cloud.githubusercontent.com/assets/3952687/24606283/d642cff2-18af-11e7-870d-db2255164940.png)

**Comment by zeffii** [comment]
To attempt a partial answer I'll first define a few words

 - a Mesh : 
       - a set of incoming`Verts / Verts, Edges / Verts, Faces / Verts, Edges, Faces`
 - a BMesh 
       - a data object that bmesh.ops can operate on, usually we use the variable name `bm` 
 - Unstable 
       - not as in crashing, but the expectation that a vertex/edge/face index is the same when it exits a node as it was when it entered the node.

For the most part our data is stable, the index of the Vertex is the same when it goes in as when it exits a node. This is true with most (if not all) transformation operators that we have implemented ourselves.

Quite a number of nodes internally use BMesh operators, this means they will convert any incoming Mesh into a BMesh (`bm`) first then pass the bm to a bmesh operation, and before exiting the node the bm will be converted back to a Mesh. Here is where the Mesh data can potentially become _Unstable_. With BMesh we get the convenience of a lot of prewritten / fast mesh operations, the drawback is that in some operations the output is not Stable (indices can't be assumed to be matching the input).

Some nodes that do use Bmesh.ops do a check before and after and resort the Mesh to be stable. This is a relatively slow operation and the question is "do we really need that always on? or just when needed". Often we don't care at all if the indices are stable before and after a modifier, it might not even make sense to expect continuity. For example how useful is it to keep track of the original indices on an operation like Lathe.. or Remove doubles.. or Subdiv (if we had one).

And so the question is.. where do we implement it ..and who implements it. There's currently not a convenience / library to take care of keeping a Mesh stable. The most important index to keep stable is the Vertex Index. Thankfully that is Stable for any bmesh operation that I can think of.

We can even use `bm.vertices.layer` to keep track of information stored per Vertex, (passed in as a separate socket) , so you could pass a number in parallel to each vector ..and whatever the bmesh operation does (even if it changes the Vertex Count) if will be able to (to some sane degree) output a separate socket of parallel numbers that correspond to the input.. and new Vertices that "emerged" in the bmesh operation will be given the number that matched the input Vertex's parallel passed number.

So the "Vertex Grouping / Clustering" is possible to some degree. But it's not like it's something we'd be able to just switch on... it's not a small logistic issue to go back and retrofit existing nodes. So likelyhood (combined with the fact that we only need it in certain scenarios) that it happens is remote.

---

regarding passing data unchanged in and out...  it's down to who implements the node and how many sockets it has.. Nodes with more than 5 sockets in or out (not total) is symptom of getting a node to do too much..and forgetting that we are a modular system. But yeah, some nodes like object node, it totally makes sense to pass the object reference.


uch.this was too long.

**Comment by nortikin** [comment]
too long deserves be quoted.
will post in vk.com
