### ISSUE TITLE
Sverchok embed into Blender official

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1463]
I was answering questions at Blender Stackexchange:

http://blender.stackexchange.com/questions/76979/is-it-possible-to-make-randomly-colored-objects-via-nodes-in-blender-internal/77026#77026

And the requirements: only use Add-On that comes with Blender _makes me really sad._

How to make Sverchok parts of Blender Add-Ons?

**Comment by zeffii** [comment]
step 1 - Don't worry about those people who for whatever reason don't want to use external add-ons. Not our problem.

I don't think it's realistic to add sverchok, it's not even 0.6 yet.

**Comment by zeffii** [comment]
A simple one/two liner python script would be ok to answer that Q

**Comment by enzyme69** [comment]
Ok~
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
