### ISSUE TITLE
ScalarMath Recode.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1464]
- [x] add modes (Reciprocal, sincos....)
- [x] simplify mode lists / dicts
- [x] simplify node mechanics
- [x] cosmetic upgrade
- [ ] correct draw label when self.hide
- [x] add back int/float switches

a wip

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24665348/6f8b48c6-195d-11e7-9ffd-0aaa32f2c3fe.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24670340/f0114e68-196d-11e7-9f7a-895c1ec628f9.png)

![image](https://cloud.githubusercontent.com/assets/619340/24670417/31acb560-196e-11e7-8b1f-6be1cafcef1e.png)

**Comment by zeffii** [comment]
if there's any math conveniences i'm forgetting now is the time to ask for them.

**Comment by nortikin** [comment]
sadly, i'm not mathematician enough

**Comment by zeffii** [comment]
tau * (1-n / n)

**Comment by kalwalt** [comment]
It could be useful add the gravity constant, and/or other used in physics.

**Comment by zeffii** [comment]
@kalwalt  ok good call , gravity constants. - closing for now.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25890321/5b07373a-356d-11e7-989a-dd569b901cab.png)
