### ISSUE TITLE
Limited Dissolve for "Clean Text Outline"

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1465]
[text_GP_002_2017_04_04_11_23.zip](https://github.com/nortikin/sverchok/files/892917/text_GP_002_2017_04_04_11_23.zip)

![screen shot 2017-04-04 at 21 23 24](https://cloud.githubusercontent.com/assets/3952687/24654471/17734178-197d-11e7-8a98-dccf9ef0ad91.png)

I am using @zeffii  **Limited Dissolve** node. This works really well for grid and for square pixelated mesh, but somewhat I can't get it to work for things like Text. I am trying to get just a clean Text Outline.

Mesh Filter Boundary can get the outer points, but cannot get a clean line, unfortunately.

This case might have been solved in the past, but I could not remember.

**Comment by enzyme69** [comment]
This is what I mean: when square pixelated, it works:
[text_GP_003_2017_04_04_11_28.zip](https://github.com/nortikin/sverchok/files/892925/text_GP_003_2017_04_04_11_28.zip)

The edge is almost perfectly cleaned up.

![screen shot 2017-04-04 at 21 28 32](https://cloud.githubusercontent.com/assets/3952687/24654601/b228c0da-197d-11e7-8cc0-2da87db9a769.png)

**Comment by enzyme69** [comment]
Wait the minute... this actually works!

![screen shot 2017-04-04 at 21 30 11](https://cloud.githubusercontent.com/assets/3952687/24654640/edf9a188-197d-11e7-992a-528f83e96a94.png)

**Comment by enzyme69** [comment]
Haha... I am so happy right now~

https://gist.github.com/b20e6a1857bd74bc7dc942e654045ce5

**Mesh Filter** is apparently can do the job. Who made this node? Thanks!!

![screen shot 2017-04-04 at 21 31 49](https://cloud.githubusercontent.com/assets/3952687/24654695/2919d184-197e-11e7-8847-8320e642b81f.png)

**Comment by zeffii** [comment]
@portnov. did

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24655837/2ceaca40-1940-11e7-9178-e19a603623d1.png)
