### ISSUE TITLE
Velocity, time and distance

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1467]
We seems to have enough tools to generate velocity for particles, let's say if one is drawing using grease pencil and wanting to apply velocity to points...

I watched the grafitti markup language demo, and they seems ro use this to create cool effects.

I think somebody needs to give a demo involving this.

**Comment by zeffii** [comment]
Gp doesn't record time info per point on stroke, you need delta time and delta location to calculate velocity and acceleration. Time to dig into the blender python templates , there's a modal operator for 3d view, which essentially allows you to emulate gp drawing with python and bgl.

**Comment by zeffii** [comment]
there's a few videos around... like [this one ](https://www.youtube.com/watch?v=39y1ktg_Vzo)

in the meantime, you could assume that the GP stroke is constant speed, and that the distance between consecutive stroke-points is proportional to the delta time of the two points - then you got velocity for free.

**Comment by enzyme69** [comment]
Hmm.... "blender python templates" --- I am not that advanced yet.

I'll have a think.

**Comment by enzyme69** [comment]
![interpolation_magic_003](https://cloud.githubusercontent.com/assets/3952687/24699917/fbe9447c-1a38-11e7-9c02-0599fa362eaf.gif)

I just realized that "Linear Interpolation" turns my curve into linear motion (same speed).

However, the distance difference of original points shows the "speed".

![screen shot 2017-04-05 at 19 50 10](https://cloud.githubusercontent.com/assets/3952687/24699954/19ab5784-1a39-11e7-8156-9ce06fb3e34b.png)

I used to be "good" with Math and Physics, but now it's so bad.

**Comment by enzyme69** [comment]
Maybe if I found the measure of every points, we can recreate this "speed" change.

**Comment by enzyme69** [comment]
![screen shot 2017-04-05 at 19 59 06](https://cloud.githubusercontent.com/assets/3952687/24700388/5c6c0298-1a3a-11e7-82a0-9a4834c58169.png)
![interpolation_magic_004](https://cloud.githubusercontent.com/assets/3952687/24700389/5ca70e6a-1a3a-11e7-8c0b-5687a2182cc5.gif)
[trajectory_to_velocity_003_2017_04_05_09_58.zip](https://github.com/nortikin/sverchok/files/895845/trajectory_to_velocity_003_2017_04_05_09_58.zip)

Maybe for what I am trying to do, this mapping might be enough. But it suddenly become dependant on simulation.

**Comment by enzyme69** [comment]
![interpolation_magic_005](https://cloud.githubusercontent.com/assets/3952687/24701127/b60b550e-1a3c-11e7-80ea-193c187c4307.gif)
[trajectory_to_velocity_007_2017_04_05_10_15.zip](https://github.com/nortikin/sverchok/files/895896/trajectory_to_velocity_007_2017_04_05_10_15.zip)

I think I need to make the strokes looking better first, and back to this :)
