### ISSUE TITLE
Twisting Rope using Matrix Tube

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1469]
![screen shot 2017-04-05 at 14 49 26](https://cloud.githubusercontent.com/assets/3952687/24690270/2e18c0a0-1a0f-11e7-8d76-44c051ef0c2a.png)

I am trying to make this Procedural Rope that twisting, based on 3 circles, being iterated. I am using Matrix Tube, but I have a feeling that Matrix Tube does not take multiple inputs.

GIST
https://gist.github.com/a7e25c7f8eafe1874de3d1aa4e337024

Am I doing this properly?

**Comment by enzyme69** [comment]
This is also the wrong way:

![screen shot 2017-04-05 at 14 57 53](https://cloud.githubusercontent.com/assets/3952687/24690459/463e1d28-1a10-11e7-85bd-5d0c9c862429.png)

**Comment by enzyme69** [comment]
This works, but not too elegant, can be monad, but maybe @nortikin got any tips?
![screen shot 2017-04-05 at 15 07 30](https://cloud.githubusercontent.com/assets/3952687/24690668/a9c2b8c6-1a11-11e7-89e2-d6f27ce13037.png)
https://gist.github.com/7247cc29d3e420c6dc4669f8a32a68e7

**Comment by enzyme69** [comment]
![screen shot 2017-04-05 at 15 14 46](https://cloud.githubusercontent.com/assets/3952687/24690802/a042ccc2-1a12-11e7-8f07-a890b74e27a9.png)

Was happily doing Iterate Matrix for Twisting Rope, but it hits 500 maximum Iteration Limit.

I think... in this case of Rope, Blender Array and Curve can be used, as long the rope component is made.

**Comment by enzyme69** [comment]
There must be a better way to chaining, but I think I learn something:
Modularity and Component Part: First / Head, Middle, and Last / Tail

[rope_005_2017_04_05_05_19.zip](https://github.com/nortikin/sverchok/files/895224/rope_005_2017_04_05_05_19.zip)

**Comment by zeffii** [comment]
[step1_2017_04_05_08_33.zip](https://github.com/nortikin/sverchok/files/895578/step1_2017_04_05_08_33.zip)

for the cleanest topology you probably want to pre rotate the strands before they hit the Screw modifier..
![image](https://cloud.githubusercontent.com/assets/619340/24697377/3a4939a8-19ed-11e7-8e2c-b9c8f2a04ea2.png)

**Comment by enzyme69** [comment]
Wow... so many ways to do this. Thanks for the inputs Zeffii, I will study this.

I am actually looking at this earlier:
https://www.youtube.com/watch?v=zodnCU4i6mo

I know we can make this twisting rope just by focusing on line.

Maybe we need "Lofting" node.

**Comment by zeffii** [comment]
to make lofting a reality
- the tanget
- edge direction 
- "twist" (relative to previous edge)  is necessary.

I wonder can be scavange this from Blender C code.. or persuade a dev to add util function to output twist from a Spline..
