### ISSUE TITLE
Matrix for Obj Id Set

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1470]
@Kosvor2 

![image](https://cloud.githubusercontent.com/assets/619340/24696370/8fcd64d4-19e9-11e7-987b-c6ea2a8dd146.png)

some introspection will be needed.. or extra unwrapping

**Comment by zeffii** [comment]
@Kosvor2  i thnk we should detect Matrix socket and convert its content to a a simple array `[matrix, matrix, matrix..... ]`

**Comment by Kosvor2** [comment]
![matrix1](https://cloud.githubusercontent.com/assets/22656834/24699384/39f241c8-1a0d-11e7-9d78-33a918604a84.png)

![matrix2](https://cloud.githubusercontent.com/assets/22656834/24699393/3f3d74b8-1a0d-11e7-9514-1b72b29824d5.png)


Must be node which converts Sverchok matrices and vectors to mathutils variants.
I think it can be useful not only inside of Set node.

**Comment by zeffii** [comment]
matrix_world accepts non Matrix() too..
```
>>> [v[:] for v in obj.matrix_world]
[   (1.0, 0.0, 0.0, 0.29520750045776367), 
    (0.0, 1.0, 0.0, -4.214911937713623),
    (0.0, 0.0, 1.0, -3.813822031021118), 
    (0.0, 0.0, 0.0, 1.0)
]

>>> fm2 = [
    (1.0, 0.0, 0.0, 0.29520750045776367), 
    (0.0, 1.0, 0.0, -4.214911937713623), 
    (0.0, 0.0, 1.0, -1.813822031021118), 
    (0.0, 0.0, 0.0, 1.0)
]
>>> obj.matrix_world = fm2
```

we can extract all Matrix data  from a matrices socket without casting to Matrix

**Comment by zeffii** [comment]
now..depending on how the matrices are stored in a matrix socket , can be two ways.. conceivably..
```
row = (v1, v2, v3, v4)
Matrix = [row, row, row, row]

# non nested
matrices = [Matrix, Matrix, Matrix....]

# nested
matrices = [ [Matrix, Matrix, Matrix....], [Matrix, Matrix, Matrix....], .... ]
```
The nested version isn't something we use much, but i'll make something that can iterate over both types and generate a one level Matrix list (essentially concatenating any nested lists into one massive list)

**Comment by zeffii** [comment]
```python
def non_nested_matrices(data):
    
    matrices = []
    collect_matrix = matrices.extend

    def get_all(data):
        for item in data:
            if isinstance(item, (tuple, list)) and len(item) == 4 and \
            isinstance(item[0], (list, tuple)) and len(item[0]) == 4 and \
            isinstance(item[0][0], (float, int)):

                collect_matrix([item])
            else:
                get_all(item)

    get_all(data)
    return matrices

concatenated_non_nested = non_nested_matrices(k)
print(concatenated_non_nested)
```

**Comment by nortikin** [comment]
by the way, check matrix in mk2

**Comment by Kosvor2** [comment]
#1510
