### ISSUE TITLE
Possibilites to use Modifier Chain inside Sverchok?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1472]
I use Skin Mesher node quite often and sometimes the only gotcha limitation is that this guy is outputtin Object with Skin Modifier and Smooth Modifier chain, and sometimes I append additional modifier like Remesh, and when the frame got updated, the Remesh modifier goes up, which is not good, because I like to have the Modifier Chain Order in tact.

Would be nice to have mechanism that uses Blender Modifier anywhere in Sverchok and chain any type of modifier and bring the data back into Sverchok.

Sverchok In -> Blender Modifier chain -> Sverchok Out

**Comment by zeffii** [comment]
We have discussed why the skin modifier node works that way already. I'll have another look.

However, while the notion of modifier chaining via nodes is natural and appealing - its not clear how to practically implement that

**Comment by zeffii** [comment]
you should make an effort to talk to ton about what things are essential for a 'nodes everything' system.

In sverchok we are limited to using _bmesh.ops_ or _handwritten python routines_, there's no bpy interface to just pick any modifier and use it as an effect on a sverchok mesh or `bm`. (even tho that would be lovely).

Controlling modifiers /adding removing when the stream has multiple objects and potentially multiple modifiers per object, is maybe something for the future. The more i think about it, the less daunting it seems.. but it's not trivial.

**Comment by enzyme69** [comment]
Ok thanks for looking into this. After all going in and out for Modifier is
sufficient with Intermediate object.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
