### ISSUE TITLE
displace along normal

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1473]
i did this set of nodes to displace the vertex of a mesh along the vertex normal. It is pretty simple like in the image:
![displace_along_vert_normal](https://cloud.githubusercontent.com/assets/1275858/24748918/8b6128ee-1ac1-11e7-9001-8a0e3d801aac.png)
after i coded a simplified version with a script using numpy for the mul, add part of the code. this is the scipt:

```python
"""
in verts v d=[[]] n=0
in edges s d=[[]] n=0
in faces s  d=[[]] n=0
in amount s d=[[]] n=0
out final_verts v 
"""

import math
import numpy as np
from sverchok.data_structure import match_long_repeat
from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata

def calc_mesh_normals(vertices, edges, faces):
    bm = bmesh_from_pydata(vertices, edges, faces, normal_update=True)
    vertex_normals = []
    for vertex in bm.verts:
        vertex_normals.append(tuple(vertex.normal))
    bm.free()
    return vertex_normals

result_vertex_normals = []

meshes = match_long_repeat([verts, edges, faces])

for vertices, edges, f in zip(*meshes):
    vertex_normals = calc_mesh_normals(vertices, edges, f)
    result_vertex_normals.append(vertex_normals)

vertices = np.array(verts)
r_v_n = np.array(result_vertex_normals)
a = np.array(amount)
a.shape = int((r_v_n.size)/3), 1
mul = r_v_n * a
add = vertices + mul
final_verts = add.tolist()
```
i don't know if it exist already a node that do this in Sverchok, But do you think we should develop it to a regular node?

**Comment by zeffii** [comment]
I think think we have such a node.. i like it!

**Comment by kalwalt** [comment]
and what is this node? please point me to it, i would compare both.

**Comment by zeffii** [comment]
nono ...refresh the page :/  a typo

**Comment by kalwalt** [comment]
ah ah! github is kidding us!

**Comment by zeffii** [comment]
but do this
```diff
-    vertex_normals = []
-    for vertex in bm.verts:
-        vertex_normals.append(tuple(vertex.normal))

+    vertex_normals = []
+    add_normal = vertex_normals.append
+    for vertex in bm.verts:
+        add_normal(vertex.normal[:])

```

**Comment by kalwalt** [comment]
ok thank you @zeffii

**Comment by zeffii** [comment]
or a one liner
```
+    vertex_normals = [v.normal[:] for v in bm.verts]
```

**Comment by zeffii** [comment]
the one liner list comprehension is going to be faster :)

**Comment by Kosvor2** [comment]
Compare performance with Move node:

![normal_move1](https://cloud.githubusercontent.com/assets/22656834/24751677/f57bd98c-1ae3-11e7-9b1d-d69564837eeb.png)

**Comment by kalwalt** [comment]
thanks @Kosvor2  i will do it.

**Comment by zeffii** [comment]
closing for now, welcome to reopen
