### ISSUE TITLE
SV Terrain Generator and related nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1475]
Trying to make a setup where we simply have 2 surfaces:
- Top = displaced with noise or fractal, etc
- Bottom = flat

![screen shot 2017-04-06 at 23 39 33](https://cloud.githubusercontent.com/assets/3952687/24757394/77340a9c-1b22-11e7-8b80-c73ba5e236ae.png)

GIST:
https://gist.github.com/4eb76af68bf450bfdcb6b4049b17aea7

Maybe this can be further simplified?

**Comment by enzyme69** [comment]
![screen shot 2017-04-06 at 23 42 05](https://cloud.githubusercontent.com/assets/3952687/24757459/ab31ca96-1b22-11e7-9673-6a766a983c90.png)

Maybe original Flat Plane + Displaced Plane with something in between... we don't really have "bridge" node. Could be handy.

**Comment by nortikin** [comment]
ok, maybe there was terrain generator issue, ask for implement this thickness there

**Comment by enzyme69** [comment]
@nortikin Extrude Polygon has New Vertices out, I don't know if we can:
New Vertices => become Mask

Or Bridge node :D I am sure bridge is already possible by connecting vertices and then use cylinder or something. 

If not bridge, it's "lofting" like when we have 2 curves and lofted.

**Comment by enzyme69** [comment]
Actually, a node that flatten and clip would be cool.

**Comment by nortikin** [comment]
lofting UVconnect. For bridge we can use bmesh to select bounds edges, extrude them to corresponding other. but topology... or steal from loop tools somehow...

**Comment by enzyme69** [comment]
Something like this:

Clip and just Cover flat the hole. Actually can do that operation and Fill Hole, but maybe it's heavy.
![screen shot 2017-04-07 at 09 18 25](https://cloud.githubusercontent.com/assets/3952687/24779401/7967b75e-1b73-11e7-9e83-977e9748ea63.png)

**Comment by enzyme69** [comment]
I imagine that @portnov Masking and @Kosvor2 Raycast would somewhat work to "flatten" but for clean way, I guess the Bisect thing and Fillhole.

I supposed this experiment can born 3 nodes:
- Align (might works for Objects and Vertices) would be cool to be able to quickly and easily align bunch of objects and its vertices
- Flatten based on side
- Bridge

**Comment by enzyme69** [comment]
Quick test with Dynamic Paint "vertex weight" masking and project ShrinkWrap.
![screen shot 2017-04-07 at 09 45 12](https://cloud.githubusercontent.com/assets/3952687/24779947/ff9520de-1b76-11e7-8f59-d5f9403a6c33.png)

**Comment by enzyme69** [comment]
![screen shot 2017-04-07 at 09 52 33](https://cloud.githubusercontent.com/assets/3952687/24780089/f67c1c68-1b77-11e7-958f-8cfed7fc00b0.png)

Actually this Fill Hole option was always there inside Bisect? Hmm... but not 100% works like this Donut.

**Comment by zeffii** [comment]
for a donut slice i think you need 2d curve.. because that would generate a polygon with a hole, (and that's not possible)

![image](https://cloud.githubusercontent.com/assets/619340/25074110/ddd345a4-22f4-11e7-9053-3bc283b53081.png)

**Comment by zeffii** [comment]
this issue lost focus.  issues should be limited in scope else they become harder to search later  (as the content of the issue will not match the issue title )
