### ISSUE TITLE
Lofting Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1476]
It would be a custom version of the duplicate along edges node.. because it seems to do exactly what's needed for Lofting.

![image](https://cloud.githubusercontent.com/assets/619340/24759308/641b680c-1ae5-11e7-911e-fb59baa67b02.png)

https://gist.github.com/a2cef031b547c2f57ee0798c24876b0e

**Comment by zeffii** [comment]
There's a slight twist, which you'll notice if you drop the Loft circle down to 4 verts...
![image](https://cloud.githubusercontent.com/assets/619340/24759551/22c0966a-1ae6-11e7-8c9f-398eae96191a.png)

**Comment by zeffii** [comment]
I'm assuming then that to find the least-twist variant of a Loft you need to 
 - first repeat the last instance's axis-twist
 - rotate the newly place mesh around the edge axis, in negative and positive direction
 - funnel down the least twist .. like newtons find square root method../ or linear descent.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24759899/39ebfd1a-1ae7-11e7-8f3a-6b437664c42d.png)

https://gist.github.com/e17460d0e5c63fd2213962406f6d089a

**Comment by portnov** [comment]
Maybe add this "minimize twisting" mode to Duplicate along edges node?

**Comment by zeffii** [comment]
that would be the first step I think.. I'd like to avoid needing to use UVConnect for the lofted extude to generate polygons .. so maybe an extra mode for Duplicate along Edges.. or a proper Loft Node..

**Comment by zeffii** [comment]
hmm... actually, polyline viewer with bevel object works nicely..and the output Object can be converted to mesh  :)
