### ISSUE TITLE
scipy module and Sverchok

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1477]
I think using scipy inside Sverchok especially with scripting is very interesting. Scipy as a lot of features that will be very useful if it would installed as module in blender python. Actually is possible to use the scipy module installing it in the blender python or pointing to where is installed. The point of this issue is make a reference for all the advanced SV users that intend to use the scipy module with Sverchok. I arrive to the scipy because i need some image filters that scipy luckily has in its own. i did this simple test, very simple usage of the `face` scipy image and of the gaussian filter:

![scipy_test](https://cloud.githubusercontent.com/assets/1275858/24770952/1722d2fc-1b0c-11e7-8b95-f0f09e44557c.png)

the script:
```python
"""
in value s d=[[]] n=0
in sigma s d=1 n=2
out val_out s
"""

from scipy import misc, ndimage
import numpy as np


tex = misc.face(gray=True)
print('dim tex',tex.shape)
blurred_tex = ndimage.gaussian_filter(tex, sigma)
rotate_tex = ndimage.rotate(blurred_tex, 180)
val_out = rotate_tex.tolist()

```

as past reference i found that scipy was used in this issue by @zeffii : https://github.com/nortikin/sverchok/issues/946#issuecomment-266572566

We can set here a series of 'how to' , scripts , tips on how install or setup scipy and Sverchok.
More to come of course....

**Comment by zeffii** [comment]
i welcome this :)  i often forget scipy has brilliant content... including image handling (read / write )

**Comment by kalwalt** [comment]
back to this: 
to use scipy i installed it in my system with pip ( i'm on linux) as usual, and then i copy the entire scipy folder into ` /path/to/blender/python/lib/python3.5/site-packages` i don't know if this path could change with different OS but maybe is better, instead to copy the folder (in this way you will not may update the module) to leave scipy in the loaction where was installed and then add this to the header of your script:

```python
import sys
scipy_path = r"/path/to/scipy" #it depend on your OS but just paste the path where is scipy
if not scipy_path in sys.path:
    sys.path.append(scipy_path)    

import scipy
```
in this way you may update scipy.

**Comment by kalwalt** [comment]
#### Circle with scikit
![scikitimage_circle](https://cloud.githubusercontent.com/assets/1275858/25287856/54440706-26c3-11e7-9e8d-cc7be994f3e9.png)
Though scikit is another module it's considered as an extension of `scipy`(a toolbox)
Look at the script, it is very simple and you can do also animations:
```python
"""
in size s d=400 n=2
in center_x s d=100 n=2
in center_y s d=100 n=2
in radius s d=100 n=2
in r s d=1.0 n=2
in g s d=1.0 n=2
in b s d=0.0 n=2
out pixels s
"""

import numpy as np
import sys
scikit_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is scikit
if not scikit_path in sys.path:
    sys.path.append(scikit_path)   
from skimage.draw import (line, polygon, circle,
                          circle_perimeter,
                          ellipse, ellipse_perimeter,
                          bezier_curve)

img = np.zeros((size, size, 3), dtype=np.double)
# fill circle
rr, cc = circle(center_x, center_y, radius, img.shape)
img[rr, cc, :] = (r, g, b)

pixels = [img.tolist()]

```

**Comment by zeffii** [comment]
maybe these snlite threads would have a better home in their own repository .. or wiki pages.

**Comment by enzyme69** [comment]
@kalwalt hmmm.... in latest Sverchok and Script Node Lite, can you still run this script? Mine keeps failing. Got new Mac machine, and trying to do this, but sourcing module using Pineapple 🍍 app. 

I was going to use just a normal Python install, but just found out it's 3.6. Pineapple one is 3.5.

**Comment by zeffii** [comment]
you will need scipy compiled for 3.6, what does the console say?

**Comment by enzyme69** [comment]
something like this:
https://gist.github.com/enzyme69/dc98e6d8921acbe0b7996b3e86c80659

**Comment by enzyme69** [comment]
Blender Python is 3.5. And so I tried to match it with Pineapple one. And from Blender I tried to source the module inside Pineapple.

**Comment by zeffii** [comment]
If Blender is using its own Python , then your scipy must match that version. If you are using a local 3.6 version it will need to use that.

here b2.79 has migrated to Python 3.6
```text
PYTHON INTERACTIVE CONSOLE 3.6.2 (default, Sep 19 2017, 18:07:33) [MSC v.1800 64 bit (AMD64)]

Command History:     Up/Down Arrow
Cursor:              Left/Right Home/End
Remove:              Backspace/Delete
```

**Comment by enzyme69** [comment]
@zeffii looks like the issue is with **scikit** inside Pineapple app package... I use Anaconda and Python 3.5 ... and it works. 

Blender 2.79 --> Python 3.6? Wow, which version am I using.. All good. Cheers again~

**Comment by portnov** [comment]
Well, I got scipy working with my blender installation. Here is an instruction (working on my debian gnu/linux and blender 2.79 from blender.org):

* Download get-pip.py script. I took it from https://bootstrap.pypa.io/get-pip.py, the correct link should be in documentation https://pip.pypa.io/en/stable/installing/ .
* Install pip into your blender's python location:

```
$ /path/to/blender/2.xx/python/bin/python3 /path/to/get-pip.py
```

* Now you can install anything, for example scipy, with pip into your blender's python:

```
$ /path/to/blender/2.xx/python/bin/python3.5m /path/to/blender/2.xx/python/lib/python3.5/site-packages/pip install scipy
```

Note: you may have to adjust paths depending on blender's and python's versions.

After that, you can for example run

```python
from scipy.spatial import Voronoi
```

from blender's python console to check if scipy installed successfully.

Links:
https://blender.stackexchange.com/questions/56011/how-to-use-pip-with-blenders-bundled-python/56013#56013
https://blender.stackexchange.com/questions/5287/using-3rd-party-python-modules

**Comment by kalwalt** [comment]
@portnov nice that you can now work with scipy!
