### ISSUE TITLE
macros

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1481]
this topic is coming up in several places and I want to funnel that into one location, and refer all talk of macros this here.

since we switched over to dynamic menu for shift+a,  we can add 'faux nodes' to the index.md where perhaps something like this _could_ make sense. The syntax isn't decided yet.. and i'm thinking the macro should be defined in a macrofile (of which there could be any number)

```text
## Vector
    GenVectorsNode
    VectorsOutNode
    SvAxisInputNodeMK2
    SvVectorMathNodeMK2
    VertsDelDoublesNode
    SvVectorRewire
    ---
    SvVertSortNode
    VectorDropNode
    macro SvMixInput {'selected_mode': "Vector"}

    # or
    macro <filename> <macro-identifier>

```

**Comment by zeffii** [comment]
The macro would triggerable from Nodeview console, or from Shift+A menu, and should not be limited to simply adding nodes and setting a preset, it could be used for adding a set of nodes / gist / monad..

**Comment by kalwalt** [comment]
In this way we could add nodes that are not in the master branch?

**Comment by zeffii** [comment]
yep, i suppose indeed it could allow registration of external nodes

**Comment by kalwalt** [comment]
> yep, i suppose indeed it could allow registration of external nodes

This could be indeed very, very interesting!

**Comment by zeffii** [comment]
there's several ways we can tackle macros..  we can appropriate some ideas from textmate/sublimetext 's snippets

xml would allow this notation..
```xml

<snippet>
    <description>bpy.props.EnumProperty</description>
    <content>
<![CDATA[mode_options = [(k, k, '', i) for i, k in enumerate(["${1:option1}", ""])]

selected_mode = bpy.props.EnumProperty(
    items=mode_options,
    description="offers....",
    default="${1:option1}"
    #, update=updateNode
)
]]></content>
    <tabTrigger>enum3</tabTrigger>
    <scope>source.python</scope>
</snippet>

``` 
where json is a little picky about multi line content..

**Comment by zeffii** [comment]
but we can have macro template functions, where the macro is so simple that it can be described in a sequence of function calls..
```json
{
    "macros": [{
        "name":  "macro-hulk",
        "operations": "add(<bl_idname>), set(<property_name>, <property_value>)"
     }]
}
```

**Comment by portnov** [comment]
>> In this way we could add nodes that are not in the master branch?

I think at some point we could split our nodes set to "sverchok core" and "sverchok contrib". The last could have maybe more nodes, and updated more frequently, while the first have stable collection of basic high-quality nodes that everyone needs.

**Comment by kalwalt** [comment]
> I think at some point we could split our nodes set to "sverchok core" and "sverchok contrib". The last could have maybe more nodes, and updated more frequently, while the first have stable collection of basic high-quality nodes that everyone needs.

This sounds good to me. 
The macro feature will be in handy also for scripts and monad that the user use often, it will simplify and speed the node creation a lot.

**Comment by nortikin** [comment]
and macros or templates will be in 3d mesh make menu

**Comment by zeffii** [comment]
i still want macros , but instead of mixing the macros in shift+A, I think we really need 

- a set of default macros that can be extended and overridden by the user
- macros to show up in a menu and a search tool
- macro can be a string that is a key to an executable code, or a function call (with easy to compose arguments)
