### ISSUE TITLE
Error: failure in process between frozen area Objects in mk3

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1482]
![screen shot 2017-04-08 at 21 29 31](https://cloud.githubusercontent.com/assets/3952687/24828551/d32d50e8-1ca2-11e7-83b5-c2c2990ba2fb.png)
[lightImport_DEMO_001_2017_04_08_11_29.zip](https://github.com/nortikin/sverchok/files/907409/lightImport_DEMO_001_2017_04_08_11_29.zip)

I don't know what the error message exactly mean, but I am getting this quite a lot and noticing it very often recently.

**Comment by zeffii** [comment]
SvNodeDataError means you meed to look up a few lines... I think the cause is something that happens in `obj_remove_mk2.py`

**Comment by zeffii** [comment]
could very well be recent changes in Blender.. i havent updated in about 3 weeks :)

**Comment by zeffii** [comment]
OK, lights aren't understood by `objects in` node

**Comment by zeffii** [comment]
will fix asap, thanks for the report

**Comment by zeffii** [comment]
there's this line in objects_mk3.py
```python
if obj.type == 'EMPTY':
   ...
```
it should be 

```python
if obj.type in {'EMPTY', 'LAMP'}:
   ...
```

**Comment by zeffii** [comment]
these are all the `object.type`s 

* ‘MESH’, ‘CURVE’, ‘SURFACE’, ‘META’, ‘FONT’, ‘ARMATURE’, 
* ‘LATTICE’, 
* ‘EMPTY’, ‘CAMERA’, ‘LAMP’, 

 it doesn't make a lot of sense to get the mesh of a META object.. or LATTICE..

for now i'll make it 
```python
if obj.type in {‘EMPTY’, ‘CAMERA’, ‘LAMP’ }
   ...
```

**Comment by zeffii** [comment]
done.. https://github.com/nortikin/sverchok/pull/1483
