### ISSUE TITLE
Strawberry Pineapple Topology

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1484]
Is there some kind of ways in Sverchok to do List Mixing?

Kind of like if we have List A and then got List B, I want to List B minus List A, to get List C.

Maybe I started with typical grid like Cylinder, and then somewhat get the kris kros -ing edges, and I want to get rid of the original grid and get the diagonal edges only.

![screen shot 2017-04-08 at 22 26 54](https://cloud.githubusercontent.com/assets/3952687/24828879/97b77c52-1caa-11e7-91ee-6d4447d644c7.png)
![screen shot 2017-04-08 at 22 26 28](https://cloud.githubusercontent.com/assets/3952687/24828881/980df33e-1caa-11e7-9401-6ce2df1f73cc.png)
![screen shot 2017-04-08 at 22 26 18](https://cloud.githubusercontent.com/assets/3952687/24828880/980c6398-1caa-11e7-898e-548222dddfac.png)

There must be a way.

**Comment by zeffii** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/619340/24828982/8a3fd556-1c69-11e7-9a9d-de630871af95.png)

**Comment by enzyme69** [comment]
![screen shot 2017-04-08 at 22 48 46](https://cloud.githubusercontent.com/assets/3952687/24829033/a0f9b6a6-1cad-11e7-971d-5e0f6d6b1be4.png)

https://gist.github.com/71b0aa625d6f932d21ab0f8917e74124

@zeffii  Thanks! Don't know what I was thinking but there might be few nodes missing to do it procedurally. But I will rethink my method.
