### ISSUE TITLE
Creating node class props on the fly

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1486]
Is it possible to create class props on the fly ? For the situation when I can switch the node type and have to replace the sockets, I assume I need to have properties already crated in the class to link to the sockets (e.g input.prop_name = “property_name”). Normally I would have to create all the props for all the types the node handles and then on type switch I can connect new sockets with the props already defined.. My question is would it be possible to NOT define the props in the class and add them later when switching sockets ?

**Comment by zeffii** [comment]
Not possible with bpy.props ,  while annoying it hasnt impeded us.. if anything it has strengthened our abilty to use dynamic coding concepts.

There are things called id-property but they dont allow min max .. and that makes them less ideal to warrant their usage as socket property

**Comment by zeffii** [comment]
>  Normally I would have to create all the props for all the types the node handles and then on type switch I can connect new sockets with the props already defined..

if you name your enums / their members and the properties coherently you can use `getattr()` and `setattr()` to greatly simplify the code.

**Comment by zeffii** [comment]
it is possible to create and register properties.. to the Node's Class.. but the mechanics is so much more complicated and error prone, that i'm not even going to entertain showing how to do that.

**Comment by zeffii** [comment]
an alternative is have a neat Property factory function, so the class body looks more organized, and you can generate many properties with little code (The downside is that there's a little bit of indirection if you aren't expecting properties to be generated by a function)

- https://github.com/nortikin/sverchok/blob/master/nodes/viz/viewer_indices.py#L209-L219

**Comment by zeffii** [comment]
something like...
```python
    # INPUT sockets settings

    def make_prop(ptype, pname, def=None):
        
        name = ptype + " " + pname
        description = "Mix " + ptype + pname
        params = dict(name=name, description=description, default=def, update=updateNode)

        if ptype == 'Float':
            return FloatProperty(**params)
        elif ptype == 'Int':
            return IntProperty(**params)
        elif ptype == 'Vector':
            return FloatVectorProperty(**params)
        elif ptype.startswith('Color'):
            ... etc
            csize = int(ptype[5:])
            return FloatVectorProperty(size=csize, subtype='COLOR', othersettings, **params)
        elif ptype == 'Quaternion':
            return FloatVectorProperty(size=4. subtype='QUATERNION', **params)


    value_float_a = make_prop("Float", "A", def=0.0) 
    value_float_b = make_prop("Float", "B", def=1.0) 

    value_int_a = make_prop("Int", "A", def=0) 
    value_int_b = make_prop("Int", "B", def=1) 

    value_vector_a = make_prop("Vector", "A", def=(0,0,0))
    value_vector_b = make_prop("Vector", "B", def=(0,0,0))

    value_color3_a = make_prop("Color3", "A", def=(0,0,0))
    value_color3_b = make_prop("Color3", "B", def=(1,1,1))
    value_color4_a = make_prop("Color4", "A", def=(0,0,0,1))
    value_color4_b = make_prop("Color4", "B", def=(1,1,1,1))

    value_quaternion_a = make_prop("Quaternion", "a", def=(0,0,0,1))
    value_quaternion_b = make_prop("Quaternion", "B", def=(1,1,1,1))
```

**Comment by zeffii** [comment]
and because you can do stuff like 
```python
>>> getattr(bpy.props, 'FloatProperty')(default=4)
(<built-in function FloatProperty>, {'default': 4})
```
this (untested)
```python
    # INPUT sockets settings

    def make_prop(ptype, pname, default=None):
        """ Property Factory """
        name = ptype + " " + pname
        description = "Mix " + ptype + pname
        params = dict(name=name, description=description, default=default, update=updateNode)

        kind = {
            'Float': ('Float', ),
            'Int': ('Int', ),
            'Vector': ('FloatVector', ),
            'Color3': ('FloatVector', dict(size=3, subtype='COLOR', min=0, max=1)),
            'Color4': ('FloatVector', dict(size=4, subtype='COLOR', min=0, max=1)),
            'Quaternion': ('FloatVector', dict(size=4, subtype='QUATERNION'))
        }.get(ptype)

        final_params = params.update(kind[1]) if len(kind) == 2 else params
        return getattr(bpy.props, kind[0] + 'Property')(**final_params)

    int_a = make_prop("Int", "A", default=0) 
    int_b = make_prop("Int", "B", default=1) 
    float_a = make_prop("Float", "A", default=0.0) 
    float_b = make_prop("Float", "B", default=1.0) 
    vector_a = make_prop("Vector", "A", default=(0,0,0))
    vector_b = make_prop("Vector", "B", default=(0,0,0))
    color3_a = make_prop("Color3", "A", default=(0,0,0))
    color3_b = make_prop("Color3", "B", default=(1,1,1))
    color4_a = make_prop("Color4", "A", default=(0,0,0,1))
    color4_b = make_prop("Color4", "B", default=(1,1,1,1))
    quaternion_a = make_prop("Quaternion", "A", default=(0,0,0,1))
    quaternion_b = make_prop("Quaternion", "B", default=(1,1,1,1))
```

**Comment by DolphinDream** [comment]
So I take all the class attributes have to be created in the “constructor" of the class ? i.e. they can’t be created later at runtime based on user input ? (unless you do some unregistering/registering tricks) ?

**Comment by DolphinDream** [comment]
Any reason why the need for a Color3 and a Color4? Can’t all colors be defined as 4 and let the user use or not the 4th (alpha) channel ? Perhaps the node could sanitize the inputs (fi given as a 3 channel) to a 4 channel color and always work with color 4 internally. In that respect I didn’t quite appreciate the color in/out “use alpha” setting. I would just use alpha always and keep things simple (alpha=1 if alpha is not needed).

**Comment by Kosvor2** [comment]
Blender often wants RGB (vertex colors, for example) instead of RGBA.

**Comment by DolphinDream** [comment]
@Kosvor can you give me an example ? if you’re talking about setting color attributes to some other blender objects perhaps the “set attributes” node could do the dropping of the alpha channel as part of sanitizing the color input ?

**Comment by DolphinDream** [comment]
I’m trying to set an attribute via setattr in a callback from changing the enumProperty but for some reason the attribute does not stay defined. The update_type will print the valueA after updating the props, however it seems that the valueA will not exist next time update_type/update_props is called. Any ideas why not ? Does SV or blender do some sort of attribute clearing ? (only the attributes defined within the class itself persist).

```python
    def update_type(self, context):
          self.update_props()
          print(“valueA = “, self.valueA)

    def update_props(self):
        if hasattr(self, "valueA"):
            print("Deleting valueA prop")
            delattr(self, "valueA")
        else:
            print("valueA prop not found. Create one.")
            setattr(self, “valueA", 10)
```

**Comment by zeffii** [comment]
Just define all needed props in advance, in the body of the class. Either explicitly using 

some_prop_name = FloatProperty(....)

Or
some_prop_name = make_prop(...)

Those are the only useful ways at present.

**Comment by Kosvor2** [comment]
![rgb12](https://cloud.githubusercontent.com/assets/22656834/24852307/6d46ceb8-1df0-11e7-841e-7236b202dc2c.png)

**Comment by zeffii** [comment]
> it seems that the valueA will not exist next time update_type/update_props is called. Any ideas why not ? Does SV or blender do some sort of attribute clearing ? 

I think it's a matter of the `self.bl_rna.properties`  being a collection, and I'm fairly certain that's static after the it / the node is registered.

**Comment by DolphinDream** [comment]
@Kosvor so the VertexColorNew node could simply feed RBG into the SvCol attribute of the given object regardless of what it receives as an input. If this node doesn’t do that and if it doesn’t have a input sanitizer to covert from RGB to RGBA it will break (i assume) if you plug in a RGBA input.

**Comment by Kosvor2** [comment]
This node must work with thousands of verts at the same time- IMHO its not a gud idea to sanitize them all from (rgba) to (rgb) on each update.

**Comment by zeffii** [comment]
should be implemented in numpy really then :) @Kosvor2

**Comment by DolphinDream** [comment]
@zeffii sarcasm noted 👍

**Comment by zeffii** [comment]
Thats not sarcasm, but fact

**Comment by DolphinDream** [comment]
Oh. I thought numpy was a bit overkill for color input sanitizing.

**Comment by nortikin** [comment]
All have to be numpy

**Comment by zeffii** [comment]
kind of off topic now. 

unless you find a really nice, clean, sane way to dynamically add/pop props from a node, let's close this.

**Comment by DolphinDream** [comment]
If i have a property defined in the class:

```python
valueA = IntProperty(name=“Some Name”, default=1) 
```
and later I want to check the attribute valueA’s name (“Some Name”) how do i do that ?

it seems that the self.valueA (or getattr(self, ‘valueA’) gives me the value of the valueA not the property object (which is what i need so i can query its name).

Btw, is there a good place where I can read more in depth what is going on underneath the hood with these properties, class registration etc. I feel blender is doing a bunch of shenanigans under the hood that are not intuitive from the point of view of plain python.

**Comment by zeffii** [comment]
You are right, There's a lot of hoisting going on in the pynode API, There's not much documentation of pynodes even on the blender.org API docs.  

Please show in what context you need to find the name , where it can not be inferred by mode

**Comment by DolphinDream** [comment]
I can infer it from type, np, though it will be a replica of the property 
 name.  I wished I could just reference the name defined in one place rather than define it in multiple places (or infer it). For now I'll just infer it.

**Comment by zeffii** [comment]
also..there's bl_rna.properties...
```python
>>> nodes['Polyline Viewer MK1'].resolution
3

>>> nodes['Polyline Viewer MK1'].bl_rna.properties['resolution']
<bpy_struct, IntProperty("resolution")>

>>> nodes['Polyline Viewer MK1'].bl_rna.properties['resolution'].name
'resolution'

>>> 
```

**Comment by DolphinDream** [comment]
On the same topic.. if i want to create an array of props for input sockets (e.g. angle[6]) how do I set the sockets using a prop name for an array of properties? 

If I initialize the props in the class like this:

```python
axisNames = list(map("".join, combinations(list("XYZW"), 2)))
angles = []
for i in range(len(axisNames)):
    angles[i] = FloatProperty(
        name=axisNames[i], description="Angle " + str(i),
        default=0.0, update=update_angle)
```

then how do I set the sockets up ? Would _something_ like this work?

```python
def sv_init(self, context):
    for i in range(6):
        self.inputs.new("StringsSocket", "A" + str(i)).prop_name = "angles["+str(i)+"]"
```
   
and then access it as

```python
def process():
    input_a = [inputs[“A”+str(i)].sv_get()[0] for i in range(6)]
```
