### ISSUE TITLE
Odd: Mattrix Apply appears twice

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1487]
I spot a bug:

![screen shot 2017-04-09 at 11 19 27](https://cloud.githubusercontent.com/assets/3952687/24833768/731af9b6-1d16-11e7-9e0e-649ff5d89294.png)

**Comment by zeffii** [comment]
One should be called  " matrix apply (  verts only. ) "

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/5b7fa324d722de7a178b6aa6763a8cf10e52cdf6

**Comment by nortikin** [comment]
better move to old nodes

**Comment by zeffii** [comment]
or give Matrix Apply node an MK3  . and add a "More" button to switch between more / less
```text
            [ Matrix Apply        ]
            -----------------------
            |                   v o
            |                     |
  bool ---> |  join [ ]  [more]   |
            o v                   |
            o m                   |
            | ____________________|


[ Matrix Apply        ]
-----------------------
|                   v o
|                   e o
|                   f o
|                     |
|  join [ ]  [less]   |   <---enum
o v                   |
o e                   | 
o f                   |
o m                   |
| ____________________|


```

**Comment by portnov** [comment]
More MkN nodes for god of nodes?
:)

**Comment by enzyme69** [comment]
I like Apply Matrix as mesh node, it was useful for me. Actually a good
shortcut.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
@portnov god of nodes, yes 😂

**Comment by zeffii** [comment]
ok. MK3 it is. 🔋
