### ISSUE TITLE
When A Node takes a long time to complete processing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1488]
Sometimes certain processing caused a hang on Blender. Such as this one:

Try using Subdivided Suzanne and use it as Input:
https://gist.github.com/c36cddfa5de294605d1ba76efb6c66df

Default Suzanne at its resolution can be processed without issue. But I cannot process Suzanne with 1 subdivision applied.

I wonder if this is just my computer?

But I wonder in case of something not processing, maybe we can halt Sverchok processing, somewhat?

**Comment by zeffii** [comment]
To be clear you should mention that you are talking about additional nodes.. not just the import of a higher resolution mesh.

Suzanne with subdiv -> objects in (post modifiers) -> vdmk2   should be reasonably fast 

if subdiv is not super high.

The cylinder you use to start is 72 verts / 64 polygons , this produces at the end of the _visible_ chain 1088 verts and 680 polygons. This new total does not include the viewers that you have turned off (but the processing will still happen in the nodes leading up to the output node...  so something to be aware of )  

> **So, there's about a 10 fold increase in geometry when considering the cylinder.** 

The suzanne starts with 507 verts and 500 faces,   but ends up with a final   8000 verts and 5000 polygons..

if you subdivide Suzanne 2 times you get about 7000 verts and almost 8000 faces... , calculate how many final verts and faces do you think that would produce.  A lot.

The real processing happens however.. in `extrude separate`.

![image](https://cloud.githubusercontent.com/assets/619340/24835470/a1adc91a-1d03-11e7-8ea7-34f1f3fb69c7.png)

these are all tools that have been around for ages to help us track down where the slowness is..

##### print debug timings
![image](https://cloud.githubusercontent.com/assets/619340/24835484/cff65684-1d03-11e7-9f31-81f57acda5b1.png)

##### heatmap
![image](https://cloud.githubusercontent.com/assets/619340/24835479/bb3e1ec0-1d03-11e7-91e2-ff3662b66cdb.png)

**Comment by zeffii** [comment]
@enzyme69  your approach should be .. 

- try on something small,  
- check where the slowest node. is. , 
- gradually increase input geometry size  (not doubling... unless the next step suggests a linear correlation to input...)
- track input vert/face count vs how much slower the slowest node gets


In this case i think maybe extrude separate might be able to do it faster..

**Comment by zeffii** [comment]
I think using an "Inset Special"  node might be just as good, as replacement for the "Extrude Separate". it's also currently quite a bit faster

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24835910/c6abca18-1d0e-11e7-839b-afccc993d868.png)
