### ISSUE TITLE
Plugging Color to Lamp is making thing slower by 10 times

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1490]
I am testing this setup, for unknown reason Object ID to modify prop data.color is making the animation slower.

![screen shot 2017-04-09 at 19 29 04](https://cloud.githubusercontent.com/assets/3952687/24836272/f5d6ea2e-1d5a-11e7-8f1f-0118d4f63108.png)
[object_instancer_combo_001_2017_04_09_09_28.zip](https://github.com/nortikin/sverchok/files/908095/object_instancer_combo_001_2017_04_09_09_28.zip)

I might make live noding video about this.

**Comment by zeffii** [comment]
the good thing is that the update doesn't take as long as it does to render the frame.. so at the moment it doesn't facilitate realtime animation for openGL with this particular configuration.

Not sure why the update should be so slow, but i think there's a lot of unnecessary updating ...

seems like you should be using animation nodes for this kind of stuff... it is called "Animation Nodes" for a reason.

**Comment by zeffii** [comment]
if you unplug the color socket things speed up a lot..

**Comment by zeffii** [comment]
the question  then narrows down to.. " why is the color property so slow to update "

**Comment by zeffii** [comment]
like this... is even ultra slow

![image](https://cloud.githubusercontent.com/assets/619340/24836466/bf16ddd4-1d1c-11e7-8850-cfca2a7328fc.png)

**Comment by enzyme69** [comment]
It's a mystery. But for now I can just noted that accessing props like
data.* for Lamp slows thing down. Maybe AN has something to do with it, but
I will check.

Currently using AN for Duplicating and Instancing.

**Comment by zeffii** [comment]
this is also ridiculously slow.

![image](https://cloud.githubusercontent.com/assets/619340/24836527/a561b600-1d1e-11e7-9b43-dcbbc92c8f8e.png)

AN has nothing to do with this, but I think it gets around the color update slowness, by keyframing the values instead.

**Comment by zeffii** [comment]
maybe it's worth trying to use vertex_color layer on a plane, and have an emission material..

**Comment by enzyme69** [comment]
Spotlight and 3D View has total of 15 max on my computer anyway...

So Cycles and Vertex Color Emission is a way to go.

![screen shot 2017-04-09 at 21 49 29](https://cloud.githubusercontent.com/assets/3952687/24837052/72c026dc-1d6e-11e7-8f4f-180fa747e21a.png)
[proc_emission_003_2017_04_09_11_49.zip](https://github.com/nortikin/sverchok/files/908166/proc_emission_003_2017_04_09_11_49.zip)

Yeah, but anyhow, maybe it's Blender and data changing Lamp props that causing slowness.

Thanks for checking!
