### ISSUE TITLE
Create new stable release, and after that remove all old nodes from master.

### ISSUE THREAD

**Issue by Kosvor2** [nortikin/sverchok#1493]
Such an idea.

**Comment by zeffii** [comment]
i agree :)

**Comment by zeffii** [comment]
(but maybe not remove all old generators... especially not if we move Line to old.. )

**Comment by Kosvor2** [comment]
Well if someone need old Line / Plane nodes, they can just use one of the older releases: https://github.com/nortikin/sverchok/releases

![oldvsnew](https://cloud.githubusercontent.com/assets/22656834/24858896/a07afb80-1e07-11e7-80f4-cdec2fab8dd2.png)

**Comment by zeffii** [comment]
`get / set   property`  nodes are not replaced by Obj Id Set..

**Comment by Kosvor2** [comment]
Ok, `get / set property` can stay.

![vec_inter](https://cloud.githubusercontent.com/assets/22656834/24859802/9eb66470-1e0b-11e7-8664-a3dd268dc3c5.png)

**Comment by zeffii** [comment]
we could store old nodes in `sverchok/datafiles/oldnodes`, and have an operator to download them all or when needed..

**Comment by zeffii** [comment]
i was thinking maybe a `sverchok_old_nodes` repository... but i think i'll let someone else deal with that.

**Comment by portnov** [comment]
Btw, about Interpolation: for some reason mk3 does not have tU and tV, which seem to be usable feature. Why so?

**Comment by zeffii** [comment]
@portnov  yeah `mk2` and `mk3` are different and indeed have usefull features individually. I am not sure why they aren't one node.

**Comment by portnov** [comment]
See #1500.

**Comment by Kosvor2** [comment]
There is draft release: https://github.com/nortikin/sverchok/releases/tag/untagged-371271f1754dbd5c1d7c

@zeffii If you think the master is stable enough, you can publish it right now and close this topic.

**Comment by zeffii** [comment]
sverchok is always stable :)    hahaha :)   nothing is more broken than before.

**Comment by zeffii** [comment]
published!
