### ISSUE TITLE
Intersecting Points and Pipe

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1497]
Not sure exactly my question is but we have 5 primitives Pipe. I was starring at these guys.

![screen shot 2017-04-11 at 11 06 45](https://cloud.githubusercontent.com/assets/3952687/24888461/17da744a-1ea7-11e7-9ab6-a809d87cf873.png)

Supposedly, it must be possible to create setup where we have bunch of intersecting lines (maybe drawn using grease pencil, or maybe a more complex pipe design) and then we could replace every intersecting points with Skinned Mesh, and every straight lines with pipe or tube or cylinder.

**Comment by zeffii** [comment]
Definitely not a trivial problem, even if the input mesh is 2d planar.

**Comment by zeffii** [comment]
You should ask this on Blender Stackexchange as a general question about generating nicely non-self intersecting polygons from such input,, i'm sure you'll get some smart answers.

![image](https://cloud.githubusercontent.com/assets/619340/24906078/a710d762-1eb6-11e7-992f-2589532ed8d2.png)

The problem geometry is going to be where the intersection is not planar .. or not perpendicular to a plane. If you want relatively clean geometry with arbitrary input, then you are looking for quite specialized (maybe even NURBS ) tools.

**Comment by zeffii** [comment]
@enzyme69  i don't think what you want to do with look great (using skinmod for intersections amd curve bevel object for straight parts )

**Comment by enzyme69** [comment]
Thanks for thoughtful answers. Yes, probably this is kind of tasks needing proper thinking and not just freeform thing. 

Will try stackexchange.

**Comment by enzyme69** [comment]
Would be interesting if in the future modeling this kind of thing become like Chinese / Japanese / Korean writing.

https://blender.stackexchange.com/questions/42591/how-to-aproach-the-modeling-of-duct-work-piping-wiring/42594#42594

![screen shot 2017-04-18 at 20 40 43](https://cloud.githubusercontent.com/assets/3952687/25126943/51c10c0c-2477-11e7-8192-19e8f172c52f.png)

Just for reference.

I don't know if NEURO can do this @nortikin  But that's for future.
