### ISSUE TITLE
Procedural Teapot, how can this be improved

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1498]
The GIST works after I deleted the Object ID Selector and creating it again. It was complaining about json not serializeable. Sometimes it works too.

GIST:
https://gist.github.com/7c25737784423f9b9b1d6b65bd70fe73

BLEND:
[teapot_003_2017_04_11_01_39.zip](https://github.com/nortikin/sverchok/files/911867/teapot_003_2017_04_11_01_39.zip)

The **Body** and **Lid** part of the Teapot is straight forward. Maybe the only part I think can improve it is that when we are able to "add points" and then formula the strokes maybe with Mesh Formula.

Anyhow, for the teapot **Handle** and **Spout** Part, I am using Pipe, it was quite ok, but I think if we have "Loft" node it might be better control.

Other than that, I think it's pretty good example. I enjoy making this one. The Grease Pencil bits is actually quite cool as well.

The last bit, I am trying to merge all 4 parts of teapot, that List Join is ok, but imagine if we have 10-100 parts, maybe this "merge everything as single mesh" can be improved.

4 GP Strokes = A Teapot is impossible without Sverchok.

Thank you.

**Comment by enzyme69** [comment]
![screen shot 2017-04-11 at 11 39 44](https://cloud.githubusercontent.com/assets/3952687/24889264/54a79e52-1eac-11e7-93b3-a5554fb2bd52.png)

**Comment by zeffii** [comment]
The `object ID selector` won't have anything to select when exporting as json (json/gist doesn't store the scene's grease pencil data... so that would not ideal anyway)

[teapot_003_2017_04_11_08_40.zip](https://github.com/nortikin/sverchok/files/912591/teapot_003_2017_04_11_08_40.zip)

I think a Loft node is not needed for this. When you need to loft a Planar shape (like all Z are the same.. or all X.. or Y are the same ) then using `Duplicate along Edges` node.  See the exame in the recent "Loft node" thread

**Comment by zeffii** [comment]
> but imagine if we have 10-100 parts, maybe this "merge everything as single mesh" can be improved.

we could have a 'bake selected viewer nodes, and merge resulting meshes'  operator.

**Comment by nortikin** [comment]
Mesh join mk2 with multysocket

**Comment by zeffii** [comment]
I think we could make something that spits out the profile of the intersection between two meshes
![image](https://cloud.githubusercontent.com/assets/619340/24977385/328031a0-1fcd-11e7-95ed-a486f1cc0680.png)

**Comment by enzyme69** [comment]
Also, maybe time to have Resample Curves MK1.

**Comment by enzyme69** [comment]
That intersection lines between objects == nice. Actually starting to become like realtime Freestyle stuff. More or less.

**Comment by zeffii** [comment]
http://airplanes3d.net/scripts-253_e.xml

**Comment by zeffii** [comment]
but I don't think we'll be using any of the code in that add-on.
