### ISSUE TITLE
DP modifier doesn't work on BMesh Viewer live mesh

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1499]
[noripple_001_2017_04_11_06_45.zip](https://github.com/nortikin/sverchok/files/912319/noripple_001_2017_04_11_06_45.zip)
![screen shot 2017-04-11 at 16 45 02](https://cloud.githubusercontent.com/assets/3952687/24896001/5728ac0a-1ed6-11e7-8f28-81e5a5473583.png)

This is something that I found by accident.

I am using Plane MK2 and BMesh Viewer out and turn this mesh output into Dynamic Paint Canvas. I set this Canvas as Wave for simulation.

However, the strange thing is: the mesh above does not ripple.

I tested using normal Grid Mesh in Blender and do the exact procedure above, and the Grid actually ripples.

I am wonder what causes the mesh from Sverchok to not simulating?

**Comment by enzyme69** [comment]
I suspect: some kind of broken linking.

If I re-link the modifier by relinking the DP Modifier, it seems to work.

But not working as long the Sverchok node is still active whether it is updating or not updating.

**Comment by zeffii** [comment]
what do you mean by "linking" and "relinking" the modifier.

**Comment by zeffii** [comment]
once you turn off _update_ on the node it has no more interaction with the objects it created.

I should stress that bmesh view doesn't do anything special for any modifiers, i can imagine scenarios where it would be great.. but some modifiers (like skin modifier) get broken once we update the mesh. I suspect dynamic paint modifier is also on the list of modifiers that would require special attention in order for their use.

**Comment by zeffii** [comment]
but remember, i had to make a whole Node dedicated to skin modifier to get that working in a 'faux' dynamic way.

**Comment by zeffii** [comment]
I have no intention of dealing directly with this at this time.

I might look into copying modifiers and moving them to the correct position before and after update, but that's all for now.

**Comment by enzyme69** [comment]
Thanks architect Zeffii.

**Comment by nortikin** [comment]
Turn on the fixed verts count in prps of node bmesh

**Comment by enzyme69** [comment]
@nortikin hey that works! 
![bug_fixed_vertex2](https://cloud.githubusercontent.com/assets/3952687/24986484/cee4c1e4-203d-11e7-8ce5-6285896c1fdc.gif)
