### ISSUE TITLE
Matrix Apply MK3

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1501]
maybe i'll implement 3 modes in draw buttons_ext
- Vector Conversion
- Numpy Conversion (to and from)
- Python handwritten matrix*list(matrix)

Naturally all modes should arrive at the same result (or within precision limits).  Tho for convenience i'll shuffle up the ui to go unconventional

```text
            [ Matrix Apply        ]
            -----------------------
            |                   v o
            |                     |
  bool ---> |  join [ ]  [more]   |
            o m                   |
            o v                   |
            | ____________________|


[ Matrix Apply        ]
-----------------------
|                   v o
|                   e o
|                   f o
|                     |
|  join [ ]  [less]   |   <---enum
o m                   |
o v                   |
o e                   | 
o f                   |
| ____________________|

```

**Comment by zeffii** [comment]
and give the matrix in a default Indentity matrix when not connected.

**Comment by nortikin** [comment]
why matrix slot in up?
when moving nodes it autolink connections, so vertices used first if all have to be up

**Comment by zeffii** [comment]
oh? ok.. will use conventional order then.
