### ISSUE TITLE
replace nodeview Add menu

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1502]
```python
bpy.types.NODE_MT_add.remove(bpy.types.NODE_MT_add.draw)  # <--- is the default... byebye
bpy.types.NODE_MT_add.append(bpy.types.NODEVIEW_MT_Dynamic_Menu.draw)

```

![uhhhgif](https://cloud.githubusercontent.com/assets/619340/24951052/61f6f112-1f73-11e7-8189-42fce80dab61.gif)

**Comment by zeffii** [comment]
the custom icons will appear only if they have been loaded once by the shift+A menu. i can live with that.

**Comment by zeffii** [comment]
i have a feeling this would interfere with other node systems..

**Comment by nortikin** [comment]
can be checking for tree type? or not a case?

**Comment by zeffii** [comment]
we might have to implement our own `nodeitems_utils`, most of it already exists in some for, or another..

**Comment by zeffii** [comment]
we can do .. 
```
from nodeitems_utils import _node_categories
 _node_categories.pop("SVERCHOK")
```

the downside is that you get two `search` entries (like i've seen in screenshots of Animation nodes menu... uuugllyyyeeee)

**Comment by zeffii** [comment]
...orr... if I can make the search item _context dependent_ , then it won't appear double in NODE_items_add, but will appear ofcourse once in Shift+A menu.

**Comment by zeffii** [comment]
```python
        if self.bl_idname == 'NODEVIEW_MT_Dynamic_Menu'
            s = layout.operator("node.add_search", text="Search", icon='OUTLINER_DATA_FONT')
            s.use_transform = True
```

i think the only impedement then is that when `_node_categories` are popped, the `F8` unregister step no longer automatically unregisters the nodes. So when popped, I could popupalate another dict with the result, and run through that dict upon a `def unregiser()`.

**Comment by zeffii** [comment]
i'll do this in a separate PR.. :) test it anyway.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1504/files

works as expected

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1504

done
