### ISSUE TITLE
Falloff and Selection by Order Index ala AN

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1503]
I was having a peek into Cython Branch of Animation Nodes (AN) and looking at Jacques tutorial:
https://www.youtube.com/watch?v=s4wcSW-e_Pg

Currently I am trying to understand what is happening with the **falloff** thing and trying to translate this concept into Sverchok.

I think Falloff implementation in Sverchok would be quite nice. 

Also, around 3:06 there is this neat "Selection Order Index" maybe something that is probably can be implemented into Sverchok at some point?

Thanks!

**Comment by zeffii** [comment]
[scale_individual_2017_04_12_09_43.zip](https://github.com/nortikin/sverchok/files/916088/scale_individual_2017_04_12_09_43.zip)

i'm pretty sure you can do this already with the current node set,  and a little bit of math.

**Comment by zeffii** [comment]
translating 1 number ( a range between 0 and 1 )  to 4 sets of numbers that each generate their own linear 0...1 line  with an offset in time (0....1)
![image](https://cloud.githubusercontent.com/assets/619340/24952021/882298e8-1f76-11e7-9f52-9bfb09e6fc26.png)

**Comment by zeffii** [comment]
[scale_individual_2017_04_12_10_09.zip](https://github.com/nortikin/sverchok/files/916152/scale_individual_2017_04_12_10_09.zip)

![image](https://cloud.githubusercontent.com/assets/619340/24952789/179fb440-1f79-11e7-9f06-1b49a73c04b8.png)

**Comment by enzyme69** [comment]
Yes, thanks for example Zeffii! I think I tried with Polygon too at some point.

I think what can be added is:
- Falloff thing --> not trivial --> for now I am happy with Dynamic Paint.
- Index Sorter based on Selection Order (components or objects ID) --> this can be interesting

**Comment by zeffii** [comment]
and 'offset evaluate' snlite is something you should try to make.

**Comment by enzyme69** [comment]
@zeffii I make? :D Ok~

**Comment by zeffii** [comment]
making your own solution is essential on the road to node-blackbelt.

**Comment by enzyme69** [comment]
The Easing function....It took me a while to map and remap to get the result I was expecting 💃  Finally I understand. 

[scale_individual1_2017_04_12_12_05.zip](https://github.com/nortikin/sverchok/files/916398/scale_individual1_2017_04_12_12_05.zip)
![screen shot 2017-04-12 at 22 05 16](https://cloud.githubusercontent.com/assets/3952687/24956700/338349bc-1fcc-11e7-9860-0cb2bdd1fd1f.png)
![sv_matrix_offset_001](https://cloud.githubusercontent.com/assets/3952687/24956701/33839e4e-1fcc-11e7-97fe-d2a3ad5ab7e2.gif)

**Comment by enzyme69** [comment]
![screen shot 2017-04-12 at 22 11 06](https://cloud.githubusercontent.com/assets/3952687/24956858/f443427e-1fcc-11e7-916e-843298bd791e.png)

Eventhough sorting is not falloff, this can be for "By Order of Selection".

**Comment by zeffii** [comment]
i think if the objects as given an ID property, you could sort by it.

**Comment by zeffii** [comment]
or sort object objects based on `.location`'s proximity to an empty's `.location`

**Comment by enzyme69** [comment]
[scale_individual3_2017_04_12_12_16.zip](https://github.com/nortikin/sverchok/files/916423/scale_individual3_2017_04_12_12_16.zip)

Somewhat this sorting based on Location is failing.

**Comment by enzyme69** [comment]
@zeffii  I remember having related question with "distance" or proximity and was "confused".

**Comment by enzyme69** [comment]
Aahh... I forgot to adjust the total numbers.

**Comment by enzyme69** [comment]
[scale_individual3_2017_04_12_12_25.zip](https://github.com/nortikin/sverchok/files/916441/scale_individual3_2017_04_12_12_25.zip)
![sv_matrix_offset_003](https://cloud.githubusercontent.com/assets/3952687/24957372/edb2f16e-1fce-11e7-956a-6290bafb138e.gif)

I see now. Sorting is sort of working, but not quite as "falloff". Interesting.

**Comment by nortikin** [comment]
[scale_attempt_2017_04_12_11_25.zip](https://github.com/nortikin/sverchok/files/916449/scale_attempt_2017_04_12_11_25.zip)

**Comment by Kosvor2** [comment]
No need to use [:] after Scale.

![sort_by_distance1](https://cloud.githubusercontent.com/assets/22656834/24958004/393ea902-1fa7-11e7-89e1-21e1abd31f89.png)

**Comment by enzyme69** [comment]
@nortikin  nice trick, same result:
![screen shot 2017-04-12 at 22 45 00](https://cloud.githubusercontent.com/assets/3952687/24958179/d2709002-1fd1-11e7-9ac4-15f596467b7e.png)

@Kosvor2  thanks for tips trying this one...

**Comment by enzyme69** [comment]
Kosvor2 node tree:
![screen shot 2017-04-12 at 22 56 06](https://cloud.githubusercontent.com/assets/3952687/24958619/411be91a-1fd3-11e7-9c77-046ea68ecd2c.png)
[sv_matrix_distance_003_2017_04_12_12_56.zip](https://github.com/nortikin/sverchok/files/916534/sv_matrix_distance_003_2017_04_12_12_56.zip)

Sorting is sort of like falloff, for now I guess it's good enough.

I don't know maybe needs to Numpy this at some point.

Will come back in near future~

Thanks!

**Comment by Kosvor2** [comment]
Also for straight falloff no need sorting at all:

![scale_loc2](https://cloud.githubusercontent.com/assets/22656834/24958734/ca6e8c24-1fa9-11e7-8a4c-5db6ffbbaf11.png)

**Comment by enzyme69** [comment]
@Kosvor2 this is exactly what my brain try to compute :D thanks for example!

**Comment by enzyme69** [comment]
Near future:
SV Attribute Transfer or SV Dynamic Paint that works on any attributes.

**Comment by zeffii** [comment]
in Near future:
@enzyme69  starts coding?

**Comment by nortikin** [comment]
@zeffii enzyme69 had some scripts allready, i think, he can handle when put efforts

**Comment by zeffii** [comment]
@nortikin 
>  i think, he can handle when put efforts

yeah. efforts :)

**Comment by enzyme69** [comment]
@nortikin I need to do some efforts! 👍 

![screen shot 2017-04-13 at 11 49 26](https://cloud.githubusercontent.com/assets/3952687/24986734/5ada7a6c-203f-11e7-8eca-44c9fdb8b440.png)
