### ISSUE TITLE
Object ID and Matrix In

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1505]
This confused me a bit, how to properly plug Matrix In into the slot of Object ID Set to quicly transform objects?

![screen shot 2017-04-13 at 11 05 51](https://cloud.githubusercontent.com/assets/3952687/24985702/420e5590-2039-11e7-88e4-97876211961f.png)

**Comment by enzyme69** [comment]
I asked this before:
https://github.com/nortikin/sverchok/issues/1478

And.. asking again. There must be a better way.

**Comment by Kosvor2** [comment]
There is no better way than Object Remote.
Set node not designed to work with such nesting level.

see:
![best_way](https://cloud.githubusercontent.com/assets/22656834/24987296/a1ce95a6-2018-11e7-9a1c-2ff27756882f.png)

![other_way](https://cloud.githubusercontent.com/assets/22656834/24987302/a94e6f72-2018-11e7-9958-0c4d019ec345.png)

**Comment by Kosvor2** [comment]
#1510

**Comment by enzyme69** [comment]
Thanks for explanation Kosvor~
