### ISSUE TITLE
Time and Frame update = slow, but heaps fast on node tree

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1506]
[speed_transform_002_2017_04_13_01_17.zip](https://github.com/nortikin/sverchok/files/918261/speed_transform_002_2017_04_13_01_17.zip)

When I am scrubbing on node tree, I am getting a super speedy result.

But then scrubbing in the timeline, with Time Frame updating, I am getting 10x slower interaction. Is this Blender thing? Or Sverchok "known limitation" where it needs to update node-tree each frame?

**Comment by enzyme69** [comment]
![monkey_magic_003](https://cloud.githubusercontent.com/assets/3952687/24986033/466b3782-203b-11e7-97c5-7192a3b543e9.gif)

**Comment by zeffii** [comment]
good question. no idea.

**Comment by Kosvor2** [comment]
Its `Objects IN` node. change to `object id selector` -works much faster.

**Comment by zeffii** [comment]
I suspect the slowness really comes from where in the tree the update is coming from. When you update the timeline the whole tree is updated from start to finish, when you just slide a slider midway in the tree, then only the nodes downstream are updated.   

if you are using Objects In just for the matrix.. then it's doing a lot of extra work (like converting verts / edges / faces from the Blender Object to the sverchok data format .. on each update -- that's a waste.)

**Comment by enzyme69** [comment]
@zeffii Apparently turning off update on BMesh Viewer and the speed is back at 10x faster.
@Kosvor2 yes this also increase the speed a bit.

**Comment by enzyme69** [comment]
![screen shot 2017-04-13 at 17 17 47](https://cloud.githubusercontent.com/assets/3952687/24994213/260d2658-206d-11e7-90cf-f8f87c494914.png)
[speed_transform_004x_2017_04_13_07_17.zip](https://github.com/nortikin/sverchok/files/918752/speed_transform_004x_2017_04_13_07_17.zip)

Speedy transform is now possible 💃

**Comment by enzyme69** [comment]
![screen shot 2017-04-13 at 17 25 56](https://cloud.githubusercontent.com/assets/3952687/24994466/504d6544-206e-11e7-8053-8e73f59dea30.png)

Actually faster than I imagine:
- Matrix Transformation 500 objects 15fps.
- Matrix Transformation 5000 objects 7fps.
