### ISSUE TITLE
Thinking of 10000 Matrix manipulations for Joined Mesh --- pre to Bones

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1507]
I have not tested this yet, but I wanted to do this experiment:
1000+ objects are known to be slow when animated. Can Sverchok deals with separated meshes inside and still performs very speedy?

I don't know the comparison of using AN Cython and Sverchok to calculate and animate the Transformation of 1000 or even 10000+ objects. Maybe performance can be issue, but we can bake to alembic and get 100% speed again.

I am thinking that maybe if 1000 - 10000 joined into a single mesh, it will be a lot faster? For sure in Blender 3D viewport.

I imagine if someone brings in a character made of 10000 parts, a joined mesh, and wanting to "scale animate" each parts it will be a hassle to separate all the parts and then animating them. It might be slow, I imagine.

A more **ideal scenario** is probably to set this up using many Bones and assigning each mesh that can be separated into each bone. Armature with 1000 bones will be a lot faster, I think.

**Comment by zeffii** [comment]
Imagine if you just used Sverchok for its strengths: procedural modelling. and Animation Nodes for anything related to animation. That's a situation i can believe in.

**Comment by zeffii** [comment]
btw i can totally understand why the idea of being able to animate a dynamic mesh is so appealing...
