### ISSUE TITLE
Formula to access props

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1509]
![screen shot 2017-04-13 at 11 57 17](https://cloud.githubusercontent.com/assets/3952687/24986933/6c23cb6a-2040-11e7-8504-6726c4b8bca7.png)

Wondering why... X.n[0] does not work...

**Comment by enzyme69** [comment]
And this thing not supporting item assignment, but changing it via Python works... hmm.. that's new for me.

![screen shot 2017-04-13 at 12 02 23](https://cloud.githubusercontent.com/assets/3952687/24987065/1d1fec6e-2041-11e7-84d6-d4fca44a98ee.png)

**Comment by enzyme69** [comment]
But this works, using AN...
![accessing_data](https://cloud.githubusercontent.com/assets/3952687/24987180/cefa09b0-2041-11e7-9394-ea3ea405bd9b.gif)

**Comment by enzyme69** [comment]
[object_in_dir_004_2017_04_13_02_09.zip](https://github.com/nortikin/sverchok/files/918344/object_in_dir_004_2017_04_13_02_09.zip)

**Comment by zeffii** [comment]
maybe `getattr(X, n[0])`

**Comment by enzyme69** [comment]
That is right! Thanks!
![screen shot 2017-04-13 at 17 32 01](https://cloud.githubusercontent.com/assets/3952687/24994649/228f9036-206f-11e7-8068-5b8291da07ce.png)
