### ISSUE TITLE
Bug Search Node Bar suddenly does not work :(

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1511]
![screen shot 2017-04-13 at 15 53 34](https://cloud.githubusercontent.com/assets/3952687/24991888/7509bc3c-2061-11e7-9a24-cb21b2e2ad0a.png)
 
...

**Comment by zeffii** [comment]
Oops. For the time being hit shift+ a and hit enter.

Might have to revert my last commit

**Comment by enzyme69** [comment]
@zeffii will try the listing for now, maybe next commit will fix it

**Comment by zeffii** [comment]
what key combo are you pressing to get that search?

**Comment by zeffii** [comment]
ok .. i'll revert

**Comment by enzyme69** [comment]
Confirmed, works again~ 🍡

**Comment by zeffii** [comment]
you didn't answer my question.

**Comment by zeffii** [comment]
addendum:

`class NODE_OT_add_search(NodeAddOperator, Operator)`  may require a sverchok specific operator
