### ISSUE TITLE
Vector() data to Sverchok List?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1512]
I realized that data coming from Location, Scale Object ID is Vector() Type.

[AN_to_SV_002_2017_04_13_06_26.zip](https://github.com/nortikin/sverchok/files/918652/AN_to_SV_002_2017_04_13_06_26.zip)

And I cannot simply plug that into Sverchok usual Vector Out and I cannot use Vector Math either.

Any tips? Sorry for being naive.

**Comment by Kosvor2** [comment]
this is when [:] must be used.

**Comment by enzyme69** [comment]
Aha... that's why cheers~
