### ISSUE TITLE
Intersector node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1514]
A node with a very specific and limited scope. Obtain the intersection profile between two meshes.

![image](https://cloud.githubusercontent.com/assets/619340/25001995/41a480ca-2048-11e7-853b-b720bdd2d52b.png)

@Kosvor2  you know how to do that with bvh ?

**Comment by Kosvor2** [comment]
There is a way to find which polygons of two meshes overlap each other, using mathutils.bvhtree: https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/bvh_overlap_polys.py

But it will not work for exact Poly-inside-Edge intersection.

**Comment by zeffii** [comment]
> But it will not work for exact Poly-inside-Edge intersection.

I think that's a reasonable limitation

**Comment by zeffii** [comment]
am tempted to start making temporary Meshes that are not linked to the scene, for such stuff... even if it's just to experiment.
