### ISSUE TITLE
marble script

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1515]
I'm trying to develop a marble script, i think could be improved but if you want to try test the script.
The code is taken from 'Texturing and modelling' p. 229 (Animating solid textures) and of course translated fomr C++ to python.
![marble_script](https://cloud.githubusercontent.com/assets/1275858/25045841/7ca98e7c-212e-11e7-8b3b-f47887521631.png)
the script:
```python
"""
in vertices v d=[[]] n=0
in octaves s d=2 n=2
in hard_on s d=1 n=2
in noise_type s d=0 n=2
in amp s d=0.5 n=2
in freq s d=2. n=2
out data v
""" 

from mathutils import noise, Vector, Color
import math

def marble(pnt):
    pnt = Vector(pnt)
    y = pnt.y + 3.0 * noise.turbulence(pnt, octaves, hard_on, noise_type, amp, freq)
    y = math.sin (y * math.pi/2)
    return marble_color(y)

def marble_color(x):
    clr = Color((0.0, 0.0, 0.0))
    x = math.sqrt(x + 1.0) * .707
    clr.g = .30 + .8 * x
    x = math.sqrt(x)
    clr.r = .30 + .6 * x
    clr.b = .60 + .4 * x
    return clr

for v in vertices[0]:

    out = marble(v)
    data.append(out)
```

as it is it outputs vertices ( so you have to select in the `texture viz` the rgb button), if you plug a color-in node in the data socket it will fail.  Maybe i can improve this. 
Probably it might be interesting adding the possibility to change the base color, and a turbulence factor, and differents functions instead the sin: for an example a saw function and a modulated trig function.
I think this script is very simple but you can do funny things...!

**Comment by kalwalt** [comment]
better i think this:
```diff
-for v in vertices[0]:

-    out = marble(v)
-    data.append(out)
+data = [[marble(v) for v in vertices[0]]]
```

**Comment by kalwalt** [comment]
First problem: the script output Color and it seems it can't handled by `Vectors nodes` or `Color nodes out` so i would convert this data to tuple but looking in the Blender Api i can find a to_tuple() method for `Color` as `Vector` has. Should i convert this part of code: 

```python
def marble_color(x):
    clr = Color((0.0, 0.0, 0.0))
    x = math.sqrt(x + 1.0) * .707
    clr.g = .30 + .8 * x
    x = math.sqrt(x)
    clr.r = .30 + .6 * x
    clr.b = .60 + .4 * x
    return clr
```
using `Vector` instead of `Color`?  what do you suggest to do?

**Comment by kalwalt** [comment]
it is simple:
```diff
-return clr
+return (clr.r, clr.g, clr.b)
```

**Comment by kalwalt** [comment]
so you can do:
![marble_script01](https://cloud.githubusercontent.com/assets/1275858/25047372/9dc39dde-2136-11e7-9da7-22b8b8c084ee.png)

**Comment by kalwalt** [comment]
and this:
![marble_script02](https://cloud.githubusercontent.com/assets/1275858/25047497/58560a42-2137-11e7-9111-cadb21b653a7.png)

**Comment by zeffii** [comment]
yeah ,or
```python
return clr[:]
```

**Comment by kalwalt** [comment]
and this do the same thing?

**Comment by kalwalt** [comment]
yes ok, i found the example in the APi:
```python
# components of an existing color can be set
col[:] = 0.0, 0.5, 1.0
```

**Comment by kalwalt** [comment]
final, but to be improved script [here](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/marble.py)

**Comment by zeffii** [comment]
very cool marble effect :)   can you do it in numpy?

**Comment by kalwalt** [comment]
would be nice, i have to think about it. probably not all the code but a good part can be converted to numpy, and so i hope with a performance improvement.

**Comment by zeffii** [comment]
`noise.turbulence` in particular :)

**Comment by kalwalt** [comment]
> noise.turbulence in particular :)

you mean to develop a numpy version of this? 
as i know numpy has only rand functions not noise ( and this will help to develop a custom turbulence func) 
but probably could be done in numpy C++. could be interesting but i never did before.

**Comment by kalwalt** [comment]
i added red green blue options to the script and also a `turb` factor.

**Comment by kalwalt** [comment]
uh i found some interesting articles on perlin 2d with numpy:
http://stackoverflow.com/questions/42147776/producing-2d-perlin-noise-with-numpy
and this:
http://www.siafoo.net/snippet/229

**Comment by kalwalt** [comment]
i think that with the functions used in [this](https://github.com/nortikin/sverchok/issues/1232) with the Perlin numpy we can develop a very cool marble node! In the next days i will try to implement it with scriptNode_lite, and if it make sense to develop a new node...

**Comment by zeffii** [comment]
glad to see you getting good results with numpy. persistence pays off.

**Comment by kalwalt** [comment]
yes, but still i need to improve my python knowedge. But i prefer to learn something  `working in the field` then learn something in a mechanical way. I need some interest in doing it and a motivation for it.

**Comment by zeffii** [comment]
should i include an Add that takes 3 inputs?

**Comment by zeffii** [comment]
it won't be immediately, but i'll include it in my next pass on that node.

**Comment by kalwalt** [comment]
> should i include an Add that takes 3 inputs?
do you refer to the scalar math or the Vector math node or both? i think that in some situation would be helpful. especially with multi addiction.

**Comment by zeffii** [comment]
scalar math node mk2.

**Comment by kalwalt** [comment]
yes of coures not immediately.

**Comment by zeffii** [comment]
you can still write content here btw.. but it doesn't really need to be in active issues
