### ISSUE TITLE
blend4web patch

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#1517]
https://developer.blender.org/D113

**Comment by portnov** [comment]
In short: this adds support of bpy.props.PointerProperty, which is type of property that can be a "pointer" (reference) to another object in blender's scene. If I understood correctly, it can also refer to object located in another blend file (library).

**Comment by zeffii** [comment]
another related interesting development:

https://developer.blender.org/rB73a9ff0d2d4f3cabcaa64f8e47586a793daa77f0
