### ISSUE TITLE
Object or Component Selection by Order

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1522]
We have List Sorting and also a way to select components for masking.

[polygon_sort_list_004_2017_04_16_01_16.zip](https://github.com/nortikin/sverchok/files/924019/polygon_sort_list_004_2017_04_16_01_16.zip)
![screen shot 2017-04-16 at 11 16 03](https://cloud.githubusercontent.com/assets/3952687/25067950/4ba6f698-2296-11e7-9052-f479b8882f60.png)

Now, I am curious, for example if I wanted to get index sorting based on:
- selection in 3D view
- grease pencil strokes direction

Any hints of how this might be achieved?

**Comment by enzyme69** [comment]
Potentially for origami flat unfolding effect, but that's kind of beyond the scope of the question, but I put in anyway.

![screen shot 2017-04-16 at 11 21 16](https://cloud.githubusercontent.com/assets/3952687/25067962/e47c3766-2296-11e7-967b-863b95283232.png)

**Comment by enzyme69** [comment]
Or peeling kind of effects.
![screen shot 2017-04-16 at 11 23 29](https://cloud.githubusercontent.com/assets/3952687/25067969/22c661f4-2297-11e7-9fe8-f0fe9f105b2e.png)

**Comment by enzyme69** [comment]
This might be related:
http://blenderscripting.blogspot.com.au/2011/07/getting-index-of-currently-selected.html

**Comment by enzyme69** [comment]
I will ask Blender Stack Exchange as well...

**Comment by enzyme69** [comment]
I imagine some kind of "mechanism" that is keep watching the component and as it become True, it gets added to the list.

**Comment by enzyme69** [comment]
I could probably fake it this way... but not quite satisfying.

![screen shot 2017-04-16 at 11 46 57](https://cloud.githubusercontent.com/assets/3952687/25068056/720a66cc-229a-11e7-9993-02a9ec383e9e.png)

[list_masking_magic_001_2017_04_16_01_47.zip](https://github.com/nortikin/sverchok/files/924035/list_masking_magic_001_2017_04_16_01_47.zip)

**Comment by enzyme69** [comment]
This one I quite like, but then again kind of wondering if we can get the index order, or will the resulting mesh have the index already in order anyway? Not sure...
[list_masking_magic_003_2017_04_16_01_54.zip](https://github.com/nortikin/sverchok/files/924037/list_masking_magic_003_2017_04_16_01_54.zip)

**Comment by enzyme69** [comment]
This one is also related:
https://blenderartists.org/forum/showthread.php?241524-respect-selection-order

**Comment by nortikin** [comment]
[sort-by-gp_2017_04_16_07_32.zip](https://github.com/nortikin/sverchok/files/924138/sort-by-gp_2017_04_16_07_32.zip)
please, use this layout
![sort-by-gp](https://cloud.githubusercontent.com/assets/5783432/25069659/37e2b616-2290-11e7-894a-239433ef7608.png)

**Comment by enzyme69** [comment]
@nortikin Roger that, I am studying now...

**Comment by enzyme69** [comment]
![polygon_face_index_order](https://cloud.githubusercontent.com/assets/3952687/25069905/ae40044e-22d1-11e7-8b60-af056b82a389.gif)

This is actually quite fascinating... Sorting and Ordering in a way I could never imagine ever be done or ... something might be taken for granted.

It is somewhat clearly presented. Even though only 1 grease pencil stroke, I think with some kind of "solver" allowing it to branching. Maybe.

I'll have to meditate on it first. Thanks again @nortikin you are the man~

**Comment by enzyme69** [comment]
@nortikin How did you hide slots?

![screen shot 2017-04-16 at 18 26 16](https://cloud.githubusercontent.com/assets/3952687/25069925/3888b100-22d2-11e7-8998-1acad53d17cd.png)

**Comment by enzyme69** [comment]
Based on Nortikin Example.
![screen shot 2017-04-16 at 19 05 20](https://cloud.githubusercontent.com/assets/3952687/25070103/ae5d3752-22d7-11e7-8927-94381ee1d39d.png)

For future question:
**_Based on User Selected Orders of Objects._**

**Comment by nortikin** [comment]
@enzyme69  ctrl+H will hide sockets H will hide node
