### ISSUE TITLE
help me understand Vector Sort

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1524]
I have a feeling SV Vector Sort node is not quite right, needs MK2.

![screen shot 2017-04-16 at 19 21 37](https://cloud.githubusercontent.com/assets/3952687/25070151/f7955eca-22d9-11e7-82a4-6f73529d4eb2.png)

**XYZ mode** is not so clear, or maybe just a bit broken.

This node does not have documentation (yet) --> I want to add, but still not quite sure.

My guess:
- Vector Sort is to sort bunch of vectors, not really for polygon face, but it looks at bunch of points and give it a number
- User can provide index data... ?
- Distance and Axis probably as I guess it is, but scratching my head.
- My guess XYZ should sort based on direction?

**Comment by enzyme69** [comment]
Maybe I was imagining thing, but I swear Sverchok used to have Vertex Component sort node.
![screen shot 2017-04-16 at 19 26 28](https://cloud.githubusercontent.com/assets/3952687/25070173/9c12b376-22da-11e7-8d9a-fbd210828720.png)

**Comment by zeffii** [comment]
i invite you to spend a few minutes looking at the code.

**Comment by zeffii** [comment]
>  This node does not have documentation (yet)

it does : http://nikitron.cc.ua/sverch/html/nodes/vector/vertices_sort.html

**Comment by zeffii** [comment]
stick a matrix apply infront of the Verts/Polygons, and rotate the mesh around, you'll get an idea of how XYZ sort works.. it doesn't sort the polygons, but it rearranges vertices and keeps the visible topology the same.

**Comment by kalwalt** [comment]
@enzyme69 also look at the pull request thread https://github.com/nortikin/sverchok/pull/88

**Comment by zeffii** [comment]
if you wanted to sort the polygons based on their distance from an empty, you'd sort the polygon lists based on the median of the verts that comprise each polygon.

**Comment by enzyme69** [comment]
I think I sort of got it. Thanks!!
