### ISSUE TITLE
SN Lite - Get List Component Index By User Selection Order

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1525]
I got my Python bpy answer regarding User Selection Order of Component Index:
https://blender.stackexchange.com/questions/77824/would-it-be-possible-to-get-list-of-index-of-components-by-selection-order-in-ed

Script is as below:

```python
import bpy
import bmesh

obj = bpy.context.object

if obj.mode == 'EDIT':
    bm = bmesh.from_edit_mesh(obj.data)
elif obj.mode == 'OBJECT':
    bm = bmesh.new()
    bm.from_mesh(obj.data)

mysort = []

for i in bm.select_history:
    print(type(i),i.index)
    mysort.append(i.index)
    
print(mysort)
```

A quick port into SN Lite, but I am failing at Object In slot:

```python
"""
in obj o
out indexsort s d=0 n=2 
"""

import bpy
import bmesh

#obj = bpy.context.object

print(obj)

#obj = obj


#if obj.mode == 'EDIT':
#    bm = bmesh.from_edit_mesh(obj.data)
#elif obj.mode == 'OBJECT':
#    bm = bmesh.new()
#    bm.from_mesh(obj.data)

indexsort = []

#for i in bm.select_history:
#    #print(type(i),i.index)
#    indexsort.append(i.index)
    
print(indexsort)


```

**Comment by enzyme69** [comment]
![screen shot 2017-04-16 at 21 23 23](https://cloud.githubusercontent.com/assets/3952687/25070788/f2b6fe7a-22ea-11e7-9892-e5a2e1a1716a.png)

**Comment by enzyme69** [comment]
I modified a bit the code, I think I got it:

```
"""
in objects_in o d=[[]] n=0
out indexsort s d=0 n=2 
"""

import bpy
import bmesh

#obj = bpy.context.object
#print(objects_in)

obj = objects_in[0]


if obj.mode == 'EDIT':
    bm = bmesh.from_edit_mesh(obj.data)
elif obj.mode == 'OBJECT':
    bm = bmesh.new()
    bm.from_mesh(obj.data)

indexsort = []

for i in bm.select_history:
    #print(type(i),i.index)
    indexsort.append(i.index)
    
print(indexsort)


```

@zeffii the droplist does not work though, I need to use Objects In node.

**Comment by enzyme69** [comment]
![screen shot 2017-04-16 at 21 28 55](https://cloud.githubusercontent.com/assets/3952687/25070813/b7ec5708-22eb-11e7-857a-6b1e8a03dbf2.png)

**Comment by enzyme69** [comment]
Hmm... selecting one by one works, but not if I use C and draw.

**Comment by zeffii** [comment]
> @zeffii the droplist does not work though, I need to use Objects In node.

you need to start thinking in terms of "I can't get it to work" not.  " it doesn't work "

**Comment by zeffii** [comment]
The object socket implementation in SNLite has no documentation, but i've added it now.

```python
"""
in objects_in o d=[] n=0
out indexsort s d=0 n=2 
"""

import bpy
import bmesh

obj = objects_in
if obj and len(obj):
    obj = obj[0]
else:
    obj_name = self.inputs['objects_in'].object_ref
    obj = bpy.data.objects[obj_name]


if obj.mode == 'EDIT':
    bm = bmesh.from_edit_mesh(obj.data)
elif obj.mode == 'OBJECT':
    bm = bmesh.new()
    bm.from_mesh(obj.data)

indexsort = []

for i in bm.select_history:
    indexsort.append(i.index)
    
print(indexsort)
```
i'll fix it up so the if/else is done in the background..  but for now, this is what you do.

**Comment by zeffii** [comment]
> but not if I use C and draw.

0_o

**Comment by enzyme69** [comment]
I got it now. Apparently my mistake is always assuming node to work in
certain way.

But I need to dig the code or read the docs.

This is always the case for visual node based environments and maybe
programming environments I think....

Hmmm..
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
