### ISSUE TITLE
New guidelines for writing docstrings for nodes (and update old ones)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1534]
Currently our docstrings for Node Classes don't have much practical utility. They don't show up in the Node Index (manual Menu / Submenus) because the descriptor shows only the operator for the menu item. Don't know what I mean?

![image](https://cloud.githubusercontent.com/assets/619340/25123569/262539ea-2429-11e7-9e31-61f47062a432.png)

which is utterly useless. But can't be avoided unless we generate operators dynamically for each `node_add`, and that is not going to happen. (not because we can't... but because... well.. it's about as stupid as pulling an aeroplane with your teeth... it can be done.. but... wtf... ).

Anyway, i digress, The default search menu (the one that lets you type letters and get results) doesn't show the node description either... this would have been a perfect place to use the docstring... 
    
![image](https://cloud.githubusercontent.com/assets/619340/25123696/99f1e378-2429-11e7-9a38-d8b35e7b36cf.png)

well, it doesnt.. so I made an alternative searchbar (just commited) and it can be triggered from `shift+]`.

![image](https://cloud.githubusercontent.com/assets/619340/25123739/bf86273e-2429-11e7-986d-202277aef149.png)

currently not many nodes have a docstring that describes anything other than the node name, and before this search tool there was little reason to adapt any sort of convention. But now..there is, and i suggest the following .  

1. The docstring should start off with a short < 20 char description (too short? think harder) and be something like `""" generate line/polyline """. 

2. For sanity's sake i've added a feature that will let you write much longer docstrings (as you should), but you add a `///` at around 20 characters to indicate the end of the short description. See for instance the docstring of SvProfileNode

![image](https://cloud.githubusercontent.com/assets/619340/25124340/b4947450-242b-11e7-8a8f-d5b4a5b1c563.png)

https://github.com/nortikin/sverchok/blob/master/nodes/generators_extended/profile.py#L521-L537

```python
class SvProfileNode(bpy.types.Node, SverchCustomTreeNode):
    '''
    svg-like 2d profiles ///

    SvProfileNode generates one or more profiles / elevation segments using;
    assignments, variables, and a string descriptor similar to SVG.

    This node expects simple input, or vectorized input.
    - sockets with no input are automatically 0, not None
    - The longest input array will be used to extend the shorter ones, using last value repeat.

    '''

    bl_idname = 'SvProfileNode'
    bl_label = 'Profile Parametric'
    bl_icon = 'OUTLINER_OB_EMPTY'

    def mode_change(self, context):
```

**Comment by zeffii** [comment]
for more details about the new search feature, see https://github.com/nortikin/sverchok/pull/1521

**Comment by kalwalt** [comment]
testing this new feature but i can't see the alternative searchbar: shift+] do nothing for me.

**Comment by kalwalt** [comment]
could be an issue with different keyboard type? i have an italian keyboard

**Comment by zeffii** [comment]
@kalwalt  look in the user preferences, to see what it creates..

**Comment by zeffii** [comment]
```python
        kmi = km.keymap_items.new('node.sv_extra_search', 'RIGHT_BRACKET', 'PRESS', shift=True)
        nodeview_keymaps.append((km, kmi))
```

generates

![image](https://cloud.githubusercontent.com/assets/619340/25128858/b8b1ff98-243b-11e7-99fd-5334afe290ef.png)

**Comment by kalwalt** [comment]
mine is:
![schermata del 2017-04-18 13-37-41](https://cloud.githubusercontent.com/assets/1275858/25129038/a2c980f6-243c-11e7-9f5e-97ffe315e1e5.png)
don't know why it doesn't open

**Comment by zeffii** [comment]
change it to shift+M   to test..   or hit `spacebar` and type 'extra' and enter to invoke the search :)

**Comment by zeffii** [comment]
i think ubuntu hijacks shift+]

**Comment by kalwalt** [comment]
yes i was thinking the same. i will try it . yes probably related to Ubuntu.

**Comment by zeffii** [comment]
or some other background app..  btw

![image](https://cloud.githubusercontent.com/assets/619340/25129439/60ea8dfe-243e-11e7-9e9d-764d1e423746.png)

the search also uses the `description` to dig results.

**Comment by kalwalt** [comment]
`spacebar`  + typing extra works well: i can now import the `>obj vd`  macro.
trying now to change the predefined key with shift + m

**Comment by kalwalt** [comment]
changed to shft + M works well.
just a note on my key board  the key conbimation  shift + ]  is `shift` +`Alt Gr`  and `]`  normally give me` }`

**Comment by kalwalt** [comment]
Btw, having the macros is awesome!

**Comment by zeffii** [comment]
a few nice default macros should be added too... but i want to keep user macros for those users who can use them without is holding their hand :)

regarding shift+M, when you restart I think the modification will be lost.. not sure...  but if you say you press `shift+alt gr+]`  i hope you're ok with that.

**Comment by kalwalt** [comment]
i think that i can't use `shift + ]` with my keyboard type. I was explaining that the combination of the keys is not correct for me. i have to press that keys i got` }` that is not correct. I tested also in the blender user preferences, you can type the key and see the resultant input associated but it seems impossible with my keyboard type the `shift + ]` combination.
this is the italian keyboard:
![it_keyb](https://cloud.githubusercontent.com/assets/1275858/25131944/017262e8-2448-11e7-9bcb-1cd2885c3248.png)

**Comment by kalwalt** [comment]
us keyboard:
![400px-kb_united_states-noaltgr svg](https://cloud.githubusercontent.com/assets/1275858/25132021/52982806-2448-11e7-805f-1722870572bc.png)
do you see the difference?

**Comment by zeffii** [comment]
I understand :)   it's a very convenient shortcut for me...   not sure what to do about that..

i'd change it to shift+S it's not mapped yet.. and S for search..     because it's closer than F...for find.

**Comment by kalwalt** [comment]
also a bit difficult to explain. The images are self explanatory. Ok for the changes. This is not a critical issue but if we can improve is better.

**Comment by zeffii** [comment]
@kalwalt   what does yours print here

```python
>>> import locale
>>> locale.getdefaultlocale()
('en_GB', 'cp1252')

```

**Comment by kalwalt** [comment]
this is mine:
>> import locale
>>> locale.getdefaultlocale()
('it_IT', 'UTF-8')

**Comment by zeffii** [comment]
well -- this is not a topic I have much patience with .  eventually we'll add a sublime/textmate like kb combo figuration json (i prefer doing settings with json... instead of ui)

**Comment by zeffii** [comment]
something like 
```json
{
    "node_editor": [
                {"operator": "node.sv_monad_enter", ........keys  },
                {"operator": "node.sv_monad_expand", ........keys  },
                {"operator": "node.sv_extra_search", ........keys  },
    ]
}
```

**Comment by kalwalt** [comment]
and so the user may changes his keys?

**Comment by zeffii** [comment]
yep. there would be a `sv_default_keymaps.json`  and a corresponding `sv_user_keymaps.json`, and keys added into sv_user_keymaps would override entries found in the default.

**Comment by kalwalt** [comment]
ok, someething like a `.config ` file as in the Ogre engine, where you can customize path and other settings.

**Comment by zeffii** [comment]
campbell suggested we use a dynamic enum property for the shift+A menus, that way we can give more useful tooltips.
