### ISSUE TITLE
issue with macros search

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1535]
I open this issue as started in [this](https://github.com/nortikin/sverchok/issues/1534)
if other users as these issues post here please.
In ubuntu `Shift + ]` doesn' works for me change if you can to `Shift + M` , changing this line of code
https://github.com/nortikin/sverchok/blob/master/ui/nodeview_keymaps.py#L55

 ```diff
 - kmi = km.keymap_items.new('node.sv_extra_search', 'RIGHT_BRACKET', 'PRESS', shift=True)
 + kmi = km.keymap_items.new('node.sv_extra_search', 'M', 'PRESS', shift=True)
```
i have also another issue:
i create my folder` '/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/datafiles/sverchok/user_macros'`
and my file `macros.py`:

```python
"""

blablabla

"""

def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(a=10, b=140):
    """ info about domo esta4 """
    print(a, b)

```

but in the extra search typing `<` doesn't give me the resultant user macro.

**Comment by zeffii** [comment]
is this second part resolved yet?  `<` should display
![image](https://cloud.githubusercontent.com/assets/619340/25133182/34a67f7e-244c-11e7-9fe9-c65331fb8f44.png)

does your terminal say anything?

**Comment by kalwalt** [comment]
@zeffii no, not tresolved  but as mentioned in the pull request https://github.com/nortikin/sverchok/pull/1521 i can have the searching macros result by scripting, at least in this way it  works.

**Comment by nortikin** [comment]
nothing on <

**Comment by kalwalt** [comment]
this is also a keyboard issue?

**Comment by kalwalt** [comment]
i will try changing the key binding

**Comment by zeffii** [comment]
ideally i would not hardcore any shortcuts..

and `>` does work?

**Comment by zeffii** [comment]
what about whem you type `domo`   or ` vd`

**Comment by kalwalt** [comment]
`> ` works good for me

**Comment by kalwalt** [comment]
domo do nothing
vd give me the two macros, as expected, and i can import them

**Comment by zeffii** [comment]
ok, if domo isn't working, then you don't see this in your console 

```
--- first time getting sv_macro_module ---

```

**Comment by zeffii** [comment]
you will need to hit F8  if you haven't already..

**Comment by kalwalt** [comment]
nothing of this, but my macros is a bit different:

```python
"""

blablabla

"""

def domo_esta(self, context):
    """ info about domo esta /// will ignore this"""
    active_node = context.active_node
    if active_node:
        print(active_node.name)
        print(active_node.location)
        print(active_node.bl_idname)


def domo_esta4(a=10, b=140):
    """ info about domo esta4 """
    print(a, b)

```
but i can't see `blablabla` comment.

**Comment by kalwalt** [comment]
should i try with the other one?

**Comment by kalwalt** [comment]
changing the macro has no effect...

**Comment by zeffii** [comment]
```
# test

import os
import importlib.util as getutil
import bpy


idx = 20
fx = []
local_macros = {}

def get_main_macro_module(fullpath):
    if os.path.exists(fullpath):
        print('--- first time getting sv_macro_module --- ')
        spec = getutil.spec_from_file_location("macro_module.name", fullpath)
        macro_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(macro_module)
        local_macros['sv_macro_module'] = macro_module
        return macro_module

def fx_extend(idx, datastorage, filepath):

    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    fullpath = os.path.join(datafiles, filepath)
    get_main_macro_module(fullpath)

fx_extend(idx, fx, 'user_macros/macros.py')

print(local_macros['sv_macro_module'])

```

should output

```
--- first time getting sv_macro_module ---
<module 'macro_module.name' from 'C:\\Users\\zeffi\\AppData\\Roaming\\Blender Foundation\\Blender\\2.78\\datafiles\\sverchok\\user_macros/macros.py'>
```

**Comment by kalwalt** [comment]
i will look at this evening again hoping to find the reason of this behavior.

**Comment by zeffii** [comment]
i think it's a path slash thing..

**Comment by kalwalt** [comment]
@zeffii yes that script works but not in the extra search menu.

**Comment by zeffii** [comment]
w e i r d .

**Comment by kalwalt** [comment]
maybe becuase i'm on linux OS and you on windows?

**Comment by zeffii** [comment]
at this moment i'm not sure.. but i'll make some changes anyway.

**Comment by kalwalt** [comment]
i wll try this evening on my windows partition. sorry i can't now.

**Comment by zeffii** [comment]
that's ok. I appreciate the testing!

**Comment by kalwalt** [comment]
i like this feature! more later...

**Comment by zeffii** [comment]
and this should print consistent paths
```
import os
import bpy

datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
fullpath = os.path.join(datafiles, 'user_macros', 'macros.py')

print(fullpath)
```

**Comment by kalwalt** [comment]
to be clear: this script:
```python
# test

import os
import importlib.util as getutil
import bpy


idx = 20
fx = []
local_macros = {}

def get_main_macro_module(fullpath):
    if os.path.exists(fullpath):
        print('--- first time getting sv_macro_module --- ')
        spec = getutil.spec_from_file_location("macro_module.name", fullpath)
        macro_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(macro_module)
        local_macros['sv_macro_module'] = macro_module
        return macro_module

def fx_extend(idx, datastorage, filepath):

    datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
    fullpath = os.path.join(datafiles, filepath)
    get_main_macro_module(fullpath)

fx_extend(idx, fx, 'user_macros/macros.py')

print(local_macros['sv_macro_module'])

```

give me:
```
Traceback (most recent call last):
  File "/Text", line 29, in <module>
KeyError: 'sv_macro_module'
Error: Python script fail, look in the console for now...
```
instead
this:
```python
import importlib.util as getutil
import os

ddir = lambda content: [n for n in dir(content) if not n.startswith('__')]


def function_iterator(foo):
    for name in ddir(foo):
        obj = getattr(foo, name)
        if callable(obj):
            yield name, obj.__doc__

def get_main_macro_module(fullpath):
    if os.path.exists(fullpath):
        spec = getutil.spec_from_file_location("macro_module.name", fullpath)
        macro_module = getutil.module_from_spec(spec)
        spec.loader.exec_module(macro_module)
        return macro_module

def fx_extend(idx, datastorage, filepath):
    # shall be dynamic
    datafiles = r'/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78' 
    fullpath = os.path.join(datafiles, filepath)

    macro_module = get_main_macro_module(fullpath)
    if not macro_module:
        return

    for func_name, func_descriptor in function_iterator(macro_module):
        fx.append((func_name, func_descriptor, '', idx))
        idx +=1


fx = []
idx = 20
fx_extend(idx, fx, 'datafiles/sverchok/user_macros/macros.py')

print(fx)


```
give me as espected:
`[('domo_esta', ' info about domo esta /// will ignore this', '', 20), ('domo_esta4', ' info about domo esta4 ', '', 21)]`
i hope this will help.

**Comment by zeffii** [comment]
we won't be hardcoding the path :)

but what does this return
```
import os
import bpy
datafiles = os.path.join(bpy.utils.user_resource('DATAFILES', path='sverchok', create=True))
print(datafiles)
```

**Comment by zeffii** [comment]
something like `/home/walter/.config/blender/2.78/datafiles/sverchok`  ?

**Comment by kalwalt** [comment]
yes `/home/walter/.config/blender/2.78/datafiles/sverchok` but my macro are in 
`/home/walter/blender-2.78a-linux-glibc211-x86_64/2.78/datafiles/sverchok/user_macros
`
now, i try to move the macro in the `/home/walter/.config/blender/2.78/datafiles/sverchok/user_macros`

**Comment by kalwalt** [comment]
moving the macro into  `/home/walter/.config/blender/2.78/datafiles/sverchok/user_macros` solved the issue:
![macro_ok](https://cloud.githubusercontent.com/assets/1275858/25142522/71606b44-2467-11e7-9d44-2f31eb17f7d4.png)
Excellent!! :smile: 

p.s. should be added a note at the top of the https://github.com/nortikin/sverchok/pull/1521

**Comment by kalwalt** [comment]
i want to try now creating a custom macro to see what happens.

**Comment by zeffii** [comment]
cool

**Comment by zeffii** [comment]
i've added that to the prelim docs.

**Comment by zeffii** [comment]
how about `shift + /?`  that's another nice combo for me.

**Comment by kalwalt** [comment]
i can test it. but i think shift + S is better, maybe less problematic.

**Comment by zeffii** [comment]
OK. shift+S until i (or someone else) gets around to doing custom keymaps.

**Comment by kalwalt** [comment]
but wait before doing this changes `Shift S` is used by many addons. i will try `Shift /` now.

**Comment by zeffii** [comment]
actually.. i'm liking ctrl+Space :)

**Comment by zeffii** [comment]
ctrl+space is perfect.  

space => general search
ctrl+space => extra search.

**Comment by zeffii** [comment]
but... i think osx hijacks that combo too...

**Comment by kalwalt** [comment]
how is called in English ` /` is slash, right?

**Comment by zeffii** [comment]
yeah `kmi = km.keymap_items.new('node.sv_extra_search', 'SLASH', 'PRESS', shift=True)`

**Comment by kalwalt** [comment]
i did:
```diff
- kmi = km.keymap_items.new('node.sv_extra_search', 'RIGHT_BRACKET', 'PRESS', shift=True)
+kmi = km.keymap_items.new('node.sv_extra_search', 'SLASH', 'PRESS', shift=True)
```

**Comment by kalwalt** [comment]
it has no effect. maybe than `ctrl+space` is better.

**Comment by zeffii** [comment]
hey... am tempted to do some kind of keyboard language test for the keymaps.. os language locality or something ..

**Comment by kalwalt** [comment]
`ctrl+space ` works fine:

`kmi = km.keymap_items.new('node.sv_extra_search', 'SPACE', 'PRESS', ctrl=True)`

> hey... am tempted to do some kind of keyboard language test for the keymaps.. os language locality or something ..

Would be nice. it will save many issues.

**Comment by zeffii** [comment]
well i remember @ly29  didn't use ctrl+space (the original command for the dynamic menu) because he used that for some other app / system shortcut.  

i'm OK with setting it to ctrl+space for the time being...it totally makes sense.

**Comment by kalwalt** [comment]
yes it used by some pie menu... and context toggle in the 3dview.

**Comment by kalwalt** [comment]
regarding creating custom macros i think i will open a separate issue ( and so we can use it also as reference)

**Comment by zeffii** [comment]
ok. lets do it
