### ISSUE TITLE
How to add a custom macro?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1537]
I thought that macro should be similar to a scriptnode_lite script but it's not. I'm working wth Linux OS (Ubuntu 64) and  my macro is in `/home/walter/.config/blender/2.78/datafiles/sverchok/user_macros`  
 This script will raise an error, because it can't get the `some` variable:

#### macros.py
```python
"""
in some s d=0 n=1
out other s
"""

import numpy as np

def simple_add(self, some):
   """ info about simple_add /// will ignore this"""
   
   s = np.array(some)
   add = s + 2

   return add.tolist()

other = [simple_add(some)]
```
in sinthesis how sholud add my macro and how should be coded? How should be intended the macros.py file? Should be intended as a list of macros ( an index)?

**Comment by zeffii** [comment]
yeah, the macros at present are just 'one shot'  / triggerables.    I haven't yet had any bright ideas about how to pick a macro and send variables to it. perhaps via an additional popup..

**Comment by zeffii** [comment]
do you just want to add custom snlite templates?

**Comment by kalwalt** [comment]
could be a possibility, we have other choices?

**Comment by kalwalt** [comment]
but first i want to understand the basic approach.

**Comment by zeffii** [comment]
i'm definitely open to adding a directory for user defined snlite scripts.. so they appear in the dropdown.

**Comment by nortikin** [comment]
< still not work

**Comment by kalwalt** [comment]
@nortikin where are located your macros.py? In linux i need to move them to `home/walter/.config/blender/2.78/datafiles/sverchok/user_macros`
