### ISSUE TITLE
Socket Custom Drawing - Collapse / Expand 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1539]
Starting a new thread to dissect the socket custom drawing (in particular the collapse/expand input feature) and continue the discussion here since it turned into a long digression on the [mix input node thread](https://github.com/nortikin/sverchok/pull/1440). I’m going to continue to use the mixInput node as a guinea pig since it has all of the input types.

Here’s the current iteration on the subject:

![sv-mixinputs-demo8](https://cloud.githubusercontent.com/assets/2083719/25159410/9a1c3e8a-247d-11e7-965c-272aca1a309e.gif)
![sv-collapseexpand-2](https://cloud.githubusercontent.com/assets/2083719/25160680/78babc8c-2485-11e7-91d5-8137e46bf4ee.jpg)

I’m still trying to figure out / brainstorm some issues:

- Figure out how to make the expand button connected to the drop down list. (see screenshot)
In collapsed form the property is a drop down created using template_component_menu that doesn’t seem to behave the same way as the enum property when added to a column (with aligned set on).

- Vector input typically has VerticesSocket type, but for this socket type there doesn’t seem to be a custom draw. In order to have an expandable vector input I have to make the Vector input socket as a StringsSocket. Is this OK? Is there a way to keep the VerticesSocket type and still use custom draw ? 

- Add more space between socket inputs. They seem to be a little bit too crowded. What is the best way to space them apart a little bit ?

- Align the socket label (in custom draw) with the socket nodule :)

**Comment by zeffii** [comment]
Stare at the difference between the draw function of verticessocket and stringssocket.

The .separator is one way to add some headspace between rows or columns, or an empty .label, or an extra but unused .row()

I'm thinking we should add an expand boolprop to the sockets

**Comment by zeffii** [comment]
as for the gap, i don't really mind it so much, but i think it's something like

pseudo
```
    if not socket.is_linked:
        if not socket.showing_expanded:
            draw this using a single row()
        else:
            draw this with a set of columns
```

**Comment by zeffii** [comment]
i'm strongly considering doing further subclassing of the sockets... to allow easier creation of Color3/Color4 Quaternion /

**Comment by DolphinDream** [comment]
Sweet 🤗 so we're getting ColorSocket and QuaternionSocket ? 😁 hmm I almost mistyped that ColorSuckit 😉

**Comment by kalwalt** [comment]
> i'm strongly considering doing further subclassing of the sockets... to allow easier creation of Color3/Color4 Quaternion

a nice idea would also extend `vector `to vec4

**Comment by DolphinDream** [comment]
Subclassing sockets .. nice :) Can we please get the custom_draw for every socket type, not just the strings type ? 

Also.. i'm tempted to mess with the SocketCommon code to add the expander/collapser UI directly in the base of all sockets so that all nodes could benefit from this feature. Perhaps the expander/collapser button could be hidden and let each node enable it via some explicit socket flags (e.g. like socket.use_expander = True).

**Comment by zeffii** [comment]
i don't want to get in the way of progress, it's the most dangerous thing to do in a project.. but we like to be a bit conservative with updates to fundamental parts like the sockets. that part has very high inertia because it impacts the whole system.

- I am inclined to agree that the default UI for Vectors should have the expand feature. Matrix, Color, Quaternion too. 
- Each affected ****Socket class should have the `expand` BoolProperty (it simplifies a lot)
- Color3/4 can be one socket type with a mode and an additional BoolProperty
- All these sockets can also have their own FloatVectorProperty, further relieving that stuff from the node's definition.

**Comment by zeffii** [comment]
tho.. matrix is such an awkard 4*4 beast to show on a node... maybe showing it is a little silly, but we should certain be able to use   `self.inputs['matrix'].sv_get()`  , and have the default unconnected matrix , return Identity matrix without passing `(default=Identify_Matrix)`. that needs to stop.

**Comment by DolphinDream** [comment]
I completely agree with everything you said @zeffii  It is dangerous to touch the fundamentals and extreme care should be given for such changes. I’m just scratching the SV world surface so I don’t know what the best approach would be, but I can nevertheless give it a try and let you use your SV expert machete to dice through :) I’ll give it a try, unless you would rather mess with this yourself. At best I’m sure I could learn more of the SV inner intricacies. 

Yeah, the matrix expansion would indeed look too much. A “matrix in” node would probably be best approach. We can experiment with it nevertheless. Identity matrix gone? oh yeah, baby! :) I’ve been meaning for this to be gone since the first time i started using it ;)

**Comment by DolphinDream** [comment]
Why are some sockets defined in the node_tree.py (strings, vertices, matrix, dummy) and some in sockets.py (object, text, float? int?)

**Comment by DolphinDream** [comment]
Is there a good reason for not creating a ColorSocket and a QuaternionSocket ? (instead of using the StringsSocket) ? I think it would make the code cleaner especially if we add the prop expander code in the base classes.

**Comment by DolphinDream** [comment]
See latest [mixNumbers branch](https://github.com/nortikin/sverchok/pull/1440). 

The node_tree.py was updated to include:

```python
class SvSocketCommon:

    use_expander = BoolProperty(default=True)
    expanded = BoolProperty(default=False)
```

and the VerticesSocket to draw expanded UI if the use_expander is True. (for now I turned it ON for all, but it can be turned OFF and let each node’s socket turn it ON via socket.use_expander=True.

```python
def draw(self, context, layout, node, text):
        if not self.is_output and not self.is_linked:
            if self.prop_name:
                if self.use_expander:
                   # draw expander UI and expanded/collapsed prop
               else:
                  # render as before
```

![sv-expandsockets-demo1](https://cloud.githubusercontent.com/assets/2083719/25211724/a5ab83be-2554-11e7-9ce8-4b05dec8f02e.gif)

For now i enabled the expander for the sockets that do not have prop (and use the use_prop feature). It enables nodes like “Vector Attractor” to also expand its “Center” vector socket.  The caveat with the vector input sockets that have longer names is that the name added underneath the expander button gets clipped (which is why I chose for the time being to simply show the first character of the name). Perhaps for longer names the prop name could be displayed on the top instead.

**Comment by zeffii** [comment]
Unlinked matrix input socket could have a button + operator to generate a matrix in to the left and autolink it.

**Comment by zeffii** [comment]
the socket upgrades should be their own branch, and the mix input node should not rely on them yet.

**Comment by DolphinDream** [comment]
You’re right. i’m all over the place. I’ll create a separate branch. I just needed mixInput for the quaternion part but I guess I could go ahead on a separate socketDev branch for now.

**Comment by zeffii** [comment]
>  Why are some sockets defined in the node_tree.py (strings, vertices, matrix, dummy) and some in sockets.py (object, text, float? int?)

the sockets.py is only used for `ScriptNode 3` (which was not fully released. I made SNLite (it's not better than SN3.. but i can better wrestle with my own code... and am less tolerant for it's failures ).

**Comment by zeffii** [comment]
![gobblin](https://cloud.githubusercontent.com/assets/619340/25236817/2022af52-25e9-11e7-8238-481037423c2f.gif)

```python
class SvLinkMatrix(bpy.types.Operator):

    bl_idname = "node.sv_link_matrix_in"
    bl_label = "add a matrix in to the left"

    origin_socket = bpy.props.StringProperty()
    origin = bpy.props.StringProperty()   # incase the operator is executed 
                                          # while the node is not active. (yes..that's possible)
 
    def execute(self, context):
        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        caller_node = nodes.get(self.origin)
        mat_node = nodes.new('SvMatrixGenNodeMK2')
        mat_node.location = caller_node.location[0] - 200, caller_node.location[1]
        
        links.new( mat_node.outputs[0], caller_node.inputs[self.origin_socket])
        return {'FINISHED'}
```

**Comment by DolphinDream** [comment]
Would it cool if we color a socket red if the connected input is of the wrong  type ? To identify which socket is at fault.

**Comment by zeffii** [comment]
we've allowed cross socket connections on purpose,  coloring it with a socket missmatch is a labour of diminishing returns i think... i vote no.

**Comment by zeffii** [comment]
we trust out users to have some awareness..

![image](https://cloud.githubusercontent.com/assets/619340/25244808/768a6902-2602-11e7-976f-86b5b21590ed.png)

**Comment by DolphinDream** [comment]
Fair enough. Though if the right socket is connected but somewhere up the stream the data gets weird it would be useful to know why the note turns red.. which socket data is at fault.

**Comment by zeffii** [comment]
yeah, i think most of us have the terminal / console open at all times (start blender from a terminal by default) so any weirdness is printed out.

i realize that might not help the novice user, but we don't get any significant requests for more "hand holding" in that area. In Sverchok's Redux we experiment with doing some lightweight bgl / blf drawing being side the node in question, with the Exception if possible.

but one thing at a time.

**Comment by DolphinDream** [comment]
@zeffii if i am to add the matrix popper code/button in the MatrixSocket class.. how do i get it to work since I need to find out the caller node the **socket** belongs to. I assume in your test above you added the button/operator to the caller node.

**Comment by zeffii** [comment]
Yes, you must pass the two props to the operator. Which socket and which node, i picked the socket name as an identifier but index (IntProp) might be less prone to failure.

op = layout.operator(........)
op.origin_socket = self.index
op.origin = node.name

**Comment by zeffii** [comment]
so rather it might be
```python
class SvLinkMatrix(bpy.types.Operator):

    bl_idname = "node.sv_link_matrix_in"
    bl_label = "add a matrix in to the left"

    socket_index = bpy.props.IntProperty()
    origin = bpy.props.StringProperty()
 
    def execute(self, context):
        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        caller_node = nodes.get(self.origin)
        mat_node = nodes.new('SvMatrixGenNodeMK2')
        mat_node.location = caller_node.location[0] - 200, caller_node.location[1]
        
        links.new( mat_node.outputs[0], caller_node.inputs[self.socket_index])
        return {'FINISHED'}
```

and then the layout stuff

```python
op = layout.operator(........)
op.socket_index = self.index
op.origin = node.name
```

**Comment by DolphinDream** [comment]
I think we can close this one and continue on the [Socket Expander](https://github.com/nortikin/sverchok/pull/1561) pull request thread.
