### ISSUE TITLE
Is there a way to view colors ? (Color Viewer)

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1540]
Is there a way to see a color in a viewer node ? I’m not sure if the stethoscope could be enhanced to also display color (if it can identify the input is a color)

**Comment by zeffii** [comment]
i was going to suggest stethoscope.. it is supremely suitable for that, because if you need to debug the color data for whatever reason.. you can view the inputs using the other views too.

I don't mind adding a colorviewing mode to stethoscope at all.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25173480/855e22ca-24f4-11e7-9252-7cc2bc5a265a.png)

https://gist.github.com/zeffii/93bf67fc8e04e9c651fa73fb7949d5a4

because it's fast drawing using Vertex size, it is sensitive to the zoom resolution, so you'll see banding if you zoom in out.. The alternative was to draw rects of a certain size or solutions that @kalwalt has provided already.

**Comment by zeffii** [comment]
the grid divisions could gradually decrease as a function of the length of the incoming data. 

- if the incoming color list is size 1 with ten colours, then it might draw 3*3 relatively large rects and a 10'th attached on the side somewhere.
- each increase in color size would result in a call to the int(sqr(size)) to get the optmal rect size.. etc, the remainder would be drawn to the side ..

maybe even display the colour's index in smaller colour lists... and hide that from if you have more than 100 colors..

**Comment by zeffii** [comment]
i'm hoping @kalwalt  will provide a feature on texture viewer to 'pad incoming' if expected does not match given
![image](https://cloud.githubusercontent.com/assets/619340/25174151/c5fc04b2-24f6-11e7-80a9-5febaba66e60.png)

**Comment by zeffii** [comment]
```python
def simple_color_viewer_nvBGL(x, y, args):

    colors = args[0]
    size = 10.0
    
    bgl.glEnable(bgl.GL_POINT_SMOOTH)
    bgl.glPointSize(size)
    bgl.glBlendFunc(bgl.GL_SRC_ALPHA, bgl.GL_ONE_MINUS_SRC_ALPHA)
    
    for color_list in colors:

        bgl.glBegin(bgl.GL_QUADS)
        for idx, color in enumerate(color_list):
            bgl.glColor4f(*color)
            coord = get_location(idx)
            tx = coord[0] + x
            ty = coord[1] + y

            w = size//2
            h = size//2        
            coords = [(tx, ty), (tx+w, ty), (w+tx, ty-h), (tx, ty-h)]
            for coord in coords:
                bgl.glVertex2f(*coord)            
            
        bgl.glEnd()

    
    bgl.glDisable(bgl.GL_POINT_SMOOTH)
    bgl.glDisable(bgl.GL_POINTS)
        
```
https://gist.github.com/zeffii/06bd602aacf8f050966b1b4696ffc085

**Comment by kalwalt** [comment]
or use this script, with glDrawPixels:
```python
"""
in   in_colors  v  d=[[]]  n=0
out  dummy_out  s
"""
import math

import bgl
import bpy
import numpy as np

from sverchok.data_structure import node_id
from sverchok.ui import nodeview_bgl_viewer_draw_mk2 as nvBGL2

clr=0
texture =0

def get_location(i):
    items_wide = 40
    offset_x = 5
    offset_y = 5
    x = offset_x * (i % items_wide)
    y = offset_y * math.floor(i / items_wide)
    return [x, y]

def draw_pixels(x=0, y=0, w=30, h=10, format=clr, pixels=texture):
    type = bgl.GL_FLOAT
    
    bgl.glRasterPos2i(x, y)
    # from Blender API => glDrawPixels(width, height, format, type, pixels)
    bgl.glDrawPixels(w, h, format, type, pixels)

    bgl.glDisable(bgl.GL_TEXTURE_2D)
    bgl.glFlush()
    
self.n_id = node_id(self)
nvBGL2.callback_disable(self.n_id)


def simple_color_viewer_nvBGL(x, y, args):

    colors = args[0]
    tex = args[1]
    size = args[2]
    clr = args[3]
    
    idx=10
    coord = get_location(idx)
    tx = int(coord[0] + x)
    ty = int(coord[1] + y)

    width = int(size//2)
    height = int(size//2)
    width =64
    height = 64
    draw_pixels(x=tx, y=ty, w=width, h=height, format=clr, pixels=tex) 
    
socket = self.inputs['in_colors']
if socket.links:
    w= 64
    h= 64
    size = w = h
    total_size = w * h * 3
    data = np.array(in_colors).flatten()
    texture = bgl.Buffer(bgl.GL_FLOAT, total_size, data)
    clr = bgl.GL_RGB

    draw_data = {
        'tree_name': self.id_data.name[:],
        'mode': 'custom_function',
        'custom_function': simple_color_viewer_nvBGL,    
        'loc': (self.location[:]),
        'args': (socket.sv_get(), texture, size, clr)
    }

    nvBGL2.callback_enable(self.n_id, draw_data)

```

![draw_pixels](https://cloud.githubusercontent.com/assets/1275858/25179616/f8c7cd18-250a-11e7-9112-487a0cdfb8b6.png)

>i'm hoping @kalwalt will provide a feature on texture viewer to 'pad incoming' if expected does not match given

i hope me too... but no Eta.

**Comment by zeffii** [comment]
and a slightly buggy dynamic version:  https://gist.github.com/zeffii/a0763e196b0dde7d369a4b2da36f85c7

![tambo](https://cloud.githubusercontent.com/assets/619340/25181338/8aa59b60-2511-11e7-876e-1a5bddcbd811.gif)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25186627/04bbbcb8-2521-11e7-8513-edad49b322d5.png)

**Comment by zeffii** [comment]
![uhhhgif](https://cloud.githubusercontent.com/assets/619340/25194495/d9f5cf4a-253a-11e7-8e4c-19061b9f6803.gif)

**Comment by zeffii** [comment]
![huuugif](https://cloud.githubusercontent.com/assets/619340/25194519/ecabe7e6-253a-11e7-971c-5acfa6a743be.gif)

**Comment by kalwalt** [comment]
that's coool!!

**Comment by zeffii** [comment]
i think then.. then because it gets progressively smaller when the count increases that at some point it should just draw `bgl.glDrawPixels` ?

**Comment by kalwalt** [comment]
> i think then because it gets progressively smaller when the count increases that at some point it should just draw bgl.glDrawPixels ?

i think it always draw points (as geometry) you can have a confirm of this zooming in and out in the node tree view, instead with `bgl.glDrawPixels` the zooming has no effect because draw directly pixels intead of geometry.

**Comment by kalwalt** [comment]
I think that latest your script @zeffii  could be `Very Dangerous` in the right hands!!

**Comment by zeffii** [comment]
hehe :)  agreed

to be certain here what i mean is .. i want it to draw large squares for input that's small... and progressively get smaller...and still draw using GL_QUADS, then at some point switch over to drawing pixels.. maybe around 1024 (and yes.. i think that then becomes zoom-rate invariant )

**Comment by kalwalt** [comment]
> to be certain here what i mean is .. i want it to draw large squares for input that's small... and progressively get smaller...and still draw using GL_QUADS, then at some point switch over to drawing pixels.. maybe around 1024 (and yes.. i think that then becomes zoom-rate invariant )

now it's clear! 
maybe you can draw GL_QUADS and after only glVertex as points. But probably  drawing ad glDrawPixels is less consuming.

**Comment by zeffii** [comment]
i think i'll make this into a mode of stethoscope and slightly rewrite it. 

closing for now.
