### ISSUE TITLE
How does Matrix In and Matrix Out vectorization work?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1541]
Hard to explain, but if you open the Blend and test Matrix In and Matrix Out or when adding multiple Vector Position, we are not getting the usual vectorization.

![screen shot 2017-04-19 at 18 34 36](https://cloud.githubusercontent.com/assets/3952687/25170750/f3a213ec-252e-11e7-9894-fb808fd5b12d.png)
![screen shot 2017-04-19 at 18 34 29](https://cloud.githubusercontent.com/assets/3952687/25170752/f3db7736-252e-11e7-982b-84f35466a65c.png)
![screen shot 2017-04-19 at 18 34 25](https://cloud.githubusercontent.com/assets/3952687/25170753/f3dcdc34-252e-11e7-8cad-e8fac5fae038.png)
[random_qtown_city_006_2017_04_19_08_34.zip](https://github.com/nortikin/sverchok/files/932747/random_qtown_city_006_2017_04_19_08_34.zip)

**Comment by enzyme69** [comment]
List Join node in between Vector In and Matrix In works. I kind of understand what's going on. But still...

**Comment by enzyme69** [comment]
Same thing here, I need to split out the data.
![screen shot 2017-04-19 at 18 40 14](https://cloud.githubusercontent.com/assets/3952687/25170969/a68829e2-252f-11e7-8252-3a7f0ed59f11.png)

**Comment by zeffii** [comment]
`Matrix. 3`  means the data is at the minimum `[matrix, matrix, matrix]`. With that input the Matrix Out node generates `[[vector, vector, vector]]` (shows on the node as `Locations. 1` .

With list split you are forcing it to `[[vector],[vector],[vector]]` , which shows as `whateversocket. 3`.

A switch on the Matrix Out node to `autosplit` could be a nice UI feature..

**Comment by zeffii** [comment]
The only way you are going to be less suprised about how this works is if you use debugprint node or stethoscope..

not sure that's there's an actionable issue here.. or a question.

**Comment by enzyme69** [comment]
Understood, I shall watch debug and watch for

[[[][][]]]
[[]]
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
