### ISSUE TITLE
Marching_cubes with pymcubes, skimage and sverchok

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1549]
[Pymcubes](https://pypi.python.org/pypi/PyMCubes/0.0.6) is a python module with a marching cubes algorithm. In the simple example that i provide it simply plot a sphere. You can set the bounds, the number of samples in each dimension, and the iso surface level. The sphere is defined by the function `f`; of course you can use what function you desire. 
You must install the module in the python 3 location and then import it with the sys importing statement.

```python
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is mcubes
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes
```
change your path accordingly. 
to install pymcubes i used pip:

`pip3 install pymcubes`

it requires also pycollada and cython.

![pymcubes_test](https://cloud.githubusercontent.com/assets/1275858/25227328/5bffeac4-25c8-11e7-80ec-c421f06ef2f0.png)

```python
"""
in bounds s d=10 n=2
in iso_val s d=8.0 n=2
in samples s d=100 n=2
out vertices v
out triangles s
"""


import numpy as np
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is mcubes
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes

# Create the volume
def f(x, y, z):
    return x**2 + y**2 + z**2

# Create a data volume (30 x 30 x 30)
#X, Y, Z = np.mgrid[:100, :100, :100]
# u = (X-50)**2 + (Y-50)**2 + (Z-50)**2 - 25**2

# Extract the 0-isosurface
#verts, tri = mcubes.marching_cubes(u, 0)

# Extract the 16-isosurface
verts, tri = mcubes.marching_cubes_func(
        (-bounds, -bounds, -bounds), (bounds, bounds, bounds),  # Bounds
        samples, samples, samples,              # Number of samples in each dimension
        f,                          # Implicit function
        iso_val)                         # Isosurface value

vertices, triangles = verts.tolist(), tri.tolist()
```

you can take the script also [here](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/pymcubes/pymcubes_test.py)

**Comment by kalwalt** [comment]
![multi_schwarz](https://cloud.githubusercontent.com/assets/1275858/25229898/780c285e-25d2-11e7-82a4-787ca1d66f03.png)

multi schwarz ( i think it is called so...) with just a function call.
this is the formula used:

> `math.cos(x) + math.cos(y) + math.cos(z)`

notice the isovalue used ( do not use high values).

script [here](https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/pymcubes/pymcubes_multi_schwarz.py)

**Comment by kalwalt** [comment]
![hyperboloid](https://cloud.githubusercontent.com/assets/1275858/25230674/21d3a1b2-25d5-11e7-883a-9c427a534d91.png)
hyperboloid with function:

> `x**2 + y**2 - z**2 - 0.3`

**Comment by zeffii** [comment]
it can do metaballs? :)

**Comment by kalwalt** [comment]
> it can do metaballs? :)

maybe, i will try to add a set of multi spheres,...

**Comment by kalwalt** [comment]
Bingo!
![metaballs_test](https://cloud.githubusercontent.com/assets/1275858/25231093/c49d7c50-25d6-11e7-9971-d05c3fd98620.png)
 with this script:

```python
"""
in bounds s d=10 n=2
in iso_val s d=8.0 n=2
in samples s d=100 n=2
in factor s d=0.9 n=2
out vertices v
out triangles s
"""


import numpy as np
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is scipy
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes
import math

# Create the volume
def f(x, y, z):
    
    return ((x-factor)*(x-factor)+y*y+z*z-1)*((x+factor)*(x+factor)+y*y+z*z-1)-0.3

# Extract the 16-isosurface
verts, tri = mcubes.marching_cubes_func(
        (-bounds, -bounds, -bounds), (bounds, bounds, bounds),  # Bounds
        samples, samples, samples,              # Number of samples in each dimension
        f,                          # Implicit function
        iso_val)                         # Isosurface value

vertices, triangles = verts.tolist(), tri.tolist()

```

This only create two spheres but it can be developed a multi spheres version.

**Comment by kalwalt** [comment]
Scikit image module has also marching cubes functions http://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html
but i didn't tryed yet. I found this modules as possibles replacement for polyvox lib that i used before https://github.com/nortikin/sverchok/issues/1168 as this has some issues....

**Comment by zeffii** [comment]
i'd like to see an example of multi verts for metaballs. very cool stuff.

**Comment by kalwalt** [comment]
> i'd like to see an example of multi verts for metaballs. very cool stuff.

i will do later if i can.

**Comment by zeffii** [comment]
i think you're forgetting to wrap the final outputs..with `[ ]`   else you get thousands of verts/polygons.. lists..

**Comment by nortikin** [comment]
hm, will try at home just essentially needed stuff

**Comment by kalwalt** [comment]
> i think you're forgetting to wrap the final outputs..with [ ] else you get thousands of verts/polygons.. lists..

verts and tri are numpy arrray
vertices and triangles after are converted to lists:

```python
verts :  [[-2.11404321  0.          0.        ]
 [-2.         -0.31853448  0.        ]
 [-2.          0.         -0.31853448]
 [-2.          0.          0.31853448]
 [-2.          0.31853448  0.        ]
 [-0.1525      0.          0.        ]
 [ 0.1525      0.          0.        ]
 [ 2.         -0.31853448  0.        ]
 [ 2.          0.         -0.31853448]
 [ 2.          0.          0.31853448]
 [ 2.          0.31853448  0.        ]
 [ 2.11404321  0.          0.        ]]
tri :  [[ 2  0  1]
 [ 1  0  3]
 [ 2  4  0]
 [ 0  4  3]
 [ 1  5  2]
 [ 1  3  5]
 [ 5  4  2]
 [ 5  3  4]
 [ 8  6  7]
 [ 7  6  9]
 [ 8 10  6]
 [ 6 10  9]
 [ 7 11  8]
 [ 7  9 11]
 [11 10  8]
 [11  9 10]]
/n-------------
vertices :  [[-2.1140432098765434, 0.0, 0.0], [-2.0, -0.3185344827586205, 0.0], [-2.0, 0.0, -0.3185344827586205], [-2.0, 0.0, 0.31853448275862073], [-2.0, 0.31853448275862073, 0.0], [-0.1525, 0.0, 0.0], [0.15249999999999986, 0.0, 0.0], [2.0, -0.3185344827586205, 0.0], [2.0, 0.0, -0.3185344827586205], [2.0, 0.0, 0.31853448275862073], [2.0, 0.31853448275862073, 0.0], [2.1140432098765434, 0.0, 0.0]]
triangles :  [[2, 0, 1], [1, 0, 3], [2, 4, 0], [0, 4, 3], [1, 5, 2], [1, 3, 5], [5, 4, 2], [5, 3, 4], [8, 6, 7], [7, 6, 9], [8, 10, 6], [6, 10, 9], [7, 11, 8], [7, 9, 11], [11, 10, 8], [11, 9, 10]]

i think maybe  vertices can be converted to lists of tuples. Maybe vertices and triangles as you mentioned need one more nestness level?

```

**Comment by zeffii** [comment]
yeah just output   
```python
vertices, triangles = [verts.tolist()], [tri.tolist()]
``` 

 i think

**Comment by kalwalt** [comment]
ok thank you. I'm looking for the multi metaballs example.
one difficult is that the function `f` must be in the form `f(x, y, z)` as described in the struct of the `pywrapper.ccp`:
```c++
struct PythonToCFunc
{
    PyObject* func;
    PythonToCFunc(PyObject* func) {this->func = func;}
    double operator()(double x, double y, double z)
    {
        PyObject* res = PyObject_CallFunction(func, "(d,d,d)", x, y, z); // py::extract<double>(func(x,y,z));
        if(res == NULL)
            return 0.0;
        
        double result = PyFloat_AsDouble(res);
        Py_DECREF(res);
        return result;
    }
};
```
https://github.com/pmneila/PyMCubes/blob/master/mcubes/src/pywrapper.cpp#L8

**Comment by scorpion451** [comment]
anyone know a reason the script would fail to load mcubes on Windows? 
I swapped out the file path to "C:\Program Files\Python36\Lib\site-packages" but it keeps giving me an error about not being able to find mcube._mcube

**Comment by enzyme69** [comment]
So it supposedly capable of remeshing Particles into something meshy?
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
@scorpion451  i suspect the problem could also be a mismatch between python 3.5 and your 3.6

**Comment by kalwalt** [comment]
#### TorusIso
![pymcubes_torus](https://cloud.githubusercontent.com/assets/1275858/25270564/62855938-2681-11e7-94e7-60a42dc65bef.png)
```python
"""
in bounds s d=10 n=2
in iso_val s d=8.0 n=2
in samples s d=100 n=2
in r_i s d=5.0 n=2
in r_o s d=1.0 n=2
out vertices v
out triangles s
"""


import numpy as np
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is mcubes
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes
import math

# Create the volume
def f(x, y, z):
    
    # (sqrt(x*x+y*y)-3)^2+z*z-1 formula from MathMod
    res=(math.sqrt(x*x+y*y)-r_i)**2+z*z-r_o

    return res

# Extract the 16-isosurface

verts, tri = mcubes.marching_cubes_func(
    (-bounds, -bounds, -bounds), (bounds, bounds, bounds),  # Bounds
    samples, samples, samples,              # Number of samples in each dimension
    f,                          # Implicit function
    iso_val)                         # Isosurface value

vertices, triangles = [verts.tolist()], [tri.tolist()]

```

**Comment by kalwalt** [comment]
Testing the scikit marching cubes function:
![ellipsoid_skimage_test](https://cloud.githubusercontent.com/assets/1275858/25273573/a7e5f16c-268c-11e7-8b76-ac9f809c94c1.png)
Example taken from here:
http://scikit-image.org/docs/dev/auto_examples/edges/plot_marching_cubes.html
Skimage marching cubes documentation:
http://scikit-image.org/docs/dev/api/skimage.measure.html#marching-cubes
The script i used:
```python
"""
in sp s d=0.0 n=2
in iso_val s d=0.0 n=2
in step s d=1 n=2
in a s d=6 n=2
in b s d=10 n=2
in c s d=16 n=2
out vertices v
out faces s
"""


import numpy as np
import sys
scikit_path = r"/usr/local/lib/python3.5/dist-packages" # it depend on your OS but just paste the path where is scikit
if not scikit_path in sys.path:
    sys.path.append(scikit_path)
from skimage import measure
from skimage.draw import ellipsoid


# Generate a level set about zero of two identical ellipsoids in 3D
ellip_base = ellipsoid(a, b, c, levelset=True)
ellip_double = np.concatenate((ellip_base[:-1, ...],
                               ellip_base[2:, ...]), axis=0)

# Use marching cubes to obtain the surface mesh of these ellipsoids
verts, faces, normals, values = measure.marching_cubes(
    ellip_double, level=iso_val,spacing=(sp, sp, sp), step_size=step)

vertices, faces = [verts.tolist()], [faces.tolist()]


```
https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/skimage/ellipsoid_skimage.py

**Comment by scorpion451** [comment]
@kalwalt double checked, and I do have mcubes in my C:\Program Files\Python36\Lib\site-packages folder, with
```
exporter.py
__init__.py
_mcubes.cp36-win_amd64.pyd # .pyd is theoretically a "better dll" format for windows python
```

I just updated Python, so I'm going to try rolling back to 3.5, see if that makes difference.

**Comment by scorpion451** [comment]
Okay, so now that I've got it working and played with it for a while:
How can we make f = (interpolation/lerp/closest vertex/etc of an existing mesh)

**Comment by kalwalt** [comment]
> Okay, so now that I've got it working and played with it for a while:

@scorpion451 Happy, that you got it working!
> How can we make f = (interpolation/lerp/closest vertex/etc of an existing mesh)?

This is sure possible. Probably given the Bounding Box of the mesh you can calculate the distance of every vertex from the center of the BB, so finding the values for the marching cubes algorithm.  This is a feature that would fine have with Sverchok. but for now we can only develop some script or macro, because pymcubes can't be installed in blender python. I suggest also to try the scikit-image module as mentioned in a previous post in this issue. For now I'm testing the two modules to see what is more convenient to use.

**Comment by nortikin** [comment]
```
Unexpected error: <class 'ImportError'>
on line:  2
Traceback (most recent call last):
  File "/home/ololo/.config/blender/2.78/scripts/addons/sverchok/nodes/generator/script1_lite.py", line 348, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 16, in <module>
ImportError: No module named 'mcubes._mcubes'
```

**Comment by kalwalt** [comment]
@nortikin i think should match the python versions. Blender use python 3.5 (at least 2.78a) your system python installed  is as i can see 3.6.

**Comment by nortikin** [comment]
the same 3.6 problem, i see

**Comment by kalwalt** [comment]
if you can  you should intall python 3.5 on your system and after the` pymcubes module`

**Comment by nortikin** [comment]
```bash
Traceback (most recent call last):
  File "/home/ololo/.config/blender/2.78/scripts/addons/sverchok/nodes/generator/script1_lite.py", line 348, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 16, in <module>
ImportError: No module named 'mcubes._mcubes'
```
have now 3.5

**Comment by nortikin** [comment]
how to point blender on locan python?

**Comment by kalwalt** [comment]
@nortikin  now how is your `mcubes_path`?

**Comment by nortikin** [comment]
@kalwalt  r"/usr/lib/python3.5/site-packages/"

**Comment by nortikin** [comment]
```
  File "/usr/lib/python3.5/site-packages/mcubes/__init__.py", line 2, in <module>
    from ._mcubes import marching_cubes, marching_cubes_func
ImportError: No module named 'mcubes._mcubes'
```

**Comment by kalwalt** [comment]
try:
```diff
-r"/usr/lib/python3.5/site-packages/"
+r"/usr/lib/python3.5/site-packages"
```

**Comment by nortikin** [comment]
@kalwalt  the problem in clean python3.5 under bash also, the same. It is something with python itself
```
  File "/home/ololo/.config/blender/2.78/scripts/addons/sverchok/nodes/generator/script1_lite.py", line 348, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 16, in <module>
ImportError: No module named 'mcubes._mcubes'

```

**Comment by zeffii** [comment]
try doing the imports directly in the Blender text editor, maybe snlite is not showing the full Exception.

**Comment by kalwalt** [comment]
Are you saying that you have this problem also outside sverchok/Blender? Did you try the pymcubes example? and from a python3.5 idle what you get running `import mcubes`?

**Comment by nortikin** [comment]
```bash
ololo@ololo:~/Downloads/blender-2.78-linux-glibc211-i686/2.78$ python3.5
Python 3.5.3 (default, Apr 22 2017, 20:09:34) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mcubes
>>> 
```
it is ok

**Comment by kalwalt** [comment]
but your addon sverchok is in `.config/blender/2.78/scripts/addons/sverchok` my is in `home/walter/blender2,78/scripts/addons` could make a difference?

**Comment by kalwalt** [comment]
try to test the `import` in the blender python console.

**Comment by kalwalt** [comment]
with all the` import sys` stuff, of course.

**Comment by nortikin** [comment]
import from blender console couse: ```ImportError: No module named 'mcubes._mcubes'```

**Comment by kalwalt** [comment]
i would suggest to copy the `mcubes` folder to `/path/to/blender-2.78/2.78/python/lib/python3.5/site-packages` but i think it won't works because needs of `Cython`...

**Comment by nortikin** [comment]
import cython works, but not mcubes inside blender.
all numpy, scipy import works, manjaro linux fails with blender + mcubes (((

**Comment by kalwalt** [comment]
i'm sad for this maybe open an issue on pymcubes github.

**Comment by scorpion451** [comment]
What's your pythonpath set to? I could still launch blender when I had the path pointed to 3.6- I just got that error every time I tried to load mcubes. As soon as I changed my global pythonpath to 3.5 and installed mcubes there, everything worked fine,

**Comment by nortikin** [comment]
yes, it handles latest python, see now. 
Investigating dark side of linux now. numpy installation on python3.5 with pip go wrong, not see muiltiarray and so on

**Comment by kalwalt** [comment]
> Investigating dark side of linux now. numpy installation on python3.5 with pip go wrong, not see muiltiarray and so on

never had this problems in Ubuntu, that's really strange. 
But you installed with `sudo pip install`?
on Ubuntu64 for python3.5 should be `sudo pip3 install 'module'`

**Comment by nortikin** [comment]
used pip3.5 install pymcubes

**Comment by kalwalt** [comment]
Maybe pip it is not installing in the right location, try as suggested here
http://stackoverflow.com/questions/35261468/how-to-use-pip-with-python3-5-after-upgrade-from-3-4
`python3.5 -m pip install package`
If blender had the option to install at least with pip, this process should a lot easier and without isssues of this kind...

**Comment by nortikin** [comment]
changed yesturday the path in linux for python 3.5, o it uses site-packages 3.5, it fails import mcubes in bash also. so, mcubes or something installed wrong (maybe about environment verables was not set)

**Comment by kalwalt** [comment]
@nortikin i think it'is a issue related to path or the installation process. To be sure of the path where mcubes is:  run `pip show` pymcubes in the console. Could be also an issue with permissions or conflict with a previuos installation.

**Comment by kalwalt** [comment]
#### pymcubes with noise array
![image](https://cloud.githubusercontent.com/assets/1275858/25380219/c24986ec-29af-11e7-84df-94c864f23803.png)


```python
"""
in bounds s d=10 n=2
in iso_val s d=8.0 n=2
in noise s d=[] n=0
out vertices v
out triangles s
"""


import numpy as np
import random
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is scipy
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes



# Create a data volume
X, Y, Z = np.mgrid[:bounds, :bounds, :bounds]
n = np.array(noise)
u = np.reshape(n, (bounds,bounds,bounds))
v = Z * u

# Extract the 0-isosurface
verts, tri = mcubes.marching_cubes(v, iso_val)

vertices, triangles = [verts.tolist()], [tri.tolist()]
```
It's not the best solution but it something that very near to a terrain, To do this we need a 3d grid of points for create a 3d noise texture, we can't use a plane node to create that grid nor the box node so i used the range float nodes to vectorize, and after a list repeater. Maybe we can devekop a script for a grid mesh.

**Comment by zeffii** [comment]
@kalwalt  i made np grids a whileback.. https://github.com/nortikin/sverchok/issues/942#issuecomment-262976864

**Comment by kalwalt** [comment]
> @kalwalt i made np grids a whileback.. #942 (comment)
Good to know, this is exactly what i need!

**Comment by kalwalt** [comment]
![pymcubes_w_numpygrid_noise](https://cloud.githubusercontent.com/assets/1275858/25383266/996a4566-29bb-11e7-9047-313673bc0e72.png)
With your suggested script @zeffii , this is the result i was expecting! Wow!

**Comment by zeffii** [comment]
use the `A Number node` :)

`ctrl+space => nu`

![image](https://cloud.githubusercontent.com/assets/619340/25383539/da97c8fa-29bc-11e7-99a9-a39c97dd7275.png)

**Comment by zeffii** [comment]
(can output float and int)

**Comment by kalwalt** [comment]
This with a 64x64x64 grid:
![pymcubes_w_numpygrid_noise_64](https://cloud.githubusercontent.com/assets/1275858/25383615/2dca39ae-29bd-11e7-959b-035a29aaa9e7.png)
This only using a simple noise node, You can do more and more elaborate operations with the data before to be plugged in the voxelizer.

> use the A Number node :)

I always forgot to use it, i must remember...

**Comment by kalwalt** [comment]
another update:
![pymcubes_w_numpygrid_noise_64_01](https://cloud.githubusercontent.com/assets/1275858/25386828/fc61bd90-29c8-11e7-8fa5-54f3fc4b1739.png)
updated and improved script here:
https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/pymcubes/pymcubes_w_noise.py

**Comment by zeffii** [comment]
stick a plate of glass ontop of that and you got a copy table.

**Comment by kalwalt** [comment]
try also;
```python
# instead of multiplying
v = Z * u
# try yo add
v = Z + u
```

**Comment by kalwalt** [comment]
![pymcubes_w_numpygrid_noise_64_02](https://cloud.githubusercontent.com/assets/1275858/25388608/973c44c0-29ce-11e7-89d0-1b639d7db5b7.png)
I did this only changing:

```diff
-v = Z * u
+v = Z + u
```
and adjusting the isovalue, note the difference with the previous image.

**Comment by paulofalcao** [comment]
Cool stuff, if I also send normals / colors or others attributes per vertex, how can I use them in sverchok / blender ?

**Comment by kalwalt** [comment]
> Cool stuff, if I also send normals / colors or others attributes per vertex

Hi @paulofalcao, no pymcubes can't send normals or other vertex informations. Polyvox lib has this feature but the python bindings unfortunately not. I would update the bindings to the latest but Polyvox, the original lib in C++, is heavily templated and i don't feel very comfortable with.  

> how can I use them in sverchok / blender ?

i think you can do what you want with it. You can apply other nodes, baking in the scene and use all the modifiers and other blender tools.

**Comment by paulofalcao** [comment]
> i think you can do what you want with it. You can apply other nodes, baking in the scene and use all the modifiers and other blender tools.

Thanks, that's what I was trying to do with a simple a example like this:
```python

"""
in bounds s d=10 n=2
in iso_val s d=0.0 n=2
in samples s d=100 n=2
in sphere_size s d=5.0 n=2
out vertices v
out triangles s
out normals v
out colors v
"""


import numpy as np
import sys
mcubes_path = r"/usr/local/lib/python3.6/site-packages/PyMCubes-0.0.6-py3.6-macosx-10.11-x86_64.egg"  # it depend on your OS but just paste the path where is mcubes
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)
import mcubes
import math


# Signed Distance Function
def sdf(x, y, z):
    x = x + math.sin(y*2.0)*1.0
    res = math.sqrt(x*x + y*y + z*z) - sphere_size
    return res

def norm(p):
    e = 0.001
    v = sdf(p[0],p[1],p[2])
    return np.linalg.norm([v-sdf(p[0]+e,p[1],p[2]),
                           v-sdf(p[0],p[1]+e,p[2]),
                           v-sdf(p[0],p[1],p[2]+e)])

def cor(p):
    return [math.sin(p[0]*0.5)+0.5,
            math.sin(p[1]*0.7)+0.5,
            math.sin(p[2]*0.9)+0.5]

# Extract the 16-isosurface
verts, tri = mcubes.marching_cubes_func(
    (-bounds, -bounds, -bounds), (bounds, bounds, bounds),  # Bounds
    samples, samples, samples,            # Number of samples in each dimension
    sdf,                                  # Signed Distance Function
    iso_val)                              # Isosurface value

vertices = [verts.tolist()]
triangles =  [tri.tolist()]
normals = map(norm,vertices)
colors = map(cor,vertices)
```

**Comment by kalwalt** [comment]
@paulofalcao great! but colors and normals i think won't works as it is now.  Anyway you could plug into a viewer bmesh and a vertex color new to display the color information onto the mesh. But i will show you tomorrow, maybe opening another issue thread, as i have no time now

**Comment by paulofalcao** [comment]
@kalwalt, OK thanks. I was just playing around with these stuff :)

**Comment by nortikin** [comment]
consulted with pymcubes developer, i had blender 32 bit, system 64 bit, so it was not working )))

**Comment by kalwalt** [comment]
> consulted with pymcubes developer, i had blender 32 bit, system 64 bit, so it was not working )))

do you have tried with blender 64 bit now?

**Comment by nortikin** [comment]
yes, it importing ok

**Comment by enzyme69** [comment]
I would not mind a coffee shop with such futuristic furniture!

I think this 3D voxel mesher is what I need to meditate soon.

I always want it since Cycles can do volumetric.

-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
With difficulty:
- can install mcubes finally 
- numpy version was different, copy paste from outside into blender

Somewhat works: 
<img width="340" alt="screen shot 2018-02-06 at 11 04 49 pm" src="https://user-images.githubusercontent.com/3952687/35858899-2fa54496-0b92-11e8-999d-f554adc566ad.png">

```python
def heart(x,y,z):
    # some kind of heart 3D function
    
    res = 320 * ((-x**2 * z**3 -9*y**2 * z**3/80) + (x**2 + 9*y**2/4 + z**2-1)**3)
    return res
```

**Comment by zeffii** [comment]
also.. i can't get mcubes installed

if you want answers, paste / copy (not screenshot)  the output of a working SNLite piped into a Debug node, and SNLite that doesn't work

and by "doesn't work" i mean, it doesn't display anything for VDMK. also show the whole Error messages, but maybe not the parts of the message that repeat, or have already been printed earlier.

**Comment by zeffii** [comment]
also.. disconnect the VDMK2 when you connect the `debug print` node

**Comment by enzyme69** [comment]
@zeffii Yes, I think the issue was: data list was empty: [[]] --> this gives "int not iterable" error. By adjusting parameter, etc, I finally got something. 

False alarm.

**Comment by enzyme69** [comment]
<img width="422" alt="screen shot 2018-02-07 at 4 03 00 pm" src="https://user-images.githubusercontent.com/3952687/35899409-6298b03e-0c20-11e8-8a72-1ab7b2f14343.png">

**Comment by kalwalt** [comment]
hi @enzyme69  glad that you work with it ! pay attention to the iso values. As i remember it is very sensible. Sorry for my long delay here. I have no time to work or experimenting with sverchok and programming in general...

**Comment by nortikin** [comment]
![clouds3](https://user-images.githubusercontent.com/5783432/36116257-a5cf7de0-1046-11e8-823f-eabde0a08f9f.png)
![clouds2](https://user-images.githubusercontent.com/5783432/36116258-a605e83a-1046-11e8-8af7-0f4d6ecaccd0.png)
![clouds1](https://user-images.githubusercontent.com/5783432/36116259-a6357212-1046-11e8-9340-ad3934a55c35.png)

**Comment by nortikin** [comment]
![clouds4](https://user-images.githubusercontent.com/5783432/36116451-61363bbe-1047-11e8-944e-722882778be6.png)
(y**2 / math.sin(z*y) + 2**x)**2

**Comment by nortikin** [comment]
https://vk.com/wall-35076122_9416

**Comment by enzyme69** [comment]
What would be cool is a way to read or export Cycles Volumetric back into
Sverchok. Maybe OSL can help with this?
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by akalyan3** [comment]
import mcubes command generating the following error:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Users/adityak/anaconda2/envs/conda-python-blender/lib/python3.5/site-packages/mcubes/__init__.py", line 2, in <module>
    from ._mcubes import marching_cubes, marching_cubes_func
ImportError: cannot import name 'marching_cubes'

Any help would be appreciated!

**Comment by enzyme69** [comment]
@akalyan3 You need to ensure that the module is callable from inside Blender or Script node. 

Have you downloaded the PyMCubes module and install it into your computer and testing it using Python outside Blender? Ensuring also the Python version is good.

Then once it's good, you can call it using the lines mentioned above by @kalwalt 

```
import sys
mcubes_path = r"/usr/local/lib/python3.5/dist-packages" #it depend on your OS but just paste the path where is mcubes
if not mcubes_path in sys.path:
    sys.path.append(mcubes_path)    
import mcubes
```

**Comment by akalyan3** [comment]
@enzyme69 Thanks for that. That resolved the issue. But I ran into another one :P 
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Users/adityak/anaconda2/envs/conda-python-blender/lib/python3.5/site-packages/mcubes/exporter.py", line 29, in export_mesh
    vert_src = collada.source.FloatSource("verts-array", vertices, ('X','Y','Z'))
AttributeError: module 'collada' has no attribute 'source'

I'm trying to export a Schwarz.

**Comment by nortikin** [comment]
export? try other exporter from blender.
![mcubes6](https://user-images.githubusercontent.com/5783432/38782554-225d172c-40fe-11e8-914a-8e979e1f765d.png)
![mcubes5](https://user-images.githubusercontent.com/5783432/38782555-22c7f042-40fe-11e8-9269-d48ed12700d0.png)
![mcubes4](https://user-images.githubusercontent.com/5783432/38782556-22f09560-40fe-11e8-959c-f27bc61cc3b4.png)
![mcubes3](https://user-images.githubusercontent.com/5783432/38782557-2319da74-40fe-11e8-9172-d1e298ed4b21.png)
![mcubes1](https://user-images.githubusercontent.com/5783432/38782558-23431d80-40fe-11e8-9562-4c7c22bb4b7a.png)
