### ISSUE TITLE
Mask and other small conveniences

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1553]
from: https://github.com/nortikin/sverchok/issues/1552

##### Masks

>  Polygon Face Mask Selection needs a way to just do List Mask by providing index: 1,5,12, etc I know this can be done already the hard way. Just like if use give 1,5, and we compare with range 0-6, we get False, True, False, False, True, False.

Good point, I agree (and have touched on the subject in the past). This would be implemented per node, preferably using a utility function that turns a list of indices into a mask list. 

```python
def mask_list_from_indices(mask_indices, data_to_mask):

```

It should take both... and be able to determine automatically (if it encounters values in the mask list above 1..  so if it gets `0,0,0,01,1,1,1,0,0,0`, it does the regular thing.. but if it gets `1,5,12`, it knows that those are not booleans/onoff, and will generate `0,1,0,0,0,1,0,0,0,0,0,0,1`

##### Vector interpolation

A similar case can be made for vector Interpolation, rather than forcing us to pass float-lists between 0 and 1, the node can detect if we pass it an integer, it should generate the float-list by itself internally. If we pass it a 10, it should generate `0.0, 0.1 ..... 1.0` 

##### Lathe  (done  https://github.com/nortikin/sverchok/commit/cb11acc86e4f827e9f72662ec6ba5e72fc4f1844 )

interpret incoming Verts as sequential, if edges are not supplied.
```python
            if medges:
                if verts_match_edges or (idx <= len(medges) - 1):
                    final_values['edges'] = medges[idx]
            else:
                final_values['edges'] = [(i, i+1) for i in range(len(verts)-1)]

```

**Comment by portnov** [comment]
Btw, I had "mask convertor" node somewhere in my local repo; it can for example convert mask for faces into mask for vertices or vice versa.

**Comment by zeffii** [comment]
@portnov  great!

**Comment by Kosvor2** [comment]
There can be a node that converts masks to indexes and vice versa, instead of adding this function to each node.

![index_or_mask1](https://cloud.githubusercontent.com/assets/22656834/25270903/a4a54a66-269b-11e7-885f-19bf24a9fd3c.png)

**Comment by zeffii** [comment]
@Kosvor2 

well it would be sane to write such a utility function anyway, and implement it in the nodes that use masking.. and gradually retrofit current nodes that have masking.

**Comment by zeffii** [comment]
especially for new nodes.

**Comment by zeffii** [comment]
@Kosvor2  some kind of Mask Builder node totally makes sense

**Comment by Kosvor2** [comment]
https://github.com/nortikin/sverchok/commit/bf5a723619cf287f36da4b3822a95db60bcac425

**Comment by zeffii** [comment]
how about : https://github.com/nortikin/sverchok/commit/bf5a723619cf287f36da4b3822a95db60bcac425#commitcomment-21854949

![img](https://cloud.githubusercontent.com/assets/619340/25279158/d9c1a7ee-26a5-11e7-92cc-c5660096a759.png)

**Comment by portnov** [comment]
See #1555 .
