### ISSUE TITLE
Obj Edit Mode Enhancement?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1562]
I saw this **Obj Edit Mode** node. Looks like new to me. Never seen it before in this thread, not sure who made it, no documentation. It's a mystery.

I think this node is potentially useful to store some kind of "destructive edit". Ideally it would have:
- some kind of history of what index being edited, so that perhaps the node can pass whatever edit to another object, if assigned to multiple other objects.
- Object ID Out Slot

![screen shot 2017-04-22 at 19 23 36](https://cloud.githubusercontent.com/assets/3952687/25303192/3e2ce144-2791-11e7-9eea-976e31b8bce4.png)

Any idea? Thanks :)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25303235/e2c7caae-274e-11e7-974b-ede1d72506ca.png)

https://github.com/nortikin/sverchok/blob/master/nodes/scene/obj_edit.py  (me)

who asked for it?  you.
https://github.com/nortikin/sverchok/issues/1072

**Comment by zeffii** [comment]
i'm failing to see the need, but you are welcome to try convince me further in this thread.

closing for now

**Comment by enzyme69** [comment]
Yes, maybe having "history" is not really crucial for now. It can get weird if we are changing vertices. This can be simplified in many different way.

Strangely enough I have a feeling "Obj Edit" and "Mesh Expression" have similar or related philosophy. Or maybe not.

Future Wishlists:
- **Object Out** Mesh from Obj Edit
- **Object In** from Mesh Expresion @portnov 

![screen shot 2017-04-25 at 11 28 42](https://cloud.githubusercontent.com/assets/3952687/25365175/5eddc7d0-29aa-11e7-8919-4353a9371d89.png)
