### ISSUE TITLE
GText is broken, time to update

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1564]
Changes to Blender's Grease Pencil have resulted in a non working grease pencil text node.. no ETA, but it's on my radar.

**Comment by kalwalt** [comment]
I was going to open an issue for this but i I hesitated with a strange feeling that maybe  I just did not know how to use this node...

**Comment by zeffii** [comment]
if you think it's broken, but aren't sure. start the issue title as a question 'is X node broken - (feature Y fails, with errors)`. If it turns out to be broken, we rename the title and deal with it. Else we explain, and close fast.

**Comment by zeffii** [comment]
parking a few things here for later
```python
gp_data = ntree.grease_pencil
mpal = gp_data.palettes.new(name='delo')
m = mpal.colors.new()
m.color = (0.2, 0.9, 0.6)
```

**Comment by zeffii** [comment]
ok phase 1. it works.. but its still broken in places

![image](https://cloud.githubusercontent.com/assets/619340/25304926/9f15ff74-2771-11e7-8c21-ee2903a15eb9.png)

**Comment by zeffii** [comment]
setting colors coming up
![image](https://cloud.githubusercontent.com/assets/619340/25304936/c6897eaa-2771-11e7-8a00-13e7ec3651d4.png)

**Comment by zeffii** [comment]
formerly layers had a single color, now color is pushed per stroke

**Comment by zeffii** [comment]
almost able to push the patch.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25307061/fe880668-279a-11e7-8366-68ee93ab336c.png)

- Set  udpdate a current text  (use for when you've adjusted the color - it doesn't update realtime) 
- Clipboard icon will get and set from clipboard
- the `Font Size` does update immediately.

**Comment by zeffii** [comment]
that's all i'm prepared to do on this for now.

**Comment by kalwalt** [comment]
trying this now. i get blender crashing while try to past text into Gtext node, i get seg fault error, i let here the gist for the crash log.
https://gist.github.com/kalwalt/19539eee67e2a0231f1a4ecc1164a6a0
don't know if it makes a difference but i'm using blender 2.78a.

**Comment by zeffii** [comment]
Ok.. thats not good. Im using latest from builder.blender.org.

I might add a version test and disable it for lower revisions. Significant gp changes took place since 2.78a

**Comment by zeffii** [comment]
Ok.. thats not good. Im using latest from builder.blender.org.

I might add a version test and disable it for lower revisions. Significant gp changes took place since 2.78a
