### ISSUE TITLE
Save a sequence of images with sverchok nodes

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1566]
I would add to the Texture viewer node this feature, for now i'm experimenting with a simple script node:
```python
'''
in frame_current s d=0 n=2
in frame_start s d=0 n=2
in frame_end s d=4 n=2
in width s d=64 n=2
in height s d=64 n=2
in data s d=0.0 n=1
out some s 
'''

import bpy
import numpy as np

def assign_BW_image(image, buffer):
    # from sverchok redux, modified version
    np_buff = np.empty(len(image.pixels), dtype=np.float32)
    np_buff.shape = (-1, 4)
    np_buff[:, :] = np.array(buffer)[:, np.newaxis]
    np_buff[:, 3] = 1
    np_buff.shape = -1
    image.pixels[:] = np_buff
    return image

print('frame is: {0}\n'.format(frame_current))

image_name = 'test' + str(frame_current)
if data:
    img = bpy.data.images.new(name=image_name, width=width, height=height ,alpha=False,float_buffer=True)
    assign_BW_image(img, data)
   
    # img.filepath_raw = '/tmp/' + image_name
    path = '/tmp/' + image_name

    scene=bpy.context.scene
    scene.render.image_settings.file_format='PNG'
    image = bpy.data.images[image_name]
    if image.has_data:
        path = '/tmp/' + image_name + '.png'
        img.save_render(path, scene)
        if bpy.data.images[image_name].is_dirty:
            print('saved!')
        else frame_current == frame_end:
            bpy.ops.screen.animation_play()
    else frame_current == frame_end:
        bpy.ops.screen.animation_play()
        
     
```
this is my setup in the node tree:
![save_from_frame](https://cloud.githubusercontent.com/assets/1275858/25305975/0b6f9fb4-2785-11e7-9c78-e8058c16bf7f.png)
It save only 4 images by settting the fame end to 4. I started so for obviuous reason with a very small sequence.
the code:
  ```python
      else frame_current == frame_end:
            bpy.ops.screen.animation_play()
    else frame_current == frame_end:
        bpy.ops.screen.animation_play()
```
do nothing, it should stop the animation but it doesn't. Probably that part should implemented with a `try` cycle, 
These are the resulting saved images, note the first is completely black because `octave` is 0:

![test0](https://cloud.githubusercontent.com/assets/1275858/25306212/1c7fa5f2-2789-11e7-8082-84f973c9878d.png)
![test1](https://cloud.githubusercontent.com/assets/1275858/25306218/25a2b278-2789-11e7-84dd-9287aced0b18.png)
![test2](https://cloud.githubusercontent.com/assets/1275858/25306219/2aa1e92e-2789-11e7-99de-28af28fe1068.png)
![test3](https://cloud.githubusercontent.com/assets/1275858/25306223/2f89256a-2789-11e7-8896-6431192aa6f3.png)
![test4](https://cloud.githubusercontent.com/assets/1275858/25306226/34cf5bfc-2789-11e7-98ba-d3eef274c9e6.png)

**Comment by kalwalt** [comment]
code should be changed to:
```diff
-path = '/tmp/' + image_name
+path = '/tmp/' + image_name + '.png'
```

edited the first post to reflect this changes.

**Comment by kalwalt** [comment]
Another test:
#### Saving a simple circle animation.

![saving_a_circle_seq](https://cloud.githubusercontent.com/assets/1275858/25308628/41694910-27b9-11e7-9475-6ca6b9157fa3.png)

**skimage_circle.py**
```python
"""
in size s d=400 n=2
in center_x s d=100 n=2
in center_y s d=100 n=2
in radius s d=100 n=2
out pixels s
"""

import numpy as np
import sys
scikit_path = r"/usr/local/lib/python3.5/dist-packages" # it depend on your OS but just paste the path where is scikit
if not scikit_path in sys.path:
    sys.path.append(scikit_path)
from skimage.draw import (line, polygon, circle,
                          circle_perimeter,  circle_perimeter_aa,
                          ellipse, ellipse_perimeter,
                          bezier_curve)

# img = np.zeros((size, size, 3), dtype=np.double)
img = np.zeros((size, size), dtype=np.float32)
# fill circle
rr, cc = circle(center_x, center_y, radius, img.shape)

img[rr, cc] = 1.0

out = np.reshape(img, (4096,))

pixels = [out.tolist()]

```

**save_from_frame.py**

```python
"""
in size s d=400 n=2
in center_x s d=100 n=2
in center_y s d=100 n=2
in radius s d=100 n=2
out pixels s
"""

import numpy as np
import sys
scikit_path = r"/usr/local/lib/python3.5/dist-packages" # it depend on your OS but just paste the path where is scikit
if not scikit_path in sys.path:
    sys.path.append(scikit_path)
from skimage.draw import (line, polygon, circle,
                          circle_perimeter,  circle_perimeter_aa,
                          ellipse, ellipse_perimeter,
                          bezier_curve)

# img = np.zeros((size, size, 3), dtype=np.double)
img = np.zeros((size, size), dtype=np.float32)
# fill circle
rr, cc = circle(center_x, center_y, radius, img.shape)

img[rr, cc] = 1.0

out = np.reshape(img, (4096,))

pixels = [out.tolist()]

```

Result:

![circle0_](https://cloud.githubusercontent.com/assets/1275858/25308649/c62e436c-27b9-11e7-85c8-4ec73f1691ec.png)
![circle1_](https://cloud.githubusercontent.com/assets/1275858/25308650/d0517f26-27b9-11e7-92e8-8b6666827903.png)
![circle2_](https://cloud.githubusercontent.com/assets/1275858/25308653/d8195efe-27b9-11e7-8a97-3b07ab32414f.png)
![circle3_](https://cloud.githubusercontent.com/assets/1275858/25308656/dd6f4d32-27b9-11e7-84f1-6c09bae541b3.png)
![circle4_](https://cloud.githubusercontent.com/assets/1275858/25308658/e391c8ac-27b9-11e7-80d7-427486f4688d.png)
![circle5_](https://cloud.githubusercontent.com/assets/1275858/25308660/e8b167b6-27b9-11e7-9ed9-1ba1f79a88dc.png)
![circle6_](https://cloud.githubusercontent.com/assets/1275858/25308661/eca30532-27b9-11e7-92b2-57b0ce1889d7.png)
![circle7_](https://cloud.githubusercontent.com/assets/1275858/25308662/f15a215a-27b9-11e7-926a-afcd1dd01394.png)
![circle8_](https://cloud.githubusercontent.com/assets/1275858/25308663/f660136c-27b9-11e7-94c8-194ceae77add.png)

I think it is good for saving images for gif animations. Don't know if it will let save more robust animations.
Don't understand how to stop the animation from the code if i type in the blender console:

> `bpy.ops.screen.animation_play()`

it will stop the animation while the animation is running but this don't works in the script.

**Comment by enzyme69** [comment]
Cool!! Last time I saw something similar with Python is MoviePy module and Gizeh. I wonder if that can be ported to Python 3 properly.

Animated GIF within Sverchok, would be nice.

So far, I am using:
http://gifcreator.me

**Comment by enzyme69** [comment]
@kalwalt I am testing your SN Lite to generate this SciKit imagery, but getting weird error:

```
0 ('StringsSocket', 'size', 400, 2)
1 ('StringsSocket', 'center_x', 100, 2)
2 ('StringsSocket', 'center_y', 100, 2)
3 ('StringsSocket', 'radius', 100, 2)
Unexpected error: <class 'ValueError'>
on line:  224
Traceback (most recent call last):
  File "/Users/jimmygunawan/bsscript/addons/sverchok/nodes/generator/script1_lite.py", line 348, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 30, in <module>
ValueError: total size of new array must be unchanged

```

**Comment by kalwalt** [comment]
@enzyme69 This error should happens when the size of the array does not match between the two scripts,
check how they are.

**Comment by kalwalt** [comment]
also note this:
`out = np.reshape(img, (4096,))`
i reshape the array but if you change the size you must change the value.
better:
```diff
new_shape = size * size
- out = np.reshape(img, (4096,))
+ out = np.reshape(img, (new_shape,))
```

**Comment by kalwalt** [comment]
Progress with stop an animation, this script works:

```python
"""
in stop s d=1 n=2
out text s
"""

if stop == 0:
    bpy.ops.screen.animation_play()
    alert = "STOP"
    text.append(alert)
```
if you press the button play in the timeline it will stop with the zero value, and if you have plugged a `Note` node in the text socket it will display the alert 'STOP'

**Comment by kalwalt** [comment]
```python
 if image.has_data:
        print('preparing')
        path = '/tmp/' + image_name + '.png'
        img.save_render(path, scene)
        if frame_current == 8:
            bpy.ops.screen.animation_play()
        elif bpy.data.images[image_name].is_dirty:
            print('saved!')

    elif frame_current == 8:
        bpy.ops.screen.animation_play()
```

This stop the animation when frame is == 8 but not all frames(images) are saved correctly (some are empty,,,)

**Comment by kalwalt** [comment]
```python
    if image.has_data:
        print('img-data : ', image.has_data)
        print('preparing')
        frame_current = scene.frame_current # to be sure of the frame...
        while frame_current < frame_end:
            print('frame is: {0}\n'.format(frame_current))
            path = '/tmp/' + image_name  + str(frame_current) + '.png'
            print(path)
            img.save_render(path, scene)
            print('saved!')
        if frame_current > frame_end:
            print('stop')
```
Trying to use  a while loop instead.
@zeffii this while loop seems not getting update; `frame_current` is always 0 when animation is playing. should i use another approach bu i haven't idea.

**Comment by kalwalt** [comment]
Maybe now i get it! soon an update...

**Comment by kalwalt** [comment]
No, still no success this is even worste:
```python
'''
in frame_current s d=0 n=2
in frame_start s d=0 n=2
in frame_end s d=4 n=2
in width s d=64 n=2
in height s d=64 n=2
in data s d=0.0 n=1
out some s
'''

import bpy
import numpy as np


def assign_BW_image(image, buffer):
    # from sverchok redux, modified version
    np_buff = np.empty(len(image.pixels), dtype=np.float32)
    np_buff.shape = (-1, 4)
    np_buff[:, :] = np.array(buffer)[:, np.newaxis]
    np_buff[:, 3] = 1
    np_buff.shape = -1
    image.pixels[:] = np_buff
    return image

image_name = 'circle' + '_'

if data:

    scene = bpy.context.scene
    scene.render.image_settings.file_format = 'PNG'
    image = bpy.data.images[image_name]

    if image.has_data:
        print('img-data : ', image.has_data)
        print('preparing')

        while frame_current <= frame_end:
            print('frame is: {0}\n'.format(frame_current))
            path = '/tmp/' + image_name  + str(frame_current) + '.png'
            print(path)
            img = bpy.data.images.new(name=image_name, width=width, height=height,
                                      alpha=False, float_buffer=True)

            assign_BW_image(img, data)
            if image.has_data:
                img.save_render(path, scene)
                print('saved!')
                frame_current += 1

        if frame_current == frame_end:
            print('stop')

        #bpy.ops.screen.animation_play()

```
This code saves all the frames but always the same  number frame ... it save 8 frames (circle_0.png, ....circle_8.png) but all the same the first or the eight frame.

**Comment by zeffii** [comment]
`frame_current += 1`

i think just updates the variable , not actually `scene.frame_current`.

**Comment by kalwalt** [comment]
I added `frame_current += 1` in the while loop because `frame_curren`t wasn't getting updated.  
but maybe for this kind of things `script_lite node` is not the right approach.

**Comment by zeffii** [comment]
`while frame_current <= frame_end:`

i think you just want an `if frame_current <= frame_end` . On each framechange (if  the animation is playing) the body of the if statement gets executed then..

it's a little late in the day to explain this :/

**Comment by kalwalt** [comment]
```python
'''
in frame_current s d=0 n=2
in frame_start s d=0 n=2
in frame_end s d=4 n=2
in width s d=64 n=2
in height s d=64 n=2
in data s d=0.0 n=1
out some s
'''

import bpy
import numpy as np


def assign_BW_image(image, buffer):
    # from sverchok redux, modified version
    np_buff = np.empty(len(image.pixels), dtype=np.float32)
    np_buff.shape = (-1, 4)
    np_buff[:, :] = np.array(buffer)[:, np.newaxis]
    np_buff[:, 3] = 1
    np_buff.shape = -1
    image.pixels[:] = np_buff
    return image

image_name = 'circle' + '_'

if data:

    scene = bpy.context.scene
    scene.render.image_settings.file_format = 'PNG'
    path = '/tmp/' + image_name  + str(frame_current) + '.png'
    print(path)
    img = bpy.data.images.new(name=image_name, width=width, height=height,
                                      alpha=False, float_buffer=True)

    assign_BW_image(img, data)
    image = bpy.data.images[image_name]

    if image.has_data:
        #print('img-data : ', image.has_data)
        print('preparing')

        if frame_current <= frame_end: 
            print('frame is: {0}\n'.format(frame_current))
            
            if img.has_data:
                img.save_render(path, scene)
                print('saved!')

        if frame_current == frame_end:
           
            print('stop')
            bpy.ops.screen.animation_play()

```
You mean something like this. This code stop the animation when `frame current == frame_end` but not save all the frames: two are saved correctly the other are 0 byte files. A similar result i already had, Probably there are some method for image handling that i don't know that is required to save the images correctly.

**Comment by zeffii** [comment]
doesn't scipy have good png writing api?

**Comment by kalwalt** [comment]
>  doesn't scipy have good png writing api?

Yes it has. It is based on Pillow(PIL) module. It icould be an idea; the downside is that is an outside module and could be a source of issues for other users. 
But i will look into it, Thank for the input @zeffii

**Comment by zeffii** [comment]
there comes a point where the Blender only route gets in the way of progress.

but regardless
```python
    img = bpy.data.images.new(name=image_name, width=width, height=height,
                                      alpha=False, float_buffer=True)

    assign_BW_image(img, data)
    image = bpy.data.images[image_name]

```
isn't that the same as 
```python
    params = dict(name=image_name, width=width, height=height, alpha=False, float_buffer=True)
    image = bpy.data.images.new(**params)
    assign_BW_image(image, data)
```

**Comment by kalwalt** [comment]
i will give a try again! Thanks

**Comment by zeffii** [comment]
##### regarding external modules. 

In snlite scripts that aren't part of the main Sverchok distro, i encourage you to write those scripts in a way that is most convenient to you (its main user) primarily. 

##### but...
Alternatively, we could add a few bw/rgb/rgba writing routines to a place like `sverchok.utils.sv_image_writing.py` -- it does appear that using the `save_render` method on images isn't working for you.

I think what I would do is avoid the `image.save_render` method entirely.

**Comment by kalwalt** [comment]
It seems that injecting the params all the frames are saved correctly! But i need to do more testing to be sure fo this.

> regarding external modules.

yes you are right but i would also do this as a potential upgrade for the Texture viewer or another node related.

>but...

This could be a nice idea, but wait for this until we are not sure.

**Comment by kalwalt** [comment]
latest here: https://github.com/kalwalt/sverchok_nodes_collection/blob/master/scripts/save_from_frame.py

**Comment by zeffii** [comment]
```diff
-    image = bpy.data.images[image_name]
```
:)  it's unused because the fist time you obtain a reference to the image, stays a valid image refer until you're done.

**Comment by zeffii** [comment]
we are permitted to use http://stackoverflow.com/a/19174800/1243487 btw with credit to the SE link ( i asked ideasman42 just in case )

so if you want you can generate bw/rgb/rgba numpy versions of that :)   else I will.. actually i might do that anyway, it's been a while since i abused a png from code.

**Comment by kalwalt** [comment]
> so if you want you can generate bw/rgb/rgba numpy versions of that :) else I will.. actually i might do that anyway, it's been a while since i abused a png from code.

ok i will open a pull request, not immediately. but i will do.

**Comment by kalwalt** [comment]
look at this:
https://github.com/WarrenWeckesser/numpngw/blob/master/numpngw.py#L969
 `Write an APNG file from a sequence of numpy arrays.`

**Comment by zeffii** [comment]
closing till you find time again.
