### ISSUE TITLE
Simple Deformation Error and Wishlist

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1567]
![screen shot 2017-04-23 at 10 30 46](https://cloud.githubusercontent.com/assets/3952687/25309400/09e224ce-2810-11e7-961e-f081d7b8301a.png)

I tested Simple Deformation, and it seems to be intuitive and work great.

Few things I noticed:
- Bend does not like zero value for angle. Maybe this should be allowed?
- The node does not do vectorization yet, but this is future wishlist.

And, I wonder if we can have some kind of "**_axis visualization_**" for this kind of node, that would be pretty helpful I think?

![screen shot 2017-04-23 at 10 33 14](https://cloud.githubusercontent.com/assets/3952687/25309419/48ac9298-2810-11e7-8462-1f501b64fee7.png)

![screen shot 2017-04-23 at 10 34 02](https://cloud.githubusercontent.com/assets/3952687/25309426/6406bf28-2810-11e7-9348-dbe723f5f4ca.png)

**Comment by portnov** [comment]
About axis visualization: you can plug Matrix to Viewer 3D (not plugging other inputs), it will show something. Doesn't it help?

**Comment by zeffii** [comment]
or a `matrix_viewer`. with start and end colors (so you get a different dashed line color for each matrix to help you distinguish)

**Comment by enzyme69** [comment]
@portnov @zeffii Yes! This will become a nice accidental thing.

**Comment by zeffii** [comment]
I do not think the deform node should take care of matrix drawing, because then that's limited to only that node. better we provide a nicer alternative to the Viewer draw, something lite-weight

**Comment by enzyme69** [comment]
![screen shot 2017-04-23 at 17 44 59](https://cloud.githubusercontent.com/assets/3952687/25311756/a34e89c2-284c-11e7-93e7-2076260b5638.png)

Empty Magic.

**Comment by enzyme69** [comment]
[bendy_001_2017_04_23_08_07.zip](https://github.com/nortikin/sverchok/files/949550/bendy_001_2017_04_23_08_07.zip)

I am actually a bit confused with the setup above. Maybe I create accidental Double Deformation. I don't know how to parent matrix or inverse matrix in Sverchok. Maybe need Parent Node?

I recall in another 3D package (Maya), it is kind of nice to bring user control in 3D view. So if we have Cyclinder, and create deformation, normally parenting Deformation under Cylinder Matrix will create a setup for animator to move around the cylinder, and have bendy2 still working from that pivot.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25312356/66a41ba2-2817-11e7-8992-2b8a26fddd36.png)

**Comment by portnov** [comment]
About vectorization: just try to plug "range float" via "list split" with size=1. The question is, what you gonna do with result...

**Comment by zeffii** [comment]
error was fixed : https://github.com/nortikin/sverchok/commit/d6b541a208fa23dfdd8060e6739c1bd940905092

as for a wishlist...meh.

**Comment by enzyme69** [comment]
Thanks! :-))
