### ISSUE TITLE
Ordering of Vertex Index based on connected edges?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1573]
Not sure how to explain this.

I am using Linus BTrace KDTree Script node to get a single line that is going through all the vertices and getting result I wanted. 

[bspline_trace_001_2017_04_24_01_16.zip](https://github.com/nortikin/sverchok/files/950206/bspline_trace_001_2017_04_24_01_16.zip)
![screen shot 2017-04-24 at 11 15 58](https://cloud.githubusercontent.com/assets/3952687/25319297/a04c0860-28df-11e7-92f1-4b4cbf7437b6.png)

The lines bakes fine as Polygon Edge. But if I just plug it into Polyline Viewer, it generates a totally different result. Because with Polyline, I think it does not care about edges, just the order of the index of vertices.

However, if I bake Polygon Edge, and then convert to Curve, and I get result I want, everything is correctly ordered.

Is there a trick in Sverchok to re-order Vertices based on the Edge connection? Kind of like:
- This is first and last points
- sort everything in between.

@nortikin any idea?

**Comment by zeffii** [comment]
> if I bake Polygon Edge, and then convert to Curve, and I get result I want, everything is correctly ordered.

Blender's `Mesh -> Curve` operator does some magic. You'd be able to show this more comprehensibly by using a Icosphere with far fewer verts, that way you can see with IndexViewer is the new sorting is edge index dependant or not.

**Comment by zeffii** [comment]
@nortikin  make a small script that sorts vetices based on the edge sequence, it's profiles .. but it might just work for this. (it's a SN1 script.. look in nikita's folder)  'vertex sorting for profile' (or something similar

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25329797/a0059756-28dd-11e7-9384-5a687e30e930.png)

**Comment by zeffii** [comment]
snlite version : 
```python
"""
in in_verts v
in in_edges s
out vout v
out eout s
"""


def dodo(verts, edges, verts_o,k):
    for i in edges:
        if k in i:
            # this is awesome !!
            k = i[int(not i.index(k))]
            verts_o.append(verts[k])
            return k, i
    return False, False

if in_verts:
    for edges,verts in zip(in_edges, in_verts):
        ed = 1
        edges_o = []
        verts_o = []
        k = 0
        while True:
            k, ed = dodo(verts, edges, verts_o,k)
            if ed:
                edges.remove(ed)
            if not ed:
                break
        edges_o = [[k,k+1] for k in range(len(verts_o)-1)]
        edges_o.append([0, len(verts_o)-1])
        eout.append(edges_o)
        vout.append(verts_o)
```

**Comment by zeffii** [comment]
The Object `Mesh->Curve` operator (if you inspect the result carefully) generates multiple curves for Suzanne. 

![image](https://cloud.githubusercontent.com/assets/619340/25331101/23064750-28e2-11e7-9fcf-034627cc27c8.png)


The BTrace KDTree routine doesn't do that,

**Comment by nortikin** [comment]
long time it must to became separate node

**Comment by nortikin** [comment]
and it fails with non manifold and  cycled mesh, not suits for suzanne

**Comment by zeffii** [comment]
but btrace kdtree scriptnode produces a single vert+edge sequence, that connects all verts at least 1 time and never more than 2 times.

**Comment by zeffii** [comment]
nice bit of bmesh here

##### bmesh verts sort.py

```python
"""
in in_verts v
in in_edges s
out vout v
"""


from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata

for verts, edges in zip(in_verts, in_edges):
    bm = bmesh_from_pydata(verts, edges, [])
    
    idx_start = -1
    
    # find the vertex that only lies on one edge
    for v in bm.verts:
        if len(v.link_edges) == 1:
            idx_start = v.index
            break
    
    # seems this set of verts / edges is not usable
    if idx_start == -1:
        continue
    
    bm.verts.ensure_lookup_table()

    final = 20
    v1 = bm.verts[idx_start]
    e1 = v1.link_edges[0]
    v1.select = True
    e1.select = True
    
    get_verts = []
    get_verts.append(v1.co[:])
    while True:
        
        v1 = e1.other_vert(v1)
        pot_edges = v1.link_edges[:]
        get_verts.append(v1.co[:])
        
        if len(pot_edges) == 1:
            # at the end!
            break
        elif len(pot_edges) > 2:
            break
        elif len(pot_edges) == 2:
            selects = [e.select for e in pot_edges]
            if selects == [0, 1]:
                e1 = pot_edges[0]
            elif selects == [1, 0]:
                e1 = pot_edges[1]
            else:
                break
            e1.select = True
        
        v1.select = True
    vout.append(get_verts)    
        
  ```  

not extensively tested, but expects to find a start and a finish, and will return a list of verts that traverses the edgeloop.

- No vert shall be used by more than 2 edges
- it shall find at least 1 vert that has onle one `edge_links`

##### Sverchok Saucage

![image](https://cloud.githubusercontent.com/assets/619340/25346888/5c3bf768-2919-11e7-887f-7d0a75681c74.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/bmesh_verts_sort_mode1.py

**Comment by enzyme69** [comment]
![screen shot 2017-04-25 at 11 53 17](https://cloud.githubusercontent.com/assets/3952687/25365702/cff0b920-29ad-11e7-9d40-791470350370.png)

@zeffii Sverchok Sausage logo.

**Comment by nortikin** [comment]
only dog holders can appreciate
