### ISSUE TITLE
Polyline Radii Control Over Easing of Stroke

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1574]
![screen shot 2017-04-24 at 11 51 20](https://cloud.githubusercontent.com/assets/3952687/25319759/7abb04d4-28e4-11e7-996b-af2a38a95718.png)

I have grease pencil stroke and currently thinking of way to make the strokes less "even" and have some kind of variation of thickness. But I wanted it to be automatic.

Thin - Thick until max thickness - Thin

Maybe this is something to do with Ease function and clamping?

Rewording:
What is the easiest math function that does this Ease In - Hold.... - Ease Out. >> Animator terminology. Maybe more or less like SNAKE.

Head - body - Tail >> Snake eats and body gets longer.

**Comment by enzyme69** [comment]
![screen shot 2017-04-24 at 11 56 04](https://cloud.githubusercontent.com/assets/3952687/25319844/03ac9a1e-28e5-11e7-96ef-c69323415804.png)

Easier to draw.

I mean, it's easy to make Float Range 0 .. 1 but to make it 0..1 + 1..1 + 0..1 ? Confusing.

**Comment by enzyme69** [comment]
This is an app on iPad (Adobe Draw) and the stroke has nice easing...

![grease_ease](https://cloud.githubusercontent.com/assets/3952687/25320010/7c9c305a-28e6-11e7-9392-8dd927fd81f7.gif)

**Comment by zeffii** [comment]
>  it's easy to make Float Range 0 .. 1 but to make it 0..1 + 1..1 + 0..1 ?

try something

**Comment by enzyme69** [comment]
This also useful, looking at it now:
https://github.com/nortikin/sverchok/issues/695#issuecomment-275868417

**Comment by enzyme69** [comment]
Still a little weird, but I think one step forward.

https://gist.github.com/a77c29df03bcb2f7eb20afcacfb70c5d

![screen shot 2017-04-24 at 16 16 16](https://cloud.githubusercontent.com/assets/3952687/25324466/5fa2f236-2909-11e7-92fe-ef0c4f634f5b.png)
![screen shot 2017-04-24 at 16 16 10](https://cloud.githubusercontent.com/assets/3952687/25324467/5fde306c-2909-11e7-86e0-20e4339aeab0.png)
![screen shot 2017-04-24 at 16 16 09](https://cloud.githubusercontent.com/assets/3952687/25324468/5fde5ace-2909-11e7-81c4-e6e90c1ae36e.png)

**Comment by zeffii** [comment]
i'm with you on this one. i am tempted to make a `parametric ramp` node. that takes an incoming float range (0....1) and outputs such a `ramp up -- level -- ramp down` output. There are many other scenarios where this can be useful.

**Comment by enzyme69** [comment]
Yes, some kind of Gradient Ramp curve would be nice.

This I just made during live noding:
https://gist.github.com/26ef1ba912e79183ccd85d55fb99a033

Your abs(x) thing works.

It seems to be dependant on Curve Points Strokes, so I really should use the Resampling thing from Nikitron.

Maybe: 
SV Ramp like Attack, Decay, Sustain and Release (ADSR)

![screen shot 2017-04-24 at 17 39 05](https://cloud.githubusercontent.com/assets/3952687/25326771/f27bba60-2914-11e7-81b8-109cd3bf81fd.png)

**Comment by enzyme69** [comment]
Nothing too urgent this can be "hacked" just be drawing the curve and resampling that.

**Comment by zeffii** [comment]
> SV Ramp like Attack, Decay, Sustain and Release (ADSR)

indeed, that's all this is.

`mode 1` parametric A   (A..because there could be more implementations... B..C..D..etc)
- Attack (shape, duration in %) 
- Sustain (level, duration in %)
- Decay (shape, duration in % )

`mode 2` resample from input shape  (like bevel radius of a curve can be controlled via another curve..)

**Comment by zeffii** [comment]
multi sampling:

![image](https://cloud.githubusercontent.com/assets/619340/25381878/bc74fd7c-29b5-11e7-93ce-4313858ebe6c.png)
