### ISSUE TITLE
Object In Lite does not update Matrix on frame update?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1576]
Just like the title. I am wondering if this can be optional?

I tested the > ObjInLite + Viewer Draw and it works, but I realized the Object In Lite does not update the Matrix Transformation even when frame is running. Is this by design? 

![screen shot 2017-04-24 at 20 03 03](https://cloud.githubusercontent.com/assets/3952687/25332262/1e0a2cc0-2929-11e7-8efd-d09ecf9ef89a.png)

Can it be optional thing?

**Comment by zeffii** [comment]
it could.. but i want snlite to remain this way Just braindead pickup an object _once_.

But you can do it other ways.

- use `> objs vd ` instead, that uses `objects in 3`.
- use Get/Set prop node

   ![image](https://cloud.githubusercontent.com/assets/619340/25333155/83161560-28e9-11e7-8eea-9067660f5a9a.png)

**Comment by zeffii** [comment]
there is space for one icon-based button in the interface... i'll think about it.
