### ISSUE TITLE
Operator to center a 3d View on the output of any viewer node (and subset)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1578]
i've put this off for too long. One of the things that annoys me most about the GL viewer is you can't quicky focus a 3dview on an object and rotate it around, because there's nothing to click on. 

i propose an operator that pops up a menu of the current bgl viewer nodes, and each has a dropdown for the indices of the vertex inputs lists ( so if 4 sets of vertlists are being input you can pick any of those to focus on) ...  If there are hundreds of vertlists you probably are faster using the 3d cursor to find a pivot point.

**Comment by portnov** [comment]
Maybe just calculate center (average) of all vertices?

**Comment by zeffii** [comment]
probably, post matrix.

**Comment by DolphinDream** [comment]
I miss this feature too. I usually create an empty I can grab in the viewport to view selected. Could a random selection of some points to average and get an approximate Center work?

**Comment by zeffii** [comment]
yeah, i think pick every nth coordinate and average of them... if doesn't need to be super precise. Most of the code is ready for this (implemented in BCPrompt... a different add-on) just need to port it over.

just parking this here so I won't forget to do it.

**Comment by zeffii** [comment]
![3dvgif](https://cloud.githubusercontent.com/assets/619340/25485919/da4ffc06-2b5f-11e7-82c2-46afc741e1d6.gif)
https://github.com/nortikin/sverchok/pull/1591

**Comment by zeffii** [comment]
further discussion in the PR
