### ISSUE TITLE
CSG Boolean MK2 on Suzanne: BMesh / Carve mode?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1583]
I am testing this scenario with nested boolean @Kosvor2  : Suzanne Head + many Planes with Thickness.

[boolean_experiment_002_2017_04_26_07_09.zip](https://github.com/nortikin/sverchok/files/957521/boolean_experiment_002_2017_04_26_07_09.zip)

Apparently it failed:
_Node CSG Boolean 2 had exception maximum recursion depth exceeded_

If I use Suzanne head with Cylinder or Box, simple objects works.
---

I tested with the manual way and it works if I use _BMesh_ option instead of _Carve_. Carve mode failed with Suzanne.

![screen shot 2017-04-26 at 17 06 04](https://cloud.githubusercontent.com/assets/3952687/25422127/1ba81354-2aa3-11e7-8866-88b57c530753.png)
![screen shot 2017-04-26 at 17 05 55](https://cloud.githubusercontent.com/assets/3952687/25422129/1be3e94c-2aa3-11e7-96bd-69e3b5204f21.png)

Does the Sverchok Boolean node have this option to choose?

**Comment by zeffii** [comment]
nope. CSG Node is implemented in python, the Blender boolean is implemented in C++/C  and does not have any bmesh bindings.

**Comment by zeffii** [comment]
I did ask ideasman42 for bmesh.ops interface for the boolean functions, and he didn't oppose it.. but didn't want to do it himself.

so if we have any C++/C coders readings this. you could really help Sverchok (and bpy scripters in general) if you added this.

**Comment by zeffii** [comment]
if you have to make compex geometry from booleans, do it all in Blender and import the result using `obj in`   it will be much ... much ..faster

**Comment by zeffii** [comment]
i want to point out that the math involved in doing booleans on objects that are not 'water tight' tends to result in unpredictable meshes.. so of all example meshes, Suzanne is probably one of the worst for booleans.

**Comment by zeffii** [comment]
dont cut with just a single polygon plane / quad,  subdivide it

![image](https://cloud.githubusercontent.com/assets/619340/25424729/bace1c24-2a69-11e7-883e-142537444bbf.png)

**Comment by enzyme69** [comment]
Thanks for this detailed answers, Zeffii, I understand.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
