### ISSUE TITLE
Problem with export/import group node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1584]
@ly29 
1. Before import 2. After import 3. After rename
That they became bigger is not problem :P

![2017-04-25_16-16-46](https://cloud.githubusercontent.com/assets/28003269/25384983/6c668efe-29d3-11e7-8006-9c9c3569542e.png) ![2017-04-25_16-17-34](https://cloud.githubusercontent.com/assets/28003269/25384990/75d235ce-29d3-11e7-8309-ddff05288427.png) ![2017-04-25_16-19-13](https://cloud.githubusercontent.com/assets/28003269/25385002/7feeceb4-29d3-11e7-858e-ef1ecc2e3689.png)

**Comment by zeffii** [comment]
in case @ly29  doesn't have time to respond, i would like you to make a small .blend to demonstrate the issue using the least amount of possible. and describe the steps exactly to reproduce the problem.

**Comment by zeffii** [comment]
in case @ly29 doesn't have time to respond, i would like you to make a small .blend to demonstrate the issue using the least amount of nodes and energy as possible. and describe the steps exactly to reproduce the problem.

**Comment by zeffii** [comment]
you can link zipped .blends here by dragging a zip into the issue tracker

**Comment by Durman** [comment]
@zeffii 
![iport group node](https://cloud.githubusercontent.com/assets/28003269/25426374/f364344a-2a7f-11e7-9eeb-8cc30fdb3e31.gif)
[group node_2017_04_26_08_55.zip](https://github.com/nortikin/sverchok/files/957762/group.node_2017_04_26_08_55.zip)

**Comment by zeffii** [comment]
OK, i see. thank you.   No ETA btw.

**Comment by zeffii** [comment]
just to be clear... the Monad itself still works, but the UI is not showing the correct property anymore.

**Comment by zeffii** [comment]
i'm pretty sure this worked at one point, but I don't see any reasons for this (yet)

**Comment by Durman** [comment]
@zeffii 
It is not comfortable to use when the node have many inputs.
![2017-04-26_15-01-06](https://cloud.githubusercontent.com/assets/28003269/25431373/6c212c42-2a91-11e7-8835-822ae7b56835.png)

**Comment by zeffii** [comment]
@Durman  i appreciate that.. and agree fully. Monad's are easily the most complicated code in Sverchok, it can take a while to get back into debug mode ( "wrap brain around them ")

**Comment by enzyme69** [comment]
I used it a couple of time, it has always been like this. I think. Maybe
best is to load nodetree from Blend?

**Comment by zeffii** [comment]
it looks like `prop_name=    ` isn't assigned after import.

**Comment by zeffii** [comment]
the info is stored in `node.input_template` , but it seems that the node's bl_idname is no longer switched. from generic to dynamically generated.

```
import bpy

nodes = bpy.data.node_groups['Imported_name'].nodes
n = nodes['Monad.001']

for idx, socket_data in enumerate(n.input_template):
    n.inputs[idx].prop_name = socket_data[2].get('prop_name', '')

```

that should have worked.. i think.

**Comment by zeffii** [comment]
when you make a monad initially, this is what it makes
![image](https://cloud.githubusercontent.com/assets/619340/25434191/aa10d7f6-2a8b-11e7-98ed-9f141d0a7cc0.png)

the number at the end shows you that the monad's bl_idname is generated dynamically, and this will update each time you change sockets on the monad. 

but what's happening on the import, is that the bl_idname is first initialized as a generic monad node, and it is then told to "shapeshift" into a dynamically created node. But it doesn't appear to be doing the shapeshift : / 

![image](https://cloud.githubusercontent.com/assets/619340/25434300/0eee354c-2a8c-11e7-8941-0402fa49a81a.png)

i think i'm a bit closer to understanding what the problem is.

**Comment by ly29** [comment]
Call ```update_group``` or something like that after import the monad.

**Comment by zeffii** [comment]
`monad.update_cls` ?

**Comment by ly29** [comment]
That sounds right

**Comment by ly29** [comment]
I will try to a look but a lot to of stuff going on right now.

**Comment by zeffii** [comment]
```python
    try:
        if old_nodes.is_old(bl_idname):
            old_nodes.register_old(bl_idname)

        if bl_idname == 'SvMonadGenericNode':
            params = node_ref.get('params')
            cls_dict = params.get('cls_dict')
            monad_name = params.get('monad')
            monad = bpy.data.node_groups[monad_name]
            cls_ref = monad.update_cls()
            node = nodes.new(cls_ref.bl_idname)


            # setattr(monad, 'cls_bl_idname', cls_dict['cls_bl_idname'])
            # node = nodes.new(bl_idname)
            
            # node.input_template = cls_dict['input_template']
            # node.output_template = cls_dict['output_template']
            # setattr(node, 'cls_bl_idname', cls_dict['cls_bl_idname'])

            # # node.bl_idname = node.cls_bl_idname
            # monad.update()

        else:
            node = nodes.new(bl_idname)
``` 

: )

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1587

this seems to resolve it.. at least it generates the correct node(monad) from the monad(layout)

**Comment by zeffii** [comment]
i've updated Sverchok now - i think it's resolved. let me know either way.

**Comment by Durman** [comment]
@zeffii 
There are another problem with names of inputs. After import group node the input names are empty.

![name of group node](https://cloud.githubusercontent.com/assets/28003269/25469194/dff7e170-2b2b-11e7-89fe-dae36dd263a3.gif)
![2017-04-27_09-24-43](https://cloud.githubusercontent.com/assets/28003269/25469232/1be23780-2b2c-11e7-9f3d-3de2610567f5.png)

**Comment by zeffii** [comment]
Ok. Ill look into it

**Comment by ly29** [comment]
I don't remember where we get the name from but I guess that the multi type input does something clever

**Comment by zeffii** [comment]
```python
        if bl_idname == 'SvMonadGenericNode':
            params = node_ref.get('params')
            if params:

                monad_name = params.get('monad')
                monad = bpy.data.node_groups[monad_name]
                cls_ref = monad.update_cls()
                node = nodes.new(cls_ref.bl_idname)

                cls_dict = params.get('cls_dict')
                node.input_template = cls_dict['input_template']
                node.output_template = cls_dict['output_template']
```

seems to do the trick nicely.

**Comment by zeffii** [comment]
![ggggggif](https://cloud.githubusercontent.com/assets/619340/25474058/143fbab0-2b32-11e7-8a1c-291825ef333e.gif)

**Comment by Durman** [comment]
Is the problem decided? I do not see changes in my Sverchek. May be I will create new issue about names of group nodes inputs?

**Comment by zeffii** [comment]
I thought it was fixed, update if you can. If still not working raise new issue and show gif
