### ISSUE TITLE
Custom PNG saving

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#1586]
Discussion from https://github.com/nortikin/sverchok/issues/1566
Before to ask a pull request, i'm testing the code that @zeffii pointed out in this link http://stackoverflow.com/a/19174800/1243487
original code from @ideasman42 and @Evgeni_Sergeev

**PNG_test.py**

```python
'''
code taken from:
http://stackoverflow.com/questions/902761/saving-a-numpy-array-as-an-image/19174800#19174800
thanks to @ideasman42 and @Evgeni Sergeev
'''
"""
in buf s d=[[]] n=1
out some s
"""

def write_png(buf, width, height):
    """ buf: must be bytes or a bytearray in Python3.x,
        a regular string in Python2.x.
    """
    import zlib, struct

    # reverse the vertical line order and add null bytes at the start
    width_byte_4 = width * 4
    raw_data = b''.join(b'\x00' + buf[span:span + width_byte_4]
                        for span in range((height - 1) * width_byte_4, -1, - width_byte_4))

    def png_pack(png_tag, data):
        chunk_head = png_tag + data
        return (struct.pack("!I", len(data)) +
                chunk_head +
                struct.pack("!I", 0xFFFFFFFF & zlib.crc32(chunk_head)))

    return b''.join([
        b'\x89PNG\r\n\x1a\n',
        png_pack(b'IHDR', struct.pack("!2I5B", width, height, 8, 6, 0, 0, 0)),
        png_pack(b'IDAT', zlib.compress(raw_data, 9)),
        png_pack(b'IEND', b'')])
        

def saveAsPNG(array, filename):
    import struct
    if any([len(row) != len(array[0]) for row in array]):
        raise ValueError("Array should have elements of equal size")

                                #First row becomes top row of image.
    flat = []; map(flat.extend, reversed(array))
                                 #Big-endian, unsigned 32-byte integer.
    buf = b''.join([struct.pack('>I', ((0xffFFff & i32)<<8)|(i32>>24) )
                    for i32 in flat])   #Rotate from ARGB to RGBA.

    data = write_png(buf, len(array[0]), len(array))
    f = open(filename, 'wb')
    f.write(data)
    f.close()
    
saveAsPNG(buf, 'test_grid.png')
#saveAsPNG([[0xffFF0000, 0xffFFFF00],
           #[0xff00aa77, 0xff333333]], 'test_EU_grid.png')

```

my nodeTree:

![savepng_custom](https://cloud.githubusercontent.com/assets/1275858/25432339/5913cca2-2a84-11e7-84df-581bd2ae6feb.png)

gist of nodetree:
https://gist.github.com/432eed6f4e3befe150bf037bc4d7e09f

Bu there is a difference from the imaged passed to blender image editor and png saved from the script:

**texture_grid.png** --> image passed and saved from blender image editor
![texture_grid](https://cloud.githubusercontent.com/assets/1275858/25432452/c7072420-2a84-11e7-834d-5b4b9aedb191.png)

**test_grid.png** --> saved directly from the script
![test_grid](https://cloud.githubusercontent.com/assets/1275858/25432493/f8967e46-2a84-11e7-8617-58045546526d.png)

**Comment by kalwalt** [comment]
Maybe the buffer data type is not correct?

**Comment by zeffii** [comment]
```
libpng error: Not enough image data
DDS: trying to read beyond end of stream (corrupt file?)
IMB_ibImageFromMemory: unknown fileformat (C:\Users\zeffi\Desktop\b278c\test_grid.png)
```

**Comment by kalwalt** [comment]
That strange with Ubuntu i can read that file instead.

**Comment by kalwalt** [comment]
Tetsing now the numpypngw module https://github.com/WarrenWeckesser/numpngw as also suggesed in the stackoferflow thread.
it's just one file **numpngw.py** , temporarly i placed it in `sverchok/utils` and tested this with a RGBA buffer:
```python
"""
in buf s d=[[]] n=1
in size s d=4 n=2
out d s
"""

import numpy as np
from sverchok.utils.numpngw import write_png


in_data = np.array(buf)
max = np.amax(in_data)
print('in_data max val: ', max)
data = np.interp(in_data,[0, max],[0, 255])
print('data mapped: ', data)
data_uint = np.array(data, dtype=np.uint8)
img= np.reshape(data_uint, (size, size, 4))
print('img data reshaped: ', img)
print('img shape is', img.shape)

write_png('example_buf.png', img)
```
of course the incoming data must be in the range (0.0, 1.0).
The script save corectly the png file.
I would give a try also to PyPng module but i think numpngw is lighter.

**Comment by kalwalt** [comment]
performance comparsion between `pypng` and `numpngw`:
```c
0 ('StringsSocket', 'buf', [[]], 1)
numpyPNg saved in 0.0648 sec.
0 ('StringsSocket', 'buf', [[]], 1)
numpyPNg saved in 0.0671 sec.
0 ('StringsSocket', 'buf', [[]], 1)
numpyPNg saved in 0.0663 sec.
0 ('StringsSocket', 'buf', [[]], 1)
numpyPNg saved in 0.0704 sec.
0 ('StringsSocket', 'buf', [[]], 1)
numpyPNg saved in 0.0627 sec.
0 ('StringsSocket', 'buf', [[]], 1)
PyPNg saved in 0.0555 sec.
0 ('StringsSocket', 'buf', [[]], 1)
PyPNg saved in 0.0533 sec.
0 ('StringsSocket', 'buf', [[]], 1)
PyPNg saved in 0.0547 sec.
0 ('StringsSocket', 'buf', [[]], 1)
PyPNg saved in 0.0558 sec.
0 ('StringsSocket', 'buf', [[]], 1)
PyPNg saved in 0.0547 sec.
```

I thought `numpngw` was faster but btw little differences.
scripts used for testing:
**numpngw script**
```python
"""
in buf s d=[[]] n=1
out d s
"""

import numpy as np
from sverchok.utils.numpngw import write_png
import time

# Example 1
#
# Create an 8-bit RGB image.
start_time = time.process_time()
img = np.zeros((80, 128, 3), dtype=np.uint8)

grad = np.linspace(0, 255, img.shape[1])

img[:16, :, :] = 127
img[16:32, :, 0] = grad
img[32:48, :, 1] = grad[::-1]
img[48:64, :, 2] = grad
img[64:, :, :] = 127

write_png('example1.png', img)
print('numpyPNg saved in %.4f sec.' % (time.process_time() - start_time))

```
**pypng script**
```python
"""
in buf s d=[[]] n=1
out d s
"""

import numpy as np
from sverchok.utils.png import from_array
import time


# Example 1
#
# Create an 8-bit RGB image.
start_time = time.process_time()
img = np.zeros((80, 128, 3), dtype=np.uint8)

grad = np.linspace(0, 255, img.shape[1])

img[:16, :, :] = 127
img[16:32, :, 0] = grad
img[32:48, :, 1] = grad[::-1]
img[48:64, :, 2] = grad
img[64:, :, :] = 127

from_array(img, 'RGB').save("small_example1.png")
print('PyPNg saved in %.4f sec.' % (time.process_time() - start_time))
```

**Comment by zeffii** [comment]
let me suggest using a single module file for various png exporters..  `sverchok.utils.sv_export_png`

**Comment by kalwalt** [comment]
but `sverchok.utils.sv_export_png` also as a container(folder)?

**Comment by kalwalt** [comment]
it is a smart idea, so we could develop different exporters ( if we wants) but pypng and numpngw are one file that could be easily stored in a folder inside sverchok. other modules (scipy, PIL...) will require them to be installed in the dist-package of blender. Maybe one day blender will let install extra package in an easier way...

**Comment by zeffii** [comment]
no, sorry, just a file.  I'm sure that we can add folder there without adding extra lines to `__init__` / not worth the hassle yet.

**Comment by kalwalt** [comment]
ok, anyway   I'm inclined to use a lightweight module rather than developing a PNG exporter from scratch. What do you think?

**Comment by zeffii** [comment]
i'm not in favour of any reliance on 3rd party modules with respect to the standard node set.

**Comment by kalwalt** [comment]
understood, so i will continue in this direction.

**Comment by kalwalt** [comment]
...and about `pypng` or `numpngw`? they are only one file/module that we could store  in `sverchok.utils` and implement our function/exporters in `sverchok.utils.sv_export_png`

**Comment by zeffii** [comment]
if they have a permissive licence, then i think we might allow `sverchok.utils.modules`  as a directory, for such things.

**Comment by zeffii** [comment]
(they would not be refreshed upon F8 tho...but that's ok if modules are truely static most of the time.. unless you are bugfixing.. -- modules can be hot reloaded with other code (see how macros are imported for an example) )

**Comment by kalwalt** [comment]
> if they have a permissive licence, then i think we might allow sverchok.utils.modules as a directory, for such things.

yes of course

>(they would not be refreshed upon F8 tho...but that's ok if modules are truely static most of the time.. unless you are bugfixing.. -- modules can be hot reloaded with other code (see how macros are imported for an example) )

So for these reasons a sverchok native exporter will be better.

**Comment by kalwalt** [comment]
This now works for me:

```python
'''
code taken from:
http://stackoverflow.com/questions/902761/saving-a-numpy-array-as-an-image/19174800#19174800
thanks to @ideasman42 and @Evgeni Sergeev
'''
"""
in buf s d=[[]] n=0
out some s
"""


def write_png(buf, width, height):
    """ buf: must be bytes or a bytearray in Python3.x,
        a regular string in Python2.x.
    """
    import zlib, struct

    # reverse the vertical line order and add null bytes at the start
    width_byte_4 = width * 4
    raw_data = b''.join(b'\x00' + buf[span:span + width_byte_4]
                        for span in range((height - 1) * width_byte_4, -1, - width_byte_4))

    def png_pack(png_tag, data):
        chunk_head = png_tag + data
        return (struct.pack("!I", len(data)) +
                chunk_head +
                struct.pack("!I", 0xFFFFFFFF & zlib.crc32(chunk_head)))

    return b''.join([
        b'\x89PNG\r\n\x1a\n',
        png_pack(b'IHDR', struct.pack("!2I5B", width, height, 8, 6, 0, 0, 0)),
        png_pack(b'IDAT', zlib.compress(raw_data, 9)),
        png_pack(b'IEND', b'')])
        

def saveAsPNG(array, filename):
    import struct
    if any([len(row) != len(array[0]) for row in array]):
        raise ValueError("Array should have elements of equal size")

                                #First row becomes top row of image.
    flat = []; map(flat.extend, reversed(array))
                                 #Big-endian, unsigned 32-byte integer.
    buf = b''.join([struct.pack('>I', ((0xffFFff & i32)<<8)|(i32>>24) )
                    for i32 in flat])   #Rotate from ARGB to RGBA.

    data = write_png(buf, len(array[0]), len(array))
    f = open(filename, 'wb')
    f.write(data)
    f.close()
 
data = bytearray([int(p * 255) for p in buf[0]])    
print(data)
# saveAsPNG(data, 'test_grid.png')
#saveAsPNG([[0xffFF0000, 0xffFFFF00],
           #[0xff00aa77, 0xff333333]], 'test_EU_grid.png')
           
final_data= write_png(data, 4, 4)
with open("my_image.png", 'wb') as fd:
    fd.write(final_data)
```
before was:
```diff
-data = bytearray([int(p * 127) for p in buf[0]])  
+data = bytearray([int(p * 255) for p in buf[0]])  
```
my_image.png
![my_image](https://cloud.githubusercontent.com/assets/1275858/25447207/9795b8f2-2ab4-11e7-9c53-6e9f12b9e870.png)

**Comment by zeffii** [comment]
cool!

**Comment by zeffii** [comment]
i can't test atm.. but later day maybe

**Comment by kalwalt** [comment]
the 'problem' is that the data saved in the PNG file can be 8 or 16 bit instead i was transfering float values. Mapping and converting via nodes it's a bit tricky i think it's better doing this via code...

**Comment by kalwalt** [comment]
a bigger one
![my_image01](https://cloud.githubusercontent.com/assets/1275858/25449796/3788b74e-2abd-11e7-85cb-c4fe500b45a5.png)

**Comment by zeffii** [comment]
oh it works fine btw  ( but probably not so well with F8 ..which should be no problem as mentioned )

```
>>> from sverchok.utils.modules.some_file import ddir
>>> ddir(Matrix)
```

![image](https://cloud.githubusercontent.com/assets/619340/25452505/15dc4c2e-2ac6-11e7-89f4-a957932157d4.png)

##### some_file.py

```python

def ddir(obj):
    return [d for d in dir(obj) if not d.startswith('__')]

```

**Comment by zeffii** [comment]
it seems F8 should be fine too (at least to the extend that i've tested it )

**Comment by kalwalt** [comment]
very good, i'm working now for a very primitive sv_export_png.py file, maybe later i can show something.

**Comment by zeffii** [comment]
closing for now - feel free to reopen when ready
