### ISSUE TITLE
ob3 (objects in mk3) maintenance

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1592]
- add UILayout list display of names (let's not bother with layout.label drawing there..)
- depending on connected sockets perform obj->data lookup, no earlier than strictly needed
- maybe object in socket.

**Comment by zeffii** [comment]
it will happen eventually

**Comment by zeffii** [comment]
UI layout version :)

![image](https://user-images.githubusercontent.com/619340/27014455-b4cc701e-4ef9-11e7-9017-13e174d08967.png)

**Comment by zeffii** [comment]
Could add `x` operator to remove objects from current selection.

Not sure if the layout.mode = 'COMPACT' does anything useful.

**Comment by nortikin** [comment]
stretching list field will size node itself?

**Comment by zeffii** [comment]
> stretching list field will size node itself? 

i think it then adds a vertical-slider? i'll take a look soon

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/27075702-434a0752-502b-11e7-8ddf-5aaeaff3e388.png)
unfortunately, this will require a move to MK4, and if doing so I might also add a few optimizations.
