### ISSUE TITLE
stethoscope mk2 zoom / dpi issue

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1593]
as reported in the [BlenderArtists . org  ](https://blenderartists.org/forum/showthread.php?272679-Addon-WIP-Sverchok-parametric-nodes-for-architects&p=3182055&viewfull=1#post3182055)

affected by `ui_scale`  and  dpi..

**Comment by Kosvor2** [comment]
It seems all bgl drawing inside of nodetree is affected, not only stethoscope.

**Comment by zeffii** [comment]
yeah, i think first step is to times x and y by the `settings.ui_scale` value.

i might add a zoomfactor detection (calculate zoom based on distance betwen two known 2d vectors points)..

any help appreciated

**Comment by zeffii** [comment]
closing for now : https://github.com/nortikin/sverchok/pull/1607

**Comment by zeffii** [comment]
this has morphed into a different issue  https://github.com/nortikin/sverchok/issues/1612

**Comment by zeffii** [comment]
needs a multiplier sverchok_preference...
