### ISSUE TITLE
Parsing ArtRage stroke script and GML and maybe 3D Grease Pencil ML

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1594]
I am currently starting at this script generated via app called ArtRage. Maybe this can be an interesting study in Sverchok.
https://www.artrage.com/manuals/getting-started-artrage/older-desktop-editions-artrage-2-3/artrage-4/script-files/

This can be a fun parsing task as a Python node.
[artrage_test_001.arscript.zip](https://github.com/nortikin/sverchok/files/963372/artrage_test_001.arscript.zip)

Ideally, I really like @zeffii idea of GML (Graffiti Markup Language) thing. It should transfer well into Grease Pencil, maybe, more or less. There are probably some GML data out there that can be transferred into Grease Pencil via Sverchok. Something I want to see.

At some point in the future, we probably have 3D paint tool ala TiltBrush for VR users. I do not have access to those 3D painter unfortunatley.

Anyway, Art Rage 2D strokes look something like below:
![screen shot 2017-04-28 at 13 23 57](https://cloud.githubusercontent.com/assets/3952687/25513091/f6557eba-2c15-11e7-8368-2cb192376467.png)

Maybe it is like a basic Motion Capture data of some sort. I will try to parse it using my knowledge of Python. I think the data has XML bits.

Hoping for some hints to the right direction.

Thank you!

**Comment by enzyme69** [comment]
Currently discovering XML, elementree, tag, etc. This 

<StrokeEvent> -> I suspect, this is all the strokes of my artwork,  this thing has lots of lines in it, weird
<StrokeHeader> -> useless tag for now

Really just want Loc and Pressure info. Should be simple as soon I could access StrokeEvent.

**Comment by zeffii** [comment]
You need to figure this out by yourself. All progress involves struggle and determination. Good luck

**Comment by enzyme69** [comment]
Thanks Zeffii!
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
This is actually getting somewhere! 💃 

![screen shot 2017-04-28 at 17 06 40](https://cloud.githubusercontent.com/assets/3952687/25517976/24e6a366-2c35-11e7-8d5f-64f82c0e728c.png)

There is a sense of accomplishment with parsing code.

The code is pretty crappy at the moment, but basically since the data itself is actually fairly tidy and has certain pattern, this XML, all I want is the coordinate X,Y and the stroke pressure.

To Be Continued.

Maybe I share the completed Script Node here.

I don't know maybe I am the only person in the world using iPad and ArtRage and Sverchok in Blender :D

**Comment by zeffii** [comment]
Don't worry about crappy code, you have to write a whole lot of crap code to gradually become better. It's more useful as a learning experience just to code it .. warts and all. Then if you feel it should be improved, that's when you ask someone more experienced to have a look and point you at better coding style / conventions / techniques..

Once you can do no more to it, share it. always share it. I've found this to be the best way to make sure I never lose code (code=time you'll never get back).

**Comment by nortikin** [comment]
i will quote this frase about time

**Comment by enzyme69** [comment]
Thanks for tips, @zeffii :D I am learning. True on CODE=TIME.

I will put some of my internal dialogue here:
https://github.com/enzyme69/blendersushi/issues/1

**Comment by enzyme69** [comment]
Checking out this by Nick:
https://github.com/n1ckfg/LightningArtist/tree/master/blender

**Comment by nortikin** [comment]
it is GP animation import export, so usefull maybe for animators.

**Comment by enzyme69** [comment]
@Nikitron unfortunate effect is one frame delay... maybe sverchok needs
force update node that update something each cycle, kind of like AN process
all, using all CPU
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
No.. obj id selector probably needs a frame in. Socket.
