### ISSUE TITLE
List shift node bad works with objects

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1595]
List shift can not work with objects different length. Is It impossible?

![bug list shift](https://cloud.githubusercontent.com/assets/28003269/25515111/55decdfa-2bf3-11e7-86ad-5fefad28ff8a.gif)

**Comment by zeffii** [comment]
good find!

**Comment by nortikin** [comment]
newer used with objects

**Comment by zeffii** [comment]
for the record, when that node goes red, other nodes aren't processed. This means that depending on 'deterministic' randomness, either the List Slide node or the Stethoscope is processed first. In this case the List Slide is processed first and it's causing an Exception , so the Stethoscope isn't processed.

![image](https://cloud.githubusercontent.com/assets/619340/25555578/77987e62-2cea-11e7-8639-23a376520191.png)

**Comment by zeffii** [comment]
What kind list shifting had you hoped to do, this?
```python
[[1, 2, 4], [5, 6, 9, 0]]
[[2, 4, 1], [6, 9, 0, 5]]
[[4, 1, 2], [9, 0, 5, 6]]
``` 
?

**Comment by Durman** [comment]
@zeffii 
Your example is right. I want to shift lists inside objects.
@nortikin 
I love objects.))

**Comment by zeffii** [comment]
it's a relatively uncomplicated node.
```
    def process(self):
        if not self.outputs["data"].is_linked:
            return

        data = self.inputs['data'].sv_get()
        number = self.inputs["shift"].sv_get()[0][0]
        # numpy case:
        dat = np.array(data)
        # levelsOfList replacement:
        depth = dat.ndim #len(np.shape(dat))-1
        # roll with enclose (we need case of declose and vectorization)
        output = np.roll(dat,number,axis=min(self.level,depth)).tolist()

        self.outputs['data'].sv_set(output)
```

**Comment by zeffii** [comment]
@nortikin   should we open it up and add a few modes? i wont get around to it until other things are fixed.

**Comment by zeffii** [comment]
@Durman   in the meantime stick separate List Shifts before the List Join.

**Comment by Durman** [comment]
@zeffii 
This is just example. In real I have many objects from Blander scene. I prepare them in Sverchek.

**Comment by zeffii** [comment]
ok . it's on my todo list now, unless someone else feels like doing it.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25784284/4d2aa34a-336a-11e7-9542-ad8eb6620d08.png)

coming soon probably :)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1630

**Comment by zeffii** [comment]
should work.
