### ISSUE TITLE
Socket conversion demystified 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1599]
I’m trying to understand some of the socket conversion code.. in particular the location from matrices socket convert. I can’t make sense of the new_sublist/container recursion. I would think the alternative convertor (listed below) should do the job. Is there some particular matrix input nestiness that this implementation is the preferred one? 

```python
def get_locs_from_matrices(data):
    locations = []

    def get_all(m, container):

        for sublist in m:
            if is_matrix(sublist):
                # matrix_to_vector
                container.append((sublist[0][3], sublist[1][3], sublist[2][3]))
            else:
                new_sublist = []
                get_all(sublist, new_sublist)

    get_all(data, locations)
    return locations
```

```python
def get_locs_from_matrices(data):
    locations = []
    collect_vector = locations.append

    def get_all(data):

        for sublist in data:
            if is_matrix(sublist):
                collect_vector((sublist[0][3], sublist[1][3], sublist[2][3]))
            else:
                get_all(sublist)

    get_all(data)
    return locations
```

For instance an input like [[m],[m]] will result in [[v,v]], while [[[m],[m]]] will result in [], which is kind of expected due to the recursive call using a local list new_sublist that doesn’t really make its way upstream the recursive calls.

**Comment by zeffii** [comment]
[[[m],[m]]] is malformed, wrapped one time too often. We collectively agreed that it was practical to generate a single list of verts that doesn't preserve original structure, for that we could use matrix decomposer.

**Comment by zeffii** [comment]
I didn't put a lot of thought into the recursive function there,  the proposed modification seems sane if it produces the same output for useful input. ( discussed in the other thread you started about demystifying data nesting.

**Comment by zeffii** [comment]
```python
# input 
[[m1],[m2],[m3]]
[[m1, m2],[m3]]
[[m1, m2, m3]]

# expected output
[[v1, v2, v3]]
```

**Comment by zeffii** [comment]
```python
def m(c):
    return ((c, c, c, c), (c, c, c, c), (c, c, c, c), (c, c, c, c))


A = [[m(1)], [m(2)], [m(3)]]
B = [[m(1), m(2)], [m(3)]]
C = [[m(1), m(2), m(3)]]
D = [m(1), m(2), m(3)]

# expected output
# [[v1, v2, v3]]


def is_matrix(mat):
    ''' expensive function call? '''
    if not isinstance(mat, (tuple, list)) or not len(mat) == 4:
        return

    for i in range(4):
        if isinstance(mat[i], (tuple, list)):
            if not (len(mat[i]) == 4 and all([isinstance(j, (float, int)) for j in mat[i]])):
                return
        else:
            return
    return True



def get_locs_from_matrices(data):
    locations = []

    def get_all(m, container):

        for sublist in m:
            if is_matrix(sublist):
                container.append((sublist[0][3], sublist[1][3], sublist[2][3]))
            else:
                new_sublist = []
                get_all(sublist, new_sublist)

    get_all(data, locations)
    return locations


def get_locs_from_matrices2(data):
    locations = []
    collect_vector = locations.append

    def get_all(data):

        for sublist in data:
            if is_matrix(sublist):
                collect_vector((sublist[0][3], sublist[1][3], sublist[2][3]))
            else:
                get_all(sublist)

    get_all(data)
    return locations


print('1: A', get_locs_from_matrices(A))
print('2: A', get_locs_from_matrices2(A))

print('1: B', get_locs_from_matrices(B))
print('2: B', get_locs_from_matrices2(B))

print('1: C', get_locs_from_matrices(C))
print('2: C', get_locs_from_matrices2(C))

print('1: D', get_locs_from_matrices(D))
print('2: D', get_locs_from_matrices2(D))
```
so yes, lets go with the shorter version
```text
1: A []
2: A [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
1: B []
2: B [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
1: C []
2: C [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
1: D [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
2: D [(1, 1, 1), (2, 2, 2), (3, 3, 3)]
```

**Comment by zeffii** [comment]
i've pushed that already

**Comment by DolphinDream** [comment]
Sweet. That makes my quaternion socket convert job clear now :) 

Btw.. is there a thread where this was discussed? why the expected output should always be unstructured ? I would think you want to keep the structure [[m,m], [m]] -> [[v,v],[v]] and use a separate node to flatten the structure if that’s what you want, but maybe i don’t see the big picture here .

**Comment by zeffii** [comment]
it was a choice. with something binary like that it's not possible to please everyone all the time. So..i chose the convention that most reflected my immediate needs. If i want specific nesting i add a proper node inbetween. Don't think too deep about this.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1060

here and a few other places.
