### ISSUE TITLE
Sverchok failed to load after latest GIT PULL

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1600]
Eek... what happened. How to roll back? I cannot make video.

![screen shot 2017-04-30 at 00 11 22](https://cloud.githubusercontent.com/assets/3952687/25556091/c41f2552-2d39-11e7-948c-66b88f4a287c.png)

**Comment by enzyme69** [comment]
cannot import name get_loc_from_matrices.py?

**Comment by zeffii** [comment]
oops. my fault.

**Comment by zeffii** [comment]
pull again.

**Comment by enzyme69** [comment]
*phew* cheers Zeff

**Comment by zeffii** [comment]
no need for caps @enzyme69 .
