### ISSUE TITLE
Box and Index Order

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1604]
This is a funny thing, but I told to Blender Developers as bug recently:
![screen shot 2017-04-30 at 18 49 33](https://cloud.githubusercontent.com/assets/3952687/25562992/d6e95328-2dd5-11e7-9f6e-fd28c0e98267.png)

Basically:
Default Box and Create Box in Blender does not have a matching index order.

Sv Box actually matches the Default Box, but does not match the Create Box.

I probably can have live noding just talk about how to reshuffle the index :D 

Ideally the default box matches the create box, matches sverchok Box.

Sv Box should probably matches the create box. Currently it is matching the default box.

**Comment by zeffii** [comment]
https://en.wikipedia.org/wiki/Law_of_triviality

**Comment by zeffii** [comment]
maybe the `Mesh->Add Cube`  should correspond to the original Cube, either way -- this is how we implemented in Sv. Changing it now might have undesirable effects for existing Blends.  This is low on the ladder of importance, so lets close it as an interesting observation
