### ISSUE TITLE
SV BMesh Viewer and Dupli Vert Orientation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1605]
Probably just another _interesting found_ in Blender and how it reacts to Sverchok, but I wonder if we can get the normal to work with Duplivert without "Smooth Shade" option needs to be checked? Or is it just the way it works in Blender like a "gotcha" thing?

![duplivert_001](https://cloud.githubusercontent.com/assets/3952687/25563325/5bc4e1fa-2ddd-11e7-95ad-ff39d2cf2f1d.gif)

**Comment by enzyme69** [comment]
I think DupliVert object orientation is "limited". 
[duplivert_01_2017_04_30_09_48.zip](https://github.com/nortikin/sverchok/files/966666/duplivert_01_2017_04_30_09_48.zip)

Currently testing in Sverchok and checking if we can keep the objects positions, but changing the Vertex Normal to affect the DupliVert.

DupliFace might be more controllable... but then again.

**Comment by zeffii** [comment]
This is a valid point, I could add explicit normal calcs, as a toggle in the N Panel ( so you'd get the normals, without the shading effect)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1608
