### ISSUE TITLE
How to Polygon Boom and Center Pivot each Poly Face?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1606]
![screen shot 2017-04-30 at 19 59 52](https://cloud.githubusercontent.com/assets/3952687/25563429/a49c14dc-2ddf-11e7-9666-79f2de38604c.png)
[polygon_boom_center_pivot_001_2017_04_30_09_59.zip](https://github.com/nortikin/sverchok/files/966668/polygon_boom_center_pivot_001_2017_04_30_09_59.zip)

I should probably know this by now, but still I am not so sure.

I tried with grid and using Polygon Boom to separate poly faces, and I want to center pivot every face inside Sverchok for further modification.

Potentially to use each poly face for dupliface. But until I can "center pivot" this is a little tricky.

**Comment by enzyme69** [comment]
Center Polygon is not the answer either.

![screen shot 2017-04-30 at 20 02 04](https://cloud.githubusercontent.com/assets/3952687/25563452/ec85905c-2ddf-11e7-8016-b5aaa745bf01.png)

**Comment by enzyme69** [comment]
Maybe Vector Drop, but what annoy me is the Matrix of Center Polygon always gives 45 degree.

![screen shot 2017-04-30 at 20 07 01](https://cloud.githubusercontent.com/assets/3952687/25563511/ae944bca-2de0-11e7-8237-77fff58a2037.png)

**Comment by zeffii** [comment]
then filter out the rotation.. Centers really just hopes to give you the location, and combines it with the normal ( i think -- look at the source if you are curious )

![image](https://cloud.githubusercontent.com/assets/619340/25563664/f106b82a-2da0-11e7-8a93-b0660cdca283.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1385

maybe it's me... but i think you've asked this about 4 or 5 times now. that's the latest.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25563697/eca2e9c4-2da1-11e7-8258-dfe865c0997f.png)

**Comment by zeffii** [comment]
this would give you the same result i think..
![image](https://cloud.githubusercontent.com/assets/619340/25563746/e1ef77b2-2da2-11e7-8ee5-678d5d5336b1.png)

**Comment by zeffii** [comment]
![lazygif](https://cloud.githubusercontent.com/assets/619340/25563820/5dd6944a-2da4-11e7-9c6e-ec212aa8d6eb.gif)

If you use the `Centers polygons 3` Centers socket, it uses the rotation part of the matrix to give you the orientation (normal). When you have a mesh like a icosphere, it will use the rotation elements in the matrix to give you the normal along with the location. In the example you should it still uses the rotation elements to give the normal, but in that case the rotation gives more information than needed to indicate orientiation. There could be a switch to "drop the rotation elements" from the output of Centers matrix... but you could also just use the Origins(v) --> Matrix(m) implicit conversion...

**Comment by enzyme69** [comment]
Thanks Zeffii... sorry it's my brain going in the loop, asking same
question for many years, but I think it's clear now!! @_@
