### ISSUE TITLE
BMesh Ops documentation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1611]
I realized we have a bunch of BMesh Node that seems peculiar, it does not have documentation whatsoever, I have Poke a try and so far so good, but BMesh element thing confused me.

[bmesh_thing_001_2017_05_01_00_58.zip](https://github.com/nortikin/sverchok/files/967144/bmesh_thing_001_2017_05_01_00_58.zip)
![screen shot 2017-05-01 at 10 56 54](https://cloud.githubusercontent.com/assets/3952687/25569559/19604fcc-2e5d-11e7-9006-9f2cdf41a26c.png)

Care to give some enlightenment?

**Comment by zeffii** [comment]
Explore read the node code.

**Comment by enzyme69** [comment]
Ah! Sorry forgot that method. I'll check...

**Comment by zeffii** [comment]
Then do a search in bpy api docs for the functions listed, and observe the very basic information provided to us about these functions.

**Comment by Kosvor2** [comment]
It is better to create separate nodes for each operator. Created this node long before realized how flawed this approach is.

**Comment by enzyme69** [comment]
I don't mind one Uber Operator :D and many smaller ones.

**Comment by enzyme69** [comment]
So far, Poke is my only "aha". Kind of want to push the poke, but have to probably mask something, I think I can use select mask and transform.

**Comment by enzyme69** [comment]
![screen shot 2017-05-01 at 23 32 03](https://cloud.githubusercontent.com/assets/3952687/25580713/6bdb46a8-2ec6-11e7-85de-30f5e79906af.png)

GIST:
https://gist.github.com/c7c829488624bb887c974b90838b4b2a

**Comment by zeffii** [comment]
transparent frame ??

**Comment by enzyme69** [comment]
@zeffii It's been like this since I am using this Theme. I don't quite like it, I wish it has a bit of shade.

**Comment by zeffii** [comment]
what theme?

**Comment by enzyme69** [comment]
@zeffii RTheme.

**Comment by zeffii** [comment]
hmm.. the xml : frame_node="#96969600"

**Comment by zeffii** [comment]
#### Alpha and Beta nodes

as Bmesh Ops is an alpha node, it is not required to supply documentation. 
 - Either the author is unwilling to write docs ( i often don't like to -- for the truly curious reading source code is often sufficient) ,
 - or the author is not happy with the state of the Node and expects it to morph into something else or not make it into the standard node set. So why waste time writing docs....

That means you have to read the source code of the node, (not a bad thing to do with any node which has behaviour you don't understand... i sound like a broken record...)  

if you like the node you should consider writing documentation for it, to help us out :)

**Comment by nortikin** [comment]
was thought of fill grid operator, that i need sometimes, when UVconnect node gives flat (caps, than make grid fill of holes) maybe as modifier after uvconnected cycled mesh

**Comment by enzyme69** [comment]
Points taken, I started to understand what Alpha, Beta and a complete node
is. Sort of.

What would be nice is if a person make a video tutorial on how to write a
node.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
Ok

**Comment by zeffii** [comment]
> What would be nice is if a person make a video tutorial on how to write a
node.

yeah maybe - but maybe a good annotated simple node example will be sufficient. I'll start a wiki page for it

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/wiki/Sverchok-Node-tutorial
