### ISSUE TITLE
Monad parameter clashing issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1618]
I have a setup like below:
https://drive.google.com/open?id=0B0ogUwJ-NEFgN1VWaVR5LTdMX1k

It should work in that Blend, but if I export out the Monad and bring back, there are few issues, especially with parameter / attribute props name variable that are clashing. 

Bug 1: 
JSON monad has clashing issue.

https://gist.github.com/f4be9264e9a02d53720c9b3bd910f915

Best solution for now is when grouping nodes, I need to plug manually.

**Comment by enzyme69** [comment]
And also, if I accidentally delete Monad Group Input or Output, how to get it back? >-<

**Comment by enzyme69** [comment]
This one if I plug the input one by one:
https://gist.github.com/bf77e5787918f600e1022960f4f49ecd

**Comment by enzyme69** [comment]
Bug 3:
Editing Socket Signature, s, m, v, actually almost always breaks the monad.

**Comment by zeffii** [comment]
there are two separate issues here
- issues that are directly monad related (how it's implemented)
- issues with how iojson interprets the monad information.

it would be great if you made each "bug" it's own issue (so we can close each individually when/if it's resolved)

**Comment by zeffii** [comment]
> export out the Monad and bring back,

thats iojson issue.  You should be able to append/link existing monads from the Group menu -- if that's what you're trying to do.

**Comment by zeffii** [comment]
also i wish to point you at an issue that's already made for this.. https://github.com/nortikin/sverchok/issues/1596

**Comment by enzyme69** [comment]
Got it~

**Comment by zeffii** [comment]
i know it's not very satisfying, but most of the hard work is done already.. what's left is the finer details ..and that seems to need longer uninterrupted periods of attention to solve. Which i don't have atm.
