### ISSUE TITLE
Monads and IOjson.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1619]
here's my list of observations about Monad and IOJson. The ticked items have been merged and are in master.

##### Monad

- [x] adding a socket does not automatically give the surrogate socket the same value to start off with (this would be useful to carry over)
- [x] avoid duplicate prop_name when initially creating the monad manually, by delaying the setattr until the last moment.
- [x] could allow basic recursion if input is same as output, and given recursion depth.
- [ ] properties that don't have a name attribute cause problems
- [ ] it is permitted, but should be cleverly avoided i think, to use the same name for sockets ( it doesn't matter that they will always have unique identifiers/socket indices...)
- [ ] adding monad info node (at least in my mod version ) will auto add a new socket, repeating last socket added.. very strange
- [ ] prop_name for vector properties doesn't add the property to the instance of the monad node.

##### IO Json

- [x] use index on compile socket instead of socket name (which can conflict), but use `socket.name` for NodeReroute nodes.
- [x] ensure correct corresponding socket property value, especially useful for monad with no connections on the outside
- [x] add more elaborate debug printing for failed output.
------

##### I/O = import / export

I started writing the IOjson code so people could exchange small ideas without the need for a .blend . Monads were developed much later and have not been integrated into the IOjson code succesfully yet. Monads bring new problems to the IOjson code.  

A lot of monad IO issues are related to these two things. They are separate, but affect eachother.

  - unfinished IO implementation for Monads. 
  - parts of the Monad system need to be fixed.

The Monad implementation is separate from our I/O (Json) code. People think that bugs experienced as a result of I/O are bugs in the Monad, but the bug is for the most part in how the I/O code packs and unpacks the Monad information. into

   1. Monad (Layout...nodegroup)... 
    ![image](https://cloud.githubusercontent.com/assets/619340/25662342/77a9be48-3014-11e7-8e48-85d4405b5966.png)

   2. Monad Node (front facing Node that represents the abstraction).
    ![image](https://cloud.githubusercontent.com/assets/619340/25662375/96a271d2-3014-11e7-8e89-376280cfdf99.png)

##### it's not totally broken...

currently monads do work in some limited scenarios within a gist/json 
- no duplicate named sockets,  
   1. Add a socket 
   2. rename it immediately to something unique...something sensible
   3. add the next socket, and repeat this process.

..but explaning how to circumnavigate the broken IO is more effort than i want to stick into this ..and it's not the right thing to do anyway.. and i don't want to encourage. These are very specific things that need to be addressed before it's OK to use Monads in json. Until then,, don't use the IO panel to export a layout which has Monads in it,, use `zipped Blends`. instead. 

-------------------

#### I'll try to explain

Most of the code needed to use Monads in IOjson is already in place, but a few small unimplemented details make the whole thing fail. ( the weakest link )

##### update_list

The update_list is where we store the connections between all nodes in a layout. Currently that's implemented as a whole bunch of 

```python
[
   [from_node_name, out_socket_name, to_node_name, in_socket_name], ,...
]
```
 `update_list` per layout doesn't store the index of a socket, only the name. This means that nodes that have several identical socket names will not receive the correct connections when relinked. Normally we mitigate this by not allowing identical socket names on nodes, as a matter of practice, but with Monads that's harder to enforce because it's up to the user/creator. And it's easy to get several identical socket names (as any user of monads can probably show us) 

##### Regenerating Monad Node (front facing) from Monad Group.

The code for this is partially supplied in the Monad as monad.get_all_props() and .set_all_props(data), but it doesn't yet have enough information to rebuild the front facing node properly.

---------------------------

**Comment by zeffii** [comment]
each socket has an `index`  and a `name` and an `identifier`.

- The identifiers are always unique (and are like Blender object names ... Cube Cube.001 Cube.002.. no two can be the same)
- The name can be the same, because the identifier takes care of the uniqueness
- The index is also always unique, no two sockets could share the same index.

**Comment by zeffii** [comment]
currently we build the update list this way
```python
    try:
        ng.build_update_list()
        links_out = []
        for name in chain(*ng.get_update_lists()[0]):
            for socket in ng.nodes[name].inputs:
                if selected and not ng.nodes[name].select:
                    continue
                if socket.links:
                    link = socket.links[0]
                    if selected and not link.from_node.select:
                        continue
                    links_out.append(compile_socket(link))
        layout_dict['update_lists'] = links_out
    except Exception as err:
        print(traceback.format_exc())
        print('no update lists found or other error!')
        print(' - trigger an update and retry')
        return
```

**Comment by zeffii** [comment]
#### solutions?

##### name collisions

'update_lists'

i propose switching to an alternative update_list for monads
```
update_list_plus = [from_node_name, output_index, to_node_name, input_index]
```
that would solve name collisions i think. -- i'll test it first..

'prevent duplicate names'

prevent dupe names from existing in the Group Input / Output nodes: 

- those that are generated automatically after connection can be changed before the socket is created...
- those that are renamed manually to be the same as an existing socket can be forced to be different before applied to socket ( this is my favourite..)

**Comment by zeffii** [comment]
currently monads do work in some limited scenarios within a gist/json 
- no duplicate named sockets,  (Add a socket it rename it immediately to something unique...something sensible )

..but explaning how to circumnavigate the broken IO is more effort than i want to stick into this ..and it's not the right thing to do anyway.. and i don't want to encourage

**Comment by zeffii** [comment]
i'll also be simplifying some of this code
```python
            # first switch socket type
            socket = socket_list[-1]
            if kind == "outputs":
                prop_name = monad.add_prop_from(socket)
            else:
                prop_name = ""

            cls = monad.update_cls()

            if kind == "outputs":
                new_name, new_type, prop_data = cls.input_template[-1]
            else:
                new_name, new_type = cls.output_template[-1]
                prop_data = {}

-------------------------------------------------------------------------------

            socket = socket_list[-1]
            if kind == "outputs":
                prop_name = monad.add_prop_from(socket)
                cls = monad.update_cls()
                new_name, new_type, prop_data = cls.input_template[-1]
            else:
                prop_name = ""
                cls = monad.update_cls()                
                new_name, new_type = cls.output_template[-1]
                prop_data = {}
```

**Comment by zeffii** [comment]
A bug exists in SvSocketAcquisition, where it doesn't add the modified `prop_name` in the case of duplicates. I spent way too much time tracking this down... and it's one of the first classes added for Monads , it should have been obvious this was the root of the bug. ohwell.. it's located now.

**Comment by nortikin** [comment]
THANK you, @zeffii

**Comment by zeffii** [comment]
it's not fixed yet, but i know now where to begin :)

**Comment by zeffii** [comment]
all those interested should try the https://github.com/nortikin/sverchok/tree/iojson_mod2 branch

**Comment by zeffii** [comment]
I might add an automatic property name generator, (like A,B,C....E) if the socket being connected doesn't have a name attribute. ( like Float/IntProperty(name='')  )  not many Socket Properties suffer this, but A Number does (intentionally).

**Comment by zeffii** [comment]
I'm slightly hesitant to push these changes. Because @ly29 took the Monad implementation much deeper than what I had originally written, i'm going to claim a certain ignorance of the smaller details (even tho I have now passed through the code several times....there's still a disconnect between my map of the code (in my brain) and the code as written/intended by @ly29 .

If you could have a look at the suggested modifications @ly29 that would be super, else I might just push anyway and brace for impact :)

It's complex code. but i'd like to get it more stable.

**Comment by ly29** [comment]
I am deep in a project but will try to have look in the weekend

**Comment by zeffii** [comment]
note to self / anybody interested / this won't be news to anyone who has stared at the code.

### vector properties

If Monads just created sockets on their _Monad Node_, without trying to display their UI representation (Dropdown, sliders) then Monad essentially is fully functional already. However - Sockets have been accompanied by Sliders/Dropdowns for a long time now, people can expect to have access to that kind of control.

The problem is divided into two parts and a solution will involve a bit of mental gymnastics.

Sockets get their ui slider/dropdown from either of two locations 
  1. the node itself has a registered property in the class definition, 
        - this is usually `socketname.prop_name = 'some_floatvector_property'`
        defining the (ui) property in advance allows for hardcoding min/max and setting
        various other attributes of the property that can't be changed after definition (at run time)
  2. the socket itself can also provide the property
        - this comes in the form of `socket_name.use_prop`
        a downside to defining the (ui) property on the socket is that (at present Dec/2017 ) you are limited to the defaults defined for that property in the socket class.

Currently the solution for Int/Float properties is to fill members of `int_props` and `float_props` in the dynamically created Monad node class. This allows for the UI to display sliders for Int and Float props. This does not address the sockets that use FloatVectorProps (vectors.. matrices), so at present their property is not displayed on the UI of the dynamically generated Monad class.

There's code in the Monad Properties side panel (N) that injects new custom properties into the Monad class dynamically, this is only triggered if you edit the individual properties of a socket in the N panel.

**Comment by zeffii** [comment]
the next step is to 
- add a `floatvector_props` collection, and use that for those nodes that define their own properties for the sockets.
- during socket acquisition determin if `use_prop` or `.prop_name` are used for the Vector socket and handle accordingly.

**Comment by zeffii** [comment]
secondly. considering the Monad class is dynamically generated, it's not unreasonable to inject new properties into the `class dict` before the `update()/hotswap` of _current dynamic class_ to _next dynamic class_.

this would allow for maximum CC of UI properties.. the only real pain here is generating unique names for the properties..

**Comment by zeffii** [comment]
I think this would mean that, if we really wanted, we could drop the int / float / floatvector_props collections and purely create the needed props dynamically.  (but it's not a crazy notion to use collections anyway)

**Comment by ly29** [comment]
I think this is the right thing todo. With the limitations that exist
