### ISSUE TITLE
Intersect edges

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1622]
I have problem with intersection between plane and some objects in scene. I do equal measure for z coordinate but it does not helping. I have not idea why.

![2017-05-03_15-34-49](https://cloud.githubusercontent.com/assets/28003269/25658894/316112d6-3016-11e7-91c3-982fd23b6e8f.png)
[untitled.zip](https://github.com/nortikin/sverchok/files/973162/untitled.zip)

**Comment by zeffii** [comment]
likely the scale of your object it too large. see:
https://github.com/nortikin/sverchok/issues/1302

**Comment by zeffii** [comment]
because this is the second observation concerning this limitation, i think it makes sense to add `epsilon` as a parameter in the N panel (draw buttons ext) for that node. ( already on my todo for some time... )

**Comment by Durman** [comment]
@zeffii 
Thanks. Scale helped me.

**Comment by zeffii** [comment]
closing now. but will fix later.. maybe today.
