### ISSUE TITLE
Maybe SVG Importer Node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1624]
I am looking at this Freestyle to GPencil Exporter:
https://github.com/folkertdev/freestyle-gpencil-exporter

Maybe that code is incomplete, but I found actually Freestyle to SVG Add-On in Blender which can export out SVG based on Frestyle Strokes.

I don't know the limitation yet, but I got a few ideas that might be nice and can be transferred into Sverchok. Especially since Freestyle can do outline stroke.

What needed for now is maybe SVG Importer node and would be nice to be able to do that as sequence.

Blender can import SVG and it comes as multiple curves. Maybe a tweak can join the curve into a single object.

I have a dejavu feeling, I swear I tried this SVG importing thing at some point.

What do you think?

**Comment by enzyme69** [comment]
So far my setup is like this:
![screen shot 2017-05-04 at 12 02 58](https://cloud.githubusercontent.com/assets/3952687/25688348/a915f318-30c1-11e7-8ee0-39cb5a88fad7.png)

I can do this manually:
1. Load a single SVG artwork, get all the curves
2. Run the node tree above in a Blend (loading all the Curves of SVG)
3. Get the Sverchok processed Curve
4. Delete all
5. Go back to step 1 for next frame.

Actually Polyline Merge is super handy, as we will end up with a single Curve Object from Sverchok.

**Comment by enzyme69** [comment]
So far so good, but still manual process, this manual process can be pythonized, I think.

![screen shot 2017-05-04 at 12 12 30](https://cloud.githubusercontent.com/assets/3952687/25688502/fcbd9c72-30c2-11e7-9dd1-095f5c4079c0.png)

This might lead into something nice.

But current SVG is just outline stroke with fill and Grease stroke should be varying in thickness.

I am curious with Freestyle to GPencil stroke script... hmmm... it does not load as addon somewhat.

**Comment by enzyme69** [comment]
Whoa... apparently it loads. This can be sweet.

![screen shot 2017-05-04 at 12 24 51](https://cloud.githubusercontent.com/assets/3952687/25688700/c098ca44-30c4-11e7-90e9-3e60e7ce56f8.png)

**Comment by enzyme69** [comment]
![screen shot 2017-05-04 at 12 38 15](https://cloud.githubusercontent.com/assets/3952687/25688926/92bea9de-30c6-11e7-9011-b3194009849c.png)

Kind of semi 3D. Maybe 2.5D generator.

It works really well with Zeffii GP and Polyline workflow. Not sure what this is for apart from quick way of generating outlines.

**Comment by enzyme69** [comment]
![screen shot 2017-05-04 at 13 02 07](https://cloud.githubusercontent.com/assets/3952687/25689268/ea62652e-30c9-11e7-9152-8980aab80516.png)

**Comment by enzyme69** [comment]
Currently the FS to GP script seems to generate the GP projection after "Render" triggered. Not quite real time, but after it generates the Grease Pencil, it become baked realtime for that particular frame and Sverchok can access the Grease Pencil.

I think this is great for Freestyle user, but also opening up a lot of possibilites.

**Comment by enzyme69** [comment]
I remember this semi fake 3D flat lamp..

![screen shot 2017-05-04 at 13 20 49](https://cloud.githubusercontent.com/assets/3952687/25689554/8a8656d0-30cc-11e7-80a6-a396251bffc5.png)

**Comment by enzyme69** [comment]
What cool is actually this thing "project" freestyle and generate grease which can be converted to 3D ish per projections, despite outline only. 

If we have 3D scan data, we can perhaps generate some kind of line detection, albeit can be slow if heavy.

**Comment by enzyme69** [comment]
![freestyle_stroke_combo_002](https://cloud.githubusercontent.com/assets/3952687/25689944/ad4e4ce2-30cf-11e7-8f99-ae888e5e73ae.png)

I guess the final conclusion for now is that:
If we can generate the Grease Pencil Freestyle thing on the fly without having to hit the render button each time, then it will quite awesom.

**Comment by zeffii** [comment]
1. You should really ask the devs of freestyle why the render step is needed. Or ask them to point you to an already written explanation. Maybe even ask on BSE why that is so it reaches more people.

2. svg input node? sounds great, if you really want that - you will code it. 

A very basic svg input node can be made relatively easily, but SVG has many implementation details and specs - even writing a basic implementation will be a rude awakening into how complex simple stuff can be.

**Comment by zeffii** [comment]
seems like your blog is a better place for fleshing out these things, than the Sverchok issue tracker.

**Comment by enzyme69** [comment]
![screen shot 2017-05-04 at 19 29 41](https://cloud.githubusercontent.com/assets/3952687/25697892/0fb4aa7c-3100-11e7-8acf-ab3201901ec5.png)

Ok got it~

**Comment by zeffii** [comment]
there is a `render_post` event handler btw ( we don't implement it in Sverchok ) 
https://docs.blender.org/api/2.61/bpy.app.handlers.html

This can trigger a callback after a frame is rendered, The API docs show how to add such an event handler to Blender's update system (and what the code should look like). A callback is really just an entry point for you to trigger some other bit of code. (like an update of a specific node tree )

```python
    ntree = bpy.data.node_groups['NodeTree']
    ntree.update()
```
if you want to update from a specific node only that's a bit more complicated, and probably not worth the granularity before understanding how the mentioned stuff works.
