### ISSUE TITLE
Grease Pencil Frame Delay

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1625]
Trying to render this out, but there is this frame delay thing so that I ofset the Grease Pencil, but on top of that, I am having this ever changing Grease Pencil per frame, and Sverchok does not seem to catch up during render: (it's okey during 3D view playback)

[sv_gp_fs_013_2017_05_04_11_35.zip](https://github.com/nortikin/sverchok/files/975964/sv_gp_fs_013_2017_05_04_11_35.zip)

Wondering why.

**Comment by enzyme69** [comment]
![fs_gp_sv_006](https://cloud.githubusercontent.com/assets/3952687/25701916/dce51c96-3111-11e7-8408-037af068faec.gif)

I am thinking to bake it into Alembic, but it exploded. I think the reason is because of this changing mesh. But... maybe I can bake as mesh not curve. Will try...

**Comment by zeffii** [comment]
> Wondering why

is the FS Lineset baked to frames? If so you'll still get the delay frame - it's a known issue without a solution.

why I don't really know (and that's also why this isn't "fixed" yet), it might be necessary to have a dedicated GP Selector node (also already mentioned before) with a frame input socket for the 'pick frame' mode.

**Comment by enzyme69** [comment]
In this case it is not just the one frame delay, it's more like Blender stops updating the node tree once it is rendering. This is strange, because normally I think Blender updates the frame and cook everything and then renders.

I think a possible hack is to force update Sverchok without relying on Frame Update.

OpenGL Animation Render actually works. But this defeat the purpose of already baking every Grease Pencil into mesh. This should work somewhat I think.

**Comment by enzyme69** [comment]
What would be a "force process node tree layout" before the render time? This might be the key. I can use AN to force process SV node tree.

**Comment by enzyme69** [comment]
I manage to render this one out! Simply by forcing everything:
- Using AN to modify the Curve Bevel 
- Also instead of Curve, I am forcing Sverchok to output BMesh Viewer and render that instead of the Curve.

Machine gets really hot when rendering this.

**Comment by enzyme69** [comment]
Ha.. apparently the 3D mouse cursor needs to be in 3D viewport, while other layout is processing the render. So weird.

**Comment by enzyme69** [comment]
I think we can close this but will bring this up again when it happens. Viewer BMesh seems to force something before render.

**Comment by enzyme69** [comment]
Very likely Blender thing... having both 3d viewport screen and the render panel, force trigger update:

![fs_gp_sv_008](https://cloud.githubusercontent.com/assets/3952687/25732411/a160b7e4-3192-11e7-9d9e-214c24f63bdd.gif)
