### ISSUE TITLE
Grease Pencil -> Bones

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1626]
I am thinking to try to make a setup that streamline the Grease Pencil to Bone. This actually works already quite nicely like this:
1. Draw grease pencil (artist)
2. Grease Pencil become clean Edge Poly, resampled (SV)
3. Edge Poly merged together (SV) -> not sure this is necessary, maybe ok
4. Turn Edge into Skin Modifier (Artist Manual) -> This Part SV Mesher, but cause issue below
5. Create Armature via Modifier button
6. Armature connected to Skin and the rest is Bone Animation 
7. Bone animation using Sverchok -> awesome but complicated but this is already entering Rigging area, Bone and Constraints, etc.

[sv_bone_test_002_2017_05_05_12_51.zip](https://github.com/nortikin/sverchok/files/979041/sv_bone_test_002_2017_05_05_12_51.zip)

STEP No.4 issue
Currently there is one "broken connection" is from Skin Mesher to Bone. Because the way Skin Mesher was designed, when I hit the "Create Armature" button in the modifier, I am getting something like below:

![screen shot 2017-05-05 at 22 48 14](https://cloud.githubusercontent.com/assets/3952687/25746069/15c4887a-31e5-11e7-8e5c-fe3f33caef80.png)

If User actually bake the edge and create skin modifier then add the Root, we get a good result.

![screen shot 2017-05-05 at 22 56 05](https://cloud.githubusercontent.com/assets/3952687/25746266/0c114a92-31e6-11e7-879e-df7d2e31c879.png)

Maybe the option here is:
- Skin Mesher needs tweak so that it works more like when we apply Skin Modifier into Edge
- Some kind of Bone generator directly from Sverchok -> SV Bones

What do you all think?

**Comment by enzyme69** [comment]
Aha... Zeffii is Groot, I remember this:

https://github.com/nortikin/sverchok/issues/939#issuecomment-257175967

**Comment by enzyme69** [comment]
Ok, with Skin Mesher, I remember the conversion where you mark all as Root.

Actually with Step No.4, I think Bmesh Viewer out the Edge and user manually add Skin Modifier and then add Root Skin in Edit mode should be okey.

In a way, 2 steps of Sverchok node:
1. Build the bones, bake it and stop updating
2. Animate the bone rotation.

Animating bones procedurally can be super interesting actually. Blender itself does not have Spline IK, ideally I think every point simply correspond to Bone Location...

_to be continued_

**Comment by zeffii** [comment]
i'm pretty sure armature can be scripted 100% without any skin modifier.

**Comment by enzyme69** [comment]
@zeffii now that's something I did not think of. I do like the Skin Mesher -> Create Armature step. 

I will research on ... Blender Spline IK.

**Comment by enzyme69** [comment]
Correction, Blender also has Spline IK, which means it's pretty easy now, we can use location to move the bones. 

![screen shot 2017-05-05 at 23 28 55](https://cloud.githubusercontent.com/assets/3952687/25747408/b8b71912-31ea-11e7-9708-10ec4ed952fc.png)

So GP can be used to pose bone.
