### ISSUE TITLE
Normal at Grease Points

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1628]
I am trying to build this Great Grease Stair thing and encounter an interesting situation:

![screen shot 2017-05-07 at 12 23 19](https://cloud.githubusercontent.com/assets/3952687/25777416/144b6c98-3320-11e7-8b75-603e0d36cf71.png)

Very often I wanted to find out the "normal" at particular point of grease pencil to help correcting "Twist" of perhaps making instance to "stand" properly. Especially when I use Polyline Viewer to make this "flat" strokes.

Maybe I will make an example setup first using modifier and drawing grease and try to find out the normal. 

Currently one idea I could think of is using one of Object ID Normal.

**Comment by enzyme69** [comment]
One unfortunate thing: Grease Pencil strokes does not stick to the surface...

**Comment by enzyme69** [comment]
![screen shot 2017-05-07 at 12 31 27](https://cloud.githubusercontent.com/assets/3952687/25777447/1f9933ea-3321-11e7-9ab5-659d75ff9ce5.png)
[grease_point_normal_003_2017_05_07_02_31.zip](https://github.com/nortikin/sverchok/files/981288/grease_point_normal_003_2017_05_07_02_31.zip)

This is a quick standin up trick, but if we like to have a normalized tilt....

**Comment by enzyme69** [comment]
A more careful observation... looks like the Curve somewhat has Tilt already. Hmm..

[grease_point_normal_003_2017_05_07_02_34.zip](https://github.com/nortikin/sverchok/files/981289/grease_point_normal_003_2017_05_07_02_34.zip)
![screen shot 2017-05-07 at 12 34 37](https://cloud.githubusercontent.com/assets/3952687/25777466/9e72b420-3321-11e7-9789-83aa98008961.png)

**Comment by enzyme69** [comment]
Would be nice to have a node that just simply tell you: ok this is the normal pointing out based on the projected point on X surface.

**Comment by zeffii** [comment]
you have two things here. 
   1. points that form a path
   2. a terrain

pass the points of the path and the points of the terein to kdtree to find the indices of the closest points on the terrain, then with the indices get the normals using any of the nodes that get normals.

if we make a node very every situation, then why bother with a modular system.

**Comment by enzyme69** [comment]
Got it, I will try thanks!
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
also... there is a raycast node...

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25796617/7808b24e-33da-11e7-9202-89cb346673e9.png)

**Comment by enzyme69** [comment]
Cheers Zeffii! Exactly what I need, sorry didn't come back earlier, was a bit busy. Will use this soon~
