### ISSUE TITLE
Strangeness regarding BMesh Normal affecting Tissue Tesselation Instancing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1634]
I am currently meditating and studying this Tissue Add-On, this is more or less something that work together with Sverchok:
https://github.com/alessandro-zomparelli/tissue

The Tissue add-on is like **SV Adaptive Polygon** but it does a bit more, maybe @ly29  can explain. But I save that for later. In this one I wanted to point out a strange thing that I found when using both Add-On.

My idea is to generate Component and Base mesh using Sverchok, and then combine the two as Complex Tesselated 3D Mesh using Tissue Addon.

The funny thing is that, Sverchok generated Base Mesh often gave a flat tesselation result:
![screen shot 2017-05-09 at 11 13 06](https://cloud.githubusercontent.com/assets/3952687/25831807/d934531e-34a9-11e7-91ce-e1376c001040.png)

ABOVE: Grid Mesh via Blender, the resulting mesh has thickness Z that I can control using Tissue.
BELOW: Sverchok generated Grid Plane Mesh, it results in 0 thickness and I cannot control using Tissue Add-On.

I tried many times, and only if I duplicate the generated Sverchok mesh, then go to Edit Mode and do Normalize, then I am getting a proper "thickness" in the Tissue mesh.

What could be the issue here?

**Comment by enzyme69** [comment]
Made a quick video showing the quirk:
https://youtu.be/bApfgkGfLQY

Is there a way to reset the surface normal? I know there is Recalculate Normal node, but it does not work, I tested it :(

**Comment by enzyme69** [comment]
Ok, it's Sverchok quirk apparently, but "Calculate Normal" is important for Tissue.

![screen shot 2017-05-09 at 11 35 59](https://cloud.githubusercontent.com/assets/3952687/25832085/bf2fad54-34ab-11e7-8aea-b26c07e7dcf0.png)

Glad I figured this out here.

**Comment by zeffii** [comment]
>  I wonder why it is not on by default? Maybe to save calculation time?

exactly.
