### ISSUE TITLE
Selecting Scene object Verts, Edges, Faces Procedurally 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1637]
I tried this setup:

![screen shot 2017-05-09 at 23 00 27](https://cloud.githubusercontent.com/assets/3952687/25852032/5b9a63f0-350b-11e7-8a30-48a32b3106eb.png)

Basically wanting to test selecting poly face randomly. It works, but it crashes Blender every time. Somewhat the setup making everything very unstable.

Any idea how this could work better?

**Comment by zeffii** [comment]
if using `.data` directly, you have to place the object in Object mode first, then make the selection. Else you have to use bmesh_from_editmesh  ( see the python templates in TextEditor)

**Comment by zeffii** [comment]
i think this goes into an infinite loop because as soon as you trigger a scene update , sverchok is triggered once, and if sverchok is setting an object property, a scene update is triggered, _..ad infinitum_.

**Comment by zeffii** [comment]
Earlier today I added an operator function to SNLite (not yet in master) , that would let you write a lite-weight operator to perform a one off procedural selection - when triggered

**Comment by zeffii** [comment]
Click that socket while in Object mode
![image](https://cloud.githubusercontent.com/assets/619340/25860810/07d37dd8-34e3-11e7-9c06-f149115a9ff9.png)

**Comment by enzyme69** [comment]
@zeffii Got it, but this will not be updated per frame basis?

**Comment by zeffii** [comment]
I can't be certain of that. All this is trivial if you are willing to write some code, i'm not going to sink time into this.
