### ISSUE TITLE
List split node with several input numerals.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1642]
List split node can receive only one numeral for split size. Is it possible to change this node? I want receive [10,11,],[12,13,14],[15,16,17,18] for my example. May be I am going wrong way?

![2017-05-10_15-20-13](https://cloud.githubusercontent.com/assets/28003269/25896223/4fe1126e-3594-11e7-8023-90bdfe3e211d.png)

**Comment by zeffii** [comment]
in python `.split()` concept is for generating equal size splits of an iterable. I think what you're looking for is `list slice`..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25897738/59a700a2-3589-11e7-86e1-e3bb6c8504b4.png)

**Comment by zeffii** [comment]
same question: https://github.com/nortikin/sverchok/issues/1142

**Comment by zeffii** [comment]
But.. i don't think it's a crazy idea to have a List Slice mode that takes as input a list of slice lengths, and calculates the start/index automatically for us. That's totally sane to want.

i might add that.

**Comment by Durman** [comment]
@zeffii Thanks. I will use search next time.))
