### ISSUE TITLE
I am new to Sverchok - Where do i ask questions

### ISSUE THREAD

**Issue by bcraig6973** [nortikin/sverchok#1643]
Hi there I am also new to this site GitHub 
so my  apologies if I'm writing this in the wrong place I donot know where do go to ask questions 
 can some please Lead me to the  correct area for us questions Thank You Inadvance God Bless

**Comment by nortikin** [comment]
ask question here or blenderartists.org sverchok theme

**Comment by zeffii** [comment]
The [GitHub issue tracker](https://github.com/nortikin/sverchok/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) is for reporting bugs and discussing technical queries. We don't mind giving support for general Sverchok questions here (within reason..and time constraints). 

   - [BlenderArtists.org sverchok thread](http://www.blenderartists.org/forum/showthread.php?272679) If you have general questions,
   - [blender.stackexchange](http://blender.stackexchange.com/) (tag the question with `sverchok`) , (has a large audience)
   - [VK](http://vk.com/public35076122) (russian sverchok group)
   - [Google+](https://plus.google.com/communities/113245231013159497850) (generally english language group)

**Comment by bcraig6973** [comment]
Thank You Sir 
First I just want say Thank You  for all the team and head developers for coming up with this idea
  for visual programming for  interactive visual feedback  with nodes 
I am myself been learning the basic of Python and wanted to use it with blender
When I cam across this I though this could help me with me learn  Learning curve 
would I be  correct in assuming that or my missing something?
Thank You Inadvance 
P.S. I also put on blenderartist.org for others that may be thinking in this way

**Comment by zeffii** [comment]
What you get out of Sverchok will be directly proportionate to the amount of effort/time you put into it. There are no shortcuts. 

While Python knowledge isn't needed for most users, it does become useful when you want to extend the standard set of nodes that we offer. There are plenty of online Python courses that will help you get a working understanding of Python, and Sverchok's source is free to modify/read. There's nothing stopping you from experimenting with the code to make it do what you want.

**Comment by zeffii** [comment]
@bcraig6973  don't ask the same question in multiple places.  If we need to answer a question here because of its technical nature we'll respond on the other site with a link to the issue-tracker here.

**Comment by bcraig6973** [comment]
Thank You guys 
If I have a suggestion for possible future updates do I post them Over here ?

https://github.com/nortikin/sverchok/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc


"The GitHub issue tracker is for reporting bugs and discussing technical queries"

**Comment by zeffii** [comment]
Use the search feature inside the issue tracker before asking/suggesting - chance is high that we already talked about or implemented it. If the search comes up with no results, feel free to start a new issue.

**Comment by zeffii** [comment]
(closed because i believe this question is now answered in full - and we close questions fast)
