### ISSUE TITLE
Node tree does not work in group.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1645]
I have two equal node tree. One of them I contained in group and after that it did not work, why?
https://gist.github.com/39a999a63ccabbbcd523a91f8d5a684e

**Comment by zeffii** [comment]
share the .blend instead.

**Comment by zeffii** [comment]
do you mean when you edit the content of a monad, that the output doesn't change until you leave the monad?

**Comment by Durman** [comment]
@zeffii 

![bug2](https://cloud.githubusercontent.com/assets/28003269/25928605/1fe888d8-360e-11e7-95c0-621e1af8aad7.gif)
[test.zip](https://github.com/nortikin/sverchok/files/991652/test.zip)

**Comment by zeffii** [comment]
if a set of nodes is indentical to an existing mona, you can just use an instance of the monad ( either duplicate it.. or you'll see the named Monad in the Group menu.

**Comment by zeffii** [comment]
btw, sometimes if a Monad Node turns red, you can trigger it into action by clicking on any of its sockets (worth a try).

Thanks for the report, i'm still looking at solutions in the development branch of Monads. no ETA.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/25940678/3090d43c-3637-11e7-9e13-605b845d1167.png)

**Comment by zeffii** [comment]
@Durman   I advise you to start Blender from a terminal / console (or open console  from Blender if you're on windows) and pay attention to the errors / exceptions that it displays in these cases.

that seems to be the problem there, else  -- reopen or help us by narrowing the problem down to as few nodes as possible.
