### ISSUE TITLE
Custom Defaults for nodes. (already in master)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1653]
### Node Defaults

When we (as coders) submit a node, we decide on sane defaults. Sometimes those defaults are not optimal for you (the user). If you find yourself always tweaking the parameters of a node before using it, then you might want to define custom node defaults. 

We can now configure node defaults from a _.json_ file. 

##### datafiles/sverchok/node_defaults/node_defaults.json
```json
{

    "SvGenFloatRange": {
        "props": [
            ["stop_", 1.0],
            ["count_", 20],
            ["mode", "FRANGE_COUNT"]
        ]
    },

    "ViewerNode2": {
        "props": [], 
        "function": "view3d.init_vdmk2"
    }
}
```
All we have to do is create key, value pair for each node.

- key: ( the node's `bl_idname`) 
- value: Currently the `value` accepts two directives (but can be extended later)

    1. `props`  ( _push props in sequence with a list of prop_name, prop_value pairs._ )
    2. `function` ( _push a function:_ in the example below the function is referenced as `view3d.init_vdmk2`. read that as `filename.function` and filename shall be located in `datafiles/sverchok/node_defaults/` )

##### datafiles/sverchok/node_defaults/view3d.py
```python
import random
import colorsys

import bpy



def init_vdmk2(node):

    def fold_color(color, shift):
        h, s, v = colorsys.rgb_to_hsv(*color)
        return colorsys.hsv_to_rgb(shift, s, v)

    A = [0.938000, 0.948000, 0.900000, 1.000000]
    B = [0.500000, 0.752000, 0.899000, 1.000000]
    C = [0.030100, 0.488000, 0.899000, 1.000000]

    shift = random.random()
    node.vertex_colors = fold_color(A[:3], shift)
    node.edge_colors = fold_color(B[:3], shift)
    node.face_colors = fold_color(C[:3], shift)

    node.edge_width = 1.0
    node.vertex_size = 2.0

```

------------------

Each time you add a node, the `node_default_dict` is checked if the `bl_idname` has an entry. 

- this has no effect on nodes that you duplicate, they clone their properties according to `self.copy()`
- this doesn't offer a visual way to set the preferences yet, that would be the next step.

**Comment by zeffii** [comment]
here's my current `node_defaults` dir / repo . it will be updated as i progress..
https://github.com/zeffii/node_defaults

**Comment by zeffii** [comment]
I didn't think of this during the implementation, there's a small (but important) todo. before this can be used without messing up your imported IO json layouts.

- iojson loading layouts will also first apply your defaults to nodes as soon as it's created, it will then apply the properties stored in the json. There will need to be a sverchok_global bool value to set when iojson is running.

**Comment by zeffii** [comment]
something like

```python
    def init(self, context):
        """
        this function is triggered upon node creation, 
        - freezes the node
        - delegates further initialization information to sv_init
        - sets node color
        - unfreezes the node
        - sets custom defaults (nodes, and sockets)
        """
        ng = self.id_data

        ng.freeze()
        if hasattr(self, "sv_init"):
            self.sv_init(context)
        self.set_color()
        ng.unfreeze()

        if not sverchok.io_json_running:
            set_defaults_if_defined(self)
```

**Comment by zeffii** [comment]
`<SverchCustomTreeType>.io_panel_properties.io_json_running`

**Comment by nortikin** [comment]
love an idea. usefull for advanced

**Comment by zeffii** [comment]
I  have not had time to push these last additions yet. I'm not even sure they are strictly necessary.  But there could be scenarios where the custom default applies complex code to a node ( or automatically add different nodes and connect etc..)

**Comment by zeffii** [comment]
Note to self: 

    ng.limited_info

After thinking about the name for a while. There could be other scenarios where we may want to restrict applying custom defaults. This is not solved yet.

**Comment by zeffii** [comment]
applied patch.. should work now.
