### ISSUE TITLE
Dual Mesh Tissue as a node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1654]
I am curious in what does it take to turn a process like below into a node?

https://github.com/alessandro-zomparelli/tissue/blob/b040f2cca393d7fbd6befac21029644b5000c2a9/dual_mesh.py

Probably I could try Script Node for this.

It is a once off operation, with few options. Done ✅ with a click of a button. I often wonder if this should be a node, or can be a node?

Can Sverchok perform every step to turn a mesh into dual mesh?

What do you think?

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/tissuenode

( don't bother trying - but by all means look at the code)

i started one a few days ago. but  have not had time to get it working. I think with some cleverness most of it might just be importing from the tissue addon. with a thin wrapper around the operators. But it wont be included as a standard Sverchok node, because it would rely directly on the presence of `tissue` in addons/addon-contrib.

If someone really wants this bad enough as a _live_ node, they'll have to replace all the `ops.mesh` calls  with bmesh.ops equivalents (i am not that person).

**Comment by zeffii** [comment]
actually. i'm not sure i even pushed the commits to the branch, so there is no tissue node to look at :)

**Comment by enzyme69** [comment]
It's gonna be my long time project, thanks @zeffii for some inputs!

**Comment by meta-androcto** [comment]
hi, just a heads up, tissue will be in contrib or release soon, also there's a duel mesh function in geodesic domes

**Comment by enzyme69** [comment]
Ooh! Cool thanks!

**Comment by zeffii** [comment]
if the tissue code used all bmesh.ops and had a few modifications to the draw function / execute function, we could easily make it a live node. But i totally understand if Alessandro doesn't want balloon his code just to make it easier to implement as a node.

```
def apply_a_to_b(bm_a, bm_b, props):
    ...
    return bm_out
```

Not that it's hard, but it is time consuming and requires persistence from even for those versed in bmesh.

**Comment by zeffii** [comment]
just a pity I have no interest in this at all. (Despite my commenting here)

**Comment by nortikin** [comment]
Because many select operations in screen

**Comment by enzyme69** [comment]
My hack is to Script node the process every update:
- switch node view to 3d view, run process on object and back to node view

It crashes Blender sometimes.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
Zeffii mention of "all bmesh operations" is interesting.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
@zeffii  https://github.com/nortikin/sverchok/issues/1391 Genius!
