### ISSUE TITLE
List Slice Lite (Beta)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1656]
https://github.com/nortikin/sverchok/tree/slice_mk2  (not mk2.. it's a Lite )

not finished yet, the part that isn't finished yet can be achieved using ListSplit node.

When slice_length is unconnected, it will generate equal slices using the Slider value (and repeat last value if the number of slices produces a remainder)

![image](https://cloud.githubusercontent.com/assets/619340/26196275/cab603ac-3bbe-11e7-9e80-6d40a0d3705f.png)

When slice_length is conneced and the input is a list of slice lengths, it will produce those

![image](https://cloud.githubusercontent.com/assets/619340/26196326/e6e4b852-3bbe-11e7-990d-bba36e387f4b.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26196857/8cd368b6-3bc0-11e7-837a-0838ac5c2942.png)

**Comment by Durman** [comment]
Good. I noticed that slice and split nodes have different behavior whit objects input, and slice is better.)

**Comment by nortikin** [comment]
not better, different needs

**Comment by JoseConseco** [comment]
There seems to be bug with new List Split. When last chunk size is equal to number of elements left in list, the node is not outputing this last chunk of list:
[https://image.prntscr.com/image/KS0gslclS2Cn34CFSAaoNQ.png](https://image.prntscr.com/image/KS0gslclS2Cn34CFSAaoNQ.png)

**Comment by zeffii** [comment]
>  new List Split.

I think you mean the relatively new `List Slice Lite` node. OK, yeah that look like the wrong output for the given input.

**Comment by zeffii** [comment]
fixed. https://github.com/nortikin/sverchok/commit/136801600131f9197b68a7cc96e954fc6bc292b0
