### ISSUE TITLE
Sverchok and Particle Hair

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1659]
Is it possible to source Particle Hair into Sverchok without baking?

![screen shot 2017-05-19 at 13 44 24](https://cloud.githubusercontent.com/assets/3952687/26232420/76c9772a-3c99-11e7-8b08-b811972c6beb.png)

**Comment by zeffii** [comment]
why not experiment with SNLite, and figure if that's possible

```
"""
in obj_in o
out data v
"""

try:
    obj = obj_in[0]
    # print(ddir(obj.particle_systems[0]))
    psystem = obj.particle_systems[0]
    for d in psystem.particles:
        data.append(d.location[:])
    data = [data]
except:
    ...
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26241014/786f2a0e-3c83-11e7-8fc7-8226103c4cb6.png)
```python
"""
in obj_in o
in totals s d=100 n=2
in steps s d=5 n=2
out data v
"""

try:
    obj = obj_in[0]
    psystem = obj.particle_systems[0]
    
    for idx in range(totals):
        for step in range(steps):
            data.append(psystem.co_hair(obj, particle_no=idx, step=step)[:])
    
    data = [data]
except:
    ...
```

**Comment by enzyme69** [comment]
I am currently testing another way using Particle Instancer and Hair. The instance object is from Sverchok. Works a treat too. 

Thanks for example @zeffii  I will check this!
