### ISSUE TITLE
Monad with Loop

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1662]
in order for this to work, you need to rearrange the sockets to be of the same type for the input and output. 

![image](https://cloud.githubusercontent.com/assets/619340/26275235/58fdf3ec-3d5c-11e7-9af0-e11714de8a2b.png)

![image](https://cloud.githubusercontent.com/assets/619340/26275241/6cca588e-3d5c-11e7-8dbd-34fff27693a2.png)

https://github.com/nortikin/sverchok/pull/1661 (unmerged monad loop branch)

**Comment by zeffii** [comment]
![biiiiiii](https://cloud.githubusercontent.com/assets/619340/26276304/f8728a24-3d74-11e7-8b27-fed6f1e8bfa3.png)

**Comment by zeffii** [comment]
i think sverchgrouptreenode/monad needs to show the UI of the monad node in the properties panel while inside the node.

**Comment by zeffii** [comment]
if more than one Instance exists of the node, then the monad UI is hidden (not sure if that makes sense... but that's how it's implemented atm)

![image](https://cloud.githubusercontent.com/assets/619340/26282270/85f09bd6-3e0e-11e7-9bea-b8fb4384b816.png)

**Comment by zeffii** [comment]
![biiiiut4](https://cloud.githubusercontent.com/assets/619340/26282666/0b267b66-3e16-11e7-9ef7-aa763a40abc8.png)

**Comment by portnov** [comment]
`edit!' button in editor panel looks... odd... :)

**Comment by zeffii** [comment]
haha! yes.. i'll look at suppressing it

**Comment by zeffii** [comment]
gone !

**Comment by zeffii** [comment]
it's pushed now.  no good examples yet..

**Comment by enzyme69** [comment]
![screen shot 2017-05-22 at 11 46 06](https://cloud.githubusercontent.com/assets/3952687/26289556/54d79c62-3ee4-11e7-85aa-9e7e2e3c3081.png)

@zeffii 👍 my jaw dropped.

**Comment by enzyme69** [comment]
I wonder if we can start with a grid.
Then we random pick poly face.
Subdivide it.
Then from those subdivided, we subdivide, smaller.
And smaller.

**Comment by zeffii** [comment]
i've added `Current Index` and `Current Total`

![image](https://cloud.githubusercontent.com/assets/619340/26412964/bb8cbc72-40aa-11e7-80e4-7d8ab12f0d99.png)

**Comment by enzyme69** [comment]
@zeffii Is Monad x Loop still working?

**Comment by zeffii** [comment]
monad is not properly working yet

**Comment by enzyme69** [comment]
Ok no wonder sometimes I think it works brilliantly and some other times it does not ...  but when it works, it is brilliant. I am studying your inset and random face select. That's a very good example.

**Comment by zeffii** [comment]
monad is unfortunately a pesky bit of code to maintain, and right now I prefer to do other things.
