### ISSUE TITLE
Monad Loop and limitation why

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1666]
![screen shot 2017-05-22 at 23 38 09](https://cloud.githubusercontent.com/assets/3952687/26311471/c2d620ea-3f47-11e7-826f-658b63bb89cf.png)

[select_center_extrude_001_2017_05_22_13_38.zip](https://github.com/nortikin/sverchok/files/1018998/select_center_extrude_001_2017_05_22_13_38.zip)

I noticed the loop limitation of N, why is this? Is there a way to increase the number without going inside the code?

Also... with what I am trying to do, can we get an effect where the number is getting smaller and smaller or bigger and bigger on each loop?

**Comment by zeffii** [comment]
1. the loop limit is hardcoded, but it is arbitrary.

2. There are many ways to apply a factor to each iteration, one way would be to add a float socket to input and output, 
```text
    verts ->                    algo          ---> verts out
    faces ->                    algo          ---> faces out
    f ----> math x/y ---------> algo
                        \
                          \--------------------->f output
```
you could also pass a list unchanged in and out, and an additional integer in / out that is +1 during each loop to get the next element

**Comment by zeffii** [comment]
i thought this would work.. but it may require some extra 'coercing' :)

![image](https://cloud.githubusercontent.com/assets/619340/26318238/ce76fe74-3f1a-11e7-9dc8-d443b2e467e0.png)

**Comment by zeffii** [comment]
@enzyme69  in your example you need to move the center of the radius too, with each iteration.

**Comment by zeffii** [comment]
I think that at the moment you need to have a physical socket linked to all inputs and outputs of the monad.. -- this feature is not heavily tested yet, but I do want it to work correctly -- it _will_ be fixed.

**Comment by zeffii** [comment]
[chupaaa_2017_05_22_20_31.zip](https://github.com/nortikin/sverchok/files/1020138/chupaaa_2017_05_22_20_31.zip)

![image](https://cloud.githubusercontent.com/assets/619340/26327236/df2fe9be-3f3e-11e7-9aa2-197fd924d500.png)

it does already work, but i'll be the first to say out loud that it's a little awkward to force the monad output socket to be 'must be connected' for it to work correctly in loop.

**Comment by enzyme69** [comment]
Interesting!! Thanks for this functionality Zeffii, I can start to think of ideas and actually this concept.

I actually tried doing this:
- Multiple Monad piggy chaining
- Monad inside Monad and endless loop... 🗡

**Comment by enzyme69** [comment]
![screen shot 2017-05-23 at 15 29 09](https://cloud.githubusercontent.com/assets/3952687/26339638/9c1fb030-3fcc-11e7-8b81-add8655d6f0a.png)

Offset thing is interesting.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26344536/44c62d9a-3fa0-11e7-8a4d-3cc0ccb22e9b.png)

![image](https://cloud.githubusercontent.com/assets/619340/26344603/8c0239b0-3fa0-11e7-8f4d-b63dc08a73a0.png)


i'm putting the max_count slider in the draw_buttons_ext and sidebar inside the monad, not on the monad node itself.

**Comment by enzyme69** [comment]
Thanks Zeff.. I am testing now. 

Trying to create vertex extrude that works in iterative way. Funny thing is: I kept getting just like a normal line.

1 - 2 
1 - 2 -3 
1 - 2 -3 -4

Was expecting:

1- 1 
1-2 1 -2 
1 -2 3 -4.

Wait... maybe I need to split into 2

**Comment by zeffii** [comment]
`split` and `vectorize` are ignored in loop mode. meaning you need to set up the data correct first.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26353145/3f91a254-3fbf-11e7-86ba-22db3a3cc506.png)
