### ISSUE TITLE
Grease ID Selector Active Frame has behaviour changed...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1669]
![screen shot 2017-05-24 at 15 00 05](https://cloud.githubusercontent.com/assets/3952687/26387527/bce18198-4091-11e7-9ab1-af51e44cf460.png)

@zeffii 
Used to be able just to scrub the timeline frame and get the data updated per frame, just wonder if you made a change so that we can trigger the grease pencil "one frame delay" thing?

How to actually make this work now?

Cheers Zeff!

**Comment by enzyme69** [comment]
Ok it does actually work and with no more frame delay!

However, I found an occassionaly bugging, still trying to figure out how to trigger the bug. Other than that this is an improvement 👍

**Comment by enzyme69** [comment]
I think when the frame is outside the boundary, it's giving None, causing the bug, but I will investigate. Thanks for this feature!

**Comment by zeffii** [comment]
Nothing changed for the unconnected scenario. 

Active frame + frameinfo node has a new ( dumb ) routine. I think it might expect frame data on the first frame.

I recommend not using timeline scrub to trigger updates, maybe ill add a key combo for nodeview

**Comment by zeffii** [comment]
the function internally should be able to pick frames that exist or pick the last existing frame. For example if you have strokes on these frames

```text
f - - - f - - f - -
1 2 3 4 5 6 7 8 9 10
```
if you do a lookup on frame 2 there is no explicit frame, so it should use frame 1's data. (this is the intention)

However.. i think at present if you have this (no frame data on frame 1)
```text
- - - - f - - f - -
1 2 3 4 5 6 7 8 9 10
```
then nothing is returned.  I could make it so it returns the first frame data , but i haven't yet.

**Comment by zeffii** [comment]
but the fact that when it does work, and the frame delay is gone, tells me that this is the way to go.. it's just a little boring and definitely not complicated.

if you can generate from this 
```python
input = [5, 8]
start_end = [1, 10]
>>> [5 5 5 5 5 5 5 8 8 8] = some_function(input_frames, start_end)

input = [1, 5, 8]
start_end = [1, 10]
>>> [1 1 1 1 5 5 5 8 8 8] = some_function(input_frames, start_end)
```
then you have the solution.

**Comment by enzyme69** [comment]
Thanks so much for further explanation~ I was surprised :)

**Comment by zeffii** [comment]
all you do is complete the `some_function` so it doesn't produce an Assertion Error anymore. :)
```python
def some_function(inp, rng):
    remaps = []  # you fill this
    for i in range(rng[0], rng[1]+1):
        print(i)
    return remaps

input_frames = [5, 8]
start_end = [1, 10]
assert([5, 5, 5, 5, 5, 5, 5, 8, 8, 8] == some_function(input_frames, start_end))

input_frames = [1, 5, 8]
start_end = [1, 10]
assert([1, 1, 1, 1, 5, 5, 5, 8, 8, 8] == some_function(input_frames, start_end))
```

**Comment by zeffii** [comment]
it's a bit of a brain tease, expect to struggle with it.

**Comment by enzyme69** [comment]
:D a little puzzling for my level of programming skill.

**Comment by zeffii** [comment]
bullshit.

**Comment by zeffii** [comment]
this is the kind of barrier you need to break more often.  useful programming puzzles.

**Comment by zeffii** [comment]
Here's a solution i came up with. Don't read it before solving it yourself. (seriously you may come up with something nicer if you don't pollute your brain with my first attempt)

<details>

```python
def some_function(inp, rng):
    remaps = []  # you fill this
    last_valid = None
    for i in range(rng[0], rng[1]+1):
        if i < inp[0]:
            last_valid = inp[0]
        elif i in set(inp):
            last_valid = i
        elif i >= inp[-1]:
            last_valid = inp[-1]
        else:
            for j in range(len(inp)-1):
                begin, end = inp[j], inp[j+1]
                if begin < i < end:
                    last_valid = begin
                    
        remaps.append(last_valid)

    print(remaps)
    return remaps

input_frames = [5, 8]
start_end = [1, 10]
assert([5, 5, 5, 5, 5, 5, 5, 8, 8, 8] == some_function(input_frames, start_end))

input_frames = [1, 5, 8]
start_end = [1, 10]
assert([1, 1, 1, 1, 5, 5, 5, 8, 8, 8] == some_function(input_frames, start_end))

```

</details>

**Comment by zeffii** [comment]
https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect

let's see.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1671

i changed the default to `pick frame`. but may change back later.
