### ISSUE TITLE
Split (actual) Edge at Point, if Angle

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1675]
Blender has this Split Edge Modifier that works by splitting edges at certain angle of polygon face (it needs faces).

I am kind of wondering if this is something that is possible to do already using Sverchok? Just wondering if "split" under condition is possible already, like the easy simple way.

I imagine a line:

1---2---3---4---5

If 2---3 angle tangency is too big, maybe split?

Wondering what split is actually means. If we have Edge Indices [1,2],[2,3], with vector 1,2,3 that is a single line. But if I split the vertex at 2, does this mean, I need to repeat the vector twice at that point, so it becomes: [1,2],[3,4] where 2 and 3 are actually the same?

Maybe it's just a weird question, don't worry about it.

**Comment by nortikin** [comment]
angle node + item list or something + scripted node to separate
