### ISSUE TITLE
Sverchok and BGE procedural animation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1676]
I know how to run animation of baked animation in BGE. I am wondering if anyone has experiencing generating procedural animation actually for BGE, like:
https://www.youtube.com/watch?v=N2jbxH3BTyQ

The idea is to make like some kind of "Demoscene" materials that will loop or react to music.

Wonder if node-tree gets calculated somewhat in BGE?

I will research.....

**Comment by enzyme69** [comment]
Might be outside the scope of Sverchok, but still curious.

Found this:
https://www.youtube.com/watch?v=vVA8lUpA3lQ

And this:
https://blenderartists.org/forum/showthread.php?351526-Thoughts-about-procedural-animation-quot-blend-quot-template-included
https://www.youtube.com/watch?v=u0VnCdtCFCQ

There is an interesting link about interactive animation and procedural animation.

**Comment by zeffii** [comment]
blender.stackexchange.com
