### ISSUE TITLE
Sverchok Zine

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1679]
If I could make book, I probably make something like this:
https://issuu.com/emilylucchesi/docs/algorithmic_sketchbook/2?ff=true

Maybe I have 100 pages material, what do you think?

Can try replicating everything in this book and more.

**Comment by nortikin** [comment]
cannot open link

**Comment by enzyme69** [comment]
@nortikin Hmm... must be needing some kind of plugins. I maybe should take snapshot of every pages. This is really good, the Zine can be studied and adapted to Sverchok.

**Comment by enzyme69** [comment]
Will close this, but will keep Zine in mind. Mini booklet. Original ones.

**Comment by kalwalt** [comment]
i can open the link and i can confirm it this very interesting...!

**Comment by nortikin** [comment]
tor browser helped me well
thanks
