### ISSUE TITLE
Twistiness of Skin Mesh node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1681]
I made this quick and dirty procedural cactus setup in Sverchok. But found a lot of Twistiness from Skin Mesher. Is there a way to smooth it somewhat so that it is not twisting?

![screen shot 2017-05-29 at 11 10 29](https://cloud.githubusercontent.com/assets/3952687/26533667/acc71594-445f-11e7-9b39-650b2f7fd67a.png)

**Comment by enzyme69** [comment]
BLEND: 
[sv_cactussimple_003_2017_05_29_01_13.zip](https://github.com/nortikin/sverchok/files/1034660/sv_cactussimple_003_2017_05_29_01_13.zip)

**Comment by enzyme69** [comment]
If I bake poly edge structure, not using Skin Mesher node, I can get cleaner result.
![screen shot 2017-05-29 at 11 43 40](https://cloud.githubusercontent.com/assets/3952687/26534110/1b875ba2-4464-11e7-8fba-e213a688891f.png)

I recall this was mentioned at some point. I think Zeffii explained was that by design the Skin Mesher "root" at every edge.

**Comment by zeffii** [comment]
Not sure what's going on there.

**Comment by zeffii** [comment]
> by design the Skin Mesher "root" at every edge.

you mean root at every vertex.

**Comment by zeffii** [comment]
In recent weeks some changes were made to skin modifier's C code, this might have impact on skin mesher Node.

**Comment by zeffii** [comment]
it seems like `verts.foreach_set("use_root", all_true)` either never worked as I intended, or has stopped working. It seems the best place to force Mark Root is at junctions or tips, but not midway.

I have no immediate solution for this @enzyme69 . The algorithm is not too difficult

If i just bake the VDMK2, and manually add a skin modifier it produces this.
![image](https://cloud.githubusercontent.com/assets/619340/26545278/4f8f2b0e-4465-11e7-97a3-e08ab2f17a32.png)

**Comment by zeffii** [comment]
internally it will need to 

![image](https://cloud.githubusercontent.com/assets/619340/26553320/5a55728e-448b-11e7-8784-15d8657396eb.png)


1. find all disjoint elements of the input mesh (and their tips / joints)
2. find any rings
3. for each disjoint element pick a tip or a junction and mark it as root. 

While the example shows that the edges may be unordered, it should not matter ( user should provide correct input ) for finding a valid tip or joint.  Sequential vert-edge (polylines) are useful only if you plan to grow/shrink the radius of a vertex as a function of the vertex location in the polyline. (think tentacles...branches.... where the width closest to the trunk is larger than at the tip)

If a disjoint element
-  has two tips:  pick the lowest index.
-  has more than one function, like the junction with the most branches.
-  has multiple competing junctions (with same amount of branches) pick the junction with lowest index.

**Comment by enzyme69** [comment]
Got it~ ok I will use this information for now. Cheers~

**Comment by zeffii** [comment]
the Node doesn't expect multiple disjoint meshes, for that case an alternate method of root setting is being worked on.

**Comment by enzyme69** [comment]
Could it work more similarly to Polyline Viewer? If possible.

**Comment by zeffii** [comment]
in what way?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26581763/77b4d820-453e-11e7-9e96-2ec85d246edd.png)

**Comment by zeffii** [comment]
The default will continue to assume that there are no disjoint meshes per mesh. and that setting is called "mark all". But if you have lots of separated segments, then use "mark some".

The code i'm about to push is not particularly smart, and to understand it you are going to have to read it. Else trust that it's the best i can do with the constraint of time.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26582236/b2a8a81a-4540-11e7-9784-2851a8733677.png)
