### ISSUE TITLE
Selections

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1682]
I just closed 3 issues which all touch on selection of elements in some way. (elements being: verts, edges, faces)

 1. procedurally selecting elements of members of bpy.data.objects
 2. guided (boxes, sphere..etc) selection of sverchok mesh elements (with graphical representation of selection brush)
 3. selecting (with persistence if possible) elements in sv generated objects in bpy.data.objects, by going into edit mode in those objects.

I want to address them in one go..

1.  if it's truly procedural then you don't need to be in edit mode, and all that's needed is a new node. A dedicated node can be optimized 

```text
      
      [ object element selector ]
      ---------------------------
      |                 objects -
      | mode: mask / indices    |
      |                         |
      - objects                 |
      - vert indices            |
      - edges indices           |
      - faces indices           |
      |_________________________|
```
i think... but i might be wrong and the bmesh->obj conversion can be unstable. Of the elements only `verts` are guaranteed to match up.

2. This is not essential (but would be great).  I'd argue that being able to see this selection brush or not.. is not a strong factor in the usability of the tool. You can always see the result of a selection, if something isn't happening that you expect, then you don't understand the underlying parameters. The visual brush would help with that, but I did already show how to make a brush visible using VDMK2. I also get how that might seem like something that should be implemented in the node, and i agree to some extent. But just saying that won't make it happen.

3. i'm pretty sure that the selection (or the creation of selection lists) can be done using the node described in 2,

**Comment by Kosvor2** [comment]
Also selecting verts by feeding in polygons\edges lists this way:

![select_by_edge_poly](https://cloud.githubusercontent.com/assets/22656834/26591674/d2bec71a-4577-11e7-83b2-39763bcf3764.png)

**Comment by zeffii** [comment]
yes, `index`  or `mask`.

**Comment by enzyme69** [comment]
A while back ago, we have related case:
https://github.com/nortikin/sverchok/issues/98
https://github.com/nortikin/sverchok/issues/219

**Comment by Kosvor2** [comment]
Something like this: https://github.com/nortikin/sverchok/commit/3105cbe83c55b3f6afc816983b8edb0722ceea3f

**Comment by Kosvor2** [comment]
https://github.com/nortikin/sverchok/pull/2171

**Comment by Kosvor2** [comment]
![only_object_mode3567](https://user-images.githubusercontent.com/22656834/37584192-5089c7fa-2b76-11e8-8474-340cde4b2383.png)


May be there is a place for lite version which will be updating in Edit Mode (and most likely will work with only one object instead of list).
