### ISSUE TITLE
GIST Export Null

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1686]
I have noticed a lot of my GIST are actually empty. It seems like it is successful and copying something but failed.

For example, this cactus thing:
https://drive.google.com/open?id=0B0ogUwJ-NEFgM1BlZzgxdEVVQ0k

Try exporting the GIST.

**Comment by zeffii** [comment]
save the blend and drag it into this issue.

**Comment by zeffii** [comment]
save the blend/zipped and drag it into this issue.

**Comment by zeffii** [comment]
so all i have to do is open blender , and do the import zipped url.

**Comment by zeffii** [comment]
i see, from the console it displays a cause
```
[]
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 299, in create_dict_of_tree
    links_out.append(compile_socket(link))
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 95, in compile_socket
    return (link.from_node.name, link.from_socket.index, link.to_node.name, link.to_socket.index)
AttributeError: 'NodeSocketColor' object has no attribute 'index'

no update lists found or other error!
 - trigger an update and retry
sending
received response from server
https://gist.github.com/2e59b3302fa16d014e99d76eafa00615
```
i think this relates to the NodeRoute node ( i never use it.. so didn't test it with recent changes to gist IO )

**Comment by zeffii** [comment]
you are also using gpencil strokes... i'd just use `.blends` instead then. 

simple rule for you @enzyme69  --

Q. Am i using anything in the layout that uses something generated outside of Sverchok?
A.  if yes, (objects, GP strokes... materials....) use `.blend`

i'll fix the nodereroute issue (if that's the problem) ..  but the local references to Blender objects that are stored inside Nodes is not something that can be fixed without introducing binary storage.. meaning you might as well use .blends.

.json is really meant for simpler stuff.

**Comment by zeffii** [comment]
i can add extra unloading for the OBJ ID selector node.. because this can't be passed into json
```
{'bl_idname': 'SvGetAssetProperties', 'params': {'Mode': 'grease_pencil', 'gp_selected_frame_mode': 'active frame', 'Type': 'MESH', 'gp_layer': 'GP_Layer', 'gp_name': 'GPencil', 'frame_collection_name': [<bpy id prop: owner="NTSweep_Cactus", name="", address=0x0000021C35391C08>]}, 'color': (0.6079999804496765, 0.6079999804496765, 0.6079999804496765), 'label': '', 'height': 100.0, 'location': (-752.6806030273438, -267.0469665527344), 'hide': False, 'width': 210.0},
```
especially this
```python
'frame_collection_name': [<bpy id prop: owner="NTSweep_Cactus", name="", address=0x0000021C35391C08>]
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1688
