### ISSUE TITLE
Multiple Extrude, Normal at New Faces, Scale at confusion

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1687]
Been trying to do this correctly.

(Ideally: simple extrude along path, at the curve placed at point normal from each face.)

But I tried using Multiple Extrude anyway, so far getting headache and pulling hair:

![screen shot 2017-05-31 at 20 06 28](https://cloud.githubusercontent.com/assets/3952687/26627153/cbba0266-463c-11e7-9a85-494a047075af.png)

Where did I do wrong?
[multiple_extrude_001_2017_05_31_10_08.zip](https://github.com/nortikin/sverchok/files/1041008/multiple_extrude_001_2017_05_31_10_08.zip)

**Comment by enzyme69** [comment]
Extrude Separate Face gives the correct normal, although limited that it does not have Matrix control for next extrusion...

![screen shot 2017-05-31 at 20 09 17](https://cloud.githubusercontent.com/assets/3952687/26627237/1a77e4d6-463d-11e7-8cc0-e8b31ba131c3.png)

**Comment by enzyme69** [comment]
Do we need to operate on each face? Or we can pass in some vectorized "directions" for each face?

![screen shot 2017-05-31 at 20 19 12](https://cloud.githubusercontent.com/assets/3952687/26627632/7624609c-463e-11e7-8d5a-8f7c5a73a23a.png)

**Comment by enzyme69** [comment]
One by one makes sense.

[multiple_extrude_004_2017_05_31_10_25.zip](https://github.com/nortikin/sverchok/files/1041064/multiple_extrude_004_2017_05_31_10_25.zip)
![Uploading Screen Shot 2017-05-31 at 20.24.55.png…]()

**Comment by enzyme69** [comment]
I am think I am into something... but maybe not perfect.
[multiple_extrude_004_2017_05_31_10_30.zip](https://github.com/nortikin/sverchok/files/1041079/multiple_extrude_004_2017_05_31_10_30.zip)
![screen shot 2017-05-31 at 20 30 29](https://cloud.githubusercontent.com/assets/3952687/26628086/06a19d96-4640-11e7-8b31-b674149643df.png)

**Comment by enzyme69** [comment]
The issue is with scaling @portnov Seems to be affecting the "normal".

[multiple_extrude_006_2017_05_31_11_07.zip](https://github.com/nortikin/sverchok/files/1041216/multiple_extrude_006_2017_05_31_11_07.zip)

**Comment by enzyme69** [comment]
With and without scaling:

![screen shot 2017-05-31 at 21 07 00](https://cloud.githubusercontent.com/assets/3952687/26629342/4cb8dae2-4645-11e7-8d6b-9412a57637d7.png)
![screen shot 2017-05-31 at 21 06 47](https://cloud.githubusercontent.com/assets/3952687/26629341/4c799102-4645-11e7-961b-25773fd99af1.png)

**Comment by enzyme69** [comment]
Simpler setup:
[extrude_region_scale_issue_001_2017_05_31_11_18.zip](https://github.com/nortikin/sverchok/files/1041240/extrude_region_scale_issue_001_2017_05_31_11_18.zip)
![screen shot 2017-05-31 at 21 18 15](https://cloud.githubusercontent.com/assets/3952687/26629675/c6fa032a-4646-11e7-98fe-b520f80d74f1.png)

If I offset the object somewhere else in 3D space, "Scale" seems to be stuck. It should not behave that way, I don't think

**Comment by meta-androcto** [comment]
hi, hope you guys have looked at the new multi extrude in addons release (nightly builds)
it has more functionality you guys might find useful

**Comment by enzyme69** [comment]
Ooh.. There is multi extrude add-ons?? Is this Sverchok?

**Comment by zeffii** [comment]
@meta-androcto  what's the name of that .py file for multi-extrude i can't find it in https://git.blender.org/gitweb/gitweb.cgi/blender-addons.git/tree

**Comment by zeffii** [comment]
this i guess? https://git.blender.org/gitweb/gitweb.cgi/blender-addons.git/blob/b5d1d095fd6432182654f9bd0e5cc3ac8b76c2a1:/mesh_extra_tools/mesh_mextrude_plus.py

**Comment by zeffii** [comment]
i could totally convert that quickly @meta-androcto  it's just a pitty the code isn't a bit more modularized in the first place so we can just import a function and pass it parameters like 

```
from some_addon import perform_multi_extrude, named_property_collection, draw_ui

# masks ( vert / edge / faces selection if this can be supplied)
bm = perform_multi_extrude(pydata, settings, masks)

```

**Comment by zeffii** [comment]
@meta-androcto
![image](https://cloud.githubusercontent.com/assets/619340/26633294/355371e6-4613-11e7-8b21-5572f6be72cd.png)

**Comment by zeffii** [comment]
@meta-androcto see above

**Comment by zeffii** [comment]
it would be relatively easy to also accept a "start normal" for each masked face, rather than just the one

**Comment by enzyme69** [comment]
@zeffii Thanks for this one!! Very powerful interesting. Could the extrusion accept some kind of custom Matrix or function? :)

Now with the Extrude Region node, I think "Keep Original" option is broken or does not work with Multi.

**Comment by zeffii** [comment]
A more advanced mode for multi extrude alt is likely.  But. Not imminent

**Comment by enzyme69** [comment]
@zeffii  Thanks for this! and meta androco also say hello to Liero!

**Comment by Kosvor2** [comment]
```

    for v in bm.verts:    # is this really needed?
        v.select = False
    for e in bm.edges:
        e.select = False
    for f in after:
        f.select = f not in sel

```

**Comment by zeffii** [comment]
nope comment it out is fine.. i left it in just in case we go for a `bmesh socket` ...
