### ISSUE TITLE
error activating add-on

### ISSUE THREAD

**Issue by freder** [nortikin/sverchok#1693]
hi,

I just installed sverchok from the master branch zip file, but trying to activate it results in this error:
<img width="1335" alt="screen shot 2017-06-01 at 14 04 34" src="https://cloud.githubusercontent.com/assets/724844/26679176/3485cd6a-46d4-11e7-8b4e-841be257ca18.png">

**Comment by zeffii** [comment]
get a more recent version of Blender for osx.

`requests` is a standard python module, included in all official Blender releases (and that's why we use it). However some builds for osx didn't include the `requests` module.

Try a latest build for osx here:  https://builder.blender.org/download/

**Comment by zeffii** [comment]
same issue as here. https://github.com/nortikin/sverchok/issues/1279

**Comment by zeffii** [comment]
we could add code that detects if the `requests` module is found, and if it isn't then use appropriate fallback code. That's not likely to happen, also other add-ons will use `requests` too. 

i'm closing this issue because it won't result in changes to Sverchok. Hope you understand.

**Comment by zeffii** [comment]
I just checked the latest buildbot build for _osx_, it does contain `requests`, so that should work.

The alternative would be to add a fallback anyway..(but this is not in master yet, and kind of defeats the prupose of using requests in the first place..

##### sv_requests_fallback.py
```python

import json
import urllib
import urllib.request

def get(url):

    processed = lambda: None

    def get_json():
        json_to_parse = urlopen(url)
        found_json = json_to_parse.read().decode()
        wfile = json.JSONDecoder()
        return wfile.decode(found_json)        

    processed.json = get_json()
    return processed

```

and to check if the requests module is around
```python
try:
    import requests
except:
    import sverchok.utils.sv_requests_fallback as requests
```
