### ISSUE TITLE
3d Voronoi (i think)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1694]
how it works:
- takes a bounding box. (can be any shape)
- takes a point cloud (all points must lie in the bounding box)

```text
for each point in the cloud find n nearest points
    for each nearest point consider:
       - the line that connects both points as the normal
       - halfway between both points is considered the border point

for each point: 
    make a copy of the original bounding box, call it "working_geom"
    for point and resulting set of normal and border points:
        slice away (bisect using normal and border points slice plane and location) from working_geom 
        until all sets are handled for that point.
    the resulting mesh is a single cell.

```

all using bmesh ops and kdtree.

The latest iteration of the code is located in `node_scripts/SNlite_templates/voronoi3d.py`

<img src="https://cloud.githubusercontent.com/assets/619340/26685479/8f4cd07a-46ea-11e7-925c-2184407152ad.png" height="420"/> <img src="https://cloud.githubusercontent.com/assets/619340/26685504/9f84eacc-46ea-11e7-8952-933eb657d634.png" height="420"/> 

https://gist.github.com/fed8c6f323f6920360671a103b2a1d74
[pointcloud_v_plane_GET_EDGES2_ygtbk_2017_06_01_14_53.zip](https://github.com/nortikin/sverchok/files/1045166/pointcloud_v_plane_GET_EDGES2_ygtbk_2017_06_01_14_53.zip)

keywords: python, blender, simple, 3d, voronoi

**Comment by zeffii** [comment]
how it works:
- takes a bounding box. (can be any shape)
- takes a point cloud (all points must lie in the bounding box)

for each point in the cloud find n nearest points
    for each nearest point consider:
       - the line that connects both points as the normal
      - halfway between both points is considered the border point

for each point and resulting set of normal and border points, 
    slice away from a copy of the bounding box until all sets are handled for that point.
    the resulting mesh is a single cell.

**Comment by zeffii** [comment]
i added a bmesh_join method to sv_bmesh_utils :  https://gist.github.com/38c39d728bd5f214bd87ef09dea6ed01

**Comment by zeffii** [comment]
i've also added a more uptodate version in the snlite script folder.

![image](https://cloud.githubusercontent.com/assets/619340/26694939/69b27ba2-4709-11e7-86c7-f3a6334cd5ee.png)

**Comment by enzyme69** [comment]
![screen shot 2017-06-02 at 12 17 09](https://cloud.githubusercontent.com/assets/3952687/26708160/6f531e48-478d-11e7-9210-f7d79577e114.png)

That's totally awesome!!

Text Object -> Remesh -> Sv -> Mesh -> Particle Points Scatter

**Comment by zeffii** [comment]
yep.. it's pretty cool I agree. Unfortunately it's not a very smart algorithm (yet)

btw:
![image](https://cloud.githubusercontent.com/assets/619340/26715366/c3b97d6e-4775-11e7-9228-f0d3be67c64f.png)

means one of two things (or both?) 
- you might need more points in those regions 
- increase the value (in the script) for the nearest `find_range(vtx, 24)` from 24 to something higher.

**Comment by zeffii** [comment]
offroad "Voronoi Tire Generator"

![image](https://cloud.githubusercontent.com/assets/619340/26717704/a3cf5fb0-477e-11e7-9882-5a84a732844a.png)

**Comment by zeffii** [comment]
i've updated the snlite script in templates, 
- bounding_n , means it will pick the n closest points to form a cell from
- shrink, will scale the cell (0.001,..... 1.0) are sane values

**Comment by zeffii** [comment]
##### improvements to the algorithm

Speed has not been my focus, but now as I use it on more geometry i'm considering ways to make it faster, but splitting up the search geometry as early as possible. While python does introduce some speed bumps, it's quite possible to speed this up by better understanding which redundancies can be eliminated. (No ETA)

**Comment by nortikin** [comment]
![koltso11](https://cloud.githubusercontent.com/assets/5783432/26757659/5732ca96-48d4-11e7-8d3a-6ba054a6dcb5.png)

**Comment by zeffii** [comment]
closing the thread, but i'll work the SNLite script into a dedicated node, and work in some optimizations (optional switches for speed ups in certain scenarios)

nothing else to see here :)

**Comment by zeffii** [comment]
##### voronoi 3d from range distance

```python
"""
in verts_in v d=[] n=1
in obj_verts_in v d=[] n=1
in obj_faces_in s d=[] n=1
in shrink s d=0.9 n=2
in bounding_dist s d=0.2 n=2
in bisect_dist s d=0.00001 n=2
out new_verts v
out new_faces s
"""
from itertools import combinations
import bmesh
import mathutils
from mathutils import Vector
from collections import defaultdict

# from sverchok.utils.sv_bmesh_utils import bmesh_join
from sverchok.utils.sv_mesh_utils import mesh_join

locators = defaultdict(list)

size = len(verts_in)
kd = mathutils.kdtree.KDTree(size)
for i, xyz in enumerate(verts_in):
    kd.insert(xyz, i)
kd.balance()

for idx, vtx in enumerate(verts_in):
    n_list = kd.find_range(vtx, bounding_dist)
    for co, index, dist in n_list:
        if index == idx:
            continue
        pt = (((Vector(co)-Vector(vtx))/2)*shrink) + Vector(vtx)   #((.... ) * distor) + Vector(vtx)
        normal = Vector(co)-Vector(vtx)
        locators[idx].append((pt, normal))

__new_verts = []
__new_faces = []
for k, v in locators.items():

    working_geom = bmesh_from_pydata(obj_verts_in, None, obj_faces_in, normal_update=True)
    for pt, normal in v:
        geom_in = working_geom.verts[:] + working_geom.edges[:] + working_geom.faces[:]

        res = bmesh.ops.bisect_plane(
            working_geom, geom=geom_in, dist=bisect_dist,
            plane_co=pt, plane_no=normal, use_snap_center=False,
            clear_outer=True, clear_inner=False
        )

        surround = [e for e in res['geom_cut'] if isinstance(e, bmesh.types.BMEdge)]
        fres = bmesh.ops.edgenet_prepare(working_geom, edges=surround)
        bmesh.ops.edgeloop_fill(working_geom, edges=fres['edges'])  

    ___v, _, ___f = pydata_from_bmesh(working_geom)
    __new_verts.append(___v)
    __new_faces.append(___f)

_v, _e, _f = mesh_join(__new_verts, [], __new_faces)

new_verts.append(_v)
new_faces.append(_f)
```

**Comment by enzyme69** [comment]
Lots of interestingness here that could easily be overlooked. One day I will read all these SN nodes like novels.

**Comment by zeffii** [comment]
here a slight modification to current voronoi3d script..
```python
"""
in verts_in v d=[] n=1
in obj_verts_in v d=[] n=1
in obj_faces_in s d=[] n=1
in shrink s d=0.9 n=2
in bounding_n s d=14 n=2
out new_verts v
out new_faces s
"""
from itertools import combinations
import bmesh
import mathutils
from mathutils import Vector
from collections import defaultdict

# from sverchok.utils.sv_bmesh_utils import bmesh_join
from sverchok.utils.sv_mesh_utils import mesh_join

locators = defaultdict(list)

size = len(verts_in)
kd = mathutils.kdtree.KDTree(size)
for i, xyz in enumerate(verts_in):
    kd.insert(xyz, i)
kd.balance()

for idx, vtx in enumerate(verts_in):
    n_list = kd.find_n(vtx, bounding_n)
    for co, index, dist in n_list:
        if index == idx:
            continue
        pt = (((Vector(co)-Vector(vtx))/2)*shrink) + Vector(vtx)   #((.... ) * distor) + Vector(vtx)
        pre_normal = (Vector(co)-Vector(vtx))
        if pre_normal.length < 0.0001:
            continue
        locators[idx].append((pt, pre_normal.normalized()))

__new_verts = []
__new_faces = []
for k, v in locators.items():

    working_geom = bmesh_from_pydata(obj_verts_in, None, obj_faces_in, normal_update=True)
    for pt, normal in v:
        geom_in = working_geom.verts[:] + working_geom.edges[:] + working_geom.faces[:]

        try:
            res = bmesh.ops.bisect_plane(
                working_geom, geom=geom_in, dist=0.00001,
                plane_co=pt, plane_no=normal, use_snap_center=False,
                clear_outer=True, clear_inner=False
            )
        except:
            # print(pt, normal)
            continue

        surround = [e for e in res['geom_cut'] if isinstance(e, bmesh.types.BMEdge)]
        fres = bmesh.ops.edgenet_prepare(working_geom, edges=surround)
        bmesh.ops.edgeloop_fill(working_geom, edges=fres['edges'])  

    ___v, _, ___f = pydata_from_bmesh(working_geom)
    __new_verts.append(___v)
    __new_faces.append(___f)

_v, _e, _f = mesh_join(__new_verts, [], __new_faces)

new_verts.append(_v)
new_faces.append(_f)

```

ensures no doubles, mostly.

**Comment by zeffii** [comment]
[uzkebiki_2017_07_09_18_12.zip](https://github.com/nortikin/sverchok/files/1133951/uzkebiki_2017_07_09_18_12.zip)

**Comment by Fucaoult** [comment]
hello, great contribution. I would like to know how I can use it to create isosurfaces thank you very much for sharing!

**Comment by nortikin** [comment]
@Fucaoult 
there is pymcubes librery with same called scripted node presented in sverchok popup menu of scripted node light.
