### ISSUE TITLE
INSPIRATION: Archimatix

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1698]
This node based system is pretty cool :) Can be for our study and maybe start building some kind of library of shapes (we kind of did):
https://80.lv/articles/archimatix-parametric-modeling-extension-for-unity/

A lot of these can be done already via repetition, etc. What make this more solid presentation is the UV thing, which is another area I hardly touch.

This thing is of course $145...

I think Sverchok worth pricelessly more!

**Comment by enzyme69** [comment]
NOTE:
Archimatix does not have 3D booleans yet. All of the boolean operations you see in this video are 2D booleans., with the resulting shapes being used for meshing and repeating. For a list of the nodes available (more are being added all the time!), check out archimatix.com/nodes

**Comment by Kosvor2** [comment]
Agreed, if this is priced $145... Sverchok must be more than $1000.
