### ISSUE TITLE
TOY: Sverchok Spinner basic

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1699]
Who has 3D Printer here and want to test this out?

https://gist.github.com/cf080a175ec291ef47f22a1fa5f70a46

Need the ball roller thing in the center though...

![screen shot 2017-06-03 at 18 45 16](https://cloud.githubusercontent.com/assets/3952687/26752158/f174a4fa-488c-11e7-87a7-b8e59dfb0126.png)

**Comment by enzyme69** [comment]
@portnov Your Cylinder selection comes in handy for this kind of thing :)

**Comment by enzyme69** [comment]
![screen shot 2017-06-03 at 19 13 50](https://cloud.githubusercontent.com/assets/3952687/26752332/df982c3a-4890-11e7-9c7e-be5b89731ab7.png)

Beer holder spinners.

**Comment by portnov** [comment]
o_O
