### ISSUE TITLE
Neuro node for Grease Pencil?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1700]
It might be a strange or stupid, but what if, we can use Sverchok to assist and enable people with accessibilities.

Maybe Grease Pencil stroke that instantly can do trigger of action.

I do not know how Neuro node works, still. Can I draw 100 hand gesture number 8 and Sverchok return: number 8?

**Comment by enzyme69** [comment]
Hmm... https://github.com/nortikin/sverchok/issues/324

Wonder if this is a correct setup:
[neuro3_2017_06_04_11_57.zip](https://github.com/nortikin/sverchok/files/1050285/neuro3_2017_06_04_11_57.zip)

Wonder if Alex still around @Cfyzzz

**Comment by enzyme69** [comment]
My imagination is something like this:
![screen shot 2017-06-04 at 21 59 20](https://cloud.githubusercontent.com/assets/3952687/26761379/1edfcfca-4971-11e7-9d89-a56353b4f9ef.png)

**Comment by enzyme69** [comment]
http://fotogenerator.npocloud.nl

**Comment by zeffii** [comment]
it seems you have two questions
1. can we have gesture recognition
2. can neuro elman node do it.

1. that should be solved on a Blender level, as it would be much more useful.
2. yes, but :)  http://www.ijeit.com/vol%202/Issue%205/IJEIT1412201211_02.pdf

**Comment by enzyme69** [comment]
@zeffii Thanks Zeff! I'll read the paper now. Not sure brain is capable. But yeah, I don't know how Alex uses that node, such mystery.

Gestural > to Macro is an idea that you are right, better implemented at Blender UI level. 

We can leave this one here. Will revisit in the future....
