### ISSUE TITLE
new nodes ( random homogenous vert cloud , vert inside mesh mask )

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1702]
these things exist as Scripted Nodes, obj ID nodes ( iirc ) i need them as regular nodes.

- [x] Hom.Vector Cloud (with max dist)
- [x] Vec Inside Mesh

**Comment by zeffii** [comment]
pcloud
```
"""
in xdim s d=3 n=2
in ydim s d=3 n=2
in zdim s d=3 n=2
in size s d=1.0 n=2
in amt s d=0.0 n=2
in seed s d=10 n=2
out verts v
"""

import numpy as np

verts = []
hs = size/2
x_ = np.linspace(-hs, hs, xdim)
y_ = np.linspace(-hs, hs, ydim)
z_ = np.linspace(-hs, hs, zdim)

f = np.vstack(np.meshgrid(x_,y_,z_)).reshape(3,-1).T
num_items = f.shape[0]* f.shape[1]

if amt > 0.0:
    np.random.seed(seed)
    noise = (np.random.normal(0, 0.5, num_items) * amt).reshape(3,-1).T
    f += noise
    

f = f.tolist()
verts.append(f)
```

**Comment by zeffii** [comment]
vec_inside
```python
"""
in verts_in v 
in faces_in s
in points v
out mask s
"""

from mathutils.kdtree import KDTree
from mathutils import Vector

def are_inside(points, bm, max_dist=None):
    if max_dist is None:
        max_dist = 1.84467e+19

    rpoints = []
    addp = rpoints.append

    size = len(bm.verts)
    kd = KDTree(size)
    for i, xyz in enumerate(bm.verts):
        kd.insert(xyz.co[:], i)
    kd.balance()
    
    # bm.verts.ensure_lookup_table()
    
    verts = bm.verts
    for p in points:
        co, index, dist = kd.find(p)
        normal = verts[index].normal
        p2 = co - Vector(p)
        v = p2.dot(normal)
        addp(not(v < 0.0))

    return rpoints


for idx, (verts, faces, pts_in) in enumerate(zip(verts_in, faces_in, points)):
    bm = bmesh_from_pydata(verts, [], faces, normal_update=True)
    mask.append(are_inside(pts_in, bm))

```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26763431/1eb43374-4953-11e7-9c53-b3a3a12de39b.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26763438/3439333e-4953-11e7-99f1-24de76a34e01.png)

**Comment by enzyme69** [comment]
Random points scattering nodes? Neat! Thanks Zeffii!!

**Comment by enzyme69** [comment]
@zeffii I think I am doing it wrong.

[Uploading pointcloud_scatter_001_2017_06_05_01_25.zip…]()
![screen shot 2017-06-05 at 11 25 44](https://cloud.githubusercontent.com/assets/3952687/26767283/ca545ca2-49e1-11e7-9ebd-b6319955d391.png)

**Comment by enzyme69** [comment]
Increasing the mesh of the box increases the "accuracy"
![screen shot 2017-06-05 at 11 27 25](https://cloud.githubusercontent.com/assets/3952687/26767303/0351549c-49e2-11e7-96d1-62e21fa9597b.png)
 somewhat.

**Comment by zeffii** [comment]
Yes,  I'm adding a subdivider if the Input mesh is just 8 or less verts

**Comment by zeffii** [comment]
good catch btw :)

**Comment by nortikin** [comment]
it is like magic.
Thanks for so usefull additions.

**Comment by enzyme69** [comment]
@zeffii Did you put this one under SNLite templates or I just copy paste the code from here?

**Comment by zeffii** [comment]
Its a node now... called point inside mesh  or something
