### ISSUE TITLE
Multiple Object Meshes Join operator

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1704]
As I use Sverchok more and more, I realized that it would be nice to have a way to "join" objects that actually allowing "multiple materials" of "many objects" as one at Object Level.

Like for example this funky low poly tree thing I did:

![screen shot 2017-06-05 at 19 26 58](https://cloud.githubusercontent.com/assets/3952687/26778535/036cfa60-4a25-11e7-8b04-2176448c24c3.png)

Manually joined:
![screen shot 2017-06-05 at 19 28 18](https://cloud.githubusercontent.com/assets/3952687/26778580/3bd573e6-4a25-11e7-8607-f0e702bb4122.png)

What do you think?

**Comment by zeffii** [comment]
possible even to set `vertex_groups` on the joined mesh, to retain separate-ability.

**Comment by zeffii** [comment]
I question what you gain from having such a node, you need to justify it. ..stick more effort into arguing why it would be useful.

**Comment by enzyme69** [comment]
There will be times when "Merge" node is needed. Maybe Merge objects listed, and determine the Center Pivot. That would be nice. That way, we can further place the merged objects and work in Object Mode, if needed.

Currently, I was thinking "Group" is probably ok, kind of good enough. But "Merge" object can be handy, for keeping Material for multiple polygon face.

"Group" seems possibile for bunch of objects per BMesh Viewer, but currently does not allow for grouping from multiple BMesh Viewer.

![screen shot 2017-06-05 at 21 21 09](https://cloud.githubusercontent.com/assets/3952687/26782053/f1f543d6-4a34-11e7-8ed1-2fcb5575ecea.png)

Not urgent, just an idea.

**Comment by enzyme69** [comment]
![screen shot 2017-06-05 at 21 29 33](https://cloud.githubusercontent.com/assets/3952687/26782276/1713bdae-4a36-11e7-964c-68e60c7c671e.png)

Modeling "parts" sometimes requires different Material. For creature, maybe the palm and top part separated, and maybe stomach and other body area are different materials.

**Comment by enzyme69** [comment]
![screen shot 2017-06-05 at 21 31 31](https://cloud.githubusercontent.com/assets/3952687/26782324/5cc9bf24-4a36-11e7-9035-efa78a7744c2.png)

**Comment by zeffii** [comment]
it's not hard to do, but in the last scenario I think it makes more sense to add a material index socket to bmeshviewer instead. If one material index is passed per mesh, then all faces in the mesh are assigned the same material, if multiple indices are passed per mesh, then materials are assigned per face.

i'm not terribly interested in doing this right now.

**Comment by enzyme69** [comment]
I guess we can close this for now.

My instancing solution will be then like this:
- Sverchok can do variations
- Output MULTIPLE Blend each with Grouped objects, slightly randomize setting of Sverchok
- If we want to instance those variations, we use Empty and Dupli.

Blender Dupli is weird that it does not work with Particles, but anyway, Sverchok can do it using Empty instancing and randomize the Empty DupliGroup.
