### ISSUE TITLE
Convex Hull node does not do 2D

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1705]
![screen shot 2017-06-05 at 22 29 40](https://cloud.githubusercontent.com/assets/3952687/26784008/913534ca-4a3e-11e7-8bc0-d1259c960c72.png)

[wheels_003_2017_06_05_12_30.zip](https://github.com/nortikin/sverchok/files/1051986/wheels_003_2017_06_05_12_30.zip)

I got this setup with Convex Hull and seems to be a lucky accident that it can actually conveniently generate this wrap around wheels effects, like in Wall-E.

The funny thing is that I am stuck where I have bunch of Vector that wraps around, but it does not close. Maybe possible with sorting and finding the First and Last, but is there a better way to close that particular curve?

**Comment by enzyme69** [comment]
![img_8801 jpg](https://cloud.githubusercontent.com/assets/3952687/26784197/a07e5280-4a3f-11e7-8c32-2c640c3a0174.JPG)

I tried Vector Interpolation and realized needing List Sorting. Maybe I should try sorting. But is there a convenient sorting that seek through a line and sort based on loose ends?

**Comment by zeffii** [comment]
there's a scriptnode for `sorting edges for profile` by @nortikin .  use it.

**Comment by enzyme69** [comment]
Got it, and if I manually add edge indices, it would be like this:

[wheels_004_2017_06_05_12_57.zip](https://github.com/nortikin/sverchok/files/1052024/wheels_004_2017_06_05_12_57.zip)
![Uploading Screen Shot 2017-06-05 at 22.55.59.png…]()


Interesting feat.

**Comment by zeffii** [comment]
I just tried.. it's not so simple.. This is a good one, i like these.

**Comment by enzyme69** [comment]
[wheels_005_2017_06_05_13_05.zip](https://github.com/nortikin/sverchok/files/1052043/wheels_005_2017_06_05_13_05.zip)
![screen shot 2017-06-05 at 23 05 51](https://cloud.githubusercontent.com/assets/3952687/26785014/ca2cac86-4a43-11e7-994d-580e68c79617.png)

I tried List Shifting the index, but no luck. I remember encountering this a few times, but give up.

Apart from wheels, maybe end result can be used to make fence.

**Comment by zeffii** [comment]
i think the convex hull doesn't do 2d. (this one just assumes you want 3d)
![image](https://cloud.githubusercontent.com/assets/619340/26785202/83ee7d9a-4a01-11e7-9a50-418f5f308bf7.png)

**Comment by enzyme69** [comment]
Finding silhouette of convex hull, this might help:
https://github.com/nortikin/sverchok/issues/913

There seems 2 issues here:
- wanting to get the outer of convex hull
- wanting to close vectors curve.

**Comment by zeffii** [comment]
`mathutils.geometry.convex_hull_2d(points)` it's just this..i think @ly29 won't mind if we add a 3d/2d mode

**Comment by zeffii** [comment]
once you have the the correct bounding edges, sticking them in "sort edges for profile" should be no problem (that will sort the vertices too).

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26785704/19a1e96a-4a04-11e7-81ad-e21d2ca3b69e.png)
```python
"""
in verts_in v
out faces_out s
"""

import mathutils

for verts in verts_in:
    GG = mathutils.geometry.convex_hull_2d([v[:2] for v in verts])
    faces_out.append([GG])

```
GG may or may not need to extra `[  ]`

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/26786127/d2851050-4a05-11e7-902d-3fcb8ebe0f2b.png)

**Comment by zeffii** [comment]
i'm thinking
```text
[ convex hull mk2 ]
+-----------------+
|           verts +
|       poly_edge +
| 
|   [3D  |   2D]  |
|   [X | Y | Z ]  |
|  [inner/ outer] |
|                 | 
+ verts           | 
-------------------
```
the xyz enum would only be visible in 2d mode, xyz will represent the 2d plane (I haven't tested with a tilted plane, but i'd be surprised if it's arbitrary...if it is then xyz isn't needed )

**Comment by zeffii** [comment]
The question for 2d mode is should there be a mode that retains some element of the original (x, y, z) per vertex, rather than settings the non-used component to `0` by default.

**Comment by enzyme69** [comment]
Mind blown by your way of thinking 0_o

This "convex hull 2D" can be interpolated like usual? Need sorting still?

**Comment by zeffii** [comment]
Auto sorting is appropriate, a switch ..on by default.

I'm going to be busy for the next few days. No eta

**Comment by zeffii** [comment]
pushed as an mk2 for now

**Comment by zeffii** [comment]
please add inevitable questions to the end of this Issue, and don't start new issues regarding this node.
