### ISSUE TITLE
BVH (mocap) reading

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1707]
I am thinking to observe BVH Armature mocap data and get the usual Location, Rotation for Sverchok meshing. This is what I have so far, and something is not right, but I think pretty close...
[bvh_mocap_test_002_2017_06_09_02_34.zip](https://github.com/nortikin/sverchok/files/1062902/bvh_mocap_test_002_2017_06_09_02_34.zip)

Reference:
https://blender.stackexchange.com/questions/35982/how-to-get-posebone-global-location

**Comment by enzyme69** [comment]
![screen shot 2017-06-09 at 12 44 14](https://user-images.githubusercontent.com/3952687/26959036-5dcdac2c-4d11-11e7-95d1-3d94f83d88f5.png)
[bvh_mocap_test_002_2017_06_09_02_44.zip](https://github.com/nortikin/sverchok/files/1062913/bvh_mocap_test_002_2017_06_09_02_44.zip)

Ok seems to be getting somewhere, but there is 1 frame delay like Grease Pencil. Wonder why...

**Comment by enzyme69** [comment]
Need @zeffii way to force update Frame into into ... **SV Bone Info** node, just like how he did it on Grease Pencil node.

Uh-Oh maybe this is my first node. I'll study AN Bone Info first.

**Comment by zeffii** [comment]
i loaded it and can't see any frame delay.

**Comment by zeffii** [comment]
maybe you are rendering it?

**Comment by enzyme69** [comment]
Frame delay happens when I scrub the timeline. I should try rendering it.

**Comment by zeffii** [comment]
this seems like a general problem with the node (OBJ Asset Properties) - and Animation/scrubbing the timeline isn't really case that's tested for. While I solved it explicitly for the GP data, i don't think the same applies for Armature.

maybe try making a branch, and comment out 
```python
    # if not has_frame_changed(scene):
    #    return
```

in 
https://github.com/nortikin/sverchok/blob/master/core/handlers.py#L35-L50

**Comment by enzyme69** [comment]
Seems ok when rendered, so I call this just Blender UI glitch.
