### ISSUE TITLE
Node Externals

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1708]
uch.. this needs a solution for my own sanity. It will be like ScriptNode on steroids, as close as you can get to writing full regular nodes without committing to master.

- [ ] milestone 1 : making xnodes available from a dynamically generated menu
  - nodes will be put in `datafiles/sverchok/xnodes/folders/..`
  - the structure of `xnodes` folder would determine the final menu composition
  -  for the sake of arguments:
      ```
      xnodes/text/text_in_example.py
      xnodes/modifiers/line_thickness.py
      xnodes/modifiers/delete_random.py
      ```
- [ ] milestone 2 : storing / reloading to ensure availability on same machine / on other machines.
- *upon saving:* nodes will be stored in a textfile in the .blend , as `(text)text_in_example` (not .py)
    - this is parsed out as `(text)` _(the folder)_ and `regular_filename`
    - `bl_idname` can be introspected from the file, if you need more than one bl_idname for multiple classes, then I think the main Node class should have a `sv_idname` or something. This is not important for now.
- *upon loading:* the .blend, if Blender is not able to find the xnode in `datafiles/sverchok/xnodes` then it will check if any of the xnodes shares the same `bl_idname` and if it finds no matches it will copy the xnode to the appropriate directory.

there will be no iojson support for this feature initially.

**Comment by enzyme69** [comment]
Some kind of Sverchok USD? Universal Scene Descriptor that can be loaded and make variation? 

You are the engineer.

**Comment by zeffii** [comment]
USD has nothing to do with the topic of the issue.

**Comment by zeffii** [comment]
I want it to be easy to write normal nodes..for when a scripted node does not really offer a convenient enough UI. And I can't be bothered submitting a node as official. I may start an external repo.

**Comment by nortikin** [comment]
not much of users making own nodes

**Comment by zeffii** [comment]
yep. so this is for power users :)

**Comment by kalwalt** [comment]
@zeffii i think i will one of the very few users that will be happy for this feature.

**Comment by nortikin** [comment]
anyway, why not motivate to put new nodes to sverchok?
Maybe it will motivate to make them.

**Comment by zeffii** [comment]
exactly @nortikin - it can be a testing ground for nodes, (minus going through the procedure of making branches etc...) 

Generally useful nodes can be pulled into sverchok as 'release' nodes from time to time. Some Nodes should stay external when they rely on non-standard modules like scipy or something.

**Comment by zeffii** [comment]
I think my first node for this feature will be _Voronoi 3D_. but it's a little bit too warm here to get any coding done..

**Comment by zeffii** [comment]
it's getting warm again, and i've had too many other things to deal with.

**Comment by enzyme69** [comment]
​So from Script Node to External Node... can you make also documentation?

**Comment by zeffii** [comment]
There's nothing to document yet. Haven't found dev time lately

**Comment by zeffii** [comment]
cleaning away comments.

i don't want to bolt this into existing menus / menu generators - but if things work out it might persuade me to refactor the menu code a bit.

- new kb combo to show 'user nodes' menu, automatically populated given directory structure found in self.__module__
- no custom icon drawing support initially..

**Comment by zeffii** [comment]
<sub>i had some free time..(but it's not finished)</sub>

when experimenting with throwaway nodes ( or pre pre pre alpha ..whatever)

instead of registering the node using `bpy.utils.register_class`, you could do:
```python
import sverchok
from sverchok.ui.nodeview_usernodes_menu import register_class_and_menu

< usual node stuff and imports >

def register():
    # bpy.utils.register_class(SvFKB)
    register_class_and_menu(SvFKB, 'matrix_info')

def unregister():
    # this is the same for now...
```

this doesn't register the new node as part of the sverchok node menu

![image](https://user-images.githubusercontent.com/619340/30326670-8b20e024-97c9-11e7-8d2c-84ab68c520fa.png)

**Comment by zeffii** [comment]
ahhaaaa!!  https://blender.stackexchange.com/questions/45845/how-to-create-submenus-with-dynamic-content
