### ISSUE TITLE
List split - into chunks of different sizes

### ISSUE THREAD

**Issue by JoseConseco** [nortikin/sverchok#1711]
Right now 'List split' node gets 'size' parameter which is single integer number. So eg. list below splits into chunks of size 2 would look like:
[1,2,3,3,5] => [1,2] + [3,3]+[5]
I wish 'size' parameter could be list of integers, so I can split list into chunks of different sizes. Eg. for size = [2,3]:
[1,2,3,3,5] => [1,2] + [3,3,5]
We can get this way lists with different sizes.
I'm not sure is there a different way to split list into sublists with different lengths.

**Comment by zeffii** [comment]
use _List Slice Lite_ from the alpha nodes..

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1656

**Comment by zeffii** [comment]
Think of Split when you need equal sizes, and Slice Lite when you need arbitrary sizes. 

Closing because I think it resolved, else reopen
