### ISSUE TITLE
Vector P Field to control voronoi pieces?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1712]
![screen shot 2017-06-13 at 18 53 17](https://user-images.githubusercontent.com/3952687/27074191-bbeb854e-5069-11e7-964c-1969d734048d.png)
![screen shot 2017-06-13 at 18 53 12](https://user-images.githubusercontent.com/3952687/27074192-bc29ba08-5069-11e7-8a97-c85c62d66b01.png)
[vector_p_001_2017_06_13_08_53.zip](https://github.com/nortikin/sverchok/files/1070846/vector_p_001_2017_06_13_08_53.zip)

I accidentally saw this Vector P node. Not sure who made it. But interesting.

For box 3D cube, I could use this for starting Voronoi. Maybe I could even use this Vector P field to control Particles? Who knows.

Anyhow, my idea is like this:
For every points generating the Voronoi Fracture, I would like to be able to use the points as center point and rotation for each fracture.

Again I got this situation wher I need to Center Polygon per object fracture. So far, I seems to have double transform.

**Comment by enzyme69** [comment]
Digging old thread about center pivot, maybe I need to use Vector Drop...

https://github.com/nortikin/sverchok/issues/1606

**Comment by enzyme69** [comment]
I thought that some point "Separate Loose Park MK2" has auto center pivot.

**Comment by zeffii** [comment]
Vector P Field was made for generating a grid of Vectors within a certain bounding box 
- defined by X, Y, Z dimensions
- number of elements for "axis slice"
- added randomization
- added rm doubles to make the spread homogenous.
That's a node you just have to play with to understand.

It was indeed made for generating nice internal point cloud for voronoi to operate on. Use it along with Point Inside Mesh node,

I stopped reading.

**Comment by zeffii** [comment]
the Voronoi script is merely a suggested algorithm for a specific use case, if you want more control you should read the script, modify+break it..(rinse and repeat until it makes sense). You'll notice I intentionally add an internal "mesh merging" for the output because that's how I wanted to present the script.

It's very inefficient to  

1. merge inside the node
2. unmerge outside of the node

inside the node you can already be tracking the midpoint associated with each fragment.

**Comment by enzyme69** [comment]
Got it! I'll investigate. The center pivot etc, is a separate case. Thanks for explanation!

**Comment by enzyme69** [comment]
![screen shot 2017-06-13 at 20 01 39](https://user-images.githubusercontent.com/3952687/27077362-2aeab1c8-5073-11e7-995c-7d695e23a7ce.png)

Nearly there, this is the wrong way again.

**Comment by enzyme69** [comment]
I figure it out, me from the past answered. Sverchok is a very strange tool MK2:
https://github.com/nortikin/sverchok/issues/976

**gist**
https://gist.github.com/e1f47df107aca2c6bc0ef19fdfd52fba

![screen shot 2017-06-13 at 20 10 25](https://user-images.githubusercontent.com/3952687/27077719-5f163318-5074-11e7-98cd-b01c1f395b9f.png)

**Comment by zeffii** [comment]
> Sverchok is a very strange tool

blame the tool, that'll fix it.

**Comment by enzyme69** [comment]
I like a strange quirky tool. It can evolve.

**Comment by zeffii** [comment]
user should evolve too.
