### ISSUE TITLE
Bounding Box XYZ Width Height Depth Out

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1715]
![screen shot 2017-06-16 at 11 39 41](https://user-images.githubusercontent.com/3952687/27208352-809808de-5288-11e7-82db-2679685e55b5.png)
![screen shot 2017-06-16 at 11 39 35](https://user-images.githubusercontent.com/3952687/27208353-80ceceb4-5288-11e7-9175-4e8c27eeab51.png)
[scatter_points_within_bound_004_2017_06_16_01_39.zip](https://github.com/nortikin/sverchok/files/1079500/scatter_points_within_bound_004_2017_06_16_01_39.zip)

I am thinking to add this "feature" to the Bounding Box node. Possibly modifying the current node. Not sure how it is going to work with vectorization etc.

Safest is for me to modify it locally on my computer first...

**Comment by enzyme69** [comment]
![screen shot 2017-06-16 at 11 54 05](https://user-images.githubusercontent.com/3952687/27208683-8506fde2-528a-11e7-86e1-965f296b3468.png)

So I think I just need to check verts_out and list item.

**Comment by zeffii** [comment]
Be sure to not edit you local master branch. 

git checkout xyzmod

Then make your changes in xyzmod branch.

**Comment by zeffii** [comment]
i'll add a small wiki page about how to use git with sverchok.

**Comment by enzyme69** [comment]
```
"""
in   bboxVerts v          default=(0,0,0) n=1
out  dx s
out  dy s
out  dz s
"""

def distance(p1, p2):
    return sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2+(p1[2]-p2[2])**2)

dx = distance(bboxVerts[0], bboxVerts[1]) # dimension X
dy = distance(bboxVerts[0], bboxVerts[2]) # dimension Y
dz = distance(bboxVerts[0], bboxVerts[4]) # dimension Z


```

I am going to test with Script Node Lite first.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/wiki/Git-Practices   do some googling about git before asking here.

**Comment by enzyme69** [comment]
Got it.

**Comment by zeffii** [comment]
good luck with SNLite.

`s` is a list. so always return a list. `dx = [[distance....... ]]`

**Comment by enzyme69** [comment]
That's why... [[]] and [] 

```python
"""
in   bboxVerts v          default=(0,0,0) n=1
out  dx s 
out  dy s 
out  dz s 
"""

from math import sqrt

def distance(p1, p2):
    return sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2+(p1[2]-p2[2])**2)

# return the width, depth, height dimensions of Bounding Box

dx = [distance(bboxVerts[0], bboxVerts[1])] # dimension X
dy = [distance(bboxVerts[0], bboxVerts[2])] # dimension Y
dz = [distance(bboxVerts[0], bboxVerts[4])] # dimension Z

```

**Comment by zeffii** [comment]
if you are just returning one number, then you do `[[some_number]]`

**Comment by zeffii** [comment]
I think you should spend time with this on your own. I've been explaining the same thing since 2014 when the original SN was first introduced.

**Comment by enzyme69** [comment]
Thanks Zeff. I can close this one, but the node is pending. 😑 I'll spend time thinking.
