### ISSUE TITLE
Polyline and Skin Mesher Sorting are different

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1720]
I am testing this noodle algorithm thing both on Curves Polyline Viewer and also on Skin Mesher.

[spline_thing_001_2017_06_19_09_06.zip](https://github.com/nortikin/sverchok/files/1084385/spline_thing_001_2017_06_19_09_06.zip)
![screen shot 2017-06-19 at 19 06 20](https://user-images.githubusercontent.com/3952687/27277717-815776a0-5522-11e7-9c76-982cbd6d717e.png)

I also use Ly BSpline thing, the result differs... any explanation on this?

**Comment by enzyme69** [comment]
Add Topo Sort... kind of making something different. Which is nicer too.

![screen shot 2017-06-19 at 19 10 10](https://user-images.githubusercontent.com/3952687/27277847-fd1f5e6a-5522-11e7-92f0-2f80922f2dc5.png)

Ly BTrace KDTree node gives edges that makes the result looks nice on Skin Mesher. If I use UV Connection, I get what I get using Polyline Viewer, without using Topo Sort.

All this difference, is it because of sorting of points?

**Comment by zeffii** [comment]
> All this difference, is it because of sorting of points? 

yes

**Comment by enzyme69** [comment]
@zeffii Thanks then it is answered. Cheers.

**Comment by zeffii** [comment]
if you are trying to figure our whether a node is doing what it should, the first step is to dial back as many parameters as possible and reduce the geometry to some number of verts/edges that you can reason about using an indexviewer.

that's the only time i use indexviewr, when something happens that I don't expect.

**Comment by enzyme69** [comment]
Quite interesting for me is that Ly's "btrace kdtree" generates "nice" Edges for scrambled unsorted points for the noodles:
![screen shot 2017-06-19 at 20 56 11](https://user-images.githubusercontent.com/3952687/27282061-c4035802-5531-11e7-99cb-b6a5f28313d7.png)

If I bake out the poly edges, convert the curve, I get the "nice sorted" result. Polygon to curve conversion in Blender sorts the index.

Something I keep in mind. We can have random index points and nice edge.

**Comment by enzyme69** [comment]
@zeffii One more question: I use Ly BTrace thing, it generates "nice edges" that connects points in a sorted kind of way. Is there a node in Sverchok that can "confirm" this and sort the index based on connected edges? I believe your Topo nodes is doing this, but sometimes it does not work, when I use with Polyline. It's a mystery.

**Comment by enzyme69** [comment]
![screen shot 2017-06-19 at 21 22 48](https://user-images.githubusercontent.com/3952687/27282963-8754fd4e-5535-11e7-8aa3-9bb9951f6da9.png)
[Uploading grease_noodles_001_2017_06_19_11_22.zip…]()

Ly also has Topo Edge node.

**Comment by zeffii** [comment]
i don't know, i'd have to look but am not going to do that. you should read the code of all nodes and scripts involved, and reason about it ( else the explanation will mean nothing anyway..)

**Comment by zeffii** [comment]
my comment here is based on recollection, not recent code reading.

i think @ly29 's btrace is simply for generating a single path between all given input vertices. The start vertex might be picked at random (i don't know - indexviewer should tell you).  I don't know if there's a seed you can set, or how the algorithm decides on which 'next' vertex to connect if there are multiple vertices at the same distance from the current vertex.  

my topo_sort is purely based on picking the lowest vertex index, the associated edges and the opposite (other) vertex. This is repeated till it finds the last edge in the chain.  I think in the code i mention the limitations of that script (and what scenario it works for) . It doesn't expect edge_loops, they must be open. It also doesn't expect disjoint edge sets in a single verts/edge list (it will simply stop after finding the first polyline).

![image](https://user-images.githubusercontent.com/619340/27285311-9dd5da40-54fc-11e7-95bd-f869d111c3e9.png)

the red polyline segments in don't get recongized in my toposort. ( i think...)
