### ISSUE TITLE
Topology Sorting

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1721]
i'm writing this to address recent questions about what it means to sort topology, and what unsorted topology is.

There are various states of unsorted / sorted topology

![image](https://user-images.githubusercontent.com/619340/27327735-cdae92a8-55af-11e7-8ff1-b55dc548f582.png)

A = completely unsorted
B = unsorted verts, but sorted edges
C = sorted verts, unsorted edges
D = sorted verts and edges.

- Most of the time you will encounter type A. There are many situations where it is not relevant to us how the  topology is indexed.
- for 2d stuff (profiles, paths) however it does help to have at least sorted verts (state C, or D).
   - Nodes that don't take edges will assume that the incoming set of verts is already sorted in the right sequence.

**Comment by zeffii** [comment]
There are various states of unsorted / sorted topology

![image](https://user-images.githubusercontent.com/619340/27327735-cdae92a8-55af-11e7-8ff1-b55dc548f582.png)

A = completely unsorted
B = unsorted verts, but sorted edges
C = sorted verts, unsorted edges
D = sorted verts and edges.

- Most of the time you will encounter type A. There are many situations where it is not relevant to us how the  topology is indexed.
- for 2d stuff (profiles, paths) however it does help to have at least sorted verts (state C, or D)

**Comment by zeffii** [comment]
If you are getting weird results with edges that seem to be all over the place, then you probably are feeding the geometry to a Node that expects a certain sorted state.

We have various _ScriptedNodeMK1_ and _SNLite_ Scripts to help us generate a meaningful sort. Arguably we should add these to a `topo sort` node.

**Comment by Durman** [comment]
I think that sometimes direction of sorting have meaning. And what point are first in array. When line of points are looping we have many variants of sorting.

**Comment by zeffii** [comment]
Yes, there are a few more variants, some more specialised than others. Like:

- Tree structures (with a single trunk and many branches, and subbranches)
- disjoint polylines
- Networks like a LAN

sorting for all of those requires 'agency' (extra parameters to consider for the sort - other than purely rearranging verts/indices to make a sequence sorted )
