### ISSUE TITLE
Solidify SV

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1727]
following the situation in https://github.com/nortikin/sverchok/issues/1726

Sometimes all we need is to give thickness to one or more faces. Solidfy and Extrude nodes all use bmesh operators that can't be relied on to produce consistent face and edge indexing (over time...scrubbing timeline will invariably show you that)

Often we don't worry about indexing, but sometimes it is essential -- and that's what Solidify SV hopes to address. SV postfix would mean "has no bmesh or bpy.ops" operations. Most of the code exists for this in some form in the Inset Specials node..

```text
[ Solidifiy SV]
+-------------+
|       verts o
|    polygons o
|             |
o verts       |
o polygons    |
o direction   |
o amount      |
+-------------+
```
To be clear, this would be a bit slower on large amounts of geometry, but it provides a feature that the similar nodes that use bmesh operators can not. Stability in topo sorting.

- is not intended to operate on regions

**Comment by Durman** [comment]
Why bmesh operators have this behavior? I noticed that boolean result likes dancing too. May be could sort node to decide this problem if it will have properties of first point and direction for looping?

**Comment by zeffii** [comment]
@Durman  bmesh uses a fast mesh storage, which essentially behaves (in a sense..) like a `set` or a `unordered dict` . The verts order are guaranteed, but not the edge/face indices.  I realize this might not give a satisfying answer, but it's out of our control.

I think if you search the term "bmesh unordered indices" in this repo, or generally in a search machine you'll get a more precise explanation.


closing for now, coding this would be too boring.
