### ISSUE TITLE
Discrete Scaling

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1730]
In response to: [BA post post3212304](https://blenderartists.org/forum/showthread.php?272679-Addon-WIP-Sverchok-parametric-nodes-for-architects&p=3212304&viewfull=1#post3212304)

> You have to be able to control the size of gemstones, i mean the gem can't be 1.26mm for example, they're mostly done in 0.1 increments (1, 1.1, 1.2, 1.3...)

Consider the Python operators needed to achieve this from an arbitrary continuous scaling curve.

**Comment by zeffii** [comment]
This is called quantizing, but for the sake of this example you can round values at `n` positions 
```python
import math


print('----- start -----')
theta = (math.pi / 20) / 2

for i in range(10, 20):
    real_value = i*theta
    rounded = round(real_value, 1)
    print("real_value: {0}, rounded: {1}".format(real_value, rounded))
    
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/27635508-96aa7782-5c07-11e7-8acf-6e6ccd3dcb0e.png)

**Comment by zeffii** [comment]
In the example image, any input input the Math (MK2) node, will be rounded at the first digit after the decimal point.

**Comment by Durman** [comment]
I think about something like this.)
![scale](https://user-images.githubusercontent.com/28003269/27636760-11ac2e42-5c1e-11e7-92fa-9f0cb272f377.gif)

**Comment by zeffii** [comment]
closing the issue, you can still add further posts - but because it isn't bug tracking i want to close it.
