### ISSUE TITLE
List Shift node and lists vertices different lengths

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1731]
https://gist.github.com/8a1c0fdc444b8f82ee6a687981927e00

![shift bug](https://user-images.githubusercontent.com/28003269/27771590-bf9892ce-5f62-11e7-9e83-69bbfeb1ab71.gif)

**Comment by zeffii** [comment]
use the `py` option,  `NP` is limited.

**Comment by zeffii** [comment]
if that doesn't work, then 

> write out in full a sample of the input and the parameters you expect to be able to pass, and the resulting output. 

Then if you want to help even more you should write a SNlite script that does this.

**Comment by Durman** [comment]
NP mode is special for work with lists different length, do not you remember? look here:

[https://github.com/nortikin/sverchok/issues/1595](https://github.com/nortikin/sverchok/issues/1595)

**Comment by zeffii** [comment]
Keep reading, and re-read my previous comment

**Comment by zeffii** [comment]
also. if a node goes colour red, it usually displays an error message in the windows console.

![image](https://user-images.githubusercontent.com/619340/27785076-be490028-5fdc-11e7-8c29-79a978b2e049.png)

show me the output there.

**Comment by Durman** [comment]
Sorry, I understood now, I must to use Py mode.

![2017-07-03_13-07-05](https://user-images.githubusercontent.com/28003269/27786020-943a50b6-5ff0-11e7-8f70-9ffb3f1169a7.png)

Thank you for showing console, it was problem with searching bugs in my codes for Scripted node.

**Comment by zeffii** [comment]
good. happy to help
