### ISSUE TITLE
branch for 2.8 testing

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1732]
i think there will be considerable rewriting needed for sverchok to run with openGL drawing in 2.8, quite a bit of work.. but definitely worth it.

For the time being, it's probably fun to try a branch of sverchok that uses fewer openGL nodes, just the bmesh and curve nodes.. as outputs.

**Comment by zeffii** [comment]
....uhmmmm.... 
```python
 'bpy.app.handlers' object has no attribute 'scene_update_pre'
```

that's not good :)

**Comment by enzyme69** [comment]
Since I am currently on Windows, maybe I can try experimental 2.8 mode.

**Comment by zeffii** [comment]
don't bother. literally.

**Comment by Kosvor2** [comment]
related: https://developer.blender.org/T47811

**Comment by zeffii** [comment]
i wonder if we'll have to trigger update system purely from the `updateNode`.. 

closing for now.
