### ISSUE TITLE
Delaunay and z axis

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1735]
I must use this node.) Is it possible to work with vertices that lay on z axis plane? =S
https://gist.github.com/46f86b3d278a9c479a6081b15879e631

![delaunay](https://user-images.githubusercontent.com/28003269/27911154-14e3d172-6269-11e7-9380-90aa6d107acc.gif)

**Comment by nortikin** [comment]
https://gist.github.com/5f910b10d4efc02c12411057dd32ce95
one case

**Comment by nortikin** [comment]
https://gist.github.com/964f75eb13d48b4d73733fd429c78e20
other case

**Comment by Durman** [comment]
Thanks, you are right. I did not manage to it.)

![cub](https://user-images.githubusercontent.com/28003269/27984411-9b7d13d2-63e6-11e7-8d33-f192ac356f3c.gif)

**Comment by nortikin** [comment]
so, you filtered mesh in post process?

**Comment by Durman** [comment]
@nortikin 
I united polygons by direction and used delaunay node, then I masked holes.

**Comment by zeffii** [comment]
does this need to be addressed, or can this issue be closed?

**Comment by Durman** [comment]
can close
