### ISSUE TITLE
about solidify

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#1736]
why solidify's polygon output is data, not polygon?
i can't use solidify with boolean node.

**Comment by Durman** [comment]
It is looks normally.
![2017-07-07_13-24-17](https://user-images.githubusercontent.com/28003269/27951950-ae106fa0-6317-11e7-88ed-d9d6a31ac1dc.png)

**Comment by stansu** [comment]
you have to use viewer text to tell the different.

**Comment by Durman** [comment]
Polygon is data of 3 and more indexes of vertices. :/

**Comment by stansu** [comment]
you can try boolean node after solidify, it will not works.

**Comment by Durman** [comment]
https://gist.github.com/3d326677739e0f24b1a614f4edff980a
![solidify](https://user-images.githubusercontent.com/28003269/27954046-454e132a-631f-11e7-845d-fbf505bc8dfd.gif)

**Comment by stansu** [comment]
oh sorry, I forgot to tell you. you need to input 2 solidify into boolean.

**Comment by Durman** [comment]
Can you show your example?

![solidify2](https://user-images.githubusercontent.com/28003269/27954410-dfba6bb0-6320-11e7-8686-dec40fe8e987.gif)

**Comment by stansu** [comment]
https://drive.google.com/open?id=0Bxsx44J5Qh8XYnlFNkk3OU9Jelk
thanks!

**Comment by Durman** [comment]
Here is problem with boolean node, i saw it before.
May be Zeffii will can to say something more.))

![2017-07-07_16-16-50](https://user-images.githubusercontent.com/28003269/27957475-bd9a4398-632f-11e7-8c65-999f7b604aa5.png)

**Comment by Kosvor2** [comment]
@zeffii 
#1737 can crash, i guess...

**Comment by zeffii** [comment]
Sticking it into a try except might still allow partial computation. And return the error in the failing case .. would be nice to track down the error cause. For now upping the recursion is fine. Really no idea.

**Comment by stansu** [comment]
can we use Cork Boolean Library?
http://arc-team-open-research.blogspot.tw/2014/10/boolean-operations-powerful-cork.html
https://github.com/cloudcompare/cork

**Comment by zeffii** [comment]
Technically you could already try that using a scripted node, and execute the binary. Someone would need to write a converter/writer from verts,faces to .off format, and back.

**Comment by zeffii** [comment]
continue here: https://github.com/nortikin/sverchok/issues/1743

**Comment by zeffii** [comment]
the problem here is not the usage of 2 Solidify nodes going into the Boolean node. 

![image](https://user-images.githubusercontent.com/619340/28419291-cbb03c06-6d5e-11e7-9d4d-9dd5655b0c74.png)

So, can you show with a simple `gist` or .blend a failing example that causes the recursion limit to be a problem?

I'm not opposed to modifying the recursion limit for the boolean Node, but I'm not yet convinved that will address the real problem.

**Comment by zeffii** [comment]
and by simple I really mean simple.  Because if the issue can't be shown by a simple layout, then the problem more and more likely isn't simply one node's fault.

**Comment by stansu** [comment]
i founnd that boolean is very slow in sverchok.
i will try another way to make boolean.
thanks anyway.

**Comment by zeffii** [comment]
> boolean is very slow in sverchok.

it's OK for simple geometry..  anything moderately complicated probably needs a different solution. Ideally boolean would be a bmesh.operator, and operate at the speed of C/C++ (the only thing slowing it down would be the fact that you need to pass pydata to the function ) .

I can make a simple Boolean node that takes two Object Sockets, and offers all choices available in the Boolean Modifier UI, then add an output socket for the result -- that would work OK for Object Lists with single objects each

```text
| bool modifier basic |
+---------------------+
|             obj out o
|   operation [   ]   |
|   carve/bmesh       | 
o obj 1               |
o obj 2               |
+---------------------+
```

not sure if I should...

**Comment by stansu** [comment]
That will be great!
Because Boolean can make many shapes, like openscad or freecad.

I heard animation-node use cython in 2.0.
That will good idea for sverchok too?

**Comment by zeffii** [comment]
> I heard animation-node use cython in 2.0.
> That will be a good idea for sverchok too?

There are two ways we can speed up Sverchok (and they can be used in parallel)
- Cython Probably would increase execution speed noticeably for the heavier algorithms implemented in pure standard python. (excluding bpy / bmesh calls).
- Adding C coded functions to mathutils.geometry / bmesh.ops etc, benefit there is that it then exposes these functions to other add-on users.

All of this relies on a sverchok developer willing to write C and or compile the modules. I am not that person at the moment.

**Comment by zeffii** [comment]
i'm not sure what else can be done in this thread
- solidify works, but maybe it's a bit slow?
- boolean works, but is slow. This can't be fixed in any significant way without the bmesh module being augmented with its own boolean. Ideasman42 said this would be simple to do, but that he wasn't going to do it (at that time).

Both seem to work within the intended scenarios.
