### ISSUE TITLE
An approach to Voronoi3d from object

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1739]
First, i'm sure much of the setup could be done inside a dedicated node. I don't have a lot of time at the moment, but i do want to show how you might setup a node tree to make OK voronoi.

1. get a surface object, and generate a Vector P field for it. First make a vector field, then add randomization and start adjusting the remove doubles value

  ![image](https://user-images.githubusercontent.com/619340/27992794-792e9b0a-649c-11e7-8ed3-bf695166b42c.png)

  keep tweaking randomize and rm doubles until it looks like you have a nice homogenous spread of vectors ( like snow...)

  ![image](https://user-images.githubusercontent.com/619340/27992821-267b8f20-649d-11e7-8f68-778bda076e9b.png)

2. a next ( optional, and currently hit and miss ) step is to remove those points that are outside of the surface. They only slow down the solution. For this you can add `Anaylizer/Points inside Mesh` node.  This node is not yet accurate enough to be used without thinking/checking the result ( [feel free to  contribute solutions ...this is one node that really needs fixing](https://github.com/nortikin/sverchok/issues/1740)) 

  ![image](https://user-images.githubusercontent.com/619340/27992862-fbdfd838-649d-11e7-84a4-75f44d8a0cf2.png)

3. then add the SNLite voronoi script. Warning - you might want to toggle "processing" button to off first, before connecting the nodes up. 

  ![image](https://user-images.githubusercontent.com/619340/27994794-aea2ec96-64c4-11e7-913b-0b963a44e513.png)

Then enable processing, and then click the vertex socket on the Objects In node to trigger the updates down stream (that's how I do it).

  ![image](https://user-images.githubusercontent.com/619340/27992935-c71938cc-649f-11e7-8cc2-5292a15ce3ef.png)

  There are currently two sliders on the SNLite node exposed by the script.  
   - shrink:  scales the resulting polyhedra
 
   - "Bounding N" is related to how many facets you expect the resulting polyhedra to have. Sometimes you need 40..  it's not an exact science, and it's not trivial to set up an algorithm that can detect that automatically - or set it up dynamically.

**Comment by enzyme69** [comment]
So the snow does not have to be inside the volume 3D mesh?

**Comment by zeffii** [comment]
> So the snow does not have to be inside the volume 3D mesh?

No................., but if you want internal geometry..then .........................yes.

Any points (flakes) that are a certain distance away from the surface (on the outside) will not effect (in a meaningful way) the output, except for to slow down the calculation of the voronoi surfaces. The better we get at ignoring the points outside the mesh_surface, the faster the calculations can be done.

if you experiment, keep the number of points down...and the mesh_surface simple.
