### ISSUE TITLE
Point Inside Mesh

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1740]
A point is either inside or outside a manifold mesh, or exactly on a vertex/edge/face. I welcome working solutions to replace the code in that node. I'm tempted to have various modes, that would allow us to pick fast algorithms for simple cases and slower algorithms for complicated geometry.

i was thinking of the following algorithm.

```python
"""
in points_in v
in verts_in v
in faces_in s
out points_out v
"""

from mathutils import Vector, bvhtree


xup, xdown = (1, 0, 0), (-1, 0, 0)
yup, ydown = (0, 1, 0), (0, -1, 0)
zup, zdown = (0, 0, 1), (0, 0, -1)
directions = (xup, xdown, yup, ydown, zup, zdown)


def get_points_in_mesh(points, verts, faces):

    bvh = bvhtree.BVHTree.FromPolygons(verts, faces, all_triangles=False, epsilon=0.0)

    points_inside = []
    for point in points:
        for direction in directions:
            hit = bvh.ray_cast(point, direction)
            if hit[0]:
                p2 = hit[0] - Vector(point)
                v = p2.dot(hit[1])
                if not v < 0.0:
                    points_inside.append(point)
                    break

    return points_inside

for pointset, verts, faces in zip(points_in, verts_in, faces_in):
    points_out.append(get_points_in_mesh(pointset, verts, faces))




```

**Comment by zeffii** [comment]
this is a naive algorithm.. closing for now

**Comment by zeffii** [comment]
adding a check to test if the point is inside the bounding box of the testmesh will also speed up the final search (sometimes)

**Comment by zeffii** [comment]
#### Thinking about the algorithm

Hybrids are possible and multi-sampling, and preprocessing. Simple algorithms can be fast, but can suffer inaccuracy. I will refer to the Mesh (volume) as a Polyhedra

##### preprocessing
This won't always be necessary, but it might be nice as an additional step
- **(optional)** filter out points that fall outside of the bounding box immediately ( this step would be redundant if the user already provides incoming points that are within this space
- **(optional)** filter out points external to the barycentric bounding box, (a bounding box that fits as closely as possible to the external surface, could be achieved with a convex hull preprocessor i think)
- **(optional)** slice incoming (potentially concave) polyhedra into several smaller convex polyhedra first

##### Algorithms
I wrote a few approaches to this on [BSE (link) ](https://blender.stackexchange.com/questions/31693/how-to-find-if-a-point-is-inside-a-mesh)
 - one is the classic "count how many polygons a point's raycast hits until it no longer hits any more (certain it is outside of the polyhedron)"  (animation nodes uses this)
 - imagine a polyhedron and imagine you are a point inside it, raycast in any direction
    - if the first polygon you hit is faceing away from you, then you know you are inside the polyhedron.
    - if the first polygon you hit is facing towards you, you know you outside (no matter how complex the polyhedron is)
 - multisampling, do either of the above algorithms a number of times per test-point , each time changing the raycast direction and taking the most often returned 'conclusion' of 3 ..or 4..or N attempts. Increasing the samples per point has a reasonable chance of increasing the accuracy, but will slow down the overal algorithm.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/28565160-a8b7e66a-712b-11e7-9606-f30f848315bd.png)

**Comment by zeffii** [comment]
am tempted to push the modified node, it may break existing layouts...

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1745

added a more robust algorithm with resampling (oversampling, 

```
if 2 samples per point, then best of 1
if 3 samples per point, then best of 2
if 4 samples per point, then best of 3
if 5 samples per point, then best of 4
if 6 samples per point, then best of 4   <--- on purpose
```


```

**Comment by enzyme69** [comment]
OT: I wish I had zeffii brain and will make some awesome AR app for iPhone.
