### ISSUE TITLE
Extracting just twisty edge of Curves

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1741]
![prtscr capture_7](https://user-images.githubusercontent.com/3952687/28095228-8a0fa1d6-66e4-11e7-9cb6-5a02f34de637.png)
[wiring_stuff_003_2017_07_11_23_28.zip](https://github.com/nortikin/sverchok/files/1140487/wiring_stuff_003_2017_07_11_23_28.zip)

In Sverchok, is there a quick and nice way to "extract" the just twistiness of CURVE lines, without all the Circles along path?

UV connection does not seems  to do it. I think Curve is different than Cylinder of Polygon normally is.

**Comment by enzyme69** [comment]
![prtscr capture_8](https://user-images.githubusercontent.com/3952687/28095455-dff70b4c-66e5-11e7-94f9-3c15b8e3aa05.png)
[wiring_stuff_006_2017_07_11_23_38.zip](https://github.com/nortikin/sverchok/files/1140501/wiring_stuff_006_2017_07_11_23_38.zip)

Although this can be done this way...

With Output of Curve with Twistiness, can we extract the twisty spiral in the same way using UV?

**Comment by Durman** [comment]
Yes, I did it.
https://plus.google.com/112901248458436952300/posts/QqoXWbmXFoV
https://gist.github.com/5d800d0a9e6e9f32076064f6a8f77fdb

![spiral by spiral](https://user-images.githubusercontent.com/28003269/28098105-67ec25bc-66c5-11e7-917e-208275e1ea48.gif)

**Comment by enzyme69** [comment]
@Durman Thanks man~ will study this! I might break it down in my vlog.
