### ISSUE TITLE
Range float - nesting 2 level

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1742]
I want it for working with objects. Is it possible to do?)

![2017-07-13_10-57-01](https://user-images.githubusercontent.com/28003269/28154147-0373c59a-67ba-11e7-9a2c-7fc2eb0efe9f.png)

**Comment by zeffii** [comment]
currently i think you have to feed Range Float a nested input into start/step too, to do that ( i might be mistaken).

**Comment by zeffii** [comment]
but @Durman  , rather than using words to describe this.. and a screenshot that only shows an effect you don't want. Why not show us the minimum amount of input you hope to need, and exactly what output you expect could be possible.

`input ->  node --> expected output `

**Comment by Durman** [comment]
@zeffii  I want to receive [[[0],[0,1]],[[0,1,2],[0,1,2,3]]]. Now range float node can read list of inputs figures, but can not read several inputs lists. It cuts its to one list.

**Comment by Durman** [comment]
I create interpolation edges script. Interpolation will be proportional length of the edges, and will work with several objects. For this I must feed it with nesting two level list.

![2017-07-13_16-43-58](https://user-images.githubusercontent.com/28003269/28166831-8cc0bde6-67ea-11e7-91b4-9e202dbe864e.png)

**Comment by Durman** [comment]
I recreated this node for my self. Now I think about nesting impute.)

![2017-07-14_10-30-35](https://user-images.githubusercontent.com/28003269/28200952-d1424ee0-687f-11e7-80a1-2c24e7614aa4.png)

**Comment by Durman** [comment]
I did it. It seems working. I thought that this task will be more simplest. :/
Only this morning I was not in sure for what classes are existing, but I thought that using something like classes will be useful in this way. This is first so strong code for me.))

![2017-07-14_20-39-58](https://user-images.githubusercontent.com/28003269/28221516-a5c68ae2-68d4-11e7-8e81-8fa45847939c.png)
```python
"""
in start s d=0.0 n=0
in stop s d=1.0 n=0
in step s d=1.0 n=0
in count s d=4 n=0
enum = Range Count Step
out range s
"""
import numpy as np

class Input:
    obj_pul = []
    seq_pul = [[]]
    
    def __init__ (self,data):
        self.data = data
        self.n_obj = 0
        self.n_seq = 0
        
        if type(data) == list:
            self.n_seq = []
            Input.obj_pul.extend([len(data)])
            self.n_obj = len(data)
            while len(Input.seq_pul) < len(Input.obj_pul):
                Input.seq_pul.extend([[]])
            for i,d in enumerate(data):
                Input.seq_pul[i].extend([len(d)])
                self.n_seq.extend([len(d)])
        else:
            Input.obj_pul.extend([1])
            Input.seq_pul[0].extend([1])
                
    def coll(self,i_obj,i_seq):
        if type(self.data) != list:
            return self.data
        elif i_obj + 1 > self.n_obj:
            return self.data[-1][-1]
        elif i_seq + 1 > self.n_seq[i_obj]:
            return self.data[i_obj][-1]
        else:
            return self.data[i_obj][i_seq]
        
start = Input(start)
stop = Input(stop)
step = Input(step)
count = Input(count)

def ui(self, context, layout):
    layout.prop(self, 'custom_enum', expand=True)
    
def rangeing (start,stop,step,count,button):    
    if button == 'Range':
        range = list(np.arange(start,stop,step))
    
    elif button == 'Count':
        range = list(np.linspace(start,stop,count))
    
    else:
        range = list(np.linspace(start,step*(count-1)+start,count))
        
    return range

i_obj = 0
while i_obj < max(Input.obj_pul):
    i_seq = 0
    range0 = []
    while i_seq < max(Input.seq_pul[i_obj]):
        range0.extend([ rangeing( start.coll(i_obj,i_seq), stop.coll(i_obj,i_seq), step.coll(i_obj,i_seq), count.coll(i_obj,i_seq), self.custom_enum ) ])
        
        i_seq += 1
    range.extend([range0])
    i_obj += 1
```

**Comment by zeffii** [comment]
> I did it. It seems working. I thought that this task will be more simplest. :/

it's great to solve your own problems, and helps give appreciation for how complicated something can be..even if the concept is not difficult.

![image](https://user-images.githubusercontent.com/619340/28226431-6d0417ea-68d6-11e7-93d8-32d789b73e7d.png)

sometimes it can be easier to give lists/nested lists their shape as a "post processing" step, rather than packing too much functionality into the node.

**Comment by Durman** [comment]
@zeffii 
You are right. I could do not write this code. Split is normal working))

**Comment by zeffii** [comment]
there's no serious plan to change the Range Float node, so will close to issue.

I was tempted to make a "range Int/Float" (like A Number node) but the complexity is not worth it.
