### ISSUE TITLE
Debug inside function

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1744]
Is it possible to receive link on error inside function or classes? In this case I want to receive 6, not 7.)

![2017-07-16_21-21-33](https://user-images.githubusercontent.com/28003269/28249775-226844fc-6a6d-11e7-87ff-d6eaddcea31d.png)

**Comment by zeffii** [comment]
Look slightly above ,  in the first line of the error in the screenshot, it says " on line: 6 "

**Comment by zeffii** [comment]
The function in line 5 and 6 isn't an error until called on line 7.

**Comment by Durman** [comment]
@zeffii Thanks.))
