### ISSUE TITLE
Testing Point Inside Mesh Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1746]
[point_inside_002_2017_07_24_13_03.zip](https://github.com/nortikin/sverchok/files/1169871/point_inside_002_2017_07_24_13_03.zip)
![prtscr capture_8](https://user-images.githubusercontent.com/3952687/28524570-61d79c02-70c4-11e7-82a0-0aaf7d92197d.png)

I am testing this node, seems like pretty intuitive, although I might be doing it wrong?

The idea is to somewhat fit the box elements perfectly, kind of creating Remesh, but each voxel box fits inside the 3D mesh input.

**Comment by enzyme69** [comment]
[ansv_points_inside_outside_001_2017_07_24_13_35.zip](https://github.com/nortikin/sverchok/files/1169948/ansv_points_inside_outside_001_2017_07_24_13_35.zip)
![prtscr capture_9](https://user-images.githubusercontent.com/3952687/28525795-c7970fe2-70c8-11e7-8bb6-962f7f6eeb54.png)

AN BVH Inside thing seems to give more accurate points inside. 

Wonder why...

**Comment by zeffii** [comment]
there's a thread for this already.. https://github.com/nortikin/sverchok/issues/1740
and a branch  https://github.com/nortikin/sverchok/tree/pinside_mod

> AN BVH Inside thing seems to give more accurate points inside.
> Wonder why...

different code, difference algorithm

**Comment by zeffii** [comment]
look at AnimationNodes' algorithm: https://github.com/JacquesLucke/animation_nodes/blob/c44280aae363402797e5da6319e755861b800380/animation_nodes/nodes/bvh_tree/is_inside_volume.py

read that and interpret what it does for yourself. 

##### What do I think?
I think the multiple random direction raycasting from each test point might be the strength of the algorithm. I'm happy to add variations to the node. Excellent project for someone else.

**Comment by Durman** [comment]
@enzyme69 
Points inside mesh have normal working. Do not use mask socket, the points out is already masked. Or use mask with primary points.
 I a little modernized your node tree.))
https://gist.github.com/f3be5fe21fb571b2fa7797c4b8e50add

![2017-07-24_19-20-03](https://user-images.githubusercontent.com/28003269/28530711-ca55de16-70a5-11e7-80f4-52da01543782.png)

**Comment by Durman** [comment]
@nortikin 
Constraints rotation is good, thanks.)

![rotation](https://user-images.githubusercontent.com/28003269/28573065-5d00ac78-715a-11e7-8785-c714aa5cb55b.gif)
