### ISSUE TITLE
"A Number Node": Why no Input for limits?

### ISSUE THREAD

**Issue by geniusupgrader** [nortikin/sverchok#1749]
Why has the "A Number Node" no inputs to its min and max values?
I want to assign the value of a variable to the min/max parametre?
Do I have to make my own Node for that?

**Comment by zeffii** [comment]
At the moment you can't set the min/max via a socket, only from the dropdown on the node's ui. It's not something that I considered, but I can imagine scenarios that could benefit from it. I think having three sockets is not appropriate as a default, but a modified version (`A Number (Parametric)`) could easily show all params at once, and even allow the int/float toggle to be controlled via socket.

feel free to make a pull request with a parametric version, with a different `filename` and `bl_idname`, if we like it it might even be accepted/merged

**Comment by geniusupgrader** [comment]
Why do you think having three sockets is not appropriate as a default? They don't need to be connected, do they?

**Comment by zeffii** [comment]
To economise on screen space, i prefer minimal default UIs.

**Comment by geniusupgrader** [comment]
Well, I still think the min/max values need sockets. But I get your point in minimal default UIs, especially with Sverchok and Nodes in general. But maybe just add the sockets, when the show_limits button is pressed? Is that possible?

**Comment by geniusupgrader** [comment]
Furthermore, you can cancel out the min/max values by passing a float value in the input socket. For example a second "A Number Node" beforehand, like in the picture below. I classify this a bug.

![cancel_out_min_max](https://user-images.githubusercontent.com/6190906/29239139-94696052-7f46-11e7-8b5a-ea4333f21be1.png)

**Comment by zeffii** [comment]
if you are inputting these values from a scriptnode instance, you can set the min/max via the script.

**Comment by geniusupgrader** [comment]
Yeah, with a scriptnode this is easily done. I'm just saying the "A Number" Node need some revision.

**Comment by zeffii** [comment]
> like in the picture below. I classify this a bug.

I don't see that as a bug, but we did discuss this in development thread at the time. Another thing that shouldn't be default, else it will always check all values being passed through.. you might use a Remap Range node instead.

> "A Number" Node need some revision.

let's see if we outlast this USA/North Korea thing first , ey?

**Comment by zeffii** [comment]
I appreciate the input on this node, btw. So i will take time to explain my position.

The number node is an _input node_, not a throughput node (despite the fact that it does have an input socket...i appreciate that this can fuel some frustration....). This is why you might want to use a Remap Range node to scale or clip incoming values to conform to a range.

**Comment by geniusupgrader** [comment]
I wasn't aware of the Remap Range node.
But for what exactly is the input Socket then, if it is apparently not really a input node?

Alright, then after all a new node, something like an "extended Number" node should be proposed.

**Comment by zeffii** [comment]
> But for what exactly is the input Socket then, if it is apparently not really a input node?

it is an input node for users who want to input with sliders, and limit min/max using a slider. This is user-input in the truest sense. If you want to pass data from a socket and enforce limits, then use Remap Range  node. I would resist a new node to essentially do what Remap Range currently does. You probably want that node and not a Number node..

**Comment by nortikin** [comment]
i use formula node as
`min(max(x,n[0]),n[1])`

**Comment by nortikin** [comment]
but remap is case too
