### ISSUE TITLE
Best working method for Profile Parametric Node together with Boolean Node

### ISSUE THREAD

**Issue by geniusupgrader** [nortikin/sverchok#1753]
I think this is a question.
See Picture below for reference.
When setting some variable to "0" in a Profile Parametric Node (see in the lower left corner), then only one face is left, like intended, ok....
But now I want to use a Boolean Node, after the "extrude region" node for combining another profile (made in similiar fashion like this one). And this is of course not working, because this profile is only a 2d plate.
So my Question: How to use the Profile Parametric Node and the Boolean Node together with this kind of use?

![now](https://user-images.githubusercontent.com/6190906/29240807-bbc0ce8a-7f6c-11e7-9067-30abea416b82.png)

**Comment by zeffii** [comment]
maybe if you share the .blend ( zip it and drag it into the issue ) i can show.

a few things might be happening here, the CSG Boolean expects both polyhedra to be manifold and have all faces pointing outwards. (not dissimilar to Blender's own boolean implementation).  Maybe if you bake the two polyhedra as objects you can inspect the face normals to confirm this.

Polyhedra that are adjacent (or: share parts of a planar surface with each other) will not behave with predictable results. This unfortunately is a limitation of the implemented CSG algorithm. Blender does not expose it's own Boolean implementation via bmesh operators, so we don't use that yet.

**Comment by geniusupgrader** [comment]
Please, look at it. I just want to overcome this issue...

[parametricbool1.zip](https://github.com/nortikin/sverchok/files/1219797/parametricbool1.zip)

**Comment by zeffii** [comment]
you might want a different node, "Mesh Expression" Node : http://nikitron.cc.ua/sverch/html/nodes/generators_extended/mesh_eval.html

**Comment by zeffii** [comment]
The important detail here is that this is how the Boolean Node is implemented. The use of the other nodes is incidental. Polyhedra with toching faces/planes will not be merged in a satisfactory fashion, but _optically_ it will be correct (most of the time)

**Comment by geniusupgrader** [comment]
Thanks, I will try the "Mesh Expression" Node. Issue can be closed?

**Comment by zeffii** [comment]
Sure!

**Comment by zeffii** [comment]
When i load that `.blend`  it shows this (i added drawing info)

![image](https://user-images.githubusercontent.com/619340/29241254-4a1ca772-7f76-11e7-9084-76c4491621f4.png)

The vertex marked, belongs to the face made up by the verts that have a red twin. The marked Vertex only toches the Edge of the other face, but doesn't topologically interact with it.

**Comment by geniusupgrader** [comment]
I don't know, what you want to say with your last post.
In my .blend file the second box starts exactly at the right face from the first box. Yeah, there are some visual artifacts when using Viewer Draw, but the boolean is working, or not? At least if I move the second box into the first one, intersect, join and diff are working. My previeous problem was with setting one length to zero.

**Comment by geniusupgrader** [comment]
So, now I have substituted the "Profile Parametric" node with the "Mesh Expression" node, but there is again the problem with the boolean node.
How do I use the Boolean node when I must join some body with a face? The optimal solution would be to remove all standalone faces or rather only allow bodies to be processed. In the current situation the Boolean node just goes in error mode and nothing is working..

**Comment by zeffii** [comment]
i'll insist then that you try more thoroughly to explain the expected result.

**Comment by zeffii** [comment]
(pretend I am stupid)

**Comment by geniusupgrader** [comment]
Ok, just now I have achieved, what I wanted to achieve with the "Mesh Expression" node. And the "Remove Doubles" note. In fact it was only a very easy body with an hole in it, but I wanted to be able to nullify every value and this was not possible with above way and the Boolean node.
If you're interested: [working.zip](https://github.com/nortikin/sverchok/files/1219926/working.zip)

Thanks, for your support today zeffii! 

Maybe one last follow-up question:
How to remove those in-between lines:
![follow up](https://user-images.githubusercontent.com/6190906/29242664-1f7069f8-7f91-11e7-9a71-636dc21d733a.png)

**Comment by zeffii** [comment]
the blender operator for that is "Limited Dissolve", so we have a node for that too.
