### ISSUE TITLE
vdmk2 not being flushed during animation updates

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1755]
mentioned here : 
https://github.com/nortikin/sverchok/pull/1754

The memory usage of vdmk2 goes up and up during uninterrupted animation. I suspect a more rigorous use of .GLflush may be needed.

-----

it should perhaps be mentioned that the vdmk2 is designed to optimally display static mesh data, by caching drawing calls once as a function, and calling that function repeatedly when a view update is called (for example: rotating a view around an unchanging object). This works great as long as the mesh isn't continuously updating/recaching. There's a small computation price to pay for caching the initial draw call (slower by `1.2 * non cached speed`), but redrawing from the cached function is about 10 times faster than non-cached.

In the scenario where animation comes in, and you intentionally cause mesh updates then you'd expect constant slower drawing (because it never uses the display list / caching feature )

**Comment by DolphinDream** [comment]
Any ideas if this can be easily fixed ? For some node-settings I get huge memory consumption making the SV animations with viewer draw a bit prohibitive (I need to restart blender often to clear the memory)

**Comment by zeffii** [comment]
at the moment the bmesh viewer might be a good fit? at least it's output will render anti-aliased if you an openGL render animation. (definitely not the case with vdmk2)

i've not thought much about this, but i'll poke around in it today.  it's a fundamental node and requires more cautious update policy :)

**Comment by zeffii** [comment]
I think this is the section that needs modification (it's been a long time since we really manipulated the opengl drawlist code...)

https://github.com/nortikin/sverchok/blob/a0fe08cb430fe403f0267231d066dc0dfce6d797/ui/viewer_draw_mk2.py#L420-L449

**Comment by zeffii** [comment]
it may have to be an option that you would enable if you are doing an animation, there's a chance that the option won't be the most efficient drawing solution for regular ui interaction. (tho ...we'll have to see .. but that's a suspicion of mine)

**Comment by DolphinDream** [comment]
I like to do animation with vdmk2 first before creating any mesh since i believe it is faster. Once i’m satisfied with the way the animation looks of course i have to use the bmesh node to make it renderable. Which btw, I wish there was a way I could render the SV output the vdmk2 creates without having to create a mesh/materials first :)

**Comment by zeffii** [comment]
> since i believe it is faster

for testing the vdmk2 should be fine, as long as you aren't running blender's renderanimation/ play animation mode. otherwise the bmviewer should really be plenty fast. Whether it generates the mesh in 0.002 or 0.2 second, it doesn't really impact the render time (or at least mesh generation times are much smaller than scene render duration )

but make another .blend that uses a standard (already present) node in sverchok that exhibits the memory leak (i'm too lazy and doing other stuff)  and if i can play it.. all i have to do is edit code to introspect. ( sorry.. that's the way things are at the moment )

**Comment by zeffii** [comment]
..some notes
```
            if options.get('genlist'):
                glDeleteLists(options['genlist'], 1)
```

**Comment by DolphinDream** [comment]
@zeffii is this a potential fix ?

**Comment by zeffii** [comment]
I think so `glDeleteLists()` is needed, glFlush just tells gl to finish drawing.

but I suggest you help me by making a simple .blend using existing nodes that starts to increase memory usage simply by playing. Then all i have to do is load the blend and debug.

**Comment by DolphinDream** [comment]
Will do.. as soon as I can.

**Comment by zeffii** [comment]
it might be something like
```python
if scene.is_playing and cache_size > 1:
    glDeleteLists(the_display_list, 1)
```

**Comment by zeffii** [comment]
it's certainly not solved yet, but it makes sense that glDeleteLists should be involved... I only hope I don't need to keep track of which cache was generated by which ViewerDraw Node :)

additionally, in 2.8 / VBO drawing I don't think there's a concept of Display List anymore..so this might be a shortlived fix.

**Comment by DolphinDream** [comment]
Yeah.. deleting the display lists makes sense. For 2.8 Will SV need to switch to VBO rendering then ?

**Comment by zeffii** [comment]
yep, exclusively.

**Comment by zeffii** [comment]
Blender devs might even make that switch in nightly builds of 2.79 eventually - and we'll be screwed royally :) (at least for a while)

**Comment by DolphinDream** [comment]
Here’s a node tree that sucks about 13MB/s on my system (blender 2.79 / MacOSX sierra):

gist: https://gist.github.com/8c48cf8455888e021a27eacef59e9deb

![sv-vdmk2-debug1-1](https://user-images.githubusercontent.com/2083719/31577907-bdabdfd8-b0e4-11e7-982d-e84c4502fe90.png)

![sv-vdmk2-debug1-2](https://user-images.githubusercontent.com/2083719/31577906-bd9faef2-b0e4-11e7-9088-89a7180ea82d.png)

**Comment by zeffii** [comment]
cool. no ETA.. but it's high on my priorities list.

**Comment by zeffii** [comment]
more notes to self... i think this is what our code does ( it was written a long time ago.. and my brain seems to have misplaced any details it once knew ..so i read it with no prior knowledge -- haha )

```python
            the_display_list = glGenLists(1)   # generate an index for this display list, returns the new index

            # prepare for the following gl commands passed by draw_geometry
            glNewList(the_display_list, GL_COMPILE)
            draw_geometry(n_id, options, data_vector, data_polygons, data_matrix, data_edges)

            # done passing command, store them in cache
            glEndList()

            # draw the cache stored at index stored in the variable "the_display_list" (just an int)
            glCallList(the_display_list)

            # i think this attempts to complete/finish drawing
            glFlush()
```
note that at no point is `glDeleteLists` called, which i have reason to believe causes all prior cache data to remain in memory.. new drawcalls are just added to the "bank of caches" .  It's interesting to print the value stored in the variable "the_display_list", it keeps going up.. but i think it should be 0 or 1 and not go higher for one node. I have not yet tried this with multiple ViewerDraw Nodes present, i would not be suprised that the cache draw call index (and value..cached draw instructions too ) takes a global key.

**Comment by zeffii** [comment]
when added a second VDMK2 .. and a small debug statement

```python
    if not 'error' in options:
        glCallList(the_display_list)
        print(the_display_list, n_id)
        glFlush()
```

```
....
<snip>
....
407 -7927488248669193630   (the_display_list,  n_id)
334 -7530883285341105186
408 -7927488248669193630
334 -7530883285341105186
409 -7927488248669193630
334 -7530883285341105186
410 -7927488248669193630
334 -7530883285341105186
411 -7927488248669193630
334 -7530883285341105186
412 -7927488248669193630
334 -7530883285341105186
413 -7927488248669193630
334 -7530883285341105186
414 -7927488248669193630
334 -7530883285341105186
415 -7927488248669193630
334 -7530883285341105186
416 -7927488248669193630
334 -7530883285341105186
417 -7927488248669193630

```
when both nodes are updated it becomes clear that there's a shared master / global display_list index
```
521 -7530883285341105186
522 -7927488248669193630
vdmk2 update holdout
523 -7530883285341105186
524 -7927488248669193630
vdmk2 update holdout
525 -7530883285341105186
526 -7927488248669193630
vdmk2 update holdout
527 -7530883285341105186
528 -7927488248669193630
527 -7530883285341105186
529 -7927488248669193630
527 -7530883285341105186
530 -7927488248669193630
527 -7530883285341105186
531 -7927488248669193630
527 -7530883285341105186

```
which makes sense and confirms my suspicion. In order to get this to work properly (discarding used caches...) more bookkeeping will be needed.

**Comment by zeffii** [comment]
I think this is the kind of bookkeeping needed to implement VBO too, so it makes sense to fix this now. sooner, rather than later.

**Comment by zeffii** [comment]
```python
if draw_new_data:
    existing_list = options.get('genlist')
    if existing_list:
        the_display_list = existing_list
    else:
        the_display_list = glGenLists(1)
    
glNewList(the_display_list, GL_COMPILE)
draw_geometry(n_id, options, data_vector, data_polygons, data_matrix, data_edges)

# done passing command, store them in cache
glEndList()

# draw the cache stored at index stored in the variable "the_display_list" (just an int)
glCallList(the_display_list)

# i think this attempts to complete/finish drawing
glFlush()    
```
this means also the cache could be tracked per node .. linking  `n_id` to any and all indexed display_lists, and upon deleting of a node the glDeleteLists should delete those references.

**Comment by zeffii** [comment]
i don't know if a `the_display_list` index can be reused. this will need to be investigated. 
i don't know if deleting an index recycles that number for `glGenList(1)` to produce again.

**Comment by zeffii** [comment]
according to  https://www.opengl.org/discussion_boards/showthread.php/128966-How-delete-a-display-list-quick-and-clean?p=968552&viewfull=1#post968552

> according to the specs, if you call glNewList again with a display list ID you used previously (and have not deleted), then it will replace that display list.

**Comment by zeffii** [comment]
i'm reluctant to push this without a few more eyeballs experiencing it.. but I think this is the simplest fix for now

https://github.com/nortikin/sverchok/pull/1814

**Comment by zeffii** [comment]
at this this keeps the display_list indices to the expected low counts..

**Comment by DolphinDream** [comment]
Awesome ! :) no more leaks.. blender has 108MB constant usage for 10 min now :) 

Using the same node tree I posted above.

**Comment by zeffii** [comment]
cool. This must have been broken since day one.

**Comment by DolphinDream** [comment]
Btw, are the display lists properly deallocated when the vdmk2 nodes are being deleted ? Also do the display lists need to be deleted when the vdmk2 nodes input sockets are disconnected (i.e. when they do not render anything) ?

**Comment by zeffii** [comment]
> Btw, are the display lists properly deallocated when the vdmk2 nodes are being deleted ?

not yet. thanks for reminding me. (won't fix that immediately) . this would happen in the `def free(self):` function. and seen as the `n_id` is used as a key of the `drawlists_3dview` dict. it can remove the index (value) easily -- i think ( this is the purpose of glDeleteLists after all)

> Also do the display lists need to be deleted when the vdmk2 nodes input sockets are disconnected (i.e. when they do not render anything) ?

ideally yes, it would be the "polite" thing to do. As soon a node has drawn once it will forever keep that display_list index and it will be recycled if that node ever redraws. But if a node is no longer drawing I would agree that it no longer needs to have a display_list index, this can be deleted and regenerated later.

i'll fix these two things asap.
