### ISSUE TITLE
Objects with different Materials joined as one

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1756]
Probably has been asked at some point, but is there a possibility or workaround in Sverchok to have a way to Join a bunch of Mesh objects, while retaining its Materials?

With Mesh Join, the Material disappear back into a single mesh.

Supposed I have a procedural Donuts made of 2 parts. My idea is to export this Donut as Alembic, where each frame will output a different shape of the donut.

Later in another Blender, I would like to load the Alembic, and hoping the material can directly connect to each Donut Part.

![prtscr capture_23](https://user-images.githubusercontent.com/3952687/29600826-8ddd8b90-881b-11e7-904a-9f0710bc685c.png)

**Comment by zeffii** [comment]
nope, not at this point because Sverchok's internal representation of mesh doesn't carry any material information. There's no ready made solution for this, but there are a number of (not so trivial) ways to implement it.

What benefit do you get from merging the geometries , that you can't get from ..say... grouping/parenting them?  i'd be more prepared to find solutions for that than messing with our ignorance of materials :)

**Comment by enzyme69** [comment]
Ok grouping so far has been fine, until I was thinking of another workflow: Alembic for every frame generated mesh in Sverchok (in this case: Donut and Icing). I am still trying to keep all the loose part of the mesh the same number and hoping that connection does not disappear.

--- The problem with Alembic might be hairier (more tricky?) than I mentioned here.

I am still wondering also if Alembic also can be good, since it seems to also mess up the Materials (losing all materials connection). This is I think when Pixar USD came in? I used to work a short time as Layout Artist and Asset person, the tools usually can get mixed up when using Alembic and connecting materials back with the asset.

I imagine that at some point, maybe there is case where we have multiple parts of nodes put together as one mesh, each with different materials and animated as one, joined with Armature.

It's ok I will investigate for now.

For now, thinking to have OBJ In and Out or Blend In and Out nodes :)

**Comment by enzyme69** [comment]
What would be a good start and interesting exercise is for me to use Python and Scriptnode to make some kind of Plane Grid with 2 Materials or more. Will think.

**Comment by enzyme69** [comment]
Reference:
https://blender.stackexchange.com/questions/27631/assigning-material-to-every-second-face-via-python

Interesting:
![prtscr capture_35](https://user-images.githubusercontent.com/3952687/29645182-2825a3ba-88bf-11e7-9555-7889ab169cf8.png)

**Comment by enzyme69** [comment]
Assigning Material Python:
https://blenderartists.org/forum/showthread.php?286081-Random-material-Assigner-V2-%96-assign-by-vertex-groups-or-loose-parts!

**Comment by enzyme69** [comment]
Become OT, but found this interesting.
![prtscr capture_36](https://user-images.githubusercontent.com/3952687/29647411-595ad9de-88cc-11e7-8559-97015428530f.png)

**Comment by Durman** [comment]
I am thinking over about it. ))

![2018-05-25_06-24-12](https://user-images.githubusercontent.com/28003269/40522935-45d6efd4-5fe4-11e8-8d73-44749aa80ce5.png)

**Comment by Durman** [comment]
![2018-05-25_08-47-30](https://user-images.githubusercontent.com/28003269/40526566-7b583334-5ff8-11e8-8cb9-47dff146ecb4.png)

**Comment by enzyme69** [comment]
Set Material node!? Material Index and assignment... neat!!

**Comment by Durman** [comment]
![2018-05-25_11-38-14](https://user-images.githubusercontent.com/28003269/40532423-74173558-6010-11e8-855c-27adaec59744.png)
