### ISSUE TITLE
Randomizing Single Object Multiple Splines Radius (from BlenderStackExchange)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1758]
I am looking at this and feel challenged to use Object ID to modify the radius of each Spline:
https://blender.stackexchange.com/questions/88712/randomize-the-radius-of-a-curve

I got this working
![prtscr capture_38](https://user-images.githubusercontent.com/3952687/29661459-6bda8e52-8907-11e7-82cf-77b75fefbe15.png)

But is there a way to make above setup more compact?

[multi_curve_python_004_2017_08_24_10_04.zip](https://github.com/nortikin/sverchok/files/1248435/multi_curve_python_004_2017_08_24_10_04.zip)

**Comment by enzyme69** [comment]
Try:
[multi_curve_python_005_2017_08_24_10_12.zip](https://github.com/nortikin/sverchok/files/1248445/multi_curve_python_005_2017_08_24_10_12.zip)

![prtscr capture_39](https://user-images.githubusercontent.com/3952687/29661862-ad4dbf70-8908-11e7-97ec-e54359276936.png)

Can be even more compacter?

**Comment by zeffii** [comment]
writing code is the compact way..
![image](https://user-images.githubusercontent.com/619340/29666156-6bcb4184-88d7-11e7-8e27-d82526b7c8e9.png)

**Comment by enzyme69** [comment]
@zeffii Aha... haha yeah I forgot this node! Cheers~~!!
