### ISSUE TITLE
Extrude Separate Face can be unstable

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1761]
[procedural_skull_006_2017_08_27_09_33.zip](https://github.com/nortikin/sverchok/files/1254260/procedural_skull_006_2017_08_27_09_33.zip)
![prtscr capture_54](https://user-images.githubusercontent.com/3952687/29748703-bdbcac2e-8b5e-11e7-90c5-b90608c109eb.png)

I made this procedural skeleton skull base head using Sverchok, I found that Extrude Separate Face is a bit strange that it keeps changing the topology.

This is similar to my "Procedural Spoon" setup. I remember exactly got the same issue.

Any tips on how to ensure the Polygon Face Index topology does not change?

**Comment by zeffii** [comment]
enzyme, what was my explanation for the topology instability?  same answer.

**Comment by zeffii** [comment]
(duplicate issue)

**Comment by zeffii** [comment]
> Any tips on how to ensure the Polygon Face Index topology does not change?

you can't . not with that node.

**Comment by zeffii** [comment]
I think your best bet it to take a snapshot of the mesh (using parametric mesh) when it has been modified to your liking, and work on the indices that that provides.

I guess not very satisfying, but that's down to the limitation already discussed in the spoon thread.
