### ISSUE TITLE
Voronoi Shell only

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1762]
Just a curiosity, is it possible to get just the shell of Voronoi fracture 3D?

[spherical_turtle_001_2017_08_28_09_00.zip](https://github.com/nortikin/sverchok/files/1255869/spherical_turtle_001_2017_08_28_09_00.zip)

![prtscr capture_3](https://user-images.githubusercontent.com/3952687/29766820-794cef16-8c23-11e7-9c31-bd1627f90490.png)

I tried using Solidify to have some kind of thickness, before then using bunch of points, testing it on Sphere. But I always get the middle part. If I manually delete the point, I sort of get the surface without thickness.

**Comment by enzyme69** [comment]
![prtscr capture_4](https://user-images.githubusercontent.com/3952687/29767469-e1937a2a-8c25-11e7-92df-ed10c652e4ad.png)
![prtscr capture_3](https://user-images.githubusercontent.com/3952687/29767470-e1bd8dba-8c25-11e7-94b0-cc18ceb064f0.png)

This... works in the magical kind of way. There is a manual work to delete that 1 vertices in the center, but other than that, can work.

**Comment by enzyme69** [comment]
[spherical_turtle_003_2017_08_28_09_19.zip](https://github.com/nortikin/sverchok/files/1255990/spherical_turtle_003_2017_08_28_09_19.zip)

We just simulate pangaea...

Any thing to add?

**Comment by enzyme69** [comment]
Maybe it's not that important.

**Comment by zeffii** [comment]
my 3d voronoi algorithm isn't suited to generate a fractured shell (not without considerable modification anyway).   but a valid approach is to first give a mesh thickness and then generate appropriate points inside the  "thickened" shell, then the algorithm works fine.
