### ISSUE TITLE
Trying to make Book Rack like Omar

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1764]
Omar made AN Book and Book rack:
https://squircleart.github.io/animation-nodes/procedural-bookshelves-in-animation-nodes.html

I started with a book , it's a hacky method, but maybe there is relationship between Solidify thickness and the inside here:

https://gist.github.com/863db6bbb20c3cecfacb399b33e6eee5

![prtscr capture_7](https://user-images.githubusercontent.com/3952687/29771986-d1fde8d4-8c39-11e7-9415-92b24a255535.png)

**Comment by enzyme69** [comment]
Probably will continue here:
https://github.com/enzyme69/blendersushi/issues/91

**Comment by enzyme69** [comment]
Wonder why when I scrub on the timeline, it keeps changing:
![prtscr capture_17](https://user-images.githubusercontent.com/3952687/29774115-b3ed9aec-8c43-11e7-8935-8d4742e7fff6.png)
[book_cheat_007_2017_08_28_12_52.zip](https://github.com/nortikin/sverchok/files/1256779/book_cheat_007_2017_08_28_12_52.zip)

**Comment by zeffii** [comment]
i get this when loading that .blend

![image](https://user-images.githubusercontent.com/619340/29775327-182b88a0-8c05-11e7-9973-c8215993355b.png)

```python
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 322, in do_update_general
    node.process()
  File "sverchok\nodes\modifier_change\extrude_edges.py", line 102, in process
    bmesh.ops.transform(bm, verts=[vertex], matrix=matrix, space=Matrix())
Node Extrude Edges had exception transform: keyword "space" expected a 3x3 or 4x4 matrix Matrix
```

**Comment by zeffii** [comment]
whenever you find there's an unexpected level of randomness when you update the node tree, it's going to be 1 of these
- there's a random without a seed value somewhere
- there's a node in the layout that uses bmesh operators for something. (f.ex "Remove Doubles" may not be deterministic )

makes me wish we had an indicator on the node for bm /

**Comment by zeffii** [comment]
and just to be clear about what I mean when using " non-deterministic ", i mean 

> non-Deterministic: Given the same input, a node can produce a variety of valid outputs. Sometimes an algorithm will have a choice between two or more elements but has no implemented constraints to favour any of the possible choices. There may indeed be no sane way to weigh options.

usually this is bmesh releated.

**Comment by enzyme69** [comment]
Thanks for explanation Zeff... yes I think you are probably correct again. Some kind of hidden switches.... oh well, I'll find another way to do this. Cheers~

**Comment by stansu** [comment]
the problem is Extrude Separate Faces, you can use index viewer to see random vertex sort.

**Comment by enzyme69** [comment]
Yes, maybe I need to snapshot the mesh after all. Like intermediate object.
