### ISSUE TITLE
Mesh Expression Combo issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1765]
[procedural_house_advanced_001_2017_08_31_00_36.zip](https://github.com/nortikin/sverchok/files/1265424/procedural_house_advanced_001_2017_08_31_00_36.zip)

I am trying to test using Mesh Expression combo, but found a bit of quirk...

- Wonder why I cannot use Objects In Mesh data with Mask from Mesh Expression
- More than one Mesh Expression seems to be failing.

I am trying to make a house for example, using a started Mesh that consist of 6 points.

**Comment by enzyme69** [comment]
![prtscr capture_29](https://user-images.githubusercontent.com/3952687/29900986-b9534ea4-8e38-11e7-8f92-d90b396b109c.png)

My feeling is that "Get Selected Components" as Mask should be a separate node?

**Comment by enzyme69** [comment]
I have a feeling, "List Mask" node level has something to do with this error exception.

**Comment by enzyme69** [comment]
Maybe "Mesh Expression" node "Selected" Masking has something to do with this issue.
![prtscr capture_32](https://user-images.githubusercontent.com/3952687/29901162-c1c28540-8e39-11e7-9064-ee6b7f659bc1.png)

**Comment by enzyme69** [comment]
GOTCHA!
![prtscr capture_34](https://user-images.githubusercontent.com/3952687/29901259-60af2348-8e3a-11e7-80f3-420cfbb54d52.png)
![prtscr capture_33](https://user-images.githubusercontent.com/3952687/29901260-60afcbe0-8e3a-11e7-8ccc-c280b1cf608e.png)

Mesh Expression Verts, need to be connected in order for Selected to function properly.

**Comment by enzyme69** [comment]
This explains why this did not work previously
![prtscr capture_37](https://user-images.githubusercontent.com/3952687/29901409-264d4b20-8e3b-11e7-9e79-c67a54adf2e5.png)
![prtscr capture_36](https://user-images.githubusercontent.com/3952687/29901410-26522a3c-8e3b-11e7-90de-04d15bba81c7.png)
![prtscr capture_35](https://user-images.githubusercontent.com/3952687/29901411-265206b0-8e3b-11e7-89a6-9a097ad74de0.png)

**Comment by zeffii** [comment]
@portnov wrote this node. best tag his name here

**Comment by portnov** [comment]
em? :)

**Comment by enzyme69** [comment]
@portnov I found that the node works fine and very stable, but it generates exception when there is nothing plugged out to Viewer. I usually plug Vertices Out into Viewer in order to get it to work.

The node is actually functioning really well as Selection Mask snapshot capture. I really like it and this has interesting usages.

**Comment by enzyme69** [comment]
Close it because no answer.
