### ISSUE TITLE
Phylotaxis Rotation, Vector -> Matrix Angle First and Last issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1766]
[flower_structure_004_2017_09_03_10_16.zip](https://github.com/nortikin/sverchok/files/1272842/flower_structure_004_2017_09_03_10_16.zip)
Wondering why with this setup, the first and last got flipped?

![prtscr capture_17](https://user-images.githubusercontent.com/3952687/30002116-ce743a4c-90e4-11e7-9be6-0b293eb823f8.png)

**Comment by enzyme69** [comment]
![prtscr capture_18](https://user-images.githubusercontent.com/3952687/30002155-b4c09978-90e5-11e7-8b46-0837be5a831f.png)

Apparently not first and last but 2 weird ones...

**Comment by enzyme69** [comment]
As I grow more up to 1000, few more weird ones appear.


![prtscr capture_19](https://user-images.githubusercontent.com/3952687/30002175-f19b020c-90e5-11e7-8db4-a244525ca5f3.png)

**Comment by zeffii** [comment]
isn't this something you solved in the past? best you struggle with it more

**Comment by zeffii** [comment]
you should look at the matrices that cause the flips... by ...as always... reducing the number of petals way down to a number that's still manageable for the indexviewer.  the viewer the matrices using list index and see if there's a common thread ( the are probably identity matrices. ..default matrices as a result of zero rotation )

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/30005759-db34d930-90e9-11e7-8dc0-24e82b7e5652.png)

![image](https://user-images.githubusercontent.com/619340/30005769-0eaff894-90ea-11e7-9985-7d67480796f5.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/30005789-7ef4724c-90ea-11e7-8a33-125de358a81c.png)

flipping here, means you should use a different approach ( do transforms in a different order )

**Comment by zeffii** [comment]
https://gist.github.com/f1ec97bc306a3c5a18931b75ca1fd1c1

**Comment by enzyme69** [comment]
Thanks Zeffii, I will study this probably related to the Fish Scale issue I am facing:
https://github.com/nortikin/sverchok/issues/1768
