### ISSUE TITLE
Fish Scales Orientation Over 3D Surface

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1768]
This one is another particular matter that is tricky for me. Testing a setup that simulate some kind of Scale. Maybe the way I am doing it using Vertex Normal is not right.

Kind of looking at this video tutorial earlier:
https://www.youtube.com/watch?v=Vxc4P0YI2rI&t=7s

I wanted to simulate scale, but orientation might tricky. Adaptive Face is probably kind of handling this and already showing "directional issue".

![prtscr capture_22](https://user-images.githubusercontent.com/3952687/30003375-4436c32a-90ff-11e7-86fc-d5e785e5b6fe.png)

Is it going to be tricky to simulate "hair" "plant like leafs" or "fish scale" and "direction"? Maybe they are all different. Maybe "scale" for now.

[ANSV_flower_004_2017_09_03_13_25.zip](https://github.com/nortikin/sverchok/files/1272941/ANSV_flower_004_2017_09_03_13_25.zip)

How to control the direction better?

**Comment by zeffii** [comment]
either reformulate your question (which is hard to understand)  or model an example representation of the desired end result by hand and post a screenshot . Screenshot of a failing layout are only informative if we can be sure we understand the desired end result.

**Comment by enzyme69** [comment]
I just got an idea while having shower, I think using IcoSphere is a bad way to start. I am using Cylinder and using Face Normal first, and try to get some kind of Fish Scale going in direction based on Face Point.

Will be back will make Live Noding video first...

**Comment by enzyme69** [comment]
So basically in the nutshell, I wanted to have control over an object that will be like a Shell or Tile of Roof over a surface, hopefully to follow the direction of the surface, stick with it nicely like Fish Scale.


![prtscr capture_25](https://user-images.githubusercontent.com/3952687/30008314-b7bd719c-9161-11e7-9173-b8a44d18da17.png)
![prtscr capture_24](https://user-images.githubusercontent.com/3952687/30008315-b7be9c20-9161-11e7-96e4-dbcc8e863741.png)

**Comment by enzyme69** [comment]
It's very much almost like Polygon Adaptive, actually. But I wanted to have more control. I imagine that at some point to try drawing this on 3D Surface using Grease Pencil and want it to follow the direction and normal.

Above setup is almost working:
[ANSV_flower_008_2017_09_04_01_13.zip](https://github.com/nortikin/sverchok/files/1273391/ANSV_flower_008_2017_09_04_01_13.zip)

**Comment by enzyme69** [comment]
With Rotation and Angles, I often just conveniently plug Vector or Normal to get the **Aim** Direction, and then I think I didn't care much about the **Rotation**

**Comment by enzyme69** [comment]
When using Cylinder it seems to work, as soon as I angle the Cylinder into Cone, things become strange. And also with Vertices number, when I use Odd Number, it flips...

![weird_scale_001](https://user-images.githubusercontent.com/3952687/30008559-16580710-9164-11e7-83a9-0dbfcd3cc6c1.gif)

**Comment by enzyme69** [comment]
![prtscr capture_26](https://user-images.githubusercontent.com/3952687/30008706-7c82d19a-9165-11e7-8e05-98684f51d134.png)

@zeffii Thanks!!

**Comment by enzyme69** [comment]
https://gist.github.com/bfafa4568e72a8dcf07aa9cee0b9996d
