### ISSUE TITLE
Small Basic Fractal to Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1769]
Out of curiosity, I am porting this "Fractal" setup of Simple Basic program into Sverchok Script Node.

![prtscr capture_38](https://user-images.githubusercontent.com/3952687/30027255-7aabe92a-91c3-11e7-9bf5-e3260ba774d8.png)
![prtscr capture_37](https://user-images.githubusercontent.com/3952687/30027252-79e679e2-91c3-11e7-8f0b-1506fd5a5fb3.png)

```python
"""
in seed s   d=1   n=2
in maxLoop s   d=1000   n=2
in x s   d=100   n=2
in y s   d=100   n=2
out verts      v
"""

import random

random.seed(seed)

def makeFractal(maxLoop, x=100, y=100):
    listFractal = []
        
    for i in range(1,maxLoop):
            
        r = random.randint(0, 2)

        if r==1:
            ux = 30
            uy = 1000
        elif r==2:
            ux = 1000
            uy = 1000
        else:
            ux = 150
            uy = 30

        x = (x + ux) / 2
        y = (y + uy) / 2  
        
        listFractal.append([x,y,0])
        
    return listFractal

point_gen = makeFractal(maxLoop, x, y)

verts = [[point_gen]]

```

I am wondering about a couple of thing, in the Archimedes Spiral example, you use "yield" and other function, is that to ensure things can work when we are Vectorizing?

The script is working and it does result in something I can use, but any additional idea to make this even more interesting? 

Any simple example how things can be vectorized inside Script Node? (sorry if I asked this before)

**Comment by nortikin** [comment]
vectorizing for-in always

**Comment by zeffii** [comment]
search the python docs for the kw `yield` . I also give examples on [blenderscripting.blogspot](http://blenderscripting.blogspot.nl/search?q=yield)
