### ISSUE TITLE
Decal Node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1770]
Take a look at this:
https://blender3d.com.ua/sozdaniye-besshovnykh-decal-meshey/

Wondering how it would be implemented as node in Sverchok?

Curve Projected into surface, then decal?

**Comment by nortikin** [comment]
lattice used. you mark deforming part by hands, so it usefull in blender default tools. node is not so usefull here.

**Comment by enzyme69** [comment]
Got it!
