### ISSUE TITLE
Macro Ideas: How about > Merge Join all Viewer Draw

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1771]
I got an idea and wanted to make this happening, basically very often I have multiple Viewer Draw output of setup that I put together into a single Mesh Join by hand. Would be nice to just have Macro that does this.

Such a fine task for beginner Python coder!

**Comment by enzyme69** [comment]
How do one make this > macro thing. I realized @zeffii made some super useful one like Multi Obj VD.

**Comment by enzyme69** [comment]
Procedure:
- Get selected multiple VD
- For every VD with same Vertices and Edge/Poly, use List Join
- Pipe all into Mesh Join
- Remove Double is optional.

**Comment by enzyme69** [comment]
Before:
![prtscr capture_77](https://user-images.githubusercontent.com/3952687/30140640-6ae084d6-93b9-11e7-88fe-a226b3f43daa.png)
After:
![prtscr capture_75](https://user-images.githubusercontent.com/3952687/30140639-6adaae9e-93b9-11e7-83a2-930dc1877104.png)

**Comment by enzyme69** [comment]
Studying now... TO BE CONTINUED:
https://github.com/nortikin/sverchok/wiki/Macros

**Comment by enzyme69** [comment]
Hardcoded for multi box nodes output:

```python
import bpy

nt = bpy.data.node_groups['NodeTree']

# METHOD A: get just box nodes

box_list = []

for name, node in nt.nodes.items():
    if "Box" in name:
        box_list.append(node)

# METHOD B: get Viewer Nodes nodes that being selected by user 
        

listjoinVerts = nt.nodes.new("ListJoinNode")
listjoinEdges = nt.nodes.new("ListJoinNode")

# Connect Vertices output of every Box Node into List Join
for num, box in enumerate(box_list):
    nt.links.new(box.outputs['Vers'], listjoinVerts.inputs[num])
    nt.links.new(box.outputs['Edgs'], listjoinEdges.inputs[num])
    print(num, box, "--- ok")

# Finally, connect mesh join into list join output for vertices and edges


# create Mesh Join node
meshjoin = nt.nodes.new("SvMeshJoinNode")

nt.links.new(listjoinVerts.outputs[0], meshjoin.inputs['Vertices'])
nt.links.new(listjoinEdges.outputs[0], meshjoin.inputs['PolyEdge'])

# create new Viewer Node
myviewer = nt.nodes.new("ViewerNode2")
myviewer.activate = False


# connect Viewer and Mesh Join node
nt.links.new(meshjoin.outputs['Vertices'], myviewer.inputs['vertices'])
nt.links.new(meshjoin.outputs['PolyEdge'], myviewer.inputs['edg_pol'])

myviewer.activate = True
```

Another method is to select all current active Viewer Node and then traverse back once and join Mesh, need to be aware of Vertices, Edges, Poly data, sometimes Mesh might contain these or not.

Cannot assume each data is the same... hmm..

**Comment by zeffii** [comment]
> a fine task for beginner Python coder!

agreed. the default macros are quite comprehensive examples

**Comment by zeffii** [comment]
I added a issue-link to the wiki/macros page, which gives even more examples
