### ISSUE TITLE
Poke and Diagonal Strawberry Topology

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1773]
Is it possible to Select Mesh Element by Location based on the most outer points of the Poke?

[sv_poke_03_2017_09_07_13_21.zip](https://github.com/nortikin/sverchok/files/1284775/sv_poke_03_2017_09_07_13_21.zip)

I am also trying to use Select Similar Face Angle.

A quick trick to get the diagonal topology like strawberry.
https://vimeo.com/82099913

![prtscr capture_85](https://user-images.githubusercontent.com/3952687/30165458-7bcca10c-9423-11e7-8f9b-b3e2331c4898.png)

**Comment by enzyme69** [comment]
I am up to here... 

https://gist.github.com/a6d4d46005d77b98f4d86d87bbe88e8f

**Comment by zeffii** [comment]
i think you are trying to achieve a relatively complex manual effect using nodes that aren't really "composeable" into a chain that would allow you to nodify the effect.

i'm not saying it's not possible but maybe you should try describing in a flowchart (forget what nodes we have) the process like

```
start_shape (verts, faces) ->
   > (verts, faces, selection mask) some operation (verts, faces, indices of new faces) -->
       > etc 
                  
                 > output
```
the better you get at describing the details of sequenced operations, the better you will get at finding novel solutions.

**Comment by enzyme69** [comment]
[sv_poke_04_2017_09_08_00_36.zip](https://github.com/nortikin/sverchok/files/1286437/sv_poke_04_2017_09_08_00_36.zip)

Yes probably above is not the best solution to the issue.

I am sure this can be simpler:
1. Provide quad objects.
2. Poke to get criss-cross diagonal pattern
3. Get just the edges that is the original, but keep the edges and points that connects the criss-crossing points.

**Comment by enzyme69** [comment]
I'll think again...

**Comment by enzyme69** [comment]
And "Remove Doubles" also a bad choice because it might change the index pattern... yikes.

**Comment by zeffii** [comment]
ideasman recently changed the behaviour (literally last week) to have stable remove doubles, sorting by index was possible in that case.

but yeah, i'll say this a million times. if you want to solve problems you need to get in the habit of reducing the problems down into the smallest subproblems , almost psuedo code. write them out.. .

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/search?utf8=%E2%9C%93&q=poke&type=

**Comment by enzyme69** [comment]
​Wow... things that SV coolness one can dig is abundant. I only know so
little. I must read the whole code like a good novel.

**Comment by zeffii** [comment]
> I must read the whole code

sure :)
