### ISSUE TITLE
Add "View Node Source" to NPanel's Node tab.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1776]
might entice the reader.  it should open a copy.. or not... or option for both.

**Comment by zeffii** [comment]
branchname :   `sourceviewer`

i'll have two ways to view the source
- directly using TextEditor  (simplest to implement)
- using custom path to Preferred Code Editor.    (most comfortable for end user who wants to code a bit)

milestones

- [ ] show path to node in npanel (with option to copy path)
- [ ] add button to view source in TextEditor
- [ ] add button to view source in Preferred code editor ( likely will need a custom entry in Sverchok preferences for the command to call on the path)

**Comment by zeffii** [comment]
fullpath
```python
import bpy
import os
import sverchok

def get_filepath_from_node(n):
    """ get full filepath on disk for a given node reference """
    sv_path = os.path.dirname(sverchok.__file__)
    path_structure = n.__module__.split('.')[1:]  # strip sverchok
    path_structure[-1] += '.py'
    return os.path.join(sv_path, *path_structure)

nodes = bpy.data.node_groups['NodeTree'].nodes
ico = nodes['IcoSphere']

fp = get_filepath_from_node(ico)
print(fp)
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/30239972-8dc366a8-9567-11e7-814d-cac833e857e4.png)

**Comment by zeffii** [comment]
done

### note to the user... 

if you are symlinking your sverchok, i think you don't want to edit the file that the external viewer throws at you..  use it just to read the code.

**Comment by zeffii** [comment]
the string for Ext Editor will call this.
```python
    # you are setting this value from the preferences window.
    sv_preferences.external_editor = "sublime_text"

    fpath = `<this value is inferred from node.__module__>`
    app_name = sv_preferences.external_editor
    subprocess.call([app_name, fpath])
    
```

**Comment by zeffii** [comment]
am tempted to add a function that checks for the real location on disk, i use symlinked directories for convenience and the path that the function `get_filepath_from_node` returns is unaware of this.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/30247647-4dfdb340-9619-11e7-99d7-e381274e379c.png)

tho you will have to use the convention for backslashes suitable for your os. test this and if this is problematic for linux/mac we can add specfic os routing

**Comment by nortikin** [comment]
first i missed that need define text editor

**Comment by zeffii** [comment]
here's a script i'll use to set this property for my machine
```python

from sverchok.utils.context_managers import sv_preferences
with sv_preferences() as prefs:
    prefs.external_editor = "sublime_text"
    prefs.real_sverchok_path = r"C:\Users\zeffi\Desktop\GITHUB\sverchok"
```
