### ISSUE TITLE
can we have twist option in torus?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#1780]
![torustwist](https://user-images.githubusercontent.com/9460236/30255584-6703acb4-96d7-11e7-96a5-8d71eca6424a.gif)

**Comment by zeffii** [comment]
we could even have a twist option that knows how many segments that minor ring has, to allow the start-end connection to line up to the most appropriate verts. maybe @DolphinDream is interested

**Comment by DolphinDream** [comment]
I'll take a look.

**Comment by nortikin** [comment]
@DolphinDream , please, such little improvements make life easier

**Comment by DolphinDream** [comment]
PR coming soon..

![sv-twistedtorus-1](https://user-images.githubusercontent.com/2083719/30308695-1879b376-9755-11e7-8ad7-2964f6710bd0.png)

**Comment by stansu** [comment]
Wow!
So fast.

**Comment by DolphinDream** [comment]
Here's the PR for this feature: https://github.com/nortikin/sverchok/pull/1782
