### ISSUE TITLE
recent B2.79 builds may also start to affect Sverchok

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1785]
**edit**

i have a ~semi~ working branch now here - https://github.com/nortikin/sverchok/tree/customtree_test

-----------

#### original

not to be alarmist or anything but I get this error starting Sverchok with a builder.blender.org build for 2.79
```python
Exception in module register(): 'sverchok\\__init__.py'
Traceback (most recent call last):
  File "scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "sverchok\__init__.py", line 166, in register
    m.register()
  File "sverchok\utils\sv_panels_tools.py", line 253, in register
    bpy.types.SverchCustomTreeType.Sv3DProps = CollectionProperty(type=Sv3dPropItem)
AttributeError: 'RNA_Types' object has no attribute 'SverchCustomTreeType'

```
I think this relates to a new imposed limitation on what can be registered to `bpy.types`

**Comment by zeffii** [comment]
`https://developer.blender.org/T52599`

**Comment by nortikin** [comment]
where did you found this 279c build? maybe it is experimental for now?

**Comment by nortikin** [comment]
SverchCustomTreeType cannot be registered? https://github.com/nortikin/sverchok/blob/42d7f706228f35b882daa259de9eb769965bf740/node_tree.py#L370

**Comment by zeffii** [comment]
i have a semi working branch now

here -

with still a problem. for instance. This used to put `SvMyNode` directly onto `bpy.types`
```python
def register():
    bpy.utils.register_class(SvMyNode)
```
and we used to be able to get a reference to the class using `node_ref = getattr(bpy.types, "SvMyNode")`. New changes now don't add the node reference `bpy.types.SvMyNode` anymore. (which is probably good..)

This means at the moment, the spacebar menu and extended search (anything that uses `getattr(bpy.types, NAME)` will fail)

**Comment by zeffii** [comment]
i'm sure there's an easy way to find the `node_ref` from `bl_idname`, just this way we use now doesn't work anymore.

**Comment by zeffii** [comment]
if not we will use a wrapper for `bpy.utils.register_class` which will store a global dict for us (probably a good idea anyway)

```python
sv_node_lookup = {}

def sverchok_register_class_wrapper(class_reference):
    sv_node_lookup[class_reference.bl_idname] = class_reference
    bpy.utils.register_class(class_reference)

```
then instead of bpy.types we use direct dict lookup
```python
node_ref = getattr(bpy.types, "SvClassNameNode")
node_ref = sv_node_lookup["SvClassNameNode"]
```

**Comment by zeffii** [comment]
@nortikin  yes, the mos recent buildbot build. I don't think this is a major problem yet , but SV will not work 100% in new version until we make a few adjustments.

**Comment by zeffii** [comment]
ideasman42 confirms in IRC that we will have to maintain a lookup table instead of relying on `getattr(bpy.types, node_bl_idname)`.

**Comment by zeffii** [comment]
after reading `nodeitems_utils` , it appears we can go `bpy.types.Node.bl_rna_get_subclass("SvScalarMathNodeMK2").<attribute>`  
like
```python
>>> bpy.types.Node.bl_rna_get_subclass("SvScalarMathNodeMK2").sv_icon
'SV_FUNCTION'
```

**Comment by zeffii** [comment]
also Monad will need some attention.
https://github.com/nortikin/sverchok/blob/99d8c99016041828b6d70cb3fcc124ceaeb91022/core/monad.py#L100

**Comment by zeffii** [comment]
@nortikin   `b279c` is the directory name i choose for the blender directory, it is not officially a `c` release.

looks these changes can be pushed soon and are backwards compatible. I have not yet tried the `monad` fixing mentioned in the above comment

**Comment by zeffii** [comment]
hmmm.. not sure how this will go

https://github.com/nortikin/sverchok/blob/99d8c99016041828b6d70cb3fcc124ceaeb91022/core/monad.py#L287-L295

**Comment by zeffii** [comment]
ok. cool.
```python
>>> cls = bpy.types.Node.bl_rna_get_subclass_py("SvGroupNodeMonad_2833115989016")
>>> cls
<class 'bpy_types.SvGroupNodeMonad_2833115989016'>
```

**Comment by zeffii** [comment]
according to ideasman42 we should not use `bl_rna_get_subclasses_py` for several reasons 
  1. because it performs a lot of lookup
  2. we should be keeping track of the classes anyway.

Reason 1 doesn't really bother me, but it is a valid concern.
Reason 2 yeah we do, and the only problem is the dynamic classes generated by the Monad system.

After all nodes are registered ( or during the registration process ) we can build a lookup

```python
n= --> nodes = bpy.data.node_groups['NodeTree'].nodes
>>> nodes = bpy.data.node_groups['NodeTree'].nodes
>>> n = nodes['Viewer Draw']
>>> n
bpy.data...nodes["Viewer Draw"]

>>> bpy.types.Node.bl_rna_get_subclass
                                      (
                                      _py(
>>> bpy.types.Node.bl_rna_get_subclass_py("ViewerNode2")
<class 'sverchok.nodes.viz.viewer_mk2.ViewerNode2'>

>>> n.bl_idname
'ViewerNode2'

>>> ## Now the dynamically generated nodegroup ( Monad )
>>> 
>>> n2 = nodes['
                Monad']
                Viewer Draw']
>>> n2 = nodes['Monad']
>>> n2.bl_idname
'SvGroupNodeMonad_1466612553604'

>>> bpy.types.Node.bl_rna_get_subclass_py(n2.bl_idname)
<class 'bpy_types.SvGroupNodeMonad_1466612553604'>
```

but the problem i'm looking at is what to do with the dynamic classes, getting a direct reference. I haven't put a lot of time into this, but it looks like a fat problem.

**Comment by zeffii** [comment]
it turns out that in the `post_load handler` we register all dynamic monad classes in `update_cls()`,  this means that we can build a proper wrapper for `bpy.utils.register/unregister` to build a class reference lookup table.

to repeat from what is stated earlier in this issue. we will need to make a wrapper for `bpy.utils.register_class` to be used specifically for when we register a Node.  any other class (Ops etc... will be done using normal `register_class`.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/30511945-e8da5ac0-9ae3-11e7-8bd7-68f166127f65.png)

##### sverchok/utils/__init__.py
```python
import bpy

node_classes = {}


def register_node_class(class_ref):
    node_classes[class_ref.bl_idname] = class_ref
    bpy.utils.register_class(class_ref)

def unregister_node_class(class_ref):
    del node_classes[class_ref.bl_idname]
    bpy.utils.unregister_class(class_ref)

```

**Comment by zeffii** [comment]
we would need to start registering nodes this way.

either use the wrappers
```python
def register():
    sverchok.utils.register_node_class(SvNumberNode)


def unregister():
    sverchok.utils.unregister_node_class(SvNumberNode)
```
or the factory..
```python
register, unregister = sverchok.utils.register_node_classes_factory((SvNumberNode,))
```

**Comment by zeffii** [comment]
An alternative is to have a separate registration step at the end after all nodes have been added to `sverchok.nodes`.  It is possible to iterate over each item and build the `node_classes` dict that way. However that method does require unique treatment of dynamically added monad classes. (not hard, just important to mention)

unfortunately the code i'm thinking off is not very pretty .

the choice is .  
  - modify 233 node files with the alternative register/unregister methods, or 
  - write a nice automatic "post processing" batch introspection of `sverchok.nodes`.

**Comment by zeffii** [comment]
well.. i don't feel like changing the registration of the standard nodes, so a final automated method is the only remaining option :)

this is ugly, but the end result is what we need
```python
import sverchok

print(dir(sverchok.nodes))

items_to_drop = [
    'automatic_collection', 'basename', 'defaultdict', 
    'directory', 'dirname', 'nodes_dict', 'os']

def track_me(item_name):
    if item_name.startswith("__"):
        return False
    elif item_name in items_to_drop:
        return False
    return True

node_classes = {}
for i in dir(sverchok.nodes):
    if track_me(i):
        file_ref = getattr(sverchok.nodes, i)
        for j in dir(file_ref):
            if track_me(j):
                node_ref = getattr(file_ref, j)
                for varname in dir(node_ref):
                    isnode = False
                    try:
                        cls = getattr(node_ref, varname)
                        isnode = cls.bl_rna.base.name == "Node"
                    except:
                        ...
                    if isnode:
                        node_classes[varname] = cls


print(len(node_classes))   # 242


```

**Comment by zeffii** [comment]
or..
```python
import sverchok


items_to_drop = [
    'automatic_collection', 'basename', 'defaultdict', 
    'directory', 'dirname', 'nodes_dict', 'os']

def track_me(item_name):
    return not item_name.startswith("__") or item_name in items_to_drop

node_classes = {}

def filter_module(_mod):
    return (getattr(_mod, item) for item in dir(_mod) if track_me(item))

for i in filter_module(sverchok.nodes):
    for j in filter_module(i):
        for cls in filter_module(j):
            try:
                if cls.bl_rna.base.name == "Node":
                    print('yes')
                    node_classes[cls.bl_idname] = cls
            except:
                ...

print(len(node_classes))

```

**Comment by zeffii** [comment]
ignore this
```python
# def register():
#     sverchok.utils.register_node_class(SvNumberNode)


# def unregister():
#     sverchok.utils.unregister_node_class(SvNumberNode)

# register, unregister = sverchok.utils.register_node_classes_factory((SvNumberNode,))
```

**Comment by zeffii** [comment]
I choose for an automated `node_classes` lookup generator. seems to work nicely.  Can probably push soon.

**Comment by zeffii** [comment]
this should be safe to `pull` now.  but might need to be tested on official b2.79 builds. think it is safe anyway.

**Comment by zeffii** [comment]
inspect.getmembers(object[, predicate])

   - inspect.isclass
   - inspect.ismodule

```python
import inspect
name_func_tuples = inspect.getmembers(module, inspect.isfunction)
```
per https://stackoverflow.com/a/15813469/1243487

**Comment by zeffii** [comment]
```python
import inspect

node_cats = inspect.getmembers(sverchok.nodes, inspect.ismodule)
for catname, nodecat in node_cats:
    print(catname)
    node_files = inspect.getmembers(nodecat, inspect.ismodule)
    for filename, fileref in node_files:

        classes = inspect.getmembers(fileref, inspect.isclass)
        for clsname, cls in classes:
            try:
                if cls.bl_rna.base.name == "Node":
                    node_classes[cls.bl_idname] = cls
            except:
                ...

print(node_classes)
            
```

**Comment by zeffii** [comment]
tested and pushed.
