### ISSUE TITLE
Assigning Modifier via Exec

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1787]
![screen shot 2017-09-15 at 09 58 59](https://user-images.githubusercontent.com/3952687/30460811-a8f3fa98-99fc-11e7-8fea-1c9b9ee6774a.png)

Kind of wanting to use Exec Mode to add Modifier to all incoming Objects In, but getting recursive limit...

**Comment by Kosvor2** [comment]
![exec_modifier_create123](https://user-images.githubusercontent.com/22656834/30463216-e4fb243a-99e3-11e7-9aa5-5b06518b8df4.png)

**Comment by enzyme69** [comment]
@Kosvor2 Спасибо!
