### ISSUE TITLE
Vector Field Visualization Needs Hints

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1788]
I am looking at this article for Processing.

Wondering if I am doing the right thing in Sverchok using Vector P Field.

[vector_p_001_2017_09_15_10_52.zip](https://github.com/nortikin/sverchok/files/1306107/vector_p_001_2017_09_15_10_52.zip)

![prtscr capture_8](https://user-images.githubusercontent.com/3952687/30479264-caad8d42-9a57-11e7-9315-d66e2d7aff5c.png)

@zeffii Have you done something similar?

**Comment by zeffii** [comment]
what article

**Comment by enzyme69** [comment]
@zeffii forgotten link:
https://generateme.wordpress.com/2016/04/24/drawing-vector-field/amp/

**Comment by zeffii** [comment]
and what are you trying to achieve ( don't use words... show me )

**Comment by enzyme69** [comment]
Something like this:
https://twitter.com/omarsquircleart/status/908067741613133824

**Comment by enzyme69** [comment]
http://www.tokeru.com/cgwiki/index.php?title=File:Pig_worms.gif

**Comment by zeffii** [comment]
you'll have to figure it out on your own.

**Comment by zeffii** [comment]
( i don't have an instant answer for you )

**Comment by enzyme69** [comment]
Ok, I will investigate~ Cheers. Just in case anyone here has done something similar.

**Comment by enzyme69** [comment]
Apparently related to Curl Noise of Perlin function...
https://vimeo.com/169438746

**Comment by nortikin** [comment]
vector field representation can be 
as points on grid with vertices reacting on forces
or as starting points, and loop recursive moving by forces making lines at the end.
Don't know more, maybe fields can leave other way.

**Comment by nortikin** [comment]
by the way, acting with second case (start points and recursion loops) is less accurate, to find shape you have predict line movements. they can simply collect on one corner.

**Comment by enzyme69** [comment]
@nortikin recursively similar in the past when we want to do random walk? 

Omar has some examples:
https://twitter.com/omarsquircleart/status/908067741613133824

So with noise, those points will never actually touch or across one another? I still don't get it. There are many examples out there of people doing similar thing, but need one basic simple examples. 

This and reaction diffusion are interesting as it is basically some kind of "magic algorithm" that makes points or lines to magically fill up 3D space or 2D space.

I will probably study Daniel Shiffman Processing example and then can figure out what's going on.

With Processing, sometimes it is a lot easier to make "trace" of points. Maybe if Sverchok can have Trace node of some sort. 

This is seems to get into area of simulation.

**Comment by zeffii** [comment]
Each strand is a Trace of what happens to one Vector if it moves through the "Turbulence Field". So if you have a grid of Vectors and each has a trace, you have to offest the original vectors to make the traces behave like their are moving through a turbulence Field.  Yeah it doesn't appear that these traces intersect at any point.

my understanding is that the node they use for that in AN executes Cythonized code, which will perform much faster than sverchok at scale. I think this effect can be achieved with Modifiers ..just modifiers.

**Comment by zeffii** [comment]
without writing a dedicated node for this / script node  i'm not sure you'll get similar results.

**Comment by enzyme69** [comment]
Ok, cheers Zeff, let's wait for Omar to post his study.

**Comment by zeffii** [comment]
this won't answer your question, but it will give an interesting effect
```python
"""
in initial_grid v d=[] n=1
in rescale s d=0.2 n=1
in sections s d=10 n=1
in offset_vector v d=[0,0,0] n=2
out verts v
out edges s
"""

from mathutils import noise

verts.append([])

_noise_type=5
for v in initial_grid:
    for offset in range(sections):
        voff = v[0], v[1], (v[2] + (offset * rescale))
        voff = voff[0] + offset_vector[0], voff[1] + offset_vector[1], voff[2] + offset_vector[2]
        u = noise.noise_vector(voff, _noise_type)[:]
        xv = u[0] - voff[0], u[1] - voff[1], u[2] - voff[2]
        xv2 = xv[0] + offset_vector[0], xv[1] + offset_vector[1], xv[2] + offset_vector[2]
        verts[0].append(xv2)
```
move the Z of Vector in, very gradually, it's like maggots in a suspension

![image](https://user-images.githubusercontent.com/619340/30634704-424910a6-9df0-11e7-9387-f76b69c2d065.png)

**Comment by enzyme69** [comment]
![prtscr capture_51](https://user-images.githubusercontent.com/3952687/30642546-a81e6c42-9e4e-11e7-875f-0fcb03744059.png)

Neat! Similar to this setup, but actually different? Your maggots motion seems to be more energetic, while my maggot is just flowing underwater.
![prtscr capture_51](https://user-images.githubusercontent.com/3952687/30642572-c0e70054-9e4e-11e7-9edb-97521864072c.png)

![maggot_001](https://user-images.githubusercontent.com/3952687/30642826-b9b0c8a0-9e4f-11e7-93ea-e25c8688a559.gif)

[sv_zeffii_maggot_004_2017_09_20_11_57.zip](https://github.com/nortikin/sverchok/files/1317620/sv_zeffii_maggot_004_2017_09_20_11_57.zip)

I think the Curl and Swirl involves some kind of physics simulation. This part I got lost. I don't know if Blender's own Particle and Force simulation can do it, maybe possible.

From the Houdini example by Entagma, I think he create a setup that generate some kind Particle Advection, 3D Vector Field and formula that generates swirl, and then tracing it.
