### ISSUE TITLE
Sverchok Text HUD to display LIST OF VALUES?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1790]
![prtscr capture_66](https://user-images.githubusercontent.com/3952687/30837978-15defd26-a2ac-11e7-8deb-12d7e696e05d.png)
![prtscr capture_67](https://user-images.githubusercontent.com/3952687/30837979-15df6220-a2ac-11e7-97cc-d99c73bc859b.png)

[sv_HUD_004_2017_09_26_01_16.zip](https://github.com/nortikin/sverchok/files/1331383/sv_HUD_004_2017_09_26_01_16.zip)

I tried all kind of ways, but cannot seem to be able to display LIST as HUD?

**Comment by Kosvor2** [comment]
You mean like this:

![text_join1234](https://user-images.githubusercontent.com/22656834/30841101-2210c1b4-a294-11e7-90c5-78fe1df7da56.png)

**Comment by enzyme69** [comment]
Thanks again @Kosvor2 !! Will append this to my study~
