### ISSUE TITLE
Sverchok as Modifier Stack

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1792]
Modifier Node proposal:
https://wiki.blender.org/index.php/User:Lucarood/Modifier_Nodes/Proposal

Sverchok is probably already working that way, although I mentioned the fact that with BMesh Output, often it reshuffle the Blender Modifier stacking.

Just for future consideration.

**Comment by zeffii** [comment]
> BMesh Output, often it reshuffle the Blender Modifier stacking.

modifier stack is never touched. but Skinmodifier (if you add it yourself to an object generated by the BMesh node) will become invalidated. Just to be clear here, in case someone else reads this and finds your statement puzzling.
