### ISSUE TITLE
SV Pixel Averaging and found weird bug

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1794]
I am trying to understand Pixel Color Averaging, similar to Photoshop:
https://superuser.com/questions/1221820/pick-color-from-a-pixel-in-photoshop-cc-2017

I don't think Blender has this and I wanted to create one. Trying to imagine pixel as vector first.

So, I am digging old example of SV Image Pixel Processing...  But soon I found something strange with color order, I am using just 4 x 4 grid points and supposedly the color matches my image, but it does not, so weird I wonder why:
![prtscr capture](https://user-images.githubusercontent.com/3952687/30963505-ff41695a-a490-11e7-8e79-20318b37fc4e.png)

I check 16 rgba colors list and matching it with index and vector list, and all seems correct. I think I am going mad.

[pixel_sampling_averaging_002_2017_09_28_11_06.zip](https://github.com/nortikin/sverchok/files/1340590/pixel_sampling_averaging_002_2017_09_28_11_06.zip)

**Comment by enzyme69** [comment]
Oh... objects in actually reshuffle and sorting the object ... @_@ that's the only explanation.

**Comment by enzyme69** [comment]
It's become a sorting problem, it's weird, there must be a better way...
![prtscr capture_2](https://user-images.githubusercontent.com/3952687/30964070-309541dc-a493-11e7-8d31-328481e13657.png)

[pixel_sampling_averaging_003_2017_09_28_11_22.zip](https://github.com/nortikin/sverchok/files/1340620/pixel_sampling_averaging_003_2017_09_28_11_22.zip)

Anyhow, now back to "averaging problem"...

**Comment by enzyme69** [comment]
[pixel_sampling_averaging_006_2017_09_28_11_34.zip](https://github.com/nortikin/sverchok/files/1340654/pixel_sampling_averaging_006_2017_09_28_11_34.zip)

Not sure if Average is the Mean of Numpy, but:
![prtscr capture_4](https://user-images.githubusercontent.com/3952687/30964483-e0e72c0c-a494-11e7-8d19-5f5a98093bcc.png)

Ideally, if we have an image in 3D and we want to find a color average based on position of the point on the surface, looking at the point in UV, finding nearest color, we should be able to do it.

--- to be continued ---

**Comment by Kosvor2** [comment]
There is "ObjectID Sort" node. Just type "name" into text box, and it will sort objects by name.
