### ISSUE TITLE
Array of Pixels RGBA

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1795]
<img width="1024" alt="2e34e4ef-84f2-49ab-a67a-216dd734111e" src="https://user-images.githubusercontent.com/3952687/31041981-99f84648-a5e1-11e7-94a6-219b843aa185.png">

I am tinkering with this pixels art in Sverchok and would like to imagine it as 2d or even 3d grid, but still very much confused.

So, we can already grab pixels as LIST. I can slice it into RGBA. So we have list range of rgba that correspond to grid of pixels XY of the image.

Question is: would be the best, fastest method to say if we like to supply coordinate (1,2), (4,5), etc so that we get back the pixel rgba? Dictionary? Or am I overthinking such simple question?

I imagine if user can supply some kind of (x,y) coordinates, and then from that point, they can find nearest coordinates, then find average pixel color.

Maybe this is kind of UV color sampling node, I am thinking since years ago.

**Comment by Kosvor2** [comment]
Better to use numpy for that:

![numpy_pixels123](https://user-images.githubusercontent.com/22656834/31042714-9a2bc37a-a5c7-11e7-8433-497378cb86b9.png)

**Comment by enzyme69** [comment]
Thank you so much again Kosvor! Made my day~ Numpy it is!

At first, I was thinking to use SV "Selection" node.

When points grid laid out in 3D space, and then users can select points which correspond to "Data" it becomes clear. Although, not sure it is the most efficient.
