### ISSUE TITLE
Software to capture live-noding sessions

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1796]
This is a bit off SV topic but.. what software do you guys use to capture a video session (SV live-noding or any blender recording for that matter) ? 

@enzyme69 has probably a good answer, but he’s not answering his youtube video comments which is why I’m asking again here 😛 

I’m personally using blender with macs / OS X.

**Comment by zeffii** [comment]
OBS software i think is cross platform? really good .    https://obsproject.com/

**Comment by zeffii** [comment]
but i use GifCam for smaller area gifs.

**Comment by enzyme69** [comment]
I am using Camtasia Recorder on Windows, while on Mac, Quicktime Capture
works fine.

I must have missed some comments, will check cheers!
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
I use LiceCap for GIF.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by DolphinDream** [comment]
I also use LiceCap on mac for GIF.

**Comment by zeffii** [comment]
you can still talk with the issue closed
