### ISSUE TITLE
Node to set object property

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1798]
Is there a node that lets you set an object’s property? Like select the camera object and set its camera focal length for instance ?

**Comment by Kosvor2** [comment]
Yes, there already a bunch of them. Thought they require from users to know Blender python api to use them effectively.

**Comment by DolphinDream** [comment]
Hm... well, maybe we are overdue for having a Set Object Properties node.. where you can select an object.. and then select what property you want o modify (no copy and past RNA paths and stuff), just drop down menus, etc. That would be sweeeet ;)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/31114670-79655d40-a81f-11e7-9938-9c6c483f722a.png)

The BPY nodes are almost all in place...

A while back i proposed a modification to the Object ID Set node to generate the dropdown (properties to select from) automatically, depending on the objects in the input. 

Tho at this point i would go for a new node with the added picking feature, and it can coexist with the existing version.. ( i like to type the property rather than select it)

**Comment by zeffii** [comment]
also this already works
![image](https://user-images.githubusercontent.com/619340/31114926-9148fdda-a820-11e7-925b-ab0374b4483c.png)

**Comment by zeffii** [comment]
with minimal extra code.. ( so..still lacking most of the needed error checking )
![image](https://user-images.githubusercontent.com/619340/31120958-a1fda494-a836-11e7-87b9-98534696aa65.png)

That enum might be overkill. If we hand picked the most common props per object type, we'd get a shorter list, but then we'd lose the completeness. perhaps a second property in the extended parameters to say "pick from common properties" or "take a chance and show all props".

https://github.com/nortikin/sverchok/pull/1799

**Comment by zeffii** [comment]
this modification is by no means a stable implementation

**Comment by enzyme69** [comment]
I kind of like how Sverchok digs into object properties like this. The
library big view is also interesting.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
a selector between automatic property listing , and manual.

![ttttgif](https://user-images.githubusercontent.com/619340/31219481-bcf49040-a9bd-11e7-9353-8dd017b4b953.gif)

**Comment by DolphinDream** [comment]
Some thoughts on this node...

1. Have both the OBJECT and DATA parameters available in the drop downs lists. 
I implemented a variation of this node and added an OBJECT/DATA mode to allow the user to select between what parameters to list. Alternatively there could be just one list and have the OBJECT parameters listed in one column and the DATA in another column of the drop down list (if possible, similar to the interpolation type in the animation UI : https://blender.stackexchange.com/questions/91639/customize-drop-down-ui-with-multiple-column)

2. As zeffi suggested, we can filter out and show only the most common properties. This filtering can be done per object type. For mesh object some useful parameters are location, rotation_euler, scale etc. No need to display all 50 different properties to select from.

3. I would like to have a way to add multiple properties as input sockets when I select them from the dropdown or enter them manually. Perpahs a + (add) button could allow to add them and an x (remove) button next to the already created sockets could remove them.

Alternatively, adding new properties as sockets from the list of all available properties, can be done via Property Panel where all properties are displayed in scrollable list and allow the user to check a checkbox to show or hide a given property in the node itself as an input/output socket. I'm thinking of this as something similar to the monad inputs/outputs lists in the Property Panel where you can add, remove, reorder input/output sockets.

Note: having multiple sockets added for various properties could be problematic with multiple objects of different types since, for example, the camera and the mesh objects do not share the "lens" property. However, it may still be ok to have properties listed in the input socket list that do not apply to all objects and have the node simply ignore the inputs that do not apply to a given object.

Basically you can have a node showing:

* objects (fixed input socket)

# and added sockets:

* lens (data.lens) - for camera
* location (location) - for any object
* bevel (data.bevel_depth) - for curve object

Providing a camera, a mesh and a curve object list to the node, the node will modify these objects accordingly using the properties that are applicable to those objects.. e.g. location to all objects, lens only to the camera and bevel only to the curve object.

4. This node could be both a set and a get node. You can select to create an input socket, an output socket or both for any given property. Creating just the input socket for a property will just modify that property (set), creating the output socket will just spit out its value (get).. and creating both sockets would set and get (propagate the set value) of that property.

![sv-getsetproperty-01](https://user-images.githubusercontent.com/2083719/31256445-9f85516e-aa00-11e7-896a-7fda908111e0.jpg)

**Comment by enzyme69** [comment]
Or maybe implementation similar to AN where properties are listed on the
panel and can be toggled as needed.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
Feel free to do such a node from scratch, the current node is pretty advanced in its own right.

**Comment by zeffii** [comment]
btw.. the node i suggested above has a Object/Data switch in Auto mode, in the form of a toggle.

passing mixed lists seems a little akward, trying to solve a problem that doesn't really make sense to have. I get the concept of being able to use the one node and let it handle good / bad input, but any scenario that I might use that would be better solved by first parenting objects and applying changes to the parent rather than children. ( but you might have other ideas..)

**Comment by k1ff** [comment]
Hi guys,

I can't seem to set property of visibility (objs["name_of_objects"].hide)
I enter that into the Set Property node, it doesn't error, so it's understanding the code, but it doesn't create a property. Would it possible to get a checkbox for when the property defined is a boolean? That way we could toggle the property on and off.

If there is already a way to do this, I would love to know. Thanks!
