### ISSUE TITLE
2.79 problem can't activate Sverchok

### ISSUE THREAD

**Issue by dza6549** [nortikin/sverchok#1800]
Hi

trying to install on 2.79. Win10

Used latest Sverchok release https://github.com/nortikin/sverchok/releases/tag/0.5.9.6.2
install from file zip, changed plugin folder name to sverchok, click activate button
following error name nodes is not defined

![image](https://user-images.githubusercontent.com/27390320/31154990-bbf48d02-a8f6-11e7-858b-43599957fdb2.png)

Happy to provide further information.

Thanks

**Comment by zeffii** [comment]
1. close / restart blender
2. re-enable blender from the add-ons panel, but allow for a couple of seconds to pass (it's a big program to initialize the first time)

**Comment by zeffii** [comment]
1. close / restart blender
2. re-enable Sverchok from the add-ons panel, but allow for a couple of seconds to pass (it's a big program to initialize the first time)

**Comment by dza6549** [comment]
Yes. That sorted it.
Thanks

**Comment by zeffii** [comment]
enjoy!
