### ISSUE TITLE
Update node tree on scene object’s property change

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1801]
It would be cool if SV could update the node tree when an object’s property changes. Currently if I have an object imported into the SV node tree to read, for instance, the position of an object in the scene, in order for this position to be updated in the node tree whenever the object location changes in the scene is only possible if the playback is running.

This is kind of a hack for now and it is sometime slow (depending on the scene complexity) and uses CPU cycles unnecessarily. A better approach would be to have SV somehow detect object’s property changes and update this property accordingly in the tree. Of course the update of the node tree would only be necessary if the property of that object is used in the tree.

**Comment by zeffii** [comment]
> this position to be updated in the node tree whenever the object location changes in the scene is only possible if the playback is running

not true. 
- there's a live update modal operator ( https://github.com/nortikin/sverchok/issues/1028 , needs to be enabled in sverchok-preferences "Enable live Object In" ) , can you be more specific about which nodes are involved in this tree.
- if the movement is just incidental then you can press left/right arrow keys in nodeview to move the framenumber and this will trigger an update too.
- i sometimes bind ctrl+enter to the nodetree update operator.

The event handler system exposed to Python via bpy is not very finegrained and using scene's handlers for post and pre_scene update is considered a necessary hack. Those handlers are not going to survive in 2.8 (they've already been removed), so i'll resist modifying that until they figure out what direction to take.

**Comment by DolphinDream** [comment]
> there's a live update modal operator ( #1028 (comment) , needs to be enabled in sverchok-preferences "Enable live Object In" ) ,

Actually this doesn’t seem to work with object location.

![sv-liveobject-demo1](https://user-images.githubusercontent.com/2083719/31309745-4e1ca052-ab59-11e7-87a5-a7b4a381c4f5.gif)

**Comment by zeffii** [comment]
yeah, it doesn't trigger an update in `Object ID Out MK2` use `Object in MK3`

**Comment by zeffii** [comment]
see

https://github.com/nortikin/sverchok/blob/28022409909413126ae61d3b8a02c4e381360624/ui/sv_panels.py#L76-L92

"""python
if n.bl_idname in objects_nodes_set:
"""
and objects_nodes_set doesn't include the bl_idname of Objects ID Out MK2 , hence no updating. (don't add a pull request to add that node to the list..  branch it locally and add it yourself and if it solves your problem then push to master )

**Comment by DolphinDream** [comment]
huh.. is there a reason why searching for “object in” does not list the Object in MK3 btw?

**Comment by DolphinDream** [comment]
@zeffii I tried “Objects in MK3” and unfortunately it doesn’t update either.

**Comment by zeffii** [comment]
you need to switch it on, not just enable it.   https://github.com/nortikin/sverchok/issues/1028#issuecomment-267290657

**Comment by zeffii** [comment]
enable Live Object In , just adds the button for the operator onto the sidepanel that SV gets in 3dview

**Comment by DolphinDream** [comment]
Wow.. that is one hard to find setting. I didn’t know that setting even exists there on that 3dview tool panel. :) Shouldn’t this setting be added to the Property Panel in the node editor as well ?

**Comment by DolphinDream** [comment]
Also, enabling live update makes my blender CPU usage go from 4% to 36% .. any reason why so much consumption for monitoring the update of one object ?

**Comment by zeffii** [comment]
> any reason why so much consumption for monitoring the update of one object ?

it executes quite a bit more than just listen and respond to a single object, take some time to read the code. Unfortunately this is a general operator, meaning we sacrifice processing time for convenience/ease of use.

You could write your own update handler script, and taylor/customize it to handle specific scenarios. (see the bpy docs for the `scene_update_pre` / post handlers -- has a few examples ). You'll quickly notice that dedicated scripts are sometimes the way to go (it's also tricky to implement dedicated scripts into generalized operators...)

**Comment by zeffii** [comment]
also.. the modal operator is configured to retrigger based on an interval.. ( 0,1 second or something? ) whereas a `scene_update_pre/post` may trigger only after a datablock changes.

**Comment by zeffii** [comment]
> Shouldn’t this setting be added to the Property Panel in the node editor as well ?

The jury is out on that because if you are editing using 3dview then you can already conveniently open the T panel and start the modal operator. I chose on purpose to not put that button in multiple places, and also the fact that it's so obscure is not by chance -- it's implementation relies on a method I didn't think was a good idea but we felt was OK for occasional use.

Definitely room for improvement there, and also a good opportunity to make a list of features we'd like to update handlers to be able to do/trigger on in 2.8

**Comment by zeffii** [comment]
maybe look at how to attach a driver to something like an object's location.

**Comment by DolphinDream** [comment]
makes sense. 

Drivers? One reason why I started to be interested in noding is to move away from drivers since many times they prove not to work for me (depgraph problem). 

CPU consumption doesn’t seem that big compared to playing animation. Play animation at 25fps CPU consumption is 70% by itself, and live update by itself is 36%... I haven’t tried more complex scenes though.

**Comment by zeffii** [comment]
event handlers are a big topic with little documentation (and that's only partially because there's little to say about them..)

https://docs.blender.org/api/blender_python_api_2_76_2/bpy.app.handlers.html

```python
import bpy


def my_handler(scene):
    print("Scene Update Post")
    # nodetree.process_from_node(node)

bpy.app.handlers.scene_update_post.append(my_handler)
# bpy.app.handlers.scene_update_post.remove(my_handler)  <-- must remove handler reference
```

https://blender.stackexchange.com/questions/13721/handler-existence-checking
(always good to give the handler a more descriptive name..)
and https://blender.stackexchange.com/a/53895/47

and i like this one:
https://blender.stackexchange.com/a/44381/47

The problem is indeed the cyclic circumstance in which you may find yourself. updating the node tree can in turn also trigger a scene_update_post if you pipe to BMeshViewer.

**Comment by zeffii** [comment]
maybe it makes sense to have some kind of custom handler manager, in which you could 
   - for specific scenarios force the order of updates.
   - state what to do in the event of an update, and to which nodes

maybe the blender update handlers will be made more granular in future ( i suspect they will )
