### ISSUE TITLE
Rounding Edges, Bevel failed

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1803]
I am thinking to make edges with rounded corner, but seems to fail when I use Bevel node. Is there alternative? 

The idea is to make Pipe.

[spiral_square_resampled_004_2017_10_06_00_23.zip](https://github.com/nortikin/sverchok/files/1361220/spiral_square_resampled_004_2017_10_06_00_23.zip)

**Comment by enzyme69** [comment]
I tried Subdivide and smooth, but getting funny wobbly lines.

**Comment by Durman** [comment]
Something like this?
[spiral_square_resampled_004.zip](https://github.com/nortikin/sverchok/files/1362120/spiral_square_resampled_004.zip)

**Comment by enzyme69** [comment]
That is correct! I will study this, wonder why didn't work on mine. Thanks @Durman
