### ISSUE TITLE
Cyclic state entered when piping BMeshViewer output into Object ID out MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1804]
[ray_thing_002_2017_10_06_03_09.zip](https://github.com/nortikin/sverchok/files/1361451/ray_thing_002_2017_10_06_03_09.zip)

Try opening the Blend, scrub the timeline to update the node tree and ... crash.

The setup is basically like this:
- I am using Raycast node, it does not work with Text Object.
- I am meshing the Text Object as BMesh Viewer, then I source that using Raycast. 
- Updating will crash Blender.

**Comment by zeffii** [comment]
You can import text.geometry with obj-in,  should let you raycast

**Comment by zeffii** [comment]
it might be appropriate to add a verts+faces (input) socket version of the raycaster. I thought we already had one of those..

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/31316590-aafea0ea-ac30-11e7-9124-4727cd5eb56b.png)
a new Raycaster node

https://github.com/nortikin/sverchok/pull/1806

update and find it in analyzers->raycaster

**Comment by zeffii** [comment]
This won't fix the behaviour you experience while piping `obj->bmeshviewer->obj_ID_raycast`, but that's not something that can be fixed in any of those nodes mentioned anyway (it is a system problem...)

**Comment by zeffii** [comment]
because this is related to the Object ID raycast node specifically i'll respond here
```python
# old
for OB in obj:
    if sm1:
        obm = OB.matrix_local.inverted()
        outfin.append([OB.ray_cast(obm*Vector(i), obm*Vector(i2)) for i,i2 in zip(st,en)])
    else:
        outfin.append([OB.ray_cast(i,i2) for i,i2 in zip(st,en)])


# new


def OB_to_BVH(OB):
    OB_NEW = lambda: None
    OB_NEW.matrix_local = OB.matrix_local
    BVH = BVHTree.FromObject(OB, bpy.context.scene, deform=True, render=False, cage=False, epsilon=0.0)
    OB_NEW.ray_cast = BVH.ray_cast
    return OB_NEW


for OB in obj:
    if OB.type == 'FONT':
        OB = OB_to_BVH(OB)

    if sm1:
        obm = OB.matrix_local.inverted()
        outfin.append([OB.ray_cast(obm*Vector(i), obm*Vector(i2)) for i,i2 in zip(st,en)])
    else:
        outfin.append([OB.ray_cast(i,i2) for i,i2 in zip(st,en)])

```

I think should work.. or something like it.

**Comment by zeffii** [comment]
well, that just crashes Blender..

maybe..
```python
class FakeObj(object):

    def __init__(self, OB):
        self.matrix_local = OB.matrix_local
        
        mesh_settings = (bpy.context.scene, False, 'PREVIEW')
        data = OB.to_mesh(*mesh_settings)

        vertices = [vert.co[:] for vert in data.vertices] 
        polygons = [poly.vertices[:] for poly in data.polygons]
        self.BVH = BVHTree.FromPolygons(vertices, polygons)
        bpy.data.meshes.remove(data)


    def ray_cast(self, a, b):
        return self.BVH.ray_cast(a, b)

...

        for OB in obj:
            if OB.type == 'FONT':
                NOB = FakeObj(OB)
            else:
                NOB = OB

            print(OB, NOB)

            if sm1:
                obm = NOB.matrix_local.inverted()
                outfin.append([NOB.ray_cast(obm*Vector(i), obm*Vector(i2)) for i,i2 in zip(st,en)])
            else:
                outfin.append([NOB.ray_cast(i,i2) for i,i2 in zip(st,en)])


```

**Comment by zeffii** [comment]
tho I think this will need to be an MK3 so i can remove the `.use_prop` occurences ..

**Comment by zeffii** [comment]
branch https://github.com/nortikin/sverchok/pull/1811
