### ISSUE TITLE
BMeshViewer to generate UV and retain between updates when topology is static.

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1809]
I have this dilemma with UV Map when working using Sverchok. I knew this matter will eventually arise.

1) I am generating some kind of random mesh using Sverchok and output it as BMesh. 
2) Once happy with random mesh, I am doing this UV projection and make UV nice.
3) Next step however, I want to be able to animate and modify the mesh, while preserving the UV. In the past, I just use Ctrl + L to transfer UV from mesh with good UV to final 3D object tweaked in Sverchok.

Blender has **DataTransfer Modifier** that actually do transfer UV on the fly, however this failed because whenever Sverchok updates the mesh, the UV disappear. So currently my "hack" is to use Exec Node to do smart_project(), but maybe not the best:

![prtscr capture_34](https://user-images.githubusercontent.com/3952687/31371940-47f45976-addf-11e7-85ae-b6617147547c.png)

Any tips on this? Thanks!

**Comment by zeffii** [comment]
seems to me bpy.ops.uv.smart_project is a UI only operator? does it not take the 3dview viewing angle into account?

**Comment by zeffii** [comment]
remember there's also the N-Panel settings for ViewerBmesh node, one mode may be useful here ( if your geometry is not adding / removing verts per update ) - I think this doesn't invalidate the UV ..but I could be wrong.

**Comment by zeffii** [comment]
if the vert count and  edge/face indices change during animation is is only logical that the UV becomes invalidated by default and will need to be regenerated somehow.

I'm not sure if there's a bpy method to take a Mesh and pass it a Matrix (viewing angle) and get a UV projection.

**Comment by zeffii** [comment]
o i see, smart_project doesn't need view..

[bpy.ops.uv.smart_project](https://docs.blender.org/api/blender_python_api_2_73_release/bpy.ops.uv.html#bpy.ops.uv.smart_project)
```python
uv.smart_project(angle_limit=66.0, island_margin=0.0, user_area_weight=0.0, use_aspect=True)
```

I think that operator only works in ExecNode when you have one object in the scene and it's active.

**Comment by zeffii** [comment]
turns out this operator is coded in [pure python..](https://svn.blender.org/svnroot/bf-blender/trunk/blender/release/scripts/startup/bl_operators/uvcalc_smart_project.py)

**Comment by enzyme69** [comment]
@zeffii Which means it can be easily become Script Node?

**Comment by zeffii** [comment]
easily?  that depends who's coding :)

i didn't read the code carefully, but it seems with several customizations the function called "main" can be modified and called by something like a SN or a new UVnode. Yes i think that could work.

**Comment by zeffii** [comment]
or maybe as part of BMeshViewer ...but i'd decide that only after it's obvious that the proposal works.

**Comment by zeffii** [comment]
btw @enzyme69   , BMeshViewer doesn't output BMesh, but simply Mesh. I think it's better if you avoid this confusion by using the term Mesh or Object for the output of BMeshViewer.

BMeshViewer is rather unfortunately named according to the internal procedures I used (bmesh_from_pydata) rather than the output (Mesh/Object). Not a big deal.. but it won't make sense to the casual reader/googler.

**Comment by Durman** [comment]
Not sure that it is useful.
[Texture_2017_12_16_18_38.zip](https://github.com/nortikin/sverchok/files/1565032/Texture_2017_12_16_18_38.zip)

![2017-12-16_22-40-48](https://user-images.githubusercontent.com/28003269/34073391-4b4c1e58-e2b2-11e7-84e2-c4b4db0f3b0e.png)

**Comment by nortikin** [comment]
we need example in templates for texturing and generating texture at the same time

**Comment by enzyme69** [comment]
Maybe @Durman solution is kind of working I guess we can close this until the next one. Maintaining UV that would work with procedurally generated objects is tricky, I guess. 

Yes @nortikin we need template texturing and generating texture.

@nortikin your "UV" layout actually is kind of nice. It is a bridge for 3D tiling and "tissue".

**Comment by enzyme69** [comment]
My some kind of proposal is to "project" back the UV from 3D as actual UV data.

**Comment by enzyme69** [comment]
I always think UVTextures In and Out would be cool. It's just a matter of time I guess.

![screen shot 2017-12-17 at 12 17 27](https://user-images.githubusercontent.com/3952687/34075742-4dc99c2e-e324-11e7-9e19-7f355e34a6f3.png)

**Comment by enzyme69** [comment]
I also always wanted to animate "textures", like if we have animated texture tiles, and if we can just animate that square easily across UV...

**Comment by enzyme69** [comment]
@Durman Somewhat this adds calculation time by 100 times.

[bmesh_box_with_uv_002_2017_12_17_01_33.zip](https://github.com/nortikin/sverchok/files/1565235/bmesh_box_with_uv_002_2017_12_17_01_33.zip)

One thing: we have Cycles, really we don't need too many fancy UV Modifier of somesort.. just UV that sticks on BMesh Viewer.

**Comment by Durman** [comment]
@enzyme69 
In this case all is working fast but you cannot change object after creating UV Mapping. If we want to create UV mapping before changing objects we have to keep data about mapping in Sverchok. It can be changed with mesh together and be set to object afterall.

![2017-12-17_08-15-35](https://user-images.githubusercontent.com/28003269/34076543-fa4b63ea-e303-11e7-82cb-f0adcce97231.png)

**Comment by enzyme69** [comment]
Ok I see... I remember at some point looking at some bpy python code that deals with UV, there is this loop etc, that I think feels similar to Vertex Color.

I guess, this is not priority but plausible.

Blender should have UV Modifier that can be "hacked" already I am sure about this.

**Comment by Durman** [comment]
I was seeing this video (https://youtu.be/cSiKSrQ9eOI?t=2199) when I suddenly recognized how it is possible to manage with UV mapping by Sverchok.))) In the movie was information how to make randomized UV mapping. In my case I created UV of one polygon of the cube.

![2018-01-27_23-29-29](https://user-images.githubusercontent.com/28003269/35475559-0fb1cc52-03ba-11e8-8398-9979f234fbcf.png)
[UV maping_2018_01_27_19_30.gz](https://github.com/nortikin/sverchok/files/1670451/UV.maping_2018_01_27_19_30.gz)

**Comment by enzyme69** [comment]
@Durman Hey that's cool! I remember a while back ago I played with this a bit, kind of like finding a way to randomize UV Texture via Attribute node. There is a limitation of min and max but manage to randomize UV on an object. 

I am looking at your blend now... so is it possible to get all 6 side of cube to have a nice UV? I have to spend a bit of time watching the video... thanks for pointing this out!

**Comment by Durman** [comment]
@enzyme69 Yes, but each faces should be single object so it's not cool :/
[UV maping_2018_01_28_03_59.gz](https://github.com/nortikin/sverchok/files/1670763/UV.maping_2018_01_28_03_59.gz)
![2018-01-28_07-59-34](https://user-images.githubusercontent.com/28003269/35478843-93f7aec2-0401-11e8-94ab-fdbdb0ea916a.png)

**Comment by Durman** [comment]
![texturise](https://user-images.githubusercontent.com/28003269/39960001-8747c136-562b-11e8-9491-8aefa77b2084.gif)

**Comment by Durman** [comment]
It is possible to create UV map but only with equal topology both mesh and uv map.

![2018-05-13_20-11-32](https://user-images.githubusercontent.com/28003269/39969258-3093a46c-56ea-11e8-83e4-82b45737f61b.png)

**Comment by Durman** [comment]
The copy UV map from one object to another with equal topology. 

So we can create object via Sverchok, copy it in scene and make unwrap for duplicate by hand. After that, we can copy UV map on the object in Sverchok and use.

![2018-05-14_13-26-32](https://user-images.githubusercontent.com/28003269/39989640-886bee7e-577b-11e8-9087-51930bd3ceca.png)

**Comment by Durman** [comment]
I will open this issue for a while.)) 
I am searching approach for mapping in Sverchok. And results look interesting. It is not obvious how to do it because blender create UV from loops which has not representation in Sverchok.

![maping](https://user-images.githubusercontent.com/28003269/40037932-c496beec-5820-11e8-8432-4b2a45f15ef8.gif)
![2018-05-15_09-14-17](https://user-images.githubusercontent.com/28003269/40037933-c88161ec-5820-11e8-97a8-0f92dd71539d.png)

**Comment by Durman** [comment]
Auto ttexturing roads.

![2018-05-15_14-27-07](https://user-images.githubusercontent.com/28003269/40051549-378f489e-584c-11e8-83fc-95d543b09185.png)
