### ISSUE TITLE
random points on faces (snlite)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1810]
no serious error checking implemented here..

```python
"""
in verts_list v
in faces_list s
in num_points s d=20 n=2
out verts_out v
"""

import bpy_extras
from bpy_extras import mesh_utils

for verts, faces in zip(verts_list, faces_list):

    mesh = []
    try:
        mesh = bpy.data.meshes.new(name="xxxxaaaa")
        mesh.from_pydata(verts, [], faces)
        tessfaces = mesh.polygons
        new_verts = mesh_utils.face_random_points(num_points, tessfaces)
        verts_out.append([v[:] for v in new_verts])
        
        if "xxxxaaaa" in bpy.data.meshes:
            bpy.data.meshes.remove(mesh)

    except Exception as err:
        print('nope', err)

```

![image](https://user-images.githubusercontent.com/619340/31381894-2ae5f39a-adb6-11e7-8785-a0d33249a7ef.png)

**Comment by Durman** [comment]
Better than random verts on polygons script.
![2017-10-10_16-23-59](https://user-images.githubusercontent.com/28003269/31386366-9d68f6a8-add7-11e7-9a7f-ac2a768076f8.png)

**Comment by zeffii** [comment]
oh.. it seems that the `face_random_points` expects triangles only?.. or quads.. but not ngons?

**Comment by zeffii** [comment]
turns out `face_random_points` is also written in python

##### scripts/modules/bpy_extras/mesh_utils | face_random_points
```python
def face_random_points(num_points, tessfaces):
    """
    Generates a list of random points over mesh tessfaces.

    :arg num_points: the number of random points to generate on each face.
    :type int:
    :arg tessfaces: list of the faces to generate points on.
    :type tessfaces: :class:`bpy.types.MeshTessFace`, sequence
    :return: list of random points over all faces.
    :rtype: list
    """

    from random import random
    from mathutils.geometry import area_tri

    # Split all quads into 2 tris, tris remain unchanged
    tri_faces = []
    for f in tessfaces:
        tris = []
        verts = f.id_data.vertices
        fv = f.vertices[:]
        tris.append((verts[fv[0]].co,
                     verts[fv[1]].co,
                     verts[fv[2]].co,
                     ))
        if len(fv) == 4:
            tris.append((verts[fv[0]].co,
                         verts[fv[3]].co,
                         verts[fv[2]].co,
                         ))
        tri_faces.append(tris)

    # For each face, generate the required number of random points
    sampled_points = [None] * (num_points * len(tessfaces))
    for i, tf in enumerate(tri_faces):
        for k in range(num_points):
            # If this is a quad, we need to weight its 2 tris by their area
            if len(tf) != 1:
                area1 = area_tri(*tf[0])
                area2 = area_tri(*tf[1])
                area_tot = area1 + area2

                area1 = area1 / area_tot
                area2 = area2 / area_tot

                vecs = tf[0 if (random() < area1) else 1]
            else:
                vecs = tf[0]

            u1 = random()
            u2 = random()
            u_tot = u1 + u2

            if u_tot > 1:
                u1 = 1.0 - u1
                u2 = 1.0 - u2

            side1 = vecs[1] - vecs[0]
            side2 = vecs[2] - vecs[0]

            p = vecs[0] + u1 * side1 + u2 * side2

            sampled_points[num_points * i + k] = p

    return sampled_points
```
we could make a "fake" tessfaces object that automatically converts ngons into new tris,

I'm not sure but I think we could even make the `num_points` be relative to the surface area of each triangle. else smaller tris will get denser point collections..

**Comment by zeffii** [comment]
this works for ngons, but to get a nicer spread the `face_random_points` really does need a slight rewrite
```python
"""
in verts_list v
in faces_list s
in num_points s d=20 n=2
out verts_out v
"""

import bpy_extras
import mathutils
from mathutils import Vector
from bpy_extras import mesh_utils

for verts, faces in zip(verts_list, faces_list):

    mesh = []
    tessellated_faces = []
    add_face = tessellated_faces.append
    add_faces = tessellated_faces.extend
    try:
        for f in faces:
            if len(f) in {3, 4}:
                add_face(f)
            else:
                # Takes a list of polylines (each point a vector) and returns the point indices for a polyline filled with triangles.
                v = [Vector(verts[i]) for i in f]
                tess_poly = mathutils.geometry.tessellate_polygon([v])
                print(tess_poly)
                for tess in tess_poly:
                    add_face([f[i] for i in tess])

        mesh = bpy.data.meshes.new(name="xxxxaaaa")
        mesh.from_pydata(verts, [], tessellated_faces)

        tessfaces = mesh.polygons
        new_verts = mesh_utils.face_random_points(num_points, tessfaces)
        verts_out.append([v[:] for v in new_verts])
        
        if "xxxxaaaa" in bpy.data.meshes:
            bpy.data.meshes.remove(mesh)

    except Exception as err:
        print('nope', err)
```
![image](https://user-images.githubusercontent.com/619340/31454369-857d1e5a-aeb5-11e7-882c-0f5de9c13b33.png)

thanks for your input @Durman

**Comment by Durman** [comment]
I looked for this function before. Now it exists, it's great.)) @zeffii 
![points on mesh](https://user-images.githubusercontent.com/28003269/31481476-a76c00a6-af34-11e7-8658-1a14d3499162.gif)

**Comment by zeffii** [comment]
@Durman maybe you'd like to make an alternative `def face_random_points(num_points, tessfaces)`  that operates on num_points per surface area, rather than per Tri/Quad :)

**Comment by Durman** [comment]
@zeffii  I afraid that my knowledge about Python and Blender API can not allow me to do this work effectively yet. I began one interesting free course about Python but can not to finish it because almost all my free time was eaten by English language lessons.)) At first I want improve my English and then may be...) 
I suppose it is necessary to look for in Particle system direction.

**Comment by zeffii** [comment]
English lessons? excellent!   btw I am already rewriting `face_random_points` might stick it in a node.

**Comment by zeffii** [comment]
partially (doesn't work yet)
```python
def face_random_points(num_points, tessfaces):

    from random import random
    import mathutils
    from mathutils.geometry import area_tri

    # Split all quads into 2 tris, tris remain unchanged
    tri_faces = []
    for f in tessfaces:
        tris = []
        verts = f.id_data.vertices
        fv = f.vertices[:]
        if len(fv) == 3:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
        elif len(fv) == 4:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
            tris.append((verts[fv[0]].co, verts[fv[3]].co, verts[fv[2]].co))
        else:
            tris.extend([[fv[i] for i in tess] for tess in mathutils.geometry.tessellate_polygon([fv])])

        tri_faces.append(tris)

    # For each face, generate the required number of random points
    sampled_points = [None] * (num_points * len(tessfaces))
    for i, tf in enumerate(tri_faces):
        for k in range(num_points):
            # If this is a quad, we need to weight its 2 tris by their area
            if len(tf) != 1:

                # this still needs to be made ngon agnostic #
                area1 = area_tri(*tf[0])                    #
                area2 = area_tri(*tf[1])                    #
                area_tot = area1 + area2                    #
                                                            #   all of this
                area1 = area1 / area_tot                    #
                area2 = area2 / area_tot                    #
                                                            #
                vecs = tf[0 if (random() < area1) else 1]   #
            else:
                vecs = tf[0]

            u1 = random()
            u2 = random()
            u_tot = u1 + u2

            if u_tot > 1:
                u1 = 1.0 - u1
                u2 = 1.0 - u2

            side1 = vecs[1] - vecs[0]
            side2 = vecs[2] - vecs[0]

            p = vecs[0] + u1 * side1 + u2 * side2

            sampled_points[num_points * i + k] = p

    return sampled_points
```

**Comment by nortikin** [comment]
lets vectorize numpoints

**Comment by nortikin** [comment]
'''python
def face_random_points_ngons(num_points, tessfaces):

    from random import random
    import mathutils
    from mathutils.geometry import area_tri, tessellate_polygon

    # Split all quads into 2 tris, tris remain unchanged
    tri_faces = []
    for f in tessfaces:
        tris = []
        verts = f.id_data.vertices
        fv = f.vertices[:]

        if len(fv) == 3:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
        elif len(fv) == 4:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
            tris.append((verts[fv[0]].co, verts[fv[3]].co, verts[fv[2]].co))
        else:
            fvngon = [v.co for v in verts]
            tris.extend([[fvngon[i] for i in tess] for tess in tessellate_polygon([fvngon])])

        tri_faces.append(tris)

    # For each face, generate the required number of random points
    sampled_points = [None] * (num_points * len(tessfaces))
    for i, tf in enumerate(tri_faces):
        for k in range(num_points):
            # If this is a quad, we need to weight its 2 tris by their area
            if len(tf) == 2:

                area1 = area_tri(*tf[0])
                area2 = area_tri(*tf[1])
                area_tot = area1 + area2
                area1 = area1 / area_tot
                area2 = area2 / area_tot
                vecs = tf[0 if (random() < area1) else 1]

            elif len(tf) == 1:

                vecs = tf[0]

            else:

                areas = [area_tri(*tface) for tface in tf]
                area_tot = sum(areas)
                areas = [(area / area_tot) for area in areas]

                #  vecs = tf[0 if (random() < area1) else 1]   ???

            u1 = random()
            u2 = random()
            u_tot = u1 + u2

            if u_tot > 1:
                u1 = 1.0 - u1
                u2 = 1.0 - u2

            side1 = vecs[1] - vecs[0]
            side2 = vecs[2] - vecs[0]

            p = vecs[0] + u1 * side1 + u2 * side2

            sampled_points[num_points * i + k] = p

    return sampled_points
'''
