### ISSUE TITLE
Loop Accum in Sverchok?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1812]
[sverchok_monad_iteration_002_2017_10_11_05_09.zip](https://github.com/nortikin/sverchok/files/1374285/sverchok_monad_iteration_002_2017_10_11_05_09.zip)
![screen shot 2017-10-11 at 16 09 43](https://user-images.githubusercontent.com/3952687/31423189-db1ceb2c-ae9e-11e7-96e9-f1e376a235c6.png)
![screen shot 2017-10-11 at 16 09 40](https://user-images.githubusercontent.com/3952687/31423190-db53fbc6-ae9e-11e7-8b5d-6fa086a2c65c.png)
![screen shot 2017-10-11 at 16 09 30](https://user-images.githubusercontent.com/3952687/31423191-db84f4ec-ae9e-11e7-9b1b-0954e48ffd1d.png)

I am trying to Loop Iterate in Sverchok similar to what I am doing in Animation Nodes (random walk)... using Monad.

Is this possible?

PS: In the past I made random walk using Sverchok numpy accum.

**Comment by zeffii** [comment]
be more specific, and show the numpy stuff too

**Comment by enzyme69** [comment]
@zeffii 
Numpy Array version:
gist: fbca483c51e2b7ad4360ad7606478548
![screen shot 2017-10-11 at 18 40 36](https://user-images.githubusercontent.com/3952687/31427654-ba3045f2-aeb3-11e7-9f49-66d1f6e71d80.png)

Trying to loop and reassign last added number into the loop. I thought monad loop does this.

starting vector = xyz

X.times loop do:
   xyz + random vector
end

**Comment by zeffii** [comment]
i think where you're going wrong is that the loop mode monad requires inputs to be identical to outputs. (even if that means just piping the input of one socket directly to the corresponding output)

**Comment by enzyme69** [comment]
[accum_002_2017_10_11_08_11.zip](https://github.com/nortikin/sverchok/files/1374718/accum_002_2017_10_11_08_11.zip)
![Uploading Screen Shot 2017-10-11 at 19.11.35.png…]()
![Uploading Screen Shot 2017-10-11 at 19.11.27.png…]()

**Comment by enzyme69** [comment]
Looking at this:
https://github.com/nortikin/sverchok/issues/933

That's kind of does it, but more like inside scriptnode.

I kind of thing Monad should be able to do this.

**Comment by enzyme69** [comment]
![screen shot 2017-10-11 at 19 37 53](https://user-images.githubusercontent.com/3952687/31430132-b1171858-aebb-11e7-8b7e-957bd18a44b8.png)

**Comment by zeffii** [comment]
i don't know how to help you. my advice is still to spend more time implementing things using python for yourself, it will make noding much easier.

**Comment by enzyme69** [comment]
Got it, maybe this iterative inside monad is not yet implemented. Cheer~

**Comment by enzyme69** [comment]
Apparently..... this kind of doing it.
[sv_cumsum_001_2017_10_11_09_28.zip](https://github.com/nortikin/sverchok/files/1375003/sv_cumsum_001_2017_10_11_09_28.zip)
![screen shot 2017-10-11 at 20 27 29](https://user-images.githubusercontent.com/3952687/31432623-bb9e6626-aec2-11e7-8164-0efee15fcda1.png)
![screen shot 2017-10-11 at 20 27 27](https://user-images.githubusercontent.com/3952687/31432625-bbcd2dee-aec2-11e7-8170-73128af4b100.png)
![screen shot 2017-10-11 at 20 27 22](https://user-images.githubusercontent.com/3952687/31432626-bc24caea-aec2-11e7-8f89-00a56ee8f5b8.png)

**Comment by enzyme69** [comment]
But something strange... not doing the right thing.

![screen shot 2017-10-11 at 20 31 58](https://user-images.githubusercontent.com/3952687/31432809-43e26dd4-aec3-11e7-8672-dcd84a37959b.png)

**Comment by enzyme69** [comment]
[sv_cumsum_002_2017_10_11_09_32.zip](https://github.com/nortikin/sverchok/files/1375025/sv_cumsum_002_2017_10_11_09_32.zip)

**Comment by enzyme69** [comment]
Monad can actually works 🥇 

Simplified to just making a single list to iterate.
[sv_cumsum_003_2017_10_11_09_35.zip](https://github.com/nortikin/sverchok/files/1375038/sv_cumsum_003_2017_10_11_09_35.zip)

![screen shot 2017-10-11 at 20 34 56](https://user-images.githubusercontent.com/3952687/31432971-be0d0c54-aec3-11e7-9281-1d1d03b47392.png)
![screen shot 2017-10-11 at 20 34 52](https://user-images.githubusercontent.com/3952687/31432972-be57fc28-aec3-11e7-9753-bdc125d43663.png)

**Comment by enzyme69** [comment]
When applied to Vector, we sort of get:
- The final number per loop iteration
- List of Vectors
![Uploading Screen Shot 2017-10-
![screen shot 2017-10-11 at 20 41 18](https://user-images.githubusercontent.com/3952687/31433280-91a57542-aec4-11e7-9ab9-f58162b2afb1.png)
11 at 20.41.24.png…]()

However, we don't get the CumSum list... hmmm... oh well.

**Comment by enzyme69** [comment]
@zeffii I am up to here...
[monad_vector_cumsum_005_2017_10_11_10_49.zip](https://github.com/nortikin/sverchok/files/1375263/monad_vector_cumsum_005_2017_10_11_10_49.zip)

Is there a way we can "cache" the result of monad loop, kind of appending each step into one big list showing the iteration steps?

**Comment by enzyme69** [comment]
Otherwise it become like this:
[monad_vector_cumsum_006_2017_10_11_10_52.zip](https://github.com/nortikin/sverchok/files/1375283/monad_vector_cumsum_006_2017_10_11_10_52.zip)

Kind of going around twice:
![screen shot 2017-10-11 at 21 52 43](https://user-images.githubusercontent.com/3952687/31436748-943eca10-aece-11e7-85f9-cbf17cb5944d.png)

Would be nice to have "append" in Monad.

**Comment by zeffii** [comment]
input sockets of monad must be identical to output sockets. i've said this already.

**Comment by zeffii** [comment]
that SN snippet above is essentially a "Vector Accumulate" Node. The vector equivalent of 
```python
A -> 0,1,2,3,4,5,6,7

#  0
#  1 = 0  + 1
#  3 = 1  + 2
#  6 = 3  + 3
# 10 = 6  + 4
# 15 = 10 + 5
# 21 = 15 + 6
# 28 = 21 + 7

B -> 0,1,3,6,10,15,21,28
```

**Comment by zeffii** [comment]
![swaltc](https://user-images.githubusercontent.com/619340/31464047-7cb13598-aed0-11e7-866d-103c00885ddc.PNG)

**Comment by enzyme69** [comment]
@zeffii Thanks man for sharing some brain processing. I thought that Loop Monad can do this "appending" data more easily. Maybe I am skipping one important factor.

This should be simpler...
[0] -> 0
[0,2] -> 2
[0,2,6] -> 8
[0,2,6,3] -> 11

Get appended [0,2,8,11]....
Yeah, I have to code and node. I got a loose screw brain 👍 

I think Monad is more for Fractal or something...
![screen shot 2017-10-12 at 11 31 22](https://user-images.githubusercontent.com/3952687/31473575-25988d08-af41-11e7-9314-164560c2f153.png)

**Comment by enzyme69** [comment]
There must be a simple way to Append in Monad. Must be!

But then again....
![screen shot 2017-10-12 at 11 40 39](https://user-images.githubusercontent.com/3952687/31473764-3eac6638-af42-11e7-9766-9cfe32d2717e.png)

**Comment by Durman** [comment]
May be it will be useful for you. @enzyme69  I made it in beginner of my meeting with python.)) I investigated that Sverchek is bad means for this task. Every new frame all node tree are recalculated. When structure get begin too bigger, frame rate get slow down.
[Image of work](https://plus.google.com/u/0/+%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9%D0%A1%D0%BE%D0%BB%D1%83%D1%8F%D0%BD%D0%BE%D0%B2/posts/BgfF5HDWb7T)
```Python
from random import seed, choice

def sv_main(num=0,s=0):
    
    in_sockets = [['s', 'loops', num],['s','seed', s]]
    
    vert = [[0, 0, 0]] #начальная точка и все последующие точки
    last_vert = vert[:]   #Последняя поставленная точка
    vert_pos = [(1,0,0), (0,1,0), (-1,0,0), (0,-1,0)] #Направление будущих точек
    vert_empty = [] #Возможные будущие точки
    vert_empty_check = [] #Проверенные на дублирование
    seed(s)
    
    i_w = 0
    while i_w < num:
        
        for i in vert_pos:
            x = last_vert[0][0] + i[0]
            y = last_vert[0][1] + i[1]
            z = last_vert[0][2] + i[2]
            vert_empty.append([x,y,z])
        for i2 in vert_empty:
            a = 0
            b = []
            for i3 in vert:
                x2 = i2[0] - i3[0]
                y2 = i2[1] - i3[1]
                z2 = i2[2] - i3[2]
                if max(abs(x2),abs(y2),abs(z2)) == 0: a = 0
                else: a = 1
                b.append(a)
            if min(b) != 0: vert_empty_check.append(i2)
        
        vert_empty_choise = choice(vert_empty_check) #Выбираем следующую точку
        last_vert = [vert_empty_choise[:]] #Обновляем последнюю точку
        vert.append(vert_empty_choise) #Добавляем её в общий список
        i_w += 1
        vert_empty = []
        vert_empty_check = []
    
    #edge = [[0, 1]]
    
    out_sockets = [
        ['v', 'vert', [vert]],
        #['s', 'edge', [edge]],
        #['v', 'test', [vert_empty_chouse]],
    ]
    #ui_operators = [['Update', update]]
    
    return in_sockets, out_sockets, #ui_operators
```

**Comment by zeffii** [comment]
the List Modifier Node has an Accumulating Sum mode, it doesn't understand Vectors.. so you must split them
![image](https://user-images.githubusercontent.com/619340/31498599-b2e948de-af62-11e7-9d8d-07ba7d6251c1.png)

**Comment by enzyme69** [comment]
Thanks @Durman @zeffii 

I am starting to wonder whether we can have "live node" without needing frame updates. 

I am currently also playing with Sonic Pi, which uses Ruby and Super Collider and it can send data using multi thread and its "live loop" is instantly running in queue. I don't know what is exactly happening there.

Probably not Sverchok, maybe I should look into game engine and live node :)

**Comment by enzyme69** [comment]
List Modifier... surprised, I use Sverchok for long time and this is misssed 🥇 

![screen shot 2017-10-13 at 13 39 14](https://user-images.githubusercontent.com/3952687/31527900-f47d9246-b01b-11e7-8924-309d435af2b6.png)

![screen shot 2017-10-13 at 13 39 24](https://user-images.githubusercontent.com/3952687/31527899-f43fcd44-b01b-11e7-95bd-bfb19d2e9b48.png)

**Comment by zeffii** [comment]
> playing with Sonic Pi, which uses Ruby and Super Collider 

Ruby? i can't see any reference to ruby with sonicPI.  But that's off topic .

> wonder whether we can have "live node" without needing frame updates.

do you mean a node that's always listening to some port and can respond by triggering nodetree update downstream. (also slightly off topic for the thread..)

**Comment by enzyme69** [comment]
@zeffii Yes, I think Sonic Pi uses Ruby language. Are you into Ruby?

Yes, some kind of node that is alive and continue to listen and update even when frame is not running. Probably not Blender normal environment, more like BGE and "realtime interative mode"

AN is doing this, but probably different topic :D AN Transform Object is pushing object even when frame is not running --> use a lot of processing though.

Actually AddOSC addon is doing this "live processing" as well. Frame is not running, but it seems to listen to events and OSC coming from Sonic Pi.

**Comment by zeffii** [comment]
at the moment there are only two ways to do this without BGE (that I'm aware of )

- scene.update_handler post/pre:
     - this is triggered easily when adjusting objects
- modal operator ( every n milliseconds check the state.. and do something )  
     - always running, but needs to be started once and stopped when you're done. (AddOsc uses this.. so does Live Object In , also my [b3d_osc_panel](https://github.com/zeffii/b3d_osc_panel/issues/1)

but anyway, you'd need to invest time into your coding foo to appreciate how they work :)

**Comment by Durman** [comment]
My version. Just 7 strings on Python.
https://gist.github.com/ae3cacb8c80a031c8e1b32af759fda8d
![random way](https://user-images.githubusercontent.com/28003269/31810108-983c62ee-b58b-11e7-9a36-59a95d0799b1.gif)

**Comment by zeffii** [comment]
I should really add a method to get the current python lines into clipboard easier :)

```python
>>> nodes = bpy.data.node_groups['NodeTree'].nodes
>>> for l in [d.line for d in nodes['Exec Node Mod'].dynamic_strings]:
...     print(l)
...     
from mathutils import Vector as V
l = []
last_v = V((0,0,0))
for i in V1[0]:
    l.append(last_v[:])
    last_v =last_v + V(i)
append(l)

>>>
