### ISSUE TITLE
Vector attraction

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1816]
It is just some thoughts about this theme.
I thought about vector attraction node it is normal working but have some limitation. At first it have not radius of action, all mesh are attracted by attraction points. In the Second attraction points having different direction of attraction reduce influence each other to the mesh. I have some result with my own script but it does not work perfectly.

![attraction](https://user-images.githubusercontent.com/28003269/31597897-f42585d2-b25b-11e7-9e73-6d352fe7f8a8.gif)

I investigated that all points was moving to attraction point so with this way it is possible to have only concave curve.

![attraction2](https://user-images.githubusercontent.com/28003269/31598129-fa919e14-b25c-11e7-94dd-f897ce859273.gif)

May be it will be better to have parallel attraction. In this case will possible to have bulging curves.

![attraction3](https://user-images.githubusercontent.com/28003269/31598372-4b7d8a44-b25e-11e7-9363-6c0a415d44e2.gif)

**Comment by zeffii** [comment]
that will because the Vectors/Vertices that are read by Objects In Mk3 don't read the radius of the Bezier/Splines. It might make sense to have a dedicated _Curve In_ node

**Comment by Durman** [comment]
Curve In node is good idea but i do not use radius parameter of curve yet. I just think how to improve vector attraction node. By radius I meant distance between attraction point and mesh. It is helpful to have maximum distance where attraction point could not to influence to mesh. 
Possible behavior of attraction point:

![attraction4](https://user-images.githubusercontent.com/28003269/31609183-2954ea9a-b284-11e7-8592-484ad81e1779.gif)

**Comment by zeffii** [comment]
I see. I will continue with Curve Input node anyway. Maybe you can keep elaborating eventually I will understand (or someone reading this)

**Comment by Durman** [comment]
May be more interesting to use normal vector direction for attraction.

![attraction6](https://user-images.githubusercontent.com/28003269/31652801-70f04086-b331-11e7-918f-f51d1584a782.gif)
![attraction5](https://user-images.githubusercontent.com/28003269/31652803-725cc746-b331-11e7-8a00-f618cbaed0c2.gif)

**Comment by Durman** [comment]
I managed to do correct behavior of point attraction. 

![attraction7](https://user-images.githubusercontent.com/28003269/31716364-7f952d9e-b418-11e7-8867-97d1666934f6.gif)

But I did not use Proportional edit fall off node I forgot about it.)) 
For this goal it need have two analyzers nodes that absent in Sverchek now. The first must look for closest polygon to vector. The second must measure distance between plane of polygon and vector. For this I found perfect function in mathutils that can give even negative distance. 
```Python
from mathutils.geometry import distance_point_to_plane

def get_dist(pt,pl_co,pl_no):
    return distance_point_to_plane(pt,pl_co,pl_no)

for c,i in enumerate(faces):
    dist.append(get_dist(point,verts[i[0]],normal_f[c]))
    
dist = [dist]
```
May be it will be useful to have such nodes in Sverchek.

**Comment by Durman** [comment]
I have some result it most likely work as I wanted. I use for this Proportional edit fall off node it is perfect but have some weaknesses: can't have negative values if speak about concave surface, absent possibility to set strength (altitude) of bulging. I used nodes next way:

![2017-10-20_08-26-10](https://user-images.githubusercontent.com/28003269/31805725-33674db4-b574-11e7-8e7e-3d80172754a1.png)

1. Just normal direction 
2. Value of something like altitude 
3. Here can be pasted some preparation. I use here multiplication for fixing value of altitude.
As result generator of random mountains.))

![2017-10-20_08-59-02](https://user-images.githubusercontent.com/28003269/31805819-f1ba58ce-b574-11e7-8ff6-433c38081c32.png)
And something strange.))
![strange](https://user-images.githubusercontent.com/28003269/31805873-5eb95f9c-b575-11e7-8340-c0448c6ebaff.gif)

**Comment by Durman** [comment]
Interesting behavior of positive and negative vectors.

![positive and negetive points](https://user-images.githubusercontent.com/28003269/31808456-47056f26-b584-11e7-8e74-0e0ba9fc707d.gif)
