### ISSUE TITLE
Curve In node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1817]
`Object In` can already load Curve data, but strips all data except points.

As @Durman [alludes to in this thread](https://github.com/nortikin/sverchok/issues/1816) there's a weakness in what we offer regarding Curve Object data. I'd like to offer extra introspection into the spline data, there's a lot we can add. Some of this data can only be [conveniently accessed](https://gist.github.com/zeffii/90fa1a83ce821d6ae03a71ae91e7cdd5) via scripts at this point.
```
Bezier Curve
    - points
    - num points per subcurve (set this property)
    - radius at points ( interpolate according to `LINEAR`..etc )
Spline Curve
    - points
    - num points per subcurve (set this property)
    - radius at points ( interpolate according to `LINEAR`..etc )
optional 
    - edges 
         - inferred if no thickness :   connect between points, 
         - if thickneses then use obj.to_mesh
    - polygons output  (when thickness present this can use obj.to_mesh)
```
No ETA.

**Comment by Durman** [comment]
I already have tried to receive radiuses of curve with script node.

```Python
if objs_in[0].data.splines[0].type == 'BEZIER':

    for i in objs_in[0].data.splines[0].bezier_points:
        bas_r.append(i.radius)
        bas_c.append(i.co)
else:
    for i in objs_in[0].data.splines[0].points:
        bas_r.append(i.radius)
        bas_c.append(i.co)
```
But i had problem with interpolation value of radius between intermediate points. I did not manage to receive exact distance between points by curve.

**Comment by zeffii** [comment]
yeah, i think the radii must be calculated by hand for interpolated points - i'm not aware of any convenience methods for this.. that's OK though.

**Comment by Durman** [comment]
Interpolation of radiuses i did thus: 
![2017-10-16_18-57-47](https://user-images.githubusercontent.com/28003269/31619396-751df662-b2a5-11e7-9163-ac63ac524324.png)
Where D axis is distance between points, R axis is radiuses of points, C1,2 is points of curve, Pn is interpolation points.
Pny = dyC2 * dyPn / dyC2 + C1y
But i do not know how to find distance between points on curve.

**Comment by zeffii** [comment]
@Durman we can offer multiple radius interpolation approaches. I'll implement linear and maybe cubic. If you're interested you can look at the Blender source for the exact algorithms. I'm not ready to do this yet

**Comment by zeffii** [comment]
anyone want to write a function that interpolations radii?
```python

def interpolate_radii(spline, num_segments, interpolation_type='LINEAR'):
    radii = []
    if spline.use_cyclic_u:
        ...

    return radii

```

**Comment by zeffii** [comment]
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.interp.html

**Comment by zeffii** [comment]
something like this? 
```python
import sverchok
from sverchok.nodes.number.range_float import frange_count


def interpolate_radii(spline, segments, interpolation_type='LINEAR', spline_type='NURBS'):
    radii = []

    point_attr = {'NURBS': 'points', 'BEZIER': 'bezier_points'}.get(spline_type)
    points = [p.radius for p in getattr(spline, point_attr)]

    if spline.use_cyclic_u:
        points.append(points[0])

    for idx in range(len(points)-1):
        params = points[idx], points[idx+1], segments
        if len(points) == 2 or not (idx < (len(points)-2)):
            radii.extend(list(frange_count(*params)))
        else:
            radii.extend(list(frange_count(*params))[:-1])

    return radii


num_segments = curve.render_resolution_u or curve.resolution_u
interpolate_radii(spline, segments, interpolation_type='LINEAR', spline_type='NURBS')


```

**Comment by zeffii** [comment]
looks like Linear and Catmul radii interpolation works.. and Biezer curve pickup too, but NURBS  pickup should work too (Path)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32104813-4a64ac84-bb26-11e7-86cd-c975ce5360a3.png)

**Comment by zeffii** [comment]
see the curve-in branch for testing.
![image](https://user-images.githubusercontent.com/619340/32124074-d1473466-bb66-11e7-857f-624af11fda96.png)

Note: the radius won't match if the Curve has a bevel depth. In that case you should add `bevel_depth/2` to the radius i think.. or subtract it..whatever :)

**Comment by Durman** [comment]
Is it possible to do same resolution of radiuses as points?
![resolution](https://user-images.githubusercontent.com/28003269/32131193-bd33a778-bbb8-11e7-942c-2b511a82d5ff.gif)

**Comment by zeffii** [comment]
I think I will leave it at `Object Level U resolution` for the time being. Obviously resolution per Spline (which is what you are changing when modifiering Active Spline's U resolution) would be valuable to have.

```python
    for obj in objects:

            ## collect all data we can get from the subcurve(s)

            mtrx_out.append([list(m) for m in obj.matrix_world])
            verts, edges, faces, radii = [], [], [], []
            curve = obj.data
            resolution = curve.render_resolution_u or curve.resolution_u
            # ('POLY', 'BEZIER', 'BSPLINE', 'CARDINAL', 'NURBS')
            for spline in obj.data.splines:
                
                if spline.type == 'BEZIER':
                    verts_part, edges_part, radii = get_points_bezier(spline, calc_radii=calc_radii)
                elif spline.type == 'NURBS':
                    verts_part, edges_part, radii = get_points_nurbs(spline, resolution, calc_radii=calc_radii)
                else:
                    # maybe later?
                    continue

                # empty means we don't offset the index
                edges.extend(offset(edges_part, len(verts)) if verts else edges_part)
                verts.extend(verts_part)
                # faces.extend(faces_part)
                if _out['radii'].is_linked:
                    radii_part = interpolate_radii(spline, resolution, interpolation_type=self.selected_mode)
                    radii.extend(radii_part)

            ## pass all resulting subcurve data

            verts_out.append(verts)
            edges_out.append(edges)
            # faces_out.append(faces) 
            radii_out.append(radii)
```
