### ISSUE TITLE
Absent checking that KDTree was built in Proportional Edit Fall off node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1820]
When mask list consist just from False values node try to create KDTree...
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/nodes/analyzer/proportional.py#L106-L108
After that this is trying to use KDTree...
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/nodes/analyzer/proportional.py#L114-L119
and is receiving exception here
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/nodes/analyzer/proportional.py#L82-L83
![2017-10-18_19-34-36](https://user-images.githubusercontent.com/28003269/31727727-676fbf7c-b43b-11e7-9dd7-2d4146a037f6.png)
It is not good.

**Comment by zeffii** [comment]
@portnov might respond ( analyzer/proportional.py is his node )

**Comment by Durman** [comment]
I think if all values in mask is False all coefficients must be zeros.

**Comment by zeffii** [comment]
so if no tree is built..
```
coeffs = []

if len(base):

    for vertex, mask in zip(vertices, masks):
        if mask:
            coef = 1.0
        else:
            _, _, rho = tree.find(vertex)
            coef = self.falloff(radius, rho)
        coeffs.append(coef)

else:
    coeffs = [0.0 for m in masks]

```
?

**Comment by Durman** [comment]
Yeah, something like that)

**Comment by zeffii** [comment]
```python
        out_coeffs = []
        meshes = match_long_repeat([vertices_s, masks_s, radius_s])
        for vertices, masks, radius in zip(*meshes):
            fullList(masks, len(vertices))

            if isinstance(radius, list) and isinstance(radius[0], (int, float)):
                radius = radius[0]

            # build KDTree
            base = [v for v, mask in zip(vertices, masks) if mask]

            if len(base):
                tree = kdtree.KDTree(len(base))
                for i, v in enumerate(base):
                    tree.insert(v, i)
                tree.balance()

                coeffs = []
                for vertex, mask in zip(vertices, masks):
                    if mask:
                        coef = 1.0
                    else:
                        _, _, rho = tree.find(vertex)
                        coef = self.falloff(radius, rho)
                    coeffs.append(coef)
            else:
                coeffs = [0.0 for m in masks]

            out_coeffs.append(coeffs)

        self.outputs['Coeffs'].sv_set(out_coeffs)
```

**Comment by zeffii** [comment]
@Durman  make a branch, edit the code... test it... and do a pullrequest :)  i think you are more than capable to do this.

**Comment by Durman** [comment]
Okay I will try.

**Comment by Durman** [comment]
I am not quite understand how to test my code? 
I created my branch fixed there proportional node downloaded and pasted it into Sverchok master folder on my computer but when I start Blender Sverchok absent there. How to do this right?

**Comment by zeffii** [comment]
maybe for the first few pull requests.. if you are new to GIT / github i suggest the following. Use the online github website features to do a pull request.

navigate to the file in the online browser, and press the icon i've indicated ( the pencil ):
![image](https://user-images.githubusercontent.com/619340/31854398-9ca4b2f6-b698-11e7-9fe8-4dc8f150df58.png)

then 
![image](https://user-images.githubusercontent.com/619340/31854412-e90d3726-b698-11e7-866f-572be5839700.png)

the button will turn green if you actually change something in the code :)

you can test your file locally, then copy the entire content into that window and press the green button to do a pull request.

( we main developers don't submit code this way.. but it's OK to do it this way for small changes )
