### ISSUE TITLE
Circle to Triangle ala Golan Levin

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1827]
![prtscr capture_59](https://user-images.githubusercontent.com/3952687/32031086-d02856d6-ba4a-11e7-96ad-ebd3fd901751.png)
![circle_tri_001](https://user-images.githubusercontent.com/3952687/32031087-d055f866-ba4a-11e7-83a0-cb7b0a08daeb.gif)
[golanlevin_interpolation_tri_circle_002_2017_10_26_01_40.zip](https://github.com/nortikin/sverchok/files/1416692/golanlevin_interpolation_tri_circle_002_2017_10_26_01_40.zip)

I am recreating this Circle to Triangle ala Golan Levin (Processing Code Train).

It's not yet perfect. I am kind of wondering if Sverchok has a way to "split" a connected lines that turns:
A - B - C
into
A - A1,  A1 - B1,  B1 - C

**Comment by enzyme69** [comment]
![prtscr capture_60](https://user-images.githubusercontent.com/3952687/32031190-6a309cf2-ba4b-11e7-89c0-435e0cf07b7f.png)

Seems like I could do this... but

**Comment by enzyme69** [comment]
![circle_tri_002](https://user-images.githubusercontent.com/3952687/32031381-a0e2e60a-ba4c-11e7-908c-2f1fe0da4cf4.gif)
![prtscr capture_61](https://user-images.githubusercontent.com/3952687/32031383-a1103c40-ba4c-11e7-80aa-653a6425103b.png)
[golanlevin_interpolation_tri_circle_003_2017_10_26_01_53.zip](https://github.com/nortikin/sverchok/files/1416726/golanlevin_interpolation_tri_circle_003_2017_10_26_01_53.zip)

I can fake the setup, but there must be a way to cut snake / worm so that at intersection it keeps the points.

**Comment by Durman** [comment]
I reckon that Split Edges node should split object like the Vector interpolation node but it does not work

![split adge](https://user-images.githubusercontent.com/28003269/32036184-34ea220a-ba2f-11e7-853d-349f127db611.gif)

**Comment by enzyme69** [comment]
[cut_circle_002_2017_10_26_05_42.zip](https://github.com/nortikin/sverchok/files/1417063/cut_circle_002_2017_10_26_05_42.zip)
![screen shot 2017-10-26 at 16 42 36](https://user-images.githubusercontent.com/3952687/32036634-6194c956-ba64-11e7-8a6f-c44ad6c9bad8.png)

Maybe that Split Edges is not "vectorized". But I can use Monad.

So there are 2 ways, very Sverchok way to do this:
1) 3 x Arc for Triangle with resampling
2) Some kind of node or setup that can cut but leaves extra point, just like "intersect".

**Comment by enzyme69** [comment]
Using List Item and List Shift and Monad, weird, but also logical...
[cutting_circle_002_2017_10_26_07_09.zip](https://github.com/nortikin/sverchok/files/1417293/cutting_circle_002_2017_10_26_07_09.zip)

**Comment by zeffii** [comment]
look at the trigonometry
![image](https://user-images.githubusercontent.com/619340/32133450-447b942e-bbd8-11e7-97dc-6e64f41a5171.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32134093-c8411ed4-bbe5-11e7-8c45-1b25258741fb.png)
