### ISSUE TITLE
Floyd Steinberg Dither using Sverchok Script Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1828]
[dither_python_012_2017_10_27_03_28.zip](https://github.com/nortikin/sverchok/files/1420692/dither_python_012_2017_10_27_03_28.zip)

I am trying to understand Numpy and Pixel and converting this "dither algorithm".
https://github.com/trimailov/qwer/blob/master/main.py

For my Pikachu image 64 x 64 pixel, somehow I am stuck with a simple fact that Python Numpy is between 0-63 while in the algorithm, I think it needs 1-64 for list that will later become pixel[x,y].

There is this Stackoverflow talking about it, by simply adding 0, but does not work.
https://stackoverflow.com/questions/11623264/python-data-structure-index-start-at-1-instead-of-0

Does anyone here familiar with Image Processing and use Numpy and Scipy and how to handle this?

Thanks!

**Comment by enzyme69** [comment]
![prtscr capture_69](https://user-images.githubusercontent.com/3952687/32086955-580b0222-bb24-11e7-9c0b-bc2fddd6c247.png)

Just changing the range gives an error... it is off, I think because the array 0-63 and 1-64 thing.

![prtscr capture_69](https://user-images.githubusercontent.com/3952687/32086972-6cfe15ca-bb24-11e7-8f44-2c380cc8ab1d.png)

**Comment by enzyme69** [comment]
![numpy_expand_001](https://user-images.githubusercontent.com/3952687/32087988-9e0be49c-bb2b-11e7-99c4-fa7e4023abdd.png)
There must be an easy way to add row and column zero... checking...

**Comment by enzyme69** [comment]
![prtscr capture](https://user-images.githubusercontent.com/3952687/32089604-aa894b6e-bb36-11e7-8deb-de74b6b042c6.png)

I might have done the right thing by switching the X and Y in the array, it was not apparently the 0-63 and 1-64 issue.

[dither_python_016_2017_10_27_05_47.zip](https://github.com/nortikin/sverchok/files/1420906/dither_python_016_2017_10_27_05_47.zip)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/947 11 dither methods
