### ISSUE TITLE
Sorting polygons based on distance/direction

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1829]
Is there a way SV can sort polygons based on distance to a point or in a given direction  ?

**Comment by zeffii** [comment]
vertices_sort.py will sort verts and edges/faces based on various criteria

**Comment by zeffii** [comment]
But.. i think it reindexes the verts rather than keeping then static and reindexing edges and faces

**Comment by nortikin** [comment]
using list sort helps me always

**Comment by DolphinDream** [comment]
I wonder if the “Select Mesh Elements” node does some sort of polygon sorting by distance already.

**Comment by nortikin** [comment]
no, it acts like selection only.
![selection](https://user-images.githubusercontent.com/5783432/32679445-845fc73c-c677-11e7-8676-8ce1e3cef55f.png)

**Comment by zeffii** [comment]
if you want to make a polygon sort node, do :)

**Comment by DolphinDream** [comment]
Well.. I wanted it.. so i did it! :) #2324 

Honestly I don’t remember why I originally wanted this node, but I must have needed it bad enough to warrant filing an issue ticket a year ago. :)
