### ISSUE TITLE
Vectorization(or how is it named?) for some internal blender classes. 

### ISSUE THREAD

**Issue by xxxLOwreriderxxx** [nortikin/sverchok#1831]
Hello there
How can I get some values from list of objects, materials or anything whith Object ID Set node? There is some error. 
![2017-11-01_03-47-13](https://user-images.githubusercontent.com/33270542/32255325-1ae07930-beb8-11e7-9810-4c33cab71156.png)
![2017-11-01_03-47-27](https://user-images.githubusercontent.com/33270542/32255330-1da38e28-beb8-11e7-9412-950a7e320974.png)
Formula node dosen't work too. 
I thinking to write script for scriptnode, but I don't know how.

**Comment by enzyme69** [comment]
![screen shot 2017-11-01 at 18 21 52](https://user-images.githubusercontent.com/3952687/32264189-920331b4-bf31-11e7-93b5-02dcaa94521b.png)

I would usually do it this way like above. So it's inspecting the Material, linked to the object.

**Comment by Kosvor2** [comment]
One material have its ".node_tree" activated, while others not. They return "None" as their ".node_tree", and "None" does not have ".nodes" attribute. Just a guess.

**Comment by zeffii** [comment]
Setting material properties like colour rgba may not work in realtime (it will , it should work  but the updates might be slow.)

**Comment by enzyme69** [comment]
Yes, Zeffii is right, the Material RGB update is often slow. I use Object
Color as alternative.

**Comment by xxxLOwreriderxxx** [comment]
@Kosvor2 
Your version was closest. But all materials except one witch I filered out used node. 
I think problem was in the way I get several materials. I just don't know where from it appeared:D Maybe because it's generated by SV or something. 
Anyway whith my handmade materials the scheme is working.
![2017-11-01_19-10-04](https://user-images.githubusercontent.com/33270542/32284440-4dfb0198-bf38-11e7-8fdc-b02f1680700f.png)

@zeffii
@enzyme69 
Textures go well. 
![](http://g.recordit.co/D5UCou4OHY.gif)

Thank you all!
