### ISSUE TITLE
Exec Node to keep last frame while not True

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1832]
![screen shot 2017-11-02 at 11 58 12](https://user-images.githubusercontent.com/3952687/32304660-1d5a36e8-bfc5-11e7-8559-bd621abbec22.png)

I got this setup using setup using Sverchok, the exec node is supposed to get and return the last frame before input True.

Does not seems to work.

I did however manage to make Sverchok keep printing numbers, until True is input.

**Comment by enzyme69** [comment]
Blend Zip:
[sv_lotto_001_2017_11_02_00_45.zip](https://github.com/nortikin/sverchok/files/1436135/sv_lotto_001_2017_11_02_00_45.zip)

Where did I go wrong?

**Comment by enzyme69** [comment]
I noticed I did a typo, but that's not it.

**Comment by enzyme69** [comment]
![screen shot 2017-11-02 at 12 06 51](https://user-images.githubusercontent.com/3952687/32304883-55bd8e94-bfc6-11e7-96fd-64124ed73587.png)
This seems to work but not elegant.

**Comment by Durman** [comment]
something like this
```Python
if V1[0][0] != True:
    append([bpy.context.scene.frame_current])
```
but is't it the same?
![2017-11-02_07-54-52](https://user-images.githubusercontent.com/28003269/32309180-394bb3a8-bfa3-11e7-8a23-4fbdce4be5f0.png)

**Comment by enzyme69** [comment]
Yes somewhat that does not work, maybe my setup is funky and causing it not
to work this way. Hmmm...

**Comment by zeffii** [comment]
i'm not sure I understand what you're trying to do... you've written code here and stated that it doesn't work.. or it does work but doesn't look elegant.  (jimmy if it works.. it's OK code... elegance is something you can only asses when you have some mastery)

Execnode isn't stateful (and won't be.. probably..) so you can not rely on values stored during a previous update   to the node tree. If you want to keep track of a value for longer durations than one frame you will need to use SNlite with a `setup()` or register a throwaway IntProperty to something like `bpy.types.Scene`

**Comment by enzyme69** [comment]
I see... ok thanks Dealga.

**Comment by zeffii** [comment]
jimmy, use the "copy code to clipboard" button in the Exec Node's external N panel buttons, to paste code here. It beats having to read code in a screenshot.

**Comment by zeffii** [comment]
```python
# ------------------ yours ------------------

lastframe = []

if V1[0][0] != True:

    print(bpy.context.scene.frame_current)
    lastframe.append(bpy.context.scene.frame_current)

append([lastframe[-1]])

# ------------- yours rewritten -------------

lastframe = []
scn = bpy.context.scene

if not V1[0][0]:
    print(scn.frame_current)
    lastframe.append(scn.frame_current)

append([lastframe[-1]])
```
this is what i mean by using the throwaway property..
```python
# ----------------------------  
scn = bpy.context.scene
if not hasattr(scn, bs_lastframe): 
    bpy.types.Scene.bs_lastframe = bpy.props.IntProperty()

if V1[0][0]:
    print(scn.bs_lastframe)
    scn.bs_lastframe = scn.frame_current

append([scn.bs_lastframe])
```
This is more code, but using a scene variable means you can store information outside of the loop ecxecuted by Exec Node. I haven't run that code, it might not work.. but it should :)

**Comment by zeffii** [comment]
the last snippet i suggested above, maybe you can explain what you think that does @enzyme69 .

**Comment by zeffii** [comment]
not really an "issue"
