### ISSUE TITLE
Axis control for scaling factor in Extrude Separate Faces

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1835]
See new users sane request: 
https://blenderartists.org/forum/showthread.php?272679-Addon-WIP-Sverchok-parametric-nodes-for-architects&p=3253764&viewfull=1#post3253764

https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/extrude_separate.py

any takers?

**Comment by Durman** [comment]
Okay. I tried to do something but it's not work. How to change type of scale input from list to vector?
I tried rewrite in this way:
```Python
scale_ = FloatVectorProperty(name='Scale', default=(1.0,1.0,1.0),
            description='Extruded faces scale', precision=3,
            update=updateNode)
...
        self.inputs.new('VerticesSocket', "Scale").prop_name = "scale_"
```

**Comment by zeffii** [comment]
Cool Durman - i'll help you a little 

We don't need to add a new a socket, we can "recast" a socket type from one type to another ( similar to doing `int(float)` or `float(int)` )  with `socket.replace_socket("VerticesSocket")` 

have a look in the code base for the use of `replace_socket`. When a socket is replaced we can set a new `prop_name`.

**Comment by zeffii** [comment]
but.. @Durman  i don't really think the socket needs to be replaced_dynamically (certainily not initially...for exploring this feature) . we can get the Node understand `Scalar->Scale` and `Vector->Scale`.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32415026-9f55d408-c232-11e7-8bdd-a979cb797806.png)

https://github.com/nortikin/sverchok/pull/1844

if you look at the changed code, you'll get an idea of some of the code needed. I think it might only make sense to interpret 2 axis for the scale (this is hard to explain.. try the branch )

**Comment by Durman** [comment]
The work of scaling is working wrong now. This happened because matrixes was prepared for another logical in `bmesh.ops.scale` function.

![extrude scale axic](https://user-images.githubusercontent.com/28003269/32531643-7cb5f184-c45e-11e7-87a8-f9822562fdfc.gif)
```Python
dr = face.normal * height
center = face.calc_center_median()
translation = Matrix.Translation(center)
rotation = face.normal.rotation_difference((0,0,1)).to_matrix().to_4x4()
#rotation = autorotate(z, face.normal).inverted()
m = translation * rotation
bmesh.ops.scale(bm, vec=(scale, scale, scale), space=m.inverted(), verts=face.verts)
```
here face is get extruded faces
I am investigating how to fix this and what behavior is expected from scaling.

**Comment by Durman** [comment]
I suppose that axis Y of rotation matrix must always be in the surface that are created by vector of normal to polygon and vector of axis Z. It will be work except case when polygon lays on XY sourface. In this case axis Y can always match with Y axis of scene.

![2017-11-08_11-42-57](https://user-images.githubusercontent.com/28003269/32536941-fbca6d40-c479-11e7-98d8-1c9f7ab66941.png)

**Comment by zeffii** [comment]
@Durman  yes, restrict the scale factor to X/Y (in the plane of the  extruded face). We discard then Z component of the input vector. This is the desired end-effect

**Comment by Durman** [comment]
It appears is working now. But code is not great I think. I am not clever in matrix )) and didn't understand why is necessary `.inverted()` matrix for `bmesh.ops.scale`

![extrude scale axic2](https://user-images.githubusercontent.com/28003269/32592472-4c478afa-c53d-11e7-9289-661f878aee2f.gif)

My version of preparing matrixes
```Python
    normal = face.normal
    
    if normal[0] == 0 and normal[1] == 0 and normal[2] >= 0: mmy = Matrix()
    elif normal[0] == 0 and normal[1] == 0 and normal[2] < 0: mmy = Matrix.Rotation(pi,4,'X')
    else:    
        z_axis = normal
        x_axis = (Vector((z_axis[1] * -1, z_axis[0], 0))).normalized()
        y_axis = (z_axis.cross(x_axis)).normalized()

        mmy= Matrix_generate([[(x_axis[0], y_axis[0], z_axis[0], 0.0),
            (x_axis[1], y_axis[1], z_axis[1], 0.0),
            (x_axis[2], y_axis[2], z_axis[2], 0.0),
            (0.0, 0.0, 0.0, 1.0)]])[0]
```
I will create branch soon.

**Comment by zeffii** [comment]
as long as the output looks good @Durman , its OK. it also provides an opportunity to add algorithm-time testing. Sometimes verbose code outperforms shorter code.

**Comment by Durman** [comment]
#1853

**Comment by zeffii** [comment]
further discussion has taken place in the branches. 

close the issue - but we can still keep debate open.
