### ISSUE TITLE
Drawing Text from numeric values from a node

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1836]
How do I draw text based on some numeric values from a node? e.g I have various squares with different scales and I want to annotate each square with the scale factor of each square.

For that matter, is there (or should there be) a node that lets you enter a string/text and have that drawn via a Text Draw node ? 

![sv-textannotation](https://user-images.githubusercontent.com/2083719/32401532-8f2e6d30-c0e6-11e7-9ff6-b695ad8a5ed2.png)

![sv-textannotation-mockup](https://user-images.githubusercontent.com/2083719/32401533-8f3d8df6-c0e6-11e7-907c-808a4b41773c.jpg)

**Comment by zeffii** [comment]
do you mean Text Objects or bgl drawn text... we have both

**Comment by zeffii** [comment]
#### Index Viewer 

The bgl text is draw-able using Index Viewer. It has additional sockets for text at coordinates given by vectors. The downside is that the font size is not variable per text-element. 

#### Typography Viewer

Uses scene Objects (Font type) and has many features. The more generalized a node hopes to be, the more complex the internals tend to get. have a look at the .py ...but be in a good mood first.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/581

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32404335-0d5f4190-c14e-11e7-8c09-7ca37e02ba30.png)
(typography viewer doesn't work with IO/JSON at the moment... i'll investigate - some bpy might have changed)

**Comment by zeffii** [comment]
but don't be fooled, it's just these nodes that would be involved in setting text / matrix
![image](https://user-images.githubusercontent.com/619340/32404413-88c449a6-c14f-11e7-9a41-d3ec37fc282a.png)

**Comment by zeffii** [comment]
and if all you have is a list of numbers..  `[1,2,4,8]` and want to transform that into `["x1", "x2", "x4", "x8"]` then you do:

![image](https://user-images.githubusercontent.com/619340/32405445-6cbc79a2-c165-11e7-8226-377b776a68ff.png)

**Comment by DolphinDream** [comment]
Perfect ! Thanks @zeffii . The Topography Viewer is what I wanted. Thanks for setup details btw, it helped a lot. I thought you would need some sort of “string” node to feed into that TV node :)  So I guess if you want to feed a set of strings into the TV you can either use Formula or ExecMod node. Kewl.

**Comment by DolphinDream** [comment]
Now all I need to do is to figure out a way to say x1/8 instead of x0.125 :) 

![sv-textannotation-x](https://user-images.githubusercontent.com/2083719/32407681-c631d7fa-c162-11e7-9903-3259b04efc9a.png)

**Comment by DolphinDream** [comment]
And the winner goes to:  **Exec Node Mod** : x1/N and xN 😃 


![sv-textannotation-spiral](https://user-images.githubusercontent.com/2083719/32408055-3e927c7c-c168-11e7-87b2-d51f93d12481.png)

**Comment by zeffii** [comment]
>  is there a way to get the double nested output from the ExecNodeMode without using the extra list joint node

can you show what the list looks like..and how you would like it to look.. i don't like guessing

**Comment by DolphinDream** [comment]
Btw, I wanted this annotation setup to illustrate the scales for a logarithmic spiral with the spiral node (apparent form the screenshots). In general it’s impossible to know at what scale you are while looking at a spiral. The sceencapture shows 3 differenet scales.. x1 (center) and zoomed in / zoomed out (left/right) to show how the SpiralNode modes affect the spiral (spoiler alert for the next SpiralNode additions :) 

![sv-spiralnode-demo9](https://user-images.githubusercontent.com/2083719/32408163-d49edade-c169-11e7-9675-9658d00b9a84.gif)

**Comment by zeffii** [comment]
oh.. think you just want to drop the brackets in the `extend` .. or use `append`..

**Comment by DolphinDream** [comment]
@zeffii The way I have the ExecNodeMod setup it ouputs [s1, s2, .., Sn] and i think the Topography Node expects the input to be [[s1, s2, .. ,sn]] .. so I added the **List Join** node to add the extra nested level. 

![sv-execnodemod-nestedness](https://user-images.githubusercontent.com/2083719/32408189-3c39c1a4-c16a-11e7-948e-e1c163f23211.png)

**Comment by zeffii** [comment]
you can probably write something like..
```
out.append([])
for x ....
    ...
    ...
    out[0].append(text)
```

btw, the N panel of the exec node has an option to copy the code to the clipboard.. for pasting here easily.

**Comment by DolphinDream** [comment]
> oh.. think you just want to drop the brackets in the extend .. or use append..

actually neither of these work: extend(text) will create  a list of characters (length 1) and append([text]) will create a list [[s1], [s2], .. [sn]] .. neither of which will work as expected with TV node.

**Comment by DolphinDream** [comment]
btw, a copy from clipboard feature would be nice to have. (I typically use an external editor to edit code... I’m not a big fan of Blender’s text editor).

**Comment by DolphinDream** [comment]
Should TV node accept single nested lists anyway ? [s1, s2.. s2] ? and perhaps internally convert them to a [[s1, s2, .., sn]] ?

**Comment by zeffii** [comment]
in exec node we aliased `append` and `extend` keywords for `out.append` and `out.extend`

> a copy from clipboard feature would be nice to have.  

yeah, can add.

> Should TV node accept single nested lists anyway ? [s1, s2.. s2] ? and perhaps internally convert them to a [[s1, s2, .., sn]] ?

also, probably should. I didn't spend a lot of time ironing out usability issues. It really depends how you're generating the input..

**Comment by zeffii** [comment]
but regarding `[s1, s2, s3...]`  in Sverchok convention that's malformed, there always needs to be an outer list.

**Comment by DolphinDream** [comment]
Also, is it possible to join the text objects created with TV node  somehow? in order to avoid ending up with lots of text objects (in the outliner). Apparently I can’t join the text objects (via ctrl+j). Perhaps have an option to create a parent holder object so that all text objects can be collapsed under its parent in the outliner ? I think this would be a cool feature (similar to AN) to add to the group/merge features. (e.g. the Bmesh Viewer could have: group/merge/parent), where parent option would create individual objects, but would parent them all under the given parent object.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32408441-31075d9a-c198-11e7-9b7d-86e02dae1610.png)
and
![image](https://user-images.githubusercontent.com/619340/32408454-5a501976-c198-11e7-8aca-68c7f6e757ce.png)

**Comment by DolphinDream** [comment]
Sweeeeet :) Wow.. what an easy to find awesome feature ;) I have to explore this node a bit more it seems.

**Comment by DolphinDream** [comment]
We should probably add this feature to Bmesh Viewer node and other object generating nodes.

**Comment by zeffii** [comment]
it's not intentionally hidden away, ... there's also the `Group` feature in the main node UI. rather deliberately ever-present..

**Comment by zeffii** [comment]
all scene-object-generator  nodes have group, some also have Empty parenting.

**Comment by DolphinDream** [comment]
Btw, once you use the “parented”, the text objects stay parented even when you unselect that option. is this by design ?

**Comment by zeffii** [comment]
no... by "lack of design" maybe.

**Comment by zeffii** [comment]
i'll add the parent removal to my current Typography Viewer pass.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1839

can close this topic, seen as question is answered ..?

**Comment by DolphinDream** [comment]
Perhaps also add the option to name the empty parent.

**Comment by Durman** [comment]
I prefer such way for creating nested lists.
![2017-11-05_09-19-15](https://user-images.githubusercontent.com/28003269/32412237-9099f5fc-c20a-11e7-90bc-4865732a68e0.png)
