### ISSUE TITLE
Color input to Viewer Draw 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1841]
Would it be possible to make Viewer Draw take a color input (for all colors: vertex, edge, poly) so that you can control the colors externally ?

**Comment by zeffii** [comment]
i hadn't planned on adding a socket to ViewerDraw (and actively oppose it before 2.8). The request has surfaced a few times before, if you really need that i'd suggest using SNLite or Exec Node -- while they may not be so immediately accessible they will allow you to use sockets and pass color values to the instances of viewerdraw..

**Comment by DolphinDream** [comment]
Any clues of how to do that ? a good starting point where to look for examples ?

**Comment by zeffii** [comment]
```python
"""
in color_one s
in color_two s
in color_three s
out dummy v
"""

nodes = self.id_data.nodes
vd0 = nodes["Viewer Draw"]
#vd1 = nodes["Viewer Draw.001"]
#vd2 = nodes["Viewer Draw.002"]

try:
    vd0.vertex_colors = color_one[0][0]
    vd0.edge_colors = color_two[0][0]
    vd0.face_colors = color_three[0][0]
except:
    print('sockets not connected')
```
i'll be the first to admit this isn't super convenient.. it could be much simpler.
![image](https://user-images.githubusercontent.com/619340/32413362-60a50c46-c210-11e7-8661-d29b5decd871.png)

**Comment by zeffii** [comment]
there are so many properties of a viewer node that one might want to control, that it would make sense to dedicate a new socket to it. But.. like max/msp / puredata i'd consider letting the socket by "packable", either accepting a dict of values to set..(because argument lists tend to be a pain)...

so the socket might take input like 
```python
{'vertex_colors': (....), 'edge_colors': (...) ,.... 'vertex_size': 3.4}
```
and you'd use a different node to pack it.

**Comment by zeffii** [comment]
composed temporarily in ExecNode 
```python
out.append({
    'vertex_colors': V1[0][0],
    'face_colors': V2[0][0],
    'edge_colors': V3[0][0]
})
right now it probably looks a little clumbsy using the execnode... but hey.. vdmk2 isn't antialiased, so we don't use it for final visualization and don't need t a lot of parametric control over the parameters.

I'm showing with this a reason why it's probably not a great idea to add tonnes of sockets for something like this... because it will always miss something needed by someone.. but with the addition of a props socket you open up alternative ways to pass properties.

https://github.com/nortikin/sverchok/pull/1843 Branch... test..

**Comment by zeffii** [comment]
you'll notice that the props socket content doesn't overwrite the VDMK2's own properties. It instead replaces the values with new values right before making the callback to the bgl routine.

Updating node properties from a socket would require freezing the update feature until all properties that have `update=updateNode` are modified. It's possible, easy.. but ultimately i'm not willing to modify that yet (or in this iteration of vdmk2)

**Comment by DolphinDream** [comment]
That is super awesome.. however what I had in mind is more than just changing the node 3 colors, but the ability to change also the 3  colors of every instances the VDK creates via matrix input. Additionally it would be even more awesome if you could also modify the color at the vertex level, so that each vertex/edge/poly in the mesh is colored with a color value you can set externally.

I’m thinking of a spiral line that changes colors as it goes from one end to the other :) Or a set of squares replicated for different scales that have different colors at different scales etc.

I’m not sure if you can do this via scripts or additional props socket or whether the VD node itself would have to be further modified to work with array of colors.

**Comment by zeffii** [comment]
Ive been thinking about those kinds of modifications for a while, not just vdmk2 but bmv2 too. A props socket is the way to go.  But you may want to explore snlite to draw bgl.. search the tracker.

**Comment by zeffii** [comment]
a few working examples..
![image](https://user-images.githubusercontent.com/619340/32436705-32485d5a-c2e5-11e7-8f67-8cf29f36658f.png)
..more work, but potentially supremely customizable.

i'm reluctant to spend much of my time trying to augment vdmk2, until blender2.8 exposes/settles on a new drawing api..

**Comment by zeffii** [comment]
if you read `viewer_draw_mk2.py` (in sverchok/ui...this is the callback that VDMK2 node passes raw data into) it's optimised based on an assumption that the node doesn't set the vertex colors per `vertex`, `face-vertex`, `edge-vertex`.

A way out of this is to keep vdmk2 the way it is, and instead make a branch and write a `ViewerDraw Lite`, with simple (potentially highly unoptimized) routines to allow more creative experimentation of input.

I'd like to point out that there's still no good way to render the bgl drawing by vdmk2 (like anti-aliased edges...and no z-fighting edges/faces) , the ways Blender itself gets around those issues are by face orientation checking and z-offsetting (all relatively fast in C,... but can be much slower for python....)

**Comment by zeffii** [comment]
or.. have a secondary draw_geometry method.. as an import..
```python
...
...
            glNewList(the_display_list, GL_COMPILE)
            if ['custom_drawing'] in options:
                draw_geometry_custom(n_id, options, data_vector, data_polygons, data_matrix, data_edges)
            else:
                draw_geometry(n_id, options, data_vector, data_polygons, data_matrix, data_edges)
...
```

**Comment by zeffii** [comment]
or... like the snlite callback
```
            glNewList(the_display_list, GL_COMPILE)
            if 'custom_drawing' in options:
                if 'draw_function' in options:
                    options['draw_function'](n_id, options, data_vector, data_polygons, data_matrix, data_edges)
                else:
                    draw_geometry_custom(n_id, options, data_vector, data_polygons, data_matrix, data_edges)
            else:
                draw_geometry(n_id, options, data_vector, data_polygons, data_matrix, data_edges)
...

**Comment by zeffii** [comment]
```git
- draw = options['draw_function'] if 'draw_function' in options else draw_geometry_custom
+ draw = options['draw_function'] or draw_geometry_custom
```

**Comment by zeffii** [comment]
because..
```python
def draw_me():
    print('like this')

def draw_it():
    print('like that')

options = {'draw_function': draw_me}

draw = options['draw_function'] or draw_it

draw()
# >>>  like this
```

**Comment by zeffii** [comment]
and doing `vd_props = id, options ..........`  is OK because
```python
fasr = ['twoo', 20, 30, 'eeeee']
fare = [1,2,3,4,5,30,50,200000]

print(id(fasr))
print(id(fare))

alk = fasr, fare

print(id(alk))

print(id(alk[0]))
print(id(alk[1]))

> 2412157130440
> 2412157130696
> 2412157215496
> 2412157130440
> 2412157130696

```
making a tuple of variables doesn't make copies of those variables :)
