### ISSUE TITLE
f-curves

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#1846]
https://docs.blender.org/api/blender_python_api_2_59_0/bpy.types.FCurve.html
will experiment with f-curves. needed for some resons.
 maybe to add in workflow or to add to only float/int number nodes.

**Comment by nortikin** [comment]
```python
class fc(bpy.types.FCurve):
    bl_idname = 'fc'
    bl_label = 'fc'
    data_path = D.scenes['Scene'].sv_light_direction
```
for example this will give f-curve to manipulate in animation.

**Comment by nortikin** [comment]
do we need add data_path all the node tree?

**Comment by nortikin** [comment]
data_path = bpy.types.SverchCustomTreeType maybe. not sure, later will investigate

**Comment by zeffii** [comment]
@nortikin  see end : https://github.com/nortikin/sverchok/issues/1364
