### ISSUE TITLE
Get an object property

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1855]
Is there a way to get an object property, like the object’s bounding box ?

**Comment by DolphinDream** [comment]
I did a min/max on the verts (with applied matrix) but i wonder if there is an easier/quicker way.

**Comment by enzyme69** [comment]
I had same question way back ago, wondering if Blender bpy provides way to
get bbox min and max. So far using calculation of bbox node....
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32650168-0ebc50f6-c5fd-11e7-8409-9ea54d0eb64d.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32662841-256fd366-c62c-11e7-8a36-f106b667f2e7.png)
maybe.. bounding_box node should have another socket, `SvObjectSocket` or autorecast..
