### ISSUE TITLE
Getting Color from UV Space, based on nearest position of an object

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1856]
Probably has been asked or there is a similar question somewhere. Or maybe not yet asked.

Just wondering if Sverchok or BMesh has some kind of ways to give 3D point XYZ in 3D space, and then it can find the nearest UV point and return color based on texture.

... 

A quick brain thinking, I think Sverchok can layout UV and then the UV can represent 2D flat texture, perhaps I could reverse engineer the node... hmm....

**Comment by enzyme69** [comment]
I am actually staring at this questions:
https://blender.stackexchange.com/questions/93840/particle-instance-modifier-colour-each-instance-based-on-the-emitter-texture?atw=1

Weird thing is that if Blender Hair Strand can color particle hair by looking at UV, there should be a way to get those colors and then pass it into Instance easily. Unless it is not that easy.

**Comment by zeffii** [comment]
given a `3d Vector` and an `Object` you can return the `location on the Object` that lies closest to the `3d Vector`. The location obtained can either lie on a _polygon, edge.. or a single vertex_.

The question really becomes, How to translate a location on an Object's polygon, to the location on the corresponding UV map.

**Comment by zeffii** [comment]
blender.stackexchange.com welcomes those kinds of question.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/32689862-533b0fac-c6ec-11e7-866f-673520967ef4.png)


https://blender.stackexchange.com/questions/79236/access-color-of-a-point-given-the-3d-position-on-the-surface-of-a-polygon
