### ISSUE TITLE
[NODE] Making sense of Matrix Track To...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1862]
Even after reading this documentation, I am still quite confused:
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/docs/nodes/matrix/matrix_track_to.rst

How does this node compareds to the Track To Constraint? If we wanted to make a Cone to point at Empty?

![screen shot 2017-11-13 at 10 27 26](https://user-images.githubusercontent.com/3952687/32704701-4380e6a0-c85d-11e7-930d-d94175f73f45.png)

**Comment by nortikin** [comment]
it is not using Z axis
![matrix-track-to](https://user-images.githubusercontent.com/5783432/32766058-4b9850dc-c91e-11e7-942f-cc9b670db996.gif)

**Comment by enzyme69** [comment]
Ok I will study this, cheers @nortikin

**Comment by enzyme69** [comment]
Example here:
[matrix_track_to_002_2018_01_04_00_54.zip](https://github.com/nortikin/sverchok/files/1602149/matrix_track_to_002_2018_01_04_00_54.zip)
<img width="904" alt="screen shot 2018-01-04 at 11 54 44 am" src="https://user-images.githubusercontent.com/3952687/34546228-98245e5a-f146-11e7-8e4b-a6bbd2491cd2.png">

But still A and B does not make sense...

**Comment by enzyme69** [comment]
Why not all the monkeys looking into the Empty?
[matrix_track_to_002_2018_01_04_01_00.zip](https://github.com/nortikin/sverchok/files/1602154/matrix_track_to_002_2018_01_04_01_00.zip)
<img width="956" alt="screen shot 2018-01-04 at 12 00 02 pm" src="https://user-images.githubusercontent.com/3952687/34546270-d2882a4a-f146-11e7-9035-e50141055c4f.png">

**Comment by enzyme69** [comment]
And seems like the Matrix Track To only works for (0,0,0) position?

<img width="612" alt="screen shot 2018-01-04 at 12 04 15 pm" src="https://user-images.githubusercontent.com/3952687/34546353-6645b388-f147-11e7-8c0e-5620b9cc5507.png">

**Comment by Durman** [comment]
@enzyme69 
[matrix_track_to_003_2018_01_05_14_23.gz](https://github.com/nortikin/sverchok/files/1606824/matrix_track_to_003_2018_01_05_14_23.gz)

![2018-01-05_18-24-22](https://user-images.githubusercontent.com/28003269/34613215-797c376a-f246-11e7-8e45-6aa52cd1682c.png)

It is easier to do it with `matrix normal` node:
#1377

**Comment by enzyme69** [comment]
Thanks @Durman ! I'll study this one.

**Comment by enzyme69** [comment]
<img width="997" alt="screen shot 2018-01-07 at 12 48 58 am" src="https://user-images.githubusercontent.com/3952687/34640331-a7dba51a-f344-11e7-9a4c-30804a998f4c.png">

https://gist.github.com/811cf2d4ba6dd3876946b5ecaa92e94b

Yes, interesting Matrix Normal node!
