### ISSUE TITLE
debugging gear_03a.blend by gritche from ba.com

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1865]
- first make a copy of the .blend so you can work on that instead of the main file.
- then cull the node tree of all nodes that do not directly contribute to the problem output.
- then reduce any parameters possible to obtain a result with less geometry, but that still shows the issue in the same form.
- then stick the indexviewer node on the output, and observe if there's any indices overlapping.

in your case. yes there is 

![image](https://user-images.githubusercontent.com/619340/32833575-931e738c-c9ff-11e7-881d-298e1d229b48.png)

- and start disconnecting in reverse order, start connecting the vdraw and indexviewer to nodes one step upwards and remove the nodes that you've disconnected.

![image](https://user-images.githubusercontent.com/619340/32833878-b6e0da98-ca00-11e7-88b6-8f55ac61de9f.png)

i'm not sure where that extra vertex comes from, but you are mirroring stuff so if there's an 'off-by-one' it might be that the mirror operation is swallowing a vertex you aren't expecting it to. 

Simplify your geometry the moment you can't figure out the results.

**Comment by zeffii** [comment]
when you do a join on the Matrix Apply output, you'll see a lot of duplicate location vertices..
![image](https://user-images.githubusercontent.com/619340/32834134-bd8e2dea-ca01-11e7-8a65-7a26bc692e08.png)

You seem relatively comfortable with transformation and matrix/vector math, and I'm pretty sure you'll end up with a much less complicated node tree eventually. Unfortunately I don't have time today.

**Comment by nortikin** [comment]
matrix error
it appears to be the same vector of rotation and vector to rotate to.
So deviation making error.
![gear_03a](https://user-images.githubusercontent.com/5783432/32841876-a287ab36-ca2c-11e7-91b7-bc31c43aa955.png)

**Comment by nortikin** [comment]
lets make an other order of matrix deform operations. So we will get
![gear_04a](https://user-images.githubusercontent.com/5783432/32842179-74641ab8-ca2d-11e7-8f2d-96c2d46c282e.png)

**Comment by gritchiee** [comment]
39/5000
thank you for spending time on this
sadly i'm not so comfortable with transformation and matrix/vector math, and sometimes sverchok give me good headache^^

**Comment by zeffii** [comment]
@gritchiee One of my first contributions to Sverchok was a script node. Sometimes ideas can be much more succinctly stated in code than with nodes. I realize you aren't a python-eer yet, but the scripted node is designed to be easy to use and therefor has a relatively low barrier for new users.

##### scaling the vector..
![image](https://user-images.githubusercontent.com/619340/32885443-d012ff9c-cabd-11e7-9057-155e8cd3cbb5.png)

of course this can be expressed in nodes, and it's fine if you want to.. but for mechanical stuff i urge you to look at the supplied scripts in `sverchok/script_nodes/SNLite_templates/` especially `petal_sine.py`

##### adding a vector
![image](https://user-images.githubusercontent.com/619340/32885706-923d4fbe-cabe-11e7-87cb-0d9c197679c7.png)

##### adding nodes to get xy length of each vector (dropping z)
This allows you to adjust the z as a function of the xy..
![image](https://user-images.githubusercontent.com/619340/32886264-701d7808-cac0-11e7-9f15-f1ae099ecf8c.png)

https://gist.github.com/b753a957f7c74555682479cacb04bd6a

**Comment by zeffii** [comment]
@nortikin maybe all nodes that output matrices could have a 'sanitize matrix` switch in `buttons_ext` to deal with the issue of floating point precision threshold..

**Comment by nortikin** [comment]
there are some cases we can do nothing with presicion.
But yes, this is semi-solution maybe for first time

**Comment by nortikin** [comment]
[gear_03a_2017_11_19_11_07.zip](https://github.com/nortikin/sverchok/files/1485482/gear_03a_2017_11_19_11_07.zip)
![gear_05a](https://user-images.githubusercontent.com/5783432/32990051-ff610c90-cd32-11e7-8acf-b16922412233.png)
