### ISSUE TITLE
CSG Boolean issue

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#1872]
Hello, after reading some of the issues about this node there was something i wanted to point out.

When joining to simple meshes it seems to make the necessary horizontal "loop cuts" but fails on some of the vertical cuts, resulting in invisible holes that are very hard to fix with in sverchok.

![screen](https://user-images.githubusercontent.com/10011941/33206009-31fdc038-d109-11e7-971d-16fd7473a79e.png)
[CSGbooleanBug.zip](https://github.com/nortikin/sverchok/files/1501312/booleanBug.zip)
Is this fixable? do you know any workaround?

Thanks again for your work

**Comment by Kosvor2** [comment]
You can try remesh modifier on resulted object. This a shortcomings of algorithm used in this node: slowness, and not-watertight mesh.

**Comment by zeffii** [comment]
yes @vicdoval the implementation of the CSG is unsatisfactory in some cases. I mentioned to Blender developers sergey/ideasman for a bmesh operator for this stuff, two years ago. It's not something that should be implemented in Python at all... at all... at all.

My advice is to use more subdivisions in your box.. to give csg code a fighting chance :)

![image](https://user-images.githubusercontent.com/619340/33223952-1e4dafc4-d165-11e7-85fa-3d60a8a81d8f.png)

**Comment by vicdoval** [comment]
@Kosvor2  Yes, "remesh + decimate" can make the work but as you point it is superslow and geometry transforming, so it can't be kept inside a procedural tree. :)
And subdividing the mesh gives smaller holes but more polygons... @zeffii Did you make an official request? (I don't know if this is even possible) Maybe I could ask for it again if you point me where to do it.

I was thinking in a possible workaround: 
If the "Intersect Edges" could integrate polygons , by comparing the edges intersections with the polygons definitions, the "watertightness" problem could be solved..
Maybe this is to complicate to implement or to slow for python... but it could also solve another cases... (I usually place a "fill holes" after but in this case it would create interior faces and so..)

**Comment by zeffii** [comment]
The mailing list fun dev blender is where people tend to discuss requests or in irc blendercoders freenet. A bmesh ops is the sensible and most scripter friendly feature they could offer..

Someone could also have a long stare at our code..

**Comment by zeffii** [comment]
The CSG code is intended to be optically correct, not topologically watertight. But for best results it does expect a manifold Mesh to begin with. When using the iterated mode in CSG sooner or later the intermediate output will be non manifold (and in the next iteration that will be used as the input) and i'm surprised that that doesn't throw an error. Maybe you don't notice if it's just two objects going into the sockets.

There exist a scenario where two adjacent polygons may not be fully connected, yet be considered valid topology. Zero area holes is a real problem for optical CSG.

![image](https://user-images.githubusercontent.com/619340/33239276-88f90730-d29e-11e7-873f-f411bbdb95d9.png)

In the above illustration imagine polygon `0` is a true quad with indices `[0, 1, 3, 2]` and un-subdivided by the adjacent polygons `1` and `2`, which share vertex _2_ and _3_ with polygon `0` but have their own vertex (_6_) right on the edge of polygon `0`.  So.. between vertex `[2,6,3]` you'll get a zero area edgenet with edges `[[2,6],[6,3],[2,3]]` ..and while all of that is legal topology, is not manifold.

------------

it seems such a waste of time trying to implement this in Python when a "tested-by-millions" routine exists in bmesh land just waiting to be converted to a call like `bmesh.ops.boolean(bm, mode='JOIN')` . I understand they have other priorities and want to encourage people to contribute in these areas. If there weren't 10's of other things I should be doing instead of this, then of course i'd sink the time in.

**Comment by zeffii** [comment]
stuff like this:
![image](https://user-images.githubusercontent.com/619340/33239439-5e96bfec-d2a2-11e7-9099-054c4adc82b8.png)

just because there's a vertex doesn't mean the adjacent faces use that vertex..

**Comment by zeffii** [comment]
Am i right, is this what you mean?
![image](https://user-images.githubusercontent.com/619340/33240277-0cec26de-d2b4-11e7-97a9-97bff0ba1635.png)
The selected vertex is not attached to the top polygon? This is what i mean with optically correct (for rendering as a last stage).. not great if you want to further process the mesh.

**Comment by zeffii** [comment]
The selected vertex is part of polygon A and B but not C .
![image](https://user-images.githubusercontent.com/619340/33240311-75edcc78-d2b4-11e7-8089-f25d6c5959ad.png)

this is unfortunately a known issue.

**Comment by zeffii** [comment]
now! .. I _do_ think it might be possible to perform am _optional_ final cleanup step to help add verts and make the result manifold. That code can be heavily tested completely separate from the Boolean CSG node.

I think the algorithm might go like
```python
- get bmesh (or BVH) from CSG output
- make sets of all faces that are coplanar,
- further subdivide each set into adjacent islands
- all faces in each set of adjacent islands shall test 
     if any vertices are located on the edges of other members of the set
- the locations of new proposed vertices on existing edges will first
     be tracked `edge index, new vertex location on edge 
     (either as Vector or percentage between A-B of edge, 
     where A is the vertex with the lowest vertex index)
- finally, pass cut information to a edgesplit  bmesh.ops
- remove doubles
```
this does not take care of zero-area edge nets that might occur on extreme boundaries, which I imagine can occur but I have not seen in practice.

**Comment by zeffii** [comment]
optionally a final "dissolve faces" option for the adjacent coplanar faces

makes me wish I had more time to get back into C programming.. and do a whole bunch of sverchok in C.

**Comment by vicdoval** [comment]
It would be great to have this algorithm inside sverchok. Maybe it could be part of a "Clean Mesh" node that could include some other mesh cleaning algorithms (in the case there where some)... or it could be called something like "polygon welder"..

**Comment by zeffii** [comment]
@vicdoval  yes, agreed. The algorithm would be entirely modularized out of the csg node's core, and can be called by the node, and even be used as the basis of a dedicated node to do `polygon welding` as you call it. ( i like that name)

**Comment by zeffii** [comment]
"Smart Dissolve" node most likely.

**Comment by zeffii** [comment]
seen as the solution to this will lie in a new module detached from the CSG boolean node (initially) i'm going to close this issue, and start a `smart dissolve` issue soon to test some code.

**Comment by vicdoval** [comment]
By now,  inspired by Bool Tools and  this @enzyme69 [video](https://youtu.be/7sx9f9pH4eE),  I've reached a quite baroque method to use Blender internal Boolean system.   

```
Output the meshes with a BMesh Viewer.
Using and Exec Node:
   Hold everything under an Empty (to keep clean the Outliner)
   Assign and apply Boolean Modifiers
Using ID Out MK2 get back to Sverchok the mesh data
```
![sverchok_multiple_boolean](https://user-images.githubusercontent.com/10011941/33518702-e24141f4-d799-11e7-9bcb-9adda0473db8.png)

It gives nice results with the obvious computing limitations :)

[sverchok_execute_boolean.zip](https://github.com/nortikin/sverchok/files/1524065/sverchok_execute_boolean.zip)

**Comment by nortikin** [comment]
kek

**Comment by enzyme69** [comment]
Victor you inspired me! Whoa
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by vicdoval** [comment]
@zeffii  is this what we didn't have?
bpy.ops.mesh.intersect_boolean()
found at https://docs.blender.org/api/2.78a/bpy.ops.mesh.html

**Comment by zeffii** [comment]
admittedly the function signature would suggest that's what we want, but it's a `bpy.ops` which means setting objects to selected / active and a whole lot of tiptoeing around (maybe context hopping) -- we've removed all that from Sverchok.  We really need a bmesh.ops.boolean() that takes 2 bm, and potentially a 3rd bm to store the output in, and a param intersect/union/difference, tolerance.

**Comment by portnov** [comment]
@vicdoval not exactly. The thing is, `bpy.ops.mesh` things operate on meshes already present in scene (and available as `bpy.data....`). Sverchok, in most cases, does not deal with such objects. Instead, we use so-called BMesh API (https://docs.blender.org/api/blender_python_api_2_77_0/bmesh.ops.html?highlight=bmesh.ops#module-bmesh.ops). This allows us to have meshes as "pure pythonic" objects (you can, for example, create a mesh without actually adding it to scene, apply different methods like "smooth" or "subdivide", return resulting vertex coordinates as lists of numbers and dispose the mesh). And this bmesh thing, unfortunately, does not have boolean operations exposed as python API.

**Comment by vicdoval** [comment]
Thanks! I thought our wishes were already accomplished 🌈
