### ISSUE TITLE
search for unknown operator on unregistering

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#1877]
How to reproduce:
Go to Addons preferences and untick the checkbox for Sverchok.

Result:

search for unknown operator 'NODE_OT_sv_extra_search', 'NODE_OT_sv_extra_search'
search for unknown operator 'NODE_OT_sv_monad_expand', 'NODE_OT_sv_monad_expand'
search for unknown operator 'NODE_OT_sv_monad_enter', 'NODE_OT_sv_monad_enter'
search for unknown operator 'NODE_OT_sv_monad_from_selected', 'NODE_OT_sv_monad_from_selected'
search for unknown operator 'NODE_OT_sv_monad_from_selected', 'NODE_OT_sv_monad_from_selected'
search for unknown operator 'TEXT_OT_noderefresh_from_texteditor', 'TEXT_OT_noderefresh_from_texteditor'
search for unknown operator 'NODE_OT_sv_extra_search', 'NODE_OT_sv_extra_search'
search for unknown operator 'NODE_OT_sv_monad_expand', 'NODE_OT_sv_monad_expand'
search for unknown operator 'NODE_OT_sv_monad_enter', 'NODE_OT_sv_monad_enter'
search for unknown operator 'NODE_OT_sv_monad_from_selected', 'NODE_OT_sv_monad_from_selected'
search for unknown operator 'NODE_OT_sv_monad_from_selected', 'NODE_OT_sv_monad_from_selected'
search for unknown operator 'TEXT_OT_noderefresh_from_texteditor', 'TEXT_OT_noderefresh_from_texteditor'

**Comment by zeffii** [comment]
I'm not exactly certain the untick/tick was ever really flawless. we've avoided it for a long time..  i wouldn't worry about this. restarting Blender and enabling Sverchok is what we suggest in the readme.md already for this scenario..

**Comment by zeffii** [comment]
unticking should trigger an unregister to all keymap items, not sure why these wouldn't be unregistered.

**Comment by zeffii** [comment]
this sounds like the operators being unregistered before the keymap entries that reference the operators are removed.

**Comment by zeffii** [comment]
the `__init__.py` 's unregister would need to register the keymap removal first for all files that add keymaps, then proceed to normally unregister all files (skipping the now redundant keymap removal function calls...)

**Comment by zeffii** [comment]
the `__init__.py` 's unregister would need to call the keymap removal functions first for all files that add keymaps, then proceed to normally unregister all files (skipping the then redundant keymap removal function calls...)

**Comment by zeffii** [comment]
adressed here https://github.com/nortikin/sverchok/pull/1878
