### ISSUE TITLE
SV Raycaster node does not seem to work :(

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1879]
[ray_thing_008_failed_001_2017_11_28_11_25.zip](https://github.com/nortikin/sverchok/files/1509651/ray_thing_008_failed_001_2017_11_28_11_25.zip)
![screen shot 2017-11-28 at 22 24 59](https://user-images.githubusercontent.com/3952687/33317404-1b23b45a-d48b-11e7-9423-bc9ab7b942f8.png)

A while back ago, I made this setup:
https://github.com/enzyme69/blendersushi/issues/156

It works, but today I am reloading the example and wanted to raycast some points, it does not work anymore... not sure what is wrong.

But there is error message:
```
Node Raycaster had exception not enough values to unpack (expected 5, got 4)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/core/update_system.py", line 322, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.79/scripts/addons/sverchok-master/nodes/analyzer/raycaster_lite.py", line 58, in process
    L, N, I, D, S = self.outputs
Node Raycaster had exception not enough
```

**Comment by portnov** [comment]
Try to recreate this particular node.

**Comment by zeffii** [comment]
@enzyme69   count the number of output sockets on that node in your blend, then count the number of objects being unpacked _into_ in the line `L, N, I, D, S = self,outputs` .

your blend is storing a reference to an old version of that node, one that lacked an additional socket.

The full error is `Node Raycaster had exception not enough values to unpack (expected 5, got 4)`

**Comment by zeffii** [comment]
no code change needed, just delete the node and recreate it.
