### ISSUE TITLE
Text In node to read CSV strings

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1882]
for example a question from the Google+ community reader John Harvey shows this spreadsheet 
https://docs.google.com/spreadsheets/d/1qPdntD_avz1xMosDSkglt2QEU3bPO7rxYS9ns5ttADQ/edit?usp=sharing

```csv
Bump Rail Schedule,,,,,,
Type Mark,Type,Description,Count,Phase Created,Phase Demolished,Level
,,,,,,
A,Type A - 1000mm Length,Stainless Steel Bump Rail,425,New Construction,None,SVP Level 1
B,Type B - 750mm Length,Stainless Steel Bump Rail,161,New Construction,None,SVP Level 1
C,Type C - 500mm Length,Stainless Steel Bump Rail,96,New Construction,None,SVP Level 1
D,Type D - 250mm Length,Stainless Steel Bump Rail,31,New Construction,None,SVP Level 1
E,Type E - 250x250mm,Stainless Steel Bump Rail,68,New Construction,None,SVP Level 1
F,Type F - 250x360x250,Stainless Steel Bump Rail,7,New Construction,None,SVP Level 1
G,Type G - 400x250mm,Stainless Steel Bump Rail,43,New Construction,None,SVP Level 1
H,Type H - 250x400mm,Stainless Steel Bump Rail,43,New Construction,None,SVP Level 1
J,Type J - 350mm Length,Stainless Steel Bump Rail,44,New Construction,None,SVP Level 1
K,Type K - 350x250mm,Stainless Steel Bump Rail,12,New Construction,None,SVP Level 1
L,Type L - 250x350mm,Stainless Steel Bump Rail,5,New Construction,None,SVP Level 1
N,Type N - 750mm,Galvanised Steel Bump Rail,5,New Construction,None,SVP Level 1
P,Type P - 2000mm,Galvanised Steel Bump Rail,1,New Construction,None,SVP Level 1
Q,Type Q - 350x400mm,Galvanised Steel Bump Rail,1,New Construction,None,SVP Level 1
```

this reader asks how to import that and manipulate it within sverchok.

--------

We can suggest a few ways to get the data from the csv file state into separate sockets, to be processed through other nodes. Exactly what the datastream is used for is not the immediate concern.

**Comment by zeffii** [comment]
However. The current `Text In` node implementation doesn't generalize to all types of input files. Trying to load `Bump Rail Schedule - Bump Rail Schedule.csv` in particular results in no input data, because the code that parses the csv is not tailored to handle the input.

This means we'd write a bit of python to see what the code needs to do, and potentially include that in Text In node as a functionality, or create an additional CSV in node. Text In node is one of the older nodes, and deserve reconsideration.

**Comment by zeffii** [comment]
The node's code lives here https://github.com/nortikin/sverchok/blob/master/nodes/scene/text.py

while flicking through it i've noticed some code that won't work anymore because Blender has changed where it stores registered classes. Some fixes will be needed, existing / older blends that use this node may be unaffected.

**Comment by zeffii** [comment]
the code that makes your csv fail to load lies here
```python
            for j, name in enumerate(csv_data):
                try:
                    n = get_number(row[j])
                    csv_data[name].append(n)
                except (ValueError, IndexError):
                    pass  # discard strings other than first row

```
you alluded to it already, csv of string data is not supported out of the box in the csv mode of the Text In node. It's not a giant amount of work further generalize it..

**Comment by zeffii** [comment]
this doesn't work in the current release/master .

![image](https://user-images.githubusercontent.com/619340/33380244-ba4b7e0c-d51a-11e7-83fa-63db131d38d9.png)

https://github.com/nortikin/sverchok/pull/1883

**Comment by zeffii** [comment]
here it is using  the headers.. but you have to modify the csv's header manually a little bit.. to be a standard header. I really don't know why the google-doc exporter adds the header that way, it's maybe a convention i'm not aware of.

![image](https://user-images.githubusercontent.com/619340/33380476-804df3be-d51b-11e7-9051-5b3c258d6ef6.png)

**Comment by zeffii** [comment]
after which you will need some basic Python to decompose the content into something usable..
![image](https://user-images.githubusercontent.com/619340/33381266-c96700f2-d51d-11e7-9ebe-ddeb5c433d9f.png)

**Comment by zeffii** [comment]
and because there's no real sane way to predict in advance all the possible input types of CSV and conventions, you might end up making a dedicated parse instruction for a specific csv file and reuse/adapt it for other similar files.
```python
for item in V1[0]:
    if not 'x' in item:
        append(int(item.split('mm')[0]))
    elif item.count('x') == 2:
        append([int(i) for i in item.split('x')])
    elif item.count('x') == 1:
        items = item.replace('mm', '')
        vals = items.split('x')
        append([int(i) for i in vals])
```
![image](https://user-images.githubusercontent.com/619340/33382445-0d1eaf22-d521-11e7-950e-20449e1f07d1.png)

The formula node is handy for mixing raw python operations with the data that flows throw the node tree. Obviously, if you don't know much python this will be where you get stuck.

**Comment by zeffii** [comment]
i've commited this to master, it opens up some user defined parsing of the CSV filetype. enjoy... and learn Python :)

https://github.com/nortikin/sverchok/pull/1883

**Comment by johntedharvey** [comment]
Hi zeffii.
I'm the google+ user who posted the original query. Thanks for your work on this.

**Comment by zeffii** [comment]
@johntedharvey  welcome! hopefully this helps, it was a missing feature of the node and was lightweight to implement.  That being said, just because a node can read the csv data doesn't mean you'll be able to get sverchok to do anything useful with it unless you can express your expectations / hopes for importing the data.

We can give tips, and even help initially.
