### ISSUE TITLE
Sverchok connecting and meshing 2 different numbers of Vector Edges

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1887]
If I wanted to "loft" operation 2 mesh with different number of vertices... is this possible in Sverchok already in a simple way? Or we need to do list matching and face hole?

[different_point_2017_11_30_00_52.zip](https://github.com/nortikin/sverchok/files/1516136/different_point_2017_11_30_00_52.zip)

**Comment by enzyme69** [comment]
@nortikin Maybe UV connect can "blend" match different number of vertices?

**Comment by enzyme69** [comment]
Strange this is like dejavu.
[different_point_2017_11_30_01_10.zip](https://github.com/nortikin/sverchok/files/1516169/different_point_2017_11_30_01_10.zip)

![screen shot 2017-11-30 at 12 10 30](https://user-images.githubusercontent.com/3952687/33407893-7c590b2a-d5c7-11e7-8ddb-b37beac27464.png)

**Comment by enzyme69** [comment]
Nope, list match is a different thing....

![screen shot 2017-11-30 at 12 21 08](https://user-images.githubusercontent.com/3952687/33408157-fff0f992-d5c8-11e7-9f24-90e3a60f5ae7.png)
[different_point_2017_11_30_01_21.zip](https://github.com/nortikin/sverchok/files/1516211/different_point_2017_11_30_01_21.zip)


Bridge and lofting of two different number of mesh edge is still an unsolved problem.

**Comment by Durman** [comment]
just an idea

![2017-11-30_13-21-22](https://user-images.githubusercontent.com/28003269/33423203-9a0ee1d0-d5d1-11e7-8eb8-520d95a48058.png)
![2017-11-30_13-23-02](https://user-images.githubusercontent.com/28003269/33423212-9dd88050-d5d1-11e7-9e8e-e9b25a6395a5.png)

https://gist.github.com/8430f249a00a0be3480a86cd86179d97

**Comment by enzyme69** [comment]
@Durman At some point, I was thinking the same thing, maybe this will do for now, until the same thing arise in the future 👍  Thanks!

**Comment by enzyme69** [comment]
Wishlist: Bridge mesh node. <-- hard node to make?

**Comment by Durman** [comment]
May be this is also a suitable?
https://gist.github.com/835b78117697eddb876faa07f2761bae

![2017-11-30_14-23-19](https://user-images.githubusercontent.com/28003269/33426203-7719849c-d5da-11e7-9720-b848d64b1873.png)

**Comment by enzyme69** [comment]
@Durman Interesting! Although it does not bridge X number of points into Y directly, this one does try to vector interpolate the 2 shapes using new number of Z points... Thanks for helping with this, Durman!
