### ISSUE TITLE
Using numpy in sverchok

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1890]
In general, are there any objections to using numpy in sverchok nodes ?
I’m considering this module for the 4D math nodes I’m working on since I need a 5x5 matrix so that I can generate homogeneous matrices composing 4D TRS matrices. (mathutils only supports 3x3/4x4 matrices).

**Comment by zeffii** [comment]
No problem at all internally to a node. use of np is not uncommon. If you intend to output 5x5 matrices to a matrix socket then I don't think that is a great idea

**Comment by DolphinDream** [comment]
@zeffii Cool. numpy it is then. as far as the 5x5 matrices (or for that matter any N x N matrices) they need to be output / input somehow. I did not think the current matrix socket was appropriate. I can either (ab)use the strings socket or create a new socket type for N dimensional matrices. :)

**Comment by nortikin** [comment]
to make so we need write autoconvertions in matrices socket. but why? extra operations.
more of that, matrix socket is not so huge, we convert inside node if needed. most problems come with vertices operations.
