### ISSUE TITLE
cross-section and bisect generate bad fill intersections 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1891]
Btw, both cross-section and bisect seem to have problems intersecting suzzane .. (the oblique intersections seem to be fine)

https://gist.github.com/77d0dcdeafa12bab28424a8d353912e1

![sv-bisect-crosssection-bug](https://user-images.githubusercontent.com/2083719/33511117-66507756-d6e3-11e7-8120-4294bfc7a1d6.png)

**Comment by zeffii** [comment]
Nope, these node expect manifold input. Suzanne is not manifold.

**Comment by zeffii** [comment]
there's also some subtle self intersecting in the suzanne basemesh, this goes away when you subdiv it.
