### ISSUE TITLE
Exception after recent Merge (Affects nightly Blender 2.79 build users)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1895]
```python
Exception in module register(): '\\scripts\\addons_contrib\\sverchok\\__init__.py'
Traceback (most recent call last):
  File "\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
 
  File "\scripts\addons_contrib\sverchok\menu.py", line 194, in get_node_idname_for_operator
    rna = getattr(bpy.types, nodetype).bl_rna
AttributeError: 'RNA_Types' object has no attribute 'SvLineNodeMK2'
```

**Comment by zeffii** [comment]
since the registration changed in Blender (if using newer Blender versions 2.79 nightlies...) you can't access a node's class reference by doing `getattr(bpy.types, nodetype)` .  you have to use our lookup table instead.

**Comment by portnov** [comment]
Ah. I'm using 2.79 release version.

What is the "our lookup table"?

**Comment by portnov** [comment]
You mean sverchok.utils.get_node_class_reference? will try.

**Comment by zeffii** [comment]
`cls = get_node_class_reference(cls_bl_idname)`

it will work fine in release, but many people don't use release anymore - including us.

**Comment by zeffii** [comment]
Blender developers try to speed up the bpy.types lookups by removing as much as possible from being registered in that namespace by default. So we have to track our nodes manually using a lookup.

**Comment by portnov** [comment]
@zeffii 
Hmm. I changed this locally and now my code can't find registered node by bl_idname "NodeReroute". But I can't grep such node anywhere. What is going on? Is this some special node?

**Comment by zeffii** [comment]
yeah, that node is registered to bpy.types :)  i think.  it's the only node where this applies.

**Comment by zeffii** [comment]
it's not really a "node" as we would define it.

**Comment by portnov** [comment]
Then I'll add this exception directly to get_node_class_reference(). ok?

**Comment by zeffii** [comment]
yes please.

**Comment by portnov** [comment]
@zeffii 
Please test #1896. It works for me.

**Comment by zeffii** [comment]
i recon you should use a nightly build for testing too.

**Comment by portnov** [comment]
Well, will try :) 
But since blender api changes in nightly builds, we actually have to test both on nightly builds and on stable ones.

**Comment by portnov** [comment]
@zeffii 
I tried the nightly build (today's) and it started normally. When I tried to open a scene with ViewerText node, I got

location: <unknown location>:-1
search for unknown operator 'NODE_OT_sverchok_viewer_button', 'node.sverchok_viewer_button'
rna_uiItemO: operator missing srna 'node.sverchok_viewer_button'
/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/text/viewer_text_mk2.py:219
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/text/viewer_text_mk2.py", line 220, in draw_buttons
    do_text.nodename = self.name
AttributeError: 'NoneType' object has no attribute 'nodename'

But I can't reproduce this anymore :/ Now the scene opens correctly. Instead, when clicking on VIEW on ViewerText node in that scene, I receive

Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/text/viewer_text_mk2.py", line 58, in execute
    if isinstance(inputs['edg_pol'].other, bpy.types.StringsSocket):
AttributeError: 'RNA_Types' object has no attribute 'StringsSocket'

**Comment by zeffii** [comment]
uch...
```
if isinstance(inputs['edg_pol'].other, bpy.types.StringsSocket):
AttributeError: 'RNA_Types' object has no attribute 'StringsSocket'
```
is another place where the namespace `bpy.types` no longer contains `StringsSocket` we can instead obtain bl_idname

**Comment by portnov** [comment]
Can't we just refer to io it as sverchok.node_tree.StringsSocket instead?

**Comment by zeffii** [comment]
naw... bl_idname string value is fine..
see 
https://github.com/nortikin/sverchok/commit/15760ce5109c8f9a683235df606c1d8c14dfe401

**Comment by zeffii** [comment]
well you could use `sverchok.node_tree.StringsSocket` but to be constent why not use the simple property `.bl_idname`

**Comment by zeffii** [comment]
probably can remove these tests altogether
```python
if isinstance(inputs['vertices'].other, bpy.types.VerticesSocket):
if isinstance(inputs['edg_pol'].other, bpy.types.StringsSocket):
if isinstance(inputs['matrix'].other, bpy.types.MatrixSocket):
```

**Comment by zeffii** [comment]
but maybe that's better left for a different pullrequest. where we just rage thru all direct `bpy.types.*` in the code base and sanitize them.
