### ISSUE TITLE
Developing nodes with arbitrary number of input sockets

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1901]
What is the recommended approach for designing a node that has multiple numbers of sockets (created dynamically) similar to the List Join node? I’m considering extending the Matrix Math node to allow arbitrary number of matrices to be plugged into the node and be able to reorder them by disconnect and reconnect to other slots.

**Comment by zeffii** [comment]
there are several approaches..  List Join as you mention is one, but also ProfileNode employs it's own interpretation. and Formula Node

I can't recall any node having the ability to reorder its inputs (other than the Monad node... but that was necessary as a Meta device ). But -- this is merely my opinion -- i'm worried you are over implementing a feature that can be achieved by disconnecting a socket and sticking it where it should be (it will often beat clicking a socket-move-button until it is in the right spot... just move it directly).

**Comment by zeffii** [comment]
but I could imagine you might want a Flip button
```
A                            C
B           Flip             D
C                            A
D                            B
```

**Comment by zeffii** [comment]
but that wouldn't move the order of `self.sockets` on the node, rather reconnect the incoming sockets by disconnecting a socket and reconnecting it via script

**Comment by DolphinDream** [comment]
Manual disconnect and reconnect is what I had in mind. List join node seems to play well wit that.

**Comment by DolphinDream** [comment]
Here’s an example.. using the 4D Matrix Math node as a guinea pig :) 

I borrowed the code from multi_socket to get the multi socket going. I could have used the multi_socket itself, but I wanted my socket names to be labeled A, B, C, ... ,Z and also to keep my nodule color.

Btw, I wonder whether the unlinked sockets should be auto removed somehow.  They are useful to stay in place in order to rewire the inputs easier, but eventually they just hangout without any purpose taking up node space. Or perhaps is more trouble than its worth to solve this issue.

![sv-4dmatrixmath-demo1](https://user-images.githubusercontent.com/2083719/33640190-1678f092-d9fd-11e7-87d8-a35d5f43023b.gif)

**Comment by DolphinDream** [comment]
Same deal but with the 3D Matrix Math node. 
Say Hello to the multi socket matrix composition :) and goodbye to matrix composition spaghetti :) 

![sv-4dmatrixmath-demo2](https://user-images.githubusercontent.com/2083719/33642307-5bba8148-da07-11e7-8726-19d974ddd58b.gif)
