### ISSUE TITLE
Potential Bug with List Sum

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1906]
I am using @zeffii Dictionary Lookup setup from the other day. With tinkering I did manage to get list of values and I wanted to do List Sum, but I am getting weird error like below. Not sure why.

[sv_dictionary_lookup_003_2017_12_06_00_55.zip](https://github.com/nortikin/sverchok/files/1533487/sv_dictionary_lookup_003_2017_12_06_00_55.zip)
![screen shot 2017-12-06 at 11 55 06](https://user-images.githubusercontent.com/3952687/33638891-abac2c72-da7c-11e7-9e2b-0a18ad79538b.png)

Wonder why a single "banana" list sum always gives 30. Supposed to be 15.

**Comment by enzyme69** [comment]
![screen shot 2017-12-06 at 12 10 17](https://user-images.githubusercontent.com/3952687/33639247-72d14368-da7e-11e7-83fb-67438e5634b0.png)

**Comment by zeffii** [comment]
Ill look at your zip later, but it maybe due to the list repeater.

**Comment by enzyme69** [comment]
Thanks @zeffii I am looking at this: https://github.com/nortikin/sverchok/blob/master/nodes/list_main/func.py

But I am overwhelmed by the code.

**Comment by zeffii** [comment]
yeah, off the top of my head I can't say with certainty why List Math (Sum) mode behaves that way..
but it's probably the reason we have a dedicated List Sum node.
![image](https://user-images.githubusercontent.com/619340/33652610-62cb9c52-da6a-11e7-9d0d-5ed95a0dd6a8.png)

**Comment by zeffii** [comment]
but.. 
https://github.com/nortikin/sverchok/blob/6b8f9e346e3fa34f2f5848b1d1fb6bf6ea12ec83/nodes/list_main/func.py#L84-L87

especially line 85 gives a hint.

**Comment by zeffii** [comment]
it's not a bug.. it's a feature (in the truest sense)

**Comment by zeffii** [comment]
my issue with that is that if one of the sublists has only 1 item, it will always only be extended to 2 items by repeating its own `(data)` using `data.extend(data)`. i'd be happy to add a mode that does unmodified `sum`, like 'easy sum' or something.

**Comment by enzyme69** [comment]
Gotcha...! Interesting and I will remember this. Thanks Zeff!

**Comment by nortikin** [comment]
not so good for user...
