### ISSUE TITLE
Is Empty Out node only works for 1 Matrix?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1907]
I am checking SV Empty node... it seems to work only with 1 Matrix input? Wonder why?

![screen shot 2017-12-06 at 21 38 19](https://user-images.githubusercontent.com/3952687/33657555-cb104674-dacd-11e7-9e75-0da770af3a9c.png)

**Comment by zeffii** [comment]
yes

**Comment by zeffii** [comment]
Empty node's code is designed only for 1 empty. We could debate whether it should handle multiple empties. At the time of creation we decided it made sense to have a single `node <---> empty` link. And since we had little interaction with Scene Objects back then it didn't make much sense to support anything else.

**Comment by enzyme69** [comment]
![screen shot 2017-12-06 at 22 20 45](https://user-images.githubusercontent.com/3952687/33659283-c018b886-dad3-11e7-9f17-024819d1026a.png)

Yes somewhat Single Empty sadden me 🙄 unusual. Not very Sverchok node. It does not work inside Monad either.

But I can use Script Node for now.

**Comment by enzyme69** [comment]
![screen shot 2017-12-06 at 22 31 06](https://user-images.githubusercontent.com/3952687/33659684-37f94b12-dad5-11e7-87b6-a275919ecce4.png)

I see... this is somewhat reminds me of Maya and Houdini. Unusual node. @vicdoval wonder if this can magically works inside Monad.

**Comment by zeffii** [comment]
You should consider the Empty Node (and any variants of it) as similar to ViewerDraw or Bmesh nodes.. these are nodes that make no sense to have in a monad.  If you want to generate matrices to drive the Empties, then you could generate them in a monad... but don't put the Empty Node inside the monad.

**Comment by enzyme69** [comment]
Ok, my solution for now is to involve AN:
![screen shot 2017-12-06 at 22 58 21](https://user-images.githubusercontent.com/3952687/33660747-059076e2-dad9-11e7-9a60-0881467a689b.png)

Script Node Empty Out is still quite something.

Empty Out node designed like this is indeed different unusual. A different paradigm. It's almost asking for a different kind of Monad that can simply "wrap" all those Empty and then can perform Matrix.

**Comment by vicdoval** [comment]
I think a proper MK2 of this node should include:

- _The "hide button" and "Select Toggle" button (so useful when there are multiple elements created.)
- _Multiple Input matrix

I was trying to follow the Bmesh viewer to clone this features but the "empty out" does not have the same internal structure (no callback operator) so it was not as straight as would have liked... :)

@enzyme69  By now it can be a sad lonely Empty but it can be useful to handle hundreds of elements :D
![emptyout](https://user-images.githubusercontent.com/10011941/33660970-2801317e-da86-11e7-80b7-b3b44cd59bc8.png)

**Comment by zeffii** [comment]
ok// i might make a MK2, @vicdoval promise me you'll do a nice demo of it :)

**Comment by vicdoval** [comment]
:) The empty is finally a helper, I think everything you can do with an Empty it could be reproduced by a "one vertex" mesh (or anything not renderable) , just sometimes is nice to understand and to avoid confusion between helpers and real  geometries (as far as I know)
So for advanced of sverchok may not be a big deal,  but for the eventual user I think its pretty cool to be able to handle Emptys from SV.

In my case I use Emptys for parenting and to create Hooks . For both cases I could use a different mesh, but if you do the MK2 i'll try to push a demo to it's best :)
