### ISSUE TITLE
Parenting Empty to Empty

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1908]
![screen shot 2017-12-07 at 11 18 44](https://user-images.githubusercontent.com/3952687/33692256-746d4e3e-db40-11e7-8f40-9902e4d4c336.png)

[parenting_empty_001_2017_12_07_00_19.zip](https://github.com/nortikin/sverchok/files/1537328/parenting_empty_001_2017_12_07_00_19.zip)
![screen shot 2017-12-07 at 11 18 44](https://user-images.githubusercontent.com/3952687/33692267-82cb8932-db40-11e7-9657-fc6fe5aaf5fe.png)

@vicdoval The other day you showed me something new that we can use Object ID Set and "parent" to link objects easily.

I am trying to do this using multiple empty, hoping to easily create like Sun and Planets simulation.

Somewhat I am not getting the result I was expecting. Wonder if this is a limitation or is there a way around it?

If I make my own empty objects in 3D, offset them, I can actually parent to Sv Empty and they will rotate and behave like normal parent-child relationship.

Any tips on this?

Also btw, Empty node maybe needs option to have different type of Views? And also option for Size? Although this is of course something that we can use Object ID set is for...

![screen shot 2017-12-07 at 11 21 31](https://user-images.githubusercontent.com/3952687/33692317-d50c85c0-db40-11e7-9e31-9ff432f53a62.png)

![screen shot 2017-12-07 at 11 25 23](https://user-images.githubusercontent.com/3952687/33692426-5ac22be8-db41-11e7-8632-bd31ecd991bc.png)

**Comment by enzyme69** [comment]
Current behaviour of parenting empty:
![empty_parenting](https://user-images.githubusercontent.com/3952687/33692412-43ab3116-db41-11e7-825b-57f7d4881bce.gif)

**Comment by enzyme69** [comment]
Oh! So we need to "Apply Matrix" first?
![screen shot 2017-12-07 at 11 31 04](https://user-images.githubusercontent.com/3952687/33692599-221f6566-db42-11e7-93e0-4d3a90340e56.png)

**Comment by enzyme69** [comment]
Actually... still not quite right...
[empty_parenting_002_2017_12_07_00_34.zip](https://github.com/nortikin/sverchok/files/1537351/empty_parenting_002_2017_12_07_00_34.zip)

**Comment by zeffii** [comment]
_a side remark.._

I suspect setting the Parent via the Object ID Set node is not a great idea - ofcourse it works, but it can and will keep resetting the parent on every update, even if the parent is already set to the proposed value/object. There's no clever testing in the node whether or not the parent needs to be reassigned.

maybe a dedicated parenting node is also not a bad idea, with a mode to clear all `obj.parent` in the incoming objects lists. (un-parent)

**Comment by enzyme69** [comment]
Matrix is a mystery. I used to think "parenting" is multiplying one matrix with another. But not as clear.

I was surprised that we can use Object ID parent but the effect is somewhat also unexpected on those Empty node.

**Comment by vicdoval** [comment]
I see what you mean @enzyme69, i think using this method uses some "keep transform" that translates the input coordinates to the coordinates it should have inside de "Empty coord system"..
Indeed looks strange... 
Probably a Parenting Node that can handle this would make sense in the best of the futures... :)

To avoid the permanent update this script can be used in an Exec Node:


```
for ob in V1:
    p= ob.parent
    if p == V2[0]:
        continue
    else:
        ob.parent=V2[0]

```
But this does not solve the position problems :)

**Comment by enzyme69** [comment]
Ok.. seems too complicated for me for now. I still am not sure how Sverchok can make orbiting planet animation.

**Comment by enzyme69** [comment]
Thanks for explanation u'all~

**Comment by enzyme69** [comment]
Matrix Apply maybe kind of does the job, maybe.
[sverchok_matrix_planet_001_2017_12_07_12_18.zip](https://github.com/nortikin/sverchok/files/1539000/sverchok_matrix_planet_001_2017_12_07_12_18.zip)
![screen shot 2017-12-07 at 23 18 33](https://user-images.githubusercontent.com/3952687/33714991-1e086ea6-dba5-11e7-96ea-48f227833c20.png)

**Comment by enzyme69** [comment]
I am probably mixing Parent-Child and Position/Rotation Constraints via Matrix here. But will come back to this in the future.
