### ISSUE TITLE
Bmesh functions in extrude_separate.py

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1910]
There are linear and cubic complexity of some function. The Analyzing function usually use the cubic complexity. I noticed that `bmesh.ops.scale` and `bmesh.ops.translate` have the cubic complexity without any reason for it. It have became apparently after I tried to extrude many thousands of faces. I don't know why it has that behavior but I think if rewright this to Python, this function will become faster.
Test for 10 faces.
![2017-12-07_14-18-36](https://user-images.githubusercontent.com/28003269/33710368-be058fb6-db59-11e7-87d6-3727e4c7cc53.png)
Test for 100 faces.
![2017-12-07_14-20-45](https://user-images.githubusercontent.com/28003269/33710435-f580c906-db59-11e7-9815-43fd5b6879ef.png)
Test for 1000 faces.
![2017-12-07_14-22-18](https://user-images.githubusercontent.com/28003269/33710454-0d9c4c2c-db5a-11e7-87f9-fffbe55db2ae.png)
Test for 10000 faces.
![2017-12-07_14-23-34](https://user-images.githubusercontent.com/28003269/33710520-410bcef2-db5a-11e7-809f-a847e5b937be.png)
You can see that, that the more faces in object the much time  function take per face. So it is very weird.
And there is no problem if object will be broken into faces.

**Comment by zeffii** [comment]
yep. a very similar node is "Inset Specials" and it is dramatically faster.

**Comment by zeffii** [comment]
see: https://github.com/nortikin/sverchok/issues/1488

**Comment by zeffii** [comment]
I will gladly accept a PR to speed up this node.

**Comment by portnov** [comment]
@Durman Do you mean that blender's internal methods are slow? Or slow is some part of our Python "glue" around them?
It would surprise me if it is possible to rewrite bmesh operations in python faster than they are (implemented in C).

**Comment by portnov** [comment]
Also, if some of bmesh operations are really so slow, it desires a bugreport to blender.

**Comment by zeffii** [comment]
hmm..
https://github.com/dfelinto/blender/blob/1d33843ea6b128242183bb31804474019c606a9d/source/blender/bmesh/operators/bmo_utils.c#L74-L98

and
https://github.com/dfelinto/blender/blob/1d33843ea6b128242183bb31804474019c606a9d/source/blender/bmesh/intern/bmesh_opdefines.c#L758-L795

**Comment by zeffii** [comment]
perhaps the overhead of the function call (1) and the standard processing done in each function call (2) combined. 

for example 
1) calling the function on all the verts of a bm individually, 
2) vs calling it on all verts by passing it the list of verts.

The difference being that you have no way to pass a unique matrix to the second example.

**Comment by Durman** [comment]
@portnov 
> Do you mean that blender's internal methods are slow? Or slow is some part of our Python "glue" around them?

I can only suggest that every time there is search of face in bmesh and the more bmesh the more time it takes for serching.
```Python
bmesh.ops.scale(bm, vec=vec, space=m, verts=face.verts)
```

**Comment by Durman** [comment]
And I measured speed only for 2 strings in code.
https://github.com/nortikin/sverchok/blob/37f0f1ce5f47af4d0792b62b6a3e867b2ca8fc3f/nodes/modifier_change/extrude_separate.py#L137-L139

**Comment by Durman** [comment]
I have made a proposal about the problem in Blender community. Voting is not forbidden.))
https://blender.community/c/rightclickselect/vbfbbc/

**Comment by Durman** [comment]
https://devtalk.blender.org/t/performance-of-bmesh-operators-with-multiple-input-values/10909
