### ISSUE TITLE
Bending Mesh Along Surface on Hexa Grid possible bug 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1912]
@portnov  I am testing BAS node and ~somewhat~ my hexa grid is missing a single polygon info:

[bend_along_surface_005_2017_12_08_00_14.zip](https://github.com/nortikin/sverchok/files/1541016/bend_along_surface_005_2017_12_08_00_14.zip)
![screen shot 2017-12-08 at 11 14 23](https://user-images.githubusercontent.com/3952687/33745106-0a4baba8-dc09-11e7-80fb-a76257edc405.png)

Any idea why?

**Comment by portnov** [comment]
Interesting. The problem appears only with Linear interpolation:
geom.py:752: RuntimeWarning: invalid value encountered in true_divide
  n = n / np.linalg.norm(n)

will check.

With Cubic interpolation everything seems to work ok.
