### ISSUE TITLE
Line into face in 2D space.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1914]
I want to create algorithm that will add thickness for lines in 2D. It absents in Sverchek as I know. I imagine like this:
![2017-12-08_12-57-01](https://user-images.githubusercontent.com/28003269/33758468-c7cf63b4-dc17-11e7-8985-59bf9a4d6cc6.png)
I think Initially it is necessary to start from an analyze and understand how many neighbors have each point also it is necessary to counting angles between edges. After that it is possible to start a bypass around the mesh by edges. 
For first variant the pass will be 01,10 ; second 01,12,21,13,31,10, third 02,21,13,30 and 03,31,12,20.
![2017-12-08_13-29-57](https://user-images.githubusercontent.com/28003269/33759473-e67d11d6-dc1b-11e7-9eb4-bf9209ea2870.png)
For measurement angles it is better to use[ angle_signed](https://docs.blender.org/api/blender_python_api_2_78c_release/mathutils.html#mathutils.Vector.angle_signed). It have unique values for all 360 degrees.

**Comment by zeffii** [comment]
it's difficult :)  especially for more interesting edge-nets  

https://github.com/nortikin/sverchok/issues/623 i never got to the end of it.

**Comment by Durman** [comment]
@zeffii 
Either way I'll take a try and I'll write my experience here.

**Comment by enzyme69** [comment]
A silhouette of 3D shapes is also hard I think.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by Durman** [comment]
I already have some result. )

![lit to plan](https://user-images.githubusercontent.com/28003269/33798360-53229bb6-dd30-11e7-8383-d7fa3e3b4cc5.gif)

**Comment by Durman** [comment]
I have finished. It is ready for testing. I have done it for SLnode.
[line to face2.zip](https://github.com/nortikin/sverchok/files/1545327/line.to.face2.zip)
```Python
"""
in verts_in v d=[] n=1
in edges_in s d=[] n=1
in shift s d=1.0 n=2
out verts_out v
out edges_out s
"""
from mathutils import Vector, Matrix
from math import radians, pi, sin

verts_in = [Vector(v).to_2d() for v in verts_in]

#Searching neighbours for each point
neighbours = [[] for _ in range(len(verts_in))]
for edg in edges_in:
    neighbours[edg[0]].append(edg)
    neighbours[edg[1]].append(edg)

#Convert to from 0 to 2pi angle
def calc_angle(p1,p2):
    angle = p1.angle_signed(p2)
    if angle < 0:
        angle += 2*pi
    return angle

#Sorting neighbours by hour hand
for i, p_neighbs in enumerate(neighbours):
    if len(p_neighbs) != 1:
        angles = [0]
        first_item = list(set(p_neighbs[0]) - set([i]))[0]
        for another_neighb in p_neighbs[1:]:            
            second_item = list(set(another_neighb) - set([i]))[0]
            vector1 = verts_in[first_item] - verts_in[i]
            vector2 = verts_in[second_item] - verts_in[i]
            angles.append(calc_angle(vector1, vector2))
        sorted = list(zip(angles, p_neighbs))
        sorted.sort()
        neighbours[i] = [e[1] for e in sorted]

def get_end_points(item_point):
    second_item = list(set(neighbours[item_point][0]) - set([item_point]))[0]
    vert_edg = verts_in[item_point] - verts_in[second_item]
    mat_r1 = Matrix.Rotation(radians(-45),2,'X')
    mat_r2 = Matrix.Rotation(radians(45),2,'X')
    vert_new1 = (vert_edg * mat_r1).normalized() * shift/sin(radians(45)) + verts_in[item_point]
    vert_new2 = (vert_edg * mat_r2).normalized() * shift/sin(radians(45)) + verts_in[item_point]
    return [vert_new1,vert_new2]

def get_middle_points(item_point):
    points = []
    for i in range(len(neighbours[item_point])):
        current_edges = (neighbours[item_point][i:] + neighbours[item_point][:i])[:2]
        second_item1 = list(set(current_edges[0]) - set([item_point]))[0]
        second_item2 = list(set(current_edges[1]) - set([item_point]))[0]
        vert_edg1 = verts_in[second_item1] - verts_in[item_point]
        vert_edg2 = verts_in[second_item2] - verts_in[item_point]
        angle = calc_angle(vert_edg1, vert_edg2) / 2
        mat_r = Matrix.Rotation(angle, 2, 'X')        
        points.append((vert_edg1 * mat_r).normalized() * shift/sin(angle) + verts_in[item_point])
    return points

#Seting points
findex_new_points = [0]
for i in range(len(verts_in)):
    if len(neighbours[i]) == 1:
        verts_out.extend(get_end_points(i))
        findex_new_points.append(findex_new_points[-1] + 2)
    else:
        p = get_middle_points(i)
        verts_out.extend(p)
        findex_new_points.append(findex_new_points[-1] + len(p))
        
findex_new_points = findex_new_points[:-1]
        
#Creating faces
current_index = len(verts_out) - 1
position_old_points = [0 for _ in range(len(verts_out))]
for edg in edges_in:
    need_points = []
    for i in edg:
        if len(neighbours[i]) <= 2:
            need_points.extend([findex_new_points[i], findex_new_points[i] + 1])
        else:
            position = neighbours[i].index(edg)
            nomber_points = len(neighbours[i])
            variants_positions = list(range(findex_new_points[i], findex_new_points[i] + nomber_points))
            need_points.extend((variants_positions[position - 1:] + variants_positions[:position - 1])[:2])
    
    vec_edg = verts_in[edg[0]] - verts_in[edg[1]]
    vec_1 = verts_out[need_points[0]] - verts_in[edg[0]]
    vec_2 = verts_out[need_points[1]] - verts_in[edg[0]]
    vec_3 = verts_out[need_points[2]] - verts_in[edg[1]]
    vec_4 = verts_out[need_points[3]] - verts_in[edg[1]]
    new_vecs = [vec_1, vec_2, vec_3, vec_4]

    angles = []
    for vec in new_vecs:
        angles.append(vec_edg.angle_signed(vec))

    if angles[0] < 0 and angles[2] < 0 or angles[0] >= 0 and angles[2] >= 0:
        new_edges = [need_points[0],need_points[2],need_points[3],need_points[1]]
    else:
        new_edges = [need_points[0],need_points[3],need_points[2],need_points[1]]
    
    if len(neighbours[edg[0]]) > 2:
        if position_old_points[edg[0]] == 0:
            verts_out.append(verts_in[edg[0]])
            current_index += 1
            position_old_points[edg[0]] = current_index
        new_edges.append(position_old_points[edg[0]])
        
    if len(neighbours[edg[1]]) > 2:
        if position_old_points[edg[1]] == 0:
            verts_out.append(verts_in[edg[1]])
            current_index += 1
            position_old_points[edg[1]] = current_index
        new_edges.insert(2, position_old_points[edg[1]])
        
    edges_out.append(new_edges)    
    
verts_out = [[i.to_3d()[:] for i in verts_out]]
```

**Comment by portnov** [comment]
Very cool. Just I see some troubles with normals in that file.

**Comment by Durman** [comment]
@portnov 
Indeed, I'll fix.
![2017-12-10_09-37-15](https://user-images.githubusercontent.com/28003269/33802354-c37b6c2c-dd8e-11e7-85a8-ba8f834bfa8b.png)

**Comment by Durman** [comment]
I have fixed code above. It will have to be alright with normals now.

**Comment by zeffii** [comment]
we will move this into a dedicated node, it's pretty neat @Durman

**Comment by zeffii** [comment]
(when you are happy with it of course)

maybe a few modifications like...
```diff
- neighbours = [[] for _ in range(len(verts_in))]
+ neighbours = [[] for _ in verts_in]



-    angles = []
-    for vec in new_vecs:
-        angles.append(vec_edg.angle_signed(vec))
+    angles = [vec_edg.angle_signed(vec) for vec in new_vecs]
```

**Comment by zeffii** [comment]
maybe
```diff
#Convert to from 0 to 2pi angle
def calc_angle(p1,p2):
    angle = p1.angle_signed(p2)
-   if angle < 0:
-       angle += 2*pi
-   return angle

+   return (angle + 2PI) if angle < 0 else angle
```

**Comment by zeffii** [comment]
but.. that's up to you. it's more important that it works for now :)

**Comment by zeffii** [comment]
very nice work indeed, @Durman !

**Comment by enzyme69** [comment]
In the past, I would probably use Skin Modifier, flattened. This is quite
something that has been in my wishlist for years.

**Comment by nortikin** [comment]
is it in master?

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/line2face.py
ok, pasted

**Comment by portnov** [comment]
Maybe this deserves to be a proper node?

**Comment by nortikin** [comment]
ofcourse

**Comment by Durman** [comment]
@zeffii 
> maybe a few modifications like...

Of course I'll fix it, thank you for teaching. I write longer than it is necessary sometimes for more understanding what it happens in my script.

I'll try to add more features for this node.

**Comment by Durman** [comment]
I think to add a feature that will unite faces into one face like fill function in Blender. 
First all faces are sorted contra clockwise. If we want to unite faces `[01234]` and `[15672]` we have to paste `[567]` between `[12]` of first face and we will receive `[01567234]`. There is equal behavior for all faces with one common edge.
There are situation we have two common edge `[13],...[67]` and gaps `[4,5]` between them. It show us that we met loop.
![2017-12-11_11-21-25](https://user-images.githubusercontent.com/28003269/33820018-b8d9c902-de66-11e7-8f6c-19c76f475993.png)

**Comment by zeffii** [comment]
@Durman there's a bmesh operation for limited dissolve, which you _could_ use. But I understand that you might want to add your own interpretation..

**Comment by Durman** [comment]
@zeffii 
I know but I don't like how this function fills holes and I'll receive more control with my function although it will work less quickly.

**Comment by zeffii** [comment]
that's OK. i understand perfectly.

**Comment by Durman** [comment]
Already it works but not loops yet.

![2017-12-12_09-47-38](https://user-images.githubusercontent.com/28003269/33869357-b4fcd246-df21-11e7-9cb4-563d369250f9.png)

**Comment by zeffii** [comment]
instant go-cart track creator : )

**Comment by Durman** [comment]
Sheet of paper is best the interpreter: )

![doc00013320171212090251_001](https://user-images.githubusercontent.com/28003269/33876145-12f8f750-df3e-11e7-86de-c1bba0217543.jpg)

**Comment by Durman** [comment]
Also algorithm like this is useful for creating roofs.

![2017-12-14_16-23-21](https://user-images.githubusercontent.com/28003269/33992210-253be02c-e0eb-11e7-9fca-e5cb46e380cb.png)

**Comment by enzyme69** [comment]
At this stage, we should already have nodes for generating
- railway track
- roller coaster
- tunnel
- bridge
- houses like above
- ferris wheel
- Amsterdam wind turbin
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by Durman** [comment]
@enzyme69 The sound's great. )))

**Comment by enzyme69** [comment]
@Durman What is the name of this algorithm / script / node you made, is this in the latest SV now? Btw check also the Maze generator by Elfnor, it generates Edges, and perfect to use with your Edge to Face node.

**Comment by enzyme69** [comment]
Bend along Curve can do it for a single line edge:
![screen shot 2017-12-17 at 22 49 11](https://user-images.githubusercontent.com/3952687/34079186-87bfc694-e37c-11e7-9f4e-381e0527e77c.png)
[bend_along_path_002_2017_12_17_11_49.zip](https://github.com/nortikin/sverchok/files/1565592/bend_along_path_002_2017_12_17_11_49.zip)

I supposed your one can do branching.

**Comment by Durman** [comment]
@enzyme69 
The name is line to face or may an offset of line. I also made something like offset for line. I study how to make a normal node in Sverchok.

**Comment by zeffii** [comment]
how about "2D Line thickness", as might be expected from a vector drafting tool. I understand what you mean by "line to face", but i find it minimally descriptive. "Line Offset/Outset" would also be reasonable.

**Comment by Durman** [comment]
@zeffii 
```Python
class SvOffsetLineNode(bpy.types.Node, SverchCustomTreeNode):
    ''' Doing offset of line '''
    bl_idname = 'SvOffsetLineNode'
    bl_label = 'Offset line'
    bl_icon = 'OUTLINER_OB_EMPTY'
```

**Comment by zeffii** [comment]
@Durman  cool!  small suggestion; we now use the class docstring for search keyword and menu tooltip , so use this format:
```python
class SvOffsetLineNode(bpy.types.Node, SverchCustomTreeNode):
    """
    Triggers: Offset Line 2D
    Tooltip: Offsetting a Line into 2D space

    Any additional information here, using a separator space.
    """
    bl_idname = 'SvOffsetLineNode'
    bl_label = 'Offset line'
    bl_icon = 'OUTLINER_OB_EMPTY'
```

**Comment by Durman** [comment]
Creating windows ))

![windows macker](https://user-images.githubusercontent.com/28003269/34141592-b2883fc6-e49b-11e7-971a-636707466a24.gif)
![2017-12-19_09-06-40](https://user-images.githubusercontent.com/28003269/34141658-0bfa5472-e49c-11e7-8a6e-131b68b906cc.png)

**Comment by enzyme69** [comment]
That's nice and I will study this and perhaps also Live Noding it. Thanks
for example Durman!

**Comment by Durman** [comment]
Now node available from Alpha menu. Here is short [documentation](https://github.com/nortikin/sverchok/blob/master/docs/nodes/alpha_nodes/offset_line.rst).

**Comment by enzyme69** [comment]
@Durman Thanks Durman this node is really awesome, I have wished a very long time to have such node! Although it works in XY only, but together with projection from camera angle, maybe can be interesting.

**Comment by enzyme69** [comment]
<img width="781" alt="screen shot 2018-01-08 at 11 48 49 pm" src="https://user-images.githubusercontent.com/3952687/34671391-807d16a8-f4ce-11e7-83cd-983e2081a25f.png">

**Comment by Durman** [comment]
Rotation of worker surface of offset node:
[2018_01_15_12_40.gz](https://github.com/nortikin/sverchok/files/1631640/2018_01_15_12_40.gz)

![2018-01-15_16-36-21](https://user-images.githubusercontent.com/28003269/34942923-e33d9efe-fa12-11e7-8562-911a0fa889da.png)
![offset line](https://user-images.githubusercontent.com/28003269/34942930-e9350c34-fa12-11e7-8339-316310512af6.gif)
