### ISSUE TITLE
Monad crashing blender on SvNoDataError exception

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1918]
In current master branch.. if i disconnect a vector input from a modad blender crashes with the following error. Try to delete a vector node connecting to the monad and undo a few times until it (hopefully) you get it to crash.

https://gist.github.com/cda35a4ae53012f63b7b61fdc035c990

```
2017-12-08 19:40:35,091 [ERROR] sverchok.core.update_system: Node Monad had exception: No data passed into socket `Location'
Traceback (most recent call last):
  File "/scripts/addons/sverchok/core/update_system.py", line 323, in do_update_general
    node.process()
  File "/scripts/addons/sverchok/core/monad.py", line 462, in process
    data = socket.sv_get(deepcopy=False)
  File "/scripts/addons/sverchok/node_tree.py", line 297, in sv_get
    raise SvNoDataError(self)
sverchok.core.socket_data.SvNoDataError: No data passed into socket `Location'


Writing: /tmp/monadBug.crash.txt
Segmentation fault: 11
```

![screen shot 2017-12-08 at 7 40 14 pm](https://user-images.githubusercontent.com/2083719/33790639-eca19c60-dc4f-11e7-8da1-95072570a058.png)
![screen shot 2017-12-08 at 7 40 06 pm](https://user-images.githubusercontent.com/2083719/33790640-ecb0535e-dc4f-11e7-8e90-1c7ca24136b1.png)

Note the monad is stuck for some reason in orange land even though everything is connected. The same crash happens btw even if i start from scratch to get a monad that is not orange (which i suspect has to do to something not updating properly)

**Comment by DolphinDream** [comment]
I assume the Monad handles the no data exception,  but perhaps it doesn’t do it quite right.

**Comment by DolphinDream** [comment]
Also, in the context of the decision to raise exception for no data instead of returning implicit default value.. what happens if the input of a monad comes from a node that has an explicit default value inside the monad. Does the monad propagate that setting to the newly created input socket? or does it always require socket to be connected or else it would result in a no data exception ?

**Comment by zeffii** [comment]
Ouch.. segmentation fault. Well well well. We'll have to operate.

**Comment by portnov** [comment]
I saw similar symptoms a couple of times. For me, it does not reproduce each time.  I don't think it has something to do with our code, most probably the bug is in blender somewhere.

**Comment by zeffii** [comment]
if it's reproducable, i would track back to see where it became less stable
- was it the addition of `SvNodDataError(self)`
- was it the move to the logging module
- was it always kind of broken this way.
- are properties being accessed that don't exist?

the `bpy` can be crashed easily. While i'd like to investigate the sverchok element of this, because Blender isn't often the real culprit (but it's hard to entirely exclude it.. and what if it happens mostly on certain architecture... what then? )

**Comment by zeffii** [comment]
also i'd like to point you to https://github.com/nortikin/sverchok/issues/1619 the last issue.

**Comment by zeffii** [comment]
additionally, the matrix_in node is perhaps underspecified..

https://github.com/nortikin/sverchok/blob/a5e113f65581e4347752be70e80845bca1325303/nodes/matrix/matrix_in_mk2.py#L62-L64

**Comment by zeffii** [comment]
if we do a grep for `.sv_get() ` we'll find many instances (indeed a vast majority) of the process functions having additional code at later stages that handles the unconnected scenario.

**Comment by zeffii** [comment]
maybe stick a fair set of try/except in the various process functions in 
https://github.com/nortikin/sverchok/blob/master/core/monad.py

**Comment by portnov** [comment]
I very much doubt that python's try/catch can catch C-level segfault :)

**Comment by zeffii** [comment]
the update system is responsible for updating the color when a node fails to update

https://github.com/nortikin/sverchok/blob/f0d664da335fb73c61367f0e553363cf1a30bc2b/core/update_system.py#L35-L42

**Comment by portnov** [comment]
@DolphinDream  do you have stack from txt file that blender produces on crash?

**Comment by zeffii** [comment]
>  I very much doubt that python's try/catch can catch C-level segfault :)

you're probably right.  that being said, there's clutter in the monad/update system/exception handling that may exacerbate the issue.

**Comment by DolphinDream** [comment]
Here’s the blender crash file. I use the same gist as above and did the following in a newly started blender session: import the SV gist, delete the first vector node, undo, and delete the same node again... blender crashes.

[blender.crash.txt](https://github.com/nortikin/sverchok/files/1544778/blender.crash.txt)

**Comment by zeffii** [comment]
i can reproduce that crash too.

**Comment by portnov** [comment]
Reproduces for me too.
Okay, this seems to have something with logging to internal text buffer... :(

**Comment by portnov** [comment]
@DolphinDream @zeffii  what OS/distros are you running? I'm using Debian testing/unstable.

**Comment by portnov** [comment]
"Haha". On machine with ubuntu I got "Attempt to free NULL pointer" and hang with 100% CPU usage instead of crash. Will try again.

**Comment by portnov** [comment]
That reproduces too.

**Comment by DolphinDream** [comment]
I got that free NULL pointer too sometimes and had blender actually stuck instead of crashing. I have Macosx 64bit

**Comment by portnov** [comment]
I have a rough idea of what's going on. Try to reproduce the same scenario when you have blender's text frame sverchok.log opened. You will see that when you heat Ctrl-Z, the record with exception disappears from log. It seems blender is trying to undo all changes done by deleting the node, including writing to text buffer. I'm not sure if this is good idea but... And when you do the same for the second time some conflict occurs...

**Comment by portnov** [comment]
https://blenderartists.org/forum/showthread.php?259074-Undoing-something-in-3D-view-undoes-progress-in-text-editor-help

**Comment by portnov** [comment]
https://gist.github.com/portnov/d9f5cab6188fa1b8d32b64f742c9087d simple script that reproduces the same bug.

**Comment by zeffii** [comment]
@portnov   Win10 x64

**Comment by portnov** [comment]
Well. https://developer.blender.org/T53530 .

**Comment by portnov** [comment]
#1921 - this helped for me.

**Comment by zeffii** [comment]
tested `1918_fix` and indeed no crash.

**Comment by DolphinDream** [comment]
That seems to fix the crash for me too.

**Comment by portnov** [comment]
Good.

**Comment by portnov** [comment]
@DolphinDream @zeffii FYI, main points from T53530:
* Undo invalidates all python insances of any bpy objects. So it is required to do not store such references for long in python code, instead it is required to fetch them (via bpy.data.some[name]) each time we need it. Link: https://docs.blender.org/api/master/info_gotcha.html#undo-redo
* The fact that any undo undoes something in text editor is known and put onto todo list.

**Comment by zeffii** [comment]
passing around bpy.data.objects in SvObjectsSocket is crashes waiting to happen too.

**Comment by portnov** [comment]
I did not investigate, do we actually pass references to bpy objects? if so, then yes, this is very probably will be reason of crash. Maybe different kinds of bpy objects are handled in a bit different way, so with one type of objects we have 100% crash, while with other the behaivour is different.

**Comment by zeffii** [comment]
yeah 🐙  https://github.com/nortikin/sverchok/blob/ce79c703aa8109940b2be5ad9f61ea710945a146/nodes/scene/objects_mk3.py#L270

**Comment by portnov** [comment]
Ideally we should pass object names instead. As an option, we can write a wrapper class that only stores the name, and has all methods that we need from bpy object, implemented by delegation (taking object from bpy by name at each call).
But I lean to do not rush and wait for next crash report :)

**Comment by zeffii** [comment]
> But I lean to do not rush and wait for next crash report :)

agreed, i brought this up some time last year with the same reservations.. it seems to work.

**Comment by nortikin** [comment]
from blender 2.79 we can store RNA property as object and scene inside of node.
create collection property for node with objects.

**Comment by portnov** [comment]
```python
import bpy
from sverchok.utils.logging import debug

class BpyObject(object):
    def __init__(self, object=None, name=None):
        if object is None and name is None:
            raise Exception("BpyObject must be given with at least name or object instance")
        if name is None:
            name = object.name
        self.name = name
    
    def get_object(self):
        return bpy.data.objects[self.name]
    
    def __getattr__(self, name):
        return getattr(self.get_object(), name)

plane = BpyObject(name="Plane")
debug(plane.color)
```
