### ISSUE TITLE
Bending Hexa Grid and Surface Bending Conundrum

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1924]
[bend_hexa_error_001_2017_12_11_00_42.zip](https://github.com/nortikin/sverchok/files/1546244/bend_hexa_error_001_2017_12_11_00_42.zip)

Whenever I am using Hexa Grid and wanting to Extrude it, I always got a bit confusion. "Join" seems to fix it when I just simply want to extrude Hexa Grid.

![screen shot 2017-12-11 at 11 43 22](https://user-images.githubusercontent.com/3952687/33811542-d547e4aa-de68-11e7-8d34-7d6341129213.png)

However, Hexa Grid -> Bend Surface -> Extrude Region, once again puzzles me. It does not work. Wonder why?

Why can't "Mesh Join" simply combine Hexa Grid back?

**Comment by Durman** [comment]
Neha grid node has incorrect output.
[bend_hexa_error_001.zip](https://github.com/nortikin/sverchok/files/1546406/bend_hexa_error_001.zip)
![2017-12-11_06-54-13](https://user-images.githubusercontent.com/28003269/33813903-45afe04a-de40-11e7-8027-716747be8d7f.png)

**Comment by enzyme69** [comment]
Ok, the list del 1,2, - 2,3, 0,3, etc sometimes confuses me :D But thanks!

**Comment by DolphinDream** [comment]
@Durman why do you say HexaGrid node has wrong output ? 

For a non-vectorized input the output of the node is (e.g. for rectangular type Nx=2, Ny=1, or any layout type that has more than one tile):

tile1 = [(x,y,z), ..., (x,y,z)]  # 6 vertices
tile2 = [(x,y,z), ..., (x,y,z)]  # 6 vertices

and the combined tiles (not joined):

[tile1, tile2] -> [ [(x,y,z), ..., (x,y,z)], [(x,y,z), ..., (x,y,z)] ] 

while for vectorized input (e.g. input Nx = [1,2]) there are two grids, each one with its own tiles: 

grid1: 1x1
[tile1] -> [ [(x,y,z), ..., (x,y,z)] ]

grid2: 2x1
[tile1, tile2] -> [ [(x,y,z), ..., (x,y,z)], [(x,y,z), ..., (x,y,z)] ] 

and the combined output including both grids:

[grid1, grid2] = [ [tile1], [tile1, tile2] ] ->
[ [[(x,y,z), ..., (x,y,z)]],  [[(x,y,z), ..., (x,y,z)], [(x,y,z), ..., (x,y,z)]] ]

**Comment by enzyme69** [comment]
Maybe “wrong” in term of what required for that particular node? But cheers
for this explanation! It helps also.

After years using Sverchok, seems like I still have to understand the
levels of Vectorization. Matryoshka is a mystery.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by Durman** [comment]
@DolphinDream 
Sorry, I supposed that structure of data from picture below is single true but maybe i am mistaken because I know for example UV connection node supports 3 level nested lists. Eitherway if press on join button data will be correct.

![](http://nikitron.cc.ua/sverch/man02/simple_section.blend.png)

**Comment by DolphinDream** [comment]
Yeah. I see where the confusion may come from. The join option groups together the tiles of each grid into one VEP list, which is more in line with other nodes output.

**Comment by nortikin** [comment]
@DolphinDream 
in such cases optimal to use separate flag to make controllable behaviour

**Comment by DolphinDream** [comment]
@nortikin I agree. That probably makes more sense. It’s easy to change that. What would be the bet way to do this ?  Do I need to create a new node MK1 ? or can I just change the default behavior ? Also, If i replace join with separate.. should the default be separate ON or OFF ?

**Comment by nortikin** [comment]
default always off.
`separate` appears in insertion of node, so make mk1... sadly yes.
