### ISSUE TITLE
Text Out: auto append current input to existing file, update when process is called.

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1926]
![image](https://user-images.githubusercontent.com/619340/33951044-32ea4e60-e02e-11e7-86ab-3bd55da401a3.png)

I am in a situation where I would like to "track" and "record" some kind of changing data into Text Out and would like this to continuously happen.

**SV Text Out** has this "Append" via **Button**. I can tap the button really fast, but I wish it can be updated per frame update.

**Auto**_**Dump** checkbox simple replace the text content each frame update. 

Is there a suggestion that does what I am trying to do?

**Comment by zeffii** [comment]
probably autodump isn't using the Append property. Looking at the code confirms this:
https://github.com/nortikin/sverchok/blob/8fae3136a9ef3e73d835ffc1f06b7d148de4beee/nodes/scene/text.py#L663-L670

The notion of a dump is really to output the current state, I think what you're looking for is a different mode that 'auto appends' whenever the node is told to process (ie.. per frame change when animating)

there's no way to currently do that with the node. (without modifying/adding code)

**Comment by zeffii** [comment]
i suggest adding a Boolean called "auto_append_when_animating" to the TextIn node class, and Node's UI
```python
 def process(self): 
     if self.text_mode == 'CSV' or self.text_mode == 'JSON': 
         multi_socket(self, min=1) 
     elif self.text_mode == 'SV': 
         pass  # only one input, do nothing 
     if self.autodump: 
         self.append = False
         self.dump()
     elif hasattr(self, "auto_append_when_animating") and self.auto_append_when_animating:
         self.append = True
         self.dump()
```
the `hasattr(self, "auto_append_when_animating")`  is just to prevent existing .blends with a TextIn node to throw errors saying they don't have that BoolProperty. As soon as you add a new TextNode the node (and thus `self`) will always have the *auto_append_when_animating* property

**Comment by zeffii** [comment]
AAWA = `auto_append_when_animating`

 - I don't think AAWA needs an `update=updateNode` attribute
 - i'm not sure it's trivial to add automatic disabling of the AAWA state, as a function of the Animation being stopped. But.. we have several tests in the code base to check if the animation is currently playing, do a search and you'll find them.

**Comment by enzyme69** [comment]
Ok thanks for the rundown of this Zeffii. I supposed this can be handled by pre and post. I like SV and Blender to have animation keyframing and recording of all attributes easier at least frame by frame update basis.

**Comment by zeffii** [comment]
```
bpy.context.screen.is_animation_playing
```
my hope with the responses above is that you @enzyme69 would experiment with your local copy of Sverchok / TextIn node by editing it, and make the node do what you want.
