### ISSUE TITLE
Loft then Extrude and .... fail

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1929]
![screen shot 2017-12-14 at 19 47 56](https://user-images.githubusercontent.com/3952687/33983315-d6adce4e-e107-11e7-9b82-e5044a3471e2.png)
[trick_loft_002_2017_12_14_08_47.zip](https://github.com/nortikin/sverchok/files/1558435/trick_loft_002_2017_12_14_08_47.zip)

I have this quite dilemma when using Sverchok and when finding the "data" level does not match and I usually try List Del 1,2 - 0,1 - 2,3 every combination hoping it would work.

Here is another example, maybe @portnov Know why?

**Comment by enzyme69** [comment]
Currently staring at this:
https://github.com/nortikin/sverchok/issues/1924

**Comment by enzyme69** [comment]
Oh ok, this works:
https://gist.github.com/81050d72723a6ac56cc6a550ab2113e4

![screen shot 2017-12-14 at 19 52 52](https://user-images.githubusercontent.com/3952687/33983458-6cc5bcc0-e108-11e7-833b-71fd970ff374.png)

**Comment by enzyme69** [comment]
![screen shot 2017-12-14 at 19 59 49](https://user-images.githubusercontent.com/3952687/33983745-6024f39a-e109-11e7-95c7-feec5a0ea2dd.png)
[Uploading trick_loft_002_2017_12_14_08_59.zip…]()

Ilya you made Procedural Corn :D)

**Comment by portnov** [comment]
See also  #1942.
