### ISSUE TITLE
Creating available nodes in a category

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1931]
What would be a good way to go (script/utility node) to instantiate a set of nodes in a given category ? 
Example if i want to create ALL nodes in the generator section, layed out on a grid. Can i iterate over all existing SV nodes and identify their categories ?

Here are all the Generator nodes:
![sv-generatornodes](https://user-images.githubusercontent.com/2083719/34014866-a4d8c724-e0ea-11e7-9c1e-b88d3bc8ca88.png)

**Comment by zeffii** [comment]
you can iterate over all categories, and get each node contain therein.

this is one way.

1. 

![image](https://user-images.githubusercontent.com/619340/34015093-b7f54034-e11d-11e7-8df6-c73b58dae949.png)

(you'll have to add some standard item skipping like...  "automatic_collection.. basename...defaultdict..directory...etc " )

![image](https://user-images.githubusercontent.com/619340/34015178-f8762696-e11d-11e7-9c9c-5a3449802df0.png)

and further introspection to find which members of this module are instances of a `bpy.types.Node`

2. 
`sverchok.node_list`  is easy enough to parse

3.
`sverchok.node_classes` is too

4.
```python
import nodeitems_utils
nodeitems_utils._node_categories["SVERCHOK"]
```

**Comment by nortikin** [comment]
maybe in N panel to label the folder? Menu is not folder, not always....
No, changed my mind. but for sure label  needed

**Comment by DolphinDream** [comment]
Sweet! :) Once I create a node is there a way to probe for its height ? e.g. if i want to put them on a grid in a compact way I need to know the height.

**Comment by DolphinDream** [comment]
Also, how do I instantiate the nodes programmatically ? I know the node_tree quicklink has something like this to spawn new nodes:

```python
def execute(self, context):
        tree = context.space_data.edit_tree
        nodes, links = tree.nodes, tree.links

        caller_node = nodes.get(self.origin)
        new_node = nodes.new(self.new_node_idname)
```

Is this the way to go? Once i find the names of the nodes in a category I do: nodes.new(new_node_idname) and set its location ?

**Comment by DolphinDream** [comment]
It seems that node.dimensions would return the actual width and height. (note: the height itself seems to not be the correct value for node’s height).

**Comment by DolphinDream** [comment]
@zeffii can you elaborate on 1 ? not sure how to parse a class structure. i find it a bit strange that SV doesn’t have a dictionary structure of the nodes based on categories/subcategories. 

So far i was able to extract the categories like this:

```python
    def get_categories(self):
        nodes = nodeitems_utils._node_categories["SVERCHOK"][3]
        categories = [nodes[i].category.name for i in range(len(nodes))]
        return categories
```

but once i have a category I need to get the list of nodes in that category.. and eventually get their bl_idname so i can create new nodes. Is there a structure that gives the nodes in a category?

**Comment by zeffii** [comment]
also see https://blender.stackexchange.com/a/79981/47

**Comment by zeffii** [comment]
if you're looking for a dict of `{category_name: [node_bl_idname_list], ...}` , then that's not presently generated because we didn't need it. Also blender's own node trees don't have such a thing by default.

**Comment by zeffii** [comment]
thus..
```python
import bpy
from collections import defaultdict

ddir = lambda data, filter_str: [i for i in dir(data) if i.startswith(filter_str)]
get_nodes = lambda cat: [i for i in getattr(bpy.types, cat).category.items(None)]

node_cat_dict = defaultdict(list)

sverchok_categories = ddir(bpy.types, "NODE_MT_category_SVERCHOK")
for cat in sverchok_categories:
    category_name = getattr(bpy.types, cat).category.name 
    for node in get_nodes(cat):
        node_cat_dict[category_name].append(node.nodetype)

print(node_cat_dict)
```

**Comment by zeffii** [comment]
regarding height / width / dimensions.. i've also noticed anomalies in my quest to complete IO/JSON "carbon copy" effort.

**Comment by DolphinDream** [comment]
@zeffii  awesome. Thansk. Btw, would the previous category fetcher examples get the subcategories as well? I noticed that it doesn’t return a category “List”, it only returns the subcategories “List Main” and list “List Struct” with the nodes in the root category “List” merged with the list in “List Main”. Similarly the “Generator” category is reported, but the “Generator Extended” is missing and its nodes are actually merged into the “Generator” list.

**Comment by zeffii** [comment]
subcategory? nope. But really, the distinction is purely cosmetic to help break up the menus. If you really wanted proper tracking of all distinguishable categories as seen from a menu perspective, then loop at how `index.md` is parsed, and `menu.py`

**Comment by zeffii** [comment]
so something like 
```python
from sverchok.menu import juggle_and_join, make_node_cats
all_categories = juggle_and_join(make_node_cats())
```

**Comment by zeffii** [comment]
so something like 
```python
from sverchok.menu import make_node_cats
all_categories = make_node_cats()

for name, items in all_categories.items():
    print(name)
    print(items)
```

**Comment by zeffii** [comment]
i'd cache that if you need to call it often.

**Comment by zeffii** [comment]
don't ask why each bl_idname is individually wrapped in a list. It's a vestige from when those elements stored more information.

**Comment by DolphinDream** [comment]
Wicked! :) thx @zeffii 

Btw, should “separator” be part of the categories/nodenames? no biggie, i just skip over this “node name” for now, but was wondering if this name appears in the cat list by accident or intentional.

**Comment by DolphinDream** [comment]
Also, do you know why I can’t seem to get the new node dimensions once I create it with nodes.new(nodename)  ? the dimensions turn back as zero. Do some calls need to be made to update the dimensions of the newly created nodes or something?

**Comment by zeffii** [comment]
it's intentional. (` separator `) is used for adding `layout.separator` in menus. This dict is generated directly from the content of `index.md`.

**Comment by DolphinDream** [comment]
Here’s a demo so far.. regular grid (no compact form.. for which I would need the actual heights).

![sv-displaynodes-demo1](https://user-images.githubusercontent.com/2083719/34058555-64a06df0-e1a9-11e7-9f37-bd5a8ee1bc3b.gif)

**Comment by DolphinDream** [comment]
@zeffii cool. i thought so (about the separator). Also, i assume that a better implementation would be to check if the node with the given name exists before creating one, instead of just skipping over specific names like “separator”. What is the way to do this introspection btw?

**Comment by zeffii** [comment]
@DolphinDream  just focus on what you're doing.  skipping an item based on a single string test is faster than checking from a list of strings whether it a string is present.

**Comment by DolphinDream** [comment]
Also, for now this is a node (with property panel access).. if I was to make this a debug/dev feature only and always available in the property panel, how do you do that ? (perhaps dev features made visible via settings and not always displayed in the PP). I’m thinking along the same lines we discussed the icon manager a while back, whether we should put this feature on the PP in “dev" mode)

**Comment by zeffii** [comment]
i have to wrap your gif in `<details>` because that gif slows down my machine (crawls it)

**Comment by DolphinDream** [comment]
@zeffii sure, the simpler is sometimes better. I was future proofing in case for some reasons other “node names” that are not actual nodes are injected into this category list. no biggie.

**Comment by DolphinDream** [comment]
Is the gif too large ? i can make smaller ones. or is it gif in general slows down your machine?

**Comment by zeffii** [comment]
nope. just certain gif types. it's a slow machine.. and if you use `<details>` it can be viewed optionally.

**Comment by DolphinDream** [comment]
dimensions ?

**Comment by zeffii** [comment]
well, there's a node lookup you could use to test if a node is registered.
```
import sverchok
from sverchok.utils import node_classes

print(node_classes)
```
where node_classes becomes filled with a dict, a direct mapping from `bl_idname` to `class reference`.

**Comment by zeffii** [comment]
if a node isn't in node_classes after startup, then it wasn't registered during startup.

**Comment by zeffii** [comment]
```python
# n = new node
>>> n.dimensions
Vector((159.85824584960938, 75.0))

>>> n.height
100.0
>>> n.width
159.85824584960938
```

**Comment by zeffii** [comment]
for `SvAxisInputNodeMK2` i happen to set the height from `sv_init`

**Comment by zeffii** [comment]
yeah, you might have to call `node.update()` or something then.
```python
import bpy

nodes = bpy.data.node_groups['NodeTree'].nodes

nn = nodes.new('SvAxisInputNodeMK2')
print(nn.dimensions, nn.height, nn.width)

>>> <Vector (0.0000, 0.0000)> 100.0 100.0
```
hmm..

**Comment by zeffii** [comment]
not sure exactly. don't get stuck on this.

**Comment by zeffii** [comment]
that might be a bug in pynode api, also check if the same happens for other node tree types, like Shader trees.

**Comment by DolphinDream** [comment]
Ha.. just a note that SvPolylineViewerNodeMK1 shadows the dimensions attribute defined in the base class. Got this while trying to print dimensions.x  (expecting dimensions to be a vector). in this node this attr is a string. Should this be changed to some other name to avoid shadowing ?

**Comment by DolphinDream** [comment]
Also, another “discovery” is that the “List mask” nodes listed in the “list” category have their own “List Masks” category while the menu does not display them in a “List Masks” subcategory. (intentional/accidental?)

Same with the List Modifier node has its own “List Mutator” category while it’s listed in menu in the main “list” category (accidental/intentional?)

**Comment by DolphinDream** [comment]
Hm... slightly off topic (but i’m dealing with this for this node).. should a node’s process() method be called when changing a node’s property (if the prop’s update=updateNode) ?

**Comment by DolphinDream** [comment]
Wow.. process() is being called only when there is a connected out socket?? 😕

**Comment by DolphinDream** [comment]
Btw.. here’s an interesting addon to order nodes (shared by TynkaTopi): https://puu.sh/yHp9E/3c975e988c.gif

**Comment by DolphinDream** [comment]
Added a few features. 
- grid height
- grid x/y spacing
- orientation (not yet implemented)
- bin packing based on height 
- centering horizontally within column

Still need to figure out:
- how to have dimensions value updated automatically after adding new nodes to the tree
- have processing be called (or any other way to update) upon prop change value without having a connected output socket

![sv-displaynodes-demo2](https://user-images.githubusercontent.com/2083719/34067089-34e45536-e1ea-11e7-9e2d-0242dcefc51c.gif)

**Comment by portnov** [comment]
@DolphinDream You can implement this as an Operator and put the button somewhere to Sverchok panel, near Update buttons. Just maybe show the button not always, only in certain mode (only if configured in addon settings or if certain environment variable is set), because most users do not need this feature, I think.

**Comment by zeffii** [comment]
> SvPolylineViewerNodeMK1 shadows the dimensions attribute

that's unintentional, and might explain why sometimes the node gets stuck in grab mode and attaches itself to the mouse - this has puzzled me and this seems like it might be connected.

> the menu does not display them in a “List Masks” subcategory

There's two menus, 
  - `NodeView / header / Add`   (standard categories, filled by the mere fact of node registration in `nodeutils`.)
  - `shift + A` -> this one uses the raw `index.md` and menu.py to show the nodes.

sadly its not trivial to replace the `header/add`, and the code involved is pure obfuscation. look away.

> Wow.. process() is being called only when there is a connected out socket??

really? well.. please include the snippet of code that made you come to this conclusion.

> addon to arrange nodes (shared by TynkaTopi)

I contributed some code to that add-on, but have not found it particularly useful in practical day-to-day noding. It is useful for scripted node networks, sure - the only real application.

**Comment by zeffii** [comment]
@DolphinDream 

I don't think it's intentional that there's a List Masks subcategory, but it is intentional that these nodes are not displayed in the other List categories. Maybe that main list category should be called List Main.. it's a non issue. for now.

**Comment by zeffii** [comment]
> should a node’s process() method be called when changing a node’s property (if the prop’s update=updateNode) 

in general we don't need to process nodes that don't have socket output (except Viewer Nodes that use bgl, or `debug print` node  <--- these nodes all have an input, but no socket output ). 

`updateNode` is not just a simple call to the nodes `process()`, as you've been able to summise there are some conscious/sanity checks first.

If you are implementing a node that has no inputs or outputs and need it to trigger something then you can use `self.process_node(None)` to trigger `process` locally.

```python
class ....

    def local_updateNode(self, context):
        self.process_node(None)

    some_property = IntProperty(update=local_updateNode)

    def process(self):
        print('hi!!!!')
```
you can either do the work in local_updateNode.. and not need to call `process`.  Or do it in process for sake of consistency.

**Comment by zeffii** [comment]
you will find (in the code base) a couple of variants of properties with alternative update functions. maybe  one that calls `process` directly via a lambda or something (wouldn't surprise me)

**Comment by DolphinDream** [comment]
thanks @zeffii . yeah, that example does work, however mine is pretty similar and it doesn’t. I made a PR #1938  for the new node, if you can take a look and tell me what I may be doing wrong Id appreciate it.

**Comment by DolphinDream** [comment]
Here’s a simpler example that does not work (e.g. process is not triggered when changing property values):

```python
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
from bpy.props import IntProperty, FloatProperty, BoolProperty, EnumProperty, FloatVectorProperty

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode


class SvBoo(bpy.types.Node, SverchCustomTreeNode):
    ''' Boo '''
    bl_idname = 'SvBoo'
    bl_label = 'Boo'

    grid_height = IntProperty(
        name="Grid Height",
        default=400, update=updateNode)

    grid_x_space = IntProperty(
        name="Grid X spacing",
        default=20, update=updateNode)

    grid_y_space = IntProperty(
        name="Grid Y spacing",
        default=20, update=updateNode)

    def draw_buttons(self, context, layout):
        layout.prop(self, 'grid_height')
        layout.prop(self, 'grid_x_space')
        layout.prop(self, 'grid_y_space')

    def draw_buttons_ext(self, context, layout):
        layout.prop(self, 'grid_height')
        layout.prop(self, 'grid_x_space')
        layout.prop(self, 'grid_y_space')

    def update(self):
        pass

    def process(self):
        print("Processing node")


def register():
    bpy.utils.register_class(SvBoo)


def unregister():
    bpy.utils.unregister_class(SvBoo)

```

**Comment by DolphinDream** [comment]
Another demo... (I figured out how to update the node dimensions immediately after I add them to the node tree; thanks to IRC/scorpio81 for the tip)

<details>
![sv-displaynodes-demo3](https://user-images.githubusercontent.com/2083719/34073213-aa5fd312-e262-11e7-92ff-bd6f61cc0439.gif)
<details>

**Comment by DolphinDream** [comment]
Btw, are the generator colors gone ? or did I mess up my sverchok stttings ?

**Comment by zeffii** [comment]
```python
    grid_height = IntProperty(
        name="Grid Height",
        default=400, update=lambda s, c: s.process())
```

**Comment by zeffii** [comment]
> or did I mess up my sverchok stttings ? they used to be green.  (@DolphinDream )

first look at where and how Sverchok sets theme colors, check if you need to store a setting .. or if we removed theme related stuff by accident.

**Comment by DolphinDream** [comment]
I’m getting a weird segfault when i use undo: I create the nodes, then change the grid layout settings.. then undo the adjustments I just made.. then when i adjust the settings (e.g. the grid spacing) I get a segfault. Does undo messes up the nodes in the hierarchy or my local reference to these nodes ? (i’m storing the spawned nodes in a global _spanwed_nodes array btw.

**Comment by zeffii** [comment]
undo sucks :)  we can't fix that from our side.

i'd store the string of the node.name , try/except access to it using `n = nodes[string_of_name]`

**Comment by DolphinDream** [comment]
@zeffii the generator colors got messed up when the names changed from “Generators” to “Generator” (we won’t give names as to who broke this ;) . The color_def.py needs to have the indexing string in the color dictionaries changed from “Generators” to “Generator”. Btw, I hope this name change did not affect other things like gist importing/exporting or other aspects.

I have the fix to color_def.py locally. I can push a PR if needed.

**Comment by zeffii** [comment]
> Btw, I hope this name change did not affect other things like gist importing/exporting or other aspects.

IO/json just needs bl_idnames.. it cares nothing about categories

**Comment by DolphinDream** [comment]
I fixed the generator colors in this PR #1939

**Comment by zeffii** [comment]
i think you overlook my response, or don't understand it.

```python
    grid_height = IntProperty(
        name="Grid Height",
        default=400, update=lambda s, c: s.process())
```

this `update=lambda s, c: s.process()` calls the node's own process function bypassing the checks and balances that would be required if you had `update=updateNode`, and doesn't require any sockets to be present.

**Comment by DolphinDream** [comment]
@zeffii yeah. i got your s.process suggestion. I actually got rid of my node’s process() altogether and set the props update to an arrange_nodes() method I already had.

**Comment by nortikin** [comment]
is there branch for it?

**Comment by DolphinDream** [comment]
@nortikin #1938  on my DisplayNodesDev branch .. still under developing :)
