### ISSUE TITLE
Objects in node - get group

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1932]
This can take objects by groups it is good but it is better also to have automatic check of changing of group. I grab objects from scene and if number of objects increases I each time come back to the input node and i press refresh group. (
https://gist.github.com/600453040f140d21fffe544e497591ed
![group check](https://user-images.githubusercontent.com/28003269/34030855-2dc43f8a-e188-11e7-9881-569f96dd66bf.gif)

**Comment by enzyme69** [comment]
This will surely be handy, I have encountered this situation many times.
Group is interesting.

**Comment by zeffii** [comment]
good point @Durman .

**Comment by zeffii** [comment]
`Objects In`'s process function is not called by the (automated/userdriven) action of adding items to a group that it tracks.  `Objects In` essentially just gets the names of objects contained by the group at the time "Get Selection" is pressed.

This is another case of the assumption being that not all attributes require frame by frame / constant checks. Of course you show that it might be useful to at least have the ability to do that. It may be especially simple in this case as you generate the group called Beta from BMV2 node, and are also reading it in the same node tree. 

We would need to experiment with triggering one node from another "wirelessly" ..
```text
   BVMK2
   - if generating groups get name of group
       - check current node tree, do any Object In nodes track the same group?
             - if yes, the call Object In's . `get_objects_from_scene(self, ops):`  with a fake `ops` parameter
```

**Comment by zeffii** [comment]
of course, the above suggestion does not solve a similar issue for Groups which are updated by other means (user manually, AN...etc)

**Comment by Durman** [comment]
According that this issue hardly has relation with 2.8 and 2.79 is not in focus anymore, I'm closing this.
