### ISSUE TITLE
Polyline Viewer may move to MK2 (but will stay MK1 if humanly possible)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1935]
@DolphinDream points out that i accidentally use a class attribute ( `.dimensions` ) that's already defined in the base Node class. I use it for a switch between 2d/3d mode of the Spline, but scripted interfaces to nodes will expect dimensions to represent the node's height/width as a Vector(2D).

this is a todo.

**Comment by DolphinDream** [comment]
Is this as simple as changing the var name to a different one?

**Comment by zeffii** [comment]
Technically its a pre-release. I don't fancy changing bl_idname for a single property. Maybe I will have time later today to test scenarios.

**Comment by zeffii** [comment]
>  Is this as simple as changing the var name to a different one?

almost never.

procedure here is 
- make simple .blend using two pview node mk1s, one with 3D set and the other with 2D
- save .blend
- branch mk1
- edit branch, do the simplest possible edit
- open blender and behold.. did it break
    - if it broke, then mk2 is on the cards..
    - if not..ask people to test the branch ... if no problems .. or no responses... push the new change.

- if people do have issues
   - because this is a pre-release I kind of feel bad.. but ..kind of don't. it's beta/alpha for a reason. No matter how long it stays beta/alpha.

**Comment by zeffii** [comment]
you can tell here: https://github.com/nortikin/sverchok/pull/1960

The property name change doesn't cause the node to error, but it will reset the users selection to the default of 3D for all nodes.

**Comment by zeffii** [comment]
fixing that also didn't solve the node attaching to the cursor.
