### ISSUE TITLE
Common "bpy.objects" class for the Viewers that generate objects.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1936]
### This is for after expander sockets are merged.

Right now we have quite a collection of nodes that output and update bpy.objects of type 'CURVE/MESH/METABALL`. all of these nodes share a considerable amount of 'procedural' code with respect to 
   - `getting children` of the node  (`objs = `)
   - generating object names
   - setting materials
   - generating materials
   - cleanup orphan objects
   - hide / hide_select / hide_render / select operations.
   - easy auto update the node switches https://github.com/nortikin/sverchok/issues/1930
   - include layer handling
   - include per object material passing.

When i started out with BMViewer..and later CurveViewer it was still manageable but with the 6 or 7 nodes that generate bpy.objects now duplicating these things i'd like to gradually streamline these nodes and allow an easier way to add features to all nodes of this "class" at the same time.

then consider pulling them out of Beta. unibrows and all.

**Comment by portnov** [comment]
+1. Also I have beginnings of "Lamp out" node, which has all the same problems.

**Comment by zeffii** [comment]
the PR is here. it's not in a working state yet ( and has no users to depend on it yet.. )

https://github.com/nortikin/sverchok/pull/1951

this may take a while.

**Comment by zeffii** [comment]
am closing this Issue to focus the talk in one place. https://github.com/nortikin/sverchok/pull/1951
