### ISSUE TITLE
Face Adaptive MK II - A wishlist

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1937]
While exploring Brick node and Bend Surface nodes, I am also looking at Face Adaptive, and wondering if it is about time that this node can be improved. To be something that feels more like Tissue add-on adaptive.

![Uploading Screen Shot 2017-12-16 at 23.29.50.png…]()
![screen shot 2017-12-16 at 23 30 07](https://user-images.githubusercontent.com/3952687/34070357-12ececde-e2b9-11e7-9a7e-4a856bb58b94.png)

Especially in term of being able to know the "Normal" of original face it is adapting. It can be handy for lots of situations.

**Comment by nortikin** [comment]
it is tissue with modifications

**Comment by zeffii** [comment]
> wondering if it is about time that this node can be improved

be the change you want to see @enzyme69 . code it. yes it's difficult, but mostly just in the beginning.

**Comment by zeffii** [comment]
i'm closing this as unclear @enzyme69 .

Can you edit your original question, take a bit more time / effort to explain the details of how the current Adaptive Polygons node is unsatisfactory. Use images with basic geometry (not thousands of faces..where 20 faces would be enough) , highlight faces, draw normals.
