### ISSUE TITLE
Events, promotion (Ton Roosendaal etc)

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#194]
Ton Roosendaal invites us to IRC chat.
freenode server and #blendercoders channel
I use X-Chat programm to connect IRC
when you choose from catalog reenode server (allready in catalog) than use commanD;
/join #blendercoders

**Comment by nortikin** [comment]
@zeffii , please give me your paypal. You ignore my email. What is wrong?

**Comment by zeffii** [comment]
@nortikin  yes I will reply to that email. soon. promise.

**Comment by nortikin** [comment]
http://vk.com/public35076122?w=wall-35076122_5131
At last there is video of CGevent.
I posted it on Vkontakte because of audience and Russian language here, i know nobody like non-English languges in English-speaking world.

**Comment by nortikin** [comment]
http://vk.com/public35076122?w=wall-35076122_5361
let see, today i met Elistratov Vladimir in Moscow, here it is what he do, propose him to participate in Sverchok with his addon

**Comment by nortikin** [comment]
tomorrow CGevent2015 i will present Sverchok.
have not mood for that. will do all i can

**Comment by zeffii** [comment]
I think your latest Sverchok videos where you speak english are pretty good. improved since the last videos :)

**Comment by nortikin** [comment]
Waffle node will be presented.
http://www.blendernation.com/2015/11/25/sverchok-news/

**Comment by nortikin** [comment]
ok, i did it. Waffle node was presented in CGevent2015. Video will be available i think as usually after new year, but hope sooner.
Not much folks presented, but enough

**Comment by nortikin** [comment]
CGevent2016 went away, i presented sverchok with stripes vertex node. (interpolation case)
name of lection was "Searching an architectureal form in Sverchok"

Next, was interviewed for brenchpoint blog. Mentioned there in both events you, guys. Hope people will pay attention.
Maybe this tradition that CGevent with opensource section, where interesting krita lection and AN was presented there in examples. will share video.
I promised my CGevent 2015 video to you... so will now upload. later will upload 2016 when it appears on site.

**Comment by nortikin** [comment]
https://www.youtube.com/watch?v=mgJnXSSKfgQ
here we go. look what is roads generator

**Comment by enzyme69** [comment]
I wish I understand Russian language :| ㊙️

**Comment by nortikin** [comment]
sometimes i wish to understand all languages in the World...

**Comment by nortikin** [comment]
CGevent 2017 is coming, will introduce new layout ordering of mine, new 3dprinted items (spinners and wedding rings that i made this year) also talks of usefulness of parametric at all and procrastination of your PC + levels in Sverchok in examples.

**Comment by nortikin** [comment]
https://vk.com/video-35076122_456239348
Here is 2016 CGevent Moscow

**Comment by nortikin** [comment]
http://nortikin.github.io/sverchok/About
colors changed

**Comment by nortikin** [comment]
http://coub.com/view/zn0cq
git push the tempo

**Comment by nortikin** [comment]
![stat1](https://user-images.githubusercontent.com/5783432/51233780-e24ed600-197b-11e9-82d1-d96a8cb8978e.png)
![stat2](https://user-images.githubusercontent.com/5783432/51233781-e24ed600-197b-11e9-8fcf-26b0fb65f190.png)
![stat3](https://user-images.githubusercontent.com/5783432/51233782-e2e76c80-197b-11e9-8f3c-9fcde7d1bc2f.png)

**Comment by nortikin** [comment]
Trailer from year ago
https://vk.com/video-35076122_456239721

**Comment by nortikin** [comment]
This is from year ago presentation
https://youtu.be/kCf76YzXjfw

**Comment by kalwalt** [comment]
Hi @nortikin can you provide this is interesting can you porvide the statistics data in English? i am refering to the images above. Thank you! :smile:

**Comment by nortikin** [comment]
@kalwalt if you need exact data, i can translate. there is no interface english as i see.
Zip with history:
[stat-nikitron.zip](https://github.com/nortikin/sverchok/files/2799501/stat-nikitron.zip)

**Comment by nortikin** [comment]
New places:
https://discord.gg/pjHHhjJz8Z
https://t.me/sverchok3d
