### ISSUE TITLE
Scale node is keep printing to console

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1940]
I was working on something... and realized the Console is keep printing something... I check all nodes and apparently the culprit is **Scale** node. 

[something_keeps_printing_03_2017_12_17_00_29.zip](https://github.com/nortikin/sverchok/files/1565202/something_keeps_printing_03_2017_12_17_00_29.zip)

Can we remove the printing maybe it will make faster processing?

**Comment by enzyme69** [comment]
Let say if a noob like me really wants to make changes like this in this Github, I know that one line is doing printing... how would one do this?

**Comment by enzyme69** [comment]
View Source - Permission Denied.

**Comment by enzyme69** [comment]
Found this and found the line that print:
https://github.com/nortikin/sverchok/blob/47d6350bd9436098334b4af033376fe598905bcd/nodes/transforms/scale_mk2.py

**Comment by zeffii** [comment]
For details about View Source and what preferences you should *read*/ask on the related thread. you can find it. i'm sure.

now, you are right about the node needing to not print all the time.

the options are
   
https://github.com/nortikin/sverchok/blob/47d6350bd9436098334b4af033376fe598905bcd/nodes/transforms/scale_mk2.py#L63-L65

1.
```diff
    - print(c,v,m)
    + self.debug(c, v, m)
```
This would make use of the new logging module, it gives each node a few standard printing functions that let us set in the preferences what level of importance printing we want. [See the thread](https://github.com/nortikin/sverchok/pull/1911), ask questions if you're interested. Some more examples will follow if it is unclear.

2.
```diff
    - print(c,v,m)
    # print(c,v,m)
```
just kill it.. it isn't needed. so i've committed https://github.com/nortikin/sverchok/commit/0cc008580b5708bb040ba10ab904f3ffcf9fbe08

**Comment by zeffii** [comment]
>  Let say if a noob like me really wants to make changes like this in this Github, I know that one line is doing printing... how would one do this?

that's a perfect question for a separate thread. OR you make the title of this thread about that instead.

**Comment by portnov** [comment]
I think our contributing.rst is waiting for update. And for link from front page (readme).

**Comment by zeffii** [comment]
maybe waiting for a rewrite :)

**Comment by zeffii** [comment]
i will do this. -- at least the basics.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/cont_doc_updates/docs/contribute_small_things.rst
