### ISSUE TITLE
Sometimes Extrude Region does not extrude along normal...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1946]
Exactly like the title, here is an example:
[bending_collar_001_2017_12_18_11_34.zip](https://github.com/nortikin/sverchok/files/1567707/bending_collar_001_2017_12_18_11_34.zip)
![height](https://user-images.githubusercontent.com/3952687/34104271-db95d82c-e443-11e7-82ce-04603c1569a8.gif)

Not quite sure what's causing this behaviour.

**Comment by portnov** [comment]
It extrudes along the normal of *region* (because it is extrude Region), which is defined as average of all faces in region. So when faces have oppositely directed normals, region normal is zero vector, it is directed nowhere. You just have to use Matrix mode instead.

**Comment by enzyme69** [comment]
Ok gotcha, cheers @portnov
