### ISSUE TITLE
Color Node to display the color on the node in limited cases.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1950]
i wonder if we should have a small half `row()` element to display the colour in the case that there's no input into the node. We could make the colour property _non editable_ , or make the sliders react to the picked colour.

would be hidden when the node is producing lists of colours.

yes / no  @DolphinDream  @portnov  @nortikin ?

**Comment by portnov** [comment]
You mean Color In MK1?

If we go with proposed implementation:

1. If any of sockets are connected, then I think the property should be hidden.
2. If sockets are not connected, then color and slider property should affect each other (edit color -> sliders change, and vice versa).

Also we can go other way, and implement separate node, "Color Input" (similar to Matrix Input or List Input), which has only one Color property. Analogy with *Input nodes leads to another interesting question: maybe we should allow to change Color inputs from 3D panel?

**Comment by portnov** [comment]
For separate "Color Input" node we might use `template_color_picker`.

**Comment by zeffii** [comment]
mk1 yep.   ok maybe just a separate node would be fine instead. (or in addition to the limitations we've enumerated )

**Comment by DolphinDream** [comment]
@zeffii can you do a quick mockup (of the “small half row()” idea) ?

**Comment by DolphinDream** [comment]
Talking about color inputs.. i noticed that the “Vertex color mk3” doesn’t have an expandable color socket. Should this be converted to use the expanding feature ?

**Comment by zeffii** [comment]
@DolphinDream if I did a mockup, i might aswell also just commit the code :) so no.  not tonight :)

**Comment by zeffii** [comment]
but with Alpha enabled it would be (these are slices of the UI )
```
|  [x] Alpha  [RGB][Opacity]  |
```
and Alpha disabled
```
|  [ ] Alpha [     RGB     ]  |
```

where RGB is represented by a FloatVectorProperty  with type attribute similar to what is available on VDMK2 , and the Opacity is .. i'm not sure how that's draw.

**Comment by zeffii** [comment]
I did some other colour node experiments a while back but can't seem to find them at the moment.

**Comment by DolphinDream** [comment]
I don’t know if this “use alpha” is unavoidable, but sure thing is a bit annoying. Can't the nodes figure out whether to use the alpha or not?

**Comment by zeffii** [comment]
> Can't the nodes figure out whether to use the alpha or not?

in the process function of the node where the color is passed to a scene object / material / etc, there could be a check to see if the incoming data is all n*4 or n*3 and if that matches what the property being set expects. Then if not, traverse upstream till a ColorNode is reached and freeze the node, enable/disable alpha on the node, unfreeze the node and trigger a process from the ColorNode(s) .

that would work, probably, for nodes that are dedicated to setting color attributes, but freeform nodes like Formula, Exec Nod, SN* would perhaps be served by final clause in the try/except to test specically for the word 'color' and then do a similar test.

Not sure if you'll ever earn the time back spent on figuring out how to do it, vs just ticking the box for 60 years. Of this I am sceptical. It would be an interesting exercise, i admit.

**Comment by portnov** [comment]
I'm going to implement separate "color input" node if nobody has objections.

**Comment by portnov** [comment]
![screenshot_20171219_195911](https://user-images.githubusercontent.com/284644/34162892-18e52d96-e4f7-11e7-8b9b-472555ca5a6f.png)

**Comment by zeffii** [comment]
Would be useful to see the selected color too, not just a dot on the location

**Comment by portnov** [comment]
Hmm. If I add layout.prop(self, "color_data"), it not only shows color widget; that slot is clickable, and on click it pops up yet another picker. A bit weird.

![screenshot_20171219_203246](https://user-images.githubusercontent.com/284644/34164603-cab0afce-e4fb-11e7-8c1e-8b4557264998.png)

Also I became unsure if we really need this separate node:
* template_color_picker is nice, but it does not allow to enter alpha values;
* just prop() allows to enter color with more options;
* color_out mk1 already has such prop(). But it does not output the color itself, only it's RGBA components.

**Comment by portnov** [comment]
Huh.
![screenshot_20171219_203828](https://user-images.githubusercontent.com/284644/34164888-986b7e4e-e4fc-11e7-8ee3-8c8241602b8b.png)

**Comment by DolphinDream** [comment]
Here’s a twilight zone behavior : )

![sv-colornode-demo1](https://user-images.githubusercontent.com/2083719/34165489-728fe78e-e4aa-11e7-9e84-096e97e9b216.gif)

**Comment by zeffii** [comment]
> Isn’t the node supposed to stay red as long as the input is incorrect ?

it would make sense if it did, yes. worth noting this side effect.. the focus of error handling switches to the most recent node that is told to update, in this case that node is disjoint from the graph.

**Comment by portnov** [comment]
#1957 1957
