### ISSUE TITLE
Text file as place for exchange data between sheets

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1953]
Another way to change data between layouts.

![exchenge data](https://user-images.githubusercontent.com/28003269/34145989-b6c40168-e4b1-11e7-879f-5546308f4676.gif)

**Comment by zeffii** [comment]
@Durman   you know you can hit Left or Right in the NodeView to trigger a keyframe change?

**Comment by Durman** [comment]
@zeffii  Yes. I showed timeline for clarity.
