### ISSUE TITLE
Link to text file in text out and text in nodes.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1954]
Link to text file depend from position in text files list, it's bad very. (

![bug text node](https://user-images.githubusercontent.com/28003269/34152563-79746e62-e4c8-11e7-99e6-e491e1029a3f.gif)

**Comment by enzyme69** [comment]
Interesting, I am watching.

A while back ago, I thought Wifi Out and Wifi In can connect data from different node tree. I was wrong.

![screen shot 2017-12-19 at 22 39 03](https://user-images.githubusercontent.com/3952687/34155453-7a42ce8e-e50d-11e7-90c8-2a606256950d.png)

**Comment by zeffii** [comment]
OK i'll fix this/

**Comment by zeffii** [comment]
whats happening, is that shouldn't be an Enum. Same thing used to happen with the Image node (if you remember @enzyme69 )

**Comment by zeffii** [comment]
for example:
https://github.com/nortikin/sverchok/commit/427c946ba273f28f3b78b79e1dff9eb880471474#diff-d59f5262cbf73933339be555d4e4aa29  (example is image.. but it holds true for bpy.data.text too )

**Comment by zeffii** [comment]
the question is.. can it be fixed while leaving the bl_idname unchanged + not break existing blends... I'm not a fan of going to MK2 for this kind of thing, but will if we have to.

**Comment by zeffii** [comment]
making this PR https://github.com/nortikin/sverchok/pull/1956 to handle the recent Text IO issues found in the issue tracker (thanks for reports)
