### ISSUE TITLE
When Text In and Text Out failed, what should we do?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1955]
[textinout_failed_2017_12_19_11_14.zip](https://github.com/nortikin/sverchok/files/1571411/textinout_failed_2017_12_19_11_14.zip)
![screen shot 2017-12-19 at 22 14 02](https://user-images.githubusercontent.com/3952687/34154558-06e71524-e50a-11e7-9772-23634cd36ed5.png)

I was expecting this to work, somewhat it does not work... wonder why. Anyone knows?

**Comment by enzyme69** [comment]
Invalid syntax or something introduced by a bracket?

**Comment by zeffii** [comment]
use json or csv for now, i'm really not sure what `Sverchok` datatype was intended for. It doesn't seem useful for anything other than debugging the output of a node, not for `data out - data in` .

**Comment by zeffii** [comment]
> Invalid syntax or something introduced by a bracket?

if you write to Text Out , disable auto dump ..then remove the surrounding _parenthesis_ of the resulting text, then you can get Text In to read Sverchok "Data".

But.. because i don't know the intention of that Sverchok-data type i'm hesitant to "fix" it, it might not be broken. @nortikin   care to weigh in?

**Comment by enzyme69** [comment]
Roger that! @Durman how did you make this work?

**Comment by zeffii** [comment]
also... don't use the Text called "sverchok.log" to store your text, this is a file that Sverchok writes to for debug / info.  I think we might have to add code to reset the node if a user selects that filename

**Comment by Durman** [comment]
@enzyme69 This node don't understand round brackets :/

![2017-12-19_19-52-48](https://user-images.githubusercontent.com/28003269/34165623-3be90d22-e4f6-11e7-8723-8d1ea2f4fc6e.png)

**Comment by zeffii** [comment]
not sure why box is outputting a tuple.. it's not wrong, but it's a little unconventional. 

Text Out in Sverchok mode should probably recast to a List when the Data socket encounters a `tuple()` / _parenthesised data_.

or

Text In should recast to list when reading.

probably the Text In node is the most appropriate to fix.

**Comment by zeffii** [comment]
see progress here: https://github.com/nortikin/sverchok/pull/1956
