### ISSUE TITLE
Nodes upgrade approaches: discussion

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#1959]
## Problem statement

Sometimes we have to change some node in incompatible way. Examples of such changes are:
* Changing type of property
* Changing type of socket
* Removing a property
* Adding input or output not to the end of list
* etc (it would be nice to have full list of such changes written somewhere, for example right here)

We cant "just change" node code in such situations, because in existing blend files nodes are already set up in the old way, so the new code will not know how to deal with old node.

## Current solution

* Create new node with new bl_idname
* Move old node to old_nodes

## Drawbacks of current approach

* Users have to manually remove old nodes from their setups and create new ones, if they do not want to see ugly red "Deprecated" frames
* We have to maintain several versions of the same code
* In some situations, we have several MkN non-deprecated versions of the same node at the same time.

## Suggested approach

* Introduce a new IntProperty in base node class, `node_version`, with default value of 0. This property is not displayed anywhere in UI, but it will be stored in blend files as all properties are. This property will mean the version of node code, which was used when this node was created; so this is the version of stored node settings.
* Introduce a new method in base node class, `get_current_version(self)`. Return value of this method will mean current version of node code. Default implementation just always returns 0. 
* In base implementation of `node.init()` (not even sv_init, because this one is overriden everywhere) do `self.node_version = get_self.get_current_version()`.
* Introduce a new method in base node class, `upgrade_version(self, old_version, new_version)`. This method should re-setup node properties and sockets, considering that node was created with `old_version` of code, and current version of code is `new_version`.
* At event of scene loading, loop through all nodes that have `node_version != get_current_version()`,  and mark them as "needing upgrade" somehow (by using node.color or a frame).
* For actually upgrading node settings, I see two possible approaches:
  * Call `node.upgrade_version()` automatically at scene loading; This has obvious advantage, which is that user does not have to do anything to upgrade the whole setup.
  * Or have a special bpy.types.Operator, that calls `upgrade_version` for selected node, and a button for it somewhere, so that user would upgrade nodes manually. This has another advantage: Operator can interact with user somehow, for example ask for initial value of newly introduced property. But, in this approach, we must have in mind, that there can exist non-upgraded nodes, so in `process()` we will have to add checks like `if self.node_version == 0: don't try to use new properties`.
* Similar logic should be triggered after importing nodetree from json.
* Anyway, after `node.upgrade_version()` is called, we should do `node.node_version = node.get_current_version()`.
* When we want to introduce an incompatible change, we will have to:
  * override `get_current_version()` or increase version number in already existing override (just write `return 7` instead of `return 6` there).
  * override `upgrade_version()` or write a new branch in existing one (if old_version == 6 and new_version == 7: self.outputs.new(), self.new_property = default_value and so on)

Obviously, the new approach is to be used only for new situations when we would change nodes in incompatible way; already existing old_nodes will live as they are.

@zeffii @nortikin @DolphinDream any thoughts?

**Comment by zeffii** [comment]
counter arguments..

- there are not that many (if any..) nodes that are maintained past their move to the old_nodes graveyard.
- very few nodes share the current node directory with early MKs ( maybe just the Interpolation node )
- making an MK++ isn't that big of a deal, it is a nice opportunity to depart from older code.

the notion of auto upgrading using a node version attribute / function does appeal to me - something similar (but less developed) has been going through my mind for a while now. too. for the same reasons. Some parts of the node properties simply can't be replaced on the fly without introducing hideous code, i still don't see how that's going to be any easier with a formal "version control"

but.. i'm not a very smart person , so i'll probably re-read this a few times and squint my eyes a little.

**Comment by portnov** [comment]
Yes, there are pros and contras, that's why i'm not in rush to code this right now :) Just some thoughts on how this problem can be addressed. Maybe we can invent another solution that is simpler but solves the same problem.

**Comment by portnov** [comment]
@zeffii  proposed solution is nearly the same as you used for text nodes: we just need to have some sort of marker to know whether this node was upgraded or not; and with this marker we can either upgrade node settings, or just write some "if node is old: old code else: new code".

**Comment by zeffii** [comment]
@portnov i'm glad we continue this topic. It's one of the trickier issues - certainly when you consider the simplicity of the code we propose to the change sometimes.

**Comment by zeffii** [comment]
migrating a node to a new `bl_idname` tends to keep the resulting node clean, tidy up a few things that you might hesitate to touch otherwise.

we could offer a bl_idname upgrade operator utility, where the author optionally adds a section of code to add the replacement node and migrate properties/disconnect/reconnect/remove deprecated node.

**Comment by zeffii** [comment]
If we did head that way, I think once we get a few examples of bl_idname migrations snippets it won't seem so painful to quickly make a migrator for a "socket reindexing due to bl_idname++" or something.

**Comment by zeffii** [comment]
As soon as a node tree is loaded ( at the final stage of the event handle post_load_blend ) , 

- we could check if any nodes were deprecated, if yes, then toggle the visibility of a button in the NPanel to try to replace the nodes (one shot for all.. )
- we could offer a CollectionProperty / UI_Layoutlist that enumerates the deprecated nodes found in the tree, and put a button beside the node name with "attempt upgrade" , so user could step by step upgrade a node tree.
- the rightlick menu could understand the context of rightclicking with a Deprecation Frame selected, and offer the migration as a menu option. (maybe I like this best)

**Comment by DolphinDream** [comment]
I’d very much like to see a feature where you can easily upgrade an “obsolete” node in a tree with the new version of the same node. True, the new versions (MK#) may have a different socket layout (missing old ones, adding new ones etc) so it may not be possible for an out of the box replacement of the old with new keeping all the links in place, but if the nodes could be updated by keeping as many of the input/output socket links to the new node that would be pretty awesome.

**Comment by zeffii** [comment]
it's not hard, there will be many nodes that require only some of these steps

- first name the upgrade. f.ex "SvNodeMK1->SvNodeMK2"
- then obtain the current links
- if old node and new node have different socketnames make a map, for the reconnection
- if node has property renames/modified defaults, track those.
- track all propery values
- location , hidden state.

Some nodes will be trivial forthis, other nodes will definitely need massaging. The goal is really to make the sparsest possible representation of the node migration. I'm not in a hurry to do this.

**Comment by zeffii** [comment]
NodeWrangler contains a function i wrote to reset a node, much of  the same code can be reused.
https://blender.stackexchange.com/questions/42306/reset-nodes-to-their-default-values
