### ISSUE TITLE
Random Num Generator outputs array ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1964]
I noticed the Random Num Generator output is an array type. Is this supposed to happen ? Shouldn’t the output always be a list of lists?

![sv-randomnumgenerator-arrayoutput](https://user-images.githubusercontent.com/2083719/34314798-9d380fdc-e745-11e7-821f-24135c91f17b.png)

**Comment by enzyme69** [comment]
That's interesting because it's list of list on my computer:
![screen shot 2017-12-23 at 13 22 57](https://user-images.githubusercontent.com/3952687/34316225-6e302aae-e7e4-11e7-97b5-aa1469392450.png)

**Comment by enzyme69** [comment]
Ooh... you need to toggle "As List".

**Comment by zeffii** [comment]
By default to_list is enabled , this outputs numpy array when disabled, yes it's intentional. Read the code.

**Comment by zeffii** [comment]
By default to_list is enabled , this outputs numpy array when disabled, yes it's intentional. Read the code.

**Comment by DolphinDream** [comment]
Yeah.. thx for the tip @zeffii  I guess reading the code was also an option. ;) 
It’s the firs time I see an output that is NOT a list of lists/tuples.

**Comment by zeffii** [comment]
>  I guess reading the code was also an option. ;)

code is better than my crappy answers :) At the time i made `rnd num gen` we were contemplating adding a lot more numpy data nodes.
