### ISSUE TITLE
Shinning Star Rays project 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#1965]
Ever since I started meddling with SV nodes I was hoping one day I would be able to use SV to do this somewhat trivial “shining star rays” animation.. but I’m still having a hard time figuring this out. Any ideas what’s the best way to do this? hints are kindly appreciated :)

I have this static image (see below) and I want to make the rainbow textured rays wiggle/animate in and out radially and axially (subtle animation).. ignoring the center hallow/star for now, just the outer rays. What I would need to figure out is:

- make a tree node that creates the static rays of random lengths and widths
- apply the rainbow texture to each ray, with slight radial offset 
- animate the radial position (rotate around the center) of each ray (subtle drift CC and CCW)
- animate their radial length and width
- fade the rays in and out (new rays will appear and disappear as they animate)
- make each ray have subtle radial variation of the texture (darker streaks within each ray)

Honestly I can’t rally tell the exact end effect I’m after that would make it more “natural” as a shining star, but I was hoping that once I figure out how to implement these components it would be just a matter of fiddling with the settings to make the effect look more “natural".

![sv-shinningstarrays](https://user-images.githubusercontent.com/2083719/34314983-5f0b6210-e748-11e7-8ff5-5b770990985e.png)

[shinningStarRays.blend.zip](https://github.com/nortikin/sverchok/files/1583695/shinningStarRays.blend.zip)

**Comment by enzyme69** [comment]
Do you have reference of what looks you are looking for? That render looks quite nice already. I don't know if Compositor Artist can probably help with this?

Maybe the rays just needs to move slightly and subtly.

**Comment by DolphinDream** [comment]
@enzyme69  Here’s an attempt I did a while ago by simply scaling multiple versions of the image above. Obviously all rays in the image scale in and out which make it less natural to me (as I want each ray to scale individually). Needless to say that isolating these rays and animate them independently was a bit too much work than I wanted to take on. I bought this image off of a photo stock site a while ago and I doubt the author would be willing to share his/her secrets of how to make this with me :) I suspect that this was done in photoshop and was not based on an animated project, but I may be wrong. Either way, I don’t see why I wouldn’t be able to make this using SV (if i had enough SV knowhow).

https://youtu.be/kbm1fm41K44

**Comment by Durman** [comment]
My result
https://gist.github.com/b58779ec3b1ad09b4a196671cc048471
![2017-12-23_08-22-29](https://user-images.githubusercontent.com/28003269/34316885-90489592-e7ba-11e7-9820-48dd90318e87.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/34318270-ff48aece-e7c3-11e7-8202-819f4c4f2187.png)

i notice that CurveViewer doesn't read the value of `active` (UDP) , so it's always on. (bug)

**Comment by DolphinDream** [comment]
Thx @Durman The rainbow texture is radial, actually..from inside out : red-yellow-green-blue-purple. Also I can’t get your gist to work. Did you upload your proper tree for your above example ?

**Comment by DolphinDream** [comment]
A step closer ...

Now I need to figure out how to slowly drift each ray axially. Is there a **wiggle float** type of node in SV ? I want each ray to start at its initial random angle then have its angle slowly vary (noise) similar to a brownian motion perhaps. 

![sv-rainbowrays-demo1](https://user-images.githubusercontent.com/2083719/34321900-3be41ca6-e7e7-11e7-9dc5-fcd5ab0ee663.gif)

**Comment by DolphinDream** [comment]
My latest setup. 
I used an external rainbow texture though I think this could be easily generated via the SV texture nodes. I added a radial blur in compositor to smooth/smear out the rays. They are still pretty regular though (no radial streaks within each ray yet, like in the reference image).


https://gist.github.com/82b6405ff4fb4e4bb208134754bb88e6

![sv-shinningstarrays-01](https://user-images.githubusercontent.com/2083719/34321931-306b1964-e7e8-11e7-986e-789a35a0bdb1.png)

[shinningStarRays1.blend.zip](https://github.com/nortikin/sverchok/files/1584369/shinningStarRays1.blend.zip)

**Comment by zeffii** [comment]
various noise nodes, that also output float between 0...1 depending on the incoming vector. You could use that and remap to 0.8-1.2 (or something) to use as a multiplier for the inner or outer vectors.

**Comment by Durman** [comment]
[shinningStarRays_2017_12_23_19_13.gz](https://github.com/nortikin/sverchok/files/1584381/shinningStarRays_2017_12_23_19_13.gz)

![2017-12-23_23-13-09](https://user-images.githubusercontent.com/28003269/34322073-0e2432ba-e837-11e7-9b68-300fdc2b5e65.png)
![rays](https://user-images.githubusercontent.com/28003269/34322084-3f60a94e-e837-11e7-9ee9-c2fc83ef4c01.gif)

**Comment by zeffii** [comment]
there's also "modifier change"->"randomize input verts" ( you can randomize per axis, or just Z)

**Comment by DolphinDream** [comment]
Latest update... with slight radial drift. Btw.. forgot to mention, very important, this animation has to be loop-able :) so, nosy animation has to also be cycle-able. I’m not 100% happy with the result so far but it’s getting closer to what I was hoping for.

![sv-rainbowrays-demo2](https://user-images.githubusercontent.com/2083719/34324440-154ee3d2-e841-11e7-916c-f83cef9ab7e7.gif)

**Comment by zeffii** [comment]
i take it this is no longer needed.
