### ISSUE TITLE
Stethoscope Viewing goes funky on Retina Display (Mac)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1969]
<img width="567" alt="screen shot 2017-12-23 at 10 41 59 pm" src="https://user-images.githubusercontent.com/3952687/34319308-a9704f2e-e832-11e7-8ca7-ff224e517906.png">

Not sure if this is a known issue, but on **Retina Display**, Stethoscope text is not at the position and super tiny. Is this Blender thing that I did not know until today?

**Comment by zeffii** [comment]
there was a fix done a while back: https://github.com/nortikin/sverchok/issues/1593

**Comment by zeffii** [comment]
if you want, continue the issue there/
