### ISSUE TITLE
Line Offset and Grease Pencil, but without that Center Line ...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1971]
<img width="662" alt="screen shot 2017-12-24 at 2 23 49 pm" src="https://user-images.githubusercontent.com/3952687/34324048-4c41a512-e8b6-11e7-9b0a-8116624801f1.png">
<img width="798" alt="screen shot 2017-12-24 at 2 22 18 pm" src="https://user-images.githubusercontent.com/3952687/34324049-4c7294ce-e8b6-11e7-935b-3bd809a46d30.png">
[gp_to_lineXY_001_2017_12_24_03_22.zip](https://github.com/nortikin/sverchok/files/1584589/gp_to_lineXY_001_2017_12_24_03_22.zip)

I am testing the Line Offset with Grease Pencil. It works well and I can get a very nice mesh out of it as a flat XY projection.

Let say supposedly I wanted to ensure each points **not overlapping**, normally I would use something like **Vector Rewire**, offsetting by one.

But in this case, I am getting the center lines. That I wish I could just dissolve.

Just using the Outer Edges currently is the only solution, but it does not generate face along the lines, and if I just fill hole it does not always give a nice polygon face, because it is not "flat". Ideally there should be connecting lines for every points.

**Comment by enzyme69** [comment]
<img width="859" alt="screen shot 2017-12-24 at 2 34 47 pm" src="https://user-images.githubusercontent.com/3952687/34324074-9d5f7856-e8b7-11e7-83a7-f8877e65146d.png">
<img width="611" alt="screen shot 2017-12-24 at 2 34 44 pm" src="https://user-images.githubusercontent.com/3952687/34324075-9d915e7a-e8b7-11e7-8d75-dd9f35ae91b8.png">
[train_track_001_2017_12_24_03_34.zip](https://github.com/nortikin/sverchok/files/1584593/train_track_001_2017_12_24_03_34.zip)

Grease Pencil does not really have a proper "angle direction orientation" because it is always flat, if I am not wrong we have "tangent" somewhere.

I don't know @Durman maybe using Bending like above is the best for now?

**Comment by enzyme69** [comment]
Ok... after tinkering, probably this is the most ideal setup for now.

[train_track_002_2017_12_24_03_41.zip](https://github.com/nortikin/sverchok/files/1584594/train_track_002_2017_12_24_03_41.zip)

<img width="1097" alt="screen shot 2017-12-24 at 2 41 33 pm" src="https://user-images.githubusercontent.com/3952687/34324097-8c21a55e-e8b8-11e7-92fa-cfd5b4c87acc.png">

Maybe in the future Offset Line itself can understand orientation and the tangent to flow along grease pencil more smoothly?

**Comment by enzyme69** [comment]
Polyline Curve Viewer by @zeffii is doing this "tangent" thing, But I realized that the twist and turn also something that needs to be controlled if we want to make roller coaster.

<img width="721" alt="screen shot 2017-12-24 at 2 43 46 pm" src="https://user-images.githubusercontent.com/3952687/34324108-dcf1a222-e8b8-11e7-993e-4aa2506fc1e6.png">

**Comment by Durman** [comment]
@enzyme69 I can add z coordinate for output points that will be equal z coordinate of input mesh. But in this case can be a problem with normals if somebody will want to create loop by Z coordinate.)) Otherwise it is necessary to do heavy algorithm of calculation normals.

**Comment by enzyme69** [comment]
I guess that might complicate thing, actually.

Maybe for MK2?

I can see for now that the points will be flatten.

Ideally: it can project from camera or from other angle. And then generate
the mesh. This can be done I think with some other nodes trickery.

Will think on this. It is pretty handy node.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
the documentation is quite clear this expects only 2D data XY (it will convert any incoming 3D data into just the XY components) - https://github.com/nortikin/sverchok/blob/81df95cffae19c79394605438f1b9d7eaf4591ad/docs/nodes/alpha_nodes/offset_line.rst

If your goal in the end was a RollerCoaster , this is not the tool for that task. This is good for roofs, streets, lettering. Especially where there is no overlapping edges in the input mesh. (as in your first image - remember that's a singular ngon with highly irregular shape) -- that won't triangulate nicely (unless you force triangulate it)
