### ISSUE TITLE
Data recording.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1972]
If slightly change `text out` node it will be possible.))

![traking](https://user-images.githubusercontent.com/28003269/34324535-ce294f02-e88f-11e7-9427-f8e185fefb1f.gif)

@zeffii I didn't find how to delete letter in text editor via Blender API. Is it possible?

**Comment by zeffii** [comment]
Beware I  started a text in / out mk2.
I'm not sure what your question is.

**Comment by Durman** [comment]
I changed text out node thus
```Python
        bpy.data.texts[self.text].write(out[1:-1])
        bpy.data.texts[self.text].write(',')
```
And also I want to add something like this: that mean that I want to delete last letter in last string. )))
```Python
        bpy.data.texts[self.text].del(-1,-1)
```
I didn't find delete function [here](https://docs.blender.org/api/blender_python_api_2_78a_release/bpy.types.Text.html#bpy.types.Text)

**Comment by zeffii** [comment]
in python Strings are immutable, you cannot change anything about the string, you must assign a new string to it. It would be neat if the Text datablock had an abstraction that would let you do 
```python
textdata = bpy.data.texts[self.text]
textdata.delete_characters(index_start, index_end)
```
but it doesn't.

**Comment by zeffii** [comment]
so you end up doing
```python
textdata = bpy.data.texts[self.text]
current_string = textdata.as_string()
textdata.from_string(current_string + ", new content")
```
it's not as inefficient as that seems.

**Comment by zeffii** [comment]
in your scenario, if you want to remove the last character first, before append new data
```python
textdata = bpy.data.texts[self.text]
current_string_minus_last_char = textdata.as_string()[:-1]
textdata.from_string(current_string_minus_last_char + ", new content")
```

**Comment by zeffii** [comment]
if your output has a `\n` (hidden newline symbol) at the end of the string, then
```
current_string_minus_last_char = textdata.as_string().strip()[:-1]
```

**Comment by Durman** [comment]
Thanks @zeffii 
It works but Python algorithm of working with strings is really slow. ((

![traking2](https://user-images.githubusercontent.com/28003269/34328247-f1dba062-e8f3-11e7-8698-140486a25f2e.gif)
