### ISSUE TITLE
Offset Line node (Offset radius per point possible?)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1973]
<img width="350" alt="screen shot 2017-12-24 at 8 41 55 pm" src="https://user-images.githubusercontent.com/3952687/34325624-e613d38e-e8ea-11e7-8fb8-0f2f22dfdd92.png">

[line_to_leaf_01_2017_12_24_09_41.zip](https://github.com/nortikin/sverchok/files/1584728/line_to_leaf_01_2017_12_24_09_41.zip)

I am kind of curious of the possibilities to modify Offset Line node so that we can "scale offset" per points. To make something like a Leaft from a few points+edges, and passing offset radius per point (similar to PolylineViewerMK1).

Currently it is very cool already that it is vectorizing and works for multiple Lines input.

**Comment by enzyme69** [comment]
<img width="165" alt="screen shot 2017-12-24 at 8 41 18 pm" src="https://user-images.githubusercontent.com/3952687/34325634-55ea7366-e8eb-11e7-9be0-34e315cffc5e.png">

From the index, it looks like this might not be possible. 

But I suspect it is possible to do it another way...

**Comment by zeffii** [comment]
i have no idea what you're talking about. please re-edit your posts.

**Comment by zeffii** [comment]
if the essence of your question is this:

> Is it possible to modify it to allow "offset" per individual (original) vertex.

**Comment by zeffii** [comment]
I spoke with durman about adding support for per vertex radius, last week (so it would act more like SkinModifier / PolylineViewer. and be generally more versatile). You're question is not unique and certainly is the logical next step.

We don't need an open issue for this.

**Comment by nortikin** [comment]
please, vectorize someone )))

**Comment by Durman** [comment]
@nortikin 
I am not sure what does vectorize mean if it is about multiple values of offset socket it works now.

**Comment by nortikin** [comment]
yes, i see. it is vectorization itself
