### ISSUE TITLE
Node Help button is pointing to non-existing url (when we have not updated online docs recently)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1974]
When selecting a node and clicking on "Help Online" I was expecting to go to the node's documentation, but recent nodes often don't do this.

For example Online button for **Offset Line** takes users here:
http://nikitron.cc.ua/sverch/html/nodes/alpha_nodes/offset_line.html

~Supposedly~ here:
https://github.com/nortikin/sverchok/blob/master/docs/nodes/alpha_nodes/offset_line.rst
I am happy to check from time to time, but not sure how.

**Comment by zeffii** [comment]
http://sverchok.readthedocs.io | is rarely updated.
http://nikitron.cc.ua/sverch/html | is also not updated often

both need to be done manually.

That does present a problem, i might change those links.. or add a link to the current master/view.. A read on GitHub button: would link directly to https://github.com/nortikin/sverchok/blob/master/docs/nodes/alpha_nodes/offset_line.rst

**Comment by zeffii** [comment]
http://sverchok.readthedocs.io | is rarely updated.
http://nikitron.cc.ua/sverch/html | is also not updated often

both need to be done manually. In practice this means it doesn't happen with any regularity.

### However!

That does present a problem, i might add a "Read on GitHub" link/button, it would link directly to https://github.com/nortikin/sverchok/blob/master/docs/nodes/alpha_nodes/offset_line.rst

  - the downside: it doesn't look as nice as readthedocs with stylesheets
  - the downside: not easy to navigate to other docs
  - the upside: the docs will be viewable and show their images
  - the upside: there's no excuse not to be familiar with the docs.

### what then?

there are always ways to read it. Either the offline version (minus the images) or this directory contains the docs automatically.

https://github.com/nortikin/sverchok/blob/master/docs/

The Node heading in the N-panel has the `Offline` button, that always points to a directory on the users hard disk. (Never online....there's no way for the code to do that) -- it will point to somewhere like
```
scripts/addons_contrib/sverchok/docs/nodes/some_category/some_node_name.rst
```

**Comment by portnov** [comment]
@zeffii we might also put generated html pages at sverchok.github.io.

**Comment by zeffii** [comment]
portnov, yes maybe! but.. unless i'm entirely mistaken / or something has changed in the webrooting on `*.github.io` it may not be possible to have working hyperlinks within the documents.  Easy enough to verify on a different repository.

**Comment by zeffii** [comment]
you can now press the small "ghosting" icon beside the `online | offline` documentation buttons, to view the doc on github master directly.

Not sure if we'll get around to setting up an automatic / periodic online compiled doc job. This at least solves the immediate issue. the information is availabale.

**Comment by nortikin** [comment]
i was loaded at job. Before NewYear celebration.

**Comment by portnov** [comment]
I tried to build the docs and saw that we have some bugs in it (links pointing nowhere, topics not mentioned in TOC). Will do a PR for that.

**Comment by portnov** [comment]
see #2005 .
