### ISSUE TITLE
Snowflake

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1982]
I propose to hold a little competition for the best parametric snowflake.))
[Снежинка_2017_12_27_10_42.gz](https://github.com/nortikin/sverchok/files/1588849/_2017_12_27_10_42.gz)

![snowflace](https://user-images.githubusercontent.com/28003269/34379306-10c0b9a0-eb14-11e7-8758-7db7ab6efcdd.gif)

**Comment by enzyme69** [comment]
Ooo!! I've been thinking about it, but this is one of the best! Snowflake is arranged in hexagonal, wonder why.

**Comment by enzyme69** [comment]
Here is an example by Garman, Houdini artist.
http://garmanherigstad.com/shop-snowflakes/snowflake-carl

<img width="1056" alt="screen shot 2017-12-28 at 12 30 54 pm" src="https://user-images.githubusercontent.com/3952687/34397538-01642b42-ebcb-11e7-977c-2f17d2475d9e.png">

I remember Entagma talked about Snowflake... they always makes things so complicated!
http://www.entagma.com/creating-a-procedural-snowflake/

**Comment by enzyme69** [comment]
I am sure if you render out your one with nice material, you get a very nice looking snowflake! Snowflake is cool.

**Comment by enzyme69** [comment]
A friend took this photo, taken by C.Lee.
<img width="600" alt="screen shot 2017-12-28 at 12 32 53 pm" src="https://user-images.githubusercontent.com/3952687/34397573-43744b5c-ebcb-11e7-8fde-035a412a6ca5.png">

**Comment by Durman** [comment]
@enzyme69 
>I remember Entagma talked about Snowflake... they always makes things so complicated!

I will take a look.)
[Снежинка1_2017_12_28_05_22.gz](https://github.com/nortikin/sverchok/files/1590485/1_2017_12_28_05_22.gz)
![snowflakes](https://user-images.githubusercontent.com/28003269/34401011-a9878e1a-ebb0-11e7-8b09-8d55a239321f.gif)

**Comment by enzyme69** [comment]
![fancy_snowflake_001](https://user-images.githubusercontent.com/3952687/34406367-bdcb5404-ec0c-11e7-8e5d-c7493372417c.png)

I use fancy world.

**Comment by enzyme69** [comment]
<img width="441" alt="screen shot 2017-12-28 at 8 37 32 pm" src="https://user-images.githubusercontent.com/3952687/34406797-f43ce2e4-ec0e-11e7-9b8e-77c8a5b7967f.png">
[elfnor_snowflake_002_2017_12_28_09_37.zip](https://github.com/nortikin/sverchok/files/1590906/elfnor_snowflake_002_2017_12_28_09_37.zip)

Using elfnor tree but offset line failed, I don't know why...

**Comment by enzyme69** [comment]
<img width="1605" alt="screen shot 2017-12-28 at 8 46 51 pm" src="https://user-images.githubusercontent.com/3952687/34407012-4007f708-ec10-11e7-8c6d-8cfb802277bc.png">
<img width="428" alt="screen shot 2017-12-28 at 8 46 44 pm" src="https://user-images.githubusercontent.com/3952687/34407013-404bda68-ec10-11e7-9eb3-adaee3635103.png">

I think a bit too "branchy" but it has something.

Entagma does it in a weird reaction diffusion chemical kind of way. This elfnor space tree supposedly can do lightning as well.

[elfnor_snowflake_004_2017_12_28_09_47.zip](https://github.com/nortikin/sverchok/files/1590924/elfnor_snowflake_004_2017_12_28_09_47.zip)

**Comment by enzyme69** [comment]
I do really like the original post snowflake, just need to be rendered nicely as particles with sparks @Durman

**Comment by Durman** [comment]
@enzyme69  Tree generator is cool.))
[Snowflake3_2017_12_28_10_30.gz](https://github.com/nortikin/sverchok/files/1591031/3_2017_12_28_10_30.gz)
![2017-12-28_14-29-58](https://user-images.githubusercontent.com/28003269/34408229-048b2594-ebdc-11e7-9d22-54672765e22c.png)

**Comment by Durman** [comment]
https://gist.github.com/ecbce2c34cf33d79f86e7bef02e1956d

![2017-12-28_15-46-44](https://user-images.githubusercontent.com/28003269/34409966-876ff7f0-ebe6-11e7-8a4a-1b095c672834.png)

**Comment by Durman** [comment]
[snowflake_2017_12_28_12_51.gz](https://github.com/nortikin/sverchok/files/1591217/5_2017_12_28_12_51.gz)

![snowflakes2](https://user-images.githubusercontent.com/28003269/34411291-5079166a-ebef-11e7-985d-31653e374b62.gif)

**Comment by nortikin** [comment]
Happy NY and Christmas!!! and old NY!!!

**Comment by enzyme69** [comment]
https://blogs.scientificamerican.com/sa-visual/in-silico-flurries/?utm_source=twitter&utm_medium=social&utm_campaign=sa-editorial-social&utm_content&utm_term&sf178446986=1

**Comment by enzyme69** [comment]
@Durman I will breakdown your snowflakes and maybe use it for live noding :D So interesting!! Exactly what I need to make leaf, trees, etc... maybe fish bone?
