### ISSUE TITLE
Interpolation_mesh.py

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1983]
Idea:

![](http://api.ning.com/files/ElXMUm33IIVGDYbVLiS4UWqVQhEdViq85BjXX4vexHqjkVvQIkYa0d-t2zSOEbgcUQVNpquU8UYrgbojK0Xw9ZFKWiyc*pa6/Pf_Image18.jpg)

Rrealization:

![interpolation mesh](https://user-images.githubusercontent.com/28003269/34381840-85e51720-eb24-11e7-8f83-9529bc53cdb7.gif)
![2017-12-27_16-40-25](https://user-images.githubusercontent.com/28003269/34381866-ab4c2c42-eb24-11e7-9bdf-629085ac6751.png)
![2017-12-27_16-41-41](https://user-images.githubusercontent.com/28003269/34381889-d55f046e-eb24-11e7-85e8-c75a47813bb6.png)

```Python
"""
in verts_in v d=[] n=0
in faces_in s d=[] n=1
in t s d=0.5 n=1
out verts_out v
out faces_out s
"""
from sverchok.utils.geom import LinearSpline, CubicSpline
import numpy as np

if type(t) != list:
    t = [t]

verts_out = [[] for _ in t]    
faces_out = [faces_in for i in t]
t_corr = np.array(t).clip(0, 1)
for v in zip(*verts_in):
    spline = LinearSpline(v, metric = "DISTANCE", is_cyclic = False)
    out = spline.eval(t_corr)
    [verts_out[i].append(v.tolist()) for i,v in enumerate(out)]
```

**Comment by zeffii** [comment]
if you checkout my Curve In branch I also implement a Catmull interpolation (for single dimention values)..maybe a neat addition.

**Comment by portnov** [comment]
@zeffii It would be nice if Catmull would implement the same interface as LinearSpline and CubicSpline do. Then it would be possible to add Catmull mode to Interpolation mk3, Bend along [path, surface].

**Comment by zeffii** [comment]
@portnov  yeah, will do. can't promise how soon.
