### ISSUE TITLE
Vector in node, fullList to have a deepcopy alternative.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#1984]
![2017-12-28_14-36-41](https://user-images.githubusercontent.com/28003269/34408357-c391bc6e-ebdc-11e7-8197-c6dbc52092ca.png)

**Comment by zeffii** [comment]
Im not certain this is wrong, you should also show the textbased output,

**Comment by zeffii** [comment]
it's interesting however, that it's not symmetrical..  if you look at Vector In's source, maybe you can pinpoint why this is. Probably elements are extended to be as long as the first element, unless the current element is longer than the first or previous element.

**Comment by Durman** [comment]
After first cycle For, Y and Z coordinate are filled and have 5 elements. :/

![2017-12-29_10-08-29](https://user-images.githubusercontent.com/28003269/34430640-8da143aa-ec80-11e7-9bac-d47c12674a84.png)

**Comment by zeffii** [comment]
but is it _wrong_ or _unexpected_ or _undesired_. 

i understand the point you make, at one point we must have agreed that the current behaviour was desired, but I can completely agree that alternative behaviour might also be needed sometimes. It would need to be a MK2 with maybe a mode switch in `draw_buttons_ext` to go from `default mode` to `minimal mode`.

**Comment by Durman** [comment]
@zeffii 
>but is it wrong or unexpected or undesired.

Of course it is wrong. Look:
![2017-12-29_22-18-45](https://user-images.githubusercontent.com/28003269/34444287-812f1226-ece6-11e7-8f3d-c97ed9090686.png)
```Python
        for i in range(max_obj):

            max_v = max(map(len, (X_[i], Y_[i], Z_[i])))
            print('Y_ -', Y_)
            fullList(X_[i], max_v)
            fullList(Y_[i], max_v)
            fullList(Z_[i], max_v)
            series_vec.append(list(zip(X_[i], Y_[i], Z_[i])))
```
We can see here that `fullList(Y_[i], max_v)` didn't fill values for item object but do it for all objects.

**Comment by Durman** [comment]
@zeffii `fullList` function can work with nested lists correctly?

**Comment by zeffii** [comment]
i've had a few beers :) i don't know what to think about this.

i didn't write fullList but it appears that we focus how it works by passing it the least nested list possible, when extending its length.

see implementation:

https://github.com/nortikin/sverchok/blob/69058d106528a671a74394751b12ed6911dabe1c/data_structure.py#L151-L157

**Comment by Durman** [comment]
@zeffii I understood what is wrong. When we use fullList first time it create references on the last object, than when we use fullList second time we change one object but all objects are changed. Simple example:
```Python
from sverchok.data_structure import fullList
data = [[0]]
fullList(data,2)
fullList(data[0],2)
print(data)
```
We expected to see [[0,0],[0]], but:

![2017-12-29_22-58-30](https://user-images.githubusercontent.com/28003269/34445224-cf5ad052-eceb-11e7-86ea-d307856b81cb.png)

**Comment by zeffii** [comment]
yes, both objects inside `data` are the same object.. (by id... and by value)
```python
data = [[0]]
fullList(data,2)
fullList(data[0],2)
print(data)

for obj in data:
    print(id(obj))  # <---- this is the same value, both times.
```

**Comment by zeffii** [comment]
unlike in this example, where both objects with be a different `id`
```python
item_one = [0, 34]
item_two = [30, 0]
data = [item_one, item_two]

print(id(data[0]))
print(id(data[1]))
```

**Comment by zeffii** [comment]
something like
```python
# from sverchok.data_structure import fullList

def fullList(l, count):
     import copy
     """extends list l so len is at least count if needed with the 
     last element of l""" 
     d = count - len(l) 
     if d > 0: 
         l.extend([copy.deepcopy(l[-1])] * d) 
     return 


data = [[0]]
fullList(data,2)
for obj in data:
    print(id(obj))
fullList(data[0],2)
for obj in data:
    print(id(obj))

```

**Comment by zeffii** [comment]
and we might do something like this:
```python
for upper_register in lists:
    max_len = ...
    a = fullList_deep_copy(.....)  # <--- deep copy is important here..
    ...
    for lower_register in lists:
        max_len = ...
        a = fullList(.....)
        ...

```
we also have a parameter in `socket.sv_get(deepcopy=True)`, that would be an alternative option.

But whatever we do, consider that any change would need to be in an MK2, some people might be relying on the old behaviour ( which I think too, is probably incorrect...)

**Comment by zeffii** [comment]
we could keep it mk1 by doing 
```python
def fullList_deepcopy(l, count):
    import copy
    """extends list l so len is at least count if needed with the 
    last element of l""" 
    d = count - len(l) 
    if d > 0: 
        l.extend([copy.deepcopy(l[-1])] * d) 
    return

...

    def get_full_list_func(self):
        if hasattr(self, "deepcopy_mode") and self.deepcopy_mode:
            fullList_func = fullList_deepcopy
        else:
            fullList_func = fullList
        return fullList_func

    def process(self):
        if not self.outputs['Vectors'].is_linked:
            return
        inputs = self.inputs
        X_ = inputs['X'].sv_get()
        Y_ = inputs['Y'].sv_get()
        Z_ = inputs['Z'].sv_get()
        series_vec = []
        max_obj = max(map(len, (X_, Y_, Z_)))

        fullList_func = self.get_full_list_func()

        fullList_func(X_, max_obj)
        fullList_func(Y_, max_obj)
        fullList_func(Z_, max_obj)
        for i in range(max_obj):

            max_v = max(map(len, (X_[i], Y_[i], Z_[i])))
            fullList_func(X_[i], max_v)
            fullList_func(Y_[i], max_v)
            fullList_func(Z_[i], max_v)
            series_vec.append(list(zip(X_[i], Y_[i], Z_[i])))

        self.outputs['Vectors'].sv_set(series_vec)

```

**Comment by zeffii** [comment]
@Durman  I welcome you to propose an alternative algorithm that does output the desired data. add a BoolProperty in the class definition, and reference it in `draw_buttons_ext` and in `process`.

```python

class ...

    advanced_mode = BoolProperty(name='advanced deep copy')
    
    ...

    def draw_buttons_ext(self, context, layout):
        layout.row().prop(self, 'advanced_mode')


    def process(self):

        ...
        if self.advanced_mode:
            ... new code
        else:
            ... original code


```

**Comment by Durman** [comment]
@zeffii Yes, I'll do it soon.

**Comment by zeffii** [comment]
closing issue. cause established. we can continue talk in the PR 
https://github.com/nortikin/sverchok/pull/2019

should push soon.
