### ISSUE TITLE
sverchok/core/exceptions.py

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1986]
i'm not totally familiar with writing Exceptions, @portnov maybe some hints.

```python
class SvNotFullyConnected(Exception):
    def __init__(self, node, msg):
        logging.error(msg.format(node))
```
i haven't tried this yet, but i imagine _something_ like this would work for this case:
```python
...
if not all(socket.is_linked for socket in self.inputs[:2]):
    raise SvNotFullyConnected(self, msg="{{node.name}} needs input verts and edges to perform work")
...
```

**Comment by portnov** [comment]
My proposals:
* In `__init__` of specific exception classes, do `self.message = ...`, for example `self.message = msg.format(node)`.
* If there will be more specific exception classes, then add fields to them. For example: `node`, `socket`, ...
* The main idea is to encode as much information about error as much as we can in exception classes themselves, not in error messages. Thus, we could catch specific exceptions anywhere and process them specifically. Maybe even automatically connect nodes in some cases, for example. I remember I saw parsing a message string of exception somewhere in IOjson code - this is awful and should be avoided.
* Do `sverchok.utils.logging.exception(e)` in `try-except` construct somewhere in update_system.py (I believe it already is there).
* If we just need to inform user about error, which does not stop node processing ("You entered very strange values at inputs X and Y, but I will process them nevertheless"), then it is enough to write `self.error("...")`.

**Comment by portnov** [comment]
```python
class SvProcessingError(Exception):
    pass

class SvNoDataError(SvProcessingError):
...

class SvNotFullyConnected(SvProcessingError):
    def __init__(self, node, *sockets):
        self.node = node
        self.sockets = sockets
        socket_names = ", ".join(sockets)
        self.message = "The following inputs are required for node to perform correctly: " + socket_names
        # "Node %s have an exception: " part will be added by standard code in update_system.py automatically
```

```python
if not all(socket.is_linked for socket in self.inputs[:2]):
    raise SvNotFullyConnected(self, "verts", "edges")
```

```python
try:
    ...
except SvNotFullyConnected as e:
    for name in e.sockets:
        e.node.inputs[name].nodule_color = red
```

**Comment by zeffii** [comment]
looks good, i like standardizing the error message. but would maybe make it 
```python
SvNotFullyConnected(self, sockets=["verts", "edges"])
```
in anticipation of further parameters.

**Comment by zeffii** [comment]
> I remember I saw parsing a message string of exception somewhere in IOjson code - this is awful and should be avoided.

for co-readers, that refers to this line

https://github.com/nortikin/sverchok/blob/71a97e18052d21fd8f036d9be4fb37113e722d08/utils/sv_IO_panel_tools.py#L490-L506

**Comment by zeffii** [comment]
the real error is ( https://github.com/nortikin/sverchok/issues/1245 )
```python
TypeError: bpy_struct: item.attr = val: expected sequence items of type boolean, not int
```
i don't know if we can subclass the TypeError, to be really specifically triggered by that one scenario (even if the exact text of the error changed)

or if it makes more sense to indeed file a bugreport to Blender devs, as Ly29 suggested.

**Comment by zeffii** [comment]
```python
def is_compatible_assignment(e, node, p, val):
    if e.__name__ == TypeError:
        prop_ref = getattr(node.bl_rna, p)
        prop = prop_ref.bl_rna.properties.get('prop_types')
        if prop.is_array and prop.type == 'BOOLEAN':
            if isinstance(val, (list, tuple)) and isinstance(val[0], int):
                if prop.array_length == len(val):
                    return True

def apply_core_props(node, node_ref):
    params = node_ref['params']
    if 'cls_dict' in params:
        return
    for p in params:
        val = params[p]
        try:
            setattr(node, p, val)
        except Exception as e:

            error_message = repr(e)
            error(error_message)

            if is_compatible_assignment(e, node, p, val):            
                debug("going to convert a list of ints to a list of bools and assign that instead")
                setattr(node, p, [bool(i) for i in val])
            else:
                msg = 'failed to assign value to the node'
                debug("`%s': %s = %s: %s", node.name, p, val, msg)
```

**Comment by zeffii** [comment]
```python
>>> try:
...     nodes['Math'].prop_types = (0, 1)
... except Exception as e:
...     print(isinstance(e, TypeError))
### True
```
