### ISSUE TITLE
SNL Natural Object Name Sorting for Object Name With No Padding

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1987]
Once again I encountered a situation where Object sorting become an issue because of no padding on the names. Usually when using **Viewer BMesh** node and then using Objects In or passing the Object List for the next processing.

<img width="187" alt="screen shot 2017-12-29 at 9 11 08 pm" src="https://user-images.githubusercontent.com/3952687/34434820-fd3f6032-ecdc-11e7-80de-f5b1adc780bc.png">

So I created a bridge that sort the object by natural sorting.

SN LITE as below:
```
"""
in obnames s
out obsorted s
"""

# natural sorting for name without zero padding

import re
import bpy

#mylist = ['apple_10', 'apple_1', 'apple_12', 'apple_123', 'apple_2']

def natural_sort(l): 
    convert = lambda text: int(text) if text.isdigit() else text.lower() 
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(l, key = alphanum_key)

obnamesorted = natural_sort(obnames)

obsorted = []

for ob in obnamesorted:
    obsorted.append(bpy.data.objects[ob])
```

**Comment by enzyme69** [comment]
As a result the list is back to original sorting.

Object ID Sorting can probably do the job as well with custom index value, but that is for future user to figure out themselves.

<img width="177" alt="screen shot 2017-12-29 at 9 14 05 pm" src="https://user-images.githubusercontent.com/3952687/34434857-4be18bf2-ecdd-11e7-8e0e-0456cec830ff.png">

Basically what I am doing:
- I have bunch of list, containing XYZ and Color. All in order
- XYZ become position of objects, generated object for each position
- the generated object name padding is sorted unexpectedly
- the SNL above should resort it
- then I can color the object based on the original list data

**Comment by enzyme69** [comment]
Oh yeah btw I tried using **Exec Mod Node**, but I cannot "import re" for that node. Not sure why. @Kosvor2

**Comment by zeffii** [comment]
but you already can sort by object's index (using `object['idx']` as key ) --- If the objects are generated by a Sverchok Object node (like BMviewer etc...)

in ExecNodeMod.  just this one line.
```python
extend(list(sorted(V1, key=lambda obj: obj['idx'])))
```

**Comment by zeffii** [comment]
```
NameError: name 're' is not defined
```
we can/should fix that. It's a matter of adding `locals()` to the `exec(   )` context. Similar [to this change](https://github.com/nortikin/sverchok/commit/69058d106528a671a74394751b12ed6911dabe1c) 

in ExecNodeMod, you can do this too:
```python
def natural_sort(obj):
    import re
    return int(re.search('\d+', obj.name).group())

extend(sorted(V1, key=natural_sort))
```

**Comment by zeffii** [comment]
see

https://github.com/nortikin/sverchok/blob/69058d106528a671a74394751b12ed6911dabe1c/nodes/script/multi_exec.py#L192-L199

we can change it to
```diff
- exec('\n'.join([j.line for j in self.dynamic_strings])) 
+ exec('\n'.join([j.line for j in self.dynamic_strings]), locals()) 
```
and imports will work (in main body of the lines of text).

**Comment by zeffii** [comment]
i've just updated Sverchok. you can now write
```
from re import search

natural_sort = lambda obj: int(search('\d+', obj.name).group())
extend(sorted(V1, key=natural_sort))
```
in ExecNode Mod.

**Comment by nortikin** [comment]
lovely!
