### ISSUE TITLE
Using List Set and Then Actually Using It Properly - Magica Voxel VOX Reader

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1988]
<img width="904" alt="screen shot 2017-12-29 at 9 33 00 pm" src="https://user-images.githubusercontent.com/3952687/34435197-dc7c4808-ecdf-11e7-9907-f39341b5d81e.png">

[vox_reader_study_013_2017_12_29_10_32.zip](https://github.com/nortikin/sverchok/files/1592955/vox_reader_study_013_2017_12_29_10_32.zip)

I am working on **Vox Importer** (Magica Voxel) for Blender, and using Sverchok nodes to parse the list of data. I modified this Python code a bit from this code by Mate S:
https://github.com/MateSteinforth/ImportVOX/blob/master/import_vox.py

Ideally the code above can become a nicer SV node that can generate Voxel by reading the VOX file, maybe even frame by frame. The modified code above is printing out list of text, representing XYZ and color index. The Color Index number is interesting, basically 0-255 index number that will pick based on Palette (palette is 1 x 256 pixel dimension). I know that "List Set" can spit out non repeating list of 'Key'. Can be used like for dictionary.

From the supplied Blend example, there is 7 keys Index Color. Each should represent a Color based on list of data supplied.

So the actual question is:
Based on the List Set List or Keys, how do we set it in Sverchok so that each keys can return a supplied Color?

Originally I just use the Index this way:
- Index divided by 256 for HSV Hue Spectrum

<img width="956" alt="screen shot 2017-12-29 at 9 45 35 pm" src="https://user-images.githubusercontent.com/3952687/34435431-b94a5058-ece1-11e7-92e7-9daf20afcb4a.png">

- Index for List Item to grab from 255 

<img width="1032" alt="screen shot 2017-12-29 at 9 46 52 pm" src="https://user-images.githubusercontent.com/3952687/34435444-cd2d07be-ece1-11e7-9b83-b5538e83957e.png">

But supposedly I really only want to worry about a couple of color based on **List Set** I do not want to always generate 256 palette.

**Comment by enzyme69** [comment]
Wonder if I should make the "List Set" to become just another smaller "List Index" which then can just pick select from smaller number perhaps my own color.

**Comment by enzyme69** [comment]
<img width="329" alt="screen shot 2017-12-29 at 9 58 55 pm" src="https://user-images.githubusercontent.com/3952687/34435663-7ccc023c-ece3-11e7-96d0-63158560e060.png">

From List I seems to have a unique 8 "keys". 🔑 then supposedly somewhat I can supply list of 8 colors. How do I convert the keys back into index that can pick the colors?

Such simple, but I have no understanding of this.

**Comment by zeffii** [comment]
make a simple `python` program that can convert the last form of data you understand into the new form you are looking for.

try understanding that first. Then consider how you'd do that in Sverchok. If you can't write the python, then you can't explain it to me.

**Comment by Durman** [comment]
@enzyme69 I managed to understand your goal and I can offer you next:

![2017-12-29_21-45-55](https://user-images.githubusercontent.com/28003269/34443616-bf964ae8-ece1-11e7-9623-6fe00fdd4a88.png)
This can be more effective if to use SNL instead Exec node and to use 2 output sockets, one is for index mask (it is correct name for what you searched), two for the length of list of unique items.
[vox_reader_study_013_2017_12_29_17_53.gz](https://github.com/nortikin/sverchok/files/1593631/vox_reader_study_013_2017_12_29_17_53.gz)

**Comment by enzyme69** [comment]
Ok that makes a bit more sense. I will give a study.

It's based on the idea if we have given list of data, the total is 256 color slots, but the data has some missing index, maybe there are 5 of data, with index palette only 7, 3 , 123, 19, 29 being used. I like to care only for those 5 color data that I want to replace.

Anyhow, I will study first from @Durman , the whole process will be posted here @zeffii thanks again for sharing brain:
https://github.com/enzyme69/blendersushi/issues/242
