### ISSUE TITLE
Vertex Color MK3 expects input as RGBA

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1989]
A while back ago, I have this situation of wanting to colorize joined separate shell of a mesh (single objects with many shells) using Vertex Color. I talked with Ly and there was a solution like below:

<img width="443" alt="screen shot 2017-12-30 at 6 10 01 pm" src="https://user-images.githubusercontent.com/3952687/34452144-def78d42-ed8c-11e7-9757-fa64529fb228.png">
<img width="1109" alt="screen shot 2017-12-30 at 6 09 58 pm" src="https://user-images.githubusercontent.com/3952687/34452145-df29dda6-ed8c-11e7-8c19-605e61595499.png">

[coloring_separate_objects_001_2017_12_30_07_09.zip](https://github.com/nortikin/sverchok/files/1594221/coloring_separate_objects_001_2017_12_30_07_09.zip)

Seems like with Vertex Color MK3 things changed a bit. And this is no longer working.

**Comment by enzyme69** [comment]
Related to this:
https://github.com/nortikin/sverchok/issues/1140

**Comment by zeffii** [comment]
The only difference between MK2 and MK3 for the VCOL node is that one supports RGBA in Vertex Colors layer.  Latest version of Blender expect you to pass RGBA. 

MK2 and MK3 both expect parseable input.
![image](https://user-images.githubusercontent.com/619340/34452889-879c16dc-ed49-11e7-9a76-99c542f396c6.png)

**Comment by zeffii** [comment]
now this is my super lazy solution.
![image](https://user-images.githubusercontent.com/619340/34453044-35ec3bee-ed4b-11e7-95f9-b0405ef330bb.png)

but really, we could consider adding a feature to auto-fill the Alpha channel is the input vector (color) only has three components. I admit this is not friendly at the moment.

**Comment by zeffii** [comment]
VCol MK3 node doesn't use a real SvColorSocket, but it should soon. ( this won't change the situation, but it opens possibilities like building the automatic insertion of Alpha 1.0 into the data.. )

**Comment by enzyme69** [comment]
Cheers for in depth explanation @zeffii Will bring this into consideration. Cheers~
