### ISSUE TITLE
Bmesh Viewer Unwanted Linking for Duplicated Object

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1991]
[viewer_bmesh_coloring_002_2017_12_30_11_39.zip](https://github.com/nortikin/sverchok/files/1594338/viewer_bmesh_coloring_002_2017_12_30_11_39.zip)
![linked_somewhat](https://user-images.githubusercontent.com/3952687/34453878-625474c8-edb2-11e7-8a5a-dd8b90a5f3ea.gif)

I was playing around with Vertex Color node, and noticed an unusual behaviour when I am duplicating Bmesh Viewer output objects. Sometimes there seems to be link to previous object, even though I think it should not be.

Here in the blend, I am using Vertex Color to give random color per vertex per object. Somewhat under circumstances, the data seems to reset and link itself.

**Comment by zeffii** [comment]
as soon as you use the 3dview to copy / duplicate you are outside of what Sverchok can control. (or is aimed at )

**Comment by zeffii** [comment]
i think you'd need to duplicate unique. and remove all ID properties from those duplicated objects, else they will be included in the objects that BMViewer thinks belong to it.

expect stuff to be broken if you do this.

**Comment by zeffii** [comment]
as soon as you use the 3dview to copy / duplicate you are outside of what Sverchok can control. (or is aimed at )

i think you'd need to duplicate unique. and remove all ID properties from those duplicated objects, else they will be included in the objects that BMViewer thinks belong to it.

expect stuff to be broken if you do this.

![image](https://user-images.githubusercontent.com/619340/34454022-dd77ac16-ed61-11e7-9418-0a40e61d17f9.png)

**Comment by enzyme69** [comment]
Interesting I have just realized this! Thanks again~
