### ISSUE TITLE
Auto running nodes that use exec/eval upon .blend load / iojson load (discussion and review)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#1992]
The age old issue of running untrusted code, unintentionally.

- what is our approach to this currently
- can it be improved

currently: 

https://github.com/nortikin/sverchok/blob/d414c2e9f056e091c005d16c7f943becb463ecc6/core/handlers.py#L130-L151

our main defence is to have similar code in
  - the post handler for loading .blend files.
  - iojson tree loader. (pointless to rely on any code in the save/export portion)

```python
...

if security_level == 'prohibit_all':
    for node in nodes:
        if node in nodes_with_security_concerns):
            source = find_source(node)
            copy_source_to_disk_for_viewing_in_ext_editor(source)
            # do not add node to tree

    show_disk_paths_to_all_sources()
elif security_level == 'tentative':
    ...
elif security_level == 'trusted':
   # current behaviour.
```
security_level: `tentative`  could load all nodes but `hard freeze` the tree automatically so no node runs the process function.

security_level: `trusted`  current behaviour.

**Comment by zeffii** [comment]
these are the nodes enumerated that use exec or eval ( whether it is essential or not )
```python
caution_nodes = {
    'SvExecNodeMod',
    'SvSetDataObjectNodeMK2',
    'SvSetDataObjectNode',
    'SvBMOpsNodeMK2',
    'SvBMOpsNode',
    'EvalKnievalNode',
    'SvBMVertsNode',
    'SvScriptNodeLite',
    'Formula2Node',
    'SvScriptNode',
    'SvSetPropNode',
    'SvGetPropNode',
    'SvNumpyArrayNode',
    'SvFormulaShapeNode',
    'SvSortObjsNode',
    'FormulaNode',
    'VoronoiNode',
    'SvImageComponentsNode',
    'SvProfileNode',
    'SvProfileNodeMK2',
    'SvSpiralNode'
}
```
rather than tracking these nodes via a Set, it might make sense to add a property to the Sverchok node base class, something like 

```python
    uses_eval = BoolProperty(description="makes use of python eval")
    uses_exec = BoolProperty(description="makes use of python exec")
```
and we flip those to True on those nodes that use these features (also a form of explicit annotation), that way we don't have to track the Set.

**Comment by portnov** [comment]
The BoolProperty will be 1) saved per node instance, not per node class, 2) can be potentially changed programmatically. We can instead declare `class SvUnsafeNode(object): pass` (or several classes for different types of unsafeness, if you wish) and make all unsafe nodes inherit it. Then check for `isinstance(node, SvUnsafeNode)`.

**Comment by zeffii** [comment]
> The BoolProperty will be
> 1. saved per node instance, not per node class, 
> 2. can be potentially changed programmatically. 

at that level of shenanigans we'd have no defence anyway, we can check the class reference.
```python
>>> sn = sverchok.node_classes.get('SvScriptNode')
>>> sn.script_name
(<built-in function StringProperty>, {'attr': 'script_name'})
```

**Comment by zeffii** [comment]
am just throwing some thoughts out there..
```python

def test_node_safety(node=None, node_bl_idname=None):
    
    details = {}
    
    if node:
        node_ref = sverchok.node_classes.get(node.bl_idname)
        
    elif node_bl_idname:
        node_ref = sverchok.node_classes.get(node_bl_idname)

    if node_ref:
        node_ref.bl_rna.properties.get('uses_exec')
        node_ref.bl_rna.properties.get('uses_eval')
        node_ref.bl_rna.properties.get('unsecure_string')

    # if details returns {} that doesn't mean the node is safe, it just 
    # means the node is not registered in node_classes    
    return details
```

**Comment by portnov** [comment]
My point 1 is that if we have a node property, then theoretically one instance of SvScriptNode can be safe, while the second is unsafe. This is incorrect imho: the "unsafeness" property is a property of node class itself, not of it's instance. That's why I propose to encode it as class inheritance.

**Comment by zeffii** [comment]
i'm glad we're having this conversation, we've pushed it forward for too long.  Ultimately I don't really care how it's done, but i'd like the least amount of impact.

So. let's assume we settle on a method.

The nodes that do `return` as unsecure, need to be able to show me the string that would be evaluated/executed. Some nodes will need a `@property` we can read to return a dict of properties and values.

Sadly it will not help those who don't have a at least a vague understand of what the string could potentially do if exec/evalled.

**Comment by portnov** [comment]
Ah, you're suggesting to check if the property is present in node class, not to check property's value. Well, it will work. Though, a property whose value does not mean anything... :)

> The nodes that do return as unsecure, need to be able to show me the string that would be evaluated/executed. Some nodes will need a @property we can read to return a dict of properties and values.

Smth like:

```python
class SvUnsafeNode(object):
  def show_evaluated_string(self):
    raise AbstractMethodError("Unsafe node class must implement the show_evaluated_string() method")

class SvScriptNode(bpy.types.Node, SverchCustomNodeTree, SvUnsafeNode):
...
  def show_evaluated_string(self):
    self.info("Please check script text in `%s` text buffer", self.script_buffer_name)
```

and then

```python
if isinstance(Node, SvUnsafeNode):
  node.show_evaluated_string()
```

We might also want this method to return something to be processed by generic code, not directly display the message.

**Comment by zeffii** [comment]
my only concern about the addition of `SvUnsafeNode`, does that mean a node can be an instance of multiple classes?

```python
if isinstance(Node, SverchCustomNodeTree):
    ...
```
I would still like this to return True for nodes that inherrit from SvUnsafeNode .. does it?

**Comment by zeffii** [comment]
> We might also want this method to return something to be processed by generic code, not directly display the message.

yes, we could process the string for the presence of  
- imports like os / shutil / 
- cmd / os.process

i'm under no illusion that an automated search for known dangers is going to catch the persistent jack-ass.

**Comment by portnov** [comment]
> does that mean a node can be an instance of multiple classes?

Yes :) Python has multiple inheritance:

```python
    class Node(object):
       pass
    
    class SvUnsafeNode(object):
       pass
    
    class SvScriptNode(Node, SvUnsafeNode):
       pass
   
    class SvBoxNode(Node):
       pass
    
    script = SvScriptNode()
    box = SvBoxNode()
    
    print("Is Box it a Node?", isinstance(box, Node))            # Prints True
    print("Is Box unsafe?", isinstance(box, SvUnsafeNode))       # Prints False
    
    print("Is Script it a Node?", isinstance(script, Node))      # Prints True
    print("Is Script unsafe?", isinstance(script, SvUnsafeNode)) # Prints True
```

Moreover, if we once will want to subclass an Unsafe node, it will be unsafe automatically:
```python
...
    class SvSuperScriptNode(SvScriptNode):
-       pass
    
    print("Is SuperScript it a Node?", isinstance(script, Node))      # Prints True
    print("Is SuperScript unsafe?", isinstance(script, SvUnsafeNode)) # Prints True
```

**Comment by zeffii** [comment]
cool! i wasn't sure. I think that retract my original object to `SvUnsafeNode`

**Comment by portnov** [comment]
> security_level: tentative could load all nodes but hard freeze the tree automatically so no node runs the process function.

For user to be able to control this, I think we need https://github.com/nortikin/sverchok/issues/1990#issuecomment-354586202:
> Have a setting in addon preferences, how often to recalculate the tree: On any update / On update of node settings / Only manually.

So that in "tentative" mode the tree automatically switches to "only manual" mode.

**Comment by nortikin** [comment]
it is ostrich
