### ISSUE TITLE
Blender doesn't see the Sverchok plugin

### ISSUE THREAD

**Issue by yurivict** [nortikin/sverchok#1993]
I installed following instructions, but it just doesn't show up in the list.
First, it copied the files locally, under ```/home/{user}/.config/blender/2.79/scripts/addons```,  and it wasn't visible. Then, I moved the directory to ```/usr/local/share/blender/2.79/scripts/addons/```, and blender still didn't see it.

What is wrong?

blender-2.79 on FreeBSD 11.1

**Comment by enzyme69** [comment]
When installing the add-on, is there any error red message, or extra info on the console? You install from zip right?

**Comment by yurivict** [comment]
> When installing the add-on, is there any error red message, or extra info on the console

No

> You install from zip right?

Yes

**Comment by zeffii** [comment]
@yurivict have you installed blender add-ons before?

if you manually moved the files (as stated in the first post) then I can't be confident that you moved the right folder. Wherever you manually move the files you need this structure..

```
scripts/addons/sverchok/__init__.py
scripts/addons/sverchok/index.md
scripts/addons/sverchok/nodes
scripts/addons/sverchok/core
... etc ...
```
if you have `scripts/addons/sverchok/sverchok/,,,` it won't work. (notice two nested sverchok folders)
if you have `scripts/addons/sverchok-master/..` that will work (notice the `-master` is added by GitHub)

**Comment by yurivict** [comment]
I just installed other add-ons without a problem.
I only moved them when they failed at the local folder. And the moved one still didn't work.
Does blender show some log somewhere where I can see what went wrong?

**Comment by zeffii** [comment]
start blender from a terminal, it might show some add-on related errors. also you will need blender with numpy (precompiled usually?)

**Comment by yurivict** [comment]
> start blender from a terminal

That's how I started it, and it didn't show anything.

I press the button to install it, it prints this
```
$ blender
Read prefs: /home/yuri/.config/blender/2.79/config/userpref.blend
Modules Installed () from '/tmp/sverchok-0.5.9.6.2.zip' into '/home/yuri/.config/blender/2.79/scripts/addons'
```
the window closes, and Sverchok can't be found.

**Comment by zeffii** [comment]
oooooooooooooooh. i see, use `https://github.com/nortikin/sverchok/archive/master.zip`

**Comment by zeffii** [comment]
but if that creates
```
/home/yuri/.config/blender/2.79/scripts/addons/sverchok-master/sverchok-master
```
that's not correct. (unfortunately we can't control the exact file structure of the zip provided by GitHub)

**Comment by zeffii** [comment]
https://blender.stackexchange.com/a/39747/47

**Comment by zeffii** [comment]
i dont think "sverchok-0.5.9.6.2.zip" is a filename that works for python modules. I wouldn't not be surprised if this causes the loading of the addon to fail (or even show up in the list) . Remove that folder from scripts/addons and install using master.zip

**Comment by yurivict** [comment]
Yes, with master.zip it now works, thanks!
You need to update installation instructions, because I followed them and it failed to install.

**Comment by zeffii** [comment]
@yurivict I'll make the troubleshooting more clear. I obviously failed there.

**Comment by zeffii** [comment]
see https://github.com/nortikin/sverchok/blob/master/README.md#troubleshooting-installation-errors

this page shows the change i made to the existing installation / troubleshooting steps.

https://github.com/nortikin/sverchok/commit/8692c587a2ac7d6304fa5973d246c86d49a94b90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by zeffii** [comment]
"bug" in installation instructions / troubleshooting .

@yurivict  thanks for taking the time to check it out and sticking with it :)  much appreciated.

**Comment by yurivict** [comment]
@zeffii Thank you for working on this project!
