### ISSUE TITLE
Installation instructions should list prerequisite python packages

### ISSUE THREAD

**Issue by yurivict** [nortikin/sverchok#1994]
For me, py-numpy and py-requests were missing. Blender was installed with python-3.5 dependency and these were missing.

Just like regular python-based packages are expected to have a list of their dependencies (in setup.py), you should list them too (in instructions), so that people can save time.

Thanks!
Yuri

**Comment by zeffii** [comment]
that's a fair point. I do want to point out that we already list `numpy`.

https://github.com/nortikin/sverchok/commit/9b91cda641974419d7d54ba33db4798ed2bf3a93#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by yurivict** [comment]
Thanks!

**Comment by zeffii** [comment]
we've had a few issues on the tacker here by people with exactly this problem, i even wrote a replacement requests interface at one point. (that would kick in if `requests` wasn't found)

https://github.com/nortikin/sverchok/issues/1693 - sv_requests_fallback.py

**Comment by yurivict** [comment]
What you should do is encourage major linux distros to create packages for Sverchok.
Sverchok is a very advanced and slick software, and it certainly deserves to be installed as a package.
Packages are supposed to take care of fetching zips, dependencies, installation, etc.

I will create a port for FreeBSD. I am trying it on FreeBSD, and often create ports when they are missing.

**Comment by zeffii** [comment]
i don't think that will be my priority. anyone is welcome to do that however. -- and if it is useful to people i'm sure it will be appreciated.

**Comment by portnov** [comment]
I am not sure that it worth making packages... for example, in ubuntu/debian, to install a package, you need `sudo dpkg -i *.deb` or `sudo apt-get install sverchok` (notice the sudo part); while without the package you just need to download zip file and feed it to blender.

**Comment by portnov** [comment]
Well, if as a result of discussions in #1990 we will decide that we really want to write some part in C++, then we will have to offer some kind of binary packages (maybe even just a prebuilt `.tar.gz` for several platforms). Because building C++ part will be too tricky for many users.

**Comment by yurivict** [comment]
@portnov Dependencies might be missing, etc. The point of a package is that software is installed in one standard step, and after this it always just works. ```sudo apt-get install``` or ```rpm install``` are standard commands, they are always there.

**Comment by portnov** [comment]
Hmm. Dependencies is good point. However, i do not know how many our users use blender with "non-statndard" set of python packages; By "standard" I mean blender build downloaded from blender.org, because version from the linux is usually too old.

**Comment by yurivict** [comment]
> because version from the linux is usually too old.

People mostly use packages nowadays.

**Comment by nortikin** [comment]
we update every day sometimes. So master is uptodate
