### ISSUE TITLE
Typo on the website: "height level language" -> "high level language"

### ISSUE THREAD

**Issue by yurivict** [nortikin/sverchok#1996]
Also:
> Our approach is MATH + MESH + SPLINES + NURBS. Lets you

should be

> Our approach is MATH + MESH + SPLINES + NURBS. It lets you

also:
>  and uses a similar

should be

>  and it uses a similar

also:

> Great thank to all, who supporting us, it is appretiated, and exceptional thank to Pavel Kotelevets, who trust in us first.

should be

> Great thanks to everybody who is supporting us, it is appreciated, and exceptional thanks to Pavel Kotelevets, who had trust in us first.

**Comment by zeffii** [comment]
but i'd go for 

```diff
- Great thank to all, who supporting us, it is appretiated, and exceptional thank to Pavel Kotelevets, who trust in us first.
+ Many thanks to all who support us, it is appreciated, and especially thanks to Pavel Kotelevets, who backed us first.
```

**Comment by zeffii** [comment]
has been pushed to the page, thanks @nortikin
