### ISSUE TITLE
Spider Web AN by Karlis Stigis for study...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1997]
Perhaps this is a good study challenge for SV, I got this AN node setup from Karlis Stigis.

YouTube:
https://www.youtube.com/watch?v=NK_XYNpdTKQ

[SpiderWeb_KARLIS_STIGIS.zip](https://github.com/nortikin/sverchok/files/1597580/SpiderWeb_KARLIS_STIGIS.zip)

I looked at the design and jaw dropped, and also his way of PDF documenting and organizing the nodes... 

I realized I have only been at kindergarten level... 

There are a few SV list of things I wanted to generate properly:
- Jellyfish
- Some Insects
- Face 
- Spider Web (there are few examples out there, but that AN one actually surprising)

**Comment by enzyme69** [comment]
<img width="998" alt="screen shot 2018-01-03 at 12 44 35 am" src="https://user-images.githubusercontent.com/3952687/34485550-5d352612-f01f-11e7-9414-66e8b1919079.png">
[spiderweb_sverchok_002_2018_01_02_13_43.zip](https://github.com/nortikin/sverchok/files/1597658/spiderweb_sverchok_002_2018_01_02_13_43.zip)

Sometimes I do think I have very short life span on something.

There are lots of things I think Sverchok artists or myself already should make:
- Jellyfish
- Some insects creature
- Turtle Procedural
- Proper Mushrooms
- Spider Web --> the example by AN above was really impressive... he showed me the blend, but it was not shareable.

**Comment by nortikin** [comment]
he made maybe complicated scripted node for such generator

**Comment by enzyme69** [comment]
[spiderweb_vector_influence_002_2018_01_04_02_14.zip](https://github.com/nortikin/sverchok/files/1602255/spiderweb_vector_influence_002_2018_01_04_02_14.zip)

<img width="1235" alt="screen shot 2018-01-04 at 1 14 53 pm" src="https://user-images.githubusercontent.com/3952687/34547703-4a901408-f151-11e7-9725-18a454db7b62.png">

Yes quite fascinating nodes study. I guess it can be simplified in Sverchok, since Sverchok seems perfect for such cases.

**Comment by nortikin** [comment]
there was my comment somewhere i guess, it lost.

**Comment by nortikin** [comment]
https://gist.github.com/e6b8c843b86dac2c91cd443b1a580d87
![vector_influence_002](https://user-images.githubusercontent.com/5783432/34587268-b09c7144-f1b8-11e7-9583-d0fc4a7b5090.png)

**Comment by enzyme69** [comment]
Interesting @nortikin opening your example, I am getting a different result:
<img width="744" alt="screen shot 2018-01-05 at 11 57 45 am" src="https://user-images.githubusercontent.com/3952687/34591153-a86b5c4a-f20f-11e7-8588-c079c665278f.png">
[nortikin_spiderweb_001_2018_01_05_00_57.zip](https://github.com/nortikin/sverchok/files/1605224/nortikin_spiderweb_001_2018_01_05_00_57.zip)

Sverchok is perfect for spider web, I don't know how to explain, but we should have sophisticated result, I am pretty sure some day.

**Comment by enzyme69** [comment]
Inspiration:
https://thumbs.gfycat.com/UnderstatedKindEland-size_restricted.gif

**Comment by nortikin** [comment]
yes, list split in export import not change level to 1 if even 0 esteblished
[spiders_2018_01_05_22_40.gz](https://github.com/nortikin/sverchok/files/1608128/spiders_2018_01_05_22_40.gz)
