### ISSUE TITLE
Proportional Edit Influence Move

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#1999]
Is there some ways in Sverchok nodes to move some points proportionally, to get below result?

[vector_influence_001_2018_01_03_10_06.zip](https://github.com/nortikin/sverchok/files/1600000/vector_influence_001_2018_01_03_10_06.zip)
<img width="1260" alt="screen shot 2018-01-03 at 9 06 05 pm" src="https://user-images.githubusercontent.com/3952687/34516181-0e5535ae-f0ca-11e7-8c29-074d540c9456.png">

**Comment by enzyme69** [comment]
Kind of like a force to pull the line like psychedelic app. 

<img width="565" alt="screen shot 2018-01-03 at 9 08 56 pm" src="https://user-images.githubusercontent.com/3952687/34516246-55ec95a6-f0ca-11e7-9ade-d7dc2b5ec123.png">

(this is for my WIP spider web)

**Comment by enzyme69** [comment]
If I am not wrong, however, I made some kind of "reverse flower" setup at some point...

**Comment by portnov** [comment]
"Vector attraction" node?

**Comment by enzyme69** [comment]
@portnov Aha yes that's the one, I will check cheers~

**Comment by enzyme69** [comment]
<img width="1151" alt="screen shot 2018-01-03 at 9 18 29 pm" src="https://user-images.githubusercontent.com/3952687/34516617-ab644c1c-f0cb-11e7-9d6c-234cbc83705b.png">
[vector_influence_001_2018_01_03_10_18.zip](https://github.com/nortikin/sverchok/files/1600027/vector_influence_001_2018_01_03_10_18.zip)

**Comment by nortikin** [comment]
https://gist.github.com/1852b5b5afc1e82db362049c5fe6b58f
please, try my modification of your's

**Comment by nortikin** [comment]
https://gist.github.com/d0b0d2fca5fb8a7edfda3a29e5e659fd
new
