### ISSUE TITLE
Instances along Path that Orient and also Has Custom Normal Up

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2000]
I remember asking this in the past and Zeffii gave answer:
https://github.com/nortikin/sverchok/issues/1628

Now, if I am using Duplicate Along Path, I wonder how to get the "Normal" to orient out from nearest surface?

**Comment by enzyme69** [comment]
Here is what I got so far, and trying to incorporate the Zeffi solution above....


[raycast_points_normal_004_2018_01_03_12_16.zip](https://github.com/nortikin/sverchok/files/1600270/raycast_points_normal_004_2018_01_03_12_16.zip)
<img width="452" alt="screen shot 2018-01-03 at 11 16 54 pm" src="https://user-images.githubusercontent.com/3952687/34520361-6c84c2f4-f0dc-11e7-87a7-9b74b62936cc.png">

**Comment by enzyme69** [comment]
<img width="1019" alt="screen shot 2018-01-03 at 11 24 02 pm" src="https://user-images.githubusercontent.com/3952687/34520546-341433fe-f0dd-11e7-8e94-1c4c8fd4f572.png">
[raycast_points_normal_006_2018_01_03_12_23.zip](https://github.com/nortikin/sverchok/files/1600279/raycast_points_normal_006_2018_01_03_12_23.zip)

So this is kind of doing it, but does is really orient and also has up vector correct? Not sure... let's try monkey heads...

**Comment by enzyme69** [comment]
<img width="586" alt="screen shot 2018-01-03 at 11 27 34 pm" src="https://user-images.githubusercontent.com/3952687/34520656-b17468dc-f0dd-11e7-991d-4d4030a1a278.png">

It seems to be kind of orienting..

But the real question is if each Suzanne head is an edge that will be lofted like Ribbon, will it work?

**Comment by zeffii** [comment]
jimmy, edit your last post so there's a space between this

![image](https://user-images.githubusercontent.com/619340/34520715-28ff10ae-f08a-11e7-994d-394390e0c594.png)

it's this lack of space that fails to generate the correct response to markup.

![image](https://user-images.githubusercontent.com/619340/34520684-03672278-f08a-11e7-90eb-8cae8808c55a.png)

**Comment by zeffii** [comment]
jimmy, the same issue. The "normal" does not carry information about the orientation. For this reason you won't get correct 'rotational flow' along the surfaces, until we have some way to generate a 'minimized' tilting function. Minimized tilting would take a sequence of normals and output a list of Matrices that represent the Normal and Rotations to accomodate for the concept of Tilt.

**Comment by enzyme69** [comment]
[raycast_points_normal_009_2018_01_03_12_33.zip](https://github.com/nortikin/sverchok/files/1600310/raycast_points_normal_009_2018_01_03_12_33.zip)

<img width="474" alt="screen shot 2018-01-03 at 11 33 19 pm" src="https://user-images.githubusercontent.com/3952687/34520793-8a17a8e8-f0de-11e7-9a10-3f0446fe55d6.png">

Latest as above... reading Zeffii's reply.

**Comment by enzyme69** [comment]
Ok so this is here I am dealing with "Tilt".

**Comment by enzyme69** [comment]
So maybe we don't quite have solutions to get the tilt right and orient wrap along surface?

Maybe if duplicate along edge has "Custom Up Normal" we might have solutions?

**Comment by portnov** [comment]
Theoretically you can use it's "Matrices" output and replace rotational component of that matrices via matrix math.

**Comment by enzyme69** [comment]
If too hard we can close here and come back to it. I think the solution is out there.

**Comment by portnov** [comment]
But I am not sure what exactly do you want to achieve... If you do not like rotation that "Duplicate along edge" does, and it seems you are using it with just 1 object per edge... Then imho you most probably do not need this node, just "matrix normal" or "matrix track to" will do better.

**Comment by enzyme69** [comment]
Unfinish solution, but best for now?

[raycast_points_normal_009_2018_01_03_12_41.zip](https://github.com/nortikin/sverchok/files/1600336/raycast_points_normal_009_2018_01_03_12_41.zip)

<img width="637" alt="screen shot 2018-01-03 at 11 41 46 pm" src="https://user-images.githubusercontent.com/3952687/34521036-b0b6f4c6-f0df-11e7-8853-d8508aa3ce8d.png">

**Comment by enzyme69** [comment]
@portnov Maybe Matrix Tract To is the answer! I will check cheers!

**Comment by enzyme69** [comment]
However Matrix Track To node is a node I hardly understand it needs an example @portnov  @nortikin 

Checking docs.....

**Comment by enzyme69** [comment]
[raycast_points_normal_010_2018_01_03_13_01.zip](https://github.com/nortikin/sverchok/files/1600384/raycast_points_normal_010_2018_01_03_13_01.zip)

<img width="685" alt="screen shot 2018-01-04 at 12 01 28 am" src="https://user-images.githubusercontent.com/3952687/34521573-711878fa-f0e2-11e7-98c6-1d6f6e2a94c7.png">

**Matrix Track To:**
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/docs/nodes/matrix/matrix_track_to.rst

https://github.com/nortikin/sverchok/issues/1862

Quite possible that this is probably the most correct answer. Or pretty close.

I think I should probably just raycast the ribbon or something.

**Comment by enzyme69** [comment]
<img width="542" alt="screen shot 2018-01-04 at 12 21 43 am" src="https://user-images.githubusercontent.com/3952687/34522110-423757c4-f0e5-11e7-8490-bb90724f9ea6.png">

[lofting_raycasting_box_004_2018_01_03_13_21.zip](https://github.com/nortikin/sverchok/files/1600442/lofting_raycasting_box_004_2018_01_03_13_21.zip)

Maybe some kind of manual input lofting is best.

**Comment by portnov** [comment]
Eh, we have a two-thousand issue! :)

**Comment by nortikin** [comment]
somehow it will be 2018 issue
