### ISSUE TITLE
Want to make changes and adding some examples to documentation...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2002]
... but I need to make "Branch". Every single time I wanted to add to the Sverchok "Wiki". I have no idea about this. Maybe I should learn to make Branch?

For example:
https://github.com/nortikin/sverchok/blob/13a1b663bd090a07ec96687bab2990fdd94d3f88/docs/nodes/matrix/matrix_track_to.rst

That documentation needs some pictures. And maybe blend zip example.

**Comment by zeffii** [comment]
you can use the online interface. I think it's simpler than you realize.

step 1. Edit Online.

![image](https://user-images.githubusercontent.com/619340/34558286-c36721be-f13d-11e7-9f02-ed70035db439.png)

![image](https://user-images.githubusercontent.com/619340/34558406-4fc2b844-f13e-11e7-83e0-b4348b89b5c2.png)

2. Edit the text. and check the preview (to see what it looks like)

![image](https://user-images.githubusercontent.com/619340/34558488-9fc53736-f13e-11e7-9578-3bf8f1692027.png)

3. Commiting ...well. don't commit. First get the hang of it

instead do a single branch. it's easy.

![image](https://user-images.githubusercontent.com/619340/34558565-f9da18f4-f13e-11e7-986e-58b94d994dd9.png)

**Comment by enzyme69** [comment]
Will do, let see when I got something to add.

**Comment by zeffii** [comment]
you can _propose file changes_ for any file in sverchok, using this same process. It's especially great for one-liners or catching stray print statements.

just don't commit directly to branch. That's not the way we generally fix stuff. first confirm with someone else.
