### ISSUE TITLE
Making Sense of Vector Stripes Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2004]
Here is another node that gives me lots of "????". I read the documentation:
http://nikitron.cc.ua/sverch/html/nodes/vector/interpolation_stripes.html

But I still don't quite understand.

[vector_stripes_002_2018_01_04_08_50.zip](https://github.com/nortikin/sverchok/files/1602832/vector_stripes_002_2018_01_04_08_50.zip)

<img width="1274" alt="screen shot 2018-01-04 at 7 49 45 pm" src="https://user-images.githubusercontent.com/3952687/34555973-980120b0-f188-11e7-89d1-1b66810f64f2.png">

**Comment by nortikin** [comment]
stripes making same as bend on surface, but with attractors. maybe we should make remake of this node

**Comment by nortikin** [comment]
https://gist.github.com/036e5bb514b11ce88daeb8ae8e48fafc
![stripes](https://user-images.githubusercontent.com/5783432/34587714-907cc6fa-f1ba-11e7-8022-c23b3880a1a3.png)

**Comment by enzyme69** [comment]
@nortikin I see... this is that type of nodes require the "Slice" option. Thanks for this example!!
