### ISSUE TITLE
Wishlist: Vectorized Rotation

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2006]
[rotation_is_not_vectorized_001_2018_01_04_10_40.zip](https://github.com/nortikin/sverchok/files/1603075/rotation_is_not_vectorized_001_2018_01_04_10_40.zip)

<img width="1053" alt="screen shot 2018-01-04 at 9 40 37 pm" src="https://user-images.githubusercontent.com/3952687/34559916-ecf7f3aa-f197-11e7-86ec-ca349b699edc.png">

Very likely, Rotation node is not really vectorized. Compared to Move or Scale.

I think I mentioned this at some point a while back ago, but I was not sure how to explain it.

**Comment by nortikin** [comment]
yes, it is my deal. Will do on days

**Comment by nortikin** [comment]
it is vectorized. but in way of - object-to-object.
example
https://gist.github.com/4d0cf9afd9aa836abe55872d32e6ad64

**Comment by enzyme69** [comment]
I see... the Split seems to trigger it!
