### ISSUE TITLE
Inconsistent Normals indicator

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2009]
Is there a way in Sverchok to quickly spot normal that is going the opposite of its surrounding? This question was asked on Twitter by My Guru Price.

<img width="1250" alt="screen shot 2018-01-05 at 6 41 36 pm" src="https://user-images.githubusercontent.com/3952687/34599784-31a8061a-f248-11e7-930e-fcc923e1906a.png">

For sure there is addon out there we can just use and include in Sverchok.

**Comment by enzyme69** [comment]
For example:
https://blender.stackexchange.com/questions/87106/python-find-faces-with-incorrect-normals-to-flip-and-flip-them

Extrude might do it, but I am afraid it might slow for heavy mesh.

**Comment by enzyme69** [comment]
Just some kind of viewer of abnormal faces, since we already have "flip normal" node.

**Comment by enzyme69** [comment]
I tried, not sure if this is correct.. what do you think?

<img width="989" alt="screen shot 2018-01-05 at 6 59 25 pm" src="https://user-images.githubusercontent.com/3952687/34600236-915e3136-f24a-11e7-8c67-f7bf0950d2c9.png">
[abnormal_face_002_2018_01_05_07_59.zip](https://github.com/nortikin/sverchok/files/1605863/abnormal_face_002_2018_01_05_07_59.zip)

**Comment by enzyme69** [comment]
No apparently not quite right.

**Comment by portnov** [comment]
Huh. What do you mean by "abnormal"? Where should they point to?

**Comment by zeffii** [comment]
if all faces in the mesh have `normal` or `-normal` then you want Flip Normals node.

https://github.com/nortikin/sverchok/pull/1218 - this has a "Match" mode that flips 'negative' normals,

**Comment by zeffii** [comment]
> Just some kind of viewer of abnormal faces, since we already have "flip normal" node.

ok. no. but in terms of Sverchok; if you were really interested in understanding and providing a solution that that problem (rather than suggesting that "we" do it) you could read the source of FlipNormals node and in particular the "Matching" algorithm, and think of a way to make a SNLite to generate a mask output of normals that seem inconsistent.

**Comment by enzyme69** [comment]
@zeffii Sounds like a plan! Will close and study.

@portnov Abnormal because they are different than average.

**Comment by enzyme69** [comment]
Since Zeffii is already has some kind of abnormal algorithm, so I cheated:
[abnormal_002_2018_01_05_11_36.zip](https://github.com/nortikin/sverchok/files/1606448/abnormal_002_2018_01_05_11_36.zip)
<img width="1452" alt="screen shot 2018-01-05 at 10 36 44 pm" src="https://user-images.githubusercontent.com/3952687/34607720-f097c388-f268-11e7-954a-b09297d18785.png">

Face Normal gives 3 different values, not sure why, but anyhow I think this kind of doing the job :D

**Comment by enzyme69** [comment]
Seems to work on a plane 🙈

**Comment by zeffii** [comment]
@enzyme69   format your links properly man

**Comment by zeffii** [comment]
> Seems to work on a plane  

yeah, it expects all normals in the given mesh to be pointing in one direction, or the exact opposite direction (hence: `normal` or `-normal`. That's the bases of the _matching_ mode - ie "consistency".  As soon as you get single polygons in a mesh, any algorithm that attempts to detect whether the normal is correct will need extra finetuning and contextual information (surrounding polygons) and that increases the complexity of the algorithm, it also decreases the speed.

**Comment by zeffii** [comment]
if a small number of faces are flipped "randomly" while still attached to a mesh that has an obvious (local) normal direction and many neighbouring+attached faces (like torus / suzanne) then the recalc normal algorithm will take care of the outliers.

with detached polygons you'll get more complex approaches, so as to make it almost pointless to speak about the simplest implementation (unless that's exactly the scenario you are in.. if it's just a plane.. it'll work )
