### ISSUE TITLE
SNLite node depends on context

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2013]
I programmatically load node tree and try to export it. The code is in the "testing" branch: https://github.com/nortikin/sverchok/pull/2011/files#diff-2594045266f6e0898d61c2674cb78b0dR8

Basically what the code does is:

```python
# Link the whole node tree from reference blend file. link=True or False does not matter.
    with bpy.data.libraries.load(reference_blend_path, link=True) as (data_src, data_dst):
        data_dst.node_groups = ["TestingTree"]

# Obtain linked node tree
tree = bpy.data.node_groups["TestingTree"]

# Export it
export_result = create_dict_of_tree(tree)
```

Here is the blend file which I am loading: 
[script_uv_ref.blend.gz](https://github.com/nortikin/sverchok/files/1607051/script_uv_ref.blend.gz)

And this is what I receive:

```
ERROR: test_script_uv_export (tree_export_tests.ScriptUvExportTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/tests/tree_export_tests.py", line 13, in test_script_uv_export
    export_result = create_dict_of_tree(self.tree)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 298, in create_dict_of_tree
    node.storage_get_data(node_dict)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 493, in storage_get_data
    storage = self.node_dict[hash(self)]['sockets']
KeyError: -9223363294578807616
```

It looks like `self.node_dict` is called depending on current `bpy.context` somehow.

Found while testing #2011 .

**Comment by zeffii** [comment]
you are loading the nodetree from a .blend , and then exporting the resulting node_dict. 

i'm not surprised by this, but `hash(self)` needs attention there. it's being used in a untested way. I can suggest a way to get around that ( but am uncertain at this very moment.. )

**Comment by zeffii** [comment]
stick a print statement at the top of snlite's `storage_get_data` to print the keys that "are" in `self.node_dict`

**Comment by zeffii** [comment]
if it's empty, i think you will need to add a call to `make_new_locals(self)` then `storage = self.node_dict[hash(self)]['sockets']` will work.

**Comment by portnov** [comment]
Keys in self.node_dict: dict_keys([])

**Comment by portnov** [comment]
> add a call to make_new_locals(self)
Should this be added into test case? Or in node itself?

**Comment by zeffii** [comment]
```
def storage_get_data(self, node_dict):

        if not self.node_dict or not self.node_dict.get(hash(self)):
            make_new_locals(self):

        storage = self.node_dict[hash(self)]['sockets']

        ui_info = storage['snlite_ui']
        node_dict['snlite_ui'] = []
```

to the node itself. just to test it.

**Comment by zeffii** [comment]
```python
def storage_get_data(self, node_dict):

        if not self.node_dict or not self.node_dict.get(hash(self)):
            self.make_new_locals()

        storage = self.node_dict[hash(self)]['sockets']

        ui_info = storage['snlite_ui']
        node_dict['snlite_ui'] = []
```

to the node itself. just to test it.

**Comment by portnov** [comment]
Okay. This way it works, no exception.

**Comment by portnov** [comment]
Should this patch be applied to master? Or?...

The whole node_dict(hash(self)) thing looks like magic for me :)

**Comment by zeffii** [comment]
feel free to commit that with a comment 
```python
def storage_get_data(self, node_dict):

    # this check and function call is needed to allow loading node trees directly
    # from a .blend in order to export them via create_dict_of_tree
    if not self.node_dict or not self.node_dict.get(hash(self)):
        self.make_new_locals()

    storage = self.node_dict[hash(self)]['sockets']

    ui_info = storage['snlite_ui']
    node_dict['snlite_ui'] = []
```

**Comment by zeffii** [comment]
i suspect you will encounter the same missing node_dict keys for any node that uses node_dict and storage_get_data.

**Comment by zeffii** [comment]
a node's `self.node_dict`  must further distinguish itself from all other nodes of the same class by using a key that only it knows/can generate.  You can only ever store/get data from `self.node_dict` if you have a unique key. The fact that self.node_dict is empty in this scenario is a surprise but not really weird.

**Comment by zeffii** [comment]
it's the mechanism i like to use to store arbitrary data in a node/instance

**Comment by portnov** [comment]
Is `node_dict` a property of class? Because if it is a property of class instance, then I do not see how another instance can see it.

**Comment by zeffii** [comment]
it's a bit like recursion. You'll understand it when you understand it.

**Comment by portnov** [comment]
Huh :)

**Comment by portnov** [comment]
Okay, I think we can close this for now.

**Comment by zeffii** [comment]
it does bring up an interesting point, this is a feature that could be encapsulated in a mixin or something.
