### ISSUE TITLE
Script Node Lite for slicing Audio

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2018]
https://user-images.githubusercontent.com/3952687/34646012-33fc6766-f3b1-11e7-8b56-9b72f50a0c5c.png (big screenshot image..... )

[sound_chopper_009_2018_01_07_02_46.zip](https://github.com/nortikin/sverchok/files/1609447/sound_chopper_009_2018_01_07_02_46.zip)

I wanted to create some kind of Time Markers setup, giving **_start_** and **_end_** frames which later user can use to automatically slice and chop Audio from VSE.

Original script was based on [this BSE post](
https://blender.stackexchange.com/questions/62163/extract-audio-to-file-from-movie-clip-with-blender)

Perhaps not the best "node use" scenario. Maybe Python and CSV Text would be sufficient, actually. But I wanted to try this anyway.

I cannot seems to get it to work with **Script Node Lite** (keep getting maximum recursive error), maybe **Exec Node** is better? 

I keep wondering whether a button for SNL can be useful in such case. Calling the script only when button is pushed, not for every frame update.

**Comment by enzyme69** [comment]
Both Exec Mod and Script Node Lite is giving max recursive error... no idea why, never happened before. 💩 

<img width="488" alt="screen shot 2018-01-07 at 1 55 34 pm" src="https://user-images.githubusercontent.com/3952687/34646062-9e6ac6f0-f3b2-11e7-828f-a350672094e8.png">

**Comment by zeffii** [comment]
first i want to ask how you are inserting images, can't you just copy a screenshot into the mac's buffer and paste it into the issue? what's creating these html tags? ..even dragging an image from the desktop into the issue will generate the right markup

```text
<img width="488" alt="screen shot 2018-01-07 at 1 55 34 pm" src="https://user-images.githubusercontent.com/3952687/34646062-9e6ac6f0-f3b2-11e7-828f-a350672094e8.png">
```
github will do the right thing if you just paste, i think.

it will make 
```
![some_image](https://user-images.githubusercontent.com/3952687/34646062-.......094e8.png)
```
i'd really like to get you to stop auto-showing large images.

**Comment by zeffii** [comment]
instead of including the code of the snlite script in your screenshot, just copy it here man. always do that instead. Likewise the output into csv, .. just copy it and use backticks to tell markdown it's plain text or code.
<pre>
```python
def your_python_here(some_param):
    some_stuff = 10
```
</pre>
and csv
<pre>
```csv
20, 30
40, 20
50, 20
```
</pre>

produces

```python
def your_python_here(some_param):
    some_stuff = 10
```

and csv

```csv
20, 30
40, 20
50, 20
```

**Comment by zeffii** [comment]
this is the only part of the screenshot that you can't easily convert to text.
![image](https://user-images.githubusercontent.com/619340/34648000-97cec740-f391-11e7-909b-9a41a5a511d1.png)

**Comment by zeffii** [comment]
i see stethoscope is still outputting in the wrong place.

**Comment by enzyme69** [comment]
@zeffii I usually take screen shot and then attaching files by selecting them. Then I added space in between line like you suggested.

**Comment by zeffii** [comment]
so let me understand this. you want to manually write a csv with a list of start/end frames, you want to feed that those values to SNLite and let SNLite perform `main(start, finish)` for each pair of values.

yes, that's a little over the top. I suggest just using a script in the Text Editor for that.

the recursion error comes from the fact that your script is setting `scn.frame_start` and `_end`, this triggers a scene update and causes the nodetree to recalc.

**Comment by enzyme69** [comment]
Ok Zeff, thanks for confirmation. I will use Macro for this.

**Comment by zeffii** [comment]
Macro?

**Comment by zeffii** [comment]
with csv like this (that has a header to describe what these values are):
```csv
start,end
10,20
40,60
120,230
340,460

```

```python
import csv


some_path = r'C:\Users\zeffi\Desktop\GITHUB\times.csv'

def csv_row_iterator(filepath, delimiter, skip_headers=True):
    with open(filepath, 'r', newline='') as csvfile:
        ofile = csv.reader(csvfile, delimiter=delimiter)

        if skip_headers:
            ofile.__next__()

        for row in ofile:
            # >> ['10', '20']  needs to be converted into integers using int( )
            yield (int(column) for column in row)

for start, end in csv_row_iterator(some_path, delimiter=',', skip_headers=True):
    print(start, end)
```
then instead of printing the values, call the `main()`

**Comment by enzyme69** [comment]
Make sense that is a lot cleaner too. Node is overkill for such case indeed.

**Comment by zeffii** [comment]
nodes are meant for interacting with data,  for this operation you want to interact zero with the data, it's just a direct transform from `csv->function calls`.

**Comment by nortikin** [comment]
happy new Year!!!!

**Comment by zeffii** [comment]
happy new year back at you @nortikin  :)
