### ISSUE TITLE
Presets that modify nodes values instead of creating new ones

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2021]
@portnov With your SV Presets and Management JSON, is there a plan so that the Preset loading can actually simply modify existing node, modify the value, instead of bringing a group of node tree each time?

<img width="606" alt="screen shot 2018-01-08 at 9 28 25 pm" src="https://user-images.githubusercontent.com/3952687/34666942-dff5a1fe-f4ba-11e7-8653-83eb3491a29b.png">

**Comment by portnov** [comment]
No, this was not included in my initial requirements. That would be relatively complex task.

**Comment by enzyme69** [comment]
Ok, 👌 that's fine, I will think of something. Thanks for your preset addition btw, it would also be handy.

**Comment by portnov** [comment]
@enzyme69 Original discussion is #1998. Documentation is here: https://github.com/nortikin/sverchok/blob/master/docs/panels.rst (search for "presets").
