### ISSUE TITLE
nested data to evaluate in native way

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#2028]
https://github.com/nortikin/sverchok/issues/2003
do this node deal with nested data? i prefer all nodes to deal with nested data. but i think my fault was not to implement it at beginning. I left this question for future. Future is now.
Data has to be evaluated in any nested level, as i try to do in nodes of transformation here https://github.com/nortikin/sverchok/blob/master/utils/sv_recursive.py . And i donno if i do right. What do you think of it? how to solve? or only redux?
Thank you for propositions.

**Comment by Kosvor2** [comment]
How much more nested you want it to be?

**Comment by nortikin** [comment]
at least 5 levels in front of 3 by default.
because we allready have separate flag in generators and transformations and also we can makesubobjects

**Comment by portnov** [comment]
That was one of main ideas behind SverchokRedux. It is theoretically possible to implement it within current architecture, gradually, node-by-node. But that might take a lot much efforts...

**Comment by nortikin** [comment]
if we will have instructions on howto, than we will shortly do togather.
