### ISSUE TITLE
Map Range Does Not Vectorize

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2035]
<img width="979" alt="screen shot 2018-01-12 at 2 57 59 pm" src="https://user-images.githubusercontent.com/3952687/34859228-0f914116-f7a9-11e7-86c7-410b0e9575b1.png">

[maprange_vectorize_or_not_002_2018_01_12_03_58.zip](https://github.com/nortikin/sverchok/files/1624941/maprange_vectorize_or_not_002_2018_01_12_03_58.zip)

I have a feeling Map Range does not quite vectorize itself. But I might have asked this before.

**Comment by Durman** [comment]
It really don't work but you can use monad for this now.
https://gist.github.com/54b9cb2d7fcdb6455231befa2b4ac06c

![2018-01-12_08-24-43](https://user-images.githubusercontent.com/28003269/34859806-4793e898-f772-11e7-9b01-7ac983fe3e26.png)

**Comment by enzyme69** [comment]
Thanks @Durman ! Yes Monad is the way for now~
