### ISSUE TITLE
Class dependencies graph tool 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2037]
I wanted to get a view of what are the main components in SV and how are these linked to each other so that I can get a better understanding of SV inner working and how it is structured. Do you guys know of a python tool that can build a caller graph (UML ?) of sort (import based graph?). On that note, do you guys happen to have a diagram of sort showing what are the main components in SV and how they are interrelated ?

**Comment by portnov** [comment]
Googling gives https://github.com/thebjorn/pydeps :)

**Comment by portnov** [comment]
err, it's python2-only :/

**Comment by portnov** [comment]
https://modulegraph.readthedocs.io/en/latest/modulegraph.html This is more like it.

**Comment by portnov** [comment]
```python
#!/usr/bin/python3

import modulegraph.modulegraph as mg
import sys

sys.path.append("..")

g = mg.ModuleGraph()
g.import_hook("sverchok")
g.graphreport()
```

and then smth like

```
$ ./print_deps.py | dot -Tpng -o deps.png
```

The output will be huge, this thing draws all dependencies...

**Comment by portnov** [comment]
Draw only modules with "sverchok" in name:
```
./print_graph.py | gvpr -i 'N[match(name, "sverchok") >= 0]' | dot -Tpng -o graph.png
```

**Comment by portnov** [comment]
The exact result depends on which exactly module do you import in `g.import_hook()` line. This is what I got starting from `sverchok.utils.testing`:
![graph](https://user-images.githubusercontent.com/284644/34904659-653ca614-f86c-11e7-8a5d-2ae19339dcbf.png)

**Comment by nortikin** [comment]
Something i doing wrong
py file in git folder, sverchok folder in git folder, i cd to git folder and run:
```./print_graph.py | gvpr -i 'N[match(name, "sverchok") >= 0]' | dot -Tpng -o graph.png```
```bash
./print_graph.py | gvpr -i 'N[match(name, "sverchok") >= 0]' | dot -Tpng -o graph.png
bash: gvpr: команда не найдена
bash: dot: команда не найдена
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by portnov** [comment]
Well, you have to install graphviz (sudo apt-get install graphviz or smth like that) to actually draw the graphs.

**Comment by nortikin** [comment]
it makes blank small image... 

```
  GNU nano 2.7.4                 Файл: print_graph.py                           

#!/usr/bin/python3

import modulegraph.modulegraph as mg
import sys

sys.path.append("..")


g = mg.ModuleGraph()
g.import_hook("sverchok.nodes.number.formula2")
g.graphreport()
```
