### ISSUE TITLE
Scripted new nodes in Frame do not get valid xy locations.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2038]
It does not take into account the presence of the frame : See [sokets and frame](https://user-images.githubusercontent.com/28003269/34902801-3e828190-f83c-11e7-9fcf-c00bb6cef354.gif)

**Comment by zeffii** [comment]
: ) should be relatively easy to fix. thanks for reporting

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2039

**Comment by Durman** [comment]
Problem still exists. Auto connection don't know about frame movements. 
Should I to create separate issue with creating `ViewerDraw` and `stethoscope` by right click menu which have the same problem?

![sokets and frame 2](https://user-images.githubusercontent.com/28003269/34908479-9a0c4d8a-f8a9-11e7-840a-ce276a337277.gif)

**Comment by zeffii** [comment]
this is a different problem

**Comment by zeffii** [comment]
the rightclick "autolinking" in Frames and "quicklink" in Frames however, could share similar code to ensure they get the right location. ill reopen the issue.

**Comment by zeffii** [comment]
there's a bit of code in NodeWrangler that we'll have to consider (but write it dynamically)

https://github.com/gregzaal/node_wrangler/blob/ebe2b32f411604c2f5590d3c352dd19a40e6bd27/node_wrangler.py#L556-L567

**Comment by zeffii** [comment]
maybe
```python
def recursive_framed_location_finder(node, (locx, locy)):
    if node.parent:
        locx += node.parent.location.x
        locy += node.parent.location.y
        recursive_framed_location_finder(node, (locx, locy))
    else:
        return locx, locy
```

**Comment by zeffii** [comment]
This problem is also present in the IO/json importer when it deals with Framed nodes.. Solving this would help there too. 

 perhaps @portnov ?   i have a particular blind-spot for this problem.

**Comment by portnov** [comment]
I can investigate this, maybe this or next week.

**Comment by zeffii** [comment]
hmm i think this works. for quicklink anyway

```python
def recursive_framed_location_finder(node, loc_xy):
    locx, locy = loc_xy
    if node.parent:
        locx += node.parent.location.x
        locy += node.parent.location.y
        return recursive_framed_location_finder(node.parent, (locx, locy))
    else:
        return locx, locy

...
...
        if caller_node.parent:
            new_node.parent = caller_node.parent
            loc_xy = new_node.location[:]
            locx, locy = recursive_framed_location_finder(new_node, loc_xy)
            new_node.location = locx, locy
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2042

leaving the rclick menu node stuff for later, after more eyeballs confirm that _this_ solves the singular problem.

**Comment by zeffii** [comment]
the rclick menu will get something like
```


def frame_adjust(caller_node, new_node):
    if caller_node.parent:
        new_node.parent = caller_node.parent
        loc_xy = new_node.location[:]
        locx, locy = recursive_framed_location_finder(new_node, loc_xy)
        new_node.location = locx, locy

....
....

      offset_node_location(existing_node, new_node, offset)
      frame_adjust(existing_node, new_node)

```
we will put recursive_framed_location_finder into a util module, maybe consolidate between the different names for the same thing (caller_node, vs existing_node) to reduce potential confusion.

**Comment by zeffii** [comment]
this should be resolved now.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2045
