### ISSUE TITLE
Remesh and Voxel and Vector P

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2049]
## Problem statement

Wanting to turn Blender Remesh Modifier into XYZ Volumetric Voxel.

## Steps to reproduce

1. Create Remesh 3D of any geo
2. Bring into Sverchok
3. Fitting the Vector P into the XYZ is easy via Bounding Box

## Expected result

Expected to want to have the "center of each voxel".

## Actual result

I am getting the vertices positionl

## Sverchok version

0.072

## In the nutshell

I want to take advantage of @zeffii Vector P as Voxel generator too. Currently I am using dependency of Remesh Modifier. Maybe it is not necessary.

But basically wanting to Voxelize objects, in a way that it fits the Remesh Modifier.

<img width="500" alt="screen shot 2018-01-15 at 4 18 31 pm" src="https://user-images.githubusercontent.com/3952687/34928157-bd4ef556-fa0f-11e7-84b6-22630c31f35a.png">

[remesh_test_007_2018_01_15_05_16.zip](https://github.com/nortikin/sverchok/files/1630466/remesh_test_007_2018_01_15_05_16.zip)

**Comment by enzyme69** [comment]
<img width="774" alt="screen shot 2018-01-15 at 4 22 21 pm" src="https://user-images.githubusercontent.com/3952687/34928236-4786b420-fa10-11e7-828b-d3268d3d0225.png">

Not sure if this is correct, but may try anyway...

**Comment by enzyme69** [comment]
Yes, I think I need help. If we have XYZ mesh voxel vertices, how to find the center voxel?

**Comment by enzyme69** [comment]
There must be easy way to get the 3D center points at half way distance from every points.

**Comment by Durman** [comment]
My suggestion: )) But I forgot about remove doubles it have to be.
[remesh_test_007_2018_01_15_06_45.gz](https://github.com/nortikin/sverchok/files/1630626/remesh_test_007_2018_01_15_06_45.gz)

![2018-01-15_10-45-38](https://user-images.githubusercontent.com/28003269/34930126-6b569048-f9e1-11e7-9885-89abd1f30a17.png)

**Comment by enzyme69** [comment]
@Durman It might be one simpler solution for now, thanks I will use this for now!

**Comment by zeffii** [comment]
- object ID reads data post-modifier?
- callibrate the vector P parameters to match the remesh XYZ grid
- use data post-modifier as a base mesh, and vector P xyz grid as the 'to test' vectors, stick them into the `Is_Inside (mesh)` node, it will then spit out those Vector P points that are inside the post-modifier data.

```

                                                                   | is _ inside           |
                                                                   -------------------------
object (plust Remesh modifier) -> Object ID out -> Verts/Faces =>  | - mesh       inside - |
Vector P XYZ grid ---------------------------------------------=>  | - test                |
```

**Comment by enzyme69** [comment]
<img width="1011" alt="screen shot 2018-01-16 at 11 55 26 pm" src="https://user-images.githubusercontent.com/3952687/34990034-bda4d746-fb18-11e7-92ce-d0a7a9cf4e0e.png">

[vector_P_voxel_003_2018_01_16_12_55.zip](https://github.com/nortikin/sverchok/files/1635131/vector_P_voxel_003_2018_01_16_12_55.zip)

Yes, it is the relation between "Remeshed Objects", Bounding Box, Vector P that I am kind of wondering.

There must be a simple Math underneath 🥇 Must be. But I don't know it yet.

**Comment by zeffii** [comment]
Remesh Modifier unfortunately doesn't output data like 

1. num x/y/z grid divisions
2. gridpoint distances

but I think that can be calculated to some degree by using:

 - the bounding box of the base object
 - the octo-tree depth and `scale`
 - (maybe) GCD (greatest common divider) of the above mentioned variables

i have a vague recollection of needing to solve this in the past and succeeding (possibly I posted the answer on BSE too), but can not recall immediately or with certainty that this isn't something i've imagined.
