### ISSUE TITLE
BMesh Ops Grid Fill does not quite work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2050]
## Problem statement

Not sure exactly how Grid fill works, supposedly if we follow procedure like Ken shown here, it should fill the poly edge with grid:
https://twitter.com/khtrammell/status/952925513839935488

## Steps to reproduce

BMesh Ops expecting element that I could not understand... @Kosvor2 

[influence_001_2018_01_16_04_01.zip](https://github.com/nortikin/sverchok/files/1633603/influence_001_2018_01_16_04_01.zip)

## Expected result

I am expecting to see grid filled mesh.

## Actual result

I get error:
RuntimeError: bmesh operator: Select two edge loops

## Sverchok version

0.072

**Comment by enzyme69** [comment]
This might be a clue: the actual Grid Fill operation requires something... more.
https://blender.stackexchange.com/questions/50853/bmesh-grid-fill-doesnt-work-on-closed-edge-loop

**Comment by enzyme69** [comment]
Problem 2:
Wondering if this is also possible to close the hole.
[influence_002_2018_01_16_04_13.zip](https://github.com/nortikin/sverchok/files/1633613/influence_002_2018_01_16_04_13.zip)

**Comment by Kosvor2** [comment]
There must be "Bmesh elements" node somewere, which can output BMedges. It seems "Grid Fill" want list of edges which forms two separated parts of hole (while in Blender interface entire edge loop forming hole can be used), and hole itself must have an even number of vertices.

Not easy to use it in Sverchok.

**Comment by enzyme69** [comment]
Yeah, unfortunately that Bmesh operation is not node friendly. Maybe in the future. Cheers!

**Comment by nortikin** [comment]
https://github.com/Cfyzzz/Scripts/blob/master/mesh_gf_manager_13.py
