### ISSUE TITLE
Cross section and Bisect nodes create empty objects

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2054]
## Problem statement

`Cross section` and `Bisect` nodes create empty objects if the objects don't fit into section matrix. 

## Steps to reproduce

https://gist.github.com/a52791f3e5e6d9907156961a7d400485
![2018-01-17_10-58-30](https://user-images.githubusercontent.com/28003269/35029684-785eb99c-fb75-11e7-95e6-450793f0b2a6.png)

## Expected result

In this case objects should be deleted.

## Actual result

It is creates errors in the next nodes.

**Comment by Kosvor2** [comment]
Other nodes can create output like this too, im sure. Maybe we need sanitiser node which will be outputting healed lists and boolean mask to mask out other data if needed.

```
    def sv_init(self, context):
        self.inputs.new('StringsSocket', "data")
        self.outputs.new('StringsSocket', "san data")
        self.outputs.new('StringsSocket', "mask")

    def process(self):
        sd, m = self.outputs
        D = self.inputs[0]

        if sd.is_linked:
            sd.sv_set([d for d in D.sv_get() if d != []])
        if m.is_linked:
            m.sv_set([d != [] for d in D.sv_get()])

```

**Comment by Durman** [comment]
Yes, `vector interpolation` node also can receive an empty object.
`Exec` node can delete empty objects but it is need to use `socket converter` for vector data. It seems works.

![2018-01-17_14-06-34](https://user-images.githubusercontent.com/28003269/35037084-d30521d2-fb8f-11e7-9f43-5673dbc81cbe.png)
![2018-01-17_14-10-03](https://user-images.githubusercontent.com/28003269/35037169-2454bf02-fb90-11e7-8d1a-301e864c1a55.png)

**Comment by zeffii** [comment]
I'll also use the term "object" to mean a pair of Verts+Edges/Faces.

----

I don't consider this broken because we sometimes want to know which matrix doesn't produce an output, Nevertheless it does pose a valid problem.

we :
- can make a node that either filters out the "objects" that aren't complete
- or node can analyse the objects and generate a mask list

can't execnode also just do `[V for V in V1 if V]`  ?


or use execnode with simply `[V for V in V1 if V]` , but perhaps we should offer a node that takes

**Comment by Kosvor2** [comment]
This way also possible to filter out `None` objects which "scene raycast" node can output.

```
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode


class FixEmptieObjectsNode(bpy.types.Node, SverchCustomTreeNode):
    ''' filter out None or emptie object level items '''
    bl_idname = 'FixEmptieObjectsNode'
    bl_label = 'fix emptie objects'
    bl_icon = 'OUTLINER_OB_EMPTY'

    def sv_init(self, context):
        self.inputs.new('StringsSocket', "data")
        self.outputs.new('StringsSocket', "san data")
        self.outputs.new('StringsSocket', "mask")

    def process(self):
        sd, m = self.outputs
        D = self.inputs[0].sv_get()
        if sd.is_linked:
            sd.sv_set([d for d in D if d])
        if m.is_linked:
            m.sv_set([bool(d) for d in D])


def register():
    bpy.utils.register_class(FixEmptieObjectsNode)


def unregister():
    bpy.utils.unregister_class(FixEmptieObjectsNode)

```

**Comment by zeffii** [comment]
cool @Kosvor2   , remember to prefix these class names / bl_idname with `Sv`

**Comment by Kosvor2** [comment]
https://github.com/nortikin/sverchok/tree/filter_emptie_lists_node

**Comment by nortikin** [comment]
merge!

**Comment by nortikin** [comment]
but nestedness... vectorization...

**Comment by zeffii** [comment]
To summarize:

While this may seem like a bug in the mentioned nodes, it is in-fact a useful feature for parametric trees. Sometimes it's important to know when a set of parameters-mesh does not result in an output. The node proposed by kosvor will handle the output of such nodes in a way that will allow users to react to empty 'products' of the operation.

closing in the hope this triggers people to test the proposed node.
