### ISSUE TITLE
can i speed up this by numpy?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#2056]
my frame rate is about 0.8 when i play animation.
the file in here..
https://gist.github.com/c388cfbf0c041b8f77222c77e4a5c391

**Comment by Durman** [comment]
You can increase your speed dramatically if you will replace `Extrude separate faces` node with `Insert special` node.

![2018-01-18_10-08-09](https://user-images.githubusercontent.com/28003269/35083287-cb0da65e-fc37-11e7-8dd6-68001bb923f6.png)

**Comment by stansu** [comment]
it's working! thanks!
but, why?

**Comment by stansu** [comment]
Thanks

**Comment by enzyme69** [comment]
@stansu Nice example procedural animation there! I might use it in one my live noding for study. Do you have website or credit link?

**Comment by stansu** [comment]
I have a group on Facebook, it is call “sverchok Taiwan “

https://m.facebook.com/groups/327976844259432?ref=bookmarks

**Comment by zeffii** [comment]
> can i speed up this by numpy?

the current node does almost no Python manipulation of the mesh data - it calls bmesh.ops all over the place, there's no NumPy alternative to those functions. As shown by @Durman  the inset_specials node does pretty much the same thing entirely in Python, and it's already noticeably faster. Closing issue, but feel free to keep talking in it.

**Comment by stansu** [comment]
Where can I found some numpy example in sverchok?

**Comment by zeffii** [comment]
@stansu 
![image](https://user-images.githubusercontent.com/619340/35105745-b91b1c12-fc6c-11e7-8e6d-a99f4a2f8155.png)
