### ISSUE TITLE
Does Sverchok have Vertex Color In (not Out) node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2057]
Ok this is a weird question, I am sure that at some point Sverchok has Vertex Color In node. Hmm.. I might be wrong, but maybe it was Vertex Weight.

Currently if I export PLY as ASCII, I could very much get the vertex color as raw data.

**Comment by enzyme69** [comment]
<img width="1050" alt="screen shot 2018-01-18 at 7 33 19 pm" src="https://user-images.githubusercontent.com/3952687/35088054-7c507a74-fc86-11e7-9fde-8df0b62bd3f1.png">

I can do like above, but latest Sverchok has issue with Object ID... :( fun time,

**Comment by zeffii** [comment]
`i.color`  is a Vector() , you need to cast it to a simple data, `i.color[:]`

**Comment by enzyme69** [comment]
@zeffii Oh ok, alright that's now clear.

, but something still is not quite right, this error keeps appearing:

sverchok.core.socket_conversions.ImplicitConversionProhibited: Implicit conversion from socket type SvColorSocket to socket type VerticesSocket is not supported for socket Color of node Vertex color new. Please use explicit conversion nodes.

**Comment by zeffii** [comment]
yes, ColorOutMk2 will need a more lenient Socket conversion policy. that allows StringsSocket (the green nipple) to connect to ColorSocket (yellow nipple)

This extra check is something we've recently added, it will take a while before we iron out the usability issues.

**Comment by zeffii** [comment]
"whyyyyyyy make things harder for me"   i hear you think.

well, when this eventually settles down we will be able to have more types of implicit conversion schemes. (what does that mean) At the moment if you pass a vectorsocket to a matrix it will convert all vectors to a flat list of matrices, and nothing else. However, we might want certain nodes to be able to convert a vectorsocket's data into nested matrix lists (not flat),  this `ImplicitConversionPolicy` will help us be more flexible.

it's not a permanent break/regression.

**Comment by enzyme69** [comment]
Alrighty, I don't know what to do now 🗡  in order to make Object ID Set works like before. Hmm...

**Comment by zeffii** [comment]
learn to use `Git` (as i've suggested many times now...and given short tutorials ) and you can test our experiments before they hit `Master`. 

> Alrighty, I don't know what to do now

**Comment by nortikin** [comment]
[vertex-colors_wip_2018_01_24_17_43.gz](https://github.com/nortikin/sverchok/files/1660976/vertex-colors_wip_2018_01_24_17_43.gz)
motivated by post

**Comment by enzyme69** [comment]
@nortikin I have used Sverchok for a few years now, and hundreds of videos, probably just talking the basics, but your brain is at another level. You, zeffii and everyone else here is like alien. Seriously, your node tree is complex 👍

**Comment by nortikin** [comment]
but you making much better and complicated things with time.
Hope it will help you in life somehow.

**Comment by enzyme69** [comment]
@nortikin Very true, I'll absorb it.
