### ISSUE TITLE
Sverchok Object ID Select new error "ImplicitConversionProhibited"

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2058]
@Kosvor2  your awesome Object ID node is broken in latest SV update.... 😗

## Problem statement

Object ID select failed

## Steps to reproduce

Use Object ID Selector --> Object ID Set failed

## Expected result

I expect it to work normally without error

## Actual result

<img width="1474" alt="screen shot 2018-01-18 at 7 20 13 pm" src="https://user-images.githubusercontent.com/3952687/35087554-b0b9f238-fc84-11e7-92a4-09e3079bf3bb.png">

## Sverchok version

0.5.9.6

**Comment by zeffii** [comment]
@portnov  @Kosvor2  we need to check that these nodes use SvObjectsSocket , or relax `implicitconversionpolicy`

**Comment by zeffii** [comment]
@enzyme69 in future when showing us the error from your console, please copy the text by selecting it (whatever you need to do) and paste it directly into the issue. Screenshots are a bit of a pain (i can't edit those quickly to remove the non essential info )

**Comment by portnov** [comment]
@zeffii That seems a bit strange that some node produces something (not objects?) from StringsSocket output, and other node is required to consume that in ObjectsSocket... Is data inside in fact compatible?

**Comment by zeffii** [comment]
@enzyme69 provide a blend please, so all we have to do is open and look

**Comment by zeffii** [comment]
@portnov  some nodes passed objects before `SvObjectsSocket` was implemented, and i fear they have not been updated. Also.. some nodes might be outputting/inputted content into a single socket that depends on the context (so StringsSocket is reused for all kinds of output, input. )   not saying that's good.. but it was the solution at the time.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/35089916-8629d48a-fc38-11e7-84f6-3d9904825b05.png)

**Comment by zeffii** [comment]
also consider that we sometimes want to pass data that isn't strictly an `Object` in the sense of bpy.data.objects , but rather some deeper data type ..like VertexColor Layer or something

**Comment by enzyme69** [comment]
Ok yes sorry about the big image.

Here is zip, but all Object ID set operation does not work...
[object_id_bug_001_2018_01_18_09_39.zip](https://github.com/nortikin/sverchok/files/1642297/object_id_bug_001_2018_01_18_09_39.zip)

I guess let's revert to previous.

**Comment by zeffii** [comment]
this stuff will be slightly broken (or entirely broken..depending on your perspective) for a little while.
![image](https://user-images.githubusercontent.com/619340/35091397-d85cc81c-fc3c-11e7-92ce-144f29bef5b0.png)

**Comment by portnov** [comment]
@zeffii 
1) ok, I think we can add yet another exception to DefaultImplicitConversionPolicy: for SvObjectSocket, allow to connect any type of socket, as already done for StringsSocket.
2) 
> also consider that we sometimes want to pass data that isn't strictly an Object in the sense of bpy.data.objects , but rather some deeper data type

This actually does not matter, since we compare not type of data, but types of sockets.

**Comment by zeffii** [comment]
cool @portnov  i think it's necessary

**Comment by Kosvor2** [comment]
Fortunately, we can still insert from the obj socket into the data socket. But nodes that are designed to work with a list of at least two objects look strange with this property of selecting the object next to the obj socket.

![conver375623](https://user-images.githubusercontent.com/22656834/35091437-7da0c1d6-fc5e-11e7-8b9d-7d09f23b2921.png)

**Comment by zeffii** [comment]
> This actually does not matter, since we compare not type of data, but types of sockets.

yes, we might be passing vertexcolor layer data in a stringssocket to a SvObjectSocket. Socket type is not indicative of data

**Comment by zeffii** [comment]
@enzyme69 

> I guess let's revert to previous.

naw, take a break do something else.

**Comment by portnov** [comment]
@Kosvor2 I think it would be good idea to plan a Mk2 of "Object ID selector", which would have SvObjectSocket as output, not StringsSocket.

**Comment by zeffii** [comment]
else.. a temp solution for older files
![image](https://user-images.githubusercontent.com/619340/35103287-b51b9332-fc65-11e7-9a21-e5be06e2becd.png)
https://gist.github.com/zeffii/c981121becc6e3001b7860a3a45b6ffc

**Comment by zeffii** [comment]
but portnov, the implicit stuff might even work out of the box if the let SvObjectSocket inherit from SvSocketCommon (which it doesn't do..)

**Comment by zeffii** [comment]
oh i'm wrong.. it does inherit from it..

**Comment by portnov** [comment]
@zeffii that is just a strange idea to have socket named "objects" but not of SvObjectSocket type.

**Comment by zeffii** [comment]
@portnov  agreed. `Object ID select MK3` will need to happen.

**Comment by zeffii** [comment]
we came to a point a few years back where we removed restrictions from cross-socket connections, so it became a free for all -- as long as the socket could interpret the data in a meaningful way it wasn't an error. Now we have more formal cross-socket conversions, a few older nodes need to be brought into 2018. We should attempt to list the more common (or all) nodes that do this.

**Comment by zeffii** [comment]
@enzyme69  with @portnov's commit you should be able to use these nodes as per normal again. 
https://github.com/nortikin/sverchok/commit/f5abcee1dca76fee99e80133b09c58c72b6c7133
