### ISSUE TITLE
from sverchok.sockets import SvObjectSocket   HUH? :)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2059]
not sure why this `sockettype/class` is not included in the `node_tree.py`, but it makes me want to relocate all purely socket class related code in one file outside of `node_tree.py`. 

yay ? nay ?  not a massive job I think, but maybe deceptively so.  Not sure if worth it .  @portnov @nortikin

**Comment by zeffii** [comment]
maybe `core/socket_classes.py`.

**Comment by zeffii** [comment]
and because `core/sockets.py` is related only to SN3 (which didn't get much traction.. i would like to consider removing that file .... carefully )

**Comment by portnov** [comment]
We have some socket classes in node_tree.py, others in sockets.py. Have no idea why.

**Comment by zeffii** [comment]
see my last comment @portnov
