### ISSUE TITLE
sverchok terminology

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2061]
## Problem statement

A needed glossary of terms that you can encounter reading the issues or the source code. We get asked  to clarify terms, occasionally. The aim is to make a page in the documentation that we can link to. This is aimed at all users.

-----

##### nested (nestedness, nastyness)

lists of lists of lists. Practically this means: (Iterables of Iterables of Iterables .... )

##### Level

How many times information is nested. (show brief example)

##### Vectorized

This can mean various things, usually a combination of these:
- A node can take multiple pairs of Verts/edge/faces
- A node will auto generate incomplete incoming data (repeat last till end, or repeat in a loop), if the input data don't match length-wise. (use image to show) 

##### mk1, mk2, mk3

> Alpha, Beta, Mark1, Mark2, Mark3. 

All you can be sure of in the iteration from Alpha to Mark3 and beyond, is that each iteration step probably results in a new Node that isn't backwards compatible with the old node, meaning .blends using the old node will need small amounts of massaging (usually) to use the new version.  

##### Deprecated Node

or "Depreciated". When we upgrade a Node we still need to have the ability to load the old Node, we don't technically remove/delete the old node from Sverchok. We relocate the old node so that it isn't available in the node menu anymore. This means we keep the old Node around for an indefinite amount of time. This allows us to load old .blend files that contain the old node. When Sverchok encounters a file that uses an old node it will make it available for that Blender session (but it will not appear in Menus). To give you a hint that the node is old/deprecated we put a Frame around the node with the label "Deprecated Node". 

##### IO/JSON

it's a convenient way to share the node tree, you can upload your current pure-sverchok node tree as a github gist and paste into an issue. The reader only has to copy the link to the clipboard and can load it directly into their Blender. (show link to example )

##### Implicit Conversion

Connecting sockets of different kinds, is usually possible. Try Vector->Matrix

##### Monad

this is Sverchok's implementation of "Group Node" you might know from the standard node trees. It's a way to abstract away a collection of nodes, and define a limited number of parameters/sockets to the outside world. In one sense it is like making a Node by linking nodes instead of coding,

##### Viewer Nodes

There are two main types of Viewer Node:
   1. Viewer Draw
   2. Object Viewers

These nodes are used to output Vert/edge/face data into the 3dView.  We have nodes that just draw openGL to the viewport (Viewer Draw: VDMK+), and a collection of nodes that generate proper Blender scene objects of type Mesh/Curve/Metaball/Font (Object Viewer nodes).

Use the VDMK+ early on while getting to grips with Sverchok, then investigate the Object Viewer nodes.

##### Index Viewer

This node helps you see the indices of verts / edges / faces , and is drawn overlaid onto the geometry in 3d view. You'll know when you need this node.

##### N-panel (draw_buttons_ext)

Each node can be told to draw information into the Properties panel (press N while a node is Active to show it). We tend to add extra node properties there if their presence on the main Node UI would  complicate normal use.

**Comment by portnov** [comment]
Well, "nastyness" (in this exact form) appears somewhere in sverchok comments/docs, but it should not :)

**Comment by zeffii** [comment]
> "nastyness" appears .... in sverchok comments/docs, but it should not :)

it will be no surprise that I agree, and disagree. Yes we should use conventional terminology, but we can also acknowledge that the nesting levels are a little "nasty". Whether this was intentional use of the term by @nortikin (et all. ) at the time is less important to me than the message that particular word choice invokes. I happen to think it's nasty too.

But... i'd be fine with scrubbing the repo to use nestedness instead.

I don't know. leave it for now.

**Comment by nortikin** [comment]
kek.
nested
i did not know even there are two words

**Comment by zeffii** [comment]
if someone wants to make a `.rst` from this, do.    closing for now.
