### ISSUE TITLE
How to use Contour 2D weighted mode

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2063]
Quick question: with Contour 2D node, what is weighted means? I imagine, similar to Skin Modifier, we can someone Ctrl A in edit mode to increase or decrease weighting?

[contour_test_001_2018_01_19_04_12.zip](https://github.com/nortikin/sverchok/files/1645327/contour_test_001_2018_01_19_04_12.zip)
<img width="854" alt="screen shot 2018-01-19 at 3 11 15 pm" src="https://user-images.githubusercontent.com/3952687/35134553-212ed94c-fd2b-11e7-9809-55aa45d8ee1a.png">

I could not get the weighted thing to happen, I would imagine, if we provide weight values to each vertices?

**Comment by enzyme69** [comment]
Ok apparently it works kind of expected. Cheers~

[contour2D_test_001_2018_01_19_05_20.zip](https://github.com/nortikin/sverchok/files/1645409/contour2D_test_001_2018_01_19_05_20.zip)

<img width="813" alt="screen shot 2018-01-19 at 4 20 14 pm" src="https://user-images.githubusercontent.com/3952687/35135971-b086c56a-fd34-11e7-87a5-e82b8127a817.png">

**Comment by nortikin** [comment]
![offset-line2d](https://user-images.githubusercontent.com/5783432/35446607-4f812ed0-02c6-11e8-8dab-7fb539b3b572.png)

**Comment by Ribel78** [comment]
By connecting a list of numbers (that preferably should be as much as the vertices of the 2D shape) you can set different offset of the contour as shown in the image below (red shape).

![image 031](https://user-images.githubusercontent.com/15086376/35460570-31ac1bf0-02ed-11e8-983f-8e362cdddca2.png)

If you add different distances in Constant mode you'll get concentric contour shapes.
