### ISSUE TITLE
Curve 2D Matrix Input broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2064]
## Problem statement

Curve 2D node has Matrix In input slot. It stops working.

## Steps to reproduce

1. Create Curve 2D
2. Create Matrix In or plug in Vector In to the node input, it does not work.

## Expected result

Matrix In gives transform to Curve 2D

## Actual result

Error.
    coord_strip = lambda c: 0.0 if (-1.6e-5 <= c <= 1.6e-5) else c
TypeError: unorderable types: float() <= tuple()

## Sverchok version

0.072

**Comment by zeffii** [comment]
well. that error means `c` is a tuple() , interesting I get a different error..but it amounts to the same thing
```
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_viewer_utils.py", line 24, in <lambda>
    coord_strip = lambda c: 0.0 if (-1.6e-5 <= c <= 1.6e-5) else c
TypeError: '<=' not supported between instances of 'float' and 'tuple'
```
This probably never worked for this Curve2D node. I will make sure it does work in the Curve MK1 (which has 2D and 3D modes built into one Node)

**Comment by zeffii** [comment]
Another note to consider is that in 2D mode all geometry should be locally on `z=0`

**Comment by zeffii** [comment]
best you can do now is use Matrix Apply first. and just feed the node Verts/Edges and not the Matrix.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/35143316-863a788e-fd01-11e7-8b2e-56a49bfbd986.png)
