### ISSUE TITLE
SV JSON In and Out Study, strange things when dealing with Vectors and

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2074]
## Problem statement

I am studying JSON Text In and Out. Originally was looking at this preset color from ParaView app and it was JSON and I am thinking to make something similar in Sverchok.

Sverchok JSON accept certain data structure so I am testing some kind of setup that uses Sverchok to spit out JSON data and import it back in. 

Somewhat when I am using Random Vector and Absolute, the JSON is stop being readable.

## Steps to reproduce

1. JSON out JSON in.
2. Random Vector, make absolute.
3. JSON does not read.

## Expected result

I was expecting it would work.

## Actual result

I am getting error maybe data has changed.

## Sverchok version

0.072

[json_store_data_003_2018_01_22_01_55.zip](https://github.com/nortikin/sverchok/files/1650469/json_store_data_003_2018_01_22_01_55.zip)
![json_study_001](https://user-images.githubusercontent.com/3952687/35201987-ae375626-ff73-11e7-8e38-47d7ceb1440d.gif)

**Comment by enzyme69** [comment]
Ok, I realized why. It's because of the "key" name has changed and was not updating as I am changing the socket.

Would be nice to have the JSON data to reflect based on custom labeling. Wonder if this is possible?

**Comment by zeffii** [comment]
Whenever you disconnect a socket on the `Text Out+` node, it will check itself and write the json using the currently inputted nodes and socket names. I can see that in your scenario that's a bit unnecessary, however -- that's the way the node was designed, not taking into account that the user might change the nodes "mid session". There's no wrong or right there,, I might add a mode in the json mode to use to `Text Out+`'s own socket input names as json keys.

The `Text In+` also expects the json to be "stable" , and pressing reset will unlink nodes, 

So there's a few valid remarks to be made, which i'm quite happy to address (not sure when)
