### ISSUE TITLE
Vertex color mk3 node display gradients instead of solid color

### ISSUE THREAD

**Issue by Ribel78** [nortikin/sverchok#2077]
## Problem statement

Vertex color mk3 behaves strangely on my computer.
No matter what mode I select: Vert, Face or Loop it display the same (see the attached image)
For comparison the Vertex color new node behaves correctly with Vector in input (to set rgb values).

## Steps to reproduce

1. Create cube and set the Display mode to Texture to observe the result.
2. In Sverchok add "Object in" node and assign the Cube to it.
3. Connect the object output of "Object in" node to object input of "Vertex color mk3" with Vert mode enabled.

## Expected result

I expected to see vertices colored with the selected color

## Actual result

1. The Cube vertices are colored with different colors of, red green blue and black. The faces are colored in gradients.
2. Changing the color from the selector slightly affects the gradients. If you set it to Black the colors are most saturated, to White - all colors are white. In all other cases some color mixing occurs. If you set the alpha to 0.5 you can set all vertices to gray 50% with r g b set to 0.5 each.
3. Switching to Face or Loop mode, doesn't change a thing.

[image 014](https://user-images.githubusercontent.com/15086376/35219230-7de98b72-ff7a-11e7-8073-3dfe372c5ea5.png)
[image 015](https://user-images.githubusercontent.com/15086376/35219235-81e8d192-ff7a-11e7-88cb-6730f7c33c21.png)
[image 016](https://user-images.githubusercontent.com/15086376/35219237-84ebbdf0-ff7a-11e7-9a98-dcfc70f7b284.png)
[image 017](https://user-images.githubusercontent.com/15086376/35219239-86b742da-ff7a-11e7-9728-b02a93d89b2b.png)
[image 018](https://user-images.githubusercontent.com/15086376/35219253-8c06d8ea-ff7a-11e7-836e-51f37582d137.png)
[image 019](https://user-images.githubusercontent.com/15086376/35219255-8e635fbe-ff7a-11e7-9d28-e067f2f6b2b5.png)

## Sverchok version

SV 0.5.9.6 (2b70c71)
I usually update Sverchok using the Check for updates button in the Version panel.
This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

Also I use the official Blender 2.79 release

**Comment by zeffii** [comment]
Blender 2.79 Release (win 64) shows this
```
>>> bpy.data.objects['Cube'].data.vertex_colors[0].data[0].color[:]
(1.0, 1.0, 1.0)
```
This means you need to use "Vertex Color New"  , which supports Colors of size 3.
-----------------
However, recent nightly 2.79 builds return `(1.0, 1.0, 1.0, 1.0)` , and we made `Vertex Colors MK3` to support that.

**Comment by zeffii** [comment]
and... further updated  https://github.com/nortikin/sverchok/pull/2078

**Comment by zeffii** [comment]
@kosvor you want to try 2078 locally, test it for 2.79 Release and 2,79 Nightly build.

works here, and @Ribel78  the gradient stuff can be resolved if we commit this patch and you set the Node to RGB mode (if you don't want to update to Nightly 2.79 builds...)

**Comment by zeffii** [comment]
if it's tested then we can relocate Vertex Colors MK2  to old_nodes.

**Comment by zeffii** [comment]
@kosvor you want to try 2078 locally, test it for 2.79 Release and 2,79 Nightly build.

works here, and @Ribel78  the gradient stuff can be resolved if we commit this patch and you set the Node to RGB mode in the N-toolshelf Properties panel (if you don't want to update to Nightly 2.79 builds...)

**Comment by Kosvor2** [comment]
Going to sleep. Just merge everything in and later will see.

**Comment by zeffii** [comment]
: ) OK.

**Comment by Ribel78** [comment]
@zeffii, If it is not a bug, I don't mind if not being fixed for previous versions of Blender. 
However, some kind of notification for the users that specific node may not work with older versions of Blender would be nice. Like in this case the node don't give an error and that may leave the impression that the user is doing something wrong.

**Comment by zeffii** [comment]
@Ribel78  yeah, i've contemplated some automated testing of bpy upon Sverchok registration, maybe build date.
```python
import bpy
import time

vertex_color_update_timestamp = DOOMSDAY
blender_build_date = bpy.app.build_date.decode('ascii')
build_timestamp = time.strptime(build_date, '%a %m/%d/%Y')

build_timestamp > vertex_color_update_timestamp:
    sv_prefs.num_vertex_color_layer_components = 3
```

i realize this is a painfull introduction to vcols in sverchok

**Comment by zeffii** [comment]
@Ribel78  for now it's not worth making at automatic detection. within the next few days 2,79a release will also include rgba. None the less i've removed `vertex colors mk2`, and allowed mk3 to have a switch that lets you set RGB or RGBA.  You should update sverchok

**Comment by Ribel78** [comment]
@zeffii But I learned a lot ;)

**Comment by enzyme69** [comment]
@zeffii You
<img width="717" alt="screen shot 2018-01-30 at 12 30 06 am" src="https://user-images.githubusercontent.com/3952687/35512688-c0c2acdc-0554-11e8-8244-964eef35088e.png">
 removed the old Vertex Color? I still don't quite get the new one....

[test_normal_001_2018_01_29_13_30.zip](https://github.com/nortikin/sverchok/files/1673696/test_normal_001_2018_01_29_13_30.zip)

Can we have an example blend and documentation please.

**Comment by enzyme69** [comment]
@zeffii Never mind I figure out the special RGB option! Cheers~
