### ISSUE TITLE
Inconsistency of the contents of Beta Node in Tool Shelf and in Dropdown Menu

### ISSUE THREAD

**Issue by Ribel78** [nortikin/sverchok#2080]
## Problem statement

The contents of Beta Node is different.

## Steps to reproduce

1. In Tool Shelf click on the vertical tab Beta Nodes (I hate vertical tabs :))
2. In compositor window press Shift+A -> Beta Nodes
3. Compare the contents

## Expected result

The content should be the same in both places.

## Actual result

In Tool Shelf - Beta Nodes have the same content as the Alpha Nodes in the context menu.

## Sverchok version

SV 0.5.9.6 (2b70c71)

**Comment by zeffii** [comment]
This is intentional, shift - a, is a bit more refined than the T-shelf and header add nodes menu.

Its a fine observation , but its not something I consider broken, though the sense of inconsistency is not lost on me. There are some technical limitations to the way pynode api auto populates the default menu. At the time I decided to generate my own menu with more customized options, and those options make little sense in the  t-shelf.

**Comment by Ribel78** [comment]
Can't you simply Switch the names of the Alpha and Beta Nodes menus?

**Comment by zeffii** [comment]
we could add Alpha category to the standard menu, that would make at least the Beta / Alpha categories consistent. That would be a minimal change, but there are other inconsistencies between the Shift+A and (Header->Add, or T-Shelf) menus. The pynodes API doesn't provide nice customization options, and abstracting away this inconsistency involves ugly code that I'm not going to add.

Maybe I should just say that we are conscious of the inconsistency, but recommend you use the Shift+A menu or the Ctrl+Space (custom search) menu to locate nodes.

**Comment by zeffii** [comment]
I'll try to explain this from about 10 km high.

- PyNodes API auto populates the `NodeView:T-Shelf` and the `NodeView->Header->Add` as soon as the Nodes are registered during Sverchok startup. It does this using a list of Categories and associated Nodes per category. This generates something what we can call the "Standard Categories/Menu"
- The PyNodes API automatic Menu generation doesn't have submenus, or any way to add them (nicely).
- Team Sverchok wanted a more flexible menu structure with submenus, meaning we had to "manually" define a Menu. This menu is what is now triggered from Shift+A.
- Ideally I would be able to replace the Menu in `NodeView->Header->Add` with the Shift+A menu, and I wrote code some time ago that could do this but it's not worth the extra code. It's just hacky, in a bad way.

The end result is this inconsistent feeling between the standard menus and the Shift+A. If that's a problem, I get it.. but there's not a whole lot I wish to do about it. Shift+A or Ctrl+Space are the "power tools" of the addon.

I might modify the Standard Categories to rename Beta (which currently holds both Beta and Alpha nodes... but their actual distinction is pretty nebulous at best) .. rename it to "Pre Release Nodes". Meaning those nodes would appear in that Category in the menus that display the Standard Categories,, and only in Shift+A menu it would they be separated into Beta and Alpha. Not a big change to do that.. much less work than writing this...   but I don't want to do that at this time.

**Comment by zeffii** [comment]
in `menu.py` (link above) the `juggle_and_join` function does post processing of the `index.md`.

we could add 
```python
    # join beta and alpha node cats, into new Pre Release category
    node_cats['Pre Release Nodes'] = []
    node_cats['Pre Release Nodes'].extend(node_cats.pop('Alpha Nodes'))
    node_cats['Pre Release Nodes'].extend(node_cats.pop('Beta Nodes'))
```
to make a new category, or simply  keep the original `node_cats`, so the standard menus have Alpha and Beta.

**Comment by Ribel78** [comment]
If the problem is known, that's OK.

I was searching for a node in the Shift+A menu and I had hard time locating it (always invoking it using the Search option before). That is why I made a screen shot of all nodes in the Tool Shelf and that is how I noticed the inconsistency (see the image)
![image 025](https://user-images.githubusercontent.com/15086376/35274927-ac2b52c8-0046-11e8-99cc-98f62470d24f.png)

I also think Search option (Ctrl+Space bar) is the best way to operate with nodes as long as you know what you are looking for. Personally, I dislike vertical tabs because they are not visible enough, but are better for exploration than opening every time the dropdown menu.

On a side note - I tried to add individual nodes into Presets Tab, which is a great way to keep favorites, but there is a problem too. As opposed to the other node tabs which when clicked a button allows you to position a node with the mouse, in the Presets the nodes are placed always at some initial position and have to be moved second time. I know it is not related to the current issue, but it is still inconsistency in placing nodes (or group of nodes) via Presets against the other tabs.

**Comment by portnov** [comment]
Yeah, I thought about how to make presets behave like simple nodes, but I couldn't find suitable python API.

**Comment by zeffii** [comment]
Let me suggest that you start a new dedicated issue to UI inconsistencies,  where you do do
<pre>
- [ ] item 1
- [ ] item 2 ( [link name](hyperlink) )
- [ ] item 3
</pre>
that formats to

- [ ] item 1
- [ ] item 2 ( [link name](hyperlink) )
- [ ] item 3

then you can make separate issues for each, and we can handle them individually.

**Comment by zeffii** [comment]
but unless the issue is massively inconvenient for you/users/us there may be some "grace" period where nothing happens about it. (that doesn't mean it's not being thought about)

**Comment by zeffii** [comment]
btw @Ribel78   , Shift+A was missing a few items until yesterday, the `Vertex Color` nodes :).  

i'll add a trigger shortcut for ctrl+space `vcol` 
```python
class SvVertexColorNodeMK3(bpy.types.Node, SverchCustomTreeNode):
    '''
    Triggers: vcol vertex colors
    Tooltip: Set the vertex colors of the named Layer
    '''
    bl_idname = 'SvVertexColorNodeMK3'
    bl_label = 'Vertex color mk3'
    bl_icon = 'COLOR'
```

The areas you experience the most weird circumstances are the parts that we developers use the least.

**Comment by zeffii** [comment]
that gives:
![image](https://user-images.githubusercontent.com/619340/35276968-7e27bf0c-0045-11e8-99fe-21dad05a9959.png)

**Comment by Ribel78** [comment]
@zeffii Vertex Color node was the node I was searching for and that made me bend and twist the Blender UI for this enormous screenshot :)
I can't see Objects sub menu in the drop down menu, but it exists in the Toolshelf with Vertex Colors nodes in it.

**Comment by zeffii** [comment]
yep. forget about the `Vertical menus (T-Shelf)` and the `NodeView->Header->Add` menu. 

Shift+A and Ctrl+Space all the way.

**Comment by zeffii** [comment]
- There are too many nodes/categories to make the Vertical menu a sane UI solution.
- the default Add menu can't be conveniently replaced.

**Comment by zeffii** [comment]
I tried taking this seriously a while back https://github.com/nortikin/sverchok/issues/1502  , but didn't find the solutions very nice.  I could think of many other things that I would much rather stick time into.
