### ISSUE TITLE
Red copy of formula node keeps its colour.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2081]
## Problem statement

Red copy of formula node keeps its colour.  It can confuse sometimes.

## Steps to reproduce

[red copy formula node](https://user-images.githubusercontent.com/28003269/35267660-731c3534-0040-11e8-9e32-b0de8292e006.gif)  (click for animated GIF)

## Expected result

Normal color of the node

## Actual result

Red color of the node. ))

**Comment by zeffii** [comment]
LOL :) propose a change,  hint... [search for `def copy(self, node)`](https://github.com/nortikin/sverchok/blob/9b8953816828e6246edb9ebfcf6ba825b689fcaf/nodes/text/shape.py#L51)

**Comment by zeffii** [comment]
I suspect this is not the only node with this effect.

**Comment by Durman** [comment]
I hardly can imagine what one have to fix for improving this situation.))

**Comment by zeffii** [comment]
the function that checks this is 

https://github.com/nortikin/sverchok/blob/14320d6220deb48990a439033d4b2771ef67f888/core/update_system.py#L296-L304

**Comment by zeffii** [comment]
interesting problem, we'll maybe have to add a member to the Node baseclass..  this is not trivial @Durman . Thanks for reminding me..

**Comment by zeffii** [comment]
on the positive side it's more cosmetic than anything..Not very clear for the user, but easy enough to fix.

**Comment by zeffii** [comment]
@portnov , any suggestions. Some nodes have additional processing upon the `copy` invoke. and i'm not sure if one solution will work for all variations. maybe ..
```python

# utility function
def invoke_if_present(self, node, function_name):
    if hasattr(self, function_name):
        getattr(self, function_name)(node)

.. Node Class ..

    # place in node if special actions are needed
    def post_copy(self, node):
        # add code you to to execute after the standard copy code is executed

    # place in node if special actions are needed
    def pre_copy(self, node):
        # add code you to to execute before the standard copy code is executed

.. Node Base Class (mixin) ..

    # -- in Sv Node class mixin:   handle generic scenarios..
    def copy(self, node):
        # don't add this method to individual node classes

        invoke_if_present(self, node, "pre_copy")
        # ... standard copy code, check error color state...
        invoke_if_present(self, node, "post_copy")

```

**Comment by zeffii** [comment]
each node should do this..
```python

    def copy(self, node):
        self.set_color()
```
and  in node_tree.py
```diff
    def set_color(self):
        color = color_def.get_color(self.bl_idname)
        if color:
            self.use_custom_color = True
            self.color = color
+       else:
+           self.use_custom_color = False
```

**Comment by portnov** [comment]
Why not define this copy() in base node class then?

**Comment by zeffii** [comment]
it is a `bpy.types.Node` default method,

**Comment by zeffii** [comment]
something like this would be OK i think.. https://github.com/nortikin/sverchok/issues/2081#issuecomment-359764517

**Comment by zeffii** [comment]
upon copy of a node, the following "expected" functions are not called `init` and `sv_init` .

**Comment by portnov** [comment]
@zeffii here comes "method resolution order" of multiple inheritance. If we have

```python
#!/usr/bin/python3

# Imagine this is bpy.types.Node definition
class Node(object):
    def copy(self, node):
        print("Generic copy method works")

class SverchCustomTreeNode(object):
    def copy(self, node):
        print("Sverchok default method works")

class SvBoxNode(Node, SverchCustomTreeNode):
    pass

node = SvBoxNode()
node.copy(None)
```
This prints "Generic copy method works".

BUT if we have

```python
...

class SvBoxNode(SverchCustomTreeNode, Node):
    pass

node = SvBoxNode()
node.copy(None)
```

it will print "Sverchok default method works". General idea is that Python searches the method definition in parent classes in the same order as they are enlisted in class definition.

See also https://makina-corpus.com/blog/metier/2014/python-tutorial-understanding-python-mro-class-search-path (all our classes are "new-style" classes since blender uses python3).

**Comment by zeffii** [comment]
we might certainly have cross communications.  but of course I might totally not understand.

- my proposal is to search all nodes that currently implement their own `copy()` function. and rename them to `post_copy`.
- then add `copy` explicitly to SverchCustomTreeNode,  and have it call
    ```python
    def copy(self, node):
        invoke_if_present(self, node, "pre_copy")
        # ... standard copy code, check error color state...
        invoke_if_present(self, node, "post_copy")
    ```

the only thing i'm uncertain about here is what happens if we overload `copy`, what kind of other magic might it be doing.  -- but I don't think it does much other than copy all of the code (deepcopy).

**Comment by zeffii** [comment]
turns out this is a little trickier @Durman  thanks for you patience.

**Comment by Durman** [comment]
I thought it will be easy to fix, maybe it is not worth to spend time on it?

**Comment by zeffii** [comment]
The fix won't be just for the Formula node, this will apply to any node. So it's worth fixing, even if this is a cosmetic quirk that has no impact on the functioning of the node.  But.. it's not critical :)

**Comment by zeffii** [comment]
it does mean slightly modifying 20 nodes that implement their own `def copy(self, node)`.

**Comment by zeffii** [comment]
there are a number of ways, i just have not been able to decide yet. and don't really want to modify sverchok for this, without thinking a bit longer :)

**Comment by zeffii** [comment]
i think what I might do is offer a `copy/duplicate` operator replacement, that creates another node of the same bl_idname without using the copy mechanism.   but for now i'm unwilling to tackle the bug in this specific scenario.   : /
