### ISSUE TITLE
Unable to run templates or add nodes

### ISSUE THREAD

**Issue by fadelm0** [nortikin/sverchok#2082]
## Problem statement

None of the templates work, and the nodes are all grayed out. Error received when trying to load a template. ![attached image](https://user-images.githubusercontent.com/14968300/35301509-664f82c6-0094-11e8-89d6-c57757892e65.jpg) 

## Steps to reproduce

1. Install Blender 2.79
2. Download sverchok from [here](https://github.com/nortikin/sverchok/archive/master.zip) and install as usual from blender preferences.
3. Open node editor and try to use sverchok
Note: This was tested on a fresh install of Blender 2.79 on both Windows 7 x64 and Windows 10.
The contents of the sverchok installation archive were inspected for any folders that have periods in the name, and none were found.

## Expected result

I expected to have a working addon for parametric exploration in blender.

## Actual result

2.20 MB of disappointment, and tears in my eyes.

## Sverchok version

0.5.9.6. Installation outlined in "steps to reproduce" above.

**Comment by zeffii** [comment]
ok. before loading a template, just press New nodetree.. it will then let you load a template.

![image](https://user-images.githubusercontent.com/619340/35303613-df21bdce-0092-11e8-87fc-1b60c2efbf15.png)


i'll fix this so in future you won't have to first press `+ New`

**Comment by fadelm0** [comment]
Ohhh! Completely missed that button! Thanks.

**Comment by zeffii** [comment]
i'm going to bed now,, but will do this tomorrow. in the mean time just make sure there's nodetree before adding a template.

**Comment by zeffii** [comment]
note to self
```python
    def execute(self, context):

        # if triggered from a non-initialized tree, we first make a tree
        if self.id_tree == '____make_new____' or not self.id_tree in bpy.data.node_groups:
            ng_params = {
                'name': basename(self.filepath),
                'type': 'SverchCustomTreeType'}
            ng = bpy.data.node_groups.new(**ng_params)
        else:
            ng = bpy.data.node_groups[self.id_tree]
```

**Comment by zeffii** [comment]
or fix here
https://github.com/nortikin/sverchok/blob/d5c1f4c8093a8fdf54a3760ffad3b5e4cd4be7b7/ui/sv_templates_menu.py#L58-L64

**Comment by zeffii** [comment]
fixed with https://github.com/nortikin/sverchok/pull/2083
