### ISSUE TITLE
range integer when linked makes stop not count. Why?

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#2086]
## Problem statement

range int not use count when linked socket to count, instead it uses `count` value for `stop` operation
import gist: https://gist.github.com/8dad1ae6d7ee6e6b9a0debb2b6829ca8
this is guilty code:
```python
    def mode_change(self, context):

        # just because click doesn't mean we need to change mode
        mode = self.mode
        if mode == self.current_mode:
            return

        self.inputs[-1].prop_name = {'LAZYRANGE': 'stop_'}.get(mode, 'count_')

        self.current_mode = mode
        updateNode(self, context)
```
not understand where is happening that linkage change things?

## Steps to reproduce

1. define how to stay count in update function
2. rewrite update function

## Expected result

use count, not stop when linked

## Actual result

stop instead of count if linked

## Sverchok version 

current

**Comment by zeffii** [comment]
@nortikin   it's only the label.text that has a bug.. the behaviour is correct, but the UI is not.

![image](https://user-images.githubusercontent.com/619340/35353869-d1a0f046-0148-11e8-84c6-1898af8d6ff4.png)

**Comment by zeffii** [comment]
Float Range also suffer this.. it must have gone unnoticed during the Socket Upgrades a few weeks ago.
![image](https://user-images.githubusercontent.com/619340/35354033-3c2c74a8-0149-11e8-8512-c0acd827c84d.png)

definitely needs to be resolved.

**Comment by zeffii** [comment]
might require an mk2 to avoid breaking old .blends... but ... maybe not :)

**Comment by zeffii** [comment]
When linked the socket label should show the [node.prop_name].name and not the Socket Name.

**Comment by zeffii** [comment]
we might find a lot of socket that do this, so best try to wait and gather them.. before editing one ..two..nodes and then realizing that its a lot more nodes...

https://github.com/nortikin/sverchok/blob/b546794c1e34daa91e7e9071471ca1d688169db4/node_tree.py#L201-L204

the `text` value there is taken from the socket name. Which is set originally in sv_init upon socket creation..

**Comment by zeffii** [comment]
so ... i think that should be 
```
 if self.is_linked:  # linked INPUT or OUTPUT 
     info_text = self.get_text() + '. ' + SvGetSocketInfo(self) 
     info_text += self.extra_info 
     layout.label(info_text) 
```

**Comment by zeffii** [comment]
where 
```
def get_linked_socket_text(self, text):
    if socket.prop_name:
         property = socket.bl_rna.properties[socket.prop_name]
         if name in property:
              return name
    return text

```

**Comment by zeffii** [comment]
but not all prop_name might have a `name` parameter... (we should discourage this...)

but in the meantime we might have to test the presence of a name parameter in the property
```python
>>> hasattr(node.bl_rna.properties[socket.prop_name], 'name')
True

>>> hasattr(node.bl_rna.properties[socket.prop_name], 'name2')
False
```

**Comment by zeffii** [comment]
this is a nasty bug @nortikin   nice find.

**Comment by zeffii** [comment]
or something like the older version..

https://github.com/nortikin/sverchok/blob/daa82d31e30a0db39e22925f5bd0164589853586/node_tree.py#L152-L175

**Comment by zeffii** [comment]
will propose a fix tomorrow when fresher :)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/35360409-e64f4974-015d-11e8-8dbd-b65e92d2dd38.png)

https://github.com/nortikin/sverchok/pull/2087/files

**Comment by zeffii** [comment]
committed the fix for this.
