### ISSUE TITLE
Insolation calculation

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2091]
Here one can find all nodes that I did on this topic for `SNL` node: https://gist.github.com/22388494d23d6e00d06f173831fcb141

I want to create insolation calculation. 
I think it is easy goal with raycaster node that will do main work. As result we have to receive insolation time in calculation points. 
Main task is to create script that will give directions of the sun. They will be depend on the time and the place. I have found good code that solves the same problem: https://github.com/mourner/suncalc
I think it can be easily rewritten on Python. Also I already have something to show on the picture below.))

![insolation calculation](https://user-images.githubusercontent.com/28003269/35454956-9aac1456-02e9-11e8-821c-a3e51cd250d2.gif)

**Comment by zeffii** [comment]
do you mean https://en.wikipedia.org/wiki/Building_insulation  ?

**Comment by Durman** [comment]
It's not certainly what I want to do but something like that. https://www.youtube.com/watch?v=OpnjfWLWJdE

**Comment by zeffii** [comment]
it definitely worth a dedicated node at some point, when we get more scene conscious :)

**Comment by zeffii** [comment]
cool video. yeah.. look extremely doable :)

**Comment by Durman** [comment]
My algorithm will determine how long sun is shining during a day in calculation point. Buildings can cast shadows on the point and in this case insolation time will be less. It depends on height and width of opposite building. 
It is important to have such calculation when one going to build housing in Russia. In the video is another calculation it is not good example. I suppose that there is not such calculation in another countries.

**Comment by zeffii** [comment]
it's great that this interests you. I will help any way I can (if i have time too )

**Comment by Durman** [comment]
Well, I have node that can show azimuth and altitude of the sun for current coordinates, date and time. It seems working.))

![the sun](https://user-images.githubusercontent.com/28003269/35498703-ccee5c2a-04e8-11e8-87d8-057e3083eaa5.gif)
![2018-01-29_11-38-33](https://user-images.githubusercontent.com/28003269/35498747-f3c8e176-04e8-11e8-9d53-5c1b98c132f4.png)
![2018-01-29_11-37-25](https://user-images.githubusercontent.com/28003269/35498750-f70e91c8-04e8-11e8-8f46-3ea0d5cfaf1d.png)

**Comment by Durman** [comment]
Moving of the sun during a year in my region. I think the node can become more interesting after appearing viewer node of lamp.

![2018-01-29_15-24-13](https://user-images.githubusercontent.com/28003269/35508229-ff70b236-0508-11e8-95a5-bcd4091cd5b1.png)

**Comment by enzyme69** [comment]
@Durman Is this awesome node available?

**Comment by Durman** [comment]
The node is not finished yet. I would not like to share while it is in bad condition. 
Also I noticed that Sverchok have not any nodes for working with time. I am thinking about adding  time in/out and date in/out nodes.

**Comment by Durman** [comment]
Some examples with time nodes:
I took 24 hours as 1.0. Thus it becomes possible to make all mathematical operation with the time as with simple number.

![2018-01-30_11-43-22](https://user-images.githubusercontent.com/28003269/35553803-ca94a216-05b2-11e8-9b0a-d194f424ab0a.png)
![2018-01-30_11-41-54](https://user-images.githubusercontent.com/28003269/35553810-d1aea6f0-05b2-11e8-8dee-94d05ec1444a.png)

**Comment by Durman** [comment]
Output of `date in` node is integer number that show number of days between current date and initial date equal 1st year 1st month 1st day.

![2018-01-31_13-57-35](https://user-images.githubusercontent.com/28003269/35616758-a7080bd4-068f-11e8-99f4-803978e64640.png)
![2018-01-31_13-58-31](https://user-images.githubusercontent.com/28003269/35616774-b2eca5cc-068f-11e8-8546-2a76d57b3388.png)

**Comment by zeffii** [comment]
i was parsing a csv lately and might want to add a node specially for `datetime` and `time` modules too.
```python
import datetime

VC = []

for value in V1[0]:
    t = datetime.datetime.strptime(value, '%m/%d/%Y')
    m = t.toordinal() - 736600
    VC.append(m)

append(VC)
```

**Comment by Durman** [comment]
Something similar but I have done checking of input data for avoiding error of node. What is it 736600?

```Python
    for year,month,day in zip(*data):
        #Checking data
        def fit_data(data,min_d,max_d):
            if data < min_d:
                return min_d
            if data > max_d:
                return max_d
            else:
                return data
            
        year = fit_data(year,1,9999)
        month = fit_data(month,1,12)
        last_day_month = None
        if month in (1,3,5,7,8,10,12):
            last_day_month = 31
        elif month in (4,6,9,11):
            last_day_month = 30
        elif year % 4 == 0:
            last_day_month = 29
        else:
            last_day_month = 28
        day = fit_data(day,1,last_day_month)
        
        date = datetime.date(year,month,day)
        data_obj.append(date.toordinal())
```

**Comment by zeffii** [comment]
736600 was just a placeholder number, it marks the beginning of the data (ie the first entry), the result is a list of much smaller numbers that show the offset since the beginning.

**Comment by Durman** [comment]
I have six nodes now. Is it interesting to have something of this in master?

![2018-02-02_08-20-33](https://user-images.githubusercontent.com/28003269/35716380-06c065e0-07f2-11e8-8478-3598bb277d97.png)

**Comment by enzyme69** [comment]
I am actually very okey with Script Node Lite :D Durman Folder.

**Comment by zeffii** [comment]
@Durman    https://docs.python.org/3/library/calendar.html#calendar.monthrange

I think it can be written like this:
```python

        import calendar
        ...
        ...
        year = fit_data(year,1,9999)
        month = fit_data(month,1,12)        
        wkday_first, last_day_month = calendar.monthrange(year, month)
```

**Comment by Durman** [comment]
I have finished. Result is shared in first message.

**Comment by nortikin** [comment]
result is sun position? Or insolation at all?

**Comment by Durman** [comment]
I have spent most of my time creating sun position node. Also I created insolation calculation of course, it hadn't been difficult, I used almost only existing nodes. If it is interesting I can share with example of calculation.

**Comment by nortikin** [comment]
ok, please.
if it is property send email

**Comment by Durman** [comment]
There is nothing tricky in the calculation for who knows SV.))
I will put here file tomorrow from my job.

**Comment by nortikin** [comment]
main trouble is vectorising.

**Comment by nortikin** [comment]
there is task i solving now with conflict finding concept.
In Revit you can see wall-celling intersection with engineering.
So i do it
![revit_intersection](https://user-images.githubusercontent.com/5783432/35879724-f523ea84-0b8c-11e8-9b48-5e7aff812b1a.png)

**Comment by nortikin** [comment]
![revit_intersection1](https://user-images.githubusercontent.com/5783432/35881994-b6ce5f24-0b93-11e8-9c9e-c5826fcc6fcc.png)

**Comment by nortikin** [comment]
И Задача ещё импортировать IFC формат

**Comment by Durman** [comment]
If there are questions I will answer.)
[К-16_2018_02_07_04_15.gz](https://github.com/nortikin/sverchok/files/1701716/-16_2018_02_07_04_15.gz)
![2018-02-07_08-14-43](https://user-images.githubusercontent.com/28003269/35898351-99c3da52-0bdf-11e8-863e-87dd5df7d4b2.png)

**Comment by nortikin** [comment]
not sure i understand.
now have same work on my job. maybe will snl on my own

**Comment by nortikin** [comment]
there is addon https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/3D_interaction/Sun_Position
that we can use for sun position indeed

**Comment by nortikin** [comment]
writing my new node for this stuff. it will do same as raycast mk2 object but with sun calculations
hesitate to use hours or % in output

**Comment by nortikin** [comment]
![insolation1](https://user-images.githubusercontent.com/5783432/36618599-c5ae875a-18fc-11e8-8d48-1265f3dcae1a.png)
![insolation2](https://user-images.githubusercontent.com/5783432/36618624-e8f8ec64-18fc-11e8-9a85-55ced8ce7857.png)

**Comment by nortikin** [comment]
the last thing to do - latitude and aptitude automatic estimation  of sun directions
It will calc for date from date time text node.
So you will have three input nodes, one indices viewer and latitude and aptitude inputs

**Comment by Durman** [comment]
Your representation of insolation is very visual.)
