### ISSUE TITLE
NameError: name 'nodes' is not defined

### ISSUE THREAD

**Issue by yurivict** [nortikin/sverchok#2092]
I created the port for FreeBSD. It works fine for me with blender-2.79, but I've got the bug report from the user.

Version 0.5.9.6.2
```
Traceback (most recent call last):
File "/usr/local/share/blender/2.79/scripts/modules/addon_utils.py",line 331, in enable modd=_import_(module_name)
File "/usr/local/share/blender/2.79/scripts/addon/sverchok/_init_.py",line 142, in <module> node_list=make_node_list()
File "/usr/local/share/blender/2.79/scripts/addon/sverchok/_init_.py",line 134, in make_node_list for category, names in nodes.nodes_dict.items():
NameError: name 'nodes' is not defined
```

The file ```/usr/local/share/blender/2.79/scripts/addons/sverchok/nodes/__init__.py``` exists, so ```nodes``` should be defined. But it isn't defined for some reason.

**Comment by zeffii** [comment]
Generally this means user needs to restart blender. Then check in prefs to see if the add-on is enabled. If not then tick the box just one time, and wait until the tick appears. This can take up to 10 seconds. Sadly blender offers no feedback in the interim.

**Comment by zeffii** [comment]
When Sverchok gets the chance to initialize properly the symbol `nodes` is dynamically imported into the 'globals()` before `nodes` is referenced.  A careful reader won't see the symbol `nodes` defined prior to it use, that's correct. `init_architecture` does some importlib magic. 

I have considered adding some code comments to reflect that, and might still do that. The recommended resolution advice, still applies.

**Comment by zeffii** [comment]
you should also update sverchok.  in master `init` no longer has more than 104 lines.

**Comment by zeffii** [comment]
also... make sure you provide Sverchok from `https://github.com/nortikin/sverchok/archive/master.zip`  and not the "Releases".  Master will generally be the most up to date _working_ version. Releases will just confuse people.

**Comment by zeffii** [comment]
there's no other earthly reason why this error would be displayed.  Closing unless reality has broken.

**Comment by yurivict** [comment]
The user says that he restarted, and still gets the same problem:

> I did it and I did before too but it is the same problem.
> Thank you very much for the help.

**Comment by zeffii** [comment]
use a different zip ( https://github.com/nortikin/sverchok/archive/master.zip )

make sure the user's Blender has 'requests' and 'numpy' .

**Comment by yurivict** [comment]
The port installs 'requests' and 'numpy'.

**Comment by zeffii** [comment]
but not master archive.zip

**Comment by zeffii** [comment]
but @yurivict  you have bsd and all of this works for you? then maybe user should come here.. or show more of the error message.  Not enough information to be terribly helpful : /

**Comment by yurivict** [comment]
It doesn't use .zip. It takes code from GitHub by revision.
https://github.com/nortikin/sverchok/archive/master.zip will change with the new version. It can't be used for ports, because it changes.

**Comment by yurivict** [comment]
> but yurivict you have bsd and all of this works for you? 

Yes, it worked when I made the port, of course.

> Not enough information to be terribly helpful : /

Ok, I'll invite him.

**Comment by zeffii** [comment]
then user should redownload, because Master repo has a different `__init__` now

**Comment by yurivict** [comment]
The port has a fixed version, until the port is updated.
Users generally don't change version, unless they know how to and change it manually.

**Comment by zeffii** [comment]
update the port then

**Comment by yurivict** [comment]
Now I also have this problem. The code is the same that worked before. Version 0.5.9.6.2

Attempt to enable Sverchok causes the error.

**Comment by yurivict** [comment]
For some reason, now when I updated to 4ec06b6318fdf21015af70cf6e54ae0a6c797d6f it works.
But it did work before for 0.5.9.6.2. I am afraid that there is something that makes it unstable like this.

**Comment by zeffii** [comment]
OK. then use that for the port.   Master is fluid (but mostly stable), the "releases" are something you want to stay away from.

**Comment by zeffii** [comment]
it is very possible that the code that tries to create a folder called /datafiles/sverchok on your disk first meets resistance, but doesn't report the error.. i don't know.

**Comment by zeffii** [comment]
all i can really know is that using the lastest Master, the code that is executed in "init_architecture" must have failed for some reason. A side effect of that is that "nodes" then isn't available in `__init__`

**Comment by yurivict** [comment]
Ok, I will update the port, will close this issue, and then see if this problem comes up again some time in the future.

**Comment by zeffii** [comment]
cool. we have automated testing implemented using CLI travis, if you can suggest any tests you're welcome to submit some.
