### ISSUE TITLE
Can I sort vertices by connected edges?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#2100]
Blender can expand selected vertex by pressing Ctrl+numpad +.
I want to sort vertices like that, can I?

**Comment by Kosvor2** [comment]
![index_shift345cvb](https://user-images.githubusercontent.com/22656834/35561481-42b02832-05d2-11e8-8b5f-09498a634e6a.png)

Used "list shift" as there is offset by one item either in "Vector sort" or "View index" node...

**Comment by stansu** [comment]
why your vector sort have connect mode?

**Comment by Kosvor2** [comment]
Does it really matter?

**Comment by stansu** [comment]
i just update sverchok, the new "vector sort" solve my problem.
thank you!

**Comment by zeffii** [comment]
@stansu   Connected mode was added recently by @vicdoval  ( in this commit ) https://github.com/nortikin/sverchok/pull/2001  have fun!

**Comment by zeffii** [comment]
seems resolved. closing unless more questions :)

**Comment by zeffii** [comment]
@stansu you mention you want to sort disjoint sections too like 
```
0----1----2---3--4---5          6---7--8---9       10---11---12
```
that's not impossible but the current Connect mode might need an alternative, "Disjointed Sections", which would use proximity to figure out the final ordering . Because there are many approaches and many desired specific outcomes in might need a better way to describe the input mesh and prepare the algorithms to do what's intended.

**Comment by stansu** [comment]
![image](https://user-images.githubusercontent.com/9460236/35614357-c10859ac-06a9-11e8-91a4-9ee2b3d9c540.png)
@zeffii, i'm not mean multi-section, i'm mean open shape.
https://gist.github.com/2afb7c38a6b00798fc051f449fc9f5fc

**Comment by zeffii** [comment]
oh! cool.

**Comment by Durman** [comment]
@stansu You can use this way until vector sort node will be fixed.

![2018-01-31_13-55-04](https://user-images.githubusercontent.com/28003269/35616337-6c0bcfda-068e-11e8-9484-dae22e30f883.png)
https://gist.github.com/425da0d96d6f705d111ce21b008625e5

**Comment by stansu** [comment]
wow, genius!
thank you @Durman.

**Comment by vicdoval** [comment]
Searching for the beginning of the path would be the solution. I will add it soon.
Also sorting by distance for "disjoints" would be interesting but also would  make it slower..
By now it's just a question o which is the first given edge
![sortbyconnex](https://user-images.githubusercontent.com/10011941/35617008-3df4bf92-0677-11e8-9b6e-bdff9ed135aa.png)

https://gist.github.com/812959cd6912f6c782367f404dfc4d75

**Comment by zeffii** [comment]
i'd rather have multiple modes in a node, than one mode that does everything but is slower because it expects a variety of inputs. If it's not possible to generalize, make it easy to specialize.

**Comment by stansu** [comment]
@vicdoval , why it will work when you add list shift?

**Comment by vicdoval** [comment]
The implementation works like this:
  Take the first given edge.  [0, 8]
  Find another edge with the 8 --> [4, 8]
  Next find another with de 4 --> [4, 6]
  By now de vertex order would be [0, 8, 4, 6]
When it arrives to a  "end point" it starts the process on the next unused edge.
There is not any pre-processing for finding the end points or the nearest's points.
So if you tell the node which should be the starting edge it is more probable to get the desired result.  :)

**Comment by nortikin** [comment]
oh, i missed this question
sorry
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/topo_sort_for_profile.py
here it is

**Comment by nortikin** [comment]
will make mk2 for this
