### ISSUE TITLE
Cylinder + 2 Half Sphere = SV Capsule

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2106]
<img width="807" alt="screen shot 2018-02-02 at 11 30 04 pm" src="https://user-images.githubusercontent.com/3952687/35733354-38a69654-0871-11e8-917c-a09e7c8c5775.png">

[capsule_002_2018_02_02_12_29.zip](https://github.com/nortikin/sverchok/files/1689337/capsule_002_2018_02_02_12_29.zip)

Sverchok does not seem to have capsule node, so I make one. There is rounded box that can actually make capsule shape, but I make this one anyway.

**Comment by enzyme69** [comment]
<img width="248" alt="screen shot 2018-02-02 at 11 32 24 pm" src="https://user-images.githubusercontent.com/3952687/35733378-556b028e-0871-11e8-9b5a-46e7afa6f2ad.png">

Useful to make:
- R2D2
- Bender
- Android Bot

**Comment by Durman** [comment]
I would advise to make monad for this generator and to publish it in G+.)) We already have there stair and diamond generator from me and pillows generators from Portnov and Gorodetsky. This generator could expand this collection.
https://plus.google.com/u/0/photos/photo/112199007352865185412/6512791508779329794?sqid=113245231013159497850&ssid=f46940c3-ccfd-4aa8-bd99-293760850995

**Comment by enzyme69** [comment]
[capsule_monad_002_2018_02_03_04_02.zip](https://github.com/nortikin/sverchok/files/1691374/capsule_monad_002_2018_02_03_04_02.zip)

Above is Monad for Capsule. Ideally top and bottom can be switched on and off easily (I kind of wish Cylinder also has it).

**Comment by enzyme69** [comment]
Radius and Remove Double. It's a hack capsule, but maybe useful. Ideally also the capsule can be easily divided into 2.

[capsule_monad_003_2018_02_03_04_12.zip](https://github.com/nortikin/sverchok/files/1691380/capsule_monad_003_2018_02_03_04_12.zip)

**Comment by nortikin** [comment]
https://gist.github.com/c688826efe9e83d258e669180c5fab01
![caps](https://user-images.githubusercontent.com/5783432/35766229-d92dd74a-08e4-11e8-91c3-069421210e9a.png)

**Comment by enzyme69** [comment]
In a way rounded box is a nice capsule.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
