### ISSUE TITLE
Triangulate mesh - Beautify mode doesn't work

### ISSUE THREAD

**Issue by Ribel78** [nortikin/sverchok#2110]
## Problem statement

**Triangulate mesh** node doesn't modify mesh that needs edge rearrangement.

## Steps to reproduce

1.  Download the blend file here:
[SV_Delaunay - Error - Triangulate mesh - 01_2018_02_04_21_04.zip](https://github.com/nortikin/sverchok/files/1693309/SV_Delaunay.-.Error.-.Triangulate.mesh.-.01_2018_02_04_21_04.zip)

2. Try using **Triangulate mesh**  node to make Dealunay triangulation look beautiful. Nothing changes.

## Expected result

I expected **Polygons - Beautify** option of the node to work as Blender's **Beautify Faces** operator
Below I compare the baked result after **Triangulate mesh** (in the middle) and the mesh after performing **Beautify Faces** in Mesh Edit mode (on the right).

![image 008](https://user-images.githubusercontent.com/15086376/35782497-94fc2ef0-0a01-11e8-8841-00551fd3fad4.png)

## Actual result

Nothing changes using **Triangulate mesh** node this way.
Does it require Edges input? I tried **Polygons to Edges** nodes for Edge input without success.

## Sverchok version

SV 0.9.5.6 (a2e7f6a)

Freshly updated using the update controls in the Node Editor, but this problem was present in the previously installed version.

**Comment by zeffii** [comment]
> Does it require Edges input?

I doubt it, the algorithm is calling bmesh.ops directly, most (if not all) bmesh operators that take polygons should be able to infer edges. I'm not sure why the node has an edges socket.

**Comment by zeffii** [comment]
I'd be inclined to add a `beautify faces` node, it might be that the triangulate node is expecting quads or ngons, and that the beauty function was broken along the way and has gone unnoticed until now.

**Comment by Ribel78** [comment]
I've used previously **Triangulate mesh** node and it worked. Probably broken.
I tested with simpler node tree.
Just add Text object and convert it to mesh. In Sverchok plug the object in **Triangulate mesh** node:
![image 010](https://user-images.githubusercontent.com/15086376/35803098-3d6e8e92-0a7b-11e8-9315-da0781d2f3e2.png)
Below the Viz is the result from Blender' Beautify Faces

**Comment by zeffii** [comment]
from a dev point of view, the bmesh docs are rather sparse with that operation.

![image](https://user-images.githubusercontent.com/619340/35805653-ff6d1c74-0a7c-11e8-8305-32a8da1216cb.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/a2e7f6ad03d7f00fe2170e6ad5392b77b9b83bcd/nodes/modifier_change/triangulate.py#L34-L45

I think the node expects Quad input, and the algorithm ( i might be incorrect here ) might not fair well with input that is already triangulated. Now, that doesn't help the comparrison of what happens in Blender edit mode with a triangle mesh and the beautify operator. I think we would need to implement this as a dedicated node..

[bmesh.ops.beautify_fill](https://docs.blender.org/api/blender_python_api_current/bmesh.ops.html)

(which we don't appear to implement anywhere in the code base... )

**Comment by zeffii** [comment]
```python
"""
in in_verts v
in in_faces s
out out_verts v
out out_faces s
"""

import bmesh

if in_verts and in_faces:
    fill = bmesh.ops.beautify_fill
    for verts, faces in zip(in_verts, in_faces):
        bm = bmesh_from_pydata(verts, [], faces)
        bm.verts.ensure_lookup_table()
        fill(bm, faces=bm.faces[:], edges=bm.edges[:], use_restrict_tag=False, method=0)
        nv, ne, nf = pydata_from_bmesh(bm)
        out_verts.append(nv)
        out_faces.append(nf)

# EOF
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/35814878-7769d3ec-0a97-11e8-891c-abd74a89ec2c.png)

**Comment by Ribel78** [comment]
@zeffii That' awesome!
I wish I had a bite of your programming skills :)
Is there a node that is similar to Tris to Quads operator.
What does **Join Triangles** node do? If it is similar to Tris to Quads operator this can be used together with the **Triangualte mesh** node for "beautification' of triangle meshes.
In any case the scripted node above is far better solution.

**Comment by zeffii** [comment]
should this snlite script be a node?

**Comment by zeffii** [comment]
check out the new `Mesh Beautify` node in `Modifers change`
