### ISSUE TITLE
Enhance Viewer Draw node by adding a “visibility layer" setting

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2111]
Here’s an idea.. I often time want to show/hide multiple viewer draw nodes outputs at the same time and was wondering if adding a **visibility layer** option to the node would be beneficial for that purpose. You could have certain VD nodes set to display only on certain layers, but not others and use blender’s visibility layer feature to simultaneously turn on/off certain VD outputs.

I think this would a be similar to objects behavior (e.g objects have layer visibility).

![sv-viewerdraw-visibilitylayers](https://user-images.githubusercontent.com/2083719/35786866-34375ddc-09f8-11e8-82f6-10c497d341d2.jpg)

**Comment by zeffii** [comment]
I was thinking of using a Collection property per `node_group`. So the VD node only stores the name of the layer it is a child of. The node tree would have a mechanism to add remove layers by name, Not sure how this would work with io/json but something would be possible. Also the problem arrises of how to deal with nodes that are imported into an exist node tree.    these are not nice problems. :)    (whch i suppose would be simlified if there was no named layer system... but i have the anonymous layering.. )

worth some experimenting.. but don't be too jaded if it takes a while to materialize.

**Comment by DolphinDream** [comment]
Importing could be handled via default props (similar to the ones we did for the socket expander). If the node setups (gists) don’t have the “layer visibility” prop set upon import the prop is set to the default “all layers”. Exporting can be sparse to only save this prop if it deviates from default value.

**Comment by DolphinDream** [comment]
Sandboxing the layers in VDMK2. here’s what it looks like. For now I added the layer selection to the property panel only.

![sv-vdmk2-layers](https://user-images.githubusercontent.com/2083719/36063060-07ddce54-0e46-11e8-99b7-dd50d273d5e6.png)

**Comment by DolphinDream** [comment]
And a little demo showing how it would play with blender’s visibility layers.
I used 1-10 layers to display individual components, and 11-20 to combine various components into one layer. 

![sv-viewerdraw-layers-demo2](https://user-images.githubusercontent.com/2083719/36063109-94cc1460-0e46-11e8-89b0-3eaaa8710cd5.gif)

**Comment by zeffii** [comment]
no. please no PR for this yet.

**Comment by zeffii** [comment]
the implementation should be independent from the Blender layer system.

**Comment by zeffii** [comment]
because VDMK2 is such a major node, all changes should be considered even more slowly than normal node changes :)

technically, you could even just have a controller node, which could enumerate all VDMK2 in the current layout.. (or even other layouts in the .blend) and have a set of  input socket that match the picked nodes... even allow to rearrange.

**Comment by DolphinDream** [comment]
What do you mean independent of BLS ? the whole idea is to let a layer settings affect which SV drawing takes place in each layer.

**Comment by zeffii** [comment]
" the whole idea is to let a layer settings affect which SV drawing takes place in each layer. "

A layer setting... not the BLS.

**Comment by DolphinDream** [comment]
Alternatively the VD layer setting could work in conjunction with a global SV layer setting displayed in the PP, thus not relying on the BLS at all. The global SV “visibility layer” setting could be displayed along with the rest of the SV settings in the PP.

**Comment by zeffii** [comment]
at least.. i don't want the BLS to influence the VDMK2 visibility. Is your reason for wanting that so you can edit keyframes?

**Comment by DolphinDream** [comment]
Something like this:

![sv-visibilitylayers](https://user-images.githubusercontent.com/2083719/36063348-befdb57e-0e49-11e8-9aae-17c15664cdcb.jpg)

**Comment by portnov** [comment]
Btw, in 2.8 blender people will rework layers thingy. Maybe it worth thinking how this will play with new layers system.

**Comment by DolphinDream** [comment]
@portnov Yes. true. Though I expect that it will be a while until blender gets the new feature out.. plus it may even continue to change as it is a fairly new feature. Perhaps @zeffii  idea is best as it doesn’t rely on BLS at all.

**Comment by DolphinDream** [comment]
Here’s another idea.. each SV tree has its own “visibility layer” option. Perhaps an overkill but it gives more flexibiity of what you want to show/hide. The “layers” don’t actually need to be 20 (like in BLS) .. and we dont’ even need to call them layers. :) These “layer” settings are just a convenient way to link together various VD nodes so you can turn a collection of them on/off easily.

![sv-visibilitylayers2](https://user-images.githubusercontent.com/2083719/36063588-d3c2c726-0e4c-11e8-8c60-61b1585fb291.jpg)

**Comment by DolphinDream** [comment]
There’s got to be an easy way to have multiple VD nodes be toggled on/off. I personally find such feature highly desirable especially for working on animation/illustration projects. Using the bmesh viewer node to convert everything to mesh would let you use BLS to toggle on/off certain parts of the drawing / meshdisplay, however this slows down the animation significantly compared to VD draw, not to mention i also have to create materials for every bmesh, while in the VD node I can simply edit the colors.

**Comment by zeffii** [comment]
i see the need for this. but.. i was thinking primarily of a different approach ( the ui_layout drawing could be drawn in any panel / 3dview panel too... )

![image](https://user-images.githubusercontent.com/619340/36064495-05f9b580-0e8c-11e8-9031-cf111968b1ca.png)

there would be more than just name and eye icon. also "node picker" and maybe color props. Quite a bit of internal plumbing could need to be implemented.  far more than is written for the ui demo here
```
# This file is part of project Sverchok. It's copyrighted by the contributors
# recorded in the version control history of the file, available from
# its original location https://github.com/nortikin/sverchok/commit/master
#  
# SPDX-License-Identifier: GPL3
# License-Filename: LICENSE


import bpy
# import mathutils
# from mathutils import Vector
# from bpy.props import FloatProperty, BoolProperty
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode


class SvVDMK2LayerGroup(bpy.types.PropertyGroup):
    vd_node_name = bpy.props.StringProperty()
    vd_node_viewstate = bpy.props.BoolProperty()


class SvVDMK2LayerNode(bpy.types.Node, SverchCustomTreeNode):
    ''' VDMK layer teste '''
    bl_idname = 'SvVDMK2LayerNode'
    bl_label = 'VDMK Layers'
    bl_icon = 'CAMERA_STEREO'

    vd_layers = bpy.props.CollectionProperty(name="Viewer Draw Layers", type=SvVDMK2LayerGroup)

    def sv_init(self, context):
        self.width = 300

    def draw_buttons(self, context, layout):
        for viewer in self.vd_layers:
            row = layout.row(align=True)
            row.prop(viewer, "vd_node_name", text='')
            row.prop(viewer, "vd_node_viewstate", toggle=True, icon='VISIBLE_IPO_ON', text='')


    def process(self):
        ...


def register():
    try:
        bpy.utils.register_class(SvVDMK2LayerGroup)
        bpy.utils.register_class(SvVDMK2LayerNode)
    except Exception as err:
        print(err)
        
        bpy.utils.unregister_class(SvVDMK2LayerNode)
        bpy.utils.unregister_class(SvVDMK2LayerGroup)

        bpy.utils.register_class(SvVDMK2LayerGroup)
        bpy.utils.register_class(SvVDMK2LayerNode)
    
def unregister():
    bpy.utils.unregister_class(SvVDMK2LayerNode)
    bpy.utils.unregister_class(SvVDMK2LayerGroup)

if __name__ == '__main__':
    register()
    nodes = bpy.data.node_groups['NodeTree'].nodes
    newnode = nodes.new('SvVDMK2LayerNode')
    layer_1 = newnode.vd_layers.add()
    layer_1.vd_node_name = "Viewer Draw"
    layer_1.vd_node_viewstate = nodes[layer_1.vd_node_name].activate
    layer_2 = newnode.vd_layers.add()
    layer_2.vd_node_name = "Viewer Draw.001"
    layer_2.vd_node_viewstate = nodes[layer_2.vd_node_name].activate
    layer_3 = newnode.vd_layers.add()
    layer_3.vd_node_name = "Viewer Draw.002"
    layer_3.vd_node_viewstate = nodes[layer_3.vd_node_name].activate        
```

**Comment by DolphinDream** [comment]
If I get your suggestion correctly, it looks like such node/feature would pretty much leave the VD node alone. It would be simply a “remote control” for the show/hide of each VD node? I guess that would work too. If the VDL node/feature would let you create arbitrary “layer” groups and add various VD nodes to each group you could easily turn on/off various groups. I don’t see the need for a lot of pluming in this case though.

```
└── Layers
    ├── Planets Layer
    │   ├── The Planet Orbits Layer
    │   │   ├── Venus Orbit VD
    │   │   ├── Earth Orbit VD
    │   │   └── Mars Orbit VD
    │   └── The Planets Layer
    │       ├── Venus VD
    │       ├── Earth VD
    │       └── Mars VD
    └── Extras Layer
        ├── The Lines Layer
        │   ├── Earth-Venus VD
        │   ├── Earth-Mars VD
        │   └── Venus-Mars VD
        └── The Grids Layer
            ├── Ecliptic Grid VD
            ├── Earth Grid VD
            └── Moon Grid VD
```
Here’s a hierarchical “layer” grouping structure where a VD can be added to one group or multiple groups. Each node in the hierarchy (VD node or layer sub/group) can be toggled on/off. Toggling on/off a “layer” group will toggle every VD inside that hierarchy.

**Comment by zeffii** [comment]
the more complex such UI, the more plumbing is needed. such is the pain of UI.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/36072582-0ab71216-0f22-11e8-87c6-d44d87941e02.png)

stub    https://gist.github.com/zeffii/6c45a37301a96ee3033d195a9d78f4f7

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/36077533-5076e5e8-0f6c-11e8-9293-db5b8b0b37f1.png)

https://gist.github.com/zeffii/06e2b5f6ccda02b2854e004afe039f8f

haha... eeeww

**Comment by DolphinDream** [comment]
Ha :) Just implemented something similar :) 

![sv-layergroups](https://user-images.githubusercontent.com/2083719/36079199-9e43fd1a-0f4e-11e8-8c38-b25b55e955f3.png)

**Comment by DolphinDream** [comment]
Layer groups can have a visibility setting to turn on/off visibility for all VD nodes in the group. The trick is how to preserve the previous visibility settings of the individual nodes in the group when you toggle the “master” visibility of the entire group. This would toggle on/off all nodes in the group thus erasing their initial visibility setting (e.g if Group G1 has VD1 off and VD2 on, toggling G1 off will make VD1 and VD2 off, and switching to G1 on will turn on  both VD1 and VD2).  Pherhaps a 3-way switch for the master visibilit of a group would let all nodes in the group be set to OFF, ON or MIX values (whatever values they happened to be set to originally.

**Comment by DolphinDream** [comment]
![sv-viewerdraw-layers-demo3](https://user-images.githubusercontent.com/2083719/36079709-09fa5702-0f54-11e8-8442-9434476d23cc.gif)

**Comment by DolphinDream** [comment]
With this scheme, one question is how do you show only the nodes in one group and hide everything not in that group. One solution could be to have a “toggle all VD nodes to OFF” and then toggle the group you’re interested to show ON.

**Comment by zeffii** [comment]
SvVDMK2LayerGroup (in my implementation)  could have many extra Properties, but I think that further complicates the UI, if you wanted to add something like a "restore" state. (but i totally understand why you want the feature... just giving a sane solution is something that can take time)

**Comment by zeffii** [comment]
each group could have a state, that overrides the overal Group visibility (but only if the groups visibility is On)

**Comment by zeffii** [comment]
My point with the examples is really that the VDMK2 node can be oblivious to any collection / layer / container we stick it in.  What exactly such a system (or node) should look like, and what features it should have, is going to emerge from usage... not planning alone). I would prefer to gradually upgrade a Layer Node than any of the Viewer Nodes..

**Comment by nortikin** [comment]
it have to be able close and open section with arrows
▶️ closed
◀️ opened
    🔲 🔲 🔲 🔲 🔲   🔲 🔲 🔲 🔲 🔲 
    🔲 🔲 🔲 🔲 🔲   🔲 🔲 🔲 🔲 🔲

**Comment by DolphinDream** [comment]
Is there a blender UI element you can add to a node that is similar to the panel items that lets you collapse/expand the UI groups?

**Comment by nortikin** [comment]
No, there is not complete blender construction. but for tree you can define `viewer_groups` collection property from BoolProperties that express arrow state and draw something like this:
```python
col = layout.column(align=True)
tree = self.tree
for vg in tree.viewer_groups:
    row = col.row(align=True)
    row.scale_y=1.1
    split = row.split(percentage=0.22)
    if vg.show_sv:
        split.prop(vg, "show_sv", text=" ", icon='DOWNARROW_HLT')
        split.prop(vg, "show_group", text...,icon...)
        for viewernode in vg[nodes]:
            split.prop(tree.nodes[viewernode], "activate", text=viewernode, icon="RESTRICT_VIEW_ON")
    else:
        split.prop(vg, "show_sv", text=" ", icon='RIGHTARROW')
```
not sure for collection property data. If you go to ui and look at panels:
https://github.com/nortikin/sverchok/blob/master/ui/sv_panels.py#L122
https://github.com/nortikin/sverchok/blob/master/ui/sv_panels.py#L256
but with collection property like this:
define https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L33 https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L547
write https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L76-L77
clear https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L301
add https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L133-L135
del https://github.com/nortikin/nikitron_tools/blob/master/MusicPlayer.py#L159

**Comment by nortikin** [comment]
for layers maybe can be used collection property from scene.layers...
