### ISSUE TITLE
Presets catalog fiesta :) 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2112]
How about starting a thread for posting various presets that You - the mighty SV user - rely on most often and that would likely be useful to other users? It would be cool if we could somehow vote for these submissions or have a way to “download” them and somehow count the number of downloads (similar to the blender swap) so that we can appreciate which presets are super-useful to most people. Perhaps the ones that make it to the top 10 could also be included by default with SV ? :)

**Comment by DolphinDream** [comment]
Here’s my first preset submission: a “Camera FlyBy” 

https://gist.github.com/f5a00857b767755b23d4216b6551b267

I often time find myself having to create a setup to create a camera flyby to move around an object. Circle is a common flyby path, but sometime I want a bit more variation, so a Torus Knot or an Ellipse make the fly by a little bit less boring. So... getting tired of creating such setups, I ended up creating one such preset (thanks to super awesome preset feature) :)

The preset is not most polished, but I added it here just to illustrate the idea. 

![sv-preset-cameraflyby](https://user-images.githubusercontent.com/2083719/35837499-7bb1c618-0ab4-11e8-98df-e176078d9933.png)

**Comment by nortikin** [comment]
https://vk.com/topic-35076122_35054289
the same in vk.com
Thank you, it is right place for nowaday

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/36019171-ae49e458-0d7e-11e8-88c1-72a85a742572.png)

https://gist.github.com/bd69caafbdbb167c575c74f296dcfa8a

**Comment by portnov** [comment]
https://gist.github.com/0a04c1c40d19ae09ac4cdea5e032e854
Calculate the "circle likelyhood" coefficient for a polygon, which is 1 for right polygons, and less than 1 for more deformed ones. May be interesting if you want to do something only with faces which are "round enough". For example, apply "adaptive polys" to "round enough" faces only:

https://gist.github.com/portnov/68a6a51ce7958642d92c372d2dcaba40
![Screenshot_20200107_234216](https://user-images.githubusercontent.com/284644/71920057-ce613d00-31a7-11ea-8e68-ba048fd12a6a.png)

**Comment by portnov** [comment]
This uses SciPy via scripted node `spherical_voronoi_3d_scipy.py` (which I've already put into examples in the repo) to draw a Voronoi pattern on any "Star-shaped domain surface" (https://en.wikipedia.org/wiki/Star_domain), i.e. closed surface, which can be made from sphere by moving points of the sphere along sphere's radius:

https://gist.github.com/fceb3fe74e1481afc222965ccb819893

Example:
https://gist.github.com/1f0dacf9f7b701423f07290eeea2411e

![Screenshot_20200108_122913](https://user-images.githubusercontent.com/284644/71958801-f33eca00-3212-11ea-8a05-4a4ad3bae492.png)

**Comment by portnov** [comment]
This uses our standard Voronoi 2D node plus Linear Approximation node, to make a Voronoi pattern on any "semi-plane" surface, i.e. non-closed surface, that can be made from a plane by moving it's points
https://gist.github.com/3ed90cc1d27b91e999082618ebbbc8bf

Example:
https://gist.github.com/9f5f2da3253caa204be07fd221cfcd4a
![Screenshot_20200108_130640](https://user-images.githubusercontent.com/284644/71960804-ba552400-3217-11ea-9538-2dd2b2411001.png)

**Comment by portnov** [comment]
Btw, I wonder, maybe it worth to integrate this "voronoi on any plane" functionality into our Voronoi 2D node itself?

**Comment by zeffii** [comment]
recreating capsule:

![image](https://user-images.githubusercontent.com/619340/72286197-f0920980-3644-11ea-8cd9-44dea6582751.png)

https://gist.github.com/b65ba758028fb4eb9f2b5018ff08b50a

**Comment by portnov** [comment]
This is implementing Lloyd's algorithm (2D only) (https://en.wikipedia.org/wiki/Lloyd%27s_algorithm) for "relaxation", re-arrangement of vertices to be more evenly spaced:
https://gist.github.com/b8d46abbfb3c0b3f9d8c6b2daaf6a754

![Screenshot_20200116_005103](https://user-images.githubusercontent.com/284644/72466465-bb2f1c80-37fa-11ea-8286-dc4455d41f44.png)


https://gist.github.com/95d6a2a78376f05ca738c40af8437c82

**Comment by enzyme69** [comment]
My feeling is that we need to have some kind of good basic presets for:
- Arc
- Tunnel
- Bridge
- Door / Gate

**Comment by enzyme69** [comment]
SV Cookie Jar. With missing top knob.

(I think this is quite beautiful setup. I wonder if Cylinder node can be incorporated.)

<img width="1189" alt="Screen Shot 2020-02-24 at 11 15 38 am" src="https://user-images.githubusercontent.com/3952687/75122937-16580700-56f7-11ea-996b-87db1a6d0ef6.png"> 

[cookie_like_008.blend.zip](https://github.com/nortikin/sverchok/files/4242771/cookie_like_008.blend.zip)

**Comment by enzyme69** [comment]
Railway Track / Ladder, probably can be tweaked better.

[like_railway_track_014.blend.zip](https://github.com/nortikin/sverchok/files/4243009/like_railway_track_014.blend.zip)

<img width="1445" alt="Screen Shot 2020-02-24 at 2 13 54 pm" src="https://user-images.githubusercontent.com/3952687/75126849-ecf7a500-570f-11ea-8605-696f2224a0c3.png">

**Comment by nortikin** [comment]
I need license in heared for gist
![изображение](https://user-images.githubusercontent.com/5783432/115963093-ef79a880-a526-11eb-9421-37189f3bf804.png)
CC-BY is it ok for you, folks?

**Comment by nortikin** [comment]
or CC BY-NC-SA
