### ISSUE TITLE
Simple Deformation Bend - how to get 360 or 2 pi perfectly?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2113]
[snake_it_001_2018_02_06_03_24.zip](https://github.com/nortikin/sverchok/files/1697643/snake_it_001_2018_02_06_03_24.zip)
<img width="987" alt="screen shot 2018-02-06 at 2 23 57 pm" src="https://user-images.githubusercontent.com/3952687/35840295-7570967c-0b49-11e8-82aa-e2dadb9d3b40.png">

I am trying to get a bend that is perfectly circular 360 ° but could not get it to work, any idea what I did wrong?

**Comment by Durman** [comment]
Try this ))
https://gist.github.com/4ff45599723c1a5a77762373d626d1b5
![2018-02-06_08-31-22](https://user-images.githubusercontent.com/28003269/35841922-4e6cacfe-0b18-11e8-86ee-5d24bcd53d0e.png)

**Comment by enzyme69** [comment]
@Durman Oh, it works with flat grid, but not with the hexagon isn't that strange. Can Surface Bender then make it close? Hmm...

**Comment by enzyme69** [comment]
Hmm... stumbled into old confusion.
[simple_deformation_angle_002_2018_02_06_08_13.zip](https://github.com/nortikin/sverchok/files/1698255/simple_deformation_angle_002_2018_02_06_08_13.zip)

**Comment by enzyme69** [comment]
<img width="840" alt="screen shot 2018-02-06 at 7 27 50 pm" src="https://user-images.githubusercontent.com/3952687/35848886-db0a0d4a-0b73-11e8-9169-02a4827aa0cd.png">
[hexa_bending_001_2018_02_06_08_27.zip](https://github.com/nortikin/sverchok/files/1698290/hexa_bending_001_2018_02_06_08_27.zip)

Nope, it just does not want to close itself, maybe because of the bounding box.

**Comment by Durman** [comment]
Maybe thus?
https://gist.github.com/720b786e96ba2557ba6317ef411f9515
![2018-02-06_12-54-44](https://user-images.githubusercontent.com/28003269/35850085-24d9bff6-0b3d-11e8-8cf5-0c5eb1abc8e8.png)

**Comment by zeffii** [comment]
The deformation code first establishes a 2D bounding box for the input geometry, here the green shape shows that 2D bounding box being deformed. (as an illustration)

![image](https://user-images.githubusercontent.com/619340/35850775-35c221a8-0b26-11e8-8987-d35c04582c65.png)

**Comment by enzyme69** [comment]
Thanks now this makes sense! Will study tiling more~

**Comment by zeffii** [comment]
I also wondered about this @enzyme69 , it wasn't until I simplified the input geometry to a plane (which wraps up into a cylinder) did the reason become apparent.
