### ISSUE TITLE
profilemk2 profilizer operator assumes closed bezier

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2123]
this bezier is imported like this (closed)  

![image](https://user-images.githubusercontent.com/619340/36022236-a1896ec8-0d88-11e8-8352-a53a9a4f6b40.png)

(offset intentional for comparison)

**Comment by nortikin** [comment]
so?
Should we fix cycled bezier to correctly be read from xml?
There is hack way i added - adding closing line to close curve. But if it will close curve from end-point curve i will remove line ending

**Comment by nortikin** [comment]
ok, see now

**Comment by nortikin** [comment]
so, if two curves in text one have `x` other not, it will cause both cycled.
Parser need to be writed more.

**Comment by zeffii** [comment]
i have been tempted to rewrite the main parser, it has not changed much since the first implementation.

**Comment by nortikin** [comment]
ok, i will fix now

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/commit/9e1b95471105f1fb25125e2f0cc6e8062fbf2f03#diff-d18a9dc63fe3c895ab599b5a49b5bb59
just now.
but order of curves defines if it will be defects. first open curve it join several curves/ for first closed and last open curve it will do well
