### ISSUE TITLE
Frames in Sv have a rightclick behaviour :)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2124]
I didn't make this well known, but it's handy and it works well. If you make a (new) frame active, you can get a context menu when right clicking. It shows

```
name:          [                       ]
(use) color:   [                       ]
text size      [                       ]
shrink:        [                       ]
```
the ui is a little wonky, but that's the best that BPY will permit inside a regular menu.
![frame_usage](https://user-images.githubusercontent.com/619340/36027011-c01727ac-0d99-11e8-8ef4-0a7b16c4ef69.gif)

**Comment by nortikin** [comment]
hahaha
