### ISSUE TITLE
Import of "Text In ++" is broken

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2126]
## Problem statement

https://gist.github.com/portnov/582de3f84a99210493882393a9137ef9

```

======================================================================
ERROR: test_import_examples (tree_import_tests.ExamplesImportTest) (file='5.Sverchok_Spread.json')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/tests/tree_import_tests.py", line 66, in test_import_examples
    import_tree(new_tree, path)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 729, in import_tree
    generate_layout(fullpath, nodes_json)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 711, in generate_layout
    place_frames(ng, nodes_json, name_remap)
  File "/home/portnov/.config/blender/2.79/scripts/addons/sverchok-master/utils/sv_IO_panel_tools.py", line 638, in place_frames
    ng.nodes[finalize(node_name)].parent = ng.nodes[finalize(parent)]
KeyError: 'bpy_prop_collection[key]: key "Text in+.001" not found'
```

## Steps to reproduce

1. Load example "5.Sverchok_Spread.json"
2. replace Text In nodes with Text In ++
3. Export result to json again
4. Try to import it again (from test or manually from blender, doesn't matter)

## Expected result

Loaded node tree

## Actual result

Exception

## Sverchok version

git master

**Comment by zeffii** [comment]
[5spread_textin_test_2018_02_10_08_53.gz](https://github.com/nortikin/sverchok/files/1713210/5spread_textin_test_2018_02_10_08_53.gz)

**Comment by zeffii** [comment]
https://gist.github.com/b0b21b5aa1af9c8b8a06bc24c84d7c58

**Comment by zeffii** [comment]
hmmm..
```
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 432, in perform_svtextin_node_object
    current_text = params['current_text']
KeyError: 'current_text'
```

**Comment by zeffii** [comment]
```python
    params = node_ref.get('params')
    current_text = params['current_text']

```
looking at this json
```
    "Text in+": {
      "bl_idname": "SvTextInNodeMK2",
      "color": [
        0.5,
        0.699999988079071,
        1.0
      ],
      "current_text": "Cube",
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        1581.4335479736328,
        733.016357421875
      ],
      "params": {
        "text": "Cube",
        "textmode": "JSON"
      },
```

**Comment by zeffii** [comment]
```
current_text = params.get('current_text', params.get('text'))
```

**Comment by zeffii** [comment]
that will support the old text_in for another while.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2128

**Comment by zeffii** [comment]
this fixes the inability to import such a gist, it does leave some redundancy (one key) -- which doesn't bother me

**Comment by portnov** [comment]
@zeffii there is yet another problem... How is order of outputs defined? 
Here is "fixed" json_examples/6.AdaptiveSpread.json : https://gist.github.com/portnov/3da6519f58c2bfa67e6ca5bc903666f8
When I try to import it, order of outputs of top "text in" node is not the same as when I exported it, so node connection is wrong. So imported layout does not work.

**Comment by portnov** [comment]
Hmm. It looks for "socket_order" key, and if it is not defined - uses "standard" order, which is actually random. I think we should at least sort outputs alphabetically then.

**Comment by zeffii** [comment]
`socket_order` didnt exist in `< text in+` ..so it was always broken.

**Comment by zeffii** [comment]
if you really wanted you could manually edit the json to include the socket_order key,

**Comment by zeffii** [comment]
but you're saying even a new layout exported doesn't contain socket_order ?  ..

**Comment by zeffii** [comment]
you won't fix the inferred order.
https://gist.github.com/99601eae90fb029b0477290c0cc9eedb   added `socket_order`

**Comment by zeffii** [comment]
it won't fix gists that store `index` but not `socket_order` .  I don't think there will be many such gists..

**Comment by zeffii** [comment]
this might be one of those  times where there's no satisfactory solution, for gists generated between a few weeks last year :)

**Comment by portnov** [comment]
Closing this, we can continue discussion in the PR thread.
