### ISSUE TITLE
DateTime repeat data injectors

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2145]
imagine you have data like this
```
date,value
12/08/2017,34
13/08/2017,38
23/08/2017,39
03/09/2017,34
13/09/2017,32
02/10/2017,30
```
and you want to draw a line that shows how the value changes over time. In my scenario I want the `value` to jump and stay at that value until the next day it changes, i want all days not explicitly given to also generate a value .. and a date :)

![image](https://user-images.githubusercontent.com/619340/36424199-c9916f84-1642-11e8-9c0a-87d6c29b49cf.png)

the SNlite for that is
```python
"""
in dummy s
out dates s
out values s
"""

import bpy
from datetime import datetime, date, timedelta

csv = bpy.data.texts['caldera.csv'].as_string()

date_format = "%d/%m/%Y"

csv_data = []
for idx, item in enumerate(csv.splitlines()):
    if idx == 0:
        continue
    k, v = item.split(',')
    print(k, type(k), v, type(v))
    csv_data.append((k, int(v)))

csv_data_dict = {date: insuline for date, insuline in csv_data}

dates_out = []
values_out = []

def generate_interpolation_data(csv_data):
    start = csv_data[0][0]
    end = csv_data[-1][0]
    
    a = datetime.strptime(start, date_format)
    b = datetime.strptime(end, date_format)
    delta = b - a
    num_days = delta.days

    insuline = 0
    for i in range(delta.days + 1):
        day = a + timedelta(days=i)
        day_str = day.strftime(date_format)
        insuline = csv_data_dict.get(day_str, insuline)
        dates_out.append(day_str)
        values_out.append(insuline)

generate_interpolation_data(csv_data)

dates.append(dates_out)
values.append(values_out)

```
but In case i want to lines with angles ( I don't ) , then another step is needed. -- no time now.

[resurge_2018_02_20_12_40.zip](https://github.com/nortikin/sverchok/files/1740069/resurge_2018_02_20_12_40.zip)

**Comment by enzyme69** [comment]
Can the date be the same?

**Comment by zeffii** [comment]
> Can the date be the same?

in this script there's an assumption that all datapoints (datetime formatted strings) are for different days. If that's what you want to know.  Something similar can be made for values during the day.. but not with a single line of code change.. i think
