### ISSUE TITLE
Injecting Shapely for Sverchok 2D

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2146]
I am curious and wondering whether this Shapely "modules" can be of anyone use for dealing with 2D shapes in Sverchok realm:
http://www.ia.arch.ethz.ch/shapely-as-a-python-module-for-blender/

@zeffii you mentioned this Shapely at some point and I am actually manage to get something working, but currently I need to type Python script.

I try generating random X, Y point with buffer size radius using Python and I realized how much I took Sverchok nodes for granted 👍 

Shapely seems to be able to do boolean 2D in a cool way. I am still reading documentation.

**Comment by zeffii** [comment]
@enzyme69  https://github.com/nortikin/sverchok/issues/763

**Comment by enzyme69** [comment]
Will make a video of my impression comparing Sverchok and Shapely.

**Comment by enzyme69** [comment]
<img width="1141" alt="screen shot 2018-02-22 at 8 39 22 pm" src="https://user-images.githubusercontent.com/3952687/36530918-7da5e7ec-1810-11e8-9238-d0832f5390a2.png">

I think the Python command provided by that Shapely module is pretty "easy" enough for artist.  But I do find that this kind of generating and operating objects with Python script still feels pretty weird for me. I do not know how to explain it.

With nodes, it's like million times easier.

**Comment by zeffii** [comment]
this doesn't work.. but i suspect with some tweaking of the input it would..
```python
"""
in verts_A v
in verts_B v
out verts_MIX v
out faces_MIX s
""" 

import shapely
from shapely.geometry import Polygon

def to_2d(vert_list):
    return [v[:2] for v in vert_list]

if verts_A and verts_A[0]:
    # print(to_2d(verts_A[0]))
    poly_a = Polygon(to_2d(verts_A[0]))
    # print(poly_a.bounds)

    if verts_B and verts_B[0]:
        poly_b = Polygon(to_2d(verts_B[0]))
        print(poly_b.bounds)
        
        # poly_a and poly_b exist:
        poly_mix = poly_a.intersection(poly_b)
        print(dir(poly_mix))

```
![image](https://user-images.githubusercontent.com/619340/36534120-ed4d8c80-17c5-11e8-8042-48fcf3b14d94.png)

**Comment by zeffii** [comment]
this does work..
```python
"""
in verts_A v
in verts_B v
out verts_MIX v
out faces_MIX s
""" 

import shapely
from shapely.geometry import Polygon

def to_2d(vert_list):
    return [v[:2] for v in vert_list]

if verts_A and verts_A[0]:
    # print(to_2d(verts_A[0]))
    poly_a = Polygon(to_2d(verts_A[0]))
    # print(poly_a.bounds)

    if verts_B and verts_B[0]:
        poly_b = Polygon(to_2d(verts_B[0]))
        # print(poly_b.bounds)
        
        # poly_a and poly_b exist:
        poly_mix = poly_a.intersection(poly_b)
        print(dir(poly_mix))
        verts_MIX.append([[(v[0], v[1], 0.0) for v in poly_mix.exterior.coords]])
```

![image](https://user-images.githubusercontent.com/619340/36534775-d215e06e-17c7-11e8-9fda-4b90d3e6ce88.png)
[trotski_2018_02_22_11_00.zip](https://github.com/nortikin/sverchok/files/1747601/trotski_2018_02_22_11_00.zip)

**Comment by zeffii** [comment]
i find it reassuring that the limitations in shapely are also based on issues with shared edges / edge colinearity

**Comment by enzyme69** [comment]
I have only tested the "blender_show.py" so far, not yet making node.

I like the script node, even this can be handy. 
<img width="520" alt="screen shot 2018-02-22 at 10 32 17 pm" src="https://user-images.githubusercontent.com/3952687/36536222-44eb9680-1820-11e8-8253-f53860b408b8.png">

It can generate interesting mesh shapes, even though "not perfect". I will try to study this.

**Comment by zeffii** [comment]
@enzyme69  you will need to take time to read through the shapely documentation (which is nice and long and seems comprehensive).

i'm reluctant to make a shapely node part of the standard Sverchok distro, because it is a dependency.. on the other hand it would be nice to experiment with including some reliance on `scripts/modules` folder. Installations that don't have the `shapely` module would simply produce a 'shell' of a shapely node.

**Comment by zeffii** [comment]
Shapely has many features, it would require a whole category just for Shapely nodes to get access to all the goodies in a sane way. Maybe even their own socket type. I'll think about it, it would need to stay beta for a long time..and people would have to expect stuff to break..

but.. to start that ball rolling i'd welcome people providing SNLite examples that match the documentation.. maybe even reach out to the maintainers of Shapely module they might get a kick out of it.

**Comment by enzyme69** [comment]
Yes, will do that, thanks for showing the way!

**Comment by portnov** [comment]
@zeffii I was thinking, that some day there might appear one or several Sverchok addons with specific dependencies. I.e. we (or somebody else) could develop separate blender addons, which would import sverchok and define their own nodes. Such separate addons may have a lot more freedom about dependencies. For example, there could be an addon with nodes that use shapely, another addon with nodes that use mcubes, and so on.

**Comment by zeffii** [comment]
yep @portnov ,  and some of those addons could implement their internals in a faster language :)

There's now an add-on update for AudioNodes with a rewritten backend in C++:  https://github.com/nomelif/Audionodes
