### ISSUE TITLE
Bending cylinder like pipe and straw way

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2150]
I am looking at this  question at Stack Exchange:
https://blender.stackexchange.com/questions/101616/bend-a-cylinder-by-its-middle?atw=1

This is a good opportunity to show what Sverchok can do, I think.

1)
At first, I am thinking to use Cylinder, maybe + bended Cylinder, attached the end + Cylinder. I think this is possible although getting first and last end of cylinder and direction still slightly tricky.

<img width="545" alt="screen shot 2018-02-24 at 8 36 07 pm" src="https://user-images.githubusercontent.com/3952687/36628852-5dbf3f9e-19a2-11e8-9383-8c8980abd615.png">

I realized, Simple Bend node apparently does not work multiple times! 

2)
So I decided to use different method just Line and Bevel, but somewhat this does not work with mesh data with Polygon and Edge only. 

<img width="840" alt="screen shot 2018-02-24 at 8 35 25 pm" src="https://user-images.githubusercontent.com/3952687/36628848-49f5a8ae-19a2-11e8-9c44-622d94cad2c6.png">

Not sure whether I am overthinking and miss a simpler solution.

Blend so far:

[bendy_cylinder_004_2018_02_24_09_35.zip](https://github.com/nortikin/sverchok/files/1754212/bendy_cylinder_004_2018_02_24_09_35.zip)

I rather go with 1st method and maybe work with multiple Cylinder chaining technique... but any other ideas?

**Comment by enzyme69** [comment]
<img width="943" alt="screen shot 2018-02-24 at 8 46 00 pm" src="https://user-images.githubusercontent.com/3952687/36628966-bbf4a652-19a3-11e8-880a-3bbdb2b5dbb6.png">

This one is probably not yet ideal, but most logical...

I imagine with a cylinder, it would be nice if one can just easily attach to top and bottom with orientation matching each end.

**Comment by enzyme69** [comment]
[bendy_cylinder_004_2018_02_24_09_58.zip](https://github.com/nortikin/sverchok/files/1754233/bendy_cylinder_004_2018_02_24_09_58.zip)

This is wrong.

**Comment by zeffii** [comment]
see https://github.com/nortikin/sverchok/issues/942#issuecomment-368221087

please correct the Title "Being cylinder like" is maybe a little zen.

**Comment by enzyme69** [comment]
@zeffii Interesting sophisticated way! :D Can the input be simplified like turning any sharp corner into this nice bendy point? Supposedly Edge Bevel does it, but it does not work without poly face somewhat.

**Comment by zeffii** [comment]
the current bevel node does not work handle this scenario (ie not able to selectively pick verts to Fillet/Bevel), hence a small snlite script was my solution. Most of that node tree is just for creating the base geometry to apply bevel to.

**Comment by enzyme69** [comment]
Ok then maybe I will use the hard way for not just piecing cylinder, bended cylinder and working on top and bottom part.
