### ISSUE TITLE
Mechanical animatronic automaton 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2153]
In theory, we could create a parametric design that when we set up with blender rigid body, it will start a cyclic motion like walking etc, right? I just think this is one area no one is yet doing. 

Ready to crawl, just insert motor:
https://m.youtube.com/watch?v=G0-lJKOgTuo

So far I have only tested a dynamic random shapes with cloth sims.

Maybe somebody can try gear setup or maybe sproings kind of effect, not sure if possible, kind of like if you have a spring and push it into tube.

I actually wanna make wintergattan style music, using sverchok...

**Comment by nortikin** [comment]
wow

**Comment by enzyme69** [comment]
![rigid_001](https://user-images.githubusercontent.com/3952687/36636458-f4d0e328-1a1b-11e8-9c9b-63062388e493.gif)

I know nothing about Blender Rigid Body and its limitation and what it capables of. But will try simple one, at least making a motor motion or walk cycle.

I know there are some Blender users making some dynamic virtual robot at some point. A new area in itself.

**Comment by enzyme69** [comment]
Seems to work although currently the only gotcha is how Sverchok BMesh MK2 is grouping based on name, and in many cases, one would like to separate name of mesh and grouping.

**Comment by Durman** [comment]
One more cockroach: )) https://www.youtube.com/watch?v=CeJYarsCcwA&index=41&list=PLbOv_IBJppejk2Guw0PnCjU6xlxl3WrEb&t=0s
