### ISSUE TITLE
Viewer BMesh overwrites updates would be nice

### ISSUE THREAD

**Issue by MasterJames** [nortikin/sverchok#2154]
It would be nice if the "Viewer BMesh" node 'updated' it's output mesh per frame instead of replacing certain aspects of it. Example in case Dynamic Paint maps.

I was trying to use dynamic paint on a curve so I thought to use the Objects in MK3 to Viewer BMesh for per frame curve to mesh conversion that suites nicely in many situations to help resolve the fundamental flaw of Blender... that it's not as procedural as it could (or should, really needs to) be.
Since a Curve is not a mesh, it doesn't have options to add dynamic paint physics. Using the Viewer Bmesh from Objects in MK3 does the trick but every frame update destroys the Dynamic Paint Output aka Vertex Colors generated when setting that up.

It would be great if there's a way to not upset those paint layers etc. I'm assuming it generates the object again and knows not to damage the material settings, so it would seem maybe this is an easy fix and just an oversight, or it could rebuild those if it's found and transfer the paint from one map to the next?!

Again I hoped to see the Physics Dynamic Paint, Dynamic Paint Output, Vertex maps to not be corrupted and deleted per frame when BMesh generates. Unfortunately they get removed when the BMesh regenerates the geometry. 

I suppose it's probably impossible because the mess is changing and the vertex are different. I will aspire to find another solution. Maybe there is a way to use a particular final frame as the permanent map (assuming there's a frame with the most geometry to bake/freeze one working vertex map) and previous frames with less vertex just don't have the geometry to paint on those vertex. I guess it's a problem of being completely disconnected code etc. In a way it seems you are the best suited to make blender better in these (lacking procedural) ways.

Feel free to close this if it's not doable, but I'm hopeful it's just an oversight and with some thinking there is away.

**Comment by portnov** [comment]
There is "Fixed vert count" setting in the N panel of bmesh viewer node. If it is checked, then the node does not recreate the mesh, only updates it.
Unintuitive name for the checkbox, maybe...

**Comment by zeffii** [comment]
After reading the BMViewer source again, it never add the vertex_color layer explicitely, if you are manually adding it from the Blender 3D viewport i think it might survive the 'overwrites' if you tick `fixed_verts` .

**Comment by MasterJames** [comment]
Okay wow great feedback everybody all helpful.
Unfortunately it still stomps on (aka deletes) those "Vertex Colors" from the Dynamic Paint Output.
The topology is changing but I was still thinking if when I check the "Fixed vert count" at the max vert count frame those mappings would again only paint when and where the vertex are for a lesser vert count shape (because it's pretty consistent from model to model with a simple line extension). 

Anyway it does seem unlikely that will or should be workable. I can see a custom hack is needed, but pretty noob on this but I do know Houdini etc. so it's within my ability... eventually.
What I did was used an imported curve with handwriting and with round Bevel Object animated the Bevel Factor's End value to animate the ink of the pen tip as it where (imagined).
My thought with regards to some nice particle sparks I added and a bright emitter glowing pen tip was to have the newly formed (ink/weld?) glow red hot for a moment as it glowed down to a cold hard result (would make it look cooler more believable).  
It's so close but yet so far. I think it's not worth for me to try to custom build this via Sverchok nodes, but I think there' would be a way just not very simple likely a very different approach all in nodes without piggybacking in the Blender stuff that already exists.
I was also able to do a simple test with the Dynamic Paint to achieve this glowing tip on a simple static geometry cylinder/rod.
Any thoughts on how to do this would be appreciated, as well as mind opening on how to navigate beyond the wall I've been bashing up against.

I know in the corner of my mind I've done a curve deform and animated the x-scale of a sufficiently subdivided tube before, so maybe that's the better way for this afterthought to add a cooling glow?

Some sort of UV mapping texture ramping, or skinning of a static geo come to mind but I don't think either of those would flow like the pen tip does. Also I'm animating the Taper Object with shape morphs to help the thickness where it's expected and some kind of ink absorption/expansion expectation.
It's too bad Curves don't currently import pressure weights per vertex/vector.

As a side note pressure or force is in the newest spec for multitouch devices and so something to actually think about being needed in the not too distant future. 

https://developer.mozilla.org/en-US/docs/Web/API/Touch/force
Touch Events Level 2
https://w3c.github.io/touch-events/#widl-Touch-force

Anyway maybe I should just think about how to animate a ramp along the UV in U. I'm actually not sure how to do that in blender. I could somehow add transparent after/before the tip maybe and manage to do it with a static model. I'm sure I did this decades ago in the Max or maybe more recently in Houdini.

**Comment by zeffii** [comment]
fixed vertex count , really means you need to keep the verts/edges/faces the same. So if you're doing anything that changes those then fixed vertex count doesn't help.

**Comment by zeffii** [comment]
dead issue? not much can be done i think..

**Comment by zeffii** [comment]
I should clarify that statement. I'm not willing to change the BMeshViewer node for the described user scenario. However... once the `mixin` version with object_helper is pushed, it would be much easier to write a dedicated Mesh Object node that could attempt to solve some of the problems mentioned above. (but perhaps still not actually provide a working solution...)
