### ISSUE TITLE
2D voronoi with radius parameter

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2161]
Result: https://github.com/nortikin/sverchok/files/1851743/voronoi.with.radius7_2018_03_27_11_29.zip
I have sum thoughts about creating this algorithm:
![2018-03-07_21-01-20](https://user-images.githubusercontent.com/28003269/37109334-16acca04-2253-11e8-80ce-6e36817dad11.png)
![2018-03-07_21-02-18](https://user-images.githubusercontent.com/28003269/37109382-3a0fe29c-2253-11e8-99c5-d5bbfc48b6f8.png)
![2018-03-07_21-02-42](https://user-images.githubusercontent.com/28003269/37109402-47b3be0a-2253-11e8-9cad-d9a550f1e584.png)
![2018-03-07_21-03-03](https://user-images.githubusercontent.com/28003269/37109420-5352687e-2253-11e8-8850-e5175930f2d4.png)
Creating arc with two points and center:
https://gist.github.com/b21c411afde560cf99c5b2f2589ad3c8
![arck](https://user-images.githubusercontent.com/28003269/37109840-a1097372-2254-11e8-833d-9484e4302fd5.gif)

**Comment by vicdoval** [comment]
I stepped through that output when i was coding de "Contour 2D", but for the purpose of the node I deleted the separation lines.
Probably this lines could be easily exposed to get this "voronoi arc" all the math is already inside the node
And it works with weighted radius.
![screen](https://user-images.githubusercontent.com/10011941/37204434-16d3b18e-2391-11e8-83c1-4d01731a5001.png)

**Comment by Durman** [comment]
I allready have written something but didn't test it yet.)
```Python
def get_arc(start_v, end_v, center_v, resolution, mode='clockwise'):
    #return points of arc by two points and center of circle
    #resolution determines distanse between points of arc
    start_v, end_v = start_v - center_v, end_v - center_v
    start_angle = calc_angle(Vector((0,1)), start_v)
    #angle between start and end vectors
    angle = calc_angle(start_v, end_v)
    radius = get_distance(start_v, end_v)
    len_arc = get_len_arc(radius, angle)
    count = len_arc / resolution
    end_angle = start_angle + angle if mode == 'clockwise' else start_angle + angle - TWO_PI
    steps_angle = list(np.linspace(start_angle,end_angle,count))
    vectors = [Vector((sin(ang),cos(ang))) * radius + center_v for ang in steps_angle]
    return vectors
```
I think about how to keep data now. Just using lists is seemed too confusing. I think I will do two dictionary one for data of vectors and other for data of edges. Dictionary of vectors will keep information about neighbours of current point and something else maybe. Dictionary of edges will keep information about found chords of circles because there is no point to calculate chords for each point whose located on one edge. 
Something like that:
```Python
def get_structure_vert():
    dictionary = {'neibs':[],
                  'ang_neibs':[],
                  'sorted_neibs':[]}
    return dictionary
                  
def get_structure_edg(edg):
    dictionary = {tuple(edg):{'height_chords':[],
                              'chords':[],
                              'intersect_chords':[]}}
    return dictionary
```
Nested dictionary also can get confuse :/

**Comment by vicdoval** [comment]
For sure you may found a faster/clearer way of doing it  :D 
I keept the information in lists, is confusing but works (also with np).


I did a fast transformation from the contour2d into voronoiArc in case you want to test it, (It creates glitches  in complicated situations)
 https://github.com/vicdoval/sverchok/tree/voronoi_arc_2d
![screen](https://user-images.githubusercontent.com/10011941/37225398-ce70071c-23d6-11e8-8f69-7aeb5ee11cd6.png)
![screen1](https://user-images.githubusercontent.com/10011941/37225399-ce8a0072-23d6-11e8-8edc-59cbc342a0d3.png)




Maybe it is not even the same concept but looks similar isnt it? :D

**Comment by Durman** [comment]
I tested your node, it is really hard node, a lot of functions and code.)) And it works not as voronoi diagram now. The sense of voronoi is to have equal radius for each point otherwise diagram will not be voronoi.
![1](https://user-images.githubusercontent.com/28003269/37238381-972cc020-243e-11e8-8af8-f9b8c247530c.png)
[voronoi sense_2018_03_10_04_38.gz](https://github.com/nortikin/sverchok/files/1799088/voronoi.sense_2018_03_10_04_38.gz)
I am going to make a more easy node. Main work will do delaunay triangulation, this algorithm we already have. After that I have to only find chords of circles and work will be done.))

**Comment by vicdoval** [comment]
:) 
I did my best clearing the code but you know..
If you want you can search about "variable radius voronoi" or "Weighted Voronoi diagram" it is a pretty interesting topic, maybe not part of what you are searching right now :D

**Comment by Durman** [comment]
It have appeared really hard goal for me in spite that all math stuff are clear. But however I managed to do something. It is far from the end yet.

![chords](https://user-images.githubusercontent.com/28003269/37701956-68e018e6-2d0a-11e8-8c33-7497f57955ce.gif)

**Comment by Durman** [comment]
Something have gone wrong ))

![arcs](https://user-images.githubusercontent.com/28003269/37750919-da2cfb92-2da8-11e8-9ffc-19b7b4639e70.gif)

**Comment by Durman** [comment]
![2018-03-22_09-31-07](https://user-images.githubusercontent.com/28003269/37752953-02af81f6-2db4-11e8-95fd-3614bd2dcb4d.png)

**Comment by Durman** [comment]
It looks like nearly working. Process of implementation was really painful. I didn't use any articles about voronoi diagram so I faced with a lot of unpleasant surprises. And it is a little bit strange that it is working in the end.
![2018-03-27_08-56-29](https://user-images.githubusercontent.com/28003269/37947866-5b0dd350-319e-11e8-97f6-0e89c790eaf2.png)

**Comment by Durman** [comment]
Ready for test.
[voronoi with radius7_2018_03_27_11_29.zip](https://github.com/nortikin/sverchok/files/1851743/voronoi.with.radius7_2018_03_27_11_29.zip)

**Comment by Durman** [comment]
Dividing to buildings based on this algorithm.
![2018-03-28_16-37-43](https://user-images.githubusercontent.com/28003269/38029333-9fc9c69e-32a6-11e8-91da-27dc711eb857.png)

**Comment by Kosvor2** [comment]
@nortikin can you send @Durman invite for collaboration? no one have time to test things from outcomers. Sverchok is just an addon after all.

**Comment by Durman** [comment]
I don't think it is really necessary. I always can create pull request, isn't it? ))

**Comment by Durman** [comment]
![2018-03-29_15-37-03](https://user-images.githubusercontent.com/28003269/38086908-3d54bf52-3367-11e8-8acb-832fa8a6b421.png)
![2018-03-29_15-39-44](https://user-images.githubusercontent.com/28003269/38086963-6c861258-3367-11e8-86c8-f74f0542c84e.png)

**Comment by Durman** [comment]
![2018-03-30_13-16-18](https://user-images.githubusercontent.com/28003269/38132602-ba68b2d6-341c-11e8-9be5-8d836b06e98b.png)

**Comment by zeffii** [comment]
lovely stuff @Durman !!

**Comment by nortikin** [comment]
invited

**Comment by Kosvor2** [comment]
@Durman now you can create this template here: https://github.com/nortikin/sverchok/tree/master/node_scripts/SNLite_templates

**Comment by Durman** [comment]
Ok, I will do it soon.
