### ISSUE TITLE
Math MK2 SinCosX is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2165]
## Problem statement

I am using SinCosX node of Math MK2 and Cos X is not giving any output.

## Steps to reproduce

1. Attach frame into Math SinCosX
2. Check Sin and Cos X output

## Expected result

Sin and Cos X both giving output at the same time, but nothing from Cos X

## Actual result

Only Sin X is giving output, Cos X is giving error..,..

```
Traceback (most recent call last):
  File "/sverchok-master/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/sverchok-master/nodes/text/stethoscope_mk2.py", line 142, in process
    data = inputs[0].sv_get(deepcopy=False)
  File "/sverchok-master/node_tree.py", line 417, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "/sverchok-master/core/socket_data.py", line 108, in SvGetSocket
    raise SvNoDataError(socket)
sverchok.core.socket_data.SvNoDataError: No data passed into socket `Data'
```

**Comment by Durman** [comment]
I don't see problem:
https://gist.github.com/6b544b7f9638714fa3aaf3d4611e6bf0
![2018-03-09_06-54-50](https://user-images.githubusercontent.com/28003269/37189715-2bb77bca-236f-11e8-902b-9addddcf3d67.png)

**Comment by zeffii** [comment]
i suspect you are feeding some empty lists into the Math Mk2 node @enzyme69 .

**Comment by zeffii** [comment]
@portnov  i think we should add more info here

```diff
- sverchok.core.socket_data.SvNoDataError: No data passed into socket `Data'
+ sverchok.core.socket_data.SvNoDataError: No data passed into socket `Data' of <node name>
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/37203060-bc7cb5ae-238c-11e8-8fec-9199c2806cb8.png)

**Comment by zeffii** [comment]
it's not broken.

**Comment by enzyme69** [comment]
So weird.... and I cannot update Sverchok, I might reinstall.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
if you want the updating to work you need to use a builder.blender org build .. not `b2.79 Release Candidate A`
