### ISSUE TITLE
Skin mesher and and other viewers are not orange

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2166]
## Problem statement
The output nodes in severchok are orange.
Shouldn't this be the same for the skin mesher, the typography viewer, the curve viewer and the Polyline Viewer?
## Steps to reproduce

1.  Insert any of the mentioned nodes
2. They are not orange

**Comment by zeffii** [comment]
that's a not a bug :)  the viewers beside BMeshViewer and ViewerDrawMk2  are still beta. Not sure i'll change that.

The upside is that there's a pull request that introduces a new set of Viewer nodes that reuse a lot of Mixin class, and they are all intended to be Release quality nodes. Not sure when I'll get time to finish and push that.

**Comment by vicdoval** [comment]
Ok, thanks for the explanation. I found your work at https://github.com/nortikin/sverchok/pull/1951
The color is just a small detail you already thought about :) I was creating some educational documents and I realized that they weren't orange (a little incoherence) 
Anyway thanks again for you work!
