### ISSUE TITLE
PyAudio Realtime Audio, what does it take to have a node that runs separately?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2169]
Thinking to have some kind of setup that can listen and trigger action by audio in real time, I am looking at this PyAudio script:
https://www.swharden.com/wp/2016-07-19-realtime-audio-visualization-in-python/

I manage to run the script using Blender 2.79 with Python 3.5.4, it does not work with latest Blender with latest Python unfortunately.

I first test it using AN like below, but would like to make it work using SV and Script Node:
[pyaudio_realtime_006.blend.zip](https://github.com/nortikin/sverchok/files/1821095/pyaudio_realtime_006.blend.zip)

Kind of works for few seconds but then I think I have too many instance of PyAudio and it is halted....

Seems like I could not just keep calling the Python script on every frame. This is one case where I need to node to keep running in the background and listen without frame being advanced... 

Sverchok has UDP Port that can listen and send message, similar to OSC, but that's beyond my brain ability.

**Comment by enzyme69** [comment]
Potential usage:
- Real time Audio Visualization
- Speech Recognition: can run and trigger action by human voice

**Comment by enzyme69** [comment]
Might be also related, I am looking at this:
https://github.com/zeffii/audio_nodes

**Comment by zeffii** [comment]
i removed `zeffii/audio_nodes` . https://github.com/nomelif/Audionodes is where development of that add-on is happening.

**Comment by zeffii** [comment]
> Sverchok has UDP Port that can listen and send message, similar to OSC, but that's beyond my brain ability.

You should see that as an opportunity to learn. Get stuck in.

**Comment by zeffii** [comment]
we've already been down this road. https://github.com/nortikin/sverchok/pull/815

**Comment by enzyme69** [comment]
Ok, looks like I am back in this cycles and still has not found the answers. It's quite frustrating whenever one knows what he wants and it should be as simple as plug and play but even installing it is quite hard.... This should be so simple.

Will meditate...

**Comment by enzyme69** [comment]
This might be the way to properly install PyGame before this PyAudio business...
http://brysonpayne.com/2015/01/10/setting-up-pygame-on-a-mac/
