### ISSUE TITLE
navigating away from nodetree, and back to restore appropriate tree

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2184]
@enzyme69 brought this up a long time ago, but here's some example code of what could be used to do this in a simple way.

in `class SverchCustomTree(NodeTree, SvNodeTreeCommon):`

```python
    @classmethod
    def poll(cls, context):

        editing = context.space_data.edit_tree
        ntree = context.space_data.node_tree

        show_sverchok = True if ntree else False
        
        if editing:
            return True

        if len(bpy.data.node_groups):
            if len([ng for ng in bpy.data.node_groups if ng.bl_idname == 'SverchCustomTreeType']):
                if not editing or ntree:
                    context.space_data.node_tree = bpy.data.node_groups[0]  ### INFO 

        return True
```
the selection marked "### INFO" is the tentative part, this should be picking from the last touched sv node trees, not just blindly `node_groups[0]`

**Comment by nortikin** [comment]
simply that?

**Comment by zeffii** [comment]
probably not as simple as this.. would need to keep track of more info to test even this simple solution, else it has to be done in `scene.update_pre` event handler (or whatever) . but maybe soon i will have time.
