### ISSUE TITLE
how to filter list in sverchok

### ISSUE THREAD

**Issue by gastrodia** [nortikin/sverchok#2187]
## Problem statement

if I have too list , for example [1,2,3,4,5] and anthor [3,5] , i want get [1,2,4] how to do it ?

![image](https://user-images.githubusercontent.com/4869158/38239879-96ce35a2-3760-11e8-8e04-9903f81b7c64.png)

**Comment by Kosvor2** [comment]
Doubt there is dedicated node for that, so here script for exec node for now:
![filter_list2764](https://user-images.githubusercontent.com/22656834/38242492-60f829ea-374e-11e8-812a-ee4979aa796d.png)

**Comment by Durman** [comment]
Also there is `list modifier` node:
![2018-04-03_13-54-37](https://user-images.githubusercontent.com/28003269/38242927-150dce7e-3747-11e8-9b19-88ba0268604b.png)
