### ISSUE TITLE
Export to gist button - error

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2188]
## Problem statement

There is  error of Export to gis button

## Steps to reproduce

1. just press the button

## Expected result

URL

## Actual result

![2018-04-03_14-03-50](https://user-images.githubusercontent.com/28003269/38243223-dac86606-3747-11e8-864e-4cde535c5472.png)

## Sverchok version

last

**Comment by zeffii** [comment]
confirmed
```python
sending
2018-04-03 12:58:29,608 [INFO] sverchok.utils.sv_IO_panel_operators: HTTP Error 401: Unauthorized
```
my first thought is that github might have added some requirements (like identifiers..) to anonymous gist uploads..

**Comment by zeffii** [comment]
this is an example of the code that should upload..
```python
import os
# import bpy
import json
import sys
from time import gmtime, strftime
from urllib.request import urlopen


def main_upload_function(gist_filename, gist_description, gist_body, show_browser=False):

    gist_post_data = {
        'description': gist_description, 
        'public': True,
        'files': {
            gist_filename: {
                'content': gist_body
            }
        }
    }

    json_post_data = json.dumps(gist_post_data).encode('utf-8')

    def get_gist_url(found_json):
        wfile = json.JSONDecoder()
        wjson = wfile.decode(found_json)
        gist_url = 'https://gist.github.com/' + wjson['id']

        if show_browser:
            import webbrowser
            print(gist_url)
            webbrowser.open(gist_url)

        return gist_url

    def upload_gist():
        print('sending')
        url = 'https://api.github.com/gists'
        json_to_parse = urlopen(url, data=json_post_data)
        
        print('received response from server')
        found_json = json_to_parse.read().decode()
        return get_gist_url(found_json)

    return upload_gist()


try:
    tk = "AAAA\nBBBB\nCCCCCC\n\n"
    n = main_upload_function("parma.txt", "vooodooooo", tk)
    print(n)
except Exception as err:
    sys.stderr.write('ERROR: %s\n' % str(err))
    print("||1|", 'Error on line {}'.format(sys.exc_info()[-1].tb_lineno))
```

**Comment by zeffii** [comment]
something changed in github api.

i might try a few things, and also maybe try to provide an option to link the upload to the github account of a user (optionally for those of us who do have a github user account)

**Comment by zeffii** [comment]
with the requests module...  you need to fill username / password
```python
import requests, json

url = 'https://api.github.com/gists'
username = ""
password = ""
filename = "proof.txt"

content = "aaaa\nbbbbb\ncccccc"
data = {'files': {filename: {"content":content}}}

r = requests.post(url, json.dumps(data), auth=requests.auth.HTTPBasicAuth(username, password)) 
print(r.json()['html_url'])
```

**Comment by zeffii** [comment]
welll.. welll...wellllll..

https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by zeffii** [comment]
i don't know about the process of acquiring an app token for Sverchok for gist uploads.. and how we would keep such a token private in an opensource project.  (research needed)

failing that, the gist export feature will be (out of necessity) disabled for Sverchok users who don't provide credentials. Credentials would be either via a system cert ( OAuth) ..or another means.

**Comment by zeffii** [comment]
now... what i might do initially is get people to make a file called "sv_fx.wad" in datafiles/sverchok , and inside it you paste the result of 
```python
import base64
arp = '%s:%s' % ("your username", "your password")
b43 = base64.b64encode(arp.encode()).decode('utf-8')
print(b43)
```
in this case `eW91ciB1c2VybmFtZTp5b3VyIHBhc3N3b3Jk`

i don't want to make this too complicated..

**Comment by zeffii** [comment]
yeah. neither way is ideal. Storing it in a form that can be so easily decoded just blows.. i've not had much time to read about other means of authentication (Token). Also.. this forces people to have a git account which is a bit of a downer.

https://github.com/nortikin/sverchok/pull/2197   (exceptions not handled everywhere, in _presets_ the main upload is also called..)

**Comment by Durman** [comment]
Can I save gist file on my computer and download gist file through web interface on Github somehow?

**Comment by zeffii** [comment]
- saving as json should work fine ( use the big Export button ) 
- downloading should also still work... unless they changed that too.

**Comment by zeffii** [comment]
@Durman  for example; your own gist upload still works.. https://gist.github.com/b21c411afde560cf99c5b2f2589ad3c8

maybe i should just push the wad-reader branch with a description... i've been busy for a couple of weeks now. will look later and tidy/push it.

**Comment by zeffii** [comment]
my only concern is that storing passwords with username that way is a terrible solution. i forgot how much i don't like that.

**Comment by zeffii** [comment]
for now i'm going to push a UI change that hides the upload. https://github.com/nortikin/sverchok/pull/2197

**Comment by nortikin** [comment]
https://vk.com/sverchok_b3d?w=wall-35076122_9947
created poll
