### ISSUE TITLE
Mesh filter node has wrong output of edges mask

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2191]
## Problem statement

@portnov 
Mesh filter node has wrong output of edges mask

## Steps to reproduce

compare `YesEdges` and `mask` sokets

## Expected result

Mask output should have the same edges as `YesEdges` socket.
May be node makes sorting of edges into itself and this makes output mask wrong.

## Actual result

![2018-04-05_08-22-39](https://user-images.githubusercontent.com/28003269/38347181-f3fbbc0e-38aa-11e8-8094-e087195b9cce.png)

**Comment by Durman** [comment]
Indeed this cylce hase another oder of edges

https://github.com/nortikin/sverchok/blob/49cce4493dd377d3c8bcbb85b52419108dacd7b5/nodes/analyzer/mesh_filter.py#L162-L171

![2018-04-05_13-18-20](https://user-images.githubusercontent.com/28003269/38357839-b841312e-38d4-11e8-89e9-2e712f37b42c.png)

May be `bmesh_from_pydata` function should be checked:
https://github.com/nortikin/sverchok/blob/49cce4493dd377d3c8bcbb85b52419108dacd7b5/utils/sv_bmesh_utils.py#L22-L25

**Comment by Durman** [comment]
Maybe just sort order?
```python
        edg_m = {}

        for e in bm.edges:
            idxs = (e.verts[0].index, e.verts[1].index)
            ok = is_good(e)
            if ok:
                good.append(idxs)
            else:
                bad.append(idxs)
                
            edg_m[tuple(sorted(idxs))] = ok
               
        for edg in edges:
             mask.append(edg_m[tuple(sorted(edg))])

        return [good, bad, mask]
```

**Comment by portnov** [comment]
Most probably this issue has something to do with the problem of edges not being ordered in the bmesh structure. Search for "bmesh edges" in this issue tracker, you'll find the problem description. I will be able to look into this issue deeper at holidays.
