### ISSUE TITLE
Logic manipulations and empty objects.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2198]
## Problem statement

Several questions:
1. `Logic functions` node does not update. It is confusing. ([fixed](https://github.com/nortikin/sverchok/commit/b4f19ad43675e19c317df33ff4a7dcd9752cb2fb))
2. I tried change empty data to other but it turn out that `switch` node does not work with empty objects.

## Steps to reproduce

[untitled_2018_04_11_05_17.zip](https://github.com/nortikin/sverchok/files/1897341/untitled_2018_04_11_05_17.zip)

## Expected result

It would be better to have update of logic functions node when mode is changed.
And I don't see way how to change empty data to other without Python. It looks like switch node have to learn deal with empty objects.

## Actual result

![update logick node](https://user-images.githubusercontent.com/28003269/38597356-3b66de18-3d68-11e8-84f8-cf09b0cbc3b8.gif)
![swithch dose not work with amptys](https://user-images.githubusercontent.com/28003269/38597359-3cbe4f26-3d68-11e8-9c22-9df2e43ecd2d.gif)

**Comment by Durman** [comment]
I have suggestion for fixing this issue. 
@zeffii  What do you think?

```python
            for params in zip(*match_long_repeat([state_lists, A, B])):
                S_obj, A_obj, B_obj = params
                A_empty = len(A_obj) == 0
                B_empty = len(B_obj) == 0
                
                if A_empty and B_empty:
                    data.append([])
                
                elif A_empty:
                    data.append([b for state, b in zip(*match_long_repeat([S_obj,B_obj])) if not bool(state)])
                    
                elif B_empty:
                    data.append([a for state, a in zip(*match_long_repeat([S_obj,A_obj])) if bool(state)])
                
                else:    
                    data.append([[a, b][[1,0][bool(state)]] for state, a, b in zip(*match_long_repeat(params))])
                    
            self.outputs[0].sv_set(data)
```
![fixing](https://user-images.githubusercontent.com/28003269/38617690-b8d774da-3da8-11e8-9280-945190e39a4c.gif)

**Comment by zeffii** [comment]
i'll check later!

**Comment by zeffii** [comment]
_switch node._
i'll agree that the behaviour of the Switch node is perhaps unexpected, but it is at least predictable and knowing what you now know it is understandable.

_logic functions_
ok, this should just update. will fix.

**Comment by zeffii** [comment]
for logic functions node
```diff
    def change_type(self, context):
        nrInputs = 1
        if self.items_ in self.constant:
            nrInputs = 0
        elif self.items_ in self.fx:
            nrInputs = 1
        elif self.items_ in self.fxy or self.items_ in self.fxy2:
            nrInputs = 2

        self.set_inputs(nrInputs)

        if self.items_ in self.fxy2:
            self.inputs[0].prop_name = 'i_x'
            self.inputs[1].prop_name = 'i_y'
        elif self.items_ in self.fxy:
            self.inputs[0].prop_name = 'x'
            self.inputs[1].prop_name = 'y'
        elif self.items_ in self.fx:
            self.inputs[0].prop_name = 'x'

+       self.process()
```
or, maybe just if this happens only for the constants..

```diff
    def change_type(self, context):
        nrInputs = 1
        if self.items_ in self.constant:
            nrInputs = 0
+           self.process()
        elif self.items_ in self.fx:
            nrInputs = 1
        elif self.items_ in self.fxy or self.items_ in self.fxy2:
            nrInputs = 2

        self.set_inputs(nrInputs)

        if self.items_ in self.fxy2:
            self.inputs[0].prop_name = 'i_x'
            self.inputs[1].prop_name = 'i_y'
        elif self.items_ in self.fxy:
            self.inputs[0].prop_name = 'x'
            self.inputs[1].prop_name = 'y'
        elif self.items_ in self.fx:
            self.inputs[0].prop_name = 'x'
```

**Comment by zeffii** [comment]
or in those snippets instead of `self.process()` use `self.process_node(context)` or `updateNode(self, context)` i'm not sure what the difference is anymore.

**Comment by zeffii** [comment]
`change_type` would need to trigger an update. When the node has no inputs, it's necessary to use `updateNode(self, context)` i think..

**Comment by Durman** [comment]
About `switch` node:
I couldn't help noticing that work of `switch` node in `single` mode with empty objects is perfect. I don't see any reason why `multi` mode shouldn't work the same way :/
This will be work good with new `fix empty objects` node that have socket with indication of empty objects. I used it to avoid empty data into `viewer Bmesh` node.
![2018-04-12_12-53-47](https://user-images.githubusercontent.com/28003269/38667010-62e3248a-3e51-11e8-8c53-6619bbdf4bb0.png)

**Comment by zeffii** [comment]
Durman, i suspect that the case of the socket with empty internal lists isn't considered "nominal" input. (and for that reason has weak support in most nodes)

**Comment by Durman** [comment]
Ok, I will try to explain my problem.
I was creating town generator as usual when I faced with the problem. I have two types of blocks in the town. If area of block is big enough I locate houses on it (2). Otherwise I locate grass (1).

![2018-04-12_13-14-48](https://user-images.githubusercontent.com/28003269/38672175-782e8782-3e5e-11e8-957a-f558f384e763.png)
I use `list mask` node for dividing blocks. Sometimes happen that green bloks don't generate at all. In this case dataTrue socket generates empty object.

![2018-04-12_14-39-59](https://user-images.githubusercontent.com/28003269/38672487-6fec7fce-3e5f-11e8-87c9-f07c408028fa.png)
It would be fine to switch off branch of nodes that coming from dataTrue socket, but how can I do this?

**Comment by zeffii** [comment]
yes. i understand.  i also think the problem exists (and is solved) a little earlier in the node tree than you suggest, in the end the BMViewer just expects all valid data.  For example if you use the region extrude node, the input matricies will already give you enough information to apply a mask before hitting the `region extrude` node. Filter out the matrices that are small.

**Comment by Durman** [comment]
I am not quite understand what do you mean. I decided to make more easy example.
[empty object_2018_04_12_12_30.zip](https://github.com/nortikin/sverchok/files/1903086/empty.object_2018_04_12_12_30.zip)
![empty data](https://user-images.githubusercontent.com/28003269/38677277-d707d212-3e6e-11e8-98de-e1528d1456a7.gif)
How we have to make both square red or green without BMesh viewer error?

**Comment by zeffii** [comment]
OK, that example is a bit more serious, thanks. You've probably read the bmviewer process function and appreciate what part of the code is involved in this behaviour. There's a lot of assumptions in there.

there could be a bmviewer mode that would permit a rule like: 
> " for every object (vert + [edges + faces]) , if the sublist of (edges. faces) contains an empty list, then 
just create the object (but give it a tag ID Property) -- or skip this object creation. "

presumably if faces is connected but contains empty lists (all or some), then you don't need the verts to be created either, you don't even need the object.

This becomes tricky to "fix" the node as an afterthought, specifically for this problem. A quick fix would work for this scenario, but could prove unwelcome for other user-cases. Hence i'm going to be slow to suggest anything useful.

**Comment by Durman** [comment]
Ok, but I still disagree that different modes of switch node have different behaviour at least. Even true and false data change places in output socket.

**Comment by zeffii** [comment]
yes, logic switch node should either have a new multi mode, or fix current multi mode.

**Comment by zeffii** [comment]
fixed https://github.com/nortikin/sverchok/pull/2204

**Comment by zeffii** [comment]
this issue unfortunately touches three separate issues (but some partially related)

1. logic functions node behaviour
2. logic switch node behaviour "inconcistency"
3. how viewers behave when we pass partial/incomplete data

1 is resolved, but 2 and 3 are definitely worth thinking about.

2: the logic switch issue is unclear to me what the cleanest solution would be that doesn't break existing blends. I think you could do several things but maybe the most sane is to make a third mode `multi+`, that fixes some obvious issues that `multi` didn't get right.

3: well, that really is a separate issue and should be started separately with the most dumbest example possible.

**Comment by zeffii** [comment]
i'm OK with MK2 for this :)

**Comment by Durman** [comment]
Searching new representation for new version of the node.
I am happy that I managed more or less to sort out with creating interface of nodes.))
![2018-04-27_08-42-25](https://user-images.githubusercontent.com/28003269/39345104-a1018534-49f7-11e8-861a-8da6f5000d06.png)

**Comment by zeffii** [comment]
cool

**Comment by Durman** [comment]
My implementation for generation new sockets with property parameter. I didn't find such example among other nodes.
```Python
def change_sockets(self, context):
        pre_num = (len(self.inputs)-1)//2
        diff = self.socket_number - pre_num
        if diff > 0:
            for i in range(diff):
                num = pre_num + i
                name_A = 'A_{}'.format(num)
                name_B = 'B_{}'.format(num)
                prop_A = EnumProperty(items=self.input_items, name=name_A, default="True", update=updateNode)
                prop_B = EnumProperty(items=self.input_items, name=name_B, default="False", update=updateNode)
                setattr(SvSwitchNodeMK2, name_A, prop_A)
                setattr(SvSwitchNodeMK2, name_B, prop_B)
            
                self.inputs.new("StringsSocket", "").prop_name = name_A
                self.inputs.new("StringsSocket", "").prop_name = name_B
                self.outputs.new("StringsSocket", "Out {}".format(num))
```

**Comment by Durman** [comment]
Interesting thing is that when I reboot Blender generated properties get lost somewhere. :/

![loose prop](https://user-images.githubusercontent.com/28003269/39577145-8a1c06a6-4ef1-11e8-9617-c21e83b6ea5e.gif)

**Comment by zeffii** [comment]
show all node source

**Comment by Durman** [comment]
```Python
import bpy
from bpy.props import IntProperty, StringProperty, BoolProperty, EnumProperty

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import get_other_socket, updateNode, match_long_repeat, changable_sockets


class SvSwitchNodeMK2(bpy.types.Node, SverchCustomTreeNode):
    """
    Triggers: Switch MK2
    Tooltip: This version is more clever of previous one
    
    You can deal with empty data connected to input sockets (True or False)
    """
    bl_idname = 'SvSwitchNodeMK2'
    bl_label = 'Switch mk2'
    bl_icon = 'ACTION_TWEAK'
    
    input_items = [
            ("True", "True", "", 0),
            ("False", "False", "", 1),
            ("None", "None", "", 2)
        ]
    
    def change_sockets(self, context):
        pre_num = (len(self.inputs)-1)//2
        diff = int(self.socket_number - pre_num)
        if diff > 0:
            for i in range(diff):
                num = pre_num + i
                name_A = 'A_{}'.format(num)
                name_B = 'B_{}'.format(num)
                prop_A = EnumProperty(items=self.input_items, name=name_A, default="True", update=updateNode)
                prop_B = EnumProperty(items=self.input_items, name=name_B, default="False", update=updateNode)
                setattr(SvSwitchNodeMK2, name_A, prop_A)
                setattr(SvSwitchNodeMK2, name_B, prop_B)
            
                self.inputs.new("StringsSocket", "").prop_name = name_A
                self.inputs.new("StringsSocket", "").prop_name = name_B
                self.outputs.new("StringsSocket", "Out_{}".format(num))
            
        elif diff < 0:
            for i in range(abs(diff)):
                self.inputs.remove(self.inputs[-1])
                self.inputs.remove(self.inputs[-1])
                self.outputs.remove(self.outputs[-1])
            
    switch_state  = EnumProperty(items=input_items[:2], name="state", default="False", update=updateNode)
    socket_number = IntProperty(name="count", min=1, max=10, default=1, update=change_sockets)
    input_A   = EnumProperty(items=input_items, name="A_0", default="True", update=updateNode)
    input_B   = EnumProperty(items=input_items, name="B_0", default="False", update=updateNode)
    
    def sv_init(self, context):        
        self.inputs.new("StringsSocket", "State").prop_name = 'switch_state'
        self.inputs.new("StringsSocket", "A 0").prop_name   = 'input_A'
        self.inputs.new("StringsSocket", "B 0").prop_name   = 'input_B'
        self.outputs.new("StringsSocket", "Out_0")        
    
    def draw_buttons_ext(self, context, layout):
        layout.prop(self, 'socket_number', text="in/out number")
        
    def rclick_menu(self, context, layout):
        layout.prop(self, 'socket_number', text="in/out number")
        
    def process(self):
        pass
        
def register():
    bpy.utils.register_class(SvSwitchNodeMK2)

def unregister():
    bpy.utils.unregister_class(SvSwitchNodeMK2)
```

**Comment by zeffii** [comment]
you can only initialize an `EnumProperty` in the class body. In change_socket you do the equivalent of generating an EnumProperty "at run time" this is not allowed in bpy/pynodes in this way. 

Look at other nodes that dynamically add sockets. This means you might be forced to initialize all 10 enumproperties in the class body, and only assign them in change_socket when they are needed.

**Comment by zeffii** [comment]
you will need to reformulate the change_socket function, and include a check in the process function to check if the number of sockets currently on the node ( it might be 2...or 6...) matches the expected number of sockets. (again, see other nodes that have dynamically added sockets..)  in process you would do nothing if the num sockets is correct, and populate the sockets if not.

**Comment by zeffii** [comment]
you are perfectly capable of doing this so i'll avoid coding it. if after struggles you still don't succeed please reach out again :)

**Comment by Durman** [comment]
@zeffii 
Thank you. Your advices have helped me.) I have done attributes generation in body of the class thus:

```Python
class SvSwitchNodeMK2(bpy.types.Node, SverchCustomTreeNode):
    #............

    switch_state  = EnumProperty(items=input_items[:2], name="state", default="False", update=updateNode)
    socket_number = IntProperty(name="count", min=1, max=10, default=1, update=change_sockets)
        
    for i in range(10):
        name_A = 'A_{}'.format(i)
        name_B = 'B_{}'.format(i)
        locals()[name_A] = EnumProperty(items=input_items, name=name_A, default="True", update=updateNode)
        locals()[name_B] = EnumProperty(items=input_items, name=name_B, default="False", update=updateNode)
```

**Comment by zeffii** [comment]
yep! cool

**Comment by Durman** [comment]
![example](https://user-images.githubusercontent.com/28003269/39796222-4e31fd48-5366-11e8-8d7b-0153bc088607.gif)
![2018-05-09_08-50-26](https://user-images.githubusercontent.com/28003269/39796224-5086d078-5366-11e8-8939-8190278b9cc5.png)
