### ISSUE TITLE
Mathutils.Matrix instead of what we have now.

### ISSUE THREAD

**Issue by Kosvor2** [nortikin/sverchok#2199]
https://github.com/nortikin/sverchok/tree/Mathutils_Matrix_test

Currently many nodes create them internally. Other nodes also convert them back to Sverchok matrices for output. Maybe better to use them always? 8 out of 10 nodes will have to do less computations because of that. Branch is ready for testing.

**Comment by Durman** [comment]
I tested it looks normal.

**Comment by Kosvor2** [comment]
My main concern- socket conversions (from matrix to vector for example), i tried to fix it but nestines most likely wrong now.

And also there this strange thing: https://github.com/nortikin/sverchok/commit/0e91045003fab73735aa5a0272ede2537a67a3dc

**Comment by Kosvor2** [comment]
I propose to make new release for users (last one with old matrices). After that merge everyting to master and start debugging from there.

**Comment by zeffii** [comment]
I don't mind the switch, but I have problems with the method of making the switch.

Use a development branch, and debug in that (and keep in sync with master). once you are confident that it works, then you merge into master. I get the impression that you wanted to merge before a comprehensive testing effort. Merging early gives me no confidence.

would be a great opportunity to start a new socket type `SvMathutilsMatrixSocket`. and gradually phase out  the old one. by first relying on implicit_conversion between `SvMathutilsMatrixSocket <-> MatrixSocket`.

@portnov a voice of sanity please? :)

**Comment by portnov** [comment]
I totally agree with @zeffii  on this :)

While using mathutils.Matrix everywhere can give us more performance, it may also give us also a ton of compatibility headache. There potentially is a lot of scripts or nodes, that assume they always work with lists.

**Comment by Kosvor2** [comment]
Creating new socket types is not my style. And `old_nodes` is pretty full already. Does anyone really want to do it this way?

**Comment by zeffii** [comment]
because the number of matrices will generally be low in most data transferred out / in to nodes, I would be surprised if the overhead was noticeable, this also makes me want to resist this. It's also a big change so the inertia should be noticable.

**Comment by Kosvor2** [comment]
merged https://github.com/nortikin/sverchok/pull/2193, https://github.com/nortikin/sverchok/pull/1949, and https://github.com/nortikin/sverchok/pull/1818 into https://github.com/nortikin/sverchok/tree/Mathutils_Matrix_test
