### ISSUE TITLE
is it possible to disable ctrl+space in other node editor?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#2209]
i'm using sverchok and animation node.
sometimes i'll add sverchok's node in animation node editor by accident, then animation node will freeze.
if some one can disable ctrl+space hotkey in other node editor, i'll be appreciated.
thanks for reply,

stan

**Comment by zeffii** [comment]
yes, the poll function of that menu will need to be a bit more precise :)

**Comment by zeffii** [comment]
this is the operator called by ctrl+space

https://github.com/nortikin/sverchok/blob/5cd48f56591b329537f8e6aca935bafcff04fff2/utils/sv_extra_search.py#L124-L131

it needs an explicit poll like the shift+a menu has..

https://github.com/nortikin/sverchok/blob/7488fe39814591ebbb1f0fc6619f8bd1fc5ca8e5/ui/nodeview_space_menu.py#L88-L95

will do asap. thanks for reporting this. @stansu

**Comment by zeffii** [comment]
done https://github.com/nortikin/sverchok/pull/2210
