### ISSUE TITLE
When rendering BMesh Viewer object is not updating correctly

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2214]
I have to give example with simple Blend, but seems like when rendering, I could not get mesh generated to show up.

I tried Pre and Post update, but it does not work. Is there a force button to ensure that SV always update before rendering?

**Comment by zeffii** [comment]
post a blend anyway. even if its stupid simple. (preferably stupid simple)

https://github.com/nortikin/sverchok/blob/master/core/handlers.py

**Comment by zeffii** [comment]
we indeed don't have a listener for the [`render_pre`](https://docs.blender.org/api/blender_python_api_current/bpy.app.handlers.html#bpy.app.handlers.render_pre) handler,  yet.   but i recall giving you a snippet a long time ago that would trigger an explicit update to the sverchok nodetree pre render.. maybe you can find it.

**Comment by enzyme69** [comment]
@zeffii It's with this FLIP Fluid Add-On, so I can't exactly explain it unless you all go the add-on.

But basically, FLIP fluid will produce some kind of 3D mesh. And I could not transform the mesh so easily, but I am using Sverchok to do the offset transformation so that if I have the fluid sims from Blend A, I can easily transform the resulting mesh in Blend B using Sverchok.

I figure it out, so when rendering happens, the FLUID somewhat has this weird -1, -1, -1 offset and so that's why when I render, it seems like Sverchok mesh disappear, but in fact it was somewhere else.

The solution is that in Sverchok, I invert the -1,-1,-1.

Sometimes between scene pre and post render, something happen without user knowledge :)

![prtscr capture_4](https://user-images.githubusercontent.com/3952687/39624108-6cbcf3d2-4fdb-11e8-8e7d-56bc85e817f2.png)
![prtscr capture_3](https://user-images.githubusercontent.com/3952687/39624109-6ceb4fca-4fdb-11e8-9c1b-747653119ed3.png)
![prtscr capture](https://user-images.githubusercontent.com/3952687/39624110-6d1f8cc2-4fdb-11e8-8d78-50659143e862.png)

I guess, it's not SV bug, wrong alarm.

Thanks for looking into this.
