### ISSUE TITLE
Viewer Draw node does not bake with input some matrix any more.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2215]
## Problem statement

 Viewer Draw node can't bake mesh if it has some input matrix.

## Steps to reproduce

![2018-05-10_13-06-17](https://user-images.githubusercontent.com/28003269/39861894-21ad0676-5453-11e8-8282-87f249e03f5f.png)

## Expected result

Baked mesh

## Actual result

![2018-05-10_13-08-26](https://user-images.githubusercontent.com/28003269/39861921-3874de7e-5453-11e8-8c32-7a5bb53224bf.png)

**Comment by Kosvor2** [comment]
I will look

**Comment by Kosvor2** [comment]
Fixed: https://github.com/nortikin/sverchok/blob/master/nodes/viz/viewer_mk2.py

**Comment by Kosvor2** [comment]
Honestly, it would be better to just remove autocorrect() from its matrices. https://github.com/nortikin/sverchok/pull/2216

**Comment by Durman** [comment]
It is interesting that it is possible to create nested list of matrix now but no one node does not expect this and does not work. I think the `switch mk2` node will be first who will manage.))

![nested matrix](https://user-images.githubusercontent.com/28003269/39877854-04d9edae-5488-11e8-9631-8883f7f7a745.gif)

**Comment by nortikin** [comment]
we need some rewrite correct list levels def
