### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'get_shorthand'

### ISSUE THREAD

**Issue by Mohammad-Aliraqi** [nortikin/sverchok#2219]
## Problem statement

I get the following error when I try to use the generic search in Sverchok node editor

```Shell
Traceback (most recent call last):
  File "/PortableApps/Installed/PortableApps/BlenderPortable/App/Blender64/2.79/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 165, in invoke
    loop['results'] = gather_items()
  File "/PortableApps/Installed/PortableApps/BlenderPortable/App/Blender64/2.79/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 108, in gather_items
    fx.append((str(idx), ensure_valid_show_string(item), '', idx))
  File "/PortableApps/Installed/PortableApps/BlenderPortable/App/Blender64/2.79/scripts/addons/sverchok-master/utils/sv_extra_search.py", line 66, in ensure_valid_show_string
    description = nodetype.bl_rna.get_shorthand()
AttributeError: 'Node' object has no attribute 'get_shorthand'
```

I am using Blender v2.79b (Portable version from [PortableApps](https://portableapps.com/apps/graphics_pictures/blender_portable))

## Steps to reproduce

I am getting the error whenever I do the following:

1. Open Blender (the version mentioned above).
2. Make sure you have the latest Sverchok version installed. If not, click on Sverchok button "Check for updates" and if it turned red click on it once more, wait till the install finishes and then restart Blender.
3. Go to Node editor and create a new Sverchok node tree.
4. In the node editor of Sverchok, press SHIFT+A (or right click to display the menu).
5. Click on "Search" from the menu.

## Expected result

I should be able to perform search without any errors

## Actual result

I get the above error and the search is not possible, please refer to the attached snapshot

## Sverchok version

I am currently using Sverchok version 0.5.9.6 (c548444). Please note that I am updating Sverchok all the time using its builtin functionality (clicking on "Check for updates" button and click it once more if it turned red in the first time and after it finishes installing I restart Blender)

![image](https://user-images.githubusercontent.com/39595162/40496453-0f694e52-5f7a-11e8-8658-14f039f3f2ae.png)

**Comment by zeffii** [comment]
i cannot reproduce.

**Comment by zeffii** [comment]
usual suggestion here is to try removing sverchok entirely from your scripts / addons folders and installing it fresh, and then update.

**Comment by zeffii** [comment]
before doing that, you should start Blender from a terminal and look for any other print outs that Sverchok/blender might be pumping out. Sometimes the last error is the only visible notification of an error, while the root cause can be a problem elsewhere.

```
2018-05-24 23:04:10,935 [INFO] sverchok.utils.logging: Registering Sverchok addon. Messages issued during registration will be only available in the console and in file (if configured).
** version:  0.5.9.6, branch master, commit c5484445  **
** Have a nice day with sverchok  **

 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
loading default dict..

** Sverchok loaded with 283 nodes **


```

**Comment by Mohammad-Aliraqi** [comment]
Thanks @zeffii , it seems to work now after removal and re-installing fresh from the releases in github. Not sure what was the cause of the issue though

Wish you the best

**Comment by zeffii** [comment]
@Mohammad-Aliraqi  OK, thanks for the report anyway. Someone else might also encounter this, now it is logged here with a solution :)
