### ISSUE TITLE
Fuzzy Search for generic data?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2220]
Object ID Filter can filter Objects in Blender scene by name, etc.

I wonder if Sverchok can perform "fuzzy search" on list of data that user provided? 

In this case, I am dealing with some list of data, just names like 'mouthOpen', 'mouthClosed', 'eyesBlink' and kind of wanted to be able to filter those by just specifying 'mouth' or something. This way I can filter out 'mouth_open', 'openMouth', etc. 

Any suggestion?

<img width="1029" alt="screen shot 2018-05-29 at 12 09 54 pm" src="https://user-images.githubusercontent.com/3952687/40634615-43a4c03a-6339-11e8-92c0-b17c2ce7974c.png">

**Comment by Durman** [comment]
looks like it's working

![2018-05-29_08-14-48](https://user-images.githubusercontent.com/28003269/40637821-7d4f1d38-6318-11e8-8b97-250bb207c71d.png)

**Comment by enzyme69** [comment]
Ah, yes, that Object ID filtering name is working fine.

I mean I am curious on how you implement SV fuzzy search on node for example:
<img width="288" alt="screen shot 2018-05-29 at 6 49 05 pm" src="https://user-images.githubusercontent.com/3952687/40648137-fb399900-6370-11e8-995e-e7b3a8569700.png">

For objects it works:
<img width="690" alt="screen shot 2018-05-29 at 6 48 42 pm" src="https://user-images.githubusercontent.com/3952687/40648170-13002702-6371-11e8-8193-7186d3cb2aab.png">

But I am wondering if I have big list of text string data, maybe if SV has fuzzy search implementation or it could be created easily using Script Node and Python? --> maybe I should research on this?

**Comment by Durman** [comment]
like this?

![2018-05-29_14-02-24](https://user-images.githubusercontent.com/28003269/40652377-241d3eb2-6349-11e8-993f-5b50dd5ff146.png)

**Comment by enzyme69** [comment]
That might be it! Thank~ will try
