### ISSUE TITLE
Override context of operators

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2221]
I am thinking how to unwrap meshes in sverchok and using existing operators (bpy.ops.uv....) looks easy to implement. But for this purpose context should be override.

[API - override context](https://docs.blender.org/api/blender_python_api_current/bpy.ops.html#overriding-context)

I learned that different operators require different context. For example: 

```Python
import bpy
override = bpy.context.copy()
override['selected_bases'] = list(bpy.context.scene.object_bases)
bpy.ops.object.delete(override)
```
Objects are being deleted normally. But if I change operator on bpy.ops.uv.smart_project() it does not work.
[Here](https://blender.stackexchange.com/questions/8983/python-apply-object-operator-to-dupli-objects) I found some information about the issue, ideasman42 was writing:

> You can find out which attributes are used by passing in a Python context, and then check the terminal for where each requested attribute is printed.

I did not figure out yet what did he mean and how to do it.))

**Comment by Durman** [comment]
[Here](https://blender.stackexchange.com/questions/6101/poll-failed-context-incorrect-example-bpy-ops-view3d-background-image-add/6105#6105) I found a clue what I have to do to override context of the operator.

As it turned out it is good idea to look downright at a [code of the operator](https://developer.blender.org/diffusion/B/browse/master/release/scripts/startup/bl_operators/uvcalc_smart_project.py).

So what I had to do was:
```Python
override = {"active_object":bpy.data.objects['Plane'],
            "selected_editable_objects": [bpy.data.objects['Plane']]}

bpy.ops.uv.smart_project(override)
```

**Comment by nortikin** [comment]
passing python context. there was addon for check context
if something, i have one my own
https://github.com/nortikin/nikitron_tools/blob/master/context_printer.py
