### ISSUE TITLE
Fastest way to flip U and V of Cylinder?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2222]
[cylinder_flip_uv_001.blend.zip](https://github.com/nortikin/sverchok/files/2060797/cylinder_flip_uv_001.blend.zip)

Just wondering what is the fastest way to flip U and V polygon index of Cylinder to match the Ring? I remember having similar thing in the past... cannot remember the solution.

<img width="736" alt="screen shot 2018-06-01 at 12 38 00 pm" src="https://user-images.githubusercontent.com/3952687/40818109-ea9e92ce-6598-11e8-9c65-5a21490afe25.png">

If I am using the UV Connection and Cyclic, the face index is a bit strange at the closing part.

<img width="349" alt="screen shot 2018-06-01 at 12 40 45 pm" src="https://user-images.githubusercontent.com/3952687/40818133-0aeec1f2-6599-11e8-8703-46884bc01cdf.png">

Cylinder Flat vs Ring Index UV order.
<img width="1002" alt="screen shot 2018-06-01 at 12 42 36 pm" src="https://user-images.githubusercontent.com/3952687/40818185-4697e292-6599-11e8-9543-c54020aaf30b.png">

**Comment by Durman** [comment]
I think there are a lot of ways to do this. For example so:

![2018-06-01_08-35-05](https://user-images.githubusercontent.com/28003269/40821339-586a28f8-6577-11e8-9a24-bb338e8c0f33.png)

You can create your own rings generator like [here](https://plus.google.com/u/0/photos/photo/112901248458436952300/6511546234524447986?sqid=113245231013159497850&ssid=f46940c3-ccfd-4aa8-bd99-293760850995)

Also it is possible reorder order of polygons as you like:
[reoder UV_conection out of polygons_2018_06_01_04_42.zip](https://github.com/nortikin/sverchok/files/2061014/reoder.UV_conection.out.of.polygons_2018_06_01_04_42.zip)
![2018-06-01_08-44-48](https://user-images.githubusercontent.com/28003269/40821436-1362ee10-6578-11e8-85b3-7dd939208700.png)

**Comment by enzyme69** [comment]
INTERESTING! I'll keep this for future usage~ Cheers @Durman

**Comment by enzyme69** [comment]
@nortikin Still I am wondering on why UV Connection, when closing the gap does not have the "nice UV ordering"?


https://github.com/enzyme69/blendersushi/issues/398

**Comment by Durman** [comment]
Just more one idea: ))

![2018-06-02_08-34-12](https://user-images.githubusercontent.com/28003269/40870417-d7240ede-663f-11e8-8098-4dbd78299cdd.png)

**Comment by enzyme69** [comment]
That's seriously cool actually! I have not touched the Set UV Map node.

**Comment by Durman** [comment]
It is very experimental node far from release and even it is not clear the approach is good or not. 

I am thinking about running with materials and uv maps via Sverchok but it's looks like brand new approach to deal with objects. I have got three nodes: set material, set UV map, UV mapping node and a lot of troubles with all of them.)) 

If you want you can test `set UV map` node for this you have to download a branch from [here](https://github.com/nortikin/sverchok/pull/2218).

**Comment by nortikin** [comment]
UVconnect will be rewritten asap, there are many issues. but also many issues in all the nodes. UVconnect can deal with not only bottom level. Every modifier should deal with user defined level.
meanwhile i made SNL
commited to master now https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/flip_polygons.py

**Comment by Durman** [comment]
@nortikin I can't figure out a profit of  this node. Could you give whatever example of using?

**Comment by nortikin** [comment]
@Durman not now
use only polygons socket and U subdivisions, that needed to match
It will flip polygons
