### ISSUE TITLE
Sverchok crash with certain node setup

### ISSUE THREAD

**Issue by 0xD34DC0DE** [nortikin/sverchok#2223]
## Problem statement

Sverchok crashes blender with a specific node setup

## Steps to reproduce

1. Create a new scene
2. replicate the node tree like in the screenshot below
![screenshot 7](https://user-images.githubusercontent.com/31230799/40897045-b6a1721c-6786-11e8-903a-24e93b1b287f.png)
3. change the Vector math node from Reflect to dot product

## Expected result

Correct math calculation

## Actual result

Blender crash

## Sverchok version

got the latest release of blender 2.79
Sverchok version 0.5.9.6
installed from zip file

**Comment by Durman** [comment]
I have confirmed the bug at home computer, it's looks like this occurs with Blender 2.79 only. 

However it's not critical error because there is no point to connect vector math node in dot product mode with input vector socket. Look [here](https://en.wikipedia.org/wiki/Dot_product) what dot product means.

But ofcourse it's not desirable behavior. :/

**Comment by unwave** [comment]
My speed run guide:
![speedrun](https://user-images.githubusercontent.com/39925416/40937389-21e27cb8-6847-11e8-9f4b-8dc22bbb9cbe.gif)

**Comment by Durman** [comment]
@unwave 
It's okay in my case but moving of the node tree space become harder I wish I knew why. ))

![range](https://user-images.githubusercontent.com/28003269/40955366-adf59868-689a-11e8-9e15-17483cfc49aa.gif)

You can see here that step can't be equal zero but 1e-5 is also fairly small number. Maybe it should be increase. :/

https://github.com/nortikin/sverchok/blob/52d12d264fde789192b46814647e7fc8a34c1041/nodes/number/range_float.py#L26-L39

**Comment by Durman** [comment]
```
2018-06-06 06:40:36,167 [ERROR] sverchok.core.update_system: Node Vector Math had exception: Vector.project(other), inva
lid 'other' arg: sequence index 511 expected a number, found 'list' type,
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.
py", line 325, in do_update_general
    node.process()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\vector\math_m
k2.py", line 165, in process
    result = recurse_fxy(input_one, input_two, func, level)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\vector\math_m
k2.py", line 83, in recurse_fxy
    res_append(f(u, v))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\vector\math_m
k2.py", line 44, in <lambda>
    "PROJECT":        (13, lambda u, v: Vector(u).project(v)[:],                   ('vv v'),            "Project"),
TypeError: Vector.project(other), invalid 'other' arg: sequence index 511 expected a number, found 'list' type,
```

**Comment by nortikin** [comment]
@Durman it is list instead of number. vector math expects standart level of data for now, sadly

**Comment by nortikin** [comment]
maybe for the range float to limit minimum ratio of step-length?

**Comment by Durman** [comment]
@nortikin 
The question is why Blender crashes. It's looks like this happens if put in Vector big list of numbers and it's fair for 2.79 version only. I will examine this theory at home.))

![2018-06-06_13-04-52](https://user-images.githubusercontent.com/28003269/41028484-9620730c-698a-11e8-9ca7-f4f6957779e6.png)

**Comment by Durman** [comment]
It turned out that it is possible to create Vector any length. :/

```
>>> Vector(list(range(10)))
Vector((0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0))
```

![mathutils bug](https://user-images.githubusercontent.com/28003269/41078467-06971f70-6a2e-11e8-8bb5-869c2558cbb4.gif)

**Comment by zeffii** [comment]
That should be a bug report to blender then

**Comment by Durman** [comment]
I'v done this [here](https://developer.blender.org/T55374)

**Comment by zeffii** [comment]
if there are serious issues that are not yet solved, please open a fresh issue for any subsequent unique/unrelated issue. Please one issue per "thread".
