### ISSUE TITLE
migration to GITLAB

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#2224]
## Problem statement

Microsoft is acquiring GitHub!

## Steps to reproduce

1. development
2. development
3. development

## Expected result

not buy

## Actual result

they grab last part of freedom

## Sverchok version

DO WE NEED TO MIGRATE GITLAB?
lets vote.

P.S.
started migration, but sverchok seems to be large enough to hang long time + it showing an error.

**Comment by unwave** [comment]
What are the direct reasons of the migration? MS's corporate oppression which has not taken place yet?

**Comment by nortikin** [comment]
this agreement accured half a year ago, but only now promoted in media and site. This time they limited access to gists. So we cannot push jsons trees from sverchok on Internet with no pain.
So, i see in future the same as Nokia - killing opensource projects by activly pushing forward MS products instead.
They use git against opensource, against itself. Much of smart approach. MS loves OpenSource is lie.
http://www.askaswiss.com/2018/06/top-5-free-github-alternatives-in-2018.html

**Comment by Durman** [comment]
I'm afraid that migration can slow down developing of Sverchok. If we can migrate in any time would it be better to wait serious reason from GItHub to do this?

**Comment by nortikin** [comment]
https://gitlab.com/nikitron/sverchok
all issues automerged

**Comment by zeffii** [comment]
gitlab is hosted on Azure. maybe it's time to make a peerGit page with the `::dat` protocol..
