### ISSUE TITLE
Create profile from selection

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2231]
## Problem statement

`Profile parametric` node can't create profile from selected curve.

## Steps to reproduce

1. Convert plane to curve in a scene
2. Press `from selection` button on a `profile parametric` node
3. See a result

## Expected result

No errors at least

## Actual result

```Python
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\ad
dons\sverchok-master\nodes\generators_extended\profile_mk2.py", line 631, in exe
cute
    if ob_points[0].handle_left_type in types or ob_points[-1].handle_right_type
 in types:
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/45b57d17b908f76bf0a2e338d2a6af3c88ea3e58/nodes/generators_extended/profile_mk2.py#L538

I think what happens here is that the "convert to curve" operator that you use on the Plane to generate the Curve initially, will generate a Curve of type X. The sverchok "profile from selection" operator isn't generalized enough to handle all types of curves. We could add better curve-type checking and print a more informative message..

**Comment by Durman** [comment]
Yes it would be not bad to give this information in `info` panel for example. Also there is a point to add information into help file that this button works with Bezier type curve only. 

It is possible to convert polyline into Bezier, I didn't know:
https://docs.blender.org/manual/en/dev/modeling/curves/editing/introduction.html#set-spline-type

But if I create standard Bezier curve and press `from selection` button Sverchok gives me next error message:
```Python
error on line CurveTo:  (-0.5+a),(0.5+a) (0.0+a),(0.0+a) (1.0+a),(0.0+a) 20 0 # expression (#+a) added because
2018-06-19 08:43:27,500 [ERROR] sverchok.core.update_system: Node Profile Parametric had exception: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\core\update_system.py", line 325, in do_update_general
    node.process()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\generators_extended\profile_mk2.py", line 895, in process
    vertices, edges = path_object.get_geometry()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\generators_extended\profile_mk2.py", line 177, in get_geometry
    self.sanitize_edgekeys(final_verts, final_edges)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sverchok-master\nodes\generators_extended\profile_mk2.py", line 131, in sanitize_edgekeys
    if len(final_verts) in final_edges[-1]:
IndexError: list index out of range
```

**Comment by zeffii** [comment]
- in the case of POLY (polyline) i'll add notification to `info` , but not the manual yet.
    - it should be relatively easy (but maybe time consuming) to write a short path converter for POLY
- as for standard bezier curves, i wasn't aware that was broken.
   - the operator seems to not expect single segment beziers ( @nortikin  )

**Comment by zeffii** [comment]
i've added warning / cancel operation when the operator encounters of a `spline.type == 'POLY'`

**Comment by Durman** [comment]
I this case it would be great to have the same message and about NURBS curves too. ))

**Comment by Durman** [comment]
Also the node has got more nestedness for edges output than usual. Was this done in purpose?

![2018-06-21_13-08-49](https://user-images.githubusercontent.com/28003269/41709475-48383582-7554-11e8-819b-adf0af370be8.png)

**Comment by zeffii** [comment]
it's tricky to answer that, i'll try to refresh my memory..as some of the early history of the node seems to be lost..

the nestedness might be a bug, but it might also be intended to allow the socket to output several disjoints edge nets related to one pair of vertices. A profile can have several "islands". Whether this is intentional i can't remember, but it would make sense. Whether this is desired nestedness by default is debatable and i'm (predictably) undecided whether it's a good idea.

You may have to sift through the issue tracker for discussion about the edge keys, i'd be disappointed if it remained unmentioned in the source at the very least.
