### ISSUE TITLE
It is possible to  create a crosssection from 2 meshes?

### ISSUE THREAD

**Issue by victorcalixto** [nortikin/sverchok#2237]
Hey Guys, Im stuck in that problem that i cant solve. It is possible to create a crosssection from 2 meshes? I cant use crosssection node because it just work with planes that are infinite in all directions causing extra intersections.

![sverchok](https://user-images.githubusercontent.com/4661824/41813989-c1705154-7717-11e8-8d57-254cccb602af.png)

Could anyone help me in this task?

**Comment by Durman** [comment]
Hello, we can use standard Blender boolean modifier. Look at the file how I've done this.
[crosssection from 2 meshes_2018_06_24_03_53.zip](https://github.com/nortikin/sverchok/files/2130447/crosssection.from.2.meshes_2018_06_24_03_53.zip)
![2018-06-24_07-57-08](https://user-images.githubusercontent.com/28003269/41815721-39b88b56-7784-11e8-8f6b-3afdf180f571.png)

**Comment by victorcalixto** [comment]
Thanks for your answer Durman, and sorry about my miss here in the forum. I was overload of work.

**Comment by Durman** [comment]
I hope the answer was useful. I will close issue if you have not another.
