### ISSUE TITLE
Vector polar output

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2238]
## Problem statement

Little problem with `vector polar output`.

## Steps to reproduce

- Connect `Z`/`theta` socket. 
- Switch `Cylinder`/`Sphere` modes. 
- Do the same with disconnected `Z`/`theta` socket.

## Expected result

`Z` and `theta` sockets should replace each other when `cylinder` and `sphere` modes are being changed.

## Actual result

In `sphere` mode `Z` socket cannot give any value.

![vector polar output](https://user-images.githubusercontent.com/28003269/41966259-b4a6c52a-7a0f-11e8-94b4-519b368f1ff2.gif)

**Comment by Durman** [comment]
It looks like the socket cannot be hidden if it has a connection.

https://github.com/nortikin/sverchok/blob/f053deb6bb1024667c610ee2d02e5d88718b7754/nodes/vector/vector_polar_out.py#L56-L59

**Comment by zeffii** [comment]
i added a method last year called `socket.safe_hide` or `.safe_hide`, nodes that don't use this will behave the way you show.
