### ISSUE TITLE
Socket for number of loops of monad node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2240]
I am thinking about serial editing like on the picture below, but input can have different number of matrix. It would be nice to have socket for `quantity of loops`, is it hard to do?

![serial editing](https://user-images.githubusercontent.com/28003269/42199687-e834c992-7ea0-11e8-86d5-97d1b6a20b54.gif)

**Comment by zeffii** [comment]
yeah..i don't know about that in the current configuration of Monad. I'll think about it, how it might be possible with the least amount of code. Worst case scenario you can use a SNLite and reference the N and the N limit properties of the monad node ( N is limited by the user defined limit value..to avoid likely super long calculation times.. )

..will need to think about.

**Comment by zeffii** [comment]
the code that handles this is here:

https://github.com/nortikin/sverchok/blob/c98364dcf3d0c36860b93a74789a92bd46f6ca20/core/monad.py#L540-L558

a minor change would allow the monad to count the size of data in the first socket, and use that as the iteration count. it would be a single tickbox in draw_buttons_ext.. a new boolean property `self.determine_first_socket_size`

```python
 def process_looped(self, iterations_remaining): 
     sockets_in = [i.sv_get() for i in self.inputs] 
  
     if self.determine_first_socket_size:
        iterations_remaining = len(sockets_in[0])  # first socket important..

     monad = self.monad 
     monad['current_total'] = iterations_remaining
     monad['current_index'] = 0 
  
     in_node = monad.input_node 
     out_node = monad.output_node 
  
     for iteration in range(iterations_remaining): 
         if 'Monad Info' in monad.nodes: 
             # info_node = monad.nodes['Monad Info'] 
             # info_node.outputs[0].sv_set([[iteration]]) 
             monad["current_index"] = iteration 
  
         sockets_in = self.do_process(sockets_in) 
     self.apply_output(sockets_in) 

```

**Comment by zeffii** [comment]
@Durman do you still feel you want this?  now would be the time to talk about this again.

**Comment by Durman** [comment]
It of course would be interesting to have this functionality but I think there are loads of thing with higher priority that we and especially you ))) have to do.

**Comment by zeffii** [comment]
I haven't even tried monads in 2.8 yet.  0_0

the main issue is thinking of what mechanism would be acceptable..  maybe a config socket that only processes if it has
```python
 {
    'num_iterations': ...,
    'max_iterations': ...
}

# or a list of length 1. with 2 elements.

[[num_iterations, max_iterations]]

```

**Comment by Durman** [comment]
I have found interesting solution of the problem. 

![2019-05-21_12-44-23](https://user-images.githubusercontent.com/28003269/58081982-23bfee00-7bc7-11e9-8e1a-805ec441133e.png)

The parameter number of loops can be even vectorized.)) 
There is no any need in such socket any more. 
But there is some problem with color of the node. And I'm not sure about order of processing such node tree if this has matter.

**Comment by zeffii** [comment]
as far as i know the order of nodetree updates is not static. In the case of the two outputs from List Join node, it's not certain that the set property Node will be updated first, (and thus setting monad loop value )  

you could use a SNLite as a THRU node, and set the ".loops" from inside the SNLite script ( can even freeze / unfreeze node tree while setting the `.loops`.

**Comment by zeffii** [comment]
something like
```python
"""
in s numloops d=4 n=2
in s inputs
out s outputs
"""
self.id_data.hard_freeze()
self.id_data.nodes[ your monad node ].loops = numloops  # maybe set a min max yourself?
self.id_data.hard_freeze()

outputs = inputs
```

**Comment by zeffii** [comment]
i'm not sure if that snippet works,  but it's where i would start. because that's more likely to control the update order

**Comment by Durman** [comment]
While I investigated updated system I did not catch what purpose of having freezing nodes parameter.))

**Comment by zeffii** [comment]
when a node has  a `***Property(......update=updateNode)`  , then whenever that property is touched/set it will cause the nodetree to be updated from that node.

https://github.com/nortikin/sverchok/blob/81624bbc0edee3221483d8bab7292185a9565aae/core/monad.py#L453-L458

so if you update that value, you are triggering a nodetree updated ,  likely before the new data input into monad is read.

**Comment by Durman** [comment]
Well, then I see two possible scenarios:

- Firstly number of loops parameter is changed what caused to process monad with old input data. Then new data came and monad start process again. 
- Second scenario is when firstly new data for monad comes it causes process of monad. Then comes changes of the parameter that also causes extra process of monad. 

So finally this will return correct result in both cases, but with extra calculations.

**Comment by zeffii** [comment]
and you want to avoid extra calculations.

**Comment by Durman** [comment]
Defenetly. I think it is okay for temporary solution.

**Comment by zeffii** [comment]
there's also a `node_tree.sv_process = False` you can set before changing a value, and revert it to True when done.  If i recall correctly they are interchangable. whatever is easier.

**Comment by Durman** [comment]
I think it is not perspective direction because an order of processing of nodes is not clear and too much tricky.
