### ISSUE TITLE
Color bug with list slice node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2241]
## Problem statement

I faced with two little bugs with `list slice` node. First is that when the node is copied with input data it starts to change its color when there is not input data. This bug can be no important.

The next can be more confusing. When the node is orange and one is copied it becomes orange all time there is input data or not.

## Steps to reproduce

![orange bug](https://user-images.githubusercontent.com/28003269/42360012-0e59feaa-80f7-11e8-8e98-76644b83450d.gif)

## Expected result

It would be better to have not confusing colours in the node.

## Actual result

In this case the node draws attention without needing.

**Comment by zeffii** [comment]
Copying a node from a category that isnt themed will result in this issue, spmeone reported a similar issue for the formula node. Yes it sucks, but the fix may be simple or haxxy

**Comment by zeffii** [comment]
see same problem here.. 
https://github.com/nortikin/sverchok/issues/2081

**Comment by zeffii** [comment]
but the first problem is really
https://github.com/nortikin/sverchok/blob/52cd71df107ae10163eb3ff91595fc22f1e25c97/nodes/list_struct/slice.py#L66-L83

the node should probably just `return` out of the `process` function if the Data socket is not linked.

**Comment by zeffii** [comment]
i'm pretty sure i _didn't_ close the issue.

**Comment by zeffii** [comment]
these are the nodes that directly implement copy.

```md
23 matches

nodes/text/note.py                         |  2 lines,
                                    self.n_id = ""
                                    node_id(self)

nodes/text/shape.py                        |  1 line,  self.text = ""
nodes/text/stethoscope_mk2.py              |  1 line,  self.n_id = ""
nodes/text/text_in_mk2.py                  |  1 line,  self.n_id = ""
nodes/viz/empty_out.py                     |  multi line
nodes/viz/viewer_matrix.py                 |  1 line,  self.n_id = ''
nodes/viz/texture_viewer_lite.py           |  1 line,  self.n_id = ''
nodes/viz/metaball_out.py                  |  multi line

nodes/viz/viewer_polyline_mk1.py           |  1 line, 
                                    self.basemesh_name = get_random_init()

nodes/viz/viewer_typography.py             |  1 line,  
                                    self.basemesh_name = get_random_init()

nodes/viz/viewer_indices.py                |  1 line,  self.n_id = ""
nodes/viz/viewer_mk2.py                    |  1 line,  self.n_id = ""
nodes/viz/texture_viewer.py                |  1 line,  self.n_id = ""
nodes/number/easing.py                     |  self.n_id = ''
nodes/layout/wifi_in.py                    |  multi line
nodes/script/multi_exec.py                 |  --- faux hit.
nodes/generator/script1_lite.py            |  2 line simple
nodes/generators_extended/script_mk2.py    |  1 line,  self.n_id = ""

old_nodes/stethoscope.py                   |  1 line,  self.n_id = ""
old_nodes/objects.py                       |  multi line elaborate
old_nodes/objects_mk2.py                   |  multi line elaborate
old_nodes/viewer.py                        |  1 line,  self.n_id = "" 
old_nodes/text.py                          |  1 line,  self.n_id = "" 
```

**Comment by zeffii** [comment]
in the case of the Orange getting stuck, for now you can use the N-panel and untick the Color tickbox. If the node goes into an error state again the update system will automatically reset this variable.

![image](https://user-images.githubusercontent.com/619340/43355048-1b21be64-9256-11e8-9891-e77213aec80e.png)

closing for now.
