### ISSUE TITLE
Normals for 3d curve

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2242]
I find this a little bit tricky to do, so it can become a separate node I think. 
What I have now and it still works unexpectable in some cases:

<details> 
  <summary>gif</summary>  
  
  ![case1](https://user-images.githubusercontent.com/28003269/42391184-95743da2-815f-11e8-91c9-0731130f3c87.gif)  
![case2](https://user-images.githubusercontent.com/28003269/42391278-ed14236a-815f-11e8-870a-ea759fd373eb.gif)
![case3](https://user-images.githubusercontent.com/28003269/42391346-20b4f3a2-8160-11e8-803c-474eaa94785d.gif)
![case4](https://user-images.githubusercontent.com/28003269/42391480-90e0d75e-8160-11e8-8f1a-4d349c37a9a3.gif)

</details>

--
[my to do list](https://trello.com/b/vvC6ieUZ)

**Comment by Durman** [comment]
<details> 
  <summary>gif</summary>  

![spiral](https://user-images.githubusercontent.com/28003269/42395214-224dfa66-816e-11e8-8780-18582095ff8e.gif)

</details>

**Comment by Durman** [comment]
<details> 
  <summary>gif</summary>  

![shift](https://user-images.githubusercontent.com/28003269/42395756-093787de-8170-11e8-8dc4-e1971aacd027.gif)

</details>

**Comment by Durman** [comment]
A little bit about math. 
The idea is to create normals for 3d curves. I have noticed that trigonometry does not work in 3d space. Also it was difficult to use matrix for rotation. So I used only vector math and quaternions for rotation.

![3dcurve noramsl](https://user-images.githubusercontent.com/28003269/42436659-c0503108-836b-11e8-9504-38daafb3bca5.jpg)

**Comment by Durman** [comment]
I've decided don't use quaternions for this node, matrixes is sufficient.

![2018-07-13_08-53-44](https://user-images.githubusercontent.com/28003269/42672983-4612060c-867a-11e8-8e67-f42ed6761f99.png)

**Comment by nortikin** [comment]
is it ready?

**Comment by alessandro-zomparelli** [comment]
hi @Durman , that's great, sorry for the duplicate :P 
Do you think that we can combine my code with your?
In my case I used derivates, really simple to implement with polylines.

![immagine](https://user-images.githubusercontent.com/6708848/48416728-3efdfc80-e751-11e8-92dc-3ba7b5c05291.png)

(code from #2272 )

```
"""
in verts v d=[] n=[]
out nor v
out tan v
"""
"""
in verts v d=[] n=[]
out nor v
out tan v
"""

from mathutils import Vector

curve_2D = False
plane_normal = Vector((0,0,1))
cyclic = False
normalize = False

if verts:
    if len(verts[0])>2:
        if cyclic:
            verts = [verts[0][-1]] + verts[0] + [verts[0][0]]
        else:
            verts = [verts[0][0]] + verts[0] + [verts[0][-1]]
        nor = []
        tan = []
        for i in range(1,len(verts)-1):
            p0 = Vector(verts[i-1])
            p = Vector(verts[i])
            p1 = Vector(verts[i+1])
            
            v0 = (p-p0).normalized()
            v1 = (p1-p0).normalized()
            t = (v0+v1)/2
            if curve_2D:
                n = t.cross(plane_normal)
            else:
                n = (v1-v0)
                if normalize: n.normalize()
            nor.append(tuple(-n))
            tan.append(tuple(t))
        if not cyclic:
            tan[0] = tan[1]
            tan[-1] = tan[-2]
            nor[0] = nor[1]
            nor[-1] = nor[-2]
        tan, nor = [tan], [nor]
```

The only issue that I had, is with zero curvature, it is a problem only if you want to normalize them. 
The only solution that I thought was to store the normal of the last point before the straight segment, and the first right after that segment. Then just interpolate them for the points with zero curvature.

![immagine](https://user-images.githubusercontent.com/6708848/48417247-9486d900-e752-11e8-9b7e-9357328fdcd4.png)

What do you think?

**Comment by 0000888888880000** [comment]
![[ⵙᗝꖴⓄᙏᕤᕦꖴᔓᔕⵙᕤᕦИNꖴИNⓄꖴ✤ꖴᔓᔕИNᗩᴥ✤ꗳᙁᗱᗴᔓᔕⵙᙁᗩᗱᗴᗝꖴ⊚◌⊚◌⚪ⵙ◯ⵙ◯ⵙ⚪◌⊚◌⊚ꖴᗝᗱᗴᗩᙁⵙᔓᔕᗱᗴᙁꗳ✤ᴥᗩИNᔓᔕꖴ✤ꖴⓄИNꖴИNᕤᕦⵙᔓᔕꖴᕤᕦᙏⓄꖴᗝⵙ](http://web.archive.org/web/*/FREEIMAGE.HOST/i/HZubt5u)](https://github.com/nortikin/sverchok/assets/139945999/05196578-ef9f-420d-ba46-65d1b97c7013)
