### ISSUE TITLE
3pt Arc node, type of vector input UI

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2244]
## Problem statement

As I see it, there is no point to have input where it is possible to set coordinates for only one point because the node expects at least three coordinates.

![2018-07-10_08-45-05](https://user-images.githubusercontent.com/28003269/42489709-a4bb1900-841d-11e8-80ac-07181d45a6b3.png)

**Comment by zeffii** [comment]
Agreed this default UI makes no sense.on 3pt node.

**Comment by zeffii** [comment]
What about a quicklink that adds 3 vector nodes and a list join, sets the vectors to a sane default then links them.

**Comment by zeffii** [comment]
or indeed, just a vector quicklink :)

**Comment by Durman** [comment]
Great idea. If it possible we can connect just `list input` node in `vector` mode.

**Comment by Durman** [comment]
might so?

```Python
vector_prop.prop_name = 'at least 3 points'
```
![2018-07-10_12-53-08](https://user-images.githubusercontent.com/28003269/42499646-5c3f345e-8440-11e8-9d29-28774000bdbd.png)

**Comment by zeffii** [comment]
no. we dont do that. i'll push an acceptable change :) soon!

**Comment by zeffii** [comment]
not ready yet:  https://github.com/nortikin/sverchok/pull/2245
