### ISSUE TITLE
Presets Macro Buttons but in 3D View Left Panel?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2252]
I really love the SV Presets Panel with easy buttons creation for nodes and also the management. A lot of efforts have been made to create this system. Kudos and respect to the designer.

What would be even nicer is to be able to trigger the Preset Buttons in 3D view, even with SV Node Tree panel hidden. Is there a trick to do this at the moment?

I could imagine a lot of scenario where this could be useful. Perhaps even turning it into a combo that does something like this:
- Original Object -> Scatter Points -> Voronoi 3D Fracture -> New Object / Intermediate Object and then continue with next presets.

I was thinking about this because Blender does not have a nice shelf and easy button creation at the moment, even to trigger simple bpy ops combo.

**Comment by portnov** [comment]
I do not see how it is possible / useful to use Presets panel without node editor visible. Please describe one or two scenarios.

**Comment by enzyme69** [comment]
It could be handy if we like to be in Object Mode longer, or even deeper into Edit Mode when selecting component levels like polygon face. 

So from 3D Viewport we can invoke: Sverchok Extrude, for example. Then we jump into node editor and tweak.

[Object] -> invoke Macro -> continue work in Object mode -> invoke Macro -> etc. With potential for every process is an intermediate object or got deleted as needed.

Another scenario:
Draw Grease Pencil -> Macro GP+ while in 3D view, and we get result with the GP deleted with Macro. -Continue drawing grease pencil.

Actually I am just wondering if Sverchok Macro can trigger multiple lines command or scripts? This way, we have Blender Shelf, although it is Vertical like Panel.

**Comment by zeffii** [comment]
you should look at the code of some of the macros, plenty of multi-line commands. The ability to make macros was added in the hope that it would let people "scriptify" certain repeating tasks.  I distinctly remember showing a macro that would take a GP stroke and import it, all you would need to do is add another line to remove the GP at the end. This does require you to figure out how to do that via code.

One way to go about that would be to ask on BSE, with no other context than:

> "i'm trying to delete a GP stroke from a scene programatically, how do I do this"

(you don't need to mention that you are going to use it in sverchok... )

**Comment by enzyme69** [comment]
Ok thanks for informations and suggestions, I will close this for now and investigate. Cheers~

**Comment by enzyme69** [comment]
@zeffii I am recalling the Macro < > and now looking at the documentation. Wondering if Button Presets can work with Macro.... Or maybe having the ability to load Macro from 3D View?

**Comment by enzyme69** [comment]
And is there a Script Node Lite: generate Button? So we can have node with button that simple call the Macro?

The Macro can be called via the special menu, but how to actually call the Macro from Script?

**Comment by zeffii** [comment]
A lot is possible, unfortunately as with all cool stuff -- unless it is similar to something that we implemented already -- someone has to figure out all the steps and code it and test it. I'm not in position to offer my time on this. (Also i think you should sink time into how to write operators... it would benefit you more in the long run than if,.. say...someone were to code this up for you)

**Comment by enzyme69** [comment]
Will do then maybe I assign this task to myself 👍
