### ISSUE TITLE
Do we have Boolean 2D already?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2261]
I look around for nodes that does curve and path boolean, does Sverchok already have it?

Here I am using Intersect Node and Manually getting rid of the inside:
<img width="1201" alt="screen shot 2018-08-21 at 11 48 29 pm" src="https://user-images.githubusercontent.com/3952687/44405613-03fa8b80-a59d-11e8-98a4-2d870ec08be6.png">

**Comment by enzyme69** [comment]
Ookey... I remember this Shapely thing:
https://github.com/nortikin/sverchok/issues/2146

But I wonder if SV already has this (unite, intersect)  2D node without shapely?

**Comment by enzyme69** [comment]
I stumbled into TinyCAD add-on by @zeffii 
https://en.blender.org/index.php/Extensions:2.6/Py/Scripts/Modeling/mesh_tinyCAD

For working in Edit Mode, modeler can use "intersect" operation in this add-on which is probably what Blender user is more used to.

SV Intersect 3D kind of doing similar thing.

**Comment by zeffii** [comment]
i think @Durman has had some success with a scripted node version (SNL), as seen on VK.com. When ready I expect it will be turned into a Node properly (else I will)

tinyCAD is the origin of SV's intersect node. It had some updates from @portnov so it's even faster than tinyCAD's VTX function. (both are full 3d)

**Comment by enzyme69** [comment]
@zeffii  @Durman Do you recall the name of the SNL? At this point, I started to find some difficulties in finding nodes that does what function 😅The grouping and search does help.

**Comment by zeffii** [comment]
i don't think the SNL is public yet, that would make finding it difficult indeed.

**Comment by enzyme69** [comment]
@zeffii Your Intersect Edge and Edgenet Planar works really well actually, but the funny thing is that I need to run **bpy.ops.mesh.split()** manually for each face and then the face are actually split nicely and cleanly.

Is there SV operator that perform this bpy.ops.mesh.split()?

[edgenet_circles_005.blend.zip](https://github.com/nortikin/sverchok/files/2313073/edgenet_circles_005.blend.zip)
<img width="1039" alt="screen shot 2018-08-23 at 3 40 42 pm" src="https://user-images.githubusercontent.com/3952687/44506714-f6531c00-a6ea-11e8-99a7-5fb206de135e.png">

**Comment by enzyme69** [comment]
Somewhat I also realized your Extrude Separate Face does this!

<img width="615" alt="screen shot 2018-08-23 at 3 43 34 pm" src="https://user-images.githubusercontent.com/3952687/44506789-51850e80-a6eb-11e8-803f-4d85fce073f5.png">

**Comment by enzyme69** [comment]
@nortikin 
<img width="836" alt="screen shot 2018-08-24 at 12 01 07 pm" src="https://user-images.githubusercontent.com/3952687/44560917-674f0e00-a795-11e8-975f-c5dd61acbca5.png">

Thanks Nikitron! 

I think I got some interesting things here. What would be cool is if we can then easily "Fyuse" Polygon Faces that are close or touching each other. Then we have "Unite" Boolean 2D.

**Comment by enzyme69** [comment]
BLEND
[edgenet_circles_012.blend.zip](https://github.com/nortikin/sverchok/files/2316769/edgenet_circles_012.blend.zip)

**Comment by nortikin** [comment]
![holes-extruder2](https://user-images.githubusercontent.com/5783432/44596018-7c4a9200-a7d3-11e8-8e56-ad2b332e8bf1.png)
![holes2](https://user-images.githubusercontent.com/5783432/44596019-7c4a9200-a7d3-11e8-933c-42f2ce265f20.png)
![holes1](https://user-images.githubusercontent.com/5783432/44596020-7ce32880-a7d3-11e8-97e4-f29fc1c04255.png)
![holes](https://user-images.githubusercontent.com/5783432/44596021-7ce32880-a7d3-11e8-9364-aa5e6c648f44.png)

**Comment by enzyme69** [comment]
@nortikin I still don't know how to use the SNL Hole in Ordered Polygon node!

Btw, it's amazing that we can generate Brutalism buildings using SV already.

**Comment by nortikin** [comment]
@enzyme69  in examples there is shape-holes in polygon example. try.
and also this example:
[holes-extruder1.blend.json.zip](https://github.com/nortikin/sverchok/files/2321968/holes-extruder1.blend.json.zip)

**Comment by vicdoval** [comment]
I have been also trying to fit the puzzle, more searching a way to crop a surface
![crop2d](https://user-images.githubusercontent.com/10011941/45192601-86e03f00-b249-11e8-917f-3d70cabf8907.png)
Although the node is mainly functional there are still many glitches, I hope i will find time to polish it soon...

**Comment by enzyme69** [comment]
That's cool! Should be pretty handy to sketch up logo then. Grease Pencil
Blender 2.8 should have operation dealing with this, I think.

Also maybe can work with UV layout, so we can wrap arbitraty lines into 3D
shapes.

>

**Comment by alessandro-zomparelli** [comment]
thanks @enzyme69 for mentionig that. The limitation of contour curves is that they still depends on the number of subdivision of the starting mesh. If you want very small details it is not the best solution, but if you work with more soft shapes I think that it can do the job.
