### ISSUE TITLE
Set Property fails when grouped

### ISSUE THREAD

**Issue by k1ff** [nortikin/sverchok#2263]
## Problem statement

I have a node tree, with a Set Property node that is referencing the Size parameter of a Line MK2 node.
When I group the entire node tree the Set Property node doesn't seem to communicate with the Size parameter anymore. So I jumped into the group and realised the code needed to be changed to the new node group name, but still, it doesn't seem to be linked anymore. I even deleted the Set Property node and created a new one in the group hoping that would work, but it didn't.

## Steps to reproduce

1. Create a Line MK2 node and connect it to a Viewer Draw node. Enable Center and Normalize on the Line MK2 node.
2. Create a Set Property node and link it to the Size parameter. Would look something like this - 
bpy.data.node_groups["NodeTree"].nodes["Line MK2"].size
3. Group the Set Property and the Line MK2 node and connect the Set Property to the Group Input node.
4. When you go back now and try drag the parameter on the group nothing happens.
5. Jump back into the group and change the code from ["NodeTree"] to ["Monad"] to reference the new node group.
6. Jump back out of the group and it still doesn't work.

## Expected result

You should still be able to control the parameter.

## Actual result

The link is broken and you can no longer control the property.

## Sverchok version

SV 0.5.9.6 (300a895)

**Comment by zeffii** [comment]
thank you for this thorough introduction to the problem.

`set property` node was aimed at passing values to things that don't have sockets. In particular properties of Scene Objects.. or properties of the Scene. 

@DolphinDream maybe expose `.size` as a socket?

using Set Property from one NodeTree into a monad is not supported (and might never be). You should consider the content of a Monad as fully encapsulated except for values passed into it via incoming sockets.  I've had crashes using Set Property that way.

**Comment by DolphinDream** [comment]
@zeffii Sure, the size could be exposed as a socket.. however this property is only available when "normalize" is on.. so, if something is connected to it while turning normalize ON the connection will be dropped. Also, injecting input sockets may mess up the socket indices.. unless the "size" socket is added at the end of the input socket list.

On this note, the Plane MK2 node has a "normalize" size property as well. however it has size x and y.. with the option to lock the two. If we switch this node as well to expose the sizes as sockets the layout may not be as nice and compact and each size prop will take one row as an input socket. If such an update is desired and all agree to change the layout then I don't see a reason why not to expose the size(s) as a socket(s).

**Comment by DolphinDream** [comment]
Vectorizing the node to include the **size** may not be trivial though considering that the line/plane nodes vectorization is somewhat sophisticated (based on @nortikin nestedness needs : #1147)

**Comment by zeffii** [comment]
i'd mk++ it and add a size socket at index -1 (end of socket inputs). Don't even need to hide it when not used.  or use `socket.hide_safe = True/False` (as was once requested...)

**Comment by zeffii** [comment]
i would also not worry about vectorizing size.

**Comment by k1ff** [comment]
Thank you so much for the feedback and answers. If an input socket for the size parameter could be added to the Line MK2 I would be very happy.

**Comment by zeffii** [comment]
btw this may work
![image](https://user-images.githubusercontent.com/619340/44618956-04867100-a880-11e8-9363-aa4467edd7f0.png)

**Comment by k1ff** [comment]
That doesn't seem to work. Got really excited. I want to package this tree into a node group but this one issue won't let me. Was the final verdict to add an input socket for "size"?

**Comment by zeffii** [comment]
there are complications that make this set/get property stuff working inside a monad a lower priority for me. Even a scripted node will show that i'm still not getting desired results.

```python
""" 
in size s .=[] n=2
in dummy_in s .=[] n=0
out dummy_out s
"""

from sverchok.utils.context_managers import hard_freeze

line_node = self.id_data.nodes['Line MK2']
with hard_freeze(line_node) as node:
    node.size = size

dummy_out = dummy_in
```
where the dummy socket acts as a way to define the order in which to trigger the nodes.
this works.. kind of, but shows there's a competing updateloop ...

![image](https://user-images.githubusercontent.com/619340/44714531-d8543580-aab5-11e8-9d0d-de370cb33811.png)

**Comment by k1ff** [comment]
Would it be possible for now to just expose the "size" socket? I don't think it will be bad thing to have regardless.

**Comment by zeffii** [comment]
i agree.. there doesn't appear to be a great reason why that property shouldn't have a socket.  It wasn't part of the design spec at the time, and it's not like it will require any huge edits.

the sad thing here is ... that the amount of energy i expended responding to this dwarfs the amount of code needed to add the socket.

**Comment by zeffii** [comment]
if I do this i demand some visuals :)

**Comment by k1ff** [comment]
Sure :)

**Comment by k1ff** [comment]
It will be hugely appreciated. I have built a sort of house generator. It's a very simply house but it's a step in the right direction. And I use the Line MK2 as vertices to spawn the windows. But I can't group the node tree (it's quite big) so this would be awesome. And the method I am using the line for I will use in a lot of setups!

**Comment by zeffii** [comment]
look at the changed code..
https://github.com/nortikin/sverchok/pull/2265/files

**Comment by zeffii** [comment]
I think i'll make it automatically upgrade the node , so no need to go to MK3. (don't worry if that doesn't make any sense)

**Comment by k1ff** [comment]
That would be great! I also think no need for MK3. Thank you so much zeffii :)

**Comment by zeffii** [comment]
@k1ff   that should work as hoped now. (new socket is created automatically once you update Sverchok)

However. the issue in the title of the thread - of passing values to `nodes.{properties}` _inside a monad_ - must be considered another time. There may be a workable solution

There are other nodes that don't expose all useful params as a socket, because doing that would make huge node interfaces... for those nodes in the future maybe we can add a generic `props` socket, that takes a dict of props/values to pass. That would be quite workable for most nodes.

**Comment by k1ff** [comment]
As promised, here is what I was creating and was able to finish it thanks to your updated Line MK2 input socket :) https://www.youtube.com/watch?v=bc3VVfMNbT8

I know it's real simple, but it's a start :) I'm still learning.

**Comment by zeffii** [comment]
i like it. enjoy!
