### ISSUE TITLE
SNL Points On Surface is a bit off?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2264]
Wondering why with this setup, the SNL Point Inside 3D Mesh is kind of off?
<img width="892" alt="screen shot 2018-08-28 at 1 05 09 am" src="https://user-images.githubusercontent.com/3952687/44667564-7a483380-aa5e-11e8-8398-4f84625cd075.png">

[points_inside_002.blend.zip](https://github.com/nortikin/sverchok/files/2324403/points_inside_002.blend.zip)

**Comment by zeffii** [comment]
use the `points inside mesh` node.  we can remove that SNL.

**Comment by zeffii** [comment]
hmmm. that SNL is called `random points on polygons` , it should be producing a variety of points on the faces of the input mush. it clearly isn't doing that here. not sure why.

**Comment by zeffii** [comment]
have a look at the SNL script

**Comment by enzyme69** [comment]
It makes random points on plane, not spread evenly, but like for Box it generates only on 5 sides.
<img width="395" alt="screen shot 2018-08-28 at 3 34 44 pm" src="https://user-images.githubusercontent.com/3952687/44702678-e87d0c80-aad7-11e8-95e6-3f443e98234d.png">

I'll check your post from the past...

**Comment by zeffii** [comment]
that old post concluded with a better script.

https://github.com/nortikin/sverchok/issues/1810#issuecomment-335875470

**Comment by zeffii** [comment]
> It makes random points on plane, not spread evenly,

where does it imply that the script would produce evenly spread points? .. i don't think it does.

**Comment by zeffii** [comment]
some of those SNL scripts are really intended just as a "springboard" for the inquisitive user who wants to start messing about with dissecting / improving code to do what _they_ want. This means some of them will be incomplete in one or more aspect.

**Comment by nortikin** [comment]
```python
"""
in verts_list v
in faces_list s
in num_points s d=20 n=2
out verts_out v
"""

import bpy_extras
import mathutils
from mathutils import Vector
from bpy_extras import mesh_utils

for verts, faces in zip(verts_list, faces_list):

    mesh = []
    tessellated_faces = []
    add_face = tessellated_faces.append

    try:
        for f in faces:
            if len(f) in {3, 4}:
                add_face(f)
            else:
                # Takes a list of polylines (each point a vector) and returns the point indices for a polyline filled with triangles.
                v = [Vector(verts[i]) for i in f]
                tess_poly = mathutils.geometry.tessellate_polygon([v])
                for tess in tess_poly:
                    add_face([f[i] for i in tess])

        mesh = bpy.data.meshes.new(name="xxxxaaaa")
        mesh.from_pydata(verts, [], tessellated_faces)

        tessfaces = mesh.polygons
        new_verts = mesh_utils.face_random_points(num_points, tessfaces)
        verts_out.append([v[:] for v in new_verts])
        
        if "xxxxaaaa" in bpy.data.meshes:
            bpy.data.meshes.remove(mesh)

    except Exception as err:
        print('nope', err)




def face_random_points_ngons(num_points, tessfaces):

    from random import random
    import mathutils
    from mathutils.geometry import area_tri, tessellate_polygon

    # Split all quads into 2 tris, tris remain unchanged
    tri_faces = []
    for f in tessfaces:
        tris = []
        verts = f.id_data.vertices
        fv = f.vertices[:]

        if len(fv) == 3:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
        elif len(fv) == 4:
            tris.append((verts[fv[0]].co, verts[fv[1]].co, verts[fv[2]].co))
            tris.append((verts[fv[0]].co, verts[fv[3]].co, verts[fv[2]].co))
        else:
            fvngon = [v.co for v in verts]
            tris.extend([[fvngon[i] for i in tess] for tess in tessellate_polygon([fvngon])])

        tri_faces.append(tris)

    # For each face, generate the required number of random points
    sampled_points = [None] * (num_points * len(tessfaces))
    # sampled points need to be vectorized as npo below
    for i, tf, npo in enumerate(zip(tri_faces,num_points)):
        for k in range(npo):
            # If this is a quad, we need to weight its 2 tris by their area
            if len(tf) == 2:

                area1 = area_tri(*tf[0])
                area2 = area_tri(*tf[1])
                area_tot = area1 + area2
                area1 = area1 / area_tot
                area2 = area2 / area_tot
                vecs = tf[0 if (random() < area1) else 1]

            elif len(tf) == 1:

                vecs = tf[0]

            else:

                areas = [area_tri(*tface) for tface in tf]
                area_tot = sum(areas)
                areas = [(area / area_tot) for area in areas]

                #  vecs = tf[0 if (random() < area1) else 1]   ???

            u1 = random()
            u2 = random()
            u_tot = u1 + u2

            if u_tot > 1:
                u1 = 1.0 - u1
                u2 = 1.0 - u2

            side1 = vecs[1] - vecs[0]
            side2 = vecs[2] - vecs[0]

            p = vecs[0] + u1 * side1 + u2 * side2

            sampled_points[npo * i + k] = p

    return sampled_points
```

**Comment by Durman** [comment]
@nortikin There are some downsides of the code. It is possible to create one point per polygon and impossible to create one point per mesh. So it impossible to have the same density for whole mesh if polygons have different square. And random seed depends from current frame.

![random](https://user-images.githubusercontent.com/28003269/45083572-3cf23e80-b10d-11e8-8a44-14ca4dac778f.gif)

**Comment by zeffii** [comment]
a proposition would be to give the number of points relative to a 2d unit, surface. instead of per face

**Comment by zeffii** [comment]
so if a quad or tri is encountered that's a relatively simple calculation, but an ngon would first calculate the tessellated surfaces and the required numbers of points per tessellation. All good fun.
