### ISSUE TITLE
Bmesh In Out Modifier dependency crashing Blender

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2267]
[nodes_modifier_workflow_002.blend.zip](https://github.com/nortikin/sverchok/files/2338592/nodes_modifier_workflow_002.blend.zip)
<img width="1097" alt="screen shot 2018-08-31 at 12 41 03 pm" src="https://user-images.githubusercontent.com/3952687/44889886-4e0d0b00-ad1b-11e8-8a30-f2c540f94455.png">

It's pretty strange, but I experienced crashing every single time I do this:
- SV generate BMesh Out for Boolean Modifier operations
- Bmesh In back into Sverchok
- Scrub timeline and .... CRASH!!!

Is there a way to prevent this crashing so that I could have a smooth Node and Modifier combo?

**Comment by zeffii** [comment]
maybe not with just those nodes. i can't be certain of the cause. but .. i suspect the BMViewer is updating `scene` and causing other node trees to update and in turn also updating `scene`, and in turn causing the first node tree to update again. Did you test with a ViewerDraw in `nodetree.002` instead of BMViewer ?

![image](https://user-images.githubusercontent.com/619340/44895590-463a7000-acf5-11e8-895d-dbbf013fb38f.png)

that does work..

**Comment by enzyme69** [comment]
With Viewer Draw (on the right) it is also crashing. Because the idea is to
have node processing >> output bmesh >> assign some modifiers >> bring back
to node

>

**Comment by zeffii** [comment]
bummer :)

**Comment by zeffii** [comment]
this is a cyclic thing that Sverchok can not handle at the moment. I think you've brought up variants of this issue numerous times. It's also what I consider a "strenuous use case", where time spent adapting sverchok to allow this would distract from improving sverchok in general.

**Comment by enzyme69** [comment]
@zeffii Thanks for explanation Zeffii, I'll try to find way around this for now... not sure if all node tree gets calculated all at the same time, or ...

**Comment by Durman** [comment]
@enzyme69 You can use this way but it also crushes with animation.

![2018-09-05_08-53-01](https://user-images.githubusercontent.com/28003269/45071887-829d1000-b0e9-11e8-9ec5-0ab88d9c0601.png)

I faced with similar loop when I tried to use operators and `objects in` node. https://github.com/nortikin/sverchok/pull/2218#issuecomment-393947450
