### ISSUE TITLE
Image Node

### ISSUE THREAD

**Issue by GrindingAgony** [nortikin/sverchok#2268]
## Problem statement
Using Image Node to produce an array of circles resembling image density -
"Framing" of image not always correct, for example, when image height is 1.5 times width,  used Xvecs = 30 & Yvecs = 45, & image displays correctly , but not for  Xvecs = 60 & Yvecs = 90. The proportion is the same for both cases, but for the higher values, the image is far too big & I can only see the centre part of the image in the result.

## Steps to reproduce

1. Load image in image editor, setup node tree . . .
2. For Image Node, load image - after processing with Xvecs = 30 & Yvecs = 45, result appears as expected
3. Change to  Xvecs = 60 & Yvecs = 90, & image size seems approximately 3 times what it should be, expect it to be twice, ie image no longer fits the dimensions.

## Expected result

Entire image should be processed

## Actual result

Image far too big, & only centre part fits the array generated from the Image Node.

## Sverchok version

Installed from zip file, Blender 2.79, Sverchok 0.5.9.6
ok - tried to download the file, but I got message - "that file type not supported"

**Comment by zeffii** [comment]
A node that may better suite your needs is `Generators->Image Decompose`

![image](https://user-images.githubusercontent.com/619340/44953769-5048a400-ae98-11e8-8874-b42c5b5809d2.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/44954365-26e04600-aea1-11e8-8766-a67052bf5932.png)

**Comment by GrindingAgony** [comment]
Yes - Thanks for your attention here, & I've tried the Image Decompose node, but upon loading a small image, I get a traceback error - "unexpected EOF while parsing". I have played with the values a bit & different images, am getting no output at all.  These images are all fine in other application.  I'm using .png's. I'm going to "practise" with the Image Decompose node till I can get something to load.

**Comment by GrindingAgony** [comment]
OK - I can't load any .jpg or .png into this node.

**Comment by zeffii** [comment]
load the images into the `UV editor/ Image View` first?

**Comment by zeffii** [comment]
also you need to connect both XYA and RGB sockets before the node outputs anything.

**Comment by GrindingAgony** [comment]
Yes, they show in image editor. Yes, I had both those sockets connected, exactly as in your image above.

**Comment by GrindingAgony** [comment]
OK - now it's going totally crazy - let me go away, play with this tomorrow morning as I'm nearly falling to sleep here, & I'll come up with something consistent. Once I have a reproduceable set of circumstances, I'll feed back what I find. At the moment with the image loaded, I can't even connect any noodles - so, thanks for your help, I'll get back to you with something more definative, (for what it's worth I'm using a quad core processor, no other programs, plenty RAM, system smooth & no errors, Windows 7) - back soon.

**Comment by zeffii** [comment]
OK.  big images will inevitably be slow within our current framework, but because the node caches the image that only happens once. Sadly we've only done a limited amount of experiments with images as input, and fewer still with larger images.

**Comment by GrindingAgony** [comment]
OK - I have found the following issues - 
Image Node - As detailed in the original comment, the image size is not correctly detected for all image formats I have tried. Sometimes it's close, other times it's way out.
Image Decompose Node - works well BUT only if you connect its outputs AFTER you have the image loaded. It seems that processing of data may start prematurely on load-up, or some other interference is occuring. What I did was put in all the node structure without the Image Decompose connected, load the image, then connect the node. 

I wish I could help here - in 6 months when I'm retired, I'd like to help as a programmer. Sverchok is a great piece of software. Thanks for all your help, GrindingAgony!

**Comment by zeffii** [comment]
> I wish I could help here - in 6 months when I'm retired, I'd like to help as a programmer. Sverchok is a great piece of software. Thanks for all your help, GrindingAgony!

We are open to contributors. The upcoming Blender 2.8 will require a fresh look at several Sverchok features, there will be a non trivial amount of work.

**Comment by GrindingAgony** [comment]
Thanks, - when Blender 2.8 is settled, I will review the Sverchok feature set & contact the team to see if I can put some time in.

**Comment by zeffii** [comment]
btw. regarding your issue it has bugged me.  We have a Text Out node that writes data (so..data you've processed) into a json (on disk or in bpy.data.texts as a datablock), and that would save some massive recomputation. Note however you haven't mentioned animation or video/raster-sequence input, but even that could be handled (with a custom solution). The rest of this answer will assume you don't need new data per frame.

Text Out is pretty neat, in combination with Text In.

![image](https://user-images.githubusercontent.com/619340/45018843-312e4b80-b02b-11e8-8171-f612fc2ac0e7.png)

Note here i'm showing two different node trees, you can even freeze `NodeTree` by depressing the P here (stops processing that tree entirely)

![image](https://user-images.githubusercontent.com/619340/45018982-75b9e700-b02b-11e8-901e-2997144aca28.png)

tips:
  -  I suggest trying this on a smaller image first to get the hand of it . 
  - do not have the Text Viewer open when pressing "Dump" on Text Out , it will slow down the entire process a bit.

**Comment by GrindingAgony** [comment]
OK - good "insight" here. I'll investigate with other images - if I can isolate what is going on here, I'll be back.
