### ISSUE TITLE
"Vertex colors mk3" odd behaviour

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2269]
## Problem statement

"Vertex color mk3" node draws something strange instead of simple color

## Steps to reproduce

1. set up simple tree, see screenshot
2. observe

![screenshot_20180902_121916](https://user-images.githubusercontent.com/284644/44953159-72e3b880-aeaa-11e8-8412-57f90d6c73a2.png)

## Expected result

The plane should be in one color

## Actual result

The plane is oddly colored

## Sverchok version

** version:  0.5.9.6, branch master, commit f589a874  **

## Blender

````
Blender 2.79 (sub 0)
        build date: 2017-09-11
        build time: 12:19:07
        build commit date: 2017-09-11
        build commit time: 10:43
        build hash: 5bd8ac9abfa
        build platform: Linux
        build type: Release
        build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wnonnull -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -fuse-ld=gold -std=gnu11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
        build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Werror=implicit-function-declaration -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -fuse-ld=gold -std=c++11   -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -msse2
        build link flags:  -Wl,--version-script='/home/sources/blender-release/source/creator/blender.map'
        build system: CMake
````

**Comment by portnov** [comment]
Observation: "Vertex colors mk2" works fine ... wtf?

**Comment by zeffii** [comment]
possibly the vertex layer now has two modes? `-/+ alpha`

**Comment by vicdoval** [comment]
"Vertex color mk3" works fine on RGB mode (on the N-panel) and seems to to fail on RGBA, maybe  the default should still be RGB

**Comment by vicdoval** [comment]
in the last build 2.79.6 works perfect on RGBA. I guess 2.79b didn't support RGBA

**Comment by portnov** [comment]
Can we add a version check to the node?

```
if blender_version >= 2.79.c:
   use_rgba()
else:
  use_rgb()
```

**Comment by zeffii** [comment]
@portnov feel free to do that!       for some reason i was not notified about this comment back in september.

**Comment by zeffii** [comment]
what do you want to do about this @portnov  , is OK to close?   else perhaps someone should write a util function to test the build date . nothing too complicated but ... 
```python
is blender_built_before(date=unixtime):
    ...
```

**Comment by zeffii** [comment]
that would catch most stuff for that node

**Comment by Gerkinfeltser** [comment]
Hmm, I'm having this same issue whether swapping from RGB to RGBA. Could it perhaps be reopened or should I make a new issue?
[SvVertexColorBug.zip](https://github.com/nortikin/sverchok/files/2715465/SvVertexColorBug.zip)

**Comment by zeffii** [comment]
@Gerkinfeltser the solution (if i recall correctly) is to ensure than your nodes are generating 4 values per color.

**Comment by zeffii** [comment]
depending on the version of Blender you're using you can't just 'switch' arbitrarily. The latest Blender 2.79 nightly builder.blender.org versions will all expect 4 channels for vertex colors.

Try it in a fresh file just to prove to yourself how this works.

**Comment by Gerkinfeltser** [comment]
Oh, you're right. Nightly Build works fine. Was a bit confused as I assumed the official 2.79b would be the last they needed to do nightly builds for. :+1:
