### ISSUE TITLE
Node - Vector Interpolation Mk2

### ISSUE THREAD

**Issue by GrindingAgony** [nortikin/sverchok#2270]
## Problem statement

I see a Grid option in the examples given (there's a "default grid" checkbox),  
https://cloud.githubusercontent.com/assets/5783432/19576172/09c7d264-9723-11e6-86fc-3b6acd0b5d53.png
with a black grid built between the blue vectors - is that black grid for illustrative purposes or should I be able to produce it with a node setup similar to what is shown?

**Comment by zeffii** [comment]
no nodes other than the Viz nodes will output drawing data into 3dview. The grid you see is composed by UV Connection node ( i would love to call that node EdgeSurf and place it in a UV menu )

**Comment by nortikin** [comment]
@zeffii have we UV menu?

**Comment by nortikin** [comment]
@GrindingAgony use this:
![uvconnect](https://user-images.githubusercontent.com/5783432/45061587-c1ad7000-b0ad-11e8-8d81-1fc3f95d6d08.gif)

**Comment by GrindingAgony** [comment]
Great!! Appreciate UR help. 
Yes - I can build on the above - It took me a while to "get" the methodology of Sverchok, I will come back to make a contribution when my headspace is clear of work etc in about 6 months. I'd love to "code" in this project. So many people now use Blender, the Sverchok-Blender combo is a good partnership.

**Comment by zeffii** [comment]
> @zeffii have we UV menu?

not yet :)
