### ISSUE TITLE
Dicing Algorithm for 2D Image

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2271]
Not sure if this has been done or asked, slightly general, but I am wondering if Sverchok already has something like "Dicing Algorithm" kind of a way to turn 2D Image into diced pixel image where we can control the details along edge, kind of similar to this:

<img width="480" alt="screen shot 2018-09-06 at 12 30 07 pm" src="https://user-images.githubusercontent.com/3952687/45131515-9bccbc00-b1d0-11e8-8a5a-8dea25eb049b.png">

But as it is nearing edges with more details, the dicing is getting smaller and smaller.

**Comment by zeffii** [comment]
not really a Sverchok issue @enzyme69 , start using Blender Stack Exchange. (seriously)

**Comment by zeffii** [comment]
maybe someone there is bored and will help you with code, or suggest how to start.

**Comment by enzyme69** [comment]
Ok thanks 🙏🏽
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by vicdoval** [comment]
@enzyme69 you could filter the image through a border detection algorithm (in gimp) and use the brightness of the resulting pixels as polygon subdivision factor.

**Comment by enzyme69** [comment]
@vicdoval I'll try that, thanks Vic! I think I need to seek for proper Tree Map algorithm...

Based on your suggestion, I ended up with this:
<img width="784" alt="screen shot 2018-09-11 at 10 42 56 am" src="https://user-images.githubusercontent.com/3952687/45331930-03a84b80-b5b1-11e8-9ea7-0634388fa19e.png">

Maybe I didn't do that properly, but I think if I randomize subdiv based on area masking, it might work!
