### ISSUE TITLE
Extrude Separate Face Lite + Matrix is Weird

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2274]
## Problem statement

I am testing Extrude Separate Face Lite, and providing Matrix data, which supposedly based on center and normal of each face.

<img width="413" alt="screen shot 2018-09-08 at 4 12 17 pm" src="https://user-images.githubusercontent.com/3952687/45251004-27397f00-b382-11e8-94db-5bb8847a7c47.png">
<img width="933" alt="screen shot 2018-09-08 at 4 12 16 pm" src="https://user-images.githubusercontent.com/3952687/45251005-27397f00-b382-11e8-944b-9b758a896719.png">

[virus_008.blend.zip](https://github.com/nortikin/sverchok/files/2363059/virus_008.blend.zip)

## Steps to reproduce

Use Extrude Separate Face Lite and provide Matrix Data.

## Expected result

I am expecting the Matrix push the extrusion based on the provided normal.

## Actual result

Messy extrusion.

## Sverchok version
185ecb1

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by enzyme69** [comment]
@zeffii My feeling is ... by default that Extrude Separate Lite Z+ is extrude along normal. If so, what would be a way to override it so that the new input "normal" I pass into the Matrix can follow my own "Normal" + variation.

**Comment by enzyme69** [comment]
I tested it with Cylinder.
<img width="1047" alt="screen shot 2018-09-08 at 9 12 34 pm" src="https://user-images.githubusercontent.com/3952687/45253521-10a81d80-b3ac-11e8-816f-007a333944d3.png">

**Comment by enzyme69** [comment]
Yes, so I again misunderstood the node:
<img width="845" alt="screen shot 2018-09-08 at 9 15 08 pm" src="https://user-images.githubusercontent.com/3952687/45253536-5533b900-b3ac-11e8-946c-2c1c427fcf81.png">

**Comment by zeffii** [comment]
then write a little bit about what you understand now, so people coming to this issue know how to use it... or someone might want to add/update docs for this node.. showing simple setups is the easiest way, the simpler the better
