### ISSUE TITLE
Sverchok and UV Texture Nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2276]
I am currently looking at some nodes in SV that escaped my radar especially dealing with UV Texture on object:

- Find UV Coord on Surface
- Set UV Color
- Sample UV Color

I remembered also Nikitron made UVTextures node at some point.

By any chance is there a quick way in SV to output something like below:

```
uvs.Set([(0.375, 0), (0.625, 0), (0.625, 0.25), (0.375, 0.25), (0.625, 0.5), (0.375, 0.5), (0.625, 0.75), (0.375, 0.75), (0.625, 1), (0.375, 1), (0.875, 0), (0.875, 0.25), (0.125, 0), (0.125, 0.25)])
uvs.SetIndices(Vt.IntArray([0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 8, 9, 1, 10, 11, 2, 12, 0, 3, 13]))

```

So, basically needing the index vertices on where the UV position is.

**Comment by enzyme69** [comment]
This is what I got so far, it is promising but there must be easier way.

[uv_position_005.blend.zip](https://github.com/nortikin/sverchok/files/2369213/uv_position_005.blend.zip)

I have a Cube + UV.
I output the UV as mesh, so I can find the position of each UV, normalized between 0-1 as another mesh.
From that other mesh, I can back trace and "translate" the UV back and find the original index number. But I still have to write down manually.

I supposed, I can write a script that find a matching vertex position and return the index... 🤔

Is there a documentation on those UV nodes? I could not recall anyone posting about this.

**Comment by enzyme69** [comment]
@Kosvor2 you made the UV node? Is there way we can just output all the UV coords and the original index vertices as list?

**Comment by enzyme69** [comment]
Latest setup using KDT Closest Vertex, I think I can output the index...
[uv_position_006.blend.zip](https://github.com/nortikin/sverchok/files/2369242/uv_position_006.blend.zip)

**Comment by enzyme69** [comment]
Hmm...

I realized my question was wrong:
```
uvs.Set([(0.375, 0), (0.625, 0), (0.625, 0.25), (0.375, 0.25), (0.625, 0.5), (0.375, 0.5), (0.625, 0.75), (0.375, 0.75), (0.625, 1), (0.375, 1), (0.875, 0), (0.875, 0.25), (0.125, 0), (0.125, 0.25)])
uvs.SetIndices(Vt.IntArray([0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 8, 9, 1, 10, 11, 2, 12, 0, 3, 13]))

```

Supposedly, we can output the sets, and then I just need to match the coordinates and get the Indices set number based on that sequence...

**Comment by enzyme69** [comment]
[uv_position_011.blend.zip](https://github.com/nortikin/sverchok/files/2369312/uv_position_011.blend.zip)

I have problem in making a "unique set" based on vector, but using Remove Doubles, I think that's taking care of the problem.

KDT search helps a lot too.

**Comment by enzyme69** [comment]
And Kosvor did gives some insight:
https://github.com/nortikin/sverchok/pull/2181

Amazing nodes...!

**Comment by nortikin** [comment]
![unfold](https://user-images.githubusercontent.com/5783432/45596216-1d86cb80-b9c1-11e8-88b6-bbeb52969915.gif)
not exact subject, but...

**Comment by enzyme69** [comment]
@nortikin Does SV do UV Texture already?

**Comment by nortikin** [comment]
sorry for delay
@enzyme69 
file of blend:
[shapes_unfold.blend.zip](https://github.com/nortikin/sverchok/files/2454293/shapes_unfold.blend.zip)
