### ISSUE TITLE
Subdividing more like Blender Subdivide Modifier?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2279]
<img width="1092" alt="screen shot 2018-09-12 at 12 23 02 pm" src="https://user-images.githubusercontent.com/3952687/45398238-c57d5b80-b686-11e8-9ef9-5fd86bb9e84b.png">
[planar_edgenet_006.blend.zip](https://github.com/nortikin/sverchok/files/2373354/planar_edgenet_006.blend.zip)

Is there anyway we can use SV Subdivide and make the result more similar to Blender Subdiv Modifier? (Catmul Clark)

**Comment by zeffii** [comment]
not sure how you'd specify this:
![image](https://user-images.githubusercontent.com/619340/45417671-04111700-b683-11e8-85a5-0ad0015f87aa.png)

but regarding the issue of `iterative subdivision`, if that's something you really want then I warmly advise to knuckle down and practice the skill of programming. I feel that each time I code something for you as a response to these questions, it is one more excuse for you to not investigate deeper (take a leap of faith that you can figure this shit out) .

**Comment by zeffii** [comment]
it seems to me that you really want some kind of `subdivision grammar`  (not unlike L system )

```python
num_iterations = 4
"""
tris-> this1 if area > 0.3 else that3
quads -> this2
ngons -> this3
"""
new_mesh = SvMesh()           # see i just imagined we have this.   we don't.

def subdiv_pass(n, mesh):
    for face in mesh.faces:
        if face=='tri':
            new_mesh.add_geom(this1(face))
        ...
            etc

```

**Comment by enzyme69** [comment]
@zeffii Ok thanks Zeffii, I'll put it to sleep.
