### ISSUE TITLE
Object In Curves from SVG is triangulated, can we have the shape without triangulation?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2280]
[curve_no_triangle_002.blend.zip](https://github.com/nortikin/sverchok/files/2385230/curve_no_triangle_002.blend.zip)

## Problem statement

Importing Curves SVG into Sverchok generate polygons that is triangulated and looks wrong when extruded.

## Steps to reproduce

1. Import SVG shapes
2. Import Curves into SV node tree
3. Extrude Separate Face

## Expected result

Probably because Blender Curve to Mesh conversion produces Mesh with Triangulated Poly but we need a method to keep it N-Poly.

## Actual result

Triangulated poly mesh.

## Sverchok version

SV 0.5.9.6 185ecb1

**Comment by enzyme69** [comment]
<img width="1029" alt="screen shot 2018-09-15 at 11 10 21 am" src="https://user-images.githubusercontent.com/3952687/45580738-f56f6d80-b8d7-11e8-8092-673242c3c063.png">

Ok so we have limited dissolve...I guest that will do. But I wonder if we have tris to quads?

**Comment by vicdoval** [comment]
The *Join Triangles* node can turn tris to quads

**Comment by enzyme69** [comment]
@vicdoval There is "face" and "shape" property with description "not sure", but it works after I find the nice value! Thanks Vic!

<img width="937" alt="screen shot 2018-09-15 at 10 06 47 pm" src="https://user-images.githubusercontent.com/3952687/45586075-a820e980-b933-11e8-8a66-37dfc9dc6068.png">
