### ISSUE TITLE
Why not ellipsoid?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2282]
[ellipsoide_007.blend.zip](https://github.com/nortikin/sverchok/files/2394568/ellipsoide_007.blend.zip)
<img width="1218" alt="screen shot 2018-09-19 at 7 24 46 am" src="https://user-images.githubusercontent.com/3952687/45717381-2c49ca00-bbdd-11e8-8683-3f68eb9da1f7.png">
<img width="1108" alt="screen shot 2018-09-19 at 7 24 27 am" src="https://user-images.githubusercontent.com/3952687/45717382-2ce26080-bbdd-11e8-8b1a-f501d24e2327.png">

According to Wikipedia, I should be getting an ellipse, but I keep getting spiral:
https://en.wikipedia.org/wiki/Ellipsoid

Wonder why?

And can we use Vector Polar In and Out node in this case?

**Comment by zeffii** [comment]
you are giving it a continuous range for azimuth, instead if you want to generate one 'slice' (latitude line), you should give it only a limited number of azimuth values ( one per slice ) and however many _polar angle_ values you want per slice.

try to express that with a scriptnode

**Comment by zeffii** [comment]
something like
```python
verts = []
for a in azimuth_values:
    for theta in polar_angles:
        x = ...
        y = ...
        z = ...
        verts.append((x, y, z))
```

**Comment by Durman** [comment]
![2018-09-19_16-42-38](https://user-images.githubusercontent.com/28003269/45753863-119e4200-bc2b-11e8-911f-7daa962ac6a5.png)
[untitled_2018_09_19_12_42.zip](https://github.com/nortikin/sverchok/files/2397070/untitled_2018_09_19_12_42.zip)

**Comment by zeffii** [comment]
just in case this seemed difficult
![image](https://user-images.githubusercontent.com/619340/45808097-48289b00-bcc5-11e8-8d76-0eea0edcc4ca.png)

```python
"""
in a s d=1.2 n=2
in b s d=1.8 n=2
in c s d=1.2 n=2
in num_latitude s d=14 n=2
in num_longitude s d=13 n=2
out verts_out v
"""

from math import pi, cos, sin
from sverchok.nodes.number.range_float import frange_count as interval


azimuth_values = list(interval(start=-pi, stop=pi, count=num_latitude))
polar_angles = list(interval(start=-pi/2, stop=pi/2, count=num_longitude))

for azimuth in azimuth_values:
    verts = []
    for theta in polar_angles:
        x = a * cos(theta) * cos(azimuth)
        y = b * cos(theta) * sin(azimuth)
        z = c * sin(theta)
        verts.append([x, y, z])
    verts_out.append(verts)

```
i spotted a bug in SNLite doing this, so there will be a small update soon.
