### ISSUE TITLE
Stethoscope info out of place & Viewer index font too small

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2284]
I noticed that on current master the stethoscope info is displayed overlapped with the node.. and the font is smaller than usual.. Also (may be related) the viewer index text in the view port is way smaller than it used to be (unreadable). Any ideas what the problem may be ? 

 sverchok version: 0.5.9.6 - master (0bdf0a18) 

<img width="1344" alt="screen shot 2018-09-21 at 9 58 51 pm" src="https://user-images.githubusercontent.com/2083719/45912053-933bce80-bde9-11e8-9a0d-81bfa9a79558.png">

**Comment by enzyme69** [comment]
A know issue 😏 https://github.com/nortikin/sverchok/issues/1969

@zeffii Has been trying to fix it but I think it's more like Apple thing...

**Comment by zeffii** [comment]
yep, feel free to suggest a solution for Mac, and test the crap out of it. If that works i will integrate it into the nodes in a way that works for both OS.

**Comment by alessandro-zomparelli** [comment]
Actually I have the same problem on windows 10... the position is always unpredictable.
![immagine](https://user-images.githubusercontent.com/6708848/46906849-34f69d00-cf0a-11e8-8922-56b656d18e2f.png)

**Comment by DolphinDream** [comment]
Yeah. The node is almost entirely unusable for me (high sierra, macbook pro 2018).

**Comment by DolphinDream** [comment]
It seems that other nodes that render in node view have their rendering location messed up.
Here’s the easing and texture nodes renders.

<img width="788" alt="sv-nodeview-render-bug" src="https://user-images.githubusercontent.com/2083719/46907888-dae4e000-cee7-11e8-924c-335f6603b399.png">

**Comment by DolphinDream** [comment]
Originally I though this may have something to do retina display in OSX having messed up the font DPI somehow (as stethoscope renders text).. but apparently the artifact may not be related to fonts at all.

**Comment by zeffii** [comment]
what kind of DPI settings guys? .. i also use win10

**Comment by zeffii** [comment]
The texture and easing draw code doesn't take into account the Blender DPI/resolution settings. Unlike the stethoschope node. Look at how it decides where and at what scale to draw
```
                    scale = prefs.stethoscope_view_scale
                    location_theta = prefs.stethoscope_view_xy_multiplier
```
https://github.com/nortikin/sverchok/blob/ef2947bc8c6aa2b83bad51a7f1f54b691fbffdf4/nodes/text/stethoscope_mk2.py#L132-L139

ofcourse you shouldn't have to go into sverchok prefs to tweak those values, 

![image](https://user-images.githubusercontent.com/619340/46913742-243e3980-cf93-11e8-9b93-064cf91f180b.png)

![image](https://user-images.githubusercontent.com/619340/46913773-f4436600-cf93-11e8-8444-4151db2252a2.png)


but whatever.. i asked for testers/feedback maybe 5 months ago and got zero feedback.

**Comment by DolphinDream** [comment]
@zeffii I looked into fixing this in the Stethoscope node a while back but I didn’t have any success tracking it down so I stopped looking. As far as the xy multiplier settings go.. I just tried it and it seems that a xy multiplier of x2 brings the Stethoscope output back where it’s supposed to be and a scale of 2 also makes the text big enough to read (similar in size to what it used to be for me a while back when i used a different non-retina mac book). 

The easing and texture node are not affected by these pref settings though (as expected, since the pref settings seem to be for stethoscope node). Pe

My macbook pro 15” (mid 2018) resolutions is:
2880 x 1800 (native) : 220 PPI

while my previous mac book pro 15” (early 2011)  had:
1440 x 900 (native)

The new mac seems to have double the pixel resolution.. which kind of explains the x2 multiplier factor that fixes the Stethoscope node output. I wonder though if SV could read this resolution settings directly from the system and adjust the node output location without relying on the xy multiplier. For now this xy multiplier setting is a nice to have as a temporary solution though.

**Comment by enzyme69** [comment]
<img width="450" alt="screen shot 2018-10-16 at 12 17 17" src="https://user-images.githubusercontent.com/3952687/46994172-7b800d80-d13d-11e8-82d6-f5880255bdb2.png">
@zeffii  It's quite possible that you fix it a while ago, I just made the scaling to 2x for both and seems to work ok on Mac OS Mojave...?

**Comment by zeffii** [comment]
closing until there's a neat solution to autodetect.

**Comment by zeffii** [comment]
you are welcome do do a pullrequest on indexviewer @DolphinDream  : >

i'd understand if users want independent scale factor for idxview and stethoscope..
