### ISSUE TITLE
Gcode Exporter

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2288]
Dear all,
I'm not sure if it is correct to create an issue for that, but I'm working on a new node for gcode generation starting from one or more list of points:

![immagine](https://user-images.githubusercontent.com/6708848/46895606-830f9000-ce79-11e8-8a6d-86ed5019b104.png)

I didn't find an easy way to feed multiline text for Start and End codes, so I decided to use blender's text 
editor for that. Do you think that there is a better way to do that?
At the moment I'm keeping that with the Alpha Nodes, but maybe in future it will be placed with the Text Nodes.

Here you can see what I did with that: https://www.instagram.com/stories/highlights/17942796004146281/

I'm still testing how to correctly calibrate the flow. If you want to test it you can check the gcode branch:
https://github.com/alessandro-zomparelli/sverchok/tree/gcode

Any suggestion is appreciated, many thanks! :)

**Comment by zeffii** [comment]
looks fine, even better if it works as you want it :)

my only kneejerk is the text formatting code,..

```diff
- file.write('G1 X' + format(v[0], '.4f') + ' Y' + format(v[1], '.4f') + ' Z' + format(v[2], '.4f') + ' F' + format(feed, '.0f') + '\n')


+ params = v[:3] + [feed]
+ line_to_write = 'G1 X{0:.4f} Y{1:.4f} Z{2:.4f} F{3:.0f}\n'.format(*params)
+ file.write(line_to_write)
```

**Comment by alessandro-zomparelli** [comment]
Thanks @zeffii , I'll fix that!
I'm still struggling with E parameter that control the extrusion... I need to do more research.

**Comment by alessandro-zomparelli** [comment]
> we don't generally add _who_ made code to the docstring of functions, this can be derived from the git history. i recommend adding a short description of what the functions do. similar to here

Thanks  @zeffii I'll fix that :)

> https://github.com/nortikin/sverchok/blob/master/data_structure.py may be of some interest too. (it looks like you reimplement "match long repeat" function ..but it may be subtily different so...)

I'll check better for duplicates in data_structure.py, do you think that I should move my functions in data_structure.py?

**Comment by alessandro-zomparelli** [comment]
Ok, thanks!

**Comment by stansu** [comment]
![image](https://user-images.githubusercontent.com/9460236/47077003-94b6b600-d232-11e8-8bfb-c8785ab7025d.png)
when i install it, this error came up.

**Comment by alessandro-zomparelli** [comment]
@stansu I tryed reinstalling from file the branch and initially gave me the same error. After opening Blender again and trying again it worked. I think that the problem is some residual from the old Sverchok version.

**Comment by stansu** [comment]
> @stansu I tryed reinstalling from file the branch and initially gave me the same error. After opening Blender again and trying again it worked. I think that the problem is some residual from the old Sverchok version.

i can use it now, thanks!

**Comment by alessandro-zomparelli** [comment]
Great, let me know if you need help. So far I have tested it with a custom 3D printer for Clay. I've made some comparisons for the filament using Cura, and the values seems similar.

**Comment by nortikin** [comment]
made you collaborator
