### ISSUE TITLE
Bug with Dupli Instancer

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2289]
<img width="751" alt="screen shot 2018-10-16 at 11 18 14" src="https://user-images.githubusercontent.com/3952687/46992649-52f41580-d135-11e8-81d7-34a88c57861a.png">

There seems to be a bug with Dupli Instancer where supplying vertices generates "triangles" duplications for every vertices... weird.

**Comment by enzyme69** [comment]
<img width="835" alt="screen shot 2018-10-16 at 11 29 40" src="https://user-images.githubusercontent.com/3952687/46992928-c9ddde00-d136-11e8-95ae-2b3631572a1c.png">

On the other hand we have Mesh Instancer that respect instancing scale, but generates lots of object.

**Comment by enzyme69** [comment]
@Durman The triangle itself works fine in Poly mode, but I wonder if Vertices mode is necessary or it works as intended by the node designer. It's a bit strange, and unless the user really want to have instance for each triangle, this Vertices generating dupli on triangle is ... strange.

Poly / Face Dupli is okey, but then the Scaling does not work in XYZ...

**Comment by enzyme69** [comment]
@zeffii You design this node. The Dupli on Face mode works fine, it generates triangles for it to place the dupli. But the Vertices mode is strange because it creates duplication not on the vertices of the base template, but on the triangles....

**Comment by zeffii** [comment]
> There is no better solution. Triangles does not render on render picture.

I never really considered the code after pushing it 3 years ago :) .

> On the other hand we have Mesh Instancer that respect instancing scale, but generates lots of object.

yeah, but remember that the only slow down there is the initial creation of the objects (if many).. the subsequent update of the object matrices should be really really fast.

**Comment by zeffii** [comment]
the console does suggest there's an error in the logic of that node in its current state
```
    if not obj.name == self.name_child:
AttributeError: 'SvDupliInstancesMK4' object has no attribute 'name_child'
File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\scene\dupli_instances_mk4.py", line 45, in set_child_quota
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/47005310-c39a3280-d133-11e8-9ff4-3871f48c4223.png)

**Comment by Kosvor2** [comment]
Please try with old version to find out whether or not my recent changes caused it: https://github.com/nortikin/sverchok/blob/7fb8a82cabe76b85fcdb5074af5f21a1675a4d65/nodes/scene/dupli_instances_mk4.py

**Comment by zeffii** [comment]
@enzyme69 

>  Scaling does not work in XYZ...

yes, there is no xyz scaling in duplicverts/faces from Blender's perspective. It just offer that ability, this is not a bug in Sverchok. Scaling on duplis is a single scalar value applied to all axes.

**Comment by zeffii** [comment]
@enzyme69 

>  Scaling does not work in XYZ...

yes, there is no xyz scaling in duplicverts/faces from Blender's perspective. Blender does not offer that ability, this is not a bug in Sverchok. Scaling on duplis is a single scalar value applied to all axes.

**Comment by zeffii** [comment]
we can only pass Location (vec) / Rotation (vec) / Scale (scalar)

**Comment by zeffii** [comment]
but we chose to expose those parameters as a Matrix value for convenience. I think this is covered in the docs (if they exist? )  :]

**Comment by enzyme69** [comment]
@Kosvor2 I wonder how to switch to older version and managing the SV script, is this simply by using Github Desktop?

Anyhow... @zeffii thanks for explanation, what I don't get is why vertices mode gives 3x dupli at each vertices location, logically I would think it would just generate Dupli at the template mesh vertices or faces... I will check documentation if exist...

**Comment by enzyme69** [comment]
@Kosvor2 @zeffii https://youtu.be/G4jaFDOYRRc Triangle dupli...

**Comment by Kosvor2** [comment]
@enzyme69 you can just copy-past code into the node .py file.
if last line will have wrong indentation after that, fix that.

This node need a way to add custom object as parent. right now it creates only triangle.

**Comment by enzyme69** [comment]
@Kosvor2 You added some new features like "Vertices" and "Polys" however, there is slight surprised with the result:
<img width="741" alt="screen shot 2018-10-19 at 14 45 10" src="https://user-images.githubusercontent.com/3952687/47204474-9953a980-d3ad-11e8-8ebb-9685d4741dd3.png">

Originally @zeffii seems to provide vertices dupli only. Now the Vertices produces triangle-duplis, while the Face, seems working okey.

**Comment by zeffii** [comment]
what should the behaviour of the 'polys' mode be?  

- place a dupli at the center of each poly in the parent object?  and optionally scale the dupli according to polygon sizes , rotate according to normal ?

**Comment by enzyme69** [comment]
Placement on 'polys' is right, just centered at polygon face. Orientation matrix can use Matrix Normal node.

Placement on 'vertices' is strange because currently it generates tri-dupli at each triangle.

**Comment by zeffii** [comment]
oh right... uhm maybe @Kosvor2 wants to fix it? i'll only touch the code if i definitely know @Kosvor2 has no intention of doing that.

**Comment by Kosvor2** [comment]
I will.

**Comment by enzyme69** [comment]
@Kosvor2 Ready for testing? 💃

**Comment by zeffii** [comment]
check the commits @enzyme69
