### ISSUE TITLE
Evaluate Image Node

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2296]
Hi everybody,
preparing some work for the Gcode generation I added a node that I called "Evaluate Image":
![immagine](https://user-images.githubusercontent.com/6708848/47827890-9fb82d00-dd80-11e8-8a8c-52fc190b3022.png)
You can read the RGB values of an image giving some 2D points (the z is not considered) representing the UV coordinates.
You can chose different Tiling method: Clip, Repeat and Mirror
You can also add some shifting methods in both U and V
Additionally you can change the domain of the image, by default its 0 to 1 for both U and V

What do you think?
I also did a small change in the existing Image Node, removing the limit to 100 and just setting it as a soft_max. Can I merge that too?

**Comment by zeffii** [comment]
looks cool.

> I also did a small change in the existing Image Node, removing the limit to 100 and just setting it as a soft_max. Can I merge that too?

if if doesn't break existing .blend files that use the current Image Node code, then i don't see why not :)

**Comment by alessandro-zomparelli** [comment]
Thanks Zeffii, I'll check possible conflicts.
Inthe meanwhile this is a brief explanation of the Evaluate Image Node:
![immagine](https://user-images.githubusercontent.com/6708848/47952623-ac03dc00-df72-11e8-893b-d08f5a9ec146.png)

From XYZ Vector to UV Pixel:

![evaluate image - xyz to uv](https://user-images.githubusercontent.com/6708848/47952642-d8b7f380-df72-11e8-840b-b346f9323ac1.png)

Scaling Domain U and Domain V:

![evaluate image - domain](https://user-images.githubusercontent.com/6708848/47952643-dce41100-df72-11e8-9b86-1f9ae854f570.png)

Tile Strategies:

![evaluate image - tile and shift](https://user-images.githubusercontent.com/6708848/47952646-e1102e80-df72-11e8-8563-09b1277c114f.png)

**Comment by enzyme69** [comment]
@alessandro-zomparelli It seems to also "tile" the UV information across the 3D model, do you have example application on the cylinder? 

While Sample UV color needs actual UV, your one seems to tile based on parametric?

**Comment by enzyme69** [comment]
<img width="807" alt="screen shot 2018-11-22 at 7 07 55 am" src="https://user-images.githubusercontent.com/3952687/48865996-5d38bc00-ee25-11e8-90fc-d819f4035429.png">

Checker Pattern not tiling across the cylinder...

**Comment by enzyme69** [comment]
<img width="1137" alt="screen shot 2018-11-22 at 7 10 35 am" src="https://user-images.githubusercontent.com/3952687/48866093-b99bdb80-ee25-11e8-9538-4638cb37ec5e.png">

That's actually a bit interesting...

**Comment by enzyme69** [comment]
@Durman Can you reupload the blend example, I am curious... it's not uploading 100% I think.

**Comment by Durman** [comment]
Perhaps I posted message before file have been downloaded.)))
[image evaluate tower_2018_11_23_04_12.zip](https://github.com/nortikin/sverchok/files/2609687/image.evaluate.tower_2018_11_23_04_12.zip)

**Comment by nortikin** [comment]
https://youtu.be/mNPzESCRn2E
