### ISSUE TITLE
Math MK2 and Polyline wierd interference

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2300]
As you can see in the imiage I'm just multiplying a number by itself:
![immagine](https://user-images.githubusercontent.com/6708848/47915495-57456000-dea3-11e8-9f31-5c7c792f8470.png)

But apparently, if the number is used also for a Polyline Viewer MK1 then the Math MK2 generate a list instead of a single value. I don't have the same issue with the Math Node.
Also, if I check the length of the list, the problem disappear...

![immagine](https://user-images.githubusercontent.com/6708848/47915601-aee3cb80-dea3-11e8-8f7c-fcb1de9117cd.png)

Is it quantum physics? @_@

**Comment by zeffii** [comment]
hmmm, there's some shallow copy / deepcopy bullshit going on there.  good find @alessandro-zomparelli

**Comment by zeffii** [comment]
without looking at the polyline code, 

it seems the number node's output value is transformed from `[[some number]]` to `[[some number * n = len(verts) ]]`. 

the polyline node is "match long repeating" the value received by the number node, "in place".

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/7b4cf529a3a39f8507586969c9665b08ac9c20fb/nodes/viz/viewer_polyline_mk1.py#L319

**Comment by zeffii** [comment]
i'm definitely willing to add `deepcopy=True` as a default mode, and `=False` as a boolean option for those who need it.

**Comment by alessandro-zomparelli** [comment]
Great, thanks. I've just experienced the same with the Math Node + Polyline. As you have spotted, the problem is the Polyline :)

**Comment by zeffii** [comment]
pushed the fix. it's https://github.com/nortikin/sverchok/commit/b72083b37b5a55b1d1f13cab0c77bd2f481f262b
