### ISSUE TITLE
Guidelines for 2.8 sverchok nodes

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2301]
Over the last 2 days most of sverchok has been converted to Blender 2.8. Initially this means a few nodes are removed until replacement code is completed. I have read and edited most of the nodes to make this possible and want to encourage new nodes to use the following conventions. Some conventions are now mandatory in Blender 2.8 anyway, others are for making the code easier to look at.

I will update this as the port progresses.

## Guidelines for 2.8 sverchok nodes

- [starting nodes]()
- [modifying existing nodes]()
- [optimizations]()
- [submitting code]()

### Basic stuff

1.  add your properties at the top, inside of the node class. In Blender 2.8+ these properties are expected to be "annotations", and they'll have a slightly different syntax than properties written for `<2.79`.

```python
class SomeClass(....):
    # some_prop_name = IntProperty(.....)    <--don't do this
    some_prop_name: IntProperty(.....)   # <--- do this.  This is the annotation style
```
   -  provide a `update=updateNode` to any of these properties that need to trigger calculations.

2.  add your sockets in `sv_init`. All nodes that have inputs and/or outputs will have a variant of these lines in `sv_init` (or in a function called from sv_init)

```python
    self.inputs.new(socket_type, socket_name)
    self.outputs.new(socket_type, socket_name)
```
   the common *socket types* are

socket_type (a string) | purpose 
 -------------| ----------
`"VerticesSocket"` | transports vectors ( iterables of length 3 )
`"MatrixSocket"` | transports lists of proper mathutils.Matrix() 
`"StringsSocket"` | transports numbers or index lists (edges or polygons)
`"SvColorSocket"` | transports iterables of length 3 or 4 destined for use as colors
`"ObjectSocket"` | transports lists of referebces to proper Blender Objects

*socket names* should be unique, and relatively short.

3.  in `sv_init` you can add `.prop_name` to a socket to make the associated property available as a slider
4.  use `draw_buttons` if you want properties available that you don't want to provide as sockets.
5.  the `process` function is where you 
       - get the incoming socket data

       ```python
       socket_data = self.inputs[socket_name].sv_get()
       ```
       - handle the data combined with property states
       - and set the outgoing sockets with the resulting data

       ```python
       self.outputs[socket_name].sv_set(your_processed_data)
       ```
 6. Make the node `class name` and `bl_idname` identical
 7. add the classname to `index.md`, in the appropriate category

you don't strictly need to use "update" or "update_socket" functions, but some nodes with dynamic sockets / socket changing types may find those functions useful.

### class props are now annotations, mandatory.

While this is mentioned above in the Basics, here to reiterate: Python classes with bpy.props now must use the following annotation syntax

```
class SomeClass(....):
    some_prop_name: IntProperty(.....)
```
alternatively, the `__annotations__` dict can also be used ( link here to example )

### hiding sockets

Certain nodes have a variety of modes and need a robust way to dynamically modify the types of sockets available to the user. Instead of `socket.hide` use `socket.hide_safe`,  this forces sockets to go. you want that.

### replace socket

sometimes.. we want to change the type and name of a socket. we got you covered there too. (stub) . Check the definition of socket_replace to get a better understanding of all the things it can handle.
```python
    some_socket_reference.replace_socket(socket_type, socket_name)
```
this will preserve existing connections.

### adding multiple sockets in `sv_init`

i like seeing stuff like this. do more of this

```python
inew = self.inputs.new
inew(socket_type, socketname1)
inew(socket_type, socketname2)

onew = self.outputs.new
onew(socket_type, socketname1)
...etc
```
if your socket has a property attached do
```python
inew = self.inputs.new

# when just a prop_name 
inew(socket_type, socketname1).pop_name="whatever"

# when several properties of the socket must be set
socketname = inew(socket_type, socketname2)
socketname.prop_name = ...
socketname.some_other_prop = ...

...etc
```
keep the references beyond `inew` and `onew` descriptive. and avoid reusing the same reference name repeatedly to avoid confusion.

### you want a slider movement to perform some action/computation before calling the node's process function.

We have many nodes that do this, especially nodes that change their mode as a function of some UI interaction with a property (usually an EnumProperty, but not exclusively ). Nodes that do this will not have a `update=updateNode` on the property in question, but instead they'll use a "wrapper". The wrapper will first execute some code, then call the updateNode function itself. Here's an abstract example

```python
def someNodeClass(...):

    def wrapped_update(self, context):
        ... do stuff ...
        self.process_node(context)   # or    updateNode(self, context)

    some_property: BoolProperty(update=wrapped_update)
```
   - calling `self.process_node(  )` in the above snippet is how i'd like to see all new nodes proceed. the `updateNode` function's only function is to call `self.process_node` anyway. To be clearer; `updateNode` is only to be used directly in a property declaration when attaching the function to the `update` attribute like `update=updateNode`.

for more examples search the repo for `wrapped_update`

### Math

formerly `Vector*Matrix` was allowed, you must now do `Vector @ Matrix`,  or `Matrix @ Vector` (depends what your looking for)

### Complexity of UI code

The internal algorithms used in your node to process incoming data into new output, can be as complicated as you want. That's not ours to interfere with. The code you write to modify the UI based on the node's state is something we like to give advice on, hit us op if your node has much dynamic interactivity. "there's always a better way".

----

## modifying existing nodes

if you plan to introduce new sockets, then add them to the end of the socket lists (self.inputs, or self.outputs) , 

good
```diff
self.inputs.new(_type, existing_socket_1)
self.inputs.new(_type, existing_socket_2)
+ self.inputs.new(_type, new_socket)
```
bad
```diff
+ self.inputs.new(_type, new_socket)
self.inputs.new(_type, existing_socket_1)
self.inputs.new(_type, existing_socket_2)
```

The reason is because links between nodes tend to be stored by index, and not socket name.

----

## Optimizations

This is not something you want to ignore. Some of this advice is deep and some is superficial. It will happen that you optimize code early and make it more work later when you or someone else wants to extend the code's behaviour. This is something I can't teach, i suck at it often, but I can warn you about that annoying feeling you get telling you to just "leave it" before trying to make the code more condensed. If your change doesn't make the node faster, or more readable - stop.

### Readability

_link checking_

but first. some simple readability stuff. The following snippet exists all over in Sverchok. We check if a socket is linked before calling `sv_set` on it.

```python
if self.outputs['Verts'].is_linked:
    self.outputs['Verts'].sv_set(vertList)
```
If you've already calculated `vertList`, just skip the first test, pass the data reference anyway. There is no speed gain added by the first test. Less typing, less reading.

```diff
-if self.outputs['Verts'].is_linked:
self.outputs['Verts'].sv_set(vertList)
```

_aliases_

whenever possible alias a lookup. You can use the alias repeatedly in the rest of the function logic, instead of bloating the function code with `bracket` or `dot` look-ups
```python
verts_socket = self.inputs['Verts']

if verts_socket.is_linked:
    verts = verts_socket.sv_get()
```

## Submitting code

Before we accept code, either new code or changes to code, we will look at it first. If there's anything in  the Pullrequest that gives us hesitation, we'll comment on the lines in question. If the PR wants to change a core module or utility we'll give it closer scrutiny. If your code will cause existing .blends that use that node to behave differently we'll suggest ways around that.

Sverchok has some code that hasn't changed much since 2014, and that means some nodes are old and not exactly examples of best practices. When you study the code of nodes for inspiration, take the file date stamp into account.

**Comment by zeffii** [comment]
i'll turn this into a wiki page / add to docs.

**Comment by zeffii** [comment]
## to deepcopy or not to deepcopy, that _is_ the question

Nodes that use `sv_get(deepcopy=False)` should pay attention to what they do with that data
- do not modify the incoming data if deepcopy=False,  (this includes using Fulllist.. to pad incoming data to match a desired length ) , *Use `fullList_deep_copy` instead.*

**Comment by zeffii** [comment]
## Style Guide

beyond syntactically correct code, it's good practice to keep a homogeneous aesthetic about our code. Below will be some examples of awkwardly formatted code vs convention.

```python
# no
    z_ = FloatProperty(name='Z', description='Z angle',
                            default=0.0,
                            options={'ANIMATABLE'}, update=updateNode)
# yes
    z_: FloatProperty(
        name='Z', description='Z angle', default=0.0, update=updateNode)
```
- all properties are by default 'ANIMATABLE', it is a redundant statement
- the arbitrary indent in the top property definition tends to become more arbitrary when the property types changes, the indentation will hop all over the place, just indent to one deeper than than the variable/annotation name and you'll be good.
- technically the pynodes API doesn't force you to add the default value, but in Sverchok we find it useful for introspection and comprehension
- the name parameter, yes please use that :)

**Comment by songproducer** [comment]
I tried to install on Blender 2.8 but got this:

> Traceback (most recent call last):
>   File "/Users/leotreasure/Downloads/blender-2.80.0-git20181204.1b6a394d862-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/__init__.py", line 77, in <module>
>     imported_modules = init_architecture(__name__, utils_modules, ui_modules)
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/core/__init__.py", line 99, in init_architecture
>     import_settings(imported_modules, sv_name)
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/core/__init__.py", line 80, in import_settings
>     settings = importlib.import_module(".settings", sv_dir_name)
>   File "/Users/leotreasure/Downloads/blender-2.80.0-git20181204.1b6a394d862-x86_64/blender.app/Contents/Resources/2.80/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/settings.py", line 8, in <module>
>     from sverchok.core import handlers
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/core/handlers.py", line 10, in <module>
>     from sverchok.ui import (
>   File "/Users/leotreasure/Library/Application Support/Blender/2.80/scripts/addons/sverchok-master/ui/viewer_draw_mk2.py", line 36, in <module>
>     from bgl import (
> ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)
