### ISSUE TITLE
Int and Float range with zero step

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2302]
Hi everybody, I've spotted some issues with Float Range Node, when a Step=0 is used. It uses 1 instead of 0. 

![immagine](https://user-images.githubusercontent.com/6708848/48129317-70765400-e289-11e8-8618-6ae01efa0507.png)

Also, the equivalent Int Range Node is actually called Count instead of Step (I think it could be a bit confusing):

![immagine](https://user-images.githubusercontent.com/6708848/48129559-29d52980-e28a-11e8-9518-245d073364fe.png)

and it gives an error when a zero Step is used:

![immagine](https://user-images.githubusercontent.com/6708848/48129585-407b8080-e28a-11e8-853e-9d052ea350e5.png)

**Comment by zeffii** [comment]
you expecting `[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...]]`  ?

**Comment by zeffii** [comment]
> Also, the equivalent Int Range Node is actually called Count instead of Step (I think it could be a bit confusing):

it's been this way for 4+ years, i'm going to have to disagree. ...but maybe i stopped thinking about it a long time ago :)

**Comment by alessandro-zomparelli** [comment]
Hi @zeffii , thanks for your answer!
Yes I was expecting a series of zeros. For instances I'm using that range for controlling the rotation of a series of circles, but when I change the value I'm not able to reach the zero rotation, it's a bit wierd I think... 

Regarding the "Range Int" (Count or Step) I think that it's not a big deal, I just noticed that the meaning for "Range Float" and "Range Int" is different. You can keep it in that way and I think that people will easily figure out how to  use it, maybe nobody will notice it :P 
I have noticed it because I was comparing the two nodes for the "zeros thing" :)

**Comment by zeffii** [comment]
I've also thought of making the Count mode do zero steps, so i'm feeling that point of view.

**Comment by zeffii** [comment]
maybe you want to do a pullrequest for this feature, and make the new output optional. (N-panel, draw_buttons_ext  can be used for the Boolean to switch it on or off.

I'll make it default behaviour in `sv for 2.8`

**Comment by alessandro-zomparelli** [comment]
> 
> 
> maybe you want to do a pullrequest for this feature, and make the new output optional. (N-panel, draw_buttons_ext can be used for the Boolean to switch it on or off.
> 

Hi @zeffii , sorry, maybe I didn't get it, but why people should want to use a different step value instead of the specified one? If you set 0, then you should expect 0 step, no?

**Comment by zeffii** [comment]
then it comes down to terminology.  "range" to us implied a "set of equally spaced numbers".

there may be .blends out there that erroneously rely on the output of step=0 (internally converted to 1 as you've noticed). so then we decide is it OK to fix something ... and break some blends?

if @nortikin is OK. i'm OK too.  You do a PR and make the 0=step output a repeat value of `start`, i'll be happy to accept it.  And i'll implement it in sv for b2.8 too.

**Comment by alessandro-zomparelli** [comment]
I see, I didn't thought about blends files based on that...  now I see your concerns. Maybe we can just change it for the 2.8...

**Comment by zeffii** [comment]
in sv for b28

![image](https://user-images.githubusercontent.com/619340/48661926-27d54c80-ea7a-11e8-9abf-6414a2081e14.png)

**Comment by zeffii** [comment]
check the few lines in float range / int range nodes, if you want to backport to Master.
