### ISSUE TITLE
Spiral generate Lists instead of Tuples

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2304]
Dear all, 
I've used a lot the node Spiral lately and I found a minor issue with the type of data generated. Instead of generating Tuples, it generates vertices as Lists:

![immagine](https://user-images.githubusercontent.com/6708848/48337715-fd435800-e663-11e8-9678-20df6e9b1ace.png)

Anyway this node was really usefull for generating continuous paths for 3D printer!

**Comment by zeffii** [comment]
I don't think we technically have a convention to force nodes to use `lists` or `tuples` for the vectors.

**Comment by zeffii** [comment]
Your nodes can use whatever they want (tuple or list). There are cases to be made for all the mentioned enclosures (List, Tuple, Vector). We did some speed testing a few years ago and found generating vectors was a little slower than using generics. I would not be surprised if we tested that hypothesis from a different angle that we could get different results and opinions. (like: using Vectors in the whole tree would make vector math less verbose, by calling methods on the vectors...) 

efficiencies noted in python `3.1` for tuple over lists or vice versa may be different now for `3.7`.

... but `numpy` blows all of it out of the water :) If we wanted speed as a primary target that's where it's at, but for now we seem to have settled on generics.

good question..

**Comment by zeffii** [comment]
the node tree is only as fast as the slowest node, so when we do a lot of casting in and out of vector or `np.array` that's going to hit performance.

what would be awesome is if the `bmesh` accepted np.array, and outputting np.array if it encountered np.array as input. oooh man.

**Comment by DolphinDream** [comment]
we can perhaps add this to convert from list to tuples right before appending to the output lists.

`                verts =[tuple(v) for v in verts]
`

**Comment by zeffii** [comment]
optional, by default off. it's just extra processing

**Comment by alessandro-zomparelli** [comment]
@zeffii Yes I was thinking about passing Vectors through sockets in the NodeTree.
For math operations you don't have to cast them and Bmesh can directly use them.
Also it prevents "misunderstanding" between Lists and Vertices. I know, lately I'm always proposing big changes, but to be clear I absolutely respect and love the work done so far. It's just for talking, evaluating and maybe collect some ideas for the next versions of Sverchok :P

@DolphinDream can't I just change the lines with: 
```
addVert([x, y, z])
```
Just using tuples there? It shouldn't cause any problem right?

**Comment by DolphinDream** [comment]
@alessandro-zomparelli That’s what I thought too initially, but that won’t work since there is a call later, after generating the vert lists, to a method to normalize the verts in place and if they are tuples you can’t change the verts values. That normalization method would have to make a copy of the list during normalization if the verts are stored as tuples.

**Comment by zeffii** [comment]
> always proposing big changes,  (Vectors)

i'm happy to entertain ideas. but to move towards action would require speed testing a non trivial nodetree in two version of Sverchok ( 1.current sverchok 2. modified sverchok )

i'd prefer to potter around doing the 2.8 conversion for a while :)

**Comment by DolphinDream** [comment]
The question is what node restricts the vertex input to tuples only ? 

Also, I wonder if this list-tuple conversion “feature” could be implemented at the lower level for the vertices string output socket and allow it to convert to tuples optionally (the option could appear on the property panel for the nodes that have vertex output.)

**Comment by DolphinDream** [comment]
Alternatively one could create a list to tuple node :)

**Comment by zeffii** [comment]
> The question is what node restricts the vertex input to tuples only ?

i forgot to bring that up. nodes should not be so fussy about the input. list and tuple should both be accepted. If there are problems with nodes or node combos then those are things I'm obliged to get fixed.

> named tuple

the reason we don't use that for vectors is because it's initial implementation was in python, and introduced some overhead, this may have changed in python 3.7 . Also ideasman had his cautions about it.

    > (2011) " my main annoyance with named tuples is they're implemented in python so they're not as fast as builtin types like dicts."

**Comment by DolphinDream** [comment]
@alessandro-zomparelli what is the reason you need the verts to be output as tuples ?

**Comment by alessandro-zomparelli** [comment]
@_@ Black Magic!
Not exactely what I need but I'll study, thanks!
I needed 3 levels: 1 is main, 2 is vertices lists (one list = one curve), 3 is vertices' coordinates (x,y,z). With your code I get only one big curve.

**Comment by nortikin** [comment]
that it. numpy, as i understand, gives more flat array, but we need sometimes subdivisions and representation in sublevels to have separate objects. it means more to know math, what i am weak in.

**Comment by zeffii** [comment]
mind if i close this as a bit of a non-issue?
