### ISSUE TITLE
UPDATE: Maybe Sverchok logo twisted S

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2306]
<img width="1023" alt="screen shot 2018-11-13 at 6 29 16 am" src="https://user-images.githubusercontent.com/3952687/48370498-a4c89500-e70d-11e8-8657-aeabeabe1f36.png">

<img width="630" alt="screen shot 2018-11-13 at 6 28 25 am" src="https://user-images.githubusercontent.com/3952687/48370449-75b22380-e70d-11e8-84e1-fff76dab3482.png">

Just an idea... there is probably pretzel like logo similar to this out there already, but kind of like Snake twisting itself. Maybe it can be more intricate.

**Comment by nortikin** [comment]
lets go around current icon with 3d-zation
