### ISSUE TITLE
Q: Is there SV node that simply "repeat matrix on certain normal"

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2307]
I got this setup, but I think it can be made more elegant, I am looking for a simple way to repeat Matrix with offset by the normal, similar to Array Modifier.

[grease_echo_009.blend.zip](https://github.com/nortikin/sverchok/files/2575262/grease_echo_009.blend.zip)

<img width="1155" alt="screen shot 2018-11-13 at 7 25 48 pm" src="https://user-images.githubusercontent.com/3952687/48400239-f149ba00-e779-11e8-98af-30053be7710e.png">

I thought Matrix Normal was kind of doing it, but not really. There must be something I missed.

**Comment by zeffii** [comment]
maybe you should write a script node

**Comment by Durman** [comment]
@enzyme69 
![2018-11-13_15-00-11](https://user-images.githubusercontent.com/28003269/48409300-e4669f80-e754-11e8-9bed-232a586e0a5a.png)
[grease_echo_009_2018_11_13_11_00.zip](https://github.com/nortikin/sverchok/files/2575914/grease_echo_009_2018_11_13_11_00.zip)

**Comment by enzyme69** [comment]
Aaah... vector interpolation.. yes, will take a look thanks!!

**Comment by nortikin** [comment]
will be maybe line mk3 able to make it easier now

**Comment by zeffii** [comment]
why not matrix array node ? : ) i'll make one for b2.8
