### ISSUE TITLE
How to write custom Sverchok node?

### ISSUE THREAD

**Issue by romanvolodin** [nortikin/sverchok#2311]
While Script Node Lite has a lot of pros, it also has two huge cons (at least for me):

- it changes manually set values to default  when I duplicate SN Lite node or reopen blend file.
- it's hard to debug. For example, I have 2 modules imported, one of them imports 8 more modules. In which module this error?
```
Unexpected error: <class 'ZeroDivisionError'>
on line:  26
Traceback (most recent call last):
  File "/home/roman/.config/blender/2.79/scripts/addons/sverchok-master/nodes/generator/script1_lite.py", line 398, in process_script
    exec(self.script_str, locals(), locals())
  File "<string>", line 43, in <module>
ZeroDivisionError: float division by zero
```

So I want to convert my SN nodes to real Sverchok nodes. It will give me all possible properties (BoolProperty for example, I don't like use 0/1 int instead) and full python trace back.

The main question is - how to conveniently debug node while coding? For now the only way I know is to reload blender over and over again. It's just a pain.

Other questions:
- which methods sv node must have? Is there a list of such methods?
- Is the a common practic of how to read input data? Type, nesting, length and so on. Ready-to-use functions maybe.
- Same for outputs.

Please share best practics.

Custom nodes documentation is too short and outdated. I do understand that I can answer my question by digging in existing nodes for couple of weeks. But I just don't have these weeks :)

**Comment by zeffii** [comment]
I would love to upload what I know into your brain and be done with it. Or point you to a really detailed explanation of how to do write a simple node. But we don't have such tutorials, we expect people interested and compelled enough to write their own node,  to be able to sift through the nodes in `sverchok/nodes/*/*.py`  and form their own map of what is required. and how to do stuff.

I suggest you should look at the source of the simpler nodes. look at multiple nodes so you form patterns in your head about what goes where.

1.  add your properties at the top, inside of the node class (provide a `update=updateNode` to any of these properties that need to trigger calculations)
 2.  add your sockets in `sv_init`
3.  in `sv_init` you can ad `.prop_name` to a socket to make the associated property available as a slider
4.  use `draw_buttons` if you want properties available that you don't want to provide as sockets.
5.  the `process` function is where you 
      - get the incoming socket data
            `socket_data = self.inputs[socket_name].sv_get()
      - handle the data combined with property states
      - and set the outgoing sockets with the resulting data
            `self.outputs[socket_name].sv_set(your_processed_data)

you don't strictly need to use "update" or "update_socket" functions, but some nodes with dynamic sockets / socket changing types may find those functions useful.

**Comment by zeffii** [comment]
> In which module this error?

i see your point, the error does talk about 3 places in the code where that error might be. I bet i'd find it if it bugged me enough.

your conclusion to want to try a custom node is I think worthy of your time. You can certainly post your working / non-working code here for advice.

**Comment by zeffii** [comment]
>  I do understand that I can answer my question by digging in existing nodes for couple of weeks. But I just don't have these weeks :)

that won't take weeks. start somewhere, knock some code out...paste it here, and one of us might find time (in _our_ busy schedule) to answer specific questions.

**Comment by romanvolodin** [comment]
Thanks for yous answers, Dealga!

This one already can be added to the Sverchok's manual - https://github.com/nortikin/sverchok/issues/2311#issuecomment-438736636

> I bet i'd find it if it bugged me enough.

Already solved it =)
I do understand that SN Lite is kind of prototype node (I mean it's for checking thoughts and ideas). But the edge where your prototype become your day-to-day tool is very thin =)

Thanks one more time.

**Comment by romanvolodin** [comment]
> The main question is - how to conveniently debug node while coding? For now the only way I know is to reload blender over and over again. It's just a pain.

Turned out it's quite simple - just press ```F8```
More info here - https://blender.stackexchange.com/questions/2691/is-there-a-way-to-restart-a-modified-addon

**Comment by zeffii** [comment]
`F8` may not reload external modules, so if you edit something and hit f8 and you feel that something should change but didn't then you restart blender :)

I have been thinking about doing another iteration of snlite. with a fixed set of preregistered variables/properties. not sure it would  solve your problems but it would maybe be as close to a custom node as we can get.  more about this in a different thread.

**Comment by romanvolodin** [comment]
> F8 may not reload external modules, so if you edit something and hit f8 and you feel that something should change but didn't then you restart blender :)

Oh, good to know, thanks!

**Comment by zeffii** [comment]
i'm gradually updating the guidelines for 2.8 node development. closing this for now. most is the same.
