### ISSUE TITLE
Evaluate Image First Look -- missing Alpha and conundrum

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2313]
I am testing the new Evaluate Image node @alessandro-zomparelli  and realized it's missing Alpha sampling, only RGB is being outputted, but funny thing is when I am adding my own Alpha value to the Color In node, I seems unable to assign value back to my box duplicates... weird.

[image_evaluate_014.blend.zip](https://github.com/nortikin/sverchok/files/2591045/image_evaluate_014.blend.zip)

So more like feedback:
- Would be nice to have Alpha / A out, besides R G B.
- Grayscale maybe nice also :D 

Thanks!

**Comment by enzyme69** [comment]
I experience this a couple of time in the past... similar to Image Decompose node back then.

<img width="1091" alt="screen shot 2018-11-17 at 9 15 03 am" src="https://user-images.githubusercontent.com/3952687/48650178-48d17980-ea49-11e8-90e8-df0faae4f068.png">

**Comment by enzyme69** [comment]
Objects was sorted wrongly:
https://github.com/nortikin/sverchok/issues/1987

And back then Zeffii did something but still import re is not possible..

<img width="848" alt="screen shot 2018-11-17 at 9 34 38 am" src="https://user-images.githubusercontent.com/3952687/48650859-2f7dfc80-ea4c-11e8-82a9-e564aa2ab6f4.png">

This shall fix it.

**Comment by zeffii** [comment]
@enzyme69  ,  it's better to keep on topic.  start another thread if you want about the object sorting. it's a valid issue, but perhaps you understand it is entirely independent from the features you feel are missing from the image node.

**Comment by alessandro-zomparelli** [comment]
@enzyme69 I've added both alpha and grayscale. Pull request already sent.

**Comment by enzyme69** [comment]
Thanks @alessandro-zomparelli Will check~

**Comment by enzyme69** [comment]
@zeffii Yes you are right again, I will keep in mind.
