### ISSUE TITLE
freeze on load setting VCols with VertexColorsMk3 in B2.79 Py3.7 Mac (beta mojave)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2316]
I have recently noticed a random frozen while using Blender 2.79 with Python 3.7 on my Mac. I used to ignore this bug but this one is in particular annoying because it freezes as soon I open the Blend.

It's probably one of those things that is really hard to explain, potentially because:
- I have multiple Python installed on my Mac (Python 2 and 3) without virtual env.
- I am using beta version of MacOS Mojave (like latest one non official)

It does not seem to freeze Blender 2.79 with Python 3.5.3. (Blender Official)

[evaluate_monalisa_008.blend 2.zip](https://github.com/nortikin/sverchok/files/2593251/evaluate_monalisa_008.blend.2.zip)

<img width="980" alt="screen shot 2018-11-19 at 8 26 19 am" src="https://user-images.githubusercontent.com/3952687/48678245-cfff2880-ebd4-11e8-8eb4-a121acdc968a.png">

Vertex Color in latest Blender support Alpha, RGBA, the reason I am using 2.79 with Python 3.7 but this one crashes and frozen a lot, in my latest video.

Can anyone try opening the BLEND above on their Mac or PC and see if it is frozen right away? 

There is no explanation, and Blender did not crash, just frozen... something weird bug.

**Comment by enzyme69** [comment]
I am keeping a different version of the BLEND. 

This one was still working without frozen issue...
[evaluate_monalisa_006.blend.zip](https://github.com/nortikin/sverchok/files/2593256/evaluate_monalisa_006.blend.zip)

And I can't remember doing anything funky, just zooming in and out of node tree, and then BOOM, Blender is frozen, reopening the BLEND totally froze Blender again and again.

**Comment by zeffii** [comment]
[this issue](https://github.com/nortikin/sverchok/issues/2269) might be related

**Comment by zeffii** [comment]
not super sure i want to spend time on this if it works in the official blender, but not in nightly. You can take a deep breath and try these modifications to a `vertex colors mk3` node. 

https://github.com/nortikin/sverchok/pull/2317/files

## do not commit this patch. just test the changes locally, do not save .blend with these changes. it's just a test. "
