### ISSUE TITLE
Is it possible to use Monad Loops to create multiple 2pt Spline Curves?

### ISSUE THREAD

**Issue by ben-mkiv** [nortikin/sverchok#2325]
## Problem statement
I want to create a procedural Leaf. So i made a Monad group which should generate Spline Curves from the main vain of the Leaf to the Leaf edges, and at this point im not sure if thats even possible or if my setup is wrong)

## Expected result
Multiple Curves

## Actual result
One Curve which changes its position based on the amount of Loops i've set to run

## Sverchok version
tried with current Master and 2.8 prerelease

This is my Monad node Setup: (it's feed with the vertices from the main vain as vertices.1 and with the vertices from the edges as vertices.2, the edge inputs are just there to get input/output node types the same as this was stated to be required in another issue, resolution is for vertex count of the spline and offset is just to not start at the first vertice of the leaf edges)

![Node Setup](http://pasteall.org/pic/show.php?id=b9015c8c3aa3df1dede1c1b9b42e8cf7)

**Comment by zeffii** [comment]
maybe monad-master @Durman knows :)

**Comment by zeffii** [comment]
the 3pt spline node is vectorized, so.. you can do this:

![image](https://user-images.githubusercontent.com/619340/49389113-d1c50200-f725-11e8-9dc9-0eea67088723.png)

**Comment by ben-mkiv** [comment]
thanks much for the quick response, i wasn't aware that i can use the range node to create multiple curves :)
