### ISSUE TITLE
Installation of sverchok for Blender 2.80

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2326]
## One you have it installed. Do Not press update / upgrade ..  it will not work as expected.

The following instructions should get it running

- download the zip from [here](https://github.com/nortikin/sverchok/archive/b28_prelease_master.zip)
- unpack the zip somewhere (desktop for now)
- the resulting Folder/(with content) will be `sverchok-b28_prelease_master`, you rename that just to `sverchok`.
- drag the resulting folder into your 2.80/scripts/addons_contrib, so you get
   
    ![image](https://user-images.githubusercontent.com/619340/49426797-e646e000-f7a1-11e8-9d00-a4c02f5db1f7.png)

- then enable sverchok.

_Originally posted by @zeffii in https://github.com/nortikin/sverchok/pull/2299#issuecomment-444005102_

**Comment by zeffii** [comment]
closing this.. but you can use it to link to people who may not be comfortable with the process. If it's missing precise statements, consider editing the text,

**Comment by zeffii** [comment]
can anyone that uses Sverchok from the zip this way, tell me once they've installed the `b28_prelease_master` - does the update function work now?   i hard coded the path... it should download `b28_prelease_master ( current version ) `

**Comment by hitrpr** [comment]
Да, вот так установилось нормально! Win7 x64
