### ISSUE TITLE
Shader not working on b28_prelease_master?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#2331]
## Shader not working

Trying to test the new shader feature, i used this shader:

>```python
> vertex_shader = '''
>     uniform mat4 viewProjectionMatrix;
> 
>     in vec3 position;
>     out vec3 pos;
> 
>     void main()
>     {
>         pos = position;
>         gl_Position = viewProjectionMatrix * vec4(position, 1.0f);
>     }
> '''
> 
> fragment_shader = '''
>     uniform float brightness;
> 
>     in vec3 pos;
> 
>     void main()
>     {
>         float a = floor(sin(pos.x * 5.2)*0.8 + 0.4)
>         float b = floor(sin(pos.y * 7.2)*0.8 + 0.4)
>         float b = floor(sin(pos.z * 1.6)*2.2 * brightness/0.7)
>         gl_FragColor = vec4(a, b, c, 1.0);
>     }
> '''
> 
> def draw(context, args):
>     geom, config = args
>     batch = config.batch
>     shader = config.shader
>     shader.bind()
>     matrix = bpy.context.region_data.perspective_matrix
>     shader.uniform_float("viewProjectionMatrix", matrix)
>     shader.uniform_float("brightness", 0.5)
>     batch.draw(shader)
> ```

with internal scripting but nothing happens as expected... what is wrong?
## Steps to reproduce

1. create a torus and VD experimental node, connect them. 
2. past the code in the text scripting field, select the script in the VD experimental node.
3. run the script(?)

## Expected result

What did you expect to see as a result of those steps?
A torus with a chessboard texture.

## Actual result

What did you actually get?
the standard display as that in the VD experimental code.

## Sverchok version

the 2.8_prelease_master branch

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

Probably something that i missed or changes in the code....

**Comment by kalwalt** [comment]
related to https://github.com/nortikin/sverchok/pull/2299

**Comment by zeffii** [comment]
your fragment shader lines must definitely end in ` ; `

**Comment by kalwalt** [comment]
@zeffii you are rigth, but this not change nothing...sigh!

**Comment by zeffii** [comment]
nope. i agree. " this was working two days ago"  :)   hahah  i'll have to have a look later. i may have messed up some plumbing :(

**Comment by zeffii** [comment]
i don't _reallllly_ know .  i thought maybe 
- each symbol must have a space between it and the next..
- or line endings need `;`
- or redefinition of `float b`  

and that brings you to the use of the undeclared variable `c`  :)

**Comment by kalwalt** [comment]
@zeffii thank you! This explain why didn't works! 

> this may be a recent back-end development? because during development last week (older 2.8 build) i was informed nicely most of the time in the event of compilation failure. Maybe i'll stick a try/except somewhere..

Are you refering of back-end dev of blender 2.8?

**Comment by zeffii** [comment]
> Are you refering of back-end dev of blender 2.8?

yep. but I keep track of that area and didn't notice any changes. maybe I missed something.

if you add a `uniform_float` to the draw function but don't reference/use it in the shader, gpu will also fail to compile.

**Comment by kalwalt** [comment]
Also i can confirm that your code works! I'd like to know, as you say, why my code was wrong ( just to know...)

**Comment by zeffii** [comment]
it was wrong. because you reference a variable `c` that you don't define. you repeat `b` :)

**Comment by kalwalt** [comment]
> maybe it would be more appropriate to make a dedicated custom shader node, so the node has a lot less code and plumbing.. maybe add a shaderscripts folder.

This is a cool and smart idea, maybe like the scripting lite node?

**Comment by kalwalt** [comment]
I also saw that Texture viewer node is not yet available for the 2.8 version?  Something related to bgl new features? maybe i could open an issue for this also...

**Comment by zeffii** [comment]
that doesn't need a new issue. i'll tackle it tomorrow.

**Comment by zeffii** [comment]
i bet a fragment shader could easily draw the matrixviewer stuff too... or a texture

**Comment by kalwalt** [comment]
super news!
