### ISSUE TITLE
How to use Text In Node, with arbitrary literal data (like lists of lists of vertices)?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2332]
<img width="933" alt="screen shot 2018-12-13 at 11 40 09 am" src="https://user-images.githubusercontent.com/3952687/49907789-ea72ac00-fecb-11e8-8ec1-95da4681ff7c.png">

I am processing JSX camera data from Google Earth Studio using SV Text In, I wonder why it is really slow to calculate big value data (7 digits per value)?

Could it be faster at processing data?

**Comment by zeffii** [comment]
please supply the file you are loading into SV TextIn.

**Comment by zeffii** [comment]
judging by the screenshot, the format is `literal` (ie, not CSV, JSON or Sverchok-like ). So i'm surprised the Text In node reads it, maybe it just processes it and never reaches the end? Whatever the case, i would read this using `data = ast.literal_eval(total_string_content)`. And not any of the methods in TextIn.

**Comment by zeffii** [comment]
but. the sverchok mode set to Vertices can read a format like this
```python
[[[12, 24, 46], [16, 28, 40], [19, 32, 45]]]
```
you need an extra wrap to tell sverchok `list_of(list_of(vertices))`

**Comment by enzyme69** [comment]
[camera_position_002slow.blend.zip](https://github.com/nortikin/sverchok/files/2675321/camera_position_002slow.blend.zip)

I might be doing wrong thing with list [[]]

**Comment by enzyme69** [comment]
it's super slow that vector math does not work.

**Comment by zeffii** [comment]
wrap the data with an extra `[` and `]`. 

![image](https://user-images.githubusercontent.com/619340/49931743-d62cb000-fec7-11e8-9cb0-7aa53bf68e36.png)

**Comment by zeffii** [comment]
that textfile only has about 700 vectors, so i'm not experiencing any speed issues with correctly wrapped input.

**Comment by enzyme69** [comment]
<img width="753" alt="screen shot 2018-12-13 at 11 21 19 pm" src="https://user-images.githubusercontent.com/3952687/49938372-d19ae280-ff2d-11e8-8863-cb524f0a943c.png">

Ok my mistake very likely something with wrapping and joining the list .... cheers Zeff
