### ISSUE TITLE
Matrix is not read as Matrix()

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2336]
I am playing around with @nortikin Elfnor Tree Preset, I noticed that the Matrix output for Leafs is no longer working.

It's also pretty weird that I could see sometimes Matrix (list) is not seen as Matrix data.

<img width="1282" alt="screen shot 2018-12-17 at 9 01 51 am" src="https://user-images.githubusercontent.com/3952687/50059402-75101f80-01da-11e9-8e8c-b3bd6059afa3.png">

[elfnor_matrix_002.blend.zip](https://github.com/nortikin/sverchok/files/2684004/elfnor_matrix_002.blend.zip)

**Comment by enzyme69** [comment]
My feeling is that "Socket Convertor" node should do the job, but it does not.

**Comment by enzyme69** [comment]
I tried making my own Matrix using snippet of code stated here:
https://blenderartists.org/t/constructing-a-4x4-matrix-from-list-values/611359/4

But when I put this in Exec Node Mode, it does not seem to load the import math and from mathutils import Vector, Matrix, Euler properly.

**Comment by enzyme69** [comment]
Probably useful:
https://sinestesia.co/blog/tutorials/python-cube-matrices/

In my desperation I just add the Matrix convertor snippet:
[elfnor_matrix_008x.blend.zip](https://github.com/nortikin/sverchok/files/2684032/elfnor_matrix_008x.blend.zip)

But the rotation does not seem to work.

**Comment by zeffii** [comment]
The matrix socket used to contain lists of lists of 4 tuples, but @Kosvor2 converted all proper nodes to accept (and expect) lists of objects of type `mathutils.Matrix()` only. Therefore older nodescripts that don't output/input data in the matrix socket as a list of `[mathutils.Matrix,.....]`, won't be accepted correctly by the nodes you connect them to.

yes, this could be done with autoconverting, but it's perhaps simpler for everyone to make the nodescript more up-to-date and output `mathutils.Matrix()` to that socket.

I think you can probably just do
```python
mats_out = [Matrix(item) for item in mats_out]
```
no need for blah out.

**Comment by zeffii** [comment]
also.. why not ask @elfnor  :)

**Comment by enzyme69** [comment]
Thanks Zeffii!!! Will try~ @elfnor is mysterious~

**Comment by Kosvor2** [comment]
`mats_out =  Matrix_listing(mats)`

Matrix_listing() is what converts them into lists. This function must be removed from this script.

**Comment by Kosvor2** [comment]
https://github.com/nortikin/sverchok/pull/2337
