### ISSUE TITLE
Matrix socket output Matrix type ?

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2339]
I noticed that the nodes that output matrices don’t output lists anymore.. but mathutil Matrix type. Was this change made recently ?  Is this the recommended output type for matrices ?

<img width="495" alt="sv-matrixoutput" src="https://user-images.githubusercontent.com/2083719/50260438-0bf4fb80-03d6-11e9-8902-3576c5afcd8a.png">

**Comment by Kosvor2** [comment]
Yes. https://github.com/nortikin/sverchok/releases/tag/0.5.9.6.4

**Comment by zeffii** [comment]
6 months ago.

>  Is this the recommended output type for matrices ?

at this point, it's the only _acceptable_ output of the Matrix socket.

**Comment by DolphinDream** [comment]
Wow.. where have I been ? 😉  
What is the reason behind this change ? I suspect is has something to do with performance since we may unnecessarily convert back and forth from list to matrix. Is there more to it?
