### ISSUE TITLE
Vector Interpolation Nodes club

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2340]
Any reason why there are so many Vector Interpolation nodes? Can’t we stick with one?

<img width="389" alt="sv-vectorinrterpolationnodes" src="https://user-images.githubusercontent.com/2083719/50370035-5b216480-056d-11e9-846b-6211fdede937.png">

**Comment by zeffii** [comment]
the bottom left version I think could be deprecated, (MK1?)
the top right, LERP is a mix of two nodes, a granular node that doesn't try to be too clever.
the top left / bottom right (Mk2, MK3? ) maybe deserve better names to help identify their purpose.

The option is to merge the MK2/MK3,  or to give them more suitable names. There is a reason we haven't merged them.

The problem with nodes that have an enormous amount of variability and states / modes, is that the total amount of code that they encapsulate tends to expand, and become difficult to reason about. The more I code for sverchok, the more I appreciate those nodes that have simpler interfaces and static socket configurations. 

Just as with the notion that functions should do one thing, and one thing only. It's easier to give a name to a function to describe what it does, when its behavior doesn't drastically become modified by input switches.

**Comment by DolphinDream** [comment]
Having so many nodes for one purpose (vector interpolation) is confusing/frustrating since every time I want to do vector interpolation I have to stop and think which one I really want to use, which one has the function that I need. A better naming in this case is highly desirable. At a first glance the left top/bottom ones seem to be suitable for a merge into one node and perhaps renamed it Vertex Interpolation (?) since they evaluate/interpolate along the vectors/vertices in a list of vertices. The Lerp node interpolates between two vectors (or between two vectors lists) so maybe this can be renamed "Vector Interpolation". On this note, maybe the "Mix Inputs" node that I was working on a while ago, which I still need to finish, which includes the Vector interpolation as one of the Inputs it interpolates, may eventually replace the need of having a separate vector interpolator (lerp) node. I’m also working on Quaternion nodes, and the "Mix Input" node will cover Quaternion interpolation (sLerp) as well. Maybe the right bottom node could be renamed to something like “UV Vector interpolator” (?) or something of that nature (it’s not clear to me what exactly this node is used for so I can’t propose a more suitable name).

I general I agree with the philosophy of keeping node function to a minimum. Not only that it simplifies the code and the interface, but it also the keeps the purpose clear / less confusing for the user. However, I sometimes favor adding extra features in a node that the user may do frequently albeit with two or more nodes, this way it can minimize the size of the node trees, which I think it’s an important aspect of noding effectively (e.g. if I can add a “center” option to the line node instead, it may be better than (or maybe in addition to) adding a dedicated “centering" node). There is always a tradeoff.

**Comment by zeffii** [comment]
I think the main issue anyone will agree with is that we should not allow nebulous names like `Vector Interpolation MK1/MK2/MK3` in the future., where the names really don't help you remember their functionality, or their functionality don't help remember their names.

I made `Lerp` to encapsulate an older node and keep it simple.

**Comment by DolphinDream** [comment]
I think most would agree too that the node’s name  should be closely linked to its functionality. If you want to do vector interpolation then searching/typing either of the triggers (vector or interpolation) it should bring up the node names.

**Comment by DolphinDream** [comment]
This is what you get when you search for an “interpolation” node... some of the names are not even displayed in full, so I can’t even tell which node I’m picking until I pick one. (which may not be the right one)

<img width="383" alt="sv-searchinterpolationnodes" src="https://user-images.githubusercontent.com/2083719/50380000-b5cbc680-0628-11e9-8b6b-10d50dc84a4e.png">

**Comment by vicdoval** [comment]
Also the maybe the search menu could be wider? There could fit better explanations

**Comment by DolphinDream** [comment]
Yeah, I think @zeffii  had hinted a while ago to the idea of introducing a new interpolation category. The issue still remains in general. Maybe making the search box wider could alleviate such issues and would also allow to include more triggers into the mix.

**Comment by zeffii** [comment]
> Also the maybe the search menu could be wider? There could fit better explanations

that's something that i can't find any documentation for .. or examples.. else i would have force a minimum width for the search results to fit in longer descriptors.

**Comment by nortikin** [comment]
mk1 to remove and mk2 to rename (UV interpolation node), mk3 with tangent is really inerpolation, but if to add tangent to mk2, than we will have mk4 one node for both - U and UV also
