### ISSUE TITLE
ViewerDraw node viewport artifacts

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2342]
I found some issues with the ViewerDraw node .. (and possibly with Texture Viewer Lite node)

1. When the Texture Viewer Lite is in the node tree it seems that the ViewerDraw node has some rendering artifact in the viewport. (see demo). This could be related maybe to the Texture Viewer Node maybe missing to unbind the GL texture?

2. When spawning a ViewerDraw node (via right click menu for SV) from a generator node and then undo (ctrl+Z) the drawing in the viewport is not properly removed. It will only be removed once you reload the blend file (or start a new blend). The deletion of the viewer node directly does however remove its corresponding viewport drawing properly.

![sv-viewerdrawbugs-demo1](https://user-images.githubusercontent.com/2083719/50387078-5cb07100-06c2-11e9-8600-410fc3ae553b.gif)

![sv-viewerdrawbugs-demo2](https://user-images.githubusercontent.com/2083719/50387080-5d490780-06c2-11e9-854d-b98805180b4e.gif)

I’m using Blender 2.79b and ** version:  0.5.9.6, branch master, commit 2f660fa3  **

**Comment by zeffii** [comment]
the Blender undo feature doesn't seem to call the "free" function (whereas Deleting manually does...)

i might argue that that's a Blender bug.

**Comment by zeffii** [comment]
bpy.app.handlers.undo_post

**Comment by zeffii** [comment]
I added an operator to sv for 2.80, that essentially removes all callbacks and triggers a general tree update. The downside is you must manually trigger it.
The updside is that you only perform that excessive processing call once, in the (rare) event that you press ctrl+z and it wipes a viewer node.

**Comment by zeffii** [comment]
in 2.80 the app.handlers for `undo_post/pre` was broken, but [fixed now](https://developer.blender.org/T60247)

good chance i'll add appropriate handlers for 2.80, or maybe it's worth asking blender devs if they might be able to call free on a node before the undo-action removes it.

**Comment by zeffii** [comment]
as for the first issue. the "GL state being polluted" by texture viewer lite. if this happens with the normal texture viewer too, then both need a fix. if it's just the lite version then there's a slight difference in 'break down' (reset state) code. would be great if @DolphinDream could elucidate.  (i don't have 2.79 installed anymore )

**Comment by DolphinDream** [comment]
@zeffii well.. bad news.. the TextureViewer node has the same effect on VD viewport rendering it seems.

![sv-viewerdrawviewportartifact2-demo2](https://user-images.githubusercontent.com/2083719/51067447-600f8c00-15e0-11e9-9c82-fed121344b88.gif)

**Comment by DolphinDream** [comment]
Also.. this artifact disappears once you rotate the viewport camera. Also it doesn’t matter if the viewport is in orhto/perspective or whether it is in user camera point of view or one of  the top/bottom, left/right, front/back views.
![sv-viewerdrawviewportartifact2-demo3](https://user-images.githubusercontent.com/2083719/51067521-15424400-15e1-11e9-9504-f9d92fe7229f.gif)

**Comment by zeffii** [comment]
i propose that @Kosvor2 and @kalwalt  have a look at 
https://github.com/nortikin/sverchok/blob/master/nodes/viz/texture_viewer_lite.py

and that node's process function, when it goes into 'bgl' mode, and determin which of the GL state variables must be stored/restored before that function ends.

**Comment by zeffii** [comment]
```
bgl.glDisable(bgl.GL_DEPTH_TEST)
```
might need to do a glEnable(  ) on that value before letting go.
