### ISSUE TITLE
Issue with numpy array node - argument not passing integer values?

### ISSUE THREAD

**Issue by kalwalt** [nortikin/sverchok#2344]
## Problem statement

Please describe your problem here.
i create a tree node with different numpy array nodes, see the picture:
![schermata da 2018-12-24 19-19-55](https://user-images.githubusercontent.com/1275858/50405236-d4a99480-07b1-11e9-8207-8aec47c874ec.png)
the Custom numpy array node `np.random.rand(128, 128)` works as expected, i don't receive any errors, but if substitute with x and y values taken from the integer node `np.random.rand(x, y)` the node became red:
![schermata da 2018-12-24 19-22-20](https://user-images.githubusercontent.com/1275858/50405803-5b626f80-07ba-11e9-9223-d4552dee590e.png)
and the error:

> sverchok.core.socket_data.SvNoDataError: No data passed into socket `Data'
> 2018-12-24 19:21:50,343 [ERROR] sverchok.core.update_system: Node Numpy Array.001 had exception: an integer is required
> Traceback (most recent call last):
>   File "/home/walter/blender-2.79/2.79/scripts/addons_contrib/sverchok/core/update_system.py", line 325, in do_update_general
>     node.process()
>   File "/home/walter/blender-2.79/2.79/scripts/addons_contrib/sverchok/nodes/list_struct/numpy_array.py", line 58, in process
>     out.sv_set(eval("["+string+" for x,y in zip(X.sv_get(),Y.sv_get())]"))
>   File "<string>", line 1, in <module>
>   File "<string>", line 1, in <listcomp>
>   File "mtrand.pyx", line 1309, in mtrand.RandomState.rand (numpy/random/mtrand/mtrand.c:12099)
>   File "mtrand.pyx", line 829, in mtrand.RandomState.random_sample (numpy/random/mtrand/mtrand.c:9256)
>   File "mtrand.pyx", line 148, in mtrand.cont0_array (numpy/random/mtrand/mtrand.c:1893)
> TypeError: an integer is required

## Steps to reproduce

see above 

## Expected result

What did you expect to see as a result of those steps?
The values should be replaced without errors.

## Actual result

What did you actually get?
The numpy array node became red and error above.

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

From master 2.79

**Comment by kalwalt** [comment]
note that i can live with this issue, i can write a simple script like this:
```python
"""
in x s d=64 n=2
in y s d=64 n=2
out data s
"""
import numpy as np

data=np.random.rand(x, y)

```

and i am fine. Not sure if  you @zeffii should take some attention now, take just note...

**Comment by zeffii** [comment]
i will check it out, thanks @kalwalt  :)

**Comment by zeffii** [comment]
please use the 'A Number` node too btw.

**Comment by zeffii** [comment]
i think both numbers do need to be different?

**Comment by zeffii** [comment]
look at the code too @kalwalt , it's a simple node not equipped with clever interpretations (yet)

![image](https://user-images.githubusercontent.com/619340/50407321-0bdd6d00-07d5-11e9-8968-ea3977002297.png)

**Comment by kalwalt** [comment]
Thank you @zeffii, i see now, btw not obvious for me to use` x[0] or y[0] ` because the example show `x[y.argsort()]` and so i assumed that i should use like showed.
Anyway Merry Christmas!

**Comment by zeffii** [comment]
yep but if you see how the loop is constructed in the numpy node you see `x` is a list (even if its one item long), something like:
```python
data = [ <function x, y> for x. y in zip(X.sv_get(), Y.sv_get())]
```
also `x[y.argsort()]` is an index lookup of x by the return value(s) of `y.argsort()`, i think...

**Comment by zeffii** [comment]
I guess then you would write into the custom string box something like 
`[np.random.rand(xi, yi) for xi, yi in zip(x, y)]`
to get
```python
data = [[np.random.rand(xi, yi) for xi, yi in zip(x, y)] for x, y in zip(X.sv_get(), Y.sv_get())]
```

**Comment by zeffii** [comment]
and that totally makes sense.
![image](https://user-images.githubusercontent.com/619340/50536100-3c186900-0b51-11e9-8441-160e1c89a5d4.png)
