### ISSUE TITLE
Property Panel shows hidden input sockets

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2350]
Not sure if this is the intended behavior or it’s a bug.. For Quaternion nodes (in/out) I chose to hide/show input/output sockets when changing mode.. but this has an artifact (the QIN node) that shows all inputs created for the node(on the Property Panel) regardless of whether they are shown or hidden.

<img width="1181" alt="sv-pp-showhiddensockets" src="https://user-images.githubusercontent.com/2083719/50805887-545f5500-12c2-11e9-88c8-8ff051c7f8c1.png">

**Comment by zeffii** [comment]
that's out of our control.  tho it might be worth a bug report to blender.org

**Comment by zeffii** [comment]
or maybe we could convince blender devs to at least 'grey out' those sockets for which `socket.hide` evaluates to `True` in that panel.
