### ISSUE TITLE
Right click menu connects to hidden output socket

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2351]
This may be a bug.

For the Quaternion Math node I chose to show/hide output nodes based on operation selected. Some operations output quaternions, some scalar values. When right click on the node to connect the output to the stethoscope node the connection is made to the first output socket of the node regardless of whether this socket is visible or not, and if it happens to be hidden, the connection operation will automatically show the first output socket (even though this socket is not supposed to be visible for the current operation, hence it doens’t even get values). Perhaps the right click feature should link to the first visible output socket instead of to the first socket in the output list.

![sv-connecttohiddenoutputsocket-demo](https://user-images.githubusercontent.com/2083719/50806136-6392d280-12c3-11e9-8638-6ca31d852c18.gif)

**Comment by zeffii** [comment]
that's a valid issue.  i seem to be linking by index, rather than name.. 

something like this for stethoschope (because we can't get an event from clicking a socket)
```
for socket in self.outputs:
    if socket.hide:
        continue
    connect_stethoscope(socket)
    break
```

**Comment by zeffii** [comment]
right now the code looks like this
```python
        elif bl_idname_new_node == 'SvStethoscopeNodeMK2':
            # we can't determin thru cursor location which socket was nearest the rightclick
            # maybe in the future.. or if someone does know :)
            links.new(outputs[0], inputs[0])
```
perhaps
```python
        elif bl_idname_new_node == 'SvStethoscopeNodeMK2':
            # we can't determin thru cursor location which socket was nearest the rightclick
            # maybe in the future.. or if someone does know :)
            
            for socket in self.outputs:
                if socket.hide:
                    continue
                # connect_stethoscope
                links.new(socket, inputs[0])
```

**Comment by zeffii** [comment]
right now the code looks like this
```python
        elif bl_idname_new_node == 'SvStethoscopeNodeMK2':
            # we can't determin thru cursor location which socket was nearest the rightclick
            # maybe in the future.. or if someone does know :)
            links.new(outputs[0], inputs[0])
```
perhaps
```python
        elif bl_idname_new_node == 'SvStethoscopeNodeMK2':
            # we can't determin thru cursor location which socket was nearest the rightclick
            # maybe in the future.. or if someone does know :)
            
            for socket in outputs:
                if socket.hide:
                    continue
                # connect_stethoscope to first visible output socket of active node
                links.new(socket, inputs[0])
                break
```

**Comment by zeffii** [comment]
i've pushed what i think is a sane solution to 2.80. if you feel like porting.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/04e9a55e5e6c2bd951bc7b5b76ede713d97de1f6
