### ISSUE TITLE
Bounding box node failure

### ISSUE THREAD

**Issue by nantille** [nortikin/sverchok#2354]
## Problem statement

On b28_prelease_master, the bounding box node fails with message

2019-01-13 10:58:12,049 [ERROR] sverchok.core.update_system: Node Bounding box had exception: 'bpy_prop_collection[key]: key "Center" not found'
Traceback (most recent call last):
  File ".../Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master/core/update_system.py", line 325, in do_update_general
    node.process()
  File ".../Application Support/Blender/2.80/scripts/addons/sverchok-b28_prelease_master/nodes/analyzer/bbox.py", line 50, in process
    has_mat_out = bool(self.outputs['Center'].is_linked)
KeyError: 'bpy_prop_collection[key]: key "Center" not found' 

So I edited bbox.py to print self.outputs and this is what I get
<bpy_collection[1], NodeOutputs>
<bpy_struct, VerticesSocket("Vertices")>

The other output nodes are missing. I wanted to find out why and it's possible that self.outputs.new() fails in sv_init() for some reason but I don't know the details.

## Steps to reproduce

1. Open Blender 2.8 and go to Sverchok panel
2. Add any source of vertex data like Objects In mk3 and select an object in the viewport
3. Connect the Objects In mk3 vertices output to Bounding box vertices input
4. Connect the Bounding box vertices to another node that will use that dataset

## Expected result

The bounding box should display 4 outputs

## Actual result

Bounding box node is red and only shows one output "Vertices"

## Sverchok version

v. 0.6.0.0
branch b28_prelease_master

**Comment by zeffii** [comment]
ok. i'll look at it. thanks

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/51084767-ad4e4380-172f-11e9-8b3b-f00d87b03b17.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2299/commits/016ed7719c88ccd9d76ff1629f7dfac833eacc1d
