### ISSUE TITLE
Particles in b28

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2355]
I add it here as I found an issue that seems to be related to Blender 2.8, not Sverchok.

Issue: empty particle data

How: 
1. add an object on scene
2. add a particle system and tweak it to see particles in the viewport
3. now go to Sverchok and add a particle node
Expected: the particle node gives you the locations of the particles

Test: 
1. select your object and go in Console, 
2. write len(C.active_object.particle_systems[-1].particles) and it returns 0 (!...)

Done with latest January update of blender master repo.

So I suppose we have to wait for either an explanation on how to access particle data or a fix.

_Originally posted by @nantille in https://github.com/nortikin/sverchok/pull/2353#issuecomment-453829503_

**Comment by zeffii** [comment]
yeah, I don't know how permanent the particle API is in 2.80

**Comment by zeffii** [comment]
i will reopen this when there is more clarity from 2.80 devs

**Comment by nantille** [comment]
Well, it seems the workaround turned to be the way we have to access particle data from now on. They just closed now the tickets as they reached a consensus about that.
Bastien Montagne said "this should remain an exception (and a documented one)."
More details here https://developer.blender.org/T60083.

**Comment by zeffii** [comment]
if i'm not mistaken, it is for reading only.. not setting..?

**Comment by nantille** [comment]
I did a quick test and you can set values like the location of the particle *but* the position is not updated in the viewport. As long as you don't change frame in the timeline, the particle location remains the same as what you set in Python (I tried Psys with physics None and also with Newtonian). Now I don't know how to refresh the viewport. Calling bpy.context.scene.update() does nothing.

**Comment by zeffii** [comment]
OK. seems similar to the 2.79 'debacle' then :)  i'm sure there's a way to trigger a viewport update,   maybe `bpy.context.depsgraph.update()`

**Comment by nantille** [comment]
Yes, the particle system is Blender's orphan. It can do a lot of good things but it has issues that haven't been addressed in years, such as wrong rotations when emitting using face normals. Maybe after the release of 2.8...
Depsgraph has no update method so it's probably something else.

**Comment by zeffii** [comment]
maybe
```python
def tag_redraw_all_3dviews():

    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        region.tag_redraw()
```

from  ui/callback_view3d

**Comment by niarchou** [comment]
I encountered the same issue with the stable blender 2.80 version (blender-2.80-linux-glibc217-x86_64) and sverchok-b28_prerelease_master. Briefly:

1. Add particles to default cube
   Start frame: 1.000
   End frame: 1.000
   
2. Create a node tree with the following nodes:
   ParticlesMK2
   VD Experimental

3. Add the default cube to the Object slot of the ParticlesMK2 node and connect its outLocation to the verts slot of the VD Experimental node.

Nothing shows in the viewport and we can see that the ParticlesMK2 node outputs an empty list: 

![particles_before](https://user-images.githubusercontent.com/1999404/63636638-a6e75900-c67a-11e9-8dec-271563b8b1c4.png)

I tried the particles access method described in a more recent post and found that it works:
https://devtalk.blender.org/t/manipulating-particles-in-python/7552/2

I also noticed that `bpy.context` does not have a `depsgraph` attribute anymore.

I got the node to work in this case by using the above access method in particles_MK2.py:

```python
def process(self):
    O, V, L, S = self.inputs
    outL, outV = self.outputs
    degp = bpy.context.evaluated_depsgraph_get()
    evalO = [i.evaluated_get(degp) for i in O.sv_get()]
    listobj = [i.particle_systems[0].particles for i in evalO if i.particle_systems]
```

![particles_after](https://user-images.githubusercontent.com/1999404/63636642-acdd3a00-c67a-11e9-94ba-1a9a2d0adce9.png)

**Comment by zeffii** [comment]
instead, i think it might be possible to have something like

```
def process(self):
   deps = self.deps_graph
   ...

```
which could potentially work for nodetrees that don't get to complicated (ie not writing object data to the scene in the same sv nodetree as the sv particle nodes..)

calling `get_evaluated_depsgraph()` has a performance penalty, so we would preferably do it only once, per nodetree. per frame

**Comment by niarchou** [comment]
Thank you for your reply. In this case, the dependency graph could be cached in the node tree instance:

```python
class SverchCustomTree(NodeTree, SvNodeTreeCommon):

    ...

    @property
    def deps_graph(self):
        if getattr(self, "_deps_graph", None) is None:
            setattr(self, "_deps_graph", bpy.context.evaluated_depsgraph_get())
        return self._deps_graph
    
    @deps_graph.setter
    def deps_graph(self, value):
        setattr(self, "_deps_graph", value)

    ...
```
so that the node can access it by `self.id_data.deps_graph`. However, I found that when loading a saved .blend file, the depsgraph lost its references to objects during the second pass sometime between calling `process_tree()` and `sv_post_load(scene)`. The particle data are missing and making a change in the node tree or calling `update()` on the depsgraph after that, crashes blender. To get around this, I set the `deps_graph` property in `sv_post_load(scene)` where it iterates over node trees:

```python
@persistent
def sv_post_load(scene):

    ...

    for ng in sv_trees:
        if hasattr(ng, "deps_graph"):
           ng.deps_graph = bpy.context.evaluated_depsgraph_get()
        ng.freeze(True)

    ...
```
There are no further calls to `get_evaluated_depsgraph()` after that.

**Comment by zeffii** [comment]
i welcome you to submit a pull-request. to the `b28_prelease_master` branch, it seems you are interested in this (and we have other nodes that also need depsgraph access - ie Object In node.. for geometry modified by modifiers / shape keys )

**Comment by zeffii** [comment]
maybe branch `b28_prelease_master`, make the modifications, and we can experiment in the branch to get a few nodes working that way.

**Comment by niarchou** [comment]
Thanks, the changes are in pull request ##2511.

**Comment by gerroon** [comment]
Hi

Hiding a particle object in the viewport (closed eye) causes "key" error. Is this related? Hiding it in the viewport should not be an issue in my view, the depsgraph is related to "disabling" not "hiding"?


https://i.imgur.com/TPHbBx2.png

**Comment by Durman** [comment]
I remember that there was a decision not to support the node because particles will be outdated sooner or later.
