### ISSUE TITLE
Guidelines for node documentation "Example of Usage"

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2356]
Are there any guidelines regarding images referenced in the "Example of Usage" of the node documentation (*.rst files) ?

* Where should these images be posted so that the documentation generated based on the *.rst files finds them? 

* Should such documentation images be stored within the repo itself? 

* Any particular recommendation/guidelines for the SV theme to be used to capture the node trees? Is there even a need for consistency of theme for these examples?

* Any recommendation for the image sizes, aspect ratio? (since these will end up in a html documentation site maybe image sizes and aspect ratio is important?).  If the documentation generator tool does downsampling of the images then may the image size submitted with the node documentation doesn't matter as much.

* Who and when is the documentation updated so that the (Help&Doc Online buttons in the Property Panel takes you to an updated documentation site) ?

* Other considerations?

**Comment by zeffii** [comment]
definitely not appropriate to store images in the repo (it will balloon the size of the dl zip), but a side repo for images would maybe be OK. 

we have had discussions in the past about theme usage for the images used for docs, but it seems impossible to get everyone to use a single theme for docs, and switch back to their favourite when done. There were even experiments with an SVG exporter that interpreted ui drawing commands to generate a standard UI images and screenshot. But to be honest also that would turn into a massive side project to get reasonable coverage for all the crazy stuff we have going on.

image size / resolution... that's all unfortunate isn't it.

---- 

The node menu is quite heavily rearranged in 2.8 and i'm thinking about ways to auto generate the rst indices based on the files found in the various folder structures, which would remove a few more obstacles for including docs conveniently.

it's surely worth thinking about more optimal ways for 2.80, to encourage docs

**Comment by vicdoval** [comment]
I have been uploading the images to the Pull Request conversation, that way at least they stay sorted in place and time. 
There is also this issue that was used with that purpose: https://github.com/nortikin/sverchok/issues/394
I would suggest not to open another repo for the images, at least by this moment...

**Comment by DolphinDream** [comment]
I'm not suggesting to post images on github which may create the un-descriptive renaming. My suggestions was to store them in a separate repo with specific names.. then whatever script we use to generate documentation would clone both repos and construct the html documentation putting the images in the proper location to be served as html. 

example of what the documentation script would do:

* clone the main repo
git clone sverckock
git checkout master (or some tag version)

* clone the image repo
git clone sverchock-docImages
git checkout master (or some tag version)

* generate the html files
The script will generate html from *rst files found in the first repo and from the images found in the other repo. The images would be copied with the same name as they are stored in the image repo to a folder that can be posted online with the html files.

I don't think it's that complicated really. 

The image repo can have the same structure as the nodes so that the images are placed hierarchically as the nodes are stored within the main repo.. or perhaps it can have a flat hierarchy with subfolders for each node. Each subfolder would contain all the images related to one given node.


```
hierarchical:

images/
  ├── generators
  │   ├── line
  │   │   ├── line_example1.png
  │   │   └── line_example2.png
  │   └── plane
  │       ├── plane_exampl1.png
  │       ├── plane_exampl2.png
  │       └── plane_exampl3.png
  ├── lists
  │   └── list_join
  │       └── list_join_example1.png
  ├── matrices
  │   ├── matrix_in
  │   │   ├── matrix_in_example1.png
  │   │   └── matrix_in_example2.png
  │   └── matrix_out
  │       ├── matrix_out_example1.png
  │       └── matrix_out_example2.png
  └── vectors
      ├── vector_interpolate
      │   ├── vector_interpolate_example1.png
      │   └── vector_interpolate_example2.png
      └── vector_math
          └── vector_math_example1.png

or as a flat hierarchy:

images/
  ├── line
  │   ├── line_example1.png
  │   ├── line_example2.png
  │   └── line_example3.png
  ├── list_join
  │   └── list_join_example1.png
  └── plane
      ├── plane_example1.png
      └── plane_example2.png
```
