### ISSUE TITLE
Render Gallery 2019 - January to July

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2357]
To keep these issues shorter and more searchable, let us do half year galleries. 

(status of this issue is closed, because it doesn't need to appear in the issue tracker, it is pinned to appear prominently above)

**Comment by nortikin** [comment]
![post-dream](https://user-images.githubusercontent.com/5783432/51792893-eb844200-21c8-11e9-940e-5026e11df48b.png)
breaf - numbers are in sverchok
typography viewer

> The concept of "building without tenants" Imagine that you come to visit a friend, go to the entrance, like the right entrance, all right, see mailboxes, but one of them the number of the apartment, you climb... rise. But there is no end to mailboxes. No end. You meet the postman, and he tells you: "and here never and nebylo apartments, this building mailboxes."
> You can only leave messages, nothing else. 
> And then you realize that an angel is a messenger, literally a heavenly postman. And that our souls are already written in the book of life according to their merits. And that the place of residence on Earth is only temporary shelter, that we have no home other than the house of our Father. And that the sky is open before us on our ascending path. But who can? Gorodetsky Nikita Sergeevich.
> nikitron.cc.ua
> Two thousand nineteen
> Building area 100 m2
> No floors.
> There is no Elevator.
> The type of stairs H1.
> Building height 100 m
> Number of residents: 0 people.
> Electricity, water and heating are not provided.
> There is no roof.

**Comment by AG89z** [comment]
![cells](https://user-images.githubusercontent.com/26380268/53050940-d71b2880-349a-11e9-9713-a665825ca3a1.png)
![cells2](https://user-images.githubusercontent.com/26380268/53050941-d71b2880-349a-11e9-80d4-949719f77647.png)

**Comment by AG89z** [comment]
![metaball_sculpture](https://user-images.githubusercontent.com/26380268/53604557-17725900-3bb5-11e9-9e95-d99b9ef381a2.png)

https://www.youtube.com/watch?v=txl-YMwoAOY&t=1s

**Comment by portnov** [comment]
![fractal_curve_1](https://user-images.githubusercontent.com/284644/57974082-1b4f9380-79cc-11e9-8afd-0d02516d4cbe.png)

**Comment by portnov** [comment]
![fractal_curve_2](https://user-images.githubusercontent.com/284644/57974377-784d4880-79d0-11e9-86c1-b4cbd54f6afc.png)

**Comment by portnov** [comment]
![extruded_tubes2](https://user-images.githubusercontent.com/284644/58759410-cf136000-8542-11e9-9ace-9f5e9dfdbcd7.png)

**Comment by portnov** [comment]
![bevel_penta_rail_2](https://user-images.githubusercontent.com/284644/59206613-c06e1e00-8bbe-11e9-8c2c-7a53d77b858f.png)

**Comment by nortikin** [comment]
![chairs_01](https://user-images.githubusercontent.com/5783432/59551271-cf1e5180-8f7f-11e9-9b37-04f2f9359636.png)

**Comment by portnov** [comment]
![building_profile_1](https://user-images.githubusercontent.com/284644/59694719-81fde200-9202-11e9-8889-056db4cbe562.png)

**Comment by BennyGovaerts** [comment]
![Ngon area Mask flower inset trick_12bb](https://user-images.githubusercontent.com/49908008/60403159-0ef95180-9b9a-11e9-9b3b-2bf1eb197e84.jpg)
![Ngon area Mask](https://user-images.githubusercontent.com/49908008/60403162-22a4b800-9b9a-11e9-87ec-2a2cc6db3b7f.jpg)
