### ISSUE TITLE
Questions: Cylinder pattern and CSG afterwards in Sverchok

### ISSUE THREAD

**Issue by bakakouhai** [nortikin/sverchok#2358]
## Problem statement

As the titled said, there are questions here and only one issue. 

Suppose I want to create box with 4 holes, each at their respective corner. The origin of the coordinate system is at the centre, on bottom side of the cube. Is there a way to create a pattern (circular / linear) of the holes, made by cylinder generator?

Currently, I got my model made by:
1. making 4 cylinder
2. CSG-join them 3 times
3. and finally CSG-Diff the cylinders to the block.

The real model is far more complex than this (see in link, standardised part) and Blender needs about 1 -2 minutes to recalculate the mesh (unchanged vertices and subdivisions), even when I am not adding/connecting another node, e.g. drawing a connector to unused space and let go.

[https://www.emco-world.com/uploads/tx_commerce/pic_E1200_Test_UNI_ISO_10791-7_425x283_web_02.png](url)

I know that you can create duplicates by matrix input, but it only Viewer Draw or B_mesh create them.  Setting the object from Viewer B-Mesh to the CSG node is possible via B-Mesh-in --> B-Mesh-out --> CSG. However, using list join on the cylinder vector position cause the mesh to be created 4 times, for each hole.

There is also mesh and dupli-instancer, but they mess up the coordinates since I need to create one parent mesh at the right position and adjust the position of the other according to the parent, not the origin. 

Another question is which method is better for computation resources. Do I build the geometry first and do the boolean later (many Viewer B_mesh nodes) or do the boolean first and just visualise 1 final mesh (and draw).

One issue I have with Sverchok is that I cannot update it from Blender on my Mac. I use homebrew to install blender. probably that's why.

Kind regards

**Comment by zeffii** [comment]
I never considered the Sverchok/Python implementation of the CSG node as very useful for composite objects, because it produces unhelpful topology. (it's my fault that node exists)

I don't know if there is a best approach to your described problem, but what you could do is set up your objects in a blender scene first (including boolean modifiers), and then control the location/scale of individual objects via `get/set props` nodes.

it's not really a hard issue to solve, but we haven't made any convenience nodes that specifically make it easy to use the boolean modifiers without leaving the node tree.

**Comment by bakakouhai** [comment]
Noted. I will try to generate only the geometry in Sverchok then. CSG operations will be done using the modifiers. Thank you.

The screenshot below is the current model. The node editor is zoomed in to the hole part, only 2 holes. 

<img width="1440" alt="screenshot 2019-01-22 at 11 07 33" src="https://user-images.githubusercontent.com/39821914/51528148-4e2ab600-1e36-11e9-8104-67963b2ca2ea.png">

**Comment by zeffii** [comment]
This is a recurring question / topic, and I do have some interest in it. (I was experimenting with it as you posted the last comment). I might have time to offer a more "natural" sverchok based implementation, but it is not a priority, i don't want to get your hopes up.

**Comment by bakakouhai** [comment]
I will worry the topology part later, probably re-mesh the geometry or shrink-wrap trick I do not yet try. Of course, quads are preferred. This is my first month trying blender, moving from CAD based software.

The reason I am doing this is because inspections systems nowadays are working with point clouds. Even if I create the model in as CAD, when imported to the inspection software, it is still triangulated, which I do not have much freedom compare to modelling it from scratch in Blender.

The boolean operation I am doing represents the machining operations. This modelling system is called feature based parametric modelling such as FreeCAD. I am currently happy that Sverchok give the ability to edit the mesh parameter after it is created. Last time I need hours just to make a shaft since Blender use destructive modelling. I even cannot specify the correct fillet radius using bevel.

**Comment by zeffii** [comment]
all these things are interests of mine too ( CAD/CAM ) , Blender is from the beginning not aimed at precision modeling, but can achieve adequate results as a visualization tool. Blender's 32-bit float precision does have limitation when applied to large scale objects where also microscopic measurement tolerances are needed.

**Comment by zeffii** [comment]
again in b28 : 
![image](https://user-images.githubusercontent.com/619340/51536354-930d1780-1e4b-11e9-8ea0-f95b34e17608.png)

**Comment by bakakouhai** [comment]
They looks fine to me. Will try to use Object ID out then. I cannot just open my 2.79 model on 2.8. The node is there, but it does work, even from viewing the initial generator.
<img width="1440" alt="screenshot 2019-01-22 at 13 54 46" src="https://user-images.githubusercontent.com/39821914/51537142-09ab1480-1e4e-11e9-9e5e-c817d20c769b.png">

**Comment by bakakouhai** [comment]
* does not work

**Comment by zeffii** [comment]
Sadly Sverchok for Blender 2.80 is not backwards compatible with 2.79. The changes between the two API are relatively superficial for most things, and prohibitively significant in a few small areas. 

I don't advice using Sverchok in 2.80 yet, i'm still gradually fixing nodes for the new API. Unless you expect and accept stuff to be broken. Sverchok for 2.79 is the `Long Term Support` version, that will be supported for a while, until 2.80 stabilizes.

**Comment by zeffii** [comment]
I should have been more clear perhaps, sorry if the screenshots were misleading.

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/51907451-e34e2180-23d7-11e9-8d5c-a60e12675857.png)

**Comment by bakakouhai** [comment]
@nortikin I know that example, but that is not what I wanted. I tried to use Matrix Apply node before, but not for duplicating separate holes. The CSG difference is giving me strange result, that's why I did not use it.

Today I try it again on the holes since you remind me with you post, and it works for separate hole (the one I questioned before) but not for overlapping one (file attached, bl2.79b). Sorry for not trying it before.
[trial aio.blend.zip](https://github.com/nortikin/sverchok/files/2808789/trial.aio.blend.zip)

<img width="373" alt="screenshot 2019-01-29 at 18 19 36" src="https://user-images.githubusercontent.com/39821914/51926851-84e26c80-23f2-11e9-85c1-178412092b8d.png">

**Comment by bakakouhai** [comment]
Yes. I have updated my model to use the matrix apply node for geometry creation purpose only. The carve library works great on my case as seen below. The upper is overall view and the lower is the zoom out. The cylinder is 1 mm diameter and consist of 3000 vertices
![sverchok trial machining](https://user-images.githubusercontent.com/39821914/51929988-d9d5b100-23f9-11e9-9689-96d4c18b57b4.png)
![sverchok trial machining detail](https://user-images.githubusercontent.com/39821914/51929998-df32fb80-23f9-11e9-8135-f579421f50ac.png)
