### ISSUE TITLE
Viewer Drawer MK2 node multi type input bug

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2361]
When feeding lists of mixed inputs: verts/edges and verts/polys the node doesn't seem to do a good job rendering each set of VE or VP properly. Sometimes it only renders them VE .. or sometimes renders them both VE and VP but some edges are missing in the VE.

Node tree below shows actually both artifacts.. all meshes are rendere as VE even though the icosphere node feeds VP to the VD input... and you can also see some edges missing.

<img width="1281" alt="sv-vdmk2-multiinputbug" src="https://user-images.githubusercontent.com/2083719/52157337-3b955580-265c-11e9-9b9f-ecc9aecd0135.png">

[VDMK2-MultiInputBug.blend.zip](https://github.com/nortikin/sverchok/files/2823853/VDMK2-MultiInputBug.blend.zip)

**Comment by zeffii** [comment]
tricky...in 2.8 i'm inclined to offer several ways for the viewer node to interpret input
```
0: only real data
1: persumed repeats if indices exist
2: an analogue to vdmk2
```

**Comment by nortikin** [comment]
> tricky...in 2.8 i'm inclined to offer several ways for the viewer node to interpret input
> 
> ```
> 0: only real data
> 1: presumed repeats if indices exist ( most magic )
> 2: an analogue to vdmk2
> ```

if only less computation
