### ISSUE TITLE
can sverchok create custom vertex connectors like grasshopper from an existing mesh?

### ISSUE THREAD

**Issue by rvisani** [nortikin/sverchok#2362]
## Problem statement
Can sverchok create custom vertex connectors like grasshopper from an existing mesh?

Please describe your problem here.
I am trying to create custom connectors which would describe the verticies in low poly meshes that I have designed in blender.  They would connect to linear material which would correspond to the edges of the mesh.  I know of similar work being done with Grasshopper, which led me to sverchok.  Does sverchok have this capability.  I've attached a sample mesh, as well as examples of the grasshopper generated connectors.

![nodes_ae_04](https://user-images.githubusercontent.com/47344345/52254461-dea7d280-28db-11e9-9ccd-11cee7550b70.jpg)

![capture](https://user-images.githubusercontent.com/47344345/52254516-23cc0480-28dc-11e9-98e2-07025a2e1824.JPG)

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
hopefully i'm interpreting the question accurately,.

you want to feed sverchok an arbitrary edge-based mesh, as shown in your screenshot, and ask sverchok to generate these 'connectors' with holes of a certain diameter. For 3d printing and reconstructing a model with sticks of some kind?

we don't yet have a node that spits out the geometry of such connectors. (that's not to say that it isn't possible)

**Comment by zeffii** [comment]
there are a few ways to approach this:

1. - **use metaballs**, arrange numerous metaballs at each vertex, to shape  the connector
   -  convert metaballs to real mesh, maybe subdiv the result
   - boolean subtract the 'edge' geometry
    - separate all geometry to individual units  (like a separate loose)
    - automatically rearrange/transform resulting geometry to a plane appropriate for 3d printing


2.  - **use skin modifier**, arrange multiple new vertices at each vertex, to shape the connector
    - subdiv mesh
     - boolean subtract the 'edge' geometry  ...
     - the rest is same as 1.

3.  - **devise a function** that accepts parameters and produce this arithmetically (probably most satisfying to do )
    ```python
    def generate_connector_geom(vertex_prime, vertex_ring, connector_radius. stick_radius):
        """
        - vertex_prime is p, 
        - vertex_ring are all vertices associated with the edges attached to vertex_prime
        - connector radius, the span of the geometry from the point p
        - stick radius, the size of the opening at the ends of the connector
         r1  ----------  p  ----------- r2
                         |
                        r3 
        """
        return verts, faces

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/52275041-b73e1d80-294e-11e9-8c9a-3e9a1914a0a9.png)

**Comment by zeffii** [comment]
some metaball tweaking 
![image](https://user-images.githubusercontent.com/619340/52275630-63cccf00-2950-11e9-9465-f08176dd73a2.png)


i can't remember is this is available in Sverchok for 2.79 .  I also don't advise yet to use Sverchok in 2.80 (but that's what i'm using as a developer)

**Comment by zeffii** [comment]
and this shows with less stiffness
![image](https://user-images.githubusercontent.com/619340/52276438-7cd67f80-2952-11e9-9907-27cee42db1e0.png)

I think i'd not use metaballs, but try skin mesher node..

**Comment by zeffii** [comment]
# SkinMesher node

this is a little more involved, because you must supply both the vertices and the edges

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/52281933-7a2e5700-295f-11e9-9a4e-8128bf6e2cb2.png)
```python
"""
in verts v
in edges s
in radius s d=0.3 n=2
out overts v
out ofaces s
out oedges s
"""

from mathutils import Vector
from collections import defaultdict

for obj in zip(verts, edges):
    overts.append([])
    ofaces.append([])
    oedges.append([])
    new_verts = overts[-1]
    new_faces = ofaces[-1]
    new_edges = oedges[-1]
    vert_list, edge_list = obj
    
    connection_dict = defaultdict(set)

    for edge in edge_list:
        sx = sorted(list(edge))
        connection_dict[sx[0]].add(sx[1])
        connection_dict[sx[1]].add(sx[0])

    for idx1, idx_set in connection_dict.items():     

        # gather vertex prime
        vec1 = Vector(vert_list[idx1]) 
        new_verts.append(vert_list[idx1])
        
        start_idx = len(new_verts) - 1 
        
        # gather vertex radials
        for offset, idx2 in enumerate(idx_set):
            vec2 = Vector(vert_list[idx2])
            rate = radius / (vec1-vec2).length

            new_vtx = vec1.lerp(vec2, rate)[:]
            new_verts.append(new_vtx)
        
            new_edges.append([start_idx, start_idx + offset + 1])

```

**Comment by rvisani** [comment]
Thanks for the info zeffii!  I'm new to nodes and sverchok so it may take a few attempts before I work thru this, but based on what you are showing me it should work for my purposes.

**Comment by zeffii** [comment]
while not optimal, the metaball approach is still pretty fast.  the SN:
```python
"""
in verts v
in edges s
in radius s d=0.3 n=2
out overts v
out ofaces s
out oedges s
"""

from collections import defaultdict
from itertools import permutations 

from mathutils import Vector
from mathutils.geometry import interpolate_bezier as bezlerp

def make_arc(prime, vtx1, vtx2, num_verts=22):
    ctrl_1 = ctrl_2 = prime
    knot1 = vtx1
    knot2 = vtx2
    verts = bezlerp(knot1, ctrl_1, ctrl_2, knot2, num_verts)
    return [v[:] for v in verts[1:-1]]
    


for obj in zip(verts, edges):
    overts.append([])
    ofaces.append([])
    oedges.append([])
    new_verts = overts[-1]
    new_faces = ofaces[-1]
    new_edges = oedges[-1]
    vert_list, edge_list = obj
    
    connection_dict = defaultdict(set)

    for edge in edge_list:
        sx = sorted(list(edge))
        connection_dict[sx[0]].add(sx[1])
        connection_dict[sx[1]].add(sx[0])

    for idx1, idx_set in connection_dict.items():

        # gather vertex prime
        vec1 = Vector(vert_list[idx1]) 
        new_verts.append(vert_list[idx1])
        
        start_idx = len(new_verts) - 1 
        
        # gather vertex radials
        for offset, idx2 in enumerate(idx_set):
            vec2 = Vector(vert_list[idx2])
            rate = radius / (vec1-vec2).length

            new_vtx = vec1.lerp(vec2, rate)[:]
            new_verts.append(new_vtx)
        
            new_edges.append([start_idx, start_idx + offset + 1])

    for idx1, idx_set in connection_dict.items():
        perm = permutations(idx_set, 2)
        prime = Vector(vert_list[idx1])

        for p1, p2 in perm:

            vec1 = Vector(vert_list[p1])
            vec2 = Vector(vert_list[p2])
            rate = radius / (prime-vec1).length
            vtx1 = prime.lerp(vec1, rate)[:]
            rate = radius / (prime-vec2).length
            vtx2 = prime.lerp(vec2, rate)[:]
                        
            arc_vecs = make_arc(prime, vtx1, vtx2)
            new_verts.extend(arc_vecs)
```
this version would generate an arc between all permutations of the edges attached to each vertex, adding structural rigidity 
![image](https://user-images.githubusercontent.com/619340/52341853-07cb7e80-2a14-11e9-9349-0da59a398c13.png)

under the hood that looks like this: 
![image](https://user-images.githubusercontent.com/619340/52341909-36e1f000-2a14-11e9-8fbb-d41115a95c05.png)

**Comment by vicdoval** [comment]
This can work too.
Using this SNLite https://github.com/nortikin/sverchok/issues/2362#issuecomment-460670093 and a monad to convert edges to  capsule metaballs
[conectors.zip](https://github.com/nortikin/sverchok/files/2844707/conectors.zip)
![conectors1](https://user-images.githubusercontent.com/10011941/52473836-2017d680-2b97-11e9-9527-c8a72d84dc01.png)
Final boolean subtraction done with blender modifiers

**Comment by nortikin** [comment]
maybe try of this 2.79
https://vk.com/video287985479_456239780

[joints_2019_02_18_20_38.zip](https://github.com/nortikin/sverchok/files/2877320/joints_2019_02_18_20_38.zip)

**Comment by ichbinscheisse** [comment]
Blendersushi posted something similar. 
https://github.com/enzyme69/blendersushi/issues/367
