### ISSUE TITLE
Viewer Index - missing Text input

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2363]
Hi everybody, 
I'm playing around with Blender 2.80, and I've found a difference with the 2.79 version. The Viewer Index doesn't support text anymore... is there a different way or is a missing feature?

![immagine](https://user-images.githubusercontent.com/6708848/52498194-64779680-2bd8-11e9-9013-d391f7771f1b.png)

thanks
Alessandro

**Comment by zeffii** [comment]
that's because i didn't implement that feature, i also think it makes sense to implement that in it's own node, in a different way.

**Comment by alessandro-zomparelli** [comment]
Yes, I totally agree with you. A dedicated node makes more sense. Do you already have scheduled it? I'm asking because I need that for a project, and in case I'll stick to Blender 2.79b.
Thanks

**Comment by zeffii** [comment]
it wasn't on my shortlist :)   but i'll think about it now, and add to the todo over at the pullrequest.

**Comment by alessandro-zomparelli** [comment]
Thanks, no pressure though :-)

**Comment by zeffii** [comment]
so.. let's talk about this :) 

```python
    if draw_bface:

        blf.color(font_id, *vert_idx_color)
        for vidx in geom.vert_data:
            draw_index(*vidx)
    
        blf.color(font_id, *edge_idx_color)
        for eidx in geom.edge_data:
            draw_index(*eidx)

        blf.color(font_id, *face_idx_color)
        for fidx in geom.face_data:
            draw_index(*fidx)

```

- this part of the code is executed when `draw backfacing` is set to on (ie always draw... ). 
- this part of the code does not yet know about a text socket. (and it's not yet implemented on the UI)


maybe something like this


```diff
-        for vidx in geom.vert_data:
-            draw_index(*vidx)
+        if geom.vert_data and geom.text_data:
+            for text_item, (idx, location) in zip(geom.text_data, geom.vert_data):
+                draw_index(text_item, location)
+        else:
+            for vidx in geom.vert_data:
+                draw_index(*vidx)

```

**Comment by zeffii** [comment]
i've put this off for waay to long,  but here's the stub of the PR i want to use:
https://github.com/nortikin/sverchok/pull/2535
