### ISSUE TITLE
Bmesh Viewer - hide issue

### ISSUE THREAD

**Issue by alessandro-zomparelli** [nortikin/sverchok#2364]
Hi everybody,
I've found a bug in the BMesh Viever, I think that it still use the "hide" method from Blender 2.79:
![immagine](https://user-images.githubusercontent.com/6708848/52498451-22028980-2bd9-11e9-8cd5-3285fdb3c93e.png)

thanks
Alessandro

**Comment by zeffii** [comment]
yep. _that_ i will fix soon.

**Comment by zeffii** [comment]
definitely read through the ticklist of https://github.com/nortikin/sverchok/pull/2299

**Comment by alessandro-zomparelli** [comment]
I'm sorry, should I report issues in that general issue, or it's better to create separated onces?

**Comment by zeffii** [comment]
it's now `hide_viewport`  btw, there are a few other pesky things :)

> should I report issues in that general issue,

yes please, it will keep stuff in one place if you add comments to the pullrequest.

**Comment by alessandro-zomparelli** [comment]
Ok, I'll do that in future. Feel free to close them if you have take note.

**Comment by zeffii** [comment]
i (think) have a few hours tomorrow to address these things. I appreciate you checking it out!
