### ISSUE TITLE
For loop for CSG operation in  sverchok

### ISSUE THREAD

**Issue by bakakouhai** [nortikin/sverchok#2368]
## Problem statement

This is continuation from:
https://github.com/nortikin/sverchok/issues/2358

I want to simulate a machining process via Boolean operation in Blender.
The input is xyz cooordinates with cylinder tool, let's  say 100k position.

Can I do a for loop in Sverchok node environment to:
1. create a cylinder
for each position:
    2. move the cylinder to the position
    3. do CSG difference

The for loop is  required to avoid loading all 100k cylinder at once.
I have  tried to do the same thing using Blender modifier (Carve) and Cork addon (code below). Both cannot go pass 20 positions. I do not know if other addons  such as Bool Tool and Fast Carve are using other libraries or just shortcut the boolean process. 

Regards
Iwan

    import bpy

    with open(bpy.path.abspath("//cutting position trial.txt")) as content:
        # create tool
        bpy.ops.mesh.primitive_cylinder_add(
            vertices = 3000, 
            radius = 0.5, 
            depth = 10,
            location = (0, 0, 0)
            )
        
        for i, line in enumerate(content):
            print(i)
        
            # extract tool position
            x, y, z = line.split(' ',2)
        
            # select  cylinder
            bpy.ops.object.select_all(action='DESELECT')
            bpy.data.objects['Cylinder'].select = True
        
            # move the cylinder to the right position
            bpy.data.objects['Cylinder'].location[0] = float(x)
            bpy.data.objects['Cylinder'].location[1] = float(y)
            bpy.data.objects['Cylinder'].location[2] = float(z)+5
        
            # add BOOLEAN modifier
            bpy.data.objects['ISO 10791 M1 blank cd 0.0025'].modifiers.new('Boolean', 'BOOLEAN')
            bpy.data.objects['ISO 10791 M1 blank cd 0.0025'].modifiers['Boolean'].operation = 'DIFFERENCE'
            bpy.data.objects['ISO 10791 M1 blank cd 0.0025'].modifiers['Boolean'].object = bpy.data.objects["Cylinder"]
            bpy.data.objects['ISO 10791 M1 blank cd 0.0025'].modifiers['Boolean'].solver = 'CARVE'
            # activate the blank
            bpy.context.scene.objects.active = bpy.data.objects['ISO 10791 M1 blank cd 0.0025']
            # apply modifier
            bpy.ops.object.modifier_apply(apply_as='DATA', modifier="Boolean")

**Comment by zeffii** [comment]
i have used software that simulates the result of G-code, so i kind of understand what you are trying to achieve here.  The question is really how integral Sverchok is to getting the best results. Our CSG node is obviously ill equipped do do this, but Blender's Booleans will probably be able to do this flawlessly once the right approach is found.

My advice to you is to ask this question (without mentioning Sverchok) on blender.stackexchange.com

**Comment by vicdoval** [comment]
This could be another approach if your path is 2D : 
Use de `Contour 2D + Planar Edgenet to Polygons + Solidify` nodes to _join_ the cylinders and after subtract it as one piece.
![miling](https://user-images.githubusercontent.com/10011941/52781166-28b35580-304c-11e9-9171-90e6fe9a4fa0.png)
[milling.zip](https://github.com/nortikin/sverchok/files/2864560/milling.zip)
The Contour 2D calculates circular intersections by default (on the N-panel you can change it to polygonal if that is what you are looking for)

**Comment by zeffii** [comment]
@vicdoval   :)  https://www.youtube.com/watch?v=wyuIN7f-VPI

**Comment by bakakouhai** [comment]
@zeffii Blender gave segmentation fault error when I use Blender Carve modifier. I have asked the in stack exchange before coming here:
    https://blender.stackexchange.com/questions/131157/why-do-i-get-this-error-loading-large-text-file-to-blender
and to r/blender also:
    https://www.reddit.com/r/blender/comments/aosn36/help_blender_segmentation_fault/

No  reply from  stack exchange and I considered the reedit thread closed. This is because it works until line 75 when I do union first via intersect -bounding box method and then difference afterwards. Still gives  the same error though.

@vicdoval The method looks promising. The G code should be in 2D since I set the  depth of cut 1 mm. The machining is divided into 6 layer of 1 mm (positions can be grouped based on z value probably). Assuming the method works and I can load all  cylinder into the viewport (the real data is 244 MB of csv), I still need  to create the same code for each layer, hence the question about the loop.

I am sorry if the question is not at the right place.

Regards, Iwan

**Comment by zeffii** [comment]
`contour 2d` is pretty neat for this, as @vicdoval suggests..  note that it will massively reduce the complexity of the resulting goemetry. (rather than joining hundreds of cylinders)

![image](https://user-images.githubusercontent.com/619340/52859513-37256e00-312d-11e9-8847-e672e50390df.png)

**Comment by zeffii** [comment]
you could if you want even animate it :)  , there may be an optimal number of subdivisions on the `path` that produces the smoothest edges.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/52859864-2aede080-312e-11e9-82f3-518fe2361850.png)
vs
![image](https://user-images.githubusercontent.com/619340/52860107-cf702280-312e-11e9-8b87-53d415fa5f59.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/52860496-e5caae00-312f-11e9-898f-b5998292a2a8.png)
seems like animation parameter/ keyframes is broken in my build of b28, but this should work in b2.79 no problem.

**Comment by zeffii** [comment]
![portofol](https://user-images.githubusercontent.com/619340/52861252-32af8400-3132-11e9-8889-c0eb7ea2859e.gif)

**Comment by bakakouhai** [comment]
@vicdoval It does work like a charm! However, Carve library is used instead of BMesh since it gives me a wrong result. 

@zeffii I cannot use Blender 2.8 since the carve  library s not yet there. Animating it will be the next step if I can get the geometry right. It requires SV CSG instead of Blender Carve I think?

Is there any difference if I use extrude function instead of solidify? There are many functions in sverchok that seems to do the same thing.

I use different file to create each geometry:
1.  tool.blend contains cutting tool geometry (cylinder) and toolpath
2. blank contains the blank (of course)
3. machining contains linked tool and appended blank to do boolean modifiers.

As seen in the pic below, the  path mesh is not my concern since it is extracted from real CAM output. Also, the radii is 0.5 mm with 3000 verts it is a smooth one.
![capture2](https://user-images.githubusercontent.com/39821914/52890316-70d59380-3184-11e9-8e50-1e2e775d61df.PNG)

![capture 1](https://user-images.githubusercontent.com/39821914/52889915-729e5780-3182-11e9-814b-95a2f2bf2af8.PNG)

**Comment by Durman** [comment]
@bakakouhai I can suggest a little trick - to use update system of Sverchok like a loop for. But Sverchok does not expect layouts like that. It easy can be broken.
![drilling](https://user-images.githubusercontent.com/28003269/52894797-7acdb580-31c9-11e9-99f8-542fee9dbc11.gif)
![2019-02-16_09-02-16](https://user-images.githubusercontent.com/28003269/52894812-9638c080-31c9-11e9-961a-6f5f6d8cb2a4.png)
<details> 
  <summary>code</summary>  

```Python
'''
in A o
in B o
'''
import bpy

a, b = A[0], B[0]

bool_mod = a.modifiers.new('My_bool', 'BOOLEAN')
bool_mod.object = b
bool_mod.operation = 'DIFFERENCE'

bpy.context.scene.objects.active = a
bpy.ops.object.modifier_apply(apply_as='DATA', modifier=bool_mod.name)
```

</details>

[driil.zip](https://github.com/nortikin/sverchok/files/2871620/driil.zip)

**Comment by zeffii** [comment]
@bakakouhai ok, i wasn't suggesting using b2.8 (but that's what i'm using.. so it was easier to make screenshots)

> Is there any difference if I use extrude function instead of solidify?

they differ mostly in available parameters and are internally completele different, use whichever works best for your needs or either.

**Comment by bakakouhai** [comment]
@Durman Thank you for the suggestion. I will try it later probably to enhance my thesis presentation.
@zeffii I notice that you comment on stack exchange. Shared the complete zip as you suggested.
@vicdoval Thank you for the insight. I can create the tool pass the 200 th position now.

I seems need to break the toolpath further so the contour form a closed loop, besides the memory overload problem. Next thing to try is then automation process of boolean and updating the input text file via scripts.
![capture3](https://user-images.githubusercontent.com/39821914/52900694-17f41280-31f9-11e9-93bc-511e44b20cbe.PNG)

**Comment by vicdoval** [comment]
@bakakouhai note that you can input edges to the `Contour2D `node, that could simplify the output geometry. You can create the edges of a continuous path with the `UV Connection` node and also could simplify this path using `Limited Dissolve`  node after the UV Connection
![miling1](https://user-images.githubusercontent.com/10011941/52901142-660c1480-31ff-11e9-93d9-83021a632d72.png)

**Comment by bakakouhai** [comment]
@vicdoval I cannot input the edges since it will create a perfect straight  line. The extracted positions are induced slightly by errors, so it is not really a straight line for that far(micron scale both for error and movement resolution).

**Comment by bakakouhai** [comment]
The bottleneck for this kind of operation is on CPU it seems. I am in the 6000th line now, trying to find the limits, and Blender use only ~6 % of CPU resources and 2 GB of RAM. Does this means multi-core support is used only in scene rendering and not in modelling?

**Comment by zeffii** [comment]
@bakakouhai  your tool is drilling individual holes? not dragging through the medium? 

all i can think of are hacks :/

**Comment by bakakouhai** [comment]
It s a micro-milling process. the CAM generated output is set to spit out line (G1 commands only). Arcs are created with many straight line movement  with small steps. On top of this small steps, I added another 5 points to represent some error in movement. Example of the positions that  am creating is as follows:
```
61.412 80.147 -1.000
61.4165 80.1458 -1.0
61.4501 80.1278 -1.0
61.4837 80.1098 -1.0
61.5173 80.0918 -1.0
61.5509 80.0738 -1.0
61.580 80.057 -1.000

61.580 80.057 -1.000
61.5845 80.0558 -1.0
61.6181 80.0376 -1.0
61.6517 80.0194 -1.0
61.6853 80.0012 -1.0
61.7189 79.983 -1.0
61.748 79.966 -1.000
61.748 79.966 -1.000
```
They are initially 2 G1 commands from the previous position:
from X61.412 Y80.147 Z-1.00;   G1 X61.580 Y80.057 Z-1.000
from X61.580 Y80.057 Z-1.000; G1 X61.748 Y79.966 Z-1.000

Since the movement resolution is high the adding edges will just burden the memory.

**Comment by bakakouhai** [comment]
@vicdoval I tried to use the uv connection as you suggested hoping to reduce the computation more. The contour 2D node fails when I connect the edges. It is still useful to show  where the tool goes.  I attached the tool file below (Blender 2.79b). 
![capture5](https://user-images.githubusercontent.com/39821914/52907369-d8f9a780-3260-11e9-827d-497d38e2bf16.PNG)

[tool.zip](https://github.com/nortikin/sverchok/files/2872588/tool.zip)

**Comment by vicdoval** [comment]
@bakakouhai the crossing edges shouldn't be a problem, what definitely is is making troubles with "Contour 2D" and will make your calculation slower is the "doubled vertices" place a "Remove Doubles" at the beginning and it should improve. 
(Although I have notice that when the edges length is really small compared to the Contour2D Distance creates some kind of bug....)
