### ISSUE TITLE
Formula node and strange limited range graphing result

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2369]
BLEND:
[shape_of_math_formula_002.blend.zip](https://github.com/nortikin/sverchok/files/2882909/shape_of_math_formula_002.blend.zip)

## Problem statement

I have a Math f(X) formula from a friend and trying to see graphing, but somewhat the range limit is -1 to 1 only and cannot go further.

## Expected result
![photo-2019-02-20-06-52-25](https://user-images.githubusercontent.com/3952687/53064925-2180c180-34fc-11e9-8102-7122b9ca304c.jpg)

Expecting to see the graph goes beyond -1 and 1 range

## Actual result

<img width="889" alt="screen shot 2019-02-20 at 10 35 52" src="https://user-images.githubusercontent.com/3952687/53064783-9b647b00-34fb-11e9-8d35-b79d477ffed6.png">

## Sverchok version
0.5.9.6

**Comment by zeffii** [comment]
dunno... 

```python
import numpy as np
from math import sin, pow, cos, e


x_vals = np.linspace(-1, 1, 20)
new_xvals = []
for X in x_vals:
    new_x = abs( sin(X)) + 5 * pow(e, pow(-X, 100)) * cos(X)
    new_xvals.append(new_x)

print(new_xvals)

```
outputs
```
[8.184940684387321, 3.908711234680528, 4.231078170799871, 4.506652852947999,  
 4.7323384148220935, 4.905636493355263, 5.024628660614767, 5.087997660810009,  
 5.095041992452489, 5.045683674050985, 5.045683674050985, 5.095041992452489,  
 5.087997660810009, 5.024628660614768, 4.905636493355263, 4.7323384148220935,   
 4.506652852948, 4.231078170799871, 3.908711234680528, 8.184940684387321]
```

maybe the original formula is a bit different..
