### ISSUE TITLE
Update socket crash Investigation

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2370]
I'm investigating the crash I'm getting developing the InputSwitch node (#2367) so I stripped out all the InputSwitch node code and left pretty much only the code that changes the set size (number of input and output sockets, just one set for simplicity, and the code to update the socket types).

The Testing node in the https://github.com/nortikin/sverchok/tree/updateSocketsBug) branch has the following implementation:

* the update() method basically does nothing other than calling update_socket_type method.
* the update_set_sockets callback is called when changing the set size and it recreates new set of inputs / outputs every time the set size changes AND it also calls the update_socket_type at the end.
* the update_socket_type essentially replaces output sockets with new socket types (different type based on set size: StringsSocket and VerticesSocket).

To trigger the segfault if you connect the first input of the node and then scrub the set_size parameter eventually you'll get blender to crash. Having at least one input socket connected it is necessary so that the update() is called. This is the case since the update_set_sockets removes all inputs, recreates new inputs and RELINKS prior connections and this socket relinking is what triggers an update call. 

I suspect that somehow the double call to the update_socket_type, one done at the end of the update_set_sockets(), and one done at the end of update() somehow creates the segfault. If I comment out any of these calls to update_set_sockets (either the one in the update or the one in the update_set_sockets) I'm not able to replicate the segfault.

I don't fully understand the order of calling to pinpoint why the segfault happens. If anyone wants to take a look at the code and try the node to replicate the segfault and give me some ideas of why this may happen I would appreciate it.

To my understanding this shold be the order of calls:

```
scrub the set_size -> callback update_set_sockets
updates_set_sockets -> stores links, removes old inputs, creates new inputs, relinks sockets 
(relinks sockets will trigger call to update())
update_socket_type -> replace output sockets with new types

update() (triggered by the relinking in update_set_sockets) -> calls update_socket_type
update_socket_type -> replaces outputs sockets with new types
```

<img width="509" alt="screen shot 2019-02-22 at 11 28 40 pm" src="https://user-images.githubusercontent.com/2083719/53281620-9c62fb80-36f9-11e9-891f-4741fdb32891.png">

**Comment by zeffii** [comment]
Your Links collection dict is storing references to sockets , use socket.index to avoid that

I think

**Comment by DolphinDream** [comment]
@zeffii isn't what replace_socket also does? stores to_socket and from_socket refrences (in lists). Besides, aren't these to/from sockets actually the sockets of the external nodes ? (which don't change)

**Comment by zeffii** [comment]
yeah, the implementation doesn't differ. the problem isn't replace_socket or your implementation using the same principles. (i read it carefully now)

If this bug happens only during scrubbing of the `set size`, I would consider making `set size` editable only via the macro or two operator buttons on the node's UI.  (+1,  -1) to avoid triggering these issues. After all the ability to scrub the value for `set size` is not the node's core feature, nor would it be a feature used at any frequency during the node's lifetime.

**Comment by zeffii** [comment]
i've had no luck replicating that error using SvTestingNode (with property notations instead of attributes) in b.280  .  it may be a dependancygraph thing.

```python
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
from bpy.props import IntProperty, BoolProperty

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode
from collections import OrderedDict

indentSize = 0


class SvTestingNode(bpy.types.Node, SverchCustomTreeNode):
    """
    Triggers: Testing
    Tooltip: Testing stuff
    """
    bl_idname = 'SvTestingNode'
    bl_label = 'Testing Node'

    def update_socket_types(self):
        indent = self.set_indent(True)
        print("")
        print(indent, "TIC update_socket_types")

        self.id_data.freeze(hard=True)
        self.update = True

        inputs = self.inputs
        outputs = self.outputs

        for i in range(self.set_size):
            outLabel = "Data " + str(i + 1)
            outSockeType = "StringsSocket" if self.set_size % 2 else "VerticesSocket"

            if outLabel in outputs:
                print(indent, "TIC replacing:", i + 1, " of ", self.set_size)
                print(indent, "replace :", outLabel)
                print(indent, "replacing out socket type with: ", outSockeType)
                socket = outputs[outLabel]
                socket.replace_socket(outSockeType)
                print(indent, "TOC replacing:", i + 1, " of ", self.set_size)

        self.update = False
        self.id_data.unfreeze(hard=True)

        print(indent, "TOC update_socket_types")
        print("")
        self.set_indent(False)

    def update_set_sockets(self, context):
        indent = self.set_indent(True)
        print("")
        print(indent, "TIC update_set_sockets")

        self.id_data.freeze(hard=True)
        self.updating = True  # inhibit the calls to update()

        inputs = self.inputs
        outputs = self.outputs

        # INPUT SOCKETS ========================================================

        # RECORD the previous links to the SET's inputs sockets
        iLinkMap = OrderedDict()
        for s in inputs:
            if s.is_linked:
                iLinkMap[s.name] = [link.from_socket for link in s.links]

        # REMOVE the old SET's input sockets
        inSocketNames = [s.name for s in inputs]
        for name in inSocketNames:
            print(indent, "TIC: remove input socket:", name)
            inputs.remove(inputs[name])
            print(indent, "TOC: remove input socket:", name)

        # CREATE new input sockets
        for i in range(self.set_size):  # create the SET inputs
            label = "Alpha " + str(i + 1)
            print(indent, "TIC: add input socket:", label)
            inputs.new("StringsSocket", label)
            print(indent, "TOC: add input socket:", label)

        # RECONNECT previously linked SET input sockets (if they still exist)
        for sn, fromSocketList in iLinkMap.items():
            if sn in inputs:
                for fromSocket in fromSocketList:
                    print(indent, "TIC: link input socket:", sn)
                    links = inputs[sn].id_data.links
                    links.new(fromSocket, inputs[sn])
                    print(indent, "TOC: link input socket:", sn)

        # OUTPUT SOCKETS =======================================================

        # RECORD the previous links to the SET's output sockets
        oLinkMap = OrderedDict()
        for s in outputs:
            if s.is_linked:
                oLinkMap[s.name] = [link.to_socket for link in s.links]

        # REMOVE the old SET's output sockets
        outSocketNames = [s.name for s in outputs]
        for name in outSocketNames:
            print(indent, "TIC: remove output socket:", name)
            outputs.remove(outputs[name])
            print(indent, "TOC: remove output socket:", name)

        # CREATE new output sockets
        for i in range(self.set_size):  # create the SET outputs
            label = "Data " + str(i + 1)
            print(indent, "TIC: add output socket:", label)
            outputs.new("StringsSocket", label)
            print(indent, "TOC: add output socket:", label)

        # RECONNECT previously linked SET output sockets (if they still exist)
        for sn, toSocketList in oLinkMap.items():
            if sn in outputs:
                for toSocket in toSocketList:
                    print(indent, "TIC: link output socket:", sn)
                    links = outputs[sn].id_data.links
                    links.new(outputs[sn], toSocket)
                    print(indent, "TOC: link output socket:", sn)

        self.updating = False
        self.id_data.unfreeze(hard=True)

        self.update_socket_types()

        print(indent, "TOC update_set_sockets")
        print("")
        self.set_indent(False)

    set_size: IntProperty(
        name="Set Size", description="Number of inputs in a set",
        default=2, min=1, max=9, update=update_set_sockets)

    updating: BoolProperty(
        name="Updating", description="Flag to inhibit update calls when setting sockets",
        default=False)

    def set_indent(self, plus):
        global indentSize
        if plus:
            indentSize = indentSize + 2
        else:
            indentSize = indentSize - 2

        return '+' * indentSize

    def update(self):
        """ Update the input sockets when sockets are connected/disconnected """
        indent = self.set_indent(True)
        print("")
        print(indent, "TIC update")

        if self.updating:
            print(indent, "TOC update : already updating")
            print("")
            self.set_indent(False)
            return

        self.id_data.freeze(hard=True)
        self.updating = True

        inputs = self.inputs

        self.updating = False
        self.id_data.unfreeze(hard=True)

        self.update_socket_types()

        print(indent, "TOC update")
        print("")
        self.set_indent(False)

    def draw_buttons(self, context, layout):
        layout.prop(self, "set_size")

    def sv_init(self, context):
        for i in range(self.set_size):  # create the first SET inputs & outputs
            self.inputs.new("StringsSocket", "Alpha" + " " + str(i + 1))
            self.outputs.new("StringsSocket", "Data " + str(i + 1))

    def process(self):
        return


def register():
    bpy.utils.register_class(SvTestingNode)


def unregister():
    bpy.utils.unregister_class(SvTestingNode)

if __name__ == '__main__':
    register()

```
and
```
>>> nodes = bpy.data.node_groups['NodeTree'].nodes
>>> nodes.new("SvTestingNode")

```

**Comment by zeffii** [comment]
Blender 2.80 has a different update system / event handlers, and Sverchok necessarily had to evolve.

I realize that's probably not a very satisfying answer.  Maybe you can make it crash in 2.80, if not, then the despgraph / event handlers are the main change.

**Comment by DolphinDream** [comment]
It seems 2.79 has this

```
Experimental Features:
--enable-new-depsgraph
        Use new dependency graph.
```

**Comment by DolphinDream** [comment]
It seems 2.79 has this

```
Experimental Features:
--enable-new-depsgraph
        Use new dependency graph.
```

But it crashes even with this enabled. :(

**Comment by DolphinDream** [comment]
It seems 2.79 has this

```
Experimental Features:
--enable-new-depsgraph
        Use new dependency graph.
```

But it crashes even with this enabled. :(

**Comment by DolphinDream** [comment]
Thanks, @zeffii 
Btw, the scrubbing may not be the issue. This segfault can be triggered even when you disconnect a socket (e.g input socket). Sometimes it happens when I cut an input socket link, sometimes when I click on the input socket (temporarily disconnecting it). Try this setup and click on a socket. If it doesn't' crash immediately try clicking on the socket repeatedly and eventually it should crash. Sure, normally nobody does this rapid clicking and you may say this is not a real issue I should be concern fixing, but it helps to get to that race condition that triggers the segfault.

In this case what I think happens is: a input socket disconnection triggers the update() which calls the update_socket_type, which then updates the out socket disconnecting and reconnecting the output which triggers another update etc. (as you noticed I have "update inhibitors" in place in the update_socket_type to not trigger a recursive update but for some reason this succession of calls ends up somehow accessing deallocating memory and segfaults). 

You may be right it could be related to the depth graph somehow. Do you know if 2.79 uses the "fixed/experimental/alternative" depth graph by default or do you have to launch blender with some depth graph enable parameter?

<img width="766" alt="screen shot 2019-02-23 at 8 27 49 am" src="https://user-images.githubusercontent.com/2083719/53287080-5df32e00-3745-11e9-8dea-48588536008e.png">

**Comment by DolphinDream** [comment]
It seems 2.79 has this

```
Experimental Features:
--enable-new-depsgraph
        Use new dependency graph.
```

But it crashes even with this enabled. :(

**Comment by DolphinDream** [comment]
@zeffii what branch should i use to install SV for 2.8 ?

**Comment by zeffii** [comment]
i've still not been able to crash Blender with the suggested UI interactions. I suggest you really do try this in 2.80 with the current `2.80 prelease master` branch.

i'm tempted to write a version from scratch, you may have overcomplicated things ( but I won't appreciate whether that assumption is true or not.. until I try myself, you understand?  )

**Comment by zeffii** [comment]
- load blender
- add a scripts folder in blender preferences
    - inside the scripts folder have two folders
               - addons
               - addons_contrib
- in addons_contrib symlink a `sverchok` folder ( with its origin some local Git  repo of sverchok ) 
- switch master sverchok to `b28_prelease_master`
- store blender preferences, refresh addons
- then enable Sverchok  (may take a few moments)

**Comment by zeffii** [comment]
please don't commit anything to `* b28_prelease_master`

**Comment by DolphinDream** [comment]
I'm getting this when I enable SV addon. is it expected? 

<img width="1072" alt="screen shot 2019-02-23 at 10 10 35 am" src="https://user-images.githubusercontent.com/2083719/53288168-5cc8fd80-3753-11e9-9129-96a70bd37737.png">

**Comment by DolphinDream** [comment]
Trying to enable the second time:

<img width="1208" alt="screen shot 2019-02-23 at 10 20 06 am" src="https://user-images.githubusercontent.com/2083719/53288280-a108cd80-3754-11e9-8384-d743329e28d7.png">

**Comment by zeffii** [comment]
you need to use a more uptodate b28

**Comment by DolphinDream** [comment]
Got it. And sadly.. it crashes in 2.8 too (both when scrubbing and clicking on the socket). Here are some screencaptures (youtube vidoes this time since animated GIFs suck :) 

Scrub crash
https://youtu.be/eBY4PpH_hMI

Click crash
https://youtu.be/SOO4H0YfyWY

**Comment by zeffii** [comment]
OK. thanks for trying.   that's a pitty.

now i'm more inclined to debug it :) no ETA... but i'd start over from scratch.

**Comment by DolphinDream** [comment]
@zeffii btw.. what' s the difference between getting the links these two ways:

links = context.space_data.edit_tree.links
links = socket.id_data.links

then make connections:

links.new(fromSocket, toSocket)

**Comment by zeffii** [comment]
there should be no difference, because `edit_tree` would be the same reference as `socket.id_data`

**Comment by zeffii** [comment]
buuut.. if `socket` itself becomes invalidated.. it's likely that `.links` will point to a vacuum.

**Comment by DolphinDream** [comment]
This **may** be the root cause. Who knows. We need to check.

**Comment by DolphinDream** [comment]
Btw, for the time being, until we find the root cause of this segfault, I found a workaround solution. :) Essentially, instead of calling update_socket_type() form the update() (as this is also called from the update_set_size()) I am using a flag (set to True at the end of update call) to mark that the socket types need to be updated (e..g "typesNeedUpdate"). Then, in the process() method, I check if this flag is on.. and call the update_socket_types() if it is. It seems to do the job in my InputSwitch node and I can't get it to crash anymore. Btw, I assume that process() is always called (it seems to be) whenever update() is also called (e.g. connect/disconnect sockets) so this approach may be a reasonable workaround.

**Comment by DolphinDream** [comment]
Here's the InputSwitch node behavior using this workaround. no crash :) Auto Socket Type is happening! :) 

(again... here's youtube capture instead of animated gif)

https://youtu.be/JGhgWorWdIo

**Comment by DolphinDream** [comment]
What does this freeze/unfreeze (hard/soft) really do?

node.id_data.freeze(hard=True)

**Comment by zeffii** [comment]
you can find that by grepping.

**Comment by DolphinDream** [comment]
Well.. I did. I just don't think it's doing what I think it should be doing. (hence my use of my own bool update flag in my code). I thought it was supposed to suppress the calls to update during connect/disconnect (remove/new) sockets but it doesn't, which is why I kept my flag around.

**Comment by DolphinDream** [comment]
So, I gather the freeze inhibits the calls to process the node tree.. not the calls to update. Did I get this right?

**Comment by zeffii** [comment]
yep, often we want to do a number of things in a node, and if we individually do those things they might all each trigger the node's process function. `freeze` lets us turn that off, until we've established that the node is in the correct state for a single "final" process call (and downstream calls that it may trigger)

**Comment by zeffii** [comment]
i think only the nodes that use the update function are 
 - 3dview/nodeview drawing callbacks ( got to know when nothing is connected to disable it )
 - dynamic sockets that automatically update the ui based on kind/existence of linked sockets.

**Comment by zeffii** [comment]
this reminds me. there is a function called "update_socket" .. implemented by a tonne of sverchok nodes, but it's not triggered by anything inside sverchok nor the internal pynode mechanism. 

i'm removing these entirely from 2.80 nodes

**Comment by DolphinDream** [comment]
I wonder if other nodes call replace_socket from within update(). If so they are likely to crash.

**Comment by zeffii** [comment]
usually we've called 'replace_socket' from an `bpy.props.***Property(.....update=wrapped_update)` or a direct operator call.    ...buuut, if you do go looking and find one you find questionable, let me know.
