### ISSUE TITLE
Work with materials

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2374]
I decided to share some thoughts about approaches to set materials to objects. 

At first it looks like representation of materials should have own socket type. It is very similar to object socket type, so it can also have grey colour. I think we can use this colour for all sockets that work with Blender data. 

Initially I was thinking about creating list of materials but this approach shows itself inconvenient. 
#1756

I made simple node that can be named something like "material in" node. 
![2019-03-01_23-13-51](https://user-images.githubusercontent.com/28003269/53660617-ba8ba700-3c77-11e9-886b-cdbaea3c743b.png)

It just creates link to existing materials in blender data. Benefits of this node is customizing material via familiar Blender interface.
Also it is easy to combine them in one list.
![2019-03-01_23-18-27](https://user-images.githubusercontent.com/28003269/53660881-57e6db00-3c78-11e9-9c9d-1f4d00e5f7fe.png)

It is make sense to create another type of "material in" node  as well that can create material with some parameters. In this way it will be not only link but also a generator of materials. 

Also I made set material node.
![2019-03-01_23-22-41](https://user-images.githubusercontent.com/28003269/53661081-f1ae8800-3c78-11e9-8bd9-2e2d1288bfba.png)

Work of the node consists from applying materials to objects and linking material to polygons. It is possible to set as several materials to one object as one material to many objects. It is possible to assign different materials to different parts of a mesh with material index socket.

<details> 
  <summary>Several examples</summary>  

![2019-03-01_23-35-03](https://user-images.githubusercontent.com/28003269/53661809-bf9e2580-3c7a-11e9-8f2f-faef33732563.png)
![2019-03-01_23-36-34](https://user-images.githubusercontent.com/28003269/53661864-e52b2f00-3c7a-11e9-9708-243ac6856277.png)
![set_material](https://user-images.githubusercontent.com/28003269/53662129-93cf6f80-3c7b-11e9-8fd6-2d0238efa827.gif)

</details>

It can be integrated to Viewer Bmesh node but in this way last should have two additional sockets so this can be too much for using the node with comfort.

**Comment by nortikin** [comment]
here we closely came to limitation. more sockets times, more wire hell.
We need one sverchok object, that will handle all data from one socket... maybe I am wrong...

**Comment by Durman** [comment]
Something useful, will leave here.
https://blender.stackexchange.com/questions/67487/cycles-materials-math-node-with-more-than-two-inputs/99003#99003

**Comment by Durman** [comment]
It looks like there is no any need in such nodes which just makes links to Blender because Sverchok already have node with such functionality.
![2019-05-28_08-22-24](https://user-images.githubusercontent.com/28003269/58450861-fa9ce180-8121-11e9-99e7-97fcc5555e5f.png)

**Comment by enzyme69** [comment]
That's what I often found, the Object ID nodes is amazingly powerful and
can dig down Objects, etc. I think they need conversion to Blender 2.80.

I can't remember but I think it can also dig into directory of user.

>

**Comment by Durman** [comment]
The experiment with creating shader nodes for connection with Sverchok. Will open the issue while I'm working on this.
![2019-05-28_20-14-20](https://user-images.githubusercontent.com/28003269/58494013-361cc780-8185-11e9-9581-96e3e2f65057.png)
![sv cycle mat](https://user-images.githubusercontent.com/28003269/58493533-349ecf80-8184-11e9-858a-a78a0d0134b0.gif)

**Comment by nortikin** [comment]
also node remote control can be extended to handle materials.
looks like it has future also
![blender_remote](https://user-images.githubusercontent.com/5783432/58494783-8f352d00-817e-11e9-814b-3bae516b7a6b.png)

**Comment by Durman** [comment]
I don't see how it is possible connect to some shader node with `remote control` node, but it possible with `set property` node. 
Nevertheless I'm going to create factory of materials what required more complex functionality. Probably it is not specially for cycles engine but for every which capable of working with node editor.

**Comment by portnov** [comment]
@Durman looks nice. Only rename "Go back" to "Go to Sverchok" or smth like that, otherwise it's not clear what that means :)
Such approach could also be used for interaction for other node-based subsystems of blender.

**Comment by Durman** [comment]
Thank you. I will rename this later. 
There are still a lot of work to implement all features which I intended to do. Also approach of applying materials to objects is in fog in my mind. 😕

**Comment by nortikin** [comment]
also remote control can be renamed. And it can be cluster of nodes:
wifi
remote control
work with materials node
maybe other

**Comment by Durman** [comment]
@nortikin If you are talking about making new categories of node I would prefer for materials nodes make separate category which can include also nodes dedecated to UV maps and textures probably.

**Comment by Durman** [comment]
I'm very surprised. :open_mouth: 
It turned out that such collection as `bpy.data.objects` or `bpy.data materials` actually are just lists in spite of that such constraction like `objects['Cube']` looks like a dictionary.

Actually `objects['Cube']` in Python way should looks like `objects[objects.index('Cube')]`.

- So it means that it is quite expensive function which should be avoided in often using. I don't see another alternative only searching objects once and than keeping them in Python to the end of session. 

Probably someone can suggest better solution.

Some tests:
```Python
# Scene with 400 objects, from Cube.001 to Cube.400 
>>> import timeit
>>> objs = bpy.data.objects

>>> timeit.repeat("objs['Cube.007']", "from __main__ import objs", number=1000)
[0.0012341255112381772, 0.001228351074221726, 0.0012382959379722805]

>>> timeit.repeat("objs['Cube.001']", "from __main__ import objs", number=1000)
[0.0006159399484211292, 0.0006217143854350127, 0.000610165511403693]

>>> timeit.repeat("objs['Cube.010']", "from __main__ import objs", number=1000)
[0.0029022962048799172, 0.002884972893824056, 0.0028856144979414466]

>>> timeit.repeat("objs['Cube.100']", "from __main__ import objs", number=1000)
[0.011830859040529162, 0.011705746238519055, 0.0111337561718301]

>>> timeit.repeat("objs['Cube.400']", "from __main__ import objs", number=1000)
[0.0390210789407206, 0.023310119027186715, 0.01902997798977424]

```

**Comment by portnov** [comment]
Unfortunately, one can't afford to keep references to bpy objects from python side. See https://developer.blender.org/T53530 , https://docs.blender.org/api/master/info_gotcha.html#undo-redo , #1918 .

**Comment by Durman** [comment]
@portnov Bad news. 
But it looks like that there is solution of the problem. 

During surfing of internet I found a post about possibilities of using pointer properties for such types like Object, Material and so on since Blender 2.79. And it looks like this is working indeed. It is even does not lose objects during renaming of them. If to rename object and then press undo link will be lost but it does not cause of crushing of Blender.

```Python
>>> bpy.data.objects['Cube.400']
bpy.data.objects['Cube.400']

>>> bpy.types.Object.next_object = bpy.props.PointerProperty(name="Next_obj", type=bpy.types.Object)
>>> Cube = bpy.data.objects['Cube']
>>> Cube.next_object = bpy.data.objects['Cube.400']
>>> Cube.next_object
bpy.data.objects['Cube.400']

>>> import timeit
>>> timeit.repeat("Cube.next_object", "from __main__ import Cube", number=1000)
[0.00035897750118937366, 0.00035448627239880056, 0.0003807920410292999]

>>> objs = bpy.data.objects
>>> timeit.repeat("objs['Cube.400']", "from __main__ import objs", number=1000)
[0.03157847123063107, 0.018376504200745103, 0.01829181245783218]
```

**Comment by nortikin** [comment]
@Durman https://github.com/nortikin/sverchok/pull/2434

**Comment by Durman** [comment]
![2019-06-02_22-58-27](https://user-images.githubusercontent.com/28003269/58766002-926b5700-858a-11e9-8352-8fbe452404c8.png)

**Comment by Durman** [comment]
I have discovered that dynamic material icon is really expensive, it slow down animation much.
![2019-06-04_23-02-31](https://user-images.githubusercontent.com/28003269/58906400-dee69c00-871c-11e9-8480-a09fa34624fa.png)

**Comment by Durman** [comment]
Well, I have to say that changing material dynamically have awful performance. Worst result gives opengl render of material. Slightly better is cycle render. But it is better does not render material at all.)) Also it would be interesting make tests with eevee.

 I notice that opengl render of material does not support animation parameters of material. Probably there are some reasons for this.)

Well I have to think how to move on. 😕 

<details> 
  <summary>node tree
</summary>  

![2019-06-05_08-50-58](https://user-images.githubusercontent.com/28003269/58931034-0f572600-876f-11e9-9ea4-6a3873b93a69.png)
![2019-06-05_09-02-46](https://user-images.githubusercontent.com/28003269/58931438-bbe5d780-8770-11e9-80d5-cd24280c1a55.png)

</details>

![dinamick material](https://user-images.githubusercontent.com/28003269/58931003-f3ec1b00-876e-11e9-9777-fe11114eb399.gif)
![dinamick material2](https://user-images.githubusercontent.com/28003269/58931397-9f499f80-8770-11e9-8931-89e26d123023.gif)

**Comment by Durman** [comment]
![maping material](https://user-images.githubusercontent.com/28003269/58955016-d38e8180-87ab-11e9-9eaa-0511e123a8c6.gif)

**Comment by Durman** [comment]
Performance with cycles engine is not too bad.
<details> 
  <summary>node tree</summary>  

![2019-06-05_18-57-08](https://user-images.githubusercontent.com/28003269/58966674-c5e4f600-87c3-11e9-8c09-ee7cb772f36c.png)

</details>

![color wheel](https://user-images.githubusercontent.com/28003269/58966569-8f0ee000-87c3-11e9-8e3d-07ad2b654171.gif)

**Comment by Durman** [comment]
Don't know why but image decompose node gives only blue color in my case.
![2019-06-07_12-10-18](https://user-images.githubusercontent.com/28003269/59091325-238e5500-8920-11e9-99d0-aec953eccdbf.png)

**Comment by Durman** [comment]
I'm continuing playing with material node. I decided to refuse from using several agent in one material. So I have to create UI for customizing sockets. First attempt looks quite simple and stable.

![soket dinamikes](https://user-images.githubusercontent.com/28003269/59291549-3ab8a400-8c8c-11e9-90a8-480904d90c0a.gif)
