### ISSUE TITLE
Interpolation / Resampling functions

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2375]
I have a set of 1D values [a1, a2, .. an] and I want to do a resampling at some points [t0, t1, .. tm] between a1 and an. Is there a function in SV already that can do spline interpolation and resampling?

**Comment by zeffii** [comment]
nope, only for vectors/vector-likes .

**Comment by zeffii** [comment]
...but... i did make a scriptnode script at one point with a 1D interpolator / resampler  (implementing Moving Average too) ,struggling to remember the   name / issue

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1680

**Comment by DolphinDream** [comment]
What I actually end up doing is this:
* I used the CubicSpline to interpolate 3D points formed by adding the 1D array as the Y values of the 3D points and then extracting th Ys from the interpolated 3D points as the resampled values :) works great. 

```
def get_resample_profile(profile, samples, cyclic):
    ''' Resample 1D array '''
    N = len(profile)
    v = [[n / (N - 1), p, 0] for n, p in enumerate(profile)]
    samples_array = np.array(samples).clip(0, 1)
    spline = CubicSpline(v, metric="POINTS", is_cyclic=cyclic)
    out = spline.eval(samples_array)
    verts = out.tolist()

    resampled_profile = [v[1] for v in verts]

    return resampled_profile

```
