### ISSUE TITLE
2d tessellation functions / utlity

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2383]
something like an adaptive remesher for 2d polygons.

close to

![image](https://user-images.githubusercontent.com/619340/54356696-855e5c00-465c-11e9-9e78-03deb6785e6c.png)

and

![image](https://user-images.githubusercontent.com/619340/54356759-af178300-465c-11e9-9f8f-0270a6eac127.png)

and 

![image](https://user-images.githubusercontent.com/619340/54357109-9bb8e780-465d-11e9-806e-16bd64c175dd.png)

**Comment by nortikin** [comment]
external library?
