### ISSUE TITLE
can't change Functions in Logic functions node

### ISSUE THREAD

**Issue by AboAlFadlSD** [nortikin/sverchok#2384]
logic functions node missing logic gate choice menu
![issue](https://user-images.githubusercontent.com/37113910/54360642-5d7bf200-4676-11e9-9ba7-5d83b5543faa.png)

 Sverchok version: 0.6.0.0(c0af4e8)
blender version: 2.80-87aca8bd02bc-win64

sverchok installed from b28_prerelease_master branch from github

**Comment by Durman** [comment]
I would recommend to use version of Sverchok for Blander 2.79. Version for Blander 2.8 does not support yet. 

As far as I know, despite of there is available version for 2.8, is still should be done a lot of work before there will be stable version. So there is no even sense left bug reports about Sverchok for 2.8.))

**Comment by Kosvor2** [comment]
Must work now. Try new version.
