### ISSUE TITLE
SverchokUpdateObjectIn - Operator

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2386]
While I was trying to understand update system of Sverchok I faced with operator that can call for updating node tree but I didn't manage to finde usage of the operator. May be it be should deleted?

https://github.com/nortikin/sverchok/blob/c0af4e843f9c7cb39c5b1d2a9b4bc6e726c3840e/ui/sv_panels.py#L32-L36

**Comment by zeffii** [comment]
yeah, i think it can be removed.. nothing seems to call it.

**Comment by zeffii** [comment]
... i might have added that a while back to call from another program  :)

**Comment by Durman** [comment]
Done)
