### ISSUE TITLE
Flameprof tool

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2388]
I just discovered a tool which can convert python's cProfile's `*.prof` output to nice flamegraph pictures:
https://github.com/baverman/flameprof

If you are not familiar with flamegraphs (yet), see http://www.brendangregg.com/flamegraphs.html .
Shortly: this is a nice way of visual representation of code's performance.

Usage with Sverchok:
* enable profiling in settings
* press "start profiling" in panel
* do something, for example update the tree
* press "stop profiling" in panel
* press "save data" and save it to some `*.prof` file
* In simplest case, it is enough to run `python flameprof.py sverchok.prof > output.svg` and open SVG file in the browser. Just make sure you are using Python 3 to run `flameprof.py`.

FYI: @zeffii @Durman @DolphinDream and everyone who is interested in sverchok's performance.

**Comment by portnov** [comment]
Just an example of generated image
![output](https://user-images.githubusercontent.com/284644/54452806-ceef9980-4777-11e9-8046-2f3fb8ac3010.png)

**Comment by zeffii** [comment]
i wrote a similar html/svg output of the older timing system.. so i'd be interested if we could convert flameprof to output the data to 3dview or nodeview, with proper zooming...panning.. etc.

**Comment by portnov** [comment]
Closing, nothing to do here.

**Comment by nortikin** [comment]
For sverchok pip installer it should be one of default modules to use

**Comment by nortikin** [comment]
just png lost popup information from element with % and node names...

**Comment by nortikin** [comment]
```sudo apt-get install flameprof 
cd folder
flameprof a.prof > a.svg```
