### ISSUE TITLE
Baking Sverchok animation to Shape Keys (Script)

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2390]
I wanted to share this little script for Blender 2.79  to bake Sverchok animations to Shape Keys
This allows to have smooth motion blur, very fast viewport animation,  sending it to a render farm or to render the output animation it in 2.8
It works by creating a copy of the selected object and adding every frame a new keyframed Shape Key 

To use it just paste it in a text-block, select the original object and hit  'Run the script'
```
import bpy

original_name = bpy.context.active_object.name
first_frame = bpy.context.scene.frame_start 
end_frame = bpy.context.scene.frame_end 
bpy.context.scene.frame_current = first_frame
bpy.ops.node.sverchok_update_all()
bpy.ops.object.duplicate()
bpy.context.active_object.name = 'Baked_' + original_name
bpy.context.active_object.data.name = 'Baked_' + original_name
bpy.data.objects[original_name].select = True
bpy.ops.object.join_shapes()
for actFrame in range(first_frame+1, end_frame+1):
    bpy.context.scene.frame_current = actFrame
    bpy.ops.node.sverchok_update_all()

    bpy.ops.object.join_shapes()
    bpy.context.object.active_shape_key_index = actFrame-1
    keys_name = bpy.context.object.data.shape_keys.name
    k = bpy.data.shape_keys[keys_name]
    k.key_blocks[-1].value = 1
    name = bpy.data.shape_keys[keys_name].key_blocks[-1].name
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name +'"].value')
    k.key_blocks[-2].value = 0
    name_p = bpy.data.shape_keys[keys_name].key_blocks[-2].name
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name_p +'"].value')
    bpy.context.scene.frame_current = actFrame-1
    k.key_blocks[-1].value = 0
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name +'"].value')

```

(It was asked here https://github.com/nortikin/sverchok/issues/469 but I opened  a new issue to keep it cleaner)

Maybe it could became one sverchok operator but by now here is the script :)

**Comment by zeffii** [comment]
i want to add my support for this approach to animation via `sverchok`. Using sverchok as only part of the process allows you to control a lot more, even animate properties that don't have socket-input.

**Comment by nortikin** [comment]
why not modify this https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/shape_key_bake.py

**Comment by zeffii** [comment]
@vicdoval  reckon you could assemble a small script that does, something like

```
for frame in range(30, 60):
    # set desired render file name and location ( if it can't be done automatically )
    # render()

```

**Comment by vicdoval** [comment]
Like this?
The bad thing is that it does not report to the ui the render progress
```
import bpy 
file_name = '/tmp\\imtest2\\'

start_frame = 10
end_frame =14

for act_frame in range(start_frame, end_frame + 1):
    bpy.context.scene.frame_current = act_frame
    bpy.ops.node.sverchok_update_all()
    bpy.ops.render.render()
    this_file = file_name + str(act_frame).zfill(4) +'.png'
    bpy.data.images["Render Result"].save_render(filepath=this_file)
    print(act_frame)

print ('done')
```

**Comment by zeffii** [comment]
hmmm.. i think maybe the solution is to add an event handler in the script (post_render) to do the `save_render(file_path=.... )` stuff..

i suspect when you set the `frame_current`, that would already trigger `sverchok_update_all()`

**Comment by vicdoval** [comment]
I will try to check the handler idea

>    i suspect when you set the frame_current, that would already trigger sverchok_update_all()

I thought so too, but if you update the frame from a script it does not update the nodetree

**Comment by vicdoval** [comment]
the 2.8 version of the "baking animation to shapekeys" script:
```
import bpy

original_name = bpy.context.active_object.name
first_frame = bpy.context.scene.frame_start 
end_frame = bpy.context.scene.frame_end 
bpy.context.scene.frame_current = first_frame
bpy.ops.node.sverchok_update_all()
bpy.ops.object.duplicate()
bpy.context.active_object.name = 'Baked_' + original_name
bpy.context.active_object.data.name = 'Baked_' + original_name
bpy.data.objects[original_name].select_set(state=True)
bpy.ops.object.join_shapes()
for actFrame in range(first_frame+1, end_frame+1):
    bpy.context.scene.frame_current = actFrame
    bpy.ops.node.sverchok_update_all()

    bpy.ops.object.join_shapes()
    bpy.context.object.active_shape_key_index = actFrame-1
    keys_name = bpy.context.object.data.shape_keys.name
    k = bpy.data.shape_keys[keys_name]
    k.key_blocks[-1].value = 1
    name = bpy.data.shape_keys[keys_name].key_blocks[-1].name
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name +'"].value')
    k.key_blocks[-2].value = 0
    name_p = bpy.data.shape_keys[keys_name].key_blocks[-2].name
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name_p +'"].value')
    bpy.context.scene.frame_current = actFrame-1
    k.key_blocks[-1].value = 0
    bpy.data.shape_keys[keys_name].keyframe_insert(data_path='key_blocks["'+ name +'"].value')
```

**Comment by vicdoval** [comment]
this would work rendering n frames in the 2.8
```
import bpy 
file_path = '/tmp\\imtest8\\'

start_frame = 10
end_frame =14

for act_frame in range(start_frame, end_frame + 1):
    bpy.context.scene.frame_current = act_frame
    bpy.ops.node.sverchok_update_all()
    bpy.context.scene.render.filepath = file_path + str(act_frame).zfill(4) +'.png'
    bpy.ops.render.render(write_still=True)
    print(act_frame)

print ('done')
```

**Comment by javismiles** [comment]
@zeffii @vicdoval here feedback
- the code just posted by vicdoval and a previous one of zeffii both work but the latest is faster and works better, this works yes except for the one puzzling thing that the background gets rendered solid black in the PNG when it should be transparent, its set to transparent in blender and rendering separated frames in blender renders background transparent, any idea why the script is not rendering the background transparent?

**Comment by enzyme69** [comment]
@nortikin Your Script Node Lite solution is interesting but not sure how it would work? I tried it does not work.

I have weird method at some point, basically passing the data into Shapekeys... via Object ID.
https://www.youtube.com/watch?v=eIPRhKzJ6fM

It's like Victor baking data into shapekeys.

**Comment by vktcl** [comment]
@nortikin How to use this node? about (shape_key_bake.py)。I hope you can give me an example to understand it

**Comment by nortikin** [comment]
> @nortikin How to use this node? about (shape_key_bake.py)。I hope you can give me an example to understand it

update sverchok - collections links added
link nodes:
![изображение](https://user-images.githubusercontent.com/5783432/106294016-b69ba180-625f-11eb-8b0d-561f67729d4f.png)
choose frame and define parameters:
![изображение](https://user-images.githubusercontent.com/5783432/106297624-f6648800-6263-11eb-8f9c-472e6462ee84.png)
change active to 1 and back to 0 to deactivate after:
![изображение](https://user-images.githubusercontent.com/5783432/106297645-fbc1d280-6263-11eb-8f32-f635aff1b6a0.png)

**Comment by vktcl** [comment]
@nortikin use blender2.91.No bake shape keys,what should I do to bake shape keys
![屏幕截图 2021-01-30 094348](https://user-images.githubusercontent.com/74725748/106343643-5c432500-62e1-11eb-9c0e-8ea7d55d48a2.png)

**Comment by nortikin** [comment]
> @nortikin use blender2.91.No bake shape keys,what should I do to bake shape keys

upgrade sverchok and add SNL shape key bake again from scratch
