### ISSUE TITLE
Socket count

### ISSUE THREAD

**Issue by TWINGSISTER** [nortikin/sverchok#2399]
==============
Issue template
==============

## Problem statement

Socket values are now passed as a list within a list, yet drawing the node the code do not peel off this additional list and indication about Vertices, Edges and Faces is wrong.

## Steps to reproduce

1. create a sphere display it
2. look
3. be disappointed
![sphere-too](https://user-images.githubusercontent.com/18615968/56454365-c0d10200-634f-11e9-9d57-104f25983116.png)

## Expected result

edges, faces, vertices count could be easily corrected
Suggest to look in /sverchok/core/socket_data.py line 66
<`return str(len(data))` 
turn into 
> `return dataTag(data)`
and put somewhere something like
```python
def dataTag(data):
    if type(data) is list:
        sw=len(data)
        if sw==0: return "[]"
        elif sw==1: return "[%s]" % str(len(data[0]))
        elif sw==2: return "[%s,%s]" % str(len(data[0])),str(len(data[1]))
        elif sw==3: return "[%s,%s,%s]" % str(len(data[0])),str(len(data[1])),str(len(data[2]))
        else: return "%s" % str(sw)
    else: return "1"
```
![хорошо](https://user-images.githubusercontent.com/18615968/56454208-967e4500-634d-11e9-9d80-37c5818683f7.png)

## Actual result

edges, faces, vertices count are not correct i.e. 1 is displayed
These happens either with our hardcoded nodes (that could be buggy, yes..)
![one-quadric](https://user-images.githubusercontent.com/18615968/56453844-54063980-6348-11e9-9929-3e2c4ec34ab2.png)
We think this helps in general! Probably this will resist in most context (even within our dreadful patches, too...) even in future without a complete review of the code. So we think this could be adopted in general.
## Sverchok version
0.6.0.0. for Blender 2.80
This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by Kosvor2** [comment]
This number is a number of objects. Not number of verts or edges. Must be more obvious, agreed.

**Comment by Kosvor2** [comment]
Now it looks like this:

![obj_count234](https://user-images.githubusercontent.com/22656834/56456124-52a53300-6381-11e9-8b91-ab6ab85eeae1.png)

But only in 2.8 branch.

**Comment by Kosvor2** [comment]
Now also in master.

**Comment by zeffii** [comment]
it's been this way since 2014 i think -- so this change might be a little premature, what do you say @nortikin .  The number behind the socket name indicates the number of lists of vertices, not the number of vertices.

**Comment by nortikin** [comment]
i think, adding obj grabbing space much. and this is ugly.
just leave as it was. maybe add to documentation more about point and number in socket  name.
**### Minimalism first of all.**

**Comment by zeffii** [comment]
i am also not happy with the change.
