### ISSUE TITLE
Handler for objects in node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2420]
I have an idea how it is possible to track changes of objects in scene. 

Instead of creating global event like "Some object have been changed" it is easier to bind such handler to a node in node tree. In particularly I suggest create additional button for `objects in` node named like "track changes":

- When the button is pushed function tracking changes is added to handlers. 
- Additional pushing on the button will remove function from handlers. 
- Pushing on `get selection` button alse will remove function. 

I think button for creating handler is most appropriate because it gives understanding that it is not cheap functionality. I already experimented with such handlers during working under alternative update system.

<details> 
  <summary>code</summary>  

```Python
@persistent
def changes_of_objects_handler(scene):
    select_objs = bpy.context.selected_objects
    active_obj = scene.objects.active
    if select_objs:
        if select_objs[0].is_updated:
            # this means object was moved move by user but setting new material also can pass this condition
            debug('{} - is updated'.format([ob.name for ob in bpy.context.selected_objects]))
            tree_updater.changed_object_in_scene.update(select_objs)
            tree_updater.update(props='OBJECTS_UPDATE')
            return
    if active_obj:
        if active_obj.is_updated_data:
            # setting new vertex group, changing geometry and etc.
            debug('{} - is updated data'.format(active_obj.name))
            tree_updater.changed_object_in_scene.add(active_obj)
            tree_updater.update(props='OBJECTS_UPDATE')
            return
        if active_obj.data.is_updated:
            # setting new vertex group, changing geometry and etc.
            debug('{} - DATA is updated'.format(active_obj.data.name))
            tree_updater.changed_object_in_scene.add(active_obj)
            tree_updater.update(props='OBJECTS_UPDATE')
            return
        if active_obj.data.is_updated_data:
            # did not catch this trigger
            debug('{} - DATA is updated data'.format(active_obj.data.name))
            tree_updater.changed_object_in_scene.add(active_obj)
            tree_updater.update(props='OBJECTS_UPDATE')
            return
```

</details>

This function tracks changes of selected objects in scene but can be easily changed for tracking changes of named objects.

What benefits it can achieve. 

- Firstly we can stop using animation during changing objects for getting updating node tree immediately. 
- In second the function can call update from node event that is as fast as possible.

Problems:
Main problem as I see is possibility to create loop in update events. For example, object from scene is gotten, next its matrix is changed and set to this object back that will rise update event again. 

![2019-05-19_21-15-26](https://user-images.githubusercontent.com/28003269/57985602-447b2d00-7a7b-11e9-87ba-5fabce0a3520.png)

How can this be avoided. 
I can suggest to add special mode for Sverchok called update. If Sverchok is in `update mode` all other update events will be ignored.

So, anybody is interested in such feature for Sverchok?

**Comment by zeffii** [comment]
there's a `live mode`, and operator to enable it" Live Obj In "  , do a search in the code / issue tracker . it might already be what you want? -- 

in b.28 the event handlers are different, but still not very refined.. it would be lovely to add an event handler to a specific object..

**Comment by Durman** [comment]
Yes indeed, live update works close to the idea. The code below is calling during live updating.

https://github.com/nortikin/sverchok/blob/9e6abea4824ee2e7f7574e44fe40fe73bdca17c8/ui/sv_panels.py#L44-L69

The downside of this algorithm is that object nodes are updating each 1/13 second whether there are some changes in objects or not if understand correctly. And if after `objects in` nodes are going huge slow algorithm, this approach have no benefits against animation event.

In my approach, the function before calling update object node checks whether changes of objects in scene were or not. If there was no changes function just do nothing.

Well, now I see two ways: to improve live update mode or implement handler for objects in node. First way looks easier but second more flexible. Probably it have sense to implement both approaches.))

**Comment by zeffii** [comment]
it would be awesome if the scene/depsgraph update handler could be explicit about which objects caused the update, that way if the object is not loaded in the ObjIn node then those updates can be ignored.

is that possible?  i don't know.. does your code figure out which object was updated?

**Comment by Durman** [comment]
Your suggestion is nice but unfortunately I did not find suitable Blender API for such approach. 

What is possible is to ask all objects in scene was there changed or not. If there are alot of objects it will take too much time. According this reason there is sense to ask only objects that was added to objects in node. 

Of course it would be fine to have such function that could return only changed objects but I guess that Blender does not give such possibilities.

**Comment by zeffii** [comment]
i think we should ask Blender devs for a more fine grained depsgraph update `event handler`,  one where there's a local variable  available to the bpy api  that any add-on can lookup to see which object/ objects triggered an update.. in 2.8 there's a chance of that happening -- 

write a detailed explanation of 
 - what is needed, 
 - why it is needed

in a way where it makes sense and a solution would not just apply to Sverchok.

**Comment by Durman** [comment]
> i think we should ask Blender devs for a more fine grained depsgraph update `event handler`, one where there's a local variable available to the bpy api that any add-on can lookup to see which object/ objects triggered an update.. in 2.8 there's a chance of that happening --

I think objects can't trigger updates by themselves. 

$vecrhok interact with blender internal data. It can read data from Blender database do something with this data and record this information back. Processing of data can take long time, so number of processing should be reduced as less as possible. 

According this it is good idea to check was input data really changed or not. If the data was not changed there is no sense to repeat processing again. 
Blender already has some features which allow to check was an object changed during update event or not. 

```
is_updated
Datablock is tagged for recalculation

is_updated_data
Datablock data is tagged for recalculation
```
As far as I understand correctly for getting information about update status of object there is need make call to an object each time when update event happens. 
There is no problems if Sverchok interacts only with several objects but if there are alot of objects to check it can slowdawn whole process. 

I see the solution of this problem without knowing of internal structure of Blender in giving extra information what exectly was changed during update event.
In this way all that should be done for chacking of changing data is to find name of chaged object in dictionary of Sverchok that store information wich data was get from Blender. If there is no coincidence do nothing else update current data from Blender. 

Another approach can be possibility to subscribe to updates. I imagine this like creating function that should be called only if an object to which function is bound is updated. In this way there is no even need in checking anything. Sverchok just waiting when the function will be called.

Also I think that sometimes information about which object was changed can be not full. 
As sooner as objects have large number of parameters it can be interesting to know what exactly parameter was changed. So it would be nice to include such information in update event too. 

And one more thing. Changing of an object can be caused by different reasons. It can be important to know, changing was caused by user or something else.

**Comment by Durman** [comment]
> i think we should ask Blender devs for a more fine grained depsgraph update `event handler`, 

By the way where is there such a place, where Blender devs are considering some suggestions?)

**Comment by Durman** [comment]
> By the way where is there such a place, where Blender devs are considering some suggestions?)

https://blender.community/c/rightclickselect/

**Comment by Durman** [comment]
Next code gives next result.
```Python
        for nodes in obj_nodes:
            for node in nodes:
                for i in node.object_names:
                    obj = bpy.data.objects[i.name]
                    if obj.is_updated or obj.is_updated_data or obj.data.is_updated:
                        print('calling process on:', node.name, node.id_data)
                        process_from_node(node)
```

![test update event](https://user-images.githubusercontent.com/28003269/59555447-6789f580-8fc3-11e9-9a57-db03df07074f.gif)

On the gif I'm testing animation mode at first. This mode update all nodes every frame. Then I switch to to live object update. In my modification this mode updates nodes only if objects which they holds was changed. So if there is no changes it returns better performance.

But I did not manage to force update only those nodes which objects was changes. Updating of one `object` node causes to the updates of remain `object` nodes. I don't know this what such behavior related. Probably current update system have some rules which I don't know or there is something in `object` node.

**Comment by zeffii** [comment]
i could add a feature to the operator that makes it test to see which object is currently in edit_mode, and only trigger from the node which references that object.  i'll do that for svb2.8, if anyone wants to backport it

**Comment by zeffii** [comment]
on second thought, i will leave the coding for this to people who really need the feature. if you have troubles - then @ me.

**Comment by Durman** [comment]
It looks like I have found the solution. The reason why all nodes was updated when only one node was calling to update was that changing of one node caused of changing of whole node tree. So I just freeze node tree and after changing `object` nodes returns node tree condition to unchanged. 

<details> 
  <summary>code</summary>  

```Python
        for nodes in obj_nodes:
            for node in nodes:
                with hard_freeze(node):
                    for i in node.object_names:
                        obj = bpy.data.objects[i.name]
                        if obj.is_updated or obj.is_updated_data or obj.data.is_updated:
                            # print('calling process on:', node.name, node.id_data)
                            process_from_node(node)
                    node.id_data.has_changed = False
```

</details>

![test update event2](https://user-images.githubusercontent.com/28003269/59564927-bbe1b380-905d-11e9-8ff3-81e9a8617df6.gif)

New implementation should update only those `objec`t nodes which objects was changed. 
There is cases when this have sense: 
- For example there are two objects and only one changed object should be updated for better performance.
 
- Another case is when there are two nodes branches in one layout. One of them include `object` node. Another has expensive algorithm. There is need avoiding updating second branch for better performance during changing of object. It will be possible with new implementation. 

But probably there are some cases which can knock out Blender at all. I can't imagine them now.

**Comment by nortikin** [comment]
hahaha!!! straight to 2.80

**Comment by Durman** [comment]
It looks like there is nothing to discuss here any more. `Object in` node has old well tested code, such changes can make this node unstable what is unacceptabl.
