### ISSUE TITLE
Classification of nodes manipulating with Blender data.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2422]
All data with which Sverchok manipulating can be divided on two groups: internal and external data. So and all nodes can be divided by this attribute. I am not sure how exactly Sverchok should manipulate with Blender data so I decided create such classification of already exesting nodes for finding a hint in which direction to move.

Firstly I imagine Blender data like database. Generally there are two ection for interaction with database: read and write eсtion. Entire classification looks in next view.

- Read
  - Linke
  - Copy
  - Pattern
  - Sorting
- Write
  - Rewrite data of existing objects
  - Create objects
- Read and write
- Remote user interface

![2019-05-24_20-28-51](https://user-images.githubusercontent.com/28003269/58342877-b62fee00-7e62-11e9-97cc-d19d0603dcd1.png)

***Read***
**Linke**
- features:
Nodes provide access to attributes of Blender data. They update provided data each time of any update event of Sverchok. Mostly they were prepared to use with one type of objects. Can be divided on two subcategories. First subcategories gives all data instantly. Second subcategories gives only part of data. For example `F-Curve in` node. It will return only requested points on curve.
- features in UI:
  - They mainly has outputs sockets.
  - Input sockets uses for pointing which part of data to return. 

**Copy**
- features:
Nodes read Blender data and keeps it inside. They update data from Blender object only after request. `Objects in Lite` node can't be entirely related with this categories because it keeps data only with launched Blender. When Blender is rebooted the node read data from Blender database again.
- features in UI:
  - They has buttons for updating data from Blender database.

**Pattern**
- features:
Nodes has some algorithm which uses external data something like a pattern. So they does not just read but do some some job as well.
- features in UI:
  - Nodes has more inputs sockets than others read nodes.

**Sorting**
- features:
They useful for preparing group of objects before reading their attributes. They can stands before other reading nodes in node tree.

***Write***
**Rewrite data of existing objects**
- features:
They can set attributes of existing Blender objects.
- features in UI:
  - They nearly have not output sockets. 
  - They can have option of using auto update of applying of values to attributes of objects.

**Create objects**
- features:
They creates Blender objects and then applies some values to their attributes.
- features in UI:
  - They have string properties for defining a name for object.

***Read and write***
- features:
Close to patterns category, but in spite to them they does not produce new data so I would say they have no any algorithm. Also they have sockets for writing data. Several such nodes can create loop of modification data of objects. By such loop I mean reading data from attribute of an object, modifying this data, and writing data back to the attribute.

***Remote user interface***
- features:
Only several nodes I recognised fitable to this categories. But many other nodes includes elements repeats Blender user interface. For example Fame info node repeats buttons of timeline working area.
- features in UI:
  - Can have not any sockets at all.

**Comment by zeffii** [comment]
i welcome any changes directly like this (for menus and docs) in a svb28 branch. I'll start a thread about the major things I think should / can be addressed soon in the svb28

**Comment by Durman** [comment]
This classification can't be taken as instruction of creating categories. It has narrow point of view. 

It will be great if someone create some rules according of which it will possible to relate new nodes with one or another category. Like a test. You fill all gaps and get back category of node.))

**Comment by nortikin** [comment]
great, but it is hardest. If we have enough nodes for each category, maybe you should create.
As i see, you talk only about blender objects operations, so it will be subcats of objects nodes menu (bpy data, scene, viz)
by the way, my monitor can not handle much of categories, so menu maybe can be compacted with sub menus.
Agree, that bpydata name not handle all senses. Maybe rename it as simply `Blender`?
Scene partially can be named as IN and leave only insertion nodes from blender.
Viz can be named as OUT
i'm ok with network section anyway, maybe it will be more nodes and can be Gcode export node placed there?
If only to sort all beta nodes to their places we can see all the situation... Lets start with beta nodes repatriation.
