### ISSUE TITLE
Sverchok like modifier for Blender objects

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2423]
According my previous issue #2422 Sverchok already good handle with reading and writing data to Blender objects. But what about if we have intention to work with external data in more complex way?

What if there is need not just write some data to object but also modify them and give opportunity for user to change the data. 
I am speaking about something looking like Blender modifiers. 

Unlike Sverchok Blender modifiers do their job only once. If we try to modify any value of object in Sverchok the object will be modified each update event. Also if we apply some value to object it can't be changed outside Sverchok because next update event will rewrite the value back. 

For achieving Blender modifiers logic I can suggest next algorithm. On picture below I represent simulation of array modifier:

![2019-05-24_23-39-48](https://user-images.githubusercontent.com/28003269/58352692-6c083600-7e7d-11e9-910c-8d99e9d89146.png)
![2019-05-25_00-22-35](https://user-images.githubusercontent.com/28003269/58354676-3a926900-7e83-11e9-89c5-57db85a37c70.png)

Firstly I would like to draw attention to `Mesh Expression` node. 
At present it is only node that can catches geometry data of object and keeps it even after rebooting Blender. It is important not to have a link to an object but its copy. 

Than `Matrix Apply` node do the job of array modifier. 
`Mesh switch` node useful for switching between old and new data.

Algorithm of working: 
- Select object for repeating in scene. 
- Press button `from selection` of `Mesh expression` node. 
- Rename object name properties of `Viewer BMesh` node to name of the object.
So you get array of the object.

There is no sense to change array of object via edit mode because Sverchok rewrites changes. So it is similar to Blender modifier behavior. 

If there is need to change initial object:
-  Switch `selected` parameter of `Mesh switch` to 0. 
- Select the object in scene and change object via edit mode. 
- Directly after changing press `from selection` button of `Mesh Expression` node. 
- Switch `selected` parameter of `Mesh switch` to 1
You get array of changed object. 

Well this approach can be slightly boring, alot of click of mouse have been done, but I appreciate that this principle is workable. 

Nothing can stop from applying second array modifier in another direction:
![2019-05-25_00-15-54](https://user-images.githubusercontent.com/28003269/58354434-7973ef00-7e82-11e9-9f87-28e8257b3dee.png)
![2019-05-25_00-23-11](https://user-images.githubusercontent.com/28003269/58354704-4c740c00-7e83-11e9-9028-9758d3d70001.png)

[emulating of Blender modifiers_2019_05_24_20_20.zip](https://github.com/nortikin/sverchok/files/3218462/emulating.of.Blender.modifiers_2019_05_24_20_20.zip)

**Comment by enzyme69** [comment]
Not sure if related, but I have experience this:
Objects In 1000+ objects into Sverchok and trying to process them animating etc is 100x slower than using Object ID and getting the mesh and then process them one by one.

In a way, if we can have SV to read the data from outside one by one is faster than loading GBs of data at the same time.

**Comment by nortikin** [comment]
if you recreate objects from sverchok it go slow. Implementing in blender core only will give modifier-like pipeline.
Anyway, expression node handy.

**Comment by Durman** [comment]
Another example of tricky working with Blender data. 
If there is no need make data completely different and goal is just to modify some parameters of object like to shift an object on ten units by Y axis it is possible to keep impacts frome differente sources simultaneously.
![impacts](https://user-images.githubusercontent.com/28003269/58608730-03beb780-82b6-11e9-85f3-da7a20b48e5b.gif)
<details> 
  <summary>nodetree</summary>  

![2019-05-30_08-38-21](https://user-images.githubusercontent.com/28003269/58608815-526c5180-82b6-11e9-9519-3f538f9e11af.png)

</details>

```Python
"""
in mat m
in obj o
"""
import bpy
from mathutils import Matrix

obj = bpy.data.objects['Cube']

if 'last_val' not in obj or not self.inputs[0].is_linked:
    obj['last_val'] = Matrix()
    
if self.inputs[0].is_linked:
    obj.matrix_basis = obj.matrix_basis + mat[0] - Matrix(obj['last_val'])
    obj['last_val'] = mat[0]
```
So in this way there is need to keep with object value of last impact. And next impact should be equal to difference of next impact and last impact applied to current value. 
I think how it treats now can be named like `hard way` and new principle can be named `soft way`.
