### ISSUE TITLE
Vertex Color IN and OUT?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2424]
A while back ago, SV has Vertex Color In and Out node, but in recent update, I can see the Vertex Color In has disappeared. We still have Vertex Color Out however.

Am I missing something?

Thanks!

**Comment by zeffii** [comment]
version blender / sverchok ?

**Comment by enzyme69** [comment]
Both Blender 2.79 and 2.80 and Sverchok latest. 0.5.9.6 --- I always see this as current version number, have not changed for months.

**Comment by zeffii** [comment]
I don't know about VertexColor out. I only see `SvVertexColorNodeMK3`

**Comment by enzyme69** [comment]
Yes, a while back ago.... Linusy I think made Vertex Color In and Out. Then it become SVVertexColorNodeMK3.

**Comment by enzyme69** [comment]
I have to dig down, but I am sure in the past we have a way to get vertex color and then set vertex color....
https://www.youtube.com/watch?v=PIJ8YYq9tAk

**Comment by zeffii** [comment]
@enzyme69   show me a commit that shows `vertex color out` node  , or when it was removed.

**Comment by enzyme69** [comment]
https://blendersushi.blogspot.com/2016/08/sverchok-vertex-color-node.html

**Comment by enzyme69** [comment]
Around 2 years ago this one node take vertex color both in and out. It was a weird node. Hmm... let me find a commit that does this.

**Comment by enzyme69** [comment]
@elfnor I think commit the color out:
https://github.com/nortikin/sverchok/pull/744

So that we can also see the Vertex Color Out and not just set it.

**Comment by zeffii** [comment]
very good!  well i can't quickly find a reason that part of the node was removed. getting the VCols of an object is not super useful (also judging by the fact that this feature was removed for 2 years without a peep )

**Comment by nortikin** [comment]
poltergeist

**Comment by zeffii** [comment]
give a good reason to add that feature back, i'm struggling to justify adding that back.

just being able to do something `=/=`  being useful
