### ISSUE TITLE
Can viewer draw update real-time?

### ISSUE THREAD

**Issue by rampagedog12** [nortikin/sverchok#2430]
Hello,
I am creating a contour line for an object. I want the contour line change as the object is changed in Edit Mode real-time.

**Comment by vicdoval** [comment]
Hello @rampagedog12, 
At this moment the only way to do what you want is by keeping the animation running (Alt+A) while you are editing

**Comment by portnov** [comment]
Well, what about "live" mode? 3D view -> T panel -> Sverchok tab -> Start live update...

**Comment by rampagedog12** [comment]
@vicdoval it doesn't work.
@portnov Where is live update....?
![image](https://user-images.githubusercontent.com/25874618/58733775-736e9880-83c3-11e9-8f63-ed2f81063ab6.png)

**Comment by portnov** [comment]
Ah.
@rampagedog12 you have to enable it first in preferences of Sverchok addon (blender preferences => addons => sverchok)

**Comment by rampagedog12** [comment]
@portnov Thank you, but it is pretty slow....

**Comment by portnov** [comment]
It is not very fast, yes :)

**Comment by Durman** [comment]
Probably adding handlers of changing of objects would help, as it was discussed here. #2420
I will try implement this in future but not earlier then I will finish with `material node`.)

**Comment by zeffii** [comment]
if the live update is slow, let's discuss why that is.

- the live-update is a modal operator with (currently) a static interval time. You can look in the code, but I think i set it to 3 times a second or something
- the whole nodetree gets updated, a complex tree will therefore be recalculated entirely on each update. That's fine for trivial trees, but complex trees or trees that generate a lot of new geometry depending on the input will have noticeable slowdown.

so? what can be done.

- if your tree is simple (and doesn't produce an exponential amount of geometry ), then all you might have to do is change the live-in operator time-interval ( 10 times a second or more will probably suffice ) -- this I think would be an acceptable modification
- you can currently already use left and right keys to trigger an update to the nodetree, (those keys will trigger a frame change, and that will trigger an recalc)

I'm not sure we'll get an event handler for object changes in edit_mode, and if you think about it, we would need to handler minute changes too -at high rates- (like dragging a vertex of an edge could be 300 updates from start to finish )

**Comment by rampagedog12** [comment]
@zeffii Can the speed be modified somewhere in GUI? I think I probably change or override the speed. The frame change doesn't work for me somehow. In object mode, I use shape key and animate the object. It doesn't work either.

**Comment by zeffii** [comment]
I didn't add a way to increase the interval frequency, but we could do that.

I don't know enough about Blender's animation and shapekeys to suggest anything sensible there.

**Comment by zeffii** [comment]
@rampagedog12   i suggest you do a search for this file, 

https://github.com/nortikin/sverchok/blob/605f7a3c7a1d9e368b78ac7c4a7595a5c7b5c47f/ui/sv_panels.py#L39

in your sverchok folder. Then change `1/13` to `1/24` see if that makes any appreciable change. If not, then i suggest we don't change it in sverchok-master source either.

**Comment by Durman** [comment]
Just for test this can be done simpler. Write next in Blender console. Update events will happen 24 times per second.
```Python
>>> bpy.ops.wm.sv_obj_modal_update(speed=1/24, mode='start')
```

**Comment by zeffii** [comment]
lol yes :)

**Comment by Durman** [comment]
@rampagedog12 I would recommend you update Sverchok and try to use `live update` mode again. I have added some improvements to this mode so dependently your situation it can have better performance.

**Comment by rampagedog12** [comment]
@Druman Live Update doesn't work if I use scripts node....

**Comment by Durman** [comment]
Yes this mode looks after `Objects in` nodes only.
https://github.com/nortikin/sverchok/blob/1807d83ea2cb4efedbb6b340f327bcaa7e3a8776/ui/sv_panels.py#L28
https://github.com/nortikin/sverchok/blob/1807d83ea2cb4efedbb6b340f327bcaa7e3a8776/ui/sv_panels.py#L52-L60

Solution of your problem will be something like this.
![2019-06-24_10-41-00](https://user-images.githubusercontent.com/28003269/59996867-91e74d00-966c-11e9-97e0-ca0558aebb59.png)

**Comment by rampagedog12** [comment]
@Durman I use Object in mk3 as input for my script node, but it doesn't work well in live update...

**Comment by Durman** [comment]
There is known problem. Actually this mode works well if changes of object related with movement of some points. Subdivision and other momentarily operations are cached badly. It looks like I have to investigate Blender API deeper. 😞 
https://github.com/nortikin/sverchok/pull/2458#issuecomment-503666214
What you can do just press ctrl + A buttons for switching on animation but in this case performance can be slow.
Or just press left or right arrow on keyboard for switching to next frame for triggering update of sverchok each time after change of object.
