### ISSUE TITLE
How to display vertex group

### ISSUE THREAD

**Issue by rampagedog12** [nortikin/sverchok#2435]
I want to display the geometry of vertex groups by the group's name.
The searching engine doesn't work in the document....
I am trying Object-in node. There is a Vers_grouped out socket, but I don't know how to make it. There are some tutorials, but all of them are out-of-date...
Is there a forum or community to ask some common questions about sverchok? I think my question is not like some technical ones.

**Comment by nortikin** [comment]
[masking vertices_2019_06_02_21_39.zip](https://github.com/nortikin/sverchok/files/3245266/masking.vertices_2019_06_02_21_39.zip)

**Comment by nortikin** [comment]
![masking vertices](https://user-images.githubusercontent.com/5783432/58767713-2bed3580-8598-11e9-9db6-4b6223e8b8f2.png)

**Comment by rampagedog12** [comment]
@nortikin I was planning to write a scripts node for it... Thank you. This is helpful!
