### ISSUE TITLE
Obj.to_mesh API change in nightly B28 builds, affects plurality of nodes

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2436]
1).  Add plane .
2). Add new node tree sv nodes 
3). Add Node Object in lite 
4). Get object  error ....

Sv node version 0.072

![image](https://user-images.githubusercontent.com/49908008/58768578-f51a1e00-859d-11e9-9ae8-b81cf85d55de.png)

**Comment by zeffii** [comment]
that's odd, i'll look at it.

**Comment by zeffii** [comment]
works as expected in by (slightly older) version of B28

![image](https://user-images.githubusercontent.com/619340/58787892-0dfcf080-85eb-11e9-9b4d-27dc6bbba324.png)

it's possible the b28 API was changed again.

**Comment by zeffii** [comment]
@BennyGovaerts  are you using an official Blender 2.80 beta   or the [https://builder.blender.org/download/](`nightly builds`)?

**Comment by zeffii** [comment]
and looking at the current API for b28, it appears it has been changed again.

https://docs.blender.org/api/blender2.8/bpy.types.Object.html?highlight=to_mesh#bpy.types.Object.to_mesh

now it's 
```python
obj.to_mesh(preserve_all_data_layers=False, depsgraph=None)
```
and might require more attention : /

**Comment by zeffii** [comment]
```python
C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\analyzer\object_insolation.py:
   34          
   35          # mesh_settings = (..., True, 'RENDER')
   36:         # data = OB.to_mesh(*mesh_settings)
   37:         data = obj.to_mesh(bpy.context.depsgraph, apply_modifiers=True, calc_undeformed=False)
   38  
   39          vertices = [vert.co[:] for vert in data.vertices] 

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\object_nodes\object_raycast2.py:
   31          self.matrix_local = OB.matrix_local
   32          mesh_settings = (bpy.context.scene, True, 'RENDER')
   33:         data = OB.to_mesh(*mesh_settings)
   34          vertices = [vert.co[:] for vert in data.vertices]
   35          polygons = [poly.vertices[:] for poly in data.polygons]

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\scene\blenddata_to_svdata2.py:
   62                  ms.append(obj.matrix_world)
   63              if ot:
   64:                 # obj_data = obj.to_mesh(scene, mod, 'PREVIEW')
   65:                 obj_data = obj.to_mesh(depsgraph, apply_modifiers=self.modifiers, calc_undeformed=True)
   66                  
   67                  if o1.is_linked:

C:\Users\zeffi\Desktop\GITHUB\sverchok\nodes\scene\objects_in_lite.py:
   69  
   70          if obj:
   71:             obj_data = obj.to_mesh(bpy.context.depsgraph, apply_modifiers=self.modifiers, calc_undeformed=True)
   72              self.node_dict[hash(self)] = {
   73                  'Vertices': list([v.co[:] for v in obj_data.vertices]),

C:\Users\zeffi\Desktop\GITHUB\TubeTool\tt_operators.py:
  315          settings = False
  316          modifiers = True
  317:         obj_data = obj.to_mesh(bpy.context.depsgraph, apply_modifiers=modifiers, calc_undeformed=settings)
  318  
  319          obj_n = objects.new('MESHED_' + obj.name, obj_data)
```

**Comment by zeffii** [comment]
looks like that was changed 7 days ago - 
https://github.com/dfelinto/blender/blob/846056de6b272d1da087c5ad133f612eecc722af/intern/cycles/blender/blender_util.h#L79

will fix asap.

**Comment by zeffii** [comment]
the downside of the new API, does appear to be that the mesh will not be gotten with `modifiers` and `transforms`   , not a massive issue,  but sucks if you want modified geometry ( seems you would need to apply first? )

**Comment by zeffii** [comment]
@nortikin  @portnov   @Durman   @Kosvor2     seems like this sucks  ..

**Comment by portnov** [comment]
That code you pointed at looks like being under development: there is, for example, `calc_undeformed` parameter, but it is not used... I think it worth asking about it at IRC.

**Comment by zeffii** [comment]
for now i think i'll comment the line out and replace them with an empty function call `obj.to_mesh()`

**Comment by zeffii** [comment]
yeah, such are the pains of coding against something under active development

**Comment by zeffii** [comment]
closing for now. committed changes to alleviate this
