### ISSUE TITLE
Draft mode for node tree

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2439]
From https://github.com/nortikin/sverchok/issues/1990#issuecomment-354586202

  * Enabled/disabled by a toggle button near "Update tree".
  * Input nodes, such as "A Number", have (and store) separate value for Draft mode (which is usually smaller, but it depends). It is displayed and used instead of main value, when the tree is in Draft mode.
  * Some nodes have (and store) separate values of their settings for Draft mode.
  * All nodes have programmatic access to this mode (smth like `if self.tree.draft:`). In draft mode, complex nodes execute some simplified version of their algorithm.

**Comment by Durman** [comment]
As how I understood your suggestion I didn't catch what is purpose of this mode?

**Comment by portnov** [comment]
@Durman , it is supposed that with smaller values of some parameters (such as number of subdivisions), node tree update will be much faster. So you can switch to "draft mode", play with tree and see result updated in real time, then switch to "final mode" and see final result.

**Comment by Durman** [comment]
Possible variant of implementing of set of properties. Not sure that it is workable variant. But in this case it would not have limitation in number of modes.

```Python
class VectorInProps(bpy.types.PropertyGroup):
    x = bpy.props.FloatProperty(name='X')
    y = bpy.props.FloatProperty(name='Y')
    z = bpy.props.FloatProperty(name='Z')

class SvVectorIn ...

    props = bpy.props.ColectionProperty(name='Vector in props', type=VectorInProps)

    for mode_name in modes:
        props.add().name = mode_name

    x = props[active_mode].x
    y = props[active_mode].y
    z = props[active_mode].z
```

**Comment by portnov** [comment]
done
