### ISSUE TITLE
List Match property and use of right click menu

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2443]
On the last nodes I coded i added a couple of enhancements that could be applied to future coding of nodes.
List Match Global and Local:
I have added a couple of Enumproperties to control the list matching in the node.
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/nodes/analyzer/distance_point_line.py#L119-L129
In stead of importing match_long_repeat as usual i add 
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/nodes/analyzer/distance_point_line.py#L23
calling to this:
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/data_structure.py#L185-L200
and use them as in this function to get inputs data:
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/nodes/analyzer/distance_point_line.py#L165-L169
or this case:
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/nodes/analyzer/distance_point_line.py#L184-L188

I add this property to the N-Panel and on the Right-Click Menu

Which brings the next topic: Using the  Right-Click Menu
We already have it in Sverchok and i find a good practice to use it to add advanced parameters of the node
https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/nodes/analyzer/distance_point_line.py#L156-L163

Maybe the List Match Properties could be added as a default node property.. or just use it from now on..
What do you think? Do you find it a good practices? Any idea to improve them?

**Comment by zeffii** [comment]
i have reservations about the usefulness of setting `list_math_global` from one node to apply to all nodes ( which is what 'global' suggests to me.... or do you mean all list_matching for that node ) . For `list_match_local` I 'm supportive.  What if the node has multiple sockets which might benefit from each a different `list_match` routine

I would however not be comfortable retrofitting existing nodes because it does look like that would be extra code for a tonne of nodes, and that's perhaps after a while you realize the feature is only useful in a small portion.

also... that would be more work to then apply those changes to svb28.

maybe i'm missing the point.

**Comment by vicdoval** [comment]
`list_match_global` states for a level 1 data matching of incoming lists, `list_match_local` to a level 2 data.
And they just affect to the node
Probably not necessary for all nodes, but it could be handy for many.
Obviously does not cover different behaviours for each list but opens  some integrated possibilities

**Comment by Durman** [comment]
I have notice this strange parameters of your several last nodes.)) 
I think it is okay for new nodes, but I share Zeffii's concerns about adding such features for o all other old nodes. 

And it's looks like this proposal contradicts to ideas about working with sublevel data. 
#477

As I understand big headache for newcomers is complexity of working with nested lists of Sverchok. So it will be much better if user can have possibility to increase complexity of nestedness data by there own choose. This proposal for old nodes decrease flexibility in this direction.

**Comment by vicdoval** [comment]
Most of the nodes include `match_long_repeat` function so i guess the could also benefit from choosing other ways of matching.
#447 opens many different ideas.. in my own experience I try to work only in two levels (list of data and list of lists of data) and I try to keep the nodes to input and output only this two, maybe it can represent a reduction of flexibility but also a amount of simplicity.
Anyway this issue was more oriented to share this behaviours for future nodes if it is found convenient by to the node developer 😄

**Comment by nortikin** [comment]
it is function alike to grass hoper with rmb click on socket. and they use it much as they know it works  in all nodes. to avoid extra nodes for list matching. In GH you have two ways for that, maybe if 2.80 - to implement now.
