### ISSUE TITLE
Bug report on ui.sv_panels.py

### ISSUE THREAD

**Issue by dimanjy** [nortikin/sverchok#2444]
Bug at line 235:
`for i in range(self.v_int):`

Should be:
`for i in range(node.v_int):`

**Comment by zeffii** [comment]
indeed. that looks wrong. 

https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/ui/sv_panels.py#L235-L238

**Comment by dimanjy** [comment]
...and it would be nice to add after line 232 something like

`col.row(align=True).label(node.label if node.label else node.name)`

to add a label for List Input Node. It looks much better in UI that way, IMHO.

**Comment by zeffii** [comment]
in svb28 we must pass kw `text` to label
```python
col.row(align=True).label(text=node.label if node.label else node.name)
```

feel free to do a PR for 2.79

**Comment by zeffii** [comment]
also.. i think we can get away with
```python
col.row(align=True).label(text=node.label or node.name)
```

**Comment by dimanjy** [comment]
OK, I'll try to do PR later (never did it before - I'm kinda GIT-noob:)
I'm working on Import/Export feature for SV 3D Panel to save public properties for individual trees in a separate .JSON files. Don't know would it be usefull for others, but I need this feature like a breath.

**Comment by zeffii** [comment]
ok, are you saying our current IO/json doesn't store the 3dview panel's Sverchok properties (that you populate manually? )

oh.. i see how that could be useful.

**Comment by dimanjy** [comment]
@zeffii, current export saves whole snapshort of structure and data (as I understood), but I need to save only data and have the ability to modify structure without changing saved data sets (could be a lot of data sets for one tree).

**Comment by zeffii** [comment]
i see/  well, i wrote most of the IO/json stuff so @ me if you're struggling

**Comment by dimanjy** [comment]
@zeffii ok, thanks!

**Comment by dimanjy** [comment]
Just commited a PR #2447

**Comment by zeffii** [comment]
i'm thinking of doing this for 2.8
```python
        def free(self):
            """
            some nodes require additional operations upon node removal
            """

            if hasattr(self, "has_3dview_props"):

                # this code seems to be a necessary evil
                print("about to remove this node's props from Sv3DProps")

                # find and remove a property stored in tree.sv3dprops for the node currently being deleted/freed
                props = self.id_data.Sv3DProps
                for index in range(len(props)):
                    if props[index].node_name == self.name:
                        props.remove(index)
                        break
```

**Comment by zeffii** [comment]
rather than skipping the property in 3dview (when the node doesn't exist). in 2.8 it will look like this now
![image](https://user-images.githubusercontent.com/619340/59501004-e2a3bc80-8e9a-11e9-8a68-bf40c26aa110.png)
