### ISSUE TITLE
Node ID

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2445]
## Problem statement

While I was working with material node, I realized the necessity of having some unique value for node for possibility of distinguish one node from others. Svercho already has node_id method and node_id function in data structure file. 

https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/node_tree.py#L613-L617

https://github.com/nortikin/sverchok/blob/210f48b1d0718820ecc549828f4e3bde133f5fec/data_structure.py#L807-L811

But I don't understand how it works. I have tried a test of method and function and get equal result.

```Python
>>> import sverchok
>>> node = D.node_groups['NodeTree'].nodes['Line']
>>> sverchok.data_structure.node_id(node)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "D:\Серегй\ЯндексДиск\3.Свои_проекты\Blender_code\addons\sverchok\data_structure.py", line 775, in node_id
    return node.node_id
  File "D:\Серегй\ЯндексДиск\3.Свои_проекты\Blender_code\addons\sverchok\node_tree.py", line 615, in node_id
    if not self.n_id:
AttributeError: 'SvLineNodeMK3' object has no attribute 'n_id'
```

Actually I thought that all classes type of Node can have class attributes with only bpy.props assigned to them. 
Well I don't see how this code can work.

Related issues: #166 #116

**Comment by zeffii** [comment]
The bass class `SverchCustomTreeNode` does not explicitly define the `n_id` property. Since not all nodes have the need to be able to identify themselves. (more complicated nodes like BMeshViewers and ScriptNodes do .. and you will see `n_id` declared as properties in those nodes)

**Comment by zeffii** [comment]
but.. when we made the baseclass we added the `node_id` property/decorator for the function, and that property lookup works whever a node does define it's own `n_id = StringProperty` .

**Comment by zeffii** [comment]
does that help?  

- if you have one new node that needs to be able to distinguish itself from peers, then add the `n_id` StringProperty to the `node child class`
- if you think all nodes need a `n_id`, i welcome a good reasoning.

**Comment by Durman** [comment]
> does that help?

Yes it does. I did not figure out that this property can be defined in child class.)) 
It is quite enough for material node. Probably it will be needed for all nodes for new update system but I'm not working with this issue now, so it can be discussed later.

**Comment by ly29** [comment]
In retrospect the design could have been more clear, with n_id as explicit inheritance for classes that needed it. Or at least a comment. 

Still somewhat happy to see my old code around.
