### ISSUE TITLE
Expansion of structure of blender data base

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2446]
## Problem statement

As far as I know there are two ways to adding custom values to Blender objects. First is similar to working with Python dictionary. Second is creating attributes of object by assign to them a Blender property. 

```Python
D.objects['Cube']['my_var'] = 1
```

```Python
bpy.types.Object.my_var = bpy.props.IntigerProperty()
D.objects['Cube'].my_var = 1
```

Viewer BMesh looks like using first way. 
While I worked with material node I found second way more useful because it allows to keep link to other objects like ths:

```Python
bpy.types.Object.my_mat = bpy.props.PointerProperty(name='my_mat', type=bpy.types.Material)
mat = D.materials['Material']
D.objects['Cube'].my_mat = mat
```

 So I created quite complicated data structure and according this I have two questions:

```
Data stored in Material internal type of data of Blender:
Material - (type=ID)
  └ sv_props - (type=Group)
    ├ sv_created - (type=Bool)
    └ children_branch - (type=Collection)
      ├ nodes_data - (type=Collection)
      │ └ required_number - (type=Int)
      └ children - (type=Collection)
        └ mat - (type=ID)
```

- Why Sverchok does not use second way more wide. Is it because this way have less stability or there was no use in using such way before? 
- And If I'm going to develop this approach further where should I store the code of such data structure?

**Comment by zeffii** [comment]
There was a good reason to use the first method ( called a ID_property ). but I can't remember.
One reason I can think of is when you create an ID_property for an object, only that object gets the property. However, if you register a full IntProperty to bpy.types.Object, then every obj in the scene receives that property, even if unused.

> So I created quite complicated data structure

i don't like complicated things : / unless absolutely necessary

**Comment by Durman** [comment]
@zeffii I agree with your altitude about complicated things. Probably I was slightly enthusiastic during writing the code for material node.)) 
I think I can easily to sacrifice some features of this node and reduce complexity. Bad news for me is that I have spend several weeks on this node without result. :disappointed:  
I will delete current request and will create new sooner or later.

**Comment by zeffii** [comment]
sometimes in order to get blender to do something which has no simple API, we resort to very roundabout ways of doing stuff. Avoiding complexity is not always possible, but as you say - it may be possible to sacrifice non-essential features to keep the code simple. that's a winning strategy.

In the end you make nodes to get "shit done", you will eventually (by using it) really learn which features must have solutions. (and potentially justify extra complexity)

**Comment by zeffii** [comment]
regarding the time spent writing code / understanding API -- that's time and knowledge that you'll still keep in the back of your mind while implementing alternatives or other nodes. never time lost.  ( i've plenty of experience of sinking time into nodes that didn't materialize as initially intended )

**Comment by Durman** [comment]
@zeffii Thanks, I hope next attempt will have more success.))
