### ISSUE TITLE
Custom switcher

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2454]
Just an idea of new node. Sometimes there is a wish of having something human readable and not only figures. I have shown on gif only one example of benefit of having such node. 

![custom switcher](https://user-images.githubusercontent.com/28003269/59553816-d4919100-8fab-11e9-9823-7a6292f6321d.gif)

I think this node can have input socket for list of strings. Then node converts them to buttons. Also can have two modes. First mode when only one item can be selected. Second when multiple selections are available.

Output is number of selected item or bunch of numbers if multiple selection is available.

Also this node can be located in SV 3D panel.

**Comment by Durman** [comment]
It have revealed that it looks like it is unexpected way for using Enum property in this way. There are some bugs. I will attempt to switch on Bool property. Probably this will help.
![switcher](https://user-images.githubusercontent.com/28003269/59584316-b3858900-90ee-11e9-91f2-c0f9bac2e7b1.gif)

**Comment by portnov** [comment]
Maybe better specify possible values in settings of the node, in the N panel?

**Comment by Durman** [comment]
Well I thought about it. It means more code and less flexibility. Via socket i can feed any data and hold it in actual condition. So it gives more possibilities.

**Comment by zeffii** [comment]
pretty cool! 

maybe you want to set a limit of 10 or 20 items, because i can imagine if you try to populate 1000 elements (easily done using Float Range by accident) you might be setting up blender to crash, and when the list is populated by a function (as i assume it is..because it's dynamic) then the function is called a lot more times per second on a continual base than you realize.  (stick a print statement in that function to see how much it is called )

**Comment by Durman** [comment]
I have switched from using enum property to BoolVecotrProperty. Maximum size of this property is 32. I update this properties in process method of the node so redraw function does not do any calculation. 

Actually Enum property has the same limitation of size of 32. 
I did not manage to force Blender to crush during coding this node yet. 😄

**Comment by zeffii** [comment]
i see.  i'm surprised we've not hit the enum limit yet :)  nice work/good exercise
