### ISSUE TITLE
Viewer Draw shown in a specific layer

### ISSUE THREAD

**Issue by rampagedog12** [nortikin/sverchok#2461]
Is there any way to make Viewer Draw shown in a specific layer? For example, I want to see my original object in layer 0 and see the viewer draw in layer 1.

**Comment by portnov** [comment]
Afaik, Viewer Draw does not actually create an object to place it on some level or smth like this. It just draws something over the viewport.

Viewer BMesh, on the other hand, does create an object, and in it's settings in N panel you can specify the layer to put that object to.

**Comment by rampagedog12** [comment]
@portnov I am using Viewer Bmesh to create multiple curve objects for preview. Is there any way to let the curve object have different colors....?

**Comment by zeffii** [comment]
if there's a way in Blender to set the `Vertex / Edge / Face` colors of a Mesh object that overrides the Blender defaults, i would definitely implement that for the BMeshViewer.

as for layers..it's not a bad idea.. it would be possible to add a layer option to VD_Experimental
