### ISSUE TITLE
Parameter Set Node for 3D panel

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2469]
Just concept. Would be it useful to have now? 

![2019-06-21_23-52-06](https://user-images.githubusercontent.com/28003269/59947931-a0bcdc80-947f-11e9-8395-ed1395c31360.png)

![set properties](https://user-images.githubusercontent.com/28003269/59947889-82ef7780-947f-11e9-8538-cb9cf3588e30.gif)

branch: https://github.com/nortikin/sverchok/tree/3d_panel_parameter_set

**Comment by nortikin** [comment]
Как это использовать?
Может лучше такое дело сделать доброе:
рамка, объединяющая узлы может создавать группы узлов. Если узел находится в рамке, то в 3дпанели создаётся такое выпадающее меню, без вложений, просто группировать.
