### ISSUE TITLE
Simple, single segment Bezier spline node.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#247]
while we can import splines using object in, I need to have parametric control over splines.
The SN is already written, starting to convert to node after hitting Enter on this message :)

**Comment by sfire** [comment]
There is some description in the [Manual](http://nikitron.cc.ua/sverch/html/nodes/generator/2pt_spline.html):
>The Node is vectorized in the following way. If any of the knots or control points are given in a list that doesn’t match the length of the other lists, then the last value of that shorter list is repeated to match the length of the longest.

>This means; if knot1, control1, knot2 are length 3, 4 and 8 and control2 is length 20 then knot1, control1, knot2 will all get their last value repeated till the full list matches 20 values.

I tried it, but it seems that the **autofill** or **automatch** feature doesn't work.....


![gif](https://cloud.githubusercontent.com/assets/5409756/11963556/cfd56952-a922-11e5-94aa-b538fadd21bd.gif)

**Comment by zeffii** [comment]
@sfire you need to use a _UV Connect_ node,
