### ISSUE TITLE
How to make an object or string as input for scripts node?

### ISSUE THREAD

**Issue by rampagedog12** [nortikin/sverchok#2473]
How to make an object or string as input for scripts node?

I am writing a node that uses an object or string as input. If I use string, it will use string to search object.

**Comment by Durman** [comment]
use ScriptNode - Lite
documentation you can find here: https://github.com/nortikin/sverchok/issues/942
for creating object type socket use this code:
```Python
'''
in my_object o
'''
```

**Comment by rampagedog12** [comment]
@Durman Can I make a loop to create output socket dynamically? In the previous scripts node, the sockets can be created by loops.

**Comment by Durman** [comment]
If I'm not mistaken, self word are available inside script. So you can add sockets in this way:
```Python
if your_statment() and 'my_socket' not in self.outputs:
    self.outputs.new('StringsSocket', 'my_socket')
```
or delete
```Python
if your_statment() and 'my_socket' in self.outputs:
    self.outputs.remove(self.outputs['my_socket'])
```
documentation about editing sockets: https://docs.blender.org/api/2.79b/bpy.types.NodeOutputs.html#bpy.types.NodeOutputs
available socket types here:
https://github.com/nortikin/sverchok/blob/master/node_tree.py

**Comment by zeffii** [comment]
>  In the previous scripts node, the sockets can be created by loops.

that was probably also a bad idea : )
