### ISSUE TITLE
Porting Point Cloud Visualizer Add-On into a Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2476]
I tested this add-on called "Point Cloud Visualizer" by UHLIK just the other day:
https://github.com/uhlik/bpy

The add-on perfectly load and display Point Cloud. I even manage to use SV Exec Node Mod to turn it into animated visulization of point cloud.

What the PCV add-on did not do is to expose the data so we can tinker further with the point cloud. I wonder if any SV developer here can port the add-on as a node that can both display and also we can edit the point cloud?

I am willing to pay $50-99 for such node >> Commision?

**Comment by enzyme69** [comment]
Here is a quick video kind of explaining what I want:
https://youtu.be/dTP1Sv7CkjQ

**Comment by zeffii** [comment]
i suggest you give a link to a directory of a couple of frames of that `.ply`.

The only problem is processing speed, and this would be best achieved with several dedicated nodes (that would need to be not mixed with normal non-numpy sverchok nodes)

- numpy array based math node (scalar, and vector3/4)
- numpy array outputting .ply reader (where frame input socket determines the filename to read)
    - outputting all column data ( normal, color, location... )
- numpy array reading pointcloud object generator
     - 1. either it creates one object and builds up little low-res spheres / icosahedrons (or whatever) and colors the faces according to the input array, rotates the icosahedrons according to normal (optional)
     - 2. or, initially generates a collection and within it as many objects as needed. 
               - downside: initial update would be slow... 
               - upside:but subsequent transforms/recolorings would be rapid. )
     
i might like to try this, but not for money

**Comment by enzyme69** [comment]
[GANESHA_PTC.zip](https://github.com/nortikin/sverchok/files/3338223/GANESHA_PTC.zip)

@zeffii Thanks for your kind response on this. Attached is a couple of PLY sequence. It is pretty big. 

So the add-on already does something like loading and displaying the point cloud on screen of Blender 3D. The animated point cloud was a simple ops hack and that part is "okey" for now. -- my stupid exec node mod hack can be improved.

What I am wondering is whether that add-on can be twisted to give direct access to the point position, color and maybe the normal of point cloud, thus we can further process it with Sverchok nodes.

Blender 3D currently is not very friendly with point cloud only data and usually needing instancing over the point cloud. If the PLY point cloud is already "meshed" like when using Meshlab, it should be easier to work with.

The ideal situation is the ability to display the points, and make modification to the points data and then display it as what Point Cloud Visualizer already does.

**Comment by zeffii** [comment]
those files are binary .ply , so the file-reader part of the add-on would need to be ported (for time-sake)

**Comment by enzyme69** [comment]
Yes the developer says: all functions are pretty much inside a single Class. That add-on seems to just load the binary PLY and magically display it as point cloud with color and normal (if available).

**Comment by zeffii** [comment]
ok. i'm not going to do this. :)

**Comment by enzyme69** [comment]
Ok I'll close this for now... :D
