### ISSUE TITLE
Repeating CommandRecorder maybe Exec Node Mod question

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2477]
I stumbled into this add-on called Command Recorder:
https://github.com/Muthird/CommandRecorder

The add-on record ops and commands, then turn it into a "button" or one ops that runs all the commands.

Sverchok has similar thing in form of **Exec Node Mod**. One thing that's always an issue is the change of mode Object or Edit.

Can anyone recall a node that can randomly select face (edit mode) and then so we can execute it while in edit mode?

NOTE: I'll just save the question for the future...

**Comment by nortikin** [comment]
it seems like MACROS concept. there are many macroses for CAM/CAD as i know
