### ISSUE TITLE
Duplicate along Edge - Blender 2.8

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2483]
## Problem statement

I tried to follow thew first part of this tutorial:
https://www.youtube.com/watch?v=tXhkhTlgd4s

The "Dupliacte objects along edge" node however turns red and there is no output.
I use Blender 2.8.
Please see my screenshot here:
https://ibb.co/0Vmm9Xs

## Expected result

I wanted to have an array of boxes following the path.
(I am trying to make train tracks.)

## Actual result

No array of boxes following the path. :(

## Sverchok version
0.072

I followed this tutorial for installation:
https://github.com/nortikin/sverchok/issues/2326

Am I overlooking something stupid? Thanks in advance! :)

**Comment by vicdoval** [comment]
Thanks for reporting, the bug has been fixed.
Please update and try again 😄

**Comment by morph3us-net** [comment]
Oh, wow, this is even more than I had hoped for! Thank you so much!

May I stupidly ask where exactly I should download?
The master isnt for 2,8 yet, right? And the one in the tutorial should be outdated? 
(Or does GitHub update that link?)
