### ISSUE TITLE
Ctrl + Space Replacement

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2487]
## Problem statement

Ctrl + Space is in 2.8 the default shortcut to maximize one editor .
I propose to change the Sverchok search menu shortcut to Alt + Space 

Any thoughts on this?

**Comment by zeffii** [comment]
i'm OK with alt+space

**Comment by morph3us-net** [comment]
Not that I have any right to have an opinion, but I believe Alt+Space is a kinda unergonomical choice.

How about CTRL (or SHIFT) + F? (for "F"ind)

**Comment by portnov** [comment]
I'll just leave it here: https://developer.blender.org/T55162
Discussion by blender developers of how and why to reassign shortcuts in 2.8.

**Comment by zeffii** [comment]
maybe just 'spacebar'  :)   ,,when i first implemented it.. i think it was spacebar, later it became ctrl+spacebar

if we really get stuck , it might be convenient to implement some UI for sverchok keymaps

**Comment by portnov** [comment]
They've changed Spacebar to F3. Maybe we should chagne Ctrl+Spacebar to Ctrl+F3?...

**Comment by zeffii** [comment]
F keys are kinda annoying on some laptops... (mine)

**Comment by vicdoval** [comment]
The "E" key is also free of sEarch 😄  
also ctrl+A but in my mind this is "select All"
The most ergonomic solution would be the "E" otherwise I would go for Alt+Space
(There would be always the option "shift+ a" and  after "s")

**Comment by morph3us-net** [comment]
Shift + Space, maybe?

**Comment by portnov** [comment]
...escape-meta-alt-control-shift...

**Comment by zeffii** [comment]
we don't have pie menus yet :)

**Comment by zeffii** [comment]
i've changed it to @vicdoval 's suggestion  alt+space ? everyone cool? ok. cool :) let's roll with this for now
