### ISSUE TITLE
Update when deleting object

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2488]
I guess some stepped over this before and can explain me why does sverchok update when one object on the scene is deleted.
I think this update makes blender crash when trying to implement `bpy.context.evaluated_depsgraph_get()` in the "objects in" node to get the mesh with the modifiers applied

**Comment by zeffii** [comment]
last time I checked in 2.8+ the api does not yet give the option to `object.to_mesh()` with or without modifiers. Unless that has changed in the last couple of days

the event handler is indeed clearly not tamed, 

are you attempting to use `evaluated_depsgraph_get() ` in order to get the depsgraph parameter for `to_mesh` ?  I looked at the source code for `to_mesh` and can't make sense of it, but it doesn't look like it's feature complete yet ( @portnov  you looked too, is it still the same ? )

**Comment by zeffii** [comment]
wouldn't we love a more granular event handler system that's tells the event receiver "why" the event was triggered. Some event handlers handle a tsunami of possible events, but can't tell you exactly what happened ( unless i've completely misunderstood those whole thing.. )

**Comment by zeffii** [comment]
if calling `evaluated_depsgraph_get()` causes the event handler for `depsgraph_update_***` to be triggered, then I think we could freeze the nodetree before calling `****_get()`, unfreezing it after. Easy enough to try.

```python
        from sverchok.utils.context_managers import hard_freeze

        ...
        ...

        with hard_freeze(self) as node:
            depsgraph = bpy.context.evaluated_depsgraph_get()
```

usually crashes are infinite eval loops in disguise.  maybe.

**Comment by vicdoval** [comment]
I tried first in the hard_freeze area of the node but It crashes anyway when deleting. 
I also believe is because of infinite looping but i don't know how to solve it 
We would love a more granular event system...

**Comment by Durman** [comment]
Funny thing is that when I studied Sverchok update system I did not reveal such way of updating. 

![2019-07-17_20-33-43](https://user-images.githubusercontent.com/28003269/61393714-9f41d100-a8d2-11e9-93b9-c63af76fe91b.png)

**Comment by zeffii** [comment]
the `freeze` is a method in `class SvNodeTreeCommon(object)`

**Comment by zeffii** [comment]
technically, as soon as an external update triggers `app.handlers.depsgraph_update_pre/post`, that would inturn trigger `objInMk3`, and inside it would trigger `context.depsgraph_evaluated_get()` .. kind of what is described [here.](https://devtalk.blender.org/t/detect-changes-in-object/7467)

**Comment by vicdoval** [comment]
It seems moving:

    dep = bpy.context.evaluated_depsgraph_get()

    Outside handler function helps.

whenever we call evaluated_depsgraph_get a new depsgraph update is triggered so it calls again the handler... it does not matter if it is pre or post update... 
How could we call this function from outside a handler... is there any work around... lets trust the solution will came soon...
I think is a known bug by the blender devs... 
probably when this is fixed we will have a solution https://developer.blender.org/T60094
By now maybe we should remove the "Post" from objects_in node...

**Comment by zeffii** [comment]
maybe something like
```python
    # inside obj in..
    nodetree.dont_update = True
    dep = bpy.context.evaluated_depsgraph_get()
```
then in all (or selected)  handlers... maybe specifically `app.handlers.depsgraph_update_pre/pos`
```python

    # at the very top..

    if nodetree.dont_update:
        nodetree.dont_update = False
        return
```

**Comment by zeffii** [comment]
uch.. lol i have no idea.

**Comment by zeffii** [comment]
seems fixed
