### ISSUE TITLE
Blender 2.80 RC memory error

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2491]
<img width="906" alt="Screen Shot 2019-07-15 at 11 14 56 am" src="https://user-images.githubusercontent.com/3952687/61191814-094f5000-a6f2-11e9-91f6-d19eadd0e0f3.png">

Hmm... this is new. I downladed latest RC Blender 2.80 and tried running SV 2.80 release and getting error above.

Very likely from Blender Dev issue...

But I posted here anyways... since this is a cause that SV does not work. Back to 2.79 now...

**Comment by zeffii** [comment]
thats not good.

**Comment by Durman** [comment]
I does not have such problem on windows.
I would recommend try to import numpy from console.

**Comment by enzyme69** [comment]
I copy paste numpy from outside into this Blender.app directory but giving a weird error. I guess I will be using older beta for now. Cheers~

**Comment by enzyme69** [comment]
[ Issue Unsolved, hopefully next version ]

**Comment by enzyme69** [comment]
A Beta before RC for MacOS works... this version is good:
blender-2.80.0-git20190716.af51988115d4-x86_64
