### ISSUE TITLE
Scripted Node in Blender 2.8

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2492]
## Problem statement

The "scripted node lite" does not do anything in 2.8
It does not show any connections and doesnt show any errors when following the wiki's tutorial on it.

## Steps to reproduce

1.  Follow the tutorial in the wiki [here](http://nikitron.cc.ua/sverch/html/nodes/generators_extended/scripted_intro.html?highlight=script)

## Sverchok version
0.072 b28_prelease_master

**Comment by zeffii** [comment]
use `ScriptNode Lite` , plenty of examples in the issue tracker

**Comment by enzyme69** [comment]
I confirmed, Scripted Node Lite does nothing in Blender 2.80 ... it shows just a node without sockets.

**Comment by enzyme69** [comment]
@morph3us-net You are referring to the old classic Script Node of Sverchok smile 😃 for now, just check for SNL / Scripted Node Lite. The old one still works in Blender 2.79. Older Script node is slightly more complicated to use, but the SNL is easier.

**Comment by enzyme69** [comment]
<img width="1284" alt="Screen Shot 2019-07-16 at 11 03 49 pm" src="https://user-images.githubusercontent.com/3952687/61296713-02bdf700-a81e-11e9-891e-16ef0a7e1a41.png">

When using Sverchok, remember 2.79 is the most stable, but 2.80 is also pretty okey and already working awesome...

**Comment by morph3us-net** [comment]
Yes, a confusion of two script nodes, I am sorry for the disturbance! Maybe that should be noted specifically in the documentation?

P.S.: I hate 2.79, no way I am going back to that! :D

**Comment by zeffii** [comment]
I discontinued the old Script Node in 2.80 - to make a clean break. But... it would be possible to make a mode for SNLite to load old script node scripts. This is however not a priority, or even on my TODO.

i've been progressively more distracted to find time to get around to really stress testing SNLite in 2.80, there are issues that bug me (prime of these issue is the file load feature using `search_prop` - a replacement is necessary )

**Comment by zeffii** [comment]
If i had it my way we would include all docs inside Blender, and no longer have the "read the docs" stuff, so you would only ever see documentation that is relevant for 2.8x
