### ISSUE TITLE
Sverchok generated Path connects subcurves

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2493]
## Problem statement

I have made a small train track test scene. 
Now I want to use that system on a bigger railway system with a lot of curves. They are all in one curve object however and the newly created path from Sverchok connects the last curve point of one subcurve with the first one of the next.
Is there any way to detect these and throw them out?

![screenshot_20190716_120358](https://user-images.githubusercontent.com/43741267/61288893-64537680-a7c8-11e9-9dd9-7d40bb985698.jpg)

Extracting each indivual curve is non feasable, as I would need to copy dozens of nodes dozens of times...

**Comment by Durman** [comment]
There is way in Sverchok to separate objects. 
![2019-07-16_15-06-38](https://user-images.githubusercontent.com/28003269/61289836-5b1fd500-a7db-11e9-8eb0-858b97ac3ed5.png)

**Comment by morph3us-net** [comment]
I dont really see the benefit, I am afraid, as then I need to have like 50 different viewer nodes I would need to connect... But thanks!

**Comment by Durman** [comment]
This not what you are looking for?
![2019-07-16_16-05-24](https://user-images.githubusercontent.com/28003269/61292963-a50cb900-a7e3-11e9-89e5-c6bf71cceac6.png)

**Comment by morph3us-net** [comment]
I fear I am too dumb to understand your example and then on top of that to implement that into the node tree I already have... :(
![screenshot_20190716_141810](https://user-images.githubusercontent.com/43741267/61293697-92d74e80-a7d4-11e9-98f4-a4eb6fc96cab.jpg)

I will close this, as it seems totally doable and is just my fault! Thanks for taking your time!

**Comment by zeffii** [comment]
i should probably mention that some things (1) that work fine in 2.79 don't work so fine in 2.80. It took a long time to get Sverchok relatively stable in 2.79, unfortunately 2.80 has not had many user-hours yet :)

(1)  mostly end point nodes, like the viewers
