### ISSUE TITLE
"Duplicate along Edge" with "Separate Loose Parts"

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2496]
I believe there is only one last hurdle before success:
I am able to separate the subcurves of a sampled curve, but when trying to duplicate the sleepers, I only get the first one.
I believe I need to join a list somewhere? I have tried out a lot of different thing but didnt find the right combination. Could somebody help me again, please? :)

<img width="2732" alt="screengrab_sverchok008" src="https://user-images.githubusercontent.com/43741267/61493269-6fb6c580-a9b3-11e9-85d4-52be0e248898.png">

**Comment by vicdoval** [comment]
Did you try to add a "mesh join" node just before "duplicate obj.." with the data of the receiver?

**Comment by Durman** [comment]
This node as we call is not vectorized. Only way as I see for you is to put this node in monad. But probably this should be fixed.
![2019-07-19_08-14-32](https://user-images.githubusercontent.com/28003269/61508950-50dd2100-a9fd-11e9-9003-ec5d45d07c28.png)

- In your layout select `duplicate objects` node
- Press ctrl + G
- Press exit from monad
- Press vectorize button on `monad` node

**Comment by morph3us-net** [comment]
I never would have figured that one out! Thanks very much!
Only small problem is that I cannot reverse curves, I have some asymmetrical things to duplicate, too, and sometimes they just face in the wrong direction. But yeah, thats for another day!

Thanks very much for the input!

**Comment by zeffii** [comment]
🛑 warning .   `Monad`  is  barely tested in `b2.8`, 

🌲  it would be better (of team sverchok) to (as @Durman said) "vectorize" the `duplicate along edges node`.
  
------

sometimes more complex nodes only handle the first lists of incoming verts / edges / faces / parameters, because at the time the node was submitted there may have been little need for flexibility. But as more users work with a node, a wider range of requirements become self evident - and most of the time we update the node to handle more input.

however, it may not be needed here. you might be able to repeat the Donor mesh an X amount of times , and feed that into the `duplicate along edges node`, so there is a Donor for every Recipient. So the number behind the socket input names match for the Donor and the Recipient.

**Comment by Durman** [comment]
> however, it may not be needed here. you might be able to repeat the Donor mesh an X amount of times , and feed that into the `duplicate along edges node`, so there is a Donor for every Recipient. So the number behind the socket input names match for the Donor and the Recipient.

I tested this case before answering. It can be strange but repeating donor does not give any effect.

**Comment by zeffii** [comment]
in that case... time to fix the node :)

*reads source*

**Comment by morph3us-net** [comment]
if you are already at it, may I kindly ask if you could implement to only duplicate a set amount of duplicates per edge? as of now, if the edge gets too long, the node tries to cram more and more copies along each edge...

also, I would be happy about any idea regarding switching curve  directions.
its clear that I need a "list reverse" before the "duplicate along edges", however I would only like to reverse certain edges, so I would need to mask that out. but how to achieve such mask? any idea?

**Comment by zeffii** [comment]
@morph3us-net  nope.  i'm just reading the source

https://github.com/nortikin/sverchok/blob/30e8d6824365dffcc66bd6ecb36383d80cef832f/nodes/modifier_change/objects_along_edge.py#L250

**Comment by Durman** [comment]
Here example of creating mask which divide input lines on two groups. One of them are shorter than value and other are greatest.
![2019-07-19_14-48-29](https://user-images.githubusercontent.com/28003269/61530156-59048300-aa34-11e9-8652-daf3e52e9326.png)
[example_2019_07_19_10_48.zip](https://github.com/nortikin/sverchok/files/3410734/example_2019_07_19_10_48.zip)

**Comment by morph3us-net** [comment]
Durman, you are a beast! Thank you very much. I will try to adapt this, as it is not the length that conditions the splitting, I am not sure which weay to go, but maybe the active selection or some custom properties or something will do the trick. Thanks for taking your time!

**Comment by morph3us-net** [comment]
I am trying to hook up two "list item" nodes in between my "objects in" and my separate loose parts.
I would like to generate two different resampled splines, so i can reverse one.
However, the "seperate loose parts" node errors out, saying "No data passed into socket `float`"
What am I doing wrong? :)

![sverchok_maskverticesbygroup](https://user-images.githubusercontent.com/43741267/61536844-e4cadf00-aa35-11e9-82c7-69862f2972c6.jpg)

**Comment by zeffii** [comment]
when a node turns red, open the console to get the full error

**Comment by zeffii** [comment]
could be the `Level` setting of the preceding `List Item` nodes..

**Comment by morph3us-net** [comment]
oh, no, I looked in the wrong line, its a list index out of range error
![sverchok_listoutofrange](https://user-images.githubusercontent.com/43741267/61538153-16917500-aa39-11e9-86de-8c1cefa8325a.jpg)

**Comment by zeffii** [comment]
oh... and `Verts Grouped` output, looks to be just outputting the indices that correspond to each set of grouped verts in the Objects.   

lol.  imho this stuff tends to get complicated fast when using Blender objects as your source material for a sverchok node tree.

**Comment by morph3us-net** [comment]
I believe it puts out a list of all vertices being in any group at all.
I updated my post just when you answered, so yeah, I need to somehow mask out better. I believe the answer is somewhere in Durman`s example?

**Comment by zeffii** [comment]
the output of verts grouped can't be used to `list item` the data from the `edges` socket, those are different kinds of indices.  (vertex indices =/= edge indices)

**Comment by morph3us-net** [comment]
okay, I put a `UV Connection` between the vertex `list item` and the `separate loose meshes` and it works as expected, however now the end points get connected again (like the string of a bow)...
i am slowly getting grey hair from this... :D

**Comment by zeffii** [comment]
the UV connect has two U and V 'cyclic'  buttons..

**Comment by morph3us-net** [comment]
they are both already turned off, unfortunately

![sverchok_bow](https://user-images.githubusercontent.com/43741267/61540484-fe702480-aa3d-11e9-91c0-0ebfd431cf06.jpg)

**Comment by zeffii** [comment]
hmm, i'm not sure I understand..and also not sure I would tackle the problem this way.

but! if the vertex sequence is becoming cyclic inside the monad, that's something you would want to debug in a much more simple layout.

**Comment by morph3us-net** [comment]
I want to only resample the curve where I put the originals´ vertices into a vertex group.

Therefore I activated VertexGroups in the `objects in mk3` node and put a `list item` behind it, as seen in the last screenshot. (This should work: #2435)

Now, either I need to get the corresponding edges from the input aswell (how would I mask that?)
or
I put a `UV Connection` node afterwards (as demonstrated in the last screenshot).
The latter isnt as streamlined as the first, but works, however it closes the curves:
![sverchok_bow2](https://user-images.githubusercontent.com/43741267/61545957-e0f48800-aa48-11e9-9447-998034b3d035.jpg)

**Comment by zeffii** [comment]
out of curiosity, 
- `sampled Curve` input in Object In is a single simple mesh?  (no longer Bezier Curves) 
- and `vers groups`.. is something you manually populated using Vertex Groups.?

**Comment by morph3us-net** [comment]
I am struggling to vocalize the exact problem, I am sorry... :(

Yes, it is not a curve anymore, but a mesh with some lines being in a vertex group.
This way, in the end, I want to selectivly reverse some lines and leave some alone.

I made a smaller sample scene, as you suggested.
My problem is the connection of those two seperate lines on the top.
<img width="835" alt="screengrab_sverchok009" src="https://user-images.githubusercontent.com/43741267/61577272-5dd53f80-aae5-11e9-9746-bcda2462d199.png">

I know that I need to `seperate loose parts`, but cannot get it to work with the `vers_grouped` however.
`list item` out the vertices in the vertex group, and then `separate loose parts` based on the original curves obviously doesnt work because there are too many edges in the list for too few vertices.
<img width="866" alt="screengrab_sverchok010" src="https://user-images.githubusercontent.com/43741267/61577346-84e04100-aae6-11e9-851b-7983067366b6.png">

Ideally I would be able to filter out the corresponding edges to those vertices in a group.
As you already told me however, vertex id != edge id.
<img width="903" alt="screengrab_sverchok011" src="https://user-images.githubusercontent.com/43741267/61577493-40ee3b80-aae8-11e9-9f62-6013091b2e14.png">

Is my confusion a little clearer? :/

**Comment by zeffii** [comment]
yes, being able to communicate (or finding the right vocabulary to use) is essential for _all_ problem solving. I like stating very obvious stuff routinely :)

I think the problem is being introduced prior to this step, but... sometimes we can just hack away at the end of a broken solution and still get a usable result.  

you could find a way to drop all edges that are over a certain length. If you're really lucky the indices are all in sequence, then `separate  loose`.. and if the resulting segments are not indexed nicely then we do have a scriptnode that can `correct indices`.

**Comment by morph3us-net** [comment]
in this example the length would work, however not in my real world case, so its unfortunately no option for me...

**Comment by zeffii** [comment]
then the problem must be solved earlier in the layout.. prior to converting to SampledCurve

**Comment by zeffii** [comment]
preferably in a way that doesn't require you to manually set `vertex groups`, ...in essence (correct me if im wrong) you want to do this

1 BezierCurve (with multiple splines) => split into individual splines => each resampled to generate the "normalized equal distribution coordinate sequence" => multiple vertex/edge lists

**Comment by zeffii** [comment]
i think in your eyes the remaining problem there was " how do i procedurally get multiple objects back into a new `objects in` node.

**Comment by morph3us-net** [comment]
the vertex groups thing is for reversing the list order before `duplicate along edge`.
but only for those lines that are in a vertex group.

To give a real life example:
The poles from which the cables of the train hang from are non symmetrical. Sometimes they are on the right side of the tracks, sometimes not. 

Unfortunately `reverse direction` of the curve (before converting to a mesh) didnt work, so I resorted to the method I am trying now.

I do not want to seperate the edges. I want one object to come in.

**Comment by morph3us-net** [comment]
I am very sorry for the confusion. I retested the `switch direction` function of the curve (outside of sverchok) and it does exactly what I want.
Dammit, I am really sorry for the trouble... :(

**Comment by zeffii** [comment]
:  )   now i'm closer to understanding. 

cool. whatever works for you!  all i try to do here is get people less afraid of sverchok

**Comment by morph3us-net** [comment]
...and you are doing a fantastic job! :)
but it is a very hard job nevertheless!

thank you really very muhc for all your patience and the time you are taking to respond!

**Comment by zeffii** [comment]
anytime @morph3us-net   , and.. if not me.. then we have others in the team that like solving/talking issues out.
