### ISSUE TITLE
Finding intersections algorithm

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2497]
Will leave here some explanation, can be useful later. #2480 #2494

Used data structure: https://en.wikipedia.org/wiki/Doubly_connected_edge_list

At this moment I stucked on marking half edges for finding of belonging edge to another subdivision.

The goal is to prove that if left adjacent edge has face the edge at event point is inside this face.

![е1](https://user-images.githubusercontent.com/28003269/61554062-1b701c00-aa6d-11e9-9399-1763873b15a2.jpg)

In the next example e2 is not inside f1 but e1 also is not adjacent any more.

![е2](https://user-images.githubusercontent.com/28003269/61554456-08aa1700-aa6e-11e9-96dc-0b0edea97b1e.jpg)

In this case half edge of e1 does not have face.

![е3](https://user-images.githubusercontent.com/28003269/61554615-65a5cd00-aa6e-11e9-8c10-4b1cdcdf76db.jpg)

Here e2 is really inside f1 but it is not only variant.

![е4](https://user-images.githubusercontent.com/28003269/61554686-9423a800-aa6e-11e9-8019-49745800ed7e.jpg)

Here only half of e2 is inside f1.

![е5](https://user-images.githubusercontent.com/28003269/61554801-dbaa3400-aa6e-11e9-83a3-40aca4630d4d.jpg)

As I suppose this is last variant.

![е6](https://user-images.githubusercontent.com/28003269/61554912-24fa8380-aa6f-11e9-938c-d39dc7112b8b.jpg)

Marking half edges.

![е7](https://user-images.githubusercontent.com/28003269/61554979-570be580-aa6f-11e9-96c1-ea20759a60aa.jpg)

**Comment by Durman** [comment]
![е8](https://user-images.githubusercontent.com/28003269/61556527-0b5b3b00-aa73-11e9-8509-fdf415cc4ce1.jpg)
![е9](https://user-images.githubusercontent.com/28003269/61556554-1dd57480-aa73-11e9-8f84-d482047ba0bd.jpg)
In case if polygon can has holes.
![е10](https://user-images.githubusercontent.com/28003269/61556586-36de2580-aa73-11e9-8d33-db93dafc7c3b.jpg)
![е11](https://user-images.githubusercontent.com/28003269/61556776-b1a74080-aa73-11e9-9144-d8c44b9292c6.jpg)

**Comment by Durman** [comment]
I actually used only information about sets of subdivisions. It is easier to keep that either edge belongs to first set or second or both. But it looks like such information is not sufficient.

![е12](https://user-images.githubusercontent.com/28003269/61560461-65f99480-aa7d-11e9-9c84-17c537b11b8f.jpg)
![е13](https://user-images.githubusercontent.com/28003269/61560506-86c1ea00-aa7d-11e9-9c0e-cc90a51eb806.jpg)
![е14](https://user-images.githubusercontent.com/28003269/61560571-b40e9800-aa7d-11e9-8254-f426bcaeecee.jpg)
I see two possible cases.
![е15](https://user-images.githubusercontent.com/28003269/61560608-ce487600-aa7d-11e9-8269-819b0a392bb9.jpg)
![е16](https://user-images.githubusercontent.com/28003269/61560614-d0aad000-aa7d-11e9-85b5-c9c94549b075.jpg)

**Comment by zeffii** [comment]
i love these drawings :)

**Comment by Durman** [comment]
> i love these drawings :)

Then I'm continuing.))) 
In this drawing shown most left point of a polygon and half edges which contain information about left neighbour. As it shown sometimes up half edge should be taken, sometimes low half edge, for determining left binding component.

![marking edges4](https://user-images.githubusercontent.com/28003269/63926755-6eba8e80-ca5d-11e9-971e-3d10b1635517.jpg)

**Comment by Durman** [comment]
Take in account belonging half edges to faces during splitting edges. 
When edge is splitting the half edges already have actual information about belonging but this information can be not actualf for half edges below event split point. So what i did is just set for such half edges belonging to initial faces which they get from input of the node. After that, `setting face in` algorithm can fill the half edges with actual information. But this is not enough as soon as edges can be overlapping and one half edge can coincide with several faces...
![set face_in](https://user-images.githubusercontent.com/28003269/65934890-18f45000-e428-11e9-9d2b-de80c7a65984.jpg)
![split edge](https://user-images.githubusercontent.com/28003269/65934974-62dd3600-e428-11e9-8528-72e46feca25b.jpg)

**Comment by Durman** [comment]
Solution of dealing with overlapping as I see is a creating something like `super edge` which keeps all overlapping edges and them information.
![overlapping edges1](https://user-images.githubusercontent.com/28003269/66098897-8bdf0180-e5b5-11e9-8929-572c8fd61f5d.jpg)
![overlapping edges2](https://user-images.githubusercontent.com/28003269/66098898-8bdf0180-e5b5-11e9-943f-f5d66239a729.jpg)
When overlapping is detected shortest edge (between event point and lust point of the edge) among overlapping edges should be taken as super edge. Also information about edges should keeps in status of super edge (in this particular case this is a color).

![overlapping edges3](https://user-images.githubusercontent.com/28003269/66098899-8bdf0180-e5b5-11e9-9534-b8407c783cb8.jpg)
![overlapping edges4](https://user-images.githubusercontent.com/28003269/66098900-8bdf0180-e5b5-11e9-80a5-9224bf99bb47.jpg)
When end of super edge is detected current edge should be replace by another shortest overlapping edge and color of the edge should be removed from status. 

Here is the problem of keeping overlapping edges. According that each time shortest edge should be taken it takes O(n) time from list. Or it is possible to keep list in ordered condition but pasting new item will take also O(n) time. Probably a lot of overlapping edges is not expected in input for the node and using list in this case is okay.
![overlapping edges5](https://user-images.githubusercontent.com/28003269/66098901-8c779800-e5b5-11e9-8e3d-4608568d8195.jpg)

#### There are some corner cases when overlapping edges are start in one point or end in one.
![overlapping edges6](https://user-images.githubusercontent.com/28003269/66099928-e0847b80-e5b9-11e9-8e65-cd68199d0df6.jpg)
When overlapping edges shares one start point they should be handled one by one with adding information in the color status.
![overlapping edges7](https://user-images.githubusercontent.com/28003269/66099929-e0847b80-e5b9-11e9-88e2-65648101ec64.jpg)
When overlapping edges shares one endpoint it looks a little bit trickier. Shortest edge should being taken from overlapping list until the end point of current edge is not equal to event point.

**Comment by Durman** [comment]
About complexity of implementation `sweeping line` algorithm :smile: 
https://youtu.be/KLPLvcOfwPU?t=1419

I have tested the algorithm:

| Number of intersection | Time (minutes) |
| --- | --- |
| 6250 | 0.3 |
| 12500 | 0.6 |
| 25000 | 1.2 |
| 50000 | 2.5 |

It proves that implementation is correct.

**Comment by Durman** [comment]
https://youtu.be/dbiO2_GKgGc?t=503

https://docs.python.org/3/library/decimal.html
https://en.wikipedia.org/wiki/Arbitrary-precision_arithmetic
https://simple.wikipedia.org/wiki/Accuracy_and_precision
