### ISSUE TITLE
OCVL (OpenCVLab) is clashing with Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2499]
Not sure exactly how to explain this:

Just like Sverchok is clashing with Sorcar, making Search does not work. Sverchok is also clashing with OCVL add-on. 

If I have OCVL active, some Sverchok nodes are misbehaving and not working properly. If I turn of OCVL, Sverchok works again.

https://github.com/feler404/ocvl-addon/issues/23

Why is it many addon clashing with Sverchok I wonder...

**Comment by zeffii** [comment]
at least for OCVL i can confirm that they reuse portions of Sverchok's code, in `core/sockets.py` i recognize functions that _i_ wrote , this seems to have a strange interaction with systems that run Sverchok too. How exactly that's happening i can only guess at (prior to doing a deep dig.. and installing ocvl... -- which i'm not going to do `:)` )

maybe interference with classes being registered with the same bl_idname .. or classname ,

**Comment by zeffii** [comment]
there are a few socket classes  in SV that don't have the Sv prefix (  StringsSocket  )  and ocVL also registers that class..

so.. yes,  we could fix that..  now would be the time.

**Comment by zeffii** [comment]
>  Why is it many addon clashing with Sverchok I wonder...

because Sverchok is bigger than you think, we register many classes - it seems it's easy to pollute the class namespace in Blender : /

**Comment by zeffii** [comment]
in Sverchok, we have `1138 matches across 278 files`  for StringsSocket , some of those as `.json` . 

so.. definitely issue to correct.  but as mentioned above,  now would be the time - before "prelease" becomes master.

**Comment by zeffii** [comment]
it's these classes in particular that I would rename with a Sv Prefix 
```
VerticesSocket, MatrixSocket, StringsSocket,
```
that would solve ( going forwards ) most of the legitimate bugs that our early names might cause.

but.. in fairness, no other add-on should be using such general class names either ...

**Comment by zeffii** [comment]
it's on my radar @enzyme69   - thanks. at least in this instance I think i'll fix a long standing annoyance with these class names.  No ETA. probably soon.

**Comment by enzyme69** [comment]
Thanks there for impromptu explanation once again, Zeff, ~ no rush, as usual I am just exploring around.
