### ISSUE TITLE
Hilbert 3D Edge is broken and weird Size issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2501]
<img width="588" alt="Screen Shot 2019-08-19 at 11 00 30 am" src="https://user-images.githubusercontent.com/3952687/63233389-3eac0800-c273-11e9-80b9-e7aea2f99aab.png">
<img width="633" alt="Screen Shot 2019-08-19 at 10 59 34 am" src="https://user-images.githubusercontent.com/3952687/63233390-3f449e80-c273-11e9-9fd3-65ed55c64d96.png">

I was making a video tutorial and realize Hilbert 3D in Blender 2.80 SV seems to be broken. The Edge is no longer giving a proper output [[]] 

... and the Size is also broken randomly. It works sometimes, but at other time scaling or resizing the Hilbert gives some broken lines...

**Comment by zeffii** [comment]
@nortikin   :) you did this ??  isn't this broken in 2.79 too?

**Comment by zeffii** [comment]
I think the `size` parameter is not what you think it is @enzyme69 .  If you want to scale the output in the Scene sense, then use the Vector Math node.  The `size` parameter on the node, controls the "petals" (for lack of better word) and to a lesser extent it controls the output scale... or maybe not at all..

but yeah, edges seems fucked.

**Comment by zeffii** [comment]
current code
```py
    def process(self):
        level_socket, size_socket = self.inputs
        verts_socket, edges_socket = self.outputs

        if verts_socket.is_linked:
            Integer = level_socket.sv_get()[0]
            Step = size_socket.sv_get()[0]

            Integer,Step = match_long_repeat((Integer,Step))
            verts = []
            for lev,siz in zip(Integer, Step):
                verts.append(hilbert(siz, int(lev)))
            verts_socket.sv_set(verts)
            if edges_socket.is_linked:
                listEdg = []
                for ve in verts:
                    listEdg_ = []
                    r = len(ve[0])-1
                    for i in range(r):
                        listEdg_.append((i, i+1))

                    listEdg.append(list(listEdg))
                edg = listEdg
                edges_socket.sv_set(edg)
```

**Comment by zeffii** [comment]
but i'm puzzled why you didn't show the simplest reproducible bug

![image](https://user-images.githubusercontent.com/619340/63637697-97b6da00-c67f-11e9-8667-f639fd02d88a.png)

**Comment by zeffii** [comment]
seems ok now:

![image](https://user-images.githubusercontent.com/619340/63639106-2c293880-c690-11e9-9b5e-bb1becac9155.png)

simpler code

```py
    def process(self):
        level_socket, size_socket = self.inputs
        verts_socket, edges_socket = self.outputs

        if verts_socket.is_linked:
            Integer = level_socket.sv_get()[0]
            Step = size_socket.sv_get()[0]

            # make verts
            Integer, Step = match_long_repeat((Integer, Step))
            verts = []
            for lev, siz in zip(Integer, Step):
                verts.append(hilbert(siz, int(lev)))
            verts_socket.sv_set(verts)

            # make associated edge lists
            if edges_socket.is_linked:
                listEdg = []
                for ve in verts:
                    listEdg.append([(i, i+1) for i in range(len(ve) - 1)])
                edges_socket.sv_set(listEdg)
```
