### ISSUE TITLE
Loading Macro GP+ error 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2502]
B28 Sverchok has issue loading this GP+ macro that I use all the time...

<img width="1026" alt="Screen Shot 2019-08-19 at 11 34 41 am" src="https://user-images.githubusercontent.com/3952687/63233776-68662e80-c275-11e9-9423-32e310c3bd7a.png">
<img width="967" alt="Screen Shot 2019-08-19 at 11 34 44 am" src="https://user-images.githubusercontent.com/3952687/63233777-68662e80-c275-11e9-91f2-3b856d2b5b4c.png">

**Comment by zeffii** [comment]
the macro was not updated yet, there is no longer a node called "ViewerNode2" ..

https://github.com/nortikin/sverchok/blob/032e5ee24ac5587600d877e2d8e297c0b2590578/utils/sv_default_macros.py#L262-L272

the closest resemblance to the old VDMk2 is now `SvVDExperimental`.

**Comment by zeffii** [comment]
i'm not super confident that the GP api is not also a little bit different than the Get Asset props node expects.  I've left this un-dealt with because GP is still being worked on in 2.8+

**Comment by zeffii** [comment]
after swapping to the `VD_Experimental` there are now two issues. 

-  the pathlength script doesn't load ( this worries me.. )
-  the GP stroke data is now located in the `.data.grease_pencils`

these kinds of bugs are really boring..

**Comment by zeffii** [comment]
blender's API fails to complete  `bpy.data.texts.load(filepath)`, that might be a Blender bug but i'll download a latest version anyway to test..

**Comment by zeffii** [comment]
it kinda works now I guess..

![image](https://user-images.githubusercontent.com/619340/63637991-2c6f0700-c683-11e9-8f1d-930c05f064ab.png)
