### ISSUE TITLE
Attempting to turn Voxel Remesher Ops into A Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2504]
I am in the process of turning "Voxel Remesher" of Sculpt Mode (Blender 2.81) into some kind of node.

It's gonna be destructive and brute force. I might use Exec Node Mode. The output is hopefully something that can be updated if the node parameter is changing.

So far I made something like this, a once off script that when triggered will "voxel remesh" selected geometry.

```python
import bpy

bpy.ops.object.duplicate()
bpy.ops.object.join()
bpy.ops.sculpt.sculptmode_toggle()

# be careful context incorrect error
bpy.context.object.data.remesh_voxel_size = 0.05
bpy.context.object.data.remesh_smooth_normals = True

#bpy.context.object.data.remesh_smooth_normals = False
bpy.ops.object.voxel_remesh()
bpy.ops.sculpt.sculptmode_toggle()
bpy.context.selected_objects[0].name = "voxel_remeshed"
#bpy.ops.object.select_all(action='DESELECT')

```

Ideally all this should happen inside SV node tree. But I don't know how. Maybe I can get some pointer?

**Comment by zeffii** [comment]
Sverchok is not suitable for executing `Ops` like this. Our best hope is to persuade blender devs to turn that operator into a Bmesh.ops, so we can use it dynamically.

closing because it's not anything we can fix in Sverchok code.... realistically

**Comment by enzyme69** [comment]
<img width="816" alt="Screen Shot 2019-08-21 at 9 59 27 pm" src="https://user-images.githubusercontent.com/3952687/63430062-06691d00-c45f-11e9-83bb-f6714909f1f1.png">

I just realized that this "Voxel Remesh" operator is also on the Object Mode...
