### ISSUE TITLE
`SverchCustomTreeNode.free` wrongly defined

### ISSUE THREAD

**Issue by KoltesDigital** [nortikin/sverchok#2506]
https://github.com/nortikin/sverchok/blob/032e5ee24ac5587600d877e2d8e297c0b2590578/node_tree.py#L431

I think the intent is to define the function in the class, not in the other function.

**Comment by zeffii** [comment]
this class is a `mix-in`, and this function is necessary.

it's possible that your `pylinter` doesn't like the style, but it's working OK as far as i can tell.

**Comment by zeffii** [comment]
oh.. you mean it is indented.. yeah, i agree.. it should be part of the class.

**Comment by zeffii** [comment]
not sure how that happened?!

**Comment by zeffii** [comment]
i've dedented this again. (or maybe it was never indented correctly, but it was tested as a separate function call a while back.. ) 

i suspect this is not finished.. but i've committed a fix to the issue raised.
