### ISSUE TITLE
Using Blender 2.81 SV nodes and back to Blender 2.80 = nightmare undefined socket

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2520]
I've been using 2.81 alpha for a while and SV is running fine.

What shocked me is when I downloaded the latest official Blender 2.80 and all the nodes are broken (undefined sockets). I wonder what's going on...

<img width="1230" alt="Screen Shot 2019-09-05 at 10 29 30 pm" src="https://user-images.githubusercontent.com/3952687/64341959-db6cf480-d02c-11e9-9ef7-4e8ed906d3ae.png">
<img width="1202" alt="Screen Shot 2019-09-05 at 10 30 06 pm" src="https://user-images.githubusercontent.com/3952687/64341960-db6cf480-d02c-11e9-8d82-ad5e3353e471.png">

**Comment by zeffii** [comment]
only use 2.8 nightlies please.   we can't make this stuff compatible with all versions of 2.8+

**Comment by zeffii** [comment]
maybe you have a different sverchok for 2.80 and 2.81  , and trying to load a file build with 2.81 into an older 2.80 will encounter issues with socketse because we renamed "StringsSocket". and "VerticesSocket" and "MatrixSocket" .   You see the socket called "Object" this was not renamed.

this will happen. adding code to make this not happen just adds noise to the codebase.

**Comment by zeffii** [comment]
we expected this, and did it anyway :)

**Comment by zeffii** [comment]
for anyone else reading, it was necessary to rename these sockets because they potentially interfered with other add-ons that also used those socket names.  

https://github.com/nortikin/sverchok/pull/2500

it's the price of progress.

**Comment by zeffii** [comment]
I don't think all is lost @enzyme69  , you can upgrade the 2.80 sverchok.. so it has new sockets.

if you really get pannicky, then have a separate Blender 2.80 installation with a newer version of SV installed. The logistics of that i will leave up to you

**Comment by enzyme69** [comment]
Thanks again @zeffii Yeah, I guess as long the node name is there...
