### ISSUE TITLE
Any Tips on UV Texturing in Sverchok? - "The Penguin" Umbrella

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2532]
<img width="942" alt="Screen Shot 2019-09-12 at 10 51 38 am" src="https://user-images.githubusercontent.com/3952687/64745511-814bc200-d54b-11e9-9c57-65170ed17f2f.png">

I made a silly procedural Umbrella setup using SVerchok and also the shader for Eevee or Cycles, it's all good and just need baking and I need... UV layout.

I was wondering if UV has been mentioned in the past a couple of times and how is SV would best deal with UV for things like Cylinder, Sphere, Cone, Pipe, ...

For Polyline Curve, we solved that somewhat because Blender has auto-UV for long curves...

Cylinder MK2 ==> UV should be pretty straight forward right? :)

**Comment by enzyme69** [comment]
<img width="934" alt="Screen Shot 2019-09-12 at 11 39 05 am" src="https://user-images.githubusercontent.com/3952687/64747301-f28e7380-d551-11e9-8c84-35c09b05c7c0.png">

It's interesting because I use quick manual Spherical here in a shape that's already like umbrella, but maybe I could get better UV result...

**Comment by enzyme69** [comment]
Might be related and unsolved:
https://github.com/nortikin/sverchok/pull/2218

**Comment by zeffii** [comment]
not sure how you expect to get bet UV with topology like that..

**Comment by enzyme69** [comment]
Just wondering if we got way to auto UV yet, if we have multiple shape
islands... and if we need different materials~

**Comment by Durman** [comment]
@enzyme69 Sverchok does not have nodes for dealing with materials and uv maps at this moment and I don't think such nodes will hapend soon even if there are some PRs of such nodes. It should take some time for searching of approach how Sverchok should deal with all of this.

**Comment by enzyme69** [comment]
Thanks Durman, I'll close this for now, I will resort to just "dropping vector" and project UV flat~ cheers~
