### ISSUE TITLE
2.80: What is socket.socket_id ?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2539]
On 2.80, one of the tests is failing with the following message:

```
======================================================================
ERROR: test_intersect_edges (intersect_edges_tests.IntersectEdgesTest2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/tests/intersect_edges_tests.py", line 16, in test_intersect_edges
    result_verts = get_output_socket_data(node, "Verts_out")
  File "/home/portnov/.config/blender/2.80/scripts/addons_contrib/sverchok/core/socket_data.py", line 150, in get_output_socket_data
    socket_id = socket.socket_id
AttributeError: 'NodeSocket' object has no attribute 'socket_id'
```

I was not able to find out what socket.socket_id is supposed to be; it is not mentioned in bpy documentation. Maybe it was some undocumented property that was removed from 2.8? Or was it somehow set by sverchok? I could not find any assignments to this property in our code.

**Comment by portnov** [comment]
Aah, I got an idea...

https://github.com/nortikin/sverchok/blob/d19fe8838339a63f785a497a3c19618d13b586f4/node_tree.py#L103-L106

For some reason the socket we are working with is not an SvSocketCommon, but a general NodeSocket...

**Comment by portnov** [comment]
The actual problem was that we Blender 2.8  was not able to correctly load blend file with sverchok node tree, which was saved in 2.79. Nodes were loaded, but they had incorrect types.

**Comment by zeffii** [comment]
cool :)
