### ISSUE TITLE
Viewer Draw - extras

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2558]
- [x] attr socket (in which data can be sent to turn off vd node - handy if you know the data is useless for drawing)
     attrs: 
     - draw_fancy
     - mute
     - edge base color
     - face base color
     - etc
- [x] zfighting needs a solution :) : https://stackoverflow.com/questions/30567044/how-do-i-draw-a-wireframe-mesh-with-hidden-lines-removed-in-opengl-es
- [x] rlick menu for draw_ext props..

**Comment by zeffii** [comment]
FINALLY.

![image](https://user-images.githubusercontent.com/619340/65838827-7a70cd80-e307-11e9-8546-1fd15badacaa.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2559/files

**Comment by enzyme69** [comment]
Pretty awesome Zeffii~

**Comment by zeffii** [comment]
this is currently disabled in `prelease_master` - but it will be back soon.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/65894010-48b04300-e3a9-11e9-905b-3fd023bf40f6.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/65908341-8a9bb200-e3c6-11e9-90c2-7b08b8d6f5d7.png)

i'll propose a dictnode too...
