### ISSUE TITLE
Not an Issue, Trying To Contact You ref TinyCAD

### ISSUE THREAD

**Issue by Clockmender** [nortikin/sverchok#2582]
I am writing to you here as a means of contacting you, TinyCAD is archived, so I can't through that.

I have been developing a set of CAD tools for Blender, you can find info here:

https://devtalk.blender.org/t/making-an-add-on-for-precision-modelling-cad-tools/8637

IT has come a long way since the first post. I am interested in incorporating XALL and E2F from your TinyCAD into my Precision Drawing Tools (PDT) and wondered if you would have any objections to this as I think these two functions would add considerably to PDT's capabilities.

Can you let me know if you have any objections to this, I would, of course, credit you with writing the  code. I am proposing to add these two functions into my N Panel menu.

Please let me have your thoughts.

Cheers , Clock.

**Comment by zeffii** [comment]
no objects at all @Clockmender   :)

I no longer maintain tinyCAD, and expect it to be expelled from Blender's default add-ons eventually.

**Comment by zeffii** [comment]
in case you do intend to reuse that code, i recommend you look at the Sverchok Node version which has several optimizations.

https://github.com/nortikin/sverchok/blob/master/nodes/modifier_change/edges_intersect_mk2.py

**Comment by zeffii** [comment]
great to see more CAD heads helping to get good CAD functionality in Blender -- it was a desert at one point, now.. it's looking like an oasis. Nice work @Clockmender

**Comment by Clockmender** [comment]
Thank you for that, I will compare new to old to see differences. We plan a new release this weekend, if we get the Docstrings all completed, then I will incorporate XALL, E2F and BIX into my PDT Add-on. I confirm that I will credit you for the code.

Thank you for this, it saves me "re-inventing the wheel". You can close this now if you want, I will keep updates of these functions on the devtalk thread.

PS. I really like Sverchok...

**Comment by zeffii** [comment]
you're welcome, i'll check out PDT eventually -- i rarely model non procedurally at the moment.
