### ISSUE TITLE
VD Experimental

### ISSUE THREAD

**Issue by unity2k** [nortikin/sverchok#2587]
## Problem statement

VD Experimental can crash Blender

## Steps to reproduce

1. Add the Cricket
2. Connect Cricket faces to VD Experimental faces
3. Hit Bake without connecting anything to VD Experimental verts

## Expected result

Nothing really as I forgot to connect Verts between the two nodes but I didn't expect an instant shutdown of Blender either.

## Actual result

Blender disappears

## Sverchok version

Most recent download of the B28 pre-release master that Cricket was just added to and it's on the most recent 2.81 nightly.

**Comment by zeffii** [comment]
scary :)    thanks for the report

**Comment by zeffii** [comment]
totally confirmed :)

**Comment by zeffii** [comment]
fixed: https://github.com/nortikin/sverchok/pull/2299/commits/875043b44488a0387d8aaffb7f5d232543859b16
