### ISSUE TITLE
VD experimental NGon shading issue

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2589]
I'm not super sure where to start with this, I rarely generate ngons. Some nodes however (like bisect) do output ngons, it would be nice to be certain that the normals (or clockwise/anticlockwise direction of the ngon-vertices ) is an artifact of the Viewer node .. or not. 

I think it is..   but we'll see.

**Comment by zeffii** [comment]
so... let's reduce this sucker :)

**Comment by zeffii** [comment]
wow.

this seems to work..
```
            subcoords = [Vector(coords[idx]) for idx in idxset]
            for pol in tessellate([subcoords]):
                concat([idxset[i] for i in pol[::-1]])
```

**Comment by Durman** [comment]
I get strange result with this function
![2019-10-06_20-39-47](https://user-images.githubusercontent.com/28003269/66272334-8285bb80-e879-11e9-93d2-260d9ae73f1a.png)

**Comment by Durman** [comment]
Probably you are looking for something like this?

```Python 
def is_ccw_polygon(all_verts=None, most_lefts=None):
     """
     The function get either all points or most left point and its two neighbours of the polygon
     and returns True if order of points are in counterclockwise
     :param all_verts: [(x, y, z) or (x, y), ...]
     :param most_lefts: [(x, y, z) or (x, y), ...]
     :return: bool
     """
     def is_vertical(points):
         # is 3 most left points vertical
         if almost_equal(points[0][x], points[1][x]) and almost_equal(points[0][x], points[2][x]):
             return True
         else:
             return False
     if all([all_verts, most_lefts]) or not any([all_verts, most_lefts]):
         raise ValueError('The function get either all points or most left point and its two neighbours of the polygon.')
     if all_verts:
         x_min = min(range(len(all_verts)), key=lambda i: all_verts[i][x])
         most_lefts = [all_verts[(x_min - 1) % len(all_verts)], all_verts[x_min], all_verts[(x_min + 1) % len(all_verts)]]
     if is_vertical(most_lefts):
         # here is handled corner case when most left points are vertical
         return True if most_lefts[0][y] > most_lefts[1][y] else False
     else:
         return True if is_ccw(*most_lefts) else False
```

**Comment by zeffii** [comment]
@durman,    `pol` are indices into the ngon that was received by tesselate,   not indices of the verts list.

**Comment by Durman** [comment]
Well, actually it works but probably this can has less performance if the only need is define order (cw or ccw) of points in a polygon.))

![2019-10-06_20-50-04](https://user-images.githubusercontent.com/28003269/66272488-769af900-e87b-11e9-9939-2c4642cbca5a.png)

**Comment by zeffii** [comment]
like
```python
v1 = (. . .)
v2 = (. . .)
v3 = (. . .)
v4 = (. . .)
v5 = (. . .)
v6 = (. . .)
v7 = (. . .)
remapped_indices = tesselate([v3, v4, v5, v6, v7])   # v3 is index 0 , v4 is index 1
for pol in remapped_indices:
    pol  #  indices in pol will refer to the order in which the vectors where received
```

**Comment by zeffii** [comment]
i'll show in sverchok / snlite :)

**Comment by Durman** [comment]
I have understood the idea. The function returns indexes of triangulated polygon.

**Comment by zeffii** [comment]
there's a lot to be optimized in VD_experimental.. i'm avoiding kneejerk changes :)

**Comment by zeffii** [comment]
until now I hadn't considered calculating the normal for all polygons, before triangularization.
knowing the normal before triangularization (even quad.. not just ngons) can be visually desired too.
the chances that normal calculation will be different for each tri of an ngon, are relatively large (i've seen it with my own eyes..)

**Comment by Durman** [comment]
Wow, even this is possible.
![2019-10-06_21-06-40](https://user-images.githubusercontent.com/28003269/66272704-27a29300-e87e-11e9-8fca-4ec081be531d.png)

**Comment by zeffii** [comment]
hmmmmm...
![image](https://user-images.githubusercontent.com/619340/66272753-15205d80-e86e-11e9-9cda-41e18fe6cd37.png)

**Comment by Durman** [comment]
Perhaps, VD node should not care about normals at all?
All other nodes should give polygons with front side in counterclockwise order and backside with clockwise order of points.

**Comment by zeffii** [comment]
facet face colour is determined by normal, and cw/ccw direction of index sequence - it has to draw something : )

**Comment by zeffii** [comment]
cool feature to get `hole in polygon` @Durman  :)

**Comment by Durman** [comment]
Yes, this looks familiar. I saw something similar already.))) #2498

I don't know how viewer node is working but sometimes it flips polygons in spite of their order of points.

![2019-10-06_21-06-40](https://user-images.githubusercontent.com/28003269/62184940-6a715780-b371-11e9-8b82-e5fd5bcd26d0.png)

**Comment by zeffii** [comment]
yeah @Durman .  i wont revisit b279 sverchok,  but i'll try to get a Viewer "Panzer" node going, which brute forces through things.

**Comment by Durman** [comment]
As I understand the viewer node try to check either a polygon is in ccw order or cw and sometimes do this wrong. But we can have an arrangement that all polygons should be in ccw order only. In this case viewer node should not care about it any more.

**Comment by Durman** [comment]
I don't think there is need in fixing viewer node in 2.79. I meant that VD node should perhaps has similar problem.

**Comment by zeffii** [comment]
sometimes with `bmesh.ops` the output may not be consistent.  but i'm starting to think that it was the viewer 's fault in some cases.

i predict that if you also apply the `reverse(pol)` in vdmk2, that it will draw correct colors.

**Comment by zeffii** [comment]
in direct mode (old openGL style VDMK2) , the colour is calculated before triangulation.
```python
    glColor3f(*face_color)

    if (num_verts in {3, 4}) or (not forced_tessellation):
        glBegin(GL_POLYGON)
        for point in pol:
            vec = data_matrix[i] * dvk[point]
            glVertex3f(*vec)
        glEnd()

    else:
        ''' ngons, we tessellate '''
        glBegin(GL_TRIANGLES)
        v = [dvk[i] for i in pol]
        for pol in tessellate([v]):
            for point in pol:
                vec = data_matrix[i] * v[point]
                glVertex3f(*vec)
        glEnd()
```

unfortunately that's not the way we do it anymore.

**Comment by zeffii** [comment]
anyway. i'm happy with reversing the tesselated polygons, it seems to work as expected.

or ...maybe ask in IRC if this is a bug

**Comment by zeffii** [comment]
in b279 SV vdmk2 - i do this... hahahah
```python
def get_color_from_normal(dvk, pol, num_verts, vectorlight, colo):
    if num_verts <= 4:
        normal_no = normal(dvk[pol[0]], dvk[pol[1]], dvk[pol[2]])
    else:
        normal_no = normal(dvk[pol[0]], dvk[pol[1]], dvk[pol[2]], dvk[pol[3]])

    normal_no = (normal_no.angle(vectorlight, 0)) / pi

    r = (normal_no * colo[0]) - 0.1
    g = (normal_no * colo[1]) - 0.1
    b = (normal_no * colo[2]) - 0.1
    return (r+0.2, g+0.2, b+0.2)

```
that doesn't seem to be a correct strategy for complex ngons

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/66273593-916a6f00-e875-11e9-8c45-3884b38a033e.png)

**Comment by Durman** [comment]
Yes not all points are appropriate for calculation a normal.
<details> 
  <summary>tree</summary>  

![2019-10-06_22-19-43](https://user-images.githubusercontent.com/28003269/66273716-743e9c00-e887-11e9-9994-3442ed1f9ed4.png)

</details>

![normal](https://user-images.githubusercontent.com/28003269/66273698-3a6d9580-e887-11e9-8176-dac3b483af82.gif)

**Comment by Durman** [comment]
It should be something like this.

``` Python
if ccw_polygon:
    calc_normal(vecs[most_left_index - 1], vecs[most_left_index], vecs[most_left_index + 1])
else:
    calc_normal(vecs[most_left_index + 1], vecs[most_left_index], vecs[most_left_index - 1])
```

**Comment by zeffii** [comment]
in the b279 version i think we could pass all polygon verts to normal, as it accept 3 or _more_ vertices (no limit )

**Comment by zeffii** [comment]
i files a bugreport anyway. https://developer.blender.org/T70594

**Comment by zeffii** [comment]
i'm happy at some point in the future to rectify the b279 viewer issue, relative to normal calcs.  but closing for now..    OR anyone still using b279 @Durman @nortikin   feel free to fix -- https://github.com/nortikin/sverchok/issues/2589#issuecomment-538771728 by passing all indices of the polygon to `normal` and not just the first 4 :)

**Comment by zeffii** [comment]
i think that would look like
```diff
- normal(dvk[pol[0]], dvk[pol[1]], dvk[pol[2]], dvk[pol[3]])
+ normal(*[dvk[ip] for ip in pol])

**Comment by Durman** [comment]
Yes, this is working. I'll make PR.
![2019-10-07_13-14-42](https://user-images.githubusercontent.com/28003269/66299396-7eeb4680-e904-11e9-8243-36a213e0e5ca.png)

**Comment by zeffii** [comment]
blender devs tessellate_polygon https://developer.blender.org/T70594

**Comment by zeffii** [comment]
i'll undo the `reverse()` - asap
