### ISSUE TITLE
bisect node when used to make a cross-section can generate undesired results.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2593]
bisect node will generate this, with inner and outer on. perhaps we should use the `tessellate_polygon` routine for that..  ? 

![image](https://user-images.githubusercontent.com/619340/66300932-768c0f00-e8f6-11e9-8db4-78f059fc1d43.png)

**Comment by Durman** [comment]
It's not simple as can be looked like. Before tessellation function there is need in determining which polygon a hole belonging. I mean if there are two torus, points of first torus should be put to the function and then points of second but not simultaneously.

**Comment by zeffii** [comment]
maybe when user does crosssection with bisect node, there can be an option to use the code of the CrossSection node instead.

**Comment by Durman** [comment]
As I see neither of this two nodes does not cut a torus properly.

**Comment by zeffii** [comment]
yeah, the Plane of the cut surface is known ( because we pass it : )  ) and we can invert transform to be flat on Z., strip Z coordinate, do calculations, get/return indices,

**Comment by zeffii** [comment]
i find _this_ stuff fascinating, but i you to do it @Durman  :)     -- else for me it's just a bit far down on my todo.

**Comment by Durman** [comment]
> we can invert transform to be flat on Z

It will be cheaper just project section to one of the XY, XZ or YZ surface

Well, I can make some investigation in this direction but not before i'll switch to 2.8

**Comment by Durman** [comment]
![2019-10-07_15-42-33](https://user-images.githubusercontent.com/28003269/66308864-2a05fb00-e919-11e9-934d-f847230a3732.png)

![torus](https://user-images.githubusercontent.com/28003269/66308844-1bb7df00-e919-11e9-902b-bb815e0ea7ef.gif)

**Comment by Durman** [comment]
I'm trying to implement all code which I had done for `merge mesh` node in a package with name `geom_2d` for Sverchok 2.8. The code from this package will be possible to use in different nodes. 

I have tried to use it for new mode of the `intersect edges` node. At this moment it looks in this way :)

```Python
def intersect_sv_edges(sv_verts, sv_edges, accuracy=1e-5):
    # Merge several Sverchok mesh objects into one with finding self intersections
    mesh = DCELMesh()
    mesh.from_sv_edges(sv_verts, sv_edges)
    find_intersetions(mesh, accuracy)
    return mesh.to_sv_edges()
```
![2019-10-16_16-33-43](https://user-images.githubusercontent.com/28003269/66919639-c3788f80-f032-11e9-97d4-0bcdf5b42081.png)

**Comment by zeffii** [comment]
looks superb, and tidy :)

**Comment by portnov** [comment]
`mesh = Mesh(); mesh.from_xxx()` should be `mesh = Mesh.from_xxx()` (i.e., `from_xxx` should be `@staticmethod` or `@classmethod`).

**Comment by Durman** [comment]
Dcel data approximately looks in this way:
```Python
class DCELMesh:
    accuracy = 1e-5

    def __init__(self):
        self.points = []
        self.hedges = []
        self.faces = []

    def from_sv_faces(verts, faces):
        some code...

        self.points.extend([Points(co) for ... ])
        self.hedges.extand([HalfEdge(origin) for ... ])
        self.faces.extand([Faces(hedge) for ... ])
```
Well I implemented this in the way when several Sverchok meshes can be included in one DCEL mesh. It is useful for finding intersection between two SV objects.
```Python
mesh = DCELMesh()
mesh.from_sv_faces(vert_obj1, face_obj1)
mesh.from_sv_faces(vert_obj2, face_obj2)
find_intersections(mesh)
return mesh.to_sv_mesh()
```
I think staticmethod or classmethod does not allow to join several meshes and implement another method would be overkill.

**Comment by Durman** [comment]
What can be achieved with edges to faces node (bisection of torus and sphere). The logic is not correct but i'm afraid that output of bisect node is not enuf to fill edges in more proper way.

![edges to fases fill holes4](https://user-images.githubusercontent.com/28003269/67941187-91e4f400-fbee-11e9-9574-981eb00612fa.gif)

**Comment by zeffii** [comment]
looks OK to me?

**Comment by Durman** [comment]
For me result of intersection torus with plane as hole is not natural.)

**Comment by Durman** [comment]
Now it can be like this:
https://gist.github.com/16210098bf0e1eadc39cfc0fc953166e
![2019-11-26_16-51-47](https://user-images.githubusercontent.com/28003269/69635090-0df71e00-106d-11ea-8ff6-4c37609bfa31.png)

 It is actually not fully correct solution and it is reason why i don't want to implement such approach inside Bisect node. As I see Bisect does not produce enough information about intersection for the problem could be solved carefully.

**Comment by Durman** [comment]
I see the solution in completely rewriting the node. The new algorithm should check all input faces whether they have intersection or not with plane. So it is easy and pretty fast. More tricky thing is to rebuild mesh according found intersections. 
Another approach would be possible if Sverchok would have test which can say to which face intersection edge belong. 
Either way both variants looks too complicated for me now. I hope that temporary solution can work for a while.))

**Comment by zeffii** [comment]
i'm happy to close this, and recognize the inherent difficulty in the algorithm
