### ISSUE TITLE
Nodes to forget

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2601]
Any reason to keep this nodes out of old_nodes?
CylinderNode
SvProfileNodeMK2
CentersPolsNodeMK2
SvConvexHullNode
Formula2Node
SvInterpolationNode
EvaluateLineNode

**Comment by zeffii** [comment]
nope.

**Comment by vicdoval** [comment]
The EvaluateLineNode has different bl_idname/class_name.
This unables the old_nodes automated system to work.
I suggest to delete it and don't look back.
Any better idea?

**Comment by zeffii** [comment]
so much stuff will just fail - this is not unintentional.   :D

**Comment by zeffii** [comment]
put it this way, no single feature (that i'm aware of) has even been truly 'regressed' out of sverchok, it's always been a matter of improvement / increase convenience.

**Comment by zeffii** [comment]
only regressions are features disappearing/changing from `bpy`, or `bmesh` -- where no one has been interested yet in implementing them afresh. 

like now with the particle nodes being developed by jacques, it feels almost redundant to have any attempt of b28 sverchok-nodes to control particles yet ..

**Comment by vicdoval** [comment]
So you are fine with me deleting it...?

**Comment by zeffii** [comment]
yes. do it.

**Comment by zeffii** [comment]
all particle nodes, will have no use in blender 2.82 when the current particle system becomes end of life.

i suspect the built in particle node system will be sufficient, and to some degree 'remote controllable' via sverchok :)

**Comment by portnov** [comment]
This is done as far as I see....
