### ISSUE TITLE
VD Experimental - experiments

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2608]
i want to keep this open for a while, there's so much that can be done directly in a shader. i'm thinking about doing this in a `development viewer`m kicking out VD_basic_lines.

- [x] dashed lines   
- [x] smooth shading, precalcuated
- [x]  facet shading, precalcuated
- [ ] facet shading from geometry
- [ ] facet normal shading from geometry
- [ ] transparent edges
- [ ] transparent faces
- [ ] rendering the draw frame of a given Viewport, to a png. (at any resolution.. and AA)

attempt line smoothing?
    ```
    glEnable and glDisable with argument GL_LINE_SMOOTH
    ```

### instancing

https://learnopengl.com/Advanced-OpenGL/Instancing

### numpy

http://pyopengl.sourceforge.net/context/numeric_arrays.html

--------

# useful links

_color from normals.. without calculating everything in advance_

- https://stackoverflow.com/questions/34486670/opengl-shader-to-shade-each-face-similar-to-meshlabs-visualizer 

- https://www.gsn-lib.org/docs/nodes/ShaderPluginNode.php

_interesting wireframe modes_

- https://github.com/rreusser/glsl-solid-wireframe

- https://github.com/martin-pr/possumwood/wiki/Wireframe-using-a-Geometry-Shader

# GL insights

- https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glLineWidth.xhtml

- https://www.labri.fr/perso/nrougier/python-opengl/code/chapter-09/linestrip-3d.py (also numpy)

_lineWidth with maybe AA_

- https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc

- https://blog.tammearu.eu/posts/gllines/

# Geometry Shader

- http://www.lighthouse3d.com/tutorials/glsl-tutorial/geometry-shader/

- https://www.shadertoy.com/view/ltdyzj (nice shader syntax)

- http://www.geeks3d.com/20111111/simple-introduction-to-geometry-shaders-glsl-opengl-tutorial-part1/

- https://learnopengl.com/Advanced-OpenGL/Geometry-Shader

_extensive shader example. resource_

- https://hal.inria.fr/hal-00907326/file/paper.pdf

_web gl shader with linewidth and miter_

- https://wwwtyro.net/2019/11/18/instanced-lines.html

_WebGL examples to draw lines with shaders_

- https://mattdesl.svbtle.com/drawing-lines-is-hard
- https://github.com/mattdesl/webgl-lines

_WebGL shaders examples_

- https://www.clicktorelease.com/code/THREE.MeshLine/demo/index.html
- https://github.com/spite/THREE.MeshLine
- https://www.clicktorelease.com/code/polygon-shredder/

# Lines..

- https://stackoverflow.com/questions/56501795/drawing-aliased-pixel-perfect-lines-in-fragment-shader

**Comment by Durman** [comment]
Some bug. Not sure where to post this.
https://yadi.sk/i/Bapo-dAkO_0_Fg

**Comment by zeffii** [comment]
hope i can recreate..

**Comment by zeffii** [comment]
i can not seem to recreate that .. @portnov  @DolphinDream  @vicdoval   any luck ?

**Comment by vicdoval** [comment]
![Annotation 2019-10-11 222911](https://user-images.githubusercontent.com/10011941/66682949-97e25780-ec76-11e9-9308-9877af6af1dc.png)
Confirme, as soon as draw gl wireframe is enabled craziness starts :D

**Comment by DolphinDream** [comment]
This looks to me like an opengl push/pop attributes kind of bug.. Not sure what version of opengl B28 uses so maybe push/pop attributes is not even a thing, but it looks like something is accumulated, not properly flushed out (texture left enabled/bound). 

Btw, I wasn’t able to replicate this on my system.

**Comment by zeffii** [comment]
yah. well - i'm going to just disable draw wireframe, it's for debugging purposes anyway.

**Comment by zeffii** [comment]
(also.. be sure to be using the very latest `b28_prelease_master`  , there was one bug fixed a day or so ago.

**Comment by zeffii** [comment]
please discus the bug in a separate issue, and state your Blender build info , and Sverchok branch/hash

**Comment by zeffii** [comment]
```
>>> shader.uniform_
                   block_from_name(
                   bool(
                   float(
                   from_name(
                   int(
                   vector_float(
                   vector_int(
```

**Comment by zeffii** [comment]
this goes beyond my level of comprehension, but it's cool: http://jcgt.org/published/0003/04/01/paper.pdf

**Comment by zeffii** [comment]
there's a feature in openGL that lets you load a mesh, and instance it using matrices - worth implementing for the scenario "one mesh, many matrices".

**Comment by zeffii** [comment]
declaring in node annotations
```python
    commentColor: bpy.props.FloatVectorProperty(
        min=0, max=1, size=4, name="Comment Color", 
        default=(0.3, 0.3, 0.3, 1.0), subtype='COLOR', update=updateNode
    )
```

passing a color as uniform to all fragments

```python
    config.commentColor = self.commentColor[:]
    shader.uniform_float("commentColor", config.commentColor)
```
received as:
**fragment_shader**
```glsl
   ...
   uniform vec4 commentColor;
   void main() {
       ...

```

**Comment by DolphinDream** [comment]
Is the linewidth bigger than 1px (on mac) working already ?

**Comment by zeffii** [comment]
no, it's not high on the todo. but I did start a PR that you could fork, and try to excavate the b3d line shader and transplant it into the fragment shader..  i had started but quickly discontinued efforts.

https://github.com/nortikin/sverchok/pull/2965

**Comment by DolphinDream** [comment]
A very early demo for line width using geometry shaders (line width is not in pixels):

![SV-LineWidth-Demo1](https://user-images.githubusercontent.com/2083719/78295396-14554500-74fa-11ea-86e6-e7535d1d0639.gif)

**Comment by zeffii** [comment]
now ..i've just thought of a way to do it, but i've not had experience with the subparts to the problem to be certain about the solution. it's a logic thing
- first draw edges + (flat) faces to a offscreenbuffer of px viewport dims.
- subtract all pixels that have the same colour as the flat faces
- the result is the occluded edge markings
- perform smoothing/AA on the result
- overlay the result onto the flat faces (or other shaded face rendering
- display the combined results as an overlay on the screen.

i imagine that is much faster in straight C/C++ than python.

**Comment by zeffii** [comment]
looks like github's having a difficult time tonight ..

**Comment by enzyme69** [comment]
VD node color and viewer outline draw in color is a great idea, Zeffii

**Comment by DolphinDream** [comment]
Wouldn’t the offscreen buffer / overlay solution ignore the other 3D objects in the scene? Currently the 3D objects in the scene can occlude geometry rendered by VD node. 

<img width="456" alt="Screen Shot 2020-04-02 at 8 38 03 PM" src="https://user-images.githubusercontent.com/2083719/78312465-e1bf4280-7521-11ea-82d3-1e9969925f1a.png">

**Comment by DolphinDream** [comment]
@zeffii here’s my experimentation branch with the code used to generate the above thick lines demo.

https://github.com/DolphinDream/sverchok/commit/86adce9c3f62809f88de783b4e695ad2fda07275

**Comment by zeffii** [comment]
> Perhaps if you render to an offscreen buffer you’d have to take the current depth buffer (updated by rendering the 3D objects in the scene) into account ?

likely.   it's safe to say that there's only so much we can do with py-openGL. before it becomes "a day job"

**Comment by zeffii** [comment]
> Also the line thickness varies with the orientation in 3D so it’s not quite what I was hoping to get (a constant line thickness irrespective of the 3D orientation and zoom).

it looked like the edge was being thickened in the X,Y axis regardless of Z. or line orientation.

i'm glad to have more eyes looking at this, i'll help out if i can.

**Comment by DolphinDream** [comment]
Any luck int getting the mesh viewer node to draw thick lines in macOS ?
