### ISSUE TITLE
ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)

### ISSUE THREAD

**Issue by forenbuddy** [nortikin/sverchok#2617]
## Problem statement

After installing when I want to switch on the addon Blender 2.8 gives: "ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)"

## Steps to reproduce

1. download sverchok-master.zip from github
2. install addon from file in blender
3. clicking on the little square Node: Sverchok

## Expected result

What did you expect to see as a result of those steps?

enabled addon

## Actual result

What did you actually get?

Stacktrace and
"ImportError: cannot import name 'glBegin' from 'bgl' (unknown location)"

## Sverchok version

downloaded ZIP from twenty minutes ago

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

sverchok-master.zip from github

**Comment by Durman** [comment]
Try this: #2326

**Comment by zeffii** [comment]
sorry @forenbuddy 

i expected Blender 2.8+ to no longer allow non 2.8 add-ons to be enabled. The `bl_dict` indicates that the current master is not for blender 2.8 .. ` "blender": (2, 7, 8),  `

the suggested link by @Durman will however work.

**Comment by portnov** [comment]
I think blender version specified in addon meta-info is the *minimal* blender version, not maximum...
So it's better to add maximum version check somewhere in register()...

**Comment by zeffii** [comment]
i think we'll add code to `master` and `b28_prelease_master` to prevent enabling them in the wrong version of Blender.  no ETA.
