### ISSUE TITLE
Moon satellite challenge (levels of abstraction)

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2633]
Imagine for a moment that you are in 2100 year and working for a little lunar mining company as senior engineer. You have the task to build satellite for miners where they can rest between shifts. According that fact that moon has lousy gravitation what is quite unhealthy for human satellite should have artificial gravity. Something like that will be perfect solution.)))

![moon 1](https://user-images.githubusercontent.com/28003269/67148361-f7141d80-f2af-11e9-830a-d105ebba0abf.gif)
![2019-10-19_20-17-00](https://user-images.githubusercontent.com/28003269/67148366-02ffdf80-f2b0-11e9-9f4c-cecf1bfbe863.png)

After building the little miner colony the company start to grow faster and your new task is to build more several ring modules for the station. Fortunately your tools allows you to develop several objects simultaneously. 

![moon 2](https://user-images.githubusercontent.com/28003269/67148458-e0ba9180-f2b0-11e9-809d-40fc7d38fff8.gif)
![2019-10-19_20-22-20](https://user-images.githubusercontent.com/28003269/67148459-e3b58200-f2b0-11e9-9fce-45403b6a0ede.png)

After that next step is to build several new station nearby the first one because new rings can't be effective anymore. Any suggestions how to do this?)))
file:
[moon chelenge_2019_10_19_17_06.zip](https://github.com/nortikin/sverchok/files/3746988/moon.chelenge_2019_10_19_17_06.zip)

**Comment by zeffii** [comment]
thanks for this :)  i've fixed the load "zipped blend from web" operator:
https://github.com/nortikin/sverchok/pull/2299/commits/15ca47387570bbd0752b865d9f38f9a829293ba5

**Comment by nortikin** [comment]
Case simple

[moon chelenge1.zip](https://github.com/nortikin/sverchok/files/3850507/moon.chelenge1.zip)

**Comment by Durman** [comment]
Sverchok has monads. Probably they can help:

![2020-02-05_16-44-19](https://user-images.githubusercontent.com/28003269/73842851-d956ce00-4836-11ea-876b-1b9e7c9aff69.png)
![2020-02-05_16-47-26](https://user-images.githubusercontent.com/28003269/73843031-381c4780-4837-11ea-85f5-f246db18c6ed.png)

But such approach is also alien for them. On last picture I'm expecting to get 3 station in random points but shifting of modules have get instead.
![2020-02-05_16-52-29](https://user-images.githubusercontent.com/28003269/73843359-f0e28680-4837-11ea-916a-eb3373a1ba7e.png)

**Comment by vicdoval** [comment]
You can encapsulate everything inside a monad:
![image](https://user-images.githubusercontent.com/10011941/73849426-339d6200-482a-11ea-8472-4b25e5e38f57.png)

**Comment by Durman** [comment]
Actually I was searching a way of creating something like mesh inside mesh inside mesh. And I have found that with monads it is quite possible.
