### ISSUE TITLE
Q: Closing an Open PolyLine?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2638]
Is there a node in SV that simply "close an open 2D shape" (just like how Curve can be closed and open) and then fill the inside with polygon face just like "Fill Hole" node?

<img width="989" alt="Screen Shot 2019-10-22 at 11 33 13 am" src="https://user-images.githubusercontent.com/3952687/67252710-e4703300-f4bf-11e9-8993-f55ac12e6bc9.png">

[gp_open_close_curve.blend.zip](https://github.com/nortikin/sverchok/files/3753440/gp_open_close_curve.blend.zip)

I am sure there is an easy way to do this...

**Comment by Durman** [comment]
![2019-10-22_08-42-59](https://user-images.githubusercontent.com/28003269/67259637-fe058080-f4a7-11e9-97b2-fe8d38fdb3d8.png)

**Comment by enzyme69** [comment]
That's the node thanks @Durman The "Planar Edgenet" is a difficult name to remember or guess!~

**Comment by zeffii** [comment]
glad all of this works in b28 

![image](https://user-images.githubusercontent.com/619340/67271588-14690780-f4bb-11e9-9b91-71142daf8d93.png)

**Comment by zeffii** [comment]
but the SN pathlength node will fail until Object ID selector outputs Points.. and that's a little finnicky (seems to miss an update)

**Comment by Durman** [comment]
> That's the node thanks @Durman The "Planar Edgenet" is a difficult name to remember or guess!~

Probably I will remove the node after I will finish with `edges to faces 2D` node.))
