### ISSUE TITLE
Merge Mesh 2D but to auto-merge all meshes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2641]
I really like Merge Mesh 2D node, and the way it works is to have 2 x Mesh A and B and it will merge and find intersection, etc.

Is there an option or a way so that it simply takes N number of mesh and simple merge and intersect without having to have Mesh B? So far I am using Plane as Mesh B as a clipping, which is not a bad idea. 

[merge_mesh_unite_all_001.blend.zip](https://github.com/nortikin/sverchok/files/3771741/merge_mesh_unite_all_001.blend.zip)
<img width="1069" alt="Screen Shot 2019-10-25 at 10 07 39 pm" src="https://user-images.githubusercontent.com/3952687/67566611-009bfa80-f774-11e9-9946-9ea796aab08f.png">

**Comment by Durman** [comment]
I also have came to the similar thought about the node. I'm going to add `merge mesh 2D light` node which is exactly fitted into your description. But I'm going to do this only for 2.8 since I switched to the branch. 
You can have a look at my plans for 2.8: #2623

 Also I would recommend to read the documentation of the node:
https://github.com/nortikin/sverchok/blob/master/docs/nodes/modifier_change/merge_mesh_2d.rst

**Comment by Durman** [comment]
@enzyme69  Now you can try this: https://gist.github.com/4e5c293547f751113c7c4f10d3dee3d8

![2019-11-27_08-33-22](https://user-images.githubusercontent.com/28003269/69693940-979bff80-10f0-11ea-8c31-4d0bceab48c8.png)

**Comment by enzyme69** [comment]
That's a cool node! (Merge Mesh 2D Lite), but does not work if I use Bmesh Viewer, works with Viewer Draw however~

```
ode Viewer BMesh had exception: faces.new(...): found the same (BMVert) used multiple times
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/sverchok-b28_prelease_master-6/core/update_system.py", line 343, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/sverchok-b28_prelease_master-6/nodes/viz/viewer_bmesh.py", line 344, in process
    make_bmesh_geometry(self, obj_index, bpy.context, Verts, *data)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/sverchok-b28_prelease_master-6/nodes/viz/viewer_bmesh.py", line 136, in make_bmesh_geometry
    bm = bmesh_from_pydata(verts, edges, faces, normal_update=node.calc_normals)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.81/scripts/addons/sverchok-b28_prelease_master-6/utils/sv_bmesh_utils.py", line 39, in bmesh_from_pydata
    add_face(tuple(bm.verts[i] for i in face))
ValueError: faces.new(...): found the same (BMVert) used multiple times
```

**Comment by enzyme69** [comment]
Ok wait it actually works but I must have accidentally got a bug ... weird.

Works as below:
<img width="1040" alt="Screen Shot 2019-11-27 at 10 39 49 pm" src="https://user-images.githubusercontent.com/3952687/69720488-d2d91580-1166-11ea-9dc6-9e687ebdbf84.png">

**Comment by enzyme69** [comment]
Yes like this:
<img width="1067" alt="Screen Shot 2019-11-27 at 10 40 50 pm" src="https://user-images.githubusercontent.com/3952687/69720539-f8661f00-1166-11ea-9874-3f30a025030d.png">

[mergeMesh_auto_006.blend.zip](https://github.com/nortikin/sverchok/files/3896679/mergeMesh_auto_006.blend.zip)

**Comment by Durman** [comment]
Be careful with `Bevel` node it can produce self intersection faces. Such faces does not support by `merge mesh` node. 
The error is related with output face. You can see in screenshot that one point is used twice in face creating. `BMViewer` can't views such faces.

![2019-11-27_16-14-06](https://user-images.githubusercontent.com/28003269/69722902-a8209a00-1131-11ea-8a0f-6e19a9002e05.png)

**Comment by portnov** [comment]
@Durman Bevel node now has "Clamp overlap" flag exactly to avoid this kind of problems.
