### ISSUE TITLE
[Feature request] Text curve node?

### ISSUE THREAD

**Issue by myselfhimself** [nortikin/sverchok#2645]
Hello,
when trying the current master branch ( "version": (0, 5, 9, 6),) on blender 2.79, I could not find a node allowing me to create a Text Curve (and possibly then convert it to mesh). 
Is that intended?
Thank you :)

**Comment by zeffii** [comment]
hi @myselfhimself 
use `Objects In` (from Scene menu) - have the Text Object selected, then press pickup.

**Comment by zeffii** [comment]
any further problems, get back to us.
