### ISSUE TITLE
Contour 2D only Inner or Outer Contours

### ISSUE THREAD

**Issue by aurelw** [nortikin/sverchok#2650]
It would be nice to have the **Contour 2D** Node only to generate inner or outer contours. Not both at the same time. This would require a new option. Meaning that for a closed polygon only inner contours.

The node's code is rather complicated and undocumented and I have a hard time figuring out how to do this.

Sverchok version: tagged with 2.79

**Comment by vicdoval** [comment]
Hi @aurelw, the Contour 2D Node works with edges (not with polygons) so there are not insides or outsides.  
It was my first contribution to Sverchok and probably could be better coded and more documented :)  At some point I may try to improve it... 
By now what you can do is using "Separate Loose" node to separate the contours and filter what you want from there
![image](https://user-images.githubusercontent.com/10011941/68072132-6b57c200-fd82-11e9-82ec-b50ffd7fb310.png)

**Comment by Durman** [comment]
I think closed loop of edges can considered as polygon. 

It is possible to determine in such case that contour which lays from left side against leftmost point of edges loop is outer contour and vice versa about innter contour. 

If edges loop is unclosed than only outer contour can be created. So it proves that for closed edges loop inner contour can be determined. =D

![contour](https://user-images.githubusercontent.com/28003269/68075153-65cb9d80-fdbd-11e9-95d3-1191f3b1831f.jpg)
But this fair only for loops without self intersections.

**Comment by aurelw** [comment]
@vicdoval thanks for your answer, I see what you did there. However, it seems like that I can separate both contours in that way, but their order is not deterministic. Meaning I still can't figure out what the inner contour and outer contour is. And this approach only works if I handle a single loop of edges. If I have a different topology, this breaks as well.

![Uploading sverchok_slicer_5.png…]()

@Durman that's exactly what I want to achieve. Closed loops in the edges should be detected as closed polygons. Winding order of the edges encodes inside/outside of polygon.

**Comment by Durman** [comment]
My approach looks in this way.)))

https://gist.github.com/23797a435a744b96f79a81a4656ff945

![2019-11-04_09-25-10](https://user-images.githubusercontent.com/28003269/68101099-61020900-fee5-11e9-9d31-92ae96859b8b.png)

**Comment by vicdoval** [comment]
Separating the loops before passing through the Contour 2D and applying the "list item" technique inside a vectorized Monad (group) 

![image](https://user-images.githubusercontent.com/10011941/68104575-e5e82500-fedb-11e9-9609-6ae2067cf2de.png)

**Comment by Durman** [comment]
This variant based on test whether point is inside face or not.

https://gist.github.com/25489a73e685e096477629992d971c90
![2019-11-04_12-29-17](https://user-images.githubusercontent.com/28003269/68107601-cd3d3680-fefe-11e9-9874-55639e82aff0.png)

**Comment by aurelw** [comment]
Ok, that helped me quite a bit. I had a previously broken solution with a PointInsideMesh, which is now working. However, I think it's quite convoluted to do it like this.

I still think the Offset 2D node would profile from an option to offset only in one direction. You basically offset every edge to the right and to the left. If we can limit the node to just one direction we would essentially be able to only generate inner/outer contours for polygons with a correct winding order. This would make things much more efficient and easier to use.

**Comment by Durman** [comment]
#3803
