### ISSUE TITLE
Documentation for Node UV Connection Outdated

### ISSUE THREAD

**Issue by aurelw** [nortikin/sverchok#2655]
The documentation lacks the "cup U" and "cup V" parameters and also has other inconsistencies to the current version, using 2.79.

**Comment by zeffii** [comment]
sometimes we forget to update documentation, unfortunately it doesn't update automatically when we change node behaviour/ui.

fortunately it is reasonably self explanatory. I welcome you to experiment.

![image](https://user-images.githubusercontent.com/619340/68290653-97c45480-0088-11ea-94d8-5552023480c1.png)


We are working on 2.8 mostly at the moment..
