### ISSUE TITLE
Matrix array node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2656]
The node looks like duplicate `matrix apply` node. What purpose of the node?

![2019-11-07_08-24-01](https://user-images.githubusercontent.com/28003269/68360135-3b207280-0138-11ea-92a9-2cef96229441.png)

**Comment by zeffii** [comment]
i'm not sure anymore i was testing/experimenting something. like a Node version of an Array Modifier.

i'm OK with it being removed in its current state...
