### ISSUE TITLE
Inset special node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2658]
Looks like the node has problem with determining normal direction.

![inset spetial](https://user-images.githubusercontent.com/28003269/68380735-db42bf80-0169-11ea-9961-9d9e5046ab52.gif)

**Comment by zeffii** [comment]
yikes....
https://github.com/nortikin/sverchok/blob/c96a5497dd91166a392c8b4f1362e7f05d34a72b/nodes/CAD/inset_special.py#L129-L134

**Comment by zeffii** [comment]
the initial algorithm expects convex faces, for speed and simplicity. 
alternative algorithms would be appropriate if the input is expected to contain concave faces

i only implemented what I expected to use / feed it.

**Comment by Durman** [comment]
Well, it seems that there are some corner cases when it does not work properly even with convex polygons.

![2019-11-07_15-37-31](https://user-images.githubusercontent.com/28003269/68386030-983a1980-0174-11ea-8377-f4fba735a5d4.png)

**Comment by zeffii** [comment]
@Durman   yes, i think  this  is a failure/feature of my algorithm,  the new edges are attracted by disance N towards the median of all verts in the original polygon.

**Comment by Durman** [comment]
Also there is problem with almost convex polygons.
![2019-11-07_15-57-43](https://user-images.githubusercontent.com/28003269/68387466-d127bd80-0177-11ea-881e-8540674b763d.png)
On the picture below all polygons are almost convex but some of them extrude in one direction and other in opposite one.
![2019-11-07_15-59-24](https://user-images.githubusercontent.com/28003269/68387532-f7e5f400-0177-11ea-998f-2bd484f4220f.png)

**Comment by zeffii** [comment]
@Durman   maybe you can look at the recent changes to this node, 

-- whatever the case, the direction of the new node should not be arbitrary (i agree) , especially not in 'accurate mode.

**Comment by zeffii** [comment]
we see here the 'accurate' method (supplied by @portnov also makes assumptions about the shape of the ngon.
```
def calc_normal(vertices):
    """
    Calculate normal for a face defined by specified vertices.
    For tris or quads, mathutils.geometry.normal() is used.
    Ngon will be triangulated, and then the average normal of
    all resulting tris will be returned.

    input: list of 3-tuples or list of mathutils.Vector.
    output: mathutils.Vector.
    """
    n = len(vertices)
    vertices = list(map(mathutils.Vector, vertices))
    if n <= 4:
        return mathutils.geometry.normal(*vertices)
    else:
        # Triangluate
        triangle_idxs = [[0, k, k+1] for k in range(1, n-1)]
        triangles = [[vertices[i] for i in idxs] for idxs in triangle_idxs]
        subnormals = [mathutils.geometry.normal(*triangle) for triangle in triangles]
        return mathutils.Vector(center(subnormals))
``
so.. we must have '" Fast / Accurate / Robust " mode

**Comment by zeffii** [comment]
where Robust uses `mathutils.geometry.normal(*vertices)`

**Comment by zeffii** [comment]
because...the area made by `(0, 1, 2)`  ... or  `vertices[:3]`
```
2
| \
|  \
|   \
1    \
|     \
|      \
|       \
0--------3

```
is going to return something you don't expect..  only because of numerical innacuracies does it return anything at all.. there's no `normal` if there's no `area`.

**Comment by zeffii** [comment]
@portnov  some triage may be needed

https://github.com/nortikin/sverchok/pull/2545

i feel that the "faster" mode can probably drop the `new_verts_prime[:3]` list slice, and just pass the whole `*new_verts_prime` , complexity is dealth with in that mathutils function

**Comment by zeffii** [comment]
the algorithm to inset the face currently expects regular / convex geometry, and will produce "relative" insets, the inset amount will not be a constant scalar amount between the old edges and the new inset edges. Offering absolute distance per inset might be nice, and appropriate..  but important to have a quick and dirty method..

**Comment by portnov** [comment]
Uh. In 2.7x, mathutils function could work with tris and quads only: https://docs.blender.org/api/blender_python_api_2_71_release/mathutils.geometry.html#mathutils.geometry.normal - that's why before the addition of "precise" mode the node always did `[:3]`.
But it seems that in 2.80 it can work with any number of vectors: https://docs.blender.org/api/current/mathutils.geometry.html#mathutils.geometry.normal
So, I think there is no need in two modes anymore — it is possible to just call mathutils function always. Any objections?

**Comment by zeffii** [comment]
nope. mathutils all the way gets my vote

**Comment by zeffii** [comment]
i'll push that.. and hopefully avoid breaking blends. (will retain some dud properties.. with comments about why ..)

**Comment by zeffii** [comment]
something for tomorrow, `new_inner_from`  has two normal calculations, which if both are calculated should be returning the same value. and that feels daft.

**Comment by zeffii** [comment]
maybe..
```python
        if abs(inset_by) < 1e-6 or distance:
            local_normal = mathutils.geometry.normal(*verts)

        if abs(inset_by) < 1e-6:
            new_vertex = avg_vec.lerp(avg_vec + local_normal, distance)
            vertices.append(new_vertex)
            new_vertex_idx = current_verts_idx
            new_faces
            for i, j in zip(face, face[1:]):
                new_faces.append([i, j, new_vertex_idx])
            new_faces.append([face[-1], face[0], new_vertex_idx])
            return

        # lerp and add to vertices immediately
        new_verts_prime = [avg_vec.lerp(v, inset_by) for v in verts]

        if distance:
            new_verts_prime = [v.lerp(v+local_normal, distance) for v in new_verts_prime]
```

**Comment by Durman** [comment]
One more:
![2019-12-09_16-54-46](https://user-images.githubusercontent.com/28003269/70437319-c9c04080-1aa4-11ea-8890-e5b65ac4a3e7.png)

**Comment by zeffii** [comment]
what kind of input @durman

**Comment by zeffii** [comment]
huh? : )

**Comment by zeffii** [comment]
oh.. i see
```python
        if make_inner:
            
            add_face([idx[-1] for idx in out_faces])
            new_insets.append([idx[-1] for idx in out_faces])
```
when add_face is called, "out_faces" becomes one item longer. which means the `idx` range in the next line is also one longer.

**Comment by zeffii** [comment]
resolved by https://github.com/nortikin/sverchok/pull/2726
