### ISSUE TITLE
Update event during creating new sockets

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2660]
I have faced with the problem in `merge mesh` node when creating new sockets cause update of the node. I did not dig deep into reasons of such behavior. I think temporary solution can look like this: 

```Python
    def update_sockets(node, context):
        node.id_data.freeze()

        add_new_sokets(node)

        node.id_data.unfreeze()
        node.id_data.process()
```

Downside of this approach is that adding new sockets cause update all node tree what definitely is overkill.
In my case it should be okay because I expect adding new sockets only when node was first created and unlikly ever again.

#2370

**Comment by zeffii** [comment]
yes, pynode API doesn't provide its own set of event handlers. so we must "skip" updating the node tree whenever possible or appropriate.

I propse a wrapper, as part of `node` Common mixin class.. something that handles the freezing automatically.  I've been thinking about this for a while.

```python
class NodeCommon...

    def new_socket(self, direction, socket_type, socket_name, properties=None):
        """
        usage:

        def sv_init(self):
            self.new_socket('in', 'SvStringsSocket', 'distance', properties={'prop_name': 'distance'}) 

        """
        sockets = self.inputs if direction == 'in' else self.outputs
        node = self.node
        tree = node.id_data
        tree.freeze()
        sock = sockets.new(socket_type, socket_name)
        tree.unfreeze()
        if properties:
            for k, v in properties.items():
                setattr(sock, k, v)

```

**Comment by zeffii** [comment]
maybe with a try/except in there to force the tree to be unfrozen before leaving the `new_socket` function.

**Comment by zeffii** [comment]
but just to be clear.. i added a general nodetree freeze feature some time ago, that is triggered before 
 `sv_init` is called, and unfrozen after  `sv_init` is complete, so these kinds of wrappers are useful only for when we update a node's socket-set after `sv_init`

**Comment by Durman** [comment]
Unfortunately the freeze function makes somehow the socket data clear. It would be nice if particularly in our case socket data have been remained so there would not be need in updating everything after adding new socket.
https://github.com/nortikin/sverchok/blob/12e1b094f29210371f2b5fc728db81b57e69aa49/core/socket_data.py#L28-L29

**Comment by zeffii** [comment]
i will look into that.

if we can bypass cache destruction, it will be optional. there are scenarios (As you might expect) where we do not want the cache to be kept, where new socket means also different algorithm, and different expected output.

**Comment by zeffii** [comment]
i don't see anywhere that `socket_data_cache` is cleared -- this only happens in the event that the nodetree is told to do a complete update ( a la : `node.id_data.process()`  ) 

you can call the following in a update wrapper  :
```
updateNode(self, context)
# or directly
self.process_node(context)   # <---  is called up updateNode anyway..
# or ...maybe don't do this..
process_from_node(self)    #  requires:   sverchok.core.update_system.process_from_node
```
there's a call to 'reset_socket_cache` from `def build_update_list(ng=None):` all of those options will eventually end up at that point.

**Comment by zeffii** [comment]
also.. it's better for most nodes to completely avoid implementing `def update()` , there are almost always alternatives (with the exception of nodes that draw with bgl )

**Comment by Durman** [comment]
I expect that such scenario is happening:
- New socket is adding via python apy
- This is causing blender update event on node editor changes according [this](https://docs.blender.org/api/2.80/bpy.types.NodeTree.html#bpy.types.NodeTree.update) 
- Sverchok upon this event switch node_tree.has_changed to True
https://github.com/nortikin/sverchok/blob/36d70cd221f76071b3f81fb8bc3e88cb9d2e725a/node_tree.py#L178-L186
- Then, the process method is calling.
https://github.com/nortikin/sverchok/blob/36d70cd221f76071b3f81fb8bc3e88cb9d2e725a/node_tree.py#L196-L209
- then, the build update list, where there is reset_socket_catch function
https://github.com/nortikin/sverchok/blob/36d70cd221f76071b3f81fb8bc3e88cb9d2e725a/core/update_system.py#L367-L373

**Comment by zeffii** [comment]
OK, yes. it's worth experimenting with adding another property to the node tree. 

```
adding_socket: BoolProperty()
```

- setting it to True before adding a socket, 
- then in `tree.update()`  test for the state of that variable
     - if True,   then set to False and return
     - if False,  proceed to do current behaviour.

This would be easiest in a wrapper, so we always have this behaviour in a consistent way.

**Comment by zeffii** [comment]
also.. i'm not sure the `has_link_count_changed`  feature is useful anymore.

**Comment by Durman** [comment]
What about using context manager like this:
```Python
with adding_sokets():
    [node.inputs.new('SvVerticesSocket', f'Verts {i}') for i in range(10))]
```
This approach probably can be faster if more than one socket is going to be added. And it allows to use familiar interface of adding sockets instad of using custom function.

**Comment by Durman** [comment]
Or probably decorator can be used even.
```Python
@adding_sockets
def update_sockets(node, context):
    [node.inputs.new('SvVerticesSocket', f'Verts {i}') for i in range(10))]
```

**Comment by zeffii** [comment]
yeah, either of those would be OK, but i think `context_manager` route offers the most flexibility, if the function wants to do more than just add sockets.

**Comment by zeffii** [comment]
and maybe call is  `with throttled_update():`  instead of `adding_sockets`

**Comment by zeffii** [comment]
i've added a context manager for `throttle_tree_update` , see the most recent commit. perhaps merge b28_prelease_master into your working branch, and test it.

**Comment by Durman** [comment]
#2661

**Comment by Durman** [comment]
I have tested this. It works as expected.)

**Comment by Durman** [comment]
According this #2770 creating of new sockets does not trigger any `node tree` update events but creating/removing links does. Also it triggers node update event so probably we should throttle them as well. 

Probably it worth to create `sv_update`method which will be called unless a tree is not throttled.

**Comment by zeffii** [comment]
i hope we can fix this, because it is a very stupid problem :)
