### ISSUE TITLE
`Viewer text mk3` node bug

### ISSUE THREAD

**Issue by KassadinL** [nortikin/sverchok#2662]
## Problem statement

`Viewer text mk3` node bug, crash Blender

## Steps to reproduce

1. create a mesh with Sverchok
2. `Viewer text mk3` have at least one data in, and check on `autoupdate`
3. delete the mesh
4. Blender crash

## Expected result

delete the mesh object

## Actual result

crash

## Sverchok version

version 0.6.0.0,  download from GitHub page 2.8+ zip at 10/25, update in Blender today(11/09)
Blender v2.82.1 daily build(11/08)

***
a example
![06bug](https://user-images.githubusercontent.com/19602109/68522434-313c7200-02e6-11ea-9104-7ed3f332024f.png)

**Comment by Durman** [comment]
Confirm:
```
Info: Deleted 1 object(s)

Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x000000013FE873D0
Module  : C:\Program Files\Blender Foundation\Blender\blender.exe
```

**Comment by portnov** [comment]
Well, what if you take another blender version?
We have to determine whether this is Blender or Sverchok's bug.

**Comment by KassadinL** [comment]
> 
> 
> Well, what if you take another blender version?
> We have to determine whether this is Blender or Sverchok's bug.

Blender 2.80 and 2.81 have the same problem, just tried it.

**Comment by zeffii** [comment]
wasn't there a bug after deleting   any   bmeshviewer generated object ?   i'd be suprised if this anything to do with viewertext

**Comment by zeffii** [comment]
hmmmmmmmmmmm

**Comment by zeffii** [comment]
woooaaah.  

that's crazy .

**Comment by zeffii** [comment]
the same also happens without the BMeshviewer.. 
- add a Plane (from 3dView, Add Mesh ...)
- add a generator + attache to Viewer Text
- remove the Plane
boom.

**Comment by Durman** [comment]
Probably this can be related: #2488

**Comment by zeffii** [comment]
does anyone know how to get Blender's last "event" info ?

like.. i'd be happy to skip update/processing tree if the last event was "Info: Deleted %n object(s)"

out depsgraph event handler should not have to figure out everything for every event..

**Comment by KassadinL** [comment]
> 
> 
> Probably this can be related: #2488

Seems to be this problem

**Comment by zeffii** [comment]
digging through the source of `Viewer Text` 

unrelated: the update function in this node only ever performs this..
```
    def update(self):
        multi_socket(self, min=1)
```
there is no `data` socket, only `data0` (or 1,2,3,4,5...etc)

**Comment by zeffii** [comment]
it seems like the issue is really that process calls 'bpy.ops.node....`

**Comment by zeffii** [comment]
i'll replace that ops call..

**Comment by zeffii** [comment]
OK, it is the operator call, which I think we can bypass..

**Comment by zeffii** [comment]
thanks for the report @KassadinL   and sorry for the  crazy unexpected crash :)

**Comment by KassadinL** [comment]
> 
> 
> thanks for the report @KassadinL and sorry for the crazy unexpected crash :)

thanks for your amazing work, so efficient 👍

**Comment by zeffii** [comment]
if you make anything cool with sverchok, please show us :)

**Comment by KassadinL** [comment]
> 
> 
> if you make anything cool with sverchok, please show us :)

oh, yes :P  (when after more learning
