### ISSUE TITLE
Render gallery 2019 #2

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2666]
Previous gallery ticket - #2357.

![adaptive_icosphere_14](https://user-images.githubusercontent.com/284644/68532565-86a56d00-0340-11ea-9ffc-1ae2752dffae.png)

**Comment by portnov** [comment]
![adaptive_icosphere_7](https://user-images.githubusercontent.com/284644/68532571-ae94d080-0340-11ea-9bb1-e5db8c182be2.png)

**Comment by Tortenrandband** [comment]
small contribution, experimenting with the gcode exporter and contour nodes.
![2a3179d5-fb17-43f9-a6ab-ffd7a7532e12](https://user-images.githubusercontent.com/52531782/68596462-8ec5ef80-049b-11ea-901f-515f43fb5977.jpg)

**Comment by portnov** [comment]
![icosphere-spirals-3](https://user-images.githubusercontent.com/284644/68701903-9378c980-05a9-11ea-88bf-4df237c78233.png)

**Comment by enzyme69** [comment]
Procedural Spider Mechanism based on really old setup by Nikitron. Can be improved.

<img width="1078" alt="Screen Shot 2019-11-13 at 10 39 15 am" src="https://user-images.githubusercontent.com/3952687/68719983-e4b4a780-0601-11ea-8fcf-963503932171.png">

**Comment by portnov** [comment]
![adaptive_icosphere_18](https://user-images.githubusercontent.com/284644/69653396-f16edc00-1094-11ea-9f8a-dddd6e4c30a0.png)
![adaptive-torus-engage-1](https://user-images.githubusercontent.com/284644/69653397-f2077280-1094-11ea-895d-4ad2ff5424e8.png)

**Comment by portnov** [comment]
![adaptive_icosphere_29](https://user-images.githubusercontent.com/284644/70266162-c9325c00-17bd-11ea-8b7f-cf04d5cc62f5.png)

**Comment by vicdoval** [comment]
This was my proposal for the contest architectures for freedom on Sziget 2017.
Was mainly created in Sverchok (also some openSCAD and FreeCad to create de documentation)

![carpaOctaedro2](https://user-images.githubusercontent.com/10011941/70378679-9013fc00-1923-11ea-8697-bb64694e02a7.png)
![Octa_Axo25_AFutura](https://user-images.githubusercontent.com/10011941/70378693-b33eab80-1923-11ea-9861-3e395cfa696f.png)
![Octa_Inside3](https://user-images.githubusercontent.com/10011941/70378706-ccdff300-1923-11ea-8243-3693cf10dcb2.png)

**Comment by portnov** [comment]
![adaptive_icosphere_31](https://user-images.githubusercontent.com/284644/70649506-1c4d5880-1c6f-11ea-9d89-988ceae59777.png)

**Comment by portnov** [comment]
Donuts anyone?... :)

![donuts_1](https://user-images.githubusercontent.com/284644/71528467-bf55d180-2901-11ea-9b31-932b8e9c46f0.png)

**Comment by enzyme69** [comment]
I did try with the Donuts thing:
https://github.com/enzyme69/blendersushi/issues/81

But your one seems tasty :D

**Comment by portnov** [comment]
Continued in #2814.
