### ISSUE TITLE
Switch node?...

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2671]
Currently we have two types of "switch" node ("Switch" and "Input Switch MOD"). But neither of them does what I want... :/

What I want is: given a mask (i.e. a list like [0, 1, 1, 0 ...]) and two items as two inputs (for example, two numbers, or two objects...), generate a list of `[objects[0], objects[1], objects[1], objects[0] ...]`.

I'm not able to do it with existing nodes. I was able to do it with a scripted node:

```
"""
in   mask_in s
in   true_in  s
in   false_in s
out  data_out   s
"""

from sverchok.data_structure import match_long_repeat

items = match_long_repeat([mask_in, true_in, false_in])

data_out = []
for masks, trues, falses in zip(*items):
    output_item = []
    for mask in masks:
        if mask:
            output_item.append(trues)
        else:
            output_item.append(falses)
    data_out.extend(output_item)
```

![Screenshot_20191113_210447](https://user-images.githubusercontent.com/284644/68781214-43594000-0659-11ea-9807-daa6dede41a8.png)

Am I overlooking something? Can I do the same with existing nodes, or do we need a new one?

**Comment by vicdoval** [comment]
With the "list item" node you can do that. (Just need to join them first).
Also i think it was possible think with the switch node in multi mode

**Comment by Durman** [comment]
Yes it is possible but as you see the `switch` node is not perfect. I have been improving the node for 2.79 before. #2217
I would like to do the same for 2.8 but not exactly in the same way as for the 2.79.

![2019-11-13_21-25-56](https://user-images.githubusercontent.com/28003269/68789098-2d01b300-065e-11ea-8f0f-ff88eafa1790.png)

**Comment by portnov** [comment]
So I'm looking forward for your updates @Durman  :)
Will use your solution with "list split" for the time being.

**Comment by DolphinDream** [comment]
@portnov the Input Switch node for 2.79 does actually support your desired behavior. The MOD version for 2.80 did not port all the features of its 2.79 counterpart.

<img width="1063" alt="SV-InputSwitchReplication" src="https://user-images.githubusercontent.com/2083719/69387338-889df300-0c93-11ea-945a-8f361391b362.png">

**Comment by enzyme69** [comment]
I am facing similar situation right now and yes the 2.80 version of Input Swith MOD is broken....

So I have to do it like this but it gets pretty messy quickly.

[plane_subdiv_002.blend.zip](https://github.com/nortikin/sverchok/files/3964853/plane_subdiv_002.blend.zip)
<img width="1144" alt="Screen Shot 2019-12-15 at 10 40 15 pm" src="https://user-images.githubusercontent.com/3952687/70862106-e91b0a00-1f8b-11ea-84ce-c30075702129.png">

**Comment by enzyme69** [comment]
<img width="1209" alt="Screen Shot 2019-12-15 at 10 46 55 pm" src="https://user-images.githubusercontent.com/3952687/70862163-cccb9d00-1f8c-11ea-850a-3efaf003d3ee.png">

Ok I think I remember this kind of logic setup before ...

**Comment by nortikin** [comment]
https://gist.github.com/c4378c950af934bcf5b36fa01708ded7
Hi
I cannot make it works anyway

> @portnov the Input Switch node for 2.79 does actually support your desired behavior. The MOD version for 2.80 did not port all the features of its 2.79 counterpart.
> 
> <img alt="SV-InputSwitchReplication" width="1063" src="https://user-images.githubusercontent.com/2083719/69387338-889df300-0c93-11ea-945a-8f361391b362.png">

![Снимок экрана от 2020-04-26 01-24-26](https://user-images.githubusercontent.com/5783432/80292145-aef11e80-875c-11ea-9a26-629f628738eb.png)

**Comment by vicdoval** [comment]
I run on the same problem some days ago, I ended using this `List Join + List Item`
![image](https://user-images.githubusercontent.com/10011941/80292972-5ec58c80-875b-11ea-8d9f-539ec7678611.png)
