### ISSUE TITLE
Sverchok for Blender 2.8x Release Notes

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2676]
I've started a wiki page about the upcoming release — https://github.com/nortikin/sverchok/wiki/Sverchok-for-Blender-2.8x-Release-Notes .

@zeffii @DolphinDream @Durman  @vicdoval @nortikin feel free to add / fix if I've missed something.

**Comment by zeffii** [comment]
cool. time to write docs for "ViewerDrawMK4"

**Comment by Durman** [comment]
I have added nodes from `geom_2d` PR :)
