### ISSUE TITLE
Port "Custom switcher" to 2.8x

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2678]
#2459 is to be ported to b28_prelease_master.
Or not, if you do not consider this node useful anymore :)

**Comment by Durman** [comment]
No, i like this node but before reimplementing the node 3d panel should be redone. 

I see that T panel is not appropriate place for sverchok 3D viewport anymore. It looks like the N panel and Properties viewport are more appropriate.
![2019-11-19_12-51-37](https://user-images.githubusercontent.com/28003269/69131208-648fb580-0acb-11ea-9372-5f565412bbec.png)

Also I think it is worth to reimplement view of properties. All views of properties should be implemented inside those node which properties they represent. Like this:

```Python 
class SvSomeNode():

    node_prop: bpy.props.IntegerProperty(name='Some property')
    show_in_3d_panel: bpy.props.BoolProperty(description='whether to show the property in 3d panel')

    def draw_buttons_3dpanel(self, layout):
        layout.prop(self, 'node_prop')
```

When properties for 3D panel are searched it looks up method `draw_buttons_3dpanel` and property `show_in_3d_panel` if both are True then properties of a node are added to 3d panel.

**Comment by Durman** [comment]
ported: #2713
