### ISSUE TITLE
fixing Cache misses (SvNoDataError)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2681]
I'm not touching any more code until we've resolved this. It's probably something I broke early on, but haven't been annoyed by enough to sit down an localize the issue.

any help appreciated @portnov .. or indeed anyone.

**Comment by zeffii** [comment]
one reproducible scenario is this:

![image](https://user-images.githubusercontent.com/619340/69014354-b92b1780-0989-11ea-85a7-c67d0709ac31.png)

if you tick "merge", then for instance change the Height value in Cylinder, the BMeshViewer will throw an error
```
2019-11-17 22:28:53,206 [ERROR] sverchok.core.update_system: Node Viewer BMesh had exception: No data passed into socket 'vertices'
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 341, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\viz\viewer_bmesh.py", line 307, in process
    mverts, *mrest = self.get_geometry_from_sockets()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\viz\viewer_bmesh.py", line 285, in get_geometry_from_sockets
    mverts = get('vertices')
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\viz\viewer_bmesh.py", line 283, in get
    return self.inputs[socket_name].sv_get(default=[])
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\sockets.py", line 371, in sv_get
    source_data = SvGetSocket(self, deepcopy = True if self.needs_data_conversion() else deepcopy)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\socket_data.py", line 107, in SvGetSocket
    raise SvNoDataError(socket)
sverchok.core.socket_data.SvNoDataError: No data passed into socket 'vertices'
```

**Comment by zeffii** [comment]
but, the nodetree will kick back into cache-hit when you adjust the Size in the Box node

**Comment by zeffii** [comment]
I rarely encounter the error when using `vdmk3`, so perhaps i'll revisit the bmeshviewer node code ..

**Comment by zeffii** [comment]
it must be possible to avoid the state, where the current nodetree / socket id can be wiped..
```
def SvGetSocket(socket, deepcopy=True):
    """gets socket data from socket,
    if deep copy is True a deep copy is make_dep_dict,
    to increase performance if the node doesn't mutate input
    set to False and increase performance substanstilly
    """
    global socket_data_cache
    if socket.is_linked:
        other = socket.other
        s_id = other.socket_id
        s_ng = other.id_data.name
        if s_ng not in socket_data_cache:
            raise LookupError
        if s_id in socket_data_cache[s_ng]:  # <------------------
            out = socket_data_cache[s_ng][s_id]    
            if deepcopy:
                return sv_deep_copy(out)
            else:
                return out
        else:
            if data_structure.DEBUG_MODE:
                debug(f"cache miss: {socket.node.name} -> {socket.name} from: {other.node.name} -> {other.name}")
            raise SvNoDataError(socket)
    # not linked
    raise SvNoDataError(socket)
```
if in a previous update event the `socket_data_cache` was flattened.

**Comment by zeffii** [comment]
the question I ask myself here is:

>  how does the update mechanism arrive at the state where the `updateNode` results in the socket cache being completely wiped.

because there is a simple-ish way to reproduce the problem with very few nodes, there is hope.. and this worked in 2.79 for a long time without issues. What i changed (the handlers that needed to be implemented) is not so directly related to any of the code involved in this undesired reset. in `reset_socket_cache`

https://github.com/nortikin/sverchok/blob/10c28352797f8aab0dbcb381a40ef8fcfc60ac17/core/update_system.py#L389

**Comment by portnov** [comment]
Are we able to find a git revision, where sverchok already does work (somehow) in 2.8x, but does not have this problem?

**Comment by zeffii** [comment]
. this is a problem i've noticed from very early on.

i think the problem may exist in 2.79 but is masked by a few extraneous tree updates. ( that statement will be interesting to prove)

**Comment by zeffii** [comment]
i wonder if an updateNode replacement is in order, which just calls "process_from_node(node)`, instead.

**Comment by zeffii** [comment]
if `process_from_node(node)` includes calling process on `node` too, not just downstream

**Comment by portnov** [comment]
It seems 12049d084df8023e310d312b00498ea9fe90c842 is a good revision... Starting git bisect :)

**Comment by portnov** [comment]
@zeffii it seems that 56e18d64891dfe095028e9946f886e8c0c886465 is the first "bad" revision: I can't reproduce the described problem in any previous revision. 
There were another problem
```
2019-11-19 23:04:41,150 [ERROR] sverchok.core.update_system: Node Viewer BMesh had exception: Error: Object 'Alpha.0014' not in collection 'Master Collection'
Traceback (most recent call last):
  File "/home/portnov/.config/blender/2.81/scripts/addons_contrib/sverchok/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/home/portnov/.config/blender/2.81/scripts/addons_contrib/sverchok/nodes/viz/viewer_bmesh.py", line 283, in process
    self.remove_non_updated_objects(last_index)
  File "/home/portnov/.config/blender/2.81/scripts/addons_contrib/sverchok/utils/sv_obj_helper.py", line 312, in remove_non_updated_objects
    collection.objects.unlink(obj)
RuntimeError: Error: Object 'Alpha.0014' not in collection 'Master Collection'
```

**Comment by zeffii** [comment]
it's possible... but i will dig around and see if I can get that error using something other than bmeshviewer.

**Comment by portnov** [comment]
I suspect that the problem is near the "freeze/unfreeze" logic: it is possible, that in freezed state the "cache" is not updated properly.

**Comment by zeffii** [comment]
that occurred to me too. but the error is thrown prior to that section, when geometry is obtained.

wouldn't hurt to use the context manager (update throttle) there anyway.

**Comment by zeffii** [comment]
well well well :)  it appears to help @portnov   https://github.com/nortikin/sverchok/pull/2685

**Comment by zeffii** [comment]
i hesitate to keep the "extra_message" part of SvNoDataError , but i do want extra ability to distinguish the origin of that error. currently it is not helpful

**Comment by zeffii** [comment]
committed .  thanks @portnov 

will reopen if I can again trigger that error consistently

**Comment by zeffii** [comment]
very nice indeed @portnov

**Comment by portnov** [comment]
@zeffii `git bisect` is our friend :)

**Comment by zeffii** [comment]
the freeze became suddenly necessary with a change in depsgraph, around that time. 

maybe the freeze mechanism deserves closer scrutiny, we use it `between(sporadically, pervasively)`

**Comment by portnov** [comment]
What is the difference between freeze/unfreeze and throttle_tree_update?

**Comment by zeffii** [comment]
hahah.. FYI 

you said @portnov
>  I suspect that the problem is near the "freeze/unfreeze" logic: it is possible, that in freezed state the "cache" is not updated properly.

i had to run that code mentally in my mind a few times, then suddenly i said out loud. YES!

**Comment by portnov** [comment]
:)
