### ISSUE TITLE
Hilbert as Adaptive Polygon is looking skewed and weird...

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2683]
<img width="1059" alt="Screen Shot 2019-11-19 at 11 04 25 am" src="https://user-images.githubusercontent.com/3952687/69104495-7b7adb80-0abc-11ea-8ada-3a21b1817c82.png">
[adaptive_polygon_weird.blend.zip](https://github.com/nortikin/sverchok/files/3861262/adaptive_polygon_weird.blend.zip)

It might be a bug. Somewhat Hilbert 2D result is rotated on a flat plane.

I am using Blender 2.81 Beta and SV 2.0.

The error is showing in my latest video:
https://youtu.be/G46wFFgG95o

**Comment by enzyme69** [comment]
<img width="567" alt="Screen Shot 2019-11-19 at 11 17 09 am" src="https://user-images.githubusercontent.com/3952687/69104984-293aba00-0abe-11ea-9ba6-6766ceeea14a.png">
<img width="646" alt="Screen Shot 2019-11-19 at 11 17 05 am" src="https://user-images.githubusercontent.com/3952687/69104985-293aba00-0abe-11ea-8541-258861ab9c27.png">
<img width="640" alt="Screen Shot 2019-11-19 at 11 17 00 am" src="https://user-images.githubusercontent.com/3952687/69104987-29d35080-0abe-11ea-8070-c436bff151b8.png">

How odd.... it's the offline line causing weird angle adaptive polygon.

**Comment by Durman** [comment]
I don't see any troubles:
![2019-11-19_08-15-24](https://user-images.githubusercontent.com/28003269/69116193-db658800-0aa4-11ea-8f03-d17a8a7b82c3.png)

**Comment by portnov** [comment]
Well, it seems on the first screenshot you are rotating the Hilbert curve with "vector drop" node...

**Comment by enzyme69** [comment]
Ok I guess it's not really an issue, but I did a bit amount offset or something, just a note for future users. Using Apply Matrix and Vector Drop I supposed to flatten the Component.

**Comment by enzyme69** [comment]
As long I didn't use too much offset on the offset line node, it works.

<img width="1053" alt="Screen Shot 2019-11-19 at 3 46 41 pm" src="https://user-images.githubusercontent.com/3952687/69117449-c9efa080-0ae3-11ea-831e-3e507be80e40.png">

[adaptive_polygon_weird5.blend.zip](https://github.com/nortikin/sverchok/files/3861938/adaptive_polygon_weird5.blend.zip)
