### ISSUE TITLE
No Custom Group Interface for Monad IO in 2.8x

### ISSUE THREAD

**Issue by TimothyDespair** [nortikin/sverchok#2684]
## Problem statement

Using sverchok blender pre-release for 2.8x. When making a monad everything works as expected except there is no way to name inputs/outputs, this also leads to any two unnamed outputs of the same type getting their values tied together. 

Issue is present in 2.8 stable and 2.81 beta. I don't think it makes a difference but just in case I'm running on MacOS Catalina.

The release notes [here](https://github.com/nortikin/sverchok/wiki/Sverchok-for-Blender-2.8x-Release-Notes) say something changed with blender panel API, not sure if it's relevant here, but this feature might have moved and I just haven't found its new location yet.

## Steps to reproduce

1. Make a monad.
2. Open Sverchock tab to name IO Sockets
3. Nothing in "Sv Custom Group Interface Panel"

## Expected result

IO Naming to be in Sv Custom Group Interface Panel

## Actual result

Sv Custom Group Interface is empty:
<img width="280" alt="Screen Shot 2019-11-19 at 2 00 50 pm" src="https://user-images.githubusercontent.com/1546076/69113251-9bb79400-0ad6-11ea-877d-6dfaa8835cd8.png">

## Sverchok version

sverchok-b28_prerelease_master.zip from here.

**Comment by zeffii** [comment]
the current release notes omit certain details, especially Monad node and associated mechanisms are not tested extensively (yet). 

i will resurrect the monad UI now.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/69131015-de1aaa00-0ab1-11ea-9f2d-d451e3b4a8f0.png)

**Comment by zeffii** [comment]
there might still be some unresolved issues, but Monad is close to the state it was in in 2.79 when we departed from there.

**Comment by TimothyDespair** [comment]
Ah! Easy fix.

Also found  line 72 should be or the panel disappears when it's wider than the threshold:
`            split = row.split(factor=0.5)`

Can submit a PR if you'd like, but seemed a bit much for a single line.

**Comment by zeffii** [comment]
yes, please. good catch.

**Comment by zeffii** [comment]
the width threshold is something i'd like to link to screen resolution too..(as noted in the code)

**Comment by TimothyDespair** [comment]
I'll give it a look in the next couple days!

**Comment by zeffii** [comment]
in the meantime i will fix the `factor` kw.
