### ISSUE TITLE
Node Tree IO from gist error - weird Internet connection issue?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2695]
Earlier today, Durman gave example node tree that's hosted at .gist I remember using this a lot in the past, but only today I tried again and keeps on failing. Internet direct link download of node tree is not possible and not sure how to load it from my HDD:

Example link like this:
https://gist.github.com/Durman/51d9e1f7dab90d7c898256c504c73726

<img width="587" alt="Screen Shot 2019-11-27 at 10 09 16 am" src="https://user-images.githubusercontent.com/3952687/69680183-409d2700-10fe-11ea-9f1c-974a5f0bd5b4.png">

It's been a while that we have this issue I don't think many people use this handy method of exporting and importing SV node tree.

**Comment by enzyme69** [comment]
Weird, it works after I updated to latest b280 pre release..

<img width="1059" alt="Screen Shot 2019-11-27 at 10 32 39 am" src="https://user-images.githubusercontent.com/3952687/69681139-3df00100-1101-11ea-9155-9ddae68b44d3.png">

**Comment by enzyme69** [comment]
@Durman it's using the depreciated node, strange~

**Comment by Durman** [comment]
Because when I have been creating this layout those nodes was not deprecated yet.))

And you can have a look how to export gists in Sverchok 2.8+:
https://github.com/nortikin/sverchok/wiki/Set-up-GitHub-account-for-exporting-node-trees-from-Sverchok
