### ISSUE TITLE
SVerchok handling multiple Scenes and Collections?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2702]
BTW, found out that if we have multiple Blender Scene, SV can get confused and only generate on Scene (main) and took me a while to figure out on why SV did not produce anything... apparently I was in Scene 2.

SV also known not to use Collections. But maybe this will be added in the future?

**Comment by zeffii** [comment]
well, the viewers (both object, and bgl/shader viewers) are not yet "made aware" of scenes. i felt it more useful to get it working in the current scene first... then expand to use more features of Blender.

**Comment by zeffii** [comment]
adding Collections support to the viewers, should be relatively easy - but i haven't gotten around to it... it is high on my Todo.
