### ISSUE TITLE
list join node - socket interactions dont always update node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2705]
The node does not update properly if first input socket is reconnected. 

![оjoin bug](https://user-images.githubusercontent.com/28003269/69917050-9b76ab80-147b-11ea-9b5e-9a4ad34132dd.gif)

**Comment by zeffii** [comment]
its logic in update seems a little weak
```python
    def update(self):
        # inputs
        multi_socket(self, min=1)

        if 'data' in self.inputs and len(self.inputs['data'].links) > 0:
            inputsocketname = 'data'
            outputsocketname = ['data']
            changable_sockets(self, inputsocketname, outputsocketname)

```

**Comment by zeffii** [comment]
it should maybe resemble this a bit..
https://github.com/nortikin/sverchok/blob/4e4c74d7cb3daa91705039ce5bd800d7f898c5f1/nodes/text/viewer_text_mk3.py#L199-L208

**Comment by zeffii** [comment]
i might have time for this tomorrow.

**Comment by zeffii** [comment]
i started a debug branch for this locally, but didn't manage to resolve anything yet.

**Comment by zeffii** [comment]
```python
    def update(self):

        if len(self.inputs) > 0:
            multi_socket(self, min=1)

```
that does work but doesn't change the socket colours. these are symptoms of our broken update mechanism as a result of the event handler change in 2.80.

**Comment by zeffii** [comment]
it also doesn't make sense for this node to set the kind of output socket if the input sockets are mixed. 

I think the expected use of the join node is not for "packing" a stream with varying socket data, but rather all edges.. or all verts.. or all matrices.. etc.  not `(Verts, Matrices, Verts, Objects, Edges)`.

further maybe it does make sense to set the output socket if all connected input sockets are of a comparable bl_idname, and leave it generic (SvStringsSocket) if the input is mixed.

@Durman @portnov @nortikin  how do we feel about this.

**Comment by Durman** [comment]
Agree. If at least one input type is different from others output should have string socket type.

**Comment by zeffii** [comment]
please try this.
https://github.com/nortikin/sverchok/pull/2718

**Comment by zeffii** [comment]
resovled for now with that PR.

**Comment by Durman** [comment]
I have found interesting behaviour of update system during dragging and dropping link from input sockets. 

For example there is a node with input socket A. The socket has a link. If start to dragging the link from the socket it cause update event. 

- During this update event the socket will have peculiar properties. The `is linked` property will be True but collection of links of the node will be empty. Also during this event update function is called only for current node and then process only of current node is called. 

- Next update event is dropping of the link. In this case the socket has normal properties. Firstly update function of all nodes in a tree is called, then process of all nodes in a tree is called.

**Comment by Durman** [comment]
Interesting but between `node.update` event and `tree.update` event looks like something else is happening because when `node.update` is called `update_cache` has data but when `tree.update` is called `update_cache` already is empty.

**Comment by Durman** [comment]
Looks like on this part of code update algorithm are stumbling:
https://github.com/nortikin/sverchok/blob/d87c5fff58f9e98a44480111f216bf94cd42c6f2/core/update_system.py#L77-L78

**Comment by Durman** [comment]
Looks like that troubles are going away if to set for new links `is_valid` property to True manually during `node.update` event.

Actually the logic of current update system is that if node tree has at least one invalid link it does not make update of the tree. 

And it looks like if to create links during any update events (or at least `node.update` event) they are all invalid until update event does not finish.
