### ISSUE TITLE
A number node - slider

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2707]
I was interested in such feature for the `A Number` node:
![slider](https://user-images.githubusercontent.com/28003269/69944333-6bbdb700-1500-11ea-88c6-9d1d53b528f3.gif)
Unfortunately it looks like that can be done or it least in simple way. 

The thing is that for this feature properties of each instance of the node should have different max/min parameter but Blender dose not produce such functionality. At this moment the node do a trick for setting min and max parameter and it useless with slider. Probably another trick like creating for each instance of the node its own properties can do the job but I expect alot of troubles in such approach and I does not feel like spending a lot of time on it right now. 

Just for sharing my experience.))

If I recall correctly sliders had come since Blender 2.8.

**Comment by zeffii** [comment]
the core of this issue has bugged me since 2014, you can't set min / max on int / float sliders at runtime.  but the mechanism is pretty much there according to ideasman42, just someone has to add it to C

**Comment by Durman** [comment]
Interesting how it works here:

![slider](https://user-images.githubusercontent.com/28003269/71367449-84306700-25be-11ea-9b01-6adbdf902d4e.gif)

**Comment by zeffii** [comment]
i think those UI elements for shapekeys are defined in C and are allowed to be dynamic, a feature that must be unlocked in the API for python.. unless i'm completely mistaken, this is not something that can be solved in Sverchok code alone.
