### ISSUE TITLE
upgrade SV may version to current one in relation to may projects

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#2711]
Im gonna give a new try to upgrade my SV to latest version,
question is, the current may projects as we know will break because of that socket naming stuff we saw days ago,
in order to fix this, I guess I can replicate the very same nodes creating them again and that should work, right?
what I mean is that apart from that naming issue, the rest of SV remained the same, right? so if I reconstruct the very same nodes in the same may project, after upgrade, it should again work all well, right?
thank you ;)

**Comment by zeffii** [comment]
yeah, if you can take a screenshot in the older sverchok,  recreating in current version is going to be fine.

i already suggested that you export the nodetree (as a .json) using the Export tab in the N-Panel (from this May version), and if you paste the link here, we can edit the  json if needed, for reimporting into the current version of Sverchok.

![image](https://user-images.githubusercontent.com/619340/70079969-05bb5780-1606-11ea-9c2e-a97c3491c318.png)

(that should create a json on your disk... copy it's content into a gist or something.  https://gist.github.com/
