### ISSUE TITLE
SV 2.80 branch has issue with BMesh Viewer displaying vertex and edges

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2714]
I updated recently and finding issue with Bmesh and also VD (cannot bake) unable to view and display vertices and edges properly...

<img width="707" alt="Screen Shot 2019-12-05 at 3 15 08 pm" src="https://user-images.githubusercontent.com/3952687/70203767-2accd900-1772-11ea-8981-1bbb16c9a8e6.png">
<img width="507" alt="Screen Shot 2019-12-05 at 3 14 46 pm" src="https://user-images.githubusercontent.com/3952687/70203768-2accd900-1772-11ea-8e45-13997caf86ea.png">

**Comment by enzyme69** [comment]
https://youtu.be/615ldXPJMgw

Hmmm... well it works time to time, but I am experiencing weird issue of vertices or edges not displaying until I get into Edit Mode.

**Comment by Durman** [comment]
Is it enabled?
![2019-12-05_08-56-02](https://user-images.githubusercontent.com/28003269/70205340-2803c100-173d-11ea-8bf8-6d9f84d50ea6.png)

**Comment by enzyme69** [comment]
Yes, but it might just be a bug with Blender and MacOS Catalina. So it's false alarm, but I will keep eyes... Thanks!

**Comment by Durman** [comment]
Try to recreate this without Sverchok.

**Comment by zeffii** [comment]
also 
- have the outliner in the screenshot, (shows us if the Bmeshviewer generated anything..) 
- the terminal output (maybe there are errors! maybe not! )
- also.. execute this in ther bpy console..
```python
>>> bpy.app.build_date, bpy.app.build_hash
(b'2019-11-21', b'ba1e9ae4733a')
```

**Comment by enzyme69** [comment]
```
>>> bpy.app.build_date
b'2019-11-20'

>>> bpy.app.build_date, bpy.app.build_hash
(b'2019-11-20', b'26bd5ebd42e3')
```
Generating random points, normally BMesh Viewer displays it in realtime. But this time, I need to select the mesh, then go to Edit Mode, then back, and .... wait and it appears.

Making and drawing line is also funny because axis is hiding the line. Hmm... It's probably MacOS Catalina thing. Not sure how this kind of resolved, but I guess we will wait and see...

<img width="1245" alt="Screen Shot 2019-12-05 at 10 09 29 pm" src="https://user-images.githubusercontent.com/3952687/70230286-1d344500-17ac-11ea-8525-5005e9f8bc55.png">
<img width="1247" alt="Screen Shot 2019-12-05 at 10 09 16 pm" src="https://user-images.githubusercontent.com/3952687/70230290-1d344500-17ac-11ea-83b3-4d4c0002f3f6.png">

**Comment by zeffii** [comment]
that's a pain in the ass @enzyme69  - not a whole lot we can do.

i don't think we have many users, and even fewer mac users.

**Comment by enzyme69** [comment]
My feeling is that with Blender 2.81 and up, we can no longer see Points / Vertices only in the 3D view. Well I can always use SV Viewer Draw :D Thanks man, yes maybe only under 1000 people in the world use SVerchok in Blender.
