### ISSUE TITLE
renderscript frame by frame - particle system reset

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2717]
@zeffii as this thread is about temporal changes, may I ask something else here as Im not sure where to ask it, its unrelated so I apologize but its related to a code you all gave me in the past to render frame by frame to avoid the animation crashes (I posted question on blender forums but no answer so far): 

```python
import bpy 
file_path = 'xxxxx'

start_frame = 0
end_frame =130

for act_frame in range(start_frame, end_frame + 1):
    bpy.context.scene.frame_current = act_frame
    bpy.ops.node.sverchok_update_all()
    bpy.context.scene.render.filepath = file_path + str(act_frame).zfill(4) +'.png'
    bpy.ops.render.render(write_still=True)
    print(act_frame)

print ('done')
```

The question is, when I have a particle system in blender, and I change the position of the particles via python script, it all works, but when I render frame by frame (or the animation as a whole), the positions of the particles are not being taken from the script; if I render a single frame then yes (after moving from previous frame), but if I just render the whole thing frame by frame then the particle positions are not taken from the python script mmm, I posted a question on blender forums but no answer so far, I thought maybe you know something about this as you are way more experts than me, thank you for any tips :)

_Originally posted by @wisarTR in https://github.com/nortikin/sverchok/issues/2709#issuecomment-562497870_

**Comment by zeffii** [comment]
for Blender 2.8+ i think we aren't supporting particles (yet)

as for 2.79, from memory Blender sends out events in this order: 
0. scene update pre
1. scene update post
2. before rendering
3. after rendering
4. before changing frame
5. after changing frame

, we capture these events and execute code appropriately. When our node tree is processed, it can set the locations (maybe other properties too) of particles, and that must be the very last thing that Sverchok does before Blender renders the frame, otherwise -as you see- Blender internally sets the particle properties to what they would have been if sverchok wasn't involved. Here the term to use is "deterministic race condition" i think. "What updates the particles just before rendering, Sverchok (good) or Blender (not so good for you)".

i've never much liked this approach to scripted particles, because it is convoluted. good thing 2.80 is getting dedicated particle nodes.

**Comment by javismiles** [comment]
@zeffii thank you, I see, as Im only using 2.80 from now on, mmm, so maybe there is no way to make my script work, maybe I have to research into those particle nodes of blender

**Comment by javismiles** [comment]
@zeffii it is really fascinating that in 2.8, if you move manually from one frame to the next, and then render 1 single frame, it works perfect and the positions of particles are taken from the python script and all great

but if you decide to render all the frames of the animation either with the animation button or manually from a script, no matter what you do, blender will keep resetting the particle positions to its own internal ones, even if doing:

bpy.app.handlers.frame_change_pre.append(particleSetter)
bpy.app.handlers.render_pre.append(particleSetter)
bpy.app.handlers.render_post.append(particleSetter)
bpy.app.handlers.render_init.append(particleSetter)
bpy.app.handlers.frame_change_post.append(particleSetter)
bpy.app.handlers.depsgraph_update_post.append(particleSetter)
bpy.app.handlers.depsgraph_update_pre.append(particleSetter)

intercepting every possible event

even doing a timer

def every_2_seconds():
    particleSetter(5)
    return 0.00001
bpy.app.timers.register(every_2_seconds)

nothing, seems impossible, but amazing that with 1 single frame it works

**Comment by zeffii** [comment]
@javismiles ,  painful stuff .. i know. i can think of some ugly hacks, 
repeatedly, till frame range is completed:
```
for each frame:
   - that spawn a subprocess and open blender, 
   - set the frame, 
   - render to file name , 
   - then closer blender,
```

hahaha. i would do _that_ as a last resort.

**Comment by javismiles** [comment]
@zeffii wow I need desperately a hack Zeffii but that one hack seems rather insane ;)

**Comment by zeffii** [comment]
you'd be surprised, sometimes ugly hacks are the way to go.

**Comment by javismiles** [comment]
@zeffii maybe you are right, in any case im not sure how to do that, how to spawn a subprocess and open blender headless... etc

**Comment by javismiles** [comment]
@zeffii jumping by the way to a specific frame could fail, what works always is to go to the frame before the frame you want, and then advance a frame forwards, and then render that new frame, that always works

**Comment by javismiles** [comment]
@zeffii seems to be the act itself to advance from one frame to the next that makes it work, but to advance with the arrow key in the viewport, is that reproducible by code?

**Comment by javismiles** [comment]
@zeffii this is actually the puzzling thing, move to x frame and then advancing to x+1 frame with the keyboard arrow will make things work always 100%. But simply jumping to x frame, and rendering, many times can fail (kind of random). What never fails is to go x frame, then advance to x+1 but through the keyboard.   Simply setting the frame directly through code just won´t make it

**Comment by zeffii** [comment]
i think it is possible to emulate the 'right arrow key press', by triggering the same code that that keymap triggers.
```
bpy.ops.screen.frame_offset(delta=1)
```

**Comment by zeffii** [comment]
if you made a small, simple demo animation file, that I could run and experiment with - that would decrease my workload/ and make me happier.

**Comment by javismiles** [comment]
@zeffii let me try to get that to you yeah

**Comment by javismiles** [comment]
@zeffii I got it, give me an email to send it to you please

**Comment by zeffii** [comment]
you can zip it, and drag it into these issues.

**Comment by javismiles** [comment]
@zeffii get it from here please https://we.tl/t-itYXc82xc7
contains .blend and .csv
you may go to text area and run the script that is there,
then you will see a bunch of particles that begin from a cloud above and move until resting at their final unified positions

**Comment by zeffii** [comment]
oh . ok

**Comment by zeffii** [comment]
that file didn't contain a sverchok node tree?

**Comment by zeffii** [comment]
use the "Shield" icon , to give the nodetree a fake user.
![image](https://user-images.githubusercontent.com/619340/70327059-4bf6fd80-1836-11ea-9e4c-0628af749b46.png)
, then save the blend

**Comment by javismiles** [comment]
@zeffii yes because the part to solve actually is just the part of blender ignoring the changes to particles positions from the python script so that´s the only part that matters, now if you actually think that what I have in that code could be replicated with some sverchok nodes that would be awesome also :)

**Comment by zeffii** [comment]
maybe someone else feels like converting that to a nodetree.. my time is limited at the moment

**Comment by javismiles** [comment]
@zeffii totally understand I will try myself to see if I can manage
