### ISSUE TITLE
API changes 2.8+

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2720]
https://docs.blender.org/api/current/change_log.html

`bpy.types.NodeSocket`
Added
`bpy.types.NodeSocket.draw_shape`
`links` - List of node links from or to this socket. **Warning: takes O(len(nodetree.links)) time.** (readonly)

`bpy.types.BoolProperty / FloatProperty / IntProperty`
Added
`bpy.types.BoolProperty.array_dimensions`

`bpy.types.UILayout`
a lot of [changes](https://docs.blender.org/api/current/change_log.html#bpy-types-uilayout)

new - `mathutils.geometry.delaunay_2d_cdt`

**Comment by Durman** [comment]
![2019-12-10_12-50-05](https://user-images.githubusercontent.com/28003269/70513740-a1d7e800-1b4b-11ea-9de4-67c0e6fa8b7b.png)

**Comment by Durman** [comment]
Looks like `bmesh.ops.inset_individual` does not work as intended.
<details> 
  <summary>cod</summary>  

```Python
import bpy
import bmesh
from bmesh.ops import inset_individual

verts = [[0,0,0], [1,0,0], [1,1,0], [0,1,0]]
faces = [[0,1,2,3]]

bm = bmesh.new()
[bm.verts.new(co) for co in verts]
bm.verts.ensure_lookup_table()
[bm.faces.new([bm.verts[i] for i in face]) for face in faces]

inset_individual(bm, faces=list(bm.faces), 
                     thickness=0.5, 
                     depth=0.0, 
                     use_even_offset=True,
                     use_interpolate=True, 
                     use_relative_offset=False)

me = bpy.data.meshes.new("Inset face")
bm.to_mesh(me)
bm.free()
obj = bpy.data.objects.new("Inset face", me)
bpy.context.collection.objects.link(obj)
```

</details>

![2019-12-11_09-09-23](https://user-images.githubusercontent.com/28003269/70593355-2aab5e00-1bf6-11ea-92f5-9be6b00e3bad.png)

**Comment by Durman** [comment]
Blender 2.81
![2019-12-16_20-13-15](https://user-images.githubusercontent.com/28003269/70923002-86377a80-2040-11ea-9e58-ffbcf55a2571.png)

**Comment by Durman** [comment]
If I have understood this correctly, now, during update event `is_linked` status of socket can be False and have links and vice versa. 
There are two possible cases: 
- when socket gen new link(s): `is_linked` is False, links are True. 
- when socket loose its link(s): `is_linkd` is True, links are False.

**Comment by portnov** [comment]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.82/Python_API
> The CurveProfile type was added which allows the construction and evaluation of a 2D curve. (ba1e9ae4733a)

The widget supports arbitrary curves rather than an X to Y mapping, so the result of evaluation is a 2D vector.

**Comment by portnov** [comment]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.81/Python_API # Operators
> Operators can now have a dynamic tooltip that changes based on the context and operator parameters. 

This is interesting for menus and similar things.

**Comment by zeffii** [comment]
@portnov  we could drastically reduce the number of operators we create ( one for each node? )

**Comment by zeffii** [comment]
`mesh.clear_geometry()` is something i'll be applying too.

**Comment by portnov** [comment]
We could, but i'm not sure we should. Current implementation adds all nodes into standard "Space" menu, and I like that :)

**Comment by zeffii** [comment]
refresh my memory, you implemented (quite rightly) an `Add` operator per node so that we could give each node a unique "tooltip". I would like to explore reversing that without introducing regressions of course.

my initial implementation of `sv_search` operator, didn't rely on unique operators per node.

it's not a massive issue, but it does bug me for some reason

**Comment by zeffii** [comment]
are there any examples of the 2d curve widget, does it require a Curve Object

**Comment by Durman** [comment]
More information about curve profile:
https://developer.blender.org/D5516

**Comment by portnov** [comment]
@zeffii 
https://github.com/nortikin/sverchok/blob/61deb2ff87885fae0489c8016e03c2e5fa604dfd/menu.py#L143-L152

Standard "Space" (F3) menu just lists all registered operators. So since we register specific operator per node, there is separate line in the "Space" menu.

**Comment by zeffii** [comment]
@portnov  i'll defer to your familiarity on that section of the code, until i get the urge to procrastinate some day.

**Comment by Durman** [comment]
Using different shapes of sockets, source: https://code.blender.org/2020/03/feb-2020-ui-workshop/
1. Data-flow Nodes
The nodes you already use in shaders and in the Compositor all represent a flow of data. Particle nodes will also include data-flow nodes.
2. Control-flow Nodes
These don’t represent data being passed from left to right at all. You can think of them is being a ‘condition gate’, and can essentially be read from right to left.
3. List Nodes
Not a flow, but simply a list. We use these for effectors like emitters, forces and events. They are essentially to be read as a list from top to bottom.

![Screenshot-2020-02-28-at-16 44 46-1024x485](https://user-images.githubusercontent.com/28003269/76058221-39a37180-5f95-11ea-8102-3ecf3f89adc6.png)

**Comment by Durman** [comment]
https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Python_API

**Comment by Durman** [comment]
> The bgl module will be deprecated in Blender 3.0, in preparation of future Vulkan support. Add-ons should switch to using the gpu module, so that they will work with both OpenGL and Vulkan.

**This can be a lot of work -**  https://developer.blender.org/D8826

> New BlendFile.temp_data method, providing a context manager to temporarily load blend file data without linking/appending it into the current file.

This can be useful in unit tests. https://developer.blender.org/rB9e0921497912cbfe9846358d1cb1220f88315f80

> UI: Add support for bl_description and python doc-strings for panel classes.

https://developer.blender.org/rB8971018eb64a

![muting wires](https://user-images.githubusercontent.com/28003269/120629581-050fb580-c477-11eb-9ae9-a6f98750db76.gif)
https://developer.blender.org/rB266cd7bb82ce

**Comment by Durman** [comment]
Sockets now have description attribute.

https://docs.blender.org/api/current/bpy.types.NodeSocket.html#bpy.types.NodeSocket.description
