### ISSUE TITLE
Port "Viewer GP" node to 2.8x

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2722]
Port #1417 to 2.8x branch.

**Comment by zeffii** [comment]
i wonder what kind of fresh hell awaits me.

**Comment by zeffii** [comment]
i've made a small amount of progress. the node draws lines at least.

waiting for a reason to do a more extensive update. but it won't be soon.

**Comment by zeffii** [comment]
this is doing about the same as pre 2.8 now. closing this in anticipation of a more structured todolist for that node.  low priority.
