### ISSUE TITLE
latest blender 2.81a + latest Sverchok fails to activate

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#2736]
finally I decided to try to upgrade to latest blender and latest sverchok,
so far I was using blender 2.8 and the sverchok from may 2019.

So in installed blender 2.81a and that works all fine with the sverchok from may 2019. When I move to the latest sverchok I will have to rebuild my graphs because of that change with the socket thing but I decided that´s ok so I wanna do it

But then I tried to install on blender 2.81a the latest sverchok as per this link:
https://github.com/nortikin/sverchok/issues/2326

and when trying to activate it, many error messages appear and it just won´t activate properly, is maybe the latest version not ready yet for 2.81?

thank you :)

**Comment by javismiles** [comment]
![addonsverchokactivation281](https://user-images.githubusercontent.com/1000452/70827240-19767300-1de9-11ea-9353-f6233fae25ae.jpg)

there the error messages I get when trying to activate latest sverchok for 2.8+ with blender 2.81a

**Comment by zeffii** [comment]
for sverchok in Blender 2.8+, i only use nightly builds. from builder.blender.org , even 2.82 version should be fine.

i suspect what might have happened is that you pressed enable twice, before it  got a chance to enable.

**Comment by javismiles** [comment]
thank you @zeffii , its definitely not pressing twice, I tried it like 5 or 6 times, clicking only once, and immediately those errors pop up, surely its not the pressing twice, so... I dont know.. tried it many times

**Comment by zeffii** [comment]
you restarted Blender ?

**Comment by zeffii** [comment]
the official Blender `2.81a` is already a bit dated i think, definitely be using a recent 2.82 from builder.blender.org as described here. 

https://github.com/nortikin/sverchok/issues/2326

and maybe get the latest `b28_prelease_master` zip from that same link.

i'm not aware of this being broken.

**Comment by javismiles** [comment]
thank you  @zeffii , of course I restarted and even reinstalled 2.81a again, also got the very latest zip from the same link today, got it all fresh today,
I totally believe you if you say that its not broken, so I guess another day I will try again from scratch the process and see if it then work, thank you :)

**Comment by zeffii** [comment]
seriously .. i don't advise using the official builds of blender 2.8  , i'm not testing against that old stuff.

https://builder.blender.org/download/    <- 2.82

**Comment by zeffii** [comment]
the Python error message is also not exactly helpful, but it does hint at a location that is known to cause problems. the requests module, on posix systems.

**Comment by zeffii** [comment]
perhaps if you where loading Blender from terminal you could print/copy paste the entire error output into the textfield here, the screenshot unfortunately just shows the last 20 lines, but we might have the answer in earlier errors.

**Comment by javismiles** [comment]
thank you @zeffii , so you mean that the official builds of blender are too old and that it is safe to be using the nightly ones? arent they more buggy? 
as for executing from command line, will try yes, running blender from command line I get it that it should show me the entire output will try as soon as I can thank you ;)

**Comment by zeffii** [comment]
> thank you @zeffii , so you mean that the official builds of blender are too old and that it is safe to be using the nightly ones? arent they more buggy?

some nightly builds are buggy, but generally they are very well behaved. The thing to remember is that the nightly builds fix tonnes of bugs encountered in the official releases, but because they are works in progress occasionally they will have new and unique bugs of their own.  (but these usually are fixed in the next nightlies..)

the official b2.81a is a snapshot of the development progress, and we don't have resources to have a version of Sverchok running on all releases. It would also make sverchok code a bit more bloaty in places.

**Comment by portnov** [comment]
So. @javismiles,
* have you managed to enable sverchok?
* if not, please specify the exact blender build you are using (whether do you download from blender.org main page, or is it a night build from builder.blender.org or what)?

**Comment by zeffii** [comment]
get back to us if this is still a problem after using a nightly build.

**Comment by javismiles** [comment]
@zeffii good day I was about to reply, the build I used was the official one offered at the official blender download page for the latest version 2.81a, from the main page yes

couldnt try yet a nightly build but I will do it as soon as possible and tell you then what happens when I do, thank you again for your great support :)

**Comment by FabianSchempp** [comment]
Hi, i have the same Problem with latest nightly build 2.82 Alpha

**Comment by zeffii** [comment]
but @FabianSchempp  , the error you're getting is because you are using `sverchok-master` (which is not compatible with Blender 2.8+), you must install Sverchok `b28_prelease_master`, see https://github.com/nortikin/sverchok/issues/2326  , the [`zip`](https://github.com/nortikin/sverchok/archive/b28_prelease_master.zip) part is important.
