### ISSUE TITLE
lamp node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2742]
## Problem statement

Looks like the node should be fixed to new Blender API.

```Python
  File "C:\Users\....\Blender_code\addons\sverchok\nodes\viz\lamp_out.py", line 206
, in make_lamp
    lamps_data = bpy.data.lamps
AttributeError: 'BlendData' object has no attribute 'lamps'
```

Blender 2.81

**Comment by zeffii** [comment]
it's now `bpy.data.lights`

and references to scene, in that section of the code should be
```python
collection = bpy.data.context.scene.collection
   ...
collection.objects.link(...)
collection.objects.unlink(...)

```

**Comment by portnov** [comment]
This particular problem is solved. There is still question of Eevee support, but that is for another issue.
