### ISSUE TITLE
Limited Dissolve nodes?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2746]
We appear to have two "limited dissolve" nodes: limited_dissolve.py and limited_dissolve_mk2.py. None of them is in old_nodes. None of them has any documentation. Both appear to be made by @Kosvor2 .

Do we need them both?

Mk2 has unclear sockets "bmesh_list", "bm region". What they are for?...

**Comment by Durman** [comment]
#601
#868
#2192

It looks like the node just adds the result into given Bmesh list, not sure when this approach can be useful.

```Python
        bmlist = BML.sv_get([])
        bmlist.extend([bmesh_from_pydata(verts, edges, faces, normal_update=True) for verts, edges, faces in zip(*mlr([Verts.sv_get(), Edges.sv_get([[]]), Polys.sv_get([[]])]))])
```
