### ISSUE TITLE
Cricket Node is facing the wrong way

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2748]
<img width="856" alt="Screen Shot 2019-12-17 at 11 37 14 am" src="https://user-images.githubusercontent.com/3952687/70954533-b2471000-20c1-11ea-8fe7-b98e67a5a115.png">

This just more like an enhancement request, I wonder if Cricket mesh node can face the right way (front is front) just like Suzanne head. 

Thanks!

**Comment by zeffii** [comment]
i'm not sure what the deal is there, maybe i'm not remembering this correctly but i thought when i committed this originally that the two did face in the same direction.

it's a trivial fix, so yeah, i will.
