### ISSUE TITLE
Object ID Selector issue with GP/Frame Select

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2751]
In the old time, we can pick frame from grease pencil object ID access, but in 2.8x we can no longer pick frame. Active frame is working however.

Maybe it's just the current limitation?

<img width="1123" alt="Screen Shot 2019-12-18 at 1 22 27 pm" src="https://user-images.githubusercontent.com/3952687/71050524-8a2ae000-2199-11ea-86cb-6c9fbf726fad.png">

**Comment by zeffii** [comment]
there's API rename issue there

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2299/commits/1c11aea24216804b2d2fa2c2ff37ad6b2402223e

that should address the real problem, but because GP is now a bit more complicated, it might make sense to devote an entire node to its Selection features.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/71079761-251cbd80-218c-11ea-8207-86ca63fcd99f.png)

**Comment by zeffii** [comment]
also the frame update event, (if you use the left/right keys) will not pass the correct set of points from the Object ID Selector node -- you'll notice it lags a frame or two.

fixing this is not high on my todo, but it does tie-in with a general update event issue that we have. but hey... we are not "Animation"nodes :)   using the frame integer setter from the `Frame Info` node, does work.
