### ISSUE TITLE
Request : option to enable use uv mapping from polyline 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2763]
Is there maybe a solution that you can enable use uv for mapping from the polyline viewer 
This way you have automatic uv with sverchok polyline curve 

![image](https://user-images.githubusercontent.com/49908008/71356517-cb006b80-2582-11ea-85c6-290334c8c8ef.png)

**Comment by zeffii** [comment]
yes, i think that should be possible

**Comment by zeffii** [comment]
"Use UV for mapping"  is
```python
>>> obj.data.use_uv_as_generated = True
``
and use auto texture space
```python
obj.data.use_auto_texspace = True
```
yeah, looks dooable.

**Comment by BennyGovaerts** [comment]
Excellent , look forward to try it

**Comment by zeffii** [comment]
i've committed a preliminary `draw buttons ext` ( N Panel ) option for this. As in your image

https://github.com/nortikin/sverchok/pull/2765

update Sverchok
