### ISSUE TITLE
Drawing number of objects on sockets

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2772]
## Problem statement

The function is calling each time when UI is redrawing. UI is redrawing each time when mouse is passed over any interactive element on a screen. The function is calling `other` method of socket which is calling `links` method which is actually quite expensive. Calling `links` method takes O(n) time where `n` is number of links in a tree. 
https://github.com/nortikin/sverchok/blob/61deb2ff87885fae0489c8016e03c2e5fa604dfd/core/socket_data.py#L47-L67
So with growing size of a tree number of calculations is growing exponentially and recalculating quite often. It definitely can be reimplemented. I think that number of objects can be recalculated during tree update event and memorize in sockets somewhere.

**Comment by zeffii** [comment]
perhaps, the socket class `common` can hold a 'object count', which is set only at the end of a successful completion of a node's `process()`  (also means setting to a default 0 prior to calling `process` ).

i've thought about this too in the past when visiting these areas of code, and i'm supportive of reducing redundant cpu cycles, but here i'm apprehensive to implement `object count`.

**Comment by zeffii** [comment]
but whatever :)  we can try it

**Comment by ly29** [comment]
Having a compiled links data structure would be good and would also make the update system easier. 
Removing reroutes and wifi (if that is still is used) is a big win and would make the update system easier.

**Comment by ly29** [comment]
Made a very simple cache implementation for these kind of issues. Untested as a minimal implemenation.
https://github.com/nortikin/sverchok/blob/testNameCache/core/socket_data.py

**Comment by Durman** [comment]
By the way I was thinking about `socket.sv_links` approach and it looks it would be impossible to implement. Because what this method should returns? We can't keep straight references to nodes. Links to nodes can't be created via Pointer property. We can keep their names but search node by their name again returns to O(n**2) performance.

**Comment by nortikin** [comment]
default off
optionally turn it on may be better experience.

**Comment by Durman** [comment]
![lags](https://user-images.githubusercontent.com/28003269/82578548-93333980-9b9d-11ea-85f8-1c05b48d3651.gif)

https://github.com/nortikin/sverchok/blob/09e9788c53c7c92b447c02f60e1851a4aecfedc2/core/sockets.py#L229
And performance without calling the function.
```Python
info_text = t + '. ' 
```

![no lags](https://user-images.githubusercontent.com/28003269/82578703-cd9cd680-9b9d-11ea-937a-86260d28d2dc.gif)

**Comment by nortikin** [comment]
every time calculate length is much of lost?

**Comment by Durman** [comment]
According the fact that not just number of objects of other output sockets should be shown but also the number of objects after they will be converted from that sockets the only way to improve performance is to calculate and to memorize this value during update event. Only case when number of objects does not coincide is conversion from vector to matrix sockets now. And the reason of it is that matrixes are treated differently and inconsistently with other data types.
