### ISSUE TITLE
Duplicate object  along edge with mask 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2777]
Duplicate along edge works fine except if i scale the object lower then 0.2 is this normally or how can i avoid this , or how can i select only copy to the top edge 

![image](https://user-images.githubusercontent.com/49908008/71586962-41b9dd80-2b1c-11ea-8297-eff95d31a81b.png)
![image](https://user-images.githubusercontent.com/49908008/71586976-4d0d0900-2b1c-11ea-8446-c6b5313d39b9.png)
![image](https://user-images.githubusercontent.com/49908008/71586985-539b8080-2b1c-11ea-834e-09748ce542fd.png)

**Comment by BennyGovaerts** [comment]
![image](https://user-images.githubusercontent.com/49908008/71587103-b7be4480-2b1c-11ea-8ce2-ff5b24a6d24c.png)

**Comment by BennyGovaerts** [comment]
It works correct if i do it like this 
![image](https://user-images.githubusercontent.com/49908008/71588914-7aa98080-2b23-11ea-862e-666dfc986783.png)

**Comment by zeffii** [comment]
stale topic?
