### ISSUE TITLE
Question : Polyline input bevelworks this inside the nodetree 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2780]
Can this input be used inside the node tree to make everything procedural in the future 
![image](https://user-images.githubusercontent.com/49908008/71700822-4d303180-2dc6-11ea-8c19-4719b97353bd.png)

**Comment by zeffii** [comment]
Last time I checked you can link the output of a CurveViewer Node to that bevel-object socket, to set the shape of the PolyLine's bevel. I'm not sure i understand the question.

...i  do suspect we need to add more throttling to the Object-Viewer nodes, so we don't cause stupid recalculations

**Comment by BennyGovaerts** [comment]
Excellent ; works fine ,
