### ISSUE TITLE
Is there a solution to use collection with polyline 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2781]
For example if you use a matrix with the polyline it would be better to assign this to a collection in the future
![image](https://user-images.githubusercontent.com/49908008/71701042-7d2c0480-2dc7-11ea-8d0e-5e1738bd449b.png)

**Comment by zeffii** [comment]
yeah totally makes sense - and is high on my todo.

**Comment by BennyGovaerts** [comment]
Excellent , thanks for the feedback

**Comment by zeffii** [comment]
currently no, but implementing this is part of single sweep over the object nodes, to keep the code uniform and modular (if practical)

https://github.com/nortikin/sverchok/issues/2807
