### ISSUE TITLE
"Crop Mesh 2D" is not vectorized properly

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2790]
I think, "zip" near line 172 must be replaced with "sverchok.data_structure.zip_long_repeat". At least, this fixed the problem for me.

## Steps to reproduce

https://gist.github.com/f286756f1ae1d27cf487d88dee23721a

1. Generate a list of several objects
2. Connect them to verts/polys inputs of "Crop mesh"
3. Connect one object to "Crop verts/polys" inputs of "Crop mesh"

## Expected result

The node will cut a hole in each of the provided objects

## Actual result

The node processes the first object and stops

## Sverchok version
b28 master

**Comment by Durman** [comment]
For some reason when I was coding the node I have thought that repeating mesh is not something expected but it is probably better to fix indeed.
