### ISSUE TITLE
Monad: Loop requires output sockets to be linked

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2798]
https://github.com/nortikin/sverchok/blob/55f41cc778740eb5317faadb86307d531a1f0958/core/monad.py#L602-L604

If you create a monad with Loop, and do not connect one of output sockets of the Monad to anywhere, then the data will not be re-put from output to input during looping.
I don't think this is desirable behavior, and most certainly it is not obvious.

Options:
a) remove that is_linked check at all;
b) pass optional argument from do_process_looped to do_process, that would say "do not check is_linked".

**Comment by zeffii** [comment]
Sure, it could be more lenient. The current implementation is intentional though.

**Comment by zeffii** [comment]
i think, to preserve my own sanity i will keep this function unchanged. The behaviour is described in the docs now at least.
