### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2804]
RELEASE DONE

* [x] Rename master -> 279_master,  b28_prelease_master -> master — @portnov at 06:30 UTC
* [x] Reconfigure Travis CI to inform it about new branch names — @portnov 
* [x] Create a first github release with Sverchok code, add generated documentation — @portnov 
* [x] Update Release Notes — @portnov 
* [x] Deprecate existing 2.80 installation instruction — @portnov 
* [x] Write a new instruction for 2.79 installation — @portnov
* [x] Update README — @portnov
* [x] Update github pages if necessary — @zeffii 
* [ ] Update documentation at readthedocs — @nortikin 
* [ ] Check that all infrastracture (github, travis) is working as expected — @zeffii @portnov  @nortikin  @Durman  @vicdoval 
* [ ] Check that updated installation instructions are correct and working — @zeffii @portnov @nortikin  @Durman @vicdoval 
* [x] After all previous is done — publish announcement at VK: @portnov to prepare text, @nortikin to publish
* [ ] Publish announcements somewhere else — @zeffii, @nortikin  and @portnov to decide who and where.

-----------------

HOW TO make your current git checkout work with new branches:

One way is to delete your existing repository, and clone git@github.com:nortikin/sverchok.git in to another directory. But you may do not want to do that if you have some unpushed changes or for other reasons.

You can rename and reconfigure your local branches:

```
# Let's assume you're starting from old master branch, which was for 2.79
$ git checkout master
# Rename it to 279_master according to github branches
$ git branch -m master 279_master
# Reconfigure repository to say which github branches corresponds to your one
$ vi .git/config
```

find the lines

```
[branch "279_master"]
  remote = origin
  merge = refs/heads/master
```

and make them look like

```
[branch "279_master"]
  remote = origin
  merge = refs/heads/279_master
```

```
# Make sure pull is working correctly
$ git pull # should say that there is nothing to pull
# Now let's deal with b28 branch
$ git checkout b28_prelease_master
$ git branch -m b28_prelease_master master
$ vi .git/config
```

find the lines 

```
[branch "master"]
  remote = origin
  merge = refs/heads/b28_prelease_master
```

and make them look like

```
[branch "master"]
  remote = origin
  merge = refs/heads/master
```

```
$ git pull # should pull latest changes from 2.8x master.
```

-----------------

Our 2.8x branch seems quite ready, and there are not so many issues left in the "2.80 Mandatory" milestone.
On the other hand, the development seems to be actively going in b28_prelease_master, but it mostly is not related to 2.80 port anymore. We have to put an end for this :)
So, I propose:
1) to agree a date, at which b28_prelease_master will be renamed to master, and current master will be renamed to 279_master ("technical release");
2) For each currently active PR, we will have to decide: whether we will merge it before the agreed release date, or will we postpone the merge a bit, to merge it to the new master.
3) Let's select the release day to be January 12, 2020 (Sunday).

@zeffii @Durman @vicdoval @nortikin Any comments?
If there will not be any objections in the comments until January 12th, I will rename branches at Sunday. I will write here before I will do renaming, to avoid confusion.

I can update release notes and Readme. Also I will reconfigure Travis to inform it about new branch names.
Someone should update github pages and published documentation. @zeffii  / @nortikin  ?
Probably after we do technical release, update documentation and make sure our infrastructure is working correctly after branch renaming, we should announce the release somewhere. BlenderArtists thread? VK most probably (russian-speaking group).

**Comment by zeffii** [comment]
> actively going in b28_prelease_master, but it mostly is not related to 2.80 port anymore. We have to put an end for this :)

agreed. hard yes.  
  - moving current 2.79 master to LTS mode. 
  - and setting it's update zip links to point at that location.
  - maybe include code to prohibit users from enabling old sverchok in new blender, and viceversa.

i'll update the github pages, and do a bit of a cleanup on them. Sunday seems a fine day.

**Comment by Durman** [comment]
I have not objections. I think we can keep up with creating pre release branches. I like feeling that merging can't brock anything in master. It gives opportunity to test everything all together. I think it is more effective way than test each branch separately.

**Comment by zeffii** [comment]
also a useful administrative move, signalling that "master" will now be bound to 2.8+

i'm curious what the statistics are, but i suspect that most new people now start directly with 2.8+ and that a large portion of Blender users now use 2.8 more than 2.79.

**Comment by portnov** [comment]
I believe most users that are starting to use Blender now, are off course using 2.8; but there are a lot of people who used 2.7x for a long time in production, and it is not so easy for them to switch to 2.8. I do not think there are a lot of Sverchok users among them, but even so... I don't think it will take us too much resources to just keep 279_master branch and a wiki page with instruction how to install Sverchok for 2.79. If there will be 1-2 issues per year about 2.79 branch — I believe we can handle it :)

**Comment by nortikin** [comment]
docs will be done.

**Comment by portnov** [comment]
I will start renaming the branches nearly in 1 hour, at 06:30 UTC (09:30 MSK).
If you're coding right now and wish to push to b28_prelease_master before "technical release", it's now.
If you need a delay for some reason, please write here.

**Comment by portnov** [comment]
Branches are renamed. "master" since now is the main branch for ongoing 2.8x development. "279_master" is the support branch for Sverchok for 2.79.

**Comment by portnov** [comment]
I've updated the description with an instruction of what developer should do to deal with branches renamed on github.

**Comment by portnov** [comment]
Travis reconfiguration is in progress, so travis may fail for some time. I'll write here when it's ready.

**Comment by portnov** [comment]
Travis for "master" and "279_master" seems to be working again.

**Comment by portnov** [comment]
Btw, I've managed to build `.tar.gz` with all imaged included, but it's 244 MB >__<
So in the release I've put a tarball without images included (images point to github).

**Comment by portnov** [comment]
I've checked installation instructions for master and for 279_master — works for me. But maybe someone will find problems?...

**Comment by portnov** [comment]
@nortikin could you update documentation on readthedocs?

**Comment by Durman** [comment]
I have installed it with success. But I had to find out that dots are forbidden in names of folders of addons. Also it looks like this part on main page of Sverchok is outdated:

> If you are installing from a release found [here](https://github.com/nortikin/sverchok/releases), these files contain folders that have the dots mentioned in the previous point. These versioned release zips are not meant for installing from, but rather can be used to try older versions of Sverchok when you are using older .blend files and older Blender versions. Don't use these release zips if you are installing sverchok for the first time.

Or is it okay?

**Comment by zeffii** [comment]
@Durman   why what do you propose?

@portnov i've updated the `gh-pages` minimally. I do want to change the Links section and ditch a bunch of the tutorials from so many different sources using a snapshot of Sverchok that will be almost alien to new users. Maybe it's time we do our own.

**Comment by Durman** [comment]
I can mention the event on Blender artist.

**Comment by portnov** [comment]
I do not oppose :)

**Comment by portnov** [comment]
Announcement in the Blenderartists thread is done.

**Comment by portnov** [comment]
I believe we can consider this done.
