### ISSUE TITLE
Before Release Recommendation_1 (Disable or Fix "Add" Pulldown Menu in Header)

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2805]
<img width="500" alt="post 1" src="https://user-images.githubusercontent.com/59537375/72014263-64cb4800-3214-11ea-80a8-5f85ae53dda9.PNG">

## Problem statement
The Add pulldown menu search function in the Header does not work (it is blank and gives no results).  In addition, the sub-categorization of nodes is different from the the Shift - A pulldown menu.  

## Steps to reproduce

1. Simply select the Add pulldown menu. 

## Expected result

I would expect the search function to work and the sub-categorization of nodes to be the same as the Shift - A (and the T-Panel) method.

## Actual result

Described above. The search function works fine with both the Shift - A and T-Panel method (and the categorization of the nodes are identical for both of these methods).  I recommend that this be A ) fixed if resources permitted,  or b) be disabled with a mention in the release notes that the search for nodes is accomplished by the Shift - A or T-Panel method. From a new users perspective, it would be very confusing as it stands.  
  

## Sverchok version

b28_prerelease_master, commits to 2020_01_05
Blender add-on Preference version 0.6.0.0
Tested on both Blender versions 2.81.16 and 2.82.6

Thanks you very much for all your hard work in developing this triple-mega awesomeness program.

**Comment by zeffii** [comment]
i don't disagree with this request, i've even had code that did this for maybe 3 years (but commented out because it was a bit crazy)

maybe there are new ways in 2.8, it's worth a look. @portnov suggestions?

**Comment by zeffii** [comment]
maybe we can pop the sverchok stuff from `NODE_MT_add` another way

**Comment by zeffii** [comment]
in partiucular this bit of node_items utils:

https://github.com/sobotka/blender/blob/e760972221e68d3c81f2ee3687cc71836dde8ae9/release/scripts/modules/nodeitems_utils.py#L129-L137
```python
    def draw_add_menu(self, context):
        layout = self.layout


        for cat in cat_list:
            if cat.poll(context):
                layout.menu("NODE_MT_category_%s" % cat.identifier)


    # stores: (categories list, menu draw function, submenu types)
    _node_categories[identifier] = (cat_list, draw_add_menu, menu_types)
```
can we overwrite that with `(cat_list, custom_add_menu, menu_types)`

**Comment by zeffii** [comment]
but i'm not sure if that also drops the default "Search" and "Presets" menu when Sverchok has context..

.. probably not.

**Comment by portnov** [comment]
I agree that there is a problem, but 1) it seem to have relatively low priority, and 2) it is not related to 2.80 port, the same behavior was in 2.79 version. So, I'd suggest not to rush things about this issue — we will solve it when we figure out a good solution.

**Comment by zeffii** [comment]
yes, agreed @portnov

**Comment by zeffii** [comment]
this doesn't replace the broken Search feature. 
```python
import bpy
import nodeitems_utils

NC = nodeitems_utils._node_categories
SV = NC['SVERCHOK']
SVcatlist, sv_draw, SvCats = SV
NC['SVERCHOK'] = (SVcatlist, bpy.types.NODEVIEW_MT_Dynamic_Menu.draw, SvCats)
```

I added a custom implementation of the search feature to allow more elaborate functionality..

**Comment by zeffii** [comment]
I suspect one option is to completely pop all menu items from the Sverchok/Node Editor header, and repopulate. This has downsides, it may be worth browsing through other NodeTree implementations to see if anyone else offers a nicer canonical approach.

**Comment by zeffii** [comment]
looks like Animation nodes also suffers this issue. Notice the two Search fields.
![image](https://user-images.githubusercontent.com/619340/72071499-37ea6400-32ec-11ea-9c32-a276d2742bf2.png)

**Comment by zeffii** [comment]
here's a snippet you can run from TextEditor, and it will replace that menu..

https://gist.github.com/zeffii/8fd7ff2d1bad02cd2b8b73e8f8a91773

![image](https://user-images.githubusercontent.com/619340/72075666-8439a200-32f4-11ea-9f27-281a13606431.png)

but it means replacing default code from Blender and "injecting" Sverchok specific stuff.

**Comment by zeffii** [comment]
so, if this doesn't make it into the release (as an option, or default behaviour) it's not because we don't want it.
