### ISSUE TITLE
Before Release Recommendation_2 (Naming Convention of Upcoming Release)

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2806]
## Problem statement

Before I was initiated into Github, I thought I was using Sverchok for blender 2.8 because, well, it worked for Blender 2.8 beta, then official 2.8, then 2.81 and then 2.82 alpha. I now know that I am using Add-on Version 0.6.0.0 which is a branch of the Master and that the latest release (verified) is version is 2.79 and the one before that is 0.5.9.6.4 (with a gap for 0.6.0.0). 

Solution

It looks like the name of the upcoming release might be 2.8x.  I recommend the the official name be expanded to something like **2.8x (Add-on Version 0.X.X.X)**, a number other than 0.6.0.0. In this way there will be a bright line of what was old and what is new.

**Comment by zeffii** [comment]
We put effort into keeping the barriers low for new users to get Sverchok running. After a point in time we will deprecate the current `sverchok-master`, and rename and release it with a name and description that make it clear to the reader that it is for 2.79 and that we consider it generally feature frozen (not withstanding reports of critical bugs).

from that point, our main development branch for the Blender2.8x versions will become `sverchok-master`, and we'll be following Blender API changes for 2.8+ as we have done for all Blender versions in the past. We could offer more frequent b2.8x releases if there are major API shifts, but with limited resources (and limited desire to do so) we have to acknowledge the cost-benefit of that work.

Throughout the entire development of Sverchok on Github, each change we made to sverchok represents a new snapshot of the repository at that time. Github allows you to download an archive of the repository at each commit, this is far more fine-grained than a release cycle with major and minor versions.

**Comment by zeffii** [comment]
I hope this addresses the concerns.
