### ISSUE TITLE
Nodes that use/set Collections

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2807]
One of the few remaining easy things to fix should be restoring Group support using Collections. I suspect all that is really needed for this to be useful is to always make a new collection for a node, and generate all objects inside that collection.

```python
# setup collection for node
basename = "Alpha" #  or random_available_name()
node_related_collection = bpy.data.collections.new(basename)

parent = ( current scene collection?  )
parent.children.link(node_related_collection)
```
There are two main areas of interest here

1. Object Viewers
    These use SvObjHelper directly and are straightforward upgrades
    
    - [x] BMesh https://github.com/nortikin/sverchok/pull/2810  | SvObjHelper
    - [x] PolyLine https://github.com/nortikin/sverchok/pull/2810  | SvObjHelper
    - [x] Curve https://github.com/nortikin/sverchok/pull/2810 | SvObjHelper
    - [x] Typography https://github.com/nortikin/sverchok/pull/2810 | SvObjHelper
    - [ ] SkinMesher  <-needed?  | SvObjHelper  , low priority
    - [ ] Metaball  <-needed? | SvObjHelper  , low priority

2. "Feature" Viewers
    These can be converted to use SvObjHelper, or implement their own

    - [ ] Lamp 
    - [ ] Empty
    - [x] Instancer https://github.com/nortikin/sverchok/pull/2818  grouping is now standard

**Comment by Durman** [comment]
Probably the node could have property on the N panel with name of collection where objects should be generated with default value `SV Objects` or whatever.
In this case several nodes can generate objects to one collection.

**Comment by portnov** [comment]
As far as I understand the collections are hierarchical? Then we can do always a collection under path "/Sverchok/NodeTreeName/NodeName" for each node.

**Comment by Durman** [comment]
I think a user should have control over creating of collections.

**Comment by zeffii** [comment]
- the collection can use:
   ```python
   collection_name = self.custom_collection_name or self.base_name 
   ```

i also like the nesting,
```
- Collection Sverchok
   |
   +-- Collection NodeTreeName
          | 
          +--  Collection (NodeName or collection_name)
```

**Comment by zeffii** [comment]
i've never used a separate `scene` , that would be an additional nesting.

**Comment by zeffii** [comment]
i don't feel like bumping the Object Nodes for this to a new `MK`,   but it might not be possible to introduce this without undesired effects in existing .blends that use those nodes.

i'll try to get this in before sunday

**Comment by zeffii** [comment]
OK. i'll make this optional in the N-Panel in a preliminary step, the eventually default all Objects nodes to use a Collection of their own (if there's a demand for it).

**Comment by zeffii** [comment]
closing for now, none of the remaining items are immediately useful to me
