### ISSUE TITLE
Group/collection In Viewers

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2812]
For me this works a little bit strange with blender 2.83

- Hide collection from the top is not working maybe i use it the wrong way 

![image](https://user-images.githubusercontent.com/49908008/72205860-f1ca0780-3487-11ea-9be9-9319bff712fe.png)

**Comment by zeffii** [comment]
yeah i'm not super certain how to add objects to a collection without also adding them to the main Scene collection

**Comment by zeffii** [comment]
i'll find a fix for this, all nodes that implement Group will suffer from the same issue until that's done.

I thought this was normal behaviour but obviously it isnt.

**Comment by zeffii** [comment]
it's a bit more complicated than I had hoped.

**Comment by zeffii** [comment]
there's also an error when visible is pressed twice, 
```
ERROR (bke.library): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\library.c:265 id_us_min: ID user decrement error: OBAlpha.0000 (from '[Main]'): 0 <= 0
```
it's probably something the code is doing that doesn't make sense, i'll have to check lateron.

**Comment by zeffii** [comment]
i've committed code that solves this problem. - it is in Master already. ( note that we've moved the 2.8 version to sverchok-master now)
