### ISSUE TITLE
Render Gallery 2020 #1

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2814]
Previous gallery ticket - #2666.

![adaptive_polys_12](https://user-images.githubusercontent.com/284644/72210404-a42bba00-34dc-11ea-8b24-863e7645789a.png)

**Comment by portnov** [comment]
https://www.reddit.com/r/blender/comments/enb9ai/everyones_favourite_doughnut_but_more_sverchok/

**Comment by BennyGovaerts** [comment]
![Basic_noise_options](https://user-images.githubusercontent.com/49908008/72402689-32f43d00-3750-11ea-90c6-636c79586410.jpg)

**Comment by BennyGovaerts** [comment]
![Basic_noise_options_phi](https://user-images.githubusercontent.com/49908008/72438920-2e5a7380-37a6-11ea-801c-9e218942aa6c.jpg)

**Comment by portnov** [comment]
This I decided to put into sverchok-extra repo, because that's not easy to do with plain Sverchok:
https://github.com/portnov/sverchok-extra/issues/1

**Comment by AG89z** [comment]
![render cycles](https://user-images.githubusercontent.com/26380268/72716771-15b9d700-3b73-11ea-80f2-155ca58c1344.png)
http://www.codeplastic.com/2020/01/20/parametric-wall-with-blender-and-sverchok/

**Comment by enzyme69** [comment]
<img width="765" alt="Screen Shot 2020-02-17 at 11 06 29 pm" src="https://user-images.githubusercontent.com/3952687/74652474-34df6f00-51da-11ea-91de-0fd40a199f56.png">

Shoebox / Containers. WIP.

**Comment by enzyme69** [comment]
Some kind of creature.

<img width="411" alt="Screen Shot 2020-02-22 at 11 43 13 pm" src="https://user-images.githubusercontent.com/3952687/75092599-7e123300-55cd-11ea-8e50-fe407d3f0df7.png">

**Comment by portnov** [comment]
![bend_spiral_1](https://user-images.githubusercontent.com/284644/79682717-e122ed80-823d-11ea-8e27-3ebc350fdccf.png)

**Comment by portnov** [comment]
![arc_surface_2](https://user-images.githubusercontent.com/284644/80255178-ddf08d00-8695-11ea-8cfc-b0c3763fcd31.png)
https://gist.github.com/e9f9d2a2aa11c5993fc2b6ecb43ec19e

**Comment by portnov** [comment]
![noisy_surface_3](https://user-images.githubusercontent.com/284644/81068271-8950db80-8ef9-11ea-9c30-9caf969e6d15.png)

**Comment by portnov** [comment]
![field_lines_1](https://user-images.githubusercontent.com/284644/81506672-8434c780-9311-11ea-96a0-8ae2a7a127cf.png)

**Comment by portnov** [comment]
![ring_1](https://user-images.githubusercontent.com/284644/81597771-b0b71500-93df-11ea-8491-80c0482a420e.png)

**Comment by Durman** [comment]
![building](https://user-images.githubusercontent.com/28003269/81825864-348c1100-9548-11ea-9748-02079fff4089.gif)

**Comment by enzyme69** [comment]
@Durman Durman what's your YouTube channel / blog? Someone ask on Twitter~

**Comment by Durman** [comment]
@enzyme69 https://www.youtube.com/channel/UCG0X2w4SETBI745pGK_Zccg?view_as=subscriber
There is no much there. Probably sketchfab looks a beet more interesting.
https://sketchfab.com/randum

**Comment by Durman** [comment]
![2020-05-15_18-28-30](https://user-images.githubusercontent.com/28003269/82061857-4dc4c700-96da-11ea-8c38-ef9e39fbd629.png)

**Comment by Durman** [comment]
![untitled2](https://user-images.githubusercontent.com/28003269/82126911-da49b500-97c0-11ea-9c29-c64ecfa264d8.jpg)

**Comment by enzyme69** [comment]
@Durman If you have iPhone or iPad or MacOS, I made USDZ for AR version from your Sketchfab. Cool works!

https://twitter.com/jimmygunawanapp/status/1261834152011108353?s=20

![IMG_9311](https://user-images.githubusercontent.com/3952687/82133832-c12e1c00-9833-11ea-977e-5e7b08aa826d.PNG)
![IMG_9312](https://user-images.githubusercontent.com/3952687/82133837-c8edc080-9833-11ea-8d28-9564d279a566.JPG)

[durman_building_001.usdz.zip](https://github.com/nortikin/sverchok/files/4639523/durman_building_001.usdz.zip)

**Comment by enzyme69** [comment]
<img width="868" alt="Screen Shot 2020-05-21 at 11 25 00 am" src="https://user-images.githubusercontent.com/3952687/82513250-cf42ac00-9b55-11ea-912c-b331dd507b6c.png">

<img width="1576" alt="Screen Shot 2020-05-21 at 11 26 13 am" src="https://user-images.githubusercontent.com/3952687/82513286-e2557c00-9b55-11ea-96f7-e96bffa649d1.png">

**Comment by Durman** [comment]
![town9](https://user-images.githubusercontent.com/28003269/82721308-261ec180-9ccd-11ea-8c67-72ac9806cf03.jpg)

**Comment by enzyme69** [comment]
<img width="1039" alt="Screen Shot 2020-05-24 at 11 34 55 am" src="https://user-images.githubusercontent.com/3952687/82743725-aff48a80-9db2-11ea-8a35-2f3cf7a99bda.png">

Social Distancing Sombrero Hat, 1.5 meter radius.

**Comment by nortikin** [comment]
Stair generator in sverchok.
You can generate from lines. Somehow define lines on plan and feed them to sverchok.
![Снимок экрана от 2020-05-28 21-24-40](https://user-images.githubusercontent.com/5783432/83178951-f2f38c80-a129-11ea-86d2-f4009e540dca.png)
![Снимок экрана от 2020-05-28 21-25-55](https://user-images.githubusercontent.com/5783432
![Снимок экрана от 2020-05-28 21-25-14](https://user-images.githubusercontent.com/5783432/83178948-f25af600-a129-11ea-83b9-05ccb00e12e6.png)
/83178943-f0913280-a129-11ea-85b7-7900871214d5.png)
![Снимок экрана от 2020-05-28 21-25-25](https://user-images.githubusercontent.com/5783432/83178945-f1c25f80-a129-11ea-9794-7e48a951629b.png)

**Comment by nortikin** [comment]
of course it can be extended to supports and so on

**Comment by enzyme69** [comment]
<img width="830" alt="Screen Shot 2020-05-29 at 10 59 49 am" src="https://user-images.githubusercontent.com/3952687/83209404-9b8e0480-a19b-11ea-986a-5cda409b2472.png">

Social Distancing Meditational YIN YANG Jigsaw...

**Comment by enzyme69** [comment]
Balloon Sculpture simplified...

GIST:
https://gist.github.com/a4b961ee3706c6ed27e3328b0aad0461

<img width="1015" alt="Screen Shot 2020-06-01 at 10 32 25 am" src="https://user-images.githubusercontent.com/3952687/83366550-303e6f80-a3f3-11ea-9f89-8c6ab1ec7973.png">

**Comment by enzyme69** [comment]
CRICKEY...!!! 🦗 

<img width="1310" alt="Screen Shot 2020-06-01 at 10 48 57 am" src="https://user-images.githubusercontent.com/3952687/83366983-8a403480-a3f5-11ea-82d4-20f290c9a665.png">

**Comment by enzyme69** [comment]
<img width="1184" alt="Screen Shot 2020-06-02 at 11 32 19 am" src="https://user-images.githubusercontent.com/3952687/83470135-d3ab8500-a4c4-11ea-8887-e02f2254bd2c.png">

Using Grease Pencils and SV Nodes to draw WALLS and DOORS for my simple imaginary house.

**Comment by Durman** [comment]
![tramway](https://user-images.githubusercontent.com/28003269/83859075-7a468e80-a72e-11ea-8212-cf981e566aaa.gif)

**Comment by enzyme69** [comment]
Basic Procedural Temple. It's a compilation.

<img width="1552" alt="Screen Shot 2020-06-11 at 1 36 23 pm" src="https://user-images.githubusercontent.com/3952687/84342352-b70bfd00-abe8-11ea-84eb-f048fbeb5e76.png">
<img width="1680" alt="Screen Shot 2020-06-11 at 1 35 44 pm" src="https://user-images.githubusercontent.com/3952687/84342370-bffcce80-abe8-11ea-8f4b-194e583301cb.png">
<img width="1365" alt="Screen Shot 2020-06-11 at 1 35 35 pm" src="https://user-images.githubusercontent.com/3952687/84342375-c12dfb80-abe8-11ea-86e0-f2b071dfa499.png">
<img width="1334" alt="Screen Shot 2020-06-11 at 1 35 28 pm" src="https://user-images.githubusercontent.com/3952687/84342380-c2f7bf00-abe8-11ea-8633-9a0c0a6d211a.png">
<img width="1183" alt="Screen Shot 2020-06-11 at 1 19 13 pm" src="https://user-images.githubusercontent.com/3952687/84342384-c428ec00-abe8-11ea-9896-cf605500f5fe.png">

**Comment by enzyme69** [comment]
* With dependency to Mirror Modifier.

<img width="1613" alt="Screen Shot 2020-06-15 at 11 39 27 am" src="https://user-images.githubusercontent.com/3952687/84610119-e9756d00-aefc-11ea-92d1-20e8c0ca0419.png">

**Comment by enzyme69** [comment]
<img width="1279" alt="Screen Shot 2020-06-15 at 12 15 31 pm" src="https://user-images.githubusercontent.com/3952687/84611700-f47ecc00-af01-11ea-909a-7efc00b564a8.png">

Crickey Monkey Mecha Warriors.

**Comment by enzyme69** [comment]
<img width="803" alt="Screen Shot 2020-06-19 at 12 36 17 pm" src="https://user-images.githubusercontent.com/3952687/85090899-9582c500-b229-11ea-8bd4-8583efa3d1a0.png">

WFC Low Poly city using WFC texture node.

If you have node tree that can turn basic shapes into tower or building, then this will look awesome...

**Comment by enzyme69** [comment]
CRICKET METAL: (loud and noisy)
<img width="552" alt="Screen Shot 2020-06-22 at 5 43 13 pm" src="https://user-images.githubusercontent.com/3952687/85261711-e99edb00-b4af-11ea-81ce-297119170de0.png">
https://youtu.be/BqydwYLJ6v0

**Comment by ricardomatias** [comment]
![torus-twist_01](https://user-images.githubusercontent.com/8850708/85410087-ef0b2c80-b566-11ea-9925-87eaad5dd217.png)

Slowly getting acquainted with Sverchok :)

**Comment by nortikin** [comment]
Mcubes + Sfields + evaluate sfield to color
![Снимок экрана от 2020-06-24 21-41-22](https://user-images.githubusercontent.com/5783432/85614892-198edf80-b664-11ea-9822-bd5426858d31.png)

**Comment by enzyme69** [comment]
<img width="1162" alt="Screen Shot 2020-07-05 at 11 34 36 am" src="https://user-images.githubusercontent.com/3952687/86523717-97988500-beb3-11ea-8d04-b36f8f6e1ebd.png">

**Comment by enzyme69** [comment]
<img width="703" alt="Screen Shot 2020-07-16 at 3 03 36 pm" src="https://user-images.githubusercontent.com/3952687/87666637-4d18e180-c7ac-11ea-910a-4e284745389a.png">


<img width="785" alt="Screen Shot 2020-07-16 at 9 34 10 pm" src="https://user-images.githubusercontent.com/3952687/87666645-530ec280-c7ac-11ea-861e-f6df29f3a7e5.png">

**Comment by enzyme69** [comment]
<img width="898" alt="Screen Shot 2020-07-18 at 8 56 16 am" src="https://user-images.githubusercontent.com/3952687/87836799-a3813f80-c8d4-11ea-9a8b-3b6d67ee613a.png">

Moai and Singularity

**Comment by nortikin** [comment]
![Parametric Skyscraper](https://user-images.githubusercontent.com/5783432/88434164-46234c00-ce08-11ea-8d7f-7d086c22de2f.png)

**Comment by portnov** [comment]
![Screenshot_20200816_222405](https://user-images.githubusercontent.com/284644/90340159-8fce1380-e00f-11ea-8e71-7e46f6a8cd81.png)
![Screenshot_20200816_222713](https://user-images.githubusercontent.com/284644/90340170-a7a59780-e00f-11ea-9c5d-a8011bd39d4e.png)

**Comment by portnov** [comment]
One of the simplest things that can be done with curves & surfaces...
![Screenshot_20200828_194428](https://user-images.githubusercontent.com/284644/91580699-e79d4080-e966-11ea-9519-06f961352cef.png)

[coons_test_2_2020_08_28_14_43.zip](https://github.com/nortikin/sverchok/files/5142680/coons_test_2_2020_08_28_14_43.zip)

**Comment by portnov** [comment]
![nurbs_1](https://user-images.githubusercontent.com/284644/91760474-dd8c7380-ebec-11ea-9764-6788f7092db5.png)
![nurbs_2](https://user-images.githubusercontent.com/284644/91760477-e0876400-ebec-11ea-91e7-1cb73d1a4606.png)

**Comment by enzyme69** [comment]
Nortikin can probably make SVerchok Reel month by month basis.

**Comment by nortikin** [comment]
> Nortikin can probably make SVerchok Reel month by month basis.

Long time we need new observation video. The question is spectacularity. How to make it pleasure to see and united in narrative at the time?
Mostly works are static and not represent full process's pipeline.

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/92271302-38c1ad00-eef0-11ea-9fb9-d2265163949f.png)
Супер-семки
Super-semki

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/92765588-289d4800-f39e-11ea-8ab4-c3f72d673bbb.png)
![image](https://user-images.githubusercontent.com/5783432/92765688-3d79db80-f39e-11ea-9f7b-f91b6eb6d8ca.png)

https://gist.github.com/8697eb921bf4afe4c732f5ab1fa46f37

**Comment by enzyme69** [comment]
Grease Pencil -> Sverchok -> Sandals

![IMG_0850](https://user-images.githubusercontent.com/3952687/93160428-a329e700-f753-11ea-9a34-5f40b43d220f.JPG)

**Comment by nortikin** [comment]
![pulga+svg](https://user-images.githubusercontent.com/5783432/93361549-a7d2c600-f84d-11ea-8546-51397d32aa2e.png)
![pulga+svg2](https://user-images.githubusercontent.com/5783432/93361552-a903f300-f84d-11ea-8abb-84fa6de2efff.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/93403125-4af7ff80-f88f-11ea-9d86-7af39d029d84.png)
![изображение](https://user-images.githubusercontent.com/5783432/93403148-59461b80-f88f-11ea-8acd-34f052cb5cfc.png)
![изображение](https://user-images.githubusercontent.com/5783432/93403154-5f3bfc80-f88f-11ea-923e-7e259fef86a6.png)
Хорошая новость.
Подготовил для вас файл для экспорта чертежей из Сверчка в SVG формат. Здесь по умолчанию штамп по ГОСТ Р 21. Формат пока что только А4, но это исправимо вполне.
Благодаря некоторым комитам последним, у нас полетел экспорт в гист, потому выкладываю здесь файл бленд, когда исправят сделаем шаблон в примерах.

П.С. добавил визуализацию метода проецирования на плоскость, чтобы более-менее было понятно как строится перспектива, конечно данный метод должен быть заменён на использоание камеры в сцене.

**Comment by Durman** [comment]
> Благодаря некоторым комитам последним, у нас полетел экспорт в гист,

Не стоит благодарности. Обращайтесь если что.

**Comment by nortikin** [comment]
> > Благодаря некоторым комитам последним, у нас полетел экспорт в гист,
> 
> Не стоит благодарности. Обращайтесь если что.

не уверен что твои изменения, мало ли чьи, я вообще без намёка, последние имел в виду за месяц, я мог не пользоваться некоторыми узлами до сих пор

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/93689862-550e3e00-fadb-11ea-824a-230e993a1906.png)
![изображение](https://user-images.githubusercontent.com/5783432/93689870-63f4f080-fadb-11ea-8cc3-a2548d252a8d.png)
![изображение](https://user-images.githubusercontent.com/5783432/93689874-6bb49500-fadb-11ea-8def-c6b602f41e9f.png)
![изображение](https://user-images.githubusercontent.com/5783432/93689876-73743980-fadb-11ea-98c9-09ea076e9a58.png)

**Comment by onerawartist** [comment]
@AG89z i was kinda going for the same result, i did the slicing with an array of a boolean lol , took a shortcut hhhhhh 
![post (1 of 1)](https://user-images.githubusercontent.com/71472224/93727659-ff599480-fbb3-11ea-9386-4913e166729b.jpg)

**Comment by portnov** [comment]
![Screenshot_20200923_021903](https://user-images.githubusercontent.com/284644/93939076-af113c80-fd43-11ea-840c-552c99f414cd.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/94706844-619c5d00-034b-11eb-9c5e-846bd38a329d.png)

**Comment by onerawartist** [comment]
![post (1 of 1)](https://user-images.githubusercontent.com/71472224/94976939-8260e000-050e-11eb-97ce-09711561eeda.jpg)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/95029323-0900f300-06b0-11eb-99a8-d94fa920d41e.png)

**Comment by enzyme69** [comment]
<img width="793" alt="Screen Shot 2020-10-05 at 4 04 05 pm" src="https://user-images.githubusercontent.com/3952687/95042634-4011eb80-0726-11eb-8bd4-2ed4382cce99.png">

Under ten nodes challenge. It's Human 2020.

**Comment by nortikin** [comment]
https://pasteall.org/pic/1fa19462d4564c0fb28432bf874059f2
![0155](https://user-images.githubusercontent.com/5783432/95775302-d3b95e00-0cca-11eb-8cf4-7855dac8d014.png)
![0024](https://user-images.githubusercontent.com/5783432/95775303-d4ea8b00-0cca-11eb-8520-55d2803a11ba.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/99152337-3b8c0b80-26b2-11eb-854f-b45c5217de5f.png)
![изображение](https://user-images.githubusercontent.com/5783432/99152349-45157380-26b2-11eb-8bfc-e3ced3c50c2f.png)
![изображение](https://user-images.githubusercontent.com/5783432/99152355-51013580-26b2-11eb-995b-59979bf3683e.png)

**Comment by Ahr0n** [comment]
![369_The_Armchair_G](https://user-images.githubusercontent.com/45789626/99911136-9d6ff500-2cf2-11eb-9470-fb73ce767fcf.png)
![369_The_Armchair_H](https://user-images.githubusercontent.com/45789626/99911139-a06ae580-2cf2-11eb-86b2-535c12d11174.png)


My latest project where Sverchok and Houdini were involved for cloth simulations. Full project on Behance: https://www.behance.net/gallery/108131517/369-Armchair

**Comment by enzyme69** [comment]
<img width="1216" alt="Screen Shot 2020-11-25 at 2 28 48 pm" src="https://user-images.githubusercontent.com/3952687/100179685-a0edc100-2f2a-11eb-9c94-2aac83bff807.png">

Nikitron's Queens Gambit

**Comment by nortikin** [comment]
> <img alt="Screen Shot 2020-11-25 at 2 28 48 pm" width="1216" src="https://user-images.githubusercontent.com/3952687/100179685-a0edc100-2f2a-11eb-9c94-2aac83bff807.png">
> 
> Nikitron's Queens Gambit

god save the queen

**Comment by onerawartist** [comment]
![one-raw-artist-post-1-of-1 (2).jpg](https://user-images.githubusercontent.com/71472224/100307661-b4d70880-2fa6-11eb-98a7-5a8ff5e06edc.jpg)

**Comment by nortikin** [comment]
Suppose to make observation of my nodevember' sverchok' trees and publish them on december

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/100485814-9726b200-3112-11eb-9ab2-e9120ac7734a.png)
![изображение](https://user-images.githubusercontent.com/5783432/100485820-9aba3900-3112-11eb-9075-430e6ad6e027.png)
![изображение](https://user-images.githubusercontent.com/5783432/100485823-9db52980-3112-11eb-9fd2-a268749ca014.png)
![изображение](https://user-images.githubusercontent.com/5783432/100485830-a1e14700-3112-11eb-9c12-76fdaaeef670.png)
![изображение](https://user-images.githubusercontent.com/5783432/100485832-a443a100-3112-11eb-90f9-8550c171c535.png)

**Comment by Durman** [comment]
![2020-12-25_14-21-04](https://user-images.githubusercontent.com/28003269/103132044-a7539200-46bc-11eb-9dc5-fe35abc046b5.png)

**Comment by portnov** [comment]
Continued in #3817.
