### ISSUE TITLE
Suggestion : Dupli instancer mk4-instancing extra options 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2819]
Extra options for the N- panel:
 - disable/enable:  display instancer & render instancer 
 - Scale factor 

is there maybe a solution so that you can use different instancer objects:
![image](https://user-images.githubusercontent.com/49908008/72261014-4dc19700-3614-11ea-9131-d0ad2b83044f.png)

**Comment by zeffii** [comment]
sure, can you link that blend so all i have to do is load it, and update the code

**Comment by BennyGovaerts** [comment]
Test file : blender 2.82.6
[Basic dual_mesh_instance_duplifaces.zip](https://github.com/nortikin/sverchok/files/4054104/Basic.dual_mesh_instance_duplifaces.zip)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/72268264-cb3fd400-3621-11ea-8918-c979ad27ab9e.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2820

try it, report back

**Comment by zeffii** [comment]
i've only enabled this for the FACE instancing,  if it makes sense to enable more features be explicit :)

**Comment by BennyGovaerts** [comment]
Excellent , thanks

**Comment by BennyGovaerts** [comment]
With dupliverts you can use this setup and works fine with the new options 👍 
![image](https://user-images.githubusercontent.com/49908008/72272529-127d9300-3629-11ea-936a-c6e34a50b992.png)
