### ISSUE TITLE
Polyline viewer collection not updating realtime 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2822]
Polyline Viewer collection Works fine but not if you change some value after group/collection 

For example if you change number off verts/points from the matrix to a lower value
![image](https://user-images.githubusercontent.com/49908008/72298471-77071500-365e-11ea-8a67-b981173183be.png)
![image](https://user-images.githubusercontent.com/49908008/72298556-b170b200-365e-11ea-97ea-d15c74011384.png)

Basic test file with blender 2.83
[Polyline_collections.zip](https://github.com/nortikin/sverchok/files/4056324/Polyline_collections.zip)

**Comment by zeffii** [comment]
excellent, i'll have to dig a little deeper. Thanks for testing.

**Comment by zeffii** [comment]
what's happening is the following

1. in group mode
2. when the matrix count is lower than the previous matrix count, then the excess objects are not removed

**Comment by zeffii** [comment]
when you go out of group mode, then the excess objects are removed properly after an update

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2823 resolves this, and has shown me that the next step is a much nicer/cleaner/easier solution. So for now the solution is dirty "under the hood", but should work

**Comment by BennyGovaerts** [comment]
Works fine ,except if you change the name off the collection  after grouping/collection , but is not importent for me at the moment

**Comment by zeffii** [comment]
name change is not supported. at all.

**Comment by zeffii** [comment]
i have been thinking about that too. I don't think it's a hugely complicated problem to solve, but it may be better to implement it as an Operator first (rather than letting the user edit the String Textbox ..at least initially)

- solve problem first
- then give it the most convenient user UI
