### ISSUE TITLE
Lamp Node: Changing Matrix Count Does Not Remove Excess Objects

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2824]
## Problem statement
Excess lamps are are not removed when changing the matrix count using a Line node connected to a Lamp node.  The seems directly related to issues #2822 that was resolved by #2823. I created a separate thread because of the different set up with the Lamp node.  

## Steps to reproduce
A. Number of verts, 2
B. Number of verts from 2 to 3
C. Number of verts from 3 back to 2 (notice also the offset of the middle lamp)
![a](https://user-images.githubusercontent.com/59537375/72370841-ed843100-36b7-11ea-92c5-8fa7cc2a37d3.PNG)
![b](https://user-images.githubusercontent.com/59537375/72371040-5c618a00-36b8-11ea-8cd2-1abedfd000b2.PNG)
![c](https://user-images.githubusercontent.com/59537375/72372443-2a055c00-36bb-11ea-8621-d63e23516ed3.PNG)

## Expected result

The number of lamps to update as the the number of verts change (and without an offset). 

## Actual result
See above.

## Sverchok version
Master, post commit caec24f

**Comment by zeffii** [comment]
Thanks for reporting this,

**Comment by zeffii** [comment]
i vote to stick lamps into a collection by default.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2828
 resolved the above issue

warning, this is not an extensive overhaul of this node.

**Comment by OiledEluer** [comment]
Now works fine, thanks.
