### ISSUE TITLE
Number Range Node (float/range): Gives Unexpected Result when using Zero as a Start Value

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2827]
## Problem statement

The Number Range node (with float/range settings) set to a start value of zero places vertices zero and one in the same place effectively collapsing both vertices into a vertex at the origin. 
I didn't have the issue if the start value was set to a non-zero number or if the integer setting was used instead of float.
## Steps to reproduce
Case A: start value  = zero
Case B: start value  = one 
![Number Range_start at 0](https://user-images.githubusercontent.com/59537375/72378278-e9f7a680-36c5-11ea-8c85-aeb37e3a83ec.PNG)

## Expected result
The same as in case B.

## Actual result

See above.

## Sverchok version

Master, post commit caec24f

**Comment by zeffii** [comment]
@vicdoval  maybe you can look at this before i do :)

**Comment by vicdoval** [comment]
The Line step input will determine the distance between de vertices, so if you input a 0 in the first place the step between the first two points will be 0
![image](https://user-images.githubusercontent.com/10011941/72385238-4fc44c80-371f-11ea-8054-d4e51080f460.png)

**Comment by zeffii** [comment]
@OiledEluer  hope that clarifies the behaviour..

**Comment by OiledEluer** [comment]
Yes, I see now what is going on.  Thanks both.
