### ISSUE TITLE
Question ; Select faces by sides 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2829]
Is there maybe a  node : Select faces by sides :
![image](https://user-images.githubusercontent.com/49908008/72384983-d298d780-371e-11ea-9952-e80fef4fd475.png)

**Comment by vicdoval** [comment]
I think this is the fastest path, also the `select similar` node could be used but you need to create the mask first ![image](https://user-images.githubusercontent.com/10011941/72385862-a0887500-3720-11ea-89e2-dbfd41842f85.png)

**Comment by zeffii** [comment]
previously in 2.79 bmesh.ops exposed these operations, they are no longer part of bmesh, 
```
      - bmesh.ops.similar_verts (missing! )
      - bmesh.ops.similar_edges (missing! )
      - bmesh.ops.similar_faces (missing! )
```
at least.. when i last looked. Didn't you make analogues @portnov  ?

**Comment by BennyGovaerts** [comment]
> I think this is the fastest path, also the `select similar` node could be used but you need to create the mask first ![image](https://user-images.githubusercontent.com/10011941/72385862-a0887500-3720-11ea-89e2-dbfd41842f85.png)

Excellent where can i find this node CA ......

**Comment by portnov** [comment]
Try "components analyzer" (it has "number of face sides mode, I believe) + "logic operations" (== 4).

**Comment by portnov** [comment]
@zeffii I remember someone rewriting that node to work without the bmesh operation that is gone...

**Comment by vicdoval** [comment]
@zeffii  I re-wrote it on #2643 
@BennyGovaerts  CA is Component Analyzer you can find it in the Analyzers section and on sverchok right click menu

**Comment by zeffii** [comment]
nice one @vicdoval  :)

**Comment by BennyGovaerts** [comment]
Excellent , thanks for the support
