### ISSUE TITLE
Get/Set Property Node: attr not listed in types dict

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2830]
## Problem statement

I am trying to pull the the position of a color stop from a color ramp in Blender using the Get Property node.  I don't get the red error message in the node (as my fat fingers caused a few times) but there are no dynamic sockets exposed as would be expected.

## Steps to reproduce
Case A: success getting the position of the cube
Case B: no dynamic socket for color stop position
![Get property](https://user-images.githubusercontent.com/59537375/72386829-fdf7d400-36d6-11ea-8be0-df600f07bbdc.PNG)

## Expected result

Same as Case A, a dynamic socket exposed.

## Actual result

see above

## Sverchok version

Master, post caec24 commit

**Comment by zeffii** [comment]
any chance you could link a .blend  or copy/paste the datapath you are trying to paste into the Get/Set node ?

**Comment by zeffii** [comment]
it's been a long time since i've looked at the internals of that node closely.  This will be interesting

**Comment by zeffii** [comment]
OK, this node is not yet configured to use `SvColorSocket` (this is another thing to improve)

**Comment by zeffii** [comment]
the error from the commandline/prompt suggests a path issue during parsing of that string..
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\object_nodes\getsetprop.py", line 209, in verify_prop
    obj = self.obj
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\object_nodes\getsetprop.py", line 203, in obj
    ast_path = ast.parse(eval_str)
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.82\python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    bpy.data.materials['Material'].
                                  ^
```
at least there's an error, that's a good start.

**Comment by zeffii** [comment]
i'll have a closer look tomorrow.

**Comment by zeffii** [comment]
a few notes to self

- add `self.sv_throttle_tree_update` during the set / get part to avoid redundant recalcs
- use correct Color/Euler/Quat sockets

**Comment by zeffii** [comment]
don't use this :)  
![image](https://user-images.githubusercontent.com/619340/72390671-94ee7b80-372b-11ea-970a-40f1a9e62abe.png)

**Comment by zeffii** [comment]
@OiledEluer   in order to provide the simplest user-interface on that node, the implementation code is a bit "fuzzy".  You can set the color components individually like this
```
mats["Material"].node_tree.nodes["ColorRamp"].color_ramp.elements[0].color[0]   # red
mats["Material"].node_tree.nodes["ColorRamp"].color_ramp.elements[0].color[1]   # green
mats["Material"].node_tree.nodes["ColorRamp"].color_ramp.elements[0].color[2]   # blue
```
for now..

internally i suspect this is not what our code-test exoects
```
>>> type(bpy.data.materials['Material'].node_tree.nodes['ColorRamp'].color_ramp.elements[0].color)
<class 'bpy_prop_array'>
```

**Comment by zeffii** [comment]
i think we can test this without major issues
```
if isinstance(item, bpy.types.bpy_prop_array):
    if hasattr(item, "path_from_id") and item.path_from_id().endswith('color'):
        if len(item) == 4:
            socket in alpha mode
        else:
           socket in 3 component mode
```

**Comment by zeffii** [comment]
there's a lot that we can do to this node, for now the most useful modification lets you at least control properties that are called "color"

**Comment by zeffii** [comment]
i've resolved the issue you touch on. Thanks for reporting it.

see my notes on [the PullRequest](https://github.com/nortikin/sverchok/pull/2831) (at the end) regarding what other issues you might experience.

i'm happy to return to this node if there are other issues/

**Comment by zeffii** [comment]
btw here as some aliases
```python
aliases = {
    "c": "bpy.context",
    "C": "bpy.context",
    "scene": "bpy.context.scene",
    "data": "bpy.data",
    "D": "bpy.data",
    "objs": "bpy.data.objects",
    "mats": "bpy.data.materials",
    "M": "bpy.data.materials",
    "meshes": "bpy.data.meshes",
    "texts": "bpy.data.texts"
}
```
you can do
```python
M["Material"].node_tree.nodes["ColorRamp"].color_ramp.elements[0].color
```

**Comment by OiledEluer** [comment]
thanks
