### ISSUE TITLE
Output NumPy Parameter: Some Undertanding Needed

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2834]
## Problem statement

I see there are NumPy output parameters in the Number Range and Map Range nodes (and maybe others?) that gives arrays instead of lists, and that if invoked should make the node run faster.  I don't have an understanding of why one would not want to have this parameter invoked all the time unless the NumPy library is not installed and would cause a conflict.  Will only certain nodes take the NumPy output as an input?

**Comment by zeffii** [comment]
> Will only certain nodes take the NumPy output as an input?

essentially yes, if all nodes supported NumPy data we would not need a switch.

That raises the real question: 

> "Well, then why aren't all nodes implemented in NumPy? "

We could convert more nodes to use NumPy but not all nodes will be trivial rewrites. sometimes a Node will implement an algorithm that is hard to convert to numpy, ( i will spare you the details.. and spare myself too )

it's also a manpower and focus thing

**Comment by OiledEluer** [comment]
Ok, thanks.  I will let the speed demons other than me pester you in the future ;)
