### ISSUE TITLE
Sverchok-Extra addon

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#2837]
We talked about this several times, and I finally started it.

There is an addon: https://github.com/portnov/sverchok-extra (I think I will move the repo under Sverchok organization later).

It provides several nodes that can work only with specific libraries installed into Blender's python ecosystem. 

**NOTE**: Sverchok-Extra is currently in early development stage; there are
many things that can change in future. So, please do not depend on this addon
in your production projects yet. But you can already test it and play with it.

At the moment, this addon includes the following nodes for Sverchok:

At the moment, this addon includes the following nodes for Sverchok:

* *Curve* category:
  * Minimal (interpolation) Curve (uses [SciPy][4])
  * Catenary Curve (uses [SciPy][4])
  * NURBS Curve (uses [Geomdl][3] library)
  * NURBS Interpolation Curve (uses Geomdl library)
  * NURBS Approximation Curve (uses Geomdl library)
  * Circlify (pack a set of circles into another circle) (uses [Circlify][15] library)
  * Blend Curves (by BSpline curve, uses [Geomdl][3] library)
  * Marching Squares (uses [Scikit-Image][5] library)
  * Intersect Surface with Plane (uses [SciPy][4])
  * Orthogonal Projection onto Curve (uses [SciPy][4])
  * Nearest Point on Curve (usess [SciPy][4])
* *Surface* category:
  * Smooth Bivariate Spline (uses [SciPy][4])
  * NURBS Surface (uses Geomdl)
  * NURBS Interpolation Surface (uses Geomdl)
  * NURBS Approximation Surface (uses Geomdl)
  * Quads to NURBS (uses Geomdl)
  * Minimal Surface (uses SciPy)
  * Minimal Surface from (closed) Curve (uses SciPy)
  * Curves to Surface (optionally uses SciPy and/or Geomdl)
  * Marching Cubes (optionally uses either [PyMCubes][8] or [Scikit-Image][5]; has slower implementation in pure Python)
  * Nearest Point on Surface (uses SciPy)
  * Raycast onto Surface (uses SciPy)
  * Raycast onto Implicit Surface (scalar field iso-surface) (uses SciPy)
  * Orthogonal Projection onto Surface (uses SciPy)
  * Implicit Surface Solver / Wrap (no dependencies, experimental node)
* *Spatial* category:
  * Voronoi 3D (uses SciPy)
  * Spherical Voronoi (uses SciPy)
  * Delaunay 3D (uses SciPy)
* *Field* category (please refer to the [wiki page][11] about used concept of the field; most of these nodes do not use external libraries, except for numpy):
  * Mesh Nearest Normals Field (optionally uses SciPy)
  * Minimal Scalar Field (uses SciPy)
  * Minimal Vector Field (uses SciPy)
  * Scalar Field Graph (uses [Scikit-Image][5])
* *Exchange* category:
  * NURBS In (input Blender's NURBS curve or surface objects into Sverchok tree)
  * NURBS to JSON (uses Geomdl to represent NURBS surfaces or curves in JSON format which can be converted to Rhino's `3dm` by [rw3dm][12]
  * JSON to NURBS (uses Geomdl to read NURBS surfaces or curves from the same JSON format)

Later, there will be more features. Also, later there can appear some kind of "booster" library, written specifically for Sverchok in C or C++, which we could use to improve performance of nodes that Sverchok already has.

Sverchok-Extra uses some extensions of Sverchok's API (#2836) to register it's nodes in Sverchok's menus and panels.

I think, the policy should be: if we want some feature in Sverchok, that requires user to compile or install anything, that should go into Sverchok-Extra. If someone wants some feature working in Sverchok, but most of the contributors think Sverchok would not benefit of it, then a separate addon should be created.

@zeffii @Durman @vicdoval @nortikin any thoughts on this?

**Comment by portnov** [comment]
For example, "Voronoi 3D" (in combination with "Cut object by surface") node allows one to make "almost honest" Voronoi pattern on almost any surface:

![Screenshot_20200115_195339](https://user-images.githubusercontent.com/284644/72461874-adc16480-37f1-11ea-841a-478d4febd4a0.png)

The surface from gallery

![adaptive_polys_12](https://user-images.githubusercontent.com/284644/72210404-a42bba00-34dc-11ea-8b24-863e7645789a.png)

is made by "minimal surface" node.

**Comment by zeffii** [comment]
i like it, it's fitting that we offer an ecosystem which allows advanced features to be added to Sverchok. Unfortunately my time is limited for participation (maybe that's a good thing! heheh..)

**Comment by nortikin** [comment]
it is dream.
remember SNL was full of such things. Now it becomes an easy-to-go for extra-users.

**Comment by portnov** [comment]
@nortikin not that easy-to-go, unfortunately: it requires non-trivial installation of dependencies (see sverchok-extra's readme). But yes, Sverchok-Extra expands Sverchok's possibilities a lot. See https://github.com/portnov/sverchok-extra/issues/1 for examples.

**Comment by portnov** [comment]
I've updated the description - there is already much more nodes :)

**Comment by portnov** [comment]
Although I've started Sverchok-Extra to contain only things that couldn't be integrated into main Sverchok repo due to dependencies, at the moment it evolved, and currently there are some interesting enough (imho) things in it that do not have external dependencies.

The following things do not require external dependencies:

* Abstract classes for Curve, Surface, Scalar Field and Vector Field (not usable by user by themselves, but their descendants are)
* Curves:
** Straight line / segment
** Circle curve
** Formula-defined curve
** Interpolation linear / cubic curve
** Cast Curve
** Curve on Surface
** Curve Lerp
** Concatenate Curves
** Apply Vector Field to Curve
** Curve Domain
** Curve Length
** Curve Length Parameter
** Curve Curvature
** Curve Torsion
** Curve Frame
** Curve Zero-Twist Frame
** Evaluate Curve
* Surfaces:
** Plane surface
** Sphere Surface
** Formula-defined Surface
** Surface of revolution
** Extrude curve along Vector
** Extrude curve along curve
** Linear / ruled surface
** Apply Vector Field to Surface
** Evaluate Surface
* Spatial:
** Scalar Field Random Probe
* Fields:
** Formula-generated Scalar Field
** Formula-generated Vector Field
** Decompose Vector Field
** Compose Vector Field
** Scalar field of a point
** Attractor Field
** Image Field
** Merge Scalar Fields
** Voronoi 3D Scalar / Vector Field
** Bending field to bend along Surface
** Bending field to bend along Curve
** Noise Vector Field
* Scalar Field Math
** Vector Field Math
** Field differential operators
** Apply Vector Field
** Evaluate Vector Field
** Evaluate Scalar Field
** Vector Field Graph
** Vector Field Lines
** Scalar Field Graph

This is quite a number of nodes, as you can see. These can be potentially moved from Sverchok-Extra to Sverchok. They do not have documentation at the moment, and most of icons are missing, and some refactoring will be required, so that's not a quick thing to do, but possible.

So, people. Should we move these nodes?

**Comment by zeffii** [comment]
scary : )   no objections.

**Comment by portnov** [comment]
@zeffii  at the moment you can just install Sverchok-Extra without installing any dependencies to play and see what and how usable there is.

**Comment by nortikin** [comment]
i lovely use them. Need examples to include.

**Comment by portnov** [comment]
@nortikin there are some additional examples in #2993.

**Comment by fewerjunk** [comment]
I've looked at this.  Specifically:

"For example, "Voronoi 3D" (in combination with "Cut object by surface") node allows one to make "almost honest" Voronoi pattern on almost any surface:"

I've used the SNlite Voronoi 3D script, Scene - Object in and a Torus Mesh.  I've added "Dual Mesh" node as well as "Cut by Surface" and I keep getting errors.  Meaning I've likely missed something.  I look at the examples talked about in this thread.  None of them seem to be pointing at the recently added FreeCAD nodes which aren't working on my system: Mac - As best I can tell, everything else is.

Attached is my nodes (JSON).

(I don't see "cut object by surface" - maybe that's the problem?)

My Nodes:

{
  "export_version": "0.10",
  "framed_nodes": {},
  "groups": {},
  "nodes": {
    "Cut by Surface": {
      "bl_idname": "SvCutObjBySurfaceNode",
      "color": [
        1.0,
        0.30000001192092896,
        0.0
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        162.93313598632812,
        -217.59762573242188
      ],
      "params": {},
      "use_custom_color": true,
      "width": 140.0
    },
    "Dual Mesh": {
      "bl_idname": "SvDualMeshNode",
      "color": [
        1.0,
        0.30000001192092896,
        0.0
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        401.3824768066406,
        -261.5870361328125
      ],
      "params": {},
      "use_custom_color": true,
      "width": 140.0
    },
    "Objects in": {
      "bl_idname": "SvObjectsNodeMK3",
      "color": [
        0.0,
        0.5,
        0.20000000298023224
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -282.90283203125,
        -240.19168090820312
      ],
      "object_names": [
        "Torus"
      ],
      "params": {},
      "use_custom_color": true,
      "width": 140.0
    },
    "Random Vector": {
      "bl_idname": "RandomVectorNodeMK3",
      "color": [
        0.0,
        0.5,
        0.5
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -264.49468994140625,
        -80.84405517578125
      ],
      "params": {
        "count_inner": 215,
        "scale": 2.0899999141693115,
        "seed": 76
      },
      "use_custom_color": true,
      "width": 140.0
    },
    "Scripted Node Lite": {
      "bl_idname": "SvScriptNodeLite",
      "color": [
        0.0,
        0.800000011920929,
        0.949999988079071
      ],
      "custom_socket_props": {
        "3": {
          "default_float_property": 4.380000114440918
        },
        "4": {
          "default_int_property": 47,
          "default_property_type": "int"
        }
      },
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        -52.31262969970703,
        -208.7801971435547
      ],
      "params": {
        "n_id": "-7674122414845683313",
        "script_name": "voronoi_3d.py",
        "script_str": "\"\"\"\nin verts_in v d=[] n=1\nin obj_verts_in v d=[] n=1\nin obj_faces_in s d=[] n=1\nin shrink s d=0.9 n=2\nin bounding_n s d=14 n=2\nout new_verts v\nout new_faces s\n\"\"\"\nfrom itertools import combinations\nimport bmesh\nimport mathutils\nfrom mathutils import Vector\nfrom collections import defaultdict\n\n# from sverchok.utils.sv_bmesh_utils import bmesh_join\nfrom sverchok.utils.sv_mesh_utils import mesh_join\n\nlocators = defaultdict(list)\n\nsize = len(verts_in)\nkd = mathutils.kdtree.KDTree(size)\nfor i, xyz in enumerate(verts_in):\n    kd.insert(xyz, i)\nkd.balance()\n\nfor idx, vtx in enumerate(verts_in):\n    n_list = kd.find_n(vtx, bounding_n)\n    for co, index, dist in n_list:\n        if index == idx:\n            continue\n        pt = (((Vector(co)-Vector(vtx))/2)*shrink) + Vector(vtx)   #((.... ) * distor) + Vector(vtx)\n        normal = Vector(co)-Vector(vtx)\n        locators[idx].append((pt, normal))\n\n__new_verts = []\n__new_faces = []\nfor k, v in locators.items():\n\n    working_geom = bmesh_from_pydata(obj_verts_in, [], obj_faces_in, normal_update=True)\n    for pt, normal in v:\n        geom_in = working_geom.verts[:] + working_geom.edges[:] + working_geom.faces[:]\n\n        res = bmesh.ops.bisect_plane(\n            working_geom, geom=geom_in, dist=0.00001,\n            plane_co=pt, plane_no=normal, use_snap_center=False,\n            clear_outer=True, clear_inner=False\n        )\n\n        surround = [e for e in res['geom_cut'] if isinstance(e, bmesh.types.BMEdge)]\n        fres = bmesh.ops.edgenet_prepare(working_geom, edges=surround)\n        bmesh.ops.edgeloop_fill(working_geom, edges=fres['edges'])  \n\n    ___v, _, ___f = pydata_from_bmesh(working_geom)\n    __new_verts.append(___v)\n    __new_faces.append(___f)\n\n_v, _e, _f = mesh_join(__new_verts, [], __new_faces)\n\nnew_verts.append(_v)\nnew_faces.append(_f)\n"
      },
      "use_custom_color": true,
      "width": 140.0
    },
    "Viewer Draw Mk3": {
      "bl_idname": "SvVDExperimental",
      "color": [
        1.0,
        0.5889999866485596,
        0.21400000154972076
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        634.7255249023438,
        -227.1575164794922
      ],
      "params": {
        "activate": false
      },
      "use_custom_color": true,
      "width": 140.0
    },
    "Viewer Draw Mk3.001": {
      "bl_idname": "SvVDExperimental",
      "color": [
        1.0,
        0.5889999866485596,
        0.21400000154972076
      ],
      "custom_socket_props": {},
      "height": 100.0,
      "hide": false,
      "label": "",
      "location": [
        365.18914794921875,
        30.84620475769043
      ],
      "params": {
        "activate": false
      },
      "use_custom_color": true,
      "width": 140.0
    }
  },
  "update_lists": [
    [
      "Random Vector",
      0,
      "Scripted Node Lite",
      0
    ],
    [
      "Objects in",
      0,
      "Scripted Node Lite",
      1
    ],
    [
      "Objects in",
      2,
      "Scripted Node Lite",
      2
    ],
    [
      "Random Vector",
      0,
      "Viewer Draw Mk3.001",
      0
    ],
    [
      "Cut by Surface",
      0,
      "Dual Mesh",
      0
    ],
    [
      "Cut by Surface",
      2,
      "Dual Mesh",
      2
    ],
    [
      "Scripted Node Lite",
      0,
      "Cut by Surface",
      0
    ],
    [
      "Scripted Node Lite",
      1,
      "Cut by Surface",
      2
    ],
    [
      "Dual Mesh",
      0,
      "Viewer Draw Mk3",
      0
    ],
    [
      "Dual Mesh",
      1,
      "Viewer Draw Mk3",
      2
    ]
  ]
}

**Comment by fewerjunk** [comment]
Might've solved it.  I used: 

Voronoi Scipy 3D instead.

**Comment by fewerjunk** [comment]
Nope.  Still broke.

**Comment by fewerjunk** [comment]
Tried using Tissue (Dual Mesh) to eliminate the Dual Mesh Node (which doesn't seem to behave the same way anyways) just to see if that helped.

Nope.

![248705C0-2801-4DD5-B551-92CC648FAE66](https://user-images.githubusercontent.com/70761456/105939198-8fe62c80-600d-11eb-95d2-997b18b0da2a.jpeg)

**Comment by fewerjunk** [comment]
This worked.

![sv_torus_voronoi_JPG](https://user-images.githubusercontent.com/70761456/106063000-66c8a900-60ac-11eb-820e-b72b2887351d.jpg)

**Comment by nortikin** [comment]
> Tried using Tissue (Dual Mesh) to eliminate the Dual Mesh Node (which doesn't seem to behave the same way anyways) just to see if that helped.
> 

no data passed into socket because it not linked

**Comment by fewerjunk** [comment]
![DD8CB920-6824-4D0E-8FB0-C47D2C1655A3_4_5005_c](https://user-images.githubusercontent.com/70761456/106302771-3bf66600-620e-11eb-9b1e-5a6b791be0d5.jpeg)

If I plug everything into ObjVertices and ObjFaces, I'm told there's nothing in SurfVertices.  I plug into SurfVertices and SurfFaces, I'm told there's nothing in ObjVertices.  I'm using Voronoi 3d.  Doesn't matter whether I'm using Voronoi 3d or Voronoi Scipy 3d, or how I connect them, it's not working.

**Comment by fewerjunk** [comment]
Another try:

![134ECE0A-D0F0-4F29-80FB-CE02B08AE3F5](https://user-images.githubusercontent.com/70761456/106305760-ee7bf800-6211-11eb-8f2c-d2798c99bfc3.jpeg)

**Comment by vicdoval** [comment]
Maybe the verts_in of the voronoi node should not be identical to the obj_verts_in?

**Comment by fewerjunk** [comment]
Maybe the choices are ambiguous?

**Comment by fewerjunk** [comment]
The choices are limited.  By process of elimination, one would think I might stumble fumble upon the right combination.

That one set is labeled "Obj" would suggest "Object" vertices, the other "Surf" vertices, as I interpret that, the intended outcome destination rather than the source.

Given that, so far, however I move the nodes around nothing seems to be working for me.  Either I'm an idiot not the first time, or there's a rest of the story.

**Comment by vicdoval** [comment]
I see, the cutter object (surface) has to intersect the object, in your case you are trying to cut a object with itself (voronoied but with the same shape)
![image](https://user-images.githubusercontent.com/10011941/106323626-01291800-6278-11eb-997a-af8e6800366e.png)

**Comment by fewerjunk** [comment]
That works, but, it's nothing like the original example which was and has been my goal:

"For example, "Voronoi 3D" (in combination with "Cut object by surface") node allows one to make "almost honest" Voronoi pattern on almost any surface:"

**Comment by vicdoval** [comment]
Randomize the voronoi verts_in  and it will start looking more similar

**Comment by fewerjunk** [comment]
Here's what I've got so far:

Picked the two random generators at the top of the list.

Tried the Random Vector (looked like the most plausible) and plugged it in at the various Voronoi verts_in points around the node structure with no luck.  I'm guessing out of the Scripted node, that's where I tried it first.

![2EEE588C-1914-4BEC-80A0-6F7537D8BCFC](https://user-images.githubusercontent.com/70761456/106334302-349b8080-623f-11eb-9671-4b43fc79060a.jpeg)

**Comment by fewerjunk** [comment]
This config looks promising:

![F10FB6B6-3EF9-4B83-AC6A-7BDFCA867891](https://user-images.githubusercontent.com/70761456/106335850-72e66f00-6242-11eb-95b7-60a4efb4f7f3.jpeg)

![13EACCCF-A1E1-4379-B6AD-BD967522E0EE](https://user-images.githubusercontent.com/70761456/106335927-a45f3a80-6242-11eb-829f-75c9f8d213e3.jpeg)
