### ISSUE TITLE
Component Analyzer - is boundary edges

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2843]
## Problem statement

![2020-01-19_13-59-52](https://user-images.githubusercontent.com/28003269/72678949-fe6fe080-3ac3-11ea-9df4-bba3b35f1d6c.png)

```
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\nodes\analyzer\component_analyze
r.py", line 335, in process
    vals = func(*param, special_op)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\utils\modules\edge_utils.py", li
ne 180, in edge_is_filter
    good, bad, mask = Edges.process(bm, mode, edges)
  File "C:\Users\User\YandexDisk\3.╨б╨▓╨╛╨╕_╨┐╤А╨╛╨╡╨║╤В╤Л\Blender_code\addons\sverchok\nodes\analyzer\mesh_filter.py",
line 171, in process
    orig_edge_idx = orig_edges_incidence[i1][i2]
KeyError: 0
```

**Comment by vicdoval** [comment]
I'm not sure if it is a bug (maybe the node should turn orange if you tell me how)
If you plug the edges it works fine and if you don't (with a internal conversion) at least the mask would be useless because it wouldn't match the original edges...
This function is taken from sverchok\nodes\analyzer\mesh_filter.py", line 171, in process
The mesh filter node does give the same error if you dont input edges.
Would you prefer to return no data and dont report the error? Or report the lack of edges to the console?

**Comment by Durman** [comment]
I think that the solution is obvious. Edges should be generated from faces. `Bmesh` by the way do this by default.

**Comment by portnov** [comment]
The problem is that it isn't obvious what order of edges you will receive; and therefore, the mask will have no meaning.
Maybe better solution is to report more clear error message.

**Comment by Durman** [comment]
Yes I see. I think mask should be generated from generated list of edges. Actually the mask will be useless but other two socket will be still useful. After exploring output data a user can come to desigion to connect edges socket if will find mask socket useful. I think that the error is less explicit in the case. It important because Sverchok has a lot of nodes which has only faces as output.

In most modes of the node I does not see any problems with working with generated edges from faces data.

**Comment by Durman** [comment]
@vicdoval If you find it is not important, you can color the node in orange in this way:
```Python
def process(self):
    if self.mode == 'Edges' and not self.inputs['Edges'].is_linked:
        return
````

**Comment by zeffii** [comment]
seems resolved?
