### ISSUE TITLE
Particle nodes not giving any output

### ISSUE THREAD

**Issue by harisreedhar** [nortikin/sverchok#2848]
## Problem statement

Particle nodes not working as expected. Not giving any output.

![screen](https://user-images.githubusercontent.com/46858047/72737318-5c382180-3bc5-11ea-87fb-5bb35c554667.png)

**Comment by zeffii** [comment]
the particle API is end-of-life in 2.83, i think we (sverchok) want to wait with implementing any particle related Sverchok Nodes in 2.8+, until after JacquesLuckes' "Particle Nodes" is implemented and merged into Master.

**Comment by zeffii** [comment]
it might make sense for us to remove such nodes from the Sverchok distribution @portnov  ?

**Comment by portnov** [comment]
Do they work in some situations, or not at all? If they do not work at all, I agree, let's remove them...

**Comment by zeffii** [comment]
currently there's a pullrequest pending ( https://github.com/nortikin/sverchok/pull/2511/files ) for mk2, which does restore some functionality ( i have not tested )  but it adds a depsgraph evaluation to the update handler, which i don't want to touch with a 10 meter pole.

**Comment by zeffii** [comment]
on the other hand, i would still like a working implementation of depsgraph lookup that doesn't crash Sverchok/Blender when we have Objects In set to PostModifiers mode, and a user deletes some random scene object.   My apprehension stems from that crash.

**Comment by zeffii** [comment]
@portnov  yes - https://github.com/nortikin/sverchok/issues/2757

**Comment by harisreedhar** [comment]
Thanks for the info :)

**Comment by zeffii** [comment]
i've implemented the dependency graph stuff in particles mk 2. i don't know if that works as expected.
see 
https://github.com/nortikin/sverchok/pull/2934
