### ISSUE TITLE
Nodes with file browser feature

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#2859]
Anybody knows how I could add a file browser field to a node ? (similar to the Image node in the compositor). Does any of the sverchok node have such feature (So i can take a look to see how it’s implemented).

**Comment by Durman** [comment]
Like this?
![2020-02-02_22-38-30](https://user-images.githubusercontent.com/28003269/73613210-d37da480-460c-11ea-9396-11436523437d.png)

**Comment by DolphinDream** [comment]
Something like this:

![FileBrowserFeature](https://user-images.githubusercontent.com/2083719/73613577-4d8a3b00-45c5-11ea-8390-56cdb42f0f58.gif)

**Comment by zeffii** [comment]
also Viewer Typography node lets you open a Filebrowser..from the N-Panel,
![image](https://user-images.githubusercontent.com/619340/73613637-1aad6a80-45f8-11ea-9cf8-d6895c7d3cf2.png)

**Comment by zeffii** [comment]
now, the class would look something like:
```python
class SvTextInFileImporterOp(bpy.types.Operator):

    bl_idname = "node.sv_textin_file_importer"
    bl_label = "File Importer"

    filepath: StringProperty(
        name="File Path",
        description="Filepath used for importing the file",
        maxlen=1024, default="", subtype='FILE_PATH')

    def execute(self, context):
        n = self.node
        t = bpy.data.texts.load(self.filepath)
        n.text = t.name
        return {'FINISHED'}

    def invoke(self, context, event):
        self.node = context.node
        wm = context.window_manager
        wm.fileselect_add(self)
        return {'RUNNING_MODAL'}
```
you might want to add `nodetreename` and `nodename` as annotations to the operator, so Blender will always know where the button press comes from.

**Comment by zeffii** [comment]
like..

```python
class SvSomeNodeFileImporterOp(bpy.types.Operator):

    bl_idname = "node.sv_somenode_file_importer"
    bl_label = "File Importer"

    filepath: StringProperty(
        name="File Path",
        description="Filepath used for importing the file",
        maxlen=1024, default="", subtype='FILE_PATH')

    idname: StringProperty(
        name='idname', description='name of parent node', default='')

    idtree: StringProperty(
        name='idtree', description='name of parent tree', default='')

    def get_node(self):
        node_group = bpy.data.node_groups[self.idtree]
        node = node_group.nodes[self.idname]
        return node

    def execute(self, context):
        n = self.get_node()
        t = bpy.data.texts.load(self.filepath)
        n.text = t.name
        return {'FINISHED'}

    def invoke(self, context, event):
        wm = context.window_manager
        wm.fileselect_add(self)
        return {'RUNNING_MODAL'}

```
and the ui..
```python


    r = layout.row()
    load_op = r.operator("node.sv_somenode_file_importer", text="Load")
    load_op.idname = self.name
    load_op.idtree = self.id_data.name


```

**Comment by DolphinDream** [comment]
Thanks @zeffii  that was very helpful.

The above solution loads the file (assuming it’s text) so I assume that if I want to load a non-text format file I won’t need to load it (via bpy.data.texts.load) but simply get the filepath from the browser and then let the node do the loading. Correct?

Also it would be nice to have other UI elements listing the latest loaded resources in a drop down list so you can quickly switch between them (similar to the image node in compositor; see attached demo). I wonder if I would have to create these UI elements myself or are they provided by some modules in blender already.

![FileBrowserFeature2](https://user-images.githubusercontent.com/2083719/73671220-8800e000-4678-11ea-903c-00cebce82345.gif)

**Comment by zeffii** [comment]
> The above solution loads the file (assuming it’s text) so I assume that if I want to load a non-text format file I won’t need to load it (via bpy.data.texts.load) but simply get the filepath from the browser and then let the node do the loading. Correct?

yeah, the example is really intended to show you how to get the `filepath` from the filebrowser usage, and then returning to the `execute` function of the operator, with a reference to the Node that triggered the button press. Then you do whatever you need with the filepath and Node.

> Also it would be nice to have other UI elements listing the latest loaded resources in a drop down list so you can quickly switch between them (similar to the image node in compositor; see attached demo). I wonder if I would have to create these UI elements myself or are they provided by some modules in blender already.

UI scripting... you might look at the monad N-panel, and the more resent materials Node, but definitely dig into the bpy docs for `template`

**Comment by portnov** [comment]
I'm not sure if there is a predefined `template` function for this, you'll have to search the docs; but if there is no, you can check `ui_previews_custom_icon.py` example in Blender's default set of examples (text editor -> Templates -> Python -> UI Previews Custom Icon).

**Comment by DolphinDream** [comment]
How do you load multiple filepaths? (if you select multiple files)

**Comment by zeffii** [comment]
https://blender.stackexchange.com/questions/30678/bpy-file-browser-get-selected-file-names
