### ISSUE TITLE
lazy loft

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2860]
from Blender Stackexchange

[shapdes_2020_02_02_21_52.zip](https://github.com/nortikin/sverchok/files/4145454/shapdes_2020_02_02_21_52.zip)

![image](https://user-images.githubusercontent.com/619340/73616053-f4df9000-460e-11ea-9ec9-e655a7197082.png)

**Comment by portnov** [comment]
"Bend along surface" node does basically the same :)

**Comment by zeffii** [comment]
@portnov, can you show me how you would setup the nodetree to get the result that was saught here: 
![image](https://user-images.githubusercontent.com/619340/73735867-33c13300-4740-11ea-816c-e70cfb4ff43d.png)
for this question.. i'm probably not understand the node.. 
https://blender.stackexchange.com/questions/165095/sweep-along-a-path-through-multiple-cross-sections

**Comment by portnov** [comment]
@zeffii I saw (it seems) the same question on blenderartists... Quote:

> The only problem I see here is how to relate the placement of “profile” objects in 3D to their place along the length of a curve. It probably can be done automatically, but maybe not that easy. As one of options, you can place your profile objects in correct places in 3D (as you did on your picture), create a “loft” through them and just hope that it will follow the correct curve. Another option is to place profile objects along, for example, X axis, then make a loft with them, and then bend that loft along the curve. Then you can adjust location of profile objects along X axis to move them along the curve correspondingly. Here is an example of the second approach.
https://blenderartists.org/t/wip-sverchok-parametric-nodes-for-architects/557250/2275?u=portnov
https://gist.github.com/portnov/cdf4e005480de36225e4fbf3b7839a64

The example of the first approach:

https://gist.github.com/05be7d58f56f4f0458463540a0c0a974

![Screenshot_20200204_214349](https://user-images.githubusercontent.com/284644/73766426-cfca5900-4797-11ea-8582-c229095a95d9.png)

**Comment by portnov** [comment]
Number of vertices in each "loft form" does not matter; the only thing you have to check is that the order of shapes is correct, as well as the order of vertices in each shape.

**Comment by zeffii** [comment]
@portnov  ! ah ha! i see,  that's not super obvious, even though it works nice enough. Notice the profiles get interpolated "loosly" (the last image on the right shows the deviation from the target shape)

I think i'd like to offer a proper Loft node (or set of nodes) , it would be an interesting problem to solve.

**Comment by portnov** [comment]
@zeffii Huh. In Sverchok-Extra, I have nodes similar to this one, but working with NURBS (requires geomdl library). There one can manually adjust weights of particular control points, to say which of them are more important to follow.
