### ISSUE TITLE
Lazy Loft (experiments)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2863]
following: https://blender.stackexchange.com/questions/165866/lofting-along-a-path

I think we can offer analogues to the "modulated extrude over path" issue, which is a combo of taper, sweep and loft. This would be a slight departure from "doing everything inside Sverchok".

We could have a node that initially duplicates the Path 2 times into its own "components" collection, and attaches one Bevel object (A) to one path, and the other Bevel object (B) to the other path, and performs its own dedicated "Object In", which knows how to split the resulting meshes into their "profiles at each Path segment" . 

![image](https://user-images.githubusercontent.com/619340/73831945-80237600-4807-11ea-8352-ed0147a675cc.png)

Then  we offer a `ratio input` to allow interpolation values between `0....1` for each vertex/node of the path, to interpolate between shape A and B.

![image](https://user-images.githubusercontent.com/619340/73832785-17d59400-4809-11ea-8980-a84de14c6a1b.png)

**Comment by zeffii** [comment]
this can be done really fast with numpy :)  , and let's assume initially that both shapes have the same Vertex count

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/73834715-81a36d00-480c-11ea-8de8-3370ffc9c683.png)

**Comment by zeffii** [comment]
[loft_starter_step3_2020_02_05_11_13.zip](https://github.com/nortikin/sverchok/files/4159143/loft_starter_step3_2020_02_05_11_13.zip)

**Comment by portnov** [comment]
The last one seems more like "cast" :)

**Comment by vicdoval** [comment]
Lofting along a path between two profiles (all inside sverchok) 😄  ![image](https://user-images.githubusercontent.com/10011941/73847437-942aa000-4826-11ea-8f6b-a9a4ab46f1df.png)

**Comment by zeffii** [comment]
@vicdoval  yeah, that's totally the way to do it :)  i've added it as an answer https://blender.stackexchange.com/a/165994/47  (i assume you don't object)

i'll still make the sweep node :)

**Comment by portnov** [comment]
@zeffii 
![Screenshot_20200205_222404](https://user-images.githubusercontent.com/284644/73866247-56e60280-4866-11ea-8a0b-d0a52e6b7f17.png)

;)

**Comment by zeffii** [comment]
super cool : ) @portnov

**Comment by zeffii** [comment]
@portnov , i like the Curve / Surface sockets :) 

you are familiar with C/C++ have you ever looked at what modifications would be needed to allow us to instanciate a NURBS surface from python? I wrote about this a while back, we're missing one small thing that would allow us to do that.

https://blenderscripting.blogspot.com/2014/04/scripting-nurbs-surfaces.html

**Comment by zeffii** [comment]
i can't believe that's almost 6 years ago already.

**Comment by zeffii** [comment]
```
import bpy
from mathutils import Vector

collection = bpy.context.scene.collection

surface_data = bpy.data.curves.new('wook', 'SURFACE')
surface_data.dimensions = '3D'

# 16 coordinates, set points per segments (U * V)
points = [
    Vector((-1.5, -1.5, 0.0, 1.0)), Vector((-1.5, -0.5, 0.0, 1.0)),
    Vector((-1.5, 0.5, 0.0, 1.0)), Vector((-1.5, 1.5, 0.0, 1.0)),
    Vector((-0.5, -1.5, 0.0, 1.0)), Vector((-0.5, -0.5, 1.0, 1.0)),
    Vector((-0.5, 0.5, 1.0, 1.0)), Vector((-0.5, 1.5, 0.0, 1.0)),
    Vector((0.5, -1.5, 0.0, 1.0)), Vector((0.5, -0.5, 1.0, 1.0)),
    Vector((0.5, 0.5, 1.0, 1.0)), Vector((0.5, 1.5, 0.0, 1.0)),
    Vector((1.5, -1.5, 0.0, 1.0)), Vector((1.5, -0.5, 0.0, 1.0)),
    Vector((1.5, 0.5, 0.0, 1.0)), Vector((1.5, 1.5, 0.0, 1.0))
]

for i in range(0, 16, 4):
    spline = surface_data.splines.new(type='NURBS')
    spline.points.add(3)  # already has a default zero vector

    for p, new_co in zip(spline.points, points[i:i+4]):
        p.co = new_co

surface_object = bpy.data.objects.new('NURBS_OBJ', surface_data)
collection.objects.link(surface_object)

splines = surface_object.data.splines
for s in splines:
    for p in s.points:
        p.select = True

bpy.context.view_layer.objects.active = surface_object
bpy.ops.object.mode_set(mode='EDIT')
bpy.ops.curve.make_segment()
```

**Comment by portnov** [comment]
@zeffii we can make a "NURBS output" node, which will create Blender's nurbs object from control points (similar to how our Metaball Out node works, for example). I'm not sure it will be very useful, because 1) it's not that easy to figure out what control points you need, and 2) in most cases you will have nothing to do with the resulting nurbs object: you can't run "adaptive polygons" on it, for example...

**Comment by zeffii** [comment]
> @zeffii we can make a "NURBS output" node, which will create Blender's nurbs object from control points

i never managed to dynamically make a NURBS surface object and change the number of points in a NURBS object, show me.  maybe at the time (6 y ago) i was a little greener.

**Comment by portnov** [comment]
Well, if for some reason Blender does not allow changing number of points in nurbs objects, we can always re-create the whole object :) Not very fast though...

**Comment by zeffii** [comment]
..i've been toying with the idea that we could speed up the dynamic creation/recreation of objects a lot if we didn't "delete objects" , but only unlinked objects.. and relink them when needed. The drawback is ..depending on how the user operates the node.. there may be suddenly 10000 objects with large vertex count, hogging memory while only 3 are visible.

**Comment by zeffii** [comment]
for now i've added the Sweep Modulator node to the beta/alpha nodes
https://github.com/nortikin/sverchok/pull/2864  (and docs! )
