### ISSUE TITLE
Left Justifty Text in T-Panel for Saved Presets

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2865]
Is there a way to left justify text in the T-Panel for saved presets? My saved presets automatically center justifies the text making it difficult to read as a list. Thanks.
![___left just](https://user-images.githubusercontent.com/59537375/73890800-a6f1a480-4827-11ea-979e-1a0dc9705771.PNG)

**Comment by portnov** [comment]
Right now I don't see a way to do it — it seems Blender decides it by it's own. Maybe there is a switch in a preferences (somewhere near themes) to change text alignment on all buttons in Blender UI at once...

**Comment by portnov** [comment]
@OiledEluer since you have many presets, I'd suggest to organize them into categories. Imho it would be simpler to manage them this way.
Also there is a search bar in the top of presets panel. Just type keyword and press enter to search, click 'X' to reset search.

Also all presets can be called from standard Blender's F3 (or Space, if you use old-fashioned keymap, as I do) menu. So you can just press F3 and start typing preset name.

**Comment by OiledEluer** [comment]
That pesky Blender doing what it wants.  I did look in the preferences but only found color changes or text changes which incidentally did not change the font size in the preset panel.  I did not know about the F3 function, that is helpful.
I do already have many categories.  I will say having the preset functionality is very very useful.

**Comment by portnov** [comment]
Another useful thing is Blender's Q menu. You right-click on any button (not only preset, anywhere in Blender) and select "Add to Quick Favorites". Then the function will be available in the menu which pops up by Q key. Items will be automatically filtered depending on context (for example, nodes will not be shown if you press Q while in 3D view, and so on), but it obviously does not have sense to add a lot of things into Q menu, only the most used ones should go there.

**Comment by portnov** [comment]
About your original question: 
https://blender.stackexchange.com/questions/3576/how-can-i-change-the-buttons-text-position
It's not possible to control text alignment from python code.
(ideasman42 is one of core blender developers, so I believe that answer is the final one).

**Comment by OiledEluer** [comment]
Ok, thanks for the info.
