### ISSUE TITLE
Barycentric Transform: Unable to Bake VDMK3 or get Viewer BMesh Output

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#2866]
## Problem statement
I am using the example in the docs for the Barycentric Transform node. Everything was working fine per the example until I tried to get a renderable object.  When invoking bake in Viewer Draw MK3 node I get an error message as shown below.  The Viewer Bmesh gives no output.

## Steps to reproduce
![bake with barycentric](https://user-images.githubusercontent.com/59537375/73892903-f8e8f900-482c-11ea-996d-d5810c8daaf9.PNG)

## Expected result

An object that was renderable.

## Actual result

Per attached.

## Sverchok version

0.6.0.0 commits through Feb 4 2020

**Comment by vicdoval** [comment]
I am not getting any failure :
![image](https://user-images.githubusercontent.com/10011941/73918825-a78b4900-48c2-11ea-910d-b089b39ecef9.png)
Maybe it is because you  plugged the vertices output to the faces input of the bmesh viewer?

**Comment by zeffii** [comment]
when one node is in an error state (like the BMviewer node above) then other nodes will not do a valid socket-cache lookup (so the bake function would be trying to operate on no data, because the flow of socket-data was interrupted)

i think.

**Comment by OiledEluer** [comment]
@vicdoval I was able to replicate the example you provided above, no problem.  I went back to my file (which is the second example in the docs and has a slightly different configuration and used cycle as as the match).  I do see now that in the screenshot I sent had the vertices output to the face of the BMviewer.  That was me playing with the connections after I got the error,  and when I reproduced again with the correct (believed to be at least) connection,  I got the same error messages and error state. 
@zeffii  I tried both BMviewer and VD independently and before and after the error states to try to eliminate the error with one or the other but did not work.

**Comment by vicdoval** [comment]
@OiledEluer Could you plase supply a file with the minimum nodetree that produces the bug for me to look at?

**Comment by OiledEluer** [comment]
I can but have never uploaded a file.  Do you just drag the Blend file into this field?

**Comment by zeffii** [comment]
drag a zip into the msg

**Comment by OiledEluer** [comment]
attached here
[_sv_barycentric transform_00_match list in advanced parameters_2020_02_06_19_54.zip](https://github.com/nortikin/sverchok/files/4167213/_sv_barycentric.transform_00_match.list.in.advanced.parameters_2020_02_06_19_54.zip)

**Comment by zeffii** [comment]
i see.. 
```python
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\data_structure.py", line 368, in levelsOflist
    if n and isinstance(n, (list, tuple)):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
is not expecting a numpy  `array`

**Comment by zeffii** [comment]
in the N panel, when you untick the`output numpy` option in the barycentric transform, then the Bake Operator proceeds without throwing an error

**Comment by OiledEluer** [comment]
Ok, thanks.  With the Bake, is there a way to merge the objects as you can in BM Viewer?

**Comment by zeffii** [comment]
nope. would that be useful?   would be relatively easy to implement

**Comment by vicdoval** [comment]
you can use mesh join node before the viewer to bake it as one object, also the bmesh viewer does not support numpy (yet) but works fine if you disable the output numpy. (My fault that you can not see if that property is active or not, i will fix it soon 😄 )

**Comment by OiledEluer** [comment]
@vicdoval  I got the mesh join node to work, thanks     @zeffii Yes that would be great if it is easy to implement as it would save the step of adding the mesh join node.  You can get some interesting stop motion effects using the bake feature hooked up to the Frame Info node.

**Comment by zeffii** [comment]
it's probably less involved for me to modify BMeshViewer to accept numpy directly, than it is to update the VD's Bake operator (that thing is hella klunky )

**Comment by zeffii** [comment]
... but if someone else feels like doing it....  :)

**Comment by zeffii** [comment]
i think the issue is stale? reopen if not.
