### ISSUE TITLE
Polyline turns red -- B2.82+ Curve Objects no longer have "use_uv_as_generated"

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2872]
With blender 2.83.2 and updated sverchok if i connect the linenode  to the polyline viewer it turns red and matric input is not working any more .

![image](https://user-images.githubusercontent.com/49908008/74073486-c98fe300-4a0a-11ea-8e90-eb3469f1c6c6.png)

**Comment by vicdoval** [comment]
Confirmed `2.83\scripts\addons\sverchok-master\nodes\viz\viewer_polyline.py", line 251, in set_auto_uv
    if obj.data.use_uv_as_generated != self.use_auto_uv:
AttributeError: 'Curve' object has no attribute 'use_uv_as_generated'`

**Comment by zeffii** [comment]
maybe they renamed it?

**Comment by zeffii** [comment]
https://developer.blender.org/D6739

**Comment by zeffii** [comment]
they removed it :)   can't do much about that.

**Comment by zeffii** [comment]
is it possible that Curve objects now have better Shader Node support?

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2873 resolved the error,  but i await a shader based solution to the lack of `use_uv_as_generated`
