### ISSUE TITLE
Debugging of monads

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#2874]
## Problem statement

It would be nice if inside a monad it is possible to check socket data via `stethoscope` node.

Now It shows nothing:
![2020-02-10_08-13-29](https://user-images.githubusercontent.com/28003269/74120689-c567ef00-4bdd-11ea-854f-3c209cb66496.png)

**Comment by zeffii** [comment]
it may be possible, does debug_print node work?

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/03871e7c7c8a053aca857e9ff60bfcbffb32660c/ui/bgl_callback_nodeview.py#L228-L229

for the nodeview bgl callback. - shows some room for experimentation, but i'm not eager to have special cases there..

**Comment by Durman** [comment]
> it may be possible, does debug_print node work?

It does not.

**Comment by zeffii** [comment]
ok. i'll see what i can do.

**Comment by zeffii** [comment]
what i'm willing to do is this.
- add an automatic detection in debug_print for which nodetree it's inside.
- debug_print will become aware of what mode the monad is in.
- allow it to create a `monad{name}_debug.txt` , and let it detect which loop iteration it's on.  if not looping iteration will still be displayed as =1
```
iteration=1
...
...
...
iteration=2
...
..
.
etc.
```

**Comment by zeffii** [comment]
note to self / the interested.

https://github.com/nortikin/sverchok/blob/1d148f1b68419d70b21da705d7e35d62843fb709/core/monad.py#L550-L555

The update list ( ul ) generated inside the monad, 

![image](https://user-images.githubusercontent.com/619340/74243089-5ffc2700-4cdf-11ea-89fc-d8f6afe1c832.png)

will not include nodes that aren't connected to another node downstream.
```python
>>> ul =
['Group Inputs Exp', 'Circle', 'Group Outputs Exp']
```
In the case of debugprint, it would never be included because it doesn't have an output socket. For example. So.. `process` is not called on `debug_print` node in that current configuration.

**Comment by zeffii** [comment]
so.. possibly..
```python
ul = make_tree_from_nodes([out_node.name, <all active debug_print nodes>], monad, down=False)
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2877 @Durman 

tentatively works.

**Comment by zeffii** [comment]
not implemented for `process_vectorize` or `process_looped`  yet.  `SvDebugPrint` will need a few upgrades.

there's no real reason `stethoscope` can not draw to `SverchGroupTreeType`, it's a totally sane request. no ETA on that tho, it's also not immediately clear how you would display `process_looped`.

**Comment by zeffii** [comment]
i committed https://github.com/nortikin/sverchok/pull/2877 ,  this was on my todo for a long time .

**Comment by Durman** [comment]
Good work. Now it will be easier to deal with monads. It would be great if you find time to fix stethoscope later.
