### ISSUE TITLE
Separate property on move/scale and rotate

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#2885]
I was thinking about re-writing this nodes in numpy:
![image](https://user-images.githubusercontent.com/10011941/74731481-59723000-5248-11ea-8112-1cd9228f86ac.png)

The three of them have this "Separate" property that is not documented with the only description "Separate UV Coords". Apparently what it does is wrapping the input vertices with a extra [ ]
![image](https://user-images.githubusercontent.com/10011941/74731748-f8972780-5248-11ea-8916-e5ffe70a8a02.png)

Can anybody explain me what is the practical use  or the  idea behind this property?

**Comment by vicdoval** [comment]
It was added by @nortikin in 2017 but why? Should it be maintained?

**Comment by zeffii** [comment]
i don't recall why - reading the code it seems a little unusual, but i suspect the issue isn't simple and becomes more interesting when you feed the node more complex input.

https://github.com/nortikin/sverchok/issues/1519

**Comment by Durman** [comment]
I think he had added it by my request. I had some issue which I don't remember now. I think it is inconsistent property any way.

**Comment by vicdoval** [comment]
I see.... its like splitting the move vector and wrapping it.
![image](https://user-images.githubusercontent.com/10011941/74867243-99bed480-5354-11ea-99fe-43f350fb5889.png)

It is quite advanced property, outputting a level 4 list that would be to feed uv connections node.

It is not a bad idea but if I rewrite it in the same fashion as the Vector Math mk3 (multilevel recursion) the same result could be achieved preparing the data before using the node as seen in the example.
What do you think? Should I keep it? Should I change the name? Should I forget it?

**Comment by Durman** [comment]
I would prefer this property will be deleted from new version of the node. Approach with multilevel recursion I think always is welcomed.

**Comment by vicdoval** [comment]
Updated at #2899

**Comment by nortikin** [comment]
it was one of main ideas, that i cannot maintain for now.
To deal with sublevels to achive more tree-like structure.
some tricks can handled such a way easily. I.e. voronoi extrusion with scaling at the moment, and connected. Not only that nodes, but generators and some modifiers use separate mode.

**Comment by nortikin** [comment]
ok, we can handle one approach. masking.
masking is much usefull and can cover multilevel approach.
**And we can make special node, that converts masks to levels**s s s
so uvconnect node can be rewriten with masks input. And generators can handle this approach.
It will prepare us to numpy migration for future
