### ISSUE TITLE
Monad must die. Long live Monad Lite.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2886]
For anyone who uses Monad, but has not spent any real time investigating how it's implemented - you have no idea how much code is involved. A little bit too much in my opinion. Almost everything about it is complex. This is not to say that the implementation is entirely bad, but it is certainly more like something that has evolved with detours, side quests, and rethinks. Things that evolve don't always result in implementations that are super-efficient. I'm talking about efficiency not in terms of speed, but definitely code comprehension and maintainability.

The things that make Monad difficult are:
- it creates a another nodegroup ( the green state )
- it recreates a dynamically defined class upon each new socket acquisition, ,and updates all other instances of the Monad 
- has several "process" models (loop, vectorize, normal)
- is split into 5 or more files (ui, utils, core, node..)
- uses iojson for the "Make Unique".

i'm probably missing something, but these are the implementation details that tend to do enough damage to progress.

I have no immediate plan to start `Monad Lite`, but I might use this thread to collect thoughts about Monad's future. Starting with specs this time, now we have a better understanding of the implementation of dynamic classes.

It may even result in a complete Monad rewrite in-situ instead of a Lite version. Regardless, a clean start is premium.

-------------------
this issue will address 
#2795 
#2791 
https://github.com/nortikin/sverchok/pull/2893

-------------------
check list of stuff that needs to work flawlessly.

- [ ] create new empty monad
- [ ] clone monad as unique ( no longer linked to original monad )
- [ ] generate monad from selected nodes (ctrl + g )
- [ ] drop current monad into nodetree  (kb combo..)
- [ ] add new socket (plus var and var.attrs if appropriate ), from n panel
- [ ] add new socket (plus var and var.attrs if appropriate ), from socket drag
- [ ] monad must control its own internal variable names, to avoid duplication
- [ ] display socket names would also be unique.. 
     - maybe `in {<socket.index>} {socket.name}`  , the drawback there is definitely that it will be set only infrequently. maybe that's a good thing
- [ ] prohibit `connect me` -> `connect me` links.

**Comment by Durman** [comment]
Probably it would be better to separate this functionality to other nodes. - (loop, vectorize, normal)

**Comment by zeffii** [comment]
> Probably it would be better to separate this functionality to other nodes. - (loop, vectorize, normal)

Implementing those modes as separate nodes would make switching between modes more complex (replacing node class, hotlinking...). Currently the amount of code that has to be "loaded into your brain" for those modes is minimal. and they are all separate, and can be understood in a case-by-case basis. Maybe I should not not have added it to that list.

**Comment by portnov** [comment]
> it creates a another nodegroup ( the green state )

this, I think, is a good thing.

**Comment by zeffii** [comment]
> this, I think, is a good thing.

it's vital : )

**Comment by Durman** [comment]
Can be useful - about loops in animation nodes:
https://animation-nodes-manual.readthedocs.io/en/latest/user_guide/subprograms/loop.html

**Comment by zeffii** [comment]
maybe time for a redesign document.

# Monad

- Monad is a node with an associated node tree "inside it". 
- Monad `node trees` are stored as `bpy.data.node_groups`, as type `"SverchGroupTreeType"`
- While the user is inside the Monad `node` (ie looking at a `SverchGroupTreeType` tree, with the  green background) things get complicated.
     1. Whenever a user interacts with the Input and Output nodes in that tree, in such a way as to cause those nodes to get a new socket, then the outer `Monad node` is dynamically (re)registered to contain the correct properties for it's sliders.
    2. The input and output nodes are also dynamically updated (but not re-registered) to handle the new socket.
    3. Interaction with existing sockets on the input and output nodes do not
         - trigger dynamic reregister of the outer Monad node
         - they also do not rename the socket
    4. right now there is no nice way to ensure unique socket names

**Comment by zeffii** [comment]
it may be a relatively lite fix. i'll sleep on it.
most nodes will pass through the first section of 

- add_prop_from(self, socket)
```python
    def add_prop_from(self, socket):
        """
        Add a property if possible
        """
        other = socket.other
        cls = get_node_class_reference(self.cls_bl_idname)
        cls_dict = cls.__dict__ if cls else {}

        if other.prop_name:
            prop_name = other.prop_name

            prop_func, prop_dict = other.node.__annotations__.get(prop_name, ("", {}))
            print("prop_func:", prop_func)
            print("prop_dict:", prop_dict)
            print("prop_name:", prop_name)

            if prop_func.__name__ == "FloatProperty":
                self.get_current_as_default(prop_dict, other.node, prop_name)
                prop_settings = self.float_props.add()
            elif prop_func.__name__ == "IntProperty":
                self.get_current_as_default(prop_dict, other.node, prop_name)
                prop_settings = self.int_props.add()
            elif prop_func.__name__ == "FloatVectorProperty":
                info("FloatVectorProperty ignored (normal behaviour since day one). prop_func: %s, prop_dict: %s.", prop_func, prop_dict)
                return None # for now etc
            else: # no way to handle it
                return None

            # print('dict')
            # pprint.pprint(prop_dict)
            new_name = generate_name(prop_name, cls_dict)
            prop_settings.prop_name = new_name
            prop_settings.set_settings(prop_dict)
            socket.prop_name = new_name
            return new_name
   ...
   # snippet only of interest

```
and all of those will pass through

- generate_name

```python
def generate_name(prop_name, cls_dict):
    if prop_name in cls_dict:
        # all properties need unique names,
        # if 'x' is taken 'x2' etc.
        for i in range(2, 100):
            new_name = "{}{}".format(prop_name, i)
            if not new_name in cls_dict:
                return new_name
    else:
        return prop_name
```

**Comment by zeffii** [comment]
what I think i'll do is force internal property names (user will never see these) to be unique and valid by prepending something like
```python
   if "FloatProperty":
       idx = len(self.float_props)  # <--- this should always reflect the num of stored floats
       prop_name = ... as found
       new_prop_name = f"float_prop_{idx}_{prop_name}"
```

**Comment by zeffii** [comment]
ok . plan.

- [x]  duplicate prop_names are now allowed for most nodes
      - relatively basic prop_name modifier to ensure unique prop names on the monad node.
- [ ] some nodes implement get/set, these require explicit handling but will all follow a pattern 
      - monad's "add_prop_from" can ditch get/set for `float_` and `int_` function signature (prop_dict) and instead directly write  min / max for the dynamically created props
      - [ ]  A number node  requires special handling, in this scenario
- [ ] handle nodes that use `socket.prop_type`  (snlite... i think..)

**Comment by zeffii** [comment]
i'll test this over the next few days. but i'm inclined to think this settles most issues. and if not i've added comments in the areas which are dynamic and full of sideffects

**Comment by zeffii** [comment]
i'll keep poking around at this fort another while, right now my main issue is the update system being triggered somwhere that i haven't been able to hold yet.  i think it's in `verify_props`..

**Comment by nortikin** [comment]
i will add new process - genetic algorithm process
