### ISSUE TITLE
Extruding a Simple Bento Box is slightly complicated

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2887]
[simple_bento_004.blend.zip](https://github.com/nortikin/sverchok/files/4222599/simple_bento_004.blend.zip)

<img width="992" alt="Screen Shot 2020-02-19 at 12 09 48 pm" src="https://user-images.githubusercontent.com/3952687/74792170-ba653b00-5310-11ea-86f4-b834cd5fa164.png">

<img width="520" alt="Screen Shot 2020-02-19 at 12 08 14 pm" src="https://user-images.githubusercontent.com/3952687/74792177-bfc28580-5310-11ea-8537-e8520ab8aaf4.png">

I am basically trying to make sense this MASK way in Sverchok when dealing with Extrude, Inner Outer, and from my example case, I think it's pretty good. Usually when extruding, I never go too far, 1 or 2 nodes and it started to get confusing with masking. But it's time for me to learn deeper with art of masking. 

Any hints?

**Comment by enzyme69** [comment]
With Inset Special, I know the fact that we can separate these faces, and so I can simply extrude this bit, and then combine together and maybe remove doubles and delete loose. It's slightly dirty workflow.

<img width="781" alt="Screen Shot 2020-02-19 at 12 12 33 pm" src="https://user-images.githubusercontent.com/3952687/74792289-1d56d200-5311-11ea-97cb-aa3f4c32d364.png">

**Comment by enzyme69** [comment]
The dirty method:
[simple_bento_004_DIRTY.blend.zip](https://github.com/nortikin/sverchok/files/4222618/simple_bento_004_DIRTY.blend.zip)

<img width="980" alt="Screen Shot 2020-02-19 at 12 16 32 pm" src="https://user-images.githubusercontent.com/3952687/74792475-b1289e00-5311-11ea-8a1e-8e2a5df1e919.png">

But the method that is more preferrable is to be able to get Mask of area that was extruded and was not extruded.

**Comment by Durman** [comment]
![2020-02-19_08-04-14](https://user-images.githubusercontent.com/28003269/74800925-7103f400-52ee-11ea-80e5-5f7c74e2281c.png)

**Comment by enzyme69** [comment]
@Durman That's actually very interesting! Maybe in my previous setup I was on a path where I cannot control the last face I want to extrude.

But with Inset Faces... it's solved. 

I guess this shall do for now~

**Comment by enzyme69** [comment]
Is this the best way to close the bottom bit? (find the edge, close it using Edgenet)

<img width="1147" alt="Screen Shot 2020-02-19 at 8 13 25 pm" src="https://user-images.githubusercontent.com/3952687/74819353-5fedce00-5354-11ea-8868-6b5dc4ece02c.png">

**Comment by Durman** [comment]
![2020-02-19_13-55-58](https://user-images.githubusercontent.com/28003269/74823248-dae8c180-531f-11ea-9b80-a715cd083462.png)
[untitled3_2020_02_19_09_58.zip](https://github.com/nortikin/sverchok/files/4224336/untitled3_2020_02_19_09_58.zip)

**Comment by enzyme69** [comment]
Thanks Durman! I'll study this!

**Comment by enzyme69** [comment]
Transform Mesh is surprising.

**Comment by enzyme69** [comment]
[extrude_edge_002.blend.zip](https://github.com/nortikin/sverchok/files/4364638/extrude_edge_002.blend.zip)
<img width="580" alt="Screen Shot 2020-03-22 at 3 06 50 pm" src="https://user-images.githubusercontent.com/3952687/77242093-03314c00-6c4f-11ea-9aed-a72e48769432.png">

**Comment by Durman** [comment]
In this case you can have problem with normals of extruded from edges faces.
