### ISSUE TITLE
Question : Pulga Physics

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2888]
Pulga Physics works this the same like this example : http://paulbourke.net/fractals/randomtile/

**Comment by portnov** [comment]
Eh. It's not clear, what the question is. Please elaborate.

**Comment by BennyGovaerts** [comment]
Can this be done with sverchok ,the result looks better then if you use the Pulga Physics node for example

**Comment by portnov** [comment]
Tecnhically, there are different problems solved. PulgaPhysics moves circles around by implementing some kind of physics simulation (@vicdoval could you please elaborate?). The algorithm by your link tries to pack the space by shapes. I should say it does it with a brute-force algorithm, so it should take a lot of resources.

It is certainly possible to copy-paste that algorithm into Sverchok's scripted node :)

**Comment by portnov** [comment]
There is also https://pypi.org/project/circlify/
It solves yet another problem: it packs circles into another circle...

**Comment by portnov** [comment]
Another problem with another solution from https://www.grasshopper3d.com/forum/topics/circle-packing-in-python :

```
plane = Plane.WorldXY
arrCircle = []
distance = pts[0].DistanceTo(pts[1])
c1 = Circle(plane, pts[0], distance / 2)
c2 = Circle(plane, pts[1], distance / 2)
arrCircle.extend((c1, c2))

for i in range(2, pts.Count):
    min = float.MaxValue
    
    for j in range(0, arrCircle.Count):
        tPt = arrCircle[j].ClosestPoint(pts[i])
        dist = pts[i].DistanceTo(tPt)
        if dist &lt; min: min = dist
    
    tCircle = Circle(plane, pts[i], min)
    arrCircle.append(tCircle)
```
This just draws circles around given points, solving just the problem of their non-intersection, not trying to move them around for best packing...

**Comment by portnov** [comment]
Circlify package appeared easy enough to use... so I've implemeted a node for it into sverchok-extra
![Screenshot_20200221_202824](https://user-images.githubusercontent.com/284644/75047577-cf94c200-54e8-11ea-8905-bbbe132e89d7.png)

**Comment by portnov** [comment]
Another idea:
https://aarizat.github.io/packcircles4bims/circlespacking.html#module-circlespacking
This has dependency on matplotlib and "triangle" library. We do not need matplotlib, and "triangle" just contains Delanuay triangulation, which blender already has. The idea is more or less obvious: given a triangulated mesh, inscribe a circle into each triangle; then inscribe a circle into each free corner.... and so on. This can be relatively easy implemented in blender's python without external dependencies.

**Comment by portnov** [comment]
Well, it seems even just drawing inscribed circles for Delaunay triangulatrion may give not that bad result. If you pass random points through Lloyd algorithm first.

![Screenshot_20200221_232335](https://user-images.githubusercontent.com/284644/75060849-60779780-5501-11ea-8b85-8c1b10e71de5.png)

**Comment by vicdoval** [comment]
As @portnov points pulga phisics handles spheres and applies different simulation algorithms to them, 
The node offers different parameters that could help to create an output like the one you point.

The "Fit" parameters Grow, max Radius and min Radius will make the initial radius to change if the spheres collide (shrink) or don't collide (grow)
![image](https://user-images.githubusercontent.com/10011941/75065943-2f3f9d00-54ea-11ea-8a49-04c9902702d0.png)

The Collision and Attraction will move the spheres, with the right amount of each you can pack some circles:
![image](https://user-images.githubusercontent.com/10011941/75066444-23080f80-54eb-11ea-83da-cdc2ca0b1b12.png)

With the "Obstacles" you can force them to stay in a place (note that obstacles pols must be Tris)
![image](https://user-images.githubusercontent.com/10011941/75066816-fbfe0d80-54eb-11ea-9111-15800685842e.png)

With the "Springs" module you can attempt more complex structure packing but it will be tricky 😄 
![image](https://user-images.githubusercontent.com/10011941/75069551-af1d3580-54f1-11ea-8615-eb62987c6eb7.png)

![image](https://user-images.githubusercontent.com/10011941/75069399-62395f00-54f1-11ea-8317-b0cfcaae8ed0.png)

**Comment by portnov** [comment]
One may also take a totally different approach, and pack Steiner ellipses instead of circles...

![Screenshot_20200222_192330](https://user-images.githubusercontent.com/284644/75094443-eb619c00-55ac-11ea-8e96-2141d86eaa34.png)

**Comment by BennyGovaerts** [comment]
Thanks guys for the excellent feedback & support

**Comment by portnov** [comment]
Yet another approach: make Voronoi cells, then inscribe a maximum possible circle into each cell. This can be done with the following script (warning: SLOW! as it is brute-force).
```
"""
in vertices_in v
in faces_in s
out centers_out v
out radiuses_out s
"""

from itertools import combinations
import numpy as np

from mathutils import Vector, Matrix
from mathutils.geometry import intersect_line_sphere_2d

from sverchok.data_structure import zip_long_repeat
from sverchok.utils.geom import CircleEquation2D, PlaneEquation, LineEquation2D, Triangle, CircleApproximationData
from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata

def to_3d(v):
    return Vector((v[0], v[1], 0))

centers_out = []
radiuses_out = []
for vertices, faces in zip_long_repeat(vertices_in, faces_in):
    vertices = [(x,y,0) for x,y,z in vertices]
    bm = bmesh_from_pydata(vertices, [], faces, normal_update=True)
    new_circles = []

    for bm_face in bm.faces:
        if len(bm_face.edges) == 3:
            circle = Triangle(bm_face.verts[0].co, bm_face.verts[1].co, bm_face.verts[2].co).inscribed_circle()
            new_circles.append(circle)
            continue

        print("Check face #", bm_face.index)
        face_center = bm_face.calc_center_median()
        face_plane = PlaneEquation.from_normal_and_point(bm_face.normal, face_center)
        fp_v1, fp_v2 = face_plane.two_vectors()
        fp_v1, fp_v2 = fp_v1.normalized(), fp_v2.normalized()
        face_plane_matrix = Matrix([fp_v1, fp_v2, face_plane.normal]).to_4x4()
        face_plane_matrix.translation = face_center
        face_plane_matrix_inv = face_plane_matrix.inverted()

        def to_2d(v):
            p = face_plane_matrix @ v
            return Vector((p[0], p[1]))

        def touches_edge(circle, edge, line):
            center = Vector(circle.center)
            line_vector = line.direction
            dv1 = to_2d(edge.verts[0].co) - Vector((center[0], center[1]))
            dv2 = to_2d(edge.verts[1].co) - Vector((center[0], center[1]))
            sign1 = line_vector.dot(dv1) > 0
            sign2 = line_vector.dot(dv2) > 0
            return sign1 != sign2

        def intersects_edge(circle, edge):
            center = Vector(circle.center)
            radius = circle.radius
            p1, p2 = intersect_line_sphere_2d(to_2d(edge.verts[0].co), to_2d(edge.verts[1].co), center, radius, True)
            return (p1 is not None) or (p2 is not None)

        candidate_circles = []
        for e1, e2, e3 in combinations(bm_face.edges, 3):
            print("Check edges:", e1.index, e2.index, e3.index)
            line1 = LineEquation2D.from_two_points(to_2d(e1.verts[0].co), to_2d(e1.verts[1].co))
            line2 = LineEquation2D.from_two_points(to_2d(e2.verts[0].co), to_2d(e2.verts[1].co))
            line3 = LineEquation2D.from_two_points(to_2d(e3.verts[0].co), to_2d(e3.verts[1].co))

            t1 = line1.intersect_with_line(line2)
            t2 = line2.intersect_with_line(line3)
            t3 = line1.intersect_with_line(line3)
            if t1 is None or t2 is None or t3 is None:
                continue

            circle_on_plane = Triangle(to_3d(t1), to_3d(t2), to_3d(t3)).inscribed_circle()
            print("Cp:", face_plane_matrix_inv @ Vector(circle_on_plane.center), circle_on_plane.radius)
            if not (touches_edge(circle_on_plane, e1, line1) and touches_edge(circle_on_plane, e2, line2) and touches_edge(circle_on_plane, e3, line3)):
                print("doesn't touch edges")
                if e1.verts[1] == e2.verts[0] and e2.verts[1] == e3.verts[0]:
                    e1v = (to_2d(e1.verts[1].co) - to_2d(e1.verts[0].co)).normalized()
                    e2v = (to_2d(e2.verts[1].co) - to_2d(e2.verts[0].co)).normalized()
                    e3v = (to_2d(e3.verts[1].co) - to_2d(e3.verts[0].co)).normalized()
                    bisect1v = - e1v + e2v
                    bisect2v = e3v - e2v
                    bisect1 = LineEquation2D.from_direction_and_point(bisect1v, to_2d(e1.verts[1].co))
                    bisect2 = LineEquation2D.from_direction_and_point(bisect2v, to_2d(e2.verts[1].co))
                    center = bisect1.intersect_with_line(bisect2)
                    if center is not None:
                        print("C:", face_plane_matrix_inv @ to_3d(center))
                        radius = line2.distance_to_point(center)
                        circle_on_plane = CircleApproximationData()
                        circle_on_plane.center = np.array([center[0], center[1], 0])
                        circle_on_plane.radius = radius
                        circle_on_plane.normal = np.array([0, 0, 1.0])
                        if not (touches_edge(circle_on_plane, e1, line1) and touches_edge(circle_on_plane, e2, line2) and touches_edge(circle_on_plane, e3, line3)):
                            print("that doesn't touch either")
                            continue
                    else:
                        continue
                else:
                    continue
                        
            has_intersection = False
            for edge in bm_face.edges:
                if edge in {e1, e2, e3}:
                    continue
                if intersects_edge(circle_on_plane, edge):
                    has_intersection = True
                    break

            if has_intersection:
                continue

            circle = CircleApproximationData()
            circle.center = face_plane_matrix_inv @ Vector(circle_on_plane.center)
            circle.radius = circle_on_plane.radius #* face_plane_matrix.determinant()
            circle.normal = np.array(face_plane.normal)
            candidate_circles.append(circle)

        if candidate_circles:
            max_circle = max(candidate_circles, key = lambda c: c.radius)
            print("Selected: ", max_circle.center, max_circle.radius)
            new_circles.append(max_circle)

    bm.free()

    new_centers = [tuple(c.center) for c in new_circles]
    new_radiuses = [c.radius for c in new_circles]
    centers_out.append(new_centers)
    radiuses_out.append(new_radiuses)
```
![Screenshot_20200227_010410](https://user-images.githubusercontent.com/284644/75382850-16c1ef00-58fd-11ea-9909-2944b6ccdfe4.png)

**Comment by zeffii** [comment]
answered?
