### ISSUE TITLE
Latest Box node produce inverted side face

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2894]
In the latest SVerchok update, I noticed the Box node is generating box mesh with side faces facing inward. Top and bottom face seems ok.

<img width="523" alt="Screen Shot 2020-02-23 at 10 56 01 am" src="https://user-images.githubusercontent.com/3952687/75101083-46d26f00-562b-11ea-8139-dc059d22b428.png">

**Comment by vicdoval** [comment]
Thanks for reporting @enzyme69 😄 
Fixed via #2897
