### ISSUE TITLE
Assigning Random Material Into An Object With Many Islands Without Separating

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2896]
SV-peeps, Is there a way we can "generate list of materials" without having to manually make the list and without having to separate "an object with many islands"?

<img width="1098" alt="Screen Shot 2020-02-23 at 10 44 42 pm" src="https://user-images.githubusercontent.com/3952687/75111466-3b645f80-568e-11ea-8248-2ae05242b6d6.png">

[assigning_material_into_an_object_002.blend.zip](https://github.com/nortikin/sverchok/files/4241165/assigning_material_into_an_object_002.blend.zip)

**Comment by enzyme69** [comment]
If I were to separate them as each individual objects, then assigning material per object works, but then it takes that extra processing time?

<img width="1680" alt="Screen Shot 2020-02-23 at 10 58 28 pm" src="https://user-images.githubusercontent.com/3952687/75111602-0d801a80-5690-11ea-8fa4-6f6c80951ba2.png">

If only we could just assign to the face of a single object...?

**Comment by zeffii** [comment]
do you really want individual materals per "island" ? or just want to colour each island differently. Because: 
- the shader tree now can output a random value for each island (super fast)
- on top of that.. i added a feature the the N panel to set the Vertex Colours uniformly per Island (slow..ish for large geometry)

**Comment by enzyme69** [comment]
Hi @zeffii just wanting to assign material per object (without separating) for now. But you are right on ability to randomly assign material per face.

**Comment by zeffii** [comment]
what i suggested doesn't require separating the object into islands. If they object has islands, it will still do the right think for `SvCol`.

**Comment by enzyme69** [comment]
If I were to manually assigning:
<img width="505" alt="Screen Shot 2020-02-23 at 11 14 24 pm" src="https://user-images.githubusercontent.com/3952687/75111831-3bfef500-5692-11ea-9aeb-7c35bfb60885.png">

**Comment by enzyme69** [comment]
It's "Assign Material List" that's currently I found too manual.

**Comment by zeffii** [comment]
ok i understand that.. but have you tried using "Vertex Color Per Island" ? it requires only one Material. and you use Vertex Colors to compose your colors.

**Comment by enzyme69** [comment]
🤔 Vertex Color Per Island of Cycles? I have not looked into that.

**Comment by enzyme69** [comment]
Like this and bake, is one solution, I supposed.
<img width="594" alt="Screen Shot 2020-02-23 at 11 40 20 pm" src="https://user-images.githubusercontent.com/3952687/75112233-e0366b00-5695-11ea-9f1d-209c7beda93c.png">

I guess we cannot do it for now?

**Comment by zeffii** [comment]
bmeshviewer has an N panel feature, to make vertex colours per island.  so iguess that works with eevee and cycles

**Comment by zeffii** [comment]
but at the moment, without changing the Assign Material Node, yes.. there is no way to do that procedurally, except of course... using SNLite or something.

**Comment by zeffii** [comment]
actually... the BMV node does have a socket for Material Index (which i have not used yet) .. so @portnov  what can @enzyme69  do with that? :)

**Comment by portnov** [comment]
It expects an index of the material in the list of materials assigned to the object. But that list has to be assigned somehow, with "assign material" node or in other way.

**Comment by Durman** [comment]
I think that assigning a lot of materials ot an object is unnatural for Blender and Sverchok should avoid such approaches.
![image](https://user-images.githubusercontent.com/28003269/72244444-b6564700-3607-11ea-8662-51727aaddfb4.png)

**Comment by portnov** [comment]
Agreed. Usually in Blender you use vertex colors or smth like that instead.

**Comment by enzyme69** [comment]
Noted, thanks all!

**Comment by Durman** [comment]
![2020-02-25_19-25-43](https://user-images.githubusercontent.com/28003269/75261554-acc61e80-5804-11ea-86ef-6d01c5c5c64f.png)

**Comment by enzyme69** [comment]
@Durman I KNOW IT!! This is possible and potentially can be used for weighting too right? Like assigning bone into part islands of 3D mesh, based on this indexing! Thanks so much!!

**Comment by enzyme69** [comment]
![IMG_1253](https://user-images.githubusercontent.com/3952687/75303829-f448bb00-5895-11ea-93d1-22fb7f52d700.JPG)
