### ISSUE TITLE
Object ID Out (Post Modifier) does not quite work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2900]
Objects In (Post Modifier) can source the mesh data, post modifiers.

But Objects ID Out (Post Modifier) does not seem to do the job.

<img width="1053" alt="Screen Shot 2020-02-25 at 10 03 06 pm" src="https://user-images.githubusercontent.com/3952687/75241730-c5413380-581a-11ea-8b30-e2a23f95be3b.png">

[sv_closest_edge_test_004.blend.zip](https://github.com/nortikin/sverchok/files/4249622/sv_closest_edge_test_004.blend.zip)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/nodes/scene/blenddata_to_svdata2.py
will require some massaging.

no ETA.

**Comment by zeffii** [comment]
it would help us out if you tried the branch

https://github.com/nortikin/sverchok/pull/2901

**Comment by zeffii** [comment]
let us know how it goes.
