### ISSUE TITLE
Face Index Scrambled (every frame) when Bevel Modifier applied

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2903]
[frame_changes_index_002.blend.zip](https://github.com/nortikin/sverchok/files/4254962/frame_changes_index_002.blend.zip)

I am doing something that involves List Masking and Index To Mask, somewhat Blender Bevel 

Modifier seems to affect the sorting index of the face when frame updated. Strange right?

(screenshot by Zeffii better)

**Comment by zeffii** [comment]
@enzyme69  y u no can make better screenshots m8.

![image](https://user-images.githubusercontent.com/619340/75342130-180c0100-5896-11ea-9f64-6a2d15ce686f.png)

**Comment by enzyme69** [comment]
@zeffii I apologize. Yes, so basically as soon I assign bevel modifier, and run the keyframe, the face index scrambled itself, every frame.

**Comment by zeffii** [comment]
initially when i scrub the timeline / or use kb shortcut, yes..the object's indices change.

but any time we convert our data to `bmesh` (for use in bmesh.ops(...) ) the face and edge indices are unstable.

**Comment by enzyme69** [comment]
I tested without Bevel Modifier, just Viewer Draw, and bake, and switching frame also trigger this weird face index changes.

**Comment by zeffii** [comment]
yep, the problem is not those things. the problem is the "non deterministic" bmesh conversion. I feel i've described this before..

**Comment by zeffii** [comment]
this is why when you "hardcode" index selection using List Input, in a section of the nodetree that is downstream from a node that uses `bmesh` internally for ops, you will get unpredictable results eventually.

**Comment by Durman** [comment]
I don't know, but if to replace `extrude` nodes by `inset faces` nodes, there is no any trouble with order of the geometry. `Inset faces` node also uses bmesh operators. Probably there is problem in implementation of extrude node.
[frame_changes_index_002.zip](https://github.com/nortikin/sverchok/files/4256404/frame_changes_index_002.zip)

**Comment by enzyme69** [comment]
Will take note on this~ Cheers all~
