### ISSUE TITLE
Mesh instancer 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2904]
Mesh instancer mk 2 or mesh instancer or  duplifaces  can this be used to use objects random from a collection  etc.... or works this only with one object

**Comment by zeffii** [comment]
## Instancer MK2 

from what I understand about the implementation of `instancer_mk2`, is that it will loop though all objects and start from the beginng and continue looping untill all matrices are exhausted.
```
input = [obj1, obj2, obj3]
matrices = [m1, m2, m3, m4, m5 m6, m7]

m1->obj1
m2->obj2
m3->obj3
m4->obj1
m5->obj2
m6->obj3
m7->obj1
```

you could randomize the incoming matrices, and it would be just as random as if the node had the ability to randomly select an object to instance. 

## Mesh Instancer

no such features.

## duplifaces

this node currently can only pick one object/mesh

**Comment by zeffii** [comment]
but for duplifaces it's conceivable that with a bit of codeshuffle - internally the base object could be split into n baseobjects, all of which will get one type of object duplied onto it's faces/verts.

but you could do it more manually by splitting up the object before hitting BMviewer, then adding multiple dupliface nodes (one for each object in the output list of BMViewer) ...

**Comment by BennyGovaerts** [comment]
The mesh instancer MK2 works for example like this : 
![image](https://user-images.githubusercontent.com/49908008/75399704-3d802580-58fd-11ea-9e75-09b910707ccb.png)

**Comment by zeffii** [comment]
@BennyGovaerts  yes, so if you are passing a list of matrices, the order in which the objects are used is predictable (as shown above), so you could randomize the matrix list and that will produce the effect "optically", while unfortunately loosing the original order of the matrices.

We could add a mode to pick objects at random for each new matrix. by rewriting this:
```python
            combs = zip(objects * len(matrices), matrices)
            for obj_index, comb in enumerate(combs):
                obj_name = f'{self.basedata_name}.{obj_index:04d}'
                make_or_update_instance(self, obj_name, comb[1], comb[0])
```
to
```python

            if self.pick_at_random:
                combinations = ...
            else:
                combinations = ...
            
            for obj_index, (blueprint, matrix) in enumerate(combinations):
                obj_name = f'{self.basedata_name}.{obj_index:04d}'
                make_or_update_instance(self, obj_name, matrix, blueprint)


```

**Comment by zeffii** [comment]
@willneedit   what do you think? :)

**Comment by zeffii** [comment]
something like this? https://github.com/nortikin/sverchok/pull/2906

**Comment by zeffii** [comment]
untested :)

**Comment by zeffii** [comment]
@BennyGovaerts  

> objects random from a collection

you mean literally from a collection, like pointing a node at a collection and then using that as the object list. ?

**Comment by zeffii** [comment]
- we would need a node that is aware of "Collections" in the scene, and from that output a list of the associated objects. (we need such a node anyway)

we don't have a collections socket, and i'm not sure it's a good idea to implement that at the moment.

**Comment by BennyGovaerts** [comment]
Option 1 ; Sequence
Option 2 : Pick random , 

A better solution could be the same options like you have with particles , but with all the new things with blender hmm maybe not so easy to maintenance...

![image](https://user-images.githubusercontent.com/49908008/75497485-a5e60a00-59c4-11ea-9139-c476a2b304f5.png)

**Comment by Durman** [comment]
Why just don't use `random numbers` and `item` nodes?

**Comment by BennyGovaerts** [comment]
Excellent idea with the item node but i think this is not working with Mesh instancer MK2 , do you have a example how i can set this up ?

**Comment by Durman** [comment]
![2020-02-28_18-54-10](https://user-images.githubusercontent.com/28003269/75558882-e9d81e00-5a5b-11ea-803d-2877be46e7f8.png)
[untitled5_2020_02_28_14_54.zip](https://github.com/nortikin/sverchok/files/4267612/untitled5_2020_02_28_14_54.zip)
But the `mesh instance` node is really buggy

**Comment by BennyGovaerts** [comment]
Yeah sometimes the output is not update etc...., do you have the same problem , or works this better with blender 2.82 ....

**Comment by zeffii** [comment]
@willneedit  you are MIA so i will take control of MK2.

**Comment by zeffii** [comment]
i'll make a collection picker

**Comment by zeffii** [comment]
i'd like to hear some opinions on the following..

the node is called "Mesh Instancer", but with minor changes it could instance any Blender object (empty , lights... Collections even... )

at the moment, the node expects objects of type mesh, and only "cleans up" such types, so if you include lights/empties/nurbs in the input, those are created initially, but never removed.

**Comment by vicdoval** [comment]
I would change it to "Instancer" but im not shure if I would just update the node or move the mk2 to old nodes and and the typical replace operator...

**Comment by zeffii** [comment]
because instancer mk2 is so new, i'm going to not go through the effort of doing mk3 or adding replace stuff.

**Comment by zeffii** [comment]
i want to get back to coding.. and less tiptoeing around.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2914

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2916 committed to master.

I think addresses some major usecases.

**Comment by zeffii** [comment]
closing, bug reports welcome.  but please describe the situation. so i can recreate
