### ISSUE TITLE
Vector math and blender 2.83.5 Always crash

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2911]
Vector math and blender 2.83.5 Always crash

**Comment by zeffii** [comment]
Using Blender 2.83+ you must use a different version of Sverchok for 2.83 at the moment.

https://github.com/nortikin/sverchok/pull/2895

stuff will break. Blender devs changed some API.

**Comment by zeffii** [comment]
this is a massive pain in the butt btw.

**Comment by zeffii** [comment]
files (blends) will not be forward or backward compatible with 2.82->2.83->2.82  btw.
