### ISSUE TITLE
Object ID type Lamp is probably broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2920]
I am trying to use Object ID Lamp and make changes to Color and Energy, but it does not seem to work...

<img width="752" alt="Screen Shot 2020-03-01 at 9 21 34 pm" src="https://user-images.githubusercontent.com/3952687/75623866-bbe10e00-5c02-11ea-920f-5c31cdb955ce.png">

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/599e5ae64024b6582f476da5a9526fdba60479b4

fixed
