### ISSUE TITLE
Crashing Blend when using Two BMesh Viewer that dependant on each other

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2928]
<img width="1680" alt="Screen Shot 2020-03-05 at 12 05 55 pm" src="https://user-images.githubusercontent.com/3952687/75937692-cf79c680-5ed9-11ea-98c5-b6ab583cec46.png">

[svcloth_006.blend.zip](https://github.com/nortikin/sverchok/files/4290394/svcloth_006.blend.zip)

<img width="827" alt="Screen Shot 2020-03-05 at 12 07 11 pm" src="https://user-images.githubusercontent.com/3952687/75937716-e0c2d300-5ed9-11ea-91db-a452f679a697.png">

**Comment by enzyme69** [comment]
Can be seen near the end of the video:
https://www.youtube.com/watch?v=V58T99bZTbA

The Blend that is saved with:
Object A = bmesh viewer out
Object B = take object A and Bmesh View Out

Crashes..

**Comment by Durman** [comment]
How do you expect this should work? 
Do you know that updating of different disjoint node nets are unordered in Sverchok? So Sverchok can update `mesh in` node first of all other nodes in your example.

**Comment by enzyme69** [comment]
Let see...

I have Object A being generated by SV on the fly. Object A assigned modifiers, in this case cloth object -> say this is intermediate Object AB. I want to use the Post Modifier of AB as Object B.

I have another node, Object B, which takes Object AB, and I actually like this to duplicate or bake and store it as Object C, D, E, F, etc... when timeline reaches the end. I do this manually.

Anyways, the issue is BLEND file crashing and can no longer be opened, unless I maybe use back door method, Append.

**Comment by zeffii** [comment]
> Do you know that updating of different disjoint node nets are unordered in Sverchok?
we could make a mode to update disjoint sets as a function of their left most node's `.x` coordinate, we did some of the work for that already several years ago.

also @enzyme69  , in your first image what would be the ultimate purpose of reading the object data back into sverchok ?
```
tree -> BMV Alpha                   obj in ( picks up Alpha.0001 ) -> BMV Beta
``
remember i also added dependency graph lookup to the object ID node, ( https://github.com/nortikin/sverchok/commit/eba9e7c41af0c45e5ec42cd7206ad0ad1bfcb0c1 ) so the data doesn't even have to leave sverchok.  no disjoint nodes sets.

**Comment by Durman** [comment]
For restoring your files try next: 
- open blender and switch off all 3d view screens
- open your file without UI layout
- delete `object in` node before anything else.

**Comment by zeffii** [comment]
order of subgraph update : https://github.com/nortikin/sverchok/issues/847

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/core/update_system.py#L383

we can sort the list of sets by x location of first node : )

**Comment by zeffii** [comment]
in your demo file you have the falled cubes on the plane, their name is `Beta.000 ... 005` , i recommend never to have a objects in a scene called `Beta.000` if you have a BMViewer that's outputting `Beta.0000`. it will lead to confusion.

**Comment by zeffii** [comment]
```
    found_node_sets = [ns for ns in node_set_list if len(ns) > 1]
    sort_component = 'x'  # ["x", "y", "None"]
    
    if sort_component == 'x':
        print(found_node_sets)
        find_lowest_coordinate = lambda ns: min(ng.nodes[n].location.x for n in ns)
        found_node_sets = sorted(found_node_sets, key=find_lowest_coordinate)
        print(found_node_sets)

    return found_node_sets
```

**Comment by zeffii** [comment]
maybe @portnov @Durman  https://github.com/nortikin/sverchok/pull/2929

**Comment by zeffii** [comment]
since i've added `node.absolute_location` to the `sv node common` class, i'm tempted to make the absolute x location sorting of the disjoint sets the default (if sorting is turned on)

but if i don't get any replies here soon, i'm going to consider it a non-issue, and push it anyway.

**Comment by zeffii** [comment]
well, i can't make it crash under acceptable circumstances.

![image](https://user-images.githubusercontent.com/619340/76263361-f845e700-625e-11ea-92e3-3ca1a065a99f.png)

i've added a few modes to the Evaluation direction "chain" 
  - lets you pick X or Y to first evaluates those subgraphs that have a node with the lowest X or Y coordinate
 - None , is the current "random"/"hash" behaviour

i'll restate that you should not have objects in the scene that have the same names before the `<name>.000` , bmesh node is not guaranteed to like that.
