### ISSUE TITLE
animated recursive subdiv

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2946]
based on https://www.youtube.com/watch?v=GhquYJ9m1Oc

i was asked if that was easy in Sverchok..

![image](https://user-images.githubusercontent.com/619340/76306408-1c3d1300-62c7-11ea-89a1-8ce3d606288c.png)

well, i think for 5 minutes work..
```python
"""
in quad_verts v
in quad_faces s
in noise s d=1.2 n=2
in iterations s d=3 n=2
in X s d=0.4 n=2
in Y s d=0.4 n=2
out verts v
out faces s
"""

from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
sort = lambda vex, pox: [vex[i] for i in pox]

verts_out, faces_out = [], []
new_quad = faces_out.append

pts = sort(quad_verts[0], quad_faces[0][0])

pos_a = lerp(pts[0], pts[1], Y)
pos_b = lerp(pts[1], pts[2], X)
pos_c = lerp(pts[3], pts[2], 1-Y)
pos_d = lerp(pts[0], pts[3], X)
pos_e = lerp(pos_d, pos_b, Y)
pos_f = lerp(pos_d, pos_b, 1-Y)

# indices = 0, 1, 2, 3
verts_out.extend(pts)  

# indices =       4,     5,     6,     7,     8,     9
verts_out.extend([pos_a, pos_b, pos_c, pos_d, pos_e, pos_f])

new_quad([0, 4, 8, 7])
new_quad([4, 1, 5, 8])
new_quad([5, 2, 6, 9])
new_quad([7, 9, 6, 3])
faces.append(faces_out)
verts.append(verts_out)
```
the initial step is not hard.

**Comment by vicdoval** [comment]
In 5 more minutes...
![image](https://user-images.githubusercontent.com/10011941/76315748-9d9da100-62d9-11ea-994b-8a39e7d2d8c1.png)

**Comment by enzyme69** [comment]
Lack of brain 🧠 algorithm way. I spent 5 minutes grease pencil to do this... 😆 

<img width="1057" alt="Screen Shot 2020-03-11 at 12 20 09 am" src="https://user-images.githubusercontent.com/3952687/76316129-2514ff80-632e-11ea-97ad-766cd2f90e18.png">

**Comment by BennyGovaerts** [comment]
More inspirations what you can make with this :https://www.behance.net/gallery/79138129/Scaler

**Comment by zeffii** [comment]
nice @vicdoval 
here @BennyGovaerts 
[jungle_primifun_2020_03_10_13_52.zip](https://github.com/nortikin/sverchok/files/4312757/jungle_primifun_2020_03_10_13_52.zip)

**Comment by BennyGovaerts** [comment]
> nice @vicdoval
> here @BennyGovaerts
> [jungle_primifun_2020_03_10_13_52.zip](https://github.com/nortikin/sverchok/files/4312757/jungle_primifun_2020_03_10_13_52.zip)

Works this with blender 2.83 for the monad etc....

**Comment by zeffii** [comment]
yes

**Comment by zeffii** [comment]
1. copy the path of that zip to your clipboard
2. start Blender 2.83, go to nodeview in sverchok, press f3 , type "UR" 
![image](https://user-images.githubusercontent.com/619340/76322003-16edc180-62e3-11ea-8a5b-4d391693849b.png)

**Comment by BennyGovaerts** [comment]
Maybe that works , but if you open the file then blender crash

**Comment by zeffii** [comment]
oh.. nasty.

**Comment by zeffii** [comment]
can confirm..

**Comment by BennyGovaerts** [comment]
Do you think that you can fix this problem with the monad/scripted node etc...

**Comment by zeffii** [comment]
ofcourse i'll look into it (or someone else).  that shouldn't happen.

i don't really use nested Monads.

**Comment by BennyGovaerts** [comment]
With f3 same problem , blender crash

**Comment by zeffii** [comment]
the .blend stores all the right data, but for some reason there's a race-condition failure where Monad.000 is looking for Monad.001 before its "created in memory".   I think..

**Comment by BennyGovaerts** [comment]
And , i have no idea how i can random inset the faces , with this type off setup 

![image](https://user-images.githubusercontent.com/49908008/76323953-a8f6c980-62e5-11ea-97d1-a0be2c10859a.png)

**Comment by BennyGovaerts** [comment]
i see you have used mesh join in your setup

**Comment by BennyGovaerts** [comment]
And we need a split to assign random colors

**Comment by zeffii** [comment]
"mesh join" preserves islands, it does no merging.

**Comment by zeffii** [comment]
https://gist.github.com/7e0d0e6d58222a5bd723e33a46953977

hmmm. the gist almost stores it right...

**Comment by zeffii** [comment]
[strokes_2020_03_10_21_25.zip](https://github.com/nortikin/sverchok/files/4314860/strokes_2020_03_10_21_25.zip)

**Comment by zeffii** [comment]
i may have introduced a bug in snlite's error handling the other day during a quick code reshuffle for the Error Message display stuff (drawing bgl to the node). This can be undone easily, but it will be tomorrow probably.

**Comment by zeffii** [comment]
or maybe... just maybe the `gist io` is making bpy.data.text.new() trigger an sverchok update. in 
storage_set_data(self, node_ref):

**Comment by BennyGovaerts** [comment]
> https://gist.github.com/aa8e23ce18bb4a39e9d396fdd2ab136b
> hmmm. the gist almost stores it right...

.json file works 
![image](https://user-images.githubusercontent.com/49908008/76363449-576d2f80-6323-11ea-9666-19ef67b14132.png)

**Comment by zeffii** [comment]
@BennyGovaerts  the Merge option on the BMV is like the `Mesh Join` node . I don't think the Polygon Boom node is achieving what you think . 

either way. i think this does answer your question; the recursive subdivision is doable

-----
closing for now, and looking at fixes for the encountered issues

**Comment by zeffii** [comment]
this is a slightly different more "defensive" snlite script that autogenerates incoming mesh data, until input sockets are connected to it.  https://gist.github.com/48a3f7570416ec868ce47e1b3bdcf9b8  (this may also not load..)

**Comment by zeffii** [comment]
now the error is down to
```
2020-03-11 10:59:31,348 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
2020-03-11 10:59:31,366 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
2020-03-11 10:59:31,380 [INFO] sverchok.utils.sv_IO_panel_tools: ############0.079
sockets wiped, skipped update
sockets wiped, skipped update
0 ('SvVerticesSocket', 'quad_verts', None, None)
1 ('SvStringsSocket', 'quad_faces', None, None)
2 ('SvStringsSocket', 'noise', 1.2, 2)
3 ('SvStringsSocket', 'iterations', 3, 2)
4 ('SvStringsSocket', 'X', 0.4, 2)
5 ('SvStringsSocket', 'Y', 0.4, 2)
sockets wiped, skipped update
sockets wiped, skipped update
KeyError('bpy_struct[key]: key "current_index" not found')
couldn't find monad info


```

**Comment by zeffii** [comment]
https://gist.github.com/3dec539a7a8ebeed1597bcab8afc9a23 i've supressed some errors, but Vectorize and Looped states are not collected by iojson.

**Comment by BennyGovaerts** [comment]
.json works with monad , but if you save the blend file and reopen it with blender then blender crash

**Comment by zeffii** [comment]
i did yet another update to sverchok's iojson, which "truely" fixes the import problem. (it sets loops/vectorize properties correctly now.. )

**Comment by zeffii** [comment]
it does not solve the .blend crash tho...

**Comment by enzyme69** [comment]
I am trying to digest what is happening here, but basically monad crashing maybe because of script node...

Up to here still works, until I try to monad those nodes inside the frame. Don't know what @vicdoval did but I am sure his blend also crashes when opened. I use Append instead...

<img width="1071" alt="Screen Shot 2020-03-12 at 4 03 32 pm" src="https://user-images.githubusercontent.com/3952687/76488945-1f790000-647b-11ea-9578-e7bfe47e8b3f.png">


[test_monad_sub_006.blend.zip](https://github.com/nortikin/sverchok/files/4322346/test_monad_sub_006.blend.zip)

**Comment by enzyme69** [comment]
This does not solve why the blend is crashing, but I often think that maybe SV needs some kind of "baker". A node that can bake out a new mesh duplicate, for every frame update.

<img width="770" alt="Screen Shot 2020-03-12 at 4 06 57 pm" src="https://user-images.githubusercontent.com/3952687/76489085-80a0d380-647b-11ea-9516-755a12c4a8f3.png">

**Comment by enzyme69** [comment]
<img width="667" alt="Screen Shot 2020-03-12 at 4 22 38 pm" src="https://user-images.githubusercontent.com/3952687/76489870-b6df5280-647d-11ea-831e-fa94c0a6f3a5.png">

I "manually" bake 500 suzanne face, I realized it works on Quad only, so that's ok, I got hole, but I made above design. I should have used Cricket.

**Comment by zeffii** [comment]
here's an alternative snlite script, which autowinds the quads, in random order.
```python
"""
in quad_verts v
in quad_faces s
in noise s d=1.2 n=2
in iterations s d=3 n=2
in X s d=0.4 n=2
in Y s d=0.4 n=2
out verts v
out faces s
"""
import random
from random import shuffle, randint
from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
sort = lambda vex, pox: [vex[i] for i in pox]

verts_out, faces_out = [], []
new_quad = faces_out.append

pts = sort(quad_verts[0], quad_faces[0][0])
pos_a = lerp(pts[0], pts[1], Y)
pos_b = lerp(pts[1], pts[2], X)
pos_c = lerp(pts[3], pts[2], 1-Y)
pos_d = lerp(pts[0], pts[3], X)
pos_e = lerp(pos_d, pos_b, Y)
pos_f = lerp(pos_d, pos_b, 1-Y)

# indices = 0, 1, 2, 3
verts_out.extend(pts)  

# indices =       4,     5,     6,     7,     8,     9
verts_out.extend([pos_a, pos_b, pos_c, pos_d, pos_e, pos_f])

def rotate(l, n): return l[n:] + l[:n]

def randomize_quad_order(quad_list):
    random.shuffle(quad_list)

def randomize_quad_wind(quad_list):
    return [rotate(quad, randint(0, 4)) for quad in quad_list]

quad_list = [[0, 4, 8, 7], [4, 1, 5, 8], [5, 2, 6, 9], [7, 9, 6, 3]]
randomize_quad_order(quad_list)
q1, q2, q3, q4 = randomize_quad_wind(quad_list)

new_quad(q1)
new_quad(q2)
new_quad(q3)
new_quad(q4)

faces.append(faces_out)
verts.append(verts_out)
```
ofcourse, less than optimal :)

**Comment by zeffii** [comment]
[jungle_primifun_2020_03_13_09_52.zip](https://github.com/nortikin/sverchok/files/4328854/jungle_primifun_2020_03_13_09_52.zip)

reloading the script does work from inside the monad, but the kb shortcut i think doesn't.. tell the outer nodetree to update

**Comment by BennyGovaerts** [comment]
1).  New script works with Updated sverchok  
2).  Open Blend file works with Updated sverchok & file : Jungle_primifun_2020_03_09_52 
3).  .json file import works fine ( do not use append nodetree etc... ) 
4).  Manual add new socket inputs and manual choose a name for the inputs works 
5).  
![image](https://user-images.githubusercontent.com/49908008/76683557-5844e080-6605-11ea-908b-76a7cc92a3e8.png)

6). If you use play then the Pattern change , this is a nice option:
    But yeah  is there maybe a easy solution to set this on/off  if i need this ? 

7). For Blender 2.83.8 & Updated Sverchok : 
[Divider_with_inputs.zip](https://github.com/nortikin/sverchok/files/4332884/Divider_with_inputs.zip)

**Comment by zeffii** [comment]
it is possible to set `random.seed(<some number>)`  somewhere at the top of the `script`, and that should make all future calls to random follow a predictable pattern.

```diff
"""
in quad_verts v
in quad_faces s
+ in seed_in s d=20 n=2
- in noise s d=1.2 n=2
- in iterations s d=3 n=2
in X s d=0.4 n=2
in Y s d=0.4 n=2
out verts v
out faces s
"""
import random
from random import shuffle, randint
from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
sort = lambda vex, pox: [vex[i] for i in pox]

+ random.seed(seed_in)
verts_out, faces_out = [], []
new_quad = faces_out.append

... snipped ...
```

**Comment by zeffii** [comment]
and then you would change the random process by feeding it a different value into `seed_in`

**Comment by Durman** [comment]
It would be nice to implement this algorithm with `bmesh` data structure for creating continuous mesh without disjoint parts. 

I think with this tools: https://docs.blender.org/api/current/bmesh.utils.html

and according this description: https://wiki.blender.org/wiki/Source/Modeling/BMesh/Design#Euler_Function_Reference

it would become possible to do.

**Comment by zeffii** [comment]
>  implement this algorithm with bmesh data structure for creating continuous mesh without disjoint parts.

yeah, but it's more work :)  good practice for anyone interested in these things.

**Comment by Durman** [comment]
My most interest is developing Numpy Mesh conception now. Probably someone else will be interested.

**Comment by vicdoval** [comment]
![image](https://user-images.githubusercontent.com/10011941/76689152-56921180-6633-11ea-8ba2-ef4c97996b36.png)

```
"""
in quad_verts v
in quad_faces s
in seed s d=1 n=2
in random_factor s d=0.1 n=2
in iterations s d=1 n=2
out verts v
out faces s
"""

from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
from sverchok.utils.sv_mesh_utils import mesh_join
from sverchok.nodes.modifier_change.remove_doubles import remove_doubles
import  random


sort = lambda vex, pox: [vex[i] for i in pox]

def random_subdiv_mesh(verts_m, pols_m, iteration):

    verts, faces =[],[]
    for pol in pols_m:
        verts_out, faces_out = [], []
        new_quad = faces_out.append

        pts = sort(verts_m, pol)
        X = 0.5 +(random.random() - 0.5) * random_factor
        Y = 0.5 +(random.random() - 0.5) * random_factor
        pos_a = lerp(pts[0], pts[1], Y)
        pos_b = lerp(pts[1], pts[2], X)
        pos_c = lerp(pts[3], pts[2], 1-Y)
        pos_d = lerp(pts[0], pts[3], X)
        pos_e = lerp(pos_d, pos_b, Y)
        pos_f = lerp(pos_d, pos_b, 1-Y)

        # indices = 0, 1, 2, 3
        verts_out.extend(pts)  

        # indices =       4,     5,     6,     7,     8,     9
        verts_out.extend([pos_a, pos_b, pos_c, pos_d, pos_e, pos_f])

        new_quad([0, 4, 8, 7])
        new_quad([4, 1, 5, 8])
        new_quad([5, 2, 6, 9])
        new_quad([7, 9, 6, 3])
        faces.append(faces_out)
        verts.append(verts_out)
        
    verts, _, faces = mesh_join(verts, [],faces)
    if iteration <2 :
        return verts,faces
    else:
        return random_subdiv_mesh(verts, faces, iteration - 1)
    
if quad_verts and quad_faces:
    random.seed(seed)
    verts, faces = random_subdiv_mesh(quad_verts[0], quad_faces[0], iterations)  
    verts, _, faces, _, _ = remove_doubles(verts, faces, 1e-5, False)       
    verts =[verts]
    faces= [faces]
```

> of course, less than optimal :)

But maybe would be nice to add it to SNLite Templates

**Comment by zeffii** [comment]
do it @vicdoval  :)  i'd like to make a new category feature for snlite scripts.. so we can show more :)

**Comment by zeffii** [comment]
there will be 
- a shorter default list. (so people can see the trees through the forrests)  
- and a new section to the draw_buttons_ext panel with categories

**Comment by zeffii** [comment]
@vicdoval  feel free to add folders / snlite scripts

https://github.com/nortikin/sverchok/pull/2973  ,pushing for now.

**Comment by nortikin** [comment]
Other code inside templates and it produces not right
![Снимок экрана от 2020-04-21 23-19-23](https://user-images.githubusercontent.com/5783432/79909995-90221d80-8426-11ea-8527-01529eb38765.png)
left is in templates. right is on your comment
> ```
> """
> in quad_verts v
> in quad_faces s
> in seed s d=1 n=2
> in random_factor s d=0.1 n=2
> in iterations s d=1 n=2
> out verts v
> out faces s
> """
> 
> from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
> from sverchok.utils.sv_mesh_utils import mesh_join
> from sverchok.nodes.modifier_change.remove_doubles import remove_doubles
> import  random
> 
> 
> sort = lambda vex, pox: [vex[i] for i in pox]
> 
> def random_subdiv_mesh(verts_m, pols_m, iteration):
> 
>     verts, faces =[],[]
>     for pol in pols_m:
>         verts_out, faces_out = [], []
>         new_quad = faces_out.append
> 
>         pts = sort(verts_m, pol)
>         X = 0.5 +(random.random() - 0.5) * random_factor
>         Y = 0.5 +(random.random() - 0.5) * random_factor
>         pos_a = lerp(pts[0], pts[1], Y)
>         pos_b = lerp(pts[1], pts[2], X)
>         pos_c = lerp(pts[3], pts[2], 1-Y)
>         pos_d = lerp(pts[0], pts[3], X)
>         pos_e = lerp(pos_d, pos_b, Y)
>         pos_f = lerp(pos_d, pos_b, 1-Y)
> 
>         # indices = 0, 1, 2, 3
>         verts_out.extend(pts)  
> 
>         # indices =       4,     5,     6,     7,     8,     9
>         verts_out.extend([pos_a, pos_b, pos_c, pos_d, pos_e, pos_f])
> 
>         new_quad([0, 4, 8, 7])
>         new_quad([4, 1, 5, 8])
>         new_quad([5, 2, 6, 9])
>         new_quad([7, 9, 6, 3])
>         faces.append(faces_out)
>         verts.append(verts_out)
>         
>     verts, _, faces = mesh_join(verts, [],faces)
>     if iteration <2 :
>         return verts,faces
>     else:
>         return random_subdiv_mesh(verts, faces, iteration - 1)
>     
> if quad_verts and quad_faces:
>     random.seed(seed)
>     verts, faces = random_subdiv_mesh(quad_verts[0], quad_faces[0], iterations)  
>     verts, _, faces, _, _ = remove_doubles(verts, faces, 1e-5, False)       
>     verts =[verts]
>     faces= [faces]
> ```
> 
> > of course, less than optimal :)
> 
> But maybe would be nice to add it to SNLite Templates

**Comment by nortikin** [comment]
I'll add one from your comment with mk2 postfix
