### ISSUE TITLE
Clean install sverchok ( error ) 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#2952]
Blender 2.83.7 
- Remove old sverchok addon 
- Install update sverchok 
- Activate sverchok 
- Error 
![image](https://user-images.githubusercontent.com/49908008/76416244-fbde8880-639a-11ea-8728-38b15244c9c6.png)

Install back old version off sverchok this works but not the new  updated version

**Comment by zeffii** [comment]
why are you removing it first?  can't you just press "update"  ?

![image](https://user-images.githubusercontent.com/619340/76419279-59c19f00-63a0-11ea-8934-e1d2bef17879.png)

**Comment by BennyGovaerts** [comment]
Same problem - make no difference  , can not activate the addon , only with the older version

**Comment by zeffii** [comment]
is there any more to that error?

**Comment by BennyGovaerts** [comment]
After using the upgrade there is even no nodetree with sverchok anymore ...

**Comment by BennyGovaerts** [comment]
Blender 2.83.7 default factory settings etc. make no difference
![image](https://user-images.githubusercontent.com/49908008/76421170-8cb96200-63a3-11ea-991f-5d4520d35dcc.png)

**Comment by zeffii** [comment]
ok . i see, it's maybe something to do with the `exception drawing to nodeview`,

0_o

**Comment by zeffii** [comment]
can you start Blender from a terminal and copy/paste the entire error log?

**Comment by zeffii** [comment]
not a screenshot..

**Comment by zeffii** [comment]
i've just downloaded the latest nightly build, and uninstalled sverchok / reinstalled.  without a hitch..

**Comment by zeffii** [comment]
i can imagine some issue with `imports` not being available upon initialization of Sverchok, tho why that should happen on your system, but not mine is a source of confusion.  until i (or someone else) can reproduce the error and provide a full printout of the error i'm gonna take it easy,

**Comment by BennyGovaerts** [comment]
> can you start Blender from a terminal and copy/paste the entire error log?

How works this so that i can give you the right information ?

**Comment by zeffii** [comment]
what OS ?

**Comment by BennyGovaerts** [comment]
![image](https://user-images.githubusercontent.com/49908008/76427288-6a781200-63ac-11ea-8bc2-d340e1072ebc.png)

**Comment by zeffii** [comment]
wanna try something?

step 1 . 
 in `core/update_system.py` , at the top of the file look for 
```python
from sverchok.utils.exception_drawing_with_bgl import clear_exception_drawing_with_bgl
```
comment it out by sticking a `#` infront of it that whole line.
```diff
- from sverchok.utils.exception_drawing_with_bgl import clear_exception_drawing_with_bgl
+ #from sverchok.utils.exception_drawing_with_bgl import clear_exception_drawing_with_bgl
```

step 2
around like 300 (also in `update_system.py`) , comment out the line 

```python
        clear_exception_drawing_with_bgl(self.nodes)
```
also by adding `#` infront of it .. like 

```diff
-     clear_exception_drawing_with_bgl(self.nodes)
+     #clear_exception_drawing_with_bgl(self.nodes)
```

**Comment by zeffii** [comment]
on windows, luckily you to to  Blender -> Window -> Toggle System Console
I want everything there.

**Comment by BennyGovaerts** [comment]
[Sverchok_error.txt](https://github.com/nortikin/sverchok/files/4318870/Sverchok_error.txt)

**Comment by zeffii** [comment]
thanks @BennyGovaerts  - unfortunately it doesn't give me more information than you already provided in the screenshots.  but now I know that this is all the info i've got to work with .

i'll try a few things

**Comment by zeffii** [comment]
@portnov  any bright ideas?  i'm lost

**Comment by portnov** [comment]
Well.
What if you try other Blender build — newer or older one?

**Comment by portnov** [comment]
@zeffii 
https://github.com/nortikin/sverchok/issues/2952#issuecomment-597629458
shows a cyclic import: update_system imports exceptions_drawing_with_bgl, which imports bgl_callback_nodeview, which imports sverchok.node_tree, which imports update_system. The question is just why does not it reproduce each time you launch sverchok?!

**Comment by zeffii** [comment]
cool. i'll rip out the exception stuff to another place.

**Comment by zeffii** [comment]
i've ripped out the exception drawing @BennyGovaerts :  https://github.com/nortikin/sverchok/pull/2958

untill the snlite stuff is fixed anyway : )

**Comment by BennyGovaerts** [comment]
Excellent , clean install with sverchok or update works correct for the moment .

Thanks ,

Except :monad  snlite crash always

**Comment by zeffii** [comment]
yes i know.
