### ISSUE TITLE
lockdown blend files march 2020

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2974]
some educational .blends while we are in this situation

spiderweb basic
![image](https://user-images.githubusercontent.com/619340/76700443-ce098480-66b7-11ea-897b-3805d864a1a9.png)
[spider_net_2020_03_15_11_23.zip](https://github.com/nortikin/sverchok/files/4334098/spider_net_2020_03_15_11_23.zip)

**Comment by zeffii** [comment]
spiderweb basic 2
![image](https://user-images.githubusercontent.com/619340/76702068-2bf19880-66c7-11ea-98a7-0d3b528a3ac5.png)
[spiderweb2_2020_03_15_13_14.zip](https://github.com/nortikin/sverchok/files/4334246/spiderweb2_2020_03_15_13_14.zip)

**Comment by zeffii** [comment]
random trajectories v1, really stupid
![image](https://user-images.githubusercontent.com/619340/78261808-fe4a8300-74ff-11ea-87df-78854cd4a6c2.png)

[random_parabola_2020_04_02_14_36.zip](https://github.com/nortikin/sverchok/files/4421680/random_parabola_2020_04_02_14_36.zip)

**Comment by enzyme69** [comment]
"Anomaly" -- despite the weirdness of Adaptive Edge I still find this setup with Cylinder quite beautiful.

<img width="934" alt="Screen Shot 2020-04-04 at 12 26 43 pm" src="https://user-images.githubusercontent.com/3952687/78415747-a29f0780-766f-11ea-80aa-4f8d3e9973db.png">


[droopy_cylinder_002.blend.zip](https://github.com/nortikin/sverchok/files/4430568/droopy_cylinder_002.blend.zip)

**Comment by enzyme69** [comment]
<img width="491" alt="Screen Shot 2020-04-05 at 8 29 01 am" src="https://user-images.githubusercontent.com/3952687/78462667-88206900-7717-11ea-805a-e8cd33e24f81.png">
@zeffii With your parabola, can we have control of the direction of the curve parabola and the "droopiness"?

**Comment by zeffii** [comment]
corona cake
![image](https://user-images.githubusercontent.com/619340/78589174-12fc8300-7840-11ea-8126-24759ac33046.png)

https://gist.github.com/cb75de566f9075c2e27a9e6f2981b9f0
[abs_cos_twist3_2020_04_06_17_52.zip](https://github.com/nortikin/sverchok/files/4440003/abs_cos_twist3_2020_04_06_17_52.zip)

**Comment by enzyme69** [comment]
I hope my SVerchok skill has improved... Feels just yesterday when Nikitron says: "Are you afraid of Sverchok..?"

<img width="971" alt="Screen Shot 2020-04-07 at 1 04 26 pm" src="https://user-images.githubusercontent.com/3952687/78625863-7df59a80-78d0-11ea-9df4-296e57cd77e1.png">

[matrix_play_002.blend.zip](https://github.com/nortikin/sverchok/files/4441828/matrix_play_002.blend.zip)

**Comment by zeffii** [comment]
resampled spiral 

![image](https://user-images.githubusercontent.com/619340/79069127-035fbd00-7ccc-11ea-980b-a51cb4ac142a.png)

https://gist.github.com/e6c621de192c7a1764492adac0e7e603

**Comment by zeffii** [comment]
patchwork

![image](https://user-images.githubusercontent.com/619340/79080523-e94acc80-7d15-11ea-8eea-fee1f1e318b8.png)

https://gist.github.com/7cc8327ad129159a0b6bc8eccb4dce6e

also saw this in a twitter post first. forgot to link it.

**Comment by zeffii** [comment]
next one: 

https://twitter.com/divbyzero/status/1246839941780422656
![image](https://user-images.githubusercontent.com/619340/79104391-c8629580-7d6e-11ea-909f-21f0f768ebe0.png)
