### ISSUE TITLE
Connect Accum Lines

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2977]
<img width="967" alt="Screen Shot 2020-03-16 at 11 46 12 am" src="https://user-images.githubusercontent.com/3952687/76714569-d3300780-677b-11ea-8676-f39771745787.png">

Is there already SV nodes that can connect + accumulate bunch of "curves" ?

Like if we have a handful of curves, and we simply want to "attach" the end point into the first point of the next curve? 

I tried, but it was not pretty:

<img width="1155" alt="Screen Shot 2020-03-16 at 11 48 29 am" src="https://user-images.githubusercontent.com/3952687/76714605-0ffbfe80-677c-11ea-98b0-f91dbcc092d5.png">

[connecting_lines_001.blend.zip](https://github.com/nortikin/sverchok/files/4335577/connecting_lines_001.blend.zip)

**Comment by enzyme69** [comment]
Although I could MONAD it, but it might crash~

<img width="1204" alt="Screen Shot 2020-03-16 at 11 52 34 am" src="https://user-images.githubusercontent.com/3952687/76714689-b3e5aa00-677c-11ea-90ae-530f277c4df0.png">t 

<img width="1057" alt="Screen Shot 2020-03-16 at 11 52 45 am" src="https://user-images.githubusercontent.com/3952687/76714686-af20f600-677c-11ea-8ef5-922fe443934f.png">

**Comment by zeffii** [comment]
yeah, we seem to be missing a vector accumulator .
```
[A. B. C]  => [0, A, A+B, A+B+C]
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/76743311-b93df700-6772-11ea-8923-f659d30117db.png)

**Comment by zeffii** [comment]
then you use list modifier, accumulate sum
![image](https://user-images.githubusercontent.com/619340/76744939-526e0d00-6775-11ea-9d32-1d991e3f09fa.png)

[simpler_easing2_2020_03_16_10_00.zip](https://github.com/nortikin/sverchok/files/4337485/simpler_easing2_2020_03_16_10_00.zip)

**Comment by enzyme69** [comment]
Thanks so much Zeffii I will study this now~
