### ISSUE TITLE
Adaptive Edge MK2 wish list

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2992]
Probably if we could have adaptive edge that can have control over the "edge normal" normal, it would come in handy to avoid situation like this:

<img width="851" alt="Screen Shot 2020-03-21 at 9 08 43 pm" src="https://user-images.githubusercontent.com/3952687/77224290-47bdd880-6bb8-11ea-93b3-36ede718f1f7.png">

[circular_osc_001.blend.zip](https://github.com/nortikin/sverchok/files/4362693/circular_osc_001.blend.zip)

**Comment by BennyGovaerts** [comment]
Can you try this setup , maybe not what you need , but i think it works ...
![image](https://user-images.githubusercontent.com/49908008/77813166-a4ccf900-70a6-11ea-82e8-c3d5e11b3311.png)
[Polyline curve.zip](https://github.com/nortikin/sverchok/files/4396545/Polyline.curve.zip)

**Comment by enzyme69** [comment]
Thanks Benny!
