### ISSUE TITLE
CurveTo in Profile Parametric Mk3 couldn't process num_verts.

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#2996]
I tried to run examples in an official document below.

https://sverchok.readthedocs.io/en/latest/nodes/generators_extended/profile_mk2.html

when I run a below text, I got an error.

```
M 0,0
L 0,3 2,3 2,4
C 2,5 2,5 3,5 10 0
```
![image](https://user-images.githubusercontent.com/62538469/77295092-a6a25f80-6d28-11ea-99fa-75921b2f6fd8.png)

```
M 0,0
L 0,3 2,3 2,4
C 2,5 2,5 3,5
```
is OK.

I'm new to Github and Sverchok, if I did wrong post please close this post.

## Sverchok version

Sverchok version 0.6.0.0(71b8c23)
Sverchok: from sverchok-master.zip from github

**Comment by portnov** [comment]
In mk3, to specify num_verts, you should write it as

```
C 2,5 2,5 3,5 n=10
```
Or you can skip it, to use the default value (specified in the N panel of the node).

**Comment by ken26u** [comment]
Thank you, portnov.
I didn't know that.
I could run with no error so I close this issue.

**Comment by portnov** [comment]
@ken26u you can always find last version of the documentation in this repo, for example see https://github.com/nortikin/sverchok/blob/master/docs/nodes/generators_extended/profile_mk3.rst .

**Comment by ken26u** [comment]
I'll always check the document that you teach me.
Thank you again.

**Comment by nortikin** [comment]
what if we make button to auto create bugreport? 
So it will create breaf text and json nodetree file with tech data of system and open browser on issues?

**Comment by ken26u** [comment]
sorry, I didn't notice your reply
if you do, I glad it.
