### ISSUE TITLE
Turn off terminal output “is rendering frame #, updates missed?” 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3000]
Can this terminal output be commented out or only conditionally printed?

./core/handlers.py:        print(f'is rendering frame {scene.frame_current}, updates missed?’)

```
    if scene.render:
        print(f'is rendering frame {scene.frame_current}, updates missed?')
        # ---- raise Exception("asserting error")
```

**Comment by portnov** [comment]
I'd suggest to replace print with debug(), then one who wants to see it can always turn debug output on :)

**Comment by DolphinDream** [comment]
So adding this to the handlers.py  should be fine, right?


```
    from sverchok.utils.logging import debug
...
    if scene.render:
        debug(f'is rendering frame {scene.frame_current}, updates missed?')
        # ---- raise Exception("asserting error”)
```

**Comment by portnov** [comment]
Do some manual testing, just in case, who knows maybe there will be some cyclic import... And better run automated tests locally, also just in case.

**Comment by DolphinDream** [comment]
@portnov how do you run automated tests locally ?

**Comment by portnov** [comment]
BLENDER=/path/to/blender ./run_tests.sh
or similar command on Windows.

**Comment by DolphinDream** [comment]
@portnov Here’s the log I get when I run the tests. I don’t think the listed error is related to the changes I made to handlers.py though, since I get the same error when i run the test against the master branch.

[sv_auto_tests.log](https://github.com/nortikin/sverchok/files/4384636/sv_auto_tests.log)

**Comment by portnov** [comment]
It seems so.
