### ISSUE TITLE
Adaptive Polygon MK2 seems to be broken... 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3006]
I cannot make it to work.

<img width="797" alt="Screen Shot 2020-03-28 at 9 52 33 am" src="https://user-images.githubusercontent.com/3952687/77806791-d9a67380-70d9-11ea-8da8-d37a4ad98dfd.png">

[adaptive_bug.blend.zip](https://github.com/nortikin/sverchok/files/4396223/adaptive_bug.blend.zip)

**Comment by vicdoval** [comment]
If you update sverchok now should work

**Comment by enzyme69** [comment]
![Uploading Screen Shot 2020-03-28 at 10.37.21 am.png…]()

Thanks Vic!
