### ISSUE TITLE
Random Points On Mesh is outputting Vector() instead of [[]]]

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3008]
<img width="1289" alt="Screen Shot 2020-03-28 at 8 48 32 pm" src="https://user-images.githubusercontent.com/3952687/77820330-92e66700-7135-11ea-9361-1f2881dd6228.png">

[points_inside_fun_001.blend.zip](https://github.com/nortikin/sverchok/files/4396914/points_inside_fun_001.blend.zip)

Ok, this RPOM node is now working, but seems to be outputting Vector() instead of [[][][]] and so I cannot use it with UV Connection.

So strange~

**Comment by enzyme69** [comment]
<img width="784" alt="Screen Shot 2020-03-28 at 8 56 15 pm" src="https://user-images.githubusercontent.com/3952687/77820453-93333200-7136-11ea-9b2e-78767ae8ac93.png">

What was the thing that converts Vector() into Sverchok data... 🤔

**Comment by zeffii** [comment]
fixed https://github.com/nortikin/sverchok/commit/f53457edc8c0861eb852e0664081490dcf78c2aa

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/77821231-ce0e7900-70e8-11ea-8edb-e5c88e3bab24.png)

**Comment by enzyme69** [comment]
Thanks Zeffi! Conformed working as expected~
<img width="208" alt="Screen Shot 2020-03-28 at 11 42 27 pm" src="https://user-images.githubusercontent.com/3952687/77823269-e6fd4580-714d-11ea-9c10-65774c581000.png">
