### ISSUE TITLE
Update custom property ?

### ISSUE THREAD

**Issue by melMass** [nortikin/sverchok#3010]
## Problem statement

I'm trying to update custom attributes from LuxCore using sverchok nodes.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/7041726/77833913-18bbdf80-7141-11ea-9acd-fe6bf113624c.png)

Values input is a list of colors 

## Expected result

The color of the lamp's custom attribute to be set.

## Actual result

Nothing, but sverchok recognise the property as it's not red...

## Sverchok version
 
this master @ commit f53457edc8c0861eb852e0664081490dcf78c2aa

**Also what does Mk2 Stands for ?**

**Comment by zeffii** [comment]
mk2 = "mark 2" 

hmmm i don't have luxcore installed.. is luxcore adding custom properties to the Lamp / Light objects?

**Comment by zeffii** [comment]
do you know the full datapath to the `rgb_gain` ?  is it something like
```
bpy.data.lights[some_light_name].luxcore.rgb_gain
```
?

**Comment by zeffii** [comment]
are you passing rgb_gain as a color property (without alpha..)

https://github.com/LuxCoreRender/BlendLuxCore/blob/b9ee0d15c1a81805fa88717682114b6f8e93c49d/properties/lightgroups.py#L23

    rgb_gain: FloatVectorProperty(name="", default=(1, 1, 1), min=0, max=1, subtype="COLOR",

**Comment by zeffii** [comment]
i'm not 100% sure that the Lights instanced by the "Lamp" node, will be initialized with the appropriate extra properties associated with Luxcore ..

**Comment by zeffii** [comment]
ok..they are :)
```
>>> bpy.data.lights['Lamp_Alpha_0'].luxcore.rgb_gain
Color((1.0, 1.0, 1.0))

```

**Comment by vicdoval** [comment]
the  problem is that the property is not in bpy.data.objects but in bpy.data.lights
this is the way I found to do it 
![image](https://user-images.githubusercontent.com/10011941/77834999-7f44fb80-7149-11ea-8cf3-9c514af2b5ae.png)

**Comment by melMass** [comment]
Thanks for the answers !! 
I did not knew about `Exec` node, very useful use case thanks

**Comment by zeffii** [comment]
@vicdoval  yes! i'll fix lamp output :)

![image](https://user-images.githubusercontent.com/619340/77835259-4a39a880-714b-11ea-8898-5e2de4d0af05.png)

**Comment by zeffii** [comment]
we can do a few things
1. use this datapath in Object ID set
```
data.luxcore.rgb_gain
```
2. or we have a switch in Lamp node do do
```
self.outputs['Objects'].sv_set(objs)   # bpy.data.objects[ .... ] 
# or
self.outputs['Objects'].sv_set([o.data for o in objs])    # bpy.data.lights [ ..... ]
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/77835436-caacd900-714c-11ea-965e-58054929713c.png)

**Comment by zeffii** [comment]
@vicdoval  do you think Lamp node should just output `bpy.data.lights` ?

**Comment by melMass** [comment]
@zeffii Unlike the lamp node `Color` input knob I cannot use a list of color in the `set property` values knob. I'm using the list trick from the samples:
![image](https://user-images.githubusercontent.com/7041726/77835599-9afed080-714e-11ea-835b-5517f5f15a9b.png)

**Comment by zeffii** [comment]
oh weird... i'm sure if we look at the code of the `object id set` , it will be clear why that's failing.

but not tonight :)

**Comment by zeffii** [comment]
thanks for the bug report @melMass

**Comment by melMass** [comment]
Thanks for taking a look ;) 
Have a good night

**Comment by vicdoval** [comment]
@melMass remove the list split and it works

**Comment by vicdoval** [comment]
@zeffi With bp.objects you can also parent it and those object stuff. For me your solution is pretty clean. 
What bothers me a little, if you want to edit the lamp node is that now in Eevee and Cycles the "Strength" of a lamp is called "Power" in all but the Sun lamp. And in eevee the lamp values are not inside a nodetree but in the properties panel (this props persist in cycles but also has a node tree) so finally the strength input of the node works partially in cycles and nothing in eevee. This sooner or later has to be fixed... :)

**Comment by melMass** [comment]
@vicdoval Nope it does not work if I wire the ColorIn directly, I want a different color per light,
@zeffii the issue is that the prop expects a tuple of dimension 3 (without the alpha) I think that's the reason, I'm testing that now, this works:
![image](https://user-images.githubusercontent.com/7041726/77835840-1eb9bc80-7151-11ea-8049-018c25ee7b78.png)

**Comment by melMass** [comment]
@zeffii Yes unticking the alpha checkbox resolves the issue about multiple colors :) and using `data.luxcore.rgb_gain`. I think I can close this issue? Feel free to reopen if not!

**Comment by melMass** [comment]
Actually it does not error out but it only set the same values for all the lights, I'll investigate further

**Comment by vicdoval** [comment]
sometimes the viewport seems not to update, but generally works
![image](https://user-images.githubusercontent.com/10011941/77836177-3d6d8280-7154-11ea-8837-d6c9dfd0adbc.png)

**Comment by zeffii** [comment]
there's also the issue of recursive updates, potentially. because when we change the value of some object from Sverchok, it may cause the scene to update, and that will in turn cause sverchok nodetrees to be updated by the `depsgraph_update_post/pre` handler.

**Comment by zeffii** [comment]
yep, seems to work anyway...
![image](https://user-images.githubusercontent.com/619340/77844604-35d7c900-71a8-11ea-98ab-0900a3c26389.png)

**Comment by zeffii** [comment]
i'm not sure about this, but it's worth investigating particularly for nodes that affect the blender scene graph.

I think the "missing updates" / passing values into a node and not seeing the luxcore update is a matter of our update system building an updatelist which excludes nodes that don't seemingly have any need to be updated.  Ie if a node doesn't have linked-outputs downstream (see.. object ID set has no linked output sockets).

as a temporary hack you can press left/right arrows to trigger an update by changing keyframes :)

**Comment by zeffii** [comment]
but i'm not sure about that..  because looking at the Properties panel, it does update simulatenously as I slide the input values for something like ...  `data.luxcore.exposure`

**Comment by zeffii** [comment]
i don't think we have a kb shortcut for doing manual nodetree update.. but i've been thinking about that for a while. (for the scenario where you don't want to move the frame...but do want to update the tree/depsgraph)

**Comment by portnov** [comment]
@zeffii currently it's F5 when the node editor window is active.

**Comment by melMass** [comment]
@zeffii Thanks for the tests, I came to the same conclusions. But I'm glad to have learned a lot of tricks along the way
