### ISSUE TITLE
more bugs in Lamp Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3012]
![image](https://user-images.githubusercontent.com/619340/77851500-ced30800-71d9-11ea-8fec-6c73e169be5a.png)

i suspect not many of us are using this node, but the color socket is not unpacked properly.

**Comment by vicdoval** [comment]
I have been using it like this 
![image](https://user-images.githubusercontent.com/10011941/77853098-9a177e80-71e2-11ea-920a-7a2b8bf890f8.png)
And it didn't seem wrong to me. One color per object. But maybe as is always one color it could be packed the other way, or maybe supporting both ways

**Comment by zeffii** [comment]
the listsplit node shouldn't be needed.

**Comment by zeffii** [comment]
here "perfect consistency" is the enemy of "convenience".
on the other hand.. maybe adding a toggle to "take colours from first colorlist" is a bit overkill if list Split is a simple way to do it..

**Comment by zeffii** [comment]
maybe i'll just point people to this thread if there are other issues.  who cares : )
