### ISSUE TITLE
3dview props auto saved in preferences ?

### ISSUE THREAD

**Issue by melMass** [nortikin/sverchok#3013]
**Tags:** `#lowpriority, #ui, #2.81`
## Problem statement

This is not a real problem but a small annoyance:

When using the `3D View props` node, **the values are saved in the preferences** if Blender's new `autosave preferences`, which was added in 2.81 I think, is **on**. I usually turn it off but I discovered this while using it in someone else's blender)

## Steps to reproduce

1. Create a `3D View props`
2. Change the grid color to red
3. Restart Blender, the grid is red...

## Expected result

Do not save (somehow..?) this setting.

## Actual result
![image](https://user-images.githubusercontent.com/7041726/77857206-73664180-71fc-11ea-8d02-64e3d0949f34.png)

## Sverchok version

this master @ commit f53457edc8c0861eb852e0664081490dcf78c2aa

**Comment by zeffii** [comment]
the 3d view props node is really just displaying the UI elements in one location. (ie..the node), as you've already noticed what Blender does is decided by the state of the auto-save feature. I also don't really always like this feature, but other times I do like it.

not super sure what to do about this,    if   anything ..

**Comment by zeffii** [comment]
as far as i'm aware there is no granular control over the auto save feature.  and which properties it stores automatically vs which are not stored.

for once i also don't have even a slightest idea of what would be a workable solution. I don't really want to add a toggle onto the 3dview props to turn off autosaving.. but i might.

**Comment by melMass** [comment]
To me setting is as a default created a huge mess on my hand, I regularly rely on messing the prefs knowing that I can just not save them, as I have used Blender for years, my brain do know if I need to save them. On most of my custom addons I do have a shortcut button to save the preferences for install.

I actually thought at first that the `3D View props` node was using custom drawing like the other OGL Viz nodes it seems to be the only one that set viewport properties directly?
The solution would be to draw them using custom drawing, separating it from the viewport settings while disabling the original grid on activation?

But yes it's a very small annoyance, as I'm new to Sverchok I thought it was a good idea to report it as the behavior might after other nodes I don't know of :)

**Comment by zeffii** [comment]
i think you really want to get used to disabling that feature :) or write a small addon / attach a kb shortcut to ensure autosave is off.

the node was added with the intent that it would let me quickly adjust backgrounds... waaay before (2014...) blender got this autosave feature

**Comment by melMass** [comment]
Since then I learned my lesson 😆 
If this does not affect other nodes you can close the issue!

**Comment by zeffii** [comment]
it's i think the only node that has control over those things.

i feel your pain.
