### ISSUE TITLE
Get Element Active Index And Storing It

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3019]
It feels like a "dejavu" but does Sverchok have a way to quickly "store element index" and then to use it for Extrude etc? Since we don't actually have hands on interfacing with 3D while node is being generated (see BoxCutter and Modifiers).

<img width="1387" alt="Screen Shot 2020-03-31 at 9 08 17 pm 1" src="https://user-images.githubusercontent.com/3952687/78014633-f241b280-7393-11ea-8a37-d0fffc538215.png"> 

[print_index_002.blend.zip](https://github.com/nortikin/sverchok/files/4408303/print_index_002.blend.zip)

**Comment by zeffii** [comment]
strictly speaking whenever your intention is do selections based on a manual interaction with the subject, then you are stepping away from proceduralism.  

yes we have talked about this, and little has changed since:   https://github.com/nortikin/sverchok/issues/1320

**Comment by zeffii** [comment]
here's a SNLite solution, which I think makes a shit-tonne more sense.

```python
"""
in obj o
out mask s
"""

if obj and obj[0]:
    mesh = obj[0].data
    mask.append([f.select for f in mesh.polygons])

```

![image](https://user-images.githubusercontent.com/619340/78019511-20050800-7350-11ea-934f-5573bbe51e99.png)

**Comment by zeffii** [comment]
you can hide (or translate to the side) the "donor" object.. and then instead of VDMK3 use a BMV with a unique name, and do whatever.

**Comment by zeffii** [comment]
doing it in `edit_mode` just isn't immediate, you must tab in/out of that mode to update the mesh face selection table.

**Comment by zeffii** [comment]
you could do
```
"""
in obj o
out mask s
"""
import bpy
import bmesh

if obj and obj[0]:
    mesh = obj[0].data
    if obj[0] == bpy.context.edit_object:
        bm = bmesh.from_edit_mesh(mesh)
        mask.append([f.select for f in bm.faces])
    else:
        mask.append([f.select for f in mesh.polygons])
   
```
which can work while the object is in edit mode, but you will still need to manually update the frame somehow (either arrow keys or `f5`)

**Comment by enzyme69** [comment]
Thanks Zeffii I'll give this a try!

Would be cool if there is a clever Macro that grabs / capture components active in edit mode, then create a node that stores that index numbers in a node.

**Comment by enzyme69** [comment]
In your example it reads object. Bmesh Viewer output mesh, and reset the components. So I need to turn it off and bring it back. 

<img width="1013" alt="Screen Shot 2020-03-31 at 11 56 48 pm" src="https://user-images.githubusercontent.com/3952687/78028793-4c01a700-73ab-11ea-8093-4d7f5a8fc943.png">

The quickest is probably some kind of Macro that read the component of object being selected, and then generate "something" that stores the index numbers / mask.

**Comment by enzyme69** [comment]
I will sleep on this and come back~

**Comment by zeffii** [comment]
imo if you are manually selecting geometry, you should consider that part of the tree frozen. So you might as bake it.

I think what you really, and I said this years ago, is a way to make spatial selections based not on directly interacting with an object-mesh, but rather using greasepencil+proximity .. or 3d/2d brushes, that can touch (or be proximate to) geometry no matter how many times the object is updated.

**Comment by Durman** [comment]
@zeffii I'm not agree that everything should be procedural. What is more convenient to make manually should be done manually. For example some profile can be done manually for sweeping it along a curve. Or some input objects can be non procedural but they can be used for scattering them procedurally.

I think it can be useful to select manually some parts of mesh if the mesh will be never changed.

>Would be cool if there is a clever Macro that grabs / capture components active in edit mode, then create a node that stores that index numbers in a node.

@enzyme69 Your description is very close to work of this node:
#2465
Actually it available for 2.79 only for now.

**Comment by portnov** [comment]
bq. to select manually some parts of mesh if the mesh will be never changed.
for this case, maybe just add "selection mask" output(s) for Object In nodes?

**Comment by zeffii** [comment]
@portnov, or instead of adding another socket to object_in .. add a node that can take Objects, and output their selection masks.

**Comment by zeffii** [comment]
ie.. like
```python
import bpy
import bmesh

....

for obj in objects:
    if obj == bpy.context.edit_object:
        bm = bmesh.from_edit_mesh(mesh)
        mask.append([f.select for f in bm.faces])
    else:
        mask.append([f.select for f in mesh.polygons])
```

**Comment by zeffii** [comment]
@Durman 
> I think it can be useful to select manually some parts of mesh if the mesh will be never changed.

but at somepoint (and also in the node you suggest)  you are freezing the object, to ensure that no indices change.

maybe i've failed to explain my point here.

keep track of index 10, 12, 13

![image](https://user-images.githubusercontent.com/619340/78038440-25248000-736d-11ea-9acb-94d4fa874d13.png)
![image](https://user-images.githubusercontent.com/619340/78038508-340b3280-736d-11ea-98c9-d16f7efc0112.png)
![image](https://user-images.githubusercontent.com/619340/78038597-4be2b680-736d-11ea-8218-543373020b61.png)

now this example is the most basic form of node. The initial selection of indices bares no coherent connection to the final index location, because the node's algorithm is not concerned with that (nor..would it be useful... realistically for it to track that.. )

they best you can do is (as I point out earlier) two options
 - to consider the output of a node Frozen if you want to manually make selections on it. and progressively freeze subsequent nodes.
 - or use a spatial brush / GP stroke to mask.

**Comment by Durman** [comment]
@zeffii I still does not see problems in creating selection manually if object is not going be changed.

By the way according this picture if I have understand correctly, `everything nodes` project consider of using manual selection too. Cluster is a selection set of vertices/edges/faces/.
![image](https://dev-files.blender.org/file/data/6htodqshvp7v3dganyxt/PHID-FILE-dhnmwpjrbwvpldlxweuz/Screenshot_2020-03-22_at_11.28.33.png)

**Comment by zeffii** [comment]
@zeffii I still does not see problems in creating selection manually if object is not going be changed.

indeed. if the object is not going to be changed. it is frozen. and it no longer needs to be dynamic. so it doesn't need to be from a node. This makes the whole "problem" a matter of "perspective" .and not of "what is possible".

**Comment by zeffii** [comment]
as per: 

![image](https://user-images.githubusercontent.com/619340/78059440-2617da80-738a-11ea-83b1-ad732c17dcd7.png)

**Comment by Durman** [comment]
I think `index-instability` is so obvious that every user will expect getting arbitrary selection after arbitrary changing of initial object because what else can be exptected?

For example your example with plane. If 10, 12, 13 faces are selected what else can be expected after increasing plane tessellation if not selection of 10, 12, 13 faces?

**Comment by zeffii** [comment]
right. we can get the selected faces/edges/verts, but it can not be from a mesh generated by an active BMeshViewer, preferably baked-static.

**Comment by zeffii** [comment]
tecnically, if the 'constant vert count` mode is on, the bmeshviewer could retain the 'selections'...

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/78073807-de04b200-73a1-11ea-9d22-54c739bb02d8.png)
i'll add a lite version of that node.   https://github.com/nortikin/sverchok/pull/3021

**Comment by zeffii** [comment]
it's very easy to accidentally unselect stuff, now I remember why I never liked this mixture of manual vs procedural. I suppose selections could be stored in the object using Facemaps or something... (all things Sverchok doesn't need to be aware of - at all )

**Comment by enzyme69** [comment]
Reading the thread... yeah like zeffi said, freezing the mesh sounds right. For that part, I always think that maybe we could have  "Intermediate Object". Bmesh Viewer with LIVE turned off is about right, except it does not have Out slot to continue.

I will re-read and find some workaround. Select Mask would be nice, it simply create List Input (large) node that stores the index list.

**Comment by zeffii** [comment]
better to use FaceMap feature, of the object inside Blender, instead of making a Sverchok solution for a Blender problem.

**Comment by zeffii** [comment]
> @enzyme69 Your description is very close to work of this node:
> #2465
> Actually it available for 2.79 only for now.

just to be clear here, i've added a Lite version of that node to `nodes/scene/selection_grabber_lite`

**Comment by Durman** [comment]
> it's very easy to accidentally unselect stuff.

For this reason in my implementation of `selection grabber` selection was kept independently from object. After `grabbing`  of selection object can even be deleted and mask will be still available in node.

**Comment by zeffii** [comment]
i propose the following usage of the grabber Lite 

- if the object is generated by Sverchok/bmviewer, Freeze the node (unset Live)
- make selection in edit mode
- for faces:
    - go to obj/properties, and assign a FaceMap using the current selection

That way faces never get lost.

**Comment by Durman** [comment]
`BMViwer` does not have freezing functionality. If auto updating will be switching off, next time when a node tree will be changed catch data of the node will be lost.

**Comment by zeffii** [comment]
> BMViwer does not have freezing functionality. If auto updating will be switching off, next time when a node tree will be changed catch data of the node will be lost.

What? the Live button essentially freezes the node.

**Comment by Durman** [comment]
I mean such effect.
![non freazing](https://user-images.githubusercontent.com/28003269/78152055-5e7eed80-744a-11ea-97ce-722ec1c825e8.gif)

**Comment by zeffii** [comment]
OK.  Live, when switched off, does not output the Objects, i'd prefer to address that instead of storing indices in the grabber.
