### ISSUE TITLE
everything nodes

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3020]
## Problem statement

If EN will be developed. nodes that doubles ours must support ours data structure. And it is chance to rewrite fully to numpy.

## Needed

Propose blender developers to support our workflow, we need propose this workflow. And to develop it.
I wrote on here https://developer.blender.org/T74967#901046 next:

> just hope we can integrate sverchok nodes as extra addon for everything nodes with numpy data structure. Because if you create math nodes working with your data, we need that node to work with ours numpy also.

1. write definitions to operate data
2. ask for deal with it in EN

**Comment by Durman** [comment]
I'm afraid that Sverchok is not as such perfect addon. It does not worth efforts to integrate it into Blender. The initial goal of Sverchok is even different. It is workflow for creating procedural architecture. It's not the goal of `everything node` project.

**Comment by zeffii** [comment]
if everything nodes becomes truely useful, i will start also coding nodes for it directly in C/C++ , but it will need some form of scriptnode.
