### ISSUE TITLE
What is "Face Data"?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3022]
I have a simple basic setup here where I want to:
1) extrude top part of box
2) from that are extruded face, to subdivide
3) we don't have mask on subdivide so I am stuck -- supposedly simple

But what is the purpose of "**Face Data**" in here?

<img width="911" alt="Screen Shot 2020-04-01 at 10 01 41 am" src="https://user-images.githubusercontent.com/3952687/78082940-ef7ca700-73ff-11ea-8c38-ae012b4cec2d.png">
[extrude_subdivide_002.blend.zip](https://github.com/nortikin/sverchok/files/4411928/extrude_subdivide_002.blend.zip)

<img width="801" alt="Screen Shot 2020-04-01 at 10 03 07 am" src="https://user-images.githubusercontent.com/3952687/78083022-2783ea00-7400-11ea-95b0-79023aaf2b09.png">

**Comment by vicdoval** [comment]
You can select parts of the mesh with "Select mesh elements by location" node in this case I'm selecting by the normal but there are some other methods in the node
![image](https://user-images.githubusercontent.com/10011941/78086804-562da080-73bf-11ea-9b63-553fca5f3706.png)

Face Data is a layer of information that travels with the faces and  (in some nodes) propagates to faces created from them.
It can be used to create face groups for later material assigning. In this example i pass the first mask as FaceData and it extends to all the faces created from the top face 
![image](https://user-images.githubusercontent.com/10011941/78087015-f08de400-73bf-11ea-95fc-77955ff541d4.png)

**Comment by portnov** [comment]
FaceData is arbitrary per-face data, i.e. one item of something (some number, for example) per each object face. It can be used to pass materials information, or selection masks, or whatever.

**Comment by enzyme69** [comment]
Thanks so much for in depth explanation, we need this in documentation somewhere. Will study and use this.

**Comment by enzyme69** [comment]
One thing bothers me is how Subdivide is using "Edge Mask" and I don't quite get it. Would be more logical if it is using Face Mask?

I am using @zeffii 's Selection Grabber, grabbing Edge by Index, but somewhat I am getting a wrong subdivision.

<img width="849" alt="Screen Shot 2020-04-01 at 10 58 38 pm" src="https://user-images.githubusercontent.com/3952687/78134744-55067d00-746c-11ea-9bd2-c08d4664347f.png">

[robot_007.blend.zip](https://github.com/nortikin/sverchok/files/4414908/robot_007.blend.zip)

**Comment by enzyme69** [comment]
Video 20 MB:

My feeling is that maybe there is some thing weird with subdivide and masking.

[Screen Recording 2020-04-01 at 11.03.07 pm.mov.zip](https://github.com/nortikin/sverchok/files/4414922/Screen.Recording.2020-04-01.at.11.03.07.pm.mov.zip)

**Comment by zeffii** [comment]
i give up trying to explain this @enzyme69 .
