### ISSUE TITLE
obj helper class to correctly initialize a unique name

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3028]
noticed i've avoided doing this :)

something for tomorrow. 2 april.

**Comment by zeffii** [comment]
i've added a temporary fix, while i think about this and stare outside.

**Comment by Durman** [comment]
This can be data of custom type, like this:

```Python
class ObjectName:
    used_names = []
    def __init__(self, name):
        self.name = name
        used_names.append(name)

    @classmethod
    def create_unique(cls):
        while unique_name in used_names:
            unique_name = new_name()
        return cls(unuque_name)
```

**Comment by zeffii** [comment]
too late man. this has been open for ages. no one wanted to do it. it's done.

**Comment by zeffii** [comment]
but i might add this/something like this to ensure even random names are never identical. feel free to commit a change.

**Comment by zeffii** [comment]
ie... the implementation of `get_random_init_v3`   is the entry point.

**Comment by zeffii** [comment]
not a priority anymore.. leave it :)

**Comment by Durman** [comment]
This functionality (generation unique names)  is related more with polishing. For me Sverchok is not at that stage. I just shared thought how this could be done.

**Comment by zeffii** [comment]
> . I just shared thought how this could be done.

appreciated. it's good to think about these polishing issues, I know the lack of polish is probably one reason people tend to gravitate towards AN or even sorcar.

maybe sverchok will be forever for those people who tolerate a work-in-progress, weighted heavily towards the audience that is willing to also do some coding too :)

**Comment by Durman** [comment]
I consider Sverchok as great place for self education in procedural modeling. AN have different purpose, by the way. It is not dangerous for Sverchok users.))
