### ISSUE TITLE
Unstable Index While Extruding

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3029]
Related to this:
https://github.com/nortikin/sverchok/issues/3019

So after "Selection Grabber" node was created by Zeffii I am testing a couple of simple modeling exercise. I quickly noticed some weird things happen, like some Extrude node actually keep changing the index number even without me touching the previous nodes. I think this is quite unstable and could be a bug -- or just an unfortunate limitation that cannot be fixed? 

<img width="1253" alt="Screen Shot 2020-04-02 at 10 31 30 am" src="https://user-images.githubusercontent.com/3952687/78196199-5e740180-74cd-11ea-834d-aeb55a849f25.png">

[table_chair_004.blend.zip](https://github.com/nortikin/sverchok/files/4418096/table_chair_004.blend.zip)

**Comment by enzyme69** [comment]
Video 17 MB.
[Screen Recording 2020-04-02 at 10.37.10 am.mov.zip](https://github.com/nortikin/sverchok/files/4418111/Screen.Recording.2020-04-02.at.10.37.10.am.mov.zip)

Extrude Region node seems to be the culprit...

**Comment by enzyme69** [comment]
If I use select mesh element by locations, it seems to be more stable and sane way as it is not dependant on index.

[table_chair_006.blend.zip](https://github.com/nortikin/sverchok/files/4418143/table_chair_006.blend.zip)

Realized:
Bridge Node is also missing, so maybe "mirror for this kind of thing".

**Comment by enzyme69** [comment]
Inset Faces seems to be most stable. 

<img width="1169" alt="Screen Shot 2020-04-02 at 11 18 54 am" src="https://user-images.githubusercontent.com/3952687/78198268-caf1ff00-74d3-11ea-8383-117ddfb88974.png">

[table_chair_013.blend.zip](https://github.com/nortikin/sverchok/files/4418211/table_chair_013.blend.zip)

**Comment by zeffii** [comment]
>  If I use select mesh element by locations, it seems to be more stable and sane way as it is not dependant on index.

if you reread the responses i've given. You'll appreciate that i've said this over and over and over and over again.

**Comment by zeffii** [comment]
I think , likely , there is instability in face indexing between what you are keeping in the tree, vs what has been baked.

for example, after baking one item.. and rereading from the real geometry seems more stable.
![image](https://user-images.githubusercontent.com/619340/78224979-b7419b00-74c9-11ea-9153-7e72c2701a21.png)

i haven't been able to make that unstable by any means.

**Comment by zeffii** [comment]
by deduction you should reach the same conlusion as me. it appears the face/edge indices that are transported internally, are different to the resulted edges/faces of the baked geometry.

![image](https://user-images.githubusercontent.com/619340/78225211-25865d80-74ca-11ea-844e-88d4cfa87180.png)

**Comment by enzyme69** [comment]
Yeah, I think when I go to edit mode, the index seems to change.

**Comment by zeffii** [comment]
> If BMesh Viewer can transfer Object Out while it's off, will it be any different?

good question. maybe, maybe not.  But hey,, i'm not the one trying to mix manual with procedural modeling techniques..  I understand why you are doing this tho, it would be cool if we got this to work without hiccups.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/78229734-a8121b80-74d0-11ea-8f17-79c303999dba.png)

**Comment by enzyme69** [comment]
Will test as it got pushed. Thanks again Zeff and all~

**Comment by Durman** [comment]
I will have a look what can be done here, later.

**Comment by enzyme69** [comment]
<img width="1095" alt="Screen Shot 2020-04-03 at 11 14 26 pm" src="https://user-images.githubusercontent.com/3952687/78359521-f32b4c00-7600-11ea-9ddf-13587c6d4346.png">

The trinity combo of selection mask + function (extrude, inset) + bmesh viewer = is almost like a single node, actually... What bothers me is when BMesh Viewer triggered, the masking disappear, instead of saved with selection mask itself.

**Comment by zeffii** [comment]
the only way storing selection (on the bmviewer, internally ) would make any sense between updates is  if the objects being written to the scene do not change their topology.. (ie identical vert count.. and the only change between updates is perhaps the location of the existing verts). 

as soon as the bmeshvieewr object would change the Vertex count / edges.. or faces ... you should consider (for your own sanity) that the indices are going to be unstable.

-----
so. it may be possible, but only in the scenario where you have updated only vertex locations between updates.

**Comment by zeffii** [comment]
because... i could easily add a toggle to "try to reselect faces between updates" but there's no guarantee it will always do what you want.

**Comment by zeffii** [comment]
but wait a sec, when you have `live` **switched off** bmeshviewer does not touch those objects, it just passes the object ( `objs = self.get_children()` ) .  So selection is only lost if Live is on ?

**Comment by enzyme69** [comment]
As soon as LIVE is activated, selection is reset. Only if LIVE is off, then I would do selection.

Would be nice to have a button that "store" / "update" as needed, not resetting the selection.

**Comment by enzyme69** [comment]
I wish that Text In and Text Out (single node) would store the data as is.

<img width="1238" alt="Screen Shot 2020-04-04 at 11 26 24 am" src="https://user-images.githubusercontent.com/3952687/78414282-286a8500-7667-11ea-8171-6eba655dbd6e.png">

**Comment by enzyme69** [comment]
<img width="1083" alt="Screen Shot 2020-04-04 at 11 34 18 am" src="https://user-images.githubusercontent.com/3952687/78414593-8f3c6e00-7668-11ea-94e1-b9e68a1979a1.png">

<img width="1214" alt="Screen Shot 2020-04-04 at 11 36 13 am" src="https://user-images.githubusercontent.com/3952687/78414588-89468d00-7668-11ea-9860-2da8707e0594.png">

**Comment by Durman** [comment]
> I wish that Text In and Text Out (single node) would store the data as is.

You should make separate proposal for this.

**Comment by Durman** [comment]
@enzyme69 Can you test the branch with our examples? Note the new version of the node return faces in complete different order but the order should be stable. So you should reset `mask graber` nodes in your examples.

**Comment by enzyme69** [comment]
@Durman I am not sure how to check with branch, shall I wait for you to just push the change?

**Comment by Durman** [comment]
You can wait or download Sverchok from here:
https://github.com/nortikin/sverchok/tree/fix_face_indexing_extrude_region
