### ISSUE TITLE
Wishlist: Notes IO and Text IO 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3038]
I kind of wish Text can behave more like Notes IO. Or maybe Note IO will keep the data type.

I mean in case of Notes, it converts the data into Text, store it inside the node, and it can output. Very nice, although the type of data is String now. 

I have been using Zeffi's selection node. And this node is good at storing Masked data, but I supposed it requires something like Note IO or Text IO to save the and reload the data.

[wishlist_data_in_out_001.blend.zip](https://github.com/nortikin/sverchok/files/4430808/wishlist_data_in_out_001.blend.zip)

**Comment by enzyme69** [comment]
<img width="1024" alt="Screen Shot 2020-04-04 at 4 43 19 pm" src="https://user-images.githubusercontent.com/3952687/78419641-67163480-7693-11ea-9f17-9367f1019f5f.png">

🧐 I mean, Text can go out to text and reloaded in but Note node does it in one go.

**Comment by enzyme69** [comment]
Something like this for now~
<img width="671" alt="Screen Shot 2020-04-04 at 4 52 36 pm" src="https://user-images.githubusercontent.com/3952687/78419758-bad54d80-7694-11ea-8f83-8e5ec258b3dc.png">

Or maybe I could make something with exec node mod node...

**Comment by Durman** [comment]
I think solution of your problem can be merging this node #2465 into Sverchok for Blender 2.8. I'm going to do this later. But I agree the `text` node also can improved.

**Comment by enzyme69** [comment]
Thanks Durman,

I am still trying to parse this "[[ [[]], [[]], [[]] ]]"....

<img width="1242" alt="Screen Shot 2020-04-04 at 5 11 33 pm" src="https://user-images.githubusercontent.com/3952687/78420066-7bf4c700-7697-11ea-960c-63e1c94f1bf8.png">

**Comment by enzyme69** [comment]
Exec Mod Node to parse fro Text True False into actual value ... this took me quite a long time ...

```python
from distutils import util
import ast

print('$' * 50)
newlist = []
newlist.append(V1[0][2:]) 
for i in V1[1:-2]: newlist.append(i)
newlist.append(V1[-1][:-2] )
print(newlist)

for i in newlist:
    append(util.strtobool(i[0][:1]))

```

**Comment by enzyme69** [comment]
Example result, once all the "selection mask" dependency is scrapped and simplified.

<img width="730" alt="Screen Shot 2020-04-04 at 8 30 01 pm" src="https://user-images.githubusercontent.com/3952687/78423599-11ea1b00-76b3-11ea-8f62-7a989f0d1d53.png">

<img width="647" alt="Screen Shot 2020-04-04 at 8 31 34 pm" src="https://user-images.githubusercontent.com/3952687/78423622-48c03100-76b3-11ea-8beb-9c989aff49e8.png">

**Comment by zeffii** [comment]
a `cache` node was introduced many moons ago.

![image](https://user-images.githubusercontent.com/619340/82537654-aa950700-9b4a-11ea-8ea1-2f523d6e5ffc.png)
