### ISSUE TITLE
Sverchok B Bake All button does not work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3041]
I checked in recent versions, this Bake All Button does not quite work. Would be nice to bake all based on selected VD... maybe.

<img width="670" alt="Screen Shot 2020-04-05 at 11 08 18 pm" src="https://user-images.githubusercontent.com/3952687/78499155-6e703780-7792-11ea-95f7-910d1802fd91.png">

**Comment by zeffii** [comment]
> "Bake All Button does not quite work."
can you be more specific ?

**Comment by zeffii** [comment]
code involved
https://github.com/nortikin/sverchok/blob/b852eb49f145442e979e3739e6878bdea3fd49fb/utils/sv_panels_tools.py#L49-L72

**Comment by zeffii** [comment]
fixed https://github.com/nortikin/sverchok/pull/3076
