### ISSUE TITLE
mixin for node_dict

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3044]
some nodes implement specific storage, in data structures which are not convenient to store in `bpy.props`, traditionally we've used ` self.node_dict = {} `

as discussed in comments earlier, it's a little convoluted to implement a unique node_dict each time.

I propose a mix-in, and using a `self.node_dict` as the dict name, to be constant with existing nodes , and maybe getting those nodes to use the mix-in.

just thinking out loud here..
```python
class SvDictStorage:

    n_id = bpy.types.StringProperty(name="n_id")
    node_dict = {}

    def node_dict_data_func(self):
        # you must implement this function to ensure that the nodedict will get a valid storage
        # upon open blend
        pass

    def node_dict_set_data(self, data)
        self.node_dict[self.node_id] = {}
        self.node_dict[self.node_id]['data'] = data
        return data

    def node_dict_get_data(self):
        ndict = self.node_dict.get(self.node_id)
        if not ndict or not ndict.get('data'):
            return self.node_dict_set_data(self.node_dict_data_func())
        
        return ndict.get('data')
        
```
it would need to contain some of these..

**Comment by Durman** [comment]
I would suggest to use `@property` decorator for set and get functions. Also `save` function should be implemented for saving data into Blender during saving event. 

Also there should be raising `AttributeError` somewhere in case if requested attribute is not exist. Or probably some default value could be returned.

`Node dict` will be used for keeping only one attribute per node?

**Comment by zeffii** [comment]
> Node dict will be used for keeping only one attribute per node?

no, not necessarily

```python
self.node_dict[n_id]['data'] = ...
self.node_dict[n_id]['other_data'] = ...
```
i want to point out that you can make `data` a dict too, and stick anything inside it.
using `@property` would complicate setting specific multiple keys like `data`/`other_data`

it might be written has
```python
def node_dict_set_data(self, keyname, keyvalue)
    ...
```
-----

of course some errorhandling and recovery will be implemented.

**Comment by zeffii** [comment]
i'd like to do this with as little code as possible, because then there is less to debug.
```python
class SvDictStorage:

    n_id = bpy.types.StringProperty(name="n_id")
    node_dict = {}

    def node_dict_data_func(self, key):
        """
        this function must return the data you wish to store in 
        
            node_dict[self.node_id][key] = ...
        
        to ensure that node_dict will get a valid storage upon open blend
        """
        pass

    def node_dict_set_data(self, key, value)
        self.node_dict[self.node_id] = {}
        self.node_dict[self.node_id][key] = value
        return value

    def node_dict_get_data(self, key):
        ndict = self.node_dict.get(self.node_id)
        if not ndict or not ndict.get(key):
            return self.node_dict_set_data(self.node_dict_data_func(key))
        
        return ndict.get(key)

```

**Comment by DolphinDream** [comment]
I see various nodes using these:

```
def storage_set_data(self, storage):
def storage_get_data(self, storage):
```

called from sv_IO_panel_tools.py . the get referencing a node_dict

Is this what the nodes should use to store / retrieve the custom data ? 

I don’t see any references to the above examples in the main code (e..g node_dict_set/get_data). I wonder if these were eventually implemented as storage_set/get_data

I’m trying to understand this whole custom props that get saved/loaded (? can i assume this is what you guys refer to as serialize/deserialize). 

I see many nodes use the node_dict concept.. but not all use the storage_set/get_data thing.  What is the status of this node_dict mechanism? Is this experimental? Should all nodes that need a node_dict use the same mechanism ?

**Comment by zeffii** [comment]
>  serialize/deserialize.

yep that's what `storage_get_data` and `storage_set_data` do, the Object In Lite node has a demonstration of how you might (re)store the state of a node in the following scenarios (but not limited to)
  - the node uses local storage (ie, a node_dict ) 
  - the node implements a more complex bpy prop like PropertyGroup / CollectionProperty / PointerProperty, which itself does not offer any serialization conveniences 

if you look at the various implementations of `storage_get_data` and `storage_set_data` you'll see those nodes have explicit control over the details of how they are serialized, the complex bpy props mentioned above can be composed arbitrarily and are not trivial (edit: but not impossible) to automatically serialize.

> I don’t see any references to the above examples in the main code 

yeah,  `storage_get_data` and `storage_set_data`  at the moment are things we implement on a node by node bases. Very few nodes need this

> I see many nodes use the node_dict concept.. but not all use the storage_set/get_data thing. What is the status of this node_dict mechanism? Is this experimental? Should all nodes that need a node_dict use the same mechanism ?

I think some of that is answered by now.  It's not experimental, the `node_dict[seld.node_id] = {}` gives you a namespace within the node where you can put anything Python. yes, anything. And that's great for the runtime of the node, but it must be rebuilt under certain conditions ( iojson, and  load .blend ) . With those new freedoms of "anything python" then comes the responsibility to be able return the state of the node / and node_dict .  Which is why you'll see the nodes that implement `node_dict`  have checks to see if the key is present in process or some updatewrapper, and are prepared to repopulate.
   - in the load .blend scenario the node should be able to repopulate a node_dict from all the available data in `self` .
   - for `iojson` you will have populated a "subdict" with all that information in `storage_get_data`, which can be used by 'storage_set_data' to repopulate a node_dict

The mixin for node_dict as linked above, is a suggestion (untested..never run outside of my brain) and resembles broadly the core of the mechanism, even if some nodes implement it differently.  I hope this summarizes the picture you may have built in your mind about this. Else, let me know.

**Comment by zeffii** [comment]
@DolphinDream   i think also resetting addons/python (f8)  changes `self` , and thus anything that is derived from `self`, therefore invalidating the key in node_dict
