### ISSUE TITLE
SV Waffle Example is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3045]
I wanted to use the Waffle example for Blender 2.82... back then it was working with Blender 2.79 and I did make a video of this. 

I tested just now, it's not outputting the expected result.

<img width="538" alt="Screen Shot 2020-04-08 at 8 34 25 pm" src="https://user-images.githubusercontent.com/3952687/78774670-57bb2200-79d8-11ea-9b4c-130d040d114c.png">

**Comment by zeffii** [comment]
the old Viewer Draw only had one socket which accepted both Edges and Polygons, i split that up into separate sockets, it appears the json was not updated (just because a json loads without errors doesn't mean it is working as expected)

notice the VDMK3 in that nodetree are set to display Faces, when only edges are passed. and in the other instance it is set to display display Edges when Faces are passed (which is fine..)

**Comment by zeffii** [comment]
this would work..
https://gist.github.com/52cc12765ad27e9b6e38b30ed41cc101

**Comment by zeffii** [comment]
not sure why it recalculates so much. i suspecthe listswitch node is doing a painful amount of updates and retriggering the nodetree.

**Comment by enzyme69** [comment]
The gist still did not work and yes it recalculates so much. The Waffle node needs MK2 maybe.

**Comment by zeffii** [comment]
try it a second time.  it does work. you must be patient.

**Comment by zeffii** [comment]
nah. waffle gets triggered by the node before it.

**Comment by enzyme69** [comment]
Can you take screen shot of working result? I am only getting outline shape on top of each other. 

And the edge still goes into face.

**Comment by zeffii** [comment]
why don't you make a new fresh waffle example instead, without list switch node :)

**Comment by enzyme69** [comment]
Let me make a new fresh waffle example from scratch, hope I learn something :=)

I think Boolean might works faster.

<img width="935" alt="Screen Shot 2020-04-08 at 9 46 39 pm" src="https://user-images.githubusercontent.com/3952687/78780735-70303a00-79e2-11ea-8d71-f422b1dba94f.png">

**Comment by enzyme69** [comment]
Cross Section nodes might be the one that's broken~

**Comment by enzyme69** [comment]
I cannot get cross section node to output anything:

<img width="863" alt="Screen Shot 2020-04-08 at 10 00 27 pm" src="https://user-images.githubusercontent.com/3952687/78781873-5d1e6980-79e4-11ea-8907-dd492b309805.png">

[cross_section_broken_002.blend.zip](https://github.com/nortikin/sverchok/files/4450291/cross_section_broken_002.blend.zip)

**Comment by enzyme69** [comment]
Ok this works but Alt F and Fill broken
[cross_section_broken_003.blend.zip](https://github.com/nortikin/sverchok/files/4450297/cross_section_broken_003.blend.zip)

**Comment by enzyme69** [comment]
Too fast into conclusion, somewhat this works and that cross section Edge is really outputting polygon too. Funny.

[cross_section_broken_004.blend.zip](https://github.com/nortikin/sverchok/files/4450320/cross_section_broken_004.blend.zip)

<img width="1015" alt="Screen Shot 2020-04-08 at 10 08 37 pm" src="https://user-images.githubusercontent.com/3952687/78782518-82f83e00-79e5-11ea-81cb-8b78d51c3a53.png">

**Comment by enzyme69** [comment]
Happy to say it does actually works... not sure why the example is not giving any result.

I reckon we can use Bounding Box node and get the object inside the box and then cut slice etc. Blender Boolean might indeed gives clean result too. But that's something I have to try first. 

<img width="1341" alt="Screen Shot 2020-04-08 at 10 36 44 pm" src="https://user-images.githubusercontent.com/3952687/78784882-77a71180-79e9-11ea-96bf-a44e9754d6a0.png">

[waffle_from_scratch_005.blend.zip](https://github.com/nortikin/sverchok/files/4450459/waffle_from_scratch_005.blend.zip)

**Comment by enzyme69** [comment]
Conclusion: my feeling is saying the boolean half box is indeed can be cleaner and faster:

<img width="1155" alt="Screen Shot 2020-04-08 at 11 00 58 pm" src="https://user-images.githubusercontent.com/3952687/78786894-d1f5a180-79ec-11ea-8384-c71e635e8d87.png">

**Comment by nortikin** [comment]
ok. this node specific - it takes points and replace them with new one. so, your mesh shold be much subdivided.
Approach is bad, but it creates rounded corners and so on. i will make new version asap, it is needed.
