### ISSUE TITLE
OpenVDB

### ISSUE THREAD

**Issue by OiledEluer** [nortikin/sverchok#3048]
Blender 2.83Alpha now supports the import and use of OpenVDB files.  Does SV support the OpenVDB file format?

**Comment by zeffii** [comment]
we have no nodes that are specifically aware of openVDB What were you thinking you might find?

**Comment by OiledEluer** [comment]
Let's say I have vdb in Blender that I want to use in SV for purposes similar to ways one can use the Object In node.  For example, I have a cloud volume imported to Blender as a vdb and I want to place that into a matrix created and animated in SV.   Another example, create geometry in SV, export out and convert to a volume vdb and import back into SV around the original geometry and resize to create an "auric" glow.

**Comment by zeffii** [comment]
i don't think sverchok, in its current form, would be a useful place to implement vdb nodes. Of course it is possible, but judging by the other node-based solutions that can handle openVDB, you'd need people with time and motivation related to the field of VFX to write the appropriate set of nodes (In, modifiers, transforms, out).

sverchok is essentially geared at a generative / additive workflow, where you start inside sverchok with something simple and output something complex. Not as it seems to be used by many - namely as a node-based modifier for the Object-In node.

**Comment by OiledEluer** [comment]
Can I ask where SV is headed as far development goes?  I do understand the team is resource constrained.

**Comment by zeffii** [comment]
i don't think any of us know where Sverchok is heading. We add stuff we need, when new needs arise (in some cases on commission).  Collectively we are interested in Maths/Design/Architecture in varying ratios,

I certainly like to limit feature creep  There's also very little reason for team-sverchok to add features that none of us are super interested in. (for this reason Animation is certainly not SV strength)

i don't know if that answers your question. I'm not against new nodes for handling VDB data, it just seems beyond the scope of sverchok. and also you probably want to have a backend written in a compiled language for maximum speed.

**Comment by OiledEluer** [comment]
That partially answered and a follow-on question.  Given the interests and motivations of the dev team and constraint of resources available, what is the plan to increase the user base? As a heavy user of SV over the last six months, I have many thoughts and ideas on the matter (and will share them if you like).

**Comment by zeffii** [comment]
> what is the plan to increase the user base?

The size of our userbase is mostly an effect, not a goal. 

> I have many thoughts and ideas on the matter (and will share them if you like).

we welcome all ideas, and if they fit into sverchok you can expect that we'll consider them seriously. If you can do some of the work, then that's even better.

**Comment by OiledEluer** [comment]
Ok.  What I plan to plan to do is to put everything into a single document. It will take me several weeks to do so and until then happy developing.

**Comment by zeffii** [comment]
OK! i'll close this in the mean time.
