### ISSUE TITLE
Socket not found in data cache error on replace sockets

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3053]
Anybody knows why this error occurs ? I don’t remember being a problem before..

Simple node setup:

<img width="1008" alt="SV-EllipseError-1" src="https://user-images.githubusercontent.com/2083719/79035198-22563600-7b8a-11ea-85f1-6b841cedf4e0.png">

When switching between a:b and a:e the node turns orange (exception). The node does a replacement of the first two sockets.

<img width="1002" alt="SV-EllipseError-2" src="https://user-images.githubusercontent.com/2083719/79035234-782ade00-7b8a-11ea-9832-6f812ebc3fa0.png">

and here’s the terminal output:

<img width="967" alt="SV-EllipseError-3" src="https://user-images.githubusercontent.com/2083719/79035201-22eecc80-7b8a-11ea-80ef-ec4ac8653bd2.png">

The error is only temporary. If I change the frame the node error recovers and the node behaves normally.

**Comment by zeffii** [comment]
changes to the ui, wrt sockets will trigger nodetree updates unless there is explicit throttling.
there might also be property updates which trigger an updateNode wrapper?

**Comment by zeffii** [comment]
i'll have a look after breakfast. looks fun.

**Comment by zeffii** [comment]
because you aren't throttling in  `def update_mode(self, context)` you could do this https://github.com/nortikin/sverchok/pull/3056

but you can also , i think, do
https://github.com/nortikin/sverchok/pull/3057
