### ISSUE TITLE
items=functioncall()

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3063]
@DolphinDream 

https://github.com/nortikin/sverchok/blob/ae2495b23690881bb08218de10aa55f511128b69/utils/sv_transform_helper.py#L128

if to the right of `items=` is a funcion call, i think this function is called a lot. a lot more than you realize.

there's an alternative `items_static=`
https://docs.blender.org/api/blender2.8/bpy.types.EnumProperty.html?highlight=items_static#bpy.types.EnumProperty.enum_items_static

the docs are a bit confusing there: https://docs.blender.org/api/blender2.8/bpy.props.html?highlight=enum%20property#bpy.props.EnumProperty

```
`items`:  pass a list or a function
    - if passing a list , there are expected formats described above
    - if passing a function, it is evaluated often multiple times a second if the mouse is moving
`items_static`:  will evalute the function once
```

**Comment by Durman** [comment]
This method is called only two times in start of Sverchok working. But if it even was more what the problem?

**Comment by zeffii** [comment]
if it's only twice (i've just tested.. that's correct)  then yes, consider this issue entirely void.

**Comment by zeffii** [comment]
ahh i see.  my bad, 
i think the difference is 
```
items=some_callback   # called repeatedly
items=some_function()   # items becomes the result of this function call
```
i'm st00pid.
