### ISSUE TITLE
lockdown April : Line/Dot drawings  ,VDMK3 output only

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3068]
a 2d grid

![image](https://user-images.githubusercontent.com/619340/79110599-1b424a00-7d7b-11ea-93e9-176c73086adf.png)

https://gist.github.com/5bbdc0b088c1e253af4cac6b917aef7d

**Comment by zeffii** [comment]
a 3d grid

![image](https://user-images.githubusercontent.com/619340/79110864-a4598100-7d7b-11ea-92ee-a5ae05fe6968.png)

https://gist.github.com/6c87cd4eb4b924a64a347f6ecce4603e

**Comment by zeffii** [comment]
borg fabric pattern (kdree edges, 3d grid, vector displace)
![image](https://user-images.githubusercontent.com/619340/79111400-c30c4780-7d7c-11ea-9f48-75217a8ae96f.png)

https://gist.github.com/d8e50e66b22cf73b1b4cc1e2016b3f4b

**Comment by zeffii** [comment]
shield constellation
![image](https://user-images.githubusercontent.com/619340/79112334-9bb67a00-7d7e-11ea-88b1-eb7587ef2e44.png)

https://gist.github.com/88214b9cfaf926e66e7e13e68cf6256a

**Comment by zeffii** [comment]
grid of custom indices
![image](https://user-images.githubusercontent.com/619340/79122310-a6c9d400-7d97-11ea-968b-869771612a3b.png)
https://gist.github.com/117f93e22f882f1bab07b2912353a638

**Comment by zeffii** [comment]
i added syntax highlighting mode for ExecMod, when linked to the console node: 
![image](https://user-images.githubusercontent.com/619340/79210496-39747c80-7e45-11ea-87cc-ae53e6c57da7.png)

**Comment by mmemetea** [comment]
I would love to see something like the Truchet tiling implementation discussed in this paper:
* http://archive.bridgesmathart.org/2018/bridges2018-39.pdf
From what I can see here, that looks already very close to that.

**Comment by zeffii** [comment]
@mmemetea  sure, nice paper you mention. I would approach those using primarily the `scripted_node` (SNLite), for locations and picking the tile.

**Comment by zeffii** [comment]
inner array
![image](https://user-images.githubusercontent.com/619340/79359001-4d51d880-7f42-11ea-9687-718e2fe18fd0.png)
