### ISSUE TITLE
Overriding Blender update events.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3077]
## Problem statement

- During coding of nodes you should take in account update system of Blender. 
- Blender `update` events does not suit well to the Sverchok required `update` events. 
- It is cheaper to spend some calculation to make update smarter and save time on nodes recalculations.

## Possible solution

First of all such system should get all signals from Blender. It is possible to do by placing function in update methods. For example:
```Python
class SverchCustomTree:
    def update(self):
        tree_update(self)
```
After getting signals the system can call appropriate methods.
```Python
def tree_update(node_tree):
    for node in node_tree:
        if hasattr(node, 'sv_update'):
            node.sv_update()
```
It is simpler to make update smarter.
```Python
def tree_update(node_tree):
    type_update = get_type_update()
    if type_update == 'new_links_creation`:
        new_links = get_new_links()
        fro link in new_links:
            update_node_ui(link.from_node)
            update_node_ui(link.to_node)
```

**Comment by Durman** [comment]
Probably for the start I will try to implement class which could just print type of detected events (node tree update, property update and so on). For this I think enumeration of possible blender events would be nice to create and class which can contain current event(s). Also this class should detect nested events. 

Printing should looks like this: `update of tree="NodeTree.001" was detected`. 

If first stage will be succeeded next step will be to utilize this functionality for generation Sverchok own events. 

List of method for listening:

- [NodeTree.update](https://docs.blender.org/api/current/bpy.types.NodeTree.html#bpy.types.NodeTree.update)
- [NodeTree.interface_update](https://docs.blender.org/api/current/bpy.types.NodeTree.html#bpy.types.NodeTree.interface_update) - not sure about this

- [Node.update](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.update)
- [Node.insert_link](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.insert_link)
- [Node.init](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.init)
- [Node.copy](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.copy)
- [Node.free](https://docs.blender.org/api/current/bpy.types.Node.html#bpy.types.Node.free)

- Property update
- Frame change update
- Undo update ?

If someone know other update methods please let me know.

**Comment by Durman** [comment]
The process should consist with the next steps:
1. Listening update events. 
2.  Interpreting events for detection deleting / creating links / nodes and property changes. 
3. Redraw UI for new nodes and nodes which was connected / disconnected or their properties was changed. 
4. Letting know (to update system) which nodes worth recalculate.

Splitting process on the certain steps can let to avoid using `throttling` of redraw methods inside nodes. Because during redrawing UI step all update events can be just ignored inside the `event system`.

Completely different functionality should be implemented for `undo` events. I think it after each `update wave` system should save its shape so it would be possible to return to previous stage. More simple solution will be redraw and recalculate everything after `undo` event.

Node should be redrawn and recalculated if link is added / deleted (output as well?), node property is changed or node is newly created / copied.

Some problems:
- How to detect which event is last in `update wave`?
- How to detect new links?
- How reroute update calling of properties via `event system`?
- How to handle macros interactions with node tree (F, Ctrl + G, macros of right click menu)?

**Comment by Durman** [comment]
Example of event wave during creating monad process:
```Text
EVENT: add_node                  IN: SvGroupInputsNodeExp      INSTANCE: Group Inputs Exp
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: add_node                  IN: SvGroupOutputsNodeExp     INSTANCE: Group Outputs Exp
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: copy_node                 IN: SvLineNodeMK4             INSTANCE: Line
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: monad_tree_update         IN: SverchGroupTreeType       INSTANCE: Monad
EVENT: add_node                  IN: SvGroupNodeMonad_574770549 INSTANCE: Monad
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: node_update               IN: SvNumberNode              INSTANCE: A Number
EVENT: node_update               IN: SvLineNodeMK4             INSTANCE: Line
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: free_node                 IN: SvLineNodeMK4             INSTANCE: Line
EVENT: node_update               IN: SvNumberNode              INSTANCE: A Number
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: node_update               IN: SvNumberNode              INSTANCE: A Number
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: node_update               IN: SvNumberNode              INSTANCE: A Number
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
EVENT: node_update               IN: SvNumberNode              INSTANCE: A Number
EVENT: tree_update               IN: SverchCustomTreeType      INSTANCE: NodeTree
```

**Comment by Durman** [comment]
I have tested some macros. And I counted how much times during macros process node tree was recalculated:
- connect viewer - 2 times
- join12 - 3 times
- join123 - 4 times
- recreate node - 7 times

Looks like current update system does not design properly for using macros.

**Comment by Durman** [comment]
1,5 steps are done. Next step will be taking control over updating UI and nodes calculations. It is quite a significant changes and they will override some of bad but well tested code. For this reason I'm going to make option between old and new approaches. It will let test new code better and move to it more smooth.

**Comment by Durman** [comment]
I have tried to fill table with ranges of possible changes relatively Blender events.

|     Update event     | affected nodes | affected links |
|:--------------------:|:--------------:|:--------------:|
| tree update          | 0*              | 0-n            |
| node update          | ignore         | ignore         |
| add node             | 1              | 0              |
| copy node            | 1-n            | 0-n            |
| free node            | 1-n            | 0-n            |
| add link to node     | 0              | 2-n            |
| node property update | 1              | 0              |
| undo                 | 0-n            | 0-n            |
| frame change         | 0-n            | 0              |

affected nodes - adding/deleting nodes or property changes. 
affected links - adding/deleting or reconnection links. 
n - number of links/nodes.

**Comment by Durman** [comment]
I was thinking how override control of property update events which should be done according the proposal. First priority is - `node coder` should not think about update system and try to throttling something. Second, make as little impact on existing code as possible. 

First solution was to override control in `updateNode` function but it is too late because some properties calls `pre update` method. Second solution is to use decorator for `pre update` method but it also does not seem good solution. `Msgbus` module also does not looks suitable because it is calling after `update function` of property.
So I'm thinking something like this syntax:

```Python
node_property = BoolProperty(name="Some property", update=events.property_update('node_property', update_function)
```

Benefit of using such syntax:
- It will be difficult to forgot throttle or update node because `events system` will do this by itself. 
- It is possible to do anything you want in update function with node, node will be updated automatically after the update function calling. 
- It will be possible to know what exactly property was changed. 

Downsides are:
- property name should be retyped again.
- all properties of all nodes should be fixed.

Actually it is not necessary to know which exactly property was changed we don't use such feature. But potentially it is quite power thing. For example it would be possible to bind something to concrete property changes.

**Comment by Durman** [comment]
Another feature which can be included in this proposal is `event_wave_id`. By this ID, one update event can be distinguished from another. It can help to use  such property of Blender collection as stay unchangeable during update event. 

For example in a beginning of update event all links can be converted in more efficient data structure than just list, with using strait memory links to links. It will let to avoid Blender crashing because link won't change memory address during one update. During update event all parts of Sverchok could call more efficient data structure.

**Comment by Durman** [comment]
I am thinking about adding `node_id` for the reroute nodes and its sockets for consistency.

```Python
def node_id(self):
    if not self.n_id:
        self.n_id = str(hash(self) ^ hash(time.monotonic()))
    return self.n_id

def socket_id(self):
    """Id of socket used by data_cache"""
    return str(hash(self.node.node_id + self.identifier))


bpy.types.NodeReroute.n_id = StringProperty(default="")
bpy.types.NodeReroute.node_id = property(node_id)
bpy.types.NodeSocketColor.socket_id = property(socket_id)
```

**Comment by vicdoval** [comment]
> I am thinking about adding node_id for the reroute nodes and its sockets for consistency.

The code is filled of tricks to handle reroutes (to jump over them) the don't have socket_data_cache associated neither sv_links, and they are not in the node_id_dict.. they are ghosts for Sverchok...

**Comment by Durman** [comment]
Since I faced with limitation of Blender node editor I was thinking about possibilities to move Sverchok to some external node editor which would lack known downsides of the Beldner. The idea is quite crazy. But I was looking for something like and faced with this:

https://www.luna-lang.org/

I was absolutely delighted with conception of the software. Here is the description:
> Luna is a data processing and visualization environment built on a principle that people need an immediate connection to what they are building. It provides an ever-growing library of highly tailored, domain specific components and an extensible framework for building new ones.

> Luna targets domains where data processing is the primary focus, such as data science, IoT, bioinformatics, graphic design and architecture.

**Comment by nortikin** [comment]
> Since I faced with limitation of Blender node editor I was thinking about possibilities to move Sverchok to some external node editor which would lack known downsides of the Beldner. The idea is quite crazy. But I was looking for something like and faced with this:
> 
> https://www.luna-lang.org/
> 
> I was absolutely delighted with conception of the software. Here is the description:
> 
> > Luna is a data processing and visualization environment built on a principle that people need an immediate connection to what they are building. It provides an ever-growing library of highly tailored, domain specific components and an extensible framework for building new ones.
> 
> > Luna targets domains where data processing is the primary focus, such as data science, IoT, bioinformatics, graphic design and architecture.

great workflow!!!! i like style

**Comment by Durman** [comment]
According my experience of developing group nodes overriding Blender events is wrong way. It impossible to move code from such functions as `init`, `update` and etc to another place because node argument of those function can loos its link to the object. Another problem is inherited Blender events. Some actions can lead to repeating new events again and again (throttling system) which difficult ot handle. 

But there is another solution. JacquesLucke says that this is what is used in animation nodes. And it is actually what `node groups` are using now. And this solution was used by Sverchok before 2.8. Finally the solution is to use timer. During node tree events only changes should be detected. Real update should be done via timer. It solves problems which mentioned before.
