### ISSUE TITLE
Blender 2.83 the V connector hotkey no longer working

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3078]
@vicdoval I am testing Blender 2.83 somewhat the convenient V and Ctrl LMB and RMB no longer working :(

**Comment by zeffii** [comment]
here language is important @enzyme69 

does "no longer working" mean you've used it during the last couple of days and suddenly after upgrading Blender or sverchok it has started fail ? or it's linking but not triggering an update in the viewer?  what version of Blender exactly ?

nightly builds of Blender 2.90 with sverchok are not yet supported, if you encountered issues fall back to 2.83

**Comment by zeffii** [comment]
seems fine here  
```
>>> bpy.app.version
(2, 83, 13)
```

**Comment by enzyme69** [comment]
I am using Blender 2.83 beta, and previously with Blender 2.82 official, it works.  

I uninstall and reinstall Sverchok clean from website and now working again~ so... yeah maybe it's just a little glitch.
