### ISSUE TITLE
0_o  "msgbus" bpy docs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3086]
https://docs.blender.org/api/blender2.8/bpy.msgbus.html

wtf.

**Comment by Durman** [comment]
I have managed to subscribe to `num` property changes of `Line generator` node. By the way it reacts on manual changes as well.
```Python
import bpy
import sverchok

# Any Python object can act as the subscription's owner.
owner = object()

subscribe_to = (sverchok.nodes.generator.line_mk4.SvLineNodeMK4, 'num')

def msgbus_callback(*args):
    # This will print:
    # Something changed! (1, 2, 3)
    print("Something changed!", args)

bpy.msgbus.subscribe_rna(
    key=subscribe_to,
    owner=owner,
    args=("Node property has changed",),
    notify=msgbus_callback,
)
print("Done")
```
I have tried to subscribe to creating new links in node tree by the way but it looks like it is react only to field changes not on changes in collections.
Anyway I think it can be useful in this issue #3077

**Comment by zeffii** [comment]
yeah, i was thinking more about what it means for `Object In`  :)   and maybe the `curves ui` while we still use it.

but it is interesting and long awaited.

**Comment by vicdoval** [comment]
unluckily I cant make it work with 
`subscribe_to = bpy.data.materials["Material"].node_tree.nodes["RGB Curves"].mapping.curves[3]
`

**Comment by zeffii** [comment]
yeah , also not
```python
curves = bpy.data.materials["Material"].node_tree.nodes["RGB Curves"].mapping.curves
subscribe_to = curves[3].resolve_path("points", False)
```

**Comment by zeffii** [comment]
it registers but doesn't seem to be triggered by direct interaction..

**Comment by zeffii** [comment]
i have to believe it's possible :)

**Comment by DolphinDream** [comment]
How do you add this subscription/callback to a node and have the it still work when you start new blend file or reload a file?

**Comment by Durman** [comment]
@zeffi I think we should create (in handlers probably) wrapper for `msgbus` calling so Sverchok always could control this in one place for throttling or what ever.

**Comment by portnov** [comment]
https://docs.blender.org/api/blender2.8/bpy.msgbus.html:

> The following updates do not trigger message bus notifications:
> 
>     Moving objects in the 3D Viewport.
>     Changes performed by the animation system.
> 

I think this implies that  any changes in scene that are done manually (editing objects, for example) do not trigger notifications too.

**Comment by zeffii** [comment]
https://blender.stackexchange.com/questions/166469/example-of-persistent-usage-of-bpy-msgbus-and-how-managing-msgbus

**Comment by DolphinDream** [comment]
adding this to handlers does the trick. 

```
@persistent
def sv_handler_msgbus(scene):
    from sverchok.nodes.scene.viewer_layers import layer_nodes_subscribe_to_viewer_nodes_name_changes
    print("updating msgbus handler")
    layer_nodes_subscribe_to_viewer_nodes_name_changes()

...

handler_dict = {
    'undo_pre': sv_handler_undo_pre,
    'undo_post': sv_handler_undo_post,
    'load_pre': sv_clean,
    'load_post': sv_post_load,
    'depsgraph_update_pre': sv_main_handler,
    'load_post': sv_handler_msgbus,
}

```

I’m not sure this is the right way .. but it does seem to work.

**Comment by zeffii** [comment]
dicts can't have duplicate keys.

**Comment by DolphinDream** [comment]
@zeffii I thought this wasn’t quite right because of the duplicate keys. 

Anyway, here is an answer i got on blender exchange indicating to this handler approach:

https://blender.stackexchange.com/questions/175868/msgbus-drops-subscriptions-on-new-or-reload-blend-file/175932#175932

**Comment by DolphinDream** [comment]
I think maybe the handler class can implement something generic regarding these subscriptions instead of importing/calling a specific node/class related msgbus subscription (like in my example). Perhaps define “monitor_node_changes”(or some more appropriate name) called from the handler class. on load. and if a specific class has this defined and overrides it then then handler would call it on load and let the specific nodes/classes setup their own monitoring as needed.

```
# in handler.py

@persistent
def sv_handler_msgbus(scene):
   for node in all_nodes:
       if node.has_method_defined(“setup_monitor_node_attributes”)
           node.setup_monitor_node_attributes()
```

I’m not sure if we should abstract away the msgbus code as well.. and have the nodes use our own subscription method instead:

```
# in handler.py

def subscribe_to_node_attribute_changes(subscribe_to, message, callback)
    bpy.msgbus.subscribe_rna(
        key=subscribe_to,
        owner=owner,
        args=(message,),
        notify=callback,
    )
```

```
# in specific class code implement the monitor method (called by handler.py on load)

def setup_monitor_node_attributes(): 
     subscribe_to_node_attribute_changes((node1, attribute1), “message1”, cb1)
     subscribe_to_node_attribute_changes((node2, attribute2), “message2”, cb2)
```

**Comment by Durman** [comment]
Subscription to Sverchok tree name changes.

```Python
bpy.msgbus.subscribe_rna(
        key=(bpy.types.NodeTree.bl_rna_get_subclass_py('SverchCustomTreeType'), 'name'),
        owner=object(),
        args=(),
        notify=lambda *args: print(f'Some tree name was changed, args="{args}"')
    )
```
