### ISSUE TITLE
Replace node functionality for developing nodes

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3087]
On the topic of node replacement.. how easy would it be to add the similar functionality to the obsolete node replacement but for the nodes being developed? Often time when I develop nodes I add and remove sockets, properties etc, which breaks the testing/demo node trees I create to help test the node... and have to manually rewire the broken node with the new version. This has become quite frustrating. It be awesome if I could just right  click on the broken node and replace it with the same node albeit with the updated sockets/props and keep all the previous sockets links and prop values (if they still exist). 

I would appreciate any hints on how to start implementing such feature.

**Comment by zeffii** [comment]
care to elaborate a bit, use screenshots? how big are the node differences.

**Comment by DolphinDream** [comment]
Sure.. here’s a simple example.. other examples may be more complicated (more nodes that have multiple connections all needing to be replaced)

![SV-BrokenNode](https://user-images.githubusercontent.com/2083719/79670588-31447600-8192-11ea-99d1-dc49de6017c7.jpg)

<img width="796" alt="SV-BrokenNode-Example" src="https://user-images.githubusercontent.com/2083719/79670590-343f6680-8192-11ea-8ba6-6044e1c8e7ac.png">

**Comment by zeffii** [comment]
maybe an operator that takes two selected nodes, detects which of the nodes is fully unconnected, and moves all links from node A to node B. ?

**Comment by portnov** [comment]
There is "Re-create node" button in the N panel. It actually calls for replacement operator with new node bl_idname = old node bl_idname. It does not do much magic, but I find it useful in many similar cases.

**Comment by portnov** [comment]
@DolphinDream also, btw, if you're developing nodes that generate mathematical curves or surfaces, consider use of SvCurve / SvSurface classes (see sverchok.utils.curve, sverchok.utils.surface, and sverchok.nodes.{curve,surface} nodes for examples). This can open many possibilities — for example, you can bend something along that curve...

**Comment by DolphinDream** [comment]
@portnov yeah! that seems to do the trick. :) I didn’t know about this feature.
