### ISSUE TITLE
Attractor Field Bug

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3090]
When the point is set to 'Nearest' and the Falloff is different from "None"
![image](https://user-images.githubusercontent.com/10011941/79803681-c0a08380-8362-11ea-8436-39228dc7b03a.png)

```
...ns\sverchok\nodes\field\vector_field_apply.py", line 80, in process
    new_vectors = np.array(coeffs)[np.newaxis].T * new_vectors[0]
ValueError: operands could not be broadcast together with shapes (24,1) (3,3)
```

**Comment by portnov** [comment]
@vicdoval should be fixed now, please check.

**Comment by vicdoval** [comment]
Yes it's fixed, thanks!

**Comment by vicdoval** [comment]
You may like to check this:
https://twitter.com/VicDoval/status/1252339741531402240
https://www.facebook.com/groups/1396995897211561/permalink/2629257060652099/

**Comment by portnov** [comment]
Thanks!
