### ISSUE TITLE
nodes with `prop_search` are broken, due to recent Blender API changes.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3091]
Currently a vast majority of our nodes use a `bpy.props.StringProperty` to store the name of a Blender datablock (think Material name, Text name, Object name, Image name...etc names), the ui interaction with the search box (called `prop_search` in the Blender API) returns to us the name of the object selected from that box.  like the box below

![image](https://user-images.githubusercontent.com/619340/80480160-7154e700-8950-11ea-97e0-be64528e0b4a.png)

This method of object/material/text/image/font selection now returns more information than just the String name of the object selected, it returns also some prefixes if the object is linked. For more information about why this issue exists, read https://developer.blender.org/T58641.

the `tldr;` prop_search will store object names in `bpy.props.StringProperty` using a 3 character prefix, usually the space character, but depending if an object is linked it will be `L  object_name` amd there may be other conventions.  

-----------------

we shouldn't / can't rely on stringproperty to store object names. it was convenient for a long time, and the solution is relatively easy to implement for all affected nodes. The reason it isn't fixed is because we haven't decided on a nice canonical way and whether its going to be acceptable to break .blends that use the current method.

------

In general use of objects in the .blend the result of a prop_search will be 
```
self.filename = "   visible_filename.txt"
```
internally in the node it will locate that datablock by string name, 
```
file = bpy.data.texts[self.filename]
>>> KeyError: 'bpy_prop_collection[key]: key "   visible_filename.txt" not found'
```
so Profilenode, and whatever other nodes that do an update when `self.filename` is set, will find they they will not work because blender api is inserting chars ...to solve a problem we don't have.

if we trim the StringProperty before storing it in the node, then the prop_search turns red.. which is not a nice UI effect..
![image](https://user-images.githubusercontent.com/619340/79956407-672e7680-8480-11ea-8c8d-42340f768226.png)

**Comment by zeffii** [comment]
profilenodemk3 is working with this PR https://github.com/nortikin/sverchok/pull/3092
but there are many more to do, and i don't like this kind of `kludge`. so...before doing too many of them lets sit back and think

**Comment by zeffii** [comment]
also the viewers that set materials

**Comment by zeffii** [comment]
i suppose we must solve this using a `pointer property` ffsake

**Comment by zeffii** [comment]
the following files contain one or more prop_searches..
```
sverchok\core\sockets.py:
sverchok\nodes\analyzer\image_components.py:
sverchok\nodes\field\image_field.py:
sverchok\nodes\generator\image.py:
sverchok\nodes\generator\script1_lite.py:
sverchok\nodes\generators_extended\generative_art.py:
sverchok\nodes\generators_extended\hilbert_image.py:
sverchok\nodes\generators_extended\mesh_eval.py:
sverchok\nodes\generators_extended\profile_mk3.py:
sverchok\nodes\object_nodes\assign_materials.py:
sverchok\nodes\object_nodes\color_uv_texture.py:
sverchok\nodes\object_nodes\get_asset_properties.py:
sverchok\nodes\object_nodes\points_from_uv_to_mesh.py:
sverchok\nodes\object_nodes\sample_uv_color.py:
sverchok\nodes\scene\collection_picker_mk1.py:
sverchok\nodes\scene\dupli_instances_mk4.py:
sverchok\nodes\scene\FCurve_in.py:
sverchok\nodes\scene\node_remote.py:
sverchok\nodes\scene\objects_mk3.py:
sverchok\nodes\script\multi_exec.py:
sverchok\nodes\script\sn_functor_b.py:
sverchok\nodes\text\text_in_mk2.py:
sverchok\nodes\text\text_out_mk2.py:
sverchok\nodes\transforms\texture_displace.py:
sverchok\nodes\vector\texture_evaluate.py:
sverchok\nodes\viz\viewer_bmesh.py:
sverchok\nodes\viz\viewer_texture_lite.py:
sverchok\nodes\viz\viewer_typography.py:
sverchok\old_nodes\profile_mk2.py:
sverchok\utils\sv_obj_helper.py:


```

**Comment by Durman** [comment]
If it is bug of blender probably it is better to wait when it will be fix and don't do any changes in Sverchok?

**Comment by zeffii** [comment]
it is not a bug. see the link at the very top.( I do think it's s stupid situation tho...  )

i don't expect much difficulty implementing `pointerproperty` (for materials, texts, single objects) instead of `StringProperty`, but it will be more work than I would like.

fixing it will be better for us in the long term.

**Comment by zeffii** [comment]
i'll need to facilitate pointerproperty within `iojson` too

**Comment by zeffii** [comment]
i think i'll reserve a kw naming conventing
```python
    self.filename
    self.pointer_property_of_filename
```

**Comment by zeffii** [comment]
this is the deal
```
    collection: bpy.props.PointerProperty(
        name="collection name", 
        poll=find_collections,   # optionally filter items out of the list of Collections presented to user
        type=bpy.types.Collection, # what kind of objects are we showing
        update=on_updateNode)  # what to execute when a collection is selected

.... then ui code
        col.prop_search(self, 'collection', bpy.data, 'collections', text='', icon='GROUP')

```
- when picked, `self.collection` will be a reference to the the collection,  which can be queried as if you were using `bpy.data.collections[some_name]`
- the selected Collection will update, if you change its name elsewhere

**Comment by zeffii** [comment]
but it seems updating the name of the collection elsewhere, while it does update the selected name in the prop_search, it does not trigger "update" of that property.

**Comment by zeffii** [comment]
and so it's done like this

https://github.com/nortikin/sverchok/blob/846dcbfeb8bf40718087bac01c59b5cc71b8c971/nodes/scene/collection_picker_mk1.py#L17-L53

**Comment by zeffii** [comment]
and that can be stated much more tersely than i've settled on in the above code. which is really nice.

**Comment by zeffii** [comment]
i imagine self.collection can be set programmatically too.. incase iojson needs populate these kinds of pointerproperties

**Comment by zeffii** [comment]
There's a lot of nodes to do, and I don't mind doing them.. but i can't guarantee that fixing in the correct way won't break most json/.blends.
