### ISSUE TITLE
adjust polyline bspline resolution preview 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3093]
Request : Option to adjust polyline bspline resolution preview to reduce the polygoncount if needed 

![image](https://user-images.githubusercontent.com/49908008/79922336-08dba680-8434-11ea-84fd-86bec0c4750e.png)

**Comment by zeffii** [comment]
yeah, that's a useful option to have. will do asap

**Comment by zeffii** [comment]
added https://github.com/nortikin/sverchok/pull/3095
