### ISSUE TITLE
Taper Sweep Confusion

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3094]
I am not sure how to use "Taper Sweep" node, it seems to be doing Taper to Sweep (?) but how to pass the "Curve" and "shape" to taper for Surface is not as clear cut as "Bevel A Curve". Are we missing Bevel A Curve for Surface?

<img width="858" alt="Screen Shot 2020-04-22 at 2 15 55 pm" src="https://user-images.githubusercontent.com/3952687/79939993-d5d0fb80-84a3-11ea-9b32-ae670f383ef6.png">

[surface_taper_sweep_002.blend.zip](https://github.com/nortikin/sverchok/files/4513763/surface_taper_sweep_002.blend.zip)

**Comment by portnov** [comment]
Check out the documentation and examples in it :)
https://github.com/nortikin/sverchok/blob/master/docs/nodes/surface/taper_sweep.rst

**Comment by portnov** [comment]
And yes, there is no direct analog of "bevel a curve" node, which would make a Surface object. Not yet.

**Comment by enzyme69** [comment]
Ah thanks for the documentation, very helpful! Now I got it. Cheers~

<img width="859" alt="Screen Shot 2020-04-23 at 12 50 47 am" src="https://user-images.githubusercontent.com/3952687/79997051-7a7f2780-84fc-11ea-9958-2a2455bd7ec3.png">
