### ISSUE TITLE
Polyline Viewer's Output Curves does not have Material applied

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3096]
## Problem statement

I made a bunch of curve via Polyline Viewer, assigning a Material. However the generated curve does not have the Material assigned.

[curve_material_not_applied.blend.zip](https://github.com/nortikin/sverchok/files/4515570/curve_material_not_applied.blend.zip)
<img width="647" alt="Screen Shot 2020-04-22 at 8 41 33 pm" src="https://user-images.githubusercontent.com/3952687/79973056-3a0eb200-84da-11ea-9faf-e8acab9d35a1.png">

**Comment by zeffii** [comment]
thanks i'll look at it. 

your exact version of Blender please.

**Comment by zeffii** [comment]
this is directly related to the [prop_search issue](https://github.com/nortikin/sverchok/issues/3091) , i want you to read that list of nodes / files and understand that all of those nodes are not going to work correctly until a canonical solution is implemented for dealing with the result of a `prop_search`.  This means there is no need to start a new Issue, just add a comment and i'll try to prioritize those nodes.

here i've fixed this node for now, but it is not a nice solution. https://github.com/nortikin/sverchok/pull/3099
