### ISSUE TITLE
adding new sockets to monads

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3100]
@zeffii Does monads working? I have tried add sockets to `monads` in 2.81 and 2.83 with no luck.

**Comment by zeffii** [comment]
adding sockets by linking to the "connect me" should work.. if the socket is 

| type |
|------|
| SvStringSocket |
| SvVerticesSocket |
| SvMatrixSocket |

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/afef161defbec1ba821ca33ed58e0b969b7e2faa/core/monad.py#L40-L44

**Comment by zeffii** [comment]
anything else should really be added. gradually

**Comment by zeffii** [comment]
anything else will create a socket only, without default value (and therefore monad will be in an error state until it is fully connected with input sockets when no default is supplied)

![image](https://user-images.githubusercontent.com/619340/80077514-e2119300-854d-11ea-9bdf-bde1da31b5d2.png)

**Comment by zeffii** [comment]
currently the `Add New Socket` inputs/outputs operator is working from what I can tell. Else show me

**Comment by zeffii** [comment]
but it seems Add new socket for `outputs` is missing the name param. let me fix it.

**Comment by zeffii** [comment]
see **utils/monad.py**
```python

    def get_prop_dict(self):
        prop_dict = {}
        prop_dict['name'] = self.new_prop_name

        # we do not set the slider on the <output node> sockets
        if self.kind == 'outputs':
            return {}

        ...

```
note to self, if the new socket is being added to the output node, then 
 - do not set prop_name
 - make sure the name param is set for the socket

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3101 i hope this resolves it

**Comment by Durman** [comment]
I have problem in this PR #3097 then only with creating any inputs / outputs of a monad. I does not see reason for this. I will try delete all my code if it cause the problem.

**Comment by Durman** [comment]
Looks it is problem with inheritance order. Update of  `SvSocketAquisition` is overridden by update of `SverchCustomTreeNode`.
https://github.com/nortikin/sverchok/blob/cc02b0ec2f45bb7e09a71eab289e8902a6a366ac/nodes/scene/monad.py#L130

**Comment by Durman** [comment]
It looks like change order:
`class SvGroupInputsNodeExp(Node, SvSocketAquisition, SverchCustomTreeNode):`
`class SvGroupOutputsNodeExp(Node, SvSocketAquisition, SverchCustomTreeNode):`
is solving the issue.

**Comment by zeffii** [comment]
ok, then I fixed a different bug :)  Feel free to change the order of those class references in your Branch.  This problem is not exhibited in current Master, on my machine..

**Comment by zeffii** [comment]
given
```python
class somename(SomeOne, SomeTwo, SomeThree):
```
I thought the class SomeThree would override any similar methods found in SomeTwo or SomeOne

**Comment by Durman** [comment]
```
>>> sverchok.nodes.scene.monad.SvGroupInputsNodeExp.mro()
[<class 'sverchok.nodes.scene.monad.SvGroupInputsNodeExp'>, <class 'bpy_types.Node'>, <class 'bpy_struct'>, <class 'sverchok.node_tree.SverchCustomTreeNode'>, <class 'sverchok.nodes.scene.monad.SvSocketAquisition'>, <class 'object'>]
```
