### ISSUE TITLE
sv_main_handler

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3106]
https://github.com/nortikin/sverchok/blob/371b3c727911bdaa707fe17b9dd54d0ce49ae6a6/core/handlers.py#L126-L129
@zeffii Can you explain purpose of this handler? It looks like description is outdated.

**Comment by zeffii** [comment]
make a better description then.

**Comment by Durman** [comment]
I will do. Do you no what this handler should do?

**Comment by zeffii** [comment]
it is triggered by app.hanlder.depsgraph_pre, which receives an ungodly amount of triggers from thinks like adding a bpy.data.text to data.object ..or really anything that would cause the depsgraph to be re-evaluated.

**Comment by Durman** [comment]
I suppose this conditions is never true.

```Python
        if ng.has_changed:
            print('depsgraph_update_pre called - ng.has_changed -> ')

            ng.process()
```

This is description is also does not fit to what this method actual do. Because it update tree from itself.
https://github.com/nortikin/sverchok/blob/c6661e810504cf5e4c00f07b8134b586f156cc90/node_tree.py#L294-L298
I remember in 2.79 update method was just marking that a tree was changed but handler do the update work.
Probably `sv_main_handler` method can be deleted.

**Comment by zeffii** [comment]
i'd love to remove that event handler

**Comment by Durman** [comment]
I would too. But I don't know does deleting of this code effect anything. 
```Python
    if depsgraph_need:
        sv_depsgraph = bpy.context.evaluated_depsgraph_get()
```

By the way solution of such design in 2.79 was caused by the fact that `update` method is triggered many times during only one simple action in node tree.

**Comment by zeffii** [comment]
yeah, that would need to stay

**Comment by zeffii** [comment]
or...maybe `msgbus` implemented more granular per all objects that would usefully trigger an update to it.
