### ISSUE TITLE
Noise Displace -> Custom Displace?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3109]
Previously:
https://github.com/nortikin/sverchok/issues/199
https://github.com/nortikin/sverchok/issues/1248

Until NOISIZE aka Noise Displace node arrive:
<img width="713" alt="Screen Shot 2020-04-25 at 10 54 36 am" src="https://user-images.githubusercontent.com/3952687/80267268-28e4c180-86e3-11ea-86c8-8c027f040188.png">

But Noise Displace node seems to be "missing" a simple displacement (like Blender Displace Modifier) with custom vector field? I just want to push it out based on weight.

<img width="1164" alt="Screen Shot 2020-04-25 at 10 56 00 am" src="https://user-images.githubusercontent.com/3952687/80267339-909b0c80-86e3-11ea-9e58-7f1a681add80.png">

[masking_004.blend.zip](https://github.com/nortikin/sverchok/files/4532122/masking_004.blend.zip)

And another question: is there in anyway we can "smooth out" or add contrast to weight or areas?

**Comment by enzyme69** [comment]
<img width="906" alt="Screen Shot 2020-04-25 at 11 09 04 am" src="https://user-images.githubusercontent.com/3952687/80267608-3ac76400-86e5-11ea-8de7-55c877e1ec35.png">
[masking_005.blend.zip](https://github.com/nortikin/sverchok/files/4532133/masking_005.blend.zip)

This one kind of does it, but not considering the mesh normal, I don't think.

**Comment by enzyme69** [comment]
I wonder if this is the most correct with Move node, but still I supposed Noise Displace node can have Custom Vector or something that just push / pull based on weight.

<img width="994" alt="Screen Shot 2020-04-25 at 11 14 53 am" src="https://user-images.githubusercontent.com/3952687/80267756-07d1a000-86e6-11ea-9cd0-d7e01e2c5db3.png">

**Comment by portnov** [comment]
"Displace with custom Vector Field" is called "Apply Vector Field" node. There are also "Apply Vector Field to Curve" and "Apply Vector Field to Surface" nodes.

**Comment by portnov** [comment]
Well, there is one "miss-function": Apply Vector Field does not know anything about mesh normals, it just displaces points along the field.
I'll consider either developing a new node or adding a function to this node, to displace along mesh's normals...
