### ISSUE TITLE
Why SV Box and Subdivide does not Catmull-Clark?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3110]
Something that confuses me, why is it SVerchok Box and Subdivision does not give Catmull Clark smooth / when subdivided it does not give sphere? instead it gives a fat rounded box.

<img width="1158" alt="Screen Shot 2020-04-25 at 11 01 31 am" src="https://user-images.githubusercontent.com/3952687/80267428-351d4e80-86e4-11ea-8ef2-ee0fce23efd4.png">

**Comment by portnov** [comment]
Sverchok uses Blender's bmesh API for subdivision. And there is no API for Catmull-Clark subdivision in Blender :/

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/80279482-45422780-86fe-11ea-877d-3b963d85a650.png)

**Comment by zeffii** [comment]
the subdivision node produces that kind of fat-rounded cube output, with the `divx=4, divy=4, divz=4` input, and other options..  we are just calling bmesh operators here.
