### ISSUE TITLE
IDEA: Proposing "Macro" that can be triggered like Command Recorder button

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3111]
One thing slightly "lacking" with current nodes workflow like SVerchok is: 
The non existence of **3D View User Interface** that can be connected into Nodes while interfacing with 3D objects in the scene.

Think of it like working in 3D View on an object, but with ability to quickly select component, mask, and then performing actions while building up Node Tree in the background.

If anyone ever uses BoxCutter addon, that's one example of brilliant tool interface that uses Blender Boolean Modifier and many Blender modeling function into one toolkits. It's very handson tool, while maintaining the procedurality thanks to Boolean modifier.

I have a little interesting proposal that is related to another Blender addon called **Command Recorder**.
https://github.com/Muthird/CommandRecorder2.8

One potential usage is if we have a node tree that simply _extrude_ and _inset_, and we like to apply it into mesh component in edit mode. Again and again.

(Perhaps I am thinking of something that Sorcar Addon is more suitable for, but I just save it here for now.)

<img width="990" alt="Screen Shot 2020-04-25 at 12 53 24 pm" src="https://user-images.githubusercontent.com/3952687/80269587-6140cb80-86f4-11ea-951a-9c3e5b92f632.png"> 

<img width="1280" alt="Screen Shot 2020-04-25 at 12 56 43 pm" src="https://user-images.githubusercontent.com/3952687/80269580-5b4aea80-86f4-11ea-940a-652d6db5f3eb.png">

**Comment by enzyme69** [comment]
I thought about this because I am looking at Blender KitBashing idea and also Tissue addon and Piperator. Basically users like to be able to select area of mesh (components) and then kit bash something on top of it. Would be nice if SVerchok can function like that.

**Comment by enzyme69** [comment]
That "Play" button and other interface is non existences yet in SVerchok, but imagine things like below become very easy. It does remind me of Tissue addon "adaptive face" but giving user more of hands on experience.

<img width="1182" alt="Screen Shot 2020-04-25 at 1 14 34 pm" src="https://user-images.githubusercontent.com/3952687/80269855-b7167300-86f6-11ea-90dc-8cea6a5e536f.png">

**Comment by enzyme69** [comment]
Quickly I realized a couple of things:
- Smaller or bigger area of extrusion means a different value of extrusions, which means we need to have a way to tweak the value after "Play" button is pressed.
- Sverchok does not usually work in component level / edit mode context, but in this case of extruding and macro operation, the "Play" Macro button should work in component level.

In the end this might be some kind of ways users can operate on components while running a series of macro operators, and quickly go back to the component and replace that component with the processed result.

**Comment by enzyme69** [comment]
"Face Set" is a nice concept that can be borrowed from Blender Sculpting, to separate parts and then make each one as modular as possible. Probably it's not unlike what we could already create incorporated with SVerchok.

I look at Archimesh addon and I can already see how SVerchok works more or less the same, it's just that extra UI interface that is missing.

<img width="813" alt="Screen Shot 2020-04-25 at 3 34 09 pm" src="https://user-images.githubusercontent.com/3952687/80272155-3d888000-870a-11ea-9618-700deebf79d8.png">

**Comment by enzyme69** [comment]
<img width="859" alt="Screen Shot 2020-04-25 at 3 45 10 pm" src="https://user-images.githubusercontent.com/3952687/80272344-c18f3780-870b-11ea-9362-5b08a502ab41.png">
 
Here is another example where BoxCutter addon take advantage of modular shape from SVerchok (current caviat: BoxCutter needs the cutter from Collection) and then from that shape, BoxCutter can use its special interface to place the cutter (as Boolean) into place.

I am thinking with "macro" SVerchok can simply assign it into Component, instead of boolean. Cleaner result.

**Comment by enzyme69** [comment]
Boolean itself is not a bad thing actually... with some kind of modular parts we could easily create "Cutters" like in case of BoxCutter:

<img width="522" alt="Screen Shot 2020-04-25 at 4 02 26 pm" src="https://user-images.githubusercontent.com/3952687/80272561-34011700-870e-11ea-8559-f634937e55de.png">

https://www.youtube.com/watch?v=a6rPjlLGzA4&feature=youtu.be

**Comment by Durman** [comment]
I think the problem is that Sverchok does not designed for procedural modeling in general its purpose is to create architectural shapes what is more specific. Most developers are not interested in interaction with mesh manually.

**Comment by enzyme69** [comment]
Yeah, maybe I bury this idea for now...

**Comment by nortikin** [comment]
I thought of it some.
But it is menu in 3D, that represents examples of sverchok menu (allready exists) + space search menu part with > < features, you know. Last means you can choose object and apply node tree as modifier. it means, script will get selected object as node object in  with farthere nodes process. We can do it.
