### ISSUE TITLE
observations on nodes

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3115]
- `bisect` should not require edge_pol to perform a useful operation.

filter verts given a z limit
![image](https://user-images.githubusercontent.com/619340/80281408-3615a680-870b-11ea-9f94-f589d22fe0aa.png)

![image](https://user-images.githubusercontent.com/619340/80281521-fb603e00-870b-11ea-87a2-2b85760c56e4.png)

**Comment by zeffii** [comment]
- automatic VD linking, should not unhide sockets

**Comment by vicdoval** [comment]
> bisect should not require edge_pol to perform a useful operation.

you can use `Distante Point Plane` for that task
![image](https://user-images.githubusercontent.com/10011941/80321982-e544a180-8821-11ea-85ae-0c24573ada3c.png)

**Comment by zeffii** [comment]
- subdivide  node should not require edges, if faces is provided
