### ISSUE TITLE
SvBVHtreeNode

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3116]
I have found that this node is not used. Can I delete it? 
https://github.com/nortikin/sverchok/blob/966a0650a285f8cd4f1f4b7236d2b9f570b23852/nodes/scene/create_bvh_tree.py#L27

**Comment by zeffii** [comment]
i don't see any dependencies for it either. yeah, it can go

**Comment by Durman** [comment]
deleted here #3097
