### ISSUE TITLE
node.create_sockets

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3123]
It looks like it also is not used anywhere.
https://github.com/nortikin/sverchok/blob/93e9d4d4bdaa849ffddf5f9da2e32bea260f2c1d/node_tree.py#L571-L581

**Comment by zeffii** [comment]
make a branch, and see what breaks :) i'd only be worried about affecting Monads.

**Comment by zeffii** [comment]
then also the call in `sv_init`  to `create_sockets` is also a no op.

i think once upon a time @portnov made a wrapper for `node.process()`, (grep "input_descriptors") which we retain in data_structure.py, but it was never used in a node. I think the wrapper can be removed too
https://github.com/nortikin/sverchok/blob/b74b9f0f8076b823c4bd8bc1842b77d39a8b6422/data_structure.py#L1077
