### ISSUE TITLE
is GP Macro broken?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3131]
When I am about to use GP+ Macro thing, it's broken. Strange... I'm going crazy.

<img width="1103" alt="Screen Shot 2020-04-28 at 8 43 25 am" src="https://user-images.githubusercontent.com/3952687/80428080-638d6a80-892c-11ea-85a6-4b955f80b6f0.png">

**Comment by enzyme69** [comment]
Also this one is not Beta, it does not even work: -- not reporting bug or anything.

<img width="1027" alt="Screen Shot 2020-04-28 at 8 45 21 am" src="https://user-images.githubusercontent.com/3952687/80428197-a2232500-892c-11ea-9986-d855c2d10b4b.png">

**Comment by vicdoval** [comment]
the gp+ is working 
![image](https://user-images.githubusercontent.com/10011941/80431350-88b0b780-88f1-11ea-8c91-a9ab763be66b.png)

**Comment by enzyme69** [comment]
I just remember I am actually using 2.83 beta, the setup above works with 2.82 official.

I guess this is too early of bug report?

```
location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/object_nodes/get_asset_properties.py", line 176, in draw_buttons
    self.draw_gp_options(context, layout)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/object_nodes/get_asset_properties.py", line 145, in draw_gp_options
    layout.prop_search(self, 'gp_layer', bpy.data.grease_pencils[self.gp_name], 'layers', text='layer')
KeyError: 'bpy_prop_collection[key]: key "   Stroke" not found'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/object_nodes/get_asset_properties.py", line 176, in draw_buttons
    self.draw_gp_options(context, layout)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/object_nodes/get_asset_properties.py", line 145, in draw_gp_options
    layout.prop_search(self, 'gp_layer', bpy.data.grease_pencils[self.gp_name], 'layers', text='layer')
KeyError: 'bpy_prop_collection[key]: key "   Stroke" not found'

location: <unknown location>:-1

```

[Screen Recording 2020-04-28 at 11.01.05 am.mov.zip](https://github.com/nortikin/sverchok/files/4542824/Screen.Recording.2020-04-28.at.11.01.05.am.mov.zip)

**Comment by zeffii** [comment]
@enzyme69  GPencil draw is Beta. because i say so. and that's why it has a ridiculous warning.
![image](https://user-images.githubusercontent.com/619340/80460082-9c7d0d80-8933-11ea-83ae-9d0825db4c1a.png)

it does not draw dots, it draws strokes.. so simply a Vector node as input will produce nothing.
![image](https://user-images.githubusercontent.com/619340/80460706-828ffa80-8934-11ea-82c7-124d0a6659d4.png)

lastly, the bug you mention is in `object_nodes/get_asset_properties.py` ( bpy_data/`Object ID Selector Node`).
```
KeyError: 'bpy_prop_collection[key]: key "   Stroke" not found'
```
which... is due to an API change in Blender. https://github.com/nortikin/sverchok/issues/3091

**Comment by zeffii** [comment]
a short documentation for the GreasePencil node

- This node makes GreasePencil objects
- The text field is for manually giving the GreasePencil object a name ( if this field is empty, the node ignores you)
- The frame input, has a button that will auto connect a frame node, to get the frame. But you could use a Number node too if you want to make things difficult
- The coordinates socket expects polyline data, so sequences of Verts.. not a single vert by itself
- Draw cyclic, should work.. not sure i've tested this
- pressure.. try it. might be a no-op
- Stroke and Fill colors should work. you can feed it a unique color per "stroke",  so if your NGon is outputting 2 ngons, you can pass the Stroke socket two stroke colors.

**Comment by zeffii** [comment]
i'm closing this because it is another aspect of the `prop_search` issue i've been banging on about in https://github.com/nortikin/sverchok/issues/3091
