### ISSUE TITLE
Something wrong with Formula node?

### ISSUE THREAD

**Issue by Sanva** [nortikin/sverchok#3139]
## Problem statement

I can't follow *Lesson 01 - A Plane* ( http://nikitron.cc.ua/sverch/html/Unit_01/lesson_01.html ), I think there is something wrong with Formula module.

## Steps to reproduce

1. Add Formula modules with stethoscopes to see result, with an expression like 
```python
[[0,1],[1,2],[2,3],[3,0]]
```

![sverchok-formula](https://user-images.githubusercontent.com/911204/80576479-8d669000-8a05-11ea-90ac-ff6bc1f23910.png)

## Expected result

Something like the first stethoscope is showing, which I made from 4 list inputs and a list join with mix and wrap. It works and allows me to create the plane edges with it.

## Actual result

Neither one of 4 combinations of Formula looks like generating the expected result.

## Sverchok version

Installed yesterday from https://github.com/nortikin/sverchok/archive/master.zip and updated today with add-on preferences button. I'm using Blender v2.82.7 in Linux.

**Comment by zeffii** [comment]
good thing the function that this node calls to produce the output, is rather short.
```python
    def process(self):

        if not self.outputs[0].is_linked:
            return

        var_names = self.get_variables()
        inputs = self.get_input()

        results = []

        if var_names:
            input_values = [inputs.get(name, [[0]]) for name in var_names]
            parameters = match_long_repeat(input_values)
        else:
            parameters = [[[None]]]

        for objects in zip(*parameters):
            object_results = []
            for values in zip_long_repeat(*objects):
                variables = dict(zip(var_names, values))
                vector = []
                for formula in self.formulas():
                    if formula:
                        value = safe_eval(formula, variables)
                        vector.append(value)
                if self.separate:
                    object_results.append(vector)
                else:
                    object_results.extend(vector)
            results.append(object_results)

        if self.wrap:
            results = [results]

        self.outputs['Result'].sv_set(results)
```

**Comment by vicdoval** [comment]
On the meantime you can use "Topology Simple" node 
![image](https://user-images.githubusercontent.com/10011941/80607313-a5ee9e80-8a35-11ea-9e3b-ce421812c6b3.png)

**Comment by zeffii** [comment]
I think the docs need to be updated. the old VD node accepted a wider variety of "malformed" topology. See there's a `list count` in socket mismatch... `edg_pol.4` but `verts.1`
![image](https://user-images.githubusercontent.com/619340/80608965-dafbf080-8a37-11ea-83d7-7ed0721b6c7f.png)

**Comment by qinglangee** [comment]
Stethoscope's output is surrounded by '[ ]', which is the same as python list's symble. I think it's better to change to another one.

**Comment by zeffii** [comment]
in beta nodes i've added `formula+`

![image](https://user-images.githubusercontent.com/619340/82122663-3bf42a00-9795-11ea-941e-8a6d931a97a9.png)

docs are incoming.
there's no way i'm going to fix the existing node while 
  - preserving my sanity.
  - not breaking many gists/blends,
