### ISSUE TITLE
Select Similar node does not seem to work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3146]
@vicdoval I tried to use this node, supposed to work but I have question about how to use it. Any documentation?

[select_similar_does_not_work_001.blend.zip](https://github.com/nortikin/sverchok/files/4557968/select_similar_does_not_work_001.blend.zip)
<img width="979" alt="Screen Shot 2020-04-30 at 9 34 32 pm" src="https://user-images.githubusercontent.com/3952687/80705813-740b3400-8b2a-11ea-8113-5f8d87e3f8ae.png">

I know the alternative Component Analyzer but I want to see how to use this Select Similar node to work...

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/2dbfffccea46730391a65d0837a7a570835f57dd/docs/nodes/analyzer/select_similar.rst

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/search?q=select+similar&unscoped_q=select+similar

come on jjimmy :)

**Comment by zeffii** [comment]
https://gist.github.com/56507cdf2d2085b4630494741c4d68dc

![image](https://user-images.githubusercontent.com/619340/80729807-0ef31680-8b09-11ea-960e-7320fa7913f6.png)

**Comment by vicdoval** [comment]
@enzyme69  next time you click to see the online help you will find it if it exists :)

**Comment by enzyme69** [comment]
😆 My SV logic must have been somewhere else last night... Ok now I got it. Thanks again @zeffii

**Comment by enzyme69** [comment]
@vicdoval So many nodes do nothing when I click on help, in fact maybe it does not work anymore... can you make video capture on how to get into the help?

**Comment by zeffii** [comment]
the help system works fine, i mean here exactly that "when you press this button, if Sverchok can find the help file locally, then it can display the file at the same (transformed) path of the online help". 

The problem for any node in the analyzers category is that somehow/someone changed the directory name from `analyzers` to `analyzer`, and that means the help system was looking in a directory that had no docs, and couldn't show the docs it couldn't find. @vicdoval pushed a simple fix to master.

upgrade at your own peril :)   or in future use the Search feature on github like i suggest above, if the node has docs you'll find it there in various forms.  And then if you're feeling helpful tell us one of two things
- " node X has docs, ( link ) but the help system can't find them, HALP
- " node X has no docs ( see my search link .. nothing )
