### ISSUE TITLE
Formula node can not return the original expression

### ISSUE THREAD

**Issue by qinglangee** [nortikin/sverchok#3157]
## Problem statement

The formula node always return a list of expressions, even if dimensions is set to 1. 

## Expected result

When dimensions is set to 1, formula node return the origin expression.

## Actual result

return a list

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip   v0.6.0.0

**Comment by portnov** [comment]
Isn't it the same as #3139

**Comment by qinglangee** [comment]
Yes.
