### ISSUE TITLE
Genetic Algorithm PR

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3160]
## We need GA

I had attempt with GA without side libs in SNL-demo
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/demo/Genetic_algorithm.py

## Starting new branch of GA in monad

https://github.com/nortikin/sverchok/tree/2020_GeneticAlgorithm

## Steps
Hope it will be only start.

- [ ] - modify SNL to match monad
- [ ] - make monad class has GA def with loop and assigning correct values with checks

Maybe i will need help to understand monad.
Also not leaving my aim - deap insertion (in Sverchok external)

## Preflight Checklist
- [ ] - Code changes complete.
- [ ] - Code documentation complete.
- [ ] - Documentation for users complete (or not required, if user never sees these changes).
- [ ] - Manual testing done.
- [ ] - Unit-tests implemented.
- [ ] - Ready for merge.

**Comment by nortikin** [comment]
It is long time needed stuff. Sadly, we did not it till now.

**Comment by portnov** [comment]
What problem does this GA solve?

**Comment by nortikin** [comment]
> What problem does this GA solve?

https://www.youtube.com/watch?v=3U4TbXMn41E
https://www.youtube.com/watch?v=mj3-16y4I0k
https://www.youtube.com/watch?v=xcb2O1LPENQ

**Comment by nortikin** [comment]
we have bu the way, node neuro elman that is broken

**Comment by nortikin** [comment]
Thinking of courses to get more knowlage of GA and other things. But it is not cheap at all. hope i could do it.

**Comment by nortikin** [comment]
http://www.interactivearchitecture.org/automated-design-using-genetic-algorithm.html
https://arxiv.org/pdf/1810.03522.pdf
https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU

**Comment by nortikin** [comment]
Idea is to 
1.insert two - "criterias" and "driving values" (two sockets that can have equal lists of float data)
2.output one - "driving values" to insert node A number. it is not socket input, but assignation input
3.GA are happening inside monad.
in fact, we need first two sockets to be reserved in this case for criterias and values
![Снимок экрана от 2020-05-04 21-03-51](https://user-images.githubusercontent.com/5783432/80997951-cdd16e00-8e4a-11ea-8168-e9d64a49526a.png)

**Comment by nortikin** [comment]
so, i need the monad to loop every population and gather values for next generation to loop again.
It means, we need global property that gather generations/populations.

**Comment by vicdoval** [comment]
@nortikin  check #3284 ;)

**Comment by nortikin** [comment]
I wonnot continue
