### ISSUE TITLE
Saving Preset with Text for Profile Parametric Node Added Spaces

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3164]
## Problem statement
Profile Parametric node does not like Text with Spaces

## Steps to reproduce

1. Have node tree with Profile Parametric node + Text
2. Save node tree as Preset
3. Reload Preset into new Blend. 
4. Text goes along when you reload but it has spaces in front of the name
5. Node Tree broken until you remove the spaces from Text name for Profile Parametric

<img width="655" alt="Screen Shot 2020-05-03 at 11 35 34 am" src="https://user-images.githubusercontent.com/3952687/80896651-ee5ad480-8d33-11ea-8f6f-368620d56351.png">

## Expected result

Profile Parametric should work with text without space, or maybe Saving Preset should not add spaces into the text

## Actual result

If I remove spaces from Text name, it works.

## Sverchok version

Latest Sverchok

VIDEO: Last Part:
https://youtu.be/-Ze3jCniN2U

**Comment by portnov** [comment]
Again prop_search issue :/ @zeffii

**Comment by zeffii** [comment]
there is already 
- an open issue describing this problem... https://github.com/nortikin/sverchok/issues/3091
- an open pullrequest set up to deal with it .. https://github.com/nortikin/sverchok/pull/3133

read them @enzyme69 .
