### ISSUE TITLE
Text Out - Auto Dump seems to be broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3174]
<img width="986" alt="Screen Shot 2020-05-06 at 9 38 05 pm" src="https://user-images.githubusercontent.com/3952687/81175220-7ff16d00-8fe6-11ea-8481-bf4a97157c19.png">

Someone requested "spread sheet" view of data, I was going to use Text, but it was not working.

**Comment by zeffii** [comment]
it's all broken. jiimmy. use an older version of Blender.
https://github.com/nortikin/sverchok/issues/3091

![image](https://user-images.githubusercontent.com/619340/81178426-76e1ab00-8fa8-11ea-8e10-721db68ccdf8.png)

i think you're not reading my responses.

**Comment by enzyme69** [comment]
Roger that. Sorry I was piled up
