### ISSUE TITLE
Nodes that draw to nodeview, motion detection

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3203]
**what?**
i'd like to implement a way for nodes like stethoscope (but any nodeview callback user) to redraw their bgl/blf if they are being moved in the nodetree.

**how?**
maybe use the nodetree.update to store and check a list of callback users in the active_nodetree only, against stored locations in the last update.  Usually we wont have that many nodeview drawing nodes, so overhead is minimal. 

we can implement "minimal distance delta" to discard the movements that are not going to be visually useful to update.

**Comment by zeffii** [comment]
i think there's an update even we can use for this

**Comment by Durman** [comment]
Movements of a node does not trigger node_tree.update. `Busmsg` looks like also is not triggered.

Probably creating of an update button will be most clarity way to refresh drawing because user should not know how to cause tree udpate.

**Comment by Durman** [comment]
Or probably we could create operator with timer which would making tests of position of current node. If position is changed it should check, are there `viewer` nodes among selected and if so call their redraw method.

**Comment by zeffii** [comment]
what about depsgraph handler?  :)

**Comment by Durman** [comment]
I have tested it. It does not react on a node movements.

**Comment by zeffii** [comment]
hmmm.. can't msg bus attach to location parameter of a node..?

**Comment by Durman** [comment]
`Msgbus` is called only if a location was changed via Python but not manually.

**Comment by zeffii** [comment]
ah yes.  ok. i think maybe an operator "overloading" the G key, or use `alt+G` to invoke a move operator wrapper that also retriggers the draw function if the node is a nodeview drawing node.

**Comment by zeffii** [comment]
but that's not very high on my priority list.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3213

**Comment by Durman** [comment]
@zeffii Did you try this? Probably it can become a part of the solution.
https://docs.blender.org/api/current/bpy.app.timers.html#module-bpy.app.timers

**Comment by zeffii** [comment]
these run in "always on" mode? yeah.. i 'm not a fan of it , but without trying my concern may be more prejudice than objective reluctance.
