### ISSUE TITLE
Update issue on connect/disconnect input sockets

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3207]
I have noticed some update issues lately.. this time is related to connection/disconnection of the list joint node.. When connecting/disconnecting the input sockets the updates do not propagate to the other nodes and the rendering is not updated either. There is an error (see terminal output) that I suspect may be due to this failed update behavior. It seems that I have to trigger an update manually by changing something in the upstream nodes. The frame change doesn’t seem to update the nodes either. 

![SV-UpdateIssue](https://user-images.githubusercontent.com/2083719/81626644-4e9fe500-93ca-11ea-8d06-b90488ab3a7e.gif)

```
2020-05-11 20:49:28,806 [ERROR] sverchok.core.update_system: Node  had exception: 'bpy_prop_collection[key]: key "" not found'
Traceback (most recent call last):
  File "/Users/atokirina/Library/Application Support/Blender/2.83/scripts/addons/sverchok/core/update_system.py", line 380, in do_update_general
    node = nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "" not found'



2020-05-11 20:49:36,396 [ERROR] sverchok.core.update_system: Node  had exception: 'bpy_prop_collection[key]: key "" not found'
Traceback (most recent call last):
  File "/Users/atokirina/Library/Application Support/Blender/2.83/scripts/addons/sverchok/core/update_system.py", line 380, in do_update_general
    node = nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "" not found'
```

**Comment by DolphinDream** [comment]
Also it seems that other nodes do not update on frame change anymore.. and have to manually trigger updates.

![SV-UpdateIssue-demo2](https://user-images.githubusercontent.com/2083719/81627358-0255a480-93cc-11ea-9465-602ebab6614d.gif)

**Comment by vicdoval** [comment]
The first issue yo mention I will look into it tomorrow 
The second is related to the animatable nodes, now on frame change only the animatable nodes update, this is a downside of this behaviour (maybe the node viewers should be in this category) 
you can check #3203 but it seems there is not a perfect solution

**Comment by Durman** [comment]
> Also it seems that other nodes do not update on frame change anymore.. and have to manually trigger updates.

I don't think they should for performance reasons. Moving of nodes during animation is not common thing.

**Comment by zeffii** [comment]
these kinds of update-misses are going to confuse newcomers, this is the main problem.

**Comment by Durman** [comment]
I think `update` button for the node would solve the problem.

**Comment by DolphinDream** [comment]
Often times I rearrange the nodes and the stethoscope rendering remains in their initial place. ☹️ I used to be able to just change the frame and have their outputs update and render next to the their new location, but not anymore. It’s not only potentially confusing to the newcomers but also frustrating for expert users as well. And also having to explain to anyone (e.g if you do live noding etc) that if you move some nodes around and they don’t update their rendering properly just hit F5 or tap of the node settings etc just to trigger an update.. this just has bad impression on the add-on as of not being quite polished, aside from being annoying to the user to have to memorize to jump through theses hoops just to get the update right. I understand the performance issues and I’m all for it, but we need to make this updates a little more reliable and hassle free.

Btw, is there a way to capture node relocation and update the nodes rendering output in the node-tree? (e.g. stethoscope, easing, texture viewer etc.. all nodes that have rendering in the node-editor).

As for connecting and disconnecting sockets, for them to not update the final output in the viewport, this update misses is going to be even more confusing. Personally I find myself having to just click around on various nodes to make sure they propagate their output when something doesn't update properly. As a developer this can be even more frustrating, as it is not immediately clear if something doesn’t update correctly because of the node i’m working on or because of other parts of SV not workin properly.

**Comment by zeffii** [comment]
yes two issues here. 

1. 
Stethoscope doesn't update automatically if the node moves, and doesn't anymore (since recent update-mechanism modifications) update when you frame change. Yes, this blows. But expect this to be temporary. 

i'm diving into writing a G (transform) replacement function for the Sverchok node view, this (if it works) will let us piggyback the Mouse movement during transform, and update the nodeview drawing nodes in realtime. (or at the least..when the mouse is released...which may the best compromise)

2. the modifications to the update-mechanism are an attempt to improve efficiency in nodetree updates, i agree this blows during development of new nodes.

I think i can fix 1.

**Comment by zeffii** [comment]
so my answer for 1. is this : https://github.com/nortikin/sverchok/pull/3213

**Comment by vicdoval** [comment]
I couldn't replicate issue 2 seems to work.
Can anyone else replicate this issue?
(super low quality GIF but shows behaviour)
![untitled](https://user-images.githubusercontent.com/10011941/81713023-a2b3d380-9475-11ea-9636-a07bdb9d62aa.gif)
