### ISSUE TITLE
Splitting Cylinder in U and V methods?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3210]
I am exploring of ways to "split" Cylinder in U and V direction. 

So far I figure out a few ways, but it is not perfect especially with UV Connection method and if I enable Cyclic, I cannot get a nice slicing:

<img width="1083" alt="Screen Shot 2020-05-12 at 1 25 48 pm" src="https://user-images.githubusercontent.com/3952687/81635352-6328bf80-9454-11ea-918a-a6602d619219.png"> 

<img width="886" alt="Screen Shot 2020-05-12 at 1 26 59 pm" src="https://user-images.githubusercontent.com/3952687/81635337-5b691b00-9454-11ea-82d4-b5fac209efad.png">

[cylinder_split_002.blend.zip](https://github.com/nortikin/sverchok/files/4613213/cylinder_split_002.blend.zip)

[cylinder_splitB_001.blend.zip](https://github.com/nortikin/sverchok/files/4613212/cylinder_splitB_001.blend.zip)

Is there a more elegant and easy way to do this?

**Comment by enzyme69** [comment]
If I enable cyclic, I am getting this:

<img width="1066" alt="Screen Shot 2020-05-12 at 1 29 28 pm" src="https://user-images.githubusercontent.com/3952687/81635458-9d925c80-9454-11ea-8ea9-f93717574853.png">

**Comment by enzyme69** [comment]
I could also do this, which is the weirdest thing ever, but quite nice. But is there another solution to get stripes selection and separate?

<img width="879" alt="Screen Shot 2020-05-12 at 1 40 22 pm" src="https://user-images.githubusercontent.com/3952687/81636071-31b0f380-9456-11ea-8366-eef6400aebae.png">

[cylinder_split_004.blend.zip](https://github.com/nortikin/sverchok/files/4613244/cylinder_split_004.blend.zip)

**Comment by zeffii** [comment]
#3211 I did a little SNLite lesson, for this but it comes with no other help.

**Comment by enzyme69** [comment]
Probably kind of solved although it's dirty and I need to "delete loose". Will come back in near future, will study Zeffi's example~ cheers~
