### ISSUE TITLE
Random Num Gen error occurred when generating size and weight list length are different

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#3215]
## Problem statement

Random Num Gen error occurred when generating size and weight list length are different.

![image](https://user-images.githubusercontent.com/62538469/81708310-17096980-94ac-11ea-9a09-3365b43ec3d0.png)

when I set generating size to 3, an error didn't occur.

## Expected result
It produces four random numbers between 0 to 2 according to weights.

## Sverchok version
Blender version 2.82 (sub 7), Sverchok version 0.6.0.0
e3fc7a5

**Comment by vicdoval** [comment]
Thanks for reporting!
Now should be fixed, otherwise report back 😃

**Comment by ken26u** [comment]
Thank you for speedy fixing!
It was fixed. 😊
