### ISSUE TITLE
Cubic Spline (in Cyclic mode) to Evaluate Curve

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3220]
@portnov 

i'm wondering, should there be some information transmitted in the Curve data that would tell Evaluate Curve to merge the `last Vertex` into Vertex `0`. ?

![image](https://user-images.githubusercontent.com/619340/81738445-03ed9e00-949a-11ea-8ead-86b2daa6a574.png)

**Comment by portnov** [comment]
Yeah, this question is valid for all types of curves. We could do either:
1) each Curve could know whether it is closed or not. The problem might be, for some more complex curves this probably is not so easy to determine.
2) Or just have a flag in Evaluate Curve to remove the doubled last/first vertex.

**Comment by zeffii** [comment]
yeah if the `curve` object, as in `[curve, curve, curve,...]`, doesn't hold metadata passed in from the Cubic Spline node, then yeah evaluate curve offer a toggle+epsilon.
