### ISSUE TITLE
Display message error

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3221]
I'm suggesting to remove backtrace and move error message above or below an error node.

![2020-05-13_18-44-33](https://user-images.githubusercontent.com/28003269/81827926-4cfd2b00-954a-11ea-8db2-35fff6a27c06.png)

**Comment by vicdoval** [comment]
maybe the backtrace could be optional because is quite handy for bug-fixing

**Comment by Durman** [comment]
I think this feature is first of all for users not for developers. For debugging we already have console.

**Comment by portnov** [comment]
One problem is that our error messages is mostly non-user-friendly. Let's say you've got "tuple index out of range" error. What now? :)

**Comment by portnov** [comment]
I also do not think that stacktraces in the nodeview are useful; it's simpler to read them from console or log.

**Comment by zeffii** [comment]
i implemented it exactly how i wanted it.

**Comment by Durman** [comment]
@zeffii For own usage?

**Comment by zeffii** [comment]
yeah, but i'm open to suggestions.. but please dont just change it because you don't like it. The mechanism is in place, it can be customized with minor changes..

**Comment by Durman** [comment]
@zeffii You can find suggestion above.

**Comment by zeffii** [comment]
no. i mean code suggestions.

**Comment by zeffii** [comment]
i do find that the line in `red` is usually enough to know why the node is not working, so...

**Comment by Durman** [comment]
> yeah, but i'm open to suggestions.

It is strange. If you implemented the feature only for own usage and you are not going to discuss about possible its improvements than I think the feature should not be in master. Better place for the feature would be your own branch for example.

**Comment by zeffii** [comment]
no. I;m OK with allowing it to be modified.  but i implemented it exactly the way i wanted. I do not oppose the suggestion.

**Comment by zeffii** [comment]
and remember, users never see this error unless they manually enable it.

**Comment by zeffii** [comment]
and rembmer also.. Sverchok is full of stuff that we as developers want, where only lateron other people can appreciate why it is implemented (that way).  This is our privilege.

**Comment by zeffii** [comment]
there could be a second bool button 
```
[display error] [ full ]
```
- full on: includes stack track,  drawing to the side
- full off only print the error, above the node

yes i'm ok with that.

**Comment by portnov** [comment]
Btw, did anyone investigate how AN do this (displaying errors)? They seem to have nicer boxes...

**Comment by zeffii** [comment]
we can make it look nicer :)

**Comment by Durman** [comment]
> no. I;m OK with allowing it to be modified. but i implemented it exactly the way i wanted. I do not oppose the suggestion.

I don't understand you. You implemented it the way you wanted it and what? 

The suggestion is in first message of the issue. If you are interested in discussion you can express your opinion about the subject.

**Comment by zeffii** [comment]
> I don't understand you

no problem. i'll make it customizable, or have two modes. `simplefied` and `full` .

>  If you are interested in discussion you can express your opinion about the subject.

i believe i did. already.

**Comment by Durman** [comment]
> Btw, did anyone investigate how AN do this (displaying errors)? They seem to have nicer boxes...

Agree. It is even is connected to the node.

![viewer AN](https://user-images.githubusercontent.com/28003269/83482242-df8d4c00-a4b0-11ea-885b-3233c139b018.gif)

I does not see reasons why it should be done again if solution already exists.

**Comment by zeffii** [comment]
> I does not see reasons why it should be done again if solution already exists.

agreed

**Comment by zeffii** [comment]
There are two separate issues here
- how to draw automatically beside the node regardless of location, and user movement.
     - i've found the way to solve this.  the callback can query the nodetree and the node's current width and location
- drawing backgrounds, this is trivial.

**Comment by zeffii** [comment]
is there a way to go from `n_id` to a reference to the node ? @Durman

**Comment by zeffii** [comment]
it's time for a stethoscope mk3, it will look a lot nicer.

the `draw_callback`  will receive the treename and the nodename ( so rename will kind of break the abstraction until the nodetree is updated.. )

- because the node only offloads info to the drawcallback once per call to process, it must pass information about what node triggered it.
- the data variable will include `nodename` in future, it will be used find information about the node, maybe even call functions on the node.

the draw callback is triggered any time the mouse moves around in the nodeview. it always has. This would be a good opportunity to see if we can cache anything.
