### ISSUE TITLE
Select and Skip By N in Row and Column

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3223]
I am looking at this and it reminds me of my previous question, can someone remind me about a node that "can select mask component every N in column or grid"... I am sure we have it, or maybe I was thinking about Houdini.

<img width="684" alt="Screen Shot 2020-05-14 at 12 49 40 pm" src="https://user-images.githubusercontent.com/3952687/81886976-7321da00-95e1-11ea-85f8-8aa0515e0a61.png">

Here I am looking at checker, and wondering if checker itself can be used to select stripes in U or V / row or column...
[checker_select_002.blend.zip](https://github.com/nortikin/sverchok/files/4625787/checker_select_002.blend.zip)

**Comment by enzyme69** [comment]
Related to this precisely:
https://github.com/nortikin/sverchok/issues/3210

**Comment by enzyme69** [comment]
Something about number range and pattern that sverchok should already have... 

note: I realized "select every N" is indeed from Houdini and also in Sorcar. SVerchok does not have it... yet.

<img width="817" alt="Screen Shot 2020-05-14 at 1 09 12 pm" src="https://user-images.githubusercontent.com/3952687/81888183-28ee2800-95e4-11ea-85f6-5676e962fbd5.png">

**Comment by enzyme69** [comment]
<img width="884" alt="Screen Shot 2020-05-14 at 1 19 11 pm" src="https://user-images.githubusercontent.com/3952687/81888820-8171f500-95e5-11ea-8cd1-ea94783ebe5f.png">

Feels a bit like Sine Wave...

**Comment by enzyme69** [comment]
Might be getting somewhere...
<img width="1234" alt="Screen Shot 2020-05-14 at 1 27 19 pm" src="https://user-images.githubusercontent.com/3952687/81889350-a4e96f80-95e6-11ea-9a10-815859573bd5.png">

**Comment by Durman** [comment]
You can make your proposal, probably someone will interest in implementing it.

**Comment by stansu** [comment]
@enzyme69 
[select_row_column.zip](https://github.com/nortikin/sverchok/files/4626308/select_row_column.zip)

**Comment by portnov** [comment]
The thing with such selections is that the order of faces on the arbitrary mesh can be arbitrary; and they can be connected in any complex topology. So if you just say "select each second face" for arbitrary mesh, you'll probably get weird results. More correct way is to express it in geometric / topological terms: something like "start with this face, then go to this direction, then select the other face"... I couldn't invent any easy way to formulate such requirements. So there is a "turtle-like" API in `sverchok.utils.turtle` and examples of scripted nodes using this API (something with word "turtle" in name).

**Comment by enzyme69** [comment]
Thanks @stansu ~ I will use your setup and talk about it~

<img width="1046" alt="Screen Shot 2020-05-14 at 4 51 39 pm" src="https://user-images.githubusercontent.com/3952687/81902415-729a3b00-9603-11ea-97c2-f1af2fa33493.png">

[row_and_column_002.blend.zip](https://github.com/nortikin/sverchok/files/4626523/row_and_column_002.blend.zip)

@Durman @portnov 
Yes, it'a Skip every N sounds simple I mean should in general expected to work for easy UV grid like surface (Cylinder, Grid). If it requires Turtle and to follow like "edge loop" or "edge ring", then that's probably interesting to know. 

Can Durman or Portnov make video on this kind of thing? Maybe you can have YouTube channel?

Thanks!

**Comment by enzyme69** [comment]
I am still fascinated by the **List Split**, **List Repeat**, but especially **List Item** node... especially when dealing with polygon components.

I know there are plenty more of this list handling that I rarely used.

<img width="1413" alt="Screen Shot 2020-05-14 at 5 02 23 pm" src="https://user-images.githubusercontent.com/3952687/81903192-bc375580-9604-11ea-924b-0324274c5561.png">

<img width="268" alt="Screen Shot 2020-05-14 at 5 02 27 pm" src="https://user-images.githubusercontent.com/3952687/81903188-b93c6500-9604-11ea-993b-2cf8b9ad31f8.png">


[row_and_column_005.blend.zip](https://github.com/nortikin/sverchok/files/4626565/row_and_column_005.blend.zip)

**Comment by enzyme69** [comment]
This method works for lots of uses, but however I am lost in how to get back "List Mask" from those polygon faces as the topology is all messed up now.

**Comment by enzyme69** [comment]
Self reminder that we can also do this already. I just don't know how to transfer it to Polygon Face. And portnov mention about Turtle algorithm, I am curious.

<img width="637" alt="Screen Shot 2020-05-14 at 5 27 25 pm" src="https://user-images.githubusercontent.com/3952687/81905607-4339fd00-9608-11ea-96d4-7ef08294cebc.png">


<img width="522" alt="Screen Shot 2020-05-14 at 5 27 30 pm" src="https://user-images.githubusercontent.com/3952687/81905590-3f0ddf80-9608-11ea-9cff-63b4a66f618f.png">


[U_V_by_edge_002.blend.zip](https://github.com/nortikin/sverchok/files/4626659/U_V_by_edge_002.blend.zip)

**Comment by portnov** [comment]
See #2760, there are some examples.

**Comment by enzyme69** [comment]
Thanks Portnov, I will study them. I guess this one can be left semi-open for future. To be continued...
