### ISSUE TITLE
Formula node changes the location of the socket

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#3225]
## Problem statement

When export to gist and import from gist, if the node has multi sockets, it sorts socket order according to a parameter name but stays connect location.

## Steps to reproduce

1. add a "b" socket.
![image](https://user-images.githubusercontent.com/62538469/81937375-827b4480-962e-11ea-8029-4e60b4abd013.png)

2. next,add an "a" socket.
![image](https://user-images.githubusercontent.com/62538469/81937511-adfe2f00-962e-11ea-945c-6c71bf9d0968.png)
3. export to gist.
4. import from gist
![image](https://user-images.githubusercontent.com/62538469/81937721-f4ec2480-962e-11ea-8ac6-afcc80a197fb.png)

## Expected result
If it changes the location of the socket, fixes the connection as well.

## Sverchok version

Blender version 2.82 (sub 7), Sverchok version 0.6.0.0
6b42044

**Comment by zeffii** [comment]
interesting..

**Comment by zeffii** [comment]
the gist/iojson code doesn't determine the order/location of the sockets, but i think we might have to add a function to the node to make repopulating consistent.

**Comment by zeffii** [comment]
another way to demo this bug is to 
- empty the formula field.
- type in b+a
- node creates the sockets in alphabetic order

![image](https://user-images.githubusercontent.com/619340/81946871-31ecf280-9600-11ea-8226-8f235493c433.png)

and that's exactly what the code suggests it's doing
```python
    def get_variables(self):
        variables = set()

        for formula in self.formulas():
            vs = get_variables(formula)
            variables.update(vs)

        return list(sorted(list(variables)))

    def adjust_sockets(self):
        variables = self.get_variables()
        #self.debug("adjust_sockets:" + str(variables))
        #self.debug("inputs:" + str(self.inputs.keys()))
        for key in self.inputs.keys():
            if (key not in variables) and (key in self.inputs):
                self.debug("Input {} not in variables {}, remove it".format(key, str(variables)))
                self.inputs.remove(self.inputs[key])
        for v in variables:
            if v not in self.inputs:
                self.debug("Variable {} not in inputs {}, add it".format(v, str(self.inputs.keys())))
                self.inputs.new('SvStringsSocket', v)
```

**Comment by zeffii** [comment]
we can do a few things, i'll start by the least likely (and most disruptive)
- make an exception for the way we store the links of any node that connects directly to Formula node,  
    - right now we store links by socket index (for a variety of reasons)
- make a storage_get/set_data function
    - this is best, gives us total control, but is not going to retroactively "fix" links.

**Comment by portnov** [comment]
There are some other nodes with similar problems, so the solution should not involve hardcoding Formula node bl_idname somewhere in iojson code. It should change only some code in the Formula node itself (and maybe other similar).
I remember fixing this for some of similar node, but can't remember which one... :)

**Comment by zeffii** [comment]
agreed. anything we do won't guarantee older jsons will ever load correctly, that information is lost due to the semi sparse nature of the node storage.

**Comment by zeffii** [comment]
but this isn't crazy, imo
```python
        def storage_set_data(self, node_ref):
            '''function to get data when importing from json'''
            data_list = node_ref.get('socket_order_data')
            if data_list:
                data_dict = json.loads(data_list)
                self.restore_sockets_from_stored_dict(data_dict)
    
        def storage_get_data(self, node_ref):
            '''function to set data for exporting json'''
            data = self.get_current_socket_order()
            data_json_str = json.dumps(data)
            node_ref['socket_order_data'] = data_json_str
    
```

**Comment by portnov** [comment]
Possible solution: when writing such sockets information to json, just sort them alphabetically.

**Comment by zeffii** [comment]
no, alphabetic is the currently problematic way. During runtime these sockets can be created incrementally and not be sorted n any reproducable way.  Other than storing use self.inputs as a template
```
def get_current_socket_order(self):
    return {socket.index: socket.name for socket in self.inputs}
```

**Comment by ken26u** [comment]
sorry to interrupt. and also my English grammar.

If I type 'b+a' at once, the order of the socket is alphabetically(a → b). 
but when I type "b" and "a" separately the order is b → a. 
and more I type "b", then I type "+c+a", the order of the socket is "b→a→c". 
so sorting is always working, but only the one entered at that time.

if the node can keep the connection information when the input event occurs.
after input event sort whole parameter and restore connect.
or don't sort.

It is an idea.

**Comment by zeffii** [comment]
if you first have a formula field with `b+c+d` , at runtime whle your editing the tree it creates those in order, and then you decide to add a, the sockets will be `b c d a`.

**Comment by zeffii** [comment]
thanks @ken26u for reporting it :) 

i think we understand the cause, the problem is only what to fix to minimize impact on expected behaviour.

another solution would be at runtime, to always make sure the sockets are sorted alphabetically, this would mean rearranging current sockets at runtime. (is that what you mean @portnov  ?)

**Comment by portnov** [comment]
@zeffii the idea is, the node always works with these inputs by name, not by index. So it does not matter what the order is. If we reorder inputs before writing to json, it should be fine: they will be restored in the same order they were saved.

**Comment by zeffii** [comment]
oooh.. yes, i see!

**Comment by zeffii** [comment]
even this doesn't work
```python
    def storage_set_data(self, node_ref):
        '''function to get data when importing from json'''
        data = node_ref.get('socket_order_data')
        if data:
            with self.sv_throttle_tree_update():
                self.inputs.clear()
                for socket_name in data:
                    self.inputs.new("SvStringsSocket", socket_name)

    def storage_get_data(self, node_ref):
        '''function to set data for exporting json'''
        data_list = [socket.name for socket in self.inputs]
        node_ref['socket_order_data'] = data_list
```
those sockets are getting wiped and rewritten by later updates..

**Comment by zeffii** [comment]
at the time storage_set_data is called, variables is still the default ` ['x', 'y'] `

**Comment by zeffii** [comment]
after thinking about this, i think the thing to do is to always make sure the sockets are alphabetic in order, and rearrange them line (link/unlink) at runtime when the user modifies the formula fields. The current method is growing the socket list at runtime in a way that can not be reproduced without a lot of tiptoeing around and if/elses in the gist code.

but the fix will not be retroactive.  none of them would be.

**Comment by zeffii** [comment]
If i get some people to agree to it.. i'll be happy to implement "on_the_fly_socket_reordering" . so this never happens again.

**Comment by portnov** [comment]
I would be glad if you implement this :)

**Comment by zeffii** [comment]
good enough for me.

**Comment by zeffii** [comment]
This was closed automatically. @ken26u if you'd like to try a different version of this node ( it can't be hotswapped yet), then it's in the Beta/Alpha list, called "Formula+".  If you test it , and it's to your liking i might move it to the Numbers category and remove the exusting Formula3.py to old nodes.

https://github.com/nortikin/sverchok/pull/3234 .. i'm updating the doc, but the tooltips of the new buttons have information anyway.

**Comment by ken26u** [comment]
I tried formula+ and it was good enough for me.
thank you.😊
![image](https://user-images.githubusercontent.com/62538469/82121283-b8ebc780-97c6-11ea-89fb-468d952f0c32.png)
but if the node didn't have any parameter, it looks like the split option is enabled by default.
so I couldn't make below patterns of text.

**Comment by zeffii** [comment]
let me look at it : )

**Comment by zeffii** [comment]
yes, i do use a different parser..  there are parts of this node that i have not yet stared at long enough :)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/82122221-83c58200-9792-11ea-8bb0-b54f382e5ba0.png)

**Comment by zeffii** [comment]
the little python icon is to enable/disable use of the AST.literal_eval module.
when that's off, (as shown) then the original "safe_eval" is used.

**Comment by ken26u** [comment]
I could make the texts. I'd say good. thank you : )

**Comment by zeffii** [comment]
ok. i'll keep it in beta for a while.
