### ISSUE TITLE
Merge by distance mask

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3226]
Merge by distance mask returns None:
![2020-05-14_21-43-23](https://user-images.githubusercontent.com/28003269/81967504-10a1fb80-962c-11ea-8f50-54d426a0cc38.png)

**Comment by vicdoval** [comment]
the output mask returns the input mask "updated" after the merge.
If no input mask no output mask.

**Comment by Durman** [comment]
The documentation is mute about it. Probably it worth to specify. 

Do you no the purpose of this mask? I thought it returns vertices which was removed or merged with other.

**Comment by vicdoval** [comment]
I dont know why the "online" docs are not updated, I thought it was already automatic.. The last doc specifies it and has one example using it: https://github.com/nortikin/sverchok/blob/master/docs/nodes/modifier_change/merge_by_distance.rst

**Comment by Durman** [comment]
I'm just trying to say that description is not clear enough. What kind of mask it does not say.
> **Mask** The mask after the merge

Why by the way it returns None instead of empty list? It would be less ambiguous.

**Comment by Durman** [comment]
Also this node is cause of such messages in debug mode: 
`[DEBUG] sverchok.utils.sv_bmesh_utils: Unexisting vert_data[0] [0 - 0]`

I guess it points that some logic in the node is incorrect.
