### ISSUE TITLE
reboot (F8) + some actions = crash

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3229]
## Problem statement

Crash with pressing Ctrl+C on selected node.

## Steps to reproduce

1. Open file - [untitled1.zip](https://github.com/nortikin/sverchok/files/4633681/untitled1.zip)
2. reload.script (F8)
3. select node
4. crash

## Sverchok version

master

It looks like it crash only if a file was open.
I don't know even where to look.

**Comment by vicdoval** [comment]
> It looks like it crash only if a file was open.

What do you mean?

**Comment by Durman** [comment]
I can't reproduce it in new file. So it crashes only if to create one node then save it in a file then close and open the file.

**Comment by Durman** [comment]
Probably there are some references to blender data inside a node properties or its sockets which are read by `Ctrl+C` operator.

**Comment by Durman** [comment]
Can be useful for catching the error:
https://docs.python.org/dev/library/faulthandler.html

**Comment by Durman** [comment]
Using pointers anywhere in code can crash with similar symptoms.
https://devtalk.blender.org/t/crash-after-reload-script-f8/15284

**Comment by Durman** [comment]
Also I have found that importing json after F8 can lead to Blender crash.

**Comment by satabol** [comment]
Hi @Durman. I try now some combinations with reload script several times and now crash blender.

![image](https://github.com/nortikin/sverchok/assets/14288520/bc1c46aa-4736-4007-baed-0636f5d74693)

Can you reproduce this now?

**Comment by Durman** [comment]
Yes, I can't reproduce in 3.6. Probably the bag was on Blender side.
