### ISSUE TITLE
new FileHandler nodes

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3232]
a few straight forward utility nodes, standalone easy to debug.

| node name | description |
|------------|-------------|  
| FilePath Selector | spawn a FileSelector dialog
|                            | can 
|                            | - output the `filename` into the tree, or 
|                            | - `[fullpath, dirname, filename, extension]` (user can unpack later).
|                            | - the file as a `[string]`

or all separate nodes.
- ` FilePath Selector`
- `FilePath Decompose`
- `StringIO From FullFilepath`
- `Pickle State`
- `Unpickle State`
- `pydata picker`

i'm starting to need these things.

pydata picker would be something like a really simple switch specifically far simple mesh
```
| pydata picker |
-----------------
|         verts -
|         edges -
|         faces -
- verts         |
- edges         | 
- faces         |
- index         |
.................
```

**Comment by vicdoval** [comment]
this two i would like to have 
FilePath Selector
FilePath Decompose
Or maybe just the first one

The others i don't get clearly their use
