### ISSUE TITLE
Origins Node Flip Bug or limitation?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3236]
I am using Origins Node Matris recently to replace Top and Bottom face of Cylinder node for my "Gear".

I am noticing weird flipping happening as soon as I mingle with parameter of Cylinder. You can watch my video on Revisiting Gear or here is a quick look at this:
https://youtu.be/fe_BcY3-6C4

Is this something that cannot be avoided?

**Comment by Durman** [comment]
Have a look at historical context of creating of the node. #2849

The flickering is related with how Blender calculate tangent for a polygon. I was thought about creating an option of how to calculate tangent but come up with keeping the node as simplest as possible. 

Luckily it is easily possible to rebuild matrix according a desirable result. For your purpose looks like this solutions will be appropriate. Here the tangent always will be looking up.

![2020-05-16_11-15-47](https://user-images.githubusercontent.com/28003269/82113376-a17cf200-9766-11ea-9c8d-8e3e4847c4c7.png)

**Comment by enzyme69** [comment]
Super! Thanks Durman, now it's clear~ Will study this!
