### ISSUE TITLE
neuro node

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#324]
Alex made neuro node

neuro simple node, that learning from you how to find one ideal value between several changable values (some objects) and ideal that you propose. i.e. [[ 2.2, 2.5, 3.0 ]] in data, if this several change in time with every update and [[ 2.4 ]] as ideal solution from you can give something after time, as [[ 2.385432 ]] or something that ideal for node's opinion you, as teacher can change conditions, and than node will consider result by his own. He will understand your logic himselve

**Comment by enzyme69** [comment]
Just wondering... if Sverchok Neuro node can lead to plugin like for OpenToonz that can transfer Style into Original Image?

Even to create Google Deepdream would be nice.


And just now I found this.
http://playground.tensorflow.org/

Is it something like when I have 100 points and I provide an image like alphabet and that 100 points can started to jumbled around that image?

**Comment by nortikin** [comment]
@enzyme69 It is not AI at the moment. It was experiment with neuron unit, but not system. you can teach this neuron to find series. It is not enough to make AI.

**Comment by enzyme69** [comment]
How about this scenario:
- Supposed I have bunch of clipping from newspaper or jigsaw puzzle
- And I like to unscramble and rearrange the puzzle to match the edge

What kind of algorithm is this? Can SvNeuro do this?



On Thursday, 14 April 2016, nikitron <notifications@github.com> wrote:

> @enzyme69 <https://github.com/enzyme69> It is not AI at the moment. It
> was experiment with neuron unit, but not system. you can teach this neuron
> to find series. It is not enough to make AI.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nortikin/sverchok/issues/324#issuecomment-209812052>
>


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
it would be nice to have genetic algorythm to find such things in sverchok. This is good question and concern many cases here. It is dream for now. When we talked with Alex Nedovizin we talked of genetic algorythm, but he made neuron, maybe it cooler, but not solving some issues. If only i could learn of AI and neurons.
