### ISSUE TITLE
Using TuriCreate Machine Learning to read node tree image and rebuild as node tree

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3242]
## Problem statement
Old node tree broken depreciated node but creator supplied image / blend

## Proposed Method

Create ML (Machine Learning) that spotted and recognized nodes from a supplied [image] and rebuild the node tree to use.
https://github.com/apple/turicreate

broken node tree:
<img width="1205" alt="Screen Shot 2020-05-17 at 11 23 42 am" src="https://user-images.githubusercontent.com/3952687/82133564-13217280-9831-11ea-8891-bfa2b6d1fafc.png">

provide the working reference:
[ image ]

machine learning rebuild the node:
<img width="1227" alt="Screen Shot 2020-05-17 at 11 18 42 am" src="https://user-images.githubusercontent.com/3952687/82133566-17e62680-9831-11ea-8712-e1505ac21c31.png">

I don't know if the GIST Sverchok maybe have a way for user to list or supply the **names of the nodes** and then somewhat hook up nodes accordingly...

**Comment by enzyme69** [comment]
So far, I am manually recreating node tree by actually looking at the reference node tree. I think it's a good habit.

I don't know, maybe saving as GIST is the best way...

**Comment by zeffii** [comment]
in the top image, the tree is not broken.  the tree is being loaded into blender with a version of sverchok that has different `bl_idnames` for sockets.

if you get the right version of Blender and Sverchok, you can load that top tree and export as gist, and the gist should load OK in modern sverchok.
