### ISSUE TITLE
Mesh filter node resets submode in a specific case.

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#3247]
## Problem statement

When it in the monad and import and export, Mesh filter node sets filter mode to Interior. 

## Steps to reproduce

1.  put Mesh filter in a monad.
![image](https://user-images.githubusercontent.com/62538469/82157726-35150680-98be-11ea-958c-29a5ccea4b53.png)
2. export to gist.
3. import from gist in another blender file.
![image](https://user-images.githubusercontent.com/62538469/82157792-92a95300-98be-11ea-8252-05d8ffb4fd40.png)

## Expected result

keep the filter mode.

## Sverchok version
Blender version 2.82 (sub 7), Sverchok version 0.6.0.0
75460a7

**Comment by zeffii** [comment]
cool. i suspect this has little to do with monad, but will also happen if you just export a simple tree with that node using gist, and then try to reload it.

**Comment by ken26u** [comment]
really? I tried it in the same node setup without monad, but it didn't happen in my environment. 😳

**Comment by zeffii** [comment]
i'll look tomorrow

**Comment by ken26u** [comment]
thank you : )

**Comment by vicdoval** [comment]
Meanwhile you can use `Component Analyzer` Node . It also offers the same feature

**Comment by ken26u** [comment]
Thank you. I could and replaced it with CA.

**Comment by zeffii** [comment]
@ken26u  you're right, it doesn't appear to be a gist issue.  this loads fine.
https://gist.github.com/c01a691edc4cc1c5ecbbd79073bc721e

Notice also that your monad has no input sockets, i understand why you do this - but - monad "subsystem" is expecting at least one socket there. A `Group Input` node with no "connect me" socket is essentially "malformed", something happened.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/82185917-470c9e80-98ea-11ea-84aa-5c712ef4152e.png)

![image](https://user-images.githubusercontent.com/619340/82185977-5ee42280-98ea-11ea-85e4-8905c75f3c3d.png)

but unfortunately these also some code missing there..

```python
Error: Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_operators.py", line 223, in execute
    layout_dict = create_dict_of_tree(ng, skip_set={}, selected=self.selected_only)
  File "\sverchok\utils\sv_IO_panel_tools.py", line 320, in create_dict_of_tree
    pack_monad(node, node_items, groups_dict, create_dict_of_tree)
  File "\sverchok\utils\sv_IO_monad_helpers.py", line 53, in pack_monad
    v = getattr(node, prop_name)
AttributeError: 'SvGroupNodeMonad_2031566205090' object has no attribute 'numy'
```
[only_outer_plane_verts_2020_05_18_07_33.zip](https://github.com/nortikin/sverchok/files/4642680/only_outer_plane_verts_2020_05_18_07_33.zip)

**Comment by zeffii** [comment]
untill you manually create those sockets, using the N panel.. and rename the existing socket..
https://gist.github.com/d394722a1efd47b7eccc84953ff892a3

**Comment by zeffii** [comment]
interestingly now I also can debug that the boundary-vs-interior switch..

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3251
something is resetting the `self.submode`
```
before: Interior
after: Interior
before: Boundary
after: Boundary
before: Interior
after: Interior
```

**Comment by ken26u** [comment]
@zeffii 
> Notice also that your monad has no input sockets, i understand why you do this - but - monad "subsystem" is expecting at least one socket there. A Group Input node with no "connect me" socket is essentially "malformed", something happened.

I didn't know that. sometime I create a no socket monad. I will not create it from now on.

**Comment by zeffii** [comment]
i should be more exact in my language @ken26u .

what i mean to say is. the monad code was written with the assumption that there is a socket in / out, so if you use monad without input sockets and it works, then that's OK. do as you did before.

**Comment by zeffii** [comment]
but i do think that exposes a bug as shown by the Group Input node displaying no sockets at all, after I/O.

**Comment by zeffii** [comment]
itemized, when the meshfilter is stored inside a monad, the dict of the tree is unpacked from json in this order..
```
2020-05-18 15:02:28,250 [INFO] sverchok.utils.sv_IO_panel_tools: ############ 0.079
node name: Delete Loose
node name: Group Inputs Exp
param node_kind
sockets wiped, skipped update
node name: Group Outputs Exp
param node_kind
sockets wiped, skipped update
from sv_init
state submode: Interior
ending sv_init
node name: Mesh filter
param submode
state submode: Boundary
param mode
state submode: Interior
node name: Plane
param numx
param numy
[]
['ints_1_numy']
['floats_1_sizex', 'ints_1_numy']
['floats_1_sizex', 'floats_2_sizey', 'ints_1_numy']
node name: Viewer Draw Mk3
param vert_color
there was no links memory, creating it
from process

```

**Comment by zeffii** [comment]
so.. what i'm tempted to do is add a parameter to the node that specifies the order in which to apply the node configuration @portnov - is that agreeable?

**Comment by zeffii** [comment]
```
    param_force_order = ["mode", "submode"]
```
it could be made so that all the other params not listed are set in arbitrary order, and only those two are set last.

**Comment by zeffii** [comment]
but maybe to keep the IO code simpler, if you specify `param_force_order` that you must list them all.

**Comment by zeffii** [comment]
we must not have many nodes where the order of the parameters being set - matters.

**Comment by zeffii** [comment]
because, this works when we force the order.  https://github.com/nortikin/sverchok/pull/3251
```
2020-05-18 15:39:56,681 [INFO] sverchok.utils.sv_IO_panel_tools: ############ 0.079
  node name: Delete Loose
  node name: Group Inputs Exp
    param node_kind
sockets wiped, skipped update
  node name: Group Outputs Exp
    param node_kind
sockets wiped, skipped update
from sv_init
      state submode: Interior
ending sv_init
  node name: Mesh filter
    param mode
      state submode: Interior
    param submode
      state submode: Boundary
  node name: Plane
    param numx
    param numy
[]
['ints_1_numy']
['floats_1_sizex', 'ints_1_numy']
['floats_1_sizex', 'floats_2_sizey', 'ints_1_numy']
  node name: Viewer Draw Mk3
    param vert_color
there was no links memory, creating it
from process
```

**Comment by zeffii** [comment]
i'm suggesting we do a "force_param_order" , rather than relying on how the keys of dicts/json are sorted - invariably this stuff will happen.

**Comment by portnov** [comment]
okay. Just the name of the property should say that it has to do with "iojson". `iojson_import_order` ?

**Comment by zeffii** [comment]
yeah, i'm going with `force_param_order_iojson` for consistency with  `properties_to_skip_iojson`.

**Comment by zeffii** [comment]
and maybe this... 
```
    param_names = params.keys()
    if hasattr(node, "force_param_order_iojson"):
        param_ordered = node.force_param_order_iojson
        param_names = list(set(param_names) - set(param_ordered)) + param_ordered
```
to apply all props (except the explicitly listed parameters), then the explicitly listed at the end.

**Comment by zeffii** [comment]
fixed by https://github.com/nortikin/sverchok/pull/3251

have not decided on the set theory stuff.

**Comment by ken26u** [comment]
> i should be more exact in my language @ken26u .
> 
> what i mean to say is. the monad code was written with the assumption that there is a socket in / out, so if you use monad without input sockets and it works, then that's OK. do as you did before. but i do think that exposes a bug as shown by the Group Input node displaying no sockets at all, after I/O.
> 
> itemized, when the meshfilter is stored inside a monad, the dict of the tree is unpacked from json in this order..
> 
> ```
> 2020-05-18 15:09:02,937 [INFO] sverchok.utils.sv_IO_panel_tools: ############ 0.079
>   node name: Delete Loose
>   node name: Group Inputs Exp
>     param node_kind
> sockets wiped, skipped update
>   node name: Group Outputs Exp
>     param node_kind
> sockets wiped, skipped update
> from sv_init
>       state submode: Interior
> ending sv_init
>   node name: Mesh filter
>     param submode
>       state submode: Boundary
>     param mode
>       state submode: Interior
>   node name: Plane
>     param numx
>     param numy
> []
> ['ints_1_numy']
> ['floats_1_sizex', 'ints_1_numy']
> ['floats_1_sizex', 'floats_2_sizey', 'ints_1_numy']
>   node name: Viewer Draw Mk3
>     param vert_color
> there was no links memory, creating it
> from process
> ```

I understood. Thank you for explaining this. 😃
