### ISSUE TITLE
Unable to insert key frame on Vector Lerp

### ISSUE THREAD

**Issue by davmedei** [nortikin/sverchok#3248]
## Problem statement

Unable to insert key frame on Vector Lerp.

## Steps to reproduce

1. Two objects with same number of vertices.
2. Object In > Vector Lerp > Viewer BMesh
3. Insert Keyframe on Vector Lerp factor.

![blender_MWJceAf6OK](https://user-images.githubusercontent.com/17586937/82165233-f7799480-984f-11ea-8f82-e8f45a91b1f6.png)

## Expected result

Be able to insert key frame on Vector Lerp factor value.

## Sverchok version

Blender: 2.82a
Sverchok: 0.6.0.0

**Comment by zeffii** [comment]
Blender's PyNode API for "CustomNodeTree" types, which Sverchok is built on-top of, does not at this point permit keyframes for any slider. You'll find the same thing happens for all nodes.

there's nothing to fix here. sorry.

**Comment by Durman** [comment]
@davmedei Use `Frame info` node instead.

![2020-05-18_11-43-57](https://user-images.githubusercontent.com/28003269/82187060-e5096480-98fc-11ea-976f-911d1b9401db.png)

**Comment by zeffii** [comment]
Another way you can keyframe sverchok is by keyframing something like an Empty, and reading the Z location into Sverchok with a `F-Curve input` node. It's not the most intuitive route, but it's better than nothing.

![image](https://user-images.githubusercontent.com/619340/82189241-5a6e3880-98ef-11ea-9356-22ecec58cb4e.png)

[fcurve_show_2020_05_18_08_07.zip](https://github.com/nortikin/sverchok/files/4642853/fcurve_show_2020_05_18_08_07.zip)

the Fcurve node has a button to the right of the selector field, which will automatically generate an Empty for you to keyframe.

**Comment by zeffii** [comment]
i think technically we could even add a property to the Scene, and display this property in a Node, and let it be keyframed that way.
