### ISSUE TITLE
Scripting SVerchok Nodes using Python

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3249]
When using bpy.ops.node.sv_ops()

I keep getting context incorrect... :/

Can somebody help me how to use Python to create nodes and connect and link them?

Thanks!

```python
import bpy

ng = bpy.data.node_groups['SV']
ng.nodes.new(bpy.ops.node.sv_add_svlinenodemk4())

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
NameError: name 'sv_add_svlinenodemk4' is not defined
```

**Comment by Durman** [comment]
You have to know name of a node class. You can look class names in console when you create new nodes. For this you should enable next options:
![2020-05-18_08-06-00](https://user-images.githubusercontent.com/28003269/82173486-7b7a5d80-98de-11ea-8a43-4e869ab3a6d8.png)
```Text
EVENT: add_node                      IN: SvLineNodeMK4             INSTANCE: Line
EVENT: tree_update                   IN: SverchCustomTreeType      INSTANCE: NodeTree
SVERCHOK EVENT: add_node             NODE: Line
```
So:
```Python
ng.nodes.new('SvLineNodeMK4')
```
https://docs.blender.org/api/current/bpy.types.Nodes.html#bpy.types.Nodes.new
https://docs.blender.org/api/current/bpy.types.NodeLinks.html#bpy.types.NodeLinks.new

**Comment by zeffii** [comment]
```
ng.nodes.new()
```
expects a `bl_idname`, Explore the API from python console..

![image](https://user-images.githubusercontent.com/619340/82184642-43781800-98e8-11ea-8e82-e3076f65992e.png)

We've for several years had a button in the N panel Item tab to copy the `bl_idname` of an active node to the clipboard.

![image](https://user-images.githubusercontent.com/619340/82184355-ce0c4780-98e7-11ea-8271-2c6134758ef9.png)

**Comment by enzyme69** [comment]
Looking at this thread in 2023, I enabled the Logging but not seeing anything on the Terminal (macOS). I did manage to create the node by looking at the class name.

**Comment by enzyme69** [comment]
I am trying to use ChatGPT and AI to properly trained to make node tree and all the nodes for simple things.

Anyhow, I'll start with the basic one, if myself or someone else from the future saw this:

```python
import bpy

ng = bpy.data.node_groups['Sverchok Nodes']

blahnode = ng.nodes.new('SvTorusNodeMK2')
viewernode = ng.nodes.new('SvMeshViewer')

#connect link the nodes

ng.links.new(blahnode.outputs["Vertices"],viewernode.inputs["vertices"])
ng.links.new(blahnode.outputs["Polygons"],viewernode.inputs["faces"])
```

**Comment by enzyme69** [comment]
The issue still persist: I cannot get any detailed developer logs out of Blender into the Terminal :(

**Comment by Durman** [comment]
Which logs would you expect to see?

Can you see this on Sverchok start up?
![image](https://user-images.githubusercontent.com/28003269/229023361-20751814-bf2d-49cc-8efc-71fa7a99ad09.png)

**Comment by enzyme69** [comment]
Yes, I can see that text when I started Blender. 

I am hoping to see developer log that mention the node when I created it on screen so I could get a quick look of the node and write python script to regenerate the node.

<img width="822" alt="Screenshot 2023-04-01 at 11 25 47 am" src="https://user-images.githubusercontent.com/3952687/229256351-c98a28ea-e0c4-4561-9be4-f3fc7084cf0d.png">

**Comment by Durman** [comment]
To see such logs it requires changes in the source code. You can add `self.debug(f"{self.bl_idname} was created")` string in the beginning of the next method.

https://github.com/nortikin/sverchok/blob/bb262d45b0d75a5aa396678775c2ac9c7330bc9a/node_tree.py#L369-L378

The method is called each time new Sverchok node is created and the string will record the log message.
Such logging can be added to master but I guess it requires implementation of logging sections otherwise it will be a mess of logging records.

**Comment by enzyme69** [comment]
Thanks Durman, I will give this a try cheers~
