### ISSUE TITLE
Apply vector field node vectorization

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3250]
## Problem statement

I have put two objects of vector field and two mesh objects:
![2020-05-18_08-36-18](https://user-images.githubusercontent.com/28003269/82174964-618f4980-98e3-11ea-8518-0d57c925e2f8.png)

## Expected result

Two objects from output.

## Actual result

Four objects

**Comment by portnov** [comment]
Well, agreed, more usual behaviour would be to generate 2 objects.
Changed this without adding option, I hope no one depended on previous behaviour.
