### ISSUE TITLE
3D Cursor Location Reloaded

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3252]
Around 3 years ago, @portnov added "a button" into **Vector In** Node that grabs the location of 3D Cursor:
https://github.com/nortikin/sverchok/pull/1454

I am wondering what's going on with that button? Is it still there?

I have a feeling it could be really handy to quickly place SV output geometry. But the implementation / use it with interface that's still questionable. 

Often time user like to place geometry on the floor of 3D view, or simply "stacking" objects.

**Comment by enzyme69** [comment]
In this example, I "snap" 3D cursor into box in the 3D view, and from 3D cursor location and xyz rotation, I can accurately stick this torus into the cube:

<img width="1005" alt="Screen Shot 2020-05-19 at 12 43 04 am" src="https://user-images.githubusercontent.com/3952687/82226318-b5447600-9969-11ea-9383-da35798614ab.png">

**Comment by enzyme69** [comment]
The uber useful CTRL click to create Temporal Viewer node, perhaps we can have CTRL+OPTION or something to create Temporal Viewer, while sticking the Location & Rotation value into Matrix In like above?

By the way CTRL + Click @vicdoval twice will make Temporal Viewer in 3D view disappear.

**Comment by enzyme69** [comment]
@zeffii  https://github.com/nortikin/sverchok/issues/256 no longer working

**Comment by enzyme69** [comment]
One known way to get 3D cursor position using Object ID:

<img width="1153" alt="Screen Shot 2020-05-19 at 12 57 34 am" src="https://user-images.githubusercontent.com/3952687/82227900-bc6c8380-996b-11ea-8898-e604d0895058.png">

**Comment by zeffii** [comment]
yeah, it's variable was renamed, and extend to give rotational info.
```python
context.scene.cursor.location = 0, 0, 0
context.scene.cursor.rotation_euler = 0, 0, 0
```
matrix_in could use both.

**Comment by zeffii** [comment]
but the button must be enabled first, using the rightclick menu when the `Vector In` node is active.

![image](https://user-images.githubusercontent.com/619340/82229074-40058080-992a-11ea-86f3-2f6424785096.png)

**Comment by enzyme69** [comment]
@zeffii wow, I cannot see those awesome "right click menu for sverchok"... when I RMB click, I am getting below menu:

<img width="367" alt="Screen Shot 2020-05-19 at 1 12 58 am" src="https://user-images.githubusercontent.com/3952687/82229507-e1fa8c80-996d-11ea-8a77-a20e15b320e5.png">

**Comment by enzyme69** [comment]
Oh wow, on Mac CMD + RMB click and release CMD button will show that awesome sv menu... :D 

ok now I think 3D cursor is need rotation too.

**Comment by zeffii** [comment]
it's not broken.

**Comment by enzyme69** [comment]
@zeffii Future enhancement wishlist :) 
https://youtu.be/fA7dT54MzKo

**Comment by zeffii** [comment]
thanks, but i don't do wishlists. learn to code man.
