### ISSUE TITLE
Save Presets button is broken for these nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3253]
When I am saving the preset via button, I am getting an error:
<img width="957" alt="Screen Shot 2020-05-19 at 1 01 16 am" src="https://user-images.githubusercontent.com/3952687/82228260-41f03380-996c-11ea-9ed6-9d4d517cceb5.png">

the nodes I wanted to save is the one below (inside frame)

**Comment by enzyme69** [comment]
[py_sv_003.blend.zip](https://github.com/nortikin/sverchok/files/4644879/py_sv_003.blend.zip)
<img width="1288" alt="Screen Shot 2020-05-19 at 1 00 12 am" src="https://user-images.githubusercontent.com/3952687/82228170-21c07480-996c-11ea-834e-1da5fc458f7a.png">

**Comment by zeffii** [comment]
save it without the object ID selector, for now.

**Comment by zeffii** [comment]
looks like i forgot to add "gp_pointer" to the skip list.

**Comment by zeffii** [comment]
should work now. thanks for the bug report.
