### ISSUE TITLE
Viewer 2D

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3254]
![2020-05-18_19-50-09](https://user-images.githubusercontent.com/28003269/82233290-da70be80-9940-11ea-8a61-c7f39b3d932e.png)
```Text
    num_height = h/(max(all_numbers)- min(all_numbers))
ZeroDivisionError: division by zero
```

**Comment by vicdoval** [comment]
There was a bug, thanks for reporting 👍 

But the number mode is a way to graph lists, it won't work with one-number lists. Also wont work in all depth levels, just for the common ones, for numbers   [[n,n,n,..],[n,n,..],..]  (Level 2) and Level 3 for Vectors

**Comment by Durman** [comment]
I forgot to enabled `unwrap` checkbox. Will it work with this checkbox now?

**Comment by Durman** [comment]
By the way `number` appears to me very handy mode. It would be probably cool to have opportunity to have several inputs for numbers.
![2020-05-18_20-56-53](https://user-images.githubusercontent.com/28003269/82239687-368c1080-994a-11ea-87ed-6481f834d714.png)

**Comment by Durman** [comment]
This still does not work.
![2020-05-18_21-10-12](https://user-images.githubusercontent.com/28003269/82240739-fb8adc80-994b-11ea-80f5-133dfc5ea513.png)

**Comment by vicdoval** [comment]
i can fix it what you will see only one dot

**Comment by Durman** [comment]
Why one dote? It should be straight line as I see.

**Comment by vicdoval** [comment]
the node makes a line for every [n,n,n] list. If you input 4 list of [n],[n],[n],[n] (and n is always the same value) the output will be only one dot (the four values overlap)

**Comment by Durman** [comment]
It works as expected now. Thanks.
![2020-05-18_21-37-21](https://user-images.githubusercontent.com/28003269/82242932-c6808900-994f-11ea-95c0-adde26e0e6ae.png)

**Comment by vicdoval** [comment]
I added support for one-number lists in case some needs it
![image](https://user-images.githubusercontent.com/10011941/82244887-3d168a00-9942-11ea-9286-b5b97be129e3.png)

**Comment by Durman** [comment]
It is making the node more robust what is definitely good.
