### ISSUE TITLE
Surface from 4 curves/ cyclic curve

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3259]
![image](https://user-images.githubusercontent.com/10011941/82247049-0b072700-9946-11ea-9bf1-d674fc7a8b45.png)
![image](https://user-images.githubusercontent.com/10011941/82247317-7a7d1680-9946-11ea-91be-d8583d58e29e.png)

I coded this SNL to create a surface from 4 curves (that could be one curve splitted if four pieces).

It could became a feature (or two features, cyclic and 4-curves) of "surface from curves" or a independent node.
It is not perfect and produces some stretching in the boundary polygons, but it works in regular Sverchok.

By the moment it outputs vertices but i guess it could output a surface object....
What do you think @portnov? Are you planning to introduce a better algorithm for this task? You think is better to leave it as a SNL example till someone codes a better solution?

The script:
```
"""
in arc         C  
in U  s  d=0.1 n=1
in V  s  d=0.1 n=1
out verts      v
"""
from sverchok.utils.modules.geom_utils import interp_v3_v3v3 as lerp
from math import sin, pi


t_min0, t_max0 = arc[0].get_u_bounds()
t_min1, t_max1 = arc[1].get_u_bounds()
t_min2, t_max2 = arc[2].get_u_bounds()
t_min3, t_max3 = arc[3].get_u_bounds()

verts =[]
for v in V:
    for u in U:

        t0 = t_min0 + (t_max0 - t_min0) * u
        t2 = t_min2 + (t_max2 - t_min2) * (1-u)
        p0 =arc[0].evaluate(t0).tolist()
        p2 =arc[2].evaluate(t2).tolist()
        t1 = t_min1 + (t_max1 - t_min1) * v
        t3 = t_min3 + (t_max3 - t_min3) * (1-v)
        p1 =arc[1].evaluate(t1).tolist()
        p3 =arc[3].evaluate(t3).tolist()

        if v ==0 or v==1:
            f = 0
        elif u==0 or u==1:
            f = 1
        else:
            f1 = sin(v*pi)/2
            f2 = 1-sin(u*pi)/2
            f = f1+(f2 - f1) * sin(v * pi)
            #other possible interpolation
            # f = f1+(f2 - f1) * 0.5
            
            
        verts.append(lerp( lerp(p0, p2, v), lerp(p1, p3, 1-u), f))
    
verts = [verts]
```

**Comment by portnov** [comment]
Interesting idea...
But why `sin`? I'm afraid it is going to work only in some cases...

**Comment by vicdoval** [comment]
the `sin `is to create a smooth interpolation 0 (on v=0)  1(on v=0.5)  0 (on v=1)    
You can try the commented line to see the difference

**Comment by portnov** [comment]
Well, so basically you're doing the following
1) linear interpolation surface between curves 0 and 2
2) linear interpolation surface between curves 1 and 3
3) some non-linear interpolation between surfaces from 1 and 2

Obviously there are more than one way to do the interpolation for 3). For an snlite example, any one will be fine, because it's just an example, why not. But for core node, I'd prefer some kind of "proven" method - one based on some previous mathematical researches, not just discovered randomly :) And, this "standard" method would probably be polynoimal-based, not sine or something like this - most of mathematical works on these kind of topics (interpolation, minimal surfaces, splines etc) tend to work with polynomials; and polynomials are faster to compute, too. But there are works involving some kinds of splines involving all kinds of sines, exponents and so on, too. It probably worth doing a google-search and some reading :)

**Comment by portnov** [comment]
https://en.wikipedia.org/wiki/Coons_patch this is something like your commented-out method.

**Comment by portnov** [comment]
```
"""
in curve_in_1 C
in curve_in_2 C
in curve_in_3 C
in curve_in_4 C
out surface_out S
"""

import numpy as np

from sverchok.data_structure import zip_long_repeat, ensure_nesting_level
from sverchok.utils.surface import SvSurface, SvCurveLerpSurface
from sverchok.utils.curve import SvCurve, SvFlipCurve

class SvCoonsSurface(SvSurface):
    def __init__(self, curve1, curve2, curve3, curve4):
        self.curve1 = curve1
        self.curve2 = curve2
        self.curve3 = curve3
        self.curve4 = curve4
        self.linear1 = SvCurveLerpSurface(curve1, SvFlipCurve(curve3))
        self.linear2 = SvCurveLerpSurface(curve2, SvFlipCurve(curve4))
        self.c1_t_min, self.c1_t_max = curve1.get_u_bounds()
        self.c3_t_min, self.c3_t_max = curve3.get_u_bounds()
    
    def get_u_min(self):
        return 0
    
    def get_u_max(self):
        return 1
    
    def get_v_min(self):
        return 0
    
    def get_v_max(self):
        return 1
    
    def _calc_b(self, u, v, is_array):
        corner1 = self.curve1.evaluate(self.c1_t_min)
        corner2 = self.curve1.evaluate(self.c1_t_max)
        corner3 = self.curve3.evaluate(self.c3_t_max)
        corner4 = self.curve3.evaluate(self.c3_t_min)
        if is_array:
            corner1 = corner1[np.newaxis]
            corner2 = corner2[np.newaxis]
            corner3 = corner3[np.newaxis]
            corner4 = corner4[np.newaxis]
            u = u[np.newaxis].T
            v = v[np.newaxis].T
        return corner1 * (1 - u) * (1 - v) + corner2 * u * (1 - v) + corner3 * (1 - u) * v + corner4 * u * v
    
    def evaluate(self, u, v):    
        return self.linear1.evaluate(u, v) + self.linear2.evaluate(u, v) - self._calc_b(u, v, False)
    
    def evaluate_array(self, us, vs):
        return self.linear1.evaluate_array(us, vs) + self.linear2.evaluate_array(us, vs) - self._calc_b(us, vs, True)

curve_in_1 = ensure_nesting_level(curve_in_1, 2, data_types=(SvCurve,))
curve_in_2 = ensure_nesting_level(curve_in_2, 2, data_types=(SvCurve,))
curve_in_3 = ensure_nesting_level(curve_in_3, 2, data_types=(SvCurve,))
curve_in_4 = ensure_nesting_level(curve_in_4, 2, data_types=(SvCurve,))

surface_out = []
for curves1, curves2, curves3, curves4 in zip_long_repeat(curve_in_1, curve_in_2, curve_in_3, curve_in_4):
    for curve1, curve2, curve3, curve4 in zip_long_repeat(curves1, curves2, curves3, curves4):
        surface = SvCoonsSurface(curve1, curve2, curve3, curve4)
        surface_out.append(surface)
```

**Comment by portnov** [comment]
Hmm. These Coons patches are not so bad :)
https://gist.github.com/23bdba294c994f37017e7e1729b4a7ee
![Screenshot_20200519_230739](https://user-images.githubusercontent.com/284644/82362329-9efbf000-9a25-11ea-9bfa-17038b0d1721.png)

**Comment by vicdoval** [comment]
I did some basic search (searching surface from four curves :)) but couldnt find anything that could be applied and for sure didnt find this super cool Coons Patches.
That why i was asking :) i was sure you could bring some light to the topic. Thanks!
Are you planing to turn it into a core node? I think it could be a really nice feature for the surface family

**Comment by portnov** [comment]
Yes, I think I'll make a core node for this.

**Comment by Durman** [comment]
Does not this do the same?
https://docs.blender.org/manual/en/2.81/modeling/meshes/editing/faces.html#grid-fill
https://docs.blender.org/api/current/bmesh.ops.html#bmesh.ops.grid_fill

**Comment by portnov** [comment]
Probably the same. The thing is, even it does - it generates just a series of points, while here we have a Surface object which can be used in other ways. To bend something along it, for example.

**Comment by portnov** [comment]
This may be closed as done, I think.

**Comment by vktcl** [comment]
Can developers consider adding grid fill nodes？
The curve is generated by using contour points and lines, and the curve generates the surface in such a way that the contour of the generated surface seems to change
The contour of the face I need to generate is the same as the original
How can I do that

**Comment by Durman** [comment]
It would be better if you could visualize your input data and desirable result for more understanding. Probably `surface from four curves` node could help in your task.

**Comment by vktcl** [comment]
![image](https://user-images.githubusercontent.com/74725748/108199630-48f4de00-7158-11eb-8e25-4c630ba7dff5.png)
The white dot is the original contour, and the red dot is generated by surface from four curves. You can see that the contour is different

I need to generate a face with a white dot contour, which seems to need grid fill implementation.

**Comment by vktcl** [comment]
Or, how do I keep the original points when evaluating surfaces

**Comment by vicdoval** [comment]
The white dots in opposite curves does not seem to match.  Do they have the same number of vertices?

**Comment by vktcl** [comment]
I connect the white point to the broken line node to generate a curve, divide the curve into four curves by using the split curve node, and then use the four curves to generate a surface.
The red dot is generated by the surface using the evaluation surface node, so it doesn't match, I don't know how to match it

**Comment by Durman** [comment]
I'm not sure that it's possible to make red points match with input ones using the node. I remember there was implementation in Blender of greed fill operation. It is even exposed in bmes module API. If you know Python you could do something with this.
