### ISSUE TITLE
Add-on install problem

### ISSUE THREAD

**Issue by LuZa1976** [nortikin/sverchok#3261]
Hi guys, trying to add Sverchok I have this problem. How can I fix ? 
Thanks

Downloaded the last release of Sverchok for Blender 2.8 and using Blender 2.9 got the same problem on 2.83.

Thanks

<img width="641" alt="Screenshot 2020-05-19 at 11 03 29" src="https://user-images.githubusercontent.com/65595190/82307264-6675fb00-99c0-11ea-8432-c35121d50cd8.png">

**Comment by zeffii** [comment]
i think you want to install straight from master, not from a release :)
https://github.com/nortikin/sverchok/archive/master.zip

**Comment by zeffii** [comment]
the explanation: releases are tagged with a number so the zip and subfolders also get that number.
`sverchok-0.6.0` is not a valid python module name, in particular the `period` in the postfix (number of the name) is what's confusing the Blender add-on installer.

- either install the master zip (which is fine, at all times)
- or rename the zip to just 'sverchok` and the folder inside the zip to just `sverchok` also, 

then install again.

sorry for the inconvenience.

**Comment by zeffii** [comment]
if this doesn't resolve,, come back :)

**Comment by zeffii** [comment]
you can still type in here

**Comment by LuZa1976** [comment]
Hi Dealga,

Problem solved, works with master.
I'm new with blender sorry...
I guess u know anyone with skill in blend & python, i cannot use pyaudio in
blender 2.9

Thank u so much



Il giorno mar 19 mag 2020 alle ore 18:58 Dealga McArdle <
notifications@github.com> ha scritto:

**Comment by zeffii** [comment]
i experimented with pyaudio a few years ago, but never added a pyaudio node to Sverchok "permanently"

https://cloud.githubusercontent.com/assets/619340/17786825/e52d882c-6586-11e6-9c8a-49d4661a47c4.gif

https://github.com/nortikin/sverchok/search?q=pyaudio&type=Issues
