### ISSUE TITLE
Out of the Blue: "Brickify" or Gridify node?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3265]
I wonder if SVerchok has already a way to enclosed 2D shape (flat) with grid?

One work around I could think of is by using "intersection" of Grid and 3D shapes Boolean which result in a potential face with grid.

[brickify_002.blend.zip](https://github.com/nortikin/sverchok/files/4661219/brickify_002.blend.zip)
<img width="1157" alt="Screen Shot 2020-05-21 at 5 53 41 pm" src="https://user-images.githubusercontent.com/3952687/82536679-2bc0be00-9b8c-11ea-8985-f32aba941058.png">

Is there a better and faster method?

**Comment by Durman** [comment]
Blender mode of the node can lead to crash.
![2020-05-21_12-38-52](https://user-images.githubusercontent.com/28003269/82540432-1cc41680-9b60-11ea-8d5e-f5311b9687e7.png)

**Comment by zeffii** [comment]
also..
![image](https://user-images.githubusercontent.com/619340/82541182-555bf400-9b50-11ea-876e-38a9b71223b9.png)

**Comment by enzyme69** [comment]
Thank you I think this should be ok for now, I will try thanks!
