### ISSUE TITLE
auto opening file browser on osx , linux

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3266]
i want to add this feature for osx users, maybe 'nix users too.

for exporting the current blend to a `zip`/`gz`, on windows the code will open an Explorer window and highlight the newly added file so i can drag to the issue with easy.
```
def show_selected_in_OSfilebrowsesr(file_path):
    if os.name == 'nt':
        import subprocess
        subprocess.Popen(r'explorer /select,"{}"'.format(file_path))

```
any `os-x` / `linux` users who want their Finder /  or linux equivalent ?

**Comment by zeffii** [comment]
it's something like this for mac
```
def show_selected_in_OSfilebrowsesr(file_path):
    import subprocess
    if os.name == 'nt':
        subprocess.Popen(r'explorer /select,"{}"'.format(file_path))
    if os.name == 'unix':
        # open -a Finder myTextFile.txt
        subprocess.Popen(f"open -a Finder {file_path}")

```

**Comment by nortikin** [comment]
```python 
    if os_kind == "Linux":
        try:
            subprocess.Popen(f"nautilus -s {file_path!r}")
        try:
            subprocess.Popen(f"dolphin --select {file_path!r}")
```
sadly, not all of file managers use search of find option from terminal

**Comment by zeffii** [comment]
a preference of linux users then..
```python
def show_selected_in_OSfilebrowsesr(file_path):
    import subprocess
    import platform
    os_kind = platform.system() # 'Linux', 'Darwin', 'Java', 'Windows'

    if os_kind == "Windows":
        subprocess.Popen(f"explorer /select {file_path!r}")

    elif os_kind == "Darwin":
        subprocess.Popen(f"open -a Finder {file_path!r}")

    elif os_kind == "Linux":

        import sverchok
        viewer = sverchok.preferences.default_system_gui_filebrowsersomethingsomethingsomething
        linux_cmd = {
            "nautilus": ["nautilus", "-s", file_path],
            "dolphin": ["dolphin", "--search", file_path]
        }

        linux_command_found = linux_cmd.get(viewer)

        if not linux_command_found:
            print('nope')
            return

        try:
            subprocess.Popen(linux_command_found, stdout=subprocess.PIPE)
        except Exception as err:
            print(err)
```

**Comment by portnov** [comment]
Some windows users prefer total commander or far :)
If you think this feature is essential, i'd suggest add an option to preferences, for user to provide formatting string like `nautilus -s {0}`. And provide examples in tooltip or in a label below the option.

**Comment by zeffii** [comment]
agreed. @portnov  . i use it all the time,  is it essential ? no, but there are periods where this operator is used maybe 20 times a day.

**Comment by zeffii** [comment]
maybe the docs would look like this

------------------------
This configuration panel is for the "Archive current .blend" feature, which packs the .blend into a `.zip` or `.gz`.  The user (you) will often want to drag that newly generated archive into a Github issue or some other cloud storage device. We offer a convenience post-archiving step to automatically open your favourite file browser in the folder of your new file, and with the file selected.

What you need to provide is the name of the browser that you would like sverchok to use, below you'll see a list of suggestions for your operating system. Once you save the preferences, the next time you archive a .blend from Sverchok you should see the File Browser of your choice open and pointing at your new archive.

| Operating System | common programs | common system calls to this program |
|---------------------|----------------------|-------------------------------------|
| Windows               | Explorer         |    explorer /select file_path  |
|                               | commander   |  i dont know    |
| Mac                       | Finder                     |    open -a Finder file_path  |
| Linux                     | Nautilus                  |  nautilus -s file_path  |
|                              |  Dolpin                   |   dolphin --search file_path |

**Comment by zeffii** [comment]
no ETA.

**Comment by nortikin** [comment]
for example, my default filebrowser is nemo, but nautilus installed and callable from cinnamon DE. So, default will not work, and nautilus will.
