### ISSUE TITLE
Split edges node is not vectorized.

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3267]
Split edges node is not vectorized.
https://github.com/nortikin/sverchok/blob/09e9788c53c7c92b447c02f60e1851a4aecfedc2/nodes/generators_extended/edge_split.py#L63-L65

**Comment by nortikin** [comment]
maybe we can make universal definition to automatically vectorise?

**Comment by Durman** [comment]
I'm thinking about automatization work with sockets. Probably vectorization problem can be handled more delicate within that task. But this won't be soon.

**Comment by zeffii** [comment]
> maybe we can make universal definition to automatically vectorise?

a "vectorization_descriptor",  i think we have so many different implementations of the vectorization now (maybe 40 different , some subtle..some mental-insane ).
