### ISSUE TITLE
Preset node is always placed beginning position

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#3272]
I recently started to use preset. 
it is very useful. 
but when I place it always position is beginning position.

## Steps to reproduce

![anim5](https://user-images.githubusercontent.com/62538469/82741777-95111e80-9d90-11ea-9464-02101d6e766e.gif)

## Expected result
could you place it where the window is showing like other nodes?

## Sverchok version
Blender version 2.82 (sub 7), Sverchok version 0.6.0.0
09e9788

**Comment by enzyme69** [comment]
I thought that the preset will re-generate node tree --- drag around --- until you click, then you actually place the node tree?

**Comment by ken26u** [comment]
Yes. the preset re-generate the node tree which I saved before. 
when I click to release drag, the place is determined.

The node setup is imported to the beginning position just like other json files.

it would be nice if it was in the area we are showing like other single nodes, if possible.

**Comment by zeffii** [comment]
the boogy man lives here:

https://github.com/nortikin/sverchok/blob/fac33b1c1bb2fc2ab19f02c1b516e5384d2813f5/ui/presets.py#L275-L294

and `get_target_location` is not aware of the the visible bounds of the currently active nodeview, i think this would need to be passed during `invoke`.

**Comment by zeffii** [comment]
we can use 
```python
center  = context.space_data.edit_tree.view_center
```
@portnov  - i don't use presets much so have no strong opinion.

**Comment by Durman** [comment]
I believe it was fixed
