### ISSUE TITLE
Rewire and flipped normal

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3278]
Not so much an issue, just a slight little "aha" when using Rewire on Cylinder, it flips the normals... I am sure it was not like this in the past.

<img width="598" alt="Screen Shot 2020-05-25 at 2 26 23 pm" src="https://user-images.githubusercontent.com/3952687/82778135-cd4d5580-9e93-11ea-9a07-a93710335680.png">
[rewire_001.blend.zip](https://github.com/nortikin/sverchok/files/4675185/rewire_001.blend.zip)

**Comment by Durman** [comment]
Probably the node could have -x, -y and -z modes as well.

![2020-05-25_08-31-41](https://user-images.githubusercontent.com/28003269/82778338-30be8f80-9e62-11ea-88a5-0ba26552b8f9.png)

**Comment by zeffii** [comment]
by virtue of the fact that the node changes the coordinates, it will have a similar effect on the vertices of any Mesh - and you would change the polygons by flipping them, rather than offering a 'negate' mode in the rewire.

**Comment by zeffii** [comment]
but maybe offering a 'negate' mode in the rewire. is a good idea.

**Comment by vicdoval** [comment]
Rewire is a "quick trick' to rotate. If you want to ensure the normals it would be safer to use a Rotate node

**Comment by zeffii** [comment]
i don't want to add "negate" to rewire. the code is nice and clean right now :)

**Comment by zeffii** [comment]
i now think making changes to the node to mitigate polygon flipping is a bit of a waste of energy where the are already other options
- Flip Normals node
- Rotate / Matrix Apply node if the goal was rotation

**Comment by enzyme69** [comment]
Roger that
