### ISSUE TITLE
Creating proper UV maps with BMesh node

### ISSUE THREAD

**Issue by DaveSledz** [nortikin/sverchok#3285]
Hi guys,

I have created few instances of simple object and now I want to animate them and set UV maps for texturing. So far I was using Set custom UV map node but the UV map is not set correctly (out of map scale). I tried setting manually uv map but after changing values in nodetree the uvmap disappears. 

So how can I set proper UV maps for BMesh object?

![Zrzut ekranu 2020-05-27 o 14 12 25](https://user-images.githubusercontent.com/45789626/83017534-21873f80-a024-11ea-9283-eeab4a2987f5.jpg)
 
![Zrzut ekranu 2020-05-27 o 14 15 32](https://user-images.githubusercontent.com/45789626/83017786-8e9ad500-a024-11ea-8caa-d743aa85318d.jpg)

**Comment by Durman** [comment]
Can you explain more clear what `set uv map` node do incorrect? You can plug matrix node to the node and scale uv map how do you want.

**Comment by zeffii** [comment]
@DaveSledz 

As long as the "Live" button is toggled to _on_ a lot of data is `wiped+recreated` whenever you update the nodetree upstream from the BMeshViewer node.  

In that sense it's different to manually created Blender objects, where the UV map kind of grows as you add geometry to the object. I do not guarantee this behaviour in BMeshViewer.

**Comment by zeffii** [comment]
@DaveSledz 

there is a mode which only updates the vertex locations (in the N Panel, it;s called "fixed vertex count"), this will not drop the uv map.

- downside:  it really does only work if you are only updating vertex locations.  
    - adding vertices, will bypass this feature entirely.
    - changing edges / faces will produce undefined results.
- upside, if you can live with the constraints of the above points, then the uvmap is unchanged and you can do motion graphics with it .

**Comment by DaveSledz** [comment]
Thank you @zeffii and @Durman, that's exactly what I wanted to achieve. Unfortuantely I had to abandon the idea to animate in Sverchok and do the animation in AN. I really like SV and I find it more intuitive to play with the parameters here than in AN. Looks like SV is made mainly for design purpose but I think it can handle animations as well. 

I would also ask about workflow for SV and animations: How do you play with animations in Sverchok? From what I found there is a node Timer which acts exactly as AN Frame, but is there any way to bake SV animations to keyframes?

**Comment by zeffii** [comment]
animation is still totally possible in SV, if you can live within the current constraints. 
  - static vertex count is easy
  - you can use Object ID nodes to modify the matrices of an object
  - we have an FCurve In  node which can be used to read the curve data at any given frame.
  - the `easing` node offers smooth transitions
  - The Frame Info node offers the current frame etc..

I think it's time to write a short bit of documention specifically to describe the ways the Sverchok can be animated.

**Comment by DaveSledz** [comment]
Yup, just found Jimmy's video about animating in SV: https://www.youtube.com/watch?v=yBVYO9L4J2g It's great and it's more intuitive that AN really. Thanks again!

**Comment by vicdoval** [comment]
@DaveSledz  check also the `Vertex Color` node, it can replace sometimes to the UV coordinates and can be used to animate materials from Sverchok
