### ISSUE TITLE
Extrude region node - keep original

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3288]
Keep original property does not have effect if all faces of given mesh are extruded by the node.

![extrude bug](https://user-images.githubusercontent.com/28003269/83321705-77e1c180-a262-11ea-8195-729c27fa4e45.gif)

**Comment by satabol** [comment]
This is very interesting problem. I found some cases where is happens:
1. Your case with one face but there is more general case: with all extruded faces in mesh:
2. If all faces are extruded then property "Keep Original" is off has no effect:
![image](https://github.com/nortikin/sverchok/assets/14288520/74ce741c-abf2-4d88-a4b9-6f59fcc48995)
Some results are good. For example ("Keep original" is off), if 4-th face if excluded from extrude then result looks good:
![image](https://github.com/nortikin/sverchok/assets/14288520/3a2ee4be-a778-4240-a498-a4570cd06e91)

but in other cases result is not good ("Keep original" is off), if 0 and 1 faces are excluded from extrude then result is not good:
![image](https://github.com/nortikin/sverchok/assets/14288520/bb2e4aa5-3341-4f6e-9406-44690dfe53c4)

So why this happens?
Lets look at blender source code for function "bmesh.ops.extrude_face_region":

![image](https://github.com/nortikin/sverchok/assets/14288520/ad4d8b17-d3b7-4b89-b183-c23be4e8b60e)

So this is problem of Blender. Shame. What solution can be here? As you can see if exists a face in shape that is not extruded then result is good:

![image](https://github.com/nortikin/sverchok/assets/14288520/36c71474-0c69-4c7a-bcaf-3a4440d17e90)

So... we cannot exclude some faces from extrude... but one can append a face to every shape then exclude it from extrude then remove new faces after extrude!

![image](https://github.com/nortikin/sverchok/assets/14288520/ab9bd922-bc8e-4a4b-a15c-d675527b8fb3)

And result is good:

![image](https://github.com/nortikin/sverchok/assets/14288520/41863886-23d5-49ea-8541-63035cfb71a7)
