### ISSUE TITLE
Profile Parametric MK3

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3294]
```python
M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 1 -0.5,0 z

M -0.5, 0
C -0.09,0   0.03,-0.248   0.434,-0.248 n=20
A 0.5,0.5 0.7 0 0 -0.5,0 z

M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 0 0.434,-0.248 n=10
C 0.03,-0.248 -0.09,0 -0.5,0 n=20 z

```
![image](https://user-images.githubusercontent.com/619340/83347801-cc9b4000-a327-11ea-9654-289787e935c6.png)

@portnov vertex 19 and 20 are overlapping, and with the z command I believe 38 should hook up to 0 again (instead of creating index 39).

i'm not sure how to fix that without spraying graffiti all over your code :)

**Comment by portnov** [comment]
Can this be reproduced on a simpler example?

**Comment by zeffii** [comment]
yeah, use the first 3 commands?

**Comment by portnov** [comment]
ok

**Comment by zeffii** [comment]
profile scripting is super underrated :) 
![image](https://user-images.githubusercontent.com/619340/83348568-4afae080-a32e-11ea-8dab-bb06fdbf9977.png)

**Comment by zeffii** [comment]
yeah, that's doing what i expect.

maybe the z command can get a companion. `Z`, to close the path to the most recent `M/m`, right now `z` will close to current command.

**Comment by zeffii** [comment]
there needs to be a way to split up command-sequences, i may not have implement this correctly myself back in the day..

![image](https://user-images.githubusercontent.com/619340/83349558-08d59d00-a336-11ea-8cc4-1d032ec21b22.png)

notices while within the sequences there are no double verts, but the first and last vertex are not closed, and X doesn't have the effect that i was hoping for?

```python
M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 1 -0.5,0

M -0.5, 0
C -0.09,0   0.03,-0.248   0.434,-0.248 n=20
A 0.5,0.5 0.7 0 0 -0.5,0

M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 0 0.434,-0.248 n=10
C 0.03,-0.248 -0.09,0 -0.5,0 n=20
```
[profile_test_param_5_2020_05_31_10_00.zip](https://github.com/nortikin/sverchok/files/4707471/profile_test_param_5_2020_05_31_10_00.zip)

**Comment by portnov** [comment]
`X` command closes the whole contour, connecting current point to `0` index. There is `x` command, which closes last not-closed sequence. So if you want several separate closed contours, you have to put `x` before each `M`.

`z` is not a separate command at all, it's kind of suffix supported by some commands.

**Comment by zeffii** [comment]
i see. thanks for looking at it. this works nicely now.
```python
M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 1 -0.5,0
x
M -0.5, 0
C -0.09,0   0.03,-0.248   0.434,-0.248 n=20
A 0.5,0.5 0.7 0 0 -0.5,0
x
M -0.5, 0
C -0.09,0   0.03,0.248   0.434,0.248 n=20
A 0.5,0.5 0.7 0 0 0.434,-0.248 n=10
C 0.03,-0.248 -0.09,0 -0.5,0 n=20
x
```
