### ISSUE TITLE
Find Kink and Edgy Corners Algorithm? 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3297]
<img width="849" alt="Screen Shot 2020-06-01 at 11 11 01 am" src="https://user-images.githubusercontent.com/3952687/83367599-b90bda00-a3f8-11ea-95d6-fa603077755c.png">

With all the nodes available in SVerchok, do we have already a way to find "corners" and "kink"?  There must be an analyzer node that can measure angle, at points, but I am not 100% sure. Splitting at Hard Edge? 

This is me trying to make send of "pipe" again. We do have Pipe node, but pipe node is doing a weird thing at the moment.

<img width="977" alt="Screen Shot 2020-06-01 at 11 15 55 am" src="https://user-images.githubusercontent.com/3952687/83367715-45b69800-a3f9-11ea-881a-df257efed8d5.png">

**Comment by Durman** [comment]
![2020-06-01_08-12-32](https://user-images.githubusercontent.com/28003269/83375350-adf88000-a3df-11ea-80d1-0f4dea82d748.png)

**Comment by enzyme69** [comment]
Thanks Durman, testing this setup now so I don't forget in the future.

Pipe node is still broken @nortikin

**Comment by enzyme69** [comment]
Actually maybe it's not broken, it's just I need to Vector Sort... Connection.

<img width="1105" alt="Screen Shot 2020-06-01 at 2 29 08 pm" src="https://user-images.githubusercontent.com/3952687/83376042-4577c600-a414-11ea-9739-5762d3cbfcf4.png">

**Comment by enzyme69** [comment]
Why is it twisting and how is it fixable...?

**Comment by nortikin** [comment]
https://gist.github.com/7939188f5f2061aac28ffc9567157eaa

**Comment by nortikin** [comment]
https://gist.github.com/2c2239b34093ac28edfef33eac03bf39
