### ISSUE TITLE
Curve-Zero twist node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3306]
Strange matrixes

![2020-06-02_14-39-48](https://user-images.githubusercontent.com/28003269/83511004-ffd3ff80-a4de-11ea-8887-17adceaab96c.png)

[test.zip](https://github.com/nortikin/sverchok/files/4716557/test.zip)

**Comment by portnov** [comment]
Mathematical restrictions :/
You can't properly calculate a normal, or a binormal for curve that has zero curvature. Calculation procedures will give division by zero => NaN.
I could try to detect zero curvature and select some arbitrary normal direction... at least, when I know I deal with straight line.

**Comment by Durman** [comment]
Probably parts of curve which have zero curvature can get normals from previous or next parts of the curve (or interpolation between them) which have non zero curvature?

Have a look this post:
https://github.com/nortikin/sverchok/issues/2242#issuecomment-438271208

**Comment by portnov** [comment]
Yes, probably. The problem is even harder: S-shaped curves often have zero curvature at the point where two arcs meet, and moreover, two parts have *opposite* directions of the normal. So in the middle point, the normal is actually flipped by 180 degree.

**Comment by portnov** [comment]
It is possible to go in different direction.

To "rotate matrix according to curve's tangent", we have the following approaches:

a) historically (in Sverchok) the first: use Householder, Tracking or Rotation Difference algorithm. These algorithms take two vectors: initial tangent direction and tangent direction you want, and return a rotation matrix that converts the source tangent direction to the target. Note: these algorithms do not know at all what the "curve" is. They depend on tangent direction only.

b) Frenet and "zero-twist" algorithms. Frenet algorithm takes Frenet matrix of the curve, made from tangent direction, normal and binormal directions of the curve. "Zero-twist" is similar, it takes Frenet matrices first, and then it "substracts" rotation around the tangent, which is calculated by integrating curve torsion. These algorithms are not "curve-agnostic", they are based on differential geometry, so for "good" curves they give better results. "Good" means curve with non-zero curvature, i.e. curve which has non-zero second derivative in all points. If the curve has points with zero curvature, or, even worse, it has straight segments, then everything is suddenly very bad. 

c) New algorithm. First, let's split curve in N pieces and calculate tangent vectors at these points ("knots"). Then we take curve's normal vector at curve's starting point (let's assume that at least at this point the curve has non-zero curvature). Then we iterate through all knots. At each knot, we build a plane through the knot point, orthogonal to curve's tangent vector at this knot point; and we project normal vector from previous point to this plane. So we have N normal vectors. Then for any value of T in curve's domain, we can calculate normal vector by interpolating normals between knot points somehow. In the following script, quaternions linear interpolation is used.

```python
"""
in curve_in C
in resolution_in s
in ts_in s
out matrix_out m
"""

import numpy as np
from mathutils import Vector, Matrix

from sverchok.data_structure import zip_long_repeat, ensure_nesting_level
from sverchok.utils.curve import SvCurve
from sverchok.utils.geom import PlaneEquation

def make_matrix(point, tangent, normal, binormal):
    matrix = np.stack((normal, binormal, tangent))
    matrix = np.linalg.inv(matrix)
    matrix = Matrix(matrix).to_4x4()
    matrix.translation = Vector(point)
    return matrix

def make_matrices(points, tangents, normals, binormals):
    matrices = np.dstack((normals, binormals, tangents))
    matrices = np.transpose(matrices, axes=(0,2,1))
    matrices = np.linalg.inv(matrices)
    return [Matrix(m).to_quaternion() for m in matrices]

def pre_calc(curve, resolution):
    t_min, t_max = curve.get_u_bounds()
    ts = np.linspace(t_min, t_max, num=resolution)

    points = curve.evaluate_array(ts)
    tangents, normals, binormals = curve.tangent_normal_binormal_array(ts)
    tangents /= np.linalg.norm(tangents, axis=1, keepdims=True)

    normal = normals[0]
    binormal = binormals[0]
    binormal /= np.linalg.norm(binormal)
    out_normals = [normal]
    out_binormals = [binormal]

    for point, tangent in zip(points[1:], tangents[1:]):
        plane = PlaneEquation.from_normal_and_point(Vector(tangent), Vector(point))
        normal = plane.projection_of_vector(Vector(point), Vector(point + normal))
        normal = np.array(normal.normalized())
        binormal = np.cross(tangent, normal)
        binormal /= np.linalg.norm(binormal)
        out_normals.append(normal)
        out_binormals.append(binormal)

    quats = make_matrices(points, tangents, np.array(out_normals), np.array(out_binormals))
    return ts, quats

ts_in = ensure_nesting_level(ts_in, 3)

matrix_out = []
for curves, resolutions, ts_i in zip_long_repeat(curve_in, resolution_in, ts_in):
    for curve, resolution, ts in zip_long_repeat(curves, resolutions, ts_i):
        ts = np.array(ts)
        tknots, quats = pre_calc(curve, resolution)
        base_indexes = tknots.searchsorted(ts, side='left')-1
        t1s, t2s = tknots[base_indexes], tknots[base_indexes+1]
        dts = (ts - t1s) / (t2s - t1s)
        points = curve.evaluate_array(ts)
        for i, (dt, base_index) in enumerate(zip(dts, base_indexes)):
            q1, q2 = quats[base_index], quats[base_index+1]
            q = q1.slerp(q2, dt)
            point = points[i]
            matrix = q.to_matrix().to_4x4()
            matrix.translation = Vector(point)
            matrix_out.append(matrix)
```

![Screenshot_20200608_010829](https://user-images.githubusercontent.com/284644/83979132-92343300-a925-11ea-9e58-35c0f8dc8596.png)

**Comment by portnov** [comment]
Something has to be done in case when the curvature at the starting point is zero. For example, we could start from another point, in hope that there curvature is non-zero. Or we can just select any normal direction (implemented in the script above). Then we can handle straight segments:

![Screenshot_20200608_014236](https://user-images.githubusercontent.com/284644/83979648-57cc9500-a929-11ea-9f5a-caa218e90793.png)

**Comment by portnov** [comment]
I've
* described current behaviour in the documentation. I do not consider the algorithm as "bad" or "invalid", as it is based on mathematical definitions and works exactly when mathematics works. For "good" curves, it works fine.
* added a new algorithm to "extrude curve along curve" and "zero twist" nodes.

For other nodes that have similar problem, this algorithm can be added later if required.
