### ISSUE TITLE
Crash with update button

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3308]
Next steps in the file lead to crash without even error message. Most likely it is related with logic new update button.

![2020-06-02_16-26-42](https://user-images.githubusercontent.com/28003269/83520145-3ebd8180-a4ee-11ea-9e44-e00380acc06b.png)

[untitled4.zip](https://github.com/nortikin/sverchok/files/4717109/untitled4.zip)

**Comment by zeffii** [comment]
hit ctrl+enter after `1`, should update on the fly.

**Comment by Durman** [comment]
Yes I know, but you should not do that if you what to reproduce the crash.

**Comment by zeffii** [comment]
😎

**Comment by Durman** [comment]
It seems the node does not have the button any more. No the button no the problem.)
