### ISSUE TITLE
Edges not being drawn by VDMK3

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3314]
a user (George) ask [this question on blender.stackexchange](https://blender.stackexchange.com/questions/176114/how-to-display-faces-in-sverchok-viewer-draw-mk3-node) . and seen as there are no other options to switch/set for the drawer, it would be nice to determine
1. whats happening
2. why is it happening
3. what can be done / what are the options
4. what is expected outcomes

George's images

![image1](https://i.stack.imgur.com/pThQq.png)
![image2](https://i.stack.imgur.com/Oj2xY.png)

## things we don't know
- is the Blender self compiled / non official?
- what OS
- what graphics card
- what openGL

## we do know
- user has enabled `gl_faces_offset`

it would be simple enough to write a short script that draws uniform color with edges + depth testing, to test . but user must return to question. else it's a dead end.

**Comment by ricardomatias** [comment]
I also have the same issue.

* Blender 2.90 Alpha
* Pop_OS 20.04
* Nvidia GTX 970

**Comment by zeffii** [comment]
does it happen on nightly 2.83 builds?

**Comment by ricardomatias** [comment]
It's indeed working, my bad. I'm new to Sverchok so I'll write what happened in case of other beginner's stumbling on this.

I was following along the introduction [tutorial](https://sverchok.readthedocs.io/en/latest/induction.html#unit-00-introduction-to-nodeview-and-3dview) and couldn't get the edges to be drawn using a Formula node. I'm not sure why that was happening, but further along the tutorial shows how to create a list of indices for the edges and that works.

**Comment by zeffii** [comment]
ok. cool.. that tutorial is outdated.   i have rewritten them for 2.8+

also.. for the other user.. here is a basic-of-the-most-basic-kind test that should display edges
```python
import bpy
import gpu
import bgl
import numpy as np
from random import random
from gpu_extras.batch import batch_for_shader

mesh = bpy.context.active_object.data
mesh.calc_loop_triangles()

vertices = np.empty((len(mesh.vertices), 3), 'f')
poly_indices = np.empty((len(mesh.loop_triangles), 3), 'i')
edge_indices = np.array(mesh.edge_keys)

mesh.vertices.foreach_get("co", np.reshape(vertices, len(mesh.vertices) * 3))
mesh.loop_triangles.foreach_get("vertices", np.reshape(poly_indices, len(mesh.loop_triangles) * 3))


shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'TRIS', {"pos": vertices}, indices=poly_indices)

wire_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
wire_batch = batch_for_shader(shader, 'LINES', {"pos": vertices}, indices=edge_indices)


def draw():
    bgl.glEnable(bgl.GL_DEPTH_TEST)

    batch.draw(shader)

    wire_shader.bind()
    wire_shader.uniform_float("color", (1, 0, 0, 1))
    wire_batch.draw(wire_shader)

    bgl.glDisable(bgl.GL_DEPTH_TEST)


bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```

**Comment by zeffii** [comment]
@ricardomatias  unfortunately i didn't communicate to the rest of the team that those docs should be updated elsewhere too. 

start here
https://github.com/nortikin/sverchok/blob/master/docs/Unit_00/soft_intro_01.rst

**Comment by zeffii** [comment]
those are the right docs but not compiled into html (yet)

**Comment by zeffii** [comment]
and with polygon offset..
```python

import bpy
import gpu
import bgl
import numpy as np
from random import random
from gpu_extras.batch import batch_for_shader

mesh = bpy.context.active_object.data
mesh.calc_loop_triangles()

vertices = np.empty((len(mesh.vertices), 3), 'f')
poly_indices = np.empty((len(mesh.loop_triangles), 3), 'i')
edge_indices = np.array(mesh.edge_keys)

mesh.vertices.foreach_get("co", np.reshape(vertices, len(mesh.vertices) * 3))
mesh.loop_triangles.foreach_get("vertices", np.reshape(poly_indices, len(mesh.loop_triangles) * 3))


shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'TRIS', {"pos": vertices}, indices=poly_indices)

wire_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
wire_batch = batch_for_shader(shader, 'LINES', {"pos": vertices}, indices=edge_indices)


def draw():
    bgl.glEnable(bgl.GL_DEPTH_TEST)

    bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
    bgl.glPolygonOffset(1.0, 1.0)
    batch.draw(shader)
    bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)

    wire_shader.bind()
    wire_shader.uniform_float("color", (1, 0, 0, 1))
    wire_batch.draw(wire_shader)

    bgl.glDisable(bgl.GL_DEPTH_TEST)


bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')

```

**Comment by zeffii** [comment]
coool.   now, you can do a test for me, 

1. start blender fresh
2. add a mesh sphere (just to regular Blender scene.., default cube might be a bit boring)
3. place the sphere away from the world origin, my suggestion
 
![image](https://user-images.githubusercontent.com/619340/84361135-7c479c00-abcb-11ea-8717-50e2b3f5dc60.png)

4. select the sphere
5. `run` (alt+p)   https://github.com/nortikin/sverchok/issues/3314#issuecomment-640783000
from the text editor

6. adjust the 3dview (maybe rotate it a small amount) to trigger the update required for that script to draw to the view.

for me that shows:

![image](https://user-images.githubusercontent.com/619340/84361211-9c775b00-abcb-11ea-8330-4333eb9842e1.png)

**Comment by zeffii** [comment]
i predict yours will display a vague outline of the sphere, and the polygons will be all of uniform color.

**Comment by zeffii** [comment]
or use this script, it is almost the same as above but with modifications that allow you to test small changes on your machine. 

- The script makes a draw handler, which it attaches to 3d view. 
- Each time the 3d view is updated by user interaction, the `def draw` contents is executed and displayed on the view.

you can paste this into the text editor and run it using alt+p aswell. 
```python
import bpy
import gpu
import bgl
import numpy as np
from random import random
from gpu_extras.batch import batch_for_shader

mesh = bpy.context.active_object.data
mesh.calc_loop_triangles()

vertices = np.empty((len(mesh.vertices), 3), 'f')
poly_indices = np.empty((len(mesh.loop_triangles), 3), 'i')
edge_indices = np.array(mesh.edge_keys)

mesh.vertices.foreach_get("co", np.reshape(vertices, len(mesh.vertices) * 3))
mesh.loop_triangles.foreach_get("vertices", np.reshape(poly_indices, len(mesh.loop_triangles) * 3))


shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'TRIS', {"pos": vertices}, indices=poly_indices)

wire_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
wire_batch = batch_for_shader(shader, 'LINES', {"pos": vertices}, indices=edge_indices)


def draw():
    bgl.glEnable(bgl.GL_DEPTH_TEST)

    bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
    bgl.glPolygonOffset(-1.0, 1.0)
    batch.draw(shader)
    bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)

    wire_shader.bind()
    wire_shader.uniform_float("color", (1, 1, 0, 1))
    wire_batch.draw(wire_shader)

    bgl.glDisable(bgl.GL_DEPTH_TEST)


if hasattr(bpy, 'test_handler'):
    bpy.types.SpaceView3D.draw_handler_remove(bpy.test_handler, 'WINDOW')
bpy.test_handler = bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```
the line you can change to see if i've identified the problem is 
```python
    bgl.glPolygonOffset(1.0, 1.0)
```
if you change that to
```python
    bgl.glPolygonOffset(-1.0, 1.0)
```
i think you will see all edges drawn, and occluded correctly.

**Comment by agx9101** [comment]
Hello Zeffi - Thanks for your efforts. Your prediction for vague outline didn't pan out. 

![image](https://user-images.githubusercontent.com/66753092/84426712-a613b980-abf1-11ea-98dc-afcb47fb6a41.png)

**Comment by agx9101** [comment]
Also tried with bgl.glPolygonOffset(-1.0, 1.0). The same result however the black sometimes flickers to white on some rotation around the object. 

![image](https://user-images.githubusercontent.com/66753092/84427106-5e416200-abf2-11ea-9485-2bcbf81628b9.png)

**Comment by agx9101** [comment]
Flickering occurs when moving the sphere when bgl.glPolygonOffset(-1.0, 1.0)

![image](https://user-images.githubusercontent.com/66753092/84427325-bed09f00-abf2-11ea-8641-7addabbd2bc2.png)

**Comment by zeffii** [comment]
please use the second script.

**Comment by zeffii** [comment]
this one
```python
import bpy
import gpu
import bgl
import numpy as np
from random import random
from gpu_extras.batch import batch_for_shader

mesh = bpy.context.active_object.data
mesh.calc_loop_triangles()

vertices = np.empty((len(mesh.vertices), 3), 'f')
poly_indices = np.empty((len(mesh.loop_triangles), 3), 'i')
edge_indices = np.array(mesh.edge_keys)

mesh.vertices.foreach_get("co", np.reshape(vertices, len(mesh.vertices) * 3))
mesh.loop_triangles.foreach_get("vertices", np.reshape(poly_indices, len(mesh.loop_triangles) * 3))


shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'TRIS', {"pos": vertices}, indices=poly_indices)

wire_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
wire_batch = batch_for_shader(shader, 'LINES', {"pos": vertices}, indices=edge_indices)


def draw():
    bgl.glEnable(bgl.GL_DEPTH_TEST)

    bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
    bgl.glPolygonOffset(1.0, 1.0)
    shader.bind()
    shader.uniform_float("color", (0.3, 0.3, 0.3, 1.0))
    batch.draw(shader)
    bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)

    wire_shader.bind()
    wire_shader.uniform_float("color", (1, 1, 0, 1))
    wire_batch.draw(wire_shader)

    bgl.glDisable(bgl.GL_DEPTH_TEST)


if hasattr(bpy, 'test_handler'):
    bpy.types.SpaceView3D.draw_handler_remove(bpy.test_handler, 'WINDOW')
bpy.test_handler = bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```

**Comment by zeffii** [comment]
and blender `2.82a` might have a different openGL profile , i can't remember (will look for exact date ) but Blender devs changed a few things after `2.82a`

please try also a nightly build of blender `2.83` from builds.blender.org

**Comment by agx9101** [comment]
![image](https://user-images.githubusercontent.com/66753092/84430364-98613280-abf7-11ea-9ba9-4fd104d37bb4.png)

**Comment by zeffii** [comment]
frustrating :)

**Comment by agx9101** [comment]
I understand. It's not a problem to simply use another view drawer node. I will download 2.83 this weekend and report back.

**Comment by zeffii** [comment]
also i notice you have Pivot Transform addon enabled.  It shouldn't interfere, but just in case it is the sane thing to do is to disable it , restart blender with it not enabled. then see if vdmk3 can draw.

i say this only because it looks like pivot transform is also doing some openGL drawing whenver used, and it might ( i can't know without looking at the code ) modify the state of the openGL engine that Sverchok uses.

**Comment by zeffii** [comment]
an alternative to the previous script, is a script that does the removal of  the previously handler, before anything else.. so errors in the user's experimental code won't get in the way of removing the previous handler

```python
import bpy
import gpu
import bgl
import numpy as np
from random import random
from gpu_extras.batch import batch_for_shader

# remove previous handler if possible.
if hasattr(bpy, 'test_handler'):
    bpy.types.SpaceView3D.draw_handler_remove(bpy.test_handler, 'WINDOW')

mesh = bpy.context.active_object.data
mesh.calc_loop_triangles()

vertices = np.empty((len(mesh.vertices), 3), 'f')
poly_indices = np.empty((len(mesh.loop_triangles), 3), 'i')
edge_indices = np.array(mesh.edge_keys)

mesh.vertices.foreach_get("co", np.reshape(vertices, len(mesh.vertices) * 3))
mesh.loop_triangles.foreach_get("vertices", np.reshape(poly_indices, len(mesh.loop_triangles) * 3))

shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
batch = batch_for_shader(shader, 'TRIS', {"pos": vertices}, indices=poly_indices)
wire_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
wire_batch = batch_for_shader(shader, 'LINES', {"pos": vertices}, indices=edge_indices)


def draw():
    bgl.glEnable(bgl.GL_DEPTH_TEST)

    bgl.glEnable(bgl.GL_POLYGON_OFFSET_FILL)
    bgl.glPolygonOffset(1.0, 1.0)
    shader.bind()
    shader.uniform_float("color", (0.3, 0.3, 0.3, 1.0))
    batch.draw(shader)
    bgl.glDisable(bgl.GL_POLYGON_OFFSET_FILL)

    wire_shader.bind()
    wire_shader.uniform_float("color", (1, 1, 0, 1))
    wire_batch.draw(wire_shader)

    bgl.glDisable(bgl.GL_DEPTH_TEST)

bpy.test_handler = bpy.types.SpaceView3D.draw_handler_add(draw, (), 'WINDOW', 'POST_VIEW')
```

**Comment by agx9101** [comment]
Same issue with blender 2.83.1 with pivot transform add-on disabled. 
![image](https://user-images.githubusercontent.com/66753092/86203057-f4054880-bb31-11ea-898e-84c907f9359e.png)

**Comment by agx9101** [comment]
ran the latest script you sent
![image](https://user-images.githubusercontent.com/66753092/86203157-49d9f080-bb32-11ea-9c1d-bbeac779884c.png)

**Comment by zeffii** [comment]
cool, i think i'll send a bug report to blender devs, because as you can see; different machines running the same script are getting significantly different output.  

I'm suspecting a driver issue, or some particular workaround.

**Comment by zeffii** [comment]
i don't see this being resolved.. or a widespread problem .
