### ISSUE TITLE
Separating Straight Line and Corner / Intersection (case of Pipe)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3318]
<img width="534" alt="Screen Shot 2020-06-05 at 10 09 09 am" src="https://user-images.githubusercontent.com/3952687/83822515-99d0bd80-a714-11ea-9db9-74ebe04a6140.png">

Do we have node in SV that can separate straight edges and corners / intersecting edges (like pipe)?

**Comment by enzyme69** [comment]
Kind of like:
When there is a corner, make split cut. If not, "straight edge" can stay.

**Comment by enzyme69** [comment]
Target result:
<img width="500" alt="Screen Shot 2020-06-05 at 10 19 45 am" src="https://user-images.githubusercontent.com/3952687/83823016-14e6a380-a716-11ea-86b4-a62c4f934bb9.png">

In here, I am manually use Skin Modifier (I know Skin Modifier handles intersection meshing), and boolean the in between "straight line edge".

**Comment by Durman** [comment]
In your example I think what you actually need is to count how much edges point has. If edges more than two do nothing otherwise round corner. Probably only SNL node can do this.

**Comment by enzyme69** [comment]
Yes, the step I could imagine:
- find connectivity per vertices that intersect and making sharp corner bevel
- make "slice cut" per intersections

**Comment by zeffii** [comment]
there are node scripts on the issue tracker that take care of some of this.  

https://github.com/nortikin/sverchok/issues/2362

I think ultimately you should start thinking about how you can describe what you want as a 'recipe', or as we call them "algorithms". Your first image shows something like this 

![image](https://user-images.githubusercontent.com/619340/83854520-20869a00-a717-11ea-940c-e9c0f26d8693.png)

writing algorithms that traverse a mesh and detect verts that are part of 2, 3, 4..more.. edges is not difficult, or heavy to computate. With procedurality comes responsibility to offload decision making to the algorithm, but it means being able to give parameters with which the algorithm can make decisions. Start with robust (and dumb) algorithms and then insert some probability or spatial awareness.

**Comment by enzyme69** [comment]
@zeffii Thanks Zeff, I'll check that thread. I think my way is often too brute force and non systematic... the result of self taught programming.

**Comment by enzyme69** [comment]
<img width="924" alt="Screen Shot 2020-06-06 at 11 58 17 am" src="https://user-images.githubusercontent.com/3952687/83933603-7af22a00-a7ed-11ea-8515-17436f9e5278.png">

Somewhat myself from the past is trying to tackle the same thing...
