### ISSUE TITLE
Texture viewer

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3322]
Textures become black after scaling node tree:

![bug texture view](https://user-images.githubusercontent.com/28003269/83951332-cf26f980-a841-11ea-8d0a-66ffb0fdd9a0.gif)

**Comment by zeffii** [comment]
i can't reproduce that : /  does it also happen on TextureLite ?

**Comment by zeffii** [comment]
@Durman  mind testing: https://github.com/nortikin/sverchok/pull/3323

**Comment by zeffii** [comment]
@kalwalt  how is that drawing for you? is it drawing upside down or are my eyes deceiving me.

**Comment by zeffii** [comment]
i have noticed some "bleeding" or "leaking" of our opengl/shader stuff into other UI of Blender. This suggests that we aren't return the openGL state correctly at all times.  This stuff is tricky to dig into when there's only a passing interest.

**Comment by Durman** [comment]
> @Durman mind testing: #3323

![bug texture view2](https://user-images.githubusercontent.com/28003269/83960067-826d0e00-a895-11ea-8b69-4b3bdd23d161.gif)

**Comment by zeffii** [comment]
the annoying thing about this is that it is intermittent.  I might revert the changes for that node

**Comment by zeffii** [comment]
- only in the hardcoded viewProjectionMatrix did I manage to reproduce the problem
- doesn't seem to happen to any of the other viewers, suggesting this is down to the texture.

**Comment by enzyme69** [comment]
In the last few updates I noticed sometimes node is not updating unless
Blend reloaded.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by kalwalt** [comment]
@zeffii haven't used sverchok for a while, i have a very limited time now... sorry i can not help for this :cry:

**Comment by zeffii** [comment]
that's OK. whatever is happening here isn't a critical bug. (i'm not convinced it's critical anyway...)  would love for it to _not happen_ but hey.. i also only have so much time to offer.
