### ISSUE TITLE
Full 2d and 3d L-Systems Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#333]
In the past i've implemented this in Javascript in d3.js ([live demo here](http://tributary.io/inlet/4444616/)) but it's only 2d. There are various ways to implement L-systems and i've wanted to do a 3d L-system for some time now.

http://algorithmicbotany.org/papers/abop/abop.pdf  second time reading this now. this time slower :)

**Comment by zeffii** [comment]
https://cis700-procedural-graphics.github.io/files/lsystems_1_31_17.pdf

**Comment by enzyme69** [comment]
@zeffii Animation Nodes is having L-System node, I have not tested your node either. But awesome implementation from artistic and design perspective.

**Comment by nortikin** [comment]
pushing example json to master in shapes.
