### ISSUE TITLE
Vector Drop for "center pivot" is failing on me

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3330]
:orphan:

## Problem statement

Very often, I use "Vector Drop" node to center pivot my procedural creation. This time, vector drop seems to fail on me. I never quite encounter this.

My setup is simple, just 2D cut of plane, what strange is when I cut it not with straight edge, it will start to shift and I cannot "center pivot" this object.

This works:
<img width="834" alt="Screen Shot 2020-06-08 at 12 23 25 pm" src="https://user-images.githubusercontent.com/3952687/83987469-a9a20900-a983-11ea-97ab-8347ae909509.png">

This does not work:
<img width="850" alt="Screen Shot 2020-06-08 at 12 23 30 pm" src="https://user-images.githubusercontent.com/3952687/83987318-2b456700-a983-11ea-9cdc-14f78e357a16.png">

<img width="1405" alt="Screen Shot 2020-06-08 at 12 23 40 pm" src="https://user-images.githubusercontent.com/3952687/83987313-25e81c80-a983-11ea-8e0c-c595669c0562.png">

[vector_drop_failed.blend.zip](https://github.com/nortikin/sverchok/files/4743570/vector_drop_failed.blend.zip)

Perhaps there is a better way to control and make center pivot of object?

**Comment by enzyme69** [comment]
How the shift happens:
[Screen Recording 2020-06-08 at 12.31.13 pm.mov.zip](https://github.com/nortikin/sverchok/files/4743583/Screen.Recording.2020-06-08.at.12.31.13.pm.mov.zip)

**Comment by Durman** [comment]
![2020-06-08_08-16-04](https://user-images.githubusercontent.com/28003269/83992197-75692100-a960-11ea-8a00-5f7d9d0abd5a.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/84010556-1b268b00-a975-11ea-8561-ff55e394e205.png)

You can see why the vector drop node is not doing what you want. The node is repositioning the "basepoint/object origin", based on the average vertex location. If you look at the two shapes, and think about their average vertex location you might appreciate why the origin is in different places for both shapes.

bounding box node would also be appropriate.

**Comment by zeffii** [comment]
I would start with a centered plane, to avoid other spacial transforms.

**Comment by zeffii** [comment]
i think map_range or curve_mapper needs to be able to do a deepcopy,  one of those nodes is poluting the other part of the tree.

[vector_drop_failed_2020_06_08_10_24.zip](https://github.com/nortikin/sverchok/files/4745342/vector_drop_failed_2020_06_08_10_24.zip)

these nodes seem to be interacting.

![image](https://user-images.githubusercontent.com/619340/84020486-2aacd080-a983-11ea-8fa6-332efb96faf3.png)

**Comment by zeffii** [comment]
there's definitely a bug here,, but it's not what vector drop node.

**Comment by zeffii** [comment]
@vicdoval  @portnov   i didn't close this yet, because there does seem to be a bug which i find difficult to explain.  but the steps could be
- load @enzyme69 's original blend
- then make the changes necessary to arrive at my version of the .blend
     - set the plane node to Center
     - add a mul and sub scalar mode to rescale the output of number range
     - remove the vector drop

and I think you'll notice some weird behaviour if you hook up a VDmk3 to the output of the Vector In (just before the UVConnection node).

**Comment by vicdoval** [comment]
I don't see anything weird, what should I see? 😕

**Comment by zeffii** [comment]
it's almost like the output of the scalarmath sub  node was being influenced by the output of the map range node, which it wasn't even connected to.  Which is weird, because none of those nodes are rewritting their input data (where deepcopy=False would be a problem ).
