### ISSUE TITLE
Comfy Cushion Default Cube

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3335]
Referencing Blender Sushi experiment "Jan Van Den Hemel Recipe"
https://github.com/enzyme69/blendersushi/issues/818

Tweet:
https://twitter.com/JanvandenHemel/status/1270100984224722946?s=20

It's a little challenging exercise. I did manage to find vertices with similar condition and mask it for Bevel.

However, I found that it is very difficult to mask out some Polygon Face, extrude them in and out, and to attempt to select more and scale. Is this possible in SVerchok?

I don't know if Sorcar is any easier, or we can really use the "Send to Sorcar" and "Receive from Sverchok" nodes, because I tested and I could not find the node to send to sorcar.

**Comment by enzyme69** [comment]
From Bevel vertices, and to wanting to extrude polygon face, perhaps maybe I should have used Face Mask based on the position of vertices?

<img width="1137" alt="Screen Shot 2020-06-09 at 11 45 37 am" src="https://user-images.githubusercontent.com/3952687/84097033-be93a080-aa46-11ea-8ede-f9185d2867bf.png">

**Comment by enzyme69** [comment]
In comparison with Sorcar...
<img width="1017" alt="Screen Shot 2020-06-09 at 12 34 32 pm" src="https://user-images.githubusercontent.com/3952687/84099806-c3a81e00-aa4d-11ea-994c-f3d3bdfcab1b.png">

Mesh component select and masking in SVerchok can be quite complex.

**Comment by Durman** [comment]
Probably you are looking something like `Select similar` node.
![2020-06-09_08-21-10](https://user-images.githubusercontent.com/28003269/84105717-30a9bc80-aa2a-11ea-9822-767dbc7e98fd.png)

**Comment by enzyme69** [comment]
Thanks Durman, I think that's probably one of it, maybe some of the nodes there I should just make as preset or attempting Macro, it will be 3-4 nodes combo to achieve masking but worth doing, thanks I will try until this comfy default cube solved.

**Comment by enzyme69** [comment]
<img width="983" alt="Screen Shot 2020-06-10 at 12 44 03 pm" src="https://user-images.githubusercontent.com/3952687/84221249-1fd77480-ab18-11ea-8eda-a53514077bb2.png">
[comfy_default_cube_B_node_002.blend.zip](https://github.com/nortikin/sverchok/files/4755905/comfy_default_cube_B_node_002.blend.zip)

Still I could not find a sane way to proceed with extrude, from the newly made polygon face from "bevel vertice only" -- ideally there should be a new mask to use for extrude?

**Comment by Durman** [comment]
![2020-06-10_08-14-46](https://user-images.githubusercontent.com/28003269/84226325-847fd880-aaf2-11ea-8f16-12d5bbb6fc66.png)

**Comment by enzyme69** [comment]
@Durman You rocks!!! This is exactly the node I was looking for~
