### ISSUE TITLE
Stadium like / circle stairs

### ISSUE THREAD

**Issue by DaveSledz** [nortikin/sverchok#3337]
Hi guys, I'm trying to create stairs/steps in shape of a stadium just like on this example:
![foto-tomada-por-uno-de](https://user-images.githubusercontent.com/45789626/84259490-d9364a00-ab18-11ea-9908-9aab93e7af8a.jpg)

I came into two ideas how to co create this - first was to start with circle and use Contour 2D node and use matrix scale but the scale affects lenght of steps. The second was to use scaled circles and try to extrude faces from number range but the faces were overlapping.

My question is: what node should I use to cut overlapping faces and be able to extrude them just like normal stairs? If you have another approach to this - please let me know. Unfortunatly I couldn't find a good solution from Jimmy's videos and blogs.

![Zrzut ekranu 2020-06-10 o 12 42 51](https://user-images.githubusercontent.com/45789626/84260618-9ffed980-ab1a-11ea-8939-e9855ada0716.jpg)
![Zrzut ekranu 2020-06-10 o 12 40 30](https://user-images.githubusercontent.com/45789626/84260628-a3926080-ab1a-11ea-8c97-707b878afafd.jpg)

**Comment by nortikin** [comment]
my layout, it may help if something.
Contour - is right way.
Separate loose, sort by path length total, and move copy upper than as in my example.
https://gist.github.com/3e9aca804763cab245b5044d8ac1920c
![Снимок экрана от 2020-05-28 21-24-40](https://user-images.githubusercontent.com/5783432/84262287-089f8380-ab26-11ea-88e5-382d428316e1.png)

**Comment by nortikin** [comment]
some features are in exec node, i wish i could gather them to SNL some time and maybe than to new nodes

**Comment by zeffii** [comment]
or, using `numb_ranges` , these are great puzzles.

![image](https://user-images.githubusercontent.com/619340/84492184-13812200-aca6-11ea-9994-ca33df2fbed2.png)
