### ISSUE TITLE
CFFI and snlite

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3342]
installation of CFFI and vc15 are described in [another thread](https://github.com/nortikin/sverchok/issues/2345). a short recap might be added here at some point. Most of this is `scorpion81`'s handy work. 

## compile_wrapper.py
```python
"""
in parameters v
out result v
fh
"""
    
lib = None
mdl = None
func = None
param = {}
result = [0.0]
#in_socks_c = []
cdef = ""
code = ""
#parameters = [1, 2]

 
def load(name):
    import bpy, imp
    code = bpy.data.texts[name].as_string()
    mdl = imp.new_module(name)
    # warning, dangerous !
    exec(code, mdl.__dict__)
    return str(getattr(mdl, "cdef")) , str(getattr(mdl, "code"))

def execute(lib, mdl, function, params):
    import timeit
    
    def wrapper(func, *args, **kwargs):
        def wrapped():
            return func(*args, **kwargs)
        return wrapped
    
    args = [lib]
    print("EXEC", params)
    for p in params:
        args.append(p) 
    # take from sockets later....
    f = getattr(mdl, function)
    print(f)
    w = wrapper(f, *args)
    # print("Function execution", function,  timeit.timeit(w, number=1))
    return [w()]

def wrap(func, param):
    import imp
    params = ""
    le = len(param.items()) - 1
    #print(le)
    for index, i in enumerate(param.items()):
        #print(index, i)
        if index < le:
            params += (i[0] + ",")
        else:
            params += i[0]
            
    function = func[1]    
    print(function, params)
    
    code = "def "+function+"(lib, " + params +"):\n return lib."+function+"("+params+")"
    mdl = imp.new_module(function)
    #warning, dangerous !
    exec(code, mdl.__dict__)
    return mdl

def map_sockets(func, params, socks_v):
    mdl = None
    for i, p in enumerate(params):
        param[p[1]] = socks_v[i][0]
    
    print("PARAM", param)       
    mdl = wrap(func, param)
    
    return mdl
    
    
def testfn(i):
    return i % 2 == 1

def parse(item):
    item = item.strip()
    print("ITEM1", item)
    x = item.split("(")
    print("X", x)
    n = x[0].split(" ")
    o = x[1].split(")")[0].split(",")
    print("PARSE", o)
    t = []
    for i in range(0, len(o)):
        o[i] = o[i].strip()
        tk = o[i].split(" ")
        t.append((tk[0], tk[1]))
    return n, t

def test(item):
    it = item.strip()
    return it != ""

def parse_functions(cdef):
    #expect only one function prototype, for now
    itemz = cdef.split("\n")
    print(itemz)
    ite = [parse(it) for it in itemz if test(it)]
    print(ite)
    return ite[0]
    
def compile(cdef, code):
    
    import bpy, os, cffi
    #todo, make configurable
    path = os.path.dirname(bpy.data.filepath)
    pypath = bpy.app.binary_path + "../2.83/python/include"
    bpath = path + "/build"
    src = "/home/martin/BlenderSVN/blender_git/source/blender/"
    inc = ["blenkernel", "makesrna", "makesdna", "blenlib", "makesrna/intern"]
    incdirs = [src + i for i in inc]
    incdirs.append(pypath)
    
    ffi = cffi.FFI()		
    ffi.cdef(cdef)
    lib = ffi.verify(code, tmpdir=bpath, include_dirs=incdirs)
    
    return lib

name = self.user_filename

if  name != "":
    cdef, code = load(name) 
        
if len(cdef) > 0:
    func, params = parse_functions(cdef)
    print("FP", func, params) 
    mdl = map_sockets(func, params, parameters)

if len(cdef) > 0 and len(code) > 0:
    lib = compile(cdef, code)
 
if lib is not None and mdl is not None and func is not None:
    params = []
    for p in param.items():
        params.append(p[1])   
    result = execute(lib, mdl, func[1], params)   
```
and the c code is currently evaluated from a string

## c_add.py
```python
cdef = """
            float add(float a, float b);
       """

code = """
            float add(float a, float b)
            {
	            return a + b;
            }
       """
```
so you load the wrapper file, and when that loads you can read the datablock `c_add.py`

![image](https://user-images.githubusercontent.com/619340/84574771-14e74300-ada9-11ea-8d4b-9610dd0ac165.png)

**Comment by zeffii** [comment]
my hope is to turn it into a standard node, or add new backend to snlite to take care of the boilerplate. scorpion81 also make a dedicated node. I recall [this was a start](https://github.com/nortikin/sverchok/issues/2345#issuecomment-451665374), but the .blends in the thread also include an alternative `SvCFFINode` (more prototype)

**Comment by portnov** [comment]
So the goal is to let the user write scripts in C instead of python?

Do you have any practical ideas when this would be appropriate?

**Comment by zeffii** [comment]
it's more so I can get my head around implementing algorithms in C.  i need to get away from writing just python

**Comment by Durman** [comment]
It would be nice to bring into Sverchok performance of other faster then Python languages. I don't know is it possible without any dependencies? We can again have a look at Animation nodes. As far as I know C language is used thier but installation process is more advance.

**Comment by portnov** [comment]
AN use Cython (something in between C and Python). They have to build versions for different platforms, as far as I understand.

And again, for most problems where most time is spent in actual computations (not in copying data from node to node, or re-calculating the same thing N times), where I see, Numpy usage makes everything much faster without any C. And sometimes even faster than C, because of SIMD instructions usage.

**Comment by portnov** [comment]
Just an example: I have a draft of node, which uses pygalmesh - bindings for CGAL: https://github.com/portnov/sverchok-extra/pull/19
One would expect the node to be very fast, because... well, it's in fact written in C++!
But it is in fact very slow, nearly as slow as pure-python implementation of marching cubes algorithm. Why? Because the bindings themselves are written so that C++ side is calling a Python function to calculate scalar field value, and this is a separate call for each point where C++ part wants to evaluate the scalar field. If C++ part would ask for all wanted points in one call, Python could evaluate all points in one numpy vectorized computation; but calculating something one point at a time in Python is in general a bad idea...
What I want to say is that C or C++ are not silver bullets. You have to design C/Python interaction very carefully to actually achieve performance boost.

**Comment by Durman** [comment]
Yes numpy is great help but there is some reasons to look toward other languages as well.

- Not all algorithms are using array like data structure. For example when I was searching existing implementation for `wave function collapse` node I tried numpy implementation and its performance was worse then implementation on pure Python. 
- Another greater advantage is using existing libraries written on C for example which does not have analog in Python libraries.

**Comment by portnov** [comment]
1. Well, probably there are such problems. Just I've never run in them.
2. The possibility to use existing C/C++ libraries is a great advantage, yes. There are bindings for many of them, and for those there aren't we can write our own. In my opinion, nodes that use such libraries should go to Sverchok-Extra, to leave core Sverchok installation as easy as possible.

**Comment by zeffii** [comment]
agreed, a dedicated CFFI node would be appropriately implemented in Sverchok-extra

for the time being i'll use SNLite, and maybe add a directive to automate the boilerplate, as far as possible. but first get invested in writing the C, then simplifying the ecosystem.
