### ISSUE TITLE
GLSL Shader node / Hilma binding etc

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3347]
Is this GLSL something that can plug to SVerchok and output a mesh of some sort?
https://github.com/patriciogonzalezvivo/glslTexture

**Comment by enzyme69** [comment]
Hilma Python:
https://github.com/patriciogonzalezvivo/hilma

**Comment by zeffii** [comment]
there are different things here , 
- the glslTexture stuff seems to just output a bitmap of a given size, where each pixel is coloured by the fragment shader 
- whereas hilma seems to be outputting `.ply`,  but from what i can tell this is not GLSL. but referring to GLTF.

**Comment by enzyme69** [comment]
I see thanks Zeffi, I think Hilma might be interesting for me to test because it is also python.

GLSL also but shader is too weird for me. I tried OSL.
