### ISSUE TITLE
BM Viewer upgrade

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3356]
currently in Live mode we wipe an object's mesh (data)  by generating a bmesh representation of the new desired mesh and doing `bm.to_mesh(obj.data)` . in `2.8+` Blender devs introduced another method to wipe an object's mesh ( `mesh.clear_geometry()` or something ) . A nice experiment would be to see if there are benefits of adding a feature to BMviewer, which build up the `mesh` directly, rather than first writing bmesh data.

- it could be faster
- it could include better error/consistency checking in the implementation language
- it could allow certain modifiers to work without workarounds (modifiers like skin modifier doesn't work out of the box between updates when we do `bm.to_mesh(obj.data)`

**Comment by zeffii** [comment]
in particular : 
https://devtalk.blender.org/t/alternative-in-2-80-to-create-meshes-from-python-using-the-tessfaces-api/7445/3

**Comment by zeffii** [comment]
if it's faster it will be the default..and maybe only mode :)

**Comment by zeffii** [comment]
something like
```python

if using_mesh_clear():
    flat_verts = list(itertools.chain.from_iterable(verts))
    mesh.vertices.foreach_set('co', flat_verts)

    if edges:
        flat_edges = list(itertools.chain.from_iterable(edges))
        mesh.edges.add(len(edges))
        mesh.edges.foreach_set("vertices", edges)

    if faces:
        flat_faces = list(itertools.chain.from_iterable(faces))
        vertex_index = numpy.array(flat_faces, dtype=numpy.int32)

        loop_start_indices = ...
        loop_start = numpy.array(loop_start_indices, dtype=numpy.int32)

        loop_lengths = ...
        loop_total = numpy.array(loop_lengths, dtype=numpy.int32)

        num_vertex_indices = vertex_index.shape[0]
        num_loops = loop_start.shape[0]

        mesh.loops.add(num_vertex_indices)
        mesh.loops.foreach_set("vertex_index", vertex_index)

        mesh.polygons.add(num_loops)
        mesh.polygons.foreach_set("loop_start", loop_start)
        mesh.polygons.foreach_set("loop_total", loop_total)

    mesh.update()
    mesh.validate()

```

**Comment by zeffii** [comment]
this perhaps..
```python
import numpy as np



if using_mesh_clear():
    mesh.clear_geometry()
    flat_verts = list(itertools.chain.from_iterable(verts))
    mesh.vertices.add(len(verts))
    mesh.vertices.foreach_set('co', flat_verts)

    if edges:
        flat_edges = list(itertools.chain.from_iterable(edges))
        mesh.edges.add(len(edges))
        mesh.edges.foreach_set("vertices", edges)

    if faces:
        flat_faces = list(itertools.chain.from_iterable(faces))
        vertex_index = numpy.array(flat_faces, dtype=numpy.int32)

        loop_lengths = [len(f) for f in faces]
        loop_start_indices = np.cumsum([0] + loop_lengths[:-1])
        loop_start = numpy.array(loop_start_indices, dtype=numpy.int32)
        loop_total = numpy.array(loop_lengths, dtype=numpy.int32)

        num_vertex_indices = vertex_index.shape[0]
        num_loops = loop_start.shape[0]

        mesh.loops.add(num_vertex_indices)
        mesh.loops.foreach_set("vertex_index", vertex_index)

        mesh.polygons.add(num_loops)
        mesh.polygons.foreach_set("loop_start", loop_start)
        mesh.polygons.foreach_set("loop_total", loop_total)

    mesh.update()
    mesh.validate()
```

**Comment by zeffii** [comment]
the materials tab in blender 2.90 alpha is a little    "unpredictable" and keeps crashing on me so more testing will come later. see the PR.

https://github.com/nortikin/sverchok/pull/3357

**Comment by zeffii** [comment]
@portnov  do you know if there's a safe index for faces that have no material assigned?  or is that the equivalent to 0, and the materials indices for real materials starts at 1 ?

**Comment by zeffii** [comment]
because .. haha

https://github.com/nortikin/sverchok/blob/c55da860c98b181ef80a037f6844c39da354c0db/nodes/viz/viewer_bmesh.py#L135-L144

**Comment by zeffii** [comment]
also interesting.. 
https://github.com/mont29/blender-io-fbx/blob/ea45491a84b64f7396030775536be562bc118c41/io_scene_fbx/import_fbx.py#L655-L684

**Comment by portnov** [comment]
It seemed to me that all faces have some material assigned by default anyway. Just default material index is 0, which means use first material.

**Comment by Durman** [comment]
> A nice experiment would be to see if there are benefits of adding a feature to BMviewer, which build up the mesh directly, rather than first writing bmesh data.

https://github.com/nortikin/sverchok/issues/2767#issuecomment-586631148
And other comments below.

**Comment by zeffii** [comment]
weird issue as mentioned on the blender.org dev thread that :
- if setting edges via foreach_set then the `edges` aren't 'updated' (shown in view) until the mesh has been in and out of Edit mode.  

so.. for now this is a dead end.
