### ISSUE TITLE
[BUG] search dont work

### ISSUE THREAD

**Issue by Zawarud** [nortikin/sverchok#3361]
search dont work with blender 2.83 and 2.90

**Comment by zeffii** [comment]
you must `+new`  a new node tree first.

**Comment by zeffii** [comment]
`alt+space` is our shortcut for search

**Comment by zeffii** [comment]
search from the node "Add" menu - does indeed not work.

**Comment by zeffii** [comment]
another way to get that search field is 
- rightlick the nodeview
- pick "node menu"
- go to `Search  (alt+space )`

![image](https://user-images.githubusercontent.com/619340/85288570-3d042f80-b496-11ea-9dcb-774a70bc98b1.png)
