### ISSUE TITLE
ways to draw straight lines and matrices

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#3363]
good day, are there are specific nodes in sverchok that would help me make these 2 things:

- creating a line, straight line that links a specific point with another specific point. And even better if that line can somehow be animated in some way

- Taking a math matrix, say 2x128, or 1x128 (1 row, 128 columns), and draw it with a rectangle and put different colors in each of its columns visually (feeding the data from python of course)

just exploring to see if sverchok has nodes that could help with these, thank you :)

**Comment by javismiles** [comment]
![line1](https://user-images.githubusercontent.com/1000452/85364728-0f65c780-b524-11ea-81ba-f604039a26fe.jpg)

This used to work but its not working for me in latest 2.82, what is wrong in the parameters?

And this will connect one line with the other, what if I wanted them to be independent?
say in a file I have 100 lines, each has 6 coordinates, point A and point B, each should be an independent line, going from A to B, without linking them all

any way to do that?

and any way to animate in some way the lines? thank you :)

**Comment by javismiles** [comment]
![lines2](https://user-images.githubusercontent.com/1000452/85364924-8ef39680-b524-11ea-8361-57164a1ec9a8.jpg)

it works if i take the vector math node out, mmm, whats wrong with how i use that node?

and question now is what if i want a bunch of independent lines, not following each other

**Comment by javismiles** [comment]
![lines3](https://user-images.githubusercontent.com/1000452/85365156-09bcb180-b525-11ea-9910-731f63ad2e0c.jpg)

yes, now it works, so now questions then are:

- how to make x independent lines, not linked to each other
- how to also visualize content of a matrix nxm, different colors on each cell of matrix

**Comment by zeffii** [comment]
i don't really understand the question the way it's phrased.

perhaps if you supply us an example .csv with said coordinates, and a drawing of what you would expect the output to be, then the nodetree will be easy to suggest/fix

**Comment by zeffii** [comment]
remember the Polyline viewer, will just be passing a list of coordinates to to a function that makes a SPLINE/PATH type Curve object. It requires no edges, because it expects the desired effect is that sequential vertices are linked, like a PolyLine (hence the name).

if you want polyline to generate Truely separate Splines, then you must feed it multiple lists of verts. Right now your Vertex list is a single long list. You could split that list after the first `Vector In` into x number of lists of length 2. -- each sublist will have two verts.

i'm not sure why you need the interpolator node.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/85379143-bb66dd00-b53b-11ea-91a3-0f973f861362.png)

there does seem to be a bug in the PolylineViewer when switching between Single and Multiple objects -- it doesn;t delete the dead unused objects . will fix asap. (in the meantime you can manually delete those objects after you switch mode, and from then on it will do the correct thing..until you change the mode again.)

**Comment by javismiles** [comment]
@zeffii thank you very much, I ended up using the grease pencil blender pythong api which works well for creating lines, but I will also try what you tell me here. 

The other thing in which I was wondering if maybe Sverchok could help me was that I wanted to take data from a matrix or vector, let´s suppose a 2x128 matrix, 2 rows, 128 columns, 
and create a plane, mesh plane, subdivided in those 2x128 cells, and put a different color in each cell according to the values of a csv file or python tensor-array etc, any way to do that?

**Comment by zeffii** [comment]
we do have a GreasePencil node too btw, it's similar to PolylineViewer (but you must first fill in a unique name into the object name field )

- the colour planes, could technically be done in the GP node too.
- or.. using VertexColors like the other stuff you were doing ( a drone i believe ?)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/85389347-9710fd80-b547-11ea-906b-30cbc048f7f7.png)

**Comment by zeffii** [comment]
for lines this is what is possible with GP. disable the cyclic-drawing 
![image](https://user-images.githubusercontent.com/619340/85389713-169ecc80-b548-11ea-83f7-3cf81706645e.png)

**Comment by javismiles** [comment]
@zeffii this is great zeffii, Im going to try what you sent me and see how it goes, both of them, thank you again, will report back in here

**Comment by javismiles** [comment]
@zeffii works great thank you zeffii, now I will see how to feed the data, so that lines go from specific points to specific points for example, thank you

**Comment by javismiles** [comment]
@zeffii with grease pencil, once lines are drawn, lines or rectangles etc, can they be moved and changed, or they have to be redrawn I guess, they dont have an id or anything I guess

**Comment by javismiles** [comment]
@zeffii ah yes I found how to manage them, great, this is good, this could be a solution, thank you Zeffi :)

**Comment by zeffii** [comment]
the GP node is not extensively tested, or even fully featured yet. useful for basic drawing and an example of the GP API usage.
