### ISSUE TITLE
how to make a Clifford Torus?

### ISSUE THREAD

**Issue by stansu** [nortikin/sverchok#3364]
[like this ](https://youtu.be/1_pzjvVixL0)

**Comment by asahidari** [comment]
Excuse me for jumping in. But I had researched for related things before.
You can do that with Rotation4D template in Script Node Lite added recently.

But without modification for the script, the output is rotated around z-axis when 't' parameter changed.
If you want to do that without the rotation, you have to modify 'evaluate' and 'evaluate_grid' function like this:
```python
    def evaluate(self, x, y, z):
        p, q, t = self.p, self.q, self.t
        ...
        # now rotate the hypersphere (use p = q = 1 for isoclinic rotations)
        # and vary t between 0 and 2*PI
        # xc = +xb * cos_pt + yb * sin_pt   # comment out this line 
        # yc = -xb * sin_pt + yb * cos_pt    # comment out this line
        xc = xb    # add this line
        yc = yb    # add this line
        ...
    def evaluate_grid(self, xs, ys, zs):
        p, q, t = self.p, self.q, self.t
       ...
        # now rotate the hypersphere (use p = q = 1 for isoclinic rotations)
        # and vary t between 0 and 2*PI
        # xc = +xb * cos_pt + yb * sin_pt   # comment out this line 
        # yc = -xb * sin_pt + yb * cos_pt    # comment out this line
        xc = xb    # add this line
        yc = yb    # add this line
        ...
```
You can get a result like this:
![CliffordTorus](https://user-images.githubusercontent.com/64673405/86258191-80c50a80-bbf5-11ea-84d1-980e3b6e3e58.gif)

**Comment by stansu** [comment]
> Excuse me for jumping in. But I had researched for related things before.
> You can do that with Rotation4D template in Script Node Lite added recently.
> 
> But without modification for the script, the output is rotated around z-axis when 't' parameter changed.
> If you want to do that without the rotation, you have to modify 'evaluate' and 'evaluate_grid' function like this:
> 
> ```python
>     def evaluate(self, x, y, z):
>         p, q, t = self.p, self.q, self.t
>         ...
>         # now rotate the hypersphere (use p = q = 1 for isoclinic rotations)
>         # and vary t between 0 and 2*PI
>         # xc = +xb * cos_pt + yb * sin_pt   # comment out this line 
>         # yc = -xb * sin_pt + yb * cos_pt    # comment out this line
>         xc = xb    # add this line
>         yc = yb    # add this line
>         ...
>     def evaluate_grid(self, xs, ys, zs):
>         p, q, t = self.p, self.q, self.t
>        ...
>         # now rotate the hypersphere (use p = q = 1 for isoclinic rotations)
>         # and vary t between 0 and 2*PI
>         # xc = +xb * cos_pt + yb * sin_pt   # comment out this line 
>         # yc = -xb * sin_pt + yb * cos_pt    # comment out this line
>         xc = xb    # add this line
>         yc = yb    # add this line
>         ...
> ```
> 
> You can get a result like this:
> ![CliffordTorus](https://user-images.githubusercontent.com/64673405/86258191-80c50a80-bbf5-11ea-84d1-980e3b6e3e58.gif)

You are the man! Thanks for sharing.
