### ISSUE TITLE
How to move plane vertices based on other vertices with proportional (edit) falloff?

### ISSUE THREAD

**Issue by ricardomatias** [nortikin/sverchok#3369]
As the 1st image below shows, I've got a plane and a curve. I want to move the plane's closest points to the curve with the proportional fallof node in order to make something like the 2nd image.

The 2nd image is from a book based on Grasshoper, in a section about surfaces. Perhaps someone has another approach to model such surface curvatures.

Thanks in advance!

![Screenshot from 2020-06-25 19-20-04](https://user-images.githubusercontent.com/8850708/85769265-1d7d3900-b71a-11ea-82b5-059450391365.png)

![Screenshot from 2020-06-25 19-30-10](https://user-images.githubusercontent.com/8850708/85769570-6634f200-b71a-11ea-84cc-976202c191f7.png)

**Comment by portnov** [comment]
As one of options, you can do it in a similar way :)
![Screenshot_20200625_224516](https://user-images.githubusercontent.com/284644/85771689-98a01880-b735-11ea-8b95-5705bb117c06.png)

**Comment by ricardomatias** [comment]
@portnov thanks a bunch, exactly what I wanted.

![curved-surface](https://user-images.githubusercontent.com/8850708/85792334-989f1900-b733-11ea-93fe-5a87a33daec1.png)
