### ISSUE TITLE
Obj instancer node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3370]
It looks like the node does not expect changings in list of input objects. When I change seed (random switch between two meshes) there is no any reaction from the node.

![2020-06-26_08-56-42](https://user-images.githubusercontent.com/28003269/85822244-79cc7100-b78b-11ea-807c-517015f55a7d.png)

[TEST obj instancer.zip](https://github.com/nortikin/sverchok/files/4835179/TEST.obj.instancer.zip)
@willneedit

**Comment by zeffii** [comment]
weird. @durman do you know if it always was this way? i can't remember.

**Comment by Durman** [comment]
I guess this is start point to search #2902
In this PR new features was implemented which was never well tested.

**Comment by zeffii** [comment]
i think this is more related to @vicdoval  animatable stuff?  the node is getting fresh input but ignoring it.

**Comment by Durman** [comment]
I don't think so. I was trying to relink node and switch on/off update button on the node what would definetly trigger update process but no any reaction. Also change matrixes works well what would not be if any troubles with update triggering.

**Comment by zeffii** [comment]
weirdly if you press 'full copy'  it does update the input list.

**Comment by zeffii** [comment]
> I don't think so

yeah, maybe not. : /  a tricky node.

**Comment by zeffii** [comment]
i'll fix this tomorrow, seen as it is the worst kind of user-facing bug .

**Comment by zeffii** [comment]
the bug is in 
```
def make_or_update_instance(node, obj_name, matrix, blueprint_obj):
```
i think here
```python
    collections = bpy.data.collections
    collection = collections.get(node.basedata_name)

    if obj_name in objects:
        sv_object = objects[obj_name]

        < ------------- >

    else:
        data = blueprint_obj.data# data_kind.get(data_name)

        if node.full_copy:
            sv_object = blueprint_obj.copy()
            sv_object.name = obj_name
        else:
            sv_object = objects.new(obj_name, blueprint_obj.data)
        
        collection.objects.link(sv_object)
```

**Comment by zeffii** [comment]
```python
    if obj_name in objects:
        sv_object = objects[obj_name]
        if sv_object.data != blueprint_obj.data:
            sv_object.data = blueprint_obj.data
```

**Comment by zeffii** [comment]
good catch @Durman

**Comment by zeffii** [comment]
( untested )
