### ISSUE TITLE
SNL node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3380]
Weird bug. I guess that it is related with last update system changes because I did not manage to reproduce the bug with my experimental update system. 

In my case it does not reproduce each time. I have to open the file several time to get it. Probably such instability it is related with Sverchok loading order. Also it is related with a similar socket names of SNL nodes I think.

![2020-06-29_13-20-53](https://user-images.githubusercontent.com/28003269/85995107-fa4ed400-ba0e-11ea-9395-24dcfa253802.png)

[test1.zip](https://github.com/nortikin/sverchok/files/4844876/test1.zip)

**Comment by vicdoval** [comment]
I also found this bug in one file some time ago,  I came along by changing the name of the sockets... 

Now i see that when coping a snl the old node_id gets copied to the new node, but in node_tree.py we can find
```
def copy(self, original):
        ... ...
        self.sv_copy(original)
        self.n_id = ""
        ... ...
```
Maybe is something related to the SNL loading process...

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/86012407-350c3880-ba1e-11ea-9444-e374d4cd8f42.png)

**Comment by zeffii** [comment]
using the duplicate/copy node feature may not be doing what i expected.  I've avoided this bug somehow :)

**Comment by vicdoval** [comment]
@Durman  can you check if you can still find the bug after #3381

**Comment by Durman** [comment]
@vicdoval Yes it looks like the problem is gone in new layouts. But what about old one? They are already broken and the fix does not improve them.

**Comment by vicdoval** [comment]
@Durman  Running this script should fix the old layouts
```
import bpy
for ng in bpy.data.node_groups:
    for node in ng.nodes:
        if node.bl_idname == 'SvScriptNodeLite':
            node.n_id= ""
```

**Comment by Durman** [comment]
For running this script you should know about existing of this script and that your particular bug could be fixed by it. Also there could be significant amount of layouts which should be repaired manually. Don't think this is good solution.

**Comment by zeffii** [comment]
my perspective is that this issue will only affect 
- `.blend` files older than two months. (when "less global updates" PR was merged)
- and those node tree where the users used "clone/copy" node

this makes it a little bit of a question if it makes sense to add any extra permanent code, to fix a relatively temporal potential bug.  i am not convinced.

**Comment by zeffii** [comment]
unless we add a cleanup step in the .blend post-load handler, which i think would not be a disaster.
