### ISSUE TITLE
Renaming viewer nodes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3390]
## Problem statement

Renaming objects names in viewer nodes creates copy of an object with new name. I would expect current name of an object would be changed.

![2020-07-06_21-44-22](https://user-images.githubusercontent.com/28003269/86623291-62368900-bfd2-11ea-9f81-d2b7132d1bed.png)

**Comment by zeffii** [comment]
this is tricky, there is a scenario where i have used the feature (changing basename) to have a trail effect of old objects.

My thoughts on this are that the more liberal implementation of renaming the basename + autorenaming of generated objects, is done via an Operator. 
 - select the node
 - trigger the (unwritten) operator to change the basename + update children.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/2825

**Comment by zeffii** [comment]
@vicdoval @Durman   check out the rename operator :)  only implemented in bmview for testing.

**Comment by Durman** [comment]
It looks it is working. I will agree with UI solution if the text field won't be editable. Because it too gives opportunity to rename object but it will create copy of an object with new name instead.

![2020-07-13_22-50-32](https://user-images.githubusercontent.com/28003269/87342054-a211e900-c55b-11ea-8731-e9d273bdfa05.png)

**Comment by Durman** [comment]
I think with setter and getter the UI can be done more elegant. I mean it can remain as it was without new button and window.

https://docs.blender.org/api/current/bpy.props.html#getter-setter-example

**Comment by vicdoval** [comment]
I like it, it gives a new feature that was not possible before...
Other approach that could also work would be:
- if the text-field is edited -> rename 
- Button to make a "unconnected" copies

**Comment by vicdoval** [comment]
And some improvements for the actual implementation:
"Cancel" Button although it can be cancelled with Escape key it would make it clearer
Cancel operator if pop-up text-field is empty

**Comment by zeffii** [comment]
I'm partial to using the operator _only_ method to set the string in `basedata_name` , and making the string non-editable on the node UI, possibly removing the updatefunc for that property completely.

but i'm distracted with other worries right now, so if you collectively can settle on an approach that treats the user with more respect than I do, then certainly move towards implementing that.
