### ISSUE TITLE
Latest SVerchok addon update gives "search node error"

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3394]
## Problem statement

After uploading to latest sverchok

Shift A + search now give me error:
<img width="998" alt="Screen Shot 2020-07-08 at 10 35 41 am" src="https://user-images.githubusercontent.com/3952687/86859806-d83c0c80-c106-11ea-958b-a2211303ee42.png">

## Steps to reproduce

as above

## Expected result

it should give me list of nodes with that name

## Actual result

instant error popup

## Sverchok version
latest

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
if this still happens after starting Blender again then

@enzyme69  @vicdoval  i think the new FreeCAD dependency code handling must be revisited,  this works fine when FreeCAD is found.  but throws this error when it isn't found.

**Comment by zeffii** [comment]
the function `ensure_valid_show_string` is only called in one place,

in `gather_items`
```python
def gather_items():
    fx = []
    idx = 0
    for _, node_list in node_cats.items():
        for item in node_list:
            if item[0] in {'separator', 'NodeReroute'}:
                continue
            
            fx.append((str(idx), ensure_valid_show_string(item), '', idx))
            idx += 1

    for k, v in macros.items():
        fx.append((k, format_item(k, v), '', idx))
        idx += 1
    
    fx_extend(idx, fx)

    return fx
```

**Comment by zeffii** [comment]
i think dummy nodes aren't found by the function "get_node_class_reference"

**Comment by zeffii** [comment]
i think it doesn't make sense to have nodes which haven't found their dependencies show up in the sv_extra_search. So something like this is in order
```diff
def gather_items():
    fx = []
    idx = 0
    for _, node_list in node_cats.items():
        for item in node_list:
            if item[0] in {'separator', 'NodeReroute'}:
                continue
+           if item[0] in dummy_set:
+               continue
            
            fx.append((str(idx), ensure_valid_show_string(item), '', idx))
            idx += 1

    for k, v in macros.items():
        fx.append((k, format_item(k, v), '', idx))
        idx += 1
    
    fx_extend(idx, fx)

    return fx
```

**Comment by vicdoval** [comment]
Should be fixed now,:D

**Comment by enzyme69** [comment]
Thanks y'all!
