### ISSUE TITLE
Wondering how: to converted 3D extrusion into 3D vector displacement?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3400]
<img width="663" alt="Screen Shot 2020-07-12 at 11 20 27 am" src="https://user-images.githubusercontent.com/3952687/87236873-c2458900-c431-11ea-9404-f4583ee82428.png">

<img width="739" alt="Screen Shot 2020-07-12 at 11 18 50 am" src="https://user-images.githubusercontent.com/3952687/87236874-c671a680-c431-11ea-81b3-033f05fdab94.png">

Earlier today I saw oscurart and seeing his "3D baker" for vector displacement.

I am wondering maybe there is a way to bake 3D into a flat plane but morphing it into 3D texture vector displacement.

**Comment by enzyme69** [comment]
Maybe I can start from here, but still it does not make sense how to make from flat to 3D

<img width="800" alt="Screen Shot 2020-07-12 at 11 53 01 am" src="https://user-images.githubusercontent.com/3952687/87237212-ce801500-c436-11ea-8301-a0689c1e107b.png">

**Comment by enzyme69** [comment]
And maybe I need to turn them into UV grid then somewhat morph 🤔 to get vector RGB value of the final position?

**Comment by nortikin** [comment]
in blender there is normal map, you can create it inside blender

**Comment by enzyme69** [comment]
<img width="1680" alt="Screen Shot 2020-07-16 at 1 38 47 pm" src="https://user-images.githubusercontent.com/3952687/87623864-b3c8db80-c769-11ea-8329-79a6d4390c38.png">

Erin gave me example for of extrusion but as shader.

I am wondering on how to substract the original position to end position vector, but as shader, involving UV.

The closest I could think is like Shapekeys starting position and end position...

**Comment by enzyme69** [comment]
From ErinDaleXYZ:
[RandomExtrusion.blend.zip](https://github.com/nortikin/sverchok/files/4929171/RandomExtrusion.blend.zip)

Shader Vector Displacement is crazy.
