### ISSUE TITLE
Introduction to Sverchok dated

### ISSUE THREAD

**Issue by bluecondor** [nortikin/sverchok#3401]
## Problem statement

I just started going through your introduction tutorial here: http://nikitron.cc.ua/sverch/html/Unit_01/lesson_02.html and I see many things have changed, from the names of the nodes to how they work.

**Comment by zeffii** [comment]
i updated them, but they haven't been compiled and pushed to the online resources yet. @nortikin @portnov  

i didn't manage to get the readthedocs to compile online..

@bluecondor  in the meantime, read them here:

https://github.com/nortikin/sverchok/pull/3198

**Comment by bluecondor** [comment]
Thank you very much for the quick reply @zeffii!

**Comment by zeffii** [comment]
they are updated here too, compiled correctly.
http://nikitron.cc.ua/sverch/html/induction.html
