### ISSUE TITLE
FreeCAD boolean

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3404]
https://github.com/nortikin/sverchok/blob/70e14ec61c197148f23d6bf47dd19e4ed815db34/nodes/solid/solid_boolean.py#L14

interesting to see in openCascade coplanar faces and coincident edges are also problematic.
https://wiki.freecadweb.org/Part_Boolean

**Comment by vicdoval** [comment]
Yes.. by the moment i found some glitches joining cylinders with tangent faces but no troubles with co-planar faces in boxes...
![image](https://user-images.githubusercontent.com/10011941/87811537-1cde4b00-c85f-11ea-8764-4f5265db6fa4.png)
