### ISSUE TITLE
compas cad

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3408]
https://compas-dev.github.io/examples/mesh-cutting/mesh-cutting.html

i don't know if this is great or just meh. but it seems interesting.

**Comment by portnov** [comment]
Hm. I don't quite understand what it is. There is well-known in Russia CAD named Compass 3D (kompas.ru, it's in russian, but you can look at pictures to understand what it is about), but that thing is far from being free or opensource. Now, does this COMPAS have any relation to that Kompas?... I'm confused.

**Comment by zeffii** [comment]
i don't know. but it's on the radar now :)

**Comment by zeffii** [comment]
https://github.com/compas-dev/compas
