### ISSUE TITLE
Presenting nodes with dependencies in menu

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3410]
As far as I understand the nodes which are not available according not installed Python modules are not presented in the `add node` menu. 

I think it makes more difficult to learn those nodes. For example if one install one of the dependencies you have to investigate all `add nodes` menu to find new nodes and most likely you will not spot them from first time among huge number of available nodes. 

It would be much easier if you first find a node read documentation and required dependencies and decide would it be useful install it.

**Comment by zeffii** [comment]
I oppose that. i think only nodes that you can add immediately (etc..without restarting, adding decependancy paths) should appear in the `add` menu. 

What we can do is create a neat html/js/brython page that shows a list of all available "extra" nodes, and shows which dependencies (perhaps multiple) are needed for them to load correctly.

for every category :
- category
   - node name 
       - description + link to documentation
       - required dependancies: [module name, lib_name]

**Comment by Durman** [comment]
This may also be a good solution. But in this case it can be more difficult to implement and keep it in actual condition. Also it will be difficult to point to users on to existence of such a list. It diminishes usefulness of moving the nodes from sverchok-extra addon.

**Comment by Durman** [comment]
Probably it would be possible to show such nodes in menu as inactive. 

Just example inactivity.
![2020-09-02_21-13-21](https://user-images.githubusercontent.com/28003269/92015007-33822800-ed61-11ea-9001-150f7f2b313e.png)
