### ISSUE TITLE
applying a texture to a mesh generated by BV node

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#3411]
Good day,
when I create any mesh in blender, I can easily apply a texture to it using image texture and the BSDF shader,

but when I use the sverchok BV node to create a mesh from a set of points for example, and I try to apply an image texture to the mesh it never shows up, doesnt appear, neither in viewport nor in render

Is there anything that I need to do to be able to apply textures to meshes generated by the BV node?
thank you :)

**Comment by zeffii** [comment]
if the mesh is static (like you aren't adding verts/edges/polygons... only transforming them) then perhaps the BV node's N-panel "fixed vertex count" mode might allow to continuously update the mesh data, without wipe-ing the uv data every time the nodetree updates.

i've never tried.

**Comment by javismiles** [comment]
@zeffii thank you, what puzzles me, is that I put live Off, so now its an independent mesh, not being changed by sverchok, and yet I cannot show a texture mapped onto it,
so its now a mesh independent from sverchok, it just was created by sverchok,

**Comment by zeffii** [comment]
then maybe it doesn't have a uvmap.

**Comment by zeffii** [comment]
i think you need to use the sverchok node called "set custom uv map", you should be able to keep the BV node live.

**Comment by zeffii** [comment]
see: https://github.com/nortikin/sverchok/issues/3285

**Comment by javismiles** [comment]
@zeffii thank you very much will try it as soon as possible

**Comment by Durman** [comment]
@javismiles I guess you have to learn Blender before using Sverchok.
https://docs.blender.org/manual/en/latest/modeling/meshes/uv/index.html

**Comment by javismiles** [comment]
@Durman @zeffii will check the uv stuff, thank you very much for the help
