### ISSUE TITLE
Sample UV Color node is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3413]
[color_point_broken_001.blend.zip](https://github.com/nortikin/sverchok/files/4951436/color_point_broken_001.blend.zip)

I have a feeling Sample UV Color node is broken:

Error message:
```python
2020-07-21 15:07:29,432 - sverchok.core.update_system - ERROR - Node Sample UV Color had exception: BVHTree.FromObject() takes at most 5 arguments (6 given)
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/core/update_system.py", line 383, in do_update_general
    node.process()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/sverchok-master/nodes/object_nodes/sample_uv_color.py", line 55, in process
    bvh = BVHTree.FromObject(obj, bpy.context.scene, deform=True, render=False, cage=False, epsilon=0.0)
TypeError: BVHTree.FromObject() takes at most 5 arguments (6 given)
Info: Saved "color_point_broken_001.blend"
```

**Comment by enzyme69** [comment]
<img width="650" alt="Screen Shot 2020-07-21 at 3 11 28 pm" src="https://user-images.githubusercontent.com/3952687/88015422-76e35700-cb64-11ea-9d89-e36820ddd920.png">

Yes it's broken, confirmed twice.

**Comment by Durman** [comment]
The node still uses 2.79 API
https://docs.blender.org/api/2.79/mathutils.bvhtree.html#mathutils.bvhtree.BVHTree.FromObject
https://docs.blender.org/api/current/mathutils.bvhtree.html#mathutils.bvhtree.BVHTree.FromObject

**Comment by zeffii** [comment]
seen as this _is_ broken, and will not have worked in any blend in 2.8+ we can complete update the node and keep the classname + bl_idname.

3 things to fix

1. image -> PointerProperty
2. Object > PointerProperty
3. BVHTree.FromObject using depsgraph.

**Comment by zeffii** [comment]
and the priority for this node is proportional to the number of people that have used it in 2.8 , which is `0` :) ..or.. `1`

**Comment by Durman** [comment]
Probably it is worth deleting?

**Comment by zeffii** [comment]
good question @Durman ,  i don't like to have nodes _just for the sake of having them_, and how useful is that capability ultimately.

if someone really wanted that node, it would be a nice way to get their hands dirty. plenty of examples of nodes that use depsgraph and pointproperty .

**Comment by enzyme69** [comment]
Even if just 1 person using it (me), I think it matters.

**Comment by Kosvor2** [comment]
https://github.com/nortikin/sverchok/pull/3420
