### ISSUE TITLE
Installing dependecies in Ubuntu 20.4

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3414]
I'm trying to move from Windows to Ubuntu 20.4 :partying_face:  and i'm a total newby in Linux so I'm facing many new challenges... One of them is installing the extra-dependencies for Sverchok

I installed Blender from de "Ubuntu Software" App and it landed in snap/blender/.. now I'm not able to install pip or to set the freecad path due [Errno 30] Read-only file system. Maybe you can help me somehow @portnov @nortikin? Should I try to change the folder permissions, change the installation folder or anything else?

**Comment by portnov** [comment]
I do not have any experience with Snap packages. Usually I do not use blender from Ubuntu/Debian repos, as it is usually updated too infrequently there. It's simpler to download tar.gz from blender.org, unpack and run.

Installing dependencies into Snap version of Blender is probably tricky, because snap creates some kind of isolated readonly file system...

**Comment by zeffii** [comment]
@vicdoval  may want to try BlenderUpdater :  https://github.com/overmindstudios/BlenderUpdater  for Blender builds. It's very convenient.

**Comment by vicdoval** [comment]
@portnov thanks that fixed the external dependencies installation... but more problems appeared:
1 - Is there a easy way to enable the blender console? i changed the file Terminal=true in the blender.desktop file but the terminal only appears if i start blender  from a terminal with ./blender

2 - I got the freecad version by `sudo apt install libfreecad-python3-0.18` and as soon i place the path in the prefs and re-start i get total Sverchok Error:
```
import MeshPart
ImportError: libnglib.so: cannot open shared object file: No such file or directory
```
and if i try `import FreeCAD` in the console it works but dosen't if i try  `import MeshPart` (although FreeCAD.so exists and also MeshPart.so) have you experiment anything similar?

@zeffii lets see if i manage to do it with one version first :smiley:

**Comment by nortikin** [comment]
@vicdoval glad you trying Linux. I have two or more years of trying before removed Windows completely. Windows occupied all computers.
I use Debian. It is the same, you know.

1. I never using repository. Download tar.gz from blender org site and unpack.
2. Than i use alias for blender and for addon github installation (you can write that aliases to file ~/.bashrc):
  2.1. ```alias B='~/Downloads/INSTALL/blender-2.82-linux64/blender'``` - just run blender from terminal
  2.2. ```alias LNaddon='{ read -r url&&cd ~/git&&git clone $url&&bn=$(basename $url .git)&&cd $bn&&d=$(pwd)&&us=$(users)&&ln -s $d /home/$us/.config/blender/2.82/scripts/addons/; } <<< '``` - clone git addon and put it to your version, i.e. 2.82 of blender. To run write LNaddon http://github_path_to_addon_git
  2.3. than bashreload with `source ~/.bashrc`
3. my errors (but it works with that errors):
```bash
PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
FreeCAD 0.18, Libs: 0.18R
No modules found in /usr/lib/freecad-python3/Mod
During initialization the error No module named 'freecad' occurred
Dependencies available: pip, scipy, geomdl, scikit-image, circlify, lbt-ladybug, FreeCAD.
```
4. Path to freecadlib ```/usr/lib/freecad-python3/lib/```
5. If dependency not installed, use `sudo apt-cache search libnglib` command to find lost items
6. `libnglib-6.2.1804 - Automatic 3d tetrahedral mesh generator shared library` it is how it called in my case from list of previous step. Beforehand i installed some freecad stuff, so maybe all dependencies OK on my PC was before i started freecadpython3lin installation

**Comment by nortikin** [comment]
![sverchok_b3d](https://user-images.githubusercontent.com/5783432/88101487-b9c61e80-cba6-11ea-8039-b2e30eb4729a.png)

**Comment by nortikin** [comment]
https://github.com/KeithSloan/ImportNURBS
while we here. rhino open nurbs python importing lib. Can be handy.

**Comment by vicdoval** [comment]
Thanks @nortikin  for you detailed instructions :) i managed to create the aliases (into .bash_aliases) I would like to have a blender icon somewhere but that is a minor problem.

It seems that FreeCad had a dependency missed: libnglib . I fixed it following the instructions described here: https://bugs.launchpad.net/ubuntu/+source/freecad/+bug/1866914 

1- run `sudo apt install libfreecad-python3-0.18`
2- run `sudo apt install libnglib-6.2.1804`
3 - add this line` /usr/lib/x86_64-linux-gnu/netgen` to the file  `x86_64-linux-gnu.conf`
4 - run `sudo ldconfig`
 

Maybe we could find a simpler way to make it run :D 

By the moment I think everything works as expected :partying_face: so I will close this issue by the moment.

Thanks again!

**Comment by nortikin** [comment]
it have to be additional instructions somewhere in docs

**Comment by portnov** [comment]
Currently dependencies installation instruction are in the wiki: https://github.com/nortikin/sverchok/wiki/Dependencies (there is a link to this page from readme). Everyone is welcome to improve that page!

**Comment by nortikin** [comment]
added desription to wikkii

**Comment by stansu** [comment]
i encounter permission denied when i use the following command...
```
sudo echo '/usr/lib/x86_64-linux-gnu/netgen' >> /etc/ld.so.conf.d/x86_64-linux-gnu.conf
```
so I just manually edit that file with the root user, it's working now.
