### ISSUE TITLE
Empty Out node does not seem to work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3415]
<img width="716" alt="Screen Shot 2020-07-22 at 11 51 00 am" src="https://user-images.githubusercontent.com/3952687/88125027-bddb5600-cc11-11ea-8c88-c34431659233.png">

This node maybe a little bit broken also. Expecting it to generate and delete Empty on the fly.

**Comment by Durman** [comment]
According documentation it is correct behavior. It can generate only one empty object at the present.

Actually I'm not aware of the usefulness of generation of multiple empties. Can you give an example?

**Comment by enzyme69** [comment]
Empty is like a transformation object but real and can be tweaked by user, and the usefulness usually when it is used as dummy for rigging. 

I imagine like if we like users to give input that is transform, we can use Empty:
- SV generate mesh
- mesh placed using empty

Animation Nodes has instancing ways that duplicates empty, but SV instancing does not work with Empty..
<img width="798" alt="Screen Shot 2020-07-22 at 6 29 10 pm" src="https://user-images.githubusercontent.com/3952687/88153817-445f5a00-cc49-11ea-9fcd-598120a64bbd.png">

**Comment by Durman** [comment]
Still does not see real example. It is possible to place meshes applying matrices in case if mesh is generated by Sverchok. If mesh is manually modeled or has came from other addon it can be placed with `instancer` node.

**Comment by zeffii** [comment]
it's not broken, we failed to find a good reason to allow the `Empty Node` to be able to make multiple empties. Indeed I don't think it has ever had that capability. I remember writing a script for SN(L) that would show people how to do that if they really needed it - but as @Durman suggests the instancer node is probably most suitable.
