### ISSUE TITLE
idxviewer Text mode bug, reading floats as text.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3417]
...I found another case that didn't work for me after the changes. Should I open new issue about that or just continue posting here?.. 

I'm trying here to plot some T values along the length of a curve. It was fine before, but now throws an error.

![t_values](https://user-images.githubusercontent.com/66558924/88330702-73062f00-cd34-11ea-89d6-4bd85d200472.jpg)

_Originally posted by @rendetto in https://github.com/nortikin/sverchok/issues/3412#issuecomment-663193242_

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/88337669-5c150c00-cd37-11ea-883d-4fd6dfad041c.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3418

should be OK now @rendetto

**Comment by rendetto** [comment]
Thanks a lot! 👍

**Comment by zeffii** [comment]
There are scenarios in which the text-viewing will still not work identical to the earlier implementation.. i will address those shortly.
