### ISSUE TITLE
Easing node is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3419]
<img width="592" alt="Screen Shot 2020-07-24 at 10 40 52 am" src="https://user-images.githubusercontent.com/3952687/88351597-3836e200-cd9a-11ea-8c1d-be94239b699b.png">

The output seems strange.

**Comment by enzyme69** [comment]
My bad. It was correct, I should have used "Count".

**Comment by zeffii** [comment]
why isn't the graph visible?
