### ISSUE TITLE
Solids and masks

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3421]
@vicdoval 

when doing a solid boolean, is there a way to output the boundary/boundaries of the intersection between the two solids? This would be handy information for performing fillet/chamfer over the boundary perimeter.

**Comment by vicdoval** [comment]
I don't think there is a staight method, but maybe  if you compare the edges from the Intersection bool from the edges of the Union bool you could find the right edges...

**Comment by zeffii** [comment]
in non-nested boolean mode, the boolean node could output the mask?  this is kind of outside of my wheelhouse, users will eventually want that kind of stuff.

**Comment by portnov** [comment]
FreeCAD's boolean methods do not provide information which edge came from where, and which edges were newly created by boolean operation.
There is `generalFuse` method, which is something like merge of all 3 boolean methods: it splits one object at places where it intersects with other, so you have some number of parts, and it says which part came from which object, so then you can somehow select which of them you need: only those which are parts of all input objects, or only those which are parts of only one of them, or whatever. It still does not say which edges did it create, unfortunately.

**Comment by zeffii** [comment]
ooh @portnov, have you seen this thead? bmesh booleans might happen.  https://blenderartists.org/t/new-boolean/1245336/101?u=zeffii

**Comment by portnov** [comment]
Well, waiting for bmesh api :)
However, it would not reduce the importance of solid booleans by much, because with full Solids support we can be integrated into "grown-ups" CAD workflow...

**Comment by zeffii** [comment]
> Well, waiting for bmesh api :)

haha . well..yes,  but this is movement at least. (obliviously optimistic)

> However, it would not reduce the importance of solid booleans by much

sure, they are really two different things.
