### ISSUE TITLE
NaN when Sine Osc -> Map Range 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3427]
## Problem statement

Sine Oscillator when plugged into Map Range with 'List Limits is giving a NaN

<img width="1077" alt="Screen Shot 2020-07-30 at 12 18 00 pm" src="https://user-images.githubusercontent.com/3952687/88872974-e17c4d00-d25e-11ea-9430-f426fbad67b2.png">

**Comment by zeffii** [comment]
fewer nodes
![image](https://user-images.githubusercontent.com/619340/88902277-49786680-d252-11ea-98f8-6305528b31f5.png)

how would `limits` be useful for single number inputs @enzyme69 .

**Comment by enzyme69** [comment]
Good point, I leave it there...

**Comment by enzyme69** [comment]
Hmm.... ok I am sure at some point it was a NaN even with multiple values.... I'll leave it there. thanks zef!
