### ISSUE TITLE
Native vs geomdl Curve

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3436]
@portnov
I'm not sure that this is an issue or was intended to work like that, but I found a case that works somewhat different for native curve implementation and the one used from geomdl. 
I tested how "nearest point" will react to the new "native" curve and what I found is that if the projected point gets closer to the ends of the curve the "nearest" node throws an error.

![Native_NURBS_Curve_Nearest_Point](https://user-images.githubusercontent.com/66558924/89274136-2e8a6580-d649-11ea-8688-12dbf3767eac.jpg)

You can test different X values for the yellow point and see how the 'nearest point' node reacts both for "native" and "geomdl" implementations.
The tests show that, when using "native" curve we need to raise the "init resolution" for getting rid of the error(however it works only in a certain extent)
When using the geomdl implementation, the error is not present at the beginning of the curve T = 0.0 (regardless the "init resolution"), and it's present only at the end if the projection of the yellow point passes T = 1.05 (which I find very practical). Passing over that T = 1.05 value the raise of "init resolution" cannot fix the error, but I'm not sure if that implies any practical problem.

**Comment by portnov** [comment]
Hmm. I can reproduce the problem with "Sverchok" implementation, but the thing is, it reproduces for me with "Geomdl" implementation too. Please check with "Geomdl" implementation one more time :)

**Comment by rendetto** [comment]
OK so.. 
using geomdl curve, "init resolution" from 3 up to 900, X value for the yellow point from -30000 up to 1.44 does not present any errors.
At X = 1.441 no matter what "init resolution" I'm using, the error is present.

Here's my file:

[Native_NURBS_Curve_NearestPoint.zip](https://github.com/nortikin/sverchok/files/5021436/Native_NURBS_Curve_NearestPoint.zip)

Could this be OS specific behavior?

**Comment by portnov** [comment]
> At X = 1.441 no matter what "init resolution" I'm using, the error is present.

Does this reproduce for you with "geomdl" implementation? Or "Sverchok" only?

**Comment by rendetto** [comment]
X = 1.441 is for geomdl only.

Using the sverchok version - the error is limited by X=-0.298 (T=0.0007) up to X=1.298 (T=0.999) at "init resolution" = 900 (I guess those values will differ for different init resolutions)

**Comment by portnov** [comment]
Well, it seems I can find situations when the situation is reproducible with "Sverchok" implementation, but not reproducible with "Geomdl". Though I can't figure out what is the root of the problem, yet.

Let's confirm that we both can reproduce the same problem. Please try the following:

* Open file [Native_NURBS_Curve_NearestPoint_2020_08_04_11_25.zip](https://github.com/nortikin/sverchok/files/5021795/Native_NURBS_Curve_NearestPoint_2020_08_04_11_25.zip)
* There implementation is set to "Geomdl". Does the problem reproduce?
* Change implementation to "Sverchok" (no other changes). Does the problem reproduce?

**Comment by rendetto** [comment]
In file https://github.com/nortikin/sverchok/files/5021795/Native_NURBS_Curve_NearestPoint_2020_08_04_11_25.zip:
after https://github.com/nortikin/sverchok/commit/454cd66e224b241f2de2175d0222c8743fa81aa3 using geomdl option we can go above X=2000(T=10.5 wow!) no matter the init resolution. So geomdl behaves great.

Changing implementation to "Sverchok" (no other changes) - the problem persists.

Before I got your file and using https://github.com/nortikin/sverchok/commit/454cd66e224b241f2de2175d0222c8743fa81aa3, I tested "init resolution" of 10000 im my file, and got very practical limits from T=0.0000731 to 1.0, but for some reason I cannot reproduce this anymore, and the limits become even worse.

**Comment by portnov** [comment]
@rendetto I've pushed a change that fixes the problem for me. Please check.

**Comment by portnov** [comment]
Whoops...

**Comment by portnov** [comment]
@rendetto I've pushed a change that fixes the problem for me. Please check.

**Comment by rendetto** [comment]
Verified! The error is gone both for geomdl and sverchok implementations.
Thanks a lot! 

P.S. Can I address some issues I have with the curvature calculatons, near the ends of curves an surfaces, or you are aware of those? It's not directly connected to this issue but looks similar.

**Comment by portnov** [comment]
Please create separate issues for those problems.

**Comment by rendetto** [comment]
Sure, thanks!

**Comment by rendetto** [comment]
...Well it appears that I cannot replicate those problems anymore, so don't bother.
