### ISSUE TITLE
Faces Weights

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3444]
From a question in BlenderArtist https://blenderartists.org/t/wip-sverchok-parametric-nodes-for-architects/557250/2433l
How to align Vertex Weight with Face Extrusión?

The problem is that the Weight is a value per Vertex and the extrusion is set per Face.

Solution: Determine the average Weight of each face and use that value as the extrusion height

 ![image](https://user-images.githubusercontent.com/10011941/89535423-b792cf80-d7f6-11ea-8a4b-27293a821343.png)

Script for Scripted Node Lite:
```
"""
in   faces_in  s   
in   weights_in  s   

out  facesweights   s
"""

for faces, weights in zip(faces_in, weights_in):
    
    fs_w = []
    
    for f in faces:
        fw = sum([weights[c] for c in f])/len(f)
        fs_w.append(fw)
    
    facesweights.append(fs_w)
```

**Comment by nortikin** [comment]
vertex group from object in node have to be rewriten for weights and groups. Each group could make new socket
