### ISSUE TITLE
Set the selected item of the Custom Switcher 

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#3452]
Is there a way to set programmatically (in my case, i want to randomize it on frame change) the selected item in the Custom Switcher ?

**Comment by Durman** [comment]
It definitely not for what the node was designed. 
Probably you will be satisfied with next solution:
![2020-08-11_20-12-54](https://user-images.githubusercontent.com/28003269/89921797-34ff7b00-dc0f-11ea-801e-5517c1d5d85c.png)

**Comment by zeffii** [comment]
@mlevet  one solution is to randomize the input list using `list shuffle` and a `list item` picking item index=0,   the list shuffle is the node you would update upon frame change, by changing the seed.

![image](https://user-images.githubusercontent.com/619340/89932502-0634d500-dc0e-11ea-919a-27613f79c5ae.png)

**Comment by mlevet** [comment]
Thank you very much, that would work indeed but still not totally what I need.
I will try to explain what i need to accomplish and why I first thought about the custom switcher.
I want to generate some table furnitures with various properties : one property for example would be the type, ie : is it a big table (option 1) or a small table (option 2). I want this property to be properly displayed and manually switchable, just like with the custom switcher but also randomized on frame change and then updated on the switcher as well.
For this, I tried a scripted node with enum as switcher and a randomized seed input.

def my_function(seed):
    self.custom_enum='small' if seed==0 else 'big'
    return self.custom_enum

p = my_function(seed)
test.extend([p])

Problem is the enum is constantly updated by the seed, even when the animation is not playing, thus making the enum impossible to click/change manually.

**Comment by zeffii** [comment]
i'm not sure i understand.
1. you want random
2. you want to be able to override the random, if random wasn't what you wanted 

?

**Comment by mlevet** [comment]
Exactly!
thank you for making it less circumvoluting

**Comment by Durman** [comment]
What you are trying to do is not possible and I'm not sure that it good UI where settings are jumping randomly. 

What I can suggest is to add `random` property which would override manual settings. Like this:
![2020-08-12_08-39-36](https://user-images.githubusercontent.com/28003269/89975697-7297ee80-dc77-11ea-95ab-d2170074f536.png)
[untitled8.zip](https://github.com/nortikin/sverchok/files/5060651/untitled8.zip)

**Comment by mlevet** [comment]
Thank you so much, i will implement this solution !
