### ISSUE TITLE
Dissolve Mesh Element Topology Patterns Question

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3454]
I am wondering if "Dissolve Mesh Element" node can give resulting pattern that is similar to how Particles and Explode Modifiers does it to mesh:

[particle_explode_001.blend.zip](https://github.com/nortikin/sverchok/files/5059984/particle_explode_001.blend.zip)
<img width="866" alt="Screen Shot 2020-08-12 at 9 57 16 am" src="https://user-images.githubusercontent.com/3952687/89960405-4897f980-dc82-11ea-8741-646aa18da1e9.png">

When triangulated
<img width="1059" alt="Screen Shot 2020-08-12 at 10 03 31 am" src="https://user-images.githubusercontent.com/3952687/89960706-15a23580-dc83-11ea-900e-bb9488a5c67c.png">

I tried Dissolve Mesh Element node with random numbers to mask vertices and edges:

<img width="996" alt="Screen Shot 2020-08-12 at 10 00 16 am" src="https://user-images.githubusercontent.com/3952687/89960530-a1679200-dc82-11ea-863f-987b029b95b7.png">

Masking Edges give me brick like result. Masking vertices one is interesting, but it introduces this tiny little polygon square. 

I want to have topology that's more like pieces of clothes.

**Comment by enzyme69** [comment]
Wonder why this one still giving small areas:

<img width="1080" alt="Screen Shot 2020-08-12 at 10 23 59 am" src="https://user-images.githubusercontent.com/3952687/89961727-f9ec5e80-dc85-11ea-816c-dd1bce72f672.png">

[dissolve_mesh_007.blend.zip](https://github.com/nortikin/sverchok/files/5060024/dissolve_mesh_007.blend.zip)

I wonder if we could break pieces according to noise hard edge...

**Comment by Durman** [comment]
> I wonder if we could break pieces according to noise hard edge...

I also noticed some inconsistency. For now I only can say that it is how the blender algorithm is working.

Example of dissolving edges based on noise:
![dissolve noise](https://user-images.githubusercontent.com/28003269/89974798-1764fc80-dc75-11ea-9ea3-3faee1e444e5.gif)
![2020-08-12_08-21-01](https://user-images.githubusercontent.com/28003269/89974801-1b911a00-dc75-11ea-9af6-226119d4cf6b.png)
[untitled7.zip](https://github.com/nortikin/sverchok/files/5060590/untitled7.zip)

**Comment by enzyme69** [comment]
Thanks Durman! I'll play around with it a bit more, Maybe I can "flip or invert" selection of big areas, and select small ones, and just merge closer one.

It's pretty cool node!!
