### ISSUE TITLE
Matrix Normal or another way to convert direction to rotation?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3459]
I am attempting to animate pose bones wiggle using SVerchok, but this time I want to have proper control of the rotation of each bone, which is transferred from Wiggle Bones.

So far I did have something, but having issue with understanding "Matrix Normal" or to have rotation of bones that follow the "path" of the Wiggle Bones, but not flipping. I am not using Blender's Curve Path Armature Constraint here, maybe I should have 🤔 

But is there another way to have "direction to rotation" that is not flipping?

<img width="598" alt="Screen Shot 2020-08-13 at 10 59 02 am" src="https://user-images.githubusercontent.com/3952687/90082805-1787f980-dd54-11ea-9fd2-fcd549660a9f.png">

[Screen Recording 2020-08-13 at 10.58.03 am.mov.zip](https://github.com/nortikin/sverchok/files/5066607/Screen.Recording.2020-08-13.at.10.58.03.am.mov.zip)

<img width="1158" alt="Screen Shot 2020-08-13 at 10 59 12 am" src="https://user-images.githubusercontent.com/3952687/90082792-10f98200-dd54-11ea-8a93-201555093311.png">

[wiggle_bone_007.blend.zip](https://github.com/nortikin/sverchok/files/5066606/wiggle_bone_007.blend.zip)

**Comment by Durman** [comment]
The node you need is calling `Curve zero twist frame`.
[wiggle_bone_007.zip](https://github.com/nortikin/sverchok/files/5067109/wiggle_bone_007.zip)
![2020-08-13_08-27-31](https://user-images.githubusercontent.com/28003269/90094389-db966980-dd3e-11ea-9ddd-ed0f771effea.png)

**Comment by enzyme69** [comment]
Thanks Durman, you're the man!!!

**Comment by enzyme69** [comment]
Although the pose bone become like crazy not sure why....

**Comment by enzyme69** [comment]
Will need to revisit again in the future...
[Screen Recording 2020-08-14 at 1.06.14 am.mov.zip](https://github.com/nortikin/sverchok/files/5069823/Screen.Recording.2020-08-14.at.1.06.14.am.mov.zip)
