### ISSUE TITLE
Origin node on separate edges (using Split Curve) not really giving the center point

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3462]
I am testing a split curve node on Cicle, so I should get split curves, I need to get the center of each curve, using Origin node, but not getting what I want:

<img width="951" alt="Screen Shot 2020-08-14 at 10 55 53 am" src="https://user-images.githubusercontent.com/3952687/90200997-e32c4000-de1c-11ea-95a1-dad88ed40e76.png">

[split_curve_002.blend.zip](https://github.com/nortikin/sverchok/files/5072160/split_curve_002.blend.zip)

**Comment by Durman** [comment]
`Origins` node can find centers of edges not of curves. It is possible with `evaluate curve` node and simple formula.
![2020-08-14_08-09-52](https://user-images.githubusercontent.com/28003269/90212927-95f0a400-de05-11ea-92d3-8a97d0094ff7.png)
[split_curve_002.zip](https://github.com/nortikin/sverchok/files/5072602/split_curve_002.zip)

**Comment by enzyme69** [comment]
<img width="1025" alt="Screen Shot 2020-08-14 at 2 18 11 pm" src="https://user-images.githubusercontent.com/3952687/90213381-01a03480-de39-11ea-8f56-45273142724a.png">

Cheers Durman, I end up using Vector Interpolation and 0.5 value to get the "center" of every split curve.
