### ISSUE TITLE
Node defaults module

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3487]
Is this module used somewhere in Sverchok? I did not find any files in `sverchok datafiles` directory with default settings for nodes.

https://github.com/nortikin/sverchok/blob/59354d366a3a51f6d39a25d7b5135924598a95f2/core/node_defaults.py#L27

#1650
#3483

**Comment by portnov** [comment]
As far as I remember, it should be reading some user-defined configs... See https://github.com/nortikin/sverchok/wiki/Custom-Defaults
Probably it would be better to replace the whole thing with Presets functionality - somehow mark one of per-node presets as 'default'...

**Comment by zeffii** [comment]
node defaults should still be operational.  please leave it alone.

**Comment by Durman** [comment]
Less code less bugs and less efforts for other developers to maintain the code. I as developer did not know about this feature so hardly any Sverchok user has used it.

Also as I see it redundant functionality. We have node presets now which has the same functionality. It has UI so it is more user friendly.

I think this two reason more than enough to clean the code. If there are any reasons don't do this please name them.

**Comment by portnov** [comment]
It seems Zeffii uses them, that's the reason :)
As an option, we could write a script that automatically converts those defaults to presets.
(and still, currently we do not have an option to use one of presets by default, at node creation).

**Comment by zeffii** [comment]
> Less code less bugs 

i agree.  this was the most minimal node defaults code i could come up with at the time. this was long before presets, and this code only gets triggered if there are node defaults found for that node. 

we have bigger problems than that little bit of code :)

**Comment by zeffii** [comment]
> If there are any reasons don't do this please name them.

@Durman  Who appointed you the arbitrator of what is deemed OK to remove?

The node defaults feature as i implemented it offers 
- a way to set the default on any number of properties of a node (even those not exposed to users from the ui)
- also it offer a "post load function call hook", which can call a user defined function on the node after it's creation.

The pull request that introduced the feature shows an example of both use-cases. i can document stuff, but i cant force people to read it. https://github.com/nortikin/sverchok/wiki/Custom-Defaults

**Comment by zeffii** [comment]
it might have been a very long time since i used this feature, it does not appear to be working as expected anymore.

i'll look into this later .

**Comment by zeffii** [comment]
nm, it works fine.

![image](https://user-images.githubusercontent.com/619340/91434393-09ae9a00-e865-11ea-8e60-1dc135a3e10a.png)

### node_defaults.json

```json
{

    "SvGenNumberRange": {
        "props": [
            ["stop_float", 1.0],
            ["count_", 20],
            ["range_mode", "RANGE_COUNT"]
        ]
    },

    "SvVDExperimental": {
        "props": [], 
        "function": "view3d.init_vdmk3"
    }

}


```

### and view3d.py

```python
import random
import colorsys

import bpy


def init_vdmk3(node):

    def fold_color(color, shift):
        h, s, v = colorsys.rgb_to_hsv(*color)
        return list(colorsys.hsv_to_rgb(shift, s, v))

    A = [0.938000, 0.948000, 0.900000, 1.000000]
    B = [0.500000, 0.752000, 0.899000, 1.000000]
    C = [0.030100, 0.488000, 0.899000, 1.000000]

    shift = random.random()
    node.vertex_color = fold_color(A[:3], shift) + [1.0]
    node.edge_color = fold_color(B[:3], shift) + [1.0]
    node.face_color = fold_color(C[:3], shift) + [1.0]

    node.line_width = 1.0
    node.point_size = 2.0
```

and here is where the user sets the path.

![image](https://user-images.githubusercontent.com/619340/91434592-54301680-e865-11ea-83d0-dece782d4f78.png)

**Comment by zeffii** [comment]
i'm glad you dug this up @Durman  , i've missed this feature. i'll update the docs with examples.

**Comment by portnov** [comment]
Functions called from jsons... well... :)
addons for an addon? :)

**Comment by Durman** [comment]
> i'm glad you dug this up @Durman , i've missed this feature. i'll update the docs with examples.

I feel like I was should to remove this module silently. After 3 years of no using hardly anybody would noticed its disappearing.

And from my point of view the only user of this feature will only you (since I `dug this up`) @zeffii 

If so I denied to maintain this code. I mean if I will be going to add some feature nearby this code I won't keep this module in mind. And if something will be broken to put efforts to repair will be your own responsibility. Probably you would agree that this is fair.

**Comment by zeffii** [comment]
dude sure.  all this does is a single call at the end of sv_init, to apply properties. it was @DolphinDream who asked for this kind of feature.

**Comment by Durman** [comment]
Probably he did not know that Svercho will get `Node presets` soon.

**Comment by zeffii** [comment]
if you break it, i can always make it work if i need it.

**Comment by zeffii** [comment]
it's ok. kill it.   i'll modify vdmk3 :)
