### ISSUE TITLE
Reparametrize Curve node does not work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3494]
<img width="977" alt="Screen Shot 2020-08-30 at 2 40 09 pm" src="https://user-images.githubusercontent.com/3952687/91651326-c9525480-eace-11ea-885b-35701c80573f.png">

[zuggamasta_curvesphere_003_error.blend.zip](https://github.com/nortikin/sverchok/files/5146350/zuggamasta_curvesphere_003_error.blend.zip)

Logically TMin and TMax are values to trim the curve?

**Comment by portnov** [comment]
"Reparametrize curve" returns the same curve, but with another parametrization: https://github.com/nortikin/sverchok/blob/master/docs/nodes/curve/reparametrize.rst
If you want to cut a part of curve, you need "Curve Segment" https://github.com/nortikin/sverchok/blob/master/docs/nodes/curve/curve_segment.rst

**Comment by enzyme69** [comment]
Gotcha, ok roger that, now I understand. Maybe Trim Curve is a better name?
