### ISSUE TITLE
Curve With Rounded Start and End Without Twist

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3498]
<img width="1126" alt="Screen Shot 2020-08-31 at 1 03 22 pm" src="https://user-images.githubusercontent.com/3952687/91679026-7211ba00-eb8a-11ea-9a3a-5604305e9f20.png">

[sphere_line_002.blend.zip](https://github.com/nortikin/sverchok/files/5148128/sphere_line_002.blend.zip)

I've been trying to use SV nodes, to make a nice curve without twisting, as close as possible to Blender's own Curve + Bevel, but so far I am not getting the perfect result.

- Twisting still happens
- Rounded bevel does not seem possible?

**Comment by enzyme69** [comment]
I want to bevel just the start and end edge, how to do this?

<img width="619" alt="Screen Shot 2020-08-31 at 1 07 05 pm" src="https://user-images.githubusercontent.com/3952687/91679159-dfbde600-eb8a-11ea-9f4f-38cb3eee47d5.png">

**Comment by enzyme69** [comment]
<img width="785" alt="Screen Shot 2020-08-31 at 1 14 07 pm" src="https://user-images.githubusercontent.com/3952687/91679529-e6009200-eb8b-11ea-9ad6-e8353042dee7.png">

Ultimately just a simple half sphere at the end like this:
https://blender.community/c/rightclickselect/fwgbbc/

**Comment by enzyme69** [comment]
My solution so far:

<img width="1159" alt="Screen Shot 2020-08-31 at 1 21 51 pm" src="https://user-images.githubusercontent.com/3952687/91679931-fb29f080-eb8c-11ea-903f-bd8a228672ce.png">

[sphere_line_005.blend.zip](https://github.com/nortikin/sverchok/files/5148165/sphere_line_005.blend.zip)


* not sure how to get sphere to align perfectly with the circle bevel
* getting half sphere from full sphere is still kind of pain

**Comment by Durman** [comment]
![2020-08-31_07-22-10](https://user-images.githubusercontent.com/28003269/91679973-d74db700-eb5a-11ea-9dd6-2afd3b5a7964.png)
[untitled8.zip](https://github.com/nortikin/sverchok/files/5148167/untitled8.zip)

**Comment by enzyme69** [comment]
Thanks Durman, your solution might be it, I will test. There are few nodes I rarely used there! I'll close for now.

In the past, Blender's way is to use array, with head and tail, and curve deform. I feel that maybe Rounded Box node can be used somewhat with curve deform.

**Comment by enzyme69** [comment]
This method however failed when radius increased and bevel cannot handle it, unless perhaps the start and end cap is extruded once.

I could now find the easiest way to simply:
- extrude cap along normal
- scale cap
- loop cut the new extruded area <-- this
- smooth

**Comment by enzyme69** [comment]
<img width="1008" alt="Screen Shot 2020-09-06 at 1 14 01 am" src="https://user-images.githubusercontent.com/3952687/92308055-4190ac80-efde-11ea-9f8d-2a9d0c8c2961.png">

Like this, SV nodes should be able to do this right?

**Comment by Durman** [comment]
![2020-09-05_20-42-19](https://user-images.githubusercontent.com/28003269/92309644-5eb28480-efb8-11ea-97bc-1e0d924cf022.png)
