### ISSUE TITLE
Surface From Four Curves node: sometimes a glitch

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3503]
[surface_four_curves_003.blend.zip](https://github.com/nortikin/sverchok/files/5153351/surface_four_curves_003.blend.zip)
<img width="777" alt="Screen Shot 2020-09-01 at 11 02 32 am" src="https://user-images.githubusercontent.com/3952687/91783196-bcef0880-ec42-11ea-8987-085a987811ab.png">

I am testing this node, and from the premise, it's simple enough to use but I just encounter this weirdness.

Why is the surface failed to generate? Is it because of the curve direction? All needs to follow the same direction?

**Comment by enzyme69** [comment]
Is this the solution? 
<img width="955" alt="Screen Shot 2020-09-01 at 11 16 41 am" src="https://user-images.githubusercontent.com/3952687/91783818-a3e75700-ec44-11ea-84f2-fa9c45cd12d9.png">

**Comment by enzyme69** [comment]
Also @portnov how to get "grid" same spacing with Bezier In -> Surface From Four

Can we have Surface From Three Curves or Birail etc?

**Comment by portnov** [comment]
> Can we have Surface From Three Curves or Birail etc?

Such nodes probably will appear later, but no ETA.
