### ISSUE TITLE
Surface From Four "Polygon Edge": Questions

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3504]
Why is it that sometimes I am not getting Surface that is closer to original Polygon Edge:

<img width="1154" alt="Screen Shot 2020-09-01 at 11 32 57 am" src="https://user-images.githubusercontent.com/3952687/91784760-07728400-ec47-11ea-9279-afe54ea59cfb.png">

[four_curves_006.blend.zip](https://github.com/nortikin/sverchok/files/5153417/four_curves_006.blend.zip)

I am expecting the surface to "touch" every edge.

Also, why is it triangulated mesh Surface instead of beautiful grid surface?

**Comment by portnov** [comment]
Curves must form an *exact* loop in order for this node to work properly. In your case, there is a hole in it:
![settings1](https://user-images.githubusercontent.com/284644/91811831-8ff22400-ec49-11ea-9a36-7889478f3e10.png)
You can check "Check coincidence" parameter, then the node will check that there are no such holes, and write errors to console.

"Adaptive tessellate" node always generates triangulated mesh, see documentation: https://github.com/nortikin/sverchok/blob/master/docs/nodes/surface/adaptive_tessellate.rst
If you want a rectangular grid, use "evaluate mesh" instead.

**Comment by enzyme69** [comment]
Thanks so much Portnov!! This could potentially be handy to generate cloth or wrapping topology.

**Comment by enzyme69** [comment]
Even with closed loop, weird thing is however with the resulting surface of the back jacket, which is not matching exactly:

<img width="629" alt="Screen Shot 2020-09-02 at 11 10 10 am" src="https://user-images.githubusercontent.com/3952687/91920580-df4d5880-ed0c-11ea-8321-e6e89d1d6a0e.png">


Originally I use it to generate the front part:

<img width="1182" alt="Screen Shot 2020-09-02 at 11 13 02 am" src="https://user-images.githubusercontent.com/3952687/91920739-45d27680-ed0d-11ea-8872-4443093db563.png">


[four_curves_008.blend.zip](https://github.com/nortikin/sverchok/files/5159494/four_curves_008.blend.zip)


My feeling is the algorithm used to see the loop is backward and causing it to fail in making the shape for arm?

**Comment by portnov** [comment]
Also make sure that the loop goes always in one direction: the end of first curve should coincide with the beginning of the second, and so on. You can check this with "Evaluate Curve" + "Index Viewer".

**Comment by enzyme69** [comment]
<img width="851" alt="Screen Shot 2020-09-02 at 2 58 08 pm" src="https://user-images.githubusercontent.com/3952687/91933621-b76ded00-ed2c-11ea-8bcd-826fe93d27ee.png">
 
Great tips! Flip Curve works also thanks Portnov-san~
