### ISSUE TITLE
NURBS support in Blender is to be reborn!?...

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3506]
There is a rebase of old GSoC-2014 NURBS branch to current Blender master; it is (at least sometimes) working. It is waiting for review and testing. There are some non-zero chances that it will be merged in a foreseeable future. There is no full-fledged Python API yet, but they say "it will follow".

https://devtalk.blender.org/t/branch-soc-2014-nurbs-update-to-master-code-base-d6807/11681/38

**Comment by zeffii** [comment]
wow. that's 6 years ago already? wtf.

**Comment by rendetto** [comment]
I think NURBS in SV have bigger potential and are far more flexible.
