### ISSUE TITLE
The new Mesh viewer does not include "Show Edges" anymore

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3509]
Please can we have this back?

Thanks

**Comment by Durman** [comment]
It still has got it.
![2020-09-02_21-09-56](https://user-images.githubusercontent.com/28003269/92014702-b5258600-ed60-11ea-9af0-808e5b08e67d.png)

**Comment by rendetto** [comment]
My bad! I'm blind :D
Thanks

**Comment by Durman** [comment]
Welcome

**Comment by zeffii** [comment]
maybe we should stick color + visibility of ViewerDraw on the socket draw layout too.

**Comment by Durman** [comment]
It would make the node more compact I guess.
