### ISSUE TITLE
Nurbs lofting questions

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3510]
Well, I get few errors with Nurbs when it comes to form an arc or any simple form. The lofting doesn't work well with it. It intersects with faces. All transforms applied.

However it works perfect with Bezier. And the transforms don't have to be applied - it just works.
![Zrzut ekranu 2020-09-3 o 09 03 07](https://user-images.githubusercontent.com/45789626/92084945-67446880-edc8-11ea-9abc-c2982b8593ba.jpg)
![Zrzut ekranu 2020-09-3 o 09 24 37](https://user-images.githubusercontent.com/45789626/92084955-6d3a4980-edc8-11ea-8775-7b6c48ee1746.jpg)

_Originally posted by @DaveSledz in https://github.com/nortikin/sverchok/issues/2644#issuecomment-686311795_

**Comment by portnov** [comment]
@DaveSledz let's continue here. Could you please attach a blend.zip file with an issue.

**Comment by DaveSledz** [comment]
Sure. Here's my blend with Nurbs:
[SV_test_02.blend.zip](https://github.com/nortikin/sverchok/files/5167137/SV_test_02.blend.zip)

**Comment by portnov** [comment]
I see. There is an issue when operating with closed (cyclic) nurbs curves. Will fix.

**Comment by portnov** [comment]
Seems to be fixed in master. Please check.

**Comment by DaveSledz** [comment]
Just checked and it works perfectly. Thanks
