### ISSUE TITLE
Problem of creating new node version if socket name was changed

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3514]
The problem is that some minor changes in node code force us to create its new version. It's totally related with sockets. It is possible to fix node property without problems meanwhile one can't say this about sockets. There is hint of a solution in animation nodes. 

This articles describes the problem: https://wiki.blender.org/wiki/Source/Nodes/NodeInterfaceFramework#Existing_Approaches

One of possible approaches is re initialize node on each tree update event as article describes. And we already have one node which share similar conception. It's SNL node.

https://github.com/nortikin/sverchok/blob/979172d84807af9cb37a48621589a8f90c2ac2a4/nodes/generator/script1_lite.py#L328-L334

This method is calling each time when `process` method of the node is called and it updates sockets state. It is why my last changes in initialization sockets code does not required creating new version of the node. 

We could think whether it is possible to bring this logic to the reast of the nodes.

**Comment by zeffii** [comment]
> This method is calling each time when process method of the node is called and it updates sockets state

just to be a bit more exact in language:  the `make_new_locals` function only makes changes to the node if it must, but it wil always inject locals to be available for the `execution script` (the thing that snlite loads from TextEditor)

**Comment by Durman** [comment]
As far as I understand it calls `update sockets` each time when new file is opened. It's enough for renaming sockets for example without necessity of creating new version of a node.

**Comment by zeffii** [comment]
yes, but the point is that new sockets are not created every time process is called.

**Comment by zeffii** [comment]
there are a limited set of scenarios where snilte updates sockets 
- opening the blend, 
- python reload f8, or 
- node script update from TextEditor
- (maybe) copying node

all other times process is called, without invoking "update_sockets".      i think :)

**Comment by Durman** [comment]
Probably it's enough for renaming socket without breaking capability with old files.

**Comment by Durman** [comment]
The main problem I see is renaming sockets. Since a socket is renamed it is loosing its relationships with its old versions.

First what comes to mind is to create attribute like `sv_identifier` but in this case `sv_initi` methodes of all nodes should be rewrite and in old files sockets won't be able to have this attribute. 

So another solution can be create special attribute for names and use socket names as identifiers instead. The attribute can have name like `draw_name`. In this case sockets of old files can be renamed just assigning new value to `draw_name` attributes.

**Comment by Durman** [comment]
It is impossible just call `sv_init` method again because it will reset sockets into default condition. One of solution can be extract information from the method and according this information make decisions how to update sockets properly. It would be possible to create special object for this task which should be replaced with real node in th method. Something like this:

```Python
class NodeReader:

    def __init__(self):
        self.inputs = SocketReader()


class SocketReader:
    def __init__(self):
        self.socket_data = []

    def new(self, socket_type, socket_name):
        self.socket_data.append(socket_typem coket_name)


class BaseNode:
    def update(self):
        if sverchok is reloaded:
            NodeClass = type(self)
            node_reader = NodeReader()

            NodeClass.sv_init(node_reader)
            node_reader.reinit_node()
```
