### ISSUE TITLE
FreeCAD's booleans performance investigation

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3519]
https://twitter.com/FreeCADNews/status/1302641737895206915

> I have to say, FreeCAD's booleans are far from being realtime. In the last example, they take about 12 seconds to calculate.

> please post to our forum. lets see what the devs can do about it.

**Comment by portnov** [comment]
I've found at least one problem in Sverchok itself: when doing booleans with multiple objects, we ware calling `cut` / `fuse` / `common` many times, instead of calling them once with a list of objects. When I fixed that, I got about 2x improvement on that scene. @vicdoval FYI.

However, I still can't figure out what it is doing for several seconds there (5.6 seconds for cutting 18 holes).
For a reference, the following script makes ~20-50 holes in 3.7 seconds:
```python

#FREECAD_PATH = '/usr/lib/freecad/lib'

import sys
import random
from math import sin, cos, pi

from sverchok.utils.profile import profile, profiling_enabled, dump_stats, reset_stats

#sys.path.append(FREECAD_PATH)

import FreeCAD
import Part
from FreeCAD import Base

SIZE = 10
RADIUS = 1
HEIGHT = 3

def make_hexagon(origin, radius, height):
    pts = []
    N = 6
    for i in range(N):
        alpha = i * 2*pi / N
        dx = radius * cos(alpha)
        dy = radius * sin(alpha)
        dv = Base.Vector(dx, dy, 0)
        pt = origin + dv
        pts.append(pt)
    pts.append(pts[0])
    wire = Part.makePolygon(pts)
    face = Part.Face(wire)
    shape = face.extrude(Base.Vector(0, 0, height))
    return shape

def make_small(origin, radius, height):
    hexa = make_hexagon(origin, radius, height)
    dv = Base.Vector(0, 0, -height)
    cylinder = Part.makeCylinder(radius * 0.6, height * 2, origin + dv)
    return hexa.fuse(cylinder)

def make_base(radius1, radius2):
    pts = []
    N = 6
    origin = Base.Vector(radius1, 0, 0)
    for i in range(N):
        alpha = i * 2*pi / N
        dx = radius2 * cos(alpha)
        dy = radius2 * sin(alpha)
        dv = Base.Vector(dx, 0, dy)
        pt = origin + dv
        pts.append(pt)
    pts.append(pts[0])
    wire = Part.makePolygon(pts)
    face = Part.Face(wire)
    shape = face.revolve(Base.Vector(0, 0, 0), Base.Vector(0, 0, 1), 360)
    return shape

@profile
def main():
    #shape = make_hexagon(Base.Vector(0,0,0), SIZE, SIZE)
    shape = make_base(8, 4)

    smalls = []
    for i in range(50):
        x = random.uniform(-SIZE, SIZE)
        y = random.uniform(-SIZE, SIZE)
        z = random.uniform(-4, 3)
        small = make_small(Base.Vector(x,y,z), RADIUS, HEIGHT)
        smalls.append(small)

    shape = shape.cut(smalls)

    shape = shape.cut(smalls)
    print(shape)
    shape.exportBrep("out.brp")

if __name__ == '__main__':
    with profiling_enabled():
        main()
        dump_stats('cumtime')
        reset_stats()
```
(to be run from blender).

**Comment by portnov** [comment]
Aha. The script above becomes much slower if I replace polygons with Nurbs, by replacing `make_hexagon` with
```python
def make_hexagon(origin, radius, height):
    pts = []
    N = 6
    for i in range(N):
        alpha = i * 2*pi / N
        dx = radius * cos(alpha)
        dy = radius * sin(alpha)
        dv = Base.Vector(dx, dy, 0)
        pt = origin + dv
        pts.append(pt)
    pts.append(pts[0])
    wire = Part.makePolygon(pts)
    edges_nurbs = [e.toNurbs() for e in wire.Edges]
    wire_nurbs = Part.Wire(edges_nurbs)
    face = Part.Face(wire_nurbs)
    shape = face.extrude(Base.Vector(0, 0, height))
    return shape
```

**Comment by portnov** [comment]
Posted to freecad forum: https://forum.freecadweb.org/viewtopic.php?f=10&t=50080

**Comment by portnov** [comment]
> We're aware that boolean operations are 'expensive'.

> ... I get roughly a 1.8 speed factor between Nurbs and Polygon.
That doesn't look that big to me.
And I have no clue what can be done to lower that speed gap.

So, the advise is: do not use Nurbs when you do not require it. From Sverchok code perspective, I already started this movement - at least, for lines and circles I pass corresponding FreeCAD objects to FreeCAD API instead of NURBS (#3537). Later some other types of curves may be supported.

From user's perspective, if you see that FreeCAD's boolean operations in your node tree take too much time, you can inspect your tree with Stethoscope and see if you have Nurbs objects somewhere where you could've use simpler objects. If you see that somewhere Sverchok generates Nurbs objects where it could've generate simpler FreeCAD objects (lines, circles, planes, ...) — write here. Will see what we can do.

**Comment by vicdoval** [comment]
I have notice that the nurbs conversion happening in the Solid Faces node slows a lot (like 10 times) the Solid Distance node (Calculating Face to vertex) and also slows a Solid Face constrain i'm preparing for the new modular Pulga Physics.
Probably also affects performance turning the Solid Edges to Nurbs but I have not tested it.
Would you mind leaving it as an option? Or if you prefer I can change it when i'm done with #3525

**Comment by portnov** [comment]
I suggest to make it an option, hidden in the N panel, off by default. Most nodes that require Nurbs convert surfaces into Nurbs theirselves automatically.

**Comment by portnov** [comment]
@vicdoval 
Do you already have some drafts of functionality discussed above? If no, I think i'll implement it...

**Comment by vicdoval** [comment]
I dont have any, I'm still trapped in the #3525

**Comment by portnov** [comment]
ok. #3598.
