### ISSUE TITLE
BSpline Surface does not work

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3536]
I got an error when tried to generate a BSpline surface:
![BSpline_Surface_Issue](https://user-images.githubusercontent.com/66558924/93016231-4f3ec700-f5c8-11ea-82b0-79e3e698d1b8.jpg)

ERROR:sverchok.core.update_system:Node Build NURBS Surface had exception: 'NoneType' object is not iterable

The error persists through all implementations.

Thanks

**Comment by portnov** [comment]
Should be fixed now. Pls check.

**Comment by rendetto** [comment]
Yes it works now. Thank you!
