### ISSUE TITLE
Object In with post modifiers causes issue in console - object has no attribute 'objects'

### ISSUE THREAD

**Issue by Draise14** [nortikin/sverchok#3539]
## Issue
![bforartists_JcrUg1Vf9P](https://user-images.githubusercontent.com/35357409/93040602-04e13880-f610-11ea-8e07-b0dcbf1dc9c7.png)

When trying to get an object with post modifiers (to consider the modifier stack), it causes an issue and pulls this error. It can't pull an object with modifiers to process. 

## Steps to reproduce

![image](https://user-images.githubusercontent.com/35357409/93040591-00b51b00-f610-11ea-9bff-92acd43b1ec8.png)

1. Create a cube, add Bevel Modifier
2. Get a Object In or Object ID out with the Object ID selector, and turn on Post Modifiers. 
3. See the error in console

## Expected result

I'd expect that once you  turn on Post Modifiers, you'd be able to see and get the data of a mesh that has the modifier stack applied. 

## Actual result

I can only get objects without the modifier stack. 

## Sverchok version

0.6.0.0 Master - 13 September 2020

**Comment by zeffii** [comment]
i won't have time to fix this : /  looks like a wrapping issue.

**Comment by Draise14** [comment]
A wrapping issue? Maybe I could fix it if it's a simple fix. 

I think this is pretty necessary to get remeshing and more from the blender modifier stack back into Sverchok.

**Comment by Durman** [comment]
In my case it works but only with second attempt. First enabling of button raise the error.

**Comment by zeffii** [comment]
the usage of "global" bothers me here..

https://github.com/nortikin/sverchok/blob/90e84a2674498cc0148a2ed1d28c19e48dc02ab5/core/handlers.py#L22-L33

**Comment by vicdoval** [comment]
Should be fixed now, please report back if the bug persist

**Comment by Draise14** [comment]
Wow! You just earned huge respect, was not expecting a bug fix so quickly! Now testing.

**Comment by Draise14** [comment]
Fixed, it works fine now. Thank you!
