### ISSUE TITLE
JSON serialization (creating new or refactoring existing implementation)

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3542]
Will see if it is possible to make it in more OOP way.

```Python
class A:
    def __init__(self, v):
        self.v = v
    def to_json(self):
        return {type(self).__name__: {'v': self.v, }}

def json_encoder(o):
    try:
        return o.to_json()
    except AttributeError:
        raise TypeError
```

```Python
json.dumps([1,2,3,A(1)], default=json_encoder)
'[1, 2, 3, {"A": {"v": 1}}]'
```

**Comment by Durman** [comment]
And with decoding

```Python
import json


class A:
    def __init__(self, v):
        self.v = v

    def to_json(self):
        return {'type': type(self).__name__, 'v': self.v}

    @classmethod
    def from_json(cls, obj):
        return cls(obj['v'])

    def __repr__(self):
        return f"A={self.v}"


def json_encoder(obj):
    try:
        return obj.to_json()
    except AttributeError:
        raise TypeError


def json_decoder(obj):
    supported_classes = {A.__name__: A}
    if obj['type'] in supported_classes:
        return supported_classes[obj['type']].from_json(obj)
    else:
        raise TypeError
```

```Python
json_data = json.dumps([1, 2, A(3), A(4), 5], default=json_encoder)
json_data
'[1, 2, {"type": "A", "v": 3}, {"type": "A", "v": 4}, 5]'

json.loads(json_data, object_hook=json_decoder)
[1, 2, A=3, A=4, 5]
```

**Comment by Durman** [comment]
Also I have thought that it would be good to have got a class which would know about correct structure of a json file. Also such class could have method which would help to fill in the structure step by step. It's hardly that node should know how to build correct structure of a json file.

```Python
class JSONFormat01:
    """It's only know about Sverchok JSON structure nad can fill it"""
    def __init__(self):
        self._json_data = {
            "export_version": "0.10",
            "framed_nodes": dict(),
            "groups": dict(),
            "nodes": dict(),
            "update_lists": []
        }

    def add_node_in_frame(self, node_name, frame_name): ...

    def add_monad(self, monad_name, magic_string): ...

    def add_node(self, node_name) -> NodeFormat:
        node_data = dict()
        self._json_data['nodes'][node_name] = node_data
        return NodeFormat(node_data)

    def add_link(self, from_node_name, from_socket_index, to_node_name, to_node_index): ...


class NodeFormat:
    def __init__(self, empty_node_data: dict):
        self._json_data = empty_node_data
        self._json_data.update({
            "bl_idname": "",
            "location": [],
            "params": dict(),
            "custom_socket_props": dict()
        })

    def add_mandatory_attributes(self, bl_idname: str, location: list): ...

    def add_node_custom_attribute(self, attr_name, attr_value): ...

    def add_socket_attribute(self, socket_index: int, attr_name: str, attr_value): ...
```

**Comment by Durman** [comment]
Node tree can be converted into json like this:

```Python
json.dumps(node_tree, tree_encoder(JSONFormat(), selected))
```
```Python
def tree_encoder(format, selected):
    def endocer(obj):
        if isinstance(obj, NodeTree):
            obj.to_json(format, selected):
        except:
            raise TypeErorr
    return encoder
```
```Python
class Tree:
    def to_json(format, selected):
        for node in self.nodes:
            node_format = format.add_node(node.name)
            node.to_json(node_format)
            if node in frame_node:
                format.add_node_in_frame_node(node.name, frame_node.name)
            if node is monad:
                node.add_monad(format)
        for link in self.links:
            format.add_link(link.from_node.name, link.from_node.sock_index, link.to_node.name, link.to_node.sock_index)
```

Looks not too bad.

**Comment by zeffii** [comment]
remember to handle `Reroute Nodes`

**Comment by Durman** [comment]
https://github.com/nortikin/sverchok/blob/325dad18adeb0d7c84435532a19c5242faae4dd9/utils/sv_IO_panel_tools.py#L188

https://github.com/nortikin/sverchok/blob/325dad18adeb0d7c84435532a19c5242faae4dd9/utils/sv_IO_panel_tools.py#L206-L210

I'm thinking probably instead of creating such lists it would be better to add extra option to properties.

```Python
prop: bpy.props.FloatProperty(options={'SKIP_SAVE'})
```
And to make JSON serialization according this option.

**Comment by zeffii** [comment]
yeah. makes sense. i'm for it.

**Comment by Durman** [comment]
Also it can let rid off `properties_to_skip_iojson` attribute in nodes implementation. Each node can just add the option into its property and exporter will be aware that the property should be skipped.

**Comment by zeffii** [comment]
yes! my concern is only about keeping the IO code backward compatible.

**Comment by zeffii** [comment]
(at least for the existing IO code... )

**Comment by Durman** [comment]
It goes without saying. Old json should be importable. 

My concern is whether it always convenient to have the same option for saving into a file and into a json.

**Comment by zeffii** [comment]
ah yes "SKIP_SAVE"  is part of the enum/set of a property.  I thought you could add arbitrary items to that enum, guess not?

**Comment by Durman** [comment]
Definitely not.
```
ValueError: BoolProperty(options={ ...}):: 'MY_OPTION' not found in ('HIDDEN', 'SKIP_SAVE', 
'ANIMATABLE', 'LIBRARY_EDITABLE', 'PROPORTIONAL', 'TEXTEDIT_UPDATE')
```

**Comment by Durman** [comment]
Using `SKIP_SAVE` means that JSON importer should handle everything what should be saved in a file and pointer properties (at least some of them) as well. And this can be fair because if it should be saved in a file why this should not be saved in a json.

**Comment by zeffii** [comment]
> Definitely not.
unfortunately.

but what does SKIP_SAVE do in relation to saving a `.blend` , worst case scenario would be that the current value of a property wouldn't be saved.

**Comment by Durman** [comment]
I think it would be possible to add standard approach for serialization of collection properties. Should looks like this:
```Python
{"collection_name": [{"name": "", "my_prop": 1.0}, {"name": "", "my_prop": 2.0}, ...]}
```

**Comment by Durman** [comment]
API sketch for import module:

```Python

class JSONImporter01:
    def __init__(self, structure: dict): ...

    @classmethod
    def init_from_path(cls, path) -> JSONImporter01: ...

    def import_into_tree(self, tree: SverchCustomTree): ...

    def _nodes(self) -> Generator[NodeImporter01]: ...

    def _links(self) -> Generator[tuple]: ...

    def _parent_nodes(self) -> Generator[tuple]: ...

    def _monads(self) -> Generator[str]: ...


class NodeImporter01:
    def __init__(self, structure: dict): ...

    def node_attributes(self) -> Generator[tuple]: ...

    def node_properties(self) -> Generator[tuple]: ...

    def input_socket_properties(self) -> Generator[tuple]: ...


class TreeGenerator:
    def __init__(self, tree_name): ...

    @classmethod
    @contextmanager
    def start_from_new(cls, tree_name) -> TreeGenerator: ...

    @classmethod
    @contextmanager
    def start_from_tree(cls, tree: SverchCustomTree) -> TreeGenerator: ...

    def add_node(self, bl_type: str, node_name: str) -> NodeGenerator: ...

    def add_link(self, from_node_name, from_socket_identifier, to_node_name, to_socket_identifier): ...

    def apply_frame(self, frame_name: str, nodes): ...


class NodeGenerator:
    def __init__(self, tree_name, node_name): ...

    def set_node_attribute(self, attr_name, value): ...

    def set_node_property(self, prop: BPYProperty): ...

    def set_socket_property(self, socket_identifier: str, prop: BPYProperty): ...


class BPYProperty:
    def __init__(self, data, prop_name: str): ...

    def set_property(self, data): ...
```

**Comment by Durman** [comment]
I think generating classes for monad nodes is unnecessary complexity. All monad nodes could share one class.

**Comment by zeffii** [comment]
if properties are defined on the socket, at runtime (and hotswapped when changes), then i also think monad classes do not need to be dynamically registered.  

good.

**Comment by Durman** [comment]
Yes it would be optimal solution. But it also possible to create collection. Each item in the collection would belong to one monad where it can generate its properties. `layout.prop(group_node.collection['monad_name'], 'float')`.

**Comment by Durman** [comment]
In `storage get data` node method instead of getting data from dictionary it is setting them. And vice versa in `storage set data`. If the methods belongs to nodes they should be named relatively to them. The nodes are setting or getting data not the storage.

**Comment by zeffii** [comment]
those nodes are names from the perspective of the caller, and it's needs, which is the IO code.

i get your point, but the reason is as above.

**Comment by Durman** [comment]
I'm thinking about replacing names of the methods by:  `node.save_to_json(node_data), node.load_from_json(node_data)` or probably `node.init_from_json(node_data)` would sound clearer.

**Comment by zeffii** [comment]
yes, do it!

**Comment by portnov** [comment]
Currently, as far as I understand, we can do such renames easily when we like.
But, as Sverchok's "ecosystem" grows, we will have to consider needs of related addons — for example, the addons currently being developed for Ladybug integration, BIM, and it is probable that later new ones will appear. So, in future, we will have to think twice before introducing such changes: won't this break the code in related addons / scripts? Shouldn't we notify their authors?...
Just thinking aloud.

**Comment by Durman** [comment]
I hope that after refactoring, `node` developers will have less thinking about serialization problems. Import export should become more clever. And renaming some methods is not big deal. Some nodes which used those methods won't use them after refactoring. If I'll ever finish with this. It's bigger chunk than I thought.

**Comment by portnov** [comment]
I tried to start it some years ago, then I saw that it is a lot of code, scattered across the whole codebase and untested :) I ended up creating some testcases, but had not enough momentum to perform the refactoring itself. Hope you have more luck :)

**Comment by Durman** [comment]
Actually core is ready and it works. It is possible import and export nodes and monads. But there are nodes which import logic are hard coded into old import core and I didn't move that logic into nodes yet. I'm trying to make new system unaware of any node types. But in some cases I have to fail this principle otherwise it will involve too much code to refactor.

**Comment by Durman** [comment]
I'm thinking of default implementation of storing pointer data in JSON. It json should keep name of data_block assigned to a pointer. 

In most cases it is okay. But if pointer of `Mesh viewer` node will have aссidently the same name as name of some data block in imported file the node can erase a the data block. I think there should be the rule that if a node is modifying data the pointer should not be saved in a file. Or pointers to a mesh should not kept at all in json files.

**Comment by portnov** [comment]
In nodes like "object in" it would be nice to store actual mesh/curve/whatever data, that was used while the node was in scene, in json (and re-create objects in scene on import). "Object In Lite" already does this, but not other nodes. And I doubt it is possible to implement such logic in node-independent way. Maybe add callback methods? like `json = node.export_property(prop_name)` and `node.import_property(prop_name, json)` ?

**Comment by Durman** [comment]
I have some ideas about that but I'm definitely not going implement them in current iteration. 
It is possible to make something like this:

JSON file:
```
{'nodes': 
  'Objects in': 
    'props':
      'my_pointer': {verts: [(0,0,0), ...], 'edges': [(0, 1), ....], 'faces': [(0, 1, 2), ...]}
}}}
```

In import module:

```Python
my_pointer, value = read_node_properties_from_json()
if my_pointer.type == 'POINTER':
    if my_pointer.pointer_type == 'MESH':
        mesh_data_block = generate_mesh(value)
        my_pointer = mesh_data_block
```

**Comment by Durman** [comment]
It looks like I have to add extra argument to load_from_json (storage_set_data) method. Because many nodes does not have need in the method anymore. But old JSON files can't be loaded without the information in those methods. And the same time it should not be called if JSON is new.

```Python
class Node:
    def load_from_json(self, node_data: dict, importer_version: float):
        if importer_version <= 0.08:
            do_old_code()
```

**Comment by Durman** [comment]
I think in future we should rid of `load_from_sjon` / `save_to_json` (`storage_set_data` / `storage_get_data`) methods. I consider such code as ugly and we can came to something like that.

```Python
def load_from_json(self, node_data: dict, importer_version: float):
    if 1.0 > import_version >=0.5:
        do_not_very_old_import_code()
    elif 0.5 > import_version > 0.08:
        do_old_code()
    elif importer_version <= 0.08:
        do_ancient_code()
```

@portnov @zeffii @vicdoval 
The solution should be in storing all necessary data for node working in properties. I think it quite possible if data can be encoded to string and decoded from it. I would suggest try to avoid using those methods in future nodes.

**Comment by zeffii** [comment]
@durman congratulations, you managed to liberate sverchok from my ugly code. great! less technical debt for all.

**Comment by Durman** [comment]
Well I can't say that the code has finish state. 

I can't change everything I would like because it requires monads refactoring what I consider like time wasting. Also it requires breaking compatibility with old json files. And there are bunch of nodes which code should be refactored as well so they could drop special export/import methods and rely totally on work of import / export modules. So this issue won't be able to cover all necessary improvements but should be good base for further movements.

**Comment by Durman** [comment]
I have found that `SKIP_SAVE` options is actually works only in operator properties and it means that if an operator has UI an option with this property will be always shown with default value otherwise it would show last user choice.

https://blender.stackexchange.com/questions/21104/option-flags-for-custom-properties-bpy-props

So it is possible to use it freely for our purposes without worrying if some significant information can be lost during saving / loading a file.

For now I'm going to use this option to skip useless to be save in JSON properties. Also their usage fitting for skipping pointers in viewer nodes as far they can rebuild them by themselves. But further improvements in saving pointers into JSON should force to reconsider usage of those properties I guess.

**Comment by Durman** [comment]
Nice condition
https://github.com/nortikin/sverchok/blob/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40/utils/sv_IO_panel_tools.py#L117-L120

**Comment by portnov** [comment]
:)
Usually such things are used as "compileable comments" (code that is not called, but is compiled, so that you can be more or less sure that it will be working when you "uncomment" it). This trick does not work so nicely in interpreted languages, though...

**Comment by Durman** [comment]
Strange that importing tree and one node using the same operator.
![2020-09-29_13-17-55](https://user-images.githubusercontent.com/28003269/94539462-4e5b9580-0256-11eb-9c0d-d51691832997.png)

**Comment by portnov** [comment]
Well, I could create a separate operator, but it would be different only in title...

**Comment by Durman** [comment]
I also mean that setting node properties saves useless attributes in JSON file like `nodes`, `links`, `groups`, `frames`.

**Comment by Durman** [comment]
No size is not priority here. I mean it looks a bit suspiciously.
https://github.com/nortikin/sverchok/blob/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40/ui/presets.py#L340
Probably having separate format for storing node data is not as bad idea. It does not matter now anyway since there was done a lot of presets.

**Comment by portnov** [comment]
Having one format has one good side (i did not design it specifically, but it just appeared so and I thought this is good): per-node presets can be used from "usual" Presets panel. So you can use one "per-node preset" in two scenarios:
1) select a node, then select a preset from it's menu => settings of the selected node will be updated from the preset
2) select a preset from "presets" section of the T panel => new node with settings from preset will be created.

**Comment by Durman** [comment]
There is no option in update system which could prevent updating tree during importing tree event. 

`tree.freeze(hard=True)` looks is not dooing this hard enough and I gusses that some nodes during import unfreeze tree.

**Comment by Durman** [comment]
Interesting observation. JSON file does not keep default values assuming that new nodes are created with default values. But there is exception in this rule. Viewer nodes can automatically change object name if default was already used. It leads to that some nodes can be imported with wrong object names.
