### ISSUE TITLE
Request Optie to join polyline viewer output 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3543]
Request Optie to join polyline viewer output 

 Sometimes this can be usefull to make easy some cable profiles etc.... with bezier curves .

I can do this manual by select the collection and ctrl +j to join this but if want to change something then i must join it again etc...
And i must then set the origion again etc...

 Is there maybe a better solution for this maybe ? 

Another question with mesh viewer you have now the option to free move your object : works fine with Hard-ops for example 
Can this be done with the polyline viewer node ? 

![image](https://user-images.githubusercontent.com/49908008/93145280-39c2bd80-f6ec-11ea-8975-de3804b96cf9.png)

**Comment by Durman** [comment]
There is list of viewer nodes to be refactored: #3482

I was not sure which take next but now I think I will take `polyline viewer`.

**Comment by Durman** [comment]
And check this button, probably it is what you are looking for.
![2020-09-15_08-50-52](https://user-images.githubusercontent.com/28003269/93166950-9d6eda00-f730-11ea-87c2-2c73a84539e7.png)

**Comment by BennyGovaerts** [comment]
Group make automatic a  collection, this is not the same like CTRL + j

**Comment by zeffii** [comment]
to make all inputs into one object in Polyline viewer, you use the "Single" mode.
![image](https://user-images.githubusercontent.com/619340/93187740-6d2f3780-f740-11ea-89e9-475eaa77d23e.png)

I don't think however, that this will resolve the issue you have with the fact that you are applying "cablerator" ontop the Sverchok output.

**Comment by zeffii** [comment]
at least.. that's what the Signle mode "should do"  . but it seems to be broken?

**Comment by zeffii** [comment]
@BennyGovaerts  a small workaround for this node at the moment is (computationally no different at the moment)

![image](https://user-images.githubusercontent.com/619340/93188790-b633bb80-f741-11ea-8441-978f405b54cc.png)

**Comment by Durman** [comment]
![2020-09-15_12-54-38](https://user-images.githubusercontent.com/28003269/93189003-b7b9af80-f752-11ea-9a84-283a91486b14.png)

**Comment by BennyGovaerts** [comment]
Excellent thanks for the feedback and the examples 

![image](https://user-images.githubusercontent.com/49908008/93198982-087ad980-f74e-11ea-838d-aba1542328a3.png)

**Comment by BennyGovaerts** [comment]
![image](https://user-images.githubusercontent.com/49908008/93200890-b12a3880-f750-11ea-9b6a-ad3fa94600fc.png)
