### ISSUE TITLE
REVISITING Curve With Hemispere At First and Last Point

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3549]
This one bothers me for quite some times...

PROBLEM: Making a perfect non twisting line from grease pencil with rounded hemisphere at the start and end of the line.

<img width="1264" alt="Screen Shot 2020-09-16 at 1 22 24 pm" src="https://user-images.githubusercontent.com/3952687/93288726-ec476d00-f81f-11ea-9b0a-5c85720f8bdc.png">

[single_stroke_cylinder_002.blend.zip](https://github.com/nortikin/sverchok/files/5229440/single_stroke_cylinder_002.blend.zip)

Previously I have asked this and did get a few potential answer, but Bevel Curve often gives twisting. And making Hemisphere is still convoluted.

**Comment by enzyme69** [comment]
Related to this:

https://github.com/nortikin/sverchok/issues/3498

**Comment by zeffii** [comment]
i presume you are looking for a way to align the "cap" (start, end) object? The normal matrix of those objects would be taken from the "normal" of the start and end vectors in those lines..  This can be be simplified even further than my example:

![image](https://user-images.githubusercontent.com/619340/93333600-da67c900-f823-11ea-8356-9a95f8f03a9c.png)

[single_stroke_cylinder_002_prompt_2020_09_16_11_52.zip](https://github.com/nortikin/sverchok/files/5231939/single_stroke_cylinder_002_prompt_2020_09_16_11_52.zip)

**Comment by zeffii** [comment]
I think zuggamasta is working on improvements to the C implementation of the cap-style for Curves, Sverchok will adopt any new features.

**Comment by zeffii** [comment]
my example tries to make the point that you should leverage Blender's power when possible, like making tubes is best done using Polyline viewer because it only needs a sequence of vertices, and lets Blender calculate the geometry. It's OK to get Sverchok to drive Blender features, not everything must be done from within Sverchok. Use the best tool, not a particular node for the sake of it.

**Comment by zeffii** [comment]
i also imagine that the alignment of a sphere as a cap object, is probably not a super high priority.. with high even subdivision, and rendered who's going to see the orientation of the sphere?

**Comment by zeffii** [comment]
https://twitter.com/zuggamasta/status/1305789121286279168

i think this is what you are looking for, and it should be implemented in Blender, rather than Sverchok..
