### ISSUE TITLE
Proposal to standardise the nesting level of strings

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3555]
I see that most nodes return this pattern `[[n]]`, where `n` is an integer, a list of three coordinates for a vertex, or a list of two indices for an edge. I also see a lot of this pattern, which makes sense due to the nested list:

```
x_out = []
for a, b, c in zip_long_repeat(...):
    ...
    x_out.append()
```

However, then I see some examples like the `File Path` node which gives `['foo bar']`. Shouldn't this be `[['foo bar']]`?

Another example is the `Note` node, which gives `[[['foo'], ['bar']]]`. Shouldn't this also be `[['foo bar']]`, and then another node should split by whitespace, which can then convert it into `[['foo', 'bar']]`?

**Comment by Durman** [comment]
#2761

**Comment by Moult** [comment]
@Durman thanks - but #2761 talks about values, edges, vertices, and faces ... but it does not talk about strings. My question is about the inconsistency in strings. I believe it should be the same as values.

**Comment by zeffii** [comment]
note node and file path node are exceptions , and we have currently no standardized protocol for passing strings around.

**Comment by zeffii** [comment]
a case could be make for a variety of approaches.

sentences
```python
[
   [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.",
      "et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip"
   ]
]
```
and words..
```python
[
   ["Lorem", "ipsum", "dolor", "sit", "amet,", "consectetur", "adipiscing", "elit,", "sed", "do", "eiusmod", "tempor", "incididunt", "ut", "labore."],
   ["et", "dolore", "magna", "aliqua.", "Ut", "enim", "ad", "minim", "veniam,", "quis", "nostrud", "exercitation", "ullamco", "laboris", "nisi", "ut", "aliquip"]
]
```

**Comment by Moult** [comment]
@zeffii I am working on generating Sverchok nodes for IFC data and Ladybug tools (Ladybug - note the Ladybug node currently in Sverchok is not the full Ladybug, which I am working on, plus Honeybee and Dragonfly). To do this, standardising the protocol for passing strings would be extremely useful. There will be hundreds of nodes generated at the end of this.

Perhaps in my prototyping, I can figure out what convention makes the most sense as a "standardised" protocol for basic text nodes, and I can also offer to create a suite of string manipulation nodes (e.g. split, trim) to allow users to create variations when they need to. How does that proposal sound?

**Comment by Durman** [comment]
Best what can be done for understanding which structure would be appropriate is to think of real examples of usage. 

For example drawing labels nearby vertices. In this case structure of text should repeat structure of vertices. like this then: 
`[ ['label v1', 'label v2', ...], ['label v1, ....], ... ]`

**Comment by Moult** [comment]
@Durman agree - real examples of usages would drive this. I will see what works best in my usages of IFC and Ladybug, which would have many nodes passing around strings, and see what comes out of it :) I will post here when I discover a convention which works for the majority of cases.

**Comment by zeffii** [comment]
i also think this  (bag of strings)  is the more sane
```python
[ ['label v1', 'label v2', ...], ['label v1, ....], ... ]
```
it is equivalent to
```
[
   [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.",
      "Et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip"
   ]
]
```
we don't care what the individual list elements are.

**Comment by zeffii** [comment]
any node that _does_ care, will have internal options  or  as you propose a suite of string-handler nodes to operate on the socket data.

**Comment by zeffii** [comment]
but "note" node, is an awkard solo example : )

**Comment by zeffii** [comment]
since 2014 i've used `Scriptnode` or `formula node` or `execnode` for text processing, dedicated nodes will be interesting :)

**Comment by nortikin** [comment]
note node doesn't work with SVGtext node text socket, it is strange.
