### ISSUE TITLE
Is there a node for viewing text in the 3D viewport?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3559]
For example, the `Viewer Draw Mk3` will draw verts, edges, and faces. Is there a node for viewing text in the 3D viewport? The text should be located in a 3D location, have a size, alignment, etc?

**Comment by zeffii** [comment]
there's a "Viewer Index" node, which has extra features that allow you to display text at vertices. - it lacks a feature for Text alignment and size, rotation, tho..

But i had started a re-implementation of just the Text part of it, for a new node, the other day.
https://github.com/nortikin/sverchok/pull/3552

**Comment by zeffii** [comment]
There is also the `Typography Viewer`, but that outputs Font/Curve objects (real Blender objects) into 3d space. Orientated in worldspace, but can be transformed individually using the input Matrices) .
- upside it has extensive Text configuring properties
- downside, it isn't screenspace (without providing it with a set of Matrices to reflect a viewport orientation)

**Comment by Moult** [comment]
@zeffii I see - the typography viewer is more that I was hoping for, but it won't garbage collect after itself - i.e if the node is deleted, it won't delete the text objects.

Is there a destructor event / hook that is called when a node is deleted, so that it can clean up after itself?

**Comment by Durman** [comment]
https://github.com/nortikin/sverchok/blob/c06af7d9434f8fe93b93f85e7b1cd3f595d6cf3b/node_tree.py#L307-L311

**Comment by zeffii** [comment]
nope, the node is generally used for creating scene text / objects. 

but Blender does call `sv_free` when a node is removed, we could add code in there to remove objects created by typography viewer. easily.

**Comment by Durman** [comment]
But should they delete objects when nodes are removed? It is possible to delete object by disconnecting all input links.

**Comment by zeffii** [comment]
> But should they delete objects when nodes are removed?

i've struggled with that question for a long time, there are scenarios where removing the node is part of a workflow where a user doesn't want the objects to be removed (automatically).  so. it's not clear.  but this is the reason i didn't add anything like that to `sv_free`. 

a solution would be an operator, which user triggers explicitely to remove a node and all generated objects.

**Comment by zeffii** [comment]
an alternative to 'x' , `shift+x` maybe.

**Comment by nortikin** [comment]
> For example, the `Viewer Draw Mk3` will draw verts, edges, and faces. Is there a node for viewing text in the 3D viewport? The text should be located in a 3D location, have a size, alignment, etc?

![изображение](https://user-images.githubusercontent.com/5783432/93664230-eb0f7d80-fa75-11ea-8c20-c043fc16c2b0.png)
https://gist.github.com/7966bb8c3714225fec756b7f56ac1b20

**Comment by zeffii** [comment]
@nortikin  is that b2.91  ?   i also don't use b291 because of the graphical glitches. it's a bit worrying.

**Comment by nortikin** [comment]
> @nortikin is that b2.91 ? i also don't use b291 because of the graphical glitches. it's a bit worrying.

2.90.0 it is

**Comment by zeffii** [comment]
weird : /
