### ISSUE TITLE
How do I feed in an empty list to get "no faces"?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3561]
I'm attempting to pass lists of [verts, edges, faces], similar to the screenshot, but some will not have faces, for instances. What is the appropriate to let it know that this particular [v, e, f] doesn't have any faces? I've tried `None`, and an empty list as shown below, without success (you can see the empty list creates artifacts.

![image](https://user-images.githubusercontent.com/88302/93588136-4e55cd00-f9ee-11ea-91fc-8700f67412a6.png)

**Comment by portnov** [comment]
This particular node will work like "no faces" if you just leave the input unconnected.

**Comment by Moult** [comment]
@portnov sorry, let me try rephrase my question:

For example, let's say I have I have a plane, that has this data:

```
verts: [[ [0,0,0] , [1,0,0] , [1,1,0] , [0,1,0] ]]
edges: [[ [0,1], [1,2], [2,3], [3,0] ]]
faces: [[ [0,1,2,3] ]]
```

That works well for _one_ object... but what if I had two objects, and one object had faces, but the other one doesn't:


```
                   ## OBJECT 1 VERTS ##                              ## OBJECT 2 VERTS ##
verts: [     [[0,0,0] , [1,0,0] , [1,1,0] , [0,1,0]]    ,    [[0,0,0] , [1,0,0] , [1,1,0]]     ]
                   ## OBJECT 1 EDGES ##                              ## OBJECT 2 EDGES ##
edges: [     [[0,1], [1,2], [2,3], [3,0]]               ,    [[0,1], [1,2], [2,0]]             ]
                   ## OBJECT 1 FACES ##                              ## OBJECT 2 HAS NO FACES ##
faces: [            [[0,1,2,3]]                         ,              [?]                     ]
```

**Comment by portnov** [comment]
As far as I understand, there should be empty list.
```
faces: [            [[0,1,2,3]]                         ,              []                     ]
```

**Comment by Moult** [comment]
@portnov when I try an empty list, I get artifacts as shown in the screenshot. Maybe a bug in the viewer where it assumes a polygon must exist?

**Comment by zeffii** [comment]
the node expects consistency within the "collection" of input verts/edges/faces sockets, so if a socket is connected it's expecting data (not empty lists). It may seem like undesirable behaviour in your scenario, but that's not how we've used the node (and it's predecessors) for the past 6 years.

should it be able to handle what you're doing? yes, but some codeshuffling would be needed.

**Comment by zeffii** [comment]
i hesitate to call it a bug, but feature vacuum.

**Comment by Durman** [comment]
@Moult You probably will be satisfied with using `mesh viewer`? 
But in your case you should switch off fast update option on the N panel. I will improve mesh changes test later so it could recognize disappearing of face data.
![2020-09-18_15-03-25](https://user-images.githubusercontent.com/28003269/93597145-a16a5880-f9cb-11ea-987c-33942624683f.png)

**Comment by vicdoval** [comment]
Objects are joined before being send to the shader, so it shouldn't have any issues if one of the polygons list is empty
![image](https://user-images.githubusercontent.com/10011941/93663608-76364680-fa69-11ea-898d-af1bc18e2d11.png)
Anyway would be nice to check polygons existence even if it is linked...

**Comment by Durman** [comment]
> i hesitate to call it a bug, but feature vacuum

I think it is sign of bad design of Sverchok. Probably many nodes can't handle such case. 

It is should be either impossible to stack objects with faces with objects without faces or other nodes should expect that such case is possible.

**Comment by zeffii** [comment]
> Probably many nodes can't handle such case.

don't confuse "bad design" with code that can evolve to meet (sane) conditions.
