### ISSUE TITLE
Is it possible to link multiple node outputs to a single node input?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3562]
Can I do this?

Output 1: `[[x, y, z]]`
Output 2: `[[a, b, c]]`
Resultant input: `[[x, y, z],[a,b,c]]`

No problem if this cannot be done, but if it could, would make life easier :)

Alternatively I can write code so that once Input 01 is filled, Input 02 is generated ... i.e. there is always one more input you can plug in. Is there a node that already does this behaviour?

![image](https://user-images.githubusercontent.com/88302/93662040-28890080-faa0-11ea-9775-0770a9491049.png)

**Comment by portnov** [comment]
Currently this is not supported (and I even don't know if it can be supported with Blender's pynodes api). Usually you use "List Join" node in such cases.

**Comment by Moult** [comment]
@portnov thank you :) Makes sense!
