### ISSUE TITLE
Viewer 2d broken?

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3563]
## Problem statement

Not works

## Steps to reproduce

1. range
2. viewer2d
3. number display

## Expected result

drawing

## Actual result

no drawing

## Sverchok version

```
Exception: Shader Compile Error, see console for more details
GPUShader: compile error:
0:34(11): error: `gl_FragColor' redeclared

ERROR:sverchok.core.update_system:Node Viewer 2D had exception: Shader Compile Error, see console for more details
Traceback (most recent call last):
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/core/update_system.py", line 384, in do_update_general
    node.process()
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/nodes/viz/viewer_2d.py", line 800, in process
    geom = generate_graph_geom(config, vecs)
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/nodes/viz/viewer_2d.py", line 354, in generate_graph_geom
    config.v_shader = get_2d_smooth_color_shader()
  File "/home/ololo/.config/blender/2.90/scripts/addons/sverchok/nodes/viz/viewer_2d.py", line 158, in get_2d_smooth_color_shader
    return gpu.types.GPUShader(smooth_2d_vertex_shader, smooth_2d_fragment_shader)
Exception: Shader Compile Error, see console for more details
```

https://gist.github.com/9f4c06a7b0969828aa1853ae25e95abf

**Comment by zeffii** [comment]
works on windows.

**Comment by zeffii** [comment]
@vicdoval  it might simplest to use an alternative named output variable then, as with this example..

- we wont assume gl_FragColor is available as a default output
- can use fragColor instead, as the last item in the shader.

https://github.com/nortikin/sverchok/blob/c06af7d9434f8fe93b93f85e7b1cd3f595d6cf3b/utils/sv_shader_sources.py#L30-L50

**Comment by Durman** [comment]
Ridiculous label. What about "monday bugs"? I do not see why we should track blender API inconsistency.

**Comment by zeffii** [comment]
it's a ridiculous bug.

**Comment by Durman** [comment]
I understand labels as simple way to combine topics in general categories so it will be easy to track them.

**Comment by zeffii** [comment]
anyway. i'll fix the bug

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3575
