### ISSUE TITLE
Is it possible to get the current node ID?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3564]
Is there some way of retrieving the node's current ID with the Blender API, where if you create two of the same node, they have a different and unique ID?

**Comment by Durman** [comment]
The names of the nodes is always unique inside one tree. But name can be changed by user. For this reason we added `node_id` attribute to nodes in Sverchok. But I assume that it can have different values between different Blender sessions.

**Comment by zeffii** [comment]
`self.name`  from within the node

but using bpy nodes api, if you are spawning another node from this node
```python
node = bpy.data.node_groups["NodeTree"].nodes.new("Your_Node_bl_idname")
```
`node` is a direct reference to the node

**Comment by Durman** [comment]
One should keep in mind that keeping such references can lead to Blender crash.

https://docs.blender.org/api/current/info_gotcha.html#help-my-script-crashes-blender
