### ISSUE TITLE
What is the recommended way to show tooltips for node inputs / outputs?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3569]
In Grasshopper / Dynamo, hovering over input or output will show a tooltip, which can be very educational for the user. Is there a preferred way to do this in Sverchok?

**Comment by enzyme69** [comment]
Ctrl + LMB Click on node to give Temporary Viewer seems to do it for me. And Stethoscope node. Ctrl +RMB

**Comment by Moult** [comment]
@enzyme69 hey Jimmy - I don't mean viewing the data, I mean a tooltip for an additional description of the node. E.g. if programming my own nodes, it would be good to provide a description to explain it for users.

**Comment by enzyme69** [comment]
<img width="760" alt="Screen Shot 2020-09-21 at 4 25 08 pm" src="https://user-images.githubusercontent.com/3952687/93737631-0a99d800-fc27-11ea-81cc-9cfaf514aebc.png">

Oh ok maybe the Note node?

**Comment by Moult** [comment]
Hmm, no, it's more like this (an example from Grasshopper):

![image](https://user-images.githubusercontent.com/88302/93737891-afb4b080-fc27-11ea-8d8c-9d99e74c3bd8.png)

![image](https://user-images.githubusercontent.com/88302/93737985-f5717900-fc27-11ea-804c-9aa97a85392a.png)

**Comment by portnov** [comment]
I didn't see such possibility in Blender's pynodes API :/ It would be good to have it, though. You can start from https://docs.blender.org/api/current/bpy.types.Node.html, maybe you'll be luckier.
Another option is to make a feature request for Blender devs, they may consider it, but I'm afraid that will not be fast...

**Comment by vicdoval** [comment]
The closest we got to that is the tooltip of the property (its description), but we only have properties in input sockets 
![image](https://user-images.githubusercontent.com/10011941/93740282-79a50b80-fbea-11ea-846c-7aae29ae9058.png)

**Comment by vicdoval** [comment]
Maybe if #3312 happens we could add there a tooltip about the outputs too

**Comment by Moult** [comment]
@vicdoval ooh, yes, very cool, I like #3312. Hopefully this can be solved with that :)

**Comment by portnov** [comment]
How exactly do you think that PR will help? By adding a tooltip for dropdown menu button?

**Comment by vicdoval** [comment]
> How exactly do you think that PR will help? By adding a tooltip for dropdown menu button?

Would that be possible?

**Comment by Durman** [comment]
It is possible for operators. 
zeffii's example:
```Python
class SvGenericUITooltipOperator(bpy.types.Operator):
    arg: StringProperty()
    bl_idname = "node.sv_generic_ui_tooltip"
    bl_label = "tip"

    @classmethod
    def description(cls, context, properties):
        return properties.arg
```
https://docs.blender.org/api/current/bpy.types.Operator.html#bpy.types.Operator.Operator.description

**Comment by portnov** [comment]
One possible UX problem is that the expected tooltip for that button would be something like "Open a menu with data conversion options". If the tooltip on the button will say something like "This output contains the list of vertices", and click on the button will call the menu, I'm not sure it's the desired behavior.

**Comment by Moult** [comment]
Perhaps a little button with a "help" icon can be shown optionally if data is provided on that node, then hovering over the icon will display the tooltip. Not sure how crowded it would look, though.

**Comment by Durman** [comment]
> Another question is that this is an "operator button"; what to do when user clicks it?

It can get popup tooltip with scrollbar?

**Comment by portnov** [comment]
I didn't find a way to do such thing in Blender's API :/

**Comment by portnov** [comment]
We can instead create and connect Sthethoscope or Note node.

**Comment by Durman** [comment]
Probably best what blender can permit.
![2020-09-29_19-48-35](https://user-images.githubusercontent.com/28003269/94582181-02781300-028d-11eb-8999-b3ba4fd28562.png)

**Comment by portnov** [comment]
Aha, a tooltip with "Error" in header :)

**Comment by Durman** [comment]
Should be better.
![2020-09-29_20-35-34](https://user-images.githubusercontent.com/28003269/94587276-656ca880-0293-11eb-9730-408106061b1b.png)

**Comment by portnov** [comment]
Much better. How to do this?

**Comment by Durman** [comment]
```Python
class HelloWorldOperator(bpy.types.Operator):
    bl_idname = "wm.hello_world"
    bl_label = "Minimal Operator"
    
    text: bpy.props.StringProperty()

    def execute(self, context):
        print("Hello World")

        def draw(menu, context):
            col = menu.layout.column(align=True)
            for string in self.text.split('\n'):
                col.label(text=string)


        bpy.context.window_manager.popup_menu(draw, title="MY TITLE", icon='FUND')
        return {'FINISHED'}
```

**Comment by vicdoval** [comment]
I find this is the nicest..

> ![Screenshot_20200929_195922](https://user-images.githubusercontent.com/284644/94576108-69e29280-028e-11eb-89cb-1a5979779f07.png)

Bur couldn't this be inside the drop-down? I don't like that much to have the nodetree full of question marks... Maybe showing it only in the selected/active nodes? Or maybe hiding the name of the socket and placing it in the operator instead of the question mark icon

**Comment by portnov** [comment]
> Or maybe hiding the name of the socket and placing it in the operator instead of the question mark icon

Interesting idea. We can use `layout.operator(text=label)` instead of `layout.label(text=label)` for showing socket label, then it can have tooltip as an operator. 

![Screenshot_20200929_215248](https://user-images.githubusercontent.com/284644/94588990-22640280-029e-11eb-9a5f-cd659a6ef9fe.png)

There is text alignment glitch in this case: there is too much free space between "Vers" label and the menu button. I'm not sure if something can be done with this.

**Comment by portnov** [comment]
> Bur couldn't this be inside the drop-down? 

Interesting idea too.

![Screenshot_20200929_215924](https://user-images.githubusercontent.com/284644/94589748-1cbaec80-029f-11eb-9e0e-805e7c7431a6.png)

**Comment by portnov** [comment]
So, it appears we have all means to do what we want to. The question remains, which way we like it more? :)

**Comment by vicdoval** [comment]
I would go with the `layout.operator(text=label)` .
The spacing glitch is not that bad

**Comment by Moult** [comment]
I also like the text label.

How would this look for tooltips for inputs?

**Comment by vicdoval** [comment]
> How would this look for tooltips for inputs?

The inputs with properties (as th i think th LB nodes have) have the description of the property as tooltip

**Comment by Durman** [comment]
If socket is linked there is not property and tooltip. 
Some sockets can be without properties. 
If a property located in a socket then also there is no tooltip.
