### ISSUE TITLE
Rail Sweep and Symmetry

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3571]
I've been playing around with the new "(Mono?) Rail Sweep Surface" node trying to achieve mirror symmetry, and I noticed slight asymmetry of the generated surface although all four profile curves(green, yellow, blue and red) are perfectly symmetric about the global space Y axis. 
The first and last V rows of the new surface are indeed symmetric to XZ plane, but all interior control points aren't.

![Sweep_vs_Symmetry](https://user-images.githubusercontent.com/66558924/93820143-64b98e00-fc65-11ea-9a02-176843f81147.jpg)

I couldn't find any parameter values that could correct the precision of the result. Is that possible with the current implementation?

Thanks

**Comment by portnov** [comment]
Could you please attach blend.zip file. I'll investigate.

**Comment by rendetto** [comment]
It took me a while to simplify my overly complicated tree, but here it is:

[Sweep_Precision_Symmetry_Test.zip](https://github.com/nortikin/sverchok/files/5267141/Sweep_Precision_Symmetry_Test.zip)

Try different numbers for V-Sections. For example 5 gives better view of the asymmetry. 

Also I used explicitly the "Points" metric. The other metrics doesn't seem to work well on interpolating the middle two profiles(profile_2 and profile_3). They sure can interpolate those better but at a cost of adding a lot of V-Sections which I don't feel very practical.

The whole symmetry thing is just an observation. I'm not sure that this could be identified as a problem, but more like a attempt to seek some perfection(as it looks almost perfectly symmetric now). What I mean also by "almost perfectly symmetric" is the fact that the generated control points of the last (boundary) V curve have the same Z and X and slightly different Y coordinates as the original path curve - so that's almost a mirror copy.

I guess the mono-rail sweep object isn't targeted at solving this kind of setup as it has only one constraint at V direction - the other side isn't predefined with another(mirrored) rail curve.
Maybe a bi-rail sweep or a net of curves(Gordon surface) will be better suited for such setup?

Thanks

**Comment by portnov** [comment]
At a first glance, this looks like calculations precision issue. I think, you can achieve more perfect symmetry if you use "rail"  curve that goes by the middle ("spine") of the surface, not at one of sides. But that, off course, would require to use another curve to make the same surface.

I can implement Gordon surfaces, it looks like more or less simple in implementation; but they have very strong restriction: the curves that constitute the net must intersect exactly at all nodes of the net (not just go near one another). With such restriction, I'm not sure if this thing is really useful (are there many situations in which you can generate this kind of perfect net)? What do you think?

I wasn't able to find a good mathematical description of "Birail" operation ("Sweeping" along one curve is described in "the NURBS Book", but not birail). If you have any links, I'll look if it is easy to implement.

**Comment by rendetto** [comment]
I find Gordon very usable, despite the constraints. It won't be hard constructing a constrained net by hand using the Interpolation NURBS curve object.

There are cases where, for example, we want to construct very controllable blend surface(by hand), or reverse engineer scan data, or just want more manual control over the sections in both directions of a free-form surface. 

Unfortunately I don't recall an article about the mathematics specifically behind the bi-rail surface, but there's one particular case of Gordon net that resembles a lot the bi-rail surface  - a net interpolating 2 (boundary) curves in the first direction, and several curves at the second direction. 

So until finding proper mathematics for bi-rail, I guess a Gordon surface could be a good substitute.

Thanks

**Comment by portnov** [comment]
Ok, I'll put Gordon surfaces to my todo list, but as you understand, I can't give you any ETA.

Btw, the simplest case of Gordon surface is Coons surface, which is already implemented :)

**Comment by rendetto** [comment]
No pressure, take your time. I've done some tests with the implemented Coons and was very excited when you did it NURBS transparent.

I've also "read" The NURBS Book being just an artist, only to have some general understanding how those things work. It turns very practical reading in terms of using the tools you've implemented.

Thank you!

**Comment by portnov** [comment]
I managed to implement Birail node (#3705). I still was not able to find a good description of some commonly used algorithm, so it is very probable that I have reinvented the wheel...

**Comment by rendetto** [comment]
Great news! I'll start testing how it works and share the results. 

You've said that Gordon looks fairly easy to implement and I was expecting that it will come first. I've seen very good results using net of curves as a Birail structure(2 curves in one direction and several in the other), so I guess you could find some inspiration there also. TiGL library uses Gordon as a main modelling tool, and there is an adaptation of the same code in CurvesWB in FreeCAD.

Thanks a lot!
