### ISSUE TITLE
IFC nodes for Sverchok

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3574]
This bug is to keep track of the nodes I am creating for IFC generation. IFC is a schema to represent data about buildings (BIM), commonly used in the architecture, engineering, construction and building operations industry. As Blender can now be used to produce BIM data, it makes sense to allow some nodes to manipulate it with.

I expect there to be around 30 nodes, covering reading, writing, creating entities, modifying entities, filtering entities, visualising entities, etc.

I'm not sure if it is beneficial to distribute with Sverchok core, as IFC manipulation is a relatively niche topic, useful for BIM guys but not much else.

Here's a start, basic read, create, and write operations:

![image](https://user-images.githubusercontent.com/88302/93876394-229e5400-fd1a-11ea-9120-b22bc8db248f.png)

**Comment by Moult** [comment]
Creating entities is now possible!

![2020-10-01-144628_1848x551_scrot](https://user-images.githubusercontent.com/88302/94769357-2e160d00-03f5-11eb-821a-f6783e92fb5c.png)

**Comment by JanFilipec** [comment]
Do you plan on adding a custom ifc output to get the geometry into blender, or do you think reimporting will work fine enough?
(see also https://github.com/nortikin/sverchok/issues/3678 I'd like to generate ifcDumbWall with sverchok)

**Comment by Moult** [comment]
There is now an IFC "create shape" node. Does that do what you're asking for?

**Comment by Moult** [comment]
Closing, as the first release is now out. Any workflow discussions can be made in community.osarch.org or if it's a bug, its own bugreport.

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/109402711-06f24600-7969-11eb-938f-a38b5503da4e.png)
simply it not handle sverchok path node
