### ISSUE TITLE
How do I wrap this this list of objects?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3576]
I am trying to wrap a list of objects: -e.g. instead of `[bpy.data.objects['foo']]` I want `[ [bpy.data.objects['foo']] ]`

How do I do this?

![image](https://user-images.githubusercontent.com/88302/93955204-8f553500-fd92-11ea-8a09-8efd6398c51c.png)

**Comment by Durman** [comment]
![2020-09-23_08-13-47](https://user-images.githubusercontent.com/28003269/93966028-b866cd00-fd74-11ea-92ad-626e01b3c229.png)

**Comment by Moult** [comment]
@Durman thank you :)
