### ISSUE TITLE
number range - wrong label after connecting a socket

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3577]
this happens in several modes, f.ex  Float / Count mode, has a Stop slider, but it's displayed as "Step" once it's connected.

![count_range_stop_step](https://user-images.githubusercontent.com/619340/93987435-d8ec5280-fd87-11ea-8ab3-c0d010f43b9a.gif)

**Comment by vicdoval** [comment]
Yeah.. when the socket is linked it shows the socket id not the property name.... maybe this could be changed in the sockets class so it is not necessary to create a socket for every name

**Comment by Durman** [comment]
Probably it is time for SOCKET LABELS
I will create fix PR.

**Comment by zeffii** [comment]
i presume this is happening on other nodes too.
