### ISSUE TITLE
Fill / stroke SVG

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3579]
## Problem statement

`File / stroke SVG` node does not work with `color input`.

![2020-09-23_19-00-12](https://user-images.githubusercontent.com/28003269/94030647-1e803e00-fdcf-11ea-8605-ac8af7576fb6.png)
[untitled_2020_09_23_15_00.zip](https://github.com/nortikin/sverchok/files/5269016/untitled_2020_09_23_15_00.zip)

**Comment by vicdoval** [comment]
If the alpha value is set to 0 you wont see anything...
Maybe the default alpha of the color input should not be 0
