### ISSUE TITLE
Issues with Docs

### ISSUE THREAD

**Issue by JitQL** [nortikin/sverchok#3581]
I have been starting with Blender, BlenderBIM and now Sverchok as the combo might be one of the reasons I might change into Blender. Thanks for your work. It's incredible!

As I'm starting from scratch I tend to have basic questions that might be silly for most advanced users, but which make me loose hours in search for answers. I hope this small contribution helps you help others too.

I've been following the docs step by step, starting from installation and I intend to follow it through and pinpoint the issues I find in the way.

I'm using Blender 2.90

INSTALLATION

I had several issues installing and updating sverchok and it's dependencies starting from PIP, until I found that I had to run Blender as Administrator in windows10. After that, all went smoothly and I could update and install everything from blender > preferences > add-ons > sverchok. You could advice Windows users to do the same if somehting fails to install.

INTRODUCTION

On the "Make a first Polygon" stage this is stated:

> In Simple Topology node fill the Faces field with the shorthand: 0,1,2,3. This means “i want a face described by these vertex indices”

However I found out that "0,1,2,3" does not generate a face, you have to remove commas and add spaces for the list of indeces to work "0 1 2 3". I don't know if this is a bug of sverchok and it should work, or if it is supposed to be like that, as the format without commas is what you show in the image.

I'll keep posting more if I find.
.

**Comment by Durman** [comment]
You can fix docs yourself if you wish. It is not as difficult. Swerchok keeps all files in this folder. You have to fix them in your fork and create new pull request after that.

**Comment by JitQL** [comment]
@Durman thanks!

But How do I know if some of these are bugs from sverchok or in the documentation itself?

**Comment by Durman** [comment]
This is a file which should be fixed I guess.
https://github.com/nortikin/sverchok/blob/master/docs/Unit_01/lesson_01.rst

This is documentation of the node. You can learn from it initial intention of a developer.
https://github.com/nortikin/sverchok/blob/master/docs/nodes/script/topology_simple.rst

**Comment by zeffii** [comment]
@JitQL  you're right, i've updated the doc. typos, my bad. The node works as shown in the screenshots, the text accompanying it was not not read by anyone other than you or I.

**Comment by JitQL** [comment]
I will keep reading it and following the tutorial. It's very good! If I find more stuff I'll post it here if you don't mind. I don't feel confortable changing it for now. I know nothing of how things work, so I can only point things that do not match. If you rather I'd do anything else, if I can I'll do it.

**Comment by zeffii** [comment]
@JitQL  what you are doing is appreciated, i'd be surprised if that's the only mistake hidden away in there.

**Comment by JitQL** [comment]
I have a couple of suggestions for Lesson 01 to make it more accessible to all (even if concepts are very simple).

Change the name from "Lesson 01 - A Plane" to "Lesson 01 - Circumscribed Square" It's, after all, a specific plane that follows strict rules that are explained in the lesson.

If you agree, then the concept of the geometry could be more easily understandable like this:

Let’s make a Square circumscribed in a Circle. We will need 4 vectors and we’ll define them using math. I’ll start by using the Trigonometric concept of the unit-circle to get coordinates of the points of the square. In the unit circle, the vertexes of the square will be located 0.5 PI appart from each other, along the perimeter of the circle.

> NOTE: 
> The perimeter of the circle is C = 2*π*r , so 2/4=0.5π
> 
> If you consider that a circle represents an angle of 360 degrees then 2πr=360º and this means that 0*π places represents a vertex at 0 degrees of the circle:
> 0π=0º ; 0.5π=90º ; 1π=180º ; 1.5π=270º

To make things interesting we will rotate our circle 45º from X axis.

`Image of the circle`

To begin we want to create a series of numbers, to represent those points on the unit-circle. Essentially this sequence is [0.25 pi, 0.75 pi, 1.25 pi, 1.75 pi]. Because these aren’t whole numbers (Integers), but so called Floats, we use a Number Range Node configured to output Floats.

**Comment by zeffii** [comment]
The choice of "Plane" reflects Blender's own `Object->Add->Plane` primitive .  I'm not sure "Circumscribed Square" is more accessible. So i don't really agree. 

You can show directly how you would edit the text by doing an Edit to an rst (and submitting it as a patch/pullrequest), and i'll see easier the real change / addition you propose.

![image](https://user-images.githubusercontent.com/619340/94157758-e0902200-fe81-11ea-9960-f72fc10edf2b.png)

then the  "propose changes" submit will appear like this at the bottom, and turn darker once you start adding/changing text

![image](https://user-images.githubusercontent.com/619340/94157935-0f0dfd00-fe82-11ea-9148-c4325a312cac.png)

and look like this when i read it

https://github.com/nortikin/sverchok/pull/3586/files

**Comment by JitQL** [comment]
I understand the plane from blender idea. I just feel there could be simpler ways of creating a plane and this specific method is great for concentric polygons. At least when I understood why we were using PI and tested some side stuff, I was able to create the amount of divisions of the circle I wanted just by using the number range node. I somehow suspect that will be what happens in lesson 2.

**Comment by JitQL** [comment]
Sorry for wasting your time but how do I access the rst file? I can't see it at the website. I'm new to Github and this kind of stuff.

**Comment by zeffii** [comment]
dig through this directory: https://github.com/nortikin/sverchok/blob/master/docs/Unit_01/lesson_01.rst (online)

**Comment by zeffii** [comment]
directory: https://github.com/nortikin/sverchok/tree/master/docs/Unit_01

**Comment by JitQL** [comment]
I did it but I didn't see the "create a branch for this commit and start a pull request" option on the bottom form.

I hope I didn't brake anything.

**Comment by Durman** [comment]
Don't worry you won't be able to brake anything because you have not any permissions to edit the repository

![add changes proposal](https://user-images.githubusercontent.com/28003269/94172491-9b7ce780-fea3-11ea-81e7-405316412acc.gif)

**Comment by Durman** [comment]
Also here you can find created by you branches in your fork and create Pull request from there.
![2020-09-24_20-42-56](https://user-images.githubusercontent.com/28003269/94174682-aab16480-fea6-11ea-8ceb-f592fe86902a.png)

**Comment by JitQL** [comment]
So, do I have to o pull the request fo it to be reviewed?

Because submitted the changes with the propose changes button, but I didn't pull a request.

**Comment by Durman** [comment]
Yes you have create pool request

**Comment by JitQL** [comment]
I think I was able to create the pull request. It's still all a bit criptic to me, but I guess what forking means is that I copy the files into a new "folder" on my account, I then change them as I wish, and then "pull request" is that I send a request for validating this file and insert it into the original folder. Is this it?

Sorry for my noobishness, but it really is the first time I'm dealing with github

**Comment by Durman** [comment]
> Is this it?

Exactly, but creating a fork means copy whole repository not just one folder or file. The same True about creating new branch. In pull request only files are shown which are different from main repository.

**Comment by JitQL** [comment]
And is it necessary to create a fork? I don't know how that came to be. I don't believe I would have the need want to have a fork of the whole project. I rather work on the file and submit proposals to it exclusively. Or is it always like that, and you can only do that if you fork it?

**Comment by Durman** [comment]
It is how Git system works.

**Comment by JitQL** [comment]
I'm moving to lesson 2 and opening it directly in Github so I can suggest corrections if they occur. However I've noticed that the docs in the main site are not in line with what's in Github:

https://sverchok.readthedocs.io/en/latest/Unit_01/lesson_02.html
 
Github is updated while the main site is not. (Examole: Nodes haven't got the current name)

**Comment by zeffii** [comment]
The docs are not compiled in real-time on the site, yet. If you want to see them with a reasonable "rendering" on github.

![image](https://user-images.githubusercontent.com/619340/94253793-1981d280-ff26-11ea-80e7-9fb71dd7aced.png)


btw, i think you'll agree that seeing changes to docs in this form is pretty useful :) 

![image](https://user-images.githubusercontent.com/619340/94253649-e50e1680-ff25-11ea-9b9a-a550a38f0b84.png)

**Comment by zeffii** [comment]
i urge you to dig through the `.rst` (ReStructuredText) syntax description, to gain better control over how the text is displayed.

https://docutils.sourceforge.io/docs/user/rst/quickstart.html

**Comment by JitQL** [comment]
I just found that there are duplicated doc sites:

https://sverchok.readthedocs.io/en/latest/main.html

http://nikitron.cc.ua/sverch/html/main.html

I got to readthedocs.io by google search and to nikitron from sverchok home page.

**Comment by zeffii** [comment]
You might have noticed that the online rendering of the rst by githb, is not 100% 1-to-1 with how the ReadTheDocs renders the pages.

**Comment by JitQL** [comment]
> i urge you to dig through the `.rst` (ReStructuredText) syntax description, to gain better control over how the text is displayed.
> 
> https://docutils.sourceforge.io/docs/user/rst/quickstart.html

I will. I was searching for how to make that note format and had a hardtime. I eventually copied the formatting you made before.

**Comment by zeffii** [comment]
copying the format is probably fine :)   even if githb doesn't render it "correctly", once the docs are compiled it will look like the other "notes".

**Comment by JitQL** [comment]
> The docs are not compiled in real-time on the site, yet. If you want to see them with a reasonable "rendering" on github.
> 
> ![image](https://user-images.githubusercontent.com/619340/94253793-1981d280-ff26-11ea-80e7-9fb71dd7aced.png)
> 
> looks like
> 
> ![image](https://user-images.githubusercontent.com/619340/94253900-41713600-ff26-11ea-8d2d-4fa36c92a225.png)
> 
> btw, i think you'll agree that seeing changes to docs in this form is pretty useful :)
> 
> ![image](https://user-images.githubusercontent.com/619340/94253649-e50e1680-ff25-11ea-9b9a-a550a38f0b84.png)

That's exactly what I was trying to do today. That way I can read and suggest changes on the fly. Is there a way to see the preview on the fly? It would be very cool to see what you're formatting as you go.

**Comment by JitQL** [comment]
> copying the format is probably fine :) even if githb doesn't render it "correctly", once the docs are compiled it will look like the other "notes".

Ahhh. Then that's why I wasn't seeing notes formatting as I was expecting. It gave me a hard time and only worked above the image.

Sorry for giving you such a hardtime while learning. I hope it will pay off. The best way to learn is to teach simultaneously. If I do work on the docs, I'm hoping I learn faster and eventually help out at the same time. who knows if I'm building up more docs later... 

Thanks for your patience

**Comment by zeffii** [comment]
i'm not a fan of the web-interface, it's use-case is not intense file editing, but rather incidental edits. I think you can preview as you edit (look for a button) , but not simultaneously like some websites.

I have a syntax highlighter in my TextEditor of choice (sublime), which understands .rst and gives me a basic rendering, then i compile the manual locally (super simple btw, but maybe initial learning barrier is offputting.... such is the price of progress )

**Comment by zeffii** [comment]
it's a pain to have to learn more of the eco-system just to be able to edit/add documentation, i suspect that puts a lot of people off. Maybe we can write a short tutorial about the steps needed just to write docs..  unfortunately i have other commitments

**Comment by JitQL** [comment]
Thanks for your help.

**Comment by nortikin** [comment]
i have troubles with ftp last week. thinking of relocate docs to some strong place

**Comment by portnov** [comment]
Obvious place would be github pages...
