### ISSUE TITLE
Sverchok Not working anymore with Blender daily build 2.91.0

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3583]
Sverchok Not working anymore with Blender daily build 2.91.0

![image](https://user-images.githubusercontent.com/49908008/94137951-900bcb00-fe67-11ea-83d9-f8f1aa636377.png)

**Comment by zeffii** [comment]
```python
location: C:\Users\zeffi\Desktop\test_blenders\current_28\2.91\scripts\startup\bl_operators\node.py:92
Python: Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 336, in init
    ng.freeze()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 110, in freeze
    self["don't update"] = 0
KeyError: 'IDProperty names cannot include ", \\, or \''
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3585 fixes this, if people want to test ( 2.90 ) before committing . works in 2.91

**Comment by BennyGovaerts** [comment]
Thanks

**Comment by zeffii** [comment]
thanks for reporting it. 

i can't find the Blender API commit that forces us to do this, i suspect it's code committed within the last 26 days.

**Comment by zeffii** [comment]
@BennyGovaerts  you may experience stuff like this https://github.com/nortikin/sverchok/issues/3493
