### ISSUE TITLE
"A Number" node default value to "1"

### ISSUE THREAD

**Issue by JitQL** [nortikin/sverchok#3584]
I find it strange that the "A Number" node default value is 0. When used with addition and subtraction it is neutral, but when used with multiplication it makes our result disappear and with division it should return infinite.

Wouldn't it make more sense to have it at "1"?

I believe at 1 it would affect less nodes than having it a 0

**Comment by zeffii** [comment]
whatever number we set as the default, someone - somewhere - is going to stick up a hand and say another value is more useful. `1` would also rarely be useful, seen as we have a Scalar Math node with a +1 -1 mode too.

What i've done (and i am the author of that node) , is to set the value to something sane directly after creating it, but before connecting it.

we used to have a feature that let users set their own defaults per node, in a configuration file. but it was [refactored out](https://github.com/nortikin/sverchok/pull/3483).
https://github.com/nortikin/sverchok/wiki/Custom-Defaults

**Comment by portnov** [comment]
You can create a preset with whatever-you-want default value. Moreover, you can create several presets wit different default values. And Blender even allows you to assign different keyboard shortcuts to different presets.
https://github.com/nortikin/sverchok/blob/master/docs/panels.rst

**Comment by zeffii** [comment]
a direct kb shortcut for a number node is cool, i'd go with that.

**Comment by portnov** [comment]
Right-click on operator button or on menu item -> Assign Shortcut.

**Comment by portnov** [comment]
Also "Quick menu" is usable feature. Right click on menu item or button -> Add to Quick Favorites; then press Q to call the menu.

**Comment by JitQL** [comment]
I understand and thanks for the explanation.
