### ISSUE TITLE
Lofting with three and more starting points - possibility or other solution? 

### ISSUE THREAD

**Issue by DaveSledz** [nortikin/sverchok#3587]
Hi guys. Here's my another interesting question regards Sverchok and Blender. A simple architectural form inspired from Zaha Hadid. Please take a look and notice the wider endings of the pillars: 

![Fluid-and-Organic-Modern-Architecture-Leonardo-Glass-Cube-in-Bad-Driburg-by-3Deluxe-homesthetics-2-1024x682](https://user-images.githubusercontent.com/45789626/94160923-737e8b80-fe85-11ea-9b98-ebe48a311477.jpg)

**Question**: What's the best approach to make that in Blender? 

I tried first without SV using Metaballs, then particle flow with force fields (kinda result but I'm not satisfied) and now with SV so those are my current propositions:
- Lofting but using three and more starting points / curve cross-sections.
- Skin modifier with three vertices / vector p fields

Those propositions sound nice but I wanted to ask you guys - what'd you choose to create similar form? I suppose there's better way to do that but I couldn't find the best one. Especially with those enlarged, wider endings which look amazing.

**Comment by rendetto** [comment]
I suggest you can just make a low-poly model  and add the Catmull-Clark Subdivision modifier on top.
It's very direct and controllable approach. And you won't need SV in this case.

![Blender_PolyModeling](https://user-images.githubusercontent.com/66558924/94189114-ff5adc80-feb2-11ea-9187-acb5ed51dc6f.jpg)
The above test took me about 2 minutes, so it's not hard at all.

Cheers

**Comment by portnov** [comment]
The real question is only how many of such objects do you need and how different they should be. If you need only one, it's obviously simpler to use standard Blender modeling techniques. If you need a lot of such things, and they should be controlled somehow (randomly, or by some interesting logic), you probably will prefer to invest some time in building a node tree...

**Comment by DaveSledz** [comment]
Yup, thanks a lot, sometimes the easiest methods are the best. I also thought about subdivision modeling but of course there was an idea to control it from points, playing with particles, SV etc. There is also possibility with attractor fields and marching cubes. Nvm guys, done
