### ISSUE TITLE
Issues with Python 3.7 Dependencies for Ubuntu 20.04 (python3.7m: command not found)

### ISSUE THREAD

**Issue by MauroAmoruso** [nortikin/sverchok#3595]
## Trying Installing Python 3.7 Dependencies for Ubuntu 20.04

The Ubuntu 20.04 is shipped with Python 3.8 and the Python 3.7m version used in blender is inside a snap folder, if installed via Snap, I tried Installing Scipy at first.

**1.Installing pip**

- I tried at first installing pip

`..../snap/blender/47/2.90/python/bin$ python3.7m -m ensurepip `

result 
`python3.7m: command not found`

----
- of course not possible to upgrading pip: 

`..path/to/blender-2.9/2.90/python/bin/python3.7m -m pip install -U pip `

result 
`python3.7m: command not found`

----

- I find out blender-2.8 and 2.9 : pip is already included so you don't need to run ensurepip beforehand

```
..../snap/blender/47/2.90/python/bin$ python3.7m -m pip install -U scipy
```
still
`python3.7m: command not found`

----

**2. So I tried to use the system Python3.8**

```
../snap/blender/47/2.90/python/bin$ python3.8 -m ensurepip
```
result 

```
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules for the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.
```

**3. Then I have installed also python 3.7** 
so I can access 3.7 running command python3.7

```sudo apt-get install python3.7```

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'python3.7-2to3' for regex 'python3.7'
Note, selecting 'libpython3.7-stdlib' for regex 'python3.7'
The following packages were automatically installed and are no longer required:
  libfprint-2-tod1 libllvm9 libllvm9:i386 linux-headers-5.4.0-45
  linux-headers-5.4.0-45-generic linux-image-5.4.0-45-generic
  linux-modules-5.4.0-45-generic linux-modules-extra-5.4.0-45-generic
  linux-modules-nvidia-440-5.4.0-45-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 78 not upgraded.
```
But same problem occur 

```
../snap/blender/47/2.90/python/bin$ python3.7m -m pip install -U scipy
python3.7m: command not found
```

Similar Problem occurred for Animation Node.
https://github.com/JacquesLucke/animation_nodes/issues/1240

Sverchok works regularly except for the Dependencies.

**Comment by portnov** [comment]
> .../snap/blender/47/2.90/python/bin$ python3.7m -m ensurepip 

You have to do
```
.../snap/blender/47/2.90/python/bin$ ./python3.7m -m ensurepip
```
here (note the **./** part, it means take the executable from current directory)

**Comment by portnov** [comment]
Also I'm afraid you won't be able to install dependencies into Snap installation of blender this way, because as far as I know Snap creates a readonly file system. But let's try.

If you'll see something like `Cannot ...: readonly file system`, then there are the following options:
* use non-snap way of installing blender; IMHO, the simplest one is to just download `tar.xz` from blender.org and unpack it.
* try messing with `pth` files do let Blender's python know about packages that you have in your system's python installation. I'm not sure if this will be easy.

**Comment by MauroAmoruso** [comment]
@portnov _thanks, btw I am a follower of your work with SV and Nurbs!_

----

**Solution**
---

Downloaded the tar.xz from

https://download.blender.org/release/Blender2.90/

Unpacked and everything got Installed as for the instruction given.
It worked alright without any conflict with the snap version.
Dependencies are installed.

```
Installing collected packages: numpy, scipy
Successfully installed numpy-1.19.2 scipy-1.5.2
```

---
**Note on Snap**


As you were expected the snap version was giving [Errno 30] Read-only file system error.

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/snap/blender/47/2.90/python/lib/python3.7/site-packages/easy_install.py
```
