### ISSUE TITLE
Multy Cache Node: Particles with Random Lifespan?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3597]
I am testing out @vicdoval new node "Multy Cache" I might use this the wrong way. I am trying to have Particles with random lifespan and want to cache the particle position data into each own bucket, but getting weird result:

<img width="1043" alt="Screen Shot 2020-09-29 at 12 04 54 pm" src="https://user-images.githubusercontent.com/3952687/94504416-118aa100-024c-11eb-8edb-ead7a13cb0da.png">

If particle has same lifespan my setup seems to work. Unlike Vic example, I have to also use List Split however.

In my video I am showing the weird thing:
https://youtu.be/TIeZcnsLo6A

**Comment by enzyme69** [comment]
My feeling with Blender Particles, when we tell it to spawn 5 particles each frame, the particle will be born in this order: 1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4 -> instead of 1,2,3,4,5,1,2,3,4,5...

**Comment by vicdoval** [comment]
The `UV connection` node expects all lists to have the same length, if the particle number differs from one frame to another you will need to make some other tricks to trace them

**Comment by nortikin** [comment]
list match
