### ISSUE TITLE
"Intersect Edges" node bug

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3601]
When using the "Intersect Edges" node, it changes the output of the "Objects In" node.

![intersect_edges_bug](https://user-images.githubusercontent.com/66558924/94751476-62f07880-0391-11eb-92db-973c69b42136.jpg)

The setup includes one mesh object containing 2 separate crossed edges. After connecting the "Intersect Edges" node the "Objects in" node starts to output list of 5 vertices instead of 4.

Thanks

**Comment by Durman** [comment]
Probably `sv_get(deepcopy=False)` problem

**Comment by rendetto** [comment]
Now it works OK. Thank you!
