### ISSUE TITLE
Edit source button creates error

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3602]
Original bugreport is https://github.com/ladybug-tools/ladybug-blender/issues/8

But I think it is a problem with Sverchok, since I tried it with a regular Sverchok node and I got the same error. Ideas?

**Comment by Durman** [comment]
This button should show source code of selected node in blender text editor.

![2020-10-01_10-14-29](https://user-images.githubusercontent.com/28003269/94774402-ea101180-03ce-11eb-9282-ed59c7c94bc1.png)

**Comment by Moult** [comment]
This is what I get - by the way, I do see a new text data block holding the source, but it isn't the active data block in the text editor.

![image](https://user-images.githubusercontent.com/88302/94774777-ea75d000-0401-11eb-98a1-776bb57f37d4.png)

**Comment by Moult** [comment]
The actual key is `bpy.data.texts['line_mk4.py']`- maybe the key canonicalisation is wrong?

**Comment by Durman** [comment]
#2273

**Comment by Durman** [comment]
Probably it is operation system issue. This pursing looks suspicion to me.

https://github.com/nortikin/sverchok/blob/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40/ui/development.py#L199

**Comment by ppaawweeuu** [comment]
I have no problem with Line Node, everything is ok. All sv nodes can be opened in internal text editor.
I see problems with Ladybug nodes. I think it is becouse EditSource button uses get_filepath_from_node function (development.py, lines 231-236):

    def get_filepath_from_node(self, n):
        """ get full filepath on disk for a given node reference """
        sv_path = os.path.dirname(sverchok.__file__)
        path_structure = n.__module__.split('.')[1:]  # strip sverchok
        path_structure[-1] += '.py'
        return os.path.join(sv_path, *path_structure)

As I understand, it search for some_node.py files only in sverchok folder, not ladybug folder. If we want to use that button for 3rd party nodes (not in sv folder) there is need to change get_filepat... function. Am I correct?

**Comment by ppaawweeuu** [comment]
link to that function:
https://github.com/nortikin/sverchok/blob/eb7d5c42b11d7aacb2d5adbbbb2598d995ea1e40/ui/development.py#L231
