### ISSUE TITLE
Is there a way to pass a list of objects to matrix apply ?

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#3605]
So i was wondering if there a way to pass a list of objects to matrix apply ?
For example 2 spheres, then 1 box then 3 spheres, then 2 boxes along a line or a circle matrix let's say.
I'm trying list join but best result I can achieve is having 1 box and 1 sphere on every position which is not what i want

**Comment by vicdoval** [comment]
Can you share a screenshot of your nodetree/file?

**Comment by Durman** [comment]
![2020-10-02_16-41-21](https://user-images.githubusercontent.com/28003269/94924199-237b7680-04ce-11eb-9d96-c7b2c48fcc50.png)

**Comment by mlevet** [comment]
@vicdoval here is my nodetree
<img width="947" alt="Capture d’écran 2020-10-02 à 14 46 58" src="https://user-images.githubusercontent.com/17178730/94924762-67ff1600-04be-11eb-9c7a-3b2bed7e96c4.png">

Thank you @Durman, exactly what i want, still trying to figure out how it works but i think i get it !
I will now try to make with a matrix apply instead

**Comment by vicdoval** [comment]
If you use  joinlevel List= 2 you merge all the objects lists (it should be =1)
Also you dont need 2 box nodes if they are identical.
And be aware that you are passing 4 objects and 5 matrixes to the matrix apply node (the last object will be repeated)

**Comment by mlevet** [comment]
Thank you so much, big step for me in the matrix understanding here !

**Comment by mlevet** [comment]
Another question : using that model, would it be possible to interpolate between each of them using Vector Interpolation ?

**Comment by vicdoval** [comment]
I'm not sure if I understand the question but to interpolate between objects they need to have the same number of vertices.

**Comment by mlevet** [comment]
ah ok so i'm very wrong here,
is there a way to make this sequence of forms one continuous
object seemingly morphing together,
by filling the space between them ?

**Comment by vicdoval** [comment]
Probably there are many ways...
One possible way In this case between a Sphere and a Cube you could use the "Cast" Node to generate the middle shapes... And you you would need to manually re-mesh it later
![image](https://user-images.githubusercontent.com/10011941/94940212-7f94c980-04d3-11eb-928c-bb5ed0979271.png)
![image](https://user-images.githubusercontent.com/10011941/94940326-a4893c80-04d3-11eb-93c2-0210d638bbec.png)
In this example I'm using the Oscillator node to go from 0 to 1 smoothly, is not your exact case but it may serve as hint

**Comment by Durman** [comment]
![2020-10-02_19-26-08](https://user-images.githubusercontent.com/28003269/94940877-2b92e080-04e5-11eb-836f-e3158fdb0bbc.png)

**Comment by mlevet** [comment]
Many thanks you both, gonna try that !
