### ISSUE TITLE
How can i do the same distribution  with the polyline / Curve 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3606]
How can i do the same distribution  with the polyline / Curve : 
![image](https://user-images.githubusercontent.com/49908008/94940457-d4384480-04d3-11eb-9319-5a7fcd5b0f8c.png)

**Comment by portnov** [comment]
I'm not sure I understand what exactly are you talking about, but try "Curve Frame" or "Curve Zero-Twist Frame" nodes (in combination with "Number range" for T input).

**Comment by vicdoval** [comment]
You mean this?
![image](https://user-images.githubusercontent.com/10011941/94961606-41100680-04f5-11eb-8a2d-90f32f477305.png)

**Comment by BennyGovaerts** [comment]
Thanks Vicdoval .
