### ISSUE TITLE
Sverchok - Subdiv by Nodes

### ISSUE THREAD

**Issue by fewerjunk** [nortikin/sverchok#3608]
## Problem statement

Artifacts

Please describe your problem here.

## Steps to reproduce

https://user-images.githubusercontent.com/284644/77354971-83e26c00-6d65-11ea-8a47-193d0772f406.png

(JSon Attached for clarification)

[sve_subd.zip](https://github.com/nortikin/sverchok/files/5320726/sve_subd.zip)

![sve_sbd_artifacts_JPG](https://user-images.githubusercontent.com/70761456/94976915-5b34ef00-04cb-11eb-890f-8a36425bee9f.jpg)

## Expected result

No artifacts.

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version
0.6.0.0

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

Installed from release zip file

**Comment by Durman** [comment]
![2020-10-03_06-36-45](https://user-images.githubusercontent.com/28003269/94981375-da193e80-0542-11eb-88dd-b9d17e9e3f9f.png)

**Comment by fewerjunk** [comment]
Well, that works (sort of).

1) I like my twirl effect.
2) Maybe it's a lack of ability on my part.  The only way I seem to be able to get faces is to not add faces to the viewer and then (F) Face in edit mode which returns unuseful results to say the least.
3) I notice that to select say, corner verts means I have to Join the objects first. Tried that just to see how useful Proportional rotation would be to get a comparable twist result.  Again, maybe it's what I don't know.  The original
config was more useful in that regard.
4) Where does "Temporal Viewer" come from?  I use the default Viewer.
5) It's simpler.  And it works. (Mostly) (Sort of). So, there's that.

**Comment by Durman** [comment]
> Where does "Temporal Viewer" come from? I use the default Viewer.

https://github.com/nortikin/sverchok/blob/master/docs/shortcuts.rst

**Comment by cxdcxdcxd198** [comment]
@Durman Ctrl + Left mouse button
http://nikitron.cc.ua/sverch/html/shortcuts.html

**Comment by fewerjunk** [comment]
> > Where does "Temporal Viewer" come from? I use the default Viewer.
> 
> https://github.com/nortikin/sverchok/blob/master/docs/shortcuts.rst

Seen and saved.  Thanks.
