### ISSUE TITLE
Temporal Stethoscope - error after delete

### ISSUE THREAD

**Issue by ppaawweeuu** [nortikin/sverchok#3610]
## Problem statement

After deleting Temporal Stethoscope, ctrl+RMB rise error

## Steps to reproduce

1. create Temporal Stethoscope node, ctrl+RMB on some node (and it is awesome)
2. select and delete that stethoscop
3. nothing is selected
4. again ctrl+RMB with no node selected
5. error

> Traceback (most recent call last):
>   File "C:\Users\paweu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\ui\sv_temporal_viewers.py", line 153, in execute
>     add_temporal_viewer(context, self.force_stethoscope, self.cut_links)
>   File "C:\Users\paweu\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\sverchok-master\ui\sv_temporal_viewers.py", line 122, in add_temporal_viewer
>     if len(existing_node.outputs) == 0:
> AttributeError: 'NoneType' object has no attribute 'outputs'
> 
> location: <unknown location>:-1

## Expected result

Nothing. I think ctrl+RMB without selecting any object should do nothing.

## Actual result

I see that normally ctrl+RMB without selected any node lunch Temporial Stetoscope for last selected and deselected node (i was suprised but cal live with that). Problem is when last selected node does not exist (was deleted) - error is rised.

![tmp_stet](https://user-images.githubusercontent.com/61344631/94992553-08227100-058b-11eb-80ac-7c9e3d13cbcc.jpg)

## Sverchok version

b3d 2.9, sv 0.6.0.0

**Comment by vicdoval** [comment]
Fixed  😄 Thanks for reporting @ppaawweeuu !

**Comment by ppaawweeuu** [comment]
works fine, thx.
