### ISSUE TITLE
Temporal Viewer - geometry disapear

### ISSUE THREAD

**Issue by ppaawweeuu** [nortikin/sverchok#3611]
## Problem statement

Temporal Viewer geometry disapear after second ctrl+LMB

## Steps to reproduce

1. Create Temporal Viewer by ctrl+LMB
2. Again ctrl+LMB
3. Preview geometry disappear
4. Manipulate node values/anything -> gemetry shown again

## Expected result

Nothing. I think repeating ctrl+LMB should do nothing. 
Or maybe second click sholud do something useful/predictable (like Temporial Stethoscope swithing sockets).
I think second click could deactivate viewer (predictably, with eye icon change in TmpView.. node. Third click activate again.

## Sverchok version

win7, b3d 2.9, sv 0.6.0.0

**Comment by vicdoval** [comment]
I think this bug is fixed in the new viewer draw mk4, can you confirm it @ppaawweeuu ?

**Comment by ppaawweeuu** [comment]
fixed :+1: 
i have next one. i think it can be related, and maybe also #3610 .
my steps:
1. add Plane node
2. add Temporary Viewer (i see blue plane)
3. add Temporary Stetoscope
4. delete Temporary Stetoscope
5. undo (ctrl+z) = Temporary Stethoscope is restored but Blue Plane disapears.
Same with any other geometry displayed by Viewer. Stethoscope restored = Viewer cleared.
Any Stethoscope, even if not related to viewed geometry.
--
Should i report it as new issue?

**Comment by zeffii** [comment]
open a new issue if there is a new problem that doesn't match the title of this issue

**Comment by JuanJ67m** [comment]
1+

please fix.

Blender 2.92.0

![image](https://user-images.githubusercontent.com/4990279/117227587-c685cd00-addc-11eb-8a7e-64c002323b5a.png)
