### ISSUE TITLE
Format for Numpy mesh

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3612]
I'm thinking which format numpy mesh should have.
Something already was said here. #2761

There are some nodes which can already produce for vertices, edges, faces numpy arrays.
![2020-10-03_18-19-37](https://user-images.githubusercontent.com/28003269/94993900-32812800-05a5-11eb-96ee-c4fa1689955e.png)

`Mesh viewer` node can use vertices numpy arrays what can improve its speed significantly.
https://github.com/nortikin/sverchok/pull/3475#issuecomment-680010778

The main problem is with keeping polygons in array format.
Example how it is now.
![2020-10-03_18-35-04](https://user-images.githubusercontent.com/28003269/94994191-2dbd7380-05a7-11eb-9ae8-a7b9cac6a311.png)

It is quite limited format which let convert mesh polygons into numpy only if all polygons are equal in number of vertices.

There is alternative format which can be used but handling meshes with such format will be handled with much difficulties.
https://github.com/nortikin/sverchok/issues/2761#issuecomment-593368676

Also using numpy for polygons does not have any advantages for the Mesh Viewer node. On the contrary it can slow down displaying the mesh.
https://github.com/nortikin/sverchok/issues/2767#issuecomment-588813388

So my conclusion is it will better to convert only vertices to numpy arrays but edges and faces should be treated like Python objects. It will let keep balance between code complexity and performance I hope.

**Comment by nortikin** [comment]
@zeffii proposed slicable flat array from two pieces:
[(3,4,6,6,5,6,4),array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17....])]
where first part is number of items to slice and result:
[[1,2,3],[4,5,6,7],[8,9,10,11,12,13],[14,15,16,17,18,19]...]
