### ISSUE TITLE
Is "attrs socket" of Viewer Draw MK3 vectorized?

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3613]
Is there a way to pass different colors per object element in the "attrs socket"? 
For example I have 3 squares plugged in one "Viewer Draw MK3" node, and I want to plug 3 different edge_colors per object, so that I can get red, green and blue square in the viewport.

![viewer_draw_vectorized_colors](https://user-images.githubusercontent.com/66558924/95011186-92c0aa00-0637-11eb-9205-308c5ba5a276.jpg)

Thanks

**Comment by vicdoval** [comment]
Sorry but by the moment is not possible to pass different colors to the Viewer Draw. I will try to implement that feature soon.

**Comment by nortikin** [comment]
maybe than when placing new viewer draw we can create individual random colors for it?
```python
RGBA:
color_faces = ( random(0.5 , 1.0) , random(0.5 , 1.0) , random(0.5 , 1.0) , 1.0 )
color_edges = color_faces - (0.1 , 0.1 , 0.1 , 0)
color_vertices = color_faces - (0.2 , 0.2 , 0.2 , 0)
```

**Comment by vicdoval** [comment]
@nortikin I was thinking to follow the same idea of the viewer 2D that can receive color from input, use color per object or per vertex and use vertex color for edges and polygons

**Comment by nortikin** [comment]
> @nortikin I was thinking to follow the same idea of the viewer 2D that can receive color from input, use color per object or per vertex and use vertex color for edges and polygons

![изображение](https://user-images.githubusercontent.com/5783432/95308400-85ebc280-0892-11eb-89a1-7d3cc996aa20.png)
like this but vectorized?

**Comment by vicdoval** [comment]
Done in #3630

**Comment by rendetto** [comment]
Thank you so much! :)
