### ISSUE TITLE
Last 2 Updates breaks sverchok ....

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3614]
<img width="794" alt="Screen Shot 2020-10-06 at 12 10 44 am" src="https://user-images.githubusercontent.com/3952687/95083557-6ce6f280-0768-11eb-85bd-bf9afcb77ead.png">

Last update broke sverchok totally. And reinstalling also failed.

**Comment by enzyme69** [comment]
Never mind...

**Comment by portnov** [comment]
What was it? Describing the problem may help people if they encounter similar situation in future.

**Comment by Durman** [comment]
I think it's just mean that Blender should be rebooted after Sverchok updating.
