### ISSUE TITLE
List Join Behaviour 

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3615]
Imagine you want to add one vertex at the end of each vertex list.

![image](https://user-images.githubusercontent.com/10011941/95104875-a69f0580-0736-11eb-8f56-b4961be479c8.png)

This is probably possible with a set of nodes... but would be more natural that it could be done with just one the List Join node?

Proposed change:
When joining lists for example at Level 2 the Level 1 will be matched by the node joining only the Level 2 outputting in the example exposed 10 lists with 3 vertices.

**Comment by rendetto** [comment]
Will this change be compatible with the "List Join" we already use?

**Comment by vicdoval** [comment]
I will create a new version of the node to avoid breaking any layout. The actual node when you join level 2 you are forced to join also level 1. To replicate that behaviour 2 list join nodes will be needed. One for each level.

**Comment by nortikin** [comment]
list insert

**Comment by nortikin** [comment]
list join with mix flag?

**Comment by Durman** [comment]
What result would be expected if `Join levels list` = 2?
![2020-10-06_08-27-43](https://user-images.githubusercontent.com/28003269/95158908-d2a99d80-07ad-11eb-89e9-61bdc5601f19.png)

**Comment by portnov** [comment]
I'd suggest to add an option to the node, so that by default it's behaviour does not change.

**Comment by nortikin** [comment]
united list obvious

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/95305107-373c2980-088e-11eb-821d-fc7d1f0941fe.png)

**Comment by vicdoval** [comment]
Thanks for your feedback 👍  I added it as an option as @portnov  suggested.
You can see in the #3621 examples what new posibilites brings to list joining world 😃
