### ISSUE TITLE
Suggestions for improving node layout for node inputs with string properties?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3617]
In reference to: https://github.com/ladybug-tools/ladybug-blender/issues/14 - any ideas / suggestions on approaches to tackle this? What options does the bpy nodes api have to improve this situation? And is there something that Sverchok should set as default in its SverchokNodeItem class to improve it for all Sverchok nodes?

![](https://user-images.githubusercontent.com/61344631/95014503-b4c22880-0647-11eb-985b-109c01f55b38.JPG)

**Comment by Durman** [comment]
It is possible add method to a node which will be responsible for drawing socket layout.

```Python

calss Node:
    def draw_socket(self, socket, context, layout):
        layout.label(text="Test")

    def sv_init(self, context):
        scoket = self.inputs.new('SocketType', 'socket_name')
        socket.custom_draw = 'draw_socket'
```

https://github.com/nortikin/sverchok/blob/b2bc1765444f60b39cf4a66a226732e9347e11b6/core/sockets.py#L190-L197

Within this method you can use all Blender API and draw whatever you like.

https://docs.blender.org/api/current/bpy.types.UILayout.html

**Comment by Durman** [comment]
Or probably better way is to create separate socket type.
```Python
class SvLBSocket(NodeSocket, SvSocketCommon):
    bl_idname = "SvLBSocket"
    bl_label = "LB Socket"

    color = (0.6, 1.0, 0.6, 1.0)

    default_property: bpy.props.StringProperty(update=process_from_socket)

    def draw_property(self, layout, prop_origin=None, prop_name=None):
        if prop_origin and prop_name:
            layout.prop(prop_origin, prop_name)
        elif self.use_prop:
            layot.label(test='TEST')

class Node:
    def sv_init(self, context):
        self.inputs.new('SvLBSocket', ' Socket_name').use_prop = True
```

**Comment by Moult** [comment]
Fantastic! Thanks @Durman that's exactly what I'm looking for!
