### ISSUE TITLE
"Standardise text nesting" #3565 broke a lot of my setups

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3618]
So lots of my files are broken now. 
Those use lots of strings with "Viewer Index +", "Note",  "Switcher" etc.
What can I do after those changes to fix them back on? 
Thanks

**Comment by vicdoval** [comment]
By the moment if you use `List Del Levels` after the Note  node and delete the level 1 everyrthing should be as  before. About the switcher and the viewer index i guess something has to be changed in the code...

**Comment by Moult** [comment]
I think `List Del Levels` does the opposite of what you're looking for. I think you need split text. See PR #3619.

**Comment by rendetto** [comment]
Yes, adding the "Text Split" node solved the problem. Waiting for it to be merged in "master" soon.
Thanks

**Comment by rendetto** [comment]
Just found this setup on https://vk.com/sverchok_b3d, which utilizes split() with "Formula+" node. It solved the problem I had, so I'm closing this issue.

![TextSplit_with_Formula](https://user-images.githubusercontent.com/66558924/103487615-63c0fc80-4e0f-11eb-9ad2-23b97bfe7c46.jpg)

Great thanks to the person who did this setup :)
