### ISSUE TITLE
Is it possible for extra nodes to append to Sverchok examples?

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#3620]
A Ladybug user is requesting if examples can be provided with Ladybug https://github.com/ladybug-tools/ladybug-blender/issues/19 - is it possible to append to the Sverchok examples menu?

**Comment by Durman** [comment]
You can add ladybug directory to `json examples` folder and add your examples in json format.

**Comment by Moult** [comment]
@Durman won't that show up for people who don't have Ladybug nodes installed, which may confuse users?

**Comment by Durman** [comment]
Is it impossible to add subfolder into `json examples` inside LB addon only?

**Comment by nortikin** [comment]
@Durman do you mean definition in __init__ that check for sverchok and copy jsons and set flag 'done' in props for future loading LB.

**Comment by Durman** [comment]
Did not meant any suggestion about implementation don't have ideas about that.

**Comment by vicdoval** [comment]
I have it ready, make a folder called 'json_examples' with the folders you need (the name of the folders will be me menu names) and the json files inside and I will make it work

**Comment by vicdoval** [comment]
> I have it ready, make a folder called 'json_examples' with the folders you need (the name of the folders will be me menu names) and the json files inside and I will make it work

This applies also to sverchok-extra if @portnov wants to add any examples
