### ISSUE TITLE
Impossible to save (unknown location)

### ISSUE THREAD

**Issue by luruke** [nortikin/sverchok#3622]
## Problem statement
![Screenshot 2020-10-08 at 11 51 03](https://user-images.githubusercontent.com/61326/95443232-a1230480-095c-11eb-8dbb-2cae4c66c7b1.png)

blender 2.90.1

## Sverchok version
latest commit

**Comment by vicdoval** [comment]
I can't reproduce error

**Comment by luruke** [comment]
I also tested with blender 2.82, but same error.
The machine is running MacOS catalina

**Comment by vicdoval** [comment]
The file path node should point to the output folder.
Also try updating the nodetree (F5 or changing any value in the nodetree)

**Comment by luruke** [comment]
tried another machine, same problem:
<img width="853" alt="Screenshot 2020-10-08 at 22 24 24" src="https://user-images.githubusercontent.com/61326/95509658-102c4780-09b5-11eb-9056-1cd00253a8b6.png">

The file path is indeed a folder (in the previous screenshot i tried to give a filename, but that didn't worked as well)

**Comment by vicdoval** [comment]
You need to input a Vector for the center and a Fill/Stroke SVG node for the Fill stroke input:
![image](https://user-images.githubusercontent.com/10011941/95515379-ceec6580-09bd-11eb-92bd-3e5d9b6e38fa.png)

**Comment by luruke** [comment]
Thanks @vicdoval , indeed Fill/Stroke missing was causing the issue!

If i might suggest would be great to improve error message
