### ISSUE TITLE
Multy Cache and KDTree Find Nearest

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3623]
I am trying to find a way to loop and cache "Find Nearest N" using SV nodes. Is this something that's already possible or not really?

<img width="1011" alt="Screen Shot 2020-10-08 at 9 17 00 pm" src="https://user-images.githubusercontent.com/3952687/95446270-ca1eb600-09ab-11eb-90d2-53aa826516ca.png">

[cache_thing_001.blend.zip](https://github.com/nortikin/sverchok/files/5347098/cache_thing_001.blend.zip)

**Comment by vicdoval** [comment]
Could you explain it with more detail?

**Comment by enzyme69** [comment]
Let say I have point cloud. And I pick random points, and I want to find nearest points and grow it as cache via "looping", a bit like dynamic paint.

**Comment by vicdoval** [comment]
I was trying but did not get to anything, the problem i had is that the when the nearest to A is B is probable that the nearest to B is A... so selected items have to be removed... anyway i don't think `Multi Cache` node can help in this task...
