### ISSUE TITLE
Mesh occluding SVG exporter

### ISSUE THREAD

**Issue by luruke** [nortikin/sverchok#3631]
Hello,
sorry if this is not the right place to ask question, but I have searched thoroughly on documentation and forum before posting here.

I have the following nodes:

<img width="724" alt="Screenshot 2020-10-10 at 17 55 21" src="https://user-images.githubusercontent.com/61326/95659502-cf057600-0b21-11eb-8392-6ddd0d567098.png">

That produce the following SVG:
<img width="656" alt="Screenshot 2020-10-10 at 17 55 18" src="https://user-images.githubusercontent.com/61326/95659510-d593ed80-0b21-11eb-9bd1-efee487ea60c.png">

So far everything works great.

I would like to occlude vertices to achieve this:

<img width="579" alt="Screenshot 2020-10-10 at 17 58 05" src="https://user-images.githubusercontent.com/61326/95659561-33283a00-0b22-11eb-8a37-2bb8ac48f410.png">

I can get that result having a white fill, but It would still have `<line>` all drawn behind (which leads to a bigger file)

**Comment by luruke** [comment]
Maybe I can achieve that using a Raycaster node? Or is there a better way?

**Comment by vicdoval** [comment]
Hi @luruke 
You can try to build a workaround with the raycaster node but you may find issues with the edges/polygons that are partially hidden...
I would recommend to use the FreeStyle SVG Exporter addon for this task, I think it uses some kind of raytracing algorithm to generate the data

**Comment by luruke** [comment]
Thanks @vicdoval, closing.
