### ISSUE TITLE
Objects in / Objects in Lite - object rename

### ISSUE THREAD

**Issue by ppaawweeuu** [nortikin/sverchok#3634]
## Problem statement

Objects in and Objects in Lite nodes do not react/update after objects renaming. Other nodes (with object selecting) work fine.

![objects](https://user-images.githubusercontent.com/61344631/95665472-c5dfcd80-0b50-11eb-89b1-b21ac7229ec5.JPG)

## Sverchok version

Win7, sv 0.6.0.0

**Comment by vicdoval** [comment]
You are right, no that long ago none of the SV nodes reacted to name changing.
This feature (a pointer property) was never implemented in Objects In node.
Objects In Lite keeps in memory a copy of the object so it does not react to any kind of changes...
If you need to ensure connection after renaming you can use Object ID Out node
![image](https://user-images.githubusercontent.com/10011941/95665775-b57d2200-0b53-11eb-8ff8-b988e663f530.png)
