### ISSUE TITLE
"Extrude Face (Solid)" contour curves issue

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3635]
The wires of the cap face got an offset. This issue is present when "NURBS Output" option (for "Solid Faces (Surfaces)" and also "Solid Edges (Curves)" nodes) is set to "on".

![Solid_Extrude_NURBS_Wire_Issue](https://user-images.githubusercontent.com/66558924/95680834-f2ddc000-0be4-11eb-8eed-b249af0972b2.jpg)

**Comment by portnov** [comment]
Should be fixed, please check.

**Comment by rendetto** [comment]
Yes, it's fixed!
Thanks a lot!
