### ISSUE TITLE
Spreadsheet functionality

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3639]
I'm not sure how exactly useful these things are, so at the moment I've put them to sverchok-extra master. These nodes do not require any dependencies; they can be easily moved to Sverchok, the only question is do we need them.

### "Data Item" node.

This is similar to `dictionary Out" node, but adopted to work with nested dictionaries. In node UI you select a "path" in the nested dictionary, and the node outputs the item. For example, you can calculate something like `my_dict['Boxes']['MyBox']['Width']`.

![Screenshot_20201011_221322](https://user-images.githubusercontent.com/284644/95685056-00a83b00-0c0f-11eb-86a2-02cad04b9da5.png)

Or, for one (not more than one) of the nested keys you can say "All keys", this will be something like `my_dict[*]['Width']` or `my_dict['Box1'][*]`:

![Screenshot_20201011_221423](https://user-images.githubusercontent.com/284644/95685107-495ff400-0c0f-11eb-90da-8ba0b62b2eb6.png)

### "Spreadsheet" node.

This is more cumbersome. It allows you to input data in spreadsheet-like interface. Each row ("item") has user-provided name, and each column also. Columns to be used are configured in the N panel of the node. Supported types of columns are: integer, float, vector, boolean, string and formula. Most interesting is, off course, `formula`. It gives a possibility to do calculations in a way similar to LibreOffice or Excel (without aggregation functions). Python syntax is used, as usual in Sverchok. You can refer to other cells of the same spreadsheet as `RowName.ColumnName`. You can refer to other columns of the same row just as `ColumnName`. Special input socket named `Input` is supported for nested dictionaries input (e.g. you can plug another spreadsheet here); you can refer to items of that dictionary as `Input.RowName.ColumnName`. Any other variables (apart from well-known functions such as `sin` or `pi`) will automatically become additional inputs of the Spreadsheet node.

The node can output data in several ways:
* Dictionaries: `Data` output for nested dictionary, `Rows` output for RowName -> List of values in this row, and `Columns` for ColumnName -> List of values in that column.
* By row: a separate output for each row, with list of values in that row.
* By column: a separate output for each column, with list of values in that column.

![Screenshot_20201011_223706](https://user-images.githubusercontent.com/284644/95685618-54685380-0c12-11eb-8b56-17fb16a7725a.png)

**Comment by vicdoval** [comment]
Seems very powerful, allows a not nodal behaviour in a nodal environment... also seems a bit confusing.. How did you create the "Center" item in the Center column?
Anyhow we have a Dictionary Category in the menu with only two nodes so it wouldn't harm to have more... so I would say yes to bringing this functionalities to Sverchok

**Comment by portnov** [comment]
Columns are configured in the N panel:
![Screenshot_20201011_233426](https://user-images.githubusercontent.com/284644/95686965-51716100-0c1a-11eb-83a2-85b72cc2bdb7.png)

**Comment by Durman** [comment]
When I was testing dictionaries I did not like node tree results they was too noddy. `Data items` nodes would definitely improve the situation but I think it will still require too much work of creating and linking nodes. Optimal solution could be create sockets right in nodes which should process the data.
Example how this could look like.
![add sockets](https://user-images.githubusercontent.com/28003269/95706126-10ec0480-0c67-11eb-8f08-d19458e48c1c.gif)

**Comment by portnov** [comment]
Well, the problem I tried to address is the following. I noted that every non-trivial node tree consists of the following blocks:
1. Input parameters. 5-10 "A Number", "Vector In" or similar nodes.
2. Parameters calculations. 15+ "scalar math", "vector in", "vector math", "formula" nodes, that calculate some values based on input parameters. Width of this should be equal to width of that plus radius of that, X coordinate of this should be half of depth of that, and so on, tons of it.
3. Geometry generation. 5-10 nodes that create meshes or solids with inputs linked from parts 1 and/or 2.
4. Geometry processing. 5-10 nodes that modify (and/or multiply) geometry taken from part 3, like adding fillets, doing booleans, extrusions and so on. Input sockets are again linked from parts 1 and/or 2.
5. Outputs. 1-2-3 nodes like "viewer draw", "solid to mesh" or similar.

In my trees, the most complex, most "noddy" parts are 1 and 2, there are a lot of links between nodes there also. So I thought maybe it is possible to place such inputs and calculations into several spreadsheets. I did not manage to develop a good workflow, how should one usually use spreadsheets to replace or simplify parts 1 or 2. It is obviously possible, but I'm not sure how to do it in the best way.

**Comment by Durman** [comment]
Just made an example how this could be simplified with node groups. It does not cover all functionality.
![2020-10-12_11-32-42](https://user-images.githubusercontent.com/28003269/95717942-ca0a0900-0c7e-11eb-8450-7fd6cdb7bec5.png)

**Comment by portnov** [comment]
An example of what I'm talking about.
![Screenshot_20201012_192516](https://user-images.githubusercontent.com/284644/95758619-22162f00-0cc2-11eb-9831-f295e657edc0.png)

![Screenshot_20201012_193513](https://user-images.githubusercontent.com/284644/95758630-27737980-0cc2-11eb-9a0d-42b567aad0e9.png)

Here I marked geometry generators with green color, and "geometry modifiers" (like booleans and so on) are yellow. There are 10 input nodes framed in the left part. Collapsed nodes are instances of "scalar math", "vector in" and so on. As you can see there is a lot of them, and they create a mess of node links. If we could somehow simplify such setups it would be good.

One technology that Sverchok already has for it is "wifi nodes", they can help to make more clean layouts. I even have a draft of code somewhere that helps to create such nodes faster...

**Comment by Durman** [comment]
I'm quite suspicious about wifi nodes. How all output wifi nodes can be identified in a tree? If there are hundreds of nodes in a tree it will be quite difficult task.With links there is no such problem.
Also it is not necessary to place all `A number` nodes in left side of the tree. It is possible to combine them in 3D panel where they can be easily organized.

**Comment by portnov** [comment]
Yep, it's not necessary, just looks better (imho). Btw, maybe it worth to show the same panel in the N panel of node editor? Maybe even with option: to display all input nodes or just those marked with "to_3d".

**Comment by Durman** [comment]
Why not but renaming should be done in this case I think. The panel should be renamed to something like `Properties set` and property should be named `to prop set`. But it can't be done easily because 3d panel shows properties of all trees but in N panel most likely we would like to have properties only current tree.

**Comment by nortikin** [comment]
`to 3d` is shortest and informative name. maybe `to 3d panel`

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/95779773-4fb7a400-0cd3-11eb-9236-254180341e67.png)

**Comment by nortikin** [comment]
do you have `exec` function after `compile`?
```python
                if formula and isinstance(formula, str):
                    result[row_name][col_name] = sv_compile(formula)
    return result
```

**Comment by portnov** [comment]
It understands expressions only, not statements. You can do `5 if condition else 3`, but not `if condition: statement else: ..`.

**Comment by nortikin** [comment]
oh, i see, it cannot get own props, so if i add boolean to check it in formula it not get it

**Comment by nortikin** [comment]
i see now

**Comment by vkter** [comment]
This is a very useful node. Without it, combined data will be a disaster
![image](https://user-images.githubusercontent.com/74725748/203072999-61f83ed7-c052-44bb-ba9c-6afdb44c1bdf.png)

**Comment by vkter** [comment]
I know, but it's better to move it to sverchok
![屏幕截图 2022-11-22 073417](https://user-images.githubusercontent.com/74725748/203179392-f5f3c2a7-96e8-4ead-8a97-0e753fc33ee5.png)

**Comment by vkter** [comment]
sverchok should integrate this common node, which is frequently used

**Comment by vkter** [comment]
sverchok should integrate this common node, which is frequently used
