### ISSUE TITLE
The "Bake all" button doesn't work"

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#3645]
## Problem statement

After the latest updates, the "Bake all" button stopped working"

## Steps to reproduce

1. Correct the error

## Expected result

Bug fix

## Sverchok version

Blender 2.90.1, Sverchok: installation from sverchok-master.zip release from 01.10.20 + updates over the network.

**Comment by vicdoval** [comment]
@maxim1967 you need to update the viewer draw  nodes to the new version

**Comment by maxim1967** [comment]
Please explain that I am updating via "Check for updates" after the latest updates, the "Bake all"button stopped working.
Поясните, я делаю обновление через "Check for updates" вот после последних обновлений и перестала работать кнопка  "Bake all".

**Comment by maxim1967** [comment]
@Durman My file contains exactly this line
Мой файл содержит именно эту строку

**Comment by maxim1967** [comment]
And besides, on one of the computers I completely reinstalled Sverchok from the release from 13.10.20 and this also did not help.
Да к тому же на одном из компьютеров я полностью переустановил Sverchok из релиза от 13.10.20 и это тоже не помогло.

**Comment by vicdoval** [comment]
I suppose your nodetree is from before 13.10.20. You have to replace every `Viewer Draw`  node with the new `Viewer Draw`, you can do it using the right-click menu of the old viewer draw. Both are supported but only the new one works with the bake all operator

**Comment by maxim1967** [comment]
OK, replacing the old "Viewer Draw MK3" with the new "Viewer Draw MK4" fixed everything. Thanks to the request is closed.
