### ISSUE TITLE
"Build NURBS Curve" (FreeCAD) tangents out error

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3651]
FreeCAD curve implementation gives this error on tangents : AttributeError: 'tuple' object has no attribute 'x'

![FreeCAD_NURBS_Curve_Tangents_Issue](https://user-images.githubusercontent.com/66558924/96178151-a45b5900-0f37-11eb-8b30-402763586b87.jpg)

[FreeCAD_NURBS_Curve_Tangents_Issue.zip](https://github.com/nortikin/sverchok/files/5387390/FreeCAD_NURBS_Curve_Tangents_Issue.zip)

**Comment by portnov** [comment]
Should be fixed. Please check.

**Comment by rendetto** [comment]
The error is gone, but the results are very different from NativeSV and Geomdl.
I'm opening another issue: #3652

Thanks
