### ISSUE TITLE
"Evaluate Curve" node outputs weird FreeCAD tangents values

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3652]
FreeCAD curve tangents output differs from SV and Geomdl

![FreeCAD_NURBS_Curve_Tangents_Issue2](https://user-images.githubusercontent.com/66558924/96193228-67e82700-0f50-11eb-90cf-f3f129ea7720.jpg)

This is the test file I'm using:
[FreeCAD_NURBS_Curve_Tangents_Issue2.zip](https://github.com/nortikin/sverchok/files/5388257/FreeCAD_NURBS_Curve_Tangents_Issue2.zip)

**Comment by portnov** [comment]
I suspect they are just not normalized...

**Comment by rendetto** [comment]
You seem right, because the direction looks the same, although after a normalize the values doesn't change (weird?)

![FreeCAD_NURBS_Curve_NormalizeTangents](https://user-images.githubusercontent.com/66558924/96237647-3d28bd80-0fa6-11eb-94b4-b4f5de9bce5b.jpg)

The other thing I found is with the Curvature and Torsion values. Again FreeCAD differs from other implementations.
![FreeCAD_NURBS_Curve_Properties_Issues](https://user-images.githubusercontent.com/66558924/96237718-4fa2f700-0fa6-11eb-9b38-8c80abc3af7c.jpg)

Here's the file: 
[FreeCAD_NURBS_Curve_Issues.zip](https://github.com/nortikin/sverchok/files/5390413/FreeCAD_NURBS_Curve_Issues.zip)

**Comment by rendetto** [comment]
Also normals and binormals have slight differences at T=0.0 and T=1.0
![FreeCAD_NURBS_Curve_Properties_Issues_Frame](https://user-images.githubusercontent.com/66558924/96245798-69493c00-0fb0-11eb-8ea0-2d3cf1ae9924.jpg)

Test file updated: 
[FreeCAD_NURBS_Curve_Issues.zip](https://github.com/nortikin/sverchok/files/5390788/FreeCAD_NURBS_Curve_Issues.zip)

**Comment by rendetto** [comment]
A small off-topic: 
I just checked the surfaces(normals, tangents, curvatures) and there are no such problems.

**Comment by rendetto** [comment]
Just checked the test file I did, and none of the above issues are solved.

**Comment by rendetto** [comment]
A small update here. 
It appears that FreeCAD tangent vectors are in fact OK. FreeCAD tangents are normalized by default in oppose to Geomdl and Sverchok ones. That explains why, when I normalized a FreeCAD tangent, its value didn't change. 
![FreeCAD_Tangents](https://user-images.githubusercontent.com/66558924/103212939-e419c600-4914-11eb-9786-f06d59b1abce.jpg)

Still no clue why curvature and torsion are so different.
@portnov I guess we can close this issue and open one specifically for Curve Frame output?

**Comment by rendetto** [comment]
Closing this issue and opened one for Curve Curvature #3804
