### ISSUE TITLE
Extrude node produces wrong mask

### ISSUE THREAD

**Issue by hitrpr** [nortikin/sverchok#3653]
## Problem statement
as subject said

## Steps to reproduce
Here file  with nodes
[extrude wrong mask.blend1.gz](https://github.com/nortikin/sverchok/files/5395655/extrude.wrong.mask.blend1.gz)

## Expected result
As I expect, node should mask unextruded geometry (or all new), anyway it should separate new and old.

## Actual result
Mask destribution is wrong
Red is mask for extruded plane.
![54624742](https://user-images.githubusercontent.com/21099918/96337393-8274ea00-108f-11eb-9931-8573fb91353c.png)

## Sverchok version
0.6.0

**Comment by vicdoval** [comment]
Hi @hitrpr 
As stated in the [documentation](http://nikitron.cc.ua/sverch/html/nodes/modifier_change/extrude_region.html) the outputted mask is a face mask, not a vertices mask, if you wish to transform it to a vertices mask use the `Mask Converter Node`

**Comment by hitrpr** [comment]
Okay, sorry for disturbing.
Not obvious, because «mask» inputs and oitputs everywhere.
FaceMask instead Mask will be muche clearer.
