### ISSUE TITLE
Annoyng Rclick-menu behavior

### ISSUE THREAD

**Issue by hitrpr** [nortikin/sverchok#3654]
## Problem statement

It appears with Decline (Rclick)

## Steps to reproduce
1. Shift A,
2.  add node, without click/confirm
3. Decline with Rclick.

## Expected result
1st Rclick to decline and 2nd  (on free space) to call context menu.
Solution is easy: change «release» to press/click here
![54632751](https://user-images.githubusercontent.com/21099918/96337540-aab11880-1090-11eb-982f-5766348e0ec0.png)

## Actual result
Context menu appears immediately with decline action.

## Sverchok version
0.6.0

**Comment by vicdoval** [comment]
When changing the value to "click" or "press" as you suggest generates another even more annoying behaviour: 
Node Right-Click menu does not appear if the node you are over is the active node...

**Comment by hitrpr** [comment]
With release option and   drag-RClick I see another menu:
![54644633](https://user-images.githubusercontent.com/21099918/96339694-01255380-109f-11eb-9342-9184c2c1a0d3.png)
Node jumps back and menu appears over it.

When I changed to Click variant, i got Node context for right click everytime (with unselected node too)
![54652735](https://user-images.githubusercontent.com/21099918/96339777-5c574600-109f-11eb-8970-a884f6bd3f89.png)

And all it is bad anyway.

Expected: main rclick menu when nothing selected, with Rclick on free space; node context if node selecter or mouse pointer over node.

**Comment by vicdoval** [comment]
What os your OS?
Are you selecting with left-click or right-click on the 3d scene editor?

**Comment by hitrpr** [comment]
Win 7 home, left click select. Same behavior for 2.83.7 and 2.91.0

**Comment by hitrpr** [comment]
As I can see, there is one operator for both menus. So I can`t even set different hotkeys for 2 menus.

**Comment by hitrpr** [comment]
short video
[2020-10-17_18-42-05.mp4.gz](https://github.com/nortikin/sverchok/files/5395961/2020-10-17_18-42-05.mp4.gz)

**Comment by vicdoval** [comment]
I see, I think all the SV developers are right-click selectors so we did not face this problems...

**Comment by vicdoval** [comment]
We will try to fix it as soon as possible, for the moment i recommend you (and all left-click selectors) to switch it to Shift+Left Button release. Its not identical but its workable
![image](https://user-images.githubusercontent.com/10011941/96348785-92022c00-10ab-11eb-94a4-95af7a6a737c.png)

**Comment by vicdoval** [comment]
It seems a open bug from blender itself that the addons can't check if user is using right-click or left click in the moment of loading their keymaps... https://developer.blender.org/T59064

**Comment by vicdoval** [comment]
The problem with Shift + Left click is that overlaps with selecting multiple nodes so is probably better Alt+Left Click 
![image](https://user-images.githubusercontent.com/10011941/96364239-14d1c800-113a-11eb-9e6b-8b868f297fd4.png)
