### ISSUE TITLE
Solidify stops to update if bisect planes are out of shape.

### ISSUE THREAD

**Issue by hitrpr** [nortikin/sverchok#3655]
[видео, на русском, 1 минута](https://youtu.be/69dswzS71BQ)

Файл: 
[Solidify break.blend.gz](https://github.com/nortikin/sverchok/files/5395879/Solidify.break.blend.gz)

Try to change size and look what happens
![54662746](https://user-images.githubusercontent.com/21099918/96340013-d3d9a500-10a0-11eb-9711-5d5470ea0456.png)

Second soludify stop working, when bisect planes go out of box.

**Comment by Durman** [comment]
`Bisect` node generates empty objects and `solidify` can't handle them. For now it possible to remove empty objects with `fix empty objects` node.
![2020-10-17_19-26-40](https://user-images.githubusercontent.com/28003269/96346789-bf040e00-10ae-11eb-84d7-098038130968.png)

**Comment by hitrpr** [comment]
@Durman thank you, it helped!

**Comment by vicdoval** [comment]
Another hint:
If you don't enable Sverchok in the "Filter Addons" menu the Svechok nodes menu looks worse and you miss the sverchok menu in the n-panel with some nice options 
![image](https://user-images.githubusercontent.com/10011941/96347005-2e720180-109f-11eb-9276-190a393008f8.png)
