### ISSUE TITLE
Second nodegroup (monad) outputs result from 1st

### ISSUE THREAD

**Issue by hitrpr** [nortikin/sverchok#3656]
## Problem statement

Two groups (monads) produces same output with different inputs

## Steps to reproduce
File, video
[Group bug.blend.gz](https://github.com/nortikin/sverchok/files/5396996/Group.bug.blend.gz)
[2020-10-18_05-40-27.mp4.gz](https://github.com/nortikin/sverchok/files/5396997/2020-10-18_05-40-27.mp4.gz)

## Expected result
As shadernodes, they should operate with inputs and produce different results.

## Actual result

What did you actually get?

## Sverchok version
0.6.0.0

**Comment by Durman** [comment]
I would not recommend using monads. They are quite buggy and nobody as far as I know is going to improve them. I'm developing `node groups` which I hope will replace monad one day but it will take time.

**Comment by hitrpr** [comment]
Okay, I see. Will wait groups!
