### ISSUE TITLE
RandomVectorNodeMK3 vectorization

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3662]
## Problem statement

https://github.com/nortikin/sverchok/blob/f7bfa94ba6532b6b15687b770eb9f52bc85e68e3/nodes/generator/random_vector_mk3.py#L74-L76

**Comment by vicdoval** [comment]
What would you expect? if you input [[3,3]] in the count you get two sets of three points (Level 3) if the node accepted [[3,3],[3,3]] it would output a Level 4 list or it would need to flatten it to 4 lists of 3 vectors.

Maybe is not that bad idea but right now is the same behaviour as all the generators....

**Comment by Durman** [comment]
Yes I forgot about this generators feature
