### ISSUE TITLE
Frame info : Evaluate

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#3663]
frame info : Evaluate
it generate 0.0 only when start frame = 0
if start frame not 0 result not 0.0-1.0
![2145](https://user-images.githubusercontent.com/32074126/96723322-a2cade80-13d8-11eb-8cb2-2942c51b96ce.PNG)
thank you.

**Comment by Durman** [comment]
agree
![2020-10-21_18-55-29](https://user-images.githubusercontent.com/28003269/96737714-04864b00-13cf-11eb-8888-1a7160d872b6.png)

**Comment by zeffii** [comment]
```python
(frame_number - frame_start) / (frame_end - frame_start - 1)
```
