### ISSUE TITLE
enabling sverchok in Blender 2.92

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#3665]
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\test_blenders\current_28\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'
```

i don't know if this is a recent sverchok bug, ( as would appear from this user's experience:  [post 1](https://blenderartists.org/t/wip-sverchok-parametric-nodes-for-architects/557250/2515?u=zeffii) and [post 2](https://blenderartists.org/t/wip-sverchok-parametric-nodes-for-architects/557250/2516?u=zeffii)  )  or if it's something else.  maybe we should find an alternative for 
```
if __name__ != "sverchok":
    sys.modules["sverchok"] = sys.modules[__name__]
```

**Comment by Durman** [comment]
How it works in AN
https://github.com/JacquesLucke/animation_nodes/blob/2584786a2f20e92853ebba3e59c71388fc30de10/animation_nodes/__init__.py#L48-L52

**Comment by zeffii** [comment]
we didn't want to do that.. but yes, that's the alternative..  I would still prefer an automated solution.

**Comment by zeffii** [comment]
the problem might not be that .. 

because my own sverchok folder is named exactly `sverchok`, and i can enable it doing 
```python
bpy.ops.preferences.addon_enable(module="sverchok")
```

**Comment by Durman** [comment]
> side note: notice it's continuing to draw even after the node is disconnected

It's new feature

**Comment by zeffii** [comment]
new interesting warning on Blender startup
```
C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\settings.py:15: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
```

**Comment by Durman** [comment]
https://github.com/nortikin/sverchok/issues/3646#issuecomment-718354342
