### ISSUE TITLE
How to color object instances

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3667]
How can I use the Object instances node to color each instance with a different color, color being determined also via sverchock nodes?

I’m basically replicating an image plane at some random 3D locations.. and I want the images to fade to black based on distance along z for instance.

See my setup below (which doesn’t work obviously). I use the **ObjectIntancer** to replicate a **star** (simple plane with a “star” image material) and use the VertexColor node to generate a vertex color for each replicated object. Then, in the “star” material I multiply the svCol output by VertexColor node to multiply with the star image to accomplish the fade effect. My assumption is that the svCol is generated per object, and the one “star” material attached to each instance of the star plane would have a different svCol value.. hence each instance would have a different value to multiply with the star image. This of course doesn’t work, which is I suspect due to my lack of understanding of how materials / vertex colors and sverkchock work together. 

Any hints on how to fix this setup.. or perhaps recommend a different approach to accomplish the same effect much appreciated. :)

<img width="1680" alt="Screen Shot 2020-10-22 at 4 07 05 PM" src="https://user-images.githubusercontent.com/2083719/96924477-b3369400-1480-11eb-9a1e-7a06749d6c59.png">

**Comment by Durman** [comment]
Object instacer node generates objects and each object shares the same mesh. Vertex colors apply to mesh data block. In your example you apply vertex color 1300 times to the same mesh. You probably should use mesh viewer instead or use Z coordinate of objects in shader editor.

**Comment by vicdoval** [comment]
The good part of instances is the performance :)
You can pass the minimum and maximum Z values with the Set property node:
![image](https://user-images.githubusercontent.com/10011941/97024521-31fe0080-1557-11eb-8146-404be47f4284.png)

**Comment by DolphinDream** [comment]
I also found a way to use the **object.color** to set in SV and read within the material node tree and feed into the mix node.

Yeah, the reason why I went with instancing is to make sure it can have high performance so I can do a real time animation in the viewport (at 25fps) with lots of stars without having to render to see the animation. (animation being in my case simply moving through the stars and create a seamless loop).

**Comment by DolphinDream** [comment]
Btw, one thing that kind of puzzled me is why the linear gradient looks like it’s dark (close to black) only very close to the end of the range, but white spreads over a much larger range. I wonder if this is an eye/perception of grayscale thing.

**Comment by vicdoval** [comment]
I think that is why "gamma correction" is used https://en.wikipedia.org/wiki/Gamma_correction
