### ISSUE TITLE
Note Node Problem

### ISSUE THREAD

**Issue by summereasy** [nortikin/sverchok#3670]
## Problem statement

Dear fellows from Sverchok, this is the first time I report an issue here. After playing with this addon, I think I must show some gratitude -- it is so amazing and somewhat addictive :D. Thanks to all ya great fellows!

The problem is from the **Note Node**
I've read the menu and I think it should convert custom text to format naming indices. But all I've got is the same text line I've input.

**OS Version** : OSX
**Blender Version** : 2.90
**Sverchok Version**: 0.6.0.0 `I think my last checked in is just yesterday`

## Steps to reproduce
Just connect the **Note** node to a **Stethoscope**
![sverchok_note_issue](https://user-images.githubusercontent.com/51897649/97068584-64f9d000-15fb-11eb-9365-854c91ccfc6f.png)

**Comment by rendetto** [comment]
I think you'll need this #3619. Unfortunately it's not in master yet, but you can add it manually.

Cheers

**Comment by summereasy** [comment]
Oh yeah, it worked. Many thanks!
Thanks for the tip!
