### ISSUE TITLE
Post install pip upgrade and lib installs not working on win 10

### ISSUE THREAD

**Issue by rofoto** [nortikin/sverchok#3672]
## Problem statement

I assume this is a windows 10 specific issue

After trying a fresh install on both 2.83.3 and 2.90.1.

on **2.83.3** 
pip will not update and the message
"You should consider upgrading via the 'python -m pip install --upgrade pip' command."

on **2.90.1**
 It seems to update pip and pip install libs but after restarting blender they do not
show as installed and the libs cannot be accessed in the python window of the scripting workspace. 

I have tried to do this process with both user and admin rights. both produce the same result. 

## Steps to reproduce

1. install blender 
2. download and install Sverchok -master from git 
3. restart blender to confirm the install
4. from the Sverchok addon info panel in preferences->addons click the update pip button
5. restart blender to confirm the install  

## Expected result

What did you expect to see as a result of those steps?

Pip to be upgraded and pip install libs to install and the panel to register the updates 

## Actual result

What did you actually get?
nothing, no change at all

## Sverchok version

sverchok-master.zip from github  version listed in blender is 0.6.0.0

**Comment by portnov** [comment]
Please try running blender under administrator account. Will it help?

**Comment by zeffii** [comment]
for windows I had a similar problem, resolved by removing pip - explained here https://github.com/nortikin/sverchok/issues/3500#issuecomment-693544492

**Comment by rofoto** [comment]
> Please try running blender under administrator account. Will it help?

I tried that with no difference in results

**Comment by rofoto** [comment]
> for windows I had a similar problem, resolved by removing pip - explained here [#3500 (comment)](https://github.com/nortikin/sverchok/issues/3500#issuecomment-693544492)

Thanks for the tip. 

I tried this and it did not change anything

below are 3 screen shots, 

the first is after using the addon window to "install" scipy and being told it was successful. indicated by the lower right of the window

the second is the blender screen after restarting showing that scipy is not installed ( or at least not installed in a way that sverchok can access it ) 

and the third is the console window after restart showing the same thing as the second screenshot

![Blender_2 90 1_sverchok_scipy](https://user-images.githubusercontent.com/13305754/97121357-91772e80-1758-11eb-9804-54aa31fa4b27.png)
![Blender_2 90 1_sverchok_scipy_post_restart](https://user-images.githubusercontent.com/13305754/97121361-976d0f80-1758-11eb-9f04-9c53a6b3205c.png)
![Blender_2 90 1_sverchok_scipy_post_restart_console](https://user-images.githubusercontent.com/13305754/97121364-9e941d80-1758-11eb-9328-20455e8e38b4.png)

**Comment by rofoto** [comment]
I have also tried to link to my anaconda python install 
sverchok sees the anaconda scipy package but gives the following error and does not install

`Modules Installed (sverchok-master) from 'C:\\Users\\USERNAME\\Downloads\\sverchok-master.zip' into 'C:\\Users\\USERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'
sv: import settings
geomdl package is not available, some NURBS related nodes will not be available
PyMCubes package is not available. PyMCubes-based implementation of Marching Cubes will not be available
Circlify package is not available. Circlify node will not be available
FreeCAD package is not available, Solids nodes will not be available
Dependencies available: pip, scipy, scikit-image, Cython.
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\__init__.py", line 73, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\core\__init__.py", line 108, in init_architecture
    import_settings(imported_modules, sv_name)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\core\__init__.py", line 89, in import_settings
    settings = importlib.import_module(".settings", sv_dir_name)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\settings.py", line 12, in <module>
    from sverchok.utils.sv_gist_tools import TOKEN_HELP_URL
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\utils\sv_gist_tools.py", line 29, in <module>
    from sverchok.utils.sv_requests import urlopen
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\sverchok-master\utils\sv_requests.py", line 10, in <module>
    import ssl
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.`

**Comment by rofoto** [comment]
I hope someone out there sees this. 

I had a question/speculation. 

What versions of scipy , geomdl, scikit-image and pyMcubes does sverchok need. Is it possible that it is actually installing but does not recognize the installs because they are the wrong versions? 

I ask this because after another attempt at forcing installs ( this time from within the blender scripting tab ) I was able to install Circlify and Cython but not any of the other libs 

code used to install below ( run from blender in win 10 with admin rights ) 

`import sys
import os
import subprocess

python_exe = os.path.join(sys.prefix, 'bin', 'python.exe')

subprocess.call([python_exe, "-m", "ensurepip"])
subprocess.call([python_exe, "-m", "pip", "install", "--upgrade", "pip"])

#app install

subprocess.call([python_exe, "-m", "pip", "install", "scipy"])
subprocess.call([python_exe, "-m", "pip", "install", "geomdl"])
subprocess.call([python_exe, "-m", "pip", "install", "scikit-image"])
subprocess.call([python_exe, "-m", "pip", "install", "pymcubes"])`

**Comment by portnov** [comment]
Sverchok does not explicitly check the versions of imported libraries. Any recent version should do.

What error messages are you getting now?

**Comment by portnov** [comment]
In the message above, it says
> Dependencies available: pip, scipy, scikit-image, Cython. 

So you have most interesting things installed. Following text seems to say that your installation of Blender does not have python's `ssl` module included. That's strange.

**Comment by rofoto** [comment]
> In the message above, it says
> 
> > Dependencies available: pip, scipy, scikit-image, Cython.
> 
> So you have most interesting things installed. Following text seems to say that your installation of Blender does not have python's `ssl` module included. That's strange.

I agree the ssl issues are strange, I wonder if the 3.7.7  version of python that 2.90.1 uses made some small changes to ssl that sverchok does not like. 

It also does not answer the question as to why sverchok would report that scipy and the other packages successfully install but still seem to not be accessible to blender or sverchok. 

 it is possible that this is a blender issue as doing 'import scipy' in blenders python console does not work even after a fresh install but it does work when using my anaconda python package. the anaconda package however still produces the same issues with sverchok, where it does not or can not see the scipy install. This leads me to believe that sverchok is either not doing something it should or is not able to do the right thing.

**Comment by portnov** [comment]
It is possible that you have scipy installed into your system-wide installation of python. In this case `pip` will say that it is installed, but Blender will not be able to import it. One idea in this case is to remove scipy from your system installation and then explicitly install it with blender's python. You can also study pip's documentation and try to say it explicitly that you want it to install scipy into blender's python, not use system-wide one. `--root` option looks similar, but I did not try personally.

**Comment by rofoto** [comment]
My anaconda python has scipy, but using blenders python, it does not. the issue seems to be that I cannot install scipy ( either within blender using the script I used above or doing the correct pip commands from within the command prompt inside windows 10. ) 

both do not work with sverchok and while I can bite the bullet and just go to linux, I would prefer to solve this problem for not only myself but also for all the other windows users who want to use sverchok in windows. 

BTW using --root with my anaconda install did not do anything, it still does not work.

**Comment by portnov** [comment]
Try to point --root at Blender's python directory.

**Comment by rofoto** [comment]
> Try to point --root at Blender's python directory.

Tried that from both blender and from the command line ( both with and without admin rights. )

output from command line using  the following command 
`C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin>python.exe -m pip install --root="C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin" scipy`

`Requirement already satisfied: numpy>=1.14.5 in c:\program files\blender foundation\blender 2.90\2.90\python\lib\site-packages (from scipy) (1.17.5)`

No change, both sverchok and blender do not see scipy when attempting import scipy.

**Comment by portnov** [comment]
Well, then the main idea is to uninstall scipy from your system's installation first.
(it should be possible to have them both, but I don't know how).

**Comment by rofoto** [comment]
> Well, then the main idea is to uninstall scipy from your system's installation first.
> (it should be possible to have them both, but I don't know how).

ok I found a solution

from the windows 10 command line with admin rights

`C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin>python.exe -m pip uninstall numpy scipy geomdl scikit-image pymcubes circlify cython`

`C:\Program Files\Blender Foundation\Blender 2.90\2.90\python\bin>python.exe -m pip install numpy scipy geomdl scikit-image pymcubes circlify cython`

this fixed the issues, now sverchok sees all the python packages that can be installed via pip

I do not think this is a good fix as users should not have to dive into the command line but it is something that seems to be a potential solution to the problem

Thank you for your guidance

**Comment by portnov** [comment]
There is FAQ section on the wiki page: https://github.com/nortikin/sverchok/wiki/Dependencies . Feel free to make the explanation more detailed.

**Comment by rofoto** [comment]
will do, Thanks again for you help.
