### ISSUE TITLE
Output mesh with Blender Modifier

### ISSUE THREAD

**Issue by JanFilipec** [nortikin/sverchok#3678]
Is there a way to output sverchok geometry into Blender with Blender modifiers? For example generating a simple mesh with subdivision modifier instead of aplying the modifier inside Sverchok and outputting the complex result?
I found this http://www.codeplastic.com/2019/02/16/sverchok-modifier/ but this only shows how to apply the modifiers directly inside Sverchok, not how to output them without applying them.
Or perhaps even the possibility of generating objects with other Blender properties?

**Comment by portnov** [comment]
For some cases, it is enough to
1) use Mesh Viewer node to generate Blender object; 
2) apply modifiers to generated object in a usual way, in Properties panel. By default, Mesh viewer does not re-create objects on tree update, so your modifiers stack will be preserved.

**Comment by Durman** [comment]
![2020-10-28_19-59-39](https://user-images.githubusercontent.com/28003269/97462432-2431ec00-1958-11eb-962a-65261ee8bdde.png)

**Comment by JanFilipec** [comment]
I am aware of this option, but I think that for the BIM workflow we'll need sooner or later the possibility to output objects with properties. 
See for example this:
https://community.osarch.org/uploads/editor/h9/idrhgejo8f34.gif
Here I used your method for the walls (created dummy mesh, added modifier, added the geometry I actually wanted to the dummy mesh to get the modifier) but already for the parametric windows it gets problematic.
Do you plan on adding this or is there perhaps a scriptable node way that could do this?

**Comment by vicdoval** [comment]
Check this old example of how to apply modifiers to a sverchok-generated object. It may help you https://github.com/nortikin/sverchok/issues/1872#issuecomment-348713137

**Comment by JanFilipec** [comment]
Brilliant, pretty much exactly what I needed. Thanks!
For anyone else interested, the simplest way to add a modifier to a blender mesh with SV would be "Exec Node" with something along the lines of:
```
strName = "SubD"
for ob in V1:
    ob.modifiers.new(type = "SUBSURF", name = strName)
```

![SV Add Modifier](https://user-images.githubusercontent.com/67052298/98237658-821c9000-1f65-11eb-8232-2f18da0f66d9.JPG)

**Comment by kevinsmia1939** [comment]
@JanFilipec 
Hi, do you know how to not make the subdiv modifier keeps stacking up everytime I change anything?

**Comment by JanFilipec** [comment]
If I remeber correctly I simply removed all old modifiers before adding the new one. But if you want to keep the existing values, you have to check for existing modifiers (by your unique name? Depends on your usecase really) and skip the adding step.
