### ISSUE TITLE
Nodevember 2020

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#3679]
Nodevember is coming. Everyone who has time is welcome to participate.

**Comment by Durman** [comment]
What are we suppose to do?

**Comment by portnov** [comment]
I'm not a big specialist myself :) It seems to be something like organized flashmob, when someone (https://nodevember.io/ ?) throws some themes, and everyone posts procedurally generated arts about this theme. Mostly for fun.

**Comment by nortikin** [comment]
it looks like it pass away already

**Comment by portnov** [comment]
I do not see that any registration is required. As far as I understand, you just look for "prompts" (topics), at https://twitter.com/nodevemberio I think? and then post related art wherever you want.

**Comment by nortikin** [comment]
hashtag and node tree screenshot adding is conditions

**Comment by portnov** [comment]
https://pbs.twimg.com/media/Elp8zeCXgAAKYu0

**Comment by portnov** [comment]
I think I saw a biscuit like this...
![Screenshot_20201101_111146](https://user-images.githubusercontent.com/284644/97796389-3bf8c100-1c33-11eb-85fe-14a60f761b38.png)
Does it count? :)

**Comment by enzyme69** [comment]
I like what you did with the center bits, lovely details!

Yes, so hashtag #nodevember and #nodevember2020 and send Tweet with render and node tree snapshot. We must show case everything SV can do.

**Comment by nortikin** [comment]
in vk page there are posts gathering nodevember2020 https://vk.com/wall-35076122_11705

**Comment by nortikin** [comment]
https://youtu.be/xnovNmGFac4 resume from me
