### ISSUE TITLE
SNlite  parameters are reset to default after saved file blender 2.91

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3681]
![image](https://user-images.githubusercontent.com/49908008/97704576-f1e8d180-1ab2-11eb-9ef9-6ee525acbc6d.png)
After saved file &  reopen the parameters are back to default settings for the scripted node lite 
Is there maybe a solution for to avoid this ?
![image](https://user-images.githubusercontent.com/49908008/97704762-455b1f80-1ab3-11eb-8832-64550422ffec.png)

TestFile : 

[000 sverchok divider mirror 02.zip](https://github.com/nortikin/sverchok/files/5465084/000.sverchok.divider.mirror.02.zip)

**Comment by zeffii** [comment]
that doesn't look great : /

**Comment by zeffii** [comment]
also happens in Blender 2.92,  @Durman   can you fix it?

**Comment by Durman** [comment]
Yes it's related with this #3511

**Comment by vicdoval** [comment]
@Durman also would be nice if it could accept 0 and 0.0 as a value for the default property

**Comment by Durman** [comment]
@vicdoval I can't guess the problem.

**Comment by vicdoval** [comment]
@Durman right now if you define the default as 0 the node does not create a property because it checks
`if default_value:` which returns false in case of 0 or 0.0

**Comment by Durman** [comment]
@vicdoval Should work now.

**Comment by BennyGovaerts** [comment]
Thanks for the Fix ,works fine
