### ISSUE TITLE
Request ; Smooth shade with option Auto smooth for example 30 On/off option 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3682]
Can this be done with sverchok in the future maybe ? 
![image](https://user-images.githubusercontent.com/49908008/97707462-9f5de400-1ab7-11eb-9fb3-e8a66107512e.png)

**Comment by vicdoval** [comment]
It would not be a bad idea, for the moment you can achieve it like this:
![image](https://user-images.githubusercontent.com/10011941/97783320-2b930880-1b97-11eb-9317-89d57c8b9497.png)

**Comment by Durman** [comment]
Also we could have our own auto smooth node which would generate vertices normals but in this case `MeshViewer` should have extra socket for them.

**Comment by Durman** [comment]
Now it's possible

![image](https://user-images.githubusercontent.com/28003269/181465100-c28d0974-07b7-4cb0-8e7e-8bc41b01e8ac.png)
