### ISSUE TITLE
Is this option removed https://github.com/nortikin/sverchok/pull/2534 ? 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3683]
With the new Mesh viewer this option is removed is there maybe a solution to add this back ? 
Is this option removed https://github.com/nortikin/sverchok/pull/2534 ?

**Comment by Durman** [comment]
![2020-10-30_19-29-14](https://user-images.githubusercontent.com/28003269/97724373-42c5ed80-1ae6-11eb-96d7-f13f4bf3914c.png)

**Comment by BennyGovaerts** [comment]
Hmm this is not the same like random vertex color

**Comment by zeffii** [comment]
if you are only rendering @BennyGovaerts  then the ShaderTree's own builtin random island colour feature should be sufficient. it's definitely faster than us using Python to find islands and product an associated vertex colours map (like my implementation for VertexColours you linked to).

**Comment by vicdoval** [comment]
Is not the same as one click button but gives you more control
![image](https://user-images.githubusercontent.com/10011941/97783046-73189500-1b95-11eb-9c1b-fdfbc729f841.png)

**Comment by Durman** [comment]
![random color](https://user-images.githubusercontent.com/28003269/97783506-4ff7e080-1ba9-11eb-9782-0e622243dcf0.gif)

**Comment by BennyGovaerts** [comment]
Thanks ,to everyone for  the excellent examples & solution
