### ISSUE TITLE
Normals to Rotation

### ISSUE THREAD

**Issue by dwizor** [nortikin/sverchok#3689]
Hello, i want orient hexagons on my torus based on torus vertex normals. In Animation Nodes it's done by "rotation to direction" node but i dont have idea how to archieve it in sverchok. I tried this setup which i found on internet but it gives me error. 

![obraz_2020-11-04_174426](https://user-images.githubusercontent.com/68112419/98140154-62358f80-1ec5-11eb-807e-d3858db4ce73.png)

**Comment by Durman** [comment]
![2020-11-04_21-25-43](https://user-images.githubusercontent.com/28003269/98145433-54dbcd80-1ee4-11eb-9967-8a90e6eb0d1f.png)

**Comment by dwizor** [comment]
Oh thanks, its wierdly i cant do this by compose matrice, why this error appears? Additionally I would ask if there is an option to move every second vertical row by some degree so that the hexagons match.

**Comment by portnov** [comment]
@dwizor , as a rule of thumb, you can't connect sockets of different types (sometimes you can, but that is more like exceptional cases). On your screen, you've connected number to "Scale" (which expects vector), and vector to "Angle" (which expects number). Also, please refer to documentation of nodes you are using. It is not always comprehensive, but usually contains examples of usage.

**Comment by dwizor** [comment]
Is there any way to convert normals to angle? Numbers to scale works perfectly

**Comment by portnov** [comment]
Normals to rotation matrix, you mean? You usually can use "Matrix Normal" node for that.

**Comment by dwizor** [comment]
Ok i need to be familiar with all these nodes ^^ I came with animation nodow and it seems simpler on them. Ok last question(sorry for so much). Is there any way to rotate every horizontal row of points on this torus from world origin? To make hexagonal patter match on this torus. In animation nodes i could make it by mask fallow or smth like that.

**Comment by Durman** [comment]
[untitled.zip](https://github.com/nortikin/sverchok/files/5491968/untitled.zip)
![2020-11-05_08-20-26](https://user-images.githubusercontent.com/28003269/98197339-f2181f80-1f3f-11eb-83e3-5aa54fcf59dd.png)

**Comment by vicdoval** [comment]
If what you want is a torus with a hexagonal topology you can use this trick: 
![image](https://user-images.githubusercontent.com/10011941/98221055-7920c400-1f4f-11eb-8ed4-3081204faa18.png)

**Comment by dwizor** [comment]
Thanks a lot guys! i see pretty nice community around this addon here. It's a pity so little tutorial can be found for it and its hard to learn. Anyway thanks for pretty cool ideas!
