### ISSUE TITLE
Randomly import and combine various mesh from a library using Object ID selector ?

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#3690]
Would Object ID selector be the proper node to :
- randomly pickup some mesh (let's say various body and heads) from a library
- combine them to create various monstrous combinations
- display those combinations more or less heavenly on a surface, let's say i want to present them on a cube
(i'm thinking of a grid but with some randomisation)

So my first problem is how to make sverchok import some of those elements from a library

**Comment by Durman** [comment]
I think you can use `object instancer` node which has input for arbitrary collection of objects. Objects can be putted into Sverchok with `objects in` node for example.

https://github.com/nortikin/sverchok/blob/master/docs/nodes/viz/instancer.rst

**Comment by mlevet** [comment]
Thank you, i'm not sure how it would work yet but i'm trying using this option

**Comment by mlevet** [comment]
So I'm trying to append to cylinders from a blender file called boule.blend to my project.
Objects seems to be here according to the viewer text but I can't see them in the 3D viewport

![Capture d’écran 2020-11-06 à 09 03 26](https://user-images.githubusercontent.com/17178730/98341551-4ccc7c80-200f-11eb-9b7a-92e865758784.png)

Here's the code for the SN lite (the input is not used)

```
"""

in input1 s d=100 n=2
out  objects s

"""

import bpy
objects = []

filepath = "/Users/ml/Desktop/boule.blend"# load all meshes
with bpy.data.libraries.load(filepath) as (data_from, data_to):
    data_to.objects = data_from.objects
    for obj in data_to.objects:
        objects.append(obj)
```

**Comment by vicdoval** [comment]
I think SV "Objects" are refereces to existing objects (not the full objects) so you would need first to append/link the objects to the file and then do the transformations and combinations from those objects

**Comment by Durman** [comment]
You can't import objects in this way. The SNL node is evaluating its code each time it gets new parameters. So you will import a lot of copies. Also you should link imported object to some collection.

**Comment by mlevet** [comment]
Yes also i just noticed i only receive the name of the object as string this way.
So there's no correct way to import (append/link) to sverchok programmatically ?

**Comment by Durman** [comment]
No, your code is really importing object. Check `bpy.data.objects` collection.

**Comment by mlevet** [comment]
oops, i just found many copies of my objects are here indeed !
i'm still misunderstanding some essential concepts of blender
and thank you for the link 

So when you say I can't import objects in this way, you dont mean it's not good doing it using SN, just not this way ?

the thing is i want to import elements randomly from a library, so I guess it's better to not import everything then pick a random choice (would load too many elements to just use a few) but instead find a way to randomize the import

**Comment by Durman** [comment]
If you have to import them only once then it's better to use regular Blender script. If you want import several times you should think about how to remove already imported objects. If you want to control import via Sverchok node interface you have make protection from reimporting the same objects because the code will be evaluated multiple times. There are a lot of possibilities.
