### ISSUE TITLE
Kinetic Sculpture

### ISSUE THREAD

**Issue by thebuza** [nortikin/sverchok#3692]
Hello Guys,

I'm trying to create similar sculpture in Sverchok:

![FLCTF6MIKPS9DO5](https://user-images.githubusercontent.com/45789626/98242154-4d600700-1f6c-11eb-8e79-17b7eb2ddc85.jpg)

What I've done right now is this:
- created a segment with vector field lines + noise vector field.

And it looks quite poorly so... I'd like to challenge it more. It needs more twist and some shape of a drill. Unfortunately I can't control it with noise field. 

Guys, could you simply point me out on what's the best approach to that? I'd be extremely grateful.

![Zrzut ekranu 2020-11-5 o 13 25 07](https://user-images.githubusercontent.com/45789626/98242193-5d77e680-1f6c-11eb-8753-4efa971fc0a8.jpg)

**Comment by DaveSledz** [comment]
Jimmy's 3D Graffiti tutorial could be useful in this case but again, I'm not sure how to force vector points to form only in one direction with sort of a path?

https://www.youtube.com/watch?v=WdEGLBRTMOw

**Comment by zeffii** [comment]
can you add some attribution to the first image? who made it, with what.. etc.

**Comment by DaveSledz** [comment]
Sure, That kinematic sculpture was made by Can Buyukberber in C4D. He made a short explanation on similar project with MoGraph tools here: https://www.instructables.com/Unfold-01-Projection-on-Print/

From what I see he's using some kind of cloner and lofting.

**Comment by zeffii** [comment]
I doubt there's a "best" or "most efficient" way. it depends on how granular you want to get.  I would first start (without looking how it was done by Can Buyukberber) by speculating. 

step one.  maybe it's a noisefield applied to a line which rotates in space, 
![image](https://user-images.githubusercontent.com/619340/98259558-94f18d80-1f82-11eb-9072-7709eacf3796.png)

then translated in one direction.

**Comment by zeffii** [comment]
- step translate each iteration of the line motion

![image](https://user-images.githubusercontent.com/619340/98260654-dcc4e480-1f83-11eb-8fe2-5160a28ef78d.png)

**Comment by zeffii** [comment]
i tried introducing just noise to the result of the line swinging around..
![image](https://user-images.githubusercontent.com/619340/98261509-d4b97480-1f84-11eb-9967-9b689c216844.png)

but no matter what combination of noise or noise scale, it seems that there's another source of noise/randomization , and it appears to be introduced in the rotation phase of the line.  ( i imagine this to be a like a sword being swung around - at the moment the swinging around is happening as a function of sin and cos, but it should maybe be more like a multi-pendulum swing.)

**Comment by DaveSledz** [comment]
Huge Thanks Zeffi, I'm still playing with it. I think that Segment works better and has more possibilities. Just wondering - how can I UV connect to make faces? Tried with Vector interpolation UV and UV Connection after Noise Displace but I get weird results. 

![Zrzut ekranu 2020-11-5 o 18 20 51](https://user-images.githubusercontent.com/45789626/98274409-ab541500-1f93-11eb-82e3-5e7f35b8a9b9.jpg)

**Comment by zeffii** [comment]
here's me throwing a bit of weight into it..
![image](https://user-images.githubusercontent.com/619340/98278415-d9882380-1f98-11eb-94be-7381e4bc635e.png)

[linespace_step_twoblend_2020_11_05_17_58.zip](https://github.com/nortikin/sverchok/files/5496113/linespace_step_twoblend_2020_11_05_17_58.zip)

(i use a wite background.. so the colour of Viewerdraw may not show up)

**Comment by zeffii** [comment]
it's probably somewhere in that parameter space.

regarding the UV connection,   should be able to plug it in after the noise displace, but maybe you must flip U or V.

**Comment by vicdoval** [comment]
Another approach:
A noisy line repeated, scaled, rotated and moved
![image](https://user-images.githubusercontent.com/10011941/98282395-79947b80-1f9e-11eb-8f3b-86f18e0ded45.png)
![image](https://user-images.githubusercontent.com/10011941/98282422-844f1080-1f9e-11eb-92cc-0c26b12e5429.png)
the output from UV Connection 
![image](https://user-images.githubusercontent.com/10011941/98282683-e0199980-1f9e-11eb-87e4-596d2aa880a4.png)

**Comment by zeffii** [comment]
endless fun : )

**Comment by zeffii** [comment]
reminds me of older works (by me)
![Capture_trite_2](https://user-images.githubusercontent.com/619340/98285740-4a343d80-1fa3-11eb-9490-8eafbf81280c.PNG)
![Capture_vaschnikt555](https://user-images.githubusercontent.com/619340/98286019-a303d600-1fa3-11eb-9a5e-c1561d7e0d0f.PNG)
![silberbursh2](https://user-images.githubusercontent.com/619340/98286101-c3339500-1fa3-11eb-8ea8-0db1b5f2a096.PNG)

**Comment by DaveSledz** [comment]
Oh, that looks even better and more 'old school' than the previous version of 3D graffiti. Congrats! That is definitely super fun! 

If we are still talking about ordered line/tray on a one direction path - how about kinetic sound wave? Sounds familiar with Siri and other voice assistants motion graphics : - )

![DanielPalacios_Waves_engine-1](https://user-images.githubusercontent.com/45789626/98296226-e7e33900-1fb2-11eb-884d-63c7b85fba3a.jpg)

It may look like it is just a twisted plane with slight randomization but in fact it is a 3D form (cylinder/cuboid) with visible and variable creases. Of course can be modeled by hand but... hey we are a procedural guys : - )
https://danielpalacios.studio/portfolio/waves/

**Comment by DaveSledz** [comment]
But for the execution of this I have two ideas:
- easy one: twisted cube with post-process modeling like defining creases etc.
- more advanced one: a line with noise/oscillation, skin modifier with noise on scale on different parts and also some kind of 'cloth pressure' for more curved faces and not a straight ones (since the rope is moving in a circle way it has curvy sides)

@zeffii Would you like to try? : - )

**Comment by zeffii** [comment]
maybe this
![image](https://user-images.githubusercontent.com/619340/98351891-9cb24000-201d-11eb-8f9a-40163e262d52.png)
the tree
[motion_trace_sillhouette_2020_11_06_09_49.zip](https://github.com/nortikin/sverchok/files/5500484/motion_trace_sillhouette_2020_11_06_09_49.zip)

![image](https://user-images.githubusercontent.com/619340/98352213-016d9a80-201e-11eb-8519-fa149e564d29.png)

- the A number node would offer a way to increase the iterations (finer grain over the distance)
- the vector sorted output is where you could insert an interpolator node to increase the resolution of the shape

then the method of rendering is still up in the air :)

**Comment by vicdoval** [comment]
is not the same but is cool
![image](https://user-images.githubusercontent.com/10011941/98365888-5ec01680-2033-11eb-974e-45a4b5172e8e.png)
![image](https://user-images.githubusercontent.com/10011941/98365976-8616e380-2033-11eb-9d14-8fab14d99a29.png)
and subsurf modifier + Principled with 1.0 of transmission + sun from the top

**Comment by zeffii** [comment]
i dunno. this brings my computer to a grinding halt. even using dupli-instancer.

![image](https://user-images.githubusercontent.com/619340/98598898-6dc8f200-22db-11eb-96a5-53b1fa0d67db.png)

[motion_trace_sillhouette_2020_11_09_21_32.zip](https://github.com/nortikin/sverchok/files/5513397/motion_trace_sillhouette_2020_11_09_21_32.zip)

**Comment by Ahr0n** [comment]
Just wanted to show you guys my latest project where your Kinetic Sculpture approaches were used. Super excited to tell you about it, for cloth simulations I used Houdini but really wanted to bring Sverchok and create something unique, little bit different than normal cloth simulation.

The effects can be seen here, Sverchok part are the renders with blue cloth: https://www.behance.net/gallery/108131517/369-Armchair

And again, huge thanks to you @zeffii @vicdoval making it possible : - )
