### ISSUE TITLE
Can this be optimized ?

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3693]
The speed of the icons loading takes time to show up. Not like other blender icons
![Screenshot_2020-11-05-14-34-07-910_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/71472224/98247666-38877180-1f74-11eb-9b2a-7b7a6b2fa9bf.jpg)
![Screenshot_2020-11-05-14-33-17-977_com.google.android.apps.photos.jpg](https://user-images.githubusercontent.com/71472224/98247702-46d58d80-1f74-11eb-9011-bbff3f33c33c.jpg)
![IMG_20201105_143337.jpg](https://user-images.githubusercontent.com/71472224/98247757-52c14f80-1f74-11eb-8fed-0f7d0a080183.jpg)
.
.
.
It shows the first icon and then start loading the rest from top to bottom. 
I dont use the search feature because i wanna memories the lists and where every node is and the nodes similar to it. ^^ and its annoying to see the icons load each time.
.
Maybe its just my laptop, cuz i don't have the best laptop out there lol, but maybe its something that can be fixed and this will be my first bug report ^^

**Comment by portnov** [comment]
I can confirm this behaviour, but I suspect we can do nothing with it. What we can do is open a ticket for blender devs, and wait...

**Comment by zeffii** [comment]
i also have a crap computer, and this icon-lazy load is noticable. 

After a while users should remember the names of nodes (or predict the presence of a node by name) and use the extra search and search by name instead of wading though the growing lists of menus. (Alt + Space, by default )

**Comment by onerawartist** [comment]
I ended up deactivating the icons in the shift+A menu , this way i can remember the name of each node and not the icon ^^
