### ISSUE TITLE
Problem with following the tutorial

### ISSUE THREAD

**Issue by dwizor** [nortikin/sverchok#3694]
Hello, i tried to fallow Erin Sverchok Introduction stream but i have problem with this setup:
![stream](https://user-images.githubusercontent.com/68112419/98277054-2c60db80-1f97-11eb-82f0-0a86e0593e99.png)

On stream its just duplicate as array on axis when he have more objects on list but for it seem like it ignore list with more than 1 object.
![sverchock](https://user-images.githubusercontent.com/68112419/98276875-e73ca980-1f96-11eb-8cc0-9da75d002ce6.png)

**Comment by zeffii** [comment]
erin is using a Count mode in Number range, for a starter.

**Comment by dwizor** [comment]
it doesn't matter here, it just has different numbers ;/
![count](https://user-images.githubusercontent.com/68112419/98288331-fd526600-1fa6-11eb-9838-c9cea8a36eb7.png)

**Comment by vicdoval** [comment]
I think I screw it in the last "vector in" update

**Comment by dwizor** [comment]
Okay, easy ^^ Tell me when it will be fixed :D

**Comment by vicdoval** [comment]
Now should be fixed

**Comment by zeffii** [comment]
looks fixed
![image](https://user-images.githubusercontent.com/619340/98448884-b774d980-212f-11eb-9f9a-02fe2d4f2087.png)

reopen @dwizor  if you disagree
