### ISSUE TITLE
SV is somewhat slow at processing 100+ objects....

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3697]
<img width="725" alt="Screen Shot 2020-11-07 at 11 37 23 am" src="https://user-images.githubusercontent.com/3952687/98426624-aacf9180-20ed-11eb-86cb-d34829f3c1dd.png">

Even with "Merge" Mesh Viewer still slow at processing more than 100+ objects. I tried 100000 objects, Blender is frozen on my mac. I don't want to generate 100000 objects, I know that would be too much for Blender. But I would like to just generate for example 100.000 triangles as a single mesh that I later use to instance/dupli objects.

In the past, this does not slow down Blender.

**Comment by enzyme69** [comment]
I know DupliInsta node can duplicate efficiently. However, would there be another "hack" so that I could process 1000 objects at most efficient and fast way? Example:
- Make 1000 box
- Extrude each box face

**Comment by harisreedhar** [comment]
@enzyme69 Use Matrix Apply node for replicating.
![sverchok_instance](https://user-images.githubusercontent.com/46858047/98429728-78fb0280-20ce-11eb-8021-0f571a24307a.png)

**Comment by enzyme69** [comment]
That's probably the one! Thanks Haris!!

**Comment by Durman** [comment]
![2020-11-07_08-02-30](https://user-images.githubusercontent.com/28003269/98431533-a09e9a80-20cf-11eb-998b-8d3baaaeb448.png)

**Comment by vicdoval** [comment]
The Matrix Input in the Box node and in the Plane node re-calculates geometry again so it is slower than unsing Matrix apply after the node. 
If you want many identical boxes is faster the proposed method by @harisreedhar or @Durman.
If the boxes are different (in number of divisions) the is good to use the matrix input of the node
