### ISSUE TITLE
The ''T'' panel search

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3698]
![IMG_20201107_162359.jpg](https://user-images.githubusercontent.com/71472224/98445056-d5cddb80-2115-11eb-9bb3-ed7a87451bfa.jpg)
![IMG_20201107_162405.jpg](https://user-images.githubusercontent.com/71472224/98445091-0c0b5b00-2116-11eb-82d5-991623fa90b0.jpg)

When i use the T panel search its doesn't update the results till i hit ''entre'' and that takes a second each time adding a node.
Not like the ''alt+space'' search.

![IMG_20201107_162421.jpg](https://user-images.githubusercontent.com/71472224/98445235-d0bd5c00-2116-11eb-91d4-042b81a121d9.jpg)
.
I believe it would be great if the T panel search could update like the alt+space. And i like using it because it also shows the name of the group that has that specific node. So using this method will eventually make me memories the ''shift+A'' menu ^^

**Comment by portnov** [comment]
@onerawartist there are a lot of programs for making screenshots for any platform :) I suggest to use any of them :)

**Comment by onerawartist** [comment]
Im sorry for taking shortcuts 😂 i am using the Android github app for easy access anytime anywhere. Reading all the comments and questions from my phone and saving the important ones for later the check once im home. Like trying nodes trees and such, the github app is like my social media app now days ^^ hhhhh. I read every sverchok notification 

So when having a suggestion its much faster to just use the phone cam, even tho i can use the windows screen capture and the browser.
But yeah From now on i will use that for more consistency, its the least i can do comparing to what you guys do ^^ 🙏

**Comment by portnov** [comment]
About your initial question, it seems it is not so simple to implement... by default Blender triggers "update" event for property only when you hit Enter. Probably it is possible to listen for any key press event manually, but for now I don't know how.

**Comment by Durman** [comment]
Listening won't help because Blender is redrawing UI only when script releases control.
