### ISSUE TITLE
List Math

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3699]
![2020-11-07_22-59-01](https://user-images.githubusercontent.com/28003269/98449416-e9e0ff80-214c-11eb-99cb-edc684e0e586.png)
I would expect 1.

**Comment by vicdoval** [comment]
https://github.com/nortikin/sverchok/blob/85e0643ecbd7627074834844a2cfbc97ab6a540c/nodes/list_main/func.py#L121-L122
I wonder why this line was added, seems to have been there since the beginning of sverchok
