### ISSUE TITLE
Color out

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3700]
![2020-11-07_23-15-35](https://user-images.githubusercontent.com/28003269/98449710-37f70280-214f-11eb-822e-51a029ea0858.png)
It should be 0.

**Comment by vicdoval** [comment]
Actually it could be any number, why 0 and not 0.5 or 1?

**Comment by Durman** [comment]
![color bug](https://user-images.githubusercontent.com/28003269/98450074-ea7c9480-2152-11eb-92e6-a6295779653e.gif)

**Comment by vicdoval** [comment]
Its easy to place a arbitrary number in the code, but it will be always arbitrary because total black has no hue or has any hue... but maybe its true that NaN may be confusing
