### ISSUE TITLE
Watch sverchok videos in any language

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3702]
![Screenshot_2020-11-07-23-12-36-241_com.android.settings.jpg](https://user-images.githubusercontent.com/71472224/98452354-f403fd80-214e-11eb-95fe-e256a71828d0.jpg)
![IMG_20201107_231252.jpg](https://user-images.githubusercontent.com/71472224/98452356-fa927500-214e-11eb-9532-d4895393b6f8.jpg)
.
I did on an android device and i believe it is possible on iphones too 
.
Its not perfect but its still better than nothing 

![IMG_20201107_231221.jpg](https://user-images.githubusercontent.com/71472224/98452379-388f9900-214f-11eb-8e78-727c69e5345d.jpg)

**Comment by zeffii** [comment]
this is useful to know.  but i'm not sure we need to keep this open as an issue on the issue tracker.

keywords: translating sverchok tutorial videos
