### ISSUE TITLE
List Slice Lite

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3707]
![2020-11-09_15-45-01](https://user-images.githubusercontent.com/28003269/98537405-a698a500-22a2-11eb-9649-422207779154.png)

```
  File "...sverchok\utils\sv_extra_search.py", line 153, in bl_idname_from_bl_label
    return loop_reverse[bl_label]
KeyError: 'List Slice Lite'
```

**Comment by zeffii** [comment]
fixed by https://github.com/nortikin/sverchok/pull/3708
