### ISSUE TITLE
need an explanation 

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3710]
when i connect the formula node i get this error , don't blame for why im doing it this way lol  , i found some pdf on the internet and im following his methode to learn from the basics ^^ 
![01](https://user-images.githubusercontent.com/71472224/98752885-6c72f480-23c3-11eb-882d-95e10259e2e5.jpg)
![02](https://user-images.githubusercontent.com/71472224/98752890-6e3cb800-23c3-11eb-9f6e-6643c6921e9d.jpg)

**Comment by Durman** [comment]
![2020-11-11_08-13-48](https://user-images.githubusercontent.com/28003269/98764742-dc01d780-23f5-11eb-8442-d081d4565be6.png)

**Comment by nortikin** [comment]
this is another formula
initial formula gone. but i want it revenge anyway.

**Comment by zeffii** [comment]
> i found some pdf on the internet and im following his methode

@onerawartist , the explanation is that throughout the development cycle of the viewer node we went to more strict evaluation of the input data. Where in the past it was permitted to pass `[0, 1,, 2, 3]`, it was automatically interpreted the polygon list of one object. behind the scenes that turns into `[[[0, 1, 2, 3]]]`  (yes, seems like lots of brackets for one polygon in one object - but it is necessary to keep code simple) . 

We have a canonical [explanation of "nesting" levels](https://github.com/nortikin/sverchok/blob/master/docs/nesting.rst)

**Comment by onerawartist** [comment]
Thanks guys ^^ i really appreciate your help. And yes in that tutorial he is using a 2.79 and i switched to blender only 8 months ago hhhhhh. And discovered sverchok 3 months ago ^^
