### ISSUE TITLE
Parametric wall – Modeling - Slicing - DXF export

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3712]
## Problem statement
i am following this tutorial 
http://www.codeplastic.com/2020/01/20/parametric-wall-with-blender-and-sverchok/
 i created the wall but im stuck in "Step 2: Slicing "

the nodes are not behaving the same way it does in the tutorial 
i think you guys changed the name or  the behavior of some nodes 
this is where i am right now 
![01](https://user-images.githubusercontent.com/71472224/99012681-382c3f00-254f-11eb-98d9-9a260c902550.jpg)
can you please check the node of the tutorials and tell me if its still possible now, or the tutorial needs to be updated ?

**Comment by zeffii** [comment]
tutorial by https://github.com/AG89z @AG89z

start with first principles, and isolate the issue: how does slicing work?

start with a cube, rotate it in edit mode, import it into sverchok with objects in, then figure out how to slice it.

![image](https://user-images.githubusercontent.com/619340/99054371-8cf4a780-2599-11eb-877a-29a66a48fb36.png)

it's conceivable (without looking at the bisect code) that there's a small bug related to initializing the node which resolves itself after pressing a few buttons on the node, but I can't reproduce it at the moment.

**Comment by zeffii** [comment]
it's a good candidate for updating the docs.
https://github.com/nortikin/sverchok/blob/master/docs/nodes/modifier_make/bisect.rst

**Comment by onerawartist** [comment]
![02](https://user-images.githubusercontent.com/71472224/99082854-ff2eb180-25c4-11eb-9a02-586ecf1ab98c.jpg)
no matter what i changed, i couldn't make it do vertical cuts, and it only does one cut, can someone help?

**Comment by Durman** [comment]
Could you upload the file?

**Comment by onerawartist** [comment]
![04](https://user-images.githubusercontent.com/71472224/99084354-1e2e4300-25c7-11eb-8928-adeba10e65fe.jpg)


[sliced wall.zip](https://github.com/nortikin/sverchok/files/5537443/sliced.wall.zip)
 i got the slices step , but can't make them vertical yet

**Comment by onerawartist** [comment]
![05](https://user-images.githubusercontent.com/71472224/99086125-5f275700-25c9-11eb-9c8d-dbb32cb996d9.jpg)
rotation is edit mode and updated the node tree , and i got the result i needed, but still; if there's a way , please let me know ^^ and thank you

**Comment by Durman** [comment]
![2020-11-13_19-13-00](https://user-images.githubusercontent.com/28003269/99087539-52fcc300-25e4-11eb-987b-71fdad6d6439.png)

**Comment by onerawartist** [comment]
awesome ^^ , and giving the cut matrix another viewer is great idea, i'll be using that trick from now on.
now im on step 3 making all those slices on one plane so i can export them if needed 
![06](https://user-images.githubusercontent.com/71472224/99090177-94827380-25ce-11eb-971f-1184289e133b.jpg)
![07](https://user-images.githubusercontent.com/71472224/99090196-9a785480-25ce-11eb-894b-70045270581a.jpg)
but it seems like im lost again:
http://www.codeplastic.com/2020/01/20/parametric-wall-with-blender-and-sverchok/
thank you guys for your time @zeffii @Durman

**Comment by Durman** [comment]
[sliced wall.zip](https://github.com/nortikin/sverchok/files/5537943/sliced.wall.zip)

**Comment by zeffii** [comment]
when you are importing geometry from the Scene using `Objects In`, remember that you will get the verts un-transformed, this means if the Object has un-applied rotations/transform/scaling in the scene, then you must use the matrix socket output of the `objects-in`  node, and apply that matrix to the verts.  Like this

![image](https://user-images.githubusercontent.com/619340/99092699-c6490980-25d1-11eb-956a-314ec28c510c.png)

**Comment by onerawartist** [comment]
thank you so much @Durman

**Comment by nortikin** [comment]
there is example Design-panno

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/pull/5204 dxf exporters
