### ISSUE TITLE
Processing Point Cloud in SV is ... slower than ever.

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3718]
I am trying to process 1000000+ points just to generate triangles from point cloud data. This used to be a lot faster, but I noticed in recent years, SV node is slow at processing this. Is there a best way other than Matrix Apply node to generate poly face that I can colorize using Vertex Color?

<img width="1680" alt="Screen Shot 2020-11-16 at 12 05 05 pm" src="https://user-images.githubusercontent.com/3952687/99202693-0e4f7280-2804-11eb-8152-a2e7e6df92f3.png">

**Comment by Durman** [comment]
Can you upload the file?

**Comment by enzyme69** [comment]
@Durman here is the original point cloud XYZ text data:
[point_cloud_xyz_PUMPKIN.zip](https://github.com/nortikin/sverchok/files/5545862/point_cloud_xyz_PUMPKIN.zip)

This is the Blend file, with the node setup:
[sv_pointcloud_001.blend.zip](https://github.com/nortikin/sverchok/files/5545863/sv_pointcloud_001.blend.zip)

All I want is points at XYZ, with RGB applied into Vertex or in this case NGon Face.

Blender 2.92+ will support PLY point cloud, hopefully with RGB data. I am not sure maybe a specific "point cloud reader" is needed in such case.

**Comment by vicdoval** [comment]
> This used to be a lot faster

Are you sure? have you tested against any previous versions? (maybe 2.79?)

**Comment by Durman** [comment]
He is right, I'll fix this.

**Comment by Durman** [comment]
![2020-11-22_20-54-52](https://user-images.githubusercontent.com/28003269/99910005-36a80700-2d05-11eb-83f0-f41f55e36e2c.png)

**Comment by enzyme69** [comment]
Thanks Durman, I am testing it now! Maybe in Blender 2.92 alpha and up, with point cloud object, this should be a breeze.

**Comment by Durman** [comment]
I actually just returned performance on the level as it was before.
Is it point cloud? How did you color it?
