### ISSUE TITLE
Curve Mapper loses its curve when performing specific actions

### ISSUE THREAD

**Issue by mnn** [nortikin/sverchok#3721]
## Problem statement

When duplicating a curve mapper or creating a monad with a curve mapper, only a blank curve mapper node is created, the curve is lost.

![Peek 2020-11-18 18-20_sverchok_vanishing_curve_in_curve_mapper](https://user-images.githubusercontent.com/1975567/99564530-dfcfc400-29ca-11eb-96d8-f83f547c0017.gif)

## Steps to reproduce

1. Create Curve Mapper node with custom curve
2. Duplicate the node

## Expected result

The curve is duplicated along with other node data.

## Actual result

Curve Mapper without curve (actually even the default curve is not shown, you have change some other value in the node to get it to show, so you can edit it).

## Sverchok version

0.6.0.0

I believe it's the "stable Oktober 2020" v2, installed from inside Blender (`Add-ons` -> `Install...`)

**Comment by zeffii** [comment]
yeah, curvemapper is missing a copy() function. (to tell the node how to respond to user using node duplication)

**Comment by zeffii** [comment]
something like 
```python
    def sv_copy(self, other):
        ''' self is the new node, other is the old noe '''
        curve_dict = {}
        other.save_to_json(other, curve_dict)
        self.load_from_json(self, curve_dict)
        updateNode(self, None)

```
but this makes the new curvemapper linked to the original, which is probably not what you want.

**Comment by zeffii** [comment]
if someone else doesn't fix it by tomorrow, i'll have a closer look.

**Comment by zeffii** [comment]
i didn't manage to solve in my avaliable time.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3726  maybe? anyone confirm

**Comment by zeffii** [comment]
should be OK now , pushed a fix https://github.com/nortikin/sverchok/pull/3726
