### ISSUE TITLE
Formula+ overrides default node property "dimensions"

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3727]
I'm trying to fix some issues with the SV Display Nodes panel

Everything seems fixable but this override makes me doubt:
Do we need a new version of the node "mk5" or just change that property and potentially break some layouts?

Another idea would be changing the code of the "Display Nodes panel" to get node.width and node.height in stead of node.dimensions....

**Comment by zeffii** [comment]
`.dimensions` is a reserved keyword :/   it should never have been used.

**Comment by zeffii** [comment]
mk5 is appropriate anyway.
sadly also formula3 does this.

**Comment by Durman** [comment]
How can existing layouts be broken unless you are renaming the property?
What is wrong with dimensions attribute?

**Comment by zeffii** [comment]
dimensions attribute [bpy.types.Node.dimensions](https://docs.blender.org/api/blender2.8/bpy.types.Node.html?highlight=node%20dimensions#bpy.types.Node.dimensions)

it must default to `(0, 0)` , unless the node is resized by user or from size is set from `init`.  But we override that property in these nodes. Maybe it would make sense to add a unit test to see if any node annotations are using any of those default node properties, and make it an error ❌ .

>  How can existing layouts be broken unless you are renaming the property?

maybe we can add a small repair function at the start of formula's process function

```
if len(self.dimensions) == 1:
    self.formula_dimensions = self.dimensions
    self.dimensions = (self.width, self.height)
```
i am not sure.

**Comment by vicdoval** [comment]
@zeffii that would be a temporal solution that could work, ultimately we would need to replace fomula_mk3 and mk4 by a mk5, What are the real differences between mk3 and mk4?
Why mk4 did not replace mk3?

**Comment by zeffii** [comment]
good question. i think to make matters more interesting, @nortikin  even wants the original formula node back :)

mk4 adds additional evaluation using the ast module, and extra wrapping options. and fixes issues with the order in which sockets are created (makes them predetermined, by alphabetical enumeration) 

- https://github.com/nortikin/sverchok/issues/3225
- https://github.com/nortikin/sverchok/issues/3260

**Comment by portnov** [comment]
In the new Mk of Formula node, it would be nice to support Numpy implementation. I.e., if the option is checked, then convert each list of values from inputs to Numpy arrays and make all computations with numpy arrays. And have an option: to output numpy arrays or python lists.

**Comment by vicdoval** [comment]
and what was missed by @nortikin from mk1?

**Comment by vicdoval** [comment]
So it seems mk4 can be turned to mk5 and mk3 and mk4 go to old nodes folder.  No?

**Comment by zeffii** [comment]
i think so @vicdoval 

and if the output is dimension three, perhaps offer the option to output to a SvVerticesSocket.

**Comment by nortikin** [comment]
> and what was missed by @nortikin from mk1?

@vicdoval 
missed of working with vertices vs numbers, vertices vs vertices. so mk1 was doing all combinations and also all math functions used.

```python
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import parser

import bpy
from bpy.props import StringProperty

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode, SvSetSocketAnyType, SvGetSocketAnyType
from math import cos, sin, pi, tan


class SvFormulaNode(bpy.types.Node, SverchCustomTreeNode):
    ''' Formula '''
    bl_idname = 'SvFormulaNode'
    bl_label = 'Formula'
    bl_icon = 'OUTLINER_OB_EMPTY'
    sv_icon = 'SV_FORMULA'

    formula : StringProperty(name='formula',
                             default='x*n[0]',
                             update=updateNode)

    def draw_buttons(self, context, layout):
        layout.prop(self, "formula", text="formula")

    def sv_init(self, context):
        self.inputs.new('SvStringsSocket', "X")
        self.inputs.new('SvStringsSocket', "n[0]")
        self.outputs.new('SvStringsSocket', "Result")


    def update(self):
        # inputs
        if not self.inputs:
            return
        if self.inputs[-1].links:
            self.inputs.new('SvStringsSocket', 'n[{}]'.format(str(len(self.inputs)-1)))
        else:
            while not self.inputs[-2].links:
                self.inputs.remove(self.inputs[-1])

    def process(self):
        vecs = self.inputs['X'].sv_get(default=[[0]])
        
        list_mult = []
        for idx, socket in enumerate(self.inputs[1:-1]):
            if socket.is_linked and \
               type(socket.links[0].from_socket).bl_idname == "SvStringsSocket":

                mult = socket.sv_get()
                list_mult.extend(mult)
            else:
                list_mult.extend([[0]])
                
        if len(list_mult) == 0:
            list_mult = [[0.0]]

        # outputs
        if self.outputs['Result'].is_linked:

            code_formula = parser.expr(self.formula).compile()
            r_ = []
            result = []
            max_l = 0
            for list_m in list_mult:
                l1 = len(list_m)
                max_l = max(max_l, l1)
            max_l = max(max_l, len(vecs[0]))

            for list_m in list_mult:
                d = max_l - len(list_m)
                if d > 0:
                    for d_ in range(d):
                        list_m.append(list_m[-1])

            lres = []
            for l in range(max_l):
                ltmp = []
                for list_m in list_mult:
                    ltmp.append(list_m[l])
                lres.append(ltmp)

            r = self.inte(vecs, code_formula, lres)

            result.extend(r)
            SvSetSocketAnyType(self, 'Result', result)

    def inte(self, l, formula, list_n, indx=0):
        if type(l) in [int, float]:
            x = X = l

            n = list_n[indx]
            N = n

            t = eval(formula)
        else:
            t = []
            for idx, i in enumerate(l):
                j = self.inte(i, formula, list_n, idx)
                t.append(j)
            if type(l) == tuple:
                t = tuple(t)
        return t


def register():
    bpy.utils.register_class(SvFormulaNode)


def unregister():
    bpy.utils.unregister_class(SvFormulaNode)

if __name__ == '__main__':
    register()

```
