### ISSUE TITLE
Simple GeoPath Approximation and some issues

### ISSUE THREAD

**Issue by summereasy** [nortikin/sverchok#3730]
## Problem statement

After playing with sverchok for a bit, I find myself really in love with it. It's such great work!
The thing is that I'm currently playing with some geodesic approximation in blender. I used to think python is the only way to do it (ie. Heat Method etc.) but since sverchok got all these surface/curve nodes stuff in it, it's now much more fun to play with And much easier to animate with.

What I've got here is a simple "parallel transport" approximation, it generates geodesic paths:
![geoPath_01](https://user-images.githubusercontent.com/51897649/99874511-8e6e4180-2c23-11eb-8ed1-738221c85bdc.gif)
![geoPath_02](https://user-images.githubusercontent.com/51897649/99874512-90380500-2c23-11eb-9c77-1df4376ea7e3.gif) 

**Workflow:**
1. Create an arbitrary Surface in Sverchok
2. Drop anything (here is a box) on that Surface as an initial starting point
3. Create a Monad for moving a small distance along its local y-direction on Surface
4. Loop Monad several times to see the geo-path
![iShot2020-11-21 18 35 11](https://user-images.githubusercontent.com/51897649/99875146-4e5d8d80-2c28-11eb-825d-c2021b3ac87e.jpg)

This is fairly simple and all that parallel transport monad need is an initial frame (Matrix) and a surface to travel with. After a bit of mathmatics, it will gen-out the transported frame(matrix). 
![iShot2020-11-21 18 21 35](https://user-images.githubusercontent.com/51897649/99874918-751ac480-2c26-11eb-9eaf-bcf680504607.jpg)

## blend file for review
[ParallelTransport06.zip](https://github.com/nortikin/sverchok/files/5577377/ParallelTransport06.zip)

OS Version: **Mac OSX 10.15.7**
Blender Version : **2.90.1**
Sverchok Version: **0.6.0.0**

**The results turn to be good in general but I also encountered some issues:**

#### A. issues from monad

1. **It seems monad loop could not work unless every output is "connecting" something**

   Here, in my case, I **have to** connect 2 Stethoscopes to the output so the monad loop could work properly.
![iShot2020-11-21 18 25 43](https://user-images.githubusercontent.com/51897649/99874996-ff632880-2c26-11eb-9168-a3481ed9b100.jpg)

2. **Sometimes it cannot find the Nearest Point on the surface. I've checked those nodes one by one but couldn't find out why. It seems worked well without using Monad, but I'm not sure.**

   ```
   2020-11-21 17:03:55,804    ERROR logging.py 165 Node Nearest Point on Surface had exception: Can't find the nearest point for (-0.8980225324630737, -2.6428518295288086, 0.3407576084136963): b'ABNORMAL_TERMINATION_IN_LNSRCH'
   ```

3. **The console keeps prompting this "deepcopy" alert and crashes frequently. I don't know if this warning is associate with the crashing but it just crashes a lot. Don't know why either.**

   ```
   2020-11-21 17:03:58,618  WARNING logging.py 165 Socket='connect me' of node='Group Outputs Exp' can't update number of objects on the label. Cause is 'sv_get() got an unexpected keyword argument 'deepcopy''
   ```

#### B. other issues

1. **New Wrap/Unwrap socket options cannot be activated inside monad edit mode**
   I need to calculate the normal difference for the point on the surface and local frame to get the **connection** in order to correct the path direction. But normal outputs for "frame on the surface" and "Matrix Base" are wrapped differently. And I have tried the new Wrap/Unwrap Socket Option and found it was not working inside monad edit mode. (so I use vector out -> vector in to get a re-route)

2. **Maybe some more Matrix Math Options?**
   This is a minor one since one can always figure out a way to get the right output. But sure it would be more convenient if we implement more matrix functions. For example, some options like `$T'=RTR^T$` ? Or say, a fully **variable** based Matrix Input would be nice (just like formula node).

**Comment by zeffii** [comment]
### point 1  

is correct:  Monad's _loop mode_ does require all outside and inside sockets to be connected, the underlying code expects it. What you can do is connect a `Matrix In` into the monad instead of leaving that socket unconnected.

this behaviour has been an on and off discussion for some time. ( [2017](https://github.com/nortikin/sverchok/issues/1666#issuecomment-303160688) and [2020](
https://github.com/nortikin/sverchok/issues/2799) )

@Durman is reimplementing monad/group node , so i'm hesitant to stick any energy into monad, as it will be obsolete soon. But allowing external sockets to be unconnected and use the default value, may not be a big issue to implement any.

**Comment by zeffii** [comment]
I notice that unconnected matrix socket in monad displays the wrong kind of default parameter, it should just show the 'quick link' button and not a float slider.

**Comment by zeffii** [comment]
### point A .3

something seems to be calling `sv_get()` on a `connect me` socket type. weird.

**Comment by summereasy** [comment]
> ### point A .1
> is correct: Monad's _loop mode_ does require all output (and inside sockets) to be connected, the underlying code expects it. This behaviour has been an on and off discussion for some time. ( [2017](https://github.com/nortikin/sverchok/issues/1666#issuecomment-303160688) and [2020](https://github.com/nortikin/sverchok/issues/2799) )

Thanks zeffii for pointing that out. I did check the **manual** and it shows:
> **Loop n times**
> This can be used for repeatedly applying an effect to a mesh, the number of iteration is currently only configurable via the node UI - it’s too easy to accidentally grind your computer to a halt if that was set dynamically via an input socket. - _**currently you must connect all named sockets,**_ - the input and output nodes must be fully connected and the arrangement/order of sockets must be consistent

However I think missed understand it for what **Must Connect All Named Sockets** means, and learned it in the hard way...

**Comment by zeffii** [comment]
I think what i meant there was that "Named Sockets" are all sockets that aren't "connect me" sockets. This totally my failure to communicate about this node, it's unnecessarily complicated and i don't like reading it's code :) so it became "stunted" early on.

**Comment by summereasy** [comment]
As @zeffii stated, currently **@Durman** is reimplementing the **monad/group node**, and the old monad will be obsolete anytime, I am closing this issue. Great thanks though.

**Comment by nortikin** [comment]
You can try genetic algorythm. i think in compare it can show some kind of enhencement. GA node has own loops.

**Comment by summereasy** [comment]
> You can try genetic algorythm. i think in compare it can show some kind of enhencement. GA node has own loops.

Wow, I didn't even notice there is a GA node there. How cool is that!
I'll definitely give it a try, thanks!! 👍 😃
