### ISSUE TITLE
whats the best way to do a boolean ? 

### ISSUE THREAD

**Issue by onerawartist** [nortikin/sverchok#3740]
i created these in sverchok 

![01](https://user-images.githubusercontent.com/71472224/100032917-5ae51000-2df9-11eb-8a9f-37c98d0081cc.jpg)

and i want to cut them and make them look like this (i did it by modeling tools not sverchok)

![02](https://user-images.githubusercontent.com/71472224/100032998-88ca5480-2df9-11eb-8fbe-8880533873fb.jpg)

 and i want to make it happen all in sverchok if its possible " im sure it is , and i have no idea how " ^^
i tried to do this , and blender keeps crashing 
![05](https://user-images.githubusercontent.com/71472224/100033097-c3cc8800-2df9-11eb-8f76-3cf688a3dbff.jpg)

so i tried this 
![04](https://user-images.githubusercontent.com/71472224/100033147-e2328380-2df9-11eb-91ca-2c0699d3eed9.jpg)
 and nothing happens 
.
im sure i'm doing something terribly wrong, ^^

**Comment by onerawartist** [comment]
by the way , in the last two photos , im trying to use the wall behind "wall 03 "as a cutter

**Comment by portnov** [comment]
In this particular case, I think, "Bisect" node will be enough.

**Comment by zeffii** [comment]
i would place the `bisect node` infront of to the MeshViewer, this prevents a bit of recomputation.

**Comment by zeffii** [comment]
or even more oldschool sverchoky
![image](https://user-images.githubusercontent.com/619340/100077223-63ae0400-2e42-11eb-9b60-a8ea751ef05b.png)

[oldschool_swervy_2020_11_24_09_47.zip](https://github.com/nortikin/sverchok/files/5588914/oldschool_swervy_2020_11_24_09_47.zip)

**Comment by zeffii** [comment]
the best way to do a boolean is to learn how to avoid doing booleans. (sorry, not sorry)

**Comment by zeffii** [comment]
also @onerawartist   the csg boolean node expects to Mesh based inputs, if you look carefully, the mesh you input from the Object In node  is verts+edges only.
