### ISSUE TITLE
Changing SEED of Random Vector does not work anymore

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3743]
<img width="935" alt="Screen Shot 2020-11-26 at 11 53 17 am" src="https://user-images.githubusercontent.com/3952687/100295580-0fd82200-2fde-11eb-9278-21d8f38f023d.png">

**Comment by enzyme69** [comment]
[Screen Recording 2020-11-26 at 11.54.54 am.mov.zip](https://github.com/nortikin/sverchok/files/5599843/Screen.Recording.2020-11-26.at.11.54.54.am.mov.zip)

Tested with Blender 2.91, with Boolean collection modifier. There is something weird:

[boolean_collection_003.blend.zip](https://github.com/nortikin/sverchok/files/5599864/boolean_collection_003.blend.zip)

**Comment by Durman** [comment]
![2020-11-26_08-22-43](https://user-images.githubusercontent.com/28003269/100307962-9e3dab00-2fc0-11eb-9888-22e25dbdd5d6.png)

**Comment by enzyme69** [comment]
Hmm.... it might be it, but the seed on randomize works, but not on random vector. When it happens again, I will reopen. It's something to do with Collections.
