### ISSUE TITLE
Can not enable sverchok  anymore with 2.91 - 2.92 etc..

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#3747]
Old version off sverchok works fine but not the new version off sverchok with blender 2.91 or 2.92 etc...
![image](https://user-images.githubusercontent.com/49908008/100541757-41ebbd00-3246-11eb-90a6-2517cf740372.png)

**Comment by BennyGovaerts** [comment]
This happens  only if you do a clean install

**Comment by portnov** [comment]
Uh.

**Comment by portnov** [comment]
Please try fresh master, should be fixed.
