### ISSUE TITLE
Nothing updates and no error, strange bug (!)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3748]
I don't know what I did, but basically was noodling with nodes and suddenly the node tree stops updating.

I restart Blender, reload the node tree, etc. But nothing.

[illusion_tree_002.blend.zip](https://github.com/nortikin/sverchok/files/5613313/illusion_tree_002.blend.zip)
<img width="876" alt="Screen Shot 2020-11-30 at 12 28 17 pm" src="https://user-images.githubusercontent.com/3952687/100559672-8723f380-3307-11eb-9198-abfdf2167a43.png">

**Comment by enzyme69** [comment]
Weird but I just close it for now. I rebuild and works.

**Comment by onerawartist** [comment]
It always happens to me, i usually press update all trees in the N panel
