### ISSUE TITLE
Old nodes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3749]
Looks like master is not able to download old nodes in trees at this moment.

**Comment by vicdoval** [comment]
The problem seems to be in the Old Edge Split node by @portnov

**Comment by portnov** [comment]
@vicdoval what's a problem?

**Comment by vicdoval** [comment]
It fails to register the old node causing many old nodes not to be registered. Maybe is due the wrapnode system

**Comment by portnov** [comment]
I'm afraid I do not understand how that system works :) @Durman I think you do :)

**Comment by Durman** [comment]
Me? Why me? I think @zeffii is most familiar with this functionality.

**Comment by portnov** [comment]
@Durman "edge split" node uses "magic" from https://github.com/nortikin/sverchok/blob/master/utils/handling_nodes.py, which is mostly yours :)

**Comment by Durman** [comment]
hm. Interesting. Don't see how this could impact on registering old nodes.

**Comment by Durman** [comment]
By the way anybody knows why we bother with all this dynamic node registration? Why not just register all old nodes on Blender start?

**Comment by portnov** [comment]
Probably to do not show them in Search menu?

**Comment by zeffii** [comment]
> anybody knows why we bother with all this dynamic node registration?

this was an early design decision. you would have to read the early days of the issue tracker and "deprecated nodes", to come to a conclusion for yourself.

I would be in favour of being even more selective about which nodes to load at startup ( a true lazy load system). f.ex only load a node under these circumstances
- load from menu
- load from quick search
- load appropriate nodes for a blend.

pros:  for slower machines this speeds up sverchok loading, lower memory footprint.
cons:  who wants to do it. not me.
