### ISSUE TITLE
Not able to see the wires that connect the nodes.

### ISSUE THREAD

**Issue by narellanor** [nortikin/sverchok#3750]
Hi, I use Dynamo a lot, so I am familiar with visual programming tools. However, I am new at Sverchok so this is probably an easy fix. I can't see the wires that connect the nodes. Can anyone help me, please?

Thanks 

Nico

**Comment by vicdoval** [comment]
It sounds pretty strange, the links are created but hidden? Or you can't create the links? Can you share a screenshot?

**Comment by narellanor** [comment]
![image](https://user-images.githubusercontent.com/67920407/100942407-525f9a00-34c9-11eb-9de1-db9c2e9d3168.png)
Hi @vicdoval, thanks for replying. This is an example, I am imputing a number as a Radius but I can't see the wire. Any clue?

**Comment by Durman** [comment]
Try connect nodes in other node editors, if result will be the same then the problem is in Blender part.

**Comment by narellanor** [comment]
It seems that it is a problem with my graphic card.
https://www.blender.org/forum/viewtopic.php?p=76258&sid=7b9f37cee069adc00701cd43811f55af
_" the problem comes from some graphics drivers not supporting OpenGL line width properly."_
Thanks a lot for your suggestions. I guess I have to update the card.
