### ISSUE TITLE
Animating segment of Curve (s) efficiently

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3757]
I would like to make animation of segment based on curve or multiple curves (such as Grease Pencil), is there a more efficient or better way than below setup: (with bug)

[segment_anim_003.blend.zip](https://github.com/nortikin/sverchok/files/5649927/segment_anim_003.blend.zip)
<img width="1027" alt="Screen Shot 2020-12-07 at 12 13 13 pm" src="https://user-images.githubusercontent.com/3952687/101299262-ab428000-3885-11eb-9452-18a6dab93c15.png">

**Comment by rendetto** [comment]
TMax should always be greater than TMin. The error you get is due to TMax being smaller than TMin.

**Comment by enzyme69** [comment]
Ok thanks I'll find a way that allows this "segmentation" but maybe more in term of masking points first. Cheers!
