### ISSUE TITLE
How to expose internal properties of a node to other nodes

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3758]
Is there a way for a **node A** to know what value was selected from a drop down list in another **node B**? E.g. if a **node A** has various “Modes” selectable from a drop down list.. or perhaps a checkbox toggle value .. how can another **node B** “know” what these selections are within a **node A**? 

One way is to expose these internal properties of a node as output sockets but that would just make the node output sockets unnecessarily cluttered.

**Comment by Durman** [comment]
I don't see the problem. You can get property by its name from any place of your code `node.attr_name`.

**Comment by zeffii** [comment]
```
| node A   X.  o | --------------------------> | o Y.      node B |
```
a node can get the bl_idname/name of upstream nodes, so socket Y can be queried to find bl_idname/name associated with socket X. and once you know that you can get a reference to the node object and query its properties.

console node uses this kind of technique

```python
                connected_bl_idname = self.inputs[0].other.node.bl_idname
                
                if connected_bl_idname == "SvScriptNodeLite":
                    socket_data = list(self.inputs[0].other.node.script_str.splitlines())
                    self.set_node_props(socket_data)
```
