### ISSUE TITLE
Some kind of Collision Detection

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3761]
I want to have a setup with nodes that trigger action when "collision" happens, what would be the best SV nodes that can do this effectively? Inside Volume node? Or something else?

**Comment by Durman** [comment]
Probably `Raycaster` node could be used.

**Comment by enzyme69** [comment]
So far I tried this, but will check Raycaster and come back. Thanks Durman!

<img width="1087" alt="Screen Shot 2020-12-08 at 8 02 17 pm" src="https://user-images.githubusercontent.com/3952687/101462394-4889db00-3990-11eb-8abf-bec586c93d72.png">

[inside_volume_001.blend.zip](https://github.com/nortikin/sverchok/files/5658051/inside_volume_001.blend.zip)

**Comment by enzyme69** [comment]
Hmm not sure how to use Raycaster to detect "collision" 

<img width="817" alt="Screen Shot 2020-12-08 at 8 13 20 pm" src="https://user-images.githubusercontent.com/3952687/101463692-df0acc00-3991-11eb-814b-6ee40f4c150e.png">


[raycaster_001.blend.zip](https://github.com/nortikin/sverchok/files/5658102/raycaster_001.blend.zip)

**Comment by Durman** [comment]
![test](https://user-images.githubusercontent.com/28003269/101464718-70f5e300-3958-11eb-85bd-c7a14861a8ea.gif)
![2020-12-08_13-21-20](https://user-images.githubusercontent.com/28003269/101464723-72271000-3958-11eb-93ff-d582ec11a5b3.png)

**Comment by enzyme69** [comment]
not working on this:

<img width="1028" alt="Screen Shot 2020-12-08 at 8 31 42 pm" src="https://user-images.githubusercontent.com/3952687/101465714-66f1d580-3994-11eb-8877-b701d85d7362.png">
[hit_box_002.blend.zip](https://github.com/nortikin/sverchok/files/5658239/hit_box_002.blend.zip)

**Comment by enzyme69** [comment]
I might close this and reopen if I ever come back.
