### ISSUE TITLE
Polyline viewer node's bevel curve isn't working in blender 2.91

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#3766]
## Problem statement

![Screenshot_x](https://user-images.githubusercontent.com/62538469/101740949-cffc5900-3b0c-11eb-9d1b-ad76704b3cf7.png)

The node settings for this picture are almost identical to those found in the Polyline viewer's documentation.

If file created in blender 2.9 or open the file in blender 2.9 and save, bevel is no problem. 
but use only 2.91, bevel curve isn't working.

Maybe the following features are involved.

Custom Bevels for Text and Curves in Blender 2.91
https://www.blendernation.com/2020/09/19/custom-bevels-for-text-and-curves-in-blender-2-91/

**Comment by Durman** [comment]
Yes, it is related with Blender API changes.

**Comment by vicdoval** [comment]
fixed in #3899
