### ISSUE TITLE
SNL node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3768]
```Python
'''
in value s
'''
out = 1
```

```
  File "sverchok\nodes\generator\script1_lite.py", line 346, in make_new_locals
    socket_info = ND['sockets']
KeyError: 'sockets'
```

I would expect at least clearer error.

**Comment by zeffii** [comment]
or for the user to actually read the documentation.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/docs/nodes/generator/script1_lite.rst#syntax

**Comment by Durman** [comment]
I did not find anything about forbidden variable names in the documentation. I think it worth fixing because I spent some time over the problem before making connection between the error and variable names in a script. This can be fixed by anybody who will find time for it.

**Comment by zeffii** [comment]
i don't think this is about forbidden variable names, at all. The "directive" parser expects the directive to start with `"""` and end with `"""`, maybe this is not explicit enough in the documentation segment i linked to,  i agree that is lacking in clarity.

I limited the allowed syntax to `"""` because it simplifies the parsing code.

**Comment by Durman** [comment]
Don't know. This works perfectly.
```Python
'''
in value s
'''
test = 1
```
 And I have other quite workable scripts which use `'''` too.

**Comment by Durman** [comment]
And we have quite a lot scripts in `node_scripts` folder which use single quotes.

**Comment by zeffii** [comment]
i give up.

**Comment by rendetto** [comment]
Could it be just written in the docs that it could work the ' ' ' way but it's not recommended?

**Comment by Durman** [comment]
> i give up.

Thank you for participation.





> Could it be just written in the docs that it could work the ' ' ' way but it's not recommended?

As to me the both variants should work identically. Don't see a big problem with implementing the similar logic for the single quotes.

**Comment by zeffii** [comment]
This code would spit out only the text contained in the first occurrence of a double or single qouted string. I appreciate that the choice to "limit" correct parsing of the directive to double quotes is arbitrary, but it was the simpler of my choices. I am tempted to slightly rewrite that parser in `snlite_importhelper` to use "`find_first_quote`" instead.  

or maybe it's a complete non issue. I can't expect the execution to complete if there's no valid code in the body - no matter what you think it should be doing.

```python
import re

files = "example_001.py", "example_002.py"

def find_first_quote(lines):
    pattern = '\"{3}([\s\S]*?)\"{3}|\'{3}([\s\S]*?)\'{3}'
    p = re.compile(pattern)
    g = p.match(lines)

    types = "double qoutes", "single qoutes"
    matches = g.groups()
    for idx, m in enumerate(matches):
        if m:
            print("using:", types[idx])
            return m
    return

for file in files:
    print("=====")
    with open(file) as f:
        lines = ''.join(f.readlines())
        result = find_first_quote(lines)
        print(result)

```

example_001.py
```python
'''
single qoutes file
this file uses double quotes

and here

and also here
file 1
'''

this is supposed to be some code
and another = line - 34
yep

and end

and 
""" 
here and this should not be printed

"""

and 

'''

and this also should not be found
'''

```

example_002.py
```python
"""
double qoutes file
this file uses double quotes

and here

and also here
file 2
"""

this is supposed to be some code
and another = line - 34
yep

and end

and 
""" 
here and this should not be printed

"""

and 

'''

and this also should not be found
'''
```
