### ISSUE TITLE
replacing two deprecated node types

### ISSUE THREAD

**Issue by javismiles** [nortikin/sverchok#3769]
Good day,
I have installed the latest blender 2.91 and the latest Sverchok sverchok-master.zip 0.6.0.0,
when I open one of my projects, the nodes show that there are now two nodes that Im using that are deprecated:
a) Object ID Selector
b) the BV node (Viewer B Mesh I think this is)

what should I do to maintain same functionality and all, what do I have to replace those 2 nodes with?
thank you very much

**Comment by portnov** [comment]
Usually it is enough to right click on the node and select "Replace with ..."
New "Bmesh viewer" is called just "Mesh Viewer".

**Comment by javismiles** [comment]
thank you very much, doing right click on node there is no option "replace with",
any other way to get to that option? thank you,
and whats the replacement for the other one, for object id selector? thank you

**Comment by rendetto** [comment]
I guess it is the "Object ID Selector+"
![ID_Selector](https://user-images.githubusercontent.com/66558924/101842153-1aeb9000-3b50-11eb-841c-7151475467b4.jpg)

**Comment by javismiles** [comment]
good day and thank you for your help,
so the issue is that i am replacing the Bmesh viewer with the new MeshViewer,
and its not working,
i get error "list index out of range",

all i did was to replace it, keeping identical connections, I attach picture
![issue](https://user-images.githubusercontent.com/1000452/102093603-a18ac080-3e21-11eb-8907-fac07bdfb328.jpg)

**Comment by javismiles** [comment]
![issue2](https://user-images.githubusercontent.com/1000452/102093880-f4fd0e80-3e21-11eb-9ecb-861b9e82d1f3.jpg)

wider picture, i just kept same connections and all
