### ISSUE TITLE
export curve to STEP (Compound Solid)

### ISSUE THREAD

**Issue by h4lf** [nortikin/sverchok#3775]
## Problem statement

curve is not exported to STEP

![TestCompoundSolid](https://user-images.githubusercontent.com/17392695/102001974-fb4b9780-3d08-11eb-9ef0-55c451fea9f5.PNG)
![TestCompoundSolidF](https://user-images.githubusercontent.com/17392695/102001983-17e7cf80-3d09-11eb-9011-ecf9890b0f5e.PNG)
[TestCompoundSolid.zip](https://github.com/nortikin/sverchok/files/5684143/TestCompoundSolid.zip)

**Comment by portnov** [comment]
Well, I'm not sure if I can do something here. Sverchok creates `Part.Compound` object and then calls `shape.exportStep(file_path)`. Everything else is done inside FreeCAD libraries.
Note: if you pass the curve directly to Solids input of the Export node, it will appear in the Step file. The only thing is, this way you can't put several objects into one file.

**Comment by portnov** [comment]
Posted to upstream: https://forum.freecadweb.org/viewtopic.php?f=10&t=53202

**Comment by h4lf** [comment]
> if you pass the curve directly to Solids input of the Export node, it will appear in the Step file.

Thank you. That's enough for me at the moment.

PS: А вообще - это очень здорово, что в сверчке можно работать с твёрдыми телами.

**Comment by portnov** [comment]
@h4lf the issue appears to be floating. The first time I opened your file I was able to reproduce it, but now I can not. Please try to reproduce the problem again after relaunching blender, or maybe rebooting the computer, or I don't know what else :) Does it reproduce each time for you?

**Comment by h4lf** [comment]
> Does it reproduce each time for you?

Yes. Win10, conda-0.18.3
