### ISSUE TITLE
vertex color node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3779]
https://github.com/nortikin/sverchok/blob/3c5ca7077d23bd050483dc926d4c9e08b466266d/nodes/object_nodes/vertex_colors_mk3.py#L161-L162
https://github.com/nortikin/sverchok/blob/3c5ca7077d23bd050483dc926d4c9e08b466266d/nodes/object_nodes/vertex_colors_mk3.py#L78
https://github.com/nortikin/sverchok/blob/3c5ca7077d23bd050483dc926d4c9e08b466266d/data_structure.py#L184
Either deep copy should be used or some other function instead of `full list`.

**Comment by portnov** [comment]
TBH, I'd suggest to deprecate `fullList` method at all :)

**Comment by Durman** [comment]
Will remove `deepcopy` for now.
