### ISSUE TITLE
Loop node performance

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3783]
https://user-images.githubusercontent.com/28003269/102585514-fb410280-4121-11eb-9baf-4f65d0e4b363.mp4

<details> 
  <summary>loop node stats</summary>  

```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    19574    0.389    0.000    0.389    0.000 {built-in method nt.stat}
     6878    0.036    0.000    0.076    0.000 ntpath.py:450(normpath)
     6348    0.035    0.000    0.501    0.000 inspect.py:760(findsource)
    13226    0.033    0.000    0.401    0.000 inspect.py:680(getsourcefile)
     6348    0.025    0.000    0.739    0.000 inspect.py:1444(getframeinfo)
    13226    0.021    0.000    0.048    0.000 inspect.py:642(getfile)
   186611    0.019    0.000    0.019    0.000 {built-in method builtins.isinstance}
     6878    0.014    0.000    0.017    0.000 ntpath.py:122(splitdrive)
    26760    0.013    0.000    0.036    0.000 {built-in method builtins.any}
     6878    0.013    0.000    0.146    0.000 inspect.py:714(getmodule)
     6348    0.011    0.000    0.127    0.000 linecache.py:53(checkcache)
```

```
   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      3/1    0.000    0.000    0.891    0.891 update_system.py:361(do_update_general)
        1    0.000    0.000    0.865    0.865 loop_out.py:149(process)
        1    0.001    0.001    0.865    0.865 loop_out.py:168(for_each_mode)
      530    0.002    0.000    0.797    0.002 logging.py:155(wrapper)
      530    0.000    0.000    0.758    0.001 inspect.py:1511(stack)
      530    0.009    0.000    0.757    0.001 inspect.py:1483(getouterframes)
     6348    0.025    0.000    0.745    0.000 inspect.py:1444(getframeinfo)
      715    0.001    0.000    0.602    0.001 sockets.py:398(sv_set)
      715    0.004    0.000    0.600    0.001 socket_data.py:84(SvSetSocket)
     6348    0.035    0.000    0.507    0.000 inspect.py:760(findsource)
      101    0.002    0.000    0.411    0.004 box_mk2.py:369(process)
       99    0.001    0.000    0.403    0.004 loop_out.py:27(process_looped_nodes)
    13226    0.033    0.000    0.401    0.000 inspect.py:680(getsourcefile)
    19574    0.391    0.000    0.391    0.000 {built-in method nt.stat}
    13226    0.009    0.000    0.284    0.000 genericpath.py:16(exists)
```

</details>

<details> 
  <summary>without loops stats</summary>  

```
   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      100    0.035    0.000    0.038    0.000 stride_tricks.py:206(broadcast_arrays)
      100    0.006    0.000    0.067    0.001 box_mk2.py:67(make_verts)
      187    0.004    0.000    0.004    0.000 {built-in method nt.stat}
      300    0.004    0.000    0.010    0.000 function_base.py:37(linspace)
3001/2001    0.003    0.000    0.059    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
      100    0.002    0.000    0.002    0.000 {built-in method numpy.core._multiarray_umath.c_einsum}
      501    0.002    0.000    0.002    0.000 {method 'reduce' of 'numpy.ufunc' objects}
     1901    0.002    0.000    0.002    0.000 {built-in method numpy.array}
```

</details>

Interesting what purpose of using inspect module in loop node? This looks as cause of the problems.

[untitled.zip](https://github.com/nortikin/sverchok/files/5714152/untitled.zip)

**Comment by vicdoval** [comment]
I have been digging into this too, so far what i have is:
The inspect module is not part of the loop nodes, is part of the profiling system. And if "Print update timings" is enabled it has even worst impact in the loop process, 
The next factor that is slowing the loop process is inside sv_get and corvert_data (implicit conversions) and i'm digging into it.

This loop nodes allow us to test how the update_system reacts to really big trees...

**Comment by Durman** [comment]
It's much better now. This  is how profile looks like with the loop node.
![output](https://user-images.githubusercontent.com/28003269/102850065-00f45c00-4432-11eb-9cd9-e9e58f50e41f.png)
 And without it.
![output](https://user-images.githubusercontent.com/28003269/102850288-8415b200-4432-11eb-9d39-b233f1ca737e.png)

I think this is weak place and probably it can't be improved more in current architecture.

![2020-12-22_08-56-42](https://user-images.githubusercontent.com/28003269/102850824-ba9ffc80-4433-11eb-9d07-08a7de16c22c.png)

It should be one more sign of wrong code design. 

The solution can be to delegate `sv_get` and `sv_set` functionality to the update system. `Process` method can get input data via parameters (`def process(verts, edges, faces)`) and it should have tuple return value with size equal to number of output sockets. But before that it requires refactoring of sockets. They should have more parameters like is it input data mandatory, should last value be repeated and c.e.

**Comment by vicdoval** [comment]
I was thinking of some ways to optimise further the sv_get, but anyway that 2% becomes 0.1% when you use some heavy nodes.

Ideas to reduce sv_get:
getting socket.other from SvLinks dictionary
storing socket_id in the socket (consumes 2%)
Other:  
restrict sv_set to run only if linked (1.5%)
