### ISSUE TITLE
Render curve with round caps?

### ISSUE THREAD

**Issue by mnn** [nortikin/sverchok#3784]
## Problem statement

I would like to convert a simple curve  to a "noodle" (a tube with round ends, like with spheres on its ends). I tried CurveViewer, Polyline Viewer and Skin Mesher but I wasn't able to achieve the wanted result. (This may not be a bug, but just a lack of knowledge on my part. But some of these results look a bit broken.)

## Steps to reproduce

Order is left to right, top to bottom.

<img width="577" alt="2020-12-18_11-14" src="https://user-images.githubusercontent.com/1975567/102602726-34797280-4122-11eb-9508-4d30a5a4594c.png">

profile code:
```
M -0.85,0.1

s -0.15, 0.35 -0.09,0.7
```

## Expected result

I thought polyline viewer or skin mesher would produce wanted result (a noodle).

## Actual result

<img width="356" alt="2020-12-18_11-23" src="https://user-images.githubusercontent.com/1975567/102603744-8373d780-4123-11eb-90b5-76c1057124c3.png">

## Sverchok version

official vstable3 (Stable November 2020)
Blender 2.91.0

**Comment by vicdoval** [comment]
I think this is the simplest way to get there:
![image](https://user-images.githubusercontent.com/10011941/102712934-e9e42b80-42c4-11eb-941b-d32109bd4acf.png)
