### ISSUE TITLE
SV Custom UV Question

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3788]
I have a simple Box that I want to UV, but I would like each polygon face to have the same UV square. How to do this actually?

<img width="1024" alt="Screen Shot 2020-12-21 at 9 38 11 am" src="https://user-images.githubusercontent.com/3952687/102726157-57996180-4370-11eb-89ec-7945891f5fa6.png">

[box_uv_001.blend.zip](https://github.com/nortikin/sverchok/files/5721619/box_uv_001.blend.zip)

**Comment by enzyme69** [comment]
[box_uv_001.blend.zip](https://github.com/nortikin/sverchok/files/5721627/box_uv_001.blend.zip)
<img width="1024" alt="Screen Shot 2020-12-21 at 9 38 11 am" src="https://user-images.githubusercontent.com/3952687/102726194-c5458d80-4370-11eb-855a-c1a6bbe1f542.png">

Ok maybe I figure it out...

**Comment by enzyme69** [comment]
Actually I need the UV to be "reset" so each one is on the same UV square space.

**Comment by Durman** [comment]
![2020-12-21_07-37-49](https://user-images.githubusercontent.com/28003269/102736902-74796900-435f-11eb-885c-a099eb806be7.png)

**Comment by enzyme69** [comment]
That's interesting it rotates the UV "cross" of the Box, I tried:
https://youtu.be/MsduGnT2Zfw

However, what I really want is the "reset" version where every polygon face fits and on top of each other in UV space. And I want to later scale them and then "randomize" because I have this Texture Atlas and I want to somewhat use grid to randomize the UV of objects being generated.

[box_uv_002.blend.zip](https://github.com/nortikin/sverchok/files/5724103/box_uv_002.blend.zip)


<img width="945" alt="Screen Shot 2020-12-21 at 10 37 24 pm" src="https://user-images.githubusercontent.com/3952687/102773324-286d0980-43dd-11eb-94d6-020ad2ea0ff4.png">

**Comment by enzyme69** [comment]
Need 6 projection from 6 different sides..

<img width="1012" alt="Screen Shot 2020-12-21 at 10 59 18 pm" src="https://user-images.githubusercontent.com/3952687/102775022-2fe1e200-43e0-11eb-839b-f1709972fb41.png">

**Comment by enzyme69** [comment]
So far my "hacky solution" is to have another box, reset the UV, and then use it for the actual Box UV. If I do this, the scale does not work properly.

<img width="766" alt="Screen Shot 2020-12-21 at 11 12 30 pm" src="https://user-images.githubusercontent.com/3952687/102775958-01fd9d00-43e2-11eb-9f8e-c941b4cc6545.png">

**Comment by enzyme69** [comment]
Maybe this is the way :) I started to get a hang of it. This is a very cool node! Thanks Durman~

<img width="1038" alt="Screen Shot 2020-12-21 at 11 19 54 pm" src="https://user-images.githubusercontent.com/3952687/102776560-0aa2a300-43e3-11eb-8d75-8141232ee05f.png">

**Comment by Durman** [comment]
Something like this?
![2020-12-21_18-35-56](https://user-images.githubusercontent.com/28003269/102788015-69ecbd00-43bb-11eb-9381-3e683278b226.png)
[box_uv_002.zip](https://github.com/nortikin/sverchok/files/5724863/box_uv_002.zip)

**Comment by enzyme69** [comment]
THANKS DURMAN! Merry Christmas!
