### ISSUE TITLE
Cannot to enable add-on.

### ISSUE THREAD

**Issue by IllianDeCube09** [nortikin/sverchok#3791]
I cannot enable the installed add-on from the archive, as it produces a lot of errors. The solution to this problem, which is described on the site, is not suitable, since the archive just doesn't have a folder with dots in the name.
![изображение](https://user-images.githubusercontent.com/68920871/102824417-d5e81900-43ed-11eb-9346-217b062d22c3.png)

**Comment by zeffii** [comment]
rename `sverchok_master` to `sverchok`

**Comment by IllianDeCube09** [comment]
> 
> 
> rename `sverchok-master` to `sverchok`

Doesn't work, the error is the same.

**Comment by zeffii** [comment]
what version of windows are you using?

**Comment by zeffii** [comment]
you may also want to use a more recent version of Blender.  https://builder.blender.org/download/

**Comment by zeffii** [comment]
are you using Python as provided by Blender or are you using your system's Python ?

**Comment by IllianDeCube09** [comment]
Windows 10, Blender version 2.90.1, using installed python.

**Comment by zeffii** [comment]
> Blender version 2.90.1, using installed python. 

the version that comes with Blender  or the python you installed yourself?

**Comment by zeffii** [comment]
when you're in Blender and open the blender python console can you successfully 
```
import scipy
```
or does that throw an error too?

**Comment by IllianDeCube09** [comment]
> 
> 
> > Blender version 2.90.1, using installed python.
> 
> the version that comes with Blender or the python you installed yourself?

I have Python both from Blender and separately installed. I'm not good at programming, so I can't figure out what's wrong with installing the addon. I used it before, but deleted it for some reason.

**Comment by nortikin** [comment]
сцыпай не верно встал внутри блендера как-то. Снести папку там и заново правильно по инструкции установить через пип

**Comment by IllianDeCube09** [comment]
> 
> 
> сцыпай не верно встал внутри блендера как-то. Снести папку там и заново правильно по инструкции установить через пип

Попробовал установить в Блендеровский питон последнюю версию SciPy, но ничего не поменялось, аддон не активируется, выдавая всё ту же ошибку.

**Comment by nortikin** [comment]
> > сцыпай не верно встал внутри блендера как-то. Снести папку там и заново правильно по инструкции установить через пип
> 
> Попробовал установить в Блендеровский питон последнюю версию SciPy, но ничего не поменялось, аддон не активируется, выдавая всё ту же ошибку.

надо решать не в системе, а в блендере. следуй инструкциям https://github.com/nortikin/sverchok/wiki/Dependencies

**Comment by IllianDeCube09** [comment]
> 
> 
> > > сцыпай не верно встал внутри блендера как-то. Снести папку там и заново правильно по инструкции установить через пип
> > 
> > 
> > Попробовал установить в Блендеровский питон последнюю версию SciPy, но ничего не поменялось, аддон не активируется, выдавая всё ту же ошибку.
> 
> надо решать не в системе, а в блендере. следуй инструкциям https://github.com/nortikin/sverchok/wiki/Dependencies

Да, это помогло, спасибо)
