### ISSUE TITLE
Presets menu Bug

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#3799]
Failing the tests in #3798 made me check that it may be related to the Presets in the shift+a menu 
Every node appears there with a empty menu. In this the expected behaviour?
![image](https://user-images.githubusercontent.com/10011941/103182646-62428200-48ad-11eb-9bba-e178f2a5680c.png)

**Comment by Durman** [comment]
Probably the same problem here #3661

**Comment by portnov** [comment]
Please check #3800.
