### ISSUE TITLE
"Curve Curvature" node outputs wrong values for FreeCAD curves

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3804]
I created a simple test case using 1m arc (converted to NURBS).
Curvature node outputs 1.0 when Native and Geomdl are used, but when FreeCAD is used the values are not 1.0.  

![FreeCAD_NURBS_Curve_WrongCurvature](https://user-images.githubusercontent.com/66558924/103416276-94463380-4b8e-11eb-8b4f-662185e8e889.jpg)

Here's the test file I'm using: 
[FreeCAD_NURBS_Curve_WrongCurvature.zip](https://github.com/nortikin/sverchok/files/5757616/FreeCAD_NURBS_Curve_WrongCurvature.zip)

**Comment by rendetto** [comment]
I did a test to visualize the arc center point and it's not where it is supposed to be:
![FreeCAD_NURBS_Curve_Center](https://user-images.githubusercontent.com/66558924/106133542-1285fd80-616e-11eb-9e11-7add2c72af53.jpg)
Also the arc Radius seem to oscillate around 1.0.

**Comment by portnov** [comment]
Other implementations give correct result?

**Comment by rendetto** [comment]
Yes, others are fine. Just FreeCAD is doing this and only for curves. 
FreeCAD surfaces don't have such problems.

**Comment by portnov** [comment]
I see. FreeCAD's Nurbs API does not have explicit methods for 2nd derivative; so the curvature is evaluated numerically, hence there is precision loss. I can try to add some kind of "precision" parameter to the node, so the user could somehow try to control this loss of precision...

**Comment by rendetto** [comment]
Sounds great! I'm surprised that FreeCAD lacks such basic feature. I just found that OCC has it and even 3rd derivative:
https://dev.opencascade.org/doc/refman/html/class_geom_adaptor___curve.html#ab233e6b1967c5da228701cac6400d88d

Did you ever considered implementing PythonOCC? I know it's huge thing but it's the whole OCC.

**Comment by rendetto** [comment]
I just found curvatureAt() and centerOfCurvatureAt() methods at this page (scroll to the bottom):
https://wiki.freecadweb.org/TopoShape_API

**Comment by portnov** [comment]
Hm, I'll look into it.

**Comment by rendetto** [comment]
Your idea about adding a "precision" parameter on the existing algorithm looks really promising.
Because even if those FreeCAD methods solve the curvature, radius and center problems, there's also a torsion problem.
Torsion from FreeCAD curve gets also precision loss, and I didn't found such method on the FreeCAD API.

I'm not much into math so I don't know if some hybrid approach will be possible, e.g. deriving torsion from curvatureAt() somehow.
Maybe an option for switching between Native and FreeCAD method will be an optimal solution?

Thanks

**Comment by rendetto** [comment]
@portnov I tested adding the curvatureAt() method to freecad.py and the node now outputs correct results. 
![Fix_FreeCAD_NURBS_Curve_WrongCurvature](https://user-images.githubusercontent.com/66558924/126442150-0f17eb6a-763a-4445-a55a-c56d85004125.jpg)
I simply replicated the tangents code, but I'm sure that I messed the things up. Please can you take a look at it. 
[freecad.zip](https://github.com/nortikin/sverchok/files/6853371/freecad.zip)

While we can use curvatureAt() for the curvature/radius and center, there is still the problem with the torsion node and FreeCAD does not have an explicit API for it. So can you please consider implementing your first idea - adding a precision parameter to the original implementation of second and third derivatives?

Thanks

**Comment by portnov** [comment]
It appears that the problem was that I used `tangent` method of FreeCad's curves, while thinking that it returns the derivative of the curve; while it returns the normalized derivative vector. For non-normalized derivative, FreeCad has `getD1` method.
