### ISSUE TITLE
Creating connections between different objects

### ISSUE THREAD

**Issue by brunoperdigao** [nortikin/sverchok#3813]
Hey everyone,
I was looking at this Grasshopper tutorial and I would like to know if there is a similar approach in Sverchok. 
https://www.youtube.com/watch?v=IqH2xH_W4Y4 This is done with another plugin in Grasshopper, but I was hoping to replicate just the basics. I created an extruded hexagon and was able to randomly create matrices in up to three selected faces. But the new hexagons are created by their origin, so they connect with the bottom face. Is there a way I can change the origin of the new objects or there is another better approach for this problem? Thanks

![image](https://user-images.githubusercontent.com/57102715/103942927-f2839100-510f-11eb-8d04-e5d9b7fa606c.png)

**Comment by vicdoval** [comment]
Probably there are simpler ways... :)
![image](https://user-images.githubusercontent.com/10011941/103945219-258c4b80-5135-11eb-8f74-2ef613662ef4.png)

**Comment by brunoperdigao** [comment]
Thanks @vicdoval
I was trying to achieve this kind of result, that has randomness. Would the loop node be the best approach?
![image](https://user-images.githubusercontent.com/57102715/103963117-46ee3700-5137-11eb-9ad3-b4ea6b281070.png)

**Comment by vicdoval** [comment]
If all you need is some random hexagon tiles you could do it like this:
![image](https://user-images.githubusercontent.com/10011941/103988048-b8f16b00-518d-11eb-85bd-2f4b55b33f56.png)
If you want some kind of path you could check the Turtle api https://github.com/nortikin/sverchok/pull/2760
If you want to emulate the Wasp plug-in with grow rules and collision detection then you can probably do it with the Loop Nodes
Or even you could write the developer to invite him to port Wasp to Sverchok maybe following the parsing style of https://github.com/ladybug-tools/ladybug-blender 😃
