### ISSUE TITLE
"List Item" node issue

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3815]
I got strange behavior when connecting "List Item" nodes to "Objects In" or "Text In +". 
I can't figure it out what's happening because it seems a bit erratic, so I did some videos.

The results change when more than one "List Item" is used, but also the input data is somehow changed.

https://user-images.githubusercontent.com/66558924/104016162-667c7280-51be-11eb-8899-c22151e03e90.mp4

https://user-images.githubusercontent.com/66558924/104015853-e8b86700-51bd-11eb-93e2-dea6bac02456.mp4

I'm uploading the test file: 
[List_Item_bug2.zip](https://github.com/nortikin/sverchok/files/5787210/List_Item_bug2.zip)

**Comment by vicdoval** [comment]
@rendetto Thanks for reporting, now should be fixed

**Comment by rendetto** [comment]
Big thank you @vicdoval ! It now works as expected.
