### ISSUE TITLE
Render Gallery 2021

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#3817]
Previous gallery ticket: #2814.

https://github.com/nortikin/sverchok/issues/3688
partially here. Start from Fasade:
![изображение](https://user-images.githubusercontent.com/5783432/104107748-d75f7f80-52cf-11eb-8b51-dfc81fff423b.png)
[lesson.blend.zip](https://github.com/nortikin/sverchok/files/5791764/lesson.blend.zip)

**Comment by nortikin** [comment]
continuation
https://youtu.be/LHYkljAo4Z4

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/105986146-8ca27d80-60ad-11eb-8e36-efb0c4da3034.png)
![изображение](https://user-images.githubusercontent.com/5783432/105986154-91ffc800-60ad-11eb-9d5b-86aad0b7b26a.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/105988954-77c7e900-60b1-11eb-90c0-9ff75af738d3.png)
![изображение](https://user-images.githubusercontent.com/5783432/105989335-050b3d80-60b2-11eb-92b1-b7673921d348.png)
![изображение](https://user-images.githubusercontent.com/5783432/105989386-18b6a400-60b2-11eb-9f3d-133926fc4f72.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/105989422-279d5680-60b2-11eb-8c45-2028b2994ac5.png)

**Comment by nortikin** [comment]
https://disk.yandex.ru/a/PK8LcF0zcKW4Hg
Collected some. Hope it will help.
also artists list:
http://nortikin.github.io/sverchok/#Gallery - page' bottom

**Comment by portnov** [comment]
![Screenshot_20210704_210017](https://user-images.githubusercontent.com/284644/124391628-f6811c00-dd0a-11eb-877d-2c593796b239.png)

**Comment by Durman** [comment]
![Thumbnail](https://user-images.githubusercontent.com/28003269/124447341-51118b00-dd92-11eb-855d-def5c50feebb.jpg)

**Comment by vkter** [comment]
![屏幕截图 2021-07-11 211432](https://user-images.githubusercontent.com/74725748/125196722-6ce2c880-e28d-11eb-999e-b6fe544e08fe.png)

**Comment by enzyme69** [comment]
@vkter That's insanely great looking virus. RenderMan 24?

**Comment by vkter** [comment]
> @vkter这是疯狂的伟大的病毒。渲染人 24？
Yes, this is what I just rendered, and it uses sverchok to generate

**Comment by vkter** [comment]
> @vkter That's insanely great looking virus. RenderMan 24?

Yes, this is what I just rendered, and it uses sverchok to generate

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/164980872-5f049fd0-22ec-4f15-a250-8833717e8882.png)
