### ISSUE TITLE
Create Monad problem

### ISSUE THREAD

**Issue by molotok89** [nortikin/sverchok#3818]
## Problem statement
Error while i'm trying to add a new Monad by CTRL-G. 
And exception when i connect inputs on just added the new Monad

## Steps to reproduce

1. Select needed nodes to group. 
2. Push short keys CTRL-G to group
3. Get an Python error and no Nodes were grouped.
4. Another way i push short keys SHIFT-CTRL-G
5. The Monad was added successfully
6. Go UP to parent node and try to connect the first input
7. Get an exception and the Blender was closed

## Expected result

What did you expect to see as a result of those steps?

## Actual result
Errors for Step 3
Python: Traceback (most recent call last):
  File "/Users/alexss/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/utils/monad.py", line 641, in execute
    re_links = link_monad(monad, links)
  File "/Users/alexss/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/utils/monad.py", line 519, in link_monad
    to_socket = nodes[link.to_node.name].inputs[link.to_socket.index]
AttributeError: 'NodeSocketColor' object has no attribute 'index'

location: <unknown location>:-1

Python: Traceback (most recent call last):
  File "/Users/alexss/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/ui/development.py", line 117, in execute
    help_url = string_dir + '/' + filename
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

location: <unknown location>:-1

2021-01-10 12:08:40,272 [ERROR] sverchok.core.update_system: Node Monad.004 had exception: 'bpy_prop_collection[key]: key "Monad.004" not found'
Traceback (most recent call last):
  File "/Users/alexss/Library/Application Support/Blender/2.91/scripts/addons/sverchok-master/core/update_system.py", line 381, in do_update_general
    node = nodes[node_name]
KeyError: 'bpy_prop_collection[key]: key "Monad.004" not found'
2021-01-10 12:08:44,554 [WARNING] sverchok.core.sockets: Socket='connect me' of node='Group Outputs Exp' can't update number of objects on the label. Cause is 'sv_get() got an unexpected keyword argument 'deepcopy''

## Sverchok version
MAC OS
Blender 2.9.1 and 2.92 Alpa 
Sverchok was installed on 10.01.2021 from sverchok-master.zip from github
Latest commit is f0fa758 : by nortikin  :  Merge branch 'master' into nedovizin_developer...

**Comment by Durman** [comment]
Don't use monad nodes. They are not supported. You can use group nodes instead. In general they fully functional now. Groups just could not be imported into JSON format but they can imported via standard Blender `append` functionality.
![2021-01-10_21-39-14](https://user-images.githubusercontent.com/28003269/104130820-50241180-538c-11eb-8cc1-fdef19267612.png)

**Comment by molotok89** [comment]
> Don't use monad nodes. They are not supported. You can use group nodes instead. In general they fully functional now. Groups just could not be imported into JSON format but they can imported via standard Blender `append` functionality.
> ![2021-01-10_21-39-14](https://user-images.githubusercontent.com/28003269/104130820-50241180-538c-11eb-8cc1-fdef19267612.png)

It's work. Cool,
Thank you

**Comment by vicdoval** [comment]
> Don't use monad nodes. They are not supported. You can use group nodes instead. In general they fully functional now. Groups just could not be imported into JSON format but they can imported via standard Blender `append` functionality.
> ![2021-01-10_21-39-14](https://user-images.githubusercontent.com/28003269/104130820-50241180-538c-11eb-8cc1-fdef19267612.png)

@Durman Are you planning you to implement the json import/export so they can be saved as presets?

**Comment by Durman** [comment]
Yes, I'm going to. It will require new JSON format.

**Comment by Cactice** [comment]
@Durman 
How's the progress on importing/exporting groups to JSON?
I'd love to export to JSON but it seems unavailable for now.

**Comment by Durman** [comment]
@Cactice If your desire is to import a node group from one tree to another you can use standard Blender `append` functionality. It's working correctly. 

The current progress is I didn't even started. I was developing several nodes last weekends and I'm going to devote at least some next weekends to Sverckok too but I did not decided on what to spend the time yet. Implementing import node groups into JSON looks pretty boring and I did not manage to force myself focusing on that. Also there is a problem of registering outdated nodes inside node groups. It looks more important to fix that first of all.

**Comment by Cactice** [comment]
@Durman 
I see. 
My desire was to manage sverchok files on git so I think `append` isn't going to help me much.
Anyways I appreciate your effort on this project🚀
