### ISSUE TITLE
Viewer Draw bug (Eevee Material Preview)

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3832]
I noticed that the preview geometry I got from the Viewer Draw node disappears randomly when Material Preview is used in the viewport. This happens when I hide the source object (a mesh Plane in this case).

https://user-images.githubusercontent.com/66558924/104961190-7f66fe00-59de-11eb-8bf2-485d54076bc8.mp4

Here is the file I'm testing with:
[view_bug.zip](https://github.com/nortikin/sverchok/files/5832320/view_bug.zip)

**Comment by vicdoval** [comment]
The viewer draw creates a overlay with the geometry, not 'real' blender geometry... it seems a blender bug with the blg module so I dont think we can do anything about it... more than reporting it with a extract of the code that fails...

**Comment by zeffii** [comment]
Doesn't happen here, maybe update Blender.

it would be interesting to know what kind of videocard / blender graphics configuration you have, especially when this is related to openGL / fragment shading

**Comment by rendetto** [comment]
I run Blender2.91.2(official) under Win10 with NVIDIA GTX 1070.

**Comment by zeffii** [comment]
what happens when you try one of the fresher builds from https://builder.blender.org/download/

**Comment by rendetto** [comment]
@zeffii Thanks for the suggestion. Just tested "blender-2.93.0-d30320b4f59d-windows64" and there is no such problem.
Closing...
