### ISSUE TITLE
Blender crash on loading file with exec node 

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3833]
A couple of blend files had given me this crash on load, which I suspect is due to the exec **node mod node** that has a call to render the scene (bpy.ops.render.render(use_viewport=True). See the screenshot, screencapture and blender's crash file for reference.

I’m not sure if this is expected (maybe i’m doing something i’m not supposed to do within a SV node, e.g. calling the render image on frame change) like in the attached setup. The odd thing is though this node setup works fine most of the time.. it’s only occasionally that it crashes while creating the node tree, but it always crashes on loading the file with this node tree. The only way to get it to not crash on load is to first deactivate the SV add-on. 

I’m running SV master branch (e8f3ceccd5a5ebf59e6244fe796fe5e5a3ef9ef2) with blender 2.91, btw.

Once you load the blend file, advancing to a new frame (left, right buttons) should automatically render the new frame. The render is set to 32x32 pixels so its super fast. I am basically what i’m trying to do is to have a node setup that would trigger a render of the scene for the active camera on frame change. 

Aside from checking if this is a real “exec node" bug or not, if you guys have an alternative solution that is more suitable to accomplish this "auto-render on frame change" please let me know. 

gracias!

<img width="1680" alt="execNodeMod-Crash" src="https://user-images.githubusercontent.com/2083719/104964408-5d538880-59aa-11eb-96ca-de3e22fb757d.png">

[execNodeCrash.zip](https://github.com/nortikin/sverchok/files/5832465/execNodeCrash.zip)

**Comment by Durman** [comment]
You can try to register your own handler sensitive to frame changes.
https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.frame_change_post

**Comment by DolphinDream** [comment]
> You can try to register your own handler sensitive to frame changes.
> https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.frame_change_post

Yeah.. unfortunately this solution also crashes Blender (pasted this in the blender console)
```
import bpy
def my_handler(scene):
    bpy.ops.render.render(use_viewport=True)
bpy.app.handlers.frame_change_post.append(my_handler)

```

**Comment by zeffii** [comment]
maybe a flag `sverchok.ready`,  which we set to `True` after blend `post load` handler has completed, and `False` duing `pre load` ?
and you would write
```python
import sverchok
if sverchok.ready:
     bpy.ops.render.render(use_viewport=True)
```

**Comment by DolphinDream** [comment]
> maybe a flag `sverchok.ready`, which we set to `True` after blend `post load` handler has completed, and `False` duing `pre load` ?
> and you would write
> 
> ```python
> import sverchok
> if sverchok.ready:
>      bpy.ops.render.render(use_viewport=True)
> ```
> 
> or `sverchok.post_load_handler_completed`

Could you elaborate? Would i put this code iside of my_handler? .. so that it only executes the render code if the sv.ready is true?

**Comment by zeffii** [comment]
i'll show you what i mean.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/3839


then you would write
```python
import sverchok
if sverchok.update_system.is_postload_complete():
    bpy.ops.render.render(use_viewport=True)
```

**Comment by DolphinDream** [comment]
Apparently Brecht thinks this is normal behavior :) as rendering call will cause an infinite loop (as it changes the frame?? thus calling the handler again). I don’t know why rendering the frame would trigger a call to the post load handler though.

https://developer.blender.org/T84868

I wonder if you could somehow deactivate the handler.. and reactivate it after the render is done.

**Comment by zeffii** [comment]
i see, well that's good to know. The problem with using some `bpy.ops` is that they come with "side effects" like this.

**Comment by zeffii** [comment]
until such time as the `bpy.ops.render.render` operator code is changed, (like it gets an additional keyword argument `auto_frame_change = False`, your option is to use a script and trigger that instead.

start here https://github.com/nortikin/sverchok/issues/2390#issuecomment-492712076

**Comment by zeffii** [comment]
am closing this, i hope you understand it is not something fixable on our end in this very specific scenario. altho it is a pain , the render script approach should offer considerable freedom beyond sverchok.
