### ISSUE TITLE
Rewire Cylinder Flips the Normals....

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3835]
I often found a need of Cylinder in X, Y, Z axis, so I often use it with Rewire, however Rewire node sometimes flip the normal. Strange behaviour.

<img width="561" alt="Screen Shot 2021-01-20 at 9 28 17 am" src="https://user-images.githubusercontent.com/3952687/105100793-f21cca00-5b01-11eb-8423-3cb7c3339dea.png">

[cylinder_rewire_001.blend.zip](https://github.com/nortikin/sverchok/files/5838925/cylinder_rewire_001.blend.zip)

**Comment by Durman** [comment]
#3278
