### ISSUE TITLE
Strange Empty Data issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3846]
I probably needs to demonstrate this but few days ago I started to notice a lot of error "Empty Data" when dealing with Vertex -> Curve -> Curve Evaluate.

<img width="1238" alt="Screen Shot 2021-01-26 at 8 07 59 pm" src="https://user-images.githubusercontent.com/3952687/105824346-54019600-6012-11eb-8d6c-dd5f8915e704.png">

[pipe_arrow_anim_along_path_005.blend.zip](https://github.com/nortikin/sverchok/files/5872303/pipe_arrow_anim_along_path_005.blend.zip)

**Comment by enzyme69** [comment]
So many nodes did not work, I am using Blender 2.90.1 and 2.92 same deals.

<img width="952" alt="Screen Shot 2021-01-26 at 8 18 56 pm" src="https://user-images.githubusercontent.com/3952687/105825464-ba3ae880-6013-11eb-8d7c-ae8e20de8c04.png">

**Comment by rendetto** [comment]
What if you update the tree? Did you still got the error?

**Comment by enzyme69** [comment]
I tried the "update the tree" button but this error still showing up.

I just encounter it in a different setup that should work if I rebuild from scratch, but no luck.

<img width="755" alt="Screen Shot 2021-01-27 at 10 11 37 am" src="https://user-images.githubusercontent.com/3952687/105918500-20f9e980-6088-11eb-9a78-cf40468ff201.png">

[path_loop_001.blend.zip](https://github.com/nortikin/sverchok/files/5876686/path_loop_001.blend.zip)

**Comment by enzyme69** [comment]
This bug makes SV unusable ⚠️ @nortikin

**Comment by Durman** [comment]
@vicdoval Could you check whether this changes effects `detecting new links` code? When I was adding this code I checked but I could miss something. Not sure but this can be one of the reason of instability.

https://github.com/nortikin/sverchok/blob/9ad18096aeba9c555f76184bd528bcd6c0d4df99/core/node_group.py#L928-L930

https://github.com/nortikin/sverchok/blob/9ad18096aeba9c555f76184bd528bcd6c0d4df99/core/node_group.py#L940-L943

**Comment by vicdoval** [comment]
> I probably needs to demonstrate this but few days ago I started to notice a lot of error "Empty Data" when dealing with Vertex -> Curve -> Curve Evaluate.
> 
> <img alt="Screen Shot 2021-01-26 at 8 07 59 pm" width="1238" src="https://user-images.githubusercontent.com/3952687/105824346-54019600-6012-11eb-8d6c-dd5f8915e704.png">
> 
> [pipe_arrow_anim_along_path_005.blend.zip](https://github.com/nortikin/sverchok/files/5872303/pipe_arrow_anim_along_path_005.blend.zip)

Here i could not replicate your error, the nodetree is working with no errors

**Comment by rendetto** [comment]
This is bizarre. I can not reproduce it either.

It is an error I also get in my setups, but in random fashion.

**Comment by vicdoval** [comment]
> I tried the "update the tree" button but this error still showing up.
> 
> I just encounter it in a different setup that should work if I rebuild from scratch, but no luck.
> 
> <img alt="Screen Shot 2021-01-27 at 10 11 37 am" width="755" src="https://user-images.githubusercontent.com/3952687/105918500-20f9e980-6088-11eb-9a78-cf40468ff201.png">
> 
> [path_loop_001.blend.zip](https://github.com/nortikin/sverchok/files/5876686/path_loop_001.blend.zip)

And i this one i see some weird things in your file
check where this objects are :
![image](https://user-images.githubusercontent.com/10011941/105959889-c7d88880-607c-11eb-952c-edd284b3d384.png)
![image](https://user-images.githubusercontent.com/10011941/105959940-d7f06800-607c-11eb-89c6-0f03fed05d92.png)
i think this makes troubles with the viewer draw (seems a blender thing) when you delete them the viewers go back to work.

Another strange thing is this
![image](https://user-images.githubusercontent.com/10011941/105960327-59e09100-607d-11eb-8b75-a839502bb431.png)
You are passing a "t" value from -1.55 to 3.83 but the curve domain is from 0 to 1... that should give a pretty weird output.

I can't find any real bug in here

**Comment by rendetto** [comment]
About the "T" value.. Depending on the knot vector of the curve and implementation it could be totally valid to evaluate it outside domain. FreeCAD and GEOMDL now give equal results (see https://github.com/orbingol/NURBS-Python/issues/115). Though you should be careful with the Native implementation.

**Comment by vicdoval** [comment]
@rendetto i know it can be valid, but in the case of a this random spline the matrix locations go pretty far 
![image](https://user-images.githubusercontent.com/10011941/105966767-5f41d980-6085-11eb-8037-1e9a1ec71045.png)

**Comment by rendetto** [comment]
@vicdoval Totally agreed!

**Comment by enzyme69** [comment]
So far, I think when this bug happened, suddenly SV is not updating properly, nodes no longer works no matter what, even simple Viewer Draw or Mesh Viewer no longer responding. Appending the node tree into empty Blend does not help.

**Comment by Durman** [comment]
Can be relevant #3795

**Comment by rendetto** [comment]
I got lots of these situations where the whole tree stuck when just one error is present. It could be a lifesaver if we have the ability to include/exclude a node or whole branch from the tree execution as it will help isolating the problem. At least I'm not aware of such functionality.

**Comment by Durman** [comment]
Update system just should update us many nodes as possible. At the present as you said it's stopping updating tree immediately after encountering with first error node. For example node groups have different update system which is a bit cleverer on this matter.

**Comment by vicdoval** [comment]
When you link a stethoscope (or any other node) to any node that triggers A or B:
A update of that node (if the socket was free)  and the stethoscope
B only updates the stethoscope (if the socket was linked) 

that way you can check if there is a proper output coming out from that node... 

If it is not a good output like [ ] or shows a error it can be the source of the error or the error can be upstream. 

That's how I handle this situations if i don't want to check the console

**Comment by rendetto** [comment]
@Durman are node groups documented? I want to check those with my workflow.

**Comment by enzyme69** [comment]
Whenever "red text error" appears, SV stops working.

**Comment by enzyme69** [comment]
Apparently "Process Layout" is turned off when this "stuff" happens. And needs to be manually pressed for it to start working again!

**Comment by Durman** [comment]
> @Durman are node groups documented? I want to check those with my workflow.

No, but usage of nodes groups should be clear enough. It is more or less similar to node groups of the shader editor.
