### ISSUE TITLE
bug in the switcher

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#3847]
## Problem statement

A small bug in the switcher. After loading a previously saved json file all the buttons in the switcher are active although Multi Selection is disabled
![Снимок](https://user-images.githubusercontent.com/62519357/105846153-cf505100-5fec-11eb-9e77-0b279b0a5634.JPG)

## Steps to reproduce

1. Fix a bug

## Expected result

Fix a bug
## Sverchok version

sverchok-master.zip+updates via the Internet, Blender 2.91.2

**Comment by maxim1967** [comment]
1)If nothing was selected when saving, the first button will be active when opening the file later.
2)If the first button was selected when saving, then no button will be active when opening the file later.
3)If any button other than the first one was selected during the save, the first button + the button selected during the save will be active when the file is opened later.

1)Если при сохранении ничего не было выбрано, то первая кнопка будет активна при последующем открытии файла.
2)Если при сохранении была выбрана первая кнопка, то при последующем открытии файла ни одна кнопка активна не будет.
3)Если во время сохранения была выбрана какая-либо кнопка, отличная от первой, то первая кнопка + кнопка выбранная во время сохранения, будет активна при последующем открытии файла.

**Comment by Durman** [comment]
@maxim1967 It shoudl work now.
