### ISSUE TITLE
"Object in" node's output vertices issue

### ISSUE THREAD

**Issue by hypnospheres** [nortikin/sverchok#3851]
Hi everyone! I'm new to Sverchok ;)
Is it possible **to change X-step for the vertex array** that refers to _graph_ in the node _Object in_? Right now X=[0, 2.4, 5, 7.8..], and here is what I want to achieve х=[1, 2, 3..]

Maybe there should be some different relation with the object _graph_?

![изображение](https://user-images.githubusercontent.com/78083986/105987313-2ae31300-60af-11eb-83f7-fea67e9b0ff2.png)
graph curve with vertex indexes from _Object in_ that i have now, but i need uniform step 
![изображение](https://user-images.githubusercontent.com/78083986/105987331-333b4e00-60af-11eb-9c35-e674198f4d2d.png)

thank you for the reply!

**Comment by nortikin** [comment]
`scale` on `x` or `vector out/in` with `match` from category `numbers` in between
