### ISSUE TITLE
Sverchok website and online documentation down

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3852]
I cannot access http://nikitron.cc.ua/sverchok_en.html nor http://nikitron.cc.ua/sverch/html/main.html

**Comment by nortikin** [comment]
it is blocket by 1gb . ua because of some abuse (w/o explanation).
Lets go to http://nortikin.github.io/sverchok/

**Comment by vicdoval** [comment]
the documentation linked there is very outdated...

**Comment by nortikin** [comment]
fixed. just to change links inside sverchok and all links
maybe i could reviel placeholder for redirect site on cc.ua to make it redirect

**Comment by nortikin** [comment]
CSS for docs going crazy on gh-pages io site.what is going on?

**Comment by nortikin** [comment]
docs are there already

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/106045626-415e8e00-60f2-11eb-957f-04c4e83fdfbe.png)
How to share ability to create new manual stables?
@zeffii

**Comment by zeffii** [comment]
no idea @nortikin , i tried to update a while back but no luck.
