### ISSUE TITLE
Circlify node suddenly missing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3853]
A few days ago, we have Circlify node that is suddenly missing. Circlify node is supposedly generating circle inside another circle, providing radius.

**Comment by rendetto** [comment]
Can you check first if the library is loaded?
![Blender Preferences](https://user-images.githubusercontent.com/66558924/106062639-bbe1da80-60ff-11eb-92d6-0317ade464ce.jpg)
This is inside Sverchok addon in Extra Nodes dependencies.

**Comment by enzyme69** [comment]
<img width="769" alt="Screen Shot 2021-01-28 at 2 35 20 pm" src="https://user-images.githubusercontent.com/3952687/106086362-1ddd2700-6176-11eb-952e-ea8990f3938f.png">

Aha, that's why, I did enable that "extra" many months ago. Cheers!

**Comment by nortikin** [comment]
we can make some simple packing for CNC with that
