### ISSUE TITLE
Fitting Circle into Triangle

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3855]
A while back ago we have SNL that fits Circle into Triangles:
https://github.com/enzyme69/blendersushi/issues/408

But it seems to disappear. And we have Circle Fit node but it does not seem to work the same.

Is there anyway to find the Circle Fit SNL

**Comment by Durman** [comment]
You can find all scripts in the path which you can see on the picture below. Also there is history button which leads to the page where all changes made in the folder are shown. You can try to search via the history whether the script was deleted.

![2021-01-28_08-50-30](https://user-images.githubusercontent.com/28003269/106091453-ece4fe00-6145-11eb-965a-a357acd51512.png)

**Comment by enzyme69** [comment]
Thanks Durman!

**Comment by enzyme69** [comment]
@nortikin Nikitron you deleted this SNL? Why?

**Comment by vicdoval** [comment]
did you see this?: 
![image](https://user-images.githubusercontent.com/10011941/106110186-b067d100-614a-11eb-9b5a-2674888aa1c7.png)

**Comment by enzyme69** [comment]
I totally forgot that node, thanks Vic!

**Comment by nortikin** [comment]
> @nortikin Nikitron you deleted this SNL? Why? weary

o_O
