### ISSUE TITLE
Maybe Texture Viewer is broken

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3858]
I tried the basic example of Texture Viewer node, but getting strange image texture output:

<img width="572" alt="Screen Shot 2021-01-29 at 1 06 01 am" src="https://user-images.githubusercontent.com/3952687/106149329-3d07a300-61ce-11eb-9140-6d409f6cae50.png">

**Comment by vicdoval** [comment]
Hoy need to match the num x of the plane with thw pixels of the texture (128 in the shown case)

**Comment by enzyme69** [comment]
Ah! Cool cool! Got it thanks Vic!

<img width="966" alt="Screen Shot 2021-01-29 at 10 55 13 am" src="https://user-images.githubusercontent.com/3952687/106213289-779a2b80-6220-11eb-93e2-8e9399d37c9a.png">
