### ISSUE TITLE
about SNLite_templates/shape_key_bake.py。How to use this node?

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#3859]
## Problem statement

Please describe your problem here.

## Steps to reproduce

1. 
2. 
3. 

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by vicdoval** [comment]
Seems that that script is not updated....

**Comment by nortikin** [comment]
updated just now
