### ISSUE TITLE
ViewerDraw inside Group

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#3863]
I guess I'm failing at understanding how to use group nodes.
What I did is to try incorporating a ViewerDraw node inside a group.
The output didn't visualize the curve.

![group_test1](https://user-images.githubusercontent.com/66558924/106354950-d71a3900-62fd-11eb-994f-89c8448cf9e4.jpg)

What I'm doing wrong?
This is the file I'm testing with:
[Groups_Test1.zip](https://github.com/nortikin/sverchok/files/5897837/Groups_Test1.zip)

Thanks

**Comment by vicdoval** [comment]
Now Sverchok offers two types of groups. The old one (that will be depreciated at some point) are called Monads, the one you are using, and does not support viewers inside it. 
The new ones, called Groups, are still in Alpha stage and they still neither support viewers inside....

**Comment by rendetto** [comment]
Thanks for the explanation @vicdoval. So I'm confused now. Where are those new groups, because I've found only those:
![monad](https://user-images.githubusercontent.com/66558924/106356391-e7cfac80-6307-11eb-9836-cfd0d5564cf9.jpg)
Thanks

**Comment by vicdoval** [comment]
in the lastest sverchok you can find them in the shift+a menu 
![image](https://user-images.githubusercontent.com/10011941/106357203-eb156900-6304-11eb-87d1-ea2ba07e24d3.png)

**Comment by rendetto** [comment]
Thanks! It's shame I'm rarely using Shift+A 😄 
Closing
