### ISSUE TITLE
Select mesh elements by location

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3869]
![2021-02-02_12-48-59](https://user-images.githubusercontent.com/28003269/106575080-17272900-6555-11eb-83c1-ab8e56ea466a.png)
I think at least one of the node output should have false value.

#3423 ?

**Comment by Durman** [comment]
I always thought (until have a look into documentation) that the `percent` parameter determines value of possible deviation from chosen direction, some sort of precision for comparison of float values. But what it actually do is calculating all normals, finding difference between smallest and biggest angle to the input direction, finding angle between this two angles according input percent, filtering faces with normals less then that angle. 

In case if all faces have the same normals the node select all input faces independently of input direction or percent. Is it how it is intended to work?

https://github.com/nortikin/sverchok/blob/2162bc5a9a6c563d05d3bc83f8540b7064793834/nodes/analyzer/mesh_select.py#L144

https://github.com/nortikin/sverchok/blob/2162bc5a9a6c563d05d3bc83f8540b7064793834/nodes/analyzer/mesh_select.py#L108-L113

Interesting, how `max(values)` can be less than `min(values)`. Looks like this condition does not have sense.

**Comment by portnov** [comment]
> Is it how it is intended to work?

I think so. "Percent" setting means something like "select 1% best faces". If all faces are best, then select all...

On the other hand, it could make sense to have another mode of selection: not "percentage of best", but "percentage of deviation".

> how max(values) can be less than min(values)

I think the condition should be actually `maxv == minv`.

**Comment by Durman** [comment]
> I think the condition should be actually `maxv == minv`.

I don't see difference in the function output without the condition.

Yes, probably extra mode is required and more precise name for this one.

**Comment by Durman** [comment]
It seems the same thing can be done with math nodes.

![image](https://user-images.githubusercontent.com/28003269/181461811-754c907c-4c88-41a5-bf90-4b823cd7f65f.png)
