### ISSUE TITLE
How to turn inscribed circle data to regular point cloud?

### ISSUE THREAD

**Issue by gerroon** [nortikin/sverchok#3875]
Hi

I am using inscribed circle to create some shapes, it is all good but the vertices are wrapped in nested lists I think. I want to flatten the list , I am not able to do it using the list del levels. Maybe someone has an idea about how to do this?

![blender_z0kIfcFUc3](https://user-images.githubusercontent.com/8519469/106975822-d7ab3900-671c-11eb-85d3-f156f58f597d.jpg)

**Comment by Durman** [comment]
You can use `list levels` node which is simpler to use. Also there is `join mesh` node. It can combine all meshes into one.
