### ISSUE TITLE
some examples don't work.....

### ISSUE THREAD

**Issue by hwy1992129** [nortikin/sverchok#3876]
I am learning how to create a curve via sverchok.
I am running the example in Curves section, but some of them don't work. For example, **Arc Start / End / Tangent, Poly Arc, Polyline**.... I get the error, "sverchok.core.socket_data.SvNoDataError: No data passed into socket 'Vertices'". I believe I follow the documentation.....
I only found Viewer Draw. It seems there is no Viewer Draw Mk3...

Windows 10 system, Blender 2.91, Sverchok 0.6
I downloaded sverchok-master.zip from http://nortikin.github.io/sverchok/Download

**Comment by Durman** [comment]
If any of such errors occurs, first what can be done is to press `update tree` button in Sverchok panel. It will recalculate whole tree what will make to update nodes their output values. If it won't help upload the problematic file here.
