### ISSUE TITLE
set verts by distance from 3-4 fixpoints (indoor positioning / True-range multilateration)

### ISSUE THREAD

**Issue by m9tz** [nortikin/sverchok#3887]
I’am trying to measure a real object to get an 3d-blender-object for 3d-printing. 
 I’am thinking about mesuring 4 point exactly in 3d space an than measure 
 the distance to a 20-30 other point from the 4 reference points and than do some 
 Trilateration calculation to span up a mesh or better a curve between the points.

the object is a plexiglass-windows which needs a frame like this:
https://drive.google.com/file/d/1MQOTsBmfeaqhYQSOGnPwv5PVR6raUVVC/view?usp=sharing

the numpy part is working fine
the first 4 lines in the input file are the fixpoints
the next lines are 4 distances in each line to the fixpoints for every point

`

    def trilaterate3D(distances,n):
        p1=np.array(distances[0][:3])
        p2=np.array(distances[1][:3])
        p3=np.array(distances[2][:3])       
        p4=np.array(distances[3][:3])
      
      print("The resulting points [x, y, z] are: ")
        for i in range(4, n):
          r1=distances[i][0]
          r2=distances[i][1]
          r3=distances[i][2]
          r4=distances[i][3]
          e_x=(p2-p1)/np.linalg.norm(p2-p1)
          i=np.dot(e_x,(p3-p1))
          e_y=(p3-p1-(i*e_x))/(np.linalg.norm(p3-p1-(i*e_x)))
          e_z=np.cross(e_x,e_y)
          d=np.linalg.norm(p2-p1)
          j=np.dot(e_y,(p3-p1))
          x=((r1**2)-(r2**2)+(d**2))/(2*d)
          y=(((r1**2)-(r3**2)+(i**2)+(j**2))/(2*j))-((i/j)*(x))
          z1=np.sqrt(r1**2-x**2-y**2)
          z2=np.sqrt(r1**2-x**2-y**2)*(-1)
          ans1=p1+(x*e_x)+(y*e_y)+(z1*e_z)
          ans2=p1+(x*e_x)+(y*e_y)+(z2*e_z)
          dist1=np.linalg.norm(p4-ans1)
          dist2=np.linalg.norm(p4-ans2)
        
          if np.abs(r4-dist1)<np.abs(r4-dist2):
              print(ans1)
          else:           
              print(ans2)
    
`

numpy finds the intersection of the sphere-radians in relation to the fixpoints
 
![](https://i.stack.imgur.com/s35vv.png)

is it possible to do it with sverchok or how can I build a new modul. I have a working script here:
https://gitlab.com/m9tz/blender_lateration

it opens a data file and printout the xyz-cordinates for the points I measured.

Please think about it - I'am new to blender 
and my small old sailingboat neads a new windowsframe :-))

more about the math here: 
https://www.researchgate.net/publication/275027725_An_Algebraic_Solution_to_the_Multilateration_Problem

Thanks Michael

**Comment by vicdoval** [comment]
Hi Michael, it is a very interesting method. 
Once you have the working script to can place it inside a Scripted Node Lite and use it inside Sverchok.
Here i how i did it:
![image](https://user-images.githubusercontent.com/10011941/107333148-5b667c00-6ab5-11eb-8bb4-4c0a20dfafd8.png)
As you can see most of the nodes are used to prepare the data, this would be easier if:
Fixed points are in a different file.
Numbers are separated by commas and between brackets

This is the adapted script:
```
"""
in in_verts v
in in_distances s
out verts_out v
"""

def trilaterate3D(fixed_verts, distances,n):
    verts=[]
    p1=np.array(fixed_verts[0])
    p2=np.array(fixed_verts[1])
    p3=np.array(fixed_verts[2])       
    p4=np.array(fixed_verts[3])

    print("The resulting points [x, y, z] are: ")
    for i in range(0, n):
      r1=distances[i][0]
      r2=distances[i][1]
      r3=distances[i][2]
      r4=distances[i][3]
      e_x=(p2-p1)/np.linalg.norm(p2-p1)
      i=np.dot(e_x,(p3-p1))
      e_y=(p3-p1-(i*e_x))/(np.linalg.norm(p3-p1-(i*e_x)))
      e_z=np.cross(e_x,e_y)
      d=np.linalg.norm(p2-p1)
      j=np.dot(e_y,(p3-p1))
      x=((r1**2)-(r2**2)+(d**2))/(2*d)
      y=(((r1**2)-(r3**2)+(i**2)+(j**2))/(2*j))-((i/j)*(x))
      z1=np.sqrt(r1**2-x**2-y**2)
      z2=np.sqrt(r1**2-x**2-y**2)*(-1)
      ans1=p1+(x*e_x)+(y*e_y)+(z1*e_z)
      ans2=p1+(x*e_x)+(y*e_y)+(z2*e_z)
      dist1=np.linalg.norm(p4-ans1)
      dist2=np.linalg.norm(p4-ans2)
    
      if np.abs(r4-dist1)<np.abs(r4-dist2):
          verts.append(ans1.tolist())
      else:           
          verts.append(ans2.tolist())
    return verts

verts_out = [trilaterate3D(in_verts[0],in_distances[0], len(in_distances[0]))]
```

And this is the file:
[trilaterate3d.zip](https://github.com/nortikin/sverchok/files/5949795/trilaterate3d.zip)

I hope it helps :)

**Comment by m9tz** [comment]
thanks a lot I test it next days I think a have an idea. I ask neearly the same question in some blender forums this is the first qualified answer :-)

**Comment by vicdoval** [comment]
@m9tz you are welcome! If you manage to do your windowsframe I would love to see your outcome :)
