### ISSUE TITLE
"Polyline Viewer" is not displaying a "Bevel Object" with the correct dimensions

### ISSUE THREAD

**Issue by fd3dprinting** [nortikin/sverchok#3889]
## Problem statement

Hi

I am having issues with the "Polyline Viewer" when adding a "Bevel Object" in that the bevel object dimensions are not correct. They seem in fact to be a factor of approx. 3 too small. The attached file (see the link below to CleliaCurveFormula) shows the nodes I am using, both the top and bottom set of nodes are effectively the same and yet the output of the lower nodes is different and incorrect. Thanks for the add-on.

[**url blend file**](https://fluiddesigner.co.uk/CleliaCurveFormula-SverchokNodes.blend)

## Steps to reproduce
See the attached file.
1. 
2. 
3. 

## Expected result
See the attached file - the two objects should have the same dimensions but don't.
What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version
Version 0.6.0.0 
This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.
I used the "sverchok-master.zip" file on Blender 2.91.

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/107352272-b1024f00-6adc-11eb-80f3-1e67a23e1d42.png)
thenode doesnt add object

**Comment by Durman** [comment]
Probably this can be relevant #3766

**Comment by fd3dprinting** [comment]
I want to control the dimensions of my objects as all the work I do is for 3D printing. Thanks for quick replies.

**Comment by nortikin** [comment]
> I want to control the dimensions of my objects as all the work I do is for 3D printing. Thanks for quick replies.

you have this initial object with defined dimentions and this:

![image](https://user-images.githubusercontent.com/5783432/107399703-17559480-6b12-11eb-964d-3445b39b8b6f.png)

**Comment by fd3dprinting** [comment]
![CleliaCurveFormula-SverchokNodes(01)](https://user-images.githubusercontent.com/22477499/107493491-946e2180-6b85-11eb-8674-80a3be1cc67c.jpg)
I can see that is what your machine displays but that is not the case on my system - the Bevel Depth is 0.2 as is the Radius. The "Curve Viewer" node displays correctly but the "Polyline Viewer" node doesn't. Again, thanks for your response.

**Comment by fd3dprinting** [comment]
I have tried both adding the object in the Node and in the Properties panel and either way I get the same result.

**Comment by zeffii** [comment]
what happens if you use a test build of Blender 2.9.2 ? `builder.blender.org`

**Comment by fd3dprinting** [comment]
Hi - I still get exactly the same problem with Blender 2.92 which I have just downloaded and ran. The "Curve Viewer" node works OK but the "Polyline Viewer" doesn't read the bevel object either from the node or the properties panel. I can get the Nurbs Curves that I want from the Curve Viewer node and then using the menu to change the Spline Type but it just means messing about a little, the Polyline Viewer should do it directly.

**Comment by vicdoval** [comment]
@fd3dprinting could you update Sverchok and try again? (with a radius of 1 seems to have the right size in 2.91.2)

**Comment by fd3dprinting** [comment]
I have downloaded and installed on a completely different computer Blender 2.91.2 and Sverchok 0.6.0.0 and I still get the same issues. In addition on my systems with the default value of 0.2 for the "radius" the Z-Dimension of my curve object is not 0.2 but rather 0.0761, I can see this when I set it to a 2D curve rather than 3D!!! If in the Properties panel I change it from "Round" to "Profile" this same value, 0.0761, also stays the same. As I have said previously the "Curve Viewer" node works fine both with the default 0.2 and the bevel objects that I use. Because I work in 3D Printing mode in the Scene Properties I have the Unit Scale set to 0.001 and the Length Millimetres. Not sure if this could be an issue!! Thanks.

**Comment by nortikin** [comment]
>  is not 0.2 but rather 0.0761, I can see this when I set it to a 2D curve rather than 3D!!! 

Hi. 2D mode is for flat objects with Z=0

**Comment by fd3dprinting** [comment]
Sure 2D mode is for flat objects but when a bevel object is applied to a Bezier or Nurbs curve the Z dimension should be applied and its dimension in Z should match. Try and you will see that I am right. I use this feature with Bezier curves to get sharp edges for 3D printing whereas with Nurbs you only get very rounded objects.

**Comment by nortikin** [comment]
![image](https://user-images.githubusercontent.com/5783432/107961506-12339200-6fb7-11eb-8df1-2f1490d75a8e.png)
i have all working

[polyline_test.zip](https://github.com/nortikin/sverchok/files/5982285/polyline_test.zip)

**Comment by fd3dprinting** [comment]
Thanks. I just tested it on my machine and it does what I expect it to do just like the Curve View node. Excellent. Thanks again.
