### ISSUE TITLE
cannot add any nodes

### ISSUE THREAD

**Issue by hananbeer** [nortikin/sverchok#3890]
The addon has loaded quickly without errors. I have replaced blender's python with my installed python version 3.7.7 on Windows. I have tried both blender 2.87 and 2.91. I have all required python packages.

When I try to add any node I encounter countless errors.
`AttributeError:` 'Context' object has no attribute 'node'`

another node:
`KeyError: 'bpy_prop_collection[key]: key "" not found'`

and other functions that just don't seem to do anything.

the one I'm most interested in is SN script node:
```
Python: Traceback (most recent call last):
  File "...\sverchok-vstable4\nodes\generator\script1_lite.py", line 104, in execute
    txt = bpy.data.texts.load(self.filepath)
RuntimeError: Error: Cannot read '': Invalid argument
```

## Sverchok version

tried both sverchok-master from main page and stable-v4 from releases (from last week).

**Comment by vicdoval** [comment]
It does not seem to be a Sverchok issue... does the rest of blender work fine?

**Comment by hananbeer** [comment]
I didn't realize there's a dedicated Sverchok node editor :)

**Comment by nortikin** [comment]
> I didn't realize there's a dedicated Sverchok node editor :)

please, make screenshot of this situation, we will include it to wiki QA
