### ISSUE TITLE
How to move custom class objects between nodes

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#3891]
## Problem statement

To keep the question simple, assume two nodes:
1. The first node takes as input three floats: X, Y, and Z and creates a custom object (Vertex). Please note that this is not a Blender Vertex. It is from a different imported python module. Importing that module is done and works.
2. The second node takes as input one object (Vertex) and outputs three floats (X, Y, and Z)

Can you reply with the simplest python template for a custom node:
1. Vertex_ByCoordinates.py (inputs: X Y Z) (outputs: Vertex)
2. Vertex_Coordinates.py (inputs Vertex) (outputs: X Y Z)

Another node is to create and output an Edge from two vertices:
The method is Edge.ByVertices(v1, v2)
So how do I write a template for EdgeByVertices.py?

## Sverchok version
0.6.0.0
from sverchok-master.zip from github

**Comment by vicdoval** [comment]
We are moving custom classes all the time in sverchok.
Take a look to any of the solid nodes.  The solid is a custom class created at some node and used in other nodes
Created at [box (solid) node](https://github.com/nortikin/sverchok/blob/master/nodes/solid/box_solid.py)
Used at [offset solid node](https://github.com/nortikin/sverchok/blob/master/nodes/solid/offset_solid.py)
Turned to a regular python object at[ Solid to Mesh node](https://github.com/nortikin/sverchok/blob/master/nodes/solid/solid_to_mesh_mk2.py)

Happens the same with Curve, Surface, SVG and Pulga Physics nodes

**Comment by wassimj** [comment]
Thanks @vicdoval. Where is SvSolidSocket and SvSurfaceSocket defined? If I have my own Topologic Vertex or Topologic Edge, how do I specify the socket type for them? Thanks.

**Comment by vicdoval** [comment]
They are defined at https://github.com/nortikin/sverchok/blob/master/core/sockets.py

**Comment by nortikin** [comment]
> Thanks @vicdoval. Where is SvSolidSocket and SvSurfaceSocket defined? If I have my own Topologic Vertex or Topologic Edge, how do I specify the socket type for them? Thanks.

it is subject of discussion. Do we need new sockets. And how far you can go with this development?
