### ISSUE TITLE
No ParticleMk2 node?

### ISSUE THREAD

**Issue by foxxis** [nortikin/sverchok#3892]
## Problem statement

No particles node in sverchok under 2.8.x or 2.9.x. According to docs and the project files, it should be located in scenes->particlesmk2

## Steps to reproduce

1. Install latest sverchok
2. new nodetree
3. attempt to locate particlesmk2 node

## Expected result

A working particles node. :)

## Actual result

None found.

## Sverchok version

Most recent stable build. vstable4 2162bc5
Thanks in advance for any help!

**Comment by vicdoval** [comment]
look in the alpha category:
![image](https://user-images.githubusercontent.com/10011941/107569394-8d2c2f80-6be8-11eb-9f30-dd5cb906b30c.png)
in the search menu 
![image](https://user-images.githubusercontent.com/10011941/107569515-aa60fe00-6be8-11eb-91be-c60f6a509e35.png)

**Comment by foxxis** [comment]
It does appear in the search menu via key command (on OSX). 

However, the "Search" entry in the "Add" menu in Blender 2.91 for OSX does not function (works for other node editors, but not in Sverchok). 

Also, the Alpha nodes category is not present in the regular "Add" dropdown. So just reading the docs and looking for it, or attempting to use the search menu item will not work. You have to know the keyboard shortcut to trigger the "other" search in order to find it.

So not sure whether this would rank as a bug with the search menu item, or just a usability issue. Your call. :)

**Comment by Durman** [comment]
Solution for `add` menu

https://github.com/nortikin/sverchok/issues/3516#issuecomment-688743198

**Comment by foxxis** [comment]
Thanks! But not sure that's related? I'm in Sweden and run Blender in english...

**Comment by vicdoval** [comment]
Now should be fixed
