### ISSUE TITLE
Can you add a separator line and organise menus for custom nodes

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#3895]
## Problem statement

I have a fairly long list of methods that I am adding to sverchok. Is there a way to add separator lines and organise the menu without having to edit index.md?

## Expected result

An organised menu with separator lines

## Actual result

An unorganised menu with no separator lines

## Sverchok version

0.6.0.0
This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github

**Comment by vicdoval** [comment]
The regular add menu has just been replaced with the shift+A menu that we can control, the old one could not be controlled by Sverchok

**Comment by wassimj** [comment]
Thanks Victor. Can you please explain in a bit more detail (for a noob like me) how to add 'Topologic' to the Shift-A menu? I was following the sverchok-extras example and they add to the regular Add menu.

**Comment by vicdoval** [comment]
sverchok-extra also adds categories to the shift-A menu 
![image](https://user-images.githubusercontent.com/10011941/107612328-4e2cc700-6c46-11eb-99eb-a8274ef49a13.png)

**Comment by vicdoval** [comment]
Now I see that with the replacement of the Add menu #3894 they are added twice... @portnov 
![image](https://user-images.githubusercontent.com/10011941/107612548-c98e7880-6c46-11eb-8068-47d03370fec5.png)

**Comment by wassimj** [comment]
I am still lost. Sadly, I cannot add sverchok-extra because it is giving me an error
![Screenshot from 2021-02-11 07-55-23](https://user-images.githubusercontent.com/6302909/107612768-e4f58580-6c3e-11eb-8c91-36e3afcc36ff.png)

**Comment by wassimj** [comment]
This is the code I adapted from sverchok-extra. What do I need to do to fix it? Thank you!

```
def register():
    global our_menu_classes

    debug("Registering toplogicsverchok")

    #settings.register()
    #icons.register()

    register_nodes()
    extra_nodes = importlib.import_module(".nodes", "topologicsverchok")
    auto_gather_node_classes(extra_nodes)
    menu = make_menu()
    menu_category_provider = SvExCategoryProvider("TOPOLOGICSVERCHOK", menu)
    register_extra_category_provider(menu_category_provider) #if 'TOPOLOGICSVERCHOK' in nodeitems_utils._node_categories:
        #unregister_node_panels()
        #nodeitems_utils.unregister_node_categories("TOPOLOGICSVERCHOK")
    nodeitems_utils.register_node_categories("TOPOLOGICSVERCHOK", menu)
    our_menu_classes = make_extra_category_menus()
    #register_node_panels("TOPOLOGICSVERCHOK", menu)
    #show_welcome()
```

**Comment by vicdoval** [comment]
to avoid the doubled registration in the add menu I have just made a PR removing
`nodeitems_utils.register_node_categories("SVERCHOK_EXTRA", menu)`

**Comment by wassimj** [comment]
ok figured it out and it is now working as expected. What is now missing is that when I do a Search, other menu items have the parent category listed right-justified. What is the trick to get that?
![Screenshot from 2021-02-11 09-13-42](https://user-images.githubusercontent.com/6302909/107618444-7d910300-6c49-11eb-94b9-5b4240c70bae.png)

**Comment by vicdoval** [comment]
Uses the node docstring:

https://github.com/nortikin/sverchok/blob/4ff9c71fea9aeb0f395d72bc2763906a4ab17892/nodes/modifier_change/bevel.py#L52-L56
![image](https://user-images.githubusercontent.com/10011941/107623710-0ca61700-6c5a-11eb-837d-adba0172e247.png)
![image](https://user-images.githubusercontent.com/10011941/107623735-192a6f80-6c5a-11eb-866e-f297f7321e40.png)
