### ISSUE TITLE
Ошибка в "Switcher"

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#3896]
## Problem statement

I don't know if this is a bug in the "Switcher" node or if I did something wrong, in general, if there are more than two buttons, only the index of the first and last buttons is transmitted at the output.
![Снимок](https://user-images.githubusercontent.com/62519357/107632544-ae882c80-6c77-11eb-9a3c-31c79dfa9971.JPG)
![Снимок1](https://user-images.githubusercontent.com/62519357/107632547-afb95980-6c77-11eb-83a4-96a455d36e9a.JPG)
![Снимок2](https://user-images.githubusercontent.com/62519357/107632549-b051f000-6c77-11eb-8374-738f77578c0b.JPG)
![Снимок3](https://user-images.githubusercontent.com/62519357/107632553-b051f000-6c77-11eb-92b9-9ba2c207e7a9.JPG)
![Снимок4](https://user-images.githubusercontent.com/62519357/107632554-b0ea8680-6c77-11eb-99c1-719a36e80734.JPG)
Additional information: if you start the selection from the last button in the list, the indexes of the last button will be displayed for the buttons located between the last and the first.

## Steps to reproduce

1. If this is a bug then you need to fix it
## Expected result

Fix a bug

## Actual result

Fix a bug

## Sverchok version

Sverchok-master.zip + Updates via the Sverchok interface. Blender 2.91.2

**Comment by Durman** [comment]
Could you attach the file?

**Comment by maxim1967** [comment]
Incorrect data is transmitted for some reason, due to the fact that one of the switches is further down the node tree (it changes the number of vertices in the "Ellipse" node") was connected (connected) not to all nodes of the"Ellipse". I think this is wrong because the data is the primary source that determines further events, and it should not depend on whether I made a mistake further down the tree structure.
Link to the file with the error: https://disk.yandex.ru/d/EiRbSEHnNhkNoA
Link to the corrected file: https://disk.yandex.ru/d/SDK8vzxevYnaZg

Неправильные данные почему то передаются, из за того что дальше по дереву нод  один из переключателей (меняет количество вершин в ноде "Эллипса") был соединен (подключен) не ко всем нодам "Эллипса". Я считаю что это неправильно так как данные являются первоисточником определяющим дальнейшие события, и они не должны зависеть от того сделал ли я ошибку дальше по структуре дерева.
Ссылка на файл с ошибкой: https://disk.yandex.ru/d/EiRbSEHnNhkNoA
Ссылка на исправленный файл: https://disk.yandex.ru/d/SDK8vzxevYnaZg

**Comment by Durman** [comment]
I can't reproduce

https://user-images.githubusercontent.com/28003269/107729710-09b72f00-6d0b-11eb-91f1-04ad54f5c519.mp4

**Comment by maxim1967** [comment]
I don't understand what you mean? I gave two files one with an error the second already corrected for comparison. and explained when the error occurs.

Не понял что вы хотите сказать? Я дал два файла один с ошибкой второй уже исправленный для сравнения. и объяснил когда происходит ошибка.

**Comment by Durman** [comment]
Ok, I think I downloaded the right one now.

https://user-images.githubusercontent.com/28003269/107736091-a7662a80-6d1a-11eb-81b0-b3b19e095e2a.mp4

While investigating a problem try to use as less nodes as possible.

**Comment by maxim1967** [comment]
Cutting off what you think is superfluous, you have lost the essence of the problem, the problem is in the part that you cut off!!!

Отрезав как вам кажется лишнее, вы потеряли суть проблемы, проблема находится в той части которую вы отрезали!!!

**Comment by Durman** [comment]
You are right the problem is not in switcher node but something else. For more understanding I would suggest to open system console and try to figure it out what cause the problem.

**Comment by maxim1967** [comment]
Alas, I do not know programming, so the console will not give me anything, I will not understand anything. I raised the issue here as you will better understand what the problem is.

Увы я не владею программированием, поэтому мне консоль ничего не даст, я ничего не пойму. Я поднял вопрос здесь так как вы лучше поймете в чем проблема.

**Comment by Durman** [comment]
You really should not be a programmer to be able to read tracebacks. All that you have to do is to find error log message and read name of the node which cause the problem.

![2021-02-12_11-27-07](https://user-images.githubusercontent.com/28003269/107740815-66bfde80-6d25-11eb-916d-888559df136a.png)

In your case it is `Merge by distance` node. From what I saw in your layout you build your mesh incorrectly and the node is complaining that it can't to rebuild mesh from input data. Probably it would be better make it give more descriptive error on this account.

**Comment by maxim1967** [comment]
Yes, the error in" Merge by distance "occurs because I did not connect" Input Switch MOD. 002 "to three more"Ellipses". But why does "Switcher" react to this, it is also a data source! So it should not be because of this I do not see my error and I see that the "Switcher" transmits the wrong data?

Да ошибка в "Merge by distance" возникает потому что я не подключил "Input Switch MOD.002" еще к трем  "Эллипсам". Но почему на это реагирует "Switcher", он же является источником данных! Так не должно быть из за этого я не вижу своей ошибки а вижу что "Switcher" передает не те данные?

**Comment by Durman** [comment]
I'm troubling to understand your point. Probably there problem is in your understanding how update system works. During update event update system trying to update tree but if it is facing with error node it is stopping the update process on that node. So when you are changing properties of the `switcher` node `stethoscope` node is not been updated by update system and it's not showing actual output of `switcher` node because update system stoped on the error node.

**Comment by maxim1967** [comment]
According to your logic,, the switch should be updated since the error occurs after the switch node. And it is not updated why? Other nodes are updated, but he is not? 

По вашей логике, коммутатор должен обновляться так как ошибка возникает уже после узла коммутатора. А он не обновляется почему?  Другие узлы обновляются, а он нет?

**Comment by Durman** [comment]
Because of updating order. 
Node tree can be presented as a tree data structure (for simplicity). This data structure has root node and its branches. Branches are nodes which are chained to each other. Update system is walking over this tree and updating nodes. If in one of the branch there is node which produces an error update system is stopping and leaving other branches outdated. So in this case the `stethoscope` node is in next branches after the node where the error occurred.

**Comment by maxim1967** [comment]
I understand that everything is updated at once and if there is an error somewhere, then the update does not occur. OK. I will take this feature into account, if something is not updated, then there is an error somewhere, and I will look for it and fix it. I think the topic can be closed.

Я так понял что обновляется все сразу и если есть где то ошибка то обновления не происходит. Ок. Буду учитывать эту особенность, если что то не обновляется значит гдето есть ошибка, и буду ее искать и исправлять. Думаю тему можно закрыть.

**Comment by maxim1967** [comment]
Sorry but I have a question: how to open the system console for Windows. Sorry for the banal question.

**Comment by Durman** [comment]
There is dedicated button for that
![2021-02-12_14-26-07](https://user-images.githubusercontent.com/28003269/107756888-481a1180-6d3e-11eb-965a-989eee3af759.png)

**Comment by maxim1967** [comment]
Thank you again!!!
