### ISSUE TITLE
Latest Blender 2.93 beta from 13 February failed the SV addon loading

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3904]
SV addon not loading anymore 2.93 beta, 13 February 2021

```python
Python: Traceback (most recent call last):
  File "/Applications/BLENDER_293_alpha/Blender.app/Contents/Resources/2.93/scripts/startup/bl_operators/userpref.py", line 636, in execute
    import zipfile
  File "/Applications/BLENDER_293_alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/zipfile.py", line 6, in <module>
    import binascii
ImportError: dlopen(/Applications/BLENDER_293_alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Applications/BLENDER_293_alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Applications/BLENDER_293_alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary

location: <unknown location>:-1

```

**Comment by rendetto** [comment]
I just tested Blender 2.93.0 Alpha (February 14, 00:32:00- f362dad19bf4) (blender-2.93.0-f362dad19bf4-windows64).
There are no problems loading Sverchok (and SVExtra) but...
This build jumped to py3.9 so it's again misaligned to the current FreeCADs py3.8 :) ...aand there is no Blender build using py3.8 either.
So for those of us using FreeCAD libraries we need to stick to older Blender until FreeCAD starts using py3.9 too.

**Comment by enzyme69** [comment]
Ok, so maybe it's Blender's issue, my version is:
version: 2.93.0 Alpha, branch: master, commit date: 2021-02-12 22:08, hash: 1065b413edfa, type: Release
build date: 2021-02-13, 00:12:42
platform: Darwin

Let's wait for next version ...

**Comment by enzyme69** [comment]
From 16th February: addon still failed

version: 2.93.0 Alpha, branch: master, commit date: 2021-02-16 18:02, hash: c075b8bff220, type: Release
build date: 2021-02-16, 18:56:26

**Comment by REYNEP** [comment]
@enzyme69, Animation-Nodes does have Separate Python 3.9 Builds.... Just Download the Latest Animation Nodes
https://github.com/JacquesLucke/animation_nodes/releases/tag/master-cd-build
![image](https://user-images.githubusercontent.com/35212190/108546730-bbf68400-7313-11eb-9f8a-cd30cf7ee6b8.png)

For SverChok, I have 2.93, and Sverchok runs Okay, I have touched half of the nodes.

But Yes, AudioNodes Does not have Python 3.9 Support yet. which is what Blender 2.93 and Onwards uses

**Comment by machin3io** [comment]
Can confirm this is happening on Darwin (for an addon of mine, and I assume every other addon installation from zip files). It definitely is related to the python update to 3.9.1. Needs to be reported on the bug tracker.

**Comment by molotok89** [comment]
Cannot install from zip file on 2.93 alpha. MAC OS


> Traceback (most recent call last):
  File "/Applications/Blender 2.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 115, in init_architecture
    import_all_modules(imported_modules, mods_bases)
  File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 100, in import_all_modules
    import_modules(mods, base, imported_modules)
  File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 70, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/Applications/Blender 2.app/Contents/Resources/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 38, in <module>
    from sverchok.utils.handle_blender_data import get_func_and_args
ImportError: cannot import name 'get_func_and_args' from 'sverchok.utils.handle_blender_data' (/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/utils/handle_blender_data.py)

>

**Comment by rofoto** [comment]
> Cannot install from zip file on 2.93 alpha. MAC OS
> 
> > Traceback (most recent call last):
> > File "/Applications/Blender 2.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
> > mod = **import**(module_name)
> > File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/**init**.py", line 75, in 
> > imported_modules = init_architecture(**name**, utils_modules, ui_modules)
> > File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/**init**.py", line 115, in init_architecture
> > import_all_modules(imported_modules, mods_bases)
> > File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/**init**.py", line 100, in import_all_modules
> > import_modules(mods, base, imported_modules)
> > File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/**init**.py", line 70, in import_modules
> > im = importlib.import_module('.{}'.format(m), base)
> > File "/Applications/Blender 2.app/Contents/Resources/2.93/python/lib/python3.9/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 38, in 
> > from sverchok.utils.handle_blender_data import get_func_and_args
> > ImportError: cannot import name 'get_func_and_args' from 'sverchok.utils.handle_blender_data' (/Users/alexss/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/utils/handle_blender_data.py)
> 
> >

same issue on windows 10

**Comment by enzyme69** [comment]
As for now I think 2.92 is the one to use. 2.93 seems to be blocking any other node tree (AN, SV, etc). They also remove GLB export. Strange.

**Comment by enzyme69** [comment]
I just tested with latest 2.93. Uninstall any SV addon that it tries to bring from 2.92. Close Blender, open Blender, install SV once again and it should work!
