### ISSUE TITLE
Not displaying the default string field for a StringProperty Socket

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#3905]
## Problem statement

I am passing custom objects using SvStringsSocket with a StringProperty. When the input socket is NOT linked, I get a text field rectangle to the right of the input socket name. Is there a way to avoid that since my input socket is really not a string and typing something in there is not expected.

Just to note that I need to assign it a StringProperty to make sure it is updated (update=updateNode). Perhaps there is another way to make sure the node updates when the socket updates and I can remove prop_name?

Here is the start of the class code. Please suggest modifications. A code snippet would be much appreciated. Thank you

```
class SvTopologyEdges(bpy.types.Node, SverchCustomTreeNode):
	"""
	Triggers: Topologic
	Tooltip: Outputs the Edges of the input Topology    
	"""
	bl_idname = 'SvTopologyEdges'
	bl_label = 'Topology.Edges'
	Topology: StringProperty(name='Topology', default='', update=updateNode) 
	def sv_init(self, context):
		self.inputs.new('SvStringsSocket', 'Topology').prop_name='Topology'
		self.outputs.new('SvStringsSocket', 'Edges')
```
## Expected result

I expect the input socket to have only the name of the socket, but not the adjacent text field when not linked.

## Actual result

There is a text field to the right of the input socket name with the socket is not linked.

## Sverchok version

0.6.0.0 from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

![Screenshot from 2021-02-15 09-33-36](https://user-images.githubusercontent.com/6302909/107929012-f6a59880-6f70-11eb-9885-61478fce7630.png)
![Screenshot from 2021-02-15 09-34-23](https://user-images.githubusercontent.com/6302909/107929060-07560e80-6f71-11eb-87c9-3170fe59740a.png)

**Comment by Durman** [comment]
Update function of any property is only triggered if its value was changed. Update system of Sverchock itself keeps previous state of a tree and update nodes if it detects that those was connected. You can remove the property. The node will be updated whenever sockets will be connected / disconnected.
