### ISSUE TITLE
Matrix normal node - normal input vectorization

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3906]
## Problem statement

![2021-02-15_14-49-27](https://user-images.githubusercontent.com/28003269/107937237-194da680-6f9d-11eb-97d1-8501d637e7f2.png)

I would expect to see output of 10 matrixes

**Comment by rendetto** [comment]
I am sure that I've seen the same behavior for other nodes (unfortunately I don't remember which ones). 
My solution so far was to use the List Repeater ( in this case on the Locations value). 

![Matrix_Normal_Input_Vectorization](https://user-images.githubusercontent.com/66558924/107939513-81958b80-6f8f-11eb-8c43-3feb5c2310b2.jpg)

**Comment by Durman** [comment]
Yes. Also in this particular case `list split` can be used. But it's better to fix this node.
