### ISSUE TITLE
Mesh viewer - merging numpy vertices error

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3912]
## Problem statement

`Mesh viewer` get error with numpy vertices in merge mode.

https://github.com/nortikin/sverchok/pull/3909#issuecomment-780449134

**Comment by vicdoval** [comment]
Without #3909 Also failed to create the right mesh if the edges or polygons came in a numpy array

**Comment by Durman** [comment]
It's not supporting them because it does no have sense to do. See this issue #3612

**Comment by vicdoval** [comment]
I dont expect a full support but I think it is nice to automatically convert them to lists if they are detected in the inputs.
(Now that the list nodes support numpy using numpy for edges and polygons can be convenient in many cases)

**Comment by Durman** [comment]
Can you prove usefulness of using numpy arrays for edges and faces on some practical example of node tree?

**Comment by vicdoval** [comment]
This two trivial nodetrees:
![image](https://user-images.githubusercontent.com/10011941/108251843-3a0e2b80-7158-11eb-9bbf-a43d091518c8.png)
The top one, list of polygons and random num gen outputting lists
 ```
        1    0.000    0.000    0.140    0.140 update_system.py:361(do_update_general)
        1    0.000    0.000    0.111    0.111 box_mk2.py:369(process)
        4    0.098    0.024    0.098    0.024 {method 'tolist' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.097    0.097 box_mk2.py:50(numpy_check)
        1    0.000    0.000    0.097    0.097 box_mk2.py:51(<listcomp>)
        1    0.000    0.000    0.014    0.014 mask.py:123(process)
      2/1    0.000    0.000    0.014    0.014 mask.py:66(mask_data)
        1    0.000    0.000    0.014    0.014 mask.py:26(mask_list)
        1    0.014    0.014    0.014    0.014 mask.py:40(<listcomp>)
        1    0.000    0.000    0.011    0.011 stethoscope_v28.py:189(process)
        2    0.011    0.006    0.011    0.006 bgl_callback_nodeview.py:56(callback_disable)
        6    0.000    0.000    0.011    0.002 sockets.py:415(sv_set)
        6    0.011    0.002    0.011    0.002 socket_data.py:84(SvSetSocket)
        1    0.000    0.000    0.003    0.003 box_mk2.py:53(numpy_cube)
```
The bottom one, array of polygons and random num gen outputting numpy array
```

        1    0.000    0.000    0.010    0.010 update_system.py:361(do_update_general)
        1    0.000    0.000    0.004    0.004 box_mk2.py:369(process)
        1    0.000    0.000    0.003    0.003 box_mk2.py:53(numpy_cube)
        1    0.000    0.000    0.003    0.003 mask.py:123(process)
        1    0.002    0.002    0.003    0.003 box_mk2.py:192(make_edg_pol)
      2/1    0.000    0.000    0.003    0.003 mask.py:66(mask_data)
        1    0.003    0.003    0.003    0.003 mask.py:48(mask_array)
        1    0.000    0.000    0.002    0.002 random_num_gen.py:300(process)
        1    0.000    0.000    0.002    0.002 random_num_gen.py:314(<listcomp>)
        1    0.000    0.000    0.002    0.002 random_num_gen.py:289(produce_range)
        1    0.000    0.000    0.002    0.002 random_num_gen.py:218(int_random_range)
```

**Comment by Durman** [comment]
I have several objection to consider this proves seriously. 

The example does not look real. What I call real example is a node tree which produce complete result of something for what Sverchok is designed. It could be architectural object, some effect, animation or whatever. This four nodes could be part of those layouts but they does not make real example by themselves.
There is example from Python which explains why I'm insisting on this. It can be easily prove that using class variables is very inefficient and local variable should be used instead. The prove would be that writing access to class variable is nearly 10 times slower than to local one. But does it mean that class variables should be avoiding in general? I think certainly not. On the contrary class variable should be always used where it's appropriate and only in narrow bunch of cases it could be otherwise.

From profiling of first example I see that most time was spended in function which converts numpy arrays into lists. I assume that main node logic is using numpy arrays. If it's so it only proves that numpy implementation is faster than the same numpy implementation which finally convert everything into lists. It does not prove that Python implementation would be slower.

The numpy format of faces used in the `Box` node does not fit into Svercok requirements. Face in Sverchok data structure can have 3 and more vertices. All faces can have different number of vertices in a mesh. With that numpy format it's impossible to express such meshes. My guess is to get full benefit ot using numpy arrays we should make to support it as many nodes as possible. With such format it's hardly possible.

Decision of using format is quite important. It will effect many nodes increase developing time and complexity. If you are interested in collaboration and believe that this is what Sverchok really need take more time if it's needed to find more convinsing proves. As far as I know nobody consider this as worth efforts.

**Comment by vicdoval** [comment]
I totally agree with your concerns, the only advantage of having  such a format in some nodes is that they can benefit from faster masking, sorting, indexing... I know is a very narrow spectrum of cases, probably only for advanced users that will know how to handle it. 
I was trying to avoid a last Numpy node but I think I can live with that
