### ISSUE TITLE
English Manual link is not pointing to a full working page

### ISSUE THREAD

**Issue by just-jason** [nortikin/sverchok#3914]
## Problem statement

The English Manual link in the readme is pointing to an incomplete html page

## Steps to reproduce

From a Mozilla browser running under Ubuntu, click on the link to ["Manual-In English"](http://nortikin.github.io/sverchok/docs/main.html) in the readme. Other browsers have not been checked.

## Expected result

This Docs page works great. Maybee it should point [there](http://nikitron.cc.ua/sverch/html/main.html)?

## Actual result

[This](http://nortikin.github.io/sverchok/docs/main.html) seems kind of broken
![image](https://user-images.githubusercontent.com/45034489/108591631-04d92780-736a-11eb-84ab-79898ae972d0.png)

## Sverchok version

None yet, but will be the vstable4

**Comment by Durman** [comment]
The documentation is also available on Github - https://github.com/nortikin/sverchok/tree/master/docs

**Comment by just-jason** [comment]
> The documentation is also available on Github - https://github.com/nortikin/sverchok/tree/master/docs

Yeah, there are other places to find it, but the link in the readme is still wrong

**Comment by Durman** [comment]
@portnov Do you know what the file should do? - `sverchok/docs/main.rst`
I see that in the readme file it links to that page. Should github autogenerate html page from the rst file?

**Comment by Durman** [comment]
https://discord.com/channels/745273148018262158/806643543182802954/845578804335869954

https://pages.github.com/

**Comment by nortikin** [comment]
so i see 404 for css
maybe to change linkage or _ symbol not recognised
