### ISSUE TITLE
SDF Python as SV Nodes? - Marching Cubes SDF but easier = possible?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3917]
SV has Marching Cubes and Field nodes stuff:
<img width="727" alt="Screen Shot 2021-02-21 at 10 02 14 pm" src="https://user-images.githubusercontent.com/3952687/108622980-76ab9100-7490-11eb-8624-476913cf27ed.png">

But I found it pretty difficult to work with, when compared to this:
https://github.com/fogleman/sdf

Which is practically like doing Booleans. But can be scripted with Python.

How is it actually to use Marching Cubes and Field nodes in SVerchok that's as simple as the SDF Python implementation by Fogleman?

**Comment by enzyme69** [comment]
These two both are similar but I think the SDF thing can produce some kind of clean mesh.

<img width="1282" alt="Screen Shot 2021-02-21 at 10 30 52 pm" src="https://user-images.githubusercontent.com/3952687/108623732-9349c800-7494-11eb-93b2-c14279e89b95.png">

<img width="843" alt="Screen Shot 2021-02-21 at 10 31 04 pm" src="https://user-images.githubusercontent.com/3952687/108623725-8d53e700-7494-11eb-81bb-fe4dc47d076e.png">

**Comment by enzyme69** [comment]
@portnov Where to start, can you give guides and some examples on SDF. I wonder how it works, I mean Booleans is the simplest for modeling. But when dealing with SV SDF at the moment, it's more abstract like field.

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/118372121-2b48e080-b5b0-11eb-956c-6e305e76f252.png)

if you can get `sdf` installed in blenders python, then this script will work.   the `samples` in `generate` is where you generate accuracy.  higher will start to slow stuff down.   a     l   o      t.
```python
"""
in loc v
in radius s d=1 n=2
out verts v
out faces s
"""

import sdf

f = sdf.octahedron(radius) # sdf.sphere(radius, loc[0][0]) # translated sphere
f = sdf.translate(f, loc[0][0])

points = f.generate(samples=10000)
for plist in points:
    verts.append(plist.tolist())
verts = [verts]

face_np = np.arange(0, len(verts[0]), 1).reshape((-1, 3)).tolist()
faces.append(face_np)
```

**Comment by zeffii** [comment]
but as separate nodes? i doubt it..  the power of the sdf library is that it lends itself so well to being written in text.

**Comment by zeffii** [comment]
but it is a very nice library indeed @enzyme69 

```python
"""
in scale v
out verts v
out faces s
"""

from sdf import *

f = box(2) & slab(z0=-0.5, z1=0.5).k(0.1)
f.scale((1, 0.5, 1))
f -= cylinder(0.25).circular_array(6, 0.6).k(0.05)

points = f.generate(samples=10000)
for plist in points:
    verts.append(plist.tolist())
verts = [verts]

face_np = np.arange(0, len(verts[0]), 1).reshape((-1, 3)).tolist()
faces.append(face_np)
```

![image](https://user-images.githubusercontent.com/619340/118376038-d7e18d00-b5c5-11eb-952a-6e575a909a36.png)

**Comment by nortikin** [comment]
on my blender some troubles with hdf5 libs

**Comment by zeffii** [comment]
linux installation instructions may be different. painful : / @nortikin

**Comment by zeffii** [comment]
i added a small sdf_utils module,, now you can write
```python
        '''
        in scale v
        out verts v
        out faces s
        '''

        from sdf import *
        from sverchok.utils.modules.sdf_utils import geometry_from_points

        f = box(2) & slab(z0=-0.5, z1=0.5).k(0.1)
        f.scale((1, 0.5, 1))
        f -= cylinder(0.25).circular_array(6, 0.6).k(0.05)

        points = f.generate(samples=23200)

        geom = geometry_from_points(points, mode="np")
        verts.append(geom.verts)
        faces.append(geom.tris)
```

**Comment by nortikin** [comment]
it is installable only from github clonning. So, mechanics should be as described [here](https://github.com/fogleman/sdf#installation)

**Comment by nortikin** [comment]
it is cool!

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/118569568-e0cb8d80-b782-11eb-87dc-5833ceb29765.png)

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/118571177-1b82f500-b786-11eb-818b-7b4025bd7254.png)
```python
"""
in WIDTH s d=12 n=2
in HEIGHT s d=6 n=2
in DEPTH s d=2 n=2
in ROWS s d=3 n=2
in COLS s d=5 n=2
in WALL_THICKNESS s d=0.25 n=2
in WALL_RADIUS s d=0.5 n=2
in BOTTOM_RADIUS s d=0.25 n=2
in TOP_FILLET s d=0.125 n=2
in DIVIDER_THICKNESS s d=0.2 n=2
in ROW_DIVIDER_DEPTH s d=1.75 n=2
in COL_DIVIDER_DEPTH s d=1.5 n=2
in DIVIDER_FILLET s d=0.1 n=2
in LID_THICKNESS s d=0.25 n=2
in LID_DEPTH s d=0.75 n=2
in LID_RADIUS s d=0.125 n=2
in SAMPLES s d=48 n=2
out verts v
out faces s
out lidv v
out lidf s
"""


from sdf import *


def dividers():
    col_spacing = WIDTH / COLS
    row_spacing = HEIGHT / ROWS
    c = rounded_box((DIVIDER_THICKNESS, 1e9, COL_DIVIDER_DEPTH), DIVIDER_FILLET)
    c = c.translate(Z * COL_DIVIDER_DEPTH / 2)
    c = c.repeat((col_spacing, 0, 0))
    r = rounded_box((1e9, DIVIDER_THICKNESS, ROW_DIVIDER_DEPTH), DIVIDER_FILLET)
    r = r.translate(Z * ROW_DIVIDER_DEPTH / 2)
    r = r.repeat((0, row_spacing, 0))
    if COLS % 2 != 0:
        c = c.translate((col_spacing / 2, 0, 0))
    if ROWS % 2 != 0:
        r = r.translate((0, row_spacing / 2, 0))
    return c | r

def box():
    d = dividers()
    p = WALL_THICKNESS
    f = rounded_box((WIDTH - p, HEIGHT - p, 1e9), WALL_RADIUS)
    f &= slab(z0=p/2).k(BOTTOM_RADIUS)
    d &= f
    f = f.shell(WALL_THICKNESS)
    f &= slab(z1=DEPTH).k(TOP_FILLET)
    return f | d

def lid():
    p = WALL_THICKNESS
    f = rounded_box((WIDTH + p, HEIGHT + p, 1e9), WALL_RADIUS)
    f &= slab(z0=p/2).k(LID_RADIUS)
    f = f.shell(LID_THICKNESS)
    f &= slab(z1=LID_DEPTH).k(TOP_FILLET)
    return f


#lid().save('lid.stl', samples=SAMPLES)

points = box().generate(samples=300000)
for plist in points:
    verts.append(plist.tolist())
verts = [verts]

face_np = np.arange(0, len(verts[0]), 1).reshape((-1, 3)).tolist()
faces.append(face_np)

lid = lid().generate(samples=300000)
for plist in lid:
    lidv.append(plist.tolist())
lidv = [lidv]

lidf_np = np.arange(0, len(lidv[0]), 1).reshape((-1, 3)).tolist()
lidf.append(lidf_np)
```

**Comment by zeffii** [comment]
@nortikin I added a dedicated method to generate faces from points.

```python
 
       from sverchok.utils.modules.sdf_utils import geometry_from_points


        geom = geometry_from_points(points, mode="np")
        verts.append(geom.verts)
        faces.append(geom.tris)
```
