### ISSUE TITLE
Blender 2.93 Alpha af940c68cbed (Linux)  cannot activate Sverchok Addon

### ISSUE THREAD

**Issue by meikasahara** [nortikin/sverchok#3922]
The following error appears upon attempting to activate the latest Sverchok (from sverchok-master.zip from github,) on the latest Blender build:

`/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/settings.py:16: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
sv: import all modules
/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/settings.py:16: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python
Traceback (most recent call last):
  File "/home/vdb/locald/blender-2.93.0-af940c68cbed-linux64/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/__init__.py", line 75, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 115, in init_architecture
    import_all_modules(imported_modules, mods_bases)
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 100, in import_all_modules
    import_modules(mods, base, imported_modules)
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/core/__init__.py", line 70, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "/home/vdb/locald/blender-2.93.0-af940c68cbed-linux64/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 1463, in <module>
    register, unregister = bpy.utils.register_classes_factory(classes + list(socket_interface_classes()))
  File "/home/vdb/.config/blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 1447, in socket_interface_classes
    prop_func, prop_args = socket_cls.__annotations__['default_property']
TypeError: cannot unpack non-iterable bpy_prop_deferred object
`

Sverchok functioned normally at least up to the 4604350eefab build.

**Comment by zeffii** [comment]
can confirm also on win64 ( 37e6a1995ac7 ), it looks like this is no longer valid (or temporarily this is not an iterable that can be unpacked..)

https://github.com/nortikin/sverchok/blob/825283dc8194e9615907021613e8330cdb1f7d96/core/sockets.py#L1447

**Comment by zeffii** [comment]
it's a known issue.. https://developer.blender.org/T85872

**Comment by zeffii** [comment]
i suspect this will be fixed in the next 2.93 nightly builds. @meikasahara

**Comment by zeffii** [comment]
ooh.. it may not be fixed for us yet.. 
https://developer.blender.org/rBde67e3c0c02e9d08022cff58338099d287505f91

**Comment by zeffii** [comment]
looks like we have no unpacking now, but direct attribute lookup.
```diff
- prop_func, prop_args = socket_cls.__annotations__['default_property']
+ prop_func = socket_cls.__annotations__['default_property'].function
+ prop_args = socket_cls.__annotations__['default_property'].keywords
```
or
```diff
- prop_func, prop_args = socket_cls.__annotations__['default_property']
+ socket_default_prop = socket_cls.__annotations__['default_property']
+ prop_func = socket_default_prop.function
+ prop_args = socket_default_prop.keywords
```

**Comment by zeffii** [comment]
and in `handling_nodes.py`..
```diff
    -bpy.props.BoolProperty()[0]: bpy.props.BoolProperty,
    +bpy.props.BoolProperty().function: bpy.props.BoolProperty,
```
etc..

**Comment by zeffii** [comment]
and the list goes on :)

**Comment by zeffii** [comment]
the issue with this API change is again that users will need to make a step over to 2.93, because i don't think any of us really feel like maintaining parallel codebases.

**Comment by zeffii** [comment]
works..
![image](https://user-images.githubusercontent.com/619340/108827838-61388300-75c6-11eb-9c09-688084e43467.png)

**Comment by meikasahara** [comment]
So these changes would break backward compatibility of SV with older - stable versions of Blender, right?

**Comment by zeffii** [comment]
i suspect there are a few spots left that aren't executed until runtime (monad / groupnode..)

**Comment by zeffii** [comment]
i don't think these changes break "blends", but for now I suggest sticking to a stable 2.93 from before `feb 20 - 2021`.

**Comment by zeffii** [comment]
i should explain more exact:   the only issue here is that Sverchok uses an undocumented feature of the Blender API. which is removed/changed on feb21 2021, so the unchanged Sverchok app will work fine on any Blender 2.93 from before that date, but as soon as you want to use Blender in a more recent 2.93 then Sverchok must be adapted in a few files.

it's a pain in the ass, but it's also progress..

**Comment by zeffii** [comment]
we can write a function/util that will let Sverchok run in all versions of 2.93, the function would test behind the scenes which API to use.  Maybe something like this @portnov @Durman @vicdoval ?
```python
def get_func_and_args(prop):
    if hasattr(prop, "keywords"):
        return *prop
    else:
        return prop.function, prop.keywords

```

**Comment by zeffii** [comment]
changes.patch
```diff
diff --git a/core/sockets.py b/core/sockets.py
index e4eb6e33c..381975b56 100644
--- a/core/sockets.py
+++ b/core/sockets.py
@@ -1443,8 +1443,13 @@ def socket_interface_classes():
             'color': socket_cls.color,
             'draw_color': lambda self, context: self.color
         }
+
         if 'default_property' in socket_cls.__annotations__:
-            prop_func, prop_args = socket_cls.__annotations__['default_property']
+            
+            socket_default_prop = socket_cls.__annotations__['default_property']
+            prop_func = socket_default_prop.function
+            prop_args = socket_default_prop.keywords
+
             prop_args = {k: prop_args[k] for k in prop_args if k not in {'update', 'name'}}
             prop_args['name'] = "Default value"
             prop_args['update'] = lambda s, c: s.id_data.update_sockets()
diff --git a/nodes/list_mutators/vd_attr_node_mk2.py b/nodes/list_mutators/vd_attr_node_mk2.py
index 9f839c889..6ab39d8ec 100644
--- a/nodes/list_mutators/vd_attr_node_mk2.py
+++ b/nodes/list_mutators/vd_attr_node_mk2.py
@@ -81,7 +81,10 @@ class SvVDMK4Properties(bpy.types.PropertyGroup):
     # this populates a property-group using VDExperimental.__annotations__ as the source -
     __annotations__ = {}
     for key, v in maximum_spec_vd_dict.items():
-        prop_func, kw_args = SvViewerDrawMk4.__annotations__[key]
+
+        prop_func = SvViewerDrawMk4.__annotations__[key].function
+        kw_args = SvViewerDrawMk4.__annotations__[key].keywords
+
         copy_kw_args = copy.deepcopy(kw_args)
         copy_kw_args.pop('update', None)
         __annotations__[key] = prop_func(**copy_kw_args)
diff --git a/utils/handling_nodes.py b/utils/handling_nodes.py
index b2e84f95f..627f609ef 100644
--- a/utils/handling_nodes.py
+++ b/utils/handling_nodes.py
@@ -381,7 +381,9 @@ class NodeProps:
 
         for name, prop in self.properties.items():
 
-            bpy_prop, bpy_prop_arguments = prop.bpy_props
+            bpy_prop = prop.bpy_props.function
+            bpy_prop_arguments = prop.bpy_props.keywords
+
             bpy_prop_arguments['update'] = update_node
             rebuild_bpy_prop = blender_properties[bpy_prop](**bpy_prop_arguments)
 
@@ -391,16 +393,16 @@ class NodeProps:
 blender_properties = {
     # properties are functions which return tuples with themselves as first argument
     # it should help to rebuild properties with new arguments
-    bpy.props.BoolProperty()[0]: bpy.props.BoolProperty,
-    bpy.props.BoolVectorProperty()[0]: bpy.props.BoolVectorProperty,
-    bpy.props.CollectionProperty()[0]: bpy.props.CollectionProperty,
-    bpy.props.EnumProperty()[0]: bpy.props.EnumProperty,
-    bpy.props.FloatProperty()[0]: bpy.props.FloatProperty,
-    bpy.props.FloatVectorProperty()[0]: bpy.props.FloatVectorProperty,
-    bpy.props.IntProperty()[0]: bpy.props.IntProperty,
-    bpy.props.IntVectorProperty()[0]: bpy.props.IntVectorProperty,
-    bpy.props.PointerProperty()[0]: bpy.props.PointerProperty,
-    bpy.props.StringProperty()[0]: bpy.props.StringProperty
+    bpy.props.BoolProperty().function: bpy.props.BoolProperty,
+    bpy.props.BoolVectorProperty().function: bpy.props.BoolVectorProperty,
+    bpy.props.CollectionProperty().function: bpy.props.CollectionProperty,
+    bpy.props.EnumProperty().function: bpy.props.EnumProperty,
+    bpy.props.FloatProperty().function: bpy.props.FloatProperty,
+    bpy.props.FloatVectorProperty().function: bpy.props.FloatVectorProperty,
+    bpy.props.IntProperty().function: bpy.props.IntProperty,
+    bpy.props.IntVectorProperty().function: bpy.props.IntVectorProperty,
+    bpy.props.PointerProperty().function: bpy.props.PointerProperty,
+    bpy.props.StringProperty().function: bpy.props.StringProperty
 }
 
 
```

**Comment by zeffii** [comment]
anyway, this is not a massive problem..  but as said.. it is a pain :)

**Comment by portnov** [comment]
Maybe better to make a compatibility wrapper?
```
 prop_func, prop_args = unpack_property( socket_cls.__annotations__['default_property'] )

def unpack_property(p):
    if isinstance(p, tuple):
        return p
    else:
        return p.function, p.keywords
```
?

**Comment by zeffii** [comment]
check the PR @portnov

**Comment by meikasahara** [comment]
@zeffii Yes indeed! Thank you!
