### ISSUE TITLE
Undoing operations in 3D Viewport breaks ViewerDraw render

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3923]
Here’s a simple setup rendering with VD node.. when you annotate on viewport.. and undo, the VD node stops rendering. You have to force an update somehow (e.g. toggle show/hide on the VD node brings the rendering back, or Update All in the property panel).

As a matter of fact this may be due to the UNDO operation isself, not necessarily to what is being undo (e..g the annotation). If you add an object to the scene and then undo, it has the same behavior on the VD node viewport updates.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/2083719/108797524-5f84a600-7559-11eb-960e-eca09a620025.png">

https://user-images.githubusercontent.com/2083719/108797431-2b10ea00-7559-11eb-8948-61944b1383eb.mov

**Comment by DolphinDream** [comment]
To be honest.. i had so many issues with various nodes just not updating correctly with the latest SV updates (e.g. compared to the way SV used to work/update 1 year ago). Lately when the updates don’t work correctly I find myself tapping on nodes inputs and toggles just to get them to generate output and update their viewers or the stethoscopes. I noticed that sometimes if any node fails for some reason other nodes in the node tree somehow fail to update correctly even if the failing node is not connected to other nodes. I find myself having to have to fix the failing node just so the other nodes finish updating themselves correctly.

**Comment by zeffii** [comment]
I haven't had much time with Sverchok lately, if it feels "glitchy" then that definitely needs to be addressed. Unfortunately the `undo` blender operator has a few side effects, and we have to defend against it in `def sv_handler_undo_post(scene):`

if you're interested you might look at ` def sv_handler_undo_post(scene): ` and see if it gets called after an undo of GPencil. It might just mean that you need to add an extra call to all drawing nodes in all visible node trees at the end of that handler.

**Comment by DolphinDream** [comment]
@zeffii The “glichy” undo behavior seems to be caused by other undo operations (e.g. adding a mesh object) not necessarily due to grease pencils undos. With grease pencil is where I first observed it though.

**Comment by DolphinDream** [comment]
Hm.. i’m getting a strange message about a node being removed.. while no node was removed. (undoing adding an object in the viewport).
```
sv_handler_undo_post called
looks like a node was removed, cleaning
```

**Comment by Durman** [comment]
All links to Blender objects leads to wrong memory address after undo event. Using such objects can cause Blender crash easily. To prevent it cleaning all references is used in the code. Probably it's better to press `update tree` button after undoing to reavulate whole tree.

**Comment by zeffii** [comment]
I don't believe we have any way to find out what kind of "undo event" was triggered by the user. (or do we?!)  Maybe we can figure out the active context from within the undo handler. 
- if the undo event is triggered while a Sverchok node tree is active, then perform the current code
- if the undo is from a 3dview, then ignore it.

but i suspect this will also not be a complete solution.

**Comment by Durman** [comment]
Now should work properly #4164
