### ISSUE TITLE
Loop and monad seem to be capped at 5 iterations

### ISSUE THREAD

**Issue by RGBboy** [nortikin/sverchok#3927]
## Problem statement

I have used both the loop and monad to try and loop over a set of nodes but I am unable to increase the iterations beyond 5. 

<img width="193" alt="Screenshot 2021-02-24 at 22 58 44" src="https://user-images.githubusercontent.com/1566539/109077368-ed949400-76f3-11eb-9a39-951c47e195e6.png">

<img width="204" alt="Screenshot 2021-02-24 at 22 58 52" src="https://user-images.githubusercontent.com/1566539/109077372-eec5c100-76f3-11eb-82e2-349660202561.png">

## Steps to reproduce

1. Create a loop in and out node
2. Try to increase iterations beyond 5

## Expected result

Able to increase iterations beyond 5

## Actual result

Unable to increase above 5

## Sverchok version

Currently running 0.6.0.0 - I updated via the blender interface today.

## Other info

I am running Blender 2.91.2 on a Mac M1.

**Comment by RGBboy** [comment]
I think I found out what my problem was for anyone that experiences the same issue. If you select the loop in node there is a property in the item panel that can be used to adjust max iterations:

<img width="395" alt="Screenshot 2021-02-25 at 02 02 44" src="https://user-images.githubusercontent.com/1566539/109092010-bb902b80-770d-11eb-85bb-3007ab4cc2bb.png">

I couldn't find this in the docs (but I might have missed where to look).

**Comment by Durman** [comment]
Press this button with a selected node and you will be able to get documentation nearly about every node in Sverchok.

Hidden features on N panel is quite often problem. Probably it's not Sverchok problem but Blender UI design.

![2021-02-25_08-23-54](https://user-images.githubusercontent.com/28003269/109102860-2d369c80-7743-11eb-880b-0c95d5d88af9.png)

**Comment by zeffii** [comment]
A quick clarification to @RGBboy  about the max iterations.  

`iteration count` and `max iteration` are decoupled because it is too easy to be in a situation where something like 7 iterations will take a very long time to complete processing, if ever. Depending on the input complexity. A sane way to know the effect of N iterations is by gradually increasing that amount from 3..to 5 and beyond. Each increment of the number of iterations will result in a large number of extra calculations.

**Comment by Durman** [comment]
By the way node groups implementation has possibility of interrupting of tree evaluation by pressing Escape button. If this technique would be used here there was no need in the option.
