### ISSUE TITLE
Extrude Separate Face mask seems to be broken

### ISSUE THREAD

**Issue by CG-ECN** [nortikin/sverchok#3931]
## Problem statement
Using a mask on the Extrude Separate Face doesn't work and produce unexpected results. It either extrude all faces or none, whereas the mask work as expected with similar nodes (such as inset or extrude region). I tested this behavior on a very basic configuration (see actual result) to ensure the result is dependant on the node and not another thing.

## Steps to reproduce
Input any mask to an Extrude Separate Face node.

## Expected result
Face with index corresponding to "true" in mask should be extruded, and the one corresponding to "false" remain untouched.

## Actual result
Either all faces are extruded or none. Comparison to a similar node below with the exact same parameters (fuschia : extrude region / blue : extrude separate face)

![ESF-bug](https://user-images.githubusercontent.com/58032020/109158347-8c140a00-7773-11eb-8ef9-ce04d9c126cf.gif)

## Sverchok version
0.6.0 - Recently update from inside Blender, originally installed from github .zip

**Comment by Durman** [comment]
@vicdoval Would you like to fix this? #3790

**Comment by vicdoval** [comment]
Now should be fixed 
@CG-ECN Thanks for reporting!
