### ISSUE TITLE
Map Range not accept List input.

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#3932]
## Problem statement
![image_2021-02-27_010615](https://user-images.githubusercontent.com/32074126/109337825-fe7e0a80-7897-11eb-86d4-75ad9fd4ac54.png)
blender 2.93 Alpha + Sverchok (a3562ba)

Thank you.

**Comment by Durman** [comment]
@vicdoval Would you like to fix this? #3900

**Comment by Durman** [comment]
Last bugs shows that we have to implement more unit tests for nodes. At least they could help to avoid them.

**Comment by vicdoval** [comment]
Should be fixed now
@rwny Thanks for reporting!
@Durman I agree, maybe more examples would catch more exceptions (as they are also tested)

**Comment by summereasy** [comment]
**Report Check:**
The "list limits" checkbox seems to "somewhat" broke after this change.
![iShot2021-02-28 14 12 05](https://user-images.githubusercontent.com/51897649/109409595-0db3a400-79cf-11eb-8358-b2ca829621bb.jpg)

**Comment by vicdoval** [comment]
@summereasy now should work in both cases

**Comment by summereasy** [comment]
@vicdoval It workes great, thanks!

**Comment by Durman** [comment]
> @Durman I agree, maybe more examples would catch more exceptions (as they are also tested)

By the way they are not tested. Only their importability is tested.

https://github.com/nortikin/sverchok/blob/b6c0e36b21b1b4fe5a84ef0f9c22161b3556ad14/tests/json_import_tests.py#L87
