### ISSUE TITLE
How to use existing node to process input in SN script node

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#3939]
Can script nodes import existing nodes as modules? In this way, the existing nodes can be used in the script to control the input grid

**Comment by vicdoval** [comment]
There is not a straight forward method but any sverchok con be imported into a SNL script. You would need to read the nodes code to see if the functionality you are looking for is a separated function or depends on the nodes inputs and outputs or any other node property.
In many cases if the functionality is a separated function, this function is in another module...

To use the rendomize node you could code:
`from sverchok.nodes.transform.randomize import randomize `

But to use polygons to edges:
`from sverchok.utils.sv_mesh_utils import polygons_to_edges_np`

**Comment by zeffii** [comment]
> Can script nodes import existing nodes as modules?

technically yes, you can import the file that contains a node as a module, but in order to use it (as @vicdoval mentions) you need to be familiar with code of that node. We don't have a requirement for nodes to be written in a way that exposes the core functionality as a separate function for re-use elsewhere. Some nodes are however written in a modular way that lends itself very well to code re-use, while other nodes are necessarily more complicated.

Many nodes with useful generic features end up offloading the working code into a `sverchok.utils.****` utility file.

another example, the inset_specials node does stick the working code / algorithm in its own separate function, but in order to be able to use it you must read the `process` function to see an established way of calling the `inset_special` function.  
```python
from sverchok.nodes.CAD import inset_special as inset_node
# inset_node
# <module 'sverchok.nodes.CAD.inset_special' from 'C:\\Users\\zeffi\\Desktop\\scripts\\addons_contrib\\sverchok\\nodes\\CAD\\inset_special.py'>

inset_node.inset_special
#  inset_special(vertices, faces, inset_rates, distances, ignores, make_inners, zero_mode="SKIP"):
```

**Comment by Durman** [comment]
I think neither node exposes its functionality via Python API. They always has some part of logic implemented in `process` method. It's prevent them using in this way.

```Python
result = some_node(*parameters)
```

It means that logic code is bounded to UI code. It has its downsides. One of them impossible to use via node code via Python. Also what comes into my mind is that it impossible to port Sverchok to another environment without rewriting code of all nodes, also it makes more difficult to create tests for nodes.

**Comment by zeffii** [comment]
> One of them impossible to use via node code via Python.

it's not impossible, but success will be determined by two things:
- the existing familiarity with Python 
- or willingness to be persistent until goal is achieved

@vktcl  if there any particular nodes you'd like to "wrap" for use in an SNLite script, make a small list and i'll see if I can show you a  few examples, the rest you will figure out.

**Comment by vktcl** [comment]
> > 其中之一无法通过Python通过节点代码使用。
> 
> 这并非不可能，但成功将由两件事决定：
> 
> * 对蟒蛇的熟悉程度
> * 或愿意坚持，直到目标实现
> 
> @vktcl，如果有任何特定的节点，你想"包装"用于SNLite脚本，做一个小列表，我会看看我是否可以告诉你一些例子，其余的你会弄清楚。

The origin of this idea: I want to import cut_object_by_surface node into script node to do some loop cutting.

Later I noticed that loop nodes can do that.

cut_object_by_surface Node seems to report errors easily

Unsupported: more than two edges of the face intersect the surface

**Comment by vktcl** [comment]
> > > 熊熊
> > 
> > 
> > 这并非不可能，但成功将由两件事决定：
> > 
> > * 对蟒蛇的熟悉程度
> > * 或愿意坚持，直到目标实现
> > 
> > @vktcl，@vktcl， 功能立于一身， "10 月" 的斯恩莱特 · 斯普利特 · 斯普利特 · 斯普利克斯， @vktcl 的文集， @vktcl 的音高，
> 
> 这个想法的起源：我想导入cut_object_by_surface节点到脚本节点做一些循环切割。
> 
> 后来我注意到循环节点可以做到这一点。
> 
> cut_object_by_surface节点似乎很容易报告错误
> 
> 不受支持：脸的两个以上边缘与表面相交

bpy.ops.mesh.intersect

> > > 其中之一无法通过Python通过节点代码使用。
> > 
> > 
> > 这并非不可能，但成功将由两件事决定：
> > 
> > * 对蟒蛇的熟悉程度
> > * 或愿意坚持，直到目标实现
> > 
> > @vktcl，如果有任何特定的节点，你想"包装"用于SNLite脚本，做一个小列表，我会看看我是否可以告诉你一些例子，其余的你会弄清楚。
> 
> The origin of this idea: I want to import cut_object_by_surface node into script node to do some loop cutting.
> 
> Later I noticed that loop nodes can do that.
> 
> cut_object_by_surface Node seems to report errors easily
> 
> Unsupported: more than two edges of the face intersect the surface

In blender bpy.ops.mesh . intersects works well. It's very difficult to operate this command with OPS. Is it possible to implement this kind of cutting in sverchok

**Comment by zeffii** [comment]
i asked Blender devs several years ago for a python binding to allow `bmesh.ops` to use the boolean code. And again in this [thread](https://blenderartists.org/t/new-boolean/1245336/43) - but it's just not a priority. But you'll see a few examples of "workaround" code in that thread, which i consider an abomination (but if it works.. it works...i'll not knock it)

if you really have to use Sverchok for booleans, you might want to reconsider the engine you use for booleans and think about using Geometry Nodes in combination with Sverchok.  Sverchok  would output the base objects, and Geometry nodes would be used to drive the output of the boolean. I don't think SNLite is a suitable approach for this particular problem until bmesh.ops includes boolean operators.

**Comment by zeffii** [comment]
@vktcl  wouldn't "Bisect" or "CrossSection" node not do that?

**Comment by vktcl** [comment]
> @vktcl wouldn't "Bisect" or "CrossSection" node not do that?
The cutting line of "bisect" or "crosssection" node is a plane. I need it to be irregular. In fact, I am trying to deal with the problem of object fragmentation with sverchok. In Houdini, there are Voronoi and Boolean cutting fragmentation, and Voronoi fragmentation is feasible in sverchok

**Comment by vktcl** [comment]
The cutting line of "bisect" or "crosssection" node is a plane. I need it to be irregular. In fact, I am trying to deal with the problem of object fragmentation with sverchok. In Houdini, there are Voronoi and Boolean cutting fragmentation, and Voronoi fragmentation is feasible in sverchok
