### ISSUE TITLE
Grouping sockets using custom_draw

### ISSUE THREAD

**Issue by cvillagrasa** [nortikin/sverchok#3943]
Hi, I am new to Sverchok and have been learning about it lately. I am trying to build a dummy custom node, for now only as an exercise. It has some inputs, no outputs, and calls an external script, storing Python variables in a class attribute in a similar fashion as I have seen in the Multi Cache node. Up to now it works like a charm. But now I'm getting picky and would like some UI grouping. Namely, to have some text titles which separate input sockets by group.

I was trying to achieve that by keeping the socket definition inside `sv_init`, but passing some `custom_draw` functions. Up to now, with not much luck. See code and result below (note that for now it is just a dummy node with six float inputs):

```Python
import sys
import bpy
from bpy.props import StringProperty, IntProperty, FloatProperty, EnumProperty, BoolProperty
from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode
from pathlib import Path
from shutil import copy, rmtree


def add_dir_to_path(dir_path):
    if str(dir_path) not in sys.path:
        sys.path.append(str(dir_path))


class SvDummy(bpy.types.Node, SverchCustomTreeNode):
    bl_idname = 'SvDummy'
    bl_label = 'Just a test'
    node_list = {}

    a: FloatProperty(name='a', description='a', default=1., min=0., update=updateNode)
    b: FloatProperty(name='b', description='b', default=1., min=0., update=updateNode)
    c: FloatProperty(name='c', description='c', default=1., min=0., update=updateNode)

    one: FloatProperty(name='one', description='one', default=1., min=0., update=updateNode)
    two: FloatProperty(name='two', description='two', default=1., min=0., update=updateNode)
    three: FloatProperty(name='three', description='three', default=1., min=0., update=updateNode)

    def sv_init(self, context):
        socketname = self.inputs.new('SvStringsSocket', 'a')
        socketname.prop_name = 'a'
        socketname.custom_draw = 'custom_draw_letters'
        self.inputs.new('SvStringsSocket', 'b').prop_name = 'b'
        self.inputs.new('SvStringsSocket', 'c').prop_name = 'c'

        socketname = self.inputs.new('SvStringsSocket', 'one')
        socketname.prop_name = 'one'
        socketname.custom_draw = 'custom_draw_numbers'
        self.inputs.new('SvStringsSocket', 'two').prop_name = 'two'
        self.inputs.new('SvStringsSocket', 'three').prop_name = 'three'

        self.to_class_attribute()
        self.mode_change(context)

    def custom_draw(self, obj, context, layout, title, prop):
        layout.split()
        row = layout.row()
        row.label(text=title)
        row = layout.row()
        row.prop(self, prop)

    def custom_draw_letters(self, obj, context, layout):
        return self.custom_draw(obj, context, layout, 'Letters:', 'a')

    def custom_draw_numbers(self, obj, context, layout):
        return self.custom_draw(obj, context, layout, 'Numbers:', 'one')

    def to_class_attribute(self):
        self.node_list[self.node_id] = {}

    def get_socket_values(self):
        def get_socket_value(input_name):
            return self.inputs[input_name].sv_get()[0][0]

        letters = {letter: get_socket_value(letter) for letter in ['a', 'b', 'c']}
        numbers = {number: get_socket_value(number) for number in ['one', 'two', 'three']}

        return letters, numbers

    def process(self):
        if 'data' in self.node_list[self.node_id]:
            if self.node_list[self.node_id]['data'] is not None:
                # self.node_list[self.node_id]['data'].delete()
                self.node_list[self.node_id]['data'] = None

        # add_dir_to_path(some_path)
        # from some_module import DoSomething

        letters, numbers = self.get_socket_values()
        # self.node_list[self.node_id]['data'] = DoSomething(letters, numbers)


def register():
    bpy.utils.register_class(SvDummy)


def unregister():
    bpy.utils.unregister_class(SvDummy)
```

![imagen](https://user-images.githubusercontent.com/57069798/109548499-007cdf00-7acd-11eb-9448-f87b8dddc5f4.png)

I have two questions:
1) How can I achieve to place titles in its own row?
2) Why do I need to pass an obj argument to `custom_draw`? Is it expected to have the last `self` in https://github.com/nortikin/sverchok/blob/master/core/sockets.py#L483-L484 ?

**Comment by Durman** [comment]
`custom_draw` attribute expects to get name of a method which will draw UI of the socket. Second argument is socket instance. It can be used for getting information about it's name and other its attributes. It can be done this way.

```Python
    def draw_my_socket(self, socket, context, layout):
        # This part can be copypasted
        row = layout.row()
        text = f'. {socket.objects_number}' if socket.objects_number else ""
        row.label(text=f'{socket.label or socket.name}{text}')

        # Next should be your property
        row.prop(self, 'mask_mode', expand=True, icon_only=True)
```

I don't see how this can help you to group sockets. Probably it's not clear that sockets have their own layout where they can draw their properties. It impossible to draw there anything from node layout.

The only you can do is to past another empty sockets which will separate socket groups from each other. You can have a look at `Input switch MOD` node to see how this looks like.

**Comment by cvillagrasa** [comment]
Thanks for the guidance. Indeed, I have seen that the `Input Switch MOD` node uses a `SvSeparatorSocket`, and I have also seen a `SvDummySocket` which helps to make those empty sockets for the titles. In addition, I now use the socket argument of `custom_draw` instead of defining ad-hoc functions.

```
    def sv_init(self, context):
        self.inputs.new('SvDummySocket', 'Letters:').custom_draw = 'custom_draw'
        self.inputs.new('SvStringsSocket', 'a').prop_name = 'a'
        self.inputs.new('SvStringsSocket', 'b').prop_name = 'b'
        self.inputs.new('SvStringsSocket', 'c').prop_name = 'c'

        self.inputs.new('SvSeparatorSocket', 'sep_letters_numbers')

        self.inputs.new('SvDummySocket', 'Numbers:').custom_draw = 'custom_draw'
        self.inputs.new('SvStringsSocket', 'one').prop_name = 'one'
        self.inputs.new('SvStringsSocket', 'two').prop_name = 'two'
        self.inputs.new('SvStringsSocket', 'three').prop_name = 'three'

        self.to_class_attribute()

    def custom_draw(self, socket, context, layout):
        row = layout.row()
        row.label(text=f'{socket.name}')
```
![imagen](https://user-images.githubusercontent.com/57069798/109645431-1c2cc780-7b57-11eb-9461-f4c40bfd83c4.png)

Closing!

**Comment by Durman** [comment]
It's also possible to use socket properties.

```Python
s = self.inputs.new('SvStringsSocket', 'a')
s.use_prop = True
s.default_float_property = 1.0
```

**Comment by cvillagrasa** [comment]
Noted! btw, what's the purpose of `use_prop`? Does it actually do something if `prop_name` is established?

**Comment by Durman** [comment]
`prop_name` should be used when it's not suitable to use `use_prop`. I think it would be better if Sverchok sockets would not have `use_prop` attribute at all.

**Comment by cvillagrasa** [comment]
Ok! Then what should I use a newcomer? `use_prop` or `prop_name`? I used **prop_name** after _§[Basic Stuff].3_ from [https://github.com/nortikin/sverchok/issues/2301](url).

**Comment by Durman** [comment]
Use `use_prop` if a socket has property of type which you need otherwise use `prop_name` or `custom_draw`

**Comment by cvillagrasa** [comment]
Ok, now I understand the reason for this advice:

![imagen](https://user-images.githubusercontent.com/57069798/109742007-86348380-7bce-11eb-8ef6-ec431931a2cf.png)


When using `use_prop`, `inputs` within `process` need to be retrieved by index. At least that's my understanding up to now. It's true that the required SLOC get dramatically reduced with respect to `prop_name` with Blender properties as annotations, which seems preferable.

Thanks for the help!

**Comment by Durman** [comment]
What the documentation means I think is that during importing JSON files the order of sockets is important. When you just open Blender file with old nodes new sockets do not even be shown. To show new sockets you have to create a node again. 

In `process` method I would recommend to get sockets by their names because in most cases it's some sort of identifier in sverchok (but sometimes sockets can has similar names). In case of using socket names it's possible to keep process method unchanged during changing order or inserting new sockets.

The reason why I think `use_prop` is more preferable is that this is more consistent, that the property which a socket shows should realy belongs to the socket. The reason of having `prop_name` API is caused by Blender limitations. It's impossible to set any property of Blender properties differently per instance. It means that all instances of a property share such values as description, minimum and maximum range and others which we sometimes would like to set differently for different nodes and sometimes differently in one node like in `A number` node.

**Comment by cvillagrasa** [comment]
Fair enough. May I ask if there is any reason why `SvStringsSocket` does not have a `default_bool_property`? Is it possible to use `use_prop` with booleans?

**Comment by Durman** [comment]
AS far as I know there is no single node which would have socket with a boolean property. Usually such properties get into node UI. If you need that property using `prop_name` or `custom draw` attribute will be good solution.
