### ISSUE TITLE
Changing Sverchok node search hot key yields empty search bar that does not work

### ISSUE THREAD

**Issue by rofoto** [nortikin/sverchok#3944]
## Problem statement

changing sverchok search shortcut to tab does not work. Search appears but nodes are not able to be searched

Please describe your problem here.

## Steps to reproduce

1.  use shift-a menu 
2.  right click and attempt to change search shortcut to tab 

## Expected result

What did you expect to see as a result of those steps?

hitting tab should pop up the search menu and I should be able to search nodes by typing, same as all other node windows in blender. 

## Actual result

search bar appears but no nodes pop up in the search while typing out abbreviated or full node names. 

What did you actually get?

## Sverchok version

0.6.0.0   installed from master.zip and updated from within blender 2.92

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by Durman** [comment]
I can't reproduce for me it works. Nice idea by the way.

It's a pity that it impossible for some reason to set shortcuts to categories in that menu, probably it would help to solve some problems in its organiztion.

**Comment by zeffii** [comment]
you may want to directly set the TAB for this shortcut manually (not using the quick shortcut menu). 
![image](https://user-images.githubusercontent.com/619340/109628133-b0406400-7b42-11eb-9934-367f51f9a821.png)

**Comment by zeffii** [comment]
but maybe, the sverchok initializiation code overwrites previous manual shortcut changes.

**Comment by rofoto** [comment]
I have tried both way of changing the shortcut, both don't work for me. it seems like it is defaulting to the viewport search menu and since the context is the node editor something is breaking, 

Just a guess

**Comment by zeffii** [comment]
Sverchok does also set TAB .. 

https://github.com/nortikin/sverchok/blob/04d9a554325254df2715df70ba1782b0581f0efe/ui/nodeview_keymaps.py#L184-L186

so for now if you can live with Tilde, do.

i'm not sure we want to provide a way to customize all our shortcuts, but I get how this might be annoying to face a restriction.

**Comment by Durman** [comment]
Looks like one shortcuts just override others. I think first shortcut is used from the list in Blender keymap settings. If all similar shortcuts above are switched off extra search starts to work. Interesting that adding shortcuts via context menu can add shortcut both on top of the list and bottom. This is why I did not reproduce this at first time.

![2021-03-04_08-28-01](https://user-images.githubusercontent.com/28003269/109912033-bcecc580-7cc4-11eb-8fe3-c4db18de167f.png)
