### ISSUE TITLE
Pulga physics alternative to place objects of various shape and size randomly on a surface

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#3945]
I'm trying to place objects of various shape and size randomly on a surface,
I managed more or less doing it by using Pulga Physics node but objects are superposing sometimes and it should not.
This one is ok :
<img width="484" alt="Capture d’écran 2021-03-02 à 09 34 22" src="https://user-images.githubusercontent.com/17178730/109624505-93a22d00-7b3e-11eb-8e60-c274a01fa1ca.png">
This one is not : 
<img width="536" alt="Capture d’écran 2021-03-02 à 09 35 23" src="https://user-images.githubusercontent.com/17178730/109624549-a3ba0c80-7b3e-11eb-96af-20625417842a.png">
Also objects are sometimes too close to the border of the surface like here
<img width="381" alt="Capture d’écran 2021-03-02 à 09 32 14" src="https://user-images.githubusercontent.com/17178730/109624586-ae74a180-7b3e-11eb-8065-6eb47414b7c6.png">

- Is there a way to improve my Pulga Physics implementation or is there any more effective alternative in Sverchok ?
- I might otherwise need to use geometry nodes ?

Here is my tree 
![Capture d’écran 2021-03-02 à 09 58 08](https://user-images.githubusercontent.com/17178730/109625090-32c72480-7b3f-11eb-98d7-49cd0aa69206.png)

**Comment by Durman** [comment]
I would use `random points on mesh` node to generate points on the plane and then use `Obj instanser` node to generate your objects on this points. The same can be done with Geometry nodes. 

To satisfy your conditions some tricks are required.  For example I guess it's possible to filter those points which are too close to border of the polygon.

**Comment by vicdoval** [comment]
You are passing a One list of vertices and Ten lists of radius (that makes 10 simulation and in each all the points have the same radius), maybe joining the radius lists into one list  (with a list join node) fixes your problem

**Comment by mlevet** [comment]
Thanks a lot for your insights
Let me try that
(meanwhile my project broke after blender update, I will open another issue
for that)

**Comment by mlevet** [comment]
@vicdoval I have indeed better results now using a list join on my radius, still some errors tho, but i dont know if it can be perfect using Pulga

**Comment by mlevet** [comment]
@Durman Using random points on mesh only, i guess there's no way to place objects of different size, without collision between them, am I right ?
What is the right node to check if an object is out of a polygon ?

**Comment by Durman** [comment]
> @Durman Using random points on mesh only, i guess there's no way to place objects of different size, without collision between them, am I right ?

Unless you will detect points located too close to each other to filter them.

There is `Points inside mesh` node it can help. But in your case I don't think it will help much. Most likely it's important to know the distance between instanced point and border of a polygon. There is two nodes which can help with it `Distance point line` and `Project point to line`.

**Comment by vicdoval** [comment]
Check the examples in the Boundaries Force documentation https://github.com/nortikin/sverchok/blob/master/docs/nodes/pulga_physics/pulga_boundaries_force.rst

**Comment by mlevet** [comment]
Thank you, boundaries gives me pretty good results indeed !
Only problem is, now in some cases, random objects are too big to fit and
then collapse inside the boundaries.
A good option, if possible, would be to detect any contact between objects
and then reduce the number of objects on the surface when it happens
Is there a node by any chance that can detect collapsing objects in a list
of objects ?

**Comment by vicdoval** [comment]
You could use another Pulga Physics solver with a Fit Force, then if the input radius is more than the output radius it means there is a collision happening and maybe remove those items...
![image](https://user-images.githubusercontent.com/10011941/112112562-f9219080-8bb5-11eb-9109-569210dd3fb6.png)
