### ISSUE TITLE
Set property MK2 is sending "unsupported operand type(s) for +: 'NoneType' and 'list'" after update

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#3946]
I'm using several set property MK2 nodes in a project to set some values 
I'm now receiving this error in all of them
Any idea in what got wrong ?
<img width="1131" alt="Capture d’écran 2021-03-02 à 14 00 04" src="https://user-images.githubusercontent.com/17178730/109652159-b3961880-7b5f-11eb-9417-159f51c2fd08.png">

**Comment by zeffii** [comment]
Ratio node will be outputting a list, like `[[1]]` , which is wrapped. and you are assigning that to a property of the socket which is expecting a single float.

**Comment by mlevet** [comment]
I just found out the node is showing the same error when empty in a new project, i have two dependencies missing : FreeCAD and PyMCubes, maybe it's related ? I'm trying to install it now. (Just upgraded to blender 2.93 this morning)

**Comment by zeffii** [comment]
missing dependencies are only a problem if you try to load a node tree which uses nodes that rely on those dependencies.

You may want to downgrade to the older version of Blender if you can't get a compatible FreeCAD for Blender 2.93's Python binary.

**Comment by zeffii** [comment]
but yeah, in 293 also my mk2 starts out in this error state..

**Comment by mlevet** [comment]
Yes i just went back to 292 and it works ok now !

**Comment by zeffii** [comment]
i'm a little puzzled about this..

**Comment by zeffii** [comment]
this has nothing to do with the missing dependancies tho :)  i just tried Set prop MK2 and am trying to pickup SNlite socket 0 (for something like The Petal Sine example) and it also doesn't work,

**Comment by mlevet** [comment]
Yes in 292 the same dependencies are also missing for me and Set Prop works

**Comment by zeffii** [comment]
it may be that the ast module ( which is a python standard library ) is a different implementation..

**Comment by zeffii** [comment]
i say that because if the underlying code hasn't changed for the node,  but the Python version is different between Blender versions, then for whatever reason, that's where to starting looking for reasons.

**Comment by zeffii** [comment]
when i get time i'll compare how `Set Prop` code runs on 2.92 and 2.93 side-by-side, or maybe someone else will if they have time.

SNLite is a complex node with a lot of trickery in the background, so the NodeRemote control+ would be neater to use if you didn't have to hook it up this way.

![image](https://user-images.githubusercontent.com/619340/109802640-5f9f3880-7c20-11eb-9097-60c7329fcd61.png)

**Comment by Durman** [comment]
By the way, properties in sockets UI do not belong to the SNL node. They are attributes of sockets. I don't think `Node remote control` node can get access to them.

**Comment by zeffii** [comment]
yeah, this is offtopic, but maybe there could be a split in the choice chain
```
nodetree->node-> ( sockets  |  properties ) ->
```

**Comment by zeffii** [comment]
ah ha!
```python
# Blender 2.93
>>> isinstance(p.value.slice.value, ast.Num)
False
```
but
```python
# Blender 2.92
>>> isinstance(p.value.slice.value, ast.Num)
True
```
so maybe in 2.93 `isinstance(p.value.slice.value, (ast.Num, float, int))`
because ( https://docs.python.org/3/library/ast.html#node-classes )
```md
Deprecated since version 3.8: Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant 
and ast.Ellipsis are still available, but they will be removed in future Python releases. 
In the meantime, instantiating them will return an instance of a different class.
```

**Comment by zeffii** [comment]
OK. this seems to work in both python 3.7.7 and 3.9.2 ( Blender 2.9.2 and 2.9.3 respectively)
```python
def parse_to_path(p):
    '''
    Create a path and can be looked up easily.
    Return an array of tuples with op type and value
    ops are:
    name - global name to use
    attr - attribute to get using getattr(obj,attr)
    key - key for accesing via obj[key]
    '''

    if isinstance(p, ast.Attribute):
        return parse_to_path(p.value) + [("attr", p.attr)]

    elif isinstance(p, ast.Subscript):
 
        if isinstance(p.slice.value, ast.Num):
            return  parse_to_path(p.value) + [("key", p.slice.value.n)]
        elif isinstance(p.slice.value, (float, int)):
            return  parse_to_path(p.value) + [("key", p.slice.value)]
        elif isinstance(p.slice.value, ast.Str):
            return parse_to_path(p.value) + [("key", p.slice.value.s)]
        elif isinstance(p.slice.value, str):
             return parse_to_path(p.value) + [("key", p.slice.value)]

    elif isinstance(p, ast.Name):
        return [("name", p.id)]

    else:
        raise NameError
```

**Comment by zeffii** [comment]
while i'm at it, perhaps i should add the alias `nodes` to mean `<this_nodetree>.nodes`

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/110656660-6e599280-81c0-11eb-8e06-9c90f2a4472b.png)

**Comment by zeffii** [comment]
@mlevet should work as expected in 2.92 and 2.93 , and it has a new alias "nodes" , which is shown above. It detects the current node tree
