### ISSUE TITLE
Longest, Shortest, Cartesian Product Lacing

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#3952]
In Dynamo, we can change the behaviour of how a node deals with list input. We can choose to limit processing to the shortest of the inputs, or repeat the last element of the shorter lists to match those of the longest input or to do a Cartesian Product lacing. Is there an equivalent in sverchok? What is the standard/recommended way of dealing with this?

**Comment by vicdoval** [comment]
In sverchok.data_structure there are a lot of different functions to deal with list length if you want to implement in your own logic.

Other ways you can check https://github.com/nortikin/sverchok/issues/2443 where it is explained the method that many nodes with matching options use.

If you are looking for a more automated way to do it give me some days, i'm working in a node mixing to transform any node in a "multi-level recusion self matching node"
