### ISSUE TITLE
loop node For Each mode error

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#3953]
This is my file

[false.zip](https://github.com/nortikin/sverchok/files/6091120/false.zip)

**Comment by vicdoval** [comment]
could you explain your error a little bit more?, nodetree screenshot...

**Comment by vktcl** [comment]
![image](https://user-images.githubusercontent.com/74725748/110192753-0d058c80-7e6b-11eb-8bc1-06260a91d1d7.png)

**Comment by vktcl** [comment]
I found that this was my own problem, and my translation made a mistake for the loop node
