### ISSUE TITLE
Topologic menu appearing twice

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#3956]
When I install Topologic in sverchok, I get one menu item under Add. If I save the file, close and restart Blender and re-open the same file, I get two duplicate Topologic menus under the Add menu. Why is this happening? The Topologic code is at http://github.com/wassimj/topologicsverchok

**Comment by vicdoval** [comment]
Do you have the last Sverchok installed?
I think we messed it up a little by adding and removing the @zeffii monkey patch

**Comment by zeffii** [comment]
@wassimj  use the `shift+A` menu kb shortcut,   that default "Add" menu is not your friend at the moment

**Comment by zeffii** [comment]
@vicdoval   . maybe worth asking blender devs for a solution that will benefit custom node creators in general.

unless we blatantly write our own version of `node_utils`, it's not something i've looked at for a long time,  or alias/clone node_utils and monkeypatch the offending functions at runtime while leaving the original untouched -- we'll always have to keep an eye on any changes in node_utils.  i get a bad taste in my mouth.

**Comment by vicdoval** [comment]
It looks that Animation Nodes has a nice Add menu with a working Search on it...

**Comment by zeffii** [comment]
it doesn't have two searchs anymore?

**Comment by zeffii** [comment]
http://docs.animation-nodes.com/documentation/introduction/interface/node_menu.png

**Comment by vicdoval** [comment]
Fixed at #3959
