### ISSUE TITLE
WISHLIST: SV Custom SET and GET Attribute for Geometry Nodes instancing

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3960]
Snapshot:
<img width="853" alt="Screen Shot 2021-03-08 at 12 40 30 am" src="https://user-images.githubusercontent.com/3952687/110241805-f2383280-7fa6-11eb-8382-7c6e62435a2c.png">

As shown by Bradley Animation with Animation Nodes here:
https://www.youtube.com/watch?v=EmMyxSRGhRc

I am wondering if SV can support the creation of Custom Attribute (Points) and fill it values so that Geometry Nodes can understand the value and using it for instancing.

**Comment by vicdoval** [comment]
If it can be done in python then it can be done in sverchok

**Comment by enzyme69** [comment]
Yes, I am trying to dig more into it. Bradley Animation is using AN version with some extra nodes from Kuldeep Singh to set custom attribute.

**Comment by enzyme69** [comment]
In the past, we have already Attribute "Col". But in recent Blender there is also "Geometry" etc which I hardly used. But probably related to Geometry Nodes instancing.

<img width="935" alt="Screen Shot 2021-03-08 at 1 08 48 am" src="https://user-images.githubusercontent.com/3952687/110242579-d898ea00-7faa-11eb-82d2-be484027ffb3.png">


https://docs.blender.org/manual/en/latest/render/shader_nodes/input/attribute.html

**Comment by enzyme69** [comment]
Currently reading this:
https://docs.blender.org/manual/en/dev/modeling/geometry_nodes/attributes_reference.html

**Comment by Durman** [comment]
This is looks like [original code](https://github.com/3DSinghVFX/animation_nodes/blob/extranodes/animation_nodes/nodes/object/set_custom_attribute.py) of the node.

<details> 
  <summary>code</summary>  

```py

        if object is None: return object
        if object.type != "MESH": self.raiseErrorMessage("Object should be Mesh type.")
        if attName == "": self.raiseErrorMessage("Attribute name can't be empty.")

        attribute = object.data.attributes.get(attName)
        if attribute is None:
            attribute = object.data.attributes.new(attName, self.dataType, self.domain)
        elif attribute.data_type != self.dataType or attribute.domain != self.domain:
            object.data.attributes.remove(attribute)
            attribute = object.data.attributes.new(attName, self.dataType, self.domain)

        if self.domain == "POINT":
            amount = len(object.data.vertices)
        elif self.domain == "EDGE":
            amount = len(object.data.edges)
        elif self.domain == "CORNER":
            amount = len(object.data.loops)
        else:
            amount = len(object.data.polygons)

        if self.dataType == "FLOAT":
            _data = FloatList.fromValues(VirtualDoubleList.create(data, 0).materialize(amount))
        elif self.dataType == "INT":
            _data = VirtualLongList.create(data, 0).materialize(amount)
        elif self.dataType == "FLOAT2":
            _data = VirtualVector2DList.create(data, Vector((0, 0))).materialize(amount)
        elif self.dataType == "FLOAT_VECTOR":
            _data = VirtualVector3DList.create(data, Vector((0, 0, 0))).materialize(amount)
        elif self.dataType in ["FLOAT_COLOR", "BYTE_COLOR"]:
            _data = VirtualColorList.create(data, Color((0, 0, 0, 0))).materialize(amount)
        else:
            _data = VirtualBooleanList.create(data, False).materialize(amount)

        if self.dataType in ["FLOAT", "INT", "BOOLEAN"]:
            attribute.data.foreach_set("value", _data.asMemoryView())
        elif self.dataType in ["FLOAT2", "FLOAT_VECTOR"]:
            attribute.data.foreach_set("vector", _data.asMemoryView())
        else:
            attribute.data.foreach_set("color", _data.asMemoryView())

        attribute.data.update()
        return object

```

</details>

**Comment by enzyme69** [comment]
So far, the most interesting bits of Geometry Nodes is the ability to separate Vertex Color data like "SvCol" XYZ, then inject it back into Geometry Nodes.

**Comment by Durman** [comment]
![2021-03-13_12-16-52](https://user-images.githubusercontent.com/28003269/111024052-01c7d900-83f6-11eb-89b7-b8ed17d719ea.png)

**Comment by Durman** [comment]
![2021-03-13_13-35-14](https://user-images.githubusercontent.com/28003269/111025957-152c7180-8401-11eb-951d-4dfb51441844.png)

**Comment by summereasy** [comment]
Hey @Durman, I noticed an interesting tool in your screenshot. And quite useful.
Is that a build-in tool or some utility you made yourself? 
![screenshot](https://user-images.githubusercontent.com/51897649/111055791-5b8ed880-84b4-11eb-8e50-967757465bfa.png)

**Comment by Durman** [comment]
Do you mean spreadsheet editor? This is not what can be done with Python so it is build-in functionality. Now it's in 2.93 Blender version. It shows some attributes of selected mesh. Later more functionality will be added like filtering, editing values and etc. So it's on early development stage.

**Comment by summereasy** [comment]
> Now it's in 2.93 Blender version. It shows some attributes of selected mesh. Later more functionality will be added like filtering, editing values and etc. So it's on early development stage.

Oh! I see! It is great to know it's coming and thanks!

**Comment by Durman** [comment]
@enzyme69 or someone else, do you have any ideas in mind about usecases for the `set mesh attribute` node?

**Comment by enzyme69** [comment]
It's probably for Geometry Nodes and instancing and things like Attribute Transfer node.

Set Mesh Atrribute ... maybe:
- injecting color into points (cloud?)
- getting and setting radius from grease pencil (stylus pressure stroke) into curves?
- custom attribute

I think Kuldeep shows some Animation Nodes set and get custom attribute.

**Comment by AndGuz** [comment]
This idea would be pretty useful for use it with geonodes fields.

**Comment by Durman** [comment]
You can create attributes with Sverchok and GN can utilize them.

![2021-12-23_13-55-47](https://user-images.githubusercontent.com/28003269/147223381-6e3dfe12-f83c-41e2-80d9-310d19bff42c.png)
