### ISSUE TITLE
Conversion from Curve to Mesh causes error

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#3967]
I just did something funny:

I use Polyline Viewer and output X curve. Then I manually convert the Curve into Mesh. And then SV node tree complains: I am supposed to output curve, why is it a mesh now.

<img width="1141" alt="Screen Shot 2021-03-13 at 10 49 38 pm" src="https://user-images.githubusercontent.com/3952687/111029008-762e6680-844e-11eb-8078-0e0c1d3b7d40.png">

**Comment by zeffii** [comment]
you are converting the output of the Polyline Viewer, therefore you are changing the data-kind of the objects that it produced.  You should instead make a copy of the output of Polyline viewer, and then convert that. This way the link is broken, and PolylineViewer will be able to continue to operate on the objects that it "owns".

**Comment by Durman** [comment]
I would not like to code the check whether a user decided to convert output mesh into something else for some reason.
