### ISSUE TITLE
Installing scipy on Windows

### ISSUE THREAD

**Issue by jasonw22** [nortikin/sverchok#3968]
## Problem statement

I am unable to install scipy successfully within Blender, running on Windows.

## Steps to reproduce

1. Go to Preferences > Addons > Node: Sverchok > Extra Nodes
2. Click "Install with PIP" under SciPy
3. See success message
4. Restart Blender
5. Go to Preferences > Addons > Node: Sverchok > Extra Nodes
6. SciPy is not installed

Also, if I do: 
`C:\Program Files\Blender Foundation\Blender 2.92\2.92\python> .\bin\python.exe -m ensurepip`
I see: 
`Requirement already satisfied: pip in c:\users\jason\appdata\roaming\python\python37\site-packages (19.2.3)`
when I would have expected to see a path within the Blender folder.

## Expected result

SciPy is installed

## Actual result

SciPy is not installed

## Sverchok version

sverchok-master.zip from github. Version 0.6.0.0

**Comment by jasonw22** [comment]
Potentially relevant? 
https://developer.blender.org/T71856

**Comment by cvillagrasa** [comment]
Hi, it may have nothing to do if there is an underlying issue, but when going to install modules, do you start Blender as admin?

Alternatively, if you run this from the text editor, do you also get the success message?

```python
import sys
import os
import subprocess

def install_package(package):
    if not isinstance(package, list):
        package = [package]
    subprocess.call([os.path.join(sys.prefix, 'bin', 'python.exe'), "-m", "pip", "install", *package])
    
if __name__ == '__main__':
    install_package(['--upgrade', 'pip'])
    install_package('scipy')
```

**Comment by zeffii** [comment]
reopen if this is not yet resolved.
