### ISSUE TITLE
Matrix quick link buttons in Property Panel trigger errors when clicked

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#3976]
The nodes that have quick links (matrix, vertices etc) if these buttons are clicked in the PP it generates an error.
Perhaps these should be only displayed in the node and not in the PP. 
The code that draws the UI components of a node in the PP should probably look at the context and not display these quick link buttons if the context is PP

<img width="504" alt="SV-Bug-QuickLinkButtons-PropertyPanel" src="https://user-images.githubusercontent.com/2083719/111638116-6c9b5a80-87d0-11eb-8bb2-c652a5138f23.png">

Here’s a possible location (as per @Durman) were the context could be checked:
https://github.com/nortikin/sverchok/blob/fe5a27fc21a7ca3242215a9ef8751c2c76bfbc93/core/sockets.py#L1235-L1249

**Comment by zeffii** [comment]
the operator will need to track `tree_name` and `node_name`
```
    tree_name : StringProperty()
    node_name : StringProperty()
```
those operator buttons don't pass that information by default if the node isn't "active/selected" or the button is found in the side panel.

**Comment by Durman** [comment]
I think it's more logical just to remove this buttons from N panel adding `poll` method to the operator.

**Comment by zeffii** [comment]
yeah, 
```python
    @classmethod
    def poll(cls, context):
        return hasattr(context, 'socket')
```
doesn't hide them, but does make them unclickable.
![image](https://user-images.githubusercontent.com/619340/111656498-ddf7ff00-880a-11eb-8910-085ac12cc44a.png)

**Comment by DolphinDream** [comment]
Should these be displayed at all? 
Also, how about if they are clickable but they actually create the quick links in the node editor as if the buttons on the node were pressed? perhaps that would be too fancy.. and may be simpler to just leave them grayed out.

**Comment by Durman** [comment]
To me it does not have too much sense. Purpose of the button is quickly to create and connect another node, and set up its values typically. All of this requires to be done directly in the node editor and not in sidebar.

The button could be removed from sidebar but muting them is just simplier.

**Comment by zeffii** [comment]
I don't know how to hide that operator entirely, that doesn't mean it's not possible.. i just failed to find a way.

However, tracking the socket name upon-click is not terribly convoluted. But it is a small amount of extra code. See this example PR: https://github.com/nortikin/sverchok/pull/3981/files  @DolphinDream, and if you look at the code in its immediate vicinity this is less code than `draw_link_input_menu` uses. (Not that either is better, ultimately..it becomes a choice of taste )

**Comment by Durman** [comment]
The link can be hidden entirely by modifying this block

https://github.com/nortikin/sverchok/blob/75b9b44d737252256eb4ac137081cd36b8c9ba37/core/sockets.py#L459-L465

There should be extra check sort of `if 'node' in context:`

**Comment by zeffii** [comment]
![GIF 3-19-2021 3-10-22 PM](https://user-images.githubusercontent.com/619340/111793275-6509ad80-88c5-11eb-9dd3-8ed9dde6dfe4.gif)

well..  either way.

**Comment by zeffii** [comment]
> There should be extra check sort of if 'node' in context:

i can't get that to work, you need to show me proof :)

**Comment by Durman** [comment]
I was trying found out difference between contexts in node draw method and in N panel. The result is that I didn't manage to find differences. Probably they are but in some nested objects.
