### ISSUE TITLE
MultiExtrude alt from addons Add sockets

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#3979]
Would it be possible to add input sockets to the 'MultiExtrude alt from addons' node? like seed for example?

**Comment by Durman** [comment]
Yes it's possible

**Comment by vicdoval** [comment]
For the moment you can use 'Set Property' node 
(copy data path over the property you want to control and paste it on the text field of Set Property)
![image](https://user-images.githubusercontent.com/10011941/111748604-07f40480-8891-11eb-9e9b-66689ddf178c.png)

**Comment by Sinasta** [comment]
thank you for your answer!

**Comment by zeffii** [comment]
this was never meant to be a serious node, but a _reference node_ for those who wanted to implement algorithms from existing add-ons, but didn't know where to start.
