### ISSUE TITLE
Feature request: analysis/simulation integration

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#3980]
I would like to ask if there any plans on integrating environemental analysis nodes? I use Vi-suite nodes for light analysis. Is there a possibility to connect sverchok to the visuite nodes? I know that ladybug nodes exist but they are not quiet powerful enough.

**Comment by vicdoval** [comment]
It would be very cool but Vi-suite is a very complex addon. How would you imagine that integration?
Maybe we could invite @rgsouthall to the conversation :)

**Comment by Sinasta** [comment]
Sadly i dont know anything about coding so i cant even estimate how complicated an integration would be. The results of the Vi-Suite analysis can be stored in an csv file so an interaction between both addons could be possible.

**Comment by Sinasta** [comment]
As shown with ladybug sverchok nodes an integration seems to be possible. the problem with ladybug is that the calculation has to be started automatically and the resulting meshes have to be deleted manually as well. so parametric analysis seem to be a bit problematic

**Comment by vicdoval** [comment]
>  the problem with ladybug is that the calculation has to be started automatically and the resulting meshes have to be deleted manually as well. so parametric analysis seem to be a bit problematic

If that is the only limitation you find in Ladybug probably it would be easier to fix that than to integrate the Vi-Suite.

> How would you imagine that integration?

I meant how do you imagine it as a user.
Identical to the ladybug workflow but with a different engine or you imagine something different?

**Comment by nortikin** [comment]
we can handle interaction with nore remote control node in sverchok and ask for response node
