### ISSUE TITLE
Frame info output bug

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#3983]
there seems to be a problem with the current Frame output from the frame info node. It skips the number: 168 and 251 as well as 849. Can someone verify if it is a general bug or if its just on my installation. If its only me i will close the issue.

**Comment by zeffii** [comment]
can't confirm. they aren't skipped here.

**Comment by Sinasta** [comment]
alright thank you than its unrelated to sverchok

**Comment by zeffii** [comment]
can't imagine how Sverchok would be involved, it reacts to frame change but doesn't control frame change anywhere (except if you manually press the forward / backward buttons on the Frame Info node...but even there, there isn't any form of frame change modification .. just +1 or -1 )

**Comment by zeffii** [comment]
please let us know when you figure it out!

**Comment by Sinasta** [comment]
i will! it is a really strange problem indeed.. i forgot to add that i am on latest blender 2.93 alpha release with quiet some experimental addons installed. maybe one of them is creating that bug. maybe viewport scrub timeline addon is the cause. I will let you know

**Comment by zeffii** [comment]
> maybe viewport scrub timeline addon is the cause.

well, yeah that does sound like a prime target  : )
