### ISSUE TITLE
[question] How do you filter vertices by vertex groups?

### ISSUE THREAD

**Issue by ItsCubeTime** [nortikin/sverchok#3986]
Feels rather basic but I havent quite managed to figure it out <3

Any help appreciated

**Comment by vicdoval** [comment]
Like this 
![image](https://user-images.githubusercontent.com/10011941/112346925-ba2f3000-8cc6-11eb-9d27-55c93e01e49c.png)

**Comment by Durman** [comment]
Probably the question was about this button.
![2021-03-25_08-46-25](https://user-images.githubusercontent.com/28003269/112420505-c0fd8780-8d46-11eb-87fa-4469a86df1a2.png)

**Comment by ItsCubeTime** [comment]
Awesome, I've been having another issue with the bool 2 node crashing Blender on execute with objects with a lot of geometry.

Is there some alternative node that I can use that is more reliable?

**Comment by vicdoval** [comment]
Check this answer https://blender.stackexchange.com/a/212983/105448

**Comment by zeffii** [comment]
@ItsCubeTime  if you have new questions, start a new thread :) . closing for now
