### ISSUE TITLE
recurse_f_level_control function

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#3988]
## Problem statement

@vicdoval 

Could you explain what the function is doing? Some example probably would help.

https://github.com/nortikin/sverchok/blob/4c9c1259476e8565ed20744684db8b308bc940c1/utils/sv_itertools.py#L121-L141

**Comment by vicdoval** [comment]
It handles multilevel recursion matching.
It is used in many nodes 
Matches any number of inputs parameters  excutes the fuction with the desired nesting level for each paramter and returns one output (it does not unpack the result)
Check the code of Texture Evaluate, Oscillator, Map Range, move, scale... they all use it 

Is a previous version of the RecursiveNode mixin that uses _process_matched_ function (that works in the same way but also works for multiple outputs.

**Comment by Durman** [comment]
What is `multilevel recursion matching`?
Why this `concatenate` parameter is needed?
Why `main_function` should be called inside this function?

**Comment by vicdoval** [comment]
```
Given N parameters, 
a desired level of nesting for each parameter 
and a function that works with those parameters with that nesting level. (main func)

Check the nesting level.
If any parameter has more nesting that needed:
   wrap the parameters that has less level of nesting
   match the length of  the lists
   call again this function for every sublist
else:
  call the main_func.

Example:


In the Move node
Desired nesting:  
   Vertices: 3 [[[f, f, f], [f, f,  f],...]] 
   Movement Vectors: 3
   Strength 2 [[f,f,..]]

Outputs Vertices with a nesting level of 3

If the inputted lists has shape Vertices (4, 5, 3) level 4 , movement Vectors (1, 3) level 3, Strength (10) level 2   
                               Wrap        Match Length
Vertices         (4, 5, 3) --> (4, 5, 3) -> (4, 5, 3)
Movement Vectors (1, 3)    --> (1, 1, 3) -> (4, 1, 3)
Strength         (10)      --> (1, 10)   -> (4, 10)

result = []
for p in zip(*params):
   Vertices (5,3)
   Movement v (1,3)
   Strength (10)
   if concatenate== 'APPEND:
     result.append(main_func(params))
  else:
   result.extend(main_func(params))  (flattening output)

This example would output a Vertices List of level 4 if concatenate == APPEND or level 3 if concatenate == EXTEND 
```

Is not vey easy to explain with words, is it clearer now?

**Comment by Durman** [comment]
Why `matching_f` function is applied twice?

https://github.com/nortikin/sverchok/blob/4c9c1259476e8565ed20744684db8b308bc940c1/utils/sv_itertools.py#L136-L138

If understood correctly then from string 138 with recursive call it's possible to get into string 136. `p_temp` is nearly equal to `g`. It looks like `matching_f(g)` is usless.

**Comment by vicdoval** [comment]
`g` is a compendium of  sub-lists of `p_temp`, so is not equal, but checking all the nodes that use this function they all perform a `matching_f(g)`  at the beginning of in their `main_func` so it could be removed from the nodes or from this function

**Comment by Durman** [comment]
```py
result = recurse_f_level_control([[1, 2], [[3, 4], [[5, 6]]]], [], lambda d, *_: d, match_long_repeat, [1, 1])
result2 = recurse_f_level_control([[1, 2], [[5, 6]]], [], lambda d, *_: d, match_long_repeat, [1, 1])
print(result)
print(result2)
```
```
[[[1, 2], [3, 4]], [[[1, 2], [5, 6]], [[1, 2], [5, 6]]]]
[[[1, 2], [5, 6]]]
```
Why second result is not equal to second part of the first result? The results looks inconsistent with each other.

Or, to make this function to work correctly the input data should be prepared before calling the function?

**Comment by vicdoval** [comment]
Maybe because there is a extra bracket in the first `[5,6]`?

**Comment by Durman** [comment]
There are extra brackets in both cases.
in first case `g` is
```
loop 1 -> g = ([1, 2], [3, 4])
loop 2 -> g = ([1, 2], [[5, 6]])
```
You can see that `g` in second loop has the same data as input of second example.

**Comment by Durman** [comment]
As far as understood the initial goal of this function is to take input of any shape,  broadcasts it according given matching roles and demanded shape by the main function. I think it is what @nortikin  was trying to implement. 

The bad thing is that in current stage it's only half solution and the function can't guarantee that input will be fixed according required shape by the main function. The another thing is that adding this function into nodes code turn them into something what is difficult to understand. It requires to convert API of main functions of nodes into something what is hard to read.

I think that each node has its elementary function. For example for math node it could look like this.
```py
def math(a, b, op_name='ADD'):
    return [op[op_name](v1, v2) for v1, v2 in zip(a, b)]
```
It's easy to read and understand. But for using it in the vectorization function the API should look like this.
```py
def math(params, constant, matching_f):
    return [op[constant](v1, v2) for v1, v2 in zip(*matching_f(params))]
```
I don't like this API. It's says pretty nothing about what the function does. It makes hard to use the math function without its vectorization.

But there should be solution. There are two approaches I can think of to solve this problem. First is to use decorators with parameters.
```py
@vectorize(desired_levels=[1, 1], desired_levels_kwargs={op_name: 0})
def math(a, b, *, op_name='ADD')
```
`Desired levels` arguments should help vectorization function to understand what shape of data is expected by decorated function. But I think even more elegant and potentially more powerful solution could be used.
```py
@vectorize
def math(a: list, b: list, *, op_name: str = 'ADD')
```
It's possible to add annotations to arguments of the function which can be used by the decorator. This information should be sufficient for decorator to be able to prepare data correctly. Work of wrapping function in the decorator can roughly looks like this.
```py
def wrap(*args, **kwargs):
    out = []
    fixed_data = super_clever_broadcaster(args, kwargs, func)
    def args, kwargs in fixed_data:
        out.append(func(*args, **kwargs))
    return out
```
Downside of this approach can be that it's still is too complex. To simplify this it's possible simply to create iterator which will not call any functions but just reshape input data. The problem here to solve is how to make shape of data, processed by the main function, relevant with shape of input data. I expect such syntax.
```py
result = []
data_iterator = broadcaster(data, rules, result)
for data, out in data_iterator:
    out.append(math(*data, op_name='SUB'))
print(result) # <-- our result here with correct shape
```
As the result we have good readable API of the math function and simple flat foreach loop with the same result. All complexity will be hidden in broadcaster function which wont  be even so complex since it delegates part of its functionality to other code.

**Comment by vicdoval** [comment]
I had also realised of the limitations and complexity of this method, that is why I moved to the SvRecursiveNode mixin
where:
The desired levels are defined as socket properties
The nodes have this func `process_data(self, params)` that receives the data with the proper nesting level and from there it calls to 
```
a, b = params
math(
   a, b, 
   op_name=self.op_name,
   another_attrib=self.another_attirb,
   ...
   )
```

The RecursiveNode mixin matches the data by `ensure_min_nesting`  func + `process_matched `  func 

I have been using it lately and it removes  a lot of confusion from the nodes code and coder

**Comment by Durman** [comment]
I come out to the next solution

```py
    def math(a: float, b: float, *, mode='SUM'):
        if mode == 'SUM':
            return a + b
        elif mode == 'MUL':
            return a * b
```

This is a function which should be vectorized.

```py
    math = vectorize(math, match_modes="REPEAT")
```

For vectorization it's better to use decorator because it will not break the function API and it will be easier to pass parameters.

And now it can be used like this.
```py
    a_values = [[1, 2], [3, 4, 5]]
    b_values = [1, [2, 3], 4]

    print(math(a_values, b_values, mode='SUM'))
    >>> [[2, 3], [5, 7, 8], [7, 8, 9]]
```
The only issue I see here is how to pass `matching` parameters elegantly in case if each list of values should have its own settings (`values_a` - repeat last, `values_b` - cycle).
