### ISSUE TITLE
Point cloud data to mesh and bones

### ISSUE THREAD

**Issue by claudito1991** [nortikin/sverchok#3990]
Hi guys, i've never use sverchok and i end up here after a really long search. This is the thing i have a point cloud representing a face with data over time. I mean, the same points move each frame. I'm looking to translate this in Blender into:

1) a mesh.
2) a bone for each point. 

so i will be able to translate that data into usable mocap.

Is there a way to pull this off or i'm talking non-sense here

**Comment by zeffii** [comment]
is your pointcloud already processed down to features, like:  
![image](https://user-images.githubusercontent.com/619340/112659341-8eda4b80-8e54-11eb-93a4-5d9c775b0a6d.png)

where every frame you have all feature-points ?

**Comment by zeffii** [comment]
we can reopen this issue if you come back : )
