### ISSUE TITLE
how to multi extrude independently?

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#4000]
![Screenshot from 2021-03-29 23-35-07](https://user-images.githubusercontent.com/64699866/112903280-91080880-90e7-11eb-8075-dec871787e66.png)

Is there a way to independently multi- extrude (or duplicate along z) a list of faces? I want to generate buildings with different storey amounts and different heights but i struggle to find a way to do that. Help is appreciated. Thank you.

**Comment by zeffii** [comment]
using a few nodes atomically, you end up with something like this.

![image](https://user-images.githubusercontent.com/619340/112977759-b54efe00-9156-11eb-8fb4-411efd1e355e.png)

[VLAAIEN_2021_03_30_10_52.zip](https://github.com/nortikin/sverchok/files/6228433/VLAAIEN_2021_03_30_10_52.zip)
