### ISSUE TITLE
Meshing Points as Triangles (Delaunay 3D?)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4002]
[point_weight_distribute_002.blend.zip](https://github.com/nortikin/sverchok/files/6229001/point_weight_distribute_002.blend.zip)

I am wondering if SV nodes have now already have a way to triangulate bunch of points in 3D?

<img width="748" alt="Screen Shot 2021-03-30 at 11 30 24 pm" src="https://user-images.githubusercontent.com/3952687/112988858-0b03c480-91b0-11eb-896d-45cbbefde442.png">

**Comment by zeffii** [comment]
do you mean you want to subdivide each original Cube face, using the points generated by the points_on_mesh node?

**Comment by enzyme69** [comment]
Yes I guess something along that line, but like as triangle or voronoi on surface.

**Comment by enzyme69** [comment]
points on surface does not translate to voronoi 3D well

<img width="982" alt="Screen Shot 2021-03-31 at 6 58 01 am" src="https://user-images.githubusercontent.com/3952687/113048696-8b491a80-91ee-11eb-9224-a84cc00e5a02.png">

**Comment by zeffii** [comment]
the solution for a cube, (spherize the points, apply convex hull, get faces, restore original locations of verts) doesn't translate to arbitrary meshes.

I don't think we have a node that can do this yet, for arbitrary face orientations

![image](https://user-images.githubusercontent.com/619340/113121604-1b00c000-9213-11eb-9938-2118c483630f.png)

**Comment by zeffii** [comment]
wait.. you can do that.

![image](https://user-images.githubusercontent.com/619340/113124038-6916c300-9215-11eb-9601-ca2507238c7d.png)

**Comment by enzyme69** [comment]
Wait how is that Delaunay 3D node available already? Is it hidden?

**Comment by enzyme69** [comment]
<img width="717" alt="Screen Shot 2021-04-02 at 9 40 53 pm" src="https://user-images.githubusercontent.com/3952687/113409030-2c58f080-93fc-11eb-9b6c-8b39f9953147.png">

That's weird I installed some extras, and suddenly Delaunay 3D node appears!

open3D failed to install though... (no version satisfied)
