### ISSUE TITLE
Great news! The newest FreeCAD and Blender builds use Python3.9

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4005]
I just downloaded FreeCAD_weekly-builds-24612-Win-Conda_vc14.x-x86_64.7z and blender-2.93.0-e9616c82bd10-windows64.
Both are using Python3.9 now, making FreeCAD functions available for Sverchok with the latest Blender2.93.

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/pull/3674 hope it will be merged some day

**Comment by vktcl** [comment]
FreeCAD_weekly-builds-24665-Win-Conda_vc14.x-x86_64.7z
This latest version doesn't seem to work in 2.93
Sverchok cannot load out solidnode

**Comment by rendetto** [comment]
Yes, they reverted back to Python3.8 (https://github.com/FreeCAD/FreeCAD-AppImage/commit/095bbb2ec9bdbf59d2afbf341ff70d0926bd47c2). 

The FC0.20 win build which is Sverchok compatible is still 24612.  Seems it's too early for excitement. There are strange things in this build because I got several problems concerning some FC related nodes. For example the Mefisto triangulation doesn't create polygons or edges in "Solid To Mesh", also the "Compound Solid" doesn't work(the API seem changed there). I hadn't have time to check all Solid nodes but surely there will be things to tweak, because this is the first SV compatible FC after 0.19(build19697).
