### ISSUE TITLE
Voronoi 3D (SciPy) why missing corner

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4010]
I just stumbled upon Voronoi 3D node by accident. I wonder why it's missing the "corner" when used with box for example:

<img width="807" alt="Screen Shot 2021-04-02 at 10 04 30 pm" src="https://user-images.githubusercontent.com/3952687/113410585-7f807280-93ff-11eb-892e-36efb6f2cd46.png">

**Comment by enzyme69** [comment]
Ok I figured it out... hmm interesting node!
<img width="812" alt="Screen Shot 2021-04-02 at 10 07 05 pm" src="https://user-images.githubusercontent.com/3952687/113410700-c40c0e00-93ff-11eb-958e-a72bba6fea7d.png">

**Comment by enzyme69** [comment]
Still strange the the normal of the corner is flipped:

<img width="775" alt="Screen Shot 2021-04-03 at 12 30 11 am" src="https://user-images.githubusercontent.com/3952687/113419727-c1b3af00-9413-11eb-8aa3-6b15f50c1dca.png">

**Comment by zeffii** [comment]
I think this might be caused by the fact that in particular those 8 vertices form the extents of the domain inside which all encountered points exist. The scipy voronoi algorithm has limitations and is implemented via the http://www.qhull.org/ library, which might be a better place to look for definitive answers.

but yeah, it's probably not ideal - however, this is a very simplified use case,, which may produce weird results exactly because it is so simple.

**Comment by zeffii** [comment]
there's a term used in the qhull library called "joggle", which to me suggests that if you apply a small amount of 3d randomization to the 8 bounding verts of that cube, you will get optically better results, abeit slightly more imprecise in a computational sense.

**Comment by zeffii** [comment]
i'd like to point to the qhull [manual and "known issues"](http://www.qhull.org/news/qhull-news.html#problems) section, it specifically covers "unit cube" issues:

>  For points in the unit cube, it occurs when many points are approximately 1e-13 apart. Closer points or further apart points are OK. The problem has existed since the beginning of Qhull. Qhull 2019.1 introduces an experimental option Q14 to address this issue. It merges vertices that create topological errors. While it repairs some problems, it demonstrates the limitations of facet merging. 

it goes on, what do you think @portnov ? augment the node's documentation with links to qhull and known limitations?

**Comment by portnov** [comment]
Ok...

**Comment by vktcl** [comment]
Voronoi 3D Node doesn't work well。The Voronoi 3D script node in the script node works bette

**Comment by enzyme69** [comment]
I agree with vktcl, I will just use SNL Voronoi 3D, or something fast and easy to use.
