### ISSUE TITLE
"Mesh Join" cannot join meshes containing only vertices anymore

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4018]
After commit "Bisect Node upgrade (#4014)" the "Mesh Join" node behaves differently. 
It cannot join objects containing only vertices anymore.
![Mesh_Join_Error](https://user-images.githubusercontent.com/66558924/113609172-18a7c700-9654-11eb-9334-84c38d0faa1d.jpg)
I don't know how many other nodes could be affected by this change, but it's alarming.
this is the test file:
[Mesh_Join_Error.zip](https://github.com/nortikin/sverchok/files/6259863/Mesh_Join_Error.zip)

**Comment by zeffii** [comment]
maybe, but in the simplest case of only joining verts, you don't need a mesh_join, this is purely concatenation of lists of verts..

![image](https://user-images.githubusercontent.com/619340/113618318-c9fc2c00-9657-11eb-9ed7-e0b9c5ad3ada.png)

**Comment by rendetto** [comment]
You're right, thanks! It's just that the reported error wasn't present before.
But if this is the way we go around it, I'm perfectly fine :)

**Comment by zeffii** [comment]
mesh_join should be able to join two vertex only lists too, clearly something happened :)
