### ISSUE TITLE
Following beginner tutorial, after some steps "too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by lajawi** [nortikin/sverchok#4021]
## Problem statement

I'm following a tutorial, but after some nodes I get an error already.

![grafik](https://user-images.githubusercontent.com/51792807/113723625-d3d26d80-96f1-11eb-9133-5ae1f3aa6c07.png)

## Steps to reproduce

Just follow [this](https://youtu.be/BeC10tyfoA8?t=94) video until 1:34.

## Expected result

A torus with hexagons, as seen in the video.

## Actual result

An error: `No data passed into socket 'vertices'`

## Sverchok version

I downloaded the latest release counting from today, in the preferences I checked for updates and updated. Although I tried before that, which also didn't work.

**Comment by zeffii** [comment]
which version of Blender?

**Comment by zeffii** [comment]
it works in a nightly build of Blender and latest Sverchok, that's why I ask.

out of interest, what happens if you "wake" sverchok up, pressing update buttons marked in red here
![image](https://user-images.githubusercontent.com/619340/113725664-d0d87c80-96f3-11eb-9a1b-750c2826a98d.png)

**Comment by lajawi** [comment]
> 
> 
> which version of Blender?

Latest, 2.92.0, but I just restared Blender and now it works.....

**Comment by lajawi** [comment]
> 
> 
> it works in a nightly build of Blender and latest Sverchok, that's why I ask.
> 
> out of interest, what happens if you "wake" sverchok up, pressing update buttons marked in red here
> ![image](https://user-images.githubusercontent.com/619340/113725664-d0d87c80-96f3-11eb-9a1b-750c2826a98d.png)

Now I added the `polygon boom`, it doesn't work anymore. It gives me `too many values to unpack (expected 2)` as error.

**Comment by lajawi** [comment]
> 
> 
> if you continue to have problems, come back.

I've some problems once again, the `Viewer Draw` doesn't work as in the video... It's really strange, it just worked, kind of, showing one vertex, but now it just says there's no input.
![grafik](https://user-images.githubusercontent.com/51792807/113733613-ea30f700-96fa-11eb-9b37-c5df3536a63d.png)

**Comment by lajawi** [comment]
> 
> 
> if you continue to have problems, come back.

Also, the `Polygon Boom` gives me 450 vertices as output, but the `Bounding Box` node gives me only one mean as output, which should be the same as the 450 from the `Polygon Boom`.

**Comment by zeffii** [comment]
to be clear, restarting Blender is usually a last resort, so is pressing those update buttons. It's not "nominal" behaviour :) 

In the case of Bounding box, and any node, where you see the output sockets aren't postfixed with a number (to indicate how many lists they contain..) you will get no data from them.

![image](https://user-images.githubusercontent.com/619340/113736078-19e0fe80-96fd-11eb-95e3-d8ee4089954e.png)

**Comment by lajawi** [comment]
> 
> 
> to be clear, restarting Blender is usually a last resort, so is pressing those update buttons. It's not "nominal" behaviour :)
> 
> In the case of Bounding box, and any node, where you see the output sockets aren't postfixed with a number (to indicate how many lists they contain..) you will get no data from them.
> 
> ![image](https://user-images.githubusercontent.com/619340/113736078-19e0fe80-96fd-11eb-95e3-d8ee4089954e.png)

In the video these numbers are all the same, why isn't it here?
![grafik](https://user-images.githubusercontent.com/51792807/113737008-e94d9480-96fd-11eb-900c-1732c715787f.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/113737172-14d07f00-96fe-11eb-9bcf-284a657070f1.png)

i can't reproduce that, check if there are updates to sverchok since you last tried. One of those nodes was updated within the last 2 hours.

> In the video these numbers are all the same, why isn't it here?

This I don't know. But I would like to encourage you to try the nightly 2.93 builds, which is what we (well, .. i am anyway) run Sverchok on to be sure Sverchok is working correctly and compatible with changes internal to Blender.

Sometimes videos are slightly dated, and running older versions of Sverchok's update system. Ideally sverchok only gets better, but it's a work in progress, but so is Blender, (so yet again..that's a thing to consider trying to run the cutting edge of Blender too)

**Comment by lajawi** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/619340/113737172-14d07f00-96fe-11eb-9bcf-284a657070f1.png)
> 
> ![image](https://user-images.githubusercontent.com/619340/113738189-fc149900-96fe-11eb-8bff-b7daa87460e6.png)
> 
> i can't reproduce that, check if there are updates to sverchok since you last tried. One of those nodes was updated within the last 2 hours.
> 
> > In the video these numbers are all the same, why isn't it here?
> 
> This I don't know. But I would like to encourage you to try the nightly 2.93 builds, which is what we (well, .. i am anyway) run Sverchok on to be sure Sverchok is working correctly and compatible with changes internal to Blender.
> 
> Sometimes videos are slightly dated, and running older versions of Sverchok's update system. Ideally sverchok only gets better, but it's a work in progress, but so is Blender, (so yet again..that's a thing to consider trying to run the cutting edge of Blender too)

As I already stated, I updated after I got some errors, but that still doesn't work.

**Comment by zeffii** [comment]
then https://builder.blender.org/download/

**Comment by zeffii** [comment]
what OS / version / are you using the supplied Python (built in to Blender) ?

**Comment by zeffii** [comment]
also, 
- is there any difference if you start a new/fresh nodetree and add nodes to that? 
- any other nodebased systems enabled at the same time ?
- or other addons that interact with the timeline ?
you aren't doing anything wrong, it's just uncommon that we get reports about Sverchok doing weird stuff.

**Comment by vicdoval** [comment]
To see where the error starts you can follow this:
https://github.com/nortikin/sverchok/issues/3846#issuecomment-768494520

**Comment by lajawi** [comment]
> 
> 
> what OS / version / are you using the supplied Python (built in to Blender) ?

How can I check?



> 
> 
> also,
> 
>     * is there any difference if you start a new/fresh nodetree and add nodes to that?
> 
>     * any other nodebased systems enabled at the same time ?
> 
>     * or other addons that interact with the timeline ?
> 
> 
> you aren't doing anything wrong, it's just uncommon that we get reports about Sverchok doing weird stuff.

I do have Animation nodes on, but in the alpha I don't.

**Comment by lajawi** [comment]
Why??
![grafik](https://user-images.githubusercontent.com/51792807/113846516-d9ce5a00-9796-11eb-9e1e-b4fc2c8abe67.png)

**Comment by lajawi** [comment]
Why??
![grafik](https://user-images.githubusercontent.com/51792807/113847121-6d078f80-9797-11eb-813e-7ada197412b4.png)

**Comment by zeffii** [comment]
got to blender header menu- > help -> save system info , and this produces a file like:
```
===========================================
= Blender 2.93.0 Alpha System Information =
===========================================


Blender:
===========================================

version: 2.93.0 Alpha, branch: master, commit date: .......
build date: .......
platform: Windows
...
...etc...
```
you can copy that here.

**Comment by zeffii** [comment]
hard to establish what's going on over the @lajawi , it's not something i'm able to reproduce. 

![image](https://user-images.githubusercontent.com/619340/113853471-fae67900-979d-11eb-86b4-12c9184a84f7.png)

one way to get an idea if something is throwing errors in the background and not "bubbling up to the top", is to show us the text file (in Blender's TextEditor Window) called `sverchok.log`

**Comment by zeffii** [comment]
are you using an Apple computer by any chance?

**Comment by lajawi** [comment]
> 
> 
> are you using an Apple computer by any chance?

Nope, Windows

**Comment by lajawi** [comment]
> 
> 
> hard to establish what's going on over there @lajawi , it's not something i'm able to reproduce.
> 
> ![image](https://user-images.githubusercontent.com/619340/113853471-fae67900-979d-11eb-86b4-12c9184a84f7.png)
> 
> one way to get an idea if something is throwing errors in the background is to show us the text file (in Blender's TextEditor Window) called `sverchok.log`

That file has 4176 lines of code/text.

**Comment by lajawi** [comment]
> 
> 
> hard to establish what's going on over there @lajawi , it's not something i'm able to reproduce.
> 
> ![image](https://user-images.githubusercontent.com/619340/113853471-fae67900-979d-11eb-86b4-12c9184a84f7.png)
> 
> one way to get an idea if something is throwing errors in the background is to show us the text file (in Blender's TextEditor Window) called `sverchok.log`

Something tells me my version of Sverchok is broken.

**Comment by zeffii** [comment]
if Github doesn't let you paste it into the issue, you can save it / zip it and drag the zip into this issue.

**Comment by zeffii** [comment]
you aren't trying to continue a nodetree that you saved in an older Blender + sverchok are you? Always start a fresh node tree if you are getting errors that make no sense.

**Comment by lajawi** [comment]
> 
> 
> if Github doesn't let you paste it into the issue, you can save it / zip it and drag the zip into this issue.

Wait, I'll paste it, after I removed some personal data, like name etc.
[sverchok.log](https://github.com/nortikin/sverchok/files/6271262/sverchok.log)

**Comment by zeffii** [comment]
maybe the update isn't updating..

**Comment by lajawi** [comment]
> 
> 
> maybe the update isn't updating..

It isn't, it stays at version 0.6.0.0, but I tried downloading the newest version, which is the same.

**Comment by zeffii** [comment]
we don't update the major revision very often `0.6.0.0` is totally misleading. We should do something about that.

**Comment by lajawi** [comment]
> 
> 
> we don't update the major revision very often `0.6.0.0` is totally misleading. We should do something about that.

With the new stable release from today, v8, it's working! Thanks!

**Comment by zeffii** [comment]
sorry for the inconvenience.

**Comment by zeffii** [comment]
@lajawi   these should work btw.

![image](https://user-images.githubusercontent.com/619340/113867454-da72ea80-97ae-11eb-8b30-c725b1d606fb.png)

**Comment by lajawi** [comment]
Where do I put the `Solidify` node, without the noise breaking?
https://youtu.be/BeC10tyfoA8

**Comment by lajawi** [comment]
> 
> 
> @lajawi these should work btw.
> 
> ![image](https://user-images.githubusercontent.com/619340/113867454-da72ea80-97ae-11eb-8b30-c725b1d606fb.png)

I did it in the preferences, in the addons tab.

**Comment by zeffii** [comment]
that button in preferences triggers the same code that "Check for updates" does in the above image

**Comment by zeffii** [comment]
the video author uses a Solidify modifier, not a node.

If you do want to use the solidify node, stick it between the last node going into the MeshViewer.

![image](https://user-images.githubusercontent.com/619340/113870766-7b16d980-97b2-11eb-8807-02588397126a.png)

**Comment by lajawi** [comment]
> 
> 
> the video author uses a Solidify modifier, not a node.
> 
> If you do want to use the solidify node, stick it between the last node going into the MeshViewer.
> 
> ![image](https://user-images.githubusercontent.com/619340/113870766-7b16d980-97b2-11eb-8807-02588397126a.png)

That messes up the coloring of the vertices.

**Comment by zeffii** [comment]
the add a solidify modifier, as shown in the video at the very end.

**Comment by vicdoval** [comment]
> we don't update the major revision very often `0.6.0.0` is totally misleading. We should do something about that.

Maybe we could move to something like Sverchok YY.MM  so the next stable release could be  Sverchok 21.5

**Comment by lajawi** [comment]
> 
> 
> > we don't update the major revision very often `0.6.0.0` is totally misleading. We should do something about that.
> 
> Maybe we could move to something like Sverchok YY.MM so the next stable release could be Sverchok 21.5

That seems actually quit reasonable, and then maybe Version behind it, like `YY.MM.V`, like `Sverchok 21.4.1`.
