### ISSUE TITLE
Monad is probably not working as expected right now

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4024]
<img width="1012" alt="Screen Shot 2021-04-07 at 2 52 45 pm" src="https://user-images.githubusercontent.com/3952687/113812202-055e3e00-97b1-11eb-9b25-b2bfdd4fc5dc.png">

In the past when using Monad, when I connect in attribute, it will create extra additional connect input node, but it does not do that anymore, so no input can be created. 

Is there already alternative to Monad? Like Group is actually working or not yet?

**Comment by zeffii** [comment]
it's a small change in bpy api, i'll fix it, but i recommend you do start using Groups and Loops :)
