### ISSUE TITLE
"Bounding Box"-node not working

### ISSUE THREAD

**Issue by lajawi** [nortikin/sverchok#4026]
## Problem statement

The `Bounding Box`-node isn't working right. I input 450 vertices, but it outputs only 1.
![grafik](https://user-images.githubusercontent.com/51792807/113848493-d340e200-9798-11eb-8765-79dc82e1252a.png)

## Steps to reproduce

I followed [this video](https://youtu.be/BeC10tyfoA8), try to do this until you get to the `Bounding Box`-node.

## Expected result

I expected the same result as in the video, the same amount of vertices as output as I inputted.

## Actual result

Only one vertex is give as output.

## Sverchok version

0.6.0.0, I tried updating several times already, it stays the same though.

## Blender version

2.93.0 Alpha

**Comment by vicdoval** [comment]
This node was updated 5 days ago, are you using the last sverchok version?

**Comment by lajawi** [comment]
> 
> 
> This node was updated 5 days ago, are you using the last sverchok version?

Yes, I downloaded it yesterday and updated in Blender multiple times already. Version 0.6.0.0

**Comment by zeffii** [comment]
i made a release (vstable8), maybe you would like to install that?

if that works, then for somereason the update feature isn't working on your machine. (maybe)

**Comment by lajawi** [comment]
> 
> 
> i made a release (vstable8), maybe you would like to install that?
> 
> if that works, then for some reason the sverchok-update feature isn't working on your machine. (maybe)

Thanks, now it works, although the said version still is 0.6.0.0.
