### ISSUE TITLE
How to keyframe nodes from Sverchok?

### ISSUE THREAD

**Issue by lajawi** [nortikin/sverchok#4027]
## Problem statement

I'm trying to keyframe values inside of nodes from Sverchok, but it doesn't work.

## Steps to reproduce

Just try to animate values inside of nodes from Sverchok.

## Expected result

An animation, keyframes in the `Dope Sheet`, `Timeline` or `Graph Editor`.

## Actual result

No animation, last keyframed value gets set as constant value, no keyframes in the `Dope Sheet`, `Timeline` or `Graph Editor`.

## Sverchok version

0.6.0.0, latest stable release v8, from today, 7th of April, 2021

**Comment by zeffii** [comment]
Blender developers decided not to include this feature in the "custom nodes" API. You are not able to, because that feature is not there :(

also animation nodes uses a workaround.

https://blender.stackexchange.com/questions/42540/how-to-create-keyframes-for-animation-nodes-which-i-can-see-in-dope-sheet

for Sverchok it works similarly, add an Empty, use the X position as your keyframe "reference" and load the FCurve of that object using `FCurve-in` node

**Comment by zeffii** [comment]
related, and more elaborate example of using `FCurve in` https://github.com/nortikin/sverchok/issues/3248

**Comment by zeffii** [comment]
if it's not clear, come back

**Comment by enzyme69** [comment]
If you use Frame Info node, you can bake animation that way. Drive and keyframing does not work inside Sverchok. Use object like empty, get the matrix transform and use that data inside SVerchok. Then Bake.

**Comment by lajawi** [comment]
> 
> 
> If you use Frame Info node, you can bake animation that way. Drive and keyframing does not work inside Sverchok. Use object like empty, get the matrix transform and use that data inside SVerchok. Then Bake.

What nod should I use to get the location of an object?

**Comment by zeffii** [comment]
> What node should I use to get the location of an object?

there are several ways

![image](https://user-images.githubusercontent.com/619340/114005573-f4203a80-985f-11eb-94a6-8d909bb5f974.png)

**Comment by zeffii** [comment]
i can imagine if that is confusing.

**Comment by zeffii** [comment]
also this way
![image](https://user-images.githubusercontent.com/619340/114022417-0905c980-9872-11eb-8127-940957299b66.png)

**Comment by lajawi** [comment]
Isn't there an `Object Info` node like in the shader editor?

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/114036848-b54eac80-9880-11eb-8349-b75c153a168f.png)

nope @lajawi   ,  would be simple to add, but we already have so many ways to get that information..  but I see the point you are making..

**Comment by zeffii** [comment]
it might looks something like this

![image](https://user-images.githubusercontent.com/619340/114072291-674aa080-98a2-11eb-87c8-4b4046200602.png)

code here: https://github.com/nortikin/sverchok/pull/4030

**Comment by lajawi** [comment]
> 
> 
> it might looks something like this
> 
> ![image](https://user-images.githubusercontent.com/619340/114072291-674aa080-98a2-11eb-87c8-4b4046200602.png)
> 
> code here: #4030 , but i'm unconvinced that this new node introduction solves any real issues / missing feature.

Thanks, it's in my opinion useful because other node editors have it too, and I already know how it works.
How can I use it?

**Comment by zeffii** [comment]
i think this is still better, it offers more options, and it is in keeping with Sverchok's matrix-centered approach

![image](https://user-images.githubusercontent.com/619340/114079028-f3ac9180-98a9-11eb-9533-54da55495ed6.png)

i won't be pushing the object info node.

**Comment by vicdoval** [comment]
It is a little contradictory that `Objects In` and` Object Id Out ` have so similar behaviour isn't it?, Maybe Objects in should be renamed 'Scene Objects Out'

**Comment by enzyme69** [comment]
I often think Objects In and Out in SVerchok is doing so much more, a bit
like Geometry Nodes. The thing with Geometry Nodes that is interesting is
that when you use Instance, the animated and transformed instance are
still the original objects, with UV, etc. But when you add extra modifier,
it become real object and mesh.

With Sverchok, Objects In processed and Out will be edited and no longer
the original objects.

>

**Comment by Durman** [comment]
> > it might looks something like this
> 
> Thanks, it's in my opinion useful because other node editors have it too, and I already know how it works.
> How can I implement it?

@lajawi If you want implement any new node just find a pull request with new node and have a look at its code. Also you probably have to learn using `git` if you are not familiar with it yet.
