### ISSUE TITLE
Cannot unregister menus?

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4031]
## Problem statement

I am getting this error when quitting Blender. Could you tell me what I am doing wrong? Thanks
Can't unregister menu class <class 'sverchok.ui.nodeview_space_menu.NODEVIEW_MT_EX_TOPOLOGICSVERCHOK_Topologic'>
unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by zeffii** [comment]
This might be due to Blender unregistering Sverchok first, and that menu class is gone, then Blender unregisters the topologic menu?

I would do a test adding a `try/except` inside the unregister function.

**Comment by zeffii** [comment]
which i see, is what you are doing here
```python
    for clazz in topologic_menu_classes:
        try:
            bpy.utils.unregister_class(clazz)
        except Exception as e:
            print("Can't unregister menu class %s" % clazz)
            print(e)
```

**Comment by zeffii** [comment]
it seems that for some reason the classes are already unregistered at that stage.. (topologic piggy backs on quite a few of our "heavy lifter" functions)

```
# while everything is registered
>>> hasattr(bpy.types, clazz.__name__)
True

# after some unregistering has taken place
>>> hasattr(bpy.types, clazz.__name__)
False
```

**Comment by zeffii** [comment]
there's a function which I don't think we use.. 
```
    if clazz.is_registered:
        bpy.utils.unregister_class(clazz)
```

**Comment by zeffii** [comment]
while blender is running fine you can do
```
>>> bpy.types.NODEVIEW_MT_EX_TOPOLOGICSVERCHOK_Topologic.is_registered
... True
```

**Comment by zeffii** [comment]
feel free to reopen if you feel i've neglected something

**Comment by wassimj** [comment]
Thanks zeffi. I copied and customised the init file from sverchok extra, but I am not familiar with all the code in there. The init file is not quite right and Topologic menu item ends up on top and also interferes with sverchok extra (I must be doing something wrong, but I am not sure what). Can you point me to the simplest init file that I can use to load a Topologic menu and all the classes in the nodes folder? Thanks

**Comment by vicdoval** [comment]
Take a look to  https://github.com/vicdoval/sverchok-open3d, i tried to make it easy to mimic
starting here https://github.com/vicdoval/sverchok-open3d/blob/master/__init__.py
https://github.com/vicdoval/sverchok-open3d/blob/master/menu.py
https://github.com/vicdoval/sverchok-open3d/blob/master/settings.py
