### ISSUE TITLE
SV Partial Menus Hotkey 1-5 display inside Geometry Nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4034]
Early this morning, I accidentally tap button 1-5 while working in Geometry Nodes. I was surprised at first, but soon I tested those hotkeys inside SV node tree and works great. I wonder why it can work inside Geometry Nodes... is this not supposed to happen?

Can the SV nodes created via hotkey inside GN have input and output as well? Like Custom Attributes that generate numbers?

<img width="851" alt="Screen Shot 2021-04-10 at 1 41 17 pm" src="https://user-images.githubusercontent.com/3952687/114257325-9546f680-9a02-11eb-9325-96d343a2cc0f.png">
<img width="882" alt="Screen Shot 2021-04-10 at 1 41 35 pm" src="https://user-images.githubusercontent.com/3952687/114257329-99731400-9a02-11eb-83bf-94556b056b13.png">

**Comment by zeffii** [comment]
no, the menu must not have a `poll` to detect which nodetree has the current context.

see.
https://github.com/vicdoval/sverchok/blob/071d8f2b959cf24f946cb3a96deff67dfbc5a597/ui/nodeview_space_menu.py#L203-L211

**Comment by zeffii** [comment]
time for an SVTreePoll mixin

**Comment by zeffii** [comment]
i've pushed a change to hide the partial menus from Geometry nodes.
