### ISSUE TITLE
Getting error when removing Topologic plug-in: missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4040]
## Problem statement
I am getting the following error when trying to deactivate and remove the Topologic plugin. What is mising?
```
Exception in module unregister(): 'C:\\Users\\wassimj\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\topologicsverchok\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\topologicsverchok\__init__.py", line 232, in unregister
    unregister_node_panels()
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok\menu.py", line 591, in unregister_node_panels
    bpy.utils.unregister_class(panel_type)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\topologicsverchok\__init__.py", line 232, in unregister
    unregister_node_panels()
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok\menu.py", line 591, in unregister_node_panels
    bpy.utils.unregister_class(panel_type)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

## Steps to reproduce
Deactivate an installed and active Topologic-Sverchok add on.

## Expected result
The add on deactivated

## Actual result

The error above

**Comment by zeffii** [comment]
make it 
```python
    if panel_type and panel_type.is_registered:
        bpy.utils.unregister_class(panel_type)
```
you are somehow unregistering those classes earlier than you realize.

**Comment by zeffii** [comment]
we could add a harmless extra check in "unregister_node_panels"
```
def unregister_node_panels():
    global node_panels
    for panel_type in reversed(node_panels):
        if panel_type and panel_type.is_registered:
            bpy.utils.unregister_class(panel_type)
    node_panels = []

```

**Comment by zeffii** [comment]
you could implement your own version of `unregister_node_panels` too, as above.  just to get an idea.

**Comment by zeffii** [comment]
maybe this was too subtle..
> the tautology here is that you can't unregister something that isn't registered anymore, and bpy is very blunt :)

**Comment by wassimj** [comment]
Thank you. I went back to the old code. Topologic menu continues to be non-standard. I just don't know enough about sverchok to fix the init file to make it behave like the other menus. Maybe someone can help by creating a PR on my github repo ([http://github.com/wassimj/topologicsverchok](http://github.com/wassimj/topologicsverchok)) to fix the init file. Until then, it shows up and has a long list of methods all under one menu item. Works, but not ideal.

**Comment by zeffii** [comment]
would it make sense to have your own topologic menu, it is possible to register nodes without adding them to the default menu in any way, and then add a keymap for your new menu.

i'll have a try at making the most bare bones 3rd party add-on.

**Comment by wassimj** [comment]
Thank you @zeffii for any help you can offer! I still would like Topologic to show up in the default menu as it sometimes relies on items in that menu. I would like it to appear more integrated in the sverchok ecosystem. What I would love to have is a hierarchical menu - under "Add" as such (example only):

Topologic

> Vertex

- Vertex.ByCoordinates
- Vertex.Coordinates

> Edge

- Edge.ByStartVertexEndVertex
- Edge.VertexAtParameter

> Wire
> Face
> Shell
> Cell
> CellComplex
> Cluster

- Cluster.ByTopologies

> Topology

- Topology.ByGeometry
- Topology.Geometry

> Dictionary

- Dictionary.ByKeysValues
- Dictionary.Keys
- Dictionary.Values
- Dictionary.ValueAtKey

> Graph

- Graph.ByTopology
- Graph.Topology
- Graph.ShortestPath

**Comment by zeffii** [comment]
The downside to hoisting a new set of nodes into Sverchok is that the registration mechanism (monolith) evolved over 7 years and was not designed with 3rd party extensions in mind. It makes many assumptions, but, at the same time it isn't actively trying to discourage "injecting" new nodes. I can see the problem here is that it takes time to reason about the code involved, and it's much more fun/productive to get new nodes working.

We can easily add placeholder menu test in our main menu, which would only show up if the user has topologic installed, it would look for something like
```
    if hasattr(bpy.types, "NODEVIEW_MT_SVTOPOLOGIC"):
        layout.separator()
        layout.menu("NODEVIEW_MT_SVTOPOLOGIC")
```
then you would define that menu class (see `utils/nodeview_space_menu.py` ) for extensive references to menus.
- for docs, the documentation mechanism certain isn't expecting nodes to be located outside of `sverchok/nodes` or their `rst` to be anywhere other than `sverchok/docs` ,  ultimately this may not be a big deal early on.

**Comment by wassimj** [comment]
Yes, my focus has been on getting as close as possible to Topologic's functionality in Dynamo and Grasshopper. I am not far from that and TopologicSverchok has innovations that are not available on these other platforms. That is where my strength is rather than in configuration etc. So, ok. You know much more than me about this. I am happy to go with your suggestion on how to best load Topologic into sverchok. Thank you again for all your help. It has been amazing to participate with the open-source community.

**Comment by zeffii** [comment]
i might need your help getting topologic installed :) but i'll give it a solid try first!

**Comment by wassimj** [comment]
@zeffii Absolutely! Please don't waste your time, though. I am happy to do a zoom session to help you install it. DM me to set up a time.

**Comment by zeffii** [comment]
thanks, but i'll refuse Zoom purely on principle :)

**Comment by zeffii** [comment]
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Downloads\blender29\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\topologicsverchok\__init__.py", line 30, in <module>
    blenderName = [name for name in os.listdir(home+"\\"+conda) if name.startswith('Blender')][0]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\zeffi\\\\.conda\\envs'
```
i'll get conda then :)

**Comment by wassimj** [comment]
Oops.. I messed up the "\" too many of them. I will update the init file shortly.

**Comment by wassimj** [comment]
I just update the repo. The latest is 0.5.0.4

**Comment by wassimj** [comment]
> thanks, but i'll refuse Zoom purely on principle :)

My bad! I meant to say Jitsi! https://meet.jit.si/  ;-)

**Comment by vicdoval** [comment]
You may want to check this https://github.com/vicdoval/sverchok-open3d#sverchok-addon-template

**Comment by zeffii** [comment]
the instructions on the `topologicPy` seem to build / install fine, using `conda`.

enabling however now gives this error:
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Downloads\blender29\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\topologicsverchok\__init__.py", line 51, in <module>
    from topologic import Vertex, Edge, Wire, Face, Shell, Cell, CellComplex, Cluster, Topology
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\zeffi\.conda\envs\Blender377\lib\site-packages\topologic-0.4-py3.9.egg\topologic\__init__.py", line 18, in <module>
    import cppyy
  File "C:\Users\zeffi\.conda\envs\Blender377\lib\site-packages\cppyy\__init__.py", line 74, in <module>
    from ._cpython_cppyy import *
  File "C:\Users\zeffi\.conda\envs\Blender377\lib\site-packages\cppyy\_cpython_cppyy.py", line 20, in <module>
    c = loader.load_cpp_backend()
  File "C:\Users\zeffi\.conda\envs\Blender377\lib\site-packages\cppyy_backend\loader.py", line 85, in load_cpp_backend
    raise RuntimeError("could not load cppyy_backend library, details:\n%s" %
RuntimeError: could not load cppyy_backend library, details:
  [WinError 1114] A dynamic link library (DLL) initialization routine failed
  Could not find module 'C:\Users\zeffi\.conda\envs\Blender377\lib\site-packages\cppyy_backend\lib\libcppyy_backend.cp39-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  Could not find module 'libcppyy_backend.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  Could not find module 'libcppyy_backend.cp39-win_amd64.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by zeffii** [comment]
and that may be due to me using Blender's own Python binary, rather than the suggested route of renaming that folder and letting blender find the system Python.
