### ISSUE TITLE
Add the "To Control Panel" button to "Bezier in" and "NURBS in"

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#4045]
Add the "To Control Panel" button to "Bezier in" and "NURBS in"

**Comment by zeffii** [comment]
which parts of these nodes? 

![image](https://user-images.githubusercontent.com/619340/114775488-a466d500-9d71-11eb-8aab-f3312dabac79.png)

**Comment by maxim1967** [comment]
Add this for these nodes
![Снимок](https://user-images.githubusercontent.com/62519357/114779828-3de8b380-9d7f-11eb-8d8b-37f1b94dc96c.JPG)

**Comment by zeffii** [comment]
yes, but which buttons from the node UI ?

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/114836016-7cf42480-9dd2-11eb-8edb-395b074f1d07.png)

**Comment by zeffii** [comment]
i don't know if it makes sense to add all those to the 3d panel  

opinions @portnov , @nortikin @vicdoval @Durman  ?

**Comment by zeffii** [comment]
how about just  the "Get selection" button, and maybe a small "focus nodetree on this node" button, so user can tweak the rest on the node? or maybe all buttons on one row ` GET | SORT | APPLY MATRICES`

**Comment by maxim1967** [comment]
Only "Get selection" , and for NURBS still the choice of the method "Sverchok" or " Geomdl"

**Comment by Durman** [comment]
`Get selection` could be definitely useful, not sure about the rest. 

>  "focus nodetree on this node"

Oh, this can be tricky to code. @DolphinDream was trying to do something like this.

**Comment by maxim1967** [comment]
Perhaps yes, it is better to "Get selection", and for NURBS still the choice of the method "Cricket" or " Geomdl"

**Comment by zeffii** [comment]
there is "view2d.zoom_border" operator, which we should be able to context-fake..
```
        # this can maybe be cached...
        op2 = row.operator("view2d.zoom_border", text="", icon="TRACKER_DATA")
        node_x, node_y = node.absolute_location
        border_width = node.width * 4
        border_height = node.height * 3
        op2.xmin = node_x - border_width / 2
        op2.xmax = node_x + border_width / 2
        op2.ymin = node_y - border_height / 2
        op2.ymax = node_y + border_height / 2
        op2.wait_for_input = False
        # xmin=0, xmax=0, ymin=0, ymax=0, wait_for_input=True, zoom_out=False)
```

**Comment by zeffii** [comment]
should be cool..
![image](https://user-images.githubusercontent.com/619340/114855944-c64e6f00-9de6-11eb-8dce-555e784e4c42.png)

**Comment by maxim1967** [comment]
I agree. must be cool..

**Comment by zeffii** [comment]
it might require a macro-operator, (an operator that potentially calls several operators in sequence), just so we can offload Border calculation / tree context hopping as late as possible.

noone has proven to me that this isn't possible so i'll try further lateron.

**Comment by zeffii** [comment]
it may have to zoom out first, then convert `2d nodeview xy` to` 2d screen xy` for the border.

**Comment by maxim1967** [comment]
I'm not here to advise you, I just started learning Python, maybe that's what you need to do.

**Comment by maxim1967** [comment]
Alas, but so far only the main idea has been implemented.
1) Attempt with focus doesn't work

2) "NURBS in" lost the second "Geomdl"method.
![Снимок](https://user-images.githubusercontent.com/62519357/115103437-814b4980-9f5a-11eb-8ad6-b92bd302f1af.JPG)
![Снимок1](https://user-images.githubusercontent.com/62519357/115103446-90ca9280-9f5a-11eb-8c87-42745ae239e8.JPG)
