### ISSUE TITLE
'NodeSocket' object has no attribute 'socket_id'

### ISSUE THREAD

**Issue by OURLEDS** [nortikin/sverchok#4050]
## Problem statement

Still 'NodeSocket' object has no attribute 'socket_id'

## Steps to reproduce

1. Install blender 2.92
2. Download  prepared archive with Python libraries https://github.com/nortikin/sverchok/wiki/FAQ
On the "I can't install dependencies on Windows"
3. Locate the files under your version of Blender 2.92/2.92--copy paste that python folder you downloaded.
5. Open Blender 2.92
6. Load Bloom generator from here: http://fabacademy.org/2020/labs/techworks/students/faisal-alkilani/images/projectZoetrope/3dModeling/3D_models.rar
7.  Get the error.

## Expected result

![imagen](https://user-images.githubusercontent.com/46494097/114913025-99b34b00-9e18-11eb-985d-3833b4477e2e.png)

## Actual result

![imagen](https://user-images.githubusercontent.com/46494097/114913053-a172ef80-9e18-11eb-9166-762bca907e91.png)

## Sverchok version

 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.

sv: version: 0.6.0.0
sv: 663 nodes.
cleaning Sverchok cache
Read blend: T:\3D Printers\FRACTALS\Bloom_generator\Bloom generator ver 02.92 from scratch.blend
Loaded SvMatrixGenNodeMK2. 12 nodes are left unregistered.
Loaded CentersPolsNodeMK3. 11 nodes are left unregistered.
Loaded SvGenFloatRange. 9 nodes are left unregistered.
Loaded GenListRangeIntNode. 8 nodes are left unregistered.
Loaded SvScaleNodeMK2. 7 nodes are left unregistered.
Loaded SvMatrixGenNodeMK2. 7 nodes are left unregistered.
Loaded CentersPolsNodeMK3. 7 nodes are left unregistered.
Loaded SvGenFloatRange. 7 nodes are left unregistered.
Loaded GenListRangeIntNode. 7 nodes are left unregistered.
Loaded SvScaleNodeMK2. 7 nodes are left unregistered.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\handlers.py", line 207, in sv_post_load
    upgrade_nodes.upgrade_nodes(ng)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\upgrade_nodes.py", line 177, in upgrade_nodes
    if socket and not socket.prop_name:
AttributeError: 'NodeSocket' object has no attribute 'prop_name'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\handlers.py", line 220, in sv_post_load
    ng.update()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\node_tree.py", line 231, in update
    self.sv_update()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\node_tree.py", line 100, in sv_update
    self.sv_links.create_new_links(self)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\links.py", line 143, in create_new_links
    new_sv_links = SvLink.init_from_links(node_tree.links)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\links.py", line 97, in init_from_links
    output_socket, output_node = get_output_socket_id(link.from_socket)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\core\links.py", line 36, in get_output_socket_id
    return socket.socket_id, socket.node.node_id
AttributeError: 'NodeSocket' object has no attribute 'socket_id'

**Comment by OURLEDS** [comment]
It should create a custom node with this code:

def sv_main(samples=400, radius=2.0, zspacing=0.05):
    verts_out = []
    edges_out = []
    faces_out = []

    in_sockets = [
        ['s', 'samples', samples],
        ['s', 'radius', radius],
        ['s', 'zspacing', zspacing]
       ]

    out_sockets = [['v', 'Verts', [verts_out]],
                   ['s', 'Edges', edges_out],
                   ['s', 'Faces', faces_out]]
    
    p, e, f = bloom_sphere(samples, radius, zspacing)
    verts_out.extend(p)
    edges_out.extend(e)
    faces_out.extend([f])

    return in_sockets, out_sockets


But all I get is this: 
![imagen](https://user-images.githubusercontent.com/46494097/114916371-9e79fe00-9e1c-11eb-9083-f33b45762393.png)



Instead of this:

![imagen](https://user-images.githubusercontent.com/46494097/114916402-a6d23900-9e1c-11eb-994e-7003342f0c0f.png)

**Comment by zeffii** [comment]
There are several issues here.
- unfortunately `.blend` files created with Blender 2.79, won't load inside Blender 2.8+.
     - Blender version 2.79 (sub 0), Sverchok version 0.5.9.6
- the script node is now different, the same script is now written like this:

```python



```

**Comment by OURLEDS** [comment]
zeffii I wish you an amazing day. You have saved me 5% of incremental frustration and depression. Now I can play with blender to make life.
Thanks a lot, seriously I wish I knew what ever you know that allowed you to re-write the code.
Thanks so much  zeffii , honestly. Love you somehow. 
Thanks Github for existing .... 


Now I just need to do the same for the rest of all blocks XD
But this is great progress, I have been stuck endless in loops installing 10 versions of blender and messing up my computer with python versions .... at least now all dependencies work and the first main block works.... I just need to find out how to re write the rest of the blocks to work with the new Sverchok version like you did.

![imagen](https://user-images.githubusercontent.com/46494097/114927630-970d2180-9e29-11eb-8d5e-2daf4a4732bf.png)

**Comment by OURLEDS** [comment]
For some reason doing the same you did with just 3 blocks i get this:

![imagen](https://user-images.githubusercontent.com/46494097/114929115-4c8ca480-9e2b-11eb-9774-10d7815e104b.png)

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/114929392-05ef7800-9e34-11eb-9e50-99a1e8cb2950.png)

**Comment by zeffii** [comment]
get Blender 2.93 and install https://github.com/nortikin/sverchok/releases/tag/vstable8, 
and don't load that old 2.79 Blender file into anything above Blender 2.8+

**Comment by zeffii** [comment]
if you are a new user you should not have to _install_ any form of python, Blender comes with it's own installation of Python, and Sverchok works very well with it. I use that.

**Comment by OURLEDS** [comment]
Thanks so much, I just created a new file from scratach isntead of a new tree inside the old file. Thbat old file messes everything up. The thing is I don't know how to retrieve thge old blocks in red as they don't even show the name.
But yes its working now.

**Comment by zeffii** [comment]
one option to you is to have both Blender 2.79 installed with an appropriate [Sverchok for B2.79](https://github.com/nortikin/sverchok/releases/tag/2.79)
and Blender 2.93 with `vstable8` (above)

have them running side by side.  and try to build the same node tree in 2.93 from the equivalent (but newer nodes).

**Comment by zeffii** [comment]
There are significant differences in Blender 2.79 to 2.93 , and Sverchok made a few "big jumps" between the older versions - we had to sacrifice some backward compatibility in favour of progress.

**Comment by OURLEDS** [comment]
The thing is I can't find how to install properly sver for blender 2.79, everytime I do and install sver and then open the file, it is full of errors

**Comment by zeffii** [comment]
using [last Blender 2.79](https://download.blender.org/release/Blender2.79/latest/) and [Sverchok for B2.79](https://github.com/nortikin/sverchok/releases/tag/2.79) i can't even get the nodetree, it appears empty, no errors.

**Comment by zeffii** [comment]
i see you want to recreate this shape ? 

![image](https://user-images.githubusercontent.com/619340/115024350-409ef200-9ec0-11eb-88dd-2b2221027064.png)

**Comment by OURLEDS** [comment]
I have made some quite good progress.... but still need a lot of improvments. Yes that shape can be done. I think I can figure out how to do that one. I am at thos stage now.
![imagen](https://user-images.githubusercontent.com/46494097/115024839-8c4d9d80-9eb8-11eb-97b0-b5e6f6e6a5ae.png)


But I am looking to create things like this:

![imagen](https://user-images.githubusercontent.com/46494097/115025116-dc2c6480-9eb8-11eb-976f-d92e8b000c7b.png)


![imagen](https://user-images.githubusercontent.com/46494097/115025150-e8182680-9eb8-11eb-9354-e855c9e74605.png)


![imagen](https://user-images.githubusercontent.com/46494097/115025174-ee0e0780-9eb8-11eb-89bf-7c8b797b10fe.png)




![imagen](https://user-images.githubusercontent.com/46494097/115025299-1bf34c00-9eb9-11eb-9e4c-3f414bc403c4.png)


![imagen](https://user-images.githubusercontent.com/46494097/115025464-4e04ae00-9eb9-11eb-81ae-4aa1fd245007.png)


![imagen](https://user-images.githubusercontent.com/46494097/115025490-53fa8f00-9eb9-11eb-8342-f0b9ce83a004.png)


![imagen](https://user-images.githubusercontent.com/46494097/115025505-5957d980-9eb9-11eb-9a64-f3f3a05b7f27.png)


AND SPECIALLY THIS ONE

![blooms_1024x1024](https://user-images.githubusercontent.com/46494097/115025696-93c17680-9eb9-11eb-91ea-828bd151f4c3.gif)

**Comment by OURLEDS** [comment]
by the way I manage to get working on 2.79 jhust to follow the reference. don't ask me how exactly I did. But did deleted and reinstalled lots of things, to get it working. I had to delete several times the folde of blender 2.79 at Roaming App Data.

This is what it looks like the original file:

![imagen](https://user-images.githubusercontent.com/46494097/115026425-60cbb280-9eba-11eb-9c1f-fc51a5069a28.png)

**Comment by zeffii** [comment]
i'll close this now,  not because it's not interesting, but because ultimately there's nothing we can/want to fix in Sverchok to make that .blend work. The `NodeSocket` error is a symptom of breaking backward compatibility, as explained above.

I think you'll be fine : )
