### ISSUE TITLE
Why there is no way to connect shader textures with sverchok, which will be great for beginners.

### ISSUE THREAD

**Issue by nafik001** [nortikin/sverchok#4051]
Say I have a cool Shader node tree, which creates a cool new wave like texture. Now I am trying to convert that into mesh,(like the "voronoi to mesh" node...I dont think there is a beginner friendly way to do that. Moreover, Lets assume  I have a animating voronoi mesh, But there's no way to color each voronoi cell consistantly..because the poly count changes, and the Indexing really  messes things up. 

I guess the solution is some (most probably 3) simple new nodes.
#1. A "Texture to mesh" node, with the same functionality of the "voronoi to mesh" node, but it will take a shader texture as an input ,instead of vector noise.

#2. A shader input node, which will take a shader texture as input, and a vector field as an output (I know some complex textures will be hard to convert,But it can just show a error then.Lets start with easy and see where it goes.); which can be used as input in the #1 node.

#3. A node for Shader editor, which will take a shader trees output as input, and assign that to a name, which I can use in node 2.

I think these new nodes will be of great use, specially for beginners. As I am a beginner, please pardon my mistakes.

**Comment by Durman** [comment]
Could you show some example of what you have and what result would you expect to achieve?

**Comment by vicdoval** [comment]
Baking the texture would allow you to use Texture Evaluate or Texture field nodes, it would loose the "live" connection but may be the only way to go

**Comment by nafik001** [comment]
> Could you show some example of what you have and what result would you expect to achieve?

umm mainly ,I think there should be some new nodes.
okay, let me show a basic example what i'm trying to achieve.

lets think of a very basic texture, a 3*3 checkerboard, whichs each cell has a random greyscale color, something like:

![texture](https://user-images.githubusercontent.com/82643165/115048570-862ce080-9efb-11eb-9933-627872103e81.png)

Then, I need two things:
firstly, a node to subdivide a plane (provided by a input socket)
  into 9 faces, just like the texture... :

![mesh](https://user-images.githubusercontent.com/82643165/115048631-947afc80-9efb-11eb-92b2-b6884890d259.png)

secondly, extrude each face such that the height corresponds the grayscale value.(can be done with the "Extrude Separate Faces" node, but a way to put that grayscale value into the height input in needed.), n the result should look like :

![ssbld](https://user-images.githubusercontent.com/82643165/115048702-a78dcc80-9efb-11eb-9e27-60f931904fdc.png)

**Comment by nafik001** [comment]
> Baking the texture would allow you to use Texture Evaluate or Texture field nodes, it would loose the "live" connection but may be the only way to go

The "Live connection" is the main think I would Like to have, and I believe this will really create some new possibilities, especially for beginners.

**Comment by Durman** [comment]
How a mesh should be subdivided for example for the such texture?
![2021-04-17_17-23-22](https://user-images.githubusercontent.com/28003269/115114687-a1eac200-9fa1-11eb-8dad-80a08a3beaf0.png)

**Comment by nafik001** [comment]
> How a mesh should be subdivided for example for the such texture?
> ![2021-04-17_17-23-22](https://user-images.githubusercontent.com/28003269/115114687-a1eac200-9fa1-11eb-8dad-80a08a3beaf0.png)

For this kind of texture, It should just show an error.(in other word, just output the mesh provided by input)

The node should work like following:
  If the texture contains parts of a certain color(not a gradient ,a solid color), then it will make the regions with same color separate.
  else if , the texture contains gradient , or some abstract design like yours, It will just do nothing.(because actually, nothing can be done here, The algorithm should be straightforward,  Just separate parts with same color and output just like the "voronoi to mesh" node does.) 
And, If the texture is 2d, it will work on 2d object, if 3d or 4d, it will work on any object.(2d textures can be projected on 3d objects, and that will give something similar to first applying the texture to a 2d object and then extruding it, But that is for later.)

**Comment by nafik001** [comment]
> How a mesh should be subdivided for example for the such texture?
> ![2021-04-17_17-23-22](https://user-images.githubusercontent.com/28003269/115114687-a1eac200-9fa1-11eb-8dad-80a08a3beaf0.png)

And though there are many really interesting textures, The main thing is to Assign The color value of the texture to corresponding part of the divided mesh,(as vertex color ...a good option I guess??).
If it is possible, there are some really good animation possibilities, I believe.

**Comment by Durman** [comment]
Your algorithm reminds me the marching squares one. https://en.wikipedia.org/wiki/Marching_squares

I see two problems here. It wont be possible to implement it woking in real time upon changes in the sheader editor because I don't think that Blender Python API can give enough information from a shader. Solution can be backing a texture.

The second problem will be performance. It's senseless to implement this on Python it should be another faster language or library with required functionality but even then I think it will work only with low resolution of a texture.

In general I don't believe that your suggestion can be implemented, only partly.

**Comment by nafik001** [comment]
> Your algorithm reminds me the marching squares one. https://en.wikipedia.org/wiki/Marching_squares
> 
> I see two problems here. It wont be possible to implement it woking in real time upon changes in the sheader editor because I don't think that Blender Python API can give enough information from a shader. Solution can be backing a texture.
> 
> The second problem will be performance. It's senseless to implement this on Python it should be another faster language or library with required functionality but even then I think it will work only with low resolution of a texture.
> 
> In general I don't believe that your suggestion can be implemented, only partly.

Frankly speaking, I don't know about coding that much, But as far as I understand,
The first problem is realtime information transfer. Umm, for that ,We can just implement this just for 2d planes...I mean ,for 2d objects, I don't think this will be that hard, Because it just have to cut the plane where two different colors meets and creates an edge...And lets do just simple textures, which are not too complex and Have CLEAR EDGES where to cut.

Secondly, the performance issue. As I said I don't know about coding that much, I cant really help you with that, But isn't the "Voronoi to Mesh" node doing that..? In 3d ?? So, for only 2d objects and simple 2d textures...It will be great if you can somehow make that work...

And moreover, the more important thing is to assign the color of the texture as a value to corresponding faces...If that is possible somehow, It will definitely create a new world of animating with sverchok. (and will fix simple problems like issue #4055 )

You guys surely know better than me, But I think it will be really helpful if you can implement this (even if only for a plane, it will be great.)..   :-)

**Comment by nafik001** [comment]
> Your algorithm reminds me the marching squares one. https://en.wikipedia.org/wiki/Marching_squares
> 
> I see two problems here. It wont be possible to implement it woking in real time upon changes in the sheader editor because I don't think that Blender Python API can give enough information from a shader. Solution can be backing a texture.
> 
> The second problem will be performance. It's senseless to implement this on Python it should be another faster language or library with required functionality but even then I think it will work only with low resolution of a texture.
> 
> In general I don't believe that your suggestion can be implemented, only partly.

You definitely know how creative people can get with just some simple node setups, and converting that to real geometry...really makes me excited. I can imagine , a lots of cool stuff can be created just like [this one](https://www.youtube.com/watch?v=_bdcQXMQ4e0), in Real Geometry!! moreover, assigning same color value to each face, will also create some new possibilities.

The node just has to do 3 simple things,
1. read the shader texture.
2. Cut a plane where there two colors are meeting ,in that texture .
3. assign the color value of the texture to corresponding faces.

Seeing the possibilities, I don't think the idea is not that bad... Why not give it a try??

**Comment by Durman** [comment]
Looks like this fits better to what you want to achieve - https://en.wikipedia.org/wiki/Image_tracing

I'm not so exited about the idea. I don't see use case of it in procedural modeling. In your video example the same can be done without tracing any textures. I saw some examples in Twitter that were done in Sverchok.

**Comment by nafik001** [comment]
> Looks like this fits better to what you want to achieve - https://en.wikipedia.org/wiki/Image_tracing
> 
> I'm not so exited about the idea. I don't see use case of it in procedural modeling. In your video example the same can be done without tracing any textures. I saw some examples in Twitter that were done in Sverchok.

Yeah..the video example can be done in sverchok easily, But how can I show you an example of that node, If the node doesn't exists yet, (lol), the video was to show simple but cool shader texture 
Hmm, if you are not excited, I cant do anything. But then only solve the issue #4055 ,I am okay with that.
(look ,frankly, that is a very basic problem...I am creating a Voronoi animation ,but I cant find a way to color each of the voronoi cells consistantly, It always changes if I change the frame. That should have a solution...)

And yeah, no matter what you say, I think shader textures are more flexible and beginner friendly than creating the same thing in geometry in sverchok (I hope you agree that too),...so I  will humbly request you , At least talk with some people about this idea, get some review, and then...You guys know better... :-)

**Comment by nafik001** [comment]
> Looks like this fits better to what you want to achieve - https://en.wikipedia.org/wiki/Image_tracing
> 
> I'm not so exited about the idea. I don't see use case of it in procedural modeling. In your video example the same can be done without tracing any textures. I saw some examples in Twitter that were done in Sverchok.

One more thing I think I should mention, That the node I want is basically an updated version of the "voronoi to mesh" node (maybe it works on different algorithm, but the core concept is same), And the voronoi to mesh node is there, so an updated more powerful version of that...I don't see a reason for it to not being implemented...
Hope that you consider that too...I mean, It's a more flexible version of a node that already exists...!!!(and only for 2d objects, implementation will not be that hard, will it???)

**Comment by Durman** [comment]
This topic is free to read and write for all other developers so anyone interested can participate in the discussion. Also there is Sverchok discord chanel but for such discussions Github is better, I think.

For your information, a shader is simply a function which define what color should have an object. The color depends on many factors like camera position, lights, environment, mesh normals and orientation, probability etc. During a render a shader function is being called separately for each pixel of an output image. (The description can be not 100 % correct but in general this is how things work)

So you can see that shader is not a texture neither it can produce any mesh data.

**Comment by nafik001** [comment]
> This topic is free to read and write for all other developers so anyone interested can participate in the discussion. Also there is Sverchok discord chanel but for such discussions Github is better, I think.
> 
> For your information, a shader is simply a function which define what color should have an object. The color depends on many factors like camera position, lights, environment, mesh normals and orientation, probability etc. During a render a shader function is being called separately for each pixel of an output image. (The description can be not 100 % correct but in general this is how things work)
> 
> So you can see that shader is not a texture neither it can produce any mesh data.

You are right, But aren't we dealing with just color, Instead of using the Principled BSDF output, we should use only the RGB value of the serface, like say output of the combine HSV node.(I mensioned this in the problem statement, that we need a texture input node of shader editor, Which will have:
 a input socket taking a color value as input(eg. output of a checker texture)
 No output socket
A text input field, where the user will type a name associated to that texture.(as there can be multiple textures in use..this is for differenciate that)

secondly, A texture input node in sverchok, which will no input, will have a field where user can select which texture to use, and a output socket which will provide the texture. [ these to nodes will act like a bridge between shader editor and sverchok nodes]

****now the main part, how the main "texture to mesh" node will work...:**
**firstly , It will take the texture from the second node mentioned above, And assign the base color ,As a scalar field  I guess (I dont understand those things that good, plz understand the concept)...so ,It will create a scalar field of which ,each point will represent  the color value of the texture.****

will detect the places where the value of the field changes, and make a cut there.(and if there is 
continuous change, like a gradient ,it will just ignore that.
I don't think the cutting part will be that hard, but detecting can be a trouble. But we are using textures in displacement mordifiers, and as it will convert the value into a scalar field, You guys can figure a way out.
Then , assign the value of the generate scalar field to corresponding part of the plane, which is not a big deal...It will just do that.

**Comment by zeffii** [comment]
why do you need to create a Mesh for the animation?

have you seen `Nodevember` ?  https://twitter.com/search?q=%23nodevember2020&src=typed_query&f=image

**Comment by nafik001** [comment]
> why do you need to create a Mesh for the animation?
> 
> have you seen `Nodevember` ? https://twitter.com/search?q=%23nodevember2020&src=typed_query&f=image

Umm, It's just a idea that came into my mind, that it will be great to have a node, which is basically a upgraded version of the Voronoi to Mesh...And the animation part..The value assigned to each face, That's the thing which will be mainly used for animation... 
Yeah ...I am still a beginner and wanted to share my thought...The voronoi to mesh is there...so why not have a node which does the same, but way more flexible.
and I agree, if i can make 100 things with that, apx. 75 of them can be created by sverchok..bt my thought was that this node will make things easier...
(asking for permission to close the issue)

[...One more thing ,I want to let you guys know that...The thing you guys are doing is really cool...I mean ..procedurally created geometry...enough for making me excited...!! I really appreciate what you guys are doing...and thank you so much for your time..😊😊😊...]

**Comment by zeffii** [comment]
the shader tree is a "wrapper" that lets us define a shader function without writing a single line of code. The shader function is compiled after the tree structure is checked for validity and is offloaded to the CPU or GPU to be executed, there is no "exit" from that execution. Like a blackhole, nothing escapes it.  Nothing comes back, only pixel RGBA are calculated and placed inside the blackhole. 

This is why "baking" to texture was suggested, it's halfway between what you want and what is possible. It's a limitation of the chosen technology, but that's not to say that the technology is limited - as evidenced by the many hundreds of mind blowing entries to Nodevember (both 2019 and 2020). 

I'm sure you'll see that a lot can be achieved 100% inside a shader,, based entirely on a cube or sphere or even a plane. No modelling or sverchok required. Sverchok exists for a reason and I think you're only scratching the surface of what it _can_ do :)

keep at it.

**Comment by zeffii** [comment]
there are Python libraries that make it possible to offload computation onto GPU (and get the results back), and that would be really cool for heavy computational demands. Blender's shader implementation would still be separate from that functionality tho.

**Comment by nafik001** [comment]
Thanks again for your time ...
closing the issue. :)
