### ISSUE TITLE
"To control panel" for "Bezier in" and "NURBS in" questionable focus function

### ISSUE THREAD

**Issue by maxim1967** [nortikin/sverchok#4054]
## Problem statement

Alas, but so far only the main idea has been implemented.

1) Attempt with focus doesn't work. There is no reaction to pressing it.

2) "NURBS in" lost the second "Geomdl"method. This problem is relevant for Blender 2.93
![Снимок](https://user-images.githubusercontent.com/62519357/115103515-1b12f680-9f5b-11eb-8c1b-3b75acd7feee.JPG)
![Снимок1](https://user-images.githubusercontent.com/62519357/115103518-1fd7aa80-9f5b-11eb-9bdb-c8b0e308c198.JPG)

Tested in Blender 2.91.2, 2.92 and 2.93

**Comment by zeffii** [comment]
1.  focus, for now only selects the node in question and centers a nodeview on that node.
     
![showsworkingGIF 4-17-2021 9-48-35 AM](https://user-images.githubusercontent.com/619340/115105957-3c2b1580-9f62-11eb-9282-ba70529a16d8.gif)

2.  you will need to have geomdl installed, for that option to appear in the dropdown.  Nothing i modified would interfere with that.

**Comment by zeffii** [comment]
but the assertion that the NodeLocator doesn't work does bother me, can anyone else confirm?

for now i can only ask questions..
1. have you tried with a nodetree name that doesn't use Cyrillic characters ( just as an experiment..)

**Comment by zeffii** [comment]
as a side note:  In a recent Blender 2.9.3 nightly build, NURBS was broken (it was 2d only), so make sure are using a most recent 2.93 from https://builder.blender.org/download/

**Comment by maxim1967** [comment]
With NURBS, the question disappears, the "Geomdl" library was not installed"

**Comment by maxim1967** [comment]
I have no 3D Panel displayed at all in the Sverchok workspace.
![Снимок3](https://user-images.githubusercontent.com/62519357/115107375-3853bf00-9f73-11eb-8f78-1a2593e4d1f5.JPG)

It is only available in the 3D Viewer workspace and it is located in another tab,"Modeling".
![Снимок4](https://user-images.githubusercontent.com/62519357/115107383-40abfa00-9f73-11eb-958e-bdbc906d8fcc.JPG)

**Comment by zeffii** [comment]
my screenshot seems to have confused you, the panels are appearing in the correct spots. This is not a problem.

**Comment by maxim1967** [comment]
The problem is that the Sverchok workspace and 3D Viewer are in different tabs, and your focus works if both spaces are in the same tab. But this is quite justified if you have a monitor of at least 30 inches. And so you have to use two different tabs for comfortable work. I suggested adding the "To Control Panel" button because it would be possible to add newly constructed Curves and NURBS curves from the Modeling tab ( 3D Viewer).

**Comment by maxim1967** [comment]
And so the function is interesting but actually useless, if it could also switch between tabs, then it would be super!!!

**Comment by maxim1967** [comment]
**zeffii** I want to say that I admire you as a programmer, you still implemented the focus function, although some here doubted it!!! And thank you very much for the work done to implement my proposals.

**Comment by zeffii** [comment]
i don't know what you mean by "to control panel", the code that displays the list of Sverchok control parameters is displayed in both the 3dview N panel (sverchok sub panel), and the Properties View first panel at the bottom also called "Sverchok". The same menu is displayed in 2 places.

As for the focussing, i also tried this in 3dview sverchok panel, and it did focus the node.

I think you are saying that if there is no visible nodeview window open, that then the button doesn't do anything .  This is correct, it's working as specified. We can subdivide an existing window and display the related nodetree in that.. i'd be happy to implement, we do something similat to show the node documentation internally in the TextEditor (it opens a new text editor if none is available)

**Comment by maxim1967** [comment]
3d view Panel (Sverchok subpanel) here the buttons appear, 
![Снимок](https://user-images.githubusercontent.com/62519357/115112388-f97f3280-9f8d-11eb-8d3d-ed29e4822dd2.JPG)
but in Properties View "Sverchok" they are not.
![Снимок1](https://user-images.githubusercontent.com/62519357/115112398-04d25e00-9f8e-11eb-811c-841f620454b6.JPG)
The Properties View "Sverchok" only displays a list of trees but not their contents so these are completely different panels!

**Comment by zeffii** [comment]
> The Properties View "Sverchok" only displays a list of trees but not their contents so these are completely different panels!

OK, yes, i see. I had not considered adding the feature to that panel (Nodeview N panel, "Tree properties" tab.)

**Comment by maxim1967** [comment]
> I think you are saying that if there is no visible nodeview window open, that then the button doesn't do anything . This is correct, it's working as specified. We can subdivide an existing window and display the related nodetree in that.. i'd be happy to implement, we do something similar to show the node documentation internally in the TextEditor (it opens a new text editor if none is available)

Yes that's what I'm talking about

**Comment by zeffii** [comment]
i think rather than making a separate button to "add to properties panel"  ( which you called Control Panel )... i think it might make more sense to rename the button from "to 3d view" to "to properties panels" (which would add just a call to draw the properties in all 3 locations..)

**Comment by zeffii** [comment]
what do @nortikin @vicdoval @Durman @portnov  think ?

**Comment by maxim1967** [comment]
In general, the idea of focusing on a node is very interesting, but I would implement it in a different context. create a pop-up menu with a list (by name) of open nodes and add this focus function for each node. this was very convenient when a large proet called this menu and opened it to the node you need.

**Comment by zeffii** [comment]
in NodeView you can do ctrl+F , and search by name, it will select the node, but you still have to press `. ` (period) to center the nodeview on that node.

**Comment by maxim1967** [comment]
Your focus is more convenient, it not only highlights the desired node, but also centers it. 
> в NodeView вы можете сделать ctrl+F и поиск по имени , он выберет узел, но вы все равно должны нажать `. `(точка), чтобы центрировать nodeview на этом узле.
And here, if necessary, it is located within the window, it is only highlighted but not centered. It is centered only if it is not in the field of view.

**Comment by Durman** [comment]
@zeffii Do you mean adding of node properties (with pressed on `to 3d` option) to the `tree properties` panel?

**Comment by zeffii** [comment]
@Durman   yes .  maybe it's getting too busy?

**Comment by Durman** [comment]
If node properties will be hidden by default then there will be no difference. Also in this case I think the `Tree properties` panel should switch to using of code of 3d panel but the last one shows properties of trees only if at least one of its nodes have active `show in 3d` property, so this should be fixed to show always.

**Comment by nortikin** [comment]
> in NodeView  ctrl+F  search by name, press `. `

+100500
