### ISSUE TITLE
How can I get same vertex color to a face consistantly..???

### ISSUE THREAD

**Issue by nafik001** [nortikin/sverchok#4055]
## Problem statement
so, I am dealing with an animating voronoi mesh, and I want to assign vertex color to each face randomly. But when animating, The poly count of the mesh changes, and the vertext color of same face changes frame to frame.

![Screenshot 2021-04-17 140201](https://user-images.githubusercontent.com/82643165/115106395-68588d80-9f86-11eb-87fe-9c0995e100a8.png)

So how can I assign a color to each face in such a way, that the same face gets same color frame to frame.
## Steps to reproduce
[screenshot attached above]

## Expected result

I know the voronoi to mesh node is creating a new mesh each frame, But as I am using the same noise to genarate the color, It should be same each frame. 

## Actual result

Dont know why, but the color of same face is changing when the poly count change. Most probably its a indexing issue, But how can I avoid it and get Same color on Each face frame to frame..???

**Comment by Durman** [comment]
I think the `Vector noise` node changes output coordinates what make change of the colors as well.

**Comment by nafik001** [comment]
> I think the `Vector noise` node changes output coordinates what make change of the colors as well.

Yes ,but you play the animation, the voronoi cells are animated really smoothly.
This is just a simple demo I made to highlight the issue...


look this simple setup:

![169517517_1774191702762899_6464753608834890009_n](https://user-images.githubusercontent.com/82643165/115116495-90aeaf00-9fbb-11eb-851a-88323c633fd4.jpg)
(image from a project of Sebastian Jakoby)

The animation it creates is really satisfying, But the sad part is there's no way(as far as I know) to color "Each Cell" differently... :-(
But this thing is really simple, and there should be a way, isn't it??
But how..?? that is the question.

**Comment by zeffii** [comment]
there's a `point_region` in scipy.spatial Voronoi function, which may be of interest.

>  point_region | (list of ints, shape (npoints)) Index of the Voronoi region for each input point. If qhull option “Qc” was not specified, the list will contain -1 for points that are not associated with a Voronoi region.

https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.spatial.Voronoi.html

sverchok doesn't fully implement the Voronoi function i think.. @portnov  ?

**Comment by nafik001** [comment]
> there's a `point_region` in scipy.spatial Voronoi function, which may be of interest.
> 
> property	explanation
> point_region	(list of ints, shape (npoints)) Index of the Voronoi region for each input point. If qhull option “Qc” was not specified, the list will contain -1 for points that are not associated with a Voronoi region.
> https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.spatial.Voronoi.html
> 
> sverchok doesn't fully implement the Voronoi function i think.. @portnov ?

But This sorts of thing will be really easy, if some new nodes are implemented.(issue #4051)
If there is a way to connect shader texture to sverchok, we can use the new node instead of the "voronoi to mesh", so we can get   same vertex color for all frames, and use that in material so that we can color each cell with same color consistantly.

(really sorry to make this a separate issue, but i thought this problem can be solved differently...But as it seems where is no way, i am reffering the other issue,(#4051 ))

**Comment by Durman** [comment]
@nafik001 On the second example I don't see how you tried to color the cells so it's difficult to say what goes wrong. One of the possible problems could be that the `Voronoi on mesh` node outputs the cell objects in arbitrary order. Can you confirm this?

**Comment by zeffii** [comment]
certain input points are rejected by the voronoi algorithm (and thus have no corresponding polygon shape as an output), if the node outputted `point_region`, at least some continuity would be possible.

**Comment by nafik001** [comment]
> @nafik001 On the second example I don't see how you tried to color the cells so it's difficult to say what goes wrong. One of the possible problems could be that the `Voronoi on mesh` node outputs the cell objects in arbitrary order. Can you confirm this?

Actually the thing I did is almost similar to the first shading example. (and the problem is with the first example. The second one is just a idea, about what can be done if the first problem is solved.)
I didn't find any way to color the cells in such a way, that the color of same cell will not change frame by frame, And this issue is solved if you can find a way to color the cells in such a way that the color of each face don't change if I change frame (in the first example).

**Comment by Durman** [comment]
It's difficult to suggest anything about how the node tree could be improved without knowing particular reason of the problem. If you share your first tree probably some one have a look at it.

**Comment by nafik001** [comment]
> It's difficult to suggest anything about how the node tree could be improved without knowing particular reason of the problem. If you share your first tree probably some one have a look at it.

My first node tree is already shared. I suggest you do the same sverchok node tree on your pc,(ignore the shader tree and the vertex color mk3 node) , and play the animation ,if everything is okay, it will create a animation of which voronoi cells are animating really smoothly.
Now try to come up with a way to randomly color each cell, in such a way that a single voronoi cell gets same color for all frames(from its created to its disapears.).
I will be really grateful if you do.(I went to some people and nobody could do that..saying they dont know if a way to do that exists or not. :-(  )

**Comment by nafik001** [comment]
here is a better view of the node...

![nodes](https://user-images.githubusercontent.com/82643165/115136214-399eed80-a040-11eb-9296-fb208986ab25.png)

Create the same node tree in your pc, then find a way to color each cell randomly...in such a way that the color of same cell doesn't change if you change frame...
(really simple problem...isn't it?? find a way and the issue is solved.!)

**Comment by Durman** [comment]
What you tring to achieve is already possible in Sverhok. Check this video for example https://www.youtube.com/watch?v=Lf4t4Ks44Ek

If you will share your problem file you save time of others who will try to help you.

**Comment by nafik001** [comment]
> What you tring to achieve is already possible in Sverhok. Check this video for example https://www.youtube.com/watch?v=Lf4t4Ks44Ek
> 
> If you will share your problem file you save time of others who will try to help you.

Ahhh, Thats a solid node setup, I have to say...
But yeah, the issue is solved then...And I will definitely keep your advice in mind. :-)
Closing the issue.
