### ISSUE TITLE
Masking and matching

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#4057]
Lets say you have a node that includes a mask between the inputs.
with this inputs:
A 5 scalars [0, 1, 2, 3, 4] 
B 3 scalars [0, 1, 2]
C 5 boolean [T, F, T, F, T]
the node does:
` A + B if C else A `

If the node performs the masking after matching lengths the result would be [0,1,4,3,6]
If does the masking before matching lengths the result would be [0,1,3,3,6]

Masking before matching is usually faster.
But matching all lengths at the beginning of the execution seems more consistent.

What do you think should be the default node behaviour? @zeffii @nortikin @Durman @portnov

**Comment by portnov** [comment]
IMHO, it should do masking after matching. This behaviour seems more predictable to me.

**Comment by nortikin** [comment]
not sure i understand where 3 is came from. but masking seems to be needed.

**Comment by zeffii** [comment]
would matching first potential confer a computational benefit?

**Comment by Durman** [comment]
Actually I don't understand how masking before match concept works.

As to me it looks like a joke. ))

*Why does your program give incorrect output? 
Because otherwise it would work too slow.*

**Comment by vicdoval** [comment]
I'm coding a numpy version of inset special node

Masking after matching looks like this:
```
faces_to_inset = np_faces[mask]
matched_inset_rate = numpy_full_list(inset_rate, len(np_faces))[mask]
```

Masking before matching would be:
```
faces_to_inset = np_faces[mask]
matched_inset_rate = numpy_full_list(inset_rate, len(faces_to_inset))
```
In the first case it generates a longer list first to mask it later.
In the second case the list will only be expanded to what it is needed but from your comments seems to be more confusing...

**Comment by vicdoval** [comment]
One middle way could be:
```
if len(faces) == len(inset_rate):
    matched_inset_rate= inset_rate[mask]
else:
    matched_inset_rate = numpy_full_list(inset_rate, len(faces_to_inset))
```

**Comment by nortikin** [comment]
Is it question of to mask or not to mask inset rate? if so, maybe left choise to user? by default not masking

**Comment by vicdoval** [comment]
Thank you all for your thoughts 👍

**Comment by nortikin** [comment]
> Thank you all for your thoughts 👍

thank you! You are rgeat developer, Victor.

**Comment by vicdoval** [comment]
Thanks @nortikin your words are very appreciated :)
