### ISSUE TITLE
Duplicate along Edge Improvements

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4062]
Hi, is it possible to add Offset and Rotation parameters? For example, I want to make a chain. I need to offset every element and rotate to 90 degrees. 
My file:
[tmp1.zip](https://github.com/nortikin/sverchok/files/6358530/tmp1.zip)

![image](https://user-images.githubusercontent.com/2251298/115720953-3714fe80-a386-11eb-91e2-626bf8f1cec1.png)

**Comment by nortikin** [comment]
https://gist.github.com/b33e319349824ae0ac82c6d874d38c1a
![image](https://user-images.githubusercontent.com/5783432/115725099-37af9400-a38a-11eb-903c-cc87916f92e0.png)

**Comment by Durman** [comment]
Your choice of the node is node best. With curves it does not work as one could expect. Here is another solution for you.

[untitled.zip](https://github.com/nortikin/sverchok/files/6359199/untitled.zip)
![2021-04-22_18-47-00](https://user-images.githubusercontent.com/28003269/115735220-5c603780-a39b-11eb-9051-0c53cef56496.png)

**Comment by mifth** [comment]
Thank you. Could it be just 2-3 nodes solution? It would be nice to have all this in Duplicate along Edge as an option.
Or I ask too much? )

**Comment by Durman** [comment]
Like this?))
![2021-04-22_19-38-29](https://user-images.githubusercontent.com/28003269/115743056-5ae63d80-a3a2-11eb-8a58-2aee8629bd2a.png)

<details> 
  <summary>actual node tree</summary>  

![2021-04-22_19-34-17](https://user-images.githubusercontent.com/28003269/115743101-68032c80-a3a2-11eb-9d5c-5eec266d3e0f.png)


</details>

**Comment by mifth** [comment]
Yeah
