### ISSUE TITLE
Is there a way to install ( pygalmesh ) 

### ISSUE THREAD

**Issue by AnasFX** [nortikin/sverchok#4063]
## Problem statement

Is there a way to install ( pygalmesh ) ? , there is no ( install through pip ) option, and when I try to install it manually through Blender python console I have this error : 
Building wheels for collected packages: pygalmesh
  Building wheel for pygalmesh (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
. 
.
.
Failed to build pygalmesh
ERROR: Could not build wheels for pygalmesh which use PEP 517 and cannot be installed directly

## Sverchok version

latest version with update.

**Comment by Acanterelle** [comment]
hey, Im fairly new to python/conda etc but came across this earlier. Ive been trying to get 2.92 to work with conda through PATH etc and it's been driving me nuts... if you get this to work please give me a shout as to what you did :) 

conda install -c conda-forge pygalmesh

https://anaconda.org/conda-forge/pygalmesh

**Comment by maxim1967** [comment]
To install pygalmesh, you first need to install Visual C++ 14.0, then install it via the pygalmesh console: pip install-U pygalmesh

**Comment by Sinasta** [comment]
is there a way to install pygalmesh without Visual C++. I'am on linux Arch and Visual C++ isnt available

**Comment by maxim1967** [comment]
Instructions for installing in Linux https://github.com/nschloe/pygalmesh#installation
