### ISSUE TITLE
Stack and Align objects

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4066]
<img width="786" alt="Screen Shot 2021-04-30 at 12 49 21 pm" src="https://user-images.githubusercontent.com/3952687/116642576-912f4880-a9b2-11eb-8162-b9258692377e.png">
[sv_stackingOBJ_005.blend.zip](https://github.com/nortikin/sverchok/files/6402747/sv_stackingOBJ_005.blend.zip)
<img width="1002" alt="Screen Shot 2021-04-30 at 12 49 11 pm" src="https://user-images.githubusercontent.com/3952687/116642585-968c9300-a9b2-11eb-8234-c4c55453c989.png">

I am trying to stack and align objects in the list simply by using it's bounding box and then numpy accum() the size. Somehow, it does not work as expected. Any idea?

Also I tried to use Align Node, but for many objects, and loop, but it feels a bit complicated...

**Comment by Durman** [comment]
Have a look at this file. I did it when was testing node group implementation.

![2021-04-30_08-24-11](https://user-images.githubusercontent.com/28003269/116648199-82826a80-a98d-11eb-98dd-4b1f71c44b4c.png)

[Relative array group.zip](https://github.com/nortikin/sverchok/files/6402979/Relative.array.group.zip)

**Comment by enzyme69** [comment]
Thanks Durman, I'll check cheers!

**Comment by enzyme69** [comment]
* My Mistake was not to add zero, before accum.
