### ISSUE TITLE
Question about  Simple Deform 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#4072]
if i change the Angle to negativie the v shape ( bevel )  is flipped is there a way to avoid this : 
![image](https://user-images.githubusercontent.com/49908008/116857737-946a4480-abfd-11eb-8cd8-f5ab20f1500e.png)

**Comment by vicdoval** [comment]
Maybe using two bevel objects, one pointing down and one pointing up

**Comment by BennyGovaerts** [comment]
What happens if you use a noise , then the vshape - bevel  is sometimes flipped in another direction etc ....

**Comment by BennyGovaerts** [comment]
Ok, i have a solution for some reason it works only if i use the default settings from the simple deform node

**Comment by enzyme69** [comment]
I think Simply Deform node is very hard to use. I wonder if there is alternative and more controlled deform bend by curve.

**Comment by Durman** [comment]
@enzyme69 Maybe `Bend object along path` node?

**Comment by BennyGovaerts** [comment]
At the moment i have used the default settings & rotated the leaf with GeometryNodes ( Thanks for the feedback )
![image](https://user-images.githubusercontent.com/49908008/116999511-ff8c4780-acdf-11eb-9b92-52b46b10c5ac.png)
