### ISSUE TITLE
Activating Sverchok crashes Blender

### ISSUE THREAD

**Issue by alexsincai** [nortikin/sverchok#4073]
I'm on Ubuntu (`Linux ****** 5.8.0-52-generic #59-Ubuntu SMP Fri Apr 30 13:02:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`) on a Lenovo E490, running Blender 2.92.0

After adding the latest version of Sverchok (v 0.6.0.0, master release), it shows up deactivated in the list of addons, but activating it crashes Blender. Running Blender from the command line only says `Aborted (core dumped)`

Any ideas on how to fix this?

**Comment by portnov** [comment]
Do you have FreeCad libraries installed / configured?
It is one possible cause of similar behaviour I know of, when you have FreeCad libraries installed and configured, but for python version different from blender's python...

**Comment by alexsincai** [comment]
I do not have FreeCad, but it's likely the Python version is the issue -- I've reinstalled Blender just after updating to Python 3.9.0

Could this be the issue? And if so, any idea how to solve it?

Thank you :)

**Comment by alexsincai** [comment]
After updating to Blender 2.93.0, this issue seems to have been resolved.
