### ISSUE TITLE
Impossible dependencies

### ISSUE THREAD

**Issue by JuanJ67m** [nortikin/sverchok#4082]
I tried install dependencies since 2 entire days ago "pygalmesh" and "FreeCAD.dll" in Windows 10

please, someone could do a guide to install both dependencies for Blender?

EDIT: also is not possible install open3D node

**Comment by rendetto** [comment]
For using FreeCAD you'll need Blender2.92 (or 2.93 but built with python3.7) combined with this FreeCAD build: https://yadi.sk/d/NhCrTKi3nIgTXA (nikitron provided the link here: https://github.com/nortikin/sverchok/issues/3780).

We are waiting for FreeCAD builds that use python3.9 in order to use the last Blender2.93 builds(which use py3.9 also).

You'll always need Python versions aligned in order to use FreeCAD+Blender/Sverchok.

**Comment by JuanJ67m** [comment]
we need a complete guide for depencencies because I found that does not exist "FreeCAD.dll" file requested for Sverchok and when I use a FreeCAD with py 3.7 for Blender 2.92.0 crash or blender do not open.

I tried an entire week install Pygalmesh in Windows 10 without luck, why this dependency is not included in the Sverchok-depencencies-Pack.zip for default with FreeCAD.dll if exist?

**Comment by rendetto** [comment]
I never used Pygalmesh, but I use the FreeCAD functionality from Sverchok on a daily basis.

If this could help:
1. Download the official Blender 2.92 and extract it (under win I'm using the zip version, not the installer).
2. Download the FreeCAD build from here https://yadi.sk/d/NhCrTKi3nIgTXA and also extract it.
3. Download the latest Sverchok master and extract it to the win user folder (C:\Users\....\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master). If the folder structure does not exist you need to create it manually.
4. Open Blender and enable Sverchok.
5. In the properties of the Sverchok addon click on the Extra Nodes button and scroll to the bottom until you find the "FreeCAD python 3.7 folder" input field. There you need to paste the full path to the FreeCAD bin folder e.g. D:\Software\FreeCAD_0.19.19697_x64_Conda_Py3QT5-WinVS2015\bin\
6. Close Blender then reopen it and you should find all the FreeCAD nodes under the Solids submenu. If the nodes are not there check if the pasted path (in the "FreeCAD python 3.7 folder" field) is set and correct.

Hope this helps
