### ISSUE TITLE
External objects loaded in Scripted Node Lite are missing modifiers

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#4087]
I'm importing various objects from external blender files using SNL,
works well, but I noticed modifiers from my imported objects are missing
Here is my code in SNL :

```python
"""
in seed s d=1 n=2

out p o
"""

import bpy
import os
import random
 
file_path = bpy.path.abspath("//objects.blend")
inner_path = 'Object'
parts = {0: 'Object_Prefix'}
p = [] 

for i, part in parts.items():
    #cleaning previously imported objects
    for obj in bpy.data.objects:
        if obj.name.startswith(part):
            bpy.data.objects.remove(obj)
    #filtering objects with the required prefix in the external file
    with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
        data_to.objects = [name for name in data_from.objects if name.startswith(part)]
    #loading randomly one of the filtered objects
    if data_to.objects is not None:
        obj = data_to.objects[random.randint(0, len(data_to.objects)-1)]
        p.append(obj)
    

 
```

**Comment by zeffii** [comment]
OK, but lets get it working with a single object first @mlevet  , because that's solving the core of your problem.

**Comment by zeffii** [comment]
and because add an `obj` to the scene + collection generates a dependency graph update causes sverchok's nodetree to be recalculated, you can bypass the recalculation by enclosing the code in a `throttle` context.

`bpy` is already passed into the script automatically.

```python
"""
in seed s d=1 n=2
out p o
"""

import os
import random

from sverchok.node_tree import throttle_tree_update

 
file_path = bpy.path.abspath(r"D:\\objects.blend")
part = "Cube"

with throttle_tree_update(self):
    #cleaning previously imported objects
    for obj in bpy.data.objects:
        if obj.name.startswith(part): 
            bpy.data.objects.remove(obj)
            obj.hide_select = False
            bpy.context.scene.collection.objects.unlink(obj)

    #filtering objects with the required prefix in the external file
    with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
        data_to.objects = [name for name in data_from.objects if name.startswith(part)]

    #loading randomly one of the filtered objects
    if data_to.objects is not None:
        obj = data_to.objects[random.randint(0, len(data_to.objects)-1)]
        bpy.context.scene.collection.objects.link(obj)
        p.append(obj)
```

**Comment by zeffii** [comment]
now when i slide around the seed value, it causes the node to update and every second seed value 0..2..4...6 it will show the object (cube) + modifiers.  Why ?  is because of the code logic inside the throttle section, but I think you can figure that out.

**Comment by zeffii** [comment]
is `objects.blend`  a different `.blend`  than where you are executing the script from?

**Comment by zeffii** [comment]
except for the automatical injection of variables, `bpy` and a few other things, executing scripts from within ScriptNodeLive is very similar to executing them from inside something like a scripted driver or [event callback.](https://docs.blender.org/api/2.93/bpy.app.handlers.html?)

**Comment by zeffii** [comment]
if you want more help, best i can offer is that you make a demo zip.  with placeholder objects in several .blends . and the code you're trying to use now.  and a reasonably accurate description of the relationship between time/inputvariables and output.

preferably the simplest way you can think of demonstrating what you want, but showing that it's failing.

that way we (or I ) don't have to also make the demo files etcetc.  just solve the problem.

**Comment by zeffii** [comment]
best case scenario is that while making the demo.zip you will solve the problem, by the mere fact that you've reduced it to smaller parts.

**Comment by mlevet** [comment]
So I tried to figure out but no luck, so I prepared a demo file so you can have a look.
Problem is, for now there are two cubes on the scene, one with modifier and one without.
And the scaling is applied to the one without modifier
I would like to have only the cube with modifier on stage and then the scaling applied to that one.

https://drive.google.com/file/d/1381AyaBeDpNYJ_fd7Nz3TbzBVzy1mAgd/view?usp=sharing

```
"""
in seed s d=1 n=2

out p o
"""

import bpy
import os
import random

from sverchok.data_structure import throttle_tree_update
 
file_path = bpy.path.abspath("//cubetest.blend")

part = "Cube"

with throttle_tree_update(self):
    #cleaning previously imported objects
    for obj in bpy.data.objects:
        if obj.name.startswith(part): 
            bpy.data.objects.remove(obj)
            obj.hide_select = False
            bpy.context.scene.collection.objects.unlink(obj)

    #filtering objects with the required prefix in the external file
    with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
        data_to.objects = [name for name in data_from.objects if name.startswith(part)]

    #loading randomly one of the filtered objects
    if data_to.objects is not None:
        obj = data_to.objects[random.randint(0, len(data_to.objects)-1)]
        bpy.context.scene.collection.objects.link(obj)
        p.append(obj)

```

**Comment by zeffii** [comment]
but the cube you are importing does appear with the subdiv modifier, except its inside the large cube.

![image](https://user-images.githubusercontent.com/619340/117972050-f2e4a080-b32a-11eb-8fcf-6e0b324ac09f.png)

**Comment by zeffii** [comment]
because the thing you are importing has modifiers, you must use a different kind of node to get the mesh data, the Object ID Out node has a mode to take the modifiers into account.

![image](https://user-images.githubusercontent.com/619340/117972374-5a9aeb80-b32b-11eb-8b17-9925da2c95a7.png)

**Comment by zeffii** [comment]
but now i can see where the problem is : )

**Comment by zeffii** [comment]
i'm a little stumped so i'll do some more thinking out load.
- it's probably not useful to remove the same object you intend to import during the same frame change event.
     - maybe you never do that,
- you probably know in advance the pool of object names you want to select from
- maybe it makes sense to do the remove/unlink separately ( to keep the "import/get" code simple )

```python
"""
in seed s d=1 n=2
out p o
"""

import os
import random
from sverchok.data_structure import throttle_tree_update
 
file_path = bpy.path.abspath("//cubetest2.blend")

available_imports = ["Cube", "Cube.001", "Cube.002"]


def remove_other_objects(available_imports, part):
    with throttle_tree_update(self):
        for obj_name in available_imports:
            if obj_name in bpy.data.objects and obj_name != part:
                obj = bpy.data.objects.get(obj_name)
                bpy.data.objects.remove(obj)
                obj.hide_select = False
                bpy.context.scene.collection.objects.unlink(obj)    

def return_object(part):

    with throttle_tree_update(self):

        for obj in bpy.data.objects:
            if obj.name == part:
                return obj

        remove_other_objects(available_imports, part)
        
        #filtering objects with the required prefix in the external file
        with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
            data_to.objects = [name for name in data_from.objects if name == part]

        if data_to.objects:
            obj = data_to.objects[0]
            bpy.context.scene.collection.objects.link(obj)
            return obj


part = random.choice(available_imports)
obj = return_object(part)
p.append(obj)

```

unfortunately i don't think that's an improvement : /

**Comment by zeffii** [comment]
i'll keep thinking about it. unless someone else gives a working solution.

**Comment by zeffii** [comment]
one thing that is possible is to import all the objects first, and put them into a single collection, and then hide that collection.
This way our obj->mesh nodes can still get dependency graph data from the objects,, without them being visible.

![image](https://user-images.githubusercontent.com/619340/117984743-6345ee80-b338-11eb-8caf-96a4c15cd254.png)

**Comment by zeffii** [comment]
as a side note, i forgot that you can write
```python
with self.sv_throttle_tree_update():
    ... your throttled code ...
```
no need to import ` from sverchok.data_structure import throttle_tree_update `

**Comment by zeffii** [comment]
can you spot the bug?
```
                bpy.data.objects.remove(obj)
                obj.hide_select = False
```

**Comment by mlevet** [comment]
That should be the other way around, right ?

obj.hide_select = False

bpy.data.objects.remove(obj)

**Comment by zeffii** [comment]
OK.  yes . :)

here's one that does work. it's a little complicated, it might be possible to simplify this a lot.
```
"""
in seed s d=1 n=2
out p o
"""

import os
import random
 
file_path = bpy.path.abspath("//cubetest2.blend")
available_imports = ["CubeA", "CubeB", "CubeC"]

def remove_other_objects(removables):
    try:
        for obj_name in removables:
            obj = bpy.data.objects.get(obj_name)
            if obj:
                bpy.data.objects.remove(obj)
                bpy.context.scene.collection.objects.unlink(obj)    
    except:
        pass

def return_object(part, removables):
    remove_other_objects(removables)
    for obj in bpy.data.objects:
        if obj.name == part:
            return obj
    
    #filtering objects with the required prefix in the external file
    with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
        data_to.objects = [name for name in data_from.objects if name == part]

    if data_to.objects:
        obj = data_to.objects[0]
        bpy.context.scene.collection.objects.link(obj)
        return obj
    return None

with self.sv_throttle_tree_update():
    part = random.choice(available_imports)
    removables = [obj_name for obj_name in available_imports if obj_name != part]
    obj = return_object(part, removables)
    p.append(obj)


```

**Comment by zeffii** [comment]
[demo2.zip](https://github.com/nortikin/sverchok/files/6471330/demo2.zip)

but as soon as you attach a node to "decompose" the object into mesh data, it throws a few errors that i'm not sure are trivial to circumnavigate.

**Comment by zeffii** [comment]
but .. maybe it is, because to get the mesh representation of an object, if it has modifiers, we must call the dependency graph ,  let's seee.

**Comment by zeffii** [comment]
ah ha!
```python
"""
in seed s d=1 n=2
out p o
"""

import os
import random
 
file_path = bpy.path.abspath("//cubetest2.blend")
available_imports = ["CubeA", "CubeB", "CubeC"]

def remove_other_objects(removables):
    try:
        for obj_name in removables:
            obj = bpy.data.objects.get(obj_name)
            if obj:
                bpy.data.objects.remove(obj)
                bpy.context.scene.collection.objects.unlink(obj)    
    except:
        pass

def return_object(part, removables):
    remove_other_objects(removables)
    for obj in bpy.data.objects:
        if obj.name == part:
            return obj
    
    #filtering objects with the required prefix in the external file
    with bpy.data.libraries.load(file_path, link=False) as (data_from, data_to):
        data_to.objects = [name for name in data_from.objects if name == part]

    if data_to.objects:
        obj = data_to.objects[0]
        bpy.context.scene.collection.objects.link(obj)
        return obj
    return None

with self.sv_throttle_tree_update():
    part = random.choice(available_imports)
    removables = [obj_name for obj_name in available_imports if obj_name != part]
    obj = return_object(part, removables)
    bpy.context.evaluated_depsgraph_get()   # <----
    p.append(obj)


``` 
the call there to to evaluated_depspgraph_get()  , does  result in everything working.

**Comment by zeffii** [comment]
i'll be the first one to admit that that is an unsatisfying amount of code to accomplish this.

**Comment by mlevet** [comment]
Bit long indeed but that works great !
Here's the fully adapted version with objects imported into a hidden
collection

**Comment by zeffii** [comment]
hopefully you now get a sense of how to do this kind of stuff, there are certain parts to blender's API that are simply put "tricky to navigate due to mechanistic choices we made in Sverchok, but ultimately not impossible"

**Comment by gerroon** [comment]
@zeffii 

Is `Object ID Out MK2 ` node removed from the nightlies? I cant seem to find it.  Typing "object id" or "out mk2" does not bring anything in the search bar. I was just trying to set up like you had in these images.


> is `objects.blend` a different `.blend` than where you are executing the script from?
> 
> ![image](https://user-images.githubusercontent.com/619340/117871204-693ac180-b29d-11eb-946b-4d67f573e656.png)
> ![image](https://user-images.githubusercontent.com/619340/117871419-a56e2200-b29d-11eb-9c58-b5422e5c7d97.png)

**Comment by vicdoval** [comment]
'Objects In' and 'Object Id Out' where turned into 'Get Objects Data' node at #4091

**Comment by mlevet** [comment]
`with self.sv_throttle_tree_update():`
is now producing this error : 
NameError: name 'self' is not defined

I guess it's related to new update system ?
I just upgraded to blender 2.93 and sverchok last version.
