### ISSUE TITLE
Switcher problem

### ISSUE THREAD

**Issue by piotrkopiczynski** [nortikin/sverchok#4092]
Hi,
when i change the source data, Switcher do not refresh. It only remembers old data - out of bound. Reconect do not help. 
![01](https://user-images.githubusercontent.com/25440884/118354829-47775e00-b56d-11eb-9435-afea3b4028ef.jpg)
![02](https://user-images.githubusercontent.com/25440884/118354862-64139600-b56d-11eb-911c-44bbeece8903.jpg)

**Comment by zeffii** [comment]
maybe the elements that aren't visible anymore, after updating the range node, are still marked internally as selected?

**Comment by zeffii** [comment]
yep
![GIF 5-15-2021 11-55-53 AM](https://user-images.githubusercontent.com/619340/118356272-a55b7400-b574-11eb-981a-516354c24aaf.gif)

**Comment by zeffii** [comment]
@Durman   https://github.com/nortikin/sverchok/pull/4093  is OK?

**Comment by zeffii** [comment]
i can imagine a scenario where the user does not want to so easily "lose" the toggle states of previous user list states.

**Comment by zeffii** [comment]
that's updated @piotrkopiczynski
