### ISSUE TITLE
Toggle button for a temporal viewer

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4098]
Request for help/advice: To view a geometry in Topologic, we currently have a Topology.Geometry node that takes as input a Topology and outputs vertices, edges, and faces. This can then be CTRL-clicked or connected to a mesh viewer etc. We would like to:
1. Automate that process so that any node that has a topology output, can automatically create a blender geometry on-demand using our Topology.Geometry method.
2. Add a checkbox or toggle so that when it is clicked, the geometry appears, and when it is un-checked, the geometry disappears.

Is this possible? and if so, what is your advice on how to best achieve this using minimal code additions as I have approx. 140-150 nodes to update?

Thanks

**Comment by Durman** [comment]
I would suggest to have a look at the `sverchok\utils\nodes_mixins\generating_objects.py` module.

**Comment by wassimj** [comment]
> I would suggest to have a look at the `sverchok\utils\nodes_mixins\generating_objects.py` module.

Thank you, but I am afraid I need more guidance than just looking at the code. It will take me a long time to decipher what is being done in that node. I am also unsure if you are suggesting that I need to add that type of code in all 150 Topologic nodes?

**Comment by Durman** [comment]
I think you have to make your mix-in class than use it in all your 150 nodes.

In general implementation should looks like this

```py
class MyMixIn(BlenderObjects):
    mesh_data: bpy.props.Collection(bpy.types.SvMeshData)

    def gen_mesh(meshes):
        correct_collection_length(mesh_data, len(meshes))
        for me in meshes:
            me_data.regenerate_mesh(*me)

        self.regenerate_objects(meshes.names, [d.mesh for d in self.mesh_data], _)

class Node(MyMixIn):
    def process():
        gen_mesh(conver(self.inputs[0].sv_get()))
```

Also it can helpful to have a look at the Mesh viewer node code.

**Comment by vicdoval** [comment]
What I did for sverchok-open3d is 

in the node file `from sverchok_open3d.utils.triangle_mesh import triangle_mesh_viewer_map`
in the node class  `viewer_map = triangle_mesh_viewer_map`
in the utils file 

```
triangle_mesh_viewer_map = [
    ("SvO3TriangleMeshOutNode", [60, 0]),
    ("SvViewerDrawMk4", [60, 0]),
    ], [
    ([0, 0], [1, 0]),
    ([1, 0], [2, 0]),
    ([1, 1], [2, 1]),
    ([1, 2], [2, 2]),
    ]
```

explanation from viewer_map attribute from https://github.com/nortikin/sverchok/blob/ca65d1ff281e7f05d0e3e61e41facb5ba4e36237/ui/nodeview_rclick_menu.py#L110
'''
    viewer map is a node attribute to inform to the operator how to visualize the node data
    it is a list with two items.
    The first item is a list with tuples, every tuple need to have the node bl_idanme and offset to the previous node
    The second item is a list with tuples, every tuple indicates a link.
    The link is defined by two pairs of numbers, refering to output and input
    The first number of every pair indicates the node being 0 the active node 1 the first needed node and so on
    The second nmber of every pair indicates de socket index.

    So to say: create a Viewer Draw with a offset of 60,0 and connect the first output to the vertices input
    the node would need to have this:

        viewer_map = [
            ("SvViewerDrawMk4", [60, 0])
            ], [
            ([0, 0], [1, 0])
            ]

    '''


Adding this attribute to all nodes could be done via a MixIn Class, i added it individually to all the nodes outputing a Triangle Mesh.

With it all the Triangle Mesh Nodes create a Temporal Viewer when crtl-clicked.
