### ISSUE TITLE
Objects duplicated with Dupli Instancer mk4 disappearing when trying to join 

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#4110]
I have some duplicated spheres i want to join with a cube
The duplicated objects will just disappear when joining.
Is there a way to prevent them from disappearing ?
<img width="745" alt="Capture d’écran 2021-05-20 à 23 43 08" src="https://user-images.githubusercontent.com/17178730/119053007-bcabbe80-b9c5-11eb-9de3-2102d254ef70.png">
<img width="741" alt="Capture d’écran 2021-05-20 à 23 42 44" src="https://user-images.githubusercontent.com/17178730/119053020-c0d7dc00-b9c5-11eb-9846-977132be9dec.png">

**Comment by vicdoval** [comment]
The objects generated by the Dupli Instancer are not real objects

> To turn all duplicates into real objects, simply select the icosphere and Object ‣ Apply ‣ Make Duplicates Real, Ctrl-Shift-A. To make the icosphere and the tentacle a single object, make sure they are all selected and go to Object ‣ Join, Ctrl-J.

from http://builder.openhmd.net/blender-hmd-viewport-temp/editors/3dview/object/properties/duplication/dupliverts.html

**Comment by mlevet** [comment]
Thanks a lot,
it works like a charm
Would it make sense to have a script in SNL automating the Make Duplicates
Real coming out the viewer draw for example ?

**Comment by vicdoval** [comment]
If you need real objects you can use the `mesh viewer` or if you want independent instances you can use `Object Instancer` Node
