### ISSUE TITLE
md in terminal

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#4119]
found that tool:

https://gist.github.com/diegopacheco/754ad87f87a8e4bae35c4ebf1275e913

it can readme in terminal:
![изображение](https://user-images.githubusercontent.com/5783432/119242710-ed782900-bb68-11eb-9cf5-d9e32be81bcb.png)

**Comment by portnov** [comment]
Pandoc is, indeed, a powerful tool. It can also be used to convert between variety of formats. We can make PDFs or DOCXs from our docs, for example, if we want...
