### ISSUE TITLE
what is the last function that Sverchok executes after F8 is completed?

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4125]
i'm either too lazy, or too stupid ,  or both.  to figure this out.

reloading does a couple of things, the clearing of drawing callbacks is one of them. Which i think is probably the desired effect of an `f8`, but it would be sweet to have a point in sverchok reload code where we can prepare the state of sverchok. Like; do a general update of all node trees to retrigger all gl drawing.

otherwise, i'm tempted to include a macro for `F8` ( `"nuke python++"` is added to macro list)  which does a few things first before calling `bpy.ops.script.reload`

**Comment by Durman** [comment]
Should be this - `core.handlers.sv_post_load`

**Comment by zeffii** [comment]
right!  but if I add `bpy.ops.node.sverchok_update_all()` at the nd of that handler ( just to test ) , i would expect a general update and all bgl drawing to resume.  but it doesn't.

**Comment by Durman** [comment]
Indeed, during F8 reload the last function is `__init__.register`

**Comment by zeffii** [comment]
i'm beginning to recollect a few things. inside `__init__.register` there is no access to bpy.data.node_groups. 
```
'_RestrictData' object has no attribute 'node_groups'
```
would it make sense to ask b3d devs for a "post_script_reload" handler ?

**Comment by zeffii** [comment]
uch...this is too hacky.
