### ISSUE TITLE
Registration of old node classes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4133]
The code looks does not take into account that an opened file can have multiple node trees with different set of old nodes.

https://discord.com/channels/745273148018262158/806643543182802954/848061828012703794

https://github.com/nortikin/sverchok/blob/b6c0e36b21b1b4fe5a84ef0f9c22161b3556ad14/old_nodes/__init__.py#L83-L106

The function register all old node classes first and then unregister unused of them. 
My question is what purpose of unregistering of old node classes? It is definitely not going to make performance of the load even better. Probably @ly29 could help.

**Comment by zeffii** [comment]
if the node loaded isn't registered, it becomes undefined. i'm not sure there's a way to introspect (in a sane way) the bl_idnames of a nodetree beforehand.

something that might work is a nodegroup attribute that stores a comma separated string of all bl_idnames in each nodetree in a `pre_save` handler.

**Comment by zeffii** [comment]
it's unfortunate that if we load a .blend that contains a node that isn't registered, that the node can't be introspected other than `node.name`, but as soon as the missing node is registered then the undefined node becomes fully valid. So whatever memory-object is holding information about the node, it seems to me that it is still holding information about the `bl_idname` somewhere - just not exposed to the python API. 

Maybe  animation nodes handles this better?

**Comment by zeffii** [comment]
@jacqueslucke , @lukastoenne do you think it's possible to get a API call for undefined nodes to return the `bl_idname` of the missing node?

**Comment by JacquesLucke** [comment]
That is possible. Here is a simple test patch. I guess it's mostly a matter of finding a good name and description for the property. If you have a good idea, feel free to post this as a patch at https://developer.blender.org/.

```diff
diff --git a/source/blender/makesrna/intern/rna_nodetree.c b/source/blender/makesrna/intern/rna_nodetree.c
index f5cbb694554..b50827c6ec9 100644
--- a/source/blender/makesrna/intern/rna_nodetree.c
+++ b/source/blender/makesrna/intern/rna_nodetree.c
@@ -11188,6 +11188,11 @@ static void rna_def_node(BlenderRNA *brna)
   RNA_def_property_flag(prop, PROP_REGISTER);
   RNA_def_property_ui_text(prop, "ID Name", "");
 
+  prop = RNA_def_property(srna, "test_bl_idname", PROP_STRING, PROP_NONE);
+  RNA_def_property_string_sdna(prop, NULL, "idname");
+  RNA_def_property_flag(prop, PROP_REGISTER);
+  RNA_def_property_ui_text(prop, "ID Name", "");
+
   prop = RNA_def_property(srna, "bl_label", PROP_STRING, PROP_NONE);
   RNA_def_property_string_sdna(prop, NULL, "typeinfo->ui_name");
   RNA_def_property_flag(prop, PROP_REGISTER);
```

**Comment by ly29** [comment]
My gosh. Hard to believe that code is still in use.

**Comment by zeffii** [comment]
@ly29 don't fix what is not broken.

**Comment by zeffii** [comment]
that's great @JacquesLucke - many thanks for the insight!

**Comment by Durman** [comment]
I have suspicious that unregistering part of the old node classes does not have any sense. I know that in animation nodes there are no old nodes at all. New releases just change existent code of nodes without keeping back compatibility.

@JacquesLucke  Can you confirm that there is no any difference in an add-on work with 600 registered nodes or 800 or 1000?

**Comment by ly29** [comment]
Yeah. Backwards compatibility is hard and this is probably not totally sane. Some other approach is probably more clever. 
removing a node will always be breaking and perhaps encoding version in the node tree can give info about what version to use.

**Comment by ly29** [comment]
Considering semantic versioning, removing a node is always breaking. 

After seven years it probably is what is, and versioning was based on internal machinery more than usability which doesn’t makes sense.

**Comment by Durman** [comment]
The solution with registering of old nodes by request looks even more fragile because we have to throttle the first tree update called by Blender during loading a file.
