### ISSUE TITLE
automated test are failing (but showing they've passed)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4136]
Sverchok loads fine, but CLI tests have failed since https://github.com/nortikin/sverchok/commit/bcfe321ea6e0bc8b518e2435bc70006aa2966fa0 

it looks like the Blender 2.82 used in the automated test is from before 23 sept 2020 , when " OUTLINER_COLLECTION " was introduced.  https://github.com/blender/blender/commit/5a28090977d66d8e52d269fb5bb938d953191dde

or something else?

**Comment by zeffii** [comment]
it looks like the Blender 2.92 used in the automated test is from before 23 sept 2020 , when " OUTLINER_COLLECTION " was introduced

https://github.com/blender/blender/commit/5a28090977d66d8e52d269fb5bb938d953191dde

**Comment by zeffii** [comment]
we aretesting on Blender 2.82 . it has failed since https://github.com/nortikin/sverchok/commit/bcfe321ea6e0bc8b518e2435bc70006aa2966fa0

**Comment by zeffii** [comment]
any tips? https://github.com/nortikin/sverchok/pull/4137

**Comment by zeffii** [comment]
i changed the download of Blender to 2.92, but ultimately left the Python version the same 3.7

![image](https://user-images.githubusercontent.com/619340/120495576-201def00-c3bd-11eb-8c47-a9c91727f07a.png)

i'm not sure where to find solutions to this

**Comment by zeffii** [comment]
should it be 
```
home/runner/work/sverchok/sverchok/installation/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/scripts/addons/sverchok
````

?

**Comment by zeffii** [comment]
@vicdoval @portnov   how does one add a line to that yaml to print the installation directory of Blender ?

**Comment by vicdoval** [comment]
i would like to help more in ts task but the changes i have done in the yaml where almost blindly ...
i would say  the installation directory is 
![image](https://user-images.githubusercontent.com/10011941/120624328-e1417500-c460-11eb-8365-27928c136128.png)

**Comment by portnov** [comment]
@zeffii "run" section is just a bash script. So it's something like
```
echo Directory: $BLENDER_DIR
```

**Comment by zeffii** [comment]
ok https://github.com/nortikin/sverchok/pull/4141  is now working, but the tests are failing in some cases.
