### ISSUE TITLE
Error in Evolver name 'tree' is not defined

### ISSUE THREAD

**Issue by martinussuijkerbuijk** [nortikin/sverchok#4138]
When using the evolver as in [here](https://raw.githubusercontent.com/vicdoval/sverchok/docs_images/images_for_docs/logic/evolver/evolver_genetics_algorithm_sverchok_blender_example_03.png) it returns a NameError:

Python: Traceback (most recent call last):
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\utils\sv_operator_mixins.py", line 67, in execute
    response = self.sv_execute(context, node)
  File "C:\Users\martinus\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 548, in sv_execute
    population = Population(genotype_frame, node, tree)
NameError: name 'tree' is not defined

I think it's just the reference to the tree it can't find. Am I missing something obvious here?

**Comment by zeffii** [comment]
nope. looks like i may broken  that

**Comment by zeffii** [comment]
that should be fixed in master now.  https://github.com/nortikin/sverchok/commit/13fa96decc4b4d28e93686d7fd4cb3f702569636

**Comment by martinussuijkerbuijk** [comment]
Yes confirmed. Fixed. Thank you.

**Comment by zeffii** [comment]
thanks for the report @martinussuijkerbuijk  !
