### ISSUE TITLE
Connection to virtual sockets

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4139]
Some nodes does not expect to be connected to group input nodes.

![2021-06-02_08-16-45](https://user-images.githubusercontent.com/28003269/120423176-f6dc6f00-c37a-11eb-9dad-57528e7a1d8c.png)

It looks like that solution of generating sockets dependent on the type of socket of connected node should be generalized and spread over all nodes that use this technic.

**Comment by zeffii** [comment]
how did you achieve ListRepeater setting the output socket to `NodeSocketVirtual`, nested nodegroups?  `data_structure.changable_sockets` is quite agnostic to the socket type.. except for dummysocket.

**Comment by Durman** [comment]
Interesting indeed. Now I can't reproduce this.
I was updating some examples and got the nodes from a monad and then auto convert them into a node group.

**Comment by zeffii** [comment]
weird

**Comment by Durman** [comment]
Close for now
