### ISSUE TITLE
KDT Closest Edges MK2 - variable output

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4143]
With dependencies the node returns one result and witohut them another.

I believe that with the same input output of the node should be persistent.

I'm not sure how this should be fixed. What is difference between nodes which rely on the behaviour without dependencies and nodes relay on the behaviour with dependencies? How they can be distinguished?

**Comment by vicdoval** [comment]
If you have scipy it offers different modes if you don't it offers only the 'Complete' mode which relies in mathutils kdt.

Maybe it would be enough if the default mode would be 'Complete' so the output does not change when you install the dependecies

**Comment by Durman** [comment]
When you installed SciPy and created a node tree with the node and then after some time when you open the tree again you see that out put of the tree is strange because you don't remember that in the tree there is one node which was created when SciPy library was available and because the node does not make any hints that if you want to have the same out put you have to install the library.

This is what I mean the node should give persistent output. If the node expects the library to be installed it should make a warning if it's not but not to shift to another output.
