### ISSUE TITLE
rendering from command line

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4147]
I would like to render my sverchok animation via command line.

Unfortunately this only works ("online") only if i press the "update all" button first.

Now i have no idea how to activate this "update all" via command line. Is this possible?

Thank you.

**Comment by zeffii** [comment]
maybe add this switch in the commandline  ` --python-text update_all_overkill.py`

and you would add a short script in `Texts` called **update_all_overkill.py** containing
```python
import bpy
bpy.ops.node.sverchok_update_all()
```

maybe,

**Comment by zeffii** [comment]
but the need to press "update all" might be related to a bug that other users are reporting ( but that I can not reproduce yet )

**Comment by luckychris** [comment]
unfortunately this does not work. Ok, maybe this helps you: I am using Blender on a MacBookPro. 
![image](https://user-images.githubusercontent.com/232549/120924792-af851400-c6d5-11eb-9072-9cbb2f63a3fc.png)

I really love the using and learning Sverchok, but for me it is a bit frustrating that i have to restart Blender every 20th frame because i got constantly crashes when i try to render animations with Sverchok. maybe i am making some dumb mistakes...here is my blend file:

https://www.dropbox.com/s/pxnhpq4b1ltmgbx/sc_grass_nope.blend?dl=0

It works only, if i press "update all" before rendering, else each frame looks the same and it won't render an animation.

Unfortunately this happens on each Blender version i tried: 2.92, 2.93, 3.0.0alpha

**Comment by zeffii** [comment]
ok. there are other threads that cover crashes while rendering, they might be worth reading.
https://github.com/nortikin/sverchok/issues/3744
https://github.com/nortikin/sverchok/issues/2390#issuecomment-492712076

**Comment by zeffii** [comment]
I don't understand why you connect the Frame Info node to a maprange. It barely moves the grass here.. This is why i implemented `evaluate` to return a value between 0 and 1 for the frame range.

![image](https://user-images.githubusercontent.com/619340/120926893-16f39180-c6df-11eb-8aa3-25420745ee50.png)

**Comment by luckychris** [comment]
Hi Zeffii, you are totally right. That's much easier. Thank you.
