### ISSUE TITLE
Graph takes two times to display

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4148]
## Problem statement

When I open a sverchok graph (using Topologic nodes), I could see from the terminal window that the topologic nodes are executing correctly. However, when the Blender interface finally displays on screen, the visual results are not visible and all nodes report empty outputs. I then have to press "Update all" to re-run the graph and the output is then correct. This effectively means that graphs are taking twice the time to run. Why is that happening? Am I doing something wrong?

## Steps to reproduce

1. Install TopologicSverchok
2. Run Blender from a Terminal window
3. Open a sample topologic graph
4. Watch the results in the terminal window and then in the Blender GUI

## Expected result

The graph runs once and the visual results displayed in the Blender view

## Actual result

Empty screen and the nodes have empty output

## Sverchok version

0.6.0.0

**Comment by zeffii** [comment]
is this upon the first load of a .blend ?

**Comment by zeffii** [comment]
but i have seen reports of users needing to press update all for sverchok to fully "get a grip",
https://github.com/nortikin/sverchok/issues/4078

**Comment by wassimj** [comment]
> is this upon the first load of a .blend ?
> 
> it's helpful to also establish if this is behaviour unique to your suite of nodes, or does this happen if you make a blend with just a few sverchok-core nodes outputting to a viewer node.

Yes exactly. It is on first load of sverchok:
1. I launch blender.exe from Terminal
2. I choose open recent and choose my .blend file
3. It executes (as evidenced in the Terminal window (Topologic nodes are outputting debug information correctly)
4. Nothing displays on screen and the output of the topologic nodes is NULL/Empty
5. I choose Open Recent again and choose the same file
6. It asks me if I want to Save the current file, I choose Don't Save
7. It opens the file again and this time, everything is correct

**Comment by wassimj** [comment]
It is not specific to Topologic nodes. I just tested it with a simple:
Sphere node connected to a Temporal Viewer node.
It does not display on first load until I either press "Update all" or I re-load the file one more time without quitting Blender.

**Comment by zeffii** [comment]
[testing_temporal_viewer_2021_06_06_08_48.zip](https://github.com/nortikin/sverchok/files/6603873/testing_temporal_viewer_2021_06_06_08_48.zip)

this should load:  
![image](https://user-images.githubusercontent.com/619340/120918462-dbdc6880-c6b4-11eb-8f26-3d8d348f84b4.png)

**Comment by zeffii** [comment]
there must be something that unites all of the users who have to do this.

**Comment by zeffii** [comment]
@wassimj   when you load blender, do you 
 - always have to create a new `sverchok` node tree?   
 - or do you store a startup.blend with an empty nodetree (which is what I do..)
       - `Files` -> `Defaults` -> `Save Startup File`

**Comment by zeffii** [comment]
@wassimj   just out of interest, how many cores does your machine have? :)

**Comment by Durman** [comment]
Most likely it is relevant to, as I consider this, Blender bug - https://developer.blender.org/T88837
There is no such bug in 2.92

**Comment by zeffii** [comment]
yeah, the order can be this one sometimes:
```
Read blend: c:\see_life1.blend
do update general was called!
handler: pre load: start
loading:
cleaning Sverchok cache
handler: sv_clean: start
handler: sv_clean: end
handler: pre load: end
handler: post load: start
handler: post load: end
handler: sv_main: start
handler: sv_main: end

```

**Comment by wassimj** [comment]
> Most likely it is relevant to, as I consider this, Blender bug - https://developer.blender.org/T88837
> There is no such bug in 2.92

I can confirm that this bug does not exist in 2.92. It opens and loads correctly in 2.92.

**Comment by wassimj** [comment]
> @wassimj just out of interest, how many cores does your machine have? :)

Oh I am on a relatively weak machine: An Intel NUC i5 Quad core. I use it for software development but not for any advanced rendering or animation.

**Comment by wassimj** [comment]
> @wassimj when you load blender, do you
> 
> * always have to create a new `sverchok` node tree?
> * or have you stored a _startup.blend_ with an empty nodetree (which is what I do..)
>   
>   * `Files` -> `Defaults` -> `Save Startup File`

I have not done the save startup thing. I either start blender, press scripting and then switch to sverchok view or I already have a blender file so I start from terminal (to see errors) then File>Open a blender file. I have also experimented with saving and loading JSON graphs. Works well.

**Comment by zeffii** [comment]
a NUC ? cool :)  it can be quite deceiving to dev on a high spec machine.

There's not a whole lot we can do about Blender behaving differently between 2.92 and 2.93, except go into discussion with Blender devs. Thanks for the report, it's really weird that my machine doesn't suffer from this.
