### ISSUE TITLE
How To Read Radius Stroke of Grease Pencil?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4150]
<img width="940" alt="Screen Shot 2021-06-07 at 11 18 27 pm" src="https://user-images.githubusercontent.com/3952687/121023572-be0f2080-c7e6-11eb-8050-02d57c94b8fe.png">

Just wondering if there is SV nodes that can read the radius of Grease Pencil Strokes and then re-mapping it into the "resampled" points?

**Comment by enzyme69** [comment]
BLEND: https://www.dropbox.com/s/lpbkeyja1v3g5ne/sverchok_radius_002.blend.zip?dl=0

I like the GP+ macro and use it all the time, and now since we have Geometry Nodes, I wonder if we could take advantage of Grease Pencil strokes with Sverchok for GM.

**Comment by zeffii** [comment]
right now in `object ID selector`, you are `passing points`,  but if you untick that box you will get the GP objects proper, and those can be queried per point.  See:  https://blenderartists.org/t/wip-sverchok-parametric-nodes-for-architects/557250/2551?u=zeffii

**Comment by zeffii** [comment]
something like:  
![image](https://user-images.githubusercontent.com/619340/121069672-0cfc8c00-c7ce-11eb-89f0-fa46288ef084.png)

**Comment by zeffii** [comment]
one way to do this is to convert 1D values "pressure" to a 3D value (Vector in...and a number range) and that lets you interpolate them as if they where vectors, then you later decompose and take only the Z value (which is what pressure was representing)

**Comment by zeffii** [comment]
but it seems the pressures of the first 3 objects are all 1.0 , in the blend. so .. looks ok.

**Comment by zeffii** [comment]
this reminds me, the minimized state of the `Object Id Set` could display the selector string. @vicdoval @portnov @nortikin

**Comment by zeffii** [comment]
exactly what technique you use to interpolate between pressures, is up to you. this is merely a suggestion.

**Comment by zeffii** [comment]
@enzyme69  but this is more accurate

![image](https://user-images.githubusercontent.com/619340/121190922-cb222300-c86b-11eb-8dfb-d69e94e21db9.png)

it takes into account that the coordinates are not linearly distributed in the original, so it uses accumulated sum to generate a 2d mapping.

[sverchok_radius_002_2021_06_08_13_12.zip](https://github.com/nortikin/sverchok/files/6616743/sverchok_radius_002_2021_06_08_13_12.zip)

**Comment by gabrielmontagne** [comment]
This is wonderful!  @zeffii, might there be a way to also expose or promote the vertex colours from the GP object all the way out to use them on the curve material shaders? 

This stuff is good.  With this, one can draw and animate "directly", with no lag, into geometry.  Amazing.
