### ISSUE TITLE
gist export broken

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4151]
@Durman 
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\ui\sv_IO_panel.py", line 299, in execute
    is_tree_exportable, msg = self.can_be_exported(ng)
  File "C:\Users\zeffi\Downloads\blender29\2.93\scripts\modules\bpy_types.py", line 720, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'SvNodeTreeExportToGist' object has no attribute 'can_be_exported'

location: <unknown location>:-1
```
where is `can_be_exported` defined.

_Originally posted by @zeffii in https://github.com/nortikin/sverchok/issues/4149#issuecomment-856194760_

**Comment by zeffii** [comment]
while on this subject, the export to JSON will produce a single line file,   is this intentional?   i intentionally made that with indentation for ease of reading/editing.

**Comment by zeffii** [comment]
nice work on the rest. easy to read.

**Comment by zeffii** [comment]
this can go, right?

https://github.com/nortikin/sverchok/blob/2c1026cb5e992d69633e53fa84c6033bce9277e0/ui/sv_IO_panel.py#L299-L302

**Comment by Durman** [comment]
Yes I didn't notice this. All trees are exportable now. 
Just for your information I'm not being notified by your new messages anymore even if you mention me.

**Comment by zeffii** [comment]
> Just for your information I'm not being notified by your new messages anymore even if you mention me.

progress!

**Comment by zeffii** [comment]
@Durman 

> If you want to go fast, go alone.
> If you want to go far, go together.
