### ISSUE TITLE
How to achieve the shortest path between two faces？

### ISSUE THREAD

**Issue by vktcl** [nortikin/sverchok#4155]
## Problem statement

How to achieve the shortest path between two faces in sverchok?

**Comment by wassimj** [comment]
In Topologic for Sverchok (http://github.com/wassimj), it is quite straightforward:
1. Convert the mesh to a Topologic entity (e.g. a Shell, can be open or closed)
2. Create a Graph.ByTopology
3. Find the two vertices (which represent the centers of mass of each face or optionally a vertex guaranteed to be inside the face)
4. Connect them to Graph.ShortestPath

<img width="1920" alt="MeshShortestPath" src="https://user-images.githubusercontent.com/6302909/121345702-16483e80-c91d-11eb-8b7f-bd76b5f3efd9.PNG">

**Comment by vktcl** [comment]
> 在《斯韦乔克的托波逻辑[》（http://github.com/wassimj）](https://github.com/wassimj)中，它非常简单：
> 
> 1. 将网格转换为托波逻辑实体（例如，壳牌，可以打开或关闭）
> 2. 创建图形。按主题
> 3. 查找两个顶点（表示每个面部的质量中心或可选的顶点保证在面部内）
> 4. 将它们连接到图形。
> 
> <img alt="MeshShortestPath" width="1920" src="https://user-images.githubusercontent.com/6302909/121345702-16483e80-c91d-11eb-8b7f-bd76b5f3efd9.PNG">

The topology node is great, it solved my problem, but I ran into a new problem.
Can it be easier to install and use this topology node extension? I am very new to installing some dependent libraries.
It is recommended that you can add a button under the plugin panel to automatically install related dependencies

**Comment by wassimj** [comment]
> The topology node is great, it solved my problem, but I ran into a new problem.
> Can it be easier to install and use this topology node extension? The complicated installation process makes it difficult to use it. I am very unfamiliar with the installation of some dependent libraries.
> It is recommended that you can add a button under the plugin panel to automatically install related dependencies

We are very aware of that. Bruno Postle is working hard on this for linux. It will take me time to figure how to do it for Windows.
