### ISSUE TITLE
Evolver Error

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4156]
## Problem statement

When I try to run Evolver, it is reporting an error:
```
Read blend: D:\WasInDesktop\compactness.blend
cleaning Sverchok cache
Python: Traceback (most recent call last):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\sv_operator_mixins.py", line 67, in execute
    response = self.sv_execute(context, node)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 548, in sv_execute
    population = Population(genotype_frame, node, tree)
NameError: name 'tree' is not defined

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\sv_operator_mixins.py", line 67, in execute
    response = self.sv_execute(context, node)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 548, in sv_execute
    population = Population(genotype_frame, node, tree)
NameError: name 'tree' is not defined

location: <unknown location>:-1
```

## Steps to reproduce

1. Drag and drop an Evolver Node
2. Test it with any simple case

## Expected result

The Evolver result.

## Actual result

An error as you see above

## Sverchok version

0.6.0.0

**Comment by zeffii** [comment]
i think you are using an older version of Sverchok.

**Comment by zeffii** [comment]
i think you are using an older version of Sverchok. - i fixed this 8 days ago. 
https://github.com/nortikin/sverchok/blob/master/nodes/logic/evolver.py

https://github.com/nortikin/sverchok/commit/13fa96decc4b4d28e93686d7fd4cb3f702569636#diff-e1612d2c111545ba5013e97e54d4ea421386c517f515fe89be32bf8bda6005ce

**Comment by wassimj** [comment]
ok. Do you increment the sverchok version? Because it is very difficult to know which version I should be on otherwise. Thank you.

**Comment by zeffii** [comment]
we haven't incremented beyond 0.6.0 for a very long time.
https://github.com/nortikin/sverchok/issues/4103

**Comment by wassimj** [comment]
ok. Anyway. thank you. It now works with the new update.

**Comment by zeffii** [comment]
really sorry about the confusion. we will work on this.

**Comment by wassimj** [comment]
No worries at all :) Enoying sverchok immensely. I hope to be able to showcase Evolver optimising things in Topologic :)
