### ISSUE TITLE
[FreeCAD 0.20] Mefisto method doesn't work

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4159]
I'm starting to report the problems I got when experimenting with FreeCAD0.20 under Blender2.93.

I found that Mefisto method of conversion doesn't work as before. 
I tried to get a mesh from a sphere solid and got only few vertices.
![Mefisto_UnderFC020](https://user-images.githubusercontent.com/66558924/121549338-7242be00-ca16-11eb-8af7-a39939e3ed83.jpg)
There are no errors in the console.

**Comment by rendetto** [comment]
Just tested on Blender 2.93.1 and 2.93.2 with the latest FC0.20 - Mefisto works as expected:

![Mefisto_UnderFC020_bl2 93 2](https://user-images.githubusercontent.com/66558924/123865803-07a9e180-d935-11eb-9c88-7036d82a287b.jpg)

**Comment by rendetto** [comment]
Just tested latest to-date Blender 2.93.2 and FC0.20 build - Mefisto still works as expected.
I'm closing this issue.

**Comment by brothermechanic** [comment]
Hello, sverchok devs
I got strange results with Mefisto tesselation
![Screenshot_20220516_135405](https://user-images.githubusercontent.com/3109995/168577580-165f0d2f-2f7c-411b-bfd9-0306163fe6f7.jpg)
My blender is 3.2 with 3.10 python

**Comment by rendetto** [comment]
Which version of FreeCAD you are using? Is it built against Python 3.10?

**Comment by brothermechanic** [comment]
FreeCAD-0.19 build with same python-3.10

**Comment by rendetto** [comment]
Can you try how the FreeCAD-0.20 conda build will behave? I guess you are on Linux, so there is already package for Python-3.10.

https://anaconda.org/freecad/freecad/files

**Comment by rendetto** [comment]
I just discovered that a wind64 conda package for FreeCAD-0.20 compiled against py-3.10 was released a couple of hours ago.
There are py3.10 compatible packages for OSX and Linux also. So you can use whatever suits you.

I tested the case you showed and there are no problems - mesh generation with Mefisto method works OK.

**Comment by brothermechanic** [comment]
> Can you try how the FreeCAD-0.20 conda build will behave? I guess you are on Linux, so there is already package for Python-3.10.
> 
> https://anaconda.org/freecad/freecad/files

You are right, with freecad-0.20 all works fine.
Thank you!
