### ISSUE TITLE
[FreeCAD 0.20] Compound Solid node does not work

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4160]
When trying to use Compound Solid node with FreeCAD0.20 it throws an error: 

**AttributeError: type object 'App.Part' has no attribute 'Shape'**

![CompoundSolidFC020DoesntWork](https://user-images.githubusercontent.com/66558924/121559755-8d65fb80-ca1f-11eb-81e7-b3d181feab47.jpg)

**Comment by rendetto** [comment]
Just tested the latest to-date Blender2.93.2 build under win10 with the latest FreeCAD0.20. The error still occurs.

**Comment by portnov** [comment]
I've pushed a change to master. Please test.

**Comment by rendetto** [comment]
Tested. It works now. Thanks a lot!
