### ISSUE TITLE
[FreeCAD 0.20] Export curves does not work

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4161]
When trying to export curves with the "Export Solid" node using FreeCAD0.20 an error occurs:

**AttributeError: type object 'App.Part' has no attribute 'Shape'**

![ExportCurveFC020DoesntWork](https://user-images.githubusercontent.com/66558924/121562653-55ac8300-ca22-11eb-87c2-c075e5f40c7a.jpg)

Exporting Solids and Surfaces still works though.

**Comment by rendetto** [comment]
Just tested the latest to-date Blender2.93.2 build under win10 with the latest FreeCAD0.20. The error still occurs.

**Comment by portnov** [comment]
I've pushed a change to the master. Please test.

**Comment by rendetto** [comment]
Tested. It works now. Thanks a lot!
