### ISSUE TITLE
Clicking Update All crashes Blender

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4165]
## Problem statement

Clicking update all crashes blender. Please see video for more information
## Steps to reproduce

1. See video
[blender_debug_output.txt](https://github.com/nortikin/sverchok/files/6643739/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/nortikin/sverchok/files/6643740/blender_system_info.txt)

https://cf-my.sharepoint.com/:v:/g/personal/jabiw_cardiff_ac_uk/ESRd-yMtdn1HjLeXIf2_rPsBzrQWb4toGxSviiD5HrlFJw?e=g83DOf

**Comment by Durman** [comment]
Can you repeat the bug with this added to some Sverchok register function? This should add extra information about the fault.

```py
import faulthandler
faulthandler.enable()
```

**Comment by wassimj** [comment]
Done. I get this. I looked up the line where it stopped and it is simply:
topology = item[0]
The file is attached.

[CellPrism.zip](https://github.com/nortikin/sverchok/files/6643896/CellPrism.zip)


2021-06-13 13:41:38,555 [INFO] root: Initializing Sverchok logging. Blender version 2.93.1 Release Candidate, Sverchok version 0.6.0.0
addon_utils.disable: topologicsverchok not disabled
Modules Installed (topologicsverchok) from 'C:\\Users\\wassimj\\OneDrive - Cardiff University\\Topologic Files\\TopologicSverchok\\topologicsverchok.zip' into 'C:\\Users\\wassimj\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons'
(Re-)building pre-compiled headers (options: -O2); this may take a minute ...
2021-06-13 13:42:15,558 [WARNING] py.warnings: C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\topologicsverchok\topologicPy\site-packages\cppyy\__init__.py:318: UserWarning: CPyCppyy API not found (tried: C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\site\python3.9); set CPPYY_API_PATH envar to the 'CPyCppyy' API directory to fix
  warnings.warn("CPyCppyy API not found (tried: %s); set CPPYY_API_PATH envar to the 'CPyCppyy' API directory to fix" % apipath_extra)

Can't obtain buffer
Read blend: C:\Users\wassimj\OneDrive - Cardiff University\Topologic Files\TopologicSverchok\MeshShortestPath.blend
Graph.ByTopology Operation consumed 3.06 seconds
Graph.Vertices Operation consumed 0.0 seconds
Topology.GeometryNew Operation consumed 0.03 seconds
Use k-d tree: False. Nearest Vertex Operation consumed 0.002 seconds
Graph Topological Distance Operation consumed 0.4377 seconds
Topology.Geometry Operation consumed 0.22 seconds
Use k-d tree: False. Nearest Vertex Operation consumed 0.002 seconds

Graph.ShortestPath Operation consumed 0.04 seconds
Topology.GeometryNew Operation consumed 0.0 seconds
Graph.Topology Operation consumed 0.22 seconds
cleaning Sverchok cache
Graph.ByTopology Operation consumed 2.62 seconds
Graph.Vertices Operation consumed 0.0 seconds
Topology.GeometryNew Operation consumed 0.02 seconds
Use k-d tree: False. Nearest Vertex Operation consumed 0.002 seconds
Graph Topological Distance Operation consumed 0.4418 seconds
Topology.Geometry Operation consumed 0.13 seconds
Use k-d tree: False. Nearest Vertex Operation consumed 0.003 seconds

Graph.ShortestPath Operation consumed 0.04 seconds
Topology.GeometryNew Operation consumed 0.0 seconds
Graph.Topology Operation consumed 0.22 seconds
Read blend: D:\WasInDesktop\Prism-Test01.blend
Topology.GeometryNew Operation consumed 0.0 seconds
cleaning Sverchok cache
Topology.GeometryNew Operation consumed 0.01 seconds
Topology.GeometryNew Operation consumed 0.0 seconds
Topology.GeometryNew Operation consumed 0.0 seconds
Windows fatal exception: access violation

Current thread 0x00005314 (most recent call first):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\topologicsverchok\nodes\Topologic\CellPrism.py", line 136 in processItem
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\topologicsverchok\nodes\Topologic\CellPrism.py", line 257 in process
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 396 in do_update_general
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\profile.py", line 107 in wrapper
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 435 in do_update
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 518 in process_from_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\node_tree.py", line 419 in process_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\data_structure.py", line 1249 in updateNode
 *** Break *** segmentation violation

==========================================
=============== STACKTRACE ===============
==========================================


================ Thread 0 ================
  libcppyy_backend!??
  libCoreLegacy!CppyyLegacy::TWinNTSystem::DispatchSignals()
  ucrtbase!seh_filter_exe()
  blender!PyInit_aud()
  VCRUNTIME140!_C_specific_handler()
  ntdll!_chkstk()
  ntdll!RtlRaiseException()
  ntdll!KiUserExceptionDispatcher()
  python39!PyObject_GetItem()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyMethod_Self()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyEval_EvalFrameDefault()
  python39!PyFunction_Vectorcall()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyEval_EvalFrameDefault()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyMethod_Self()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!PyInit_aud()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 1 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 2 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 3 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 4 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 5 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 6 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 7 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 8 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 9 ================
  ntdll!ZwWaitForWorkViaWorkerFactory()
  ntdll!TpReleaseCleanupGroupMembers()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 10 ================
  ntdll!ZwWaitForMultipleObjects()
  KERNELBASE!WaitForMultipleObjectsEx()
  KERNELBASE!WaitForMultipleObjects()
  ig9icd64!DumpRegistryKeyDefinitions()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 11 ================
  ntdll!ZwWaitForAlertByThreadId()
  ntdll!RtlSleepConditionVariableSRW()
  KERNELBASE!SleepConditionVariableSRW()
  ig9icd64!??
  ig9icd64!??
  ig9icd64!??
  ig9icd64!DumpRegistryKeyDefinitions()
  ig9icd64!??
  ig9icd64!??
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 12 ================
  ntdll!NtAlpcSendWaitReceivePort()
  dwmapi!DwmUnregisterThumbnail()
  dwmapi!DwmFlush()
  ig9icd64!DumpRegistryKeyDefinitions()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 13 ================
  ntdll!ZwWaitForMultipleObjects()
  KERNELBASE!WaitForMultipleObjectsEx()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 14 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 15 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 16 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 17 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 18 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 19 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 20 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

==========================================
============= END STACKTRACE =============
==========================================

 *** Break *** segmentation violation

==========================================
=============== STACKTRACE ===============
==========================================


================ Thread 0 ================
  libcppyy_backend!??
  libCoreLegacy!CppyyLegacy::TWinNTSystem::DispatchSignals()
  ucrtbase!seh_filter_exe()
  blender!PyInit_aud()
  VCRUNTIME140!_C_specific_handler()
  ntdll!_chkstk()
  ntdll!RtlRaiseException()
  ntdll!KiUserExceptionDispatcher()
  python39!PyObject_GetItem()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyMethod_Self()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyEval_EvalFrameDefault()
  python39!PyFunction_Vectorcall()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyEval_EvalFrameDefault()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  python39!PyMethod_Self()
  python39!PyOS_URandomNonblock()
  python39!PyEval_GetFuncDesc()
  python39!PyEval_EvalFrameDefault()
  python39!PyCFunction_Call()
  python39!PyFunction_Vectorcall()
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!??
  blender!PyInit_aud()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 1 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 2 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 3 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 4 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 5 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 6 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 7 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 8 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  blender!??
  blender!??
  blender!??
  blender!??
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 9 ================
  ntdll!ZwWaitForWorkViaWorkerFactory()
  ntdll!TpReleaseCleanupGroupMembers()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 10 ================
  ntdll!ZwWaitForMultipleObjects()
  KERNELBASE!WaitForMultipleObjectsEx()
  KERNELBASE!WaitForMultipleObjects()
  ig9icd64!DumpRegistryKeyDefinitions()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 11 ================
  ntdll!ZwWaitForAlertByThreadId()
  ntdll!RtlSleepConditionVariableSRW()
  KERNELBASE!SleepConditionVariableSRW()
  ig9icd64!??
  ig9icd64!??
  ig9icd64!??
  ig9icd64!DumpRegistryKeyDefinitions()
  ig9icd64!??
  ig9icd64!??
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 12 ================
  ntdll!NtAlpcSendWaitReceivePort()
  dwmapi!DwmUnregisterThumbnail()
  dwmapi!DwmFlush()
  ig9icd64!DumpRegistryKeyDefinitions()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 13 ================
  ntdll!ZwWaitForMultipleObjects()
  KERNELBASE!WaitForMultipleObjectsEx()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  Wacom_Tablet!WTOpenW()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 14 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 15 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 16 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 17 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 18 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 19 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

================ Thread 20 ================
  ntdll!NtWaitForSingleObject()
  KERNELBASE!WaitForSingleObjectEx()
  tbb!tbb::thread_bound_filter::try_process_item()
  tbb!tbb::thread_bound_filter::try_process_item()
  ucrtbase!configthreadlocale()
  KERNEL32!BaseThreadInitThunk()
  ntdll!RtlUserThreadStart()

==========================================
============= END STACKTRACE =============
==========================================

Error: Not freed memory blocks: 114605, total unfreed memory 21.473198 MB
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.
Freeing memory after the leak detector has run. This can happen when using static variables in C++ that are defined outside of functions. To fix this error, use the 'construct on first use' idiom.

C:\WINDOWS\system32>

**Comment by Durman** [comment]
Just out of curiosity if you try reproduce the crash again will it be on the same string?

**Comment by wassimj** [comment]
No. I get crashes elsewhere based on what input I am changing. Usually, (but not exclusively), these crashes happen when I use the pointer to slide the values rather than click and type another number. It almost seems it cannot keep up and gets a confused state that crashes it (but that is just my impression. I have no real clue why this is happening). It seems to be far less stable with the latest version of sverchok than what I have been working with over the last few months

Windows fatal exception: access violation

Current thread 0x00004284 (most recent call first):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 396 in do_update_general
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\utils\profile.py", line 107 in wrapper
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 435 in do_update
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\core\update_system.py", line 518 in process_from_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\node_tree.py", line 419 in process_node
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\data_structure.py", line 1249 in updateNode
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\sverchok-master\nodes\number\number_range.py", line 142 in mode_change
 *** Break *** segmentation violation

**Comment by Durman** [comment]
Can you test this with Sverchok from this branch https://github.com/nortikin/sverchok/tree/new_update_system?
It has completely different code of evaluating a tree.

**Comment by wassimj** [comment]
I can see that the topologic nodes are creating entities, but even after I press Update All many times, none of the other nodes in sverchok activate. Nothing shows on screen, nothing gets written into the stethoscope node.
<img width="786" alt="sverchok-bug" src="https://user-images.githubusercontent.com/6302909/121870015-875f6b80-ccfa-11eb-86a0-8257704346b2.PNG">

**Comment by Durman** [comment]
Any print in a console with the debug mode enabled in Sverchok preferences?

**Comment by wassimj** [comment]
Absolutely no warnings. It also seems to me that the 5 vertices where from before, because changing the count does not change the number of Topologic Vertices.. So nothing is really getting executed.

**Comment by Durman** [comment]
It would be nice if the add-on could be enabled without installing dependencies. In this case I could help in testing.

**Comment by wassimj** [comment]
I have a version that *perhaps* can be installed just by adding the zip file in preferences (only on Windows). How can I send you a private link? I don't want to list it here as it is not ready for public consumption. Thanks.

**Comment by Durman** [comment]
Can you send it via Discord to randum#3685?

**Comment by wassimj** [comment]
https://cf-my.sharepoint.com/:u:/g/personal/jabiw_cardiff_ac_uk/EQQ7mP7AZy9AqivgMRiKubsBo9GpEvDoneRazAW-IEOklQ?e=OSiEVo
Make sure you have Visual Studio 2019 with C++ desktop development add-on
Make sure you have Blenderbim Blender add-on installed
Use Blender 2.93 with python 3.9

**Comment by Durman** [comment]
I fixed the branch https://github.com/nortikin/sverchok/tree/new_update_system, now it should update properly.

**Comment by wassimj** [comment]
This new update is causing the following issue: Nothing gets shown on screen or in stethoscope. The Topologic nodes do show the number of outputs in the output sockets, so something gets updated, but the stethoscope shows nothing and the temporal mesh viewer shows nothing. I tried with just OOTB nodes (icosphere connected to temporal mesh viewer) with same result. Nothing gets displayed even after I repeatedly press "Update All"

**Comment by Durman** [comment]
I tested the add-on and unfortunately I can't say what is the reason of the crash. The only reason I know that can cause a crash is [an attempt to read a fread memory](https://docs.blender.org/api/current/info_gotcha.html#help-my-script-crashes-blender). But in this case the backtrace always points to certain block of code where this attempt was done. Here the backtrace looks like points to arbitrary places which seems has not any relations with actual error. My suggestion would be to try to simplify reproduction of the crash. It may be just a script without using any add-ons.
