### ISSUE TITLE
box node output description

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4169]
https://github.com/nortikin/sverchok/blob/f3b5d1e063e619399ad2f9a1235461abdb9ae073/nodes/generator/box_mk2.py#L321

this introduces a space becide the text "vers" and the socket .

![image](https://user-images.githubusercontent.com/619340/122031953-792f4f00-cdcf-11eb-93da-c595bb198ac7.png)

no errors in the console, @portnov  should that be displaying an icon for the user to click?   the area does allow a click and the tooltip does show.

**Comment by portnov** [comment]
we were discussing this some time ago... it can be implemented in different ways. This is just one of options.

**Comment by zeffii** [comment]
it's cool.
```python
layout.operator('node.sv_socket_show_help', text=text, icon='BLANK1', emboss=False).text = self.description
```
reduces the space a little..
![image](https://user-images.githubusercontent.com/619340/122055905-64f84b80-cde9-11eb-9e71-0d17dca1a143.png)

**Comment by zeffii** [comment]
ok
