### ISSUE TITLE
bpy.app object has no attribure binary_path_python

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4171]
When trying to install node: Sverchok-Extra i got this error. Is there some kind of workaround?

![image](https://user-images.githubusercontent.com/232549/122550247-bd228e00-d033-11eb-826e-7fe1f64d3bf5.png)

**Comment by zeffii** [comment]
`Sverchok-Extra` is maintained separately from Sverchok. 

sverchok has a check to see if there is such a thing as binary_path_python in the Blender api.
https://github.com/nortikin/sverchok/blob/1fbcb9d8182cc83ee93bd5e9f36d1be8e8b3fef4/settings.py#L18-L21

sverchok-extra add-on does not have that check
https://github.com/portnov/sverchok-extra/blob/d41d2993969b0361e28089b8ed76d8f5bb3395cc/settings.py#L7

**Comment by portnov** [comment]
Try the latest sverchok-extra master, should be fixed.
