### ISSUE TITLE
Installing Sverchok on Macos - name 'nodes' is not defined

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4172]
i just downloaded the .zip : stable early june2021 (vstable10) version and tried to install it on MacOs and i got:

![image](https://user-images.githubusercontent.com/232549/122550855-7f723500-d034-11eb-82cf-55afd6deb0ef.png)

name 'nodes' is not defined

this happens in Blender 2.92 and Blender 3.0.0alpha too

i could however successfully install vstable9 on Blender 3.0.0alpha

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok#errors-during-install-or-enable-in-preferences

I think we''ll have to increase the minimum supported version of Blender to 2.9.3

**Comment by zeffii** [comment]
we know of no known issue installing sverchok, except for the scenario mentioned in the readme. (I hope you read the section i linked).

failing that, reopen this issue.
