### ISSUE TITLE
Live Update seem not working

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4176]
I updated Sverchok and now it's unable to perform live update.

https://user-images.githubusercontent.com/66558924/122646138-6649b100-d126-11eb-86b0-baa608a67250.mp4

**Comment by zeffii** [comment]
The live operator only updates certain nodes. so i think the new `objects data get`  node might not have added itself to that list.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/aed151036e147904322ff8198f27084d6e910711 should fix this:

it was never an ideal solution to manually add these nodes to the list, but here we are 5 years later...

**Comment by rendetto** [comment]
Thanks a lot zeffii! It works now.
