### ISSUE TITLE
Groups / Monads not available

### ISSUE THREAD

**Issue by khlorghaal** [nortikin/sverchok#4178]
Grouping in sverchok does not appear to work under any circumstance. The options are greyed-out, no error given.
'monad' does not appear in node-search.

Everything else working as expected.
sverchok.log is empty when using valid nodes.

## Expected result
grouping should work the same as material nodes and geometry nodes

## Sverchok version
Sverchok 0.6
Blender 2.93
python 3.9.5
Linux
Addon installed from link to zip in readme, updated via plugin menu in blender.

![screenshot](https://user-images.githubusercontent.com/6794830/122690004-b4c58100-d1f4-11eb-9c95-58a706960bf1.png)

**Comment by Durman** [comment]
For now you can add group via `Add` menu (shift+a). I'm not sure how to connect or override operators from context menu. But it's definitely possible to add shortcut (Ctrl+G) for creating a node group from selected nodes.
![2021-06-21_06-38-43](https://user-images.githubusercontent.com/28003269/122700067-a52d5300-d25b-11eb-8d40-28026f09eb8c.png)

**Comment by khlorghaal** [comment]
ah i didnt look in the ``Add`` menu since I saw the context menu greyed out and assumed they were unavailable.
this is a minor feature request then, to make groups work with the context menus.

**Comment by khlorghaal** [comment]
oh #4152 removed monads, sad, they are useful for fractals, i can hackaround using group duplication though

**Comment by Durman** [comment]
I believe sverchok did not lost any features with monads removing. If you were using its vectorization feature then now there are loop nodes which have similar functionality.

**Comment by khlorghaal** [comment]
Ive noticed updates to constant/unconnected parameters within groups do not cause updates to the outer tree, and ``updateall`` must be manually used.
A workaround is to wire to the inputs and adjust them externally, but this is hacky and bad.

**Comment by Durman** [comment]
Could you show screenshot of a tree which does not update properly?

**Comment by khlorghaal** [comment]
![image](https://user-images.githubusercontent.com/6794830/123510488-e8b40280-d649-11eb-9901-280d5c850dc1.png)
![image](https://user-images.githubusercontent.com/6794830/123510603-83acdc80-d64a-11eb-9d0c-8b6e74e48998.png)
![image](https://user-images.githubusercontent.com/6794830/123510509-0aad8500-d64a-11eb-8f13-741cf9df24f5.png)
the update failure applies to all parameters within groups that ive tested

**Comment by Durman** [comment]
@khlorghaal Can you create separate issue with the file and description of the steps to reproduce the problem? From what I've seen on the screenshots everything should be updated properly.
