### ISSUE TITLE
Logic functions node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4181]
## Problem statement

Two problems here. When the mode of a node is changed it changes socket property type to float. Changing type of the socket property does not update node properly.

![logic bug](https://user-images.githubusercontent.com/28003269/123248018-7ed81380-d4f8-11eb-9575-d09e43acb487.gif)

**Comment by vicdoval** [comment]
It is not that it changes the property to float, it changes it to the default type of that mode (Int for _And_ or _Or_ and Float for _==_ or _!=_)
Two possible solutions:
1 Keep the user change when changing the mode
2 Keep the user change when changing the mode only if the default type of the new mode is identical to the default type of the old node

**Comment by Durman** [comment]
Second choice looks overcomplicated to me and I'm not sure that it will always be convenient. I would expect that node sticks with user choice.

**Comment by vicdoval** [comment]
The problem is that that property is changed by the node and by the user so the node would need another property to control if it has been changed by the user

**Comment by Durman** [comment]
I think the node should not control the float/int property and should leave this to user.

**Comment by vicdoval** [comment]
I understand it but is also practical that the properties are integers when using _And_  or _Or_ and floats when using _>_ or _!=_

In my experience there has been less cases in which I have to change this manually

**Comment by Durman** [comment]
I change the type of the property quite frequently and even thought to put this property into node UI.
