### ISSUE TITLE
How to ? or Posible to do Surface offset ?

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4185]
Hi all , From Surface object . Can it offset with specific distance in 3d space ?

my purpose explain in attatch image :) 
0 -base surface for rafter 
1 -offset 1  for purlin
2 -offset 2 for tile

Thank you very much. 
![22112](https://user-images.githubusercontent.com/32074126/123451067-90f4a780-d607-11eb-86cd-7b1c7696c626.jpg)

**Comment by rwny** [comment]
1st  i create any surface and use Sample U for Rafter , Sample V for purlin.  now in on the same level on base surface.
then just want to move purlin puton top of Rafter. 

like Solidify or Extrude Surface and use result sueface for next level (purlin)

**Comment by portnov** [comment]
Eh?
[4185.zip](https://github.com/nortikin/sverchok/files/6717357/4185.zip)

![Screenshot_20210625_204832](https://user-images.githubusercontent.com/284644/123451060-cba21400-d5f6-11eb-9680-0f9bd0ad44db.png)

**Comment by rwny** [comment]
Yes. Exactly what i want.
Thank you very much :)
