### ISSUE TITLE
Why wont this file load into Text In as JSON?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4189]
## Problem statement

JSON Text In failed to work

## Steps to reproduce

try loading this
[gp_ boy.json.zip](https://github.com/nortikin/sverchok/files/6723071/gp_.boy.json.zip)

## Expected result

What did you expect to see as a result of those steps?

## Actual result

error message
<img width="962" alt="Screen Shot 2021-06-28 at 1 12 08 pm" src="https://user-images.githubusercontent.com/3952687/123574119-a0940c00-d812-11eb-8f7c-914613645cf5.png">

## Sverchok version

latest sverchok, always

**Comment by zeffii** [comment]
why is the json wrapped with a `[ ]`

**Comment by zeffii** [comment]
the docs of the `Text In` node make it clear that the `json` that this node supports is not generic json, but json exported by the `Text Out` node in json mode .  The json you are trying to load is not generated by `Text Out`

https://github.com/nortikin/sverchok/blob/master/docs/nodes/text/text_in_mk2.rst

should the node be clearer about this?  i think so,   but is it broken?   no.

**Comment by zeffii** [comment]
the reason there is no generic json support comes down to the arbitrary forms that json can take, it would be simpler to write a small snlite script to output the data from that file.

**Comment by zeffii** [comment]
given your gp_.boy.json, it looks like a list of jsons/dicts, maybe for a frame by frame animation, but not exported by sverchok.

**Comment by zeffii** [comment]
i think some of the frames might be outputting 2d info, not 3d.
![image](https://user-images.githubusercontent.com/619340/123663461-b3b8d300-d836-11eb-9b06-72d0c766192a.png)

i haven't looked very deep.

**Comment by zeffii** [comment]
in summary, `json` is a storage format that can contain a wide variety of data arranged in a way that makes sense to the author of the json. The file you want to load contains a variety of data representations which need a dedicated "loader" to read and understand.  My snlite is only a quite example of what you might be able to do, but the rest you should be able to figure out. certainly consult the manual of whatever app/add-on that generated that output.
