### ISSUE TITLE
Can't turn on sverchok/ check box error

### ISSUE THREAD

**Issue by Sleszu** [nortikin/sverchok#4192]
Hello there! I badly need help with sverchok, after installation from zip file(sverchok-master), while i try to turn it on in add ons preferences i get error message

![errrsverchok](https://user-images.githubusercontent.com/86728479/123974932-4be0c480-d9bd-11eb-9ab9-772e16b0dd7b.png)

I try sverchok from github and from main site(sverchok-master, plus some 9 and 10 version(?)

Any ideas what is going on? Thanks for replays in advance!

**Comment by zeffii** [comment]
try restarting Blender, and enabling sverchok again and wait a while for it to enable . it will not be instant.

**Comment by portnov** [comment]
What exactly version of blender are you using, isn't it some kind of alpha or beta release?
I'd suggest to try latest 2.93.1 from blender.org.

**Comment by Sleszu** [comment]
Thx for replay! Yeah, i wish the solution was that simple :D Its my second day of fighting this error, i restarted blender, removing and installing sverchok countless times by now, and all the time i get that error...

I am using latest version from blender.org, 2.93.1 for some time now :)

Can my problem be connected with sverchok incompatibility with some other add ons/plugins?

**Comment by portnov** [comment]
Theoretically yes. You can try to disable all other plugins / addons and enable sverchok only.

**Comment by Sleszu** [comment]
Yeah, it was some conflict with other add on, i turn off everything, turn on sverchok, and what is most weird, i was able to turn on all other plugins...tested almost everything and all looks like working like i charm :D Super thanks for your time and help, two heads(or more :D) are better than one!
