### ISSUE TITLE
wrapper_tracked_ui_draw_op seems to no longer be valid

### ISSUE THREAD

**Issue by Moult** [nortikin/sverchok#4203]
These two lines in wrapper_tracked_ui_draw_op: https://github.com/nortikin/sverchok/blob/master/node_tree.py#L450-L451 seem to be referring to properties of bpy.types.Node. However, `self` is `Nodeutils`. My guess is that this function was refactored into `Nodeutils`, and that broke the function.

## Steps to reproduce

1. Attempt to use the function within a node like `self.wrapper_tracked_ui_draw_op(self.layout, "node.view3d_align_from", icon='CURSOR', text='')`
2. Let the node execute

## Expected result

I expect the operator to be wrapped with two operator properties.

## Actual result

I get an error, since self is referring to the wrong class.

## Sverchok version

Master from github.

**Comment by zeffii** [comment]
what error do you get?  the full error

**Comment by Moult** [comment]
Self has no name attribute.

**Comment by zeffii** [comment]
but can you explain the scenario you're using this on? because it does seem to work, here.. blender.293

![image](https://user-images.githubusercontent.com/619340/124347692-339fbe00-dbe6-11eb-968f-91d5d3ec9485.png)

**Comment by Moult** [comment]
Aaaah sorry I'm an idiot :) I didn't realise the new names are `node_name` and `tree_name`. It used to be called `idtree` and `idname`. Closing issue :)

**Comment by zeffii** [comment]
@Moult `node_name` and `tree_name` is hopefully a more explicit naming convention.

**Comment by Moult** [comment]
I completely agree, the new names are better :)
