### ISSUE TITLE
Is Matrix invert = align any Matrix plane to XY plane ?

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4207]
i study from file //Example > CNC > CNC PANNO
![f1](https://user-images.githubusercontent.com/32074126/124364421-ba4aae80-dc6b-11eb-8423-723786cdde8a.PNG)

i try in simple mesh and success to align any plane to XY .
i don't know about Matrix Invert mean , 
try for 2d drawing . am i understand correct ?
Thank you.
![asdf](https://user-images.githubusercontent.com/32074126/124364595-bf5c2d80-dc6c-11eb-9326-0c0e6e7ce35a.PNG)

**Comment by zeffii** [comment]
essentially yes, that's what Matrix Invert can be used for

![image](https://user-images.githubusercontent.com/619340/124365885-63cd7800-dc4b-11eb-91d2-e8c4693eed89.png)

**Comment by zeffii** [comment]
it's the 3d equivalent of the "reciprocal of X"  ( 1/X )
```
A * B = C
20 * 30 = 600
600 * 1/B = 20

```
