### ISSUE TITLE
Matrix Apply not working when Line + Line

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4217]
## Problem statement

Matrix Apply not working with Line + Line
![Capture](https://user-images.githubusercontent.com/32074126/125209460-198b6d00-e2c3-11eb-9413-bc4eb549f84d.PNG)

## Expected result
try with another object is OK. 
sverchok version 02edd87
![Capture2](https://user-images.githubusercontent.com/32074126/125209472-2d36d380-e2c3-11eb-872d-f51676bdf6a3.PNG)

Thank you.

**Comment by Durman** [comment]
Should be fixed now but I did not test the case. Feel free to reopen.

**Comment by rwny** [comment]
It working. Thankyou.
