### ISSUE TITLE
numba installation failed

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4219]
**Console output:**
```
Active code page: 65001
BM-WWYL JOB init is Runnig(1/1):
FINISHED!
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\121\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\M2B.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\121\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\error.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\121\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\package_manager.py'
Requirement already satisfied: Numba in c:\users\121\appdata\roaming\python\python39\site-packages (0.53.1)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in c:\users\121\appdata\roaming\python\python39\site-packages (from Numba) (0.36.0)
Requirement already satisfied: numpy>=1.15 in d:\program files\blender2.93\2.93\python\lib\site-packages (from Numba) (1.19.5)
Requirement already satisfied: setuptools in c:\users\121\appdata\roaming\python\python39\site-packages (from Numba) (57.1.0)
inf: Numba upgraded successfully. Please restart Blender to see effect.
```
**blender 2.93**

![{FK} IPRM0O9AY~OM9R)%8Y](https://user-images.githubusercontent.com/74725748/125390966-3f556680-e3d6-11eb-8d2b-0f984b2e8cae.png)
After restarting, it shows that it is not installed

**Comment by zeffii** [comment]
There are no nodes that directly use `numba` yet, but i suspect that will be only a matter of time. SNLite can load scripts that use numba, but those are mostly for experimentation.

can you do this in the bpy python console
```
>>> import numba
>>> numba.__version__
'0.53.1'
```
do you rename/delete the Python folder that comes with Blender, so that Blender uses your system Python?

**Comment by vkter** [comment]
bpy python console：
ModuleNotFoundError: No module named 'llvmlite'

**Comment by vkter** [comment]
in python console
>>> import numba
>>> numba.__version__
'0.53.1'
Correct display can be used, but not in blender

**Comment by vkter** [comment]
Blender 2.92 can be installed and used normally
Blender 2.93 has the above problem

**Comment by portnov** [comment]
As far as I see, the problem is that you have numba installed in  your system's python installation. So when we run `pip install numba`, it says that it is already installed. But for Blender/Sverchok to see it, you have to have numba installed in your Blender's python installation.
As a workaround, you can run `python3 -m pip uninstall numba` to remove numba from your system's python, and then install it from Sverchok preferences. But then, obviously, you won't be able to use numba from python scripts except for ones you run in Blender. Probably you can manage to have several different python installations at the same time in such a way that Blender's pip does not see numba from another installation, but I do not know how.

**Comment by zeffii** [comment]
it might be worth trying to manually pip install "llvmlite" into `D:\Program Files\blender2.93\2.93\python\lib\site-packages\`

**Comment by zeffii** [comment]
while not ideal you could probably copy over those two folders directly from `c:\users\121\appdata\roaming\python\python39\site-packages` into `D:\Program Files\blender2.93\2.93\python\lib\site-packages\`

**Comment by zeffii** [comment]
> Probably you can manage to have several different python installations at the same time in such a way that Blender's pip does not see numba from another installation, but I do not know how.

it would definitely be interesting to know how to do that.

**Comment by zeffii** [comment]
@vkter  out of curiosity what does your Blender python console say when you enter this
```
bpy.app.binary_path_python
```

**Comment by zeffii** [comment]
@portnov   something like this?
```
def pip_command(self, module_name, destination):

    if bpy.app.version >= (2, 91, 0):
        PYPATH = sys.executable
    else:
        PYPATH = bpy.app.binary_path_python

    try:
        if destination:
            cmd = [PYPATH, '-m', 'pip', 'config', 'set', 'global.target', f"{destination}"]
            ok = subprocess.call(cmd) == 0
            if ok:
                self.report({'INFO'}, f"set destination for pip (temporarily) to: "{destination})

        # pip install f"{module_name}"
        cmd = [PYPATH, '-m', 'pip', 'install', '--upgrade'] + self.package.split(" ")
        ok = subprocess.call(cmd) == 0
        if ok:
            self.report({'INFO'}, f"{self.package} installed successfully. Please restart Blender to see effect.")

    except Exception as err:
        self.report({"ERROR"}, err)

    finally:
        if destination:
            cmd = [PYPATH, '-m', 'pip', 'config', 'unset', 'global.target']
            ok = subprocess.call(cmd) == 0
            if ok:
                self.report({'INFO'}, f"Uunset destination for pip to the default")


```
looks a bit crazy.

**Comment by vkter** [comment]
>>> bpy.app.binary_path_python
'D:\\Program Files\\blender2.93\\2.93\\python\\bin\\python.EXE'

**Comment by vkter** [comment]
Following the prompts, I copied the site-packages folder in another python directly to blender python to solve the problem

**Comment by zeffii** [comment]
Making this work out of the box on all possible figurations is a bit of a pipe-dream, and will definitely require more testing, but it's good to know there are ways around it.

**Comment by zeffii** [comment]
this might be a little closer forcing an install location, but it doesn't seem to work. the error message is pretty interesting tho..
```python
import bpy
import os
import sys
import subprocess

above_291 = bpy.app.version >= (2, 91, 0)
PYPATH = sys.executable if above_291 else bpy.app.binary_path_python

class TestOperator():

    def __init__(self, destination, package):
        self.package = package
        self.pip_command(destination)

    def report(self, error_type, message):
        print(f"{error_type} ---> {message}")

    def run_command(self, cmd, msg_success, msg_failure):
        ok = subprocess.call(cmd) == 0
        self.report({'INFO'}, msg_success if ok else msg_failure)

    def pip_command(self, destination):

        try:
            if destination:
                cmd = [PYPATH, '-m', 'pip', 'config', 'set', 'global.target', f'"{destination}"']
                msg_success = f"set destination for pip (temporarily) to: {destination}"
                self.run_command(cmd, msg_success, "")

            # cmd = [PYPATH, '-m', 'pip', 'install', '--upgrade'] + self.package.split(" ")
            cmd = [PYPATH, '-m', 'pip', 'install', self.package]
            msg_success = f"{self.package} installed successfully. Please restart Blender to see effect."
            self.run_command(cmd, msg_success, "")

        except Exception as err:
            self.report({"ERROR"}, err)

        finally:
            if destination:
                cmd = [PYPATH, '-m', 'pip', 'config', 'unset', 'global.target']
                msg_success = f"Uunset destination for pip to the default"
                self.run_command(cmd, msg_success, "")

dirname = os.path.dirname(os.path.dirname(PYPATH))
destination = os.path.join(dirname, "lib", "site-packages")
TestOperator(destination, "numba")

```

**Comment by zeffii** [comment]
uhm, that @portnov  does seem to work (script visible).

even if it finds numba/llvmlite in a global install, this installs them into Blender's python site-packages.

```console
['C:\\Users\\zeffi\\Downloads\\blender29\\2.93\\python\\bin\\python.EXE', '-m', 'pip', 'config', 'set', 'global.target', 'C:\\Users\\zeffi\\Downloads\\blender29\\2.93\\python\\lib\\site-packages']
Writing to C:\Users\zeffi\AppData\Roaming\pip\pip.ini
{'INFO'} ---> set destination for pip (temporarily) to: C:\Users\zeffi\Downloads\blender29\2.93\python\lib\site-packages
Collecting numba
  Using cached numba-0.53.1-cp39-cp39-win_amd64.whl (2.3 MB)
Collecting setuptools
  Using cached setuptools-57.1.0-py3-none-any.whl (818 kB)
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0-cp39-cp39-win_amd64.whl (16.0 MB)
Collecting numpy>=1.15
  Using cached numpy-1.21.0-cp39-cp39-win_amd64.whl (14.0 MB)
Installing collected packages: setuptools, llvmlite, numpy, numba
Successfully installed llvmlite-0.36.0 numba-0.53.1 numpy-1.21.0 setuptools-57.1.0
WARNING: Target directory C:\Users\zeffi\Downloads\blender29\2.93\python\lib\site-packages\numpy already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\zeffi\Downloads\blender29\2.93\python\lib\site-packages\pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory C:\Users\zeffi\Downloads\blender29\2.93\python\lib\site-packages\setuptools already exists. Specify --upgrade to force replacement.
WARNING: You are using pip version 20.2.3; however, version 21.1.3 is available.
You should consider upgrading via the 'C:\Users\zeffi\Downloads\blender29\2.93\python\bin\python.EXE -m pip install --upgrade pip' command.
{'INFO'} ---> numba installed successfully. Please restart Blender to see effect.
Writing to C:\Users\zeffi\AppData\Roaming\pip\pip.ini
{'INFO'} ---> Uunset destination for pip to the default


```

**Comment by zeffii** [comment]
tested having numba and llvmlite installed globally, and got the same errors are @vkter when trying to install using pip from Sverchok.

**Comment by Durman** [comment]
Probably virtual environment could be used somehow.

**Comment by Durman** [comment]
Looks like a solution (from Blender dev) - https://github.com/robertguetzkow/blender-python-examples/tree/master/add_ons/install_dependencies#installing-the-package

**Comment by vkter** [comment]
I found the cause of this error,
Win10 folder permissions are not set to be writable, causing the package to be installed to the python global directory
When I modify the permissions, the blender python package is installed normally

**Comment by Durman** [comment]
Now installation should work.
