### ISSUE TITLE
New update system questions

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#4221]
1. I would suggest to disable "Node timings" checkbox by default.
2. Is it possible to return old keyboard shortcuts (F5 etc) by default?

**Comment by Durman** [comment]
I don't mind. ))
But I'm not sure that there is sence to return the F5 shortcut with the same logic because when you enabling tree processing (update live) it will be updated automatically.
For Ctrl+F5 `tree.force_update` can be used. It will update a whole tree regardless to its live udpate state.
