### ISSUE TITLE
Not Updating while rendering

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#4222]
Although this is a old problem  I was not having it on this file before updating the update system.
It updates fine on frame change but does not update when rendering with eevee
This error repeats every frame
```
Failed to update: generator already executing
2021-07-14 01:08:30,636 [ERROR] sverchok.core.main_tree_handler 131: 'NoneType' object is not an iterator
Caching exr file, 1080x1080, C:\....\AppData\Local\Temp\cached_RR_radialNoise4_Scene_4764d9b13d1c2732e623b7cf927ccb01.exr
Saved: 'E:\blender\Loops\RadialNoise\im3\0009.png'
 Time: 00:00.56 (Saving: 00:00.13)

Caching exr file, 1080x1080, C:\...\AppData\Local\Temp\cached_RR_radialNoise4_Scene_4764d9b13d1c2732e623b7cf927ccb01.exr 

```

**Comment by Durman** [comment]
Could you attach the file and show the steps to reproduce the error?

**Comment by vicdoval** [comment]
[noiseSphereReduced.zip](https://github.com/nortikin/sverchok/files/6981793/noiseSphereReduced.zip)
Adding noise to a 8 subdivisions icosphere
causes
```
Failed to update: generator already executing
2021-08-13 12:33:11,209 [ERROR] sverchok.core.main_tree_handler 133: 'NoneType' object is not an iterator
```

resulting in the next frame being rendered before sverchok updates...

Screenshot of nodetree

![image](https://user-images.githubusercontent.com/10011941/129345368-28afdc1f-7df9-47c6-aee7-53db46cce2de.png)

**Comment by Durman** [comment]
Hm.. looks like Sverchok thread has less priority over render thread. Interesting is it Blender bug, limitation or is it as it was intended to work.
```py
PROCESS_ANI  # call from frame change handler
START TASK  # call from timer handler
Node:"Frame info"  # process nodes
Node:"Map Range"
Node:"Scalar Math.001"
Node:"Scalar Math"
Node:"Map Range.001"
Saved: 'C:\Users\User\Desktop\im2\0004.png'  # the tree is still in process but current frame was already saved

Node:"Vector Math"  # it still calculates previous frame
PROCESS_ANI  # new call from frame change handler but processing of previous frame is still in progress
2021-08-13 15:11:37,432 [DEBUG] sverchok.core.main_tree_handler 187: Global update - 233ms
Failed to update: generator already executing  # it indicates that calculating of previous frame is not finished yet.

Node:"Vector Math.001"  # processing of previous frame
2021-08-13 15:11:37,794 [ERROR] sverchok.core.main_tree_handler 134: 'NoneType' object is not an iterator  # error in processing of previous frame, not sure why
Saved: 'C:\Users\User\Desktop\im2\0005.png'  # save current frame processing of which even was not started
```

**Comment by Durman** [comment]
Will have a look what is point of view of Blender devs - https://developer.blender.org/T90657

**Comment by Durman** [comment]
I was tired to wait Blender devs answer and made probably temporary solution. Now animation will be updated upon frame change handler instead of timer.

**Comment by Durman** [comment]
There should not be problem with rendering now.
