### ISSUE TITLE
when re-open file sverchok 1.0.0 not working

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4231]
## Problem statement
blender 2.93.1 and 3.0

sverchok 1.0.0 
when i save , close blender and start new open from old file sverchok not working. 
i can not edit all of my previous file.

Current Version 1.0.0
![image_2021-07-18_115024](https://user-images.githubusercontent.com/32074126/126078925-8155b996-9208-42b7-a35c-545ca8e3be43.png)

then i remove sverchok and install from old sverchok-master.zip  version 0.6.0.0 ( download 6/13/21)
it working 
Downgrade version 0.6.0 
![Annotation 2021-07-18 115702](https://user-images.githubusercontent.com/32074126/126079211-7589db63-0c28-4a28-abde-f8a13a9f55c4.png)

Thank you very much  :)

**Comment by enzyme69** [comment]
It's been like this for me for quite some time I need to refresh the node
using button
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by Durman** [comment]
Looks like update system is working.

![2021-07-19_06-50-54](https://user-images.githubusercontent.com/28003269/126095791-5d18ead9-97c5-4d6e-bd56-9e3889f6e411.png)

 At least I can't reproduce it on 2.93.1. I did not give it a try on 3.0.0 yet.

With 3.0.0 can be another problem

https://github.com/nortikin/sverchok/issues/2720#issuecomment-853763925

> The bgl module will be deprecated in Blender 3.0, in preparation of future Vulkan support. Add-ons should switch to using the gpu module, so that they will work with both OpenGL and Vulkan.

It means neither `stethoscope` or `Viewer draw` nodes will work till their code will be rewritten.

Can you try to use Mesh viewer node instead?

**Comment by rwny** [comment]
2.93.1 
try Mesh viewer not work 
![image_2021-07-19_113622](https://user-images.githubusercontent.com/32074126/126103517-464b7d38-9acf-441c-9d39-e39cf46356f0.png)

**Comment by Durman** [comment]
Ok. I would ask make the next steps:
- open Blender
-  go to the Sverchok preferences
-  set the settings according to the picture
-  close the Blender
-  make all steps to reproduce the problem
-  try to make several updates
-  save the `sverchok.log` file (or copy-paste)
- attach it to the issue

![2021-07-19_09-07-35](https://user-images.githubusercontent.com/28003269/126106008-8d90d6a7-71b1-4b41-a079-27a87f64d1e4.png)
