### ISSUE TITLE
NoneType' object is not an iterator error on main_tree_handler

### ISSUE THREAD

**Issue by mlevet** [nortikin/sverchok#4232]
Weird error here on blender 2.93, sverchok last version installed through zip.
Traceback (most recent call last):
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 59, in process_from_socket
    self.node.process_node(context)
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/node_tree.py", line 312, in process_node
    self.id_data.update_nodes([self])
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/node_tree.py", line 161, in update_nodes
    return TreeHandler.send(TreeEvent(TreeEvent.NODES_UPDATE, self, nodes))
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/main_tree_handler.py", line 32, in send
    NodesUpdater.cancel_task()
  File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/main_tree_handler.py", line 172, in cancel_task
    cls._handler.throw(CancelError)
ValueError: generator already executing
File "/Users/ml/Library/Application Support/Blender/2.93/scripts/addons/sverchok-master/core/sockets.py", line 56, in process_from_socket
2021-07-20 11:32:30,026 [ERROR] sverchok.core.main_tree_handler 131: 'NoneType' object is not an iterator

I managed to isolate the problem in my project
<img width="1116" alt="Capture d’écran 2021-07-20 à 11 32 02" src="https://user-images.githubusercontent.com/17178730/126299236-8152aba8-79cd-40be-bec7-afa7150b02f8.png">
I'm trying to send 2 random values 'longueur' and 'largeur', using the first SNL to give them min and max values.
The weird thing is the random value is set correctly if I connect only one set property
The error happens when I connect both of them, then only one value is set and it throws the error !
Help

**Comment by Durman** [comment]
Why not just to connect to the node with wires?

**Comment by mlevet** [comment]
Because my client wants to be able to separetely parameter the
randomisation / visualize the result of randomisation or sometimes ajust
the values after random

**Comment by Durman** [comment]
I'm not quite understand what are you trying to achieve in your layout by using `Set property` nodes.
The update system does not support such scheme and I don't see why it should yet.
Probably you can use wifi nodes instead?

**Comment by mlevet** [comment]
Ah ok !
it used to work very well with the previous version tho, I was able to send several random values through set property without any problem
my program just broke when i upgraded to 2.93 and sverschok last version yesterday
but yes i can try with wifi nodes instead

**Comment by mlevet** [comment]
mmm i'm checking the wifi nodes and there's no way i could still see my random value in a slider in that case

**Comment by Durman** [comment]
It just does not have sense to show socket property when it is connected.
Probably you can use muting links?
http://nortikin.github.io/sverchok/docs/tree_evaluation_system.html#muting-links

**Comment by mlevet** [comment]
damn that's a pity it used to work this way and not anymore
project is finished actually so i was just supposed to check it works with
the upgrade before delivering, not rebuild it :(
muting links seems weird in term of usability for the client
he just liked being able to visualise all randomisation parameters in one
place
and being able to see the values (or even adjust them) in the other box

I agree there's a dose of absurdity in the project but this is an art
project and i'm just trying to make it according to client ideas :)

**Comment by Durman** [comment]
You can use this release. It has previous update system and should work as you expecting.
https://github.com/nortikin/sverchok/releases/tag/vstable11

**Comment by zeffii** [comment]
seen as you are using Scriptnode, you could write a script to set the other Scriptnode inputs
```python
"""
in property_one s default=1.0 nested=2
in property_two s default=2.0 nested=2
"""
snlite = bpy.data.node_groups["LatheTable"].nodes["Scripted Node Lite.007"]
snlite.inputs[0].default_int_property = property_one
snlite.inputs[1].default_int_property = property_two
```
