### ISSUE TITLE
Vector Field Lines node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4238]
## Problem statement

![2021-07-23_14-26-35](https://user-images.githubusercontent.com/28003269/126769701-0c2b03ed-929d-4f31-b69b-1d16394c0fcd.png)

This tree is from our examples
Examples -> Fields -> Biological

**Comment by zeffii** [comment]
Perhaps we need to include a dependency list in the `.json` , this example requires `scipy`.

@Durman  also, the update system is going into an endless repeat on this example.

**Comment by zeffii** [comment]
inyerestingly , why is the dummynode not displaying missing dependencies
![image](https://user-images.githubusercontent.com/619340/167573799-156d6fb2-68f8-4caf-846f-134e64ffe25b.png)

**Comment by Durman** [comment]
It seems that the problem not in JSON import but that the node does not add itself into `utils.dummy_nodes.dummy_nodes_dict`

> Maybe if there are errors the live update should turn off?

A node tree can have multiple outputs what means that it steal can do useful job even when there are errors in the tree which block only some of the viewers.

> Perhaps we need to include a dependency list in the .json

I'm not sure what do you mean. Nodes themselves declare a dependency list and repeating it in a json would be redundant.

In general I think we can switch from complex registration system of dummy nodes to simply raising errors that a node requires some dependencies installed. In this particular case this error can be just placed somewhere in Sverchok utility submodule.

**Comment by zeffii** [comment]
> Nodes themselves declare a dependency list and repeating it in a json would be redundant

true enough. it is not needed to explicitly make a toplevel entry for dependencies in the json, the loader could still do a better job of warning about the dependency failures. case in point, you mark this thread as a bug in Field Lines node, but it is a missing dependency upstream issue.

> In general I think we can switch from complex registration system of dummy nodes

i would like to see something that works better than what we have now - it seems broken?

**Comment by Durman** [comment]
As I understand the current approach is to add a node to dummy list inside a node module

```py
import dependency

if dependency is None:
    add_dummy('SvSomeNode', 'Node Label', 'dependency')

class SvSomeNode: ...

register, unregister
```

The Vector Field Lines node just does not fallow the convention. I guess that when it is saved just in Blender file it won't be converted into a dummy node when the file will be opened in an environment without the dependency.

**Comment by zeffii** [comment]
we could hide json examples that have dependencies that aren't matched :)

**Comment by Durman** [comment]
I guess yes, because in this case user can try to replace the node with something else instead of installing the dependency.

**Comment by Durman** [comment]
For some reason I can't reproduce the problem any more 🤷‍♂️
