### ISSUE TITLE
"Post" option of "Get Objects Data"cannot handle hidden objects

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4243]
"Get Objects Data" node works fine with hidden objects untill I want it to apply Blender modifiers.
![no_Post(hiddenGeo)](https://user-images.githubusercontent.com/66558924/126860405-4c340c56-dd96-4cf7-9055-9025206b2dce.jpg)

When I enable "Post" option the "Get Objects Data" node does not output data.
![with_Post_enabled](https://user-images.githubusercontent.com/66558924/126860411-126c0529-8db4-4e2e-9cd4-9d1b98ca485d.jpg)

**Comment by zeffii** [comment]
This has to do with the Blender _dependency graph_ that we use to get the "final" mesh. If `Objects` are hidden I don't think we can get the final mesh.  I hope i'm mistaken.

**Comment by zeffii** [comment]
maybe you can tolerate showing just the Bounds/ bounding box 
![image](https://user-images.githubusercontent.com/619340/126862034-170e1c2a-f09c-4314-8179-c1a78fc40cb8.png)

**Comment by rendetto** [comment]
I'm using it exactly this way but when you have 10 overlapping objects the screen clutter is huge.

**Comment by zeffii** [comment]
https://docs.blender.org/api/current/bpy.types.Object.html?highlight=to_mesh#bpy.types.Object.to_mesh 
suggests limited versatility.. 
> Create a Mesh data-block from the current state of the object

same limitation as https://github.com/nortikin/sverchok/issues/4175#issuecomment-864444439

**Comment by zeffii** [comment]
it comes down to the following issue, which is `bpy` related:

- add a Cube and add an array modifier to it.. say with a count of 3 , so it makes 24 vertices. 

Then run this script in TextEditor. 
```python
import bpy

sv_depsgraph = bpy.context.evaluated_depsgraph_get()
obj = sv_depsgraph.objects['Cube']
obj_data = obj.to_mesh(preserve_all_data_layers=True, depsgraph=sv_depsgraph)

print(len(obj_data.vertices))

obj.to_mesh_clear()
```
it will print 24. 

- now hide the Cube object, and rerun the script. it will show this error
```python
KeyError: 'bpy_prop_collection[key]: key "Cube" not found'
```

**Comment by rendetto** [comment]
@zeffii Thank you for the clarification. I just found that if an object (which is not hidden) belongs to a hidden collection the "Get Objects Data" node outputs data even if Post is enabled.
![with_Post_enabled_HiddenCollection](https://user-images.githubusercontent.com/66558924/126878301-43b9c52e-b282-4f52-837a-8575739a2a09.jpg)
So it seems a valid cheat :)

**Comment by zeffii** [comment]
that's definitely unexpected, but great to know.

**Comment by zeffii** [comment]
i've updated the node's documentation to communicate this: https://github.com/nortikin/sverchok/blob/master/docs/nodes/scene/get_objects_data.rst

if you use this node a lot and think that the documentation can be improved, feel obligated/free to submit improvements :)
