### ISSUE TITLE
New update system time display location error

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4247]
![V~OF4CNJI_7KZKH %GHMB%Q](https://user-images.githubusercontent.com/74725748/126884625-be49a568-4cc1-4429-8cf8-297dacc48467.png)

Communicate with other users and understand that some people display normal and some display error

**Comment by Durman** [comment]
Can you elaborate the issue?

**Comment by vkter** [comment]
After the node is updated, the location where the update time is displayed is not above each node, but scattered, which is obviously difficult to judge the specific time of each node

**Comment by Durman** [comment]
Aaa.. I see. The thing is that there is no way to stick the text to nodes efficiently. To update position you can just make an attempt of link creation.

![triger_redraw](https://user-images.githubusercontent.com/28003269/126942533-1403c8d5-6995-4ffc-a4c3-4984b58b1969.gif)

The alternative is to put the message inside a node.

![2021-07-26_10-22-34](https://user-images.githubusercontent.com/28003269/126942651-3ecf7453-0e9d-49c5-a109-95011364d992.png)

@vkter Which message display is more convenient do you think?

**Comment by vkter** [comment]
https://user-images.githubusercontent.com/74725748/126945366-d55682c8-f5e8-4966-9214-a9b9ceb495d1.mp4

My question is, it doesn't seem correct. I've asked other users about this question, and some are the same as me

**Comment by Durman** [comment]
I will have a look.

**Comment by zeffii** [comment]
![moving_higher_res](https://user-images.githubusercontent.com/619340/126972388-dba658b5-36b0-4d67-91f4-239a0181303e.gif)

It depends on which screen the computer is displaying on, not just timer data is drawing in the wrong place, but also the exception.

**Comment by Durman** [comment]
@vkter Let me know if the problem was not solved.

**Comment by vkter** [comment]
The display is normal after updating again
