### ISSUE TITLE
Mesh View node crashes Blender with certain Material Index inputs

### ISSUE THREAD

**Issue by sna-scourtney** [nortikin/sverchok#4248]
## Problem statement

In Blender 2.93, I am attempting to create a single output object that has multiple material slots, using the Mesh View node to create the object.

Passing the geometry (vertices, edges, and polys) works correctly whether I provide vectorized input (that is, passing two lists into vertex socket, two lists into edges socket, two lists into polys socket), or if I use the Combine Mesh node upstream to get single lists for each socket.

This also works with the material index socket connected, so long as I only pass a scalar value to that socket or a list that is shorter than three elements. If I pass a scalar, then (as expected) the entire object will be one material. If I pass two different values, then the first poly is the first material and all others are the second (I think...I'm not sure exactly which poly is getting the first material). If I pass a larger set of input values to the material index socket, Blender crashes.

I discovered this by accident. At first I thought I should pass two material indices, one for each of the lists being passed to each of the other sockets. When that didn't work, I concluded that the node must be expecting a material index per polygon, so I added list repeater nodes to make that happen. That's when Blender crashed. I also found that no matter how many values are being provided, if one enables "wrap" on the input and causes too much list nesting depth, it also crashes Blender.

## Steps to reproduce

See above. I can provide a screenshot or example if requested.

## Expected result

Even if the materials were not assigned as I intended, the result should not be a Blender crash. :)

## Actual result

Crashed Blender.

## Sverchok version

Latest Sverchok version as of 2021-07-19, Master branch, via ZIP file downloaded from GitHub.

**Comment by Durman** [comment]
Can confirm the creash.
![2021-07-26_08-34-04](https://user-images.githubusercontent.com/28003269/126933446-89105101-d910-44a2-8657-90b9095b0ebc.png)
[untitled.zip](https://github.com/nortikin/sverchok/files/6875578/untitled.zip)
`Assgn material list` node is what you were looking for by the way.

**Comment by sna-scourtney** [comment]
Terrific! Thanks for fixing this so quickly.

Agreed about the Assign Material List node, which is in fact what I used to work around the crash. What I had been hoping to do was assign my materials in the Blender Material Properties, outside of the Sverchok panel, to simplify sharing my graph with colleagues. But adding Assign Material List in the node graph was the way to go, and it is working perfectly for me.

Again, thanks for fixing the crash so it provides an error message to the user instead.
