### ISSUE TITLE
"Solid Viewer" does not react to "Viewers" switch

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4249]
When I hide the layout via the "Show(Show this layout)" button the visual generated from the "Solid Viewer" node is still present in the viewport.
![solid_viewer_issue](https://user-images.githubusercontent.com/66558924/126892250-2c8c8935-a6bf-42a1-aea0-3007fb4b6a25.jpg)

I'm testing it in Blender2.93.2(win64), but the issue was also present in Blender2.92(win64).

**Comment by zeffii** [comment]
that should word @rendetto else reopen

**Comment by rendetto** [comment]
Thanks @zeffii  It kind of works now, but does not live update  - I need to press Re-update to trigger it.

How I can reopen the issue? I cannot find an option here.

**Comment by rendetto** [comment]
Oh well, I could just open another issue...

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/126894561-6694d77b-1420-4c99-ad90-1512ef0391a0.png)

it's possible that you don't see that button if i closed it..  but you opened it.

**Comment by zeffii** [comment]
> does not live update 

can you show a gid/screencap of what you mean?

**Comment by rendetto** [comment]
Weird.. I don't have such button. I do remember seen it in the past but now it's not present.

**Comment by rendetto** [comment]
Okay. I got it now. The one who closes an issue gets the "Reopen Issue" button - others don't :)

**Comment by Durman** [comment]
![2021-07-26_12-49-09](https://user-images.githubusercontent.com/28003269/126961306-36337fea-e8eb-45f5-b4cb-cfeb752ec2d4.png)

**Comment by rendetto** [comment]
I give up. It's gone again.
