### ISSUE TITLE
"Solid Viewer" does not "live" update

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4251]
@zeffii  I couldn't find an option to reopen the previous issue(https://github.com/nortikin/sverchok/issues/4249) so I'm creating a new one.

So it kind of works after https://github.com/nortikin/sverchok/pull/4250, but cannot live update - I need to press Re-update explicitly to trigger it.

**Comment by zeffii** [comment]
are you sayin that the node does not update the displayed geometry if the input socket data changes?

**Comment by rendetto** [comment]
Here how it looks:

https://user-images.githubusercontent.com/66558924/126897811-713ce805-0af6-426c-a85f-b3d157b86c03.mp4

**Comment by zeffii** [comment]
that's weird. but it does hide the `viewer draw`  node? in the background all this instruction does is remove the GL/Shader callback from the View3D. That part of the `viewer draw` and `viewer solid` are not significantly different.

**Comment by zeffii** [comment]
using 2.92 with the freecad from here https://github.com/nortikin/sverchok/issues/4082#issuecomment-840777774
i tested the solidviewer, and the new update system. worked.. can you confirm that it works for you in 2.92?
![shows_working_sv_show](https://user-images.githubusercontent.com/619340/126903574-23af9c24-aa09-4e36-acd6-775eb4323e2f.gif)

**Comment by rendetto** [comment]
Yes I can confirm that on Blender 2.92.0 with the latest Sverchok master it works fine.
It works fine also with Blender 2.93.1, and an older 2.93.2(candidate from Jul 19).
The problem was with a more recent 2.93.2 (candidate from 22 Jul) on a different PC.
Tomorrow I'll install the latest Blender 2.93.2 and report.

Anyways.. Thank you @zeffii it seems that it works fine on most of the recent Blender versions.

**Comment by rendetto** [comment]
So it seems that I already have the latest build (that one from July 19: blender-2.93.2-candidate+v293.9e64fd461ac3-windows.amd64-release). The daily build from today have the same signature. 

I don't know why the things didn't work on that other PC, but I consider this issue as resolved.

Thank you @zeffii ..and closing.
