### ISSUE TITLE
"CancelError()" is blocking the tree live processing

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4254]
This error occurred when I tried to Live Update a tree.
![Live_Update_Issue](https://user-images.githubusercontent.com/66558924/127391689-b59621f8-cff9-4330-bf71-927b96896cae.jpg)
The same tree is processed without problems when animated.
The tree was running with no errors with the previous update system.

The other weird thing is that this error appears very erratic and on different nodes. Is that normal? For example the next time I executed Live Update the left node didn't throw an error or red color, but the tree sill doesn't update.
![Live_Update_Issue_no_red](https://user-images.githubusercontent.com/66558924/127395811-3992cf17-4c42-40d1-93d2-1041cc2de772.jpg)
Here on another run of the Live Update I got this(tree still doesn't update):
![Live_Update_Issue_both_green](https://user-images.githubusercontent.com/66558924/127397020-af9df620-80e6-4663-9e53-a008802f807a.jpg)

I'm also a bit lost with those flashing colors of the nodes. What means red flashing and what green flashing? Why are those errors and how I have to read this info so I can debug the problems?
Thanks

**Comment by Durman** [comment]
The reason is this -

http://nortikin.github.io/sverchok/docs/tree_evaluation_system.html#triggers
![2021-07-29_08-05-39](https://user-images.githubusercontent.com/28003269/127429865-c84174df-9141-4fcb-afe2-137786d8d35c.png)

**Comment by rendetto** [comment]
@Durman I don't consider it low performance. With the previous update system I got 2.50fps which is good enough for the purpose of the tree. With the new update system the frame rate drops to 2.10fps, which isn't good but tolerable enough. Hopefully it will get better when you implement the update system optimizations. 

How can I skip these errors?

**Comment by Durman** [comment]
A tree to be fully evaluated by the Live update button should be evaluated less than 1/10 of a second. If performance of the tree is less then some parts of the tree will be ignored. 

To make the tree to be evaluated entirely you can switch off the Live update button. Alternative way is to simplify the tree by using Draft mode. https://github.com/nortikin/sverchok/pull/2861

**Comment by rendetto** [comment]
Well, I need the tree to behave exactly as it was before. It was pretty ok then. 
I just tried Draft mode and nothing changed - the tree is still not executing (the details are - it is executing some parts and others not). 
There is no option of simplifying it either, it's a complicated calculation, that is what it is, and it needs to run interactively - that's the sole purpose of it.

Can we have an option of skipping those kind of errors, so we can at least run the trees? 
I guess an update system shouldn't prevent an update when it is possible(even slower than a certain time threshold). 

Is it possible to implement a setting (some threshold value, say in milliseconds) that allows the tree to be executed regardless of the running speed?

**Comment by Durman** [comment]
First of all my understanding fo this feature is that user should be able to manipulate with scene elements. This is why I made the update cancelable. Otherwise user would not be able to interact with scene in case of a heavy tree. 

But now I think this feature can be really improved. Instead of cancelling a tree it's possible just ignore next event if the tree is still in progress. It seems it lets remain the scene interactive and in the same time the tree will be fully evaluated (just with more rare frequency)

**Comment by zeffii** [comment]
the live-update works best, as @Durman suggests, in a scenario where the nodetree can complete processing within the update-rate of the LiveUpdate operator. (think of this as the Live Update Frame Rate)  Which i set at an arbitrary rate from the very beginning not too fast, not too slow. It is possible to let the user control the rate of the live update, but it would need to be set by the user before triggering the operator, it can not be adjusted while the operator is running.

there are other solutions, having a higher default update-rate for the Operator, and letting the operator figure out if the nodetrees had enough time to update, if there are still calculations pending then the tree will not retrigger an update but instead skip an update-frame until the everything is computed. It would then be more like the original behaviour.

**Comment by zeffii** [comment]
we could even show the effective update-rate for that operator somwhere in the 3dview, like Blender does for animiate framerate

**Comment by zeffii** [comment]
i haven't had much time to understand the new update system, but if it can't be determined that a nodetree isn't ready, then the LiveUpdate operator could have a default fast update rate, and an additional slider for the user to configure the effective rate themselves.  More work for the user.. but it's a possibility.

**Comment by rendetto** [comment]
> But now I think this feature can be really improved. Instead of cancelling a tree it's possible just ignore next event if the tree is still in progress. It seems it lets remain the scene interactive and in the same time the tree will be fully evaluated (just with more rare frequency)

@Durman That will be great. This improvement will help a lot for cases like mine.

> i haven't had much time to understand the new update system, but if it can't be determined that a nodetree isn't ready, then the LiveUpdate operator could have a default fast update rate, and an additional slider for the user to configure the effective rate themselves. More work for the user.. but it's a possibility.

@zeffii Unfortunately I don't have the expertise to decide which one could be the best solution. I don't mind setting more options if I could get the results I'm onto.

Thanks

**Comment by zeffii** [comment]
looks like #4255 will handle this.

**Comment by rendetto** [comment]
> looks like #4255 will handle this.

I'm already on it. Just running some basic tests.
