### ISSUE TITLE
When open the preset panel, sverchok will be very stuck

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4256]
![image](https://user-images.githubusercontent.com/74725748/127498450-8f6b0258-ead3-4c00-a880-c32d585542e8.png)

1. Loading these presets seems to take up a lot of performance. Can you improve this situation

2. I hope to put these presets in one folder without occupying the whole screen at once

**Comment by Durman** [comment]
This is because a lot of folders are generated in this path and all of them (or most) are empty.
`User\AppData\Roaming\Blender Foundation\Blender\2.93\datafiles\sverchok\presets`

 What can be done is to make presets to ignore empty folders. I'm not sure though that this will fix little freeze.

**Comment by vkter** [comment]
After deleting the folder, sverchok will restore it again, and the link above seems to be invalid
