### ISSUE TITLE
Cyclic Cubic Spline Fails with 3 vectors

### ISSUE THREAD

**Issue by vicdoval** [nortikin/sverchok#4260]
Vector Interpolation (in Cubic Mode) and and Cubic Spline fail when inputting only 3 vertices with Cyclic is enabled 
![image](https://user-images.githubusercontent.com/10011941/127745010-df770921-c93b-4cf0-9351-53b6aaf01cc3.png)

**Comment by zeffii** [comment]
@vicdoval @portnov   what would the expect output be, a "prefect" circle ?

**Comment by zeffii** [comment]
or this?
```
            #print(describe_data_shape(vertices))
            if len(vertices) == 3:
                va, vb, vc = vertices[0], vertices[1], vertices[2]
                locs = np.array([vc, va, vb, vc, va, vb, vc, va, vb, vc, va])
 
            else:
                locs = np.array(vertices[-4:] + vertices + vertices[:4])
```
results in 

![image](https://user-images.githubusercontent.com/619340/169285251-e8fd2a4f-fc1a-480a-83fe-ae4d66ec87fe.png)
[experimental_cubic_snlite_2022_05_19_11_42.zip](https://github.com/nortikin/sverchok/files/8728743/experimental_cubic_snlite_2022_05_19_11_42.zip)

**Comment by zeffii** [comment]
@vicdoval  hope that is the desired result!
