### ISSUE TITLE
Sverchoks crashs always if i render an animation :(

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4263]
Sverchok seems to "always" crash, whenever i want to render an animation

Steps to reproduce
Just start Render animation of my demo file. It will crash.
 

Expected result
No Crash.

What did you expect to see as a result of those steps?
No Crash.

Actual result
A Crash.

https://www.dropbox.com/s/rloz73gg5kd1umd/sc_noise_vector_field.blend?dl=0

![image](https://user-images.githubusercontent.com/232549/128145808-e638af17-fbf7-4bbc-896a-639e1997c08d.png)

I am working on a Mac Laptop....

**Comment by Durman** [comment]
I can't reproduce the crash. Can you confirm crashing with latest Sverchok?

https://user-images.githubusercontent.com/28003269/128288744-4d6c805e-3a77-4df6-af38-c67a8e7d907e.mp4

**Comment by luckychris** [comment]
@Durman: did you test on a mac/macbook? Can i do something to support you to find my problem? crashlog? anything?

**Comment by luckychris** [comment]
what do you mean with latest sverchok? the latest stable release build?

**Comment by zeffii** [comment]
- the latest Master can be downloaded from [here](https://github.com/nortikin/sverchok/archive/refs/heads/master.zip)
    - it's pretty stable, and when installed it will update your sverchok to 1.0.0 from 0.6.0
- alternatively, the built-in Sverchok update button, should update to 1.0.0 too
    - general utils -> check for updates  ( see [here](https://nortikin.github.io/sverchok/docs/user_interface/panels.html#general-utils-panel) )

**Comment by luckychris** [comment]
looks like i am too dumb...do you mean this button? 
![image](https://user-images.githubusercontent.com/232549/128315888-bae0b4b3-e7c1-4304-8cef-0636837951b2.png)

If i press it it says: "no new commits to download"

**Comment by luckychris** [comment]
ok, i deleted sverchok and tried to install the newest beta and now i got: 

![image](https://user-images.githubusercontent.com/232549/128318011-275be092-9162-48bf-8d00-68c21f0b3a33.png)

**Comment by luckychris** [comment]
ok, i deleted sverchok, installed it again (11er stable) which shows version 0.6, then tried to update...nothing happened.

I made a video, so hopefully i made a dumb mistake and you can help me. Thank you!!!

Video: https://youtu.be/kMoLiyxYbXo

**Comment by Durman** [comment]
I was testing on Windows. The crash may be irrelevant to operating system or may not.))
Looks like update from the button does not work as it intended. The latest version is `1.0.0` now. It does not have its own release because it still is tested.
Usually Blender generate a text file after crash with information about Blender state. The path to the file you can find in system console. To open system console press Window (in main top menu) -> Toggle 
system console. Attach the file to the issue but better test the layout with `1.0.0` version first.

**Comment by luckychris** [comment]
if i follow this link here:

![image](https://user-images.githubusercontent.com/232549/128342943-be8ea7a6-cbc0-407c-a7dd-759ede29715b.png)

the version is 1.0.0 but i cannot install it.

error message:

![image](https://user-images.githubusercontent.com/232549/128342787-074b860a-22fb-4469-8d1b-284c7a3acb55.png)

**Comment by luckychris** [comment]
so i cannot update via update button and i cannot install the newest version :( I really love Sverchok and it is stable until i try to render an animation - and unfortunately it is with every animation....after a few frames it crashed. Until now no crash report, but i try to get one.

**Comment by zeffii** [comment]
there is a method to temporarily hardcode the download link used by Sverchok to get the latest zip for the "update".  It might let you upgrade from 0.6.0 to 1.0.0 . But the error you get is not something i've seen before, so there is no confidence in this statement.

in a running version of sverchok you may be able to change the download link manually this way. This must be run in the Blender TextEditor

```python
import sverchok
from sverchok.utils import sv_prefs

sv_prefs.set_vals(
    dload_archive_path="https://github.com/nortikin/sverchok/archive/refs/heads/",
    dload_archive_name="master"
)
```

then press `update Sverchok`, or execute this in TextEditor
```python
import sverchok
import bpy
bpy.ops.node.sverchok_update_addon()

```

**Comment by zeffii** [comment]
it looks like you are using Blender 3.0 ,  can you try Blender 2.9.3 ?

**Comment by vicdoval** [comment]
I have faced this issue in some projects, this have been the solution: https://github.com/nortikin/sverchok/issues/2390#issuecomment-492712076 and also baking geometry to shape keys (mentioned in the same issue)

**Comment by Durman** [comment]
> the version is 1.0.0 but i cannot install it.

Is the error happened when you are installing or enabling the add-on?
Do you disable previous version before installing new one?

**Comment by luckychris** [comment]
i removed sverchok before installing. The error happens when enabling.

**Comment by luckychris** [comment]
> I have faced this issue in some projects, this have been the solution: [#2390 (comment)](https://github.com/nortikin/sverchok/issues/2390#issuecomment-492712076) and also baking geometry to shape keys (mentioned in the same issue)

Thank you very much. That workaround works for me! At least i can render now without restarting rendering every 10th frame.

**Comment by luckychris** [comment]
> it looks like you are using Blender 3.0 , can you try Blender 2.9.3 ?

on 2.93 this error happens already when installing 1.0.0 alpha

![image](https://user-images.githubusercontent.com/232549/128407917-ebbd9d85-7818-4fef-8d81-8d14d0333916.png)

**Comment by luckychris** [comment]
> ```python
> import bpy
> import sverchok
>  
> from sverchok.utils.context_managers import sv_preferences
>  
> with sv_preferences() as prefs:
>     prefs.dload_archive_path="https://github.com/nortikin/sverchok/archive/refs/heads/"
>     prefs.dload_archive_name="master"
>  
> bpy.ops.node.sverchok_update_addon()
> ```

i tried your script - it ran without errors, but version stayed 0.6.

**Comment by luckychris** [comment]
after dozens of tests, i got 1.0 version successfully now installed on 2.92 and....tadaaa....animation rendering works here.

But i never got the 1.0 running for 2.93 or 3.0

**Comment by zeffii** [comment]
@luckychris 
>   it ran without errors, but version stayed 0.6. on both, 3.0 alpha and 2.93

yeah. that's a bit of a puzzle for me too.  The latest 3.0 Alpha builds of Blender are not considered stable, but 2.93 should work. Most of us use it.

**Comment by zeffii** [comment]
there's a bootstrap script (written 6 years ago..? ) that will help you install Sverchok on a fresh Blender installation.  All you do is paste this into the TextEditor, and hit run.

(ps, you manually set the version by changing `blender_version = 3.0` to `blender_version = 2.93` ,  (this could be automated too.. but it's very stormy here and maybe it's better to switch off my computer )
https://github.com/nortikin/sverchok/issues/669#issuecomment-894187550

**Comment by luckychris** [comment]
unfortunately your script threw an error on my macbook:

i got this error when running on my macbook:

Traceback (most recent call last):
  File "/Users/cd/Downloads/install_sverchok.blend/InstallSverchok", line 34, in <module>
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'


Error: Python script failed, check the message in the system console

**Comment by Durman** [comment]
@enzyme69 Do you have problem with enabling latest Sverchok (1.0) in Blender 2.93 or 3.0 on Mac?

**Comment by luckychris** [comment]
yes, on both

**Comment by Durman** [comment]
Do you still have any problems with rendering or enabling the add-on?

**Comment by luckychris** [comment]
In the Moment: no. And thanks To your advice with locking the Interface even rendering works!

**Comment by 0nzlo** [comment]
This comment helped me. https://github.com/nortikin/sverchok/issues/669#issuecomment-894635193
I downloaded Blender version 3.0.0 and it works

**Comment by Durman** [comment]
I have tested and Sverchok 1.0 works with Blender 2.93 perfectly. Make sure that you are using this file from the release.

![image](https://user-images.githubusercontent.com/28003269/174941733-2fdc0c97-66d9-4391-8b51-0e042e90403e.png)

**Comment by 0nzlo** [comment]
Hi, thanks so much for the quick reply. I was able to fix it using the
blender 3.0.0 version and it works perfectly
