### ISSUE TITLE
Points Inside Mesh issue

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4264]
## Problem statement

I did a simple test of the Points Inside of Mesh node and its behaviour looks strange.

1 Regular Mode. Very strange result.
![image](https://user-images.githubusercontent.com/2251298/128498606-04481fb7-ea71-4fa4-bc3b-60c79538ec7f.png)
![image](https://user-images.githubusercontent.com/2251298/128498648-36f810b9-245e-42ea-b4c8-157c0e1065e6.png)

2 Multisample Mode. 
![image](https://user-images.githubusercontent.com/2251298/128500181-962c8a73-0f57-467c-a8cf-7e73c5a7b411.png)

![image](https://user-images.githubusercontent.com/2251298/128500005-c8f571a5-9f43-4302-aa6f-05d5525ce0b0.png)
![image](https://user-images.githubusercontent.com/2251298/128500132-98a7e899-0d69-4c76-a759-4a161ab88c75.png)

Here is my Blend file:
[sv_building_gen_2.zip](https://github.com/nortikin/sverchok/files/6945041/sv_building_gen_2.zip)

## Steps to reproduce

1. Open My scene
2.  Select Points Inside Mesh Node
3. Check modes

## Expected result

Points shoud be inside of a mesh with a proper result.

## Sverchok version
Master

**Comment by zeffii** [comment]
the Mesh you are feeding it is a little bit outside of the usual scales that the node expects. In 3D calculations of "distance between points" it matters a lot that Blender is working with 32-bit precision numbers. 

similar to: https://github.com/nortikin/sverchok/issues/1622

points_inside_mesh probably needs an `epsilon` settings. to allow larger scene spaces.

**Comment by zeffii** [comment]
(you could prove this as a test, by hardscaling down your objects and points grid... ) eventually as you scale it down it will be more accurate.

**Comment by zeffii** [comment]
additionally, i can't see from the zip you linked to that you are also `transforming` the input mesh that comes out of the `GetObjectsData` node..
![image](https://user-images.githubusercontent.com/619340/128532422-32d35866-dd0f-4658-877f-27ce0153c1b3.png)

**Comment by zeffii** [comment]
and for example:
![image](https://user-images.githubusercontent.com/619340/128533018-172c0195-7526-44a2-b56f-8581218f6473.png)

[example_usage_points_inside_mesh_2021_08_06_15_17.zip](https://github.com/nortikin/sverchok/files/6946387/example_usage_points_inside_mesh_2021_08_06_15_17.zip)

i was mistaken, this doesn't appear to be related to scene scale, but the Object you are importing into Sverchok does have a subtle unapplied scale of 0.9, which needs to be taken into account.

**Comment by zeffii** [comment]
i don't really follow what's going on in the zipped blend you linked. that's why i broke the problem down to minimal representation of node. I suspect the problem may be in the logic/flow of your tree, rather than the points_inside_mesh node being the culprit.

**Comment by zeffii** [comment]
if the points you pass are _on_ or _very close_ to the faces of the mesh, then the there's some `precision` issues that can become problematic with [32-bit float point numbers](https://blog.demofox.org/2017/11/21/floating-point-precision/). There could even be debate about whether the node should consider points that are on the faces to be "inside",  topologically I would be inclined to reject them as not inside.

**Comment by mifth** [comment]
Thanks for the replies. Yeah, this is precision issue. Can we do something with it? If no then we can close it.

**Comment by zeffii** [comment]
looks like we have a small UI bug in the points inside mesh node, the enum has a space in it.

https://github.com/nortikin/sverchok/blob/8968f011da572b5fb5c2102bca8250c81d9e3686/nodes/analyzer/points_inside_mesh.py#L224-L232

**Comment by zeffii** [comment]
that mode should show precision `Epsilon` and multisample `Samples`

**Comment by zeffii** [comment]
i'll correct it

**Comment by zeffii** [comment]
you'll need to update sverchok,   1.0.0  : )

**Comment by mifth** [comment]
Thanks a lot, You are my savior!

**Comment by zeffii** [comment]
i think the precision factor should be visible in both 3d algorithms? both functions take epsilon parameters already, just the UI only exposes it in multisample mode..

**Comment by mifth** [comment]
At the moment I see it only in the Sample mode.

**Comment by zeffii** [comment]
while all potentially selected functions in that node have an epsilon input, only multi-sample mode seems to have effect if the input is valid. I'll leave it as it is, but try to improve the docs.
