### ISSUE TITLE
Question: what does Recalculate Normals node do?

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4265]
## Problem statement

Question: what does Recalculate Normals node do? there is no Normals output.

I assume Vertex Normals, Face Normals, Loops Normals.

![image](https://user-images.githubusercontent.com/2251298/128504297-7ca65956-e44c-4c57-8745-d1e0d2f65e33.png)

## Sverchok version

Master

**Comment by rendetto** [comment]
It's the same as Blender "Shift+N" command. You input mesh(verts,edges,faces) and get mesh(verts,edges,faces) with recalculated normals. Optionally you can mask the input.

**Comment by zeffii** [comment]
if you want the Normals of faces / verts / edges use "Component Analyzer"  
https://github.com/nortikin/sverchok/blob/master/docs/nodes/analyzer/component_analyzer.rst

**Comment by mifth** [comment]
Thanks. Closed.
