### ISSUE TITLE
In the new update system, the group will still be updated after the real-time update is cancelled.

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4270]
![image](https://user-images.githubusercontent.com/74725748/128627497-232b9a75-5848-42f2-aa56-36e105542dbd.png)

**Comment by Durman** [comment]
Yes, I did not implement this feature yet. 
Bytheway why do you like to use this because I'm not sure about usecase of this feature now?

**Comment by vkter** [comment]
For multiple relatively independent groups, I only want to update one, but now I will update all, which brings a huge burden when updating

**Comment by Durman** [comment]
Can you show example of a node tree?

**Comment by vkter** [comment]
![eee](https://user-images.githubusercontent.com/74725748/128793333-b4fdf95d-afbd-4ce9-99dd-071750a4d6a7.png)
In the figure, even if the update is closed, even if the upper group is updated, all will be updated. At this time, I just want to preview the above group, simply, I don't need the following group of repetitive operations.

**Comment by Durman** [comment]
If you are going to update those nodes with `Re-update all nodes` button then the group node with disabled live button will be updated any way.
