### ISSUE TITLE
[BUG] For Loop does not work Inside of other For Loop

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4278]
I've got a problem. I cannot use a Loop inside of a Loop

Here is my blend file:
[tmp1.zip](https://github.com/nortikin/sverchok/files/6968645/tmp1.zip)

![image](https://user-images.githubusercontent.com/2251298/129035081-41862e6c-c82f-4f50-a020-7ef99d79b411.png)

**Comment by Durman** [comment]
Here is a valid example of the nested loop. In your example the nested loop is not nested. It just executes before upper loop.
![2021-08-11_18-10-22](https://user-images.githubusercontent.com/28003269/129044526-a3ea41c9-ced9-4632-8011-a53437239120.png)
[untitled.zip](https://github.com/nortikin/sverchok/files/6969048/untitled.zip)

**Comment by Durman** [comment]
This is the code of how my example could look like.
```py
def loop_data(data):
    for item in data:
        yield [item]

data = [[0, 0], [1, 1], [2, 2], [3, 3]]
out = []
for item_number, item in enumerate(loop_data(data)):
    item = split(item)  # [[0, 0]] -> [[0], [0]]
    for nested_item in loop_data(item):
        nested_item = add(nested_item, item_number)  # [i + item_number for i in nested_item]
    item = join(nested_item)  # [[0], [0]] -> [[0, 0]]
    out.append(item[0])
```
Sverchok data structure can be difficult to understand in the beginning.
The loop node in for each mode only iterate over top level of lists (as it works in Python though). But it actually not only iterates over elements but also adds and removes their nestedness. It should be clear from the code above.

**Comment by vicdoval** [comment]
@mifth The Loop out input sockets (in the for each mode) will only get the first top element of the inputted list (to avoid adding extra [ ] to the output).
This is how you could get the 16 different numbers
![image](https://user-images.githubusercontent.com/10011941/129066219-c9c1fe53-ca77-4ca2-acc7-d7b25172a0aa.png)

**Comment by mifth** [comment]
Thanks for the replies.

I don't like this approach. I would even say that I'm disappointed by this system. What if I need to do 3 loops or 5 loops? This comes to big very dificulty to compose ranges on the start.

I hope there will be time for developers to rework for loop like in houdini or animation nodes. I'm very sad by the current system.

**Comment by mifth** [comment]
this is not user friendly system. I'm sad.

**Comment by vicdoval** [comment]
It is how its supposed to work

**Comment by mifth** [comment]
I would never guess that it should work like that. It's hardcore. Loop Out node should wrap to the list itself.
This is a big confusion for me. As a user I should not bother about wrapping.

**Comment by mifth** [comment]
Ok, I close it. There is nothing to do. But it's hardcore for users.
