### ISSUE TITLE
Socket menus and Blender 3.0

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4282]
## Problem statement

https://discord.com/channels/745273148018262158/771129565987995708/875790135294300190
![image](https://user-images.githubusercontent.com/28003269/129396365-16233d1b-eae1-4165-ab50-8a2650cd56a6.png)

No any errors in console.

**Comment by zeffii** [comment]
looks like `layout.menu()` is not happening inside `draw_button_menu` . yikes.

**Comment by zeffii** [comment]
it seems that poll isn't called in  `blender < 3.0`

**Comment by zeffii** [comment]
the weird thing is, this is called in Blender 3.0 and both node and socket return False. so the `draw` funcion of `SV_MT_SocketOptionsMenu`  isn't called.
```python
hasattr(context, 'node') --> False
hasattr(context, 'socket') --> False
```
https://github.com/nortikin/sverchok/blob/3ddac60701fb1676fe89fe74a7b446043543f36e/core/sockets.py#L96-L102

whereas in b2.93 the poll is not called?!  Removing that poll lets Blender 3.0 draw the `menu`.

**Comment by zeffii** [comment]
The poll may be redundant for that menu, seen as it is called only ever from inside 
https://github.com/nortikin/sverchok/blob/3ddac60701fb1676fe89fe74a7b446043543f36e/core/sockets.py#L287-L290
