### ISSUE TITLE
Upgrade Live update operator

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4283]
## Problem statement

https://github.com/JacquesLucke/animation_nodes/pull/1769#issuecomment-890803459
>  I used the scene update handler, but due to unknown reasons this handler was always executed. We only got a "real" scene changed handler reeelatively recently, using it sounds like a good idea.

Probably instead of timer the operator could use the scene changed handler. It would help to avoid useless updates (when nothing was changed). At least it's worth to experiment.

**Comment by zeffii** [comment]
live operator was only implemented as a timed event because there was no true scene update handler that could be relied on to trigger as desired.

so yes, an alternative would be great.

**Comment by Durman** [comment]
![scen update test](https://user-images.githubusercontent.com/28003269/129555362-8793f163-7f72-4808-ab85-0f337dedcc97.gif)

![scen update test2](https://user-images.githubusercontent.com/28003269/129555545-ea27ef50-b52f-4f28-b5bb-1d67eb85743e.gif)

**Comment by Durman** [comment]
I've tested the approach and workflow seems is much more comfortable than unsing a timer. There is though a problem of looping update events. The handlers can be triggered by Mesh viewer and even by changes of node colors it causes looping update events infinitely.
![scene handler](https://user-images.githubusercontent.com/28003269/129705919-20e328b3-8086-401f-ad04-1de53cf459d4.gif)

**Comment by Durman** [comment]
![scene update](https://user-images.githubusercontent.com/28003269/130007475-0b26f9bd-0cce-4b12-bb62-2878fe3f4dce.gif)

**Comment by zeffii** [comment]
i'll be interested to see how you solve the MeshViewer triggering the depsgraph_update_post handler. It's like the freeze/throttle thing again.

**Comment by Durman** [comment]
Yes, the problem is similar. I encapsulated solution inside update system. I just add a flug to a tree which was evaluated that it was recently evaluated and next event looks to the flag. If the flag exists the event removes it and finishes execution. It seems works.
