### ISSUE TITLE
Cyclic mode of Kinked curve node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4288]
## Problem statement

I guess angle parameter should not effect the cycle parameter.
![Cyclic curve](https://user-images.githubusercontent.com/28003269/129584269-f9f9f3f7-2422-4a4f-ac4f-7edb39ff387f.gif)
[untitled1.zip](https://github.com/nortikin/sverchok/files/6993310/untitled1.zip)

**Comment by satabol** [comment]
Hi @Durman .

Can you check fix #4998 ?

**Comment by satabol** [comment]
Hi @portnov!
Can you check fix #4998 ?
