### ISSUE TITLE
How to mute a node in Sverchok?

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4290]
In other node systems like Shader nodes or geometry nodes i can mute nodes with M.

In Sverchok this does not work for me. Is it another shortcut? I also cannot do this via menu.

**Comment by Durman** [comment]
Sverchok does not support muting nodes.

http://nortikin.github.io/sverchok/docs/tree_evaluation_system.html#muting-links

**Comment by luckychris** [comment]
this is sad. 😢 But thank you for your quick answer!
