### ISSUE TITLE
upgrade-sverchok-addon button fails to update 0.6.0 to 1.0.0 and from 1.0.0 onwards also silently fails.

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4291]
Sverchok version 1.0:

in Blender 2.93 -> show socket menu does work

in Blender 3.0 -> show socket menu does not work.

-> I am working/testing on Mac.

![socket_menu_not_working](https://user-images.githubusercontent.com/232549/129849652-05838fd6-b352-4617-8e7e-3a8273dbbaf2.gif)

**Comment by zeffii** [comment]
did you update recently? it was fixed a few days ago..

**Comment by luckychris** [comment]
yes, upgraded today by the great update buttons in sverchok. It is mac version....maybe that's the reason?

**Comment by zeffii** [comment]
shouldn't be.  The code that determines whether or not the menu is shown here:

https://github.com/nortikin/sverchok/blob/2be8ed9892e897f8fe0bc3cb284ac98b1be31916/core/sockets.py#L97-L106

if you look locally for that file `core/sockets.py` and the lines listed above, it should show the same code (without a `poll` function) .  if you do see a poll function, then the update feature might be broken.

**Comment by luckychris** [comment]
yep, i see the poll function.

**Comment by zeffii** [comment]
the `update` button and its functionality is not something that get much attention unless users notify us that it's broken. Sverchok devs use `git` to contuously synchronize Sverchok and all its branches with eachother.

I know for a fact that the current sverchok-software update fails to update from 0.6.0 to 1.0.0, so there is some bug to iron out.

**Comment by zeffii** [comment]
> yep, i see the poll function.
then it didn't update.

so the bug is not with the menu, but with the sverchok-add-on update

**Comment by luckychris** [comment]
i have already 1.0 now ;) but also there....looks like update button does not work 😢 i installed with your help to 1.0 via that "magic" script

**Comment by luckychris** [comment]
is there a magic update script too? for 1.0 ?

**Comment by zeffii** [comment]
remove all sverchok directories listed under `scripts/addons` and `scripts/addons_contrib` in any folder under `blender 3.0`  , then run that script .

when the script is run on a fresh Blender without sverchok folders (even if the alternative places that it looks..also those are linked in the other thread)  then the script will run.

but i'll investigate the sverchok-addon updater.. it would be useful to know wtf is going on.

**Comment by zeffii** [comment]
in the meantime, you can just comment out that poll function... or delete it so you are left with the same code as I linked above.

but obviously the Sverchok on your system will not update correctly until the cause of update-addon failure is identified.

**Comment by luckychris** [comment]
i just ran that script on Blender 3.0 and got

```
import re
import os
import zipfile
import urllib

import bpy
from urllib.request import urlopen

# 2.93  or 3.0  ... you don't need to set this manually anymore.
MAJOR, MINOR = bpy.app.version_file[0:2]
blender_version = f"{MAJOR}.{MINOR}"

baseurl = "https://gist.githubusercontent.com/zeffii/"
url = baseurl + "5a4440e7455940174ab9/raw/39fcbbd3692da87b920ab48fb2f6c664aca74af4/bootstrap.py"

def get_sv():
    print("getting sverchok bootstrapper")
    string_load = urlopen(url).read().decode()
    
    # depending on the current version...
    new_string_load = re.sub("version=(\d\.\d+)", f"version={blender_version}", string_load)

    svbl = bpy.data.texts.new('sverchok bootloader')
    svbl.write(new_string_load)
    print("obtained bootstrapper code from github")

    ctx = bpy.context.copy()
    ctx['edit_text'] = svbl  # specify the text datablock to execute
    bpy.ops.text.run_script(ctx)
    print("execution bootstrapper complete")

get_sv()

bpy.ops.preferences.addon_enable('INVOKE_DEFAULT', module="sverchok")
```




getting sverchok bootstrapper
obtained bootstrapper code from github
destination directory: /Applications/Blender.app/Contents/MacOS/3.0/scripts/addons/sverchok
failed to enable
execution bootstrapper complete
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'

Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'

Traceback (most recent call last):
  File "/Users/.../Downloads/install_sverchok.blend/InstallSverchok", line 34, in <module>
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'


Error: Python script failed, check the message in the system console

**Comment by zeffii** [comment]
OK.. it looks like the unzip generated a folder that wasn't called `sverchok`.   I will look into that.

in the meantime, it might be worth installing the add-on a different way. Seen as you are having troubles, maybe it's worth the extra 30 seconds to do it the oldschool way.

https://docs.blender.org/manual/en/latest/editors/preferences/addons.html

describes an alternative way to install addons. This is the way I install addons, so i can have one directory for all my 3rd party addons, and point both Blender 2.9+ and 3.0 at that directory.

- make a directory somewhere on a disk, called it `scripts`
- inside scripts have two folders
    - `addons`
    - `addons_contrib`
- unzip the sverchok folder
    - rename the resulting folder to `sverchok` if it has any excess names/version info.
- drop the sverchok folder into `addons_contrib` so you have
    - `scripts/addons_contrib/sverchok` 
- in Blender preferences, go to paths and set the `File Paths` field to the location of your scripts folder
- restart Blender

**Comment by luckychris** [comment]
just a silly question, maybe it has nothing to do with it...but in your downloaded script...

![image](https://user-images.githubusercontent.com/232549/129867520-e4fc0763-c068-44e2-b123-109aaca4521c.png)

there is 2.74 hardcoded....is this ok?

**Comment by zeffii** [comment]
it's hardcoded but gets rewritten, unless you are using an older script..... 

https://github.com/nortikin/sverchok/issues/669#issuecomment-894187550

**Comment by luckychris** [comment]
i just wondered that - using your magic script - in this folder (Blender/Applications) - it downloads still the "old" version with that poll function...

![image](https://user-images.githubusercontent.com/232549/129870658-78f2f33e-92bc-4ab1-8b69-b1216953657b.png)

**Comment by zeffii** [comment]
ok. but that doesn't make any sense. that's why you should try the alternative "by hand" installation method I describe above.

forget about scripts and the autoupgrade button for a while :)

**Comment by zeffii** [comment]
can you do a search on your HD for the following file `run_tests_win.bat` , it should be found only in sverchok folders. How many of such files is it finding and how many folders starting with the word `sverchok` do you have.

**Comment by luckychris** [comment]
i don't think that a .bat file works on mac....doesn't it?

**Comment by zeffii** [comment]
nope. just looking for a file that only `sverchok` folders will have.  you won't be opening it, just searching for it's presence.

**Comment by luckychris** [comment]
i have 4 times this file. All in the downloaded and unzipped vstable*versions

**Comment by zeffii** [comment]
There are three ways to install add-ons
1. using the `install from file` feature in `Blender/preferences/addons` 
2. placing the unzipped folder into `scripts/addons_contrib` to get `scripts/addons_contrib/sverchok/..` ,  
    - or instead of `addons_contrib` it can be `addons`,  but `addons` is really meant for Blender included addons. It's a formality, Blender doesn't care. It's not a problem once you know that's the distinction. The add-on can be placed in either, but not both.
    - for this method you can use the user defined `scripts directory` setting in `preferences/File Paths` , by pointing the `Scripts` field at the location of your own scripts directory.  Detailed [here](https://github.com/nortikin/sverchok/issues/4291#issuecomment-900933820)
3. using a [`bootstrap script`](https://gist.github.com/zeffii/a325ab87931114311198c4571322b82b), which does what 1 and 2 do but using python and bpy in a convoluted looking way.

----- 

i suggest you do one of two things regarding `(un)zipped vstable*` versions, and indeed all `sverchok*` zips/folders on your machine.
- remove them (they can always be downloaded again), or
- rename them from `whatever` to `_whatever` (adding an underscore character infront of the filename/foldername , so they don't interfere.

i have a computer beside me, non dev machine, with win10 and just Blender 3.0 , with not a single zip or folder of `sverchok*` on it. I made small cosmetic modifications to the [`bootstrap script`](https://gist.github.com/zeffii/a325ab87931114311198c4571322b82b), it downloads, unpacks, and enables sverchok no problems.   (but you might have to manually press the Refresh button in `Preferences/Add-Ons` , if it says it's missing.. it will enable automatically after hitting refresh)

**Comment by zeffii** [comment]
i'd like to keep the issue in this thread clear.

## primary issue
The upgrade mechanism is not working as expected. 

## secondary issue
It is unrelated to the bootstrap script (altho, the latest bootstrap script should work if you have no folders that start with `sverchok` in any of the locations that Blender is looking.

---------

i'll focus on the upgrade operator ( the thing that's triggered by hitting the `Upgrade Svechok addon` button ). To fix it first some hardcoding is needed :)

**Comment by zeffii** [comment]
@luckychris a slightly awkward realization is
- if you installed sverchok as sverchok-master and the folder is called sverchok-master inside `scripts/addons/..` , 
- then the upgrade button should work:
    - press it, 
    - let it do its thing and 
    - restart Blender after it says it's completed.

**Comment by zeffii** [comment]
i will find time to figure out tomorrow how to make it `folder-name-agnostic` , i don't think it was always this fussy.

**Comment by luckychris** [comment]
just downloaded latest zip from master, and it directly worked

even the update button worked

and....tadaaa....

![image](https://user-images.githubusercontent.com/232549/129955541-17ba671d-b68a-4bb6-bf41-59839fade91c.png)

circle with nurbs works too...so it's fine now ;) thank you guys for all your support

**Comment by zeffii** [comment]
while the issue was closed, i don't consider it fixed. The takeaway thoughts here are
- the upgrade mechanism seems to work if the sverchok dir is called `sverchok-master`
    - this is the default archive zip name that github provides for `master` 

two things that would be neat
- allowing users to set the branch for downloading specific branches
- allow arbitrary sverchok folder name.

the extraction process should:
- look at the current directory name
- make sure that the downloaded zip is extracted into the current directory (or somehow make sure it is renamed once extracted)

**Comment by zeffii** [comment]
the regex to find the current folder / current enabled name of the add-on
```regex
(sverchok)(-?[A-Za-z0-9\.]+)?
```
given
```text
C:\\Users\\zeffi\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\sverchok-master\\__init__.py
C:\\Users\\zeffi\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\sverchok\\__init__.py
C:\\Users\\zeffi\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\sverchok-vstable10\\__init__.py
C:\\Users\\zeffi\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\sverchok-vstable10.x.y.z\\__init__.py
```
finds
```console
Match 1
1.	sverchok
2.	-master
Match 2
1.	sverchok
2.	 
Match 3
1.	sverchok
2.	-vstable10
Match 4
1.	sverchok
2.	-vstable10.x.y.z

```

altho i imagine there are simples, less breakable ways to find the folder name.
