### ISSUE TITLE
nurbs curve circle -> no n points input field

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4292]
![image](https://user-images.githubusercontent.com/232549/129850462-e25e7a85-1797-43bf-a5c4-2ff365ec2c53.png)

I want to have this: nurbs curve circle -> with n points

but when i turn on "nurbs output"

![image](https://user-images.githubusercontent.com/232549/129850613-009f18d7-82b0-4468-bb53-3e2bf36e1512.png)
 
i don't get "n points" options. 

What am i doing wrong?

Sverchok: 1.0

MacOS

Blender 2.93 + 3.0

**Comment by Durman** [comment]
Try to remove and install Sverchok from zip file from main page.

**Comment by luckychris** [comment]
works with newest version
