### ISSUE TITLE
although i use the brute force script - my animation doesn't render correct

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4295]
![image](https://user-images.githubusercontent.com/232549/130006300-8e4b1374-db41-467f-834d-9d0fc8be6273.png)

I have this node setup, in which i change the spacing between 0 and .1.

If i let the animation run in viewport all is fine.

I am using now this brute force script you advised me:

```
import bpy 
file_path = '/tmp\\sverchok_animations\\'

start_frame = 1
end_frame =250

for act_frame in range(start_frame, end_frame + 1):
    bpy.context.scene.frame_current = act_frame
    bpy.ops.node.sverchok_update_all()
    bpy.context.scene.render.filepath = file_path + str(act_frame).zfill(4) +'.png'
    bpy.ops.render.render(write_still=True)
    print(act_frame)

print ('done')
```

but even then the spacing in the render output is not correct.

My problem is on MacOS.

Sverchok 1.0 (from yesterday)
Blender 3.0

blend file:

https://www.dropbox.com/s/8qjsbq95tzywzx2/sc_animation_render_problem.blend?dl=0

**Comment by Durman** [comment]
Yes this is known issue #4222
I'm currently waiting Blender devs answer to understand in which direction to move to fix this.

**Comment by luckychris** [comment]
> Yes this is known issue #4222
> I'm currently waiting Blender devs answer to understand in which direction to move to fix this.

Thank you, so i know i am not alone.... ;)

**Comment by vicdoval** [comment]
Did you try rendering it in Cycles?

**Comment by luckychris** [comment]
no, just eevee....but now i try...give me a few minutes

**Comment by luckychris** [comment]
sorry, cylcles needed a bit longer. But...unfortunately, no, doesn't work either.

**Comment by vicdoval** [comment]
crazy but if you plug a debug print  to the frame node then you can do the render using cycles and it works!!
![image](https://user-images.githubusercontent.com/10011941/130140403-4a2d4e4e-8c47-4cfb-99ee-69eb4eb84df0.png)

**Comment by luckychris** [comment]
> crazy but if you plug a debug print to the frame node then you can do the render using cycles and it works!!
> ![image](https://user-images.githubusercontent.com/10011941/130140403-4a2d4e4e-8c47-4cfb-99ee-69eb4eb84df0.png)

unfortunately on MacOS this does not work 😢

**Comment by vicdoval** [comment]
Did you try on 2.93?
And last idea:
Bake to shapekeys: 
https://github.com/nortikin/sverchok/issues/2390#issuecomment-492654519

**Comment by luckychris** [comment]
yes i tried - unfortunately i didn't work 😢

**Comment by luckychris** [comment]
i did not try that with the shapekeys...

**Comment by luckychris** [comment]
ok, i just tried it with the debug node with cycles but unfortunately this didn't work. I did not try the solution with the shapekeys.

**Comment by luckychris** [comment]
the only way i can render an animation with sverchok is by using view -> viewport render animations. This works and updates each frame. The "normal" render just renders the same frame over and over again.

**Comment by Durman** [comment]
Should be fixed now

**Comment by luckychris** [comment]
i just updated sverchok....and don't know why but had to delete and insert again my Voronoi on mesh and my lloyd on mesh nodes, because they were shown as red (i have no idea why), so i deleted them and reinserted them again...and hoped all....but unfortunately after hitter Shift-F12 (render animation) it crashes after the first frame was rendered. (EEVEE)

**Comment by luckychris** [comment]
tried the same in Blender 2.92 -> i didn't have to reinsert the 2 nodes, but it crashed after frame 3.

**Comment by luckychris** [comment]
test in 2.93.2: good news: yes, it does render the animation - currently on frame 82 without crashing, but bad news: it does NOT update the spacing...so it's pretty useless too 😢

**Comment by Durman** [comment]
The problem with crushing can be irrelevant to Sverchok.
There is two things I can think of which you can try to protect render from crushing. First thing is to change frame change handler to pre mode in Sverchok settings. And second you can try to enable Lock interface property before rendering.

**Comment by luckychris** [comment]
wow....lock interface did work! No crash, and the spacing changed. so...big thank you to you Durman!!! (tried on 3.0 alpha)
