### ISSUE TITLE
Stethoscope MK2 display bug

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4297]
## Problem statement

Long strings in a list seem to get divided into two strings each with their own ' ' marks. Please compare the Stethoscope output to the Text viewer output of the same input.

## Steps to reproduce

Feed Stethoscope a list of long strings

## Expected result

I expected to see a properly formatted list of strings

## Actual result

Long strings get split into two strings
![Stethoscopebug](https://user-images.githubusercontent.com/6302909/130106045-d1770df1-e336-43a4-a739-28b351a346dc.png)

**Comment by zeffii** [comment]
you can increase the `row` from 60 onwards..

**Comment by wassimj** [comment]
Duh! Sorry. I am still a newbie in #sverchok. Thanks!

**Comment by zeffii** [comment]
:)
