### ISSUE TITLE
weird circle curve issue

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4298]
I have this node setup and got some strange results at certain n points:

![image](https://user-images.githubusercontent.com/232549/130118023-4d0a63d7-8e01-4926-9b49-24f6a878c0a7.png)

![image](https://user-images.githubusercontent.com/232549/130118227-b81aa974-ef4e-4caa-9752-0f8d26b72ddd.png)
![image](https://user-images.githubusercontent.com/232549/130118271-ae0f1af7-fba6-4c6f-83d9-4919d7355650.png)
![Uploading image.png…]()

**Comment by portnov** [comment]
It seems to be a numeric precision issue.
I've added more details to the error:
```
 Knot vector items are not all non-decreasing: u[28] = 6.283185307179587 > u[29] = 6.283185307179586
```

**Comment by Durman** [comment]
I'm not sure that this message make understanding of the error better.))
It would be nice to add information into the documentation that this node expects not all possible values. It will decrease number of similar issues I think.

**Comment by portnov** [comment]
For this particular node, I fixed generation of knotvector so that it is always valid.
But the error message is generated in the underlying module, where the knotvector can be passed from anywhere.
