### ISSUE TITLE
Instances Sample - Dupli - Orient Along Path but with Curve?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4300]
[rotate_along_path_003.blend.zip](https://github.com/nortikin/sverchok/files/7024513/rotate_along_path_003.blend.zip)
<img width="1684" alt="Screen Shot 2021-08-21 at 9 58 03 am" src="https://user-images.githubusercontent.com/3952687/130303684-2ad5b1c8-0b15-401c-9b4e-2986abf6f51d.png">

I want to orient object instances along path for Geometry Nodes, in SV normally I use Duplicate Object Along Edge.

From my node setup above, is there a more elegant way to "resample" points of multiple curve using SVerchok? I usually use Zeffi macro for Grease Pencil to resample points.

But SV has Curve node too right? I am using letter "e" lowercase, and it has 2 curves, and if I want to process both curve at the same time, using Curve workflow, do we have Curve nodes that does:

Curve Input (multi curve object compound) -> Resample Curve with Length -> Make duplicate instance that orient with the curve.

**Comment by Durman** [comment]
I would do this in this way.
![2021-08-21_07-23-03](https://user-images.githubusercontent.com/28003269/130308930-fbf17cea-9b5a-44b1-83c9-264c52fdc4b5.png)
[untitled.zip](https://github.com/nortikin/sverchok/files/7024796/untitled.zip)

**Comment by enzyme69** [comment]
This is the way!!! Thanks again Durman, you rock!
