### ISSUE TITLE
On a Mac unable to follow install instructions.

### ISSUE THREAD

**Issue by KeithSloan** [nortikin/sverchok#4305]
## Problem statement

Unable to follow install instruction on a Mac - Please add to installation instructions

I have no User Preferences. I found preferences under Edit.

I go to Install with a download symbol and can locate sverchok-master in downloads but no idea after that. 
I don't see an Activate Flag as per the instructions.

## Sverchok version

28

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/d4151800e492e6fd5aa62079ffad00738bedaf4a

i've updated the installation instructions. They reflected older versions of Blender. Current `README.md` will be valid for all platforms.

**Comment by zeffii** [comment]
The other options are 
1. installing from a release zip
2. installing from a `cloned git repo` 
3. installing from particular branch

- currently if a user installs from a release, then the `upgrade feature` doesn't work automatically.
    - it can be made to work by renaming the folder inside the zip to `sverchok-master` , and then installing it.
    - this should be fixed internally.. hence adding it to a "breezy" installation document seems overkill.
- installing from a `cloned git repo` 
    - user must be somewhat familiar with `git`
    - in that case i recommend a dedicated scripts folder in Blender `File Path > Scripts` , 
        - and symlink the sverchok directory into scripts/addons_contrib/sverchok`  
- installing from a branch, has the same limitation as installing from a release at the moment.

**Comment by zeffii** [comment]
@KeithSloan  We only support Blender 2.93 onwards.

**Comment by KeithSloan** [comment]
Does NOT work for me. I am on Blender 2.93.

When I get to the bit about selecting the zip file. On my Mac is opens as though a directory and I do NOT see an Active Flag.

MAC OS is Catalina 10.15.7

**Comment by zeffii** [comment]
have you e

**Comment by zeffii** [comment]
have you ever installed an add-on from a zip for Blender?

**Comment by zeffii** [comment]
this may be a Blender bug, rather than specifically sverchok related.
is it related to this? https://developer.blender.org/T77962

video tutorial. https://youtu.be/LzdoUTvAgXk?t=16

**Comment by KeithSloan** [comment]
I have watched the video.

Have you ever used a Mac?

If you download a zip file on a Mac it automatically created a directory with the contents of the zip.

**Comment by zeffii** [comment]
> Have you ever used a Mac?

i've been around macs for 20+ years.

> If you download a zip file on a Mac it automatically created a directory with the contents of the zip.

well, you need to find the `sverchok-master.zip` , and select that from Blender's browser, and not the unzipped folder.

**Comment by KeithSloan** [comment]
I resolved by right clicking on the download link and selecting the appropriate download option.
The normal Mac download saves as a directory with the contents of the zip and there is no zip to be found, maybe this is different from 20 years ago.

**Comment by zeffii** [comment]
there are all kinds of ways to do that. 
https://apple.stackexchange.com/questions/961/how-to-stop-safari-from-unzipping-files-after-download#963

glad you solved it.

**Comment by enzyme69** [comment]
>
> Yes you simply zip back the uncompressed folder and install from the zip.
>
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
The readme now includes special mention of macos in the installation process. If this fails to satisfy the issue, you can comment below and i will reopen. (the issue does not need to be open to continue discussion)
