### ISSUE TITLE
#4305 is NOT resolved and I don't see how to reopen. Have added a comment to #4305

### ISSUE THREAD

**Issue by KeithSloan** [nortikin/sverchok#4306]
## Problem statement

Please describe your problem here.

## Steps to reproduce

1. 
2. 
3. 

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
let's continue on the original thread.
