### ISSUE TITLE
Stethoscope MK2 forces numeric string formatting

### ISSUE THREAD

**Issue by sna-scourtney** [nortikin/sverchok#4313]
## Problem statement

When displaying string data, the Stethoscope MK2 node implicitly formats its input, so the displayed data may not accurately represent the data. A specific example is that strings suffixed with ".001" (or any decimal followed by a numeric value) will have a zero added left of the decimal by Stethoscope. Debug Print confirms this is not the actual data.

## Steps to reproduce

1. Use a Formula node to create a list of strings, e.g., "[['TestOne','StringTwo','ItemThree']]".
2. Pass this list through a String Tools node to append the constant ".001".
3. Use Stethoscope (in text mode) to display the test data before and after the String Tools node.
4. Compare the Stethoscope output with Debug Print output.

## Expected result

For the example above, Stethoscope should output "[[['TestOne','StringTwo','ItemThree']]]" from before the append and "[[['TestOne.001','StringTwo.001','ItemThree.001']]]" after the append. Debug Print should show identical outputs.

## Actual result

Before the append, the result matches the expected for Stethoscope and Debug Print.

After the append, Stethoscope displays "[[['TestOne0.001','StringTwo0.001','ItemThree0.001']]]". Debug Print produces the expected output after the append.

## Sverchok version

Self-updated via its embedded updater as of 2021-08-28.

**Comment by zeffii** [comment]
agreed, this is a problem. i will fix it.

**Comment by zeffii** [comment]
i've made it so if you set rounding to `0`, then there is no formatting.
https://github.com/nortikin/sverchok/pull/4314

**Comment by zeffii** [comment]
it could be nicer, but it's meant for a quick and dirty inspection of the data being passed - it just happens that the edge case is indeed obvious in object names and their postfixes. this is a fair point.

**Comment by zeffii** [comment]
so if the user has already done some processing to get the object names only then you'll be able to do this
![image](https://user-images.githubusercontent.com/619340/131255821-ad0808f0-d9ca-41cb-a57f-db0649be1db7.png)

originally i was only seeing object names with their full path
![image](https://user-images.githubusercontent.com/619340/131255911-900de7d0-3509-4093-a279-cd10489b6da0.png)

as you can probably see in the code in the stethoscope,  if a line contains `bpy`, then stethoscope will do no formatting.

**Comment by zeffii** [comment]
hope that's OK for now, it's tempting to do some introspection of the string and detect if the string represents something similar to object names so a regex would find if the pattern of a string is 
```regex
(\w+\s?\.\d+)
```

**Comment by sna-scourtney** [comment]
> it could be nicer, but it's meant as a quick and dirty inspection of the data being passed - it just happens that the edge case is indeed obvious in object names and their postfixes. this is a fair point.

Agreed on all points, and thanks for the fix. I would not have been as concerned about this except that Blender itself uses that suffix for name deduplication.

**Comment by sna-scourtney** [comment]
> hope that's OK for now, it's tempting to do some introspection of the string and detect if the string represents something similar to object names, regex is one option..
> 
> ```regexp
> (\w+\s?\.\d+)
> ```
> 
> but for simplicity maybe not, because Blender permits many permutations of the `prefix` of the object name.
> maybe a simplest automatic approach would be if the string contains a mix of alphanumeric and decimals, then don't format.

Thinking this over, I'd agree with your reluctance to over-complicate the node. Too much "intelligence" in a diagnostic node is likely to be confusing. The solution you provided as "OK for now" is, I think, actually a pretty good permanent approach. Provide an easy way ("Set rounding to zero") for the user to entirely disable the node's string formatting, and document this option (again, as you've done), and we have a very easy way to get the "raw" string output needed for troubleshooting graphs.

As far as I'm concerned, you've solved this quite elegantly. Thanks!
