### ISSUE TITLE
How to visually display a warning on a node

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4315]
My code does the following:
```
def processItem(cells):
	cellComplex = cells[0]
	for i in range(1,len(cells)):
		try:
			cellComplex = cellComplex.Merge(cells[i], False)
		except:
			raise Exception("Error: CellComplex.ByCells operation failed during processing the input Cells")
	if cellComplex.GetType() != 64: #64 is the type of a CellComplex
		warnings.warn("Warning: Input Cells do not form a CellComplex", UserWarning)
	return fixTopologyClass(cellComplex)
```
How can I display that warning visually in the GUI (perhaps by changing the colour of the node and/or display the warning text? Is there a standard way to do it?

**Comment by Durman** [comment]
There is no way to display warnings now, only errors. It could be useful to have such feature but I'm not sure about real example of using this feature.

**Comment by zeffii** [comment]
if it's vital to user friendliness there are still options using a few bpy features. One thing you could do in the meantime is:
- give your nodes a `show_warning: StringProperty()` property (without an explicit update function, default="").
- in your warning state, you set `node.show_warning = "your message"`,  and else `node.show_warning = ''`  (reset it to empty string)
- in the `draw_buttons` function you have a line
    ```python
    if self.show_warning:
        row = layout.row()
        op = row.operator("node.sv_topo_custom_warning_operator", icon="QUESTION", text="")
        op.arg = self.show_warning
   ```
- and you set up `node.sv_topo_custom_warning_operator`:

    ```python
    class WM_OT_svtopo_tooltip(bpy.types.Operator):
        bl_idname = "node.sv_topo_custom_warning_operator"
        arg: bpy.props.StringProperty()

        @classmethod
        def description(cls, context, properties):
            return "Arg is: " + properties.arg
    ```

then what happens is, you set your node into a warning state, you set `show_warning` to some informative statement, `show_warning` evaluates to true in the `draw_buttons`, and displays a questionmark+button, The user can hover over the question mark and the tooltip will be equal to the string you passed into `show_warning`.

i'm not saying this is an elegant solution, but it might be useful.

**Comment by zeffii** [comment]
so here's a small demo a do_nothing node.

```
# demo do nothing node

import bpy
from bpy.props import StringProperty

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import node_id, updateNode

class WM_OT_svtopo_tooltip(bpy.types.Operator):
    bl_idname = "node.sv_topo_custom_warning_operator"
    bl_label = 'Warning:'
    arg: StringProperty()

    @classmethod
    def description(cls, context, properties):
        return properties.arg


class SvDoNothingNode(bpy.types.Node, SverchCustomTreeNode):
    bl_idname = 'SvDoNothingNode'
    bl_label = 'Do Nothing'
    bl_icon = 'VIEW_PAN'

    show_message: StringProperty()

    def sv_init(self, context):
        self.inputs.new('SvStringsSocket', 'A')
        self.inputs.new('SvStringsSocket', 'B')

    def draw_buttons(self, context, layout):
        row = layout.row(align=True)
        if self.show_message:
            row.alert = True
            row.enabled = False
            op = row.operator("node.sv_topo_custom_warning_operator", icon="QUESTION", text="")
            op.arg = self.show_message

    def process(self):
        self.show_message = ""

        if not all([s.is_linked for s in self.inputs]):
            self.show_message = "Socket A and B must be linked"



classes = [WM_OT_svtopo_tooltip, SvDoNothingNode]
register, unregister = bpy.utils.register_classes_factory(classes)

if __name__ == "__main__":
    register()



```

**Comment by zeffii** [comment]
the upside to using a tooltip are, to name a few:
- you can fit a lot of text into it
- it doesn't reshape the node significantly, as opposed to trying to cram a full message into the node ui
- uses available bpy layout API, it can be tweaked to some extent
- if we really wanted, this could be socket specific (so drawing the socket row by prepending the tooltip button before the socket name), 
    - this will meet resistance, and i don't think it's a good idea for simplicity sake.... but it's possible. the `box node` already implements it.
         - ![image](https://user-images.githubusercontent.com/619340/131311919-acd59243-9b9c-4382-9eef-c95caa4890d7.png)


downside, 
- is not consistent with Exception messages, with draws the messages directly to the nodeview pixels.
