### ISSUE TITLE
[HELP] can't find Text to Mesh node

### ISSUE THREAD

**Issue by chiboreache** [nortikin/sverchok#4328]
can't find Text to Mesh node, please halp!

**Comment by zeffii** [comment]
there is a Typography Viewer node, which should output Blender Curve/Font objects into the Blender scene.

but it seems a little broken at the moment..

**Comment by zeffii** [comment]
well, it's not completely broken . you do have to set the Font type manually at the moment, ( this setting is in the N-panel, inside the Node tab, properties ->  Font (at the bottom).

![image](https://user-images.githubusercontent.com/619340/132575665-e5c00d39-b35c-4652-87b2-3c3503a4ef5d.png)


![image](https://user-images.githubusercontent.com/619340/132575539-d032a4df-7bed-4332-a690-ab2aa060bfa6.png)

**Comment by zeffii** [comment]
The situation is
- input text
- pass it to Typography Viewer  (TV node above)
- convert from proper Curve/Font object to mesh using `Get Objects Data`, this outputs Verts / Edges / Faces ..etc.

I added the Objects output socket to Typography Viewer just a few minutes ago, you will need to update Sverchok to get the updated Node. If you already have a Typography Viewer node in the scene you can delete it and add it back.

**Comment by chiboreache** [comment]
oh wow, got it, thanks!

what about Text SVG node?

**Comment by zeffii** [comment]
TextSVG is a different matter. SVG describes a markup (xml) document, which tells the document viewer to render Text of a given typeface at size etc. The SVG document contains no information about the Glyphs, so can not arbitrarily return Mesh from SVG (like Typography viewer can).

**Comment by chiboreache** [comment]
understood, thanks again
