### ISSUE TITLE
Extrusion inside Typography Viewer produce separated geometry

### ISSUE THREAD

**Issue by chiboreache** [nortikin/sverchok#4330]
merging by distance won't help

<img width="1162" alt="Screenshot_20210909_034856" src="https://user-images.githubusercontent.com/16459251/132604304-e656956d-ca02-461c-b1eb-774627fbcea1.png">

**Comment by chiboreache** [comment]
solution: extrude region

<img width="978" alt="Screenshot_20210909_034943" src="https://user-images.githubusercontent.com/16459251/132604373-b40b97d1-a464-4fd6-90f8-f9b0105b4528.png">

**Comment by zeffii** [comment]
there's also the built in extrude for font objects.

![image](https://user-images.githubusercontent.com/619340/132664742-91d57143-767d-4a59-a102-26c4a141a7cd.png)

**Comment by chiboreache** [comment]
yeah i know, but as i mention it in OP post - i can't get separated(by letter) joined meshes out of it

**Comment by zeffii** [comment]
oh i see. oops. yes. I failed to read that correctly. I think the problem here is the order in which you do the post processing. 
- first merge by distance   (the precision will need to be dynamically set if your fontsize changes..)
- then separate loos

![image](https://user-images.githubusercontent.com/619340/132888400-a7cfdf42-a83b-4200-9668-0882b947e910.png)

**Comment by zeffii** [comment]
pitty the Font Curve object's extrusion is separate by default and can't be optionally joined in the `.to_mesh` API call.

**Comment by zeffii** [comment]
because others will find this, here's something you might come across. The matrices from bounding box will return the boundary of the glyphs individually

![image](https://user-images.githubusercontent.com/619340/132942101-f46406f4-5834-47db-be33-be9540f69f1e.png)

**Comment by chiboreache** [comment]
@zeffii 

eh..

<img width="1312" alt="Screenshot_20210924_153153" src="https://user-images.githubusercontent.com/16459251/134674642-858a6a14-d151-4314-ab47-cc9ca07370c8.png">

**Comment by chiboreache** [comment]
> * first merge by distance   (the precision will need to be dynamically set if your fontsize changes..)

works perfectly fine, thanks!
