### ISSUE TITLE
Arc 3pt (Curve)

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4339]
## Problem statement

I have reason to assume that the node worked with the data before but now it does not.
[untitled1.zip](https://github.com/nortikin/sverchok/files/7141323/untitled1.zip)

![2021-09-10_08-48-33](https://user-images.githubusercontent.com/28003269/132801293-a92d1ee4-75e8-4493-a628-97ba5d8186fb.png)

```
Exception: Plane -9.276168823242188x + -0.005710601806640625y + 1.2683038711547852z + 355.2114353731231 = 0 does not intersect with line (x - 49.613712310791016)/-0.0006159423501230776 = (y - 0.03056362085044384)/0.9999998211860657 = (z - 0.5974085927009583)/-7.416684638883453e-06
```

**Comment by Durman** [comment]
Broken in this commit 080337b9cd06312facd65ce818c29c62213ccb98

**Comment by portnov** [comment]
Specified line is (at least almost) parallel to specified plane.
Why is it important in this case?... will check...

**Comment by portnov** [comment]
I see. In this particular case it simply means that radius of circle to be generated is too big. Will think how to better lift this restriction.

**Comment by portnov** [comment]
For now, just adjusted default value of min_det.
