### ISSUE TITLE
SvMeshSelectNode does not work properly

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4340]
## Problem statement

[untitled1.zip](https://github.com/nortikin/sverchok/files/7142680/untitled1.zip)
![2021-09-10_13-08-08](https://user-images.githubusercontent.com/28003269/132830142-3f318e4d-efd6-4e44-9e8c-a7a9c0914aa5.png)
Expecting result according to the documentation.
![2021-09-10_13-08-08](https://cloud.githubusercontent.com/assets/284644/23761372/cc0950b6-051c-11e7-9c57-4b76a91c2e5d.png)
Also there is an error if to connect edges

```
  File "\sverchok\old_nodes\mesh_select.py", line 140, in by_normal
    vertex_normals, face_normals = calc_mesh_normals(vertices, edges, faces)
  File "\sverchok\utils\sv_mesh_utils.py", line 539, in calc_mesh_normals_bmesh
    bm = bmesh_from_pydata(vertices, [], faces, normal_update=True)
  File "\sverchok\utils\sv_bmesh_utils.py", line 89, in bmesh_from_pydata
    add_face(tuple(bm_verts[i] for i in face))
TypeError: faces.new(...): sequence incorrect size, expected [3 - -1], given 2
```

**Comment by zeffii** [comment]
just to be clear here. The fault exists now in the old node (`SvMeshSelectNode`) and not the replacement `SvMeshSelectNodeMk2`

**Comment by zeffii** [comment]
in old SvMeshSelectNode
```diff
-vertex_normals, face_normals = calc_mesh_normals(vertices, edges, faces)
+vertex_normals, face_normals = calc_mesh_normals(vertices, faces)
```

**Comment by Durman** [comment]
Still does not work
[untitled1.zip](https://github.com/nortikin/sverchok/files/7147128/untitled1.zip)

![2021-09-11_07-12-17](https://user-images.githubusercontent.com/28003269/132934344-9b3383eb-58c9-4df7-9463-f900f9e581f2.png)

My opinion is that there is no sense of having old nodes if they does not work.

**Comment by zeffii** [comment]
why is the deprecated node outputting 386 mask items, where the box only outputs 384 polygons

**Comment by zeffii** [comment]
i guess the reason to keep the old node is so that users can rightclick and replace it? : )

**Comment by zeffii** [comment]
it may not be ideal to modify code of nodes directly before putting them into `old_nodes` / deprecating them, i think that's what happened here.

**Comment by zeffii** [comment]
```
        vertex_normals, face_normals = calc_mesh_normals(vertices, edges, faces)
```
should be
```
        face_normals, vertex_normals = calc_mesh_normals(vertices, faces)
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/4348  makes it not b0rked. hope you can confirm @Durman

**Comment by Durman** [comment]
Now it seems works!

> i guess the reason to keep the old node is so that users can rightclick and replace it? : )

Yes, one of the reasons. But it only works in case if some functionality of a node was extended like new output socket was added (though I guess that now we know how to handle such cases without creating a new node version). If new version changes functionality of the node then replacing probably will not bring expected result (probably it has sense to revise our Alpha and Betta nodes categories).

I think the problem with particular this old node is that it uses some external modal. There were made changes without consideration of possibilities to effect the dependent old node.
