### ISSUE TITLE
Vector interpolation

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4349]
## Problem statement

[untitled1.zip](https://github.com/nortikin/sverchok/files/7153054/untitled1.zip)
![2021-09-13_13-14-50](https://user-images.githubusercontent.com/28003269/133057805-78e2b97c-da4f-473c-a897-cd2b7c521073.png)

```
sverchok.utils.geom:283 : list indices must be integers or slices, not tuple
```

**Comment by Durman** [comment]
Breaking commit c6a2b211a43e76660ec5aa3f7753d9112f814223

**Comment by zeffii** [comment]
that's weird.
```diff
-    t_r = t_in[:, np.newaxis] - tx
+    t_r = np.column_stack((t_in, t_in, t_in)) - tx
```

**Comment by zeffii** [comment]
looks like `t_in` isn't an np.array 
```diff
- out = spline.eval(t_corr)
+ out = spline.eval(np.array(t_corr))
```
