### ISSUE TITLE
Viewer Draw - Alpha channel bug

### ISSUE THREAD

**Issue by chiboreache** [nortikin/sverchok#4354]
Alpha is lost in viewport after you change something in node graph

<img width="181" alt="Screenshot_20210924_213619" src="https://user-images.githubusercontent.com/16459251/134724364-ef392200-3db7-4d33-a1cf-e28d4690c329.png">

**Comment by Durman** [comment]
Can't confirm, though there are some glitches.

https://user-images.githubusercontent.com/28003269/134763327-2407d00f-eb20-47e9-aa4c-a7febf778fff.mp4

**Comment by zeffii** [comment]
@chiboreache 
maybe you can share a simple blend here ( drag n drop a zipped blend into these comment boxes) that demonstrates the loss of an alpha channel. Alpha-channel support is a late addition to the viewers, I'm surprised it works as well as it does. 


If we wanted to correctly handle alpha channel and alpha-mixing of several Viewer Draw nodes, this would require a different approach (client-server + preprocessing). Rendering with transparencies is a next-level step for any renderer. Right now you are better off using MeshViewers and assigning materials and using real-time viewport rendering (eevee/cycles) if you want accurate transparency mixing.

i've always considered the viewer draw as quick'n'dirty visualizer tools, but its clear that it would be nice to have something that is qualitatively in between ViewerDraw and a simple Blender renderer. eg; relatively fast as VD but without creating real geometry+materials as Meshviewer.

As europe is quickly cannibalizing itself i'm not sure i'll have time to enjoy contributing to that.

**Comment by chiboreache** [comment]
> Can't confirm, though there are some glitches.

even on your video

when you moving inner cube - outer cube alpha is going back to full opaque

**Comment by Durman** [comment]
Now I see what you are point at. I will classify this as not implemented feature.)) I guess supporting this can impact on the performance of the node so this problem should be investigated first.
Ideally the Alpha chanel should be removed from the properties until it will get the support.

**Comment by zeffii** [comment]
> Ideally the Alpha chanel should be removed from the properties until it will get the support. 

don't remove it, it's still useful even if imperfect. A mention in the documentation regarding the artefacts would be a better short term solution.

**Comment by zeffii** [comment]
it's not a bug, it's a feature of quick n dirty nature of the Viewer Draw.  I fear it will stay this way until we can execute graphics routines that are not interpreted at runtime.
