### ISSUE TITLE
Question : Attractor Field with multiple points?

### ISSUE THREAD

**Issue by rwny** [nortikin/sverchok#4355]
i use Attractor Field with multiple points, (point from 2 circle)
problem at intersection of 2 circle  value is add to each other.
how can i make it same height?
Thank you very much.
![Screenshot 2021-09-28 111916](https://user-images.githubusercontent.com/32074126/135022603-0969371c-136b-4879-b942-f9fe74c088a0.jpg)
![Screenshot 2021-09-28 112319](https://user-images.githubusercontent.com/32074126/135022919-2b55905d-85a6-49c4-9258-5881c92325b3.jpg)

[wall001.zip](https://github.com/nortikin/sverchok/files/7241004/wall001.zip)

**Comment by portnov** [comment]
I think, in your case, you want two attractor fields, one from each circle; and then join them with "Join scalar field" node...

Btw, "Attractor field" node has a special mode for generating attraction field of a circle, it should work faster than generating a number of points and then calculating the field of each of them.

**Comment by rwny** [comment]
Thank you very much . 👍 
![Screenshot 2021-09-28 121817](https://user-images.githubusercontent.com/32074126/135027548-82a6af8b-e449-4dd6-8b60-040599bff09a.jpg)
