### ISSUE TITLE
Typography Viewer

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4356]
## Problem statement

It creates text object without applied default font.
![2021-09-29_20-53-49](https://user-images.githubusercontent.com/28003269/135314290-af221369-b764-432e-b00e-2857c17dc320.png)

Breaking commit e8453398aa783bfdd21dff32d027fe5f28f5f61a

**Comment by zeffii** [comment]
should do it https://github.com/nortikin/sverchok/commit/7ee11145c7756646121b85296fc3d9e45f9fb65e
