### ISSUE TITLE
Icosphere TypeError: create_icosphere keyword "diameter" is invalid 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4357]
<img width="728" alt="Screen Shot 2021-10-10 at 12 18 03 am" src="https://user-images.githubusercontent.com/3952687/136659371-8ae8cee2-62d3-46a3-934b-036b48d57f86.png">

_keyword diameter invalid for this operator_

**Comment by zeffii** [comment]
the issue here is that Blender master since 28 days ago has renamed that parameter "Diameter", but was for several years before that named "Radius".
https://github.com/blender/blender/commit/9b2b32a3338d873529a9b2c402feae4e9d25afdf

it's an essential node, so i'll fix it asap.

**Comment by zeffii** [comment]
ok tested, seems to work. with the correct real-world radius

**Comment by Gooberinoo** [comment]
please help me im having a similar error create uv sphere keyword diameter is invalid for this operator
