### ISSUE TITLE
Location of custom defaults path Seem ineffective

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4360]
![image](https://user-images.githubusercontent.com/74725748/136888271-8256994b-0b00-435a-87ea-d5eddc6d007a.png)
There seems to be no effect after the path changes.

**Comment by zeffii** [comment]
correct, the property has no update function associated with it.  see.

https://github.com/nortikin/sverchok/blob/671e27feaf36cb5f04e5db4869a89ff0a380d04c/settings.py#L370

if you look at the current codebase, this parameter is orphaned. ( it appears only once in the codebase - namely at the location where it is defined as a property )

https://github.com/nortikin/sverchok/search?q=defaults_location

An early version of "custom defaults" was implemented something like 5 years ago by me, then reimplemented lateron by @portnov ( i think ) - In version b28+ Sverchok 1.0.0 only the new implementation survived, it is more versatile. 

This path property is not used, and can be removed. It's possible that it was only ever used (in my implementation) as a way for the user to see the location of custom defaults file.
