### ISSUE TITLE
how to understand inputs in Scalar Field Formula and vector field formula？

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4367]
![image](https://user-images.githubusercontent.com/74725748/137708620-af378f38-63e4-49a7-9924-f272e96da54b.png)
I read the decuments but i stil don't understand it, the input field invalid

**Comment by zeffii** [comment]
first it's useful to know that a Field Vector socket and a Field Scalar socket pass two different types of data.  Attaching to a default output to illustrate the data being passed. (We should have nicer ways to show this, but usually it's not relevant to the user)
![image](https://user-images.githubusercontent.com/619340/137715759-2d5607a2-c799-4268-a9af-42cf8f75748c.png)

A Scalar field is at heart a _formula_ (or "function") that returns a scalar value for all valid positions of a field. For example for any 3D point inside a given cylinder you could generate a `scalar` value.
A Vector field is the same, but it returns a Vector instead.

# Scalar Field 

![image](https://user-images.githubusercontent.com/619340/137719857-9d84612f-3a13-4eff-83fc-6a92d15b3ede.png)

here i'm displaying the `Scalar` result of the formula/function at each of the given input Vectors. To reinforce this i'm displaying a sphere which is scaled by the scalar, also at each of the given input Vectors.
