### ISSUE TITLE
Control density of distributed vertices

### ISSUE THREAD

**Issue by MedleMedler** [nortikin/sverchok#4368]
As a beginner I was wondering, how I can distribute vertices (vector in?) on a surface plane in a random (noisy) but controlled way. 

Like emitting particles from a texture. White area of this texture will give a dense density of vertices and dark areas of this texture will give a low/no density. So I want to control the density of the distribution and preferably with a texture (or weightmap).

Can anyone help me with this fantastic addon?

**Comment by Durman** [comment]
Also image field node can be used I guess
http://nortikin.github.io/sverchok/docs/nodes/field/image_field.html
But I'm not sure how to make mapping between image and a surface.

**Comment by zeffii** [comment]
another, probably less efficient - but whatever - , approach is to use Image Decompose, and scale the Z value of vertices of the image based on their Hue (or other property of the color of a pixel of the input image ). Transform Z values of vectors based on some formula, so vertices become separated more in 3d space, then apply some "Merge by Distance". Then apply the voronoi to a domain.

![image](https://user-images.githubusercontent.com/619340/139582615-c6253bf2-0c9f-4457-9bf9-2763343aa337.png)

**Comment by MedleMedler** [comment]
Good susggestion.

**Comment by MedleMedler** [comment]
How could you select faces with an vertex weight map (or texture) and divide them again in serveral pieces with the voronoi 2d node? This without changing the other faces.

**Comment by MedleMedler** [comment]
I do not think it will work, because the voronoi 2d node is a voronoi creator, not a voronoi cutter.
But maybe it is possible to make a nice voronoi pattern with a different density as above and (like in nature) have faces dat are broken again within that voronoi apttern.

Like so:
![old-cracked-concrete-surface-close-up-EMD38X](https://user-images.githubusercontent.com/92819305/141160184-70ff8695-ae15-4b19-9681-704d5e314691.jpg)

**Comment by portnov** [comment]
![Screenshot_20211110_225749](https://user-images.githubusercontent.com/284644/141167409-913ca1e5-4a6c-45ba-b644-7eeba3c85e8c.png)

**Comment by MedleMedler** [comment]
Are you serious? Of course yes, but this is incredable! Thank you very much.

**Comment by MedleMedler** [comment]
And in theory the voronoi 2D node should work also. Looking close at the picture (and also your example portnov), for the voronoi it's just a question of placing the vertices on the correct places with the correct density to.

**Comment by MedleMedler** [comment]
Only one problem: I do not have the "Voronoi on mesh node". Wich liberey I do have to upload in preferences and where do I find that libery?

**Comment by MedleMedler** [comment]
It does some werd things.

How can I get an exact voronoi pattern from the blue points (which I want to replace with above density controlled vertices) and then some extra red influance points to further  cut/crack the existing voronoi faces which are nearest to red influance points (and controlled by the amplitude of the attractor field).

**Comment by MedleMedler** [comment]
I begin to understand that the Lioyd node makes the final vertices to make the voronoi patterrn from. So I have to combine the blue dots and green dots and feed them in the Voronoi on Mesh node. In the picture below, 

Anyway: I would like to voronoi-cut some existing faces from (from blue dots) with the green dots.

![afbeelding](https://user-images.githubusercontent.com/92819305/141306292-c1b6c04c-e6c6-43a8-8a3f-43be21c32adf.png)

**Comment by MedleMedler** [comment]
I am learning a lot. 

Maybe, the solution is quite simple. I first create a voronoi pattern with the Voronoi on Mesh node. Then I separate the faces which I want to voronoi-cut in smaller pieces. Next I do the same proces again with the separte faces, feeding them in a second Voronoi on Mesh node.

This can probably completely done in sverchock, Here is a workaround,, separating a face manually

![afbeelding](https://user-images.githubusercontent.com/92819305/141311236-a74350e6-ca03-4127-8f53-cef897afa92c.png)

But now there is no influance/interaction between the both voronoi nodes. Voronoi cracking in time in nature does. Your method does have that advantage Portnov.

**Comment by MedleMedler** [comment]
It's complex. Look how the voronoi-cuts in time are related to each other. If we can recreate in sverchock, you will have very natural voronoi patterns and will create absolute beauty

![afbeelding](https://user-images.githubusercontent.com/92819305/141316177-21e177bf-e6cb-4425-9917-ae60414d2101.png)
.

**Comment by portnov** [comment]
![Screenshot_20211111_233201](https://user-images.githubusercontent.com/284644/141350633-a7da40c0-4524-4416-95fa-1d0ad6bb987b.png)

**Comment by portnov** [comment]
Also note, that Voronoi algorithm can never generate non-convex polygons.

**Comment by MedleMedler** [comment]
Nice! 

I think that this is the best solution. Although they are two independent voronoi-patterns, not influancing eachother. But the second voronoi node could be fed with more control and precise placing of the vertices.

It's time to study the psossibilities of precise placing of vertices.

Thank you very much!
