### ISSUE TITLE
Install SciPy fails on Apple M1 chipset

### ISSUE THREAD

**Issue by owenmoore** [nortikin/sverchok#4376]
## Problem statement

The SciPy install button in `Extra Nodes` does not work because the build is incompatible with Apple's new M1 chipset. I was able to manually install it via a nightly build (link to command below) and confirm that the `Voronio on Surface` node works as expected. I have yet to test anything extensively, but it appears to be a fix.

https://github.com/scipy/scipy/issues/13409#issuecomment-954596280

`pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy`

## Steps to reproduce

1. Install Blender `2.93.5` on new Apple M1 chipset
2. Preferences > Addons > sverchok > Extra Nodes
3. Press "Install with PIP"

## Expected result

Installs SciPi from a source that supports the chipset

## Actual result

Blender "freezes" while PIP attempts to find a build that works (just cycles through older and older versions)

## Sverchok version

1.0.0 from the URL on the README

## System Information

Mac OSX Monterey 12.0.1 - M1 Pro chipset

**Comment by nortikin** [comment]
nice. Doubt, noone in team has M1 chipset.
It is too new. Try to compile by your own and report to apple.

**Comment by wyhinton** [comment]
Any luck with this?
