### ISSUE TITLE
Extracting vertex group from a mesh

### ISSUE THREAD

**Issue by Zetsubonokami** [nortikin/sverchok#4377]
hi, is there a way to extract my vertex group from a mesh as lists or something? i basically have this one mesh that i'm feeding to sverchok and perform some transformation over it; and this mesh has some weight painting performed on it because i need it to deform according to a armature deform modifier and by so i need the new transformed mesh to keep all my vertex group intact, so is there a way to extract all my vertex groups (it's a character mesh so there's many one, and a single vertex has more than 1 group aswell) so i can perform operation over those, like adding /subtracting or shifting my vertices indices 

tnx in advance for a solution

**Comment by vicdoval** [comment]
In this example:
- The input mesh used as base object 
- the geometry is modified using the data from a vertex group
- A new object is created
- a vertex group is created in the new object  and the base vertex group is used to fill its data
![image](https://user-images.githubusercontent.com/10011941/140820567-31fdbc5c-db41-4123-b8b1-414be0821a44.png)

**Comment by Zetsubonokami** [comment]
yes i know this one, but it doesn't work with mroe than one vertex groups, if there's mroe than one it just calculate as any vertex affected by any weight regardless of the vertex group will get out of this socket; i basically need to transfer weight 1:1 without mixing them or i want be able to drive the new mesh with an armature deform modifier ( and i cna't use the transfer weight mdoifier becaus ethe mesh gets transformed (smoothed scaled and all faces get deleted while doubling the vertex count) so i nee dsverchok to extract each weight with each vertex index separated by wertex group

**Comment by Zetsubonokami** [comment]
> In this example:
> 
> * The input mesh used as base object
> * the geometry is modified using the data from a vertex group
> * A new object is created
> * a vertex group is created in the new object  and the base vertex group is used to fill its data
>   ![image](https://user-images.githubusercontent.com/10011941/140820567-31fdbc5c-db41-4123-b8b1-414be0821a44.png)

sorry for the answer above ,i've confused a socket later today going to try it on complex meshes with many vertex groups, if it works already this issue is closed; thanks for the lead
