### ISSUE TITLE
Error messages and node timings in wrong location

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4378]
## Problem statement
Error messages and node timings text that appear inside the canvas of the node graph show up at the wrong location far from the node with which they are associated

## Steps to reproduce

1. Turn on node timings
2. Deliberately cause a node to fail so an error can be displayed

## Expected result

error message in red near the node that generated it and the timing in white underneath the node with which it is associated. 

## Actual result

Error messages appear somewhere quite far from the node. Node timings are shifted and far from node as well so it is difficult to tell the time a node has consumed.
## Sverchok version
Latest 0.6.0.0
This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by Durman** [comment]
Hm, I'm turning on node timings and everything looks ok. Probably something else should be done?

**Comment by wassimj** [comment]
Strange. Here are how the node timings show in my definition
[https://cf-my.sharepoint.com/:i:/g/personal/jabiw_cardiff_ac_uk/EVc2Vyqu2hpFqeEkkfYn-OcBGR3T9C-HpEmQe5axGETzcg?e=FEJDlQ](https://cf-my.sharepoint.com/:i:/g/personal/jabiw_cardiff_ac_uk/EVc2Vyqu2hpFqeEkkfYn-OcBGR3T9C-HpEmQe5axGETzcg?e=FEJDlQ
)

**Comment by Durman** [comment]
What version of Blender do you use?

**Comment by wassimj** [comment]
Yes sorry, should've included that at the start:
Blender 2.93.1 Release Candidate
OS: Windows 10
