### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [nortikin/sverchok#4379]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Sverchok/lokal -name '*.py')
```

**Comment by elfring** [comment]
:thought_balloon: I would appreciate a more constructive feedback.

**Comment by zeffii** [comment]
it's up to you to make a case for the need for "increase the usage of augmented assignment statements" . Tight now your issue/mission is bordering on bot activity (as judged by similar posts to other repositories)

**Comment by elfring** [comment]
Some programming languages support operators with a special property:
* augmented
* combined
* compound

Thus corresponding change possibilities can occasionally be reconsidered, can't they? :thinking:

**Comment by zeffii** [comment]
you seem to have a mission to increase the uptake of augmented operators. 

![image](https://user-images.githubusercontent.com/619340/146657029-cb9e87f2-757a-403c-a02a-a8b7da0012cd.png)

we don't actively try to avoid these operators btw.

**Comment by elfring** [comment]
The support for the usage of these operator variants is evolving together with some factors.

:thought_balloon: Which factors do hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?
