### ISSUE TITLE
Volume node output format 

### ISSUE THREAD

**Issue by cromlyngames** [nortikin/sverchok#4380]
## Problem statement

Analyzer: Volume node outputs number result in [x] format. This is not compatible with the number node or the area node, both of which output in [[x]]

## Steps to reproduce

1. create circle and cylinder of same diamter
2. find area of circle, and volume of cylinder
3. divide (scalar maths) of volume by area fails

## Expected result

A number result, the same as the cylinder height 

## Actual result

"IndexError('Tuple index out of range')

## Sverchok version

1.0.0   from sverchok-master.zip from github

**Comment by Durman** [comment]
I guess new version of the node should be created for keeping backward compatibility with existing node trees.
