### ISSUE TITLE
Vector from 3D Cursor

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4382]
## Problem statement

Unable to use "Vector from 3D Cursor" command in SVerchok.

## Steps to reproduce

1. I want to copy 3D cursor position
2. I vaguely remember SV can copy paste 3D Cursor Vector Position
3. 
<img width="909" alt="Screen Shot 2021-11-30 at 1 42 47 pm" src="https://user-images.githubusercontent.com/3952687/143976540-82eeef9b-9267-4025-8d20-177383500c36.png">
<img width="824" alt="Screen Shot 2021-11-30 at 1 42 41 pm" src="https://user-images.githubusercontent.com/3952687/143976545-4375ab97-1126-4f84-a83f-5feaa157aa56.png">

## Expected result

I wish it can copy paste Vector position or as Matrix node

## Actual result

Error message

## Sverchok version

Latest!

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
it's not an operator you can call on it's own. it's meant to be called behind the scenes by the user who presses the "3d cursor" button on a `Vector-in` node.

![image](https://user-images.githubusercontent.com/619340/144037872-ae4ac699-7f70-4891-af40-1c663a1f9d51.png)

we can totally make a modification to that operator to make a new Vector-in node if if detects that the operator is called manually.

**Comment by zeffii** [comment]
or a macro "3d cursor to Vector" / "3d cursor to Matrix" .

**Comment by zeffii** [comment]
it's a pitty we don't have a 3d cursor node, that can output a vector and a matrix, and can "track" (or forget, detach from tracking) the 3d cursor position/rotation.

**Comment by Durman** [comment]
I guess the operator should get `INTERNAL` option. https://docs.blender.org/api/3.0/bpy.types.Operator.html#bpy.types.Operator.bl_options

**Comment by zeffii** [comment]
yes. no question

**Comment by zeffii** [comment]
macros added.

Get Property MK2 outputs the matrix correctly, but wrapped one too many times..

![image](https://user-images.githubusercontent.com/619340/144424489-d354021a-6028-4e1e-91d6-f94bb02d389c.png)

hmmm, we can do better.   but this is better than nothing.. for now.

**Comment by zeffii** [comment]
I think having a live-updated Node that outputs the 3D Cursor location/matrix into the nodetree, is going to a bit of a gimmick - because it's so easy to accidentally change the 3d Cursor position. It's not a freedom I think will work comfortably, or as expected most of the time.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/4383 i think offers part of the solution,  i'm tempted to also add a `Matrix In` version of the `3dcursor to matrix` macro, but that's a little bit more involved :)
