### ISSUE TITLE
Cannot enable sverchok add-on

### ISSUE THREAD

**Issue by fananthony** [nortikin/sverchok#4389]
![Screenshot 2022-01-03 at 4 47 43 PM](https://user-images.githubusercontent.com/94852753/147912900-1148a58e-da20-44d4-be08-d28889d933d4.png)

i received this message when enable the sverchok add-on. 
may I know how to solve this issue? thank u

**Comment by zeffii** [comment]
delete `...Library/Application Support/Blender/2.93/scripts/addons/sverchok-279_master` , and install from current master.zip

https://github.com/nortikin/sverchok/archive/refs/heads/master.zip

**Comment by zeffii** [comment]
reopen if still stuck
