### ISSUE TITLE
SYBREN Flatterer Addon

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4390]
I thought maybe SVerchok can take advantage of this Flatterer addon:
https://stuvel.eu/software/flatterer/

Anyone has made inspiring 3D print lately?

**Comment by Durman** [comment]
According to the description the add-on is using https://github.com/secnot/rectpack library. Probably Sverchok can convert this library into nodes instead.

**Comment by nortikin** [comment]
it seems like we already can do that and even more.
Examples - CNC. There is already SVG export example and we can cut edges as pro also, my concept is WIP anyway. And i don't see the edge formatting code, that makes joints.

**Comment by sybrenstuvel** [comment]
Thanks for the interest folks :)

**Comment by Durman** [comment]
Don't mention it. ))  I'm afraid that it will be difficult to integrate the add-on. For know we only use pip installable dependencies. I also thought about using vendoring for some external modules but I'm not sure about modules which require compilation steps.

**Comment by sybrenstuvel** [comment]
I'd also be rather unhappy if you decide to just "integrate" my add-on into Sverschok. Learning from it, sure, but just copying as-is, I don't see why you'd do that.

**Comment by Durman** [comment]
There is several precedents of including other add-ons into Sverchok. One of them is converting Tissue add-on into Adaptive Polygons node. Benefit of this is that functionality of the add-on can be used in Sverchok workflow, together with other numberless nodes. We have never get negative feedback from users about that. I don't know probably @alessandro-zomparelli is unhappy about that? I don't think it could make the original add-on less popular.

By the way the same node may appear in Geometry nodes as well. I saw someone from community was experimenting with the implementation.

**Comment by portnov** [comment]
It would be nice if the addon provided  API for it's main function. Then in Sverchok (or probably better in Sverchok-Extra) there could be a node that used that API.

**Comment by alessandro-zomparelli** [comment]
> There is several precedents of including other add-ons into Sverchok. One of them is converting Tissue add-on into Adaptive Polygons node. Benefit of this is that functionality of the add-on can be used in Sverchok workflow, together with other numberless nodes. We have never get negative feedback from users about that. I don't know probably @alessandro-zomparelli is unhappy about that? I don't think it could make the original add-on less popular.
> 
> By the way the same node may appear in Geometry nodes as well. I saw someone from community was experimenting with the implementation.

I wasn't unhappy about that. Doing an open-source add-on, you accept that people can take pieces of code, or ideas from that. Besides that, I think that it also depends on individuals' personalities. @portnov 's idea of using the addon API seems a nice idea and may engage the developer without the need to duplicate the code with subsequent maintenance difficulties. It also promotes the idea of Sverchock as an ecosystem of add-ons.

**Comment by sybrenstuvel** [comment]
> Doing an open-source add-on, you accept that people can take pieces of code, or ideas from that.

I know what it means to write Open Source, done it for quite a while now ;-) I'd be happy if people get inspiration from my code to make their own thing. Or even copy certain parts if it happens to match what they're doing. Just blatantly taking & integrating, not so much of a fan.

**Comment by zeffii** [comment]
this kind of went into a dead end, and that was unfortunate.

an excerpt from the license of `flatterer`.

```text
The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
our General Public Licenses are intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.
```
but it goes on..

```text
When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

  Developers that use our General Public Licenses protect your rights
with two steps: (1) assert copyright on the software, and (2) offer
you this License which gives you legal permission to copy, distribute
and/or modify the software.
```

I think the most we would have done would be to offer a scripted node way to pass verts/faces into the algorithm, and depending on the arguments/parameters write a small interface to show users how to customize it. Flatterer would still be required as a dependency, and all credit would still go to the author. I think that would be firmly within the letter and the intent of that license.

**Comment by zeffii** [comment]
such a script would look something like this
```python
"""
>in objects o
>in FilePath FP
"""
from sverchok.core.handlers import get_sv_depsgraph
import pathlib

import flatterer
from flatterer import svg_export, mesh_analysis, _pack_sort_items

depsgraph = get_sv_depsgraph()
out_path = pathlib.Path(FilePath[0][0])

# see params in docs/code
options = mesh_analysis.Options(
    laser_width = 0.2,   # float
    material_width = 2.0,  # float
    shape_padding = 2.2,  # float
    reduce_waste = False,   # bool
    pack_sort = _pack_sort_items[1][0],    # str
    pack_may_rotate = True, # bool
    shape_table = False  # bool
)
svg_export.write(depsgraph, out_path, objects, options)

```

**Comment by sybrenstuvel** [comment]
> Firstly, i like flatterer, it is an elegantly crafted piece of code.

Thanks!

> Flatterer would still be required as a dependency, and all credit would still go to the author. I think that would be firmly within the letter and the intent of that license.

Sure, and I'm not against this at all. From the initial posts I got much more of a "grab & assimilate" vibe, which is what got me barking a bit.

If some API change is needed to make things possible, by all means shoot me a PR.

**Comment by zeffii** [comment]
> I got much more of a "grab & assimilate" vibe, which is what got me barking a bit.

totally understandable, it's not how we operate.
