### ISSUE TITLE
Size of Sv files

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4391]
## Problem statement

By default Sverchok writes logs into Blender file. Some times it can increase the size of the file dramatically. From time to time I see complains of users that they can't share files because of their big size. Last report was about file with 300 mb size.

I see the solution of the problem in removing logs when the file is closed. If Blender crashed the logs might be still available when the file is reopened.

**Comment by zeffii** [comment]
we could set a post-save event to trim the sverchok.log size to N lines (set in preferences) . default of 256 lines maybe, (would be tiny filesize)
