### ISSUE TITLE
Group Node Creation and Input/Output socket linking bug

### ISSUE THREAD

**Issue by DolphinDream** [nortikin/sverchok#4394]
Creating a group node (ctrl+g) fails (using blender 3.0 and latest SV master at 66c158c9).

The group node seems to be created but it fails to completely generate and link. The selected nodes that were to be converted to a group  node and linked to the other nodes in the node tree is generated but the selected nodes are not replaced by the group node. Also the partially created group node (once you tab into the group) seems to have all the selected nodes but these are not linked to the input/output nodes in the group. What’s more, the manual linking of any sockets of the input/output nodes within the group also fail (which may be the reason why the group node generation and linking fails. 

https://user-images.githubusercontent.com/2083719/149643609-3c28315e-aae5-4887-bbbf-01d916bf9684.mov

Note: this may be the reason why exporting / importing a group node to/from presets also fails... or why the import/export of a group node to/from json file also fails. I can file a separate bug about the preset/export/import once this is resolved.

**Comment by Durman** [comment]
Can you reproduce the problem in 3.0.1?

**Comment by DolphinDream** [comment]
3.0.1 seems to work fine.
