### ISSUE TITLE
blender 3.2 alpha + serchok

### ISSUE THREAD

**Issue by luckychris** [nortikin/sverchok#4397]
i tried to install Sverchok on Blender3.2 alpha and i got:

![image](https://user-images.githubusercontent.com/232549/151797438-3b57b528-bb62-4db1-8bbf-8bebbb01b0a2.png)

do you have any idea how to solve that?

**Comment by luckychris** [comment]
Thanks for your fast reply. I did and now i got this:

![image](https://user-images.githubusercontent.com/232549/151842028-3774c5cc-f078-4b2f-b0b7-c34f5545d2c7.png)

**Comment by Durman** [comment]
I can't reproduce this with this version 3.2.0 Alpha, branch: master, commit date: 2022-02-01 23:18, hash: `rB9cc4861e6f7d`
Try to install last version of Blender, if there is still the problem try to describe exact steps to reproduce the problem.

**Comment by luckychris** [comment]
https://user-images.githubusercontent.com/232549/152315248-44091404-5a9c-462f-b40c-ec21d37e09d9.mov

here are all steps

**Comment by Durman** [comment]
Well, everything looks valid.
And this is strange:
![image](https://user-images.githubusercontent.com/28003269/152471197-01edcf11-8675-4166-a396-c6346143edd2.png)
I already saw such strange errors but don't remember what was the reason of them now.
Can you check your `addons` folder on the path? If there are more than one Sverchok folder delete all of them and install Sverchok again.

**Comment by luckychris** [comment]
Thx Durman. With the newest versions of all and deleting all folders before - it worked for all version!! Big thank you!!
