### ISSUE TITLE
Gradual Performance Degradation

### ISSUE THREAD

**Issue by Mosrod** [nortikin/sverchok#4399]
## Problem statement

After around 5-10 minutes working with Sverchok, Blender starts to slow down (especially selection & animation). This causes selections to take a couple of seconds to load. Selections remain near instant in the node view, however, there is a lag when moving around the node viewport and zooming in and out.

However, right when Blender starts (and the couple of minutes after), Blender performs optimally & quickly (selection is near instant and animations load at around 25 fps--five minutes later, it starts to slow all the way down to 6 fps). I have not noticed this issue with Blender without Sverchok (doing animations as well as modeling). I've been able to reproduce this issue with only a couple of nodes (such as the regular mesh generator nodes) and no complex geometry.

To resolve this lag, restarting Blender is the only option (when I create a new file, I can still see the performance lag). Additionally, Blender slowly starts to take up more memory in task manager, crawling to around 2 GB, which might be indicative of some sort of memory leak (not sure if this is a normal amount, especially with very simple geometry). 

Seems like moving nodes causes memory to drastically increase:

https://user-images.githubusercontent.com/18247709/153520410-172d3163-9dd0-4545-a45e-4c792befcd0c.mp4

## Steps to reproduce

1. Load Blender (have been able to reproduce this issue with 2.93.8 and 3.1.0. Have also been able to reproduce with Sverchok 1.1 and an older version (think its v0.6--stable june30_2021)
2. Open a Sverchok node editor & play around (dragging nodes repeatedly also works).
3. Notice lag delay

## Expected result

No delay.

https://user-images.githubusercontent.com/18247709/153517726-13dcdb49-5950-4757-9836-310e1b5e841b.mp4

https://user-images.githubusercontent.com/18247709/153517751-e318fbf5-fb73-4d49-9268-bbe09f111021.mp4

https://user-images.githubusercontent.com/18247709/153517777-cda23573-0fb0-4c36-ab7b-bd095fd52a81.mp4

## Actual result

Delayed performance.

https://user-images.githubusercontent.com/18247709/153517405-67c019af-f937-4161-88d5-b03b23c905f8.mp4

https://user-images.githubusercontent.com/18247709/153517442-2b621ac9-1f86-4a93-b641-ea9c06a4f474.mp4

https://user-images.githubusercontent.com/18247709/153517518-f04372cd-2f7e-486a-a668-2b1515333c4c.mp4

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

Installed from sverchock-master.zip from github (latest version--v 1.0.1)

**Comment by portnov** [comment]
Probably the reason is a big logging buffer? Check Sverchok preferences. If debug log is enabled, and writing to internal text buffer is enabled, who knows, may be affecting performance (it does not for me).

**Comment by zeffii** [comment]
- do you self compile Blender ?  
- windows 10 or 11 ?
- how long have you been using Sverchok,?
- is this a problem that has existed from the first days/moments you've used it?
- in windows you can show the "terminal window"  (window -> toggle system console) , that shouldn't be constantly printing stuff.

**Comment by Mosrod** [comment]
Hi,
Thank you for your quick support. I have been able to fix the issue by updating graphics drivers.

See the following closed thread on Blender's development bug tracker: https://developer.blender.org/T95715

Thanks!
