### ISSUE TITLE
Feature request: Floor Plan generation

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#4403]
I would like to know if somebody figured out a way to generate parametric floor-plans like in those grasshopper examples:
https://www.youtube.com/watch?v=xIOzF05ZYeU
https://www.youtube.com/watch?v=oUaLOr0cS6M
https://www.youtube.com/watch?v=6tdx_js0Gtc
https://www.youtube.com/watch?v=FC7mJqvcdcE
https://www.youtube.com/watch?v=w6Vs3RZX-1Q
I am sadly not knowledgeable enough to figure out a way on my own for now. I guess there could be a way to do so with help of the Evolver node. Maybe even by using the [topologic addon](https://github.com/wassimj/TopologicSverchok) by @wassimj.
In general a kind of [shape grammar](https://www.youtube.com/watch?v=uriZZjg5_PU) in sverchok would be extremly useful in my opinion.  I would be really greatful for any answers.

**Comment by Durman** [comment]
First step in this direction would be to find which algorithm is used for creating such graphs of rooms. Probably there is something in Grasshopper documentation.

The videos reminded me an [article](https://habr.com/ru/company/numdes/blog/599971/) (it's in Russian) where they used some similar technic for placing close to each other buildings. There was no any links about which particular algorithm was used but I guess it was sort of this - https://en.wikipedia.org/wiki/Force-directed_graph_drawing.

**Comment by wassimj** [comment]
Topologic already has a robust dual graph algorithm and set of nodes. I think the first step is to familiarise yourself with Topologic's functionality by downloading and trying a few things and then you can discover and discuss what is missing and suggest additions.

**Comment by enzyme69** [comment]
Try also MAZE MESH addon from Elfnor.
