### ISSUE TITLE
Changing parameter of this will crash blender

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4404]
## Problem statement

<img width="1246" alt="Screen Shot 2022-02-26 at 6 37 47 am" src="https://user-images.githubusercontent.com/3952687/155784101-74cae460-41c4-4d62-8efa-23a719da1f73.png">

## Steps to reproduce

Recreate above node setup.

## Expected result

It should not crash.

## Actual result

Crash

## Sverchok version

latest

**Comment by enzyme69** [comment]
Seems like it is crashing in Blender 3.1 and 3.2 but stable with Blender 3.0.1. I am on latest macOS.

**Comment by enzyme69** [comment]
[star_variants_001.crash.txt](https://github.com/nortikin/sverchok/files/8147480/star_variants_001.crash.txt)

Crash report above:

**Comment by Durman** [comment]
Can you run the script in the text editor and confirm that it crashes your Blender or not?

```py
import bpy
from bpy.types import PropertyGroup, Object, Scene, Mesh, bpy_prop_collection
from bpy.props import PointerProperty, CollectionProperty


class MyObjects(PropertyGroup):
    obj: PointerProperty(type=Object)


adding = True


def generate_objects():
    global adding
    my_objects: bpy_prop_collection = bpy.context.scene.my_objects
    if len(my_objects) > 20:
        adding = False
        print('REMOVING OBJECTS')
    elif len(my_objects) == 0:
        adding = True
        print('ADDING OBJECTS')

    me = bpy.data.meshes.get('Cube') or bpy.data.meshes.new('Cube')
    if adding:
        my_objects.add()
        my_objects[-1].obj = bpy.data.objects.new(name='Cube', object_data=me)
    else:
        bpy.data.objects.remove(my_objects[-1].obj)
        my_objects.remove(len(my_objects) - 1)


def loop_call():
    generate_objects()
    return 0.01


def register():
    bpy.utils.register_class(MyObjects)
    Scene.my_objects = CollectionProperty(type=MyObjects)
    bpy.context.scene.my_objects.clear()
    bpy.app.timers.register(loop_call)
    print("Timer registered")


register()
```

**Comment by enzyme69** [comment]
I run the script just now and it is no longer crashing Blender. It's probably macOS related.
