### ISSUE TITLE
Request : update script for blender 3.1 sverchok 

### ISSUE THREAD

**Issue by BennyGovaerts** [nortikin/sverchok#4407]
Hi , can this script maybe updated for blender 3.1 

https://elfnor.com/hyperbolic-tiling-in-3d.html

![image](https://user-images.githubusercontent.com/49908008/158797607-b6dc0f74-228f-4ea6-b6d9-97cef644544b.png)

**Comment by BennyGovaerts** [comment]
Hi , i have found a update script that works with blender 3.1 

https://github.com/elfnor/hyperbolic_coral/blob/master/hyperbolic_tiling_2.91.blend

**Comment by zeffii** [comment]
well, the `snl` script is here
https://github.com/elfnor/hyperbolic_coral/blob/master/snl_hyperbolic_tiling.py
