### ISSUE TITLE
SV Dictionary node accessing "custom property" string value?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4408]
If I have custom property stored in a mesh like this:

>>> bpy.data.objects['Mesh Point Cloud']["colors"][0].to_list()
[196.0, 245.0, 244.0, 1.0]

How do we actually access the data using SV Dictionary In or Out?

Originally I tried using Object ID Set, but then it does not like this ["colors"] string. I thought... okey maybe @Durman Dictionary nodes can be used?

<img width="936" alt="Screen Shot 2022-03-18 at 3 48 22 pm" src="https://user-images.githubusercontent.com/3952687/158939385-48c181ed-0285-4de3-871d-5e674224785a.png">

**Comment by enzyme69** [comment]
Supposedly like if I have CSV and added custom props, and then wanting to access it using SV nodes.
https://github.com/MarioDelgadoSr/AddBlenderCustomPropertiesFromCSV

I don't know also if SV can generate Custom Props (not attribute) from Dict nodes?

**Comment by Durman** [comment]
Dictionary nodes are not designed for that. Probably you can wright a script which would take an object and name of a custom property and return the value.

By the way properties with such notation `['prop']` are called as ID properties in Blender API.

**Comment by enzyme69** [comment]
Ok in the end I use "Exec Node Mod" to get the data out, which only calculated once, but also can pass the data. It's not a bad way, I guess.

![](https://user-images.githubusercontent.com/3952687/159817873-45e3530e-3469-444d-8a9d-021fe23315cf.png)

Thanks for reply!
