### ISSUE TITLE
Polygon 2D intersection analyse

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#4409]
Hello, i would like to ask if there is a simple method to analyse if a list of polygons are intersecting and then possibly output the index of the overlapping faces?
In the example below the output mask should be false for the 4 faces
![Screenshot from 2022-03-23 18-46-09](https://user-images.githubusercontent.com/64699866/159763804-cd27e9b3-fff7-40c1-97e0-0747fac2e662.png)
And here the output mask should be true for the faces 0,3 and 1.
![Screenshot from 2022-03-23 18-47-21](https://user-images.githubusercontent.com/64699866/159764141-6fc105fb-63bd-42da-879a-0e0a3333627a.png)
I feel like there must be a simple way to check the 2D overlapping of shapes, possibly even a specific node but i just cant find it.
Thank you

**Comment by Sinasta** [comment]
i guess shapely handles this pretty well:
from shapely.geometry import Polygon
p1 = Polygon([(0,0), (1,1), (1,0)])
p2 = Polygon([(0,1), (1,0), (1,1)])
print(p1.intersects(p2))
print(p1.intersection(p2).area)

But i'd still like to know if there is a dedicated node for that

**Comment by enzyme69** [comment]
Planar Edgenet node. Use it after Intersect Edges.
<img width="1100" alt="Screen Shot 2022-03-24 at 11 45 12 pm" src="https://user-images.githubusercontent.com/3952687/159918973-cc120d99-bef6-46d7-b76e-e1cfd5a42d05.png">

**Comment by Durman** [comment]
Probably you can use this layout somehow. For example it's possible to try to implement condition that a polygon does not have overlapping with other ones if its area was unchanged.

![image](https://user-images.githubusercontent.com/28003269/160535449-4cd3571b-e4f6-418b-8230-69bac42f9e23.png)
