### ISSUE TITLE
Can you add group marking as an asset function?

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4412]
![image](https://user-images.githubusercontent.com/74725748/160224342-cb236d59-2390-4787-a215-3b09ce598713.png)

**Comment by Durman** [comment]
It seems it does not have too match sense. Blender does not support this. It's not priority for Blender devs to support API for add-ons. Though it's probably worth to create bug report but it seems quite unlikely that they will fix this in this year.))
![sv group asset](https://user-images.githubusercontent.com/28003269/160532567-538b9eac-cfc2-4af1-a1f5-c50d60bea854.gif)

**Comment by Durman** [comment]
I've created the bug report on Blender tracker - https://developer.blender.org/T97237

**Comment by vkter** [comment]
Thank you for your feedback, I hope that the official will fix it as soon as possible.

**Comment by Durman** [comment]
There are issues which are unsolved for years unfortunately.

**Comment by Durman** [comment]
![image](https://user-images.githubusercontent.com/28003269/165883258-f1361ded-befb-40f8-8210-8a93835da766.png)

**Comment by Durman** [comment]
The Blender developers decided not to support adding custom node groups to the asset editor. I don't think they will change their mind soon.
