### ISSUE TITLE
Filepath Input Returning Error in Scripted Node

### ISSUE THREAD

**Issue by Marcus-Richmond** [nortikin/sverchok#4414]
## Problem statement

Running into an issue when trying to create a script with a file path input. 

## Steps to reproduce

1.  Here is my script:

```
"""
in path FP
out text s
"""

text = path

print(text)
```

2. When I execute this script in the blender text editor, I get the following message in the console output:

```
Traceback (most recent call last):
  File "D:\0_RMaps\Projects\2400_BlenderAndGIS\Documents_.BlendFiles\BlenderAndGIS_v1.blend\scratch.py", line 6, in <module>
NameError: name 'path' is not defined
Error: Python script failed, check the message in the system console

Code marked as unreachable has been executed. Please report this as a bug.
Error found at C:\Users\blender\git\blender-v293\blender.git\source\blender\blenkernel\intern\node.cc:441 in write_node_socket_default_value.
``` 

## Expected result

The actual file path should be `D:\0_RMaps\Projects\2400_BlenderAndGIS\Vector_Geopackage\BlenderAndGIS.gpkg`

## Actual result

See error message above

## Sverchok version

Sverchok version 1.0.0, installed from sverchok-master.zip from github

**Comment by Durman** [comment]
You should not run the code in the text editor. The text data block with the script should be assigned to the SNL node if you want to use the script in your tree.

![image](https://user-images.githubusercontent.com/28003269/160531961-fc05c6bc-d076-48b6-990f-db94003ef5ad.png)

**Comment by Marcus-Richmond** [comment]
I see, when I assign the script to the SNL node it works. 

I had been working on a few other scripts and was running the code in the text editor just to test that everything was working. For those other scripts, running in the text editor corresponded to the code working in the sverchok node interface so I assumed the same for this one. 

Thanks for the quick reply, I really appreciate the help!

**Comment by Durman** [comment]
A script works in text editor until node properties are not used.

**Comment by zeffii** [comment]
@Marcus-Richmond , the difference is only that you reference the variable `path` from the script body, but this variable doesn't exist within the enterpretter that you get when `running` the script from Text Editor. 

Snlite parses and hoists the content of the "directive" string (the place you write inputs and outputs) and makes it available at runtime from the node.

**Comment by Marcus-Richmond** [comment]
Thanks @zeffii,  I appreciate the response. I'm a bit new to python (and coding in general) so to be honest, this is still a bit over my head at the moment. For example, I'm not sure what your second sentence really means, but I will look into the terms used here to get a better understanding. 

I tried to implement this file path input in a more complex script, but am having trouble getting it to work, so I made this post on stack exchange: [https://blender.stackexchange.com/questions/258985/cannot-get-file-path-input-to-work-in-sverchok-addon](https://blender.stackexchange.com/questions/258985/cannot-get-file-path-input-to-work-in-sverchok-addon)

**Comment by zeffii** [comment]
ok
1. this part is called the directive. 

```
"""
in path FP
out text s
"""

```
    
2. TextEditor doesn't know about its content when you hit alt+P to run the script. (TextEditor just considers it a `string/comment` because of the `"""...."""`
3. Script Node has a mechanism which reads the content of the directive and makes `path` and `text` available as readable/writable variables at runtime. (from inside the node)

**Comment by zeffii** [comment]
you have a typo in your script.

`Attibute`  (the socket / also variable)

and you try to assign it to `Attribute` which doesn't exist.

**Comment by zeffii** [comment]
i'd try
```python
"""
in path FP
out Attribute s
"""

import geopandas as gpd
import pandas as pd
import fiona
import numpy as np


gpd1 = gpd.read_file(path, layer = "test shapes - polygons 1")

# call geo interface method on geodataframe
gi = gpd1.__geo_interface__

# variable to control which attribute is being extracted
variableAttribute = 'Integer'

# loop through geointerface (gi) and extract values from the 'Integer' column, and add them to the list created above
for features in range(len(gi['features'])):
    value = [gi['features'][features]['properties'][variableAttribute]]
    Attribute.append(value)

```

**Comment by zeffii** [comment]
i haven't been able to install gdal/geopandas/fiona etc,  but it seems that
```python
for features in range(len(gi['features'])):
    value = [gi['features'][features]['properties'][variableAttribute]]
    Attribute.append(value)
```
this will be doing
```
value = [gi['features'][0]['properties']["Integer"]]
value = [gi['features'][1]['properties']["Integer"]]
value = [gi['features'][2]['properties']["Integer"]]
value = [gi['features'][3]['properties']["Integer"]]
...
maybe it's like this?
```python
for feature in gi['features']:
    value = [feature['properties'][variableAttribute]]
    Attribute.append(value)
```

**Comment by zeffii** [comment]
@Marcus-Richmond  i added a few more thoughts just above (incase github didn't notify)

**Comment by Marcus-Richmond** [comment]
I've tried the following scripts:
```
"""
in path FP
out Attribute s
"""

import geopandas as gpd
import pandas as pd
import fiona
import numpy as np


gpd1 = gpd.read_file(path, layer = "test shapes - polygons 1")
gi = gpd1.__geo_interface__
variableAttribute = 'Integer'

# loop through geointerface (gi) and extract values from the 'Integer' column, and add them to the list created above
for features in range(len(gi['features'])):
    value = [gi['features'][features]['properties'][variableAttribute]]
    Attribute.append(value)
```
and
```
"""
in path FP
out Attribute s
"""

import geopandas as gpd
import pandas as pd
import fiona
import numpy as np


gpd1 = gpd.read_file(path, layer = "test shapes - polygons 1")
gi = gpd1.__geo_interface__
variableAttribute = 'Integer'

# loop through geointerface (gi) and extract values from the 'Integer' column, and add them to the list created above
for features in range(len(gi['features'])):
    value = [gi['features'][features]['properties'][variableAttribute]]
    Attribute.append(value)
```
But cannot get either of these to work. Also, when selecting these scripts with the SNL node, it doesn't seem to recognize the script properly (not sure how to phrase this, but the SNL node does not turn blue when selecting either of these scripts).

![image](https://user-images.githubusercontent.com/59568811/160975057-b40c9822-7684-4f2c-bad1-fbc3590fdafe.png)

**Comment by Marcus-Richmond** [comment]
Maybe another option, is there a good example of a node that uses a file path input that I could review and try to copy for my purposes?

**Comment by zeffii** [comment]
i'll do one later :)   using no 3rd party libaraies

**Comment by zeffii** [comment]
i'd start with getting snlite to throw errors with the least amount of code involved.

1. using lowercass variables (is the convention for python)
```
"""
in my_path FP
out some_output s
"""

if my_path:
    some_output.append(my_path)
```

above you'll notice that there is some guarding you can do in the circumstance where `my_path` is not yet acquired. This will be the case when you first initialize the script.

**Comment by zeffii** [comment]
so, let's say I have a simple file reader scenario 

### monty_python_lines.txt
```
SOLDIER #1: Where'd you get the coconut?
ARTHUR: We found them.
SOLDIER #1: Found them? In Mercea? The coconut's tropical!
ARTHUR: What do you mean?
SOLDIER #1: Well, this is a temperate zone.
ARTHUR: The swallow may fly south with the sun or the house martin or the plumber may seek warmer climes in winter yet these are not strangers to our land.
SOLDIER #1: Are you suggesting coconuts migrate?
ARTHUR: Not at all, they could be carried.
```

and a reader script like this

```python
"""
in my_path FP
out my_lines s
"""

if my_path:
    with open(my_path) as file:
        for line in file.readlines():
            my_lines.append(line)



```
my guess is you're getting an error like 
```python
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by zeffii** [comment]
because you are entering the world of scripting here, there are boilerplate / contextual (pretty mundane things... yet critical to get right)
```python
"""
in my_path FP
out my_lines s
"""

if my_path:
    print(my_path)
    with open(my_path) as file:
        for line in file.readlines():
            my_lines.append(line)
else:
    print("not executed yet because no filepath was given")
```

so, here the `else` statement will be triggered if my_path is an empty string or None, this can be a useful way to know if the code you wanted to run is in-fact really run or not.

**Comment by zeffii** [comment]
you were (as is usually the case in programming) excruciatingly close to this working out of the box.
```
"""
in my_path FP
out my_lines s
"""

if my_path:
    with open(my_path[0][0]) as file:
        for line in file.readlines():
            my_lines.append(line)
else:
    print("not executed yet because no filepath was given")
```
![image](https://user-images.githubusercontent.com/619340/161014528-3d20672d-d665-4a4b-b6ca-81b2d313d4e3.png)

**Comment by Marcus-Richmond** [comment]
Yes! This works!

```
"""
in my_path FP
out text s
out attribute s
"""

import geopandas as gpd
import pandas as pd
import fiona
import numpy as np

if my_path:
    
    print(my_path)
    
    # read in gpkg layer as geopandas data frame
    gpd1 = gpd.read_file(my_path[0][0], layer = "test shapes - polygons 1")


    # call geo interface method on geodataframe
    gi = gpd1.__geo_interface__

    # variable to control which attribute is being extracted
    variableAttribute = 'Integer'

    # create empty list to add attributes to
    listAttribute = []

    # loop through geointerface (gi) and extract values from the 'Integer' column, and add them to the list created above
    for features in range(len(gi['features'])):
        value = [gi['features'][features]['properties'][variableAttribute]]
        
        listAttribute.append(value)
        
    attribute = listAttribute
    
else:
    print("not executed yet because no filepath was given")
```

Thank you @zeffii! You have been a huge help and I really appreciate you walking me through this. Learning Sverchok has been a great way to get into coding, and I plan to keep at it. So, more to come, and thanks again!
