### ISSUE TITLE
Adding different functionnalities to 'Nearest Point on Mesh'

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4416]
Would it be possible to modify this node so that it could use an optional direction along which the distance is calculated, like for diameter? I know it is possible to do it by a workaround, but that takes a lot of nodes (and therefore is slow). Also, in case the closest point is a vertex or on an edge, it would be great if the node returned all the neighbouring faces. Finally, I think that having the angle(s) between the face(s) normal(s) and the direction of the segment linking the reference point and the nearest point on mesh would be even more useful than the face(s) normal(s). Of course, when the direction is an input, the answer is obvious, but when it is not the case, it could be very useful.

**Comment by portnov** [comment]
Isn't this what "Raycaster" node does?

**Comment by ArpegorPSGH** [comment]
That solves the biggest problems but not all. It still lacks the possibility to get all the faces when an edge or a vertex is hit, which is quite common for regular meshes. I still think that for Nearest Point on Mesh, knowing the angle between  the segment linking the reference point and the nearest point on mesh is quite useful. Finally, if I want to calculate distance between two meshes along a direction, is there an easy way to do so (2-3 nodes)? Maybe it would be worth creating a new node or modifying an existing one?

**Comment by Durman** [comment]
I don't think the node should have the option. Probably the Raycaster node can be improved to solve the corner cases but I guess this is what gives us Blender API. It's better to open separate issue (probably the problem was already solved =)
