### ISSUE TITLE
Create a 'Plane Line Intersection' node

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4417]
It sems strange to me that this node does not exist already, as all other combinations of intersections/distance calculations are present.
The node should have as input a set of at least 3 vertices on one hand (plane) and a set of at least two vertices on the other hand (line). It should return the point of intersection, and also (maybe) if this point is inside the triangle defined and if it is between the points defining the line.

**Comment by vicdoval** [comment]
Hi ArpegorPSGH
You are right, this node could exist and it does not but the problem can be solved with 2 nodes:
1st Project the line on the plane with "Distance Point Plane" Node
2nd Get the intersection with original line with the Distance Line Line inputting the original line and the projected line
![image](https://user-images.githubusercontent.com/10011941/161304873-f07e7add-24c4-40b5-9173-aecb183fbe69.png)

**Comment by ArpegorPSGH** [comment]
Thanks, I'll use that.
