### ISSUE TITLE
Write access for setting Freecad path.

### ISSUE THREAD

**Issue by HaasNL2** [nortikin/sverchok#4419]
## Problem statement

Need to start Blender in Administrator to set FreeCAD path.
Had this in Blender 3.1 and in 3.0.1 on windows 64x

## Steps to reproduce

1. Install Sverchok on windows.
2. Set Freecad Path
3. Start Blender in Administrator mode.
4. Set Freecad path

## Expected result

That it sets the path.

## Actual result

error message 
![afbeelding](https://user-images.githubusercontent.com/29804962/161421515-8511c7f1-dec0-4696-90a7-b2eaddff6b96.png)

## Sverchok version

Current master 1.0.1

**Comment by macdroid53** [comment]
Similar issue on Debian 11 with FreeCAD 0.20, Blender 3.1. When the the path is set to ../freecad-build/lib it still says FreeCAD is not installed. It also says PIP is not installed, which is not the case, it is indeed there.

**Comment by rendetto** [comment]
Please take a look at this issue #4406 
You cannot run FreeCAD for Sverchok/Blender that is built against different python version.
The last running combination is FreeCAD 0.20 with Blender 3.0.0, both compiled against Python 3.9.
Compiling FreeCAD with the latest Python 3.10 is still problematic, as I have read in some FreeCAD forum threads.

**Comment by HaasNL2** [comment]
@rendetto After starting Blender with admin mode it worked. Maybe it is unable to obtain the Freecad python version without admin rights?

**Comment by rendetto** [comment]
I'm not sure if admin rights are messing with python detection, but this is mainly OS setup and behaviour. I don't recall such case from my own experience.
About python compatibility... I'm not really sure exactly when this switch to python 3.10 happened. In any case this is not so important unless you're using some exotic new feature in Blender combined with FreeCAD nodes in Sverchok. Hopefully FreeCAD will catchup soon.

**Comment by zeffii** [comment]
@HaasNL2 
i'm a windows user, which combo would you like me to try, and what would you like me to point the `freecad Path` to

**Comment by zeffii** [comment]
for the record, here i loaded up Blender 3.0.1 (stable) and the Blender Py console..
```python
>>> sys.path.append(r"D:\DOWNLOADS\FreeCAD_Python_3.9.12\FreeCAD_Python_3.9.12\Library\bin")
>>> import FreeCAD
>>> FreeCAD.Version()
['0', '19', '24366 (Git)', 'Unknown', '2021/12/04 21:56:30']
```
if i remove that `bin` from the sys.path and start Blender regularly and then manually add the path from the Sverchok extra nodes preferences, and restart Blender, then FreeCAD is available . No admin required,  but I do get windows `Security Scan` warnings. I can warnings from windows Virus Threat and protection whenever I do even something as mundain as browse that folder from Explorer. (This happens to no other folder on my machine) 

![image](https://user-images.githubusercontent.com/619340/166140854-b6efed12-786c-4303-a796-5bf76ac90961.png)

**Comment by HaasNL2** [comment]
ugh I tried reproducing it, but I can't it could be caused by making the variable for the url, but I have no clue. I'll close the issue now and hopefully it dissolved after Freecad nodes got merged.
