### ISSUE TITLE
Enabling release version

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4420]
## Problem statement

I faced with several complains recently about enabling Sverchok. It seems there is no problem with installing the add-on from master. But installation from last release rises an error.

Steps to reproduce:
1. Download source code from [last release](https://github.com/nortikin/sverchok/releases/tag/v1.0.0).
2. Install add-on from zip
3. Press enable button
4. Read the strange error

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok-1'
```

Actual name of the folder after add-on installation is `sverchok-1.0.0`

Probably the problem is on Blender part and this somehow is related with parsing dots in add-on names.

**Comment by zeffii** [comment]
yeah, but
```
mod = __import__(module_name)
```
is like doing
```
import sverchok-1.0.0 as mod
```
but there is no folder called `sverchok-1`.

if the folder was named `sverchok-1_0_0` ( as awkward as that looks... i agree)  i'm sure it would enable no problems.

**Comment by kevinwright** [comment]
Yes, but...

The problem is with using the github-provided source folder as the plugin, in which case the folder name is determined for us and we have no control to name it `severchock-1_0_0` or anything else!

This is the main issue I tackled in https://github.com/nortikin/sverchok/issues/4415 - by explicitly building our own release zip that's independent of the github-provided one, we have complete control over naming. And once we have that, we might as well just name the folder `sverchok`, which is what Blender expects anyway.

**Comment by zeffii** [comment]
I don't think we feel obliged to keep master supporting all possible Blender revisions. ( 2.8x 2.9x 3.x ), that would start to complicate stuff, if there's a way to automate a table creation which associated last Sverchok git-hash to support certain Blender versions, no one will object to that but it would something we would need to only occasionally run.

I support your PR but only for the creation of the custom zip.

**Comment by kevinwright** [comment]
> i'm all for that. Your PR provides a way to automatically have that zip named correctly?

Yes! **Exactly** that.  And also testing via the zip instead of via a folder copy, which confirms that installation works and is much of the reason I use docker.

**Comment by zeffii** [comment]
@kevinwright  it's possible that we use some `.git` stuff to extract the current hash for displaying on user's Sverchok Menu..
https://github.com/nortikin/sverchok/search?q=get_hash

**Comment by Durman** [comment]
I have added the add-on zip file with valid name in the release. Will consider this as solved. In future releases this problem should be taken into account.
