### ISSUE TITLE
Unable to enable after install

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4421]
## Problem statement
Can't enable after install.

## Steps to reproduce

1.Download zip file: sverchok-1.0.0.zip

2. Attempt to enable (addons click the checkbox) in Blender 3.1.2 Linux (Debian 11) reports: "Module not found: sverchok-1"
 
## Expected result

sverchok to be enabled

## Actual result

sverchok not enabled.

## Sverchok version

Assume download of sverchok-1.0.0.zip from github is version 1.0.0

**Comment by zeffii** [comment]
#4413  same issue. sorry.
