### ISSUE TITLE
Reset boolean input after node execution

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4422]
Is there a way to reset a boolean checkbox input socket after the execution of the node? Or, alternatively, is there a method to implement a temporary push button that when pressed, executes the node, but otherwise, the node does not execute?

**Comment by zeffii** [comment]
yes, i think you want the `animatable mixin`: https://github.com/nortikin/sverchok/pull/3134

**Comment by Durman** [comment]
The description seems more fits into the Evolver node functionality.

**Comment by zeffii** [comment]
this seems resolved?

**Comment by wassimj** [comment]
Yes it is. Sorry. You are too fast for me :) I used the Evolver script method and that works great!
