### ISSUE TITLE
Distance Line Line wrong result

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4423]
When applying this node to parrallel lines, intersection flag is True instead of False (the distance between lines is far greater than Tolerance). Could this be corrected?

**Comment by zeffii** [comment]
it's behaving as intended, according to the code that implements that function.

>      In case of parallel lines it will return the origin of the first line as the closest point 


https://github.com/nortikin/sverchok/blob/675f70c33f537c87f546e35a8394fe63960dec44/utils/geom.py#L2479-L2510

**Comment by zeffii** [comment]
i think you're suggestion is valid.

**Comment by zeffii** [comment]
when the `else` is run, the ` dist = (inter_p[0] - line_origin_b).length ` part is (i think) likely to be an operation on the same vector3d. there `inter_p[0]` and `line_origin_b` are identical, and subtracting one from the other will result in a `(0, 0, 0)` and have `0` length

**Comment by ArpegorPSGH** [comment]
One solution is to calculate the angle between the line's directions and if it is 0 or 180, output false for intersection.

**Comment by ArpegorPSGH** [comment]
Well, after analysing it a bit, the problem just stems from a little mistake from the author of the function : instead of `dist = (inter_p[0] - line_origin_b).length`, it should be `dist = (inter_p[0] - line_origin_a).length`. Perhaps you could correct that, @zeffii.
