### ISSUE TITLE
BUG? Frame number node become static

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4425]
## Problem statement

Frame info number does not advance. Bug?

## Steps to reproduce

Create Frame Info, test the output

## Expected result

Frame should be moving

## Actual result

Frame static, weird, maybe bug

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by enzyme69** [comment]
<img width="748" alt="Screen Shot 2022-04-13 at 4 24 28 pm" src="https://user-images.githubusercontent.com/3952687/163113536-dea6d6d8-b71e-44d1-8fd7-bc6349d69125.png">
Frame become static, somehow this happens suddenly in latest Blender.

**Comment by enzyme69** [comment]
Seems fixed again with latest Blender.

**Comment by enzyme69** [comment]
UPDATE: it does not work. Frame does not automatically update itself as I scrub the timeline. I am using Blender 3.1 and 3.2.

**Comment by Durman** [comment]
Works for me in the both versions.

![scrubing](https://user-images.githubusercontent.com/28003269/163752787-3b2bcaa7-0f0c-4378-a362-3759579c2c9b.gif)

Any errors in console?

**Comment by enzyme69** [comment]
It works in Blender 3.2 latest (today)

Frame Info node still does not work in Blender 3.1. It does not update as I scrub.

This might be Blender issue because this was intermitten, I remember updating Blender 3.1 and 3.2 on the same days and both does not work. And then few days later 3.2 works.

No error message. 

Uploading Screen Recording 2022-04-19 at 11.46.09 am.mov…

**Comment by Durman** [comment]
Did you try 3.1.2 version?

**Comment by enzyme69** [comment]
Yes, this is 3.1.2 version. They did something to this version of Blender that switch off SV frame update. Works with 3.2.

**Comment by Durman** [comment]
There are known issues which appear only on macOS-s - https://github.com/nortikin/sverchok/issues/4404, probably this one is one of them.

I you wish I can create a code snippet which you have to run on your machine to define the source of the problem.

**Comment by enzyme69** [comment]
I'll keep eyes on this one. 

The crashing bug seems fixed with latest macOS.

**Comment by enzyme69** [comment]
<img width="851" alt="Screen Shot 2022-05-02 at 9 14 18 pm" src="https://user-images.githubusercontent.com/3952687/166225715-ca56efe6-e035-47fa-a6ed-271aec93b19e.png">

Strange that I need to set it to "POST" for the frame to work. Change of behaviour maybe? But it works like this.
