### ISSUE TITLE
Vectors Angle Node

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4427]
I did not find a node able to calculate the angle between two vectors (for example normals). I did it with a formula node, but as the formula is very long, it isn't really practical to use. Maybe that would be useful to add a specific node, if there isn't already one I did not find?

**Comment by portnov** [comment]
"Vector Math" node can calculate angles between vectors.

**Comment by ArpegorPSGH** [comment]
Ok, thanks.
