### ISSUE TITLE
Write FCStd node requires existing FreeCAD file, can't create one on demand.

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4431]
This should probably be in a discussion section of this github...

Is there an example of using this node?

Failing that what do I feed the _Mesh to Solid_ node to feed the _Write FCStd_ node? (So, essentially, what do I use to get the Verts and Faces for the _Mesh to Solid_ node?)

![image](https://user-images.githubusercontent.com/6831752/164894998-7e35fb01-a8df-46d1-ba80-4328b17c51db.png)

**Comment by zeffii** [comment]
try Generators -> Cube / Torus -> and pass their Verts and Polygons/Faces into `Mesh to Solid`

https://github.com/nortikin/sverchok/blob/master/docs/nodes/solid/mesh_to_solid.rst

**Comment by macdroid53** [comment]
Ended up using Get Objects Data.

That didn't work until I learned that the FreeCAD file had to exist first. So, I just saved a file with nothing in it from FreeCAD and it worked

So, I'm going to edit the subject of this issue to reflect that if I can.
