### ISSUE TITLE
Write FCStd node should create a FreeCAD file.

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4432]
Expected:
When Write FCStd node is executed creates file with specified name.

Actual:
When node is executed no file is created. If an empty FCStd file by the specified name exists, the data is written.

**Comment by zeffii** [comment]
https://wiki.freecadweb.org/FreeCAD_API
suggests a function call like ` F.newDocument(doc_name) ` would be capable of starting a new empty file.  
it likes like F.open is really only for existing Freecad docs?

**Comment by zeffii** [comment]
I see the `FCStd_write` node doesn't offer a way to start a new freecad file from scratch, only a way to pick up an existing file.

**Comment by zeffii** [comment]
i propose we add a button to the FCStd_write node, which lets you 
   - pick a file location and a new file name, 
   - and then the node automatically adds a FilePath Node attached to the FCStd_write node 
       - The newly created FilePath will point at the File
       - The newly created File will be initialized as a new empty freecad file. 

yay/nay ?

**Comment by macdroid53** [comment]
Hmm...I thought what happened when I tried the node was I could indeed select a path and filename (note: it by default offered .blend as the extension **_not_** .FCStd).
But, if the file did not exist and the node executed, it did nothing (which was good at that point because it would have overwritten my blend file of the same name?)
IMO, it should act as would be expected of any file output. If the specified name exists, ask if it should be overwritten, otherwise create the file and output the solid.

**Comment by zeffii** [comment]
yeah OK. that makes a lot more sense. FilePath node allows you to type an arbitrary filename into the FileName text box, and it will pass the `current path + filename` (or actually `os.path.join(current_path, filename)`) into the FilePath output socket (even if the file does not exist)

**Comment by zeffii** [comment]
perhaps something like this
```python
    try:
        from os.path import exists
        
        Fname = bpy.path.display_name_from_filepath(fc_file)
        
        if not exists(fc_file):
            F.newDocument(fc_file)
        else:
            F.open(fc_file)

    except Exception as err:
        info(f'FCStd open error, {err}')
        return

    F.setActiveDocument(Fname)
    fc_root = F.getDocument(Fname)

```

**Comment by macdroid53** [comment]
This seems good.

I don't know if there is a way to do it. When I click on the socket and it creates a File path node, it would be nice if it defaulted to .FCStd rather than .blend. But, the code you show would at least help to prevent and accidental overwrite.

**Comment by zeffii** [comment]
> it would be nice if it defaulted to .FCStd

yeah, it may be possible to coerce the instance of the FileOpen dialogue to do that.

**Comment by zeffii** [comment]
@macdroid53   i can make a branch for you and you can tell me if you like how that works.
- can reject filepaths that don't end in FCStd
- can create new file at filepath specified in FilePath Node, if filepath doesn't exist yet.

**Comment by macdroid53** [comment]
Sure, I can have a look.
Can I just copy the code to `/home/mac/.config/blender/2.93/scripts/addons/sverchok/`

**Comment by zeffii** [comment]
yeah, that'll work.. or you could even just replace the `nodes/exchange/FCStd_write.py` file manually.

**Comment by macdroid53** [comment]
Which branch?

**Comment by zeffii** [comment]
sorry. just added : https://github.com/nortikin/sverchok/pull/4437

**Comment by zeffii** [comment]
it is untested as I can not get freecad currently

**Comment by zeffii** [comment]
but for now i only implemented the feature that tells the FCStd_write node to create the FCStd file on-the-fly if it doesn't exist.

**Comment by zeffii** [comment]
(in theory..)

**Comment by luzpaz** [comment]
CC 
@yorikvanhavre (FreeCAD)  
@wassimj (Topologic)  
@Moult (BlenderBIM)

**Comment by yorikvanhavre** [comment]
Note that `doc.save()` assumes the doc.FileName attribute is set. If you create a doc with `FreeCAD.newDocument(docname)`, the FileName attribute will be an empty string. Rather, better use `doc.saveAs(filepath)`. This also has the effect of setting FileName.

**Comment by zeffii** [comment]
implemented. seems to work, thanks @yorikvanhavre !

**Comment by luzpaz** [comment]
Nice! What's the next task?

**Comment by zeffii** [comment]
a solution will need to be found for forcing the FilePath node to look specifically for certain kinds of files, and automatically suffix `.FCStd` if not provided by user.

**Comment by zeffii** [comment]
but that's an issue with FilePath node, rather than FreeCAD =)

**Comment by luzpaz** [comment]
Apropos #4446
