### ISSUE TITLE
list item node,The data length is not matched correctly

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4435]
![image](https://user-images.githubusercontent.com/74725748/165014687-2dd0eb41-d449-4b95-89ff-397fc270a66d.png)
[untitled.zip](https://github.com/nortikin/sverchok/files/8551349/untitled.zip)

**Comment by Durman** [comment]
Thanks. There is already issue about this problem - https://github.com/nortikin/sverchok/issues/3908
