### ISSUE TITLE
File Path not always in correct format for Windows

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4436]
## Problem statement

I have an SvStringSocket with property of StringProperty with subtype="FILE_PATH". When I click on the folder icon and choose a path from the filesystems, sometimes, the displayed path is using the Linux/Unix style (e.g "//testfile.txt") rather than the Windows style (e.g. "C:\Users\tom\Desktop\testfile.txt").

## Steps to reproduce

1. Uses a Sverchok for Windows
2. Create node that uses a file path input
3. Choose the file path from the desktop (e.g "testfile.txt")
4. Observe the result in the node.

## Expected result

I expected to see a Windows-style path "C:\Users\tom\Desktop\testfile.txt"

## Actual result

"//testfile.txt"

## Sverchok version

0.6

**Comment by zeffii** [comment]
have a look at how FilePath node is implemented.
https://github.com/nortikin/sverchok/blob/master/nodes/network/file_path.py , this will return the directory and the file(s) and combine them using `os.path.join(directory, file)`

**Comment by wassimj** [comment]
@zeffii  I am not trying to write my own filepath node. I am using the standard way to specify a StringProperty with subtype="FILE_PATH". The result from sverchok's own code is wrong it seems. Please see image. This is on Windows, so it should never show //test.txt
![filepathglitch](https://user-images.githubusercontent.com/6302909/165085949-3c263e76-e8a1-4145-b4c8-9f200a92e45e.png)

**Comment by zeffii** [comment]
you are drawing a custom layout for the File Path socket?  show me code.

**Comment by zeffii** [comment]
i suspect we moved on to using a dedicated SvFilePath socket and a FilePath node so we could control the interface better. I think if you aren't explicitly defining that Folder open icon (and the operator that it spawns, and the resulting FileOpenDialogue)  beside the FilePath Textfield, then you are using something that is provided to us by the Blender API, and there may be limited options to control that.

**Comment by wassimj** [comment]
FilePathProp: StringProperty(name="File Path", description="A file path", subtype="FILE_PATH")
def sv_init(self, context):
		self.width = 400
		self.inputs.new('SvStringsSocket', 'File Path').prop_name='FilePathProp'

**Comment by zeffii** [comment]
you have options:
- you could define an update function for that `bpy.props.StringProperty()` which post processes the value it wanted to return, into a value that you would prefer.    ( i think this is prone to complexity , because as soon as you programmatically modify the variable you trigger another update.. so you will need to add some way to prevent recursion in updates)
- you can define an operator, which would behave essentially like the FilePath Node, and you would not use subtype="FILE_PATH"  (subtype seems to be doing stuff that isn't helping you in this case), then custom draw your socket layout. so something like that.. but you would want to refine it..
    ```python
    row = layout.row()
    row = layout.prop(node, "FilePathProp")
    row = layout.operator("bpy.ops.node.your_file_path_locator_operator")
    ```

- if your Sverchok has a socket type `SvFilePathSocket` use it.

**Comment by zeffii** [comment]
i'm sure you can figure out some code to test whether a string is a stub or a full path to an absolute location

**Comment by zeffii** [comment]
leading to the inevitable (but potentially flawed solution)
```python
import bpy
import sverchok

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode

class SvFPTest(bpy.types.Node, SverchCustomTreeNode):
    """
    Triggers: GIS 
    Tooltip: test
    """
    bl_idname = 'SvFPTest'
    bl_label = 'path test'
    bl_icon = 'ASSET_MANAGER'
    
    def update_fullpath(self, context):
        if not self.FilePathProp:
            return
        if self.FilePathProp != bpy.path.abspath(self.FilePathProp):
            self.FilePathProp = bpy.path.abspath(self.FilePathProp)
    
    FilePathProp: bpy.props.StringProperty(name="File Path", description="A file path", subtype="FILE_PATH", update=update_fullpath)
    
    def sv_init(self, context):
        self.width = 400
        self.inputs.new('SvStringsSocket', "Path").prop_name = "FilePathProp"
        self.outputs.new('SvStringsSocket', "output Path")

    def process(self):  
        
        # create initial variables
        pass

classes = [SvFPTest]
register, unregister = bpy.utils.register_classes_factory(classes)

if __name__ == "__main__":
    if hasattr(bpy.types, "SvFPTest"):
        bpy.utils.unregister(SvFPTest)

    register()


```
this would update using abspath.

**Comment by zeffii** [comment]
but!   i would probably stress test that `update function` a little to prevent it encountering a non halting situation.

**Comment by zeffii** [comment]
you can also stick a check inside `sv_process` to see if the value stored in `FilePathProp` is a an absolute path or not, and make it into an absolute filepath inside `sv_process` (but don't overwrite self.FilePathProp). The advantage to doing that inside sv_process is that you can share a zipped dir with a `blend` files and your other `file`, and make use of the "relative" nature of the value stored in `FilePathProp`.

**Comment by wassimj** [comment]
Many thanks! I will see which to implement.
