### ISSUE TITLE
Read FCStd reads some objects not others

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4439]
## Problem statement

Read FCStd node won't read specific object from the FreeCAD file.

## Steps to reproduce

1. Create File Path node(specify attached file), Read FCStd node, select object named Cut
2. Add Solid Viewer node, nothing is created
3. Select other objects from file and they are created. (For instance the clone of Cut called Cut001 or Cut002.)

## Expected result

Expected to see Cut when specified.

## Actual result

Nothing when specifying Cut.

## Sverchok version
1.0.1

Blender 2.93.3
[Fig_114.zip](https://github.com/nortikin/sverchok/files/8564272/Fig_114.zip)

**Comment by rendetto** [comment]
Hi,

I'm using Blender 3.0.0 with the latest Sverchok and when specifying the object you mentioned I got an expected result.

![Cut_Visible](https://user-images.githubusercontent.com/66558924/165388235-f98901c7-e97a-4fb0-bab9-e461d9437ae9.jpg)

Can you please double check on that?

**Comment by macdroid53** [comment]
I have never been able to get the  combination of Blender 3 to work with any system I have.

Even on my Manjaro pc where FreeCAD is using Python 3.

Is 1.0.1 not the latest sverchok?

If I copy the Cut object into a new FreeCAD file, then read node does produce the expected  model.

**Comment by rendetto** [comment]
I just tested your file on Blender 2.93.2 with the latest Sverchok, and the result is the same as on the screenshot above.
Can you check if all the filters are set like those shown in my test?

**Comment by macdroid53** [comment]
The filters are the same. I suspect some other  conflict in Blender. I don't understand why it works if I get the same solid from another FCSTd file. And I don't understand why the other solids from that file also update normally.

**Comment by macdroid53** [comment]
Ok, my bad. I did not have the tool_parts checkbox ticked.

Discovered this while trying to get Blender 3.1 going on my Manjaro box. I got that working as well.
