### ISSUE TITLE
Read FCStd can't read Body objects

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4441]
## Problem statement

Can't read Body objects. Is this known?

## Steps to reproduce

1. Create, File path node, READ FCStd node
2. Attempt to select any Body Object (can't actually, they aren't listed.
3. 

## Expected result

Select Body objects.

## Actual result

Body objects not list for selection

## Sverchok version
Blender 3.1.2, Sverchok 1.1.0
[Simple_assy_001.zip](https://github.com/nortikin/sverchok/files/8576525/Simple_assy_001.zip)

**Comment by zeffii** [comment]
@macdroid53  it might be time to read the source code behind that node.

https://github.com/nortikin/sverchok/blob/master/nodes/exchange/FCStd_read.py

(i'm still having trouble getting freecad dependency to enable in Windows10 and Blender `3.0` or `3.1.0` or `3.1.2` ..)
what I can do is load FreeCAD application and open the built in python console, and use it as a REPL.

**Comment by macdroid53** [comment]
More details...

This combination of sverchok and Blender fails to read the Body objects:
Blender 3.1.2, sverchok 1.1.0-alpha, FreeCAD 0.20(doesn't seem to matter, but, the Python 3.10 on this machine, Manjaro)

This combination sees the Body objects.
Blender 2.93.3, sverchok 1.0.1, FreeCAD 0.20 (Debian 11, Python 3.9.2)

**Comment by zeffii** [comment]
this is directly from the FreeCAD REPL.
```python
>>> import FreeCAD as F
>>> path = "D:\DOWNLOADS\Simple_assy_001"
>>> live_fc = F.open(path)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
OSError: Invalid project file: D:/DOWNLOADS/Simple_assy_001
>>> # App.setActiveDocument("Simple_assy_001")
>>> # App.ActiveDocument=App.getDocument("Simple_assy_001")
>>> # Gui.ActiveDocument=Gui.getDocument("Simple_assy_001")
>>> # App.setActiveDocument("")
>>> # App.ActiveDocument=None
>>> # Gui.ActiveDocument=None
```

**Comment by zeffii** [comment]
oops.   i'm experimenting with the FreeCAD REPL. mght take a few minutes

**Comment by zeffii** [comment]
```python
>>> import FreeCAD as F
>>> fc_file = r"D:\DOWNLOADS\Simple_assy_001\Simple_assy_001.FCStd"
>>> live_fc = F.open(fc_file)
>>> # App.setActiveDocument("Simple_assy_001")
>>> # App.ActiveDocument=App.getDocument("Simple_assy_001")
>>> # Gui.ActiveDocument=Gui.getDocument("Simple_assy_001")
>>> Gui.runCommand('Std_OrthographicCamera',1)
```

**Comment by zeffii** [comment]
then in Blender Python console (or Blender TextEditor..whichever you prefer) i'd expect to see different outputs from this simple script?
```python
import FreeCAD as F
fc_file = r"<----your path to----->\Simple_assy_001.FCStd"
live_fc = F.open(fc_file)
for obj in F.ActiveDocument.Objects:
    print(obj.TypeId)
```

**Comment by macdroid53** [comment]
On Blender 3.1.2, sverchok 1.1.0-alpha that code lists no PartDesign::Body objects

On Blender 2.93.3, sverchok 1.0.1, FreeCAD 0.20 lists PartDesign::Body objects

**Comment by zeffii** [comment]
but that's probably a FreeCAD api issue?

**Comment by macdroid53** [comment]
Hmm...that code works in FreeCAD (i.e. it finds the Body objects).

I have the AUR version of FreeCAD on this machine and a straight from git version.
With either the code finds the Body objects.

I tried changing the path specified in the sverchok setup in Blender. But, no matter what is set, the source directory for FreeCAD shows: /usr/lib/python3.10/site-packages/ in the Blender Python in console.

So, not sure what to try next.

**Comment by zeffii** [comment]
i'm trying to get a python 3.10 version of freecad to experiment on here..   but i'm afraid all that would do is confirm that freecad built with py3.10 isn't finding certain objects.  So next thing to turn to would be the freecad python library source. (which i imagine is a huge automatically generated wrapper around C/C++ code )

**Comment by zeffii** [comment]
this might be a bit more overseeable
```python
from collections import defaultdict
import FreeCAD as F
from pprint import pprint

fc_file = r"D:\DOWNLOADS\Simple_assy_001\Simple_assy_001.FCStd"
live_fc = F.open(fc_file)

obj_names = defaultdict(list)
for obj in F.ActiveDocument.Objects:
    ID = str(obj.TypeId)
    A, B = ID.split('::')
    obj_names[A].append(B)

pprint(obj_names)

```
results in 
```python
            {'App': ['Origin',
                     'Line',
                     'Line',
                     'Line',
                     'Plane',
                     'Plane',
                     'Plane',
                     'Origin',
                     'Line',
                     'Line',
                     'Line',
                     'Plane',
                     'Plane',
                     'Plane',
                     'Origin',
                     'Line',
                     'Line',
                     'Line',
                     'Plane',
                     'Plane',
                     'Plane'],
             'Part': ['Cylinder',
                      'FeaturePython',
                      'Extrusion',
                      'Cut',
                      'Extrusion',
                      'FeaturePython',
                      'Cut',
                      'Revolution',
                      'Cut',
                      'Fillet',
                      'Fillet',
                      'FeaturePython',
                      'FeaturePython',
                      'FeaturePython',
                      'FeaturePython'],
             'PartDesign': ['Body',
                            'Pad',
                            'Body',
                            'Pad',
                            'Body',
                            'FeatureBase',
                            'Pocket',
                            'Mirrored',
                            'ShapeBinder',
                            'Hole',
                            'MultiTransform',
                            'Mirrored',
                            'Mirrored'],
             'Sketcher': ['SketchObject',
                          'SketchObject',
                          'SketchObject',
                          'SketchObject',
                          'SketchObject',
                          'SketchObject']}
```

**Comment by macdroid53** [comment]
> 

That code lists no 'PartDesign': ['Body',...

**Comment by zeffii** [comment]
so what's the F.Version of the version that works.. vs the version that doesn't work ?

**Comment by zeffii** [comment]
can you find the object by part `Type` ?
```python
>>> F.ActiveDocument.findObjects(Type="PartDesign::Body")
[<body object>, <body object>, <body object>]
>>> 
```

**Comment by macdroid53** [comment]
I've been working this in a thread on the freecadweb.org forum. It appears there is a packaging issue with AUR. 

__init__.py doesn't appear to be present and thus import PartDesign doesn't happen.

https://forum.freecadweb.org/viewtopic.php?f=22&t=68354&start=10

**Comment by zeffii** [comment]
as this is an issue with FreeCAD's distribution, and is not expected to be fixed from Sverchok code, i'm going to close the issue.

Feel free to keep adding commentary to this thread

**Comment by smr02** [comment]
I'm still facing this Issue. Did anyone find a solution?
