### ISSUE TITLE
Raycaster bug : wrong face index

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4443]
In one of my node trees when veryfying proper working, I found out that when hitting the first polygon of the mesh, -1 gets returned instead of 0, while everything else is normal. Attached is a MWE.
[Bug raycaster_2022_04_28_17_11.zip](https://github.com/nortikin/sverchok/files/8584910/Bug.raycaster_2022_04_28_17_11.zip)

**Comment by zeffii** [comment]
interestingly - in this scenario
```
        if I.is_linked:
            I.sv_set([[r[2] if r[2] else -1 for r in L] for L in RL])
```
`r[2]` must be evaluating to False. RL is `[[(Vector((0.0, 0.0, -1.0)), Vector((0.0, 0.0, 1.0)), 0, 1.0)]]`

**Comment by zeffii** [comment]
and the first polygon's index being 0,  results in r[2] evaluating to False. and therefore is replaced by `-1` .

**Comment by zeffii** [comment]
we might have to write 
```python
F = [[r[2] if (r[2] != None) else -1 for r in L] for L in RL]
```

**Comment by zeffii** [comment]
nice catch @ArpegorPSGH

**Comment by Durman** [comment]
If we stick to pep8 - https://pep8.org/#programming-recommendations
It should be `something is not None`

**Comment by zeffii** [comment]
even better
