### ISSUE TITLE
SVG Document node Parameter control

### ISSUE THREAD

**Issue by Sinasta** [nortikin/sverchok#4448]
I want to create a 2D animation in Blender without passing by the internal render of Blender. So I am creating SVG files for each frame but sadly there is no parametric control for The 'name' and 'write' parameter. Is there any way to automatically save a SVG for each frame? Thank you

**Comment by zeffii** [comment]
a formula node could be used for the filename
```
A + "_" + str(B).zfill(4)+ ".svg"
```
![image](https://user-images.githubusercontent.com/619340/166225161-ada3e21c-c849-4db8-a0c6-07ea9766f47b.png)

**Comment by zeffii** [comment]
i think if you hook up a SNLite and assemble the filename from a script
```python
"""
in frame_idx s d=1 n=2
>in trigger_me v
>in filename_base s
"""

node = self.inputs['trigger_me'].other.node
node.file_name = filename_base[0][0] + str(frame_idx).zfill(4)
bpy.ops.node.svg_write(tree_name=node.id_data.name, node_name=node.name)

```
that could work, you may need to hook up the SNLite downstream from the SVG Document node so it triggers later.

![image](https://user-images.githubusercontent.com/619340/166230363-52557890-2a05-4d08-af65-57960ebed14f.png)


![image](https://user-images.githubusercontent.com/619340/166230323-155996a8-8179-4c96-9934-472f1175e398.png)

**Comment by zeffii** [comment]
you could use that until someone finds time to make a less adhoc solution @Sinasta

**Comment by zeffii** [comment]
@Sinasta `live update` does already write upon input change, so all that is needed is a way to suffix the filename
https://github.com/nortikin/sverchok/pull/4450 if you feel like test driving it

**Comment by Sinasta** [comment]
Thank you very much! it is working perfectly well! I personally prefer the option with an input socket for filename because it offers more options (like naming the first 10 frames Triangle_01 etc and the rest Square_01 etc). But the numbered suffix property is interesting as well.

**Comment by zeffii** [comment]
i see. yeah i'll still do a socket version, which lets you control the filename, and merge that as soon as i can.
