### ISSUE TITLE
Submenus Branch (space bar menu)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#448]
makes sense when moniker 'modifier' doesn't. Transforms are very specific operations, whereas modifier can be a whole range of different operations.

Maybe
- Rotate
- Move ( wish it was called translate )
- Scale
- Mirror
- Matrix apply
- Matrix Sheer

**Comment by zohozer** [comment]
@zeffi. How did you get this icons in the menus? Personally I don't have them and don't know how to activate them.

![icons](https://cloud.githubusercontent.com/assets/619340/4561291/ddb46cc6-4efb-11e4-8e9d-5d5fcd995fb0.gif)

**Comment by nortikin** [comment]
@zohozer 
use sverchok properties ctrl+alt+U --> sverchok icons boolean switch

**Comment by zohozer** [comment]
@nortikin 
Thank you. Now it is working.
