### ISSUE TITLE
string tools code question

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4483]
https://github.com/nortikin/sverchok/blob/e78d4824c1c8395a948e7c02c302f99de8842f9e/nodes/text/string_tools.py#L269

@vicdoval  is the indentation "intended" there?  if so is it unintended in the `"n"` clause of that if-else? 

https://github.com/nortikin/sverchok/blob/e78d4824c1c8395a948e7c02c302f99de8842f9e/nodes/text/string_tools.py#L261-L270

i'm experimenting with adding a mode, which drops input sockets.. to produce a node that looks like

![image](https://user-images.githubusercontent.com/619340/169474697-7f311b95-1708-4d2f-a679-995d8866ae17.png)

or maybe just keep it simple. simpler. simplest. https://github.com/nortikin/sverchok/discussions/4482#discussioncomment-2788312

**Comment by vicdoval** [comment]
It seems that line 264 can be deleted

**Comment by zeffii** [comment]
looks like it.
