### ISSUE TITLE
Float precision

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4498]
In one of my node trees, I need to get the vertices normals used in Solidifify modifier in constraint mode. So, I solidify my model of 10e-6 m, then get the original vertices and the new ones, and substract their coordinates to get the normals used. However, when I do the substraction, the values I obtain are all the same, around +/-10e-5, like if I hit maximal precision or something. A float precision is supposed to be 10e-7/10e-8, and Blender limit precision to 10e-6, so there shouldn't be any problem, right? So, is the problem coming from Blender, Sverchok, or my procedure itself? When I switch the solidification to 10e-4 in thickness, it works as intended (but there are still some imprecisions left).

**Comment by zeffii** [comment]
10e-5 is hitting the limits of signed 32bit float, the issue is "significant digits".  I started writing a doc about it here https://github.com/nortikin/sverchok/blob/9d8bd27a36dcac8e942ed2f5f5e2725d912046ba/docs/epsilon.rst , not sure if that helps.

**Comment by zeffii** [comment]
some nodes allow you to adjust their espsilon, in practice this sets the "scale" of the object and if all the numbers in the calculation are small you can get away with a much smaller epsilon than might be set standard for that node.  But - if the feature you're using doesn't have an epsilon you might have to work on a large scale and use larger epsilons, and rescale down to the desired scale in the end (maybe even outside of blender)

**Comment by zeffii** [comment]
when components of coordinates are on the order of `10e-6 m`  ( `0.000010` m) , we are "wasting" 5 digits of precision to indicate "how small" the thing is.  -- this is not so meaningful "inside" a computer, you can work virtually in much larger scales so that you can make use of as many significant digits as 32 bit signed float allows.  You probably want to work at meters, or tens of meters (bounding box)

**Comment by zeffii** [comment]
i should also stress that using Stethoscope to display the values might result in confusing values, it is geared towards the meters and tens of meters (descirbed above). As soon as it encounters small numbers if will simplify them.. based on rounding
https://github.com/nortikin/sverchok/blob/f7537fbaaa7c5ef336de24062cddb186a57b8454/nodes/text/stethoscope_v28.py#L141
and
https://github.com/nortikin/sverchok/blob/f7537fbaaa7c5ef336de24062cddb186a57b8454/nodes/text/stethoscope_v28.py#L89-L95

**Comment by ArpegorPSGH** [comment]
Yes, eveythin can be scaled up, the only limit being the level of detail in the model ; in my use case, if the largest vertex coordinate goes over 10 000 time the smaller edge length, I'm screwed, because I cannot have enough precision to ensure my vectors are not too far off from the reality.

**Comment by zeffii** [comment]
set rounding to 0

**Comment by zeffii** [comment]
here's another way to view them..  by plugging this is the `np.array` Node set to _custom mode_
```python
[f"{np.array(x)}"]
```
![image](https://user-images.githubusercontent.com/619340/171660684-2e531be2-4026-4f00-8b95-6c613d9349a4.png)

it's pretty. but be careful about passing it thousands of coordinates.

**Comment by zeffii** [comment]
my guess is that this issue is resolved, but the reality of the limits of 32bit float precision are not being to satisfy certain use-cases.
