### ISSUE TITLE
Preference setting for FreeCAD nodes

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4499]
## Problem statement

The setting of the path to FreeCAD seems to have no effect.

I have discovered while trouble shooting the FreeCAD package issues under Arch AUR the setrting of the FreeCAD path in the Blender preferences seems to have no effect. Even is it is blank, if system PYTHONPATH is correct, sverchok nodes work.

Note: the package issues with AUR are ancillary.

This issue is more a question, by me, as to what the setting in preferences is supposed to do.

## Sverchok version

v1.1.0-alpha.1

**Comment by zeffii** [comment]
following the code, if the path pointed to by the user can be imported, then this code
```python
file_path = open(os.path.join(site_packages, "freecad_path.pth"), "w+")
```
writes a file in the `...site-packages/freecad_path.pth` , and this is a python feature/convention ( https://docs.python.org/3/library/site.html ) , and from what i can make out, this makes it possible for the FreeCAD library to be located in a different location (like a proxy location), it's supposed to be a practical convenience.

**Comment by zeffii** [comment]
if you can `import FreeCAD` in bpy python console , without setting it explicitly via the path, then yeah, it's a redundant step.

**Comment by macdroid53** [comment]
Ok, that tracks what I've seen in my experiments. Thanks.
