### ISSUE TITLE
Matrix track to node

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4500]
## Problem statement

![image](https://user-images.githubusercontent.com/28003269/171017640-0d82fb2f-69a7-4dde-b311-fbe73b26a5bc.png)

![image](https://user-images.githubusercontent.com/28003269/171017682-fbe461af-43bc-455a-98ed-543e97f2a6d5.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/81062ac28da6c4418994a20972afbc2edddfc411/nodes/matrix/matrix_track_to.py#L216-L221
