### ISSUE TITLE
Unable to use Metaball viewer in 3.1

### ISSUE THREAD

**Issue by Marcus-Richmond** [nortikin/sverchok#4504]
The metaball viewer node is not working, I'm receiving this error when trying to use it:

<img width="996" alt="Metaball viewer error" src="https://user-images.githubusercontent.com/59568811/171543402-96fe32c4-f5a4-44b2-85d0-29b20f27744a.png">

This only seems to be in blender version 3.1, I tried using the metaball viewer in 3.0 and it worked fine.

Using Sverchok version 1.1.0 as well.

Thanks,

**Comment by Durman** [comment]
Blender 3.1.2 + Sverchok 1.1.0-alpha.1 (master) works for me

**Comment by portnov** [comment]
It looks like there is already a mesh object in your scheme, named Alpha. Try use another name for Metaball.

**Comment by Durman** [comment]
I checked this scenario and the node seems is clever enough to create new object if type of current one does not match.

**Comment by Marcus-Richmond** [comment]
> It looks like there is already a mesh object in your scheme, named Alpha. Try use another name for Metaball.

This was it @portnov @Durman! Glad it wasn't a bigger issue. Thanks,
