### ISSUE TITLE
Trees with reroutes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4512]
## Problem statement

![image](https://user-images.githubusercontent.com/28003269/172013554-6ec4c2d9-2695-43fb-a948-3c35da295a5c.png)

[broken.zip](https://github.com/nortikin/sverchok/files/8838187/broken.zip)

It seems that I messed something up in this method:

https://github.com/nortikin/sverchok/blob/fa455c1e061d5abfafbdb3e92f86dc3b9af086ad/core/update_system.py#L152-L157

In the update tree data structure I remove reroutes because there is no any sense to take them into account during updating trees. The code is not complex but delicate and it seems is better to add some tests for this step.

**Comment by Durman** [comment]
This is how I think the test should look like

![image](https://user-images.githubusercontent.com/28003269/172016288-ec48db1f-cf94-49d3-80f3-2a77e541f84c.png)

**Comment by zeffii** [comment]
`self.inputs['some_socket'].is_linked` would have to return False is the input is from a reroute node with no upstream connection?
```
      no upstream connections        
            V                                      ___________some node_________
      (reroute) --------------------------------->| o [ some_socket]            |
                                                  |_____________________________| 
```

**Comment by Durman** [comment]
The actual Blender tree is always unchanged so inside nodes the `is_linked` test will be true but update system uses its internal efficient data structure where the some_socket will be recognised as disconnected.
