### ISSUE TITLE
File name with non alphanumeric characters not handled correctly

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4521]
## Problem statement

When using File path and Read FCStd node, if the file name includes non alphanumeric characters (-, '(',')' ) file is not recognized.

If the file name includes a '-' or ')', the error (shown above the Read FCStd node):

```
2022-06-10 08:31:41,837 [INFO] sverchok.nodes.exchange.FCStd_read 334: FCStd read error
2022-06-10 08:31:41,837 [ERROR] sverchok.nodes.exchange.FCStd_read:337 : <class 'NameError'>
```

If the file name includes a '_', the error (shown in the terminal window): 

```  
File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/nodes/exchange/FCStd_read.py", line 337, in LoadSolid
    F.closeDocument(Fname)
NameError: Unknown document 'RaspPi4random_4'

location: <unknown location>:-1
```

## Steps to reproduce

1. Create a FreeCAD file with the described characters
2. Attempt to specify the file in the File path node connected to a Read FCStd node.

## Sverchok version

v1.1.0-alpha.2

**Comment by zeffii** [comment]
okay, let's have a look

**Comment by zeffii** [comment]
that's weird, because the only file i've ever opened is called `Simple_assy_001.FCStd`,  for testing

just to be clear here, are you saying you can use these nodes without issues read/write.etc all day long, just as long as the filenames do not contain `underscores, hyphens and parenthesis` characters?  

is this something which has never been possible for you or _don't know never tried_

**Comment by zeffii** [comment]
kind of peculiar that the line numbers in the error message (334, 337) are beyond the length of the current version of that node. 243 lines) . Hinting that the error might be in the FreeCad module.

**Comment by macdroid53** [comment]
I'm on Debian and Manjaro.

If I remove the offending character it works fine.

Not sure it matters, but I'm am using this version of FCStd_read.py:


[FCStd_read.zip](https://github.com/nortikin/sverchok/files/8879280/FCStd_read.zip)

**Comment by zeffii** [comment]
this line worries me
```
                            labels.append( (obj.Label, obj.Label, obj.Label) )
```
this appends entries to a bpy enum i think, and they must be not include any characters other than `[a-zA-Z_0-9]`

**Comment by zeffii** [comment]
i;m going  to guess object labels are permitted to have spaces in FreeCAD.
```python
from sverchok.data_structure import no_spaces

...
      labels.append( (no_space(obj.Label), obj.Label, obj.Label) )
```

**Comment by macdroid53** [comment]
> i;m going to guess object labels are permitted to have spaces in FreeCAD.
> 
> ```python
> from sverchok.data_structure import no_spaces
> 
> ...
>       labels.append( (no_space(obj.Label), obj.Label, obj.Label) )
> ```
> 
> there will probably need to be a remap to go from the nospaces(label) back to the original label for lookups based on the selected enum. This is harder to explain than to do, but the whole thing is unpleasant and brittle -- if this is indeed part of the issue

FreeCAD, indeed does allow spaces in object names. As well as commas, etc.

**Comment by zeffii** [comment]
in that case it might be more versatile to to do something like
```python
file_obj_remapper = {}

    ...

            # this will require some unique identifier, simplest is hash(self)
            file_obj_remapper[hash(self)] = {}

            for idx_file, f in enumerate(fc_file_list):
                try:
                    F.open(f) 
                    Fname = bpy.path.display_name_from_filepath(f)
                    F.setActiveDocument(Fname)
                    
                    for idx_obj, obj in enumerate(F.ActiveDocument.Objects):
                        if obj.Module in obj_mask or obj.TypeId in obj_mask:
                            safe_string_id = no_space(f"{(idx_file, idx_obj)}")
                            file_obj_remapper[hash(self)][safe_string_id] = obj.label
                            labels.append( (safe_string_id, obj.Label, obj.Label) )


# the lookup would be 
freecad_original_object_label = file_obj_remapper[hash(self)].get(self.option)
```

**Comment by zeffii** [comment]
just to be clear here, there are two issues here

1. the population of enum's identifier (first column) must be `[a-zA-Z_0-9]` only
2. the File name issue.

fixing `1` will probably break existing .blends if the modification doesn't attempt to "upgrade" the code at runtime. Bit of a headache, but probably doable. It needs to be corrected anyway.

it could be that fixing 1.  fixes 2,  because the FreeCAD module while running in FreeCAD loads those files fine.
```python
>>> import FreeCAD as F
>>> doc = F.open(r"D:\DOWNLOADS\2022\ObjectCount45\RaspPi4random_5 - Copy.FCStd")
>>> # App.setActiveDocument("RaspPi4random_5___Copy")
>>> # App.ActiveDocument=App.getDocument("RaspPi4random_5___Copy")
>>> # Gui.ActiveDocument=Gui.getDocument("RaspPi4random_5___Copy")
>>> Gui.runCommand('Std_OrthographicCamera',1)
>>> doc.FileName
'D:/DOWNLOADS/2022/ObjectCount45/RaspPi4random_5 - Copy.FCStd'
>>> 
```

**Comment by zeffii** [comment]
further inside FreeCAD
```python
>>> from pathlib import Path
>>> Path(doc.FileName).stem
'RaspPi4random_5 - Copy'
>>> Fname = Path(doc.FileName).stem
>>> F.setActiveDocument(Fname)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
Base.FreeCADError: Try to activate unknown document 'RaspPi4random_5 - Copy'
>>> 
```

**Comment by zeffii** [comment]
```python
>>> doc.Name
'RaspPi4random_5___Copy'
```
tadaa!

**Comment by macdroid53** [comment]
Sorry, my comment about FC allowing characters like comma, or parentheses, was about the names (labels displayed in the Tree view in FC) of the solids in the file. Not the file name itself, which is the focus of this issue.
As for file names, I not sure of the complete list of characters FC allows. But, if understand, for example, Blender allows underscore, but, not minus. So, the File path node would be subject to Blender rules and the Read FCStd would be subject to FC rules? Does Read FCStd node actually do the file open? (thus making it need to follow FC rules?)
And, Read FCStd node would need to be able to deal with all the characters FC allows for object labels (the names displayed in the Tree view?

Sorry, for all the questions.

**Comment by zeffii** [comment]
all questions are welcome @macdroid53 .

0. I didn't know blender has that limitation, I'm not very adventurous with filenames.
1. `F.open()` is freecad, and it doesn't really care what the file is called. If you can "os-legally" name a file something, it seems to accept it.
2. `File Path` node is not subject to Blender's file name rules, it simply looks at your filesystem and lets you pick a file.
3. The visible `name` from that dropdown is just one of the elements of the [enumerator list](https://docs.blender.org/api/current/bpy.props.html?highlight=enum#bpy.props.EnumProperty). 
```python
enum = [(identifier, name, description), ...]

```
the name member accepts a liberal character set, just the identifier element was restricted by blender devs to a limited charset.
5. here the FCStd read node assumes that these following will be the same "string"
```python
>>> file_name = r"D:\DOWNLOADS\2022\ObjectCount45\RaspPi4random_5 - Copy.FCStd"
>>> import FreeCAD as F
>>> doc = F.open(file_name)
>>> doc.Name
'RaspPi4random_5___Copy'  # <--- will work
>>>
>>> from pathlib import Path
>>> Path(doc.FileName).stem
'RaspPi4random_5 - Copy'   # <--- wont work
>>>
>>> bpy.path.display_name_from_filepath(doc.FileName)      # <---- FCStd node uses this 
'RaspPi4random_5 - Copy'   # <--- also not
```
so... when the node tries to
```python
                    F.open(f)   #  f = file_name
                    Fname = bpy.path.display_name_from_filepath(f)
                    F.setActiveDocument(Fname)
```
it throws an exception, and the exception has a `finally` clause, which tries to execute another thing that will cause an exception
```python
                    F.closeDocument(Fname)
```

**Comment by zeffii** [comment]
this will probably work for the `document name` issue  (the internal name doc.name)
```python
            for f in fc_file_list:
                try:
                    temp_doc = F.open(f) 
                    Fname = temp_doc.Name or bpy.path.display_name_from_filepath(f) 

                    F.setActiveDocument(Fname)
                    
                    for obj in F.ActiveDocument.Objects:
                        if obj.Module in obj_mask or obj.TypeId in obj_mask:
                            labels.append( (obj.Label, obj.Label, obj.Label) )
                    
                except Exception as err:
                    info(f'FCStd label read error: {Fname=}')
                    info(err)
                finally:
                    F.closeDocument(Fname)

```
but i suspect this might work too
```python
            for f in fc_file_list:
                try:
                    doc = F.open(f) 
                    for obj in doc.Objects:
                        if obj.Module in obj_mask or obj.TypeId in obj_mask:
                            labels.append( (obj.Label, obj.Label, obj.Label) )
                    
                except Exception as err:
                    info(f'FCStd label read error: {f}')
                    info(err)

```

**Comment by zeffii** [comment]
@macdroid53  https://github.com/nortikin/sverchok/pull/4524

**Comment by zeffii** [comment]
I think this solves the FileName issue,   but the obj.label issue is still a gaping wound.

**Comment by zeffii** [comment]
and the other FCStd nodes are probably doing something similar in places.

**Comment by zeffii** [comment]
as for alternative version of the `FCStd read` the filename/docname issue, if you are comfortable editing the python yourselff for that file you can replace lines that create `Fname`, usually something like
```diff
- F.open(f)
- Fname = bpy.path.display_name_from_filepath(f)
+ doc = F.open(f)
+ Fname = doc.Name or bpy.path.display_name_from_filepath(f)
```

**Comment by zeffii** [comment]
it doesn't appear that using the `obj.Label` in enum identifier element has caused any errors, that code isn't even called until the user clicks "Select FC Part". But when it is called it's still not a problem

**Comment by macdroid53** [comment]
> as for alternative version of the `FCStd read` the filename/docname issue, if you are comfortable editing the python yourself for that file you can replace lines that create `Fname`, usually something like
> 
> ```diff
> - F.open(f)
> - Fname = bpy.path.display_name_from_filepath(f)
> + doc = F.open(f)
> + Fname = doc.Name or bpy.path.display_name_from_filepath(f)
> ```

Comfortable enough.

I see that the File path node allows multi-select. How would I use that, what does it mean to the Read_FCStd node?

**Comment by zeffii** [comment]
FilePath node, pick multiple files by holding ctrl and click the file.
![image](https://user-images.githubusercontent.com/619340/173250718-2d535d15-def1-45e7-bfee-922bd855fa0f.png)

according to the FCStd read node's code, it will let you 
- output all objects in those files
- the node uses a `Set` collection datatype to store the objects, this should mean that there are no duplicate references to objects, but i wouldn't count on that being a useful mechanism to ensure uniqueness. Only one way to find out how effective that is :)  try it.
