### ISSUE TITLE
Number of objects in FreeCAD file cause face already exisits error

### ISSUE THREAD

**Issue by macdroid53** [nortikin/sverchok#4522]
## Problem statement

The attached zip has 2 FreeCAD files. One has 4 solids, one has 5 solids.
Using the following connected nodes:

- File path
- Read FCStd
- Solid to Mesh
- Mesh viewer

Specifying RaspPi4random4.FCStd the Mesh viewer reports no error.
Specifying RaspPi4random5.FCStd the Mesh viewer reports error:
`ValueError('faces.new(verts): face already exists)`

Note: the original RaspPi4 file has 19 solids. The files attached can include any random selection of 4 or 5 solids and the same result is seen.

## Sverchok version

v1.1.0-alpha.2
[ObjectCount45.zip](https://github.com/nortikin/sverchok/files/8878915/ObjectCount45.zip)

**Comment by macdroid53** [comment]
`Traceback (most recent call last):
  File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/core/update_system.py", line 369, in main_update
    node.process()
  File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/nodes/viz/mesh_viewer.py", line 184, in process
    me_data.regenerate_mesh(self.base_data_name, v, e, f, m, self.fast_mesh_update)
  File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/utils/nodes_mixins/generating_objects.py", line 206, in regenerate_mesh
    add_mesh_to_bmesh(bm, verts, edges, faces, update_indexes=False, update_normals=False)
  File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 133, in add_mesh_to_bmesh
    [new_face([bm_verts[i] for i in face]) for face in faces or []]
  File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 133, in <listcomp>
    [new_face([bm_verts[i] for i in face]) for face in faces or []]
ValueError: faces.new(verts): face already exists
2022-06-10 11:07:11,811 [DEBUG] sverchok.core.tasks 112: Global update - 1204ms

`

**Comment by zeffii** [comment]
i'm not able to replicate the error

**Comment by zeffii** [comment]
for sv_mesh_utils `add_mesh_to_bmesh` to give that error
```
File "/home/mac/.config/blender/2.93/scripts/addons/sverchok-master/utils/sv_bmesh_utils.py", line 133, in
[new_face([bm_verts[i] for i in face]) for face in faces or []]
```
does narrow down the search :)

**Comment by macdroid53** [comment]
Does it show Solid. 5 and read all as shown here:
![image](https://user-images.githubusercontent.com/6831752/173096098-3b2f96dd-0962-44c4-9576-80199ff37926.png)

**Comment by zeffii** [comment]
oh.. i see. no i was not displaying the 5 objects simultaneously

**Comment by zeffii** [comment]
i'm a little confused.  but it's time for dinner :) 

![image](https://user-images.githubusercontent.com/619340/173098031-9721e1c1-50af-4d9c-8107-3bfdd793d821.png)

**Comment by zeffii** [comment]
from what i can tell there are no duplicate faces in those face lists.  
```python
for faces in Faces:
    len(set([sorted(f) for f in faces]))
for faces in Faces:
    len(set(faces))
```
are the same..

**Comment by zeffii** [comment]
ahh.. thats not sorting the way i thought it was..

**Comment by zeffii** [comment]
there are definitely duplicate polygons in that output from `Solid To Mesh`.

confirmed here 
```python
"""
>in Verts v
>in Faces s
"""

import bmesh

def add_mesh_to_bmesh(bm, verts, faces):
    new_vert = bm.verts.new
    new_edge = bm.edges.new
    new_face = bm.faces.new
    bm_verts = [new_vert(co) for co in verts]
    # [new_edge((bm_verts[i1], bm_verts[i2])) for i1, i2 in edges or []]
    faces_selection = faces[16000:-3000]
    for idx, face in enumerate(faces_selection):
        try:
            [new_face([bm_verts[i] for i in face]) or []]
        except Exception as err:
            print(f"{idx=}, and {len(faces_selection)=}")
            [print([face]) or []]
            print(err)
            print("^^^^^^^^^")
            internally_sorted = list(sorted([list(sorted(f)) for f in faces_selection]))
            print(internally_sorted)
            print(len(internally_sorted))
            A = set([tuple(f) for f in internally_sorted])
            print(len(A))
            break

for verts, faces in zip(Verts, Faces):
    bm = bmesh.new()
    add_mesh_to_bmesh(bm, verts, faces)

```

**Comment by zeffii** [comment]
we could add a "Filter Degenerates" Node / API  , but it does slow down things a little.  The saving grace of this geometry is that it is tris all the way, lending itself nicely to numba/numpy for speedup

**Comment by macdroid53** [comment]
Hmm..."there appear to be 400 duplicates ( either rotated, or reversed ) polygons in the output of Solid To Mesh.."

That means those solids aren't manifold, right?

**Comment by zeffii** [comment]
### degenerate_filter
```python
"""
>in Verts v
>in Faces s
out Verts_out v
out Faces_out s
"""

import bmesh

def add_mesh_to_bmesh(bm, verts, faces):
    new_vert = bm.verts.new
    new_edge = bm.edges.new
    new_face = bm.faces.new
    bm_verts = [new_vert(co) for co in verts]
    # [new_edge((bm_verts[i1], bm_verts[i2])) for i1, i2 in edges or []]
    reference_faces = set()
    good_faces = []
    add_face = good_faces.append
    
    for idx, face in enumerate(faces):
        try:
            polygon_shell = tuple(sorted(face))
            if not polygon_shell in reference_faces:
                reference_faces.add(polygon_shell)
                [new_face([bm_verts[i] for i in face]) or []]
                add_face(face)
        except Exception as err:
            break
    return verts, good_faces

for verts, faces in zip(Verts, Faces):
    bm = bmesh.new()
    v, f = add_mesh_to_bmesh(bm, verts, faces)
    Verts_out.append(v)
    Faces_out.append(f)
```
![image](https://user-images.githubusercontent.com/619340/173136636-41b19835-8d8f-4d66-bc6b-d78a6db6a3a4.png)

**Comment by zeffii** [comment]
>  That means those solids aren't manifold, right?

not necessarily, the duplicate faces still "bridge" the same verts, take for example
```python
[0, 1, 2] = first come first serve.
[2, 1, 0] = reversed
[1, 0, 2] = rotated reversed
[0, 2, 1] = rotated reversed
... etc
```
the snippet i posted doesn't check if the duplicates are reversed,  or simply rotated.. or rotated and reversed. I think the issue may be the conversion between Solid to Mesh, and the resulting mesh may not be manifold.

**Comment by zeffii** [comment]
@macdroid53  there is a mesh cleanup node .  

![image](https://user-images.githubusercontent.com/619340/173178898-e0eb94ff-44f7-48d4-898d-6cb2594e230d.png)

**Comment by zeffii** [comment]
```python
import numpy as np

def remove_degenerate_triangles(verts, faces):

    F = np.array(faces)
    M = np.sort(F, axis=-1, order=None)

    # from https://stackoverflow.com/a/16973510/1243487
    K = np.ascontiguousarray(M).view(np.dtype((np.void, M.dtype.itemsize * M.shape[1])))
    _, idx = np.unique(K, return_index=True)

    return verts, F[idx]
```

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/173190224-8e7600b8-9c60-4b70-aa09-2939960db845.png)

see the new filter button.

**Comment by macdroid53** [comment]
In the image I posted above, the Read FCStd node is different (note: I didn't mod it, I understood it was provided by someone involved with the sverchok project...).
Are you referring to the funnel icon on the Solid to Mesh node?

I see this, or similar, being more of an issue as more complex assemblies are used. The FC file in the OP is just a extracted portion of this file.
[RaspPi4-all.FCStd.zip](https://github.com/nortikin/sverchok/files/8884062/RaspPi4-all.FCStd.zip)

And even that is a reduction from the original:
[RaspPi4_initial.FCStd.zip](https://github.com/nortikin/sverchok/files/8884073/RaspPi4_initial.FCStd.zip)

This would be a typical application. In fact the various pieces would probably be subsequently used in Blender to do rendering and animation.

**Comment by zeffii** [comment]
> Are you referring to the funnel icon on the Solid to Mesh node?

yes, i haven't if or how to include that in the node in the master-branch, but the image shows the experiment works.

> In the image I posted above, the Read FCStd node is different

well, you may want to modify it in a similar way that I modified sverchok's version. Not much I can do about versions that aren't in Sverchok's distribution.

> the various pieces would probably be subsequently used in Blender to do rendering

yeah i'm sure excellent work can be done that way.

**Comment by zeffii** [comment]
i accidentally unzipped those FCStd files and see that they carry an xml with material information (color..etc) , sverchok can set up materials too..

![image](https://user-images.githubusercontent.com/619340/173194982-80f5369c-8fa4-43c3-bcd7-490d62e6e168.png)

**Comment by macdroid53** [comment]
I don't think they do have that sort of info at this point...haven't gotten that far in my exploration.

As for the version of FCStd_read.py...I though Haas got it from someone involved with the sverchok project...

**Comment by zeffii** [comment]
The folder contains this information, i just don't know how to read it yet.  but  - when i do : )
![image](https://user-images.githubusercontent.com/619340/173195373-6a003543-2044-492c-9f16-f8b4e49acb05.png)

**Comment by zeffii** [comment]
OK. well. this might be useful.
https://gist.github.com/yorikvanhavre/680156f59e2b42df8f5f5391cae2660b

**Comment by macdroid53** [comment]
Yes, I think Yorik wrote that for his architectural work. It seems to have never been fleshed out, but it may have info to help read the color info. In theory, there is material info possible though.
The source of the FCStd file/s I've uploaded here is originally geometry from a step file, in this particular case, those colors may have originated in the step file.

**Comment by zeffii** [comment]
i see, the freecad add-on has a few nice bits of code we can learn from : ]

**Comment by zeffii** [comment]
There's a considerable divergence between your version of the FCStd_read.py and the one that ships with Sverchok. I'm inclined to add this larger version as a MK2 (different classname, similar node) - and then update the code inside that node too. But at the same time update the `enum` as described earlier.

**Comment by macdroid53** [comment]
That code came from restart. 

But, I think it is experimental.

**Comment by zeffii** [comment]
ok!  the topic of this issue has drifted a little from the original intent;  the bad geometry produced by some algos. 
- a problem was identified
- the cause is now known
- a partial solution can be implemented for some modes of the Solid To Mesh node (some modes don't even work on my machine)

**Comment by macdroid53** [comment]
> i accidentally unzipped those FCStd files and see that they carry an xml with material information (color..etc) , sverchok can set up materials too..
> 
> ![image](https://user-images.githubusercontent.com/619340/173194982-80f5369c-8fa4-43c3-bcd7-490d62e6e168.png)

Having the colors would be nice when available.

But, at this point I'm not sure I know where this stands. Is there code here I should attempt to try (i.e. cobbling on my system, copy from this thread, etc.) Does it make sense for me to even tinker with it, or just wait...

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/4525 see the description for details. This is one step of many.

but I too hope @rastart can keep an eye on these nodes, in-case i do something stupid.

**Comment by macdroid53** [comment]
Given I have his version of Read_FCStd.py with the FName changes, I'm trying to determine what files I need to get to use this.

It appears these 3 files were changed for the merge:

nodes/exchange/FCStd_read.py
nodes/solid/solid_to_mesh_mk2.py
utils/sv_mesh_utils.py

But is my version Read_FCStd.py compatible?

**Comment by zeffii** [comment]
`solid_to_mesh_mk2` is a self contained change, but i added a function to `sv_mesh_utils`... so those are necessary for fixing triangles.

as for the FCStd_read  node, 
- the `Fname` stuff is necessary to change
- if you want a names socket, you can make those changes locally too probably. :)
    - i can add a `FCStd_read_experiment.py`  with all these fixes merged into your "experimental" version of the node

**Comment by macdroid53** [comment]
> `solid_to_mesh_mk2` is a self contained change, but i added a function to `sv_mesh_utils`... so those are necessary for fixing triangles.
> 
> as for the FCStd_read node,
> 
>     * the `Fname` stuff is necessary to change
> 
>     * if you want a names socket, you can make those changes locally too probably. :)
>       
>       * i can add a `FCStd_read_experiment.py`  with all these fixes merged into your "experimental" version of the node  (it will have a different class name and maybe be called `FCStd Read Mod`

If you do the `FCStd Read Mod`, maybe it then may make more sense for me to just do a git clone?

**Comment by zeffii** [comment]
yeah, probably.  The script made by yorik shows yet another way to extract geometry including face colors (other visual properties too), allowing for an automated way to extract materials.

what i'm just not sure about is how this node-based workflow has any benefit over a one-off operator import.   one thing i do know is that doing this will teach me about freecad :)

**Comment by macdroid53** [comment]
> yeah, probably. The script made by yorik shows yet another way to extract geometry including face colors (other visual properties too), allowing for an automated way to extract materials.
> 
So, should I do a clone now?

> what i'm just not sure about is how this node-based workflow has any benefit over a one-off operator import. one thing i do know is that doing this will teach me about freecad :)

Hmm...could you elaborate?

**Comment by macdroid53** [comment]
> > yeah, probably. The script made by yorik shows yet another way to extract geometry including face colors (other visual properties too), allowing for an automated way to extract materials.
> 
> So, should I do a clone now?
> 
> > what i'm just not sure about is how this node-based workflow has any benefit over a one-off operator import. one thing i do know is that doing this will teach me about freecad :)
> 
> Hmm...could you elaborate?
@zeffii 
Don't mean to be bothersome...but, if cloning it will help by letting me exercise things, I'd like to help. Same with the workflow. I have a pretty good handle on the FC workflow and would be happy to explain what I can.

**Comment by zeffii** [comment]
> Hmm...could you elaborate?  .... Don't mean to be bothersome

sure, questions welcome! it's nice to know this isn't happening in a vacuum. it's not clear how this would be a very pleasant experience due to the slowness of the importing code. My goal is to speed the importer code up ( it seems rather expensive ), while keeping it correct and generate materials. In my scripted node experiment i've added caching to save my nerves a little.

i spent most of my free time yesterday dissecting yorik's fcstd->blender importer script , i'm about 30% way into that process (geometry and transforms work now). Materials per face next.

![image](https://user-images.githubusercontent.com/619340/173755981-b1ffcbf0-6ccf-4c10-b712-fa553ba61a7b.png)

- the importer also produces geometry that is not accepted by `bmesh` (like Solid_to_Mesh node in Mefisto and trivial mode) but permitted by blender's Object data `Mesh` storage type, 
   -  I intentionally made the ViewerDraw node above as lenient as possible to allow it to be used to debug data like this visually.

**Comment by zeffii** [comment]
[freecad_utils_test_2022_06_15_08_55.zip](https://github.com/nortikin/sverchok/files/8907623/freecad_utils_test_2022_06_15_08_55.zip)

**Comment by macdroid53** [comment]
I need to reread your post. But a side note; apparently there is a version of sverchok that reads  material from the Label2 property. No idea what that means for what you are doing...

**Comment by zeffii** [comment]
yorik confirms that colors can be derived per face, that's part of the importer code i've still not read with much focus.

**Comment by macdroid53** [comment]
So, when is a good time for me to do a clone?

**Comment by zeffii** [comment]
continuing on the topic of " ValueError: faces.new(verts): face already exists "
here's a snippet that shows it
```python
import bmesh
from sverchok.utils.console_print import console_print as prin

bm = bmesh.new()
bm_verts = bm.verts
new = bm_verts.new
new((0.0, 1.0, 2.0))
new((1.0, 1.0, 2.0))
new((2.0, 1.0, 2.0))
new((3.0, 1.0, 2.0))
new((4.0, 1.0, 2.0))

bm_verts.index_update()
bm_verts.ensure_lookup_table()

desired_faces = [
    [0, 1, 2],
    [0, 1, 2, 3, 4],   # <-- this is allowd
    [2, 1, 0],       # <-- this is not.
    [1, 2, 3, 3],  
]
for f in desired_faces:
    try:
        bm.faces.new([bm_verts[i] for i in f])
    except Exception as err:
        prin(f"{f} -- {err}")

```
outputs
```console
[2, 1, 0] -- faces.new(verts): face already exists
[1, 2, 3, 3] -- faces.new(...): found the same (BMVert) used multiple times
```
it's not as hopeless as i thought. it appears to literally mean any similar length faces which share identical indices with any existing face will be prohibited
