### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by Tokarzewski** [nortikin/sverchok#4528]
## Problem statement

The Sverchok github repo does not have setup.py or pyproject.toml file that is useful for setting up the development environment.

pip install git+https://github.com/nortikin/sverchok.git

ERROR: git+https://github.com/nortikin/sverchok.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

## Expected result

Add setup.py or pyproject.toml so it will be easier for others to join the development process.

**Comment by zeffii** [comment]
We could do that, but there's very little environment setup needed to get started (with "Vanilla Sverchok"). 
- some Blender experience is helpful, navigating the interface
- Sverchok is an add-on, not a standalone package, and add-ons are installed/enabled in Blender before they can be useful, moreover blender add-ons can be installed in any number of directories depending on how the user has their Blender configured.
- point your terminal at your `scripts/addons_contrib` folder (and Blender must be told to look there for the scripts folder) and do
    - `git clone https://github.com/nortikin/sverchok.git`
- We don't do any compiling (yet). 
- The main dependency is Blender 3.0 +, which ships with numpy, 
- Other dependencies are optional and can be installed as-and-when they're needed using 
    - `add-on preferences -> Sverchok -> Extra nodes` 
        - (except FreeCAD which requires the Blender Python build to match the FreeCAD library build, discussed in the wiki )

so pip would look something like (referencing : https://stackoverflow.com/a/47393161/1243487 )
```python
pip install git+https://github.com/nortikin/sverchok.git --install-option="--scripts_path=path_to_scripts"
```
