### ISSUE TITLE
Freecad Windows installation is too much imprecise

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4538]
I am trying to install Freecad library on sverchok after changing from Blender 2.92 to 3.2 (I tried with 3.1.0 too, and the issue is the same), but the instructions are too much imprecise. 

- install/unzip FreeCAD : how is it even possible to install an archive file? I only unzipped it.
- enter freecad-python3-lib path that ends with ...\bin : what is "freecad-python3-lib" exactly? Not a file nor a folder, I verified. There is only one bin folder, so I used its path as the Freecad path, but it does not work. Should I precise the path up to the precise file? Put \bin\ at the end of the path instead of just \bin?

Could the installation procedure be clarified? I already spent more than an hour trying to install it, and last time, I only made it work by sheer luck after a few hours, too. All the other extensions are so simple to install, something really need to be done with this one, as spending multiple hours to make it work each time one changes Blender version is so annoying.

**Comment by rendetto** [comment]
Under which OS you're trying to set the things up?

**Comment by zeffii** [comment]
i only managed to get Blender 3.0 working with FreeCAD
download
1. blender-3.0.1-stable+v30.dc2d18018171-windows.amd64-release 
   - https://download.blender.org/release/Blender3.0/ the 3.0.1 probably works too
3. create the following `freecad_path.pth` file in this location
- `your_full_path\blender-3.0.1-stable+v30.dc2d18018171-windows.amd64-release\blender-3.0.1\3.0\python\lib\site-packages\freecad_path.pth`  , 
- this file would tell Blender's Python where to look for the FreeCAD Python binary resources.
4. the content of that file should read something like
```
your_full_path\FreeCAD_Python_3.9.12\FreeCAD_Python_3.9.12\Library\bin
```
5. you can get this `FreeCAD_Python_3.9.12` from here https://disk.yandex.com/d/jeIrD4k1MIy73g

**Comment by rendetto** [comment]
I'm running successfully the latest conda-packaged FreeCAD-0.20 (python3.10) with blender-3.2.0-stable (also python3.10) under win10.
The way I'm installing FreeCAD is by using conda with this command:

`conda create -p fc_env freecad python=3.10 --copy -y -c freecad/label/dev -c conda-forge
`

It created the FreeCAD package just as in this tutorial I wrote - https://github.com/nortikin/sverchok/issues/4131 
The Blender I'm using is just extracted from zip somewhere, and after that I just pointed out in the Addon interface where is the freecad bin (again as in the tutorial I mentioned above). 
Never had problems :/

**Comment by zeffii** [comment]
oh cool, rendetto, i will try that too :)

**Comment by rendetto** [comment]
I tested some heavy old scenes in this combination and I noticed really impressive gain in the performance. So I strongly recommend it :)

**Comment by ArpegorPSGH** [comment]
Ok, I managed to install Freecad, but it is such a hassle... According to rendetto, only line of code is enough to get Freecad, so why not automating its installation like for the other packages?

**Comment by zeffii** [comment]
confirmed.
- `conda create -p fc_env freecad python=3.10 --copy -y -c freecad/label/dev -c conda-forge`  (can take several minutes... )
- setting path to `your_path\fc_env\Library\bin`

![image](https://user-images.githubusercontent.com/619340/174493874-87f969b7-c499-49d4-962d-5bc908e7c045.png)

**Comment by zeffii** [comment]
big thanks to @rendetto  :)

> so why not automating its installation like for the other packages?

With this method perhaps we might be able to offer a single button install too, but it may take a while to get that foolproof too.  If someone offers to do a PR for it :)

**Comment by rendetto** [comment]
> so why not automating its installation like for the other packages?

My thoughts... this installation is huge and it's not just a library. Also I know that it works under windows but what about other OS.
I personally would prefer to do it separate from SV until there is some way to install only the library thingy from the whole FreeCAD ...if that's possible. There is also the thing that this conda package is far from official and being that we cannot rely on it for stability ...or installability. We don't know if this conda repository will exist and how it will change in the future.

**Comment by zeffii** [comment]
the steps i wrote above are literally all i did, but here's some clarification:  
- `conda` makes the `fc_env` folder in whatever folder you land in when you launch the `anaconda prompt`.  For me that happened to be 
- `(base) C:\Users\zeffi>`
- so my freecad_path.pth file reads `C:\Users\zeffi\fc_env\Library\bin\`

![image](https://user-images.githubusercontent.com/619340/174577367-37a50381-35c4-45da-88bb-2ff9d7e35512.png)

**Comment by zeffii** [comment]
> I think an up to date tutorial on how to install freecad this way in the simplest manner should be added to the documentation or at least a link pointing to such a tutorial.

yeah it should be. i volunteer you @ArpegorPSGH to write those instructions as soon as you get comfortable with it.

**Comment by ArpegorPSGH** [comment]
There is no need to specifically create a freecad_path.pth file, no? If we set the path directly in sverchok, then press the set path button, it should work the same, right?

**Comment by zeffii** [comment]
correct @ArpegorPSGH .

**Comment by ArpegorPSGH** [comment]
Okay, the instalation instructions have been updated and I verified the procedure works for me too. Now, if no one wants to automate installation, I believe this issue can be closed.

**Comment by zeffii** [comment]
Thanks for updating the docs!

> Now, if no one wants to automate installation

it's not that we don't want to provide a one click solution, but like @rendetto mentions here https://github.com/nortikin/sverchok/issues/4538#issuecomment-1159788275 the freecad dependency isn't exactly trivial or certain. There's also high variability in end-user situations (os, disk-permissions, blender versions, and some people use their system's python rather than blender's supplied python ) ,
