### ISSUE TITLE
Dual Mesh and Clip Vertices nodes failing to work together

### ISSUE THREAD

**Issue by Marcus-Richmond** [nortikin/sverchok#4542]
## Problem statement

As part of a node setup, I would like to use the Dual Mesh node connected to the Clip Vertices node, like this:

![image](https://user-images.githubusercontent.com/59568811/175451815-f2f85fc1-0fdb-44a7-a3b8-fe4d826b6b86.png)

The following error is from the Debug print node: `[ERROR] sverchok.utils.sv_bmesh_utils:541 : faces.new(...): found the same (BMVert) used multiple times`

After looking here: [https://github.com/nortikin/sverchok/issues/3989](https://github.com/nortikin/sverchok/issues/3989), I tried using the following code and mesh clean node, but without any luck:

exec node
![image](https://user-images.githubusercontent.com/59568811/175452290-176c084f-cf93-4cad-9a0e-8a5258c306eb.png)

mesh clean
![image](https://user-images.githubusercontent.com/59568811/175452383-16c05287-e4a5-49a6-8cc2-f04da5639734.png)
(I tried the various options with the mesh clean node, but didn't resolve the error)

The Clip Vertices node still works without the Dual Mesh node however:
![image](https://user-images.githubusercontent.com/59568811/175453082-5b957cf0-644f-4bc2-8976-b3afc122aade.png)

Seems like without edges being input into the Clip Vertices node, this node returns this error. I tried another setup where the Clip Vertices node was only being passed verts/polygons and no edges:
![image](https://user-images.githubusercontent.com/59568811/175453632-39e0c2d2-1c59-4240-981c-7a2b2169a11d.png)

Again, looking at [https://github.com/nortikin/sverchok/issues/3989](https://github.com/nortikin/sverchok/issues/3989), I see the discussion is about duplicate faces, but none of these node setups appear to be creating duplicate faces. 

## Sverchok version

Sverchok 1.1.0 with Blender 3.1.2

**Comment by Durman** [comment]
This is certainly a bug because the example below should work according to the node documentation. 

![image](https://user-images.githubusercontent.com/28003269/175460424-82b75145-4146-40ed-b443-443739efd9e6.png)

**Comment by Durman** [comment]
The problem is that this line is not called when edges are not provided.

https://github.com/nortikin/sverchok/blob/61339672e8ec7cdfb7853fe84c6c956fb87e6b58/utils/sv_bmesh_utils.py#L108

**Comment by zeffii** [comment]
weirdly enough that `bm.edges.index_update()` seems to have been always dependent on the presence of edges input, and somehow it now bugs out.  (earliest version i can find https://github.com/nortikin/sverchok/blob/df942c23e73d6e093cf1d2306e3c10ee6e5bbecd/utils/sv_bmesh_utils.py)

**Comment by zeffii** [comment]
also, kind of awkward that the cross section node outputs "faces" from an "edges" socket (Seen https://user-images.githubusercontent.com/59568811/175453632-39e0c2d2-1c59-4240-981c-7a2b2169a11d.png )

**Comment by zeffii** [comment]
the error is emanating from `truncate_vertices`
```python
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_bmesh_utils.py", line 541, in truncate_vertices
    new_bm_add_face(new_face)
ValueError: faces.new(...): found the same (BMVert) used multiple times
```

**Comment by zeffii** [comment]
maybe we dedent `bm.edges.index_update()` in bmesh_from_pydata ? @Durman

**Comment by Durman** [comment]
I thought about adding extra property to the function because calling `index_update` method might be expensive (not sure how much)

```py
def bmesh_from_pydata(..., edge_update=False):
    ...
    if has_element(edges) or edge_update:
        bm.edges.index_update()
    ...
```
It should not impact on existing usage of the function, especially if to catch the `has_element` function result.

**Comment by zeffii** [comment]
i thought about that too, for the same reasons, but i doubt the computational penalty is dramatic. i'll test and change if necessary

**Comment by zeffii** [comment]
a uvsphere 300*300 = 89700 is number of faces,  the following is always updating edge indices.
```console
89700
bmesh_from_pydata: 177.67 ms
```
vs... a switch `index_edges` (which i think is a more descriptive name)
```console
89700
bmesh_from_pydata: 109.94 ms
```

**Comment by zeffii** [comment]
indexing edges is now an explicit switch in the `bmesh_from_pydata` function call. @Durman
