### ISSUE TITLE
CropMesh2d - sweep line

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#4554]
I don't know if this is a bug or whether I'm fundamentally not understanding its feature-set, @durman @vicdoval  ?

![image](https://user-images.githubusercontent.com/619340/177126964-960b7b01-a7b9-4923-a20e-28f97b433425.png)

[secret_green_2022_07_04_09_34.zip](https://github.com/nortikin/sverchok/files/9038240/secret_green_2022_07_04_09_34.zip)

something like this should be possible with this node? 
![image](https://user-images.githubusercontent.com/619340/177127515-316e0957-0f03-4c14-ba8b-559dd958b1b8.png)

**Comment by zeffii** [comment]
shapely snlite script incoming.

**Comment by zeffii** [comment]
with optional joining... but this is slow :)
```python
"""
>in verts_a v
>in faces_a s
>in verts_b v
out verts_c v
out faces_c s
"""
import mathutils
import shapely
from shapely.geometry import Polygon, Point

def shapely_polygon(coords):
    return Polygon([Point(v[0], v[1]) for v in coords])

def tessellated(verts, faces):
    for indices in faces:
        coords = [verts[i] for i in indices]
        if len(coords) == 3:
            yield shapely_polygon(coords)
        pols = mathutils.geometry.tessellate_polygon([coords])
        for pol in pols:
            yield shapely_polygon([verts[indices[i]] for i in pol])

collect_verts = verts_c.append
collect_face = faces_c.append

joined = True
object_b = shapely_polygon(verts_b[0])
for fragment in tessellated(verts_a[0], faces_a[0]):
    object_c = fragment.intersection(object_b)
    if hasattr(object_c, 'exterior'):
        tri = [(x, y, 0.0) for x, y in object_c.exterior.coords[:]]
        if tri:
            if joined:
                offset = len(verts_c)
                faces_c.extend([[idx+offset for idx in range(len(tri))]])
                verts_c.extend(tri)
            else:
                collect_verts(tri)
                collect_face([list(range(len(tri)))])
if joined:
    verts_c = [verts_c]
    faces_c = [faces_c]
```

**Comment by Durman** [comment]
It seems works

![image](https://user-images.githubusercontent.com/28003269/177250186-3729f94a-5304-426d-be65-08bc56cf5f31.png)

![crop test](https://user-images.githubusercontent.com/28003269/177250082-ff8c75b2-e3ce-4d55-aa08-8fc4d41fa941.gif)

[untitled.zip](https://github.com/nortikin/sverchok/files/9043238/untitled.zip)
