### ISSUE TITLE
Mesh Join outputs broken list

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4558]
The Mesh join Node outputs a broken list with an additionnal comma like that : [[[a1,a2],[b1,b2]]**,**]. It is like it tried adding one more list, but put an empty object instead.
It was not the case before, I believe it stopped functionning properly after an update, but I just noticed it today. I attached a Blender file with a node tree illustrating the problem :
[MeshJoinProblemExample.zip](https://github.com/nortikin/sverchok/files/9074278/MeshJoinProblemExample.zip)

**Comment by zeffii** [comment]
mesh join is outputting a tuple as an outer wrapper, and for example `(1, )` is a legal tuple, so `(list,)` would be too.  

![image](https://user-images.githubusercontent.com/619340/178092911-cc1a3075-6422-4ca4-a574-895424a434b7.png)

that shouldn't be a problem.

**Comment by zeffii** [comment]
the code that joins the meshes has essentially been unchanged for about 1.5 years

**Comment by ArpegorPSGH** [comment]
Ok, so my problem must not come from this. The thing is I connect the output to a merge dy distance node, and it crashes. I will try to investigate the problem and post a complement here if I don't find an answer.

**Comment by zeffii** [comment]
there's not many nodes that can crash Blender/sverchok,  but if you're using any `bpy.ops` directly or any of the following nodes under certain circumstances: https://github.com/nortikin/sverchok/search?q=crash

**Comment by ArpegorPSGH** [comment]
No, it's okay, I found the problem and solved it, it was just a wrong nesting level of lists.
