### ISSUE TITLE
Can't activate Sverchok 1.1.0 in Blender 3.2.0 with M1 macOS 12.4 

### ISSUE THREAD

**Issue by labaus** [nortikin/sverchok#4559]
## Problem statement

Please describe your problem here.

## Steps to reproduce

1. 
<img width="939" alt="Screen Shot 2022-07-10 at 5 30 54 pm" src="https://user-images.githubusercontent.com/65227054/178139384-72d28d58-d6b5-4062-a059-4431d126875b.png">
<img width="939" alt="Screen Shot 2022-07-10 at 5 30 54 pm" src="https://user-images.githubusercontent.com/65227054/178139399-46af3cf1-0d98-4498-9a51-ad2c3cf34083.png">

## Expected result

What did you expect to see as a result of those steps?

## Actual result

What did you actually get?

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by zeffii** [comment]
restart blender,  press the `tick box` once, to enable sverchok and wait until it becomes ticked. (it might take a few seconds).

**Comment by labaus** [comment]
it works now following your step.
