### ISSUE TITLE
One name for different items 

### ISSUE THREAD

**Issue by soratnikov** [nortikin/sverchok#4561]
## Problem statement

One name for different items in user guide (see attachment screenshot)

## Steps to reproduce

1. Open link https://nortikin.github.io/sverchok/docs/nodes/list_masks/mask_to_index.html
2. Open link https://nortikin.github.io/sverchok/docs/nodes/list_masks/index_to_mask.html
3. Compare
![Screenshot_%Nd-350](https://user-images.githubusercontent.com/96102459/178142810-ef5074da-0f97-4435-a417-b25d1b73fd95.png)

**Comment by zeffii** [comment]
thanks, will fix.

**Comment by zeffii** [comment]
@soratnikov  it might take a while for the online docs to synchronize.
