### ISSUE TITLE
Get Object Data node and curve object

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4562]
## Problem statement

For some reason Blender crashes when a curve object is used in Get Object Data node and the curve object is edited. However, there are no any problems when the curve is connected to a Curve Input node.

https://user-images.githubusercontent.com/28003269/178191867-3e3a39d9-adde-4f49-b8ae-e0b0d6d82d68.mp4

**Comment by Durman** [comment]
It seems this line causes the crash. It looks like calling the method, when a curve is in edit mode, is unsafe.

https://github.com/nortikin/sverchok/blob/d7ad9b9fdfcd1418c03e3efe57ed31b89ca6cce5/nodes/scene/get_objects_data.py#L329

Also I was able to reproduce this problem in Sv1.0 when the scene handler was not introduced yet, so this problem already exists for a wile.

One of solutions is to forbid using curves by the node but it requires either new version of the node or it will break old layouts.

Another solution is to include separate logic for handling curve objects.

🤔

**Comment by zeffii** [comment]
yeah i think we've discussed something related to this in the past with no real solution..
- https://github.com/nortikin/sverchok/issues/1028#issuecomment-267291352
weid the above seems like the reverse of the problem.

if we can get the correct control and knots in edit mode (and whatever other curve data), we could hand calculate the resulting polyline, as a last resort.

**Comment by zeffii** [comment]
oh yeah.. this crashes blender..
```python
import bpy
import bmesh

obj = bpy.context.edit_object
data = obj.to_mesh()
data.append([v[:] for v in data.vertices])

```

**Comment by zeffii** [comment]
ooh look, a flow diagram in markdown!

```mermaid
flowchart TD
A[Object] --> B[Curve?];
B -- Edit Mode --> C[something...];
B -- Object Mode --> D[current behaviour];


```

**Comment by Durman** [comment]
It seems that Curve Input node works perfectly normal with curves in edit mode. Probably, we can reuse its code in the Get Object Data node.

```mermaid
classDiagram
class CurveInputNode {
    process()
}
class GetObjectDataNode {
    process()
}
class UtilsModule {
    read_curve_data(curve) List~vert~
}
CurveInputNode ..> UtilsModule
GetObjectDataNode ..> UtilsModule
```

**Comment by zeffii** [comment]
>  if we can get the correct control and knots in edit mode (and whatever other curve data), we could hand calculate the resulting polyline, as a last resort.

as a last resort.

perhaps a hack of is possible..
```python
import bpy
import bmesh

obj = bpy.context.edit_object
# if type==Curve and in edit mode
temp_curve_data = obj.to_curve().copy()   # maybe from "temp curve data" to "permanent snapshot"?
proxy_object = get_surrogate_object(temp_curve_data)
data = proxy_object.to_mesh(......)
f = [v[:] for v in data.vertices]

```

**Comment by zeffii** [comment]
this does work from texteditor
```python
import bpy
import bmesh

def get_surrogate_object(proxy_curve_data):
    o = bpy.data.objects.get("Surrogate")
    o.data = proxy_curve_data
    return o

obj = bpy.context.edit_object
if obj.type == "CURVE":
    depsgraph = bpy.context.evaluated_depsgraph_get()
    temp_curve_data = obj.to_curve(depsgraph=depsgraph).copy()   # maybe from "temp curve data" to "permanent snapshot"?
    proxy_object = get_surrogate_object(temp_curve_data)
    data = proxy_object.to_mesh()
    f = [v.co[:] for v in data.vertices]
    print(f)

```

**Comment by Durman** [comment]
I tested it in Blender 3.1 and it works just fine. So I created a bug report because it seems it is related to new curve implementation - https://developer.blender.org/T99661

For now, simplest solution is just pass the execution if a curve is in edit mode. Or we can use `surrogate object` but the solution scares me. ))

**Comment by zeffii** [comment]
surrogate object is most unsatisfying indeed.
