### ISSUE TITLE
Multiple Viewer Index nodes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4568]
## Problem statement

It seems multiple nodes does not work correctly with multiple objects.

![image](https://user-images.githubusercontent.com/28003269/178925560-575c7ecf-2f19-45ed-980f-fd45a3a24943.png)
[untitled2.zip](https://github.com/nortikin/sverchok/files/9109505/untitled2.zip)

**Comment by zeffii** [comment]
the matrix is only applied to the first object in the second idxviewer.

**Comment by zeffii** [comment]
i am reluctant to call it a bug, because i intentionally coded it this way.  I'll agree that maybe it is unexpected/inconsistent behaviour

https://github.com/nortikin/sverchok/blob/78ef71e5efa06d74c6c7dcde6297692a9e254e3d/nodes/viz/viewer_idx28.py#L197-L201

**Comment by Durman** [comment]
I see. Then it is vectorization problem (similar to this #3908). What was the intention to code it in this way?

I think we have convention of auto matching objects number inside nodes.

**Comment by zeffii** [comment]
same can be done for edges/faces -but- i like a debug tool to be as minimal as possible, inventing data is not minimal.

**Comment by zeffii** [comment]
it's tempting to revise the node further
- text alignment
- quick-scale font
- index range selection
- element selection (as per #4566 )
