### ISSUE TITLE
Speed up vectorization and Bmesh nodes (experiment)

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4572]
Vectorization is slow in Sverchok. I used Split Mesh Element node for speed tests. They show that the node works about 20 times slower with the same amount of data split into multiple objects. The speed difference is dependent on size and number of objects. The smaller peace and larger their number the greater the difference.

The idea to solve this problem was to merge all separate object into single one, perform operation of the node and split them back into initial pieces. Here is implementation - [island_mesh](https://github.com/nortikin/sverchok/tree/island_mesh).

The result is that it gives some performance improvement. In my test it worked about 2 times faster. But also such approach has an overhead in case of a single mesh it works 2 times slower. It's not easy to find the border when such approach starts to give the boost. And improvement over 2 times (in best corner case) is not enough to worth the effort.

Such approach would work more efficient if, between joining and splitting mesh, it could perform more operation on the mesh. We can create separate node for joining mesh and splitting it back into initial pieces but it also requires changes of all modifier nodes which together with vertices, edges and faces should return old their indexes so it would possible to split mesh. But in this case it's not clear what is use case of vectorization then.

## Bmesh nodes

Interesting thing is that even with one large (10k faces) object the actual function of the node takes only about **4%** of all time. The rest of the time it spends in converting Python lists into bmesh and back. (With 160k faces it still takes only **4%**)

![image](https://user-images.githubusercontent.com/28003269/179192203-418740f6-bac6-4b6e-aa37-578a2b0e02f6.png)

So it's possible to make the node **20 times faster** if we simply remove the conversion part by adding input and output Bmesh sockets. Extra advantage of having this sockets is that Blender API can show Bmesh data directly and Bmesh viewer can be the fastest viewer in Sverchok.

There are though next problems:
- It's not clear where and when to clear the bmesh objects
- Should bmesh sockets use vectorization? Vectorization potentially can diminish the advantages of Bmesh. Creating, even empty, a lot of Bmesh objects can take a lot of memory and crush Blender
- Each node should work on it's own copy of a bmesh object. It's probably possible to do with `bmesh.ops.duplicate`. The question is how it's efficient and won't it crash Blender with a lot of bmesh copies.
- It can require a lot of conversions from/to bmesh (extra nodes in a tree) because we can't extend bmesh functionality and have to use our Python/NumPy implementation.

**Comment by zeffii** [comment]
another upside to a suite of exclusively bm socket nodes is that the internals have a chance to be less complicated than the `vef` counterpart.

**Comment by Durman** [comment]
I remember there was a report about indexing problem - #3029. But in general bmesh nodes work well. I'm not sure that it's worth efforts because bmesh module has limited number operations which hardly get any development in a future. So it will force users to use conversion nodes a lot and performance will be lost any way.

**Comment by ArpegorPSGH** [comment]
Couldn't it be possible to, for each node using numpy/Bmesh internally, offer the possibility to switch entry type between python and numpy/Bmesh data, or even recognize it automatically. That way, you would loose far less time if you use multiple numpy/Bmesh nodes in a row, and it would make clear which nodes are working internally with what, so users could optimize their trees.

**Comment by Durman** [comment]
Bmesh object can't be passed via Vertices/Edges/Faces sockets. It's required one separate socket type. This will be enough for users to see that such a node uses Bmesh internally.
