### ISSUE TITLE
Sverchok Node Tree Updates needlessly

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4576]
## Problem statement

With the latest version of sverchok, it seems anytime I connect a new node, existing nodes that are on a separate unrelated branch get updated which slows down all execution.

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce

1. Create a node tree that is time consuming to complete
2. Add a new node and connetc

## Expected result

Only the affected/downstream nodes to be updated

## Actual result

Unrelated nodes get updated.

## Sverchok version

Latest from downloading from the Green Code button as a ZIP file

**Comment by Durman** [comment]
Could you upload a file with such problem?

**Comment by wassimj** [comment]
I was recording a video and noticed the exact behaviour: If you connect a second output to the same output socket, then all nodes that were previously connected to that output socket get updated. This can cause a cascade of un-necessary updates. To test:
1. Create a Sphere node with U=500 and V=500 (to slow it down)
2. Attach a Stethoscope to the Vertices output socket
3. Attach a Matrix Out to the Vertices output socket
You will notice that the Stethoscope node also gets re-updated when it shouldn't (See the messages on top left about what nodes are being updated)

**Comment by Durman** [comment]
Now it's clear and ,actually, it's intendent behavior for now, but of cause it should be improved in future.

The problem is that many nodes uses next optimization:
```py
def process(self):
    ...
    if self.outputs[0].is_linked:
        self.outputs[0].sv_set(data)
    if self.outputs[1].is_linked:
        self.outputs[1].sv_set(data)
```
It means that update system should process the node not only when input data was changed bat also when output connection was changed. It of cause leads to redundant calculations.

We can either:
- simply remove all such optimizations
- or move the optimization into update system (#4322)

**Comment by wassimj** [comment]
Thank you. From a user perspective, the cost can be really high if the existing chain of nodes is long and/or time-consuming to compute.

**Comment by wassimj** [comment]
By the way, even dragging and dropping a new node seems to trigger updates. It has slowed down the workflow considerably. I would appreciate an urgent look at this if it can be remedied. Thank you!

**Comment by wassimj** [comment]
Here is my process. I tested this on an example IFC file from BuildingSmart. I took only some walls and closed off one boundary manually. The rest is all automated. Here is a summary:
Create a base Face (the large white surface)
Convert the walls to Topologic Cells
Get the Wires of the Cells
Project the Wires unto the base Face
Merge all the Wires into one Cluster
Boolean "Slice" the base Face with the Cluster: You get a Shell of Faces
Start filtering to remove faces that we know are not "Rooms":
 1. Any face with 3 edges (no triangular rooms)
 2. Any face less than a certain area  (most walls hopefully have an area less than a typical room)
 3. Optional: You can compute the 'compactness' of a face and filter on that. Walls tend to be less compact in shape than rooms
 4. Finally, to remove outer boundary face, filter by rooms that do not have holes (most rooms we are interested in do not have a hole)

Then convert back to Wires, remove collinear edges, convert back to faces, Cell.ByThickened Face! Done!!

<img width="800" alt="max01" src="https://user-images.githubusercontent.com/6302909/181081215-df1f73e2-6419-44d4-9b14-a418ced73813.png">
<img width="800" alt="max02" src="https://user-images.githubusercontent.com/6302909/181081221-e2f4f4fa-97ec-496a-b42b-0eaadac0be96.png">
<img width="800" alt="max03" src="https://user-images.githubusercontent.com/6302909/181081225-880838bd-fc9d-4d0d-b9f0-1dbab79cceb0.png">
<img width="800" alt="max04" src="https://user-images.githubusercontent.com/6302909/181081228-f083c7a0-1cde-42f2-9f88-6963da78b04f.png">
<img width="800" alt="max05" src="https://user-images.githubusercontent.com/6302909/181081230-1e4bce17-a800-4469-9838-d3582e408377.png">
<img width="800" alt="max06" src="https://user-images.githubusercontent.com/6302909/181081235-e397fa05-e4ce-4dad-b50a-1e4e5392d29c.png">
<img width="800" alt="max07" src="https://user-images.githubusercontent.com/6302909/181081236-993edec7-5540-4d49-973c-a81f91685acd.png">
<img width="800" alt="max08" src="https://user-images.githubusercontent.com/6302909/181081240-f2d3a9a2-1486-4743-bbc9-38c97987bf97.png">

**Comment by Durman** [comment]
I thought to wait with the fix for next Sverchok version because it requires a lot of small changes and can bring some instability. But probably what I can do now is to add some temporary node attribute which would mark a node for update system that it should not be updated when its output sockets are connected. In this case you have to add the attribute to all nodes which should not be updated.

**Comment by wassimj** [comment]
I think I would wait for next release because I don’t control the code for all nodes. So if my workflow depends on an OOTB node and that nodes is connected to a time consuming Topologic nodes, I would still face the same problem because the input socket data ‘changed’. Thank you for looking at this and solving it. Also please look at what dragging and dropping a new disconnected node sometimes triggers an update and the GUI freezes until the update is done. In that case no sockets are connected to trigger an update. Weird.

**Comment by Durman** [comment]
I see what you mean. In an example below the nodes will be called each time when new node is added to the tree. This because Get Objects Data uses scene update handler. Unfortunately the handler does not produce information about what exactly was change in a scene and it's difficult to filter out specific events. I'll have a look what can be done.

![image](https://user-images.githubusercontent.com/28003269/181418433-6c7c7b8e-cec7-4fe9-b31c-dabbe816c6a3.png)

**Comment by wassimj** [comment]
I downloaded the latest sverchok software using the green code button then download ZIP and installed. Sadly this does not seem to be resolved. If you notice in the attached images, if I add a second stethoscope, the Vertex.ByCoordinates node re-triggers and creates a brand new vertex with a different address
<img width="1309" alt="vertex01" src="https://user-images.githubusercontent.com/6302909/182774267-52f588a4-476f-49b1-b04e-f59a73ef76ad.png">
<img width="1332" alt="vertex02" src="https://user-images.githubusercontent.com/6302909/182774287-6574c635-031a-4170-8f4c-f83d87838bd3.png">
.

**Comment by Durman** [comment]
You've reported two problems here, I fixed one of them believe.

Another problem should be fixed within #4322 
But I'm not sure when such changes should be introduce because they way I think to implement them might broke all other Sverchok add-ons.
The simplest way, as I said, is to remove extra [checks](https://github.com/nortikin/sverchok/issues/4576#issuecomment-1186821253) inside nodes and I'm not against it but I guess that @portnov @zeffii @vicdoval think that they are must have.

**Comment by wassimj** [comment]
Apologies for the confusion. Can you please explain what the two problems are and which one is fixed? Thank you.

**Comment by wassimj** [comment]
I just modified the code inside my Vertex.ByCoordinates to remove the check for output links and actually it makes it worse. It still re-triggers the node and therefore can create three different outputs: 1 when the node is created, 2 when an output is connected, 3 when a second output is connected and so on and so forth.
<img width="1633" alt="step01" src="https://user-images.githubusercontent.com/6302909/182785404-7d8e192c-ab69-4bba-b4f5-19d633ba6cf9.png">
<img width="1666" alt="step02" src="https://user-images.githubusercontent.com/6302909/182785401-d11e002a-9253-4321-8468-c11424c6c7b9.png">
<img width="1699" alt="step03" src="https://user-images.githubusercontent.com/6302909/182785396-9d7d6258-7243-426e-a1b6-1db7c62b01b0.png">

**Comment by Durman** [comment]
> Apologies for the confusion. Can you please explain what the two problems are and which one is fixed? Thank you.

I mean this.

>  Also please look at why dragging and dropping a new disconnected node sometimes triggers an update and the GUI freezes until the update is done. In that case no sockets are connected to trigger an update. Weird.

All described above behavior, as I said, is expected for now.

**Comment by wassimj** [comment]
ok thank you. My current workaround for now is when I create a node, I immediately mute it (by pressing M on it), connect all the nodes that need to emanate from it, then unmute it to see the result without having to create multiple copies of the output.

**Comment by Durman** [comment]
I'm sorry you have to do all this and I hope that Sverchok will get improvement in this area once.
