### ISSUE TITLE
List Item Insert - negative indexing

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4578]
## Problem statement

It looks like a bug that `-1` index does not refer to the last element.

![image](https://user-images.githubusercontent.com/28003269/179668546-7dc79f62-3504-4671-9f7d-70d094d0c047.png)

#3827

**Comment by zeffii** [comment]
interesting .wtf is happening there? :)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/94b5cf329b1f82a472b5e255f0cadb3d0d37e21b/nodes/list_struct/item_insert.py#L107-L110

**Comment by Durman** [comment]
The approach is not efficient for replace mode. Should be `data_out[ind] = i`

**Comment by zeffii** [comment]
hmm.. yeah puzzling implementation.
```python
            for ind, i in zip(*params):
                idx = ind % len(data)  # translate to positive idx
                if self.replace:
                    data_out[idx] = i
                else:
                    data_out.insert(idx, i)
```

**Comment by Durman** [comment]
Or like this =). But this, I think, does not give big performance improvement, at least compare to moving from `O(len(data))` to `O(1)`.

```py
if self.replace:
    for ind, i in zip(*params):
        idx = ind % len(data)  # translate to positive idx
        data_out[idx] = i
else:
    for ind, i in zip(*params):
        idx = ind % len(data)  # translate to positive idx
        data_out.insert(idx, i)
```

**Comment by zeffii** [comment]
hehe .. or that.  commit if you wish :)

**Comment by Durman** [comment]
![image](https://user-images.githubusercontent.com/28003269/188558260-15f86843-f4c5-4eca-9a1b-c5b7d4f16628.png)

It seems another bug was produced by the fix. I guess next string is to blame

https://github.com/nortikin/sverchok/blob/510c1e382799375cd7435c3fb695c48a29bf1425/nodes/list_struct/item_insert.py#L108

**Comment by Durman** [comment]
7cb34506b50c978e3a062b3b48a52c1239ea93e1

**Comment by Durman** [comment]
The fix changes behavior in some cases. It seems that previous behavior is not valid in the example

![image](https://user-images.githubusercontent.com/28003269/191659840-b26c8a75-f7b1-4aef-8b61-73a1729f5671.png)
