### ISSUE TITLE
Geodesic objects

### ISSUE THREAD

**Issue by PKHG** [nortikin/sverchok#459]
Some time ago I made the "Geodesic_domes" addon suitable for  2.7*
To some degree it could be done in SV too.
So I tried using Script 2 (analog to the example of lines https://github.com/nortikin/sverchok/issues/458
Seems to work see:
![sv_tetrahedron](https://cloud.githubusercontent.com/assets/1043959/4898198/facb6fe0-640d-11e4-8eb0-668b2c522359.jpg)

Two things:
First is how do I generate the faces? 

``` python
    @staticmethod
    def make_faces(*param):
        return [[0,1,2],[0,2,3],[0,1,3],[1,2,3]]
    (<snip>inputs)
    outputs = [("v", "Verts", "make_tetraeder"),
                ("s", "Edges", "make_edges"),]
               #(f","Faces", "make_faces")]  <==== ????? does not work
```

Second if you know geodesic_domes is it a good idea to build (parts) in SV?

Peter

**Comment by PKHG** [comment]
detected  a small error, omission

in the script adjust the second line:
[code]
 elif which == 6: #icosaeder
            edgeskeleton = [[0,1],[0,2],[0,3],[0,4],[0,5],[1,2],[2,3],[3,4],[4,5],[5,1],
[/code]
the edges [0,4], [0.5] are missing

**Comment by zeffii** [comment]
@PKHG 
instead of 
```
        elif type_geodesic == 6:  #icosaeder
            edgeskeleton = [(0,1),(0,2),(0,3),(1,2),(2,3),(3,4),(4,5),(5,1),
                            (1,6),(2,6),(2,7),(3,7),(3,8),(4,8),(4,9),(5,10),
                            (1,10),(6,7),(7,8),(8,9),(9,10),(10,6),(6,11),(7,11),
                            (8,11),(9,11),(10,11)]
```
should it be
```
        elif type_geodesic == 6:  #icosaeder
            edgeskeleton = [(0,1),(0,2),(0,3),(0,4),(0,5),(1,2),(2,3),(3,4),(4,5),(5,1),
                            (1,6),(2,6),(2,7),(3,7),(3,8),(4,8),(4,9),(5,10),
                            (1,10),(6,7),(7,8),(8,9),(9,10),(10,6),(6,11),(7,11),
                            (8,11),(9,11),(10,11)]
```

**Comment by zeffii** [comment]
@PKHG  fixed, and pep8 now

**Comment by PKHG** [comment]
@Dealga ..
Ok suggestion read good, thanks

2015-01-29 12:54 GMT+01:00 Dealga McArdle <notifications@github.com>:
