### ISSUE TITLE
Errors no longer reported where they occur in the python file

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4591]
## Problem statement

It used to be that if an error occurred, I can inspect the system console and it would tell me exactly in what line number in the node .py file the error occurred. This is no longer the case in the newest release which makes debugging a lot more difficult.

**Comment by Durman** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/28003269/180697357-1ad5c19b-072e-4069-a2ec-b3b0944adfd2.png)

Also, switch on debug mode if you need traceback.

**Comment by wassimj** [comment]
How do I switch on debug mode in sverchok?

**Comment by Durman** [comment]
I was not correct. It's not a mode but a logging level (in add-on settings).

![image](https://user-images.githubusercontent.com/28003269/180702647-c25d8b58-ed2d-4a7b-98ce-d6aaa594d475.png)

**Comment by wassimj** [comment]
Thank you. This is now working as expected.

**Comment by Durman** [comment]
I've added this into docs - http://nortikin.github.io/sverchok/docs/contributing/node_api.html#printing-logging
