### ISSUE TITLE
Temporal Viewer and Viewer Draw Change of Behaviour

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4592]
## Problem statement

In previous versions of sverchok, Temporal viewer and Viewer Draw would gracefully handle a connected but empty list of faces or a connected but empty list of edges. If there are only edges and vertices, it would draw a wireframe. If there are only vertices, it would draw only vertices.

Now,  it will not draw anything if the connected socket of Faces does not receive a list of faces. The workaround is to disconnect the wire feeding that socket.

Topologic has a node called Topology.Geometry that converts all possible Topologies (vertex, edge, wire, face, shell, cell, cellcomplex) to a Blender mesh (vertices, edges, faces). So all three output sockets would be connected to Temporal Viewer or Viewer Draw, but not all will have data.

Is it possible to revert to the old behaviour? Thanks

**Comment by zeffii** [comment]
so you have a node that passes something like 
```python
vertex_lists = [verts, verts, verts]
edge_lists =   [edges, [],    edges]
face_lists =   [[],    faces, faces]
```

**Comment by zeffii** [comment]
The temporal viewer is merely an instance of a `viewer draw (vd)` with cosmetics changed, so what happens to `vd` will happen to `temporal vd`.

i'm not aware of any changes that have taken place in the viewer draw node. The blame file confirms this node wasn't significantly changed for a considerable time. https://github.com/nortikin/sverchok/blame/master/nodes/viz/viewer_draw_mk4.py

i'm not saying this won't / can't be fixed,  it's just unusual that you should be encountering issues lately.

**Comment by zeffii** [comment]
>  Viewer Draw would gracefully handle a connected but empty list of faces or a connected but empty list of edges. If there are only edges and vertices, it would draw a wireframe. If there are only vertices, it would draw only vertices.

i'm surprised it did anything gracefully :)

**Comment by wassimj** [comment]
Here is a picture of the new behaviour. I have other colleagues who reported the same behaviour to me.  You see that for a "Wire" Rectangle, I would not have faces. It used to draw the rectangle regardless if the faces socket was connected or not. You see at the bottom set of nodes, once I disconnect the faces socket, it works.
<img width="1401" alt="wireDrawing" src="https://user-images.githubusercontent.com/6302909/180803350-28c022cd-2cc0-4efd-a67f-f45726b197db.png">

**Comment by wassimj** [comment]
oh no! I found the issue. If empty, faces need to be a wrapped list within a list
<img width="1400" alt="wireDrawing02" src="https://user-images.githubusercontent.com/6302909/180804250-d000ac6f-ec4a-4b20-a50c-123241fd2093.png">
!

**Comment by wassimj** [comment]
Thank you. I change Topologic’s code to check for empty lists and wrap them. Issue solved!

**Comment by zeffii** [comment]
I think you may encounter Matrix and Object sockets passing empty lists on occasion.
