### ISSUE TITLE
Sverchok deserves an icon

### ISSUE THREAD

**Issue by DuncanLithgow** [nortikin/sverchok#4593]
I think Sverchok deserves an icon - and there must be lots of good possibilities.

How about Sverchok (and us in OSArch will help) push a request out to the community for suggestions.

Just a suggestion.

**Comment by portnov** [comment]
There was some activity in this direction. It seems the one which is currently displayed in the readme, have won the competition.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/1834 on logos

**Comment by DuncanLithgow** [comment]
Okay, so I've used that icon (which is broken at that link) for OSArch https://wiki.osarch.org/index.php?title=Sverchok

It would be great if that logo was actually visible somewhere. In a perfect world it shouldn't be something I need to ask about, it should be obvious.
