### ISSUE TITLE
Option "Post" does not reflect parameter updates

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4598]
Inspired from the OpenSubdiv topic #4575 I played a bit with what we have currently.

We actually can use the the Subdivision Modifier from Blender itself (along with all other modifiers I guess).
Which brings back the old topic #4175 for the "Post" option in "Get Objects Data" node.

So in order to use the Subdivision modifier for a node generated mesh we can turn it into a Blender mesh first then apply the modifier and get back to Sverchok. Also for controlling the iterations amount (or any other parameter) within the nodes I used the awesome "Set Property MK2" node.

![Subd_and_Post](https://user-images.githubusercontent.com/66558924/181229361-28dc89e9-0c28-4759-8063-0e4cb859b6bf.jpg)

Doing that I noticed that Post does not reflect parameter changes interactively but needs manual refresh.

There is another problem mentioned a long ago for it not updating when the input mesh is in edit mode which breaks some useful modelling approaches.

Is it possible to address those problems within the new update system?

Thanks

**Comment by Durman** [comment]
I think it's Blender limitation. Looks like Get object data node can't see freshly changed geometry and uses previous one instead.

By the way there is Copy Modifiers node.

![copy modifiers](https://user-images.githubusercontent.com/28003269/181238542-d22a83b8-b9c2-44bf-a143-21e8d4faf3ed.gif)

![image](https://user-images.githubusercontent.com/28003269/181238714-7375b4e6-1c4f-45b2-96ee-bbe9b6397286.png)

**Comment by zeffii** [comment]
maybe GetObjectsData should have the animatable state, but switched off by default.

**Comment by zeffii** [comment]
alternatively i could add a remote-update parameter to the `Set Property MK2`, where you can pick a node in the current tree to start an update cascade.  I'm not sure how great that would work with the update system..

**Comment by Durman** [comment]
I've got it. I was wrong about the Blender limitation. It is the same problem as this #4609. If the Get Object Data node uses fresh depsgraph everything works as expected.

![subdiv](https://user-images.githubusercontent.com/28003269/182836627-92e0540d-1c80-4049-8f0d-24f61e7eeecf.gif)

![image](https://user-images.githubusercontent.com/28003269/182836831-2d3a9f40-e2ef-4d57-ae73-56513d945009.png)

**Comment by rendetto** [comment]
Thanks a lot @Durman! The problem seem solved.
