### ISSUE TITLE
Is there a way to update the colours of custom nodes?

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4602]
## Problem statement

If I add a new background colour to a custom node, is there a way to update an existing node in a sverchok graph? If I drag and drop a new instance of the node, it has the new colours, but existing nodes do not update their look. Any way to force an update? Thanks!
```
def sv_init(self, context):
     self.width = 150
     self.color = (0.05, 0.05, 0.07)
     self.use_custom_color = True
```

**Comment by zeffii** [comment]
`sv_init` is only called once; when a node is added to a nodetree. `sv_init` is, as you might have realized, not called again if you load a `.blend`.  You could add `self.use_custom_color` at the top of `process` , as a way to hot force this new state
```python
...
    def process(self):
        ...
        if not self.use_custom_color:
            self.use_custom_color = True
        ...
```
you could also write a utility function in your baseclass
```
def set_custom_color_usage_to_true(self):
    if not self.use_custom_color:
        self.use_custom_color = True
```
you might end up with
...
    def process(self):
        ...
        self.set_custom_color_usage_to_true()
        ...
```

**Comment by wassimj** [comment]
Thank you!
