### ISSUE TITLE
Unavailable `bpy.context.screen` while rendering animation prevents updates

### ISSUE THREAD

**Issue by gabrielmontagne** [nortikin/sverchok#4605]
## Problem statement

Check for null `bpy.context.screen` property `is_animation_playing` in `handlers.py` `sv_update_handler` causes nodes to not update when rendering an animation. 

```
Traceback (most recent call last):
  File "/home/gabriel/.config/blender/3.2/scripts/addons/sverchok/core/handlers.py", line 101, in sv_update_handler
    is_playing = bpy.context.screen.is_animation_playing
AttributeError: 'NoneType' object has no attribute 'is_animation_playing'
```

A workaround I'm using ATM is to assume (most likely incorrectly) that if `bpy.context.screen` is `None`, `is_playing` would be `True`.

**System Information**
Operating system: Linux-5.15.57-2-MANJARO-x86_64-with-glibc2.35 64 Bits
Graphics card: Mesa Intel(R) Xe Graphics (TGL GT2) Intel 4.6 (Core Profile) Mesa 22.1.4

**Blender Version**
]3.2.2 Release Candidate, branch: master, commit date: 2022-07-15 13:02, hash: `rB746e2f02c4ce`

## Steps to reproduce

It most likely happens with any Sverchok animation, but I'm uploading my `.blend` for reference.
https://drive.google.com/file/d/1SMOas4Kg3q6SK8W9P6KIFaXxfYMk8zwJ/view?usp=sharing 

1. Open the attached blend file. 
2. Go to Render menu -> Render Animation

## Expected result

Grease Pencil object and generated geometry should match on every frame.

## Actual result

Generated geometry is not update between frames, so gets out of sync with reference GP object.
The above error is displayed on the console.

## Sverchok version

Running off master, "version": (1, 1, 0),

**Comment by Durman** [comment]
Thanks for the report, should work now.
