### ISSUE TITLE
Evolver Node Error on Iterations > 1

### ISSUE THREAD

**Issue by wassimj** [nortikin/sverchok#4613]
## Problem statement
The Evolver node gives an error if the number of iterations is set greater than 1
```
Error: Python: Traceback (most recent call last):
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\sverchok-master\utils\sv_operator_mixins.py", line 67, in execute
    response = self.sv_execute(context, node)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 556, in sv_execute
    population.evolve()
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 524, in evolve
    self.population_g = self.get_new_population(actual_population_fitenss, mode)
  File "C:\Users\wassimj\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\sverchok-master\nodes\logic\evolver.py", line 458, in get_new_population
    parents_id = np.random.choice(len(self.population_g), [len(self.population_g)-1, 2], replace=True, p=weights)
  File "mtrand.pyx", line 935, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```

## Steps to reproduce

1. Unzip the attached evolver-bug.zip file
2. Open the extracted evolver-bug.blend Blender File
3. Set number of iterations to 2 in the Evolver node
4. Press RUN in the Evolver node

## Expected result
Evolver runs normally and finds the numbers that produce the smallest multiple

## Actual result

An error message is displayed

## Sverchok version

1.10

<img width="1447" alt="evolver01" src="https://user-images.githubusercontent.com/6302909/184471389-f2aa7da3-5e00-4746-9a44-d2af446ae0c7.png">
<img width="1447" alt="evolver02" src="https://user-images.githubusercontent.com/6302909/184471390-56ab7c48-cbba-492d-87bf-5ed2aea93240.png">
[evolver-bug.zip](https://github.com/nortikin/sverchok/files/9330925/evolver-bug.zip)

**Comment by zeffii** [comment]
seems to work in master.
![image](https://user-images.githubusercontent.com/619340/184493562-e1f16e2b-e860-4252-808e-52e70e68dae9.png)

**Comment by wassimj** [comment]
Thank you for checking it. Can you please point me to the exact download link for master? It may be that I am downloading an older version all the time?

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/archive/refs/heads/master.zip  this is the most up to date, but may contain ( at any time ) new and amazing bugs.

**Comment by zeffii** [comment]
there seems to be a small line count discrepancy in your evolver.py  because the error message says 
`        parents_id = np.random.choice(len(self.population_g), [len(self.population_g)-1, 2], replace=True, p=weights)
` is on line 458,  but in master that's on line 460.

**Comment by zeffii** [comment]
and another thing, i see in the current bug .blend that all those weights are identical ( `p=weights` ) and if that's the case perhaps the P parameter should not even be passed along.

**Comment by wassimj** [comment]
Thank you. I upgraded sverchok from the preference panel and now it works. Please feel free to close. Thanks!

**Comment by wassimj** [comment]
> https://github.com/nortikin/sverchok/archive/refs/heads/master.zip this is the most up to date, but may contain ( at any time ) new and amazing bugs.

Thank you. some of Topologic's best friends are new and amazing bugs! :)

**Comment by zeffii** [comment]
ok !

**Comment by zeffii** [comment]
why your version didn't work may remain a mystery.

**Comment by wassimj** [comment]
New bug. If you set a goal, it complains that it is comparing a float to a list line 483

**Comment by zeffii** [comment]
bug .blend ?

**Comment by zeffii** [comment]
can't confirm.
