### ISSUE TITLE
F3 node.ungroup_group_tree operator poll func error

### ISSUE THREAD

**Issue by 1234EMMM** [nortikin/sverchok#4614]
## Problem statement

Is the problem installation related? then `visit this page first <https://github.com/nortikin/sverchok#troubleshooting-installation-errors>`_.  

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce

1. 
2. 
3. 

## Expected result

poll error

## Actual result

When using F3, there will be an error prompt
![image](https://user-images.githubusercontent.com/49475772/185042641-3f52007e-38f0-4137-9594-0a5aa3735d57.png)

## Sverchok version
1.1
![image](https://user-images.githubusercontent.com/49475772/185042474-8ae29106-7ecf-4352-8c88-33262c338ed0.png)

**Comment by zeffii** [comment]
the `F3` should probably not show this operator, the operator requires `bpy.context.node` to be present, which will be present if you trigger the operator using the button the nodegroup UI.
