### ISSUE TITLE
Nodes Torus with Mesh Viewer generate wrong torus form when a param "spin twist" is non zero

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4615]
## Problem statement
Nodes Torus with Mesh Viewer generate wrong torus form when a param "spin twist" is non zero.

## Steps to reproduce

1. Create torus
2. Set spin twist non zero (1,2,3 and other)
3. Connect to Mesh viewer and "Viewer Draw". Move mesh aside.
4. Meshes are different

## Expected result

I expect seamless torus mesh, like with node "Viewer draw"

## Actual result
![2022-08-19_113504](https://user-images.githubusercontent.com/14288520/185580402-4fb65bba-3936-41e7-bbc8-403842cfe691.png)

## Sverchok version
![2022-08-19_113611](https://user-images.githubusercontent.com/14288520/185579465-347e994d-9c1f-407a-a3a6-a38616f5f106.png)

This is especially important for installation-related issues.
Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.
- sverchok-master with update.

**Comment by zeffii** [comment]
That's down to an optimization, which tries to do less topology updating if the vertex count doesn't change in between updates. The usecase if if you are modifying only the locations of vertices of a big mesh, but not changing the face/edge indices  

This can be switched off in the node's N Panel. 
![image](https://user-images.githubusercontent.com/619340/185586330-b61654df-e664-496e-aff6-5e26f192b832.png)

**Comment by satabol** [comment]
> That's down to an optimization, which tries to do less topology updating if the vertex count doesn't change in between updates. The usecase is if you are modifying only the locations of vertices of a big mesh, but not changing the face/edge indices. It's on by default because usually the input is pretty dynamic with respect to verts/edges/faces.
> 
> This can be switched off in the node's N Panel. ![image](https://user-images.githubusercontent.com/619340/185586330-b61654df-e664-496e-aff6-5e26f192b832.png)

Cool! Thank you. It is work. I knew about this property but I did not think about one in this context.
![2022-08-19_124023](https://user-images.githubusercontent.com/14288520/185591707-b45f3699-5454-49af-9e4d-34cc010e8378.png)
Whish I could do it myself. )))
