### ISSUE TITLE
Node groups

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#462]
![editgroup](https://cloud.githubusercontent.com/assets/6241382/4964688/dcec9a22-6768-11e4-8e0d-f64cf7da3fe0.png)
A node group can be seen as code block. It is very beta right now but works.

Plans: recursion, iteration, do while.

For recursion the key issue is to change update system to use switch node as a if statement for flow control.
 
Iteration and do while is pretty straightforward to do inside of the current system.

Other issues to resolve:
- [ ] I/O of node groups inside a layout
- [ ] Letting live in the same layout where they are used
- [x] Editing socket types
- [ ] Recursive node groups

**Comment by portnov** [comment]
Is it possible to reuse groups in one setup? For example, if I create a group which duplicates input mesh N times, and then I want to apply this group twice, for two different inputs...

**Comment by ly29** [comment]
Yes. 

This part needs to be redone however partly, which is why it is in beta.

**Comment by snovvfall** [comment]
Is it a good idea to use a separate layout as a group and put there some sort of Wifi nodes for input and output for another layouts?

So it will be like:
1) user makes some nodes
2) adds "Wifi in" which leads to another layout
3) in that layout "Wifi out" connects to some other nodes
4) "Wifi in" as an output pushes data back to first layout
5) "Wifi out" receives data and sends it to other nodes the user nees
6) ...
7) profit

So it all comes to making Wifi node that can transfer data between layouts. Or is it even harder to code and make it work than the thing you already did? I use groups a lot ever since you implemented them, would be glad if they improve.

**Comment by ly29** [comment]
It is a very good idea in general. My thinking about sverchok has become clearear lately, since I developed groups I have reached an deeper understanding of how I think it should work.

**Comment by pierdr** [comment]
Hi, I think it's not so straight forward to understand how to manage group inputs. 
Any suggestions?
![screen shot 2015-08-25 at 6 31 03 pm](https://cloud.githubusercontent.com/assets/2287727/9472826/d0bbe93c-4b57-11e5-8e29-4f28c0111503.png)

**Comment by nortikin** [comment]
just create group connected with outer nodes allready. It is beta version, and works as it works. sorry

**Comment by pierdr** [comment]
@nortikin Thanks! It works. Sverchok is super! Keep going!

**Comment by nortikin** [comment]
follow vk.com group of #sverchok there is more stuff.

**Comment by Durman** [comment]
Group node has problem with import/export. 
1. Before import 2. After import 3. After rename

![2017-04-25_16-16-46](https://cloud.githubusercontent.com/assets/28003269/25384983/6c668efe-29d3-11e7-8006-9c9c3569542e.png) ![2017-04-25_16-17-34](https://cloud.githubusercontent.com/assets/28003269/25384990/75d235ce-29d3-11e7-8309-ddff05288427.png) ![2017-04-25_16-19-13](https://cloud.githubusercontent.com/assets/28003269/25385002/7feeceb4-29d3-11e7-858e-ef1ecc2e3689.png)

**Comment by nortikin** [comment]
i see it became bigger ))
https://github.com/nortikin/sverchok/issues/1485
here was discussed and 
https://github.com/nortikin/sverchok/issues/1251
and
https://github.com/nortikin/sverchok/issues/1230

**Comment by ly29** [comment]
I thought I had solved that. Make new issue and tag me.
