### ISSUE TITLE
Merge Input Switcher and List Mask (In) nodes to form a new node

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4629]
The idea is to have a node that can have any number of input lists, grouped if needed, like the Input Switcher, and also the possibility to mask each element independently, to choose the level at which to apply the mask, along with a mechanism to match lengths (once #4607 is merged), like the List Mask (In) node.

**Comment by Durman** [comment]
The proposal is close to the Switch node functionality I guess.
![image](https://user-images.githubusercontent.com/28003269/187123845-8042e5dc-51b4-4fe1-ab23-544914d90213.png)

**Comment by ArpegorPSGH** [comment]
Indeed, it is quite close, and perfectly fit my needs, it just lacks the list length matching and list masking level options, but I should manage without.
