### ISSUE TITLE
A Separate Param with a Sphere and Torus node do not work as expected. Cylinder is good.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4650]
Hello.
There is three Generator-> with Separate param: Cylinder, Sphere, Torus. This param has good result only on Cylinder. Sphere and Torus has a half result - only on Vertices. Their Edges and Polygons do not changed on any state of Separate:

https://user-images.githubusercontent.com/14288520/189489786-674814a8-e555-4009-8be9-18daae696f79.mp4

**Comment by satabol** [comment]
Sorry. I think this is my inattention:
![image](https://user-images.githubusercontent.com/14288520/189496368-16b2a4c9-fd57-4e20-9bfb-a38f0565aca7.png)

But I think that it is strange do not separate sphere and torus unlike as cylinder. What do you think?

**Comment by Durman** [comment]
As to me this "separate" functionality looks strange. It seems I even never used it in my layouts. It took me for a while to understand what is going on with the option on.

**Comment by satabol** [comment]
I agree but I think that strange things has to be work identically.

**Comment by satabol** [comment]
You are right.

P.S.
So, this is not an error.
