### ISSUE TITLE
3D views node show error

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4665]
## Problem statement

Hello.

Viz->3D views node show error:
![image](https://user-images.githubusercontent.com/14288520/190644367-56ea3b69-731c-4585-9147-26fcd0a6c6a8.png)

All functions and buttons work good. Node has no inputs and outputs.

Windows 11, Blender 3.2.2, Sverchok master version. (1.1-beta),

**Comment by Durman** [comment]
Easy fix is to add process method to the node )). I don't think it worth adding extra condition into the update system just because of one node.

**Comment by satabol** [comment]
@Durman If it is ok can I close this issue ?

**Comment by Durman** [comment]
Sure
