### ISSUE TITLE
Generator->Generators Extended->Bricks (Faces Stich and Center do not working)

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4670]
Hello.

I try this generator and got unexpected result:

![image](https://user-images.githubusercontent.com/14288520/190888559-5931bfe2-0853-43be-b5df-0af572191bd6.png)

Can you check in? (Windows 11, Blender 3.2.2, Sverchok 1.1.0-beta/master)

Docs ref: http://nortikin.github.io/sverchok/docs/nodes/generator/bricks.html

**Comment by portnov** [comment]
Thanks for the information!

it've been in this state since 2017 :/ Although temporary solution was very simple: just do not connect the Edges socket.

**Comment by satabol** [comment]
@portnov Thank you! I use V-shortcut and did not pay attention for that moment. It is work now with edge connection:

![image](https://user-images.githubusercontent.com/14288520/190897157-e1e6a991-03b5-4eb5-a29c-7685cbb8584e.png)

![image](https://user-images.githubusercontent.com/14288520/190897162-d4441984-1eea-48f5-82ba-2212149437da.png)
