### ISSUE TITLE
Conflicting SVerchok nodes appearing inside Geometry Nodes

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4683]
I am using Blender 3.4 alpha, maybe just a glitch, but SV nodes seems to appear inside Geometry Nodes. I don't mind it if they were actually functional and can process the data, but at the moment SV nodes inside Geometry Nodes does not do anything. 

It is becoming really hard to pick a node because SV Nodes appearing in search. I need to turn off SV addon while working in Geometry Nodes.

**Comment by Durman** [comment]
Probably it's Sverchok problem now - https://developer.blender.org/T101259
