### ISSUE TITLE
Get Property and Set Property nodes not working

### ISSUE THREAD

**Issue by Marcus-Richmond** [nortikin/sverchok#4684]
## Problem statement

The Get Property and Set Property nodes are not working for me, but are returning the following error:

![image](https://user-images.githubusercontent.com/59568811/192426592-7908fc5d-0556-4c87-bec9-1cae91b2312c.png)

I haven't used these nodes in a while, thought I may be using incorrectly, but I tried to reproduce what is shown on the [documentation ](https://nortikin.github.io/sverchok/docs/nodes/object_nodes/getsetprop.html)and still got the error.

## Sverchok version

Sverchok version 1.1.0
Blender version 3.1.2

Thanks,

**Comment by zeffii** [comment]
![image](https://user-images.githubusercontent.com/619340/192508282-13143760-2779-423a-8325-89b0d514da32.png)

objects that are put into nested collections may not be accessed using 
```python
bpy.data.objects['Cylinder']
```
but maybe
```python
 bpy.data.collections['studio'].children['studio 1'].objects['Cylinder']
```
not sure if it's a bug.. i can't confirm yet.

![image](https://user-images.githubusercontent.com/619340/192509506-dfdc69c9-0444-4e58-b376-d99d94126de3.png)

**Comment by zeffii** [comment]
this is not what i would use this node for. There is `Get Objects Data` and `Objects ID Set MK2`m which is essentially a get and set node.

![image](https://user-images.githubusercontent.com/619340/192510295-4519ad94-47ea-4dc7-9993-ca8714efd833.png)

**Comment by Marcus-Richmond** [comment]
@zeffii the `Get Objects Data` and `Objects ID Set MK2` work like a charm, thanks for pointing those out. 

I cannot make the Get/Set Property nodes working even when accounting for the collections as you describe above. Although, I'm not really concerned anymore since, like you said, the `Objects ID Set MK2` has the same functionality.

**Comment by Durman** [comment]
I have this error
```text
Traceback (most recent call last):
  File "\sverchok\nodes\object_nodes\getsetprop.py", line 173, in verify_prop
    obj = self.obj
  File "\sverchok\nodes\object_nodes\getsetprop.py", line 200, in obj
    return get_object(path)
  File "\sverchok\nodes\object_nodes\getsetprop.py", line 60, in get_object
    curr_object = globals()[path[0][1]]
TypeError: 'NoneType' object is not subscriptable
2022-09-28 08:43:19,472 [ERROR] sverchok.nodes.object_nodes.getsetprop:208 : bpy_prop_collection[index]: index 0 out of range, size 0
Traceback (most recent call last):
  File "\sverchok\core\update_system.py", line 463, in main_update
    node.process()
  File "\sverchok\nodes\object_nodes\getsetprop.py", line 208, in process
    self.outputs[0].sv_set(wrap_output_data(self.obj))
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
2022-09-28 08:43:19,477 [DEBUG] sverchok.core.tasks 122: Global update - 4ms
```

**Comment by Durman** [comment]
I guess this is the problem

> Deprecated since version 3.8: Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.

https://github.com/nortikin/sverchok/blob/e29e44abf4280c78a2425a80b9341db258b4f83d/nodes/object_nodes/getsetprop.py#L32-L52

So such expression as `collection[name]` is instance of ast.Subscript but `name` is instanse of str class and not ast.Str. So the function returns None and this raises an error in next functions.

@zeffii I don't know how it happened that it works on your machine.
