### ISSUE TITLE
baking animation

### ISSUE THREAD

**Issue by flowb** [nortikin/sverchok#469]
Hallo,

What is the best way, currently, for me to bake animations that I create by animating input parameters to sverchock. Would I need to do something with shape keys? I did a little bit of research but it seemed wisest just to ask here.

Thanks!

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/shape_key_bake.py
https://github.com/nortikin/sverchok/issues/2390
