### ISSUE TITLE
Errors within group nodes not appearing

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4692]
When an error occurs within a group node, the exact node raising the error is not highlighted in red with the error message displayed next to it, like it was until a few weeks ago. This makes localizing the error more tedious, so could it be solved? Or maybe that's just a problem with my Sverchok installation.

**Comment by Durman** [comment]
I can't reproduce.

![image](https://user-images.githubusercontent.com/28003269/193732660-580dca9d-3eac-46d8-9e9f-63fc6b2c170e.png)

**Comment by ArpegorPSGH** [comment]
Ok, so it probably comes from my installation. I'll try to reinstall it.

**Comment by ArpegorPSGH** [comment]
Error messages weren't showing because live update of the tree was off.
