### ISSUE TITLE
Node Group StopIteration Exception

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4693]
I have a StopIteration Exception raised by a node group, but I have absolutely no idea what might cause it, as within the node everything works fine (I checked with stethoscope that I get the intended output, which is plugged into Group Output node). However, outside the node group, I get no output data, as it crashes and raises an error. Any idea on how to solve this?

**Comment by Durman** [comment]
Could you share a file with minimal example of the problem?

**Comment by ArpegorPSGH** [comment]
I rebuilt the node group from scratch and it solved the problem.
