### ISSUE TITLE
Object_Nodes

### ISSUE THREAD

**Issue by Kosvor** [nortikin/sverchok#471]
Its like ObjRemote node on steroids (however these are two instead of one node):

![parent_objects](https://cloud.githubusercontent.com/assets/7894950/4999226/8b1416cc-69f1-11e4-9e58-600ca5280775.png)
![111111111](https://cloud.githubusercontent.com/assets/7894950/5028126/5cb7fa20-6b48-11e4-8f49-a8950271741c.png)
![11221111](https://cloud.githubusercontent.com/assets/7894950/5028138/860bd70c-6b48-11e4-97cc-44662e6630b4.png)

@ly29 stated that there must be also specialised object socket instead of vector. Agreed.

https://github.com/nortikin/sverchok/tree/obj_sockets

**Comment by Kosvor** [comment]
I want the code of the setdataobject node to look like this:
```
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####


import bpy
import mathutils
from mathutils import Vector
from bpy.props import StringProperty, EnumProperty
from sverchok.node_tree import SverchCustomTreeNode, VerticesSocket
from sverchok.data_structure import (updateNode, match_long_cycle)


class SvSetDataObjectNode(bpy.types.Node, SverchCustomTreeNode):
    ''' Set Object Props '''
    bl_idname = 'SvSetDataObjectNode'
    bl_label = 'set_dataobject'
    bl_icon = 'OUTLINER_OB_EMPTY'

    modes = [
        ("location",   "Location",   "", 1),
        ("scale",   "Scale",   "", 2),
        ("rotation_euler",   "Rotation_Euler",   "", 3),
        ("delta_location",   "Delta_Location",   "", 4),
        ("delta_scale",   "Delta_Scale",   "", 5),
        ("delta_rotation_euler",   "Delta_Rotation_Euler",   "", 6),
        ("parent",   "Parent",   "", 7),
        ("layers",   "Layers",   "", 8),
        ("select",   "Selection",   "", 9),
        ("custom",   "Custom",   "", 10)
    ]

    formula = StringProperty(name='formula', description='',
                             default='select', update=updateNode)
    Modes = EnumProperty(name="property modes", description="Objects property",
                         default="location", items=modes, update=updateNode)

    def draw_buttons(self, context, layout):
        if self.Modes == 'custom':
            layout.prop(self,  "formula", text="")
        row = layout.row(align=True)
        layout.prop(self, "Modes", "Objects property")

    def sv_init(self, context):
        self.inputs.new('SvObjectSocket', 'Objects')
        self.inputs.new('VerticesSocket', 'values')

    def process(self):
        objs = self.inputs['Objects'].sv_get()
        valsoc = self.inputs['values'].sv_get()
        lob = len(objs)

        if self.Modes == 'parent':
            Val = valsoc
            if lob > len(Val):
                temp = match_long_cycle([objs, Val])
                objs, Val = temp[0], temp[1]
        elif self.Modes == 'layers':
            Val = [[True if i > 0 else False for i in valsoc[0]]]
            if lob > len(Val):
                temp = match_long_cycle([objs, Val])
                objs, Val = temp[0], temp[1]
        else:
            Val = valsoc[0]
            if isinstance(Val, (tuple)):
                Val = [Vector(i) for i in Val]
            if lob > len(Val):
                temp = match_long_cycle([objs, Val])
                objs, Val = temp[0], temp[1]

        if self.Modes != 'custom':
            Prop = self.Modes
        else:
            Prop = self.formula

        g = 0
        while g != lob:
            if objs[g] != None:
                exec("objs[g]."+Prop+"= Val[g]")
            g = g+1


def register():
    bpy.utils.register_class(SvSetDataObjectNode)


def unregister():
    bpy.utils.unregister_class(SvSetDataObjectNode)
```

**Comment by nortikin** [comment]
change input type socket if mode changed.

**Comment by Kosvor** [comment]
UndefinedType socket added. Old code commented out...
![custom type socket](https://cloud.githubusercontent.com/assets/7894950/5606109/03e8cc2a-942f-11e4-8451-d6ba1f5783ff.png)

**Comment by nortikin** [comment]
not red, please, grey or wite, but nor red. it has to be preserved for error or something. @Kosvor

**Comment by Kosvor** [comment]
Ok.

**Comment by nortikin** [comment]
or better use data strings socket as default.

**Comment by Kosvor** [comment]
Half of the site buthons doesnt work anymore. Demn uou proxyserver!!!

**Comment by nortikin** [comment]
@Kosvor what site?

**Comment by Kosvor** [comment]
http://free-proxyserver.com/
но на самом деле этот работает лучше остальных. Они вообще не пашут.

**Comment by nortikin** [comment]
@Kosvor и куда хочешь заходить через прокси?

**Comment by Kosvor** [comment]
Сюда через прокси захожу уже месяц не меньше. Ещё пару дней назад удавалось создавать новые файлы нажимая на синий крестик, теперь он не работает. Пока могу нажимать на зелёные кнопки и редактировать уже созданные файлы, но это неудобно.

**Comment by nortikin** [comment]
ты в вконтакте есть?
@Kosvor

**Comment by Kosvor** [comment]
нет, только на блендерартист и здесь

**Comment by nortikin** [comment]
тогда почту, будем писать там

**Comment by Kosvor** [comment]
Please test it again. Many nodes changed their concept. Some may need new names.

**Comment by Kosvor** [comment]
Может кто нибудь создать по три пустых файла в "basic_data" и в "basic_data" в мастере?
Никита?

**Comment by Kosvor** [comment]
То есть там и в "analyzer"

**Comment by Kosvor** [comment]
I need someone to create emptie files in master so i can manualy port atleast some of the nodes, please?

**Comment by nortikin** [comment]
зачем? то есть ты не можешь этого сделать? Именно в мастере надо? Создай форк, потом его совместим.
и не понятно что за файлы и как их называть и зачем они нужны.

**Comment by Kosvor** [comment]
ничего не могу создавать, только обновлять уже существующие- долго обьяснять почему.
пустые файлы с любым названием. Ну или форк, но опять же с пустыми файлами.

**Comment by Kosvor** [comment]
уже не надо. Мне нужно было просто обновить браузер

**Comment by nortikin** [comment]
у меня другая проблема, я не умею работать с гитом вообще, GITeye в частности, я сделал изменения, но не могу запустить, они есть на винчестере, но нет в коммите, я делал фетч (или стак, не помню), но не знаю что такое фетч, оно куда-то пропало. Изменения не пушатся на сервер.
