### ISSUE TITLE
Incorrect result of surface trimming function ？

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4713]
![image](https://user-images.githubusercontent.com/74725748/196887652-79775b8a-8d45-45a1-a9e3-932fa464b0d9.png)
Obviously, the result is deformed. It looks like the UV is stretched

**Comment by rendetto** [comment]
Hello vkter.

The result is correct according to what this node does.

![help](https://user-images.githubusercontent.com/66558924/197051315-c4f86247-8e7f-4485-9da5-13565b1c7d65.JPG)


Giving the fact that the input trim curve (the circle) should be in UV space of the patch, and the patch is not a perfect square you'll always get stretched/deformed result. Just make square surface and you'll get a perfect circle hole.

![SquareSurface](https://user-images.githubusercontent.com/66558924/197049788-28b58052-7853-4185-83c6-57b05825b849.JPG)

**Comment by vkter** [comment]
The clipping function has the expected result only for square. Is there any way to make any surface effective？

**Comment by rendetto** [comment]
You can use "Face from Surface" node. It does what your are looking for.
