### ISSUE TITLE
Documentation sort order has errors for Headers.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4714]
In all parts of Headers exisis some pages with wrong order:

http://nortikin.github.io/sverchok/docs/nodes/transforms/transforms_index.html

![image](https://user-images.githubusercontent.com/14288520/197365143-f7f27d42-9e81-44de-a926-1334917d0b7f.png)

![image](https://user-images.githubusercontent.com/14288520/197365169-ff30c8cd-bb65-44d3-95af-e13312c67b9b.png)

**Comment by Durman** [comment]
The order is determent by file names as far as I understand.

**Comment by satabol** [comment]
@Durman You are right. Is it possible to fix it and set sort order by name of menu items?

**Comment by Durman** [comment]
I did not see such feature in the Sphinx documentation but you can try your luck.

**Comment by satabol** [comment]
@Durman Is make.bat is a start point? (Is that command do compilation html on the github in actions or something else? Will docs/html changed If docs/make.bat is changed?)

**Comment by Durman** [comment]
It seems no. I don't think the bat file is used anywhere.
https://github.com/nortikin/sverchok/blob/a74063a17608f1e2b3b82f3cc2e270a793776375/.github/workflows/docs_builder.yml#L32

**Comment by satabol** [comment]
Thank you. I close for a while.
