### ISSUE TITLE
Documentation wasn't updated after merging pool request.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4716]
I merged pull request https://github.com/nortikin/sverchok/pull/4715 (update documentation). Documentation wasn't updated. Log messages looks good.
Master has all changes I pull.

**Comment by portnov** [comment]
Unfortunately our current documentation build system is not ideal. Sometimes two jobs, build of user documentation and build of API documentation, try to push changes to gh-pages branch simultaneously, so one of them fails.
For now I just re-run the failed job.

**Comment by satabol** [comment]
@portnov Thank you. It is updated! How did you do that? (I did not find any failed jobs and can I did that?)

**Comment by portnov** [comment]
@satabol  I'm not sure if you have access, try it: Actions tab -> pages build and deployment -> Re-run jobs
https://github.com/nortikin/sverchok/actions/runs/3307505000

**Comment by satabol** [comment]
@portnov Yes I can. I think I did run another action at first time. I will see that place next time.
