### ISSUE TITLE
quick search nodes unavailable

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4725]
Alt+spacebar search does not give access to nodes, only to operations.

**Comment by Durman** [comment]
What do you mean?

![image](https://user-images.githubusercontent.com/28003269/198352064-4db0a358-68fc-4dbf-921d-ce2ea2fa08c0.png)

Any errors in console?

**Comment by ArpegorPSGH** [comment]
I'll try again, but I did not have the same as you, whatever I typed, I had only propositions starting with '>', which mean operations to perform on nodes, I believe. Maybe restarting Blender will solve the problem.
