### ISSUE TITLE
Inset special ignore list of ignored faces in Fan mode if distance is not zero.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4729]
CAD->Inset Special. Docs: http://nortikin.github.io/sverchok/docs/nodes/CAD/inset_special_mk2.html

If mode is FAN and Distance is not zero and Inset is 0 then I got unexpected result:

![image](https://user-images.githubusercontent.com/14288520/198611667-ae29f1a0-a1cb-453e-a435-e57e5b982688.png)

**Comment by Durman** [comment]
Can confirm, also there is next error.
[untitled.zip](https://github.com/nortikin/sverchok/files/9898075/untitled.zip)

![image](https://user-images.githubusercontent.com/28003269/198931398-1594f259-bfa0-49f7-891a-f702957d710b.png)

**Comment by satabol** [comment]
Hi @Durman! Can you check Pull Request #4997 ?
