### ISSUE TITLE
NURBS Sweep and Loft issues using FreeCAD curves

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4735]
In one of my setups I'm using closed periodic curves for constructing a torus-like object:

![sweep_toruslike](https://user-images.githubusercontent.com/66558924/199595497-a61f50cb-7c14-4a04-a019-2147436ba6c8.JPG)

With the merge of https://github.com/nortikin/sverchok/commit/66a4cfbbf8fecd8537b1fc2013d8ad5b573a4763 the NURBS Sweep node started having problems with FreeCAD curves:
`[ERROR] sverchok.utils.nurbs_common:64 : type object 'SvFreeCadNurbsCurve' has no attribute 'interpolate'`

I'm uploading the test file for examination 
[Sweep_ClosedPeriodicCurves_Issue.zip](https://github.com/nortikin/sverchok/files/9924004/Sweep_ClosedPeriodicCurves_Issue.zip)

I got similar issue using the Loft node on another setup.

**Comment by portnov** [comment]
Huh, interesting bug. It tries to use FreeCAD version of nurbs interpolation and discovers that there is no such in Sverchok.
In fact, in FreeCAD API there is `BSplineCurve.interpolate` method; but it is somewhat limited: it does not allow you to specify degree of the curve or metric (although it allows to specify tangents).
For now, I choose to fall back to built-in Sverchok implementation - this is what was done earlier.

**Comment by portnov** [comment]
There is simply no API in Geomdl library to produce an isocurve (curve on the surface with fixed U or V parameter). For non-rational surfaces it is easy enough to calculate by combining other calls from Geomdl library, so I supported it. But for rational surfaces it's not so easy, so for now it is not supported.

**Comment by rendetto** [comment]
Thanks! 

Another question just popped. While tweaking the V Sections of the node I got another error:
`[ERROR] sverchok.utils.curve.nurbs:860 : Unsupported metric`

![Sweep_GEOMDL_UnsupportedMetric](https://user-images.githubusercontent.com/66558924/199743459-aee2cb84-95bb-49a6-8ba3-135465973eec.JPG)

It's when I use V Sections number exactly as the number of Profiles. 

What "Unsupported metric" means, since it is present for all metrics I tried?

**Comment by portnov** [comment]
Probably a bug.Can you attach the file?

**Comment by rendetto** [comment]
Sure. Here it is:
[Sweep_ClosedPeriodicCurves_UnsupportedMetric.zip](https://github.com/nortikin/sverchok/files/9930501/Sweep_ClosedPeriodicCurves_UnsupportedMetric.zip)

Just found another bug. 
When I use Native Implementation to generate the Path and the Profiles and use the above setup with 5 Profiles and 5 V Sections the Sweep node does not throw an error but does not generate a proper surface either. It appears that there are no Control Points in the result.

![Sweep_GEOMDL_NoErrorNoSurface](https://user-images.githubusercontent.com/66558924/199772377-a25ebb92-c4e7-419a-bec1-b0ddea1a9b6a.JPG)

I'm uploading the setup for examination also:

[Sweep_ClosedPeriodicCurves_NoErrorNoSurface.zip](https://github.com/nortikin/sverchok/files/9930898/Sweep_ClosedPeriodicCurves_NoErrorNoSurface.zip)

**Comment by portnov** [comment]
About NaNs instead of control points: it appears Nans are happening because of Frenet algorithm in the Nurbs Sweep node. At some point, your path curve has zero curvature (probably in the start / end point?). Calculation of Frenet frame in such point causes division by zero, hence we have NaNs. If you select, for example, Householder algorithm, you will have something more sensible.

**Comment by rendetto** [comment]
> I could probably make this more explicit in the UI...

It makes sense, yes. 

> At some point, your path curve has zero curvature (probably in the start / end point?).

Yes, that should be the case since I'm using TMax close to 1.0 (0.999999) for the segments I took from Native NURBS Curve, and because of https://github.com/nortikin/sverchok/issues/4722 the curve at the end gets straight.
As you can test - if you switch to a Geomdl input curves the sweep surface is build OK - that makes sense too because Geomgl and Native behave a bit differently at the end when approaching TMax = 1.0.
Geomdl gets the straightening bug a bit slower than Native.

Noted that it's just a corner case here.

Thanks again for the clarification :)

Thanks :)
