### ISSUE TITLE
Remove some nodes

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4737]
## Problem statement

I guess there are nodes which can be removed for some reason:

- [ ] - Object Edit mode. #1072
  
  ![e2db3f6a-cf9e-11e6-8b8d-eaba4108d84b](https://user-images.githubusercontent.com/28003269/199654110-16862764-ba97-4e7b-9a36-12137d8feee2.gif)

  I don't see the role of the node in Sverchok's procedural workflow.

- [ ] - 3dview Props
  
  ![image](https://user-images.githubusercontent.com/28003269/199654343-3ba5ed90-0995-49c3-a0be-5ac361ccf088.png)
  A node without sockets is not a node it's a panel. I'm not against functionality (though I also do not see how it's connected to Sverchok) but at least it should be converted to a panel or removed.

**Comment by satabol** [comment]
They a very strange. Functions are good but I have no idea how to use them as nodes.

**Comment by satabol** [comment]
@nortikin @zeffii 

[Modifiers->Modifier Make->Pipe] several params are absent.

Is it too old and need move to old nodes? What do you think? (first screen was did 8 years ago :) )

![image](https://user-images.githubusercontent.com/14288520/201471760-404d0714-41d3-4963-856e-36603189f8da.png)

**Comment by Durman** [comment]
I guess Bevel a Curve can't do such operation:

![image](https://user-images.githubusercontent.com/28003269/201576996-6e4346b5-cf90-4de1-ae75-bf603f267794.png)

**Comment by satabol** [comment]
@Durman Ok, I see. I do not understand why these parameters are hidden? This node do his job partially.

**Comment by vkter** [comment]
The bmesh node is difficult for non programmers to use: the node has errors, and there is no detailed documentation. Maybe you can hide it temporarily?
![屏幕截图 2022-11-21 212743](https://user-images.githubusercontent.com/74725748/203067223-e5a6543d-a8ad-4de6-9af9-9935d524a57b.png)

**Comment by Durman** [comment]
Bmesh nodes give alternative approach of handling geometry operations. They are experimental and have corresponding indication. To hide them is similar to delete. Nobody will know that there is such possible approach and nobody will be able to use and improve/fix the nodes.

**Comment by vkter** [comment]
At present, many nodes or functions are packaged based on bmesh. Maybe we should consider how to choose them, whether to continue packaging based on bmesh or focus on promoting this experimental bmesh operation

**Comment by Durman** [comment]
We can do both. As far as I know Bmesh are heavy objects and there can be a problem of generating thousands of them. On other side converting python lists into Bmesh and Bmesh into Python lists (or numpy arrays) can take 90% of node execution time.
