### ISSUE TITLE
Duplicate command reset duplicated Color Ramp.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4741]
Windows 11, Blender 3.3.1, Sverchok-Master.

![image](https://user-images.githubusercontent.com/14288520/200016584-4659fc8e-26b2-46e9-a7a6-8fdc9b3f74b9.png)

![Duplicate Colorramp reset](https://user-images.githubusercontent.com/14288520/200017750-4725c1ae-36ae-4ca2-912d-c1e1f38c0694.gif)

**Comment by Durman** [comment]
I will call it as a proposal because the node uses a hack to add such kind of UI into Sverchok.

**Comment by satabol** [comment]
I see. Thank you.
