### ISSUE TITLE
Bug: Vectors in SNLite Look Different

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4742]
## Problem statement

Vectors in SNLite look different.
![image](https://user-images.githubusercontent.com/2251298/200109589-e4844386-da60-4061-9f1b-3307097f6b0a.png)

## Steps to reproduce
Open my blend file.
[tmp_1.zip](https://github.com/nortikin/sverchok/files/9943306/tmp_1.zip)

## Expected result
I expect the same look as vec1 value.

## Sverchok version
v1.1.0

**Comment by Durman** [comment]
I guess if a default value is not given then a socket should not have any property. So it's correct.

Another question is how to set up a default property for a Vector socket. I tested `d=(1,1,1)` and it did not work - looks like a bug.

**Comment by mifth** [comment]
Sorry, just to clarify these guys look different.
![image](https://user-images.githubusercontent.com/2251298/200110209-7cf6060e-9223-4484-961d-28338048ee0f.png)

**Comment by Durman** [comment]
If a config does not have a default value for a socket, the socket should not show any property.

**Comment by mifth** [comment]
Maybe if it has no a default value then it could have 0,0,0 as a default value? It looks weird as there is no possibilty to change values in the node itself.

**Comment by Durman** [comment]
This is how every node in Sverchok works currently. If user didn't give any input, nodes should guess about default values.

**Comment by mifth** [comment]
Alright, thanks for the explanation. I'm closing it.
