### ISSUE TITLE
A problem about the installation of freeCAD package

### ISSUE THREAD

**Issue by 369386973** [nortikin/sverchok#4753]
![QQ20221110220013](https://user-images.githubusercontent.com/101614185/201112270-5fb844c6-be4e-4499-aed2-bd83e9a46fb9.jpg)
As you see，it fail to set path even if i had executed the installation instructions...

**Comment by 369386973** [comment]
And I want to use this tool to create intersection line between plane and  surface（nurbs）

**Comment by rendetto** [comment]
Seems like a permission problem. Not a Sverchok problems for sure. Try using the portable Blender version and run it from the extraction folder. Just be sure you have permission to write there.

**Comment by rendetto** [comment]
Slice Solid sounds like what you need.

**Comment by 369386973** [comment]
> Slice Solid sounds like what you need.
Big thx！！！
