### ISSUE TITLE
Automatic conversion vectors to matrixes with multilist is unexpected.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4771]
Windows 11, blender 3.3.1, sverchok master

Lets combine two list of vertices (9 verts and 6 verts). 
1. If set a result list to a Plane Matrix input socket then Plane node show 15 matrices. 
2. But if do path through "Matrix In" node then Plane Matrix socket show 2 list (9 and 6 verts).

![image](https://user-images.githubusercontent.com/14288520/203790441-285daf5e-ba1f-40b9-b82f-14032fc9000e.png)

I expect path 1 has to be like path 2. Investigation:

![image](https://user-images.githubusercontent.com/14288520/203790708-3c8f34ff-a38c-4de8-8cf3-33c198c45417.png)

May be some strange with automatic conversion vectors to matrices?

P.S.
I do test node and got trouble with that conversion:
![image](https://user-images.githubusercontent.com/14288520/203792828-e2a8aae7-1b03-467f-ad79-d93402630e5e.png)

Input data are same but results are different. Expected: Matrix socket has to be equals to Data socket.

**Comment by Durman** [comment]
This behaviour has historical reasons. Initially Sverchok only supported flat list of matrixes where single matrix was an object.

Later there was added support of nested list of matrix. This format still does not support all nodes, so it's optional. 
![image](https://user-images.githubusercontent.com/28003269/203900756-baf8cb73-3d56-4782-a7cb-5253fc5321fd.png)

Nested list of matrixes can handle Apply Matrix node.

**Comment by satabol** [comment]
Thank you. But is it possible to convert 2 list of vertices [9 verts,6 verts] to 2 list of matrixes [9 matrix, 6 matrix] for input socket without “matrix in”? May be exists some setting for sv_get?

**Comment by satabol** [comment]
@Durman

2. Is this code do plane conversion?

https://github.com/nortikin/sverchok/blob/ada473a00cbf3c5bdbfdfe1642642a97e55b7b2e/core/socket_conversions.py#L63-L79

**Comment by Durman** [comment]
> 1. But is it possible to convert 2 list of vertices [9 verts,6 verts] to 2 list of matrixes [9 matrix, 6 matrix] for input socket without “matrix in”? May be exists some setting for sv_get?

I don't think we can change default conversions, probably only in Sverchok 2.0.

> Is this code do plane conversion?

Yes

**Comment by satabol** [comment]
@Durman Thank you.
