### ISSUE TITLE
The performance seem dropped twice since last year

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4772]
I'm doing a pass on all setups I worked on the past few years, searching for bugs and broken things in the current Sverchok master. 
Unfortunately it seems that for the past year the performance of Sverchok dropped twice concerning this particular setup:

![Sweep_Node_PerformanceDrop](https://user-images.githubusercontent.com/66558924/203990228-7281fd52-aac2-43b2-950a-93e3ce59ccaf.jpg)

The problem doesn't seem to be in the current code of NURBS Sweep, because I deliberately reverted it to match the one from Apr 2021 and it doesn't matter what calculations it's doing - it's just twice as slow in master. So it should be somewhere else. Maybe in the update system? @Durman I've seen you making detailed studies on the node performances, can you please take a look at this?

I'm uploading the file for examination:
[Sweep_Precision_Symmetry_TestSpeed.zip](https://github.com/nortikin/sverchok/files/10093036/Sweep_Precision_Symmetry_TestSpeed.zip)

Thanks

**Comment by portnov** [comment]
Can you point a commit at which performance was "good"?

**Comment by rendetto** [comment]
This is the one I used for the testing 8bef7918a6bcbb05772c040bbbb189b4b27f5eb8
I'm not sure that I can find the breaking point commit, but I can try.

**Comment by portnov** [comment]
Theoretically it should be easy enough, using git bisect.
The only problem can be is that your file probably will not load on old blender :/

**Comment by rendetto** [comment]
I'm using several Blender versions for those purposes. I'm on it. It just will take some more time because I do those things manually x_x (need to learn about git bisect).

**Comment by portnov** [comment]
Hm. I just loaded your file on blender 2.90 with https://github.com/nortikin/sverchok/commit/8bef7918a6bcbb05772c040bbbb189b4b27f5eb8, and on 3.3.1 with master. I see no difference: for both, tree update takes about 66 ms.
What are your results?
Can you provide profiling data for "good" and "bad" cases?

**Comment by rendetto** [comment]
Ummmm... thats weird. Same scene, same revision:

Blender 2.90.0 - 25fps
DEBUG:sverchok.core.update_system:Node set updated in: 0.0332 seconds

Blender2.93.9 - 11fps but again:
2022-11-25 18:18:49,567 [DEBUG] sverchok.core.update_system: Node set updated in: 0.0307 seconds

I don't know what to think :/

**Comment by portnov** [comment]
@rendetto 
https://git-scm.com/docs/git-bisect

Basically you do:

    git checkout master

    git bisect start 8bef791

it switches you to the version halfway between master and that commit. Then you run blender and check performance. If you like it, you say `git bisect good`; otherwise, you say `git bisect bad`. It switches you to some other revision, you check it again. After some iteration,  git will guide you to the point where everything changed.

**Comment by Durman** [comment]
Also position of the cursor can effect the performance during animation =)

**Comment by rendetto** [comment]
Thanks @portnov  I was doing almost the same thing but manually :)

**Comment by portnov** [comment]
The thing is, since it divides the segment between commits by two each time, you will find the problematic commit in O(log(n)) steps instead of O(n) if you check each commit. That can be much faster.

**Comment by rendetto** [comment]
> you will find the problematic commit in O(log(n)) steps instead of O(n) if you check each commit. That can be much faster.

Valid point

**Comment by rendetto** [comment]
> Also position of the cursor can effect the performance during animation =)

What I'm doing while looking at the fps is moving the selected vertex in the viewport. 

My focus of using Sverchok is mainly at researching the Direct NURBS Modelling capabilities of the system, that's why I'm so sensitive for those fps.

**Comment by rendetto** [comment]
Found it! In fact there should be several drops but I found the first significant one.

Blender 2.93.9: ~25fps, SV commit https://github.com/nortikin/sverchok/commit/c034f1729ef375495f57fa87e829c41566c299f3
**Blender 2.93.9: ~16fps, SV commit** 2b26e66bdfdc477ec5286da9ddabccedd83a9670

The performance these days is like that:
Blender 2.93.9: ~12fps, SV commit f6676511e124811e16b2f9ff7fc9f4e64d616b22

**Comment by portnov** [comment]
Well, yeah, using `inspect` is slow.
@Durman can we remove it? https://github.com/nortikin/sverchok/commit/2b26e66bdfdc477ec5286da9ddabccedd83a9670

**Comment by rendetto** [comment]
Found the second drop.

From ~16fps at:
Blender 2.93.9: **~16fps**, SV commit cf7245cb23acdde9a4e1ad808848ed64081f3fb5

Dropped to ~13fps at:
Blender 2.93.9: **~13fps**, SV commit 1225957f1d9ebac835d743cc1228edaa185ad6e9, started from 66a4cfbbf8fecd8537b1fc2013d8ad5b573a4763

Then there are several commits that are at 6fps (due to some debug prints) until again:
Blender 2.93.9: **~13fps**, SV commit 3cf3f62c10dc87f8e67d7b5cb4420e6552b058c8 and that persists to this date.

**Comment by Durman** [comment]
I guess we should try something like this:
```diff
def debug(self, msg, *args, **kwargs):
+    if is_debug_level:
        self.get_logger().debug(msg, *args, **kwargs)
```
And the same for other log methods

**Comment by Durman** [comment]
@rendetto I've added optimizations into master. Can you check whether it was helpful?

**Comment by rendetto** [comment]
@Durman Thanks a lot! Just tested and we're about ~20fps now!

@Portnov did you manage to take a look at the second drop I found https://github.com/nortikin/sverchok/commit/1225957f1d9ebac835d743cc1228edaa185ad6e9 ?

**Comment by portnov** [comment]
not yet

**Comment by portnov** [comment]
@rendetto strange. For me, 
* at https://github.com/nortikin/sverchok/commit/1225957f1d9ebac835d743cc1228edaa185ad6e9, total recalculation of the tree you attached in the beginning, takes about 90ms;
* at previous commit, cf7245c, update takes ~60ms — so it seems you were right, that commit made things slower.
* But, in current master, it also makes 60ms!

Can you check?

**Comment by portnov** [comment]
However, I was able to find a place where it did get slower: new curve interpolation code was more generic, and, as such, it was executing more computational-heavy code for interpolation of rational curves, even when the curve was non-rational. I added a check for this to run more fast version of code for simple case in #4805. Please check.

**Comment by rendetto** [comment]
@portnov  Just checked. And yes, with https://github.com/nortikin/sverchok/pull/4805 we gained more speed.

I seems that with https://github.com/nortikin/sverchok/issues/4772 and https://github.com/nortikin/sverchok/pull/4805 the performance drops are cleared out :) 

Thanks a lot!
