### ISSUE TITLE
if Socket input has description then alignment is unexpected

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4773]
Windows 11, blender 3.3.1, Sverchok master.

If sockets created with no description attribute then all look good:

![image](https://user-images.githubusercontent.com/14288520/204056637-d9696fbd-81f9-4c27-8753-06801921751f.png)

If sockets created with description attribute then sockets label alignment at center. Expected alignment 'LEFT':

![image](https://user-images.githubusercontent.com/14288520/204056672-9937d9fb-ecbc-4b31-b488-eba16160890f.png)

The investigation:

There is a SvSocketCommon.draw function. If description has some chars then next "if" happens:

https://github.com/nortikin/sverchok/blob/ada473a00cbf3c5bdbfdfe1642642a97e55b7b2e/core/sockets.py#L495

![image](https://user-images.githubusercontent.com/14288520/204059506-f76ceb60-dbdd-4d73-bfdd-46a4bd659bba.png)

If set "alignment"='LEFT' then label move to the left with a little gap remained:

![image](https://user-images.githubusercontent.com/14288520/204060260-b6ae3dff-5a2c-4461-a225-2f3bcc8ae39b.png)

![image](https://user-images.githubusercontent.com/14288520/204059615-aed7cbdb-d579-4258-b700-59955d0b5f67.png)

the problem is in the operator:

![image](https://user-images.githubusercontent.com/14288520/204059821-ea419f0e-cb4c-4fd0-a3e9-596953160745.png)

If emboss==True then buttons show:

![image](https://user-images.githubusercontent.com/14288520/204059892-179284fd-0afb-46bb-b890-0ad7f6f8de2a.png)

I think that problem is in the operator drawing.

P.S.
May be this is expected behavior of Blender?

**Comment by Durman** [comment]
It's just a hack of showing description of a socket and it's quite unpopular in use. I guess when socket shows a property current approach unable to provide description of the socket.

**Comment by satabol** [comment]
@Durman Thank you. I found function "custom_draw" and did next layout:

(label is label and operator as icon. So gap on the left of button is invisible and all socket labels has no gap)

![image](https://user-images.githubusercontent.com/14288520/204248740-f5a5ae3a-7ee3-4666-aeba-93519baf6562.png)
