### ISSUE TITLE
A quick question：How to move points to points？

### ISSUE THREAD

**Issue by 369386973** [nortikin/sverchok#4774]
I want to move a polygon grid from its center vertices to  edge vertices.which Sverchok's node  is available?
![20221127160424](https://user-images.githubusercontent.com/101614185/204125284-2ab6def5-b035-4aa4-b640-ba952d0abe97.jpg)

**Comment by satabol** [comment]
Can you take more info?
There is several nodes to move vertices:
![image](https://user-images.githubusercontent.com/14288520/204132788-e24ef6e2-89b6-44a7-8e1e-764e97004187.png)

**Comment by 369386973** [comment]
Oh，I know these nodes, but I don't know how to move a point from a specific location to another specific location.“Specific” I mean vectors direction info.

**Comment by 369386973** [comment]
![20221127202012](https://user-images.githubusercontent.com/101614185/204134908-3ba6cf5c-7b90-40ee-9c31-ecdce794c2d5.jpg)
As shown in the screenshot, I want to move the yellow grid to the orange grid position.，and the direction of the moving vector is from the blue center point to a red edge vertex.

**Comment by satabol** [comment]
?
![image](https://user-images.githubusercontent.com/14288520/204136363-9907aace-2744-4965-8f87-4c4f4115687f.png)

**Comment by 369386973** [comment]
Vector math！thx！

**Comment by 369386973** [comment]
I got a new question：How can I separate the Polygon Grid without switching on the “Separate” button？Because I need to open it in some cases, while not in other cases.

**Comment by satabol** [comment]
There is node “Polygon Boom”: http://nortikin.github.io/sverchok/docs/nodes/modifier_change/polygons_boom.html

**Comment by 369386973** [comment]
> There is node “Polygon Boom”: http://nortikin.github.io/sverchok/docs/nodes/modifier_change/polygons_boom.html

Got it！Thanks again！

**Comment by satabol** [comment]
Glad to help.

**Comment by 369386973** [comment]
![20221128000830](https://user-images.githubusercontent.com/101614185/204145190-f67fb2ec-4b82-4aea-ab75-9e1490a2b389.jpg)
That's Strange，why the vertices&edges&faces do not be displayed in the end?

**Comment by satabol** [comment]
?
![image](https://user-images.githubusercontent.com/14288520/204157610-462174b0-ce54-4bbf-8596-856b65b218f6.png)

**Comment by 369386973** [comment]
![20221128102648](https://user-images.githubusercontent.com/101614185/204178450-c7ab45bf-2574-4093-ac13-6cd91f5df42e.jpg)
Nothing happens with “Level 1”  as well.

**Comment by satabol** [comment]
Try disconnect edges from temp.viewer (right side)

**Comment by 369386973** [comment]
![20221128132508](https://user-images.githubusercontent.com/101614185/204200451-8c791c85-304f-49cf-9138-0ce9e29ce30c.jpg)
![20221128132425](https://user-images.githubusercontent.com/101614185/204200455-f53ce4b8-59b3-43dc-84a8-8ae0e0c45c2f.jpg)
Thx！It seems to work,but I want to achieve the result of the second picture：Moving the three vertices of an independent hexagon rather than an entire hexagon.

**Comment by 369386973** [comment]
![20221128133149](https://user-images.githubusercontent.com/101614185/204201264-8d5785ee-a128-49e3-b7b3-898b5dd96e07.jpg)
The result of the first picture

**Comment by satabol** [comment]
Sorry my misunderstood, I understand you just now. ))) I outside computer now for a one or two hours.

**Comment by satabol** [comment]
https://gist.github.com/fcfc8f92cef690932e4f421a41e53733
![image](https://user-images.githubusercontent.com/14288520/204229509-55a6ec4f-8ee1-4ec9-9e18-48bff2f137a1.png)
![image](https://user-images.githubusercontent.com/14288520/204229415-ef8669b4-01a5-4950-84bc-df80c269f7c1.png)

**Comment by 369386973** [comment]
Thank you！It's helpful.
