### ISSUE TITLE
Socket property link_menu_handler unexpected result

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4779]
Windows 11, Blender 3.3.1, sverchok master.

I do test with socket params. I try to use link_menu_handler like in docs: http://nortikin.github.io/sverchok/docs/contributing/node_api.html#socket-properties

![image](https://user-images.githubusercontent.com/14288520/204667718-07ed1e7f-2d8b-420b-89f8-43f81af2a66c.png)

I expect some menu when I press 

![image](https://user-images.githubusercontent.com/14288520/204667891-fb7168e0-df65-466e-acbd-9d6b26c820eb.png)

**Comment by Durman** [comment]
Did you code some example? Could you push a branch with the test code?

**Comment by satabol** [comment]
@Durman I try recreate it with node "Field Random Probe" with the same result:
(Just add two lines of code for return list of "get_items", restart addon and create or recreate this node. Now it is only one element in returned array )

![image](https://user-images.githubusercontent.com/14288520/204741693-d4bfa78e-16f3-43aa-b3f3-14c05b9d08f8.png)

**Comment by Durman** [comment]
I guess you have to switch this on

![image](https://user-images.githubusercontent.com/28003269/204752822-e3765e15-dfbb-4595-987c-068dab8fd788.png)

![image](https://user-images.githubusercontent.com/28003269/204753007-f07ad2f0-5aed-4277-80be-b9c33a998dbc.png)

Probably docs could show a link to the option.

**Comment by satabol** [comment]
@Durman Thank you very much! Haha! Newer try third settings!
