### ISSUE TITLE
Some ideas about bmesh processing

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4780]
# Preface: 
Bmesh already exists in Blender, which deals with geometry. Bmesh is an optimized half-side data structure, which can access the element adjacency structure very quickly. 
Bmesh modules usually work together with mathutils modules, so bmesh and mathutils are closely integrated, and sverchok has a large number of nodes packaged by these two modules, in which python data and bmesh (mathutils) data are exchanged frequently, which is not conducive to performance improvement. 
 # Future of sverchok. 
1. Sverchok depends on blender, and sverchok should take bmesh as the main body to deal with grid. 
2. Make up for the deficiency of bmesh and mathutils with the help of many python modules. 
At present, a lot of work has been done on the second point, and the first is stagnant. 
# I will promote bmesh processing, and the process will be recorded here

**Comment by Durman** [comment]
Here are my thoughts about bmesh nodes #4572

Also if you are willing to spend some time on it, it would be nice to update existing bmesh nodes. Since they are in alpha state they can be changed in any way without creating new node version.

![image](https://user-images.githubusercontent.com/28003269/204707787-4005004b-d69a-45dc-9c1e-a7adb98a004c.png)

**Comment by vkter** [comment]
Rewrite the bmesh input-output node
![image](https://user-images.githubusercontent.com/74725748/206595814-42425693-0a0b-49f1-90eb-16431682aaff.png)

**Comment by vkter** [comment]
Preliminary rewrite of the bmesh ops processing node, which contains all the functions of the bmesh.ops module
![image](https://user-images.githubusercontent.com/74725748/206601200-7434443b-1c34-4d6e-87a1-a3dfeb2e1e1d.png)

**Comment by vkter** [comment]
The bmesh module already exists all in the form of nodes in the form of sverchok

**Comment by vkter** [comment]
Bmesh will exist in Sverchok in the form of additional extensions
https://github.com/vkter/Sverchok-Bmesh

**Comment by mifth** [comment]
Lovely, exactly we need bmesh.

**Comment by mifth** [comment]
Bmesh in sverchok is like Geometry sockets in GN. In my view.
