### ISSUE TITLE
Sverchok animation crashes. 

### ISSUE THREAD

**Issue by Teamfiy** [nortikin/sverchok#4781]
Windows 10, Blender 3.4\3.3, latest sverchok build. 
I ran into a problem with constant crashes in my phyllotaxis animation project. I use sverchok to build curves, which I then process in geometry nodes. 
![image](https://user-images.githubusercontent.com/68289842/204765298-adfc3dd1-ea8f-4aa4-8517-b392faa1eb68.png)
I spent several days trying to understand what causes these crashes. I usually looked at which frame the crash happened and adjusted the specific parameters of my nodes for animation. That worked on sometimes, but my project became bigger and it always started to crash when i make wrong move.
I use a lot of attributes written on the mesh viewer here. and I suspect that it is because of them that crashes occur, but before they worked perfectly:

![image](https://user-images.githubusercontent.com/68289842/204765929-6531e112-2fa9-47ce-859d-41295e4cdf08.png)
![image](https://user-images.githubusercontent.com/68289842/204764667-85697329-b474-4ddd-a330-48831fc529b0.png)

 I've disabled and enabled a bunch of nodes, reverted to previous versions of blender, created clean files with this tree, but it still crashes.
I repeatedly looked at the crash logs and realized that the problem is with the addon: 
Example of crash log: (I don't understand much about it, so I can send full logs. They are usually the same, but some lines are different)
# Python backtrace
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\nodes\object_nodes\set_mesh_attribute.py", line 57 in set_attribute_node
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\nodes\object_nodes\set_mesh_attribute.py", line 136 in process
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\core\update_system.py", line 467 in main_update
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\core\update_system.py", line 444 in update_animation
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\utils\profile.py", line 107 in wrapper
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\core\update_system.py", line 41 in control_center
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\core\event_system.py", line 33 in handle_event
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\node_tree.py", line 254 in process_ani
  File "C:\Users\Teamf\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\sverchok-master\core\handlers.py", line 92 in sv_update_handler
  
 How can i debug this issue? I really like sverchok, but the animation with it is hell

**Comment by satabol** [comment]
Hello @Teamfiy

This is instruction to tune debug environment for python in Blender. I use Standalone Visual Studio Code (VSCode) to catch exceptions with python.
Read it first and make sure you understand it. This is not one step instruction.
To use this instruction you need to:

**1. Download Blender Portable, Visual Studio Code portable and sverchok master**

![image](https://user-images.githubusercontent.com/14288520/204902603-e3f7ba0a-760e-42c0-99d8-fae1275a0a93.png)

VSCode: https://code.visualstudio.com/download Unpack it to some folder. I use **F:\install\vscode\VSCode-win32-x64-1.73.1**
Blender: https://www.blender.org/download/ (I use folder **D:\Install\Blender\blender-3.3.1-windows-x64**)
Sverchok: https://github.com/nortikin/sverchok  (I use folder **F:\Enternet\projects\blender\addons\sverchok**)

(May be you have to install Python 3.10.2 for blender 3.3.x, read Python instruction: https://www.python.org/downloads/release/python-3102/ )

![image](https://user-images.githubusercontent.com/14288520/204903917-ca2fce7b-dcd9-40eb-ac14-f4ca93a86eff.png)

If something goes wrong I just remove folder with portable blender and **C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\3.3**. But some times I do backup of this folder:

![image](https://user-images.githubusercontent.com/14288520/204900841-da85c5f7-77a5-4726-ac0e-eb95e9a94458.png)

**2. Switch off and Uninstall sverchock in your Blender**

(this is destructive for your version of sverchok)

![image](https://user-images.githubusercontent.com/14288520/204901645-ab750768-06ad-4d22-bad5-8b552d8b3225.png)

You should remove this folder in your profile:

![image](https://user-images.githubusercontent.com/14288520/204905391-50d6c20e-4ed7-489d-b0fb-f2cf7ee77380.png)

**3. Run VSCode and Install Plugins for VSCode with names "Blender Development" and "Python"**:

![image](https://user-images.githubusercontent.com/14288520/204899080-fd63ba57-30c5-4a62-9842-4e44cc61413d.png)

**4. Do hard link to sverchok folder in your profile folder**

with Run->CMD
mklink /d "C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\sverchok" "F:\Enternet\projects\blender\addons\sverchok"

change username to your profile:
![image](https://user-images.githubusercontent.com/14288520/204915819-243800c6-8458-4bbf-915d-0a7cfee5e671.png)
![image](https://user-images.githubusercontent.com/14288520/204915675-f40e3506-a0a3-4c23-ba89-47b18e629042.png)

**5. Start VSCode**

I think it is time now to start Blender under VSCode debugger. So open VSCode and open folder with sverchok:
![image](https://user-images.githubusercontent.com/14288520/204907776-fc744579-4fb6-43dd-98c0-67b4e0b14c4c.png)

Blender has to be opened:
![image](https://user-images.githubusercontent.com/14288520/204908086-84936f09-4914-46d7-ba5a-de1511e5ad21.png)


**6. Try simple scheme**

Set Break Point and catch it on value change:
![image](https://user-images.githubusercontent.com/14288520/204914136-23ee17bb-ad56-4a9e-ba98-35405e5a79fa.png)

Then go to your scheme to debug.

**Comment by Durman** [comment]
Will it crash if Lock User interface is on?

![image](https://user-images.githubusercontent.com/28003269/204966389-65480bd6-e0ef-4eae-bb94-524e247a6cff.png)

**Comment by Teamfiy** [comment]
@satabol thank you for instruction, But i missed a very important clarification: blender only crashes when rendering an animation, when I run viewport render everything works great and never crashes. That is, I can't find a specific place and reason manually, I just can't finish rendering in eevee, Cycles, Workbench. Simply changing the values ​​responsible for "procedural keyframing" sometimes helps, but the problem of crashes remains and I can run a render with a successful setup several times and the crashes occur again. 
So I tried @Durman's suggestion for a few hours and it solved my problem pretty well, but sometimes crashes still happen for some unknown reason, maybe blender and geonodes, I'm still working on that. Thanks, I have never used this checkbox, now I will never turn it off for procedural motion😅

**Comment by Durman** [comment]
@satabol Such detailed answer would be nice to have in docs
