### ISSUE TITLE
Poly Arc. cannot use "Center" output socket

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4788]
Windows 11, Blender 3.3.1. Sverchok master

![image](https://user-images.githubusercontent.com/14288520/205466730-8548a5c6-99b3-4a83-8b63-d8f3c2fee796.png)

https://gist.github.com/dd030e059781134410fd5e248e842e7c

Can not convert numpyarray to matrix or vectors.

**Comment by portnov** [comment]
As a temporary solution, you can use Formula node with formula = "x.tolist()".

**Comment by satabol** [comment]
@portnov Thank you. This is calc now with some convertion:

![image](https://user-images.githubusercontent.com/14288520/205483744-abb36f3b-300f-480c-b137-827f79ac2ba7.png)
https://gist.github.com/10888725365c458afdeb95ed2e21e42a

But... this is not centers. Am I doing something wrong?

**Comment by portnov** [comment]
I believe those are matrices - the same as mathutils.Matrix, just in numpy form for some reason. And, from what I see on your screenshot, those matrices contain only rotational component. Have no idea why at the moment :)
