### ISSUE TITLE
The text floats away from the stethoscope in Blender 3.4.

### ISSUE THREAD

**Issue by Gaalets** [nortikin/sverchok#4797]
Win 10, blender 3.4, Sverchok  1.2.0 last.

The text floats away from the stethoscope.

![сверчок](https://user-images.githubusercontent.com/120024667/206180104-98f2ba12-20f5-4209-b016-10fb9e287fcc.PNG)

**Comment by Durman** [comment]
It's known - #4709. Thanks ))
