### ISSUE TITLE
Some problems  "cross section" at the zero point.

### ISSUE THREAD

**Issue by Gaalets** [nortikin/sverchok#4799]
Some problems at the zero point.  The "cross section" does not cut in the XY plane at Z=0 if it hits the edges. In any other Z - normal slice. 1) Icosphere - a slice at zero - torn, full section not work. 2) Torus - there is a ring inside, there is no external cut.  Any other slices are normal.
![image](https://user-images.githubusercontent.com/120024667/206217829-003d6bcc-1c2e-467d-b156-0557700cde0e.png)
![image](https://user-images.githubusercontent.com/120024667/206218456-d6fad077-ae13-4a26-a6cd-f4a9be126f5c.png)
![image](https://user-images.githubusercontent.com/120024667/206218641-fe88121d-94c6-4e99-9163-322298cbb5f3.png)

**Comment by Durman** [comment]
Use bisect node instead. It's more efficient and it seems does not have the issue.

![image](https://user-images.githubusercontent.com/28003269/206360734-2ad17f2f-ae1d-443a-b5cf-967725378d4a.png)
