### ISSUE TITLE
Subdivide to Quads

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4812]
## Problem statement

Unless output Edges socket is not connected the node rises the error.

![image](https://user-images.githubusercontent.com/28003269/207031936-34be06c7-9054-4e0e-aebd-6169fee6e78f.png)

**Comment by satabol** [comment]
I have no exception on master now:
![image](https://github.com/nortikin/sverchok/assets/14288520/805f1e11-404e-4e38-a231-dd2f6fc59952)

**Comment by Durman** [comment]
I don't know why but I still have the error on this line.

https://github.com/nortikin/sverchok/blob/3026ccb1a9944c5efd9efb824fec0b0e5d79fe6e/nodes/modifier_change/subdivide_to_quads.py#L144
