### ISSUE TITLE
BUG: Negative and Positive Offset Values Have Same Direction.

### ISSUE THREAD

**Issue by mifth** [nortikin/sverchok#4818]
## Problem statement

OffsetCurve node has the same direction with positive and negative values (1 and -1). I guess this is a bug.

![image](https://user-images.githubusercontent.com/2251298/207423438-87134b2f-9572-49a2-8807-d713d9369ab7.png)
![image](https://user-images.githubusercontent.com/2251298/207423477-01c04263-d5bf-468d-aa33-59bd4bd76339.png)

Blend file:
[tmp_1.zip](https://github.com/nortikin/sverchok/files/10221310/tmp_1.zip)

**Comment by mifth** [comment]
Found a fix.  X and Y vectors should alway be the same or absolute. That's because offset_vector and offset_amount become both negative.
![image](https://user-images.githubusercontent.com/2251298/207426087-6ddf2b56-cebc-456e-8340-8458cab68b3c.png)

**Comment by mifth** [comment]
Or vectors should always be positive and normalized. As they are multiplied to offset_amount after.
![image](https://user-images.githubusercontent.com/2251298/207427084-1810aeba-262a-4697-ba17-4c7ecc05bfa0.png)

**Comment by mifth** [comment]
Oops sorry, I wanted to make a pull request but I did a commit. https://github.com/nortikin/sverchok/commit/b7c5278a52781875996737bda5fcbec261a54c96

**Comment by mifth** [comment]
I can prove that this is correct as the formula looks like this. 
![image](https://user-images.githubusercontent.com/2251298/207429315-c745f4dc-ae8c-4431-b700-75b15740b3aa.png)

**Comment by rendetto** [comment]
I confirm this bug. Just tested the solution https://github.com/nortikin/sverchok/commit/b7c5278a52781875996737bda5fcbec261a54c96 and it seem solved the problem.

**Comment by mifth** [comment]
Thanks for testing, I'm closing the issue. Sorry again for the commit. I messed the Commit and PullRequest buttons.
