### ISSUE TITLE
GeomDL implementation of NURBS Loft (and possibly NURBS Sweep) was using all metrics

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4822]
@portnov I just opened an old setup of a NURBS Loft where the node successfully uses Points (and all the other metrics) and the results are matching Native implementation. So apparently it's was possible at least for lofting. I don't know about the NURBS Sweep but I saw in the code that it uses also lofting so I suppose it can use the other metrics as well, but you can tell better.

![GeomDL_can_use_Points_metric](https://user-images.githubusercontent.com/66558924/207955646-1d97e38b-9197-4959-ac16-3bb393411d8b.jpg)

Just to remind.. After https://github.com/nortikin/sverchok/issues/4735 you [stated](https://github.com/nortikin/sverchok/issues/4735#issuecomment-1302355712)
> About "Unsupported metric": Geomdl's interpolation supports only "Euclidian" and "Centripetal" metrics. I could probably make this more explicit in the UI...

and then you pushed https://github.com/nortikin/sverchok/commit/f8521ad59ce9748a3546754e4ff609e280afd5dc

Now if we try using other metrics with GeomDL Lofting, we got the error message. 

This is the old setup I have:
[GeomDL_Loft_can_use_Points_metric.zip](https://github.com/nortikin/sverchok/files/10240269/GeomDL_Loft_can_use_Points_metric.zip)
I used Blender 2.93 and an old Sverchok 925540f0646f1317f37fe12a60360a9af0b1a315 for this example.

**Comment by portnov** [comment]
Well... as you can see on line 861
https://github.com/nortikin/sverchok/commit/f8521ad59ce9748a3546754e4ff609e280afd5dc#diff-8576ea978ecc39db6c202e10a2f7fcb86f5a7aa7aa050ab24e1e688873fc3e1fL861
In fact, any metric you would specify, was mapped into one of two values of `centripetal` parameter of Geomdl's interpolate method: CENTRIPETAL was mapped into `centripetal == True`, and any other was just (implicitly) mapped into `centripetal == False`. In general, I'd say, it's better to raise an error, than implicitly do something other than you were asked for, without warning :)

**Comment by rendetto** [comment]
Ah .. now trying to check the NURBS Sweep node with GeomDL and Points, but the Sweep Node tells me that it cannot have rational iso curves with GeomDL:
![GeomDL_NURBS_Sweep_Error](https://user-images.githubusercontent.com/66558924/207961531-20be3185-b04c-406a-b644-acb80b65423d.jpg)
[Sweep_GeomDL_Error.zip](https://github.com/nortikin/sverchok/files/10240487/Sweep_GeomDL_Error.zip)
I know that we cannot get iso curves from Retional NURBS GeomDL surface, but surely we can take iso curves from a non-rational one (B-Spline):
![IsoCurve_from_GeomDL_Surface](https://user-images.githubusercontent.com/66558924/207963375-fe1d4f04-50d0-4075-b5bf-8b6af2f8c617.jpg)
So apparently there is a way to create a Non-Rational NURBS Sweep with GeomDL.

**Comment by rendetto** [comment]
> Well... as you can see on line 861 [f8521ad#diff-8576ea978ecc39db6c202e10a2f7fcb86f5a7aa7aa050ab24e1e688873fc3e1fL861](https://github.com/nortikin/sverchok/commit/f8521ad59ce9748a3546754e4ff609e280afd5dc#diff-8576ea978ecc39db6c202e10a2f7fcb86f5a7aa7aa050ab24e1e688873fc3e1fL861) In fact, any metric you would specify, was mapped into one of two values of `centripetal` parameter of Geomdl's interpolate method: CENTRIPETAL was mapped into `centripetal == True`, and any other was just (implicitly) mapped into `centripetal == False`. In general, I'd say, it's better to raise an error, than implicitly do something other than you were asked for, without warning :)

I'm not sure that I understand correctly. I thought that when requesting from GeomDL to use Points it will fallback to Centripedal or Distance, but that was not the case. What I tested is that using Points with GeomDL I got the same control point positions as with Native and Points, so it appears to me that we can use all metrics and get the same results like with the Native implementation. Is it necessary to limit the use of GeomDL? I'm a bit confused

**Comment by rendetto** [comment]
Ummm... I opened the current code and the old code and I'm confused a bit more because GeomDL Loft does not throw "Unsupported metric" on the operations from the above video. It just works.

**old:**
[`    def interpolate(cls, degree, points, metric='DISTANCE'):
        if metric not in {'DISTANCE', 'CENTRIPETAL'}:
            raise Exception("Unsupported metric")
        centripetal = metric == 'CENTRIPETAL'
        curve = fitting.interpolate_curve(points.tolist(), degree, centripetal=centripetal)
        return SvGeomdlCurve(curve)`](https://github.com/nortikin/sverchok/blob/925540f0646f1317f37fe12a60360a9af0b1a315/utils/curve/nurbs.py#L533-L538)

**current:**
[`    def interpolate(cls, degree, points, metric='DISTANCE', **kwargs):
        if metric not in {'DISTANCE', 'CENTRIPETAL'}:
            raise Exception(f"`{metric}` metric is not supported by interpolation routine of Geomdl library; supported are DISTANCE and CENTRIPETAL")
        centripetal = metric == 'CENTRIPETAL'
        curve = fitting.interpolate_curve(points.tolist(), degree, centripetal=centripetal)
        return SvGeomdlCurve(curve)`](https://github.com/nortikin/sverchok/blob/master/utils/curve/nurbs.py#L934-L939)

**Comment by portnov** [comment]
> Is this an illegal operation, because is seems to work fine?

Geomdl's `interpolate` method does not have an option to specify arbitrary metric. It has only one boolean parameter: `centripetal == True` for centripetal metric or `centripetal == False` for Euclidean metric.

Because of
```
        centripetal = metric == 'CENTRIPETAL'
        curve = fitting.interpolate_curve(points.tolist(), degree, centripetal=centripetal)
```
If you specified any metric other than CENTRIPETAL, actual geomdl's method was called with `centripetal = False`, i.e. the interpolation was done with Euclidean metric. IMHO it was incorrect behaviour: you asked, for example, Manhattan metric, the node said "okay", but actually used Euclidean metric instead. Now it just reports that the metric you want can not be used.

**Comment by rendetto** [comment]
I understand. So my question is how it's possible for the Loft node to output the same result with GeomDL and Native? If Native uses Points and GeomDL uses Euclidean, we have to get different control points positions, right?

**Comment by portnov** [comment]
Not necessarily. At least, not in each case. The shape of resulting surface depends not so much on numeric value of the metric between each pair of points, as on relations between metrics between different pairs of points. For example, let's say we have three points, A, B, and C, and Euclidean distance A-B is 2, and Euclidean distance B-C is also 2. When these values are used to construct curve's (or surface's) knotvector, it will only matter that A-B is equal to B-C, because we calculate knotvector by splitting interval [0; 1] proportionally to metric values; so T value for A will be 0, for B will be 0.5, and for C will be 1.0.
"Points" distance mean just number of point in the list, so if we have [A,B,C], then distance A-B is 1, and B-C is also 1, so again, A-B is equal to B-C, so we will again have T[A] = 0, T[B] = 0.5, T[C] = 1.0.
On the other hand, if we take some totally different metric, for example Manhattan, it may appear (for some specific set of points) that A-B is 2 and B-C is 1. Then we will have T[A] = 0, T[B] = 0.666.., T[C] = 1.0. Or, with another set of points, it may appear that values of Manhattan metric between points also have the same relations as values of Euclidean metric - then we will again have [0, 0.5, 1.0].
Knotvector is calculated as first step of interpolation algorithm, so given fixed positions of initial points, different knotvectors will lead to different control points position, and equal knotvectors will lead to equal control points position.

**Comment by rendetto** [comment]
Thanks that explains a lot. So following this logic I can assume that in my experiment I have a special case - a case where Native/Points produces the same result as GeomDL/Euclidean, if I understand correctly. 

If that's the case when I compare GeomDL/Points with GeomDL/Euclidean I should get same control point positions, right?
But the results are different:

![GeomDL-Euclidean_vs_GeomDL-Points](https://user-images.githubusercontent.com/66558924/208236170-8d21ef64-6926-487c-bf47-6570840b5548.jpg)

Am I mistaken something?

**Comment by rendetto** [comment]
Well...I was no mistaking. I think I found an answer or at least I think of it like that.
It seems that the NURBS Loft node was doing something hacky - it was taking the first Section curve type https://github.com/nortikin/sverchok/blob/1f9f99b4ae7f6123639426de22b5cc34e44a7807/utils/surface/nurbs.py#L1173 and doing the interpolation on that base https://github.com/nortikin/sverchok/blob/1f9f99b4ae7f6123639426de22b5cc34e44a7807/utils/surface/nurbs.py#L1201 while retaining the output Surface/Implementation type requested by the user.

In short - we feed Native curves to NURBS Loft node, choose GeomDL as implementation, choose Points metric and at the end we get GeomDL type surface that is build with the Points metric (despite GeomDL itself cannot do this type of metric).

On the other hand if we feed GeomDL curves in the GeomDL Loft node and we request for Points metric we get an error "metric not supported" ...because the GeomDL math does not know this type of metric.

And there's a third type of behavior: We feed GeomDL Curves to a Native Loft node, choose Points and... again get "metric not supported".

The only benefit from this erratic behavior is that if we want GeomDL type of surface in the end we can have it (but we have to input FreeCAD or Native curves first)

So the conclusion I can have is that the current SV master code is more consistent even if we cannot get the desired output. The previous code was "working" giving the requested result by a hacked solution.

As a workaround of this new situation, if we need specifically GeomDL type of surface at the end, we can just convert the lofted Native Surface to a GeomDL one using the Deconstruct Surface node and a Build Surface Node.
...Why we will need GeomDL over Native surface ...that's a question I cannot answer still :)

@portnov Thank you for your patience and again for all detailed explanations. If you don't have anything to add, we can close this issue.

**Comment by rendetto** [comment]
So case closed :)
