### ISSUE TITLE
Sverchok file can't run after saving changes.

### ISSUE THREAD

**Issue by FredRus** [nortikin/sverchok#4834]
## Problem statement
I was working on a node group with about 60 nodes. I saved the file, and I was working on it just fine. But when I tried to reopen it, blender stayed on a frozen screen and stayed unresponsive.

## Steps to reproduce
Try to open this blend.zip file
[House_SV.zip](https://github.com/nortikin/sverchok/files/10280085/House_SV.zip)

## Actual result
Blender could not be responsive, and the screen froze forever.

https://user-images.githubusercontent.com/120553860/208971879-6eda60cd-5138-4125-9e96-ce255edfb728.mp4

## Sverchok version
1.2.0 latest

**Comment by Durman** [comment]
It seems this is problem of Bforartist. Probably it's damaging Blender file somehow. Try to open a bug report there that you can't open the file.

**Comment by FredRus** [comment]
It seemed to work fine after I separated the group into smaller node groups. Maybe It's the number of nodes within a single node group that it didn't like. But there were less than 80 nodes in the group before separation. I don't understand how that could be too much.

**Comment by Durman** [comment]
If you have certain steps how to reproduce the problem from scratch I can try it in Blender.

**Comment by FredRus** [comment]
The thing is, I don't know what led to it crashing. I may end up giving you steps that don't contribute to the crash at all. But here are the nodes that I think may have had the biggest impact:
1)Loops
2)Component Analyzer: it was processing some like 3k faces, which is not too much but that may be a cause.
Otherwise, everything else was just simple transformations
