### ISSUE TITLE
Viewer Draw

### ISSUE THREAD

**Issue by Durman** [nortikin/sverchok#4837]
## Problem statement

Viewer Draw node can crush Blender (at least in 3.4.0).

![image](https://user-images.githubusercontent.com/28003269/209189896-681d9aeb-7735-481d-91bb-00852b2411c9.png)

[untitled.blend.zip](https://github.com/nortikin/sverchok/files/10289095/untitled.blend.zip)

**Comment by satabol** [comment]
I reproduce error:

![image](https://user-images.githubusercontent.com/14288520/209211101-52a1a4b5-2bf7-470d-a08b-48788146d152.png)

Crash is not good but expected in this situation. Proposal is to check **geom.v_vertices** length for first vertex. If first point has three digits and other are not then no crash and only errors in console:
![image](https://user-images.githubusercontent.com/14288520/209212019-d1797bd9-5180-49e4-adcc-f34d320f52d9.png)

If set this rules then no crash happens:
![image](https://user-images.githubusercontent.com/14288520/209212175-2f25b6bf-ea29-4b9e-8951-0a9c8a4781c8.png)

May be zero check is not enough (?)

**Comment by satabol** [comment]
@Durman , hello. Can you see fix for this issue?
