### ISSUE TITLE
Weird noodle overlay Sverchok

### ISSUE THREAD

**Issue by FredRus** [nortikin/sverchok#4839]
## Problem statement
The file I am working on gives me weird errors. They are a lot of them to an extent I don't know whether I should make a bug report for them all individually

## Steps to reproduce
This error occurred for a reason I don't know

## Actual result
![Sv_Noodles](https://user-images.githubusercontent.com/120553860/209416892-2ee25ae9-ca59-4482-a728-ad79e921e1a8.png)

## Sverchok version
Sverchok version 1.2.0 blender version 3.4.0

## Extra info
Let me know if it's okay whether I should pack most of the buggy issues I came across into a single file or make many bug reports for the most common ones. I think making a single bug report for each one of them could crowd the issues queue

**Comment by Durman** [comment]
There should be certain steps to reproduce the error, other wise I don't think it will be possible to fix.

**Comment by satabol** [comment]
You use 3.4.0 **Alpha**. Try use 3.4.1?
