### ISSUE TITLE
Exec Node Mod error

### ISSUE THREAD

**Issue by vkter** [nortikin/sverchok#4845]
A strange error：name 'bm' is not defined
```
import bmesh
for ind,bm in zip(V1,V2):
    edge = [bm.edges[i] for i in ind]
    bmesh.ops.collapse(bm,edges=edge)
extend(V1)
```

**Comment by zeffii** [comment]
i imagine you solved this already?  the content of V2 is not automatically converted to a bmesh representation, V2 would need to be a nested list of bmeshes, for you to be able to seek `bm.edges` - until such time i wouldn't really trust any error message..
