### ISSUE TITLE
"Bend along surface field": Src U/V parameters are not documented good enough

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#4854]
When Orientation == Z, Src U Min/Max for some reason correspond to min/max Y, not X!

**Comment by satabol** [comment]
Hello. Can you show example with nodes? (with parameters of surface node)

**Comment by satabol** [comment]
If you move points (1) to points (2) of node "Surfaces->Plane(Surface)" then U/V swap.

![image](https://github.com/nortikin/sverchok/assets/14288520/0cd604cf-33b0-427d-a1c0-aca8e06f2c37)

So I think the problem is not in the node "Bend Along Surface field".

**Comment by satabol** [comment]
Hi @portnov. May be convert default params for “Plane (surface)” to (2) to exclude this collision?
