### ISSUE TITLE
Why does the Geo Nodes Viewer not support custom list inputs?

### ISSUE THREAD

**Issue by FredRus** [nortikin/sverchok#4859]
## Problem statement
Sverchok version 1.2.0 alpha
I was experimenting with the Geo Nodes Viewer node and trying to use custom position inputs. It truly makes multiple inputs, but the values all stay at zero despite the values you plugin
## Steps to reproduce
![Geo Nodes Viewer](https://user-images.githubusercontent.com/120553860/210691855-03dc0d75-d32d-4b49-8d0a-d8526173cd8a.png)

## Expected result

Expected the values to not be all zero and the points not at the same location

**Comment by Durman** [comment]
This is a limitation of the approach. See the documentation:

http://nortikin.github.io/sverchok/docs/nodes/viz/geo_nodes_viewer.html

![image](https://user-images.githubusercontent.com/28003269/210750447-5d37f3b2-7381-44ce-9b87-ce6595690e8b.png)

**Comment by FredRus** [comment]
Why doesn't this setup work either?
![Geo Nodes Viewer1](https://user-images.githubusercontent.com/120553860/210843056-6b415e63-63fd-447b-b37a-57124e0eef59.png)

**Comment by Durman** [comment]
This is because you are reading vertices from point cloud domain meanwhile actual values are on vertices domain.

![image](https://user-images.githubusercontent.com/28003269/210848106-dbecd09c-b9e2-4eb2-9300-604fc4df5d4b.png)

**Comment by FredRus** [comment]
Thanks for the answer! This was helpful
