### ISSUE TITLE
Can't use the Num Expression Node

### ISSUE THREAD

**Issue by FredRus** [nortikin/sverchok#4862]
## Problem statement
I failed to use the num expr node in sverchok. It gave me an error that numexpr has no attribute called evaluate. I used pip to install the module into blender's site package folder in Vscode. It installed numexpr.whl into a numexpr folder and numpy v1.20.0 if I can remember very well. I don't know if this is enough for the node to function, or I need more dependency Levels

## Sverchok version
1.2.0-alpha

**Comment by Durman** [comment]
Are you sure that it says that numexpr does not have evaluate attribute and not None value? If None value has the AttributeError then Sverchok failed to import the library. But in this cases this is also a bug because the node should raise an error that the library is not installed. 🤔

**Comment by FredRus** [comment]
The module works inside of Vscode using blender python. But when trying to load it into Blender'd Python console, it shows:
![Numexpr_blend](https://user-images.githubusercontent.com/120553860/211445518-f7ad3f78-6e37-4d29-8817-9c030f4cb10e.png)

If I change the __init__ file name to something else, that's when it loads the error NonType has no evaluate attribute.
my numexpr folder looks like this:

![Numexpr_Floder](https://user-images.githubusercontent.com/120553860/211445379-58df2a12-749c-4fc4-8d46-8f62d3bfc332.png)

**Comment by Durman** [comment]
It seems the problem is with installation. I don't know how to help. The contents of my folder is absolutely the same. You can try to install newer numpy version. On Blender 3.4 I have 1.22 version.

![image](https://user-images.githubusercontent.com/28003269/211468112-0cff7a13-c90e-4e6c-8188-3ed1efb8c2ca.png)

**Comment by FredRus** [comment]
I'm using the same version as yours. I don't know why it's not working

**Comment by satabol** [comment]
@FredRus I this this issue is #4984 . try https://github.com/nortikin/sverchok/issues/4984#issuecomment-1682562586
