### ISSUE TITLE
Curves->Blend Curves. With mode "Two curves" and "Concatenate: On" no concatenate.

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4867]
Windows 11. Blender 3.4.1, Sverchok-master:

![image](https://user-images.githubusercontent.com/14288520/211350770-1e489152-e29d-4a80-9ca9-b44a4a7bfffd.png)

Mode "List of Curves" work good.

**Comment by satabol** [comment]
@portnov Hi.
I found:
https://github.com/nortikin/sverchok/blame/4c4bbcaaf5ba11635e17dad108c38fab98152e21/nodes/curve/blend_curves.py#L248-L253

If remove self.mode='N' all work good. Is it ok? Can I do Pull Request for this?

**Comment by portnov** [comment]
ok :)

**Comment by satabol** [comment]
Hi @portnov. Can you see a fix for this? Also I upload blend file for tests.

**Comment by satabol** [comment]
Not all properties are visible if mode is "two curves":

![image](https://github.com/nortikin/sverchok/assets/14288520/dc6d548b-e00e-43fe-8b65-9104d54abed1)
