### ISSUE TITLE
Feeding [[[]]] to socket Vertices in "Viewer Draw" node will crash Blender

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#4875]
Blender crashes when passing a triple nested empty list to the "Viewer Draw" node (Blender3.4.1 with Sverchok master)

![Tripple_Nested_Empty_List](https://user-images.githubusercontent.com/66558924/212556940-6cb50084-1b0f-4401-88d2-af4802de94db.jpg)

It was not a problem a while ago.

This is the example file (just activate Wrap to add one more level):
[blender_crash.zip](https://github.com/nortikin/sverchok/files/10420782/blender_crash.zip)

**Comment by satabol** [comment]
I think this issue is a duplicate of #4837 and there is a fix for this #4838 in pull request.

**Comment by rendetto** [comment]
Sorry. Closing as duplicate.
