### ISSUE TITLE
"Approximate NURBS Curve - FreeCAD" node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#4880]

**Comment by rendetto** [comment]
@portnov Are you about to implement it already?

**Comment by portnov** [comment]
No, I just created an issue to do not forget that I wanted to :)

**Comment by rendetto** [comment]
Perfect! I'm almost there, just need to make some tweaks. I found several approximation ..ways on OCCT and tested the PointsToBSpline (the above screenshot which I'm about to implement) and the ApproximateWire (which was not so good):
![FC_approx_wire](https://user-images.githubusercontent.com/66558924/214082040-e26afdc6-0b57-4cb8-86f9-9b5387db4cb1.jpg)

So I guess I'll need a day or so, in case everything does smoothly :)

**Comment by rendetto** [comment]
@portnov I shared up a PR https://github.com/nortikin/sverchok/pull/4881. Hopefully I didn't messed up the node :) Documentation will follow shortly.
