### ISSUE TITLE
temporal viewer node is not showing tried in 3.4 and 2.93 blender version

### ISSUE THREAD

**Issue by AmitMourya1322** [nortikin/sverchok#4882]
## Problem statement

Is the problem installation related? then `visit this page first <https://github.com/nortikin/sverchok#troubleshooting-installation-errors>`_.  

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce

1.temporal viewer node is not showing tried in 3.4 and 2.93 blender version

## Expected result

What did you expect to see as a result of those steps?
show temporal viewer node

## Actual result

What did you actually get?
nothing

## Sverchok version

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.

**Comment by rwny** [comment]
temporal viewer node is from  Ctrl+Shift+left mouse click 
not on menu list
![Screenshot 2023-01-28 002958](https://user-images.githubusercontent.com/32074126/215154453-c08860bb-c431-4869-b2f4-61d4211f95c1.png)

**Comment by Durman** [comment]
Could upload a file which represents the problem.
And what is your version of Sverchok and name of OS?
