### ISSUE TITLE
UI props for Scripted node lite

### ISSUE THREAD

**Issue by FredRus** [nortikin/sverchok#4890]
## Problem
The impossibility of making your own props in scripted node lite

## Proposal
I was even able to dynamically change the properties.
I made a script that helped do this named 'make_props' but, since I'm just a noob at python, you can improve it and make a way for it to be declared in the current_node_dict. Let me know if you'll be interested in seeing it.

![snlite_expample](https://user-images.githubusercontent.com/120553860/219842427-eed9e4cf-2b80-4676-ae80-f3f309207a92.png)

**Comment by zeffii** [comment]
cool.  this is possible since day one, at least I implemented an example in an early thread - maybe I overcomplicated it.  Here was my attempt:  
https://github.com/nortikin/sverchok/issues/942#issuecomment-282285012
(dig through the thread for old experiments,  maybe some don't work anymore)

there are no noobs here, just people learning :)

**Comment by portnov** [comment]
See "custom_properties.py" script template
https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/templates/custom_properties.py

**Comment by FredRus** [comment]
> See "custom_properties.py" script template https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/templates/custom_properties.py

The problem with the script template is that once you use the property more than once, They will all have the same value.

**Comment by zeffii** [comment]
yeah `self[property_name]` i imagine will be available for all instances of nodescript, so the only way around that is to use unique property names per instance of this script.

**Comment by FredRus** [comment]
I tried some of the properties in the experiment, but they seem to not work anymore. Like [layout modifiers](https://github.com/nortikin/sverchok/issues/942#issuecomment-262738179). Some part of the code you provided needed some tweaks in order to work. The good part about the function I made is its simplicity, only providing the name and the type.

**Comment by zeffii** [comment]
@FredRus  do whatever works :)   those experiments are from 2017/18 , which is an aeon ago. 

where is 'self.make_props` defined?

**Comment by FredRus** [comment]
@zeffii 
make_props is the name of the function I added. You also give me the idea of making a subclass of the node instead of making it part of the node itself.

**Comment by zeffii** [comment]
i'm no Python authority, i'll be pleasantly surprised if it's possible to add a convenient way to define custom properties per script instance, so people can use a simple abstraction to declare properties. 

The properties directly visible on a socket however are not so easily customized, for instance I had always wanted to add a custom min/max to float and int, but that seems to make the internals really quite complicated and also requires changes in other parts of sverchok - things i've avoided when possible :) .

**Comment by FredRus** [comment]
@zeffii Your method seems to be working excellently 🥇.  After tweaking the code a little, making the properties only looks like:
![snlite_props](https://user-images.githubusercontent.com/120553860/219898371-82090a32-aca6-429d-9591-cbba70ecb0e3.png)

What can be done to even simplify this process is being able to declare the properties together with the sockets. 
Something like, 'props=bool(default=True)'

**Comment by zeffii** [comment]
declaring props on the sockets directly is a different matter, as described above, and requires an extension of the socket display functions -- to pass the origin of the property that the user wants to show on a socket. For now we settled on a limited customizability of that space. Depending on how much effort someone wants to stick into things everything is possible. We do have a way to pass a function name to the socket properties of normal nodes, sverchok would then draw the socket according to the output of the function. Currently that UI code expects the function to already be defined in the node's baseclass - also this draw_function override would need modifications specific to SNLite to work. Something i don't think we'll find much support for, and I don't want to do it :) 

another issue about explicit settings for socket min/max is that the node would then be expected to also apply min/max to the incoming data of a socket when it is coming from another node. ie, the script will still have to guard against values outside of the desired range. 

I tried to keep snlite backend simple, but if you stare at the internal code long enough you'll probably come to the conclusion that it is not simple. I called it a Lite node to draw attention to the fact that it is a compromise between simple user driven stuff vs developer backend. 

at some point it's just easier to write a full node, and include its script in Blender's TextEditor.

**Comment by FredRus** [comment]
Sure, if it has to change the code base that much, it's worth putting aside :)

**Comment by zeffii** [comment]
we ( team sverchok )  have had many talks about how to implement a convenient way for users ( including us! ) to write concisely the interface and the execution code for a node.  Frankly I welcome any input to this messy space.

**Comment by Durman** [comment]
> > See "custom_properties.py" script template https://github.com/nortikin/sverchok/blob/master/node_scripts/SNLite_templates/templates/custom_properties.py
> 
> The problem with the script template is that once you use the property more than once, They will all have the same value.

Could you show an example of the problem? It seems that two nodes can point to the same property name and have different values.

**Comment by zeffii** [comment]
> It seems that two nodes can point to the same property name and have different values.

oh yes
```python
"""
in portamento s d=1.0 n=0
out signal v
"""

if 'sn_storage_1' not in self.keys():
    self['sn_storage_1'] = 1.0

def ui(self, context, layout):
    layout.prop(self, '["sn_storage_1"]')
```

unfortunately there is no way to configure the limits of ints/floats of such node properties (unless i'm very much mistaken? ) .

**Comment by Durman** [comment]
Yes, there is an approach to set limits for custom properties, but, as I was told, node custom properties has different implementation and thus the limits does not work for them there. =)

**Comment by zeffii** [comment]
@Durman 
LOL.  of course :)  pitty.  A dynamically defined property group might be the only sane way then, and to avoid nameclashes the name would need to be n_id related.    the idea makes my skin crawl.

**Comment by Durman** [comment]
Well, probably I've remembered wrong that I was told. I guess the limits do not work for ID properties but works well for custom. At least in my test I was able to set custom description and maximum values.

Copy past to Blender text editor to display custom properties on nodes and a tree.

```py
import bpy


tree = bpy.data.node_groups.get('NodeTree') or bpy.data.node_groups.new('NodeTree', 'SverchCustomTreeType')
tree['my_prop'] = 0
tree.id_properties_ui('my_prop').update(max=10, description='Custom description')

node = tree.nodes.get('Line') or tree.nodes.new('SvLineNodeMK4')
node.name = 'Line'
node['my_node_prop'] = 0
node.id_properties_ui('my_node_prop').update(max=20, description='Custom node property')

node2 = tree.nodes.get('Line.001') or tree.nodes.new('SvLineNodeMK4')
node2.name = 'Line.001'
node2['my_node_prop'] = 0
node2.id_properties_ui('my_node_prop').update(max=30, description='Another custom node property')

class ShowObjPropOp(bpy.types.Operator):
    bl_idname = "soluserg.show_obj_prop"
    bl_label = "Show object property"      
    
    def execute(self, context):
        return {'FINISHED'} 
    
    def invoke(self, context, event):
        wm = context.window_manager
        return wm.invoke_props_dialog(self)
    
    def draw(self, context):
        layout = self.layout
        col = layout.column()
        tree = bpy.data.node_groups['NodeTree']
        col.prop(tree, '["my_prop"]')
        node = tree.nodes['Line']
        col.prop(node, '["my_node_prop"]')
        node = tree.nodes['Line.001']
        col.prop(node, '["my_node_prop"]')

def register():
    bpy.utils.register_class(ShowObjPropOp)


def unregister():
    cls = bpy.types.Operator.bl_rna_get_subclass_py('soluserg.show_obj_prop')
    if cls:
        bpy.utils.unregister_class(cls)
        

unregister()
register()
bpy.ops.soluserg.show_obj_prop('INVOKE_DEFAULT')
```

**Comment by FredRus** [comment]
@Durman 
> Could you show an example of the problem? It seems that two nodes can point to the same property name and have different values.

That was just due to my ignorance. Using the same property on the same node was what made it the same. But I don't see the reason to try to use the same property knowing you can easily make another one. I didn't realize the configuration in the template was what made the properties and thought they are built in.

**Comment by zeffii** [comment]
that's unfortunate.

**Comment by FredRus** [comment]
The code for making props can be as simple as:
![snlite_code](https://user-images.githubusercontent.com/120553860/220189807-bd93778c-8c17-4395-935e-9ad1908cd28b.png)
