### ISSUE TITLE
Raycaster node bug

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4903]
I ran into a bug where I cast a ray on a face, the ray is clearly very near from it (around 1e-6m), and whatever epsilon I put, it never detects a hit on my face.
Here is an example of this problem : [Raycaster issue.zip](https://github.com/nortikin/sverchok/files/11376274/Raycaster.issue.zip)

**Comment by Durman** [comment]
Does it show false in your case?

![image](https://user-images.githubusercontent.com/28003269/235834373-1af7474a-459d-4b84-a1d3-15b31434cd06.png)

**Comment by ArpegorPSGH** [comment]
Yes, it shows False, and my sverchok is up to date.

**Comment by Durman** [comment]
Did you try epsilon equal 0? I guess we should set it as default value of the property.

**Comment by ArpegorPSGH** [comment]
It works with epsilon=0, but I added that parameter to ensure that even with some rounding imprecision on my mesh and projection, it still detects hits that are supposed to touch the exact edge of the mesh and could otherwise pass right next to it. How is it that it does not work anymore when I increase epsilon?

**Comment by ArpegorPSGH** [comment]
Ok, I'll report the problem to Blender devs if the problem I envision really does appear.
