### ISSUE TITLE
Diameter node input format

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4907]
The Diameter node direction input only accepts directions as tuples, not lists. A list of tuples is fine, but not a pure list of lists. There is no such obligation with the vertices input. I think the node should accept both formats.

**Comment by satabol** [comment]
Temporary Solution "Vector In -> Vector Out":
![image](https://github.com/nortikin/sverchok/assets/14288520/06316527-87ed-4520-bb44-881fc1c8193e)

**Comment by ArpegorPSGH** [comment]
Yeah, I already figured this out and I'm currently using it to make the node tree work, but it is ugly.
