### ISSUE TITLE
http://nortikin.github.io/sverchok/  landing page redesign

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#491]
## edit:  now: http://nortikin.github.io/sverchok/

As we now have a growing collection of nicely formatted documentation, it's time (I think) to put the Sverchok site in the spotlight too and consider how to do an upgrade/redesign.

Prelim tests: http://sverchok.neocities.org/

**Comment by nortikin** [comment]
nice solution with md. Maybe to continue md all pages?

**Comment by zeffii** [comment]
@nortikin how about I transfer all this to: gh-pages for the project?

**Comment by nortikin** [comment]
I donno wat is gh-pages. But you can do. I just learning from you now all this and have fun when see result.

**Comment by zeffii** [comment]
instead of http://nortikin.github.io/sverchok/

**Comment by zeffii** [comment]
cool. yes I will overwrite that content. It is a special type of branch, which doesn't track the main repository but is related

**Comment by nortikin** [comment]
yes, remember that page. Cool

**Comment by zeffii** [comment]
ok done. check again

**Comment by nortikin** [comment]
working. will update with github

**Comment by zeffii** [comment]
now we can collaboratively edit the markdown and style the css. not sure how to approach dual language but if you want larger audience, it may be more convenient to show english first?

**Comment by zeffii** [comment]
I think the javascript (js) is written a way that lets you understand how it works, if not always i am open to questions

**Comment by nortikin** [comment]
site has to be stratchable, so for any width of monitor it needs to be same - from left to right nomergin.
As Artemiy Lebedev do

**Comment by zeffii** [comment]
please worry about content first, responsive design to match screen orientation / resolution will come when the content exists

**Comment by nortikin** [comment]
what with popup areas? Let it be as in old site in css or in java better?

**Comment by zeffii** [comment]
Popups can almost always be avoided. If we need a popup, let's indicate it via CSS style, the actual popup even (or popup initiated on click) can be triggered and closed via javascript.

**Comment by zeffii** [comment]
I will fix `design / color / css` issues when all content is there and grammatically correct english :)

**Comment by nortikin** [comment]
It is, let me experiment with site. Need stratchable page.

**Comment by zeffii** [comment]
yes 'responsive' design means the site should respond to window dimensions, perhaps even orientation. I wasn't finished with design and implementation of subpages yet, keep this in mind don't put too much effort into this.

**Comment by nortikin** [comment]
take over now, will make other content later

**Comment by zeffii** [comment]
OK. will take a few days to add new `code + css + layout` and fix language. There may be some changes that you don't agree with but I won't know in advance.

**Comment by nortikin** [comment]
intrigued

**Comment by zeffii** [comment]
I am still thinking about these things even though not actively writing code yet. As carpenters say 'measure twice before cutting saves wood`. Where we don't have a real deadline it is not useful to impose an artificial one. I will be busy with this in slow increments for a while.

Next area of concentration will be the Lessons  / Magazine / Video heading.   

#### Video
Preferably we respect the visitors and not auto load a connection to youtube without their consent. In practice we do this by putting the video behind an image and only load the video frame when the user actively shows interest in the video. (easy)

#### Magazine
We should drop this entirely for good reasons. Only very few people care about how much Sverchok is mentioned in media, if you wanted this as a way to reinforce sverchok status.. those with true status never have to remind people of their successes, Other people do that for us.

instead of Magazine links we should make better *release notes* for major releases and write about features added / improved / fixed bugs new nodes. Write about the things we are really happy with for that release cycle. We can mix images with release cycle notes so as to make things less abstract.

#### Lessons
Many links on one page is a recipe for weakening the strength of these links.  *Firstly*, I propose a maximum visible set of 5 links per origin . 5 for BlenderSushi and say 'Showing 5 of 25`. This would indicate, there are more but we don't want to overwhelm you with them.  *Secondly*, name-only links to off-site destinations doesn't tell a reader why they should be clicking on these links. Each link should have a paragraph or at least two sentences describing what we think they'll learn from the link. This would be a good place for full .blends instead of Gallery.

#### Gallery
My intention was to reserve this for larger rendered images, to give an impression of the power of Sverchok. We don't have enough stylish renders, but sverchok is more than capable of generating the geometry to make very cool images.

**Comment by portnov** [comment]
@zeffii,  About content. I think it would be good to add something like "news" - that (in ideal world) should be current news from development, like "wow, look we implemented new cool node!", so people can know what to wait in the next release.

Another thing about design/markup... When I follow links, URL does not change. That's weird. And as far as I understand, it will not work with JS disabled. I wonder how Google or other crawlers will index it?

**Comment by zeffii** [comment]
@portnov 
> Another thing about design/markup... When I follow links, URL does not change.

Yeah, keep in mind this is a working mockup with no url routing just DOM manipulation. Not having the URL update bothers me because it also means I can't link directly to a page. Google not being able to index the whole site doesn't bother me, yet

Agreed about `news` section, or even 'latest news', I have mixed sentiment about keeping old news articles around tho.

**Comment by portnov** [comment]
You can have an "archive" page with all old news, articles, release notes and so on.

**Comment by zeffii** [comment]
I am more familiar with [GAE](https://cloud.google.com/appengine/docs/python/) and Flask, for the implementation of web pages with Python, but it would be nice to have the site run entirely in .js so it can be hosted on github.

Yes, if people have javascript disabled that's a problem, but hopefully it's a minority. (2%?).
http://stackoverflow.com/questions/121203/how-to-detect-if-javascript-is-disabled (and solution)
url/path changes in combo with history.pushState
http://medialize.github.io/URI.js/about-uris.html

**Comment by portnov** [comment]
For real site, i still think Google indexing is an important thing. And as far as i know, google's crawler does not have js enabled...

**Comment by yanivg101** [comment]
I think that if you will add a forum so people can ask "How to make...?" that will be wonderful.
when you search in Google you can find the answer too.

**Comment by zeffii** [comment]
First optimize content, then optimize implementation with respect to automated indexing 

@yanivg101 
A forum would be OK, or a simple second repo called 'Sverchok_Community" where the issue tracker is used exclusively for `how to` threads. Google indexes these quite well

**Comment by zeffii** [comment]
@yanivg101 
Would a simple second repo called 'Sverchok_Community" where the issue tracker is used exclusively for `how to` threads be OK?. Google / Github indexes these quite well, and might make more sense with our the total user count being low.

**Comment by yanivg101** [comment]
If you can go here from the main page and have it on iframe etc. I think it will be good.
but when you reach site like Github, it's not so friendly to usual user that afraid from too much technical info.

**Comment by zeffii** [comment]
A forum may or may not happen soon, but building our own community scene would be very nice. BlenderArtists tends to be a little distracting because there's so much content unrelated to computational design, and the forum software is more suitable for the year 2004 (the more I use it the more I start to get disappointed by it). 

There are the VK and Google+ pages but even that community has very few active contributors. My advice if you want 'how tos' ask here in the issues and we'll tag it as a `how to`. One of us is bound to answer. I think a lot of people are more technical than they think and will accept the subtle renaissance of minimalism that github provides. In the end the only thing most people want is answers to their problem, or the feeling that their problem has been heard and someone has attempted to answer it .

**Comment by portnov** [comment]
Well, personally i'd prefer a traditional forum or maybe even just a mailing list :) But maybe i'm just tooo old-fashioned :)
Sverchok's communities in vk and G+ and BA are split: there are some people here, some people there... It would be good to have one place to gather.

**Comment by yanivg101** [comment]
It's easy to install forum like this: http://www.mybb.com.
we use it on Blender Israel Forum (http://forum.blender.org.il)

**Comment by zeffii** [comment]
hah, it's bit hacky but it's possible to link directly to Lessons , Manual ..etc. There's a same-site redirect and some ugly js code, just to get the effect. If user gh-pages had allowed custom 404 this would be much easier. but whatever. 

I will now continue to tweak CSS and design of the page. (That's what the thread is about)

**Comment by zeffii** [comment]
Nothing to see here just placeholder stuff.
![lorenztest800300t](https://cloud.githubusercontent.com/assets/619340/5768759/405160a8-9d14-11e4-9c2d-ed125d183ac9.png)

**Comment by nortikin** [comment]
site todo:
[ ] - change examples blend zip and jsons up-to-date
[ ] - change images gallery for represent power of Sverchok
[ ] - change lessons, separate videos to page
[ ] - disquis page separately
[ ] - download page with installation instructions
[ ] - donate on all pages on bottom or separate page
[ ] - something more

I will land new site on my site, but we should migrate it to io.
change links in:
[ ] - README
[ ] - nikitron.cc.ua
[ ] - vk.com
[ ] - code
[ ] - g+
[ ] - instagram
[ ] - documentation
[ ] - buttons in properties of addon

also i should keep data in github basically
Any thoughts?
