### ISSUE TITLE
Group nesting bug

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4911]
I have a node group inside a node group, and the input of the inside group viewed (stethoscope) from within the outside group is not the same as the input of the inside group viewed from within the inside group. More specifically, part of the data is lost, i. e. my 4\*2 lists became 2\*1 lists. However, the sockets themselves still display they have a first dimension of 4. So, does the problem come from the stethoscope node or the group itself? Either way, I need to clearly visualize the data to debug the tree.

Thanks for helping me out.

**Comment by Durman** [comment]
Could you add the file and screenshot of the problem?

**Comment by ArpegorPSGH** [comment]
The file is humonguous, so let's start with the screenshots :
![Within outside group](https://github.com/nortikin/sverchok/assets/89776412/7107c257-8f88-4f38-8bce-5511d91ff4ef)
![Within inside group](https://github.com/nortikin/sverchok/assets/89776412/4ba1782e-bfca-40fb-881c-0d89c098a37f)
I noticed that even within the outside group I have to get out of the node group then enter it again so that it gives correct result, otherwise it shows similar behaviour as inside group.

**Comment by Durman** [comment]
It seems I can reproduce

![Bug](https://github.com/nortikin/sverchok/assets/28003269/1b55f826-0a52-4a65-b8c9-cfac51dc5846)

[untitled.zip](https://github.com/nortikin/sverchok/files/11561143/untitled.zip)

**Comment by ArpegorPSGH** [comment]
Yeah, that's exactly that. I can work around this by extracting the content of the group for debugging, then wrapping it in the group again, but that's tedious and messy.

**Comment by Durman** [comment]
When something changed inside a node group we search in which group nodes this group tree is used and mark all those nodes as outdated. It works when node groups are used directly from main trees. But when they are nested in another node groups the update system can't detect outdated places.

https://github.com/nortikin/sverchok/blob/5163f9fca854066d06db1aaab31b439909a27b6c/core/group_update_system.py#L42-L47

To fix this not only group nodes in main trees should be marked as outdated but also group nodes inside subtrees.

**Comment by ArpegorPSGH** [comment]
Yes, it should be a recursive task to work whatever the level of nesting is.
