### ISSUE TITLE
macOS FreeCAD lib path still not working

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4918]
I really want this FreeCAD nodes to work on macOS.

I got the app running from inside Applications. I can see the Python console inside FreeCAD actually working fine.

![Screenshot 2023-06-06 at 1 38 02 pm](https://github.com/nortikin/sverchok/assets/3952687/657aaa73-bbba-4b4a-a081-62a6de62deac)

My Path:
/Applications/FreeCAD.app/Contents/Resources/lib/

Is this the wrong way? Do I actually need to install as Python package outside of this Application? I will search around, but so far, I could not find one straight forward tutorial to install this freecad app as python module without the app itself.

**Comment by luzpaz** [comment]
bump

**Comment by satabol** [comment]
@enzyme69 
>> My Path:
/Applications/FreeCAD.app/Contents/Resources/lib/
Is this the wrong way?

Yes. This is the wrong way. There is instruction about **integration** FreeCAD into the Sverchok: https://github.com/nortikin/sverchok/wiki/FreeCAD
I have FreeCAD version like in instruction and this is working for blender 3.6.1 (Windows 11)

**Comment by luzpaz** [comment]
Cool, this ticket can be closed
