### ISSUE TITLE
Triangulation Node Error

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4919]
Upon trying to triangulate a rather simple mesh, but with some non convex faces, these faces became a mess :
![Problème triangulation1](https://github.com/nortikin/sverchok/assets/89776412/4cff0360-59dc-44d1-86a6-ba97b81db646)
![Problème triangulation2](https://github.com/nortikin/sverchok/assets/89776412/d964fe0c-3729-4d8d-90ba-28198d155a05)
Here is the blend file with the mesh and the node tree :
[Problem triangulation.zip](https://github.com/nortikin/sverchok/files/11680605/Problem.triangulation.zip)
However, the same triangulation works fine with blender native function.

**Comment by Durman** [comment]
Most likely the bug should be reported on Blender tracker. (But in that case it should be done without Sverchok installed, with simple script using the API, demonstrating the problem),

This is what Sverchok is using for performing the operation -
https://github.com/nortikin/sverchok/blob/0b9c092499dba67c7654094bd0971dfa57a578ea/nodes/modifier_change/triangulate.py#L115-L120

**Comment by ArpegorPSGH** [comment]
Ok, I tested the operator with the following script:

import bpy, bmesh

obj = bpy.data.objects['example']
bm = bmesh.new()
bm.from_mesh(obj.data)  
res = bmesh.ops.triangulate(bm, faces=bm.faces)
new_edges = [tuple(v.index for v in edge.verts) for edge in res['edges']]
new_faces = [[v.index for v in face.verts] for face in res['faces']]
res_mesh = bpy.data.meshes.new('res_mesh')
verts = [v.co[:] for v in bm.verts]
res_mesh.from_pydata(verts, new_edges, new_faces)
res_mesh.update()
res_obj = bpy.data.objects.new('result', res_mesh)
bpy.context.collection.objects.link(res_obj)

It turns out it works perfectly fine, so the problem comes from the node :
![Problème triangulation3](https://github.com/nortikin/sverchok/assets/89776412/ad394e1f-a04b-4429-b5fe-243f7f19fbdf)

**Comment by Durman** [comment]
That was something not obvious to me =)
