### ISSUE TITLE
Strange extrude region result 

### ISSUE THREAD

**Issue by ArpegorPSGH** [nortikin/sverchok#4920]
I tried to extrude this polygon with the normals indicated as a list of matrixes, one for each vertex:
![Extrusion problem](https://github.com/nortikin/sverchok/assets/89776412/d49dd0a4-6b84-49a1-960b-fea2edd88a2f)

But I got a strange result, where not all the extruded vertices overlap exactly by pair:
![Extrusion problem2](https://github.com/nortikin/sverchok/assets/89776412/d4f3153a-ef7a-4780-94e8-094e083acf99)

Given my input face and extrusion normals, I should get this perfect overlapping, right? There is also the extruded face which is messed up.

**Comment by Durman** [comment]
Could you attach the file?

**Comment by ArpegorPSGH** [comment]
My bad, in fact, after verification, the two branches of the L aren't exactly the same width, so the behaviour is perfectly normal. 

As for the messed up extruded face, it seems to be a strange quirk, because when I perform the exact same extrusion on another part of my tree, it works fine, and same thing if I perform it in a different tree.
