### ISSUE TITLE
Viewer Draw does not show multicolor dashed lines. Is it bug or feature?

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4946]
Sverchok-master-1.2.0 alpha. Windows 11, Blender 3.6.

If set ON mode "Color per edge" and "Dashed edges" then dashed color set mono:

![image](https://github.com/nortikin/sverchok/assets/14288520/319d0fcd-cf89-467b-8dbd-97542adf2e75)

IMHO the problem is in shaders.

**Comment by zeffii** [comment]
i never tried that, so i think of it as a unimplemented feature rather than a bug. I don't imagine it is that big of a code change to implement this, but without looking and trying that's only a guess.

**Comment by satabol** [comment]
Thank you for explanation. I like use dashed lines. It is useful effect. I try it colorize later.
