### ISSUE TITLE
version 5.9.6 on blender 2.79 search is blank

### ISSUE THREAD

**Issue by rwoods2023** [nortikin/sverchok#4949]
I still use blender 2.79c and sverchok 5.1.1 ... when I install sverchok 5.9.6, the search is blank. I presume everything else works. I use Windows 10 and my PC has no GPU card installed, so I can't use blender 2.80+. Is there anything I can do with blender 2.79c to correct this?

## Steps to reproduce

1. installed version 5.9.6 on blender 2.79b
2. search is blank
3. uninstalled 5.9.6
4. re-installed 5.9.6 via zip, got error

## Expected result

ability to search

## Actual result
search is blank

What did you actually get?

nothing

## Sverchok version
5.9.6 installed in addons folder, and also via zip

**Comment by Durman** [comment]
I guess this is the last release for 2.79 https://github.com/nortikin/sverchok/releases/tag/2.79
