### ISSUE TITLE
The installation doesn't work in Blender 3.61

### ISSUE THREAD

**Issue by lucagal** [nortikin/sverchok#4954]
## Problem statement

Is the problem installation related? then `visit this page first <https://github.com/nortikin/sverchok#troubleshooting-installation-errors>`_.  

For any other issues, or if the installation still failed; Please describe the problem here.

## Steps to reproduce

1. Install latest Sverchok master from blender->preferences
2. in blender, preferences, addon,Sverchok check the small square to activate this addon 
3. 

## Expected result
Sverchok activated

What did you expect to see as a result of those steps?

## Actual result
the activation failed

What did you actually get?
from console:
ImportError: DLL load failed while importing MeshPart: Impossibile trovare la procedura specificata.

## Sverchok version 1.2.0 sverchok master zip from github

This is especially important for installation-related issues. Please specify how do you install Sverchok: from sverchok-master.zip from github, or from release zip file, or from cloned git repo.
I downloaded the latest  sverchok-master.zip, version: (1, 2, 0), from github the day 19 july 2023
[sverchok activation log.txt](https://github.com/nortikin/sverchok/files/12105998/sverchok.activation.log.txt)

**Comment by satabol** [comment]
Is it an update or a clean installation?

**Comment by lucagal** [comment]
Thank you Satabol for your help, anyways it still doesn't work.
I made a clean installation of Blender 3.61 and I tried also the renaming sverchok-master -> sverchok.
In the system console i found this error message:
Modules Installed (sverchok-master) from 'C:\\Users\\Utente\\Downloads\\sverchok
-master-7.zip' into 'C:\\Users\\Utente\\AppData\\Roaming\\Blender Foundation\\Bl
ender\\3.6\\scripts\\addons'
addon not loaded: 'sverchok-master'
cause: cannot import name 'core' from partially initialized module 'sverchok-mas
ter' (most likely due to a circular import) (C:\Users\Utente\AppData\Roaming\Ble
nder Foundation\Blender\3.6\scripts\addons\sverchok-master\__init__.py)
Thank you for any suggestion

**Comment by satabol** [comment]
Do you have old version of blender installed before? For ex. 3.6.0? If so then I advice to rename folder
3.6 to 3.6.00 (do not remove it to restore in the future):
![image](https://github.com/nortikin/sverchok/assets/14288520/d68f3293-7a2c-4443-92f5-b67642410719)
then try to start Blender again and try to install sverchok after it.

Also oneday I got a trouble with starting sverchok with wrong version of freecad library in the system. So If you have installed freecad then try to temporary rename freecad ref in you profile:
![image](https://github.com/nortikin/sverchok/assets/14288520/3e7a89ce-c3ca-4b62-bc89-7d5e750ce002)

**Comment by lucagal** [comment]
Satabol,
thank you very much because by deactivating Freecad finally Sverchok works! At this point I uninstalled my Freecad and installed the latest release following the instructions on this site for dependencies. It would have taken me a long time to trace Freecad's interference, unless I had given up along the way. I work with point clouds and I found Sverchok very useful for reconstructing parts of my 3d scans with minimal surfaces and the like. But now with sverchok extra I have problems with the installation due to sdf, which gives me an error when activating the addon
  File "C:\Users\Utente\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\a
ddons\sverchok-extra-master\nodes\sdf\estimate_bounds.py", line 10, in <module>
    from sverchok_extra.utils.sdf import *
  File "C:\Users\Utente\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\a
ddons\sverchok-extra-master\utils\sdf.py", line 114, in <module>
    ease.linear,
NameError: name 'ease' is not defined

Anyways thank you a lot for your help and any suggestions

**Comment by satabol** [comment]
Glad to help you. I did not ever use Sverchok-extra-master. I have only guess.
In the documentation of Sverchok-extra is description: "**At the moment, Sverchok-Extra does not have any specific dependencies, except for [Sverchok](https://github.com/nortikin/sverchok) and it's dependencies**" So I think not all dependency of Sverchok installed yet. Yesterday I reinstall all library and my Sverchok config has look:

![image](https://github.com/nortikin/sverchok/assets/14288520/26cb7262-3715-4658-8b17-688a21b86166)

If it is not help then you need close this issue (if result of your source question is good) and open another issue for sverchok-extra. Here are developers of sverchok-extra plugin.

**Comment by lucagal** [comment]
Thank you very much for your help, I close this issue
