### ISSUE TITLE
Curve Auto Sample By Length?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#4972]
I am using Curve Spline nodes, and trying to "resample by length" but I could not find SV node that deals with this. 

Like I want to have more evenly sampled curves, regardless long or short.

![Screenshot 2023-08-09 at 9 16 39 am](https://github.com/nortikin/sverchok/assets/3952687/dfa76d00-4e10-495a-beb6-bcd05499a8d7)

![Screenshot 2023-08-09 at 9 20 06 am](https://github.com/nortikin/sverchok/assets/3952687/33d3331b-e336-4bb8-98d7-4c9cdf1e787e)

BLEND
[evenly_sample_001.blend.zip](https://github.com/nortikin/sverchok/files/12296788/evenly_sample_001.blend.zip)

**Comment by enzyme69** [comment]
![Screenshot 2023-08-09 at 9 23 28 am](https://github.com/nortikin/sverchok/assets/3952687/caadd4e0-d509-47ac-9a01-a90e36390675)

Geometry Nodes have this "Length" sampling. I am sure SV has its own version, but could not find the node. 

There is an example by Zeffii under GP+ but, I need a single node for "Length" sampling.

**Comment by enzyme69** [comment]
I was reading this:
https://github.com/nortikin/sverchok/issues/2489

Also realized "Duplicate Along Edge" node is broken?

![Screenshot 2023-08-09 at 9 30 34 am](https://github.com/nortikin/sverchok/assets/3952687/c1598c7b-959d-426a-8c1f-8651102da231)

**Comment by enzyme69** [comment]
![Screenshot 2023-08-09 at 9 33 05 am](https://github.com/nortikin/sverchok/assets/3952687/bd452774-bae6-46d6-bb56-3f84ffd6e316)

UPDATE: Ok duplicate along edge is not broken.

But anyhow, need a "Curve" node that does "sampling by length"

**Comment by satabol** [comment]
@enzyme69 
Hi. About resampling. Do you try change this parameter?
<img width="1194" alt="image" src="https://github.com/nortikin/sverchok/assets/14288520/c296e638-22b7-4baf-992b-eb3dca2d1d36">

**Comment by satabol** [comment]
Hi, @enzyme69 . Sverchok is not geometry nodes. It has more math. Curves is not so simple as them used in Blender. To resample curve by length you can use next algorithm:
![image](https://github.com/nortikin/sverchok/assets/14288520/b2d71cf8-05ad-43f6-a991-1401a858f9b5)
After use "Curves->Naturally Parametrized Curve" you get domain range of curve equals the length of curve. Then you divide Range by length of one segment and get count of samples. I think that algorithm used inside Blender too.

**Comment by enzyme69** [comment]
Thanks @satabol ! I'll try this.
