### ISSUE TITLE
Online document menu do not work

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#4990]
Sverchok 1.3.0-alpha, Blender 3.6.1, windows 11.

If try to use item "Online Manual" in context menu then error message in console shown:

![image](https://github.com/nortikin/sverchok/assets/14288520/08240530-aaac-4e33-a5c2-2626f29df63c)

**Comment by satabol** [comment]
I cannot identify where is it? ))) Do you know?

**Comment by Durman** [comment]
Ah, it's new Blender feature I guess. I don't know why but when you press right click on a node it opens Blender menu and wile it is opened you can press right button again and that will open Sverchok context menu. Ideally we would like to have deal only with our own menu. =)

**Comment by satabol** [comment]
I try find any info about 'rna_manual_reference.py' or 'bpy.utils.manual_map()' and nothing find.

![image](https://github.com/nortikin/sverchok/assets/14288520/35393bc3-9c22-4444-a4ed-2cdf01c7e74b)

https://docs.blender.org/api/current/bpy.utils.html#bpy.utils.manual_map
![image](https://github.com/nortikin/sverchok/assets/14288520/210b6b2c-a59f-4450-84e9-1b2cc6179270)

rna_wiki_reference.py:
![image](https://github.com/nortikin/sverchok/assets/14288520/0ea79bd0-1308-4264-8f1b-3199e790da23)

There is some info about manual_map():
![image](https://github.com/nortikin/sverchok/assets/14288520/183770d8-fcc0-4dd3-b0bb-468968854181)
But I don't know how to extend this list?

**Comment by satabol** [comment]
I found it!
![image](https://github.com/nortikin/sverchok/assets/14288520/9d4e32d2-3d80-4b50-a15d-dde0d87cbf7c)

I try this later.

But there is a property help and no info too:
![image](https://github.com/nortikin/sverchok/assets/14288520/9599944a-35c2-4272-b220-10aa8e6d5a88)
