### ISSUE TITLE
Graph Execution visualization

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#500]
I propose to make a visualizer (probably with d3.js or straight 2d openGL) that shows exactly for each node in the tree 1) when a node is given the command to process and 2) when it finishes. If we have a good visualization to assist the debug timing-prints it could help identify unfavourable execution paths, and even show places where it could be possible to implement parallelism.

something like this:
http://cloudlink.soasta.com/soasta/attachments/soasta/Perf-TestExecutionAndManagement/1469/1/requests_sent_by_browser_chrome.png 

![image](https://cloud.githubusercontent.com/assets/619340/5413166/5db966c4-8214-11e4-9521-0ad1e6a96f04.png)

**Comment by zeffii** [comment]
![ooohtes](https://cloud.githubusercontent.com/assets/619340/6195443/7c092916-b3ce-11e4-999d-b360ea0f29aa.gif)

**Comment by zeffii** [comment]
i'll probably add Node Tree names to the `core.update_system.graphs` output - to allow stacked named graphs

**Comment by zeffii** [comment]
![wasabi](https://cloud.githubusercontent.com/assets/619340/6254508/7c2124f6-b7a9-11e4-8e39-0ecbe91e80d1.gif)

**Comment by zeffii** [comment]
- [ ] math nodes (function, function.001) should probably which operation they perform.
- [ ] node_tree / group name

**Comment by Durman** [comment]
@zeffii Is it possible to use now somehow?

**Comment by zeffii** [comment]
@Durman  i wrote some of this code in a different add-on ( BCP, Blender Console Prompt ) , which lets me type in "times" into the bpy console and hit `ctrl+enter` to execute it.  it generates the json and should spawn a browser.. but it seems to be currently broken somewhere.
