### ISSUE TITLE
Viewer Draw Not Working in blender 4.0

### ISSUE THREAD

**Issue by johntedharvey** [nortikin/sverchok#5071]
The Viewer Draw node does not appear to be working.
Simply connecting any generator node to the viewer draw node does not display any geometry.

**Comment by InProject64** [comment]
Hello! Is there a solution to this problem? Or are we waiting for an update?

**Comment by johntedharvey** [comment]
Hi guys.
Just following up on this issue.
The latest version of Sverchok Viewer Draw node still doesn't seem to be working in Blender 4.1.
Has this been resolved as yet?
regards
John

**Comment by ppaawweeuu** [comment]
Awesome!

**Comment by johntedharvey** [comment]
Fantastic.
Thank you very much.

Kind regards
John Harvey
