### ISSUE TITLE
2015 NY

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#510]
Congradulations!
This year was full of events and much of code was done by Dealga and Linus and others.
You put your soul to Sverchok, it is evident. Some solutions was accepted unic for our programm.
Wish you health, luck, much money and many freands, last is more than money.
I love you, guys.
![rd6mfcz8p04](https://cloud.githubusercontent.com/assets/5783432/5588674/3add06e6-911f-11e4-9772-f8ef12eed1a4.jpg)

**Comment by nortikin** [comment]
```
Everything Nodes

So while we’re on Particle nodes anyway – we should check on having Modifier-Nodes, Constraint-Nodes, Transform-nodes, Generative modeling Nodes, and so on.

And – why not then try to unify it into one system? Here a lot of experimenting and design work is needed still. It’s surprising and inspiring to see how well Python scripters manage to do this (partially) already.

Working on it: Lukas Toenne, Campbell Barton, …
Likely to happen in 2015: Unknown.
```
http://www.blender.org/press/18-anticipated-blender-development-projects-of-2015/

**Comment by zeffii** [comment]
yes! 2015, maybe it will be better than 2014, maybe not.

Particle system nodified would be sweet. even a simple way to dupliObject with a matrix for each dupli would be a fine for a lot of geometry experiments. I hope the devs take some cues from what we've done with Sverchok, the speed up for all that stuff in C/C++ would be pretty great.

**Comment by nortikin** [comment]
It will be great to port sverchok to framework and handle development in C. Will learn C than

**Comment by ly29** [comment]
Hi
 Yes 2014 was fun with Sverchok, I hope 2015 will make more official node workflows possible. I have not had any time for a while, lot of work in lately, and moved to a new apartment and holiday season. Will see how things develop.

**Comment by nortikin** [comment]
new flat is great always. wait to move from hostel one day
