### ISSUE TITLE
The new "Get Objects Data" node broke backward compatibility and usability

### ISSUE THREAD

**Issue by rendetto** [nortikin/sverchok#5105]
With the merge of https://github.com/nortikin/sverchok/pull/5022 the node "Get Objects Data" now outputs vertices and normals in Vector(( )) format. 
This brakes the compatibility with other nodes and also it makes it harder to modify the data further using list nodes.

![GetObjectsData_OutputFormatProblem](https://github.com/nortikin/sverchok/assets/66558924/041bc59a-84a5-44f6-ba33-fe790acfe684)

**Comment by satabol** [comment]
Hi @rendetto Can you give a file for tests? I try an example of grid and do not see any vectors:

**With mesh:**
![image](https://github.com/nortikin/sverchok/assets/14288520/bb88b42b-a01c-47e9-8b32-e1ed119f269c)


**With surface:**
![image](https://github.com/nortikin/sverchok/assets/14288520/36bfa107-8c3f-49cd-81d6-66f6119c3ee1)

**Additionally:**
![image](https://github.com/nortikin/sverchok/assets/14288520/efc9e126-689c-4955-ba8d-8306a43651a6)

**Comment by rendetto** [comment]
Hello @satabol 
Sorry my mistake - I wasn't changed to master after testing where the problem appeared for the first time and the "Get Objects Data" node has older UI.

Here's a screenshot from master and the problem is still present:
![image](https://github.com/nortikin/sverchok/assets/66558924/ad56fc15-0c77-4ceb-9aef-444a46158050)

It appears that it's present when the input object is a mesh and is in edit mode. When the input mesh is in object mode the problem is not present:
![image](https://github.com/nortikin/sverchok/assets/66558924/f4b3840c-e467-48c7-817a-b86d355517dc)

**Comment by satabol** [comment]
I see. I look code and see this feature:

https://github.com/nortikin/sverchok/blob/6db84ff4c0c0f56976d587b8b4b86a779bb9da49/nodes/scene/get_objects_data.py#L408-L414

I don't know why this feature is used but now it is work as expected.

Hi @Durman. Can you explain why this if used?

**Comment by rendetto** [comment]
You mean that it is supposed to output Vector when in edit mode?

**Comment by satabol** [comment]
It is my turn to send you my sorry. I understood all problems now! ))) I need some time to think. Please wait.

**Comment by satabol** [comment]
@rendetto Try this trick for a while: turn on numpy for vertices:

![image](https://github.com/nortikin/sverchok/assets/14288520/cf369cbe-5d30-4e54-b2c7-6dc7f5f3fb7e)

It will work without errors in object or mesh mode now. I continue thinking...

**Comment by satabol** [comment]
Hi @rendetto.
I fix this problem. Can you try update Sverchok and replay your scheme?
See https://github.com/nortikin/sverchok/pull/5108

**Comment by rendetto** [comment]
@satabol now it works as expected. Thank you!
