### ISSUE TITLE
Problem with EvaluateLine node when input factor is a nested list.

### ISSUE THREAD

**Issue by 12edge** [nortikin/sverchok#512]
hi,
The EvaluateLine node works great when there is simple list as the input factor and multiple verticies going into Vertex A & B. But when a nested list is used as the input factor only the first nested list is used as factors for all of the verticies. I was expecting that the first nested list would be used by the first pair of verticies then the second nested list would be used by the second pair of verticies and so on.
A copy of the blend file has been placed https://drive.google.com/open?id=0BwFQiTKfux0qT2NZLU9CREpDOGs&authuser=0

I was hoping to divide up each side of a square with potentially different percentages then add things at those locations.
![problem_evaluateline](https://cloud.githubusercontent.com/assets/9768590/5606147/c68d9d70-93dd-11e4-93dd-7a07b2247703.PNG)

Thanks for the great software.
Forgot to add: Windows 7, Blender 2.72a, SV 0.5.0.8

**Comment by zeffii** [comment]
yeah, not all nodes are Vectorized (configured to understand nested input). I think this is one of the earlier nodes and vectorization wasn't implemented so broadly at the time. You might have to manually stick a list repeat into the two set of vertices so they all have `4.` . 

Unless i'm mistaken this could definitely be added to `Vector Evaluate` and `Vector Interpolation`

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5606272/9390cf56-9427-11e4-98e3-3da7c5f9e054.png)

try this way for now, (i think this is what you wanted to accomplish)
https://www.dropbox.com/s/zq1ocpeih4ezzay/problem_evaluateline_rb.blend?dl=0
i've minimized the new nodes, you can that kind of node and forget about them

**Comment by nortikin** [comment]
@12edge you not correctly understand nature of vertices. why you think it is not polygons, but edges you working with?
No, vertices are not edges and not polygons, it is count of vertices and no more. to use edges, please, follow next. https://yadi.sk/d/kWysvFHfdnPth

**Comment by 12edge** [comment]
Thank you @nortikin because your solution works well. The example you put together not only shows how to correctly use the EvaluateLine but also for extracting the data from the ObjectIn. It is cold here today, -30C, but the solution warms my thoughts.
