### ISSUE TITLE
Get Objects Data node. Add output sockets for Seams and Sharp edges

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#5120]
Sverchok -1.3.0-Alpha

![image](https://github.com/nortikin/sverchok/assets/14288520/416b04ce-5528-434e-aeb8-6e13e8c34143)

Is it convenient to mask edges by this properties?

**Comment by rendetto** [comment]
This looks useful. I wonder, does adding more output sockets affect the node performance?

**Comment by satabol** [comment]
Hi @rendetto 
The code check if output socket is connected. So if it is not connected then no actions performed.

**Comment by satabol** [comment]
I found some interesting things. Some modifiers can share attributes like "select" in result mesh elements:

https://github.com/nortikin/sverchok/assets/14288520/96d661c3-dd86-4acf-934d-b23df241ec07

**Comment by satabol** [comment]
Buttons to show or to hide new sockets.
https://github.com/nortikin/sverchok/assets/14288520/89000e05-5a00-4db1-b71d-63a504f68ff1

You can select what sockets you need and hide other:
https://github.com/nortikin/sverchok/assets/14288520/f593282f-651b-4d74-8c09-bbc929d1961b

**Comment by satabol** [comment]
Example with edges:
![image](https://github.com/nortikin/sverchok/assets/14288520/c2ede390-5a54-4474-ab3c-470f43de60ec)

**Comment by satabol** [comment]
Example of new Interface:

https://github.com/nortikin/sverchok/assets/14288520/48279129-b206-4335-8bcf-41de431a90a3

![image](https://github.com/nortikin/sverchok/assets/14288520/72eaff56-e16d-43f0-816b-3bd56aaee6ae)

**Comment by satabol** [comment]
Example of new Interface:

(Ctrl-Shift-'+')

https://github.com/nortikin/sverchok/assets/14288520/48279129-b206-4335-8bcf-41de431a90a3

![image](https://github.com/nortikin/sverchok/assets/14288520/72eaff56-e16d-43f0-816b-3bd56aaee6ae)
