### ISSUE TITLE
[Need Help] How to create Gyroid mesh?

### ISSUE THREAD

**Issue by kevinsmia1939** [nortikin/sverchok#5130]
Hi,
I want to create a surface with sverchok in Blender. Specifically Gyroid.
https://en.wikipedia.org/wiki/Gyroid

The implicit function of Gyroid can be express in Python as:
np.sin(x) * np.cos(y) + np.sin(y) * np.cos(z) + np.sin(z) * np.cos(x)

But I don't know how to actually implement this in Sverchok.
There are example tutorial with Grasshopper 3D: https://www.youtube.com/watch?v=mhYrVlvbN4k
But since Sverchok is different, I don't know where to write the implicit equation and generate mesh from it.

Thanks for the help.

Blender 4.1.1
Sverchok bgl_replacement latest commit.
OS: openSUSE Tumbleweed

Here is the example Python code to draw Gyroid with Matplotlib and marching cubes.
```
import numpy as np
from skimage import measure
import matplotlib.pyplot as plt

# implicit function
def gyroid(x, y, z):
    return np.sin(x) * np.cos(y) + np.sin(y) * np.cos(z) + np.sin(z) * np.cos(x)

xl = np.linspace(-np.pi, np.pi, 40)
X, Y, Z = np.meshgrid(xl, xl, xl)
F = gyroid(X, Y, Z)

verts, faces, normals, values = measure.marching_cubes(F, 0, spacing=[np.diff(xl)[0]]*3)
verts -= 3

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.plot_trisurf(verts[:, 0], verts[:, 1], faces, verts[:, 2],cmap='jet')
```

![Screenshot_20240602_162747](https://github.com/nortikin/sverchok/assets/11407922/38d31c17-737e-43cb-adb3-19b287671e1c)

**Comment by portnov** [comment]
You can implement such things pretty straightforward with Scalar Field Formula + Marching Cubes:
![Screenshot_20240602_215629](https://github.com/nortikin/sverchok/assets/284644/f86577cd-0ef7-4d3e-8b23-8b846b322ccb)
Note: "Scalar Field Formula" will use numpy by default, so you even don't have to bother about "np.".

**Comment by kevinsmia1939** [comment]
> You can implement such things pretty straightforward with Scalar Field Formula + Marching Cubes: ![Screenshot_20240602_215629](https://private-user-images.githubusercontent.com/284644/335884280-f86577cd-0ef7-4d3e-8b23-8b846b322ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjUwODQsIm5iZiI6MTcxNzM2NDc4NCwicGF0aCI6Ii8yODQ2NDQvMzM1ODg0MjgwLWY4NjU3N2NkLTBlZjctNGQzZS04YjIzLThiODQ2YjMyMmNjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQyMTQ2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODdlY2RhZTYzYWNlYTkwMjg1N2UyZmQ3OTNjZjgyNjBkNDc5YjY0OGExZmMzMDFiM2Y4YjA0ZTZjYzcyNDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Hil46Ln2033MKXVC-_zrC00FdXO9rtzqvHkUHdmkFc) Note: "Scalar Field Formula" will use numpy by default, so you even don't have to bother about "np.".

Thank you so much it work!
Instead of "bounds", it is called box on my node.
