### ISSUE TITLE
Adaptive Edges

### ISSUE THREAD

**Issue by unknownLupo** [nortikin/sverchok#5131]
Is it possible to achieve the same result with a rectangular grid
![image](https://github.com/nortikin/sverchok/assets/144554824/007c15a7-b1ab-4d4b-8d68-6cd3dfb53ffd)
![image](https://github.com/nortikin/sverchok/assets/144554824/bb114775-dc96-4acc-ab37-6124f4c9eb8c)

**Comment by satabol** [comment]
Hi @unknownLupo 
Can you update Sverchok and test new version of node "Adaptive Edges" ?
See new documentation: https://nortikin.github.io/sverchok/docs/nodes/modifier_make/edges_adaptative.html
