### ISSUE TITLE
Error when trying to change fonts in Typography Viewer.

### ISSUE THREAD

**Issue by ken26u** [nortikin/sverchok#5132]
## Problem statement

Error when trying to change fonts in Typography Viewer.

I made a temporary change to the code and it worked, but I'm not sure if that's correct.

self.node = context.node 
↓
self.node = context.active_node

## Steps to reproduce
1. Press the Change Font button in the Typography viewer
![image](https://github.com/nortikin/sverchok/assets/62538469/2fd82174-e66f-4db9-8c08-80b4870c5c55)

## Actual result
An error occurs.

Error: Python: Traceback (most recent call last):
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sverchok-master\nodes\viz\viewer_typography.py", line 118, in invoke
    self.node = context.node
                ^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'node'. Did you mean: 'mode'?

## Sverchok version
Sverchok 1.2.0 
Blender 4.1

**Comment by satabol** [comment]
Hi @ken26u.

Can you update Sverchok and try change font ?

**Comment by ken26u** [comment]
Hi @satabol 

I updated and checked.
it was fixed. Thank you.
