### ISSUE TITLE
Update List Input node (proposal)

### ISSUE THREAD

**Issue by satabol** [nortikin/sverchok#5136]
Sverchok 1.3.0-Alpha

![image](https://github.com/user-attachments/assets/cfc650cb-4dd0-4736-b480-8b0209b0fd28)

A node List Input has next disadvantages:

1. It has limit of List Length parameter (128 for int/floats and 10 for vectors params).
2. After switch mode from Numbers to Vectors then node disconnects from another nodes
3. There are another types and formats of items (Colors, Angles, Power. see https://docs.blender.org/api/current/bpy_types_enum_items/property_subtype_number_array_items.html#rna-enum-property-subtype-number-array-items)

I have several proposals:

1. Append mask column 
2. Append new index column:
3. Append preview result column
![image](https://github.com/user-attachments/assets/6b8e194f-7625-47c2-9629-556b95ab25a0)

4. Append Bool type of data
![image](https://github.com/user-attachments/assets/ac4384f4-4ad4-4250-9d21-cccd160c43b4)

5. Append subtypes to Vector column
![image](https://github.com/user-attachments/assets/23abdef7-0fae-413d-bc62-dae330ae0208)

6. Append Color Types and subtypes
![image](https://github.com/user-attachments/assets/302fca5f-b14a-4250-969c-5cc6c69cf0c6)

**What do you think ?**

**Comment by vicdoval** [comment]
Hi satabol. I find those are great additions except for the mask column/concept that seems a little over-complicated.

**Comment by satabol** [comment]
Hi @vicdoval.
You are right. Sverchok has nodes to work with lists. But some times this mask allow to quickly exclude some elements from list to see effects without add some list nodes. May be add mask input socket?
![image](https://github.com/user-attachments/assets/9a7a2b37-3985-4ce0-8589-2c710d3c043e)
Also I thinking about exchange data with a clipboard. For example copy/paste data from some data editors like Excel or some thing else? 
![image](https://github.com/user-attachments/assets/71e1fa3d-f323-44be-93b9-08aa28239d30)

**Comment by vicdoval** [comment]
Copying from is a great!
Masking this way could be done with two List Input and a mask node. It seems a simple node that can became very big may became too complex but do as you wish

**Comment by satabol** [comment]
>> It seems a simple node that can became very big may became too complex
I see. But I think this method can simplify a node tree at all (and a node tree will use less nodes). Creating mask after any node is harder than connect mask right into the node to affect a result. If node has several output sockets then mask will affect to all output sockets.

**Comment by satabol** [comment]
![image](https://github.com/user-attachments/assets/fd02c98b-9d6a-429e-b16d-009adb322d2f)

**Comment by EmergencyTemporalShift** [comment]
Would it be an option to add the old one back as a lite option? I find the new version a bit bulky if I only need a couple floats, ints, or vectors.

**Comment by satabol** [comment]
Hi @EmergencyTemporalShift 
I can’t promise when, but I’ll think about it. I also feel like the interface should be easier.

**Comment by satabol** [comment]
Hi @EmergencyTemporalShift 
If you’re comfortable, join our Telegram discussion group: https://t.me/sverchok_3d
In this group, you can ask questions in English.
