### ISSUE TITLE
Division by zero in Offset node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#515]
Under some circumstances i have the following exception:

```
  File "/home/portnov/.config/blender/2.72/scripts/addons/sverchok-master/core/update_system.py", line 318, in do_update_general
    node.process()
  File "/home/portnov/.config/blender/2.72/scripts/addons/sverchok-master/nodes/modifier_make/offset.py", line 88, in process
    self.Offset_pols(bme, list_0, offset, radius, nsides, verlen)
  File "/home/portnov/.config/blender/2.72/scripts/addons/sverchok-master/nodes/modifier_make/offset.py", line 143, in Offset_pols
    adj = opp / tan(ang * 0.5)
Node Offset Node had exception float division by zero
```

I can attach blend file if needed...

**Comment by nortikin** [comment]
да, пожалуйста, давай файл

**Comment by portnov** [comment]
http://home.iportnov.ru/files/www/sv-test.blend.gz

Там, по всей видимости, узел Voronoi выдаёт данные в некотором роде "вырожденные". Если покрутить random seed или параметры Plane, то видно, что на большинстве значений исключения нет, оно возникает только иногда. Но анноит.
Некоторые другие узлы у меня тоже такие данные выдавали. Delaunay 2D, в частности.

**Comment by zeffii** [comment]
offset node needs to be updated to work with 2.73, nortikin you want do this i didn't push the fix

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/offset-node-fixing
(note this does *not* fix 'division by zero)

**Comment by zeffii** [comment]
division by zero just means on the line 
```python
adj = opp / tan(ang * 0.5)
```
Of the components of `tan(ang * 0.5)` means this results in 0. This is not a bug really, strictly speaking, of offset node but of input. We could add noise to the denominator if the result of `tan` is zero, but this is an expensive process if you think about how often we need to check if it is 0.

We could build in a safety feature, for the event the seed is being picked at random / through animation, and add some small value to prevent 0 in the denominator.

**Comment by zeffii** [comment]
I propose 
```
adj = opp / (tan(ang * 0.5) or 0.00001)
```

**Comment by zeffii** [comment]
But then if you change the seed a different mathematical problem arrises. When the input is random, the input can be 'meaningless' to a calculation such as
```
Node Offset Node had exception Vector.angle(other): zero length vectors have no valid angle
```
That means the input of random vectors is not guaranteed to produce valid offset-able geometry. Maybe this also can be resolved.

**Comment by zeffii** [comment]
so input like this can happen
```python
# vec1 = <Vector (3.0607, 1.6247, 0.0000)> 
# vec2 = <Vector (0.0000, 0.0000, 0.0000)>
ang = vec1.angle(vec2)
```
Then we would need to also add noises to the vectors and it is not clear that there might be a reasonable value to inject there.

**Comment by zeffii** [comment]
Also this kind of geometry , means some adaptive radii are needed 
![image](https://cloud.githubusercontent.com/assets/619340/5672798/24050f6a-9794-11e4-87fa-f0eda047eb13.png)

**Comment by portnov** [comment]
As far as I understand, the problem arises when some angle in one of polygons is zero. Such polygons are obviously "degenerate" cases, but we need to deal with them somehow; i don't think that raising an exception is good option. Maybe the right way to solve this (in offset node) would be to just leave such polygons unchanged (pass it from input to output as-is)?

**Comment by portnov** [comment]
Or is it the case when some vertices in polygon are in the same point?... Then i'd say we need to internally (in offset mode) run procedure like "remove duplicates" on each polygon, before actual processing...

**Comment by zeffii** [comment]
Definitely an interesting problem.

A short checking routine before processing each polygon would at least give us an option to implement a behaviour suitable for given inputs. I'm sure @nortikin is already thinking of a neat solution

**Comment by zeffii** [comment]
I was working on a similar node, "inset specials" with adjustable inset per polygon and a vector to push/pull per polygon ( https://gist.github.com/zeffii/c97bdc5d9f125f8bd25f )

**Comment by nortikin** [comment]
"preserving intersection" how it called in other tools. Expensive geometry analisys is all i can propose for offset node. calc distances between vertices and angle to deside radius of exact round or do not make radius at all. calc neighbours is most expensive (kdtree?)

**Comment by zeffii** [comment]
sortof gone off topic
