### ISSUE TITLE
nurbs

### ISSUE THREAD

**Issue by ghost** [nortikin/sverchok#52]
Hey guys,

THis is fantastic. Grasshopper and Rhino is very limiting.
I read the blender wiki article and am very impressed.

Does this support the blender nurbs yet ?

DO you have a roadmap.

**Comment by nortikin** [comment]
https://github.com/orbingol/NURBS-Python

**Comment by nortikin** [comment]
https://media.readthedocs.org/pdf/nurbs-python/latest/nurbs-python.pdf

**Comment by nortikin** [comment]
on job have only python34 on windows, cannot look
have to install all again

**Comment by nortikin** [comment]
some error with installation python. donno what todo

**Comment by nortikin** [comment]
reinstalling python with other settings

**Comment by nortikin** [comment]
it can be used as utility inside sverchok without changes, i think.

**Comment by nortikin** [comment]
it can be used as utility inside sverchok without changes, i think.
```python
from utils/nurbs/Surface import Surface as Sf
class SvNurb(Sf):
    ...
```

**Comment by nortikin** [comment]
list of functions we can use from surface (we need most surfaces, not even curves, but we will use all three files)

**Comment by nortikin** [comment]
We need flag to handle if class was evaluated. Once it done, we can work with it

**Comment by nortikin** [comment]
So clean code... i wish to write like that

**Comment by zeffii** [comment]
```python
"""
in UUU s d=3 n=2
out verts v
"""

import sys
import os

origin = "C:\\Users\\zeffi\\Desktop\\GITHUB\\NURBS-Python"
if not origin in sys.path:
    sys.path.append(origin)

import nurbs
from nurbs import Surface as ns

# Create a NURBS surface instance
surf = ns.Surface()

# Set up the NURBS surface
ctrl_pts = os.path.join(origin, "data", "CP_Surface1.txt")
surf.read_ctrlpts(ctrl_pts)
surf.degree_u = UUU  # 3
surf.degree_v = 3
surf.knotvector_u = [0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0]
surf.knotvector_v = [0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 3.0, 3.0, 3.0]

# Calculate surface points
surf.evaluate()
verts = [surf.surfpts]
```
![image](https://cloud.githubusercontent.com/assets/619340/25918557/225cca58-35cc-11e7-9c32-48a95d27c4ca.png)

**Comment by zeffii** [comment]
pitty it's not numpy..

**Comment by nortikin** [comment]
What do you think? @zeffii
Should we use it?

**Comment by zeffii** [comment]
for surfaces it's too slow for interactive use. I think i might lobby ideasman to implement python interface for surfaces.  We could give a flat list of ctrl points and a UV count, and it generates all surface points. Most of the code is there, and it's _faaast_.

**Comment by nortikin** [comment]
we need tangents, normals and evaluation. it is not too much

**Comment by nortikin** [comment]
and to build new nurbs

**Comment by nortikin** [comment]
i'm trying for myself to make branch with it in `utils/nurbs/` but get this:
```bash
  File "<string>", line 6, in <module>
ImportError: No module named 'nurbs'

```

**Comment by enzyme69** [comment]
UV will be nice I think. I can understand why NURBS is so popular.

**Comment by nortikin** [comment]
than we can do the same as we do with interpolation mk2 but + normals + pattern faster (i think) + tangents easier.
i hope that we will get some day boolean for surface projections. i.e. plane + circle nurbs = plane with round hole. But it is metter of triangulation of nurbs, that is next step

**Comment by nortikin** [comment]
http://stackoverflow.com/questions/33240475/python-how-to-convert-spline-defined-by-xy-list-of-point-into-nurb-curve
```
Are you certain that you need NURBS surfaces? As far as I can tell, their primary advantage over b-spline surfaces is that they can precisely model circular arcs. I've worked with airfoils for many years, and arcs aren't something that are particularly useful to me.
```
