### ISSUE TITLE
Online manual CSS has broken tables

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#526]
@nortikin the css for tables in the online manual is broken, when tables have long text it should not have scrollers but fold to the next line

this
![image](https://cloud.githubusercontent.com/assets/619340/5695112/0dbe730a-9991-11e4-946d-14d8bb1c8c98.png)

versus
![image](https://cloud.githubusercontent.com/assets/619340/5695114/29cc512a-9991-11e4-88e3-070671e65263.png)

I'll assume this is a mistake

**Comment by zeffii** [comment]
I think it would be sensible to do the html/css customization (which i like btw, the static position of the side bar is great!)  make this as part of the `make html` sphynx build process. This would save you from hassle of redoing this each time. I'm not familiar with this build process so be confident that I can apply these changes, but it's worth investigating.

**Comment by nortikin** [comment]
will look

**Comment by nortikin** [comment]
think it is not css, but java script, think it calc defises +----+ and make width. Cannot find nothing from css used in final table odd even. need time

**Comment by zeffii** [comment]
did you add `wy-table-responsive` ?

**Comment by nortikin** [comment]
ok, it works, will tune and upload

**Comment by zeffii** [comment]
cool!
