### ISSUE TITLE
'Running Sum' mode for List Math mode

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#528]
Maybe i've gone senile, but I can't seem to find this feature but I recall seeing it. Running sum would be 
```
input = [0,1,2,3,4,5,6,7,8,9]
output = [0,1,3,6,10,15,21,28,36,45]
```

**Comment by enzyme69** [comment]
I think I use zip and a long winding way to do this.

On Tuesday, 13 January 2015, Dealga McArdle <notifications@github.com>
wrote:

> Maybe i've gone senile, but I can't seem to find this feature but I recall
> seeing it. Running sum would be
>
> input = [0,1,2,3,4,5,6,7,8,9]
> output = [0,1,3,6,10,15,21,28,36,45]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nortikin/sverchok/issues/528>.
>


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
yeah? I just wrote a SN for it instead, seems like it should be a mode of ListMath or ListSum

**Comment by ly29** [comment]
Should most definitely exist.

**Comment by zeffii** [comment]
http://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html

**Comment by ly29** [comment]
```python
>>> import itertools
>>> from itertools import accumulate
>>> list(accumulate(range(10)))
[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]

```
https://docs.python.org/3/library/itertools.html#itertools.accumulate

**Comment by ly29** [comment]
Have a look here, don't remember why I didn't enable it at the time...
Test and see.
https://github.com/nortikin/sverchok/blob/master/nodes/list_basic/func.py#L41

**Comment by zeffii** [comment]
Cool. push it whenever!

**Comment by ly29** [comment]
I don't have time to test it, make quick test with removing the two lines of comments and see what happens...

**Comment by stansu** [comment]
i tested accumulate in ListMath node, i found a weird behavior.
if i input a list with an object, it will output a list with 2 objects.

**Comment by zeffii** [comment]
What should the expected behaviour be? No special behaviours are defined.

**Comment by zeffii** [comment]
@stansu, with [[1]] as input, perhaps you might expect [[1]] as output? Collectively we never got around to testing it or defining what the desired behaviour should be.
```
[[1]]  =>  [[1]]
[[1, 2]] => [[1,3]]
[[1, 4], [3, 6]] => [[1, 5], [3, 9]]
```
I don't know what kind or wrapping to expect, perhaps an extra layer?

**Comment by stansu** [comment]
my expect as following ...
[[1]] => [[1]]
 not...
[[1]] => [[1,2]]

**Comment by nortikin** [comment]
just extra breckets, nothing special

**Comment by stansu** [comment]
I don't understand extra brackets mean, you mean [[1]] and [[1,2]] just difference in brackets?
Thank for you guys reply.

**Comment by zeffii** [comment]
When using it with lists of ` len > 1` , then output is correct but is wrapped in an additional set of brackets. ie ` [[1, 2]]`  I would expect ` [[1,3]]`  and not ` [[[1, 3]]]` .
