### ISSUE TITLE
Blender 2015: Everything Nodes !?

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#529]
Just for discussion.
Look at it: http://www.blender.org/press/18-anticipated-blender-development-projects-of-2015/

> Modifier-Nodes, Constraint-Nodes, Transform-nodes, Generative modeling Nodes, and so on.

While for "Everything Nodes" item "likely to happen" is stated as "Unknown", I still think it's better to cooperate with Blender developers who are interested in it (Working on it: Lukas Toenne, Campbell Barton, …). Other way, there are risks - that one work will be done twice by different people, or that Blender node api will be changed in a way which we will not like, or whatever.
Maybe Sverchok should someday become an "official" Blender extension, or maybe we just should let Blender's developers be aware of Sverchok; for example, if node system is going to be changed, we could propose some changes or extensions of its API.

**Comment by ly29** [comment]
Sverchok will probably not be the final system, most certainly not in its current form, they certainly are aware of Sverchok but I think they will take a different approach. Anyway Sverchok is not that big a piece of code, individual nodes are, with a few exceptions, quite small.
Especially if one separate out the mostly common code and thinks ahead a bit a system of similar complexity could be done quite quickly to a large degree. For me Sverchok is at the point where I mostly want to start over and clean up a series of fundamental things but I do not have the time to do it. 
That said already today it is most certainly very useful.

**Comment by portnov** [comment]
You know, i think Blender (and many other projects, especially Gimp) are in that stage of "where I mostly want to start over and clean up a series of fundamental things  but I do not have the time to do it" for a long time :)

Still, i willn't like if someday it will come to "ah, we decided to change approach totally, and implement some parts analogous to Sverchok in Blender core, please put your code to recycle bin and write all your nodes from scratch using that new core" :)

**Comment by zeffii** [comment]
Nodes everything doesn't necessarily mean Blender devs need to turn everything into a node, as long as features are exposed (like particle system / "object-less" duplicate system and mesh building, NURBS) in a way that can be wrapped in Nodes that would already open a lot of possibilities. It would be a mistake to implement the node alone, and not expose the Function to python.

The more C/C++ code we can execute throughout the chain the better, the nodes themselves can still be Python declared 'exchanges / relays'. We can only do so much with python, it is great for working with a limited section of geometry, but as soon as we start needing to process big chunks and pass them around using generics such as List we start to hit speed bumps prematurely.

Ideasman42 suggested passing around data in [`carray`](http://carray.pytables.org/docs/manual/intro.html) which is very similar to a flat `nd.array`.Reading and writing from Python and a wrapped C function should be significantly faster than staying entirely in Python.

**Comment by ly29** [comment]
Exactly, so even if most of the logic can be kept, a lot of Sverchok code will have to be rewritten at some point, no matter if for carray or numpy as we have discussed previously. Or even if just choose to have more explicit data structures.

**Comment by portnov** [comment]
Then maybe we should start rewriting it now, while there is not so much code? Imaging such rewriting after yet another year of active developement, when number of nodes for example will be several times bigger?

**Comment by portnov** [comment]
I think Gimp developers one day made a mistake to stay in state of "well that needs to be rewritten some day, but not today" too long. As a result, they ended up with huge amount of code which used ancient core, so now there are too few developers enthusiastic enough to deal with all that ancient stuff, and too few of them to port all this to new core (Gegl) in a short period of time...

**Comment by zeffii** [comment]
I don't see that happen soon, but I will question ideasman42 to get more information about the vague statements in that press release.

I think we have done cool things with Sverchok and can show which features we need to be executing in lower level languages. like UV connection / Intersect ALL / remove doubles / various math. The bonus is we even have prototype code and can show what it should be doing given specific inputs.

Over the past couple of days i've needed direct output to curves a few times, that will be my next node - it's been on my mind for ages.

**Comment by portnov** [comment]
About porting something to lower-level language for performance reasons — imho, it should be some releatively small part of core code and maybe a few of most complex nodes (like those you mentioned). And this part of code is unlikely to grow quick. Most quickly growing part of code, i beleive, will be higher-level nodes. And imho, while doing any refactorings in core, we should think how to keep amount of changes needed in that nodes as small as possible. Just to not rewrite huge amount of code, if it's possible, even if it's relatively simple code.

**Comment by zeffii** [comment]
After a brief IRC back and forth with ideasman42 I think BF goals are too far away to have meaningful conversations about them. But I think my initial impression may be mistaken and that indeed the geometry nodes won't be integrated with Python. I will keep asking ideasman42 about the mood every now and then :)

**Comment by zeffii** [comment]
I don't see a Sverchok rewrite in the near future, but there are things I would do differently. I just want to be able to use it for a while and taking nodes about stuff that works in ways that seems inconvenient

**Comment by nortikin** [comment]
I have to say, we discussed this from beginning with Alexander Nedovizin, python or C.
But we did not thought went to point we standing now - so large product. Ok, now it is time to rethink.
Problem is i dont know C even breafly. But there are needs in C code anyway

**Comment by portnov** [comment]
http://www.blendernation.com/2015/02/23/animation-nodes-addon/#prettyPhoto

**Comment by portnov** [comment]
https://blender-brussels.github.io/articles/experimental-mesh-generation/

**Comment by nortikin** [comment]
second link is fantastic, thanks Илья.
