### ISSUE TITLE
SvCurvesViewer

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#531]
# Warning, don't use in important Files Yet!

Much code in this is almost identical to BmeshViewer, a minority are similar enough to consider writing them as more generic functions/operators which can be imported and subclassed into both BmeshViewer and SvCurveViewer. Some of it is conceptually deceptively different.

But for experimentation i'm keeping them separated

![image](https://cloud.githubusercontent.com/assets/619340/5737264/237fe494-9bdf-11e4-9e87-1fe444a6a24a.png)

current limitations: 
At the moment it just converts a set of incoming verts+edges to individual segments of a spline. Literally just allowing us to render edges as tubes.

further options could / should include support for:
- updating fixed verts/edges (better for transform only changes)
- multi segment spline lines
- true spline input that accepts sequence of control points / handle, like Simple Spline node

Sending soon to Alpha!

Features I want to add before doing that:

- [x] additional `+ New material button` (beside material selection, a small + ) to generate a new empty material.
- [x] option to join all incoming into one Curve object.  (logistical nightmare, but worth it)
- [x] use existing bpy.data.curves for new objects if `vert+edges==1 and matrices>1` and more==duplicates

**Comment by zeffii** [comment]
development shall take place in https://github.com/nortikin/sverchok/tree/CurveViewer branch

**Comment by zeffii** [comment]
When an object is of type `Curve` (Call this Curve-Object) it can have many `Curves` internally (Call these Curve-Definitions), they are enumerated in the property 'Splines'. If a Curve Object has any loose segments they are actually separate Curve-Definitions.

Unlike when an object is type 'Mesh', when it can only have a reference to one `Mesh` data. This makes auto naming and indexing of the Curves associated with each set of verts+edges different and will require extra book keeping

**Comment by zeffii** [comment]
actually, i'll remove it from Alpha untill I get proper object cleanup working

**Comment by ly29** [comment]
Nice, we should make curve socket soon also. Many of the problems people have comes from treating edges as polylines or curves.

**Comment by zeffii** [comment]
i'm not sure why this won't reuse existing `.data.curves`, it just creates a new curve for every update..

**Comment by zeffii** [comment]
ha, looks fixed now. will keep longform for the time being

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5739948/0bdf4738-9bff-11e4-941d-ebec97d63c9a.png)

**Comment by nortikin** [comment]
))))

**Comment by zeffii** [comment]
OK. added option to Merge, it's a little dirty and slow but quite handy

**Comment by zeffii** [comment]
adding option to use existing curve objects , when vert+edges = 1 and matrices > 1

**Comment by zeffii** [comment]
should adjust curve radius to adhere to be unaffected by the matrix rescale

**Comment by zeffii** [comment]
hmm, that only makes sense if the matrix scales uniformly, else the curve object radius is also scaled non-uniform

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5840194/f51c3a0c-a193-11e4-9633-2ca64f773d56.png)

**Comment by zeffii** [comment]
added the node in Alpha for broader testing and feature spotting

**Comment by zeffii** [comment]
This is all I want to do for now on svCurvesViewer Node, it is really only intended for rendering edges as   tubes. Tragically the code is sufficiently different for each mode to warrant separate functions which look very similar on the surface, but are different in deceptive ways. Also it's easier to debug if the code isn't tangled up trying to save lines of code.

**Comment by zeffii** [comment]
Curves viewer has a slight bug with switching to duplicate / unique mode, in duplicate mode the node should never using any meshes beyond `name_0` as it is intended to assume that all mesh geometry are identical. There exists some sequence of user input that will bypass this assumption and generate unique geometry (or not refresh to duplicate geometry) when the user presses duplicate.

Confused? I'll fix soon.
