### ISSUE TITLE
Vertices sort based on Edge Keys

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#534]
4 years ago I [wrote a routine](
http://blenderscripting.blogspot.nl/2011/07/sorting-edge-keys-part-ii.html) that sorts the topology of a given set of vertices + edges. The limitations of the algorithm are: 

- 1) the sequence must be non-closed, 
- 2) it must not already be correctly sorted
- 3) the sequence must be not be segmented by interruptions.

Today I needed to import a set of vertices using Objects-in and place points along the edges at a given interval. The geometry is twisty and irregular, but more importantly the vertices+edges are not sorted sequentially, and that's what Vector interpolation needs to do its business.

![image](https://cloud.githubusercontent.com/assets/619340/5750058/73e9fc6a-9c4f-11e4-85ad-55164b3d44f8.png)

Normally when we construct geometry computationally we know that it will conform to a sequential form, but when importing into Sverchok we may want to offer an reorder scheme, not just for non-looping sequences, but for looping ones too. I'll implement the 4 year old one, but probably a fresh rewrite in the hope that i've progressed a bit since then :)

**Comment by portnov** [comment]
Support for closed forms in Vector Interpolate would be nice anyway. In the simplest case, imagine applying it to output of NGon node (or Circle with points = 3 or 5).

**Comment by zeffii** [comment]
Yeah, agreed. Extra sorting will still be needed for that to work, it might as well be a module so it can be imported into Nodes as a helper, and be available as a dedicated sorting Node.

**Comment by zeffii** [comment]
thinking out loud aboit the specs and functions here
```
try_ordering_inputverts, edges):
  # finds if the set is looped, or single interruption
  # returns verts, edges if can order the set, else returns False
```

**Comment by ly29** [comment]
My attempt at the same thing.
https://github.com/nortikin/sverchok/blob/master/node_scripts/templates/ly/topo_get_edge.py

Want we actually want are curves, the limitations of meshes are annoying.

**Comment by ly29** [comment]
The interpolation node should give tangents and support cyclic interpolation.

**Comment by zeffii** [comment]
> /topo_get_edge.py
yes I remember now.

@ly29 you literally mean bpy.data.curves as a base of a socket?

**Comment by ly29** [comment]
No, but making our own simple curves. It would be nice with bmesh variant for curves of course. 
Polylines, line and cubic spline , bezier would take us a long way.

**Comment by zeffii** [comment]
that code works fine for my tests @ly29 
![image](https://cloud.githubusercontent.com/assets/619340/5761985/5baa588a-9cdf-11e4-8a10-885262816f80.png)

**Comment by ly29** [comment]
it is easy to break out the contents of the for loop as a function, if could do with some cleanup however. for fun give it sphere or something, it will return one edge but randomish due to using dict for lookup.

**Comment by zeffii** [comment]
That's sometimes the problem with finalizing these `effector` routines as nodes, instead of a script node, one tends to loose the facility to get in there and mess things up and have unique behaviours. whic can be a royal pain to code a ui for, but easy enough to 'hot wire' through code.

**Comment by ly29** [comment]
this is a case where we should have a template to mess with and a standard behavior.
but a lot works better now that exceptions are handled in a sane way

**Comment by zeffii** [comment]
OK, if we really need this as a node, the code is pretty much there. Closing for now

**Comment by portnov** [comment]
So, is it available as script node or what?

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/534#issuecomment-70082252 yeah

**Comment by portnov** [comment]
ok, thanks.

**Comment by ly29** [comment]
If somebody wants to pack it up as node feel free to do it. Even a recode could be fun.
