### ISSUE TITLE
[node script MK1] Simple polygon subdiv

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#538]
![image](https://cloud.githubusercontent.com/assets/619340/5800394/27024924-9fde-11e4-95f6-44ee8386c99a.png)

At this point the templates folder is starting to grow to the size where I want to make a separate repository for it and a `gh-page` dedicated to just SN MK1 / MK2 templates.

usage: 
- scheme can be integers separated by comma or dash  `,-`.  This way: `1-2-1`, or `1,4,1`, ...`1,6,3` 
- iterations, ls limited to 1..5
- no polygon index output yet

![image](https://cloud.githubusercontent.com/assets/619340/5800576/b5228b7c-9fe0-11e4-869b-fa2885c3f64d.png)

**Comment by zeffii** [comment]
here a version with polygons: 
![image](https://cloud.githubusercontent.com/assets/619340/5800805/85e7badc-9fe3-11e4-9c11-047590831de8.png)
https://gist.github.com/zeffii/9b1c06a4862616151b5a

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5800881/b0b05228-9fe4-11e4-8d33-06de1bea7ecf.png)

**Comment by zeffii** [comment]
cool, I found a bug :)

**Comment by nortikin** [comment]
wery well
