### ISSUE TITLE
BMeshViewer MK2

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#541]
Features I want to implement in BMeshViewer MK2

- [x] new material button (not just select)
- [x] added layer options, only 1 layer (not multi layer, yet)
- [x] objects now have two ID-Properties each `idx` and `madeby`.
    - this is intended to help with cleanup.
- [x] rewrite `hide-view / lock select / renderable` operator. 
- [x] add option to _merge_ geometry into one object before sending to bmesh
    - [x] merge will delete current object duplicates

optional Experimental branch: 

- add zfill to obj names to help with sorting, make zfill default at 4, `0001`
- consider a different naming scheme 
    - `Objname<int>_Dup<zfill, int>` , something like `Alpha_Dup0000`,`'Alpha_Dup0001`

**Comment by yanivg101** [comment]
I want to add too for this:
when I'm using Sverchok as a pipeline to change several models that is on different layers, I usually need to search for the output of the BMesh node and change the name of it so the new mesh will be at the same layer as the input mesh and to ensure that the output mesh of the previous input mesh will stay with the same name without update (of the new mesh input).
Is there any way that I can make this process more intuitive and predictable?

**Comment by zeffii** [comment]
@yanivg101 
I'm not sure I understand. If my response doesn't help or answer, please elaborate

**thought 1**
- It is possible to select all objects generated by a viewer by pressing the `Select/Deselect` button. 
- Then press the M key with the mouse in 3d view, 
- then pick the Layer you want to move it to. 

However, new updated objects will probably still be generated on layer 0 (or 1..if you count from 1 ). In that event it might be convenient to have an option to select which layer A viewer generates objects on. This can be done, i'm OK with adding, if that would help. It would probably be an option in the N-Panel (external button, like random name)

**Comment by yanivg101** [comment]
Yes, It will solve the most of the problem.

**Comment by zeffii** [comment]
some memory jog
```python
obj = bpy.context.active_object
obj['origin_node'] = 'BMesh_0'
obj['idx'] = 0

obj.get('origin_node')
obj.get('idx')

obj.layers[0]
>>> True
```

**Comment by zeffii** [comment]
hmmm, ID property only settable / makeable if the object is 'active', not strictly through obj reference? weird.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/5855910/d4fa6546-a23d-11e4-803d-98e7b7307782.png)

**Comment by zeffii** [comment]
added mesh merging, super untested :) but generator madness :)

**Comment by zeffii** [comment]
I think my matrix is flipped or something (for merged geometry) will test later

**Comment by zeffii** [comment]
I was contemplating a different method to fill the merged mesh. and perhaps speed testing the alternative. It would be a `foreach_set` based but it would be necessary to do
```python
foreach_set( all vertices ) 

foreach_set( all faces, index adjusted ) 

# all edges index adjusted, and checked against all faces, to avoid illegal doubles
foreach_set( all edges ) 
```

**Comment by zeffii** [comment]
maybe by the end of the day I will do a pull request for this, and put the existing BmeshViewer in the old_nodes folder etc. Would appreciate some testing but I haven't managed to break it.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6019550/087976a6-aba2-11e4-9198-079522601598.png)

**Comment by zeffii** [comment]
I think at some point `self.activate` was removed from the check in `process()` , should really but that back or it will always generate geometry

**Comment by zeffii** [comment]
bmesh viewer 2 is usable now. I moved some shared functions that MK1, MK2, CurvesViewer use into a separate `sv_viewer_utils` module. All of this naming stuff is slightly complex.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6096457/9eb2b7fc-af91-11e4-9677-5d9512347ddb.png)

I've wanted to change the icon for update/activate for a while. It seemed using the eye icon twice for different purposes on the same node is a little user unfriendly
