### ISSUE TITLE
FreeCAD export / client node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#561]
not sure what this might look like, but it could be cool to have something like a BmeshViewer or ViewerDraw that sends commands or geometry to FreeCAD..

**Comment by nortikin** [comment]
yes, but if only i use freecad...
need to try it, every time stuck on first steps, cannot understand how freecad works

**Comment by zeffii** [comment]
Looking at PythonOCC, it seems really interesting too! 
http://www.pythonocc.org/
Perhaps even allow us to implement a NURBS viewer (but might be with external window..could be interesting)
