### ISSUE TITLE
Apply matrices to vertices, edges and faces

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#563]
This corresponds to nortikin#517, No.6. Options:

* to create "Mk2" version of Matrix Apply node, which would not only apply matrices to vertices, but also repeat edges and faces from input to output, so in case of several matrices whole meshes would be duplicated, not only vertices.
* To create "Mk2" of Mesh Join node, which would automatically repeat input edges and faces.

These options are compatible though, i.e. we can have both.

I started implementation of Option1 for now, as it seems simpler for use.

![1](https://cloud.githubusercontent.com/assets/284644/6096652/ac13659e-afbf-11e4-83c9-e13b75c0e346.png)

The code is in apply_and_join branch in my repo.

refs portnov#9

**Comment by nortikin** [comment]
but we have allready this node
apply matrix

**Comment by zeffii** [comment]
Matrix Apply should have optional duplication, not implicit. Because often Matrix Apply will be a final node, and it is more efficient to let the Viewer obtain the edges on the fly, than prefetch.

**Comment by zeffii** [comment]
But i suspect there will be no extra processing per socket, unless something is connected right?

**Comment by portnov** [comment]
@zeffii if edges and/or faces input is not connected, then this input works like Matrix Apply.

**Comment by zeffii** [comment]
yes, cool!

**Comment by portnov** [comment]
![2](https://cloud.githubusercontent.com/assets/284644/6096654/b300fbfa-afbf-11e4-901b-1361a44238c2.png)

**Comment by zeffii** [comment]
Somewhere in the docs for this node, we should mention (due to this change), that unless there is further processing going on which explicitly require the duplicated topology, that letting the _viewer draw_ or _bmesh viewer_ nodes auto repeat the index lists of the topology is slightly more efficient.

**Comment by portnov** [comment]
Ok.

**Comment by nortikin** [comment]
like this one. Why i did not that at beginning? maybe i'm too lazy

**Comment by portnov** [comment]
Closing since this is implemented and merged.
