### ISSUE TITLE
Exodus 3 : Nominate Beta nodes to migrate

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#565]
Already the 3rd time we're doing this! Sometimes development goes fast and perhaps we want to avoid committing these nodes to a more permanent place - but the list is getting long.  Quite a lof of these new nodes (thanks @portnov ) do have docs and should not linger much longer in the Beta Category. 

```python
    node_cats["Beta Nodes"] = [
        # for testing convenience, and while no documentation
        ### ['SvPipeNode',          'Pipe'],
        ['SvBevelNode',         "Bevel"],
        ["SvOffsetNode",        "Offset"],
        ### ["SvExtrudeSeparateNode", "Extrude Separate Faces"],     
        ["SvListDecomposeNode", "List Decompose"],
        ### ["SvWafelNode",         "Wafel"],
        ["SvFormulaShapeNode",  "Formula shape", "IPO"],
        ["SvScriptNodeMK2",     "Script 2"],
        ### ["VectorPolarInNode", "Vector polar input"],                  
        ### ["VectorPolarOutNode", "Vector polar output"],              
        ### ["GetNormalsNode", "Calculate normals"],
        ["SvMeshFilterNode", "Mesh filter"],
        ### ["SvGenFibonacci", "Fibonacci sequence"],
        ### ["SvGenExponential", "Exponential sequence"],
        ### ['SvNGonNode',    'NGon',     'RNDCURVE'],
        ['SvBmeshViewerNodeMK2', 'BMeshView2'],
        ['SvBricksNode', 'Bricks grid'],
        ### ["SvRandomizeVerticesNode", "Randomize input vertices"],
        ### ["SvDuplicateAlongEdgeNode", "Duplicate objects along edge"],
        ["SvIterateNode", "Iterate matrix transformation"],
    ]
```
I've commented the nodes that I think can be moved to their final destination. Objections? or confirmation that other nodes are solid enough?

**Comment by nortikin** [comment]
move pipe to modifiers make

**Comment by nortikin** [comment]
also waffel

**Comment by zeffii** [comment]
cool

**Comment by zeffii** [comment]
I propose that new future beta documentation be placed directly in the final docs/nodes/ folder, adding that the node can be found in beta menu and that the node is somewhat untested/beta (something to this effect). It probably makes sense to already classify the node from the start.. (not just that it's less work for pushes like these)

**Comment by zeffii** [comment]
these are now moved
