### ISSUE TITLE
[node script MK1] Simple javascript execution

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#568]
requires: https://pypi.python.org/pypi/PyExecJS

![image](https://cloud.githubusercontent.com/assets/619340/6199801/29420bd0-b45a-11e4-822e-eae6a5c268dc.png)
```js
function gen_verts(r1, r2, num_verts){
    var tv = [];
    var edges = [];
    
    // # verts
    for (var i=0; i<num_verts; i+=1){
        var theta = i/num_verts * 2 * Math.PI;
        tv.push([Math.sin(theta)*r1, Math.cos(theta)*r2, 0.0])
    }
    
    // # edges
    for (var i=0; i<(num_verts-1); i+=1){
        edges.push([i, i+1])
    }
    edges.push([num_verts-1, 0])
    return [tv, edges]
}
```
and
```python
import bpy
import execjs

def recall(r1, r2, nv):
    local_file = bpy.data.texts['daft.js'].as_string()
    ctx = execjs.compile(local_file)
    v, e = ctx.call("gen_verts", r1, r2, nv)
    return v, e
    

def sv_main(radius1=0.3, radius2=0.4, num_verts=10):
    verts_out = []
    edges_out = []

    in_sockets = [
        ['s', 'radius1', radius1],
        ['s', 'radius2', radius2],
        ['s', 'num_verts', num_verts]
    ]

    out_sockets = [
        ['v', 'verts', [verts_out]],
        ['s', 'edges', [edges_out]],
    ]

    js_out = recall(radius1, radius2, num_verts)
    verts_out.extend(js_out[0])
    edges_out.extend(js_out[1])    

    return in_sockets, out_sockets
```
it's not optimal to compile the function on each call, so perhaps this needs a dedicated SN mode.

**Comment by zeffii** [comment]
https://gist.github.com/anonymous/84abc6db5ca3848d4539

**Comment by portnov** [comment]
@zeffii, do you have a link or instruction about how to install third-party python modules into blender? i'm interested in scipy, for example.

**Comment by zeffii** [comment]
@portnov I use my local python 3.4 install, (it means renaming or deleting the Blender supplied python folder. ( blender\2.73\python ) . Blender will then look on your system for a 3.4.

**Comment by zeffii** [comment]
here a version which compiles the javascript once, then calls the compiled function only
https://gist.github.com/anonymous/0032d78dbd0064a52c3b
