### ISSUE TITLE
Prototype JS node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#570]
in https://github.com/nortikin/sverchok/tree/js_prototype_node

Similar to the existing Script Nodes but using execjs. ExecJS will look in the most common places on your machine to find installed JS runtimes. On my machine it finds Node.JS and thus can execute javascript via the v8 engine. (Probably coffeescript too, it would mean a one-off trans-compile between coffee to js)

I want to see if it's possible to get nice fast code execution with v8 / js by having a precompile step. The exact format of the js file isn't decided yet, but it could potentially look something like:

```js
function inputs(){
    return [
        ['a', {min: 1.0, max: 100.0, default: 5.0, step: 0.1}],
        ['b', {default: 14}],
        ['c', {default: 0.7}]
    ];
}

function outputs(){
    return [['verts', 'v'], ['edges', 's']];
}

function sv_proto_main(a, b, c){
    var verts = [],
        edges = [],
        coordinate,
        theta;
        
    for (var j=0; j<b; j+=1){
        theta = j/b * 2 * Math.PI;
        coordinate = [Math.sin(theta)*c, Math.cos(theta)*c, 0]
        verts.push(coordinate)
    }
        
    return [[verts], edges];
}

```

**Comment by portnov** [comment]
Here I have two questions.
1. What are advantages of using JS for script nodes, comparing to python?
2. What is our policy regarding nodes that require some 3rd-party python modules? Are we going to include them in standard sverchok distribution? Then do we need to somehow catch ImportErrors or whatever? Or maybe we should put such nodes into separate distribution, smth like sverchok-contrib?

**Comment by zeffii** [comment]
I like JS / coffeescript - for me this wins any practical advantage, and want to speed test comparable code.

Checks will need to exist for the availability of modules. So yeah, catch import errors.. Not a fan of separate distribution for what might turn out to be only a small amount of nodes that would be eligible. However, having an _externals_ or _contrib_ directory inside Sverchok for nodes which use more than bpy and numpy seems like a sensible idea. Maybe it will make more sense if the number of nodes grows.

**Comment by zeffii** [comment]
I don't think we have a formal policy regarding 3rd-party modules. If the module is publicly available, I don't see a problem with including a link and perhaps brief install instructions in the docs / source.

**Comment by ly29** [comment]
I think a reasonable strategy is that it should work with default blender, however optional modules could be provided. 
Already today such module is place, @AgustinJB created module is included that isn't used by anybody except him I guess. https://github.com/nortikin/sverchok/blob/master/utils/sv_draw_svg_node.py

**Comment by ly29** [comment]
It was part of the documentation effort, now I remember.

**Comment by zeffii** [comment]
we could offer a canonical way to check for non standard modules, and include info about the module to inform potential users
```python
import importlib

# necessary for import checking
if importlib.find_loader('execjs'):
    import execjs
    print('execjs will be available')
else:
    print('execjs will not be available, prototype node will not function.')
    print('obtain execjs from: https://github.com/doloopwhile/PyExecJS')

```
something like this.. I think this works OK and will print the `else` part if execjs isn't found, for me it prints
```
execjs will be available
```

**Comment by zeffii** [comment]
There's so much code out there waiting to be abused by sverchok..

**Comment by zeffii** [comment]
on reflection I will make this a SN MK1 mode instead (non breaking..)
