### ISSUE TITLE
Matrix output of "Iterate" node

### ISSUE THREAD

**Issue by elfnor** [nortikin/sverchok#571]
The new "Iterate" or "Iterate matrix transform" node would be more consistent with other nodes such as "Matrix Interpolation" if it only had a Matrix and number of iterations as inputs and  a list of powers of the input matrix as ouput. It would also, I think, calculate faster.

I quickly wrote up a "Scripted Node" to show this. Sorry I havn't looked at writing full nodes yet.
```
from mathutils import Matrix
from sverchok.data_structure import Matrix_listing


id_matrix = [[[1.0, 0.0, 0.0, 0.0],
             [0.0, 1.0, 0.0, 0.0],
             [0.0, 0.0, 1.0, 0.0],
             [0.0, 0.0, 0.0, 1.0]]]

def sv_main(mat1=id_matrix, pows = 1):

    in_sockets = [
        ['m', 'Matrix',  mat1],
        ['s', 'powers', pows]
    ]
    
    mat_in = Matrix(mat1[0])
    result = Matrix(id_matrix[0])
        
    mat_list = []
    mat_list.append(result)
            
    for i in range(pows):
        result = result * mat_in
        mat_list.append(result)   
    
    mat_out =  Matrix_listing(mat_list)
    
    out_sockets = [
        ['m', 'Mat out', mat_out]
    ]

    return in_sockets, out_sockets
```
![pyramid_matrix_power_node blend](https://cloud.githubusercontent.com/assets/7930130/6224742/dae4838a-b6e5-11e4-812f-32ee4b993bbd.png)

It produces the same output (as separate objects) as this:
![pyramid_interpolate_iterate_04 blend](https://cloud.githubusercontent.com/assets/7930130/6224766/4a240c3e-b6e6-11e4-85df-8a20da9de24e.png)

**Comment by portnov** [comment]
Agreed.
@zeffii , does addition of new output at this stage need some magic in upgrade_nodes.py?

**Comment by zeffii** [comment]
@portnov  The upgrade_nodes mechanism -- @ly29 correct if wrong -- only deals with renaming properties/sockets (so unchanged socket counts).

New sockets might be OK, but don't be surprised if old .blends fail. or don't load at all. Especially if the new sockets is between existing sockets.. like 
```
inputs = [old, old]
inputs = [old, new, old]
```
If the change is substantial it may be worth going to a MK2 straight away.

**Comment by zeffii** [comment]
@portnov because it's still listed as _Beta_ I would encourage you to just make the change. Using beta nodes means users accept that there may be breaking changes.

**Comment by ly29** [comment]
@zeffii 
You can list additional sockets that will be added if they are not already present on loading of a .blend.

I really would like a parse able data structure instead of sv_init/init which is a function that mostly defines something that could be a list, things are would be useful if could be inspected.
Oh well.

**Comment by portnov** [comment]
![4](https://cloud.githubusercontent.com/assets/284644/6249157/241a50c2-b7a7-11e4-9937-adb096f1d694.png)

**Comment by zeffii** [comment]
looks a bit weird that the output matrix is `1`, is it nested one time too many?

**Comment by portnov** [comment]
I think so. Will fix.

**Comment by zeffii** [comment]
This exposes an interesting bug in the ViewerDrawMK2  , baking the node even with simple input like :

![image](https://cloud.githubusercontent.com/assets/619340/6271652/6632659c-b862-11e4-8462-d4a0a4ae5b46.png)

produces results which while amusing, are not good...

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6271719/f9f60702-b862-11e4-92e9-0c3ce840320c.png)

**Comment by zeffii** [comment]
we've already seen something like this before, possibly ViewerDraw should sanitize the values which tend towards 0. There's been some reshuffling of the geometry module in 2.7x which I think may affect Vector and Matrix directly.

**Comment by portnov** [comment]
@elfnor , please test - matrices output is implemented in master.

**Comment by elfnor** [comment]
I've tested the new version and works for all my examples. Thanks for the quick response. Will now  update my Simple Sverchok post.
