### ISSUE TITLE
Triangulation node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#577]
See http://www.blender.org/api/blender_python_api_2_72_1/bmesh.ops.html#bmesh.ops.triangulate
Useful when some node generates ngons, especially non-convex ones.

**Comment by portnov** [comment]
![2](https://cloud.githubusercontent.com/assets/284644/6314914/4f821eb2-ba12-11e4-91c6-ea464efdfea5.png)
![1](https://cloud.githubusercontent.com/assets/284644/6314915/4fb6a9c0-ba12-11e4-9600-4d08a5d67f86.png)

**Comment by nortikin** [comment]
needed long time, thanks
