### ISSUE TITLE
Normalize normals node

### ISSUE THREAD

**Issue by portnov** [nortikin/sverchok#578]
Usual blender's Ctrl-N & Ctrl-Shift-N
See http://www.blender.org/api/blender_python_api_2_72_1/bmesh.ops.html#bmesh.ops.recalc_face_normals

**Comment by zeffii** [comment]
yeah recalc normals could be handy, triangulate too - both welcome additions I think.

**Comment by portnov** [comment]
![invert_normals](https://cloud.githubusercontent.com/assets/284644/6315650/6e5f9d88-ba2a-11e4-84db-624d670ee04d.png)

**Comment by nortikin** [comment]
Ыыыы!
