### ISSUE TITLE
Viewer Typography

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#581]
it's about time for native Sverchok support of renderable Text.

![image](https://cloud.githubusercontent.com/assets/619340/6315629/11fada66-ba08-11e4-813e-54280c873f52.png)

can't be dealing with a ScriptNode any longer for this :)

**Comment by zeffii** [comment]
maybe tonight or tomorrow I will implement a `ViewerTypograpy_PRE.py`

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6318103/ab4f14c2-ba7e-11e4-96fb-7f3f75cff5b8.png)

**Comment by zeffii** [comment]
`draw_ext` should probably have most of the font options..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6318292/8041d718-ba8a-11e4-85df-c894af233e20.png)

**Comment by zeffii** [comment]
a small SN
```
def sv_main(radius=0.3):
    strings_out = []

    in_sockets = [
        ['s', 'radius', radius]
    ]

    t = bpy.data.texts['barb.text']
    st = t.as_string()
    print(repr(st))
    stp = st.split('\n\n')
    
    strings_out.append(stp)

    out_sockets = [
        ['s', 'strings', strings_out]
    ]

    return in_sockets, out_sockets

```
will read the text block and return paragraphs as list items (

**Comment by zeffii** [comment]
todo, add spacing `word / line / letter`

**Comment by zeffii** [comment]
![mook](https://cloud.githubusercontent.com/assets/619340/6327670/e0d204f2-bb5e-11e4-80c8-6febaaab1a63.gif)

**Comment by nortikin** [comment]
like this, making life easyer sometimes

**Comment by zeffii** [comment]
i've seen @enzyme69 struggle in his videos with this..

![image](https://cloud.githubusercontent.com/assets/619340/21980906/45e0716e-dbe5-11e6-96ce-0b4326e946bd.png)

**Comment by zeffii** [comment]
i strongly recommend using debug_print node and reading the console, as a backup. i think stethoscope is misleading you sometimes when it's displaying data in the abbreviated for ( using `... ... ...` in the middle )

**Comment by enzyme69** [comment]
Gotcha! Thanks!
