### ISSUE TITLE
Auto-update after object geometry or mesh changed

### ISSUE THREAD

**Issue by snovvfall** [nortikin/sverchok#592]
This article
http://blendersushi.blogspot.ru/2014/06/sverchok-parametric-snippets-4.html
contains an image
![sverchok_lofting](https://cloud.githubusercontent.com/assets/2778154/6612271/c9fe4d94-c8ab-11e4-8e71-491ff68a6a20.gif)
where I see the author editing the mesh or bezier curve and Sverchok Viewer Draw updates automatically in 3D view without pressing update button each time.
Is it already possible in Sverchok and how? Or at least how to do the thing so Sverchok will update after I switch from Blender edit mode to object mode. So I don't have to click Update button or Get selection button on "Object in" node to see updated result.

**Comment by Kosvor** [comment]
Turn animation slider ON.

**Comment by zeffii** [comment]
we didn't add a modal operator to poll for changes every (small time unit) here, this means you need to have the timeline playing too. (Alt-A)

**Comment by snovvfall** [comment]
Animation is not the case here. I meant only static objects, editing them and seeing Sverchok changes on the go. Or do I need to implement animation somehow to make "auto-update" working even for only 1 frame?

**Comment by zeffii** [comment]
We tend to use sverchok more in the generative sense, which out much interaction in the 3d view -- it is for this reason that we don't have super convenient modes for Sverchok to _live_ update_ . But if you do want to see object-in update itself live while you modify vertices manually, you have to just hit Alt-A so the timeline moves, and blender can respond to the frame change event handler which is then triggered as many times per second as possible up to the frame-rate. 

Even if you don't have any animated stuff in your scene, this is how it works. try it.

**Comment by snovvfall** [comment]
Thank you, now I understand the situation and made it working. But on a bigger project this animation workaround is slow as hell and FPS goes "below the sea level". Maybe this happens because Sverchok calculates everything in the tree each frame instead of one object I change.

**Comment by zeffii** [comment]
Without discrimination it will update everything during frame change. Team Sverchok has superficially discussed this issue several times. It could be worth a quick experiment, it's been something i've been contemplating for a while, and I've got ideas and written very similar code.

perhaps lateron today, or over the weekend.

In a bigger project you might use multiple layouts, remember to press F symbol so they get a fake user (else they can disappear when saving). The benefit of multiple layouts is that they are disjoint from the other layouts if they need to be, so wont be updating if they animation icon is off.

**Comment by zeffii** [comment]
just to give this some context..  I think the Objects In node needs an operator either directly on the UI or in buttons_external (side panel)

```
class FlowOscServerOps(bpy.types.Operator, object):

    """Operator which runs its self from a timer"""
    bl_idname = "wm.flow_osc_server"
    bl_label = "start n stop osc server"

    _timer = None
    mode = StringProperty(default='')
    node_name = StringProperty(default='')
    node_group = StringProperty(default='')
    speed = FloatProperty()

    def modal(self, context, event):
        if self.node_group and self.node_name:
            ng = bpy.data.node_groups.get(self.node_group)
            n = ng.nodes[self.node_name]
        else:
            return {'PASS_THROUGH'}

        if not (event.type == 'TIMER'):
            return {'PASS_THROUGH'}

        if not n.active:
            self.cancel(context)
            return {'FINISHED'}

        self.process(ng, n)
        return {'PASS_THROUGH'}

    def process(self, ng, n):
        ''' reaches here only if event is TIMER and n.active '''
        trigger_event()  # this would trigger the update beginning from object_in node

    def event_dispatcher(self, context, type_op):
        if type_op == 'start':
            context.node.active = True
            wm = context.window_manager
            self._timer = wm.event_timer_add(self.speed, context.window)
            wm.modal_handler_add(self)

        if type_op == 'end':
            context.node.active = False

    def execute(self, context):
        n = context.node
        self.node_name = context.node.name
        self.node_group = context.node.id_data.name

        self.event_dispatcher(context, self.mode)
        return {'RUNNING_MODAL'}

    def cancel(self, context):
        wm = context.window_manager
        wm.event_timer_remove(self._timer)
```

`trigger_event()` is a placeholder for something we want to do every time the modal operator fires...

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/6629039/3875b3fc-c90b-11e4-9e44-c8739a71c469.png)
You might try the branch.. but it may not work yet.. https://github.com/nortikin/sverchok/tree/obj_in_liveupdate_mode

**Comment by zeffii** [comment]
added small usability feature to objects_in node in the liveupdate branch, this works as I imagined.. @ly29 @nortikin any remarks?

**Comment by zeffii** [comment]
also @snovvfall perhaps test if you can :)

**Comment by zeffii** [comment]
right now i've hardcoded the refresh rate to 5 times per second, this is an arbitrary choice, it could be a preference in the Sverchok Preferences panel in Addons, or slider with limited range in the side panel (draw_buttons_ext) .

I do not yet know how this behaves with regard to multiple `Object_in` nodes, probably not very good - please consider this a temporary limitation. But understand that even b3d doesn't let you edit multiple objects in parallel.

**Comment by zeffii** [comment]
What would be really great is if b3d had an event handler to fire at regular intervals and stop firiing if there have been no changes to the object in a given time-frame. like 
```python
not updated for 1 second, stop firing
else fire every 0.1 seconds
```
Something like this

**Comment by ly29** [comment]
There is the scene update handler.
From there we could see if any object node has the object that currently is in edit mode.
Then we could update say 5 times per second.
For extra cleverness we time it and back off if it takes to long.

**Comment by zeffii** [comment]
oh I like that idea...

**Comment by zeffii** [comment]
[http://www.blender.org/api/blender_python_api_2_74_0/bpy.app.handlers.html?highlight=scene%20update%20handler#bpy.app.handlers.scene_update_post](bpy.app.handlers.scene_update_post)

[http://www.blender.org/api/blender_python_api_2_74_0/bpy.app.handlers.html?highlight=scene%20update%20handler#bpy.app.handlers.scene_update_pre](bpy.app.handlers.scene_update_pre)

time to read :)

**Comment by zeffii** [comment]
not sure if during edit mode, then data of the object is updated, thus firing scene_update ?

**Comment by zeffii** [comment]
```
    edit_obj = bpy.context.edit_object
    if edit_obj and edit_obj.is_updated_data:
        trigger..
```

**Comment by ly29** [comment]
Maybe not. 
I think you might have to do some special things get the edit mesh.

**Comment by ly29** [comment]
http://stackoverflow.com/questions/15429796/blender-scripting-indices-of-selected-vertices
It is a bit old and might have changed

**Comment by zeffii** [comment]
i'm now a bit more convinced that my original modal operator is not a terrible solution, altho probably not a final solution.

Maybe with a little caching of the active verts of the active object and checking against the previous state of those verts, and not call update_from_node if the coordinates are unchanged. In the case of the Spline object, however, this is a little more convoluted..

**Comment by zeffii** [comment]
hmmm, it might be useful to disengage the modal operator if the Objects_In node is no longer active...

**Comment by ly29** [comment]
I think the modal option is probably better than the scene handler. 
"Engage Live Update when Objects are being edited" perhaps.

Long term, sverchok is really close to being a Programming Language even though it does not work like one, imagine a layout like text file containging a multipile functions or independent programs.
I have some nice ideas in this area but no time.

**Comment by zeffii** [comment]
> "Engage Live Update when Objects are being edited" perhaps.

sounds good, and disengage after after a second of no mouse movement.. I found I forgot to switch it off manually and it floored Blender

i've started learning C again

**Comment by snovvfall** [comment]
This happens when I try to activate Sverchok add-on from branch "obj_in_liveupdate_mode":
![sverchok obj_in_liveupdate_mode](https://cloud.githubusercontent.com/assets/2778154/6666879/de274858-cc1a-11e4-849d-fa334e194dd8.png)
And I don't really know how to put the code you posted here into the new node in Sverchok installed from "master" branch.

**Comment by nortikin** [comment]
so now we have own modal handler?
Zeffii making best.

**Comment by nortikin** [comment]
Animation nodes have mn_execution mechanism of update, but don't know how it is works
```python
def updateAnimationTrees(event = "NONE", sender = None):
	if COMPILE_BLOCKER == 0:
		forbidCompiling()
		
		start = time.clock()
		
		secureExecution(event, sender)
		clearExecutionCache()
		
		timeSpan = time.clock() - start
		
		if bpy.context.scene.mn_settings.developer.printUpdateTime:
			printTimeSpan("Update Time ", timeSpan)
			
		try:
			bpy.context.scene.update()
			redraw_areas_if_possible()
		except: pass
			
		allowCompiling()
```

**Comment by zeffii** [comment]
@snovvfall please use an appropriate GIT command to checkout a Branch, you should not be manually copying code over -- let GIT do all the ugly work for you. 

I don't have access to my development machine + environment at the moment so even if the branch needed small fixes I don't really feel like touching it yet.

**Comment by zeffii** [comment]
with zero testing done to the code i'm going to close this for now.

**Comment by LeonCheung** [comment]
Zeffii's screenshot on Objects In design can be great. It appears to be very convenient one. I really appreciate that it could be supported in the future.

**Comment by zeffii** [comment]
@LeonCheung agreed, but I haven't worked on it since the implementation didn't feel clean. Also as soon as the node tree has to do complex operations which take longer than the timer-interval, i'm not  entirely sure what will happen.

**Comment by nortikin** [comment]
it needs activate update scene handle, maybe it has sense.

**Comment by zeffii** [comment]
http://gfycat.com/GranularPleasedBluemorphobutterfly

**Comment by ly29** [comment]
For simple layouts it works well enough, I wish we could run in the background like cycles render engine does.
Speed is major issue but still should be made possible.

**Comment by zeffii** [comment]
Yeah, not optimal, but there might not be a lot of improvement possible. 

i've made it so:
 -  only updates those layouts that have `sv_process=True`, 
 -  then it goes through all object-in's of that

I guess it could further parse the 'selected_nodes' from each *object_in*, and only update those *object_in*'s which have an object that is `active`.

**Comment by ly29** [comment]
Yeah, those results could even be cached. And process could be limited to the affected nodes.

**Comment by zeffii** [comment]
I understand the desire to get immediate feedback, but from a practical point of view I would just as effectively use a keyboard-shorcut to update nodegroups on demand (from 3dview)

**Comment by zeffii** [comment]
maybe also only update if the `mouse x y` is different from the last event , would definitely filter a lot.

**Comment by zeffii** [comment]
I think i'll enable this is an optional feature from User Preferences , so it can be merged but only people who ask about it will know it exists (unless they take time to read the user preference UI )

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/11609411/85f2a9d4-9b86-11e5-8931-597c93b88f3b.png)

**Comment by zeffii** [comment]
this works OK for a while but as soon as you start to move the mouse around the view the UV connection node starts to reference results which don't exist yet, seems like a race condition. So... while Id like to implement this properly -- i'm going to stop and probably not commit this to master.

The compromise, which is something that will be much less processor intensive is a keyboard-shortcut for 3dview to update any object-in node, in layouts which are set to update.

anyone agree?

**Comment by nortikin** [comment]
shortcut i agree.
But flag in UI as in GIF is the same good

**Comment by ly29** [comment]
It works well enough, the problem of course is when we use non trivial layout...
UV has always been a bit prone to crashing, I would like to find out why.

**Comment by zeffii** [comment]
cool @nortikin  a shortcut ...just like for editing a node script...boom..update the nodetree :). picking which kb shortcut is tricky...

@ly29 you mention earlier in this thread an idea to throttle updates if calls are more frequent than speed at which the tree can be fullly updated. I don't know the update mechanism very well, and maybe it's not worth the effort, but is there a 
```python
{
    'fully_updated" : True,    # all planned updates occurred
    "time_stamp": unix_timestamp,
    "update_duration": ms
}
```
That way it would hold-off updating if `fully update` returns false, or update_duration exceeds modal timer rate..

**Comment by nortikin** [comment]
ctrl+shift+U

**Comment by nortikin** [comment]
operator bpy.ops.node not make right click "define shortcut" action. only bpy.ops.object. Why?

**Comment by ly29** [comment]
@zeffii 
I wish there could be a reliable way to detect changes in object but there isn't. Oh well.
I guess simply to time the execution time of process from node. Which also could be extended to process as needed from a set of nodes per layout. Which wouldn't trigger multiple executions per layout with potential redundancies.

**Comment by zeffii** [comment]
@ly29 for some reason I can't merge my local live_updates branch with the center branch, arg.. yes the operator is fine and limiting to one update per layout seems the saner approach.

**Comment by zeffii** [comment]
maybe you will to merge yours with master so I can delete mine and fork it. 

(argh.. sometimes GIT is confusing)
```
To https://github.com/nortikin/sverchok.git
 ! [rejected]        live_updates -> live_updates (non-fast-forward)
error: failed to push some refs to 'https://github.com/nortikin/sverchok.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by zeffii** [comment]
ok 
```
git pull origin live_updates
```
seems to have worked

**Comment by ly29** [comment]
Sorry about causing confusion, but git is quite clever. Most of the time.

**Comment by zeffii** [comment]
git rarely gives me problem, now I learnt something new :)

**Comment by zeffii** [comment]
woah.. it does already store socket properties... no code needed.

**Comment by ly29** [comment]
well, the code is needed to store/restore the values stored in sockets for relevant nodes.

**Comment by zeffii** [comment]
that already seems to be in place, unless you can show me a node that doesn't.

for instance Lathe does restore those values.. for cent, axis and dvec.

**Comment by zeffii** [comment]
```python
            for p in params:
                val = params[p]
                setattr(node, p, val)
```
it seems that this snippet pretty much does it already

**Comment by zeffii** [comment]
i'm partially confused now, but it has been a crazy day.

**Comment by ly29** [comment]
Matrix in use the storage in socket for its values.
```python
for s in node.inputs:
    if s.bl_idname == "VerticesSocket" and s.use_prop:
         # store prop etc
```
https://github.com/nortikin/sverchok/blob/master/node_tree.py#L89-L91

**Comment by ly29** [comment]
Anyway there are simply to much exceptions for completely sane code in the old Sverchok.

**Comment by ly29** [comment]
oops, in the wrong issue. tired,

**Comment by ly29** [comment]
Note that this is in master now.

**Comment by ZodiacFRA** [comment]
hello @zeffii 
I'm trying to achieve realtime nodes for a personal project and you previously stated:
> right now i've hardcoded the refresh rate to 5 times per second
You did this with a modal operator am I right?
Could you explain me briefly how you did this? thanks :)

**Comment by victorcalixto** [comment]
![sverchok-autoupdate](https://user-images.githubusercontent.com/4661824/106075968-8f7d8c80-6106-11eb-81b2-441398f4a699.gif)
Hi guys! I am having the same issue even when "Live node" or "animation" options is on. Anyone knows why? Or have similar issue? Cheers!

**Comment by Durman** [comment]
The most simple thing you can do to have live update is just switch on animation. Or if the tree has heavy calculation process you can just press right/left arrow on keyboard to switch the frame number manually. It will trigger tree updating. Also there is `Live update` button in N panel in tools category. In some cases instead of using animation it's more convenient to use this button.

**Comment by victorcalixto** [comment]
Many thanks Durman! The `Live update` button in N panel is not updating, but right/ left arrow  and updating through the animation work great. Cheers

**Comment by nortikin** [comment]
button `update tree`?
