### ISSUE TITLE
Objects in nodes mess up their input objects after duplicating nodes

### ISSUE THREAD

**Issue by snovvfall** [nortikin/sverchok#596]
When I duplicate Objects in node with input Cube it creates new node with Cube2 input, because there is another object in the scene called Cube 2. So after duplicating Objects in node Sverchok looks for other objects and assigns them to duplicated Objects in node. I understand it can be a feature, but I often need Objects in node to stay exactly the same after duplicating.
![object in duplicate](https://cloud.githubusercontent.com/assets/2778154/6839049/f7940d32-d39d-11e4-9cf5-c5f0c569847d.png)

**Comment by ly29** [comment]
Hmmm, I cannot duplicate this.

**Comment by snovvfall** [comment]
I tested it on another computer with latest versions of Blender and Sverchok (master) and it behaves differently, but the problem is the same. If there are several objects, Objects in node changes its object after duplicating. On one computer it changes only from Cube to Cube2, for example, and on another it changes only from Cube2 to Cube.

**Comment by nortikin** [comment]
cannot recreate this behaviour. Strange

**Comment by zeffii** [comment]
I can reproduce this. it is weird! 
![image](https://cloud.githubusercontent.com/assets/619340/6850504/d45fd9c2-d3d9-11e4-910d-be74c5d3b08d.png)

**Comment by ly29** [comment]
Okay this is a string handling issue with objectin most likely. Could be solved by switching to a different more sane way of storing the object names if that is the case.

**Comment by ly29** [comment]
Still can't reproduce it, do you duplicate with shift-D?

@zeffii 
Could you test something?
Disable ```process``` in object in and test again and compare the object_local string prop of the nodes.

What should happen is:
node is copied, doesn't have the whole handle thing, but has the list of objects serialized into ```object_local``` then it will try to serialize it.

```
        if self.objects_local and not handle[0]:
            handle_write(name, literal_eval(self.objects_local))
            handle = handle_read(name)
```
And a similar thing in ```draw_buttons```

**Comment by zeffii** [comment]
yeah, shift+D on the `Objects-in` node.

But I can't reproduce without fail, sometimes the duplication gives the correct objects list, other times the list contains references to a different object.

I think for simplicity this part of code should see a rewrite, also for clarity -- i'm puzzled why it was written this way.

**Comment by ly29** [comment]
The reason for that is lost in history...
Especially it would be extra sane since the whole handle thing is only used here and could be dumped.
The sane approach would be to use a ```bpy.props.CollectionProperty```

**Comment by ly29** [comment]
I can kind of duplicate if the mouse pointer is over the selection button when I press shift-D, then it will get the active selection. Sometimes.. Hmm

Try adding and see if you can duplicate it then. 
```python
    def copy(self, node):
        if self.objects_local:
            name = self.name + self.id_data.name
            handle_write(name, literal_eval(self.objects_local))
```

of course adding a collection property would break old layouts without some compatibility cruft.

**Comment by zeffii** [comment]
The explicit copy method seems to do the trick, i'd be happy to submit it was a fix..  I haven't been able to get weird results since adding it.

**Comment by ly29** [comment]
Okay let go with it then, I can't duplicate it with copy either. 
Can you do it? Don't have time today.

**Comment by zeffii** [comment]
sure thing @ly29 .

**Comment by zeffii** [comment]
please test latest master @snovvfall , if this patch doesn't fix it then something more extreme will be needed.

**Comment by nortikin** [comment]
i writed that way object in because it was first node in sverchok!! we got objects somehow there.

**Comment by snovvfall** [comment]
I can confirm that this issue is fixed in master branch. Good work!
