### ISSUE TITLE
Viewer Draw and Index Viewer "Show" option as True/False input socket

### ISSUE THREAD

**Issue by snovvfall** [nortikin/sverchok#598]
Just an idea to show/hide many viewers at once manually or with predefined logic by other nodes. I used reroute node on the image.
![viewer show socket](https://cloud.githubusercontent.com/assets/2778154/6839358/292dc348-d3a2-11e4-9402-6b033b50ea1c.png)

**Comment by ly29** [comment]
I does make sense and I wish we could place socket like you show in the example. Also other settings would be nice.

**Comment by zeffii** [comment]
Yeah, this would be useful. I've considered a different approach which involves a dedicated ViewerEnsemble node (a proxy..). The idea being that you might select a group of ViewerDraw nodes, then use an operator to fill up an Ensemble node with references to those ViewerDraw nodes. The ensemble node would get a property checklist. Any property of the ViewerDraw node could be exposed selectively as a socket. 

The advantage of such a proxy node is the ViewerDraw node code remains unchanged, but many more properties become available for keyframing / socket input

**Comment by zeffii** [comment]
I short SN MK1 script to select ViewerDraw nodes and activate / deactivate and change face_colours.
```python
def sv_main(show=0, col1=[[]], col2=[[]]):

    in_sockets = [
        ['s', 'show', show],
        ['v', 'col1', col1],
        ['v', 'col2', col2]
    ]

    ng = bpy.data.node_groups['NodeTree']
    nodes = ng.nodes
    
    vd1 = nodes['Viewer Draw2']
    vd2 = nodes['Viewer Draw2.001']
    
    vd1.activate = vd2.activate = show

    if col1 and col1[0]:
        vd1.face_colors = (col1[0][0])

    if col2 and col2[0]:
        vd2.face_colors = (col2[0][0])


    # irrelevant
    out_sockets = [['v', 'verts', []]]

    return in_sockets, out_sockets

```

**Comment by nortikin** [comment]
more flexible interface!!!

**Comment by ly29** [comment]
I have some long term ideas about how this could be done in a flexible, extensible, standard way.
