### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by xaccrocheur** [nortikin/sverchok#600]
I "installed from file" *without any error*, but now I can't find sverchok anywhere in the addon list to activate it... Is it listed under another name? Is it activated by default, and not managed in the user prefs? Did I miss something in the install process?

**Comment by zeffii** [comment]
it is not activated by default. Have you followed the install guide? 
https://github.com/nortikin/sverchok/blob/master/README.md#installation

**Comment by zeffii** [comment]
don't feel bad about having difficulty installing the addon. Addon installation is in my opinion one of the weaker parts of Blender, especially complex multi-file addons like Sverchok.

**Comment by zeffii** [comment]
here's a raw bootstrap script, which downloads the zip, puts it in the right place, then automagically enables the addon:
https://gist.github.com/zeffii/5a4440e7455940174ab9

if you want to try that that would be great. It works at least on Ubuntu, but has been written platform agnostic so should work on all platforms. If this works for you, i'm tempted to add it to the installation section of the readme.

**Comment by ly29** [comment]
It should be available in the Nodes section of the preferences.

**Comment by xaccrocheur** [comment]
Hey thanks for your answer guys, I'm trying your leads as soon as I'm home! (I'm using GNU/Linux Ubuntu 14.04 and Blender 2.73a (the archive from the website)

**Comment by zeffii** [comment]
OK the script is set to 2.74, change that to 2.73, then rerun

**Comment by zeffii** [comment]
https://gist.github.com/zeffii/5a4440e7455940174ab9#file-bootstrap-py-L13

**Comment by nortikin** [comment]
or `addons_contrib` !!!

**Comment by nortikin** [comment]
not see problems, have debian.

**Comment by xaccrocheur** [comment]
@zeffii Aaahhh! Time to test 2.74 instead ;) Thanks!

**Comment by nortikin** [comment]
sverchok 040??? wtf?

**Comment by xaccrocheur** [comment]
OK, so it works now; I ran the script, then re-launched Blender, still no sverchok. Then changed from addons to addons_contrib, re-ran the script, then re-launched Blender, and then in the prefs I had sverchok and an error "addons with the same name" and an error when trying to activate sverchok. Then I deleted the one from addons, then no sverchok again. Then I moved the one from addons_contribs to addons and BAM! Activatable sverchok. Thank you very much everybody!

@nortikin What, is there a younger version?

**Comment by ly29** [comment]
Oh I see, down this version.
https://github.com/nortikin/sverchok/archive/master.zip

**Comment by ly29** [comment]
@nortikin 
0.4.0 is the latest realease

**Comment by nortikin** [comment]
@ly29 can i delete release 040? or should release new version?
