### ISSUE TITLE
PyCON 2015

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#603]
Videos i've found interesting in this year's PyCon. (will add videos as watched)

- [Raymond Hettinger - Beyond PEP 8 -- Best practices for beautiful intelligible code] (https://www.youtube.com/watch?v=wf-BqAjZb8M) "pep8 onto thyself"
- [David Beazley - Modules and Packages](https://www.youtube.com/watch?v=0oTh1CXRaQ0)  also handles imports!

**Comment by ly29** [comment]
interesting.

**Comment by nortikin** [comment]
newer thought of what import is

**Comment by zeffii** [comment]
I'll have to watch the dave beazley import video several times, it rocks.
