### ISSUE TITLE
Ctrl+I menu not working in TextEditor?

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#605]
It could just be my machine. And by ' not working ' i mean, the keyboard short isn't added automatically anymore. It's been a while since I used svlang converter so I can't say if this was broken recently.

**Comment by nortikin** [comment]
i cannot make work one shortcut in my addon. Don't understand what is it. So, maybe we forgot something? compare to other addons?

**Comment by zeffii** [comment]
Something changed in Blender with respect to scripted keymap insertion. Obviously at some point this has worked, else it wouldnt be broken now. Yes. will fix. can fix.

**Comment by zeffii** [comment]
this should be fixed by the latest commit

**Comment by zeffii** [comment]
but no unregistering of keymaps yet...

**Comment by zeffii** [comment]
key map issue still wonky
```
def add_keymap():
    wm = bpy.context.window_manager
    text_editor = wm.keyconfigs.user.keymaps.get('Text')

    if not text_editor:
        # print('Text Editor keymap not available to add to.')
        return

    keymaps = text_editor.keymap_items

    ''' SHORTCUT 1 Node Refresh: Ctrl + Return '''
    ident_str = 'text.noderefresh_from_texteditor'
    if not (ident_str in keymaps):
        keymaps.new(ident_str, 'RET', 'PRESS', ctrl=1, head=0)

    ''' SHORTCUT 2 Show svplugMenu Ctrl + I (no text selected) '''
    new_shortcut = keymaps.new('wm.call_menu', 'I', 'PRESS', ctrl=1, head=0)
    new_shortcut.properties.name = 'TEXT_MT_svplug_menu'

    print('added keyboard items to Text Editor.')

``` 

this is how to script a keymap adding, and if that code is executed from text editor then the 'Text' keymap collection is available for sure, but during Sverchok startup this is not the case. .. Actually, at this point I really don't understand why sometimes itś OK and others not..

**Comment by ly29** [comment]
From where is it called?

**Comment by zeffii** [comment]
text_editor_plugins.py

**Comment by zeffii** [comment]
```python
import bpy

wm = bpy.context.window_manager
km = wm.keyconfigs.user.keymaps
text_editor = km.get('Text')

def does_svplug_kbshort_exist(text_editor):
    for k in text_editor.keymap_items:
        try:
            m = (k.properties.name == 'TEXT_MT_svplug_menu')
            if m:
                return True
        except:
            ...

print(does_svplug_kbshort_exist(text_editor))
```

a solution is to include an operator in preferences, to enable kb shortcts... i really can't be bothered figuring out what this mess is about.
