### ISSUE TITLE
primitive geodesic sn1 code (convert from sn2 version)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#606]
https://gist.github.com/zeffii/059caaa9b88af35e4098

this just has the features I need. 

Might be time to check and merge the IcoSphere node, or if a few primitives can be combined instead.

**Comment by zeffii** [comment]
the normals of the hedrons are not all pointing outwards...

**Comment by zeffii** [comment]
@ly29 the included SN2 version of the geodesic script doesn't seem to work, it gives a nice error tho..

**Comment by ly29** [comment]
a very pretty error indeed

**Comment by ly29** [comment]
Should work now.

Actually I am bit surprised it ever worked, I wonder when it stopped, haven't used it in while to be honest.

**Comment by ly29** [comment]
Still want redo the load as a series of virtual modules mapped into a namespaces per script, especially after watching a bit more about the

**Comment by zeffii** [comment]
cool thanks. I don't really use SN2, because i've made it unstable a few times and the sockets don't change if I change my mind and modfiy the script..I recall they just get added to existing. The code I wrote for that was super super ugly and i've found instances where even that atrocity isn't smart enough to hot-swap the sockets ("There's got to be a better way - Raymond Hettinger")

More and more I think of starting a similar project in C++ with openFrameworks, but as a solo project it seems a bit daunting - but also maybe liberating

**Comment by ly29** [comment]
I am thinking about redoing sverchok since I think the basic idea is good, but some bad decisions early one hamper the project quite a bit, a bmesh based system for mesh editing interesting me the most right now. But time...
C++ sounds like fun,

**Comment by nortikin** [comment]
C++ sounds good. Main mistakes of current system need to be writed - sockets may be more informative and complex, C++ base, naming of classes, decorators usage, what else? This all we need keep in mind. I need study C++ to go forward and all early layout need to be supported, because of this http://www.blendernation.com/event/sverchok-workshop-mons-belgium/ or example
