### ISSUE TITLE
Viewer Draw dosen't bake shear transforms

### ISSUE THREAD

**Issue by elfnor** [nortikin/sverchok#607]
Shear transforms show in preview but don't get baked.
![shear_direct](https://cloud.githubusercontent.com/assets/7930130/7309713/05ee16b8-ea76-11e4-8d2b-206d660e7c60.png)

The "Viewer Bmesh" node also ignores shear transforms.

I know I can use the "Apply Matrix" node to get them applied but seeing them in preview and not baked is surprising.

The "Matrix Interpolate" node also does not shear. It does some interesting rotations with a shear matrix as input.

The "Matrix Iterate" node is OK.

**Comment by ly29** [comment]
Ohh I see.
What I happens is:
Viewer draw does something similar to apply matrix internally and the ```.matrix_world``` doesn't seem to support none Rotate, Translate, Scale matrices.

**Comment by ly29** [comment]
Matrix interpolate probably is probably for some similar reason. There is no description of the underlaying method used, would have to look into the source. Will try to soon.
http://www.blender.org/api/blender_python_api_2_74_release/mathutils.html?highlight=matrix.lerp#mathutils.Matrix.lerp

**Comment by zeffii** [comment]
very odd. haha :) 

The code path for the Viewing and Baking are very different by design, this allows for fast bgl drawing when Viewed, and convenient Mesh construction when baked. By convenient I mean relatively simple to write and read that code. I suspect also the Beta BMeshViewer2 suffers from this, sadly I don't immediately come with a good solution.. there's nothing special about a shear matrix..

**Comment by nortikin** [comment]
odd realy

**Comment by zeffii** [comment]
does this have to do with a shear matrix being not Orthogonal, unlike scale/rotation/location matrices... it breaks the relationships between coordinates..

**Comment by zeffii** [comment]
yeah, Efnor. this is a bug in matrix_world of mesh objects, we can write a co-routine as an optional 'force own matrix'  toggle in the external panel, I think that would be the most helpful option. It will however be slower than offloading the matrix transforrms to `obj.matrix_world`.

**Comment by zeffii** [comment]
or maybe the sheer matrix must be be extracted and applied to the `obj.matrix_local`, in addition to obj.matrix_world

**Comment by zeffii** [comment]
```python
import bpy
import bmesh
import mathutils
from mathutils import Matrix, Vector

def new_obj(bm, named_object, named_mesh):
    me = bpy.data.meshes.new(named_mesh)
    bm.to_mesh(me)
    bm.free()

    scene = bpy.context.scene
    obj = bpy.data.objects.new(named_object, me)
    scene.objects.link(obj)
    return obj


shear_matrix = Matrix([
    (1.0, 0.0, 0.6, 0.0),
    (0.0, 1.0, 1.1, 0.0),
    (0.0, 0.0, 1.0, 0.0),
    (0.0, 0.0, 0.0, 1.0)
])

# given sheat matrix at creation time
bm = bmesh.new()
bmesh.ops.create_cube(bm, size=2, matrix=shear_matrix)
obj1 = new_obj(bm, 'named_object_1', 'named_mesh_1')

# vertex coordinates set one by one
bm = bmesh.new()
bmesh.ops.create_cube(bm, size=2)
for v in bm.verts:
    v.co = shear_matrix * v.co
obj2 = new_obj(bm, 'named_object_2', 'named_mesh_2')
obj2.location = 3, 0, 0

# given shear matrix to matrix_world
bm = bmesh.new()
bmesh.ops.create_cube(bm, size=2)
obj3 = new_obj(bm, 'named_object_3', 'named_mesh_3')
obj3.matrix_world = shear_matrix
obj3.location = 6, 0, 0
```

![image](https://cloud.githubusercontent.com/assets/619340/7555063/1fe6adba-f740-11e4-9062-efc7fe2f6a84.png)

there's a 4th method..  `me.transform(matrix)`

**Comment by zeffii** [comment]
I will fix this in BMeshViewer2 (already in Beta nodes...)

**Comment by zeffii** [comment]
```python
    if matrix:
        matrix = matrix_sanitizer(matrix)
        if node.extended_matrix:
            sv_object.data.transform(matrix)
            sv_object.matrix_local = Matrix.Identity(4)
        else:
            sv_object.matrix_local = matrix
    else:
        sv_object.matrix_local = Matrix.Identity(4)

```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7555245/278fa530-f745-11e4-8337-5242968ed222.png)

You can test this in the `pragma2` branch shortly

**Comment by zeffii** [comment]
![screenshot from 2015-05-10 19 45 57](https://cloud.githubusercontent.com/assets/619340/7555484/39ed4f40-f74d-11e4-815e-31881390f86a.png)

implemented in ViewerDrawMK2 also. I welcome testing.. Before pushing to master.

**Comment by nortikin** [comment]
even did not think of local matrix, missed from my attention.

**Comment by zeffii** [comment]
after discussion with ideasman some weeks ago it appears that that sheer matrix is not supported as a matrix_world, the solution I was used to implement the transform function which does take a sheer matrix. Implemented in bmeshview2 and viewerdraw baking. Not much else can be done here.
