### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#616]
what about:

```
sv_ascii_logo = """\
 _______ _    _ _______  ______ _______ _     _  _____  _     _
 |______  \  /  |______ |_____/ |       |_____| |     | |____/
 ______|   \/   |______ |    \_ |_____  |     | |_____| |    \_

 """
```

**Comment by zeffii** [comment]
on posix system (linux, mac) we can even have 
![image](https://cloud.githubusercontent.com/assets/619340/7349475/a971276e-ecf9-11e4-8df0-c58fff379ebe.png)

windows will default to no colour :)

**Comment by zeffii** [comment]
```
sv_ascii_logo = """\
  ______ _    _ _______  ______ _______ _     _  _____  _     _
 /______  \  /  |______ |_____/ |       |_____| |     | |____/
 ______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
 """


def do_logo():
    print(sv_ascii_logo)

    intialized = 'initialized.'
    if os.name in ('posix'):
        print("\033[1;31m{0}\033[0m\n".format(intialized))
    else:
        print(intialized)

```

damn.. i thought the keymap issue was solved...

**Comment by zeffii** [comment]
```python
def do_logo():

    l1 = " ______ _    _ _______  ______ _______ _     _  _____  _     _"
    l2 = "/______  \  /  |______ |_____/ |       |_____| |     | |____/"
    l3 = "______/   \/   |______ |    \_ |_____  |     | |_____| |    \_"
    l4 = "initialized."
    lines = [l1, l2, l3, l4]

    can_paint = os.name in {'posix'}

    with_color = "\033[1;31m{0}\033[0m" if can_paint else "{0}"
    for line in lines:
        print(with_color.format(line))
```

**Comment by snovvfall** [comment]
Do we need a small logo for a website, for example? I mean another logo, like most of software and some brands have. If so, I can try make a vector sketch and suggest it here or in a new issue.

**Comment by nortikin** [comment]
This logo is nice and simple. ))
No problem to have new logo for website. will upload to old site also.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/7984227/dee5335e-0ac7-11e5-8562-da0e2c1159e0.png)
Not a logo, just an image

**Comment by nortikin** [comment]
it is not obviouse where is head... but it is intrigue indeed

**Comment by zeffii** [comment]
here, this can be run and it will download a mesh.json and decode it , mirror it:

```python
import bpy
import urllib
import json
from urllib.request import urlopen

A = "https://gist.githubusercontent.com/zeffii/"
B = "394581876fa60887d240/raw/"
C = "b0df45752b9aea4cd0cc08d477a0091eac3b909a/"
D = "sverchzanna.json"
url = A + B + C + D

found_json = urlopen(url).readall().decode()
wfile = json.JSONDecoder()
wjson = wfile.decode(found_json)

verts = wjson['verts']
faces = wjson['faces']

mesh = bpy.data.meshes.new("mesh_name")
mesh.from_pydata(verts, [], faces)
mesh.update()

obj = bpy.data.objects.new("obj_name", mesh)

scene = bpy.context.scene
scene.objects.link(obj)

mirror = obj.modifiers.new(type='MIRROR', name="mirror")
mirror.use_z = 1
mirror.use_x = 0
mirror.use_y = 0
```

could use similar technique for object_in mesh storage..

**Comment by zeffii** [comment]
this encodes it to a `.json`
```python
import bpy
import bmesh

object_name = 'SVERCHZANNA'
me = bpy.data.objects[object_name].data

# Get a BMesh representation
bm = bmesh.new()   # create an empty BMesh
bm.from_mesh(me)   # fill it in from a Mesh

mesh_dict = {}
bm.faces.ensure_lookup_table()

mesh_dict['verts'] = [v.co[:] for v in bm.verts]
mesh_dict['faces'] = [[v.index for v in f.verts[:]] for f in bm.faces]

m = json.dumps(mesh_dict, sort_keys=True, indent=2)
text_block = bpy.data.texts.new(object_name + '.json')
text_block.from_string(m)
```

**Comment by portnov** [comment]
So, the next step is to parametrize the model :)

**Comment by zeffii** [comment]
yep :)

**Comment by zeffii** [comment]
here is a front facing one (??)

```python
import bpy
import urllib
import json
from urllib.request import urlopen

A = "https://gist.githubusercontent.com/zeffii/"
B = "644038548b5c22c7808e/raw/"
C = "d6ba8583d436a43a5c99302f290e9e6f795dca26/"
D = "SVERCHZANNA.json"

url = A + B + C + D

found_json = urlopen(url).readall().decode()
wfile = json.JSONDecoder()
wjson = wfile.decode(found_json)

verts = wjson['verts']
faces = wjson['faces']

mesh = bpy.data.meshes.new("mesh_name")
mesh.from_pydata(verts, [], faces)
mesh.update()

obj = bpy.data.objects.new("obj_name", mesh)

scene = bpy.context.scene
scene.objects.link(obj)

mirror = obj.modifiers.new(type='MIRROR', name="mirror")
mirror.use_z = 0
mirror.use_x = 1
mirror.use_y = 0
```

**Comment by zeffii** [comment]
I think I've lost my Ubuntu harddrive, not sure how the others survived (bad electrical storm here)

**Comment by nortikin** [comment]
ssd?

**Comment by zeffii** [comment]
old western digital... it was starting to rattle anyway.

**Comment by nortikin** [comment]
if you need 150 dollars for that, i can transfer

**Comment by zeffii** [comment]
when I unplugged for the storm... the power [socket heads](http://img.weiku.com/waterpicture/2011/10/27/6/10_16A_250V_EUROPE_VDE_POWER_PLUG_634556805117749390_3.jpg) touched a metal hammer head (stupid place for hammer to be...but it was there) and made a closed loop and I saw a big spark. The ubuntu harddrive has not booted up since.

**Comment by zeffii** [comment]
It's OK i have funds for fixing the computer.

**Comment by nortikin** [comment]
logo is beautifull

**Comment by zeffii** [comment]
the ascii or lowpoly ?

**Comment by zeffii** [comment]
i like looking at the red sverchok ascii logo when Blender stars.

**Comment by zeffii** [comment]
If i had not uploaded the model as json it would be lost forever.

**Comment by nortikin** [comment]
need recalc normals

**Comment by nortikin** [comment]
yes, it is mirricul'

**Comment by zeffii** [comment]
are normals inverted?  #sverchok irc

**Comment by nortikin** [comment]
shame - between legs

**Comment by enzyme69** [comment]
Brilliant....

On Saturday, 6 June 2015, nikitron <notifications@github.com> wrote:

> shame - between legs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nortikin/sverchok/issues/616#issuecomment-109421787>.
>


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
@nortikin  on monday explain / annotate what you think the rear shold look like, i have no reference images.

**Comment by zeffii** [comment]
http://blenderpython.tumblr.com/image/120718560859

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8018490/cdf0d6cc-0c1e-11e5-98d2-30fa03de70ed.png)

**Comment by zeffii** [comment]
good news, Ubuntu harddrive lives again.

**Comment by nortikin** [comment]
goood

**Comment by nortikin** [comment]
rear shold is nothing else, that you made. Not so important.

**Comment by zeffii** [comment]
here's an updated version: https://www.dropbox.com/s/pe7f6ciza8vt8fq/cricket_remakeFIXR.blend?dl=0

**Comment by enzyme69** [comment]
![screen shot 2016-10-28 at 11 58 33](https://cloud.githubusercontent.com/assets/3952687/19790690/f4d5b3ce-9d05-11e6-90a1-96ce5a0298ea.png)

I don't know just accidental.

**Comment by nortikin** [comment]
![arc_cases](https://cloud.githubusercontent.com/assets/5783432/19823977/05a58874-9d7d-11e6-8356-3c81e2af0a4f.png)
https://gist.github.com/nortikin/ffb5566e1ba7ecf2ecb7ca7edb96e571
this flip

**Comment by enzyme69** [comment]
I am confident to make some Insects creatures using Sverchok now. Soon! Thanks for the help so far.

**Comment by zeffii** [comment]
@enzyme69 do you reckon you could animate a walk cycle for the sverchok cricket? :)

@portnov said a while back  

> So, the next step is to parametrize the model :)

With radii x,y for Skin Mesher (when I get around to it) that would be totally possible .

**Comment by enzyme69** [comment]
@zeffii I am trying to get into Blender rigging properly. Resources are all over the place. Wondering if Blender Rigify can do it. 

Hmm... it's been a while since I am actually animating. I think I start to feel the itch to rig and animate again.

Will keep this in mind as homework. 

Currently the sverchok model you made sitting on my desktop. It's a pending work.

**Comment by enzyme69** [comment]
[text_GP_008_2017_04_04_11_50.zip](https://github.com/nortikin/sverchok/files/892983/text_GP_008_2017_04_04_11_50.zip)
![screen shot 2017-04-04 at 21 49 36](https://cloud.githubusercontent.com/assets/3952687/24655230/c358bace-1980-11e7-8f0a-928b6e37d5a0.png)
