### ISSUE TITLE
Numpy-array-node

### ISSUE THREAD

**Issue by Kosvor** [nortikin/sverchok#622]
![555555](https://cloud.githubusercontent.com/assets/7894950/7407970/66c27c00-ef20-11e4-985a-04ed83228efa.png)

https://github.com/nortikin/sverchok/tree/Numpy-array-node

Du not know a single thing in numpy, so... Is it works as expeсted?

**Comment by zeffii** [comment]
that looks about right.

**Comment by nortikin** [comment]
cool
