### ISSUE TITLE
Outline Node.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#623]
![screenshot from 2015-04-30 19 29 46](https://cloud.githubusercontent.com/assets/619340/7418615/61d52cca-ef6f-11e4-8a2c-864d76b22a1c.png)

The general idea..

**Comment by nortikin** [comment]
this idea usefull for streets projecting, but there are radiuses also and different roads width

**Comment by zeffii** [comment]
potentially offset could be configured per edge index, but it increases the complexity a lot..

**Comment by nortikin** [comment]
did i showed you my road file? maybe we need superprofiler? to automate different intersections from user

**Comment by zeffii** [comment]
Think you did show the road file, show again just in case :)

closer !

![image](https://cloud.githubusercontent.com/assets/619340/7445897/135f6b7e-f1c6-11e4-8489-671c5cb2fcba.png)

**Comment by zeffii** [comment]
yes, I remember that Road file, thanks for the file Nikita. very very cool. Awesome use of profile node.

btw, the last part of this script (outliner) are difficult . hurting my brain.

**Comment by nortikin** [comment]
on sunday i can look at it, not now, sorry. it my lovely thing - to make such pofiles or connect edges, polygons etc.

**Comment by zeffii** [comment]
i was going to only join verts, to get edges, and use the bmesh fill edgenet because there will only be tris and quads from the original output.

**Comment by zeffii** [comment]
I haven't found time to return to this, I think it requires a preprocessing step , if total angels found is not 360 then at least 1 set of edges in the edge fan is larger than 180. Without doing a costly rotation check, a solution might be to test if the outer vertices of any of the sequential edge combinations intersects with any other edge, if they do, then the edge combo is more than 180, but lipped. Will show with images.

**Comment by zeffii** [comment]
finished another part of this yesterday, now to add intersection checks :)

**Comment by zeffii** [comment]
here the gist: https://gist.github.com/zeffii/528ccd234adb297593c9

**Comment by Aiena-g** [comment]
Hmm this is really interesting can it be used to define say walls of a building with even thickness. Could potentially massively speed up modelling of base geometry.

**Comment by Aiena-g** [comment]
Its like skin modifier. But Skin makes a round sort of skin. Also give an option to project from an edge instead of center.

**Comment by zeffii** [comment]
I don't mean to get your hopes up. I had not abstracted this code far enough to make it easy to work with and pick up later. I suspect it is not too hard to rewrite based on an assumption that the Z is up and the geometry being fed into it is always on the XY plane.

**Comment by zeffii** [comment]
well, much less code now for more useful results. the polygon twisting is easy to fix. (either check intersections or 2d convex hull) 

![image](https://cloud.githubusercontent.com/assets/619340/23580934/8a5bc172-010b-11e7-8244-4c2b4141045a.png)

**Comment by zeffii** [comment]
this might be a fluke.. but it looks like only those edges that are terminals, need looking at..

**Comment by DolphinDream** [comment]
This is basically a 2D skin node. Perhaps the joint radius could be controlled the same way as the skin node does.

**Comment by zeffii** [comment]
looking at the interim results.. i think a simple solution exists :)  

- each intersection is linked to the vertices it creates, 
- each vertex is linked to a new edge
- and each new edge will be able to return 'other'.
- each new edge associated with an intersection will be able to test if it meets up with any edges (virtually or really intersects an edge), if either other those is true, then vertices closest to the intersection are moved towards the intersection. 
- vertices that happen with Epsilon will be a single vertex later (after double removal step)

**Comment by enzyme69** [comment]
Can the Outline also works to make Silhouette? *cough* Or that's a bit too crazy request again?

**Comment by zeffii** [comment]
>  Can the Outline also works to make Silhouette?

That's not what i'm trying to do in this case. When you are talking about a silhouette you should consider it a 3d to 2d operation, much like Kosvor's raycasting experiment.
