### ISSUE TITLE
Installation without error unsuccessful

### ISSUE THREAD

**Issue by ajwood** [nortikin/sverchok#631]
Sverchock 0.5.1
Blender 2.74
Ubuntu 14.04

My installation appears to be successful, but Blender doesn't recognize the add-on.

I've tried installing from file (using the .zip):
```
$ ./blender-2.74-linux-glibc211-x86_64/blender
connect failed: No such file or directory
Read new prefs: /home/andrew/.config/blender/2.74/config/userpref.blend
found bundled python: /home/andrew/Blender/PACKAGE/blender-2.74-linux-glibc211-x86_64/2.74/python
# <install from file in the Blender window>
Modules Installed from '/home/andrew/Blender/PACKAGE/sverchok-0.5.1.zip' into '/home/andrew/.config/blender/2.74/scripts/addons' ()
```

After this, Sverchok doesn't appear in the add-on menu:
![screenshot from 2015-05-09 13 37 55](https://cloud.githubusercontent.com/assets/93171/7551266/a31d71dc-f650-11e4-91fc-3229a7c0dbaa.png)

It looks like Blender installed the add-on without any trouble:
```
$ ls ~/.config/blender/2.74/scripts/addons/
__init__.py  sverchok-0.5.1
$ ls ~/.config/blender/2.74/scripts/addons/sverchok-0.5.1/
core  data_structure.py  docs  __init__.py  json_examples  LICENSE  menu.py  nodes  node_scripts  node_tree.py  old_nodes  package.py  README.md  settings.py  ui  utils
```

I also confirmed that python3 knows how to find the numpy installation:
```
andrew@cort ~$ python3.4
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>>
```

**Comment by zeffii** [comment]
rename the directory to sverchok not `sverchok-0.5.1` first..

**Comment by ajwood** [comment]
Yep, that's it! I knew it was something silly..

**Comment by zeffii** [comment]
python can't handle dots in folder names, when they are hoisted as a package name

**Comment by ajwood** [comment]
Why are other add-ons not hurt by this? Do most people package their add-on in directories without version strings?

**Comment by zeffii** [comment]
yeah, the version string is unfortunate, we should change it. it's an easy mistake to make. we could make it `sverchok-master-051`

**Comment by ajwood** [comment]
Might it be worth updating the the README to indicate what name the directory should have once it's installed?

**Comment by zeffii** [comment]
I just read it's a GitHub convention, but it breaks the `install from file`  mechanism if you use the release version. If you simply download from the main page 

![image](https://cloud.githubusercontent.com/assets/619340/7551588/30565e96-f68e-11e4-9955-52364ce90324.png)

all is OK.  I have just updated the readme.

**Comment by zeffii** [comment]
Thanks by the way, for reporting it. Most of the users go straight for the zip on the main page, or use GIT directly

**Comment by ajwood** [comment]
Nice, glad it was useful :) A couple quick follow-up questions:

1) Is the master branch typically stable enough for daily use?
2) Is it appropriate to ask Sverchok-specific questions over at Blender.SE?

**Comment by zeffii** [comment]
1) yeah, we don't want master to be unstable at any point.  Releases aren't more like milestones, not a classification of code robustness.
2) By all means ask sverchok specific stuff here.

**Comment by nortikin** [comment]
Here you can ask as far as you here allready.
