### ISSUE TITLE
edit mode script node (copies vertex normals from donator mesh for low poly modeling)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#632]
- Sphere is a mesh which has has a collection of vertex normals which are preventing the gradient smoothing of the surface shade.
- Sphere.001 is a replicate surface that follows the proposed contour of the low polymesh, but it is highly and smoothly subdivided. this allows a smooth gradient of vertex normals to be calculated.
- The function operates on a set of selected vertices in `Sphere`, and finds the closest vertices in Sphere.001 and copies the normals into Sphere

Sphere:

![image](https://cloud.githubusercontent.com/assets/619340/7554056/9709dc38-f717-11e4-84c4-b989f4925cef.png)

Sphere.001

(with origin in same place)
![image](https://cloud.githubusercontent.com/assets/619340/7554052/5f3bd270-f717-11e4-8a62-fa748fab8d67.png)

### Code

```python
import bpy
import bmesh
import mathutils
from mathutils import Vector, kdtree
from sverchok.utils.sv_bmesh_utils import pydata_from_bmesh

def sv_main(radius=0.3):
    verts_out = []
    edges_out = []
    faces_out = []

    in_sockets = [
        ['s', 'radius', radius]
    ]

    bm = bmesh.new()
    objname = "Sphere"
    obj = bpy.data.objects.get(objname)
    replicator = bpy.data.objects.get('Sphere.001')
    rmesh = replicator.data
    
    size = len(rmesh.vertices)
    kd = kdtree.KDTree(size)

    for i, vtx in enumerate(rmesh.vertices):
        kd.insert(vtx.co, i)
    kd.balance()    

    if obj:

        bm = bmesh.from_edit_mesh(obj.data)
        verts = (v for v in bm.verts if v.select)
        for v in verts:
            co, idx, dist = kd.find(v.co)
            n = rmesh.vertices[idx].normal
            v.normal = n

        bmesh.update_edit_mesh(obj.data)
        

    out_sockets = [
        ['v', 'verts', verts_out],
        ['s', 'edges', edges_out],
        ['s', 'faces', faces_out]
    ]

    return in_sockets, out_sockets
```

result... useless, blender overwrites anyway:

![opt_mover_and_shaker](https://cloud.githubusercontent.com/assets/619340/7554061/281eed94-f718-11e4-95e8-846c40466ece.gif)

**Comment by nortikin** [comment]
blender overwrites... sad. but nice try

**Comment by nortikin** [comment]
http://youtu.be/Sy4LxibVVI8
https://www.blend4web.com/ru/article/110
