### ISSUE TITLE
rollout uv texture to 3d

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#634]
https://gist.github.com/nortikin/1d316cc7d945e521996b this is working scripted node to output coordinates from layout to 3D.
One thing left to make - handle proportions. it can be achived as coeffitient avarage from every edge length for example. or area coef.
What do you think?
i need to make layout as dxf file. could it be handy? i afraid it have too much theshold deviations. do not know initial code of Unwrapping.

**Comment by zeffii** [comment]
@nortikin, UV is one those things I have zero practical experience with in Blender. Maybe now is time for me to learn :)

**Comment by nortikin** [comment]
i will experiment in modelling, i have my own thoughts of it - algorythm from 5 steps:
1. ordering polygons with order by vertex orientation
2. separate triangles, indexing all
3. define angles on diagonals and polygon' sides
4. find formula to define exact edge length to be unfolded, rolled out.
5. out to 3d

**Comment by Kosvor** [comment]
my attempt:
![23434](https://cloud.githubusercontent.com/assets/7894950/7569366/ebf6298c-f810-11e4-821f-a68e7ff23f8c.png)
cant do polygons this way and every polygon corner outputed as another vertice, so nortikin's way better.

**Comment by nortikin** [comment]
my way not completed fully, will finish later, not now.

**Comment by Kosvor** [comment]
without script node:
![444](https://cloud.githubusercontent.com/assets/7894950/7670289/b7998e72-fca7-11e4-863b-23c0613355a4.png)

**Comment by nortikin** [comment]
Спасибо, Костя )))
