### ISSUE TITLE
custom icons.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#641]
these are now in master, could be work experimenting with getting the right icons in the ctrl+space menu

**Comment by nortikin** [comment]
will try on sunday.
intrigue!!!

**Comment by zeffii** [comment]
![](http://i.imgur.com/dmfyKl4.png)

**Comment by nortikin** [comment]
))) like tinyCAD, use it every day.

**Comment by zeffii** [comment]
I don't imagine anyone wants to make 160 node icons..  But If they did there would need to be a template with lights and materials and render settings, to give all icons a sense of 'togetherness'.

**Comment by zeffii** [comment]
All icons could be generated in one .blend file, using multiple layers. Each layer for the various submenus..

**Comment by nortikin** [comment]
i will do it asap, will spend some time and default for beta node as placeholder. So i can do step by step with placeholders. But now i making ring-on-vertices node and node for unroll, it is hard, i even don't know exact algrythm for second node.

**Comment by zeffii** [comment]
@nortikin recommend you do it in a branch, not master...i've noticed some instability with icons (but can not reproduce confidently a scenario to do bug reports)

**Comment by nortikin** [comment]
ok
