### ISSUE TITLE
Generative Art Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#642]
Cool! Might it be handy to have the text editor update this node too using Ctrl+Enter like ScriptNodes and Profile Node?

**Comment by zeffii** [comment]
@elfnor if you want to add refresh from TextEditor its in `utils/text_editor_plugins`. Else I'll add it eventually.

**Comment by nortikin** [comment]
i found that blender crashes if wrong xml appears

**Comment by nortikin** [comment]
should we have some folder to collect xml for generativeArt node and profile node texts as we have to scripted node? Or maybe just let usercollect locally on his computer? What if new nodes will appear with same functions?

**Comment by zeffii** [comment]
yeah, it crashed on me too on 5000 matrix, totally ground the machine to a stand still - I didn't realize it was going to output that many matrices :)

I find the xml format for L-system confusing, but it looks really interesting based on the results.

**Comment by elfnor** [comment]
Thanks for the comments.

I'll look at the TextEditor refresh stuff

>i found that blender crashes if wrong xml appears.

Oops. I'll look at this as well and hopefully make it exit more gracefully.

> yeah, it crashed on me too on 5000 matrix

It really easy to make more matrices than you expect. I could make the default max matrices a bit lower. My machine handles 5000 cubes but not 5000 of anything with more vertices.

>should we have some folder to collect xml

Definetley, I couldn't work out where to put it in the current structure. I've got a few more examples that I can add to help with understanding the xml format.

**Comment by zeffii** [comment]
@elfnor can you also please confirm that VIewerDrawMK2 now bakes the shear matrix correctly. and BMeshViewerMK2 (the one in beta, not 1) displays (+bakes) them correctly too.

**Comment by elfnor** [comment]
Fixed above issues and generated pull request.

I still don't get shearing baking or viewing properly with the Viz> ViewerDraw2 node or the Beta>BMeshView2 node using the example I gave at the top of the original issue. I thought I had trouble with my versions and branches but I downloaded the zip for the master branch and installed on a fresh machine and still get the wrong result.

Also if I use "Apply Matrix" node to apply the shear matrix to the vertices, the result is different for the Viewer Draw and the Bmesh nodes.

**Comment by zeffii** [comment]
@elfnor unfortunately there's not a lot I can do about that at the moment. I'm waiting for RAM replacement for my main machine. it has gone crazy.

I was under the impression that the VDMK2 displayed the sheared mesh currently but just failed to bake it. My tests did show there was difference there, and the fix seemed reasonable. If you say the VDMK2 doesn't even show the right result from the matrix input, I don't quite understand why that would be.

In any case, until my computer is repaired it won't be possible for me  to investigate..

**Comment by zeffii** [comment]
Also @elfnor please continue the shear matrix discussion in the original thread, it would help if you could give some input there
