### ISSUE TITLE
"Antimony"

### ISSUE THREAD

**Issue by yanivg101** [nortikin/sverchok#665]
Hi all,
Is this ability can be made with Sverchok?
http://www.mattkeeter.com/projects/antimony
It's seem to work faster and easier than OpenSCAD and current Sverchok.

**Comment by zeffii** [comment]
It would be really nice if it could. The thing that makes it faster is the bulk of heavier calculations is done in C++, while most of the UI and 'glue' is done in Python.

Maybe if one day we start including compiled binaries in Sverchok as optional we could get big speed ups and implement 'Functional' representations which are necessary for non polygon based CSG, then yes. I'd love it.
