### ISSUE TITLE
Brussel in April

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#666]
https://github.com/Blender-Brussels/sverchok-workshop
here is conclusions of brussels group that investigated sverchok and made some experience.

**Comment by zeffii** [comment]
such a sadness to see them struggle with features that aren't really our prime motivators for making Sverchok...

**Comment by nortikin** [comment]
maybe lessons was not so clean?
today pened animation nodes and closed it about some time, because don't know where theyr's lessons situates. Maybe to promote lessons on sverchok? or share to blendswap as zipped archive of html files?

**Comment by zeffii** [comment]
I don't know, the manual should be linked more prominently.
