### ISSUE TITLE
updated bootstrap script for non developers

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#669]
```python
import re
import os
import zipfile
import urllib
import json
import bpy
from urllib.request import urlopen

def get_raw_url_from_gist_id(gist_id):
    gist_id = str(gist_id)
    url = 'https://api.github.com/gists/' + gist_id
    found_json = urlopen(url).readall().decode()
    wfile = json.JSONDecoder()
    wjson = wfile.decode(found_json)

    files_flag = 'files'
    file_names = list(wjson[files_flag].keys())
    file_name = file_names[0]
    return wjson[files_flag][file_name]['raw_url']


def get_gist_as_string(gist_id):
    url = get_raw_url_from_gist_id(gist_id)
    conn = urlopen(url).readall().decode()
    return conn

def get_sv():
    print("getting sverchok bootstrapper")
    string_load = get_gist_as_string("5a4440e7455940174ab9")
    
    svbl = bpy.data.texts.new('sverchok bootloader')
    svbl.write(string_load)
    print("obtained bootstrapper code from github")

    # until a tidier solution comes along
    ctx = bpy.context.copy()
    ctx['edit_text'] = svbl # specify the text datablock to execute
    bpy.ops.text.run_script(ctx)
    print("execution bootstrapper complete")

get_sv()
```

**Comment by zeffii** [comment]
tho, this could be truncate even further to: 

```python
import re
import os
import zipfile
import urllib

import bpy
from urllib.request import urlopen


def get_sv():
    url = "".join([
        "https://gist.githubusercontent.com/zeffii/",
        "5a4440e7455940174ab9/raw/",
        "39fcbbd3692da87b920ab48fb2f6c664aca74af4/",
        "bootstrap.py"])

    print("getting sverchok bootstrapper")
    string_load = urlopen(url).readall().decode()

    svbl = bpy.data.texts.new('sverchok bootloader')
    svbl.write(string_load)
    print("obtained bootstrapper code from github")

    ctx = bpy.context.copy()
    ctx['edit_text'] = svbl  # specify the text datablock to execute
    bpy.ops.text.run_script(ctx)
    print("execution bootstrapper complete")

get_sv()

```

**Comment by zeffii** [comment]
apparently this script doesn't work on win10 64 build of Blender. error 'HTTPResponse has no attribute 'readall' .. but works fine on ubuntu64

**Comment by zeffii** [comment]
```
import re
import os
import zipfile
import urllib

import bpy
from urllib.request import urlopen


def get_sv():
    url = "".join([
        "https://gist.githubusercontent.com/zeffii/",
        "5a4440e7455940174ab9/raw/",
        "39fcbbd3692da87b920ab48fb2f6c664aca74af4/",
        "bootstrap.py"])

    print("getting sverchok bootstrapper")
    string_load = urlopen(url).read().decode()

    svbl = bpy.data.texts.new('sverchok bootloader')
    svbl.write(string_load)
    print("obtained bootstrapper code from github")

    ctx = bpy.context.copy()
    ctx['edit_text'] = svbl  # specify the text datablock to execute
    bpy.ops.text.run_script(ctx)
    print("execution bootstrapper complete")

get_sv()
```

**Comment by luckychris** [comment]
i got this error when running on my macbook:

Traceback (most recent call last):
  File "/Users/cd/Downloads/install_sverchok.blend/InstallSverchok", line 34, in <module>
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'sverchok'


Error: Python script failed, check the message in the system console

**Comment by zeffii** [comment]
If you used the "install Addon" button in Blender preferences, then Blender will put the add-on in a system-specific folder.

https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html#platform-dependent-paths

as you use osx, if you get the message `no module named sverchok`, then Blender is not finding a folder named sverchok 
in any of the `scripts` subdirs in https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html#macos

**Comment by zeffii** [comment]
maybe Blender 3.0 needs to be given permissions to modify the filesystem ? else Python can not create a directory to unzip the sverchok source correctly.

**Comment by luckychris** [comment]
Maybe - but why did all other adons work?🙈

**Comment by zeffii** [comment]
beats me.

**Comment by luckychris** [comment]
Or don’t they create folders? I don’t know. You are the expert.

**Comment by zeffii** [comment]
well the bootstrap script will, i think, specifically look in the first addon folder shown in that list, and look for a folder called 'sverchok'. If that folder's `3.0/scripts/addons` doesn't contain a folder called "sverchok" then there's nothing to enable.

for example in windows..

![image](https://user-images.githubusercontent.com/619340/128596475-5a04e94d-84dc-492b-8ba8-056ed0347c5d.png)

**Comment by zeffii** [comment]
it's kind of frustrating to not have access to `macos` in these situations :)

**Comment by zeffii** [comment]
but if you can show the output to system console of that script.. it should look something like : 

```
getting sverchok bootstrapper
obtained bootstrapper code from github
destination directory: D:\b30\blender-3.0.0-alpha+master.99738fbfdc8b\3.0\scripts\addons\sverchok
failed to enable
execution bootstrapper complete
```
I get a failed to enable error,  but it does enable.

**Comment by zeffii** [comment]
the blender API changed slightly in 6 years. i've updated the bootstrapper script, but still testing..

**Comment by luckychris** [comment]
ok, don't know why and don't know how...maybe because i downloaded the newest blender3.0 alpha....but all of a sudden it showed now for the first time the 1.0 version in sverchok and i could enable it. And believe or not ....rendering works too now. But i have no idea why i now could see 1.0 and it worked. Whenever i saw 1.0 version until now, i wasn't able to enable it.

**Comment by luckychris** [comment]
But...(after downloading a fresh 2.93) i got this error, when installing 1.0 beta .....
![image](https://user-images.githubusercontent.com/232549/128596946-d27b4113-70b8-429b-8a08-a8843e2fee76.png)

**Comment by luckychris** [comment]
i don't know if it is interesting for you, just checked the folder structure of 3.0 which works now, it looks like this:

![image](https://user-images.githubusercontent.com/232549/128596984-f1bb8eae-a2d1-441c-988b-796905fcafbb.png)

folder name is sverchok-0 ...i think you ...and i ....didn't expect that. But that's how it works. I did not rename that.

**Comment by luckychris** [comment]
2.93 in comparison to that...(does not work) looks like this:

![image](https://user-images.githubusercontent.com/232549/128597016-973e6817-5d9d-4682-9791-646bd0048c53.png)

**Comment by zeffii** [comment]
rename it to sverchok  , the extra `-1.0.0-beta.2` turns the folder into an invalid module name i think... for the `enable` step

**Comment by zeffii** [comment]
correct, i have no explanation at the moment for the folder being called `sverchok-0` unless that's what happens if you have two folders called `sverchok`, there might be some autorenaming of new folders..

**Comment by luckychris** [comment]
i renamed it. Tried to enable and got: 

![image](https://user-images.githubusercontent.com/232549/128597439-cf12e972-680b-4e80-a4bd-a8ea14079062.png)

**Comment by luckychris** [comment]
i renamed it and tried to enable and got:

![image](https://user-images.githubusercontent.com/232549/128597463-8179439b-3617-4c8e-8d61-bf11fd1cd409.png)

**Comment by luckychris** [comment]
i renamed it and when i tried to enable, i got this:

![image](https://user-images.githubusercontent.com/232549/128597502-be6c9a46-e961-4e77-a1bb-181e36d70631.png)

**Comment by luckychris** [comment]
then i was brave, maybe reckless...and renamed it to sverchok-1...and i got:

![image](https://user-images.githubusercontent.com/232549/128597562-36bda098-d442-4891-8ab7-3515bcdf35ad.png)

now i am feeling ripped....

**Comment by luckychris** [comment]
ok, clean try:

i have:

![image](https://user-images.githubusercontent.com/232549/128597621-0bc42321-1f7b-4ffa-809a-7724ea2d9dc2.png)


after installing and before enabling it looks like this:

![image](https://user-images.githubusercontent.com/232549/128597671-a8227a10-82c4-4a9c-a142-f13097021144.png)

then tried to enable and got:

![image](https://user-images.githubusercontent.com/232549/128597685-ccf23c04-0162-461c-bf85-b379bef4c851.png)

**Comment by luckychris** [comment]
next "clean try" was: renaming it to sverchok BEFORE enabling, same result with "no module named 'sverchok-1' ...it' weird.

**Comment by zeffii** [comment]
if there was no other folder in `scripts/addons` called `sverchok`, then there should be no reason for Blender to automatically rename that folder, this suggests to me that there are parallel folders ( system specific as listed above ) that do have a folder named `sverchok` and blender attempts to avoid name collisions over all the potential folders.

but i'm not certain.

**Comment by luckychris** [comment]
nope, that's why i wrote "clean try" and copied the folder structure. There were no sverchok folders.

**Comment by zeffii** [comment]
well.. now you've seen the dirtier side of add-on development.

**Comment by luckychris** [comment]
I just cannot believe I am the only one with a macOS having this problem….🙈

**Comment by zeffii** [comment]
https://gist.github.com/zeffii/a325ab87931114311198c4571322b82b
