### ISSUE TITLE
IRC channel.  freenode #sverchok

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#674]
Let's get people involved, we can't do this with just 5 people. There must be more people out there that use sverchok and IRC. Hence for a period I will keep `freenode #sverchok` open.

Please spread the word, you can speak in any language you want. Or symbolic 

` node1.socket_out(name) -> node2.socket_in(name)`  or gist IDS for fast passing of information.

**Comment by zeffii** [comment]
this channel is now properly registered to my username, it can transferred if necessary- I think to multiple user names

**Comment by nortikin** [comment]
ok, on weekend i have not comp, so will have fun at monday in irc

**Comment by zeffii** [comment]
i will need to buy new HD (SSD?) and ram for this ancient machine.. 3rd computer to fail on me now

**Comment by nortikin** [comment]
no way, third at 3 monthes?

**Comment by nortikin** [comment]
cannot send message to chat freenode somehow.
```
[22:48] == nikitron_sverch_ [6dbc7d0f@gateway/web/freenode/ip.109.188.125.15] has joined #sverchok
[22:49] <nikitron_sverch_> just to say, i chating from comp last for 3 days. next time will online monday
[22:49] == Cannot send to channel: #sverchok
[22:50] * nikitron_sverch_ cannot chat
[22:50] == Cannot send to channel: #sverchok
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8014593/075cbd0e-0bca-11e5-9103-ba639a44746b.png)
