### ISSUE TITLE
PIE menu experiment for Sverchok node tree

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#675]
yes today I have time for this, maybe it's useful.

start the clock 10:15 3 june 2015

**Comment by nortikin** [comment]
o_O omg

**Comment by zeffii** [comment]
am making some custom icons now to see if that works.. it should

**Comment by zeffii** [comment]
OK, custom icons do not work in property_enums , but do work on regular menu entries. this means a bit more scripting magic to get nice icons in pie menu:)
