### ISSUE TITLE
Shading problem

### ISSUE THREAD

**Issue by milisan** [nortikin/sverchok#680]
Hello,

the shade smooth option for a generated object only works after entering the editing mode.
![shading_problem](https://cloud.githubusercontent.com/assets/12745245/7981289/37ce316a-0aae-11e5-9339-aa57ce388639.gif)

I also try the recalc-normals node, but that doesnt solve the problem.

I hope its my fault and not a bug ;-)

Many Thanks

Patrick

**Comment by zeffii** [comment]
the shading option is on the N panel (external panel) of the bmesh viewer.

![image](https://cloud.githubusercontent.com/assets/619340/7981954/db3e4d2c-0ab2-11e5-81b5-3351c4b4f503.png)

**Comment by zeffii** [comment]
The reasoning behind putting the option on the external panel is that it's not something you need to access repeatedly, set it once and it will continue to work for that node, until un-ticked.

**Comment by milisan** [comment]
Thank You!!!

**Comment by zeffii** [comment]
may I close this now? :)

**Comment by milisan** [comment]
Sure! ;-)
