### ISSUE TITLE
Node Random with range number

### ISSUE THREAD

**Issue by ManlioSca** [nortikin/sverchok#683]
Hello,
i have modified the node Random.
The new node creates random number in a range of two float number.

where do I send the code to let you see?

**Comment by zeffii** [comment]
you cold share a link to a gist, or a fork. But I don't think it's likely that the current Random node will be modifier, it is possible that we do a MK2 (version 2) to avoid older scenes/blends from potentially becoming broken.

**Comment by ManlioSca** [comment]
i think you have right.
i have modified the node for my personal study.
Maybe you can use in the future as the second node type random.

**Comment by ManlioSca** [comment]
https://gist.github.com/ManlioSca/e22a0e2d21213b50c2e6

**Comment by zeffii** [comment]
I would use: http://stackoverflow.com/a/6088092/1243487  `random.uniform(low, high)`

**Comment by zeffii** [comment]
but having said that.. the random node is a great first introduction to programming nodes. welcome :)

**Comment by zeffii** [comment]
and don't use `min, max` as variable names, they are built in python keywords! :)

**Comment by ManlioSca** [comment]
thanks for the tips ;)
