### ISSUE TITLE
Node to eliminate common vertices

### ISSUE THREAD

**Issue by ManlioSca** [nortikin/sverchok#685]
Hello,
i have created this node for my studies:

https://gist.github.com/ManlioSca/ddad4e61ae82443e17b8

with this node we can eliminate all vertices that an object has in common with other objects.
The first input is the object that we want to eliminate the leaders.

I am new to the python and I do not know many functions, so I think that the code is not the best.

**Comment by zeffii** [comment]
don't worry about code, i mean that. If it's a good feature for sverchok we will analyse it and recode if necessary. Thanks for sharing!
