### ISSUE TITLE
Node for remove from a list the elements in position even or odd

### ISSUE THREAD

**Issue by ManlioSca** [nortikin/sverchok#687]
Hello,
always for my studies i have create this node for remove from a list the elements in position even or odd. Can shuffle the list before remove elements
I hope it will serve.

https://gist.github.com/ManlioSca/b26f6f5a7bafe0ef3c07

**Comment by ly29** [comment]
Since list mask already does the dropping of odd or even and we already have a shuffle node I think it is a bit specialized.
