### ISSUE TITLE
Can we make something like that?

### ISSUE THREAD

**Issue by yanivg101** [nortikin/sverchok#691]
Hi,
I wish we have tool to make mesh like that:
http://n-e-r-v-o-u-s.com/blog/?p=6721

**Comment by elfnor** [comment]
This is related, 
<http://elfnor.com/blender-adventures-with-hyperbolic-planes.html>
 in that it makes ruffled surfaces with negative curvature.

Thank you for the link to differential growth, I'll look at the papers, could be my next project.

**Comment by unity2k** [comment]
Awesome Elfnor if you would make the differential growth your next project!!!

**Comment by zeffii** [comment]
feel free to re-open if any progress is made.
