### ISSUE TITLE
Transition Node

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#695]
It's been a while since I've done any Sverchok coding. Formerly this existed only as a Node script, but 
https://github.com/nortikin/sverchok/tree/easing_node

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8634118/d2b8a354-27eb-11e5-963f-a509dc37d223.png)

**Comment by zeffii** [comment]
The idea of the node is to take an input between 0 and 1  and output the value produced by the easing function that was selected.

**Comment by zeffii** [comment]
most of the necessary code is plugged in now, but nothing has been tested yet

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8635349/938e0488-281f-11e5-8f6b-e5c4104651c0.png)

**Comment by zeffii** [comment]
![opt_moving_images](https://cloud.githubusercontent.com/assets/619340/8635370/aa7ec0a0-2820-11e5-9a26-794fa9a0bfd6.gif)

**Comment by enzyme69** [comment]
Thanks Dealga! Oh man I gotta come back to this soon :|

On Sunday, 12 July 2015, Dealga McArdle <notifications@github.com> wrote:

> [image: opt_moving_images]
> <https://cloud.githubusercontent.com/assets/619340/8635370/aa7ec0a0-2820-11e5-9a26-794fa9a0bfd6.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nortikin/sverchok/issues/695#issuecomment-120661413>.
>


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
it might be useful to have a 'duration in frames' and 'start frame'  socket input, meaning before 'start_frame' is reached the output is 0 and during (start_frame...start_frame+duration) it will output the transition between 0...1.

**Comment by zeffii** [comment]
also this needs to be vectorized asap :)

**Comment by nortikin** [comment]
it is usefull for case of animation offcourse and to ease geometry, as experiment could be

**Comment by zeffii** [comment]
https://gist.github.com/a663793209a91310f8410f98673759a8

use this to experiment with easing node

**Comment by enzyme69** [comment]
Thank you very much!!

**Comment by enzyme69** [comment]
![screen shot 2017-01-04 at 21 43 38](https://cloud.githubusercontent.com/assets/3952687/21639926/e0dbe4dc-d2c6-11e6-8dbe-8e96e59fe704.png)

I like the anim visualization and suddenly have that idea above.... Can we actually do that? Connecting random animation of varying easing to get a really weird animation?

Is this similar to the idea of thinking L-Sytem but for animation? 

Because suddenly I am thinking Turtle and animation.

**Comment by zeffii** [comment]
yeah, i'm sure you'll figure it out.. The node might not be vectorized yet :)

**Comment by zeffii** [comment]
here's a zip of image-representations of the easing node's output:

[easing_functions.zip](https://github.com/nortikin/sverchok/files/684502/easing_functions.zip)

one for example:
![0019](https://cloud.githubusercontent.com/assets/619340/21641290/23bc0058-d27b-11e6-9fb2-65b946780680.png)

**Comment by enzyme69** [comment]
![screen shot 2017-01-05 at 18 31 27](https://cloud.githubusercontent.com/assets/3952687/21672237/33e5ac4a-d375-11e6-82f7-6c61733db321.png)

Noob error as above, but I probably need to offset slice the range and then put them together.

**Comment by enzyme69** [comment]
Somewhat the list need to accumulate:

https://gist.github.com/1200172806094870468db25117482b91

![screen shot 2017-01-05 at 18 34 50](https://cloud.githubusercontent.com/assets/3952687/21672291/b0ac4c7a-d375-11e6-8027-4ea256d24bf9.png)

**Comment by enzyme69** [comment]
Wait the minute.... EASE is a function, but unlike SINE it does not continue, so I need to use MODULO maybe?

**Comment by enzyme69** [comment]
Still does not help if I just want to use Grease to draw my Curve bits...

![screen shot 2017-01-05 at 18 44 49](https://cloud.githubusercontent.com/assets/3952687/21672501/162e515a-d377-11e6-827a-a757faf52d64.png)

**Comment by enzyme69** [comment]
https://gist.github.com/b2021815f00247f68b0e0827ca5cb2a8

![screen shot 2017-01-05 at 19 09 59](https://cloud.githubusercontent.com/assets/3952687/21673048/93e9cef0-d37a-11e6-9eb4-322de18ac291.png)

This one I think an improvement.

**Comment by enzyme69** [comment]
I suddently remember EDGE ADAPTIVE node!

![screen shot 2017-01-05 at 19 13 09](https://cloud.githubusercontent.com/assets/3952687/21673111/0945c3d4-d37b-11e6-8ab1-5065f5686cfa.png)

That can be nice, if only we can "Randomize" the input of adaptive edge.... hmm...

**Comment by enzyme69** [comment]
Does Edge Adaptive node take multiple DONOR? Or maybe we need to use List Masking? Hmmm...

![screen shot 2017-01-05 at 19 16 44](https://cloud.githubusercontent.com/assets/3952687/21673181/91b2ea1c-d37b-11e6-9622-414d68e57508.png)
https://gist.github.com/20293f6d11c352b22dbe6f8cc05f21c1

**Comment by nortikin** [comment]
not vectorized yet. now try to make vectorisation

**Comment by nortikin** [comment]
did it

**Comment by enzyme69** [comment]
How does it actually works now that it is Vectorized. Nikitron you are the
Vectorizeman.

**Comment by zeffii** [comment]
https://pbs.twimg.com/media/C3O3vckWcAAVzmU.jpg:large
