### ISSUE TITLE
Auto update before rendering cancel my script

### ISSUE THREAD

**Issue by ManlioSca** [nortikin/sverchok#696]
Hello,

i have a problem with sverchok.

After I create a scene, run a script.
The script attaches two color at the object and the two colors are randomly assigned to faces

Before launching the rendering the scene is updated with the working script (just because step by object mode to edit mode and edit mode to object mode in the script), but once launched rendering some effects of the script disappear.

The faces of the object are colored all with the first material append to him (in this case the red) and the scene in the 3D view is different.

I do not understand if it's a bug of sverchok or I have to disable some function

sverchok + script:
![sv1](https://cloud.githubusercontent.com/assets/12796669/8959790/1e210906-360d-11e5-8e41-f8c1c7f775e0.jpg)

i have press only f12:
![sv2](https://cloud.githubusercontent.com/assets/12796669/8959789/1e1da342-360d-11e5-8226-764511e35c3e.jpg)

the code is very simple:

    import bpy
    import bmesh
    class main():
        
        context = bpy.context
        scene = bpy.context.scene   
                
        scene.objects.active = bpy.data.objects["Camera"]  
        blue = bpy.data.materials.new('Blue')
        blue.diffuse_color = (0,0,1)
        red = bpy.data.materials.new('Red')
        red.diffuse_color = (1,0,0)
        for obj in scene.objects:
            if obj.type == 'MESH':
                obj.select = True
                mesh = obj.data
                mesh.materials.append(red)
                mesh.materials.append(blue)
                
                obj.data.update( calc_tessface = True )
                for face in obj.data.polygons:
                    face.material_index = face.index % 2
                obj.select = False
                
                #only for see the difference
                scene.objects.active = obj
                bpy.ops.object.mode_set(mode='EDIT')
                bpy.ops.object.mode_set(mode='OBJECT')

**Comment by zeffii** [comment]
You are trying to load 'class main()` in a script node? did you read the guide for Scriptnodes?

**Comment by zeffii** [comment]
i'm not sure I can explain to you how this works without you first reading: [The Guide](http://nikitron.cc.ua/sverch/html/nodes/generator/scripted_intro.html#scripted-node-1-an-informal-introduction) i wrote for SN 1

**Comment by zeffii** [comment]
The code needs at least one input before it can acknowledge triggers to update

**Comment by zeffii** [comment]
It seems you want to assign two materials to an object ( but if you repeatedly execute _this_ code you will repeatedly assign the two materials )
You only need to add the 2 materials once. Then in subsequent updates check if the object already has materials ( `len(obj.data.materials)` ) . If you want to then pick different faces for these materials on each update the code you wrote will not do that randomly. So the bug is in your code and unfamiliarity with bpy / scripted nodes

**Comment by zeffii** [comment]
My advice to you is to write a function that you can call repeatedly (from TextEditor as a test ) and make sure it does the following

- add the materials to each object, only 1 time
- prevent subsequent execution of the script from adding the materials if the object already has the material
- assign different colours (materials) to each face at random each time you run the code.

Once you have a function that can do that, then making a scripted node from it is easy.

**Comment by ManlioSca** [comment]
no, i'm not trying to load the class main in the script node.

i've tried with the script node and without the script node (run the script in the text editor after update the scene with sverchok), but the result does not change.

i've read the guide and i created 5 personal nodes for my studies.


As zeffii said:
>The code/node needs at least one input before it can acknowledge triggers to update in a render context

right :)

As zeffii said:
>It seems you want to assign two materials to an object ( but if you repeatedly execute this code you will repeatedly assign the two materials )
>You only need to add the 2 materials once. Then in subsequent updates check if the object already has materials ( len(obj.data.materials) ) . If you want to then pick different faces for these materials on each update the code you wrote will not do that randomly. So the bug is in your code and unfamiliarity with boy / scripted nodes

this is a minor problem, more than anything else is a system resource problem, but i have change the condition:
    
    if obj.type == 'MESH' and len(obj.data.materials)==0:


this script goes when update the node tree, but the problem is the same.
The color on the single face is replaced with the first color append with 'mesh.materials.append()'

    import bpy
    import bmesh


    def colorFun(context,scene):
        scene.objects.active = bpy.data.objects["Camera"]  
        blue = bpy.data.materials.new('Blue')
        blue.diffuse_color = (0,0,1)
        red = bpy.data.materials.new('Red')
        red.diffuse_color = (1,0,0)
        for obj in scene.objects:
            if obj.type == 'MESH' and len(obj.data.materials)==0:
                obj.select = True
                mesh = obj.data
                mesh.materials.append(red)
                mesh.materials.append(blue)
                obj.data.update( calc_tessface = True )
                for face in obj.data.polygons:
                    face.material_index = face.index % 2
                obj.select = False
                
                
    def sv_main(v=[]):
        context = bpy.context
        scene = bpy.context.scene   
        verts = []
        in_sockets = [['v','verts', [v]]]
        out_sockets = [['v','verts', [v]]]
        v = in_sockets
        colorFun(context,scene)
        return in_sockets, out_sockets

**Comment by zeffii** [comment]
maybe this is what you want..
```python
import bpy
import bmesh


def get_material(named):
    materials = bpy.data.materials
    m = materials.get(named)
    if not m:
        # only set diffuse once.
        m = materials.new(named)
        m.diffuse_color = {'Blue': (0,0,1), 'Red': (1,0,0)}.get(named)
    return m


def colorFun(context,scene):
    
    scene.objects.active = bpy.data.objects["Camera"]  
    
    blue = get_material('Blue')
    red = get_material('Red')
    
    for obj in scene.objects:
        if obj.type == 'MESH' and len(obj.data.materials)==0:
            mesh = obj.data
            mesh.materials.append(red)
            mesh.materials.append(blue)
            for face in obj.data.polygons:
                face.material_index = face.index % 2

    scene.update()


def sv_main(v=[]):
    context = bpy.context
    scene = bpy.context.scene   
    verts = []
    in_sockets = [['v','verts', [v]]]
    out_sockets = [['v','verts', [v]]]
    v = in_sockets
    colorFun(context,scene)
    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/8967001/a42cb7a8-3634-11e5-8797-53a943f0e875.png)

**Comment by ManlioSca** [comment]
have you tried the rendering?

when rendering the scene, the cube has always one color

**Comment by zeffii** [comment]
disco! 
```
def colorFun(context,scene):
    
    scene.objects.active = bpy.data.objects["Camera"]  
    
    blue = get_material('Blue')
    red = get_material('Red')
    
    for obj in scene.objects:
        if obj.type == 'MESH' and len(obj.data.materials)==0:
            print('setting different colors')
            mesh = obj.data
            mesh.materials.append(red)
            mesh.materials.append(blue)
        if obj.type == 'MESH' and len(obj.data.materials) == 2:
            for face in obj.data.polygons:
                face.material_index = random.randint(0,1)

    scene.update()
```

**Comment by zeffii** [comment]
![frost](https://cloud.githubusercontent.com/assets/619340/8967538/d41af7f6-3637-11e5-9ee2-b6966bf4e92b.gif)

**Comment by zeffii** [comment]
each frame the code you wrote was setting the material_index exactly the same as the last frame.. proven by the code I show here that if you introduce randomization that the code works ..

**Comment by zeffii** [comment]
maybe i'm misunderstanding your question?

**Comment by ManlioSca** [comment]
It was not exactly the problem but I realized :)

I think I'm missing something for me to understand completely sverchok...

at least I knew that everything must be done in sverchok, if not at the time of rendering everything resets.

Thx for the help, my bad! ;)

**Comment by zeffii** [comment]
I can't say I agree with your assessment -- I think your gap in knowledge is more centered in `bpy` , of which Sverchok is a mere extension itself.

To trigger something every frame did require an input (i used `scene - Frame Node ` current frame input , anything works..)

**Comment by zeffii** [comment]
but the rendering could be a frame behind, depending if you use Frame change handler `pre` or `post`
![image](https://cloud.githubusercontent.com/assets/619340/8968014/136b7798-363b-11e5-9c31-20299a6e2bb2.png)

I don't think sverchok provides a good way to deal with material updates...  it's not something we've focused on. So if it works in unexpected ways it is because it has been given little attention.

**Comment by zeffii** [comment]
We don't have a swtich to defer update of a node until after a designated other node is executed, for example if would be great if a node like Scripted Node had a switch to update after all Viz - Bmesh nodes... so it would affect the latest created mesh before frame render.

**Comment by zeffii** [comment]
So if that's what you meant, then yeah - sorry about that .. it is a primitive tool in some sense.

**Comment by zeffii** [comment]
we already had experiments with a BMesh node that had one output, so anything attached to that would update _after_ the bmesh node..
