### ISSUE TITLE
interpolation node

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#699]
@ly29 i remember you made vector interpolation node. people (in G+) ask me to implement in mk2 normal definition. what i thought. We have this part https://github.com/nortikin/sverchok/blob/master/nodes/vector/interpolation_mk2.py#L154-L155 and if we can find tangent to every point than we can find tangents on both directions flipped and not, than we can find matrix rotation based on this two vectors-tangents, it will be as normal, ineed we can in one node realize many things to work later on. When generating from interpolation node we get normal, matrix on point position and grid for uvconnect node.
The question for you is next - can you find tangent when finding point?

**Comment by nortikin** [comment]
and needed close case for spline

**Comment by ly29** [comment]
It is quite easy to do numerically. The closed case shouldn be to much work.

**Comment by ly29** [comment]
But finding time

**Comment by nortikin** [comment]
i changed node some, hope you like it, but need solution on normal/tangent

**Comment by ly29** [comment]
The tanget is easiest done for t ```f(t)=x,y,z``` as ```f(t+h)-f(t-h)``` where ```h=0.001``` or something like that. perhaps ```f(t+h)-f(t)``` would be good enough.

```python
                spl = cubic_spline(v, t)
                out = eval_spline(spl, t, t_corr)
                h = 0.001 # maybe should be controllable in the side panel
                t_h = eval_spline(spl, t - h, t_corr)
                t_ph = eval_spline(spl, t + h, t_corr) 
                tangents = t_h - t_ph # okay they are not numpy arrays but you get it
                # also an option for normalizing the tanget vectors could be nice
                
```
Except that the curve does not eval outside of t=0 and t=1 which gives some nice corner cases to deal with.

**Comment by ly29** [comment]
@nortikin 
Slightly more tricky than outlined but done for linear case vector interpol mk3
For surface I think a separate node is better since the outputs are different with normal, u and v tangents etc.
See interpol_np branch https://github.com/nortikin/sverchok/tree/interpol_np

**Comment by ly29** [comment]
![skarmavbild 2015-09-03 kl 10 27 08](https://cloud.githubusercontent.com/assets/6241382/9653799/6049fd8a-5226-11e5-8962-cb7e0c80d552.png)
![skarmavbild 2015-09-03 kl 10 31 45](https://cloud.githubusercontent.com/assets/6241382/9653890/03a3b17e-5227-11e5-8dd8-13a199a825ed.png)

**Comment by ly29** [comment]
Norm tanget is the normalized tanget, tanget is not normalized.

**Comment by ly29** [comment]
Next is cyclic case...

**Comment by ly29** [comment]
actually spent some time on bumpy instead, it is fun.
eval function is totally numpy now. no ```for``` loops.
in preliminary testing it is about 10x times faster.

```python
def eval_spline(splines, tknots, t_in):

    index = tknots.searchsorted(t_in, side='left') - 1
    index = index.clip(0, len(splines) - 1)
    to_calc = splines[index]
    ax, bx, cx, dx, tx = np.swapaxes(to_calc, 0, 1)
    t_r = t_in[:,np.newaxis] - tx
    out = ax + t_r * (bx + t_r * (cx + t_r * dx))
    return out
```

do you like it @zeffii ?

**Comment by zeffii** [comment]
I only just got notified about this now. Yes!!  but I can't claim to understand either without dissection..  great news about the speedup.  More proof that numpy is a viable step towards terse and faster code. 

I think the increase in difficulty of comprehension is justified by these gains.

**Comment by ly29** [comment]
it is a valid point, proper documentation for the techniques used is important...

**Comment by ly29** [comment]
![skarmavbild 2015-09-05 kl 08 03 50](https://cloud.githubusercontent.com/assets/6241382/9697977/af58c5f8-53a4-11e5-9a83-10ab5abc3754.png)
```
Linear case
Processed  Vector Interpolation 3 in: 0.0412
Processed  Vector Interpolation in: 0.1642
Cubic case
Processed  Vector Interpolation 3 in: 0.0978
Processed  Vector Interpolation in: 1.0242
```
With big number of points to test eval mostly.

**Comment by zeffii** [comment]
that's a major boost for the node!

**Comment by nortikin** [comment]
i really not understand why we need two nodes? i try to unificate as uvconnection node.
Cases we will have:
1.U interpolation with tangents output in one direction
2.UV interpolation with tangents in two directions and normals. (+2 additional sockets)
That is it.
nice job, Linus. I wish to understand math as you do. At least i see you understand what you are doing with numpy to this node... T-T

**Comment by ly29** [comment]
Maybe it is not necessary, for me it conceptually simpler to consider them like that. 
In general I rather avoid juggling sockets. 

But first I will do cyclic case and factor out the actual code for the spline. Also worth considering is different metrics for construction of the knots.


Re numpy the node was doing some rather stupid things before which slowed it down.

**Comment by ly29** [comment]
Started refactoring out the spline code from the node and made the spline creation function use more numpy. The node seems quicker overall varying from 10x (and more) to 2x but havn't done any serious performance work yet of testing different solutions and alternatives.

I wonder if expressions like these are possible to make into array expressions however. 
```python
    for i in range(n-2, -1, -1):
        c[i] = z[i] - u[i]*c[i+1]
```
Where we calc an value which each depends on a previous one. Not that critical but would be nice.

**Comment by nortikin** [comment]
must be numpy has shift

**Comment by nortikin** [comment]
lets define than
if we make just one direction node, than i will make both directions node that i made mk2, but with socket norm/tang that means normal/tangent
And we will have one node with both cases without lost sockets.

**Comment by nortikin** [comment]
i think noone will loose from combined node.

**Comment by ly29** [comment]
![splines](https://cloud.githubusercontent.com/assets/6241382/9755583/6bb09cd6-56d3-11e5-9dc3-d059f963397c.png)
Play around with different distance metrics and ugly cyclic hacks

**Comment by zeffii** [comment]
@ly29  regarding numpy for 

```python
    for i in range(n-2, -1, -1):
        c[i] = z[i] - u[i]*c[i+1]
```

perhaps stackoverflow?

**Comment by ly29** [comment]
My intuition says something like below should work, but it does not. But then we are far from easily readable code which also might explain why it does not work, some subtle bugs. Will ask for it.
```
    c_c[-2::-1] = z[-2::-1] - u[::-1] * c_c[-1:0:-1]
```

**Comment by ly29** [comment]
It isn't possible, the reason being that each part of the expression is computed sepepartly then done together.
```
tmp0 = u[::-1] * c_c[-1:0:-1]
tmp1 =  z[-2::-1]  - tmp0
c_c = tmp1
```

http://stackoverflow.com/questions/1587367/python-numpy-tricky-slicing-problem?rq=1

**Comment by ly29** [comment]
Now cyclic is working, might get strange results with cyclic with less than 4 points though...
Please test.

**Comment by nortikin** [comment]
https://yadi.sk/d/jbea5Aj9izWoM
tangent not correctly calculated or cross product used wrong way?
and flipped interpolation not makes cycled calculation... why is it happened?

**Comment by ly29** [comment]
Cyclic is a done in a hacky way where we extend the interpolation with four points on each side.
```python
pts = np.array(v[-4:] + v + v[:4])
```
Then the respective knot or t value in the function ```f(t) = x, y, z``` which is uually scaled from 0 to 1 is rescaled so 0 and 1 happen at the start/end point even though the function extends beyond this point.

So some extra math.

@nortikin 
I will take a look at that as soon as I can. Not today though.

**Comment by ly29** [comment]
Can access blender right now but if you post a picture of the relevant part of the layout I can try to guess.

**Comment by nortikin** [comment]
![interpol tangent blend](https://cloud.githubusercontent.com/assets/5783432/9793793/fde4e7b6-57ef-11e5-9e21-6bde645825cc.png)

@ly29

**Comment by nortikin** [comment]
tangents are ok, but first tangent has 3 objects, second 25, we have cross product between different lists

**Comment by ly29** [comment]
Yeah, try to join the list of vertices.

**Comment by nortikin** [comment]
first list or second?

**Comment by nortikin** [comment]
joined as in your image, the same with normals

**Comment by ly29** [comment]
The normal outputs, both, my image worked because of a perfectly symmetrical grid.

**Comment by nortikin** [comment]
in case of only U  interpolated node no need to give normal, but tangent

**Comment by nortikin** [comment]
great node. becomes maybe one of basic nodes to use

**Comment by nortikin** [comment]
looking at interpolation node i will think of numpying vector field node... it will be great.

**Comment by zeffii** [comment]
and math and vector math node :)

**Comment by ly29** [comment]
Yeah, I think this is my last effort for 0.5 Sverchok, future time will be spent on Redux

**Comment by nortikin** [comment]
this will work for redux also, when it will

**Comment by ly29** [comment]
exactly, this was numpy exercise before that. This isn't quite finished but now all the hard parts are in place. I think

**Comment by nortikin** [comment]
https://gist.github.com/nortikin/62ab77fc818acc6b0bd5
just trying to handle numpy. Normalized vectors with np

**Comment by ly29** [comment]
If that makes sense depends on the object, I guess, but for bonus points use the ```vertices.foreach_get``` methods for getting the data in numpy, it is 2 orders of magnitude quicker.

**Comment by nortikin** [comment]
:+1:

**Comment by zeffii** [comment]
we now have good interpolation nodes :)
