### ISSUE TITLE
Can't install in 2.75

### ISSUE THREAD

**Issue by limor1** [nortikin/sverchok#704]
getting error on line 115 of `__init__.py`
    `for category, names in nodes.nodes_dict.items():`

NameError: Name 'nodes' is not defined

**Comment by Kosvor** [comment]
You're using the latest version of the master? in my version 2.75.3 it works well

**Comment by nortikin** [comment]
каждый раз эта ошибка выползает. Как названа папка? sverchok или sverchok-master?
Удали старую версию, установи с гитхаба с нуля, проблем ыть не должно на блендере 2,74+.

**Comment by ekammerloher** [comment]
I guess I have the same issue. Blender v2.75a, sverchok 0.5.2.5 on OS X.

I followed @nortikin changed README manual installation instructions.
Restarted blender. Did the equivalent of 'Activate flag beside sverchok' in the console to get a traceback:

```python
bpy.ops.wm.addon_enable(module='sverchok-master')
```

I run this two times and get [this tracebacks](https://gist.github.com/ekammerloher/e0d993804f7aa453a911).

First error:
`
ImportError: No module named 'mathutils.bvhtree'; 'mathutils' is not a package
`
Second error:
`
NameError: name 'nodes' is not defined
`

**Comment by limor1** [comment]
I'm running 2.75a on Windows

**Comment by nortikin** [comment]
guys, did you removed and deactivates previouse sverchok completely? from ~/scripts/addons sverchok folder and deactivate flag from CTRL+U
I never used osx, so try rename folder to sverchok. We have this lines https://github.com/nortikin/sverchok/blob/master/__init__.py#L65-L66 but they seems work not always, and other lines as https://github.com/nortikin/sverchok/blob/master/__init__.py#L114 this do not find any folders. just try foldername "sverchok"

**Comment by nortikin** [comment]
strange.

**Comment by limor1** [comment]
Extracted all files into a directory called sverchok and now seeing 2 lines
in crtl-alt-u add-ons.
One gives error:
Importerror : module sverchock-master not in modules

The other gives the 2 consecutive errors as described by ekammerlohr

**Comment by Kosvor** [comment]
mathutils.bvh tree perhaps doesn't exist in blender prior to 2.75.3
I remove the nodes that use it

**Comment by limor1** [comment]
I've uninstalled 2.75a and installed the nightly build 2.75.4 (https://builder.blender.org/download/)
sverchok installed without any errors!
