### ISSUE TITLE
render handler

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#732]
We have missing thing - when rendering frame changing not affects on crop border (alt+b, ctrl+b), it renders all the same.
Need as frame change handler also render handlers.
Donno when will do so, people asked. or maybe it will not work? what is wrong than?

**Comment by zeffii** [comment]
I don't know what you mean, can you make an example .blend ?

**Comment by nortikin** [comment]
@zeffii SOME investigations went me to this script https://github.com/RayMairlot/Animated-Render-Border/blob/master/animatedRenderborder.py wich makes extra handler-manipulations to change render border in scene, so it will render using this border, not only animate it. Render mechanics different from animation as i see now.
`from bpy.app.handlers import persistent`
`def updateFrame(self,context):`

**Comment by zeffii** [comment]
ok, that addon adjusts the render border depending on the camera target and how much of the target is visible. A problem may be that one addon updates before the other. Either sverchok before Renderborder.py or Renderborder.py before Sverchok. If sverchok is updated before render border then the border will reflect correctly the active data, if it's after then... never going to be OK.

I don't think there's a way to specify ' please update this handler at the last possible moment before framechange `.

**Comment by zeffii** [comment]
it may be more appropriate for us to provide a version of that addon / or something analogous -- that works well with Sverchok, rather than changing Sverchok to work with Renderborder.py

**Comment by nortikin** [comment]
nonono, this addon is key to solve problend in Sverchok. sverchok cannot change border if you render. it can animate border, but when render, sverchok powerless. I want to fix it

**Comment by zeffii** [comment]
but that addon drives the animation, by doing `current_frame += 1` . it doesn't follow the animation, it makes it.

**Comment by nortikin** [comment]
ok, i see.
anyway blender has not such possibility to handle this border. Why?
And maybe we can bring object in node to scene update handler, what do you think? So if you change some geometry it will affect object in node.

**Comment by zeffii** [comment]
it's definitely interesting to think about. I did already write a script-node that adjusts render border.. but it wasn't automatic...

**Comment by nortikin** [comment]
i did the same after you, not finding your SN, and impacted the same problem.
