### ISSUE TITLE
viewer draw to recognize edges and polygons for every object

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#735]
If edges in one object, than polygons in other, viewer draw has to understand each time, not generalize case.
i.e. to output objects that have edges and polygons at once or one object polygons, other edges.

**Comment by zeffii** [comment]
like:
```python
object1 = [verts, edges, faces]
object2 = [verts, None, faces]
object3 = [verts, edges, None]
object4 = [verts, None, None]
obj_list = [object1, object2, object3, object4]
obj_list > viewer_draw
```
![image](https://cloud.githubusercontent.com/assets/619340/17474245/46880a1e-5d55-11e6-8cb7-85e14c15a3c5.png)

**Comment by zeffii** [comment]
I don't recall any serious issue that would prevent that from making its way into the code, furthermore if the lists for Vertex/edges/faces are all of the same length, none of them should be extended with FullList anyway.. but it's been a long  time since writing that code to be sure.

**Comment by nortikin** [comment]
this idea better for redux to define how we deal with data (naturally to deal as it is in blender itself i guess)

**Comment by zeffii** [comment]
unless someone has time for this i think it's OK to close this issue for now.  Blender 2.8 will bring some interesting solutions, along with a new renderer PyGLSL.

this is not forgotten.
