### ISSUE TITLE
Boolean Branch

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#736]
http://download.blender.org/ftp/ideasman42/donelist/2015.html#week-271-october-26

ideasman42 is putting more work into Bmesh booleans branch, this means `bmesh.ops` too! This would open up a new world of much faster booleans in sverchok. I'll be happy to rip out the internals of the existing boolean node.

**Comment by nortikin** [comment]
yeah, now is too slow. As Sverchok overall is without numpy. yesturday one told me that animation nodes faster to animate than Sverchok, and he choosed AN.
Boolean is cool!

**Comment by zeffii** [comment]
When people try to compare Sverchok to AN for animation.. it's mostly unfair. It's like comparing a 24 wheel construction crane versus a Ferrari, and complaining that the construction crane can't go as fast. Sverchok is meant for building things, not driving people around fast.

Sverchok's architecture and nodes were never developed with high realtime framerate in mind, or to even be particularly convenient to animate / bake with. AN was developed with that in mind, and it should be no wonder that it does that exceptionally well.

I'm starting to wonder if the REDUX could be split into two phases. 

- First solve the nodification of numpy, and add maybe 2 new socket type ( np arrays, and composite np objects (all flat list descriptions of mesh objects, verts, vertgroups, faces, edges, vertexcolors, face colors, weights..whatever)) . 
- Then update the execution model (this doesn't bother me as much as it seems to bother @ly29 )

separating the two phases could help show what the individual speed ups are. I don't mean this to be a distraction, I just don't seem to find the time for coding anymore.. :(

**Comment by ly29** [comment]
@zeffii 
It does bother me deeply, mostly because the bigger possibilities with a refined execution model.

**Comment by ly29** [comment]
Also yay for better bmesh tools.

**Comment by nortikin** [comment]
execution model for me is dark matter.
Also first of all definitions working with numpy flat array. 

i.e. how you will flatten this?:
``` python
import numpy as np
import bpy

meshdata = [o.data for o in bpy.context.selected_objects]

def NumPy_read_object(meshdata):
    vertices = np.array([[v.co for v in o.vertices] for o in meshdata])
    edges = np.array([[e.vertices[:] for e in o.edges] for o in meshdata])
    polygons = np.array([[p.vertices[:] for p in o.polygons] for o in meshdata])
    return vertices, edges, polygons

print(NumPy_read_object(meshdata))
```

**Comment by nortikin** [comment]
definetly np.shape should present, but we need complete polygons solution, not only for cubes and np.shape not fits this goal
so, every time we change shape of flat array we need rebuild this indeces... to interact with current generators and so on, we need to convert this arrays. painful till we finish redux...

**Comment by nortikin** [comment]
this is the way too
array([array([ 1.,  2.,  3.]), array([-2.,  4.]), array([
5.])], dtype=object)

**Comment by nortikin** [comment]
from here http://numpy-discussion.10968.n7.nabble.com/Accessing-irregular-sized-array-data-from-C-td37833.html
```
another thing, don't use int as the index to the array, use npy_intp
which is large enough to also index arrays > 4GB if the platform
supports it.

Also note that object arrays are not very well optimized in numpy, so
numerous operations can be slow. 
```

**Comment by nortikin** [comment]
hmmm
is it working allready?
```
array([[[ 4.3131671 ,  3.37275887, -0.69085413],
        [ 4.3131671 ,  1.99105072, -0.69085413],
        [ 2.93145895,  1.99105072, -0.69085413],
        [ 2.93145919,  3.3727591 , -0.69085413],
        [ 4.31316757,  3.37275863,  0.69085413],
        [ 4.31316662,  1.99105024,  0.69085413],
        [ 2.93145871,  1.99105096,  0.69085413],
        [ 2.93145895,  3.37275887,  0.69085413]],

       [[ 1.        ,  0.99999994, -1.        ],
        [ 1.        , -1.        , -1.        ],
        [-1.00000012, -0.99999982, -1.        ],
        [-0.99999964,  1.00000036, -1.        ],
        [ 1.00000048,  0.99999946,  1.        ],
        [ 0.99999934, -1.0000006 ,  1.        ],
        [-1.00000036, -0.99999964,  1.        ],
        [-0.99999994,  1.        ,  1.        ]]]), 

array([ [(0, 1), (0, 3), (0, 4), (1, 2), (1, 5), (2, 3), (2, 6), (3, 7), (4, 5), (4, 7), (5, 6), (6, 7), (1, 3), (4, 1), (5, 2), (6, 3), (0, 7)],
       [(0, 1), (0, 3), (0, 4), (1, 2), (1, 5), (2, 3), (2, 6), (3, 7), (4, 5), (4, 7), (5, 6), (6, 7)]], dtype=object), 

array([ [(1, 2, 3), (4, 5, 1), (5, 6, 2), (6, 7, 3), (0, 3, 7), (0, 1, 3), (0, 4, 1), (1, 5, 2), (2, 6, 3), (4, 0, 7), (4, 7, 6, 5)],
       [(0, 1, 2, 3), (4, 7, 6, 5), (0, 4, 5, 1), (1, 5, 6, 2), (2, 6, 7, 3), (4, 0, 3, 7)]], dtype=object)

```

**Comment by nortikin** [comment]
Than we can find this shape in recursion mode? or we not need this?
If irregular numpy arrays possible now, what we can do with them? first of all we need know depth of tree to predict recursion cycles without np.shape... hm. Or to find own way, but this much more of head ache.

**Comment by nortikin** [comment]
We have template menu now

**Comment by zeffii** [comment]
if we chose to use irregular arrays, then there is no gain to be had from using numpy. This is unfortunately an unchangable fact. I understand the need for grouping verts (for rings, slices...). But let's not forget that a lot of geometry doesn't need those at all, so I don't fully understand why we shouldn't consider the fastest method when it's not complicated. We can always add complexity, but it will likely not give the numpy boost.

Luckily for us, most irregular structures that we might need for geometry and topology can be described using a number of simpler structures. @nortikin I recall showing how something like that is done a couple of months ago.

**Comment by nortikin** [comment]
+1 :cry:
