### ISSUE TITLE
considering an inter nodegroup communicator node "Node Remote"

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#737]
![image](https://cloud.githubusercontent.com/assets/619340/11062564/334f33ee-87b0-11e5-8e81-e5f6aeed3317.png)

https://github.com/nortikin/sverchok/blob/node_remote/nodes/basic_data/node_remote.py

needs a lot of work, but the basics already exist in the Set/Get property node.. so. When someone finds time :) We could offer this as a convenient communication path to Animation Nodes node tree.. Maybe offer input / output as two modes of the single node.

**Comment by zeffii** [comment]
outputs: bpy.data.node_groups[1].nodes[2].outputs[0].getValue()

**Comment by zeffii** [comment]
```python
from nodes.basic_data.getsetprop import assign_data, wrap_output_data, types
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/11066739/ae464470-87c9-11e5-8bed-7fa50932b44e.png)

**Comment by nortikin** [comment]
great idea.
i will have time on weekend, will look.
Thanks!

**Comment by zeffii** [comment]
also AN guy made new node today too for data exchange: http://animation-nodes-manual.readthedocs.org/en/latest/dev_guide/data_interface.html

**Comment by zeffii** [comment]
@enzyme69 

A small recap. There are two scenarios. 
```python
SV => AN
AN => SV
```
and four possible nodes
```python
SV_SETS_AN 
AN_SETS_SV

SV_GETS_AN
AN_GETS_SV
```

An SV node setting the value of an AN node is the almost the same as having an AN get a value from SV node. Essentially the same -- but with subtle differences, execution order most notably.

As far as i remember, for Scripted node to update, it requires at least one connection on the output. This is kind of an arbitrary limitation due to the SN starting out as a generator node, which didn't need to process until it have sockets connected to the output.

**Comment by zeffii** [comment]
i imagine it's possible to make both SV and AN shit bricks by doing something like this. Where the color of the background indicates that SV is communicating with AN , but it doesn't matter which is which. Cyclic update loop seems possible, but difficult to avoid if you are not careful.

https://gist.github.com/zeffii/2a49db1c41497515e459

**Comment by zeffii** [comment]
You might never experience it, and I don't have time to experiment :)

**Comment by nortikin** [comment]
@zeffii 
assign_data(named_input.value, data)
value is not exists... how to call?

**Comment by enzyme69** [comment]
I downloaded latest Sverhcok and could not find "SV Node Remote".

**Comment by nortikin** [comment]
@enzyme69 because it is on branch node_remote. It is ok

**Comment by Bearmod** [comment]
Yes please! This would be amazing.

**Comment by zeffii** [comment]
This node is now added to the beta nodes as `Node Remote (control)` it is not tested at all. 

But !  you can ignore the color of the Socket dot, it should just accept any useful socket.

**Comment by zeffii** [comment]
this is far from being a useful node.. hence beta

**Comment by zeffii** [comment]
implementing the dynamic socket kind will at least show users what kind of socket to feed the node...

**Comment by Bearmod** [comment]
Excellent! I'll try it out this week.

**Comment by zeffii** [comment]
don't get your hopes up. @Bearmod  the `set props` and `get props` node are already great. And i'm too lazy to do anything with this _convenience_ feature..

**Comment by zeffii** [comment]
we need someone who not only wants this, but can invest their own time into adding the required conversion scheme. currently it's low priority and it seems like get and set props nodes can already be used for most stuff.
