### ISSUE TITLE
blenders's BGL is now 3.1 what does that mean for Sverchok

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#738]
i'm wondering can we make GLSL and VBO's now. Anyone tried yet?

**Comment by nortikin** [comment]
did not know. before we used version 1?
Did not concerned GLSL.
I'd like ofcourse to use in viewer node mk3,4,5... GLSL but did not find how is better to communicate. we need material or color socket indeed

**Comment by nortikin** [comment]
@zeffii i'd broke Centers of polygons node, UVconnect and some others without back compblty half a year ago. What you thing better is to leave as it is or roll back and make properly mk2's?

**Comment by ly29** [comment]
@zeffii 
Know any good primers on them?

**Comment by zeffii** [comment]
@ly29 nope, but I can imagine some cool things will be possible.

**Comment by zeffii** [comment]
also new updates to bgl 
https://developer.blender.org/rB5cbc7b6ed29645d793e813fab374add4e11fa4c7
