### ISSUE TITLE
SV Instancer Node does not update as expected

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#739]
![screen shot 2015-11-14 at 12 59 45 pm](https://cloud.githubusercontent.com/assets/3952687/11162325/9d1b07fe-8acf-11e5-8fac-1b0363894f97.png)

I tested this SV Instancer Node, maybe I am not so familiar with it yet. But I recall some Sverchok knowledge, I believe I only need to supply vector information in order for it to generate Matrix for Instance Clone Copies.

I tested using Lines and Grid, and both of them do not seem to update as expected.

**Comment by enzyme69** [comment]
For example: changing N Verts, then Step value, I expect it to update also in 3D view, but looks like the Step value only respected when NVerts is changed.

**Comment by zeffii** [comment]
have been tempted to make it do face duplication, that would give rotation+scale+location, but mean it would need to generate triangles with orientation and size for every vertex passed.

I'll have a look @enzyme69

**Comment by zeffii** [comment]
not sure what I was thinking when implementing the Sv Instancer node that way... a dupliverts approach would be a lot better.

**Comment by zeffii** [comment]
oh I see I did make some attempt at a duplivert node... let met try an repair and that perhaps remove the sv_instancer node, as it is slow/clumsy in comparisson. (sv instancer is slow because name collision checking is slow as hell)

**Comment by zeffii** [comment]
I see why SvInstancer is failing. It isn't a very smart node. It seems (and will probably show by looking at the code) that It doesn't update if the number of vertices hasn't changed between updates. If you tweak the vertex locations and the number of vertices being fed into the Sv Instancer it will udpdate. This is hardly obvious so yeah, definitely a bug... But you are probably the only one who has used it ..ever :)

**Comment by zeffii** [comment]
I would prefer to remove this node and replace it with an alternative.

**Comment by zeffii** [comment]
I would prefer to remove this node and replace it with an alternative.  https://github.com/nortikin/sverchok/tree/dupli_instances

**Comment by zeffii** [comment]
I'm not sure why the sv instancer node doesn't work at the moment. Either I stopped coding it for exactly this reason, or it became broken through other changes and wasn't tested.  I don't know :)

**Comment by zeffii** [comment]
like this: 
![image](https://cloud.githubusercontent.com/assets/619340/11168229/2178fba8-8b86-11e5-9f71-ef05e7e14156.png)

**Comment by zeffii** [comment]
i'm slightly rusty with regards to Sverchok specific code, perhaps @nortikin and @ly29 can check the code and commit improves. I also vote to remove the SvInstancer node.

**Comment by ly29** [comment]
Also slightly rusty. Thrust your judgement about the instancer noder

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/11168561/25c27244-8b94-11e5-832f-a763f4362670.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/11168569/869f0b7c-8b94-11e5-831b-48acb70ee00d.png)

**Comment by zeffii** [comment]
Closing this issue. The SvInstancer node is now removed from Sverchok.

**Comment by nortikin** [comment]
i fixed some code that was somehow broken, not sure why it is. Poltergeist

**Comment by zeffii** [comment]
@nortikin  you  fixed the update of SvInstancer ? Maybe I should not have removed it..,

**Comment by nortikin** [comment]
no, i didnt. I mean, something went wrong, somewhere several nodes was broken. I fixed couple, but backword compability is not ok.

**Comment by zeffii** [comment]
adding back shortly, will fix the update issue.

**Comment by zeffii** [comment]
I've added the node back and it uses an explicit data.update() which seems to be necessary for the matrix to take effect. Not sure why this is the case, and @ly29 will probably not be happy, but for now it serves a purpose.. unless a nicer alternative presents itself.

**Comment by ly29** [comment]
Well, I'm looking forward so not so worried about that.
Will take a look anyway.

**Comment by zeffii** [comment]
it seems simply assigning a matrix to an object which is a user of a mesh that other objects use, needs an extra nudge? I can't logically explain why this should be the case, but there must be a logical explanation.
