### ISSUE TITLE
Dupli Instances  (node) prelim docs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#740]
This is a simple node so far. It's simplicity makes it stable as far as I can tell. The idea is as follows:

The Node works in two ways. One mode accepts just Locations, the other mode accepts just Matrices.

 - If Locations are passed (vectors), then the node generates a proper blender mesh, based on vertices. The duplication is set to `VERTS`.
 - If Matrices are passed, the node generates a vertex+face mesh using the transforms contained in individual matrices. First it makes a unit 1 triangle, then multiplies the vertex coordinates with a matrix. This is done for each of the passed matrices. Passing 4 matrices, makes 4 triangles : a total of 12 verts and 4 faces. The duplication is set to `FACES`.
- You pick the child Object from the UI.

The name of the internal parent object in this example is 'booom' , but this can be changed and should probably be node specific. 

![](https://cloud.githubusercontent.com/assets/619340/11168229/2178fba8-8b86-11e5-9f71-ef05e7e14156.png)

![](https://cloud.githubusercontent.com/assets/619340/11168561/25c27244-8b94-11e5-832f-a763f4362670.png)

![](https://cloud.githubusercontent.com/assets/619340/11168569/869f0b7c-8b94-11e5-831b-48acb70ee00d.png)

thoughts on improvements:

- hash the `.self` to append to desired parent name.

**Comment by zeffii** [comment]
unfortunately this only allows for uniform scaling, by this I mean that duplicates can only be scaled in 2  dimensions. This is a limitation of Blender's duplication code that treats each face as a reference for location, orientation and scale, the problem is that faces are only two dimensions,

**Comment by zeffii** [comment]
maybe It should offer a Particles mode

**Comment by nortikin** [comment]
Why blender limits duplicat's scale?

**Comment by zeffii** [comment]
Perhaps because duplifaces use the face area to scale the duplicate, and area is a 1d value. I think even the same is true for particles. it's a pitty!
