### ISSUE TITLE
Gtext node not work

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#745]
D.grease_pencil['NodeTree_grease'].layers['GText']
has all is have to have, points and fills are showed, but not lines of grease pencil...

**Comment by zeffii** [comment]
yeah, gpencil internals API changed a bit in the last months. I will fix this.

**Comment by nortikin** [comment]
what did changed?

**Comment by nortikin** [comment]
http://www.blender.org/api/blender_python_api_2_76_0/bpy.types.GreasePencil.html#bpy.types.GreasePencil
draw mode?

**Comment by nortikin** [comment]
nope. cannot see what drives it.

**Comment by zeffii** [comment]
it's a new property called `points . pressure`

`ng.grease_pencil.layers['GText'].frames[0].strokes[0].points[:][0].pressure = 1.0`

**Comment by zeffii** [comment]
(actually i don't know for certain if this is a new property or that the property now suddenly is included in linewidth calcs)

**Comment by zeffii** [comment]
fixed with https://github.com/nortikin/sverchok/commit/0e5f390379e65209a975260f730577312745a537

**Comment by nortikin** [comment]
so, we can play with pressure
