### ISSUE TITLE
Text In - json to read from disk / path

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#746]
http://blender.stackexchange.com/questions/40950/how-do-i-open-json-files-using-the-text-editor

This is low priority, but we should allow json to picked from disk and have the option to update the disk-read at low frequency at least (for dynamic json). I know there's more important things going on but lets make a reminder.

**Comment by ly29** [comment]
Wouldn't be that hard, some restructuring of the code would be needed. But that restructuring should probably be done anyway... Old code. Many many things I didn't get when I wrote it.
