### ISSUE TITLE
Genetic Algorithms

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#747]
https://github.com/deap/deap
this is what i think to use. not investigated yet, and maybe you know better libraries examples?

**Comment by enzyme69** [comment]
I like deep stuff, but requires powerful GPU computer. There are few nice CPU ones, that works with Python, I think we can do something like filtering ala Deepdream, or simpler one.

Maybe some kind of ways to resample multiple strokes into one good stroke. Or something that adapt dots into area.

**Comment by enzyme69** [comment]
OpenToonz Chainer Python to style transfer...
https://opentoonz.github.io/e/

**Comment by nortikin** [comment]
@enzyme69 check this wonderfull http://digg.com/video/neural-network-animation-engine

**Comment by nortikin** [comment]
subject:
http://deap.readthedocs.io/en/master/examples/gp_spambase.html

**Comment by enzyme69** [comment]
I have a feeling this deep neural thing is simply teaching computer to
better match one thing with another thing.

Kind of like sampling resampling but in a more advanced level.


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
Yes, that kind of presents in grasshopper long time

**Comment by enzyme69** [comment]
@nortikin I wish I had learned and studied Architecture or Industrial Design.... but things are changing rapidly nowadays. In developed countries, I think architecture and design with aid of computing is so advanced, that I think it became strange to under developed countries. Why would people design expensive voronoi structure that looks very aliens? :) 

I was watching this just now:
https://www.ted.com/talks/maurice_conti_the_incredible_inventions_of_intuitive_ai

Exciting stuffs.

**Comment by nortikin** [comment]
good link

**Comment by vicdoval** [comment]
It would be amazing to integrate this Deap library with Sverchok... so many possibilities 😄 

@enzyme69 this is my favorite book about the parametric architecture, probably you will like it and for sure will help you understand: [The new math in architecture](https://www.google.es/search?q=new+math+in+architecture)

**Comment by enzyme69** [comment]
I am curious if one day we can use Grease Pencil --> and then Sverchok can understand the stroke and generate something.

**Comment by vicdoval** [comment]
@nortikin Finally did you do any attempt of mixing de Deap Library with sverchok?

**Comment by vicdoval** [comment]
@enzyme69  in some way its already happening :D

**Comment by nortikin** [comment]
ok, i made simple SNL of GA
Next step i will start PR for this https://github.com/nortikin/sverchok/issues/3160
