### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#751]
A few Blender Stack Exchange posts have now surfaced where the issue was that the documentation for a node was not comprehensive enough or didn't exist. We also have docs for nodes that have been removed (eval knieval).

for instance we would like to prevent questions like this: http://blender.stackexchange.com/questions/42319/whats-the-usage-of-set-get-property-nodes-in-sverchok  (not because it's a bad question.. but because those docs should exist) 

@ly29  i'll start a doc and you can augment it

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/blob/master/docs/nodes/scene/get_set_properties.rst

**Comment by sfire** [comment]
I've read the doc, you mentioned aliases in the doc. So,how many aliases do we have in sverchok? <br/>Or is there an aliases list available？

**Comment by zeffii** [comment]
welcome sfire, that node implements its own list of aliases, it should be visible..
```
aliases = {
    "c": "bpy.context",
    "C" : "bpy.context",
    "scene": "bpy.context.scene",
    "data": "bpy.data",
    "D": "bpy.data",
    "objs": "bpy.data.objects",
    "mats": "bpy.data.materials",
    "meshes": "bpy.data.meshes",
    "texts": "bpy.data.texts"
}
```
meaning you could write 
```python
bpy.data.objects['Cube'].location
D.objects['Cube'].location
objs['Cube'].location
```
ideasman42 just committed a keyboard shortcut to copy the full path to the clipboard, from the tooltip:
http://blender.stackexchange.com/a/42330/47
This will work for most properties. I would like to add a mode to these two Nodes that also gives the possibility to pick from a sequence of dropdown menus - but it's low priority.

**Comment by nortikin** [comment]
this objects nodes are not understandable at all. tried to force Ko. to write lessons, but he made some breaf example and all. Completely not usable about not documented or no lessons. I prefare both - docs and lessons. lessons just to be more clear.

**Comment by zeffii** [comment]
@nortikin do you refer to SvSetDataObjectNode and SvGetDataObjectNode ?

**Comment by zeffii** [comment]
hmm.. i never did a doc for SvObjRemote it should perhaps be removed..

**Comment by zeffii** [comment]
```python
                        # prevent setting scale to somethign that can't be
                        # recovered from
                        if (socket == 'scale') and (new_val == (0, 0, 0)):
                            new_val = 0.000001, 0.000001, 0.000001
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/11479731/ce5109e2-9793-11e5-861b-70b23705dda7.png)

**Comment by zeffii** [comment]
or maybe "Basic Object Control"

**Comment by zeffii** [comment]
well i've renamed it from 'Scene Objects' to 'Object Remote (Control)' because 'scene objects' is a weak descriptive name.

**Comment by nortikin** [comment]
i renamed some object nodes for more consistency. SvObj**** is default for any object operations

**Comment by nortikin** [comment]
and Bmesh also have prefix

**Comment by sfire** [comment]
There is no doc for [Voronoi 2D](http://nikitron.cc.ua/sverch/html/nodes/modifier_make/voronoi.html?highlight=voronoi), I can't find how to use it.... Can anyone fix it.
BTW，if a **3D Voronoi** is possible？

**Comment by ly29** [comment]
3D Voronoi is not possible until somebody implements it.

![skarmavbild 2015-12-04 kl 09 09 45](https://cloud.githubusercontent.com/assets/6241382/11584753/d67fb28c-9a66-11e5-9d60-aa21daeaf851.png)
Voronoi node creates a [voronoi diagram](https://en.wikipedia.org/wiki/Voronoi_diagram) based on the input locations, using the x,y components of the input vertices. It provides edges and vertices for the diagram. It is a very old node so might have odd behaviors.

**Comment by nortikin** [comment]
also Manhattan distance and approximate voronoi is preferrable but have to spend time... witch i have not.
