### ISSUE TITLE
Dupli Instances MK3 extra triangles

### ISSUE THREAD

**Issue by elfnor** [nortikin/sverchok#752]
If I scale an object used with the new Dupli Instances MK3 node this happens. 
The example from #739 

![dupli_instances_mk3_issue](https://cloud.githubusercontent.com/assets/7930130/11526693/2b9952b8-9941-11e5-88f4-0d00862c224c.png)

Each instance gets its own triangle to sit on.  These triangles are mostly hidden by the mesh if the object isn't scaled.

**Comment by sfire** [comment]
Yes, I've found the same problem.
And there is another issue. If I change the **object to duplicate** from one to another, such as shown below, from **monkey** to **cone**, the first object(**monkey**) dulplications still exist, and I get duplications of the **two** objects.....
![instance](https://cloud.githubusercontent.com/assets/5409756/11529261/dd1aa8c2-9926-11e5-86fb-9ca1245d3472.gif)

**Comment by zeffii** [comment]
this is not a problem, this is a feature :) that's how the node can duplicate geometry.

**Comment by zeffii** [comment]
but I agree that it would be awesome to be able to quickly hide the triangles. (they don't _render_ btw)

**Comment by zeffii** [comment]
i'll look into _that_ problem of switching objects, admittedly i have never tried to switch objects.

**Comment by zeffii** [comment]
@sfire, for now you have to manually unparent the previous object
![image](https://cloud.githubusercontent.com/assets/619340/11533439/01845d24-990a-11e5-9ed1-d661b0da1c07.png)

**Comment by zeffii** [comment]
How do you we feel about adding a mode that will limit the Dupli Instances MK3 node to only 1 child per parent?

```python
>>> obj = bpy.context.active_object
>>> obj.children
(bpy.data.objects['Cube'], bpy.data.objects['Suzanne'])
```

it's relatively easy to remove parents / children automatically .. it's not something I've thought about, but I would like to keep the UI simple - maybe one more row  .. maybe 

```
    - parent object [ booooom       ]
    - child object    [ Suzanne        ]
    - 1 child [x]  [ c l e a r a l l ] 
```

**Comment by zeffii** [comment]
A tickbox for 1 child is probably enough. will code this later :)

**Comment by elfnor** [comment]
Ok, It's good that they don't render, I didn't check that.

**Comment by elfnor** [comment]
But, I've just checked the game engine where I'm using this and unfortunately they do render. This is obviously Blender dupliverts behavior not Sverchok.  

Some of my generative art mazes for games get pretty high face counts if I make the duplicates real. I don't think this was the case with the old instancer. (I'll check on another machine)

**Comment by zeffii** [comment]
@elfnor The old instancer can be re-instated if you need, this is no problem. I was under the impression that no-one used it.

Yes, the old instancer worked by creating real objects, and using the same underlying `Mesh`, great for memory footprint, not so great for speed. Name collision checking of objects at creation time is still slow inside blender when considering large quantities of objects, each new object has to check if its name is safe. Once they're created updating them is a faster operator.

It's good that you mention this because none of us use the Game Engine in Blender. If your main issue  here is the visibility of the triangle, I 'll probably add a triangle scalar either as a socket or a slider on draw_buttons_ext..

I think you can make duplicates real and still have them share geometry by using just _Object_  not _Object and Data_

**Comment by zeffii** [comment]
@elfnor  Though I think this is less convenient in your specific case (compared to the old _Mesh Instancer_) You can 

Select boooom (parent object) -> Make Duplicates Real
Then _Deselect_ boooom
Then _Make Single User _-> _Object_

You see that each object now uses the same Mesh, thus not taking up more space

![image](https://cloud.githubusercontent.com/assets/619340/11560791/40d0de44-99c3-11e5-982f-3f6a6fd2d488.png)

**Comment by elfnor** [comment]
@zeffii  OK, I can get to the same place as the old  *mesh_instancer* with either:

*  *dupli_instancer*, then *Make Duplicates Real* 
*  *Viewer Draw* and *Objects In* , then *Bake* then *Make Links > Object Data*
*  *Viewer Bmesh* and *Objects In*, then *Make Links > Object Data*

Maybe a *Links* toggle next to the *Group* and *Merge* buttons on the *Viewer Bmesh* node?

**Comment by zeffii** [comment]
@elfnor maybe, but please understand my resistance to adding buttons to the nodeview UI of a node, especially buttons that may be used only infrequently. The *mesh_instancer* is more likely to be added back than adding features to BMeshViewer. -- I just wasn't aware that It was being used seriously

**Comment by zeffii** [comment]
unfortunately I can not do anything about the Triangle in the *dupli_instances* node, I tried, but the triangle's area directly correlates to the uniform scale of the duplicate. I'll reinstate the mesh instancer.
