### ISSUE TITLE
typo in UV connection node UI cup_u, cup_v

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#754]
I think this is supposed to be cap_u and cap_v  but I'm not certain and modifying the node UI may not be nice for existing layouts. But for future reference, cup doesn't mean much in English... it means vessel... something you drink coffee out of :)  @nortikin

**Comment by nortikin** [comment]
ok, cap, yeah ))) but ethimology the same, i guess.
Will fix in next release. thank you.
