### ISSUE TITLE
Use a more lighter default color for Stethoscope Node

### ISSUE THREAD

**Issue by LeonCheung** [nortikin/sverchok#757]
Currently the default Stethoscope color is (0.1, 0.1, 0.1), which usually needs to be manually changed because it apears quite darker in front of the default gray color of compositor background. So. :)  (Or expose as an option in Add-ons setting panel?) Thanks!

![dark_col](https://cloud.githubusercontent.com/assets/494788/11772308/43fe5c7c-a256-11e5-846a-7f16db0c26b2.png)

**Comment by ly29** [comment]
Yeah, that is good point.

My vote goes for a default based on the node editor theme, perhaps ```wire_inner``` as in
```python
>>> C.user_preferences.themes['Default'].node_editor.wire_inner
Color((0.6000000238418579, 0.6000000238418579, 0.6000000238418579))
```
Otherwise the user can set it via settings, or override on per node basis as now.

**Comment by zeffii** [comment]
I have been thinking about making it automatically invert or get _most appropriate high contrast color_..for quite some time. But then again, I do use a white nodeview background so it doesn't bother me.

**Comment by zeffii** [comment]
this gets current background color:
```python
        current_theme = bpy.context.user_preferences.themes.items()[0][0]
        editor = bpy.context.user_preferences.themes[current_theme].node_editor
        # = editor.space.back
```

**Comment by zeffii** [comment]
```python
def high_contrast_color(c):
    g = 2.2  # gamma
    L = 0.2126 * (c.r**g) + 0.7152 * (c.g**g) + 0.0722 * (c.b**g)
    return [(.1, .1, .1), (.95,.95,.95)][int(L < 0.5)]

```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/00fc26946b61b43c94cd03f905c14f5d5a6c8050

**Comment by ly29** [comment]
Background polygon seems like nicest option but for now changing the default seems sane enough.

**Comment by zeffii** [comment]
smarted initialization colors are picked now, depending on existing background color for nodeview.
I see no reason to sink time into additional features for this node. Efforts should be going towards [_sverchok redux_](https://github.com/Sverchok/SverchokRedux).

**Comment by LeonCheung** [comment]
Pretty nice. Thank you!

**Comment by zeffii** [comment]
no problem. should have done it ages ago.
