### ISSUE TITLE
Sv Curve node - Some thoughts

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#758]
At present (2015 Dec) this node only produces single Segment Curves of type 'POLY' .  This just means 
```
  vertex ------------ vertex  ------------ vertex ------------ vertex

  becomes

  vertex ------------ vertex      
  vertex ------------ vertex
  vertex ------------ vertex
```
And that's all it was designed to do. This only uses a very small portion of the available features of Curve Objects. It's definitely a bit of a compromise. but handy for renderable edges.

Naturally you might want to feed it multi-segment polylines, or even rings (cyclic). Most of the code is already in place for that, but extra logic needs to be added to allow us to switch between single segments and chained segments, or cyclic segments.

To me it makes the most sense if we add an extra enum to decide ( segments | chains | cyclic chains )
and if in chains / cyclic chains mode there could be a U subdiv level to get smooth splines from fewer points.

**Comment by zeffii** [comment]
What should the node be able to do?

These are the scenarios

**verts + edges + faces inputs:**  
- make curves from all edges as separate segments (non cyclic, disjoint)
- make edge loops into polylines / non cyclic path (with option to make each disjoint Spline cyclic)
   - auto detecting this is a pain.
- make polygons into cyclic paths (these could always be assumed to be cyclic)
- have 2D / 3D toggle.
- have additional input for Bezier points and a toggle for disjoint or continuous multi-part splines.
  - quite tricky

**Comment by zeffii** [comment]
I'd propose to call it the Curve Output node, and give it Enums for the various _modes_
`[Path, Bezier, 3ptArc]`
and within these modes also have submodes where applicable.

**Comment by zeffii** [comment]
but.. because these top-level modes are so different, i'm inclined to make them seperate nodes but register them from the same file.

**Comment by zeffii** [comment]
no more groups, use parent instead. that simplifies some code
```py
for i in obj.children:
...     i.select=1
```

**Comment by nortikin** [comment]
yes, all that was in mind, but i needed fast solution to show what Sverchok can do. Next step to organize mk1/mk2 for enum and others.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/CurveOutput i did start branch . hope to find time tomorrow start getting it useable.

**Comment by zeffii** [comment]
uch... this needs a polyline mode :) meaning: if edges are not connected, then the node assumes that each list of vertices are intended to be connected continuously like a polyline..

**Comment by zeffii** [comment]
Okay, instead I think this deserves a polyline node (not Mode,.... Node! ). This should give a chance to streamline some of what feels bloaty about svCurvenode..

https://github.com/nortikin/sverchok/tree/curve_node_polylines_mode  (crappy name for branch... it's a new Node)

**Comment by zeffii** [comment]
also... it doesn't work  yet :)
