### ISSUE TITLE
2d boolean node.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#763]
http://i.stack.imgur.com/Fp2O0.png

There are several frameworks out there to do a 2d boolean of polygons. I'd prefer not to have to use a dependency, but I also don't really want to code something if it exists in a usable form already. @nortikin  you linked to some polygon library a while back but I don't remember what..

https://pypi.python.org/pypi/Polygon3  is too restrictive with licensing

**Comment by ly29** [comment]
There is shapely which is BSD but it requires geos which is external. 
https://pypi.python.org/pypi/Shapely

**Comment by zeffii** [comment]
i'm in the process of coding up : http://www.cc.gatech.edu/~jarek/graphics/papers/04PolygonBooleansMargalit.pdf
https://github.com/zeffii/2D_Booleans_polygon

but, shapely is cool.

**Comment by ly29** [comment]
cool, been busy lately, have some things I want to try out over at redux but I just don't have time

**Comment by nortikin** [comment]
thsat was shapely i found time ago

**Comment by zeffii** [comment]
2 boolean is a lot of work, not difficult, just mountains of code comprehension :) maybe this week

**Comment by zeffii** [comment]
maybe this week :)

**Comment by zeffii** [comment]
I think if this works in Python i'll write it in C .

**Comment by Durman** [comment]
So, is it possible to make 2d boolean operation in Sverchok now?)

**Comment by zeffii** [comment]
could it be made? yes.
is there currently a nice way? no.

**Comment by Durman** [comment]
I would like to make something simple like this:
![2018-02-14_12-47-27](https://user-images.githubusercontent.com/28003269/36197058-21a59ada-118c-11e8-87ac-cab63ddfcb3e.png)

**Comment by zeffii** [comment]
i suspect someone who really needs this, can invest time in implementing something we could use :)

**Comment by zeffii** [comment]
interesting : http://boolean.klaasholwerda.nl/bool.html

**Comment by Durman** [comment]
Somerthing already works. )

![2d boolean](https://user-images.githubusercontent.com/28003269/36301079-0e862a68-131d-11e8-8fc0-8a57d3537608.gif)

**Comment by Durman** [comment]
![giar](https://user-images.githubusercontent.com/28003269/36338429-4888154a-13c8-11e8-9be2-26d8ee82bda3.gif)

**Comment by enzyme69** [comment]
@Durman I am looking at this, so there is "Boolean 2D" script node somewhere? I am testing Shapely right now and testing Shapely intersection and union, seems quite useful if we can "simply" use it with Sverchok.

**Comment by Durman** [comment]
@enzyme69 My boolean node does not work. I discovered that there are not all needed algorithm in Sverchok yet for this task.I did not see Shapely yet. I will look forward your video about this.))
