### ISSUE TITLE
List Shift mk2 not working?

### ISSUE THREAD

**Issue by diramazioni** [nortikin/sverchok#765]
I've noticed that "List Shift mk2" doesn't actually shift the list like the old node did. Is it a bug? If not how to use it properly?
I'd like also to ask if there is a way to access old nodes, there are not present in the menu but the outdated templates still use them so they are still there just not present in the menus and there is no preference to active them
thanks in advance

**Comment by ly29** [comment]
@nortikin 

the new one is neat and all for what it does but why remove the old one before it is all implemented?

**Comment by zeffii** [comment]
You can access old nodes by going to console and getting a reference to the current node tree. If you are really stuck.

```python
# here NodeTree would be your layout's name
>>> nodes = bpy.data.node_groups['NodeTree'].nodes

>>> sverchok.old_nodes.register_old("ShiftNode")
<module 'sverchok.old_nodes.shift' from '/home/zeffii/GITHUB/scripts/addons/sverchok/old_nodes/shift.py'>

>>> nodes.new("ShiftNode")
```

**Comment by diramazioni** [comment]
thanks zeffii, I've ended up adding it to menu.py and __init__.py that day.
But in my opinion they should all be present in an "old" subtree, since they have all different bl_idname they can coexist. 
bl_label should reflect bl_idname like "List Shift mk2" (or just 2) to not get confused what is what. 
cheers

**Comment by zeffii** [comment]
I don't think we'll add an 'old_nodes' menu item, for a simple reason. Those nodes are depricated. As @ly29  points out, The `shiftnode` shouldn't be in the old_nodes list until the old functionality can be duplicated or supersede - which is normally the case.

hope it isn't too inconvenient, i'm sure future updates will resolve it.

**Comment by ly29** [comment]
For now we should reinstate the shift node.

The old nodes shouldn't be user accessible, since they are all supposed to have been replaced with a newer functional node that breaks the old one in a non trivial way.  

They are kept there for a while until the we move on.

**Comment by nortikin** [comment]
i will return old. Not remember i deleted it

**Comment by nortikin** [comment]
did it. use version 1, not 2.
