### ISSUE TITLE
Mysterious Menu

### ISSUE THREAD

**Issue by LeonCheung** [nortikin/sverchok#766]
Maybe a bit off topic here, but I'm very curious that if some dev made the menu list with a bit black humor? Or is it sorta easter egg? 

![sv_menu](https://cloud.githubusercontent.com/assets/494788/12376416/582470b8-bd2e-11e5-9141-c0151edbbffe.jpg)

**Comment by nortikin** [comment]
It was hard. we discussed a lot of naming items in menu, at last we made some kind of shape.
Rorschach's image.

**Comment by LeonCheung** [comment]
Aha, so there was a story. :tongue:  Thanks!

**Comment by nortikin** [comment]
partially it was accident indeed. but let it be

**Comment by nortikin** [comment]
PLEASE, use CTRL+Space buttons. )))

**Comment by LeonCheung** [comment]
LOL interesting. So Who the Ctrl Space menu indicates BTW? :smiling_imp:

**Comment by nortikin** [comment]
some kind of something. What do you see there?

**Comment by LeonCheung** [comment]
A pandora box for procedural modeling for sure. :P

**Comment by nortikin** [comment]
or send watches

**Comment by nortikin** [comment]
http://vk.com/blendernet?w=wall-59673042_1049

**Comment by LeonCheung** [comment]
LOL That's..........cute :P
