### ISSUE TITLE
Generative Art Pull Request

### ISSUE THREAD

**Issue by elfnor** [nortikin/sverchok#771]
Any chance someone could have a look at my pull request for the Generative Art node? Its all self-contained so shouldn't be a problem to anything else.

I've got a couple of blog posts waiting on the update,

Thanks elfnor

**Comment by zeffii** [comment]
done :) and thanks!

**Comment by nortikin** [comment]
thank you, guys

**Comment by zeffii** [comment]
upon adding this node to the scene, it produces an AttributeError
```python
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\generator\generative_art.py", line 329, in update
    self.make_sockets()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\generator\generative_art.py", line 368, in make_sockets
    for elem in self.xml_tree.findall("constants"):
AttributeError: 'SvGenerativeArtNode' object has no attribute 'xml_tree'
```

@elfnor  perhaps you would like to fix this, not a serious error by any stretch, but it would be nice to suppress it.

creating arbitrary variables in  the `self` namespace of Nodes/Operators in one function and expecting them to be available in the next function's `self` is known to cause problems. We have an easy fix (see nodescript's node_func dict ) .

**Comment by zeffii** [comment]
it may be simpler to do some defensive coding here in `def make_sockets(self):`
```
        d_constants = {}
        for elem in self.xml_tree.findall("constants"):
            d_constants.update(elem.attrib)
```
maybe
```python
        d_constants = {}
        if not hasattr(self, 'xml_tree'):
            return
        for elem in self.xml_tree.findall("constants"):
            d_constants.update(elem.attrib)
```
