### ISSUE TITLE
skin modifer - issues

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#775]
- [x] needs to set / retain material between updates..
- [x] should allow multiple datastreams, not simply ignore anything past index 0
- [x] needs internal remove doubles

no eta.

**Comment by zeffii** [comment]
the code for material set/reset was a fast code-copy from bmesh mk2, it is tested only in the node of origin, not in its new place -- it does however appear to function correctly. Caviat is that if you want to rename the material you must do so from the node tree or the properties dialog (not from the node interface)

regarding the remove doubles: I do not know if the bmesh operations for remove doubles also deals with generating the appropriate `vertex_radius` information for the skin_modifier. I'll assume it does and if it doesn't then devise some kind of procedure to compare the verts / edges / radii. It should be simple enough.

**Comment by zeffii** [comment]
what this machine does is 

 1. make or pickup an object
 2. inject a bmesh
 3. remove modifiers (skin / subdiv )) if present
 4. add skin + subdiv modifiers (back)
 5. set radii ( vertex_radii become available after adding skin modifier )

The reason this node needs to remove + re-add the skin modifier on each update is because the skin modifier (when scripted this way) doesn't let one simply update the mesh + vertex_radii information, instead it just drops the radii information entirely and won't let us update it until 
the skin modifier is removed and added. It is hackish, and must remain until a Blender-C dev decides to implement the scenario for the modifier.

**Comment by zeffii** [comment]
I won't be touching this for a very long time.

**Comment by zeffii** [comment]
@enzyme69 
i hear what you're saying regarding the multiple input streams, right now (if you look at the code - do it... yeah do it.. go on...) you'll see stuf like  `some_input.sv_get()[0]` , that means it's only going to take the first list for that socket and ignore the rest.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1132

![svkingif](https://cloud.githubusercontent.com/assets/619340/21954655/cb969336-da57-11e6-8c56-7119d0cbc35a.gif)

**Comment by zeffii** [comment]
not going to push this just yet. It will need a companion node for the remove doubles part. This is too much of a headfuck to do in one node.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21954680/883595aa-da58-11e6-9ab4-a4493ee0663b.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21954693/f99a71de-da58-11e6-9dd0-27b13f5792ae.png)

**Comment by zeffii** [comment]
![harggif](https://cloud.githubusercontent.com/assets/619340/21955051/b2c44028-da62-11e6-98d9-9bd6549b9943.gif)

**Comment by enzyme69** [comment]
Wooh!!! Awesome works! This is it! Will give this a try as soon it is updated.

**Comment by enzyme69** [comment]
Internal Remove Doubles is also taken care of? :)

**Comment by zeffii** [comment]
one the companion node works, i'll add it to the skinviewer as a first processing step

**Comment by zeffii** [comment]
![kooogif](https://cloud.githubusercontent.com/assets/619340/21965855/81ce34cc-db68-11e6-94cc-3af43de0c739.gif)

the companion node's code could do into the skin viewer node, but i'm kinda busy.
current limitation on its input is it expects two data layers, this is hardcoded for my convenience.
```python
# ##### BEGIN GPL LICENSE BLOCK #####
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# ##### END GPL LICENSE BLOCK #####

import bpy
from bpy.props import IntProperty, EnumProperty, BoolProperty, FloatProperty
import bmesh
import bmesh.ops

from sverchok.node_tree import SverchCustomTreeNode
from sverchok.data_structure import updateNode, match_long_repeat, fullList
from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata, pydata_from_bmesh

def set_data_for_layer(bm, data, layer):
    for i in range(len(bm.verts)):
        bm.verts[i][data] = layer[i] or 0.1


def shrink_geometry(bm, dist, layers):

    # should detect float/int/
    made_layers = []
    for idx, layer in enumerate(layers):
        
        first_element = layer[0] or 0.2
        layer_name = '_layer' + str(idx)
        layers = bm.verts.layers
        current_type = ''

        if isinstance(first_element, float):
            current_type = 'float'
            data_layer = layers.float.new(current_type + layer_name)
        elif isinstance(first_element, int):
            current_type = 'int'
            data_layer = layers.int.new(current_type + layer_name)

        made_layers.append(data_layer)
        bm.verts.ensure_lookup_table()
        set_data_for_layer(bm, data_layer, layer)

    bmesh.ops.remove_doubles(bm, verts=bm.verts[:], dist=dist)
    bm.verts.ensure_lookup_table()
    
    verts, edges, faces = pydata_from_bmesh(bm)
    data_out = [verts, edges, faces]
    for layer_name in made_layers:
        # is there a foreach for this?
        # something like
        #    bm.verts.layers.foreach_get(layer_name, receiver_list)
        data_out.append([bm.verts[i][layer_name] for i in range(len(bm.verts))])

    return data_out


class SvBmeshRemoveDoublesKeepDatalayer(bpy.types.Node, SverchCustomTreeNode):
    ''' Limited Dissolve '''
    bl_idname = 'SvBmeshRemoveDoublesKeepDatalayer'
    bl_label = 'bm rm Doubles KeepDatalayers'
    bl_icon = 'OUTLINER_OB_EMPTY'

    distance = FloatProperty(default=0.001, min=0.0, update=updateNode)
    num_extra_sockets = IntProperty(default=0)

    def sv_init(self, context):
        for idx, sockets in enumerate([self.inputs, self.outputs]):
            sockets.new('VerticesSocket', 'Verts')
            sockets.new('StringsSocket', 'Edges')
            sockets.new('StringsSocket', 'Polys')
            sockets.new('StringsSocket', 'Data A')
            sockets.new('StringsSocket', 'Data B')


    def draw_buttons(self, context, layout):
        layout.prop(self, "distance")

    def process(self):

        in_linked = lambda x: self.inputs[x].is_linked
        out_linked = lambda x: self.outputs[x].is_linked

        if not in_linked('Verts'):
            return
        else:
            if not (in_linked('Polys') or in_linked('Edges')):
                return

        if not (any(out_linked(x) for x in ['Verts', 'Edges', 'Polys'])):
            return

        input_data = [socket.sv_get(default=[[]]) for socket in self.inputs]
        all_data = match_long_repeat(input_data)

        collected = [[], [], [], [], []]
        for verts, edges, faces, d1, d2 in zip(*all_data):
            bm = bmesh_from_pydata(verts, edges, faces)
            for idx, content in enumerate(shrink_geometry(bm, self.distance, [d1, d2])):
                collected[idx].append(content)
            bm.free()

        for idx, socket in enumerate(self.outputs):
            socket.sv_set(collected[idx])


def register():
    bpy.utils.register_class(SvBmeshRemoveDoublesKeepDatalayer)


def unregister():
    bpy.utils.unregister_class(SvBmeshRemoveDoublesKeepDatalayer)


```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21999256/6c54cfc6-dc39-11e6-9271-f8a7f54cb46f.png)
not hooked up yet..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22000474/8c7920c6-dc3f-11e6-9322-f77e1dc32010.png)


it works :)

- x and y radii are independant, but both need to be connected. If x or y isn't connected, the constant is used.
- remove doubles is handle internally. ( pure magic. )

https://github.com/nortikin/sverchok/tree/skin_view_mk1B

**Comment by zeffii** [comment]
have pushed to master. (no version bump, you'll have to manually update )
might change the ui 
- stick the word "Live" in a button beside the basename, and 
- remove the little modifier man (which serves no purpose anymore .. or ever..that I can recall..)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22001212/cfcd33ea-dc43-11e6-91e5-35623e1e1a81.png)

**Comment by enzyme69** [comment]
@zeffii Is this in the latest Sverchok yet? Didn't see 🍡

**Comment by zeffii** [comment]
force update .

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22018420/11e911de-dcaf-11e6-9afc-c7eb8788f146.png)

https://gist.github.com/777e7cb4304115714131a70f3187b159

**Comment by enzyme69** [comment]
@zeffii 

This is the setup I am working at the moment. I will update Sverchok and get the latest node, maybe I will get a different result.
https://gist.github.com/edb219093b5bf67e3541389c1c73fd5b

**Comment by zeffii** [comment]
The layout you linked in your Issue was not quite suitable for the precision required by Skin Mesher. When i first opened your gist and connected a Skin Mesher instead of the Viewer Draw to see the Lines, it wouldn't even generate meshes. Leading me to believe I wasn't correctly testing the length of the vertices per object versus the number of edges. ( i could still put checks in there.. )

but then if we do a simple test as above,, we know each set of vertices/edges is going to be OK, and feeding that into the Skin Mesher proves that with correct input, the output of Skin Mesher will be correct. Well then why does ViewerDraw not complain? because .. it's like a junky, it accepts almost anything and has a great number of tests to reject bad input.

**Comment by zeffii** [comment]
i  think the line node should be revisted and vectorize in a similar way to Circle node.

**Comment by enzyme69** [comment]
That is something I was gonna say. Line needs [[ [1], [2], [3] ]] while Circle accept it right away.

I can try joining those lines as a single object.

**Comment by zeffii** [comment]
stick an indexviewer on the output of Vector in..
![image](https://cloud.githubusercontent.com/assets/619340/22018710/8e41317a-dcb0-11e6-95d7-9159dbaba488.png)

**Comment by enzyme69** [comment]
Aha.. no wonder. Hmm...

**Comment by enzyme69** [comment]
![screen shot 2017-01-17 at 22 35 16](https://cloud.githubusercontent.com/assets/3952687/22018904/3f12823e-dd05-11e6-9958-b8bd9db6636b.png)
Things work well here:
https://gist.github.com/94a9bbb064938f29d9addf05e0150f57

**Comment by zeffii** [comment]
i don't even understand the use case that the Line node is vectorized for..

**Comment by nortikin** [comment]
@zeffii i have video abot that
https://www.youtube.com/watch?v=H5SYNxykqtM

**Comment by enzyme69** [comment]
Skin Mesher is awesome~
![screen shot 2017-01-19 at 23 25 48](https://cloud.githubusercontent.com/assets/3952687/22106837/ce3b3060-de9e-11e6-888e-d0d0be1115b5.png)
![screen shot 2017-01-19 at 23 22 29](https://cloud.githubusercontent.com/assets/3952687/22106835/ce38e710-de9e-11e6-8b72-f8aaa4a0491c.png)
![screen shot 2017-01-19 at 23 20 19](https://cloud.githubusercontent.com/assets/3952687/22106836/ce3ac274-de9e-11e6-8fea-3a7f42ff9be1.png)

**Comment by zeffii** [comment]
nice work @enzyme69 .

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22328554/33ca894e-e3bd-11e6-83ae-48168834f189.png)
@enzyme69 

I don't know why the Get/Set props node can't do that, will look.  But I might add the smooth switch to the node instead..

**Comment by zeffii** [comment]
had a look at get/set source , it doesn't handle `booleans` - will fix soon.

**Comment by zeffii** [comment]
@enzyme69  i've noticed one of your videos that Skin Mesher crashes if you plug a remove doubles before passing verts/edges to it. That shouldn't happen, but here's the reference for later.
https://www.youtube.com/watch?v=dh7dZHdlEAo&t=1417s

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/24191567/7a3c844a-0eec-11e7-86ae-1c161dd0d423.png)

**Comment by enzyme69** [comment]
@zeffii This way to Set the Object.Data.Modifier Skin Smooth seems to work:
![screen shot 2017-03-22 at 21 45 33](https://cloud.githubusercontent.com/assets/3952687/24194115/e6ef8360-0f48-11e7-8c0d-248a207090d1.png)

Maybe if you have time we can have Skin Mesher Object Out slot 👍  :)

I am actually really happy with all the toolsets and how in Sverchok we can now smoothly and fluently work with Curve and Skinning Edges. Very unreal.

**Comment by zeffii** [comment]
re: obj out. yes, maybe. also smooth (as ext option)

btw, arrow keys can be used to scrub - you dont need the timeline
