### ISSUE TITLE
Image node faulty process logic

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#777]
from: http://blender.stackexchange.com/questions/49811/im-getting-no-output-from-the-image-node-when-using-sverchok

```python
if 'edgs' in self.outputs and len(self.outputs['edgs'].is_linked) > 0:
   Node Image had exception object of type 'bool' has no len()
```
In earlier Python 3.x versions I think this was legal syntax, but not in 3.5

**Comment by zeffii** [comment]
should just be
```python
if 'edgs' in self.outputs and self.outputs['edgs'].is_linked:
```

**Comment by zeffii** [comment]
fixed:
![image](https://cloud.githubusercontent.com/assets/619340/15273777/4bb2fcfa-1aa3-11e6-922c-7728f14f893b.png)

**Comment by ly29** [comment]
Actually a global search/replace gone wrong. From ```.links``` to ```.linked```. Anyway checking length of a list to be none zero is bad python. Just check the list, ```if my_list``` which I think all new code does now.

**Comment by zeffii** [comment]
It seems that this node doesn't get used much when the last update was Nov 25, 2014.
https://github.com/nortikin/sverchok/commit/52198511f92ff79f82fa49681f0a911acbffc455#diff-65cd86979326f1ef116969e4626ed747L112.

anyway, it should work again :)
