### ISSUE TITLE
beta SVG writer/viewer

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#780]
The idea is to write a node that takes in 3d verts/edges/faces and generates appropriate 2D SVG path data. Perhaps initial implementation will be only a Path generator, because its easy to take 3D data and strip off the 3rd dimension.

inputs, I think 
- linewidth (vectorized)
- stroke (color, vectorized)
- fill (color, vectorized)
- verts, edges, faces

![image](https://cloud.githubusercontent.com/assets/619340/15429269/7acaa802-1ea0-11e6-8865-468aa5936ff6.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/15437271/86c803fe-1ec6-11e6-92d2-d4a92b90f71e.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/15448476/10754d90-1f63-11e6-8ca1-da04adcfa44b.png)

**Comment by nortikin** [comment]
ok. how will you use this data? 3D for site? or how?

**Comment by zeffii** [comment]
imagine you want to quickly draw some parametric geometry as an svg. No this node will decompose 3d-xyz to 2d-xy

**Comment by zeffii** [comment]
I have not decided how it will interpret incoming socket data..  like..
- if verts only input, then create a group with ellipses at each coordinate
- if verts+edges then generate paths vert-edge-vert,  ...vert-edge-vert
- if verts+faces then generate closed polygons

**Comment by nortikin** [comment]
nice

**Comment by zeffii** [comment]
don't know if I'll find time to work on this again..
![image](https://cloud.githubusercontent.com/assets/619340/15801386/361f8160-2a93-11e6-8c27-646d979077c7.png)

i'm trying to think of another way to compose svg with nodes
