### ISSUE TITLE
newsroom graphics

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#781]
i've been following the news a lot lately and often see these matrix-dot worlds, wondered how one might script those:

converting from blacknwhite bitmap to 3d earth (equirectangular projection)

![image](https://cloud.githubusercontent.com/assets/619340/15469636/d333b1e4-20eb-11e6-8bcf-8e8d48987415.png)

scriptnode:
```python
import math
from math import (cos, sin)

def sv_main(verts=[[]], R=0.3):
    verts_out = []

    in_sockets = [
        ['v', 'some_socket_name', verts],
        ['s', 'R', R]
    ]

    def xyz(lat, lon):
        return [R * cos(lat) * cos(lon), R * cos(lat) * sin(lon), R * sin(lat)]
    
    if verts and verts[0]:
        verts = verts[0]
        for lat, lon, _ in verts:
            coord = xyz(lat, lon)
            verts_out.append(coord)



    out_sockets = [
        ['v', 'verts', [verts_out]]
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
or something like this anyway..

**Comment by zeffii** [comment]
![joke3d](https://cloud.githubusercontent.com/assets/619340/15478504/e77ec862-211a-11e6-8f07-624910ca666a.PNG)

**Comment by nortikin** [comment]
image decomposer not works for me. what i doing wrong? no error message.

**Comment by zeffii** [comment]
first two sockets must be connected, even if 2nd socket data is not used.

**Comment by zeffii** [comment]
(this is not a bug, but a feature...)

**Comment by nortikin** [comment]
![image_in_strange](https://cloud.githubusercontent.com/assets/5783432/15621109/a884d64e-246f-11e6-819e-d7cc7a2d3a56.png)
![image_in_strange1](https://cloud.githubusercontent.com/assets/5783432/15621110/a88e5e80-246f-11e6-95da-4a63f74bcddd.png)

**Comment by zeffii** [comment]
: ) )  -- you see often the decompose node would be used when XYZ and RGB both have socket connection, my silly code just prevent calculation when not sufficiently connected. maybe it's over-caution.

**Comment by nortikin** [comment]
it is ok. Needed to be mentioned in my post on Vk.com group
