### ISSUE TITLE
Cannot install plugin in 2.76b

### ISSUE THREAD

**Issue by Ilidur** [nortikin/sverchok#783]
Error seems to stem from line 115 in __init__.py where everything has been put into functions but the declaration of "nodes" has not been copied.

nodes = importlib.import_module('nodes')  is missing.

**Comment by nortikin** [comment]
what is name of sverchok folder?

**Comment by Ilidur** [comment]
sverchok-master straight from the zip. This is under Ubuntu if that helps. I just noticed the markup messed up my initial comment, I was refering to `__init__.py`

**Comment by Ilidur** [comment]
So I tried installing it initially and it complained about numpy not being installed when I activated. I installed the packgage python3-numpy but didn't try to reinstall the package. Instead I tried activating it again which didn't work.

I have removed the installed folder from /scripts/addons and reinstalled with numpy already on the system and it seems to be activating fine now.
