### ISSUE TITLE
Vertex Group Weights Node

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#786]
I am uising the Vertex Group Weights node and this node I assume can do both modify and read weight input and output. However, a quick test setup and it does not seem to update the weight instantly.

![sv_not_updating_weight_instant](https://cloud.githubusercontent.com/assets/3952687/17281142/36c87b54-57dd-11e6-9a64-d6fab8a7bc49.gif)

I need to cut and reconnect in order for it to update.

**Comment by ly29** [comment]
@Kosvor is the one who can answer questions here. 
The documentation is out of date and even though the node code is short it does somethings somewhat subtle.

**Comment by Kosvor** [comment]
It does not work when the input and output weight sockets used simultaneously. This was done so that the code does not perform unnecessary operations and running quickly. Try to use two nodes. One to enter the weight and the other to output weight.

**Comment by enzyme69** [comment]
​Ok got it! Thanks for explanation~ :D
