### ISSUE TITLE
menu.py

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#788]
uhhhhmmm wtf?

```python

def reload_menu():
    menu, node_count = make_categories()
    if 'SVERCHOK' in nodeitems_utils._node_categories:
        nodeitems_utils.unregister_node_categories("SVERCHOK")
    nodeitems_utils.register_node_categories("SVERCHOK", menu)


def register():
    menu, node_count = make_categories()
    if 'SVERCHOK' in nodeitems_utils._node_categories:
        nodeitems_utils.unregister_node_categories("SVERCHOK")
    nodeitems_utils.register_node_categories("SVERCHOK", menu)

    print("\n** Sverchok loaded with {i} nodes **".format(i=node_count))


def unregister():
    if 'SVERCHOK' in nodeitems_utils._node_categories:
        nodeitems_utils.unregister_node_categories("SVERCHOK")
```

maybe just 

```python

def reload_menu():
    menu, node_count = make_categories()
    if 'SVERCHOK' in nodeitems_utils._node_categories:
        nodeitems_utils.unregister_node_categories("SVERCHOK")
    nodeitems_utils.register_node_categories("SVERCHOK", menu)


def register():
    reload_menu()
    print("\n** Sverchok loaded with {i} nodes **".format(i=node_count))


def unregister():
    if 'SVERCHOK' in nodeitems_utils._node_categories:
        nodeitems_utils.unregister_node_categories("SVERCHOK")
```

**Comment by ly29** [comment]
Yeah that makes sense.


Side note:
The menu and introducing dynamic items for node groups is kind of needed for groups.

**Comment by zeffii** [comment]
yeah, serialize monad to local storage to make available as template / loadable monad.

The hardest part about that is: where to store serialized content...   make it configurable in a userpreference? defaulting to some sane OS / Blender convention... 
- for windows perhaps  `C:\Users\zeffi\AppData\Roaming\Blender Foundation\Blender\2.77\scripts `

**Comment by ly29** [comment]
Have look at how it works for the builtin nodes.
https://github.com/dfelinto/blender/blob/3068ea34e414e7af6d20af7ab92c69cbd9a33414/release/scripts/startup/nodeitems_builtins.py#L68-L99

**Comment by ly29** [comment]
![skarmavbild 2016-08-09 kl 22 09 21](https://cloud.githubusercontent.com/assets/6241382/17531846/fd7d40da-5e7d-11e6-8b4a-6183f9ecc9ac.png)

**Comment by zeffii** [comment]
I'm not so sure adding a new empty MonadNode is necessary.. (anymore)

but if it's really needed:
rather than `node.add_node`  (type=SvGroupNodeExp) i think we can just add an operator to call make_group_monad  /  SvMonadCreateFromSelected   (with a new property to ignore nodes.. entirely)

**Comment by ly29** [comment]
I don't think it is needed. Monad from selection is good enough for me.

**Comment by zeffii** [comment]
that's settled then :)
