### ISSUE TITLE
Dynamic monad nodes

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#789]
As per reasons #785 there is a need for node groups to have dynamic properties.

The way to do this is via dynamic node classes registered as needed in runtime.

The basic implementation is in  [dynamic_monad_node](https://github.com/nortikin/sverchok/tree/dynamic_monad_node)

Todo
- [x] Dynamic properties
- [x] Class registration on file load
- [x] Collision testing on property names
- [x] Updating class definition on editing
- [x] Update class definition on socket connect
- [x] Move/Remove sockets
- [x] Rename sockets
- [x] Recast sockets
- [x] Create socket via connect 
- [x] Edit node group name
- [x] Fix multisocket 

Choose/custom properties (far out), #798 

I hope this can be finished quickly so it can be folded in into #785 since it diverges from there are bit

Termininology.

*monad* - the actual layout that pops up to be edited (stored in ```bpy.data.node_groups```)
*monad nodes* - the nodes that are _inside_ a monad, ```monad.nodes```
*monad class* - the dynamiclly generated node class that each monad has
*monad instance nodes* - the nodes that reference a certain monad. ```monad.instances```

**Comment by ly29** [comment]
per suggestion of @zeffii #785 is overcrowded so this is moved here.

**Comment by zeffii** [comment]
i added some explicit items in the todo.

**Comment by zeffii** [comment]
let me know when you want to triage some stuff, as it stands I'd like to not edit places that you might be working on.  But, am reading your edits and think I understand it. nice splitting between work that happens inside the monad and on the exterior interface.

**Comment by ly29** [comment]
The main issue to solve how edits to the monads trees are processed, specifically edits that changes the interface.

Ways to to edit:
- Rename socket, side panel
- Move socket, side panel
- Remove socket, side panel
- Change socket type, side panel


All of these are easy, once we decide what to do since the lead directly to our operator.

- Editing links

This is more complicated since it leads to the ```update``` function being called.

**Comment by zeffii** [comment]
mostly this: `'SvGroupInputsNodeExp' object has no attribute 'parent_tree_name' ` .. anyway, too late for tonight !  goodnight!

**Comment by ly29** [comment]
Yeah the general assumption of one parent node isn't valid. But all monad instance  nodes can accessed via monad.node_instances.

**Comment by zeffii** [comment]
in the case of instances you iterate over all siblings to perform changes.. (i saw some code to this effect?)

each monad will know its siblings by calling a function,  maybe each monad just stores the name of the 'first born' , that way instances will automatically always iterate over those monads that self identify as siblings of the first born, or are the first born.

**Comment by ly29** [comment]
Termininology.

monad - the actual layout that pops up to be edited (stored in ```bpy.data.node_groups```)
monad node class - the dynamiclly generated node class that each monad has
monad (instance) nodes - the nodes that reference en certain monad

To access the instances of a certain node monad one use the property.

Yeah that code was something I wrote as sketch,  I will not be able to test it today so if you want to give it a go feel free to.
```python
    @property
    def node_instances(self):
        res = []
        for ng in self.sv_trees:
            for node in ng.nodes:
                if hasattr(node, "group_name") and node.group_name == self.name:
                    res.append(node)
        return res
```
https://github.com/nortikin/sverchok/blob/dynamic_monad_node/node_tree.py#L347-L354

**Comment by zeffii** [comment]
ok i was calling _monad nodes_ : 

> those nodes which are stored inside the monad, 

it seems the more explicit _'monad_instances'_ is more suitable to convey the node that you click to edit the monad?

I know it's a bit of handwaving but makes talking about this easier.. 

Yes will have a stab at _propagating instance updates_.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17548290/7dccf61e-5eeb-11e6-8d7a-9c3be04cba28.png)

maybe the naming is a bit twisted? this felt easier during the exploration phase, but I can see how it is comfortable to call the Monad Instance ' monad node' , I chose not to .. and would still like to make a case for keeping it ...

.. possibly also deprecate the names where they mention 'group node' etc...

**Comment by ly29** [comment]
I like monad but the problem is the blender context where they are called groups... Oh well let us go with monad.

Updated the terminology a bit also.

**Comment by zeffii** [comment]
maybe we should call them groups too.. i went for `monad` during exploration... because ofcourse sverchok itself is in bpy.data.node_groups .. thought it was necessary for some distinction. This may be lost on the user...that i _can_ understand..

**Comment by ly29** [comment]
The property could be renamed ```instances``` which in code very conveniently becomes ```monad.instances```, reading very naturally.

```python
for instance in monad.instances:
    instance.inputs.remove(...)
```

**Comment by zeffii** [comment]
yes! and no ambiguity! 

I didn't have time yet today to work on the code. maybe later

**Comment by ly29** [comment]
Some testing needed to see how exactly a node reacts when we remove it's backing class, but having thought about I think I will try the different approaches.

Somehow they seem simpler today, I think this can be resolved in a good way without too much issue.

Also I have some issues with the ```get_relinks(ng)``` function. The ```node.inputs[0].links``` interface should be avoided a much as possible for these kind for operations since it is slow, it is implemented as a python property and each access goes through all links the node group. 
It is better just to parse all links at once directly in ```ng.links```. How big effect it has in practice I am not sure but it disturbs me a bit.

**Comment by zeffii** [comment]
ok, do whatever you feel like doing :)  that was just my first-pass approach..

.. but am puzzled why a single call to `node.inputs[0].links` would need to cycle through all nodes, unless it is syntactic sugar for `[  ..  for n in nodes if n.outputs[:].links.to_socket == some_socket]`

**Comment by ly29** [comment]
```python
    @property
    def links(self):
        """List of node links from or to this socket"""
        return tuple(link for link in self.id_data.links
                     if (link.from_socket == self or
                         link.to_socket == self))
```
https://github.com/nortikin/sverchok/blob/group_experiment/utils/group_tools.py#L56-L59

**Comment by zeffii** [comment]
do i recall correctly that we did this straight from node_tree.links for IO/JSON too? for the same reason... i'm a bit rusty :)

**Comment by ly29** [comment]
Yeah but I think we went back that time because how the order of connections was important for the  nodes with dynamic sockets.

**Comment by ly29** [comment]
Some progress, editing via side panel now works.

**Comment by zeffii** [comment]
each new socket aquisition after monad creation requires the monad instance to make a new class? (to make sure it has the props locally) ?

**Comment by ly29** [comment]
Yeah, so each new monad instance has the right metadata and properties. 
Strictly speaking I guess we only _really_ need it for properties. Socket names could be gotten directly from the monad input/output nodes.

**Comment by ly29** [comment]
But I prefer the metadata route because otherwise editing of the monad that doesn't change the monad interface could result in different properties expected. 
In best case the interface I made in the monad for updating the class is all we need, just add it to the operators and everything works. 
Would be great if you could test that actually

**Comment by zeffii** [comment]
i have time this-morning. will pull first.

**Comment by zeffii** [comment]
```python
ImportError: cannot import name 'SverchCustomTreeNode'
```

**Comment by ly29** [comment]
Oops
I know what went wrong, circular import dependency in ```node_tree.py``` remove the ```from sverchok.utils.sv_monad import make_class_from_monad``` and consider ```monad.update_cls()``` to be broken, at least for now.

**Comment by zeffii** [comment]
ok will pull :)

**Comment by ly29** [comment]
Actually the tree definition should probably be in ```monad_tools```

**Comment by zeffii** [comment]
showing two name properties on the UI ?
![image](https://cloud.githubusercontent.com/assets/619340/17582139/46b4c82c-5faa-11e6-8680-d2c2af845e31.png)

yeah putting the tree def in monad_tools (or something more descriptively named)

**Comment by ly29** [comment]
Yes, it was a test for how to deal with namning of the ```monad```, I guess we will have to look at 
```python
         c.prop(self, 'group_name', text='name') 
         c.prop(bpy.data.node_groups[self.group_name], "name", text='name') 
```
One is the name belonging to the node, the other is the name of monad.

**Comment by ly29** [comment]
The renaming of a monad give me some problems. 
Right now the name of a monad is directly related to the ```.bl_idname``` in way that is directly related to it. That felt natural but isn't strictly necessary I guess.
The important thing is that from a monad we can generate a unique and repeatable name such a way that the relation ```monad -> class.bl_idname``` is assured. There is strictly no reason for it to be the monad name...

```python

def make_valid_identifier(name): 
     return "".join(ch for ch in name if ch.isalnum() or ch=="_") 

...
    cls_name = "SvGroupNodeExp{}".format(make_valid_identifier(monad_name))
...
```

The monad ```cls.bl_idname``` could be assigned upon creation and remain static, then changing the monad name is less of a problem.

**Comment by zeffii** [comment]
maybe the only time a user might see a monad (tree) name is if they 
  - link/append from a different blender  ..or 
  - using the dynamic menu which populates the groups submenu..

i'd be comfortable never seeing the tree name, and working solely with the name as it appears on the monad instance, the monad_instance name and monad's (tree) name don't need any correlation.

**Comment by ly29** [comment]
Could introduce a property for the node to keep track of the monad from the node and use the class ```bl_idname``` as identifier. If proves slow we could provide a dictionary for lookup.

```python
    @property
    def monad(self):
          for tree in bpy.data.node_groups:
               if tree.bl_idname == 'SverchGroupTreeType' and self.bl_idname = tree.cls_bl_idname:
                     return tree
          return None # or raise LookupError or something
```
Also in the monad it would be nice with property highlightning the monad input and output nodes.

Which leads to elegant code without the lookup in blender all the name.
```python
# in say node.process
monad = self.monad
outputs = monad.input_node.outputs
# etc
```

As you might notice I really like propertys right now, I think they clean up code a lot.

**Comment by zeffii** [comment]
it seems as you get deeper more and more elegant ways emerge organically. maybe it's better if I stay away entire from the code :)

**Comment by ly29** [comment]
Maybe :) I don't think so however. 
I think have the whole dynamic monad class thing worked out.

Would be good think about how monad in monad editing works out.

**Comment by zeffii** [comment]
one thing i'd like would be to draw the name of the monad in the bottom left, I didn't explore how to do that. I think it has something to do with how i'm forcing the overlay
```python
        # by switching, space_data is now different
        path = context.space_data.path
        path.clear()
        path.append(parent_tree) # below the green opacity layer
        path.append(monad)       # top level
```

**Comment by ly29** [comment]
Some issues left to deal with are also how - to expand the monad into nodes
- the name change, like .prop_search with filter, switching between monads (the latter part is low priority)

**Comment by zeffii** [comment]
i'm not aware of prop_search with filter.. it will have to either be a dynamic collection (and use prop_search) or use a UIList (which does have some filter)

**Comment by zeffii** [comment]
ooh.. whats this ` [bpy.props.RemoveProperty](https://www.blender.org/api/blender_python_api_current/bpy.props.html#bpy.props.RemoveProperty) `

**Comment by ly29** [comment]
For properties defined directly on bpy.types.SomeClass I think

**Comment by ly29** [comment]
I guess we could have used that to add properties to a monad class actually. Still it is class wide and would require a somewhat convoluted naming scheme.

**Comment by ly29** [comment]
Everything seems to be working, except updating the class definition when a socket reconnect, however if you trigger that by editing via the sidebar it starts working again. Don't have time to bug hunt right now.

**Comment by ly29** [comment]
There probably are more bugs lurking, so if you have time to do some testing I would be very happy.

**Comment by zeffii** [comment]
okidoki..  

> except updating the class definition when a socket reconnect

i'm not sure what you mean... as long as it handles the svdummy connection to make fresh socket, it 's essentially working. I intentionally didn't auto change sockets if a socket was disconnected and reconnected with a different node. But now as there are props on the node_instance, maybe that does make sense..

**Comment by ly29** [comment]
Yeah managing properties is area of further development and much possibility. 
However, when you connect to the dummy socket for some reason the monad class doesn't update ad expected. 
So if you connect to the dummy a new socket is created but the class isn't updated correctly until you trigger somehow.

**Comment by zeffii** [comment]
I see .. it doesn't display the  `.prop_name` / slider after a disconnect reconnect until after an update is triggered..

**Comment by zeffii** [comment]
but that's the case even on fresh sockets, seems like the process function of the IO nodes needs a few extra awareness statements and trigger self.update() from there?

**Comment by zeffii** [comment]
I edited the previous comment.

**Comment by ly29** [comment]
In ```SvSocketAquisition.update``` the class definition should be updated. However dealing with things in the ```update``` function is horrible in general, since it gets called so many times leading to very defensive code being needed...
https://github.com/nortikin/sverchok/blob/dynamic_monad_node/utils/sv_monad_tools.py#L621-L653

Perhaps moving the update in this case to the ```monad.update()``` which could verify the class definition against itself and trigger an update when needed.

Or something else is going on.

**Comment by zeffii** [comment]
> dealing with things in the update function is horrible in general, since it gets called so many times leading to very defensive code being needed...

clearly not what we want, may it's possible to have a ui update only  like tag a node for ui updates. this is something i've never understood in blender, the tag system.

**Comment by zeffii** [comment]
maybe a quick hack is 
```
parent.hide = True
parent.hide = False
```

**Comment by ly29** [comment]
One thing that could be tested done is to update the class definiton before updating the children, since that way the property will exist.

**Comment by zeffii** [comment]
that doesn't appear to cause a ui update either..

**Comment by ly29** [comment]
Didn't expect it to, really, but at least it is sane. To make sure the class definition and property exist before it is displayed.

**Comment by zeffii** [comment]
hmm, something weird is happening now.. when I drag a noodle blender is closing to desktop..

**Comment by zeffii** [comment]
even if i'm just panning around the node view.

this could be a ram issue here tho..but if reverting that code change resolves it I'd be weary of it.

**Comment by ly29** [comment]
revert and test.

**Comment by zeffii** [comment]
also the console says:
```
C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py:207
rna_uiItemR: property not found: SvGroupNodeExpMonad.z_
```  
so it is looking for it..

**Comment by zeffii** [comment]
I added debug code in the update function of `SvSocketAquisition`  apparently that seems to have caused  it..

**Comment by ly29** [comment]
It is very easy to trigger the update functions to go into crazy mode causing recursive updates. Something that **will** crash blender.

**Comment by zeffii** [comment]
it seems like the class made after the socket connect ( lets take virgin connection for example) will not include the new property?

**Comment by zeffii** [comment]
chronologically:

> drag new socket to svdummy
```
making class from Monad
{'y_': (<built-in function FloatProperty>, {'attr': 'y_', 'precision': 3, 'name': 'Y', 'update': <function updateNode at 0x000001996B8DBEA0>, 'default': 0.0, 'description': 'Y'}), 'angle_': (<built-in function FloatProperty>, {'attr': 'angle_', 'name': 'Angle', 'update': <function updateNode at 0x000001996B8DBEA0>, 'options': {'ANIMATABLE'}, 'default': 0.0, 'description': 'rotation angle'}), 'stop_': (<built-in function FloatProperty>, {'attr': 'stop_', 'name': 'stop', 'update': <function updateNode at 0x000001996B8DBEA0>, 'options': {'ANIMATABLE'}, 'default': 10, 'description': 'stop'}), 'start_': (<built-in function FloatProperty>, {'attr': 'start_', 'name': 'start', 'update': <function updateNode at 0x000001996B8DBEA0>, 'options': {'ANIMATABLE'}, 'default': 0, 'description': 'start'}), 'y': (<built-in function FloatProperty>, {'name': 'y', 'attr': 'y', 'update': <function updateNode at 0x000001996B8DBEA0>, 'default': 1}), 'input_template': [['Stop', 'StringsSocket', 'count_'], ['Y', 'StringsSocket', 'y'], ['Start', 'StringsSocket', 'start_'], ['Step', 'StringsSocket', 'stop_'], ['Y', 'StringsSocket', 'y_'], ['Angle', 'StringsSocket', 'angle_']], 'count_': (<built-in function IntProperty>, {'attr': 'count_', 'min': 1, 'name': 'count', 'update': <function updateNode at 0x000001996B8DBEA0>, 'options': {'ANIMATABLE'}, 'default': 10, 'description': 'num items'}), 'output_template': [['Vectors', 'VerticesSocket']], 'bl_idname': 'SvGroupNodeExpMonad'}
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\core\update_system.py", line 318, in do_update_general
    node.process()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_monad_tools.py", line 177, in process
    data = socket.sv_get(deepcopy=False)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 188, in sv_get
    raise SvNoDataError
Node Group Exp had exception
rna_uiItemR: property not found: SvGroupNodeExpMonad.mindist
```

**Comment by ly29** [comment]
Yeah, for some reason the ```make_class_from_monad``` in the nodein/out update function doesn't actually update the class.

**Comment by zeffii** [comment]
it makes the class but with stale data?

**Comment by ly29** [comment]
I seems to, the why is unclear.

I want to test the following, move the ```make_class_from_monad``` out of the ```update``` function and into the monad update function, the layout level ```update``` is called after all node level ```update```.
It is bit more editing than I am happy to do with the github web editor...
Move the monad definition from ```node_tree.py``` into ```sv_monad_tools.py``` and add a a call to the make class from monad function.
That might work, or not.

**Comment by zeffii** [comment]
there's no haste with this. if you want to do it take your time, do it on your preferred setup.

i'll be doing other stuff anyway.

**Comment by ly29** [comment]
Did some further testing and it didn't work out either, however since we know what data should be added to the class, we could simply provide directly instead of parsing it...

**Comment by ly29** [comment]
Did the suggest shuffling, did work out either. Also got some crashes...

**Comment by zeffii** [comment]
yeah, like weird stuff can cause it to crash..  i suspect it has something to do with
```python
        # by switching, space_data is now different
        path = context.space_data.path
        path.clear()
        path.append(parent_tree) # below the green opacity layer
        path.append(monad)       # top level
```

**Comment by zeffii** [comment]
also in Lukas Toenne's implementation he doesn't have to do that... we miss a subtle detail i think..

**Comment by zeffii** [comment]
but .. he also has lines like this which I think relate to the same problem we have
```python
               # XXX this shouldn't be necessary, but node updates are terrible
                groupnode.update()
```

**Comment by zeffii** [comment]
he does !! :)
```python

        if exit:
            space.path.pop()
        else:
            space.path.append(node.id, node)
```
whereas I'm only appending the node tree there..

**Comment by ly29** [comment]
Okay I see the problem now, the ```monad_monad_from_class``` filters out unlinked socket which, the newly connect socket is when the location is reached. somehow the changes made by ```replace_socket``` aren't available until later...

**Comment by zeffii** [comment]
refresh this page

**Comment by ly29** [comment]
Done it.
Also solved the stale data problem.

**Comment by zeffii** [comment]
```
** Sverchok loaded with 181 nodes **
Exception in module register(): 'C:\\Users\\zeffi\\Desktop\\scripts\\addons_contrib\\sverchok\\__init__.py'
Traceback (most recent call last):
  File "C:\Users\zeffi\Downloads\blender-2.76\blender-2.76.0-git.50a19cc-AMD64\2.77\scripts\modules\addon_utils.py", line 349, in enable
    mod.register()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\__init__.py", line 156, in register
    m.register()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\node_tree.py", line 398, in register
    bpy.utils.register_class(SverchGroupTree)
NameError: name 'SverchGroupTree' is not defined
```

**Comment by ly29** [comment]
Wait a sec

**Comment by zeffii** [comment]
it's OK i'm going for a walk :)

**Comment by ly29** [comment]
Now, have a nice walk.

**Comment by ly29** [comment]
So basically what happened was that the socket wasn't considered linked.

So remade the ```make_class_from_monad``` to be aware of ```SvDummySocket``` and created the class first, then to the black magic of removing socket etc.

Also using the class metadata for the info for the new socket name, properties etc. This keeps the logic in one place.

```python
        if socket_list[-1].is_linked:

            # first switch socket type
            socket = socket_list[-1]

            monad = self.id_data
            cls = make_class_from_monad(monad)
            if kind == "outputs":
                new_name, new_type, prop_name = cls.input_template[-1]
            else:
                new_name, new_type = cls.output_template[-1]
                prop_name = ""

            # if no 'linked_socket.prop_name' then use 'linked_socket.name'
            replace_socket(socket, new_type, new_name=new_name)

            for instance in monad.instances:
                sockets = getattr(instance, reverse_lookup[kind])
                new_socket = sockets.new(new_type, new_name)
                if prop_name:
                    new_socket.prop_name = prop_name

            # add new dangling dummy
            socket_list.new('SvDummySocket', 'connect me')
```

Now I think it needs some testing.

**Comment by ly29** [comment]
Then on to the next stage, with a new issues.

- Editable properties, select if there are many to pick from. This would require some extra metadata perhaps.
- Sorting the links by y
- Upgrading old beta node groups magically
- Group the code in logical blocks

**Comment by zeffii** [comment]
it feels close!    https://github.com/zeffii/weblog/blob/master/blends/experimental/test_head_tail.blend this one fails to Ctrl+G

**Comment by ly29** [comment]
Which nodes fails? I will try to have a look tomorrow. 
I think there might be some issues with nodes with dynamic sockets and perhaps with connections while creating the monad. 
Also some sanity checks for bad node groups might be in order...

**Comment by zeffii** [comment]
the initial ctrl+G fails to populate the parent _monad_instance_node_ inputs (and probably doesn't get to the outputs)

**Comment by ly29** [comment]
So what happened is I did some refactoring and changed the names of some variables so that bad data was stored in the class template, causing the *monad_instance_node.sv_init* to fail.

**Comment by zeffii** [comment]
the todo item `Choose/custom properties (far out)` would mean being able to set custom props with custom limits min/max. That would be neat!


I might make an operator that takes a short text file and generates from it a new empty monad_instance with props and mins and maxs like

```python
inputs = {
    0: dict(name='name1', prop_type="S", default=20, min=2, max=35, softmin...  ),
    1: dict(name='name2', prop_type="V", default=(2,1,2), min=0, max=3, softmin... ),
    ....
}

# optional.. as user can build this as needed
outputs = {
   0: dict(name='outname1', prop_type="S"),
   1: dict(name='outname2', prop_type="V"),
   2: dict(name='outname3', prop_type="M")
}
```

btw , SvGroupEdit should be this instead:
```python
class SvGroupEdit(Operator):
    bl_idname = "node.sv_group_edit"
    bl_label = "edits an sv group"

    group_name = StringProperty()

    def execute(self, context):
        ng = bpy.data.node_groups
        node = context.node
        parent_tree = node.id_data

        monad = ng.get(self.group_name)
        if not monad:
            monad = monad_make(new_group_name=self.group_name)

        # bpy.ops.node.sv_switch_layout(layout_name=self.group_name)

        # by switching, space_data is now different
        path = context.space_data.path
        # path.clear()
        # path.append(parent_tree) # below the green opacity layer
        path.append(monad, node)       # top level

        return {"FINISHED"}
```
it will allow us to ditch the SvTreePathParent(Operator) and button.

**Comment by zeffii** [comment]
I don't know if that breaks other assumptions... but if it does those assumptions should be revised .. (probably my fault at the beginning)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17648091/f8d82f38-6209-11e6-9828-0d5271d2de88.png)

**Comment by zeffii** [comment]
A dig around in the C implementation might reveal how to properly populate that bottom left text..

**Comment by ly29** [comment]
Take a shot at changeing that. 

Custom props and editing sounds like new issue.

**Comment by ly29** [comment]
Try the instance.label

**Comment by zeffii** [comment]
ok// let's not replace the Back button yet :) it's a snake pit :)

**Comment by zeffii** [comment]
despite the fact that it's not hidden but greyed out.. i do like the `sv_parent` button and its location, the standard back button almost seems too camouflaged between other unrelated stuff..

**Comment by ly29** [comment]
Yeah, I doubt anybody uses that hidden button, everybody probably just have to learn the tab as method for going in and out of groups...

**Comment by zeffii** [comment]
hehe.. i've never tabbed out of a monad..   tab will call the one that doesn't work for monads

**Comment by zeffii** [comment]
i didn't look very hard, but is there a simple way to get a reference to the monad_instance_node if I have a reference to the monad ?

**Comment by ly29** [comment]
```python
>>> monad = D.node_groups['Monad']
>>> monad.instances
[bpy.data...nodes["Group Exp"]]
```

**Comment by ly29** [comment]
Some clean up of the code could be in order since it uses many different ideas of to do things in one file.

**Comment by ly29** [comment]
![skarmavbild 2016-08-14 kl 14 55 06](https://cloud.githubusercontent.com/assets/6241382/17649213/2c947b9a-622f-11e6-8883-e641efeeae51.png)
Only show the button inside a node group. Yes or no?
[flexible_parent_button](https://github.com/nortikin/sverchok/tree/flexible_parent_buttonl)

**Comment by ly29** [comment]
Also moved the menu options to our own menu copying standard blender.

**Comment by zeffii** [comment]
yes!  only show button inside a node_group. works for me.. and is obvious to the user where to press.. 

would be great to ditch the unused `node.parent_group_path` operator.. but the code for that is a little ugly ( altho maybe not so ugly with dynamic programming)

**Comment by ly29** [comment]
okay merged it.

**Comment by zeffii** [comment]
neat!

I remember with IO/json node tree creation there was some difficulty doing automatic zooms of the tree, so it doesn't appear off screen / inconveniently positioned. Not sure I ever solved that (the operator `ops.node.view_all` and `ops.node.view_selected` didn't seem to work in that scenario, 

but here they should..

**Comment by zeffii** [comment]
but then again... do we always want to have the view zoom.. it might turn out annoying too..

**Comment by zeffii** [comment]
`bpy.ops.node.view_all()`  is not bad at the end of `SvMonadCreateFromSelected`

**Comment by zeffii** [comment]
yloc sorting.. for input nodes is a little bit easier than outputs...
```python
    # def relink_monad(links, monad):

    def yloc(item):
        return item[0].node.location[1]

    for m_idx, (k, v) in enumerate(sorted(input_links.items(), key=yloc)):
       ...
```

**Comment by zeffii** [comment]
hmm, the above isn't as deterministic as I thought.. scrap it.

**Comment by zeffii** [comment]
for outputs...i dunno  
 - first by destination node's Y loc, and 
 - if multiple sockets go to one node, then individually by socket index.

**Comment by zeffii** [comment]
Whats the Multisocket issue about? do we have nodes that auto shrink inputs/outputs if sockets are disconnected?

**Comment by ly29** [comment]
For outputs by the ```link.from_node.location.y``` feels good. So the sockets are located in the order of the nodes. Also the advantage that there is only one node by socket.
Actually if we generate a a tuple ```(loc_y, socket_index)``` and sort by that it could get kind of nice.

**Comment by ly29** [comment]
If the node directly connected to the monad input node is multi socket node, like formula, it needs to to be connected in increasing order. The copy operator deals with that fine.
![skarmavbild 2016-08-14 kl 18 18 52](https://cloud.githubusercontent.com/assets/6241382/17650349/97bb1836-624b-11e6-8559-46aaf3942578.png)
![skarmavbild 2016-08-14 kl 18 18 18](https://cloud.githubusercontent.com/assets/6241382/17650350/97fc581e-624b-11e6-8b22-79a63d0ea428.png)

But this works fine.

![skarmavbild 2016-08-14 kl 18 17 50](https://cloud.githubusercontent.com/assets/6241382/17650354/baddbed6-624b-11e6-9bb4-09285a1e4c3c.png)

Solution, sort connections for relink by socket index.

**Comment by ly29** [comment]
So basically the socket collection code needs a massage for these two problems, two birds with one stone time.

**Comment by ly29** [comment]
I did some short code to collect the links.
```python
    in_links = [l for l in ng.links if (not l.from_node.select) and (l.to_node.select)]
    out_links = [l for l in ng.links if (l.from_node.select) and (not l.to_node.select)]
```
And something like below for sorting.
```python
def get_socket_index(socket):
    if socket.is_output:
         sockets = socket.node.outputs
    else:
         sockets = socket.node.inputs
    for i, s in enumerate(sockets):
         if s == socket:
             return i

def sort_keys_out(link):
     return (link.from_node.location.y, get_socket_index(link.from_socket))

def sort_keys_in(link):
     return (link.from_node.location.y, get_socket_index(link.to_socket)

in_links.sort(key=sort_keys_in)
out_links.sort(key=sort_keys_out)
```

**Comment by zeffii** [comment]
what if the direct connection is a reroute terminal  ? ( i didn't try )

**Comment by ly29** [comment]
Good point.

**Comment by zeffii** [comment]
```python
def get_socket_index(socket):
    node = socket.node
    sockets = node.outputs if socket.is_output else node.inputs
    for i, s in enumerate(sockets):
         if s == socket:
             return i
```

**Comment by ly29** [comment]
As far I can tell python sorts by many numbers if if you give a tuple sort sorting, so we can give as many things we want to sort by as needed.
```python
>>> sorted([(10,2), (11, 2), (10,1)])
[(10, 1), (10, 2), (11, 2)]
```

**Comment by zeffii** [comment]
yep.. if first item is tied, it uses next item in the tuple..

**Comment by ly29** [comment]
Yeah wanted to confirm after my min max confusion...

**Comment by ly29** [comment]
Could stick index as a property on the socket to cleanup the code a bit.

**Comment by zeffii** [comment]
as a property of all sockets? base class?
```python
@property
def index(self):
   ...
```

**Comment by ly29** [comment]
Yeah, on all our sockets

**Comment by zeffii** [comment]
does that mean state-book-keeping .. or is it something like 
```
@property
def index(self):
    # if not outputs..
    for idx, socket in self.node.inputs:
        if socket == self:
            return idx
```
haha :)

**Comment by ly29** [comment]
```python
    @property
    def index(self):
        node = self.node
        sockets = node.outputs if self.is_output else node.inputs
        for i, s in enumerate(sockets):
             if s == self:
                 return i
```

**Comment by zeffii** [comment]
lol <3

**Comment by ly29** [comment]
Okay, redid the collecting of links, felt easier than re doing your code, not fully sorting on ```.location.y``` yet however.
It does need some more testing but right now takes care of the relevant cases, I think. I leave the old code for now.
Sorting the links proved more subtle than I thought...
