### ISSUE TITLE
Coloring Object Output from MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#791]
It's me again, asking silly question.

I am back to Sverchok and comparing it with AN. In term of instancing and coloring objects, supposed to be simple.

I understand there is this Vertex coloring, but even that seems complicated (I have not read the documentation, maybe after this).

I have been reading some of Elfnor awesome blog post on Sverchok and he even made some articles about coloring objects generated in Sverchok:
http://elfnor.com/shaders-for-sverchok-01-object-info-node.html

Supposed I am being old school and just want to random colorize the Object Color. Is there the most efficient and recommended way to do this using Sverchok?

In AN, I can target it using Object Attribute Out node >> directly to color data.

**Comment by enzyme69** [comment]
@zeffii MK2 Viewer cannot display vertex color data, can it? Even after reading this article a couple of times, I still don't get it.

http://elfnor.com/shaders-for-sverchok-04-vertex-colors-update.html

Who made the Vertex Color node and no documentation and although Elfnor can work it out (amazing), I have a headache trying to undertand this node. At least need example per node. 

I think no matter how powerful, Sverchok is still too puzzling to use, sometimes.

**Comment by zeffii** [comment]
@enzyme69

@elfnor is not a he but a she :) I attribute her success with these undocumented nodes to her tendency to read the code behind the nodes. If the documentation doesn't say it, the node's code surely does. It is the best way to really understand how a node works. I will keep saying this :)

I think it was KO who wrote VertexColor node, I have not used it.

Viewer Draw MK2 / BMeshView weren't intended to show vertex colors, it' s something we did think about and maybe later versions will. For BMeshViewer I can see it would be useful..no argument there.

**Comment by zeffii** [comment]
I think the vertex color node is also just for sending vertex colors to existing scene objects.. not for the output of BMeshViewer   (BMeshviewer might overwrite the mesh data of an object after the VertexColor node assigns vertex colors to it)  this is down to where in the node tree each node is..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17625229/36142482-60a8-11e6-8aec-ed875a1922ac.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17625267/63a84388-60a8-11e6-9fc6-587d2c66bf3e.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17625469/4b200098-60a9-11e6-968a-419a101b6c7c.png)

**Comment by zeffii** [comment]
infact .. if you look at the history of the Vertex Color node, @elfnor even contributed a bit of Python to it :)
https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/colors.py
https://github.com/nortikin/sverchok/commit/04affe7de115cb96b287345664b4604220af6d8d

**Comment by zeffii** [comment]
> just want to random colorize the Object Color. Is there the most efficient and recommended way to do this using Sverchok?
![image](https://cloud.githubusercontent.com/assets/619340/17627453/9090c632-60b1-11e6-9f92-93b01c7f8214.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17630583/342974a2-60c0-11e6-8266-88701ec0de2e.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17631032/8ef2e7ea-60c2-11e6-98ee-3a8fbc726083.png)

**Comment by zeffii** [comment]
a simple approach to editing vertex colors of objects made in Sverchok, is to use a second layout / node tree:)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17633804/82bfd4f8-60cf-11e6-9311-e90181c81482.png)

**Comment by zeffii** [comment]
A few take-away's may be worth adding to the node docs..

- BmeshViewer doesn't create `Sv VColor` map
- When you have a setup like the above image, the VertexColors node marked `1` will be the first to generate `Sv VColor`, (it will appear in the dropdown) then click the dropdown in node `2` and you'll see it.

I can see why this is not very obvious..

**Comment by enzyme69** [comment]
![screen shot 2016-08-13 at 11 17 14](https://cloud.githubusercontent.com/assets/3952687/17640642/a15699ba-6147-11e6-83bf-b79d438575f4.png)

Thanks a lot Zeffii...! You are the man.

Hey, I still cannot get around my head to "color each object" even after joining the mesh. I have spent few hours on it last night and this morning. Kind of understand, but still finding surprise here and there.

Let me read you explanation above...

**Comment by enzyme69** [comment]
You are completely right in actually digging inside the code that creates the node. That will be in my list of habit. NOTED!

**Comment by enzyme69** [comment]
I almost completely understand, but just one more thing is missing:
1) If we are generating multiple Alpha objects
2) Then I want to colorize each and every object, how is this possible with no slot to pipe in the objects?

Another way I could think is to join the mesh then colorize them as one, and using some weird Sverchok lists. 

I will re-read Elfnor's post.....

**Comment by zeffii** [comment]
It would make more sense to:

- make a modified BMesh viewer MK2, with an output containing references (or just the names) of the objects it created, and..
- a modified version of VertexColors node which takes an extra input (a list of named object, exactly the data that the modified BMeshViewer would be outputting)

Otherwise yeah, there are lots of workarounds. Unfortunately at the moment, all a bit ugly.

**Comment by ly29** [comment]
Yes that is the way forward. But the bmesh viewer should also be able to deal with mesh objects instead decomposed mesh objects. I did experiments with a branch with some new sockets and data types way back. However I abandoned it due to some different opinions on how to proceed. Oh well

**Comment by zeffii** [comment]
i totally think an object socket type would be great. If I didn't back then, then I do now ( but I think I did ..ad even implemented it in Flow because it made sense to compose objects as a separate stage prior to hitting the builder/viewer node)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17642253/94a6e624-613e-11e6-9e60-4f659d9e338e.png)

**Comment by zeffii** [comment]
i'll make a branch for it..

**Comment by zeffii** [comment]
I didn't have time to finish it.. but I did make an excellent infinite-loop generator. :)

**Comment by ly29** [comment]
Not enough of those around :)

**Comment by zeffii** [comment]
probably it's better to push the vertex colors at the same time as the mesh creation _inside_ BMeshViewer, else there's a bit of wasted processing..

@enzyme69 I don't really feel like modifying VDMK2 further, a MK3 would be more appropriate but it's not exaclt high on my _todo_.

**Comment by enzyme69** [comment]
Ok in that case we will leave it there :dash:
