### ISSUE TITLE
Matrix Iterate issue

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#792]
I don't know why I keep getting frozen Blender when creating this node tree setup. I must have done something wrong / bad.

![screen shot 2016-08-12 at 23 49 41](https://cloud.githubusercontent.com/assets/3952687/17624380/bb9edd74-60e7-11e6-9940-f27afda28c52.png)

**Comment by zeffii** [comment]
use fewer iterations.. set to 2 first..

**Comment by zeffii** [comment]
also set to Random Vector count to 2 first too..and gradually increase them. With this node you'll generate many thousands of matrices before you know it.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17626043/d9f2dab4-60ab-11e6-9eeb-e98d12553596.png)

**Comment by zeffii** [comment]
it's not really a bug, but I will fully agree that the Iterate node can easily produce unexpected -- cpu killing -- results.

**Comment by stansu** [comment]
Iterate matrix transformation's output is not a matrix.
![screenshot from 2019-02-15 11-27-26](https://user-images.githubusercontent.com/9460236/52832713-b35f8780-3114-11e9-8ab0-00c0293e0bba.png)

**Comment by zeffii** [comment]
thanks @stansu  we appear to have overlooked that node in the list44->matrix conversion change. will fix asap.

**Comment by zeffii** [comment]
the offending line being 

https://github.com/nortikin/sverchok/blob/f053deb6bb1024667c610ee2d02e5d88718b7754/nodes/modifier_change/iterate.py#L183-L184

we are degenerating the matrix there, it doesn't need that function call any more.
