### ISSUE TITLE
OpenGL crash on empty edge/polygon data

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#797]
![skarmavbild 2016-08-15 kl 09 27 56](https://cloud.githubusercontent.com/assets/6241382/17658310/08f42b3a-62cb-11e6-9394-83f18922f827.png)

Crash is repeatable by turning on the viewer draw and set the marked field to 0.

The debug print output.
```
vertices = [[(0.0, 0.0, 0.0)]]
edge_data = ([],)
```

Old debug issue thread #495, Line issue with original bug report  #793

**Comment by zeffii** [comment]
maybe line shouldn't be outputting [single vert + empty edge] combos either..

**Comment by ly29** [comment]
For some reason the bad polygon data isn't triggering an exception but leads to a bad callback being generated...

No it should't.

**Comment by zeffii** [comment]
in 
https://github.com/nortikin/sverchok/blob/master/ui/viewer_draw_mk2.py#L317-L342

maybe an explicit test for the `verlen` ,
```python
for i, matrix in enumerate(data_matrix):
            k = get_max_k(i, verlen)
            if verlen <= 2:
                continue
```
and also for the polygons..

**Comment by zeffii** [comment]
weird.. it does'nt crash here..

![image](https://cloud.githubusercontent.com/assets/619340/17660296/cd594f34-62d8-11e6-89c8-ce55c1cd876a.png)

So.. i can only suggest a likely non-invasive modification..

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/vdmk2_verlen_check  ?

**Comment by zeffii** [comment]
hmm, it doesn't even reach my code :)

**Comment by ly29** [comment]
I will test soon, doing some other test for props.

**Comment by zeffii** [comment]
can't reproduce so will have bail on this one.
```python
>>> import bgl
>>> bgl.glGetString(bgl.GL_VERSION)
'4.0.0 - Build 10.18.10.4276'
```

**Comment by ly29** [comment]
Yeah, might be Mac OS X specific.

**Comment by zeffii** [comment]
I haven't updated blender since 2016-07-09:
```
>>> bpy.app.version
(2, 77, 1)
```

**Comment by ly29** [comment]
Well, mine is older than that... It is tricky because the OpenGL error might be hiding in so many different ways. One option is to turn of all sanity checks inside the drawing code and just having it crash.

**Comment by ly29** [comment]
```python
>>> bgl.glGetString(bgl.GL_VERSION)
'2.1 ATI-1.42.15'
```
It depends of how the OpenGL is created which version you get on macOS, it is a bit of a mess to be honest... Sadly

**Comment by zeffii** [comment]
interesting, but annoying, bug :) thanks @enzyme69

**Comment by ly29** [comment]
Okay, found it.
If you disable the ```callback_disable``` from inside the callback it will crash.

**Comment by ly29** [comment]
It kind of makes sense that removing a callback from inside of it might cause problems...

**Comment by zeffii** [comment]
doesn't crash here either..

**Comment by zeffii** [comment]
also...yikes:
```python
        if (data_vector, data_polygons, data_matrix, data_edges) == (0, 0, 0, 0):
            callback_disable(n_id)
            return
```
perhaps
```python

        if not all(data_vector, data_polygons, data_matrix, data_edges):
            callback_disable(n_id)
            return
```

**Comment by ly29** [comment]
Yeah, that line was somewhat shocking.

**Comment by ly29** [comment]
It is the ```callback_disable``` that is causing it for me. Commenting it out prevents crashes for me, if it doesn't have any bad side effects for you I think we could remove the ```callback_disable``` or set an error condition in ```options``` perhaps

```python
        if sl2 and sl2[0]:
            if isinstance(sl2[0], int):
                callback_disable(n_id)
                return
```
https://github.com/nortikin/sverchok/blob/vdmk2_verlen_check/ui/viewer_draw_mk2.py#L396-L399

**Comment by zeffii** [comment]
yeah, seems OK <no funny business on this end>. don't quire recall why we are disabling the callback from inside the callback in the first place..

**Comment by ly29** [comment]
well intended book keeping, as long as the callback fails quickly until the node does something to update it has no practical effect.

**Comment by zeffii** [comment]
also..best leave ` if (data_vector, data_polygons, data_matrix, data_edges) == (0, 0, 0, 0): ` for now :)

**Comment by ly29** [comment]
version bump and merge and close this issue.

**Comment by zeffii** [comment]
sounds good.

**Comment by zeffii** [comment]
uchh. you push/nudge i'm not synced
