### ISSUE TITLE
Dynamic properties

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#798]
Setting the up the properties for monad would be more user if force them to certain values, creating custom limits as appropriate.

Lets us consider the property, take [FloatProperty](https://www.blender.org/api/blender_python_api_2_77a_release/bpy.props.html?highlight=bpy.props.floatproperty#bpy.props.FloatProperty) to start with.

There are a large number of properties to consider, almost of them could be considered valid to edit. So let us focus on mechanism for now.

```
>>> bpy.props.FloatProperty()
(<built-in function FloatProperty>, {})

# on List Range Int Node
>>> node.rna_type.start_
(<built-in function IntProperty>, {'options': {'ANIMATABLE'}, 'description': 'start', 'default': 0, 'attr': 'start_', 'update': <function updateNode at 0x116c1a2f0>, 'name': 'start'})
```
So when we copy the property from the node to the monad class we simply copy the data.
```python
# some more things going on to ensure a safe name etc.
prop_rna = getattr(other.node.rna_type, prop_name)
cls_dict[prop_name] = prop_rna

```
So what need to override the settings for the property when we create own custom one.

```python
prop_func, prop_dict = getattr(other.node.rna_type, prop_name)
prop_dict.update(custom_props[prop_name]) 
cls_dict[prop_name] = prop_func, prop_dict
```
Where ```custom_props``` is a ```defaultdict``` populated with the override properties.

Two problems, how to store the data used with ```custom_props``` and how to edit them in a good way.

### Storage
 I can imagine two methods right now, one simple and easy, one simple and slightly more cumbersome:
- serialize the ```custom_props``` to a StringProperty in the monad
- create a property group for each property type and store them in the monad

### Editing
Create a Operator for each property type we would need to edit that uses ```context.window_manager.invoke_props_dialog``` to display the properties.

**Comment by ly29** [comment]
![skarmavbild 2016-08-15 kl 11 38 45](https://cloud.githubusercontent.com/assets/6241382/17661022/eaec5696-62dc-11e6-8952-7a3a258528cd.png)

**Comment by ly29** [comment]
![skarmavbild 2016-08-15 kl 12 07 04](https://cloud.githubusercontent.com/assets/6241382/17661668/da8cd7c2-62e0-11e6-9c9a-ca8417fbd1dd.png)
Edit the property
![skarmavbild 2016-08-15 kl 12 07 18](https://cloud.githubusercontent.com/assets/6241382/17661667/da88e360-62e0-11e6-8686-3a7fe088fdc6.png)
Create a new monad instance node, which gets the default.

**Comment by ly29** [comment]
This needs some thinking to make in a general and somewhat clean way.

**Comment by ly29** [comment]
![skarmavbild 2016-08-24 kl 11 14 17](https://cloud.githubusercontent.com/assets/6241382/17925129/ff3b5654-69eb-11e6-988c-67261aea6dab.png)
Clear progress but some details to clear out. Almost but not quite works right now...
There are some logic issues with how sockets are named that I haven't quite sorted out yet...

**Comment by ly29** [comment]
Ok so there are number of possible bugs that not having this solved see #863

**Comment by zeffii** [comment]
where in the code do you think this will be solved?

**Comment by ly29** [comment]
In a couple of places. actually. 
Won't be today. 
When a property is created store the relevant settings and use that info for generating the class info instead of trying to generate each time.

**Comment by zeffii** [comment]
i have not paid much attention to the dynamic properties additions, are you saying that the abstraction breaks when setting a property with new/different limits min/max/ etc ...   but if the user stays away from that capability it - on the whole - works OK ?

**Comment by ly29** [comment]
It needs some testing and some tedious details. 
Too many things going on right now...

**Comment by ly29** [comment]
So this is more tedious than expected.

Right now when we add a property to the monad class we get the property info directly from the connected socket and copy it over.
But this property needs to be stored since if we continue to edit the same property should be used, also this affects when restart blender.

But since this affects how things work a bit more than expected and storing data in blender is slightly tedious... Some of the operators have to be aware of this also.

**Comment by ly29** [comment]
The code I keep writing for this keep being ugly and breaks older layouts. It is annoying

**Comment by zeffii** [comment]
what branch are you experimenting in ?

**Comment by ly29** [comment]
Haven't synced right now because I am unhappy with code, will think about it over night. 
And publish tomorrow.

**Comment by ly29** [comment]
Branch name is monad fixes, slowly taking issue by issue, bug after bug

**Comment by ly29** [comment]
![skarmavbild 2016-09-13 kl 11 22 19](https://cloud.githubusercontent.com/assets/6241382/18468473/74c18138-79a4-11e6-9a65-ce219232ab40.png)
Okay so things seems to be working, will test it more and try to break a bit here and there.

**Comment by zeffii** [comment]
hand it over to jimmy, he'll be far less kind to it :)

**Comment by ly29** [comment]
I broke it myself already, will limit editing to soft_min, soft_max, description and default for now I think...

**Comment by ly29** [comment]
It is a shame sometimes that only we use git and test things...
Anyway it is moving forward, backwards compatibility added but not without bugs.

**Comment by ly29** [comment]
@zeffii 
If you have time do some quick tests. Things to test.

- Edit Socket / property name
- Open old files

If nothing else breaks let us push to master and take it from there.

**Comment by zeffii** [comment]
Glad to hear you are getting to a better place with this code. It hardly resembles my first experiments anymore. I look at it and think "Yeah i barely know what that does anymore".

_old files?_  
How to weigh effort to retain backwards compatibility vs having streamlined working code. I have no old files to test with. Understanding the transient nature of this feature makes me reluctant to rely on it.

I do look forward to using it more, but its a busy time for me here.

**Comment by ly29** [comment]
Yeah, not over concerned about old files either. Old files as meaning a couple of days old...

The old files support is localized into one function that sets everything up so as such it isolated. There needs to be some comments and clean up but even then what is going on here isn't totally obvious. 

Will make an interface for I/O to use as now there is a need to save some things for the actual monad (in node_groups) as not just in the nodes themselves.

**Comment by zeffii** [comment]
oh yeah, IOJson would need to know more about all the params of a dynamic property, it is oblivious to those iirc.

**Comment by ly29** [comment]
Anyway want to get back to SN3 instead of this detour with monads.

**Comment by ly29** [comment]
I will merge tomorrow most likely, any bugs will have to be resolved then...

**Comment by ly29** [comment]
Merged
