### ISSUE TITLE
Upgrade node groups into monads

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#800]
A rough first draft is available, see [upgrade_nodegroups](https://github.com/nortikin/sverchok/tree/update_nodegroups)

Basically straightforward process.

**Comment by ly29** [comment]
Working, would be nice with some further testing.

**Comment by zeffii** [comment]
I don't have have any older .blends with frame-based node_groups.. so... : /

**Comment by ly29** [comment]
I have two versions right now, one breaks new monads, the other breaks old monads. Trying to resolve it...

**Comment by zeffii** [comment]
old node_groups / monads were all beta,  trying to make the new monad system behave nicely with all should (imo) be less imporant than picking the cleanest forward looking approach...

**Comment by zeffii** [comment]
tho.. i'm symapthetic towards the desire to offer a way to upgrade (automagically)

**Comment by ly29** [comment]
it ain't that much work. We are talking a file with 88 lines (including header). I don't expect to go up much but some points need to be resolved.

**Comment by ly29** [comment]
Okay, I consider it done now. If anybody has concrete layout that breaks we can resolve it then.
