### ISSUE TITLE
Show current git branch in node editor header

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#805]
This would be so extremely useful for development...

For me the following works well, in the blender console.

```python
import subprocess
import os
import sverchok
res = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                            stdout=subprocess.PIPE, 
                            cwd=os.path.dirname(sverchok.__file__))
branch = str(res.stdout.decode("utf-8"))
print(branch)
```

If it works for you I will implement it.

**Comment by ly29** [comment]
![skarmavbild 2016-08-16 kl 11 41 06](https://cloud.githubusercontent.com/assets/6241382/17694912/6aa541bc-63a6-11e6-8f23-f1faa33cf719.png)
[branch_side_panel](https://github.com/nortikin/sverchok/tree/branch_side_panel)

**Comment by ly29** [comment]
Perhaps the node editor after template would be a better place.

**Comment by ly29** [comment]
![skarmavbild 2016-08-16 kl 12 02 40](https://cloud.githubusercontent.com/assets/6241382/17695556/67563338-63a9-11e6-8baf-128543bf79b1.png)

**Comment by ly29** [comment]
Actually it would be easy to switch branches with this also but for now I would be happy with something like this.

**Comment by zeffii** [comment]
lovely. do it :)

**Comment by ly29** [comment]
@zeffii 
Does the command above work for you?

**Comment by zeffii** [comment]
no
```
fatal: Invalid symlink 'C:/Users/zeffi/Desktop/scripts/addons_contrib/sverchok': Function not implemented
```

i'm totally fine with it being added in a more prominent place.. as you first indicated.

**Comment by zeffii** [comment]
i have a folder called GITHUB, which i cloned `sverchok` into
from there I symlinked sverchok to a folder called `...../scripts/addons_contrib`

**Comment by ly29** [comment]
I totally fine accepting some limitations for when this works.
I have symlink from deep in my ```~/Documents``` directory where i have my sverchok to ```~/Library/Application Support/blender/2.77/scripts/addons``` or something.

[fatal: Invalid symlink](https://github.com/msysgit/msysgit/wiki/Why-am-I-getting-fatal-Invalid-symlink-....-Function-not-supported.-error-when-initcloneing) 
Some easy way to resolve the symlink?

**Comment by zeffii** [comment]
this doesnt work `path = os.readlink( path )`

**Comment by zeffii** [comment]
because `print(os.path.islink(path))`  also doesn't see `sverchok.__file__` as one..

**Comment by zeffii** [comment]
A user preference for `local - sverchok - repo` would alleviate the guesswork..  tho am not certain that the preference gets stored with enough permanency to make it practical..

**Comment by ly29** [comment]
```
$ cat .git/HEAD
ref: refs/heads/dynamic_monad_node
```
So something to open ```.git/HEAD``` could work as well, it is okay if is fragile for now, but using git directly feels better.

**Comment by zeffii** [comment]
tho... something like this should be universal
```python
import os, sverchok
head = os.path.join(os.path.dirname(sverchok.__file__), '.git', 'HEAD')
print(head)
with open(head) as headfile:
    print(headfile.readlines()[0].strip()[4:])
```

**Comment by ly29** [comment]
```
with open(git_head_file_path, "r") as file:
     for line in file:
           branch = line.split("/")[-1]
```

**Comment by zeffii** [comment]
yeah, wrap it in a try/except and anyone who has a git repo version of sverchok will be able to see the branch.

**Comment by ly29** [comment]
Something like this.
```python
BRANCH = ""

def get_branch():
    global BRANCH
    try:
        res = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                              stdout=subprocess.PIPE,
                              cwd=os.path.dirname(sverchok.__file__),
                              timeout=2)

        branch = str(res.stdout.decode("utf-8"))
        BRANCH = branch.rstrip()
    except: # if does not work ignore it
        BRANCH = ""
    if not BRANCH:
        head = os.path.join(os.path.dirname(sverchok.__file__), '.git', 'HEAD')
        with open(head) as headfile:
            branch = headfile.readlines()[0].split("/")[-1]
        BRANCH = branch.rstrip()
```

**Comment by zeffii** [comment]
a try/except around the `os.path` lookup too

**Comment by ly29** [comment]
Yeah, it is very ugly but should be safe...

**Comment by ly29** [comment]
Pushed updated version.

**Comment by zeffii** [comment]
```python
def get_branch():
    global BRANCH

    # first use git to find branch
    try:
        res = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                              stdout=subprocess.PIPE,
                              cwd=os.path.dirname(sverchok.__file__),
                              timeout=2)

        branch = str(res.stdout.decode("utf-8"))
        BRANCH = branch.rstrip()
    except: # if does not work ignore it
        BRANCH = ""
    if BRANCH:
        return

    # if the above failed we can dig deeper, if this failed we concede victory.
    try:
        head = os.path.join(os.path.dirname(sverchok.__file__), '.git', 'HEAD')
        branch = ""
        with open(head) as headfile:
            branch = headfile.readlines()[0].split("/")[-1]
        BRANCH = branch.rstrip()
    except:
        BRANCH = ""

```

**Comment by ly29** [comment]
Yeah, more sane to return if good, easier adding additional cases if needed that way.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/17700395/d7fa20ec-63c5-11e6-80e4-9566da1bc317.png)

It does this branch lookup once per sverchok registration cycle ?

**Comment by zeffii** [comment]
@nortikin may want to test branch to see how it reacts on a linux distro

**Comment by ly29** [comment]
```python
def register():
    get_branch()
    bpy.types.NODE_HT_header.append(node_show_branch)
```

**Comment by ly29** [comment]
If it works for @nortikin we push to master, I think it should fail gracefully.

**Comment by ly29** [comment]
I will push this now with the extra safety of not adding the header if ```BRANCH``` isn't defined.

**Comment by nortikin** [comment]
it works well.
