### ISSUE TITLE
 groups in IO/json per #782

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#810]
per https://github.com/nortikin/sverchok/issues/803

this is a topic in it's own right..

I feel like doing something experimental with the serialization. Failing that then I guestimate that the current IOjson code only needs minimal massaging to hold groups.

**Comment by zeffii** [comment]
i'm thinking perhaps less experimental.. 

the `layout_json` (dict) will take an additional key called 'monads`, into which each monad is serialized.

```json
{
"_all other keys_": [],
"monads": [
    {"name": "monad_name", "nodes": [ ]}
    {"name": "monad_name2", "nodes": [ ]}
]
}
```

**Comment by zeffii** [comment]
each monad_instance_node can be asked to produce the cls information needed to recreate at least the IO interface (outer and inner).

**Comment by ly29** [comment]
I agree, only small things are needed. 
Something like on import first import groups. 
Also if a group in group is found defer and make a second pass after all groups are created.

**Comment by ly29** [comment]
The monad class is created from the real monad, it is (right now) the only way to generate the actual class. Monad can uniquely identified from the ```monad.cls_bl_idname```.

Create monad:
1. Create monad
2. Set ````.cls_id_name```
3. Import all nodes into the monad
4. Call ```monad.update_cls()```
5. Create the monad instance node with ```.cls_bl_idname``` as node type.

**Comment by ly29** [comment]
Sometimes I think a generic group node without special class/properties support that you can use during these sort of situations would be a good idea.

**Comment by zeffii** [comment]
A dummynode just for the purposes of being able to first make / connect sockets, then fill appropriately with the monad it represents? A generic hotswap node function is needed anyway :)

**Comment by ly29** [comment]
Yeah, exactly.

**Comment by ly29** [comment]
![skarmavbild 2016-08-18 kl 10 44 27](https://cloud.githubusercontent.com/assets/6241382/17767584/cddbd580-6530-11e6-833c-a2d7a08d7171.png)

Look here:
It has 3 values to set after creation and then it behaves as the monad node except it does not have properties.

https://github.com/nortikin/sverchok/tree/dymmy_monad_node

**Comment by ly29** [comment]
Reading the old code I noticed we referred to sockets by name.

Also feel the need to impose some interface for nodes and shift responsibility to the nodes, would clean up the export code a lot and move responsibility to where it belongs.  Which given OO and all makes sense.

**Comment by ly29** [comment]
Dummy/generic monad node updated to handle be functional but without properties...

**Comment by zeffii** [comment]
not sure my brain is able for this now (or ever).

but I came to the same conclusion during the early stages of IOjson, nodes should have a function which the IOjson can call to get all the needed info. Many nodes can probably inherit a generic function, of the 180 nodes maybe 20 require individual instructions, but the others (iirc) follow a predictable pattern.

Also there's the `def __getattr__(self)` which we don't use anywhere in Sverchok, but has quite magical possibilities. see https://github.com/zeffii/pyBLOK/blob/master/core/blok_functions.py#L202-L236

**Comment by ly29** [comment]
I think it is topic worth revisiting. the ```__getattr__``` is fantastic but is hasn't quite worked itself into my vocabulary so to speak

**Comment by ly29** [comment]
Ended up reading about __getattribute__ as well. Fun stuff. 
Python is fantastically flexible in so many ways.

**Comment by zeffii** [comment]
cool, i have never used `__getattribute__` [nice writeup](http://stackoverflow.com/a/38788326/1243487). looks like fun

**Comment by ly29** [comment]
The dummy/generic node is in master now. It also helps with linking & append scenarios.

**Comment by ly29** [comment]
Was thinking if we remake this we drop the old export code but keep the old importer for older versions of the json files. 
To be less bothered with compability considerations => cleaner code.

**Comment by zeffii** [comment]
best way to proceed. imho.. and new code would be written with redux in mind i hope.. :)

**Comment by ly29** [comment]
As a side note a shocking number of template fail to import or contain old nodes.

**Comment by zeffii** [comment]
maybe the template menu should parse the descriptor of each template first, cache them, and grey out those templates that where written with older versions of the IOjson than the current Sverchok's version.

**Comment by ly29** [comment]
@zeffii 
That topic is for #818

**Comment by zeffii** [comment]
and the least fun of all tasks... is making the exporter .json write out lists on one line rather than drop a new line for each value.

**Comment by ly29** [comment]
Some interface like this for the nodes.
```python
def get_json_dict(self, external=False):
     return dict(self.items()) # + some default things

def set_json(self, items):
     for key, value in items.items():
         setattr(self, key, value)
```

Then nodes with special requirements could simply give a dict that they get back set themselves up with.

**Comment by ly29** [comment]
Some nodes could even share the code for example text resources etc...

**Comment by ly29** [comment]
Well, we (but mostly you) got a change to test the templates today. It is a good way to get to know the problem domain a bit better. :)

**Comment by zeffii** [comment]
well, the importer could have done it in an automated way, there was only a few things
{ 
  'CentersPolsNode': {'replace': 'CentersPolsNodeMK2'},
  'SvTextInNode': {'text_lines': ["add 'stored_as_json' with content of text_lines" ]},
  'LineConnectNode': {'replace': 'LineConnectNodeMK2', 'polygons': {0: "Edges", 1: "Polys"}},
  BMeshViewer': {'replace': 'SvBMeshViewerMK2'}
}

**Comment by ly29** [comment]
Such logic would be sane to have, especially if could apply the same filters to opened files...

**Comment by zeffii** [comment]
i missed one in 5.Sverchok_Spread.json

**Comment by zeffii** [comment]
as a first step i'm contemplating turning all the bodies of the if statements to function calls within the export / import code, then working these functions into the nodes..
```python
                elif node.bl_idname == 'SvTextInNode':
                    params = node_ref.get('params')
                    current_text = params['current_text']
                    node.textmode = params['textmode']

                    if not current_text:
                        print(node.name, "doesn't store a current_text in params")

                    elif not (current_text in texts):
                        new_text = texts.new(current_text)
                        if node.textmode == 'JSON':
                            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
                            new_text.from_string(json_str)
                        else:
                            new_text.from_string(node_ref['text_lines'])

                    else:
                        texts[current_text].from_string(node_ref['text_lines'])
```
would become

```python
def import_text_from_IO(node_ref):
    params = node_ref.get('params')
    current_text = params['current_text']
    node.textmode = params['textmode']

    if not current_text:
        print(node.name, "doesn't store a current_text in params")

    elif not (current_text in texts):
        new_text = texts.new(current_text)
        if node.textmode == 'JSON':
            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
            new_text.from_string(json_str)
        else:
            new_text.from_string(node_ref['text_lines'])
     else:
        bpy.data.texts[current_text].from_string(node_ref['text_lines'])

```
and later called by

```python
              elif node.bl_idname == 'SvTextInNode':
                       import_text_from_IO(node_ref)
```
As an interim step, then  in a next phase add the functions to the nodes, and replace  `node.` with `self.`

**Comment by ly29** [comment]
Sounds like a very sane approach, did something similar with monad class creation.

**Comment by ly29** [comment]
Just for reference: how I did it in redux

https://github.com/Sverchok/SverchokRedux/blob/master/ui/node.py

**Comment by zeffii** [comment]
```
        for n in sorted(nodes_to_import):
            node_ref = nodes_to_import[n]
            bl_idname = node_ref['bl_idname']

            try:
                if old_nodes.is_old(bl_idname):
                    old_nodes.register_old(bl_idname)
                node = nodes.new(bl_idname)
            except Exception as err:
                print(traceback.format_exc())
                print(bl_idname, 'not currently registered, skipping')
                continue

            if create_texts:
                add_texts(node, node_ref)

            gather_remapped_names(node, n, name_remap)
            apply_core_props(node, node_ref)
            apply_superficial_props(node, node_ref)
            apply_post_processing(node, node_ref)
```

**Comment by zeffii** [comment]
The Redux implementation seems neat, but I think that has more to do with it being devoid of nodes that do complicated things. It's definitely something we can hope to achieve (iosjon was big learning experience wrespect to pynodes, for me anyway.)

https://github.com/nortikin/sverchok/blob/iojson_codeshuffle/utils/sv_IO_panel_tools.py#L426-L459

**Comment by ly29** [comment]
It is mostly useful as reference for a default implementation of nodes. the 80-90%. The rest is a lot of work getting right of course...

**Comment by zeffii** [comment]
> 10% of nodes give 90% of the work.

so true.

**Comment by zeffii** [comment]
now.. the first part is what it should have looked like from the beginning..
```
    def generate_layout(fullpath, nodes_json):
        '''
        first create all nodes.
        '''

        print('#' * 12, nodes_json['export_version'])

        update_lists = nodes_json['update_lists']
        nodes_to_import = nodes_json['nodes']
        groups_to_import = nodes_json.get('groups', {})
        
        group_name_remap = add_groups(groups_to_import)  # this return is not used yet
        name_remap = add_nodes(nodes_to_import, nodes)

        print_update_lists(update_lists)

        '''
        now connect them
        '''
        ...
        ...
```

**Comment by zeffii** [comment]
lots of deferment.. possibly easier to edit without feeling like your going to break something accidentally.. i don't know.

**Comment by ly29** [comment]
group name remap isn't actually needed, a ```monad instance``` can find it's monad

**Comment by zeffii** [comment]
## part deux

adding support for monads. first make it work, then probably drop references to `IsGroupNode`

**Comment by zeffii** [comment]
it imports monads now, but I didn't have time to switch the dummynode with a monad_instance_node. There's a bunch of things still to do,

**Comment by zeffii** [comment]
maybe i'm over-complicating this, but am I crazy for thinking the SvMonadGenericNode needs some kind of class function to convert itself to a monad_instance_node -- when passed the imput templates / cls_dict?

**Comment by ly29** [comment]
Actually if you set the ```.cls_bl_idname``` it should just work, without any properties but work.
But such replace function would be sane. The node expand operator is the method I would use as a template.

**Comment by zeffii** [comment]
i thought also the dynamically generate MonadNode instance should have some kind of cls_dict generator function?

**Comment by ly29** [comment]
The monad generates the instance class. The instance is dumb in the regard.
https://github.com/nortikin/sverchok/blob/master/core/monad.py#L108-L150

**Comment by zeffii** [comment]
some progress... and showing signs of what needs to be offloaded to the node i think.
![image](https://cloud.githubusercontent.com/assets/619340/18086555/d38c0732-6eb0-11e6-9a07-01fd4e91c622.png)

**Comment by ly29** [comment]
Yeah, you know that the best after laboring with the I/O code.

**Comment by zeffii** [comment]
For the most part it seems to be working, except the minor (lol) issue of the inner sockets not connecting to the group_input / out_put. This feels brittle..

![image](https://cloud.githubusercontent.com/assets/619340/18100165/1116fae2-6eea-11e6-9c75-97cdeb26a938.png)

**Comment by zeffii** [comment]
seems I need to repopulate the IO nodes in the add group part, prior to setting the links.

**Comment by zeffii** [comment]
the update_list has one weakness, it doen't distinquish between multiple same-named sockets on an monad's IO nodes - I think we'll need to force the socket names on those two SvGroup*putNode to be unique.

**Comment by zeffii** [comment]
or include the index in the update_list..

**Comment by ly29** [comment]
The simple solution is to sort the links based on update list and socket index. But I feel a cleaner solution should be avilable...
The update system could also benefit from a review but that is code I would prefer not to mess with right now.

**Comment by zeffii** [comment]
I motion to force name _uniqueness_ in the SocketAcquisition class, a sane approach that has no real impact on the user.

**Comment by ly29** [comment]
I am not certain I agree, not that name uniqueness wouldn't be sane (*), but I think that using the index when saving sockets is the right way.

I think the right way is create a a way to lock the node ```update``` function so that is doesn't create sockets but can take a fixed set and create them, avoiding the issue right instead.

(*) Having dictionaries without ensuring uniqueness of keys is not sane at all, but it is as it is in blender.

**Comment by zeffii** [comment]
so update_list ideally would be something like [(from_node=from_node.name, from_socket=(socket.name, socket.index), to_node=to_node.name, to_socket=(socket.name, socket.index)]

I suggest the _name uniqueness_ then merely as an interim solution, which will be insignificant to remove at a later stage when update_lists include indices.

I don't see the reasoning behind: 
> I think the right way is create a a way to lock the node update function so that is doesn't create sockets but can take a fixed set and create them, avoiding the issue right instead.

but it is  early and i've only had half a cup of coffee :)

**Comment by zeffii** [comment]
edited answer.

**Comment by ly29** [comment]
```python
name_to_idx = {name: idx for idx, name in enumerate(chain(update_lists))}
links = links =[(l.from_node.name, l.from_socket.index, l.to_node.name, l.to_socket.index) for l in ng.links]
def get_key(l)
    name, _, _, socket_idx = l
    return name_to_idx[name], socket_idx
links.sort(key=get_key)
```
Something like this above.

Having them fixed, especially for the ```GroupInputs```, removes the constraint to connect them in order of sockets. I thinks this is the only node that has dynamic count of outputs, which isn't controlled by number or inputs or a setting.

**Comment by zeffii** [comment]
i'll make an `auto_generate_sockets(templates)` for the GroupInputs, and start offloading other work to nodes..

**Comment by ly29** [comment]
![skarmavbild 2016-08-31 kl 09 56 55](https://cloud.githubusercontent.com/assets/6241382/18120736/4f0316a2-6f61-11e6-88a8-8f822ff5e00d.png)
Just to be clear about what kind of situations might cause problems.

**Comment by zeffii** [comment]
stashing:
```python
        if node.bl_idname in {'SvGroupInputsNodeExp', 'SvGroupOutputsNodeExp'}:
            puts = node.node_kind
            node_dict[puts] = []
            for s in getattr(node, puts):
                if not s.bl_idname == 'SvDummySocket':
                    node_dict[puts].append([s.name, s.bl_idname])
```
repopulate
```python
    elif node.bl_idname in {'SvGroupInputsNodeExp', 'SvGroupOutputsNodeExp'}:
        kind = node.node_kind
        socket_kinds = node_ref.get(kind)
        sockets = getattr(node, kind)
        sockets.remove(sockets[0]) # remove dummy, it will be added anyway. during the final update
        for idx, (s, stype) in enumerate(socket_kinds):
            print('add', s, stype, 'to', node.name)
            sockets.new(stype, s)
            sockets.move(-1, idx)
```
i'm doing some extra work, but it's just a loop over the inputs/outputs

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/18121209/c24aef8e-6f63-11e6-96c8-d8bbd888aec0.png)

**Comment by zeffii** [comment]
SocketAcquisition should take a further two functions then..

```python
def stashing(self):
    socket_kinds = []
    for s in getattr(self, self.node_kind):
        if not s.bl_idname == 'SvDummySocket':
            socket_kinds.append([s.name, s.bl_idname])
    return socket_kinds

def repopulate(self, socket_kinds)
    sockets = getattr(self, self.node_kind)
    sockets.remove(sockets[0]) # remove dummy, it will be added anyway. during the final update
    for idx, (s, stype) in enumerate(socket_kinds):
        # print('add', s, stype, 'to', self.name)
        sockets.new(stype, s)

```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/b493bdfbf309886980d5e78ffcbd1e1fd4e35911

This phase is complete, unless bugs show up. Though ofcourse the issue of socket name dupes remains untouched.

**Comment by zeffii** [comment]
regarding this: https://github.com/nortikin/sverchok/issues/810#issuecomment-243684540

does this effect only the reroute node? There's a couple of important minutiae that i'm glossing over, maybe best if you deal with those since you seem to have a better grasp of them. Else I will eventually get around to it, if they bug me enough.

**Comment by zeffii** [comment]
btw :)

![keyboard](https://cloud.githubusercontent.com/assets/619340/18125691/dfd73328-6f77-11e6-96eb-b7d918623cf9.gif)

i refuse to type that one more time.

**Comment by ly29** [comment]
A million times yes!

Regarding those tiny annoying details I will try to find corner cases and deal with them. As far as I know reroute is the only node in sverchok node trees that doesn't use sverchok sockets.

**Comment by zeffii** [comment]
The rewriting function is in [this addon..](https://github.com/zeffii/BlenderConsolePrompt) but am considering make a far lighter version of it..

can we subclass the reroute node?

**Comment by ly29** [comment]
I don't think it is possible to subclass it. We do have some code capable of replacing the sockets though.

**Comment by zeffii** [comment]
as per : 
https://github.com/nortikin/sverchok/commit/84db7392d70c885f8be48fb482b0380bec774be5

The scenario where the monad already exists in the current layout is not handled correctly.

**Comment by zeffii** [comment]
should be as simple as the suggested fix.

**Comment by zeffii** [comment]
but possibly it isn't..  but can't investigate now
```python
def add_groups(groups_to_import):
    '''
    return the dictionary that tracks which groups got renamed due to conflicts
    '''
    group_name_remap = {}
    for name in groups_to_import:
        group_ng = bpy.data.node_groups.new(name, 'SverchGroupTreeType')
        if group_ng.name != name:
            group_name_remap[name] = group_ng.name
        import_tree(group_ng, '', groups_to_import[name])
    return group_name_remap
```
