### ISSUE TITLE
UDP Help

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#814]
I am looking at this and manage to make Touch OSC >> Scratch OSC Bridge >> to talk to Scratch program.
http://www.kasperkamperman.com/blog/scratch-osc-bridge/

UDP, OSC stuff. Seems a bit confusing " server and client ". Sverchok has the UDP Client, its documentation is technical. http://takuro.ws/2015/09/sverchok-udpclientnode/. I am not sure how to contact Takuro. I wish that the UDP client is more like the Scratch OSC Bridge.

I want to drive animation using realtime audio / microphone. Maybe Lipsync. ... It might be more like Animation Nodes task, but then Sverchok has the UDP client and GET and SET node in Sverchok.

UDP could be useful to me but I don't know how to generate UDP data.

**Comment by enzyme69** [comment]
Currently reading this, while pulling hair...
https://trac.v2.nl/wiki/pyOSC

**Comment by enzyme69** [comment]
Hoping to do something like this:
https://www.youtube.com/watch?v=0a_M9VsZ6Lk

**Comment by enzyme69** [comment]
![prtscr capture_10](https://cloud.githubusercontent.com/assets/3952687/17772364/a9987d9e-658b-11e6-8ce7-04d55cae1b24.png)

Either getting above or just TimeOut. Can't tell if message get sent or received.

UDP Client is not Server, wondering if we need Bridge....

**Comment by enzyme69** [comment]
And this PDF also somewhat useful, but it is going to BGE...
https://virtualacoustics.files.wordpress.com/2012/01/osc_report.pdf

**Comment by enzyme69** [comment]
This is also useful:
http://blender.stackexchange.com/questions/27959/controlling-drivers-with-data-received-via-tcp-udp

But it hangs when applied as Script node.

**Comment by enzyme69** [comment]
Barely related, but all kind of realtime data and PyNode and not BGE, will be useful. One day.

**Comment by enzyme69** [comment]
And this:
https://blenderscripting.blogspot.com.au/2014/11/blender-pynodes-and-supercollider-and.html#comment-form

**Comment by enzyme69** [comment]
Also somewhat related:
https://trac.v2.nl/wiki/pyOSC

BGE and speech:
https://blenderartists.org/forum/showthread.php?360096-Speech-recognition-in-BGE

One of this must be useful:
http://blenderartists.org/forum/showthread.php?359877-Real-Time-Lip-Sync-in-BGE

**Comment by ly29** [comment]
https://github.com/nortikin/sverchok/pull/718
Look here also

**Comment by zeffii** [comment]
I also mad something today.. it works with microphone in..  it's very rough:

https://github.com/nortikin/sverchok/pull/815

https://cloud.githubusercontent.com/assets/619340/17786825/e52d882c-6586-11e6-9c8a-49d4661a47c4.gif

**Comment by enzyme69** [comment]
​That's pretty mad, Dealga! :D

I have some bunch of crazy creative ideas if only then:
- Blender can take realtime inputs (audio, etc) without too much latency.
- Blender can generate audio frequency in realtime.

Everything can become more like IFTTT. IF THIS THEN THAT...

Even though trivials, it is not really trivial.

**Comment by zeffii** [comment]
@enzyme69 I suggest that you lobby Ton / blender core devs to include built in support for OSC. It's a well established protocol now. Anyone interested in including OSC in their scripts/addons either has to import something like pyOSC (and therefore a dependency that not all users may be able to install) or code their own OSC send/receive from scratch (which is BLEHHH unless you like that kind of programming).

### Fine

OSC is fine for sending control messages which are not impacted by network latency for instance: 
>  message: when the clock hits 11:00:00 then start rotating a matrix by 180 degrees in 20 seconds

when that message is received by the client at some time prior to 11:00:00 then it would wait until that time to perform the operation.

#### Also fine

If you are OK with about 20 ms latency between doing your OSC action (slider/knob/button) and getting the OSC client to read that message. If that kind of latency is fine then you'll be OK.

-------

I say 20 ms but it's going to be less or more... may even be close to 0.02ms a lot of the time, but the more processing your computer is doing and _random network_ activity will increase the probability that the latency will be noticeable on occasion

**Comment by enzyme69** [comment]
​Ok that sounds like the right answer for now. I will message Ton maybe not
via Twitter.... Will check.

**Comment by zeffii** [comment]
The OSC route is very different to near-realtime LipSync. I am convinved OSC should be done using a panel that lets you modify the rate at which it's listening for OSC events.

I can relatively easily make an OSC panel with a rudimentary and preliminary (working) implementation of an OSC receiver, which would let us define which `/paths/` to listen to and what to do with the values associated with them, but i'll do this [in a new repository](https://github.com/zeffii/b3d_osc_panel). (it's something i've implemented already a few times, but in none of those cases as a generic tool)

**Comment by zeffii** [comment]
please continue the discussion about OSC in that repository.

**Comment by ly29** [comment]
The current Sverchok update model isn't suited to such an update system but could be modified to do that easily. 
However with all the overheads we have currently I do think a new system would be a better idea.

**Comment by enzyme69** [comment]
I still feel that the UDP node in Sverchok is a waste, sadly not documented and the blog post by the dev has issue with the Sverchok script. I tried to change the script slightly, but....

def sv_main(in_value=[[]]):
   
    in_sockets = [['s', 'in', in_value]]
    
    out_value = str(in_value[0][0])
    
    out_sockets = [['s', 'out', out_value]]
    
    return in_sockets, out_sockets

I have no familiarity with node.js. May need to research on that.

@zeffii your implementation of OSC so far is my favourite. It works perfectly. 

I am making a new video to show my experiment so far. I will search for good head with shapekeys.

**Comment by zeffii** [comment]
> I still feel that the UDP node in Sverchok is a waste

The UDP node assumes you know how to send data to the UDP port using an external program. For instance Takuro Wada uses a locally running _node.js_ server in this demos of the node. His setup was 

     AudioSource > MAX msp -> NodeJS -> UDP -> UDPNode

it should be fine if you know how to use it, It's beyond the scope of the node's documentation to guide the user in gaining expertise in the external elements of that chain of software.

The UDPNode in conjunction with a script node to decompose the messages received, is much like opening a letter. If the letter has content you can do something, if the letter has scrambled content, you need to know how to unscramble it.

It's not a node I have any immediate use for, but we felt it was OK to include because it does have a use-case and the code was interesting :)

**Comment by zeffii** [comment]
this is probably the more robust implementation of that script.

```python
def sv_main(in_value=[[]]):
    out_value = []

    in_sockets = [['s', 'in', in_value]]

    if in_value and in_value[0]:
        out_value = str(in_value[0][0])

    out_sockets = [['s', 'out', out_value]]

    return in_sockets, out_sockets
```

**Comment by nortikin** [comment]
![изображение](https://user-images.githubusercontent.com/5783432/54879853-1f898580-4e4f-11e9-8724-ea3349730be4.png)
UDP client node mk2 is on board with documentation.

**Comment by nortikin** [comment]
send on nodetree change, receive permanently with run
