### ISSUE TITLE
experiments with auto layout

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#817]
First out, a total ordering of nodes, which ain't that clever. Based on topological max distance and in x direction and slots in y direction. 

The code is contained in `ui.autolayout`

![skarmavbild 2016-08-22 kl 09 43 18](https://cloud.githubusercontent.com/assets/6241382/17847226/2d953e48-684d-11e6-8e0a-7c981df57420.png)

As mentioned in #803 there is some need for some auto layout tools, to help move nodes out the way when expanding monads.

**Comment by ly29** [comment]
As plus the first one does account for multiple output nodes.
![skarmavbild 2016-08-22 kl 09 50 48](https://cloud.githubusercontent.com/assets/6241382/17847378/f630598c-684d-11e6-97c0-986ade37e773.png)

**Comment by ly29** [comment]
Due to preferences and different situations it is clear that there isn't one answer to this...

**Comment by zeffii** [comment]
My interest with ArrangeNodes was that it allowed us to script a fairly simple Cycles nodetree without giving each node a location. It would be just as useful for Sverchok node trees that someone generates by script.  For this reason alone it would be good to have.

not too keen on running such operators on complex node trees, I doubt any of us are..

**Comment by ly29** [comment]
No, I agree, this was more of some experiments to gather some experience about layouts. But I thought the results was fun enough to share. Should have made it more clear.

**Comment by zeffii** [comment]
i'm glad you are doing this,

**Comment by ly29** [comment]
Next to create a version based on the inputs. Also averaging them, awareness of frames and respecting such groups. 

( and of course a simpler version for just moving the node tree to sides when expanding a node. )

**Comment by zeffii** [comment]
i'm a little suprised that the built in 'move to the side' code isn't kicking in

**Comment by ly29** [comment]
Yeah that is a good point

**Comment by zeffii** [comment]
slightly tangential, maybe if we can cause a nudge in the nodeview it would solve the auto-display and auto-frame-snap in one go..

**Comment by zeffii** [comment]
auto-displace

**Comment by ly29** [comment]
Well since it doesn't do when you expand built in node group I guess it too much to ask for...

**Comment by zeffii** [comment]
worth a bug report to the tracker imo :) Julian I think is the kind of guy who would prefer to have his features working in all aspects :)

**Comment by ly29** [comment]
Yeah, playing a bit more with it today, but no real progress, have to build some interfaces and abstractions into it.

**Comment by ly29** [comment]
![skarmavbild 2016-08-23 kl 09 29 14](https://cloud.githubusercontent.com/assets/6241382/17883659/226f2ea8-6914-11e6-8872-95478800cb50.png)
Topo logical starting with inputs and with outputs.

**Comment by zeffii** [comment]
do you calculate the final positions before moving them?

**Comment by zeffii** [comment]
if so.. the easing functions: https://gist.github.com/zeffii/c1e14dd6620ad855d81ec2e89a859719

**Comment by ly29** [comment]
Re tween,
I guess one could make it a modal operator gradually update it. I could easily change the code that does that...

**Comment by ly29** [comment]
![topotween](https://cloud.githubusercontent.com/assets/6241382/17887144/61bb2bc8-6925-11e6-976d-d30ed8a89e72.gif)
Smooth.
Took me longer than I expected.

**Comment by zeffii** [comment]
: )))

**Comment by ly29** [comment]
![toposort2](https://cloud.githubusercontent.com/assets/6241382/17887778/470ca7ae-6928-11e6-9cc3-8df892ca898f.gif)
Lots of bad code but anyway a lot of fun

**Comment by ly29** [comment]
![topoavg](https://cloud.githubusercontent.com/assets/6241382/17926395/2a600776-69f1-11e6-8cea-a063ca6bcc8a.gif)
Averages topo sort that respects initial y order within given slots.

**Comment by zeffii** [comment]
and force directed graph? where more connections between individual nodes denote intended closeness..
https://bl.ocks.org/mbostock/4062045

**Comment by ly29** [comment]
That is also a good idea, next on my table is to use the actual distance between the nodes instead of the topological distance.

**Comment by zeffii** [comment]
how do framed nodes behave currently? nodes internal to a frame could stay in their relative positions or would that look wacky?

**Comment by ly29** [comment]
Currently it does know about frames at all. I think a frame should be treated as one node.

**Comment by zeffii** [comment]
yep, could encourage people who use the auto-layout to make use of the frames to indicate node cohesiveness

**Comment by zeffii** [comment]
some wonderful examples of full-on-node-gasm on the google+ group, wonder how those larger trees behave with autolayout :)

**Comment by enzyme69** [comment]
With this autolayout stuff, is there algorithm that simple push, wiggle and
nudge bunch of objects, so they are not intersecting? Is that what
happening here?

**Comment by ly29** [comment]
Right now it sorts the object using the topological information on the x axis, on the y axis it sorts based on previous location. Right now it just an experiment.
It only deals with the layout of nodes right now.

**Comment by zeffii** [comment]
@enzyme69 
complex node trees often intersect so that's a bit harder, even if the algorithm was going out of its way to inject node-reroutes 
![image](https://cloud.githubusercontent.com/assets/619340/18042213/d6ae1d2a-6dbf-11e6-9586-3da0e38d0711.png)

**Comment by zeffii** [comment]
the particular scenario that spawned this conversation ha still to be addressed,

>  moving nodes out of the way when _ungrouping_ 

So what should we do? The least node-relocations would be to 
- take the locations of all nodes
- all nodes to the left (or equal) of the monad_instance node are popped from the list
- after injecting the ungrouped nodes, relocate the left most ungrouped to be equal to the X position of the monad_instance
- the X location of the most _right places_ of the ungrouped node will be used to push the nodes that where to the right of the initial monad_instance.

**Comment by ly29** [comment]
A good first step would be to center the monad on the location of the expanded monad instance.

**Comment by zeffii** [comment]
perhaps: _moving nodes after expand_ should be its own issue?

![image](https://cloud.githubusercontent.com/assets/619340/18044013/beee1a08-6dcb-11e6-92fc-0fc9a3489750.png)

**Comment by ly29** [comment]
I think so, right now my priorities regarding sverchok are something like:
- Script MK3
- Image Sampling Node
- Editing properties
- ...
- Auto layout

**Comment by zeffii** [comment]
parking this here
```python
def average_of_selected2(nodes):
    Vector2 = Vector((0,0))
    if len(nodes):
        return ((1.0 / len(nodes)) * sum([n.location for n in nodes], Vector2))[:]
```

**Comment by ly29** [comment]
Nice, even prettier, or at least shorter, but untested.
```python
def average_of_selected2(nodes):
    if nodes:
         scale = 1/len(nodes)
        return sum(scale * n.location for n in nodes)[:]
```

**Comment by zeffii** [comment]
the second parameter to the `sum` is an accumulator/start value
```python
>>> help(sum)
Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.
``` 
I'm sure I knew this at one point.. but never used it.

**Comment by ly29** [comment]
Yeah, but you check that there are nodes first and set it to zero.

**Comment by ly29** [comment]
Was fun but won't do more here for the forseeable future
