### ISSUE TITLE
Templates failing to import

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#818]
The templates should give useful examples, the following **15** out of 33 templates fail in different ways currently.

- [x] '1.Basics_Sverchok.json',
- [x]  '2.Lists_playing.json',
- [x]  '4leveldataexample.json',
- [x]  '5.Sverchok_Spread.json',
- [x]  'Transformations.json',   -- may need cyclic V and Vdir set 
- [x]  'dancing_nodes.json',         ---  :) 
- [x]  'extruded_edges.json',    (exported with deprication warnings?)
- [x]  'join_meshes.json',
- [x]  'petal_egg.json',
- [x]  'petri_circle.json',   (intentionally placed at X=22 ?)
- [x]  'petri_spiral.json',
- [x]  'petri_spiral_scale.json',
- [x]  'profile_reconnect.json',
- [x]  'wall_from_profile_node.json',   (@nikitron may want to look at it)
- [x]  'wingflap4.json'

**Comment by ly29** [comment]
As failures counts:

-  old nodes
- exception during import
- failed connection between nodes

**Comment by zeffii** [comment]
moved comment:

maybe the template menu should parse the descriptor of each template first, cache them, and grey out those templates that were written with older versions of the IOjson than the current Sverchok's version.

**Comment by zeffii** [comment]
OK, @ly29   I will start at the bottom of that list

**Comment by ly29** [comment]
I won't have time to do anything about it today.

The debug info I collected. A ```bl_idname: True``` is an old node. Failed connections is kind of clear.
 
```python
'1.Basics_Sverchok.json'
'failed total 2'
'2.Lists_playing.json'
{'ListSortNode': True, 'ListSumNode': True, 'ShiftNode': True}
'4leveldataexample.json'
{'BmeshViewerNode': True, 'LineConnectNode': True}
'5.Sverchok_Spread.json'
'failed total 2'
'Transformations.json'
{'LineConnectNode': True}
'dancing_nodes.json'
{'BmeshViewerNode': True}
'extruded_edges.json'
{'BmeshViewerNode': True, 'LineConnectNode': True}
'join_meshes.json'
{'LineConnectNode': True}
'petal_egg.json'
{'BmeshViewerNode': True,
 'LineConnectNode': True,
 'setattr': "<class 'Exception'>"}
'petri_circle.json'
{'LineConnectNode': True}
'petri_spiral.json'
{'LineConnectNode': True}
'petri_spiral_scale.json'
{'BmeshViewerNode': True,
 'CentersPolsNode': True,
 'LineConnectNode': True,
 'setattr': "<class 'Exception'>"}
'profile_reconnect.json'
{'LineConnectNode': True}
'wall_from_profile_node.json'
{'LineConnectNode': True}
'wingflap4.json'
{'LineConnectNode': True}
```

**Comment by ly29** [comment]
Most are due to ```LineConnectNode``` being renamed.

**Comment by zeffii** [comment]
yeah and 
```python
 File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\nodes\generator\circle.py", line 115, in process
    parameters = match_long_repeat([Angle, Vertices, Radius])
Node Circle.002 had exception local variable 'Angle' referenced before assignment
```

**Comment by zeffii** [comment]
actually, i haven't updated sverchok for a day and think I missed a few Circle node mods

**Comment by zeffii** [comment]
editing the bl_idname of a `LineConnect` node to `LineConnectMK2` .. but then
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 550, in execute
    import_tree(ng, self.filepath)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 463, in import_tree
    generate_layout(fullpath, nodes_json)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\sv_IO_panel_tools.py", line 387, in generate_layout
    setattr(node, p, val)
TypeError: bpy_struct: item.attr = val: expected a string enum, not int
```

It may be less work just to ditch these templates and make new ones.

**Comment by zeffii** [comment]
( that's zeffii speak for : I can't be bothered doing it )

**Comment by ly29** [comment]
I think just removing them for now and letting @nortikin add them back when fixed is the best solution

**Comment by zeffii** [comment]
yes, a true diplomat :)

**Comment by ly29** [comment]
I think we can all agree that templates should't fail. Especially ```1. Basics Sverchok```...

**Comment by zeffii** [comment]
yes, poor form .. also perhaps an indicator that these features are under-used.

**Comment by ly29** [comment]
It is also is easy to verify the template imports...

**Comment by zeffii** [comment]
```python
Traceback (most recent call last):
  File "sverchok\utils\sv_IO_panel_tools.py", line 550, in execute
    import_tree(ng, self.filepath)
  File "sverchok\utils\sv_IO_panel_tools.py", line 463, in import_tree
    generate_layout(fullpath, nodes_json)
  File "sverchok\utils\sv_IO_panel_tools.py", line 364, in generate_layout
    json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
TypeError: string indices must be integers

```

**Comment by zeffii** [comment]
above comes from ` "bl_idname": "SvTextInNode",  `  trying to store the json internally..

**Comment by zeffii** [comment]
i don't know (or can't recall) the rational for this but perhaps it should store it as a sub_dict?

**Comment by zeffii** [comment]
or maybe deal with that node specifically ..
*runs away, dodging bullets*

**Comment by ly29** [comment]
I think won't fix for that particular scenario in the old code is the best idea.

**Comment by zeffii** [comment]
oh right, i say in the comments that I fixed the json stuff for TextInput for 0.06 , but the template was exported with 0.055

**Comment by ly29** [comment]
Template import is actually a test that is somewhat easy to automate, we just have to collect errors. For the ones that don't fail we could import/export to update them regularly...

**Comment by ly29** [comment]
How about we put the bad ones in zip file and remove them for now?

[bad_templates.zip](https://github.com/nortikin/sverchok/files/429814/bad_templates.zip)

**Comment by ly29** [comment]
did it now.

**Comment by zeffii** [comment]
technically,  it should be simple enough to load them via an older importer / save the blend / and export with later exporer

**Comment by zeffii** [comment]
text_lines should look like this:
```json
      "text_lines": {
        "stored_as_json": {
          "Objects input.004:Vertices": {
            "v": [[
              [-0.5209044814109802,-0.5209044814109802,0.0],
              [-0.5209044814109802,0.5209044814109802,0.0],
              [0.5209044814109802,0.5209044814109802,0.0],
              [0.5209044814109802,-0.5209044814109802,0.0],
              [-0.21004392206668854,-0.21004392206668854,1.0418089628219604],
              [-0.21004392206668854,0.21004392206668854,1.0418089628219604],
              [0.21004392206668854,0.21004392206668854,1.0418089628219604],
              [0.21004392206668854,-0.21004392206668854,1.0418089628219604]
            ]]
          },
          "Objects input.004:Polygons": {
            "s": [[[4,5,1,0],[5,6,2,1],[6,7,3,2],[7,4,0,3],[0,1,2,3],[7,6,5,4]]]
          }
        }
      },
      "textmode": "JSON",
      "width": 140.0
    },
```

**Comment by zeffii** [comment]
uch...
```python
failed total 2
[['Text Input', 'Objects input:Vertices', 'Centers polygons', 'Vertices'], ['Text Input', 'Objects input:Polygons', 'Centers polygons', 'Polygons']]
```

**Comment by ly29** [comment]
I think templates are a good feature but badly in need of a review.

**Comment by zeffii** [comment]
yep. agreed.

note to self, 0,60 would export that json as 
```json
..
..
      "text_lines": {
        "stored_as_json": {
          "Objects input.004:Polygons": [
            "s",
            [
              [
                [
                  4,
                  5,
                  1,
                  0
                ],
                [
                  5,
                  6,
                  2,
                  1
                ],
                [
                  6,
                  7,
                  3,
                  2
                ],
                [
                  7,
                  4,
                  0,
                  3
                ],
                [
                  0,
                  1,
                  2,
                  3
                ],
                [
                  7,
                  6,
                  5,
                  4
                ]
              ]
            ]
          ],
          "Objects input.004:Vertices": [
            "v",
            [
              [
                [
                  -0.5209044814109802,
                  -0.5209044814109802,
                  0.0
                ],
                [
                  -0.5209044814109802,
                  0.5209044814109802,
                  0.0
                ],
                [
                  0.5209044814109802,
                  0.5209044814109802,
                  0.0
                ],
                [
                  0.5209044814109802,
                  -0.5209044814109802,
                  0.0
                ],
                [
                  -0.21004392206668854,
                  -0.21004392206668854,
                  1.0418089628219604
                ],
                [
                  -0.21004392206668854,
                  0.21004392206668854,
                  1.0418089628219604
                ],
                [
                  0.21004392206668854,
                  0.21004392206668854,
                  1.0418089628219604
                ],
                [
                  0.21004392206668854,
                  -0.21004392206668854,
                  1.0418089628219604
                ]
              ]
            ]
          ]
        }
      },
      "textmode": "JSON",
      "width": 140.0
    },
```

**Comment by zeffii** [comment]
even in sort_mk2.py there's this
```
    def update(self):
        if 'data' in self.inputs and self.inputs['data'].links > 0:
            # адаптивный сокет
            inputsocketname = 'data'
            outputsocketname = ['data']
            changable_sockets(self, inputsocketname, outputsocketname)
```
but `self.inputs['data'].links > 0` causes an error  (`comparing tuple() > int()`)

**Comment by zeffii** [comment]
(which I think was allowed in earlier version of python 3.1 but has been disallowed for a while now)

**Comment by zeffii** [comment]
or maybe the pyNode api changed a little..

**Comment by ly29** [comment]
No I think it always have been broken, pushed a fix into master of that. Without the comparison it would work fine, with also.

But since it is the update function and basically only changes color/type of the socket nothing actually brakes.

**Comment by ly29** [comment]
Removing them wasn't the best option I realize now, we could simply have filtered them out temporarily. Best option is probably add them one by one to master...

**Comment by zeffii** [comment]
I see, must have branched before you edited `sort_mk2`.

The same was true for ImageNode a while back https://github.com/nortikin/sverchok/commit/9d46c7c114417c6bd5c982efd5f34e5f9457ccfa#diff-65cd86979326f1ef116969e4626ed747

**Comment by ly29** [comment]
Yeah, to be fair that one I probably caused...

**Comment by zeffii** [comment]
heh :)  I just realized that I started at the top of that list.. not the bottom.  but working through it gradually, `"0.054"` exporter stored enums differently..

**Comment by zeffii** [comment]
UVconnect

MK2
```
    polsORedges = [('Pols', 'Pols', 'Pols'), ('Edges', 'Edges', 'Edges')]
    polygons = EnumProperty(name='polsORedges',
                             items=polsORedges,
                             options={'ANIMATABLE'}, update=updateNode)
```
vs
MK1
```
    polygons = BoolProperty(name='polygons', description='Do polygons or not?',
                            default=True,
                            update=updateNode)
```

**Comment by zeffii** [comment]
so if the json says: polygons = 0
it will need to be 'Pols'

**Comment by zeffii** [comment]
am noticing with a lot of these that the nodeview needs to be updated / jigged around for the Frames to snap into place. Remember this was an early issue..never resolved..

**Comment by ly29** [comment]
Maybe tag redraw or something like that?
https://github.com/nortikin/sverchok/blob/master/ui/viewer_draw_mk2.py#L133-L143

**Comment by ly29** [comment]
You are making great progress!

**Comment by zeffii** [comment]
yep, turned off the brain for a bit.

**Comment by zeffii** [comment]
not sure how to go about just merging these..

**Comment by ly29** [comment]
I think manully copying the files into master is the best option and adding them to got. My fault.
 Sadly.

**Comment by ly29** [comment]
Would be nice with comment field that got set on frame or something

**Comment by zeffii** [comment]
ok i'll manually reinject the files..

**Comment by zeffii** [comment]
done. mostly. https://github.com/nortikin/sverchok/commit/9389e275fc7d861e4b707de2d253e7269211f8e4

**Comment by zeffii** [comment]
I thought I did 5Sverchokspread but it seems i missed something , but when I replaced the stored jsonstring as a dict it;s not correct (haven't looked at import code yet)
```json
      "text_lines": {
        "stored_as_json": {
          "Objects input.004:Vertices": [ 
            "v", [[[-0.5209044814109802,-0.5209044814109802,0.0],
              [-0.5209044814109802,0.5209044814109802,0.0],
              [0.5209044814109802,0.5209044814109802,0.0],
              [0.5209044814109802,-0.5209044814109802,0.0],
              [-0.21004392206668854,-0.21004392206668854,1.0418089628219604],
              [-0.21004392206668854,0.21004392206668854,1.0418089628219604],
              [0.21004392206668854,0.21004392206668854,1.0418089628219604],
              [0.21004392206668854,-0.21004392206668854,1.0418089628219604]]]],
          "Objects input.004:Polygons": [
            "s", [[[4,5,1,0],[5,6,2,1],[6,7,3,2],[7,4,0,3],[0,1,2,3],[7,6,5,4]]]]
        }
      },
```

**Comment by zeffii** [comment]
whereas it imports this fine... 
```json
"text_lines": "{\"Objects input.004:Vertices\":[\"v\",[[[-0.5209044814109802,-0.5209044814109802,0.0],[-0.5209044814109802,0.5209044814109802,0.0],[0.5209044814109802,0.5209044814109802,0.0],[0.5209044814109802,-0.5209044814109802,0.0],[-0.21004392206668854,-0.21004392206668854,1.0418089628219604],[-0.21004392206668854,0.21004392206668854,1.0418089628219604],[0.21004392206668854,0.21004392206668854,1.0418089628219604],[0.21004392206668854,-0.21004392206668854,1.0418089628219604]]]],\"Objects input.004:Polygons\":[\"s\",[[[4,5,1,0],[5,6,2,1],[6,7,3,2],[7,4,0,3],[0,1,2,3],[7,6,5,4]]]]}",
```

therefore somewhere one could add 
```python
text_lines = entry
if isinstance(text_lines, str):
    try:
         writing to texts the content of this stringified json
    except:
         pick your nose
elif isinsance(text_lines, dict):
    ...
```

**Comment by zeffii** [comment]
right, the code involved is here, and it must be executing the scenario where the text file is currently loaded into bpy.data.texts, and therefor is not seeking a dict.. but a string of a json. 
I suppose this is intended behaviour.

```python
                    elif not (current_text in texts):
                        new_text = texts.new(current_text)
                        if node.textmode == 'JSON':
                            json_str = json.dumps(node_ref['text_lines']['stored_as_json'])
                            new_text.from_string(json_str)
                        else:
                            new_text.from_string(node_ref['text_lines'])

                    else:
                        texts[current_text].from_string(node_ref['text_lines'])
```
https://github.com/nortikin/sverchok/blob/master/utils/sv_IO_panel_tools.py#L351-L370

**Comment by zeffii** [comment]
but maybe it shouldn't be overwriting `bpy.data.texts[current_text]` as it is probably a redundant step..

**Comment by nortikin** [comment]
as far as i remember, there was conflict when exporting in one order, or another

https://github.com/nortikin/sverchok/blob/master/utils/sv_IO_panel_tools.py#L149
this profile node not handled if handled scale node, that works in petri template (not sure whether scale node)

**Comment by nortikin** [comment]
easier to make new template, but petri wasn't exported corectly that times and i left as it is.

**Comment by zeffii** [comment]
I don't know what you mean @nortikin . but if you want to recreate, perfect :)

**Comment by nortikin** [comment]
weekend i have to spend time on Sverchok much
