### ISSUE TITLE
Proposal : add bl_idname to side panel under NODE_PT_active_node_generic

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#819]
cause it would be convenient.

**Comment by zeffii** [comment]
layout.prop(node, "bl_idname", icon='NODE')

**Comment by ly29** [comment]
I say yes. I think it belongs in, ui.development possibly with a debug mode setting

**Comment by zeffii** [comment]
not sure if it's possible to have a string selectable (to copy) but locked for editing.. 
else a copy operator with the bl_idname as a label

**Comment by ly29** [comment]
Except that it should be label I guess since it ain't a property

**Comment by zeffii** [comment]
ha.. i might just make it so there's a button in there with text=node.bl_idname and the operator copies the bl_idname to clipboard ..convenient.

**Comment by ly29** [comment]
Sounds very good. Make it :)
