### ISSUE TITLE
Cross Section node bug?

### ISSUE THREAD

**Issue by diramazioni** [nortikin/sverchok#823]
I'm trying to use the cross section node but I can't get Polygons maybe I'm doing something wrong or there is a bug indeed for example using blender-sushi example:
![sv_cross](https://cloud.githubusercontent.com/assets/682046/17909115/5bdf6fa8-6983-11e6-8386-0e283a83008b.jpg)
I've added an additional List Split and List Join to get the vertex but I can't get the Polygons

**Comment by ly29** [comment]
Mark the option Fill Section.
