### ISSUE TITLE
SV Image

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#825]
The Image node tends to change its image source into the latest image I selected.

I was doing this artwork for example, and I was picking image one by one. For unknown reason, the image source of SV Image is always switching to the last Image I select as Material or Texture.

It's a tiny bug, but still.....

Image node is quite handy and pretty fast for 100 x 100 vectors, can it also sample and output RGB separately? instead of just the greyscale. I can separate the RGB by outputting the vector into each separate points, but if I were to use 1 node and just wanted to color the vertex, maybe it could be useful to have RGB output.

**Comment by enzyme69** [comment]
![prtscr capture_29](https://cloud.githubusercontent.com/assets/3952687/17930129/013ac082-6a48-11e6-8eeb-8e9efe0109a3.png)

**Comment by zeffii** [comment]
interesting, are you duplicating the svimage node to get the second instance or picking both from the menu separately.

There's an imagine decompose node in Beta, which spits out the separate RGB(A) values. Read the docs carefully, please.

**Comment by zeffii** [comment]
i can't reproduce it , but that's irrelevant. I think more appropriate code for the image_name would be
```image_name = StringProperty()
   ...
   ...
   row.prop_search(self, 'image_name', bpy.data, 'images')
```

**Comment by enzyme69** [comment]
​Thanks for the fix Dealga, yeah, I should have checked the docs, but these
days, it's like: when I try to find documentation, there is None. When
there is documentation, I don't check. Will check documentation next...

**Comment by enzyme69** [comment]
​I duplicate the node, usually that's the fastest.

**Comment by zeffii** [comment]
http://nikitron.cc.ua/sverch/html/nodes/beta/image_decompose.html

**Comment by zeffii** [comment]
> To get output from this node you must connect something to the first 2 output sockets (xya and rgb), polygons is optional and only outputs faces when Filter? is off.

**Comment by zeffii** [comment]
I didn't change the svimage node's code yet. not sure why that should happen.. or how they could the active uv image has anything to do with the image_name used in the svimage node. it's weird.

Duplicating the nodes didn't reproduce that error for me, so.. it's still a puzzle but it did show some code that could be improved slightly.

**Comment by ly29** [comment]
It is node that would be helped with numpy I think. All the list math. But still to big an images would slow down the rest of the pipeline.

**Comment by zeffii** [comment]
yep the obvius solution may be to cache the image in some gobal sverchok.images dict as a flat numpy array and by default only be refreshed if the user tags that image to be re-cached on framechange or something.

**Comment by zeffii** [comment]
that way other nodes that relied on `bpy.data.images` would first see if the image is present in `sverchok.data.images`

**Comment by enzyme69** [comment]
It's very possible that I did something that trigger Sverchok to change the
image Path.... but it happens so many times while I am assigning Materials
and Textures.

Is it possible to have Image node to sample and scatter points based on
other things. Perhaps like scatter more dense points when lots of details.
What is the algorithm for this? I will research...



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by enzyme69** [comment]
​Maybe:
"faces with a larger surface area will get *more points*" but what define a
face area from image... hmm..

Kind of wanting to do this:
http://blender.stackexchange.com/questions/28981/solid-color-for-each-face-in-cycles-when-using-image-textures/28990#28990

But more direct.

**Comment by ly29** [comment]
How about this.
![peng](https://cloud.githubusercontent.com/assets/6241382/17959616/c2898742-6aa1-11e6-8fce-20762bfe9838.png)
100% Sverchok + cycles
Not 100% happy with this method, but as hack it is at least as valid as the one linked above.

[peng.zip](https://github.com/nortikin/sverchok/files/436361/peng.zip)

**Comment by ly29** [comment]
Generating the points could be done with image decompose with some filtering (several methods are possible) that would give a nicer result.

**Comment by zeffii** [comment]
I wrote a script to do something similar http://blenderpython.tumblr.com/post/117154100009

Tho we are going offtopic from the original premise of this issue. Please start a new thread for ideas/enhancements..

**Comment by zeffii** [comment]
what you really want is an algorithm that generates denser clusers of points in those areas where there's a lot of variation in color.

**Comment by zeffii** [comment]
@ly29  changing it to this code shouldn't break anything should it? 

https://github.com/nortikin/sverchok/issues/825#issuecomment-242052438

**Comment by ly29** [comment]
@zeffii 
I am not sure actually

**Comment by zeffii** [comment]
i think the fact that an enum was used may be to blame for the unwanted switching

**Comment by ly29** [comment]
Yeah that makes sense. Also I remember that you a some similar problem with script node a long time ago. 
Just needs to happen with old image nodes when we load such a file.

**Comment by zeffii** [comment]
yep!

**Comment by zeffii** [comment]
I can confirm this bug, it happens when you add new images to the UV editor, and this messes up the location/index of the image picked in the EnumProperty of SV Image. It's a bug you'll only notice if you have more than 1 image.

and unless someone _objects_ I would like to just replace the Enum with a prop_search for the time being, it won't break a node tree, (i  tried, it just unsets the image to '' )

**Comment by ly29** [comment]
Yeah do it.

**Comment by zeffii** [comment]
done #838

**Comment by zeffii** [comment]
now to consider an np implementation :] with caching optional. -- but its very warm so...uchhhh.
