### ISSUE TITLE
Delaunay 2D didn't work with MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#826]
Basically trying to do this kind of effect, in Sverchok, in one go.
http://blender.stackexchange.com/questions/28981/solid-color-for-each-face-in-cycles-when-using-image-textures/28990#28990

Probably cannot be done in one go, because Sverchok does not have Scatter thing.

But anyway, we can do it step by step, with a bit of manual.

The Delaunay2D unfortunately cannot do Live Mesh Baking, using MK2. So I need to bake.

The step by step is broken, I wish Sverchok can just do this in one go.
1) Analyze Image, Scatter Points >> draw points manually anyway
2) Turn points into Delaunay triangular mesh >> bake out
3) From this points, we need to separate each poly face >> I use Animation Nodes, or just manual way
4) With separated poly face, joined back and scale down each poly face to zero
5) Face with zero scaling apparently can still do UV mapping and transfer to original.

STEP 3-4-5 can be in Sverchok as well and I actually manage to get the Color back using my Displace Modifier XYZ RGB trick.

I have a feeling Sverchok should be able to do this in one go. I like the Image node, it has potential, wonder if SV Image can sample image from points scattered?

Thanks!

**Comment by ly29** [comment]
What breaks with Delaunay and the bmesh viewer? For me it seems to work.

A sampling of images points is an interesting possibility for informing the mesh.

**Comment by enzyme69** [comment]
Ok, so it's working again after I updated to latest Sverchok. So weird... I guess I just close this one. And focusing to the Image sampling thing.

**Comment by enzyme69** [comment]
@ly29 @nortikin @zeffii however, I want to bring an interesting question: Is Points to Delaunay 3D possible? And is it also possible to sample color from 3D texture pass it into points and then reapply into polygon?

**Comment by ly29** [comment]
Delaunay 3d is possible I guess, right now it only ignores the z data so you get a surface from the points, what that would become in 3d I am not sure

**Comment by enzyme69** [comment]
I think my wishlist for now is just to be able to have control over scatter points and color sampling from UV-ed polygon face :dancer:
