### ISSUE TITLE
Scatter Points based on Image content

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#827]
diverging from https://github.com/nortikin/sverchok/issues/825

@enzyme69

> Is it possible to have Image node to sample and scatter points based on
other things. Perhaps like scatter more dense points when lots of details.
What is the algorithm for this? I will research...

**Comment by zeffii** [comment]
you want an algorithm that generates a mesh with denser clusters of points in those areas where there's a lot of variation in color.

**Comment by ly29** [comment]
I feel that perhaps some preprocessing is better done in a app which is suited for that. 
However many interesting approaches are available, will perhaps play with this a bit...

**Comment by zeffii** [comment]
agreed, this isn't a priority for me.
