### ISSUE TITLE
Broken Centers Polygon

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#832]
![skarmavbild 2016-08-25 kl 20 32 49](https://cloud.githubusercontent.com/assets/6241382/17981225/20be5dea-6b03-11e6-8cc5-b67ab848231c.png)
If you don't separate it extends the lists instead for some unclear reason. 
So of the expected result of 81 we get 3321, (which is somewhat weird).

Offending code:
```python
                    if self.Separate:
                        norm_abs_out.append(norm_abs)
                        origins.append(centrs)
                        normals_out.append(normals)
                    else:
                        norm_abs_out.extend(norm_abs)
                        origins.extend(centrs)
                        normals_out.extend(normals)
```
https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/polygons_centers_mk3.py#L87-L94

The indentation level is wrong to do the extend. Also the separate threats each face as separate object. 
I feel like just decreasing the indent would help a  lot, any comments @nortikin ?

**Comment by ly29** [comment]
![skarmavbild 2016-08-25 kl 20 45 14](https://cloud.githubusercontent.com/assets/6241382/17981656/df5ddc02-6b04-11e6-97c9-06377e40ff07.png)
Un indenting gives the expected result at least.

**Comment by nortikin** [comment]
thanks, can commit?

**Comment by ly29** [comment]
I am afraid that it will break things that work around it. I will take closer look.

**Comment by nortikin** [comment]
i don'yt think so. users avoided this case, i guess. Because no bugtracking or feedbacks happened.

**Comment by ly29** [comment]
Will switch back mk3 and leave mk2 for now...

**Comment by ly29** [comment]
What exactly is the separate option supposed to do? It says separate per object, which is the default except for some really old nodes I guess.

**Comment by nortikin** [comment]
@ly29 it make grouped lists of vertices at every object, not a plain list

**Comment by ly29** [comment]
Okay, what is then reason not to separate? That seems like special case best left for list join or something like that.

**Comment by ly29** [comment]
Anyway I will not try to fix more here right now.

**Comment by nortikin** [comment]
agree

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/commit/59caf23831f21583e4201a8336e241163e284e33 this was my foult oups
