### ISSUE TITLE
Scalar Math Node socket placement bug (Pi->Sine->Sine)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#834]
When I use Math PI and switch to Sine math, I got 2 input slots. Weird. And the calculation failed.

Duplicating node is sometimes giving strange result. Sometimes.

![prtscr capture_20](https://cloud.githubusercontent.com/assets/3952687/18002250/fcb4b044-6bc9-11e6-8c7e-4bbaf810445e.png)
![pi_to_sin_error](https://cloud.githubusercontent.com/assets/3952687/18002253/fee784b8-6bc9-11e6-9bba-b89d8299b8f2.gif)

**Comment by ly29** [comment]
Easy to work around, just select sine again it is correct, will have to take a look at it though. Not looking forward to be messing around in that old old code.

**Comment by zeffii** [comment]
Vector math node also has occasional similar issues.

**Comment by ly29** [comment]
Logic node would probably be a victim as well.

**Comment by zeffii** [comment]
defo time for a MK3 of Math and Vector nodes. I've been looking at them on and off.. I think the painful part is the `socket switching / disconnect reconnect ` , the recursive fx fxy functions aren't such a big deal, I think you nailed those.

**Comment by ly29** [comment]
The logic failure is the ```set_inputs``` code. 

```python
    def set_inputs(self, n):
        if n == len(self.inputs):
            return
        if n < len(self.inputs):
            while n < len(self.inputs):
                self.inputs.remove(self.inputs[-1])
        if n > len(self.inputs):
            if 'X' not in self.inputs:
                self.inputs.new('StringsSocket', "X")
            if 'Y' not in self.inputs:
                self.inputs.new('StringsSocket', "Y")
            self.change_prop_type(None) 
```

**Comment by zeffii** [comment]
and seen as the socket switching / disco / reconnect are all reusable problems, it can be done in a sverchok.utils.janitor function or something :)

**Comment by ly29** [comment]
Or as mix-in class. I mean for example the code for multi socket input basically is a that. I could just be called ``` def update(self)``` and require some properties to be set...

```python
def multi_socket(node, min=1, start=0, breck=False, out_count=None):
# code

# could as well be ...

# with some properties set... 
class MultiSocket:
    def update(self):
```

**Comment by zeffii** [comment]
btw, wtf is `breck`

**Comment by ly29** [comment]
```python
    def set_inputs(self, n):
        if n == len(self.inputs):
            return
        if n < len(self.inputs):
            while n < len(self.inputs):
                self.inputs.remove(self.inputs[-1])
        if n > len(self.inputs):
            if 'X' not in self.inputs:
                self.inputs.new('StringsSocket', "X")
            if 'Y' not in self.inputs and n == 2: # only if y is needed
                self.inputs.new('StringsSocket', "Y")
            self.change_prop_type(None)
```

**Comment by ly29** [comment]
It means offset (in russian, googled it a long time ago), and controls the name offset it Formula nodes...

**Comment by zeffii** [comment]
`if `X` not in self.inputs` == `if not `X` in self.inputs`  ?

**Comment by ly29** [comment]
Very ugly solution but this code is all over the place and way to complex to dig into and try to clean up...

**Comment by zeffii** [comment]
no mean, i think we more often use the negation first in comparison 
`if not 'x' in self.inputs` instead of `if 'x' not in self.inputs`

**Comment by ly29** [comment]
@zeffii 
Yes it works exactly the same, but it is the same. I also generally prefer to ```not x in dict``` form now.

**Comment by zeffii** [comment]
```python
    def set_inputs(self, n):
        inputs = self.inputs
        num_inputs = len(inputs)

        if n == num_inputs:
            return
        if n < num_inputs:
            while n < num_inputs:
                inputs.remove(inputs[-1])
        if n > num_inputs:
            if 'X' not in inputs:
                inputs.new('StringsSocket', "X")
            if 'Y' not in inputs and n == 2: # only if y is needed
                inputs.new('StringsSocket', "Y")
            self.change_prop_type(None)
```

**Comment by zeffii** [comment]
ahh, breck is offset..  I might have asked that before :]

**Comment by nortikin** [comment]
:octopus: o_O
:book: breck?

**Comment by ly29** [comment]
Well, my memory might be wrong.

**Comment by nortikin** [comment]
offset in Russian отступ, ['o:tstu,p]

**Comment by ly29** [comment]
Bad memory, getting old.

**Comment by ly29** [comment]
But seriously, the vector/scalar math nodes really need some updating and cleanup.

**Comment by zeffii** [comment]
i'd also like a mode to output both `sin` and `cos` of an input.

**Comment by ly29** [comment]
Makes total sense.

**Comment by zeffii** [comment]
I was thinking we could define the bulk of this node in a dict/list
```python

one_to_one = {'in': ('X', s), 'out': ('result', s)}
one_to_two = {'in': ('X', s), 'out': (('result sin', s), ('result cos', s))}

bla = {
    'SIN': dict(op=sin, sockets=one_to_one, pidx=0, shortname='sin'),
    'COS': dict(op=cos, sockets=one_to_one, pidx=1, shortname='cos'),
    'SINCOS': dict(op=(sin, cos), sockets=one_to_two, pidx=2, shortname='sincos'),
    ...
}
```
