### ISSUE TITLE
Image Decomposer

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#835]
Not sure if the result is accurate. Maybe I need to shift something.

![prtscr capture_22](https://cloud.githubusercontent.com/assets/3952687/18003303/2016d02a-6bd0-11e6-8174-049b6a873a6f.png)
![prtscr capture_21](https://cloud.githubusercontent.com/assets/3952687/18003304/20192a00-6bd0-11e6-95c4-267ff88b69c7.png)

This node requires some guess work, even after reading the documentations.

Wonder why the RGBA needs multiple by 100. 

And also wondering about xy_spread and z_spread attribute and what can I plug into that. Maybe random?

Thanks!

**Comment by enzyme69** [comment]
And for unknown reason, Vertex Colors easily lost the connection and giving "red" reading on Sv_VColor. And getting black when rendering.

![prtscr capture_23](https://cloud.githubusercontent.com/assets/3952687/18003411/b440db24-6bd0-11e6-82dc-4e09dd8c9926.png)

**Comment by ly29** [comment]
To the second part it is because the order of update is undefined between colors and the bmesh viewer and changing the geometry of the mesh will destroy the vertex color layer.
For now turn off updates on the mesh viewer after the initial mesh been generated if you are just going to play with colors.

**Comment by enzyme69** [comment]
​Ok, and what's with the skewy result of Poly coloring? Also, is this Image
Decomposer smart enough to sample from random 2D points?

**Comment by enzyme69** [comment]
​How to "turn off updates on mesh viewer"

**Comment by enzyme69** [comment]
​Ok I switched off UPD.

**Comment by enzyme69** [comment]
You are correct, it now renders. Still skewed.



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by ly29** [comment]
@zeffii 
Any input on this?

**Comment by zeffii** [comment]
@ly29 
nope, it's possible that the image class now makes the A component optional, cycles has been receiving some updates.

would be neat to get a .blend file that I can just load up and inspect..

**Comment by zeffii** [comment]
Also.. rather than using an image that's much higher resolution, might i suggest downsampling in photoshop/gimp first, then you don't have to use skip.

**Comment by zeffii** [comment]
can confirm that doesn't have anything to do with png/jpg RGB vs RGBA blender generates a A channel in image.pixels even when it isn't used.

It seems that when you use V in the VertexColor Node that the order is right, 

![image](https://cloud.githubusercontent.com/assets/619340/18005164/7de5ae16-6b98-11e6-8c94-3071c20f0dd2.png)

but when you use P it's skewed. ..

![image](https://cloud.githubusercontent.com/assets/619340/18005173/8f89bcf2-6b98-11e6-9e67-4fd4cb1cbe6a.png)

**Comment by ly29** [comment]
P sets color value per face, you need get them accordingly, see #836

**Comment by zeffii** [comment]
set the `Z_spread` to 1 will output the correct RGB values.

**Comment by ly29** [comment]
Would be neat you could do via the composer and read the result.

**Comment by zeffii** [comment]
this isn't really a bug in ImageDecompose, i'd have to look at the VertexColor node to figure out what's going on, but @ly29 checking that out now so i'll avoid it for a while.

**Comment by enzyme69** [comment]
Ok, but one more thing: can Image Decomposer actually uses a different
source mesh like random point scatter to sample the image color, rather
than Grid or Planes?

It will work only as 2D isn't it. So the deformer modifier rgb xyz method
is still good.


-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
correct, the Image Decomposer is 'rigid' in this respect. just a grid. 

Sampling from a list of 2d points that correspond with Image pixels is something i've written a script for which could be implemented as a node, but probably make more sense as a scriptnode..

**Comment by enzyme69** [comment]
![prtscr capture_45](https://cloud.githubusercontent.com/assets/3952687/18030474/56863de6-6cfa-11e6-8093-bec35468b50c.png)

In the last 3 version update, Sverchok, this Image Decomposer is no longer working...

**Comment by ly29** [comment]
The file was last changed in 2014 so it is more likely that there is some bug with opening a file or F8... Try unload / reload the image

**Comment by zeffii** [comment]
nope. read the docs jimmy. first two sockets need a connection for it to output anything. this is by design.

**Comment by enzyme69** [comment]
Yes, but @zeffii  it's not working anymore, I tried all kinds of ways. It was working 2 days ago.

**Comment by zeffii** [comment]
> The file was last changed in 2014

maybe you did a recent blender update? that _could_ explain if something has stopped working (I rarely update Blender beyond major releases.. or unless something is obviously broken)

I will concede that the node is not fool-proof, and may not have defaults that make sense to anyone but me. The prerequisite to have the two first outputs connected to make it do any processing has tricked me several times.

I'm experimenting now with small images to better understand why the VertexColor node shows skewed images.

**Comment by ly29** [comment]
For me it is working as one would expect.
![skarmavbild 2016-08-28 kl 12 26 56](https://cloud.githubusercontent.com/assets/6241382/18033099/c81756a0-6d1a-11e6-867c-1e084e0fdaef.png)

**Comment by enzyme69** [comment]
​This is really strange... I didn't upgrade Blender. Nothing has changed
since last time. I will try Mac.

Using PC. Maybe I need to re-install Sverchok the next Blender update?

https://youtu.be/6c0512nn_ZY

**Comment by zeffii** [comment]
ok, i think i understand now. the node outputs  fewer rgb values than polygons. hence in VertexColor Polygon mode it will reach the end earlier and repeat the last value till done.

![image](https://cloud.githubusercontent.com/assets/619340/18033193/9f4b7d9e-6d1c-11e6-9155-c220f1633e11.png)

```python
28 * 36 = 1008
(28-1) * (36-1) = 945
```

**Comment by enzyme69** [comment]
Not working on Mac either. I will wait. Sorry bout this. Will meditate.

**Comment by zeffii** [comment]
let me just say that Image Decompose node was never designed with VertexColor node in mind, I am outputting vertex colors so

```
c---------c---------c---------c
|         |         |         | 
|         |         |         |
|         |         |         |
c---------c---------c---------c
|         |         |         |
|         |         |         |
|         |         |         |
c---------c---------c---------c

.---------.---------.---------.
|         |         |         | 
|    c    |    c    |    c    |
|         |         |         |
.---------.---------.---------.
|         |         |         |
|    c    |    c    |    c    |
|         |         |         |
.---------.---------.---------.
```

**Comment by zeffii** [comment]
this is why the Vertex mode kind of works (accidentally), but Polygon mode starts to wrap early

**Comment by zeffii** [comment]
here's script node that drops the last color of each column, and the last row entirely - this will create a set of colors matching the polygon count.

```python
def sv_main(colors=[[]], rows=4, cols=5):

    cols_out = []
    
    in_sockets = [
        ['s', 'colors', colors],
        ['s', 'rows', rows],
        ['s', 'cols', cols]]


    out_sockets = [
        ['v', 'cols', cols_out]
    ]
    
    if colors and colors[0]:
        c = colors[0]
        cout = []
        for i, item in enumerate(c):
            if i%cols== 0 or i>((rows-1)*(cols)):
                continue
            cout.append(item)
        cols_out.append(cout)

    return in_sockets, out_sockets

```
![image](https://cloud.githubusercontent.com/assets/619340/18034470/4841cb9e-6d3e-11e6-8d02-5c59ce1e62ec.png)

it will be similar but the border will be clipped by one pixel

**Comment by ly29** [comment]
Or for more complex cases use the image sampling script for polygon centers. Or the uv maps scripts. 
The image sampling I will turn into a node, the other I think needs a little bit more thinking. No timeline though

**Comment by zeffii** [comment]
a `numpy` based formula node is worth considering...

**Comment by ly29** [comment]
It kind of exists.

**Comment by zeffii** [comment]
ah yes.. have not yet had occasion to test-drive it on the road

![image](https://cloud.githubusercontent.com/assets/619340/18034856/0557de86-6d48-11e6-836a-4249c9fd3ceb.png)

**Comment by zeffii** [comment]
here a numpy version.

```python
import numpy as np

def sv_main(colors=[[]], rows=4, cols=5):

    cols_out = []

    in_sockets = [
        ['s', 'colors', colors],
        ['s', 'rows', rows],
        ['s', 'cols', cols]]

    out_sockets = [
        ['v', 'cols', cols_out]
    ]

    if colors and colors[0]:
        c = colors[0]
        num_items = rows*cols
        num_items_fewer = (rows - 1) * (cols - 1)

        x = np.array(c).reshape(rows, cols, 3)
        x2 = x[0:rows-1,:-1,]
        x3 = np.reshape(np.ravel(x2), (num_items_fewer, 3)).tolist()

        cols_out.append(x3)

    return in_sockets, out_sockets
```
