### ISSUE TITLE
GText mods

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#841]
load your own font .tff

![image](https://cloud.githubusercontent.com/assets/619340/18130371/0f5d7b36-6f8f-11e6-99d3-6d657cc4566d.png)

this may be of some interest.. it's something i've been meaning to make for while... alas with no antialiasing on the glyphs this is painful... 

it is also quite heavy on the nodeview unless everything is unticked in the gp props..

**Comment by ly29** [comment]
That does look very nice. Strange that grease pencil is so heavy to draw.

**Comment by zeffii** [comment]
well, i'm pre tesselating it, because my font-gp algorithm was written some time ago before the 'high quality fill' feature was added. I could probably skip the triangulation and instead draw the largest ngons possible per glyph, would reduce a lot of the overhead I think..

**Comment by ly29** [comment]
If you are tesselating it, you could draw it with opengl.

**Comment by zeffii** [comment]
would work perfectly with a display list (or whatever replaces it)

**Comment by zeffii** [comment]
at that point we might as well be drawing the nodetree ourselves too, tempting in some aspects..

**Comment by ly29** [comment]
Both yes and no. But would be fun... Maybe later...
