### ISSUE TITLE
Where to start with Sverchock as a user?

### ISSUE THREAD

**Issue by ccamara** [nortikin/sverchok#842]
I would like to start using sverchock to do very basic stuff, as I have never used parametric modelling. In fact I wanted to use it to extrude some planes according to a custom property (number) which stored as a custom property. 

I have seen there's quite a lot of documentation in several places (like http://nortikin.github.io/sverchok or the newest site http://sverchok.readthedocs.io/en/latest/geometry.html).  However, IMHO these information, although seems to be very good is too specific and does not cover the really basics, eg: how can I start adding nodes, how these nodes are linked to already existing geometry, which nodes can be used with vertexs, edges, faces, meshes... Is there any place I could start reading?

Thanks

**Comment by ly29** [comment]
You down load the zip file, install the add-on as usual in blender. Activate it.
Go to node space and select a new icon besides the usual (material, textures etc) to select the Sverchok node type.
Then pressing Shift-A open up the node menu as usual.
For concrete lessons on basic level to start thinking with parameters I think @zeffii series is a good read. See http://sverchok.readthedocs.io/en/latest/induction.html

**Comment by ly29** [comment]
Also if you have any questions about specific nodes or things you want to achieve don`t hesitate to ask them here.
The nodes themselves aren't linked to existing blender objects, you can use information from blender objects or create blender meshes that are informed and controlled from Sverchok.

**Comment by zeffii** [comment]
@ccamara 

Sverchok's main use-case is creating geometry from scratch, and that's what we focus on in development, but we are adding more ways to use with existing scene data/objects that don't require any programming. The task you envision to use Sverchok for might not be completed using any conveniently available node-configuration. Perhaps describe what you hope to achieve and we can suggest an approach that would work best with how Sverchok works.

Sverchok _can_ import existing scene Objects, but doesn't have a standard way to read custom data from them and pass that data along as a socket 'stream'. Reading custom properties can be done, it's easy, but may not be obvious and may require some python. I can imagine you have a scenario where each Object also has a IDProperty, for instance `thickness`, then you would read that value with python by getting the value stored in `obj['thickness']`.

For example.

![image](https://cloud.githubusercontent.com/assets/619340/18140420/c05c5cce-6fb5-11e6-8e88-8a8a3a2f84c9.png)

i'd write a scriptnode, but this may be a very brittle solution, and something we would consider starting from a different premise.

![image](https://cloud.githubusercontent.com/assets/619340/18141119/878150dc-6fb8-11e6-8878-54eefee5d2ae.png)

**Comment by ccamara** [comment]
Thank you very much for your quick answers @ly29 and @zeffii ! I didn't know Sverchock was for creating new geometry only, as I thought it could also be used in order to modify existing one :( 

What I wanted to do is to import a file from OpenStreetMap (using this interesting addon: [blender-geo](https://github.com/vvoovv/blender-geo)) and extrude their surfaces according to their properties (in OSM they have a tag called `building:levels=n` and from what I have seen this information (as well as other ones like address, name...) is added to the geometry as custom properties (I am quite newbie to blender, so I didn't know that was possible and I do not know how it works -so I cannot answer your question, @zeffii ). From what I have seen, the importer does extrude meshes provided the original geometry has the tag `building:height=n` (where n is a number), but the problem is that few buildings have such tags in the area I have to work, but they do have the number of levels. For that reason I wanted to aproximate their heights and extrude the planes according to their number of levels * 3m.  Hope it's clearer now, but if you need further explanations let me know.

as for @zeffii 's comment:

>Sverchok can import existing scene Objects, but doesn't have a standard way to read custom data from them and pass that data along as a socket 'stream'. Reading custom properties can be done, it's easy, but may not be obvious and may require some python. I can imagine you have a scenario where each Object also has a IDProperty, for instance thickness, then you would read that value with python by getting the value stored in obj['thickness'].

I'm afraid I didnt understand anything :(

as for @ly29 's 

> Go to node space and select a new icon besides the usual (material, textures etc) to select the Sverchok node type.
> Then pressing Shift-A open up the node menu as usual.

Thank you! that's the kind of information I didn't find in the documentation (which IMHO is quite technical, but lacks this kind of things -> I will contribute to it when I learn about sverchock)

> For concrete lessons on basic level to start thinking with parameters I think @zeffii series is a good read. See http://sverchok.readthedocs.io/en/latest/induction.html

I did read it, and although I think @zeffii has done a great work documenting I found it too technical and does not cover my needs, which are more basic and prosaic (I'd like to find where to start, not the foundations or how does sverchok internally works). I'm sure a more advanced user will find it useful, though. So I am not blaming him for the job he has already done.

**Comment by zeffii** [comment]
I'm not saying Sverchok can't do it, it's more a matter of using the right tool for the job.

I would probably first write a script to add a modifier like Solidify to each object that has the property and set the thickness to be some factor of the height value. -- I would do this before considering trying to do it in Sverchok.

As for the documentation, we kind of presume some familiarity with the Blender node trees like Cycles or the Compositor, We felt that a rudimentary understand of how to use those was sufficient for most people to get up-to-speed with Sverchok fairly fast. It gets complicated fast too.

Possibly Animation Nodes add-on would cater more directly to the kind of things you wanted to do, it is aimed more at interacting with scene objects.

**Comment by zeffii** [comment]
@ccamara wrote:
> From what I have seen, the importer does extrude meshes provided the original geometry has the tag building:height=n (where n is a number), but the problem is that few buildings have such tags in the area I have to work, but they do have the number of levels.

I think you could make a case to the author of the blender-osm addon (vvoovv) to include `building:levels=n` as an optional extrusion factor.. that way the issue gets fixed in the tool and will persist for other projects and other people.
