### ISSUE TITLE
Bmesh - Grouping Output Bug

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#843]
I am doing lots of "instancing" using Matrix, and when I switch on Group in BMesh MK2, instead of grouping properly each instance, it is also creating group for each object... Not expecting this behaviour.

![prtscr capture_3](https://cloud.githubusercontent.com/assets/3952687/18160009/a2a76890-706e-11e6-87f6-b5bef7644a0c.png)
![prtscr capture_2](https://cloud.githubusercontent.com/assets/3952687/18160010/a2b99088-706e-11e6-8f19-6747c1f60220.png)

**Comment by zeffii** [comment]
I'll have to have a look at it,, I also do not expect this behaviour.

**Comment by zeffii** [comment]
it looks like there was never any cleanup done of dormant groups, the extra groups are all empty. (and don't show up in Scene outliner) - i should have looked a little deeper.

hope to fix this soon @enzyme69  thanks!

**Comment by zeffii** [comment]
As an asside: 
I was considering dropping the Group feature entirely in favour of simple parenting and an automatic Empty for each BMeshViewer.

**Comment by zeffii** [comment]
update https://github.com/nortikin/sverchok/pull/845 (not sure if you can update if I don't do a version bump?)

**Comment by zeffii** [comment]
this simple change in code should prevent multiple groups being generated by the node, then I think that also prevents the follow on issue of objects not being deletable because of 'stale groups' containing them.

**Comment by zeffii** [comment]
@enzyme69  please try to reproduce with a fresh blender.

**Comment by zeffii** [comment]
@enzyme69 I pushed a modification which may or may not prevent that from happening again, but I suspect the interaction with AN can lead to all kinds of unforeseen issues.. like if AN becomes a user of an Object or a Group and for whatever reason Sverchok-BMeshViewer attempts to delete a Group/Object due to changes in input matrix-count. I will be less surprised if you find unusual behaviour as a side effect.

**Comment by zeffii** [comment]
closing until you respond :)

**Comment by enzyme69** [comment]
I guess it should be good for now. To prevent side effects, I probably need to bake Sverchok generated items and continue from there. But should be good thanks man!

**Comment by zeffii** [comment]
i haven't been able to reproduce that excess creation of groups, but that doesn't mean i've fixed it :) -- but if you update and can show me a fool-proof way to create excess groups i'll happily revisit the problem :)

thanks again for keeping us on our toes!
