### ISSUE TITLE
Something is not right with Viewer or BMesh MK2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#844]
I tried this simple setup, expecting just "Lofting", the Viewer is displaying it, but I cannot Bake. And MK2 refuse to take this setup. 

So weird! This used to work. 

![prtscr capture_19](https://cloud.githubusercontent.com/assets/3952687/18163931/b0dbe938-7080-11e6-946e-62f85212fe6b.png)

https://www.dropbox.com/s/9ytn8l90c31dbju/ANSV_lofting_012.blend?dl=0

**Comment by enzyme69** [comment]
![prtscr capture_21](https://cloud.githubusercontent.com/assets/3952687/18163981/ef6f586a-7080-11e6-8a73-d67c03d36dd9.png)

This also didn't work, but the Viewer does display the result...  :(

**Comment by zeffii** [comment]
in the second image at least you are mismatching the number of matrices with the number of vertex lists, I don't think the `MatrixApplyNode` is handling that very well, it is red for a reason.

not sure about what's happening in the first image.

**Comment by ly29** [comment]
The baking fails silently, the data looks good as far as I can see, quick check.

A lot of code to check...
https://github.com/nortikin/sverchok/blob/master/nodes/basic_view/viewer_mk2.py#L43-L151

**Comment by ly29** [comment]
Cylinder subdivisions should be -2.
Having 0 subdivisions gives the top and bottom already.
![skarmavbild 2016-09-01 kl 13 02 42](https://cloud.githubusercontent.com/assets/6241382/18165234/67aec49c-7044-11e6-8f96-7c872d143b9e.png)

**Comment by ly29** [comment]
Probably good if viewer draw indicated bad typology somehow, also if baking didn't fail silently.

**Comment by zeffii** [comment]
the edges your creating reference `[......[629, 616, 630, 643]]`, so you are feeding it far more indices in the Polygons list. The VDmK2 happily displays as many as it can, and simply stops when a polygon references a vertex that doesnt exist. The baker unfortunately doesn't let you off the hook so easily, it assumes the incoming data is all valid.

This could be fixed, but isn't a priority for me atm. Feed it the right data for the time being.

**Comment by zeffii** [comment]
agreed, the baker could output an error message to the Info panel. This I will happily do.

**Comment by ly29** [comment]
Better feedback is needed

**Comment by ly29** [comment]
But it isn't a priority right now, if we removed a lot of checks in the drawing code it would be good. But there isn't any nice way for the callback to give feedback right now. 

I would have thought the baking would throw an error somewhere which would make fail noisily. Crashing is good sometimes...
