### ISSUE TITLE
update precedence of subgraphs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#847]
When nodetrees have various subgraphs, rather than the current behaviour of (update each subgraph in the order returned by a hash, for simplicty) I think there's a innocuous way to sort the subgraph updates, use the Y location of the last node in the subgraph.

This way we can be more confident that subgraphs update in an obvious sequence.

A visual programming language like PureData uses Y location of nodes to solve potentially complicated UI issues with relative ease. At first it seems weird, then it's obvious and stays obvious.

**Comment by ly29** [comment]
That sounds resonable. It would require a small rewrite of the needlessly complicated update system which would be a good thing... Infact of potential nodes to evaluate we could always apply the y order using the minimum topological distance from outputs. A bit like in #817 where the algorithm for that basically exists, not super nice...

Also it would be nice if ```switch``` nodes actually worked like ```if/else``` so nodes that won't affect the result aren't processed...

**Comment by ly29** [comment]
For subgraphs
1. Generate topological value for each node
2. Sort based on with ```key=lambda node: node.topovalue, -node.y```

**Comment by ly29** [comment]
Having looked at the code in question separated graphs could to changed to work like this in 5 min or so...

**Comment by zeffii** [comment]
it would for instance solve the racecondition posed by unconnected graphs that output meshes to the Scene and Vertex Color.  If we get this going, i'm likely to start adding more Scene based nodes, (like @ccamara could have used.. taking object ID props, in the order of the objects selected by a certain Objects In -- for example)

**Comment by zeffii** [comment]
or such nodes could be easily written as a `snmk3`, a nice use-case

**Comment by ly29** [comment]
I think I will add an object socket which I think is a better solution, but some extra depdendability could be good course. 

Will do this in small gradual steps.

**Comment by ly29** [comment]
This is a bit like Python indentation, both ugly and efficient, have somewhat mixed feelings about, in general I think it is better if relationships are made explicit at the same time it is convenient.

**Comment by zeffii** [comment]
well, the Y sorting could be based on lowest Y position node, rather than highest. At least that is analogous to _indentation_

**Comment by ly29** [comment]
Okay separate node set will be updated from top to bottom of their average location. in testing branch ```update_y```
Inside of node a node set is different matter, still todo...
![skarmavbild 2016-09-02 kl 18 43 46](https://cloud.githubusercontent.com/assets/6241382/18211290/3e127c10-713d-11e6-8040-7d93974dc60a.png)

**Comment by zeffii** [comment]
so:  if you have the terminators or apex's of a subgraph, the average earliest of the terminator or apex of each subgraph can command the precedence.

i'm not sure I understand when you say  you want to also order precedence of nodes within a subgraph, something subconsciously thinks that's a bad idea.

**Comment by zeffii** [comment]
or the X location, (i've been saying Y the whole time... but meant X ..  _PureData_ uses X )  Not that it really matters.. the convention matters.

**Comment by ly29** [comment]
Clearly topological ordering takes higest precedence. Only after that y would come into play.

**Comment by zeffii** [comment]
this could be very interesting! ..it can always be disabled if it turns out to be a nuisance

**Comment by ly29** [comment]
Nothing would change from today. The order that could be manipulated  by moving the nodes would be a possible order today. 
If you have time make a simple image and explain it visually, it would be helpful to understand

**Comment by zeffii** [comment]
hmm, not working as expected..bt i'm probably doing something wrong..
import as 'NodeTree'  :)

damn.. did I never add an upload json gist? only download?

https://gist.github.com/zeffii/c4d6f5366803160b4e78a6347ac62112

gist import needs a small fix. (ill get on it immediately)

**Comment by zeffii** [comment]
uchh.. json doesn't carry cycles materials  : /

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/18213117/e0e9b3a0-7146-11e6-91ca-e5be8e435c4b.png)

**Comment by ly29** [comment]
I think that actually when you set that int the sverchok processing will be suspended and another instance of the sverchok update system will launch the second part, but the first part might not have executed bmesh viewer.


What I propose is the following.
Use the topological max depth to define the execution order. If two nodes tie, then execute the on with higher y first.
![skarmavbild 2016-09-02 kl 21 33 20](https://cloud.githubusercontent.com/assets/6241382/18216146/46c7b9d4-7155-11e6-9315-c9823202b558.png)

**Comment by zeffii** [comment]
yikes, yeah. maybe this is wasted energy. sorry.

btw the topological order indices being drawn by bgl could prove useful as a debug tool?

**Comment by ly29** [comment]
Yeah, also giving some debug info via bgl could be nice, like drawing some info about thrown errors etc.
