### ISSUE TITLE
Node Conversions

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#848]
Int -> Float -> Int
FloatRange -> IntRange -> FloatRange

![waxing](https://cloud.githubusercontent.com/assets/619340/18207570/f2b8f336-712b-11e6-878c-0acb542b12f2.gif)

maybe for the Int and Float nodes I would prefer them to have a button in the UI to switch between types.. but this was interesting..

**Comment by ly29** [comment]
If we can switch we could but a button in ext for the operator.

**Comment by zeffii** [comment]
if there's interest for it, absolutely. but closing for now
