### ISSUE TITLE
IO/json gist upload/download

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#849]
Two things while i'm at it.

- [x] small bug for windows users, py3 doesn't allow a `openurl(url).readall()` it only does `read()`, this imho is some weird crossplatform nonsense, but i'll add code to check for both
- [x] add anon upload of gist directly from Blender panel (code already written) and copy gist ID into clipboad for sharing.

**Comment by zeffii** [comment]
`c4d6f5366803160b4e78a6347ac62112` i need to know if importing that as a gist ID works on posix systems, @ly29  or does it give an error 
```python
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or bytes-like object
```
i'll know what to do.

**Comment by ly29** [comment]
```python
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or bytes-like object
```
This is what I get @zeffii

**Comment by ly29** [comment]
Also in master ```readall``` didn't work either on OS X.

**Comment by ly29** [comment]
Why is there even an ```readall``` method? Python read just returns everything it can if you don't limit it.

**Comment by zeffii** [comment]
don't know, that's the code that worked once..and now ..no longer does.

**Comment by zeffii** [comment]
the code can be simplified quite a bit..

**Comment by zeffii** [comment]
cool..
```python
import json
from urllib.request import (urlopen, urlretrieve)
# 

gist_id = 'c4d6f5366803160b4e78a6347ac62112'

def read_n_decode(url):
    content_at_url = urlopen(url)

    try:
        # posix
        found_json = content_at_url.readall().decode()
    except:
        # windows..
        found_json = content_at_url.read().decode()
    finally:
        return found_json    


gist_id = str(gist_id)
url = 'https://api.github.com/gists/' + gist_id
found_json = read_n_decode(url)

wfile = json.JSONDecoder()
wjson = wfile.decode(found_json)

# 'files' may contain several - this will mess up gist name.
files_flag = 'files'
file_names = list(wjson[files_flag].keys())
file_name = file_names[0]
nodes_str = wjson['files'][file_name]['content']
nodes_json = json.loads(nodes_str)
print(nodes_json)
```

**Comment by zeffii** [comment]
i'll fix this tomorrow. tired :]  goodnight.

**Comment by zeffii** [comment]
import gist now working again..

**Comment by zeffii** [comment]
exported directly from the export panel and the url goes into the system clipboard
```https://gist.github.com/ec541abe51daea0ffd516ef5416eeeef```

**Comment by zeffii** [comment]
tho perhaps the panel needs a proper separator now..
![image](https://cloud.githubusercontent.com/assets/619340/18224348/6ece6586-71d2-11e6-901a-adbb5ea0d6cb.png)

**Comment by zeffii** [comment]
![io_enum](https://cloud.githubusercontent.com/assets/619340/18224875/c993715c-71e4-11e6-8828-9149488d8059.gif)

almost done..

**Comment by ly29** [comment]
Looks good

**Comment by zeffii** [comment]
may have register a collectionprop instead polution ntree namespace..

**Comment by zeffii** [comment]
![io_enum](https://cloud.githubusercontent.com/assets/619340/18224930/a91421ae-71e6-11e6-8d41-c92fc3e0d77b.gif)

**Comment by zeffii** [comment]
further refinement should happen to that UI, but it doesn't bother me enough atm

**Comment by zeffii** [comment]
```python
class IOPanelProperties(bpy.types.PropertyGroup):

    .new_nodetree_name = StringProperty(
        name='new_nodetree_name',
        default="Imported_name",
        description="The name to give the new NodeTree, defaults to: Imported")

    bpy.types.SverchCustomTreeType.compress_output = BoolProperty(
        default=0,
        name='compress_output',
        description='option to also compress the json, will generate both')

    bpy.types.SverchCustomTreeType.gist_id = StringProperty(
        name='new_gist_id',
        default="Enter Gist ID here",
        description="This gist ID will be used to obtain the RAW .json from github")

    display_io_options = [
        # having element 0 and 1 helps reduce code.
        ("Import", "Import", "", 0),
        ("Export", "Export", "", 1)
    ]
    
    bpy.types.SverchCustomTreeType.io_options_enum = bpy.props.EnumProperty(
        items=display_io_options,
        description="display import or export",
        default="Export"
    )

# register
bpy.types.SverchCustomTreeType.io_panel_properties = bpy.props.PointerProperty(
    name="io_panel_properties", type=IOPanelProperties)

# unregister
del bpy.types.Scene.io_panel_properties

```
