### ISSUE TITLE
Monad Exploration

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#850]
I am thinking to test this Monad thing and wondering about a couple of things.

![Uploading Screen Shot 2016-09-03 at 11.32.49.png…]()
![Uploading Screen Shot 2016-09-03 at 11.24.29.png…]()

So I generated a Monad that simply just draw Circle X number of times, get bigger each time. For the Monad inputs:
* Int number of circles
* positioning of bunch of circles as whole

As you know I usually use Matrix to duplicate, but then not quite sure how to Mix Matrix in Sverchok like Animation Nodes.

With Monad, I would like to do the usual duplications using Matrix, and also able to have variations per Monad being instanced.

Is this actually possible in Sverchok?

**Comment by enzyme69** [comment]
I reckon the Iteration Matrix can solve what I am trying to do.

**Comment by ly29** [comment]
Please upload the images.

In general a monad or node groups are just like functions, so all variations have to be inputs. It is possible to do a stateful monad but it not a good idea.

**Comment by enzyme69** [comment]
Reuploaded...
![screen shot 2016-09-03 at 11 24 29](https://cloud.githubusercontent.com/assets/3952687/18223568/76d981d0-71fe-11e6-9abd-1c3897dce176.png)
![screen shot 2016-09-03 at 11 32 49](https://cloud.githubusercontent.com/assets/3952687/18223569/772e4080-71fe-11e6-8fec-fb2e05110cdb.png)

When doing this using program like Processing, it's almost too simple.

Animation Nodes looping is kind of logical and I was expecnting it to be able to do like Processing when Grouped, but then it has this limitation on instancing and vectorization. Too convoluted.

Sverchok, I think can do it, but different logic.

Ly, you probably have shown something similar, but Monad, I wonder how to do this.

In the past, I only tried the Vectorization variation of Lines, Circles. But this is when I tried to use Monad to try to make like Object Class, and variations.

Iteration Matrix is not the answer, it's always put Blender to hang, I did the wrong thing.

**Comment by zeffii** [comment]
the Monad, currently, is more precisely like a Node Group than you might think. It doesn't do Vectorization 'for free', it's not like if you add a RangeInt node to the input of a Monad that it will execute the whole monad with each value emitted by the RangeInt, and combine all 'streams' at the end. 

That would take a more fundamental design rewrite of Monads.. For now Monads are a way to abstract away a collection of nodes to show that they are tightly cohesive and you don't need to see them.

**Comment by ly29** [comment]
Well if would take some doing but wouldn`t be that hard. But I have enough project under way to try to do that.

**Comment by zeffii** [comment]
Also... if _Processing_ is so simple, it's because you are writing code in that casem, and for simple things processing is simple, but the ease of implementation is itself a function of the complexity of the task, hard stuff is still hard with _Processing_.  

Get more familiar with ScriptNode, we could definitely offer a whole range of convenience functions for ScriptNode, like 

```python
from sv_geom import SvCircle, SvGrid, SvCube, 

verts, edges, faces = svCircle(origin=(x,y,z), radius=2,2, vert_count=20)
```

**Comment by enzyme69** [comment]
Where can I found documentation of all convenience ScriptNode Sv Functions?

**Comment by ly29** [comment]
@enzyme69 key word is **could**

**Comment by zeffii** [comment]
let's make this a separate issue, I think a lot can be offered in terms of similarity to Processing builtins.

**Comment by zeffii** [comment]
It would definitely open up insane possibilities if we made Monads powerful enough to be able to optionally vectorize inputs, the problem is almost never one of a technical nature, but more of 'how to expose such behaviour in a consistent way'.

For now, like @ly29 says - consider monads a organisational tool. We will no doubt return to this topic at a later stage. Hopefully this answers the question, if not re-open!
