### ISSUE TITLE
Vertex Color breaks on matrix change

### ISSUE THREAD

**Issue by diramazioni** [nortikin/sverchok#851]
Hello to all, the Vertex Color node loose the colors on any matrix change. This problem is **not always** happening and not always Update All button fix it, sometime the only way to get the color back is to fiddle with the color data (like changing the seed in this example)
![vcol_break](https://cloud.githubusercontent.com/assets/682046/18221995/c0811e80-7189-11e6-9bfc-bcafe3d8e491.jpg)
[blend](http://pasteall.org/blend/index.php?id=43355)

Often there is no error in the console but I've seen Python internal context error but I hope was realated to some other bug.
Can you reproduce?

**Comment by ly29** [comment]
Sadly it is known problem, I will try resolve it.

**Comment by ly29** [comment]
Since I will this in a separate issue I will close this one. See #853
