### ISSUE TITLE
Switching Node Tree Type --> Auto Active

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#852]
This is a small annoyance, but do quite noticeable. Wonder if there is a way so that Node Tree in Sverchok can be active when switching node tree.

With Animation Nodes, the last Node Tree Type and last Node Tree Network will be displayed. When switching to Sverchok, the last Node Tree Type is always needing to be re-selected. Each time switching node type. 

I tried pinning, didn't actually work.

**Comment by ly29** [comment]
Will try to look into the difference and why this happens.

**Comment by zeffii** [comment]
we need an app handler? and a global variable to store the last updated nodetree..  i've seen how AN approaches this.. seems a little over-the-top , (but then again, maybe it has to be done that way)

**Comment by ly29** [comment]
I was suspecting something like that... I guess it is what is needed.

**Comment by ly29** [comment]
For various reasons we might need an app handler anyway...

**Comment by zeffii** [comment]
yeah, like giving each nodetree a fake user.

**Comment by ly29** [comment]
Restarting after F8, appended monads etc.

**Comment by zeffii** [comment]
a known limitation for which the solution is a little bit more ugly (in my eyes) than leaving it the way it is. closing for now.
