### ISSUE TITLE
convenience Functions for ScriptNodes (geometry, ..etc)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#854]
With a new ScriptNode MK3 being in the works, it makes sense to offer a set of useful building blocks to make ScriptNode exploration easy and possibly more fun to write docs for. A module named `geom`. Some of these can be taken from bmesh primitives, or self implemented .

> A tick will mean : 
> - the basic pydata/bm versions are done.
> - Numpy versions will be a second pass (and can alternatively be made by a pydata->np wrapper..)
> - not all params final and not all codeflows final  
> - todo transformation matrix support, which will be the same for all

2D
- [x] geom.circle 
- [x] geom.arc
- [x] geom.quad
- [x] geom.arc_slice
- [x] geom.rect 
- [x] geom.line  
- [x] geom.grid  

3D
- [ ] geom.cube
- [ ] geom.rounded_cube
- [ ] geom.cone
- [ ] geom.ico_sphere
- [ ] geom.uv_sphere
- [ ] geom.cylinder
- [ ] geom.torus
- [x] geom.CubicSpline and LinearSpline

and some constants like processing

```
HALF_PI
PI
QUARTER_PI
TAU
TWO_PI
```

maybe some other concepts.. http://p5js.org/reference/

**Comment by ly29** [comment]
Would also be nice with ```numpy``` variants allowing further manipulation or large numbers in an easy to do manner.

**Comment by zeffii** [comment]
yeah we can go nuts on this, and even reuse them in the regular nodes. 

also, the functions could be provided in vectorized form `sv_geom.vec_circle`, or built into the normal function

```python
 circle(radius=[2,3, 3,4, 5,6], verts=20, mesh='VE')   # V, VE, VEP
```
could return 3 sets of Vectors and Edges..

**Comment by ly29** [comment]
Would be great to have this in the examples for SN3 from the beginning.

**Comment by zeffii** [comment]
very well. i do agree

**Comment by ly29** [comment]
Also would be great to reuse function in the ordinary nodes because that way we can ensure that they actually work the way one would expect.

**Comment by zeffii** [comment]
yes, certainly, and we don't need to stop at geom function either. handy conveniences for list matching / merging.. kdtree (a slight abstraction!)

**Comment by ly29** [comment]
most definitely. but as a testing ground geometry seems perfect

**Comment by zeffii** [comment]
doing this in the geom branch, probably testing with SN1 temporarily, then merge with MK3 before MK3 hits master?

**Comment by ly29** [comment]
Sounds sane, I will proabably merge the socket parts of SN3 quite soon and begin obj socket transistion.

**Comment by ly29** [comment]
I will do the spline since the implementation for linear is somewhat split into the node function.

```
class Spline:
    def __init__(self, points, kind='CUBIC', metric='DISTANCE'):
             # make the spline

   def eval(t):
    
  def eval_tanget(t, normalized=True)

```
Perhaps with a function that creates and evaluates in one go. On top of this we could build surface a patch thing.

**Comment by zeffii** [comment]
i'm making vectorized geom functions from the beginning, tho arguably it would be easier to write the simple version first. oh well.

**Comment by zeffii** [comment]
will push to master soon.

**Comment by ly29** [comment]
Since it is background library it can developed inside of master, agreed.

**Comment by zeffii** [comment]
well, circle kind of works..
![image](https://cloud.githubusercontent.com/assets/619340/18288622/8758ded6-747c-11e6-816f-e51d053fccec.png)

maybe this is too heavy, i'm not even sure i'll use it! Perhaps a geom_light (unvectorized) is advisable..

```python
import sverchok

from sverchok.utils.geom import circle
from sverchok.utils.geom import N
 

def sv_main(radii=[[]], phase=[[]], verts=[[]]):
    verts_out = []
    edges_out = []
    poly_out = []

    in_sockets = [
        ['s', 'radii', radii],
        ['s', 'phase', phase],
        ['s', 'verts', verts]
    ]

    out_sockets = [
        ['v', 'verts', verts_out],
        ['s', 'edges', edges_out],
        ['s', 'poly', poly_out]        
    ]

    work = False
    if radii and radii[0]:
        if phase and phase[0]:
            if verts and verts[0]:
                work = True
    if work:
        print(radii)
        print(phase)
        print(verts)
        try:                
            v, e, p = circle(
                radius=radii[0][0], 
                phase=phase[0][0], 
                verts=verts[0][0], 
                matrix=[N,N,N,N],
                merge=True)
            verts_out.append(v)
            edges_out.append(e)
            poly_out.append(p)
        except:
            print('huh')
            raise

    return in_sockets, out_sockets

```

**Comment by zeffii** [comment]
a 'meets_condition_to_process' function , was a nice feature of portnov's wrapper.

**Comment by ly29** [comment]
Do we have any node using it?

**Comment by zeffii** [comment]
nope: https://github.com/nortikin/sverchok/search?utf8=%E2%9C%93&q=with_bmesh

**Comment by ly29** [comment]
Decorators still takes some time getting my head around, but will take a look. 
But in general there no need to check if data exists, just try get it if it is needed. It will crash nicely in that case

**Comment by zeffii** [comment]
yeah, that decorator was not written in a few minutes :)

**Comment by ly29** [comment]
The ```geom``` module could be auto exposed to node scripts I think so you can just start using it. like 

```python
my_circle = geom.circle(options...)
```

**Comment by zeffii** [comment]
yeah injecting into the locals of the nodefunc makes a lot of sense. 

wondering if my current implementation of geom.py is a bit much...as it does full vectorization (practically), but it's a choice to make..  or offer both

- `pydata = geom.circle(param1, param2, param3)` : lightweight 
- `bm or np or pydata = geom.circle2(vectorized inputs)` : currently implemented like a tank...

**Comment by zeffii** [comment]
I'm appending a `2` to the heavy functions, and making lighter single call functions in https://github.com/nortikin/sverchok/tree/geom_featherlight  no ETA, maybe tonight.

**Comment by ly29** [comment]
The lighter things take priority.

**Comment by zeffii** [comment]
ha i ditched the heavy stuff for now.

**Comment by zeffii** [comment]
ok showing SN1 usage of geom.circle , notice the use of match_long repeat, what a pain :)

```python
from sverchok.data_structure import match_long_repeat
from sverchok.utils.geom import circle

def sv_main(nverts=3, phase=0.0, radius=0.3):
    verts_out = []
    edges_out = []

    in_sockets = [
        ['s', 'nverts', nverts],
        ['s', 'phase', phase],
        ['s', 'radius', radius]
    ]

    if isinstance(nverts, (float, int)):
        nverts = [nverts]
    if isinstance(phase, (float, int)):
        phase = [phase]
    if isinstance(radius, (float, int)):
        radius = [radius]

    values = match_long_repeat([nverts, phase, radius])
    print(values)
    _v, _e = [], []

    for n, p, r in zip(*values):

        Verts, Edges, Faces = circle(radius=r, phase=p, nverts=n)
        _v.append(Verts)
        _e.append(Edges)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

![image](https://cloud.githubusercontent.com/assets/619340/18353809/bf9c4626-75e3-11e6-9b85-6134cb6fee79.png)

![image](https://cloud.githubusercontent.com/assets/619340/18353936/20db4068-75e4-11e6-98d4-0e74713fcc97.png)

![image](https://cloud.githubusercontent.com/assets/619340/18354016/673368c4-75e4-11e6-8b5d-e31e7cbf569b.png)

and docstring

```python
>>> from sverchok.utils.geom import circle
>>> help(circle)
Help on function circle in module sverchok.utils.geom:

circle(radius=1.0, phase=0, nverts=20, matrix=None, mode='pydata')
    parameters:
        radius: float
        phase:  where to start the unit circle
        nverts: number of verts of the circle
        matrix: transformation matrix
        mode:   'np' or 'pydata'
    
        :  'pydata'
        usage:
            Verts, Edges, Faces = circle(nverts=20, radius=1.6, mode='pydata')
        info:
            Each return type will be a nested list.
            Verts: will generate [[x0,y0,z0],[x1,y1,z1], ....[xN,yN,zN]]
            Edges: will generate [[a,yb],[b,c], ....[n,a]]
            Faces: a single wrapped polygon around the bounds of the shape
    
        :  'np'
        usage:
            Verts, Edges, Faces = circle(nverts=20, radius=1.6, mode='np')
        info:
            Each return type will be a numpy array
            Verts: generates [n*4] - Array([[x0,y0,z0,w0],[x1,y1,z1,w1], ....[xN,yN,zN,wN]])
            Edges: will be a [n*2] - Array([[a,yb],[b,c], ....[n,a]])
            Faces: a single wrapped polygon around the bounds of the shape
      
            to convert to pydata please consult the numpy manual.


>>> 
```

**Comment by ly29** [comment]
```match_long_repeat``` is good to use but ugly inside, Some of the very old code I wrote...

Cutting up ```data_structure``` into smaller pices would be good also

**Comment by ly29** [comment]
With such nice docstrings we should be able to auto generate documentation no?

**Comment by ly29** [comment]
For simple things like this we could easily write a ```@vectorize``` decorator...

Like below totally untested... Should use ```functools.wraps```
```python
def vectorize(func):
     def inner(*args):
           out = [[] for i in range(len(args))]:
            values = match_long_repeat(args)
             for param in zip(*values):
                   res = func(*param)
                   for idx, r in enumerate(res):
                        out[i].append(r)
             return out
    return inner
```

**Comment by zeffii** [comment]
regarding docstring to docs, that is afterall the purpose of docstring (iinm). The geom module could generate its docs on the fly.

yes to a vectorize decorator (using yield if possible), else one will always have to write this bloviated list matching

**Comment by ly29** [comment]
We should make our standard library of functions and write doc strings for them. Also things like ```match_repeat_long``` and all hidden wisdom inside of data structure...
Some horribly obsolete.

**Comment by enzyme69** [comment]
​I also like where this Script thing going :) Cool addition to Sverchok.

**Comment by ly29** [comment]
```python
>>> pprint(list(circle([1,2,3],[0], [4,5])))
[([(0.0, 1.0, 0),
   (1.0, 6.123233995736766e-17, 0),
   (1.2246467991473532e-16, -1.0, 0),
   (-1.0, -1.8369701987210297e-16, 0)],
  [[0, 1], [1, 2], [2, 3], [3, 0]],
  [[0, 1, 2, 3, 0]]),
 ([(0.0, 2.0, 0),
   (1.902113032590307, 0.6180339887498949, 0),
   (1.1755705045849465, -1.6180339887498947, 0),
   (-1.175570504584946, -1.618033988749895, 0),
   (-1.9021130325903073, 0.6180339887498945, 0)],
  [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0]],
  [[0, 1, 2, 3, 4, 0]]),
 ([(0.0, 3.0, 0),
   (2.8531695488854605, 0.9270509831248424, 0),
   (1.7633557568774196, -2.427050983124842, 0),
   (-1.7633557568774192, -2.4270509831248424, 0),
   (-2.853169548885461, 0.9270509831248417, 0)],
  [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0]],
  [[0, 1, 2, 3, 4, 0]])]

```

**Comment by ly29** [comment]
@zeffii 
I pushed it to master even in it current form since we are testing now

**Comment by ly29** [comment]
Some more cleverness in the decorator would be nice, needs some more thinking about how it should work.

**Comment by zeffii** [comment]
This is fine.

I was pondering last-minute vectorization, so as to be able to define certain params of the decoration
```     
output = utils.vectorize(circle, par=params, dec=*decorator_params)
```
downside is that requires knowledge of the abstraction, upside is that people are introduced in a lite form to the concerns of vectorization..

**Comment by ly29** [comment]
Well if you want to pass parameters to the decorators, say ```match=geom.CYCLE``` we could always make the decorator use that. The decorator could modify the doc string also and insert it there... :)

**Comment by ly29** [comment]
What is really good about the decorator is whatever behavior we decide to use it will be exactly the same for all functions, a really clear separation of logic.

**Comment by zeffii** [comment]
but: 
```python
from sverchok.utils.geom import circle
import pprint
pprint.pprint(list(circle(radius=[1,2,3],phase=[0], nverts=[4,5])))
```
```text
Traceback (most recent call last):
  File "\Text", line 3, in <module>
TypeError: inner() got an unexpected keyword argument 'radius'
```
and i want to be able to pass keywords..

**Comment by ly29** [comment]
Yeah, it needs to be reworked to handle keywords also. 
Also ```radius=5, phase=range(10), nverts=[10,8]``` could be supported.

**Comment by zeffii** [comment]
yeah accepting a generator too, indeed. 

there has to be a point where the more we do to make stuff magically work in the most scenarios that we can conceive, the more bloated it's going to get.

maybe brittle.. but that's the nature blind decorating :/ 

``python
def vectorize(func):
    '''
    Will create a yeilding vectorized generator of the
    function it is applied to.
    Note: arguments must be list or similar type
    '''
    @wraps(func)
    def inner(**kwargs):
        names, values = kwargs.keys(), kwargs.values()
        values = match_long_repeat(values)
        multiplex = {k:v for k, v in zip(names, values)}
        for i in range(len(values[0])):
            single_kwargs = {k:v[i] for k, v in multiplex.items()}
            yield func(**single_kwargs)
    return inner
```

**Comment by zeffii** [comment]
with these decorators the sn1 snippet still needs to make its input iterable, tho perhaps that's alleviated in mk3..

```python
from sverchok.data_structure import match_long_repeat
from sverchok.utils.geom import circle

def sv_main(nverts=3, phase=0.0, radius=0.3):
    verts_out = []
    edges_out = []

    in_sockets = [
        ['s', 'nverts', nverts],
        ['s', 'phase', phase],
        ['s', 'radius', radius]
    ]

    if isinstance(nverts, (float, int)):
        nverts = [nverts]
    if isinstance(phase, (float, int)):
        phase = [phase]
    if isinstance(radius, (float, int)):
        radius = [radius]


    _v, _e = [], []

    for v, e, p in circle(radius=radius, phase=phase, nverts=nverts):
        _v.append(v)
        _e.append(e)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

**Comment by ly29** [comment]
Well the only time it gets called with ordinary numbers is when it is tested during init, otherwise it will get a standard wrapped list.

**Comment by zeffii** [comment]
yeah imho one of sn1's biggest failures.

**Comment by zeffii** [comment]
i feel there should be a way to get the undecorated functions too, maybe `_circle`  ?

**Comment by ly29** [comment]
It deserves some thinking but ```_circle``` is not a good name, rather have some prefix on the vectorized version
The most subtle would be.
```circle```
```circles```

**Comment by zeffii** [comment]
ohh.. i like `circles` for vectorized.. _that_ makes complete sense.

![image](https://cloud.githubusercontent.com/assets/619340/18382245/663dc850-7680-11e6-88db-fb642e6041ee.png)

```python
from sverchok.data_structure import match_long_repeat
from sverchok.utils.geom import circle

def sn1_autowrap(*params):
    for p in params:
        if isinstance(p, (float, int)):
            p = [p]
        yield p
            

def sv_main(nverts=3, phase=0.0, radius=0.3):
    verts_out = []
    edges_out = []

    in_sockets = [
        ['s', 'nverts', nverts],
        ['s', 'phase', phase],
        ['s', 'radius', radius]
    ]

    nverts, phase, radius = sn1_autowrap(nverts, phase, radius)

    _v, _e = [], []

    for v, e, p in circle(radius=radius, phase=phase, nverts=nverts):
        _v.append(v)
        _e.append(e)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
any objections to the alterations to the wrapper? it's making some assumptions..

**Comment by zeffii** [comment]
added a small temporary function to geom, now this is a bit more convenient to write the geom primitives
```python
from sverchok.data_structure import match_long_repeat
from sverchok.utils.geom import circle
from sverchok.utils.geom import sn1_autowrap


def sv_main(nverts=3, phase=0.0, radius=0.3):
    verts_out = []
    edges_out = []

    in_sockets = [
        ['s', 'nverts', nverts],
        ['s', 'phase', phase],
        ['s', 'radius', radius]
    ]

    nverts, phase, radius = sn1_autowrap(nverts, phase, radius)

    _v, _e = [], []

    for v, e, p in circle(radius=radius, phase=phase, nverts=nverts):
        _v.append(v)
        _e.append(e)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

**Comment by ly29** [comment]
I don't think keyword names should be required but handling both is maybe more tricky. Change away! It is 5 min piece of code meant as starting point

**Comment by zeffii** [comment]
i _do_ think kw names should be required. it's the Blender standard now.

**Comment by zeffii** [comment]
we can expose more forms of the circle functions.

**Comment by ly29** [comment]
In the bmesh library for example I consider bad form, for properties it makes sense.
In ```bmesh.ops``` a function has two arguments and both have to be present but one is a keyword argument...

I think we should use keyword arguments in functions and encourage their use, but allow calling them without the keyword per standard python

**Comment by ly29** [comment]
Also, unless we actively break it, calling the ```circle``` works with positional arguments, but ```circles``` won't. I will do a solution for

**Comment by zeffii** [comment]
i am sympathetic to both the argument for positional and kw only.. the big benefit of kw is that they act as a self documenting feature of the function _call_.

**Comment by ly29** [comment]
I consider it good form to use them, I really like it in Swift for example, it might be verbose but it becomes clear, but for scripting library to break expectations from standard python is kind of bad

**Comment by zeffii** [comment]
but then i read this

```python
for verts, edges, _  in circles(range(1,4)):
    do_suff
```

and interpret that it could mean 
```python
circles(1,2,3)
```

**Comment by ly29** [comment]
I don't consider it good form, but it should still work.

**Comment by zeffii** [comment]
as you say, the non wrapped `circle` function will still work

**Comment by zeffii** [comment]
as long as we make it clear in documentation what the options and possibilities and consequences are, it will be internally consistent and that's the best kind of consistent.

**Comment by zeffii** [comment]
"Practicality beats purity"

**Comment by ly29** [comment]
Which is very python..

**Comment by zeffii** [comment]
btw, you read about py3.6 dropping ordered dict, in favour of making it ordered by default ? :)

**Comment by ly29** [comment]
It makes so much sense but once you get used the world outside of python will come as a shock. I have somewhat mixed feelings about.
But for ```kwargs``` a million times yes.

**Comment by zeffii** [comment]
meet arc(s)

![image](https://cloud.githubusercontent.com/assets/619340/18389307/a8e7b4a2-76a5-11e6-8a3c-d2dd6f6cb06f.png)

**Comment by ly29** [comment]
Looks nice

**Comment by ly29** [comment]
Try this below, it seems to work for me with both keywords and mixing and matching int and list arguments. I won't push since you work in the branch
```python
def vectorize(func):
    '''
    Will create a yeilding vectorized generator of the
    function it is applied to.
    Note: arguments must be list or similar OR str, float or int
    '''
    def wrap_param(p):
        if isinstance(p, (float, int, str)):
            return [p]
        else:
            return p
    @wraps(func)
    def inner(*args, **kwargs):
        split = len(args)
        keys = kwargs.keys()
        parameters = [wrap_param(p) for p in args + tuple(kwargs.values())]
        for param in zip(*match_long_repeat(parameters)):
            kw_args = {k: v for k, v in zip(keys, param[split:])}
            yield func(*param[:split+1], **kw_args)
    return inner
```

Now we only need ```sv_zip_longest``` and we could support iterables also

**Comment by ly29** [comment]
```python
>>> pprint(list(circles(1, nverts=[3,4])))
[([(0.1411200080598672, -0.9899924966004454, 0),
   (-0.9279186556418991, 0.3727827363381124, 0),
   (0.7867986475820313, 0.6172097602623329, 0)],
  [[0, 1], [1, 2], [2, 0]],
  [[0, 1, 2, 0]]),
 ([(-0.7568024953079282, -0.6536436208636119, 0),
   (-0.6536436208636119, 0.7568024953079282, 0),
   (0.7568024953079282, 0.653643620863612, 0),
   (0.653643620863612, -0.7568024953079282, 0)],
  [[0, 1], [1, 2], [2, 3], [3, 0]],
  [[0, 1, 2, 3, 0]])]
```

Also the polygon output looks bad.
```
[[0, 1, 2, 3, 0]]
```
Note the extra 0 at the end.

**Comment by zeffii** [comment]
yeah the extra 0 is gone now. nice job on the decorator.

was about to add a parameter to the vectorized form, 'merge=False` (mesh join of output) ,

**Comment by zeffii** [comment]
wondering can't we do 
```python
        #parameters = [wrap_param(p) for p in args + tuple(kwargs.values())]
         parameters = (wrap_param(p) for p in args + tuple(kwargs.values()))
```

**Comment by zeffii** [comment]
am reverting the vectorized decorator temporarily,  with the above sn1 snippet.. I didn't dig very deep
```python
    function_output = node_function(*params)
  File "<string>", line 19, in sv_main
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\utils\geom.py", line 74, in inner
    yield func(*param[:split+1], **kw_args)
TypeError: arc() got multiple values for argument 'radius'
```

i just want to write the geom functions

**Comment by ly29** [comment]
Yeah focus on that, will give it another shot and test more

**Comment by zeffii** [comment]
just realized, what if the Int Range nodes outputted repeating values if the step was 0

**Comment by ly29** [comment]
Makes sense I guess

**Comment by zeffii** [comment]
meet (rounded) quad:

![image](https://cloud.githubusercontent.com/assets/619340/18410490/dbda60a2-7764-11e6-8a97-1bd21d1deed2.png)

```python
from sverchok.utils.geom import quads, sn1_autowrap


def sv_main(side=1.0, radius=0.0, nverts=5):

    verts_out = []
    edges_out = []
    
    in_sockets = [
        ['s', 'side', side],
        ['s', 'radius', radius],
        ['s', 'nverts', nverts]
    ]    

    _v, _e = [], []
    radius, side, nverts = sn1_autowrap(radius, side, nverts) 
    for v, e, p in quads(radius=radius, side=side, nverts=nverts):
        _v.append(v)
        _e.append(e)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
next up `Slice`
slice is a bit more niche, but it's essential a 2d torus with inner and outer radii.

**Comment by ly29** [comment]
Nice progress

**Comment by zeffii** [comment]
@ly29 i was pondering making each primitive in its own file, it's going to get rather large..

**Comment by ly29** [comment]
Now I have updated the ```vectorize``` function above to work, a ```+1``` was wrong. Now it should work nicely I think.

If you to want spread them it out we certainly can, but I think having them all namespace makes sense. 

Also made a third implementation of ```sv_zip_longest``` so we can support range like functionality...

**Comment by zeffii** [comment]
i was thinking of having 

 utils/geom_internals/__init__.py
 utils/geom_internals/circle.py
 utils/geom.py

and inside geom.py something like

```python
from . geom_internals import circle, circles
```

so scripts just need to (when injected into namespace as we talked about)
```python
from geom import circle, circles
```

**Comment by zeffii** [comment]
but there is no rush with this. i want to keep cracking on the functions..

**Comment by zeffii** [comment]
meet `arc_slice(s)`   (slice is a python kw, avoiding the reuse)

```python
from sverchok.data_structure import match_long_repeat
from sverchok.utils.geom import arc_slices, PI

def sn1_autowrap(*params):
    for p in params:
        if isinstance(p, (float, int)):
            p = [p]
        yield p


def sv_main(outer_radius=1.0, inner_radius=0.8, phase=0, angle=PI, nverts=20):

    in_sockets = [
        ['s', 'outer_radius', outer_radius],
        ['s', 'inner_radius', inner_radius],
        ['s', 'phase', phase],
        ['s', 'angle', angle],
        ['s', 'nverts', nverts]]    
    
    my_args = (outer_radius, inner_radius, phase, angle, nverts)
    outer_radius, inner_radius, phase, angle, nverts = sn1_autowrap(*my_args)

    _v, _e, _f = [], [], []

    for v, e, p in arc_slices(
        inner_radius=inner_radius, 
        outer_radius=outer_radius,
        phase=phase,
        angle=angle,
        nverts=nverts):
            
        _v.append(v)
        _e.append(e)
        _f.append(p)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e],
        ['s', 'faces', _f]        
    ]

    return in_sockets, out_sockets


```

![image](https://cloud.githubusercontent.com/assets/619340/18412812/93fc3650-7798-11e6-9e68-8fc7a64467b5.png)

**Comment by zeffii** [comment]
spiral stairs using _arc_slices_

![image](https://cloud.githubusercontent.com/assets/619340/18413199/2af0e580-77a1-11e6-897c-f52fc0d97e43.png)

**Comment by zeffii** [comment]
### rect, rects  (also rounded)
meet rect

![image](https://cloud.githubusercontent.com/assets/619340/18416551/cc3adff6-7817-11e6-9f5c-6ec23da7a0be.png)

```python
from sverchok.utils.geom import rects, sn1_autowrap, sn1_autodict

def sv_main(dim_x=1.0, dim_y=1.62, radius=0.0, nverts=5):

    in_sockets = [
        ['s', 'dim_x', dim_x],
        ['s', 'dim_y', dim_y],
        ['s', 'radius', radius],
        ['s', 'nverts', nverts]
    ]
    
    my_args = (dim_x, dim_y, radius, nverts)
    dim_x, dim_y, radius, nverts = sn1_autowrap(*my_args)

    params = sn1_autodict('dim_x dim_y radius nverts', vars())

    _v, _e, _f = [], [], []
    for v, e, p in rects(**params):
        _v.append(v)
        _e.append(e)
        _f.append(p)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e],
        ['s', 'faces', _f]        
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
shock obsorber 
![image](https://cloud.githubusercontent.com/assets/619340/18416624/b81c021e-7819-11e6-82e4-22fe92ba337d.png)

**Comment by zeffii** [comment]
meet **line(s)**

relatively fast, may only make sense in combination with merge and remove doubles.

![image](https://cloud.githubusercontent.com/assets/619340/18418472/723af2cc-7847-11e6-9ecf-7536912c1fe0.png)

```python
from sverchok.utils.geom import lines, sn1_autowrap


def sv_main(p1=[(0,0,0)], p2=[(1,0,0)], nverts=2):

    in_sockets = [
        ['s', 'p1', p1],
        ['s', 'p2', p2],
        ['s', 'nverts', nverts]]

    p1, p2, nverts = sn1_autowrap(p1, p2, nverts)

    _v, _e = [], []

    for v, e in lines(p1=p1, p2=p2, nverts=nverts):

        _v.append(v)
        _e.append(e)

    out_sockets = [
        ['v', 'verts', _v],
        ['s', 'edges', _e]
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
line is definitely not final.. am considering letting it accept

    p1=(x,y,z), p2=(x,y,z,), nverts=2
    p1=[(x,yz)], p2=[(x,y,z,)], nverts=2
    p1=[(x,yz)], p2=[(x,y,z,)], nverts=[2]

with a little bit of introspection, and assuming that it gets enough values, else it could do a light weight match long repeat internally.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/18436135/f83747f4-78f6-11e6-905e-c335dcb03e5c.png)

not sure how best to implement the params...

**Comment by zeffii** [comment]
perhaps `line(p1=(x,y,z), p2=(x,y,z), nverts=2)` is the better user facing approach, it is consistent with the others, but my issue with it is that often the user will want to merge meshes, and that's perhaps a waste of processing which could be done in the line function in one go.

but i'm totally OK with restricting it to 
```python
    line(p1=(x,y,z), p2=(x,y,z), nverts=2)
    lines(p1=[(x,y,z), ...n)], p2=[(x,y,z), ...n)], nverts=[2, ...n)])
```

assuming the vectorized decorator will take an extra `merge=True` parameter to merge all generated data like `mesh_join`.

**Comment by zeffii** [comment]
regarding the eventual vectorize decorator..  wonder if something like this is possible.. don't know how to add the merge argument to the decorator tho. (haven't tried)

```python
def vectorize(func):
    '''
    Will create a yeilding vectorized generator of the
    function it is applied to.
    Note: arguments must be list or similar OR str, float or int
    '''
    def wrap_param(p):
        if isinstance(p, (float, int, str)):
            return [p]
        else:
            return p

    @wraps(func)
    def inner(*args, **kwargs):
        split = len(args)
        keys = kwargs.keys()
        parameters = [wrap_param(p) for p in args + tuple(kwargs.values())]

        if not merge:
            for param in zip(*match_long_repeat(parameters)):
                kw_args = {k: v for k, v in zip(keys, param[split:])}
                yield func(*param[:split], **kw_args)

        else:
            total_geom = [[],[],[]]
            for param in zip(*match_long_repeat(parameters)):
                kw_args = {k: v for k, v in zip(keys, param[split:])}
                geom = func(*param[:split], **kw_args)
                for i in range(len(geom))
                    total_geom[i].append(geom[i])
            yield mesh_join(total_geom)

    return inner
```

**Comment by ly29** [comment]
One can do that, just pop the arguments specific to the wrapper from the ```kwargs``` before doing the rest.

**Comment by ly29** [comment]
Could also have option to cycle arguments instead of just match long

**Comment by ly29** [comment]
Another issue with updated wrapper is that shouldn't set the function name any longer in the way we do using wraps.

**Comment by nortikin** [comment]
Congratulations, world's programmer day!

**Comment by nortikin** [comment]
Great sn3 by the way. Wonderfull

**Comment by zeffii** [comment]
meet grid(s)

![gifgrid](https://cloud.githubusercontent.com/assets/619340/18469168/66299f72-79a7-11e6-838c-fe8e2f1f664a.gif)

```python
from sverchok.utils.geom import grids, sn1_autowrap


def sv_main(dim_x=1.0, dim_y=1.62, nx=2, ny=2, anchor=0):

    in_sockets = [
        ['s', 'dim_x', dim_x],
        ['s', 'dim_y', dim_y],
        ['s', 'nx', nx],
        ['s', 'ny', ny],
        ['s', 'anchor', anchor]]

    dim_x, dim_y, nx, ny, anchor = sn1_autowrap(dim_x, dim_y, nx, ny, anchor)

    _v, _e, _f = [], [], []
    for geom in grids(dim_x=dim_x, dim_y=dim_y, nx=nx, ny=ny, anchor=anchor):
        _v.append(geom[0])
        _e.append(geom[1])
        _f.append(geom[2])

    out_sockets = [['v', 'verts', _v], ['s', 'faces', _f]]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
next step is to include matrix ops / transforms. I think i'll not do the 3d functions yet.

**Comment by ly29** [comment]
Included spline and linear spline as classes reflecting their nature as heavy to create, cheap to evaluate.
A convenience function doing the following could be done
```python
def spline_and_eval(locs, t_values):
     spl = CubicSpline(locs)
     return spl.eval(t_values)
```

Todo for Splines:
- better doc strings
- think about interface
- allow non numpy inputs and create them as needed

**Comment by zeffii** [comment]
lovely stuff! perhaps a class for `polylines` too, for the same reasons. and with the explicit purpose of making it easy to generate many disjoint edge chains (closed or not).

**Comment by ly29** [comment]
Yeah I think it is a good idea

**Comment by enzyme69** [comment]
So is it a good time for me to test any of this Script 3? Is there template
and example?

**Comment by ly29** [comment]
Sadly not yet, soon.

**Comment by ly29** [comment]
The geom functions above works with sn1 as well however

**Comment by zeffii** [comment]
I may test with hand multiplying.. instead of converting to Vector and Matrix for M*V
```python
def multiply_vectors(M, vlist):
    new_vecs = list(range(len(vlist)))  # first make list of len vlist.

    for i, v in enumerate(vlist):
        add_vec[i] = (None, None, None)
        add_vec[i][0] = M[0][0]*v[0] + M[0][1]*v[1] + M[0][2]*v[2]
        add_vec[i][1] = M[1][0]*v[0] + M[1][1]*v[1] + M[1][2]*v[2]
        add_vec[i][2] = M[2][0]*v[0] + M[2][1]*v[1] + M[2][2]*v[2]

    return new_vecs

```

**Comment by zeffii** [comment]
or possibly don't use the new_vecs templist and update the vlist in place ..

**Comment by zeffii** [comment]
not entirely sure if there's a speed gain to be had by making verts using tuples..(as currently the case)

**Comment by nortikin** [comment]
sn1, i see

**Comment by ly29** [comment]
Don't overthink it now.

**Comment by zeffii** [comment]
4*4 matrix for vec3
```python
def multiply_vectors(M, vlist):

    for i, v in enumerate(vlist):
        vlist[i] = (
            M[0][0]*v[0] + M[0][1]*v[1] + M[0][2]*v[2] + M[0][3]* 1.0,
            M[1][0]*v[0] + M[1][1]*v[1] + M[1][2]*v[2] + M[1][3]* 1.0, 
            M[2][0]*v[0] + M[2][1]*v[1] + M[2][2]*v[2] + M[2][3]* 1.0
        )

    return vlist
```
