### ISSUE TITLE
Script Node 3 - issues before stable

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#856]
As concrete list for introduction of SN3, for starting discussion see #839 
- [x] reload / reset
- [x] survive F8...
- [x] reload on startup 
- [x] Operator support, practically there
- [ ] UI Fixes
- [ ] reload from text editor
- [ ] custom socket values
- [ ] Changing signature
- [ ] Changing name

--- Master but beta
- [ ] Documentation
- [ ] Templates for possibilities
- [ ] SN1 Loader
- [ ] Testing

--- Stable and out of beta

**Comment by ly29** [comment]
Reading through SN1 for how deal with changing sockets. Hmm. Complicated and subtle stuff going on...

**Comment by zeffii** [comment]
i maybe have over-engineered the _link-store-restore_ code, written before appreciating the brilliance of `getattr, setattr`. If I had to redo that I would do it similar to the corresponding parts of the hotswap function https://github.com/nortikin/sverchok/blob/bfa4d1d528c3d90d38da81f1dc419e7060e73709/utils/sv_nodeview_operators.py#L40-L82

**Comment by ly29** [comment]
Will have a look at that

**Comment by zeffii** [comment]
i forgot how subtle some of the _link-store-restore_ was, but undoubtedly you'll find a more elegant and obvious way.

downside to that hotswop is that it works only by socket.index , so changing the socket order (while it doesn't happen a lot, it does happen..). 

Are you forcing socket.name uniqueness? it has obvious benefits..

**Comment by ly29** [comment]
I has obvious advantages but I am not forcing it.

There are limits to what is possible to handle with signature changes.
A input has the following attributes to keep track of:
- parameter name, the python parameter name
- the socket name
- the position
- the socket type/ type
A output has the following attributes to keep track
- socket name
- socket type / type
- position

If think renaming and reordering are valid things to keep track of. For socket changes it is different, but for example switching from ```Int``` to ```uInt``` would be reasonable to support also.
There is no total solution possible to all variations of the problem, sometime it will just fail and produce a new node without all the links preserved.

```python
old_signature = ...
new_signature = ...

do_position_change(old..., new...)
do_type_changes(old_signature, new_signature)
do_name_change(old..., new...)
```

**Comment by ly29** [comment]
After being distracted I will try go get this done

**Comment by zeffii** [comment]
using the version master, about return types.
` -> ((Vertex("Verts"))`:  and ` -> Vertex("Verts"):`  both throw a message 'Vertex is not an iterable', 

so ` -> ((Vertex("Verts"), ):`
does give me:

![image](https://cloud.githubusercontent.com/assets/619340/18352507/efe88f1a-75de-11e6-80fe-b35ad04d0e3a.png)

**Comment by ly29** [comment]
Yeah, it will also give an error if you return a single value. That are some of the issues you will face, it might, kind of, work but there are a lot of issues.

I do intend to support that but haven't gotten around to it.
The SN3 version is more advanced but still has many issues.

**Comment by ly29** [comment]
But I would be very happy if you do test and report what you run into and even happier of course if make it work... ;)

**Comment by zeffii** [comment]
ok. i think what i'll do is first write a few sn1 examples of the geom module, and when that's more feature complete (will take days, things are busy) then start doing sn3 recodes so people can check and compare new syntax.

**Comment by ly29** [comment]
that does make more sense, SN3 has many warts still

**Comment by zeffii** [comment]
the main thing i miss is reload from text editor. 

early days i get it :)

**Comment by ly29** [comment]
There is also the issue now that one text file directly corresponds with many nodes...

**Comment by ly29** [comment]
I would like to do a reload from my external editor but that comes way down the line...

**Comment by zeffii** [comment]
reloading from external texteditor, there's some good code snippets about similar stuff on BlenderSE.

**Comment by ly29** [comment]
So back on track with this...
