### ISSUE TITLE
2.77 and python 3.5

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#857]
It is inevitable that we will want to use some of the new python 3.5 features sooner or later, matrix multiplication for example. I didn't expect the first one to be a better/more powerful syntax for dictionary unpacking.

```python
# this works in 3.5
set_multiple_attrs(m, **socket_ref, direction=-1)
# have to be like this in 3.4
set_multiple_attrs(m, direction=-1, **socket_ref)
```
This example certainly is trivial to fix, but is worth it and to keep checking against the old 2.76 version of blender? As blender moves forward, so must we I think.

The last version before monads were introduced will continue to work as it did for more or less two years.

http://www.blendernation.com/2016/02/26/blender-2-77-will-drop-support-for-windows-xp/
https://docs.python.org/3/whatsnew/3.5.html
https://www.python.org/dev/peps/pep-0448/
https://github.com/nortikin/sverchok/commit/c86190f96bf659deb6c0de3bf52cdfdf3c8cf665#commitcomment-18894467

**Comment by zeffii** [comment]
that's weird that set_multiple_attrs should behave differently, it just a normal 
```python
   def function_name, (non-keyword, keywords, **kwargs):
      ...
```
style function..

3.5 's new literal string formatting will be used in a lot of places by the UI so I reckon we make a move to go b2.77+ and py3.5 exclusively.

**Comment by ly29** [comment]
It is new feature allowing more powerful ```*``` un packing, see [PEP-448](https://www.python.org/dev/peps/pep-0448/)

The new string interpolation will be in python 3.6. [PEP-498](https://www.python.org/dev/peps/pep-0498/)

**Comment by ly29** [comment]
```python
 kwargs = {str(i):j for i, j in zip(range(10), range(10, 20))}

def f(**kwargs):
    print(kwargs)

# in python 3.5 this works
f(f(**kwargs, key=10)

# in python 3.4
    f(**kwargs, key=10)
         ^
SyntaxError: invalid syntax

# But the following works in both.
f(key=10,**kwargs)
```

**Comment by zeffii** [comment]
pep-498! i see (got mixed up). looks much like ruby. lovely! 

keep the one  that works on both for now.. we can send out a message to users that soon we plan to drop 3.4 support

**Comment by ly29** [comment]
Made a fix, just changing the argument order. I won't test on 2.76 right now but @nortikin perhaps can evaluate if it works. It certainly _should_.

**Comment by zeffii** [comment]
I think I watched a pycon vid / read a blog about the new unpacking rules.. didn't think about it's effect on 3.4 users. For base functionality noone needs to install python anymore, and for more complex pip-installs into blender's python.. yeah, that's tricky.

**Comment by zeffii** [comment]
new 2.78 builds are out . may have to try soon :)

**Comment by ly29** [comment]
This issue will keep cropping up I guess but closing for now...

2.78, oh yeah.

**Comment by nortikin** [comment]
Because used my gf's laptop with old blender ))

**Comment by ly29** [comment]
@nortikin 
It should work on 3.4 again. I don't think we use any other 3.5 features at the moment.
