### ISSUE TITLE
Script Node 3 Syntax And Examples (In Progress)

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#858]
# Rationale

Why Script Node 3? Script node 1, the original, is and has been great, allowing us to easily express or ideas and turn them into proper nodes or just keep them as experiments with all the boilerplate needed for writing a full node. However by writing more code with and doing more regular nodes with it some frustration kept coming up. Some recent experiments of ours with monads and redux experience opened our eyes up to other ways of doing things allowing things that just weren't possible in good way earlier. One such problem with the old script node was the need to declare and return both inputs and outputs to be able to figure out function/node signature (which inputs and outputs it has). Another issue that is was impossible to declare your one draw function, create specialized custom properties and some other things making the old script much less powerful than the regular nodes. It turns out that these limitations can be overcome. For more see #839 
# Script 3

A script node 3, SN3, script uses a python feature called function annotations to declare the function signature, python annotations syntax is as follows:

``` python
def f(a : int, b: int) -> int:
     return a + b
# the same function without annotations
def g(a, b):
     return a + b
```

The python annotations aren't used by the standard python interpreter for anything except providing meta data information that can be used by a surrounding system/platform for metadata about the function.
To use SN3, Sverchok introduces a type system matching a series of new and old socket types to types. It is easiest if to just see this is in action.

``` python

import bpy
import numpy as np

"""
Sample an image at u,v coordinates, repeating the texture
Outputs image data at uv as rgb
"""

def draw(self, context, layout):
    layout.prop_search(self, "image_name", bpy.data, "images")

@node_script(draw_buttons=draw)
def sample_image(
        image_name: StringP(name="Image") = "",
        points: Vertex("Uv points") = None
        ) -> ( # below are output sockets
        Vertex("Colors"),
        Float("Alpha")):

    bpy_image = bpy.data.images[image_name]

    dim_x, dim_y = bpy_image.size
    image = np.array(bpy_image.pixels[:]).reshape(dim_y, dim_x, 4)

    out = []
    alpha = []
    points = np.array(points[0])
    uv = points * (dim_x, dim_y, 0)

    for u, v, _ in uv:
        color = image[v % dim_y, u % dim_x]
        out.append(color[:3].tolist())
        alpha.append(color[-1])

    return [out], [alpha]
```
## Types

Todo table with types and sockets
## Features

Syntax with examples.
## Some templates

A series of short scripts showing the new feature and concepts.
### Older Script Nodes

Script Node 1 is supported for now.
Script Node 2 will move from beta to deprecated. Any script will be ported over to the new syntax on request.

**Comment by zeffii** [comment]
help me load this, so i can get cracking on the other primitives..not using sn1

```python
import bpy
# from sverchok.utils.geom import circle

@node_script
def acircle(
    nverts: Int = 3,
    radius: Float = 1.0,
    phase: Float = 0.0        
) -> (
    Vertex("Verts"),
    Edge("Edges")
):

    # function here
    # Verts, Edges, Faces = circle(radius=radius, phase=phase, nverts=nverts)
    return Verts, Edges
```
all i get is: https://gist.github.com/zeffii/72d025f3e60dab7a5285cd908865579d

**Comment by ly29** [comment]
For some reason the Finder/Loader doesn't trigger, if it is in SN3 branch it is very strange.

For debugging you can try
```python
from sverchok.utils.loadscript import SvFinder
Import sys
sys.meta_path.append(SvFinder())
```
And try again
https://github.com/nortikin/sverchok/blob/scriptmk3/utils/loadscript.py#L330-L345

**Comment by ly29** [comment]
The version that lives but should be hidden in master doesn't load the finder

**Comment by zeffii** [comment]
yeah, that's making something happen. will read the source.

**Comment by ly29** [comment]
I will have a look tonight, but can answer questions and give pointers.
