### ISSUE TITLE
Caching images using Functools LRU cache

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#859]
Since getting the pixels from ```image.pixels``` is annoyingly slow in blender I looked into ways to either speed up access or to cache it. For speeding up access avoid copying a potentially large image there is the ```.as_pointer()``` interface meant for advanced script writes (which admittedy, I am starting to feel like sometimes). But it feels somewhat complex and I couldn't find any working examples of this being used in my somewhat quick search.
So caching felt like the best option. How to achieve this then?
Reading through the what is new python 3.5 I saw the ```@functools.lru_cache``` which I hadn't thought about.
https://docs.python.org/3/library/functools.html#functools.lru_cache

This allows the following way to be used

```python
@lru_cache(maxsize=2)
def get_image(name):
    bpy_image = bpy.data.images[name]
    dim_x, dim_y = bpy_image.size
    image = np.array(bpy_image.pixels[:], dtype=np.float32).reshape(dim_y, dim_x, 4)
    return image, dim_x, dim_y
```

Using this in my image sample script I wrote for SN3 I achieved the following speedup. From 0.3s to 0.08s for a small 640x692 pixels image.

```
# First call
Processed  sample_image in: 0.3224
# Second and later calls
Processed  sample_image in: 0.0756
```
For a bigger image: 3872, 2592.
```
Processed  sample_image in: 4.4682
Processed  sample_image in: 0.0416
```

Full script
```python
from functools import lru_cache
import numpy as np
import bpy

"""
Sample an image at u,v coordinates, repeatin the texture
Images can either be selected by name or int.
Outputs image data at uv as rgb
"""
@lru_cache(maxsize=2)
def get_image(name):
    bpy_image = bpy.data.images[name]
    dim_x, dim_y = bpy_image.size
    image = np.array(bpy_image.pixels[:], dtype=np.float32).reshape(dim_y, dim_x, 4)
    return image, dim_x, dim_y

def draw(self, context, layout):
    layout.prop_search(self, "image_name", bpy.data, "images")

@node_script(draw_buttons=draw)
def sample_image(
        image_name: StringP(name="Image") = "",
        points: Vertex("Uv points") = None
        ) -> (
        Vertex("Colors"),
        Float("Alpha")):

    image, dim_x, dim_y = get_image(image_name)

    out = []
    alpha = []
    points = np.array(points[0])
    uv = points * (dim_x, dim_y, 0)

    for u, v, _ in uv:
        color = image[v % dim_y, u % dim_x]
        out.append(color[:3].tolist())
        alpha.append(color[-1])

    return [out], [alpha]
```

**Comment by ly29** [comment]
There isn't much to discuss here really except thinking about proving a standard ```get_image``` function that can be used for a series of nodes

**Comment by zeffii** [comment]
i've seen some mention of `.as_pointer()` will try to find.

**Comment by ly29** [comment]
That would be even better, to access the built in image buffer in the blender kernel. Both fast and memory efficient. Right now this approach trades memory for speed.

**Comment by zeffii** [comment]
http://stackoverflow.com/questions/15172116/reading-datastructure-from-specific-memory-location-from-blender

**Comment by ly29** [comment]
So we would have to parse this I guess.
https://github.com/dfelinto/blender/blob/master/source/blender/makesdna/DNA_image_types.h#L99-L159

**Comment by zeffii** [comment]
something like this (Doesn't work yet)
```
import bpy
import ctypes
import numpy as np

def get_image(name):
    bpy_image = bpy.data.images[name]
    dim_x, dim_y = bpy_image.size
    array_length = dim_y * dim_x * 4
    address = bpy_image.as_pointer()
    image_array = np.ctypeslib.as_array((ctypes.c_float * array_length).from_address(address))
    
    return image_array, dim_x, dim_y

named = 'damascas.PNG'

print(get_image(named))
```

**Comment by ly29** [comment]
But pointer you get is to the Image struct, not to the actual buffer no?

**Comment by zeffii** [comment]
well, pixels doesn't have an `as_pointer()`.. and `pixels.data.as_point()` doesn't seem (tho i may be wrong) to be what we're looking for either.

**Comment by ly29** [comment]
There is the possibility of loading the image into GL as a texture

**Comment by ly29** [comment]
```pixels.data``` is just the image data block.

```python
>>> id(D.images['tele.png'].pixels.data)
4685577672

>>> id(D.images['tele.png'])
4685577672
```

**Comment by ly29** [comment]
A PIL version of get image.
```python
import bpy
import numpy as np
from PIL import Image

def get_image(name):
    img = Image.open(bpy.data.images[name].filepath)
    image = np.array(img)/np.array([255.0], dtype=np.float32)
    return image, image.shape[:2]
```

Vs ordinary above. Note that this even does the math to make it look like ordinary blender pixels format.
So opening the file as image and interpreting it, in this case largish jpeg, and converting into numpy and converting the data is significantly faster the accessing the already loaded image that is inside of blender memory. The ```.pixels``` interface is just not that good...
```python
6.55 s
39.39 s
```

**Comment by zeffii** [comment]
Yes! PIL :)
if users can install pillow..

**Comment by ly29** [comment]
If pip was part of blender life would be atleast 10x times better (when writing python scripts inside of blender)

**Comment by ly29** [comment]
Could even distribute blender add ons as pip with a custom archive backend, allowing independent releases of scripts and blender... 
One can dream.

**Comment by ly29** [comment]
Accessing the raw image inside of blender also seems hard, since to actually get the image buffer you have to query the blender kernel. I don't expect any progress on that front so closing for now.

**Comment by zeffii** [comment]
(not intending to reopen the issue)
```python
import sys

path_to_PIL = r'c:\users\zeffi\anaconda3\lib\site-packages'
sys.path.append(path_to_PIL)

import PIL
from PIL import Image

print(PIL.__file__)
```
or some variation thereof for windows anaconda users with 3.5 installed.

**Comment by ly29** [comment]
Nice thinking.

**Comment by zeffii** [comment]
a better try/except would be preferable.. if the import fails an `array_from_image` would use the slightly slower pixels but with lrucache

**Comment by zeffii** [comment]
can even add a print upon Sverchok start, when PIL fails, to suggest a link to the issue tracker / help page explaining ways to install PIL with the local Blender Python.

"If use use any of the above {nodes} you will get significant speedups by installing Python Image Library called Pil (also known as Pillow), follow the issue in this link `< ..... >` to get instructions on installation".

i dunno.. or maybe we just tell people who visit the issue tracker complaining about pixel read speed...
