### ISSUE TITLE
Edge graph to polygons

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#86]
![edges_to_polies](https://cloud.githubusercontent.com/assets/619340/2751527/70dc2db6-c8d5-11e3-9273-551980c0f25b.PNG)

I'm investigating this now, automatically iterate through edges to find Edge Cycles with which to construct polygons. I think it makes sense to have a `min=3 max=n` parameter for the input. Hopefully will find the right graph theory paper to read, else I implement my own.

Suggestions welcome.

**Comment by Durman** [comment]
It looks like not all holes are filled by this function. :/
https://gist.github.com/749b9604fc6361e93d313af3973123c8
![2018-02-20_09-00-11](https://user-images.githubusercontent.com/28003269/36408125-d055f05e-161c-11e8-899e-42745748c705.png)

**Comment by Durman** [comment]
There is interesting artical on this theme, unfortunately in Russian:
http://www.e-maxx-ru.1gb.ru/algo/facets

**Comment by zeffii** [comment]
yes, the nsides param doesn't expect many polygons in the incoming geometry, it works to a certain point, and then it will find polygons that you don't want - especially when nsides is larger than most of the easy to find polygons :).

i thought we had another fill holes... fill edgenet node..

**Comment by Durman** [comment]
I have got something.)) I can now calculate outer edges but yet not for all graphs. I think it is important step on the way to creating this algorithm.

![outer edges](https://user-images.githubusercontent.com/28003269/36577808-04584b24-1873-11e8-94c7-6584ada6d146.gif)

**Comment by Durman** [comment]
Little explanation about algorithm of searching outer edges:
![2018-02-24_18-26-15](https://user-images.githubusercontent.com/28003269/36631929-01322dda-1999-11e8-9e8a-64c8802953b8.png)

**Comment by Durman** [comment]
It looks like nearly working.

![fill edges](https://user-images.githubusercontent.com/28003269/36711598-a0fc42c8-1b9d-11e8-87c0-7bb52ceca692.gif)

**Comment by Durman** [comment]
![2018-02-27_10-53-00](https://user-images.githubusercontent.com/28003269/36714691-9fb8f0c8-1bac-11e8-962b-7688c8509fe9.png)

**Comment by Durman** [comment]
Plane with randomly deleted edges was filled with new algorithm.
![2018-03-01_12-47-54](https://user-images.githubusercontent.com/28003269/36835269-16629ca8-1d4f-11e8-88dc-20ad4a48e3ae.png)

**Comment by Durman** [comment]
I think I have finished. It's have to work for [planar graph](https://en.wikipedia.org/wiki/Planar_graph) only.
https://gist.github.com/ec6509d12b67c0907ebc1693edaf4c5b
![2018-03-02_12-59-15](https://user-images.githubusercontent.com/28003269/36891062-a3e2e554-1e19-11e8-9b2e-4b74552df957.png)

**Comment by zeffii** [comment]
@Durman  want to make a node from this? (else I will! :)

**Comment by zeffii** [comment]
"SvPlanarEdgenetToPolygons"

**Comment by Durman** [comment]
@zeffii Yes, I will make. 
I used copy of algorithm of `separate loose parts` node. Maybe it will be better to create function in this file `sverchok/utils/sv_mesh_utils.py` for this?

**Comment by nortikin** [comment]
i have this
``` bash
.config/blender/2.79/scripts/addons/sverchok/core/update_system.py", line 325, in do_update_general
    node.process()
  File "/planar_edgenet_to_polygons.py", line 364, in process
  File "/planar_edgenet_to_polygons.py", line 300, in get_filled_graph
  File "/planar_edgenet_to_polygons.py", line 222, in create_mask_used_edges
KeyError: (192, 192)
```

**Comment by Durman** [comment]
@nortikin 
Your mesh is not planar. Use `intersect edges` node before.
![2018-03-19_07-21-24](https://user-images.githubusercontent.com/28003269/37576490-287fdf9a-2b46-11e8-85b0-1bbe5f172dc9.png)
https://gist.github.com/e7d5ef9117c039403eca40d42b4f57e5

**Comment by portnov** [comment]
@Durman but better the node should throw human-readable exception: "Input mesh is not planar, please use IntersectEdges node before".

**Comment by Durman** [comment]
@portnov Certainly yes. I have not done it because I don't know how to make fast test for this. :/
And there are other cases when graph is no planar for example when two parallel line with one common point and one point of first line laying on second line, `Intersect edges` does not help here. Maybe it would be better to include in work of this node not planar graphs too.
