### ISSUE TITLE
Multiple Node Tree as Multiple Array of Array

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#862]
Just wondering if this can be possible:

So far, I am almost always working using a single node tree. Now, supposedly I am treating a single Node Tree as a single Node.

Just like if I use [Object + Array Modifier] and then I duplicate it, I still have the Array Modifier.

It occurs to me just now that using multiple Node-Tree might can solve my long time question on making variations :) 

![screen shot 2016-09-06 at 15 30 40](https://cloud.githubusercontent.com/assets/3952687/18262654/f8da929c-7446-11e6-8878-7f8ec7b8a29f.png)

In Sverchok, can we already able to Monad and then nicely have the Attribute to show up in the Panel just like AN "Input node"?

The grand setup I would like to have is to then have 1 single controlller, to drive all those Multiple Sverchok Node Tree.

In fact, if there is a quick way to make Deep Copy instance of Sverchok Node Tree, I really would like to know. I am doing it manually at this moment.

**Comment by ly29** [comment]
The monad doesn't show up in the input panel, it could be made to.
 Right now only float/int and object in show up the 3d view.

**Comment by zeffii** [comment]
At some point (and we have touched this already a couple of times) it would be neat to have some kind of meta vectorization, but it's not there yet.

**Comment by enzyme69** [comment]
Ok then, I will halt this question further more but will try to use multiple node tree like Array.

**Comment by ly29** [comment]
I think makes sense to add this and it struck me how to do it simple and cleanish way.

Needs to be tested, are you up for it @enzyme69 ? See #863

**Comment by enzyme69** [comment]
​Ok, I am up to it. Will test and follow the thread! Cheers~~
