### ISSUE TITLE
List Modifier proposal

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#865]
a few that spring to mind

> `list(set(list))`
```python
input = [0,0,0,1,1,1,3,3,3,5,5,5,6,7,8,4,4,4,6,6,6,7,7,7,8]
output = [set(input)]
```
> `list(no_sequential_duplicates_fcfs(list))`  (First Come First Serve, a Set() ordered by input)
```python
input = [0,0,0,1,1,1,3,3,3,5,5,5,6,7,8,4,4,4,6,6,6,7,7,7,8]
output = [0,1,3,5,6,7,8,4]
```
> `list(no_sequential_duplicates(list))`  (items may appear numerous times in the output list, but never consecutive dupes)
```python
input = [0,0,0,1,1,1,3,3,3,5,5,5,6,7,8,4,4,4,6,6,6,7,7,7,8]
output = [0,1,3,5,6,7,8,4,6,7,8]
```

> `list(ordered_set(list))`  (The Set() of input, ordered sequentially)
```python
input = [0,0,0,1,1,1,3,3,3,5,5,5,6,7,8,4,4,4,6,6,6,7,7,7,8]
output = [0,1,3,4,5,6,7,8]
```

**Comment by ly29** [comment]
Even though I suspect list math would have to retooled a bit.

**Comment by zeffii** [comment]
maybe a new node, List Ops.

**Comment by ly29** [comment]
Yes, doesn't need any level settings, it work recursively anyway.

**Comment by ly29** [comment]
Some thing like this could work I guess
```
def process(self):
     data = self.inputs[0].sv_get()
     def f(d):
          if isinstance(d[0], (int, float)):
              return operation(d)
         else:
               return [f(x) for x in d]
     out = f(data)
     self.outputs[0].sv_set(data)
```

**Comment by ly29** [comment]
@zeffii 
Have you had time to do this?

**Comment by ly29** [comment]
Also cumulative sum would be nice.
```python
>>> from itertools import accumulate
>>> list(accumulate(range(10)))
[0, 1, 3, 6, 10, 15, 21, 28, 36, 45]
```

**Comment by zeffii** [comment]
unfortunately no time, 

but also the boolean operators, _conjunction_ / _dysjunction_ / _negation_ / _exclusive or_.  needing ofcourse a second socket.. so maybe a separate core Set Ops node, converting implicitely to set, with (or without ) ordered output.

**Comment by ly29** [comment]
Yeah, good point. Introducing sets and maybe also dicts would give a completely new range of possibilities.

**Comment by zeffii** [comment]
The initial implementation should maybe not really output sets, but listified-sets ? 
or a switch to output real sets/listifed sets.

Alternatively have a node that converts sets to lists, if we want to compose a variety of Set operations.

**Comment by ly29** [comment]
I feel against a switch on an instinctive level, having sets seems reasonable

**Comment by zeffii** [comment]
many nodes have no idea about sets, it's a practical solution to make such _Set_ based nodes play nicely with the rest. a 'listify' switch seems very reasonable. best of both worlds.

on a mathematical level ofcourse, it's dirty.

**Comment by ly29** [comment]
Normalize perhaps also?
```python
input = list(range(10))
max_value = max(input)
output = [n/max_value for n in input]
output
[0.0, 0.1111111111111111, 0.2222222222222222, 0.3333333333333333, 0.4444444444444444, 0.555
5555555555556, 0.6666666666666666, 0.7777777777777778, 0.8888888888888888, 1.0]
```

**Comment by zeffii** [comment]
oh definitely

**Comment by ly29** [comment]
```python

def sequential_set(a):
    return list(sorted(list(set(a))))
```

Is the same as 
```python
def sequential_set(a):
    return sorted(set(a))
```
Since sorted takes an iterable and returns a list.

**Comment by zeffii** [comment]
fixed those, still waiting for a window of opportunity to work on it.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/18545201/6b7e6f24-7b38-11e6-83d8-31f697cd5eb7.png)

**Comment by zeffii** [comment]
untested yet.

**Comment by zeffii** [comment]
what about a `(a in B)` returning a list of booleans (handy for masks)

implementation for discussion only..

     A = [0,1,2,3,4,5,6,7,8,9]
     B = [2,3,4,5]
     [(a in B) for a in A]

**Comment by ly29** [comment]
Sounds very sane

**Comment by zeffii** [comment]
there's a numpy equivalent which I can't find at the moment, nice to test speeds..

**Comment by zeffii** [comment]
http://docs.scipy.org/doc/numpy/reference/generated/numpy.in1d.html

**Comment by zeffii** [comment]
re normalize
```python
import numpy as np

test_list = [10,9,8,8,8,8,6,5,5,5,4,3,2,1,0.5]

A = np.array(test_list)
A = A / np.max(A)
print(A)
'''
[ 0.12121212  0.10909091  0.0969697   0.0969697   0.0969697   0.0969697
  0.07272727  0.06060606  0.06060606  0.06060606  0.04848485  0.03636364
  0.02424242  0.01212121  0.00606061]
'''

max_value = max(test_list)
A = [n/max_value for n in test_list]
print(A)
```

**Comment by zeffii** [comment]
in that case the non numpy may have advantage sometimes..
```python
import time
import numpy as np

# https://www.andreas-jung.com/contents/a-python-decorator-for-measuring-the-execution-time-of-methods
def timeit(method):

    def timed(*args, **kw):
        ts = time.time()
        result = method(*args, **kw)
        te = time.time()

        print("%r (%r, %r) %2.2f sec" % (method.__name__, args, kw, te-ts))
        return result

    return timed



test_list = range(10**6)

@timeit
def npversion():
    A = np.array(test_list)
    return A / np.max(A)

@timeit
def stdversion():
    max_value = max(test_list)
    return [n/max_value for n in test_list]

npversion()
stdversion()
```
'npversion' ((), {}) 0.57 sec
'stdversion' ((), {}) 0.36 sec

**Comment by ly29** [comment]
Creating the np list is heavy. I have some ideas about a step wise np conversion. 

Test with a np array as input

**Comment by zeffii** [comment]
well, we knew that :)

http://stackoverflow.com/questions/30005735/list-of-numpy-arrays-to-single-numpy-array-without-copying-data

**Comment by zeffii** [comment]
Offtopic:
ScipPy allows for sparse arrays, that could potentially solve the issue with non homogenous polygon lists...  generate the `n*(len(longest_polygon))` , all spaces unused would take up practically no space.

**Comment by ly29** [comment]
I have another solution for that. Based on loops and the polygon data structure in blender allowing a flat list. 
In total of 2 arrays. The from_pydata in blender for creating a mesh is good reading.

**Comment by ly29** [comment]
Basiclly, one flat array with all vertex indexes.
And one array 2xnumber_of_faces with start and length, providing lookup.
We could package this into a class and allow iteraration over the faces...
For refrence see below.
```python
class Mesh(bpy_types.ID):
    __slots__ = ()

    def from_pydata(self, vertices, edges, faces):
 
        from itertools import chain, islice, accumulate

        face_lengths = tuple(map(len, faces))

        self.vertices.add(len(vertices))
        self.edges.add(len(edges))
        self.loops.add(sum(face_lengths))
        self.polygons.add(len(faces))

        self.vertices.foreach_set("co", tuple(chain.from_iterable(vertices)))
        self.edges.foreach_set("vertices", tuple(chain.from_iterable(edges)))

        vertex_indices = tuple(chain.from_iterable(faces))
        loop_starts = tuple(islice(chain([0], accumulate(face_lengths)), len(faces)))

        self.polygons.foreach_set("loop_total", face_lengths)
        self.polygons.foreach_set("loop_start", loop_starts)
        self.polygons.foreach_set("vertices", vertex_indices)

        # if no edges - calculate them
        if faces and (not edges):
            self.update(calc_edges=True)

   ```

**Comment by zeffii** [comment]
Cool! 
yeah, didn't we arrive at a similar flat solution in the redux threads? minus the explicit mention of loop_total and loop_start.   big speed boosts by keeping it flat/homogenous.

**Comment by ly29** [comment]
I don't remember if we did honestly, but was reading that code the other day after reading up on the loop data structure. Also if have the right datatype, ```float32```, ```uint32``` the data gets copied using ```memcpy``` in C. Then the mesh has to be validated, but that is also in C inside of blender and pretty quick.

**Comment by zeffii** [comment]
i think this node is outputting an extra bracket pair around the result..

**Comment by ly29** [comment]
```python
 out = [f(data1)]
```
So yes...

**Comment by zeffii** [comment]
yep.. i felt how snappy it could be in FLOW :)

**Comment by ly29** [comment]
It is so nice! Just wanted to post it here for completeness

**Comment by zeffii** [comment]
it will be tricky to convert the more elaborate nodes (like UV connect) , or nodes that rely on bmesh.ops

**Comment by ly29** [comment]
the nodes that rely on bmesh ops yes, for some I guess we could write replacements, for others it will be a data conversion process, ideally we should be lazy with that. 
 for others like uv connect that depends of structure it shouldn't be _that_ hard.

The data type is basically like below and sure there are some tricky cases but not impossible.
```python
List[Vertices] -> Mesh
```
The thing with uv connect and generators is that the levels of data needs to be clear, so they can be applied as needed in sensible ways.

**Comment by ly29** [comment]
Way off topic.

**Comment by zeffii** [comment]
done, just needs to push. implementation details below the hood may change. tho, the interface for the user and behaviour should be stable now.

**Comment by nortikin** [comment]
is this node vectorized?
look what i made https://yadi.sk/d/EF314fb-ws3gb
there is problem somehow with extra-polygons creation, so i need to "remove doubles" polygons, try list modifier and nothing happening. level 2,3,4...

**Comment by zeffii** [comment]
I will look into it, thanks!

**Comment by zeffii** [comment]
List Modifier doesn't know about sublists, just sequences of numbers.

I would prefer to make another simple node , like 'topology modifier' node that knows about removing double polygons - if the internal logic doesn't become frankensteinian to handle the special case, then i'm for adding a levels selector..

**Comment by zeffii** [comment]
If the order of those Polygons is of no significance, and internal ordering isn't either, then Set would be great to get uniques from tuples.

>>> m = {(0,1,2), (2,1,0), (3,4,5), (5,4,3)}
>>> m
{(0, 1, 2), (5, 4, 3), (3, 4, 5), (2, 1, 0)}

>>> m = {[0,1,2], [2,1,0], [3,4,5], [5,4,3]}
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: unhashable type: 'list'

**Comment by zeffii** [comment]
```python
plist = [
    [8, 12, 13, 9],
    [0, 3, 7, 4],
    [4, 7, 11, 8],
    [8, 11, 15, 12],
    [20, 23, 27, 24],
    [24, 27, 31, 28],
    [31, 28, 24, 27],
    [27, 31, 28, 24],    
]

def shift_until_lowest_first(p):
    # makes some assumption that the polygon is not degenerate.
    lowest = min(p)
    if lowest == p[0]:
        return tuple(p)
    else:
        idx = p.index(lowest)
        return tuple(p[idx:] + p[:idx])


mset = set()
for p in plist:
    pp = shift_until_lowest_first(p)
    print(pp)
    mset.add(pp)

print(mset)
```

**Comment by zeffii** [comment]
how about a Mode in List Modifier called ' Crush Topology ' , which can do a remove doubles for Edges or Polygons..

**Comment by zeffii** [comment]
or `Simplify Topology`

**Comment by nortikin** [comment]
other question is why connect uv node makes this doubles...

**Comment by zeffii** [comment]
_that_ I don't know -- I am too brain dead to follow the node tree logic. sorry :)

**Comment by nortikin** [comment]
investigated uvconnect code i make conclusion, that i have to remake it all. It works only with two levels of data, but i have three here, and it clean one level for usefullness.
There must be another algorithm for level connection

**Comment by nortikin** [comment]
fixed this issue in text_viewer branch
