### ISSUE TITLE
Testing with 2.78

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#866]
Mostly placeholder for now, some changes in menu code for nodes, don't know if it will affect us...

**Comment by ly29** [comment]
No issues as far as I can tell.

**Comment by zeffii** [comment]
the words "some changes" are always ominous :)

**Comment by ly29** [comment]
It broke my generic note add-on, thought it was good to check for us.
Admittedly it broke the hacky part where I insert the node into the menus, something which we don't do in Sverchok.
By the way, you realize we could set the special menu you wrote as the shift-a menu?

**Comment by ly29** [comment]
Or rather something like but simpler.

**Comment by zeffii** [comment]
not sure I follow, do you mean make the shift+A the default?

**Comment by zeffii** [comment]
edited

**Comment by ly29** [comment]
yeah, using ```NodeItemCustom``` you can draw as you want.
https://github.com/nortikin/sverchok/blob/master/menu.py#L374-L383

**Comment by zeffii** [comment]
i'm all for that. .. if @nortikin and you concur?

**Comment by ly29** [comment]
It is worth making a branch to test before deciding. Anyway I use ctrl-space for some operating system global functionality so I don't use it.

**Comment by zeffii** [comment]
I use it exclusively so will need to become familiar with shift+A again if we do make the step.. i'm in no hurry to do this.. but it is worth considering.

**Comment by ly29** [comment]
not a high priority agreed

**Comment by nortikin** [comment]
ctrl+space is ok
