### ISSUE TITLE
Mesh Join, polyedge compulsory?

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#871]
![image](https://cloud.githubusercontent.com/assets/619340/18397191/60292c38-76c7-11e6-8abe-d5c069629d14.png)

the meshjoin node needs the second input else it won't process, how do we feel about lifting that restriction, sometimes I just want to join verts using this node, even if temporarily.

**Comment by zeffii** [comment]
gist ID https://gist.github.com/fce099a2bb1552707304a711bab5c3f6

**Comment by ly29** [comment]
I feel quite good about removing all such assumptions. And I really mean all, no node should be limited by the assumptions of the author considering workflow etc. ( the author is me)

**Comment by ly29** [comment]
Also join list would work but there is no reason limit this

**Comment by zeffii** [comment]
yes to both, a new user might be confused that MeshJoin isn't the right thing to join just verts.

**Comment by ly29** [comment]
Honestly nodes shouldn't think to much. The should "just do it"

**Comment by ly29** [comment]
I am all for removing assumptions and raising  exceptions, don't try to protect against such things. That just hides bugs

**Comment by zeffii** [comment]
if you come accross any of my nodes that do this let me know.
