### ISSUE TITLE
Recursive Matter

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#874]
I made this Sverchok live noding video on "Slicing" object into pieces using Boolean. However, soon I realized I need to use "recursive" process if I want to have multiple slicers for an object.

I wonder how or whether this is possible in Sverchok or how the best way to think and implement this if I need to use Script Node MK3?

Actually in one of my old blog post, I actually did make a Python script that does this job:
1) Have an object
2) Have bunch of slicer objects (plane with solidify)
3) Python script will query the slicer objects and then slice the object, one at a time, with the next process will slice the previous result until it completes.

Thanks!

PS:
In addition to slicing. I also always wanted to do extrusion that is brancing and recursive. Something in this line:
1) Start with an object
2) Select random face(s)
3) Extude and get the result
4) Use object from previous result
5) repeat step 2 and 3

Maybe Script node and ability to recursive with iteration can do it in Sverchok?

**Comment by enzyme69** [comment]
I found old thing:
https://github.com/nortikin/sverchok/issues/315

Ly said it's more 'iterative'.

Whenever I search 'recursive', always end up with Fractal, L-Tree, etc. 

Zeffii has LTree template, but no body seems to use it because it is hidden even I don't know where to find it --- I will check documentation now.

For what I am doing, is it really easier and already the most efficient by using Python?

Should I wait a bit for Script Node 3? I am waiting in anticipation...

Another example case:
- Have a polygon
- break face into triangles
- break the triangles into smaller pieces, for each face
- do it again until it become too small.

Is this iteration? Or recursion?

**Comment by ly29** [comment]
Such things could easily be supported by the node group interface, but some thought would have be put into how it would work. At least for iteration, recursion would take a bigger change to work well, one that I would like to make, some other things need to be solved first. 
The difference between recursion and iteration is mostly philosophical when it comes down to actual calculations.

**Comment by ly29** [comment]
I think @elfnor has very sane approach, do some heavy things in the script and set up the parameters in Sverchok.

**Comment by ly29** [comment]
Also please read this part recursion vs iteration
https://en.wikipedia.org/wiki/Recursion_(computer_science)#Recursion_versus_iteration

Right now it is still not totally clear which model would be best supported for Sverchok

**Comment by enzyme69** [comment]
Ok that sounds like a plan.

Sometimes my confusion in "Script" nodes is: when is it actually triggered? Can we calculate calculation N number of iteration, then Sverchok pass it to the next node?

Ok I will read the article, in the meantime we can close this :p

**Comment by zeffii** [comment]
@enzyme69 

correction, i've implemented an L-system at least twice for script node
- https://github.com/nortikin/sverchok/blob/master/node_scripts/templates/zeffii/L-system_initial.py
- https://github.com/zeffii/BlenderLSystem3D/tree/master/sverchok_script_node_version

   (some examples) https://github.com/zeffii/BlenderLSystem3D/issues

I won't be able to offer much help in understanding how those work or what you could potentially do with them, a good book to read on the matter is : http://algorithmicbotany.org/papers/abop/abop.pdf

and Daniel Shiffman has a nice [processing / nature of code chapter](http://natureofcode.com/book/chapter-8-fractals/) about fractals (which is what an Lsystem is)

**Comment by zeffii** [comment]
@enzyme69 

> Can we calculate calculation N number of iteration, then Sverchok pass it to the next node?

exactly.

**Comment by zeffii** [comment]
## slices.. 

I would not use the Boolean nodes for slices..  the [cross-section node](http://nikitron.cc.ua/sverch/html/nodes/modifier_make/cross_section.html) takes multiple matrix's in, and you can ngon fill the output and even extrude the faces it produces..

[.blend](https://github.com/zeffii/weblog/blob/master/blends/experimental/estaw.blend?raw=true)

![image](https://cloud.githubusercontent.com/assets/619340/18580195/5bbaed66-7bfa-11e6-82d7-74c6abd2aef4.png)

**Comment by zeffii** [comment]
you'll notice in the examples that the normals of the slices (pre thickness) are not consistent, because they are calculated using the vertex order, and they are separate therefor no neighbours to make consistent with.. - the `Beta > Recalculate Normals` node may be helpful there
