### ISSUE TITLE
Change Pivot

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#875]
Actually, this is a very basic question, but how to change pivot in Sverchok :( Feel very noob.

For example, Plane pivot is not centered. 

Or if I like to rotate from specivic pivot position.

AN has this Pivot changing node. Can Sverchok does it in its own way? Or how is the math behind pivot? 

Will "Apply Matrix" does the job?

**Comment by ly29** [comment]
![skarmavbild 2016-09-13 kl 08 20 49](https://cloud.githubusercontent.com/assets/6241382/18463511/05522712-798b-11e6-9949-ad03892f0372.png)
![skarmavbild 2016-09-13 kl 08 20 55](https://cloud.githubusercontent.com/assets/6241382/18463514/0a5e5f64-798b-11e6-8e02-4941f9fbd417.png)

**Comment by enzyme69** [comment]
Gotcha! Thanks @ly29
