### ISSUE TITLE
small bugs thread..

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#879]
a small list of bugs in nodes I encounter while loading/testing.

In no particular order:

1.   SvEasingNode
    > addons_contrib\sverchok\node_tree.py:235
    > rna_uiItemR: property not found: SvEasingNode.float  
    >
    >    `self.inputs.new('StringsSocket', "Float").prop_name = 'float'  `
       
    > but there isn't a float FloatProperty() named float . not sure when this happened or it was always kaput.

2. Generative Art

    > self.xml_tree : see  https://github.com/nortikin/sverchok/issues/771#issuecomment-247772597

3. SvVertexGroupNode

    > assuming `obj` is found.. there be dragons.
     ```python
     class SvVertexGroupNode(bpy.types.Node, SverchCustomTreeNode):
        ...
        def process(self):
            obj = bpy.data.objects[self.object_ref]
            obj.data.update()
            Ve, We, Owe = self.inputs[:] + self.outputs[:]
    ```
    i think should be
    ```python
        def process(self):
            obj = bpy.data.objects.get(self.object_ref)
            if not obj:
                return
            obj.data.update()
            Ve, We, Owe = self.inputs[:] + self.outputs[:]
    ```
    and here too
    ```python
        def draw_buttons(self, context,   layout):
            layout.prop_search(self, 'object_ref', bpy.data, 'objects')
            ob = bpy.data.objects[self.object_ref]
            if ob.type == 'MESH':
                layout.prop_search(self, 'vertex_group', ob, "vertex_groups", text="")
    ```

4.  svAxisInputNode  

    >  should set bl_label upon creation to Z Axis. not before.

**Comment by zeffii** [comment]
i would like to push the node_cats stuff before fixing them..

**Comment by ly29** [comment]
Agreed they should be fixed. But one thing at a time.

**Comment by zeffii** [comment]
i'll fix these today
- [ ] sv_easing
- [ ] sv_axis_input
- [ ] generative_art
maybe @ly29 you want to do vertex_group , else I will : )
- [ ] vertex_group

**Comment by ly29** [comment]
If you are up for do it, those are small fixes, I want to introduce the object socket will change the need and logic for it anyway.

**Comment by zeffii** [comment]
OK! cool. will leave untouched.

**Comment by zeffii** [comment]
done with these.. @elfnor  if you don't like the `hasatttr(self , ...)` tests,  i'll understand - but it was necessary to suppress errors. Generative Art node Seem OK outwardly, Not sure why you are calling `self.process_node` , @ly29 any input - this is the only node to call that upon itself so perhaps it should just be `self.process`?

Have committed changes, and tested these nodes.

**Comment by ly29** [comment]
I think a lot of things are going on here, ```self.process_node()``` is call that will tripper the update system like ```updateNode```. However adding sockets after doing that seems like a bad idea... can't comment further without more testing.

**Comment by ly29** [comment]
Having looked at it I think generative art would benefit from script node like structure where the node doesn't have any outputs before loading etc.
I won't mess with it anyway.

**Comment by zeffii** [comment]
yeah, or a profile node approach, which lets one edit values of the XML via inputs..
