### ISSUE TITLE
nodes `__init__.py` automatic population..

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#880]
not sure if you've already done something about this @ly29  , else I'll start a branch and see if it breaks anything :)

**Comment by zeffii** [comment]
this is not exactly exciting stuff, but i've stared at these files for too long.

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/881

**Comment by ly29** [comment]
I did something similar once upon a time, the only thing I think about right now is to only add 
```.py``` files and skip others, including ```__init__``` of course.

```python
 if file.endswith('.py'):
    nodes_dict[current_dir].append(file[:-3])
```

**Comment by zeffii** [comment]
yeah, that's probably enough..  i added ignore_list feature.. it's a little verbose now.
