### ISSUE TITLE
Flat polygon storage

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#882]
To allow homogenous access to polygon and a simple and efficient storage mechanism it possible to have use the following approach.

```python
faces = [[0, 1, 3, 4], [0, 5, 3]]
# etc
vert_index = [0, 1 ,3, 4, 0 5, 4]
loop_start = [0, 4] # starting point of each face/loop
loop_total = [4, 3] # length of each face
```
By packing it into a class we can then provide a ```__getitem__``` method giving access for things like
```python
for face in polygons:
    print(face)
```
For a test implementation see branch [flat_polygon](https://github.com/nortikin/sverchok/tree/polygon_flat)
https://github.com/nortikin/sverchok/blob/polygon_flat/utils/polygon.py#L39-L81

**Comment by ly29** [comment]
Originally mentioned in #865 the idea is directly taken from blender ```Mesh``` and also allows quick access from and to blender mesh data. For reference see below.

```python
class Mesh(bpy_types.ID):
    __slots__ = ()

    def from_pydata(self, vertices, edges, faces):
 
        from itertools import chain, islice, accumulate

        face_lengths = tuple(map(len, faces))

        self.vertices.add(len(vertices))
        self.edges.add(len(edges))
        self.loops.add(sum(face_lengths))
        self.polygons.add(len(faces))

        self.vertices.foreach_set("co", tuple(chain.from_iterable(vertices)))
        self.edges.foreach_set("vertices", tuple(chain.from_iterable(edges)))

        vertex_indices = tuple(chain.from_iterable(faces))
        loop_starts = tuple(islice(chain([0], accumulate(face_lengths)), len(faces)))

        self.polygons.foreach_set("loop_total", face_lengths)
        self.polygons.foreach_set("loop_start", loop_starts)
        self.polygons.foreach_set("vertices", vertex_indices)

        # if no edges - calculate them
        if faces and (not edges):
            self.update(calc_edges=True)

   ```

**Comment by ly29** [comment]
As @zeffii pointed out this method was probably mentioned already in on of the old discussion threads about numpy and redux. I am not sure if I got it then to be honest...

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/issues/688#issuecomment-111143209 this illustrates it i think

**Comment by ly29** [comment]
Was exactly going to post the same thing.

**Comment by ly29** [comment]
Right now I consider a transition to a redux state allowing code reuse as is.
1. Introduce a new data interface instead of ```.sv_get/.sv_set``` producing numpy data which is then automatically converted to old data for nodes using the old interface
2. Wrap old nodes similar to what the vectorized monad does.
3. Introduce infinite sublevels using existing nodes by auto wrapping them
4. Convert nodes to level unaware and using numpy/new data model
5. Introduce cython/c modules for the slowest nodes

This will break existing layouts but would allow a large amount of code reuse.

**Comment by ly29** [comment]
Note that this might become slower before it gets quicker due to all the conversions going on... But the end result would be quicker, more flexible and more expressive.

**Comment by ly29** [comment]
Probably won't do more with this right now, just some code ideas I wanted to share.

**Comment by zeffii** [comment]
i'm all for this. Cython is not something I have experience with..

yeah autowrapping, will slow stuff down.

I'm for creating an additional, alternate set of nodes, which don't need to interact (yet) with current nodes but can be composed with eachother and have a numpy stream from start to finish, they'd be included in a new separate menu. Just to prove the experiment and gradually increase the set of numpy nodes..

**Comment by ly29** [comment]
The new nodes could even use a SN3 like interface reducing boilerplate.

**Comment by zeffii** [comment]
`\ o /`

**Comment by ly29** [comment]
Cython is clearly step 5, only some things, preferably abstracted away into a library.

**Comment by zeffii** [comment]
the great thing about rewriting as numpy is we get almost magical control over list shifting, i would not be surprised if the entire functionality of UV connect can be condensed into maybe 12 lines of numpy, or less.

**Comment by nortikin** [comment]
do we need roadmap for sockets update?
```objects ocket
polygon/edges socket
digits lists socket
vertices socket
other```
temporery step by step moving to new nodes with temporery back compability
UVconnect in 12 lines? Intrique.

**Comment by ly29** [comment]
We have an object socket

**Comment by zeffii** [comment]
a `pydata socket` perhaps :)

**Comment by nortikin** [comment]
yes, we do. maybe to add colors, etc. To have all concept as system

**Comment by ly29** [comment]
More important than sockets are types, these are related concepts but not the same.
