### ISSUE TITLE
Issues with `make html` for docs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#890]
compiling docs for the first time on this windows machine.. yikes, for the first time in over a year I think to `make html`..

i'll investigate these warnings:

```
checking consistency... C:\Users\zeffi\Desktop\GITHUB\sverchok\docs\nodes\beta\set_dataobject.rst:: WARNING: document isn't included in any toctree
C:\Users\zeffi\Desktop\GITHUB\sverchok\docs\nodes\modifier_change\iterate.rst:: WARNING: document isn't included in any toctree
C:\Users\zeffi\Desktop\GITHUB\sverchok\docs\nodes\scene\eval_knieval.rst:: WARNING: document isn't included in any toctree
```

**Comment by nortikin** [comment]
http://nikitron.cc.ua/sverch/html/nodes/list_main/list_modifier.html
i'm ok in linux

**Comment by zeffii** [comment]
I think it means the .rst exists for these nodes, but isn't included / linked in any pages..

**Comment by nortikin** [comment]
exactly

**Comment by zeffii** [comment]
iterate.rst is still beta?

**Comment by zeffii** [comment]
i know eval_knieval can be removed

**Comment by nortikin** [comment]
will do

**Comment by nortikin** [comment]
_static left
