### ISSUE TITLE
Tracing Outer Edge of Flat Projected 3D 

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#913]
Wondering if we already have node in Sverchok that does this:

Supposedly I have 3D animated objects and I projected using Blender Modifier, so all the points are flat in certain plane.

![prtscr capture_18](https://cloud.githubusercontent.com/assets/3952687/19267249/78106c76-8ff9-11e6-9a74-0a40e8016935.png)

Now, I just need the points at the most outer part, kind of like a way to trace and have just the outer outline edge.

Any clues?

Thanks!

PS: I will check my earlier question regarding finding the most out points.

**Comment by enzyme69** [comment]
Hey, I have an idea! What if I have like a line outside maybe like Circle, and try to get all the vertices closest to that boundary?

**Comment by enzyme69** [comment]
![prtscr capture_20](https://cloud.githubusercontent.com/assets/3952687/19268809/4d453572-9002-11e6-9fcf-bd2b09fbbc1d.png)

**Comment by enzyme69** [comment]
Funnily enough, I was asking the same question back in 2011...
https://blenderartists.org/forum/archive/index.php/t-238474.html

**Comment by enzyme69** [comment]
There is one solution is to use SVG Export, Freestyle. But....

**Comment by enzyme69** [comment]
![0002](https://cloud.githubusercontent.com/assets/3952687/19269213/11531b76-9005-11e6-88d7-a5ae21225294.png)

If only Sverchok has Black and White tracer, which will output edges... that I could resample.

**Comment by enzyme69** [comment]
I have a feeling that Sverchok can already do this using Projected Extrusion and Cross Section.... brain thinks..

**Comment by enzyme69** [comment]
I don't want to have to use Houdini yet...

![prtscr capture_21](https://cloud.githubusercontent.com/assets/3952687/19269374/f5b4b892-9005-11e6-915c-9d4d7a0fb76e.png)

**Comment by enzyme69** [comment]
(... this GIST thing is super handy. I wish I understand it earlier.)

https://gist.github.com/anonymous/d17c7f292d120401a95c3585551bb01d

**Comment by enzyme69** [comment]
![prtscr capture_23](https://cloud.githubusercontent.com/assets/3952687/19269734/eeeeaf8e-9007-11e6-9c7d-51d5ea014e81.png)

Here, I am using Displacement Modifier to "push" the area of silhoutte (projected 3D into 2D), however, I realized that this probably will not help much.

**Comment by nortikin** [comment]
it is task for rasterizer, so called render engine, or even opengl
what sverchok here is good for is to find smallest polygons, quads or ngons and do something with them.
We can also reytrace mesh with kosvor tools, that he upgrading today (not merged yet)
Also to use this nodes http://nikitron.cc.ua/Sverchok_man_15_obj_nodes.html

**Comment by nortikin** [comment]
sverchok is good for analyze or sort data.

**Comment by zeffii** [comment]
it seems to be that you could 
   - flatten 3d coordinates to 2d, 
   - drop the polygons, keep edges
   - then add a Intersect node
   - then fill holes node
   - then limited dissolve
   - then delete the resulting polygon.

may not work very well with silhouettes that contain holes..

**Comment by enzyme69** [comment]
![prtscr capture_23](https://cloud.githubusercontent.com/assets/3952687/19269734/eeeeaf8e-9007-11e6-9c7d-51d5ea014e81.png)

Here, I am using Displacement Modifier to "push" the area of silhoutte (projected 3D into 2D), however, I realized that this probably will not help much.

It's interesting how the Blender OpenGL that always "show edges of selected objects" might be the perfect answer, maybe not accessible.

I will try your tips @zeffii  thanks!

Will come back.

@nortikin I think Sverchok should be able to do this but needing a new node, that somewhat works on the 2D only.

One sec...

**Comment by enzyme69** [comment]
I think the simplest solution is to use SVG Export, via Freestyle, but then I need to source all the SVG back in order, but that's probably easy enough.

Still doing Zeffii suggestion, maybe missing one thing.

**Comment by nortikin** [comment]
no way it can be simple. many iterations algotythm

**Comment by zeffii** [comment]
plus.. Sverchok doesn't have a camera object interpretter (to get a Viewing Matrix) ..i think? : )

**Comment by nortikin** [comment]
Scene-Scene reycast can be used as tracer, but if it is productive...

**Comment by enzyme69** [comment]
I thought getting outline of 3D projected into 2D flat would be "simple".

Current method:
- Render export SVG to get the outline
- Bring all the SVG (segmented curves) back into Blender, merge (still
messy)
- Bring into Sverchok
- Remove double in Sverchok (some curves give opposite direction so it's
not clean).

What's Sverchok node that can do projection?

I imagene if we have bunch of points, flat, we should be able to "ray" all
the outer points and then sort it and join as outline.

**Comment by zeffii** [comment]
there's been a few questions of that nature of Blender StackExchange, looking for Python solutions ..


The cross-section Node could be probably produce useful outlines in some instances..

**Comment by enzyme69** [comment]
Since we just need 2D outline, I thought at some point perhaps we can do it
like this:
1) projected
2) projected and displaced in (so it shrink) and extruded it somewhat to
get the volume
3) get the points that are outside of no.1 minus no.2

or intersect like Zeffii said.

**Comment by nortikin** [comment]
WITH TRACING it can be done filtering from normal of intersection, but calcs... outer concerning to camera or to other objects can be done.

**Comment by enzyme69** [comment]
That brute force silhouette, that's made into operator is nice. It should
be Sverchok node :D

**Comment by nortikin** [comment]
or crossection indeed can be used several times

**Comment by nortikin** [comment]
with different angles

**Comment by nortikin** [comment]
to bind to bones (if there are)

**Comment by enzyme69** [comment]
![screen shot 2016-10-12 at 20 51 53](https://cloud.githubusercontent.com/assets/3952687/19305678/d171c156-90bd-11e6-9b2e-3c13c0ccdaad.png)

Projected Torus, using Shrinkwrap. But it's only working in Axis X,Y,Z positive and/or negative.

**Comment by zeffii** [comment]
as far as I can tell, even Blender itself uses a shortcut (openGL trick) for this..

https://github.com/dfelinto/blender/blob/e6dda514bae1aa53724ac59afc5c98177bbdbdba/source/blender/editors/space_view3d/drawobject.c#L3925-L3947

**Comment by nortikin** [comment]
sverchok vector-vector math-projection???
what Jimmy really needs? filled with polygons or outer edge? Postprocessing in compositor can help?

**Comment by nortikin** [comment]
I have the solution. But lost the Internet. Later will post

**Comment by nortikin** [comment]
https://yadi.sk/d/-N-_3GRAwhesq
this file !!!!!!!!!!!!!

**Comment by nortikin** [comment]
but turn on alt+F/F fill polygons
and use bmesh

**Comment by enzyme69** [comment]
@nortikin I will have a study, thanks a bunch!!

**Comment by enzyme69** [comment]
![screen shot 2016-10-13 at 10 16 29](https://cloud.githubusercontent.com/assets/3952687/19331080/234ae88e-912e-11e6-919b-d7d38b4fdc95.png)

Hope you are not tired of this topic already.

But, I am trying to understand your setup:
- Why do we need Vector Drop in this case?
- I can see the Solidify makes this pancake solid from flattened mesh, but the cross section has failed on me, when I don't use Vector Drop, or maybe just Sverchok misbehaving. I will check again...

**Comment by enzyme69** [comment]
![screen shot 2016-10-13 at 10 57 51](https://cloud.githubusercontent.com/assets/3952687/19332000/e953f688-9133-11e6-9770-6c697c08b43b.png)

Ok, I think I started to get this .... 

The Vector Drop, totally drops everything to the floor. That can be handy.

I think the rest I understand, it's not always perfect, I wish this can be more straight forward. But anyway.

This has been eye opening :)

Especially the "Project vector" using Cross Product is interesting.

**Comment by enzyme69** [comment]
What's interesting is though, we can have this scattered points, that are
flat, we can do triangulation, voronoi, but is there a possibility to just
delete all points in the area and retain the edges? That way we have the
outline flat, silhouetted.





------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by nortikin** [comment]
crossection making outline with some wastes. And flat.
Vector drop anti-apply matrix, so it not multiply, but delete vector on matrix.
