### ISSUE TITLE
ShrinkWrap in Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#919]
![screen shot 2016-10-16 at 22 13 26](https://cloud.githubusercontent.com/assets/3952687/19417047/f437d3a0-93ed-11e6-994e-9b84d08fdabd.png)

I am thinking of making a boring building by using Cylinder, but I wanted it to be box like, so I am using ShrinkWrap to do it.

Is there a more elegant to do this from inside Sverchok?

Like turning Circle into Square? Or vice versa. In this case, I am using Cylinder, but basically duplicating up.

Example:
UTS Building Sydney (one of the most boring building in Sydney)

JSON:
https://gist.github.com/2bcdfa055f5f4cc244973ad1d690dd47

**Comment by enzyme69** [comment]
Boring building like this:
http://www.abc.net.au/news/2016-02-22/brutalist-architecture-in-sydney-the-buildings-many-love-to-hate/7188740

I want to make using Sverchok. I start with boring structure first.

**Comment by zeffii** [comment]
if you are using shrinkwrap just to get a subdivided square, then consider using a cross section of the Rounded Cube (generator) ..

**Comment by Kosvor2** [comment]
you can use "obj raycast" node to move verts by their normals onto another object:
![shrinkwrapnormals](https://cloud.githubusercontent.com/assets/22656834/19417586/50219942-93b9-11e6-938c-ed2444763db5.png)

**Comment by enzyme69** [comment]
Awesome, I'll have a study on this thanks!
