### ISSUE TITLE
Sverchok vs Structure Synth

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#923]
Just wondering about this...  I tried Structure Synth outside of Sverchok.

Sverchok also has Structure Synth port via Elfnor, although probably not 100% and it is also scripted using a JSON? 

My quick guess is that Structure Synth is generating this "Matrix" thing, scaling, rotating, translating, and does loop and random, but with certain "limit" and recursively.

Sverhok is kind of doing that too, right (can generate matrix)? And more?

Maybe if I think Structure Synth is kind of a system or a solver in itself.

Investigation continues... maybe a good study.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19521015/76962934-9612-11e6-9aac-5bd0b6fe7fae.png)

**Comment by zeffii** [comment]
Please study the documentation, if there are still question i'm sure they can be answered. @elfnor  if you have a few minutes?

**Comment by enzyme69** [comment]
http://after12am.github.io/eisenscript/docs/

It has online version as well. I guess nice to study. and then port to Sverchok way of noding.

**Comment by zeffii** [comment]
That's a sweet looking manual.

**Comment by nortikin** [comment]
grub css?

**Comment by zeffii** [comment]
no, leave docs alone for now ;)
