### ISSUE TITLE
Exploring String and Text manipulation in Sverchok

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#924]
I am wondering where I did wrong. Basically making a simple Grid to spawn Text and I know there should be X number of Text Data, in which I was using Number List to generate.

Sometimes it corrects, sometimes missing few values.

![screen shot 2016-10-19 at 18 35 03](https://cloud.githubusercontent.com/assets/3952687/19509589/2f13335e-962b-11e6-8d85-4c8376c30224.png)

https://gist.github.com/c4f4b871e7ced035c175143156c65932

**Comment by enzyme69** [comment]
Ok, apparently I was using "Round" function and my item index total was sometimes out of the index total. Never mind 💃

**Comment by enzyme69** [comment]
But, I was wondering if there is a trick that kind of wrapping same values?

https://gist.github.com/1bad945a9f6acee036a22b19a3ebeb09

![screen shot 2016-10-19 at 18 44 07](https://cloud.githubusercontent.com/assets/3952687/19509765/0bfdd166-962c-11e6-9c42-5063a257f89c.png)

**Comment by enzyme69** [comment]
What I did so far:
1) Prepare bunch of fruit names as Text List
2) Generate random values that will then be sorted, this will then collect the Text List in order
3) Output into Typography Viewer

What I want is to tell Sverchok:
Create a tidy stack of those values.

**Comment by enzyme69** [comment]
The text: 
[["apple", "banana", "carrot", "kiwi", "orange"]]

**Comment by enzyme69** [comment]
Latest node setup:
https://gist.github.com/8da58517b4d75d3beb574324ed7a829c

**Comment by enzyme69** [comment]
Actually the exact question:
Is there a node in Sverchok or a way to "count" the number of data that is the same?
[0,1,2,3]
[0,0,0,1,2,2,3,3,3,3,3]

becoming: [3, 1, 2, 5]

This way, I could create "Lines" that will generate points for my stacks towers 💃

**Comment by nortikin** [comment]
https://gist.github.com/ce287d080128f1f5793fe1edd41c9b9b
use this scripted node for now

**Comment by enzyme69** [comment]
@nortikin in the GIST above, your example TEXT INPUT is "apple apple banana banana banana" space separated.

What if the TEXT INPUT is like "apple, apple, apple, banana, banana".

**Comment by enzyme69** [comment]
![screen shot 2016-10-20 at 21 09 58](https://cloud.githubusercontent.com/assets/3952687/19555688/9ab46af4-9709-11e6-82c4-d61ec14119fc.png)
And also:

I can access Text word, separated by comma, but how to break word into characters?

**Comment by zeffii** [comment]
in python..
```python
from collections import defaultdict

astr = """

apple, apple, apple, banana, banana

""".strip()

items = astr.split(', ')
print(items)  # >> ['apple', 'apple', 'apple', 'banana', 'banana']

sum_dict = defaultdict(int)
for i in items:
    sum_dict[i] += 1

print(sum_dict)  # >> defaultdict(<class 'int'>, {'apple': 3, 'banana': 2})

counts = []
for k in items:
    value = sum_dict.get(k)
    if value:
        counts.append(value)
        sum_dict.pop(k)

print(counts)  # >>  [3, 2]
```

**Comment by zeffii** [comment]
it seems to me like you are approaching something like this in reverse.. For example if you have a list of words, and you have a list of corresponding repeat values, the input would be the same and you avoid some post-processing..

```python
words = "word1, word2, word3, word4"
repeats = [4, 2, 1, 5, 2]
```
and think of ways to approach that with nodes..
```python
words = "word1, word2, word3, word4"
repeats = [4, 2, 1, 5, 2]

word_list = words.split(', ')
new_word_list = []
[new_word_list.extend([w for i in range(n)]) for n, w in zip(repeats, word_list)]
print(new_word_list)
# >>  ['word1', 'word1', 'word1', 'word1', 'word2', 'word2', 'word3', 'word4', 'word4', 'word4', 'word4', 'word4']
```

**Comment by zeffii** [comment]
The reason I added the Scripted Node was because sometimes you get these conceptually simple needs, that don't have dedicated nodes because it doesn't make sense to have such specificity. (it would either only work in one specific scenario or be a very complicated node internally). Sometimes a single scripted node can replace 10 or 20 or even _most_ nodes in a layout :)

**Comment by enzyme69** [comment]
This makes a lot of sense :) Thanks!!

**Comment by enzyme69** [comment]
I supposed we can close this for now, thanks for all the help :D
