### ISSUE TITLE
Modifications to "Objects In" Node breaks old layouts.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#928]
```python
  File "...sverchok\core\update_system.py", line 322, in do_update_general
    node.process()
  File "...sverchok\nodes\basic_data\objects.py", line 273, in process
    if self.outputs['Object'].is_linked:
Node Objects in had exception 'bpy_prop_collection[key]: key "Object" not found'
```

**Comment by zeffii** [comment]
i wrote some generic Node Replace code a while back, it might be worth seeing if we can auto replace nodes, or have an operator that can replace the node and reconnect sockets..

**Comment by zeffii** [comment]
because this will break a lot of layouts, perhaps we can code the `process` function with a bit less assumption..  like ..
```python
    if "Object" in self.outputs and self.outputs["Object"].is_linked:
```
or..
```python
    obj_socket = self.outputs.get("Object")
    if obj_socket and obj_socket.is_linked:
        ...
```

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/commit/b9e6bf690b268b76fe185cffdddf206d8123f9b8

you did this @nortikin  :) ?

**Comment by nortikin** [comment]
but i did after this fixing. i remember i made new objectin mk2 and old placed to oldnodes in master... or not?

**Comment by nortikin** [comment]
https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/objectsmk2.py
https://github.com/nortikin/sverchok/blob/master/old_nodes/objects.py

**Comment by nortikin** [comment]
i see now, commited

**Comment by zeffii** [comment]
cool!
