### ISSUE TITLE
Alembic Animation Export not supported?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#930]
I am testing Alembic Export using Sverchok, apparently there are a few gotchas.

In this case for example, I have a Random Vector that is changing number and seed every frame, and what I get is something that is more like Particles....

![screen shot 2016-10-23 at 10 47 57](https://cloud.githubusercontent.com/assets/3952687/19623253/57318846-990e-11e6-94f4-99571a92f6b4.png)
![Uploading Screen Shot 2016-10-23 at 10.46.57.png…]()

**Comment by enzyme69** [comment]
I also tested a deforming plane, and it will not save the animation of the mesh :( 

The MDD might work.

![screen shot 2016-10-23 at 10 52 21](https://cloud.githubusercontent.com/assets/3952687/19623265/ee9cc790-990e-11e6-8805-a91603b53b75.png)

Maybe Alembic export does not recognize that mesh as the same object if Sverchok re-generate the mesh every frame?

**Comment by zeffii** [comment]
Please resist calling things a bug if it doesn't work as expected. BmeshViewerMK2 works as intended, but we can certainly have a look at the alembic issue, if making the viewer support alembic proves complicated it will have to wait - it won't be my highest priority.

**Comment by zeffii** [comment]
try the `fix vert count` mode, this doesn't throw away the mesh but only updates it (and assumes the vert count doesn't change).

![image](https://cloud.githubusercontent.com/assets/619340/19624633/529b9f14-9900-11e6-8cd6-5282ab4d8fbc.png)

**Comment by enzyme69** [comment]
I tried the "Fixed vert count" and still not happening with Alembic. it's
only exporting 1 object. I think it's Blender Alembic current limitation (I
guess?).

But, curious when is the example case to use "Fixed vert count"? Why is it
a hidden option?

**Comment by zeffii** [comment]
when you are just manipulating vertex positions of an object; sort of like what happens when you animate with shapekeys, you don't mutate the Vertex Count , you just mutate the positions. It is a limited (but very real) use-case. Updating a fixed size list of verts using Fixed Vert Count is much faster than rebuilding an entirely new mesh (with edges and polygons too) . 

I don't know anything about what alembic supports or expects. 

it's not a hidden option, it's just not an option we use much so it's not necessary to have it on the main UI (that would be ugly and too busy).

**Comment by zeffii** [comment]
i wouldn't be surprised if the Alembic support also assumes that edge and polygon lists remain unchanged. I think Fixed Vert Count does let you change edges and polygons, another more restricted mode could be introduced if needed.. 

but as said, I have no looked into Alembic.

**Comment by enzyme69** [comment]
A quick hack I use to assign Displace Modifier with Zero Strength, and exporting the Alembic. Maybe it is triggerring Alembic export system that is not happening unless it detects Modifier like Displace Modifier (deforming mesh) or Armature.

I guess, that's good enough for now :)

Thanks for looking into this, Dealga. Much appreciated.

**Comment by enzyme69** [comment]
![sv_alembic_test_generator](https://cloud.githubusercontent.com/assets/3952687/19711728/77ff3218-9b83-11e6-9e10-8c26fc251ea5.gif)
Proof as above 💃

**Comment by zeffii** [comment]
there you go, I'm glad you found some kind of workaround.

**Comment by enzyme69** [comment]
I manage to export Alembic by appending "Displace" Modifier for each object
deforming. It's a hack, but works :) I will make video tutorial about this
later.





------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au
