### ISSUE TITLE
Operator to auto replace deprecated Nodes on demand.

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#932]
Loading some older .blends often I get these red frames around depreciated Nodes. Maybe we should add a function to the node_info of each Deprecated node frame, allowing the user to replace the node with its current equivalent. (auto disconnect, reconnect)

The main problem with this is that some replacement nodes have alternative variable names / socket names / new / changed algorithms. For most deprecated nodes the difference is not very big, but a few will require some remapping code.

Not sure when or if this will happen, it will depend on how much this issue pisses me off :)

**Comment by nortikin** [comment]
IMHO
let it be as it is.

**Comment by zeffii** [comment]
maybe i'm not clear, it would be an _on-demand_ feature. If we get depreciated nodes, they can be hotswapped by envoking an operator. Nothing is done without knowledge from user.

will close for now..

**Comment by nortikin** [comment]
ok, great idea
