### ISSUE TITLE
Real Random Walk

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#933]
I was reading this blog by Omar on Animation Nodes and there is this "Random Walk" example, where in the loop it can re-assign the value into itself.

http://squircleart.blogspot.com.au/2016/10/the-essence-of-animation-nodes-loops.html

I was surprised. 

![screen shot 2016-10-25 at 16 41 07](https://cloud.githubusercontent.com/assets/3952687/19674191/124126fe-9ad2-11e6-9890-2377f023ac5f.png)

The effect is like accumulating the point and giving output that is more "generative" instead of recycling the starting point.

Is there a way to do this in Sverchok?

This is exactly answering my confusion that I found back then "why is this random walk different from Processing".

**Comment by zeffii** [comment]
there are several ways to do a random walk. 

1. One way is to have a start position and keep updating it with a new offset in x,y,z. You might want to cache the result for each 'frame'.
2. Have a function with parameters and predictable randomness that can be evaluated at any given point, along a range from 0 to 1.

Sverchok has a few nodes that compose well to get something similar.. see: 

http://blender.stackexchange.com/a/65456/47

**Comment by zeffii** [comment]
worth the read: http://natureofcode.com/book/introduction/

**Comment by enzyme69** [comment]
Hmm.. do not quite get the "cache the result for each 'frame'."

I'll give it a try first.

**Comment by enzyme69** [comment]
![screen shot 2016-10-25 at 22 04 51](https://cloud.githubusercontent.com/assets/3952687/19683711/19a00bfe-9aff-11e6-9ba2-7b22b65752d5.png)

yet another mysterious SV node: "Cache". Without documentation.

I will recreate your example above... wait.

**Comment by enzyme69** [comment]
![screen shot 2016-10-25 at 22 12 23](https://cloud.githubusercontent.com/assets/3952687/19683911/299a9802-9b00-11e6-912c-17119ea517a6.png)

Firstly, this one gives Wiggle effect, similar to AN if I plug Line through it.

https://gist.github.com/5a3ef9d3ad5e8ec83cf8600ce26dea20

**Comment by enzyme69** [comment]
This one gives Worms with varying speed.

![screen shot 2016-10-25 at 22 18 53](https://cloud.githubusercontent.com/assets/3952687/19684087/12c94d70-9b01-11e6-9b1f-4a63aad46635.png)

https://gist.github.com/9591cd0f33276e1aacce0982ff63fe3f

I vaguely remember the Processing one. Might need to re-read that one.

I am scratching my head on why I get either of this
1) The worms swimming in the same spot
2) The worms can kind grow and random walk

**Comment by enzyme69** [comment]
I remember doing this with Line. This is the most "clear" to me.

![screen shot 2016-10-25 at 22 31 22](https://cloud.githubusercontent.com/assets/3952687/19684422/d300b4e2-9b02-11e6-9a13-3a399a2f5f2e.png)

The weird thing is... even with List Modifier Accumulate, the line just wiggle around. It does not give that free-will, real random walk.

**Comment by enzyme69** [comment]
![screen shot 2016-10-25 at 22 54 49](https://cloud.githubusercontent.com/assets/3952687/19685016/15fd342a-9b06-11e6-9d6f-78bc0a909ebc.png)

Same thing, not what I wanted.

**Comment by enzyme69** [comment]
However....
![screen shot 2016-10-25 at 22 56 10](https://cloud.githubusercontent.com/assets/3952687/19685051/4584a444-9b06-11e6-8fc1-a460e85213c8.png)

Wonder why...

**Comment by nortikin** [comment]
because it initially x.
thing with accumulating values can be made with sn1 simply.
We still have not loop iterator engine in sverchok.

**Comment by zeffii** [comment]
> Hmm.. do not quite get the "cache the result for each 'frame'."

I'm not sure how the Cache node works without looking at the code, but that's not what I meant - sorry to confuse.

With caching I mean you start with a `x,y,z` and add some `delta_x, delta_y, delta_z` on each consecutive frame, and store the value generated by each frame. That way if you've already calculated 2000 frames, and want to see frame 500's value all you do is one lookup `cache.get(500)`. instead of doing 500 randomized (with a seed) calculations from the starting point, there would be a lot of duplicated processing.

Further more, an interesting meandering (random walk) is a bit more than just a string of random values, it takes into account current direction, velocity and acceleration and maybe moment. With loops in AN that's something that looks easy enough to do, but personally I'd just code a scriptnode.

Simple random walk
```
<code> todo
```

**Comment by nortikin** [comment]
not so simple as i thought, not 5 lines

if there is aim, you can walk. randomly

**Comment by zeffii** [comment]
a 3d meandering i made last year, in .js 

http://codepen.io/zeffii/pen/meWqqr

**Comment by zeffii** [comment]
(this doesn't do any caching, despite the variable name)

[smoolie_2016_10_25_14_10.zip](https://github.com/nortikin/sverchok/files/550810/smoolie_2016_10_25_14_10.zip)

https://gist.github.com/e425cda6bd102640e9d4fbb1dc499e86

![image](https://cloud.githubusercontent.com/assets/619340/19689533/fecc5dcc-9acd-11e6-93a9-2bab714dca8a.png)

**Comment by zeffii** [comment]
[smoolie_2016_10_25_14_54.zip](https://github.com/nortikin/sverchok/files/550934/smoolie_2016_10_25_14_54.zip)

This version makes several parallel meanderings, and the bottom left slider picks an index in each vertex list produces...

[smoolie_2016_10_25_14_58.zip](https://github.com/nortikin/sverchok/files/550950/smoolie_2016_10_25_14_58.zip)

![gif](https://cloud.githubusercontent.com/assets/619340/19691471/aed66cd4-9ad4-11e6-9fea-2a346592a51f.gif)

**Comment by enzyme69** [comment]
Aah, SV Script node... ALWAYS... ok before looking at your answer, I will try not to cheat and will make my own.

Thanks again Zeff and Niki!

**Comment by enzyme69** [comment]
That's me, aimlessly wandering snail in endless forest of Sverchok...

**Comment by zeffii** [comment]
btw, `List Modifier Accumulate` doesn't operate on Vectors, but i understand if you think it should..

**Comment by zeffii** [comment]
Think of the current List Modifier in a similar class as the `math` node for numbers,  it would make sense to have a similar offer `Vector List Modifier`, that expects the deepest nested units to be vectors/3-tuples

**Comment by enzyme69** [comment]
Oh, yes I just noticed about List Modifier. So many things to learn.

**Comment by enzyme69** [comment]
![screen shot 2016-10-26 at 19 47 05](https://cloud.githubusercontent.com/assets/3952687/19719390/6b838cb4-9bb5-11e6-9096-a898c4d766c2.png)

Btw, Alembic can export 40000 points of this meandering thing, but does not export the edge. Weird.

Anyhow, I will wait for next Alembic iteration of Blender.

**Comment by enzyme69** [comment]
Furthermore, testing with Skin Modifier (LIVE). It's pretty amazing actually.

**Comment by zeffii** [comment]
@enzyme69  it could be even greater if the SkinModifier had a test on every update to see if the Mesh was modified or not, and refresh with same radii if it was changed, and if there where more verts then auto set new radii (repeat last).  

until then, Skin Mesher view node is a cumbersome / convoluted ugly code (internally)

**Comment by enzyme69** [comment]
![screen shot 2016-10-26 at 20 10 53](https://cloud.githubusercontent.com/assets/3952687/19720067/534ef702-9bb8-11e6-8b35-8e2a5bb9e20e.png)

Yes, and a bit heavy. Can be more elegant one day. 

1) 40000 points that supposed to have edges (not) is around 600 MB for 1000 frames. Maybe it should export as Curve, but yeahh...
2) And With Skin Modifier, it looks cool, but 100 frames = 2.6 GB Alembic cache :p

Probably this heavy data baking become norm when dealing with "complexity". --- I personally don't like this stupid baking process.

**Comment by zeffii** [comment]
the greatest effects are rarely easy to achieve, and if they are then they rely on some dedicated feature specifically written to make one complex thing _easier_.

**Comment by enzyme69** [comment]
I will quote that one day.
