### ISSUE TITLE
Sverchok 2016 Reel Ideas

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#936]
@nortikin Maybe modeling generator tools like Blender Extra Objects, but presented really nicely. I know we have JSON stuff too and that needs to be shown in a nice way.

I will make a video just to talk about JSON export import.

I was surprised when first seeing JSON stuff and was intimidated. But after knowing how it works, I was very joyful.

**Comment by nortikin** [comment]
at beginning i thought of this templates autogenerators in 3d. So maybe will closely do somemenu for this

**Comment by zeffii** [comment]
2017

**Comment by enzyme69** [comment]
2017 is a time we redefine Sverchok. One should start by maybe procedurally
modeling insects or something. Someone needs to do it.
