### ISSUE TITLE
3pt Arc does not seem to work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#937]
![screen shot 2016-10-28 at 11 23 02](https://cloud.githubusercontent.com/assets/3952687/19790081/f5aaa926-9d00-11e6-8304-a58155cbff78.png)

Not showing up using Viewer node.

**Comment by enzyme69** [comment]
![screen shot 2016-10-28 at 11 25 00](https://cloud.githubusercontent.com/assets/3952687/19790104/300b2226-9d01-11e6-81c3-c6151177d791.png)

Oh.. minimum 3 vector points... my bad.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19801593/1d005a30-9d00-11e6-84df-103017d8ca96.png)

we could perhaps update those docs, include a nice template or something..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19802273/31c07146-9d03-11e6-8fd1-5b6f95ec3093.png)

https://gist.github.com/a3131c6417c2914088474c37f66900e4

**Comment by zeffii** [comment]
https://gist.github.com/f5d648a2cb987eff6ff1d55170e0aa2a

![image](https://cloud.githubusercontent.com/assets/619340/19803262/fc243c2a-9d07-11e6-9e15-366ed227e434.png)

**Comment by enzyme69** [comment]
Yes this Arc thing is awesome, so flexible, but so little known!!

**Comment by nortikin** [comment]
https://gist.github.com/nortikin/ffb5566e1ba7ecf2ecb7ca7edb96e571

**Comment by enzyme69** [comment]
Checking your GIST. Do you know that before I know the GIST, that link gave me no clue what it is. But you have provided examples all along. Thanks! I will have to find more gems in Sverchok thread. It's my ongoing study.

**Comment by enzyme69** [comment]
![screen shot 2016-10-29 at 09 49 59](https://cloud.githubusercontent.com/assets/3952687/19824648/15a85568-9dbd-11e6-8ecd-56534b457cee.png)

Nice looking shell~

**Comment by zeffii** [comment]
remember @enzyme69 , when you have the gist ID copied to clipboard, you can use the button with the _world icon_ to import directly (instead of pasting the gist ID into the textfield)
