### ISSUE TITLE
small bug cleanup

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#938]
i'm using the term "bug" lightly here, because as always the code is working exactly as written, perhaps with unintended side effects. there's a few more of these around, some of the booleans don't update immediately in other nodes. I've grown accustomed to the behaviour and click on the sockets of a node to force an update, but for new users who expect some different behaviour after setting a parameter -- this is not logical.

### Analyze

- [ ] colorsMK2  (use active ...)
  https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/colors2.py#L45-L47
- [ ] distance_pp.p    (Cross_dist )
  https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/distance_pp.py#L36-L37
- [ ] image decompose ( skip )
  https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/image_components.py#L222-L224
  the underlying code doesn't expect to update skip values at will, the image must be reinspected to do that. (won't fix)
- [ ] kdtree 1
  https://github.com/nortikin/sverchok/blob/master/nodes/analyzer/kd_tree.py#L37-L42
  someone stone me to death, what was I thinking when writing this node. (will rewrite)

### Modifier Change

- [x] Remove Doubles :  shouldn't make edgepol link mandatory
  Pull Request:  https://github.com/nortikin/sverchok/pull/1012

### Modifier Make

- [x] MeshJoin  :  shouldn't make edgepol link mandatory
    Pull Requestion:   https://github.com/nortikin/sverchok/pull/1013

### Matrix

- [ ] Matrix Apply to Mesh:  if this node has no edges input it shouldn't output edges, i think.. same for faces. Unless we want it to output edges as a feature, if just Faces are connected.

### nodeview space menu

- [x] error (not serious, but shouldn't happen)

   ```
   layout_params = dict(text=node_ref.bl_label, **icon(display_icon))
   AttributeError: type object 'NodeReroute' has no attribute 'bl_label'
   ```

**Comment by ly29** [comment]
No it is not, user exposed settings should always be using ```update=```

**Comment by zeffii** [comment]
i'll do a project wide grep for candidates and share them prior to implementating changes.. just no eta yet.

**Comment by ly29** [comment]
Sounds good 👍

**Comment by zeffii** [comment]
OK. i have the flu  so will pick off a few of these taks now...  https://github.com/nortikin/sverchok/pull/1012

**Comment by zeffii** [comment]
@ly29  

```
class SvSocketCommon:
    @property
    def other(self):
        return get_other_socket(self)

    def set_default(self, value):
        if self.prop_name:
            setattr(self.node, self.prop_name, value)


    @property
    def index(self):
        node = self.node
        sockets = node.outputs if self.is_output else node.inputs
        for i, s in enumerate(sockets):
             if s == self:
                 return i

    def sv_set(self, data):
        SvSetSocket(self, data)
```

how do you feel about adding a check either in `SvSetSocket` or inside `sv_set` , to check `socket.is_linked` . Would suppress plenty of print statements when sockets aren't connected but are passed data.

**Comment by ly29** [comment]
Well,  just remove the print statement or make it a debug option. 
For now comment it out.

**Comment by zeffii** [comment]
OK a debug option! 

else

```python
def sv_set(self, data, check_is_linked=False):
        if check_is_linked and not self.is_linked:
            return
        SvSetSocket(self, data)
```

**Comment by zeffii** [comment]
also.. list Zip maybe item 0 should be `data 0` 

![image](https://cloud.githubusercontent.com/assets/619340/20864971/85f7dc26-ba05-11e6-9eac-622938fe61ce.png)

**Comment by zeffii** [comment]
line evaluate
```
            for j in range(max_l):
                tmp_pts = [(Vector(VerticesA[i][j]).lerp(VerticesB[i][j], factor[i][k]))[:]
                           for k in range(len(factor[i]))]
                points_.extend(tmp_pts)
```
i think the awkward drop line in the for-loop hides an optimisation opportunity.

```
            for j in range(max_l):
                v1 = Vector(VerticesA[i][j])
                v2 = VerticesB[i][j]
                tmp_pts = [(v1.lerp(v2, f)[:]) for f in factor[i]]
                points_.extend(tmp_pts)
```

**Comment by zeffii** [comment]
or something like that , i've not tested it.

**Comment by ly29** [comment]
Some restructure to make it easier to follow might be in order yes
