### ISSUE TITLE
Dealing with Bones and Animating them

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#939]
In Sverchok world, do we have plan to actually works with Bones? Such as generating Bones (edit mode) and then posing bones using Math?

I am currently researching and studying using Animation Nodes script node. I really want to use Sverchok, but Sverchok script node is not like AN or I am just not familiar with it.

Currently in AN, it can access Object, and Armature is an object. Armature can have Bones and Bones have different state: Edit and Pose.
### BONE EDITING

Editing bone using Python and I can't get it to update somewhat.

```
>>> arm = bpy.data.armatures
>>> arm[0]
bpy.data.armatures['Armature']

>>> arm
<bpy_collection[1], BlendDataArmatures>

>>> arm[0].bones[0].head
Vector((0.0, 0.0, 0.0))

>>> arm[0].bones[0].tail
Vector((0.0, 0.0, 1.0))

>>> arm[0].bones[0].tail = 0,0,5
>>> 

# Bone is not updating
```
### Posing bone using Python is easier, below is such AN script that I want to replicate in Sverchok

```
# pose.bones["Bone.001"].location

myarmature = Object
# bpy.data.objects["Armature"]

mybones = bpy.data.armatures['Armature'].bones

for num, bone in enumerate(mybones):
    myarmature.pose.bones[bone.name].location = LocationList[num]
    myarmature.pose.bones[bone.name].scale = ScaleList[num]
```
### 

My confusion is currently:
I know I can get to the Object.
I don't know how to get from Object to Struct.
I don't know what Struct get and set is.
I understand attribute and parameter, if they are easily accessible via bpy.data. Sverchok GET and SET I would like to use, but in such a way that LOOPING, I don't know how to do it...

NOTE: Maybe this thread is confusing. But I just want to understand something.

**Comment by enzyme69** [comment]
I guess it's not so much of Sverchok question, unless SV dev can challenge using SV Script node.

**Comment by enzyme69** [comment]
Although...

What would be nice is if we have an easy way to turn Sverchok "Edges" into a single Armature with multiple Bones?

![screen shot 2016-10-30 at 16 38 48](https://cloud.githubusercontent.com/assets/3952687/19834710/73d10b96-9ebf-11e6-847f-586a1cd24de6.png)

It works with edges that are connected, via Skin Modifier and Make Armature button. But not working for Edges that are not connected?

**Comment by enzyme69** [comment]
![screen shot 2016-10-30 at 16 41 11](https://cloud.githubusercontent.com/assets/3952687/19834722/b0034f70-9ebf-11e6-993d-ef46a522eb13.png)

Hehehe... it's actually working this way :D

**Comment by enzyme69** [comment]
But this is when the fun overs... 

![screen shot 2016-10-30 at 16 42 57](https://cloud.githubusercontent.com/assets/3952687/19834727/f4cb6c6e-9ebf-11e6-8ced-cbedca1ca154.png)

Any idea or suggestion?

**Comment by enzyme69** [comment]
Maybe Blender Skin Modifier to Armature is not perfect.

![screen shot 2016-10-30 at 16 48 42](https://cloud.githubusercontent.com/assets/3952687/19834748/d3c36e08-9ec0-11e6-8677-4bded4096a1f.png)

Or maybe it is doing what it is intended to, converting the Skin Modifier into Armature, but it generates extra bones.

Kind of want a way to just convert Edges (connected or separate, multiple or single) into Bones.

What do you reckon?

**Comment by enzyme69** [comment]
I think it is actually Skin Mesher "gotcha" not a bug that causing the bone to have those unwanted extra bones during conversion from SV Skin to Armature.

Because if I just export out Edges (joined) from Sverchok and add Skin Modifier, and then manually Mark Root at the bottom edges, I am getting below:

![screen shot 2016-10-30 at 16 58 19](https://cloud.githubusercontent.com/assets/3952687/19834779/13c7a676-9ec2-11e6-8cf8-67ce70940023.png)

**Comment by zeffii** [comment]
In Sv Skin Mesher each vertex is automarked Root. I think you'd save yourself a lot of time if you started reading the source of these nodes.

https://github.com/nortikin/sverchok/blob/master/nodes/basic_view/viewer_skin.py#L260-L262

**Comment by zeffii** [comment]
it might make sense to add a _Roots_ socket, to set True/1 or False/0 in the form of a list which corresponds to each vertex. At the time I wrote that Node I wanted all to be roots.

regarding the ScriptNode _AN ->SV_ conversion. I don't know anything about AN's approach to Scripted Nodes. In SV we offer nested list interpretations, which means there's wrapping and indexing -- I think this is minimal boilerplate (but I am totally biased because I wrote most of SN1)

Until SV SNMK3 lands, you use something like this:

```python
def sv_main(locationList=[[]], scaleList=[[]]):
    non_out = []

    in_sockets = [
        ['v', 'locationList', locationList],
        ['v', 'scaleList', scaleList]
    ]

    OK = False
    if locationList and locationList[0]:
        if scaleList and scaleList[0]:
            OK = True
    
    if OK:
        myarmature = bpy.data.objects["Armature"]
        mybones = bpy.data.armatures['Armature'].bones

        for num, bone in enumerate(mybones):
            myarmature.pose.bones[bone.name].location = locationList[num]
            myarmature.pose.bones[bone.name].scale = scaleList[num]

    out_sockets = [
        ['v', 'dummyout', non_out]
    ]

    return in_sockets, out_sockets
```

**Comment by zeffii** [comment]
or i wonder if this works (snippet change)

```python
    if OK:
        mybones = bpy.data.armatures['Armature'].bones

        for num, bone in enumerate(mybones):
            bone.location = locationList[num]
            bone..scale = scaleList[num]
```

**Comment by enzyme69** [comment]
![screen shot 2016-11-01 at 19 32 47](https://cloud.githubusercontent.com/assets/3952687/19883728/fe44fc6e-a069-11e6-9d15-64f45ba15daa.png)

This is actually working great! I'll have to study this... Very interesting.

**Comment by enzyme69** [comment]
The Pose Bone works, but second script that accessing the Edit Bone directly does not work. Heard that it needs to go into the Edit Mode. This Bone situation is interesting, I tell you.

**Comment by zeffii** [comment]
I see, Edit Mode is needed for the second version? unfortunately my knowledge of _Armature_ is zero. The best people to write Nodes for this kind of stuff are those who use these Blender features in daily life.

**Comment by enzyme69** [comment]
Yeah... I started to realize. 

After all not everything can fit "30-60 minutes LIVE NODING". Only trivial stuffs... 

I was reading this:
http://blender.stackexchange.com/questions/3549/how-can-a-bones-tail-be-changed-by-a-script

I think it's good enough information for now. I am going to explore Armature further, hopefully it will get easier over time :] Probably bone is my most favourite area after all.
