### ISSUE TITLE
Group goes into Objects In Matrix does not update

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#940]
I have this setup of bunch of Cube objects, grouped, being sourced using Objects In node.

I use Matrix Out and want to get each and every object position per frame (changing).

Apparently it is not moving like expected. Sourcing one Cube works, 

![screen shot 2016-10-31 at 19 06 31](https://cloud.githubusercontent.com/assets/3952687/19847767/33f30158-9f9d-11e6-9694-df1f0acfe6e3.png)
![grouped_object_matrix_not_updating](https://cloud.githubusercontent.com/assets/3952687/19847768/33f3e5a0-9f9d-11e6-9c3e-01e54c4cf579.gif)

**Comment by enzyme69** [comment]
Actually.... after assigning Group,  Get Selection does it... weird.

**Comment by nortikin** [comment]
in preferences there is "enable live object in"  + in 3d view button-flag in sverchok panel 'Start live update'
Maybe by default we should activate it and store value at blend file + in json for export.
