### ISSUE TITLE
Case of Interpolating 2 Curves

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#944]
I have 2 Curves: Curve A and Curve B and I want to generate bunch of curves based on this two mix.

Perhaps I also want Curve C and D and have interpolation between those 4 curves.

I thought it will be as easy as using List Join and Vector Interpolation but I am not getting the result I wanted.

![screen shot 2016-11-02 at 15 30 05](https://cloud.githubusercontent.com/assets/3952687/19916771/70ace4a4-a111-11e6-876e-a56dd73087ad.png)

Will "Vector Interpolation" actually "blend shape" or "shape key" between 2 curves or maybe 2 surfaces?

Or Vector Interpolation is for a curve resampling only?

**Comment by enzyme69** [comment]
Oyeah, Vector Evaluate node... 

Suddenly it comes back:
http://blendersushi.blogspot.com.au/2014/07/sverchok-case-of-matryoshka-dolls.html

Never mind.

Is there "Surface Evaluate"?

**Comment by enzyme69** [comment]
Oyeah, Vector Evaluate node... 

Suddenly it comes back:
http://blendersushi.blogspot.com.au/2014/07/sverchok-case-of-matryoshka-dolls.html

Never mind.

Is there "Surface Evaluate"?

**Comment by nortikin** [comment]
flip list node will make it maybe better to handle
or zip node can do in this particular two-splines case
and than uvconnect in all the kind
