### ISSUE TITLE
3d voronoi

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#946]
lets grub it https://github.com/joe-jordan/pyvoro

**Comment by nortikin** [comment]
can we handle installing pip in background? `python setup.py install --user`
or user should himself?
better to make it in background somehow.

**Comment by zeffii** [comment]
I wonder how well that will work cross platform, I think pip is already installed with supplied Blender's Python.

Including an easy way to "on demand" include 3rd part libraries would be great, and open up a lot of interesting nodes..  (scipy would be great for many things also geometry )

Maybe a plugin system for Sverchok. less impact into the base-sverchok.

**Comment by nortikin** [comment]
good think of plugins. 
`want, can, make`

**Comment by enzyme69** [comment]
​Waiting in anticipation....

**Comment by enzyme69** [comment]
@nortikin have you checked Houdini's 3D Voronoi? Sverchok needs point scatter first maybe. 3D and 2D (surface) point scatter. It can be from Blender Particles. But can Sverchok natively load Particles?

**Comment by nortikin** [comment]
scripted node for particles now.

**Comment by nortikin** [comment]
ok, i commited new particles node into stripes node branch. If i make vectorization now, will merge to master

**Comment by nortikin** [comment]
ok, merged, use new alpha node "particles"

**Comment by enzyme69** [comment]
Tested the Particle node, sweet so it reads positions for 1 selected object.

**Comment by nortikin** [comment]
sweet, yeah

**Comment by nortikin** [comment]
why we talking here? no place for particles.

**Comment by nortikin** [comment]
random vector node i also available @enzyme69

**Comment by nortikin** [comment]
http://stackoverflow.com/questions/8400382/python-pip-silent-install
answer for my question is "yes always".

**Comment by nortikin** [comment]
than we can make virus and install it silently, ok.

**Comment by zeffii** [comment]
I'm looking at Qhull (cross platform used by the Grasshopper voronoi node if i'm not mistaken ) .  Not sure how fast it is but it takes input from `stdin` and outputs the result to `stdout`. Can imagine a node that takes a snapshop of current input, executes the binary (if found) , then stores the result and sets that as the socket output, until the user manually updates.

**Comment by nortikin** [comment]
The source code runs in 2-d, 3-d, 4-d, and higher dimensions. (sick!!! :smiling_imp: )

**Comment by nortikin** [comment]
for unix it has to be compiled anyway

**Comment by zeffii** [comment]
for win64 too :/

**Comment by nortikin** [comment]
Think, we have to use pyvoro somehow. because it acts from python directly. Will have time - will give a try for both.
Asked question in vk group, maybe someone have ready solution...

**Comment by zeffii** [comment]
https://github.com/PMEAL/OpenPNM-Examples/blob/master/Topology/generate_voronoi_network.md

**Comment by zeffii** [comment]
https://openmaya.quora.com/How-to-implement-Voronoi-with-Python-for-Maya

**Comment by nortikin** [comment]
scipy needed?

**Comment by zeffii** [comment]
if blender came with scipy.. oh man...

**Comment by nortikin** [comment]
will prey in evening for scipy in blender

**Comment by nortikin** [comment]
https://spacesymmetrystructure.wordpress.com/2009/10/05/medial-axes-voronoi-skeletons/
nice analized node

**Comment by enzyme69** [comment]
​This should be perfect for skeleton generation. I think.

**Comment by zeffii** [comment]
The open maya code above, essentially does this (with some extra tuning by me) - Read it above.
might be interesting for you to try converting maya python to bpy @enzyme69 .

I started here a partial non-working implementation. https://gist.github.com/zeffii/f5d683e301a39610f65069c001c49753

**Comment by enzyme69** [comment]
I think it's time for me to dig into codes more seriously. Thanks Zeffii. Time for me to source some Maya codes.

**Comment by enzyme69** [comment]
@zeffii I looked into the code, test it in Maya. Interestingly why the code is "so simple". Are we using the Bisect operation (equivalent to Maya Cut Plane Tool)? 

In a way, we could build Script node that does the "ninja cutting" thing?

**Comment by zeffii** [comment]
Yep bmesh bisect Will a wrapper to return the geometry of both parts of a sliced element as two unique elements. I didn't get much time yesterday or today

**Comment by enzyme69** [comment]
In the mean time I made this setup with Bisects...
https://gist.github.com/bffb7f0c2343c9274ab93dec0d119b44
![screen shot 2016-12-09 at 17 26 24](https://cloud.githubusercontent.com/assets/3952687/21039796/ab320cf4-be34-11e6-8453-d69fc9a58867.png)

It become a separate question:
https://github.com/nortikin/sverchok/issues/1030

**Comment by nortikin** [comment]
https://gist.github.com/064f2db1317be9541b4f99ae4bd140e7
MY experiment.

**Comment by zeffii** [comment]
here is the wrapper, i have yet to try it
```python
from sverchok.utils.sv_bmesh_utils import pydata_from_bmesh, bmesh_from_pydata

def chop(mesh, normal, point):
    '''
    not an optimal implementation, but simple enough to be educational.s

    input:
        takes a (what it assumes is) a closed mesh as input
    outputs: 
        a collection of vert, edge, face lists, that hold 2 sublists each
        one for each section / bisection.

    '''
    verts, edges, faces = mesh
    verts_list, edges_list, faces_list = [], [], []
    vap = verts_list.append
    eap = edges_list.append
    fap = faces_list.append

    def inject_mesh(bm):
        v, e, f = pydata_from_bmesh(bm)
        vap(v)
        eap(e)
        fap(f)

    def wrev(n):
        d = n[0]*2, n[1]*2, n[2]*2
        return n[0]-d[0], n[1]-d[1], n[2]-d[2]


    for n in [normal, wrev(normal)]:
        bm = bmesh_from_pydata(verts, edges, faces)
        geom_in = bm.verts[:] + bm.faces[:]
        bmesh.ops.bisect_plane(
            bm, geom=geom_in, dist=0.00001,
            plane_co=point, plane_no=n, use_snap_center=False,
            clear_outer=True, clear_inner=False
        )

        inject_mesh(bm)
        del bm

    return verts_list, edges_list, faces_list
    
```

**Comment by zeffii** [comment]
now some recursion or iteration : )

**Comment by zeffii** [comment]
rather than picking a random vector as a slice-plane, a solution is to use a relation to the shortest dimension of the bounding box of the input mesh. (not implemented in my code, this can be done later)

**Comment by zeffii** [comment]
```python
"""
in verts v  d=[[]] .=1
in faces s  d=[[]] .=1
in seed  s  d=0    .=2
out verts_out v
out faces_out s
"""
import random
from random import random as rnd
from chop_module import chop, average

iteration = 6
verts_out = []
faces_out = []

random.seed(seed)

def recurse_chop(iteration, verts, faces):
    
    if iteration == 0:
        return

    mesh = verts, [], faces
    normal = rnd(), rnd(), rnd()
    point = average(verts)
    v, _, f = chop(mesh, normal, point)
    
    verts_out.extend(v)
    faces_out.extend(f)

    for _v, _f in zip(v, f):
        recurse_chop(iteration-1, _v, _f)        


recurse_chop(iteration, verts, faces)

verts_out = verts_out[2:]
faces_out = faces_out[2:]
```

almost there, but the recursion still includes the slices before being sliced...  
recursion gives me a headache sometimes :)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21074120/8a42b1ee-bef0-11e6-915c-f464bf7e01c3.png)

**Comment by zeffii** [comment]
this is as far as i can take this conversion for maya script to bpy, i'm not sure (without reading the docs for the maya polyCut ) -- for a later date..

```python
"""
in numPoints s   d=20   n=2
in Size      s   d=10   n=2
out vert_list  v 
out face_list  s 
"""
from mathutils import Vector
import numpy as np
from sverchok.utils.sv_bmesh_utils import bmesh_from_pydata, pydata_from_bmesh
import bmesh
import random
import math

cmds = {'locator': [0,0,0]}

class MBoundingBox:

    def __init__(self, vectors):
        self.xyz = np.array(vectors)
        self.add_all()

    def add_all(self):
        x = self.xyz[:,0]
        y = self.xyz[:,1]
        z = self.xyz[:,2]

        self.width = max(x) - min(x)
        self.depth = max(y) - min(y)
        self.height = max(z) - min(z)
        self.center = (
            min(x) + (self.width / 2),
            min(y) + (self.depth / 2),
            min(z) + (self.height / 2)
        )

def get_vps(numPoints, Size):
    x = [random.uniform(-10,10) for i in range(numPoints)]
    y = [random.uniform(-10,10) for i in range(numPoints)]
    z = [random.uniform(0,10) for i in range(numPoints)]
    return list(zip(x,y,z))


def polyCube(width, height, depth):
    w = width/2
    h = height/2
    d = depth/2
    verts = [(w, h, -d), (w, -h, -d), (-w, -h, -d), (-w, h, -d),
             (w, h, d), (w, -h, d), (-w, -h, d), (-w, h, d)]

    faces = [(0, 1, 2, 3), (4, 7, 6, 5), (0, 4, 5, 1), (1, 5, 6, 2),
             (2, 6, 7, 3), (4, 0, 3, 7)]

    return bmesh_from_pydata(verts, [], faces)

def duplicate(bm):
    return bm.copy()


def draw_3d_voronoi(numPoints, Size):
    vert_list, face_list = [], []
    vps = get_vps(numPoints, Size)
    bb = MBoundingBox(vps)
    
    startCube = polyCube(width=bb.width*1.2,height=bb.height*1.2,depth=bb.depth*1.2)
    # cmds.move(bb.center[0], bb.center[1], bb.center[2])  # not sure what its for..
    
    for from_point in vps:
        working_geom = duplicate(startCube)
        for to_point in vps:
            if from_point != to_point:              
                
                cmds['locator'] = from_point[0], from_point[1], from_point[2]
                # cmds.parent(locator, working_geom)
                
                center_point = [(e1 +e2) / 2 for (e1, e2) in zip(to_point, from_point)]
                n = [(e1-e2) for (e1,e2) in zip(from_point,to_point)]
                
                # es = cmds.angleBetween(euler=True, v1=[0,0,1], v2=n)
                es = Vector((0,0,1)).rotation_difference(Vector(n)).to_euler()[:3]
 
                # cmds.polyCut(working_geom, deleteFaces=True, 
                #              cutPlaneCenter=center_point, cutPlaneRotate=es)
                geom_in = working_geom.verts[:] + working_geom.edges[:] + working_geom.faces[:]
                res = bmesh.ops.bisect_plane(
                    working_geom, geom=geom_in, dist=0.00001,
                    plane_co=center_point, plane_no=es, use_snap_center=False,
                    clear_outer=False, clear_inner=False
                )

                # cmds.polyCloseBorder(working_geom)
                # lifted from bisect
                surround = [e for e in res['geom_cut'] if isinstance(e, bmesh.types.BMEdge)]
                fres = bmesh.ops.edgenet_prepare(working_geom, edges=surround)
                bmesh.ops.edgeloop_fill(working_geom, edges=fres['edges'])  

        v, e, f = pydata_from_bmesh(working_geom)
        vert_list.append(v)
        face_list.append(f)

    del startCube
    return vert_list, face_list

vert_list, face_list = draw_3d_voronoi(numPoints, Size)
```

**Comment by enzyme69** [comment]
![screen shot 2016-12-11 at 23 10 23](https://cloud.githubusercontent.com/assets/3952687/21079974/04a4a364-bff7-11e6-85c6-7042274f28fc.png)
Chop module json load error :(

**Comment by enzyme69** [comment]
Actually, I got it:
- chop_module.py from GIST into my Blender folder.
- load it, all good.

![screen shot 2016-12-11 at 23 16 27](https://cloud.githubusercontent.com/assets/3952687/21080000/eb35f814-bff7-11e6-8811-608bc5b81dd2.png)

Voronoi 3D is such complex.

**Comment by zeffii** [comment]
i'm probably close to the final code with this https://github.com/nortikin/sverchok/issues/946#issuecomment-266233947

but small differences details are making a big difference. anyway, i don't have maya to cross check, and don't have time for this.

**Comment by enzyme69** [comment]
Interestingly, it's almost similar to the result I am getting with stone carving... (still nope)
https://github.com/nortikin/sverchok/issues/1031

**Comment by zeffii** [comment]
http://www.gdmc.nl/publications/2007/Computing_3D_Voronoi_Diagram.pdf time for a read

**Comment by enzyme69** [comment]
Check this one out: there is Voronoi PY
https://github.com/njanakiev/blender-scripting-intro

**Comment by zeffii** [comment]
@enzyme69 yes, the technique he uses is mentioned above. Not sure we can bundle scipy with sverchok..in a sane way.

**Comment by zeffii** [comment]
three SN lites ..

**voronoi**
```python
"""
in points v d=[[]] n=1
out verts v
out edges s
out polygons s
"""
import numpy as np
import sys

scipy_path = r"C:\Users\zeffi\Anaconda3\Lib\site-packages"
if not scipy_path in sys.path:
    sys.path.append(scipy_path)    

import scipy
from scipy.spatial import Voronoi

if points:
    vor = Voronoi(points)
    # print(vor.regions)
    # print(vor.vertices)
    # print(vor.ridge_points)
    # print(vor.ridge_vertices)
    # print(vor.points)
    # print(vor.point_region)

    edges = []
    polygons = [[e for e in vor.ridge_vertices if not -1 in e]]
    verts = [vor.vertices.tolist()]
```

**3d grid**
```python
"""
in xdim s d=3 n=2
in ydim s d=3 n=2
in zdim s d=3 n=2
in size s d=1.0 n=2
out verts v
"""

import numpy as np

verts = []
hs = size/2
x_ = np.linspace(-hs, hs, xdim)
y_ = np.linspace(-hs, hs, ydim)
z_ = np.linspace(-hs, hs, zdim)
f = np.vstack(np.meshgrid(x_,y_,z_)).reshape(3,-1).T
f = f.tolist()
verts.append(f)
```
and **rm doubles (Fast)**
```python
"""
in prelim_verts   v  d=[[]] .=1
in reject_radius  s  d=0.65 .=2
out verts v
"""
from random import random as rand
from math import sqrt, cos, sin, pi as M_PI
import bmesh

verts = []

def remove_doubles(vertices, d):
    bm = bmesh.new()
    bm_verts = [bm.verts.new(v) for v in vertices]

    bmesh.ops.remove_doubles(bm, verts=bm_verts, dist=d)
    bm.verts.index_update()

    verts = [vert.co[:] for vert in bm.verts[:]]
    bm.clear()
    bm.free()
    return verts

verts = [remove_doubles(prelim_verts, reject_radius)]
```
![image](https://cloud.githubusercontent.com/assets/619340/21119270/25174630-c0c2-11e6-917e-1062f6fafc9e.png)

**Comment by zeffii** [comment]
[scipy_voroi_2016_12_12_22_27.zip](https://github.com/nortikin/sverchok/files/647412/scipy_voroi_2016_12_12_22_27.zip)

**Comment by enzyme69** [comment]
I will give a try!

**Comment by enzyme69** [comment]
![screen shot 2016-12-13 at 17 55 32](https://cloud.githubusercontent.com/assets/3952687/21130541/60f0f7dc-c15d-11e6-8ae2-d73da997debe.png)

I only need to change this to enable SCIPY....! This is powerful!

scipy_path = r"/Users/jimmygunawan/anaconda/envs/py35/lib/python3.5/site-packages"

**Comment by enzyme69** [comment]
I tried piping points scattered inside a Torus and get something like below:

![screen shot 2016-12-13 at 19 26 39](https://cloud.githubusercontent.com/assets/3952687/21132846/36b6f306-c16a-11e6-8db8-28ac23ddacef.png)

Similar to 2D Voronoi, we have this "exra stuff" outside the boundary that spiking out.

**Comment by zeffii** [comment]
@enzyme69   ok, maybe we can make a new field inside the user preferences for people to place the location of their `site-packages` folder - at some point. 

in the meantime i think we can explore what others have done with scipy's voronoi and tame it a little.

**Comment by enzyme69** [comment]
![screen shot 2016-12-14 at 09 35 56](https://cloud.githubusercontent.com/assets/3952687/21162289/c1108668-c1e0-11e6-8f8c-233a36cf1738.png)
![screen shot 2016-12-14 at 09 35 42](https://cloud.githubusercontent.com/assets/3952687/21162287/c10dff7e-c1e0-11e6-9eec-51decf6282c8.png)
![screen shot 2016-12-14 at 09 27 56](https://cloud.githubusercontent.com/assets/3952687/21162288/c10fb6e8-c1e0-11e6-9ac7-004e474fbf85.png)

Omar is testing the Voronoi 3D thing using AN.

**Comment by zeffii** [comment]
voronoi returns a list of the 4 closest points and their distances ( the function yields 
```
[dddd,vvvv,dddd,vvvv,......]
```
snlite
```python
"""
in position_list v d=[] n=1
in distance_metric s d=0 n=2
in exponent s d=2.5 n=2
out points v
"""

import bpy
from mathutils.noise import voronoi

# mode_list = "CHEBYCHEV DISTANCE DISTANCE_SQUARED MANHATTAN MINKOVSKY MINKOVSKY_FOUR MINKOVSKY_HALF".split(' ')

points = [[]]
add_point = points[0].append
distance_metric %= 7

for p in position_list:
    for idx, pt in enumerate(list(voronoi(p, distance_metric, exponent))):
        if (idx % 2) == 1:
            for x in pt:
                add_point(x[:])
                
```
