### ISSUE TITLE
Multi Lines + Noise + (Missing Seed) + Falloff

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#949]
Trying to do this kind of effects, but I think there is something off with my approach. I don't like how it gets convoluted with Range Float. And also Noise that we have does not have Seed at the moment.

https://gist.github.com/abe29772f7891bc949565d3a0a49d749
![screen shot 2016-11-05 at 19 10 05](https://cloud.githubusercontent.com/assets/3952687/20028650/dcaf003e-a38b-11e6-810d-bb312e7c1a60.png)

TARGET:
![wave](https://cloud.githubusercontent.com/assets/3952687/20028646/c8a84e1a-a38b-11e6-9a5b-e09f4dcb8546.gif)

**Comment by zeffii** [comment]
try harder.

**Comment by zeffii** [comment]
it's a good one!

**Comment by enzyme69** [comment]
At the moment, I know I am only wiggling the points. I can use Planes or Multiple Lines. I will switch to Plane.

The above effect needs:
- sliding noise
- falloff

**Comment by enzyme69** [comment]
I found that this is weird that I am not getting anything if I tried to Add these 2 Vectors.

![screen shot 2016-11-05 at 21 45 27](https://cloud.githubusercontent.com/assets/3952687/20029483/3b0bce72-a3a1-11e6-9966-c17129311a0e.png)

**Comment by enzyme69** [comment]
I know I can "slide" this way, for Sine:

![screen shot 2016-11-05 at 21 49 19](https://cloud.githubusercontent.com/assets/3952687/20029503/c5a3b84c-a3a1-11e6-9f31-625752918099.png)

**Comment by enzyme69** [comment]
But doing like above, I cannot use UV Connection.

**Comment by enzyme69** [comment]
Found this formula:
float AffectRegionFunction(float dist, float falloff,float pinch, float bubble)
{
float u = ((falloff - dist)/falloff);
float u2 = u*u, s = 1.0f-u;
return (3*u*bubble*s + 3*u2*(1.0f-pinch))*s + u*u2;
}

**Comment by enzyme69** [comment]
Manual way using Displace Modifier and Weighting seems more straight forward... and I can slide the Texture Displacement.

![screen shot 2016-11-05 at 22 03 52](https://cloud.githubusercontent.com/assets/3952687/20029583/d0572d44-a3a3-11e6-9274-6e292ba0dc68.png)

With thing like this, if I use semi-Sverchok kind of way, all I want to do next is to turn this grid into UV either in U or V lines only. But not sure how.

**Comment by enzyme69** [comment]
I supposed to know this by now. But well, got confused still.

![screen shot 2016-11-05 at 22 14 45](https://cloud.githubusercontent.com/assets/3952687/20029632/51eeb0a6-a3a5-11e6-923b-debd57fc1522.png)

![screen shot 2016-11-05 at 22 15 54](https://cloud.githubusercontent.com/assets/3952687/20029635/72464300-a3a5-11e6-91db-316dac54d0f4.png)

Blender Modifier is scrambling the Index, that's why.

**Comment by enzyme69** [comment]
Using default Grid, I can get a nice line, but looks like Subdivide Modifier is screwing the Index Sort and I am no longer able to get a nice U or V lines.

![screen shot 2016-11-05 at 22 24 58](https://cloud.githubusercontent.com/assets/3952687/20029671/cae5f694-a3a6-11e6-919b-a8a8865b8c55.png)
![screen shot 2016-11-05 at 22 24 54](https://cloud.githubusercontent.com/assets/3952687/20029672/cae5f18a-a3a6-11e6-9bd4-e84ab8fb4404.png)

**Comment by enzyme69** [comment]
I realized the Displacement Modifier and moving Locator is also only giving "Wiggle", not sliding.

![line_noise](https://cloud.githubusercontent.com/assets/3952687/20029692/80007cde-a3a7-11e6-9419-7aa6303ad2dd.gif)

Back to zero....

**Comment by enzyme69** [comment]
Yeah, I don't know the Sliding thing needs a Noise function that takes a Float value like the Sine.

![line_noise2](https://cloud.githubusercontent.com/assets/3952687/20029717/527e1234-a3a8-11e6-907b-d43c3dca03e2.gif)

For that I think we need Script node.

**Comment by enzyme69** [comment]
Figured out swimming sliding noise, but why so complicated... 🤷🏼‍♂

https://gist.github.com/d9e3ee4571e9e9ea9ccf6e6c315d2edf

![line_noise3](https://cloud.githubusercontent.com/assets/3952687/20029799/5c37546e-a3aa-11e6-8493-5c9a00e5a71a.gif)

**Comment by enzyme69** [comment]
https://gist.github.com/6f457e0121576fc29a34263fa1c61bc7

![line_noise5](https://cloud.githubusercontent.com/assets/3952687/20029855/b634b1ae-a3ab-11e6-8e52-6ebfe2e8a98e.gif)

I think kind of 60% there.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20032608/06044f6e-a38e-11e6-9468-3747972fa0c2.png)
https://gist.github.com/4df5e0b6348fee7ac580359062e9d9bd

far from being a good recreation.

**Comment by zeffii** [comment]
good opportunity to test snlite..
```python
"""
in verts v .=[] n=0
in shift s .=[] n=2
out verts v
"""

Verts = []

mod_items = len(verts[0])

for vli in verts:
    zsh = []
    for idx, v in enumerate(vli):
        zsh.append((v[0], v[1], vli[(idx+shift) % mod_items][2]))
    Verts.append(zsh)

verts = Verts
```
shifts the Z position of each vertex list ..

**Comment by zeffii** [comment]
lol. yes, the whole thing could be written with a single script node, probably in less than 15 lines..
![image](https://cloud.githubusercontent.com/assets/619340/20033370/392b386a-a39f-11e6-9dcc-588def6de549.png)

**Comment by zeffii** [comment]
![droop](https://cloud.githubusercontent.com/assets/619340/20033444/c748772e-a3a0-11e6-8c95-c3e438933720.gif)

**Comment by enzyme69** [comment]
I will let this sinked in for a few days.
