### ISSUE TITLE
Chaining Matrix ala AN (not Mixing!)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#951]
![screen shot 2016-11-07 at 19 59 42](https://cloud.githubusercontent.com/assets/3952687/20051778/e05ac7e6-a524-11e6-97e1-3220da69bfcb.png)

I want to Mix Matrix together, like in this case, I am doing this Sine Hip motion, side to side and twist to twist, I was wondering if Matrix Mixing in Sverchok is similar to AN, and using Joint List, I thought that I would get the result of object being transform, but apparently not (?)

![mixing_matrix_transform](https://cloud.githubusercontent.com/assets/3952687/20051825/1acb1192-a525-11e6-9394-19fbd3eff903.gif)

**Comment by enzyme69** [comment]
Unless I am doing it like this using Apply Matrix, one by one.

![screen shot 2016-11-07 at 20 06 56](https://cloud.githubusercontent.com/assets/3952687/20051977/db7e7ba4-a525-11e6-8214-dd3ee02c1381.png)


Is it possible though to have "List of Matrix Transform" and tell Sverchok to apply it in order in one go?

**Comment by enzyme69** [comment]
I just realized Sverchok can do this too... hmm...

https://gist.github.com/a09e4a1067152e0bfa7a280cbb275931

**Comment by enzyme69** [comment]
Anyway, this is not right, isn't it?

https://gist.github.com/ca6a52f15ebcec9f42afa280ba755f82

Kind of thinking:

Object
Transform A - rotate in X
Transform B - rotate in Z

**Comment by zeffii** [comment]
mxing / interpolation a matrix is different than applying various transforms to consecutive matrices..

**Comment by zeffii** [comment]
>  Is it possible though to have "List of Matrix Transform" and tell Sverchok to apply it in order in one go?

I don't think we have such a node, i recall contemplating making one a while back.. let's see if i can find the thread..

**Comment by zeffii** [comment]
a more descriptive name for the feature is `chained transforms`

**Comment by enzyme69** [comment]
https://gist.github.com/9f5ca40fe2f68acdf722b4c4af4b4684

![hip_cycle_001](https://cloud.githubusercontent.com/assets/3952687/20052490/54a7bcf0-a528-11e6-9724-2251663a2941.gif)

I see... right, I think I can use "Apply Matrix" multiple times. Should be ok.

**Comment by enzyme69** [comment]
Kind of working, so I think I can close this. Unless anything can be added.
