### ISSUE TITLE
Separate Loose Part Output Matrix (Request)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#952]
The other day I was using Pipe and Separate Loose Part to do segmented tail or snake like creature. I realized the need to have Matrix Output List from thing like Pipe or Separate Loose Part. Is this already possible in any way?

**Comment by enzyme69** [comment]
By the way, Pipe - Bake Button will also causing crash.

**Comment by enzyme69** [comment]
I think I can use Place Objects On Edge... that works REALLY well, whoever developed it, I treat you dinner / coffee/ beer.

**Comment by zeffii** [comment]
zip a blend and drag it into an issue, if you want us to reproduce a bug.

**Comment by enzyme69** [comment]
baking anything from Line > Pipe node crashes my Blender each time. wonder
if that is meant to be like that.

**Comment by zeffii** [comment]
ok :) I can confirm that that does crash blender.

**Comment by zeffii** [comment]
https://gist.github.com/d066ed12c291dfdf43ded579e3d0c17a

**Comment by zeffii** [comment]
that gist shows there's a situation where negative indices are generated..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20094783/1270d3aa-a5a3-11e6-9acc-9852fc31684b.png)

**Comment by zeffii** [comment]
that's a valid bug , so i made a new issue for it. https://github.com/nortikin/sverchok/issues/953
