### ISSUE TITLE
INSPIRATION: Houdini Game Engine Example

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#957]
Houdini, the big brother of Node-Based system, showcase this game production example, I think it's quite inspiring and I will attempt to do something similar.
https://www.youtube.com/watch?v=V-Zar-bXF08

Sverchok, at this stage must be already able to help with generative creations such as:
- Bridge
- Island
- Fences
- Vines
- Placement of Poles
- Buildings
- Street

Not everything needs to be nodes, in fact a bit of human touch is always good. Such as in the above example, the guy made a wood, and then put the pieces into element for floors.

**Comment by enzyme69** [comment]
Might check BlendSwap or places to get this "elements"

**Comment by enzyme69** [comment]
Something like this:
http://www.blendswap.com/blends/view/84455

**Comment by nortikin** [comment]
@enzyme69 yes, pavel is great modeller and man at all!
i have bridges already
will make it as template soon.

**Comment by nortikin** [comment]
https://yadi.sk/i/Dx-ZWCbFcbdUR
@enzyme69

**Comment by nortikin** [comment]
https://yadi.sk/d/Dc2dnhwSyM9eJ
@enzyme69 
you the first i send this file or second. Will share it in templates ASAP.

**Comment by nortikin** [comment]
https://gist.github.com/1436cdc9d8d430ba26e5cbeb72e30a36
@enzyme69 additionally for your Paul Kotelevets python theme.
sverchok node tree that explanes himself i think

**Comment by enzyme69** [comment]
@nortikin Do we have Super Formula in Sverchok already?

**Comment by enzyme69** [comment]
More inspiration...
http://marctenbosch.com/news/2016/11/spherinder-grove-video/

**Comment by enzyme69** [comment]
And... this Super Formula stuff I kind of wanted to explore it using Sverchok, IF not already :
https://www.youtube.com/watch?v=_RDacUeBIKo

**Comment by enzyme69** [comment]
I'll have a study, thanks Nortikin!

**Comment by enzyme69** [comment]
![screen shot 2016-11-11 at 16 56 52](https://cloud.githubusercontent.com/assets/3952687/20205809/effde63e-a82f-11e6-804e-a3b755b3b687.png)

Super Formula :D just ported that one from the Houdini video tutorial example.

**Comment by nortikin** [comment]
you sayed will post script in github?

**Comment by enzyme69** [comment]
@nortikin at GITS? one sec, almost forgot

**Comment by enzyme69** [comment]
Script node:
https://gist.github.com/enzyme69/101eb120edfb8c41df16a7cd1a58c962

JSON:
https://gist.github.com/enzyme69/acdae761df4d441602c68c14aafaa6e9

It's very basic.

**Comment by enzyme69** [comment]
@nortikin Thanks for that Polar Coordinates example, I am shocked. So many good nodes!
