### ISSUE TITLE
Viewer Index, baking Text

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#958]
I am testing a simple basic CSV to visualization of Line Graph.

I manage to get the Text to show up via Viewer Index, which is nice. But when I hit Bake, it complained. Something about Align.

![screen shot 2016-11-11 at 21 57 46](https://cloud.githubusercontent.com/assets/3952687/20212961/274a341a-a85a-11e6-9624-e1cdec1f26ac.png)

**Comment by enzyme69** [comment]
![screen shot 2016-11-11 at 22 00 29](https://cloud.githubusercontent.com/assets/3952687/20212994/4873f22a-a85a-11e6-8ee2-2c566fe45aae.png)

**Comment by enzyme69** [comment]
TEXT CSV

apple,pineapple,orange,durian
10,5,3,5
3,8,3,1
2,6,7,5
6,6,3,4
8,2,10,8

**Comment by enzyme69** [comment]
https://gist.github.com/29a7d84d637e461ca9e4ba3121ebc181

**Comment by nortikin** [comment]
made it. git pull new one

**Comment by enzyme69** [comment]
Eeh, what is "git pull new one"

Check new version?

**Comment by nortikin** [comment]
download and replace sverchok master

**Comment by nortikin** [comment]
git pull is command for git repository to upgrade sverchok with git

**Comment by nortikin** [comment]
or replace one file of viewer inds

**Comment by enzyme69** [comment]
Should I just wait until I can hit button?

**Comment by enzyme69** [comment]
My version 0.5.7 is latest.

What's the full command of git pull

**Comment by nortikin** [comment]
ok, now hit upgrade button

**Comment by enzyme69** [comment]
![screen shot 2016-11-12 at 17 51 47](https://cloud.githubusercontent.com/assets/3952687/20236201/bfa43034-a900-11e6-8dfa-c582ae76cbca.png)
Ok seems to work, but if possible the Text Fill needs to set to "Both" instead of "None" as default, otherwise the Text is invisible :D

**Comment by zeffii** [comment]
The show Bake UI feature could have another option to choose between `Both` or `None`. I think the default None was chosen because the text outlines were intended for a CNC router..

http://midnightoilworkshop.com/img/CutVinyl/VT_13.jpg

**Comment by zeffii** [comment]
The typography node was started to allow more comprehensive font features, I think it's a mistake to add more features to the IndexViewer (but a choice between Both or None isn't really a big deal).

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20238939/1dde7890-a8f6-11e6-8002-82382dc92704.png)

**Comment by zeffii** [comment]
not sure if gist stores this correct
https://gist.github.com/3b01b62a85365e016677ad8e72fd656a

**Comment by zeffii** [comment]
( it doesn't )

**Comment by zeffii** [comment]
this will load. (slight manual edit to the json)
https://gist.github.com/zeffii/812ae3445fbe60fc09ad230b1ed50261

**Comment by zeffii** [comment]
requires another update to load that file.

**Comment by zeffii** [comment]
seen as the bug originally reported has been resolved, this should be closed. The feature request is separate.
