### ISSUE TITLE
INSPIRATION: Pocky Stick 3D Stucture - Edge and Expand

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#959]
Currently there is this Japanese company doing clever advertisement using 3D Pocky Sticks. Let's make some using Sverchok!
https://twitter.com/PASSO1031/status/797086076993093633

Nortikin, do you have idea on how to make this kind of 3D Stucture, kind of separating edges into separate and then extending the edges slightly? AN has this node that separate all edges.

First, we need a very good realistic Pocky model, should not be hard.

![pocky_inspiration](https://cloud.githubusercontent.com/assets/3952687/20233982/c07e11be-a8c9-11e6-91bb-6e95dd9b10e3.jpg)

**Comment by enzyme69** [comment]
![screen shot 2016-11-12 at 20 59 30](https://cloud.githubusercontent.com/assets/3952687/20237019/efc87b2a-a91a-11e6-9633-f21b91176ae8.png)
![screen shot 2016-11-12 at 20 59 26](https://cloud.githubusercontent.com/assets/3952687/20237020/f02686ac-a91a-11e6-9a31-18da68d0d383.png)

Currently using Animation Nodes to turn all Edges into separate edges. Can we have node like this in Sverchok or maybe there is a way to actually separate all edges?

Sorry if it has been asked before, maybe similar to separate all polys?

And also I wanted to find the center of each edge to scale them separately.

I should know this already... 

Thinking...

**Comment by enzyme69** [comment]
Weird, I asked something similar:
https://github.com/nortikin/sverchok/issues/196

But no solution or any info.

Polygon to Edges... supposedly separating edges? @nortikin

**Comment by enzyme69** [comment]
![screen shot 2016-11-12 at 21 11 10](https://cloud.githubusercontent.com/assets/3952687/20237086/9cbce1b2-a91c-11e6-8d9a-dd074320ef6a.png)

Ok, don't care I will use AN to turn polygon into all separate edges.

Now, the next thing is the center pivot of each Pocky Stick. I am so close... But this confuse me unless there is a way to get the pivot of edges node, or maybe a way to process each and every 12 edges:
- each edge should have 2 points, and I need to find middle point.

Using AN, I probably will think: ok make a LOOP that process each 12 edges, each has vector A and vector B, find the half way vector in 3D world position somewhat.

But using Sverchok, I am stuck currently.

**Comment by enzyme69** [comment]
This is so elementary, but I cannot do :(

http://stackoverflow.com/questions/522088/position-between-two-points

**Comment by enzyme69** [comment]
AHA! I figured it out...

![screen shot 2016-11-12 at 21 16 43](https://cloud.githubusercontent.com/assets/3952687/20237111/58b7c8f0-a91d-11e6-90cd-6ca8599df6e2.png)
![Uploading Screen Shot 2016-11-12 at 21.16.39.png…]()

**Comment by enzyme69** [comment]
Now... all edges separate, I know the center point, can scale. Is it possible to make every Edge the same length? ... Hmmm....

**Comment by enzyme69** [comment]
Probably the "easiest" to make every Edge the same length is to replace every edge with another Unit Edge.

Adaptive Edge, is too adaptive, it changes the length.

Actually it's pretty close, I just need a good way to replace this "Curve" with hole on top and bottom, with a better model.

![screen shot 2016-11-12 at 21 53 35](https://cloud.githubusercontent.com/assets/3952687/20237322/b2eed480-a922-11e6-9e0e-26e83ae628f3.png)

**Comment by enzyme69** [comment]
This is such a good procedural exercise... In fact even the Cycles shader texturing and thinking about making the rounded edges, closing the hole is a fun research.

Everything fits. Almost. 

Closing hole, Sverchok needs to add this option somewhat.
http://blender.stackexchange.com/questions/45755/working-with-bezier-curve-i-need-to-fill-the-hole-at-the-end

I ended up scripting that bit.

![screen shot 2016-11-12 at 22 37 18](https://cloud.githubusercontent.com/assets/3952687/20237524/c3456d48-a928-11e6-9fbc-96d5fa9cb410.png)
![screen shot 2016-11-12 at 22 36 17](https://cloud.githubusercontent.com/assets/3952687/20237525/c38bdb7a-a928-11e6-8476-807bad998134.png)

**Comment by enzyme69** [comment]
It takes 1005 edges to create this Suzanne Pocky structure. At some point, I will make a structure that looks like Hong Kong Bamboo construction tower.

**Comment by nortikin** [comment]
POLYGON BOOM NODE

**Comment by nortikin** [comment]
cap holes can be with pipe node or matrix tube node
