### ISSUE TITLE
ALGORITHM: Substrate, Sequoia, are this hard to make?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#960]
Sverchok cannot do recursive yet, but wondering if these kind of things are hard to make?

Sequoia / GrandPerspective
![screen shot 2016-11-12 at 20 36 57](https://cloud.githubusercontent.com/assets/3952687/20236876/d05a2d4a-a917-11e6-930f-336a62fa980b.png)

Substrate in Processing
![substrate_algorithm](https://cloud.githubusercontent.com/assets/3952687/20236872/b8b3c9a8-a917-11e6-8e9c-3d6510a9e39b.png)

I still cannot get my head around things like below using Python, but very interested to do so:
- A cube, sliced into two
- Next: 2 objects from above, each sliced randomly into two again
- Next, 4 objects, each sliced randomly again
- Next, 8 objects, each sliced again

If this kind of repetition possible in Sverchok, run every frames... until stopped.

**Comment by zeffii** [comment]
> Sverchok cannot do recursive yet

Internally some of the most commonly used nodes have recursive algorithms. Scripted node can execute recursive code. You must mean recursion directly from the node view.. I don't think we oppose that,, but it's not obvious how to expose such a feature to the user via a generic UI. Perhaps the Monad interface (as discussed on other _issues_. 

Novel recursion can be difficult enough when it's just plain code..

**Comment by zeffii** [comment]
Take for instance,, if you look at the source code of substrate in processing
http://ejohn.org/apps/processing.js/examples/custom/substrate.html

if that doesn't look simple in code, it's not going to be 'trivial' to do via nodes either. The complexity doesn't just disappear.  -- realistically.

**Comment by enzyme69** [comment]
Yes fascinating complexity. I will investigate this using python and also Houdini.

One day when we have Voronoi fracture in 2D or 3D, would like to see how Sverchok can make pieces and smaller pieces....

Thanks!
