### ISSUE TITLE
Stick Algorithm 2

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#963]
Previously I was looking into how to turn polygons, separating all the edges. I still don't have the way to do it in Sverchok, but I can use AN, so that's ok.

I supposed, there might be a way to turn polygon mesh into their edges in Sverchok --- pending....

But anyway, second idea is to scatter bunch of points, but divide them into half of their total and pair each one with stick that is close but within certain distance.

Is this a trivial thing?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20244297/0a4ee7ca-a97c-11e6-8db9-79df6bdd9861.png)

https://gist.github.com/dcde8c12b6d139eaa00e78022306289c

**Comment by zeffii** [comment]
@enzyme69  kindly use the issue tracker to ask a single question per issue. It's totally fine to ask as many unique questions as you want, but helps searching answers later if the Title of the question reflects the main content of the question / answer.  Easier for us and you to find old content faster, tho i'm aware it seems like more effort in the short term.

**Comment by enzyme69** [comment]
Thanks @zeffii Ok I'll file issue tracker:

Was:
https://github.com/nortikin/sverchok/issues/959

**Comment by zeffii** [comment]
That's a thumb's down jimmy, if intentional you should elaborate

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20257953/430459e8-aa4d-11e6-9942-2c85d918e83b.png)

https://gist.github.com/2e99b4fc76c0373afe05fc83dbde4073

**Comment by zeffii** [comment]
this scales the edges in place, like scale at individual origins.

![image](https://cloud.githubusercontent.com/assets/619340/20259261/36d9ec94-aa54-11e6-8f80-7ad9bb48e711.png)

https://gist.github.com/cfedf9b953c27ee95250f7d9f0bcf62c

from here the individual verts of the separated edges can be passed to the math node to get the length of the edges ( this you can figure out ) , this edge length can be used to scale each pair of verts to become uniform.

**Comment by zeffii** [comment]
here the generated edges can all be given a single length, independant of their _donor's_ original length.
![image](https://cloud.githubusercontent.com/assets/619340/20260019/0dd7a300-aa58-11e6-97ce-d3fef3fe6c09.png)

https://gist.github.com/08194db846b08c452f73725a4d748949

**Comment by zeffii** [comment]
A _scale individual edges_ Node would of course make this much simpler.

**Comment by zeffii** [comment]
with the matrix transforms reset
![image](https://cloud.githubusercontent.com/assets/619340/20260925/fe2dfa22-aa5b-11e6-84df-eb8b71d9effa.png)

https://gist.github.com/80b7462e8e1f7065c30dc5d314e1ad0a

**Comment by zeffii** [comment]
comical results: 
![image](https://cloud.githubusercontent.com/assets/619340/20261074/95929486-aa5c-11e6-89b7-4de8704d3633.png)

**Comment by enzyme69** [comment]
Originally, this kind of effect was seen in Blender NPR Freestyle render. It does a lot of fancy thing with Edge, but renders super slow.

Thanks for the insight @zeffii  I'll have a study on this.

I think the Edge Separate and Edge replacement can be super useful, edges can be:
* stick
* bamboo
* pencil
* matches

Those element can also be procedural and I started to think about the possibilities.

**Comment by zeffii** [comment]
then..
![image](https://cloud.githubusercontent.com/assets/619340/20265073/37a1f32c-aa6f-11e6-947c-f20770cec0a6.png)

https://gist.github.com/1cbbdbae959a679b26e162bc309d5f9a

**Comment by nortikin** [comment]
pipe node not working?
