### ISSUE TITLE
Vector Polar Spiral to Follow Curve

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#964]
I am just figuring out the Vector Polar node that @nortikin showed the other day. Now I am wondering, I can make this kind of circular points, like Spiral, and even like Coil, but it is going only in one direction in Z.

Is there a way to disturb and re-orient the spiral just like using Blender Curve Modifier? Like bending this beautiful curve created to follow like Grease Pencil or Curve specified

![screen shot 2016-11-13 at 17 23 21](https://cloud.githubusercontent.com/assets/3952687/20244062/348068f8-a9c6-11e6-9bc8-f70a8d1f885b.png)

**Comment by nortikin** [comment]
plug sinus to one or other

**Comment by enzyme69** [comment]
![screen shot 2016-11-16 at 14 50 01](https://cloud.githubusercontent.com/assets/3952687/20334149/0424803e-ac0c-11e6-9b82-df79515c1300.png)

I want something like this, but is there a more elegant way? Currently I make 1 coil and just edge replacement every edges of resampled Grease Pencil. In effect, it's like Array and Curve Modifier. 

https://gist.github.com/a1f343598bbacdbdb0ce47b0ff40ef25

**Comment by enzyme69** [comment]
Vector Polar is something I am exploring, whether it is possible to have "Follow Curve" option.

**Comment by enzyme69** [comment]
A simpler Motion Path Curve Modifier type is something I keep wishing and thinking every day.

**Comment by zeffii** [comment]
seems to me you could just do this in Blender and then import using Object In.

**Comment by enzyme69** [comment]
Yes I can probably bake out, apply modifier curve and back in.

What would be nice if to stay in Sverchok, bring in Grease Pencil data in.

It's about how much combo we can do within Sverchok.

But I think whichever works.

**Comment by zeffii** [comment]
maybe an 'add modifiers' node :)  that outputs the resulting meshes 'post modifier' live :)

**Comment by zeffii** [comment]
But I think we'd have to enforce a restriction to only allow one Object reference Input , something clever could be done in the case of multiple object inputs, but that's a headache to explain.

**Comment by nortikin** [comment]
exactly, @zeffii

**Comment by enzyme69** [comment]
experimental node? :) happy to test and see the outcome

**Comment by zeffii** [comment]
Scene Object interaction are not a priority. not much time today

**Comment by zeffii** [comment]
i'd like to close for now -- if we get around to it it can be opened, you can continue talking here even if the issue is closed.
