### ISSUE TITLE
Shapes as gists

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#965]
**Poppy Curve**  (if it has a recognized name I don't know it) 

![image](https://cloud.githubusercontent.com/assets/619340/20244551/4f61447e-a987-11e6-9f85-34bea89e71b0.png)

https://gist.github.com/ae0ded74e0b43a1931c1bb83c63751ae

**Comment by enzyme69** [comment]
Thanks for this example, I'll add to my YouTube.

**Comment by enzyme69** [comment]
![screen shot 2016-11-13 at 20 21 55](https://cloud.githubusercontent.com/assets/3952687/20244739/7a7654b0-a9e1-11e6-9685-f12e1641547e.png)

**Comment by zeffii** [comment]
https://gist.github.com/949a06526223150719dc4ff18d016d0a
![image](https://cloud.githubusercontent.com/assets/619340/22124845/badd14b4-de91-11e6-87a3-37ad45248774.png)

**Comment by zeffii** [comment]
insta jewlery https://gist.github.com/ff9f1c18f25df83795276ab63dadf1bf
![image](https://cloud.githubusercontent.com/assets/619340/22125273/5d05174a-de93-11e6-9ec0-7dc466b48a42.png)

**Comment by zeffii** [comment]
instant sumarai https://gist.github.com/02482429dd2b7ad5aa6b28900f16c76b

**Comment by zeffii** [comment]
[BLENDERSUSHI / SV Simple Skipping Star Algorithm (LIVENODING275)](https://www.youtube.com/watch?v=rx6m-e2bkQk)

@enzyme69  check out the more math-based version of that layout.

https://gist.github.com/053a4abf15a93fbb25073dae1b26be68

![image](https://cloud.githubusercontent.com/assets/619340/22173342/23a73a9a-dfc0-11e6-8f63-2bd1252427ed.png)

**Comment by enzyme69** [comment]
Studying on this...

**Comment by portnov** [comment]
@zeffii 
@ly29 
Just BTW: https://github.com/portnov/assethub :)

**Comment by enzyme69** [comment]
@portnov Example and how to use :) 👍

**Comment by portnov** [comment]
@enzyme69 
example (development) site is running at http://assethub.iportnov.tech. It is just development instance, so i cannot recommend to store important information on it. But you can see how it is supposed to work.

**Comment by portnov** [comment]
@enzyme69 
https://youtu.be/AVSjxhPq01s
This is how it could be seen from blender :)

**Comment by ly29** [comment]
@portnov 
Asset hub looks like a very nice idea.

**Comment by zeffii** [comment]
https://gist.github.com/15a2099378aefcffa25f20a3cda47a2e

![image](https://cloud.githubusercontent.com/assets/619340/22257385/2c90d328-e25e-11e6-87ef-39b1be670571.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23361056/f9cf086e-fcee-11e6-9777-f16a447a89a1.png)

https://gist.github.com/6e7d5c5d241aecf7f34684b71ae7ad6c

**Comment by zeffii** [comment]
https://gist.github.com/f7cc96cca3095b8f8921120246b7278b
Cuzco caves inspired.
