### ISSUE TITLE
Edge Adaptive but no Scaling?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#966]
![screen shot 2016-11-14 at 11 29 33](https://cloud.githubusercontent.com/assets/3952687/20250126/bac5adc8-aa5d-11e6-8fd8-53100d0c6f30.png)

I was using this Edge Adaptive to replace my Pocky stick structure, but I realized that Edge Adaptive is actually changing the scale and dimension, stretching and squezing Donor into "edge" length.

Is there a way so that Edge Adaptive only replace the "Edge" and place it into center point, with the Rotation maintained (maybe can be reversed also)  but not doing any scaling?

**Comment by nortikin** [comment]
complicated, but matrix with interpolated 0.5 and rotation to one of vertices with some sex on levels.
can be done
