### ISSUE TITLE
Stripes Interpolation Node Test, Broken?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#969]
I was curious so I tried this node, 
https://github.com/nortikin/sverchok/pull/968

Didn't give me nothing, just RED mark on the node. The example GIST also failed.

Any idea?

![screen shot 2016-11-17 at 18 51 15](https://cloud.githubusercontent.com/assets/3952687/20380561/f22718b0-acf6-11e6-9d45-0f239fd02986.png)

**Comment by zeffii** [comment]
you need 3 Bezier curves selected.. and loaden into Object In.

**Comment by zeffii** [comment]
There have been changed to that node since the  _gist_ was made, possibly a new gist is needed @nortikin

**Comment by zeffii** [comment]
@nortikin  also  `numpy.power`  not `numpy.pow`

**Comment by nortikin** [comment]
omg. push now

**Comment by zeffii** [comment]
@enzyme69  it works. but you need to give it the right input.

3 beziers, with all the same origin, but all different points will work fine.
![image](https://cloud.githubusercontent.com/assets/619340/20521566/18bb528a-b0ac-11e6-8b88-1e849a14e261.png)

**Comment by enzyme69** [comment]
Ok Thanks I will investigate.

**Comment by enzyme69** [comment]
![screen shot 2017-01-17 at 15 26 23](https://cloud.githubusercontent.com/assets/3952687/22007748/55b42696-dcc9-11e6-9214-06bfd745ebba.png)

Is there the update of the GIST example? I feel like I might not be doing it right.

I am getting NAN everywhere. Cannot be a good thing.

If have time can check this. @nortikin  @zeffii

**Comment by enzyme69** [comment]
What.. ZEFFI: the origin in the same location, I apply matrix outside sverchok and it works! Sort of... still weird.

![screen shot 2017-01-17 at 15 29 53](https://cloud.githubusercontent.com/assets/3952687/22007819/d4fa844a-dcc9-11e6-95c4-30120b1257b6.png)

Will study and make sense of this.

**Comment by enzyme69** [comment]
Got it. I joined 3 x Bezier Curves, and I got result. Understood.

![Uploading Screen Shot 2017-01-17 at 15.39.29.png…]()


ZIP:
[stripesExample.zip](https://github.com/nortikin/sverchok/files/710019/stripesExample.zip)
