### ISSUE TITLE
decompose node idea

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#97]
We have join lists node.
We need anthonym node - decompose node:

it has veriable:
:::level
it makes from particular level of any list output sockets. multysockets.
For input only one adaptive socket.

for level 1 - makes objects series of sockets
for level 2 - makes vertices/pols/edgs series of sockets
for level 3 - makes digits
may be more levels, so it find lists depth and limit itself.

**Comment by zeffii** [comment]
list decompose is pretty awesome btw:)

![image](https://cloud.githubusercontent.com/assets/619340/17475569/ee55ced8-5d5b-11e6-8b59-9cac1d1240c8.png)
