### ISSUE TITLE
Vertex Grouped from Object is giving the wrong index number?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#970]
I tested something like this:
https://gist.github.com/07c85e5ba555b760708022e1c3628b61

Where I just paintweight bunch of vertices and would like to instance based on it.

But from a quick glance, looks wrong.

**Comment by enzyme69** [comment]
However, this looks correct:

![screen shot 2016-11-17 at 23 11 44](https://cloud.githubusercontent.com/assets/3952687/20388938/400e1816-ad1b-11e6-8ef1-6252caf065af.png)
 
It makes me wonder what Use Vertex Group for Nesty Insertion was for.

**Comment by enzyme69** [comment]
If not too much trouble can the Vertex Weight has Object slot in 💃

**Comment by nortikin** [comment]
made mk2, but need to upload to git, not now

**Comment by zeffii** [comment]
well, I think the issue here is .. that the `vertex group` will contain a _different number_ of items than the `Vertices`.

**Comment by zeffii** [comment]
I think this works correctly now with the update a pushed..

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21222763/e1f80aa2-c2c3-11e6-9bdb-d7a7964d54e2.png)
