### ISSUE TITLE
Vectorizing Seed is not always so straight forward

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#972]
Why is is List Repeat does not always guarantee it will Vectorize?

Very often, I just want to randomize seed using Range Int, but it didn't work down the stream.

![screen shot 2016-11-18 at 19 58 05](https://cloud.githubusercontent.com/assets/3952687/20424357/8dda0c2c-adc9-11e6-80e6-ce0f03c1299c.png)

https://gist.github.com/2f61d44d7509887e71dee78ff15abaa9

**Comment by enzyme69** [comment]
One thing I noticed, BMesh MK2 Viewer does Vectorize. Whenever I plug multiple vectors into Matrix In for BMesh MK2. And then use the Range Int for Seed, it works.

**Comment by enzyme69** [comment]
@nortikin what's the thing I am missing here. If I don't use BMesh Viewer MK2, I cannot vectorize easily? List Split or List Flip?

**Comment by nortikin** [comment]
you want to make double vectorization. I think it should be in all the nodes, but nw not every has. line node has, random hasnot. Sadly. It is one of straight thing of development.

**Comment by enzyme69** [comment]
I see, now I understand. It will be something I gotta keep in mind. I know
I crashed into this issue with Animation Nodes as well, some nodes does
"it" some does not. I use Sverchok mostly for now.

**Comment by nortikin** [comment]
that is why i am against sverchok called 1.0 version. And AN too, because folks made PR mistake, as i see. 1.0 version is version of mostly made features, alpha, 1.0...2.0 is beta evrsions, after 2.0 is completed product.
AN too fast made this desigion.

**Comment by enzyme69** [comment]
I am as Artist happy to see Add On like Sverchok and AN continue to grow in
steady and healthy pace.

I think Sverchok needs some more exposure
