### ISSUE TITLE
Back to ... Instancing In Sverchok case

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#975]
![screen shot 2016-11-20 at 12 01 41](https://cloud.githubusercontent.com/assets/3952687/20459530/2a5ebf0c-af19-11e6-807d-09ffcdf13b0a.png)

https://gist.github.com/cad763b718e011541a58c495a2b09b77

I am back in full cycles, now case of instancing in Sverchok. Can it be made simple today?

At this moment, I need to use List Repeater and List Shuffle.

Would be nice if Object can be selected from List Item and then Mesh Data can be instanced per Matrix In request.

**Comment by enzyme69** [comment]
Even though this works:

![screen shot 2016-11-20 at 12 04 42](https://cloud.githubusercontent.com/assets/3952687/20459534/8f79db56-af19-11e6-839f-84304f0fbcbd.png)

But, I cannot seem to be able to make my own pattern to instance the objects. Unless my brain is forgotting something....

Supposed I want to provide my own Formula [[ 1,2,6,2,7,8,3,6,3,7,8,5,8,4,5,4]] to Copy Instance patterns. How am I going about doing it?

**Comment by enzyme69** [comment]
![screen shot 2016-11-20 at 12 08 36](https://cloud.githubusercontent.com/assets/3952687/20459556/27387fa6-af1a-11e6-825f-7fcc4fe8afce.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20461924/907fe5ce-af0d-11e6-936c-885832fecd9d.png)

am I missing something?

**Comment by enzyme69** [comment]
Maybe it can be simpler, but I think I will close this. I thought that I could List Item the object just like Particle Alpha node.

I keep reminding myself: think in term of components.

**Comment by zeffii** [comment]
oh... yeah...:  object_socket -> ListItems    I've never tried that..  
https://github.com/nortikin/sverchok/blob/master/nodes/list_interfere/item.py

doesn't look like there's any hardcoded limitation, should just work? .. but we don't have an Object decompose node . I think.. (maybe we do)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20462550/1edf94a0-af21-11e6-9193-0bc853844e4b.png)

the most convoluted set of nodes here is the part that produces random integers within a range.

**Comment by zeffii** [comment]
i'm tempted to make a _random_int generator_..

**Comment by enzyme69** [comment]
Object ID Out... whoa... hidden node! I will investigate all this ID nodes. Thanks @zeffii 

Yeah, Random Number with Min and Max Range. It's for convenient, but probably boring task.

**Comment by zeffii** [comment]
Sverchok isn't optimised for these kinds of use-cases.   http://randomoverload.org/wp-content/uploads/2011/08/f8315dd3wheelbarrow.jpg

**Comment by enzyme69** [comment]
Aha.... I will keep that in mind then.

I am thinking of making video like that photo.

We can load many objects in 3D scene, we can load into Sverchok via group.
Objects can have many separate parts.
Each separate part can have edges, points, and polygons.
Which components all can be separated.

And I want to show that in 1 video.

This way, I have a better idea about Sverchok and Matrioshka thing.



------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
I want to be clear about terminology here. Instancing is probably not the right word for what all proceeding  posts in this thread is about. Instancing means having (mesh_data) and explicitly _not_ copying it as new lists.  Everything so far here has been full copy duplication . And this will be utterly slow for non trivial objects.

The Sv Instancer node is the only way to do real instancing with Sverchok. Now it totally makes sense to consider developing a node which lets the user give a list of Objects from the scene (or Group) and allow the user to place instances of any of those objects around the scene in the form `((Reference, Matrix),..... )`

**Comment by enzyme69** [comment]
Thanks Zeffii... I hardly thought bout it. But I remember you mentioned it
at some point. So... do I really should have used SV Instancer if I wanted
100000 objects?

In future video I will be more careful using term Instancing and actual
real mesh data.

**Comment by zeffii** [comment]
there's limits to what has been exposed to the bpy. API regarding instanciation. 

We can currently use either
  1.  Vertex/Face Duplication  (fast)
  2.  Particle System duplication (fast)
  3.  Reusing Mesh data for new objects (low memory, but not fast initially, fast after initial creation of all objects)

The fast ones don't let you give a distorted Matrix ( must have uniform scaling, and not scew ) . Option 3 does give you all the freedoms of instancing and matrices, but .. initial speed of instanciating large numbers of these kinds of Instances makes that option less attractive.

**Comment by nortikin** [comment]
as i saw in presentation https://www.youtube.com/watch?v=OfdhIvo_ops he uses numpy (i sent email to @zeffii some time ago) and maybe in numpy version instancing will be ok.

**Comment by zeffii** [comment]
oh yeah, using numpy is great for single objects ( updating all verts then using data.verts.foreach_set(...) ) boom!
