### ISSUE TITLE
Matrix Interpolation Factor --- is this vectorized?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#976]
May be related to:
https://github.com/nortikin/sverchok/issues/161

I made myself confused again in this classic case. Basically I am trying to do this:
1) I have a single object, already separated into pieces.
2) In Sverchok, I want to separate loose and then push each object, one by one. I decided to use Dynamic Paint to trigger the effect.
![screen shot 2016-11-20 at 18 42 26](https://cloud.githubusercontent.com/assets/3952687/20461396/220138b6-af51-11e6-97d6-e78270a85dbf.png)

![screen shot 2016-11-20 at 18 44 07](https://cloud.githubusercontent.com/assets/3952687/20461407/598db28c-af51-11e6-8349-44d9950b7cca.png)
![screen shot 2016-11-20 at 18 43 27](https://cloud.githubusercontent.com/assets/3952687/20461408/59db989e-af51-11e6-994a-39ef6bc2d087.png)

3) So, from no.2, I got each separate pieces center pivot output as points. With Canvas and Brush setup, and distance changes, I was wishing to trigger the transformation.
4) Plugging distances to Factor of Matrix Interpolation, however, didn't give me what I want. It seems to multiply the output Matrix. So strange....

Any idea?

GITS
https://gist.github.com/f721cabe361466b3c1077ebc88400578

BLEND ZIP:
https://www.dropbox.com/s/au30q5o5wmgci6w/pieces_011_2016_11_20_07_44%202.zip?dl=0

**Comment by zeffii** [comment]
good question, lets have a look at the code.
https://github.com/nortikin/sverchok/blob/master/nodes/matrix/interpolation.py
https://github.com/nortikin/sverchok/blob/master/nodes/matrix/interpolation.py#L54-L78

**Comment by enzyme69** [comment]
Ok I am reading the code now....

In the meantime:
https://youtu.be/Coa9GNvYue4

That video above clearly explain my confusion

**Comment by enzyme69** [comment]
Ok I am more confused after ready the code. My guess is currently the "Factor" in this Matrix Interpolation node does not really do what I was trying to do?

**Comment by nortikin** [comment]
why you ask after made video?
https://yadi.sk/d/tYmPj1Tuz55YZ

**Comment by enzyme69** [comment]
@nortikin I asked first and make video, but in that video I was stuck. I was thinking to make another video to fix.

**Comment by enzyme69** [comment]
While still in this case, I want to also propose a way to easily "center pivot" of parts of objects if possible?
![prtscr capture_29](https://cloud.githubusercontent.com/assets/3952687/20474952/461a797a-b01d-11e6-8312-bde85d7bc742.png)

We have Bounding Box, but sometimes it takes my high brain processing to get to Center Pivot.  And still sometimes I don't get it.

**Comment by enzyme69** [comment]
Above is single object, with bunch of separate parts. I want to "Object Boom" those so I can get center pivot, and proceed from each new "initial transform".  How to think about this?
https://gist.github.com/0db20ba47fc36b4b7ddd261ffcde11aa

**Comment by enzyme69** [comment]
![prtscr capture_30](https://cloud.githubusercontent.com/assets/3952687/20475202/97e49690-b01e-11e6-9605-ced4ccff0051.png)
I think I figure it out.

https://github.com/nortikin/sverchok/issues/875

Sverchok is really a strange tool :8ball:

**Comment by nortikin** [comment]
cool!!!
will investigate ))

**Comment by nortikin** [comment]
obviously, scale in matrices go wrong...
