### ISSUE TITLE
Random Number Generator

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#978]
Feature driven development :)

- must output Int or Float in a given range, for n amount of numbers. (Vectorized all inputs)
- May use numpy, and output regular lists by default or numpy arrays if wanted.

![](https://cloud.githubusercontent.com/assets/619340/20481642/71fbf3fa-afe8-11e6-9e69-3186aeb23d0c.png)

https://docs.scipy.org/doc/numpy/reference/routines.random.html

known issues. will fix shortly.

- [x]  high must be higher than low  : else
    ```
    File "mtrand.pyx", line 934, in mtrand.RandomState.randint (...\mtrand.c:9166)
    Node Random Num Gen had exception low >= high
    ```
- [x]  switching modes doesn't trigger a process (click a socket to make it process)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20481642/71fbf3fa-afe8-11e6-9e69-3186aeb23d0c.png)

**Comment by zeffii** [comment]
i'll complex mode for later..

**Comment by enzyme69** [comment]
​When designing a node, do you guys have clever way to do the wrapping and
unwrapping?

Like, those Size, Seed, Float Low, Float High... I assume they are
Vectorized, accepting List of Values and it will automatically work in
Sverchok down the line?

**Comment by zeffii** [comment]
the inputs of this node will have to be simple lists for now, as:
```python
[[1,2,3,4,5,6]]
```
meaning you can happily plug IntRange and FloatRange nodes in to all sockets, and the Node will know what to do..

### Gotchas

## 1.
A tricky situation arises if you input lists like this 
```python
[[[1],[2],[3],...]]] 
```
you'll need to unwrap first.

## 2.
also this will be undefined / not handled. Sanatize your input first.
```python
[list1=[1,2,3,4, [1,2,4],[3]], list2=[1,2,3,4]]] 
```
They are not homogenous and it's going to make extremely ugly - unreadable code to handle that.. and i'm not even sure it would make sense to the user.

**Comment by zeffii** [comment]
I want to be clear here, there's a lot of different possible inputs. Some indeed would make sense if a case can be made for  them, while others is just more hassle than it's worth trying to come up with a meaningful way to dissect the input.

So.. in summary, on the top level it is vectorized, but not if you try multiple nested lists/sublists.

**Comment by zeffii** [comment]
i'm not sure what this would output btw..  or how useful it would be.
![image](https://cloud.githubusercontent.com/assets/619340/20482493/3ae85160-afed-11e6-9114-0203e40a07cf.png)

**Comment by zeffii** [comment]
or.. (tho some interesting motion gfx effects can be achieved..)

![image](https://cloud.githubusercontent.com/assets/619340/20482622/dc736628-afed-11e6-8125-cdd30eaafae8.png)

**Comment by zeffii** [comment]
apparently randint needs to be coerced some:  (if High is lower than low )
```
 File "mtrand.pyx", line 934, in mtrand.RandomState.randint (numpy\random\mtrand\mtrand.c:9166)
Node Random Num Gen had exception low >= high
```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20502363/040f200a-b03e-11e6-8a45-5445fe801b41.png)
