### ISSUE TITLE
Dealing with Multiple Objects and Multiple Parts

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#979]
I have this question, I am wondering how Sverchok can handle such case:

1) Multiple Objects, each have multiple parts
2) I can bring multi objects via Objects in MK2.
3) I understand now we can separate using Object ID
4) But, can we unwrap it one by one or doing multiple actions.

@zeffii  said that Sverchok is not really optimized for such ~"complex".~ use cases

If Object A has 3 parts, Object B has 4 parts.

Is it possibly to have:
A1, A2, A3, B1, B2, B3, B4.

And then, grouping and accessing maybe just A1, B3, B4, and then unwrap the face further and do extude?

![prtscr capture_31](https://cloud.githubusercontent.com/assets/3952687/20480528/fe51e92e-b036-11e6-94c0-491dac6307aa.png)

**Comment by enzyme69** [comment]
![prtscr capture_32](https://cloud.githubusercontent.com/assets/3952687/20480719/e0e37be0-b037-11e6-969e-6193ec47ad2f.png)

List Decompose seems to be able to separate all the elements of Object A and B.

However... I still don't get the "Separate" in Scale node. Maybe I use Delete Level? To Unwrap once?

**Comment by enzyme69** [comment]
![prtscr capture_33](https://cloud.githubusercontent.com/assets/3952687/20480954/cdf258fc-b038-11e6-87fa-11fad85f00c5.png)

This is a more logical way.

But yeah, basically in my mind at the moment, I am trying to make sense of few things.

If I am thinking in AN maybe I would do these steps:
1) Get bunch of Object List
2) Object List, bring into loop, process it one by one. Object A has 4 elements, Object B has 3 elements. Another List. Another Loop.

In Sverchok, sort of similar but more streamlined.

**Comment by enzyme69** [comment]
Sverchok is crazy cool, because this actually works...

![prtscr capture_34](https://cloud.githubusercontent.com/assets/3952687/20481051/5c4d70c8-b039-11e6-9507-a55ea7e5fbc2.png)

But suddenly, instead of filtering by Index Number, I wonder if we can filter by name etc...

Interesting...

**Comment by enzyme69** [comment]
![prtscr capture_35](https://cloud.githubusercontent.com/assets/3952687/20481126/b6445722-b039-11e6-8ea0-3b6d1c2f6103.png)

Make sense!

**Comment by zeffii** [comment]
complex? nope, just 'alternative' priorities :)

**Comment by enzyme69** [comment]
I'll make video of this. This should be for beginner :+1:

**Comment by zeffii** [comment]
realise that if you use Obj ID out, and reference the same object 10 times , then it will make 10 unique mesh pairs, that are all identical. This is what I mean when I say it's not optimal. 

so.. using less nodes isn't always less processing :)

**Comment by enzyme69** [comment]
Ah, that's something that user will not always aware.

**Comment by zeffii** [comment]
but the Object ID out node could be made more optimal by checking if it has loaded an object's mesh during the current process-cycle , and reuse the associated data. 

https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/blenddata_to_svdata2.py

The process function assumes that each member of the Objects list is unique: 
https://github.com/nortikin/sverchok/blob/master/nodes/basic_data/blenddata_to_svdata2.py#L48-L78

**Comment by nortikin** [comment]
@enzyme69 sorry, i made changes to stripe node without safety, you just replace old node with new one, please
