### ISSUE TITLE
Clever Triggering System

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#982]
I am trying to make a trigger system for dynamics, but soon I realized although I can do this in ordered list fashion, I may need a better way, like a way to pair objects.

![trigger_system](https://cloud.githubusercontent.com/assets/3952687/20520756/4840c152-b0fc-11e6-9a58-9c8c176db89e.gif)

Is there opinion or advice or suggestion? 

Currently my setup is like this:
- I have bunch of objects in the scene. I want them to be active by trigger system
- For each object I create a POINT. This point will be displaced by Dynamic Paint as a command.
- This should generally work, although my issue is that I am using Animation Nodes to do the triggering because it has this handy Object Attribute Output, bringing objects into Animation Nodes might reshuffle or sorting the objects in 3D scene

I guess maybe I can use renaming system before attempting to do something like this?

I'll brainstorm...

**Comment by enzyme69** [comment]
Hmm... that's why

![screen shot 2016-11-22 at 21 57 03](https://cloud.githubusercontent.com/assets/3952687/20521281/a26a3ba2-b0fe-11e6-86d1-418b88bea1c7.png)

If possible: Sverchok Bmesh Viewer MK2 output numbering needs to be like this: 000, 001, 002, 003, 004...

**Comment by zeffii** [comment]
hmm, zero padding. i'm not sure why I chose no zero padding by default, it made the code a bit easier maybe.

perhaps animation nodes can sort by object ID ( bmviewer objects have an integer ID  .. `MYBOX.idx`)

**Comment by enzyme69** [comment]
I made a script to turn no padding into padding:

`
import bpy

sel = bpy.context.selected_objects

for ob in sel:
    # get master name and number
    origname = ob.data.name
    orignamesplit = origname.split('_')
    mastername, number = orignamesplit[0], orignamesplit[1]
    
    # rename so it has zero digits

    ob.data.name = '{a}_{b:04d}'.format(a=mastername, b=int(number))
    ob.name = '{a}_{b:04d}'.format(a=mastername, b=int(number))
    
    
`

**Comment by zeffii** [comment]
an argument against sorting by name is to made, if the number of objects exceeds 1000. For example
```
Objname
Objname.001
Objname.002
...
Objname.999
Objname.1000
```

![image](https://cloud.githubusercontent.com/assets/619340/20523409/2c8e42be-b0b5-11e6-9c11-51ff3b90129d.png)

**Comment by enzyme69** [comment]
At the moment, we cannot store special attribute value per point, right? Maybe possible in python like storing "key". Any trick that we can do in Sverchok?

**Comment by enzyme69** [comment]
Like for example:
- Made 5 points
- Each point has "special" attribute that become key for sorting: maybe naming 5 points with: apple, banana, carrot, durian, and pineapple.
- Then, at some other point using those as key to sort and rename

Hmm... that gave me an idea.

**Comment by zeffii** [comment]
and if i automatically add zero padding to each object...  its looks a bit silly if i only have 4 objects
```
Alpha_0.00001
Alpha_0.00002
Alpha_0.00003
Alpha_0.00004
```
It could have dynamic zero-padding, arguments can be made for both cases. I went for the side that required least amount of work. :)

**Comment by zeffii** [comment]
> At the moment, we cannot store special attribute value per point, right? Maybe possible in python like storing "key". Any trick that we can do in Sverchok?

if we used bmesh for piping meshes around in Sverchok, then yeah you could add a vertex_layer (ints, floats) per vertex.  We do have nodes that convert pydata (sv_data) to `bm` , but no node yet to add a vertex layer.

![image](https://cloud.githubusercontent.com/assets/619340/20523731/bcc3116a-b0b6-11e6-839a-c85b83a85222.png)

**Comment by zeffii** [comment]
btw..
```python
import bpy

sel = bpy.context.selected_objects

for ob in sel:
    # get master name and number
    origname = ob.data.name
    mastername, number = origname.split('_')[:2]
    
    # rename so it has zero padded digits
    ob.data.name = '{a}_{b:04d}'.format(a=mastername, b=int(number))
    ob.name = '{a}_{b:04d}'.format(a=mastername, b=int(number))
```

**Comment by zeffii** [comment]
and, the object naming is something i expressly mention as the last point in the first post here
https://github.com/nortikin/sverchok/issues/541

**Comment by nortikin** [comment]
separate parallel list
