### ISSUE TITLE
Particle system based Sv Instancer MK2

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#983]
i think we can make a node that generates instances using one or more particle systems attached to ~Empties~ surrogate point meshes.

 input 
  - list of objects 
  - list of matrices ( subset - `size, rotation` )
      - I think scale must be uniform, so matrices should be passed that respect this fact.
      - (yes: location, size, rotation)

 output:
  - into scene

thoughts?

**Comment by nortikin** [comment]
do you propose to generate empty + particle systems on fly?
It is good idea.
scale + rotation we can add during node tree.

**Comment by zeffii** [comment]
probably a 'receiver' point mesh is the way to go, either will all locations as vertices, or a single `vertex-object` where we push N particles and corresponding loc/size/rotation ..

**Comment by zeffii** [comment]
i'm not sure this was ever clear, but the triangles on the dupli instancer represent the location, rotation and size of the Face used for the instance duplication ( Yep hardcore face duplis) .  These have to exist else there's nothing to duplicate onto.

I can see how this is distracting, luckily it doesn't render those.

I dony know if it will be faster to control a particle system via python...

**Comment by zeffii** [comment]
i'm not going to sink time into this.
