### ISSUE TITLE
Numpy Nodes Docs

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#985]
let's discuss the numpy array node in Beta, what can we expect and what is hard to automate.

The general current use of this node is this:
```
A = [some non numpy node] (Vertices or regular lists)
B = [np.node ( np.array(x) mode )]
C = [np.node (some functions )]
D = [np.node (to_list()]
E = [back to sverchok / regular python lists.]
A -> B -> C -> D -> E
```

**Comment by nortikin** [comment]
the 1st problem is non-adaptive socket type
non-reducing y socket if it not needed
and it takes some error
and naming non-userfriendly at all... but how to call all this functions?

**Comment by zeffii** [comment]
My opinion is that if someone needs a numpy node, then they should be willing to read the docs for the numpy functions they're using, Likely they will be looking for numpy features because they already know numpy. (to these people the names will make sense..)

- a simple *as list* boolean for the bmesh node would be useful (hence no need for a dedicated `to_list()` enum item.
- yep also a simple `if input and input[0] and isinstance(input[0], np.ndarray):  then recast automatically`

**Comment by zeffii** [comment]
what you mention about the extra socket, there are two ways to think about this. 

### Pro
1. Sometimes it can be useful to not automatically add/remove sockets while going through the Modes, someone might accidentally pick a mode they didn't want and a socket will be unconnected.

2. Cycles also has nodes that don't dynamically add/remove sockets depending on mode..

### Con
maybe confusion? but that's what manuals are for. and people rarely read them..

**Comment by zeffii** [comment]
we could make a nodesocket transparent in certain modes ( i like this idea a lot) to indicate that the input will be ignored..

**Comment by nortikin** [comment]
visual representation of sockets, than it has to be global feature. i agree, it is better idea

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20639404/c3011edc-b3c2-11e6-82bc-8acd0fd586c4.png)

I think we should have a submenu for several dedicated numpy nodes. ( more coming later )
-  np.linspace ( start, end, count )    (numpy's range)
-  np.roll(np.array, roll_by)               (numpy's shift array indices)

I think we can use a class factory to write / generate these classes from one .py file, in a succinct style.

**Comment by zeffii** [comment]
possibly configuring nodes like this:
```python
readthedocs = 'http://numpy.readthedocs.io/en/latest/reference/'
node_details = {}


node_details['linspace'] = {
    'sig': 'np.linspace(start, stop, num=50, endpoint=True, retstep=False)'
    'inputs': [
        ['starts', 'scalar', None],
        ['stop', 'scalar', None],
        ['num', 'int', 50],
        ['endpoints', 'bool', True],
        ['retstep', 'bool', False]
    ],
    'outputs': [ ['result': 'nd.array', []] ],
    'info': 'generated/numpy.linspace.html'
}
```

**Comment by nortikin** [comment]
or separate socket?

**Comment by zeffii** [comment]
new socket sounds good, but not needed immediately.

**Comment by zeffii** [comment]
alternative node declaration...

```python
if NODE_LINSPACE:

    def process(self):
        inputs = self.inputs
        outputs = self.outputs

        if not outputs[0].is_linked:
            return

        start, stop, num = [s.sv_get()[0][0] for s in inputs]
        out = np.linspace(start, stop, num, self.endpoint, self.retstep)
        if self.retstep:
            outputs[0].sv_set([out[0]])
            outputs[1].sv_set([out[1]])
        else:
            outputs[0].sv_set([out])
    
    descriptor = """\
            =>  start    , scalar   , default=0
            =>  stop     , scalar   , default=10
            =>  num      , int      , default=50
            ==  endpoint , bool     , default=True   , (r1 toggle)
            ==  retstep  , bool     , default=False  , (r1 toggle)
            <   result   , nd.array , default=list
            <   step     , scalar   , default=0
    """

    temp_dict = {
        'process': process,
        'sig': S(default='np.linspace(start, stop, num=50, endpoint=True, retstep=False)'),
        'info': S(default=readthedocs + 'generated/numpy.linspace.html')
    }
    
    inject_attrs('linspace', descriptor, temp_dict)
    augment_node_dict('linspace', temp_dict)
```

**Comment by zeffii** [comment]
not sure about if this is a great idea..  or stupid and obfuscated.
