### ISSUE TITLE
Loop Offset Within Bounding Box for 3D Grid

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#988]
@zeffii  mentioned about the potential 3D Voxel Grid in Sverchok.
https://github.com/nortikin/sverchok/issues/914

Perhaps such node or something inside Bounding Box could do this kind of 3D XYZ offset with loop. Fancy but can be interesting. Kind of like "scrolling effect" but for 3D.

This idea appears when I was trying this Magica Voxel and the ability to slide XYZ in 3D for Voxel is cool.
![magica](https://cloud.githubusercontent.com/assets/3952687/20612377/52827c2e-b30d-11e6-8f12-d842c17864c3.gif)

I think it can be done using points grid as well, I want to try this!

**Comment by nortikin** [comment]
like that. minecraft style modelling

**Comment by enzyme69** [comment]
The sliding thing is neat, but that's probably complex right? I can try using Sverchok slicing and list shift? but in one axis only. I wonder if I do it in every axis.... silly request I know.

**Comment by zeffii** [comment]
The comment in my todo was more about making a generator for a Cube grid of 3d points, less about implementing some kind of grid + xyz shift offset node (which has limited general uses, but i'm sure some interesting VFX possibilities would be possible) .  I challenge you to implement a cube grid generator with _snlite_ , "Scratch your own itches". If you want it badly enough you'll make it.

**Comment by enzyme69** [comment]
​That will do :]
