### ISSUE TITLE
Flattening object without direction

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#990]
Under weird circumstances, I baked out geometry that is looking like this:

![need_flat](https://cloud.githubusercontent.com/assets/3952687/20613028/cd9ee73e-b313-11e6-83d2-a40a1d875ac7.gif)

Probably it was because of Alembic bake but I didn't turn on modifier.

I kind of needing it to be flat on the ground.  All the points are flat within hidden plane.

[flattenMe.zip](https://github.com/nortikin/sverchok/files/612406/flattenMe.zip)

Supposedly in theory it's like this:
- Observe all the points, make the points flat on tangent into the ground.
- For every frames.

**Comment by enzyme69** [comment]
I think the issue causing this was:

1) I first project bake Alembic to get flat monkey (that is rotating)
2) The monkey Alembic reloaded, it has Mesh Modifier and Transform Modifier.
3) Baked out again.

Now I need to reverse the rotation somewhat.

**Comment by enzyme69** [comment]
The problem is probably like this:
1) I rotate transform an object
2) somewhat the thing got transfered over
3) I want to reverse transform now ==> maybe I have the animation

**Comment by nortikin** [comment]
https://yadi.sk/d/c9AurH2YzRdgC
bad news is we can find rotation based on vertices. So three points will definetly show wrong orientation

**Comment by nortikin** [comment]
https://yadi.sk/d/yOro__V2zRrWV
something wrong with positive Y that Y I turned to negate Y

**Comment by enzyme69** [comment]
Thanks Nikitron!
