### ISSUE TITLE
passing custom draw functions to sockets from sv_init (or process...)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#992]
![image](https://cloud.githubusercontent.com/assets/619340/20624609/2ce1965c-b30e-11e6-86f2-96166abca423.png)

roughly...

in the node

```python

    def my_custom_draw(self, context, layout):
        row = layout.row(align=True)
        row.prop(self, 'axis_x', toggle=True)
        row.prop(self, 'axis_y', toggle=True)
        row.prop(self, 'axis_z', toggle=True)

    def sv_init(self, context):
        self.width = 100
        a = self.outputs.new('VerticesSocket', "Vector")
        a.custom_draw = 'my_custom_draw'


```

in the `StringsSocket`

```python

    custom_draw = StringProperty()

    ...

    def draw(self, context, layout, node, text):
        if hasattr(self, 'custom_draw'):
            if self.custom_draw and hasattr(node, self.custom_draw):
                getattr(node, self.custom_draw)(context, layout)
                return

        if not self.is_output and not self.is_linked:
            if self.prop_name:
                layout.template_component_menu(node, self.prop_name, name=self.name)
            elif self.use_prop:
                layout.template_component_menu(self, "prop", name=self.name)
            else:
                layout.label(text)
        elif self.is_linked:
            layout.label(text + '. ' + SvGetSocketInfo(self))
        else:
            layout.label(text)


```

**Comment by nortikin** [comment]
wohoo!!

**Comment by zeffii** [comment]
or
```python
    def my_custom_draw(self, socket, context, layout):
        row = layout.row(align=True)
        row.prop(self, 'axis_x', toggle=True)
        row.prop(self, 'axis_y', toggle=True)
        row.prop(self, 'axis_z', toggle=True)
```
and
```python
        if hasattr(self, 'custom_draw'):
            if self.custom_draw and hasattr(node, self.custom_draw):
                getattr(node, self.custom_draw)(self, context, layout)
                return
```

the extra parameter could be useful for more specific reactions to being connected..

**Comment by nortikin** [comment]
why not enumerate?

**Comment by zeffii** [comment]
to allow `x = [-1, 0 1] , y = [-1, 0 1] , z = [-1, 0 1]`  , i did think about that...

**Comment by nortikin** [comment]
it is interesting, but i thought of enumproperty [[x,x,x],[y,y,y],[z,z,z]]

**Comment by zeffii** [comment]
or columns... `[-][x]  [-][y]  [-][z]`   , if negative bool is unticked, then it's plus.
![image](https://cloud.githubusercontent.com/assets/619340/20640600/f07ed51e-b3e2-11e6-97be-c4add0ac75aa.png)

but that looks shit.

**Comment by zeffii** [comment]
yeah.. don't mind changing it to enum , it's a bit more flexible

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20640685/3ad5bf68-b3e5-11e6-9e18-6ce528131282.png)

**Comment by nortikin** [comment]
label as vector -1,-1,1

**Comment by zeffii** [comment]
how about "[ -1, -1, 1 ]"  mathematical notation..

**Comment by zeffii** [comment]
because : 
![image](https://cloud.githubusercontent.com/assets/619340/20640713/5db9f9f8-b3e6-11e6-88e9-0fba7a680e1e.png)

**Comment by zeffii** [comment]
wish we could draw_buttons inside the label when minimized like that...

**Comment by ly29** [comment]
Does this work with multiple instance of the node?

**Comment by zeffii** [comment]
yeah,, looks like it.. 
![image](https://cloud.githubusercontent.com/assets/619340/20650552/9e432c1a-b4d1-11e6-8e1f-cfa303692416.png)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/custom_socket_draw_append
