### ISSUE TITLE
Node for Color, RGB, HSV, etc

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#994]
I kind of wish Sverchok has node that deals with Color properly. No need to be vectorized yet, just something simple like the AN one.

If not, I will resort to the Script node, but Sverchok Mini Script node is not yet ready, right?

Anyone recalled someone asking the same question in the "Issues" at some point? 

Kind of needing to colorize something.

**Comment by zeffii** [comment]
@enzyme69  use separate issues to ask separate questions please

**Comment by zeffii** [comment]
questions about snlite, please direct them to the snlite thread.

**Comment by zeffii** [comment]
but to answer your main question, a color node is probably way over due :)

**Comment by zeffii** [comment]
do a photoshop composite of what you think the colornode should have..

**Comment by enzyme69** [comment]
![screen shot 2016-11-28 at 11 05 50](https://cloud.githubusercontent.com/assets/3952687/20653057/a5c9a0fc-b55a-11e6-91e4-5c8579de66b9.png)

I think I just screen grab the color node from Animation Nodes above.

Probably Sverchok one will be vectorized and can do other neat things.

You probably have seen me using this node many times in my AN live noding video. 

If there is other thing to add, I might sketch it out.

**Comment by nortikin** [comment]
like that idea. do with color... todo

**Comment by zeffii** [comment]
I think also add a converter in the mix.. 
like
```
    ______________________
                        c1 -
                        c2 -
                        c3 -
                     color -
   from [ rgb hsv hsl yiq ]
   to   [ rgb hsv hsl yiq ]
   - color
    ______________________
```

**Comment by zeffii** [comment]
without a dedicated color socket, this could be done using regular StringsSocket / but that would be the 'cheap' solution..

**Comment by zeffii** [comment]
parking here:  https://docs.python.org/3.5/library/colorsys.html  this standard module does all these transforms.

**Comment by zeffii** [comment]
maybe this needs a new menu `Color`. with the following nodes

- combine color
- separate color
- convert color

**Comment by zeffii** [comment]
@nortikin @ly29 @Kosvor2 

i'm tempted to add a feature to the StringsSocket socket type where the socket's _draw color_ is defined as an instance property and can be overwritten in a node's sv_init / process functions. For sockets that are essentially duplicating all functionality of a StringsSocket, but that require (for user friendliness) a slight modification to the socket color .

I don't mind doing this..

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/tree/color_nodes_v1

**Comment by zeffii** [comment]
first tests of dynamic socket colors..
![image](https://cloud.githubusercontent.com/assets/619340/21581304/bb355d90-d02c-11e6-9e91-f5dd4b3338a6.png)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21581319/d38dea0a-d02d-11e6-8af4-8e38ab9f2b3c.png)

**Comment by zeffii** [comment]
![xolgif](https://cloud.githubusercontent.com/assets/619340/21581593/0a31b5aa-d038-11e6-89fe-e0ef954eb1a4.gif)

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/21581810/298eb43a-d041-11e6-92be-63e454ecc67a.png)

**Comment by zeffii** [comment]
i think the color socket data will need an extra socket.property to describe the kind of color space..  not sure if the color socket needs the UI element to allow picking a color,, a separate node might be just as good..?

**Comment by zeffii** [comment]
this because I'm not currently passing around the color data as a `Color()` instance..

**Comment by zeffii** [comment]
i'm considering using the `Color()` class to transfer color data.

what?! :)

**Comment by zeffii** [comment]
meh, never!
```python
                                       # rgb, etc,                 # components
self.outputs['Colors'].sv_set({'kind': self.selected_mode, 'data': series_vec})
```

**Comment by zeffii** [comment]
![colzgif](https://cloud.githubusercontent.com/assets/619340/21581970/6a4bca8e-d047-11e6-99a7-3640bdb8fab9.gif)

**Comment by ly29** [comment]
Nice, would be good with a graphic color picker as well.

**Comment by enzyme69** [comment]
Nice one Zeffii, we can now do Sorting and Filtering of RGB colors. Sorting
is an interesting one, I reckon.

**Comment by zeffii** [comment]
> we can now do Sorting and Filtering of RGB colors.

hold on.. these nodes aren't functional yet.

**Comment by zeffii** [comment]
I think `sv_get` between  `color(c)->vertices(v)` or `color(c)->lists(s)` will need a conversion step to take the data from the color dict..

**Comment by zeffii** [comment]
likewise, `vertices(v)->color(c)` ,  `lists(s)->color(c)` would also need such a step to transform their data into a dict...

**Comment by zeffii** [comment]
the problem i have is that FloatVectorProperty won't let us limit min/max per component, this is ok for RGB, HSV, HSL,  but will be problematic for YIQ because I and Q have a range between [-1, 1].

**Comment by ly29** [comment]
The sane thing would probably to use RGB (or RGBA?) internally but allow different inputs types.
Then it would be simpler to use it. Compare with cycles

**Comment by zeffii** [comment]
@ly29  i'm probably mistaken (but possibly not) I think the cycles nodes for rgb have a dedicated RGBA color ui template.. for the 4 params. there's no RGBA subtype..

tempted to really make this atomic and just have a colorwheel node too, and keep it out of the socket.. but undecided, depends on taste ..

**Comment by ly29** [comment]
also, two float vector propties and switch when using YIQ? or skip YIQ, is it really that used?

**Comment by zeffii** [comment]
I am quite happy to ditch YIQ from prominence, and maybe offer a conversion node between spaces instead.

**Comment by ly29** [comment]
I want a color socket and that color data is like formatted like vertices. RGB is the format for color values by default but other colospaces are also allowed.

**Comment by zeffii** [comment]
A color socket is definitely more sane than hijacking the StringsSocket.  I tried StringsSocket, it worked but it felt icky.

**Comment by zeffii** [comment]
i'll make this today, but will hijack the StringsSocket.

**Comment by ly29** [comment]
If you use vertex like data I say use vertices otherwise stringssocket. 
It is the generic data type

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/22666666/d2c60e42-ecb9-11e6-8c42-40dc0b275f41.png)

**Comment by zeffii** [comment]
Yellow color socket is just an existing Edges/Polygons (StringsSocket) with a changeable socket-color property. 

current limitation - always have RGBA going through these yellow color sockets. and offer a conversion socket

![image](https://cloud.githubusercontent.com/assets/619340/22667387/d3baef4a-ecbc-11e6-8b14-c6ed88e8588b.png)

**Comment by enzyme69** [comment]
![screen shot 2017-02-19 at 22 06 53](https://cloud.githubusercontent.com/assets/3952687/23101781/c95dd35e-f6ef-11e6-9df5-a9eb998b68f2.png)

Brain is not so smart tonight, but I know I can **import colorsys** and convert HSV into RGB. SN Lite is cool, I just don't understand this fully yet.

Vectorization and Nestiness of Sverchok sometimes taken for granted:
- assign multiple inputs, expect multiple inputs
- loop happens automatically (?)



```
"""
in in_hsv v default=(1,0,0) n=1
out out_rgb v 
out out_rgba s 
"""
import colorsys as cs

out_rgb = cs.hsv_to_rgb(in_hsv[0][0], in_hsv[0][1], in_hsv[0][2])

out_rgba = [out_rgb[0], out_rgb[1], out_rgb[2], 1.0]

```

**Comment by enzyme69** [comment]
I am currently studying this example of Vectorize of SN Lite:
https://github.com/nortikin/sverchok/issues/1005

**Comment by enzyme69** [comment]
``` python
"""
in in_hsv v default=(1,0,0) n=1
out out_rgb v 
out out_rgba s 
inject
"""
import colorsys as cs

params = vectorize(in_hsv)

#out_rgb = cs.hsv_to_rgb(in_hsv[0][0], in_hsv[0][1], in_hsv[0][2])
#out_rgba = [out_rgb[0], out_rgb[1], out_rgb[2], 1.0]

# points = [FlowerCurve(*param_set) for param_set in zip(*params)]



out_rgb = [ cs.hsv_to_rgb(*param_set) for param_set in zip(*params) ]
#points = [FlowerCurve(*param_set) for param_set in zip(*params)]

```

Still wrong, but brute force it....

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/23101915/33bbf15a-f69f-11e6-9a74-956e99041667.png)

```python
"""
in hue         s default=1.0 n=1
in saturation  s default=1.0 n=1
in value       s default=1.0 n=1
out out_rgb v 
inject
"""
import colorsys as cs

params = vectorize(parameters)
out_rgb = [cs.hsv_to_rgb(*param_set) for param_set in zip(*params)]

```

**Comment by zeffii** [comment]
keeping digging.

**Comment by enzyme69** [comment]
I see.. thanks Zeffii. I was heading this way. Vector Input and this param* was too much, but I noticed by simplifying the input as single and this sort of make sense.

**Comment by enzyme69** [comment]
I'll save the list comprehension for other time, but I think below works.

``` python
"""
in in_hue s d=1.0 n=1
in in_sat s d=1.0 n=1
in in_val s d=1.0 n=1
in in_alpha s d=1.0 n=1
out out_rgb v 
out out_rgba s
inject
"""
import colorsys as cs

params = vectorize(parameters)

#out_rgb = cs.hsv_to_rgb(in_hsv[0][0], in_hsv[0][1], in_hsv[0][2])
#out_rgba = [out_rgb[0], out_rgb[1], out_rgb[2], 1.0]

#print(params[0])

# in case it failed
out_rgb = [1,1,1]
out_rgba = [1,1,1,1]

# this is working
out_rgb = [cs.hsv_to_rgb(*param_set) for param_set in zip(params[0], params[1], params[2])]

out_rgba = []

for rgb in out_rgb:
    r,g,b = rgb
    out_rgba.append([r,g,b,in_alpha])
    

```

**Comment by enzyme69** [comment]
At least by doing this example, I understand the inject part a bit better. To  be continued...

**Comment by enzyme69** [comment]
[colorsys_005_2017_02_19_11_49.zip](https://github.com/nortikin/sverchok/files/785806/colorsys_005_2017_02_19_11_49.zip)

**Comment by enzyme69** [comment]
Additional revision. The vectorized Alpha is now used.

```python

"""
in in_hue s d=1.0 n=1
in in_sat s d=1.0 n=1
in in_val s d=1.0 n=1
in in_alpha s d=1.0 n=1
out out_rgb v 
out out_rgba s
inject
"""
import colorsys as cs

params = vectorize(parameters)

#out_rgb = cs.hsv_to_rgb(in_hsv[0][0], in_hsv[0][1], in_hsv[0][2])
#out_rgba = [out_rgb[0], out_rgb[1], out_rgb[2], 1.0]

#print(params[0])

# in case it failed
out_rgb = [1,1,1]
out_rgba = [1,1,1,1]

# this is working
out_rgb = [cs.hsv_to_rgb(*param_set) for param_set in zip(params[0], params[1], params[2])]

#print(params[3])

out_rgba = []

for num, rgb in enumerate(out_rgb):
    r,g,b = rgb
    out_rgba.append([r,g,b,params[3][num]])
    
```

**Comment by zeffii** [comment]
```
for num, (r,g,b) in enumerate(out_rgb):
    out_rgba.append([r,g,b,params[3][num]])
```

**Comment by zeffii** [comment]
i'll do some more to https://github.com/nortikin/sverchok/tree/colornodes

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/1253 pushed to beta nodes for now.

**Comment by zeffii** [comment]
i haven't fully worked out the use_alpha toggle  yet. 

f.ex: in the color_out node i want it to be able to drop the alpha channel even if the input contains alpha.. no time atm.

**Comment by zeffii** [comment]
maybe
```python
        values = [[], [], [], []]
            for obj in data:
                vals = (list(x) for x in zip(*obj))
                for idx, v in enumerate(vals):
                    values[idx].append(v)
            for i, socket in enumerate(self.outputs):
                if self.use_alpha:
                    if idx == 3:
                        break 
                else:
                    socket.sv_set([values][i])
```

**Comment by zeffii** [comment]
please continue conversion here. about the Beta Nodes. https://github.com/nortikin/sverchok/pull/1253
