### ISSUE TITLE
Real Instance and Variations (Color etc)

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#995]
If I were to use the Vertex Color New, will it be efficient coloring 10000 points or more? Cycles Vertex Color does not mind millions of points right? 

Another quick question related to above: with Dupli, we really cannot actually colorize each dupli with different color, can't we?

Ideally we need "Particle System" or maybe not really particle, just Point Instancing System that allows for variations of values.

In current Blender Particle System, I like the simplicity of using Group to do instancing and randomization. That's one thing I always use.

Sverchok wise, I can see Instancing that works like Instance Modifier. I can colorize it randomly using Cycles, but kind of needing a way to transfer Color from Sverchok per Object or per Instance.

I don't really like the limitation Dupli Instance, if it cannot be randomized in material or color or texture.

Object (real) is better.

What do you think? Sorry brain is going all over the place. Perhaps currently there are other more important priority in Sverchok, so this can wait.

**Comment by zeffii** [comment]
> If I were to use the Vertex Color New, will it be efficient coloring 10000 points or more? Cycles Vertex Color does not mind millions of points right?

Setting 10.000 vertex colors via python isn't too slow, but it's not instantaneous.

> Another quick question related to above: with Dupli, we really cannot actually colorize each dupli with different color, can't we?

If that's possible using bpy, then it would be possible in sverchok. I don't know if dupli's can be colored independantly via bpy, but particles _can_ be via cycles nodes.

> Ideally we need "Particle System" or maybe not really particle, just Point Instancing System that allows for variations of values.

unfortunately you are limited to what bpy allows, and on top of that limited to what someone else is willing to code for you. The latter is something you can work on by coding (more).

> In current Blender Particle System, I like the simplicity of using Group to do instancing and randomization. That's one thing I always use.

Here any limitation in Sverchok's exposure of particles / instancing is down to how well we (well, me....) know what the particle system can do. And how interested I am in the problem vs other problems.

> Sverchok wise, I can see Instancing that works like Instance Modifier. I can colorize it randomly using Cycles, but kind of needing a way to transfer Color from Sverchok per Object or per Instance.

I think you're hitting a limitation here, the particle system was not designed with nodification in mind. Sergey wants to replace it entirely, seems to me like you should speak up before/while they are redesigning that. 1) gather your thoughts 2) edit them, stream line them  then ask ton (who follows you on twitter) what to do with your ideas.

> I don't really like the limitation Dupli Instance, if it cannot be randomized in material or color or texture. Object (real) is better. What do you think? Sorry brain is going all over the place. Perhaps currently there are other more important priority in Sverchok, so this can wait.

the waiting game.

**Comment by zeffii** [comment]
could be discussed in [this thread instead](https://github.com/nortikin/sverchok/issues/983). because current instancer isn't likely going to see any updates.

**Comment by enzyme69** [comment]
​I guess I will use the hack a way =)
