### ISSUE TITLE
How to do a Spirograph?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#996]
I think it's weird that the setup become more complex that necessary.

My idea is like this:
1) Have a circle A
2) Duplicates all circles along circle B
3) Circle B should be rotating, while circle A duplicates also rotating around each axis, each with slight offset.
4) Step no.3 is simulating the Time Offset Duplication / Replication for Spirograph

I am totally stuck actually. 

I tried using Rotation Matrix failed. And I still don't understand how we can use Multiple Matrix to create this "orbiting pivot" matters.

**Comment by enzyme69** [comment]
The setup so far:
https://gist.github.com/f91e0e624d35700545506de8916c495c

**Comment by enzyme69** [comment]
Another try:
https://gist.github.com/3db4e9e7bcf3883275abd847b01d256d

**Comment by enzyme69** [comment]
I tried with line first:
https://gist.github.com/1f69ad86f94f484b9320617acde14dfa

![screen shot 2016-11-28 at 18 16 47](https://cloud.githubusercontent.com/assets/3952687/20659270/c4e1b1d2-b596-11e6-851f-41c29569d50b.png)

![like_sine](https://cloud.githubusercontent.com/assets/3952687/20659290/e3a0c64e-b596-11e6-920a-d12113e23e95.gif)

**Comment by enzyme69** [comment]
Heheh... still failed effort.

https://gist.github.com/10cf97f88093d16156d0d5dbd83c231d
![screen shot 2016-11-28 at 18 21 47](https://cloud.githubusercontent.com/assets/3952687/20659398/7266f290-b597-11e6-8686-4769bde3dafd.png)

Spirograph seems to be doing loop actually. Not just a single circle.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20659760/e8212700-b545-11e6-889a-0b6d3f648058.png)

https://gist.github.com/36324d4723607b3ca11a701b621e3832

you need more points

**Comment by enzyme69** [comment]
Seems like happening, but I think I forgot something:
https://gist.github.com/4c1c5ec01b3afee7176f71709cdd01b8

It's a bit off.

**Comment by enzyme69** [comment]
Ah... I think I got it. Interesting!

**Comment by zeffii** [comment]
you should probably update your version of sverchok, vector axis mk2 had a small change.

**Comment by zeffii** [comment]
i've wanted to make a unit-circle node for a while.. I might, because it always comes up in some form or another
```
    [ unit circle * r ]
    +-----------------+ 
    |       (x) * r   o
    |       (y) * r   o
    o  * pi           |
    o  r              |
    -------------------

```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20662821/63c4b08e-b555-11e6-959e-24d68bc05fb4.png)

https://gist.github.com/06f77975c5db6e85caed2438ed466f48

**Comment by nortikin** [comment]
https://gist.github.com/3fd82117d69c853d726438250fb641fa
not sure is ok

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20671329/2e231060-b57d-11e6-9776-4d3ffb29ee0a.png)
https://gist.github.com/3f0c7eacd9011708e947ac46442220c6

**Comment by enzyme69** [comment]
Thanks a lot for suggestion and bonus example and explanation as always @zeffii  This is great study. Lots of things happening with such simple Spirograph case. It's like a Loop, but with offset. But a lot more.

Hey is the Script Node Mini ready?

**Comment by enzyme69** [comment]
For me as artist that is leaning technical stuff using add-on like Sverchok in Blender, this kind of thing made available is impressive. 

I know that it can be done in many apps in different way. But the satisfaction of creating something out of nothing using Math Formula is nice.

I know I am milking this Spirograph just about right. Maybe can be more.

**Comment by zeffii** [comment]
> Hey is the Script Node Mini ready?

`SN Lite` is in master. in Generators / Generators Extended.

[Please consult the preliminary docs](https://github.com/nortikin/sverchok/issues/942) for usage.
