### ISSUE TITLE
A value interpolation?

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#998]
![screen shot 2016-11-28 at 20 31 33](https://cloud.githubusercontent.com/assets/3952687/20662934/b6f7efb0-b5a9-11e6-9040-ef186831cb7a.png)

I just realized we don't have "float interpolation" in Sverchok? Something that I noticed in AN: Animate Nodes and Mix Nodes. 

Sverchok has Vector and Matrix interpolation. However, if we just want to "interpolate" value, we need to use Vector I supposed? I will try.

**Comment by enzyme69** [comment]
![screen shot 2016-11-28 at 20 34 36](https://cloud.githubusercontent.com/assets/3952687/20663020/195f0378-b5aa-11e6-9d80-b2510c9a27b8.png)

**Comment by enzyme69** [comment]
However, this does not work ... Maybe Rotation Matrix node is not vectorized?
https://gist.github.com/e90764249ac1fc778d8d08848b84d092

**Comment by enzyme69** [comment]
Getting somewhere, but problem with pivot:
https://gist.github.com/4bcd412538f7e17fb026075f2d343805

**Comment by enzyme69** [comment]
![screen shot 2016-11-28 at 20 45 32](https://cloud.githubusercontent.com/assets/3952687/20663449/a06450a2-b5ab-11e6-9855-a1292abf9f41.png)

**Comment by zeffii** [comment]
the `remap` node would do the trick.

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/20663863/4afe5006-b559-11e6-9975-d4816f5cdda8.png)

it's essential an interpolation node with extra features.

**Comment by enzyme69** [comment]
Ah, I thought about that.

I am up to here. 
https://gist.github.com/5c0787e635f0b65dbef5b7a3d80984c1

Something is not right with Rotation node. 

Moving pivot of transform is not trivial.

**Comment by zeffii** [comment]
closing this issue because the title 'Value Interpolation'  is possible with map range.

if you have a question about the Rotation node, I suggest making a smaller layout which contains as few nodes as possible to demonstrate the problem.

**Comment by enzyme69** [comment]
Got it~
