### ISSUE TITLE
Object Remote Control

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#999]
the question is do we need store recreate objects matrices world to make remote control based on their original matrices?

this makes some boom and dance in particles, but we can make boom from original user-defined positions.   It is more of animation. Or leave it for AN to solve such things?
https://yadi.sk/d/IOjcL7DbzkbYB
this example
theme #999

**Comment by enzyme69** [comment]
Well, I thought about this the other day:
- Sverchok MK2 can output Bmesh MK2 "real objects". This object has transform information, that I wish can connect link to original object, providing no bad cyclic dependency.

Sverchok BMesh MK2 can be used to control original object using Animation Nodes, providing no bad cyclic dependency.

**Comment by nortikin** [comment]
AN handle it better anyway. Lets make more generating geometry

**Comment by enzyme69** [comment]
@nortikin Ok coolio~
